### PR TITLE
Fix detection of new dev service model changes for situations when service config is a constant

### LINKED ISSUE #52525: New dev services model contract (javadoc) for service config equals (when to restart) isn't implemented correctly
### Describe the bug

I am opening this even though I added a test for Keycloak Dev Services which proves otherwise and I don't have time right now to create a reproducer, but still. Here `io.quarkus.deployment.builditem.DevServicesResultBuildItem.OwnedServiceBuilder#serviceConfig` javadoc says:

```
If you want it to be always restarted on live reloads, you could pass through something like a
random number. If you want the service to never be restarted, you could pass through a constant.
```

while I inspected everywhere is the service config used and it seems to be propagated to `ComparableDevServicesConfig` and nowhere else. But for service config, the equals only works correctly if it is a config mapping. So I think it cannot work properly for constants equals and hence, unnecessary restarts.

### Expected behavior

`io.quarkus.devservices.crossclassloader.runtime.ComparableDevServicesConfig#reflectiveEquals` should consider non-config mappings

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Mandrel or GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by michalvavrik**
* Closes: https://github.com/quarkusio/quarkus/issues/52525

### CODE REVIEW

File: core/runtime/src/main/java/io/quarkus/devservices/crossclassloader/runtime/ComparableDevServicesConfig.java [hunk 1]
```diff
@@ -83,7 +87,10 @@ private static boolean reflectiveEquals(Object config, Object otherConfig) {
                 otherClazz = otherClazz.getSuperclass();
 
             }
-            return true;
+            if (foundConfigInterface) {
+                return true;
+            }
```
Comment (holly-cummins) [inline core/runtime/src/main/java/io/quarkus/devservices/crossclassloader/runtime/ComparableDevServicesConfig.java:92]: I think this isn't right. It seems to be saying that the deep compare of two config interfaces will always return true? 

I wasn't sure if I was reading right, since it's my lunchtime and I'm rather hungry, so picked up your changes and I added a few more tests to the test.

``` 

    @Test
    public void wrappersWrappingDifferentConfigObjectsShouldNotBeEqual() {
        DevServiceOwner owner = new DevServiceOwner("someextension", LaunchMode.TEST.name(), configName);
        DummyDevServicesConfig globalConfig1 = new DummyDevServicesConfig("b", 3);
        DummyExtensionConfig config1 = new DummyExtensionConfig("a", 1);
        DummyDevServicesConfig globalConfig2 = new DummyDevServicesConfig("b", 3);
        DummyExtensionConfig config2 = new DummyExtensionConfig("b", 1);
        assertNotEquals(new ComparableDevServicesConfig(uuid, owner, globalConfig1, config1),
                new ComparableDevServicesConfig(uuid, owner, globalConfig2, config2));
    }

    @Test
    public void wrappersWrappingDifferentGlobalConfigObjectsShouldNotBeEqual() {
        DevServiceOwner owner = new DevServiceOwner("someextension", LaunchMode.TEST.name(), configName);
        DummyDevServicesConfig globalConfig1 = new DummyDevServicesConfig("z", 3);
        DummyExtensionConfig config1 = new DummyExtensionConfig("a", 1);
        DummyDevServicesConfig globalConfig2 = new DummyDevServicesConfig("b", 3);
        DummyExtensionConfig config2 = new DummyExtensionConfig("b", 1);
        assertNotEquals(new ComparableDevServicesConfig(uuid, owner, globalConfig1, config1),
                new ComparableDevServicesConfig(uuid, owner, globalConfig2, config2));
    }
```

The new tests failed, and I was all pleased that I managed to read code with low blood sugar. Then I stashed your changes, ran the tests, and ... they still fail. 

So now I'm worried that there's two bugs in the original implementation.

Comment (michalvavrik) [reply core/runtime/src/main/java/io/quarkus/devservices/crossclassloader/runtime/ComparableDevServicesConfig.java:92]: > I think this isn't right. It seems to be saying that the deep compare of two config interfaces will always return true?

well, that wasn't the concern I am fixing. I can look at it, but my code should keep what was there before. Do you read it differently? So while I agree, it is there just to keep previous behavior for config interfaces.

Comment (michalvavrik) [reply core/runtime/src/main/java/io/quarkus/devservices/crossclassloader/runtime/ComparableDevServicesConfig.java:92]: > So now I'm worried that there's two bugs in the original implementation.

It is definitely possible. Honestly, I only isolated change that I need for constants without looking into current logic because it didn't seem relevant. I can investigate, but it seems like you know about other scenarios more than I do.

Comment (michalvavrik) [reply core/runtime/src/main/java/io/quarkus/devservices/crossclassloader/runtime/ComparableDevServicesConfig.java:92]: > I think this isn't right. It seems to be saying that the deep compare of two config interfaces will always return true?

there is other equals btw in the loop

Comment (holly-cummins) [reply core/runtime/src/main/java/io/quarkus/devservices/crossclassloader/runtime/ComparableDevServicesConfig.java:92]: Ahh, I've had lunch and I see the intention. That `if (foundConfigInterface)` is guarding a `return true`, so it's making it less likely to return true, not more. 

I'm still worried about the tests I just wrote, but they're clearly orthogonal to this change, since they fail with and without your changes (and, in fact, when I look at them with the benefit of lunch, they might also turn out to be wrong). 

Thanks :)

**Review by holly-cummins — APPROVED** [review]
Thank you!

File: core/runtime/src/main/java/io/quarkus/devservices/crossclassloader/runtime/ComparableDevServicesConfig.java (hunk 1 above)
Comment (michalvavrik) [reply core/runtime/src/main/java/io/quarkus/devservices/crossclassloader/runtime/ComparableDevServicesConfig.java:92]: Sure, thanks for looking into it as well.
