### PR TITLE
Disable DevService if docker is not running

### LINKED ISSUE #16904: Devservices must disabled themself if docker is not installed
## Description

Currently, when docker is not installed, devservices that is enabled by default try to launch a database and fails with the following error : 

```
2021-04-28 20:45:25,128 INFO  [org.tes.doc.DockerMachineClientProviderStrategy] (build-11) docker-machine executable was not found on PATH (...)
2021-04-28 20:45:55,371 ERROR [org.tes.doc.DockerClientProviderStrategy] (build-11) Could not find a valid Docker environment. Please check configuration. Attempted configurations were:
2021-04-28 20:45:55,372 ERROR [org.tes.doc.DockerClientProviderStrategy] (build-11)     NpipeSocketClientProviderStrategy: failed with exception TimeoutException (Timeout waiting for result with exception). Root cause NoSuchFileException (\\.\pipe\docker_engine)
2021-04-28 20:45:55,372 ERROR [org.tes.doc.DockerClientProviderStrategy] (build-11) As no valid configuration was found, execution cannot continue
2021-04-28 20:45:55,377 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
```

This is not very developer friendly, it feels like Docker is needed for Quarkus dev mode and people may think the only way to solve this is to install docker.

See this Zulip thread for more detail: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Qarkus.20dev.20fails.20on.20new.20version

## Implementation ideas

Auto-disable devservices in case Docker is not installed.
The default error message will be displayed around datasource not configured.

### PR DESCRIPTION
**Pull request by glefloch**
This branch adds a check that looks for a running docker daemon. If it's not present, the `DevServicesDatasourceProcessor` build step is not triggered. 

close #16904

### CODE REVIEW

**Review by stuartwdouglas — CHANGES_REQUESTED** [review]
Can we also get a better error message that mentions that docker is an option: https://github.com/stuartwdouglas/quarkus/blob/e7fc52bf892d4507a42cacf1e418feb81c570b39/extensions/agroal/runtime/src/main/java/io/quarkus/agroal/runtime/DataSources.java#L126

Basically if you are in dev or test mode with a DS that supports it it should say 'configure the URL or get a working docker', while for prod mode or for DB's that don't support it the message should stay the same.

File: core/deployment/src/main/java/io/quarkus/deployment/util/DockerWorking.java [hunk 1]
```diff
@@ -11,8 +11,6 @@
 
 import org.jboss.logging.Logger;
 
-import io.quarkus.deployment.util.ExecUtil;
-
 public class DockerWorking implements BooleanSupplier {
```
Comment (gastaldi) [inline core/deployment/src/main/java/io/quarkus/deployment/util/DockerWorking.java:14]: Can you rename this class to `IsDockerRunning` to match the existing `BooleanSupplier` classes?

Comment (gastaldi) [reply core/deployment/src/main/java/io/quarkus/deployment/util/DockerWorking.java:14]: Also move it to the `io.quarkus.deployment` package

**Comment by glefloch** [comment]
Thanks for your reviews, I updated the code to address them :)

**Review by machi1990 — CHANGES_REQUESTED** [review]
Let's also disable it for the mongo extension dev services https://github.com/quarkusio/quarkus/blob/ba39f5d9fe4452294b70d727a2e1dccb7da21853/extensions/mongodb-client/deployment/src/main/java/io/quarkus/mongodb/deployment/DevServicesMongoProcessor.java#L39-L42

**Comment by glefloch** [comment]
@machi1990 done!

**Review by geoand — APPROVED** [review]
Looks nice, thanks!

**Review by machi1990 — APPROVED** [review]
LGTM

**Review by gastaldi — APPROVED** [review]
Great job!

**Review by stuartwdouglas — APPROVED** [review]

**Comment by glefloch** [comment]
I'm not sure the CI failure is related..

**Comment by gastaldi** [comment]
> I'm not sure the CI failure is related..

Doesn't seem to be
