### PR TITLE
Runtime artifact's POM repos aren't propagated to resolve the deployment deps

### LINKED ISSUE #3268: Runtime artifact's POM repos aren't propagated to resolve the corresponding deployment deps
**Describe the bug**
I'm testing camel extensions against the latest quarkus snapshot to validate the fix for https://github.com/quarkusio/quarkus/issues/3094 and when running the integration tests I see the following error:

```
[INFO] Running org.apache.camel.quarkus.core.CamelTest
[ERROR] Tests run: 3, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 28.218 s <<< FAILURE! - in org.apache.camel.quarkus.core.CamelTest
[ERROR] testProperties  Time elapsed: 0.008 s  <<< ERROR!
org.junit.jupiter.api.extension.TestInstantiationException: TestInstanceFactory [io.quarkus.test.junit.QuarkusTestExtension] failed to instantiate test class [org.apache.camel.quarkus.core.CamelTest]: Failed to create the boostrap class loader
Caused by: java.lang.IllegalStateException: Failed to create the boostrap class loader
Caused by: io.quarkus.bootstrap.BootstrapException: Failed to create the deployment classloader for org.apache.camel.quarkus:camel-quarkus-integration-test-core::jar:0.0.1-SNAPSHOT
Caused by: io.quarkus.bootstrap.resolver.AppModelResolverException: Failed to inject extension deployment dependencies for org.apache.camel.quarkus:camel-quarkus-integration-test-core:jar:0.0.1-SNAPSHOT
Caused by: io.quarkus.bootstrap.BootstrapDependencyProcessingException: No dependencies collected for Quarkus extension deployment artifact io.quarkus:quarkus-resteasy-deployment:jar:999-SNAPSHOT while at least the corresponding runtime artifact io.quarkus:quarkus-resteasy:jar:999-20190718.021121-60 is expected
```

**To Reproduce**
1. check-out https://github.com/lburgazzoli/apache-camel-quarkus/tree/test-packages
2. run `./mvnw clean install`

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
```
Linux mars 5.1.17-300.fc30.x86_64 #1 SMP Wed Jul 10 15:20:27 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
 - Output of `java -version`: 
```
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
```
 - GraalVM version (if different from Java): 
```
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-20190523183340.buildslave.jdk8u-src-tar--b03)
OpenJDK 64-Bit GraalVM CE 19.0.2 (build 25.212-b03-jvmci-19-b04, mixed mode)
```

 - Quarkus version or git rev: 
```
999-SNAPSHOT (from oss snapshot repo)
```

### PR DESCRIPTION
**Pull request by aloubyansky**
Fixes #3268

### CODE REVIEW

**Comment by aloubyansky** [comment]
@gsmet could you please review it for me? From previous experience I don't think anybody else will :) Thanks.

File: independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/resolver/maven/MavenArtifactResolver.java [hunk 1]
```diff
@@ -325,11 +341,20 @@ private CollectRequest newCollectManagedRequest(Artifact artifact, List<Dependen
...
-                .setRepositories(remoteRepoManager.aggregateRepositories(repoSession, remoteRepos, descr.getRepositories(), true));
+                .setRepositories(aggregateRepositories(repos, newResolutionRepositories(descr.getRepositories())));
+    }
+
+    public List<RemoteRepository> newResolutionRepositories(List<RemoteRepository> repos) {
+        return repos.isEmpty() ? Collections.emptyList() : repoSystem.newResolutionRepositories(repoSession, repos);
+    }
+
+    public List<RemoteRepository> aggregateRepositories(List<RemoteRepository> dominant, List<RemoteRepository> recessive) {
+        return dominant.isEmpty() ? recessive : remoteRepoManager.aggregateRepositories(repoSession, dominant, recessive, false);
```
Comment (gsmet) [inline independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/resolver/maven/MavenArtifactResolver.java]: In which case do we have dominant and recessive repositories?

Comment (aloubyansky) [reply independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/resolver/maven/MavenArtifactResolver.java]: That occurs naturally in any Maven project given that there is a hierarchy of POMs each of which may include repositories. Since during tests we, unfortunately, loose the Maven build context, we have to initialize repos the Maven way ourselves, taking the repos from the default settings and then merging them into the target project's repos. Repos from the project's POM will be dominating.
Another use-case is when we test/build an app from an external artifact (integration of external tests, for example). In that case, the project that integrates the external artifact is going to be dominating.

File: independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/resolver/BootstrapAppModelResolver.java [hunk 2]
```diff
@@ -134,68 +135,15 @@ public AppModel resolveManagedModel(AppArtifact appArtifact, List<AppDependency>
...
-    }
-
-    public void install(AppArtifact appArtifact, Path localPath) throws AppModelResolverException {
-        mvn.install(new DefaultArtifact(appArtifact.getGroupId(), appArtifact.getArtifactId(), appArtifact.getClassifier(),
-                appArtifact.getType(), appArtifact.getVersion(), Collections.emptyMap(), localPath.toFile()));
-    }
 
-    private AppModel injectDeploymentDependencies(AppArtifact appArtifact, DependencyNode root, List<Dependency> managedDeps) throws AppModelResolverException {
+        DependencyNode resolvedDeps = mvn.resolveManagedDependencies(toAetherArtifact(appArtifact),
+                directMvnDeps, managedDeps, managedRepos, devmode ? new String[] { "test" } : new String[0]).getRoot();
```
Comment (gsmet) [inline independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/resolver/BootstrapAppModelResolver.java]: Sorry to bother you with my dumb questions but trying to understand what's going on to make a real review :).

Why exactly do we exclude the test scope when in dev mode and not in the other modes?

**Comment by lburgazzoli** [comment]
@aloubyansky @gsmet anything missing to get this PR merged ?

**Comment by gsmet** [comment]
@lburgazzoli no sorry, I am at a F2F so available as time permits.

I just read Alexey's answer and it makes sense.

Alexey, just wondering if maybe we should add a bit more comments for the special cases in this code. Because you have everything in mind but we don't :) (and even for you, in 4 months, it might get tricky).

That being said, it can be done in a subsequent PR so let's not block this one.

**Review by gsmet — APPROVED** [review]
