### PR TITLE
Fix a regression in config doc generation

### LINKED ISSUE #32766: Issue with default values in config doc generation
There's something odd in this update: https://github.com/quarkiverse/quarkus-logging-splunk/pull/177/files , I need to have a look.

### PR DESCRIPTION
**Pull request by gsmet**
I introduced a regression withdefaultValueDocumentation for Lists and Optionals in recent changes.

Fixes #32766

### CODE REVIEW

File: core/processor/src/main/java/io/quarkus/annotation/processor/generate_doc/ConfigDocItemFinder.java [hunk 1]
```diff
@@ -141,8 +141,6 @@ private List<ConfigDocItem> recursivelyFindConfigItems(Element element, String r
         }
 
         for (Element enclosedElement : element.getEnclosedElements()) {
-            shouldProcessElement(enclosedElement);
-
```
Comment (gsmet) [inline core/processor/src/main/java/io/quarkus/annotation/processor/generate_doc/ConfigDocItemFinder.java:145]: This is useless, see the line below.

File: core/processor/src/main/java/io/quarkus/annotation/processor/generate_doc/ConfigDocItemFinder.java [hunk 2]
```diff
@@ -332,6 +330,10 @@ private List<ConfigDocItem> recursivelyFindConfigItems(Element element, String r
                                 acceptedValues = extractEnumValues(realTypeMirror, useHyphenateEnumValue,
                                         clazz.getQualifiedName().toString());
                                 configDocKey.setEnum(true);
+                            } else {
```
Comment (gsmet) [inline core/processor/src/main/java/io/quarkus/annotation/processor/generate_doc/ConfigDocItemFinder.java:333]: I prefer to keep the `else` as is rather than group in `else if` to have a proper separate case when the config type is not an enum.

**Review by radcortez — APPROVED** [review]
