### PR TITLE
fix: timezone mappings missing for Mysql JDBC driver in native mode

### LINKED ISSUE #5269: Timezone mappings missing for Mysql JDBC driver in native mode
**Describe the bug**
MySQL jdbc driver fails to create connection as timezone mapping in missing in native image. New connection fails with `com.mysql.cj.exceptions.WrongArgumentException: No timezone mapping entry for 'Etc/GMT'`

**Expected behavior**
Database connection to be created

**Actual behavior**
```
2019-11-07 00:38:09,507 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-worker-thread-0) HTTP Request to /owners/1 failed, error id: e5480ad3-242e-4408-b173-d29a8662c9b9-1: org.jboss.resteasy.spi.UnhandledException: javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection
	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106)
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:372)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:209)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:496)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:252)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:153)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:363)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:156)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:238)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:109)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatchRequestContext(VertxRequestHandler.java:84)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.lambda$handle$0(VertxRequestHandler.java:71)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:460)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
Caused by: javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
	at org.hibernate.internal.SessionImpl.find(SessionImpl.java:3355)
	at org.hibernate.internal.SessionImpl.find(SessionImpl.java:3293)
	at io.quarkus.hibernate.orm.runtime.entitymanager.TransactionScopedEntityManager.find(TransactionScopedEntityManager.java:143)
	at io.quarkus.hibernate.orm.runtime.entitymanager.ForwardingEntityManager.find(ForwardingEntityManager.java:42)
	at io.quarkus.hibernate.orm.panache.runtime.JpaOperations.findById(JpaOperations.java:196)
	at org.springframework.samples.petclinic.customers.model.OwnerRepositoryImpl.findById(OwnerRepositoryImpl.zig:337)
	at org.springframework.samples.petclinic.customers.model.OwnerRepositoryImpl.findById(OwnerRepositoryImpl.zig:320)
	at org.springframework.samples.petclinic.customers.model.OwnerRepositoryImpl_ClientProxy.findById(OwnerRepositoryImpl_ClientProxy.zig:533)
	at org.springframework.samples.petclinic.customers.web.PetResource.findOwner(PetResource.java:122)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:151)
	at org.jboss.resteasy.core.MethodInjectorImpl.lambda$invoke$3(MethodInjectorImpl.java:122)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:614)
	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1983)
	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:110)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:122)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:594)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:468)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:421)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:363)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:423)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:391)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invoke$1(ResourceMethodInvoker.java:365)
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:981)
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2124)
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:110)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:365)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:477)
	... 16 more
Caused by: org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:47)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:107)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:134)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.connection(StatementPreparerImpl.java:50)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:149)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:176)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:151)
	at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.prepareQueryStatement(AbstractLoadPlanBasedLoader.java:198)
	at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.executeQueryStatement(AbstractLoadPlanBasedLoader.java:162)
	at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.executeLoad(AbstractLoadPlanBasedLoader.java:104)
	at org.hibernate.loader.entity.plan.AbstractLoadPlanBasedEntityLoader.load(AbstractLoadPlanBasedEntityLoader.java:197)
	at org.hibernate.persister.entity.AbstractEntityPersister.load(AbstractEntityPersister.java:4350)
	at org.hibernate.event.internal.DefaultLoadEventListener.loadFromDatasource(DefaultLoadEventListener.java:569)
	at org.hibernate.event.internal.DefaultLoadEventListener.doLoad(DefaultLoadEventListener.java:537)
	at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:208)
	at org.hibernate.event.internal.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:332)
	at org.hibernate.event.internal.DefaultLoadEventListener.doOnLoad(DefaultLoadEventListener.java:108)
	at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:74)
	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:118)
	at org.hibernate.internal.SessionImpl.fireLoadNoChecks(SessionImpl.java:1168)
	at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:1157)
	at org.hibernate.internal.SessionImpl.access$2000(SessionImpl.java:197)
	at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.doLoad(SessionImpl.java:2795)
	at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.lambda$load$1(SessionImpl.java:2776)
	at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.perform(SessionImpl.java:2732)
	at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.load(SessionImpl.java:2776)
	at org.hibernate.internal.SessionImpl.find(SessionImpl.java:3326)
	... 44 more
Caused by: java.sql.SQLException: No timezone mapping entry for 'Etc/GMT'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:85)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:827)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:447)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:237)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199)
	at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:200)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:390)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:372)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:65)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 3 more
Caused by: com.mysql.cj.exceptions.WrongArgumentException: No timezone mapping entry for 'Etc/GMT'
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:85)
	at com.mysql.cj.protocol.a.NativeProtocol.configureTimezone(NativeProtocol.java:2153)
	at com.mysql.cj.protocol.a.NativeProtocol.initServerSession(NativeProtocol.java:2163)
	at com.mysql.cj.jdbc.ConnectionImpl.initializePropsFromServer(ConnectionImpl.java:1301)
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:958)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:817)
	... 13 more
```

**To Reproduce**
1. Create a project using `quarkus-jdbc-mysql` artefact 
2. generate native image
3. run native image
4. hit endpoint that retrieves data from mysql database.

### PR DESCRIPTION
**Pull request by machi1990**
Fixes #5269 

/cc @johnaohara

### CODE REVIEW

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/NativeConfig.java [hunk 1]
```diff
@@ -48,6 +48,12 @@
     @ConfigItem(defaultValue = "false")
     public boolean addAllCharsets;
 
+    /**
+     * If all timezones sets should be added to the native image. This increases image size
+     */
+    @ConfigItem(defaultValue = "false")
+    public boolean addAllTimeZones;
+
```
Comment (jaikiran) [inline core/deployment/src/main/java/io/quarkus/deployment/pkg/NativeConfig.java]: Hello @machi1990, does this mean the user will have to use `quarkus.native.add-all-time-zones` as the property in the `application.properties`?  If so, can we maybe just call it `enableAllTimezones`, so that they can consistently use `quarkus.native.enable-all-timezones`?

Comment (machi1990) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/NativeConfig.java]: Hi @jaikiran thanks for the quick review. 

> Hello @machi1990, does this mean the user will have to use `quarkus.native.add-all-time-zones` as the property in the `application.properties`? 

Yes

If so, can we maybe just call it `enableAllTimezones`, so that they can consistently use `quarkus.native.enable-all-timezones`?

+1. let me do the naming change.

I think
```
@ConfigItem(defaultValue = "false", name="nable-all-timezones")
public boolean addAllTimeZones;
```
Will do the job :-)

File: core/deployment/src/main/java/io/quarkus/deployment/builditem/NativeEnableAllTimeZonesBuildItem.java [hunk 2]
```diff
@@ -0,0 +1,7 @@
+package io.quarkus.deployment.builditem;
+
+import io.quarkus.builder.item.MultiBuildItem;
+
+public final class NativeEnableAllTimeZonesBuildItem extends MultiBuildItem {
```
Comment (gsmet) [inline core/deployment/src/main/java/io/quarkus/deployment/builditem/NativeEnableAllTimeZonesBuildItem.java]: I think I would name it `NativeImageEnableAllTimeZonesBuildItem` and also rename the other one (and maybe deprecate the old one: we have a nice mechanism to deal with these deprecations, see `DeprecatedBuildItemProcessor`).

Saying so because all the other native image related build items are prefixed with `NativeImage` so better be consistent.

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/NativeConfig.java [hunk 3]
```diff
@@ -48,6 +48,12 @@
     @ConfigItem(defaultValue = "false")
     public boolean addAllCharsets;
 
+    /**
+     * If all timezones sets should be added to the native image. This increases image size
```
Comment (gsmet) [inline core/deployment/src/main/java/io/quarkus/deployment/pkg/NativeConfig.java]:
```suggestion
     * If all timezones sets should be added to the native image. This increases image size.
```

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/NativeConfig.java (hunk 1 above)
Comment (gsmet) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/NativeConfig.java]: Well, `addAllCharsets` and `addAllTimeZones` should be consistent because they do the same thing.

I agree that having the build items and the config consistent would be nice. I don't have a strong opinion about keeping either.

@Sanne WDYT about what would be the best name?

Comment (Sanne) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/NativeConfig.java]: I'm not sure to expose this configuration attribute.

As I explained on the mailing list, there's many good reasons to _not_ have it here. I might be wrong, or I might be persuaded otherwise, but we could also simply start without having it and then add this later when there's better elements to decide.

Always easier to add things later than to remove it.

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java [hunk 4]
```diff
@@ -225,6 +227,11 @@ public NativeImageBuildItem build(NativeConfig nativeConfig, NativeImageSourceJa
             } else {
                 command.add("-H:-AddAllCharsets");
             }
+            if (nativeConfig.addAllTimeZones) {
+                command.add("-H:+IncludeAllTimeZones");
+            } else {
+                command.add("-H:-IncludeAllTimeZones");
```
Comment (gsmet) [inline core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java]: I wonder if it should be Optional and if we should do nothing if not defined.

Because it could not be defined in the config and then the user could override it with the additional build args.

**Review by gsmet — CHANGES_REQUESTED** [review]
I added a few comments and questions.

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/NativeConfig.java (hunk 1 above)
Comment (Sanne) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/NativeConfig.java]: P.S. actually I'm fairly sure we shouldn't expose this yet: at the very least we'll want to expose the option listing individual timezones, but we need to wait to be based on a GraalVM version which includes @jaikiran 's fixes

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java (hunk 4 above)
Comment (Sanne) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java]: GraalVM has the bad habit of adjusting their flags over time; setting them explicitly has been useful before.

But it's an interesting point that then the can't easily override it. Let's amit the explicit disablemnet until we introduce (later) a configuration option?

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/NativeConfig.java (hunk 1 above)
Comment (machi1990) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/NativeConfig.java]: +1 avec Sanne. I’ll remove the config.

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/NativeConfig.java (hunk 3 above)
Comment (machi1990) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/NativeConfig.java]: We can live without exposing the config for now. So this will be removed with my coming commit.

**Comment by geoand** [comment]
This will need a rebase to fix CI

File: core/deployment/src/main/java/io/quarkus/deployment/builditem/NativeEnableAllTimeZonesBuildItem.java (hunk 2 above)
Comment (machi1990) [reply core/deployment/src/main/java/io/quarkus/deployment/builditem/NativeEnableAllTimeZonesBuildItem.java]: done

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/NativeConfig.java (hunk 1 above)
Comment (machi1990) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/NativeConfig.java]: I have removed the config. We can expose it to users later based on @jaikiran GraalVM fixes.

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java (hunk 4 above)
Comment (Sanne) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java]: @machi1990 could you remove the `command.add("-H:-IncludeAllTimeZones");` line to follow @gsmet 's suggestion?

Comment (Sanne) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java]: Sorry I realize all the typos in my previous comment made it unclear :)

**Comment by Sanne** [comment]
Thanks looks great, and I verified it works. I've added a very minor comment which you might want to address - but no strong opinion, I could merge it as-is if you prefer keeping that.

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java (hunk 4 above)
Comment (machi1990) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java]: Thanks for bringing this one, I had previously forgotten about it. I have pushed a new version without it @gsmet @Sanne

**Comment by machi1990** [comment]
> Thanks looks great, and I verified it works. I've added a very minor comment which you might want to address - but no strong opinion, I could merge it as-is if you prefer keeping that.

Hey @Sanne ping,  I have force pushed a change to incorporate @gsmet suggestion. I think this PR is good to go :-)

**Comment by Sanne** [comment]
thanks @machi1990 ! I'll test it now..

File: core/deployment/src/main/java/io/quarkus/deployment/builditem/substrate/DeprecatedBuildItemProcessor.java [hunk 5]
```diff
@@ -192,4 +194,9 @@
         }
         return newProps;
     }
+
+    @BuildStep
+    NativeImageEnableAllCharsetsBuildItem enableAllCharSets(List<NativeEnableAllCharsetsBuildItem> oldProps) {
```
Comment (gsmet) [inline core/deployment/src/main/java/io/quarkus/deployment/builditem/substrate/DeprecatedBuildItemProcessor.java]:
```suggestion
    NativeImageEnableAllCharsetsBuildItem enableAllCharsets(List<NativeEnableAllCharsetsBuildItem> oldProps) {
```

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java [hunk 6]
```diff
@@ -156,6 +157,8 @@ public NativeImageBuildItem build(NativeConfig nativeConfig, NativeImageSourceJa
                     nativeConfig.enableAllSecurityServices |= Boolean.parseBoolean(prop.getValue());
                 } else if (prop.getKey().equals("quarkus.native.enable-all-charsets") && prop.getValue() != null) {
                     nativeConfig.addAllCharsets |= Boolean.parseBoolean(prop.getValue());
+                } else if (prop.getKey().equals("quarkus.native.enable-all-timezones") && prop.getValue() != null) {
+                    enableAllTimeZones = Boolean.parseBoolean(prop.getValue());
```
Comment (gsmet) [inline core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java]: I don't think removing the configuration property here is the solution.

Let's tackle the issue now. I would rename `addAllCharsets` to `enableAllCharsets` in the `nativeConfig` and maybe deprecate the old property and still somehow support it.

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java [hunk 7]
```diff
@@ -225,6 +228,9 @@ public NativeImageBuildItem build(NativeConfig nativeConfig, NativeImageSourceJa
             } else {
                 command.add("-H:-AddAllCharsets");
             }
+            if (enableAllTimeZones) {
+                command.add("-H:+IncludeAllTimeZones");
```
Comment (gsmet) [inline core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java]: If we have a proper property then I suppose we can ad the `-` version too as the user will be able to override it.

**Review by gsmet — CHANGES_REQUESTED** [review]
I added a couple more comments.

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java (hunk 6 above)
Comment (machi1990) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java]: I see your point and I agree. I'd have preferred to do it in another PR, since it is mostly unrelated :-)

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java (hunk 7 above)
Comment (Sanne) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java]: Sure that's the plan, as soon as we have a better way to expose this configuration.

**Comment by Sanne** [comment]
many thanks @machi1990 , let's merge this. Sorry for the delay, I had an unfortunate combination of travel and some problems with my hardware.

**Comment by Sanne** [comment]
@gsmet I see you blocked the merge. Are you ok to lift that? it's good to go IMO, we can polish further at another round.

**Review by Sanne — APPROVED** [review]

**Comment by machi1990** [comment]
Just rebased with master to fix CI failure.

**Comment by machi1990** [comment]
> many thanks @machi1990 , let's merge this. Sorry for the delay, I had an unfortunate combination of travel and some problems with my hardware.

Thanks @Sanne , no problem.

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
I suppose we can tweak things in a subsequent PR. But I really would like things to be symmetrical between charsets and timezones because it's exactly the same thing.

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java (hunk 6 above)
Comment (machi1990) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java]: > I don't think removing the configuration property here is the solution.
> 
> Let's tackle the issue now. I would rename `addAllCharsets` to `enableAllCharsets` in the `nativeConfig` and maybe deprecate the old property and still somehow support it.

I'll create an issue for this.

**Comment by Sanne** [comment]
thanks @gsmet and @machi1990 . Sure we can aim for a "symmetrical" solution, we can get there one step at a time :)
