### PR TITLE
Fix Arc request context state restoration on Vert.x duplicated context which allows to support security events in gRPC

### LINKED ISSUE #38159: Investigate request context activation/deactivation in grpc interceptor
This is a follow up to https://github.com/quarkusio/quarkus/issues/37741 where we didn't resolve the behavior in grpc.

The examples in the above issue are still valid (except the first one which was already addressed) and @michalvavrik has a branch with them over at https://github.com/michalvavrik/quarkus/tree/feature/grpc-event-observer-repro.

We should look into what's happening with req. context activation/deactivation and context state in these scenarios.
The issue seems to be with `VertxCurrentContext#remove` never really removing req. context which, in cases of manual context deactivation, leads to req. context permanently appearing to be active.

### PR DESCRIPTION
**Pull request by michalvavrik**
fixes: #38159

`io.quarkus.arc.runtime.context.ArcContextProvider.ContextSnapshot#begin` activated new  request context because `io.quarkus.arc.InjectableContext#getStateIfActive` returned deactivated request state. This way, when firing of security events activated request context, the context arrived activate to `io.quarkus.grpc.runtime.supports.context.GrpcRequestContextGrpcInterceptor#interceptCall` and gRPC auth tests were failing.

This PR enables security events for gRPC because it's also the only reproducer I have.

### CODE REVIEW

File: independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl/RequestContext.java [hunk 1]
```diff
@@ -172,7 +172,7 @@ public ContextState getState() {
     }
 
     public ContextState getStateIfActive() {
-        return currentContext.get();
+        return isActive() ? currentContext.get() : null;
```
Comment (mkouba) [inline independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl/RequestContext.java:175]: I think that it would be better to do something like:
```java
ContextState state = currentContext.get();
return state != null ? state.isValid() : false;
```

Comment (michalvavrik) [reply independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl/RequestContext.java:175]: oki, np

Comment (michalvavrik) [reply independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl/RequestContext.java]: done

**Review by manovotn — COMMENTED** [review]
Seems correct from ArC standpoint - this looks like an oversight from when we added context state invalidation handling and didn't adjust the check. Let's see what CI has to say.

**Comment by michalvavrik** [comment]
I don't think `DevMojoIT.testThatNewResourcesAreServed` is related, especially as there are no JDK 21 failures.

**Comment by michalvavrik** [comment]
@sberyozkin please review security events part

**Comment by manovotn** [comment]
> I don't think `DevMojoIT.testThatNewResourcesAreServed` is related, especially as there are no JDK 21 / 17 failures.

Yep, it's green after rerun 👍

**Review by manovotn — APPROVED** [review]
Thanks for digging into the grpc bits and spotting this!

**Review by mkouba — APPROVED** [review]

**Review by sberyozkin — APPROVED** [review]
Thanks @michalvavrik
