### PR TITLE
Knative fixes

### LINKED ISSUE #10823: Redeploying knative resources fails
**Describe the bug**
Knative adds annotations to the deployed service. The action of redeploying is triggering an update, that is removing these labels. Knative doesn't accept that because these labels are considered immutable.

So, we should delete and redeploy instead.

### PR DESCRIPTION
**Pull request by iocanel**
Resolves: #10823 #8659 

The pull requests adds two fixes. The #10823 is a new one I discovered last week, but #8659 is a resolved one, that I just realized that was partially fixed.

### CODE REVIEW

**Comment by gsmet** [comment]
Running CI again, there were infra issues during the run.

**Review by geoand — APPROVED** [review]

File: extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/KubernetesDeployer.java [hunk 1]
```diff
@@ -168,7 +168,11 @@ private DeploymentResultBuildItem deploy(DeploymentTargetEntry deploymentTarget,
         try (FileInputStream fis = new FileInputStream(manifest)) {
             KubernetesList list = Serialization.unmarshalAsList(fis);
             distinct(list.getItems()).forEach(i -> {
-                client.resource(i).inNamespace(namespace).createOrReplace();
+                if ("knative".equals(deploymentTarget.getName().toLowerCase())) {
```
Comment (gsmet) [inline extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/KubernetesDeployer.java:171]: Very minor but is there a reason why you use a string here rather than using the `KNATIVE` constant as below?

Comment (geoand) [reply extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/KubernetesDeployer.java:171]: Indeed, @iocanel can you fix this so we can merge?

**Review by geoand — APPROVED** [review]
