### PR TITLE
Fix Oracle DevService JDBC pattern

### LINKED ISSUE #48090: Devservices compose using oracle database construct wrong jdbc url
### Describe the bug

When using devservices compose with an oracle database using image gvenzl/oracle-free:23-slim-faststart the generated jdbc url is wrong and contains extra // like so : oracle:thin://@host:1521/db.

### Expected behavior

Devservices compose should generate the correct url for an oracle database like so : oracle:thin:@host:1521/db.

### Actual behavior

The generated jdbc or reactive url is wrong and the application cannot establish a connection.

Using quarkus:dev I get the error : 
Caused by: java.sql.SQLException: ORA-17067: Invalid Oracle URL specified

### How to Reproduce?

https://github.com/theCat69/quarkus-minimal-reproducer-oradb-dc

### Output of `uname -a` or `ver`

MSYS_NT-10.0-19045 DESKTOP-RSNRORB 3.5.4-0bc1222b.x86_64 2024-12-05 09:27 UTC x86_64 Msys

### Output of `java -version`

openjdk version "21.0.1" 2023-10-17 OpenJDK Runtime Environment (build 21.0.1+12-29) OpenJDK 64-Bit Server VM (build 21.0.1+12-29, mixed mode, sharing)

### Quarkus version or git rev

3.22.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.9

### Additional information

There is an issue in the code of OracleDatasourceServiceConfigurator class. The jdbc url and thus the reactive url are based on this string : "jdbc:%s://@%s:%d/%s%s". However it should be based on this string : "jdbc:%s:@%s:%d/%s%s".

### PR DESCRIPTION
**Pull request by gastaldi**
Tested against the reproducer provided in the issue description and it worked

- Fixes #48090

### CODE REVIEW

**Comment by gastaldi** [comment]
@theCat69 can you build this PR locally and let us know if that works for you ?

**Review by yrodiere — COMMENTED** [review]
LGTM, thanks.

Interestingly, it looks like the cause of the problem is moving away from `container.getEffectiveJdbcUrl()` in https://github.com/quarkusio/quarkus/commit/74bbe72eb06cbf5aaf47d0f342cb25ab9a08f8b7#diff-b7811d55c99ddb3f4876d1ab938bddf5c76ad43014bed43e7f98168ca5253206L92
I wonder why this was necessary... @ozangunalp might know?

**Comment by yrodiere** [comment]
Also, relatedly, we'd definitely need #44124 so that we catch that kind of problem earlier :/

File: extensions/devservices/oracle/src/main/java/io/quarkus/devservices/oracle/deployment/OracleDatasourceServiceConfigurator.java [hunk 1]
```diff
@@ -36,7 +36,7 @@ public RunningDevServicesDatasource composeRunningService(ContainerAddress conta
     }
 
     public String getJdbcUrl(ContainerAddress containerAddress, String databaseName) {
-        return "jdbc:%s://@%s:%d/%s%s".formatted(
+        return "jdbc:%s:@%s:%d/%s%s".formatted(
```
Comment (gsmet) [inline extensions/devservices/oracle/src/main/java/io/quarkus/devservices/oracle/deployment/OracleDatasourceServiceConfigurator.java:39]: What bugs me is that I fixed it at some point here: https://github.com/quarkusio/quarkus/commit/45d4db21c224cc9c9a0811b130e1de94fd51cb00 .

So either it got lost in translation or it was changed for a reason.

**Comment by brunobat** [comment]
> I am investigating, but it also looks like `db.connection_string` is a deprecated attribute in OTEL, and was replaced by `server.address` and `server.port`, but @brunobat knows more

Kind of... We get this data from the `opentelemetry-jdbc` instrumentation library. Even if  `server.address` and `server.port` can be used here, `db.connection_string` is being used instead. Probably because there is no mapping for the `oracle:thin:` part of the address.

**Comment by theCat69** [comment]
> @theCat69 can you build this PR locally and let us know if that works for you ?

I found time this morning to test my code against this PR and it works for both the minimal reproducer and my specific use case.
Thank you !

**Comment by ozangunalp** [comment]
> LGTM, thanks.
> 
> Interestingly, it looks like the cause of the problem is moving away from `container.getEffectiveJdbcUrl()` in [74bbe72#diff-b7811d55c99ddb3f4876d1ab938bddf5c76ad43014bed43e7f98168ca5253206L92](https://github.com/quarkusio/quarkus/commit/74bbe72eb06cbf5aaf47d0f342cb25ab9a08f8b7#diff-b7811d55c99ddb3f4876d1ab938bddf5c76ad43014bed43e7f98168ca5253206L92) I wonder why this was necessary... @ozangunalp might know?

The configurator is used to extract the JDBC URL from the running container, looking at it's env vars and labels. We cannot rely on `container.getEffectiveJdbcUrl()` because the container isn't started by test containers. 

@gsmet my mistake that this got overridden wrongly for Oracle DB. 

@gastaldi Although the recent correct URL seems like `jdbc:oracle:thin:@//<host>:<port>/<db_name>`, notice the `@//` not `//@`.

**Comment by gastaldi** [comment]
@ozangunalp I applied your suggestion. 
@theCat69 may I ask you to try this PR again? Thanks!

**Review by ozangunalp — APPROVED** [review]

File: extensions/devservices/oracle/src/main/java/io/quarkus/devservices/oracle/deployment/OracleDatasourceServiceConfigurator.java [hunk 2]
```diff
@@ -36,7 +36,7 @@ public RunningDevServicesDatasource composeRunningService(ContainerAddress conta
     }
 
     public String getJdbcUrl(ContainerAddress containerAddress, String databaseName) {
-        return "jdbc:%s://@%s:%d/%s%s".formatted(
+        return "jdbc:%s:@//%s:%d/%s%s".formatted(
```
Comment (gsmet) [inline extensions/devservices/oracle/src/main/java/io/quarkus/devservices/oracle/deployment/OracleDatasourceServiceConfigurator.java]: Are we sure about this? Because it's not in line with what we had before and it was working fine given nobody complained.

What we had before is: https://github.com/quarkusio/quarkus/commit/45d4db21c224cc9c9a0811b130e1de94fd51cb00 .

We really need to be extra sure.

Comment (gastaldi) [reply extensions/devservices/oracle/src/main/java/io/quarkus/devservices/oracle/deployment/OracleDatasourceServiceConfigurator.java]: I haven't tested, I trusted @ozangunalp on this :)

Comment (ozangunalp) [reply extensions/devservices/oracle/src/main/java/io/quarkus/devservices/oracle/deployment/OracleDatasourceServiceConfigurator.java]: I've checked here : https://docs.oracle.com/en/database/oracle/oracle-database/21/jajdb/oracle/jdbc/OracleDriver.html and on the intellij connection console. But I just saw that OracleContainer in test containers return URL without the `//`, so I don't think it makes a difference.

Comment (melloware) [reply extensions/devservices/oracle/src/main/java/io/quarkus/devservices/oracle/deployment/OracleDatasourceServiceConfigurator.java]: Not sure if it matters but I use Oracle everyday using a docker image and the URL is `jdbc:oracle:thin:@localhost:1521/freepdb1` with no `//` its the same image TestContainers uses...

Comment (gastaldi) [reply extensions/devservices/oracle/src/main/java/io/quarkus/devservices/oracle/deployment/OracleDatasourceServiceConfigurator.java]: I agree that it looks weird. I removed the `//` for now, let's keep with that
