### PR TITLE
Fix broken MongoClientBuildItem support

### LINKED ISSUE #7378: MongoClientBuildItem is never produced
**Describe the bug**
`MongoClientProcessor` has a `build` method which is supposed to produce `MongoClientBuildItem`(s) when the relevant Quarkus Mongo configuration is present. I never see the fields in `MongodbConfig` be anything other than `null`, hence the build items never get created.

Having `MongoClientBuildItem` available, is useful for other extensions like the Camel Mongo extension, where it can fetch the client and wire it into the relevant Camel component.

**Expected behavior**
If any of the Mongo configuration options are set, E.g `quarkus.mongodb.hosts` or `quarkus.mongodb.connection-string` then a `MongoClientBuildItem` should be produced.

**Actual behavior**
No `MongoClientBuildItem` ever seems to be produced, regardless of the Mongo configuration used.

**To Reproduce**
1. In your IDE, set a breakpoint in `MongoClientProcessor` at the start of the `build` method
2. Launch test `BookResourceTest` in debug mode
3. Observe conditions for creating `MongoClientBuildItem` are never satisfied

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #7378

### CODE REVIEW

**Comment by geoand** [comment]
There is one thing that needs to change however for `MongoClientBuildItem`.

The `value` of each `RuntimeValue` needs to become an optional instead of an actual client. The reason is that if the client is never injected into application code, the bean is never created.

**Comment by loicmathieu** [comment]
> The reason is that if the client is never injected into application code, the bean is never created.

This is the behaviour I will need to change ...

**Comment by geoand** [comment]
> > The reason is that if the client is never injected into application code, the bean is never created.
> 
> This is the behaviour I will need to change ...

Yes of course, but it's necessary, otherwise we need to make the beans unremovable which goes counter to the point of the optimization :)

**Comment by loicmathieu** [comment]
> we need to make the beans unremovable which goes counter to the point of the optimization :)

I don't really see the point of defining a mongoclient connection and not using it in the code. I don't think that bean removal should cover such case.

**Comment by geoand** [comment]
That's not the issue :wink: 

The issue is that code can use only the blocking client and not the reactive client. In that case, no bean will be created for the reactive client. Ditto if the opposite happens.

We definitely can make the beans unremoveable, but that goes counter to what the optimization actually is meant for

**Comment by loicmathieu** [comment]
> That's not the issue

That's mine, but I will look at it later, let stop the digression here :)

**Comment by geoand** [comment]
I am not hellbent on the optional thing, I'm just saying it's the proper thing to do. If it's too much of a hassle for the consumers of the Build Item to update, then we can make the bean unremovable :)

**Comment by loicmathieu** [comment]
@geoand in fact I just have an _enlightment_ (I don't know if it's the correct word). `@MongoClientName` as a base for removing bean is not suitable for my use case but I have the `@MongoEntity(clientName)` annotation so I should be able to define a `UnremovableBeanBuildItem` to tell Arc to avoid removing the client I need even if the `@MongoClientName` is not used ! This will fix my issue ! :tada:

**Comment by geoand** [comment]
Excellent 👌

File: extensions/mongodb-client/deployment/src/main/java/io/quarkus/mongodb/deployment/MongoClientProcessor.java [hunk 1]
```diff
@@ -365,21 +358,51 @@ BeanContainerListenerBuildItem build(
...
+        recorder.configureRuntimeProperties(codecProvider.getCodecProviderClassNames(),
+                bsonDiscriminator.getBsonDiscriminatorClassNames(), mongodbConfig);
+
+        for (String connectionName : resolveAllConnectionNamesFromConfig(config)) {
+            mongoClients.produce(new MongoClientBuildItem(recorder.getClient(connectionName),
+                    recorder.getReactiveClient(connectionName), connectionName));
+        }
+    }
+
+    private Set<String> resolveAllConnectionNamesFromConfig(ConfigurationBuildItem config) {
```
Comment (loicmathieu) [inline extensions/mongodb-client/deployment/src/main/java/io/quarkus/mongodb/deployment/MongoClientProcessor.java]: Why not using this new methods also in the `createMongoClientProducerBean`methods that do the same but based on Jandex ?

**Review by loicmathieu — CHANGES_REQUESTED** [review]

File: extensions/mongodb-client/deployment/src/main/java/io/quarkus/mongodb/deployment/MongoClientProcessor.java (hunk 1 above)
Comment (geoand) [reply extensions/mongodb-client/deployment/src/main/java/io/quarkus/mongodb/deployment/MongoClientProcessor.java]: That is an interesting idea! I went the way I did because that solution feels closer to the problem at hand. 
That said, I'll sleep on this idea and once the Camel folks respond with whether or not the whole idea works then I'll have settled :)

Comment (geoand) [reply extensions/mongodb-client/deployment/src/main/java/io/quarkus/mongodb/deployment/MongoClientProcessor.java]: Implemented

**Review by loicmathieu — APPROVED** [review]
LGTM but I will need to test it to see if it fixes my issue.
Maybe hold on to merge it untill I have time to test it (end of week)

**Comment by geoand** [comment]
The issue is we really need this for Camel. So I propose merging ASAP and then making any extra charges if necessary when you have the time to test

**Comment by loicmathieu** [comment]
I'm OK with this, I didn't saw prior to my comment that it fixes the issue for Camel.
So let's merge it, I'll give you feedback later on this.

**Comment by geoand** [comment]
Thanks

**Review by gsmet — APPROVED** [review]
I don't have the time to carefully review this so I'm gonna trust you on that one, considering it's blocking for Camel and CI is green.
