### PR TITLE
Let SmallRye Metrics interceptors do the metric registration

### LINKED ISSUE #1009: @Timed and @Metered metrics are not working
`@Timed` metric is not working, RuntimeException is thrown when accessing endpoint annotated with `@Timed`.

Repo: https://github.com/rsvoboda/protean-shamrock/tree/TimedMetricTest 
Test: https://github.com/rsvoboda/protean-shamrock/commit/00b7a4ab393d05649b67107568f6b80708297902

```java
Caused by: java.lang.RuntimeException: Cannot invoke method: 
  io.smallrye.metrics.interceptors.TimedInterceptor#timedMethod on 
  io.smallrye.metrics.interceptors.TimedInterceptor@c5e89ed
```
```java
Caused by: java.lang.IllegalStateException:
  No timer with name [proccessItemTimes] found in registry 
```

```java
ERROR: UT005023: Exception handling request to /metricsresource/process
org.jboss.resteasy.spi.UnhandledException: java.lang.RuntimeException: Cannot invoke method: io.smallrye.metrics.interceptors.TimedInterceptor#timedMethod on io.smallrye.metrics.interceptors.TimedInterceptor@c5e89ed
	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:103)
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:323)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:209)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:495)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:252)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:153)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:362)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:156)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:238)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:229)
	at org.jboss.shamrock.resteasy.runtime.ResteasyFilter$ResteasyResponseWrapper.sendError(ResteasyFilter.java:71)
	at io.undertow.servlet.handlers.DefaultServlet.doGet(DefaultServlet.java:173)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:686)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:791)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at org.jboss.shamrock.resteasy.runtime.ResteasyFilter.doFilter(ResteasyFilter.java:42)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.websockets.jsr.JsrWebSocketFilter.doFilter(JsrWebSocketFilter.java:173)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.opentracing.contrib.jaxrs2.server.SpanFinishingFilter.doFilter(SpanFinishingFilter.java:52)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:53)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:59)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.jboss.shamrock.undertow.runtime.UndertowDeploymentTemplate$7$1$1.call(UndertowDeploymentTemplate.java:358)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:364)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1998)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1525)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1382)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Cannot invoke method: io.smallrye.metrics.interceptors.TimedInterceptor#timedMethod on io.smallrye.metrics.interceptors.TimedInterceptor@c5e89ed
	at org.jboss.protean.arc.Reflections.invokeMethod(Reflections.java:101)
	at io.smallrye.metrics.interceptors.TimedInterceptor_Bean.intercept(Unknown Source)
	at org.jboss.protean.arc.InvocationContextImpl$InterceptorInvocation.invoke(InvocationContextImpl.java:263)
	at org.jboss.protean.arc.InvocationContextImpl.invokeNext(InvocationContextImpl.java:143)
	at org.jboss.protean.arc.InvocationContextImpl.proceed(InvocationContextImpl.java:167)
	at org.jboss.shamrock.example.metrics.MetricsResource_Subclass.proccessItem(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:152)
	at org.jboss.resteasy.core.MethodInjectorImpl.lambda$invoke$3(MethodInjectorImpl.java:123)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:614)
	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1983)
	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:110)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:123)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:543)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:418)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:372)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:362)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:374)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:343)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invoke$1(ResourceMethodInvoker.java:317)
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:981)
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2124)
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:110)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:317)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:476)
	... 54 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.protean.arc.Reflections.invokeMethod(Reflections.java:99)
	... 82 more
Caused by: java.lang.IllegalStateException: No timer with name [proccessItemTimes] found in registry [io.smallrye.metrics.MetricRegistries_ProducerMethod_getApplicationRegistry_3084f885749d4d534e6c1a0434dc45444ee9cbec_ClientProxy@6dd208f5]
	at io.smallrye.metrics.interceptors.TimedInterceptor.timedCallable(TimedInterceptor.java:75)
	at io.smallrye.metrics.interceptors.TimedInterceptor.timedMethod(TimedInterceptor.java:63)
	... 87 more
```

### PR DESCRIPTION
**Pull request by jmartisk**
Fixes #1009 and #1303

This change lets interceptors in SmallRye Metrics do the registration of metrics, so we don't anymore attempt to duplicate that logic in Quarkus. This also enables support for all remaining metrics that were not supported (Meter, Timer), fixes processing of metric tags and the `absolute` attribute.
Includes tests for all things that this resolves.

I realize this is not the best solution given the Quarkus philosophy, because this way metrics (from annotations) will NOT be initialized at build time, but at least this should be correct for the time being. Eagerly initializing metrics at Quarkus' side will require a lot of duplication of logic from SmallRye Metrics and will be very brittle with regard to changes in Metrics which can easily break everything.
So I would suggest we use this for now as the temporary solution until a more proper solution is found, which might require substantial changes in SmallRye as well... I will continue to research how to do it properly.

@rsvoboda @kenfinnigan

### CODE REVIEW

**Comment by jmartisk** [comment]
Can't say if the failures are my fault or what, does someone need to grant me access so that I can see the logs?

**Comment by gsmet** [comment]
@jmartisk 
- CI is now public so you will be able to see what's failing for your next builds
- the issue is a formatting issue: just run `mvn clean package` in the SmallRye metrics extension and it should reformat things automatically. Then you can amend your commit and push.

Thanks!

**Comment by jmartisk** [comment]
Thanks @gsmet, yes I can see the logs now.

**Comment by gsmet** [comment]
@jmartisk can you squash the 2 commits? Let's just not have one commit just for formatting fixes.

**Comment by jmartisk** [comment]
@gsmet A few days ago I got scolded in a different repository for squashing and force pushing which makes the history unreadable and that it can be squashed by the person who presses the green button :) but if you prefer me to squash right away for this repo, then no problem :)

File: extensions/smallrye-metrics/deployment/src/main/java/io/quarkus/smallrye/metrics/deployment/SmallRyeMetricsProcessor.java [hunk 1]
```diff
@@ -91,6 +90,32 @@ void beans(BuildProducer<AdditionalBeanBuildItem> additionalBeans) {
...
     }
 
+    @BuildStep
+    void annotationTransformers(BuildProducer<AnnotationsTransformerBuildItem> transformers) {
+        // attach @MetricsBinding to each class that contains any metric annotations
+        Collection<DotName> metricsAnnotations = new ArrayList<>();
+        metricsAnnotations.add(DotName.createSimple(Gauge.class.getName()));
+        metricsAnnotations.add(DotName.createSimple(Counted.class.getName()));
+        metricsAnnotations.add(DotName.createSimple(Timed.class.getName()));
+        metricsAnnotations.add(DotName.createSimple(Metered.class.getName()));
```
Comment (gsmet) [inline extensions/smallrye-metrics/deployment/src/main/java/io/quarkus/smallrye/metrics/deployment/SmallRyeMetricsProcessor.java]: Let's put them in a `private static final` list using `Arrays.asList`.

File: extensions/smallrye-metrics/deployment/src/main/java/io/quarkus/smallrye/metrics/deployment/SmallRyeMetricsProcessor.java [hunk 2]
```diff
@@ -91,6 +90,32 @@ void beans(BuildProducer<AdditionalBeanBuildItem> additionalBeans) {
...
+
+        transformers.produce(new AnnotationsTransformerBuildItem(ctx -> {
+            if (ctx.isClass()) {
+                // skip classes in package io.smallrye.metrics.interceptors
+                if (ctx.getTarget().asClass().name().prefix().equals(DotName.createSimple("io.smallrye.metrics.interceptors")))
+                    return;
```
Comment (gsmet) [inline extensions/smallrye-metrics/deployment/src/main/java/io/quarkus/smallrye/metrics/deployment/SmallRyeMetricsProcessor.java]: If the `DotName` are created with `createSimple()`, they might end up with a null prefix. I think you should get the name and `toString()` use `startsWith()`. I wonder if we should get the package name from one of the interceptor class instead of having it hardcoded?

File: extensions/smallrye-metrics/deployment/src/main/java/io/quarkus/smallrye/metrics/deployment/SmallRyeMetricsProcessor.java [hunk 3]
```diff
@@ -91,6 +90,32 @@ void beans(BuildProducer<AdditionalBeanBuildItem> additionalBeans) {
...
+        Collection<DotName> metricsAnnotations = new ArrayList<>();
+        metricsAnnotations.add(DotName.createSimple(Gauge.class.getName()));
+        metricsAnnotations.add(DotName.createSimple(Counted.class.getName()));
+        metricsAnnotations.add(DotName.createSimple(Timed.class.getName()));
+        metricsAnnotations.add(DotName.createSimple(Metered.class.getName()));
+
+        transformers.produce(new AnnotationsTransformerBuildItem(ctx -> {
+            if (ctx.isClass()) {
+                // skip classes in package io.smallrye.metrics.interceptors
+                if (ctx.getTarget().asClass().name().prefix().equals(DotName.createSimple("io.smallrye.metrics.interceptors")))
```
Comment (gsmet) [inline extensions/smallrye-metrics/deployment/src/main/java/io/quarkus/smallrye/metrics/deployment/SmallRyeMetricsProcessor.java]: Please add `{}` even for simple ifs.

File: extensions/smallrye-metrics/deployment/src/main/java/io/quarkus/smallrye/metrics/deployment/SmallRyeMetricsProcessor.java [hunk 4]
```diff
@@ -103,33 +128,12 @@ public void build(BeanContainerBuildItem beanContainerBuildItem,
         feature.produce(new FeatureBuildItem(FeatureBuildItem.SMALLRYE_METRICS));
 
         reflectiveClasses.produce(new ReflectiveClassBuildItem(false, false, Counted.class.getName()));
+        reflectiveClasses.produce(new ReflectiveClassBuildItem(false, false, Gauge.class.getName()));
+        reflectiveClasses.produce(new ReflectiveClassBuildItem(false, false, Timed.class.getName()));
+        reflectiveClasses.produce(new ReflectiveClassBuildItem(false, false, Metered.class.getName()));
```
Comment (gsmet) [inline extensions/smallrye-metrics/deployment/src/main/java/io/quarkus/smallrye/metrics/deployment/SmallRyeMetricsProcessor.java]: You could iterate on the constant list we extracted above.

File: extensions/smallrye-metrics/runtime/src/main/java/io/quarkus/smallrye/metrics/runtime/SmallRyeMetricsTemplate.java [hunk 5]
```diff
@@ -42,31 +41,6 @@
...
-        log.debugf("Register: %s", name);
-        registry.register(meta, new CounterImpl());
-        shutdown.addShutdownTask(new Runnable() {
-            @Override
-            public void run() {
-                registry.remove(name);
-            }
-        });
-    }
-
```
Comment (gsmet) [inline extensions/smallrye-metrics/runtime/src/main/java/io/quarkus/smallrye/metrics/runtime/SmallRyeMetricsTemplate.java]: We can address this comment in a follow-up PR. Let's get this one committed first as we have people asking for it.

Could you check why we have some metrics commented below? I suspect one of the reason is the usage of the MX pool but maybe we should use `ImageInfo` to disable them only if we are in native image mode.

I don't know about the CPU one though.

Having comments would help.

**Review by gsmet — CHANGES_REQUESTED** [review]
@jmartisk I added a couple of minor comments. Could you take care of them?

If you think my last one makes sense (the one about CPU and memory gauges) and you want to work on it, could you create a new issue?

Let's try to get this merged before our next release.

Thanks!

File: extensions/smallrye-metrics/runtime/src/main/java/io/quarkus/smallrye/metrics/runtime/SmallRyeMetricsTemplate.java (hunk 5 above)
Comment (jmartisk) [reply extensions/smallrye-metrics/runtime/src/main/java/io/quarkus/smallrye/metrics/runtime/SmallRyeMetricsTemplate.java]: I will look into it, reported https://github.com/quarkusio/quarkus/issues/1419 I don't have the permission to assign it to myself though.

**Comment by jmartisk** [comment]
Ok I pushed an amended commit addressing @gsmet's suggestions. If this gets merged I will create a new issue for investigating how to initialize as many metrics as possible eagerly at build time (obviously this can't be done for the ones created dynamically).

File: extensions/smallrye-metrics/deployment/src/main/java/io/quarkus/smallrye/metrics/deployment/SmallRyeMetricsProcessor.java (hunk 2 above)
Comment (jmartisk) [reply extensions/smallrye-metrics/deployment/src/main/java/io/quarkus/smallrye/metrics/deployment/SmallRyeMetricsProcessor.java]: I chose hard-coding because picking one particular interceptor class might create the impression to the reader that the code is related to that particular one :) but OK, I changed it to use the literal of `MetricsInterceptor`, it will be a bit safer

**Comment by gsmet** [comment]
@jmartisk I pushed a couple of minor adjustments I missed when reviewing. Will merge as soon as CI is green.

Thanks for your work!

**Review by gsmet — APPROVED** [review]
