### PR TITLE
InjectionPoint metadata - ignore java.lang.Deprecated...

### LINKED ISSUE #9242: Unable to run docker image + jdk 11 + maven +ubuntu
**Describe the bug**
Docker image built with `quarkus-container-image-docker` not working.

**Expected behavior**
Service should run with docker image

**Actual behavior**
Service failed when starting but works in dev mode .

**To Reproduce**
1. mvn clean package -Dquarkus.container-image.build=true
2. docker build -f src/main/docker/Dockerfile.jvm -t quarkus-service .
3. ocker run -it quarkus-service -p 9092:9092 -e QUARKUS_HTTP_PORT=9092

**Configuration**
```properties
# Add your application.properties here, if applicable.
# Configuration file
# key = value
quarkus.application.name=quarkus-service
quarkus.http.port=0

# Log
quarkus.log.level=DEBUG
quarkus.log.category."quarkus.mongodb".level=DEBUG
quarkus.log.category."org.springframework".level=DEBUG
quarkus.log.category."io.smallrye.jwt".level=DEBUG

# Spring Config
quarkus.spring-cloud-config.enabled=true
quarkus.spring-cloud-config.url=${SPRING_CLOUD_CONFIG_URL:http://localhost:8888/quarkus-service/quarkus?X-Encrypt-Key=${X_ENCRYPT_KEY}}

# JWT
mp.jwt.verify.publickey.location=${PUBLIC_KEY_PATH:/META-INF/resources/publicKey.pem}
quarkus.smallrye-jwt.enabled=true
#smallrye.jwt.verify.algorithm=${JWT_ALGORITHM:ES256}
mp.jwt.verify.requireiss=false
smallrye.jwt.path.groups=authorities

# Mongodb
quarkus.mongodb.connection-string=${MONGODB_URI:mongodb://localhost:27017}
quarkus.mongodb.database=${MONGODB_DATABASE:docker}
quarkus.mongodb.min-pool-size=${MONGODB_MIN_POOL_SIZE:10}
quarkus.mongodb.max-pool-size=${MONGODB_MAX_POOL_SIZE:50}

# Test
%test.security.oauth2.resource.jwt.keyValue=Mock
%test.quarkus.security.users.embedded.enabled=true
%test.quarkus.security.users.embedded.plain-text=true
%test.quarkus.security.users.embedded.users.admin=admin
%test.quarkus.security.users.embedded.roles.admin=ROLE_ADMIN
%test.quarkus.security.users.embedded.users.test=test
%test.quarkus.security.users.embedded.roles.test=ROLE_COMPANY_READ
%test.quarkus.spring-cloud-config.enabled=false
%test.quarkus.smallrye-jwt.enabled=false
%test.quarkus.mongodb.connection-string=mongodb://localhost:${EMBEDDED_MONGO_PORT}
%test.quarkus.mongodb.write-concern.journal=false
quarkus.http.test-port=0

# Build Native Image
#quarkus.native.additional-build-args=--initialize-at-run-time=io.quarkus.runner.ApplicationImpl
#quarkus.native.native-image-xmx=4g

# Docker
quarkus.container-image.group=
```

**Screenshots**
image

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
Linux XXX 5.4.0-29-generic #33-Ubuntu SMP Wed Apr 29 14:32:27 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: 
 - GraalVM version (if different from Java): 
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b06)
OpenJDK 64-Bit Server VM GraalVM CE 20.0.0 (build 25.242-b06-jvmci-20.0-b02, mixed mode)
 - Quarkus version or git rev: 
1.4.2.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
Apache Maven 3.6.3

**Additional context**
[Source Code](https://github.com/rodrigorodrigues/quarkus-rest-api-reactive-mongodb)

### PR DESCRIPTION
**Pull request by mkouba**
...when generating an injection point wrapper
- also fix ObserverGenerator InjectionPoint metadata support
- resolves #9242

### CODE REVIEW

File: independent-projects/arc/tests/src/test/java/io/quarkus/arc/test/metadata/InjectionPointMetadataTest.java [hunk 1]
```diff
@@ -103,9 +111,35 @@ public void testInjectionPointMetadata() {
...
+        assertTrue(annotatedParam.isAnnotationPresent(FooAnnotation.class));
+        assertTrue(annotatedParam.getAnnotation(Singleton.class) == null);
+        assertTrue(annotatedParam.getAnnotations(Singleton.class).isEmpty());
+    }
+
     @Singleton
     static class Controller {
 
+        @FooAnnotation
+        @Deprecated // This annotations should be ingnored
```
Comment (geoand) [inline independent-projects/arc/tests/src/test/java/io/quarkus/arc/test/metadata/InjectionPointMetadataTest.java:142]:
```suggestion
        @Deprecated // This annotations should be ignored
```

**Review by geoand — APPROVED** [review]
Aside from the typo I mentioned, LGTM

**Comment by mkouba** [comment]
@Ladicek @michalszynkiewicz could it be an intermittent failure?

> 2020-05-13T11:23:48.0780342Z [ERROR]   CircuitBreakerRetryTest>Arquillian.run:138->testCircuitOpenWithMultiTimeoutsAsync:487 serviceC should retry in testCircuitOpenWithMultiTimeouts on iteration 3

**Comment by Ladicek** [comment]
Is that in the MP FT TCK? I don't recall seeing such failure.

**Comment by mkouba** [comment]
> Is that in the MP FT TCK?

Yep, it is. Otherwise I wouldn't ping you ;-).

>  I don't recall seeing such failure.

So this PR is about ignoring `@Deprecated` when generating data for an `InjectionPoint`. And I don't think it should be related.

**Comment by Ladicek** [comment]
I agree that sounds quite unrelated. Let me check this out locally.

**Comment by Ladicek** [comment]
Hmm, I checked out your branch, built it, ran the MP FT TCK and it passed. Looks like the test is flaky, but as I said, I've never seen it fail...

**Comment by mkouba** [comment]
JDK Java 11 JVM Tests - the gradle plugin fails with:
```
2020-05-13T13:40:49.8457659Z [ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:exec (gradle) on project io.quarkus.gradle.plugin: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
2020-05-13T13:40:49.8459557Z org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:exec (gradle) on project io.quarkus.gradle.plugin: Command execution failed.
2020-05-13T13:40:49.8461676Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
```

The CI seems very unstable again :-(

**Comment by geoand** [comment]
> JDK Java 11 JVM Tests - the gradle plugin fails with:
> 
> ```
> 2020-05-13T13:40:49.8457659Z [ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:exec (gradle) on project io.quarkus.gradle.plugin: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
> 2020-05-13T13:40:49.8459557Z org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:exec (gradle) on project io.quarkus.gradle.plugin: Command execution failed.
> 2020-05-13T13:40:49.8461676Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
> ```
> 
> The CI seems very unstable again :-(

https://github.com/quarkusio/quarkus/pull/9265 should fix that one

**Review by manovotn — APPROVED** [review]

**Review by stuartwdouglas — APPROVED** [review]
