### PR TITLE
Register PGobject subtypes for reflection

### LINKED ISSUE #33206: Using duration with hibernate and postgres interval leads to error in native mode
### Describe the bug

Using hibernate with duration, which now with hibernate 6.2 uses the postgres interval type leads to an error due to `PGInterval` not correctly registered for reflection:

```
Caused by: org.postgresql.util.PSQLException: Failed to create object for: interval.
	at org.postgresql.jdbc.PgConnection.getObject(PgConnection.java:760)
	at org.postgresql.jdbc.PgResultSet.getObject(PgResultSet.java:3020)
	at io.agroal.pool.wrapper.ResultSetWrapper.getObject(ResultSetWrapper.java:472)
	at io.hypersistence.utils.hibernate.type.interval.PostgreSQLIntervalType.get(PostgreSQLIntervalType.java:40)
	at io.hypersistence.utils.hibernate.type.interval.PostgreSQLIntervalType.get(PostgreSQLIntervalType.java:24)
	at io.hypersistence.utils.hibernate.type.ImmutableType.nullSafeGet(ImmutableType.java:97)
	at org.hibernate.type.internal.UserTypeSqlTypeAdapter$ValueExtractorImpl.extract(UserTypeSqlTypeAdapter.java:110)
	at org.hibernate.sql.results.jdbc.internal.JdbcValuesResultSetImpl.readCurrentRowValues(JdbcValuesResultSetImpl.java:262)
	... 87 more
Caused by: java.lang.NoSuchMethodException: org.postgresql.util.PGInterval.<init>()
	at java.base@17.0.7/java.lang.Class.getConstructor0(DynamicHub.java:3585)
	at java.base@17.0.7/java.lang.Class.getDeclaredConstructor(DynamicHub.java:2754)
	at org.postgresql.jdbc.PgConnection.getObject(PgConnection.java:739)
	... 94 more
```

### Expected behavior

This probably should work out of the box as it is now in the standard hibernate implementation.

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

Mandrel 22.3.2.1

### Quarkus version or git rev

3.0.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradlew 8.1.1

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by marko-bekhta**
fixes https://github.com/quarkusio/quarkus/issues/33206

The original bug report is for `hypersistence` lib. And I'd suspect that it would be up to the lib users to register whatever it needs to function since we don't have an extension for it. But we could still get ourselves into a similar situation as ORM provides a `PostgreSQLIntervalSecondJdbcType` for a `Duration` mapping.

### CODE REVIEW

**Comment by yrodiere** [comment]
> And I'd suspect that it would be up to the lib users to register whatever it needs to function since we don't have an extension for it

+1 that's a job for the hypersistence Quarkus extension (if any).

File: extensions/jdbc/jdbc-postgresql/deployment/src/main/java/io/quarkus/jdbc/postgresql/deployment/PostgreSQLJDBCReflections.java [hunk 1]
```diff
@@ -20,6 +20,29 @@ void build(BuildProducer<ReflectiveClassBuildItem> reflectiveClass) {
...
+                "org.postgresql.geometric.PGbox",
+                "org.postgresql.geometric.PGcircle",
+                "org.postgresql.geometric.PGline",
+                "org.postgresql.geometric.PGlseg",
+                "org.postgresql.geometric.PGpath",
+                "org.postgresql.geometric.PGpoint",
+                "org.postgresql.geometric.PGpolygon",
+                // one more subtype of the PGobject, it doesn't look like that this one will be instantiated through reflection,
+                // but let's have it here anyway:
+                "org.postgresql.jdbc.PgResultSet.NullObject"
```
Comment (yrodiere) [inline extensions/jdbc/jdbc-postgresql/deployment/src/main/java/io/quarkus/jdbc/postgresql/deployment/PostgreSQLJDBCReflections.java:40]: If it's not necessary, I don't see why we would do this.

Registering types for reflection has a cost.

File: integration-tests/jpa-postgresql/src/main/java/io/quarkus/it/jpa/postgresql/Person.java [hunk 2]
```diff
@@ -64,8 +71,25 @@ public void setStatus(Status status) {
...
     }
 
+    /**
+     * Need to explicitly set the scale (and the precision so that the scale will actually be read from the annotation).
+     * Postgresql would only allow maximum scale of 6 for a `interval second`.
+     *
+     * @see org.hibernate.type.descriptor.sql.internal.Scale6IntervalSecondDdlType
+     */
+    @Column(precision = 5, scale = 5)
+    @JdbcType(PostgreSQLIntervalSecondJdbcType.class)
```
Comment (yrodiere) [inline integration-tests/jpa-postgresql/src/main/java/io/quarkus/it/jpa/postgresql/Person.java:81]: I think this is supposed to be simply `@JdbcType(INTERVAL_SECOND)`? See https://docs.jboss.org/hibernate/orm/current/userguide/html_single/Hibernate_User_Guide.html#_duration

File: integration-tests/jpa-postgresql/src/test/java/io/quarkus/it/jpa/postgresql/JPAReflectionInGraalITCase.java [hunk 3]
```diff
@@ -20,4 +20,11 @@ public void testFieldAndGetterReflectionOnEntityFromServlet() throws Exception {
         RestAssured.when().get("/jpa/testreflection").then().body(is("OK"));
     }
 
+    // Since the driver can do some reflection magic we also want to make sure that the regular functionality works fine
+    // within an integration test.
+    @Test
+    public void testJPAFunctionalityFromServlet() throws Exception {
+        RestAssured.when().get("/jpa/testfunctionality").then().body(is("OK"));
+    }
+
```
Comment (yrodiere) [inline integration-tests/jpa-postgresql/src/test/java/io/quarkus/it/jpa/postgresql/JPAReflectionInGraalITCase.java:29]: I believe this is unnecessary as we already do this in `JPAFunctionalityInGraalITCase`?

File: integration-tests/jpa-postgresql/src/main/java/io/quarkus/it/jpa/postgresql/Person.java (hunk 2 above)
Comment (marko-bekhta) [reply integration-tests/jpa-postgresql/src/main/java/io/quarkus/it/jpa/postgresql/Person.java:81]: That's what I thought looking at the docs, too 😃, but the annotation wants a class rather than an int 🙈. Should we update that to be `@JdbcType(INTERVAL_SECOND_JDBC_TYPE_CLASS)` or something similar?

File: extensions/jdbc/jdbc-postgresql/deployment/src/main/java/io/quarkus/jdbc/postgresql/deployment/PostgreSQLJDBCReflections.java [hunk 4]
```diff
@@ -20,6 +20,29 @@ void build(BuildProducer<ReflectiveClassBuildItem> reflectiveClass) {
...
+                "org.postgresql.util.PGobject",
+                "org.postgresql.util.PGInterval",
+                "org.postgresql.util.PGmoney",
+                "org.postgresql.geometric.PGbox",
+                "org.postgresql.geometric.PGcircle",
+                "org.postgresql.geometric.PGline",
+                "org.postgresql.geometric.PGlseg",
+                "org.postgresql.geometric.PGpath",
+                "org.postgresql.geometric.PGpoint",
+                "org.postgresql.geometric.PGpolygon",
```
[the remark this answers is not in the document]
Comment (marko-bekhta) [reply extensions/jdbc/jdbc-postgresql/deployment/src/main/java/io/quarkus/jdbc/postgresql/deployment/PostgreSQLJDBCReflections.java:37]: Yes, that's it. Only these two are in Hibernate ORM `org.postgresql.util.PGobject`, `org.postgresql.util.PGInterval`

File: integration-tests/jpa-postgresql/src/main/java/io/quarkus/it/jpa/postgresql/Person.java (hunk 2 above)
Comment (yrodiere) [reply integration-tests/jpa-postgresql/src/main/java/io/quarkus/it/jpa/postgresql/Person.java:81]: It should be `@JdbcTypeCode(INTERVAL_SECOND)`, I believe. And yes it would be nice to send a PR to update the docs.

Comment (marko-bekhta) [reply integration-tests/jpa-postgresql/src/main/java/io/quarkus/it/jpa/postgresql/Person.java:81]: ok will test it locally and then send an update to the docs, thanks!

File: extensions/jdbc/jdbc-postgresql/deployment/src/main/java/io/quarkus/jdbc/postgresql/deployment/PostgreSQLJDBCReflections.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (Sanne) [reply extensions/jdbc/jdbc-postgresql/deployment/src/main/java/io/quarkus/jdbc/postgresql/deployment/PostgreSQLJDBCReflections.java:37]: P.S. conditionals are better expressed in the json file format of GraalVM. Which implies, ideally one could try to contribute these to the pgjdbc driver itself for everyone to benefit.

File: integration-tests/jpa-postgresql/src/main/java/io/quarkus/it/jpa/postgresql/Person.java (hunk 2 above)
Comment (yrodiere) [reply integration-tests/jpa-postgresql/src/main/java/io/quarkus/it/jpa/postgresql/Person.java:81]: Any news on this one? It looks like you didn't update the PR, is it because `@JdbcTypeCode` didn't work?

Comment (marko-bekhta) [reply integration-tests/jpa-postgresql/src/main/java/io/quarkus/it/jpa/postgresql/Person.java:81]: The `@JdbcTypeCode` lead to https://hibernate.atlassian.net/browse/HHH-16591 🙈 
And since someone picked up that ticket to work on, I thought I'd give it a chance to see if it gets fixed 😃 
The missing parts are: 
- this annotation, 
- to address a comment from Sanne (https://github.com/quarkusio/quarkus/pull/33300#discussion_r1199034326) to simplify the registering a bit

Right?

Comment (yrodiere) [reply integration-tests/jpa-postgresql/src/main/java/io/quarkus/it/jpa/postgresql/Person.java:81]: Right.

Comment (Sanne) [reply integration-tests/jpa-postgresql/src/main/java/io/quarkus/it/jpa/postgresql/Person.java:81]: Regarding my previous comment.. it's a nice to have but definitely not a requirement ;)

**Comment by gsmet** [comment]
@marko-bekhta @yrodiere what's the status of this one? Is it good to go now?

**Comment by yrodiere** [comment]
@gsmet No, we're waiting for https://hibernate.atlassian.net/browse/HHH-16591 to get fixed.

Though I suppose we could give up on the idea of using the "proper" API (`@JdbcTypeCode`) since that's unrelated to the problem Marko is trying to fix.

**Review by yrodiere — APPROVED** [review]

**Comment by yrodiere** [comment]
Thanks. Let's wait for CI and merge.
