### PR TITLE
ArC: fix interception when some methods return void

### LINKED ISSUE #38236: Adding a decorator causes bytecode error
### Describe the bug

I tried to add a decorator for a JPA repository component. Simple project to reproduce the problem is attached 

I have created alternative implementation of GameRepository that is not based on JPA and without @Transactional. It works perfectly.

### Expected behavior

There should be no bytecode error and the decorator method should be executed

### Actual behavior

When the JpaGameRepositoryTest is run the following exception is thrown:

pl.kurs.JpaGameRepositoryTest#add(JpaGameRepositoryTest.java:19) JpaGameRepositoryTest#add() Method expects a return value
Exception Details:
  Location:
    pl/kurs/JpaGameRepository_Subclass$$function$$1.apply(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; @26: return
  Reason:
    Error exists in the bytecode
  Bytecode:
    0000000: 2cc0 000c b900 1001 0003 324e 2ab4 0012
    0000010: c000 142d c000 16b6 001a b1

### How to Reproduce?

Run tests for attached project
[decorator.zip](https://github.com/quarkusio/quarkus/files/13960004/decorator.zip)

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

openjdk 21 2023-09-19 OpenJDK Runtime Environment (build 21+35-2513) OpenJDK 64-Bit Server VM (build 21+35-2513, mixed mode, sharing)

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Java version: 21, vendor: Oracle Corporation, runtime: D:\DevTools\Java\jdk-21 Default locale: en_US, platform encoding: UTF-8 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Ladicek**
This commit fixes 2 cases when invalid bytecode is generated:

- when a `void`-returning method is intercepted and also decorated
- when an interceptor declared on a target class returns `void`

Fixes #38236

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]

**Comment by gsmet** [comment]
Let's wait at least for @mkouba 's approval (and maybe @manovotn too if deemed necessary) as there's a good chance we will backport this to 3.2.

**Review by manovotn — APPROVED** [review]

File: independent-projects/arc/tests/src/test/java/io/quarkus/arc/test/interceptors/targetclass/VoidAroundInvokeOnTargetClassTest.java [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+    }
+
+    @Singleton
+    static class MyBean {
+        String doSomething() {
+            return "foobar";
+        }
+
+        @AroundInvoke
+        void intercept(InvocationContext ctx) throws Exception {
```
Comment (mkouba) [inline independent-projects/arc/tests/src/test/java/io/quarkus/arc/test/interceptors/targetclass/VoidAroundInvokeOnTargetClassTest.java:32]: I don't think that we should support this signature. According to the spec, only `Object <METHOD>(InvocationContext)` is supported: https://jakarta.ee/specifications/interceptors/2.0/interceptors-spec-2.0.html#business_method_interceptor_methods

Comment (mkouba) [reply independent-projects/arc/tests/src/test/java/io/quarkus/arc/test/interceptors/targetclass/VoidAroundInvokeOnTargetClassTest.java:32]: In other words, this particular test should result in a validation failure...

Comment (gsmet) [reply independent-projects/arc/tests/src/test/java/io/quarkus/arc/test/interceptors/targetclass/VoidAroundInvokeOnTargetClassTest.java:32]: If it wasn't reported as a failure before, we at least need to isolate this change as we probably wouldn't backport it.

Comment (Ladicek) [reply independent-projects/arc/tests/src/test/java/io/quarkus/arc/test/interceptors/targetclass/VoidAroundInvokeOnTargetClassTest.java:32]: I'll see what would it take to fix the validation. I can either add a new commit to this PR, or submit another PR -- I guess another PR would be easier from the backporting perspective.

Comment (mkouba) [reply independent-projects/arc/tests/src/test/java/io/quarkus/arc/test/interceptors/targetclass/VoidAroundInvokeOnTargetClassTest.java:32]: :+1: Just remove this test pls.

Comment (Ladicek) [reply independent-projects/arc/tests/src/test/java/io/quarkus/arc/test/interceptors/targetclass/VoidAroundInvokeOnTargetClassTest.java]: Fair enough. Rebased and removed this test.

Comment (mkouba) [reply independent-projects/arc/tests/src/test/java/io/quarkus/arc/test/interceptors/targetclass/VoidAroundInvokeOnTargetClassTest.java]: Thanks.

**Review by mkouba — APPROVED** [review]

**Comment by gsmet** [comment]
Hi @edeweerd1A I see the commit in the 3.8 `git log`. What makes you think it's not there?

**Comment by edeweerd1A** [comment]
> Hi @edeweerd1A I see the commit in the 3.8 `git log`. What makes you think it's not there?

Hi, yes indeed. I made the stupid mistake of search with the issue title, not the commit. Thanks for confirming, and apologies for the disturbance.
