### PR TITLE
Fix narayana-jta restart in dev mode, issue 35839

### LINKED ISSUE #35839: Narayana transaction recovery stops work in DEV mode after hot reload
### Describe the bug

When I change my application in DEV mode and the app is reload, Narayana keeps using the old (previous) Datasource connection even though pool has been closed and new one was created. Details in here https://github.com/quarkusio/quarkus/pull/35242#issuecomment-1668239070

### Expected behavior

After hot reload, my app still works.

### Actual behavior

Warning is logged and periodic recovery doesn't work

```
2023-08-07 18:41:54,145 WARN  [com.arj.ats.arjuna] (Transaction Expired Entry Monitor) ARJUNA012251: allObjUids caught exception: java.sql.SQLException: This pool is closed and does not handle any more connections!
	at io.agroal.pool.ConnectionPool.beforeAcquire(ConnectionPool.java:209)
	at io.agroal.pool.ConnectionPool.getConnection(ConnectionPool.java:235)
	at io.agroal.pool.DataSource.getConnection(DataSource.java:86)
	at io.quarkus.narayana.jta.runtime.QuarkusDataSource.getConnection(QuarkusDataSource.java:38)
	at com.arjuna.ats.internal.arjuna.objectstore.jdbc.accessors.DirectDataSourceJDBCAccess.getConnection(DirectDataSourceJDBCAccess.java:27)
	at com.arjuna.ats.internal.arjuna.objectstore.jdbc.JDBCImple_driver.allObjUids(JDBCImple_driver.java:348)
	at com.arjuna.ats.internal.arjuna.objectstore.jdbc.JDBCStore.allObjUids(JDBCStore.java:169)
	at com.arjuna.ats.internal.arjuna.objectstore.jdbc.JDBCStore.allObjUids(JDBCStore.java:125)
	at com.arjuna.ats.internal.arjuna.recovery.ExpiredTransactionStatusManagerScanner.scan(ExpiredTransactionStatusManagerScanner.java:81)
	at com.arjuna.ats.internal.arjuna.recovery.ExpiredEntryMonitor.run(ExpiredEntryMonitor.java:171)
```

### How to Reproduce?

Reproducer:

- on this branch and inside quickstart added here https://github.com/quarkusio/quarkus-quickstarts/pull/1311
- `quarkus dev`
- wait till service is fully started
- force restart with `s`

### Output of `uname -a` or `ver`

Fedora

### Output of `java -version`

17

### GraalVM version (if different from Java)

23

### Quarkus version or git rev

999-SNAPSHOT

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.3

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by marcosgopen**
Deregister xa resources helpers in stop method before terminating the recoveryManager

Please note: stop() is called before destroy()

* Fixes [#35839](https://github.com/quarkusio/quarkus/issues/35839)

### CODE REVIEW

File: extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/QuarkusRecoveryService.java [hunk 1]
```diff
@@ -38,24 +41,43 @@ public void removeXAResourceRecovery(XAResourceRecovery xares) {
...
+
+        try {
+            super.stop();
+        } catch (Exception e) {
+        }
+
         isCreated = false;
-        recoveryManagerService = null;
+        // Do NOT set recoveryManagerService = null - maintain singleton pattern
+        // so datasources closing after destroy() can still properly deregister
```
Comment (gsmet) [inline extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/QuarkusRecoveryService.java]: But this will leak the original class loader, won't it?

**Review by gsmet — COMMENTED** [review]
Thanks. I added a question.

File: extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/QuarkusRecoveryService.java (hunk 1 above)
Comment (marcosgopen) [reply extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/QuarkusRecoveryService.java]: You are right, I'll update the PR

File: extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/QuarkusRecoveryService.java [hunk 2]
```diff
@@ -38,24 +41,47 @@ public void removeXAResourceRecovery(XAResourceRecovery xares) {
         if (isCreated) {
             super.removeXAResourceRecovery(xares);
         } else {
+            // Remove from pending list if not yet created
             xaResources.remove(xares);
         }
+        // Always remove from registered list to handle datasources closing after destroy()
+        registeredXaResources.remove(xares);
```
Comment (zhfeng) [inline extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/QuarkusRecoveryService.java:48]: Hmm, it looks like we only add it in `registerdXaResources` when `isCreated` is true?

Comment (marcosgopen) [reply extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/QuarkusRecoveryService.java:48]: Yes, I would see it as a safer approach. xaResources is used when isCreated is false, otherwise we use registeredXaResources.  However I'd call 'registeredXaResources.remove(xares);' also in both cases to make sure every resource is properly removed.

**Review by zhfeng — APPROVED** [review]

**Review by gsmet — APPROVED** [review]
