### PR TITLE
Fix KAFKA_TLS_CONFIGURATION_NAME environment variable not being recognized

### LINKED ISSUE #51195: Environment variable KAFKA_TLS_CONFIGURATION_NAME does not take effect
### Describe the bug

When a TLS registration for Kafka is configured via the “KAFKA_TLS_CONFIGURATION_NAME” environment variable, this setting is not applied correctly. The TLS settings of the corresponding TLS-registration are therefore not applied. 

The problem is caused in KafkaRuntimeConfigProducer.java :
[KafkaRuntimeConfigProducer.java](https://github.com/quarkusio/quarkus/blob/main/extensions/kafka-client/runtime/src/main/java/io/quarkus/kafka/client/runtime/KafkaRuntimeConfigProducer.java#L50)

When the environment property KAFKA_TLS_CONFIGURATION_NAME is set, the configuration property (propertyNameLowerCase) will be present as kafka.tls_configuration_name.
The effectivePropertyName is therefore "tls.configuration.name"

This causes the subsequent comparison to fail, so that the property “ssl.engine.factory.class” is not set.
And this setting is in turn required to configure Kaka with the TLS registry.

### Expected behavior

Setting the environment variable KAFKA_TLS_CONFIGURATION_NAME should confiure Kafka with the values provided by the corresponding tls-registry entry

### Actual behavior

See bug description

### How to Reproduce?

Reproducer project with a descriptption can be found here: https://github.com/darkmoon221/kafka-reproducer

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

Setting the property via application.yaml works as expected

e.g.:
`
kafka:
  tls-confguration-name: myTlsConfig
`

### PR DESCRIPTION
**Pull request by ozangunalp**
- Fixes: #51195

### CODE REVIEW

File: extensions/kafka-client/runtime/src/test/java/io/quarkus/kafka/client/runtime/KafkaRuntimeConfigProducerTest.java [hunk 1]
```diff
@@ -0,0 +1,86 @@
...
+        SmallRyeConfig config = new SmallRyeConfigBuilder()
+                .withDefaultValues(Map.of("kafka.bootstrap.servers", "localhost:9092"))
+                .build();
+        ApplicationConfig appConfig = mock(ApplicationConfig.class);
+        when(appConfig.name()).thenReturn(Optional.of("my-app"));
+
+        KafkaRuntimeConfigProducer producer = new KafkaRuntimeConfigProducer();
+        Map<String, Object> result = producer.createKafkaRuntimeConfig(config, appConfig);
+
+        assertEquals("my-app", result.get("group.id"));
```
Comment (gastaldi) [inline extensions/kafka-client/runtime/src/test/java/io/quarkus/kafka/client/runtime/KafkaRuntimeConfigProducerTest.java]: Here is a suggestion to give a better assertion message: 

```suggestion
        assertThat(result).containsEntry("group.id", "my-app");
```

**Review by gastaldi — APPROVED** [review]

**Comment by ozangunalp** [comment]
@gastaldi Thanks!

**Review by geoand — APPROVED** [review]
