### PR TITLE
Do not record local sources in runtime config defaults.

### LINKED ISSUE #39388: Hibernate runtime property persisting after build
### Describe the bug

The hibernate runtime property `quarkus.hibernate-orm.database.generation=drop-and-create`  persisting when set using environment variable during build  process as `set QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION=drop-and-create `. 

After build this is used by application at runtime even if it is not set/configured in `application.properties`  file.  The default value of this config property is `none`.

### Expected behavior

`quarkus.hibernate-orm.database.generation=drop-and-create` should not persist after building even if we have set the environment variable `set QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION=drop-and-create ` during build process.

We are not specifying this property quarkus.hibernate-orm.database.generation=drop-and-create` in our application.properties file hence it should take none as default value while running application as  java -jar quarkus-run.jar .

### Actual behavior

The hibernate runtime property `quarkus.hibernate-orm.database.generation=drop-and-create`  persisting when set using environment variable during build  process as `set QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION=drop-and-create `. 

After build this is used by application at runtime even if it is not set/configured in `application.properties`  file.  The default value of this config property is `none`.

### How to Reproduce?

Reproducer steps : 

1. Set environment variable `set QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION=drop-and-create `.
2. Build the application using `mvn clean install`.
3. Do not specify `quarkus.hibernate-orm.database.generation=drop-and-create` in application.properties file.
4. Run the application jar in other session/terminal  `java -jar quarkus-run.jar ` .
5. Application executes drop and create for tables instead of doing nothing.

Attached reproducer
[code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/14585171/code-with-quarkus.zip)

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

java version "17.0.4" 2022-07-19 LTS Java(TM) SE Runtime Environment (build 17.0.4+11-LTS-179) Java HotSpot(TM) 64-Bit Server VM (build 17.0.4+11-LTS-179, mixed mode, sharing)

### Quarkus version or git rev

Quarkus version  3.7.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.3 (21122926829f1ead511c958d89bd2f672198ae9f) Maven home: C:\Users\****\.m2\wrapper\dists\apache-maven-3.9.3-bin\326f10f4\apache-maven-3.9.3 Java version: 17.0.4, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-17.0.4 Default locale: en_US, platform encoding: Cp1252 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by radcortez**
- Fixes #39388

### CODE REVIEW

**Review by cescoffier — DISMISSED** [review]
Some failures are related.

File: core/deployment/src/main/java/io/quarkus/deployment/configuration/BuildTimeConfigurationReader.java [hunk 1]
```diff
@@ -1117,6 +1121,40 @@ public Set<String> getPropertyNames() {
...
+
+            // TODO - Should we reset quarkus.config.location to not record from these sources?
+            for (ConfigSource configSource : config.getConfigSources()) {
+                if (configSource instanceof SysPropConfigSource) {
+                    continue;
+                }
+                if (configSource instanceof EnvConfigSource) {
+                    continue;
+                }
+                if ("PropertiesConfigSource[source=Build system]".equals(configSource.getName())) {
```
[the remark this answers is not in the document]
Comment (aloubyansky) [reply core/deployment/src/main/java/io/quarkus/deployment/configuration/BuildTimeConfigurationReader.java:1150]: Seems like Maven/Gradle project properties

[the remark this answers is not in the document]
Comment (radcortez) [reply core/deployment/src/main/java/io/quarkus/deployment/configuration/BuildTimeConfigurationReader.java:1150]: This is to exclude them from runtime recording. Probably this is what causing the test failures.

Do we agree that sources coming from the build system must also be excluded?

File: core/deployment/src/main/java/io/quarkus/deployment/configuration/BuildTimeConfigurationReader.java [hunk 2]
```diff
@@ -1117,6 +1121,40 @@ public Set<String> getPropertyNames() {
             return properties;
         }
 
+        /**
+         * Use this Config instance to record the runtime default values. We cannot use the main Config
+         * instance because it may record values coming from local development sources (Environment Variables,
+         * System Properties, etc.) in build time. Local config source values may be completely different between the
+         * build environment and the runtime environment, so it doesn't make sense to record these.
+         *
+         * @return a new SmallRye instance without the EnvSources.
```
[the remark this answers is not in the document]
Comment (radcortez) [reply core/deployment/src/main/java/io/quarkus/deployment/configuration/BuildTimeConfigurationReader.java:1130]: Started that way, but added more. I'll complete the list in the doc.

File: core/deployment/src/main/java/io/quarkus/deployment/configuration/BuildTimeConfigurationReader.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (cescoffier) [reply core/deployment/src/main/java/io/quarkus/deployment/configuration/BuildTimeConfigurationReader.java:1150]: yes

File: core/deployment/src/main/java/io/quarkus/deployment/configuration/BuildTimeConfigurationReader.java [hunk 3]
```diff
@@ -512,10 +514,12 @@ ReadResult run() {
...
 
+            SmallRyeConfig runtimeConfig = getConfigForRuntimeRecording();
+
             // Register defaults for Roots
-            allBuildTimeValues.putAll(getDefaults(buildTimePatternMap));
-            buildTimeRunTimeValues.putAll(getDefaults(buildTimeRunTimePatternMap));
-            runTimeDefaultValues.putAll(getDefaults(runTimePatternMap));
+            allBuildTimeValues.putAll(getDefaults(config, buildTimePatternMap));
+            buildTimeRunTimeValues.putAll(getDefaults(config, buildTimeRunTimePatternMap));
+            runTimeDefaultValues.putAll(getDefaults(runtimeConfig, runTimePatternMap));
```
Comment (gsmet) [inline core/deployment/src/main/java/io/quarkus/deployment/configuration/BuildTimeConfigurationReader.java:522]: Just to clarify something: when you start your runtime app, how are the config sources evaluated?

What I'm wondering is if we need to register default values for runtime? Is it because we don't parse the existing config such as `application.properties` at runtime?

Asking because my inclination would have been to record nothing for runtime values and let things be determined at runtime.

File: core/deployment/src/main/java/io/quarkus/deployment/configuration/BuildTimeConfigurationReader.java [hunk 4]
```diff
@@ -1117,6 +1121,40 @@ public Set<String> getPropertyNames() {
...
+            SmallRyeConfigBuilder builder = ConfigUtils.emptyConfigBuilder();
+            builder.getSources().clear();
+            builder.getSourceProviders().clear();
+            builder.setAddDefaultSources(false)
+                    // Customizers may duplicate sources, but not much we can do about it, we need to run them
+                    .addDiscoveredCustomizers()
+                    // Read microprofile-config.properties, because we disabled the default sources
+                    .withSources(classPathSources(META_INF_MICROPROFILE_CONFIG_PROPERTIES, classLoader));
+
+            // TODO - Should we reset quarkus.config.location to not record from these sources?
```
Comment (gsmet) [inline core/deployment/src/main/java/io/quarkus/deployment/configuration/BuildTimeConfigurationReader.java:1142]: As for `quarkus.config.locations`, it's not that easy to decide what to do.

But it resonates with the comment I made above: I don't fully understand why we need to register defaults for runtime values?
My understanding would be that they should be fully resolved at runtime with whatever config sources are around at runtime.

**Review by gsmet — COMMENTED** [review]
I asked some questions.

If you suspect I know nothing about the config system when reading my questions, you're entirely right :).

File: core/deployment/src/main/java/io/quarkus/deployment/configuration/BuildTimeConfigurationReader.java (hunk 3 above)
Comment (radcortez) [reply core/deployment/src/main/java/io/quarkus/deployment/configuration/BuildTimeConfigurationReader.java:522]: Correct, we flatten the sources to a single source to optimize lookup and save on loading. We could try to remove the runtime recording and generate the runtime source of each `application.properties` and let it be loaded by the Config.

File: core/deployment/src/main/java/io/quarkus/deployment/configuration/BuildTimeConfigurationReader.java (hunk 4 above)
Comment (radcortez) [reply core/deployment/src/main/java/io/quarkus/deployment/configuration/BuildTimeConfigurationReader.java:1142]: It depends on the phase. We need to record the values for build time - runtime fixed to ensure they do not change between build and runtime.

For runtime, it has been a convenience; to flatten the sources to reduce lookups, avoid loading the config files, and ensure that Quarkus would still run even if a property was missing by falling back to the recorded value from the build.

Comment (gsmet) [reply core/deployment/src/main/java/io/quarkus/deployment/configuration/BuildTimeConfigurationReader.java:1142]: Yeah, so I'm not aware of all the consequences and maybe it could have some consequences but my intuition tells me to drop the recording for runtime and resolve things at runtime.

Of course, I would try to avoid reading the `application.properties` we have in the app and have it preprocessed but I wouldn't go further than that.

Now, I might be missing something entirely and it might cause issues I don't foresee, be it for performance or other things.

Comment (radcortez) [reply core/deployment/src/main/java/io/quarkus/deployment/configuration/BuildTimeConfigurationReader.java:1142]: We can certainly do that. I don't foresee any big consequences, and regarding performance, it is hard to tell the impact without measuring it, but we should be able to figure out something.

We must still record the runtime defaults from roots, mappings, and build steps, but we don't need the config instance in that case.

File: core/deployment/src/main/java/io/quarkus/deployment/configuration/BuildTimeConfigurationReader.java [hunk 5]
```diff
@@ -1117,6 +1121,41 @@ public Set<String> getPropertyNames() {
             return properties;
         }
 
+        /**
+         * Use this Config instance to record the runtime default values. We cannot use the main Config
+         * instance because it may record values coming from local development sources (Environment Variables,
+         * System Properties, etc.) in at build time. Local config source values may be completely different between the
```
Comment (maxandersen) [inline core/deployment/src/main/java/io/quarkus/deployment/configuration/BuildTimeConfigurationReader.java:1127]: can we be a  bit more specific here than just "etc" - what are we actually using from recording?

looking at code below we are not excluding sources but just gathering  a list of sources...what is actually defining what we include/exclude here?

Comment (radcortez) [reply core/deployment/src/main/java/io/quarkus/deployment/configuration/BuildTimeConfigurationReader.java:1127]: Yes, we build a new Config instance, excluding specific sources. The `.env` sources are also of type `EnvConfigSource`, so they get excluded (or, to be more correct, not added to the config instance used for recording).

File: integration-tests/test-extension/extension/deployment/src/main/resources/application.properties [hunk 6]
```diff
@@ -152,8 +152,8 @@ quarkus.arc.unremovable-types=foo
 # The YAML source may add an indexed property (depending on how the YAML is laid out). This is not supported by @ConfigRoot
 quarkus.arc.unremovable-types[0]=foo
 
-### Do not record env values in build time
-bt.ok.to.record=properties
+### recording
+bt.ok.to.record=from-app
 %test.bt.profile.record=properties
```
Comment (sberyozkin) [inline integration-tests/test-extension/extension/deployment/src/main/resources/application.properties:157]: Hi @radcortez, quick question, does `%test.bt.profile.record=properties` mean that it is OK to record the `bt` profile config property values in the test mode but the recording for this profile is off in the prod mode ?

Comment (radcortez) [reply integration-tests/test-extension/extension/deployment/src/main/resources/application.properties:157]: We record all profiled names. We need to ensure that the recorded properties retain their original property name, to not override each other. Local sources are excluded from any recording for any case with this PR.

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
@dmlloyd I plan to include this in 3.9 I will release on Wednesday morning CET. So if you want to have a second look it would be today or tomorrow at the latest.

Except if there is a significant conceptual problem, I think we should merge it.

**Review by dmlloyd — APPROVED** [review]

**Comment by geoand** [comment]
This seems to cause https://github.com/quarkusio/quarkus/issues/39776 which is rather serious.
