### PR TITLE
Make the vertx-graphql extension work in native mode

### LINKED ISSUE #5248: vertx-graphql fails in native mode - GraphQLInputDeserializer has no default (no arg) constructor
integration-tests/vertx-graphql fails in native mode - GraphQLInputDeserializer has no default (no arg) constructor

```
Caused by: java.lang.IllegalArgumentException: Class
  io.vertx.ext.web.handler.graphql.impl.GraphQLInputDeserializer
  has no default (no arg) constructor
	at com.fasterxml.jackson.databind.util.ClassUtil.createInstance(ClassUtil.java:554)
	
```

CC @machi1990 @cristianonicolai @gsmet 

```
2019-11-06 12:35:29,018 INFO  [io.quarkus] (main) Installed features: [cdi, vertx-graphql]
2019-11-06 12:35:29,876 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-3) HTTP Request to /graphql failed, error id: bc94e483-9cae-4472-aa5c-bf8d07dbc6d9-1: io.vertx.core.json.DecodeException: Failed to decode:Class io.vertx.ext.web.handler.graphql.impl.GraphQLInputDeserializer has no default (no arg) constructor
 at [Source: (io.netty.buffer.ByteBufInputStream); line: 1, column: 1]
	at io.vertx.core.json.jackson.JacksonCodec.fromParser(JacksonCodec.java:97)
	at io.vertx.core.json.jackson.JacksonCodec.fromBuffer(JacksonCodec.java:66)
	at io.vertx.ext.web.handler.graphql.impl.GraphQLHandlerImpl.handlePostJson(GraphQLHandlerImpl.java:141)
	at io.vertx.ext.web.handler.graphql.impl.GraphQLHandlerImpl.handlePost(GraphQLHandlerImpl.java:128)
	at io.vertx.ext.web.handler.graphql.impl.GraphQLHandlerImpl.lambda$handle$2(GraphQLHandlerImpl.java:86)
	at io.vertx.core.http.HttpServerRequest.lambda$bodyHandler$0(HttpServerRequest.java:216)
	at io.vertx.core.http.impl.HttpServerRequestImpl.onEnd(HttpServerRequestImpl.java:530)
	at io.vertx.core.http.impl.HttpServerRequestImpl.lambda$pendingQueue$1(HttpServerRequestImpl.java:118)
	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:237)
	at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:127)
	at io.vertx.core.http.impl.HttpServerRequestImpl.handleEnd(HttpServerRequestImpl.java:514)
	at io.vertx.core.http.impl.Http1xServerConnection.handleEnd(Http1xServerConnection.java:176)
	at io.vertx.core.http.impl.Http1xServerConnection.handleContent(Http1xServerConnection.java:163)
	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:140)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:232)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:173)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:328)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.vertx.core.http.impl.Http1xOrH2CHandler.end(Http1xOrH2CHandler.java:61)
	at io.vertx.core.http.impl.Http1xOrH2CHandler.channelRead(Http1xOrH2CHandler.java:38)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:460)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Class io.vertx.ext.web.handler.graphql.impl.GraphQLInputDeserializer has no default (no arg) constructor
 at [Source: (io.netty.buffer.ByteBufInputStream); line: 1, column: 1]
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:268)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:477)
	at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:4191)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3980)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2277)
	at io.vertx.core.json.jackson.JacksonCodec.fromParser(JacksonCodec.java:95)
	... 58 more
Caused by: java.lang.IllegalArgumentException: Class io.vertx.ext.web.handler.graphql.impl.GraphQLInputDeserializer has no default (no arg) constructor
	at com.fasterxml.jackson.databind.util.ClassUtil.createInstance(ClassUtil.java:554)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.deserializerInstance(DefaultDeserializationContext.java:229)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findDeserializerFromAnnotation(DeserializerCache.java:427)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:326)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
	... 65 more

```

### PR DESCRIPTION
**Pull request by machi1990**
fixes #5248

/cc @rsvoboda can you check if this fix the issue for you? Thanks

@gsmet @cescoffier @cristianonicolai

### CODE REVIEW

**Comment by rsvoboda** [comment]
What's the motivation to remove `@Inject Vertx vertx;`?

File: extensions/vertx-graphql/deployment/src/main/java/io/quarkus/vertx/graphql/deployment/VertxGraphqlProcessor.java [hunk 1]
```diff
@@ -18,4 +34,38 @@ FeatureBuildItem feature() {
...
+    @BuildStep
+    List<NativeImageResourceBuildItem> registerNativeImageResources() throws IOException {
+        ResolvedArtifact artifact = getVertxGraphQlArtifact();
+
+        List<NativeImageResourceBuildItem> nativeImageResourceBuildItems = new ArrayList<>();
+
+        File artifactFile = artifact.getArtifactPath().toFile();
+        try (JarFile jarFile = new JarFile(artifactFile)) {
+            Enumeration<JarEntry> entries = jarFile.entries();
+            while (entries.hasMoreElements()) {
```
Comment (rsvoboda) [inline extensions/vertx-graphql/deployment/src/main/java/io/quarkus/vertx/graphql/deployment/VertxGraphqlProcessor.java]: What's the impact on performance and native image size ?

Asking because all class entries end up in `nativeImageResourceBuildItems.add(new NativeImageResourceBuildItem(entry.getName()));`

**Comment by machi1990** [comment]
> What's the motivation to remove `@Inject Vertx vertx;`?
  
It was throwing `NPE` in native mode.

File: extensions/vertx-graphql/deployment/src/main/java/io/quarkus/vertx/graphql/deployment/VertxGraphqlProcessor.java (hunk 1 above)
Comment (machi1990) [reply extensions/vertx-graphql/deployment/src/main/java/io/quarkus/vertx/graphql/deployment/VertxGraphqlProcessor.java]: > What's the impact on performance and native image size ?
> 
> Asking because all class entries end up in `nativeImageResourceBuildItems.add(new NativeImageResourceBuildItem(entry.getName()));`

class entries are filtered out, the idea is to keep only  `.html`, `.css`, `.js`. Does it make sense?

Comment (rsvoboda) [reply extensions/vertx-graphql/deployment/src/main/java/io/quarkus/vertx/graphql/deployment/VertxGraphqlProcessor.java]: Ah, I missed `!` in `!entry` :)

**Comment by rsvoboda** [comment]
> It was throwing NPE in native mode.

`@Inject` is not working because it's in test ?

File: extensions/vertx-graphql/deployment/src/main/java/io/quarkus/vertx/graphql/deployment/VertxGraphqlProcessor.java [hunk 2]
```diff
@@ -18,4 +34,38 @@ FeatureBuildItem feature() {
...
+                JarEntry entry = entries.nextElement();
+                if (!entry.isDirectory() && entry.getName().startsWith("io/vertx/") && !entry.getName().endsWith(".class")) {
+                    nativeImageResourceBuildItems.add(new NativeImageResourceBuildItem(entry.getName()));
+                }
```
Comment (gsmet) [inline extensions/vertx-graphql/deployment/src/main/java/io/quarkus/vertx/graphql/deployment/VertxGraphqlProcessor.java]: Let's keep that one in mind in case we need it a second time, we could have a specific build item for it.

File: extensions/vertx-graphql/deployment/src/main/java/io/quarkus/vertx/graphql/deployment/VertxGraphqlProcessor.java [hunk 3]
```diff
@@ -18,4 +34,38 @@ FeatureBuildItem feature() {
...
+            }
+        }
+
+        return nativeImageResourceBuildItems;
+    }
+
+    private ResolvedArtifact getVertxGraphQlArtifact() {
```
Comment (gsmet) [inline extensions/vertx-graphql/deployment/src/main/java/io/quarkus/vertx/graphql/deployment/VertxGraphqlProcessor.java]: I'm not entirely familiar with it but I wonder if we could use `applicationArchivesBuildItem`? It has a way to find the archive hosting a class and maybe we can go from there?

Not entirely sure though so I might be entirely wrong.

File: integration-tests/vertx-graphql/src/test/java/io/quarkus/vertx/graphql/it/VertxGraphqlTest.java [hunk 4]
```diff
@@ -20,10 +18,6 @@
 
 @QuarkusTest
 class VertxGraphqlTest {
-
-    @Inject
-    Vertx vertx;
```
Comment (gsmet) [inline integration-tests/vertx-graphql/src/test/java/io/quarkus/vertx/graphql/it/VertxGraphqlTest.java]: This injection works in JVM mode but not in native?

**Review by gsmet — CHANGES_REQUESTED** [review]
I added a few comments and questions, let's sort them out.

File: integration-tests/vertx-graphql/src/test/java/io/quarkus/vertx/graphql/it/VertxGraphqlTest.java (hunk 4 above)
Comment (machi1990) [reply integration-tests/vertx-graphql/src/test/java/io/quarkus/vertx/graphql/it/VertxGraphqlTest.java]: Yes, the injection is not working in native. I am entirely not sure why though as could not get to the bottom of it. 

@mkouba @manovotn any ideas?

File: extensions/vertx-graphql/deployment/src/main/java/io/quarkus/vertx/graphql/deployment/VertxGraphqlProcessor.java (hunk 3 above)
Comment (machi1990) [reply extensions/vertx-graphql/deployment/src/main/java/io/quarkus/vertx/graphql/deployment/VertxGraphqlProcessor.java]: Sure, I'll check it.

Comment (machi1990) [reply extensions/vertx-graphql/deployment/src/main/java/io/quarkus/vertx/graphql/deployment/VertxGraphqlProcessor.java]: Could not make it work with `ApplicationArchiveBuildItem`: I cannot find a `vertx graphql` archive.

**Comment by machi1990** [comment]
> > It was throwing NPE in native mode.
> 
> `@Inject` is not working because it's in test ?

It is working in JVM mode but not for native test. I could not dig deep to understand the issue though.

**Comment by cristianonicolai** [comment]
@machi1990  thanks for the fix, I was looking into a similar fix. Let me know if I can help somehow.

File: integration-tests/vertx-graphql/src/test/java/io/quarkus/vertx/graphql/it/VertxGraphqlTest.java (hunk 4 above)
Comment (manovotn) [reply integration-tests/vertx-graphql/src/test/java/io/quarkus/vertx/graphql/it/VertxGraphqlTest.java]: Do you have anything more specific? What was the exception or the stack trace?
Also where do we actually produce the `Vertx` instance? I can see [`VertxProducer ` but that one is already injecting it,](https://github.com/quarkusio/quarkus/blob/master/extensions/vertx/runtime/src/main/java/io/quarkus/vertx/runtime/VertxProducer.java#L20-L21) so it has to be elsewhere.

Comment (machi1990) [reply integration-tests/vertx-graphql/src/test/java/io/quarkus/vertx/graphql/it/VertxGraphqlTest.java]: @cristianonicolai we are trying to figure out why we have a `null` injection of Vertx in native mode. Any insights is welcomed.

Comment (machi1990) [reply integration-tests/vertx-graphql/src/test/java/io/quarkus/vertx/graphql/it/VertxGraphqlTest.java]: > Do you have anything more specific? What was the exception or the stack trace?

It works correctly in JVM test but the value is `null` in native test. No any specific CDI stacktrace other than a NPE thrown here https://github.com/quarkusio/quarkus/pull/5253/files#diff-689b6ba08caa09cd266fc629886bcba3L40

Comment (manovotn) [reply integration-tests/vertx-graphql/src/test/java/io/quarkus/vertx/graphql/it/VertxGraphqlTest.java]: Oh, so just null. Hmm,then we probably need to figure out how is that bean registered in the first place.

Comment (machi1990) [reply integration-tests/vertx-graphql/src/test/java/io/quarkus/vertx/graphql/it/VertxGraphqlTest.java]: The bean is produced here - https://github.com/quarkusio/quarkus/blob/f98471dfb7dc0d26918a7d817b7360530d65cdd1/extensions/vertx-core/runtime/src/main/java/io/quarkus/vertx/core/runtime/VertxCoreProducer.java

I am able to reproduce in another native test e.g adding the following code for
```
   @Inject
    Flyway flyway;

    @Test
    public void test() {
        System.out.println(flyway);
        System.out.println(Arc.container());
    }
```
in https://github.com/quarkusio/quarkus/blob/785b0d5b904fe74e210084aec0d4c8448d27f7f0/integration-tests/flyway/src/test/java/io/quarkus/it/flyway/FlywayFunctionalityNativeIT.java 

Will print 
```
null
null
```

Note that `ArcContainer` is `null`, meaning not initialised at all in native test? `

Comment (cristianonicolai) [reply integration-tests/vertx-graphql/src/test/java/io/quarkus/vertx/graphql/it/VertxGraphqlTest.java]: @machi1990 after reading the docs I got the impression that injection isnt supported in native tests at all https://quarkus.io/guides/getting-started-testing#native-executable-testing

Comment (machi1990) [reply integration-tests/vertx-graphql/src/test/java/io/quarkus/vertx/graphql/it/VertxGraphqlTest.java]: Good catch @cristianonicolai thanks.  I was in a point of opening a separate issue for that.

Comment (mkouba) [reply integration-tests/vertx-graphql/src/test/java/io/quarkus/vertx/graphql/it/VertxGraphqlTest.java]: Yes, injection is not supported in `@NativeImageTest` (and it's mentioned in the [guide](https://quarkus.io/guides/getting-started-testing#native-executable-testing)). The reason is that the native executable runs in a separate process and the test class is of course not part of the native image.

**Review by rsvoboda — APPROVED** [review]

**Review by cristianonicolai — APPROVED** [review]

File: extensions/vertx-graphql/deployment/src/main/java/io/quarkus/vertx/graphql/deployment/VertxGraphqlProcessor.java (hunk 3 above)
Comment (stuartwdouglas) [reply extensions/vertx-graphql/deployment/src/main/java/io/quarkus/vertx/graphql/deployment/VertxGraphqlProcessor.java]: You need to use the AdditionalApplicationArchiveMarkerBuildItem to register a class/package in the archive as being a 'marker', and then this archive will be indexed. 

That said this approach also works fine, and avoids the need to index the archive.

Comment (machi1990) [reply extensions/vertx-graphql/deployment/src/main/java/io/quarkus/vertx/graphql/deployment/VertxGraphqlProcessor.java]: > You need to use the AdditionalApplicationArchiveMarkerBuildItem to register a class/package in the archive as being a 'marker', and then this archive will be indexed.
> 
> That said this approach also works fine, and avoids the need to index the archive.

Thanks @stuartwdouglas so I suppose we can keep it this way?

I'd try your suggestion for future references :-)

Comment (stuartwdouglas) [reply extensions/vertx-graphql/deployment/src/main/java/io/quarkus/vertx/graphql/deployment/VertxGraphqlProcessor.java]: After thinking about it I think a better approach would be to use something like:

getClass().getClassLoader().getResource("io/vertx/ext/web/handler/graphiql")

And then use the resulting URL to register all resources in the sub packages.

This could be generalised into a build item to make it easy to register all resources in a package/subpackage.

Comment (machi1990) [reply extensions/vertx-graphql/deployment/src/main/java/io/quarkus/vertx/graphql/deployment/VertxGraphqlProcessor.java]: Great, it joins Guillaume's suggestion https://github.com/quarkusio/quarkus/pull/5253#discussion_r343100496. I have pushed the changes. Let me know what you think.

**Review by stuartwdouglas — APPROVED** [review]

File: ci-templates/stages.yml [hunk 5]
```diff
@@ -15,7 +15,7 @@ stages:
     jobs:
       - job: Cache_Maven_Repo
         displayName: 'Linux Maven Repo'
-        condition: and(eq(variables.LINUX_USE_VMS, ${{parameters.expectUseVMs}}),succeeded()) 
+        condition: and(eq(variables.LINUX_USE_VMS, ${{parameters.expectUseVMs}}),succeeded())
```
Comment (cescoffier) [inline ci-templates/stages.yml]: I don't mind the reformating, but that creates noises.

File: ci-templates/stages.yml [hunk 6]
```diff
@@ -149,7 +149,7 @@ stages:
               jdk: '1.12'
 
       - job: Run_TCKs
-        condition: and(eq(variables.LINUX_USE_VMS, ${{parameters.expectUseVMs}}),succeeded()) 
+        condition: and(eq(variables.LINUX_USE_VMS, ${{parameters.expectUseVMs}}),succeeded())
         timeoutInMinutes: 60
```
Comment (cescoffier) [inline ci-templates/stages.yml]: please update the timeout in minutes by at least 5 minutes due to the new tests.

File: extensions/vertx-graphql/deployment/src/main/java/io/quarkus/vertx/graphql/deployment/VertxGraphqlProcessor.java [hunk 7]
```diff
@@ -15,4 +22,17 @@ FeatureBuildItem feature() {
...
+    List<ReflectiveClassBuildItem> registerForReflection() {
+        return Arrays.asList(
+                new ReflectiveClassBuildItem(true, true, GraphQLInputDeserializer.class.getName()),
+                new ReflectiveClassBuildItem(true, true, GraphQLBatch.class.getName()),
+                new ReflectiveClassBuildItem(true, true, GraphQLQuery.class.getName()));
+    }
+
+    @BuildStep
+    NativeImagePackageResourceBuildItem registerNativeImageResources() {
+        return new NativeImagePackageResourceBuildItem("io/vertx/ext/web/handler/graphiql");
```
Comment (cescoffier) [inline extensions/vertx-graphql/deployment/src/main/java/io/quarkus/vertx/graphql/deployment/VertxGraphqlProcessor.java]: can you double-check the name? graphiql ?

File: integration-tests/vertx-graphql/src/test/java/io/quarkus/vertx/graphql/it/VertxGraphqlTest.java [hunk 8]
```diff
@@ -37,7 +31,7 @@ public void testGraphQlQuery() {
 
     @Test
     public void testWebSocketSubProtocol() throws Exception {
-        HttpClient httpClient = vertx.createHttpClient();
+        HttpClient httpClient = Vertx.vertx().createHttpClient();
```
Comment (cescoffier) [inline integration-tests/vertx-graphql/src/test/java/io/quarkus/vertx/graphql/it/VertxGraphqlTest.java]: This new Vert.x instance must be closed.

**Review by cescoffier — CHANGES_REQUESTED** [review]

**Comment by cescoffier** [comment]
Do we want to have the UI in prod mode? That sounds more like a dev kind of thing.

File: ci-templates/stages.yml (hunk 5 above)
Comment (machi1990) [reply ci-templates/stages.yml]: I agree, must be my IDE. I'll revert.

File: extensions/vertx-graphql/deployment/src/main/java/io/quarkus/vertx/graphql/deployment/VertxGraphqlProcessor.java (hunk 7 above)
Comment (machi1990) [reply extensions/vertx-graphql/deployment/src/main/java/io/quarkus/vertx/graphql/deployment/VertxGraphqlProcessor.java]: Correct, it is `graphiql` :-)

File: integration-tests/vertx-graphql/src/test/java/io/quarkus/vertx/graphql/it/VertxGraphqlTest.java (hunk 8 above)
Comment (machi1990) [reply integration-tests/vertx-graphql/src/test/java/io/quarkus/vertx/graphql/it/VertxGraphqlTest.java]: Well spotted, I'll add it later on.

**Comment by machi1990** [comment]
> Do we want to have the UI in prod mode? That sounds more like a dev kind of thing.

Yes, I was targeting the same behaviour in JVM and native mode. Maybe later on we can refine and have a configuration variable `alwaysInclude` like what we have in `swagger-ui` extension.

File: integration-tests/vertx-graphql/src/test/java/io/quarkus/vertx/graphql/it/VertxGraphqlTest.java (hunk 8 above)
Comment (machi1990) [reply integration-tests/vertx-graphql/src/test/java/io/quarkus/vertx/graphql/it/VertxGraphqlTest.java]: done

File: ci-templates/stages.yml (hunk 6 above)
Comment (machi1990) [reply ci-templates/stages.yml]: Most of these changes were unrelated to the PR, my IDE auto-formatted the file after I had done my modification. So what I did here in my recent push is to increase the timeout by 5 minutes for the specific part. Could you please re-review if it is okay for you? Thanks

File: ci-templates/stages.yml (hunk 5 above)
Comment (machi1990) [reply ci-templates/stages.yml]: done. Thanks for catching this one.

**Comment by cescoffier** [comment]
I would like having the input from @emmanuelbernard on having the UI in prod. 
The UI is a query editor, it can be dangerous to have it in prod. At least we should have a flag to disable it.

File: integration-tests/vertx-graphql/src/test/java/io/quarkus/vertx/graphql/it/VertxGraphqlTest.java [hunk 9]
```diff
@@ -37,12 +31,14 @@ public void testGraphQlQuery() {
...
     @Test
     public void testWebSocketSubProtocol() throws Exception {
+        Vertx vertx = Vertx.vertx();
         HttpClient httpClient = vertx.createHttpClient();
         WebSocketConnectOptions options = new WebSocketConnectOptions().setPort(getPortFromConfig())
                 .addSubProtocol("graphql-ws").setURI("/graphql");
         CompletableFuture<Boolean> wsFuture = new CompletableFuture<>();
         httpClient.webSocket(options, event -> wsFuture.complete(event.succeeded()));
         Assertions.assertTrue(wsFuture.get(1, TimeUnit.MINUTES));
+        vertx.close();
```
Comment (cescoffier) [inline integration-tests/vertx-graphql/src/test/java/io/quarkus/vertx/graphql/it/VertxGraphqlTest.java]: No, that won't be enough. 
Closing a vert.x instance is asynchronous, so you need a countdown latch and use the async version.
In addition, if the test fails, you won't close the vert.x instances and resources will still be allocated (event loops...)

**Review by cescoffier — CHANGES_REQUESTED** [review]

File: integration-tests/vertx-graphql/src/test/java/io/quarkus/vertx/graphql/it/VertxGraphqlTest.java (hunk 9 above)
Comment (machi1990) [reply integration-tests/vertx-graphql/src/test/java/io/quarkus/vertx/graphql/it/VertxGraphqlTest.java]: Ouch, this slipped in fast. I'll update this part. Thanks

**Comment by machi1990** [comment]
> I would like having the input from @emmanuelbernard on having the UI in prod.
> The UI is a query editor, it can be dangerous to have it in prod. At least we should have a flag to disable it.

Thanks for this feedback. The UI is not enabled by default, so a user has  explicitly enable it. On the other hand, having a flag `quarkus.vertx-graphql.ui-enabled` to control whether we include the UI resources or not could be handy. Maybe the extension  could automatically enable the UI in dev mode. Is that a good way to go about it? @cescoffier @emmanuelbernard

**Comment by emmanuelbernard** [comment]
Yes that makes sense.

**Comment by machi1990** [comment]
> Yes that makes sense.

Thanks, I'll give it a spin in couple of hours.

**Comment by machi1990** [comment]
@emmanuelbernard @cescoffier I have added the config property.

File: integration-tests/vertx-graphql/src/test/java/io/quarkus/vertx/graphql/it/VertxGraphqlTest.java [hunk 10]
```diff
@@ -20,14 +20,22 @@
...
+    private static Vertx vertx;
+
+    @BeforeAll
+    public static void initializeVertx() {
+        vertx = Vertx.vertx();
+    }
+
+    @AfterAll
+    public static void closeVertx() {
+        vertx.close();
```
Comment (cescoffier) [inline integration-tests/vertx-graphql/src/test/java/io/quarkus/vertx/graphql/it/VertxGraphqlTest.java]: You need:

```
CountDownLatch latch = new CountDownLatch(1);
vertx.close(() -> {
     latch.countDown();
});
latch.await();
```

Comment (cescoffier) [reply integration-tests/vertx-graphql/src/test/java/io/quarkus/vertx/graphql/it/VertxGraphqlTest.java]: ^ pseudo-code :-D

File: extensions/vertx-graphql/deployment/src/test/java/io/quarkus/vertx/graphql/deployment/ErroneousConfigTest.java [hunk 11]
```diff
@@ -0,0 +1,25 @@
...
+
+    @RegisterExtension
+    static final QuarkusUnitTest config = new QuarkusUnitTest()
+            .setExpectedException(ConfigurationError.class)
+            .setArchiveProducer(() -> ShrinkWrap.create(JavaArchive.class)
+                    .addAsResource(new StringAsset("quarkus.vertx-graphql-ui.path=/\n"), "application.properties"));
+
+    @Test
+    public void shouldNotStartApplicationIfPathIsASlash() {
+        Assertions.fail();
```
Comment (cescoffier) [inline extensions/vertx-graphql/deployment/src/test/java/io/quarkus/vertx/graphql/deployment/ErroneousConfigTest.java]: I don't understand how this test works.

**Review by cescoffier — CHANGES_REQUESTED** [review]

**Comment by cescoffier** [comment]
almost there.

I would recommend rebasing the PR too.

File: extensions/vertx-graphql/deployment/src/test/java/io/quarkus/vertx/graphql/deployment/ErroneousConfigTest.java (hunk 11 above)
Comment (machi1990) [reply extensions/vertx-graphql/deployment/src/test/java/io/quarkus/vertx/graphql/deployment/ErroneousConfigTest.java]: Specifying a `/` results in  build failure - https://github.com/quarkusio/quarkus/pull/5253/files#diff-2e471b456c7129680f3d600014449819R17 so basically this test method will never be called.

File: integration-tests/vertx-graphql/src/test/java/io/quarkus/vertx/graphql/it/VertxGraphqlTest.java (hunk 10 above)
Comment (machi1990) [reply integration-tests/vertx-graphql/src/test/java/io/quarkus/vertx/graphql/it/VertxGraphqlTest.java]: Thanks, the other `vertx#close()` was to tempting for me. I'll change it :-)

**Comment by machi1990** [comment]
> almost there.
> 
> I would recommend rebasing the PR too.

Thanks for the review @cescoffier . I have updated the PR. it should be ready for another round on review.

**Comment by machi1990** [comment]
TCK test failures unrelated - cf https://github.com/quarkusio/quarkus/issues/5569

File: extensions/vertx-graphql/deployment/src/test/java/io/quarkus/vertx/graphql/deployment/ErroneousConfigTest.java (hunk 11 above)
Comment (cescoffier) [reply extensions/vertx-graphql/deployment/src/test/java/io/quarkus/vertx/graphql/deployment/ErroneousConfigTest.java]: Oh I see!

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
As build issues are unrelated, let's take the risk to merge it.

(and Thanks @machi1990 !)

**Comment by cescoffier** [comment]
ah no, @gsmet had commented on the PR too. I let him check his concerns.

**Comment by machi1990** [comment]
> ah no, @gsmet had commented on the PR too. I let him check his concerns.

Cool, I believe that @gsmet comment about the build item and a question about injection in native image to have been fixed or answered. Good to double check though before merging.

**Comment by machi1990** [comment]
> As build issues are unrelated, let's take the risk to merge it.
> 
> (and Thanks @machi1990 !)

Thanks @cescoffier 

Been a pleasure :-) We fixed quite a few things along the way, once this is merged we can close https://github.com/quarkusio/quarkus/issues/5448

File: extensions/vertx-graphql/deployment/src/main/java/io/quarkus/vertx/graphql/deployment/VertxGraphqlProcessor.java [hunk 12]
```diff
@@ -15,4 +32,36 @@ FeatureBuildItem feature() {
...
+            BuildProducer<RouteBuildItem> routes) {
+        boolean includeVertxGraphqlUi = launchMode.getLaunchMode().isDevOrTest() || config.alwaysInclude;
+
+        if (!includeVertxGraphqlUi) {
+            return;
+        }
+
+        if ("/".equals(config.path)) {
+            throw new ConfigurationError(
+                    "quarkus.vertx-graphql-ui.path was set to \"/\", this is not allowed as it blocks the application from serving anything else.");
```
Comment (gsmet) [inline extensions/vertx-graphql/deployment/src/main/java/io/quarkus/vertx/graphql/deployment/VertxGraphqlProcessor.java]: I think I would have preferred something like:
```
quarkus.vertx-graphql.ui.path
```
with the config root being the name of the extension and `ui` being a config group. It's far more consistent with the rest of Quarkus.

**Review by gsmet — CHANGES_REQUESTED** [review]
Looks good overall. I added a small comment about the config properties. WDYT?

File: extensions/vertx-graphql/deployment/src/main/java/io/quarkus/vertx/graphql/deployment/VertxGraphqlProcessor.java (hunk 12 above)
Comment (machi1990) [reply extensions/vertx-graphql/deployment/src/main/java/io/quarkus/vertx/graphql/deployment/VertxGraphqlProcessor.java]: As discussed on Zulip, let’s do it :-)

File: extensions/vertx-graphql/deployment/src/main/java/io/quarkus/vertx/graphql/deployment/VertxGraphqlProcessor.java [hunk 13]
```diff
@@ -15,4 +32,37 @@ FeatureBuildItem feature() {
...
+            return;
+        }
+
+        String path = config.ui.path;
+        if ("/".equals(path)) {
+            throw new ConfigurationError(
+                    "quarkus.vertx-graphql.ui.path was set to \"/\", this is not allowed as it blocks the application from serving anything else.");
+        }
+
+        Handler<RoutingContext> handler = recorder.handler(path);
```
Comment (gsmet) [inline extensions/vertx-graphql/deployment/src/main/java/io/quarkus/vertx/graphql/deployment/VertxGraphqlProcessor.java]: I think you should probably remove a potential trailing slash from the value.

**Review by gsmet — CHANGES_REQUESTED** [review]
Looks good to me except for one last comment.

File: extensions/vertx-graphql/deployment/src/main/java/io/quarkus/vertx/graphql/deployment/VertxGraphqlProcessor.java (hunk 13 above)
Comment (machi1990) [reply extensions/vertx-graphql/deployment/src/main/java/io/quarkus/vertx/graphql/deployment/VertxGraphqlProcessor.java]: Good catch.

Comment (machi1990) [reply extensions/vertx-graphql/deployment/src/main/java/io/quarkus/vertx/graphql/deployment/VertxGraphqlProcessor.java]: done

**Comment by machi1990** [comment]
Just rebased with master to pick config updates from #5387.

File: extensions/vertx-graphql/deployment/src/main/java/io/quarkus/vertx/graphql/deployment/VertxGraphqlProcessor.java [hunk 14]
```diff
@@ -15,4 +32,37 @@ FeatureBuildItem feature() {
...
+        if (path.isEmpty()) {
+            throw new ConfigurationError(
+                    "quarkus.vertx-graphql.ui.path was set to \"/\", this is not allowed as it blocks the application from serving anything else.");
+        }
+
+        Handler<RoutingContext> handler = recorder.handler(path);
+        routes.produce(new RouteBuildItem(path, handler));
+        routes.produce(new RouteBuildItem(path + "/*", handler));
+        displayableEndpoints.produce(new NotFoundPageDisplayableEndpointBuildItem(path + "/"));
+        nativeResourcesProducer.produce(new NativeImagePackageResourceBuildItem("io/vertx/ext/web/handler/graphiql"));
```
Comment (gsmet) [inline extensions/vertx-graphql/deployment/src/main/java/io/quarkus/vertx/graphql/deployment/VertxGraphqlProcessor.java]: Question: do we want to use the package like that? Or do we want it to be a real package?

I mean it looks a bit more like a resource directory.

So maybe rename it `NativeImageResourceDirectoryBuildItem`?

File: extensions/vertx-graphql/deployment/src/main/java/io/quarkus/vertx/graphql/deployment/VertxGraphqlProcessor.java [hunk 15]
```diff
@@ -15,4 +32,37 @@ FeatureBuildItem feature() {
...
+            BuildProducer<RouteBuildItem> routes) {
+        boolean includeVertxGraphqlUi = launchMode.getLaunchMode().isDevOrTest() || config.ui.alwaysInclude;
+
+        if (!includeVertxGraphqlUi) {
+            return;
+        }
+
+        String path = config.ui.path.replaceAll("/+$", "");
+        if (path.isEmpty()) {
+            throw new ConfigurationError(
```
Comment (gsmet) [inline extensions/vertx-graphql/deployment/src/main/java/io/quarkus/vertx/graphql/deployment/VertxGraphqlProcessor.java]: I think we should use `ConfigurationException` now.

**Review by gsmet — CHANGES_REQUESTED** [review]
I added a few minor comments.

File: extensions/vertx-graphql/deployment/src/main/java/io/quarkus/vertx/graphql/deployment/VertxGraphqlProcessor.java [hunk 16]
```diff
@@ -15,4 +32,37 @@ FeatureBuildItem feature() {
...
+            BuildProducer<NativeImagePackageResourceBuildItem> nativeResourcesProducer, VertxGraphqlConfig config,
+            LaunchModeBuildItem launchMode, BuildProducer<NotFoundPageDisplayableEndpointBuildItem> displayableEndpoints,
+            BuildProducer<RouteBuildItem> routes) {
+        boolean includeVertxGraphqlUi = launchMode.getLaunchMode().isDevOrTest() || config.ui.alwaysInclude;
+
+        if (!includeVertxGraphqlUi) {
+            return;
+        }
+
+        String path = config.ui.path.replaceAll("/+$", "");
```
[the remark this answers is not in the document]
Comment (machi1990) [reply extensions/vertx-graphql/deployment/src/main/java/io/quarkus/vertx/graphql/deployment/VertxGraphqlProcessor.java]: done

File: extensions/vertx-graphql/deployment/src/main/java/io/quarkus/vertx/graphql/deployment/VertxGraphqlProcessor.java (hunk 14 above)
Comment (machi1990) [reply extensions/vertx-graphql/deployment/src/main/java/io/quarkus/vertx/graphql/deployment/VertxGraphqlProcessor.java]: let's go with the the renaming :-)

File: extensions/vertx-graphql/deployment/src/main/java/io/quarkus/vertx/graphql/deployment/VertxGraphqlProcessor.java (hunk 15 above)
Comment (machi1990) [reply extensions/vertx-graphql/deployment/src/main/java/io/quarkus/vertx/graphql/deployment/VertxGraphqlProcessor.java]: done

**Comment by gsmet** [comment]
I just pushed a rebase to be extra sure :). Let's wait for CI.

**Review by gsmet — APPROVED** [review]

**Comment by machi1990** [comment]
> I just pushed a rebase to be extra sure :). Let's wait for CI.

Thanks, I was about to do that. the CI failure was related to a compilation failure which was fixed in master :-)

**Comment by machi1990** [comment]
All green :-) Merging, thanks @all
