### PR TITLE
Configuration property to use only system sources

### LINKED ISSUE #19549: Quarkus CLI finds and uses rogue application.properties files and crashes
### Describe the bug

I recently installed the Quarkus CLI and upon first execution of `quarkus version` it spit out tons of warnings and I had no idea why (I was not in any project directory, rather was in my home directory where I never put projects). Turns out I had a rogue `application.properties` in the directory (with no other project-related files) and it loaded and parsed it as part of the CLI runtime.

If that file is a binary (e.g. by renaming a .zip file to `application.properties`) then Quarkus CLI crashes.

### Expected behavior

No warnings on first execution, in a directory with no project.

### Actual behavior

With a valid properties file:

```sh
➜  ~ quarkus version
2021-08-20 12:48:03,173 WARN  [io.qua.config] (main) Unrecognized configuration key "quarkus.hibernate-orm.sql-load-script" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
2021-08-20 12:48:03,173 WARN  [io.qua.config] (main) Unrecognized configuration key "quarkus.datasource.username" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
2021-08-20 12:48:03,173 WARN  [io.qua.config] (main) Unrecognized configuration key "quarkus.datasource.jdbc.url" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
2021-08-20 12:48:03,174 WARN  [io.qua.config] (main) Unrecognized configuration key "quarkus.hibernate-orm.database.generation" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
2021-08-20 12:48:03,174 WARN  [io.qua.config] (main) Unrecognized configuration key "quarkus.datasource.db-kind" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
2021-08-20 12:48:03,174 WARN  [io.qua.config] (main) Unrecognized configuration key "quarkus.datasource.password" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
Client Version 2.1.2.Final
```
With a binary named `application.properties`:
```sh
➜  ~ cp v3.11.0.zip application.properties
➜  ~ quarkus version
Exception in thread "main" java.lang.ExceptionInInitializerError
	at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:60)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:65)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:30)
Caused by: java.lang.IllegalArgumentException: Malformed \uxxxx encoding.
```

### How to Reproduce?

1. Take any file and call it `application.properties`
1. Install CLI with: `curl -Ls https://sh.jbang.dev | bash -s - app install --fresh --force quarkus@quarkusio`
1. While in the same directory as the rogue file, run `quarkus version`

### Output of `uname -a` or `ver`

Darwin jfalkner-OSX 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64

### Output of `java -version`

```
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)
```

### GraalVM version (if different from Java)

N/A

### Quarkus version or git rev

Client Version 2.1.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Quarkus CLI

### Additional information

I'm concerned it may be possible to do something nasty with a cleverly-designed `application.properties`.

### PR DESCRIPTION
**Pull request by radcortez**
- Fixes #19549

### CODE REVIEW

**Comment by gsmet** [comment]
@ebullient could you have a look at this one when you have time?

File: core/deployment/src/main/java/io/quarkus/deployment/ConfigBuildTimeConfig.java [hunk 1]
```diff
@@ -0,0 +1,16 @@
...
+@ConfigRoot(name = ConfigItem.PARENT, phase = ConfigPhase.BUILD_TIME)
+public class ConfigBuildTimeConfig {
+    /**
+     * <p>
+     * Set this to <code>true</code> to read configuration from system properties and environment variables only.
+     * </p>
+     */
+    @ConfigItem(name = "config.sources.system-only", defaultValue = "false")
+    public boolean systemOnly;
+}
```
Comment (ebullient) [inline core/deployment/src/main/java/io/quarkus/deployment/ConfigBuildTimeConfig.java:16]: This is confusing. It is build time config... and it isn't clear from this description if this constrains config sources at BOTH build time AND runtime or just runtime or ..

File: core/deployment/src/main/java/io/quarkus/deployment/steps/ConfigBuildSteps.java [hunk 2]
```diff
@@ -97,4 +102,20 @@ void nativeServiceProviders(
...
+    }
+
+    private static class SystemOnlySources implements BooleanSupplier {
+        ConfigBuildTimeConfig configBuildTimeConfig;
+
+        @Override
+        public boolean getAsBoolean() {
+            return configBuildTimeConfig.systemOnly;
+        }
+    }
```
Comment (ebullient) [inline core/deployment/src/main/java/io/quarkus/deployment/steps/ConfigBuildSteps.java:120]: I am a little confused now. This was at least partly driven by what the Quarkus CLI needs. It absolutely needs to read application.properties _at build time_. It just can't/shouldn't look for anything else at runtime. 

But I think I'm probably reading too much into this... This would constrain what is available to static init (which is recorded at build time but run at run time?)

File: core/runtime/src/main/java/io/quarkus/runtime/configuration/SystemOnlySourcesConfigBuilder.java [hunk 3]
```diff
@@ -0,0 +1,17 @@
+package io.quarkus.runtime.configuration;
+
+import io.smallrye.config.SmallRyeConfigBuilder;
+
+public class SystemOnlySourcesConfigBuilder implements ConfigBuilder {
+    @Override
+    public SmallRyeConfigBuilder configBuilder(final SmallRyeConfigBuilder builder) {
+        // TODO - This still discovers sources in the classpath. Should we also remove them?
```
Comment (ebullient) [inline core/runtime/src/main/java/io/quarkus/runtime/configuration/SystemOnlySourcesConfigBuilder.java:8]: Config sources on the classpath (where they are defaults) is fine.. those would also be present at build time.

My thinking was always that constraining to system resources was solely/only a runtime concern.

File: core/deployment/src/main/java/io/quarkus/deployment/ConfigBuildTimeConfig.java (hunk 1 above)
Comment (radcortez) [reply core/deployment/src/main/java/io/quarkus/deployment/ConfigBuildTimeConfig.java:16]: No, it only applies to runtime configuration.

File: core/deployment/src/main/java/io/quarkus/deployment/steps/ConfigBuildSteps.java (hunk 2 above)
Comment (radcortez) [reply core/deployment/src/main/java/io/quarkus/deployment/steps/ConfigBuildSteps.java:120]: Yes, because we do generate the static init / runtime configuration during the build. So, if the configuration is active, we just produce config builders for static and runtime that remove the unwanted config sources.

File: core/runtime/src/main/java/io/quarkus/runtime/configuration/SystemOnlySourcesConfigBuilder.java (hunk 3 above)
Comment (radcortez) [reply core/runtime/src/main/java/io/quarkus/runtime/configuration/SystemOnlySourcesConfigBuilder.java:8]: Yes, nothing here changes what happens at build time.

This will remove sources that contain `application.properties` and the `.env` file.

Comment (ebullient) [reply core/runtime/src/main/java/io/quarkus/runtime/configuration/SystemOnlySourcesConfigBuilder.java:8]: (can we remove the todo?)

File: core/deployment/src/main/java/io/quarkus/deployment/ConfigBuildTimeConfig.java (hunk 1 above)
Comment (radcortez) [reply core/deployment/src/main/java/io/quarkus/deployment/ConfigBuildTimeConfig.java:17]: Clarified the javadoc.

File: core/runtime/src/main/java/io/quarkus/runtime/configuration/SystemOnlySourcesConfigBuilder.java (hunk 3 above)
Comment (radcortez) [reply core/runtime/src/main/java/io/quarkus/runtime/configuration/SystemOnlySourcesConfigBuilder.java]: Yes. Done!

**Review by ebullient — APPROVED** [review]
