### PR TITLE
Dev MCP: Expose last exception via Dev MCP tool

### LINKED ISSUE #53297: DevStar: Expose last exception via Dev MCP
Add a Dev MCP tool that exposes the last exception (compilation, deployment, or runtime) from a running Quarkus dev mode application.

This is useful for coding agents (e.g. quarkus-agent-mcp) that need to detect and react to errors programmatically.

The tool should return: exception class, message, full stack trace, source location in user code, and whether it's a deployment or runtime exception.

### PR DESCRIPTION
**Pull request by phillip-kruger**
When a compilation, deployment, or runtime error occurs, agents have no
programmatic way to retrieve the exception details — they must parse logs.

Adds a `getLastException` Dev MCP tool that captures exceptions via
`ExceptionNotificationBuildItem` (runtime) and `RuntimeUpdatesProcessor`
(deployment), returning structured data: exception class, message, full
stack trace, user code location, and cause chain.

- Closes: #53297

### CODE REVIEW

File: extensions/devui/deployment/src/test/java/io/quarkus/devui/deployment/exception/ExceptionProcessorTest.java
Comment (geoand) [inline extensions/devui/deployment/src/test/java/io/quarkus/devui/deployment/exception/ExceptionProcessorTest.java:1]: This test is mostly useless IMHO

File: extensions/devui/deployment/src/main/java/io/quarkus/devui/deployment/exception/ExceptionProcessor.java [hunk 1]
```diff
@@ -0,0 +1,156 @@
...
+ */
+public class ExceptionProcessor {
+
+    private static final String NAMESPACE = "devui-exceptions";
+    static final int MAX_STACK_TRACE_LINES = 200;
+    static final int MAX_CAUSE_MESSAGE_LENGTH = 500;
+    static final int MAX_CAUSE_DEPTH = 5;
+
+    // Immutable snapshot of a runtime exception and its context
+    record ExceptionSnapshot(Throwable exception, StackTraceElement userCodeLocation, long timestamp) {
```
Comment (geoand) [inline extensions/devui/deployment/src/main/java/io/quarkus/devui/deployment/exception/ExceptionProcessor.java]: Is `timestamp` of any use?

File: extensions/devui/deployment/src/main/java/io/quarkus/devui/deployment/exception/ExceptionProcessor.java [hunk 2]
```diff
@@ -0,0 +1,156 @@
...
+
+/**
+ * Exposes the last exception (compilation, deployment, or runtime) as a Dev MCP tool.
+ */
+public class ExceptionProcessor {
+
+    private static final String NAMESPACE = "devui-exceptions";
+    static final int MAX_STACK_TRACE_LINES = 200;
+    static final int MAX_CAUSE_MESSAGE_LENGTH = 500;
+    static final int MAX_CAUSE_DEPTH = 5;
```
Comment (geoand) [inline extensions/devui/deployment/src/main/java/io/quarkus/devui/deployment/exception/ExceptionProcessor.java:27]: Why only 5?

Comment (phillip-kruger) [reply extensions/devui/deployment/src/main/java/io/quarkus/devui/deployment/exception/ExceptionProcessor.java:27]: This can be a lot of data (and tokens) when used with agents. 5 was just a initial try that seems to work in my manual testing, but I can make that an input, so that the agent can control that.

File: extensions/devui/deployment/src/main/java/io/quarkus/devui/deployment/exception/ExceptionProcessor.java (hunk 1 above)
Comment (phillip-kruger) [reply extensions/devui/deployment/src/main/java/io/quarkus/devui/deployment/exception/ExceptionProcessor.java]: It was as an attempt to know that the exception is a stale one, but I now added clearException too, so the agent can clear. It does not do any harm, but let me have a look again

**Review by geoand — APPROVED** [review]

File: extensions/devui/deployment/src/main/java/io/quarkus/devui/deployment/exception/ExceptionProcessor.java [hunk 3]
```diff
@@ -0,0 +1,163 @@
...
+
+        actions.actionBuilder()
+                .methodName("getLastException")
+                .description(
+                        "Get the last exception that occurred in this Quarkus application. Returns compilation errors, deployment failures, hot-reload problems, or runtime exceptions with full stack traces and source locations. Deployment problems clear automatically on the next successful reload. For runtime exceptions, call clearLastException after handling to avoid seeing the same exception again.")
+                .enableMcpFunctionByDefault()
+                .parameter("maxCauseDepth",
+                        "Maximum depth for the cause chain (default " + MAX_CAUSE_DEPTH + ")")
+                .function(params -> {
+                    int causeDepth = MAX_CAUSE_DEPTH;
```
Comment (cescoffier) [inline extensions/devui/deployment/src/main/java/io/quarkus/devui/deployment/exception/ExceptionProcessor.java:56]: Why having this variable if it's a constant.

File: extensions/devui/deployment/src/main/java/io/quarkus/devui/deployment/exception/ExceptionProcessor.java [hunk 4]
```diff
@@ -0,0 +1,163 @@
...
+                    String maxCauseDepthParam = params.get("maxCauseDepth");
```
Comment (cescoffier) [inline extensions/devui/deployment/src/main/java/io/quarkus/devui/deployment/exception/ExceptionProcessor.java:57]: Would it make more sense to actually pass cause and suppressed exceptions?

**Review by cescoffier — CHANGES_REQUESTED** [review]
Much better, a few comments:

- I would add some explanation around the timestamp
- I would add a bit more tests (cause chain, suppressed exception, circular exception, stack trace truncation...).
- The description still mention maxCauseDepth while it got removed.

File: extensions/devui/deployment/src/main/java/io/quarkus/devui/deployment/exception/ExceptionProcessor.java (hunk 3 above)
Comment (phillip-kruger) [reply extensions/devui/deployment/src/main/java/io/quarkus/devui/deployment/exception/ExceptionProcessor.java:56]: causeDepth can be overridden by the agent as an input. So by default its the constant, by could be overridden

File: extensions/devui/deployment/src/main/java/io/quarkus/devui/deployment/exception/ExceptionProcessor.java (hunk 4 above)
Comment (phillip-kruger) [reply extensions/devui/deployment/src/main/java/io/quarkus/devui/deployment/exception/ExceptionProcessor.java:57]: Not sure, let's see how this go. I assume there is value for the agent to see the full stack trace

**Comment by phillip-kruger** [comment]
@cescoffier 

> I would add some explanation around the timestamp

It's been removed.

> I would add a bit more tests (cause chain, suppressed exception, circular exception, stack trace truncation...).

Done

> The description still mention maxCauseDepth while it got removed.

It's not removed, it's just an input with a default now

**Comment by cescoffier** [comment]
🤖 Automatically associated with the **WG - Dev Star** Working Group based on AI classification.

File: extensions/devui/deployment/src/main/java/io/quarkus/devui/deployment/exception/ExceptionProcessor.java [hunk 5]
```diff
@@ -0,0 +1,163 @@
...
+                    if (maxCauseDepthParam != null && !maxCauseDepthParam.isBlank()) {
+                        causeDepth = Integer.parseInt(maxCauseDepthParam);
```
Comment (cescoffier) [inline extensions/devui/deployment/src/main/java/io/quarkus/devui/deployment/exception/ExceptionProcessor.java]: You need to be more defensive here. Remember, it's the model asking you to call this method; you need to validate the input, it may not be an int. Typically, it can be "three". So, at least catch the NumberFormatException.

Comment (cescoffier) [reply extensions/devui/deployment/src/main/java/io/quarkus/devui/deployment/exception/ExceptionProcessor.java]: I would fall back to default if it's not an integer, or a valid integer (negative, 0)

Comment (cescoffier) [reply extensions/devui/deployment/src/main/java/io/quarkus/devui/deployment/exception/ExceptionProcessor.java]: Also, very high values should be discarded.

File: extensions/devui/deployment/src/test/java/io/quarkus/devui/devmcp/DevMcpTest.java [hunk 6]
```diff
@@ -205,6 +205,80 @@ public void testToolsCallWithEmptyArgs() {
...
+        RestAssured
+                .given()
+                .contentType(ContentType.JSON)
+                .body(jsonBody)
+                .when()
+                .post("/q/dev-mcp")
+                .then()
+                .statusCode(200)
+                .body("id", CoreMatchers.equalTo(10))
+                .body("result.content.text", CoreMatchers.notNullValue());
```
Comment (cescoffier) [inline extensions/devui/deployment/src/test/java/io/quarkus/devui/devmcp/DevMcpTest.java]: Can we improve that assertion? It's a bit vague.

File: extensions/devui/deployment/src/test/java/io/quarkus/devui/devmcp/DevMcpTest.java [hunk 7]
```diff
@@ -205,6 +205,80 @@ public void testToolsCallWithEmptyArgs() {
...
+        RestAssured
+                .given()
+                .contentType(ContentType.JSON)
+                .body(jsonBody)
+                .when()
+                .post("/q/dev-mcp")
+                .then()
+                .statusCode(200)
+                .body("id", CoreMatchers.equalTo(11))
+                .body("result.content.text", CoreMatchers.notNullValue());
```
Comment (cescoffier) [inline extensions/devui/deployment/src/test/java/io/quarkus/devui/devmcp/DevMcpTest.java]: Can we improve that assertion? It's a bit vague.

File: extensions/devui/deployment/src/main/java/io/quarkus/devui/deployment/exception/ExceptionProcessor.java [hunk 8]
```diff
@@ -0,0 +1,163 @@
...
+    static final int MAX_CAUSE_MESSAGE_LENGTH = 500;
+    static final int MAX_CAUSE_DEPTH = 5;
+
+    // Immutable snapshot of a runtime exception and its context
+    record ExceptionSnapshot(Throwable exception, StackTraceElement userCodeLocation) {
+    }
+
+    // Static so state survives hot reloads (build steps re-execute on reload).
+    // Single AtomicReference ensures atomic read/write of all fields together.
+    private static final AtomicReference<ExceptionSnapshot> lastRuntimeSnapshot = new AtomicReference<>();
```
Comment (cescoffier) [inline extensions/devui/deployment/src/main/java/io/quarkus/devui/deployment/exception/ExceptionProcessor.java:35]: We will have to see if we need to release this object at some point.

File: extensions/devui/deployment/src/main/java/io/quarkus/devui/deployment/exception/ExceptionProcessor.java [hunk 9]
```diff
@@ -0,0 +1,163 @@
...
+                .build();
+
+        buildTimeActionProducer.produce(actions);
+    }
+
+    static void populateExceptionDetails(Map<String, Object> result, Throwable throwable, int maxCauseDepth) {
+        result.put("exceptionClass", throwable.getClass().getName());
+        result.put("message", throwable.getMessage());
+
+        StringWriter sw = new StringWriter();
```
Comment (cescoffier) [inline extensions/devui/deployment/src/main/java/io/quarkus/devui/deployment/exception/ExceptionProcessor.java]: I know close is a no-op, but better call it anyway.

File: extensions/devui/deployment/src/main/java/io/quarkus/devui/deployment/exception/ExceptionProcessor.java [hunk 10]
```diff
@@ -0,0 +1,163 @@
...
+                })
+                .build();
+
+        actions.actionBuilder()
+                .methodName("clearLastException")
+                .description("Clear the last recorded runtime exception.")
+                .enableMcpFunctionByDefault()
+                .function(ignored -> {
+                    lastRuntimeSnapshot.set(null);
+                    Map<String, Object> result = new LinkedHashMap<>();
```
Comment (cescoffier) [inline extensions/devui/deployment/src/main/java/io/quarkus/devui/deployment/exception/ExceptionProcessor.java]: Do we have to make the map writable? If not, use Map.of

Comment (cescoffier) [reply extensions/devui/deployment/src/main/java/io/quarkus/devui/deployment/exception/ExceptionProcessor.java]: Also, why do you need key-ordering guarantees?

**Review by cescoffier — CHANGES_REQUESTED** [review]
Just a few more comments. Nothing major.

File: extensions/devui/deployment/src/main/java/io/quarkus/devui/deployment/exception/ExceptionProcessor.java (hunk 9 above)
Comment (cescoffier) [reply extensions/devui/deployment/src/main/java/io/quarkus/devui/deployment/exception/ExceptionProcessor.java]: I don't see where you call `close`

**Review by cescoffier — APPROVED** [review]
Only the call to `close` is missing, but as I said, it's mostly cosmetic.
