### PR TITLE
Import properties from build.gradle and remove hardcoded quarkus.package.output-directory

### LINKED ISSUE #28896: Make Gradle plugin configuration more idiomatic
### Describe the bug

Currently in order to configure the behavior of the Quarkus Gradle plugin, a build author needs to set project properties, e.g. if I want to change the package type I need to add the following to the build script:

```kotlin
ext {
  set("quarkus.package.type", "mutable-jar")
}
```

From a Gradle perspective this is a quite strange way to configure a plugin, especially because the plugin adds a custom project extension, which would be the place a Gradle build author would look for configuration options.

### Expected behavior

The QuarkusExtension that is added to the build should provide ways to configure aspects of the packaging:

```kotlin
quarkus {
    package {
        type.set("mutable-jar")
    }
}
```

### Actual behavior

QuarkusExtension does not provide options to configure packaging so one has to know that it's configured via project properties.

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### LINKED ISSUE #28897: Gradle plugin output tracking breaks if `quarkus.package.output-directory` is configured
### Describe the bug

The `QuarkusBuild` task does not provide a way to reconfigure it's output location. Instead it's hardcoded to `$buildDir/quarkus-app`. At the same time, users can configure the output location by setting the `quarkus.package.output-directory`. This will cause the build to create the output in a different location. However Gradle is unaware of this location, so UP-TO-DATE checking and build caching breaks because Gradle will track the location returned from `QuarkusBuild.getFastJar()`. Furthermore it's not possible to easily consume `QuarkusBuild` output from another task, because `QuarkusBuild` is unaware of the changed location.

### Expected behavior

When changing the output location via `quarkus.package.output-directory` this should also change the value returned from `QuarkusBuild.getFastJar()` accordingly. #28896 is related to this.

### Actual behavior

Gradle is unaware of changes to `QuarkusBuild` output location configured by `quarkus.package.output-directory`

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jacobdotcosta**
* Import properties defined in the `build.gradle` file using the syntax described below
* Replace the hard-coded output location if a `quarkus.package.output-directory` value is passed through configuration

`build.gradle` quarkus property definition:
```groovy
quarkus {
    properties {
        set("package.type", "uber-jar")
        set("package.output-directory", "build-gradle-output-dir")
    }
}
```

Closes #28897
Closes #28896

### CODE REVIEW

**Comment by geoand** [comment]
Thanks a lot for this @jacobdotcosta!

I'll let @glefloch and @aloubyansky comment

File: integration-tests/gradle/src/main/resources/build-configuration/gradle.properties [hunk 1]
```diff
@@ -0,0 +1,6 @@
+quarkusPlatformArtifactId=quarkus-bom
+quarkusPlatformGroupId=io.quarkus
+quarkusPlatformVersion=999-SNAPSHOT
```
Comment (aloubyansky) [inline integration-tests/gradle/src/main/resources/build-configuration/gradle.properties:3]: Please do not use 999-SNAPSHOT (or any real Quarkus release) versions. We've run into issues before when globally changing versions when releasing.
You could see how we pass/complete current Quarkus version in other tests.

Comment (jacobdotcosta) [reply integration-tests/gradle/src/main/resources/build-configuration/gradle.properties:3]: I'll remove it as it's not required. I added it to try fixing a problem I had with the tests but it was unrelated and I forgot to remove it.

**Comment by jacobdotcosta** [comment]
I'm not sure how to fix these errors as I'm not sure how they relate to this PR.

_Gradle Tests - JDK 11 Windows_ has 1 error which is the following:

```
2022-12-20T15:01:02.2716136Z 2022-12-20 15:01:01,864 SEVERE [org.jun.jup.eng.exe.JupiterEngineExecutionContext] (main) Caught exception while closing extension context: org.junit.jupiter.engine.descriptor.MethodExtensionContext@55877274: java.io.IOException: Failed to delete temp directory D:\a\quarkus\quarkus\integration-tests\gradle\target\junit10212038324867675530. The following paths could not be deleted (see suppressed exceptions for details): , src, src\main, src\main\resources
```

_JVM Tests - JDK 17 MacOS M1_ seems to fail to start the tests with:

```
2022-12-20T15:12:01.6643110Z Starting machine "podman-machine-default"
2022-12-20T15:12:02.2066100Z Waiting for VM ...
2022-12-20T15:12:17.2901010Z Mounting volume... /Volumes/actions-files/githubactions:/Volumes/actions-files/githubactions
2022-12-20T15:12:17.5569370Z Error: exit status 255
2022-12-20T15:12:17.5585510Z ##[error]Process completed with exit code 125.
...
2022-12-20T15:12:17.6112590Z /Volumes/actions-files/githubactions/actions-runner/_work/_temp/1f2eaa41-292c-4c25-99ae-db2308b6f743.sh: line 1: devtools/gradle/gradlew: No such file or directory
2022-12-20T15:12:17.6116990Z ##[error]Process completed with exit code 1.
```

**Comment by aloubyansky** [comment]
The MacOS is known to be problematic. The `QuarkusPluginFunctionalTest.canDetectUpToDateBuild` does seem to be related in some way though.

**Comment by jacobdotcosta** [comment]
I've downloaded the logs and checked the error messages. From what I can understand the `io.quarkus.gradle.QuarkusPluginFunctionalTest#canDetectUpToDateBuild` test case consists in executing the tests 2 times to make sure Gradle detects they haven't changed so it won't execute the tests again.

The problem seems to be that somewhere in the process the extension is trying to cleanup the `src\main\resources` sub-folder of the temporary project directory and that is failing probably because windows is locking a file. I cannot identify in the logs the step on which this failure is happening as the test class doesn't show up in the stacktrace.

@aloubyansky , could you assist me on a way of tracking this error? Do you know of any way I could try reproducing this error without having a MS Windows VM?

Thank you.

**Comment by aloubyansky** [comment]
Perhaps, instead `@TempDir File projectRoot` creating and recursively deleting a project dir "manually" will help?

**Comment by jacobdotcosta** [comment]
> Perhaps, instead `@TempDir File projectRoot` creating and recursively deleting a project dir "manually" will help?

I think I found the problem. I wasn't closing the Stream that reads the `application.properties` file. This last commit should have fixed this.

**Review by aloubyansky — APPROVED** [review]

**Comment by aloubyansky** [comment]
Thanks @jacobdotcosta!

File: devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/extension/QuarkusPluginExtension.java [hunk 2]
```diff
@@ -182,4 +188,13 @@ public Path appJarOrClasses() {
...
         return classesDir;
     }
+
+    public Map<String, String> getQuarkusBuildProperties() {
+        return quarkusBuildProperties;
+    }
+
+    public void set(String name, @Nullable String value) {
+        quarkusBuildProperties.put(String.format("quarkus.%s", name), value);
+    }
```
Comment (britter) [inline devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/extension/QuarkusPluginExtension.java:198]: This should use [lazy configuration APIs](https://docs.gradle.org/current/userguide/lazy_configuration.html). So `quarkusBuildProperties` should not be of type `Map<String, String>` but `MapProperty<String, String>`. At the same time there should be an overload for `set` where value can be passed as a `Property<String>`.

Another issue with this solution is that is assumes everything is a string, but that's not the case. For example the `package.output-directoy` should probably be of type `DirectoryProperty` (see https://docs.gradle.org/current/userguide/lazy_configuration.html#working_with_files_in_lazy_properties).

Comment (aloubyansky) [reply devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/extension/QuarkusPluginExtension.java:198]: @britter thanks a lot for the review. Let us know if you would like to submit a PR yourself. That'd be much appreciated.

Comment (jacobdotcosta) [reply devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/extension/QuarkusPluginExtension.java:198]: Thank you for the feedback @britter , I'm reviewing the docs. I can also submit a PR to fix this, if you won't.

Comment (britter) [reply devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/extension/QuarkusPluginExtension.java:198]: I don't see myself doing this before the end of the month. So if you have some time @jacobdotcosta please go ahead.

Comment (aloubyansky) [reply devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/extension/QuarkusPluginExtension.java:198]: It doesn't look like it was fixed yet. @britter in case you have some time to contribute the fixes you mentioned previously, it'll be much appreciated. Thanks!

Comment (britter) [reply devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/extension/QuarkusPluginExtension.java:198]: @aloubyansky I managed to address the first part of it in #30713. I'm not sure it's possible to address the second part using a map based approached.
