### PR TITLE
Load test classes with runtime classloader 

### LINKED ISSUE #272: Ecosystem CI failure NoClassDefFoundError: io/quarkiverse/pact/devmodetest/farm/FarmContractTest
First failure: https://github.com/quarkiverse/quarkus-pact/actions/runs/13278513756/job/37072354959

```
2025-02-12T06:42:07.8022970Z [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 9.810 s -- in io.quarkiverse.pact.it.TheTestModeContractTestIT
2025-02-12T06:42:07.8047813Z [INFO] Running io.quarkiverse.pact.it.NormalModeContractIT
2025-02-12T06:42:12.9134924Z [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 5.108 s <<< FAILURE! -- in io.quarkiverse.pact.it.NormalModeContractIT
2025-02-12T06:42:12.9141399Z [ERROR] io.quarkiverse.pact.it.NormalModeContractIT.pactVerificationTestTemplate(PactVerificationContext)[1] -- Time elapsed: 0.003 s <<< ERROR!
2025-02-12T06:42:12.9146261Z java.lang.RuntimeException: java.lang.ExceptionInInitializerError
2025-02-12T06:42:12.9150951Z 	at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:611)
2025-02-12T06:42:12.9155810Z 	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:706)
2025-02-12T06:42:12.9161485Z 	at java.base/java.util.Optional.orElseGet(Optional.java:364)
2025-02-12T06:42:12.9165273Z 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
2025-02-12T06:42:12.9167567Z 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
2025-02-12T06:42:12.9174026Z 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
2025-02-12T06:42:12.9175055Z 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
2025-02-12T06:42:12.9176086Z 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
2025-02-12T06:42:12.9177327Z 	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
2025-02-12T06:42:12.9178340Z 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
2025-02-12T06:42:12.9179618Z 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
2025-02-12T06:42:12.9180825Z 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
2025-02-12T06:42:12.9181909Z 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
2025-02-12T06:42:12.9183106Z 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
2025-02-12T06:42:12.9185705Z 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
2025-02-12T06:42:12.9186830Z 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
2025-02-12T06:42:12.9189000Z 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
2025-02-12T06:42:12.9189904Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
2025-02-12T06:42:12.9190639Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
2025-02-12T06:42:12.9191308Z Caused by: java.lang.ExceptionInInitializerError
2025-02-12T06:42:12.9191938Z 	at java.base/java.lang.Class.forName0(Native Method)
2025-02-12T06:42:12.9192559Z 	at java.base/java.lang.Class.forName(Class.java:467)
2025-02-12T06:42:12.9193647Z 	at io.quarkus.runner.bootstrap.StartupActionImpl.run(StartupActionImpl.java:289)
2025-02-12T06:42:12.9194776Z 	at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:224)
2025-02-12T06:42:12.9195953Z 	at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:578)
2025-02-12T06:42:12.9197260Z 	at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:628)
2025-02-12T06:42:12.9197989Z 	... 1 more
2025-02-12T06:42:12.9198433Z Caused by: java.lang.RuntimeException: Failed to start quarkus
2025-02-12T06:42:12.9199304Z 	at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
2025-02-12T06:42:12.9199866Z 	... 7 more
2025-02-12T06:42:12.9200724Z Caused by: java.lang.NoClassDefFoundError: io/quarkiverse/pact/devmodetest/farm/FarmContractTest
2025-02-12T06:42:12.9201834Z 	at io.quarkiverse.pact.devmodetest.farm.FarmContractTest_Bean.<init>(Unknown Source)
2025-02-12T06:42:12.9202825Z 	at io.quarkus.arc.setup.Default_ComponentsProvider.addBeans1(Unknown Source)
2025-02-12T06:42:12.9203738Z 	at io.quarkus.arc.setup.Default_ComponentsProvider.getComponents(Unknown Source)
2025-02-12T06:42:12.9204600Z 	at io.quarkus.arc.impl.ArcContainerImpl.<init>(ArcContainerImpl.java:129)
2025-02-12T06:42:12.9205465Z 	at io.quarkus.arc.Arc.initialize(Arc.java:38)
2025-02-12T06:42:12.9206152Z 	at io.quarkus.arc.runtime.ArcRecorder.initContainer(ArcRecorder.java:52)
2025-02-12T06:42:12.9207327Z 	at io.quarkus.runner.recorded.ArcProcessor$initializeContainer1770303700.deploy_0(Unknown Source)
2025-02-12T06:42:12.9208359Z 	at io.quarkus.runner.recorded.ArcProcessor$initializeContainer1770303700.deploy(Unknown Source)
2025-02-12T06:42:12.9209065Z 	... 8 more
2025-02-12T06:42:12.9209710Z Caused by: java.lang.ClassNotFoundException: io.quarkiverse.pact.devmodetest.farm.FarmContractTest
2025-02-12T06:42:12.9210791Z 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
2025-02-12T06:42:12.9211881Z 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
2025-02-12T06:42:12.9212794Z 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
2025-02-12T06:42:12.9214290Z 	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:569)
2025-02-12T06:42:12.9215517Z 	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:517)
2025-02-12T06:42:12.9216751Z 	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:569)
2025-02-12T06:42:12.9218259Z 	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:517)
2025-02-12T06:42:12.9219058Z 	... 16 more
```

### LINKED ISSUE #8446: Broken QuarkusTestExtension
When using Quarkus 1.3.1.Final or current master against our Registry, I get this:
* https://gist.githubusercontent.com/alesj/86aae892c3aa35113ce358737700b4b7/raw/8a3e105e971916bd2f997692d145043d5810ee2a/gistfile1.txt

Zulip thread:
* https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Broken.20QuarkusTestExtension.20.2E.2E.2E

As mentioned / described, we use custom JUnit5 extension
* https://github.com/Apicurio/apicurio-registry/blob/master/utils/tests/src/main/java/io/apicurio/registry/utils/tests/RegistryServiceExtension.java
(it's similar to existing JUnit5 Parameter extension, just custom for RegistryService)

To reproduce, simply change Quarkus version here:
* https://github.com/Apicurio/apicurio-registry
and run "mvn clean install"

### LINKED ISSUE #38987: Mockito fails to mock non-public inner class in continuous testing due to classloading issues
### Describe the bug

The following primitive test (and tested class):
```java
@ExtendWith(MockitoExtension.class)
public class FooTest {

    @Mock
    private Foo.Inner mock;

    @Test
    public void test() {

    }
}
```
```java
public class Foo {

    static class Inner {
    }
}
```
works fine in IDE or mvn, but fails with `mvn quarkus:test`:
```
ERROR [io.qua.test] (Test runner thread) Test FooTest#test() failed 
: org.mockito.exceptions.base.MockitoException: 
Mockito cannot mock this class: class org.acme.Foo$Inner.

Mockito can only mock non-private & non-final classes, but the root cause of this error might be different.
Please check the full stacktrace to understand what the issue is.
If you're still not sure why you're getting this error, please open an issue on GitHub.


Java               : 17
JVM vendor name    : Azul Systems, Inc.
JVM vendor version : 17.0.9+8-LTS
JVM name           : OpenJDK 64-Bit Server VM
JVM version        : 17.0.9+8-LTS
JVM info           : mixed mode, emulated-client, sharing
OS name            : Linux
OS version         : 5.15.0-94-generic


Underlying exception : org.mockito.exceptions.base.MockitoException: 
Cannot create mock for class org.acme.Foo$Inner

The type is not public and its mock class is loaded by a different class loader.
This can have multiple reasons:
 - You are mocking a class with additional interfaces of another class loader
 - Mockito is loaded by a different class loader than the mocked type (e.g. with OSGi)
 - The thread's context class loader is different than the mock's class loader
	at org.mockito.junit.jupiter.MockitoExtension.beforeEach(MockitoExtension.java:160)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	Suppressed: java.lang.NullPointerException: Cannot invoke "java.util.Set.forEach(java.util.function.Consumer)" because the return value of "org.junit.jupiter.api.extension.ExtensionContext$Store.remove(Object, java.lang.Class)" is null
		at org.mockito.junit.jupiter.MockitoExtension.afterEach(MockitoExtension.java:194)
		... 2 more
Caused by: org.mockito.exceptions.base.MockitoException: 
Cannot create mock for class org.acme.Foo$Inner

The type is not public and its mock class is loaded by a different class loader.
This can have multiple reasons:
 - You are mocking a class with additional interfaces of another class loader
 - Mockito is loaded by a different class loader than the mocked type (e.g. with OSGi)
 - The thread's context class loader is different than the mock's class loader
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:168)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:399)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:190)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:410)
	... 3 more


ERROR [io.qua.test] (Test runner thread) >>>>>>>>>>>>>>>>>>>> Summary: <<<<<<<<<<<<<<<<<<<<
FooTest#test()
```

### Expected behavior

No failure, should work as in IDE or mvn.

### Actual behavior

Fails with classloading issue.

### How to Reproduce?

1. clone https://github.com/famod/q_ctest-inner
2. `mvn clean verify` (passes)
3. `mvn quarkus:test` fails

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

3.7.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

The problem vanishes after adding `public` to the inner class.

I have another case where adding `public` helps, but that's not an inner class.

It has been an issue for many releases now, I just haven't found the time to report it.
I'm rather sure (IIRC) it was actually working some months ago.

### LINKED ISSUE #42000: Kotlin junit ParameterizedTest with functions as argument, not working anymore (Kotlin 2.0)
### Describe the bug

We have some parameterized tests in kotlin with functions as argument, which do not work anymore with kotlin 2.0 and quarkus 3.13.0.CR1. Using kotlin 1.9.24 does still work.
```
    @ParameterizedTest
    @MethodSource("provider")
    fun test1(
        function1: (String) -> String,
    )
    
        companion object {

        val function1: (String) -> String = { r: String -> r }

        @JvmStatic
        fun provider(): Stream<Arguments> {
            return Stream.of(Arguments.of(function1))
        }
```

This results in the following error:

```
java.lang.IllegalArgumentException: argument type mismatch

	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:973)
	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:903)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestTemplateMethod(QuarkusTestExtension.java:863)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```

Not sure if this is a quarkus, a junit or a kotlin problem. Maybe somebody could take a look? 

As a workaround, if the function is defined like so it does work:

```
        @JvmStatic
        fun provider(): Stream<Arguments> {
            return Stream.of(Arguments.of(::fun2))
        }

        @JvmStatic
        fun fun2(s:String) = s
```

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

https://github.com/robp94/quarkus-kotlin-junit

Run the included test.

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

21

### Quarkus version or git rev

3.13.0.CR1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven

### Additional information

_No response_

### LINKED ISSUE #42006: Regression in 3.13.0.CR1: Lambda expression from custom serializable interface used as `@QuarkusTest` method parameter fails with `ClassNotFoundException`
### Describe the bug

Up until 3.12.3 you can create a lambda expression from something like:
```java
    public interface SerializableCustom extends Serializable {
        String get();
    }
```
and pass it over to a `@QuarkusTest` method as a parameter, e.g.:
```java
@QuarkusTest
public class LambdaParamTest {

    @ParameterizedTest
    @ArgumentsSource(LambdaProvider.class)
    void test(final SerializableCustom lambda) {
        // ...
    }

    private static class LambdaProvider implements ArgumentsProvider {

        @Override
        public Stream<? extends Arguments> provideArguments(final ExtensionContext context) {
            return Stream.of(Arguments.of((SerializableCustom) () -> "foobar"));
        }
    }
```
but with 3.13.0.CR1 you'll get:
```
java.lang.IllegalStateException: java.lang.ClassNotFoundException: org.acme.LambdaParamTest$LambdaProvider$$Lambda/0x00007fa1844f3158
	at io.quarkus.test.junit.internal.NewSerializingDeepClone.clone(NewSerializingDeepClone.java:132)
	[...]
```

### Expected behavior

Cloning works for lambdas created from custom serializable interfaces.

### Actual behavior

Exception is thrown.

### How to Reproduce?

[q_test-lambda.zip](https://github.com/user-attachments/files/16313547/q_test-lambda.zip)

- `./mvnw clean test` fails
- `./mvnw clean test -Dquarkus.platform.version=3.12.3` passes

Note that the reproducer also includes a working lambda example for both versions (using a subclass of `java.util.function.Supplier<T>`).

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

3.13.0.CR1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

I suppose this is related to #40906, /cc @holly-cummins 

Workaround: Use anonymous class instead.

### LINKED ISSUE #44320: @ParameterizedTest with  @MethodSource do not work when using @QuarkusTest annotation
### Describe the bug

in @BeforeAll I am fetching list from injected service, convert it to map and i want to use keys of that map to loop through them and perform a test on each key. 
I am using @ParameterizedTest and  @MethodSource for it. However when i get to "getData()" method, the map is empty, even though it was filled in @BeforeAll

### Expected behavior

the map has data

### Actual behavior

the map is empty

### How to Reproduce?

Reproducer: https://github.com/dasha-klim/quarkus_test.git

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

17

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle

### Additional information

_No response_

### LINKED ISSUE #45349: QuarkusTest: consider removing the test profile support for `@Nested` tests
Currently, it is possible to specify a test profile for a `@Nested` test (inner class of a top-level test class). However, this may cause troubles if the enclosing test class defines a different test profile; i.e. the enclosing class should be tested against a different application build. Keep in mind that Quarkus always needs to obtain the instance of the enclosing test class from the CDI container.

More specifically, if a CDI bean `Foo` is only enabled in the profile `FooProfile` then it cannot be injected in the test class `FooTest` because it would cause unsatisfied dependency in the test class `FooTest$FooNested`:

```java
@TestProfile(FooProfile.class) // -> enables Foo
public class FooTest {
   
    @Inject Foo foo; // this is legal and works fine when FooTest#test() is run

    void test() {
       // ...
    }

   @Nested
   @TestProfile(FooNestedProfile.class) // -> Foo is not enabled here
   class FooNested {
     
      void test() {
         // ...this test always fails because when the test app is built FooTest#foo results in an unsatisfied dependency
      } 
     
   }

}
```

### LINKED ISSUE #46383: ConfigProvider.getConfig().getOptionalValue("..").get() does not work in JUnitExtension any more
### Describe the bug

since 3.18 it is not possible any more to get config in a junit-extension
```
public class JUnitExtensionUsingConfig implements BeforeEachCallback, AfterEachCallback {

    @Override
    public void afterEach(ExtensionContext extensionContext) {  //FIXME this doesn't work
        Config config = ConfigProvider.getConfig();
        Optional<String> value = config.getOptionalValue("quarkus.http.root-path", String.class);
        value.get(); //exception here, no value set
    }

    @Override
    public void beforeEach(ExtensionContext extensionContext) {//FIXME this doesn't work
        Config config = ConfigProvider.getConfig();
        Optional<String> value = config.getOptionalValue("quarkus.http.root-path", String.class);
        value.get(); //exception here, no value set
    }
}
java.util.NoSuchElementException: No value present
        at java.base/java.util.Optional.get(Optional.java:143)
        at org.acme.JUnitExtensionUsingConfig.beforeEach(JUnitExtensionUsingConfig.java:24)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
        Suppressed: java.util.NoSuchElementException: No value present
                at java.base/java.util.Optional.get(Optional.java:143)
                at org.acme.JUnitExtensionUsingConfig.afterEach(JUnitExtensionUsingConfig.java:17)
                ... 2 more
```

### Expected behavior

should work `ConfigProvider.getConfig()` or at least with `ConfigProvider.getConfig(SomeWellDocumented.class.getClassLoader())`

### Actual behavior

fails with `java.util.NoSuchElementException: No value present`

### How to Reproduce?

https://github.com/flyinfish/quarkus--configprovider-junitext
follow readme

### Output of `uname -a` or `ver`

Linux C70C7391 5.15.167.4-microsoft-standard-WSL2 #1 SMP Tue Nov 5 00:21:55 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk 21.0.6 2025-01-21 LTS

### Quarkus version or git rev

3.18.*

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.9 (8e8579a9e76f7d015ee5ec7bfcdc97d260186937)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by holly-cummins**
### Bugs fixed by this PR 

- Resolves #45349
- Resolves #8446 
- Resolves #42000
- Resolves #42006
- Resolves #44320
- Resolves #38987 
- Resolves #46383
- Resolves https://github.com/quarkiverse/quarkus-pact/issues/272

### Bugs created by this PR (doh!)

- Creates #45785 
- Creates #46542

### Outstanding issues/breaking changes (input to release notes)

- `@TestProfile` on `@Nested` tests are not supported anymore (fixes #45349).
- Version 3 of Maven Surefire and Failsafe is required, and version 2 is unlikely to work.
- Changes the order of some tests; tests should not depend on execution order if they don't set one explicitly, so this *shouldn't* cause customer failures, but it did cause failures for us (see, for example, #45955 and #45960)
- Dev services start in the discovery phase (#45785, we know how to fix this quickly)
- Increased memory footprint running tests. For suites using multiple profiles and resources, more metaspace may be needed.
- Accessing ConfigProvider from a custom JUnit condition results in ServiceConfigurationError · Issue #47081 · workaround is to set a TCCL to `this.getClass().getClassLoader()`
- Whatever causes https://github.com/quarkiverse/quarkiverse/issues/55#issuecomment-2812323118, diagnosis TBD

### What problem is this solving? 

We see a lot of problems caused by the fact that we load test classes with the deployment classloader, and then intercept the execution and reload the classes with the runtime classloader. Although the new test is loaded with the runtime classloader, its arguments are still loaded with the system classloader. To work around that we sometimes need to clone the arguments by serializing and de-serializing. This was always brittle and no longer worked at all on Java 17+ (until #40601 fixed that). We also see issues because parts of the test infrastructure see the 'wrong' instance of the class. See, for example, https://github.com/quarkiverse/quarkus-pact/issues/73 and https://github.com/quarkusio/quarkus/issues/22611. 

We have several feature raised against the JUnit team to allow us more control over classloading. The first of this features was introduced in JUnit 5.10, and allows an interceptor to be registered before any tests are launched. This interceptor can set a thread context classloader, which is then used by JUnit to load tests. 

My experiments with this feature were thoroughly disappointing. It turns out, setting a TCCL early in the test lifecycle doesn't really help us, because we overwrite our 'early' TCCL with other TCCLs later in the test lifecycle. The following diagram shows some of the places we set the TCCL.

life-of-a-tccl-2023-02-28-1714

Source: https://excalidraw.com/#json=HFPHIKx8wv0iiyXgNhAzw,8IlEmPcMRvm9pfCGShdClQ

What if we just used one of the existing interception points to set the 'right' classloader, _before_ tests are loaded? If the tests were loaded with our preferred classloader, we wouldn’t need to intercept the factory. Loading the tests with the runtime classloader needs us to move some of our app initialisation earlier in the lifecycle, but I don't think there's any fundamental barrier to this. (We would have had to do this with a solution based on the new JUnit Launcher Interceptor anyway.)

The logic for starting Quarkus needs to be in the test discovery phase, rather than in the extension. This allows us to create the runtime classloader *before* the test is loaded. The JUnitTest runner already knows about the Quarkus Extension, so it’s only a small extra bit of knowledge to do some of the startup actions. 

This only gets us part of the way, though. @stuartwdouglas raised the point that if we have to set only a single classloader, that's not very flexible, because we have a runtime classloader for each test profile. A Quarkus test run doesn't just use one classloader, it uses several. Every resource/unique profile triggers an app relaunch, which means a new classloader. What I've done to handle this is create a FacadeClassLoader. It takes the classloading requests, and then either routes them on to the quarkus application (for vanilla @QuarkusTests), or, if there's a profile/resource, it makes a new app + classloader and sends the request to that.

What we used to before was load a throwaway copy of the the test, pass it to JUnit discovery, let JUnit launch it, and then intercept the execution, figure out what profiles+resources the test declares, create a quarkus app with that information, start the quarkus app, reload the test with the runtime classloader of the quarkus app (and clone its parameters), and execute the test.

The new model is load a throwaway copy of the the test, figure out what profiles+resources the test declares, create a quarkus app with that information, reload the test with the runtime classloader of the quarkus app, pass the ‘right’ class to JUnit discovery, let JUnit launch it, and then intercept the execution, start the quarkus app, and execute the test.

One fundamental limitation of "load tests with the classloader used to execute them" is that a single test cannot run with multiple classloaders, which means it cannot support multiple profiles. We know some people do use this feature, but we also know there have been suggestions that we drop support for it, since it is complex to support (#45349). There is an easy workaround, which is to use one test per profile. 

# Thoughts on serialization and cloning

A big initial goal of this PR was to get rid of the xstream serialization, since it didn't work on Java 17+. #40601 fixes this issue by switching to use the JBoss marshaller for serialization. Does that mean this work item isn't needed any more? No, although it does mean its benefits are smaller. Here's why it's still useful:

- Even with the JBoss serializer, higher-level test infrastructure (such as `@TestTemplate`) does not see Quarkus bytecode transformations done by extensions
- Although the JBoss serializer works a lot better than xstream with the Java 17 access restrictions (as in, it works), serialization may continue to be a challenge going forward. See https://bugs.openjdk.org/browse/JDK-8164908 for some context. Most serializers use `sun.misc.unsafe`, but `unsafe` is shrinking. It seems certain the JDK team will have to come up with some solution and API to open up access for serializers, but the final design could have security implications (perhaps opening up access in a blanket way), or performance implications (reflection fun), or user experience implications (a need to manually set flags such as `--enable-serialization`?).  If we can avoid serialization, we avoid all that.

## Todo before this merges 

- [ ] Start investigating parallel tests
- [X] Start looking at classloader leaks
- [X] Flaky test reproducer - https://github.com/quarkusio/quarkus/pull/46945
- [X] Fix the ecosystem CI for pact

## Todo after this merges 
- Monitor ecosystem CI for new failures; we do not have coverage of every code path in our current suite (for example, the tests added in #46389 broke with this change, by going down an uncovered code path)
- Address the 'do not start dev services in augmentation' issue
- Removal of all dead code in `QuarkusTestExtension`
- Consolidation of duplicated code between AppMakerHelper and TestSupport
- Tests for interaction with QuarkusProdModeTest, particularly for the tests in #35124
- Continued improvements to fix hacky config usage in existing tests (such as relying on mutable system properties, etc)
- Consolidation + streamlining of logic in the test order (unify around a key-based approach?)
- Adding tests based on various outstanding issues which do not yet have reproducers in our test suite

### CODE REVIEW

**Comment by The-Funk** [comment]
Still watching this one. I've created a minimal not-working-example to see if this fixes it. :)

**Comment by holly-cummins** [comment]
> Still watching this one. I've created a minimal not-working-example to see if this fixes it. :)

Still going on it ... :) 

The profile support in normal mode turned out to be a bit thorny, so looking at that now. I haven't checked for a while, but at one point I had reproducers for three of the test-classloading-related defects. One was passing, but two (annoyingly) were failing. If your reproducer is shareable, I'm happy to take it and include it in what I'm checking, or to add it into the test suites, if it's a gap in what we're testing now. (It'd be worth checking what I've added in https://github.com/quarkusio/quarkus/pull/35124 to see if one of those covers your scenario, too.)

File: independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/app/QuarkusBootstrap.java [hunk 1]
```diff
@@ -309,12 +311,21 @@ public Supplier<DependencyInfoProvider> getDependencyInfoProvider() {
         return depInfoProvider;
     }
 
+    // TODO where is the cleanest place for this to live? We don't want code which has been given classes
```
Comment (geoand) [inline independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/app/QuarkusBootstrap.java:314]: cc @aloubyansky

File: independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/app/CuratedApplication.java [hunk 2]
```diff
@@ -440,6 +448,11 @@ public void close() {
         augmentationElements.clear();
     }
 
+    // TODO delete this? the model doesn't really work?
```
Comment (geoand) [inline independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/app/CuratedApplication.java:451]: Doesn't really work, in what sense?

**Comment by holly-cummins** [comment]
@geoand , FYI I've just spotted that these changes would break the JBeret Ecosystem CI. I think I know what the fix is, but I'll need to make an update. Hopefully it won't be a big update, just a tweak to the quarkus test detection logic to catch whatever edge case is breaking it in the JBeret tests.

**Comment by geoand** [comment]
Thanks for the heads up!

File: independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/app/CuratedApplication.java (hunk 2 above)
Comment (holly-cummins) [reply independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/app/CuratedApplication.java:451]: Good question. That comment is so old I wasn't entirely sure myself, when I was reviewing the TODOs. :) 

I *think* what it's referring to is that at an early stage of development I had good ideas about re-using more of the curated application + base classloaders between different applications. That is, if I decided we needed to restart, instead of throwing everything out, I'd do a light tidy and then re-use the lower levels of the classloader stack. That might still be a good thing to do, and it would reduce the memory footprint of doing things this way. If we can do restarts for continuous testing we should be able to achieve some reuse in normal mode testing. But I never made it work. 

So I think that `tidy()` method is a vestige of my attempts to re-use stuff. The question is whether it's now totally pointless because cleanup happens elsewhere, or whether it's still a useful part of the cleanup that we do between restarts. I'll inspect the code and try and work it out.

Comment (geoand) [reply independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/app/CuratedApplication.java:451]: 🙏🏽

File: test-framework/junit5/src/main/java/io/quarkus/test/junit/classloading/FacadeClassLoader.java [hunk 3]
```diff
@@ -0,0 +1,553 @@
...
+import io.quarkus.test.junit.QuarkusTestExtension;
+import io.quarkus.test.junit.TestProfile;
+import io.quarkus.test.junit.TestResourceUtil;
+
+/**
+ * JUnit has many interceptors and listeners, but it does not allow us to intercept test discovery in a fine-grained way that
+ * would allow us to swap the thread context classloader.
+ * Since we can't intercept with a JUnit hook, we hijack from inside the classloader.
+ * <p>
+ * We need to load all our test classes in one go, during the discovery phase, before we start the applications.
```
Comment (geoand) [inline test-framework/junit5/src/main/java/io/quarkus/test/junit/classloading/FacadeClassLoader.java:48]: > We need to load all our test classes in one go, during the discovery phase

Is this a current JUnit limitation?

Comment (geoand) [reply test-framework/junit5/src/main/java/io/quarkus/test/junit/classloading/FacadeClassLoader.java:48]: Got it thanks! Any pointers at where I can place debug breakpoints to see this in action?
I would like to understand the current limitations so after we get this in, we can go back to the JUnit 5 people with a details on what we use so far and why it's not enough.

File: core/deployment/src/main/java/io/quarkus/deployment/dev/testing/JunitTestRunner.java [hunk 4]
```diff
@@ -140,12 +144,12 @@ public Runnable prepare() {
             long start = System.currentTimeMillis();
             ClassLoader old = Thread.currentThread().getContextClassLoader();
             QuarkusClassLoader tcl = testApplication.createDeploymentClassLoader();
+            deploymentClassLoader = tcl;
             LogCapturingOutputFilter logHandler = new LogCapturingOutputFilter(testApplication, true, true,
-                    TestSupport.instance().get()::isDisplayTestOutput);
+                    TestSupport.instance()
+                            .get()::isDisplayTestOutput);
+            // TODO do we want to do this setting of the TCCL? I think it just makes problems?
```
Comment (aloubyansky) [inline core/deployment/src/main/java/io/quarkus/deployment/dev/testing/JunitTestRunner.java:151]: Any specific hints about the possible problems?

File: independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/app/QuarkusBootstrap.java (hunk 1 above)
Comment (aloubyansky) [reply independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/app/QuarkusBootstrap.java:314]: I think `ApplicationModel.getAppArtifact().getWorkspaceModule().getTestSources()` and then either `getOutputTree()` or `getSourceDirs().getOutputDir()` is meant to be that. But we need to see how/where it fits in this case.

File: test-framework/common/src/main/java/io/quarkus/test/common/PathTestHelper.java [hunk 5]
```diff
@@ -137,13 +138,22 @@ public static Path getTestClassesLocation(Class<?> testClass) {
...
             try {
                 resource = URI.create(resource.getFile().substring(0, resource.getFile().indexOf('!'))).toURL();
                 return toPath(resource);
             } catch (MalformedURLException e) {
                 throw new RuntimeException("Failed to resolve the location of the JAR containing " + testClass, e);
             }
+        } else if (resource.getProtocol().equals("quarkus")) {
+            // This is loaded with a quarkus classloader, so we can ask it directly
+            QuarkusClassLoader qcl = (QuarkusClassLoader) testClass.getClassLoader();
+            return qcl.getCuratedApplication().getQuarkusBootstrap().getTestClassesLocation();
```
Comment (aloubyansky) [inline test-framework/common/src/main/java/io/quarkus/test/common/PathTestHelper.java:155]: This is where we (theoretically) could try `qcl.getCuratedApplication().getApplicationModel().getAppArtifact().getWorkspaceModule().getTestSources().getOutputDir()`

File: test-framework/junit5/src/main/java/io/quarkus/test/junit/AppMakerHelper.java [hunk 6]
```diff
@@ -0,0 +1,352 @@
...
+
+    private PrepareResult createAugmentor(final Class<?> requiredTestClass, String displayName, boolean isContinuousTesting,
+            CuratedApplication curatedApplication,
+            Class<? extends QuarkusTestProfile> profile,
+            Collection<Runnable> shutdownTasks) throws Exception {
+
+        if (curatedApplication == null) {
+            curatedApplication = makeCuratedApplication(requiredTestClass, displayName, isContinuousTesting, shutdownTasks);
+        }
+        Path testClassLocation = getTestClassLocationIncludingPossibilityOfGradleModel(requiredTestClass);
```
Comment (aloubyansky) [inline test-framework/junit5/src/main/java/io/quarkus/test/junit/AppMakerHelper.java:88]: It seems like `testClassLocation` should already be available from the `curatedApplication` here? Could they be different here? If they are, isn't it an issue?

File: test-framework/junit5/src/main/java/io/quarkus/test/junit/classloading/FacadeClassLoader.java (hunk 3 above)
Comment (holly-cummins) [reply test-framework/junit5/src/main/java/io/quarkus/test/junit/classloading/FacadeClassLoader.java:55]: So the best way to play with the code paths is to take one of the `test-profile-profile*` projects from the `target` directory of  `integration-tests/maven` and run it, either in dev mode or with `mvn verify`, or you can run the tests in the IDE and breakpoint from there. (Make sure you take the project from the target directory). 

For breakpoints, it kind of depends what you want to see. To get right in at the beginning, before JUnit does discovery, it would be `intercept` in `CustomLauncherInterceptor`, and then you can step through from there. Or you can intercept `loadClass` in the `FacadeClassLoader`. At the moment, `QuarkusTestExtension` also uses just about every hook JUnit provides and so we can breakpoint there. 

But I think this limitation about discovery isn't entirely a missing hook, because I think our 'ideal' scenario is somewhat self-contradictory. At the moment, with my changes, we can hook before discovery, but we don't 100% like that, (a) because we need to do an ugly pre-load of the class to read profile information and decide what classloader it should be loaded with and (b) because we need to load everything up-front in the discovery stage, increasing our memory footprint and creating a risk of cross-talk if apps do things in the wrong startup phase. 

So we could say "give me a hook to let me amend the list of discovered classes post-discovery." That would simplify our code a bit, because deciding on the classpath for the peeking classloader becomes JUnit's problem. :) And it means we could rebrand the FacadeClassLoader as `The UsefulThingThatReallyIsNotAClassLoader`, which would *feel *better. But all the rest of the logic in the FacadeClassLoader, of reading the class, deciding whether it needs a new classloader, managing a list of classloaders, etc, would stay the same. And we'd still be loading everything upfront, before any test execution started. So it would be better, but it would be a kind of cosmetic improvement.

So then you say 'ok, give me a hook which happens post-discovery, and before individual tests are executed'. In that case, we lose a simplification we get with this model, which is that the class orderer can be really dumb – we just sort by classloader. If we defer classload to just before test execution, we'd have to sort the JUnit version of classes, not the 'real' one, same as we do today, so the classloader has to read the class, evaluate the profile and resources, and so on. I guess this isn't a disaster since it could share logic with the 'decide who loads this class' class, so that's not a tragedy, especially since we still need a smart orderer for component tests and integration tests and main tests. 

But getting the exact right place for this hook is non obvious. We probably don't want any part of JUnit to see the original class, because that inconsistency between 'what JUnit sees' and 'what eventually gets run' is part of what causes all the problems with parameters, and so on. JUnit has a lot of hooks (https://junit.org/junit5/docs/current/user-guide/#extensions-lifecycle-callbacks and https://junit.org/junit5/docs/current/user-guide/#extensions-test-instance-factories). I do wonder a bit about the [instance factories](https://junit.org/junit5/docs/current/api/org.junit.jupiter.api/org/junit/jupiter/api/extension/TestInstanceFactory.html); I assume there was a good reason we didn't use them anywhere but the `QuarkusDevModeTest`, but they look like an improvement over the `main` implementation. I think it would have fixed some of the current issues. 

But. An instance factory approach would still leave some functional gaps that we/I resolve by loading classes with the right classloader pre-discovery. For example, if an extension used bytecode instrumentation to add some JUnit annotations to a class, like `@Disabled` or `@ExtendWith`, swapping the classes at instantiation-time would be way too late. By that time JUnit would have already inspected the class and made evaluation decisions. 

So what we really want is something that lets us load the class pre-discovery, before JUnit ever sees the class, but not have to have the consequences of loading the class pre-discovery. :) And maybe that's something for us to work out in our internal architecture, because I'm not sure any JUnit hook could give us that.

File: independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/app/CuratedApplication.java (hunk 2 above)
Comment (holly-cummins) [reply independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/app/CuratedApplication.java]: I've removed `tidy()`, and then I spotted that if I remove it, the `CuratedApplication` no longer even needs a reference to the runtime classloader. So that shrinks the diff a tiny bit, which is good, and slightly reduces the 'store references ALL the objects EVERYWHERE` aspect of my change, which is better: https://github.com/quarkusio/quarkus/actions/runs/13842188108

File: test-framework/junit5/src/main/java/io/quarkus/test/junit/AppMakerHelper.java (hunk 6 above)
Comment (holly-cummins) [reply test-framework/junit5/src/main/java/io/quarkus/test/junit/AppMakerHelper.java:90]: You're totally right! Let me try that out.

File: test-framework/junit5/src/main/java/io/quarkus/test/junit/classloading/FacadeClassLoader.java (hunk 3 above)
Comment (holly-cummins) [reply test-framework/junit5/src/main/java/io/quarkus/test/junit/classloading/FacadeClassLoader.java:55]: It's also worth following https://github.com/junit-team/junit5/issues/3028, which is a feature request for something quite similar to what we want/need – if I understand the proposal correctly, t would allow `QuarkusTestExtension` to declare what kind of classloader should be used for a test, and making it work with things like `TestTemplate` would be the job of the JUnit framework, and not us. :)

File: test-framework/junit5/src/main/java/io/quarkus/test/junit/AppMakerHelper.java (hunk 6 above)
Comment (holly-cummins) [reply test-framework/junit5/src/main/java/io/quarkus/test/junit/AppMakerHelper.java]: Implemented in https://github.com/quarkusio/quarkus/pull/34681/commits/9dcd37826e182b78402c4119c1399e66a407de67, although it turns out to only be a marginal code saving. Testing in https://github.com/quarkusio/quarkus/actions/runs/13845822559

File: test-framework/common/src/main/java/io/quarkus/test/common/PathTestHelper.java (hunk 5 above)
Comment (holly-cummins) [reply test-framework/common/src/main/java/io/quarkus/test/common/PathTestHelper.java]: As discussed in other comments, this ended up being a 15-liner, so I isolated it to its own method :)

File: core/deployment/src/main/java/io/quarkus/deployment/dev/testing/JunitTestRunner.java (hunk 4 above)
Comment (holly-cummins) [reply core/deployment/src/main/java/io/quarkus/deployment/dev/testing/JunitTestRunner.java:151]: I need to try removing the setting of the TCCL and do a full test run to see what happens without it. In the 'old' world, the tests needed a TCCL to be set before execution, because the test was loaded with the 'wrong' classloader. Now the TCCL set at that point should be less necessary, because we set the TCCL to the FacadeClassLoader before discovery, and then as soon as test execution starts, we set the TCCL to be the test class's classloader. 

I did see problems with things like config. For example, in nested tests, when evaluate execution condition is called, the TCCL is the deployment classloader, which makes it harder to find the right config, because it has to be changed to a more useful TCCL. 

In my explorations, I never found a point where I was really *glad* that the TCCL was the deployment classloader; but I was only looking closely at some sections of the code, so there may be others where having the deployment classloader as the TCCL is absolutely necessary.

File: independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/app/CuratedApplication.java (hunk 2 above)
Comment (geoand) [reply independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/app/CuratedApplication.java]: 👍🏽

File: test-framework/junit5/src/main/java/io/quarkus/test/junit/classloading/FacadeClassLoader.java (hunk 3 above)
Comment (geoand) [reply test-framework/junit5/src/main/java/io/quarkus/test/junit/classloading/FacadeClassLoader.java:55]: Thanks a ton @holly-cummins!

Comment (holly-cummins) [reply test-framework/junit5/src/main/java/io/quarkus/test/junit/classloading/FacadeClassLoader.java:55]: If #3028 did become available we'd be back to needing to do the class analysis twice, once at the sorting stage, and then once when our classloader is triggered. So it would probably be better, but definitely not without trade-offs.

File: independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/app/QuarkusBootstrap.java (hunk 1 above)
Comment (holly-cummins) [reply independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/app/QuarkusBootstrap.java]: I've had a go, and I think this is the right long-term approach, but it's not completely trivial. `getOutputTree` gives the tree, which isn't what's wanted, and to use `getOutputDirs()` there needs to be a search/stream+filter on `getSourceDirs()`. So it's not a one-liner, but that's fine. 

A bigger problem was the fact that in the `AdditionalSourceSetsTest.executeFunctionalTest` test, we get

```
    java.lang.NullPointerException: Cannot invoke "io.quarkus.bootstrap.workspace.ArtifactSources.getOutputTree()" because "testSources" is null
        at io.quarkus.test.common.PathTestHelper.getTestClassesLocation(PathTestHelper.java:191)
        at io.quarkus.test.junit.AppMakerHelper.createAugmentor(AppMakerHelper.java:91)
        at io.quarkus.test.junit.AppMakerHelper.getStartupAction(AppMakerHelper.java:275)
        at io.quarkus.test.junit.classloading.FacadeClassLoader.getOrCreateRuntimeClassLoader(FacadeClassLoader.java:567)
        at io.quarkus.test.junit.classloading.FacadeClassLoader.getQuarkusClassLoader(FacadeClassLoader.java:471)
        at io.quarkus.test.junit.classloading.FacadeClassLoader.loadClass(FacadeClassLoader.java:346)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:534)
```

The way to solve that is to search all of the sources, not just the official `getTestSources()` ... and with that, the code is almost back to what it was when I started :) 

```
        ArtifactSources testSources = module.getTestSources();
        final String testClassFileName = ClassLoaderHelper
                .fromClassNameToResourceName(requiredTestClass.getName());
        if (testSources != null) {
            PathTree paths = testSources.getOutputTree();
            if (paths.contains(testClassFileName)) {
                for (SourceDir src : testSources.getSourceDirs()) {
                    if (Files.exists(src.getOutputDir().resolve(testClassFileName))) {
                        return src.getOutputDir();
                    }
                }
            }
        }
        // If there were no test sources, this may be a gradle application, with multiple source sets; we need to search them all
        for (String classifier : module.getSourceClassifiers()) {
            final ArtifactSources sources = module.getSources(classifier);
            if (sources.isOutputAvailable() && sources.getOutputTree().contains(testClassFileName)) {
                for (SourceDir src : sources.getSourceDirs()) {
                    if (Files.exists(src.getOutputDir().resolve(testClassFileName))) {
                        return src.getOutputDir();
                    }
                }
            }
        }

        validateTestDir(requiredTestClass, null, module);
        // The validation will throw a runtime exception, so this return is never hit
        return null;
```

Overall, though, I think this revision is cleaner, because it consistently uses the approach of searching in the module, instead of sometimes searching in the module and sometimes using a path that was stashed away earlier. I've also moved the searcher method to `PathTestHelper`, which is a more natural home for it. Thanks!

*update*

A maven test which exercised a similar scenario does *not* pass, even with the search across all source classifiers. Looking at what's going on, in maven, if we declare additional source sets, they don't turn up in `module.getSourceClassifiers()`. What the previous implementation did ended up being

```
URL resource = testClass.getClassLoader().getResource(fromClassNameToResourceName(testClass.getName()));
```
rather than trying to use anything from `curatedApplication.getApplicationModel().getAppArtifact().getWorkspaceModule();`, which is why it didn't hit this problem.

It feels like `workspaceModule` should handle the multiple source set maven case, but it also feels like that's a complex enough change that it shouldn't block this PR. I worked around things by just using the previous file-based search as a fallback if a module-based approach didn't work.

File: test-framework/common/src/main/java/io/quarkus/test/common/PathTestHelper.java [hunk 7]
```diff
@@ -161,14 +176,59 @@ public static Path getTestClassesLocation(Class<?> testClass) {
...
-        return getAppClassLocationForTestLocation(getTestClassesLocation(testClass));
+    public static Path getTestClassesLocation(Class<?> requiredTestClass, CuratedApplication curatedApplication) {
+        final WorkspaceModule module = curatedApplication.getApplicationModel().getAppArtifact().getWorkspaceModule();
+
+        ArtifactSources testSources = module.getTestSources();
+        final String testClassFileName = ClassLoaderHelper
+                .fromClassNameToResourceName(requiredTestClass.getName());
+        if (testSources != null) {
+            PathTree paths = testSources.getOutputTree();
+            if (paths.contains(testClassFileName)) {
```
Comment (aloubyansky) [inline test-framework/common/src/main/java/io/quarkus/test/common/PathTestHelper.java:187]: In this case, you could try doing
```
var testClassesDir = paths.apply(testClassFileName, visit -> {
    if(visit == null) {
        // this path does not exist in this path tree
        return null;
    }
    return visit.getRoot();
});
```

File: test-framework/junit5/src/main/java/io/quarkus/test/junit/AbstractJvmQuarkusTestExtension.java [hunk 8]
```diff
@@ -57,106 +46,70 @@ public class AbstractJvmQuarkusTestExtension extends AbstractQuarkusTestWithCont
...
-                addToBuilderIfConditionMet.accept(testResourcesLocation);
-            }
+        CuratedApplication curatedApplication = getCuratedApplication(requiredTestClass, context, shutdownTasks);
 
-            addToBuilderIfConditionMet.accept(appClassLocation);
-            final Path appResourcesLocation = PathTestHelper.getResourcesForClassesDirOrNull(appClassLocation, "main");
-            addToBuilderIfConditionMet.accept(appResourcesLocation);
-        }
+        // TODO need to handle the gradle case - can we put it in that method?
+        Path testClassLocation = getTestClassesLocation(requiredTestClass);
```
Comment (aloubyansky) [inline test-framework/junit5/src/main/java/io/quarkus/test/junit/AbstractJvmQuarkusTestExtension.java:68]:
```suggestion
        Path testClassLocation = getTestClassesLocation(requiredTestClass, curatedApplication);
```
Should it be that now?

File: test-framework/junit5/src/main/java/io/quarkus/test/junit/AppMakerHelper.java [hunk 9]
```diff
@@ -0,0 +1,299 @@
...
+    private static boolean hasPerTestResources;
+
+    private static List<Object> testMethodInvokers;
+    private Runnable configCleanup;
+
+    public static class PrepareResult {
+        protected final AugmentAction augmentAction;
+        public final QuarkusTestProfile profileInstance;
+        protected final CuratedApplication curatedApplication;
+        public final Path testClassLocation;
```
Comment (aloubyansky) [inline test-framework/junit5/src/main/java/io/quarkus/test/junit/AppMakerHelper.java:63]: This variable doesn't seem to be used besides the ctor init. You are looking for the test class location in `createAugmentor`

Comment (aloubyansky) [reply test-framework/junit5/src/main/java/io/quarkus/test/junit/AppMakerHelper.java:63]: Ah, sorry, it's initializing `PrepareResult` but still it doesn't appear to be used?

File: test-framework/common/src/main/java/io/quarkus/test/common/PathTestHelper.java (hunk 7 above)
Comment (holly-cummins) [reply test-framework/common/src/main/java/io/quarkus/test/common/PathTestHelper.java:187]: Will give it a go :)

File: test-framework/junit5/src/main/java/io/quarkus/test/junit/AbstractJvmQuarkusTestExtension.java (hunk 8 above)
Comment (holly-cummins) [reply test-framework/junit5/src/main/java/io/quarkus/test/junit/AbstractJvmQuarkusTestExtension.java:68]: Yes, it probably could be. Sometimes the version that accepts the curated application has to fall back to the 'low tech' version, but it should be safe to call the smarter version first. Will give it a try.

File: test-framework/junit5/src/main/java/io/quarkus/test/junit/AppMakerHelper.java (hunk 9 above)
Comment (holly-cummins) [reply test-framework/junit5/src/main/java/io/quarkus/test/junit/AppMakerHelper.java:63]: You're right, will get rid of it.

File: independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/classloading/QuarkusClassLoader.java [hunk 10]
```diff
@@ -803,11 +810,23 @@ private void ensureOpen() {
...
     @Override
     public String toString() {
         return "QuarkusClassLoader:" + name + "@" + Integer.toHexString(hashCode());
     }
 
+    public StartupAction getStartupAction() {
+        return startupAction;
+    }
+
+    public void setStartupAction(StartupAction startupAction) {
```
Comment (aloubyansky) [inline independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/classloading/QuarkusClassLoader.java:826]: This coupling looks like something we should review in a follow up.

File: independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/classloading/QuarkusClassLoader.java [hunk 11]
```diff
@@ -46,6 +48,9 @@ public class QuarkusClassLoader extends ClassLoader implements Closeable {
 
     protected static final String META_INF_SERVICES = "META-INF/services/";
 
+    private final CuratedApplication curatedApplication;
+    private StartupAction startupAction;
```
[the remark this answers is not in the document]
Comment (holly-cummins) [reply independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/classloading/QuarkusClassLoader.java:52]: It's so that QuarkusTestExtension has a way to start the application without creating a new StartupAction. So what we're creating is classes that can be 'started later'.

[the remark this answers is not in the document]
Comment (holly-cummins) [reply independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/classloading/QuarkusClassLoader.java:52]: The idea is that the classes carry around with them the information that's needed to allow their application to be started at the right time. The other option would be something like a big map that had the class names as keys and the associated startup action as entries, but that seemed ugly to me.

File: independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/classloading/QuarkusClassLoader.java (hunk 10 above)
Comment (holly-cummins) [reply independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/classloading/QuarkusClassLoader.java:826]: See comments in https://github.com/quarkusio/quarkus/pull/34681#discussion_r2005233801. I can't see a way of getting rid of it that doesn't involve global state ... but we can look at it, certainly.

File: independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/classloading/QuarkusClassLoader.java (hunk 11 above)
[the remark this answers is not in the document]
Comment (gsmet) [reply independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/classloading/QuarkusClassLoader.java:52]: Yeah, but if we leak class loaders - which we know happens - you end up with the `CuratedApplication` and `StartupAction` leaked too. I need to have a closer look at it.

BTW, just to be clear, I'm not saying we should block this PR until we find a solution for it. I just want to understand better what's going on.

[the remark this answers is not in the document]
Comment (holly-cummins) [reply independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/classloading/QuarkusClassLoader.java:52]: My feeling was that if we shove the classloaders and startup actions into global state, we're more likely to have leak problems. If we used a weak hashmap, we'd be no worse off than the current implementation (we don't leak the startup action unless we leak the classloader). If we used the class name as the key instead of the class, then we wouldn't need to worry about the classloaders leaking, but every startup action in the map would be stored indefinitely. So we'd need a mechanism to flush the map at the right time, and I'm not sure working that out is easier than just solving classloader leaks. 

One side effect of this PR is that it potentially reduces the amount of global state the test framework needs to carry around. At the moment we have a whole bunch of hacky static holder classes, and I'm thinking that we should be able to do a second  optimisation pass and get rid of some of them, since the test class is now much more 'self-sufficient'. At the moment we do still have to use global state to decide when we've flipped to a new application, so we can stop the old and and start the new one, but I think we could get rid of some of that. Starting the new one is easy (we just navigate to the application and check if it's started), so it's just stopping the old one which needs cross-test memory.

[the remark this answers is not in the document]
Comment (gsmet) [reply independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/classloading/QuarkusClassLoader.java:52]: From a design POV, it's not very satisfactory but I can see how it's the most practical/efficient way to pass the information.

Could we also make `startupAction` immutable? From what I can see, it should be doable to pass it when you create the runtime CLs in `StartupActionImpl`?

I suppose you also need to do it in dev mode because of continuous testing?

[the remark this answers is not in the document]
Comment (holly-cummins) [reply independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/classloading/QuarkusClassLoader.java:52]: Yes, making it immutable is a good call. I'll do that update now. 

We can also be cautious about when (ie how often) we store it. In dev mode there are two applications, and it's only the test one which needs that linking. We make classloaders on lots of different code paths, so it might already be the current behaviour to only link on the test application, but I'd have to check. I need to go through in a follow-up PR and rationalise the common code in `TestSupport` and `AppMakerHelper`, and I guess when I'm doing that I can also look to see on which paths the link back to the StartupApplication gets set, and make sure it's only on test paths.

[the remark this answers is not in the document]
Comment (gsmet) [reply independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/classloading/QuarkusClassLoader.java:52]: FWIW, any improvement in this area can come after the merge if other people are comfortable with the PR.

[the remark this answers is not in the document]
Comment (holly-cummins) [reply independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/classloading/QuarkusClassLoader.java:52]: Having just had a quick peek at the 'trivial' immutability adjustment, I think post-merge refinement might be better. Even that change means passing through StartupActions some places where we maybe wouldn't want them to go. Probably fine, but I'd want to think about it.

[the remark this answers is not in the document]
Comment (gsmet) [reply independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/classloading/QuarkusClassLoader.java:52]: Yes, it's perfectly fine.

**Comment by aloubyansky** [comment]
@holly-cummins could you rebase please? There is a conflict

**Comment by gsmet** [comment]
@holly-cummins I think you can probably squash now as I think the idea is to merge this ASAP.

**Comment by geoand** [comment]
+1

File: independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/classloading/QuarkusClassLoader.java (hunk 11 above)
[the remark this answers is not in the document]
Comment (dmlloyd) [reply independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/classloading/QuarkusClassLoader.java:52]: If you want to have a non-leaky associative map with a `Class` as a key, I recommend having a look at `java.lang.ClassValue<V>`. Idiomatically, it wants to be used as something which lazily computes a fixed value given a class, but you could (for example) have it compute a container into which a value could be stored/mutated as well.

File: test-framework/junit5/src/main/java/io/quarkus/test/junit/classloading/FacadeClassLoader.java (hunk 3 above)
Comment (dmlloyd) [reply test-framework/junit5/src/main/java/io/quarkus/test/junit/classloading/FacadeClassLoader.java:55]: > But. An instance factory approach would still leave some functional gaps that we/I resolve by loading classes with the right classloader pre-discovery. For example, if an extension used bytecode instrumentation to add some JUnit annotations to a class, like `@Disabled` or `@ExtendWith`, swapping the classes at instantiation-time would be way too late. By that time JUnit would have already inspected the class and made evaluation decisions.

Are extensions doing this today, or is this more an abundance-of-caution thing? If the latter, I wouldn't feel badly about establishing a rule that this shall not be done.

**Review by aloubyansky — APPROVED** [review]

File: test-framework/junit5/src/main/java/io/quarkus/test/junit/classloading/FacadeClassLoader.java (hunk 3 above)
Comment (holly-cummins) [reply test-framework/junit5/src/main/java/io/quarkus/test/junit/classloading/FacadeClassLoader.java:55]: > Are extensions doing this today, or is this more an abundance-of-caution thing? If the latter, I wouldn't feel badly about establishing a rule that this shall not be done.

Extensions aren't doing it today, because it's not possible with the current (pre-rewrite) design. Most of the JUnit framework sees an un-modified version of the class. It means Quarkus has no Quarkus-y power in test code. Fixing that limitation is one of the goals of this rewrite, IMO. 

I think it's a tradeoff between 'larger memory footprint for tests if people have a lot of profiles' against 'limited and defective-seeming function.' IMO, the bigger footprint is the right way to go, especially since we may be able to make savings elsewhere to compensate; but we can see if people complain, and reassess.

File: independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/classloading/QuarkusClassLoader.java (hunk 11 above)
[the remark this answers is not in the document]
Comment (holly-cummins) [reply independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/classloading/QuarkusClassLoader.java:52]: Good tip, thank you! I've raised https://github.com/quarkusio/quarkus/issues/46960.

**Review by brunobat — APPROVED** [review]
Checked out the PR and run the OTel related tests for execution time differences. Nothing meaningful was spotted.

**Review by gsmet — APPROVED** [review]
Release the KRAAAKEN!

**Comment by gemmellr** [comment]
Just an FYI note for anyone else later, I had to update my extensions tests to Surefire 3.x to fix a break which I'm guessing began due to this change (apologies if not!).

The extension test run against Quarkus main started failing last night, with:
>Caused by: java.lang.RuntimeException: Internal error. The test class class org.amqphub.quarkus.qpid.jms.it.QpidJmsReceiveTest should have been loaded with a QuarkusClassLoader, but instead it was loaded with jdk.internal.loader.ClassLoaders$AppClassLoader@2cdf8d8a. This is caused by the FacadeClassLoader not correctly identifying this class as a QuarkusTest.

The 'same tests' (repackaged) worked ok in last nights quarkus-platform run against Quarkus main however. Checking for differences, I noticed that the platform run was using Surefire 3.0.0 whilst the extension builds own runs were still on 2.22.1. Updating to the latest surefire and failsafe (3.5.2) the extension tests now work ok against quarkus main again.

**Comment by holly-cummins** [comment]
> Just an FYI note for anyone else later, I had to update my extensions tests to Surefire 3.x to fix a break which I'm guessing began due to this change (apologies if not!).
> 
> The extension test run against Quarkus main started failing last night, with:
> 
> > Caused by: java.lang.RuntimeException: Internal error. The test class class org.amqphub.quarkus.qpid.jms.it.QpidJmsReceiveTest should have been loaded with a QuarkusClassLoader, but instead it was loaded with jdk.internal.loader.ClassLoaders$AppClassLoader@2cdf8d8a. This is caused by the FacadeClassLoader not correctly identifying this class as a QuarkusTest.
> 
> The 'same tests' (repackaged) worked ok in last nights quarkus-platform run against Quarkus main however. Checking for differences, I noticed that the platform run was using Surefire 3.0.0 whilst the extension builds own runs were still on 2.22.1. Updating to the latest surefire and failsafe (3.5.2) the extension tests now work ok against quarkus main again.

Thanks for the tip, @gemmellr! I noticed several ecosystem CI runs started failing with this change (which isn't too surprising, given how big the change is). Investigating the failures is today's job, but I think you might have saved me a lot of trouble. 

I'm surprised the surefire version would make a difference. I wonder what's different in surefire? One possibility is how the classpath gets passed to the FacadeClassLoader. I *might* be able to make my stuff tolerate Surefire 2, I will investigate.

**Comment by gemmellr** [comment]
> > Just an FYI note for anyone else later, I had to update my extensions tests to Surefire 3.x to fix a break which I'm guessing began due to this change (apologies if not!).
> > The extension test run against Quarkus main started failing last night, with:
> > > Caused by: java.lang.RuntimeException: Internal error. The test class class org.amqphub.quarkus.qpid.jms.it.QpidJmsReceiveTest should have been loaded with a QuarkusClassLoader, but instead it was loaded with jdk.internal.loader.ClassLoaders$AppClassLoader@2cdf8d8a. This is caused by the FacadeClassLoader not correctly identifying this class as a QuarkusTest.
> > 
> > 
> > The 'same tests' (repackaged) worked ok in last nights quarkus-platform run against Quarkus main however. Checking for differences, I noticed that the platform run was using Surefire 3.0.0 whilst the extension builds own runs were still on 2.22.1. Updating to the latest surefire and failsafe (3.5.2) the extension tests now work ok against quarkus main again.
> 
> Thanks for the tip, @gemmellr! I noticed several ecosystem CI runs started failing with this change (which isn't too surprising, given how big the change is). Investigating the failures is today's job, but I think you might have saved me a lot of trouble.
> 
> I'm surprised the surefire version would make a difference. I wonder what's different in surefire? One possibility is how the classpath gets passed to the FacadeClassLoader. I _might_ be able to make my stuff tolerate Surefire 2, I will investigate.

Np, I was also surprised so thought it worth a mention.

I was also pleased though when I realised that was the case; it meant it was an easy fix, and also doesnt need me to release a new version for the next platform hehe.

I had skimmed the description here and couldn't see anything suggesting a break should really be expected in my case, or anything specific I could even change that would fix whatever the issue was. It was only then I went looking for how much broke in the platform build that I was then surprised to find the quarkus-qpid-jms tests had actually worked there, which pretty quickly pointed out the difference/solution.

**Comment by Karm** [comment]
Hello, 

Running one of my test apps, is there any obvious migration step to deal with:

```
Internal error. The test class class quarkus.awt.ImageResourceTest should have been 
loaded with a QuarkusClassLoader, but instead it was loaded with 
jdk.internal.loader.ClassLoaders$AppClassLoader@46faa73d. This is caused by the 
FacadeClassLoader not correctly identifying this class as a QuarkusTest.
...
```
?

**Comment by Karm** [comment]
Many of my tests are failing with Quarkus 3.22.0.CR1. The common structure is a test like this:

```
[ERROR] myquarkus.awt.ImageResourceTest  Time elapsed: 10.135 s  <<< ERROR!
java.lang.RuntimeException: Internal error. The test class class myquarkus.awt.ImageResourceTest
  should have been loaded with a QuarkusClassLoader, but instead it was loaded with
  jdk.internal.loader.ClassLoaders$AppClassLoader@46faa73d.
 This is caused by the FacadeClassLoader not correctly identifying this class as a QuarkusTest.
```

```
package myquarkus.awt;

import io.quarkus.test.junit.QuarkusTest;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.IOException;
import java.util.Objects;

import static io.restassured.RestAssured.given;

@QuarkusTest
public class ImageResourceTest {

    @Test
    public void testWatermarkJPG() throws IOException {
        final byte[] imgBytes = given()
                .multiPart("image", new File(Objects.requireNonNull(ImageResourceTest.class.getResource("/test-image-503x417.jpg")).getFile()))
                .when()
                .post("/watermark")
                .asByteArray();
        final BufferedImage image = ImageIO.read(new ByteArrayInputStream(imgBytes));
        Assertions.assertNotNull(image, "The image returned is not a valid, known format, e.g. PNG");
        Assertions.assertTrue(image.getWidth() == 503 && image.getHeight() == 417,
                String.format("Image's expected dimension is %d x %d, but was %d x %d.",
                        503, 417, image.getWidth(), image.getHeight()));
        final int[] pixel = new int[4]; //4BYTE RGBA
        image.getData().getPixel(418, 314, pixel);
        Assertions.assertTrue(pixel[0] > 100, "There should have been more red. Watermark failed.");
        image.getData().getPixel(67, 49, pixel);
        Assertions.assertTrue(pixel[0] > 100, "There should have been more red. Watermark failed.");
    }
```

accompanied by 
```
package myquarkus.awt;

import io.quarkus.test.junit.QuarkusIntegrationTest;

@QuarkusIntegrationTest
public class ImageResourceIT extends ImageResourceTest {
}
```

**Comment by gemmellr** [comment]
Are your tests using 2.x Surefire / Failsafe plugins? That looks similar to the failure I saw previously. Upgrading to Surefire / Failsafe 3.x got things going. See comments immediately prior to yours.

**Comment by Karm** [comment]
I am sorry for the noise, upgrading Surefire to 3.5.2 resolved it.

**Comment by holly-cummins** [comment]
Since more than one person has hit this, it's probably worth improving the error message at the very least, and possibly detecting the surefire version and basing the error message on that.
