### PR TITLE
Fix two class loader-related leaks, one in Jackson, the other in QuarkusClassLoader

### LINKED ISSUE #51688: Potential memory leak with `@QuarkusMainTest` for CLI application
### Describe the bug

Using `@QuarkusMainTest` JUnit test cases for a CLI application resulted in an OOM in a constrained environment (GH action). Further investigation shows that the number of loaded classes grows throughout the test execution and is not reduced with GC.

### Expected behavior

Memory use in the test execution is responsive to GC activity and unused classes are unloaded.

### Actual behavior

Loaded class count growns continuously (along with metaspace) and heap use generally grows.

Image

### How to Reproduce?

Using the reproducer/demo CLI app [1], run `./mvnw test -Dtest=TopicCommandTest` and observe in VisualVM or other tooling that the classes loaded increases and are not unloaded when GC is triggered.

[1] https://github.com/MikeEdgar/clik/commit/49ce2a314ea18c32185670163621a37b5bf5e973

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

openjdk version "21.0.9" 2025-10-21 LTS

### Quarkus version or git rev

3.30.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.12 (848fbb4bf2d427b72bdb2471c22fced7ebd9a7a1)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by gsmet**
Fixes https://github.com/quarkusio/quarkus/issues/51688

The issue is interesting as using JaCoCo causes the `MemoryClassPathElement` hosting the transformed classes to be massive, thus making the two leaks very very visible.

The first one manifests as:

Screenshot From 2025-12-23 11-03-24

The second one manifests as:

Screenshot From 2025-12-23 15-52-10

See individual commits for the details.

Now let's hope it doesn't break CI :).

### CODE REVIEW

File: independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/classloading/QuarkusClassLoader.java [hunk 1]
```diff
@@ -233,6 +233,8 @@ public void reset(Map<String, byte[]> generatedResources, Map<String, byte[]> tr
             throw new IllegalStateException("Classloader is not resettable");
         }
         synchronized (this) {
+            // we don't want the previous MemoryClassPathElement to leak as a key of protectionDomains
+            protectionDomains.remove(this.transformedClasses);
```
Comment (geoand) [inline independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/classloading/QuarkusClassLoader.java:237]: Not the first we've run into this...

**Review by geoand — APPROVED** [review]
Great work on this!!!

File: independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/classloading/QuarkusClassLoader.java (hunk 1 above)
Comment (gastaldi) [inline independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/classloading/QuarkusClassLoader.java:237]: This doesn't look right, transformedClasses is a `Map<String, byte[]>` and protectionDomains is a `ConcurrentMap<ClassPathElement, ProtectionDomain>`

Comment (gastaldi) [reply independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/classloading/QuarkusClassLoader.java:237]: Ah, nvm, it's `this.transformedClasses`, a `MemoryClassPathElement`

**Review by gastaldi — APPROVED** [review]
LGTM

File: independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/classloading/QuarkusClassLoader.java (hunk 1 above)
Comment (gastaldi) [reply independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/classloading/QuarkusClassLoader.java:237]: Perhaps the parameter name can be renamed to something less confusing, but that's not priority

Comment (gastaldi) [reply independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/classloading/QuarkusClassLoader.java:237]: Also I assume it will never be null?

Comment (gsmet) [reply independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/classloading/QuarkusClassLoader.java:237]: That's probably why I use `this.transformedClasses` :]

Comment (gsmet) [reply independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/classloading/QuarkusClassLoader.java:237]: What we do is ditch the old entry, before pushing the new one.

Comment (gsmet) [reply independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/classloading/QuarkusClassLoader.java:237]: > Also I assume it will never be null?

That is a good question and I actually checked when writing the patch. Had too many issues with null and CHMs :).

I think it would probably be better to change the field name to make it explicit they are class path elements but I would rather do it in a separate PR.
