### PR TITLE
Obtain the proper trigger in Quartz scheduler implementation

### LINKED ISSUE #25773: fire times are not getting updated in quarkus's scheduler when using quartz
### Describe the bug

Having a scheduled method using quartz. When we get the previous/next firetimes of that job  using `io.quarkus.scheduler.Scheduler` they never get updated as they should when the job runs.

### Expected behavior

Firetimes gets updated to the right values of the previous execution and the next execution

### Actual behavior

Values are not getting updated;

```
2022-05-24 20:49:34,894 INFO  [org.acm.GreetingResource] (QuarkusQuartzScheduler_Worker-2) Previous Fire time is: null
2022-05-24 20:49:34,896 INFO  [org.acm.GreetingResource] (QuarkusQuartzScheduler_Worker-2) Next Fire time is: 2022-05-25T00:49:24.893Z
2022-05-24 20:49:44,894 INFO  [org.acm.GreetingResource] (QuarkusQuartzScheduler_Worker-3) Previous Fire time is: null
2022-05-24 20:49:44,895 INFO  [org.acm.GreetingResource] (QuarkusQuartzScheduler_Worker-3) Next Fire time is: 2022-05-25T00:49:24.893Z
```

### How to Reproduce?

Reproducer: https://github.com/manofthepeace/quarkus-quartz-firetimes

Steps to reproduce;
1. run the app with mvn quarkus:dev
2. look at the logs

### Output of `uname -a` or `ver`

Darwin Kernel Version 21.4.0

### Output of `java -version`

OpenJDK Runtime Environment Temurin-17.0.3+7 (build 17.0.3+7)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.9.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven 3.8.5

### Additional information

Actual code;

```java
    @Inject
    Scheduler scheduler;

    @Inject
    Logger log;

    @Scheduled(every = "10s", identity = "test")
    public void hello() {
        Instant pft = scheduler.getScheduledJob("test").getPreviousFireTime();
        Instant nft = scheduler.getScheduledJob("test").getNextFireTime();
        log.infof("Previous Fire time is: %s", pft);
        log.infof("Next Fire time is: %s", nft);
    }
```

### PR DESCRIPTION
**Pull request by geoand**
This is needed in order to get the proper values
for the fire times.
With this change, `quarkus-quartz` behaves the same way as `quarkus-scheduler`
WRT the previous and next fire times.

Fixes: #25773

### CODE REVIEW

**Comment by geoand** [comment]
@machi1990 @mkouba if you think this is correct, I can add a test as well.

If not, I'll let you handle it :)

**Review by machi1990 — APPROVED** [review]
Great catch! 

Will it be possible to add a test for this?

**Comment by geoand** [comment]
I think so. I'll have a look tomorrow

**Comment by geoand** [comment]
Pushed a test

File: extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java [hunk 1]
```diff
@@ -302,7 +303,17 @@ public QuartzScheduler(SchedulerContext context, QuartzSupport quartzSupport, Sc
                                         scheduled, oldTrigger.getKey().getName());
                             }
                         }
-                        scheduledTasks.put(identity, new QuartzTrigger(trigger, invoker,
+                        scheduledTasks.put(identity, new QuartzTrigger(trigger.getKey(),
```
Comment (mkouba) [inline extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java:306]: I'm a bit confused ;-). So why do we need to obtain the trigger dynamically?

Comment (geoand) [reply extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java:306]: Because the instance only contains information about the 0th run

Comment (mkouba) [reply extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java:306]: Hm, my understanding of the quartz API/javadoc was that the trigger instance is updated after every execution...

Comment (geoand) [reply extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java:306]: I don't know the Quartz internals, but the linked issue clearly shows we are not doing the proper thing

Comment (mkouba) [reply extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java:306]: I do not dispute that but I'd like to know what's going on because it could break something later... BTW I don't know quartz internals either ;-)

Comment (mkouba) [reply extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java:306]: Uf, it seems that for some reason quartz does not work with the original trigger instance but with a clone instead??!!! :fearful: 

@machi1990 it would be good to try to find out whether it's actually a feature or a bug because I don't see it documented anywhere...

File: extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java [hunk 2]
```diff
@@ -593,25 +604,28 @@ public void handle(Void event) {
...
+            this.triggerKey = triggerKey;
+            this.triggerFunction = triggerFunction;
             this.invoker = invoker;
             this.gracePeriod = gracePeriod;
         }
 
         @Override
         public Instant getNextFireTime() {
-            Date nextFireTime = trigger.getNextFireTime();
+            Date nextFireTime = getTrigger().getNextFireTime();
```
Comment (mkouba) [inline extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java:622]: I wonder if we should swith to the original behavio before https://github.com/quarkusio/quarkus/commit/c4ac882fb3df5e849fcb06efeeed192c1bd8f39e, i.e. use the `JobExecutionContext` to obtain the current trigger instead of `triggerFunction`. And keep the `triggerKey` for the `getId()` method.

Comment (geoand) [reply extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java:622]: I'll leave that you and @macchi1990 to decide

File: extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java (hunk 1 above)
Comment (machi1990) [reply extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java:306]: Quartz always update the trigger information in the corresponding store e.g for db stores, the corresponding trigger table will get updated.

File: extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java (hunk 2 above)
Comment (machi1990) [reply extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java:622]: I do not think it is it possible to use the `JobExecutionContext` here. 
Instances of this class are created way before `JobExecutionContext`, which is available during invocation. 
I could be missing something though.

**Comment by geoand** [comment]
So should this be merged?

**Comment by machi1990** [comment]
> So should this be merged?

Yes, we should be good to merge, @mkouba what do you think?

**Comment by mkouba** [comment]
> I'm going to merge this as it clearly fixes the problem. If there are more comments, we can surely follow-up

Ok. I don't have spare cycles to explore the quartz API (and its oddities). So if it fixed the problem then +1 :D

**Comment by gsmet** [comment]
We won't backport it to 2.7 as we would have to rewrite the patch due to conflicts and we had no complaints so far.
