### PR TITLE
Fix bean removal algorithm

### LINKED ISSUE #4049: @Produces annotated methods that are not consumed not ignored and result in failed build
**Describe the bug**
Issue described [here](https://github.com/quarkusio/quarkus/issues/2770) persists under 0.20.0.  

**Expected behavior**
When using a class with method annotated with `@Produces`, even if never "produced", expect successful build.

**Actual behavior**
Build fails with misleading error message:

```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:0.20.0:build (default) on project injector-jira-service: Failed to build a runnable JAR: Failed to build a runner jar: Failed to augment application classes: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#generateResources threw an exception: java.lang.IllegalArgumentException: Must be a Class or String, got null
[ERROR] -> [Help 1]
[ERROR]
```

**To Reproduce**

Simple reproducer:

```
package service;

@ApplicationScoped
public class SomeResource {
    @Inject
    SomeService someService;

    public void doSomething() {
    }
}
```

```
package service;

import client.SomeProvider;
import javax.enterprise.context.ApplicationScoped;
import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;

@ApplicationScoped
public class SomeService {
    @Inject
    @RequestScoped
    SomeProvider someProvider;

    //  as a workaround, the "produced" but unused bean can be instantiated but ignored to silence this error
    // @Inject
    // @RequestScoped
    // SomeClient someClient;

    public void doSomething() {
    }
}
```

```
package client;

import java.net.URI;
import javax.enterprise.context.RequestScoped;
import javax.enterprise.inject.Produces;
import org.eclipse.microprofile.rest.client.RestClientBuilder;

@RequestScoped
public class SomeProvider {

    @Produces
    @RequestScoped
    public SomeClient getClient() {
        return RestClientBuilder
                .newBuilder()
                .baseUri(URI.create("http://example.com"))
                .build(SomeClient.class);
    }
}
```

```
package com.cloudbees.sdm.injector.jira.client;

import javax.ws.rs.Consumes;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;

@Consumes("application/json")
@Produces("application/json")
public interface SomeClient {

    @GET
    @Path("/rest/api/lols")
    void getLols();
}
```

Add classes to project and build with maven.

**Configuration**
N/A

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
```
$ uname -a
Darwin ip-192-168-1-137.ec2.internal 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64
```
 - Output of `java -version`: 
```
$ java -version
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit GraalVM EE 19.1.1 (build 25.221-b11-jvmci-19.1-b01, mixed mode)
```

 - Quarkus version or git rev: 0.20.0

### PR DESCRIPTION
**Pull request by mkouba**
- a bean that declares an unused producer but is injected should not be
removed
- resolves #4049

### CODE REVIEW

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanDeployment.java [hunk 1]
```diff
@@ -245,17 +246,18 @@ void init() {
...
-                    continue test;
-                }
                 // Instance<Foo>
                 for (InjectionPointInfo injectionPoint : instanceInjectionPoints) {
                     if (Beans.hasQualifiers(bean, injectionPoint.getRequiredQualifiers()) && Beans.matchesType(bean,
                             injectionPoint.getRequiredType().asParameterizedType().arguments().get(0))) {
                         continue test;
                     }
                 }
+                // Declares a producer - see also second pass
```
Comment (manovotn) [inline independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanDeployment.java]: Is there a specific reason why this is now processed after `instanceInjectionPoints`?

Comment (mkouba) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanDeployment.java]: There is. If `Foo`, a bean that declares a producer, is injected via `Instance<Foo>` we shall not  remove it either.

Comment (manovotn) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanDeployment.java]: In that case, shouldn't we have a test for this as well? ;-)

Comment (mkouba) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanDeployment.java]: Feel free to add one. I think the test I've added is enough ;-).

Comment (manovotn) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanDeployment.java]: Done

**Review by manovotn — APPROVED** [review]

**Review by stuartwdouglas — APPROVED** [review]
