### PR TITLE
Make providers registered with @RegisterProvider CDI beans in reactive rest client

### LINKED ISSUE #16540: Injecting into custom ClientRequestFilter does not work with Reactive RestClient
## Describe the bug
Reported by Simone DiCola.

For example, injecting a `RequestScoped` `Tokens` shipped with `quarkus-oidc-client` into a custom filter:

```
@Provider
@Priority(Priorities.AUTHENTICATION)
public class OidcClientRequestCustomFilter implements ClientRequestFilter {

    @Inject
    Tokens tokens;

    @Override
    public void filter(ClientRequestContext requestContext) throws IOException {
        requestContext.getHeaders().add(HttpHeaders.AUTHORIZATION, "Bearer " + tokens.getAccessToken());
    }
}
```

works with `quarkus-rest-client` but it is `null` with `quarkus-rest-client-reactive`.

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #16540

### CODE REVIEW

File: extensions/resteasy-reactive/rest-client-reactive/deployment/src/main/java/io/quarkus/rest/client/reactive/deployment/MicroProfileRestClientEnricher.java [hunk 1]
```diff
@@ -457,13 +465,19 @@ private void addProvider(MethodCreator ctor, AssignableResultHandle target, Inde
...
+        if ((providerClassInfo != null) && providerClassInfo.hasNoArgsConstructor()) { // if the filter has a no-args constructor, use it
+            ResultHandle provider = beanProviderNotAvailable.newInstance(MethodDescriptor.ofConstructor(providerClass));
+            alteredTarget = beanProviderNotAvailable.invokeInterfaceMethod(
+                    MethodDescriptor.ofMethod(Configurable.class, "register", Configurable.class, Object.class,
+                            int.class),
+                    target, provider,
+                    beanProviderNotAvailable.load(registerProvider.valueWithDefault(index, "priority").asInt()));
+            beanProviderNotAvailable.assign(target, alteredTarget);
+        } else { // the filter does not have a no-args constructor, so we can do nothing but fail
+            beanProviderNotAvailable.throwException(IllegalStateException.class,
```
Comment (geoand) [inline extensions/resteasy-reactive/rest-client-reactive/deployment/src/main/java/io/quarkus/rest/client/reactive/deployment/MicroProfileRestClientEnricher.java:477]: This was needed otherwise a filter with a no-args ctor would cause the native-image build to fail

File: extensions/resteasy-reactive/rest-client-reactive/deployment/src/main/java/io/quarkus/rest/client/reactive/deployment/ReactiveResteasyMpClientProcessor.java [hunk 2]
```diff
@@ -146,6 +154,58 @@ void registerHeaderFactoryBeans(CombinedIndexBuildItem index,
         }
     }
 
+    @BuildStep
+    void registerProviders(CombinedIndexBuildItem combinedIndexBuildItem,
```
Comment (geoand) [inline extensions/resteasy-reactive/rest-client-reactive/deployment/src/main/java/io/quarkus/rest/client/reactive/deployment/ReactiveResteasyMpClientProcessor.java:158]: This was copied almost verbatim from the old rest-client

File: extensions/resteasy-reactive/rest-client-reactive/deployment/src/main/java/io/quarkus/rest/client/reactive/deployment/ReactiveResteasyMpClientProcessor.java [hunk 3]
```diff
@@ -146,6 +154,58 @@ void registerHeaderFactoryBeans(CombinedIndexBuildItem index,
...
+        for (ClassInfo info : index.getAllKnownImplementors(CLIENT_REQUEST_FILTER)) {
+            reflectiveClass.produce(new ReflectiveClassBuildItem(false, false, info.name().toString()));
+        }
+        for (ClassInfo info : index.getAllKnownImplementors(CLIENT_RESPONSE_FILTER)) {
+            reflectiveClass.produce(new ReflectiveClassBuildItem(false, false, info.name().toString()));
+        }
+    }
+
+    @BuildStep
+    AdditionalBeanBuildItem registerProviderBeans(CombinedIndexBuildItem combinedIndex) {
```
Comment (geoand) [inline extensions/resteasy-reactive/rest-client-reactive/deployment/src/main/java/io/quarkus/rest/client/reactive/deployment/ReactiveResteasyMpClientProcessor.java:191]: This was copied almost verbatim from the old rest-client

File: extensions/resteasy-reactive/rest-client-reactive/deployment/src/main/java/io/quarkus/rest/client/reactive/deployment/MicroProfileRestClientEnricher.java [hunk 4]
```diff
@@ -444,6 +444,14 @@ private void addProvider(MethodCreator ctor, AssignableResultHandle target, Inde
                 MethodDescriptor.ofMethod(BeanGrabber.class, "getBeanIfDefined", Object.class, Class.class),
                 ctor.loadClass(providerClass));
 
+        ClassInfo providerClassInfo;
+        if (registerProvider.target() != null) {
+            providerClassInfo = registerProvider.target().asClass();
```
Comment (michalszynkiewicz) [inline extensions/resteasy-reactive/rest-client-reactive/deployment/src/main/java/io/quarkus/rest/client/reactive/deployment/MicroProfileRestClientEnricher.java:449]: I don't understand this part, this line seems to be setting providerClassInfo to the jaxrs-annotated interface and line 452 seems to be setting it to the provider class.

File: extensions/resteasy-reactive/rest-client-reactive/deployment/src/main/java/io/quarkus/rest/client/reactive/deployment/ReactiveResteasyMpClientProcessor.java (hunk 2 above)
Comment (michalszynkiewicz) [reply extensions/resteasy-reactive/rest-client-reactive/deployment/src/main/java/io/quarkus/rest/client/reactive/deployment/ReactiveResteasyMpClientProcessor.java:158]: this doesn't seem to be necessary. Registering client headers and providers is now handled by code generated in the build time.
Maybe some specific part of this method is needed?

File: extensions/resteasy-reactive/rest-client-reactive/deployment/src/main/java/io/quarkus/rest/client/reactive/deployment/ReactiveResteasyMpClientProcessor.java (hunk 3 above)
Comment (michalszynkiewicz) [reply extensions/resteasy-reactive/rest-client-reactive/deployment/src/main/java/io/quarkus/rest/client/reactive/deployment/ReactiveResteasyMpClientProcessor.java:191]: ditto

File: extensions/resteasy-reactive/rest-client-reactive/deployment/src/main/java/io/quarkus/rest/client/reactive/deployment/ReactiveResteasyMpClientProcessor.java (hunk 2 above)
Comment (geoand) [reply extensions/resteasy-reactive/rest-client-reactive/deployment/src/main/java/io/quarkus/rest/client/reactive/deployment/ReactiveResteasyMpClientProcessor.java:158]: I'll try, but I am pretty sure it wasn't without this

File: extensions/resteasy-reactive/rest-client-reactive/deployment/src/main/java/io/quarkus/rest/client/reactive/deployment/ReactiveResteasyMpClientProcessor.java (hunk 3 above)
Comment (geoand) [reply extensions/resteasy-reactive/rest-client-reactive/deployment/src/main/java/io/quarkus/rest/client/reactive/deployment/ReactiveResteasyMpClientProcessor.java:191]: Same comment as above

File: extensions/resteasy-reactive/rest-client-reactive/deployment/src/main/java/io/quarkus/rest/client/reactive/deployment/MicroProfileRestClientEnricher.java (hunk 4 above)
Comment (geoand) [reply extensions/resteasy-reactive/rest-client-reactive/deployment/src/main/java/io/quarkus/rest/client/reactive/deployment/MicroProfileRestClientEnricher.java:449]: Both branches get the `ClassInfo` of the class registered with `@RegisterProvider(SomeClass.class)`. 
The first branch gets it for the case where a single `@RegisterProvider` annotation is present on the interface, the second branch is used for the case of repeatable annotations

File: extensions/resteasy-reactive/rest-client-reactive/deployment/src/main/java/io/quarkus/rest/client/reactive/deployment/ReactiveResteasyMpClientProcessor.java (hunk 3 above)
Comment (geoand) [reply extensions/resteasy-reactive/rest-client-reactive/deployment/src/main/java/io/quarkus/rest/client/reactive/deployment/ReactiveResteasyMpClientProcessor.java:191]: I tried it and without this, the filters I added in the test are **not**  CDI beans

File: extensions/resteasy-reactive/rest-client-reactive/deployment/src/main/java/io/quarkus/rest/client/reactive/deployment/MicroProfileRestClientEnricher.java (hunk 4 above)
Comment (michalszynkiewicz) [reply extensions/resteasy-reactive/rest-client-reactive/deployment/src/main/java/io/quarkus/rest/client/reactive/deployment/MicroProfileRestClientEnricher.java:449]: `registerProvider.target()` returns the class on which the registerProvider annotation was placed, doesn't it?

File: extensions/resteasy-reactive/rest-client-reactive/deployment/src/main/java/io/quarkus/rest/client/reactive/deployment/ReactiveResteasyMpClientProcessor.java (hunk 2 above)
Comment (geoand) [reply extensions/resteasy-reactive/rest-client-reactive/deployment/src/main/java/io/quarkus/rest/client/reactive/deployment/ReactiveResteasyMpClientProcessor.java:158]: This indeed is no needed

File: extensions/resteasy-reactive/rest-client-reactive/deployment/src/main/java/io/quarkus/rest/client/reactive/deployment/MicroProfileRestClientEnricher.java (hunk 4 above)
Comment (geoand) [reply extensions/resteasy-reactive/rest-client-reactive/deployment/src/main/java/io/quarkus/rest/client/reactive/deployment/MicroProfileRestClientEnricher.java:449]: OK right, my dumb mistake. Thanks for spotting it

Comment (geoand) [reply extensions/resteasy-reactive/rest-client-reactive/deployment/src/main/java/io/quarkus/rest/client/reactive/deployment/MicroProfileRestClientEnricher.java:449]: Fixed

File: extensions/resteasy-reactive/rest-client-reactive/deployment/src/main/java/io/quarkus/rest/client/reactive/deployment/ReactiveResteasyMpClientProcessor.java (hunk 3 above)
Comment (michalszynkiewicz) [reply extensions/resteasy-reactive/rest-client-reactive/deployment/src/main/java/io/quarkus/rest/client/reactive/deployment/ReactiveResteasyMpClientProcessor.java:155]: sorry, I misread the code, I thought this is also registering classes for reflection. This is the part that I think should not be necessary anymore

Comment (geoand) [reply extensions/resteasy-reactive/rest-client-reactive/deployment/src/main/java/io/quarkus/rest/client/reactive/deployment/ReactiveResteasyMpClientProcessor.java:155]: 👍🏼 

I removed that part

**Review by michalszynkiewicz — APPROVED** [review]
thanks!

**Comment by geoand** [comment]
YW!

**Comment by gsmet** [comment]
Same here, this will have to wait or will require a specific patch.
