### PR TITLE
Prevent REST Client handling of abstract classes

### LINKED ISSUE #42977: Quarkus REST client and Quarkus REST with abstract resource - NATIVE build fails
### Describe the bug

I'm having app with Quarkus REST client and Quarkus REST with abstract resources with `@Path` and the build of native binary fails

If Quarkus REST client is removed, native compilation works.

Details:
```
Build resources:
 - 26.49GB of memory (73.6% of 36.00GB system memory, determined at start)
 - 12 thread(s) (100.0% of 12 available processor(s), determined at start)
[2/8] Performing analysis...  [08:12:56,063 WARN  [io.net.res.dns.DnsServerAddressStreamProviders] Can not find io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider in the classpath, fallback to system defaults. This may result in incorrect DNS resolutions on MacOS. Check whether you have a dependency on 'io.netty:netty-resolver-dns-native-macos'
*****]                                                                   (10.5s @ 0.87GB)
   11,071 reachable types   (86.0% of   12,874 total)
   15,842 reachable fields  (56.1% of   28,250 total)
   55,945 reachable methods (56.2% of   99,630 total)
    3,616 types,   118 fields, and 3,364 methods registered for reflection
       62 types,    67 fields, and    55 methods registered for JNI access
        5 native libraries: -framework CoreServices, -framework Foundation, dl, pthread, z

Error: Discovered unresolved type during parsing: org.acme.AbstractGreetingResource$$QuarkusRestClientInterface. This error is reported at image build time because class org.acme.AbstractGreetingResource$$QuarkusRestClientInterfaceCreator is registered for linking at image build time by command line and command line.
Error encountered while parsing org.acme.AbstractGreetingResource$$QuarkusRestClientInterfaceCreator.apply(Unknown Source)
Parsing context:
   at io.quarkus.vertx.http.runtime.VertxHttpRecorder$18.accept(VertxHttpRecorder.java:1626)
   at io.quarkus.vertx.http.runtime.VertxHttpRecorder$18.accept(VertxHttpRecorder.java:1622)
   at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
   at io.smallrye.config.ConfigMappingContext$ObjectCreator.optionalGroup(ConfigMappingContext.java:641)
   at io.quarkus.tls.runtime.config.TlsBucketConfig351136998Impl.<init>(Unknown Source)
   at com.oracle.svm.core.code.FactoryMethodHolder.TlsBucketConfig351136998Impl_constructor_ee647b8c465636ec0f197409c5afe32ea7a63275(generated:0)
   at static root method.(Unknown Source)

Detailed message:

com.oracle.svm.core.util.UserError$UserException: Discovered unresolved type during parsing: org.acme.AbstractGreetingResource$$QuarkusRestClientInterface. This error is reported at image build time because class org.acme.AbstractGreetingResource$$QuarkusRestClientInterfaceCreator is registered for linking at image build time by command line and command line.
Error encountered while parsing org.acme.AbstractGreetingResource$$QuarkusRestClientInterfaceCreator.apply(Unknown Source)
Parsing context:
   at io.quarkus.vertx.http.runtime.VertxHttpRecorder$18.accept(VertxHttpRecorder.java:1626)
   at io.quarkus.vertx.http.runtime.VertxHttpRecorder$18.accept(VertxHttpRecorder.java:1622)
   at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
   at io.smallrye.config.ConfigMappingContext$ObjectCreator.optionalGroup(ConfigMappingContext.java:641)
   at io.quarkus.tls.runtime.config.TlsBucketConfig351136998Impl.<init>(Unknown Source)
   at com.oracle.svm.core.code.FactoryMethodHolder.TlsBucketConfig351136998Impl_constructor_ee647b8c465636ec0f197409c5afe32ea7a63275(generated:0)
   at static root method.(Unknown Source)

Detailed message:

	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:85)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:248)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:814)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:592)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:550)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:539)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:721)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:143)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:98)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Discovered unresolved type during parsing: org.acme.AbstractGreetingResource$$QuarkusRestClientInterface. This error is reported at image build time because class org.acme.AbstractGreetingResource$$QuarkusRestClientInterfaceCreator is registered for linking at image build time by command line and command line.
Error encountered while parsing org.acme.AbstractGreetingResource$$QuarkusRestClientInterfaceCreator.apply(Unknown Source)
Parsing context:
   at io.quarkus.vertx.http.runtime.VertxHttpRecorder$18.accept(VertxHttpRecorder.java:1626)
   at io.quarkus.vertx.http.runtime.VertxHttpRecorder$18.accept(VertxHttpRecorder.java:1622)
   at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
   at io.smallrye.config.ConfigMappingContext$ObjectCreator.optionalGroup(ConfigMappingContext.java:641)
   at io.quarkus.tls.runtime.config.TlsBucketConfig351136998Impl.<init>(Unknown Source)
   at com.oracle.svm.core.code.FactoryMethodHolder.TlsBucketConfig351136998Impl_constructor_ee647b8c465636ec0f197409c5afe32ea7a63275(generated:0)
   at static root method.(Unknown Source)

Detailed message:

	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:126)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:809)
	... 6 more
Caused by: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: org.acme.AbstractGreetingResource$$QuarkusRestClientInterface. This error is reported at image build time because class org.acme.AbstractGreetingResource$$QuarkusRestClientInterfaceCreator is registered for linking at image build time by command line and command line.
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.reportUnresolvedElement(SharedGraphBuilderPhase.java:550)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.reportUnresolvedElement(SharedGraphBuilderPhase.java:544)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedType(SharedGraphBuilderPhase.java:436)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedNewInstance(SharedGraphBuilderPhase.java:293)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genNewInstance(BytecodeParser.java:4641)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genNewInstance(BytecodeParser.java:4634)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5444)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3431)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.iterateBytecodesForBlock(SharedGraphBuilderPhase.java:743)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.handleBytecodeBlock(BytecodeParser.java:3391)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3233)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1137)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.build(SharedGraphBuilderPhase.java:162)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:1029)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:101)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase.run(SharedGraphBuilderPhase.java:116)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.run(Phase.java:49)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:434)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.AnalysisParsedGraph.parseBytecode(AnalysisParsedGraph.java:146)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisMethod.parseGraph(AnalysisMethod.java:895)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisMethod.ensureGraphParsedHelper(AnalysisMethod.java:860)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisMethod.ensureGraphParsed(AnalysisMethod.java:843)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:186)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:621)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.createFlowsGraph(MethodTypeFlow.java:167)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureFlowsGraphCreated(MethodTypeFlow.java:153)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.getOrCreateMethodFlowsGraphInfo(MethodTypeFlow.java:111)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.typestate.DefaultVirtualInvokeTypeFlow.onObservedUpdate(DefaultVirtualInvokeTypeFlow.java:114)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:620)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.PointsToAnalysis$1.run(PointsToAnalysis.java:491)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:187)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:171)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```

`AbstractGreetingResource$$QuarkusRestClientInterfaceCreator` looks a bit strange.

If I switch to quarkus-resteasy-client and quarkus-resteasy, things work well.

### Expected behavior

Native compilation works.

### Actual behavior

Native compilation fails

### How to Reproduce?

 - `sdk use java 21.0.2-graalce`
 - `git clone git@github.com:rsvoboda/abstract-quarkus-rest-repro.git`
 - `cd abstract-quarkus-rest-repro`
 - `mvn clean verify -Dnative`

### Output of `uname -a` or `ver`

macOS

### Output of `java -version`

Java 21

### Quarkus version or git rev

Quarkus main / Quarkus 3.14.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
- Fixes: #42977

### CODE REVIEW

File: independent-projects/resteasy-reactive/common/processor/src/main/java/org/jboss/resteasy/reactive/common/processor/scanning/ResteasyReactiveScanner.java [hunk 1]
```diff
@@ -325,15 +316,15 @@ public static ResourceScanningResult scanResources(
...
+        // for clients, it is also enough to only have @GET, @POST, etc on methods and no PATH whatsoever
         Set<DotName> methodAnnotations = httpAnnotationToMethod.keySet();
         for (DotName methodAnnotation : methodAnnotations) {
             for (AnnotationInstance methodAnnotationInstance : index.getAnnotations(methodAnnotation)) {
                 if (methodAnnotationInstance.target().kind() == AnnotationTarget.Kind.METHOD) {
                     MethodInfo annotatedMethod = methodAnnotationInstance.target().asMethod();
                     ClassInfo classWithJaxrsMethod = annotatedMethod.declaringClass();
                     if (Modifier.isAbstract(annotatedMethod.flags())
-                            && Modifier.isAbstract(classWithJaxrsMethod.flags())
+                            && Modifier.isInterface(classWithJaxrsMethod.flags())
```
Comment (geoand) [inline independent-projects/resteasy-reactive/common/processor/src/main/java/org/jboss/resteasy/reactive/common/processor/scanning/ResteasyReactiveScanner.java:327]: This is the essence of the change

**Review by gsmet — APPROVED** [review]

**Comment by rsvoboda** [comment]
Let's have this in 3.8 stream as it's related to https://github.com/quarkusio/quarkus/pull/41606 which was backported to 3.8.6
