### PR TITLE
Fix Map.Entry handling of parameterized tests

### LINKED ISSUE #25027: Quarkus testing with `@ParameterizedTest` using Map (entries) broken with Java 17 + 18 (xstream)
### Describe the bug

This is the same issue as https://github.com/quarkusio/quarkus/issues/24492 but when the `@MethodSource` returns a `Stream<Map.Entry<String, String>>` (created from a `static final Map<String, String>` field). The error is:

```
com.thoughtworks.xstream.converters.ConversionException: 
No converter available
---- Debugging information ----
message             : No converter available
type                : java.util.KeyValueHolder
converter           : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
message[1]          : Unable to make field final java.lang.Object java.util.KeyValueHolder.key accessible: module java.base does not "opens java.util" to unnamed module @7219ec67
-------------------------------
```

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

```java
@QuarkusTest
class ResourceTest {
    private static final Map<String, String> MAP = Map.of("a", "b");

    private static Stream<Map.Entry<String, String>> params() {
        return MAP.entrySet().stream();
    }

    @ParameterizedTest
    @MethodSource("params")
    void testReadOnlyDataResource(Map.Entry<String, String> pathAndExpectedValueEntry) {
        ...
    }
}
```

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.8.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #25027

### CODE REVIEW

**Review by gsmet — APPROVED** [review]

File: test-framework/junit5/src/main/java/io/quarkus/test/junit/internal/CustomMapEntryConverter.java [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+ * for all the cases where we are using marshalling / unmarshalling.
+ *
+ * The reason for doing this is to avoid XStream causing illegal access issues
+ * for internal JDK types
+ */
+@SuppressWarnings({ "rawtypes", "unchecked" })
+public class CustomMapEntryConverter extends MapConverter {
+
+    private final Set<String> SUPPORTED_CLASS_NAMES = Set
+            .of(Map.entry(Integer.MAX_VALUE, Integer.MAX_VALUE).getClass().getName());
```
Comment (gastaldi) [inline test-framework/junit5/src/main/java/io/quarkus/test/junit/internal/CustomMapEntryConverter.java:26]: Just curious: Is there any reason why `Integer.MAX_VALUE` is used here?

Comment (geoand) [reply test-framework/junit5/src/main/java/io/quarkus/test/junit/internal/CustomMapEntryConverter.java:26]: The only reason is to use an object that already exists

File: test-framework/junit5/src/main/java/io/quarkus/test/junit/internal/CustomMapEntryConverter.java [hunk 2]
```diff
@@ -0,0 +1,55 @@
...
+
+    public CustomMapEntryConverter(Mapper mapper) {
+        super(mapper);
+    }
+
+    @Override
+    public boolean canConvert(Class type) {
+        return (type != null) && SUPPORTED_CLASS_NAMES.contains(type.getName());
```
Comment (gastaldi) [inline test-framework/junit5/src/main/java/io/quarkus/test/junit/internal/CustomMapEntryConverter.java:34]: Wondering if `Map.Entry.class.isAssignableFrom(type)` could work here

Comment (geoand) [reply test-framework/junit5/src/main/java/io/quarkus/test/junit/internal/CustomMapEntryConverter.java:34]: It would, but we want to limit this as much as possible to cases that we know don't work otherwise

**Review by gastaldi — APPROVED** [review]
