### PR TITLE
Look for RedisClient in all modules

### LINKED ISSUE #15581: Named Redis client injection not working when used in separate JAR
**Describe the bug**
We have an application scoped bean, defined in our common project and being used by other services, that utilizes `RedisClient`:
```
@ApplicationScoped
public class Service {

    @Inject
    @RedisClientName("second")
    RedisClient redisClient;
    ...
}
```
This common project is packaged as JAR and then used as a Maven dependency from other services.

We keep getting this error when starting those other services:
```
javax.enterprise.inject.spi.DeploymentException:
  javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type io.quarkus.redis.client.RedisClient and qualifiers [@RedisClientName(value = "second")]
```

We've defined an alternate Redis connection like this:
```
quarkus.redis.second.hosts=redis://localhost:6379
```
and made sure it's being used as expected by a Redis client defined in our service (not the common JAR!) like this:
```
    @Inject
    @RedisClientName("second")
    RedisClient redisClient;
```

Should it be possible to have a bean class contained in a dependency JAR and make it use Redis connection defined in the project that uses that JAR?

**Expected behavior**
Bean defined in a dependency JAR, which uses a Redis client annotated by `@RedisClientName`, properly using Redis connection defined in containing service.

### PR DESCRIPTION
**Pull request by glefloch**
This branch looks for redis client in all archives. I tested it in a multi module project locally. Is there any place where I could put such a test? the `integration-test/redis-client` is not a multi-module project. 

close #15581

### CODE REVIEW

**Comment by mkouba** [comment]
There's a formatting error:
```
 File '/home/runner/work/quarkus/quarkus/extensions/redis-client/deployment/src/main/java/io/quarkus/redis/client/deployment/RedisClientProcessor.java' has not been previously formatted.  Please format file and commit before running validation!
```

File: extensions/redis-client/deployment/src/main/java/io/quarkus/redis/client/deployment/RedisClientProcessor.java [hunk 1]
```diff
@@ -86,10 +87,12 @@ public void produceRedisClient(RedisClientRecorder recorder, ApplicationArchives
         Set<String> clientNames = new HashSet<>();
         clientNames.add(RedisClientUtil.DEFAULT_CLIENT);
 
-        IndexView indexView = applicationArchives.getRootArchive().getIndex();
-        Collection<AnnotationInstance> clientAnnotations = indexView.getAnnotations(REDIS_CLIENT_ANNOTATION);
-        for (AnnotationInstance annotation : clientAnnotations) {
-            clientNames.add(annotation.value().asString());
+        for (ApplicationArchive applicationArchive: applicationArchives.getAllApplicationArchives()) {
```
Comment (mkouba) [inline extensions/redis-client/deployment/src/main/java/io/quarkus/redis/client/deployment/RedisClientProcessor.java:90]: You can also leverage the `io.quarkus.arc.deployment.BeanArchiveIndexBuildItem`.

Comment (machi1990) [reply extensions/redis-client/deployment/src/main/java/io/quarkus/redis/client/deployment/RedisClientProcessor.java:90]: The same will have to be done for the mongo-extension https://github.com/quarkusio/quarkus/blob/33364c8700988293515dfb34d53f238f196ead15/extensions/mongodb-client/deployment/src/main/java/io/quarkus/mongodb/deployment/MongoClientProcessor.java#L119?

**Comment by glefloch** [comment]
I fixed the formatting error, I pushed to fast yesterday :)

File: extensions/redis-client/deployment/src/main/java/io/quarkus/redis/client/deployment/RedisClientProcessor.java (hunk 1 above)
Comment (glefloch) [reply extensions/redis-client/deployment/src/main/java/io/quarkus/redis/client/deployment/RedisClientProcessor.java]: @mkouba Yes, I will use the `BeanArchiveIndexBuildItem` this will remove a for-loop

**Comment by glefloch** [comment]
@mkouba I updated the code with `BeanArchiveIndexBuildItem` and fixed the formatted. 

@machi1990 for the mongo extension, should we do  that in an other branch ?

**Review by machi1990 — APPROVED** [review]

**Review by gsmet — APPROVED** [review]
