### PR TITLE
Switch Hibernate Search extension to @ConfigMapping

### LINKED ISSUE #32209: Optimize config generation
### Description

After merging https://github.com/quarkusio/quarkus/pull/30506 `io.quarkus.maven.it.DevMojoIT.testThatTheApplicationIsReloadedMultiModule` started to fail with the OOME. Although these dev mode tests are run with `-Xmx128m`, they do highlight an issue in the way our config classes are generated currently.

### Implementation ideas

As an alternative to the current impl, @radcortez suggested to switch to the ConfigMapping approach instead in https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/OOME.20in.20main/near/343476381

### PR DESCRIPTION
**Pull request by gsmet**
This is some preliminary work in order to fix https://github.com/quarkusio/quarkus/issues/32209 .

The Hibernate Search extension config uses patterns that are used in a lot of extensions and are well tested.

Creating as draft as I spotted two issues related to config and I would like @radcortez to have a look.

1. The doc generation is broken when you don't have `@ConfigGroup`: `target/asciidoc/generated/config/quarkus-hibernate-search-orm-elasticsearch.adoc` is mostly empty and is incorrect as config groups are not handled. If the solution is to put back the `@ConfigGroup` annotations, I can do it.
2. I think we have a bug somewhere as I checked what I did several times and I can't figure out what I did wrong with `active` that would explain this behavior.

Reproducing the issue is easy:
- build the tree
- run `mvn -f extensions/hibernate-search-orm-elasticsearch clean install -Dstart-containers -Dtest-containers`
- you should get the following errors:
```
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ConfigEnabledFalseAndActiveTrueTest.lambda$static$1:22 
Expecting actual throwable to be an instance of:
  io.quarkus.runtime.configuration.ConfigurationException
but was:
  io.smallrye.config.ConfigValidationException: Configuration validation failed:
	quarkus.hibernate-search-orm.active does not map to any root
	at io.smallrye.config.ConfigMappingProvider.mapConfigurationInternal(ConfigMappingProvider.java:975)
	at io.smallrye.config.ConfigMappingProvider.lambda$mapConfiguration$3(ConfigMappingProvider.java:931)
	at io.smallrye.config.SecretKeys.doUnlocked(SecretKeys.java:28)
	...(51 remaining lines not displayed - this can be changed with Assertions.setMaxStackTraceElementsDisplayed)
[ERROR] Errors: 
[ERROR]   ConfigActiveFalseAndIndexedEntityTest » Runtime io.smallrye.config.ConfigValidationException: Configuration validation failed:
	quarkus.hibernate-search-orm.active does not map to any root
[INFO] 
[ERROR] Tests run: 25, Failures: 1, Errors: 1, Skipped: 0
```

`active` is in this interface: `HibernateSearchElasticsearchRuntimeConfigPersistenceUnit`

### CODE REVIEW

File: extensions/hibernate-search-orm-elasticsearch/runtime/src/main/java/io/quarkus/hibernate/search/orm/elasticsearch/runtime/HibernateSearchElasticsearchBuildTimeConfig.java [hunk 1]
```diff
@@ -22,30 +25,50 @@ public class HibernateSearchElasticsearchBuildTimeConfig {
...
+
         if (defaultPersistenceUnit != null) {
             map.put(PersistenceUnitUtil.DEFAULT_PERSISTENCE_UNIT_NAME, defaultPersistenceUnit);
         }
-        map.putAll(persistenceUnits);
+        map.putAll(persistenceUnits());
         return map;
     }
 
+    default HibernateSearchElasticsearchBuildTimeConfigPersistenceUnit getPersistenceUnitConfig(String persistenceUnitName) {
```
Comment (yrodiere) [inline extensions/hibernate-search-orm-elasticsearch/runtime/src/main/java/io/quarkus/hibernate/search/orm/elasticsearch/runtime/HibernateSearchElasticsearchBuildTimeConfig.java:56]: In other places we just do `getPersistenceUnitConfigsAsMap().get(persistenceUnitName)`... which seems simpler than having a dedicated method.


Ideally we'd introduce a dedicated construct in the config mapping code, and we wouldn't have to reproduce those utils everywhere... E.g. instead of:

```java
    @WithParentName
    HibernateSearchElasticsearchBuildTimeConfigPersistenceUnit defaultPersistenceUnit();
    @WithParentName
    Map<String, HibernateSearchElasticsearchBuildTimeConfigPersistenceUnit> persistenceUnits();

    default Map<String, HibernateSearchElasticsearchBuildTimeConfigPersistenceUnit> getAllPersistenceUnitConfigsAsMap() {
        // ...
    }

    default HibernateSearchElasticsearchBuildTimeConfigPersistenceUnit getPersistenceUnitConfig(String persistenceUnitName) {
        // ...
    }
```

We'd simply do this:

```java
    @WithParentName
    @WithRootEntry(key = PersistenceUnitUtil.DEFAULT_PERSISTENCE_UNIT_NAME)
    Map<String, HibernateSearchElasticsearchBuildTimeConfigPersistenceUnit> persistenceUnits();
```

Would be nice to introduce this before we migrate all extensions... But I imagine we don't really have time for that? My understanding was that we were going to migrate to `@ConfigMapping` *after* 3.0.0.Final, but I guess that changed.

File: extensions/hibernate-search-orm-elasticsearch/runtime/src/main/java/io/quarkus/hibernate/search/orm/elasticsearch/runtime/HibernateSearchElasticsearchBuildTimeConfigPersistenceUnit.java [hunk 2]
```diff
@@ -244,8 +228,8 @@ public static class CoordinationConfig {
          *
          * @asciidoclet
          */
-        @ConfigItem(defaultValue = "none")
-        public Optional<String> strategy;
+        @WithDefault("none")
+        Optional<String> strategy();
```
Comment (yrodiere) [inline extensions/hibernate-search-orm-elasticsearch/runtime/src/main/java/io/quarkus/hibernate/search/orm/elasticsearch/runtime/HibernateSearchElasticsearchBuildTimeConfigPersistenceUnit.java:232]: Hey, and optional with a default value looks odd... I know it's not new, but still. Shouldn't this be `@ConfigDocDefault` instead?

Comment (gsmet) [reply extensions/hibernate-search-orm-elasticsearch/runtime/src/main/java/io/quarkus/hibernate/search/orm/elasticsearch/runtime/HibernateSearchElasticsearchBuildTimeConfigPersistenceUnit.java:232]: Agreed that it's odd. I wasn't sure how to change it so kept it as is.

File: extensions/hibernate-search-orm-elasticsearch/runtime/src/main/java/io/quarkus/hibernate/search/orm/elasticsearch/runtime/HibernateSearchElasticsearchBuildTimeConfig.java (hunk 1 above)
Comment (gsmet) [reply extensions/hibernate-search-orm-elasticsearch/runtime/src/main/java/io/quarkus/hibernate/search/orm/elasticsearch/runtime/HibernateSearchElasticsearchBuildTimeConfig.java:56]: We can avoid creating the method if you prefer. I wanted to be extra safe but I agree the checks should be useless.

Comment (yrodiere) [reply extensions/hibernate-search-orm-elasticsearch/runtime/src/main/java/io/quarkus/hibernate/search/orm/elasticsearch/runtime/HibernateSearchElasticsearchBuildTimeConfig.java:56]: I'd personally favor the simpler option, yes.

I created #32295 to perhaps address this directly in the config extension.

**Comment by radcortez** [comment]
> 1. The doc generation is broken when you don't have `@ConfigGroup`: `target/asciidoc/generated/config/quarkus-hibernate-search-orm-elasticsearch.adoc` is mostly empty and is incorrect as config groups are not handled. If the solution is to put back the `@ConfigGroup` annotations, I can do it.

Yes, right now for separate classes, it requires the `@ConfigGroup` annotation. It will work if the group classes are nested in the main interface. I'll enhance the processor to also cover that case.

> 2. I think we have a bug somewhere as I checked what I did several times and I can't figure out what I did wrong with `active` that would explain this behavior.

This requires a fix in SR Config. I'm pushing a new version shortly.

**Comment by gsmet** [comment]
I restored the config groups but things in the doc are still not up to par: I think `@WithParentName` is not taken into account. Also I have issues with the default values.

I'll have a look later this week.

File: extensions/hibernate-search-orm-elasticsearch/runtime/src/main/java/io/quarkus/hibernate/search/orm/elasticsearch/runtime/HibernateSearchElasticsearchBuildTimeConfig.java (hunk 1 above)
Comment (gsmet) [reply extensions/hibernate-search-orm-elasticsearch/runtime/src/main/java/io/quarkus/hibernate/search/orm/elasticsearch/runtime/HibernateSearchElasticsearchBuildTimeConfig.java:56]: I kept this for now because it's practical, we can drop it at some later point.

**Comment by gsmet** [comment]
i fixed the various doc issues and also migrated the Oubox Polling mapping to be consistent.

All tests pass locally, let's see what CI has to say.

Thanks @radcortez for the fixes you applied to SmallRye Config!

**Review by yrodiere — APPROVED** [review]
LGTM, thanks!

**Comment by gsmet** [comment]
@radcortez it seems there is a remaining problem with native:

```
2023-04-06T21:55:02.7392959Z java.lang.IllegalArgumentException: SRCFG00013: No Converter registered for class org.hibernate.search.backend.elasticsearch.ElasticsearchVersion
2023-04-06T21:55:02.7393660Z 	at io.smallrye.config.SmallRyeConfig.requireConverter(SmallRyeConfig.java:484)
2023-04-06T21:55:02.7394714Z 	at io.smallrye.config.ConfigMappingContext.getConverter(ConfigMappingContext.java:115)
2023-04-06T21:55:02.7395337Z 	at io.smallrye.config.ConfigMappingContext.lambda$getValueConverter$4(ConfigMappingContext.java:94)
2023-04-06T21:55:02.7395863Z 	at java.base@17.0.6/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
2023-04-06T21:55:02.7396407Z 	at io.smallrye.config.ConfigMappingContext.getValueConverter(ConfigMappingContext.java:91)
2023-04-06T21:55:02.7397399Z 	at io.quarkus.hibernate.search.orm.elasticsearch.runtime.HibernateSearchElasticsearchBuildTimeConfigPersistenceUnit$ElasticsearchBackendBuildTimeConfig1366744350Impl.<init>(Unknown Source)
```

`ElasticsearchVersion` has a static `of(String)` method so shouldn't require a converter. I'm not sure what's going on with native because it seems to work in non-native. Maybe the `of(String)` method is removed from the image while it wasn't before?

I could add a `Converter` but we are using this pattern in a lot of places so it's going to become a problem.

**Comment by radcortez** [comment]
Try with https://github.com/quarkusio/quarkus/pull/32162 :)

**Comment by radcortez** [comment]
I did encounter that issue before when I rewrote the OTel mappings. The issue is that extension mappings are discovered differently from application mappings, and we were missing registration for extension mappings implicit converters. https://github.com/quarkusio/quarkus/pull/32162 should take care of that.

**Comment by gsmet** [comment]
@radcortez thanks! I merged your PR and rebased, let's see how it goes.

**Review by radcortez — APPROVED** [review]
