### PR TITLE
Don't wrap exceptions thrown by StreamingOutput

### LINKED ISSUE #52115: Exception Mapping does not work anymore for streaming responses
### Describe the bug

In the provided example project, the MainExceptionMapper is prepared to handle: 
- a runtime exception (MyRuntimeException) and
- a checked exception (MySneakyException) which might slip through `@SneakyThrows`.

These are handled properly when the REST method throws an exception, like in

  ```
    @GET
    @Path("/getMyRuntimeEx")
    public Response getMyRuntimeEx() {
        throw new MyRuntimeException("RuntimeEx in plain GET");
    }

    @GET
    @Path("/getMySneakyEx")
    public Response getMySneakyEx() {
        throwSneakyEx("Sneaky in plain GET");

        return Response.ok().entity("Why did the chicken cross the road?").build();
    }

    @SneakyThrows
    private static void throwSneakyEx(String msg) {
        throw new MySneakyException(msg);
    }
```

But when the REST method returns a streaming response (StreamingOutput), like in
```
    @GET
    @Path("/streamMyRuntimeEx")
    public Response streamMyRuntimeEx() {
        return buildResponse((StreamingOutput) outputStream -> {
            // This StreamingOutput might come from a library,
            // and might throw an exception during initialization,
            // before writing anything to the stream.
            throw new MyRuntimeException("RuntimeEx before writing anything to the stream");
        });
    }

    @GET
    @Path("/streamMySneakyEx")
    public Response streamMySneakyEx() {
        return buildResponse((StreamingOutput) outputStream -> {
            throwSneakyEx("SneakyEx before writing anything to the stream");
        });
    }
```
the MainExceptionMapper does not kick in anymore (from version 3.29.1) when an exception is thrown before writing anything to the outputStream.

It was working up to version 3.29.0. 
Well for runtime exceptions, sneaky ones were broken in earlier versions too.

### Expected behavior

Pass all test cases in the attached ExMapperVsStreamingResponseTest.

That is, the MainExceptionMapper should handle exceptions thrown before writing anything to the outputStream in a StreamingOutput.
It should also handle checked exceptions slipped through `@SneakyThrows`.

Sometimes StreamingOutput objects come from a library, and they might throw exceptions during initialization. 
Handling those would be useful.

### Actual behavior

The exception mapper does not work for StreamingOutput responses as mentioned above from version 3.29.1.

### How to Reproduce?

Here is an example project: 

[quarkus-exception-mapper-vs-streaming-response.tar.gz](https://github.com/user-attachments/files/24764256/quarkus-exception-mapper-vs-streaming-response.tar.gz)

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

3.30.6

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
- Closes: #52115

### CODE REVIEW

File: independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/providers/serialisers/StreamingOutputMessageBodyWriter.java [hunk 1]
```diff
@@ -56,15 +56,7 @@ public void writeResponse(StreamingOutput o, Type genericType, ServerRequestCont
...
-                if (t instanceof WebApplicationException) {
-                    throw (WebApplicationException) t;
-                } else if (t instanceof IOException) {
-                    throw new WebApplicationException(t);
-                } else if (t instanceof RuntimeException) {
-                    throw new WebApplicationException(t);
-                } else {
-                    throw new WebApplicationException(t);
-                }
+                throw t;
```
Comment (gsmet) [inline independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/providers/serialisers/StreamingOutputMessageBodyWriter.java:59]: That won't leak the exception to the client? IIRC, that's why these were wrapped?

Comment (geoand) [reply independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/providers/serialisers/StreamingOutputMessageBodyWriter.java:59]: Nope, it's what we were doing before, and also ensures that exceptions in the normal Jakarta REST manner

**Review by FroMage — CHANGES_REQUESTED** [review]
I agree with the fix, but I'm puzzled by the test. The original issue's test had the `StreamingOutput` lambda throw during (I guess) `write` to make sure the exception mapper was invoked, where your test appears to successfully stream?

**Comment by geoand** [comment]
Didn't I add two test methods? One that streams correctly and one that fails, no?

**Comment by FroMage** [comment]
I see only one new method :-/

**Comment by geoand** [comment]
Darn, I must have forgot to commit

**Comment by geoand** [comment]
PR updated

File: independent-projects/resteasy-reactive/server/vertx/src/test/java/org/jboss/resteasy/reactive/server/vertx/test/providers/StreamingOutputTestCase.java [hunk 2]
```diff
@@ -39,17 +44,73 @@ public void testWith() {
...
+                .then()
+                .statusCode(200)
+                .body(equalTo("hello world"));
+    }
+
+    @Test
+    public void testWithErrorAndResponse() {
+        get("/test/response/error")
+                .then()
+                .statusCode(400);
```
Comment (FroMage) [inline independent-projects/resteasy-reactive/server/vertx/src/test/java/org/jboss/resteasy/reactive/server/vertx/test/providers/StreamingOutputTestCase.java:59]: I suppose this is enough to make sure there's an entity mapper because otherwise we'd have gotten a 500 internal server error?

**Review by FroMage — APPROVED** [review]
Good. I re-read the test three times because I doubted myself more than you 😅

File: independent-projects/resteasy-reactive/server/vertx/src/test/java/org/jboss/resteasy/reactive/server/vertx/test/providers/StreamingOutputTestCase.java (hunk 2 above)
Comment (geoand) [reply independent-projects/resteasy-reactive/server/vertx/src/test/java/org/jboss/resteasy/reactive/server/vertx/test/providers/StreamingOutputTestCase.java:59]: Yeah, it shows that the exception mapper is being engaged
