### PR TITLE
Fix native applications built with GraalVM 25 `--future-defaults` options

### LINKED ISSUE #46092: Add option to run-time initialize JDK classes
### Description

Currently we can't test the flag `-H:-InitializeJDKAtBuildTimeMigration` that is planned to be introduced to GraalVM with https://github.com/oracle/graal/pull/10531 because GraalVM internally registers classes for build-time or run-time registrations using the same mechanisms we do. 

The idea behind the `-H:-InitializeJDKAtBuildTimeMigration` flag is that it will not register JDK classes for build-time initialization (which is what happens now), allowing them to be run-time initialized which is the default behavior for classes without explicit build time initialization strategy. However, in [Quarkus registers everything for build-time initialization](https://github.com/quarkusio/quarkus/blob/4217cdb768d0cc44f183536bdfb4cfceeea9713a/core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageFeatureStep.java#L94-L95) so we will need to explicitly register for run-time initialization any JDK classes no longer being registered for build time initialization when using `-H:-InitializeJDKAtBuildTimeMigration`.

Relates to https://github.com/quarkusio/quarkus/discussions/42682 which if implemented would possibly make this easier.

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by galderz**
Closes #46092

The changes in this PR adapt Quarkus to be able to run natives built with `--future-defaults` values available in GraalVM 25.0.

The changes do not affect Quarkus unless the additional native build time argument via the given parameter is passed in. The possible values can be found in the [GraalVM 25.0 release notes](https://www.graalvm.org/release-notes/JDK_25/). Each of the necessary changes is protected by some build time check that indicates which future defaults are responsible for which changes.

I have tested the flag in [this custom Mandrel CI run](https://github.com/galderz/mandrel/actions/runs/19068758868), which includes Quarkus testsuite (the failures seen in the run are strictly limited to the Mandrel testsuite which has no yet been adjusted for JDK 25 /cc @Karm). To test the flag, I set the additional native build time argument env variable to relevant values to make sure the test passes. The Mandrel team will create a periodic CI that verifies that the testsuite still passes with these arguments.

I run peak and startup performance tests for the `getting-started-reactive` and `security-jpa-reactive quickstarts`. I didn't see any signinificant changes in peak throughtput. Startup times are unchanged but I've noticed a ~2MB additional startup RSS and this decreases to around ~1MB at peak performance. There is a 1-2 MB increase in binary file size increase too.

### CODE REVIEW

File: extensions/spring-data-jpa/deployment/src/main/java/io/quarkus/spring/data/deployment/SpringDataJPAProcessor.java [hunk 1]
```diff
@@ -97,6 +98,12 @@ IgnorableNonIndexedClasses ignorable() {
         return new IgnorableNonIndexedClasses(ignorable);
     }
 
+    @BuildStep(onlyIf = NativeImageFutureDefaults.CompleteReflectionTypes.class)
+    void registerReflectionForCompleteReflectionTypes(BuildProducer<ReflectiveClassBuildItem> producer) {
```
Comment (Sanne) [inline extensions/spring-data-jpa/deployment/src/main/java/io/quarkus/spring/data/deployment/SpringDataJPAProcessor.java:101]: hey @galderz , I don't know all details here so just being curious - how did you figure out that this was needed, are the new defaults stricter, or do they come with better diagnostic messages?

Also - is the conditional execution of the buildStep really necessary?  I'd generally let the build system decide.

**Review by gsmet — DISMISSED** [review]
Just a note that the commits will need some cleanup. I'll have a closer look later.

File: extensions/spring-data-jpa/deployment/src/main/java/io/quarkus/spring/data/deployment/SpringDataJPAProcessor.java (hunk 1 above)
Comment (galderz) [reply extensions/spring-data-jpa/deployment/src/main/java/io/quarkus/spring/data/deployment/SpringDataJPAProcessor.java:101]: > hey @galderz , I don't know all details here so just being curious - how did you figure out that this was needed, are the new defaults stricter, or do they come with better diagnostic messages?

The new defaults are stricter. They come with no additional diagnostic messages. The initial future default values are 5, but really it's only 3 since the other 2 are composites. So, I started testing them individually and saw what broke and needed changing. Then I started to add conditionals for each of them. So, in this particular case, this change was only needed when the `complete-reflection-types` future default was enabled.

> Also - is the conditional execution of the buildStep really necessary? I'd generally let the build system decide.

I wanted to minimise the effects of adding support for these future defaults, so I went for the most conservative option of only making changes if any of these future defaults are enabled. I don't expect this option to be something users would typically enable. What seemed important to me is that if they ever enable any of them (or all of them) then things work as expected..

**Comment by galderz** [comment]
@gsmet squashed commits

File: extensions/spring-data-jpa/deployment/src/main/java/io/quarkus/spring/data/deployment/SpringDataJPAProcessor.java (hunk 1 above)
Comment (Sanne) [reply extensions/spring-data-jpa/deployment/src/main/java/io/quarkus/spring/data/deployment/SpringDataJPAProcessor.java:101]: ok, thanks for the context!

Regarding the conditional though - I'd say let's test such things in all cases? The less conditionals, the better. And we'd get better coverage in preparation for such changes as well.

I'm still a bit puzzled on why this would have worked without it, if it was necessary it surely would have been neccessary even before?

**Review by Sanne — APPROVED** [review]
Great, thank you @galderz !

**Review by jerboaa — APPROVED** [review]
Looks OK to me.
