### PR TITLE
Move rocksdb native library resource registration to a feature

### LINKED ISSUE #43319: Unable to run application with kafka-stream on aarch64 built using native builder image
### Describe the bug

Unable to run application with kafka-stream on aarch64 in native, application built using builder image (use-case of RHBQ)

application startup fails with
```
[hudson@ampere-mtsnow-altramax-03-vm-13 code-with-quarkus]$ target/code-with-quarkus-1.0.0-SNAPSHOT-runner
Sep 15, 2024 7:18:35 AM io.quarkus.runtime.ApplicationLifecycleManager run
ERROR: Failed to start application
java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:119)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
Caused by: java.lang.ExceptionInInitializerError
	at io.quarkus.kafka.streams.runtime.KafkaStreamsRecorder.loadRocksDb(KafkaStreamsRecorder.java:14)
	at io.quarkus.deployment.steps.KafkaStreamsProcessor$loadRocksDb1611413226.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.KafkaStreamsProcessor$loadRocksDb1611413226.deploy(Unknown Source)
	... 7 more
Caused by: java.lang.RuntimeException: librocksdbjni-linux-aarch64.so was not found inside JAR.
	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJarToTemp(NativeLibraryLoader.java:118)
	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:102)
	at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:82)
	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:70)
	at org.rocksdb.RocksDB.<clinit>(RocksDB.java:39)
	... 10 more
```

The binary contains strings with mixture of `librocksdbjni-linux-aarch64.so` and `librocksdbjni-linux64.so`
```
strings target/code-with-quarkus-1.0.0-SNAPSHOT-runner | grep librocksdbjni
librocksdbjni-linux-aarch64.so
librocksdbjni-linux64.so
librocksdbjni
```

If the application is built using locally installed Mandrel, the app works well and strings command returns just librocksdbjni-linux-aarch64.so in 2 occurrences.

`docker inspect quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-21` reports architecture as `arm64`

This was detected when working on investigation of Quarkus Quickstarts failures investigation on aarch64 platform.

CC @cescoffier @zakkak @galderz
FYI @mjurc

### Expected behavior

Native application built using native builder image can start on RHEL 8 aarch64

### Actual behavior

Native application built using native builder image can't start on RHEL 8 aarch64

### How to Reproduce?

Using code.quarkus:
```
wget -O app.zip "https://code.quarkus.io/d?e=kafka-streams&cn=code.quarkus.io"
unzip -q app.zip
cd code-with-quarkus/
mvn clean package -Dnative -Dquarkus.native.container-build=true
target/code-with-quarkus-1.0.0-SNAPSHOT-runner
```

Using https://github.com/quarkusio/quarkus-quickstarts:
```
git clone https://github.com/quarkusio/quarkus-quickstarts -b development
cd quarkus-quickstarts
mvn clean verify -f kafka-streams-quickstart -Dnative -Dquarkus.native.container-build=true
```

### Output of `uname -a` or `ver`

RHEL 8 aarch64

### Output of `java -version`

Java 21

### Mandrel or GraalVM version (if different from Java)

quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-21

### Quarkus version or git rev

Quarkus main / Quarkus 3.14

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by zakkak**
Always registers the correct native library as the logic runs on the same architecture we are targeting (even when using containers).

Closes https://github.com/quarkusio/quarkus/issues/43319

### CODE REVIEW

**Comment by zakkak** [comment]
@rsvoboda I am trying to get access to an AArch64 machine to give this a go, but it takes much longer than expected. So if you have a setup you can easily use to confirm the PR resolves the issue please let me know. Thanks

**Comment by rsvoboda** [comment]
@zakkak I can look into it, provisioning machine from Beaker usually takes ~1 hour, so I will have to wait too ...

File: extensions/kafka-streams/runtime/src/main/java/io/quarkus/kafka/streams/runtime/graal/KafkaStreamsFeature.java [hunk 1]
```diff
@@ -0,0 +1,16 @@
...
+import org.graalvm.nativeimage.hosted.RuntimeResourceAccess;
+import org.rocksdb.util.Environment;
+
+public class KafkaStreamsFeature implements Feature {
+
+    @Override
+    public void afterRegistration(AfterRegistrationAccess access) {
+        String libraryFileName = Environment.getJniLibraryFileName("rocksdb");
+        RuntimeResourceAccess.addResource(Environment.class.getModule(), libraryFileName);
+        System.out.println("Added " + libraryFileName + " to the resources");
```
Comment (rsvoboda) [inline extensions/kafka-streams/runtime/src/main/java/io/quarkus/kafka/streams/runtime/graal/KafkaStreamsFeature.java:13]: `System.out` should be dropped

File: extensions/kafka-streams/deployment/src/main/java/io/quarkus/kafka/streams/deployment/KafkaStreamsProcessor.java [hunk 2]
```diff
@@ -236,4 +219,9 @@ void addHealthChecks(KafkaStreamsBuildTimeConfig buildTimeConfig, BuildProducer<
                         "io.quarkus.kafka.streams.runtime.health.KafkaStreamsStateHealthCheck",
                         buildTimeConfig.healthEnabled));
     }
+
+    @BuildStep
+    NativeImageFeatureBuildItem kafkaFeature() {
```
Comment (rsvoboda) [inline extensions/kafka-streams/deployment/src/main/java/io/quarkus/kafka/streams/deployment/KafkaStreamsProcessor.java:224]:
```suggestion
    NativeImageFeatureBuildItem kafkaStreamsFeature() {
```

**Comment by rsvoboda** [comment]
I've checked the reproducer and the app is working well on RHEL8 aarch64

**Comment by zakkak** [comment]
> I've checked the reproducer and the app is working well on RHEL8 aarch64

Great, thanks for the review and the testing @rsvoboda. I addressed both your comments.

**Review by rsvoboda — APPROVED** [review]

**Comment by rsvoboda** [comment]
Should we backport this to 3.15 branch? @gsmet @zakkak

**Comment by gsmet** [comment]
Probably at some point. I will add the label.
