### PR TITLE
Fix various issues in refreshed `quarkus update`

### LINKED ISSUE #46639: Quarkus CLI version 999-SNAPSHOT and 3.19.2 fails to update applications on Windows
### Describe the bug

I use Quarkus CLI to update my applications, on Windows, my applications can't be updated with Quarkus CLI v999-SNAPSHOT, but it works with other Quarkus CLI versions like 3.19.1. Applications seems to be updated, but whole process fails anyway. See also https://github.com/quarkusio/quarkus/pull/46308.

### Expected behavior

No failures, no errors, same as with older Quarkus CLI versions.

### Actual behavior

Update results in following failure:

```
PS C:\cygwin\home\hudson\app> C:\cygwin\home\hudson\quarkus-test-suite\quarkus-dev-cli.bat update
[INFO] Error stacktraces are turned on. 
[INFO] Scanning for projects... 
[INFO]  
[INFO] ----------------------------< org.acme:app >----------------------------
[INFO] Building app 1.0.0-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- quarkus:999-SNAPSHOT:update (default-cli) @ app ---
[WARNING] quarkus:update goal is experimental, its options and output might change in future versions 
[INFO] Looking for the newly published extensions in registry.quarkus.io 
[INFO] Detected project Java version: 21 
[INFO]  
[INFO] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[INFO]
[INFO] Suggested Quarkus platform BOM updates:
[INFO]  ~       io.quarkus.platform:quarkus-bom:pom:[3.15.3.1 -> 3.19.1]
[INFO]
[INFO] Suggested extensions updates for 'io.quarkus.platform:quarkus-bom':
[INFO]  v       io.quarkus:quarkus-arc (synced with BOM)
[INFO]  v       io.quarkus:quarkus-rest (synced with BOM)
[INFO]
[INFO]
[INFO] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[INFO]
[INFO]
[INFO] Resolving recipes from 'io.quarkus:quarkus-update-recipes':
[INFO] * matching recipes directory 'core' found: 
[INFO]     - '3.18.alpha1.yaml' (3.15.3.1 -> 3.19.1)
[INFO]     - '3.19.alpha1.yaml' (3.15.3.1 -> 3.19.1)
[INFO] => 2 specific recipe(s) found
[INFO]  
[INFO] We have generated a recipe file to update your project (versions updates + specific recipes):
[INFO] target\rewrite\rewrite.yaml
[INFO] 

Do you want run the generated update recipe with OpenRewrite ? ([y]es, [n]o, [d]ry-run)

y 
[INFO] Running recipe with OpenRewrite 6.2.0... 
[INFO]
[INFO]  
[INFO]
[INFO]
[INFO]  ------------------------------------------------------------------------
[INFO] Executing (this may take a while):
C:\cygwin\home\hudson\app\mvnw.cmd -B -e org.openrewrite.maven:rewrite-maven-plugin:6.2.0:run -Drewrite.plainTextMasks=**/*.adoc,**/src/test/resources/__snapshots__/**/*.java,**/*.kt,*
*/*.md,**/src/main/codestarts/**/*.java,**/*.txt,**/META-INF/services/** -Drewrite.configLocation=C:\cygwin\home\hudson\app\target\rewrite\rewrite.yaml -Drewrite.recipeArtifactCoordina
tes=io.quarkus:quarkus-update-recipes:1.2.0 -Drewrite.activeRecipes=io.quarkus.openrewrite.Quarkus -Drewrite.pomCacheEnabled=false
[INFO]
[INFO] Rewrite process completed. Logs can be found at: target\rewrite\rewrite.log 
[INFO]  
[INFO]  
[INFO]
[INFO]
[INFO]  ------------------------------------------------------------------------
[INFO] Executing (this may take a while):
C:\cygwin\home\hudson\app\mvnw.cmd -B clean process-sources
[INFO]
[INFO] ------------------------------------------------------------------------ 
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  59.790 s
[INFO] Finished at: 2025-03-05T17:59:54+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:update (default-cli) on project app: The command to update the project exited with an errorLogs can be found
 at: target\rewrite\rewrite.log -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:update (default-cli) on project app: The command to update t
he project exited with an errorLogs can be found at: target\rewrite\rewrite.log
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:333)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101) 
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:906)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:283)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:206)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:906)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:283)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:206)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke (Method.java:580)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:255)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:201)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:361)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:314)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke (Method.java:580)
    at org.apache.maven.wrapper.BootstrapMainStarter.start (BootstrapMainStarter.java:52)
    at org.apache.maven.wrapper.WrapperExecutor.execute (WrapperExecutor.java:161)
    at org.apache.maven.wrapper.MavenWrapperMain.main (MavenWrapperMain.java:73)
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
PS C:\cygwin\home\hudson\app>
```

### How to Reproduce?

```
# use PowerShell to prepare Quarkus CLI v 999-SNAPSHOT
$quarkusCliFileContent = @"
@ECHO OFF
java -jar c:\\users\\hudson\\.m2\\repository\\io\\quarkus\\quarkus-cli\\999-SNAPSHOT\\quarkus-cli-999-SNAPSHOT-runner.jar %*
"@
New-Item -Path "$(pwd)\quarkus-dev-cli.bat" -ItemType File
Set-Content -Path "$(pwd)\quarkus-dev-cli.bat" -Value $quarkusCliFileContent
./quarkus-dev-cli.bat version

# now run tests

# attempt 1 - fails
C:\cygwin\home\hudson\quarkus-test-suite\quarkus-dev-cli.bat create app app --stream=3.2
cd app
C:\cygwin\home\hudson\quarkus-test-suite\quarkus-dev-cli.bat update -y --stream=3.15

# attempt 2 - fails
C:\cygwin\home\hudson\quarkus-test-suite\quarkus-dev-cli.bat create app app --stream=3.15
cd app
C:\cygwin\home\hudson\quarkus-test-suite\quarkus-dev-cli.bat update -y

# attempt 3 - fails
C:\cygwin\home\hudson\quarkus-test-suite\quarkus-dev-cli.bat create app app --stream=3.15
cd app
C:\cygwin\home\hudson\quarkus-test-suite\quarkus-dev-cli.bat update

# Quarkus CLI 3.19.1 -> pass
quarkus create app app --stream=3.2
cd app
quarkus update --stream=3.15
```

Or you can see failures if you use the jar directly:

```
java -jar c:\\users\\hudson\\.m2\\repository\\io\\quarkus\\quarkus-cli\\999-SNAPSHOT\\quarkus-cli-999-SNAPSHOT-runner.jar create app app --stream=3.15

java -jar c:\\users\\hudson\\.m2\\repository\\io\\quarkus\\quarkus-cli\\999-SNAPSHOT\\quarkus-cli-999-SNAPSHOT-runner.jar update
```

### Output of `uname -a` or `ver`

Windows Server 2019, Microsoft Windows Server 2022

### Output of `java -version`

Temurin 21

### Quarkus version or git rev

999-SNAPSHOT

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.9.9

### Additional information

cc @ia3andy

### PR DESCRIPTION
**Pull request by gsmet**
I started having a look as bold and underline were leaking (it's very visible when running the tests from https://github.com/quarkusio/quarkus-updates) and things led to others.

One important thing is that the `target/rewrite` directory was dropped by the `mvn clean process-sources` so you ended up with no logs being available.

I did a lot of manual testing on my side.

This needs to go in before we push the first final `3.20`.

Fixes #46639 (per Rostislav's comment below)

### CODE REVIEW

**Review by ia3andy — APPROVED** [review]
Didn't test it, but code looks good! Thanks!

**Comment by ia3andy** [comment]
We might need to store the logs in a buffer before writing them in the file (to avoid file locking):
https://github.com/quarkusio/quarkus/issues/46639#issuecomment-2719053139

**Comment by ia3andy** [comment]
@gsmet any reason to do `clean process-source` and not just `process-source`?

**Comment by rsvoboda** [comment]
I wanted to try this on my wife's Windows machine, but I hit https://github.com/quarkusio/quarkus/issues/46792
I will try to install git and give it second try :/

File: independent-projects/tools/devtools-common/src/main/java/io/quarkus/devtools/project/update/rewrite/QuarkusUpdateCommand.java [hunk 1]
```diff
@@ -195,10 +195,23 @@ private static void executeRewrite(Path baseDir, Map<String, List<String>> comma
...
-        String logInfo = logFile != null ? "Logs can be found at: %s".formatted(baseDir.relativize(logFile).toString())
-                : "See the execution logs above for more details";
+        String logInfo;
+
+        if (logFile != null) {
+            logInfo = "Logs can be found at: %s".formatted(baseDir.relativize(logFile).toString());
+
+            try {
+                // we delete the log file prior to executing the command so that we start clean
+                Files.deleteIfExists(logFile);
```
Comment (michalvavrik) [inline independent-projects/tools/devtools-common/src/main/java/io/quarkus/devtools/project/update/rewrite/QuarkusUpdateCommand.java:205]: I don't understand this part, when you say _Logs can be found at_ and than you delete the log file, you can't see it there. I presume that `baseDir.relativize(logFile)` refers to different file than `logFile`?

**Review by rsvoboda — APPROVED** [review]
This fixes https://github.com/quarkusio/quarkus/issues/46639, and the update command is now finished successfully.

After installing git and cloning I could build Quarkus, on that non-dev machine it took 33 minutes with `-Dquickly -Dno-test-modules` :/ And the time wasn't massively spent on downloads as I have a fibre channel connection at home :)

Just for the record, I initially built the fork on my dev machine and copied quarkus-cli-999-SNAPSHOT-runner.jar to the Windows machine, but it's not working approach as update is called through quarkus maven plugin. So that's why I needed to build and install the bits on Windows machine ...

File: independent-projects/tools/devtools-common/src/main/java/io/quarkus/devtools/project/update/rewrite/QuarkusUpdateCommand.java (hunk 1 above)
Comment (rsvoboda) [reply independent-projects/tools/devtools-common/src/main/java/io/quarkus/devtools/project/update/rewrite/QuarkusUpdateCommand.java:205]: execution happens on line 217 and `logInfo` is passed to the called method .. that's how I interpreted the code and was OK with it :)

Comment (michalvavrik) [reply independent-projects/tools/devtools-common/src/main/java/io/quarkus/devtools/project/update/rewrite/QuarkusUpdateCommand.java:205]: so you basically say that the loggin message is for the next file that will be generated? so why is it hidden behind `logFile != null`, it doesn't make sense to me

Comment (michalvavrik) [reply independent-projects/tools/devtools-common/src/main/java/io/quarkus/devtools/project/update/rewrite/QuarkusUpdateCommand.java:205]: okay, I understand, so when `logFile != null`, it wil be stored in the file that they create; makes sense

Comment (gsmet) [reply independent-projects/tools/devtools-common/src/main/java/io/quarkus/devtools/project/update/rewrite/QuarkusUpdateCommand.java:205]: @michalvavrik sorry for the late answer. It's a bit confusing but we open the file with an append or create later so that all the executed commands accumulate in the log file. So basically I delete it, so that we start fresh every time we execute an update.

Otherwise you end up with multiple iterations.

Pattern is so so but is probably good enough.
