### PR TITLE
Avoid storing timestamp in Gradle.properties

### LINKED ISSUE #41182: Running Quarkus CLI rewrites gradle.properties
### Describe the bug

Running the Quarkus CLI to add an extension reorders the properties in `gradle.properties`. It also adds a timestamp. This is quite hostile to version control.

### Expected behavior

The file is not changed if no changes are required. If changes are required existing properties are not reordered and comments are not removed. No timestamp is added.

### Actual behavior

The properties are reordered and a timestamp is added.

### How to Reproduce?

Steps to reproduce

1. Create a Quarkus app with Gradle support: `quarkus create app --gradle && cd code-with-quarkus`
2. View `gradle.properties`.
3. Add an extension, e.g.: `quarkus extension add io.quarkus:quarkus-kotlin`
4. View `gradle.properties` again and note the changes.

### Output of `uname -a` or `ver`

Darwin Rods-MacBook-Pro.local 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:17:33 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6031 arm64

### Output of `java -version`

openjdk version "21.0.2" 2024-01-16 OpenJDK Runtime Environment Homebrew (build 21.0.2) OpenJDK 64-Bit Server VM Homebrew (build 21.0.2, mixed mode, sharing)

### Quarkus version or git rev

3.9.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.6

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by gastaldi**
- Fixes #41182

### CODE REVIEW

**Comment by gsmet** [comment]
Does it also avoid rewriting the file and respect the formatting of the existing file? Because I think that's what the original issue was about.

File: independent-projects/tools/devtools-common/src/main/java/io/quarkus/devtools/project/buildfile/AbstractGradleBuildFile.java [hunk 1]
```diff
@@ -47,22 +48,22 @@ public void writeToDisk() throws IOException {
...
             Files.write(rootProjectPath.resolve(getSettingsGradlePath()), getModel().getRootSettingsContent().getBytes());
             if (hasRootProjectFile(GRADLE_PROPERTIES_PATH)) {
-                try (ByteArrayOutputStream out = new ByteArrayOutputStream()) {
-                    getModel().getRootPropertiesContent().store(out, "Gradle properties");
-                    Files.write(rootProjectPath.resolve(GRADLE_PROPERTIES_PATH),
-                            out.toByteArray());
+                try (StringWriter sw = new StringWriter()) {
+                    getModel().getRootPropertiesContent().store(sw, "Gradle properties");
+                    Files.writeString(rootProjectPath.resolve(GRADLE_PROPERTIES_PATH),
+                            sw.toString());
```
Comment (gastaldi) [inline independent-projects/tools/devtools-common/src/main/java/io/quarkus/devtools/project/buildfile/AbstractGradleBuildFile.java:54]: Using `StringWriter` because of https://github.com/codejive/java-properties/issues/23

**Review by gsmet — APPROVED** [review]
Looks like a nice improvement. I will merge.

Could you have a look at what @radcortez did in the `quarkus config` CLI? Maybe it would benefit from this too.

**Comment by maxandersen** [comment]
awesome stuff @gastaldi !
