### PR TITLE
Properly set `typeOfHandler` field of `RouteBuildItem`

### LINKED ISSUE #48215: Bug in RouteBuildItem the builder has asBlockingRoute but not used internally
### Describe the bug

I spot this issue the builder of RouteBuildItem has the option asBlockingRoute but when it builds the  RouteBuildItem the constructor doesn't have it's fixed to NORMAL . I suppose this is a bug that doesn't allowe to create from an extension a Blocking route using a code like :
```java
 routes.produce(RouteBuildItem.newFrameworkRoute("/route")
                .withRequestHandler(recorder.createEndpointHandler("/route"))
                .asBlockingRoute()
                .build()); 
```

Image

### Expected behavior

We are able to create blocking routes from extension

### Actual behavior

The asBlockingRoute is ignored at the end.

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
- Fixes: https://github.com/quarkusio/quarkus/issues/48215

### CODE REVIEW

File: extensions/vertx-http/deployment-spi/src/main/java/io/quarkus/vertx/http/deployment/spi/RouteBuildItem.java [hunk 1]
```diff
@@ -81,14 +81,15 @@ public enum RouteType {
...
-    private final HandlerType typeOfHandler = HandlerType.NORMAL;
+    private final HandlerType typeOfHandler;
 
     private final boolean displayOnNotFoundPage;
     private final String notFoundPageTitle;
 
     private final String routeConfigKey;
 
     @SuppressWarnings("OptionalUsedAsFieldOrParameterType")
+    @Deprecated(since = "3.25", forRemoval = true)
```
Comment (gastaldi) [inline extensions/vertx-http/deployment-spi/src/main/java/io/quarkus/vertx/http/deployment/spi/RouteBuildItem.java:92]: It would be nice to add a javadoc here too suggesting what to use instead

**Review by gastaldi — APPROVED** [review]
LGTM

File: extensions/vertx-http/deployment-spi/src/main/java/io/quarkus/vertx/http/deployment/spi/RouteBuildItem.java (hunk 1 above)
Comment (geoand) [reply extensions/vertx-http/deployment-spi/src/main/java/io/quarkus/vertx/http/deployment/spi/RouteBuildItem.java:92]: I don't see any uses of it, I only deprecated it now so we can remove it later. The only use of the Build Item I see uses the builder.
