### PR TITLE
Fix documentation for Secured Routes in OpenShift

### LINKED ISSUE #33275: Secured Openshift routes should be documented
### Description

At the moment, secured Openshift routes[1] do not even have descriptions on the relevant properties[2]. 

[1] https://github.com/quarkusio/quarkus/pull/31839
[2] see https://quarkus.io/guides/deploying-to-openshift#quarkus-openshift-openshift-config_quarkus.openshift.route.tls.ca-certificate and every property, which starts with `quarkus.openshift.route.tls.`****

### Implementation ideas

Ideally, there should be a separate section in OCP deployment guide about secure routes, or a separate guide dedicated to secure connections (including HTTPS on baremetal) in general.

### PR DESCRIPTION
**Pull request by Sgitario**
Fix https://github.com/quarkusio/quarkus/issues/33275

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Comment by Sgitario** [comment]
It seems the configuration reference still does not display the property descriptions. I'm looking into this.

**Review by gsmet — APPROVED** [review]

**Comment by Sgitario** [comment]
> It seems the configuration reference still does not display the property descriptions. I'm looking into this.

I've just found the issue. PR updated.

File: extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/TLSConfig.java [hunk 1]
```diff
@@ -3,36 +3,43 @@
...
     /**
-     * @return the cert authority certificate contents.
+     * The cert authority certificate contents.
      */
+    @ConfigItem
     Optional<String> caCertificate;
 
     /**
-     * @return the certificate contents.
+     * The certificate contents.
```
Comment (fedinskiy) [inline extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/TLSConfig.java:17]: Does "contents" means **text** of certificate (2k bytes of base64 starting with "-----BEGIN CERTIFICATE-----") ? If so, how do we paste that into application.properties?

(this was the most important thing I wanted to see in the guide)
