### PR TITLE
Do not throw NPE when building an uberJar using a fileName configuration option

### LINKED ISSUE #2934: Creating an uberJar with a fileName config fails
**Describe the bug**
Creating an uberJar with a fileName set fails with a NPE. 

**Expected behavior**
Should package the uber jar without failing

**Actual behavior**
The command throws an expection but the uberJar is successfully created. 

**To Reproduce**
Run the following commands
1. `git clone -b uber-jar-bug https://github.com/machi1990/quarkus-quickstarts `
2. `cd quarkus-quickstarts/rest-client`
3. `mvn -e clean package -DskipTests -DskipITs -DuberJar=true` 

**Configuration**
N/A

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:  `Darwin`
 - Output of `java -version`:  `java version "1.8.0_202"`
 - GraalVM version (if different from Java): N/A
 - Quarkus version or git rev: `master`

**Additional context**
It is coming from here https://github.com/quarkusio/quarkus/blob/688ee16b0641ac60239c0c7970ce23b6cbff35ff/devtools/maven/src/main/java/io/quarkus/maven/BuildMojo.java#L205

### PR DESCRIPTION
**Pull request by machi1990**
Also add documentation of the finalName configuration option.

Fixes #2934

### CODE REVIEW

File: devtools/maven/src/main/java/io/quarkus/maven/BuildMojo.java [hunk 1]
```diff
@@ -202,7 +204,10 @@ public void execute() throws MojoExecutionException {
             // resolve the outcome we need here
             RunnerJarOutcome result = appCreator.resolveOutcome(RunnerJarOutcome.class);
             Artifact original = project.getArtifact();
-            original.setFile(result.getOriginalJar().toFile());
+            Path originalJar = result.getOriginalJar();
```
Comment (cescoffier) [inline devtools/maven/src/main/java/io/quarkus/maven/BuildMojo.java]: I'm a bit confused here.

If finalName is used why `getOriginalJar` is `null`, it should be the `finalName`. If not created, what t the project main artifact?

File: docs/src/main/asciidoc/maven-tooling.adoc [hunk 2]
```diff
@@ -450,3 +450,31 @@ When building an Uber-Jar you can specify entries that you want to exclude from
...
+----
+<build>
+    <plugins>
+        <plugin>
+            <groupId>io.quarkus</groupId>
+            <artifactId>quarkus-maven-plugin</artifactId>
+            <version>${quarkus.version}</version>
+            <configuration>
+                <uberJar>true</uberJar>
+                <finalName>uber-jar-name</finalName> <1>
```
Comment (cescoffier) [inline docs/src/main/asciidoc/maven-tooling.adoc]: We should also support the Maven `finalName`. See https://maven.apache.org/pom.html.

**Review by cescoffier — CHANGES_REQUESTED** [review]
I have a few questions; not about the fix but the overall behavior.

File: docs/src/main/asciidoc/maven-tooling.adoc (hunk 2 above)
Comment (machi1990) [reply docs/src/main/asciidoc/maven-tooling.adoc]: @cescoffier I’ll update the doc about this too. Will it (the two ways to configure finalName) lead to confusions?

File: devtools/maven/src/main/java/io/quarkus/maven/BuildMojo.java (hunk 1 above)
Comment (machi1990) [reply devtools/maven/src/main/java/io/quarkus/maven/BuildMojo.java]: > If finalName is used why `getOriginalJar` is `null`, it should be the `finalName`. 

I expected the same behaviour which is the case when set using Maven `finalName` build property. However this is not the case when `finalName` is a configuration property in `quarkus-maven-plugin`. 

> If not created, what t the project main artifact?

I am sorry, I did not get you here.

Comment (emmanuelbernard) [reply devtools/maven/src/main/java/io/quarkus/maven/BuildMojo.java]: Could we remove our specific configuration? @aloubyansky 
That's in the context of Gradle and native CLI support too I suppose.

Comment (aloubyansky) [reply devtools/maven/src/main/java/io/quarkus/maven/BuildMojo.java]: I actually was not aware we did it this way, I don't like this ".original" trick at all. The original JAR should not be replaced or renamed just because we decided to generate an extra JAR that is NOT conflicting with the original JAR.

Comment (aloubyansky) [reply devtools/maven/src/main/java/io/quarkus/maven/BuildMojo.java]: Ah, I see they are replacing it if the name is the same, sorry. I guess I would just move `originalJar = outputDir.resolve(finalName + ".jar");` before the `if(uberJar)`. That way originalJar would never be null.

Comment (aloubyansky) [reply devtools/maven/src/main/java/io/quarkus/maven/BuildMojo.java]: @emmanuelbernard I guess we could. There is a difference though between the Maven `finalName` and the one configured for `quarkus-maven-plugin`. If, e.g. the Maven `finalName` is initialized to `original` and the `quarkus-maven-plugin` to `quarkus` then `mvn package` will produce two JARs: `original.jar` and `other-runner.jar`.
So our `finalName` is affecting only the runner JAR filename, while the Maven one - the original app JAR.
TBH, I don't very much like what our `finalName` does. I'd prefer `runnerName` instead or something.

Comment (aloubyansky) [reply devtools/maven/src/main/java/io/quarkus/maven/BuildMojo.java]: ...the value of which should be the complete runner JAR file name, w/o expecting the -runner suffix be appended by the mojo.

Comment (machi1990) [reply devtools/maven/src/main/java/io/quarkus/maven/BuildMojo.java]: @aloubyansky thanks for the comments.

> Ah, I see they are replacing it if the name is the same, sorry. I guess I would just move `originalJar = outputDir.resolve(finalName + ".jar");` before the `if(uberJar)`. That way originalJar would never be null.

This should work. I'll make an update.

> ...the value of which should be the complete runner JAR file name, w/o expecting the -runner suffix be appended by the mojo.

+1.

Comment (machi1990) [reply devtools/maven/src/main/java/io/quarkus/maven/BuildMojo.java]: > ...the value of which should be the complete runner JAR file name, w/o expecting the -runner suffix be appended by the mojo.

@aloubyansky would we want to include this a part of the PR?

Comment (aloubyansky) [reply devtools/maven/src/main/java/io/quarkus/maven/BuildMojo.java]: No. But I think you can create a separate issue for it.

Comment (machi1990) [reply devtools/maven/src/main/java/io/quarkus/maven/BuildMojo.java]: I think it is related to this issue https://github.com/quarkusio/quarkus/issues/2931.

Comment (aloubyansky) [reply devtools/maven/src/main/java/io/quarkus/maven/BuildMojo.java]: Yes, pretty confusing. IMO, we should get rid of the ".original" one.
I don't think it makes sense attaching a non-uberjar to the project neither. It's useless w/o the lib.

Comment (machi1990) [reply devtools/maven/src/main/java/io/quarkus/maven/BuildMojo.java]: > Ah, I see they are replacing it if the name is the same, sorry. I guess I would just move `originalJar = outputDir.resolve(finalName + ".jar");` before the `if(uberJar)`. That way originalJar would never be null.

@aloubyansky, comment above has been addressed.

**Comment by aloubyansky** [comment]
@cescoffier this change does fix the NPE issue. I propose to merge it and review the way the name is configured as a separate one. WDYT?

File: docs/src/main/asciidoc/maven-tooling.adoc (hunk 2 above)
Comment (cescoffier) [reply docs/src/main/asciidoc/maven-tooling.adoc]: @aloubyansky WDYT about this?

**Comment by cescoffier** [comment]
@aloubyansky Agreed, I've added a small comment but something that we can handle is another issue.

**Review by cescoffier — APPROVED** [review]

File: docs/src/main/asciidoc/maven-tooling.adoc (hunk 2 above)
Comment (aloubyansky) [reply docs/src/main/asciidoc/maven-tooling.adoc]: I think we should change the name of the config option to reflect what it is about. As it is not the *final* name, at least, atm.
