### PR TITLE
Fix incorrect ImagePullPolicy forced setting

### LINKED ISSUE #11917: KubernetesProcessor  No registry was set for the container image, so 'ImagePullPolicy' is being force-set to 'IfNotPresent'.
**Describe the bug**
 this warnning appears even though  i put the 'property quarkus.container-image.registry' , so the kubernetes yml is not correctly generated
```
 - image: xxxx.dkr.ecr.us-east-1.amazonaws.com/business-command:1.0-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: business-command
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
```

**Expected behavior**
```
 - image: xxxx.dkr.ecr.us-east-1.amazonaws.com/business-command:0001
        imagePullPolicy: Always
        name: business-command
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
```
**Actual behavior**
(Describe the actual behavior clearly and concisely.)
[log.txt](https://github.com/quarkusio/quarkus/files/5177581/log.txt)

**Configuration**
```#CONFIG
com.app-name=${APP_NAME}
quarkus.package.output-name=${com.app-name}


# Log
quarkus.log.level=${LOG_LEVEL_ROOT:INFO}
#quarkus.log.category."io.smallrye".level=${LOG_LEVEL_ROOT:DEBUG}


#CLIENT SERVICIOS REST
data-core/mp-rest/url=http://data-core:8080


#DOCKER
quarkus.container-image.registry    =   xxxx.dkr.ecr.us-east-1.amazonaws.com
quarkus.container-image.build       =   true
quarkus.container-image.push        =   true
quarkus.container-image.name        =   ${com.app-name}
quarkus.container-image.tag         =   001
quarkus.container-image.group       =


#KUBE
quarkus.kubernetes.replicas=1
quarkus.kubernetes.part-of=core-app
quarkus.kubernetes.image-pull-policy=Always

```

### PR DESCRIPTION
**Pull request by geoand**
When the container image group was being set to empty
(which is allowed as a result of https://github.com/quarkusio/quarkus/pull/8139), then the
registry was incorrectly being determined as not being set

Fixes: #11917

### CODE REVIEW

File: extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/ContainerImageUtil.java [hunk 1]
```diff
@@ -21,7 +19,7 @@ static boolean isRegistryMissingAndNotS2I(Capabilities capabilities, ContainerIm
             return false;
         }
 
-        return !hasRegistry(containerImageInfo.getImage())
-                && !Capability.CONTAINER_IMAGE_S2I.equals(activeContainerImageCapability.get());
+        return !containerImageInfo.getRegistry().isPresent()
+                && !Capability.CONTAINER_IMAGE_S2I.getName().equals(activeContainerImageCapability.get());
```
Comment (geoand) [inline extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/ContainerImageUtil.java:23]: This was incorrectly checking the enum against the string

**Review by gsmet — APPROVED** [review]

**Review by iocanel — APPROVED** [review]
The changes I see here do look good.
However, I can't really tell out of my head if `getRegistry().isPresent()` is enough.
So, I put my trus in you and the existing code working as expected and give my +1.

**Comment by geoand** [comment]
> The changes I see here do look good.
> However, I can't really tell out of my head if `getRegistry().isPresent()` is enough.
> So, I put my trus in you and the existing code working as expected and give my +1.

Looking threw the code, I saw no reason why this wouldn't work
