### PR TITLE
ArC: split logic in ComponentsProviderGenerator

### LINKED ISSUE #45380: ClassTooLargeException when building an application containing many CDI beans
### Describe the bug

During the build phase of the application, we are getting a **ClassTooLargeException**
The number of CDI beans is ~ 13000 and it will be increasing!

We have a multi-module project heavily dependent on CDI. 
We are using the **quarkus-maven-plugin**

```
<plugin>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-maven-plugin</artifactId>
      <version>3.17.5</version>
    <executions>
        <execution>
            <goals>
                <goal>build</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:3.17.5:build (default) on project out-mapping-ear: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.arc.deployment.ArcProcessor#generateResources threw an exception: java.lang.reflect.UndeclaredThrowableException
[ERROR]         at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:862)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
[ERROR]         at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:833)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:499)
[ERROR] Caused by: java.util.concurrent.ExecutionException: org.objectweb.asm.ClassTooLargeException: Class too large: io/quarkus/arc/setup/Default_ComponentsProvider
[ERROR]         at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
[ERROR]         at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
[ERROR]         at io.quarkus.arc.processor.BeanProcessor.generateResources(BeanProcessor.java:440)
[ERROR]         at io.quarkus.arc.deployment.ArcProcessor.generateResources(ArcProcessor.java:539)
[ERROR]         at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)
[ERROR]         ... 8 more
[ERROR] Caused by: org.objectweb.asm.ClassTooLargeException: Class too large: io/quarkus/arc/setup/Default_ComponentsProvider
[ERROR]         at org.objectweb.asm.ClassWriter.toByteArray(ClassWriter.java:616)
[ERROR]         at io.quarkus.gizmo.ClassCreator.writeTo(ClassCreator.java:246)
[ERROR]         at io.quarkus.gizmo.ClassCreator.close(ClassCreator.java:257)
[ERROR]         at io.quarkus.arc.processor.ComponentsProviderGenerator.generate(ComponentsProviderGenerator.java:201)
[ERROR]         at io.quarkus.arc.processor.BeanProcessor$1.call(BeanProcessor.java:294)
[ERROR]         at io.quarkus.arc.processor.BeanProcessor$1.call(BeanProcessor.java:290)
[ERROR]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[ERROR]         ... 7 more
[ERROR] -> [Help 1]
```

This is the list of quarkus dependencies:
```
 <dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-core</artifactId>
     <version>3.17.5</version>
</dependency>
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-arc</artifactId>
     <version>3.17.5</version>
</dependency>
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-rest</artifactId>
     <version>3.17.5</version>
</dependency>
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-undertow</artifactId>
     <version>3.17.5</version>
</dependency>

```

### Expected behavior

Successful build 

### Actual behavior

```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:3.17.5:build (default) on project out-mapping-ear: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.arc.deployment.ArcProcessor#generateResources threw an exception: java.lang.reflect.UndeclaredThrowableException
[ERROR]         at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:862)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
[ERROR]         at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:833)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:499)
[ERROR] Caused by: java.util.concurrent.ExecutionException: org.objectweb.asm.ClassTooLargeException: Class too large: io/quarkus/arc/setup/Default_ComponentsProvider
[ERROR]         at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
[ERROR]         at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
[ERROR]         at io.quarkus.arc.processor.BeanProcessor.generateResources(BeanProcessor.java:440)
[ERROR]         at io.quarkus.arc.deployment.ArcProcessor.generateResources(ArcProcessor.java:539)
[ERROR]         at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)
[ERROR]         ... 8 more
[ERROR] Caused by: org.objectweb.asm.ClassTooLargeException: Class too large: io/quarkus/arc/setup/Default_ComponentsProvider
[ERROR]         at org.objectweb.asm.ClassWriter.toByteArray(ClassWriter.java:616)
[ERROR]         at io.quarkus.gizmo.ClassCreator.writeTo(ClassCreator.java:246)
[ERROR]         at io.quarkus.gizmo.ClassCreator.close(ClassCreator.java:257)
[ERROR]         at io.quarkus.arc.processor.ComponentsProviderGenerator.generate(ComponentsProviderGenerator.java:201)
[ERROR]         at io.quarkus.arc.processor.BeanProcessor$1.call(BeanProcessor.java:294)
[ERROR]         at io.quarkus.arc.processor.BeanProcessor$1.call(BeanProcessor.java:290)
[ERROR]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[ERROR]         ... 7 more
[ERROR] -> [Help 1]
```

### How to Reproduce?

In out project, we currently have ~ 13000 CDI beans
I expect that you need to create a lot of @Dependent beans! 
Not sure whether the size of the beans class itself matters!

### Output of `uname -a` or `ver`

OS name: "mac os x", version: "14.7.1", arch: "aarch64", family: "mac"

### Output of `java -version`

OpenJDK 64-Bit Server VM Corretto-17.0.7.7.1 (build 17.0.7+7-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.17.5

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mkouba**
- to support very large deployments
- we use the same strategy for beans, observers and removedBeans
- first we split the processing into multiple groups; each group is represented by a static method
- several groups belong to a container class
- static methods are invoked either directly from the ComponentsProvider or from a dedicated lambda

Fixes #45380

### CODE REVIEW

**Comment by mkouba** [comment]
FTR the container classes are necessary because of the constant pool limit.

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/ComponentsProviderGenerator.java [hunk 1]
```diff
@@ -123,26 +122,43 @@ private void createComponentsProvider(Gizmo gizmo, String name, BeanDeployment b
...
+                    // Each group is represented by a static method addBeansX(); X corresponds to the group id
+                    // Several groups belong to a container - a class named like Foo_ComponentsProvider_addBeansY; Y corresponds to the container id
+
                     // Map<String, InjectableBean<?>>
                     LocalVar beanIdToBean = bc.localVar("beanIdToBean", bc.new_(HashMap.class));
-                    for (BeanGroup group : info.beanGroups()) {
-                        ClassMethodDesc desc = ClassMethodDesc.of(cc.type(), ADD_BEANS + group.id(),
-                                void.class, Map.class);
-                        bc.invokeVirtual(desc, cc.this_(), beanIdToBean);
+                    for (ListIterator<List<BeanGroup>> it = info.groupContainers(info.beanGroups()).listIterator(); it
```
Comment (Ladicek) [inline independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/ComponentsProviderGenerator.java]: The explicit usage of iterators here (and elsewhere) is useless, no? It could just as well be a for-each, it seems to me?

Comment (Ladicek) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/ComponentsProviderGenerator.java]: Ah, I see it now -- you call the `previousIndex` method.

Well, if you ask me, I'd just take the groups in `CodeGenInfo` and applied `Grouping.of()` on those again, creating IDs along the way. Much easier to follow 😆

**Review by Ladicek — APPROVED** [review]
This is obviously OK (when I diff with whitespace disabled).

My only objection is that the secondary grouping is way too ugly compared to the primary grouping; it should be done the same way, also in `preprocess()`.

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/ComponentsProviderGenerator.java [hunk 2]
```diff
@@ -62,8 +61,8 @@ public class ComponentsProviderGenerator extends AbstractGenerator {
     static final String ADD_OBSERVERS = "addObservers";
     static final String ADD_REMOVED_BEANS = "addRemovedBeans";
     static final String ADD_BEANS = "addBeans";
-    private static final Comparator<BeanInfo> BEAN_INFO_COMPARATOR = Comparator.comparing(BeanInfo::getIdentifier);
-    private static final Comparator<ObserverInfo> OBSERVER_INFO_COMPARATOR = Comparator.comparing(ObserverInfo::getIdentifier);
+
+    static final int CONTAINER_SIZE = 5;
```
Comment (gsmet) [inline independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/ComponentsProviderGenerator.java]: I think I would use `10` or even maybe `20` here to avoid splitting too aggressively.

My understanding is that you split things by group of `150 + 150 + 5`? Given it was working fine with 4k beans, I think we could afford `600 + 600 + 100` and avoid splitting too much.

But it's really a detail.

**Review by gsmet — COMMENTED** [review]
I added a small comment but feel free to ignore if you have a strong opinion. My point is that we should avoid splitting in the relatively standard case that used to work before.

I kinda agree with @Ladicek that we should make the splitting as consistent as possible.

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/ComponentsProviderGenerator.java (hunk 2 above)
Comment (Ladicek) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/ComponentsProviderGenerator.java]: Agree we don't need too small groups, but this is a one-time setup, so it probably doesn't matter _too_ much.

Comment (mkouba) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/ComponentsProviderGenerator.java]: So for beans a group has 30 members, for observers 30 members and for removed beans 5 members. So for beans, the container class has at most 5 groups of 30 = 150. For observers the same. For removed beans it's 5 groups of 5 members = 25. We could try and experiment with the container size - that's why I created a constant ;-) - but it always depends on the complexity of the app. 

I think that we should be rather conservative and use a "safe" value here.

> Agree we don't need too small groups, but this is a one-time setup, so it probably doesn't matter _too_ much.

For 4K beans it would be ~ 27 classes. So yes, it doesn't really matter.

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/ComponentsProviderGenerator.java (hunk 1 above)
Comment (mkouba) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/ComponentsProviderGenerator.java]: > Much easier to follow 😆

Not for me, sorry :wink:. `ListIterator` is a well-known API, `Grouping` is not. No seriously, I will try to look at it tomorrow. But if you ask me - it's a ridiculous amount of nitpicking :smile:.

**Comment by mkouba** [comment]
> I kinda agree with @Ladicek that we should make the splitting as consistent as possible.

@gsmet I'm not sure what this sentence actually means?

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/ComponentsProviderGenerator.java (hunk 1 above)
Comment (Ladicek) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/ComponentsProviderGenerator.java]: I have honestly used `ListIterator` like once or twice in my entire life, so... :shrug:

My point is: `preprocess()` is there for a reason. All preprocessing we do, we do there -- so that when we do code generation, we don't have to do _anything else_ but code generation. Grouping looks like a silly preprocessing step, but it highlights how we structure the generated code, without having to look into the code generator itself.

Well, whatever. I'm certainly not gonna block this PR on this, I have actually already approved it :-) So it's your call.

**Comment by Ladicek** [comment]
> > I kinda agree with @Ladicek that we should make the splitting as consistent as possible.
> 
> @gsmet I'm not sure what this sentence actually means?

I'm not sure either, but if we did what I suggested on Zulip (split the bean graph into components and make sure the entire component is generated in a single method), we might get slight performance benefits of avoiding map lookups and using values directly. But I'm not sure how big those benefits would be.

**Comment by gsmet** [comment]
> @gsmet I'm not sure what this sentence actually means?

Sorry it was a reference to the `excessive nitpicking` on grouping :).

I'm perfectly fine with the general approach.

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/ComponentsProviderGenerator.java (hunk 1 above)
Comment (mkouba) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/ComponentsProviderGenerator.java]: I hope the last iteration will make you happy :wink:.

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/ComponentsProviderGenerator.java (hunk 2 above)
Comment (mkouba) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/ComponentsProviderGenerator.java]: @gsmet the container size is now 10 :wink:.

**Review by Ladicek — APPROVED** [review]

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/ComponentsProviderGenerator.java (hunk 1 above)
Comment (Ladicek) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/ComponentsProviderGenerator.java]: This looks pretty much perfect and I'm sure even you will agree the code is better :laughing:
