### PR TITLE
Use single mock when backing bean is the same instance

### LINKED ISSUE #15411: @InjectMock replaces existing mocks
**Describe the bug**
Basically what I have is class C1, which implements 2 interfaces I1 and I2. Class C2 then injects those 2 interfaces. The actual (non-test) code runs well, but in testing one of the mocks is not called.

It will probably be the simplest to understand with some pseudo code, as I have a hard time explaining the problem with words.

```
class C1 implements I1, I2 {...}

class C2 {
  @Inject I1
  @Inject I2

  method() {
    I1.m1()
    I2.m2()
  }
}

@QuarkusTest
class Test {
  @Inject C2
  @MockInject I1
  @MockInject I2

  @Test
  test() {
    when(I1)...
    when(I2)...

    C2.method()

    verify(I1) - NOT CALLED
    verify(I2) - CALLED
  }
}
```

From what I understand what happens is that the mocks replace the actual implementation, but that does not seem correct to me, because the implementation is not what I really want to mock or worry about.

Now... Does this qualify as a bug, or is it a "feature"? Is there some workaround except just creating interfaces that are the "same" as implementations (one interface per class)?

**Expected behavior**
Both mock get called.

**Actual behavior**
One mock gets called.

** To reproduce **

git clone https://github.com/blazmrak/inject-mock-issue.git
mvn clean test

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 10.0.19042.804
 - Output of `java -version`: 11.0.10
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.12
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 3.6.3

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #15411

### CODE REVIEW

**Comment by geoand** [comment]
Keeping in draft as master is broken for the moment. Once it is fixed, I'll move the PR out of draft

File: test-framework/junit5-mockito/src/main/java/io/quarkus/test/junit/mockito/internal/CreateMockitoMocksCallback.java [hunk 1]
```diff
@@ -25,30 +28,41 @@ public void afterConstruct(Object testInstance) {
...
+                        MockitoMocksTracker.track(testInstance, result.getValue(), beanInstance);
+                    }
                 }
             }
             current = current.getSuperclass();
         }
     }
 
-    private Object createMockAndSetTestField(Object testInstance, Field field, Object beanInstance) {
+    private Map.Entry<Boolean, Object> createMockAndSetTestField(Object testInstance, Field field, Object beanInstance) {
```
Comment (mkouba) [inline test-framework/junit5-mockito/src/main/java/io/quarkus/test/junit/mockito/internal/CreateMockitoMocksCallback.java:41]: Hm, why the `Map.Entry` here? Something like an `Optional<Object>` would be probably more clear, or?

File: integration-tests/injectmock/src/test/java/io/quarkus/it/mockbean/SameBeanInstanceTest.java [hunk 2]
```diff
@@ -0,0 +1,36 @@
...
+    SameBeanInstance.I4 i4;
+
+    @Test
+    public void sample() {
+        underTest.method1();
+
+        verify(i2).method2();
+        verify(i3).method3();
+        verify(i4, never()).method4();
+        ;
```
Comment (mkouba) [inline integration-tests/injectmock/src/test/java/io/quarkus/it/mockbean/SameBeanInstanceTest.java:34]: ? :D

**Review by mkouba — COMMENTED** [review]
Looks good. But beware that there might be use cases where a shared mock does not help. For example, if both `I2` and `I3` extend some `InterfaceX` and a user would attempt to mock `InterfaceX#foo()` for each of the `@InjectMock` (it's a corner case but still ;-).

File: integration-tests/injectmock/src/test/java/io/quarkus/it/mockbean/SameBeanInstanceTest.java (hunk 2 above)
Comment (geoand) [reply integration-tests/injectmock/src/test/java/io/quarkus/it/mockbean/SameBeanInstanceTest.java]: LOL. Fixed

File: test-framework/junit5-mockito/src/main/java/io/quarkus/test/junit/mockito/internal/CreateMockitoMocksCallback.java (hunk 1 above)
Comment (geoand) [reply test-framework/junit5-mockito/src/main/java/io/quarkus/test/junit/mockito/internal/CreateMockitoMocksCallback.java:41]: Yeah, I guess you are right. I'll fixi t

Comment (geoand) [reply test-framework/junit5-mockito/src/main/java/io/quarkus/test/junit/mockito/internal/CreateMockitoMocksCallback.java:41]: Fixed

**Comment by geoand** [comment]
> Looks good. But beware that there might be use cases where a shared mock does not help. For example, if both `I2` and `I3` extend some `InterfaceX` and a user would attempt to mock `InterfaceX#foo()` for each of the `@InjectMock` (it's a corner case but still ;-).

Yeah true.

But at least this PR is better (or what both OP and @famod expected) than what we currently have :)

**Review by mkouba — APPROVED** [review]

**Review by famod — APPROVED** [review]
I was only able to review this briefly but LGTM!

**Comment by gsmet** [comment]
Won't backport to 1.11 for now, we need some community baking for the PR.
