### PR TITLE
Run reactive rest client on Vertx same context 

### LINKED ISSUE #18977: Reactive REST Client breaks Hibernate Reactive Transactions
### Describe the bug

When combining the Reactive REST client with Hibernate Reactive, the Reactive REST client seems to break Context Propagation, leading to Hibernate Transactions not working as intended.

### Expected behavior

Using Reactive REST Client does not have any negative effects on Hibernate Reactive

### Actual behavior

Using Reactive REST Client will break Hibernate Reactive Transactions because a call to `sessionFactory.withSession()` within an existing transaction will result in a new session being created instead of re-using the previously existing session residing in context.

### How to Reproduce?

Reproducer: https://github.com/markusdlugi/hibernate-reactive-with-transaction (don't get confused by the naming)

1. Run the application
2. Open `http://localhost:8080/test`. It will fail with `java.lang.IllegalStateException: Couldn't find author 1`
3. Remove the REST call (`TestResource` line 48). If you repeat the test, it will now work, you get an author and some books.
4. Revert your change and add the REST call again. The test will fail again.
5. Remove the Hibernate Transaction by replacing `.withTransaction((session, tx)` in line 43 with `.withSession(session`. The test will now work again, even though the REST call is still in place.

It seems like after the REST call, the `session2` in the reproducer is not the same session as `session1` where the entity was initially persisted. This leads to the error. Seems like the Reactive REST client messes up the context propagation.

Not sure why the example works when getting rid of the transaction entirely, though.

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.18363.1556]

### Output of `java -version`

OpenJDK 64-Bit Server VM Corretto-11.0.10.9.1 (build 11.0.10+9-LTS, mixed mode)

### GraalVM version (if different from Java)

N/A

### Quarkus version or git rev

2.0.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3

### Additional information

Possibly related to #16949? But this one seems more severe because you cannot mix Hibernate Reactive Transactions and the REST client at all.

### PR DESCRIPTION
**Pull request by FroMage**
Fixes #18977

### CODE REVIEW

**Review by Sanne — APPROVED** [review]

**Comment by geoand** [comment]
LGTM, but I would like @stuartwdouglas to take a look as well because he had opened https://github.com/quarkusio/quarkus/pull/19144

**Comment by Sanne** [comment]
I'm not sure what Stuart was aiming to do, but I'm quite certain that we need the "run on context" that Stef introduced here.

I would suggest to merge this one first and then ask Stuart if he wants to either drop his PR or rebase it on top.

**Comment by geoand** [comment]
Yeah, I agree that this should be enough

**Comment by geoand** [comment]
@FroMage I assume that this should also fix https://github.com/quarkusio/quarkus/issues/16949, right?

**Comment by FroMage** [comment]
I thought so too, but I tried, and no: we get notified on the IO thread, so we will in turn notify on that same IO thread, which is different to the original worker thread.

I'm not sure if we should aim to do that, though. This feels like a broader discussion, because if Vert.x doesn't do thread affinity with worker threads, there's probably a good reason?

**Comment by geoand** [comment]
> I'm not sure if we should aim to do that, though. This feels like a broader discussion, because if Vert.x doesn't do thread affinity with worker threads, there's probably a good reason?

I wouldn't know TBH, but I guess :)

**Comment by gsmet** [comment]
Pretty sure the CI failures are related.

**Comment by stuartwdouglas** [comment]
So my PR basically makes sure that if we are dispatching back to the IO thread we pick the same IO thread that is tied to the connection, rather than a random IO thread. This mimics the server behavior. 

We have to be really careful with mutltiple threads being involved in reactive requests, there is a lot of potential for hard to debug races.

File: independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/impl/RestClientRequestContext.java [hunk 1]
```diff
@@ -202,7 +203,14 @@ public HttpClientResponse getVertxClientResponse() {
     @Override
     protected Executor getEventLoop() {
         if (httpClientRequest == null) {
-            return restClient.getVertx().nettyEventLoopGroup().next();
+            // make sure we execute the client callbacks on the same context as the current thread
```
Comment (stuartwdouglas) [inline independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/impl/RestClientRequestContext.java:206]: This is not right, if this is being called from a worker then it will dispatch on the worker. You still need to actually dispatch to the relevant IO thread.

**Review by stuartwdouglas — CHANGES_REQUESTED** [review]

File: independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/impl/RestClientRequestContext.java (hunk 1 above)
Comment (FroMage) [reply independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/impl/RestClientRequestContext.java:206]: How can this be called from a worker thread, though? I've always seen it called from an IO thread.

Comment (stuartwdouglas) [reply independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/impl/RestClientRequestContext.java:206]: It could be called by the user in org.jboss.resteasy.reactive.client.spi.ResteasyReactiveClientRequestContext from a org.jboss.resteasy.reactive.client.spi.ResteasyReactiveClientRequestFilter, which could be called from pretty much anywhere. 

TBH I am really worried about this 'swapping threads' approach. It opens the door to lots of subtle bugs as we now need to ensure that we always do some kind of safe hand off between the threads. We also need to be super careful with IO, as things work differently if you are not on your IO thread, because as soon as you resume IO its possible another IO thread has started running the input handler, so you need to thing about the thread safety semantics of that.

From a performance point of view it also sucks, as it will involve multiple IO threads waking up selectors that don't belong to them, which is terrible from a performance POV.

Comment (Sanne) [reply independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/impl/RestClientRequestContext.java:206]: I agree with the concerns, there's many similar difficulties with Hibernate Reactive.

As a user, I think I'd be fine to have to deal with stronger restrictions in exchange for less [potential] trouble.

Comment (stuartwdouglas) [reply independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/impl/RestClientRequestContext.java:206]: Maybe we should just merge this for now (once the tests are passing), but look to the possibility of moving to a single thread model in future.

Thinking about it I am not sure how practical it will be, as having basically a pool of connections per IO thread is not going to be great for databases which have connection limits.

Comment (stuartwdouglas) [reply independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/impl/RestClientRequestContext.java:223]: I think we should merge it for now, as I said above. I have rebased so lets see what CI says.

**Comment by FroMage** [comment]
Force-rebased, fixed the three tests. The kafka one on JDK16 I hope is unrelated. Let's see what CI says.

**Comment by FroMage** [comment]
I can confirm this fixes the issue I have in my cheese shop demo, where each REST client has its own IO thread, and I'm not sure what vert.x context they share.

**Comment by FroMage** [comment]
All checks passed, so it's up to @stuartwdouglas to reassess his review :)

**Review by stuartwdouglas — APPROVED** [review]

**Comment by ambition-consulting** [comment]
Hi, when will this be released? We want to go to production next week and would really like to have our ELK working by then.

**Comment by geoand** [comment]
@FroMage @stuartwdouglas I am kinda hesitant to backport this, but if you think we should then I will.

**Comment by stuartwdouglas** [comment]
I think we should, it's pretty broken ATM.

**Comment by geoand** [comment]
Okay

**Comment by ambition-consulting** [comment]
Thank you - greatly appreciated. :)

**Comment by geoand** [comment]
So likely to be included in `2.2.4.Final` which hopefully will be out next week sometime

**Comment by ambition-consulting** [comment]
I built the 2.2.3.Final with the changes from this PR, retested, and successfully verified that it should fix the problem.
