### PR TITLE
Warn about unknown application config files

### LINKED ISSUE #13227: warn or fail if an application.yaml is provided without the quarkus-config-yaml dependency
**Description**
If configuration is provided through a yaml file, but the quarkus-config-yaml has not been added, the configuration module will silently ignore the yaml file. it may take some time for the user to figure out that is what is happening, incorrectly thinking there is a bug in quarkus or smallrye config.
The proposition is to fail quarkus startup, or at least WARN the user that no properties file has been found, and a yaml file has been found,but will be ignored.

see also this [discussion](https://groups.google.com/g/quarkus-dev/c/7p4r3U8cemI/m/08uTTReOCgAJ) in the forum.

### PR DESCRIPTION
**Pull request by radcortez**
- Fixes #13227

### CODE REVIEW

File: core/deployment/src/main/java/io/quarkus/deployment/steps/ConfigGenerationBuildStep.java [hunk 1]
```diff
@@ -435,6 +432,34 @@ public void watchConfigFiles(BuildProducer<HotDeploymentWatchedFileBuildItem> wa
...
+        buildTimeFiles.addAll(ConfigDiagnostic.configFilesFromLocations());
+
+        // Report always at build time since config folder and locations may differ from build to runtime
+        ConfigDiagnostic.unknownConfigFiles(buildTimeFiles);
+
+        // TODO - Remove reflective registration after https://github.com/quarkusio/quarkus/pull/35247
+        reflectiveClass.produce(ReflectiveClassBuildItem.builder(URI.class).constructors(true).build());
+        // No need to include the application files, because they don't change
+        if (!launchModeBuildItem.getLaunchMode().isDevOrTest()) {
+            configRecorder.unknownConfigFiles();
```
Comment (gsmet) [inline core/deployment/src/main/java/io/quarkus/deployment/steps/ConfigGenerationBuildStep.java:459]: So you want to log it once at build time and one at runtime, right?

File: core/deployment/src/main/java/io/quarkus/deployment/steps/ConfigGenerationBuildStep.java [hunk 2]
```diff
@@ -435,6 +432,34 @@ public void watchConfigFiles(BuildProducer<HotDeploymentWatchedFileBuildItem> wa
...
+
+        Set<String> buildTimeFiles = new HashSet<>();
+        buildTimeFiles.addAll(ConfigDiagnostic.configFiles(rootDirectories.getSinglePath()));
+        buildTimeFiles.addAll(ConfigDiagnostic.configFilesFromLocations());
+
+        // Report always at build time since config folder and locations may differ from build to runtime
+        ConfigDiagnostic.unknownConfigFiles(buildTimeFiles);
+
+        // TODO - Remove reflective registration after https://github.com/quarkusio/quarkus/pull/35247
+        reflectiveClass.produce(ReflectiveClassBuildItem.builder(URI.class).constructors(true).build());
```
Comment (gsmet) [inline core/deployment/src/main/java/io/quarkus/deployment/steps/ConfigGenerationBuildStep.java:456]: I merged this PR, so you can remove this right? Don't forget to drop the `BuildProducer` too.

**Review by gsmet — CHANGES_REQUESTED** [review]

File: core/deployment/src/main/java/io/quarkus/deployment/steps/ConfigGenerationBuildStep.java (hunk 2 above)
Comment (radcortez) [reply core/deployment/src/main/java/io/quarkus/deployment/steps/ConfigGenerationBuildStep.java]: Yes. Thanks. Removed!

File: core/deployment/src/main/java/io/quarkus/deployment/steps/ConfigGenerationBuildStep.java (hunk 1 above)
Comment (radcortez) [reply core/deployment/src/main/java/io/quarkus/deployment/steps/ConfigGenerationBuildStep.java:462]: Yes, because this also looks into the `config` folder and `quarkus.config.locations`, which may be different from build to runtime, so we need to perform the checks twice.

**Review by gsmet — APPROVED** [review]
