### PR TITLE
Make Kubernetes model for native registration more complete

### LINKED ISSUE #27469: Graal Native Build missing ReflectionRegistrations in io.fabric8:kubernetes-model-core:5.12.3
### Describe the bug

Hi

The fix should be fast. I get following exception when running my native app do to missing ReflectionRegistrations:
Caused by: java.lang.NoSuchMethodException: io.fabric8.kubernetes.api.model.PersistentVolumeClaimBuilder.<init>(io.fabric8.kubernetes.api.model.PersistentVolumeClaim)
        at java.lang.Class.getConstructor0(DynamicHub.java:3585)
        at java.lang.Class.getDeclaredConstructor(DynamicHub.java:2754)
        at io.fabric8.kubernetes.client.ResourceHandlerImpl.edit(ResourceHandlerImpl.java:62)
        ... 38 more

I solved it by adding this class to my code:

import io.fabric8.kubernetes.api.model.ConfigMapBuilder;
import io.fabric8.kubernetes.api.model.PersistentVolumeClaimBuilder;
import io.quarkus.runtime.annotations.RegisterForReflection;

/**
 * Temporary registration of external classes which should be fixed by the library in the future.
 * This patch is neede for quarkus native build
 * TODO remove as soon Openshif-Client library patched this bug
 */
@RegisterForReflection(targets = {PersistentVolumeClaimBuilder.class, ConfigMapBuilder.class})
public class RegisterReflections {

}

But it should be fixed in the library.

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #27469

BTW, this PR increases the native binary size a little (3MB on the integration test we have)

### CODE REVIEW

**Comment by geoand** [comment]
cc @manusa

**Review by manusa — APPROVED** [review]
:heart: LGTM

**Comment by manusa** [comment]
The Fluent classes are not covered by these changes. They are part of the XXXBuilder chain, so I assume they'll be automatically gathered just by registering the builder.

**Comment by geoand** [comment]
That should be the case, yeah

File: extensions/jackson/deployment/src/main/java/io/quarkus/jackson/deployment/IgnoreJsonDeserializeClassBuildItem.java [hunk 1]
```diff
@@ -10,13 +12,22 @@
...
     public IgnoreJsonDeserializeClassBuildItem(DotName dotName) {
-        this.dotName = dotName;
+        this.dotNames = List.of(dotName);
+    }
+
+    public IgnoreJsonDeserializeClassBuildItem(List<DotName> dotNames) {
+        this.dotNames = dotNames;
     }
 
+    @Deprecated
```
Comment (gastaldi) [inline extensions/jackson/deployment/src/main/java/io/quarkus/jackson/deployment/IgnoreJsonDeserializeClassBuildItem.java:25]: Maybe add a javadoc why this is deprecated? Also perhaps mark for removal.
```suggestion
    @Deprecated(forRemoval= true)
```

**Review by gastaldi — APPROVED** [review]
LGTM, added a minor observation about the deprecated method

File: extensions/jackson/deployment/src/main/java/io/quarkus/jackson/deployment/IgnoreJsonDeserializeClassBuildItem.java [hunk 2]
```diff
@@ -10,13 +12,22 @@
...
+    }
+
+    public IgnoreJsonDeserializeClassBuildItem(List<DotName> dotNames) {
+        this.dotNames = dotNames;
     }
 
+    @Deprecated(forRemoval = true)
     public DotName getDotName() {
-        return dotName;
+        return dotNames.get(0);
```
Comment (gastaldi) [inline extensions/jackson/deployment/src/main/java/io/quarkus/jackson/deployment/IgnoreJsonDeserializeClassBuildItem.java:27]: Just occurred to me that this may throw an exception if the list is empty

Comment (geoand) [reply extensions/jackson/deployment/src/main/java/io/quarkus/jackson/deployment/IgnoreJsonDeserializeClassBuildItem.java:27]: It shouldn't happen, but yeah, let's guard against it
