### PR TITLE
Expand types which are considered text in multipart handling

### LINKED ISSUE #38802: Multipart form data is interpreted as a file although it's not a file
### Describe the bug

If multipart form data is not a file and specified with other MIME-Type than `text/plain`, quarkus tries to parse form data as a file, which leads to a NullPointerException.

Was introduced in quarkus 3.7.3 with this change: https://github.com/quarkusio/quarkus/pull/38714

### Expected behavior

Multipart form data is parsed with correct content type.

### Actual behavior

Multipart form data other than `text/plain` is parsed as File.

Request:

```
Hypertext Transfer Protocol
MIME Multipart Media Encapsulation, Type: multipart/form-data, Boundary: "5vI261AD6aFM_WL55jbNMpcLal_Lzt2uTnRW"
    [Type: multipart/form-data]
    First boundary: --5vI261AD6aFM_WL55jbNMpcLal_Lzt2uTnRW\r\n
    Encapsulated multipart part:  (application/json)
        Content-Disposition: form-data; name="firstParam"\r\n
        Content-Type: application/json; charset=US-ASCII\r\n
        Content-Transfer-Encoding: 8bit\r\n\r\n
        JavaScript Object Notation: application/json
    Last boundary: \r\n--5vI261AD6aFM_WL55jbNMpcLal_Lzt2uTnRW--\r\n
```

Exception:

```
2024-02-15 15:58:14,745 DEBUG [WebApplicationException] (executor-thread-1) Restarting handler chain for exception exception: jakarta.ws.rs.WebApplicationException: HTTP 400 Bad Request
	at org.jboss.resteasy.reactive.server.handlers.ParameterHandler.handle(ParameterHandler.java:66)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:137)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
	at java.base/java.nio.file.Files.readString(Files.java:3343)
	at org.jboss.resteasy.reactive.server.core.multipart.MultipartSupport.getString(MultipartSupport.java:204)
	at org.jboss.resteasy.reactive.server.core.parameters.MultipartFormParamExtractor.extractParameter(MultipartFormParamExtractor.java:46)
	at org.jboss.resteasy.reactive.server.handlers.ParameterHandler.handle(ParameterHandler.java:45)
	... 9 more
```

### How to Reproduce?

I've made a reproducer: https://github.com/chutzemischt/quarkus-multipart-reproducer

```java
@Path("/api")
public class MyTestController {

    @Path("test")
    @POST
    public Response testMultipart(@FormParam("firstParam") final String firstParam, @FormParam("secondParam") final String secondParam) {
        return Response.ok().build();
    }
}
```

```java
@QuarkusTest
class MyTestControllerTest {

    @Test
    void testMultipart() {
        given().multiPart("firstParam", "{\"id\":\"myId\",\"name\":\"myName\"}", "application/json")
                .when()
                .post("/api/test")
                .then()
                .statusCode(200);
    }
}
```

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

21.0.1

### Quarkus version or git rev

3.7.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.5

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
- Fixes: #38802

P.S. I'm not really happy with this, but I am not sure what a proper solution would be...

### CODE REVIEW

File: independent-projects/resteasy-reactive/common/runtime/src/main/java/org/jboss/resteasy/reactive/common/util/MediaTypeHelper.java [hunk 1]
```diff
@@ -267,10 +267,12 @@ public static boolean equivalentParams(MediaType m1, MediaType m2) {
...
 
+    // TODO: does this need to be more complex?
     public static boolean isTextLike(MediaType mediaType) {
-        return "text".equalsIgnoreCase(mediaType.getType())
-                || ("application".equalsIgnoreCase(mediaType.getType())
-                        && mediaType.getSubtype().toLowerCase().startsWith("xml"));
+        String type = mediaType.getType();
+        String subtype = mediaType.getSubtype();
+        return (type.equals("application") && (subtype.contains("json") || subtype.contains("xml") || subtype.contains("yaml")))
+                || type.equals("text");
```
Comment (FroMage) [inline independent-projects/resteasy-reactive/common/runtime/src/main/java/org/jboss/resteasy/reactive/common/util/MediaTypeHelper.java:275]: Heh, I wonder if there's any more formal definition of what can be turned into a text.

Also, I wonder how this all compares to "toplevel" body parsing.

In _theory_, multipart members and body entities should now have the same parsing mechanism, in that they each have an encoding, content type, and go via `MessageBodyReader` for deserialisation, which is what allows us to have not just primitive types but also JSON/XML deserialisation.

This logic appears to sit _before_ we look up the right `MessageBodyReader` for the deserialisation. I wonder why we have this. Perhaps everything _at this point_ should be read as `byte[]` (well, and associated with their content-type), and then later when we figure out whether to deserialise this into a `String` or `JsonObject` or `Person` entity, we use the same binary data?

Here we're accepting "deserialising" XML/JSON/YAML into `String` which means: no deserialisation, just give them "raw" (still respecting the encoding). For a mime part. Do we accept the same for a toplevel http request body? I think we do. But I wonder if we also limit it there for XML/JSON/YAML or if we have another sort of check of text-like, or… "String-convertible".

**Review by FroMage — APPROVED** [review]
Look OK, but I've added a question relating all this to the bigger picture. To investigate now, or think about for next time another mime type breaks this logic.

File: independent-projects/resteasy-reactive/common/runtime/src/main/java/org/jboss/resteasy/reactive/common/util/MediaTypeHelper.java (hunk 1 above)
Comment (geoand) [reply independent-projects/resteasy-reactive/common/runtime/src/main/java/org/jboss/resteasy/reactive/common/util/MediaTypeHelper.java:275]: The whole thing is weird and this is only needed to try to decide what type of part of this is (see calls to `FormData#add`).
I really don't like what we are doing, but I don't have any ideas to make it better.
