### PR TITLE
Send Authorization header from Swagger UI for methods secured with `@AuthorizationPolicy` and reflect policies in OpenAPI document

### LINKED ISSUE #51607: Swagger UI does not send Authorization header when using @AuthorizationPolicy on REST resource class instead of @Authenticated
### Describe the bug

I've annotated my REST resource classes with @AuthorizationPolicy.

Example:
```
@Path(/my-resource)
@AuthorizationPolicy(name = DefaultHttpSecurityPolicy.NAME)
public class MyResource {
    ...
}
```

I've also enabled Basic Authentication (but I have the same problem with OIDC token authentication) : 
`quarkus.http.auth.basic=true`

The problem is that once authenticated, the Swagger UI does not send the 'Authorization' header on requests.

It seems indeed the OpenAPI `security `attribute is only added on methods if I annotate my resource classes with `@Authenticated.`

But Quarkus does not allow to use both the `@Authenticated` and the `@AuthorizationPolicy` annotations : 

```
Class 'MyResource' is annotated with 'io.quarkus.vertx.http.security.AuthorizationPolicy' and 'io.quarkus.security.Authenticated' security annotations,
however security annotations cannot be combined.
```

So it is just impossible to have a working SwaggerUI when using @AuthorizationPolicy annotation

### Expected behavior

Using @AuthorizationPolicy on a resource class, should automatically mark its methods as secured in OpenAPI schema so that authentication through SwaggerUI can work.

### Actual behavior

Using @AuthorizationPolicy on a resource class, does not automatically mark its methods as secured in OpenAPI schema

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

3.27.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by michalvavrik**
* fixes https://github.com/quarkusio/quarkus/issues/51607

### CODE REVIEW

**Comment by michalvavrik** [comment]
Hello @MikeEdgar , I cannot add you as a reviewer, but @phillip-kruger is out of the office and I think you know this extension very well. Could you review? Thank you

File: extensions/smallrye-openapi/deployment/src/main/java/io/quarkus/smallrye/openapi/deployment/SmallRyeOpenApiProcessor.java [hunk 1]
```diff
@@ -1,5 +1,7 @@
 package io.quarkus.smallrye.openapi.deployment;
 
+import static io.quarkus.security.spi.SecurityTransformerBuildItem.createSecurityTransformer;
+
```
Comment (MikeEdgar) [inline extensions/smallrye-openapi/deployment/src/main/java/io/quarkus/smallrye/openapi/deployment/SmallRyeOpenApiProcessor.java]: Is this static import needed? It looks like the method is called with `SecurityTransformerBuildItem` on 1262.

**Review by MikeEdgar — APPROVED** [review]
Looks good, thanks. If I understand correctly, the `SecurityTransformer` has a way to lookup security annotations (including build-time generated ones) in the same way we use the index, correct?

File: extensions/smallrye-openapi/deployment/src/main/java/io/quarkus/smallrye/openapi/deployment/SmallRyeOpenApiProcessor.java (hunk 1 above)
Comment (michalvavrik) [reply extensions/smallrye-openapi/deployment/src/main/java/io/quarkus/smallrye/openapi/deployment/SmallRyeOpenApiProcessor.java]: Good catch, it isn't needed and build didn't remove it as unused export. It is not bullet proof. I'll remove it manually. Thanks.

**Comment by michalvavrik** [comment]
> Looks good, thanks. If I understand correctly, the `SecurityTransformer` has a way to lookup security annotations (including build-time generated ones) in the same way we use the index, correct?

Yes. It can find "more" in certain situations, but it should never find less. I can go into details, but in short - ATM it should be neutral change.

**Comment by michalvavrik** [comment]
> > Looks good, thanks. If I understand correctly, the `SecurityTransformer` has a way to lookup security annotations (including build-time generated ones) in the same way we use the index, correct?
> 
> Yes. It can find "more" in certain situations, but it should never find less. I can go into details, but in short - ATM it should be neutral change.

That reminds me @MikeEdgar , the way you currently detect `@PermissionsAllowed` will not work for repeated annotations (if it is placed on endpoints multiple times). You need to use something like `getAnnotationsWithRepeatable`. I can fix it separately if you want, but please feel free to do it yourself.

**Comment by MikeEdgar** [comment]
> That reminds me @MikeEdgar , the way you currently detect `@PermissionsAllowed` will not work for repeated annotations (if it is placed on endpoints multiple times). You need to use something like `getAnnotationsWithRepeatable`. I can fix it separately if you want, but please feel free to do it yourself.

Ack. I didn't realize that was repeatable :blush: . I should have some time in the next few weeks on "vacation" to fix that.

**Comment by michalvavrik** [comment]
> Ack. I didn't realize that was repeatable 😊 . I should have some time in the next few weeks on "vacation" to fix that.

Sounds good. Thanks.

**Review by sberyozkin — APPROVED** [review]

**Comment by sberyozkin** [comment]
Sorry, I actually missed there were comments from @MikeEdgar, but looks like Mike is also OK, see him approving too, thanks @michalvavrik
