### PR TITLE
Register kotlin reflection information for native image builds

### LINKED ISSUE #8479: Kotlin reflection fails in native build in some cases that Java reflection success
Kotlin method references (e.g. `this::someMethod`) have a s nice shorthand for retrieving the reflection `java.lang.reflect.Method` via the `javaMethod` property as in `this::someMethod.javaMethod`.

When using a JAX-RS `UriInfo` to build location headers, using the reflected method reference is a great way to keep things DRY so as not to repeat path information stated in a `@Path` annotation.

For example:
```kotlin
    @POST
    fun create(@Context uriInfo: UriInfo) =
    	Response
    		.created(
    			uriInfo.requestUriBuilder
    				.path(this::fetch.javaMethod) // Fetches path from the @Path annotation of the "fetch" method
    				.buildFromMap(mapOf(
    					"id" to "12345"
    				))
    		)
    		.entity(mapOf("id" to "12345", "name" to "test"))
    		.build()


    @GET
    @Path("{id}")
    fun fetch(@PathParam("id") id: String) =
    	Response
    		.ok()
    		.entity(mapOf("id" to "12345", "name" to "test"))
    		.build()
```

Using Kotlin references is a _great_ shorthand and keeps things type safe and compile type checked as compared to using Java...

In Kotlin
```kotlin
path(this::fetch.javaMethod)
```
In Java
```java
path(GreetingResource::class.java.getDeclaredMethod("fetch", String::class.java))
```

As usual, all is well in JVM mode (and both examples work correctly) but in native mode the Kotlin version throws an error deep in the bowels of its reflection library.

**Expected behavior**

Kotlin's reflection tools work the same as equivalent Java reflection in both JVM and native builds.

**Actual behavior**

In native builds Kotlin reflection for method references fails.

**To Reproduce**

[rest-kotlin-quickstart.zip](https://github.com/quarkusio/quarkus/files/4452112/rest-kotlin-quickstart.zip)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:

        Darwin #### 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64`

 - Output of `java -version`: 

        openjdk version "14" 2020-03-17
        OpenJDK Runtime Environment (build 14+36-1461)
        OpenJDK 64-Bit Server VM (build 14+36-1461, mixed mode, sharing)

 - Quarkus version or git rev: 

        1.3.2

 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 

        Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
        Default locale: en_US, platform encoding: UTF-8
        OS name: "mac os x", version: "10.15.4", arch: "x86_64", family: "Mac"

### PR DESCRIPTION
**Pull request by evanchooly**
fixes #8479

### CODE REVIEW

File: extensions/kotlin/deployment/src/main/java/io/quarkus/kotlin/deployment/KotlinProcessor.java [hunk 1]
```diff
@@ -30,12 +50,41 @@ void registerKotlinJacksonModule(BuildProducer<ClassPathJacksonModuleBuildItem>
...
-    /**
-     * Kotlin data classes that have multiple constructors need to have their final fields writable,
-     * otherwise creating a instance of them with default values, fails in native mode
+    /*
+     * Register the Kotlin reflection types if they are present.
      */
     @BuildStep
-    ReflectiveClassFinalFieldsWritablePredicateBuildItem dataClassPredicate() {
-        return new ReflectiveClassFinalFieldsWritablePredicateBuildItem(new IsDataClassWithDefaultValuesPredicate());
+    void registerKotlinReflection(final BuildProducer<ReflectiveClassBuildItem> reflectiveClass,
```
Comment (geoand) [inline extensions/kotlin/deployment/src/main/java/io/quarkus/kotlin/deployment/KotlinProcessor.java:57]: Why go to all this trouble when you can just create build items with the values present in the files?

There is no benefit to reading the file from the classpath  and loading Jackson to do so... It's actually quite slow...

**Review by geoand — DISMISSED** [review]

File: extensions/kotlin/deployment/src/main/java/io/quarkus/kotlin/deployment/KotlinProcessor.java (hunk 1 above)
Comment (evanchooly) [reply extensions/kotlin/deployment/src/main/java/io/quarkus/kotlin/deployment/KotlinProcessor.java:57]: yeah, i could I suppose.  I was thinking drop in replacements of those files as they evolve.  But i suppose either way is editing a text file of one sort of another.  Speed, however, not much of an issue here.  ;)

**Review by geoand — COMMENTED** [review]
Any chance we can update the Kotlin integration test to incorporate the case this addresses?

**Comment by evanchooly** [comment]
I can tweak what's there, I think.  I'll take a look.  i was using the reproducer to test it.  it's pretty basic but at least failed without this patch.  I'm afraid any test will forever have holes of unknown size due to the nature of reflection but something is better than nothing I suppose.

**Comment by geoand** [comment]
Yeah, we can't capture everything, but we can at least cover cases we know about

**Comment by gsmet** [comment]
CI is not happy about this one.

**Comment by evanchooly** [comment]
That's odd.  it's complaining about missing JAXB classes.

File: integration-tests/pom.xml [hunk 2]
```diff
@@ -243,6 +243,7 @@
                 <module>maven</module>
                 <module>scala</module>
                 <module>kotlin</module>
+                <module>kotlin-reflection-native</module>
                 <module>kotlin-serialization</module>
```
Comment (geoand) [inline integration-tests/pom.xml:247]: Does it need to be a new module?

Asking because each module adds time to CI because it needs to be built in native.

If it can't, be added to an existing module, we'll need to have this configured in the JSON file used by CI for native tests

**Review by geoand — CHANGES_REQUESTED** [review]

File: integration-tests/pom.xml (hunk 2 above)
Comment (evanchooly) [reply integration-tests/pom.xml:247]: originally i had it as just another set of tests in the kotlin integration test but the other tests are all bound to the `integration-test` and `verify` phases.  No matter what I tried, the native tests ran all the time.  So I finally moved them out to their own tests so I could have full control over the phases involved.  But you're right about the native test config.  I'll update that file.

Comment (geoand) [reply integration-tests/pom.xml:247]: I'll have a look tomorrow, because we really like to avoid adding new modules

Comment (evanchooly) [reply integration-tests/pom.xml:247]: agreed.  i'd love to know what i was missing but i banged away at for a while before finally giving up.  It could be that the tests don't actually need to be bound explicitly to the phases they are but it might be something in how maven tests are run against itself that dictate that.

Comment (geoand) [reply integration-tests/pom.xml:247]: I would just add these new tests to the `quarkus-integration-test-resteasy-reactive-kotlin-standard` module.

**Comment by gsmet** [comment]
This needs a rebase (and a squash!).

**Comment by evanchooly** [comment]
it'll get one.  i'm just trying to validate that test.  i can't get it to run locally (always says tests are skipped) so I'm seeing what CI does with it.  (There's also an intentional test failure condition.)

**Comment by geoand** [comment]
The CI failure is relevant

**Comment by evanchooly** [comment]
yeah.  i'm working on it.  juggling a few things so it's slower going than i'd like.

**Review by geoand — APPROVED** [review]
