### PR TITLE
QUARKUS_INIT_AND_EXIT is now properly handled

### LINKED ISSUE #34643: QUARKUS_INIT_AND_EXIT is currently ignored.
### Describe the bug

As title says `QUARKUS_INIT_AND_EXIT` is not respected.

### Expected behavior

When `QUARKUS_INIT_AND_EXIT` is set to true the Quarkus application should exit before starting (binding http port).

### Actual behavior

The application never exits.

### How to Reproduce?

Run the a quarkus application using:
```sh
QUARKUS_INIT_AND_EXIT=true java -jar target/quarkus-app/quarkus-run.jar
```

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by iocanel**
Resolves: #34643

### CODE REVIEW

**Comment by iocanel** [comment]
@cescoffier: I recall you mentioned having issues with it. Since #32728 does not seem to likely to be merged any time soon. I creating a PR with just the fix you need.

File: core/runtime/src/main/java/io/quarkus/runtime/init/InitializationTaskRecorder.java [hunk 1]
```diff
@@ -18,13 +20,17 @@
...
+    }
 
     public void exitIfNeeded() {
         //The tcks CustomConverTest is broken: It always returns true for boolean values.
         //To workaround this issue, we need to check if `init-and-exit` is explicitly defined.
-        boolean initAndExitConfigured = StreamSupport.stream(ConfigProvider.getConfig().getPropertyNames().spliterator(), false)
-                .anyMatch(n -> QUARKUS_INIT_AND_EXIT.equals(n));
-        if (initAndExitConfigured) {
+        boolean initAndExitConfigured = propertyConfigured(QUARKUS_INIT_AND_EXIT);
+        if (initAndExitConfigured && config.getValue().initAndExit) {
```
Comment (geoand) [inline core/runtime/src/main/java/io/quarkus/runtime/init/InitializationTaskRecorder.java:33]: Can't we just use the config object? Why do we need to do both checks?

Comment (geoand) [reply core/runtime/src/main/java/io/quarkus/runtime/init/InitializationTaskRecorder.java:33]: Ah okay, thanks

**Review by geoand — APPROVED** [review]
