### PR TITLE
Fix missing Jaeger client version in native mode

### LINKED ISSUE #10399: Field jaeger.version is empty when using quarkus-jaeger
**Describe the bug**
(Describe the problem clearly and concisely.)

The field `jaeger.version` is empty.

**Expected behavior**

The field should contain the version of the Jaeger tracing library.

**Actual behavior**

The field value is empty.

**To Reproduce**
1. Using qauarkus-jaeger
2. 
3. 

**Screenshots**

image

**Environment (please complete the following information):**

~~~
$ uname -a
Linux brocken 5.6.19-300.fc32.x86_64 #1 SMP Wed Jun 17 16:10:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
$ java -version
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment 18.9 (build 11.0.7+10)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.7+10, mixed mode, sharing)
~~~

 - GraalVM version (if different from Java): 19.3.1
 - Quarkus version or git rev: 1.5.2.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 

    ~~~
    Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
    Maven home: /home/jreimann/tools/maven/apache-maven-current
    Java version: 11.0.7, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-11-openjdk-11.0.7.10-1.fc32.x86_64
    Default locale: en_US, platform encoding: UTF-8
    OS name: "linux", version: "5.6.19-300.fc32.x86_64", arch: "amd64", family: "unix"
    ~~~

**Additional context**
(Add any other context about the problem here.)

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #10399

### CODE REVIEW

**Comment by geoand** [comment]
cc @pavolloffay

**Comment by pavolloffay** [comment]
re the title - it's not OpenTracing version but it's Jaeger client version. These versions are different.

File: integration-tests/main/src/main/java/io/quarkus/it/opentracing/OpenTracingResource.java [hunk 1]
```diff
@@ -14,4 +18,11 @@ public String getTest() {
         return "TEST";
     }
 
+    @GET
+    @Path("/version")
```
Comment (pavolloffay) [inline integration-tests/main/src/main/java/io/quarkus/it/opentracing/OpenTracingResource.java:22]: `/jaegerversion` would be better since it's the Jaeger client version and not OpenTracing version

File: integration-tests/main/src/test/java/io/quarkus/it/main/OpenTracingTestCase.java [hunk 2]
```diff
@@ -20,4 +22,10 @@ public void invokeResource() {
                 .body(is("TEST"));
     }
 
+    @Test
+    public void testVersion() {
+        RestAssured.when().get("/opentracing/version").then()
+                .body(is(not(emptyString())));
```
Comment (pavolloffay) [inline integration-tests/main/src/test/java/io/quarkus/it/main/OpenTracingTestCase.java:28]: Is this executed also in the native mode? 

Wouldn't it be better to assert on the exact string or use https://github.com/jaegertracing/jaeger-client-java/blob/master/jaeger-client/src/main/java/io/jaegertracing/client/Version.java#L29?

Comment (geoand) [reply integration-tests/main/src/test/java/io/quarkus/it/main/OpenTracingTestCase.java:28]: Sure yeah, I do that

**Comment by gsmet** [comment]
I amended the commit message per Pavol's comment. Let's merge!

**Comment by geoand** [comment]
Great thanks!
