### PR TITLE
Ability to exclude particular data sources from the health check

### LINKED ISSUE #13326: Health check configurable for each datasource
**Description**
I have multiple datasources, one of which is only used by a job at the beginning of the day. That datasource is failing sometimes and it causes the whole application to be seen as DOWN in the health check.

I'd need to configure for that specific datasource that I want the health check disabled, while still having the check enabled for my main datasource.

Any possibility to have the health check config datasource-specific?

### PR DESCRIPTION
**Pull request by jmartisk**
fixes https://github.com/quarkusio/quarkus/issues/13326
@xstefank

### CODE REVIEW

File: extensions/datasource/runtime/src/main/java/io/quarkus/datasource/runtime/DataSourceBuildTimeConfig.java [hunk 1]
```diff
@@ -16,4 +16,12 @@
     @ConvertWith(DatabaseKindConverter.class)
     public Optional<String> dbKind = Optional.empty();
 
+    /**
+     * Whether this particular data source should be excluded from the health check if
+     * the general health check for data sources is enabled. By default, the health check includes
+     * all configured data sources (if it is enabled).
+     */
+    @ConfigItem(name = "health-check-exclude", defaultValue = "false")
```
Comment (gsmet) [inline extensions/datasource/runtime/src/main/java/io/quarkus/datasource/runtime/DataSourceBuildTimeConfig.java:24]: You don't need the name, it will be the one generated.

**Review by gsmet — COMMENTED** [review]
Just a small comment.

Also I would rather have us use the config infrastructure properly rather than using strings to get the config values.

I will rework my Jackson PR today, it should give you an example of how to do it.

**Comment by jmartisk** [comment]
I pushed a new version @gsmet please look if this what you meant
It complicated things a bit more than I expected though.

File: extensions/agroal/runtime/src/main/java/io/quarkus/agroal/runtime/AgroalRecorder.java [hunk 2]
```diff
@@ -29,4 +35,24 @@ public AgroalDataSource get() {
...
     }
 
+    public Supplier<DataSourcesExcludedFromHealthChecks> dataSourcesExcludedFromHealthChecks(
+            DataSourcesBuildTimeConfig dataSourcesBuildTimeConfig) {
+        return new Supplier<DataSourcesExcludedFromHealthChecks>() {
+            @Override
+            public DataSourcesExcludedFromHealthChecks get() {
+                List<String> excludedNames = new ArrayList<>();
+                if (dataSourcesBuildTimeConfig.defaultDataSource.healthCheckExclude) {
+                    excludedNames.add(null);
```
Comment (machi1990) [inline extensions/agroal/runtime/src/main/java/io/quarkus/agroal/runtime/AgroalRecorder.java:45]: Can we use a proper https://github.com/quarkusio/quarkus/blob/e963fe4f4887cdeaf0bdee3ae9f4040be0736a8b/extensions/datasource/common/src/main/java/io/quarkus/datasource/common/runtime/DataSourceUtil.java#L7 instead of `null`?

File: extensions/agroal/runtime/src/main/java/io/quarkus/agroal/runtime/health/DataSourceHealthCheck.java [hunk 3]
```diff
@@ -27,14 +29,21 @@
...
         Set<Bean<?>> beans = Arc.container().beanManager().getBeans(DataSource.class);
+        DataSourcesExcludedFromHealthChecks excluded = Arc.container().instance(DataSourcesExcludedFromHealthChecks.class)
+                .get();
+        List<String> excludedNames = excluded.getExcludedNames();
         for (Bean<?> bean : beans) {
             if (bean.getName() == null) {
-                // this is the default DataSource: retrieve it by type
-                DataSource defaultDs = Arc.container().instance(DataSource.class).get();
-                dataSources.put(DEFAULT_DS, defaultDs);
+                if (!excludedNames.contains(null)) {
```
Comment (machi1990) [inline extensions/agroal/runtime/src/main/java/io/quarkus/agroal/runtime/health/DataSourceHealthCheck.java:37]: Let's replace the null usage by something like https://github.com/quarkusio/quarkus/blob/e963fe4f4887cdeaf0bdee3ae9f4040be0736a8b/extensions/datasource/common/src/main/java/io/quarkus/datasource/common/runtime/DataSourceUtil.java#L7

File: extensions/datasource/runtime/src/main/java/io/quarkus/datasource/runtime/DataSourceBuildTimeConfig.java [hunk 4]
```diff
@@ -16,4 +16,12 @@
     @ConvertWith(DatabaseKindConverter.class)
     public Optional<String> dbKind = Optional.empty();
 
+    /**
+     * Whether this particular data source should be excluded from the health check if
+     * the general health check for data sources is enabled. By default, the health check includes
+     * all configured data sources (if it is enabled).
+     */
```
Comment (machi1990) [inline extensions/datasource/runtime/src/main/java/io/quarkus/datasource/runtime/DataSourceBuildTimeConfig.java:23]:
```suggestion
    /**
     * Whether this particular data source should be excluded from the health check if
     * the general health check for data sources is enabled. 
     * <p>
     * By default, the health check includes all configured data sources (if it is enabled).
     */
```

Introduce `<p>` to render out nicely the generated doc.

**Review by machi1990 — DISMISSED** [review]

File: extensions/agroal/runtime/src/main/java/io/quarkus/agroal/runtime/AgroalRecorder.java (hunk 2 above)
Comment (jmartisk) [reply extensions/agroal/runtime/src/main/java/io/quarkus/agroal/runtime/AgroalRecorder.java]: done

File: extensions/agroal/runtime/src/main/java/io/quarkus/agroal/runtime/health/DataSourceHealthCheck.java (hunk 3 above)
Comment (jmartisk) [reply extensions/agroal/runtime/src/main/java/io/quarkus/agroal/runtime/health/DataSourceHealthCheck.java]: done

**Review by xstefank — APPROVED** [review]
LGTM

File: extensions/datasource/runtime/src/main/java/io/quarkus/datasource/runtime/DataSourceBuildTimeConfig.java [hunk 5]
```diff
@@ -16,4 +16,13 @@
...
     public Optional<String> dbKind = Optional.empty();
 
+    /**
+     * Whether this particular data source should be excluded from the health check if
+     * the general health check for data sources is enabled.
+     * <p>
+     * By default, the health check includes all configured data sources (if it is enabled).
+     */
+    @ConfigItem(defaultValue = "false")
+    public boolean healthCheckExclude;
```
Comment (gsmet) [inline extensions/datasource/runtime/src/main/java/io/quarkus/datasource/runtime/DataSourceBuildTimeConfig.java:26]: Could we maybe have something like `health.exclude` instead? That looks a bit more in line with `health.enabled`.

**Review by gsmet — CHANGES_REQUESTED** [review]
Added a small suggestion.

File: extensions/datasource/runtime/src/main/java/io/quarkus/datasource/runtime/DataSourceBuildTimeConfig.java (hunk 5 above)
Comment (jmartisk) [reply extensions/datasource/runtime/src/main/java/io/quarkus/datasource/runtime/DataSourceBuildTimeConfig.java]: Done

**Review by machi1990 — APPROVED** [review]

File: extensions/datasource/runtime/src/main/java/io/quarkus/datasource/runtime/DataSourceBuildTimeConfig.java [hunk 6]
```diff
@@ -16,4 +16,13 @@
...
     public Optional<String> dbKind = Optional.empty();
 
+    /**
+     * Whether this particular data source should be excluded from the health check if
+     * the general health check for data sources is enabled.
+     * <p>
+     * By default, the health check includes all configured data sources (if it is enabled).
+     */
+    @ConfigItem(defaultValue = "false")
+    public boolean healthExclude;
```
Comment (gsmet) [inline extensions/datasource/runtime/src/main/java/io/quarkus/datasource/runtime/DataSourceBuildTimeConfig.java:26]: That will make it `health-exclude` not `health.exclude`. Also shouldn't we have a test?

**Review by gsmet — CHANGES_REQUESTED** [review]

File: extensions/datasource/runtime/src/main/java/io/quarkus/datasource/runtime/DataSourceBuildTimeConfig.java (hunk 6 above)
Comment (jmartisk) [reply extensions/datasource/runtime/src/main/java/io/quarkus/datasource/runtime/DataSourceBuildTimeConfig.java:26]: Hmm. Maybe we should keep it at `health-exclude`, because`quarkus.datasource.health.enabled` is a setting that is only used globally, whereas the exclusions are per each datasource. If we used `health.enabled` here, then we would get
- `quarkus.datasource.health.enabled` for the global setting
- `quarkus.datasource.health.exclude` would be to exclude the DEFAULT data source, but it would look very similar to the previous one (it shares the complete segment namespace) and therefore it would look like it's a global setting too, but it's not... Hope my explanation is understandable

Anyway I've added a test as you requested

Comment (jmartisk) [reply extensions/datasource/runtime/src/main/java/io/quarkus/datasource/runtime/DataSourceBuildTimeConfig.java:26]: Hey @gsmet so what do you think? We got a user asking when this will be released. Still insist on renaming?

Comment (masini) [reply extensions/datasource/runtime/src/main/java/io/quarkus/datasource/runtime/DataSourceBuildTimeConfig.java:26]: Hi @gsmet we need this for many production container, can we help on this PR so that can be merged soon?

Thanks

**Review by gsmet — APPROVED** [review]
OK, I don't really agree with the config name but let's not block this PR further.

I pushed a rebase, let's see what CI has to say.
