### PR TITLE
Fix providers not auto registered for JAX-RS Client

### LINKED ISSUE #11424: JAX-RS Providers in RESTEasy are not initialized unless a @Path is present in the Application
**Describe the bug**
A RESTEasy deployment is only produced if something with a `@Path` is found:

https://github.com/quarkusio/quarkus/blob/69ba3184ecd511fe7232ad6c4a852db6399baa2e/extensions/resteasy-server-common/deployment/src/main/java/io/quarkus/resteasy/server/common/deployment/ResteasyServerCommonProcessor.java#L205-L208

This works fine for most cases. There is one case where this doesn't work:

If we have a Quarkus app, using a simple `ClientBuilder.newClient()`, annotated Providers are not automatically registered with the client, because the RESTEasy deployment was not initialized:

https://github.com/quarkusio/quarkus/blob/73d39594b469d31240bcc2dc1fca2121f5bcdf9e/extensions/resteasy/runtime/src/main/java/io/quarkus/resteasy/runtime/standalone/ResteasyStandaloneRecorder.java#L68-L74

Which causes the Providers to not being registed with the client.

If we add a simple endpoint or even a dummy rest client interface with `@Path`, it works!

**Expected behavior**
Consistent behaviour of Providers with `ClientBuilder.newClient()` independent of other classes in the application.

**Actual behavior**
Providers are only registered if a `@Path` class exists in the application.

**Environment (please complete the following information):**
- Quarkus version or git rev: 1.7.0.Final

**Additional context**
Providers can still be registered manually in the `ClientBuilder` to workaround this issue. Also RESTEasy is clear regarding Providers registration and the Client: https://docs.jboss.org/resteasy/docs/3.7.0.Final/userguide/html/Client_Providers_With_Provider_Annotation.html

### PR DESCRIPTION
**Pull request by radcortez**
Fixes #11424

### CODE REVIEW

**Comment by kenfinnigan** [comment]
Happened to see this, and I'm not sure how this fix works.

A change has been made in `resteasy-server-common`, but that artifact isn't used by `rest-client`. From the issue it seemed this problem occurred with REST Client when the server isn't present, or am I mistaken?

**Comment by radcortez** [comment]
Hi @kenfinnigan 

Common is used here:
https://github.com/quarkusio/quarkus/blob/193ebe22c12a2b7651893ade7384e8bf4b8a5924/extensions/rest-client/runtime/pom.xml#L26-L29

The issue only occurs with the programmatic REST Client `ClientBuilder.getClient()` and when there is not another class annotated with `@Path` in the application. This prevents the RESTEasy server to start and annotated `Providers` are not auto registered with the programmatic client.

**Comment by radcortez** [comment]
The proposal is to use the same solution that was used in Quartz:
https://quarkus.io/guides/quartz#quarkus-quartz_quarkus.quartz.force-start

To have a config that force starts the server.

The programmatic REST Client does work without the RESTEasy server, is just doesn't auto register scanned metadata like `Providers`. Another possible solution would be to auto start the server if we detect user `Provider` classes, but it doesn't mean that the programmatic REST Client is going to be used so it may be a waste.

**Comment by kenfinnigan** [comment]
@radcortez Yes `resteasy-common` is used by REST Client, but the change was made in `resteasy-server-common`, which is a different dependency.

That's why I wasn't sure if the change actually worked when just using REST Client with no JAX-RS endpoints

**Comment by radcortez** [comment]
Hum, maybe you are right. The dependency is there, but as test in the extension. Let me try it out with a real project.

**Comment by radcortez** [comment]
Found an easier way to do it. Plus, I believe we could probably get rid of this:
https://github.com/quarkusio/quarkus/blob/b406f7ac160389fdcf19ef95225afbdea7a48441/extensions/rest-client/runtime/src/main/java/io/quarkus/restclient/runtime/graal/ClientBuilderReplacement.java#L15

File: extensions/rest-client/runtime/src/main/java/io/quarkus/restclient/runtime/RestClientRecorder.java [hunk 1]
```diff
@@ -69,6 +69,7 @@ public InjectorFactory getInjectorFactory() {
         }
 
         RestClientBuilderImpl.setProviderFactory(clientProviderFactory);
+        ResteasyProviderFactory.setInstance(clientProviderFactory);
```
Comment (gsmet) [inline extensions/rest-client/runtime/src/main/java/io/quarkus/restclient/runtime/RestClientRecorder.java:72]: This won't conflict with the server behavior when both are used? /cc @kenfinnigan

Comment (radcortez) [reply extensions/rest-client/runtime/src/main/java/io/quarkus/restclient/runtime/RestClientRecorder.java:72]: I don't think so. When the server starts (if any) it will replace the instance:

https://github.com/resteasy/Resteasy/blob/1570f6825de1fde1ea3c3a950dcb6297e3c9bd4f/resteasy-core/src/main/java/org/jboss/resteasy/core/ResteasyDeploymentImpl.java#L377

And it will work for both server and client with the right factory.

Comment (kenfinnigan) [reply extensions/rest-client/runtime/src/main/java/io/quarkus/restclient/runtime/RestClientRecorder.java:72]: Is the `ResteasyDeploymentImpl` used in Quarkus, for some reason I'm thinking it isn't, but could easily be wrong?

If we do use it, then I think it should work fine. But certainly worth verifying

Comment (radcortez) [reply extensions/rest-client/runtime/src/main/java/io/quarkus/restclient/runtime/RestClientRecorder.java:72]: Yes, it is used here:
https://github.com/quarkusio/quarkus/blob/5941a39ba4c1eecedd854f74b4d9e688082a73fc/extensions/resteasy-server-common/runtime/src/main/java/io/quarkus/resteasy/server/common/runtime/QuarkusResteasyDeployment.java

Comment (kenfinnigan) [reply extensions/rest-client/runtime/src/main/java/io/quarkus/restclient/runtime/RestClientRecorder.java:72]: Thanks for checking

**Comment by gsmet** [comment]
@kenfinnigan could you approve it if everything is good for you? Thanks!

**Review by kenfinnigan — APPROVED** [review]

File: extensions/rest-client/runtime/src/main/java/io/quarkus/restclient/runtime/RestClientRecorder.java (hunk 1 above)
Comment (FroMage) [reply extensions/rest-client/runtime/src/main/java/io/quarkus/restclient/runtime/RestClientRecorder.java:72]: Famous Last Words™
