### PR TITLE
CLI: set registry client system property

### LINKED ISSUE #18774: quarkus21 create --registry-client -S 2.43 --dry-run test27899rr4j fails with non informative error
### Describe the bug

with no registries configured and asking for nonexistent stream I get this:

```
quarkus21 create --registry-client -S 2.43 --dry-run test27899rr4j
Creating an app (default project type, see --help).
Refreshing the local extension catalog cache of registry.quarkus.io
Downloading from registry.quarkus.io: https://registry.quarkus.io/maven/io/quarkus/registry/quarkus-registry-descriptor/1.0-SNAPSHOT/maven-metadata.xml
Downloaded from registry.quarkus.io: https://registry.quarkus.io/maven/io/quarkus/registry/quarkus-registry-descriptor/1.0-SNAPSHOT/maven-metadata.xml (736 B at 650 B/s)
Downloading from registry.quarkus.io: https://registry.quarkus.io/maven/io/quarkus/registry/quarkus-platforms/1.0-SNAPSHOT/maven-metadata.xml
Downloaded from registry.quarkus.io: https://registry.quarkus.io/maven/io/quarkus/registry/quarkus-platforms/1.0-SNAPSHOT/maven-metadata.xml (726 B at 3.6 kB/s)
[ERROR] ❗  Unable to create project: Failed to resolve the Quarkus extension catalog
```

i would have expected a message saying something like:

 "Stream io.quarkus.platform:2.43 not found. Try one of these:
   - io.quarkus.platform:2.0
   - io.quarkus.platform:2.1
   "

assuming 2.0 and 2.1 are present

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### LINKED ISSUE #18799: CLI ext add, list, remove are not registry aware
### Describe the bug

Currently the registry client needs to be explicitly enabled to resolve extension catalogs from registries. This option is available for `create` but not the rest of the commands such as `add`, `list` and `remove`.
Either we should switch to the registry client as the default source of extension catalog or we need to add the option to all the commands to enable it.

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ebullient**
Resolves #18799 
Resolves #18774

### CODE REVIEW

File: devtools/cli/src/test/java/io/quarkus/cli/CliDriver.java [hunk 1]
```diff
@@ -254,9 +262,9 @@ public static Result invokeExtensionListInstallable(Path projectRoot) throws Exc
         Result result = CliDriver.execute(projectRoot, "extension", "list", "-e", "-B", "--verbose", "-i");
         Assertions.assertEquals(CommandLine.ExitCode.OK, result.exitCode,
                 "Expected OK return code. Result:\n" + result);
-        Assertions.assertTrue(result.stdout.contains("quarkus-hibernate-orm"),
+        Assertions.assertTrue(result.stdout.matches(".*[^-]quarkus-hibernate-orm.*"),
```
Comment (aloubyansky) [inline devtools/cli/src/test/java/io/quarkus/cli/CliDriver.java:265]: This should not change. Pulling in camel should not be expected in tests.

**Review by aloubyansky — APPROVED** [review]
