### PR TITLE
[native-image] Adds -H:+ForeignAPISupport for all GraalVM 24.2+

### LINKED ISSUE #44001: AWT native extension needs porting to JDK 24 ea
### Describe the bug

AWT extension needs adjusting for the latest JDK 24 ea.

### Expected behavior

AWT integration tests pass.

### Actual behavior

AWT integration tests fail.

### Why hasn't it been caught already?

https://github.com/quarkusio/quarkus/issues/43997

### How to Reproduce?

```
$ wget https://ci.modcluster.io/view/Mandrel/job/mandrel-master-linux-build-matrix/1547/JDK_RELEASE=ea,JDK_VERSION=24,LABEL=el8_aarch64/artifact/mandrel-java24-linux-aarch64-24.2.0-devc6e7912f0d0.tar.gz
....
$ export JAVA_HOME=/home/tester/karm/openjdk-17/;export GRAALVM_HOME=/home/tester/karm/mandrel-java24-24.2.0-devc6e7912f0d0;export PATH=${JAVA
_HOME}/bin:${PATH}
$ ./mvnw verify -f integration-tests/pom.xml -pl awt -Pnative

2024-10-21 12:58:31,448 ERROR [io.qua.run.Application] (main) Failed to start application: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:121)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
Caused by: jakarta.enterprise.inject.CreationException: java.io.IOException: Problem reading font data.
	at io.quarkus.awt.it.Application_Bean.create(Unknown Source)
	at io.quarkus.awt.it.Application_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:119)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:38)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)
	at io.quarkus.arc.generator.Default_jakarta_enterprise_context_ApplicationScoped_ContextInstances.c1(Unknown Source)
	at io.quarkus.arc.generator.Default_jakarta_enterprise_context_ApplicationScoped_ContextInstances.computeIfAbsent(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:35)
	at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:21)
	at io.quarkus.awt.it.Application_ClientProxy.arc$delegate(Unknown Source)
	at io.quarkus.awt.it.Application_ClientProxy.arc_contextualInstance(Unknown Source)
	at io.quarkus.awt.it.Application_Observer_Synthetic_ynG-oL43sl6JgV-MAWMK4JViQwo.notify(Unknown Source)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:351)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:333)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:80)
	at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:163)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:114)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
	... 7 more
Caused by: java.io.IOException: Problem reading font data.
	at java.desktop@24-beta/java.awt.Font.createFont0(Font.java:1205)
	at java.desktop@24-beta/java.awt.Font.createFont(Font.java:1076)
	at io.quarkus.awt.it.Application.init(Application.java:63)
	at io.quarkus.awt.it.Application_Bean.doCreate(Unknown Source)
	... 26 more

```

~The problem is likely in the part where we cope with the fact that JDK code expects JAVA_HOME to be there to look up font files while native-image neither needs nor has any JAVA_HOME.~

 

### Output of `uname -a` or `ver`

Linux mandrel2 5.14.0-407.el9.aarch64 #1 SMP PREEMPT_DYNAMIC Thu Jan 11 00:18:37 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux

### Output of `java -version`

OpenJDK Runtime Environment Temurin-17.0.13+11 (build 17.0.13+11)   \n OpenJDK Runtime Environment Mandrel-24.2.0-devc6e7912f0d0 (build 24-beta+19-ea)

### Quarkus version or git rev

main

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvnw

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Karm**
fixes #44001
enables a disabled test, discussed in #43997

Due to the AWT test being disabled it has been slipping under the radar that latest JDK, i.e. JDK 24+ uses [JEP 454](https://openjdk.org/jeps/454) API internally at places previously catered to by plain JNI. The fonts detection and fonts loading is such a place. We reflected this change in Mandrel test suite https://github.com/Karm/mandrel-integration-tests/pull/277, but it is finding its way to Quarkus only now with this PR.

See GraalVM notes on the support of this API in Native-image: [foreign-interface](https://www.graalvm.org/latest/reference-manual/native-image/native-code-interoperability/foreign-interface/)

I tested this PR with latest JDK 24 based Mandrel dev build `Mandrel-24.2.0-dev59c335af5b8 (build 24-beta+20-ea)`
and the current GA `Mandrel-24.1.1.0-Final (build 23.0.1+11)`.

## Question:
Do we enable the API unconditionally for JDK 24+ based native-image? Or do we detect AWT extension usage? Which other use cases might trigger this in the JDK code?

## Explanation of the debug 
...for posterity.

The error message is cryptic for information leakage reasons as discussed on https://github.com/openjdk/jdk/pull/20169#issuecomment-2381602619. 

```
Caused by: java.io.IOException: Problem reading font data.
	at java.desktop@24-beta/java.awt.Font.createFont0(Font.java:1205)
	at java.desktop@24-beta/java.awt.Font.createFont(Font.java:1076)
	at io.quarkus.awt.it.Application.init(Application.java:63)
	at io.quarkus.awt.it.Application_Bean.doCreate(Unknown Source)
	... 26 more
```

So the root cause became apparent to me during a `gdb` session:

```
(gdb) p *(t->cause->detailMessage->value)
$1054 = {<byte []> = {<java.lang.Object> = {<_objhdr> = {
        hub = 0xe093b8 <io.netty.handler.codec.http2.DefaultHttp2FrameReader::readHeadersFrame(io.netty.channel.ChannelHandlerContext*, 
io.netty.buffer.ByteBuf*, io.netty.handler.codec.http2.Http2FrameListener*)+1096>}, <No data fields>}, len = 101, 
data = 0x7fffed638eb0 "Support for the Java Foreign Function and Memory API is not active: enable with -H:+ForeignAPISupport"}, <No data fields>}
(gdb) 
```

...and only then I recalled the old https://github.com/Karm/mandrel-integration-tests/pull/277.

### CODE REVIEW

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java [hunk 1]
```diff
@@ -834,6 +834,15 @@ public NativeImageInvokerInfo build() {
 
                 addExperimentalVMOption(nativeImageArgs, "-H:+AllowFoldMethods");
 
+                /*
+                 * Foreign Function and Memory API in Native Image, JDK's JEP 454
+                 * This is needed for JDK 24+ internal native calls due to AWT.
+                 * TODO: Do we enable it globally like so or do we only enable it when AWT extension is used?
```
Comment (gsmet) [inline core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java:840]: I think I would rather be consistent rather than enabling obscure options only when a very specific extension is enabled.

So +1 for your current approach but I also would like @zakkak 's opinion on this.

**Review by gsmet — APPROVED** [review]

**Comment by Karm** [comment]
Just a rebase to account for #44139

**Comment by Karm** [comment]
@zakkak If you have any specific suggestion as to what to explore, gimme a hint.  I think we eventually need this when Brotli4j switches to FFI too...

**Comment by zakkak** [comment]
> @zakkak If you have any specific suggestion as to what to explore, gimme a hint. I think we eventually need this when Brotli4j switches to FFI too...

At the moment it's not clear to me what code is using the FFM API when using AWT. Is it `java.awt` itself or some 3rd party library?

**Comment by Karm** [comment]
> > @zakkak If you have any specific suggestion as to what to explore, gimme a hint. I think we eventually need this when Brotli4j switches to FFI too...
> 
> At the moment it's not clear to me what code is using the FFM API when using AWT. Is it `java.awt` itself or some 3rd party library?

It's JDK itself, e.g. in sun.java2d, right off the bat: https://bugs.openjdk.org/browse/JDK-8337237 

i.e. this Quarkus PR is not to satisfy any specific third party lib like TwelveMonkeys or Bioformats etc.

**Comment by zakkak** [comment]
Good, in that case I guess enabling it by default (when using GraalVM for JDK >= 24) makes sense.

We could have a check to only do it when the corresponding internal libraries are reached but that will quickly get outdated.

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java (hunk 1 above)
Comment (zakkak) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java:840]:
```suggestion
```

**Review by zakkak — CHANGES_REQUESTED** [review]
Thank you Karm.

Please remove the TODO and it's good to go :)

**Comment by Karm** [comment]
@zakkak Can't merge it until you waive it I guess " Merging can be performed automatically once the requested changes are addressed. "

**Review by zakkak — APPROVED** [review]
