### PR TITLE
gRPC fix request context clean-up

### LINKED ISSUE #14820: GRPC / Panache Reactive Combination causes issues after a couple requests
**Describe the bug**
When invoking Panache Entities via a GRPC Service in a reactive way, the first couple invocations will work but after that all that happens is a "java.lang.IllegalStateException: session is currently connecting to database"

**Expected behavior**
The Panache invocations work until the end of the universe.

**Actual behavior**
After a couple of invocations only "java.lang.IllegalStateException: session is currently connecting to database" is produced.
HealthChecks will also fail if present in the project.

**To Reproduce**

Reproducer: [0SkillAllLuck/code-with-quarkus](https://github.com/0SkillAllLuck/code-with-quarkus)

**Environment (please complete the following information):**
 - Output of `java -version`:  openjdk version "11.0.9" 2020-10-20
 - Quarkus version or git rev: 1.11.1.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

### LINKED ISSUE #16890: ContextNotActive Exception When Chaining Reactive Calls
## Describe the bug
ContextNotActive Exceptions When Chaining Reactive Calls Across Stack

### Expected behavior
User should be able to make a REST call to a reactive route, which in turn calls a reactive gRPC client, which interfaces with a reactive Hibernate panache repository.

### Actual behavior
When not interfacing with the repository, user is able to make a REST call which calls a reactive gRPC client which gets picked up and processed by gRPC server implementation in separate module. When making the gRPC call then process a repository action, it throws a ContextNotActive Exception.

When calling the gRPC service directly and not via REST route, both the gRPC call and the repository action work successfully. Only when chaining this does the issue arise.

## To Reproduce

https://github.com/toandeaf/backup

I have recreated a stripped down version of my project with the services causing the issue.

- gradle user:buildNeeded
- gradle api:buildNeeded
- docker-compose up
- gradle user:quarkusDev
- gradle api:quarkusDev
- Curl/hit either localhost:8080/user/test or localhost:8080/userReactive/test to recreate issue.

Should see ContextNotActive exception.

### Screenshots
(If applicable, add screenshots to help explain your problem.)

## Environment (please complete the following information):
Development
### Output of `uname -a` or `ver`
20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64
### Output of `java -version`
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment GraalVM CE 21.0.0 (build 11.0.10+8-jvmci-21.0-b06)
OpenJDK 64-Bit Server VM GraalVM CE 21.0.0 (build 11.0.10+8-jvmci-21.0-b06, mixed mode, sharing)

### Quarkus version or git rev
1.13.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Gradle 6.8.2
## Additional context
Kotlin:       1.4.20

### PR DESCRIPTION
**Pull request by michalszynkiewicz**
fixes #14820 fixes #16890

### CODE REVIEW

File: extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/RequestScopeHandlerInterceptor.java [hunk 1]
```diff
@@ -31,10 +32,14 @@ public RequestScopeHandlerInterceptor() {
         // This interceptor is called first, so, we should be on the event loop.
         Context capturedVertxContext = Vertx.currentContext();
         if (capturedVertxContext != null) {
+            InjectableContext.ContextState state = null;
```
Comment (mkouba) [inline extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/RequestScopeHandlerInterceptor.java:35]: I think that you can make this var effectively final, i.e. `InjectableContext.ContextState state;` and assign `null` if `!activateAndDeactivateContext`.

File: extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/RequestScopeHandlerInterceptor.java [hunk 2]
```diff
@@ -43,7 +48,7 @@ public void close(Status status, Metadata trailers) {
                         capturedVertxContext.runOnContext(new Handler<Void>() {
                             @Override
                             public void handle(Void ignored) {
-                                reqContext.deactivate();
+                                reqContext.destroy(finalState);
```
Comment (cescoffier) [inline extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/RequestScopeHandlerInterceptor.java:51]: For my own curiosity, what's the difference?

Comment (mkouba) [reply extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/RequestScopeHandlerInterceptor.java:51]: `deactivate()` merely removes the state from a threadlocal variable. `destroy()` destroys all the bean instances correctly.

Comment (mkouba) [reply extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/RequestScopeHandlerInterceptor.java:51]: I know it's complicated but we need this in order to be able to propagate the context and follow the CDI rules for normal scopes...

Comment (michalszynkiewicz) [reply extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/RequestScopeHandlerInterceptor.java:51]: maybe we could rename the methods to shutdown and clear? I'm not sure it would be more clear to anyone but me :D

File: extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/RequestScopeHandlerInterceptor.java (hunk 1 above)
Comment (michalszynkiewicz) [reply extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/RequestScopeHandlerInterceptor.java]: fixed

File: extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/RequestScopeHandlerInterceptor.java (hunk 2 above)
Comment (mkouba) [reply extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/RequestScopeHandlerInterceptor.java]: > maybe we could rename the methods to shutdown and clear? I'm not sure it would be more clear to anyone but me :D

-1 the method names somehow relate to the CDI API, e.g. `Context.isActive()` and `Contextual.destroy()`.

File: extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/context/GrpcRequestContextCdiInterceptor.java [hunk 3]
```diff
@@ -0,0 +1,37 @@
...
+@Interceptor
+@CleanUpRequestContext
+public class GrpcRequestContextCdiInterceptor {
+    public static final String GRPC_REQUEST_CONTEXT_STATE = "GRPC_REQUEST_CONTEXT_STATE";
+
+    @AroundInvoke
+    public Object cleanUpContext(InvocationContext invocationContext) throws Exception {
+        boolean cleanUp = false;
+        ManagedContext requestContext = Arc.container().requestContext();
+        if (!requestContext.isActive()) {
```
Comment (michalszynkiewicz) [inline extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/context/GrpcRequestContextCdiInterceptor.java:21]: @cescoffier does this look okay? I'm chaning the logic to initialize request context in a CDI interceptor. But I need to somehow pass it to the grpc interceptor `close` method to destroy the context.
I used `Vertx.currentContext()` for this and I'm accessing it [here](https://github.com/quarkusio/quarkus/pull/16830/files#diff-e06152b8deda49666ec8a46293ccb49bef940d1d3ee1833c058fd7740a71c68eR39)

**Comment by michalszynkiewicz** [comment]
converted to draft because 

1. I discovered one issue with interceptors and dev reload that I want to fix here too 
2. The things I'm doing with vertx context work okay in the tests but I'm not sure if it's conceptually proper

File: extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/context/GrpcRequestContextCdiInterceptor.java (hunk 3 above)
Comment (mkouba) [reply extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/context/GrpcRequestContextCdiInterceptor.java:21]: So the question is whether we can be 100% sure that the service bean is always invoked on the event loop context..

**Comment by michalszynkiewicz** [comment]
dev mode client request handling is fixed now, the only thing that I'm unsure about is what I do with passing the request context state via Vertx context, I'm un-drafting the PR

File: extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/context/GrpcRequestContextCdiInterceptor.java (hunk 3 above)
Comment (cescoffier) [reply extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/context/GrpcRequestContextCdiInterceptor.java:21]: Did you try with a method marked with `@Blocking`?

Comment (cescoffier) [reply extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/context/GrpcRequestContextCdiInterceptor.java:21]: It looks fine too me. I know there have been changed in Vert.x 4 about context management but it should be ok.

Comment (michalszynkiewicz) [reply extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/context/GrpcRequestContextCdiInterceptor.java:21]: Simply adding `@Blocking` on a method that returns multi works fine in my tests

Comment (michalszynkiewicz) [reply extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/context/GrpcRequestContextCdiInterceptor.java:21]: hmm.. But when I add Blocking and do something blocking, I'm getting an error saying that I cannot block the event loop :(

Comment (michalszynkiewicz) [reply extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/context/GrpcRequestContextCdiInterceptor.java:20]: fixed in the current version :)

File: extensions/grpc/deployment/src/main/java/io/quarkus/grpc/deployment/GrpcServerProcessor.java [hunk 4]
```diff
@@ -80,15 +91,31 @@ void discoverBindableServices(BuildProducer<BindableServiceBuildItem> bindables,
...
+            @Override
+            public boolean appliesTo(AnnotationTarget.Kind kind) {
+                return kind == AnnotationTarget.Kind.METHOD;
+            }
+
+            @Override
+            public void transform(TransformationContext transformationContext) {
+                MethodInfo target = transformationContext.getTarget().asMethod();
+                if (grpcServiceNames.contains(target.declaringClass().name()) && !"bindService".equals(target.name())) {
+                    transformationContext.transform().add(CleanUpRequestContext.class).done();
```
Comment (mkouba) [inline extensions/grpc/deployment/src/main/java/io/quarkus/grpc/deployment/GrpcServerProcessor.java:107]: We could add the interceptor binding directly to the `@GrpcService` stereotype and only transform the classes that are annotated with `@Singleton`.

File: extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/context/CleanUpRequestContext.java [hunk 5]
```diff
@@ -0,0 +1,16 @@
...
+import java.lang.annotation.RetentionPolicy;
+import java.lang.annotation.Target;
+
+import javax.interceptor.InterceptorBinding;
+
+@Inherited
+@InterceptorBinding
+@Target({ ElementType.TYPE })
+@Retention(RetentionPolicy.RUNTIME)
+public @interface CleanUpRequestContext {
```
Comment (mkouba) [inline extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/context/CleanUpRequestContext.java:15]: The name of the annotation is a bit misleading now..

File: extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/context/GrpcRequestContextGrpcInterceptor.java [hunk 6]
```diff
@@ -0,0 +1,78 @@
...
+                                reqContext.destroy(contextHolder.state);
+                            }
+                        }
+                    }, headers);
+
+            return new ForwardingServerCallListener.SimpleForwardingServerCallListener<ReqT>(delegate) {
+
+                @Override
+                public void onMessage(ReqT message) {
+                    activateContext();
```
Comment (mkouba) [inline extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/context/GrpcRequestContextGrpcInterceptor.java:51]: It might make sense to add some comments why we activate the context in these callbacks although we do it in `GrpcRequestContextCdiInterceptor` as well..

File: extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/GrpcServerRecorder.java [hunk 7]
```diff
@@ -432,4 +464,17 @@ public void handle(AsyncResult<Void> ar) {
...
+
+    private class DevModeWrapper {
+        private final ClassLoader classLoader;
+
+        public DevModeWrapper(ClassLoader contextClassLoader) {
+            classLoader = contextClassLoader;
+        }
+
+        public void run(Runnable command) {
+            Thread.currentThread().setContextClassLoader(classLoader);
```
Comment (mkouba) [inline extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/GrpcServerRecorder.java:476]: Shouldn't we reset the original TCCL after the command is run?

File: extensions/grpc/deployment/src/main/java/io/quarkus/grpc/deployment/GrpcServerProcessor.java (hunk 4 above)
Comment (mkouba) [reply extensions/grpc/deployment/src/main/java/io/quarkus/grpc/deployment/GrpcServerProcessor.java:107]: Hm, is there a reason why we don't add the binding on the class level? I've noticed some warnings like these:
```
2021-04-30 13:49:20,719 WARN  [io.qua.arc.dep.sta.InterceptedStaticMethodsProcessor] (build-11) Interception of private static methods is not supported; bindings found on io.quarkus.grpc.server.services.MutinyHelloService: io.grpc.examples.helloworld.HelloReply lambda$sayHello$1(java.lang.String s)
```
If we need to transform the methods then we should probably skip at least private, static and synthetic methods.

File: extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/GrpcServerRecorder.java (hunk 7 above)
Comment (michalszynkiewicz) [reply extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/GrpcServerRecorder.java:476]: in practice, the original one is the one before dev mode reload. But in theory, it makes sense, I'll do it

File: extensions/grpc/deployment/src/main/java/io/quarkus/grpc/deployment/GrpcServerProcessor.java (hunk 4 above)
Comment (michalszynkiewicz) [reply extensions/grpc/deployment/src/main/java/io/quarkus/grpc/deployment/GrpcServerProcessor.java:107]: @cescoffier what do you think of requiring users to use `@GrpcService`? That would be even more breaking but since we are already breaking...

Then we wouldn't have to do any annotation transformations here

File: extensions/grpc/deployment/src/main/java/io/quarkus/grpc/deployment/GrpcServerProcessor.java [hunk 8]
```diff
@@ -66,9 +69,11 @@ MinNettyAllocatorMaxOrderBuildItem setMinimalNettyMaxOrderSize() {
 
     @BuildStep
     void discoverBindableServices(BuildProducer<BindableServiceBuildItem> bindables,
-            CombinedIndexBuildItem combinedIndexBuildItem) {
+            CombinedIndexBuildItem combinedIndexBuildItem,
+            BuildProducer<AnnotationsTransformerBuildItem> annotationTransformers) {
```
Comment (mkouba) [inline extensions/grpc/deployment/src/main/java/io/quarkus/grpc/deployment/GrpcServerProcessor.java:73]: The `BuildProducer<AnnotationsTransformerBuildItem>` is not used anymore..

Comment (michalszynkiewicz) [reply extensions/grpc/deployment/src/main/java/io/quarkus/grpc/deployment/GrpcServerProcessor.java]: fixed

**Review by mkouba — APPROVED** [review]
I'm not sure about the gRPC interceptors part but the fix for request context destruction looks good.

**Comment by Sgitario** [comment]
As this will start failing if not using the `@GrpcService` annotation (before it was not necessary), this should be mentionated in the migration guide.
@michalszynkiewicz  what do you think? Not sure if you already added it.

**Comment by michalszynkiewicz** [comment]
@Sgitario good point. I updated the migration guide

**Comment by gsmet** [comment]
This one is not easily backportable. So either we have specific PRs or it won't be backported.
