### PR TITLE
Place json configuration files next to thin jar when building

### LINKED ISSUE #5390: Adding a reflection configuration file fails when building native using Docker
We are currently trying to update an old 0.21.2 Quarkus Project to 0.28.1. In this project we used a reflect-config.json to keep classes from being deleted. With 0.21.2 we could successfully build a native image and a docker container, but now we can't.

We already changed to quarkus.native.additional-build-args in the application.properties file with these parameters: 
```
quarkus.native.additional-build-args=\
-H:ResourceConfigurationFiles=resources/main/resource-config.json,\
-H:ReflectionConfigurationFiles=resources/main/reflect-config.json

quarkus.native.enable-jni=true
quarkus.native.enable-http-url-handler=true
quarkus.native.enable-https-url-handler=true
quarkus.native.enable-all-security-services=true
```

Trying to execute the build ends in an error that he can't find project/resources/main/reflect-config.json.

What Quarkus tries to execute is this: 
`docker run -v /home/bfr/git/minical-multi/minical/build/minical-0.2.0-native-image-source-jar:/project:z --user 1000:1001 --rm quay.io/quarkus/ubi-quarkus-native-image:19.2.1 -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=1 -H:ResourceConfigurationFiles=resources/main/resource-config.json -H:ReflectionConfigurationFiles=resources/main/reflect-config.json --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime -jar minical-0.2.0-runner.jar -J-Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:EnableURLProtocols=http,https --enable-all-security-services -H:-SpawnIsolates -H:+JNI --no-server -H:-UseServiceLoaderFeature -H:+StackTrace minical-0.2.0-runner`

In the earlier versions of quarkus just the build directory was bound to docker as a volume and all files were found correctly, but now it is only the native-image-source-jar and we can't figure out a way to get the reflect-config.json into it, because always on build the directory is new generated and deletes the already copied file. 

The reflect-config.json itself is in the .jar file and can't also be accessed. Is there a way to do it, like change the volume path for the `docker run` or any other way we oversaw?

We are using gradle to build our project.

### PR DESCRIPTION
**Pull request by geoand**
This makes it very easy and predicable to configure
add extra json files to configure GraalVM natives.
Furthermore, this makes these files available to
docker when a container build of the native image
is being used - something which fails without this change.

Fixes: #5390

### CODE REVIEW

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/JarResultBuildStep.java [hunk 1]
```diff
@@ -358,6 +360,34 @@ public NativeImageSourceJarBuildItem buildNativeImageJar(CurateOutcomeBuildItem
...
+            public boolean test(Path path, BasicFileAttributes basicFileAttributes) {
+                return basicFileAttributes.isRegularFile() && path.toString().endsWith(".json");
+            }
+        }).forEach(new Consumer<Path>() {
+            @Override
+            public void accept(Path jsonPath) {
+                try {
+                    Files.copy(jsonPath, thinJarDirectory.resolve(jsonPath.getFileName()));
+                } catch (IOException e) {
+                    throw new RuntimeException("Unable to copy json config file from " + jsonPath + " to " + thinJarDirectory,
```
Comment (gastaldi) [inline core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/JarResultBuildStep.java]: `throw new UncheckedIOException(..., e )`

**Comment by geoand** [comment]
I could add tests for these if you feel it's warranted, but they would of course slow down the build a lot.
I tested by creating a maven and gradle project then adding a json config file for GraalVM and finally building using both regular and docker builds.

File: docs/src/main/asciidoc/writing-native-applications-tips.adoc [hunk 2]
```diff
@@ -58,37 +86,23 @@ Now, let's tell the `native-image` executable about this configuration file by t
...
-
-When using Gradle, we need to configure the additional build arguments in the plugin configuration:
+When using Gradle, configuring the `buildNative` task like so suffices:
 
 [source,groovy]
 ----
 buildNative {
     additionalBuildArgs = [
-            "-H:ResourceConfigurationFiles=${buildDir}/resources/main/resources-config.json".toString()
+            'resources-config.json'
```
Comment (gastaldi) [inline docs/src/main/asciidoc/writing-native-applications-tips.adoc]: Don't you need to still specify the `-H:ResourceConfigurationFiles` here?

**Review by gastaldi — COMMENTED** [review]
Added some comments

File: docs/src/main/asciidoc/writing-native-applications-tips.adoc (hunk 2 above)
Comment (geoand) [reply docs/src/main/asciidoc/writing-native-applications-tips.adoc]: Oops!

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/JarResultBuildStep.java (hunk 1 above)
Comment (geoand) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/JarResultBuildStep.java]: Fixed, thanks!

File: docs/src/main/asciidoc/writing-native-applications-tips.adoc (hunk 2 above)
Comment (geoand) [reply docs/src/main/asciidoc/writing-native-applications-tips.adoc]: Fixed

**Review by gastaldi — APPROVED** [review]
LGTM

**Comment by geoand** [comment]
@gsmet are you ok with this one?

**Comment by stuartwdouglas** [comment]
I don't really like this solution. Even though it improves the status quo I still don't think it provides a great user experience. 

Maybe the approach should be: 
- Everything in the application (src/main/resources) is included by default (otherwise why would it be in the application if it was not needed?)
- Additional resources can be included through either an annotation that specifies the paths to include, or a config file in a well known location (quarkus-resources.properties?) that we parse at build time and then automatically handle. 
- Maybe the ability to include resources via application.properties, but I don't know if this is really config

I think we should discuss this, as the user should not have to mess around with JSON files or the substrate command line to include some resources in their image.

**Comment by geoand** [comment]
@stuartwdouglas you have my vote when it comes to adding everything in `src/main/resources`, I had even opened an issue about it: https://github.com/quarkusio/quarkus/issues/2746.

This PR didn't really attempt to solve that problem generally. It was motivated primarily by the fact that currently one can't due a native build using docker and specify the json config files

**Comment by geoand** [comment]
Even if we do add some dedicated configuration options for resource and reflection handling (plus whatever other json file could be added), we'll still need the copy mechanics of this PR.

I do like the idea of having dedicated `quarkus.native.reflection-config-files` or something like that to users can just specify what they want to include.
