### PR TITLE
When container image credentials present, use only those

### LINKED ISSUE #10683: Jib extension ignores `quarkus.container-image.username` and `quarkus.container-image.password`
**Describe the bug**
Added the following properties to my application.properties

    quarkus.container-image.registry=docker.io
    quarkus.container-image.username=iocanel
    quarkus.container-image.password=<my password>

and run: `mvn clean install -Dquarkus.container-image.push=true`

**Expected behavior**
Image should be pushed

**Actual behavior**
Fails with 401 error
Works find with the container-image-docker

### PR DESCRIPTION
**Pull request by geoand**
This is done in order to make Jib not fail if there are invalid
credentials in the docker config file

Fixes: #10683

_This was done because @cmoulliard was hit by the same issue_

### CODE REVIEW

**Comment by geoand** [comment]
@iocanel @gastaldi do you think that it makes sense to try **only** the use provided credentials (when they are provided of course) instead of falling back to docker config?

If we made this change, it would be a breaking change

**Comment by gastaldi** [comment]
@geoand yes, that makes sense to me

**Review by gastaldi — APPROVED** [review]

**Comment by cmoulliard** [comment]
> that makes sense to me

Otherwise Jib is looking first AFAIK to use on the laptop of the user the credentials created/managed using helper tools https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin#using-docker-credential-helpers

**Comment by cmoulliard** [comment]
See the 2 use cases I tested today and confirming the issue reported by Ioannis : https://gist.github.com/cmoulliard/608b67327dc52a86e8ac3ac5acbcf6a1

**Comment by edeandrea** [comment]
My opinion - quarkus should only check its own config. you either provide credentials or you don’t. If you don’t the push fails unless you provide credentials. Yes it would be a breaking change, but going from Quarkus 1.x -> 2.x, a major version, you're allowed to make breaking changes.

**Comment by geoand** [comment]
> My opinion - quarkus should only check its own config. you either provide credentials or you don’t.

Agreed

> Yes it would be a breaking change, but going from Quarkus 1.x -> 2.x, a major version, you're allowed to make breaking changes.

Yes and no. We don't use semantic versioning and we don't want to use 2.x as an excuse to break the world. In this case the risk of breakage is small and the semantics are pretty straighforward, so I think it's warranted.

File: extensions/container-image/container-image-jib/deployment/src/main/java/io/quarkus/container/image/jib/deployment/JibProcessor.java [hunk 1]
```diff
@@ -220,10 +220,11 @@ private RegistryImage toRegistryImage(ImageReference imageReference, Optional<St
         CredentialRetrieverFactory credentialRetrieverFactory = CredentialRetrieverFactory.forImage(imageReference,
                 log::info);
         RegistryImage registryImage = RegistryImage.named(imageReference);
-        registryImage.addCredentialRetriever(credentialRetrieverFactory.wellKnownCredentialHelpers());
-        registryImage.addCredentialRetriever(credentialRetrieverFactory.dockerConfig());
         if (username.isPresent() && password.isPresent()) {
             registryImage.addCredential(username.get(), password.get());
+        } else {
```
Comment (edeandrea) [inline extensions/container-image/container-image-jib/deployment/src/main/java/io/quarkus/container/image/jib/deployment/JibProcessor.java:225]: My opinion - but I would think that we shouldn't ever include the docker credentials. It's either the quarkus credentials or nothing.

Comment (geoand) [reply extensions/container-image/container-image-jib/deployment/src/main/java/io/quarkus/container/image/jib/deployment/JibProcessor.java:225]: Which is what it does now, no?

Comment (edeandrea) [reply extensions/container-image/container-image-jib/deployment/src/main/java/io/quarkus/container/image/jib/deployment/JibProcessor.java:225]: its an `if`/`else`. If the credentials are present in the quarkus config, use them. Otherwise fall back to the docker config.

At least that's how I understand the code.

**Comment by Ladicek** [comment]
I'm not sure I agree that Quarkus should completely ignore what the user has configured for Docker.

If Quarkus config contains Docker credentials, that should obviously have priority over the user's Docker config. Whether we should fallback to user's Docker config, if the credentials in Quarkus config are invalid... I guess I don't really have an opinion. It's probably fine.

File: extensions/container-image/container-image-jib/deployment/src/main/java/io/quarkus/container/image/jib/deployment/JibProcessor.java (hunk 1 above)
Comment (geoand) [reply extensions/container-image/container-image-jib/deployment/src/main/java/io/quarkus/container/image/jib/deployment/JibProcessor.java:225]: Ah, no. We won't do that.

We definitely do want to include the standard configuration when the user has not supplied credentials

**Comment by edeandrea** [comment]
> I'm not sure I agree that Quarkus should completely ignore what the user has configured for Docker.
> 
> If Quarkus config contains Docker credentials, that should obviously have priority over the user's Docker config. Whether we should fallback to user's Docker config, if the credentials in Quarkus config are invalid... I guess I don't really have an opinion. It's probably fine to fail instead of falling back.

From a user's perspective if I don't follow the guide and provide credentials and then it succeeds, then how do I know how it actually worked, and more importantly, what credentials were used? To me that use case is almost like "failing silently", except in this case its "succeeding silently" when it should fail?

Just my 2 cents. Maybe if Quarkus still fails back, maybe add a `WARN` to the log saying that `quarkus.container-image.username` was not provided and falling back to the host's docker auth config?

**Comment by Ladicek** [comment]
> From a user's perspective if I don't follow the guide and provide credentials and then it succeeds, then how do I know how it actually worked, and more importantly, what credentials were used? To me that use case is almost like "failing silently", except in this case its "succeeding silently" when it should fail?

Fair enough. Fortunately, the present PR doesn't do that :-)

**Comment by geoand** [comment]
If you want thag warning, feel free to open a PR once this one is in.

I will not however accept a change that removes the fallback when no credentials are provided

**Comment by cmoulliard** [comment]
As Quarkus offers different building strategies (docker, jib, s2i, soon - buildpack), then I would recommend that we follow the same Auth rule(s) no matter which tool we will use to propose a great DevExp. Otherwise, that will be a pain for the developer to figure out, when there is a problem, what he should do.

My 1 or 2 cents :-)

**Comment by edeandrea** [comment]
> If you want that warning, feel free to open a PR once this one is in.
> 
> I will not however accept a change that removes the fallback when no credentials are provided

@geoand doesn't that comment go against where you agreed ` quarkus should only check its own config. you either provide credentials or you don’t.`?

**Comment by geoand** [comment]
This change does bring us closer to that

**Comment by gsmet** [comment]
@ebullient why did you add the backport label given it's already included in Alpha3? Am I missing something?

**Comment by ebullient** [comment]
looking at timing, I wasn't sure. There were some other cli ones I was marking @ the time. Sorry for not seeing this was in already.
