### PR TITLE
Log a warning when an export fails for `http/protobuf`

### LINKED ISSUE #48572: Quarkus does not send warning when TraceRequest fails for `quarkus.otel.exporter.otlp.protocol=http/protobuf`
### Describe the bug

In Quarkus, if you use OpenTelemetry with the default gRPC sender, if your trace request fails, you get a message such as:
```
2025-06-24 13:43:13,806 WARNING [io.qua.ope.run.exp.otl.sen.VertxGrpcSender] (vert.x-eventloop-thread-4) Failed to export TraceRequestMarshalers. The request could not be executed. Full error message: Connection refused: localhost/127.0.0.1:4317
```

However, if you switch to http/protobuf through 
```
quarkus.otel.exporter.otlp.protocol=http/protobuf
```

Requests fail silently without sending any warning

### Expected behavior

A warning should be given for the http/protobuf protocol if it fails to send a TraceRequest

### Actual behavior

No log message is sent to indicate that something went wrong.

### How to Reproduce?

1. Create a Quarkus application with the OpenTelemetry extension
2. Send a request to a non-existing endpoint and observe the warning log
3. Set `quarkus.otel.exporter.otlp.protocol=http/protobuf`
4. Send a request to a non-existing endpoint and observe no log message at all.

### Output of `uname -a` or `ver`

Ubuntu 25.04

### Output of `java -version`

OpenJDK 21.0.7

### Quarkus version or git rev

3.23.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.14.2

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
This is exactly the same as with `grpc`

- Fixes: #48572

### CODE REVIEW

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/exporter/otlp/sender/VertxHttpSender.java [hunk 1]
```diff
@@ -101,19 +101,33 @@ public void send(Marshaler marshaler,
...
+            public void accept(Throwable throwable) {
+                failOnClientRequest(marshalerType, throwable, onError);
+            }
+        });
+    }
+
+    private void failOnClientRequest(String type, Throwable t, Consumer<Throwable> onError) {
+        String message = "Failed to export "
+                + type
+                + "s. The request could not be executed. Full error message: "
```
Comment (gsmet) [inline extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/exporter/otlp/sender/VertxHttpSender.java]: Very minor but given the point of this PR is to add a message: I would drop the `s` from here. Won't work for `Child` for instance.

**Review by brunobat — APPROVED** [review]
Makes sense to me. Should we backport?

**Comment by geoand** [comment]
Good idea
