### PR TITLE
Validate "callback" method signature

### LINKED ISSUE #27591: Support annotation @PostConstruct (and similar) for reactive code
### Description

When writing reactive code, it's not possible to use `@PostConstruct` correctly:
```java
    @PostConstruct
    public Uni<Void> init() {
       return doSomething();
    }
```

This doesn't work and if users want to call a reactive method and be sure that it's executed before returning,
they have to block and wait:
```java
    @PostConstruct
    public void init() {
       doSomenthing().await().indefinitely();
    }
```

There are [some implementation details](https://github.com/quarkusio/quarkus/pull/26551#issuecomment-1231334195) that make this issue hard to solve:
> `@PostConstruct` callbacks are invoked during bean creation and the CDI API for bean construction is not async and therefore it does not help much. In other words, we can't properly support @PostConstruct Uni<Void> init() until we have an async bean construction API.

Note that returning a `Uni` is not the only solution and we could accept a parameter for synchronization. For example:
```java
    @PostConstruct
    public void init(CompletableFuture<Object> future) {
       doSomenthing()
           .subscribe().with( future::complete, future::completeExceptionally );
    }
```

Although we don't use this approach in other places.

Other resources:
* [The StackOveflow question of the user asking about it](https://stackoverflow.com/questions/73000578/using-transaction-in-postconstruct)
* [The previous PR where we briefly discuss this](https://github.com/quarkusio/quarkus/pull/26551#issuecomment-1231308629)

### PR DESCRIPTION
**Pull request by cescoffier**
In this case, a DefinitionException is thrown, indicating that the method signature is invalid.

Methods annotated with `@PostConstruct` and `@PreDestroy` are callbacks.

Fix #27591 according to the discussion.

### CODE REVIEW

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ArcProcessor.java [hunk 1]
```diff
@@ -521,9 +524,42 @@ public ValidationPhaseBuildItem validate(ObserverRegistrationPhaseBuildItem obse
...
+        validatePostConstructAndPreDestroyMethods(index.getIndex());
+
         return new ValidationPhaseBuildItem(validationContext, beanProcessor);
     }
 
+    /**
+     * Checks that methods annotated with {@code PostConstruct} and {@code PreDestroy} are not returning {@code Uni}
+     * or {@code Multi}
+     */
+    void validatePostConstructAndPreDestroyMethods(IndexView index) {
```
Comment (mkouba) [inline extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ArcProcessor.java:536]: I wonder if we should throw the definition exception in `io.quarkus.arc.processor.Beans.getCallbacks()` and `io.quarkus.arc.processor.Beans.collectCallbacks()` instead... A callback method must have the following signature: `void <METHOD>()`. The current behavior is that we ignore `@PostConstruc/@PreDestroy` methods with a different signature.

Comment (cescoffier) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ArcProcessor.java:536]: Wouldn't it be a breaking change for method returning something (even if ignored)?

Comment (cescoffier) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ArcProcessor.java:536]: This PR is a partial breaking change, as the method is called, but everything happening "in" the Uni would not happen. 

We can make it stricter and say that method must return "void".

Comment (mkouba) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ArcProcessor.java:536]: > This PR is a partial breaking change, as the method is called, but everything happening "in" the Uni would not happen.

I don't understand - this pr throws a `DefinitionException` and the build fails, or?

`@PostConstruct Uni<Foo> init()` is currently ignored.

Comment (cescoffier) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ArcProcessor.java:536]: I'm wondering about:

```
            if (method.returnType().kind() == Kind.VOID && method.parameterTypes().isEmpty()) {
```

in `Beans.collectCallbacks()`. 

Can't these methods receive injected beans?

Comment (mkouba) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ArcProcessor.java:536]: No. A lifecycle callback method defined on the bean class must not accept any params.

Comment (cescoffier) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ArcProcessor.java:536]: Ah ok, so yes, we can move the check here.

Comment (cescoffier) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ArcProcessor.java]: Check moved, improved error message.

File: extensions/arc/deployment/src/test/java/io/quarkus/arc/test/deployment/TestInvalidPostConstruct.java [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+import javax.enterprise.inject.spi.DefinitionException;
+
+import org.junit.jupiter.api.Test;
+import org.junit.jupiter.api.extension.RegisterExtension;
+
+import io.quarkus.arc.Unremovable;
+import io.quarkus.test.QuarkusUnitTest;
+import io.smallrye.mutiny.Uni;
+
+public class TestInvalidPostConstruct {
```
Comment (mkouba) [inline extensions/arc/deployment/src/test/java/io/quarkus/arc/test/deployment/TestInvalidPostConstruct.java:16]: These tests are ok but relatively "expensive" in terms of added value and time needed to run them. It might be better to add a test directly in the [ArC test module](https://github.com/quarkusio/quarkus/tree/main/independent-projects/arc/tests). Something like https://github.com/quarkusio/quarkus/blob/main/independent-projects/arc/tests/src/test/java/io/quarkus/arc/test/validation/InitializerMethodMarkedProducerTest.java

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ArcProcessor.java [hunk 3]
```diff
@@ -505,7 +506,7 @@ public ValidationPhaseBuildItem validate(ObserverRegistrationPhaseBuildItem obse
             List<ObserverConfiguratorBuildItem> observerConfigurationRegistry,
             List<UnremovableBeanBuildItem> unremovableBeans,
             BuildProducer<BytecodeTransformerBuildItem> bytecodeTransformer,
-            BuildProducer<SynthesisFinishedBuildItem> synthesisFinished) {
+            BuildProducer<SynthesisFinishedBuildItem> synthesisFinished, BeanArchiveIndexBuildItem index) {
```
Comment (mkouba) [inline extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ArcProcessor.java:509]: The `BeanArchiveIndexBuildItem` is no longer needed, or?

**Review by mkouba — COMMENTED** [review]
Looks good. I added two minor comments...

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ArcProcessor.java (hunk 3 above)
Comment (cescoffier) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ArcProcessor.java:509]: Yes, good catch!

File: extensions/arc/deployment/src/test/java/io/quarkus/arc/test/deployment/TestInvalidPostConstruct.java (hunk 2 above)
Comment (cescoffier) [reply extensions/arc/deployment/src/test/java/io/quarkus/arc/test/deployment/TestInvalidPostConstruct.java:16]: Let me try to move them.

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Beans.java [hunk 4]
```diff
@@ -795,13 +795,21 @@ private static void fetchType(Type type, BeanDeployment beanDeployment) {
...
         for (MethodInfo method : clazz.methods()) {
-            if (method.returnType().kind() == Kind.VOID && method.parameterTypes().isEmpty()) {
-                if (method.hasAnnotation(annotation) && !knownMethods.contains(method.name())) {
+            if (method.hasAnnotation(annotation) && !knownMethods.contains(method.name())) {
+                if (method.returnType().kind() == Kind.VOID && method.parameterTypes().isEmpty()) {
                     callbacks.add(method);
+                } else {
+                    // invalid signature - build a meaningful message.
+                    StringBuilder name = new StringBuilder(method.declaringClass() + "." + method.name() + "(");
+                    String params = method.parameters().stream().map(pi -> pi.type().name().toString())
```
Comment (mkouba) [inline independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Beans.java:804]: How about something like `method.parameterTypes().forEach(name::append)`? I know it's nitpicking... but this way we don't even need the lambda.

**Comment by mkouba** [comment]
One last comment, otherwise looks perfect!

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Beans.java (hunk 4 above)
Comment (cescoffier) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Beans.java]: It won't work; I need to join the parameter correctly (with `,`). 
I can use `String.join`, but that will require creating an intermediary list with the type names.

I've pushed another version using `MethodInfo.toString()`. Unfortunately, we lose navigability - the IDE won't open the class, but we avoid the lambda.

Comment (mkouba) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Beans.java]: Hm, and why not just `name.append(method.parametersTypes())`? That should be good enough, or?

**Review by mkouba — APPROVED** [review]

**Comment by cescoffier** [comment]
@mkouba do you think we should backport it?
