### PR TITLE
Fix opening in IDE when more than IDE is running

### LINKED ISSUE #23002: if more than two running IDE while launching 'x' gives error
### Describe the bug

when more than one IDE is running , i.e. both code and eclipse then no ide is chosen and npe happens.

using 

```
//usr/bin/env jbang "$0" "$@" ; exit $?
//DEPS io.quarkus.platform:quarkus-bom:2.6.1.Final@pom
//DEPS io.quarkus:quarkus-resteasy

//JAVAC_OPTIONS -parameters

import io.quarkus.runtime.Quarkus;
import javax.enterprise.context.ApplicationScoped;
import javax.ws.rs.GET;
import javax.ws.rs.Path;

@Path("/hello-resteasy")
@ApplicationScoped
public class main {

    @GET
    public String sayHello() {
        throw new IllegalStateException("What up");
        
    }

    public static void main(String[] args) {
        Quarkus.run(args);
    }
}
```

with `jbang -Dquarkus.dev main.java` and visit http://localhost:8080/hello-resteasy and then use 'x' you get:

```
Exception in thread "Aesh InputStream Reader" java.lang.NullPointerException: Cannot invoke "io.quarkus.deployment.ide.EffectiveIdeBuildItem.getIde()" because "this.val$ideSupport" is null
	at io.quarkus.deployment.console.ConsoleProcessor$4.run(ConsoleProcessor.java:129)
	at io.quarkus.deployment.console.ConsoleStateManager$1.accept(ConsoleStateManager.java:73)
	at io.quarkus.deployment.console.ConsoleStateManager$1.accept(ConsoleStateManager.java:46)
	at io.quarkus.deployment.console.AeshConsole.lambda$setup$1(AeshConsole.java:201)
	at org.aesh.terminal.EventDecoder.accept(EventDecoder.java:118)
	at org.aesh.terminal.EventDecoder.accept(EventDecoder.java:31)
	at org.aesh.terminal.io.Decoder.write(Decoder.java:133)
	at org.aesh.readline.tty.terminal.TerminalConnection.openBlocking(TerminalConnection.java:216)
	at org.aesh.readline.tty.terminal.TerminalConnection.openBlocking(TerminalConnection.java:203)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

if only one IDE running  - all is fine. setting `quarkus.ide.target=xyz` fixes it

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #23002

### CODE REVIEW

File: core/deployment/src/main/java/io/quarkus/deployment/ide/IdeProcessor.java [hunk 1]
```diff
@@ -104,7 +104,7 @@ public EffectiveIdeBuildItem effectiveIde(LaunchModeBuildItem launchModeBuildIte
                     }
                     if (matches.size() == 1) {
                         result = matches.get(0);
-                    } else if (matches.size() == 0 && runningIdes.size() > 0) {
+                    } else if ((matches.size() == 0 && runningIdes.size() > 0) || matches.size() > 1) {
```
Comment (gastaldi) [inline core/deployment/src/main/java/io/quarkus/deployment/ide/IdeProcessor.java:107]:
```suggestion
                    } else if (matches.size() > 1 || runningIdes.size() > 0) {
```

Comment (gsmet) [reply core/deployment/src/main/java/io/quarkus/deployment/ide/IdeProcessor.java:107]: I think it would be better to short circuit the `runningIdes.size() == 0` case above at the start. Keeping it around is dangerous given we will do a `.next()`.

Comment (gastaldi) [reply core/deployment/src/main/java/io/quarkus/deployment/ide/IdeProcessor.java]: @gsmet good catch

**Review by gastaldi — APPROVED** [review]

**Review by gsmet — APPROVED** [review]

**Comment by geoand** [comment]
Merging as there are not any tests that test for this feature and the sanity check has passed
