### PR TITLE
Un-sign modified dependency JARs when filtering

### LINKED ISSUE #40000: Signed JARs may be modified during a native build
### Describe the bug

While working in https://github.com/quarkiverse/quarkus-jgit/issues/121, I noticed that Quarkus performs a filtering in the project dependencies, which in some cases may be a signed JAR, failing the build with a `SecurityException` (see https://github.com/quarkiverse/quarkus-jgit/issues/121#issuecomment-2040108853)

### Expected behavior

Do not modify signed JARs files or if modified, unsign them

### Actual behavior

The JAR is modified and the build fails with a SecurityException

### How to Reproduce?

See https://github.com/quarkiverse/quarkus-jgit/issues/121#issuecomment-2037899769

### Output of `uname -a` or `ver`

macOS m1

### Output of `java -version`

JDK 17

### Mandrel or GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

3.9.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by gastaldi**
This makes sure that the resulting JAR's signature is removed when transformed classes are filtered out.  

- Fixes #40000

### CODE REVIEW

**Review by appiepollo14 — APPROVED** [review]

**Comment by geoand** [comment]
Seems reasonable to me, but I am wondering if there is any way we can test it..

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/JarResultBuildStep.java [hunk 1]
```diff
@@ -1237,16 +1236,27 @@ private void handleParent(FileSystem runnerZipFs, String fileName, Map<String, S
...
-                try (ZipOutputStream out = new ZipOutputStream(new FileOutputStream(targetPath.toFile()))) {
-                    Enumeration<? extends ZipEntry> entries = in.entries();
+            try (JarFile in = new JarFile(resolvedDep.toFile(), false)) {
+                Manifest manifest = in.getManifest();
+                if (manifest != null) {
+                    // Remove signature entries
+                    manifest.getEntries().clear();
+                } else {
+                    manifest = new Manifest();
+                }
```
Comment (gsmet) [inline core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/JarResultBuildStep.java:1249]: Do we really want to drop everything in the manifest?

Comment (gastaldi) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/JarResultBuildStep.java:1249]: IIRC clearing the `getEntries()` map drops just the signature entries. The rest is kept because they are in the `getMainAttributes()`

File: core/deployment/src/test/java/io/quarkus/deployment/pkg/steps/JarResultBuildStepTest.java [hunk 2]
```diff
@@ -0,0 +1,29 @@
...
+import java.util.jar.JarEntry;
+import java.util.jar.JarFile;
+import java.util.jar.Manifest;
+
+import static org.assertj.core.api.Assertions.assertThat;
+
+class JarResultBuildStepTest {
+
+    @Test
+    void should_unsign_jar_when_filtered(@TempDir Path tempDir) throws Exception {
```
Comment (gastaldi) [inline core/deployment/src/test/java/io/quarkus/deployment/pkg/steps/JarResultBuildStepTest.java:17]: @geoand test added

**Review by galderz — COMMENTED** [review]
I'm unsure about having a binary signed jar checked into source control, given the recent issues with binary test files. I think it'd better if the signed jar could be generated as part of the test.

**Comment by gastaldi** [comment]
@galderz Yeah, I considered doing that but found the steps to create the signed JAR harder than the PR and test itself. Do you have a snippet I could reuse? 😝

**Comment by gastaldi** [comment]
@galderz now the binary is gone: I used the `maven-dependency-plugin` to download and copy the signed artifact to the test directory before running the test.

**Comment by galderz** [comment]
> @galderz now the binary is gone: I used the `maven-dependency-plugin` to download and copy the signed artifact to the test directory before running the test.

That's a certainly an improvement and enough to get this PR in, but I think it'd still be better to create one on the fly if possible (with Shrinkwrap?) and then sign it with some randomly generated keys? Maybe as a follow up?

**Comment by gastaldi** [comment]
Sure, that can be improved in a separate PR

**Comment by galderz** [comment]
> Sure, that can be improved in a separate PR

If you create a separate issue for it, it could maybe be a good-first-issue?

**Review by gsmet — APPROVED** [review]
