### PR TITLE
Arc - introduce built-in bean for injection point of type @All List<X>

### LINKED ISSUE #32080: Can't inject list of interfaces with wildcards twice into beans
### Describe the bug

ARC has a problem while resolving injection points for types with wilcards.
If create an parametirized interface and several implementation and after try to inject List (with All annotion) more than one time - ARC can't resolve syntetic bean more than one time.

More details with screenshoots in additional information.

### Expected behavior

Shold inject list of beans in any injection point.

### Actual behavior

If inject List in two or more beans will cause exception about unsatisfied dependency.

### How to Reproduce?

Example here https://github.com/insideworld/quarkusbug
Just try to build it using maven and take exception about Unsatisfied dependency.
If comment BeanB - all works fine.

Test case:
1. Need to create an interface with generic parameter.
2. Create two or more implementation of generic interface and mark it as singleton.
3. Create two or more independed beans and try to inject list of interfaces with all annotation.
4. Try to build it or launch.

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

java version "17.0.5" 2022-10-18 LTS

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

3.0.0.Beta1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)

### Additional information

ARC try to resolve bean at first iteration in io.quarkus.arc.processor.Beans#resolveInjectionPoint and found possible syntetic bean to inject.
In io.quarkus.arc.processor.BeanResolverImpl#matchesNoBoxing all good because comparation by reference get true:
image

But in the second (and other) times when ARC try to compare 2 types, references are different:
image

After some recursive operation, arc try to resolve wildcards types:
image
But here we don't have comparation by references or comparation by 2 wildcards and validation return negative result.

### PR DESCRIPTION
**Pull request by manovotn**
Fixes https://github.com/quarkusio/quarkus/issues/32080

Adds built-in bean for any `@Inject @All List<Foo>` or `@Inject @All List<InstanceHandle<Foo>>`.
This is a replacement for the original attempt at https://github.com/quarkusio/quarkus/pull/32158 as that one was insufficient in addressing bound wildcards.

### CODE REVIEW

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ArcProcessor.java [hunk 1]
```diff
@@ -895,18 +827,11 @@ public void registerField(FieldInfo fieldInfo) {
                 reflectionRegistration.registerMethod(injectionPoint.getTarget().asMethod());
```
Comment (mkouba) [inline extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ArcProcessor.java:827]: We could move the registration to the `BuiltinBean.generateListBytecode()` because of `BuiltinBean.GeneratorContext.reflectionRegistration`.

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ArcProcessor.java [hunk 2]
```diff
@@ -895,18 +827,11 @@ public void registerField(FieldInfo fieldInfo) {
...
             }
 
-            AnnotationInstance identifiedAnnotation = injectionPoint.getRequiredQualifier(DotNames.IDENTIFIED);
-            if (identifiedAnnotation == null
-                    // The id is a hash of "type + all annotations" - if there's an exact match then we don't need to add another bean
-                    || !ids.add(identifiedAnnotation.value().asString())) {
```
Comment (mkouba) [inline extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ArcProcessor.java:901]: We should also remove the `ids` local variable.

Comment (mkouba) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ArcProcessor.java:901]: `annotationLiterals` is also unused...

File: extensions/arc/deployment/src/test/java/io/quarkus/arc/test/lookup/ListInjectionTest.java [hunk 3]
```diff
@@ -23,6 +23,7 @@
 import io.quarkus.arc.Arc;
 import io.quarkus.arc.InstanceHandle;
 import io.quarkus.arc.Priority;
+import io.quarkus.arc.Unremovable;
 import io.quarkus.test.QuarkusUnitTest;
 
 public class ListInjectionTest {
```
Comment (mkouba) [inline extensions/arc/deployment/src/test/java/io/quarkus/arc/test/lookup/ListInjectionTest.java:29]: I think that we should also extend the `io.quarkus.arc.test.all.ListAllTest` from the `arc-tests` module.

**Review by mkouba — COMMENTED** [review]
We should also rename the `registerListInjectionPointsBeans()` method...

File: extensions/arc/deployment/src/test/java/io/quarkus/arc/test/lookup/ListInjectionTest.java (hunk 3 above)
Comment (manovotn) [reply extensions/arc/deployment/src/test/java/io/quarkus/arc/test/lookup/ListInjectionTest.java:29]: In what manner exactly? Basically keeping them 1:1 in what they test?

Comment (mkouba) [reply extensions/arc/deployment/src/test/java/io/quarkus/arc/test/lookup/ListInjectionTest.java:29]: Yes, just add the `@Injec @All` variant there...

**Comment by Ladicek** [comment]
I don't have a lot of comments, because I only briefly skimmed through this, but 2 things stand out:

1. Do we maybe also want to remove the `Identified` annotation?
2. The test doesn't really check that wildcards are resolved correctly. We only have beans of type `Some<String>` (and `Some<Integer>`) in the test, which is not enough. I'd suggest to have beans of type `Some<Integer>`, `Some<Number>`, `Some<Object>` and `Some<String>`. Then `Some<?>` resolves to all of them, `Some<? extends Number>` resolves to `Some<Number>` and `Some<Integer>`, and `Some<? super Integer>` resolves to `Some<Object>`, `Some<Number>` and `Some<Integer>`.

**Comment by mkouba** [comment]
> 1. Do we maybe also want to remove the `Identified` annotation?

-1.  It's not a part of public API anyway. I know that we can use `io.smallrye.common.annotation.Identifier` but I'm not sure we want to keep the dependency on `io.smallrye.reactive:mutiny` which transitively brings in `smallrye-common-annotation`.

>2. The test doesn't really check that wildcards are resolved correctly.

+1

File: extensions/arc/deployment/src/test/java/io/quarkus/arc/test/lookup/ListInjectionTest.java (hunk 3 above)
Comment (manovotn) [reply extensions/arc/deployment/src/test/java/io/quarkus/arc/test/lookup/ListInjectionTest.java:29]: Done, added a test.

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ArcProcessor.java (hunk 1 above)
Comment (manovotn) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ArcProcessor.java]: Moved the code, although I am not totally clear on why we need the registration (unconditionally) :shrug:

**Comment by manovotn** [comment]
@mkouba @Ladicek I believe I have addressed all the comments here, please re-review :)

**Review by Ladicek — APPROVED** [review]

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ArcProcessor.java (hunk 1 above)
Comment (mkouba) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ArcProcessor.java]: I believe that it's because of the injection point metadata. We could optimize this later...

**Comment by mkouba** [comment]
> We should also rename the `registerListInjectionPointsBeans()` method...

@manovotn :pray:

**Comment by manovotn** [comment]
None of the CI failures look related.
@mkouba if you are fine with the current state, I'd like to merge this.

**Comment by mkouba** [comment]
> None of the CI failures look related. @mkouba if you are fine with the current state, I'd like to merge this.

:+1:

**Review by mkouba — APPROVED** [review]
