### PR TITLE
Missing sourceSets for Kotlin in Project Descriptor

### LINKED ISSUE #43242: Gradle - kotlin classes missing from the jar
### Describe the bug

Kotlin classes are missing from the jar used for the docker build

I created a new project on https://code.quarkus.io/ using 
- Gradle with kotlin dsl
- Java 21
- Starter Code
- Extensions: Rest and Kotlin

Using the dev server I can access the GreetRessource, however, when I build a docker image(Dockerfile.jvm) I get the "Resource not found" message.

When adding a new endpoint using a java class the endpoint is both accessible using the dev server and the docker image

### Expected behavior

Kotlin and Java resources should work

### Actual behavior

Kotlin resources are missing

### How to Reproduce?

https://github.com/kesslerd/kotlin-docker-test 

1. create a docker image based on https://github.com/kesslerd/kotlin-docker-test/blob/main/src/main/docker/Dockerfile.jvm 
2. Check if the endpoints /hello and /hello-java work

### Output of `uname -a` or `ver`

23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk 21.0.4 2024-07-16 LTS
OpenJDK Runtime Environment Zulu21.36+17-CA (build 21.0.4+7-LTS)
OpenJDK 64-Bit Server VM Zulu21.36+17-CA (build 21.0.4+7-LTS, mixed mode, sharing)

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.8

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by cdsap**
SourceSets for the Kotlin tasks were not included in the `ProjectDescriptorBuilder` (my mistake).

This PR adds a new integrating test to verify that the Kotlin classes have been included in the jar. 

Additional tests:
Comparing 3.13.1 vs 314.3, diff in the Kotlin classes:
Screenshot 2024-09-16 at 8 04 45 PM

Comparing 3.13.1 vs This PR, no diff in the Kotlin classes:
Screenshot 2024-09-16 at 8 05 29 PM

- Fixes: #43242.

### CODE REVIEW

File: integration-tests/gradle/src/test/java/io/quarkus/gradle/KotlinIsIncludedInQuarkusJarTest.java [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+
+import java.io.File;
+import java.nio.file.Path;
+import java.util.Enumeration;
+import java.util.jar.JarEntry;
+import java.util.jar.JarFile;
+
+import org.junit.jupiter.api.Test;
+
+public class KotlinIsIncludedInQuarkusJarTest extends QuarkusGradleWrapperTestBase {
```
Comment (cdsap) [inline integration-tests/gradle/src/test/java/io/quarkus/gradle/KotlinIsIncludedInQuarkusJarTest.java:14]: in my fork, I created another branch to validate the purpose of this test by removing the included changes in `ProjectDescriptorBuilder`, the result is:
```
2024-09-17T02:32:37.0846761Z org.opentest4j.AssertionFailedError: Expected entry basic-kotlin-application-project/src/main/kotlin/org/acme/MyMainClass.class not found in JAR file. ==> expected: <true> but was: <false>
2024-09-17T02:32:37.0849523Z 	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
2024-09-17T02:32:37.0851336Z 	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
2024-09-17T02:32:37.0853003Z 	at org.junit.jupiter.api.AssertTrue.failNotTrue(AssertTrue.java:63)
2024-09-17T02:32:37.0854351Z 	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:36)
2024-09-17T02:32:37.0855760Z 	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:214)
2024-09-17T02:32:37.0857660Z 	at io.quarkus.gradle.KotlinIsIncludedInQuarkusJarTest.assertJarContainsEntry(KotlinIsIncludedInQuarkusJarTest.java:45)
2024-09-17T02:32:37.0860012Z 	at io.quarkus.gradle.KotlinIsIncludedInQuarkusJarTest.testFastJarFormatWorks(KotlinIsIncludedInQuarkusJarTest.java:28)
2024-09-17T02:32:37.0861883Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
2024-09-17T02:32:37.0863187Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
2024-09-17T02:32:37.0864658Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
2024-09-17T02:32:37.0866574Z 
```

[Log file](https://productionresultssa10.blob.core.windows.net/actions-results/7730bb96-5f1e-470a-b67a-d5eacc46d0d2/workflow-job-run-d902fd06-6a09-54f6-29ea-e4a86af45f77/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-09-17T03%3A15%3A43Z&sig=yXMHgSg5sOWGi2dYA%2FpbegOy43%2FJOpCiRLqP%2FVDLHic%3D&ske=2024-09-17T14%3A41%3A46Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2024-09-17T02%3A41%3A46Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2024-05-04&sp=r&spr=https&sr=b&st=2024-09-17T03%3A05%3A38Z&sv=2024-05-04)

**Comment by geoand** [comment]
Thanks a lot for this!

Slightly unrelated, what tool are you using to compare the jars from which you have captured the screenshots?

**Review by aloubyansky — APPROVED** [review]
Thanks a lot @cdsap !
