### PR TITLE
native-image: Graal's ForeignAPISupport is amd64 only

### LINKED ISSUE #46235: Native images fail to build on aarch64 mac with latest GraalVM master
Error:

```
Internal exception: com.oracle.svm.core.util.UserError$UserException: Support for the Foreign Function and Memory API is currently available only on the AMD64 architecture.
```

This is probably caused by the Quarkus code in https://github.com/quarkusio/quarkus/blob/main/core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java#L857-L865 combined with latest changes in GraalVM master.

### LINKED ISSUE #46988: Native image build fails on Mac M2 with GraalVM 24
### Describe the bug

When compiling my app to native binaries, starting with GraalVM 24, I get an error saying that support for the Foreign Function and Memory API not being available on the AMD64 architecture.
Is there a configuration I can use to disable this feature?

### Expected behavior

Compilation should be successful. It's working fine with GraalVM 21.

### Actual behavior

I get the following error:
```
[1/8] Initializing...
                                                                                    (0.0s @ 0.18GB)
Error: Support for the Foreign Function and Memory API is currently available only on the AMD64 architecture.
Internal exception: com.oracle.svm.core.util.UserError$UserException: Support for the Foreign Function and Memory API is currently available only on the AMD64 architecture.
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:85)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.guarantee(UserError.java:109)
        at org.graalvm.nativeimage.foreign/com.oracle.svm.hosted.foreign.ForeignFunctionsFeature.isInConfiguration(ForeignFunctionsFeature.java:135)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.registerFeature(FeatureHandler.java:240)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.registerFeatures(FeatureHandler.java:182)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:946)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:565)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:533)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:545)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:732)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:151)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:99)
```

### How to Reproduce?

Reproducible with this project: https://github.com/Endava/cats

Run a `mvn clean package -Pnative`.

### Output of `uname -a` or `ver`

Darwin ENM9MJH4TWXP 23.6.0 Darwin Kernel Version 23.6.0: Thu Sep 12 23:36:12 PDT 2024; root:xnu-10063.141.1.701.1~1/RELEASE_ARM64_T6020 arm64

### Output of `java -version`

Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 24+36.1 (build 24+36-jvmci-b01, mixed mode, sharing)

### Mandrel or GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

3.19.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.4 (dfbb324ad4a7c8fb0bf182e6d91b0ae20e3d2dd9)

### Additional information

When using GraalVM 24 the `-H:+ForeignAPISupport`  is passed in the native image step:

```
~/.sdkman/candidates/java/24-graal/bin/native-image -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dlogging.initial-configurator.min-level=500 -J-Duser.language=en -J-Duser.country=RO -H:+UnlockExperimentalVMOptions -H:IncludeLocales=en-RO -H:-UnlockExperimentalVMOptions -J-Dfile.encoding=UTF-8 -J--add-exports=org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk=ALL-UNNAMED --features=io.quarkus.runner.Feature,io.quarkus.runtime.graal.DisableLoggingFeature,io.quarkus.runtime.graal.SkipConsoleServiceProvidersFeature -J--add-exports=java.security.jgss/sun.security.krb5=ALL-UNNAMED -J--add-exports=java.security.jgss/sun.security.jgss=ALL-UNNAMED -J--add-opens=java.base/java.text=ALL-UNNAMED -J--add-opens=java.base/java.io=ALL-UNNAMED -J--add-opens=java.base/java.lang.invoke=ALL-UNNAMED -J--add-opens=java.base/java.util=ALL-UNNAMED -H:+UnlockExperimentalVMOptions -H:BuildOutputJSONFile=cats-runner-build-output-stats.json -H:-UnlockExperimentalVMOptions -H:+UnlockExperimentalVMOptions -H:+GenerateBuildArtifactsFile -H:-UnlockExperimentalVMOptions -H:+UnlockExperimentalVMOptions -H:+AllowFoldMethods -H:-UnlockExperimentalVMOptions -H:+UnlockExperimentalVMOptions -H:+ForeignAPISupport -H:-UnlockExperimentalVMOptions -J-Djava.awt.headless=true --no-fallback --link-at-build-time -H:+UnlockExperimentalVMOptions -H:+ReportExceptionStackTraces -H:-UnlockExperimentalVMOptions -H:-AddAllCharsets --enable-url-protocols=http --enable-monitoring=heapdump -H:+UnlockExperimentalVMOptions -H:-UseServiceLoaderFeature -H:-UnlockExperimentalVMOptions -J--add-exports=org.graalvm.nativeimage/org.graalvm.nativeimage.impl=ALL-UNNAMED cats-runner -jar cats-runner.jar
```

### PR DESCRIPTION
**Pull request by Karm**
Fixes #46235
Fixes #46988

Summary:

* We don't have MacOS support for AWT extension yet. It might be trivial, but it's not coded in yet, so the extension needs to bail out just like on Windows. I am afraid that not having MacOS excluded via `UnsupportedOSBuildItem` is an artifact of moving DarwinFeature to AWT extension. The result is that the **build** might pass, but the Quarkus app **won't start**. If that is the desired design, we should allow the same on Windows and remove its `UnsupportedOSBuildItem`. I think the DarwinFeature previously was in core on purpose, to allow for building apps that effectively won't need to initialize AWT at runtime, i.e. don't need full AWT extension.  @zakkak ? Ideas?

* GraalVM has FFI/FFM implemented for amd64 arch only, so effectively starting Mandrel/GraalVM 24.2, i.e. Mandrel for JDK 24, we are **losing AWT support on Linux aarch64 where it used to work**

* UBI9's microdnf requires `-y`, so container tests hanged on `Is this ok [y/N]:`

* I tested all combinations that made sense to me and where I had access to HW, e.g. I skipped natively amd64 based MacOS. I used either our Mandrel 24.2 / JDK 24 ea builds or GraalVM CE 25 ea dev builds.

* :green_circle:  - run went as expected; spoiler alert: All runs went as expected.

# Tested

## Windows amd64 hosted :green_circle: 
**Expected:** :orange_circle: - SKIPPED, AWT Quarkus unsupported OS
**Actual:** :orange_circle:

```
C:\tmp\quarkus(issue-46235 -> origin)
λ mvnw verify -f integration-tests/pom.xml -pl awt  -Pnative
    -Dquarkus.native.container-build=false -Dquarkus.container-image.build=false -DskipITs=false

[ERROR] Caused by: java.lang.UnsupportedOperationException:
Windows AWT integration is not ready in Quarkus native-image and would result in java.lang.UnsatisfiedLinkError: no awt in java.library.path.
```

## Windows amd64 with Linux amd64 builder image :green_circle: 
**Expected:** :green_circle:
**Actual:**  :green_circle:

```
λ mvnw verify -f integration-tests/pom.xml -pl awt -Pnative 
    -Dquarkus.native.builder-image=quay.io/karmkarm/ubi9-quarkus-mandrel-builder-image:jdk-24-amd64
    -Dquarkus.native.container-build=true -Dquarkus.container-image.build=true 
...

Finished generating 'quarkus-integration-test-awt-999-SNAPSHOT-runner' in 15m 51s.
...
[INFO] [io.quarkus.container.image.docker.common.deployment.CommonProcessor]
Executing the following command to build image: 
'podman build -f C:\tmp\quarkus\integration-tests\awt\src\main\docker\Dockerfile.native -t karm/quarkus-integration-test-awt:999-SNAPSHOT C:\tmp\quarkus\integration-tests\awt'
...
INFO  [io.qua.tes.com.DefaultDockerContainerLauncher] (main) 
Executing "podman run --name quarkus-integration-test-GQcdk -i --rm -p 8081:8081 -p 8444:8444 --net=quarkus-integration-test-UNOtv --env QUARKUS_LOG_CATEGORY__IO_QUARKUS__LEVEL=INFO --env QUARKUS_HTTP_PORT=8081 --env QUARKUS_HTTP_SSL_PORT=8444 --env TEST_URL=http://localhost:8081 --env QUARKUS_PROFILE=prod --env QUARKUS_CONTAINER_IMAGE_BUILD=true --env QUARKUS_NATIVE_CONTAINER_BUILD=true --env QUARKUS_NATIVE_BUILDER_IMAGE=quay.io/karmkarm/ubi9-quarkus-mandrel-builder-image:jdk-24-amd64 karm/quarkus-integration-test-awt:999-SNAPSHOT"
...
[INFO] Tests run: 41, Failures: 0, Errors: 0, Skipped: 0

```

## MacOS aarch64 hosted :green_circle:
**Expected:** :orange_circle: - SKIPPED, AWT Quarkus unsupported OS
**Actual:** :orange_circle:

```
[ERROR] Caused by: java.lang.UnsupportedOperationException:
    MacOS AWT integration is not ready in Quarkus native-image and would result in
    java.lang.UnsatisfiedLinkError: Can't load library: awt | java.library.path = [.].,
    AWT needs JDK's JEP 454 FFI/FFM support and that is not available for AArch64 with GraalVM's native-image,
    see: https://www.graalvm.org/latest/reference-manual/native-image/native-code-interoperability/foreign-interface/#foreign-functions
```

## MacOS amd64 (via Rosetta) hosted :green_circle:
**Expected:** :orange_circle: - SKIPPED, AWT Quarkus unsupported OS
**Actual:** :orange_circle:

```
[ERROR] Caused by: java.lang.UnsupportedOperationException:
    MacOS AWT integration is not ready in Quarkus native-image and would result in
    java.lang.UnsatisfiedLinkError: Can't load library: awt | java.library.path = [.].
```

## MacOS amd64 with Linux amd64 builder

N/A - I don't have access to such HW and I don't want to try to
remove Podman machine from my MacOS aarch64 systems and try to run
podman there via Rosetta. It should work just like Windows above :-)

## MacOS aarch64 with Linux aarch64 builder image :green_circle:
**Expected:** :orange_circle: - SKIPPED, ForeignAPISupport is amd64 only
**Actual:** :orange_circle:

```
[ERROR] Caused by: java.lang.UnsupportedOperationException:
    AWT needs JDK's JEP 454 FFI/FFM support and that is not available for AArch64 with GraalVM's native-image,
    see: https://www.graalvm.org/latest/reference-manual/native-image/native-code-interoperability/foreign-interface/#foreign-functions
```

## Linux amd64 hosted :green_circle:
**Expected:** :green_circle:
**Actual:** :green_circle:

```
$ ./mvnw verify -f integration-tests/pom.xml -pl awt  -Pnative
    -Dquarkus.native.container-build=false -Dquarkus.container-image.build=false -DskipITs=false 
OK
```

## Linux amd64 with Linux amd64 builder image :green_circle:
**Expected:** :green_circle:
**Actual:** :green_circle:

```
$ ./mvnw verify -f integration-tests/pom.xml -pl awt -Pnative
    -Dquarkus.native.builder-image=quay.io/karmkarm/ubi9-quarkus-mandrel-builder-image:jdk-24-amd64
    -Dquarkus.native.container-build=true -Dquarkus.container-image.build=true
OK
```

## Linux aarch64 hosted :green_circle:
**Expected:** :orange_circle: - SKIPPED, ForeignAPISupport is amd64 only
**Actual:** :orange_circle:

```
$ ./mvnw verify -f integration-tests/pom.xml -pl awt  -Pnative
    -Dquarkus.native.container-build=false -Dquarkus.container-image.build=false -DskipITs=false 

[ERROR] Caused by: java.lang.UnsupportedOperationException:
    AWT needs JDK's JEP 454 FFI/FFM support and that is not available for AArch64 with GraalVM's native-image,
    see: https://www.graalvm.org/latest/reference-manual/native-image/native-code-interoperability/foreign-interface/#foreign-functions
```

## Linux aarch64 with Linux aarch64 builder image :green_circle:
**Expected:** :orange_circle: - SKIPPED, ForeignAPISupport is amd64 only
**Actual:** :orange_circle:

```
$ ./mvnw verify -f integration-tests/pom.xml -pl awt -Pnative
    -Dquarkus.native.builder-image=quay.io/karmkarm/ubi9-quarkus-mandrel-builder-image:jdk-24-aarch64
    -Dquarkus.native.container-build=true -Dquarkus.container-image.build=true -DskipITs=false

[ERROR] Caused by: java.lang.UnsupportedOperationException:
    AWT needs JDK's JEP 454 FFI/FFM support and that is not available for AArch64 with GraalVM's native-image,
    see: https://www.graalvm.org/latest/reference-manual/native-image/native-code-interoperability/foreign-interface/#foreign-functions
```

Thanks for feedback

### CODE REVIEW

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java [hunk 1]
```diff
@@ -855,12 +857,15 @@ public NativeImageInvokerInfo build() {
...
                  * Foreign Function and Memory API in Native Image, JDK's JEP 454
                  * This is needed for JDK 24+ internal native calls due to AWT,
                  * e.g. JDK-8337237 et al.
-                 *
+                 * Note GraalVM FFI/FFM support per platform:
+                 * https://www.graalvm.org/latest/reference-manual/native-image/native-code-interoperability/foreign-interface/#foreign-functions
+                 * @formatter:on
                  */
-                if (graalVMVersion.compareTo(GraalVM.Version.VERSION_24_2_0) >= 0) {
+                if (graalVMVersion.compareTo(GraalVM.Version.VERSION_24_2_0) >= 0 && AMD64.active) {
```
Comment (zakkak) [inline core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java:868]: Given that we now handle AArch64 as unsupported, under which configuration do you expect to reach this? I would expect the build to fail sooner than this.

**Review by zakkak — APPROVED** [review]
LGTM.

>  I think the DarwinFeature previously was in core on purpose, to allow for building apps that effectively won't need to initialize AWT at runtime, i.e. don't need full AWT extension.

By `DarwinFeature` are you referring to https://github.com/quarkusio/quarkus/blob/main/extensions/awt/runtime/src/main/java/io/quarkus/awt/runtime/graal/DarwinAwtFeature.java ?

AFAIS it was always under the awt extension https://github.com/quarkusio/quarkus/pull/21566

> The result is that the build might pass, but the Quarkus app won't start. If that is the desired design,

No, I don't think this is desired. Reporting it as unsupported seems the right thing to me.

> GraalVM has FFI/FFM implemented for amd64 arch only, so effectively starting Mandrel/GraalVM 24.2, i.e. Mandrel for JDK 24, we are losing AWT support on Linux aarch64 where it used to work

We will need to list this as a known issue, in the migration guide I guess.

> UBI9's microdnf requires `-y`, so container tests hanged on `Is this ok [y/N]:`

Good catch, I think we need this in ASAP. So if this PR ends up being delayed I would suggest openning a separate PR with just 1de05f29046ad663704bcbd6e96b7c8f0ccff9d4

Thank you @Karm

**Comment by gsmet** [comment]
@Karm could you create a specific PR for the `microdnf` changes? This is something we want to backport right away. The rest of the PR requires more thoughts.

**Comment by Karm** [comment]
> @Karm could you create a specific PR for the `microdnf` changes? This is something we want to backport right away. The rest of the PR requires more thoughts.

@gsmet 

https://github.com/quarkusio/quarkus/pull/46763

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java (hunk 1 above)
Comment (Karm) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java:868]: I am not sure I follow. It is not AWT specific, it's just that AWT was the first obvious hit. 
AMD64 Linux, Windows and also MacOS are able to use [FFI/FFM](https://www.graalvm.org/latest/reference-manual/native-image/native-code-interoperability/foreign-interface/#foreign-functions).

e.g. if jline hadn't some other issue, this would have made it work on Windows amd64.

Comment (Karm) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java:868]: >  I would expect the build to fail sooner than this.

Build doesn't fail, it just doesn't include the unsupported feature, flag.

Comment (Karm) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java:868]: It's the AWT extension that actively fails the build with an error message *if* you happen to use AWT extension.

**Comment by Karm** [comment]
> The rest of the PR requires more thoughts.

@gsmet , any specific pointers?

**Comment by zakkak** [comment]
> Do I just edit this directly or is it generated?

Directly

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java (hunk 1 above)
Comment (zakkak) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java:868]: Uh right we are always enabling FFM not just for AWT. Sorry for the noise.

**Comment by brunobat** [comment]
> No idea why would Micrometer get flaky on this PR. Do you understand the CI results @ebullient @brunobat?

Nope.

**Comment by zakkak** [comment]
@gsmet I would only consider the part that handles

> We don't have MacOS support for AWT extension yet. It might be trivial, but it's not coded in yet, so the extension needs to bail out just like on Windows.

for backporting, but IMO it's not worth it.

**Comment by zakkak** [comment]
@Karm it looks like AArch64 support will land in GraalVM for JDK 25, see https://github.com/oracle/graal/pull/10856

**Comment by Karm** [comment]
@gsmet 

> @Karm sorry, it was "more thoughts" as "if it was safe to be backported or not" :). Do you think we need a backport for this one?

I don't think so.

**Comment by Karm** [comment]
> @Karm it looks like AArch64 support will land in GraalVM for JDK 25, see [oracle/graal#10856](https://github.com/oracle/graal/pull/10856)

Aww, great.  Gonna give their branch a shot.  I will make a note to see to removing these if-else version checks for 25 if it's sound.

**Comment by Karm** [comment]
@zakkak 

Migration guide updated as https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.19/_compare/8ffa458b7951b8da1e26a86958243dd6edb4b55d...0d6004747c902b7e230e8e8a3209c765d6e8266c

**Comment by zakkak** [comment]
> @zakkak
> 
> Migration guide updated as https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.19/_compare/8ffa458b7951b8da1e26a86958243dd6edb4b55d...0d6004747c902b7e230e8e8a3209c765d6e8266c

@karm there is a typo in your update "To switch back to UBI 8" suggests using ubi9

Furthermore, we need to add a note about

> GraalVM has FFI/FFM implemented for amd64 arch only, so effectively starting Mandrel/GraalVM 24.2, i.e. Mandrel for JDK 24, we are losing AWT support on Linux aarch64 where it used to work

**Comment by Karm** [comment]
> > @zakkak
> > Migration guide updated as https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.19/_compare/8ffa458b7951b8da1e26a86958243dd6edb4b55d...0d6004747c902b7e230e8e8a3209c765d6e8266c
> 
> @Karm there is a typo in your update. "To switch back to UBI 8" suggests using ubi9
> 
> Furthermore, we need to add a note about
> 
> > GraalVM has FFI/FFM implemented for amd64 arch only, so effectively starting Mandrel/GraalVM 24.2, i.e. Mandrel for JDK 24, we are losing AWT support on Linux aarch64 where it used to work

1)  gonna fix copy-paste typo
2) I'm waiting for my build to test AWT with the recently merged FFM/FFI aarch64 JDK 25 support, gonna update text presently

**Comment by Karm** [comment]
@zakkak @gsmet 

AWT Linux aarch64 note regarding JDK 24:

https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.19/_compare/2ae1c89052997e6679e3e970035f8b5cd02c5395...7b5faaeccbec05c436d19fb8f0f940a381376d72

**Comment by zakkak** [comment]
Thank you @Karm

**Comment by Karm** [comment]
@zakkak @gsmet added backport label to help with adopting JDK 24.

**Comment by Karm** [comment]
JDK 25 won't have this limitation any more though...
