### PR TITLE
Fixed recordedBuildConfigFile absolute path resolution

### LINKED ISSUE #46726: quarkus.config-tracking.file-suffix does not work as expected
### Describe the bug

When configuring `quarkus.config-tracking.file-suffix` with Quarkus 3.8.6, the `quarkus-prod-config-check` file is not identical to the one generated with the default file suffix (`-config-dump`)
This prevents the https://github.com/gradle/quarkus-build-caching-extension to provide build cache hits with the Develocity extension

### Expected behavior

When building twice in a row a Quarkus project using 3.8.6, `.quarkus/quarkus-prod-foo-bar` and `target/quarkus-prod-config-check` should be identical

### Actual behavior

The two files have some differences 

Image

### How to Reproduce?

Clone https://github.com/jprinet/helm-quickstart and build it twice:
```
./mvnw clean package -Pcustom-suffix
./mvnw clean package -Pcustom-suffix
```

### Output of `uname -a` or `ver`

Darwin NJ7NXYPHH7 24.3.0 Darwin Kernel Version 24.3.0: Thu Jan  2 20:24:23 PST 2025; root:xnu-11215.81.4~3/RELEASE_ARM64_T6020 arm64 arm Darwin

### Output of `java -version`

openjdk version "17.0.6" 2023-01-17 LTS OpenJDK Runtime Environment (build 17.0.6+10-LTS) OpenJDK 64-Bit Server VM (build 17.0.6+10-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.8.6

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.9 (8e8579a9e76f7d015ee5ec7bfcdc97d260186937) Maven home: /Users/jprinet/.m2/wrapper/dists/apache-maven-3.9.9-bin/33b4b2b4/apache-maven-3.9.9 Java version: 17.0.6, vendor: BellSoft, runtime: /Users/jprinet/.asdf/installs/java/liberica-17.0.6+10 Default locale: en_US, platform encoding: UTF-8 OS name: "mac os x", version: "15.3.1", arch: "aarch64", family: "mac"

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by aloubyansky**
Fixes https://github.com/quarkusio/quarkus/issues/46726

### CODE REVIEW

File: devtools/maven/src/main/java/io/quarkus/maven/TrackConfigChangesMojo.java [hunk 1]
```diff
@@ -177,6 +168,19 @@ protected void doExecute() throws MojoExecutionException, MojoFailureException {
         }
     }
 
+    private Path resolvePreviousBuildConfigDump(LaunchMode launchMode) {
+        final Path previousBuildConfigDump = this.recordedBuildConfigFile == null ? null
+                : Path.of(this.recordedBuildConfigFile);
+        if (previousBuildConfigDump == null) {
+            return recordedBuildConfigDirectory.toPath()
+                    .resolve("quarkus-" + launchMode.getDefaultProfile() + "-config-dump");
```
Comment (gsmet) [inline devtools/maven/src/main/java/io/quarkus/maven/TrackConfigChangesMojo.java:176]: I was having a look at the original issue and is it expected we are not taking into account  `quarkus.config-tracking.file-suffix`?

Comment (aloubyansky) [reply devtools/maven/src/main/java/io/quarkus/maven/TrackConfigChangesMojo.java:176]: We could. We'd need to refactor the current implementation further to do that.
It will come at a cost of always resolving the the build time config and bootstrap the app even on the first build (when the config dump from the previous build does not exist, since we will not know about that).

Comment (gsmet) [reply devtools/maven/src/main/java/io/quarkus/maven/TrackConfigChangesMojo.java:176]: Does it make sense to have a config property for it if we can't honor it?

Comment (aloubyansky) [reply devtools/maven/src/main/java/io/quarkus/maven/TrackConfigChangesMojo.java:176]: No, it's used but by the process dumping the used config options during the build. This mojo is another client that reads that file. So all the options are actually used.
I think you had a good point though, we could potentially re-use the same option used by the build process in this mojo.
Perhaps we could keep the existing one but use it only if a user configured values explicitly.

Comment (gsmet) [reply devtools/maven/src/main/java/io/quarkus/maven/TrackConfigChangesMojo.java:176]: > No, it's used but by the process dumping the used config options during the build.

Yeah, I had that in mind but does it make sense to make it configurable if it's hard to propagate this config everywhere?

What's the value of allowing people to adjust the suffix?

Comment (jprinet) [reply devtools/maven/src/main/java/io/quarkus/maven/TrackConfigChangesMojo.java:176]: Exactly, when using the [quarkus-build-caching-extension](https://github.com/gradle/quarkus-build-caching-extension/) to make the Quarkus `build` goal cacheable, a recommendation is to check in the dump config in the Git repository.
You may have several versions of this dump config depending on several factors (os, arch...)

**Review by gsmet — APPROVED** [review]
Feel free to merge this. I'm just unsure it actually solves the initial issue, even if it's a step in the right direction.

**Comment by aloubyansky** [comment]
I'd say it fixes the issue taking the current design into account. We could look into config re-use as a follow up enhancement.
