### PR TITLE
Scheduler: OTel Instrumentation feature improvements and refactoring

### LINKED ISSUE #28552: traceId, spanId not set in logs when using quartz and opentelemetry
### Describe the bug

I use quarkus-quartz and quarkus-opentelemetry

Have definded a custom log format like in https://quarkus.io/guides/opentelemetry#create-the-configuration

```
quarkus.log.console.format=%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n
```

### Expected behavior

Expected that traceId etc. are filled, (this only works for rest resource), see:

```
  00:16:43 INFO  traceId=7d79594584b49a7db88f47c75a0cd185, parentId=, spanId=cb9d17786f3ed0c0, sampled=true [or.ac.qu.TaskResource] (executor-thread-0) log test
```

### Actual behavior

But for log output in quartz scheduled method everything is empty

```
00:16:45 INFO  traceId=, parentId=, spanId=, sampled= [or.ac.qu.TaskBean] (QuarkusQuartzScheduler_Worker-3) log test
```

### How to Reproduce?

https://github.com/syr/quartz-otel-logs is based on latest quartz-quickstart code.

Only needs to be started, scheduler runs every 10 seconds printing log lines without traceId etc.

Calling http://localhost:8080/tasks  shows that it works generally, but only for rest resources

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

 java -version openjdk version "17.0.2" 2022-01-18 OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8) OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode, sharing)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.13.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8.1

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mskacelik**
/cc @brunobat 
fixes: #28552
draft PR

I have Added OTel Instrumentation for quartz scheduling.
Currently there are two types of scheduling in quartz:
### Using the annotation `@Schedule`
For this type of scheduling there seems to be already existing feature for creating spans. Yet I feel that my implementation might be better because the spans contains information about the name of the executed method + duration of the method.
     
image
> [NOTE] the first span (the top one) is my implementation which contains name of the method which was executed + duration `Thread.sleep(1000l);`
The second span (the bottom one) is the current implementation which will be activated when using property `quarkus.scheduler.tracing.enabled=true`

For some reason with my implemetation I cannot log `traceId` and `spanId` inside the executed method even tho span has been created (gonna have a look at it in a meantime).

### Using Quartz API (Programmatic) 
I have created feature which enables OTel instrumentation for each Job.
Currently the span creating is enabled by default if it finds the OTel extension in the project, but maybe we could use the property `quarkus.scheduler.tracing.enabled=true` for explicit enabling (like the current `@Schedule` approach).
Logging `traceId` + `spanId` works.

Basis for the code: https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/quartz-2.0/library/src/main/java/io/opentelemetry/instrumentation/quartz/v2_0

>[NOTE]: In the issue's reproducer there were few errors for the use of programmatic style scheduling like: 
>* not using injected scheduler (using the factory)
> * not having property for forced start

### Tests
Currently missing.

### CODE REVIEW

**Comment by mskacelik** [comment]
Update:

Ok by double checking it seems that my implementation is the faulty one using the scheduler with `@Schedule` approach and the adding  `@WithSpan` via `quarkus.scheduler.tracing.enabled=true` which we have currently works as intended. But when it comes to programmatic scheduler my implementation works.

File: extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/tracing/WithSpanJob.java [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+
+public class WithSpanJob implements Job {
+    private final Job delegate;
+
+    private final Instrumenter<JobExecutionContext, Void> instrumenter;
+
+    public WithSpanJob(Job delegate, boolean captureExperimentalSpanAttributes) {
+        this.delegate = delegate;
+        InstrumenterBuilder<JobExecutionContext, Void> jobInstrumenterBuilder = Instrumenter.builder(
+                CDI.current().select(OpenTelemetry.class).get(), "io.quarkus.opentelemetry",
```
Comment (mkouba) [inline extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/tracing/WithSpanJob.java:26]: It might make more sense to add an `OpenTelemetry` parameter to the constructor and provide the instance in the component that instantiates `WithSpanJob`...

File: extensions/scheduler/common/src/main/java/io/quarkus/scheduler/common/runtime/WithSpanInvoker.java [hunk 2]
```diff
@@ -0,0 +1,50 @@
...
+import io.opentelemetry.instrumentation.api.instrumenter.SpanNameExtractor;
+import io.quarkus.scheduler.ScheduledExecution;
+
+public class WithSpanInvoker extends DelegateInvoker {
+    private final Instrumenter<ScheduledExecution, Void> instrumenter;
+
+    public WithSpanInvoker(ScheduledInvoker delegate) {
+        super(delegate);
+        InstrumenterBuilder<ScheduledExecution, Void> instrumenterBuilder = Instrumenter.builder(
+                CDI.current().select(OpenTelemetry.class).get(), "io.quarkus.opentelemetry",
```
Comment (mkouba) [inline extensions/scheduler/common/src/main/java/io/quarkus/scheduler/common/runtime/WithSpanInvoker.java:22]: Again, try to avoid `CDI.current().select()` if possible..

File: extensions/scheduler/runtime/src/main/java/io/quarkus/scheduler/runtime/SimpleScheduler.java [hunk 3]
```diff
@@ -695,6 +706,13 @@ public boolean isBlocking() {
             return null;
         }
 
+        private boolean isOTelTracingEnabled() {
+            return ConfigProvider.getConfig().getValue("quarkus.otel.enabled", Boolean.class);
+        }
+
+        private boolean isOTelExtensionAvailable() {
+            return CDI.current().select(io.opentelemetry.api.OpenTelemetry.class).isResolvable();
```
Comment (mkouba) [inline extensions/scheduler/runtime/src/main/java/io/quarkus/scheduler/runtime/SimpleScheduler.java:714]: I would try to avoid using `CDI.current().select(OpenTelemetry.class)` at all. In this particular case, I would just add the `Instance<OpenTelemetry>` injection point in the `SimpleScheduler` and use it here.

File: extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzSchedulerImpl.java [hunk 4]
```diff
@@ -757,6 +766,14 @@ private Optional<TriggerBuilder<?>> createTrigger(String identity, Scheduled sch
         return Optional.of(triggerBuilder);
     }
 
+    private static boolean isOTelTracingEnabled() {
+        return ConfigProvider.getConfig().getValue("quarkus.otel.enabled", Boolean.class);
+    }
+
+    private static boolean isOTelExtensionAvailable() {
+        return CDI.current().select(io.opentelemetry.api.OpenTelemetry.class).isResolvable();
```
Comment (mkouba) [inline extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzSchedulerImpl.java:774]: I would try to avoid using `CDI.current().select(OpenTelemetry.class)` at all. In this particular case, I would just add the `Instance<OpenTelemetry>` injection point in the SimpleScheduler and use it here.

**Review by radcortez — CHANGES_REQUESTED** [review]
I'm concerned about giving visibility to OTel APIs into other extensions. Until now, we have tried to concentrate every OTel integration in the OTel extension. Because it is an optional dependency, these hacky workarounds are required to check if the OTel bean is available. 

I think it would be better to introduce a SPI Build Item that allows other extensions to customize the current extension (if Quarts or Schedule do not have another way already).  

For instance, we use a RESTEasy Reactive build item to register additional filters and do the OTel work, so RESTEasy doesn't have to know about OTel.

//cc @brunobat

**Comment by brunobat** [comment]
> I'm concerned about giving visibility to OTel APIs into other extensions. Until now, we have tried to concentrate every OTel integration in the OTel extension. Because it is an optional dependency, these hacky workarounds are required to check if the OTel bean is available.
> 
> I think it would be better to introduce a SPI Build Item that allows other extensions to customize the current extension (if Quarts or Schedule do not have another way already).
> 
> For instance, we use a RESTEasy Reactive build item to register additional filters and do the OTel work, so RESTEasy doesn't have to know about OTel.
> 
> //cc @brunobat

`WithSpanJob implements Job` and inside it uses the OTel instrumentation API. 
There seems to be no scheduler side SPI to provide tracing, therefore it would be handy if we have one of our own... The Observation work also relates to this.
While we don't decide on it, I wonder if we could provide an SPI of our own to allow to isolate our extensions from this.

**Comment by mskacelik** [comment]
My initial implementation was entirely within the **OTel** module. I was utilizing the `JobListener` interface, which managed the spans. Unfortunately, this approach did not work with Quarkus's `@Scheduler` and `JobDefinition` approach for creating scheduling tasks. To the best of my knowledge, the idiomatic approach for **Quarkus** involves using `SuccessfulExecution` and `FailedExecution` CDI events. However, with these events, it's impossible to distinguish between running jobs (missing JobExecutionContext).

**Comment by mkouba** [comment]
> To the best of my knowledge, the idiomatic approach for **Quarkus** involves using `SuccessfulExecution` and `FailedExecution` CDI events. However, with these events, it's impossible to distinguish between running jobs (missing JobExecutionContext).

`SuccessfulExecution` and `FailedExecution` would not be enough. 

1. If I understand it correctly we need to execute some logic before the scheduled task is executed (start) and after the scheduled task is executed (end).
2. These events are not fired for Quartz jobs registered manually.

So the current behavior:
- If `quarkus.scheduler.tracing.enabled=true` and the OTel extension is present then the `@WithSpan` annotation is added automatically to every `@Scheduled` method
- Tasks registered programmatically with `JobDefinition` and Quartz jobs registered manually are not "traced automatically"

We could provide an SPI but we'll need some abstraction too because the Quartz jobs registered manually are not executed within the context of our API (i.e. no `io.quarkus.scheduler.ScheduledExecution`). In other words, we would need a `JobListener` that would bridge the SPI.

**Comment by brunobat** [comment]
I've discussed this with @radcortez and we think a good solution would be to create 2 different SPI, one for the `WithSpanJob` and another one for the `WithSpanInvoker`.
This could be achieved either with a service loader or with dedicated `BuildItems`. 
A default impl for the interfaces would need to be present if OTel is not loaded. 
If Otel is present, it would create these beans... The place where this wrapping happens would need to be Beans. 
The OTel extension would have dependencies on these extensions.

**Comment by brunobat** [comment]
Thanks @mkouba. It looks good to me. @mskacelik do you think you can add an integration test project for this PR?

File: extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzSchedulerImpl.java [hunk 5]
```diff
@@ -1039,9 +1064,16 @@ public Job newJob(TriggerFiredBundle bundle, org.quartz.Scheduler Scheduler) thr
             }
             Instance<?> instance = jobs.select(jobClass);
             if (instance.isResolvable()) {
-                return (Job) instance.get();
+                return jobWithSpanWrapper((Job) instance.get());
+            }
+            return jobWithSpanWrapper(super.newJob(bundle, Scheduler));
+        }
+
+        private Job jobWithSpanWrapper(Job job) {
```
Comment (radcortez) [inline extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzSchedulerImpl.java:1072]: Maybe rename the method to not use concept names from OTel?

**Review by radcortez — APPROVED** [review]

**Review by brunobat — DISMISSED** [review]
We need and IT test project.

**Comment by mkouba** [comment]
@mskacelik Any progress here? Do you need some help with the tests and docs?

**Comment by mskacelik** [comment]
> @mskacelik Any progress here? Would you like some help with the tests and docs?

Hi, I started by creating a new project called `opentelemetry-quartz` in the `integration-tests` (I have not yet started working with the `SimpleScheduler` implementation).  I made three rest endpoints which initiate the three types of scheduling.
- `@Scheduled`
- JobDefinition
- custom job

> For each task, I also added a fixed `Thread.sleep(...)` to measure if the span duration matches the intended (at least or equal) `Thread.sleep` in the job.

The `quartz` project inspired these endpoints from the `integration-tests.` I also added some API from the `OpenTelemetry-spi` project, for example, exporting spans, resetting spans, and working with `InMemorySpanExporter`.

But for some reason, when I enable otel for quartz by: `quarkus.scheduler.tracing.enabled=true` on each created span, it throws some weird error. Note that I tried the current implementation in a separate Quarkus project, and it works as intended, so that might be some problem with the configuration of my `opentelemetry-quartz` module. Maybe you can help me with this @mkouba? I will be available at 12:00 to discuss it in zulip chat.

**Comment by mskacelik** [comment]
# Tests
So, I added integration tests for Quartz. The only thing missing is Simple Scheduler tests, which will be pretty much the same as Quartz's (minus the custom job scheduler).

## In the test, there are 6 different schedulers:
1. **@Scheduled Type**
   - Normal scheduled task execution.
   - Scheduled task that intentionally throws an exception for testing.

2. **JobDefinition Type**
   - JobDefinition task execution.
   - JobDefinition task that intentionally throws an exception for testing.

3. **Custom Job Type (Programmatic)**
   - Custom job execution.
   - Custom job that intentionally throws an exception for testing.
   
Tests in the native mode do not work for some reason. Especially the `assertErrorJobSpan` where it checks on the error message.  It seems that spans that handle an exception do not contain the `message` of the exception as a field, nor do they contain stack trace. I tried to reproduce this problem in a separate Quarkus project, but everything worked fine, and spans in native mode contain the error message. I have no idea why this effect is only happening in my test.

File: integration-tests/opentelemetry-quartz/src/main/resources/application.properties [hunk 6]
```diff
@@ -0,0 +1,11 @@
+quarkus.application.name=opentelemetry-quartz-instrumentation-it
+quarkus.application.version=999-SNAPSHOT
+
+disabled=disabled
```
Comment (mkouba) [inline integration-tests/opentelemetry-quartz/src/main/resources/application.properties:4]: What are these properties for?

File: integration-tests/opentelemetry-quartz/pom.xml [hunk 7]
```diff
@@ -0,0 +1,144 @@
...
+    <name>Quarkus - Integration Tests - OpenTelemetry Quartz</name>
+
+    <dependencies>
+        <dependency>
+            <groupId>io.quarkus</groupId>
+            <artifactId>quarkus-arc</artifactId>
+        </dependency>
+        <dependency>
+            <groupId>io.quarkus</groupId>
+            <artifactId>quarkus-resteasy</artifactId>
```
Comment (mkouba) [inline integration-tests/opentelemetry-quartz/pom.xml:22]: I think that we should rather use `quarkus-resteasy-reactive` instead...

File: integration-tests/opentelemetry-quartz/src/main/resources/application.properties (hunk 6 above)
Comment (mskacelik) [reply integration-tests/opentelemetry-quartz/src/main/resources/application.properties:1]: I borrowed these top properties from other OTel integration tests, but it should not affect the test's outcome.

**Comment by mkouba** [comment]
Merging as the test failures do not seem to be related (and fail in other PRs as well).

**Comment by michalvavrik** [comment]
@mkouba @brunobat this changed OTEL operation names (see https://github.com/quarkus-qe/quarkus-test-suite/pull/1559) e.g. `SchedulerService.increment` => `1_io.quarkus.ts.opentelemetry.reactive.SchedulerService#increment`. That's a breaking change (if intentional? It doesn't look better) and as such should be in migration guide.

**Comment by mkouba** [comment]
> 1_io.quarkus.ts.opentelemetry.reactive.SchedulerService#increment

`1_io.quarkus.ts.opentelemetry.reactive.SchedulerService#increment` is a generated job identity. The identity must be _unique_ and is either generated (this case) or specified with `@Scheduled.identity()`. `SchedulerService.increment` is not unique. So maybe we should use the FQCN + method suffix as the span name instead?

**Comment by mskacelik** [comment]
@mkouba @michalvavrik I would personally have the job identifier as a span name because, for example, using `JobDefinition,` there is no `FQCN + method suffix` since the job has no class. That being said, I would add an explicit identity for the QE test because the default-generated identity does not have to be identical. So, there could be some nondeterministic behaviors.

**Comment by mskacelik** [comment]
@mkouba @michalvavrik 
> If there is such a change and you can't rely on operation name, I think it needs to be documented.

Martin will write some documentation in the migration guide, something along the lines of:
> When tracing is enabled using *OpenTelemetry*, previously, the span names followed the `<classname>.<methodName>` format. This has been updated to use the *job's unique identifier* as its name.

**Comment by michalvavrik** [comment]
> Well, the point is that the behavior was undefined/undocumented. So it wasn't testing a contract but an implementation detail.

I had to rely on something when writing these tests. I don't say you established contract, but little note in migration guide for people like me would help. Thanks

>  I mean, previously quarkus.scheduler.tracing.enabled=true implied that @WithSpan should be added to a scheduled method and the javadoc of @WithSpan.value() states: "If not specified, an appropriate default name should be created by auto-instrumentation. E.g. "className"."method"." Which is IMO not clear or deterministic at all. And BWT if className means the simple name and not FQCN then it's not very useful either.

I believe you are right, but I just checked my tests, I can't see any `@WithSpan` and as user I don't always read Quarkus implementation. I don't know whether for some user simple class and method name is enough, hence migration guide note.

**Comment by mkouba** [comment]
> > Well, the point is that the behavior was undefined/undocumented. So it wasn't testing a contract but an implementation detail.
> 
> I had to rely on something when writing these tests. I don't say you established contract, but little note in migration guide for people like me would help. Thanks

We will add a note to the docs so that it's clear and testable.

> 
> > I mean, previously quarkus.scheduler.tracing.enabled=true implied that @WithSpan should be added to a scheduled method and the javadoc of @WithSpan.value() states: "If not specified, an appropriate default name should be created by auto-instrumentation. E.g. "className"."method"." Which is IMO not clear or deterministic at all. And BWT if className means the simple name and not FQCN then it's not very useful either.
> 
> I believe you are right, but I just checked my tests, I can't see any `@WithSpan` and as user I don't always read Quarkus implementation. I don't know whether for some user simple class and method name is enough, hence migration guide note.

`@WithSpan` was added automatically. So it's even more confusing ;-).

I've added a migration note here:
https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.7#scheduler---opentelemetry-tracing

**Comment by michalvavrik** [comment]
Thanks!

**Comment by brunobat** [comment]
Thanks @mskacelik. This is great stuff.
