### PR TITLE
Propagate Runtime properties in JBang Dev mode

### LINKED ISSUE #44400: jbang devmode not honoring properties
### Describe the bug

I think since https://github.com/quarkusio/quarkus/pull/43160 `jbang -Dquarkus.dev some.java` does not honor Q:CONFIG.

```
///usr/bin/env jbang "$0" "$@" ; exit $?
//DEPS io.quarkus.platform:quarkus-bom:3.16.1@pom
//DEPS io.quarkus:quarkus-picocli

//Q:CONFIG quarkus.banner.enabled=false
//Q:CONFIG quarkus.log.level=ERROR
import io.quarkus.logging.Log;
import picocli.CommandLine.Command;

@Command
public class basicdev implements Runnable {
  


    @Override
    public void run() {
        System.out.println("You should see ERROR, but no WARN or INFO");
        Log.warn("This is a WARN message");
        Log.info("This is an INFO message");
        Log.error("This is an ERROR message");
    }
}
```

run above using `jbang --fresh basicdev.java` and it will only print ERROR logging, but run it with `jbang --fresh -Dquarkus.dev basicdev.java` it prints warn,info and error. As if it completely ignores Q:CONFIG

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by radcortez**
- Fixes #44400

### CODE REVIEW

**Review by aloubyansky — APPROVED** [review]

**Comment by gastaldi** [comment]
Backport?

File: independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/jbang/JBangDevModeLauncherImpl.java [hunk 1]
```diff
@@ -174,4 +179,19 @@ private static String getQuarkusVersion() {
...
+    private static Properties getConfigurationProperties(final Path source) throws IOException {
+        Properties properties = new Properties();
+        for (String line : Files.readAllLines(source)) {
+            if (line.startsWith("//Q:CONFIG")) {
+                String conf = line.substring(10).trim();
+                int equals = conf.indexOf("=");
+                if (equals == -1) {
+                    throw new RuntimeException("invalid config  " + line);
+                }
+                properties.setProperty(conf.substring(0, equals), conf.substring(equals + 1));
```
Comment (michalvavrik) [inline independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/jbang/JBangDevModeLauncherImpl.java:192]: IIUC when this is set, there is no point to continue, so maybe `break` the loop.
