### PR TITLE
QuarkusUnitTest: fix ignored overrideConfigKey()

### LINKED ISSUE #43129: QuarkusUnitTest#overrideConfigKey() is ignored if the test archive already contains an "application.properties" asset
### Describe the bug

There seems to be a [bug in the ShrinkWrap project](https://github.com/shrinkwrap/shrinkwrap/issues/179) - if you use both `archive.addAsResource(new StringAsset("quarkus.property=false"),"application.properties")` and `testConfig.overrideConfigKey("quarkus.property", "true")` then the value from the `application.properties` asset is taken.

### Expected behavior

I think that at the very least we should:

1. Clarify the javadoc of `QuarkusUnitTest#overrideConfigKey()`, and,
2. Either fail the test or log a warning if both `addResource()` and `overrideConfigKey()` are used.

Ideally, we would merge the existing `application.properties` asset and the overriden config properties but I'm not sure how complicated that could be.

### Actual behavior

The overriden config properties are ignored, no warning is logged.

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mkouba**
- if the test archive already contains an "application.properties" asset
- also clarify the javadoc: overriden config properties take precedence
- reimplement withConfigurationResource() to use JavaArchive#addAsResource(resourceName, "application.properties") and  avoid the ordering inconsistency if both withConfigurationResource() and overrideConfigKey() are used
- fixes #43129

### CODE REVIEW

**Comment by mkouba** [comment]
In theory, this is a breaking change but the good news is that it does not seem to break any test.

File: test-framework/junit5-internal/src/main/java/io/quarkus/test/QuarkusProdModeTest.java [hunk 1]
```diff
@@ -138,16 +137,8 @@ public class QuarkusProdModeTest
...
-            customApplicationProperties = new Properties();
-            try (InputStream is = appPropsIs) {
-                customApplicationProperties.load(is);
-            } catch (IOException e) {
-                throw new UncheckedIOException("Failed to load application configuration from "
-                        + Thread.currentThread().getContextClassLoader().getResource("application.properties"), e);
-            }
-        }
+        this.configResourceName = Thread.currentThread().getContextClassLoader()
+                .getResourceAsStream(APPLICATION_PROPERTIES) != null ? APPLICATION_PROPERTIES : null;
```
Comment (gastaldi) [inline test-framework/junit5-internal/src/main/java/io/quarkus/test/QuarkusProdModeTest.java:141]: Shouldn't this InputStream be closed at some point?

Comment (gastaldi) [reply test-framework/junit5-internal/src/main/java/io/quarkus/test/QuarkusProdModeTest.java:141]: Use `getResource` instead

**Review by gastaldi — CHANGES_REQUESTED** [review]

File: test-framework/junit5-internal/src/main/java/io/quarkus/test/QuarkusProdModeTest.java (hunk 1 above)
Comment (mkouba) [reply test-framework/junit5-internal/src/main/java/io/quarkus/test/QuarkusProdModeTest.java]: Done.

File: test-framework/junit5-internal/src/main/java/io/quarkus/test/QuarkusProdModeTest.java [hunk 2]
```diff
@@ -330,28 +323,48 @@ public Integer getExitCode() {
...
+                        }
                     }
-                    try (Stream<Path> stream = Files.walk(exportDir.toPath())) {
-                        stream.sorted(Comparator.reverseOrder()).map(Path::toFile)
-                                .forEach(File::delete);
+                    // overrideConfigKey() takes precedence
+                    customApplicationProperties.forEach(mergedProperties::put);
+
+                    if (Boolean.parseBoolean(System.getProperty("quarkus.test.log-merged-properties"))) {
+                        System.out.println("Merged config properties:\n" + mergedProperties.entrySet().stream()
```
Comment (yrodiere) [inline test-framework/junit5-internal/src/main/java/io/quarkus/test/QuarkusProdModeTest.java:348]: I'd use `keySet()` to be extra sure we're not logging secrets in values... The risk is low, but exists, e.g. if a module configures Maven to replace some properties in `application.properties` with an environment variable. Unlikely, I know; still.

File: test-framework/junit5-internal/src/main/java/io/quarkus/test/QuarkusProdModeTest.java [hunk 3]
```diff
@@ -793,24 +806,28 @@ public void beforeEach(ExtensionContext context) {
         });
     }
 
+    /**
+     * Add an {@code application.properties} asset loaded from the specified resource file in the test {@link JavaArchive}.
+     * <p>
```
Comment (yrodiere) [inline test-framework/junit5-internal/src/main/java/io/quarkus/test/QuarkusProdModeTest.java:811]:
```suggestion
     * Add an {@code application.properties} asset loaded from the specified resource file in the test {@link JavaArchive}.
     * <p>
     * By default, the archive is populated with the resource named {@code application.properties} at the root of the classpath, if it exists.
     * <p>
     * When calling this method, if an {@code application.properties} asset was already added explicitly to the archive (for instance added through {@code .addAsResource}), this earlier asset is removed and completely replaced by the one given here.
```

File: test-framework/junit5-internal/src/main/java/io/quarkus/test/QuarkusProdModeTest.java [hunk 4]
```diff
@@ -138,16 +137,10 @@ public class QuarkusProdModeTest
...
-                customApplicationProperties.load(is);
-            } catch (IOException e) {
-                throw new UncheckedIOException("Failed to load application configuration from "
-                        + Thread.currentThread().getContextClassLoader().getResource("application.properties"), e);
-            }
-        }
+        // If there is an application.properties resource then load the properties unless a custom config resource name is used
+        this.configResourceName = Thread.currentThread().getContextClassLoader().getResource(APPLICATION_PROPERTIES) != null
+                ? APPLICATION_PROPERTIES
+                : null;
```
Comment (yrodiere) [inline test-framework/junit5-internal/src/main/java/io/quarkus/test/QuarkusProdModeTest.java:143]: Since we pick `application.properties` from the classpath by default, and you fixed a problem that prevented it from overriding resources that already exist in the archive... Aren't we introducing a bug here, with this "default override"?

In particular, when I do this:

```java
    @RegisterExtension
    static final QuarkusProdModeTest TEST = new QuarkusProdModeTest()
            .withApplicationRoot((jar) -> jar
                    .addClasses(MyEntity.class)
                    .addAsResource("application-custom.properties", "application.properties")
                    .addAsResource("import.sql"));
```

... then if there is an `application.properties` in the classpath, it will erase the one I just added to my archive, will it not? :thinking:

File: test-framework/junit5-internal/src/main/java/io/quarkus/test/QuarkusUnitTest.java [hunk 5]
```diff
@@ -348,9 +351,44 @@ private void exportArchives(Path deploymentDir, Class<?> testClass) {
...
+                    } else {
+                        try (InputStream in = asset.openStream()) {
+                            mergedProperties.load(in);
+                        }
+                    }
+                    // overrideConfigKey() takes precedence
+                    customApplicationProperties.forEach(mergedProperties::put);
+
+                    if (Boolean.parseBoolean(System.getProperty("quarkus.test.log-merged-properties"))) {
+                        System.out.println("Merged config properties:\n" + mergedProperties.entrySet().stream()
```
Comment (yrodiere) [inline test-framework/junit5-internal/src/main/java/io/quarkus/test/QuarkusUnitTest.java:376]: Same here, I'd use `keySet()`.

File: test-framework/junit5-internal/src/main/java/io/quarkus/test/QuarkusUnitTest.java [hunk 6]
```diff
@@ -816,24 +854,28 @@ public QuarkusUnitTest setAfterUndeployListener(Runnable afterUndeployListener)
         return this;
     }
 
+    /**
+     * Add an {@code application.properties} asset loaded from the specified resource file in the test {@link JavaArchive}.
```
Comment (yrodiere) [inline test-framework/junit5-internal/src/main/java/io/quarkus/test/QuarkusUnitTest.java:858]:
```suggestion
     * Add an {@code application.properties} asset loaded from the specified resource file in the test {@link JavaArchive}.
     * <p>
     * When calling this method, if an {@code application.properties} asset was already added explicitly to the archive (for instance added through {@code .addAsResource}), this earlier asset is removed and completely replaced by the one given here.
```

**Review by yrodiere — COMMENTED** [review]
Thanks! A few comments below.

I'm especially doubtful of adding `application.properties` from the classpath to the archive _by default_, now that you've fixed asset overrides... See comment below.

File: test-framework/junit5-internal/src/main/java/io/quarkus/test/QuarkusProdModeTest.java (hunk 2 above)
Comment (mkouba) [reply test-framework/junit5-internal/src/main/java/io/quarkus/test/QuarkusProdModeTest.java:348]: Good point.

File: test-framework/junit5-internal/src/main/java/io/quarkus/test/QuarkusProdModeTest.java (hunk 4 above)
Comment (mkouba) [reply test-framework/junit5-internal/src/main/java/io/quarkus/test/QuarkusProdModeTest.java:143]: > ... then if there is an application.properties in the classpath, it will erase the one I just added to my archive, will it not? 🤔

Uf, you're right. But I wanted to keep this behavior so that we don't break the existing tests. What we could do is to only load the properties if `withConfigurationResource()` is not used && no `application.properties` is present in the test archive.

Comment (yrodiere) [reply test-framework/junit5-internal/src/main/java/io/quarkus/test/QuarkusProdModeTest.java]: > Uf, you're right. But I wanted to keep this behavior so that we don't break the existing tests

Right, my point was that, combined with you fixing the "resource precedence", this will just break existing tests in a different way :)

> What we could do is to only load the properties if `withConfigurationResource()` is not used && no `application.properties` is present in the test archive.

Looks like a plan :+1:

File: test-framework/junit5-internal/src/main/java/io/quarkus/test/ExportUtil.java [hunk 7]
```diff
@@ -35,4 +46,41 @@ static void exportToQuarkusDeploymentPath(JavaArchive archive) throws IOExceptio
         File exportFile = new File(exportDir, archive.getName());
         archive.as(ZipExporter.class).exportTo(exportFile);
     }
+
+    static void mergeCustomApplicationProperties(JavaArchive archive, Properties customApplicationProperties)
```
Comment (yrodiere) [inline test-framework/junit5-internal/src/main/java/io/quarkus/test/ExportUtil.java:50]: I almost suggested you to do that, but decided against it as it felt too much like nitpicking...

Great minds think alike :D

**Review by yrodiere — APPROVED** [review]
LGTM, thank you!

File: test-framework/junit5-internal/src/main/java/io/quarkus/test/ExportUtil.java (hunk 7 above)
Comment (radcortez) [reply test-framework/junit5-internal/src/main/java/io/quarkus/test/ExportUtil.java:50]: I guess this is a corner case and usually, we don't do it, but describing it for your consideration:

The resource archive may be a profiled file (`application-test.properties` or other), or even include both profiled and unprofiled. In the case of a profiled resource, that will always have priority over the unprofiled one.

Do we want to handle that case also? :)

Comment (mkouba) [reply test-framework/junit5-internal/src/main/java/io/quarkus/test/ExportUtil.java:50]: I have no idea :shrug:. 

In case of `QuarkusUnitTest` I think that we never use "profiled" files...

File: test-framework/junit5-internal/src/main/java/io/quarkus/test/ExportUtil.java [hunk 8]
```diff
@@ -35,4 +46,41 @@ static void exportToQuarkusDeploymentPath(JavaArchive archive) throws IOExceptio
...
+            if (asset instanceof StringAsset strAsset) {
+                mergedProperties.load(new StringReader(strAsset.getSource()));
+            } else {
+                try (InputStream in = asset.openStream()) {
+                    mergedProperties.load(in);
+                }
+            }
+            customApplicationProperties.forEach(mergedProperties::put);
+
+            if (Boolean.parseBoolean(System.getProperty("quarkus.test.log-merged-properties"))) {
```
Comment (gastaldi) [inline test-framework/junit5-internal/src/main/java/io/quarkus/test/ExportUtil.java:67]: This can also be simplified to: 

```suggestion
            if (Boolean.getBoolean("quarkus.test.log-merged-properties")) {
```

**Review by gastaldi — APPROVED** [review]
LGTM

File: test-framework/junit5-internal/src/main/java/io/quarkus/test/ExportUtil.java (hunk 8 above)
Comment (mkouba) [reply test-framework/junit5-internal/src/main/java/io/quarkus/test/ExportUtil.java:67]: Ok, will use it the next time ;-). Although I personally don't think `getBoolean()` is a good method name. I mean `parseSystemProperty()` or something along these lines would be more clear :shrug:.

Comment (gastaldi) [reply test-framework/junit5-internal/src/main/java/io/quarkus/test/ExportUtil.java:67]: We need to blame Sun for introducing this method in Java 1.0 😃

Comment (geoand) [reply test-framework/junit5-internal/src/main/java/io/quarkus/test/ExportUtil.java:67]: I'm with @mkouba on this - `Boolean.getBoolean(...)` is super confusing in that it parses a system property.
