### PR TITLE
OIDC: avoid some concurrent token refresh requests for the same session

### LINKED ISSUE #52546: Quarkus OIDC can send concurrent refresh token requests for the same session
### Describe the bug

When an already authenticated user has multiple tabs/frames in the browser, and the user session expires, what might happen is that multiple concurrent refresh token grants for the same session can flow to a provider such as Keycloak, possibly exceeding an allowed number of the refresh token reuse.

### Expected behavior

Only a single RT grant request flows, something that we can try to sort out with `.memoise`

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Mandrel or GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by michalvavrik**
* Closes: https://github.com/quarkusio/quarkus/issues/52546

### CODE REVIEW

**Comment by sberyozkin** [comment]
Hey @michalvavrik Thanks a million, I think it looks fine, where in the test should I look at to see that the same RT is used ? 
I believe it is also be worth configuring Keycloak realm to restrict a number of refresh token reuse - one of the integration tests shows how to do it. And verify that the error reported in the linked discussion is not in the logs - or may be simpler, use oidc response filter to check the response

**Comment by michalvavrik** [comment]
> where in the test should I look at to see that the same RT is used ?

this is about token refresh request, the test passes, hence it works for any token refresh request; I debugged it manually to understand it as well

> I believe it is also be worth configuring Keycloak realm to restrict a number of refresh token reuse - one of the integration tests shows how to do it.

I will do it if it helps to verify anything, but it doesn't. I am testing changes that I made in regards of concurrent refresh token requests. What it has to do with some Keycloak configuration?

> And verify that the error reported in the linked discussion is not in the logs - or may be simpler, use oidc response filter to check the response

I don't see any error in #52546, which one do you mean? Besides, I explained in the issue comments what would be bullet proof solution and you said we don't need to cover "10 %" cases, so testing this under heavy concurrency and checking logs wouldn't be safe, it would probably be flaky.

**Comment by michalvavrik** [comment]
I just think that testing concurrency against external provider where we cannot restrict "when" the provider responds is naive. I thought this test through and it took me a while to figure how to test this reliably, so I don't fight your suggestion, but I need to understand what exactly is not tested here, because if we limit concurrent requests, of course you will not get reuse of the refresh token for cases this PR covers (which is not every case, I explained that in the linked issue).

**Comment by sberyozkin** [comment]
@michalvavrik That is fine, I looked at the code, the access token comparison is ok. 

By 10% I meant that the situation where the refresh token request for the same session is concurrent is 10%.

Can you add `realm.setRefreshTokenMaxReuse(1);` to the Keycloak test code that creates a Realm ?

**Comment by sberyozkin** [comment]
Sorry Michal, I forgot one more thing, can you have `OidcProviderClient` injected and check, after the access token comparison is done, via a cast to the `OidcProviderClientImpl`, that the concurrent map is empty ?

**Comment by michalvavrik** [comment]
> Sorry Michal, I forgot one more thing, can you have `OidcProviderClient` injected and check, after the access token comparison is done, via a cast to the `OidcProviderClientImpl`, that the concurrent map is empty ?

It means I need to expose it, I did check it manually to avoid that, but sure. will do.

> Can you add realm.setRefreshTokenMaxReuse(1); to the Keycloak test code that creates a Realm ?

It will never be reliable, whether we speak one of thousand or even less cases, I have no idea, but by design this does not fix situation where the refresh token can be reused. It just limits it in the part that takes longest (IO -> communication with Keycloak), so it should limit the number of these situations positively. There is still everything I mentioned on https://github.com/quarkusio/quarkus/issues/52546. So while I think I understand why you are asking for this, we shouldn't add tests that can become flaky.

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcProviderClientImpl.java [hunk 1]
```diff
@@ -295,6 +307,10 @@ public Uni<Boolean> revokeRefreshToken(String refreshToken) {
         return revokeToken(refreshToken, OidcConstants.REFRESH_TOKEN_VALUE);
     }
 
+    public int getRefreshTokenRequestsCount() {
```
Comment (sberyozkin) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcProviderClientImpl.java]: @michalvavrik I got confused, sorry, I thought, for a moment, it was in the deployment.

Well, you are right, we clearly don't want it as a public method. But hope you agree we need to assert the map is not growing. 

So my proposal is to attempt to move it to the deployment module, make it package protected, and return a snapshot of this map, that at least theoretically we might want to use for some other kind of analysis in the future,  `getRefreshTokenRequestsCount` is a test utility method.

Please also set that refreshTokenReuse count as proposed in my previous comment, thanks

Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcProviderClientImpl.java]: @michalvavrik Never mind, please only update that method to return a snapshot of that map, will do for now

Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcProviderClientImpl.java]: @michalvavrik However, that should be accepting an actual refresh token as an input parameter

Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcProviderClientImpl.java]: Sorry, I'm getting all over the place here - please keep this method - but only add this input parameter

**Comment by sberyozkin** [comment]
@michalvavrik Can you please explain again why it can be flaky to have a refresh token limit set in Keycloak, given that this map is keyed by the refresh token value that is supposed to be unique ?

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcProviderClientImpl.java (hunk 1 above)
Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcProviderClientImpl.java]: Exposing on `OidcProviderClientImpl` in the runtime package should be ok, users won't see it via an injected `OidcProviderClient` interface, so we can change at any time, is they cast it to the implementation then it won't be our responsibility to ensure that method remains

**Comment by michalvavrik** [comment]
> @michalvavrik Can you please explain again why it can be flaky to have a refresh token limit set in Keycloak, given that this map is keyed by the refresh token value that is supposed to be unique ?

Provided we are talking about the same subject, it is exactly what I described in https://github.com/quarkusio/quarkus/issues/52546. Let me summarize it, hope I won't be repeating myself too much.

If there are concurrent requests that results in refresh token request, what happens is:

1. request one arrives (you can imagine it as a browser tab A)
2. request two arrives (you can imagine it as a browser tab B)
3. now depending of timing of A and B, following combinations happen:
  a) A arrived, refresh token was used to refresh authorization tokens and B arrived when the request to refresh was in a progress -----> this PR helps, the IO operation is running longest, hence it is most likely to happen
  b) A arrived, refresh token was used to refresh authorization tokens and B was issued before A received response, hence B arrived with the old session cookie and refresh token is required -----> mitigation is using DB/Redis token state manager, which covers 99 % of situations, but still, considering that we do not synchronize this token refresh on the token state managers itself, we do not cover situation between token state is stored in DB/Redis, hence there still is a scenario where B arrives while A already updated tokens, but still didn't persist the token result

The situation "3. b)" is what I don't want to introduce the test that you are suggesting. Now, we could try what you want for "3. b) with DB or Redis", but it is still not 100 % so it is bound to be flaky (I am not saying frequently flaky, I simply don't know that, it may happen once in the century, I simply do not know).

**Comment by sberyozkin** [comment]
Thanks @michalvavrik 

>a) A arrived, refresh token was used to refresh authorization tokens and **B arrived when the request to refresh was in a progress**

and 

> b) A arrived, refresh token was used to refresh authorization tokens and **B was issued before A received response, hence B arrived with the old session cookie and refresh token is required** 

I'm sorry for being slow, but these 2 scenarios in bold imply the same thing to me - specifically, `B was issued before A received response` - to me it reads the same as `B arrived when the request to refresh was in a progress`. 

Please clarify a bit more, may be using simple `1.`, `2.`, etc sequencing.

**Comment by michalvavrik** [comment]
Presumption (time units are of no particular type, not seconds or whatever):

```
- Tab A called Quarkus at 0:01, refresh token request was called by Quarkus (to Keycloak) at 0:05, respond arrived at 0:07, token was persisted to token storage in 0:09, response from Quarkus arrived at 0:10
```

situation when this PR helps:

```
- Tab B called Quarkus at 0:02, refresh token request was not called because we already have request from A, so we respond after 0:07
```

situation when this PR does not help unless you use DB/Redis:

```
- Tab B called Quarkus at 0:08, so the "Tab A respond did not arrive yet", hence the refresh token request was reused (AKA: old cookie)
```

situation when this PR does not help with DB/Redis:

```
- Tab B called Quarkus at 0:07, refresh token A was retrieved from the DB/Redis token storage at 0:08, hence the refresh token was reused
```

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcProviderClientImpl.java (hunk 1 above)
Comment (michalvavrik) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcProviderClientImpl.java]: updated

**Comment by sberyozkin** [comment]
@michalvavrik 

Oh yeah, I see now what you mean, I honestly hope this concurrent variation where someone has such a sophisticated app where one tab's refresh token response arrived at the Quarkus level but not made it yet to the browser and now another tab starts another refresh token request is going to be a very rare occasion.

One thing that can actually happen here, with Keycloak at least, is that, since KC usually recycles refresh tokens, i.e, such delayed concurrent request would end up failing to refresh the token because that stale RT is already gone. I'm not worried about such case as it will probably never happen, and all what will happen is that the tab in question will be asked to re-authenticate - which SPA can either do or figure out somehow that in fact the session is valid now. And we can't afford blocking to cover these very rare cases.

Overall, it is the `best effort` that should cover most of such cases, thanks.

**Review by sberyozkin — APPROVED** [review]
Thanks very much @michalvavrik
