### PR TITLE
Mutiny 0.8.1

### LINKED ISSUE #11614: Integrate Mutiny 0.8.0
**Description**

Mutiny 0.8.0 is coming _soon_, and it will require a bit of integration code:

* [ ] Integrate the dropped exception hook

@jponge volunteered to implement this once Mutiny 0.8.0 is released!

### PR DESCRIPTION
**Pull request by jponge**
Upgrading to Mutiny 0.8.1:

* fix compilation errors against parametric types,
* install a dropped exception handler/logger,
* configure a thread blocking checker that reports blocking Vert.x event-loops.

Fixes #11614

### CODE REVIEW

**Comment by jponge** [comment]
Ok, there are some issues in native images generation, let me investigate that.

File: extensions/mutiny/deployment/src/main/java/io/quarkus/mutiny/deployment/MutinyProcessor.java [hunk 1]
```diff
@@ -23,4 +23,16 @@ public void initExecutor(ExecutorBuildItem executorBuildItem, MutinyInfrastructu
         ExecutorService executor = executorBuildItem.getExecutorProxy();
         recorder.configureMutinyInfrastructure(executor);
     }
+
+    @BuildStep
+    @Record(ExecutionTime.STATIC_INIT)
+    public void defineDroppedExceptionHandler(MutinyInfrastructure recorder) {
+        recorder.configureDroppedExceptionHandler();
```
Comment (cescoffier) [inline extensions/mutiny/deployment/src/main/java/io/quarkus/mutiny/deployment/MutinyProcessor.java:30]: [Picky] - We could have done everything in a single method.

File: extensions/mutiny/runtime/src/main/java/io/quarkus/mutiny/runtime/MutinyInfrastructure.java [hunk 2]
```diff
@@ -11,4 +15,23 @@
     public void configureMutinyInfrastructure(ExecutorService exec) {
         Infrastructure.setDefaultExecutor(exec);
     }
+
+    public void configureDroppedExceptionHandler() {
+        Infrastructure.setDroppedExceptionHandler(new Consumer<Throwable>() {
+            @Override
+            public void accept(Throwable throwable) {
+                Logger.getLogger(MutinyInfrastructure.class).error("Mutiny had to drop the following exception", throwable);
```
Comment (cescoffier) [inline extensions/mutiny/runtime/src/main/java/io/quarkus/mutiny/runtime/MutinyInfrastructure.java:23]: Should we cache the logger?

Comment (cescoffier) [reply extensions/mutiny/runtime/src/main/java/io/quarkus/mutiny/runtime/MutinyInfrastructure.java:23]: Can we add the drop site too?

File: extensions/mutiny/runtime/src/main/java/io/quarkus/mutiny/runtime/MutinyInfrastructure.java [hunk 3]
```diff
@@ -11,4 +15,23 @@
...
+            }
+        });
+    }
+
+    public void configureThreadBlockingChecker() {
+        Infrastructure.setCanCallerThreadBeBlockedSupplier(new BooleanSupplier() {
+            @Override
+            public boolean getAsBoolean() {
+                String threadName = Thread.currentThread().getName();
+                return !threadName.contains("vertx-eventloop-thread-");
```
Comment (cescoffier) [inline extensions/mutiny/runtime/src/main/java/io/quarkus/mutiny/runtime/MutinyInfrastructure.java:33]: Can you add a comment about why we use that strategy (avoid depending on Vert.x explicitly, also avoid to select worker threads).

**Review by cescoffier — CHANGES_REQUESTED** [review]
I've made a few minor comments. The rest looks good.

File: extensions/mutiny/deployment/src/main/java/io/quarkus/mutiny/deployment/MutinyProcessor.java (hunk 1 above)
Comment (jponge) [reply extensions/mutiny/deployment/src/main/java/io/quarkus/mutiny/deployment/MutinyProcessor.java:30]: Ok let me change that. I was wondering if that was a pattern to delegate to a class there, but since the actual code is in runtime and we're in a static init... yeah 👍

File: extensions/mutiny/runtime/src/main/java/io/quarkus/mutiny/runtime/MutinyInfrastructure.java (hunk 3 above)
Comment (jponge) [reply extensions/mutiny/runtime/src/main/java/io/quarkus/mutiny/runtime/MutinyInfrastructure.java:33]: Yep

File: extensions/mutiny/runtime/src/main/java/io/quarkus/mutiny/runtime/MutinyInfrastructure.java (hunk 2 above)
Comment (jponge) [reply extensions/mutiny/runtime/src/main/java/io/quarkus/mutiny/runtime/MutinyInfrastructure.java:23]: It should be infrequent enough, but I can try moving it back to the heap. In earlier iterations I had GraalVM compilation issues, but it was my bad understanding of the `ExecutionTime` scopes.

File: extensions/mutiny/deployment/src/main/java/io/quarkus/mutiny/deployment/MutinyProcessor.java (hunk 1 above)
Comment (jponge) [reply extensions/mutiny/deployment/src/main/java/io/quarkus/mutiny/deployment/MutinyProcessor.java:30]: Nevermind I get it now

**Review by cescoffier — APPROVED** [review]
