### PR TITLE
Inject "annotations" and "genericType" in ParamConverterProvider

### LINKED ISSUE #22870: Resteasy Reactive Client: Parameter "annotations" is always null in ParamConverterProvider
### Describe the bug

The parameter `annotations` in `ParamConverterProvider` is always null.

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

```kotlin
@Path("/")
@RegisterProvider(MyParamConverterProvider::class)
interface MyRestService {

    @POST
    @Path("/{x}")
    fun xyz(@PathParam("x") @MyParam value: String): Uni<String>
}

@MustBeDocumented
@Retention(AnnotationRetention.RUNTIME)
@Target(AnnotationTarget.FIELD, AnnotationTarget.VALUE_PARAMETER)
annotation class MyParam

class MyParamConverter : ParamConverter<String> {

    override fun toString(value: String): String = value

    override fun fromString(value: String): String = value
}

class MyParamConverterProvider : ParamConverterProvider {

    override fun <T : Any?> getConverter(
        rawType: Class<T>?,
        genericType: Type?,
        annotations: Array<out Annotation>?
    ): ParamConverter<T>? {
	// "annotations" is alway null
        return annotations?.filterIsInstance(MyParam::class.java)?.firstOrNull()?.let {
            MyParamConverter() as ParamConverter<T>
        }
    }
}
````

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

Java 11

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.6.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Sgitario**
Note that this PR will introduce a performance penalty at load time (first time, when the rest client instance is loaded AND if and only if the rest client methods use param annotations - which is most of the times tho).

What I did was to always generate the `javaMethodX` static fields (before, it was also generated always, but it was done in the implementation MicroProfileRestClientEnricher). 
Plus, apart of the method information, we will also load the annotations and the generic types. This is done at load class time (static init).

Moreover, as I had to move some code from MicroProfileRestClientEnricher to 
JaxrsClientReactiveProcessor, in order to not increase the length of this class JaxrsClientReactiveProcessor, I started moving some code to ClassRestClientContext (which is protected - not available for users)

Fix https://github.com/quarkusio/quarkus/issues/22870

### CODE REVIEW

**Comment by geoand** [comment]
Have you tried this in native mode? 
Something tells me there might be more adjustments needed :)

File: extensions/resteasy-reactive/jaxrs-client-reactive/deployment/src/main/java/io/quarkus/jaxrs/client/reactive/deployment/ClassRestClientContext.java [hunk 1]
```diff
@@ -0,0 +1,128 @@
...
+
+        return javaMethodField;
+    }
+
+    /**
+     * Generates "method.getParameterAnnotations()" and it will only be created if and only if the supplier is used
+     * in order to not have a penalty performance.
+     */
+    protected Supplier<FieldDescriptor> getLazyJavaMethodParamAnnotationsField(int methodIndex) {
+        return () -> {
```
Comment (geoand) [inline extensions/resteasy-reactive/jaxrs-client-reactive/deployment/src/main/java/io/quarkus/jaxrs/client/reactive/deployment/ClassRestClientContext.java:82]: No lambdas in runtime code please

**Comment by Sgitario** [comment]
> Have you tried this in native mode? Something tells me there might be more adjustments needed :)

I created a sample and it worked for me in Native mode too.

**Comment by geoand** [comment]
> > Have you tried this in native mode? Something tells me there might be more adjustments needed :)
> 
> I created a sample and it worked for me in Native mode too.

Test or it didn't happen 😆

**Comment by Sgitario** [comment]
> > > Have you tried this in native mode? Something tells me there might be more adjustments needed :)
> > 
> > 
> > I created a sample and it worked for me in Native mode too.
> 
> Test or it didn't happen laughing

hehe +100. I've just added a integration test that covers a simple example in jvm and Native.

**Comment by gsmet** [comment]
@geoand I'll let you decide if this needs a backport.

**Comment by geoand** [comment]
Yeah, I think we should have it. It's not terribly important for `2.7.0.Final` though, it can go into a subsequent version

**Comment by geoand** [comment]
@michalszynkiewicz can you take a look at this?

**Comment by michalszynkiewicz** [comment]
I'll try to get to this tomorrow, sorry for the delay

File: extensions/resteasy-reactive/jaxrs-client-reactive/deployment/src/main/java/io/quarkus/jaxrs/client/reactive/deployment/ClassRestClientContext.java [hunk 2]
```diff
@@ -0,0 +1,127 @@
...
+        this.clinit = classCreator.getMethodCreator(MethodDescriptor.ofMethod(name, "<clinit>", void.class));
+        this.clinit.setModifiers(Opcodes.ACC_STATIC);
+    }
+
+    @Override
+    public void close() {
+        classCreator.close();
+    }
+
+    protected FieldDescriptor createJavaMethodField(ClassInfo interfaceClass, MethodInfo method, int methodIndex) {
```
Comment (michalszynkiewicz) [inline extensions/resteasy-reactive/jaxrs-client-reactive/deployment/src/main/java/io/quarkus/jaxrs/client/reactive/deployment/ClassRestClientContext.java:54]: is there a case when we don't need a java method field?

File: extensions/resteasy-reactive/jaxrs-client-reactive/deployment/src/main/java/io/quarkus/jaxrs/client/reactive/deployment/JaxrsClientReactiveProcessor.java [hunk 3]
```diff
@@ -1358,15 +1418,33 @@ private void handleSubResourceMethod(List<JaxrsClientReactiveEnricherBuildItem>
...
-                subClinit.returnValue(null);
-            }
+            subClassContext.constructor.returnValue(null);
+            subClassContext.clinit.returnValue(null);
 
             methodCreator.returnValue(subInstance);
         }
     }
 
+    private AssignableResultHandle createWebTargetForMethod(MethodCreator constructor, AssignableResultHandle baseTarget,
```
Comment (michalszynkiewicz) [inline extensions/resteasy-reactive/jaxrs-client-reactive/deployment/src/main/java/io/quarkus/jaxrs/client/reactive/deployment/JaxrsClientReactiveProcessor.java:1428]: these two aren't changed, just moved, right?

File: integration-tests/rest-client-reactive/src/main/java/io/quarkus/it/rest/client/main/ParamConverter.java [hunk 4]
```diff
@@ -0,0 +1,46 @@
...
+import java.lang.reflect.Type;
+
+import javax.ws.rs.ext.ParamConverterProvider;
+
+public class ParamConverter implements ParamConverterProvider {
+    @SuppressWarnings("unchecked")
+    @Override
+    public <T> javax.ws.rs.ext.ParamConverter<T> getConverter(Class<T> rawType, Type genericType,
+            Annotation[] annotations) {
+        if (genericType == null) {
```
Comment (michalszynkiewicz) [inline integration-tests/rest-client-reactive/src/main/java/io/quarkus/it/rest/client/main/ParamConverter.java:13]: it would be worth checking some actual values here, I mean adding some annotations and checking if they are passed properly, and checking the generic type with generics

File: extensions/resteasy-reactive/jaxrs-client-reactive/deployment/src/main/java/io/quarkus/jaxrs/client/reactive/deployment/ClassRestClientContext.java (hunk 2 above)
Comment (Sgitario) [reply extensions/resteasy-reactive/jaxrs-client-reactive/deployment/src/main/java/io/quarkus/jaxrs/client/reactive/deployment/ClassRestClientContext.java:54]: No, we always need it in:
- https://github.com/quarkusio/quarkus/pull/23090/files#diff-0c27cb2fbf4ead4ae377f712102826c9fbbe5ada510deda804e190838dd5b11fL46
- https://github.com/quarkusio/quarkus/pull/23090/files#diff-0c27cb2fbf4ead4ae377f712102826c9fbbe5ada510deda804e190838dd5b11fL69

Note that this is how was working before this PR, but this code was directly in JaxrsClientReactiveEnricher.

File: extensions/resteasy-reactive/jaxrs-client-reactive/deployment/src/main/java/io/quarkus/jaxrs/client/reactive/deployment/JaxrsClientReactiveProcessor.java (hunk 3 above)
Comment (Sgitario) [reply extensions/resteasy-reactive/jaxrs-client-reactive/deployment/src/main/java/io/quarkus/jaxrs/client/reactive/deployment/JaxrsClientReactiveProcessor.java:1428]: Correct

File: integration-tests/rest-client-reactive/src/main/java/io/quarkus/it/rest/client/main/ParamConverter.java (hunk 4 above)
Comment (Sgitario) [reply integration-tests/rest-client-reactive/src/main/java/io/quarkus/it/rest/client/main/ParamConverter.java]: +1 
Added

File: integration-tests/rest-client-reactive/src/main/java/io/quarkus/it/rest/client/main/ParamConverter.java [hunk 5]
```diff
@@ -0,0 +1,47 @@
...
+import javax.ws.rs.QueryParam;
+import javax.ws.rs.ext.ParamConverterProvider;
+
+public class ParamConverter implements ParamConverterProvider {
+    @SuppressWarnings("unchecked")
+    @Override
+    public <T> javax.ws.rs.ext.ParamConverter<T> getConverter(Class<T> rawType, Type genericType,
+            Annotation[] annotations) {
+        if (genericType == null || !genericType.equals(Param.class)) {
+            throw new RuntimeException("Generic Type cannot be null!");
```
Comment (michalszynkiewicz) [inline integration-tests/rest-client-reactive/src/main/java/io/quarkus/it/rest/client/main/ParamConverter.java:15]: the messages do not conform to what is checked now but this can be fixed later, by the way

**Review by michalszynkiewicz — APPROVED** [review]

File: integration-tests/rest-client-reactive/src/main/java/io/quarkus/it/rest/client/main/ParamConverter.java (hunk 5 above)
Comment (Sgitario) [reply integration-tests/rest-client-reactive/src/main/java/io/quarkus/it/rest/client/main/ParamConverter.java]: I've changed the message to simply say `Wrong generic type..."

**Comment by mschorsch** [comment]
@gsmet Will this PR be part of 2.7.1

**Comment by gsmet** [comment]
@mschorsch yes, it has the backport label so I'll backport it (if there's no large conflict).
