### PR TITLE
Panache Next: tests and changes after upstream fixes in hibernate-processor

### LINKED ISSUE #50177: Panache 2 / Hibernate processor : make sure implementing `PanacheRepository` sets the primary entity even for custom repos
### Description

For some reason, I can't currently write:

```java
@Entity
public class Cat extends PanacheEntity {
 public String name;

 @Repository
 interface Repo {
  @Delete
  long deleteByName(String name);
 }
}
```

Because it does not pick up that the primary is known. This should be possible.

Also make sure that this variant works:

For some reason, I can't currently write:

```java
@Entity
public class Cat extends PanacheEntity {
 public String name;

 @Repository
 interface Repo extends PanacheRepository<Cat> {
  @Delete
  long deleteByName(String name);
 }
}
```

### Implementation ideas

_No response_

### LINKED ISSUE #50178: Panache 2 / Hibernate Processor : Make sure JD annotations work even without `@Repository`.
### Description

The `@Repository` annotation should be optional on any nested interface with annotated methods, or extending a panache repo type:

```java
@Entity
public class Cat extends PanacheEntity {
 public String name;

 interface Repo {
  @Delete
  long deleteByName(String name);
 }
}
```

Also make sure we generate accessors even when there's no annotated member:

```java
@Entity
public class Cat extends PanacheEntity {
 public String name;

 interface Repo extends PanacheRepository<Cat> {
 }
}
```

### Implementation ideas

_No response_

### LINKED ISSUE #50179: Panache 2 : Make `CrudRepository` equivalents for stateful and HR
### Description

ATM it only supports stateless blocking, so we need counterparts for:

- managed blocking
- managed reactive
- stateless reactive

This needs to be coordinated with @gavinking because JD 1.1 might already be working on that.

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by FroMage**
This is fixed in ORM at https://github.com/hibernate/hibernate-orm/pull/11769

### CODE REVIEW

**Comment by FroMage** [comment]
Draft until we get an ORM release with this.

File: extensions/panache/hibernate-panache-next/deployment/src/test/java/io/quarkus/hibernate/panache/deployment/test/processor/orm/Panache2Book.java [hunk 1]
```diff
@@ -29,4 +31,24 @@ public interface Queries {
         @HQL("WHERE isbn = :isbn")
         List<Panache2Book> hqlBook(String isbn);
     }
+
+    public interface JDQueries {
+        // This should work without @Repository
+        @jakarta.data.repository.Find
```
Comment (lucamolteni) [inline extensions/panache/hibernate-panache-next/deployment/src/test/java/io/quarkus/hibernate/panache/deployment/test/processor/orm/Panache2Book.java:37]: It's unfortunate that we have two versions of `@Find`, will user need to specify the namespaces all the time?

**Review by lucamolteni — APPROVED** [review]
LGTM

File: extensions/panache/hibernate-panache-next/deployment/src/test/java/io/quarkus/hibernate/panache/deployment/test/processor/SessionTypeEntity.java [hunk 2]
```diff
@@ -0,0 +1,152 @@
...
+        //        @Persist
+        //        void myPersist(SessionTypeEntity entity);
+        //        @Remove
+        //        void myRemove(SessionTypeEntity entity);
+        //        @Detach
+        //        void myDetach(SessionTypeEntity entity);
+        //        @Merge
+        //        void myMerge(SessionTypeEntity entity);
+        //        @Refresh
+        //        void myRefresh(SessionTypeEntity entity);
```
Comment (yrodiere) [inline extensions/panache/hibernate-panache-next/deployment/src/test/java/io/quarkus/hibernate/panache/deployment/test/processor/SessionTypeEntity.java:54]: These seem most likely to be useful in repos that do *not* extend `PanacheRepository`, no? If so we'd better test them in that scenario, not here.

File: extensions/panache/hibernate-panache-next/deployment/pom.xml [hunk 3]
```diff
@@ -53,6 +53,11 @@
         </dependency>
 
         <!-- test dependencies -->
+        <dependency>
+            <groupId>jakarta.data</groupId>
+            <artifactId>jakarta.data-api</artifactId>
+            <scope>test</scope>
+        </dependency>
```
Comment (yrodiere) [inline extensions/panache/hibernate-panache-next/deployment/pom.xml:60]: At this point I'd make it a dependency of `hiernate-panache-next`... Maybe someday we'll pull that into `quarkus-hibernate-orm`, but that would require some more discussion. For Panache this seems like a clear win.

**Review by yrodiere — APPROVED** [review]

File: extensions/panache/hibernate-panache-next/deployment/pom.xml (hunk 3 above)
Comment (FroMage) [reply extensions/panache/hibernate-panache-next/deployment/pom.xml:60]: I've an issue open about that.

File: extensions/panache/hibernate-panache-next/deployment/src/test/java/io/quarkus/hibernate/panache/deployment/test/processor/SessionTypeEntity.java (hunk 2 above)
Comment (FroMage) [reply extensions/panache/hibernate-panache-next/deployment/src/test/java/io/quarkus/hibernate/panache/deployment/test/processor/SessionTypeEntity.java:54]: Yeah, well it's commented out because it does not exist yet anyway 🤷

File: extensions/panache/hibernate-panache-next/deployment/src/test/java/io/quarkus/hibernate/panache/deployment/test/processor/orm/Panache2Book.java (hunk 1 above)
Comment (FroMage) [reply extensions/panache/hibernate-panache-next/deployment/src/test/java/io/quarkus/hibernate/panache/deployment/test/processor/orm/Panache2Book.java:37]: Now that they both work the same, I can depend on JD and point users towards the JD version in the docs. But that's another already open issue.

**Comment by FroMage** [comment]
Thanks.
