### PR TITLE
Extend removed resources configuration to application sources themselves

### LINKED ISSUE #18725: Specify an Application class at build time
### Description

Currently if your classpath contains more than one `javax.ws.rs.core.Application` an error occurs: `RuntimeException: More than one Application class: [my.project.service1.Service1Application,my.project.service1.Service1Application,my.project.service3.Service3Application]`

The existing logic can remain to automagically pickup the `Application`, but additional logic allowing one to specify a specific `Application` could be very useful in the above case.

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by geoand**
Resolves: #18725

### CODE REVIEW

File: core/deployment/src/main/java/io/quarkus/deployment/steps/ApplicationIndexBuildStep.java [hunk 1]
```diff
@@ -33,14 +40,33 @@ public FileVisitResult preVisitDirectory(Path dir, BasicFileAttributes attrs) th
...
+                            log.debugf("Indexing %s", file);
+                            try (InputStream stream = Files.newInputStream(file)) {
+                                indexer.index(stream);
+                            }
                         }
                     }
                     return FileVisitResult.CONTINUE;
                 }
 
+                private boolean isRemovedApplicationClass(String fileName, Set<String> removedApplicationClasses) {
```
Comment (aloubyansky) [inline core/deployment/src/main/java/io/quarkus/deployment/steps/ApplicationIndexBuildStep.java:57]: Maybe path the original `Path` here and call `toString()` on it if `removedApplicationClasses` isn't empty?

Comment (geoand) [reply core/deployment/src/main/java/io/quarkus/deployment/steps/ApplicationIndexBuildStep.java:57]: Sure, done

**Review by aloubyansky — APPROVED** [review]
