### PR TITLE
Ignore the error when the stream is closed and try to continue

### LINKED ISSUE #28799: Error reading stream exception thrown from OutputFilter / NativeImageBuildStep
### Describe the bug

Error reading stream exception thrown from OutputFilter / NativeImageBuildStep

We see this issue with Quarkus 2.13

https://github.com/quarkusio/quarkus/blob/main/core/deployment/src/main/java/io/quarkus/deployment/OutputFilter.java was refactored / introduced in https://github.com/quarkusio/quarkus/pull/26892 / Quarkus 2.13.0.Final

Stacktrace:
```
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Building native image from /home/runner/work/quarkus-startstop/quarkus-startstop/app-jax-rs-minimal/target/quarkus-native-image-source-jar/quarkus-runner.jar
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildContainerRunner] Using docker to run the native image builder
Exception in thread "Process stdout" java.lang.RuntimeException: Error reading stream.
	at io.quarkus.deployment.OutputFilter.lambda$apply$0(OutputFilter.java:23)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: Stream closed
	at java.base/java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:176)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:342)
	at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:181)
	at java.base/java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:326)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:392)
	at io.quarkus.deployment.OutputFilter.lambda$apply$0(OutputFilter.java:19)
	... 1 more
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildContainerRunner] Checking image status quay.io/quarkus/ubi-quarkus-native-image:22.2-java17
```

Example logs: https://github.com/quarkus-qe/quarkus-startstop/actions/runs/3313239997 - see `ci-artifacts` and explore the directory structure of the zipped content. Alternatively click on `Linux - Native build` to see which test failed.

Issues is not regularly reproducible, we see it in daily GitHub action.

https://github.com/quarkus-qe/quarkus-startstop/actions/workflows/ci.yaml
Screenshot 2022-10-24 at 20 08 28

### Expected behavior

No error

### Actual behavior

~50% of StartStopTS runs hit at least one "Exception in thread "Process stdout" java.lang.RuntimeException: Error reading stream." during native build executions. There are 8 compilations into native binary in one TS run.

### How to Reproduce?

https://github.com/quarkus-qe/quarkus-startstop/actions/workflows/ci.yaml

https://github.com/quarkus-qe/quarkus-startstop/blob/main/.github/workflows/ci.yaml#L60

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

Java 11

### GraalVM version (if different from Java)

ubi-quarkus-native-image:22.2-java17

### Quarkus version or git rev

2.13.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by rsvoboda**
Ignore the error when the stream is closed and try to continue

Fixes https://github.com/quarkusio/quarkus/issues/28799

CC @geoand @zakkak

### CODE REVIEW

File: core/deployment/src/main/java/io/quarkus/deployment/OutputFilter.java [hunk 1]
```diff
@@ -20,7 +20,11 @@ public Runnable apply(InputStream is) {
                     builder.append(line);
                 }
             } catch (IOException e) {
-                throw new RuntimeException("Error reading stream.", e);
+                if (e.getMessage().contains("Stream closed")) {
+                    // let's ignore the error when the stream is closed and try to continue
```
Comment (geoand) [inline core/deployment/src/main/java/io/quarkus/deployment/OutputFilter.java:24]: Maybe we should just log with `warn`?+

Comment (rsvoboda) [reply core/deployment/src/main/java/io/quarkus/deployment/OutputFilter.java:24]: ok, will update it

Comment (rsvoboda) [reply core/deployment/src/main/java/io/quarkus/deployment/OutputFilter.java]: PR updated

**Review by geoand — APPROVED** [review]
LGTM. @zakkak WDYT?

**Comment by zakkak** [comment]
It looks OK to me, but I am not sure it won't just postpone the failure since we will probably not get access to the output which is needed for the native-image build.

**Comment by rsvoboda** [comment]
Native binary is created, let me paste the full log from the build, .

```
[INFO] Scanning for projects...
[INFO] 
[INFO] -------------< io.quarkus.ts.startstop:app-jax-rs-minimal >-------------
[INFO] Building app-jax-rs-minimal 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ app-jax-rs-minimal ---
[INFO] 
[INFO] --- formatter-maven-plugin:2.17.1:format (default) @ app-jax-rs-minimal ---
[INFO] Processed 2 files in 1s24ms (Formatted: 0, Unchanged: 2, Failed: 0, Readonly: 0)
[INFO] 
[INFO] --- impsort-maven-plugin:1.6.2:sort (default) @ app-jax-rs-minimal ---
[INFO] Processed 2 files in 00:00.140 (Already Sorted: 2, Needed Sorting: 0)
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ app-jax-rs-minimal ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ app-jax-rs-minimal ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /home/runner/work/quarkus-startstop/quarkus-startstop/ěščřžýáíéůú/app-jax-rs-minimal/target/classes
[INFO] 
[INFO] --- formatter-maven-plugin:2.17.1:format (default) @ app-jax-rs-minimal ---
[INFO] Processed 2 files in 43ms (Formatted: 0, Unchanged: 2, Failed: 0, Readonly: 0)
[INFO] 
[INFO] --- impsort-maven-plugin:1.6.2:sort (default) @ app-jax-rs-minimal ---
[INFO] Processed 2 files in 00:00.000 (Already Sorted: 2, Needed Sorting: 0)
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ app-jax-rs-minimal ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ app-jax-rs-minimal ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ app-jax-rs-minimal ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/runner/work/quarkus-startstop/quarkus-startstop/ěščřžýáíéůú/app-jax-rs-minimal/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ app-jax-rs-minimal ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ app-jax-rs-minimal ---
[INFO] No tests to run.
[INFO] 
[INFO] --- xml-format-maven-plugin:3.2.0:xml-format (default) @ app-jax-rs-minimal ---
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ app-jax-rs-minimal ---
[INFO] Building jar: /home/runner/work/quarkus-startstop/quarkus-startstop/ěščřžýáíéůú/app-jax-rs-minimal/target/quarkus.jar
[INFO] 
[INFO] --- quarkus-maven-plugin:2.13.3.Final:build (default) @ app-jax-rs-minimal ---
[INFO] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Building native image source jar: /home/runner/work/quarkus-startstop/quarkus-startstop/ěščřžýáíéůú/app-jax-rs-minimal/target/quarkus-native-image-source-jar/quarkus-runner.jar
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Building native image from /home/runner/work/quarkus-startstop/quarkus-startstop/ěščřžýáíéůú/app-jax-rs-minimal/target/quarkus-native-image-source-jar/quarkus-runner.jar
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildContainerRunner] Using docker to run the native image builder
Exception in thread "Process stdout" java.lang.RuntimeException: Error reading stream.
	at io.quarkus.deployment.OutputFilter.lambda$apply$0(OutputFilter.java:23)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: Stream closed
	at java.base/java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:176)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:342)
	at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:181)
	at java.base/java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:326)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:392)
	at io.quarkus.deployment.OutputFilter.lambda$apply$0(OutputFilter.java:19)
	... 1 more
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildContainerRunner] Checking image status quay.io/quarkus/ubi-quarkus-native-image:22.2-java17
22.2-java17: Pulling from quarkus/ubi-quarkus-native-image
Digest: sha256:1e053d8b159dc60ddff94ff471312675d34fe880b69e2effc3aac8ad4944b9bc
Status: Image is up to date for quay.io/quarkus/ubi-quarkus-native-image:22.2-java17
quay.io/quarkus/ubi-quarkus-native-image:22.2-java17
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on GraalVM 22.2.0 Java 17 CE (Java Version 17.0.4+8-jvmci-22.2-b06)
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildRunner] docker run --env LANG=C --rm --user 1001:121 -v /home/runner/work/quarkus-startstop/quarkus-startstop/ěščřžýáíéůú/app-jax-rs-minimal/target/quarkus-native-image-source-jar:/project:z --name build-native-gfQje quay.io/quarkus/ubi-quarkus-native-image:22.2-java17 -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dlogging.initial-configurator.min-level=500 -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=3 -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Duser.language=en -J-Dfile.encoding=UTF-8 --features=io.quarkus.runner.Feature,io.quarkus.runtime.graal.ResourcesFeature,io.quarkus.runtime.graal.DisableLoggingFeature -J--add-exports=java.security.jgss/sun.security.krb5=ALL-UNNAMED -J--add-opens=java.base/java.text=ALL-UNNAMED -J--add-opens=java.base/java.io=ALL-UNNAMED -J--add-opens=java.base/java.lang.invoke=ALL-UNNAMED -J--add-opens=java.base/java.util=ALL-UNNAMED -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy\$BySpaceAndTime -H:+AllowFoldMethods -J-Djava.awt.headless=true --no-fallback --link-at-build-time -H:+ReportExceptionStackTraces -H:-AddAllCharsets --enable-url-protocols=http,https -H:-UseServiceLoaderFeature -H:+StackTrace -J--add-exports=org.graalvm.sdk/org.graalvm.nativeimage.impl=ALL-UNNAMED -J--add-exports=org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk=ALL-UNNAMED -J--add-exports=org.graalvm.nativeimage.builder/com.oracle.svm.core.configure=ALL-UNNAMED -J--add-exports=org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.localization=ALL-UNNAMED quarkus-runner -jar quarkus-runner.jar
WARNING: Unknown module: org.graalvm.nativeimage.llvm specified to --add-exports
WARNING: Unknown module: org.graalvm.nativeimage.llvm specified to --add-exports
WARNING: Unknown module: org.graalvm.nativeimage.llvm specified to --add-exports
========================================================================================================================
GraalVM Native Image: Generating 'quarkus-runner' (executable)...
========================================================================================================================
[1/7] Initializing...                                                                                    (8.5s @ 0.20GB)
 Version info: 'GraalVM 22.2.0 Java 17 CE'
 Java version info: '17.0.4+8-jvmci-22.2-b06'
 C compiler: gcc (redhat, x86_64, 8.5.0)
 Garbage collector: Serial GC
 5 user-specific feature(s)
 - com.oracle.svm.thirdparty.gson.GsonFeature
 - io.quarkus.runner.Feature: Auto-generated class by Quarkus from the existing extensions
 - io.quarkus.runtime.graal.DisableLoggingFeature: Disables INFO logging during the analysis phase for the [org.jboss.threads] categories
 - io.quarkus.runtime.graal.ResourcesFeature: Register each line in META-INF/quarkus-native-resources.txt as a resource on Substrate VM
 - org.graalvm.home.HomeFinderFeature: Finds GraalVM paths and its version number
15:58:50,444 INFO  [org.jbo.res.res.i18n] RESTEASY002225: Deploying javax.ws.rs.core.Application: class com.example.quarkus.QuarkusRestApplication
[2/7] Performing analysis...  [*********]                                                               (78.7s @ 1.18GB)
  11,528 (90.14%) of 12,789 classes reachable
  17,952 (60.12%) of 29,860 fields reachable
  57,375 (57.45%) of 99,864 methods reachable
     484 classes,   119 fields, and 1,641 methods registered for reflection
      63 classes,    68 fields, and    55 methods registered for JNI access
       4 native libraries: dl, pthread, rt, z
[3/7] Building universe...                                                                              (10.3s @ 1.74GB)
[4/7] Parsing methods...      [***]                                                                      (9.2s @ 2.04GB)
[5/7] Inlining methods...     [***]                                                                      (5.3s @ 2.34GB)
[6/7] Compiling methods...    [********]                                                                (68.3s @ 1.45GB)
[7/7] Creating image...                                                                                  (4.8s @ 2.06GB)
  23.13MB (49.56%) for code area:    37,025 compilation units
  23.23MB (49.78%) for image heap:  281,628 objects and 66 resources
 315.05KB ( 0.66%) for other data
  46.68MB in total
------------------------------------------------------------------------------------------------------------------------
Top 10 packages in code area:                               Top 10 object types in image heap:
   1.66MB sun.security.ssl                                     5.07MB byte[] for code metadata
 981.95KB java.util                                            2.74MB java.lang.Class
 733.02KB com.sun.crypto.provider                              2.61MB java.lang.String
 565.18KB java.lang.invoke                                     2.42MB byte[] for general heap data
 475.98KB c.s.org.apache.xerces.internal.impl.xs.traversers    2.05MB byte[] for java.lang.String
 459.89KB java.lang                                          990.69KB com.oracle.svm.core.hub.DynamicHubCompanion
 458.76KB sun.security.x509                                  721.46KB byte[] for embedded resources
 444.70KB com.sun.org.apache.xerces.internal.impl            678.84KB java.util.HashMap$Node
 407.11KB java.io                                            558.81KB byte[] for reflection metadata
 397.23KB io.netty.buffer                                    537.88KB java.lang.String[]
  16.39MB for 435 more packages                                4.54MB for 2728 more object types
------------------------------------------------------------------------------------------------------------------------
                        9.9s (5.2% of total time) in 49 GCs | Peak RSS: 3.38GB | CPU load: 1.95
------------------------------------------------------------------------------------------------------------------------
Produced artifacts:
 /project/quarkus-runner (executable)
 /project/quarkus-runner.build_artifacts.txt (txt)
========================================================================================================================
Finished generating 'quarkus-runner' in 3m 9s.
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildRunner] docker run --env LANG=C --rm --user 1001:121 -v /home/runner/work/quarkus-startstop/quarkus-startstop/ěščřžýáíéůú/app-jax-rs-minimal/target/quarkus-native-image-source-jar:/project:z --entrypoint /bin/bash quay.io/quarkus/ubi-quarkus-native-image:22.2-java17 -c objcopy --strip-debug quarkus-runner
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 195973ms
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:20 min
[INFO] Finished at: 2022-10-24T16:01:47Z
[INFO] ------------------------------------------------------------------------
```

**Comment by geoand** [comment]
Thanks @rsvoboda.

Let's include this fix then.

**Review by zakkak — APPROVED** [review]
