### PR TITLE
Minor keycloak-authorization code and doc updates

### LINKED ISSUE #13838: OIDC/Keycloak Authorization
**Describe the bug**

I am trying to utilize keycloak-authorization extension using [https://quarkus.io/guides/security-keycloak-authorization#configuration-reference](following reference), and running into a null pointer exception.

 
**Expected behavior**

The authorization setup in Keycloak should kick in and decision needs to be made to allow/deny the request.

**Actual behavior**

I get the following exception. Apparently the policyEnforcer is not getting instantiated, but I don't see any issues with the configuration.

2020-12-11 08:12:57,856 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-201) HTTP Request to /useraccounts?email=a@cgmail.com failed, error id: ae6bb5cf-8796-4438-b2e0-3131a5765657-1: java.lang.NullPointerException: Cannot invoke "org.keycloak.adapters.authorization.KeycloakAdapterPolicyEnforcer.authorize(org.keycloak.adapters.OIDCHttpFacade)" because "this.delegate" is null
	at io.quarkus.keycloak.pep.runtime.KeycloakPolicyEnforcerAuthorizer.apply(KeycloakPolicyEnforcerAuthorizer.java:45)
	at io.quarkus.keycloak.pep.runtime.KeycloakPolicyEnforcerAuthorizer.apply(KeycloakPolicyEnforcerAuthorizer.java:29)
	at io.quarkus.vertx.http.runtime.security.HttpAuthorizer$1$1$1.run(HttpAuthorizer.java:72)
	at io.quarkus.runtime.CleanableExecutor$CleaningRunnable.run(CleanableExecutor.java:231)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.base/java.lang.Thread.run(Thread.java:832)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)

**Configuration**
```properties

quarkus.oidc.auth-server-url=http://localhost:8080/auth/realms/Customers
quarkus.oidc.client-id=my-client
quarkus.oidc.credentials.secret=secret
quarkus.oidc.tls.verification=none

quarkus.keycloak.policy-enforcer.paths.1.name=User Accounts Resource
quarkus.keycloak.policy-enforcer.paths.1.path=/useracounts
quarkus.keycloak.policy-enforcer.paths.1.methods.1.method=GET
quarkus.keycloak.policy-enforcer.paths.1.methods.1.scopes=read
quarkus.keycloak.policy-enforcer.paths.1.methods.2.method=POST
quarkus.keycloak.policy-enforcer.paths.1.methods.2.scopes=create
quarkus.keycloak.policy-enforcer.paths.1.methods.3.method=DELETE
quarkus.keycloak.policy-enforcer.paths.1.methods.3.scopes=delete
quarkus.keycloak.policy-enforcer.paths.1.methods.4.method=PUT
quarkus.keycloak.policy-enforcer.paths.1.methods.4.scopes=update


```

**Environment (please complete the following information):**
Darwin MacBook-Air.local 20.1.0 Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:10 PDT 2020; root:xnu-7195.50.7~2/RELEASE_ARM64_T8101 arm64
openjdk version "15.0.1" 2020-10-20
OpenJDK Runtime Environment (build 15.0.1+9)
OpenJDK 64-Bit Server VM (build 15.0.1+9, mixed mode, sharing)

Gral VM: Not using

Quarkus: 1.7.1.Final

Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /Users/lalithakulkarni/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3
Java version: 15.0.1, vendor: N/A, runtime: /usr/local/Cellar/openjdk/15.0.1/libexec/openjdk.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "11.0.1", arch: "x86_64", family: "mac"

**Additional context**

### PR DESCRIPTION
**Pull request by sberyozkin**
Fixes #13838

Also a minor doc fix

### CODE REVIEW

File: extensions/keycloak-authorization/runtime/src/main/java/io/quarkus/keycloak/pep/runtime/KeycloakPolicyEnforcerAuthorizer.java [hunk 1]
```diff
@@ -43,6 +46,11 @@
 
     @Override
     public CheckResult apply(RoutingContext routingContext, SecurityIdentity identity) {
+        if (delegate == null) {
+            LOG.debug(
+                    "Keycloak Policy Enforcer has not been initialized - please make sure 'quarkus.oidc.enabled' is not set to 'false'");
```
Comment (gastaldi) [inline extensions/keycloak-authorization/runtime/src/main/java/io/quarkus/keycloak/pep/runtime/KeycloakPolicyEnforcerAuthorizer.java:51]: I think debug logs like this should also be in the `init` method, since it seems that method returns prematurely in this case

File: extensions/keycloak-authorization/runtime/src/main/java/io/quarkus/keycloak/pep/runtime/KeycloakPolicyEnforcerAuthorizer.java [hunk 2]
```diff
@@ -43,6 +46,11 @@
...
+            throw new AuthenticationFailedException();
+        }
```
Comment (gastaldi) [inline extensions/keycloak-authorization/runtime/src/main/java/io/quarkus/keycloak/pep/runtime/KeycloakPolicyEnforcerAuthorizer.java:53]: Can we also explain why the Authentication failed to the caller here?

File: extensions/keycloak-authorization/runtime/src/main/java/io/quarkus/keycloak/pep/runtime/KeycloakPolicyEnforcerAuthorizer.java (hunk 1 above)
Comment (sberyozkin) [reply extensions/keycloak-authorization/runtime/src/main/java/io/quarkus/keycloak/pep/runtime/KeycloakPolicyEnforcerAuthorizer.java:51]: @gastaldi sure, it is just the way it is currently implemented that a recorder calls the initialization method only if that property is enabled, so the user disabled it, forgot to re-enable and got NPE, so this issue is just about avoiding NPE and saying somethng useful... Pedro @pedroigor is managing this extension, I only venture with some basic fixes into it :-).
Perhaps indeed a deeper refactoring is required here

File: extensions/keycloak-authorization/runtime/src/main/java/io/quarkus/keycloak/pep/runtime/KeycloakPolicyEnforcerAuthorizer.java (hunk 2 above)
Comment (sberyozkin) [reply extensions/keycloak-authorization/runtime/src/main/java/io/quarkus/keycloak/pep/runtime/KeycloakPolicyEnforcerAuthorizer.java:53]: I was thinking, since this code is executed as part of the user authentication process, it should be 401. In fact first I coded an `IllegalStateException` but then I changed my mind, but now that you asked, I wonder if returning 500 would be best as it is really a server configuration issue. What would you prefer yourself ?

Comment (gastaldi) [reply extensions/keycloak-authorization/runtime/src/main/java/io/quarkus/keycloak/pep/runtime/KeycloakPolicyEnforcerAuthorizer.java:53]: Returning 500 makes more sense to me

Comment (sberyozkin) [reply extensions/keycloak-authorization/runtime/src/main/java/io/quarkus/keycloak/pep/runtime/KeycloakPolicyEnforcerAuthorizer.java:53]: @gastaldi thanks, I'll fix during the next few of days, have to sign off now, thanks for starting the review, enjoy the weekend :-)

File: extensions/keycloak-authorization/runtime/src/main/java/io/quarkus/keycloak/pep/runtime/KeycloakPolicyEnforcerAuthorizer.java (hunk 1 above)
Comment (sberyozkin) [reply extensions/keycloak-authorization/runtime/src/main/java/io/quarkus/keycloak/pep/runtime/KeycloakPolicyEnforcerAuthorizer.java:51]: @gastaldi I'll have a quick look as well if it can be caught earlier, there must be a way

File: extensions/keycloak-authorization/runtime/src/main/java/io/quarkus/keycloak/pep/runtime/KeycloakPolicyEnforcerAuthorizer.java (hunk 2 above)
Comment (gastaldi) [reply extensions/keycloak-authorization/runtime/src/main/java/io/quarkus/keycloak/pep/runtime/KeycloakPolicyEnforcerAuthorizer.java:53]: Likewise, have fun! 😉

**Comment by sberyozkin** [comment]
Sorry @gastaldi - I'm finalizing the oidc-client rather large PR so have to put this one on hold for now but yeah, we'll sort this one out for sure :-)

**Comment by gastaldi** [comment]
No worries, take your time @sberyozkin 😉

**Comment by gsmet** [comment]
Could we either finalize this one or close it? I see a lot of other PRs open related to security and we really need to reduce the number of PRs that are pending.

**Comment by pedroigor** [comment]
@sberyozkin perhaps we can remove your change to solve the NPE (when oidc is disabled) and only get the docs updated?

I'm going to work on this one this week.

**Comment by sberyozkin** [comment]
Hi @gastaldi, @pedroigor, we have had this NPE reported today again - I'd like to propose to go ahead with this intermediate fix for it to make it to `1.13.0.Final` and i can open an issue to have the recorder refactored to have `KeycloakpolicyEnforcerAuthorizer` registered as a synthetic bean, what do you think ?

**Review by pedroigor — APPROVED** [review]

**Review by gastaldi — APPROVED** [review]

**Comment by sberyozkin** [comment]
I have a draft PR on the way
