### PR TITLE
Fail at build time if SpEL is used in @Value

### LINKED ISSUE #19368: Spring Properties: Can't inject values using complex SpEL
### Describe the bug

Having this class:

```
@RestController
@RequestMapping("/values")
public class ValueController {

    @Value("${values.text}")
    String fieldUsingValue; // works

    @Value("${values.list}")
    String[] fieldUsingArray; // works

    @Value("#{'${values.list}'.split(',')}")
    List<String> fieldUsingList; // does not work

    @Value("#{${values.map}}")
    Map<String, String> fieldUsingMap; // does not work

   // ...
}
```

Note the SpEL expressions I checked and that according to the Spring documentation should work.
This is the application properties I'm using:

```
values.text=hello
values.list=A,B
values.map={key1: '1', key2: '2', key3: '3'}
```

### Expected behavior

To be honest, I'm not sure how complex is to make the SpEL engine to work using the Quarkus configuration engine.
If this is too complex, I guess we should note this limitation in the Spring Properties guide.

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #19368

### CODE REVIEW

File: extensions/spring-di/deployment/src/main/java/io/quarkus/spring/di/deployment/SpringDIProcessor.java [hunk 1]
```diff
@@ -522,7 +522,12 @@ private void addSpringValueAnnotations(AnnotationTarget target, AnnotationInstan
             return;
         }
         String defaultValue = null;
-        String propertyName = annotationValue.asString().replace("${", "").replace("}", "");
+        String stringValue = annotationValue.asString();
+        if (stringValue.contains("#{")) {
+            throw new IllegalArgumentException(
+                    "SpEL expressions are not supported when using " + SPRING_VALUE_ANNOTATION.toString());
```
Comment (gsmet) [inline extensions/spring-di/deployment/src/main/java/io/quarkus/spring/di/deployment/SpringDIProcessor.java:528]: Could you print the expression in the error message?

Comment (geoand) [reply extensions/spring-di/deployment/src/main/java/io/quarkus/spring/di/deployment/SpringDIProcessor.java]: Good idea. Done

**Review by gsmet — APPROVED** [review]
