### PR TITLE
Scheduler: register ApplicationNotRunning as bean even if quartz is used

### LINKED ISSUE #37417: Build fails when using the Quartz extension and @Scheduled(..., skipExecutionIf = Scheduled.ApplicationNotRunning.class)
### Describe the bug

When using the Quarkus Quartz extension (https://quarkus.io/guides/quartz) with `@Scheduled(..., skipExecutionIf = Scheduled.ApplicationNotRunning.class)` the build fails with the following exception:

```
2023-11-30 09:57:44,529 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (vert.x-worker-thread-1) Failed to start quarkus [Error Occurred After Shutdown]: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#generateResources threw an exception: jakarta.enterprise.inject.spi.DeploymentException: java.lang.IllegalStateException: There must be exactly one bean that matches the skip predicate: "io.quarkus.scheduler.Scheduled$ApplicationNotRunning" on: @Scheduled(every = "10s",identity = "task-job",skipExecutionIf = io.quarkus.scheduler.Scheduled$ApplicationNotRunning)
	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1447)
	at io.quarkus.arc.processor.BeanProcessor.processValidationErrors(BeanProcessor.java:178)
	at io.quarkus.arc.deployment.ArcProcessor.generateResources(ArcProcessor.java:501)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at java.base/java.lang.Thread.run(Thread.java:840)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

The same error has occurred before, but without Quartz: https://github.com/quarkusio/quarkus/issues/19900

When a clone of the bean `io.quarkus.scheduler.Scheduled.ApplicationNotRunning` is declared (lets say `MyApplicationNotRunning`) in the application and then used in `@Scheduled(..., skipExecutionIf = MyApplicationNotRunning.class)`, it works.

### Expected behavior

The build should succeed without an error message and behave as expected: https://quarkus.io/guides/scheduler-reference#conditional_execution. 

### Actual behavior

An exception occurred during the build

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mkouba**
- fixes #37417

### CODE REVIEW

File: integration-tests/opentelemetry-quartz/src/test/java/io/quarkus/it/opentelemetry/quartz/OpenTelemetryQuartzTest.java [hunk 1]
```diff
@@ -28,9 +28,9 @@ public class OpenTelemetryQuartzTest {
     @Test
     public void quartzSpanTest() {
         // ensure that scheduled job is called
-        assertCounter("/scheduler/count", 1, Duration.ofSeconds(1));
+        assertCounter("/scheduler/count", 3, Duration.ofSeconds(1));
```
Comment (mkouba) [inline integration-tests/opentelemetry-quartz/src/test/java/io/quarkus/it/opentelemetry/quartz/OpenTelemetryQuartzTest.java:31]: CC @mskacelik

**Comment by mkouba** [comment]
@gsmet FYI the second commit should fix a problem with flaky OpenTelemetry integration tests.

**Comment by gsmet** [comment]
> FYI the second commit should fix a problem with flaky OpenTelemetry integration tests.

Awesome!

**Review by gsmet — APPROVED** [review]
