### PR TITLE
Remove lock icon for runtime config overrides

### LINKED ISSUE #32229: new devui shows locks  for both locked at build time and not build time
### Describe the bug

in old dev ui and https://quarkus.io/guides/all-config we use a black lock to mark build time properties.

we do not use colour (as some are color blinds) and we don't show locks for both as it gets harder to easily spot the exception (i.e. build time config)

### Expected behavior

use the same visuals as elsewhere in shape of a black lock for locked configs and no icon for the normal case.

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by gastaldi**
- Remove the lock icon from the fixed property icon in the qwc-configuration.js file
- Remove the lock icon for config values that are overridable at runtime in the config.html file
- Fixes #32229

image

### CODE REVIEW

**Review by maxandersen — APPROVED** [review]
looks good! LGTM!

File: extensions/vertx-http/dev-ui-resources/src/main/resources/dev-ui/qwc/qwc-configuration.js [hunk 1]
```diff
@@ -65,11 +65,9 @@ export class QwcConfiguration extends LitElement {
       }
       
       .lock-icon {
-        color: var(--lumo-error-color-50pct);
```
Comment (phillip-kruger) [inline extensions/vertx-http/dev-ui-resources/src/main/resources/dev-ui/qwc/qwc-configuration.js:68]: I would keep color in here, but just make it another color. Black is too "in your face" How about `--lumo-contrast-60pct` (see https://vaadin.com/docs/v23/styling/lumo/design-tokens/color)

**Review by phillip-kruger — CHANGES_REQUESTED** [review]

File: extensions/vertx-http/dev-ui-resources/src/main/resources/dev-ui/qwc/qwc-configuration.js (hunk 1 above)
Comment (gastaldi) [reply extensions/vertx-http/dev-ui-resources/src/main/resources/dev-ui/qwc/qwc-configuration.js:68]: I like it, it matches the `Filter` icon color too. I'll update it 

Night mode: 
image

Day mode:
image

Comment (phillip-kruger) [reply extensions/vertx-http/dev-ui-resources/src/main/resources/dev-ui/qwc/qwc-configuration.js:68]: Nice!

**Review by phillip-kruger — APPROVED** [review]
LGTM! Thanks !
