### PR TITLE
Fix OTel MDC context set

### LINKED ISSUE #43134: OpenTelemetry: MDC context disappears on ManagedExecutor thread
### Describe the bug

Given 
* a Quarkus application with installed extensions: quarkus-rest, quarkus-opentelemetry
* the ManagedExecutor is used to execute work in the background
* the background work contains log statements

Simplified code sample:
```java
        managedExecutor.execute(() -> {

            executeWorkOnWorkerThread();

            log.info("hello() from ManagedExecutor");
        });
```

As per my investigation, the "main" thread is calling `OpenTelemetryUtil#clearMDCData(io.vertx.core.Context vertxContext)`, causing the MDC data to be cleared for the "worker" thread as well. 

### Expected behavior

The tracing specific MDC context is available for log statements of the background work/thread.

### Actual behavior

The tracing specific MDC context is not available for log statements. 

Sample logging (assuming `quarkus.log.console.format` is configured to include MDC.traceId) 
```
2024-09-09 10:12:50,788 INFO  traceId= [org.acm.GreetingResource] (executor-thread-1) hello() from ManagedExecutor
```

### How to Reproduce?

Reproducer: https://github.com/kerkhofsd/quarkus-issue-otel-clears-mdc

### Output of `uname -a` or `ver`

WSL Ubuntu 24.04.1 LTS

### Output of `java -version`

openjdk version "21.0.4" 2024-07-16

### Quarkus version or git rev

3.14.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.8 (36645f6c9b5079805ea5009217e36f2cffd34256)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by brunobat**
There are 2 fixes here: 
- Make sure we clear the reference for the VertxMDC reference before we add more data there. If we don't do that, that reference will end up being used in multiple threads and be subject to crosstalk.
- When we close the scope, we were restoring previous scopes from spans that were already finished.

Did some refactoring to clarify context objects because we have too many types of contexts. 
Added some debug logs for future debugging. 

- Fixes: https://github.com/quarkusio/quarkus/issues/43134

### CODE REVIEW

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/OpenTelemetryUtil.java [hunk 1]
```diff
@@ -49,20 +54,27 @@ public static Map<String, String> convertKeyValueListToMap(List<String> headers)
...
+        if (otelContext == null) {
             return;
         }
 
-        Span span = Span.fromContextOrNull(context);
+        Span span = Span.fromContextOrNull(otelContext);
         if (span != null) {
+            logger.debugv("Setting span in MDC: {0} with otel data in vertx context: {1}",
+                    getSpanData(otelContext),
+                    getSpanData(QuarkusContextStorage.getOtelContext(vertxContext)));
```
Comment (geoand) [inline extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/OpenTelemetryUtil.java]: Let's put this in an `if (logger.isDebugEnabled())` as it performs operations that will not be used most of the time.

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/OpenTelemetryUtil.java [hunk 2]
```diff
@@ -109,6 +121,9 @@ public static Map<String, String> getSpanData(Context context) {
      */
     public static void clearMDCData(io.vertx.core.Context vertxContext) {
         VertxMDC vertxMDC = VertxMDC.INSTANCE;
+        logger.debugv("Removing from MDC the span id: {0}, with otel data in vertx context: {1}",
+                vertxMDC.get(SPAN_ID, vertxContext),
+                getSpanData(QuarkusContextStorage.getOtelContext(vertxContext)));
```
Comment (geoand) [inline extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/OpenTelemetryUtil.java]: Same here

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/QuarkusContextStorage.java [hunk 3]
```diff
@@ -59,32 +60,49 @@ public Scope attach(io.vertx.core.Context vertxContext, Context toAttach) {
...
 
-        Context beforeAttach = getContext(vertxContext);
-        if (toAttach == beforeAttach) {
+        Context otelBeforeAttach = getOtelContext(vertxContext);
+        if (otelToAttach == otelBeforeAttach) {
             return Scope.noop();
         }
-        vertxContext.putLocal(OTEL_CONTEXT, toAttach);
-        OpenTelemetryUtil.setMDCData(toAttach, vertxContext);
+        log.debugv("Setting Otel context: {0}", OpenTelemetryUtil.getSpanData(otelToAttach));
```
Comment (geoand) [inline extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/QuarkusContextStorage.java]: And here

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/QuarkusContextStorage.java [hunk 4]
```diff
@@ -59,32 +60,49 @@ public Scope attach(io.vertx.core.Context vertxContext, Context toAttach) {
...
 
         return new Scope() {
 
             @Override
             public void close() {
-                final Context before = getContext(vertxContext);
-                if (before != toAttach) {
+                // compare otel contexts when closing scope
+                final Context otelBefore = getOtelContext(vertxContext);
+                log.debugv("Closing Otel context: {0}", OpenTelemetryUtil.getSpanData(otelToAttach));
```
Comment (geoand) [inline extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/QuarkusContextStorage.java]: Here too

**Review by geoand — COMMENTED** [review]
Very nice work!

I only added some trivial comments

**Comment by brunobat** [comment]
@geoand I was commenting here: https://github.com/quarkusio/quarkus/issues/49630#issuecomment-3674337854
And I think I will add a method in `VertxMDC` to clear the context there to create awareness to this issue.

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/OpenTelemetryUtil.java (hunk 1 above)
Comment (brunobat) [reply extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/OpenTelemetryUtil.java]: Thanks! Done

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/OpenTelemetryUtil.java (hunk 2 above)
Comment (brunobat) [reply extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/OpenTelemetryUtil.java]: done

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/QuarkusContextStorage.java (hunk 3 above)
Comment (brunobat) [reply extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/QuarkusContextStorage.java]: done

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/QuarkusContextStorage.java (hunk 4 above)
Comment (brunobat) [reply extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/QuarkusContextStorage.java]: done

**Review by geoand — APPROVED** [review]
Great work!

**Comment by brunobat** [comment]
Failures seem unrelated. Will merge.

**Comment by brunobat** [comment]
@gsmet We should consider this to backport, if possible.
