### PR TITLE
Port resteasy fix for sub-resources

### LINKED ISSUE #42851: classic resteasy-client: ensure sub-resources are also proxied
### Describe the bug

resteasy [resteasy-microprofile](https://github.com/resteasy/resteasy-microprofile) "recently" applied a bugfix that makes sure, that sub-resources to a microprofile client are also proxied properly.

* their bug report -> https://github.com/resteasy/resteasy-microprofile/issues/239
* their pr -> https://github.com/resteasy/resteasy-microprofile/pull/241

Given that in `quarkus-rest-client` the class `QuarkusProxyInvocationHandler`  duplicates their `ProxyInvocationHandler` and `QuarkusRestClientBuilder` duplicates their `RestClientBuilderImpl` ... both should be updated accordingly.

### Expected behavior

sub-resources are properly proxied, like they are with resteasy's microprofile client implementation.

### Actual behavior

sub-resources aren't proxied.

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

Darwin Stefans-Air.localdomain 23.6.0 Darwin Kernel Version 23.6.0: Mon Jul 29 21:16:46 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T8112 arm64

### Output of `java -version`

openjdk version "21.0.2" 2024-01-16 OpenJDK Runtime Environment GraalVM CE 21.0.2+13.1 (build 21.0.2+13-jvmci-23.1-b30) OpenJDK 64-Bit Server VM GraalVM CE 21.0.2+13.1 (build 21.0.2+13-jvmci-23.1-b30, mixed mode, sharing)

### Quarkus version or git rev

3.8.5 and/or 3.14.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Java version: 21.0.2, vendor: GraalVM Community, runtime: /Users/stefansiegl/.sdkman/candidates/java/21.0.2-graalce Default locale: de_DE, platform encoding: UTF-8 OS name: "mac os x", version: "14.6.1", arch: "aarch64", family: "mac"

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by maxr2011-tech11**
Port resteasy fix for sub-resources from https://github.com/resteasy/resteasy-microprofile/pull/241

- Closes: #42851

### CODE REVIEW

File: extensions/resteasy-classic/resteasy-client/runtime/src/main/java/io/quarkus/restclient/runtime/QuarkusProxyInvocationHandler.java [hunk 1]
```diff
@@ -1,12 +1,10 @@
...
 
+import java.io.Closeable;
 import java.lang.annotation.Annotation;
-import java.lang.reflect.InvocationHandler;
-import java.lang.reflect.InvocationTargetException;
-import java.lang.reflect.Method;
-import java.lang.reflect.Modifier;
-import java.lang.reflect.ParameterizedType;
-import java.lang.reflect.Type;
+import java.lang.reflect.*;
```
Comment (geoand) [inline extensions/resteasy-classic/resteasy-client/runtime/src/main/java/io/quarkus/restclient/runtime/QuarkusProxyInvocationHandler.java:5]: Please avoid star imports (they are usually added automatically by the IDE, but it can be configured to not do so)

**Review by geoand — COMMENTED** [review]
Thanks a lot for tackling this!

I'll leave this to @manovotn and @jamezp  to review. I just added a trivial comment.

Also keep in mind that when all the changes have been done, we'll need the commits to be squashed. 

Finally, having a test verifying the change would be nice

**Comment by gsmet** [comment]
I concur it would be very nice to have a test. You should be able to add one in the `deployment` module (and worst case in the corresponding `integration-tests` module).

File: extensions/resteasy-classic/resteasy-client/runtime/src/main/java/io/quarkus/restclient/runtime/QuarkusProxyInvocationHandler.java [hunk 2]
```diff
@@ -299,4 +382,20 @@ private static Annotation[] merge(List<Annotation> methodLevelBindings, List<Ann
         return merged.toArray(new Annotation[] {});
     }
 
+    private static ClassLoader getClassLoader(final Class<?> type) {
+        if (System.getSecurityManager() == null) {
```
Comment (manovotn) [inline extensions/resteasy-classic/resteasy-client/runtime/src/main/java/io/quarkus/restclient/runtime/QuarkusProxyInvocationHandler.java:386]: I don't think we need to handle SM or priviledged actions in Quarkus; you should be able to safely remove that.

**Comment by manovotn** [comment]
@maxr2011-tech11 please try to add a test for this change. The resteasy-microprofile PR you linked also has one, so it should be a matter of mimicking that same scenario here in the `deployment` module of this extension.

Otherwise, it looks OK.

File: extensions/resteasy-classic/resteasy-client/runtime/src/main/java/io/quarkus/restclient/runtime/QuarkusProxyInvocationHandler.java (hunk 2 above)
Comment (maxr2011) [reply extensions/resteasy-classic/resteasy-client/runtime/src/main/java/io/quarkus/restclient/runtime/QuarkusProxyInvocationHandler.java:386]: so just `type.getClassLoader()` ? as this only has just one usage I would directly inline it

Comment (maxr2011) [reply extensions/resteasy-classic/resteasy-client/runtime/src/main/java/io/quarkus/restclient/runtime/QuarkusProxyInvocationHandler.java:386]: in createProxy:273 
`final Object proxy = Proxy.newProxyInstance(resourceInterface.getClassLoader(), interfaces,
                new ProxyInvocationHandler(resourceInterface, target, Set.copyOf(providers), client));`

**Comment by maxr2011** [comment]
@manovotn just added the SubResourceTest to the deployment module of the resteasy-classic/resteasy-client extension. also I did rewrite it a bit to use the quarkus integrated rest client inside the internal quarkus junit module instead of the Arquillian extension which resteasy uses (not sure if this works out)

**Comment by maxr2011** [comment]
@geoand 
@manovotn 

The pipeline checks report, that there are some tests failing, specifically those where a rest client is involved, so it has to be something in the code. No idea what it could be since I am not that deeply into the implementation of the rest client, maybe you could have a look or involve someone who has more insights?

CC @stesie

**Comment by manovotn** [comment]
> @geoand @manovotn
> 
> The pipeline checks report, that there are some tests failing, specifically those where a rest client is involved, so it has to be something in the code. No idea what it could be since I am not that deeply into the implementation of the rest client, maybe you could have a look or involve someone who has more insights?
> 
> CC @stesie

First of all, the test you added doesn't pass.
You can run that easily locally by building quarkus and then running the test:
* Fast build with - `mvn -Dquickly -Dno-test-modules -Dskip.gradle.build=true -T 4C`
* Execute the test you added with - `mvn clean test -Dtest=SubResourceTest -f extensions/resteasy-classic/resteasy-client/deployment/`

From a quick glance, you forgot to register the exception mapper to the rest client builder. This affects two of the tests.
So instead of:
```
        try (final ClientRootResource rootResource = RestClientBuilder.newBuilder().baseUrl(url)
                .build(ClientRootResource.class)) {
```

You want to do:

```
        try (final ClientRootResource rootResource = RestClientBuilder.newBuilder().baseUrl(url)
                .register(TestExceptionMapper.class)
                .build(ClientRootResource.class)) {
```

**Comment by manovotn** [comment]
@maxr2011-tech11 I've pushed a commit fixing the test since I already had it locally.

I also added `@Unremovable` to the exception mapper - if it is supposed to be a bean (which I don't know?) you will need that as otherwise Quarkus will sweep it away as unused because it has no direct injection points.
Without the annotation, you can see a CDI warning in the output where some internals attempt to resolve it but fail.

**Comment by maxr2011** [comment]
> @maxr2011-tech11 I've pushed a commit fixing the test since I already had it locally.
> 
> I also added `@Unremovable` to the exception mapper - if it is supposed to be a bean (which I don't know?) you will need that as otherwise Quarkus will sweep it away as unused because it has no direct injection points. Without the annotation, you can see a CDI warning in the output where some internals attempt to resolve it but fail.

Thx I have also another commit to simplify, will test everything and then squash the commits :+1:

**Comment by manovotn** [comment]
Ok, there are now three failing tests in this module:

```
[ERROR] Errors: 
[ERROR]   AsyncRestClientFallbackTest.testFallbackWasUsed:39 » Execution jakarta.ws.rs.WebApplicationException: Unknown error, status code 404
[ERROR]   RestClientFallbackTest.testFallbackWasUsed:35 » WebApplication Unknown error, status code 404
[ERROR]   RestClientInterceptorTest.testInterception:43 » WebApplication Unknown error, status code 404
```

I don't know much about the impl but I can try and debug tomorrow to see if I can spot anything.
All three tests would be using interceptors so something in the creation of proxy and its custom interceptor chain  (which is what `QuarkusProxyInvocationHandler` is for) must have been affected.

**Comment by maxr2011** [comment]
> Ok, there are now three failing tests in this module:
> 
> ```
> [ERROR] Errors: 
> [ERROR]   AsyncRestClientFallbackTest.testFallbackWasUsed:39 » Execution jakarta.ws.rs.WebApplicationException: Unknown error, status code 404
> [ERROR]   RestClientFallbackTest.testFallbackWasUsed:35 » WebApplication Unknown error, status code 404
> [ERROR]   RestClientInterceptorTest.testInterception:43 » WebApplication Unknown error, status code 404
> ```
> 
> I don't know much about the impl but I can try and debug tomorrow to see if I can spot anything. All three tests would be using interceptors so something in the creation of proxy and its custom interceptor chain (which is what `QuarkusProxyInvocationHandler` is for) must have been affected.

seems like Fallbacks and Interceptors won't work with this solution, wonder how this works inside the official resteasy implementation with another runtime (and if its supposed to be working like that)

**Comment by maxr2011** [comment]
Another thing I just found out: the change inside my pull-request does not cover all scenarios, since the RestClient can also be created via the annotation: @RegisterRestClient and injected via @Inject @RestClient as it is done conveniently in many tests.

Seems like this won't use the QuarkusRestClientBuilder (where we did the change)

**Comment by maxr2011** [comment]
@manovotn Just finalized the pull-request and fixed the issue inside the QuarkusProxyInvocationHandler:createProxy method to work again for the QuarkusRestClientBuilder, also cleaned up the Test.

-> Pipeline Checks should now be passing

CC @geoand @stesie

**Comment by geoand** [comment]
I have launched CI

**Comment by manovotn** [comment]
> @manovotn Just finalized the pull-request and fixed the issue inside the QuarkusProxyInvocationHandler:createProxy method to work correctly for the QuarkusRestClientBuilder, also cleaned up the Test.
> 
> -> Pipeline Checks should now be passing
> 
> CC @geoand @stesie

Right, I was just looking into it.
I do have a silly question though - what is the difference between the test you are using now and the original one you added? You are no longer using `QuarkusRestClientBuilder` API. Does that make a difference?

File: extensions/resteasy-classic/resteasy-client/deployment/src/test/java/io/quarkus/restclient/exception/SubResourceTest.java [hunk 3]
```diff
@@ -0,0 +1,167 @@
...
+        }
+
+        @GET
+        @Path("/sub/global/header")
+        public Response subGlobalHeader(@HeaderParam("test-global-header") final String value) {
+            return Response.ok(value).build();
+        }
+    }
+
+    @Provider
```
Comment (manovotn) [inline extensions/resteasy-classic/resteasy-client/deployment/src/test/java/io/quarkus/restclient/exception/SubResourceTest.java:154]: This shouldn't be needed.
Removing it gets rid of the `WARN` log.

Comment (maxr2011) [reply extensions/resteasy-classic/resteasy-client/deployment/src/test/java/io/quarkus/restclient/exception/SubResourceTest.java]: just removed it

**Comment by manovotn** [comment]
> Just found out during debugging. So it should work either way.

Yes, I also found that out through debugging. 
I was just curious why you changed it :)

> But if you want I can add additional tests that use the QuarkusRestClientBuilder instead of the Annotations (but I don't think that would be necessary, since also the other test classes in general prefer to use the Annotations)

Since we now know it is used in either approach, you can keep it as is.

Assuming the CI passes, I have no further issues with this PR but we should wait for @jamezp to take a look as well.

File: extensions/resteasy-classic/resteasy-client/deployment/src/test/java/io/quarkus/restclient/exception/SubResourceTest.java [hunk 4]
```diff
@@ -0,0 +1,165 @@
...
+    ClientRootResource clientRootResource;
+
+    /**
+     * Creates a REST client with an attached exception mapper. The exception mapper will throw a {@link TestException}.
+     * This test invokes a call to the root resource.
+     *
+     */
+    @Test
+    public void rootResourceExceptionMapper() {
+        try (final Response ignored = clientRootResource.fromRoot()) {
```
Comment (jamezp) [inline extensions/resteasy-classic/resteasy-client/deployment/src/test/java/io/quarkus/restclient/exception/SubResourceTest.java:50]: This might be minor, but `final` is redundant for resources like this. Some projects check-styles fail on this.

File: extensions/resteasy-classic/resteasy-client/deployment/src/test/java/io/quarkus/restclient/exception/SubResourceTest.java [hunk 5]
```diff
@@ -0,0 +1,165 @@
...
+        }
+
+        @GET
+        @Path("/sub/global/header")
+        public Response subGlobalHeader(@HeaderParam("test-global-header") final String value) {
+            return Response.ok(value).build();
+        }
+    }
+
+    public static class TestExceptionMapper implements ResponseExceptionMapper<TestException> {
```
Comment (jamezp) [inline extensions/resteasy-classic/resteasy-client/deployment/src/test/java/io/quarkus/restclient/exception/SubResourceTest.java:153]: Does this need a CDI qualifying annotation?

Comment (maxr2011) [reply extensions/resteasy-classic/resteasy-client/deployment/src/test/java/io/quarkus/restclient/exception/SubResourceTest.java:155]: will annotate it as 'Singleton' since it is also registered as @Provider it should be fine either way

File: extensions/resteasy-classic/resteasy-client/deployment/src/test/java/io/quarkus/restclient/exception/SubResourceTest.java (hunk 4 above)
Comment (maxr2011) [reply extensions/resteasy-classic/resteasy-client/deployment/src/test/java/io/quarkus/restclient/exception/SubResourceTest.java]: just removed it

**Review by maxr2011 — APPROVED** [review]

File: extensions/resteasy-classic/resteasy-client/deployment/src/test/java/io/quarkus/restclient/exception/SubResourceTest.java (hunk 5 above)
Comment (manovotn) [reply extensions/resteasy-classic/resteasy-client/deployment/src/test/java/io/quarkus/restclient/exception/SubResourceTest.java:155]: There is no annotation needed here but it doesn't really matter that it is present.

**Review by jamezp — APPROVED** [review]

**Review by manovotn — APPROVED** [review]

**Comment by manovotn** [comment]
@maxr2011-tech11 thanks for contributing! 👍
