### PR TITLE
Fix CDI request context not active during concurrent token refresh

### LINKED ISSUE #53748: OIDC: ContextNotActiveException during concurrent token refresh
### Describe the bug

When using `quarkus.oidc.token.refresh-expired`, expired access tokens will automatically get refreshed by quarkus. If this happens in multiple requests at the same time, it's possible to run into a `ContextNotActiveException`

### Expected behavior

No exceptions should happen

### Actual behavior

```
ERROR [io.quarkus.vertx.http.runtime.QuarkusErrorHandler] (vert.x-eventloop-thread-2) HTTP Request to /hello failed, error id: 0be5d9ed-3c8a-416a-ba11-b58cb4ce427b-91: jakarta.enterprise.context.ContextNotActiveException: RequestScoped context was not active when trying to obtain a bean instance for a client proxy of CLASS bean [class=io.quarkus.vertx.http.runtime.CurrentVertxRequest, id=ZMes0Yo6HsWixdWYNWZOvMsRHzQ]
        - you can activate the request context for a specific method using the @ActivateRequestContext interceptor binding
        at io.quarkus.arc.impl.ClientProxies.notActive(ClientProxies.java:76)                                                                                                                           
        at io.quarkus.arc.impl.ClientProxies.getSingleContextDelegate(ClientProxies.java:32)                                                                                                            
        at io.quarkus.vertx.http.runtime.CurrentVertxRequest_ClientProxy.arc$delegate(Unknown Source)                                                                                                   
        at io.quarkus.vertx.http.runtime.CurrentVertxRequest_ClientProxy.setCurrent(Unknown Source)                                                                                                     
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusCurrentRequest.set(QuarkusCurrentRequest.java:33)                                                                                         
        at org.jboss.resteasy.reactive.server.core.CurrentRequestManager.set(CurrentRequestManager.java:12)                                                                                             
        at org.jboss.resteasy.reactive.server.core.ResteasyReactiveRequestContext.handleRequestScopeActivation(ResteasyReactiveRequestContext.java:721)                                                 
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.handleRequestScopeActivation(QuarkusResteasyReactiveRequestContext.java:43)                                
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.requireCDIRequestScope(AbstractResteasyReactiveContext.java:265)                                                     
        at org.jboss.resteasy.reactive.server.handlers.ResponseWriterHandler.handle(ResponseWriterHandler.java:27)                                                                                      
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:196)                                              
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)                                                                        
        at org.jboss.resteasy.reactive.server.vertx.VertxResteasyReactiveRequestContext$1$1.handle(VertxResteasyReactiveRequestContext.java:93)                                                         
        at org.jboss.resteasy.reactive.server.vertx.VertxResteasyReactiveRequestContext$1$1.handle(VertxResteasyReactiveRequestContext.java:90)                                                         
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:270)                                                                                                                        
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:252)                                                                                                                        
        at io.vertx.core.impl.ContextInternal.lambda$runOnContext$0(ContextInternal.java:50)                                                                                                            
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)                                                                                                       
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)                                                                                                   
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)                                                                                           
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)                                                                                                                                 
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:998)                                                                                                 
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)                                                                                                                    
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)                                                                                                        
        at java.base/java.lang.Thread.run(Thread.java:1474)
```

### How to Reproduce?

Reproducer:  [code-with-quarkus.zip](https://github.com/user-attachments/files/26966243/code-with-quarkus.zip)

 - run `./mvnw clean quarkus:dev`
- (optional) reduce access token lifespan:
  - open keycloak admin interface: http://localhost:32777/admin/master/console/#/quarkus/realm-settings/tokens
  - username `admin`, password `admin`
  - set "Access Token Lifespan" to something like 1 or 2 minutes
- open the quarkus application in a browser: http://localhost:8080/hello
- you will get redirected to keycloak; log in using username `skroob`, password `12345`
- once redirected back to the application, open devtools, refresh the page and use "Copy as cURL" on the last request (that contains the cookies with the oidc tokens)
- copy the command into `curl.sh`
- wait until the access token has expired (default is 10 minutes unless changed in the optional step above)
  - (to check if it has expired, you can add `-v` to the curl command and see if the response contains new cookie headers)
- once expired, run `stress.sh`
- check the log of the quarkus app for `RequestNotActiveException`s

### Output of `uname -a` or `ver`

Linux rblei 6.8.0-110-generic #110-Ubuntu SMP PREEMPT_DYNAMIC Thu Mar 19 15:09:20 UTC 2026 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "25.0.2" 2026-01-20

### Quarkus version or git rev

3.34.5

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.12 (848fbb4bf2d427b72bdb2471c22fced7ebd9a7a1)

### Additional information

- All of our applications occasionally run into this bug
- We had multiple crashes in the last days, always preceded by these errors
- We suspect that the cause could be this commit: https://github.com/quarkusio/quarkus/commit/87510352f0deab7af5c47ebe37dbbae823080a45

### PR DESCRIPTION
**Pull request by michalvavrik**
* Closes: https://github.com/quarkusio/quarkus/issues/53748

### CODE REVIEW

**Comment by michalvavrik** [comment]
I'd like to check with one of: @jponge || @cescoffier || @Ladicek - this basically makes sure that when multiple HTTP requests are waiting for a token refresh, we provide response on their duplicated context. I verified it fixes the issue. I'd like from one of you check if `emitOn` is the right thing to do here and that the response will be dispatched on the right duplicated context, hence there won't be no leaking of contexts between requests. Thanks

**Comment by jponge** [comment]
I'm no specialist to this code, but the `emitOn` you have seems to do what you want (dispatching an action but by first hoping to the context you have). Whatever is before `emitOn` will be running from some thread(s), but `emitOn` will run the next callback on the context.

**Comment by michalvavrik** [comment]
Thanks for feedback @jponge . I think Sergey will ask around to double-check.

File: integration-tests/oidc-wiremock/src/main/java/io/quarkus/it/keycloak/CodeFlowConcurrentRefreshResource.java [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+    @GET
+    public Uni<String> access() {
+        return Uni.createFrom().item(() -> {
+            try {
+                Thread.sleep(10);
+            } catch (InterruptedException e) {
+                throw new RuntimeException(e);
+            }
+            return "hello";
+        }).emitOn(Infrastructure.getDefaultExecutor());
```
Comment (Ladicek) [inline integration-tests/oidc-wiremock/src/main/java/io/quarkus/it/keycloak/CodeFlowConcurrentRefreshResource.java]: I don't quite understand what this is supposed to do.

The subscription will occur on a Vert.x thread, because this method is not `@Blocking` and returns a `Uni`. The emitter will be invoked on that same thread, it will sleep 10 millis (???) and then emit `"hello"`. That value will then be moved to a worker thread (due to `emitOn()`) and that worker thread will complete the subscription.

It almost feels like the method really should just be annotated `@Blocking` and not play with advanced APIs.

Comment (Ladicek) [reply integration-tests/oidc-wiremock/src/main/java/io/quarkus/it/keycloak/CodeFlowConcurrentRefreshResource.java]: Or, even better, it should just return `String`, then you don't need the `@Blocking` annotation (because you have a blocking return type) and you can sleep without worrying that you'll block an event loop.

Comment (michalvavrik) [reply integration-tests/oidc-wiremock/src/main/java/io/quarkus/it/keycloak/CodeFlowConcurrentRefreshResource.java]: I took this part from a reproducer. Here is how I understand its purpose (I can easily be wrong):

Personally, I think that the purpose of this is to demonstrate that when 2 HTTP requests overlap and they are both waiting for a token refresh, the latter HTTP request receives a wrong duplicated context. So the sleeping increase chances for concurrent requests.

Anyway, if you want me to find a different way to reproduce it, I can experiment. Without knowing what users are actually doing (outside of "simple reproducer") I thought it was safer to fix what they report. Your call, I don't want to introduce something that shouldn't be done.

Comment (mbleichner) [reply integration-tests/oidc-wiremock/src/main/java/io/quarkus/it/keycloak/CodeFlowConcurrentRefreshResource.java]: The key thing seems to be that some kind of rescheduling happens to reproduce the issue - it does not matter which thread pool is used. In our production code, we have to use a custom unbounded pool (`Executors.newCachedThreadPool()`)

Comment (Ladicek) [reply integration-tests/oidc-wiremock/src/main/java/io/quarkus/it/keycloak/CodeFlowConcurrentRefreshResource.java]: > Personally, I think that the purpose of this is to demonstrate that when 2 HTTP requests overlap and they are both waiting for a token refresh, the latter HTTP request receives a wrong duplicated context. So the sleeping increase chances for concurrent requests.

If you're blocking the event loop, the requests may only overlap if multiple event loops exist. So you can also argue that by blocking the event loop, you _decrease_ the chance for concurrent request handling.

You can do a "non-blocking sleep" by:

```java
@Inject
Vertx vertx;

@GET
public Uni<String> access() {
    return Uni.createFrom().emitter(em -> {
        vertx.setTimer(1000, ignored -> {
            em.complete("hello");
        });
    });
}
```

But that may lead to both requests being handled by the same event loop thread (ableit concurrently, in an interleaved manner). I don't know how significant that is for your test.

> Anyway, if you want me to find a different way to reproduce it, I can experiment. Without knowing what users are actually doing (outside of "simple reproducer") I thought it was safer to fix what they report. Your call, I don't want to introduce something that shouldn't be done.

Are you saying that the user application blocks an event loop? If so, they have a problem they need to know about :-)

Comment (michalvavrik) [reply integration-tests/oidc-wiremock/src/main/java/io/quarkus/it/keycloak/CodeFlowConcurrentRefreshResource.java]: @Ladicek I appreciate all this feedback, but it really beats a point for me. I know how to block and how to sleep etc. I am merely trying to create a reproducer that is close to what user reported. I can see that you don't like the sleeping part, so I'll start looking for a different way to reproduce it. I'll ping you in this comment thread when I finished. Thanks

Comment (michalvavrik) [reply integration-tests/oidc-wiremock/src/main/java/io/quarkus/it/keycloak/CodeFlowConcurrentRefreshResource.java]: @mbleichner @Ladicek I have dropped the sleeping and still could reproduce the issue. So I pushed it.

> So you can also argue that by blocking the event loop, you decrease the chance for concurrent request handling.

I didn't know, though I'd expect we have more than one event loop even on GH CI executors (wasn't it related to number of available cores?). I don't have enough knowledge or time, so I'll simply trust you.

So @Ladicek, is using `emitOn` to reproduce the issue fine, considering that I can see it in the docs as well https://quarkus.io/guides/context-propagation#usage-example-with-mutiny ? If not, I can look for other ways to reproduce it.

Comment (Ladicek) [reply integration-tests/oidc-wiremock/src/main/java/io/quarkus/it/keycloak/CodeFlowConcurrentRefreshResource.java]: > @mbleichner @Ladicek I have dropped the sleeping and still could reproduce the issue. So I pushed it.

:+1:

> > So you can also argue that by blocking the event loop, you decrease the chance for concurrent request handling.
> 
> I didn't know, though I'd expect we have more than one event loop even on GH CI executors (wasn't it related to number of available cores?). I don't have enough knowledge or time, so I'll simply trust you.

Yeah, we probably do.

> So @Ladicek, is using `emitOn` to reproduce the issue fine, considering that I can see it in the docs as well https://quarkus.io/guides/context-propagation#usage-example-with-mutiny ? If not, I can look for other ways to reproduce it.

The documentation you refer to uses `emitOn()` for a reason -- they use blocking Hibernate ORM, so they have to execute on a worker thread. The example also demonstrates that the transaction propagates from the event loop to the worker thread. None of that matters in this example.

However, @mbleichner says a thread offload is required, and what you do is just that, so I'm fine here. (I guess I would also be fine if you added a comment saying something like "blocks the event loop, this is wrong in regular code, but does no harm in the test". But as you said, the issue reproduces even without the sleep, which is even better.)

Comment (michalvavrik) [reply integration-tests/oidc-wiremock/src/main/java/io/quarkus/it/keycloak/CodeFlowConcurrentRefreshResource.java]: Thanks.

Just a disclosure: when I say I reproduce it - that is true for my workstation - I can imagine that maybe to reproduce it reliably on every executor (slower ones?) it may be necessary to increase concurrency, but since I can reproduce it every single time, I will let it as is. Reviewers can check it reproduces the issue for them :-)

**Review by sberyozkin — APPROVED** [review]
Thanks very much Michal @michalvavrik for a super fast fix, and Ladislav @Ladicek for helpful and expert clarifications
