### PR TITLE
Handle gradle included-builds in quarkusDev task

### LINKED ISSUE #11902: gradle quarkusDev run fails with --include-build
**Describe the bug**
Gradle allows to compose builds - https://docs.gradle.org/current/userguide/composite_builds.html
But if you use it with some library `gradle --include-build ../lib quarkusDev` fails to find classes or injected Services from that library

**Expected behavior**
`gradle --include-build ../lib quarkusDev` should execute the same way as without `--include-build ../lib` parameter

**Actual behavior**
`gradle --include-build ../lib quarkusDev` fails with UnsatisfiedResolutionException or ClassNotFoundException

**To Reproduce**
1. checkout simple project `https://github.com/Shohou/composite_build_bug` with `lib` and `app`
2. do `gradle publish` in `lib` to put artifact in local maven
3. do `gradle quarkusDev` in `app` and see it successfully starts
4. do `gradle --include-build ../lib quarkusDev` and see how it builds lib, but then fails to find injected service. If you will change it from Injected bean to simple object created right there it will fail with ClassNotFoundException

**Environment (please complete the following information):**
 - Quarkus version or git rev: 1.7.1.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
Gradle 6.6

Build time:   2020-08-10 22:06:19 UTC
Revision:     d119144684a0c301aea027b79857815659e431b9

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          11.0.7 (AdoptOpenJDK 11.0.7+10)
OS:           Windows 10 10.0 amd64

### PR DESCRIPTION
**Pull request by glefloch**
Right now, included build were ignored while creating the quarkus model. 

This branch add support for included build by: 

- Looking for included build
- Building the quarkus model of those projects
- Adding the model and its dependencies to the current model. 

When looking for included builds, the gradle API only gives us the project name and the project directory. That's why I use the Quarkus model to collect included build infos. 

close #11902

### CODE REVIEW

**Comment by aloubyansky** [comment]
That's a tricky one. I am not sure this is the proper way, tbh. AFAIU, included builds should be replacing the matching app dependencies. It's not the same as resolving sets of dependencies separately and then merging them in. E.g. if the included build had a different dependency graph then the dependency it was replacing, I don't think you would get the proper classpath, you would get a mix of both.
Have you tried looking into `Configuration.getResolutionStrategy().dependencySubstitution(...)`?

**Comment by glefloch** [comment]
@aloubyansky, I wasn't aware of `Configuration.getResolutionStrategy().dependencySubstitution(...)` I'm gonna look in this way.

**Comment by gsmet** [comment]
This PR needs a rebase and probably another look then :).

**Comment by glefloch** [comment]
@aloubyansky I was able to work on this. Actually, resolved dependency are already substituted. 
A substituted project can be detected like a local module (using `instanceof ProjectComponentIdentifier`, the only difference of that the included module cannot be retrieved using the `project`. I used the `GradleConnector`

File: devtools/gradle/src/main/java/io/quarkus/gradle/builder/QuarkusModelBuilder.java [hunk 1]
```diff
@@ -331,9 +337,14 @@ private void collectDependencies(ResolvedConfiguration configuration,
             final DependencyImpl dep = initDependency(a);
             if (LaunchMode.DEVELOPMENT.equals(mode) &&
                     a.getId().getComponentIdentifier() instanceof ProjectComponentIdentifier) {
-                Project projectDep = project.getRootProject()
-                        .findProject(((ProjectComponentIdentifier) a.getId().getComponentIdentifier()).getProjectPath());
-                addDevModePaths(dep, a, projectDep);
+                Optional<IncludedBuild> includedBuild = includedBuild(project, a.getName());
```
Comment (aloubyansky) [inline devtools/gradle/src/main/java/io/quarkus/gradle/builder/QuarkusModelBuilder.java:340]: Couldn't this be replaced with `project.getGradle().includedBuild(name)`?

File: devtools/gradle/src/main/java/io/quarkus/gradle/builder/QuarkusModelBuilder.java [hunk 2]
```diff
@@ -402,6 +413,25 @@ private void addDevModePaths(final DependencyImpl dep, ResolvedArtifact a, Proje
         }
     }
 
+    private void addSubstitutedProject(final DependencyImpl dep, File projectFile, LaunchMode mode) {
```
Comment (aloubyansky) [inline devtools/gradle/src/main/java/io/quarkus/gradle/builder/QuarkusModelBuilder.java:416]: Just curious, have you tried to measure how long this method takes to execute? Is it seconds?

File: devtools/gradle/src/main/java/io/quarkus/gradle/builder/QuarkusModelBuilder.java (hunk 1 above)
Comment (glefloch) [reply devtools/gradle/src/main/java/io/quarkus/gradle/builder/QuarkusModelBuilder.java:341]: yes, I just wrapped that in a `try/catch` because `project.getGradle().includedBuild(name)` throws an exception if the project is not an included build.

File: devtools/gradle/src/main/java/io/quarkus/gradle/builder/QuarkusModelBuilder.java (hunk 2 above)
Comment (glefloch) [reply devtools/gradle/src/main/java/io/quarkus/gradle/builder/QuarkusModelBuilder.java:417]: I just ran some really basics benchmarks, it take 2 to 4 seconds..

Comment (aloubyansky) [reply devtools/gradle/src/main/java/io/quarkus/gradle/builder/QuarkusModelBuilder.java:417]: Sorry, do you mind not using Optional in this case? Making includeBuild return boolean will make it look simpler and perform better.

Comment (glefloch) [reply devtools/gradle/src/main/java/io/quarkus/gradle/builder/QuarkusModelBuilder.java:417]: Oh yes for sure. I'm trying to understand why the test fails in ci and passes on my machine. I will remove the optional once everything is ok.

Comment (aloubyansky) [reply devtools/gradle/src/main/java/io/quarkus/gradle/builder/QuarkusModelBuilder.java:416]: > I just ran some really basics benchmarks, it takes 2 to 4 seconds..

Just to clarify, was it a restart/reload that was taking 2 to 4 seconds in dev mode?

Comment (glefloch) [reply devtools/gradle/src/main/java/io/quarkus/gradle/builder/QuarkusModelBuilder.java:416]: It's for the first quarkusDev start. Reload is not impacted, and thanks to daemons/caches, next restart are not really impacted.

Comment (aloubyansky) [reply devtools/gradle/src/main/java/io/quarkus/gradle/builder/QuarkusModelBuilder.java:416]: Right, that's good. Thanks!

**Review by aloubyansky — APPROVED** [review]
Thanks @glefloch !
