### PR TITLE
Fix NPE when `QUARKUS_INIT_AND_EXIT` is used

### LINKED ISSUE #41113: Initialization Tasks failing
### Describe the bug

We have been using Liquibase with Kubernetes where in our own helm charts we are configuring a job to run with "QUARKUS_INIT_AND_EXIT" to execute the schema migration.

This was working up to version 3.8.x, and now fails with newer versions due to a NullPointerException on startup - this stops the deployment progressing.

```
2024-06-11 11:57:55,590 ERROR [io.qua.run.shu.ShutdownRecorder] (Quarkus Main Thread) Graceful shutdown failed: java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because "io.quarkus.runtime.shutdown.ShutdownRecorder.shutdownListeners" is null
	at io.quarkus.runtime.shutdown.ShutdownRecorder.executePreShutdown(ShutdownRecorder.java:42)
	at io.quarkus.runtime.shutdown.ShutdownRecorder.runShutdown(ShutdownRecorder.java:33)
	at io.quarkus.runtime.Application.stop(Application.java:207)
	at io.quarkus.runtime.Application.stop(Application.java:155)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:211)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
```

Following an investigation, it appears that the graceful shutdown code was refactored after 3.8.x which removed the null check for shutdown listeners - however it appears any shutdown listeners are not actually injected until after the point when "init and exit" has finished, leading to the NPE.

### Expected behavior

The Quarkus container should run the Liquibase migration and then exit cleanly.

### Actual behavior

The Liquibase migration happens as expected but the contianer does not shutdown without the error - stopping the appplication containers from starting.

### How to Reproduce?

Running any Quarkus application with environment variable "QUARKUS_INIT_AND_EXIT" set to true.

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

3.11.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
- Fixes: #41113

### CODE REVIEW

File: core/runtime/src/main/java/io/quarkus/runtime/shutdown/ShutdownRecorder.java [hunk 1]
```diff
@@ -28,6 +28,9 @@ public void setListeners(List<ShutdownListener> listeners, boolean delayEnabled)
     }
 
     public static void runShutdown() {
+        if (shutdownListeners == null) { // when QUARKUS_INIT_AND_EXIT is used, ShutdownRecorder#setListeners has not been called
```
Comment (gsmet) [inline core/runtime/src/main/java/io/quarkus/runtime/shutdown/ShutdownRecorder.java:31]: Hmmm. In this case, we are sure that we don't want to run any of the shutdown listeners? None will have been registered and needed at this phase?

Comment (geoand) [reply core/runtime/src/main/java/io/quarkus/runtime/shutdown/ShutdownRecorder.java:31]: That's how it's always has been.

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
This one is actually not a problem in 3.8, the null test is still here.
