### PR TITLE
ArC - never share a generated observer method for multiple beans

### LINKED ISSUE #23888: Bean marked with @Singleton created two times
### Describe the bug

We have a project consisting a couple of maven projects. One of the beans is marked as @Singleton. 
It is using quite a few quarkus features: @ActivateRequestContext, observes Startup event, uses @PostConstruct.

It is injected into a few places, one bean is getting a direct reference, the other one is using Instance<> and iterates over the beans.

In case the project is built using a newer much more powerful machine, then runner.jar produced *sometimes* contains duplicated instances of the given bean.

### Expected behavior

@Singleton beans should never instantiated twice.

### Actual behavior

Writing out registration and other information shows that in that case two instances are created.

### How to Reproduce?

I've tried to create a reproducer within a simple project, but it did not showed the symptom. 

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.2.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

# Good machine
Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
**$ mvn --version**
Apache Maven 3.8.2 (ea98e05a04480131370aa0c110b8c54cf726c06f)
Maven home: /opt/maven
Java version: 11.0.13, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-100-generic", arch: "amd64", family: "unix"

**$ uname -a**
Linux oahu 5.4.0-100-generic #113-Ubuntu SMP Thu Feb 3 18:43:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**$ java --version**
openjdk 11.0.13 2021-10-19
OpenJDK Runtime Environment (build 11.0.13+8-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.13+8-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)

# Bad machine
Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz

**java -version**
openjdk version "11.0.13" 2021-10-19
OpenJDK Runtime Environment (build 11.0.13+8-suse-3.68.1-x8664)
OpenJDK 64-Bit Server VM (build 11.0.13+8-suse-3.68.1-x8664, mixed mode)

**$ uname -a**
Linux happyland 5.3.18-150300.59.49-preempt #1 SMP PREEMPT Mon Feb 7 14:40:20 UTC 2022 (77d9d02) x86_64 x86_64 x86_64 GNU/Linux

**mvn --version**
Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)
Maven home: /opt/apache-maven-3.8.4
Java version: 11.0.13, vendor: Oracle Corporation, runtime: /usr/lib64/jvm/java-11-openjdk-11
Default locale: hu_HU, platform encoding: UTF-8
OS name: "linux", version: "5.3.18-150300.59.49-preempt", arch: "amd64", family: "unix"

### PR DESCRIPTION
**Pull request by mkouba**
- resolves #23888
- also throw an IAE if a bean with an invalid scope is passed as an
argument to the Context.get() methods (built-in contexts only)

### CODE REVIEW

File: independent-projects/arc/tests/src/test/java/io/quarkus/arc/test/observers/inheritance/generated/GeneratedObserverClassNotSharedTest.java [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+
+    static final Set<Alpha> ALPHAS = new CopyOnWriteArraySet<>();
+
+    @Test
+    public void testIdentities() {
+        ALPHAS.clear();
+        Event<Alpha> event = Arc.container().beanManager().getEvent().select(Alpha.class);
+        // Fire two events and verify that only one instance of Alpha and Bravo was used
+        event.fire(new Alpha());
+        event.fire(new Alpha());
```
Comment (Ladicek) [inline independent-projects/arc/tests/src/test/java/io/quarkus/arc/test/observers/inheritance/generated/GeneratedObserverClassNotSharedTest.java:31]: Did you want to fire `Bravo` too?

Comment (Ladicek) [reply independent-projects/arc/tests/src/test/java/io/quarkus/arc/test/observers/inheritance/generated/GeneratedObserverClassNotSharedTest.java:31]: Ah, I probably misunderstood what you're doing here :-) The fact that you're firing 2 events and then asserting `ALPHAS` has 2 elements confused me, I guess. Those twos are two different twos :laughing:

**Review by Ladicek — APPROVED** [review]

File: independent-projects/arc/tests/src/test/java/io/quarkus/arc/test/observers/inheritance/generated/GeneratedObserverClassNotSharedTest.java (hunk 1 above)
Comment (smil2k) [reply independent-projects/arc/tests/src/test/java/io/quarkus/arc/test/observers/inheritance/generated/GeneratedObserverClassNotSharedTest.java:31]: Is there any reason why you are throwing Alphas? It makes the test a bit confusing.

Comment (mkouba) [reply independent-projects/arc/tests/src/test/java/io/quarkus/arc/test/observers/inheritance/generated/GeneratedObserverClassNotSharedTest.java:31]: The event payload is irrelevant. I used `Alpha` so that no other class is needed for the payload. I'll change that to make the test more understandable.

Comment (mkouba) [reply independent-projects/arc/tests/src/test/java/io/quarkus/arc/test/observers/inheritance/generated/GeneratedObserverClassNotSharedTest.java]: I hope it's better now ;-)

**Comment by mkouba** [comment]
It seems that this PR breaks some dev console tests... I'm on it.

**Comment by mkouba** [comment]
Uf, it's a classloading issue in the dev console where the scope classes are obviously loaded by multiple classloaders (!). I think that we'll have to test the FQCN for equality instead of a class...

**Comment by gsmet** [comment]
Cancelling workflow for now to relieve CI. This one is a bit too touchy to be merged in a hurry just before the release.

**Review by manovotn — APPROVED** [review]
Looks good!

**Comment by mkouba** [comment]
> Cancelling workflow for now to relieve CI. This one is a bit too touchy to be merged in a hurry just before the release.

@gsmet Ok. I don't think it's "touchy" but we don't hurry so feel free to restart the jobs when the CI is ready ;-).
