### PR TITLE
Correct how we process injection point transformers for SR CP

### LINKED ISSUE #38825: ManagedExecutorConfig does not seem to be working when using constructor injection
### Describe the bug

when using something like this it works as expected;

```java
public class App {

    private static final Logger LOGGER = Logger.getLogger("App");

    @Inject
    @ManagedExecutorConfig(maxAsync = 5)
    ManagedExecutor executor;

    void onStart(@Observes StartupEvent ev) {
        IntStream.range(0, 100).forEach(i -> executor.runAsync(() -> LOGGER.info(i)));
    }

}
```

but when changing to this
```java
public class App {

    private static final Logger LOGGER = Logger.getLogger("App");

    ManagedExecutor executor;

    App(@ManagedExecutorConfig(maxAsync = 5) ManagedExecutor executor) {
        this.executor = executor;
    }

    void onStart(@Observes StartupEvent ev) {
        IntStream.range(0, 100).forEach(i -> executor.runAsync(() -> LOGGER.info(i)));
    }

}
```

The config is not respected

### Expected behavior

Annotation could be disallowed on parameters or it should be otherwise working

### Actual behavior

Annotation is not respected. in the first snippet the thread numbers stays low in the logs in the second variant it goes up to about 75.

### How to Reproduce?

Reproducer: https://github.com/manofthepeace/executorconfig-ctorinject

1- mvn quarkus:dev
2- look at the thread number; `[App] (executor-thread-76)`

### Output of `uname -a` or `ver`

Darwin Kernel Version 21.6.0

### Output of `java -version`

Temurin-21.0.2+13

### Quarkus version or git rev

3.7.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven 3.9.5

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by manovotn**
This fixes how we process injection points for SR CP processor where we were incorrectly expecting `AnnotationTarget` for method param while we should be operating on just method.
There was also a bug in Arc that, for a method injection point, returned a set of qualifiers belonging to the whole method instead of just given parameter.

~~I have yet to take a closer look at other usages in Quarkus which may have similar issues - one of which is the grpc processor I mentioned in the original issue.~~

- Fixes #38825

### CODE REVIEW

**Comment by manovotn** [comment]
I have added a comment that also alters gRPC processor which is incorrectly expecting method param as annotation target.
I quickly scanned other IP transformers as well but those look OK.

File: extensions/grpc/deployment/src/main/java/io/quarkus/grpc/deployment/GrpcClientProcessor.java [hunk 1]
```diff
@@ -345,16 +346,21 @@ public void transform(TransformationContext ctx) {
...
                         MethodParameterInfo param = clientAnnotation.target().asMethodParameter();
+                        annotationTarget = param;
                         // We don't need to check if parameter names are recorded - that's validated elsewhere
                         clientName = param.method().parameterName(param.position());
                     }
                     if (clientName != null) {
                         ctx.transform().remove(GrpcDotNames::isGrpcClient)
-                                .add(GrpcDotNames.GRPC_CLIENT, AnnotationValue.createStringValue("value", clientName)).done();
+                                .add(AnnotationInstance.create(GrpcDotNames.GRPC_CLIENT, annotationTarget,
+                                        new AnnotationValue[] { AnnotationValue.createStringValue("value", clientName) }))
```
Comment (Ladicek) [inline extensions/grpc/deployment/src/main/java/io/quarkus/grpc/deployment/GrpcClientProcessor.java:362]: For your consideration, the `AnnotationInstanceBuilder` is a much nicer API.

```java
AnnotationInstance.builder(GrpcDotNames.GRPC_CLIENT)
    .value(clientName)
    .buildWithTarget(annotationTarget)
```

Comment (manovotn) [reply extensions/grpc/deployment/src/main/java/io/quarkus/grpc/deployment/GrpcClientProcessor.java:362]: Ah, I didn't realize there's a builder. Thanks!

**Review by Ladicek — APPROVED** [review]
I can't exactly say I understand the ConProp extension, but the rest LGTM.

**Comment by gsmet** [comment]
@mkouba I let you review that one. Also we need to decide if it's a good idea to backport it or not. I'm on the verge tbh.

**Comment by manovotn** [comment]
> @mkouba I let you review that one. Also we need to decide if it's a good idea to backport it or not. I'm on the verge tbh.

Well, it is a rare use case - without this fix it has never worked (if injected as method param) since it's addition and nobody encountered it so far so I don't think it's anyhow crucial.

**Review by mkouba — APPROVED** [review]

**Comment by manovotn** [comment]
This should be good to merge but just to be safe and get proper CI result, I've rebased the PR onto main.

**Comment by manovotn** [comment]
The `Quarkus CI / Native Tests - Data5 (pull_request) ` doesn't seem related and I am seeing the same failure on other PRs as well.
