### PR TITLE
Spring DI exposing Custom scopes as build item

### LINKED ISSUE #47544: Conflict when using quarkus-kafka-messaging and quarkus-spring-di
When I am using quarkus-kafka-messaging and quarkus-spring-di dependencies I am getting the following error:

```shell
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.arc.deployment.ArcProcessor#registerBeans threw an exception: jakarta.enterprise.inject.spi.DefinitionException: Bean class dev.matheuscruz.quarkusclub.product.ProductConsumer declares multiple scope type annotations: jakarta.enterprise.context.Dependent, jakarta.inject.Singleton
```

It happens with the following code:

```java
package dev.matheuscruz.quarkusclub.product;

import org.eclipse.microprofile.reactive.messaging.Incoming;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

@Service
// we have conflict between @Dependent generated by **quarkus-kafka-messaging** and @Singleton generated by **quarkus-spring-di**
public class ProductConsumer {

    private static final Logger LOGGER = LoggerFactory.getLogger(ProductConsumer.class);

    @Incoming("product.created.v1")
    public void consume(String message) {
        LOGGER.info("📥 Received message from Kafka about new product: {}", message);
    }
}
```

I think we have conflict between `@Dependent` generated by **quarkus-kafka-messaging** and `@Singleton` generated by **quarkus-spring-di**.

### PR DESCRIPTION
**Pull request by ozangunalp**
Resolves #47544

I am not sure of the impact of this change. So letting the CI run and have feedback from @mkouba, @geoand and @aureamunoz

### CODE REVIEW

**Review by geoand — APPROVED** [review]

File: extensions/spring-di/deployment/src/main/java/io/quarkus/spring/di/deployment/SpringDIProcessor.java [hunk 1]
```diff
@@ -135,6 +138,9 @@ AnnotationsTransformerBuildItem beanTransformer(
                     .map(AnnotationInstance::name)
                     .collect(Collectors.toSet()));
         }
+        for (DotName scope : stereotypeScopes.keySet()) {
+            customScopeBuildProducer.produce(new CustomScopeBuildItem(scope));
```
Comment (mkouba) [inline extensions/spring-di/deployment/src/main/java/io/quarkus/spring/di/deployment/SpringDIProcessor.java:142]: `CustomScopeBuildItem` should only be produced for custom scopes; which isn't the case here, or?

Why exactly do we need this?

Comment (ozangunalp) [reply extensions/spring-di/deployment/src/main/java/io/quarkus/spring/di/deployment/SpringDIProcessor.java:142]: AFAICT the Spring DI extension is adding CDI scope annotations to classes where these Spring annotations are present. 

So when it comes to other extensions adding default scope to classes containing some annotations (RM adding Dependent to classes containing Incoming/Outgoing, grpc adding Singleton to classes containing GrpcService, etc.) they can check whether custom scope is already present on the class.

**Review by aureamunoz — APPROVED** [review]

**Comment by ozangunalp** [comment]
I need to adapt the IT I modified so see if it works. Obviously container runtime is not available on windows tests.

File: extensions/spring-di/deployment/src/main/java/io/quarkus/spring/di/deployment/SpringDIProcessor.java (hunk 1 above)
Comment (mkouba) [reply extensions/spring-di/deployment/src/main/java/io/quarkus/spring/di/deployment/SpringDIProcessor.java:142]: I see. So the correct solution for multiple extensions trying to add an "auto" scope is to "prioritize", i.e. only one extension can win ;-).

In this particular case, I guess that Spring DI should win because of the `org.springframework.stereotype.Service` annotation used.

Therefore, I'd recommend to (1) rewrite the [`SmallRyeReactiveMessagingProcessor#transformBeanScope()`](https://github.com/quarkusio/quarkus/blob/main/extensions/smallrye-reactive-messaging/deployment/src/main/java/io/quarkus/smallrye/reactivemessaging/deployment/SmallRyeReactiveMessagingProcessor.java#L128-L160) to produce a transformation with lower priority (Spring DI is using the default priority of `1000`). An idiomatic approach for an annotation transformer that merely adds a scope is to use the [`AutoAddScopeBuildItem`](https://quarkus.io/guides/cdi-integration#reason-2-class-is-discovered-but-has-no-bean-defining-annotation); it handles most of the tricky parts automatically (such as declared scope annotations). 

Something like:
```java
@BuildStep
AutoAddScopeBuildItem autoAddScope() {
   return AutoAddScopeBuildItem.builder()
      .containsAnnotations(INCOMING, OUTGOING, CHANNEL) 
      .defaultScope(BuiltinScope.DEPENDENT)
      .build();
}
```
However, the `AutoAddScopeBuildItem` transformer has the priority `2000` so we need to (2) modify the priority of the Spring DI's transformer as well. Or use a custom annotation transformer with lower priority instead of  `AutoAddScopeBuildItem`.

File: extensions/smallrye-reactive-messaging/deployment/src/main/java/io/quarkus/smallrye/reactivemessaging/deployment/SmallRyeReactiveMessagingProcessor.java [hunk 2]
```diff
@@ -134,12 +135,17 @@ public boolean appliesTo(AnnotationTarget.Kind kind) {
                 return kind == org.jboss.jandex.AnnotationTarget.Kind.CLASS;
             }
 
+            @Override
+            public int priority() {
+                return 500;
```
Comment (mkouba) [inline extensions/smallrye-reactive-messaging/deployment/src/main/java/io/quarkus/smallrye/reactivemessaging/deployment/SmallRyeReactiveMessagingProcessor.java:140]: It might make sense to add a comment that the value is `500` because the Spring DI's annotation transformer has the default priority of value `1000` and we want it to take precedence?

Also I would squash the changes, i.e. remove the first commit completely...

**Review by mkouba — APPROVED** [review]
