### PR TITLE
Use OIDC Tenant annotation to resolve tenants

### LINKED ISSUE #34692: Selecting OIDC tenant via annotation is not working with RESTEasy Reactive
### Describe the bug

According to [OIDC docs](https://quarkus.io/guides/security-openid-connect-multitenancy#resolving-tenant-identifiers-with-annotations), one can select OIDC tenant via annotation as follows:

```
@Inherited
@InterceptorBinding
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.METHOD, ElementType.TYPE})
public @interface HrTenant {
}
```

```
@Interceptor
@HrTenant
public class HrTenantInterceptor {
    @Inject
    RoutingContext routingContext;

    @AroundInvoke
    Object setTenant(InvocationContext context) throws Exception {
        routingContext.put(OidcUtils.TENANT_ID_ATTRIBUTE, "hr");
        return context.proceed();
    }
}
```

```
@Path("/hr")
public class HrResource {

    @HrTenant
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String helloWorld() {
        return "Hello World";
    }
}
```

### Expected behavior

Authentication of `/hr` endpoint should be based on `quarkus.oidc.hr.*` configs.

### Actual behavior

Authentication of `/hr` endpoint uses the default tenant configs `quarkus.oidc.*` as authentication is triggered before `HrTenantInterceptor`, hence the authentication fails.

### Quarkus version or git rev

3.2.0.Final

### PR DESCRIPTION
**Pull request by michalvavrik**
fixes: #34692

Now all that users need to do when they want to link certain resource method with tenant (both in RESTEasy Reactive and RESTEasy Classic) is to annotate the method with `@Tenant("my-tenant")`. I did that by completely avoiding CDI interceptors, which is necessary for RR scenario. ~~Also adding `oidc-wiremock-reactive` module as reported issue proved value of that. However I didn't add it to native runs, so additional time required in CI is about 30 seconds per JVM.~~ Using Jakarta REST filter in RESTEasy Classic enabled usage of `@Tenant` annotation for this purpose (as we avoid CDI interceptors over token customizers).

### CODE REVIEW

**Comment by michalvavrik** [comment]
Tests failing in CI didn't fail locally when I run them, I'll have a look.

**Comment by michalvavrik** [comment]
Alright, Sergey had PRs and made changes in OIDC wiremock module since I started developing. I'll do same changes in OIDC Wiremock reactive.

**Comment by sberyozkin** [comment]
Hi @michalvavrik Thanks, do we really need to have `oidc-wiremock-reactive` ? May be you can update the dependency in `oidc-wiremock` and update the tenant annotation test only ? CDI interceptor test for Resteasy Classic will keep running in 3.2.x branches - but starting from 3.3.0 we'd just recommend using @Tenant("someid") for either stack ?

**Comment by michalvavrik** [comment]
> Hi @michalvavrik Thanks, do we really need to have `oidc-wiremock-reactive` ? 

Issue #34692 would not happen if we tested it with RESTEasy Reactive. Considering RR is our preferred REST stack, it needs to be tested. Also it is additional 30 seconds (on my workstation) per JVM, so no big deal.

> May be you can update the dependency in `oidc-wiremock` and update the tenant annotation test only ? 

You mean like change RESTEasy Classic to RESTEasy Reactive in `oidc-wiremock`? I'm all in :-), just kindly @sberyozkin  confirm I got you right, please.

> CDI interceptor test for Resteasy Classic will keep running in 3.2.x branches - but starting from 3.3.0 we'd just recommend using `@Tenant("someid")` for either stack ?

Yeah, I agree with that, but principles how it works under the hood are different. If I change deps RR -> RC, than we don't test whether RC work (more specifically it is just about Jakarta REST filter in RESTEasy Classic, so chance it does not is pretty small!).

@sberyozkin I think I understand and agree, just please confirm, thank you.

**Comment by sberyozkin** [comment]
@michalvavrik Updating `oidc-wiremock` dependency will save on introducing another module, so lets update it. `oidc-code-flow`, `oidc-tenancy`  use RestEasy classic

File: extensions/oidc/deployment/src/main/java/io/quarkus/oidc/deployment/OidcBuildStep.java [hunk 1]
```diff
@@ -136,6 +158,88 @@ public void findSecurityEventObservers(
...
+                if (target.kind() == METHOD) {
+                    MethodInfo method = target.asMethod();
+                    if (hasProperEndpointModifiers(method)) {
+                        candidateToTenant.put(method, tenant);
+                    } else {
+                        LOG.warnf("Method %s is not valid endpoint, but is annotated with the '@Tenant' annotation",
+                                toTargetName(target));
+                    }
+                } else if (target.kind() == CLASS) {
+                    if (target.asClass().interfaceNames().contains(TOKEN_CUSTOMIZER_NAME)) {
```
[the remark this answers is not in the document]
Comment (michalvavrik) [reply extensions/oidc/deployment/src/main/java/io/quarkus/oidc/deployment/OidcBuildStep.java:195]: @sberyozkin it don't need to be done!

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/Tenant.java [hunk 2]
```diff
@@ -9,7 +10,7 @@
 /**
  * Qualifier which can be used to associate one or more OIDC features with a named tenant.
  */
-@Target({ TYPE })
+@Target({ TYPE, METHOD })
```
Comment (sberyozkin) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/Tenant.java:13]: It already introduces a problem if someone adds it to `TokenHeaderCustomizer` implementation method instead of class.
I should've named this annotation `TenantFeature` which aligns better with the current docs: `... associate one or more OIDC features with a named tenant.`.

Hmm... `TokenHeaderCustomizer` is a new feature in 3.2 but for the only case where it was required so far, Azure token customizations, we ship `AzureTokenCustomizer` which can be referred to from tenant configurations with the `tenant-customizer-name` property and it is very unlikely that users have used `@Tenant` to apply some other custom token customizers.

My proposal would be to have `@TenantFeature` annotation used for what current `@Tenant` (and update token customizer related JavaDocs and tests to refer to `@TenantFeature`) and mark it as a breaking change, though I'd be nearly certain it won't break any user's code. I'll add a migration note. 

And your PR then keeps working with `@Tenant` but updates its docs to say it can be used to `associate tenant configurations with JAX-RS classes and methods`, and we will evolve both annotations as required.

Or we can add a new annotation like `@TenantId` right now to support this PR, but I feel `@TenantFeature` would be a better name for what `@Tenant` was originally meant to - associate whatever feature it marks with some tenant.

Does it sound reasonable ? What do you think ?

**Comment by sberyozkin** [comment]
@michalvavrik PR is perfect, thanks, lets discuss more though how to deal with this annotation ambiguity

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/Tenant.java (hunk 2 above)
Comment (michalvavrik) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/Tenant.java:13]: > It already introduces a problem if someone adds it to TokenHeaderCustomizer implementation method instead of class.

We disagree on that point, but IMHO it is important that you must be fine with all changes here, so let's avoid using one annotation for token customizer and Jakarta REST resources :-)

It seems to have both `@Tenant` and `@TenantId` would be confusing (though it can be documented), `@TenantFeature` seems much better to me. I can wait with this PR till you do changes (I take it from context you want to do it, right? I can do it if you are busy).

File: extensions/oidc/deployment/src/main/java/io/quarkus/oidc/deployment/OidcBuildStep.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (michalvavrik) [reply extensions/oidc/deployment/src/main/java/io/quarkus/oidc/deployment/OidcBuildStep.java:195]: for transparency: it would be problem if token customizer were also Jakarta REST resource, which I hope is unlikely (and bad practice)

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/Tenant.java (hunk 2 above)
Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/Tenant.java:13]: @michalvavrik Hey, let me keep this one open for Georgios and others to have a look at what we've discussed, when reviewing #34862

**Comment by sberyozkin** [comment]
@michalvavrik Would you like to rename this PR to something like `Use OIDC Tenant annotation to resolve tenants` ? It can be marked then as a release noteworthy feature, otherwise we are fixing a bug only - which is also true :-), but the concept of using `@Tenant` is totally new and is worth getting the users attention to.

**Comment by michalvavrik** [comment]
@sberyozkin sure thing

**Comment by sberyozkin** [comment]
Thanks, added a noteworthy feature label

**Comment by michalvavrik** [comment]
JDK 17 on Windows is IMHO flaky because I saw that before

**Comment by michalvavrik** [comment]
JDK 11 got cancelled, but in logs I can't see anything related as well (huge logs though..); IMHO it just reached 6 hours Github timeout. cc @gsmet @geoand

**Comment by geoand** [comment]
Very likely

**Review by sberyozkin — APPROVED** [review]
Thanks @michalvavrik

**Comment by sberyozkin** [comment]
@michalvavrik Hi Michal, can you please give it one more try and rerun ? This PR updates the vertx-http deployment sequence, I don't see how it can affect the timeout though, but please run one more time

**Comment by sberyozkin** [comment]
JDK 17 Windows test failed again but it is grpc and reactive messaging, definitely not related
