### PR TITLE
Keep type info for polymorphic collections in generated Jackson serializers and correctly wires its serialization with the Jackson's mechanism

### LINKED ISSUE #53765: [Reflection-free Jackson serdes] `@JsonTypeInfo` discriminator missing + `@JsonUnwrapped` broken when inner type has generated serialiser
### Describe the bug

Following on from https://github.com/quarkusio/quarkus/issues/53588 (now fixed, thanks @mariofusco!), the reflection-free Jackson **serialisers** have two more gaps. Both work correctly with `enable-reflection-free-serializers=false` (see https://github.com/lloydmeta/quarkus-jackson-reflection-free-bug/pull/3)

Reminder: `enable-reflection-free-serializers` is the default from 3.35 (#53161).

1. `@JsonTypeInfo` discriminator not written by generated serialiser
    
    When a sealed interface is annotated with `@JsonTypeInfo`, the generated serialiser for the concrete record subtypes doesn't write the type discriminator property. The response is missing the discriminator entirely, so clients expecting standard Jackson polymorphic format can't deserialise it.
    
    ```java
    @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type")
    @JsonSubTypes({
        @JsonSubTypes.Type(value = Item.TypeA.class, name = "type_a"),
    })
    public sealed interface Item permits Item.TypeA {
        record TypeA(String value) implements Item {}
    }
    ```
    
    In other words, serialising an `Item.TypeA("hello")` produces `{"value": "hello"}`, without the `"type": "type_a"` discriminator.

2. `@JsonUnwrapped` broken when inner type has a generated serialiser

    The current code correctly detects `@JsonUnwrapped` on the containing type and skips serialiser generation for it (falling back to reflection). But if the _inner_ (unwrapped) type also has a generated `$quarkusjacksonserializer` (e.g. because some other endpoint returns that type directly), `@JsonUnwrapped` breaks and the fields are _nested_ instead of flattened.
    
    ```java
    record Detail(String id, String value) {}
    record Outer(@JsonUnwrapped Detail detail) {}
    ```
    
    e.g. when `Detail` has a generated serialiser (because some other endpoint returns `Detail` directly), serialising `Outer` produces:
    
    ```json
    {"detail": {"id": "abc", "value": "hello"}}
    ```
    
    instead of:
    
    ```json
    {"id": "abc", "value": "hello"}
    ```
    
    When `Detail` does **not** have a generated serialiser, `@JsonUnwrapped` works correctly AFAICT. This makes the bug depend on what other endpoints exist in the application, which is confusing to debug..

### Combined: both bugs compound

When a `@JsonTypeInfo` sealed interface has variants using `@JsonUnwrapped`, and the inner types have generated serialisers, both bugs stack such that the output is something that looks completely off:

* Expected: `{"status": "success", "id": "abc", "value": "hello"}`
* Actual: `{"detail": {"id": "abc", "value": "hello"}}` - discriminator missing AND fields nested

### Expected behavior

1. The `@JsonTypeInfo` discriminator property should be written when serialising concrete subtypes
2. `@JsonUnwrapped` should flatten fields regardless of whether the inner type has a generated serialiser

### Actual behavior

1. The type discriminator is absent from serialised output
2. `@JsonUnwrapped` fields are nested when the inner type has a generated serialiser

### How to Reproduce?

Reproducer: https://github.com/lloydmeta/quarkus-jackson-reflection-free-bug 

^has been updated with the needed test cases.  Results and test output [here](https://github.com/lloydmeta/quarkus-jackson-reflection-free-bug/actions/runs/24818838095).

```bash
git clone https://github.com/lloydmeta/quarkus-jackson-reflection-free-bug.git
cd quarkus-jackson-reflection-free-bug
./gradlew clean test
```

### Output of `uname -a` or `ver`

Darwin Mac-M2Pro 25.4.0 Darwin Kernel Version 25.4.0: Thu Mar 19 19:31:17 PDT 2026; root:xnu-12377.101.15~1/RELEASE_ARM64_T6020 arm64

### Output of `java -version`

openjdk 25.0.1 2025-10-21

### Quarkus version or git rev

3.34.6

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 9.4.1

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mariofusco**
This fixes the problem reported here http://github.com/quarkusio/quarkus/issues/53765 not implementing support for those `@JsonTypeInfo` and `@JsonUnwrapped` annotations for now, but making sure that in presence of them the serialization can correctly fallback to the standard Jackson's reflection-based mechanism as suggested by @gsmet 

Note that what I wrote in this comment https://github.com/quarkusio/quarkus/issues/53765#issuecomment-4325099687 is only part of the truth and the situation is quite more complex.

What I would have expected is that when a class for which the serializer can be generated correctly references another class with an unknown json annotation the default Jackson's serialization mechanism should automatically kicks in only when serializing the pojo with the unknown annotation, not having a registered generated serializer for that.

However the problem is that in the provided reproducer the `ErrorInfo` and `Detail` classes do get a reflection-free serializer generated for them, because they only contain `@JsonProperty` which is a supported annotation, but that is what breaks the `@JsonUnwrapped`. In fact, when Jackson's default `BeanSerializer` processes `UnwrappedResult.Failed` and encounters `ErrorInfo` annotated with `@JsonUnwrapped ` it doesn't serialize that pojo as a regular nested field. Instead, it calls `serializer.unwrappingSerializer(nameTransformer)` on the `serializer` for ErrorInfo to obtain an `UnwrappingBeanSerializer` — a special variant that writes the inner object's fields directly into the parent's JSON object without `writeStartObject()`/`writeEndObject()` and without emitting the field name "error". This is how the fields get "flattened". This breaks the reflection-free serializer generated for `ErrorInfo`, because when Jackson calls `unwrappingSerializer()` on it, the implementation inherited by the `StdSerializer` simply returns `this`, the same serializer, unchanged. In this way the generated serializer's `serialize()` method calls `writeStartObject()` at the beginning and `writeEndObject()` at the end, which means ErrorInfo is always written as a nested JSON object, not obeying the requirement of the `@JsonUnwrapped` annotation.

In summary, the assumption that the generated serializer can delegate to the default Jackson mechanism only for classes with unknown annotations breaks, because the delegation goes the wrong direction. It's not the generated serializer needing to delegate, but it's Jackson's default reflection-based serializer for the parent.

The fix aligns the generated code with how Jackson's own defaultSerializeField works, switching the `JacksonMapperUtil.serializePojo` to use the method `findTypedValueSerializer`, instead of `findValueSerializer`, that works in the same way for non-poymorphic types, while for polymorphic types it wraps with a TypeWrappedSerializer that writes the discriminator. This means that the most relevant change of this fix it is confined in the `JacksonMapperUtil.serializePojo` static method, so that the generated code isn't changed in any relavant way and I hadn't to change the sample generated serializer in the javadocs. 

I also improved the discovery mechanism of classes for which a (de)serializer should be generated also walking the known implementation of the sealed interfaces.

- Fixes: #53765

### CODE REVIEW

File: extensions/resteasy-reactive/rest-jackson/deployment/src/test/java/io/quarkus/resteasy/reactive/jackson/deployment/test/SimpleJsonWithReflectionFreeSerializersTest.java [hunk 1]
```diff
@@ -34,17 +31,19 @@ public JavaArchive get() {
...
-            })
-            .setLogRecordPredicate(record -> record.getLevel().equals(Level.INFO)
-                    && record.getLoggerName().equals(
-                            "io.quarkus.resteasy.reactive.jackson.deployment.processor.JacksonCodeGenerator"))
-            .assertLogRecords(records -> assertThat(records).isEmpty());
+            });
+    //            .setLogRecordPredicate(record -> record.getLevel().equals(Level.INFO)
+    //                    && record.getLoggerName().equals(
+    //                            "io.quarkus.resteasy.reactive.jackson.deployment.processor.JacksonCodeGenerator"))
+    //            .assertLogRecords(records -> assertThat(records).isEmpty());
```
Comment (mariofusco) [inline extensions/resteasy-reactive/rest-jackson/deployment/src/test/java/io/quarkus/resteasy/reactive/jackson/deployment/test/SimpleJsonWithReflectionFreeSerializersTest.java:54]: I had to comment out this assertion, because now it is discovering classes with unknown Jackson annotations, for which it cannot generate a serializer, and then the log generated by `JacksonCodeGenerator` is no longer empty. I'm planning to add implementation also for those outstanding annotations, but I'd prefer to merge this pull request in, in order to check that the fallback mechanism is working correctly also in this case.

File: extensions/resteasy-reactive/rest-jackson/runtime/src/main/java/io/quarkus/resteasy/reactive/jackson/runtime/mappers/JacksonMapperUtil.java [hunk 2]
```diff
@@ -173,14 +173,27 @@ public static void serializePojo(Object value, JsonGenerator generator, Serializ
             generator.writePOJO(value);
             return;
         }
-        JsonSerializer<Object> serializer = serializerProvider.findValueSerializer(value.getClass());
+        JsonSerializer<Object> serializer = serializerProvider.findTypedValueSerializer(value.getClass(), true, null);
```
Comment (mariofusco) [inline extensions/resteasy-reactive/rest-jackson/runtime/src/main/java/io/quarkus/resteasy/reactive/jackson/runtime/mappers/JacksonMapperUtil.java:176]: This is actually the main fix.

File: extensions/resteasy-reactive/rest-jackson/runtime/src/main/java/io/quarkus/resteasy/reactive/jackson/runtime/mappers/JacksonMapperUtil.java [hunk 3]
```diff
@@ -173,14 +173,27 @@ public static void serializePojo(Object value, JsonGenerator generator, Serializ
...
         if (serializer != null) {
             serializer.serialize(value, generator, serializerProvider);
         } else {
             generator.writePOJO(value);
         }
     }
 
+    @SuppressWarnings("unchecked")
+    public static void serializeCollection(Object value, Class<?> collectionClass, Class<?> elementClass,
```
Comment (mariofusco) [inline extensions/resteasy-reactive/rest-jackson/runtime/src/main/java/io/quarkus/resteasy/reactive/jackson/runtime/mappers/JacksonMapperUtil.java:185]: It was necessary to implement also a special treatment for polymorphic collections.

File: extensions/resteasy-reactive/rest-jackson/deployment/src/main/java/io/quarkus/resteasy/reactive/jackson/deployment/processor/JacksonCodeGenerator.java [hunk 4]
```diff
@@ -266,7 +266,18 @@ private void registerTypeToBeGenerated(Type type) {
...
     private void registerTypeToBeGenerated(String typeName) {
         ClassInfo classInfo = jandexIndex.getClassByName(typeName);
-        if (classInfo != null && !vetoedClass(classInfo, typeName) && shouldGenerateCodeFor(classInfo)) {
+        if (classInfo == null) {
+            return;
+        }
+        if (vetoedClass(classInfo, typeName)) {
+            if (classInfo.isSealed()) {
+                for (DotName subClassName : classInfo.permittedSubclasses()) {
+                    registerTypeToBeGenerated(subClassName.toString());
```
Comment (mariofusco) [inline extensions/resteasy-reactive/rest-jackson/deployment/src/main/java/io/quarkus/resteasy/reactive/jackson/deployment/processor/JacksonCodeGenerator.java:275]: Now it also discovers, and registers for serializer's generation, also known implementation of sealed interfaces.

Comment (gsmet) [reply extensions/resteasy-reactive/rest-jackson/deployment/src/main/java/io/quarkus/resteasy/reactive/jackson/deployment/processor/JacksonCodeGenerator.java:275]: How does it work if `classInfo` is not sealed but there are an open list of subclasses?

**Review by gsmet — COMMENTED** [review]
Thanks for the PR, I added a small question inline.

**Comment by mariofusco** [comment]
> How does it work if classInfo is not sealed but there are an open list of subclasses?

In this case I won't be able to discover the concrete classes for which I should generate the serializers and their serialization will be simply performed with the Jackson' reflection-based mechanism.

**Comment by geoand** [comment]
Thanks for this, I'll check tomorrow

File: extensions/resteasy-reactive/rest-jackson/deployment/src/test/java/io/quarkus/resteasy/reactive/jackson/deployment/test/SimpleJsonWithReflectionFreeSerializersTest.java (hunk 1 above)
Comment (geoand) [reply extensions/resteasy-reactive/rest-jackson/deployment/src/test/java/io/quarkus/resteasy/reactive/jackson/deployment/test/SimpleJsonWithReflectionFreeSerializersTest.java:54]: Let's please have a comment explaining why this is commented out, otherwise we could easily remove this code in the future

Comment (mariofusco) [reply extensions/resteasy-reactive/rest-jackson/deployment/src/test/java/io/quarkus/resteasy/reactive/jackson/deployment/test/SimpleJsonWithReflectionFreeSerializersTest.java:54]: Done.

**Review by geoand — APPROVED** [review]
