### PR TITLE
Undertow - Only load resources that are known

### LINKED ISSUE #43676: Undertow CacheResourceManager can cause frequent GC
We have recently migrated to Quarkus 3.11.2 and are facing increased heap issue.

**Below is the sample code for re-producing the issue.** 

- We have an API call for which every call with path param and all calls are saved in cache as CHM and as we receive more and more hit on this url heap started to increase.

```
-  Class Name                                                                                                                                  | Shallow Heap | Retained Heap
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
[79024] java.util.concurrent.ConcurrentHashMap$Node @ 0xf82048e0                                                                            |           32 |            32
|- <class> class java.util.concurrent.ConcurrentHashMap$Node @ 0xfab56f60 System Class                                                      |            0 |             0
|- key java.lang.String @ 0xf82048a8  META-INF/resources/v1/se/{p1}/sd/{p2}/key/1|           24 |           144
'- val java.util.Collections$EmptyList @ 0xfab845c0                                                                                         |           16 |            16
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

- Is there anything which could stop this internal caching by JVM in Quarkus

```java
import java.util.Collection;
import java.util.List;
import java.util.Scanner;
import java.util.concurrent.atomic.AtomicLong;
import java.util.stream.Stream;

public class MainTest {

    static final AtomicLong sleep = new AtomicLong(1);

    static final AtomicLong counter = new AtomicLong(1000000000);

    static void loop() {
        while (true) {
            MainTest.class.getClassLoader().getResource("META-INF/resources/my-resource/id/" + counter.get());
//            System.out.println(".");
            counter.incrementAndGet();
            try {
                Thread.sleep(sleep.get());
            } catch (InterruptedException e) {
                throw new RuntimeException(e);
            }
        }
    }

    public static void main(String[] args) {
        new Thread(() -> loop()).start();

        Scanner scanner = new Scanner(System.in);
        while (true) {
            String cmd = scanner.nextLine();
            System.out.println("delay " + sleep.get() + " /// " + counter);
            if (cmd.contains("u")) {
                sleep.set(sleep.get() / 2);
            }
            if (cmd.contains("d")) {
                sleep.set(1 + sleep.get() * 2);
            }

            printMem();
        }
    }

    private static void printMem() {
        Runtime rt = Runtime.getRuntime();
        long total_mem = rt.totalMemory() / (1024*1024);
        long free_mem = rt.freeMemory() / (1024*1024);
        long used_mem = (total_mem - free_mem)  / (1024*1024);
        System.out.println("Amount of used memory: " + used_mem + " / " + total_mem);

    }

}
```

### PR DESCRIPTION
**Pull request by gsmet**
If we try to load every resource, we end up creating cache entries in the resourceCache CHM of the AppClassLoader, which is definitely not what we want in this case, given we are supposed to serve only known resources.

Now I must admit the fix looks a bit too simple to be true :).

Fixes #43676

### CODE REVIEW

**Comment by gsmet** [comment]
@stuartwdouglas in case you have one minute to check if what I did is right or completely wrong, that would be appreciated. It looks like an oversight but you might have had very good reasons to not do that.

**Comment by gsmet** [comment]
OK, well, it doesn't look very good:

```
2024-10-04 11:25:20,035 ERROR [io.und.req.io] (executor-thread-1) Exception handling request b5951dd0-02d8-495a-8b76-5fcadb031235-1 to /foo/bar: java.lang.NullPointerException: Cannot invoke "java.util.Set.stream()" because "paths" is null
	at io.quarkus.undertow.test.ResourceManagerTestCase$ContextPathServlet.doGet(ResourceManagerTestCase.java:55)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:527)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:63)
	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:67)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:133)
```

I will have a second look after Devoxx.

**Comment by gsmet** [comment]
I pushed an additional commit (to be dropped) to get more information about the Windows CI failure.

**Comment by gsmet** [comment]
I had a closer look and we were actually collecting incorrect paths on Windows since forever but the previous code was actually fine with it. Now that we are stricter, we need to make sure the paths are correct.

**Comment by melloware** [comment]
@gsmet i think I helped cause some of this mess while trying to fix #28028 and created a test case with #33018

**Comment by prateeksharma2988** [comment]
Just for our reference, in which release version of quarkus, we should expect this fix would be available. 3.15 and 3.8 ?

**Comment by gsmet** [comment]
@prateeksharma2988 TBH the patch is a lot more involved than I thought it would be so I'm still unsure if we should backport it. It might get backported to 3.15 but I don't think it will hit 3.8.

Also we will need some bake time once 3.16 is released before we even think about backporting it.

File: extensions/undertow/runtime/src/main/java/io/quarkus/undertow/runtime/KnownPathResourceManager.java [hunk 1]
```diff
@@ -69,6 +66,9 @@ public Resource getResource(String path) throws IOException {
         if (directories.contains(path)) {
             return new DirectoryResource(path);
         }
+        if (!files.contains(path)) {
+            return null;
+        }
```
Comment (gsmet) [inline extensions/undertow/runtime/src/main/java/io/quarkus/undertow/runtime/KnownPathResourceManager.java:71]: The fix is actually here. The rest is to make paths consistent so that we don't end up comparing Unix-styled paths and Windows-style paths.

**Comment by geoand** [comment]
I will take a look tomorrow

**Review by gastaldi — APPROVED** [review]
LGTM

**Review by melloware — APPROVED** [review]

**Review by geoand — APPROVED** [review]
Indeed looks like a legit omission :)

**Comment by melloware** [comment]
Can one of you kick off this build: https://github.com/quarkusio/quarkus/pull/33018 I just rebased and want to see if it fixes that test case.
