### PR TITLE
Ensure that cookies added in filters are visible to resource methods

### LINKED ISSUE #33490: Cookies created in request filters are not accessible in Resource Methods
### Describe the bug

See https://stackoverflow.com/q/76277730/2504224

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

3.0.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #33490

### CODE REVIEW

**Review by Sgitario — APPROVED** [review]

File: independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/jaxrs/HttpHeadersImpl.java [hunk 1]
```diff
@@ -50,10 +49,7 @@ public List<String> getRequestHeader(String name) {
 
     @Override
     public Map<String, Cookie> getCookies() {
-        if (cookies == null) {
-            cookies = Collections.unmodifiableMap(HeaderUtil.getCookies(requestHeaders));
-        }
-        return cookies;
+        return Collections.unmodifiableMap(HeaderUtil.getCookies(requestHeaders));
```
Comment (gsmet) [inline independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/jaxrs/HttpHeadersImpl.java:52]: I'm a bit worried about us doing this. I see several places calling this to extract one particular cookie and that means we will build a cookie map several times if someone extracts several cookis. Not sure how it could affect performances (I'm more talking about us calling `HeaderUtil.getCookies()` several times, the wrapping probably doesn't cost that much).

Comment (geoand) [reply independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/jaxrs/HttpHeadersImpl.java:52]: That's a valid point, but in practice this is only called if users explicitly need to work with cookies, which isn't very common

Comment (geoand) [reply independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/jaxrs/HttpHeadersImpl.java:52]: > I think it's probably something that should have some bake time before we backport it.

Sure, fine with me

Comment (gsmet) [reply independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/jaxrs/HttpHeadersImpl.java:52]: In the original post in SO, they are using it. I wonder if we could somehow taint the cookies when they are modified and regenerated the map if the existing map is tainted?

Just an idea, it might not be worth the hassle or be practical.

**Comment by gsmet** [comment]
Not backported to 2.13 now that 3.2 is out and have a fix for that.
