### PR TITLE
Ensure that final methods don't prevent CDI interceptors from being applied

### LINKED ISSUE #5051: Quarkus 0.27 - JWT role validation does not work
Hi,

I have just migrated my small project from Quarkus 0.25 to 0.27 and I ran into an issue. 

Let's image we have the [SmallRye JWT extension](https://quarkus.io/guides/jwt-guide) configured and the following class:

```
@Path("/hello")
@RequestScoped
open class GreetingResource {

    @GET
    @Path("/protected")
    @Produces(MediaType.TEXT_PLAIN)
    @RolesAllowed(value = ["Echoer", "Subscriber"])
    fun helloProtected(@Context ctx: SecurityContext): String {
        val callerName = ctx.userPrincipal?.name ?: "unknown"
        return "hello $callerName"
    }
}
```

Corresponding test:

```
    @Test
    fun testHelloEndpoint_protectedAsUnknown() {
        given()
                .`when`().get("/hello/protected")
                .then()
                .statusCode(401)
    }
```

Everything works fine with 0.25. Unfortunately on Quarkus 0.27 my test fails because a request ends with HTTP 200 (```helloProtected``` method gets called).

I started looking into the problem and I found that in Quarkus 0.27:
- ```RolesFilterRegistrar#configure``` is not called and does not register ```RolesAllowedFilter```
- ```ResteasyDeploymentImpl``` contains a list (```providerClasses```) that in previous version contains ```io.quarkus.resteasy.runtime.RolesFilterRegistrar``` but in 0.27 this class is not there

 in Quarkus 0.25 ```RolesFilterRegistrar``` and ```RolesAllowedFilter``` are in ```quarkus-resteasy``` module, but 0.27 does not contain them. 

It looks that due to the fact that  ```io.quarkus.resteasy.runtime.RolesFilterRegistrar``` is not registered (present on the ```providerClasses``` list) JWT RBAC does not work. If there is a new way how ```RolesAllowedFilter``` is configured then maybe it is not enabled by default. ```RolesAllowedFilter``` class is also present in ```smallrye-jwt-2.0.9.jar```).

### PR DESCRIPTION
**Pull request by geoand**
We need security annotations to result in the creation of an interceptor
which is not possible when a method is final.
The solution we follow is to remove the final modifier from methods
that need intercepting.
This is now configurable with the default value true, meaning that
Arc will remove the final flag. If the value is set to false
Arc throws an exception at build time.

Fixes: #5051

Provides an alternative implementation to #5089 (which has now been closed) based on [this](https://github.com/quarkusio/quarkus/pull/5089#discussion_r341386797) comment

### CODE REVIEW

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Methods.java [hunk 1]
```diff
@@ -115,7 +120,9 @@ static boolean isObjectToString(MethodInfo method) {
 
     static void addInterceptedMethodCandidates(BeanDeployment beanDeployment, ClassInfo classInfo,
             Map<MethodKey, Set<AnnotationInstance>> candidates,
-            List<AnnotationInstance> classLevelBindings) {
+            List<AnnotationInstance> classLevelBindings, Consumer<BytecodeTransformer> bytecodeTransformerConsumer) {
+
+        Set<String> methodsFromWhichToRemoveFinal = new HashSet<>();
```
Comment (geoand) [inline independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Methods.java]: This could potentially remove `final` from more methods than intended, but that shouldn't be a problem, right?

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Methods.java [hunk 2]
```diff
@@ -136,20 +143,35 @@ static void addInterceptedMethodCandidates(BeanDeployment beanDeployment, ClassI
...
+        if (!methodsFromWhichToRemoveFinal.isEmpty()) {
+            bytecodeTransformerConsumer.accept(
+                    new BytecodeTransformer(classInfo.name().toString(), new BiFunction<String, ClassVisitor, ClassVisitor>() {
+                        @Override
+                        public ClassVisitor apply(String s, ClassVisitor classVisitor) {
+                            return new ClassVisitor(Opcodes.ASM7, classVisitor) {
+                                @Override
+                                public MethodVisitor visitMethod(int access, String name, String descriptor, String signature,
+                                        String[] exceptions) {
+                                    if (methodsFromWhichToRemoveFinal.contains(name)) {
```
Comment (stuartwdouglas) [inline independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Methods.java]: Technically this should match the signature as well as there could be multiple methods with the same name. In practice I don't think it will make any real difference though, removing final is not a big deal for what we are doing.

Comment (geoand) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Methods.java]: I made the same comment above only with a few seconds difference :P

Comment (geoand) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Methods.java]: This should be fixed now that I lifted some of the utils from gizmo

**Comment by geoand** [comment]
I need to rebase this on top of #5108

**Comment by geoand** [comment]
This is now rebased on top of #5108.

**Comment by geoand** [comment]
I cleared the milestone since it remains to be decided if it should go in for `0.28`

**Comment by gsmet** [comment]
Decision on this one is to wait a bit and see the feedback we have on Martin's changes before deciding if we should take the risk to include it pre 0.29.0.

**Comment by geoand** [comment]
Note to self: rebase onto master and get this one in for 1.1

**Comment by geoand** [comment]
@mkouba @gsmet should we get this one in for `1.1`?

**Review by manovotn — APPROVED** [review]
Looks good to me and +1 for tests for both cases right away!
I am not familiar with `ClassVisitor` pattern, so take my review there with a pinch of salt, but it does seem to do what I'd expect it to do ;-)

**Comment by geoand** [comment]
Thanks for the review @manovotn! 

I'll wait for another review then :)

**Comment by geoand** [comment]
@mkouba / @stuartwdouglas are you good with this?

**Review by stuartwdouglas — APPROVED** [review]

**Comment by stuartwdouglas** [comment]
LGTM but I will let @mkouba have the final say.

**Review by mkouba — CHANGES_REQUESTED** [review]
Looks really good! The only thing I'm missing is a log message that a final modifier was removed. I know that users usually don't care about these messages but it's a good habit that helps with debugging ;-).

**Comment by stuartwdouglas** [comment]
It should be debug level though

**Comment by geoand** [comment]
Added a debug level logging message

**Review by mkouba — APPROVED** [review]

**Comment by mkouba** [comment]
> [ERROR] Failed to execute goal net.revelc.code.formatter:formatter-maven-plugin:2.8.1:validate (default) on project arc-processor: File '/home/vsts/work/1/s/independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Methods.java' has not been previously formatted.  Please format file and commit before running validation! -> [Help 1]
[ERROR] 

@geoand ;-)

**Comment by geoand** [comment]
> > [ERROR] Failed to execute goal net.revelc.code.formatter:formatter-maven-plugin:2.8.1:validate (default) on project arc-processor: File '/home/vsts/work/1/s/independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Methods.java' has not been previously formatted.  Please format file and commit before running validation! -> [Help 1]
> > [ERROR]
> 
> @geoand ;-)

LOL, I'll fix it :)
