### PR TITLE
[fixes #5323] - Only SERVICE type applications are supported

### LINKED ISSUE #5323: Quarkus tries to use client_credentials grant type when calling for JWT token to Keycloak, while it should use authorization_code.
**Describe the bug**
Quarkus tries to use client_credentials grant type when calling for JWT token to Keycloak, while it should use authorization_code. 
**Expected behavior**
Quarkus should follow the Authorization Code Grant flow to authorize the user using OAuth 2.0

**Actual behavior**

- I access http://localhost:8080/
- I'm redirected to Keycloak (url looks good with scope=openid+email&response_type=code&client_id=web-application
- I log in with sample user account
- I'm redirected back with the code
- Then I get an exception in Quarkus
```
Caused by: org.keycloak.authorization.client.util.HttpResponseException: Unexpected response from server: 401 / Unauthorized / Response from server: {"error":"unauthorized_client","error_description":"Client not enabled to retrieve service account"}
    at org.keycloak.authorization.client.util.HttpMethod.execute(HttpMethod.java:95)
    at org.keycloak.authorization.client.util.HttpMethodResponse$2.execute(HttpMethodResponse.java:50)
    at org.keycloak.authorization.client.util.TokenCallable.obtainAccessToken(TokenCallable.java:121)
    at org.keycloak.authorization.client.util.TokenCallable.call(TokenCallable.java:57)
    at org.keycloak.authorization.client.resource.ProtectedResource.createFindRequest(ProtectedResource.java:276)
    at org.keycloak.authorization.client.resource.ProtectedResource.access$300(ProtectedResource.java:38)
    at org.keycloak.authorization.client.resource.ProtectedResource$5.call(ProtectedResource.java:205)
    at org.keycloak.authorization.client.resource.ProtectedResource$5.call(ProtectedResource.java:202)
    at org.keycloak.authorization.client.resource.ProtectedResource.find(ProtectedResource.java:210)
```
The error in Keycloak is:
```
09:58:25,420 WARN  [org.keycloak.events] (default task-30) type=CLIENT_LOGIN_ERROR, realmId=quarkus, clientId=web-application, userId=null, ipAddress=172.17.0.1, error=invalid_client, grant_type=client_credentials, client_auth_method=client-secret
```
Why Quarkus tries to use "grant_type=client_credentials"? It should use the grant type = "authorization_code". This looks like a bug in Quarkus, but maybe there is a flag.

**To Reproduce**
Follow the mentioned steps

**Configuration**
```properties
# OIDC Configuration
quarkus.oidc.auth-server-url=http://localhost:8180/auth/realms/quarkus
quarkus.oidc.client-id=web-application
quarkus.oidc.credentials.secret=ca21b304-XXX-XXX-XXX-51d38ef5da02
quarkus.oidc.application-type=web-app
quarkus.oidc.authentication.scopes=email
```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: 
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 

**Additional context**
https://auth0.com/docs/api-auth/tutorials/authorization-code-grant#2-exchange-the-authorization-code-for-an-access-token

### PR DESCRIPTION
**Pull request by pedroigor**
I'm also changing:

* Specific packages for deployment and runtime related classes
* Do not install the policy enforcer if in the configuration it is disabled
* Explicitly obtaining `AccessTokenCredential`

### CODE REVIEW

File: extensions/keycloak-authorization/deployment/src/main/java/io/quarkus/keycloak/pep/deployment/KeycloakPolicyEnforcerBuildStep.java [hunk 1]
```diff
@@ -31,6 +37,11 @@ EnableAllSecurityServicesBuildItem security() {
     @BuildStep
     public void setup(OidcConfig oidcConfig, KeycloakPolicyEnforcerConfig config, KeycloakPolicyEnforcerRecorder recorder,
             BeanContainerBuildItem bc) {
-        recorder.setup(oidcConfig, config, bc.getValue());
+        if (!oidcConfig.getApplicationType().equals(OidcConfig.ApplicationType.SERVICE)) {
+            throw new RuntimeException("Application type [" + oidcConfig.getApplicationType() + "] not supported");
```
Comment (sberyozkin) [inline extensions/keycloak-authorization/deployment/src/main/java/io/quarkus/keycloak/pep/deployment/KeycloakPolicyEnforcerBuildStep.java]: Perhaps `OIDCException` which is shipped with `quarkus-oidc` ?

File: docs/src/main/asciidoc/security-keycloak-authorization.adoc [hunk 2]
```diff
@@ -167,6 +167,8 @@ quarkus.oidc.credentials.secret=secret
 quarkus.keycloak.policy-enforcer.enable=true
 ----
 
+NOTE: By default, applications using the `quarkus-oidc` extension are marked as a `service` type application (see `quarkus.oidc.application-type`). This extension only support applications marked as such.
+
```
Comment (sberyozkin) [inline docs/src/main/asciidoc/security-keycloak-authorization.adoc]: May be we should say "This extensions currently supports only such `service` applications" ? To have an indirect message that we may want to support not only "service" applications in the future ?

**Comment by sberyozkin** [comment]
@pedroigor LGTM, thanks, minor updates are proposed only.

File: extensions/keycloak-authorization/runtime/src/main/java/io/quarkus/keycloak/pep/runtime/KeycloakPolicyEnforcerConfig.java [hunk 3]
```diff
@@ -35,7 +35,7 @@
          * Enables policy enforcement.
          */
         @ConfigItem
-        boolean enable;
+        public boolean enable;
```
Comment (sberyozkin) [inline extensions/keycloak-authorization/runtime/src/main/java/io/quarkus/keycloak/pep/runtime/KeycloakPolicyEnforcerConfig.java]: In `OidcConfig` we have the 'getters' pattern so I'd propose to do it here as well as opposed to have some properties public and some not, hope it works for you

Comment (stuartwdouglas) [reply extensions/keycloak-authorization/runtime/src/main/java/io/quarkus/keycloak/pep/runtime/KeycloakPolicyEnforcerConfig.java]: public properties is ok, most extensions just use properties

Comment (sberyozkin) [reply extensions/keycloak-authorization/runtime/src/main/java/io/quarkus/keycloak/pep/runtime/KeycloakPolicyEnforcerConfig.java]: Sounds good then

**Comment by pedroigor** [comment]
@sberyozkin updated with your suggestions. tks.

**Review by sberyozkin — APPROVED** [review]
