### PR TITLE
Don't pass '--enable-monitoring=heapdump' unconditionally on windows

### LINKED ISSUE #43895: Don't pass '--enable-monitoring=heapdump' unconditionally on windows
### Describe the bug

https://github.com/oracle/graal/pull/9862 introduced a new check for the usage of `--enable-monitoring=heapdump` on Windows where it's not supported.

In Quarkus we unconditionally set this option, which results in the following warning:

```
Warning: the option '--enable-monitoring' contains value(s) that are not supported on Windows: heapdump.
```

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Mandrel or GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by zakkak**
The feature is not supported on Windows

Closes https://github.com/quarkusio/quarkus/issues/43895

### CODE REVIEW

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java [hunk 1]
```diff
@@ -932,7 +932,10 @@ public NativeImageInvokerInfo build() {
                 }
 
                 List<NativeConfig.MonitoringOption> monitoringOptions = new ArrayList<>();
-                monitoringOptions.add(NativeConfig.MonitoringOption.HEAPDUMP);
+                if (!SystemUtils.IS_OS_WINDOWS || containerBuild) {
```
Comment (gsmet) [inline core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java:935]: Could you use SmallRye Common OS instead? Something like `OS.WINDOWS.isCurrent()`.

I'm not asking to change it everywhere but let's use this one when we add new code.

Comment (zakkak) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java:935]: > Could you use SmallRye Common OS instead? Something like OS.WINDOWS.isCurrent().

Sure.

> I'm not asking to change it everywhere but let's use this one when we add new code.

I think I prefer changing it everywhere so that future me (and others I hope) will see what's being used and not mistakenly use `SystemUtils` :)

**Review by gsmet — APPROVED** [review]

**Comment by zakkak** [comment]
The previous patch was resulting in an empty `--enable-monitoring=` parameter which resulted to:

```
Error: The '--enable-monitoring' option contains invalid value(s): . It can only contain 'heapdump', 'jfr', 'jvmstat', 'jmxserver' (experimental), 'jmxclient' (experimental), or 'all' (deprecated behavior: defaults to 'all' if no argument is provided).
[1/8] Initializing...                                                                                    (0.0s @ 0.19GB)
com.oracle.svm.core.util.UserError$UserException: The '--enable-monitoring' option contains invalid value(s): . It can only contain 'heapdump', 'jfr', 'jvmstat', 'jmxserver' (experimental), 'jmxclient' (experimental), or 'all' (deprecated behavior: defaults to 'all' if no argument is provided).
```

Should be fixed now.
