### PR TITLE
Fix issue with provider registration

### LINKED ISSUE #19474: security-jpa-quickstart failing in native
The native build of the security-jpa-quickstart is failing with the following errors.

Example of a build failing: https://github.com/quarkusio/quarkus-quickstarts/runs/3356862727?check_suite_focus=true .

We need this fixed before the 2.2.0.Final release.

```
Error:  org.acme.elytron.security.jpa.JpaSecurityRealmTestIT.shouldAccessAdminWhenAdminAuthenticated  Time elapsed: 0.046 s  <<< FAILURE!
java.lang.AssertionError: 
1 expectation failed.
Expected status code <200> but was <401>.


Error:  org.acme.elytron.security.jpa.JpaSecurityRealmTestIT.shouldNotAccessUserWhenAdminAuthenticated  Time elapsed: 0.014 s  <<< FAILURE!
java.lang.AssertionError: 
1 expectation failed.
Expected status code <403> but was <401>.


Error:  org.acme.elytron.security.jpa.JpaSecurityRealmTestIT.shouldAccessUserAndGetIdentityWhenUserAuthenticated  Time elapsed: 0.012 s  <<< FAILURE!
java.lang.AssertionError: 
1 expectation failed.
Expected status code <200> but was <401>.
```

### PR DESCRIPTION
**Pull request by stuartwdouglas**
Fixes #19474

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
@sberyozkin do we have native tests for bouncy castle anywhere? BC may have a similar issue.

**Comment by sberyozkin** [comment]
@stuartwdouglas Hi Stuart

`integration-tests/bouncycastle` (though one issue is open, #18642) and `integration-tests/bouncycastle-fips` have native tests but `integration-tests/bouncycastle-jsse` (#17046) and `integration-tests/bouncycastle-fips-jsse` (#14139) have them disabled. 

I'm going to check #18642 once more information is provided

**Review by sberyozkin — APPROVED** [review]

File: extensions/elytron-security-common/deployment/src/main/java/io/quarkus/elytron/security/common/deployment/QuarkusSecurityCommonProcessor.java [hunk 1]
```diff
@@ -22,6 +22,17 @@ public void registerPasswordProvider(ElytronCommonRecorder recorder) {
         recorder.registerPasswordProvider();
     }
 
+    /**
+     * Graal VM now seems to loose providers registered at static init
```
Comment (zakkak) [inline extensions/elytron-security-common/deployment/src/main/java/io/quarkus/elytron/security/common/deployment/QuarkusSecurityCommonProcessor.java:26]: Linking https://github.com/quarkusio/quarkus/issues/17046#issuecomment-879533170 for future reference
