### PR TITLE
Fix NPE when internal OIDC ID token must be signed but no client secret is available

### LINKED ISSUE #41357: OIDC private_key_jwt flow with id-token-required=false fails on generating internal IdToken
### Describe the bug

I'm integrating with a Spring Authorization Server based OIDC provider with Authorization Code Grant.
the private key jwt is used as credentials.
Since the ID token is not return in the response we also use `quarkus.oidc.authentication.id-token-required=false`
But the it fails with a NPE when trying to generate a key to use the 'internal IdToken'
```

2024-06-21 14:20:21,846 DEBUG [io.ver.ext.web.RoutingContext] (vert.x-eventloop-thread-3) RoutingContext failure (500): java.lang.NullPointerException: Cannot invoke "String.getBytes(java.nio.charset.Charset)" because "secret" is null
        at io.smallrye.jwt.util.KeyUtils.createSecretKeyFromSecret(KeyUtils.java:220)
  at io.quarkus.oidc.runtime.CodeAuthenticationMechanism.generateInternalIdToken(CodeAuthenticationMechanism.java:978)
        at io.quarkus.oidc.runtime.CodeAuthenticationMechanism$9.apply(CodeAuthenticationMechanism.java:812)
        at io.quarkus.oidc.runtime.CodeAuthenticationMechanism$9.apply(CodeAuthenticationMechanism.java:797)
 
```

when I provide a secret like `quarkus.oidc.credentials.client-secret.value=geheim`
the client secret credentials flow is choosen and this fails of course.

### Expected behavior

To not fail with a NPE or to be able to provide a secret which does not trigger the wrong client credentials flow

### Actual behavior

fails with 
```
java.lang.NullPointerException: Cannot invoke "String.getBytes(java.nio.charset.Charset)" because "secret" is null
	at io.smallrye.jwt.util.KeyUtils.createSecretKeyFromSecret(KeyUtils.java:220)
	at io.quarkus.oidc.runtime.CodeAuthenticationMechanism.generateInternalIdToken(CodeAuthenticationMechanism.java:978)
	at io.quarkus.oidc.runtime.CodeAuthenticationMechanism$9.apply(CodeAuthenticationMechanism.java:812)
	at io.quarkus.oidc.runtime.CodeAuthenticationMechanism$9.apply(CodeAuthenticationMechanism.java:797)
	at io.smallrye.context.impl.wrappers.SlowContextualBiFunction.apply(SlowContextualBiFunction.java:21)
	at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap$UniOnItemOrFailureFlatMapProcessor.performInnerSubscription(UniOnItemOrFailureFlatMap.java:86)
	at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap$UniOnItemOrFailureFlatMapProcessor.onItem(UniOnItemOrFailureFlatMap.java:54)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransform$UniOnItemTransformProcessor.onItem(UniOnItemTransform.java:43)
	at io.smallrye.mutiny.operators.uni.UniOperatorProcessor.onItem(UniOperatorProcessor.java:47)
	at io.smallrye.mutiny.operators.uni.UniOperatorProcessor.onItem(UniOperatorProcessor.java:47)
	at io.smallrye.mutiny.vertx.AsyncResultUni.lambda$subscribe$1(AsyncResultUni.java:35)
	at io.smallrye.mutiny.vertx.DelegatingHandler.handle(DelegatingHandler.java:25)
	at io.vertx.ext.web.client.impl.HttpContext.handleDispatchResponse(HttpContext.java:397)
	at io.vertx.ext.web.client.impl.HttpContext.execute(HttpContext.java:384)
	at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:362)
	at io.vertx.ext.web.client.impl.HttpContext.fire(HttpContext.java:329)
	at io.vertx.ext.web.client.impl.HttpContext.dispatchResponse(HttpContext.java:291)
	at io.vertx.ext.web.client.impl.HttpContext.lambda$null$7(HttpContext.java:507)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:279)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:261)
	at io.vertx.core.impl.ContextInternal.lambda$runOnContext$0(ContextInternal.java:59)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)

```

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

Darwin MBP-DVJM7TRQXF 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:17:33 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6031 arm64

### Output of `java -version`

java version "21.0.3" 2024-04-16 LTS Java(TM) SE Runtime Environment (build 21.0.3+7-LTS-152) Java HotSpot(TM) 64-Bit Server VM (build 21.0.3+7-LTS-152, mixed mode, sharing)

### Quarkus version or git rev

3.11.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.8 

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sberyozkin**
Fixes #41357.

Returning secured (typically signed) ID tokens is required for any OIDC server.

But Oauth2 servers don't have a concept of ID token. GitHub, and many other providers including Spring Authorization Server mentioned in #41357, don't return it. In such cases, Quarkus creates an internal ID token to represent a user authentication, and to support the code which expects the presence of the ID token. The next question is how to sign in, and until now, with all supported cases for GitHub, etc, the client secret is available, which is enough to create a symmetric signature, there is no need to make it more complex, since on top of it, the ID and other tokens will be kept in the encrypted session cookie and given this internally generated ID token does not represent any real data supplied by GitHub or other OAuth2 provider.

But with  #41357, a `private_key_jwt` authentication method is used. I.e, Quarkus, when requesting tokens from the OAuth2 provider, does not authenticate itself using the client id and secret, but instead generates a JWT token signed with a private key and then Spring Authorization Server will verify it with the earlier registered client application public key.

Since internal ID token signature process, was, until now, depending on the presence of the client secret, NPE was thrown.

So this PR fixes it by adding an additional check, by checking if the private key is available,  and if yes created a secret key out of its digest to continue supporting an internal ID token signature process. And if the private key is also not available then it now properly falls back to a generated secret key. It has to be done when creating an internal id token and verifying it.

Similar update was added to the creation of the session cookie's encryption secret key.

I've updated one of the OIDC wiremock tests which uses a github provider to confirm that the internal ID token signature and verification works and that now, the session cookie is also encrypted by the secret key created out of the private key's digest - until this PR, session encryption key ignores the presence of this private key and goes to generating the secret key which may impact the restarts, etc.

It took me a little while to realize trying to reuse the session encryption key for signing the internal ID token, as I originally suggested at  #41357, was a bad idea, it would work for the default token state manager, but asking users to create the encryption key required by this manager, but when they use a custom manager like Redis one, would be very strange...

### CODE REVIEW

**Comment by sberyozkin** [comment]
Oops, noticed I forgot to enable some test calls

File: extensions/oidc-common/runtime/src/main/java/io/quarkus/oidc/common/runtime/OidcCommonUtils.java [hunk 1]
```diff
@@ -308,6 +309,23 @@ public static String jwtSecret(Credentials creds) {
...
+            LOG.debug("Client secret is not configured, "
+                    + "trying to get the configured 'client_jwt_secret' secret");
+            encSecret = jwtSecret(creds);
+        }
+        return encSecret;
+    }
+
+    public static SecretKey generateSecretKey() throws Exception {
+        KeyGenerator keyGenerator = KeyGenerator.getInstance("AES");
+        keyGenerator.init(256);
```
Comment (gastaldi) [inline extensions/oidc-common/runtime/src/main/java/io/quarkus/oidc/common/runtime/OidcCommonUtils.java:325]: Can this be reused between calls?

**Review by gastaldi — APPROVED** [review]
LGTM, added a minor observation

File: extensions/oidc-common/runtime/src/main/java/io/quarkus/oidc/common/runtime/OidcCommonUtils.java (hunk 1 above)
Comment (sberyozkin) [reply extensions/oidc-common/runtime/src/main/java/io/quarkus/oidc/common/runtime/OidcCommonUtils.java:325]: Hi @gastaldi, can you clarify please ? As far as generating a key, it is done once, once per different properties, and then this key is reused, sorry if I've missed your point

Comment (gastaldi) [reply extensions/oidc-common/runtime/src/main/java/io/quarkus/oidc/common/runtime/OidcCommonUtils.java:325]: I mean the `KeyGenerator` instance, but if it's done once, then that's okay

Comment (sberyozkin) [reply extensions/oidc-common/runtime/src/main/java/io/quarkus/oidc/common/runtime/OidcCommonUtils.java:325]: @gastaldi I see, thanks, the key is only generated as the last fallback (for session cookie encryption key, for state encryption, etc) but if we did it dynamically, then it would fail fast, for example, we'd encrypt or sign something with it, like a session cookie, and then when it gets back, we won't be able to decrypt or verify signature with another generated secret.

As far as reusing KeyGenerator is concerned, I guess, it would probably make a sequence of keys generated from some shared seed and  that would probably mean it would decrease the entropy quality, but I don't know if it is even theoretically exploitable :-)

Comment (gsmet) [reply extensions/oidc-common/runtime/src/main/java/io/quarkus/oidc/common/runtime/OidcCommonUtils.java:325]: I think the question was about the cost of setting it up.
Depending on how often we do it and how many times we call it, we might need to have a tradeoff and initialize it lazily but store it somewhere.

Now if it's called once for the life of the application, we don't care. If it's called once per user, then we need to cache it.

Comment (sberyozkin) [reply extensions/oidc-common/runtime/src/main/java/io/quarkus/oidc/common/runtime/OidcCommonUtils.java:325]: @gsmet It is done once per the application for a given property for a given OIDC tenant, and only, I'd say, in 10%-20% cases when the final fallback in necessary, and then and this key will be used for all the users working with this tenant. Key is not created per every user. So all is good.

I'd still try to avoid caching key generators, if there was a necessity for the optimizations, but only the produced Secret Keys.

**Comment by sberyozkin** [comment]
@gastaldi @gsmet, thanks for the feedback, let me merge, any concerns going forward about anything in the OIDC code, let me know please
