### PR TITLE
WebSockets Next: CloseReason - fix NPE if connection terminated abruptly

### LINKED ISSUE #42271: NPE in websockets-next
### Describe the bug

Getting NPE
```
java.lang.NullPointerException: Cannot invoke "java.lang.Short.shortValue()" because the return value of "io.vertx.core.http.WebSocketBase.closeStatusCode()" is null
	at io.quarkus.websockets.next.runtime.WebSocketConnectionBase.closeReason(WebSocketConnectionBase.java:134)
	at myapp.core.stream.Streaming_WebSocketServerEndpoint.doOnClose(Unknown Source)
	at io.quarkus.websockets.next.runtime.WebSocketEndpointBase$4.call(WebSocketEndpointBase.java:158)
	at io.quarkus.websockets.next.runtime.WebSocketEndpointBase$4.call(WebSocketEndpointBase.java:152)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$0(ContextImpl.java:178)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:279)
	at io.vertx.core.impl.ContextImpl.lambda$internalExecuteBlocking$2(ContextImpl.java:210)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:635)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

It seems like error is happening here https://github.com/quarkusio/quarkus/blob/450681e17a86d19dcae88621dc8f6922598b1dac/extensions/websockets-next/runtime/src/main/java/io/quarkus/websockets/next/runtime/WebSocketConnectionBase.java#L134

`closeStatusCode` is `Short` and it's null. It throws when it tries to unbox (`Short` -> `short`)

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mkouba**
- fix invocation of OnClose callback with a CloseReason param
- resolves #42271

### CODE REVIEW

**Review by geoand — APPROVED** [review]

File: extensions/websockets-next/runtime/src/main/java/io/quarkus/websockets/next/runtime/WebSocketConnectionBase.java [hunk 1]
```diff
@@ -131,7 +131,12 @@ public BroadcastSender broadcast() {
     public CloseReason closeReason() {
         WebSocketBase ws = webSocket();
         if (ws.isClosed()) {
-            return new CloseReason(ws.closeStatusCode(), ws.closeReason());
+            Short code = ws.closeStatusCode();
+            if (code == null) {
+                // This could happen if the connection is terminated abruptly
+                return CloseReason.INTERNAL_SERVER_ERROR;
```
Comment (gsmet) [inline extensions/websockets-next/runtime/src/main/java/io/quarkus/websockets/next/runtime/WebSocketConnectionBase.java:137]: Does it make sense to return internal server error in this case?

Comment (mkouba) [reply extensions/websockets-next/runtime/src/main/java/io/quarkus/websockets/next/runtime/WebSocketConnectionBase.java:137]: Well, it's kind of an internal server error. Also I did not find a better code in the list defined by the spec: https://datatracker.ietf.org/doc/html/rfc6455#section-7.4.1. There is `1006` but it's reserved and has a special meaning.
