### PR TITLE
Use correct default config source name to check Kubernetes config disabled

### LINKED ISSUE #35673: Kubernetes secret not read anymore in 3.3
### Describe the bug

I had an application using:

```
# Kubernetes
%prod.quarkus.kubernetes-config.secrets.enabled=true
quarkus.kubernetes-config.secrets=device-database


# Database
quarkus.hibernate-orm.database.generation=drop-and-create

%prod.quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.username=${database-user}
%prod.quarkus.datasource.password=${database-password}
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://device-database:5432/device-database
```

It was working perfectly in 3.2.0.CR1.

I've updated it to 3.3.1, and the secret is not read anymore.

The secret is the following:

```
kind: Secret
apiVersion: v1
metadata:
  name: device-database
data:
  database-name: ZGV2aWNlLWRhdGFiYXNl
  database-password: ZjdHVHFQcW1nWW5wMkNOQg==
  database-user: dXNlcjJLNA==
type: Opaque
```

### Expected behavior

The values from the secret should be read as before.

### Actual behavior

The secret is not read. 

I can see that the secret permissions are added to the descriptor:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: view-secrets
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: measure-enrichment-view-secrets
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: view-secrets
subjects:
  - kind: ServiceAccount
    apiGroup: ""
    name: measure-enrichment
```

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by radcortez**
- Fixes #35673

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Comment by cescoffier** [comment]
@radcortez do you know if 3.2 is affected? If so, we need to backport it.

File: extensions/kubernetes-config/runtime/src/main/java/io/quarkus/kubernetes/config/runtime/KubernetesConfigSourceFactory.java [hunk 1]
```diff
@@ -84,7 +84,7 @@ Iterable<ConfigSource> getConfigSources(final KubernetesConfigSourceConfig confi
 
     private boolean isExplicitlyDisabled(ConfigSourceContext context) {
         ConfigValue configValue = context.getValue("quarkus.kubernetes-config.enabled");
-        if (AbstractRawDefaultConfigSource.NAME.equals(configValue.getConfigSourceName())) {
+        if ("DefaultValuesConfigSource".equals(configValue.getConfigSourceName())) {
```
Comment (cescoffier) [inline extensions/kubernetes-config/runtime/src/main/java/io/quarkus/kubernetes/config/runtime/KubernetesConfigSourceFactory.java:87]: Should it be a constant? IS the other constant still in use?

Comment (geoand) [reply extensions/kubernetes-config/runtime/src/main/java/io/quarkus/kubernetes/config/runtime/KubernetesConfigSourceFactory.java:87]: My understanding is that this will go away when the `TODO` is implemented

**Comment by radcortez** [comment]
> @radcortez do you know if 3.2 is affected? If so, we need to backport it.

For 3.2 no. This was introduced with https://github.com/quarkusio/quarkus/pull/34457. The issue is that the Default source for mappings have a different name, so the behaviour was not the same.

File: extensions/kubernetes-config/runtime/src/main/java/io/quarkus/kubernetes/config/runtime/KubernetesConfigSourceFactory.java (hunk 1 above)
Comment (radcortez) [reply extensions/kubernetes-config/runtime/src/main/java/io/quarkus/kubernetes/config/runtime/KubernetesConfigSourceFactory.java:87]: Yes, I need to improve this a bit. This was a migration as is, so I didn't want to introduce other changes as well. As for the constant, the source is provided by SR Config, so I prefer to add the constant there.
