### PR TITLE
Ensure that new line chars don't break Panache projection

### LINKED ISSUE #29838: StringIndexOutOfBoundsException in panache when using `project` and a linebreak before `FROM`
When executing a Panache query that (a) contains a `project`ion and (b) has a line break before the `FROM` clause, a `StringIndexOutOfBoundsException` is thrown:

```
java.lang.StringIndexOutOfBoundsException: Range [7, -1) out of bounds for length 30
        [...]
        at java.base/java.lang.String.substring(String.java:2715)
        at io.quarkus.hibernate.orm.panache.common.runtime.CommonPanacheQueryImpl.project(CommonPanacheQueryImpl.java:98)
        at io.quarkus.hibernate.orm.panache.runtime.PanacheQueryImpl.project(PanacheQueryImpl.java:33)
        at org.acme.MyEntityRepo.listEverything(MyEntityRepo.java:19)
        [...]
        at org.acme.MyEntityRepoTest_Subclass.testSelect(Unknown Source)
        [...]
```

I attached a reproducer containing this panache repository:

```java
@ApplicationScoped
@Transactional
public class MyEntityRepo implements PanacheRepository<MyEntity> {
    public List<SomeProjection> listEverything() {
        return find("""
                SELECT e.field
                FROM MyEntity e
                """)
                .project(SomeProjection.class)
                .list();
    }

    @Value
    @RegisterForReflection
    static class SomeProjection {
        String field;
    }
}
```

[quarkus-reproducer-panache-from-linebreak.zip](https://github.com/quarkusio/quarkus/files/10219599/quarkus-reproducer-panache-from-linebreak.zip)

The issue seems to be in `CommonPanacheQueryImpl#L95`:

```java
        if (lowerCasedTrimmedQuery.startsWith("select ")) {
            int endSelect = lowerCasedTrimmedQuery.indexOf(" from ");
            String trimmedQuery = query.trim();
            // 7 is the length of "select "
            String selectClause = trimmedQuery.substring(7, endSelect).trim();
```

Where `endSelect` is `-1` because the `from` is not necessarily surrounded by spaces in all cases, such as in the reproducer.

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #29838

### CODE REVIEW

File: extensions/panache/hibernate-orm-panache-common/runtime/src/main/java/io/quarkus/hibernate/orm/panache/common/runtime/CommonPanacheQueryImpl.java [hunk 1]
```diff
@@ -54,6 +54,8 @@ public void close() {
 
     private Map<String, Map<String, Object>> filters;
 
+    private final String lineSeparator = System.getProperty("line.separator");
```
Comment (loicmathieu) [inline extensions/panache/hibernate-orm-panache-common/runtime/src/main/java/io/quarkus/hibernate/orm/panache/common/runtime/CommonPanacheQueryImpl.java:57]: Maybe static ?
Or maybe it can be an issue with crosscompiling for a native image if it's final. Anyway not a big deal.

File: integration-tests/hibernate-orm-panache/src/main/java/io/quarkus/it/panache/TestEndpoint.java [hunk 2]
```diff
@@ -1188,6 +1188,11 @@ public String testProjection() {
         person = Person.find("name = ?1", "2").project(PersonName.class).firstResult();
         Assertions.assertEquals("2", person.name);
 
+        person = Person.find("select uniqueName, name\nfrom io.quarkus.it.panache.Person\nwhere name = ?1", "2")
```
Comment (loicmathieu) [inline integration-tests/hibernate-orm-panache/src/main/java/io/quarkus/it/panache/TestEndpoint.java:1191]: Shouldn't you use the `System.getProperty("line.separator")` instead of `\n` or it may not work on Windows CI ?

**Review by loicmathieu — CHANGES_REQUESTED** [review]

File: integration-tests/hibernate-orm-panache/src/main/java/io/quarkus/it/panache/TestEndpoint.java (hunk 2 above)
Comment (geoand) [reply integration-tests/hibernate-orm-panache/src/main/java/io/quarkus/it/panache/TestEndpoint.java]: Good point, fixed

**Review by loicmathieu — APPROVED** [review]
lgtm

File: extensions/panache/hibernate-orm-panache-common/runtime/src/main/java/io/quarkus/hibernate/orm/panache/common/runtime/CommonPanacheQueryImpl.java (hunk 1 above)
Comment (gsmet) [inline extensions/panache/hibernate-orm-panache-common/runtime/src/main/java/io/quarkus/hibernate/orm/panache/common/runtime/CommonPanacheQueryImpl.java:57]: Is it really a good idea to use this? From the original issue, it seems that the new lines are provided by the source code and this won't necessarily match the system line separator? Or am I missing something?

Comment (loicmathieu) [reply extensions/panache/hibernate-orm-panache-common/runtime/src/main/java/io/quarkus/hibernate/orm/panache/common/runtime/CommonPanacheQueryImpl.java:57]: This may be difficult to cover all use cases as someone may add “\n” , “\r”, or “\r\n” anywhere and request can comes from a config file.
Maybe it should be done for the 3 possible line separator, or using a "\R": https://docs.oracle.com/javase/8/docs/api/java/util/regex/Pattern.html#lineending

Comment (geoand) [reply extensions/panache/hibernate-orm-panache-common/runtime/src/main/java/io/quarkus/hibernate/orm/panache/common/runtime/CommonPanacheQueryImpl.java:57]: I think that makes sense. Do you want to follow up with that @loicmathieu ?

Comment (Felk) [reply extensions/panache/hibernate-orm-panache-common/runtime/src/main/java/io/quarkus/hibernate/orm/panache/common/runtime/CommonPanacheQueryImpl.java:57]: Thinking of weird contrived edge cases, what if someone writes a query like this...?
```sql
select o.id, 'came from Sydney' as comment from Orders o
```

Comment (loicmathieu) [reply extensions/panache/hibernate-orm-panache-common/runtime/src/main/java/io/quarkus/hibernate/orm/panache/common/runtime/CommonPanacheQueryImpl.java:57]: @gsmet i'll provide a PR to direclty handle `\n` and `\r` it will be better.
@Felk this kind of edge case cannot be handled as we didn't parse the query. For this, I strongly suggest to not use Panache.
