### PR TITLE
Spring Data Repository nested camel-case properties resolution fix

### LINKED ISSUE #13067: Spring Data Repository with nested camel-case properties does not work with Quarkus
**Describe the bug**
If a repository method addresses a nested entities Quarkus cannot parse the method.

Given the follwing JPA entities: 
```java
@Entity
@Table(name = "RACE_TEAMS")
public class RaceTeamEntity {

    @Id
    @Column(name = "ID", length = 26)
    private String id;

    @Column(name = "NAME", nullable = false, length = 256)
    private String name;
    ...
}

@Entity
@Table(name = "RACE_CAR_DRIVERS")
public class RaceCarDriverEntity {

    @Id
    @Column(name = "ID", length = 26)
    private String id;

    @ManyToOne
    @JoinColumn(name = "RACE_TEAM_ID", nullable = false)
    private RaceTeamEntity team;

    @Column(name = "NAME", nullable = false, length = 256)
    private String name;
}

@Entity
@Table(name = "CLASSIC_CARS")
public class ClassicCarEntity {

    @Id
    @Column(name = "CLASSIC_CAR_ID", length = 26)
    private String id;

    @ManyToOne
    @JoinColumn(name = "BRAND_ID", nullable = false)
    private CarBrandEnity carBrand;

    @ManyToOne
    @JoinColumn(name = "DRIVER_ID", nullable = false)
    private RaceCarDriverEntity driver;

    @Column(name = "NAME", nullable = false, length = 256)
    private String name;
}
```

The repository method `findByRaceCarDriverTeamName` should find the `RaceCarEntity` by the `Name` of the `Driver`'s `RaceTeam`
```java
@Repository
public interface ClassicCarRepository extends JpaRepository<ClassicCarEntity, String> {
    List<ClassicCarEntity> findByRaceCarDriverTeamName(String teamName);
}
```
But instead throws `UableToParseMethodException: Entity org.acme.resteasy.entities.ClassicCarEntity does not contain a field named: raceCarDriverTeamName. Offending method is findByRaceCarDriverTeamName`

**Expected behavior**
Camel-case properties can be used as in Spring Data and sub-properties are correctly matched (e.g. the expression `tomatoSpagettiSauceColor` could mean `tomato.spagehtti.sauce.color` or `tomatoSpaghetti.sauce.color` or `tomatoSpaghetti.sauceColor` or `tomato.spaghetti.sauceColor`  or `tomato.spaghettiSauce.color`or ...)

See https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.query-methods.query-property-expressions

**Actual behavior**
An `UnableToParseMethodException`is thrown if nested camel-case property address sub-entities.

**To Reproduce**

Checkout https://github.com/renegrob/spring-data-jpa-repo-method-issue

1. Execute `./mvnw compile quarkus:dev` on the command line

Error in the console output:
```
2020-11-02 16:33:45,534 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.spring.data.deployment.SpringDataJPAProcessor#build threw an exception: io.quarkus.spring.data.deployment.UnableToParseMethodException: Entity org.acme.resteasy.entities.ClassicCarEntity does not contain a field named: raceCarDriverTeamName. Offending method is findByRaceCarDriverTeamName
```

**Screenshots**
n/a

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
```
$ uname -a
Linux automatix 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
 - Output of `java -version`: 
```
$ java -version
openjdk version "11.0.9" 2020-10-20 LTS
OpenJDK Runtime Environment Zulu11.43+21-CA (build 11.0.9+11-LTS)
OpenJDK 64-Bit Server VM Zulu11.43+21-CA (build 11.0.9+11-LTS, mixed mode)
```
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 
`1.9.1.Final`
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
```
./mvnw --version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/gro/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3
Java version: 11.0.9, vendor: Azul Systems, Inc., runtime: /usr/lib/jvm/zulu11-ca-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-52-generic", arch: "amd64", family: "unix"
```

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by renegrob**
Fix #13067.
I re-implemented the resolution of nested properties now they should be resolved as described here https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.query-methods.query-property-expressions. I also widened the allowed types for the resolved properties to the types supported by JPA.
The property resolution is now done iteratively and tries to find the longest match (but at most to the next underscore because the underscore is treated as reserved character according to the Spring Data JPA documentation).

### CODE REVIEW

**Comment by geoand** [comment]
Thanks for this!

I think we really need some tests covering the issues the PR addresses

**Comment by renegrob** [comment]
@geoand I added some unit tests (and found and fixed some issues). I think the coverage should be okay now.

File: integration-tests/spring-data-jpa/src/main/java/io/quarkus/it/spring/data/jpa/Employee.java [hunk 1]
```diff
@@ -0,0 +1,69 @@
+package io.quarkus.it.spring.data.jpa;
+
+import javax.persistence.Column;
+import javax.persistence.Entity;
+import javax.persistence.FetchType;
+import javax.persistence.JoinColumn;
+import javax.persistence.ManyToOne;
+import javax.persistence.Table;
+
+// TODO: @Entity(name = "EmployeeEntity")
```
Comment (geoand) [inline integration-tests/spring-data-jpa/src/main/java/io/quarkus/it/spring/data/jpa/Employee.java:10]: Does this need to be removed?

**Comment by geoand** [comment]
Thanks a lot!

I'll take a closer look tomorrow or Monday. 
Can you please take the PR out of draft so we can get a CI run?

File: extensions/spring-data-jpa/deployment/src/main/java/io/quarkus/spring/data/deployment/MethodNameParser.java [hunk 2]
```diff
@@ -610,6 +542,37 @@ private FieldInfo getField(String fieldName) {
         return mappedSuperClassInfoElements;
     }
 
+    private boolean isSupportedHybernateType(DotName dotName) {
```
Comment (geoand) [inline extensions/spring-data-jpa/deployment/src/main/java/io/quarkus/spring/data/deployment/MethodNameParser.java:545]: Minor nitpick: `Hibernate` instead of `Hybernate`

File: integration-tests/spring-data-jpa/src/main/resources/import.sql [hunk 3]
```diff
@@ -69,3 +69,11 @@ INSERT INTO cart(id, customer_id, status) VALUES (3, 3, 'CANCELED');
 
 INSERT INTO orders(id, cart_id) VALUES (1, 1);
 INSERT INTO orders(id, cart_id) VALUES (2, 2);
+
+INSERT INTO org_unit_table(id, name) VALUES (1, 'Delivery Unit');
```
Comment (geoand) [inline integration-tests/spring-data-jpa/src/main/resources/import.sql:73]: I don't think `org_` adds much value

**Review by geoand — COMMENTED** [review]
This is great work, thanks a lot!

I added a couple of tiny comments, can you please address them so we can then merge this?

**Review by geoand — APPROVED** [review]
:+1:

**Comment by renegrob** [comment]
@geoand My branch fails but I don't see how the test failures are related to my changes. I saw that other pull requests seem to have similar problems. The branches run against an isolated repository, don't they? (Unfortunately maven does not support hash based build caches.) Do the builds share any other resources?

**Comment by geoand** [comment]
They don't share anything.

The failure is likely just a flake. If that is the case, I'll merge your PR anyway.

I'll check on Monday.

**Comment by geoand** [comment]
Can you please rebase onto the latest master in order to pick up the CI fix?

**Comment by renegrob** [comment]
@geoand Thanks for helping fixing the CI!

**Comment by geoand** [comment]
Don't thank me, thank @gsmet 😉

**Comment by gsmet** [comment]
Thanks!

@geoand is this something we want to backport to 1.10.1? If so, please add the label, thanks!

**Comment by geoand** [comment]
Yeah, I guess we can
