### PR TITLE
OpenShift: Fix `quarkus.openshift.arguments` property

### LINKED ISSUE #15943: OpenShift: We can't provide Java arguments
## Describe the bug
Before [this PR](https://github.com/quarkusio/quarkus/pull/15670) was merged, we could add Java arguments via the jvmArgs properties (which was wrong and fixed as part of this PR). However, now we don't have any properties or way to add real Java arguments.

As an example, the args section in the YAML look like:

```
args:
    - '-Dquarkus.http.host=0.0.0.0'
    - '-Djava.util.logging.manager=org.jboss.logmanager.LogManager'
    - '-jar'
    - /deployments/quarkus-run.jar
```

And what we can't achieve is to add Java arguments:

```
args:
    - '-Dquarkus.http.host=0.0.0.0'
    - '-Djava.util.logging.manager=org.jboss.logmanager.LogManager'
    - '-jar'
    - /deployments/quarkus-run.jar
    - ARG1
    - ARG2
```

I tried to use the property `quarkus.openshift.arguments` but it's replacing all the args section as:

```
args:
    - ARG1
    - ARG2
```

I think this issue is also relevant for Kubernetes and S2I.

### PR DESCRIPTION
**Pull request by Sgitario**
At the moment, when using the `quarkus.openshift.arguments` property and an unknown base image, it's replacing the arguments that are required for the Java command and hence making the application fail. For example, with no arguments are supplied, the OpenShift.yaml looks like:

```
command: java
args:
    - '-Dquarkus.http.host=0.0.0.0'
    - '-Djava.util.logging.manager=org.jboss.logmanager.LogManager'
    - '-jar'
    - /deployments/quarkus-run.jar
```

If we now set `quarkus.openshift.arguments=A,B`, then it changes to:

```
command: java
args:
    - 'A'
    - 'B'
```

And then, the above configuration would make our deployment fail (because the jar is missing).

This PR addresses the above situation by moving the required JAVA arguments to be part of the command and leaving the args field empty:

```
command: 
    - java
    - '-Dquarkus.http.host=0.0.0.0'
    - '-Djava.util.logging.manager=org.jboss.logmanager.LogManager'
    - '-jar'
    - /deployments/quarkus-run.jar
```

And now if we supply the arguments: `quarkus.openshift.arguments=A,B`, then:

```
command: 
    - java
    - '-Dquarkus.http.host=0.0.0.0'
    - '-Djava.util.logging.manager=org.jboss.logmanager.LogManager'
    - '-jar'
    - /deployments/quarkus-run.jar
args:
    - 'A'
    - 'B'
```

Users would still be able to replace the whole command by using the command property: `quarkus.openshift.command` which I think it's the expected behaviour. Now the command and argument properties work the same in Kubernetes and OpenShift deployments, regardless the base image we use. 

I've covered these changes using integration tests with the following scenarios:
- Kubernetes when using arguments
- Kubernetes when using command
- OpenShift when using arguments
- OpenShift when using default command
- OpenShift when using commands

Also, I've verified these changes manually by deploying a sample application (Rest ++ Command Line application) and now it works fine when supplying or not supplying custom arguments.

Fix https://github.com/quarkusio/quarkus/issues/15943

### CODE REVIEW

**Comment by Sgitario** [comment]
cc @iocanel @geoand

**Comment by iocanel** [comment]
> Users would still be able to replace the whole command by using the command property: quarkus.openshift.command which I think it's the expected behaviour.

@Sgitario: Can you please elaborate on this? I always considered the use of `command` and `arguments` to be quite literal (e.g. command: the path to the binary. arguments: the actual app arguments). Of course, this might be just my perception and I may totally miss the intended use. @geoand wdyt?

**Comment by Sgitario** [comment]
> > Users would still be able to replace the whole command by using the command property: quarkus.openshift.command which I think it's the expected behaviour.
> 
> @Sgitario: Can you please elaborate on this? I always considered the use of `command` and `arguments` to be quite literal (e.g. command: the path to the binary. arguments: the actual app arguments). Of course, this might be just my perception and I may totally miss the intended use. @geoand wdyt?

As far I see it, the problem was that we were mixing up the command with arguments (the command was "java" and the arguments "-jar quarkus-run.jar") which from my point of view does not make totally sense.

With these changes, the command is "java -jar quarkus-run.jar" and the arguments are empty by default. Therefore, now they are indeed literal. Users are still able to overwrite the command and arguments, but now they are not tied up with each other.

**Comment by iocanel** [comment]
> As far I see it, the problem was that we were mixing up the command with arguments (the command was "java" and the arguments "-jar quarkus-run.jar") which from my point of view does not make totally sense.

From my point of view, this makes total sense.
However, I see that command is not a `String` but a `List<String>` which strongly implies that `command` is not just the binary.
So, I would like a second opinion before I change my mind on this. @geoand @Ladicek wdyt?

**Comment by geoand** [comment]
I would like use to do what we do in `JibConfig`m where we have `List<String> jvmArguments` that are **additive** to whatever is done by other parts of the image generation process, but we also have `Optional<List<String>> jvmEntrypoint` which allows a user to specify whatever launch command they like (so it could be a bash script with arguments)

**Comment by iocanel** [comment]
> I would like use to do what we do in `JibConfig`m where we have `List<String> jvmArguments` that are **additive** to whatever is done by other parts of the image generation process, but we also have `Optional<List<String>> jvmEntrypoint` which allows a user to specify whatever launch command they like (so it could be a bash script with arguments)

Wouldn't that cause confusion between jvm and native modes?

**Comment by geoand** [comment]
> > I would like use to do what we do in `JibConfig`m where we have `List<String> jvmArguments` that are **additive** to whatever is done by other parts of the image generation process, but we also have `Optional<List<String>> jvmEntrypoint` which allows a user to specify whatever launch command they like (so it could be a bash script with arguments)
> 
> Wouldn't that cause confusion between jvm and native modes?

Which is why Jib has separate options for jvm and native :)

**Comment by iocanel** [comment]
> > > I would like use to do what we do in `JibConfig`m where we have `List<String> jvmArguments` that are **additive** to whatever is done by other parts of the image generation process, but we also have `Optional<List<String>> jvmEntrypoint` which allows a user to specify whatever launch command they like (so it could be a bash script with arguments)
> > 
> > 
> > Wouldn't that cause confusion between jvm and native modes?
> 
> Which is why Jib has separate options for jvm and native :)

This is however, not the case for our configuration files and I am afraid that things will get too complicated.

**Comment by Sgitario** [comment]
> > > > I would like use to do what we do in `JibConfig`m where we have `List<String> jvmArguments` that are **additive** to whatever is done by other parts of the image generation process, but we also have `Optional<List<String>> jvmEntrypoint` which allows a user to specify whatever launch command they like (so it could be a bash script with arguments)
> > > 
> > > 
> > > Wouldn't that cause confusion between jvm and native modes?
> > 
> > 
> > Which is why Jib has separate options for jvm and native :)
> 
> This is however, not the case for our configuration files and I am afraid that things will get too complicated.

At first, I thought to add a new property `quarkus.openshift.app-arguments` or similar, but then my concern was that this was getting indeed too complicated imho taking into account that there is already an existing `quarkus.openshift.arguments` that only works when we use known base images.

**Comment by geoand** [comment]
> This is however, not the case for our configuration files and I am afraid that things will get too complicated.

In that case, I agree with your proposal :)

**Comment by Ladicek** [comment]
I think the proposal here kinda sorta makes sense, because according to https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#notes, `command` is akin to image's `ENTRYPOINT`, while `args` are akin to image's `CMD`. But I didn't really think this through, there may easily be huge gaps in my understanding :-)

**Comment by iocanel** [comment]
Thanks @Ladicek that really helps.

According to the link provided, the command pretty much corresponds to the Dockerfile entrypoint and arguments to Dockerfile cmd. Some additional clarifications are also added:

```
When you override the default Entrypoint and Cmd, these rules apply:
If you do not supply command or args for a Container, the defaults defined in the Docker image are used.
If you supply a command but no args for a Container, only the supplied command is used. The default EntryPoint and the default Cmd defined in the Docker image are ignored.
If you supply only args for a Container, the default Entrypoint defined in the Docker image is run with the args that you supplied.
If you supply a command and args, the default Entrypoint and the default Cmd defined in the Docker image are ignored. Your command is run with your args.
```

Now how cmd and entrypoint are meant to be used in dockerland is another story, but I feel that `entrypoint` corresponds to  the `what` the image is about and is something that isn't meant to be changed per invocation, while `cmd` corresponds to the `how` (e.g. application args & parameters?).

This means that I am starting to accept what @Sgitario suggests and the only real question if this is a very intrusive change is going to break things for users.

**Comment by Sgitario** [comment]
> Thanks @Ladicek that really helps.
> 
> According to the link provided, the command pretty much corresponds to the Dockerfile entrypoint and arguments to Dockerfile cmd. Some additional clarifications are also added:
> 
> ```
> When you override the default Entrypoint and Cmd, these rules apply:
> If you do not supply command or args for a Container, the defaults defined in the Docker image are used.
> If you supply a command but no args for a Container, only the supplied command is used. The default EntryPoint and the default Cmd defined in the Docker image are ignored.
> If you supply only args for a Container, the default Entrypoint defined in the Docker image is run with the args that you supplied.
> If you supply a command and args, the default Entrypoint and the default Cmd defined in the Docker image are ignored. Your command is run with your args.
> ```
> 
> Now how cmd and entrypoint are meant to be used in dockerland is another story, but I feel that `entrypoint` corresponds to the `what` the image is about and is something that isn't meant to be changed per invocation, while `cmd` corresponds to the `how` (e.g. application args & parameters?).
> 
> This means that I am starting to accept what @Sgitario suggests and the only real question if this is a very intrusive change is going to break things for users.

This could be a breaking change for users that were using the OpenShift extension, an unknown base image and the `quarkus.openshift.arguments` property to tweak the Java command:

```
command: java
args:
    - '-Dquarkus.http.host=0.0.0.0'
    - '-DmyUserChange=anotherValue`
    - '-Djava.util.logging.manager=org.jboss.logmanager.LogManager'
    - '-jar'
    - /deployments/quarkus-run.jar
    - ARG1
```

With these changes, they should overwrite the Java command using the `quarkus.openshift.command` (and include the binary). Being said that, I don't think users are doing so or should have been doing so.

There are a failing test that I'm trying to investigate, but I can't reproduce locally :/

File: extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/KubernetesCommonHelper.java [hunk 1]
```diff
@@ -189,6 +188,50 @@
...
+     *
+     * @param target The deployment target (e.g. kubernetes, openshift, knative)
+     * @param name The name of the resource to accept the configuration
+     * @param config The {@link PlatformConfiguration} instance
+     * @param command Optional command item from other extensions
+     */
+    private static List<DecoratorBuildItem> createArgsDecorator(Optional<Project> project, String target, String name,
+            PlatformConfiguration config, Optional<KubernetesCommandBuildItem> command) {
+        List<String> args = new ArrayList<>();
+        command.ifPresent(cmd -> args.addAll(Arrays.asList(cmd.getArgs())));
```
Comment (iocanel) [inline extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/KubernetesCommonHelper.java:228]: Topic for discussion: Since, we are slightly changing the way we perceive `arguments` do we expect extension to contribute to the them? It kind of feels that now extensions are expected to only toy with `command`. Thoughts?

Comment (Sgitario) [reply extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/KubernetesCommonHelper.java:228]: For native, extensions still need to provide both the command and the arguments.
But I like what you say which would imply split KubernetesCommandBuildItem in KubernetesCommandBuildItem (only for the command) and KubernetesArgsBuildItem (only for the args).
Are you ok with and do you want me to do it as part of this PR?

Comment (geoand) [reply extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/KubernetesCommonHelper.java:228]: Why do we need to change `KubernetesCommandBuildItem`? I didn't get that part

Comment (iocanel) [reply extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/KubernetesCommonHelper.java:228]: We don't need to change anything.
I am just wondering / thinking out loud.

Do we expect extensions/build items to ever contribute to arguments?

Comment (Sgitario) [reply extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/KubernetesCommonHelper.java:228]: Yes, for Native we need extensions to contribute to the arguments.

Comment (geoand) [reply extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/KubernetesCommonHelper.java:228]: I don't see why the BuildItem now uses arrrays for both the command and args... Seems counterintuitive...

Comment (Sgitario) [reply extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/KubernetesCommonHelper.java:228]: I agree with you, I would change it to only have a single constructor for the command: `KubernetesCommandBuildItem(String ... cmd)` and add a method to set the arguments (as this is now optional for extensions).
Wdyt?

Comment (geoand) [reply extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/KubernetesCommonHelper.java:228]: Makes sense to me

**Comment by geoand** [comment]
When done, please squash the commits

File: extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/KubernetesCommonHelper.java (hunk 1 above)
Comment (Sgitario) [reply extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/KubernetesCommonHelper.java]: I've already refactored the `KubernetesCommandBuildItem`.

**Comment by Sgitario** [comment]
@iocanel I could find the root cause of the failing tests: the problem was caused by registering an args decorator with no args. This is obviously wrong and I've already fixed it.

Would you mind to take another look?

**Comment by geoand** [comment]
Do we really have to use the Maven invoker style of tests?

I know you guys where looking into some issue with the QuarkusProdMode test, what was the result of that investigation? Can the PR be updated to move the tests to that style?

**Comment by Sgitario** [comment]
> Do we really have to use the Maven invoker style of tests?
> 
> I know you guys where looking into some issue with the QuarkusProdMode test, what was the result of that investigation? Can the PR be updated to move the tests to that style?

The issue we were facing was unrelated to QuarkusProdMode and has been already fixed.
Afaik, I don't have any objections to move the scenarios from maven invoker to standard way.
Do you want me to change this?

**Comment by geoand** [comment]
Good to hear.

Yes please move them. I initially developed QuarkusProdModeTest out of frustration with the Maven invoker tests, so I would really like to avoid going back to them 😎

**Comment by Sgitario** [comment]
> Good to hear.
> 
> Yes please move them. I initially developed QuarkusProdModeTest out of frustration with the Maven invoker tests, so I would really like to avoid going back to them

Moved! I think it looks better and simpler now.

**Comment by geoand** [comment]
Great, thanks 👌

**Review by geoand — APPROVED** [review]
LGTM, but I want @iocanel to have the final say

**Comment by geoand** [comment]
There seems to be a memory leak in `QuarkusProdModeTest`... I'll have to investigate.

Sorry for the inconvinience!

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/17956 fixes the issue. Once that is in, please rebase this PR onto `main`

**Comment by geoand** [comment]
All set, can you please rebase?

**Comment by Sgitario** [comment]
> All set, can you please rebase?

Rebased

File: extensions/container-image/container-image-openshift/deployment/src/main/java/io/quarkus/container/image/openshift/deployment/OpenshiftProcessor.java [hunk 2]
```diff
@@ -148,11 +148,12 @@ public void openshiftRequirementsJvm(OpenshiftConfig openshiftConfig,
...
-                List<String> args = new ArrayList<>();
-                args.addAll(config.jvmArguments);
-                args.addAll(Arrays.asList("-jar", pathToJar));
+                List<String> cmd = new ArrayList<>();
+                cmd.add("java");
+                cmd.addAll(config.jvmArguments);
+                cmd.addAll(Arrays.asList("-jar", pathToJar));
                 envProducer.produce(KubernetesEnvBuildItem.createSimpleVar("JAVA_APP_JAR", pathToJar, null));
-                commandProducer.produce(new KubernetesCommandBuildItem("java", args.toArray(new String[args.size()])));
+                commandProducer.produce(new KubernetesCommandBuildItem(cmd.toArray(new String[cmd.size()])));
```
Comment (gastaldi) [inline extensions/container-image/container-image-openshift/deployment/src/main/java/io/quarkus/container/image/openshift/deployment/OpenshiftProcessor.java:156]:
```suggestion
                commandProducer.produce(new KubernetesCommandBuildItem(cmd));
```

Comment (Sgitario) [reply extensions/container-image/container-image-openshift/deployment/src/main/java/io/quarkus/container/image/openshift/deployment/OpenshiftProcessor.java:156]: KubernetesCommandBuildItem requires an Array, not a List.

**Comment by maxandersen** [comment]
if i understand it right this is a breaking change (for good reasons) so should have entry in migration guide, right?

**Comment by geoand** [comment]
Exactly.

@Sgitario can you write something here that we will put in the migration guide?

**Comment by Sgitario** [comment]
> Exactly.
> 
> @Sgitario can you write something here that we will put in the migration guide?

I was figuring out how to add it myself. This is the content that I wrote:

```
### Java command and arguments mapping

When deploying a Quarkus application into OpenShift, by default the container configuration to run the application looked like:

```
command: java
args:
    - '-Dquarkus.http.host=0.0.0.0'
    - '-Djava.util.logging.manager=org.jboss.logmanager.LogManager'
    - '-jar'
    - /deployments/quarkus-run.jar
```

Both `command` and `args` fields can be overriden via the `quarkus.openshift.command` and `quarkus.openshift.arguments` properties. 

However, users can't simple append their custom Java arguments, for example: `java -jar /deployments/quarkus-run.jar param1 param2`. The only workaround was to copy and paste the existing content in the default `args` field and append the custom arguments `param1` and `param2`.

This has been fixed in 2.0 by moving all the Java related parameters into the `command` field:

```
command: 
    - 'java'
    - '-Dquarkus.http.host=0.0.0.0'
    - '-Djava.util.logging.manager=org.jboss.logmanager.LogManager'
    - '-jar'
    - /deployments/quarkus-run.jar
```

Now, users can use the `quarkus.openshift.arguments` property to append their custom Java arguments, for example: `quarkus.openshift.arguments=param1,param2`.
```

wdyt?

File: extensions/container-image/container-image-openshift/deployment/src/main/java/io/quarkus/container/image/openshift/deployment/OpenshiftProcessor.java (hunk 2 above)
Comment (gastaldi) [reply extensions/container-image/container-image-openshift/deployment/src/main/java/io/quarkus/container/image/openshift/deployment/OpenshiftProcessor.java:156]: If the command is converted back to a list internally, why not take a List instead?

Comment (Sgitario) [reply extensions/container-image/container-image-openshift/deployment/src/main/java/io/quarkus/container/image/openshift/deployment/OpenshiftProcessor.java:156]: With array, we have the ability to write commands like ``KubernetesCommandBuildItem(new String[] { "java", "-jar", "jar.jar" })`("java")` or `KubernetesCommandBuildItem("java", "-jar", "jar.jar")` or `KubernetesCommandBuildItem(new String[] { "java", "-jar", "jar.jar" })`. This is how it was originally designed and didn't want to change as it would require to change other parts of the code as well.

We could certainly add a new constructor to accept a list and internally keeping the list instead of an array, but as I said, it would require to change the consumers of the KubernetesCommandBuildItem.

File: extensions/kubernetes/spi/src/main/java/io/quarkus/kubernetes/spi/KubernetesCommandBuildItem.java [hunk 3]
```diff
@@ -1,22 +1,30 @@
...
+import java.util.List;
+
 import io.quarkus.builder.item.SimpleBuildItem;
 
 public final class KubernetesCommandBuildItem extends SimpleBuildItem {
 
-    private final String command;
-    private final String[] args;
+    private final List<String> command;
+    private List<String> args = Collections.emptyList();
```
Comment (gastaldi) [inline extensions/kubernetes/spi/src/main/java/io/quarkus/kubernetes/spi/KubernetesCommandBuildItem.java:12]: Please don't make it non-final. Instead use the constructor, static factory methods or introduce a builder

File: extensions/container-image/container-image-openshift/deployment/src/main/java/io/quarkus/container/image/openshift/deployment/OpenshiftProcessor.java (hunk 2 above)
Comment (gastaldi) [reply extensions/container-image/container-image-openshift/deployment/src/main/java/io/quarkus/container/image/openshift/deployment/OpenshiftProcessor.java:156]: I think it all depends on how it is used right now, really. The existing code seems to use a list for the arguments, so using an array might seem unnecessary here.

Comment (Sgitario) [reply extensions/container-image/container-image-openshift/deployment/src/main/java/io/quarkus/container/image/openshift/deployment/OpenshiftProcessor.java:156]: In other parts, we're using the arrays: https://github.com/quarkusio/quarkus/pull/17889/files#diff-c15bcfcc919c2e97bb2cb66a3a836eb0537fbfb3a3fcfbd3373ad5df09749b63R206

File: extensions/kubernetes/spi/src/main/java/io/quarkus/kubernetes/spi/KubernetesCommandBuildItem.java (hunk 3 above)
Comment (Sgitario) [reply extensions/kubernetes/spi/src/main/java/io/quarkus/kubernetes/spi/KubernetesCommandBuildItem.java]: Changed. 
I've created a few factory methods.
Let me know what you think now.

File: extensions/container-image/container-image-openshift/deployment/src/main/java/io/quarkus/container/image/openshift/deployment/OpenshiftProcessor.java (hunk 2 above)
Comment (Sgitario) [reply extensions/container-image/container-image-openshift/deployment/src/main/java/io/quarkus/container/image/openshift/deployment/OpenshiftProcessor.java]: I've introduced a few factory methods in KubernetesCommandBuildItem to use either a command of array, or a list, or a combination of a command and arguments.
Let me know how looks like now.

**Review by gastaldi — APPROVED** [review]
LGTM

**Comment by gsmet** [comment]
@iocanel can you check this and give us your blessing?

@geoand looks like something we would want for 2.0 or not?

**Comment by geoand** [comment]
> @geoand looks like something we would want for 2.0 or not?

We could, although I don't think anyone will fall in despair if we don't :)

**Comment by gsmet** [comment]
@iocanel ping?

**Comment by geoand** [comment]
Where are we on this one?

**Comment by gsmet** [comment]
Merging after discussion with @geoand . Thanks @Sgitario .
