### PR TITLE
Register jaxb.index as native resource

### LINKED ISSUE #48059: jaxb.index not registered through quarkus-jaxb
### Describe the bug

I have an application that contains a `org/acme/jaxb.index` and a jaxb annotated `org.acme.Employee` class , and some code that relies on it when creating a context:
```
JAXBContext ctx = JAXBContext.newInstance("org.acme");
```
this is working in jvm mode, but fails in native because the file is not registered.
in native there will be an error saying that a `jaxb.index` or `ObjectFactory`  class are expected.

### Expected behavior

there should be a consistent behavior between jvm and native modes.
we should be able to register automatically `jaxb.index` either in the main module itself, or one of its dependencies.

### Actual behavior

```
jakarta.xml.bind.JAXBException: "org.acme" doesnt contain ObjectFactory.class or jaxb.index
	at org.glassfish.jaxb.runtime.v2.ContextFactory.createContext(ContextFactory.java:241)
	at org.glassfish.jaxb.runtime.v2.JAXBContextFactory.createContext(JAXBContextFactory.java:58)
	at jakarta.xml.bind.ContextFinder.find(ContextFinder.java:322)
	at jakarta.xml.bind.JAXBContext.newInstance(JAXBContext.java:392)
```

### How to Reproduce?

create an application with extension `quarkus-jaxb`
add `src/main/resources/jaxb.index` with content:
```
Employee
```
create class `org.acme.Employee` with:
```
package org.acme;

import jakarta.xml.bind.annotation.*;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "employeeType", namespace = "org.acme", propOrder = { "name", "age" })
@XmlRootElement(name = "employee", namespace = "org.acme")
public class Employee {

    @XmlElement(required = true)
    protected String name;

    protected int age;

    public String getName() {
        return name;
    }

    public void setName(String value) {
        this.name = value;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int value) {
        this.age = value;
    }
}
```

create endpoint:
```
    @GET
    @Path("/jaxb")
    @Produces(MediaType.TEXT_PLAIN)
    public String jaxb() throws JAXBException {
        JAXBContext ctx = JAXBContext.newInstance("org.acme");
        return ctx.toString();
    }
```

and test:
```
    @Test
    void testJaxbEndpoint() {
        given()
                .when().get("/hello/jaxb")
                .then()
                .statusCode(200)
                .body(containsString("Classes known to this context"));
    }
```

the same test in native will fail.

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Mandrel or GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

3.22

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

I was able to fix it with this additional code in one of our extensions:
```
    @BuildStep(onlyIf = NativeOrNativeSourcesBuild.class)
    void jaxb(final CurateOutcomeBuildItem outcome,
            final BuildProducer<ReflectiveClassBuildItem> reflective, // do not remove
            final BuildProducer<NativeImageResourcePatternsBuildItem> resource) {

        if (hasDependency(outcome, "io.quarkus", "quarkus-jaxb")) {
            Log.info("detected quarkus-jaxb dependency, adding native image resources for jaxb.index");
            resource.produce(NativeImageResourcePatternsBuildItem.builder().includePattern(".*/jaxb.index$").build());
        }
    }

    private boolean hasDependency(final CurateOutcomeBuildItem outcome, String groupId, String artifactId) {
        return outcome.getApplicationModel().getDependencies().stream()
                .anyMatch(resolvedDependency -> groupId.equals(resolvedDependency.getGroupId())
                        && artifactId.equals(resolvedDependency.getArtifactId()));
    }
```

although functional, the code could probably be more efficient?
as a note side, if I did not include the `reflective` argument, then we do not enter into the build step??

I looked at the [jaxb processor](https://github.com/quarkusio/quarkus/blob/83e6e85786b3c0d8aad4007749587fd61f11cbd1/extensions/jaxb/deployment/src/main/java/io/quarkus/jaxb/deployment/JaxbProcessor.java#L397-L427). it has some code already to do some logic about jaxb files. but in my use case I never enter those methods because `fileRoots` is empty.
and I do not see anybody creating `JaxbFileRootBuildItem` objects.

see also https://quarkusio.zulipchat.com/#narrow/channel/187030-users/topic/jaxb.2Eindex.20not.20registered.20in.20native

### PR DESCRIPTION
**Pull request by vsevel**
- Closes: https://github.com/quarkusio/quarkus/issues/48059

### CODE REVIEW

File: extensions/jaxb/deployment/src/main/java/io/quarkus/jaxb/deployment/JaxbProcessor.java [hunk 1]
```diff
@@ -70,18 +70,12 @@
...
-import io.quarkus.deployment.builditem.nativeimage.NativeImageProxyDefinitionBuildItem;
-import io.quarkus.deployment.builditem.nativeimage.NativeImageResourceBuildItem;
-import io.quarkus.deployment.builditem.nativeimage.NativeImageResourceBundleBuildItem;
-import io.quarkus.deployment.builditem.nativeimage.NativeImageSystemPropertyBuildItem;
-import io.quarkus.deployment.builditem.nativeimage.ReflectiveClassBuildItem;
-import io.quarkus.deployment.builditem.nativeimage.ReflectiveHierarchyBuildItem;
-import io.quarkus.deployment.builditem.nativeimage.ReflectiveHierarchyIgnoreWarningBuildItem;
-import io.quarkus.deployment.builditem.nativeimage.RuntimeInitializedClassBuildItem;
-import io.quarkus.deployment.builditem.nativeimage.ServiceProviderBuildItem;
+import io.quarkus.deployment.builditem.nativeimage.*;
```
Comment (geoand) [inline extensions/jaxb/deployment/src/main/java/io/quarkus/jaxb/deployment/JaxbProcessor.java]: Let's please avoid star imports. I know the IDE likes to do this automatically, but we still try to avoid them

File: extensions/jaxb/deployment/src/main/java/io/quarkus/jaxb/deployment/JaxbProcessor.java [hunk 2]
```diff
@@ -70,18 +70,12 @@
...
+import io.quarkus.deployment.pkg.steps.NativeOrNativeSourcesBuild;
 import io.quarkus.jaxb.runtime.JaxbConfig;
 import io.quarkus.jaxb.runtime.JaxbContextConfigRecorder;
 import io.quarkus.jaxb.runtime.JaxbContextProducer;
+import io.quarkus.logging.Log;
```
Comment (geoand) [inline extensions/jaxb/deployment/src/main/java/io/quarkus/jaxb/deployment/JaxbProcessor.java]: This won't properly in build time code

**Review by geoand — APPROVED** [review]
Thanks!

**Review by gsmet — APPROVED** [review]
