### PR TITLE
Work around missing GraalVM internal version starting with JDK 22

### LINKED ISSUE #36246: Quarkus main fails to parse GraalVM version starting with GraalVM for JDK 22
### Describe the bug

It looks like labsJDK 22 dropped the "old" GraalVM versioning (e.g., `23.1`) from its version:

```
❯ ~/jvms/labsjdk-ce-latest-22+13-jvmci-b01/bin/java -version 
openjdk version "22" 2024-03-19
OpenJDK Runtime Environment (build 22+13-jvmci-b01)
OpenJDK 64-Bit Server VM (build 22+13-jvmci-b01, mixed mode, sharing)

❯ ~/jvms/labsjdk-ce-21-jvmci-23.1-b15/bin/java -version
openjdk version "21" 2023-09-19
OpenJDK Runtime Environment (build 21+35-jvmci-23.1-b15)
OpenJDK 64-Bit Server VM (build 21+35-jvmci-23.1-b15, mixed mode, sharing)
```

As a result, Quarkus fails to detect the version of GraalVM builds based on LabsJDK 22 onwards.

### Expected behavior

Quarkus should detect the version and not crash.

### Actual behavior

Quarkus fails to detect the version and crashes.

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

Relates to https://github.com/quarkusio/quarkus/issues/34161

Possible fixes:

1. Rely on getting the value from the `release` file that accompanies the GraalVM build as discussed in https://github.com/quarkusio/quarkus/issues/34161#issue-1765317362
2. Switch to using the new versioning scheme

### PR DESCRIPTION
**Pull request by zakkak**
Work around missing graalvm internal version starting with JDK 22

1. Temporarily works around https://github.com/quarkusio/quarkus/issues/36246, till we have a consensus on how to move forward in https://github.com/quarkusio/quarkus/issues/34161
2. Improves log messages about GraalVM version detection
    1. Avoid null pointer exceptions and properly report version parsing failure
    2. Print the parsed version instead of the `native-image --version` output when printing the version being used
3. Adds new tests

Closes https://github.com/quarkusio/quarkus/issues/36246
Depends on https://github.com/quarkusio/quarkus/pull/36260 (otherwise the tests fail)

cc @jerboaa

### CODE REVIEW

**Review by jerboaa — APPROVED** [review]
Yes, please. This at least gets us moving again with 24.0 (JDK 22 based builds).

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/GraalVM.java [hunk 1]
```diff
@@ -109,10 +116,23 @@ private static String graalVersion(String buildInfo) {
...
+                return matchVersion(version);
+            } else {
+                return GRAAL_MAPPING.get(jdkFeature);
+            }
         }
     }
 
+    // Temporarily work around https://github.com/quarkusio/quarkus/issues/36246,
+    // till we have a consensus on how to move forward in
+    // https://github.com/quarkusio/quarkus/issues/34161
```
Comment (gsmet) [inline core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/GraalVM.java:130]: OK, I suppose we can live with this workaround for a short time but let's make progress on this issue please and decide something viable for the future.

**Review by gsmet — APPROVED** [review]

**Comment by zakkak** [comment]
CI failures seem irrelevant to me.

**Comment by gsmet** [comment]
Yeah :/ It's exhausing how CI can be unreliable these days with weird failures popping far too often :/
