### PR TITLE
RESTEasy Reactive - prevent repeating of standard security checks

### LINKED ISSUE #26536: RestEasy Reactive performs authorization checks twice
### Description

(I am filing this issue as an enhancement, because it isn't really a bug, but I suspect that performing the authorization twice isn't the desired behavior either.)

When using RestEasy Reactive the authorization checks will be performed twice: Once using RestEasy Reactive's own `EagerSecurityHandler` (registered as a `ServerRestHandler`) and once by the curresponding CDI interceptor (e.g. `RolesAllowedInterceptor`) provided by `quarkus-security`. It would seem like it would make sense to only perform the check once, as with RestEasy Classic.

I stumbled across this while migrating to RestEasy Reactive, since we also use the CDI interceptor approach for some custom security logging. With RestEasy Reactive this mechanism no longer works in the "negative" case (when the authorization check fails), since the check performed by RestEasy Reactive will short-circuit the handling. As an alternative for the negative case I can however use an `ExceptionMapper` instead.

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by michalvavrik**
fix: #26536

`EagerSecurityHandler` performs standard security checks for endpoints annotated with an RBAC annotation and the same checks are later done by `SecurityHandler`. We still need interceptors to run for CDI beans and gRPC. This PR prevents repeating of security checks by propagating the information that check is done to `SecurityHandler` via invocation context.

### CODE REVIEW

**Comment by michalvavrik** [comment]
cc @sberyozkin @geoand

**Comment by geoand** [comment]
Thanks for this!

CI seems unhappy however :)

**Comment by michalvavrik** [comment]
My point is that the check can only be removed on "method invocation" scope, not request scope as you need nested CDI beans to be able to perform its own (different checks) within same request.

**Comment by sberyozkin** [comment]
Hey @michalvavrik the last thing that should be of concern is some code in PR can make me less excited :-), you keep creating good quality PRs I may not be even getting from the first round of review :-).
But IMHO, if tweaking around `io.quarkus.arc.processor.BeanInfo#initInterceptedMethods` can disable those CDI interceptors then it would be preferred; have a look please when you get a chance, I guess we should not rush with merging it asap, so please tale your time
thanks

**Comment by michalvavrik** [comment]
@sberyozkin ready for review

**Comment by michalvavrik** [comment]
Sure, conflict resolved.

**Review by sberyozkin — APPROVED** [review]
@michalvavrik I think this is a very nicely researched and done PR.

However, I think we need to get at least one more review as there might be some details that I've missed.

Thanks

**Comment by sberyozkin** [comment]
@mkouba Hi Martin, can you please have a look at the Arc related code in this PR when you are get a chance ?

**Comment by sberyozkin** [comment]
@geoand Have a look please when you get a chance :-), I agree it is a much more complex solution compared to the original approach of passing the flags, but the complexity is isolated to the build time and is really about neatly disabling the duplicating interceptors, so in the end it is only the eager security checks which are done

**Comment by geoand** [comment]
I'm out until further notice. 

Furthermore my backlog has grown pretty large, so I can't promise when I'll get to this.

**Comment by geoand** [comment]
This definitely needs a review from @mkouba for the Arc parts as I am not 100% what is introduced is something we want

**Comment by mkouba** [comment]
@michalvavrik @sberyozkin @geoand I haven't had time to look into the details yet but is the `InterceptedMethodBindingFilter`  about ignoring an interceptor binding annotation instance? If so would an annotation transformer be a solution?

**Comment by geoand** [comment]
> If so would an annotation transformer be a solution?

+1

**Comment by michalvavrik** [comment]
but we should keep the annotation in place as the developers will count on it. what if they will bind their own interceptors to it. It's dodgy. Or did I misunderstood you @mkouba ?

**Comment by mkouba** [comment]
> but we should keep the annotation in place as the developers will count on it. what if they will bind their own interceptors to it. It's dodgy. Or did I misunderstood you @mkouba ?

I'm sorry but I don't understand. If you ignore the annotation like this then no CDI interceptors are associated. Could you be more specific? An example would be helpful. Also I'm sorry for my ignorance because I may be missing some context mentioned somewhere in this PR.

**Comment by michalvavrik** [comment]
In short - 
annotation transformer solution: one annotation instance - possibly many interceptors -> you remove it -> you loose all the bindings
this pr: one annotation instance - possibly many interceptor -> you apply `filter` -> you loose the binding between an annotation instance and the method (so all other bindings are still intercepted). I only implemented what I really need so non-static invocation interceptions of methods)

**Comment by michalvavrik** [comment]
there is the test from which the behavior should be clear - `MethodInterceptorBindingFilterTest`

**Comment by mkouba** [comment]
Ok, I get the idea but I really don't get why it's needed. I mean why do we need to keep the annotations anyway? Also I don't think it's very likely that some other interceptors use the same bindings (although it's theoretially possible ;-).

**Comment by geoand** [comment]
> I mean why do we need to keep the annotations anyway

+1

**Comment by michalvavrik** [comment]
I think this solution was isolated to repeated checks while other assumes we know what developers do (it could be breaking change theoretically, right?).

I accept that you agreed it's not necessary to keep the annotation and will rewrite the PR. Thanks for the review.

**Comment by sberyozkin** [comment]
@knutwannheden Can you please check the last few comments from @michalvavrik and @mkouba and clarify if needed ? I think you typed it all in #26536 but it might help to get some context here as well

File: extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/ResteasyReactiveProcessor.java [hunk 1]
```diff
@@ -1061,6 +1068,96 @@ public List<HandlerChainCustomizer> scan(MethodInfo method, ClassInfo actualEndp
...
+            return null;
+        }
+
+        final Predicate<AnnotationInstance> isSecurityAnnotation = new Predicate<AnnotationInstance>() {
+            @Override
+            public boolean test(AnnotationInstance annotationInstance) {
+                return SecurityTransformerUtils.SECURITY_BINDINGS.contains(annotationInstance.name());
+            }
+        };
+        // remove security annotations
```
Comment (sberyozkin) [inline extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/ResteasyReactiveProcessor.java:1135]: @michalvavrik Hi, one thing I'd like to clarify, can it affect the custom interceptors (not those provided by `quarkus-security` but the ones added by the users) ?

Comment (michalvavrik) [reply extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/ResteasyReactiveProcessor.java:1135]: @sberyozkin absolutely! However Martin and Georgios thinks it's unlikely anyone is binding custom interceptors to security  annotations.

Comment (michalvavrik) [reply extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/ResteasyReactiveProcessor.java:1135]: it at least that's how I understood our communication above, please see previous comments.

Comment (geoand) [reply extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/ResteasyReactiveProcessor.java:1135]: I'll need to review this thorougly

File: independent-projects/resteasy-reactive/common/processor/src/main/java/org/jboss/resteasy/reactive/common/processor/EndpointIndexer.java [hunk 2]
```diff
@@ -469,7 +475,65 @@ private void validateHttpAnnotations(MethodInfo info) {
         }
     }
 
-    private boolean hasProperModifiers(MethodInfo info) {
+    public static Set<MethodInfo> findEndpoints(ResourceScanningResult scanningResult, IndexView index,
```
Comment (geoand) [inline independent-projects/resteasy-reactive/common/processor/src/main/java/org/jboss/resteasy/reactive/common/processor/EndpointIndexer.java:478]: Where has the logic for this method come from?

Comment (michalvavrik) [reply independent-projects/resteasy-reactive/common/processor/src/main/java/org/jboss/resteasy/reactive/common/processor/EndpointIndexer.java:478]: I derived it from `org.jboss.resteasy.reactive.common.processor.EndpointIndexer#createEndpoints(org.jboss.jandex.ClassInfo, boolean)` as to keep firm link between checks performed by `EagerSecurityHandler` I need to have exactly same endpoints https://github.com/quarkusio/quarkus/blob/main/extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/ResteasyReactiveProcessor.java#L584

Comment (michalvavrik) [reply independent-projects/resteasy-reactive/common/processor/src/main/java/org/jboss/resteasy/reactive/common/processor/EndpointIndexer.java:478]: btw it does not use annotation store as AFAIK you can't consume annotationtransformations and produce it due to circular dependency

Comment (geoand) [reply independent-projects/resteasy-reactive/common/processor/src/main/java/org/jboss/resteasy/reactive/common/processor/EndpointIndexer.java:478]: > I derived it from `org.jboss.resteasy.reactive.common.processor.EndpointIndexer#createEndpoints(org.jboss.jandex.ClassInfo, boolean)` as to keep firm link between checks performed by `EagerSecurityHandler` I need to have exactly same endpoints https://github.com/quarkusio/quarkus/blob/main/extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/ResteasyReactiveProcessor.java#L584

So we have a duplication in how endpoints are looked up?

Comment (michalvavrik) [reply independent-projects/resteasy-reactive/common/processor/src/main/java/org/jboss/resteasy/reactive/common/processor/EndpointIndexer.java:478]: Yes. `createEndpoints` does combine look up/validation/creation of `org.jboss.resteasy.reactive.common.model.ResourceClass`. I am happy to separate look up, but please bear in mind it will require bigger changes to `createEndpoints`. Should I do it?

Comment (geoand) [reply independent-projects/resteasy-reactive/common/processor/src/main/java/org/jboss/resteasy/reactive/common/processor/EndpointIndexer.java:478]: Let me look at this closer and let you know.

File: extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/ResteasyReactiveProcessor.java (hunk 1 above)
Comment (sberyozkin) [reply extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/ResteasyReactiveProcessor.java:1135]: Hmm, it sounds like it can be a breaking change. @knutwannheden in #26536's description refers to a custom interceptor doing the security logging, but I don't know how it is bound. But it feels a bit risky.

So re your earlier comment: 
```
In short -
annotation transformer solution: one annotation instance - possibly many interceptors -> you remove it -> you loose all the bindings
this pr: one annotation instance - possibly many interceptor -> you apply filter -> you loose the binding between an interceptor and the method (so all other bindings are still intercepted). I only implemented what I really need so non-static invocation interceptions of methods)
```
I think your original solution should've stayed, it was hard for me to suggest something useful as the Arc code was quite complex, but if that complexity was needed to support the custom interceptors then it should be preferred IMHO.

However lets wait for more comments.

**Comment by knutwannheden** [comment]
@sberyozkin Yes, we do in fact register a custom interceptor against the authorization annotations. The purpose is to perform custom security logging both for successful and failed security checks. If another mechanism were available, we would however be happy to use that instead, as the failed authorization logging currently only works with RestEasy Classic anyway. (There is also a few other drawbacks to the CDI interceptor approach.) But it would be unfortunate if this refactoring means that there is no way to implement the security logging anymore.

**Comment by michalvavrik** [comment]
@mkouba @geoand could you please have a look at @knutwannheden comment and consider the arc method interceptor filter again? I need confirmation or instructions what's next as I have already provided 3 possible solutions and it doesn't make sense to make any other adjustments till there is an agreement on solution. Thank you

**Comment by geoand** [comment]
Absolutely understood. I'll have a look tomorrow

**Comment by geoand** [comment]
So if I understand correctly what @knutwannheden is saying, is that they use the same security annotations and provide additional interceptors for them, meaning that if we go through with this in the current form, their integration will stop working?

**Comment by michalvavrik** [comment]
Yes, that's my understanding.

**Comment by geoand** [comment]
@knutwannheden can you confirm?

**Comment by mkouba** [comment]
> @mkouba @geoand could you please have a look at @knutwannheden comment and consider the arc method interceptor filter again? I need confirmation or instructions what's next as I have already provided 3 possible solutions and it doesn't make sense to make any other adjustments till there is an agreement on solution. Thank you

I don't like this idea of "method interceptor filter" very much. It feels a little bit "hacky" and may lead to unexpected surprises (from user POV, e.g. _"why is one interceptor associated and the other one not?"_). On the other hand, I do understand that we need to find a solution for this problem. @manovotn @Ladicek WDYT?

**Comment by geoand** [comment]
Agreed, it looks like it's problematic

**Comment by sberyozkin** [comment]
Hi All, would it make sense to revert to the original solution from Michal which Georgios also liked ? My concerns with that solution was that it was a workaround with having to pass flags to stop one set of the interceptors duplicating what RestEasy Reactive eager checks have already done but perhaps, after 2 more iterations from Michal, it proves the original approach was best simply it was the simplest one ? 
Unfortunately the approach with fixing it `cleanly` at the build time proves to be quite complex, lets see if the CDI experts here can suggest something else; apologies in advance if Michal you will end up with your first solution :-), I think it was worth a try though...

thanks

**Comment by Ladicek** [comment]
I personally don't like the concept of "interceptor binding filtering", as it seems too easy to misuse, but I didn't see the code, so my hesitation is really quite a bit uninformed.

That said, let me draw a parallel with a very similar problem I'm facing with SmallRye Fault Tolerance (#21431). If a JAX-RS resource method is annotated `@Blocking` and e.g. `@CircuitBreaker`, then _both_ RESTEasy Reactive and SmallRye Fault Tolerance will notice the `@Blocking` annotation and offload the method call to another thread. Essentially the same situation -- 1 annotation used by 2 frameworks that don't know about each other and can't easily communicate out of band. There's one more thing these two situations have in common -- the double behavior (be it double security check, or double thread offload) isn't really problematic in essence (as in, it doesn't cause bugs), it's just useless work (which should obviously be avoided).

It makes me wonder: is there an easy way to figure out if an intercepted method is a JAX-RS resource method? An interceptor (be it the security interceptor, or the fault tolerance interceptor) could adjust its behavior based on that. I _think_ resource methods always have to have the HTTP verb annotation (`@GET` etc.), no? There's a fixed set of those annotations, and all other HTTP verb annotations must have one meta-annotation (whose name I can't remember). Right? (Not sure how subresource locators fit into this...) Would _that_ make sense?

**Comment by geoand** [comment]
I like the idea @Ladicek, but I am wondering if we can make it a little more general.
My thinking is that each framework (in this case JAX-RS) knows about itself, so maybe it could push information into the CDI execution context in order to identify itself?

**Comment by Ladicek** [comment]
That would be great, I also thought about that a little -- problem is that the invocation context starts to exist only when the method in question is actually invoked. So at the point when RESTEasy Reactive does the security check, there's no shared storage for that information. A request-scoped bean might work, but it would bring a hard dependency on context propagation.

What I can imagine is ArC exposing an API for invoking a method and adding some contextual information to the invocation context.

I guess RESTEasy Reactive currently has to have some cone that invokes the resource method. I don't know how it looks, but if the invocation is reflective, there must be something like this: `method.invoke(instance, params)`. It could probably look like this instead:

```java
Map<String, Object> data = Map.of("resteasy.reactive.resource.method", Boolean.TRUE);
Arc.container().runWithInterceptionContext(() -> method.invoke(instance, params), data);
```

(It would probably be a bit more complex, but you get the idea...)

**Comment by geoand** [comment]
The invocation in RR is not reflective, it's generated code, so we can do whatever we like in there :)

**Comment by Ladicek** [comment]
Right, gotcha.

The API I suggest above still requires some form of out-of-band communication, but that would now have a very short lifespan, so a thread local variable should be fine. It would still be quite a bit unsafe. Maybe @mkouba can think of something better/safer, but I _think_ the approach should work.

**Comment by geoand** [comment]
👍🏼

**Comment by Ladicek** [comment]
I just realized that the concept of "executable methods", which we unfortunately failed to explore in the CDI 4.0 timeframe (see https://github.com/jakartaee/cdi/issues/460), would be a perfect fit for this. If we had that, it would likely be straightforward to extend to support extending the context data map. Oh well.

**Comment by michalvavrik** [comment]
@mkouba that was my solution number one (it's already implemented), as long as other agrees, we could use interceptor solution for now.

**Comment by geoand** [comment]
Fine with me

**Comment by michalvavrik** [comment]
Done.

File: extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityHandler.java [hunk 3]
```diff
@@ -16,9 +19,6 @@
 @Singleton
 public class SecurityHandler {
 
-    private static final String HANDLER_NAME = SecurityHandler.class.getName();
-    private static final String EXECUTED = "executed";
```
Comment (geoand) [inline extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityHandler.java:20]: Shouldn't these be replaced by the constants in `SecurityHandlerConstants`?

**Review by geoand — COMMENTED** [review]
I added a minor comment, but otherwise this is a good with me!

@sberyozkin, @mkouba mind taking a look as well?

File: extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityHandler.java (hunk 3 above)
Comment (michalvavrik) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityHandler.java:20]: Sorry, I can't comprehend - SecurityHandler constants have been moved to SecurityHandlerConstants as we to access them from RR (would come with alternative mechanism like 'anything with xy there...', but this looks more reliable). RR set these constants to prevent the check. Can you explain in more detail how you mean it?

Comment (geoand) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityHandler.java:20]: Aren't these same constants defined in `io.quarkus.security.spi.runtime.SecurityHandlerConstants`?

Comment (michalvavrik) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityHandler.java:20]: Exactly, that's why they are already removed from SecurityHandler (it has red background). I'll need a little more, sorry.

Comment (geoand) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityHandler.java:20]: Nevermind, reviewing from the IDE tricked me...

Comment (michalvavrik) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityHandler.java:20]: np

File: extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/SecurityHandlerConstants.java [hunk 4]
```diff
@@ -0,0 +1,15 @@
+package io.quarkus.security.spi.runtime;
+
+public class SecurityHandlerConstants {
+
+    /**
+     * Invocation context data key used by the SecurityHandler to save a security checks state
+     */
+    public static final String SECURITY_HANDLER = "SECURITY_HANDLER";
```
Comment (mkouba) [inline extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/SecurityHandlerConstants.java:8]: The PR looks good but I wonder if the `SECURITY_HANDLER` constant is "unique enough". Usually it's good to use a package prefix so that it's immediately clear where the binding comes from, i.e. `io.quarkus.security.securityHandler`...

Comment (michalvavrik) [reply extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/SecurityHandlerConstants.java]: Your example is way better than `SECURITY_HANDLER`, I used it, thank you.

**Comment by mkouba** [comment]
> I added a minor comment, but otherwise this is a good with me!
> 
> @sberyozkin, @mkouba mind taking a look as well?

I've added a minor comment too and it's already addressed ;-). So let's wait for Sergey?

**Comment by gsmet** [comment]
General comment but I see a lot of you here so it's in good hands: we should be extremely careful given we are changing a behavior related to security. Better check things three times to make sure we are all good.

**Comment by mkouba** [comment]
> General comment but I see a lot of you here so it's in good hands: we should be extremely careful given we are changing a behavior related to security. Better check things three times to make sure we are all good.

That's the reason why we wait for Sergey's opinion as well.

**Comment by michalvavrik** [comment]
ping @sberyozkin

**Comment by sberyozkin** [comment]
Hi All, apologies for keeping you waiting, was back on Mon but missed this one. So it is back to the original solution, which is fine, it is the easiest to understand. 
@michalvavrik sorry you've had to do so many iterations :-), but as I said IMHO it was worth a try, as some very interesting comments were added, and Ladislav has identified what may prove to be the perfect solution once CDI `executable methods` are available, so there is a chance we can revisit this solution in the future :-)
