### PR TITLE
Oidc Code Flow options for SPA's

### LINKED ISSUE #10185: CORS Error when Keycloak Token Timesout
**Describe the bug**
If you enable OIDC Support with Keycloak calls to REST-APIs start to fail once the Token provided by Keycloak is timed out with an CORS-Failure like this:

```
Access to XMLHttpRequest at 'http://localhost:8081/auth/realms/keycloak-cors-public/protocol/openid-connect/auth?redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fhello&state=ba3be67d-a18b-4c6f-acb9-6e617c05674e&scope=openid&response_type=code&client_id=quarkus' (redirected from 'http://localhost:8080/hello') from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

GET http://localhost:8081/auth/realms/keycloak-cors-public/protocol/openid-connect/auth?redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fhello&state=ba3be67d-a18b-4c6f-acb9-6e617c05674e&scope=openid&response_type=code&client_id=quarkus net::ERR_FAILED

Uncaught (in promise) Error: Network Error
    at e.exports (spread.js:25)
    at XMLHttpRequest.l.onerror (spread.js:25)
```

**Expected behavior**
The timeout of the token should not lead to an error

**Actual behavior**
CORS Error produced 

**To Reproduce**
Clone https://github.com/tomsontom/keycloak-cors/ and follow the steps there

**Configuration**
```properties
quarkus.oidc.auth-server-url=${AUTH_URL}
quarkus.oidc.client-id=quarkus
quarkus.oidc.credentials.secret=${AUTH_CREDENTIALS}
quarkus.oidc.application-type=web-app
quarkus.http.auth.permission.authenticated.paths=/*
quarkus.http.auth.permission.authenticated.policy=authenticated
```

**Screenshots**
Bildschirmfoto 2020-06-23 um 11 23 08

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin Toms-MacBook-Pro.local 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64
 - Output of `java -version`:  openjdk version "11.0.6" 2020-01-14
 - GraalVM version (if different from Java): -
 - Quarkus version or git rev: 1.5.2.final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 3.6.3

**Additional context**

**Working request/response look like this:**

*General:*
```
Request URL: http://localhost:8080/hello
Request Method: GET
Status Code: 200 OK
Remote Address: [::1]:8080
Referrer Policy: no-referrer-when-downgrade
```
*Response Headers:*
```
Content-Length: 5
Content-Type: text/plain;charset=UTF-8
```
*Request Headers:*
```
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7
Connection: keep-alive
Cookie: q_session=eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJLSjBBcjZrUnFyWEFYajNlVmdGMFk2MUp4aEt4V2NWU1lDUE5HVHJMNFBVIn0.eyJqdGkiOiI3ODAxYjMzYS1hMDlmLTRhNTktYWY4Mi03NmY1MzNiNzA1OGMiLCJleHAiOjE1OTI5MDMxNzEsIm5iZiI6MCwiaWF0IjoxNTkyOTAzMTExLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODEvYXV0aC9yZWFsbXMva2V5Y2xvYWstY29ycy1wdWJsaWMiLCJhdWQiOiJxdWFya3VzIiwic3ViIjoiNmFhYmU4YmEtYmFjNy00OTdjLTljMzItYWIwYjlkYmM2NzFlIiwidHlwIjoiSUQiLCJhenAiOiJxdWFya3VzIiwiYXV0aF90aW1lIjoxNTkyOTAzMTExLCJzZXNzaW9uX3N0YXRlIjoiN2UyZTYzMzktMDYzOS00YmY5LWExYmEtMzQ4ZDRkODIxMGRlIiwiYWNyIjoiMSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwicHJlZmVycmVkX3VzZXJuYW1lIjoidGVzdCJ9.FkVV5YkOkFgrRU6I_xGTAJmlJdrNj5NbCrR8_kNYvzScVFTyQcE0W1F7b7NnokWTfZjE-PWvNtG602djiihaS00y5TYHh5mCVHNVUzVyG85A0VJovuxvrlfCLnxu0w8WSF4E3KC5twgD_Zf3YAkPpi1t-PXi9B4mSLC0GwOcvtdanW6Ul72evwk_TVeeZBzLDyEApiFuZkZ2MK5kuxV7M2W6_4CJntXA18dpGMoTZ2Ue3wVFOzalk2u2J96jFT3OtbIj9oRMVju-9fy8l1Lks88dQnzAI-x9BSk787yT8IVgA-VCeo5zAERcjBe8LPnJUD4MfrrS2Cj0vCIvCga6mg|eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJLSjBBcjZrUnFyWEFYajNlVmdGMFk2MUp4aEt4V2NWU1lDUE5HVHJMNFBVIn0.eyJqdGkiOiI4MDc2NjYwNi00OTU2LTQ5YzYtYWFhYS0yMDIxNDA4N2Q0NTUiLCJleHAiOjE1OTI5MDMxNzEsIm5iZiI6MCwiaWF0IjoxNTkyOTAzMTExLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODEvYXV0aC9yZWFsbXMva2V5Y2xvYWstY29ycy1wdWJsaWMiLCJhdWQiOiJhY2NvdW50Iiwic3ViIjoiNmFhYmU4YmEtYmFjNy00OTdjLTljMzItYWIwYjlkYmM2NzFlIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoicXVhcmt1cyIsImF1dGhfdGltZSI6MTU5MjkwMzExMSwic2Vzc2lvbl9zdGF0ZSI6IjdlMmU2MzM5LTA2MzktNGJmOS1hMWJhLTM0OGQ0ZDgyMTBkZSIsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiaHR0cDovL2xvY2FsaG9zdDo4MDgwIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJvcGVuaWQgZW1haWwgcHJvZmlsZSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwicHJlZmVycmVkX3VzZXJuYW1lIjoidGVzdCJ9.YSIQeitfiVHTN6pvfud-oW4sncfU_2NgWssAKmAYlKgOFzJyyTKbPyXCljRL3Smm-pSz0tlnVXIps-Qb6NihV7yJUr1fCn9z5AnqhNl9PQSRJ6VAJDmKyLbgtu81GNQ3vg_pYF94dmqpTzvoBLaa5OPOGACmpesCKUvUyGlTG1HPFfNsgfc-6-p2ozj-XVbPYanLFDFWliuFPv6TrhEg3SP4vyySVPltBk9-BgIGn8sCncb7m5ox0DXCzBlFQ-oaVbO9htbp5HIXFWUbYE5yfBEHnmHGFIaJIlO8YtYv9_t3YrKJwQkgP19Ej7MOZNCeQA8grYMlpbjN3YylPnDKSQ|eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJiZDdkYjg5Yy00NWJkLTQ1MDktODFkMi1lN2IxYjMxYjBhNDYifQ.eyJqdGkiOiI5NTQxY2U5My04MDlkLTRjNjQtODVjMy00ZWZmN2Q3YTg2YzgiLCJleHAiOjE1OTI5MDQ5MTEsIm5iZiI6MCwiaWF0IjoxNTkyOTAzMTExLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODEvYXV0aC9yZWFsbXMva2V5Y2xvYWstY29ycy1wdWJsaWMiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjgwODEvYXV0aC9yZWFsbXMva2V5Y2xvYWstY29ycy1wdWJsaWMiLCJzdWIiOiI2YWFiZThiYS1iYWM3LTQ5N2MtOWMzMi1hYjBiOWRiYzY3MWUiLCJ0eXAiOiJSZWZyZXNoIiwiYXpwIjoicXVhcmt1cyIsImF1dGhfdGltZSI6MCwic2Vzc2lvbl9zdGF0ZSI6IjdlMmU2MzM5LTA2MzktNGJmOS1hMWJhLTM0OGQ0ZDgyMTBkZSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJvcGVuaWQgZW1haWwgcHJvZmlsZSJ9.gOCSVyXETE24TJntdbLByVcKLFSOWIonQ5MXO9zuMFs
Host: localhost:8080
Referer: http://localhost:8080/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36
```

**Failing request/response look like this:**

*General:*
```
Request URL: http://localhost:8080/hello
Request Method: GET
Status Code: 302 Found
Remote Address: [::1]:8080
Referrer Policy: no-referrer-when-downgrade
```
*Response Headers:*
```
content-length: 0
location: http://localhost:8081/auth/realms/keycloak-cors-public/protocol/openid-connect/auth?redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fhello&state=ba3be67d-a18b-4c6f-acb9-6e617c05674e&scope=openid&response_type=code&client_id=quarkus
set-cookie: q_auth=ba3be67d-a18b-4c6f-acb9-6e617c05674e; Max-Age=1800; Expires=Tue, 23 Jun 2020 09:36:13 GMT; HTTPOnly
```
*Request Headers:*
```
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7
Connection: keep-alive
Host: localhost:8080
Referer: http://localhost:8080/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36
```

*General:*
```
Request URL: http://localhost:8081/auth/realms/keycloak-cors-public/protocol/openid-connect/auth?redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fhello&state=ba3be67d-a18b-4c6f-acb9-6e617c05674e&scope=openid&response_type=code&client_id=quarkus
Referrer Policy: no-referrer-when-downgrade
```
*Response Headers:*
```
Cache-Control: no-store, must-revalidate, max-age=0
Connection: keep-alive
Content-Language: en
Content-Length: 3089
Content-Security-Policy: frame-src 'self'; frame-ancestors 'self'; object-src 'none';
Content-Type: text/html;charset=utf-8
Date: Tue, 23 Jun 2020 09:06:13 GMT
Set-Cookie: AUTH_SESSION_ID=b2d2fe22-a5ec-4ea7-bcfc-3f248d07ee56.0a08cbc5521a; Version=1; Path=/auth/realms/keycloak-cors-public/; HttpOnly
Set-Cookie: KC_RESTART=eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJiZDdkYjg5Yy00NWJkLTQ1MDktODFkMi1lN2IxYjMxYjBhNDYifQ.eyJjaWQiOiJxdWFya3VzIiwicHR5Ijoib3BlbmlkLWNvbm5lY3QiLCJydXJpIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2hlbGxvIiwiYWN0IjoiQVVUSEVOVElDQVRFIiwibm90ZXMiOnsic2NvcGUiOiJvcGVuaWQiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODEvYXV0aC9yZWFsbXMva2V5Y2xvYWstY29ycy1wdWJsaWMiLCJyZXNwb25zZV90eXBlIjoiY29kZSIsInJlZGlyZWN0X3VyaSI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MC9oZWxsbyIsInN0YXRlIjoiYmEzYmU2N2QtYTE4Yi00YzZmLWFjYjktNmU2MTdjMDU2NzRlIn19.Bj9kuulCAHnH17VjkgpqZUwG21uLObERAOi4rVbtSrE; Version=1; Path=/auth/realms/keycloak-cors-public/; HttpOnly
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Robots-Tag: none
X-XSS-Protection: 1; mode=block
```
*Request Headers:*
```
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7
Connection: keep-alive
Host: localhost:8081
Origin: http://localhost:8080
Referer: http://localhost:8080/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36
```
*Query String Parameters:*
```
redirect_uri: http://localhost:8080/hello
state: ba3be67d-a18b-4c6f-acb9-6e617c05674e
scope: openid
response_type: code
client_id: quarkus
```

### PR DESCRIPTION
**Pull request by boosey**
Fixes #10185

Performing Code Flow OIDC authentication returns redirect status 302 when the user is un-authenticated setting the Auth Server configured in application.properties at the Location header. For Single Page Applications which are making calls to Quarkus REST endpoints as an XHR request, this redirect is automatically followed. However, not all Auth Servers allow XHR requests, so the redirect fails. This change would allow a developer to set a property in application.properties which instructs the Oidc extension to instead return an error code so that the SPA can handle the redirect manually.

### CODE REVIEW

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcTenantConfig.java [hunk 1]
```diff
@@ -533,6 +533,24 @@ public void setRoleClaimSeparator(String roleClaimSeparator) {
         @ConfigItem
         public Optional<String> cookiePath = Optional.empty();
 
+        /**
+         * If this property is set to 'true' then a normal 302 redirect response will be returned. If
+         * the request was initiated via an XMLHttpRequest, then that redirect will automatically be
+         * followed which may not be desiravle for single page applications.
```
Comment (pedroigor) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcTenantConfig.java:539]: typo `desirable`

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/AuthenticationRedirectException.java [hunk 2]
```diff
@@ -19,8 +19,12 @@ public AuthenticationRedirectException(int code, String redirectUri) {
         this.redirectUri = redirectUri;
     }
 
+    public AuthenticationRedirectException(Boolean autoRedirect, String redirectUri) {
+        this(autoRedirect ? 302 : 444, redirectUri);
```
Comment (pedroigor) [inline extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/AuthenticationRedirectException.java:23]: I'm not sure about using `444`. IMO, we should handle such requests are if they were made to `service` type applications, when using a bearer token.

A `401` response would indicate an invalid session at the application so that the SPA can perform the redirect without necessarily having to parse response headers. As for `403` it would mean the session is valid but access is denied.

From a SPA perspective, after receiving a `401` response, it should be just a matter of calling `window.reload` to start the authentication flow again.

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/AuthenticationRedirectException.java [hunk 3]
```diff
@@ -19,8 +19,12 @@ public AuthenticationRedirectException(int code, String redirectUri) {
         this.redirectUri = redirectUri;
     }
 
+    public AuthenticationRedirectException(Boolean autoRedirect, String redirectUri) {
```
Comment (pedroigor) [inline extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/AuthenticationRedirectException.java:22]: IMO, this logic belongs to the `CodeAuthenticationMechanism` as it is really related to this flow. See my other comment around using `401`and `403`.

**Review by pedroigor — DISMISSED** [review]
@boosey Nice one, just a few comments.

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/AuthenticationRedirectException.java (hunk 2 above)
Comment (boosey) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/AuthenticationRedirectException.java:23]: Agreed. 444 was just a placeholder. So, it should return a 401, correct? The 403 would already be handled by the general Auth classes would take care of that case, no?

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/AuthenticationRedirectException.java (hunk 3 above)
Comment (boosey) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/AuthenticationRedirectException.java:22]: That makes sense. I will remove this and put the logic in CodeAuthenticationMechanism using the exception constructor that allows for the specification of the return code.

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/AuthenticationRedirectException.java (hunk 2 above)
Comment (sberyozkin) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/AuthenticationRedirectException.java:23]: @pedroigor @boosey Hi. I think there should be some code followed by a custom header indicating it is to do with the XHR. Otherwise SPA will try to reload even if it is a genuine `401` (whenever we decide to return `401`, example, we return `401` in case the code flow fails to complete). 
To be honest I'm not sure it should be `401`. At the quarkus OIDC level  we want to redirect, right ? But such that if it is XHR and the option is set, then let XHR fail. Can we set `399`, at least it in the `3xx` redirect space ? 
But in any case, it should be accompanied by something like `XHR-Location: redirect_uri...` IMHO

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcTenantConfig.java [hunk 4]
```diff
@@ -533,6 +533,24 @@ public void setRoleClaimSeparator(String roleClaimSeparator) {
...
+         * If it is false, a status code of '444' will be returned to allow the client to handle the
+         * redirect manually.
+         */
+        @ConfigItem(defaultValue = "true")
+        public boolean autoRedirect;
```
Comment (sberyozkin) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcTenantConfig.java:544]: @boosey IMHO this property name should be clear it is about XHR, otherwise one may get an impression that if `it is auto-redirect=false` then we don't redirect in the code flow, but we are only doing an XHR specific exception here,
As such I suggest to rename it something similar to what @pedroigor proposed in the other discussion, `redirect-with-xhr`, something like that. And update the docs:
```
* If it is false, a status code of '...' will be returned to allow the client to handle the redirect manually only if client uses XHR....
```

**Comment by sberyozkin** [comment]
@boosey Great effort, agree with Pedro :-), thanks for starting it...

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/AuthenticationRedirectException.java (hunk 2 above)
Comment (pedroigor) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/AuthenticationRedirectException.java:23]: I think that works too, +1. I thought `401` would be simpler due to the fact that this status would also mean a `window.reload` at the SPA, the actual authentication flow is managed by the server-side.

Comment (sberyozkin) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/AuthenticationRedirectException.java:23]: Hi Pedro @pedroigor Yeah, hopefully some non standard `3xx` should be enough. `401` would be good too but my concern it can confuse SPA and cause it to loop :-) (401 during the original request, then the redirect happens, something fails with the code flow, we return another 401, etc). We can make the code configurable too going forward for sure

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcTenantConfig.java (hunk 4 above)
Comment (boosey) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcTenantConfig.java:544]: I have committed a working solution that I have been able to verify with a sample client. Actually, I was doing it all wrong. It is not the redirect exception that needs to be updated, but the CHALLENGE_DATA when it is an XHR and autoRedirect=false.

I didn't see your comments about 401 vs 399 until now, so that is not changed yet. Neither did I see the comment about the setting name which I will also change in the next day or so. 

I've revoked the changes to the AuthenitcationRedirectException except for the getCode method where I actually changed it to return the actual member variable value instead of a hard coded 302.

Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcTenantConfig.java]: @boosey Good catch, I forgot why I added in the first place :-)

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java [hunk 5]
```diff
@@ -167,12 +183,36 @@ public SecurityIdentity apply(Throwable throwable) {
...
+    }
+
+    private boolean isAutoRedirectSet(TenantConfigContext configContext) {
+        return configContext.oidcConfig.authentication.autoRedirect;
+    }
+
+    private boolean shouldAutoRedirect(TenantConfigContext configContext, RoutingContext context) {
+        return isXHR(context) ? isAutoRedirectSet(configContext) : true;
+    }
+
```
Comment (boosey) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java:215]: I messed up something here. This is duplicate code. The version at 140 - 155 is the latest. I obviously didn't quite do the "update a PR" incantation correctly.

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java [hunk 6]
```diff
@@ -294,7 +336,10 @@ public void accept(SecurityIdentity identity) {
                                                 finalRedirectUri += ("?" + finalUserQuery);
                                             }
                                             LOG.debugf("Final redirect URI: %s", finalRedirectUri);
-                                            uniEmitter.fail(new AuthenticationRedirectException(finalRedirectUri));
+                                            //TODO: Does this need to check autoRedirect
+                                            uniEmitter.fail(new AuthenticationRedirectException(
+                                                    shouldAutoRedirect(configContext, context),
+                                                    finalRedirectUri));
```
Comment (boosey) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java:342]: Same here. This constructor doesn't exist for AuthenticationRedirectException. The original code at 297 is the correct version.

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java [hunk 7]
```diff
@@ -221,7 +261,9 @@ public SecurityIdentity apply(Throwable throwable) {
 
                         String localRedirectUri = buildUri(context, isForceHttps(configContext), extraPath + extraQuery);
                         LOG.debugf("Local redirect URI: %s", localRedirectUri);
-                        return Uni.createFrom().failure(new AuthenticationRedirectException(localRedirectUri));
+                        return Uni.createFrom().failure(new AuthenticationRedirectException(
+                                shouldAutoRedirect(configContext, context),
+                                localRedirectUri));
```
Comment (boosey) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java:266]: This constructor doesn't exist for AuthenticationRedirectException. The original code at 224 is the correct version.

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java [hunk 8]
```diff
@@ -497,7 +542,8 @@ private boolean isForceHttps(TenantConfigContext configContext) {
     private AuthenticationRedirectException redirectToLogoutEndpoint(RoutingContext context, TenantConfigContext configContext,
             String idToken) {
         removeCookie(context, configContext, getSessionCookieName(configContext));
-        return new AuthenticationRedirectException(buildLogoutRedirectUri(configContext, idToken, context));
+        return new AuthenticationRedirectException(shouldAutoRedirect(configContext, context),
+                buildLogoutRedirectUri(configContext, idToken, context));
```
Comment (boosey) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java:546]: Same here. This constructor doesn't exist for AuthenticationRedirectException. The original code at 500 is the correct version.

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/AuthenticationRedirectException.java [hunk 9]
```diff
@@ -20,7 +20,7 @@ public AuthenticationRedirectException(int code, String redirectUri) {
     }
```
Comment (boosey) [inline extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/AuthenticationRedirectException.java:20]: This is the correct version of this file. I removed the constructor I had added in a previous version.

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcTenantConfig.java [hunk 10]
```diff
@@ -533,6 +533,24 @@ public void setRoleClaimSeparator(String roleClaimSeparator) {
         @ConfigItem
         public Optional<String> cookiePath = Optional.empty();
 
+        /*
+         * If this property is set to 'true' then a normal 302 redirect response will be 
+         * returned. If the request was initiated via an XMLHttpRequest, then that redirect 
+         * will automatically be followed which may not be desirable for single page applications.
+         * If it is false, a status code of '401' will be returned to allow the client to
```
Comment (boosey) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcTenantConfig.java:540]: Needs to be updated with the final status code once decided.

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java [hunk 11]
```diff
@@ -188,31 +188,19 @@ private boolean shouldAutoRedirect(TenantConfigContext configContext, RoutingCon
...
+            // return status code 499 and in the www-authenticate header put the redirect url
             // www-authenticate header content; No standard content matched the exact use case
             // so the OAuth redirect-url= is an arbitrary string that can be tested
             // for on the client side
-            String headerContent = "OAuth redirect-url=" + configContext.auth.authorizeURL(params);
+            String headerContent = "OIDC redirect-url=" + configContext.auth.authorizeURL(params);
             // Vertx HTTPHeaders does noy have a "WWW_AUTHENTICATE" static
             // So, header name is hard coded for the moment
-            challenge = new ChallengeData(399, "WWW-Authenticate", headerContent);
+            challenge = new ChallengeData(499, "WWW-Authenticate", headerContent);
```
Comment (boosey) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java:198]: 399 doesn't work - at least on Chrome. If Chrome receives any 3XX code on an XHR request it automatically redirects. 499 allows the client to handle the redirect.

Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java:198]: @boosey Sounds good

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcTenantConfig.java [hunk 12]
```diff
@@ -533,6 +533,24 @@ public void setRoleClaimSeparator(String roleClaimSeparator) {
         @ConfigItem
         public Optional<String> cookiePath = Optional.empty();
 
+        /**
+         * If this property is set to 'true' then a normal 302 redirect response will be
```
Comment (sberyozkin) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcTenantConfig.java:537]: @boosey I propose to tweak this doc section a bit. 
```
If this property is set to 'true' then a normal 302 redirect response will be returned if the request was initiated via XMLHttpRequest and the current user needs to be (re)authenticated which may not be desirable for Single Page Applications since XMLHttpRequest automatically following the redirect may not work given that OIDC authorization endpoints typically do not support CORS.
If this property is set to `false` then a status code of '499' will be returned to allow the client to handle the redirect manually
```
Something along these lines ( please tweak as needed to make it a better English) as we need to be very clear it is all about XHR and when exactly the users may want to do it.

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java [hunk 13]
```diff
@@ -167,8 +183,20 @@ public SecurityIdentity apply(Throwable throwable) {
...
+            challenge = new ChallengeData(HttpResponseStatus.FOUND.code(), HttpHeaders.LOCATION,
+                    configContext.auth.authorizeURL(params));
+        } else {
+            // If the client (usually an SPA) wants to handle the redirect manually, then
+            // return status code 499 and in the www-authenticate header put the redirect url
+            // www-authenticate header content; No standard content matched the exact use case
+            // so the OAuth redirect-url= is an arbitrary string that can be tested
+            // for on the client side
+            String headerContent = "OIDC redirect-url=" + configContext.auth.authorizeURL(params);
+            // Vertx HTTPHeaders does noy have a "WWW_AUTHENTICATE" static
```
Comment (sberyozkin) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java:196]: You can drop this comment, it is OK if you just set `WWW-Authenticate`

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java [hunk 14]
```diff
@@ -167,8 +183,20 @@ public SecurityIdentity apply(Throwable throwable) {
...
+        if (shouldAutoRedirect(configContext, context)) {
+            challenge = new ChallengeData(HttpResponseStatus.FOUND.code(), HttpHeaders.LOCATION,
+                    configContext.auth.authorizeURL(params));
+        } else {
+            // If the client (usually an SPA) wants to handle the redirect manually, then
+            // return status code 499 and in the www-authenticate header put the redirect url
+            // www-authenticate header content; No standard content matched the exact use case
+            // so the OAuth redirect-url= is an arbitrary string that can be tested
+            // for on the client side
+            String headerContent = "OIDC redirect-url=" + configContext.auth.authorizeURL(params);
```
Comment (sberyozkin) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java:195]: @boosey, so if we want the users to do `location.reload` on seeing `499` then we don't really need `OIDC redirect-url` ?

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java [hunk 15]
```diff
@@ -137,6 +137,22 @@ public SecurityIdentity apply(Throwable throwable) {
         return performCodeFlow(identityProviderManager, context, resolver);
     }
 
+    private boolean isXHR(RoutingContext context) {
+        return "XMLHttpRequest".equals(context.request().getHeader("X-Requested-With"));
+    }
+
+    private boolean isAutoRedirectSet(TenantConfigContext configContext) {
```
Comment (sberyozkin) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java:144]: You can drop this function and check `configContext.oidcConfig.authentication.isXhrAutoRedirect()` directly, it is cleaner, true :-), but we access config directly all over the place

**Comment by sberyozkin** [comment]
Hi @boosey Thanks for keeping tuning it, it looks very good now, please address a few minor comments and then we will be ready to look at backing this code with the `HtmlUnitTest`. Cheers

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java (hunk 14 above)
Comment (boosey) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java:195]: I was just folllowing the guidance I found on the purpose and usage of WWW-Authenticate.

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java (hunk 15 above)
Comment (boosey) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java:144]: Done

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java (hunk 13 above)
Comment (boosey) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java]: Done

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcTenantConfig.java (hunk 12 above)
Comment (boosey) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcTenantConfig.java]: Done.

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java (hunk 15 above)
Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java:144]: @boosey, for some reasons I'm not seeing the change

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java (hunk 14 above)
Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java:195]: @boosey Right, but this `499` is a workaround as opposed to a genuine `401` which is when `WWW-Authenticate` is required, i.e it is the authorization code flow. Hmm. Well, since we are transporting this `499` with `ChallengeData` then may be it is better to at least provide `OIDC` as the supported authentication method...But I propose to drop ` redirect-url` (I did propose to return some hint myself - simply because I was not quite getting initially what was happening in the PR :-)  ), we don't really want the user code starting doing something manual around this redirect url, etc...

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java [hunk 16]
```diff
@@ -294,6 +320,7 @@ public void accept(SecurityIdentity identity) {
                                                 finalRedirectUri += ("?" + finalUserQuery);
                                             }
                                             LOG.debugf("Final redirect URI: %s", finalRedirectUri);
+                                            //TODO: Does this need to check autoRedirect
```
Comment (sberyozkin) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java:323]: You can remove this line, it is the same origin redirect to drop the parameters returned back from OIDC (`code`, etc)

**Comment by sberyozkin** [comment]
Hi @boosey This PR also needs a rebase and the commits have to be squashed, I do it like this:
1. rebase
```
git fetch upstream master
git rebase upstream/master
// at this point you get a conflict in `OidcTenantConfig`, so open an editor and fix it, and then
git rebase --continue
git push origin your_branch --force
```
2. squash
```
git log --abbrev-commit
git rebase -i sha-of-commit-immediately-before-your-first-commit-on-your-branch
// this will open a vi editor, replace all `pick` command except with the very first `pick` with `f`, and save - this will complete the squash
git push origin your_branch --force
```
Sorry if you were planning to do it already, thanks

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java (hunk 14 above)
Comment (boosey) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java:195]: Ok. I will remove the redirect-url.

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java (hunk 15 above)
Comment (boosey) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java:144]: Ah. I misunderstood. I will change.

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java (hunk 16 above)
Comment (boosey) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java:323]: Yes. I meant to ask about this so I could remove it. Will do now.

**Comment by sberyozkin** [comment]
Hi @boosey 
I've resolved the conflict and rebased and pushed to your clone (ideally  it would be in the dedicated branch but it is fine for now).
Note I've pushed the autoredirect check to the very top of the challenge method since we don't need to calculate the redirect URI in this case. Also set the property to `true` to make it a default when `OidcTenantConfig` is created without the injection.
Hope you are OK with it.

Now as far as I'm concerned, the only thing which needs to be done is to have the test added.
Hey @pedroigor do you have some cycles to add a new test to `CodeFlowTest` ? In fact all the test can do is to  send the XHR header and verify it is `499`. I might do it as well...The PR should be ready to go early next week
Cheers, Sergey

**Comment by boosey** [comment]
@sberyozkin Thanks for the rebase and squash. It tried yesterday but I couldn't get it to work and I haven't had a chance to work it out today.

On your other change. The redirect url does need to be calculated and returned in the header. The whole point of this was to use the standard logic for code flow in Quarkus OIDC, but just short circuit the automatic redirect when it is an XHR request. The client *shouldn't* have to calculate the redirect url itself. The client simply needs to do a window.location on the returned url. Otherwise, it seems that it would be easier done with Implicit flow. Below is a Dart snippet (my UI is in Flutter) which shows the how I used this with code flow while minimizing the responsibilities of the client.
```Dart
  String getRedirectURL(MapEntry headerEntry) {
    return headerEntry.value.split("OIDC ").elementAt(1);
  }

  Future<void> callQuarkusService() async {
    Map<String, String> headers = Map.fromEntries([MapEntry("X-Requested-With", "XMLHttpRequest")]);

    await http
        .get("https://******************.com:443/serviceCall", headers: headers)
        .then((response) {
            if (response.statusCode == 499 && response.headers.containsKey("www-authenticate")) {
                var loc = getRedirectURL(response.headers.entries.firstWhere((h) => h.key == "www-authenticate"));
                window.location.assign(loc);
            }
         });
  }
```

**Comment by sberyozkin** [comment]
@boosey Sure that can be restored, but I believe @pedroigor referred to some form of `window.reload` which will repeat `https://******************.com:443/serviceCal` call bypassing XHR which is why I dropped the redirect URI with `499`. 
@pedroigor Can you clarify please ?

**Comment by sberyozkin** [comment]
@boosey 

what happens if you do:
```
await http
        .get("https://******************.com:443/serviceCall", headers: headers)
        .then((response) {
            if (response.statusCode == 499 && response.headers.containsKey("www-authenticate")) {
                window.location.assign("https://******************.com:443/serviceCall");
            }
         });
```

**Comment by sberyozkin** [comment]
Hi @pedroigor It windows reload works then I'd just leave it as is, once the user code start dealing with the redirects manually then it is getting a bit more out of our control as far as the code flow is concerned.

**Comment by boosey** [comment]
@sberyozkin @pedroigor OH! Your method is much easier, less error prone, and more secure since the client never has access to the redirect url. I made the change in my client code and it worked perfectly and made the client simpler.

I don't have a strong opinion on whether the status code is 401 or 499. The one advantage 499 has is for people like me who tend to quickly read the documentation and sometimes miss little caveats about edge cases. Returning a 499 would be completely unusual and prompt the developer to go research what that means in the Quarkus docs.

If a 401 is returned, it is a common status code and the developer may think he just has something wrong in his client code and spend hours trying to track it down before actually going to the docs to find the answer. 

401 seems better because it is well-known, but 499 seems better because it is not well-known :-)

I like the idea of not returning the redirect url for security purposes and avoid losing control of the flow as you stated. Perhaps, there may be a reason that someone might actually need the redirect url for an edge case. Could perhaps this be optional and the user can request the url be returned by setting a header or some other flag?

**Comment by sberyozkin** [comment]
@boosey OK, thanks for the confirmation. IMHO we can leave it as is for the moment - as mentioned earlier we are not returning `4xx` to indicate the failure which is what `4xx` is about, it is a only a `workaround` around the fact the OIDC authorization endpoint may not be supporting CORS with XHR , so I believe trying to formalize this workaround is not needed (yet).
`401` is reserved in the code flow for genuine failures so overloading `401` to support this workaround would likely have more cons than pros. 
Lets enhance it further when when we get some concrete requirements indicating returning `499` only is not sufficient.

Let me push a simple test and the doc update
thanks

**Comment by sberyozkin** [comment]
@boosey @pedroigor 

I've added added a test and updated the docs.
Pedro - I've update the service app guide to recommend the SPA pattern you referred to at #10185 (copied the code from your example) and update the `web-app` guilde and copied @boosey's example with minor changes to make it as simple as possible.

**Review by sberyozkin — APPROVED** [review]
Let me approve since @pedroigor has given his thumbs up as well :-)

@boosey It would've likely taken us much longer to provide something similar without you going ahead with this PR and prototyping and testing, major thanks for this contribution; as I've mentioned we will continue customizing this code further if needed for sure.
Please continue stressing `quarkus-oidc`, cheers

**Comment by sberyozkin** [comment]
OK, lets do it, thanks @boosey and @pedroigor :-)

**Comment by boosey** [comment]
Sergey,

I was proud to help. I am no longer a professional developer as you can
probably imagine, so it was great to get back to my roots.

Sincerely,

Boosey
