### PR TITLE
Dev console fixes and layout improvements

### LINKED ISSUE #14216: Regression: Redirect for non-application root path does not consider root path correctly
**Describe the bug**
I have an application where I have configured a non-standard root path using `quarkus.http.root-path=/foo`. As of Quarkus 1.11 which introduces the non-application root path (defaulting to `/q`) I now need to go to http://localhost:8080/foo/q/swagger-ui/ to get to the Swagger UI. This makes sense. But there is also a redirect in place for http://localhost:8080/foo/q/swagger-ui/. Unfortunately this redirect is wrong as it redirects to http://localhost:8080/q/foo/swagger-ui/.

The same problem also applies to `quarkus.smallrye-openapi.path`.

**Expected behavior**
The redirect URL for the Swagger UI (and the OpenAPI definition) should correctly consider the HTTP root path.

**Actual behavior**
See bug description.

**To Reproduce**
Create a minimal application which includes the OpenAPI extension and configures a non-standard `quarkus.http.root-path`.

**Configuration**
```properties
quarkus.http.root-path=/foo
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: 
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.11.0.CR1
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`):

### PR DESCRIPTION
**Pull request by phillip-kruger**
Signed-off-by:Phillip Kruger <phillip.kruger@gmail.com>
Fix #14216

This PR Contains a few small fixes related to the new non-application path and dev console.

**Dev Console**

- Fixed case where httpRoot is set (did not work)
- Pass httpRoot and frameworkRoot to all templates
- Make config available in templates
- Removed hardcoded `/q` from main.html

**Health UI**

- Fixed case where httpRoot is set
- Fixed wrong ui dependency in health UI (runtime vs deploy)
- Added embeded.html to expose health UI links
- Removed hardcoded `health-ui` and replaced with config lookup

**GraphQL UI**

- Fixed case where httpRoot is set
- Removed hardcoded `/q` from embedded.html
- Removed hardcoded `graphql-ui` and replaced with config lookup

**Swagger UI**

- Removed hardcoded `/q` from embedded.html
- Removed hardcoded `swagger-ui` and replaced with config lookup
- Fixed case where httpRoot is set

### CODE REVIEW

File: extensions/smallrye-graphql/deployment/src/main/java/io/quarkus/smallrye/graphql/deployment/SmallRyeGraphQLProcessor.java [hunk 1]
```diff
@@ -454,18 +454,19 @@ void getGraphqlUiFinalDestination(
 
             String graphQLPath = httpRootPath.adjustPath(graphQLConfig.rootPath);
             String graphQLUiPath = nonApplicationRootPathBuildItem
-                    .adjustPath(httpRootPath.adjustPath(graphQLConfig.ui.rootPath));
+                    .adjustPath(graphQLConfig.ui.rootPath);
```
Comment (FroMage) [inline extensions/smallrye-graphql/deployment/src/main/java/io/quarkus/smallrye/graphql/deployment/SmallRyeGraphQLProcessor.java:457]: Is it on purpose that you're moving `httpRootPath.adjustPath` here once in favour of doing it later several times?

File: extensions/smallrye-graphql/deployment/src/main/java/io/quarkus/smallrye/graphql/deployment/SmallRyeGraphQLProcessor.java [hunk 2]
```diff
@@ -483,7 +484,8 @@ void getGraphqlUiFinalDestination(
                                         LINE_FORMAT)
                                 .getBytes(StandardCharsets.UTF_8);
                         content = WebJarUtil
-                                .updateUrl(new String(content, StandardCharsets.UTF_8), graphQLPath, UI_LINE_TO_UPDATE,
```
Comment (FroMage) [inline extensions/smallrye-graphql/deployment/src/main/java/io/quarkus/smallrye/graphql/deployment/SmallRyeGraphQLProcessor.java:486]: This changes `graphQLPath` for `graphQLUiPath`, is it on purpose?

File: extensions/smallrye-health/deployment/src/main/resources/dev-templates/embedded.html [hunk 3]
```diff
@@ -0,0 +1,12 @@
+<a href="{frameworkRootPath}health" class="badge badge-light">
```
Comment (FroMage) [inline extensions/smallrye-health/deployment/src/main/resources/dev-templates/embedded.html:1]: I'm strongly opposed to `frameworkRootPath` that includes a `/` at the end, because it makes for very poor and confusing template usage like `{frameworkRootPath}health` where inevitably people will wonder if they need to include a `/` or not.

Can you change it to not include any last `/` and use `{frameworkRootPath}/health` in templates? This would make it consistent with the embedded path template parameter too.

File: extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/devmode/console/DevConsoleProcessor.java [hunk 4]
```diff
@@ -155,7 +157,15 @@ public void handle(HttpServerRequest event) {
...
 
-    protected static void newRouter(Engine engine) {
+    protected static void newRouter(Engine engine,
+            HttpRootPathBuildItem httpRootPathBuildItem,
+            NonApplicationRootPathBuildItem nonApplicationRootPathBuildItem) {
+
+        // "/" or "/myroot/" 
+        String httpRootPath = httpRootPathBuildItem.adjustPath("/");
+        // "/" or "/myroot/" or "/q/" or "/myroot/q/"
+        String frameworkRootPath = httpRootPathBuildItem.adjustPath(nonApplicationRootPathBuildItem.adjustPath("/"));
```
Comment (FroMage) [inline extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/devmode/console/DevConsoleProcessor.java:167]: Those should not have the last `/`.

**Review by FroMage — CHANGES_REQUESTED** [review]
Looks good, except two verifications and a disagreement about slashes ;)

File: extensions/smallrye-graphql/deployment/src/main/java/io/quarkus/smallrye/graphql/deployment/SmallRyeGraphQLProcessor.java (hunk 2 above)
Comment (phillip-kruger) [reply extensions/smallrye-graphql/deployment/src/main/java/io/quarkus/smallrye/graphql/deployment/SmallRyeGraphQLProcessor.java:486]: Yes, was a bug in the prev PR. This is used in "home" (image) click

File: extensions/smallrye-health/deployment/src/main/resources/dev-templates/embedded.html (hunk 3 above)
Comment (phillip-kruger) [reply extensions/smallrye-health/deployment/src/main/resources/dev-templates/embedded.html:1]: So, I initially had it like that, but.... to also make sure the case where httpRoot is / and nonApp is switch off, (so path is /) that we do not need to do 'if /' 
Now in all cases I know that I can just add my page. Cases include /, /httpRoot/, /httpRoot/nonAppRoot/, /nonAppRoot/

Do you think I should just add coded to always remove the last / ?

File: extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/devmode/console/DevConsoleProcessor.java (hunk 4 above)
Comment (phillip-kruger) [reply extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/devmode/console/DevConsoleProcessor.java:167]: Ok, let me remove that.

File: extensions/smallrye-graphql/deployment/src/main/java/io/quarkus/smallrye/graphql/deployment/SmallRyeGraphQLProcessor.java (hunk 1 above)
Comment (phillip-kruger) [reply extensions/smallrye-graphql/deployment/src/main/java/io/quarkus/smallrye/graphql/deployment/SmallRyeGraphQLProcessor.java:457]: Yea, because `NotFoundPageDisplayableEndpointBuildItem` does this under the covers, so I need a var without this for that.

File: extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/devmode/console/DevConsoleProcessor.java (hunk 4 above)
Comment (phillip-kruger) [reply extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/devmode/console/DevConsoleProcessor.java:167]: Removed

File: extensions/smallrye-health/deployment/src/main/resources/dev-templates/embedded.html (hunk 3 above)
Comment (phillip-kruger) [reply extensions/smallrye-health/deployment/src/main/resources/dev-templates/embedded.html]: Removed the /

File: extensions/smallrye-graphql/deployment/src/main/java/io/quarkus/smallrye/graphql/deployment/SmallRyeGraphQLProcessor.java (hunk 1 above)
Comment (FroMage) [reply extensions/smallrye-graphql/deployment/src/main/java/io/quarkus/smallrye/graphql/deployment/SmallRyeGraphQLProcessor.java:457]: OK

File: extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/devmode/console/DevConsoleProcessor.java [hunk 5]
```diff
@@ -155,7 +157,17 @@ public void handle(HttpServerRequest event) {
...
-    protected static void newRouter(Engine engine) {
+    protected static void newRouter(Engine engine,
+            HttpRootPathBuildItem httpRootPathBuildItem,
+            NonApplicationRootPathBuildItem nonApplicationRootPathBuildItem) {
+
+        // "" or "/myroot" 
+        String httpRootPath = httpRootPathBuildItem.adjustPath("/");
+        httpRootPath = httpRootPath.substring(0, httpRootPath.lastIndexOf("/"));
+        // "" or "/myroot" or "/q" or "/myroot/q"
+        String frameworkRootPath = httpRootPathBuildItem.adjustPath(nonApplicationRootPathBuildItem.adjustPath("/"));
```
Comment (FroMage) [inline extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/devmode/console/DevConsoleProcessor.java:168]: Are you absolutely sure that those will have a trailing `/`? There's no way for the user to set them to `/foo`?

**Review by FroMage — CHANGES_REQUESTED** [review]

File: extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/devmode/console/DevConsoleProcessor.java (hunk 5 above)
Comment (phillip-kruger) [reply extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/devmode/console/DevConsoleProcessor.java:168]: Yes, adjustPath add that

Comment (phillip-kruger) [reply extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/devmode/console/DevConsoleProcessor.java:168]: (I tested with /foo)

Comment (FroMage) [reply extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/devmode/console/DevConsoleProcessor.java:168]: OK great.

**Review by FroMage — APPROVED** [review]

**Comment by gsmet** [comment]
I just pushed my changes to this branch as we will collaborate with Phillip.

**Review by gsmet — CHANGES_REQUESTED** [review]
Please don't merge, we are iterating with @phillip-kruger (but I still want the CI to run so don't want to make it draft).

**Comment by gsmet** [comment]
We have a test failure:
```
Error:  io.quarkus.vertx.web.SimpleRouteTest.testSimpleRoute  Time elapsed: 1.125 s  <<< FAILURE!
java.lang.AssertionError: 
1 expectation failed.
Expected status code <405> but was <404>.
```

Looks like the fact that GET on `/delete` is not supported now get you status 404 instead of 405.

File: extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/devmode/console/DevConsole.java [hunk 6]
```diff
@@ -35,8 +35,13 @@
     final Engine engine;
     final Map<String, Map<String, Object>> extensions = new HashMap<>();
 
-    DevConsole(Engine engine) {
+    final Map<String, Object> globalData = new HashMap<>();
+
+    DevConsole(Engine engine, String httpRootPath, String frameworkRootPath) {
         this.engine = engine;
+        this.globalData.put("httpRootPath", httpRootPath);
+        this.globalData.put("frameworkRootPath", frameworkRootPath);
```
Comment (kenfinnigan) [inline extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/devmode/console/DevConsole.java:43]: Should this be named "nonApplicationRootPath" instead of "frameworkRootPath" to align with the name elsewhere?

**Review by kenfinnigan — APPROVED** [review]

**Review by gsmet — APPROVED** [review]
