### PR TITLE
Ensure that Jackson writer doesn't negatively affect endpoint score

### LINKED ISSUE #14720: Resteasy Reactive detects multiple writers, but only one response type is present
**Describe the bug**
I have a GET method annotated with `@Produces(MediaType.APPLICATION_JSON)`.
In the Score Console it says however that I have 2 writers for this method:
```
[io.quarkus.resteasy.reactive.jackson.runtime.serialisers.JacksonMessageBodyWriter@5a21df38, 
org.jboss.resteasy.reactive.server.providers.serialisers.ServerStringMessageBodyHandler@7a97f70c]
```

This negativly affects the score of this method. See screenshot.

**Expected behavior**
RR should not detect a simple Produces(MediaType.APPLICATION_JSON) as multiple writers.

**To Reproduce**

1. Download the reproducer
2. mvn quarkus:dev
3. Go to http://localhost:8080/q/dev/io.quarkus.quarkus-resteasy-reactive/scores

**Screenshots**
image

Environment (please complete the following information):

* Output of uname -a or ver:
Linux martin 5.8.0-41-generic #46~20.04.1-Ubuntu SMP Mon Jan 18 17:52:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* Output of java -version:
openjdk 11.0.7 2020-04-14 LTS
OpenJDK Runtime Environment Zulu11.39+15-CA (build 11.0.7+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.39+15-CA (build 11.0.7+10-LTS, mixed mode)
* Quarkus version or git rev:
1.11.1.Final
* Build tool (ie. output of mvnw --version or gradlew --version):
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/martin/.sdkman/candidates/maven/current
Java version: 11.0.7, vendor: Azul Systems, Inc., runtime: /home/martin/.sdkman/candidates/java/11.0.7-zulu
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.8.0-41-generic", arch: "amd64", family: "unix"

### PR DESCRIPTION
**Pull request by geoand**
Fixes https://github.com/quarkusio/quarkus/issues/14720#issuecomment-820610879

### CODE REVIEW

File: extensions/resteasy-reactive/quarkus-resteasy-reactive-jackson-common/runtime/src/main/java/io/quarkus/resteasy/reactive/jackson/runtime/serialisers/JacksonMessageBodyWriterUtil.java [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+        return jsonFactory.isEnabled(JsonGenerator.Feature.AUTO_CLOSE_TARGET)
+                || jsonFactory.isEnabled(JsonGenerator.Feature.FLUSH_PASSED_TO_STREAM);
+    }
+
+    public static void setNecessaryJsonFactoryConfig(JsonFactory jsonFactory) {
+        jsonFactory.configure(JsonGenerator.Feature.AUTO_CLOSE_TARGET, false);
+        jsonFactory.configure(JsonGenerator.Feature.FLUSH_PASSED_TO_STREAM, false);
+    }
+
+    public static void doLegacyWrite(Object o, Annotation[] annotations, MultivaluedMap<String, Object> httpHeaders,
```
Comment (michalszynkiewicz) [inline extensions/resteasy-reactive/quarkus-resteasy-reactive-jackson-common/runtime/src/main/java/io/quarkus/resteasy/reactive/jackson/runtime/serialisers/JacksonMessageBodyWriterUtil.java:44]: why is it called `doLegacyWrite`?

Comment (geoand) [reply extensions/resteasy-reactive/quarkus-resteasy-reactive-jackson-common/runtime/src/main/java/io/quarkus/resteasy/reactive/jackson/runtime/serialisers/JacksonMessageBodyWriterUtil.java:44]: Because it's the "implementation" of the JAX-RS write method, not the new RESTEasy Reactive write method

**Comment by michalszynkiewicz** [comment]
In the client, we still reuse the server jackson reader and writer if it's available but you're getting rid of the superclass, right?

**Comment by geoand** [comment]
Yeah, the whole idea is just to get rid of the super class.

I don't think I've changed anything with regards to the actual behavior, unless you see something I've missed

**Review by michalszynkiewicz — APPROVED** [review]

**Comment by michalszynkiewicz** [comment]
I think it's all good :) Just wanted to double check if there's nothing I'm missing in the change

**Comment by geoand** [comment]
👍🏼
