### PR TITLE
Adjust 'challenge' selection so that custom auth mechanism is called

### LINKED ISSUE #27180: Unable to Overwrite Response using Security-JPA & RestEasy-Classic
### Describe the bug

I'm currently unable to overwrite the Response with a CustomFormAuthenticationMechanism when using security-jpa with quarkus using RestEasy-Classic. I did not test ReastEasy-Reactive.

The last known version this was possible was using 2.7.5.Final.

If there's anything else you need let me know!

Here's my Implementation of the HttpAuthenticationMechanism

```java
@Alternative
@Priority(1)
@ApplicationScoped
public class CustomFormAuthenticationMechanism implements HttpAuthenticationMechanism {

    private static final Logger LOGGER = LoggerFactory.getLogger(CustomFormAuthenticationMechanism.class);

    @Inject
    FormAuthenticationMechanism delegate;

    @Override
    public Uni<SecurityIdentity> authenticate(RoutingContext context, IdentityProviderManager identityProviderManager) {
        return delegate.authenticate(context, identityProviderManager);
    }

    @Override
    public Uni<ChallengeData> getChallenge(RoutingContext context) {
        Uni<ChallengeData> rValue = delegate.getChallenge(context);
        return rValue.onItem().transform(challengeData -> {
            if (challengeData.status == Response.Status.FOUND.getStatusCode()) {
                return new ChallengeData(Response.Status.UNAUTHORIZED.getStatusCode(), challengeData.headerName, challengeData.headerContent);
            }
            return challengeData;
        });
    }

    @Override
    public Set<Class<? extends AuthenticationRequest>> getCredentialTypes() {
        return delegate.getCredentialTypes();
    }

    @Override
    public HttpCredentialTransport getCredentialTransport() {
        return delegate.getCredentialTransport();
    }

    @Override
    public Uni<HttpCredentialTransport> getCredentialTransport(RoutingContext context) {
        return delegate.getCredentialTransport(context);
    }

    @Override
    public Uni<Boolean> sendChallenge(RoutingContext context) {
        return getChallenge(context).map(new ChallengeSender(context));
    }
}
```

### Expected behavior

Changed Challenge Data with changed Response should be returned resulting in a 401 Response

### Actual behavior

Default Response (302) is returned

### How to Reproduce?

Reproducer: https://github.com/BrainShit/custom-formauth-reproducer

1. Start the Application
2. curl the security endpoint with user "admin" and a wrong password

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

11.0.8 2020-07-14

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.11.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by michalvavrik**
fixes: #27180

This PR makes sure `io.quarkus.vertx.http.runtime.security.HttpAuthenticationMechanism#send/getChallenge` of a custom auth mechanism get called. There is an example of [HttpAuthenticationMechanism Customization](https://quarkus.io/guides/security-customization#httpauthenticationmechanism-customization) that don't work for me as built-in auth mechanisms put into routing context themselves and this information is used when selecting an auth mechanism for challenge, I've explained actual behavior in depth in linked issue. This solution needs check from an expert (@sberyozkin ) as I only inferred "expected behavior" from PRs submitted in this area.

### CODE REVIEW

**Comment by sberyozkin** [comment]
I'm not sure it will work - for example, we have both Basic and OIDC mechanisms enabled at the same time, with this PR the challenge caused by a failing basic auth can be picked by OIDC or the other way around, depending on the sorting order.
Perhaps the condition should be: `if (mechanisms.size() > 1)` ?

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpAuthenticator.java [hunk 1]
```diff
@@ -137,10 +137,14 @@ public Uni<Boolean> sendChallenge(RoutingContext routingContext) {
         routingContext.request().resume();
         Uni<Boolean> result = null;
 
-        HttpAuthenticationMechanism matchingMech = routingContext.get(HttpAuthenticationMechanism.class.getName());
-        if (matchingMech != null) {
-            result = matchingMech.sendChallenge(routingContext);
+        // only take mechanism from context if it is path specific as we still want to send challenge to a custom mechanism
+        if (usePathSpecificMechanism(routingContext)) {
```
Comment (sberyozkin) [inline extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpAuthenticator.java:141]: See my earlier comment, I think it should check if more than one mechanism is reg-ed - if it is only one then no need to check the mech in the context

Comment (michalvavrik) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpAuthenticator.java:141]: I think you are right, I'll try it.

**Comment by sberyozkin** [comment]
And also say in the docs - that `your custom authentication mechanism has to add itself to RoutingContext if more than one authentication mechanism is available to ensure a correct challenge is returned` - something along these lines

**Comment by michalvavrik** [comment]
`if (mechanisms.size() > 1) ` fixes the reproducer only in combination with `@Priority(1) @Alternative`, that is not a problem in regards of https://github.com/quarkusio/quarkus/issues/27180, but I wonder if the auth mechanism selection don't work differently to your expecatation:

Please consider `CustomFormAuthenticator` without `@Priority(1) @Alternative` and with `routingContext.put(HttpAuthenticationMechanism.class.getName(), this);`, if you run such a test, the result depends on the order of mechanisms -> it's random. Sometimes I get 8 times green and then red, sometimes I get couple of failures etc. I think that's because both mechanisms are getting called in `io.quarkus.vertx.http.runtime.security.HttpAuthenticator#createSecurityIdentity` and who is in the routing context depends on hap.

**Comment by sberyozkin** [comment]
>Please consider CustomFormAuthenticator without @Priority(1) @Alternative and with routingContext.put(HttpAuthenticationMechanism.class.getName(), this);, if you run such a test, the result depends on the order of mechanisms -> it's random

Sure, I think we have 2 variations here
1: a mechanism such as `CustomFormAuthenticator` needs to replace the default built in form one. - this is the reproducer case.
(there is also `HttpAuthenticationMechanism.getPriority` which I guess can be used instead)
2. a totally new custom mechanism one, not conflicting with any of the existing ones, is used alongside for ex OIDC - in this case I think this new mechanism needs to set this attribute.

**Review by sberyozkin — APPROVED** [review]

**Comment by michalvavrik** [comment]
FYI Now just fixed indentation for docs as originally I had it wrong.

**Comment by michalvavrik** [comment]
I see, it makes sense.

File: docs/src/main/asciidoc/security-customization.adoc [hunk 2]
```diff
@@ -107,13 +109,13 @@ public class CustomAwareJWTAuthMechanism implements HttpAuthenticationMechanism
 
 	@Override
 	public Set<Class<? extends AuthenticationRequest>> getCredentialTypes() {
-		return selectBetweenJwtAndOidc(context).getCredentialTypes();
+		return selectBetweenJwtAndOidc(null).getCredentialTypes();
```
Comment (sberyozkin) [inline docs/src/main/asciidoc/security-customization.adoc:112]: I just prototyped some code - but this specific update shows it was a bad prototype :-). I think here we need to return a combination of 2 sets returned from JWT and OIDC...

Comment (michalvavrik) [reply docs/src/main/asciidoc/security-customization.adoc]: Done. BTW I built docs to be sure - the example is aligned.

**Comment by michalvavrik** [comment]
`io.quarkus.smallrye.reactivemessaging.amqp.AnonymousAmqpTest` clearly not related (vertx disconnected stuff), `io.quarkus.it.keycloak.CodeFlowTest.testTokenAutoRefresh` I think goes down to missing PublicKey.

**Comment by michalvavrik** [comment]
Ah, I can see that's a known issue https://github.com/quarkusio/quarkus/issues/27900
