### PR TITLE
Register all profile properties in the default config source

### LINKED ISSUE #15389: ENVs required in prod profile break dev profile but only when using the built artifact
**Describe the bug**

Quarkus tries to resolve ENVs for profiles which are not active. This breaks other profiles. This only happens with the built jar. It works fine with the `quarkus:dev` plugin.

Example:

Empty Quarkus project with `%prod.quarkus.http.port=${HTTP_PORT}` as the only configuration in `application.properties` breaks every other profile when running from jar if `HTTP_PORT` is not exported. 

**Expected behavior**

If `HTTP_PORT` is not set application should start fine with any profile but `prod`. `HTTP_PORT` is only required in `prod`.

**Actual behavior**

Quarkus tries to resolve `HTTP_PORT` regardless of the active profile and fails to start.

```
QUARKUS_PROFILE=foo java -jar target/quarkus-app/quarkus-run.jar
One or more configuration errors have prevented the application from starting. The errors are:
  - SRCFG00011: Could not expand value HTTP_PORT in property quarkus.http.port
```

**To Reproduce**

https://github.com/atamanroman/quarkus-profile-dev-prod-repro

Steps to reproduce here:

https://github.com/atamanroman/quarkus-profile-dev-prod-repro/blob/main/README.md

**Additional context**

This issue was opened after discussion in [this zulip thread](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/ENVs.20required.20in.20prod.20profile.20break.20dev).

### LINKED ISSUE #15919: Add support for postgis container images to postgresql DevService
## Description

DevServices support for PostgreSQL database does not work for `postgis` images. If you specify a custom image, e.g.:

```
%test.quarkus.datasource.devservices.image-name=postgis/postgis:latest
```

image name verification fails, since `postgis` is not recognised as a `postgresql` compatible substitute.

I have stumbled upon this issue since our previously working TestContainers configuration stopped working with Quarkus 1.12. Specifying db-kind `other` and TestContainers JDBC driver and URL somehow works for the default datasource but fails for the named datasource:

```
[error]: Build step io.quarkus.agroal.deployment.AgroalProcessor#build threw an exception: io.quarkus.runtime.configuration.ConfigurationException: Unable to find a JDBC driver corresponding to the database kind 'other' for the datasource 'qgis_import'. Either provide a suitable JDBC driver extension, define the driver manually, or disable the JDBC datasource by adding 'quarkus.datasource.qgis_import.jdbc=false' to your configuration if you don't need it.
```

## Implementation ideas

I made a patch to allow for specifying `postgis` images with `postgresql` db-kind, .e.g.:

```properties
%test.quarkus.datasource.qgis_import.db-kind=postgresql
%test.quarkus.datasource.qgis_import.devservices.image-name=postgis/postgis:latest
```

```
Index: extensions/devservices/postgresql/src/main/java/io/quarkus/devservices/postgresql/deployment/PostgresqlDevServicesProcessor.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/extensions/devservices/postgresql/src/main/java/io/quarkus/devservices/postgresql/deployment/PostgresqlDevServicesProcessor.java b/extensions/devservices/postgresql/src/main/java/io/quarkus/devservices/postgresql/deployment/PostgresqlDevServicesProcessor.java
--- a/extensions/devservices/postgresql/src/main/java/io/quarkus/devservices/postgresql/deployment/PostgresqlDevServicesProcessor.java	(revision fd713d371b10320dc8a6f9cb85fb9846255d64ac)
+++ b/extensions/devservices/postgresql/src/main/java/io/quarkus/devservices/postgresql/deployment/PostgresqlDevServicesProcessor.java	(date 1616172989135)
@@ -6,6 +6,7 @@
 import java.util.Optional;
 
 import org.testcontainers.containers.PostgreSQLContainer;
+import org.testcontainers.utility.DockerImageName;
 
 import io.quarkus.datasource.common.runtime.DatabaseKind;
 import io.quarkus.datasource.deployment.spi.DevServicesDatasourceProvider;
@@ -21,7 +22,7 @@
             public RunningDevServicesDatasource startDatabase(Optional<String> username, Optional<String> password,
                     Optional<String> datasourceName, Optional<String> imageName, Map<String, String> additionalProperties) {
                 PostgreSQLContainer container = new PostgreSQLContainer(
-                        imageName.orElse(PostgreSQLContainer.IMAGE + ":" + PostgreSQLContainer.DEFAULT_TAG))
+                        getDockerImageName(imageName.orElse(PostgreSQLContainer.IMAGE + ":" + PostgreSQLContainer.DEFAULT_TAG)))
                                 .withPassword(password.orElse("quarkus"))
                                 .withUsername(username.orElse("quarkus"))
                                 .withDatabaseName(datasourceName.orElse("default"));
@@ -36,6 +37,15 @@
                             }
                         });
             }
+
+            private DockerImageName getDockerImageName(String fullImageName) {
+                DockerImageName dockerImageName = DockerImageName.parse(fullImageName);
+                // handle postgis as postgres compatible substitute
+                if (dockerImageName.getRepository().contains("postgis")) {
+                    dockerImageName = dockerImageName.asCompatibleSubstituteFor(PostgreSQLContainer.IMAGE);
+                }
+                return dockerImageName;
+            }
         });
     }
 
```

### PR DESCRIPTION
**Pull request by radcortez**
- Fixes #15389
- Fixes #15919 

The behaviour reported in #15919 was caused by the fix in #15389. This only happened in a very specific case. When a named map with a build time configuration only had values set in a profile, and these were being used somehow in a build step.

### CODE REVIEW

File: extensions/arc/deployment/src/test/java/io/quarkus/arc/test/config/ConfigDefaultValuesTest.java [hunk 1]
```diff
@@ -0,0 +1,112 @@
...
+import io.quarkus.test.QuarkusUnitTest;
+
+public class ConfigDefaultValuesTest {
+    @RegisterExtension
+    static final QuarkusUnitTest TEST = new QuarkusUnitTest()
+            .setArchiveProducer(() -> ShrinkWrap.create(JavaArchive.class)
+                    .addClass(ConfigDefaultValuesTest.class)
+                    .addClass(MapBuildTimeConfig.class)
+                    .addClass(MapBuildTimeConfigBuildStep.class)
+                    .addAsResource(new StringAsset(MapBuildTimeConfig.class.getName()), "META-INF/quarkus-config-roots.list")
```
Comment (stuartwdouglas) [inline extensions/arc/deployment/src/test/java/io/quarkus/arc/test/config/ConfigDefaultValuesTest.java:34]: This is not something that is supported, it just happens to work. There are lots of things that could go wrong here (e.g. there are other copies of this file on the class path, it only picks up the correct one by chance).

Can you move this test to core/test-extension and put the config classes in the extension itself? Its where all the other config based tests are so I think it is where it really belongs.

**Review by stuartwdouglas — CHANGES_REQUESTED** [review]

File: extensions/arc/deployment/src/test/java/io/quarkus/arc/test/config/ConfigDefaultValuesTest.java (hunk 1 above)
Comment (radcortez) [reply extensions/arc/deployment/src/test/java/io/quarkus/arc/test/config/ConfigDefaultValuesTest.java:34]: Interesting. I've got the idea that all the files from the classpath would load and it was fine.

No worries. Let me change that. Thanks!

**Review by stuartwdouglas — APPROVED** [review]
