### PR TITLE
Remove Uni await for OIDC code access token validation and user info calls

### LINKED ISSUE #13249: OIDC 1.10.0.CR1 - event loop thread blocked
**Describe the bug**
Upgraded an existing app from 1.9.2.Final to 1.10.0.CR and I am getting below error

```java
2020-11-12 01:14:14,178 INFO  [io.quarkus] (main) Installed features: [amazon-s3, cache, cdi, kubernetes, logging-gelf, mutiny, oidc, rest-client, resteasy, resteasy-jsonb, resteasy-mutiny, security, smallrye-context-propagation]
2020-11-12 01:17:13,262 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-0) HTTP Request to /s3/s3.html?state=ea63119a-310d-4c65-9c16-5aded25683ec&session_state=9616cbb2-8869-42e1-ad81-1964a72ee7ff&code=69ad933f-9481-45f6-b731-28960124e1f5.9616cbb2-8869-42e1-ad81-1964a72ee7ff.91b23959-4d87-4fbe-a790-69b838fbe4a0 failed, error id: 479eb3ed-e9db-49e0-a817-28a3d16c0eb0-1: 
java.lang.IllegalStateException: The current thread cannot be blocked: vert.x-eventloop-thread-0
	at io.smallrye.mutiny.operators.UniBlockingAwait.await(UniBlockingAwait.java:29)
	at io.smallrye.mutiny.groups.UniAwait.atMost(UniAwait.java:61)
	at io.smallrye.mutiny.groups.UniAwait.indefinitely(UniAwait.java:42)
	at io.quarkus.oidc.runtime.OidcIdentityProvider.verifyCodeFlowAccessToken(OidcIdentityProvider.java:243)
	at io.quarkus.oidc.runtime.OidcIdentityProvider.validateTokenWithOidcServer(OidcIdentityProvider.java:96)
	at io.quarkus.oidc.runtime.OidcIdentityProvider.authenticate(OidcIdentityProvider.java:84)
	at io.quarkus.oidc.runtime.OidcIdentityProvider.access$100(OidcIdentityProvider.java:37)
	at io.quarkus.oidc.runtime.OidcIdentityProvider$1$1.get(OidcIdentityProvider.java:71)
	at io.quarkus.oidc.runtime.OidcIdentityProvider$1$1.get(OidcIdentityProvider.java:59)
	at io.smallrye.mutiny.operators.UniCreateFromDeferredSupplier.subscribing(UniCreateFromDeferredSupplier.java:24)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:54)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:49)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:30)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2.lambda$subscribing$0(ContextPropagationUniInterceptor.java:48)
	at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$1(SmallRyeThreadContext.java:530)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2.subscribing(ContextPropagationUniInterceptor.java:48)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:54)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:49)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:30)
	at io.smallrye.mutiny.operators.UniOnItemTransformToUni.handleInnerSubscription(UniOnItemTransformToUni.java:57)
	at io.smallrye.mutiny.operators.UniOnItemTransformToUni.invokeAndSubstitute(UniOnItemTransformToUni.java:43)
	at io.smallrye.mutiny.operators.UniOnItemTransformToUni$2.onItem(UniOnItemTransformToUni.java:74)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.lambda$onItem$1(ContextPropagationUniInterceptor.java:32)
	at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$1(SmallRyeThreadContext.java:530)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.onItem(ContextPropagationUniInterceptor.java:32)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.onItem(UniSerializedSubscriber.java:86)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.lambda$onItem$1(ContextPropagationUniInterceptor.java:32)
	at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$1(SmallRyeThreadContext.java:530)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.onItem(ContextPropagationUniInterceptor.java:32)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.onItem(UniSerializedSubscriber.java:86)
```

**Expected behavior**
OIDC hybrid auth should work

**Actual behavior**
Getting the above stacktrace

**Configuration**
```properties
quarkus.oidc.auth-server-url=http://keycloak.com
quarkus.oidc.client-id=backend
quarkus.oidc.credentials.secret=71234b
quarkus.oidc.application-type=hybrid
quarkus.oidc.roles.source=accesstoken
quarkus.oidc.roles.role-claim-path=scope
quarkus.http.auth.permission.authenticated.paths=/*
quarkus.http.auth.permission.authenticated.policy=authenticated
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: mac os & Linux
 - Output of `java -version`:  Java 11
 - GraalVM version (if different from Java): NA
 - Quarkus version or git rev: 1.10.0.CR1
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): mvnw

**Additional context**
@sberyozkin Let me know if you need any additional details

### PR DESCRIPTION
**Pull request by sberyozkin**
Fixes #13249.

This PR follows the earlier PR improving OIDC Uni related code:
- code access token verification and user info calls are totally async now; 
- user-info calls are always blocking hence they will run by the blocking executor
- code access token as well as a bearer access token will also be run by the blocking executor if the token is opaque - right now the introspection requests initiated internally by Vert.x would run on the IO thread

Changes look extensive but they are really not, it is just related to me having to collapse some code into reusable functions to minimize the duplication.

Also, `BlockingOperationControl` code branches will be gone as soon as I make sure that refreshing the tokens does not require a blocking call, but until then I have to check it to avoid re-dispatching to the executor (as explained by Stuart).

We already have the tests for all the affected combinations (code access token is a source of roles, opaque tokens, user-info)   

My Uni confidence is high now thanks to @cescoffier so this PR should be good to go once it will go green :-)

CC @cescoffier @gsmet

### CODE REVIEW

**Comment by gsmet** [comment]
@cescoffier could you have a close look to this one? We need to get this right.

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java [hunk 1]
```diff
@@ -35,6 +36,11 @@
 
 @ApplicationScoped
 public class OidcIdentityProvider implements IdentityProvider<TokenAuthenticationRequest> {
+
+    @SuppressWarnings("deprecation")
+    private static final Uni<AccessToken> NULL_CODE_ACCESS_TOKEN_UNI = Uni.createFrom().nullItem();
```
Comment (cescoffier) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java:41]: Why removing the deprecation?

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java [hunk 2]
```diff
@@ -81,101 +87,157 @@ public SecurityIdentity get() {
...
+                    }
+                });
+    }
+
+    @SuppressWarnings("deprecation")
+    private Uni<SecurityIdentity> validateTokenWithOidcServer(RoutingContext vertxContext, TokenAuthenticationRequest request,
+            TenantConfigContext resolvedContext, AccessToken codeAccessToken) {
+
+        if (codeAccessToken != null) {
+            vertxContext.put("code_flow_access_token_result", codeAccessToken);
```
Comment (cescoffier) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java:115]: should be a constant.

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java [hunk 3]
```diff
@@ -81,101 +87,157 @@ public SecurityIdentity get() {
...
-                resolvedContext.auth.decodeToken(request.getToken().getToken(),
-                        new Handler<AsyncResult<AccessToken>>() {
+        final TokenCredential tokenCred = request.getToken();
+        if (tokenCred instanceof AccessTokenCredential && ((AccessTokenCredential) tokenCred).isOpaque()) {
+            // remote introspection is required, a blocking call
+            if (BlockingOperationControl.isBlockingAllowed()) {
+                return Uni.createFrom().emitter(new Consumer<UniEmitter<? super SecurityIdentity>>() {
+                    @Override
+                    public void accept(UniEmitter<? super SecurityIdentity> uniEmitter) {
+                        createSecurityIdentityWithOidcServer(uniEmitter, vertxContext, request, resolvedContext, userInfo);
```
Comment (cescoffier) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java:139]: even if blocking is allowed, it may be not called on the same thread. This method is called on the subscription thread, not the assembly thread.

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java [hunk 4]
```diff
@@ -81,101 +87,157 @@ public SecurityIdentity get() {
...
+                return Uni.createFrom().emitter(
+                        new Consumer<UniEmitter<? super SecurityIdentity>>() {
                             @Override
-                            public void handle(AsyncResult<AccessToken> event) {
-                                if (event.failed()) {
-                                    uniEmitter.fail(new AuthenticationFailedException(event.cause()));
-                                    return;
-                                }
+                            public void accept(UniEmitter<? super SecurityIdentity> uniEmitter) {
+                                tenantResolver.getBlockingExecutor().execute(new Runnable() {
```
Comment (cescoffier) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java:147]: Any reason to not use Infrastructure.getDEfaultWorkerPool()?

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java [hunk 5]
```diff
@@ -81,101 +87,157 @@ public SecurityIdentity get() {
...
+                                    }
+                                });
+                            }
+                        });
+            }
+        } else {
+            return Uni.createFrom().emitter(new Consumer<UniEmitter<? super SecurityIdentity>>() {
+                @Override
+                public void accept(UniEmitter<? super SecurityIdentity> uniEmitter) {
+                    createSecurityIdentityWithOidcServer(uniEmitter, vertxContext, request, resolvedContext, userInfo);
```
Comment (cescoffier) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java:161]: if I'm not mistaken this may be blocking, here you may be on the event loop.

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java [hunk 6]
```diff
@@ -81,101 +87,157 @@ public SecurityIdentity get() {
...
-                                // Token has been verified, as a JWT or an opaque token, possibly involving
-                                // an introspection request.
-                                final TokenCredential tokenCred = request.getToken();
+    @SuppressWarnings("deprecation")
+    private void createSecurityIdentityWithOidcServer(UniEmitter<? super SecurityIdentity> uniEmitter,
+            RoutingContext vertxContext,
+            TokenAuthenticationRequest request, TenantConfigContext resolvedContext, final JsonObject userInfo) {
+        resolvedContext.auth.decodeToken(request.getToken().getToken(),
+                new Handler<AsyncResult<AccessToken>>() {
+                    @Override
```
Comment (cescoffier) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java:173]: on which thread is this called? Are you 100% sure it cannot be the event loop?

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java [hunk 7]
```diff
@@ -81,101 +87,157 @@ public SecurityIdentity get() {
...
+                        if (tokenJson != null) {
+                            OidcUtils.validatePrimaryJwtTokenType(resolvedContext.oidcConfig.token, tokenJson);
+                            JsonObject rolesJson = getRolesJson(vertxContext, resolvedContext, tokenCred, tokenJson,
+                                    userInfo);
+                            try {
+                                SecurityIdentity securityIdentity = validateAndCreateIdentity(vertxContext, tokenCred,
+                                        resolvedContext.oidcConfig,
+                                        tokenJson, rolesJson, userInfo);
+                                if (tokenAutoRefreshPrepared(tokenJson, vertxContext, resolvedContext.oidcConfig)) {
+                                    throw new TokenAutoRefreshException(securityIdentity);
```
Comment (cescoffier) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java:201]: better failing and not throwing.

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java (hunk 6 above)
Comment (cescoffier) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java:173]: where is the blocking call you mentioned earlier?

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java [hunk 8]
```diff
@@ -224,23 +286,62 @@ private static JsonObject getRolesJson(RoutingContext vertxContext, TenantConfig
...
+                        || resolvedContext.oidcConfig.roles.source.orElse(null) == Source.accesstoken)) {
+            final String codeAccessToken = (String) vertxContext.get("access_token");
+            if (OidcUtils.isOpaqueToken(codeAccessToken)) {
+                // remote introspection is required, a blocking call
+                if (BlockingOperationControl.isBlockingAllowed()) {
+                    return Uni.createFrom().emitter(
+                            new Consumer<UniEmitter<? super AccessToken>>() {
+                                @Override
+                                public void accept(UniEmitter<? super AccessToken> uniEmitter) {
+                                    verifyCodeFlowAccessToken(uniEmitter, resolvedContext, codeAccessToken);
```
Comment (cescoffier) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java:302]: again, may be a different thread. assembly and subscription threads different might be different.

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java [hunk 9]
```diff
@@ -224,23 +286,62 @@ private static JsonObject getRolesJson(RoutingContext vertxContext, TenantConfig
...
+                                        }
+                                    });
+                                }
+                            });
+                }
+            } else {
+                return Uni.createFrom().emitter(new Consumer<UniEmitter<? super AccessToken>>() {
+                    @Override
+                    public void accept(UniEmitter<? super AccessToken> uniEmitter) {
+                        verifyCodeFlowAccessToken(uniEmitter, resolvedContext, codeAccessToken);
```
Comment (cescoffier) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java:323]: I don't get why sometimes it must be wrapped on an executor and sometimes not.

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java [hunk 10]
```diff
@@ -266,33 +367,57 @@ public void handle(AsyncResult<AccessToken> event) {
         }
     }
 
-    private static JsonObject getUserInfo(RoutingContext vertxContext, TokenAuthenticationRequest request,
+    private Uni<JsonObject> getUserInfoUni(RoutingContext vertxContext, TokenAuthenticationRequest request,
             TenantConfigContext resolvedContext) {
+        if (resolvedContext.oidcConfig.authentication.isUserInfoRequired()) {
+            if (BlockingOperationControl.isBlockingAllowed()) {
```
Comment (cescoffier) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java:373]: Again, same issue.

**Review by cescoffier — CHANGES_REQUESTED** [review]

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java (hunk 1 above)
Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java:41]: @cescoffier What do you mean ? `AccessToken` is deprecated in Vert.x 3.8.x hence I add to avoid the IDE warnings...

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java (hunk 4 above)
Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java:147]: @cescoffier It is the same executor which Stuart uses [here](https://github.com/quarkusio/quarkus/blob/master/extensions/security/runtime/src/main/java/io/quarkus/security/runtime/QuarkusIdentityProviderManagerImpl.java#L54) so I'm just trying to keep it consistent. Perhaps you'd like to open an issue for Stuart (or I can do it) to replace this executor with `Infrastructure.getDEfaultWorkerPool()` ?

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java (hunk 6 above)
Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java:173]: @cescoffier Yeah; so if it is an `IdToken` which is a case with the code flow - then it is `JWT` => hence in 99% cases it is a local verification; if it is a bearer token (the one coming with HTTP `Authorization`) and it is JWT - the same situation. So it is OK to run it on the IO thread.

But if either token is opaque (binary) then it must be a remote introspection call done internally by `Vert.x` as part of this `decodeToken` call - hence in such cases it is a blocking call.

> where is the blocking call you mentioned earlier?

Right now, if OIDC is configured to refresh the token then it will run in the blocking executor starting from [here](https://github.com/quarkusio/quarkus/blob/master/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java#L62), before the decision to verify the token is made, hence this blocking operation control check

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java (hunk 1 above)
Comment (cescoffier) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java:41]: ah ok, I was referring to the mutiny part.

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java (hunk 4 above)
Comment (cescoffier) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java:147]: it's actually the same pool.

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java (hunk 6 above)
Comment (cescoffier) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java:173]: Vert.x is doing a blocking call and block the event loop? That would be a first. @pmlopes, isn't this hidden?

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java (hunk 3 above)
Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java:139]: @cescoffier I'm just trying to follow the same pattern as Stuart does [here](https://github.com/quarkusio/quarkus/blob/master/extensions/security/runtime/src/main/java/io/quarkus/security/runtime/QuarkusIdentityProviderManagerImpl.java#L54). I can remove these `BlockingOperationContext` checks ?

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java (hunk 6 above)
Comment (cescoffier) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java:173]: I guess that for you, as a user, you don't see the Vert.x gymnastics.

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java (hunk 5 above)
Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java:161]: @cescoffier please see [this comment](https://github.com/quarkusio/quarkus/pull/13257/files#r522163580) below. Unless it is an opaque token it should be fine to have on the IO thread, because it is a JWT token which is verified by a locally cached JWK keys

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java (hunk 8 above)
Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java:302]: @cescoffier please see the question above about this `BlockingOperationControl` check

**Comment by gsmet** [comment]
There seem to be a lot of questions and things to handle in this change.

Should we rather revert the original change for 1.10?

It doesn't look like an easy/obvious fix.

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java (hunk 3 above)
Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java:139]: And yes, it will be gone once that refresh token check becomes Uni async friendy, I'm actually nearly finished in another branch

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java (hunk 9 above)
Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java:323]: @cescoffier Please see above, [this](https://github.com/quarkusio/quarkus/pull/13257/files#r522163580) and [this](https://github.com/quarkusio/quarkus/pull/13257/files#r522168791) comments

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java (hunk 10 above)
Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java:373]: @cescoffier sure, hope the above comments, [this](https://github.com/quarkusio/quarkus/pull/13257/files#r522163580) and [this](https://github.com/quarkusio/quarkus/pull/13257/files#r522168791) ones, will clarify it :-)

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java (hunk 3 above)
Comment (cescoffier) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java:139]: Except that in Stuart's code, the check is done at subscription time. You are doing it at assembly time and hope for the best are subscription:

```java
// This is called at assembly time
Uni.createFrom().emitter(e -> {
   // This is called at subscription time
});
```

The thread used at assembly and subscription time may be different. So if assembly time can block, it does not means you can block at subscription time (or the opposite).

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java (hunk 6 above)
Comment (pmlopes) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java:173]: I've no knowledge on the mentioned code, but I can assure that the calls from vert.x auth to the idp server are asynchronous. There's no `executeBlocking` code on vertx-auth-oauth2`

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java (hunk 8 above)
Comment (cescoffier) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java:302]: I don't believe it is.

**Comment by cescoffier** [comment]
@gsmet we can't. It was broken before. Now we enforce it, as it could literally kill the server at runtime (by blocking an event loop forever).

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java (hunk 6 above)
Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java:174]: HI @cescoffier @pmlopes I think there may be some confusion now, I did not say `Vert.x` does a blocking call, I meant that since `introspection` calls are remote it is better for Quarkus OIDC to run them on the blocking executor, this is why we see so many blocked cases, as in case of the issue this PR is trying to fix, etc

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java (hunk 8 above)
Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java:303]: @cescoffier This code just tries to run the remote operations in the executor, what is not correct about it ?

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java (hunk 6 above)
Comment (cescoffier) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java:174]: @sberyozkin That is a bit confusing. Why "since introspection calls are remote it is better for Quarkus OIDC to run them on the blocking executor"?  Where are these calls? In Vert.x (and so non-blocking) or in some other code?

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java (hunk 8 above)
Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java:303]: @cescoffier never mind, let me think about your `assembly vs subscription clarification` above

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java (hunk 6 above)
Comment (cescoffier) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java:174]: Is it just _easier_ for you to handle the validation? But in this case, how do you make the call (as you may mess up with the event loop used to execute the call and go back to blocking indefinitely).

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java (hunk 3 above)
Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java:140]: Hey @cescoffier I'm on it, I'm learning something new here and at this rate I may qualify as a junior Mutiny bug fixer and start helping @jponge :-)

**Comment by sberyozkin** [comment]
@gsmet It is OK, the original change was good (mostly, see below - but again not related to the current issue) and not related to this issue; the changes are simple once Clement clarified
@cescoffier I've updated the code, resolved those comments which I think I've addressed - reopen if needed please. 
This wrong pattern for checking the blocking context came from my earlier PR (see the updated `OidcRecorder` in this PR) - I wanted to write a good blocking call the way Stuart does it but missed a small detail :-)

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java (hunk 6 above)
Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java:170]: @cescoffier the introspection calls are in Vert.x OAuth2, they are non-blocking (i.e async) but the introspection call is expensive, so we use the Executor for all such remote calls (introspection - starting from this PR, refresh tokens, OIDC connection resolution); IMHO it is OK, perhaps we can revisit it as part of a separate issue, but I believe it is not a bad idea...

Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java:170]: @cescoffier the previous PR where you helped with splitting the tenant context resolution was related to a remote tenant connection resolution which was run on IO thread in one code branch...even though in Vert.x it is an async call

**Review by cescoffier — APPROVED** [review]
The new changeset looks much better.

**Comment by sberyozkin** [comment]
@cescoffier Thanks for your help Clement :-)

**Comment by sberyozkin** [comment]
@gsmet hi Guillaume I'm going to merge this one tomorrow morning, Clement's approval is sufficient but I'll wait just in case Stuart or Pedro may want to add something

**Review by jponge — APPROVED** [review]

**Comment by sberyozkin** [comment]
@jponge thanks
