### PR TITLE
Make REST Client work whether or not SSL is enabled or not in native

### LINKED ISSUE #9342: Add @Patch support for RestClient
When I try to use a PATCH method with the RestClient in none-native mode, We obtain this error

`javax.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request: java.net.ProtocolException: Invalid HTTP method: PATCH
	at org.jboss.resteasy.client.jaxrs.engines.URLConnectionEngine.invoke(URLConnectionEngine.java:63)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:488)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:149)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:112)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
	at com.sun.proxy.$Proxy83.updatePartial(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:149)
	at com.sun.proxy.$Proxy86.updatePartial(Unknown Source)
	at com.example.ExampleRestConnector_27306872b9b9d6a5cde2e5a56fad18628bb23077_Synthetic_ClientProxy.updatePartial(TwinRestConnector_27306872b9b9d6a5cde2e5a56fad18628bb23077_Synthetic_ClientProxy.zig:233)
	at com.example.ExampleController.deleteNode(ExampleController.java:360)
	at com.example.ExampleController.update(ExampleController.java:223)
	at com.example.ExampleController_Subclass.update$$superaccessor11(ExampleController_Subclass.zig:172)
	at com.example.ExampleController_Subclass$$function$$11.apply(ExampleController_Subclass$$function$$11.zig:51)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.hibernate.validator.runtime.interceptor.AbstractMethodValidationInterceptor.validateMethodInvocation(AbstractMethodValidationInterceptor.java:69)
	at io.quarkus.hibernate.validator.runtime.interceptor.MethodValidationInterceptor.validateMethodInvocation(MethodValidationInterceptor.java:17)
	at io.quarkus.hibernate.validator.runtime.interceptor.MethodValidationInterceptor_Bean.intercept(MethodValidationInterceptor_Bean.zig:177)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at com.example.ExampleController_Subclass.update(ExampleController_Subclass.zig:336)
	at com.example.ExampleController_ClientProxy.update(ExampleController_ClientProxy.zig:774)
	at com.exemple.ExampleService.update(ExampleService.java:151)
	at com.exemple.ExampleService_Subclass.update$$superaccessor7(ExampleService_Subclass.zig:208)
	at com.exemple.ExampleService_Subclass$$function$$7.apply(ExampleService_Subclass$$function$$7.zig:51)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.hibernate.validator.runtime.interceptor.AbstractMethodValidationInterceptor.validateMethodInvocation(AbstractMethodValidationInterceptor.java:69)
	at io.quarkus.hibernate.validator.runtime.jaxrs.JaxrsEndPointValidationInterceptor.validateMethodInvocation(JaxrsEndPointValidationInterceptor.java:32)
	at io.quarkus.hibernate.validator.runtime.jaxrs.JaxrsEndPointValidationInterceptor_Bean.intercept(JaxrsEndPointValidationInterceptor_Bean.zig:57)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at com.exemple.ExampleService_Subclass.update(ExampleService_Subclass.zig:78)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:167)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:621)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:487)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:437)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:362)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:439)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:400)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:374)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:67)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:488)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:259)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:160)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:362)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:163)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:245)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:123)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:36)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:87)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
Caused by: java.net.ProtocolException: Invalid HTTP method: PATCH
	at java.base/java.net.HttpURLConnection.setRequestMethod(HttpURLConnection.java:487)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.setRequestMethod(HttpURLConnection.java:570)
	at org.jboss.resteasy.client.jaxrs.engines.URLConnectionEngine.createConnection(URLConnectionEngine.java:176)
	at org.jboss.resteasy.client.jaxrs.engines.URLConnectionEngine.invoke(URLConnectionEngine.java:56)
	... 68 common frames omitted
09:52:29.174 [executor-thread-1] ERROR o.jboss.resteasy.resteasy_jaxrs.i18n - RESTEASY002010: Failed to execute
javax.ws.rs.WebApplicationException: HTTP 400 Bad Request
	at com.exemple.ExampleService.update(ExampleService.java:154)
	at com.exemple.ExampleService_Subclass.update$$superaccessor7(ExampleService_Subclass.zig:208)
	at com.exemple.ExampleService_Subclass$$function$$7.apply(ExampleService_Subclass$$function$$7.zig:51)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.hibernate.validator.runtime.interceptor.AbstractMethodValidationInterceptor.validateMethodInvocation(AbstractMethodValidationInterceptor.java:69)
	at io.quarkus.hibernate.validator.runtime.jaxrs.JaxrsEndPointValidationInterceptor.validateMethodInvocation(JaxrsEndPointValidationInterceptor.java:32)
	at io.quarkus.hibernate.validator.runtime.jaxrs.JaxrsEndPointValidationInterceptor_Bean.intercept(JaxrsEndPointValidationInterceptor_Bean.zig:57)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at com.exemple.ExampleService_Subclass.update(ExampleService_Subclass.zig:78)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:167)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:621)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:487)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:437)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:362)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:439)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:400)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:374)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:67)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:488)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:259)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:160)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:362)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:163)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:245)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:123)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:36)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:87)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)`

I created a demo to reproduce the issue

https://github.com/survivant/quarkus-k8s-hello
HelloExampleTest.testPatch

@PATCH
@Produces("application/merge-patch+json")
@Consumes("application/merge-patch+json")
@Path("/nodes/{id}")
Node updatePartial(@PathParam("id") UUID id, JsonMergePatch patch);

here the code that is used in the other service that is in Spring

@PatchMapping(path = "/nodes/{id}", consumes = "application/merge-patch+json")
Node updatePartial(@PathVariable UUID id, @RequestBody JsonMergePatch patch);

I'm using Quarkus 1.4.2.Final

There is a workaround, is to use : quarkus.ssl.native=true

### PR DESCRIPTION
**Pull request by geoand**
This is done in order to enable the use of Apache HTTP Client in all
cases where the REST Client is used.
This enables us to drop the fallback to URLConnection which is rather limited

Fixes: #9342

~~Requires: https://github.com/resteasy/Resteasy/pull/2431~~

~~PR is a draft because without the RESTEasy fix this doesn't make sense.~~ (after talking with @gsmet it became clear to me that the fix in RESTEasy is not necessary)

### CODE REVIEW

**Comment by geoand** [comment]
I tested this along with https://github.com/quarkusio/quarkus/pull/9773 performing the following scenaria:

* rest-client IT using `quarkus.ssl.native=false`
* rest-client IT without setting `quarkus.ssl.native`
* rest-client quickstart using `quarkus.ssl.native=false` and `org.acme.rest.client.CountriesService/mp-rest/url=http://restcountries.eu/rest`
* rest-client quickstart using `quarkus.ssl.native=false` and `org.acme.rest.client.CountriesService/mp-rest/url=https://restcountries.eu/rest` (this obviously fails with a proper message about SSL not being enabled for the native image)
* rest-client IT without setting `quarkus.ssl.native`  and `org.acme.rest.client.CountriesService/mp-rest/url=http://restcountries.eu/rest`
* rest-client IT without setting `quarkus.ssl.native`  and `org.acme.rest.client.CountriesService/mp-rest/url=shttp://restcountries.eu/rest`

**Comment by geoand** [comment]
cc @gsmet @kenfinnigan

File: extensions/rest-client/runtime/src/main/java/io/quarkus/restclient/runtime/RestClientBase.java [hunk 1]
```diff
@@ -77,6 +80,12 @@ private void configureSsl(RestClientBuilder builder) {
         if (maybeHostnameVerifier.isPresent()) {
             registerHostnameVerifier(maybeHostnameVerifier.get(), builder);
         }
+
+        // we need to push a disabled SSL context when SSL has been disabled
+        // because otherwise Apache HTTP Client will try to initialize one and will fail
+        if (ImageInfo.inImageRuntimeCode() && !SslContextConfiguration.isSslNativeEnabled()) {
```
Comment (kenfinnigan) [inline extensions/rest-client/runtime/src/main/java/io/quarkus/restclient/runtime/RestClientBase.java:86]: What does `ImageInfo.inImageRuntimeCode()` return if it's running on OpenJDK?

Comment (geoand) [reply extensions/rest-client/runtime/src/main/java/io/quarkus/restclient/runtime/RestClientBase.java:86]: It returns `false`. We use that in a couple more places in Quarkus as well (for example: https://github.com/quarkusio/quarkus/blob/f89650be537d9f26c54c06c960b3e258bac2fe74/core/runtime/src/main/java/io/quarkus/runtime/ApplicationLifecycleManager.java#L157)

Comment (kenfinnigan) [reply extensions/rest-client/runtime/src/main/java/io/quarkus/restclient/runtime/RestClientBase.java:86]: Fair enough, I was half expecting it to majorly fail if it wasn't on GraalVM JDK

**Comment by kenfinnigan** [comment]
Looks good to me

File: extensions/rest-client/runtime/src/main/java/io/quarkus/restclient/runtime/RestClientBase.java (hunk 1 above)
Comment (geoand) [reply extensions/rest-client/runtime/src/main/java/io/quarkus/restclient/runtime/RestClientBase.java:86]: Under the hood it just checks for a system property, so it's not that smart :)

**Comment by gsmet** [comment]
How is the RESTEasy patch required? It just looks like some cleanup to me?

**Review by gsmet — APPROVED** [review]
Looks good. I'm wondering if we should move the `DisabledSslContext` elsewhere though?

Making it a proper class would be a good first step. It can stay in the `.graal.` package as I suppose it will only be useful in a GraalVM environment.

**Comment by geoand** [comment]
@gsmet because without the RESTEasy patch, URLConnection is still the default. So this basically makes Apache HttpClient work OOTB even when ssl is disabled in native.

Good idea about moving the class, I'll do that

**Comment by geoand** [comment]
PR updated as per review comment

**Comment by gsmet** [comment]
Is it? It seems it's only the case if `SSL_ENABLED` is false and it's true by default. Or am I missing something?

**Comment by geoand** [comment]
The things are now `Apache HttpClient` only comes into play for the `REST Client` iff `quarkus.ssl.native=true`. When it's left unset, `SSL_ENABLED` is still false, so URLConnection is still used.

**Comment by geoand** [comment]
@asoldano can you ping me when you release a new 4.5.x version which contains the small fix I added?

Thanks

**Comment by gsmet** [comment]
> The things are now Apache HttpClient only comes into play for the REST Client iff quarkus.ssl.native=true. When it's left unset, SSL_ENABLED is still false (so false by default), so URLConnection is still used.

Can we discuss that when you're back from PTO. I fail to see how `SSL_ENABLED` is false by default given: https://github.com/resteasy/Resteasy/pull/2431/files#diff-14ad0b8f47bf5f23be58cd4a2cb1cf96L70 .

**Comment by geoand** [comment]
Yup, let's discuss tomorrow

**Comment by geoand** [comment]
Failures are related, I'll have to take a look

**Comment by geoand** [comment]
Fixed failing tests (and also did some manual re-testing), so this should be ready for merge

**Comment by geoand** [comment]
TCKs are failing in timeout tests... I have no idea what that's all about

**Comment by geoand** [comment]
@kenfinnigan I had to disable the Timeout tests in the TCK because we were failing at https://github.com/eclipse/microprofile-rest-client/blob/1.4.1/tck/src/main/java/org/eclipse/microprofile/rest/client/tck/timeout/TimeoutTest.java#L65 (the requests were taking exactly as much time as the limit).

I saw that that in newer versions of the TCK the time cushion is configurable.
