### PR TITLE
Properly support `FAIL_ON_UNKNOWN_PROPERTIES` in reflection-free deserialisers

### LINKED ISSUE #53408: [Reflection-free Jackson deserialisers] ClassCast exceptions w/ non-standard collections and ignoring FAIL_ON_UNKNOWN_PROPERTIES
### Describe the bug

The build-time generated reflection-free Jackson deserialisers have two bugs that cause runtime failures. These are regressions vs the standard reflection-based deserialisers (all tests pass when the flag is disabled).

This is particularly relevant since `enable-reflection-free-serializers` will become the default in 3.35 (#53161).

Reproducer: https://github.com/lloydmeta/quarkus-jackson-reflection-free-bug

Disabling the flag makes everything pass: https://github.com/lloydmeta/quarkus-jackson-reflection-free-bug/pull/3

The bugs are as follows

1. Non-standard collection types lose generic type parameters during deserialization

    It seems when a REST endpoint accepts a request body with a collection field whose declared type isn't one of names in [`JacksonCodeGenerator.registerTypeToBeGenerated()`](https://github.com/quarkusio/quarkus/blob/15e70676b49217cc1f5abe191878d96233594f9b/extensions/resteasy-reactive/rest-jackson/deployment/src/main/java/io/quarkus/resteasy/reactive/jackson/deployment/processor/JacksonCodeGenerator.java#L179-L207), the generated deserialiser loses the generic type parameter (everything else falls through to `FieldKind.OBJECT`?), and the generated code calls `context.readTreeAsValue(jsonNode, RawType.class)` with no generic info.

    This doesn't just affect third-party collections like Guava's `ImmutableList` / `ImmutableSet` - it also affects standard JDK types like `LinkedList` and `LinkedHashSet`.

    Elements end up as `LinkedHashMap` (for object types) or `String` (for `@JsonValue` wrappers) instead of the expected typed objects, and result in cast errors at runtime.

    It's a bit more of a real issue for often-used Guava types that offer niceness like immutability though.

2. Unknown JSON fields silently ignored (`FAIL_ON_UNKNOWN_PROPERTIES` not respected)

    AFAICT, the generated deserialiser in [`JacksonDeserializerFactory.deserializeObjectFields()`](https://github.com/quarkusio/quarkus/blob/main/extensions/resteasy-reactive/rest-jackson/deployment/src/main/java/io/quarkus/resteasy/reactive/jackson/deployment/processor/JacksonDeserializerFactory.java#L269-L286) iterates JSON fields via a `StringSwitch`. When a field name doesn't match any known property, it falls through silently, with check `FAIL_ON_UNKNOWN_PROPERTIES`. 

### Expected behavior

All deserialised types should behave identically whether using reflection-based or reflection-free deserialisers:

1. **Bug 1**: A `POST` endpoint accepting e.g. `record BatchRequest(LinkedList<Item> items)` should deserialise elements as the correct polymorphic types. Iterating the collection and pattern-matching on elements should work without `ClassCastException`. Same for `@JsonValue` wrapper records inside collections...
2. **Bug 2**: When `quarkus.jackson.fail-on-unknown-properties=true`, sending `{"name": "world", "evil": "data"}` to an endpoint whose DTO only has a `name` field should return 400 with an unrecognised field error, not silently accept it.

### Actual behavior

1. **Bug 1**: Elements in non-standard collections are deserialised as raw types. Accessing them throws `ClassCastException`:

    ```
    java.lang.ClassCastException: class java.util.LinkedHashMap cannot be cast to class com.beachape.dto.Item
    ```

    ```
    java.lang.ClassCastException: class java.lang.String cannot be cast to class com.beachape.dto.Token
    ```

    The same payloads work fine when the field is declared as `List<Item>` or `Set<Token>`.

2. **Bug 2**: Sending `{"name": "world", "evil": "data"}` to an endpoint expecting only `name` returns 200 instead of 400. The unknown field `evil` is silently swallowed.

### How to Reproduce?

Reproducer: https://github.com/lloydmeta/quarkus-jackson-reflection-free-bug

```bash
git clone https://github.com/lloydmeta/quarkus-jackson-reflection-free-bug.git
cd quarkus-jackson-reflection-free-bug
./gradlew clean test
```

7 tests, 5 fail. The 2 control cases using `List<T>` and `Set<T>` pass:

### Output of `uname -a` or `ver`

Darwin Mac-M2Pro 25.4.0 Darwin Kernel Version 25.4.0: Thu Mar 19 19:31:17 PDT 2026; root:xnu-12377.101.15~1/RELEASE_ARM64_T6020 arm64

### Output of `java -version`

openjdk 25.0.1 2025-10-21

### Quarkus version or git rev

3.34.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

9.4.1

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mariofusco**
- Fixes: #53408

### CODE REVIEW

File: extensions/resteasy-reactive/rest-jackson/deployment/src/main/java/io/quarkus/resteasy/reactive/jackson/deployment/processor/JacksonCodeGenerator.java [hunk 1]
```diff
@@ -176,6 +177,10 @@ public boolean isGeneric() {
         }
     }
 
+    private static final DotName COLLECTION_NAME = DotName.createSimple("java.util.Collection");
+    private static final DotName SET_NAME = DotName.createSimple("java.util.Set");
+    private static final DotName MAP_NAME = DotName.createSimple("java.util.Map");
```
Comment (geoand) [inline extensions/resteasy-reactive/rest-jackson/deployment/src/main/java/io/quarkus/resteasy/reactive/jackson/deployment/processor/JacksonCodeGenerator.java]: There is no reason to use magic strings here

File: extensions/resteasy-reactive/rest-jackson/deployment/src/main/java/io/quarkus/resteasy/reactive/jackson/deployment/processor/JacksonDeserializerFactory.java [hunk 2]
```diff
@@ -285,8 +287,39 @@ private boolean deserializeObjectFields(DeserializationData deserData, ResultHan
...
+                    ofMethod(String.class, "concat", String.class, String.class),
+                    trueBranch.load("Unrecognized field \""),
+                    trueBranch.invokeVirtualMethod(
+                            ofMethod(String.class, "concat", String.class, String.class),
+                            trueBranch.checkCast(fieldName, String.class),
+                            trueBranch.load("\"")));
+            ResultHandle exception = trueBranch.newInstance(
+                    MethodDescriptor.ofConstructor(JsonMappingException.class, String.class), message);
+            trueBranch.throwException(exception);
+        });
```
Comment (geoand) [inline extensions/resteasy-reactive/rest-jackson/deployment/src/main/java/io/quarkus/resteasy/reactive/jackson/deployment/processor/JacksonDeserializerFactory.java:324]: Please add an example in the comments of what this is supposed to generate

File: extensions/resteasy-reactive/rest-jackson/deployment/src/test/java/io/quarkus/resteasy/reactive/jackson/deployment/test/SimpleJsonResource.java [hunk 3]
```diff
@@ -597,4 +603,36 @@ public ObjectReader apply(ObjectMapper objectMapper, Type type) {
...
+    }
+
+    public record GreetingRequest(@JsonProperty("name") String name) {
+    }
+
+    @POST
+    @Path("/greeting")
+    public String greeting(GreetingRequest request) {
+        return "{\"message\":\"Hello " + request.name() + "\"}";
+    }
```
Comment (geoand) [inline extensions/resteasy-reactive/rest-jackson/deployment/src/test/java/io/quarkus/resteasy/reactive/jackson/deployment/test/SimpleJsonResource.java]: This test feels a lot more complex than it could be for testing the unknown property handling...

Comment (mariofusco) [reply extensions/resteasy-reactive/rest-jackson/deployment/src/test/java/io/quarkus/resteasy/reactive/jackson/deployment/test/SimpleJsonResource.java]: Sorry, I'm not understanding your comment here, do you have any suggestion to improve/simplify?

Comment (geoand) [reply extensions/resteasy-reactive/rest-jackson/deployment/src/test/java/io/quarkus/resteasy/reactive/jackson/deployment/test/SimpleJsonResource.java]: Wouldn't having a test that uses :

```java
public record User(String name, String email) {}
```

and the json being:

```json
{
    "name":  "Alice",
    "email": "alice@example.com",
    "role":  "admin"         
}
```

result in Jackson failing to deserialize? 

Why do we need all the complexity of ` @JsonTypeInfo` and `@JsonSubTypes`?

Comment (mariofusco) [reply extensions/resteasy-reactive/rest-jackson/deployment/src/test/java/io/quarkus/resteasy/reactive/jackson/deployment/test/SimpleJsonResource.java]: Ah ok, there is some confusion here :) The test for the unknown field (which is the one I thought you were referring to) does something practically identical to what you suggesting using the record

`public record GreetingRequest(@JsonProperty("name") String name) {}`

The one with `@JsonTypeInfo` and subtypes is for the first problem reported in the bug report, the deserialization of non standard Java-collection. I copied it as it was from the original reproducer, but yes, It could be simplified, I will do so.

Comment (geoand) [reply extensions/resteasy-reactive/rest-jackson/deployment/src/test/java/io/quarkus/resteasy/reactive/jackson/deployment/test/SimpleJsonResource.java]: Thanks!

File: extensions/resteasy-reactive/rest-jackson/deployment/src/main/java/io/quarkus/resteasy/reactive/jackson/deployment/processor/JacksonDeserializerFactory.java (hunk 2 above)
Comment (mariofusco) [reply extensions/resteasy-reactive/rest-jackson/deployment/src/main/java/io/quarkus/resteasy/reactive/jackson/deployment/processor/JacksonDeserializerFactory.java:324]: Done.

**Comment by mariofusco** [comment]
@geoand I should have fixed all your suggestions, please give a second look.

**Review by geoand — APPROVED** [review]
Thanks!

**Comment by mariofusco** [comment]
Yes I wrote in my original commit message "Make reflection-free Jackson deserialisers to support non-standard collection types and FAIL_ON_UNKNOWN_PROPERTIES" both problems are fixed.
