### PR TITLE
Handle local extension project dependency in gradle plugin

### LINKED ISSUE #20953: Cannot build Quarkus extension anymore after upgrading from 2.2.3.Final to 2.3.1.Final or later
### Describe the bug

I'm the author of [JobRunr](https://github.com/jobrunr/jobrunr), a distributed job scheduler which integrates with Quarkus.

During monthly maintenance, I try to update all the dependencies of JobRunr. When I try upgrading Quarkus from 2.2.3.Final to 2.3.1.Final or later, my extension will not build anymore with the following exception (I'm using gradle).

Execution failed for task ':framework-support:jobrunr-quarkus-extension:tests:quarkusGenerateCode'.
> Could not resolve all dependencies for configuration ':framework-support:jobrunr-quarkus-extension:tests:quarkusDeploymentConfiguration'.

### Expected behavior

Build succeeds

### Actual behavior

Build fails

### How to Reproduce?

1. Checkout https://github.com/jobrunr/jobrunr
2. Do a global search in the IDE for '**2.2.3.Final**' (latest working version) and replace with **'2.4.0.Final'**.
3. Run the ./gradlew build (**or a lot faster:** use the gradle plugin of the IDE to build everything under :framework-support:jobrunr-quarkus-extension)

### Output of `uname -a` or `ver`

Linux rdehuyss-laptop 5.11.0-37-generic #41~20.04.2-Ubuntu SMP Fri Sep 24 09:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.11" 2021-04-20 OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04) OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.3.1.Final / 2.4.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by glefloch**
This branch introduce `LocalExtensionDependency` that allows to reference a module from multi-module project as extension. 

The only limitation is based on the name of the deployment module. I look for a project that match the name of the deployment artifact. if it does not exist, I use the default `deployment` name.

close #20953

### CODE REVIEW

**Comment by geoand** [comment]
The CI failures seem related

**Comment by glefloch** [comment]
Yes definitely, I had a cache issue on my machine that make ci ok.. I’m working on it.

**Comment by aloubyansky** [comment]
I am wondering whether it can be done simpler. The deployment module will appear as the application root, right? It will depend on the runtime module which should be recognized as an extension, pointing back to the deployment module as its deployment counterpart. Wouldn't it be enough to figure out the extension artifacts?

**Comment by glefloch** [comment]
In this case, we have both an application and extension modules in the same multi-module project. if we make sure the `jar` of the `deployment` module is available referencing artifact should work. 

However, in a project where the deployment module would be the application root, we will need the deployment jar to be built before tests run. This is not the case by default but I think we can add a dependency between the `test` task and the `jar` task. 

I will give it a try.

**Comment by aloubyansky** [comment]
We should not need the JAR though. As long as all the extension metadata has been generated, we should be good. We should be able to pick it up from the build directories instead of the JAR.

**Comment by glefloch** [comment]
Yes, that's what I tried to do here. The main issue is that when resolving a project dependency, gradle points to an un-existing jar.. 

In this case we have the following module structure: 

```
root
   application (here we have a dependency to the runtime module)
   runtime
   deployment
```

The `runtime` module is a project dependency (`implementation project(":runtime")`) of the `application` module. 
By default, the `compileClasspath` resolution of the `application` module will point us to jars even for the `runtime` dependency (which does not exists yet). That's why we need to identify this as a `ProjectModuleComponent` in order to access extension meta data in `build/resources/main/META-INF` using a `Project` reference. 

Once we have this, when building the deployment classpath, we cannot reference the jar from the `quarkus-extension.properties` file as it is not installed in the local maven repo (nor even built). 
In order to reference the `deployment` module, I used a project reference `implementationDeployment project(':deployment')`. And again when resolving the deployment classpath, gradle will point us to the `deployment` jar file as the artifact file whereas it does not exists. 
However, we can identify that this a `ProjectComponentModule` and load the output classe directories.

**Comment by aloubyansky** [comment]
Well, the application's build has to depend on the deployment module but not as a regular dependency to avoid on the classpath. In Maven we use a dependency on the `pom` artifact excluding all the deps.
In Gradle, I guess, it has to be task-level dependency.

**Comment by glefloch** [comment]
Yes, there is this dependency here `https://github.com/quarkusio/quarkus/pull/21303/files#diff-809da42d27d235f761fc024f19d2015cac4d1dda4ce277b387037f04284a3846R21`.

Maybe we can depend on the `jar` task. That should remove the update in the application model, but we still need to use local project when building the classpath from my point of view.

**Comment by aloubyansky** [comment]
Sure, I just think we should relying on the `deployment` suffix.

**Comment by aloubyansky** [comment]
Or the `deployment` module name.

File: devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/dependency/LocalExtensionDependency.java [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+            AppArtifactCoords deploymentModule,
+            List<Dependency> conditionalDependencies, List<ArtifactKey> dependencyConditions) {
+        super(extensionId, deploymentModule, conditionalDependencies, dependencyConditions);
+        this.localProject = localProject;
+    }
+
+    public String findDeploymentModulePath() {
+
+        String deploymentModuleName = DEFAULT_DEPLOYMENT_PATH_SUFFIX;
+        if (localProject.getParent().findProject(deploymentModule.getArtifactId()) != null) {
```
Comment (aloubyansky) [inline devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/dependency/LocalExtensionDependency.java:28]: In which case could this return null?

Comment (glefloch) [reply devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/dependency/LocalExtensionDependency.java:28]: By convention the deployment module is called `deployment` but it can be whatever other name. Here I try to look for a project named with the artifact id. If it’s null I fallback to the conventional `deployment`. I could look for the deployment project first. Actually, are `runtime` / `deployment` module names mandatory?

Comment (aloubyansky) [reply devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/dependency/LocalExtensionDependency.java:28]: No, they shouldn't be.

Comment (aloubyansky) [reply devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/dependency/LocalExtensionDependency.java:28]: Is `deploymentModule.getArtifactId()` ever null or empty? if `localProject.getParent().findProject(deploymentModule.getArtifactId()` returns null, what does it mean?

Comment (glefloch) [reply devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/dependency/LocalExtensionDependency.java:28]: `deploymentModule.getArtifactId()` should never be null (however, it can be null if the `deployment-artifact` property is missing from `quarkus-extension.properties` files but that would mean the extension is corrupted).

if `localProject.getParent().findProject(deploymentModule.getArtifactId()` returns null, this means that in the current multi-module project, there is no project named using the artifact id (which may be always the case as we promote a module name `deployment` whereas the deployment artifact name is more something like `my-extension-deployment`).

Comment (aloubyansky) [reply devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/dependency/LocalExtensionDependency.java:28]: It sounds like if `deploymentModule.getArtifactId()` is null we should just throw an error.

>if localProject.getParent().findProject(deploymentModule.getArtifactId() returns null, this means that in the current multi-module project, there is no project named using the artifact id (which may be always the case as we promote a module name deployment whereas the deployment artifact name is more something like my-extension-deployment).

Could we have `deploymentModule.getModuleName()`? Or figure it out in some other way? It's ok to have a default for the module name but we also shouldn't be only guessing here. `deployment` as the default module name is reasonable, imo, btw.

Comment (glefloch) [reply devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/dependency/LocalExtensionDependency.java:28]: If we add that in the `META-INF/quarkus-extension.properties` file then yes. But it will requires the extension to use the `io.quarkus.extension` plugin. 
I though of adding a configuration entry in the `io.quarkus` plugin that will be limited to multi-module project with one extension. For example, it won't work with the following structure:

```
root
  application
  ext-a
    runtime
    deployment
  ext-b
    runtime
    deployment

```

Comment (aloubyansky) [reply devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/dependency/LocalExtensionDependency.java:28]: Ok, I think we can merge this for now. But we should look into making it more reliable.
E.g. we could check whether modules apply `io.quarkus.extension` plugin, deployment modules also contain extension metadata, e.g. `META-INF/quarkus-build-steps.list`. Couldn't we find which module produced a given artifact in the project (we know what the deployment artifact is, we just need to find its origin module)?

**Review by aloubyansky — APPROVED** [review]
