### PR TITLE
fix(#7712): S2i build no longer renames artifacts

### LINKED ISSUE #7712: presence of `quarkus-container-image-s2i` extension causes wrong `java -jar` argument in pod spec
**Describe the bug**

I use the `quarkus-container-image-s2i` extension to be able to customize the S2I base image for my application. I then `oc apply -f target/kubernetes/openshift.yml` and `oc start-build <app name> --from-dir=target` to deploy my application, which is the usual S2I binary build flow.

However, the mere presence of this extension causes a significant difference in how the Kubernetes `Deployment` (or OpenShift `DeploymentConfig`) is generated. If the S2I extension is present, the pod spec template contains a full `java -jar ... -cp ...` command. This command seems to always read `java -jar /deployments/application-runner.jar ...`, even though the JAR itself is _not_ called `application-runner.jar`. In case of OpenShift, an env var `JAVA_APP_JAR` is also generated, and its value is the correct path to the JAR.

This is probably tailored towards the S2I extension building the image itself, but that is a severely restrictive requirement.

Is generating the `java -jar ... -cp ...` command really necessary? The JDK base images typically know how to use a single JAR in `/deployments` (which already happens if I don't include the `quarkus-container-image-s2i` extension).

**Expected behavior**
I can use the generated `target/kubernetes/openshift.yml` as is, without change.

**Actual behavior**
When the `quarkus-container-image-s2i` extension is present, the generated `target/kubernetes/openshift.yml` uses extraneous configuration that prevents the deployment from succeeding.

**To Reproduce**
1. Add the `quarkus-kubernetes` and `quarkus-container-image-s2i` extensions.
2. Run `mvn clean package -DskipTests`.
3. See `target/kubernetes/*.yml`.

**Configuration**
```properties
quarkus.kubernetes.deployment-target=kubernetes,openshift
quarkus.s2i.base-jvm-image=registry.access.redhat.com/openjdk/openjdk-11-rhel7
```

**Additional context**
Compared to 1.3.0.Alpha2, this is actually a regression.

### PR DESCRIPTION
**Pull request by iocanel**
Fixes: #7712 #7766 #7740

This pull request changes the way that the artifact is handled during the s2i build process.

- **The artifact is no longer renamed**.
- The user is able to specify the target directory and or the target filename (if the s2i builder image changes the name).
- The artifact name that is used in the manifests comes from `JarBuildItem` / `NativeBuildItem` unless the user specifies something else (see above).

### CODE REVIEW

**Comment by iocanel** [comment]
CC @Ladicek @maxandersen

**Comment by iocanel** [comment]
Found some issues with the PR related to native mode ... 
I am on it.

**Comment by maxandersen** [comment]
as this changes the behavior of kubernetes/openshift setup best to get this fixed before final.

File: extensions/container-image/container-image-s2i/deployment/src/main/java/io/quarkus/container/image/s2i/deployment/S2iProcessor.java [hunk 1]
```diff
@@ -102,11 +109,30 @@ public void s2iRequirementsNative(S2iConfig s2iConfig,
...
             BuildProducer<BaseImageInfoBuildItem> builderImageProducer,
             BuildProducer<KubernetesCommandBuildItem> commandProducer) {
 
+        boolean usingDefaultBuilder = ImageUtil.getRepository(S2iConfig.DEFAULT_BASE_NATIVE_IMAGE)
+                .equals(ImageUtil.getRepository(s2iConfig.baseNativeImage));
+        String outputNativeBinaryFileName = nativeImage.getPath().getFileName().toString();
+
+        String nativeBinaryFileName = null;
+
+        //The default s2i builder for native builds, renames the native binary.
```
Comment (maxandersen) [inline extensions/container-image/container-image-s2i/deployment/src/main/java/io/quarkus/container/image/s2i/deployment/S2iProcessor.java]: wait - so our own native s2i builder goes an rename to something even more different ?

**Comment by geoand** [comment]
I would like @Ladicek to test this if possible.

I agree with @maxandersen that we need this in for `Final` from a usability perspective. Moreover it changes the s2i configuration which we really want to do before the `Final` is out to avoid unnecessary breaking changes down the line

File: extensions/container-image/container-image-s2i/deployment/src/main/java/io/quarkus/container/image/s2i/deployment/S2iProcessor.java (hunk 1 above)
Comment (Ladicek) [reply extensions/container-image/container-image-s2i/deployment/src/main/java/io/quarkus/container/image/s2i/deployment/S2iProcessor.java]: I also think this shouldn't happen. It was probably a shortcut to make the `run` script easier. If anything, it shouldn't be a rename but a symlink.

**Review by Ladicek — APPROVED** [review]
This seems to work fine from my perspective. I don't test native binaries in OpenShift yet, but for the JVM mode, this is OK.

(I'm still not sure why we need the full `java ...` cmdline, but it can't hurt either, so I'm fine with that.)

**Comment by geoand** [comment]
Thanks for checking @Ladicek

File: extensions/container-image/container-image-s2i/deployment/src/main/java/io/quarkus/container/image/s2i/deployment/S2iConfig.java [hunk 2]
```diff
@@ -38,18 +40,32 @@
...
      */
-    @ConfigItem(defaultValue = "/deployments/application${quarkus.package.runner-suffix}.jar")
-    public String jarPath;
+    @ConfigItem(defaultValue = "/deployments/")
+    public String jarDirectory;
 
     /**
-     * The path to where the native binary is added during the assemble phase.
+     * The resulting filename of the jar in the s2i image.
+     * This option may be used of the selected s2i image uses a fixed name for the jar.
```
Comment (geoand) [inline extensions/container-image/container-image-s2i/deployment/src/main/java/io/quarkus/container/image/s2i/deployment/S2iConfig.java]:
```suggestion
     * This option may be used if the selected s2i image uses a fixed name for the jar.
```

File: extensions/container-image/container-image-s2i/deployment/src/main/java/io/quarkus/container/image/s2i/deployment/S2iConfig.java [hunk 3]
```diff
@@ -38,18 +40,32 @@
...
+     */
+    @ConfigItem
+    public Optional<String> jarFileName;
+
+    /**
+     * The directory where the native binary is added during the assemble phase.
      * This is dependant on the s2i image and should be supplied if a non default image is used.
```
Comment (geoand) [inline extensions/container-image/container-image-s2i/deployment/src/main/java/io/quarkus/container/image/s2i/deployment/S2iConfig.java]:
```suggestion
     * This is dependant on the s2i image and should be supplied if a non-default image is used.
```

File: extensions/container-image/container-image-s2i/deployment/src/main/java/io/quarkus/container/image/s2i/deployment/S2iConfig.java [hunk 4]
```diff
@@ -38,18 +40,32 @@
...
      */
-    @ConfigItem(defaultValue = "/home/quarkus/application")
-    public String nativeBinaryPath;
+    @ConfigItem(defaultValue = "/home/quarkus/")
+    public String nativeBinaryDirectory;
+
+    /**
+     * The resulting filename of the native binary in the s2i image.
+     * This option may be used of the selected s2i image uses a fixed name for the native binary.
```
Comment (geoand) [inline extensions/container-image/container-image-s2i/deployment/src/main/java/io/quarkus/container/image/s2i/deployment/S2iConfig.java]:
```suggestion
     * This option may be used if the selected s2i image uses a fixed name for the native binary.
```

**Review by geoand — COMMENTED** [review]
Added some minor comments about the config property javadoc (which should be fixed since they end up in the docs)

**Comment by iocanel** [comment]
> This seems to work fine from my perspective. I don't test native binaries in OpenShift yet, but for the JVM mode, this is OK.

It's the ubi quarkus native binary image that does rename the artifact. It doesn't affect JVM mode.

> (I'm still not sure why we need the full `java ...` cmdline, but it can't hurt either, so I'm fine with that.)

Because there is no guarantee that the s2i builder image the user selects will support `JAVA_APP_JAR` etc.

File: extensions/container-image/container-image-s2i/deployment/src/main/java/io/quarkus/container/image/s2i/deployment/S2iProcessor.java (hunk 1 above)
Comment (iocanel) [reply extensions/container-image/container-image-s2i/deployment/src/main/java/io/quarkus/container/image/s2i/deployment/S2iProcessor.java]: I logged an issue: https://github.com/quarkusio/quarkus-images/issues/58
Until the issue is address we need this, so I'll mark this discussion as resolved.

**Comment by geoand** [comment]
Please squash the commits when you are done :)

**Comment by iocanel** [comment]
> Please squash the commits when you are done :)

done

**Review by geoand — APPROVED** [review]
LGTM

**Comment by Ladicek** [comment]
> > (I'm still not sure why we need the full `java ...` cmdline, but it can't hurt either, so I'm fine with that.)
> 
> Because there is no guarantee that the s2i builder image the user selects will support `JAVA_APP_JAR` etc.

I have actually noticed that it _might_ hurt, or at least be suboptimal. I filed #7766 for that.

**Comment by gsmet** [comment]
@geoand please don't assign PRs to 1.3.0.Final. I do it when I backport things.

As long as they are not backported, they don't end up in 1.3.0.Final as we already have a branch.

Thanks!

**Comment by geoand** [comment]
So the milestone should be `1.4.0.Final`?

**Comment by iocanel** [comment]
Added a couple more commits that fixes: #7766  and #7740. 
Also it changes the default s2i java base image to `openjdk`.

**Comment by geoand** [comment]
Another looks from the s2i master @Ladicek would be great :)

File: extensions/container-image/container-image-s2i/deployment/src/main/java/io/quarkus/container/image/s2i/deployment/S2iConfig.java [hunk 5]
```diff
@@ -11,7 +11,7 @@
 @ConfigRoot(phase = ConfigPhase.BUILD_TIME)
 public class S2iConfig {
 
-    public static final String DEFAULT_BASE_JVM_IMAGE = "fabric8/s2i-java:2.3";
+    public static final String DEFAULT_BASE_JVM_IMAGE = "registry.access.redhat.com/openjdk/openjdk-11-rhel7";
```
Comment (Ladicek) [inline extensions/container-image/container-image-s2i/deployment/src/main/java/io/quarkus/container/image/s2i/deployment/S2iConfig.java]: I'm not sure if this is a good idea, purely from "legal" point of view. This is RHEL, after all. Too bad UBI Java isn't ready yet :-(

Comment (geoand) [reply extensions/container-image/container-image-s2i/deployment/src/main/java/io/quarkus/container/image/s2i/deployment/S2iConfig.java]: @maxandersen any idea about this?

File: extensions/container-image/container-image-s2i/deployment/src/main/java/io/quarkus/container/image/s2i/deployment/S2iBaseJavaImage.java [hunk 6]
```diff
@@ -0,0 +1,64 @@
...
+package io.quarkus.container.image.s2i.deployment;
+
+import java.util.Optional;
+
+import io.quarkus.container.image.deployment.util.ImageUtil;
+
+public enum S2iBaseJavaImage {
+
+    FABRIC8("fabric8/s2i-java:2.3", "JAVA_MAIN_CLASS", "JAVA_APP_JAR", "JAVA_LIB_DIR", "JAVA_CLASSPATH", "JAVA_OPTIONS"),
+    OPENJDK("registry.access.redhat.com/openjdk/openjdk-11-rhel7", "JAVA_MAIN_CLASS", "JAVA_APP_JAR", "JAVA_LIB_DIR",
```
Comment (Ladicek) [inline extensions/container-image/container-image-s2i/deployment/src/main/java/io/quarkus/container/image/s2i/deployment/S2iBaseJavaImage.java]: There are 4 Red Hat OpenJDK images that I'm aware of (OpenJDK 8 and 11, RHEL 7 and 8), some of them being available from 2 registries (authenticated and unauthenticated).

- OpenJDK 8 (I'm not sure if we still support Java 8, but we probably do. Defaulting to 11 is probably good though.)
    - RHEL 7
        - registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift
        - registry.redhat.io/redhat-openjdk-18/openjdk18-openshift
    - RHEL 8
        - registry.redhat.io/openjdk/openjdk-8-rhel8 (registry.access.redhat.com variant not available)
- OpenJDK 11
    - RHEL 7
        - registry.access.redhat.com/openjdk/openjdk-11-rhel7
        - registry.redhat.io/openjdk/openjdk-11-rhel7
    - RHEL 8
        - registry.redhat.io/openjdk/openjdk-11-rhel8 (registry.access.redhat.com variant not available)

They all have different tags (as does the Fabric8 image), which should all be recognized. (That is, tag should be ignored when searching.)

**Comment by Ladicek** [comment]
I will take a look in a few hours, I need to sort out some higher-priority items first.

**Comment by geoand** [comment]
@gsmet Just as an FYI, we'll need to get this one in for `Final`. @iocanel will be making some final changes and @Ladicek will hopefully check within the day

File: extensions/container-image/container-image-s2i/deployment/src/main/java/io/quarkus/container/image/s2i/deployment/S2iBaseJavaImage.java (hunk 6 above)
Comment (iocanel) [reply extensions/container-image/container-image-s2i/deployment/src/main/java/io/quarkus/container/image/s2i/deployment/S2iBaseJavaImage.java]: Added more images. Also cleaned them up a little bit, as the registry is stripped when performing the comparison.

**Comment by gsmet** [comment]
Please ping the appropriate people when this is ready.

**Comment by iocanel** [comment]
> Please ping the appropriate people when this is ready.
I don't have anything more to add. So @maxandersen: Ping!

**Comment by geoand** [comment]
I have already approved the PR. I just want @Ladicek to check it since he knows more about s2i and has been the one that finds all these subtle issues

**Comment by Ladicek** [comment]
I've finished the high-priority work now. I'll try to check between the meetings I have now :-)

**Comment by Ladicek** [comment]
I can confirm the duplicate env vars issue (#7740) is partially fixed.

1.

```properties
# one env var for specific key in the secret
quarkus.openshift.env-vars.MY_ENV_VAR.secret=the-secret
quarkus.openshift.env-vars.MY_ENV_VAR.value=key-in-the-secret
```

This case works fine now:

```yaml
        - name: "MY_ENV_VAR"
          valueFrom:
            secretKeyRef:
              key: "key-in-the-secret"
              name: "the-secret"
              optional: false
```

2.

```properties
# env vars for all keys in the ConfigMap
quarkus.openshift.env-vars.IGNORED.configmap=the-configmap
```

This case still causes duplicate entry in the YAML file:

```yaml
        envFrom:
        - configMapRef:
            name: "the-configmap"
            optional: false
        - configMapRef:
            name: "the-configmap"
            optional: false
```

**Comment by iocanel** [comment]
> This case still causes duplicate entry in the YAML file:

As this is a non-blocker issue, I think that the fix for that particular uses case should be deferred post 1.3.0.Final.

**Comment by geoand** [comment]
> > This case still causes duplicate entry in the YAML file:
> 
> As this is a non-blocker issue, I think that the fix for that particular uses case should be deferred post 1.3.0.Final.

I agree

**Comment by Ladicek** [comment]
Yea, there's no way how to indicate priority in GitHub issues (except labels, but I can't assign those). If it were, I'd mark that particular issue as not a blocker -- but since you already tried to fix it, I wanted to report that the fix is incomplete :-)

**Comment by Ladicek** [comment]
Ah, one thing. This doesn't mean I didn't find any other issue. I'm still checking. This one was just too easy to find :-)

**Comment by geoand** [comment]
@Ladicek I propose we merge now and if you find any issues open them along with an indication of how serious they are for `.Final`

**Comment by Ladicek** [comment]
I agree with merging (as I didn't spot any other glaring issue yet), but would like to have these 2 questions answered first:

1. Can we use the `registry.access.redhat.com/openjdk/openjdk-11-rhel7` image by default?
2. Can the fact that "known image" matching algorithm ignores the registry name have security consequences? Or any other consequences? I can only think of the possibility to abuse that by creating identically named image in an internal registry. But I'd like other folks to think about that too, at least a little.

**Comment by iocanel** [comment]
> I agree with merging (as I didn't spot any other glaring issue yet), but would like to have these 2 questions answered first:
> 
> 1. Can we use the `registry.access.redhat.com/openjdk/openjdk-11-rhel7` image by default?

This is already the image we use. If your question is if we should, then maybe @maxandersen  can answer that.

> 2. Can the fact that "known image" matching algorithm ignores the registry name have security consequences? Or any other consequences? I can only think of the possibility to abuse that by creating identically named image in an internal registry. But I'd like other folks to think about that too, at least a little.

Let me start by saying that we can't take the registry into consideration, as this would break all private registries. Now, let's see what the implications might be:

Security wise, nothing changes. We don't grant any special privileges to known images, we just align our generated manifests (something anyone can do by hand anyway).

Other consequences?

Yeah, if someone creates an identically named image that doesn't respect the same environment variable conventions as the original one, publish that to a private, and use that instead, then the resulting container will probably fail to start. But I think we can live with that (at least for now).

**Comment by Ladicek** [comment]
> > I agree with merging (as I didn't spot any other glaring issue yet), but would like to have these 2 questions answered first:
> > 
> > 1. Can we use the `registry.access.redhat.com/openjdk/openjdk-11-rhel7` image by default?
> 
> This is already the image we use.

No we don't. We currently use the Fabric8 image by default. This PR changes that to the Red Hat image. I'm not sure if that's right. Technically, the image is available for everyone. However, I think that "conditions apply". If you don't have a Red Hat subscription (even the $0 developer subscription), you shouldn't use it. Or something like that.

> > 2. Can the fact that "known image" matching algorithm ignores the registry name have security consequences? Or any other consequences? I can only think of the possibility to abuse that by creating identically named image in an internal registry. But I'd like other folks to think about that too, at least a little.
> 
> Let me start by saying that we can't take the registry into consideration, as this would break all private registries. Now, let's see what the implications might be:
> 
> Security wise, nothing changes. We don't grant any special privileges to known images, we just align our generated manifests (something anyone can do by hand anyway).
> 
> Other consequences?
> 
> Yeah, if someone creates an identically named image that doesn't respect the same environment variable conventions as the original one, publish that to a private, and use that instead, then the resulting container will probably fail to start. But I think we can live with that (at least for now).

OK, agree.

**Comment by iocanel** [comment]
> No we don't. We currently use the Fabric8 image by default. This PR changes that to the Red Hat image. 

I stand corrected!

**Comment by geoand** [comment]
> > No we don't. We currently use the Fabric8 image by default. This PR changes that to the Red Hat image.
> 
> I stand corrected!

Which leaves us where with regards to @Ladicek 's comment?

**Comment by iocanel** [comment]
> > > No we don't. We currently use the Fabric8 image by default. This PR changes that to the Red Hat image.
> > 
> > 
> > I stand corrected!
> 
> Which leaves us where with regards to @Ladicek 's comment?

We need to check if we can use `registry.access.redhat.com/openjdk/openjdk-11-rhel7` as a default image. It seems that @maxandersen is swarmed though. @tqvarnst since we discussed about this on Monday, are there any legal obstacles in proceeding with this change (adopting openjdk-11-rhel7 as the default s2i base image)?

**Comment by Ladicek** [comment]
I don't like us using the Fabric8 image, but I don't think there's a better image that we can use by default. When UBI image with Java comes out, we should switch to that for sure, but until then...

**Comment by gsmet** [comment]
For the default Dockerfiles, we use ubi and install Java manually.

**Comment by geoand** [comment]
We can't do that for s2i however

**Comment by maxandersen** [comment]
long thread and not sure what questions are left but just two things to state:

* we are stuck with fabric8 image until ubi-java comes out - for customers they'll need to explicitly set whatever supported image is needed.
* we are not going to use any image that require auth as default.

File: extensions/container-image/container-image-s2i/deployment/src/main/java/io/quarkus/container/image/s2i/deployment/S2iProcessor.java [hunk 7]
```diff
@@ -61,53 +65,100 @@
...
             BuildProducer<BaseImageInfoBuildItem> builderImageProducer,
             BuildProducer<KubernetesCommandBuildItem> commandProducer) {
 
         final List<AppDependency> appDeps = curateOutcomeBuildItem.getEffectiveModel().getUserDependencies();
+        String outputJarFileName = jarBuildItem.getPath().getFileName().toString();
         String classpath = appDeps.stream()
-                .map(d -> Paths.get(s2iConfig.jarPath).getParent().resolve("lib")
-                        .resolve(d.getArtifact().getGroupId() + "." + d.getArtifact().getPath().getFileName()).toAbsolutePath()
+                .map(d -> String.valueOf(d.getArtifact().getGroupId() + "." + d.getArtifact().getPath().getFileName()))
+                .map(s -> Paths.get(s2iConfig.jarDirectory).resolve("lib").resolve(s).toAbsolutePath()
```
Comment (Ladicek) [inline extensions/container-image/container-image-s2i/deployment/src/main/java/io/quarkus/container/image/s2i/deployment/S2iProcessor.java]: I wonder what happens on Windows, would this possibly generate Windows-style paths into the Kubernetes YAML? (Didn't check, just thinking aloud.)

**Review by Ladicek — APPROVED** [review]
This works fine for my usecase. There might be follow-up issues, but this is a good base IMHO.

**Comment by geoand** [comment]
Since we are practically out of time, I'm going to merge this to get the needed fixes into `Final`
