### PR TITLE
Fixes Flyway upgrade to 7.4.0 and adds Flyway callbacks support

### LINKED ISSUE #11409: Support Flyway callbacks
**Description**
The current Flyway extension doesn't support [Flyway callbacks](https://flywaydb.org/documentation/callbacks.html). It would be nice if the callbacks could be registered using a dedicated configuration property, which would reference the class names of the callbacks to instantiate and register.

**Implementation ideas**
As described, add a new `quarkus.flyway.callbacks` config property which lists the Java class names of the callbacks to be registered with Flyway at deployment time (using `FluentConfiguration#callbacks(String...)`).

### PR DESCRIPTION
**Pull request by cristhiank**
Replaces PR #14018  Error in this PR was because Flyway 7.3.2 added a new feature that opens more than one connection and the H2 INIT script was execute more than once.

Fixes #11409

### CODE REVIEW

File: extensions/flyway/deployment/src/main/java/io/quarkus/flyway/FlywayCallbacksProcessor.java [hunk 1]
```diff
@@ -0,0 +1,73 @@
...
+        final Collection<Callback> instances = new ArrayList<>();
+        for (String callback : callbacks) {
+            final ClassInfo clazz = combinedIndexBuildItem.getIndex().getClassByName(DotName.createSimple(callback));
+            Objects.requireNonNull(clazz, "Flyway callback not found " + callback);
+            if (Modifier.isAbstract(clazz.flags()) || !clazz.hasNoArgsConstructor()) {
+                throw new IllegalArgumentException(
+                        "Invalid Flyway callback. It shouldn't be abstract and must have a default constructor");
+            }
+            final Class<?> clazzType = Class.forName(callback, false, Thread.currentThread().getContextClassLoader());
+            final Callback instance = (Callback) clazzType.getConstructors()[0].newInstance();
```
Comment (geoand) [inline extensions/flyway/deployment/src/main/java/io/quarkus/flyway/FlywayCallbacksProcessor.java:67]: I am pretty sure we'll need to register the constructors of these class for reflection if they are to work in native mode.

Furthermore, it probably makes sense to provide some kind of actionable error message (as it is too easy for a user to mistype the FQCN).

File: extensions/flyway/runtime/src/main/java/io/quarkus/flyway/runtime/FlywayDataSourceBuildTimeConfig.java [hunk 2]
```diff
@@ -33,4 +23,22 @@ public static final FlywayDataSourceBuildTimeConfig defaultConfig() {
      */
     @ConfigItem(defaultValue = DEFAULT_LOCATION)
     public List<String> locations;
+
+    /**
+     * Comma-separated list of fully qualified class names of Callback implementations
+     * to use to hook into the Flyway lifecycle.
+     */
+    @ConfigItem
+    public Optional<List<String>> callbacks = Optional.empty();
```
Comment (geoand) [inline extensions/flyway/runtime/src/main/java/io/quarkus/flyway/runtime/FlywayDataSourceBuildTimeConfig.java:32]: We also need to mention that for this to work, the class needs to have a no-args constructor.
Furthermore these classes must also not have any fields that hold state (unless that state is initialized in the constructor).

**Review by geoand — CHANGES_REQUESTED** [review]
Great work!

I added some comments that will need to be addressed before we merge this

File: extensions/flyway/deployment/src/test/resources/config-for-multiple-datasources.properties [hunk 3]
```diff
@@ -10,15 +10,13 @@ quarkus.datasource.users.username=username1
...
 quarkus.datasource.users.jdbc.max-size=11
-quarkus.datasource.users.jdbc.xa=false
 
 # Datasource for "inventory"
 quarkus.datasource.inventory.db-kind=h2
 quarkus.datasource.inventory.username=username2
 quarkus.datasource.inventory.jdbc.driver=org.h2.jdbcx.JdbcDataSource
 quarkus.datasource.inventory.jdbc.url=jdbc:h2:tcp://localhost/mem:inventory
 quarkus.datasource.inventory.jdbc.max-size=12
-quarkus.datasource.inventory.jdbc.xa=true
```
[the remark this answers is not in the document]
Comment (cristhiank) [reply extensions/flyway/deployment/src/test/resources/config-for-multiple-datasources.properties:21]: I remove it because the quarkus.datasource.jdbc.xa doesn't exists. (I am not sure if it existe before, I was just cleaning the code)

File: extensions/flyway/deployment/src/main/java/io/quarkus/flyway/FlywayCallbacksProcessor.java (hunk 1 above)
Comment (cristhiank) [reply extensions/flyway/deployment/src/main/java/io/quarkus/flyway/FlywayCallbacksProcessor.java]: I am not sure if I understood the refelction part, I thought that using the `BuildProducer<ReflectiveClassBuildItem>` was enough for reflection. Could you please give me some details to fully understand what should be done to fully support native compilation

**Comment by cristhiank** [comment]
> Great work!
> 
> I added some comments that will need to be addressed before we merge this

Thanks. I just pushed the changes to address the comments. I also upgraded the Flyway version again as a new release was done today.

File: extensions/flyway/deployment/src/test/resources/config-for-multiple-datasources.properties (hunk 3 above)
[the remark this answers is not in the document]
Comment (geoand) [reply extensions/flyway/deployment/src/test/resources/config-for-multiple-datasources.properties:21]: OK

File: extensions/flyway/deployment/src/main/java/io/quarkus/flyway/FlywayCallbacksProcessor.java (hunk 1 above)
Comment (geoand) [reply extensions/flyway/deployment/src/main/java/io/quarkus/flyway/FlywayCallbacksProcessor.java]: I guess I had missed the call to `reflectiveClassProducer` that I now see in the code.

That is enough, nothing more needs to be done to register for reflection

File: extensions/flyway/deployment/src/main/java/io/quarkus/flyway/FlywayCallbacksLocator.java [hunk 4]
```diff
@@ -0,0 +1,100 @@
...
+import org.jboss.jandex.DotName;
+
+import io.quarkus.deployment.annotations.BuildProducer;
+import io.quarkus.deployment.builditem.CombinedIndexBuildItem;
+import io.quarkus.deployment.builditem.nativeimage.ReflectiveClassBuildItem;
+import io.quarkus.flyway.runtime.FlywayBuildTimeConfig;
+
+/**
+ * Logic to locate and process Flyway {@link Callback} classes.
+ * This class also helps to keep de {@link FlywayProcessor} class as lean as possible to make it easier to maintain
```
Comment (geoand) [inline extensions/flyway/deployment/src/main/java/io/quarkus/flyway/FlywayCallbacksLocator.java:25]:
```suggestion
 * This class also helps to keep the {@link FlywayProcessor} class as lean as possible to make it easier to maintain
```

File: extensions/flyway/deployment/src/main/java/io/quarkus/flyway/FlywayCallbacksLocator.java [hunk 5]
```diff
@@ -0,0 +1,100 @@
...
+     *            and the underlying constructor is inaccessible
+     */
+    private Collection<Callback> callbacksForDataSource(String dataSourceName)
+            throws ClassNotFoundException, IllegalAccessException, InvocationTargetException, InstantiationException {
+        final Optional<List<String>> callbackConfig = flywayBuildConfig.getConfigForDataSourceName(dataSourceName).callbacks;
+        if (!callbackConfig.isPresent()) {
+            return Collections.emptyList();
+        }
+        final Collection<String> callbacks = callbackConfig.get();
+        final Collection<Callback> instances = new ArrayList<>();
```
Comment (geoand) [inline extensions/flyway/deployment/src/main/java/io/quarkus/flyway/FlywayCallbacksLocator.java:84]:
```suggestion
        final Collection<Callback> instances = new ArrayList<>(callbacks.size());
```

**Review by geoand — COMMENTED** [review]
I added to tiny comments, other than that, LGTM!

**Comment by gsmet** [comment]
I applied the latest suggestions from Georgios and force-pushed.

Let's try to get this one in CR1.

**Comment by gsmet** [comment]
@geoand could you approve if it's good for you now?

**Review by geoand — APPROVED** [review]
All good, thanks!

**Comment by gsmet** [comment]
Thanks @cristhiank , nice work!
