### PR TITLE
Restrict properties passed to gradle worker processes

### LINKED ISSUE #33321: Different behavior in native build using env var in application.properties when build with gradle vs. maven (Quarkus 3.x)
### Describe the bug

Setting a environment variable which is used like `quarkus.some.var=${MY_ENV_VAR:defaultValue}` in application.properties has no effect when the native image is build with gradle.

The important part is the replacement of `MY_ENV_VAR` with the set value in the property `quarkus.some.var`. 

This can lead to unexpected behaviour during execution in production because a property does not have the expected value.
The behavior is only reproducible in Quarkus 3.x, but not in Quarkus 2.x.

To describe and reproduce this behavior the following configuration example is used:
`quarkus.banner.enabled=${BANNER:false}`

Reproducers:
maven -> https://github.com/dagrammy/quarkus-env-reproducer-maven
gradle -> https://github.com/dagrammy/quarkus-env-reproducer-gradle

### Expected behavior

Setting the env var `BANNER` to `true` before starting the application should show the banner regardless of the build tool used.

### Actual behavior

Using maven:
Expected behavior is met, the banner is shown.

Using gradle:
Expected behavior is not met, the banner is **NOT** shown.

### How to Reproduce?

maven -> https://github.com/dagrammy/quarkus-env-reproducer-maven

**build it using maven:**
```
unset BANNER 
./mvnw clean package -Pnative
```

**run it without env var:**
```
./target/command-mode-quickstart-1.0.0-SNAPSHOT-runner 
```

-> header is NOT shown

**run it with env var:**
```
export BANNER=true 
./target/command-mode-quickstart-1.0.0-SNAPSHOT-runner 
```

-> header is shown

 ---

gradle -> https://github.com/dagrammy/quarkus-env-reproducer-gradle

**build it using gradle:**
```
unset BANNER 
./gradlew clean build -Dquarkus.package.type=native --info
```

**run it without env var:**
```
./build/command-mode-quickstart-gradle-1.0.0-SNAPSHOT-runner 
```

-> header is NOT shown

**run it with env var:**
```
export BANNER=true 
./build/command-mode-quickstart-gradle-1.0.0-SNAPSHOT-runner 
```

-> header is **NOT** shown although env var is set

### Output of `uname -a` or `ver`

Darwin grammy.local 22.3.0 Darwin Kernel Version 22.3.0: Thu Jan  5 20:49:43 PST 2023; root:xnu-8792.81.2~2/RELEASE_ARM64_T8103 arm64

### Output of `java -version`

openjdk version "17.0.5" 2022-10-18 OpenJDK Runtime Environment GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08) OpenJDK 64-Bit Server VM GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08, mixed mode, sharing)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

3.0.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 / Gradle 7.5.1

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by dagrammy**
This PR changes/restricts which properties are passed to the gradle worker process as system properties.

Instead of all properties, only the following properties are passed now:
- quarkus.package.*
- quarkus.application.*
- quarkus.gradle-worker.*

These properties are important so the gradle worker processes uses the correct outpur directory, package type (jar, native image,...).

Keep in mind, that this only affects properties passed to the gradle worker process. To build the actual artifact (e.g. jar, native image) all properties are used.

This PR fixes https://github.com/quarkusio/quarkus/issues/33321.
Locally all gradle unit & integration test are executed successfully.

### CODE REVIEW

File: devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/QuarkusTask.java [hunk 1]
```diff
@@ -9,6 +9,7 @@
 
 import javax.inject.Inject;
 
+import org.apache.commons.lang3.StringUtils;
```
Comment (gsmet) [inline devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/QuarkusTask.java:12]: I'm not sure we want to add a dependency to this one. I would drop it and have multiple conditions.

File: devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/QuarkusTask.java [hunk 2]
```diff
@@ -20,6 +21,9 @@
 import io.quarkus.utilities.OS;
 
 public abstract class QuarkusTask extends DefaultTask {
+    private static final String[] WORKER_BUILD_FORK_OPTIONS = { "quarkus.package",
+            "quarkus.application", "quarkus.gradle-worker" };
```
Comment (gsmet) [inline devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/QuarkusTask.java:25]: Let's add a `.` because you never know if we won't add `quarkus.application-foo` one day.
```suggestion
    private static final String[] WORKER_BUILD_FORK_OPTIONS = { "quarkus.package.",
            "quarkus.application.", "quarkus.gradle-worker." };
```

**Review by gsmet — CHANGES_REQUESTED** [review]
I added a few suggestions but I would like @snazy , @glefloch and @aloubyansky to have a look if possible.

File: devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/QuarkusTask.java (hunk 1 above)
Comment (dagrammy) [reply devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/QuarkusTask.java]: I removed this dependency.

File: devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/QuarkusTask.java (hunk 2 above)
Comment (dagrammy) [reply devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/QuarkusTask.java]: That's a good and reasonable suggestion, I added the trailing `.`

**Review by gsmet — APPROVED** [review]
I squashed the commits and force pushed.

From my perspective, it looks good but I would prefer if someone more familiar with the Gradle build had a look.

I will approve the CI run in the meantime.

**Comment by dagrammy** [comment]
Is there a way to re-run the test? The problem seems unrelated to the changes and the test was successful running on Windows.

`Could not run build action using connection to Gradle distribution 'https://services.gradle.org/distributions/gradle-8.1.1-bin.zip'.` 

> ## Failing Jobs - Building [2b1f2b1](https://github.com/quarkusio/quarkus/commit/2b1f2b1dfa6651fd70b9158984ac72c0a23be1d2)
> Status	Name	Step	Failures	Logs	Raw logs
> ✖	Gradle Tests - JDK 11	`Build`	[Failures](#user-content-test-failures-job-14046932935)	[Logs](https://github.com/quarkusio/quarkus/actions/runs/5189997798/jobs/9357553440)	[Raw logs](https://github.com/quarkusio/quarkus/commit/2b1f2b1dfa6651fd70b9158984ac72c0a23be1d2/checks/14046932935/logs)
> ✔️	Gradle Tests - JDK 11 Windows				
> Full information is available in the [Build summary check run](https://github.com/quarkusio/quarkus/runs/14048946631).
> 
> ....

**Review by snazy — APPROVED** [review]
LGTM
