### PR TITLE
Move to GraalVM 19

### LINKED ISSUE #2410: Graal CE 19.0 fails to build native images
In several integration tests, i.e. Vertx and my upcoming Neo4j extension, native images cannot be build with Graal CE 19.0:

```
com.oracle.svm.core.util.UserError$UserException: Already registered: java.lang.reflect.Method.getDefaultValue()
	at com.oracle.svm.core.util.UserError.abort(UserError.java:65)
	at com.oracle.svm.core.util.UserError.guarantee(UserError.java:86)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.register(AnnotationSubstitutionProcessor.java:710)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleMethodInAliasClass(AnnotationSubstitutionProcessor.java:334)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleAliasClass(AnnotationSubstitutionProcessor.java:298)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:274)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:230)
	at com.oracle.svm.hosted.NativeImageGenerator.createDeclarativeSubstitutionProcessor(NativeImageGenerator.java:864)
	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:819)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:521)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:441)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

Environment:

Java:
> java -version 
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-20190420112649.buildslave.jdk8u-src-tar--b03)
OpenJDK GraalVM CE 19.0.0 (build 25.212-b03-jvmci-19-b01, mixed mode)

Native Image
> $GRAALVM_HOME/bin/native-image --version
GraalVM Version 19.0.0 CE

### LINKED ISSUE #2412: Support GraalVM v. 19.0
Several things changed, making GraalVM 19 currently not compatible with Quarkus.

So far I noticed:
 - [x] `native-image` is no longer included by default. Need to install it by running "gu install native-image" -> adapt documentation, adapt CI, adapt container images.
 - [x] `SubstrateAutoFeatureStep` needs to invoke different methods; e.g. `delayClassInitialization` was renamed to `initializeAtRunTime`
 - [x] Issue https://github.com/oracle/graal/issues/649 was resolved, we need to remove the substitutions for it from class `/core/runtime/src/main/java/io/quarkus/runtime/graal/MethodReplacement.java`.
 - [x] the default strategy to initialize static blocks changed; we should set `--initialize-at-build-time` by default, but also verify how this interactos with other flags we're setting.

There are certainly some more issues, to be investigated.

### LINKED ISSUE #2428: Class init controls have changed
Original comment by Sanne:

> `SubstrateAutoFeatureStep` needs to invoke different methods; e.g. `delayClassInitialization` was renamed to `initializeAtRunTime`

In addition, the "rerun init" method is gone in favor of a direct singleton call.  We need to update this class to call these new methods in the new way, probably with more ugly reflection until/unless we can get an artifact with these types in it.

### LINKED ISSUE #2438: AJP init failure under Graal 19
Output looks like this:

```
[INFO] [io.quarkus.creator.phase.nativeimage.NativeImagePhase] /home/david/local/jdk/graalvm-ce-19.0.0/bin/native-image -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -H:+ReportExceptionStackTraces -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime --initialize-at-build-time= -jar quarkus-integration-test-hibernate-validator-999-SNAPSHOT-runner.jar -J-Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -H:FallbackThreshold=0 -H:+PrintAnalysisCallTree -H:-AddAllCharsets -H:EnableURLProtocols=http -H:NativeLinkerOption=-no-pie -H:-SpawnIsolates -H:-JNI --no-server -H:-UseServiceLoaderFeature -H:+StackTrace
[quarkus-integration-test-hibernate-validator-999-SNAPSHOT-runner:95639]    classlist:   3,407.71 ms
[quarkus-integration-test-hibernate-validator-999-SNAPSHOT-runner:95639]        (cap):     862.89 ms
[quarkus-integration-test-hibernate-validator-999-SNAPSHOT-runner:95639]        setup:   2,045.37 ms
09:00:15,715 INFO  [org.hib.val.int.uti.Version] HV000001: Hibernate Validator 6.1.0.Alpha4
09:00:16,676 INFO  [org.jbo.threads] JBoss Threads version 3.0.0.Beta3
09:00:17,124 INFO  [org.xnio] XNIO version 3.7.0.Final
09:00:17,158 INFO  [org.xni.nio] XNIO NIO Implementation Version 3.7.0.Final
[quarkus-integration-test-hibernate-validator-999-SNAPSHOT-runner:95639]     analysis:  20,217.87 ms
Printing call tree to /home/david/src/java/shamrock/integration-tests/hibernate-validator/target/reports/call_tree_quarkus-integration-test-hibernate-validator-999-SNAPSHOT-runner_20190514_090037.txt
Printing list of used classes to /home/david/src/java/shamrock/integration-tests/hibernate-validator/target/reports/used_classes_quarkus-integration-test-hibernate-validator-999-SNAPSHOT-runner_20190514_090039.txt
Printing list of used packages to /home/david/src/java/shamrock/integration-tests/hibernate-validator/target/reports/used_packages_quarkus-integration-test-hibernate-validator-999-SNAPSHOT-runner_20190514_090039.txt
Error: Unsupported features in 2 methods
Detailed message:
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Detected a direct/mapped ByteBuffer in the image heap. A direct ByteBuffer has a pointer to unmanaged C memory, and C memory from the image generator is not available at image run time. A mapped ByteBuffer references a file descriptor, which is no longer open and mapped at run time. The object was probably created by a class initializer and is reachable from a static field. By default, all class initialization is done during native image building.You can manually delay class initialization to image run time by using the option -H:ClassInitialization=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: 
	at parsing io.undertow.server.protocol.ajp.AjpServerRequestConduit.read(AjpServerRequestConduit.java:195)
Call path from entry point to io.undertow.server.protocol.ajp.AjpServerRequestConduit.read(ByteBuffer): 
	at io.undertow.server.protocol.ajp.AjpServerRequestConduit.read(AjpServerRequestConduit.java:183)
	at org.xnio.conduits.ConduitStreamSourceChannel.read(ConduitStreamSourceChannel.java:127)
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:158)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136)
	at io.undertow.server.protocol.http.HttpReadListener.run(HttpReadListener.java:402)
	at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:612)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:479)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:473)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
--------------------------------------------------------------------------------------------
-- WARNING: The above stack trace is not a real stack trace, it is a theoretical call tree---
-- If an interface has multiple implementations SVM will just display one potential call  ---
-- path to the interface. This is often meaningless, and what you actually need to know is---
-- the path to the constructor of the object that implements this interface.              ---
-- Quarkus has attempted to generate a more meaningful call flow analysis below          ---
---------------------------------------------------------------------------------------------

Possible path to io.undertow.server.protocol.ajp.AjpServerRequestConduit.read(java.nio.ByteBuffer):i
	io.undertow.server.protocol.ajp.AjpServerRequestConduit.read(java.nio.ByteBuffer):i
This is an implementation of org.xnio.conduits.StreamSourceConduit printing path to constructors of io.undertow.server.protocol.ajp.AjpServerRequestConduit


Possible path to io.undertow.server.protocol.ajp.AjpServerRequestConduit.<init>(org.xnio.conduits.StreamSourceConduit, io.undertow.server.HttpServerExchange, io.undertow.server.protocol.ajp.AjpServerResponseConduit, java.lang.Long, io.undertow.conduits.ConduitListener):v
	io.undertow.server.protocol.ajp.AjpServerRequestConduit.<init>(org.xnio.conduits.StreamSourceConduit, io.undertow.server.HttpServerExchange, io.undertow.server.protocol.ajp.AjpServerResponseConduit, java.lang.Long, io.undertow.conduits.ConduitListener):v
	io.undertow.server.protocol.ajp.AjpReadListener.createSourceConduit(org.xnio.conduits.StreamSourceConduit, io.undertow.server.protocol.ajp.AjpServerResponseConduit, io.undertow.server.HttpServerExchange):o
	io.undertow.server.protocol.ajp.AjpReadListener.handleEvent(org.xnio.channels.StreamSourceChannel):v
	io.undertow.server.protocol.ajp.AjpReadListener.handleEvent(java.nio.channels.Channel):v
This is an implementation of org.xnio.ChannelListener printing path to constructors of io.undertow.server.protocol.ajp.AjpReadListener


Possible path to io.undertow.server.protocol.ajp.AjpReadListener.<init>(io.undertow.server.protocol.ajp.AjpServerConnection, java.lang.String, io.undertow.server.protocol.ajp.AjpRequestParser, io.undertow.server.ConnectorStatisticsImpl):v
	io.undertow.server.protocol.ajp.AjpReadListener.<init>(io.undertow.server.protocol.ajp.AjpServerConnection, java.lang.String, io.undertow.server.protocol.ajp.AjpRequestParser, io.undertow.server.ConnectorStatisticsImpl):v
	io.undertow.server.protocol.ajp.AjpOpenListener.handleEvent(org.xnio.StreamConnection):v
	io.undertow.server.protocol.ajp.AjpOpenListener.handleEvent(org.xnio.StreamConnection):v
	io.undertow.server.protocol.ajp.AjpOpenListener.handleEvent(java.nio.channels.Channel):v
This is an implementation of org.xnio.ChannelListener printing path to constructors of io.undertow.server.protocol.ajp.AjpOpenListener


Possible path to io.undertow.server.protocol.ajp.AjpOpenListener.<init>(io.undertow.connector.ByteBufferPool, org.xnio.OptionMap):v
	io.undertow.server.protocol.ajp.AjpOpenListener.<init>(io.undertow.connector.ByteBufferPool, org.xnio.OptionMap):v
	io.undertow.Undertow.start():v
	io.quarkus.undertow.runtime.UndertowDeploymentTemplate.doServerStart(io.quarkus.undertow.runtime.HttpConfig, io.quarkus.runtime.LaunchMode, javax.net.ssl.SSLContext, java.util.concurrent.ExecutorService):v
	io.quarkus.undertow.runtime.UndertowDeploymentTemplate.startUndertow(io.quarkus.runtime.ShutdownContext, java.util.concurrent.ExecutorService, io.undertow.servlet.api.DeploymentManager, io.quarkus.undertow.runtime.HttpConfig, java.util.List, io.quarkus.runtime.LaunchMode):i
	io.quarkus.deployment.steps.UndertowBuildStep$boot12.deploy(io.quarkus.runtime.StartupContext):v
	io.quarkus.runner.ApplicationImpl1.doStart(java.lang.String[]):v
	io.quarkus.runtime.Application.doStart(java.lang.String[]):v
	io.quarkus.runtime.Application.start(java.lang.String[]):v
	io.quarkus.runtime.Application.run(java.lang.String[]):v
	io.quarkus.runner.GeneratedMain.main(java.lang.String[]):v
	com.oracle.svm.core.JavaMainWrapper.run(int, org.graalvm.nativeimage.c.type.CCharPointerPointer):i
	com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(int, org.graalvm.nativeimage.c.type.CCharPointerPointer):i

Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Detected a direct/mapped ByteBuffer in the image heap. A direct ByteBuffer has a pointer to unmanaged C memory, and C memory from the image generator is not available at image run time. A mapped ByteBuffer references a file descriptor, which is no longer open and mapped at run time. The object was probably created by a class initializer and is reachable from a static field. By default, all class initialization is done during native image building.You can manually delay class initialization to image run time by using the option -H:ClassInitialization=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: 
	at parsing io.undertow.server.protocol.ajp.AjpServerResponseConduit.flush(AjpServerResponseConduit.java:404)
Call path from entry point to io.undertow.server.protocol.ajp.AjpServerResponseConduit.flush(): 
	at io.undertow.server.protocol.ajp.AjpServerResponseConduit.flush(AjpServerResponseConduit.java:402)
	at org.xnio.conduits.ConduitStreamSinkChannel.flush(ConduitStreamSinkChannel.java:162)
	at io.undertow.server.protocol.framed.AbstractFramedChannel.flushSenders(AbstractFramedChannel.java:609)
	at io.undertow.server.protocol.framed.AbstractFramedChannel$5.run(AbstractFramedChannel.java:724)
	at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:612)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:479)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:473)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
--------------------------------------------------------------------------------------------
-- WARNING: The above stack trace is not a real stack trace, it is a theoretical call tree---
-- If an interface has multiple implementations SVM will just display one potential call  ---
-- path to the interface. This is often meaningless, and what you actually need to know is---
-- the path to the constructor of the object that implements this interface.              ---
-- Quarkus has attempted to generate a more meaningful call flow analysis below          ---
---------------------------------------------------------------------------------------------

Possible path to io.undertow.server.protocol.ajp.AjpServerResponseConduit.flush():b
	io.undertow.server.protocol.ajp.AjpServerResponseConduit.flush():b
This is an implementation of org.xnio.conduits.SinkConduit printing path to constructors of io.undertow.server.protocol.ajp.AjpServerResponseConduit


Possible path to io.undertow.server.protocol.ajp.AjpServerResponseConduit.<init>(org.xnio.conduits.StreamSinkConduit, io.undertow.connector.ByteBufferPool, io.undertow.server.HttpServerExchange, io.undertow.conduits.ConduitListener, boolean):v
	io.undertow.server.protocol.ajp.AjpServerResponseConduit.<init>(org.xnio.conduits.StreamSinkConduit, io.undertow.connector.ByteBufferPool, io.undertow.server.HttpServerExchange, io.undertow.conduits.ConduitListener, boolean):v
	io.undertow.server.protocol.ajp.AjpReadListener.handleEvent(org.xnio.channels.StreamSourceChannel):v
	io.undertow.server.protocol.ajp.AjpReadListener.handleEvent(java.nio.channels.Channel):v
This is an implementation of org.xnio.ChannelListener printing path to constructors of io.undertow.server.protocol.ajp.AjpReadListener


Possible path to io.undertow.server.protocol.ajp.AjpReadListener.<init>(io.undertow.server.protocol.ajp.AjpServerConnection, java.lang.String, io.undertow.server.protocol.ajp.AjpRequestParser, io.undertow.server.ConnectorStatisticsImpl):v
	io.undertow.server.protocol.ajp.AjpReadListener.<init>(io.undertow.server.protocol.ajp.AjpServerConnection, java.lang.String, io.undertow.server.protocol.ajp.AjpRequestParser, io.undertow.server.ConnectorStatisticsImpl):v
	io.undertow.server.protocol.ajp.AjpOpenListener.handleEvent(org.xnio.StreamConnection):v
	io.undertow.server.protocol.ajp.AjpOpenListener.handleEvent(org.xnio.StreamConnection):v
	io.undertow.server.protocol.ajp.AjpOpenListener.handleEvent(java.nio.channels.Channel):v
This is an implementation of org.xnio.ChannelListener printing path to constructors of io.undertow.server.protocol.ajp.AjpOpenListener


Possible path to io.undertow.server.protocol.ajp.AjpOpenListener.<init>(io.undertow.connector.ByteBufferPool, org.xnio.OptionMap):v
	io.undertow.server.protocol.ajp.AjpOpenListener.<init>(io.undertow.connector.ByteBufferPool, org.xnio.OptionMap):v
	io.undertow.Undertow.start():v
	io.quarkus.undertow.runtime.UndertowDeploymentTemplate.doServerStart(io.quarkus.undertow.runtime.HttpConfig, io.quarkus.runtime.LaunchMode, javax.net.ssl.SSLContext, java.util.concurrent.ExecutorService):v
	io.quarkus.undertow.runtime.UndertowDeploymentTemplate.startUndertow(io.quarkus.runtime.ShutdownContext, java.util.concurrent.ExecutorService, io.undertow.servlet.api.DeploymentManager, io.quarkus.undertow.runtime.HttpConfig, java.util.List, io.quarkus.runtime.LaunchMode):i
	io.quarkus.deployment.steps.UndertowBuildStep$boot12.deploy(io.quarkus.runtime.StartupContext):v
	io.quarkus.runner.ApplicationImpl1.doStart(java.lang.String[]):v
	io.quarkus.runtime.Application.doStart(java.lang.String[]):v
	io.quarkus.runtime.Application.start(java.lang.String[]):v
	io.quarkus.runtime.Application.run(java.lang.String[]):v
	io.quarkus.runner.GeneratedMain.main(java.lang.String[]):v
	com.oracle.svm.core.JavaMainWrapper.run(int, org.graalvm.nativeimage.c.type.CCharPointerPointer):i
	com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(int, org.graalvm.nativeimage.c.type.CCharPointerPointer):i


com.oracle.svm.core.util.UserError$UserException: Unsupported features in 2 methods
Detailed message:
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Detected a direct/mapped ByteBuffer in the image heap. A direct ByteBuffer has a pointer to unmanaged C memory, and C memory from the image generator is not available at image run time. A mapped ByteBuffer references a file descriptor, which is no longer open and mapped at run time. The object was probably created by a class initializer and is reachable from a static field. By default, all class initialization is done during native image building.You can manually delay class initialization to image run time by using the option -H:ClassInitialization=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: 
	at parsing io.undertow.server.protocol.ajp.AjpServerRequestConduit.read(AjpServerRequestConduit.java:195)
Call path from entry point to io.undertow.server.protocol.ajp.AjpServerRequestConduit.read(ByteBuffer): 
	at io.undertow.server.protocol.ajp.AjpServerRequestConduit.read(AjpServerRequestConduit.java:183)
	at org.xnio.conduits.ConduitStreamSourceChannel.read(ConduitStreamSourceChannel.java:127)
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:158)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136)
	at io.undertow.server.protocol.http.HttpReadListener.run(HttpReadListener.java:402)
	at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:612)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:479)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:473)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
--------------------------------------------------------------------------------------------
-- WARNING: The above stack trace is not a real stack trace, it is a theoretical call tree---
-- If an interface has multiple implementations SVM will just display one potential call  ---
-- path to the interface. This is often meaningless, and what you actually need to know is---
-- the path to the constructor of the object that implements this interface.              ---
-- Quarkus has attempted to generate a more meaningful call flow analysis below          ---
---------------------------------------------------------------------------------------------

Possible path to io.undertow.server.protocol.ajp.AjpServerRequestConduit.read(java.nio.ByteBuffer):i
	io.undertow.server.protocol.ajp.AjpServerRequestConduit.read(java.nio.ByteBuffer):i
This is an implementation of org.xnio.conduits.StreamSourceConduit printing path to constructors of io.undertow.server.protocol.ajp.AjpServerRequestConduit


Possible path to io.undertow.server.protocol.ajp.AjpServerRequestConduit.<init>(org.xnio.conduits.StreamSourceConduit, io.undertow.server.HttpServerExchange, io.undertow.server.protocol.ajp.AjpServerResponseConduit, java.lang.Long, io.undertow.conduits.ConduitListener):v
	io.undertow.server.protocol.ajp.AjpServerRequestConduit.<init>(org.xnio.conduits.StreamSourceConduit, io.undertow.server.HttpServerExchange, io.undertow.server.protocol.ajp.AjpServerResponseConduit, java.lang.Long, io.undertow.conduits.ConduitListener):v
	io.undertow.server.protocol.ajp.AjpReadListener.createSourceConduit(org.xnio.conduits.StreamSourceConduit, io.undertow.server.protocol.ajp.AjpServerResponseConduit, io.undertow.server.HttpServerExchange):o
	io.undertow.server.protocol.ajp.AjpReadListener.handleEvent(org.xnio.channels.StreamSourceChannel):v
	io.undertow.server.protocol.ajp.AjpReadListener.handleEvent(java.nio.channels.Channel):v
This is an implementation of org.xnio.ChannelListener printing path to constructors of io.undertow.server.protocol.ajp.AjpReadListener


Possible path to io.undertow.server.protocol.ajp.AjpReadListener.<init>(io.undertow.server.protocol.ajp.AjpServerConnection, java.lang.String, io.undertow.server.protocol.ajp.AjpRequestParser, io.undertow.server.ConnectorStatisticsImpl):v
	io.undertow.server.protocol.ajp.AjpReadListener.<init>(io.undertow.server.protocol.ajp.AjpServerConnection, java.lang.String, io.undertow.server.protocol.ajp.AjpRequestParser, io.undertow.server.ConnectorStatisticsImpl):v
	io.undertow.server.protocol.ajp.AjpOpenListener.handleEvent(org.xnio.StreamConnection):v
	io.undertow.server.protocol.ajp.AjpOpenListener.handleEvent(org.xnio.StreamConnection):v
	io.undertow.server.protocol.ajp.AjpOpenListener.handleEvent(java.nio.channels.Channel):v
This is an implementation of org.xnio.ChannelListener printing path to constructors of io.undertow.server.protocol.ajp.AjpOpenListener


Possible path to io.undertow.server.protocol.ajp.AjpOpenListener.<init>(io.undertow.connector.ByteBufferPool, org.xnio.OptionMap):v
	io.undertow.server.protocol.ajp.AjpOpenListener.<init>(io.undertow.connector.ByteBufferPool, org.xnio.OptionMap):v
	io.undertow.Undertow.start():v
	io.quarkus.undertow.runtime.UndertowDeploymentTemplate.doServerStart(io.quarkus.undertow.runtime.HttpConfig, io.quarkus.runtime.LaunchMode, javax.net.ssl.SSLContext, java.util.concurrent.ExecutorService):v
	io.quarkus.undertow.runtime.UndertowDeploymentTemplate.startUndertow(io.quarkus.runtime.ShutdownContext, java.util.concurrent.ExecutorService, io.undertow.servlet.api.DeploymentManager, io.quarkus.undertow.runtime.HttpConfig, java.util.List, io.quarkus.runtime.LaunchMode):i
	io.quarkus.deployment.steps.UndertowBuildStep$boot12.deploy(io.quarkus.runtime.StartupContext):v
	io.quarkus.runner.ApplicationImpl1.doStart(java.lang.String[]):v
	io.quarkus.runtime.Application.doStart(java.lang.String[]):v
	io.quarkus.runtime.Application.start(java.lang.String[]):v
	io.quarkus.runtime.Application.run(java.lang.String[]):v
	io.quarkus.runner.GeneratedMain.main(java.lang.String[]):v
	com.oracle.svm.core.JavaMainWrapper.run(int, org.graalvm.nativeimage.c.type.CCharPointerPointer):i
	com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(int, org.graalvm.nativeimage.c.type.CCharPointerPointer):i

Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Detected a direct/mapped ByteBuffer in the image heap. A direct ByteBuffer has a pointer to unmanaged C memory, and C memory from the image generator is not available at image run time. A mapped ByteBuffer references a file descriptor, which is no longer open and mapped at run time. The object was probably created by a class initializer and is reachable from a static field. By default, all class initialization is done during native image building.You can manually delay class initialization to image run time by using the option -H:ClassInitialization=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: 
	at parsing io.undertow.server.protocol.ajp.AjpServerResponseConduit.flush(AjpServerResponseConduit.java:404)
Call path from entry point to io.undertow.server.protocol.ajp.AjpServerResponseConduit.flush(): 
	at io.undertow.server.protocol.ajp.AjpServerResponseConduit.flush(AjpServerResponseConduit.java:402)
	at org.xnio.conduits.ConduitStreamSinkChannel.flush(ConduitStreamSinkChannel.java:162)
	at io.undertow.server.protocol.framed.AbstractFramedChannel.flushSenders(AbstractFramedChannel.java:609)
	at io.undertow.server.protocol.framed.AbstractFramedChannel$5.run(AbstractFramedChannel.java:724)
	at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:612)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:479)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:473)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
--------------------------------------------------------------------------------------------
-- WARNING: The above stack trace is not a real stack trace, it is a theoretical call tree---
-- If an interface has multiple implementations SVM will just display one potential call  ---
-- path to the interface. This is often meaningless, and what you actually need to know is---
-- the path to the constructor of the object that implements this interface.              ---
-- Quarkus has attempted to generate a more meaningful call flow analysis below          ---
---------------------------------------------------------------------------------------------

Possible path to io.undertow.server.protocol.ajp.AjpServerResponseConduit.flush():b
	io.undertow.server.protocol.ajp.AjpServerResponseConduit.flush():b
This is an implementation of org.xnio.conduits.SinkConduit printing path to constructors of io.undertow.server.protocol.ajp.AjpServerResponseConduit


Possible path to io.undertow.server.protocol.ajp.AjpServerResponseConduit.<init>(org.xnio.conduits.StreamSinkConduit, io.undertow.connector.ByteBufferPool, io.undertow.server.HttpServerExchange, io.undertow.conduits.ConduitListener, boolean):v
	io.undertow.server.protocol.ajp.AjpServerResponseConduit.<init>(org.xnio.conduits.StreamSinkConduit, io.undertow.connector.ByteBufferPool, io.undertow.server.HttpServerExchange, io.undertow.conduits.ConduitListener, boolean):v
	io.undertow.server.protocol.ajp.AjpReadListener.handleEvent(org.xnio.channels.StreamSourceChannel):v
	io.undertow.server.protocol.ajp.AjpReadListener.handleEvent(java.nio.channels.Channel):v
This is an implementation of org.xnio.ChannelListener printing path to constructors of io.undertow.server.protocol.ajp.AjpReadListener


Possible path to io.undertow.server.protocol.ajp.AjpReadListener.<init>(io.undertow.server.protocol.ajp.AjpServerConnection, java.lang.String, io.undertow.server.protocol.ajp.AjpRequestParser, io.undertow.server.ConnectorStatisticsImpl):v
	io.undertow.server.protocol.ajp.AjpReadListener.<init>(io.undertow.server.protocol.ajp.AjpServerConnection, java.lang.String, io.undertow.server.protocol.ajp.AjpRequestParser, io.undertow.server.ConnectorStatisticsImpl):v
	io.undertow.server.protocol.ajp.AjpOpenListener.handleEvent(org.xnio.StreamConnection):v
	io.undertow.server.protocol.ajp.AjpOpenListener.handleEvent(org.xnio.StreamConnection):v
	io.undertow.server.protocol.ajp.AjpOpenListener.handleEvent(java.nio.channels.Channel):v
This is an implementation of org.xnio.ChannelListener printing path to constructors of io.undertow.server.protocol.ajp.AjpOpenListener


Possible path to io.undertow.server.protocol.ajp.AjpOpenListener.<init>(io.undertow.connector.ByteBufferPool, org.xnio.OptionMap):v
	io.undertow.server.protocol.ajp.AjpOpenListener.<init>(io.undertow.connector.ByteBufferPool, org.xnio.OptionMap):v
	io.undertow.Undertow.start():v
	io.quarkus.undertow.runtime.UndertowDeploymentTemplate.doServerStart(io.quarkus.undertow.runtime.HttpConfig, io.quarkus.runtime.LaunchMode, javax.net.ssl.SSLContext, java.util.concurrent.ExecutorService):v
	io.quarkus.undertow.runtime.UndertowDeploymentTemplate.startUndertow(io.quarkus.runtime.ShutdownContext, java.util.concurrent.ExecutorService, io.undertow.servlet.api.DeploymentManager, io.quarkus.undertow.runtime.HttpConfig, java.util.List, io.quarkus.runtime.LaunchMode):i
	io.quarkus.deployment.steps.UndertowBuildStep$boot12.deploy(io.quarkus.runtime.StartupContext):v
	io.quarkus.runner.ApplicationImpl1.doStart(java.lang.String[]):v
	io.quarkus.runtime.Application.doStart(java.lang.String[]):v
	io.quarkus.runtime.Application.start(java.lang.String[]):v
	io.quarkus.runtime.Application.run(java.lang.String[]):v
	io.quarkus.runner.GeneratedMain.main(java.lang.String[]):v
	com.oracle.svm.core.JavaMainWrapper.run(int, org.graalvm.nativeimage.c.type.CCharPointerPointer):i
	com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(int, org.graalvm.nativeimage.c.type.CCharPointerPointer):i


	at com.oracle.svm.core.util.UserError.abort(UserError.java:75)
	at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:218)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:733)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:523)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:441)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Unsupported features in 2 methods
Detailed message:
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Detected a direct/mapped ByteBuffer in the image heap. A direct ByteBuffer has a pointer to unmanaged C memory, and C memory from the image generator is not available at image run time. A mapped ByteBuffer references a file descriptor, which is no longer open and mapped at run time. The object was probably created by a class initializer and is reachable from a static field. By default, all class initialization is done during native image building.You can manually delay class initialization to image run time by using the option -H:ClassInitialization=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: 
	at parsing io.undertow.server.protocol.ajp.AjpServerRequestConduit.read(AjpServerRequestConduit.java:195)
Call path from entry point to io.undertow.server.protocol.ajp.AjpServerRequestConduit.read(ByteBuffer): 
	at io.undertow.server.protocol.ajp.AjpServerRequestConduit.read(AjpServerRequestConduit.java:183)
	at org.xnio.conduits.ConduitStreamSourceChannel.read(ConduitStreamSourceChannel.java:127)
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:158)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136)
	at io.undertow.server.protocol.http.HttpReadListener.run(HttpReadListener.java:402)
	at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:612)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:479)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:473)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
--------------------------------------------------------------------------------------------
-- WARNING: The above stack trace is not a real stack trace, it is a theoretical call tree---
-- If an interface has multiple implementations SVM will just display one potential call  ---
-- path to the interface. This is often meaningless, and what you actually need to know is---
-- the path to the constructor of the object that implements this interface.              ---
-- Quarkus has attempted to generate a more meaningful call flow analysis below          ---
---------------------------------------------------------------------------------------------

Possible path to io.undertow.server.protocol.ajp.AjpServerRequestConduit.read(java.nio.ByteBuffer):i
	io.undertow.server.protocol.ajp.AjpServerRequestConduit.read(java.nio.ByteBuffer):i
This is an implementation of org.xnio.conduits.StreamSourceConduit printing path to constructors of io.undertow.server.protocol.ajp.AjpServerRequestConduit


Possible path to io.undertow.server.protocol.ajp.AjpServerRequestConduit.<init>(org.xnio.conduits.StreamSourceConduit, io.undertow.server.HttpServerExchange, io.undertow.server.protocol.ajp.AjpServerResponseConduit, java.lang.Long, io.undertow.conduits.ConduitListener):v
	io.undertow.server.protocol.ajp.AjpServerRequestConduit.<init>(org.xnio.conduits.StreamSourceConduit, io.undertow.server.HttpServerExchange, io.undertow.server.protocol.ajp.AjpServerResponseConduit, java.lang.Long, io.undertow.conduits.ConduitListener):v
	io.undertow.server.protocol.ajp.AjpReadListener.createSourceConduit(org.xnio.conduits.StreamSourceConduit, io.undertow.server.protocol.ajp.AjpServerResponseConduit, io.undertow.server.HttpServerExchange):o
	io.undertow.server.protocol.ajp.AjpReadListener.handleEvent(org.xnio.channels.StreamSourceChannel):v
	io.undertow.server.protocol.ajp.AjpReadListener.handleEvent(java.nio.channels.Channel):v
This is an implementation of org.xnio.ChannelListener printing path to constructors of io.undertow.server.protocol.ajp.AjpReadListener


Possible path to io.undertow.server.protocol.ajp.AjpReadListener.<init>(io.undertow.server.protocol.ajp.AjpServerConnection, java.lang.String, io.undertow.server.protocol.ajp.AjpRequestParser, io.undertow.server.ConnectorStatisticsImpl):v
	io.undertow.server.protocol.ajp.AjpReadListener.<init>(io.undertow.server.protocol.ajp.AjpServerConnection, java.lang.String, io.undertow.server.protocol.ajp.AjpRequestParser, io.undertow.server.ConnectorStatisticsImpl):v
	io.undertow.server.protocol.ajp.AjpOpenListener.handleEvent(org.xnio.StreamConnection):v
	io.undertow.server.protocol.ajp.AjpOpenListener.handleEvent(org.xnio.StreamConnection):v
	io.undertow.server.protocol.ajp.AjpOpenListener.handleEvent(java.nio.channels.Channel):v
This is an implementation of org.xnio.ChannelListener printing path to constructors of io.undertow.server.protocol.ajp.AjpOpenListener


Possible path to io.undertow.server.protocol.ajp.AjpOpenListener.<init>(io.undertow.connector.ByteBufferPool, org.xnio.OptionMap):v
	io.undertow.server.protocol.ajp.AjpOpenListener.<init>(io.undertow.connector.ByteBufferPool, org.xnio.OptionMap):v
	io.undertow.Undertow.start():v
	io.quarkus.undertow.runtime.UndertowDeploymentTemplate.doServerStart(io.quarkus.undertow.runtime.HttpConfig, io.quarkus.runtime.LaunchMode, javax.net.ssl.SSLContext, java.util.concurrent.ExecutorService):v
	io.quarkus.undertow.runtime.UndertowDeploymentTemplate.startUndertow(io.quarkus.runtime.ShutdownContext, java.util.concurrent.ExecutorService, io.undertow.servlet.api.DeploymentManager, io.quarkus.undertow.runtime.HttpConfig, java.util.List, io.quarkus.runtime.LaunchMode):i
	io.quarkus.deployment.steps.UndertowBuildStep$boot12.deploy(io.quarkus.runtime.StartupContext):v
	io.quarkus.runner.ApplicationImpl1.doStart(java.lang.String[]):v
	io.quarkus.runtime.Application.doStart(java.lang.String[]):v
	io.quarkus.runtime.Application.start(java.lang.String[]):v
	io.quarkus.runtime.Application.run(java.lang.String[]):v
	io.quarkus.runner.GeneratedMain.main(java.lang.String[]):v
	com.oracle.svm.core.JavaMainWrapper.run(int, org.graalvm.nativeimage.c.type.CCharPointerPointer):i
	com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(int, org.graalvm.nativeimage.c.type.CCharPointerPointer):i

Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Detected a direct/mapped ByteBuffer in the image heap. A direct ByteBuffer has a pointer to unmanaged C memory, and C memory from the image generator is not available at image run time. A mapped ByteBuffer references a file descriptor, which is no longer open and mapped at run time. The object was probably created by a class initializer and is reachable from a static field. By default, all class initialization is done during native image building.You can manually delay class initialization to image run time by using the option -H:ClassInitialization=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: 
	at parsing io.undertow.server.protocol.ajp.AjpServerResponseConduit.flush(AjpServerResponseConduit.java:404)
Call path from entry point to io.undertow.server.protocol.ajp.AjpServerResponseConduit.flush(): 
	at io.undertow.server.protocol.ajp.AjpServerResponseConduit.flush(AjpServerResponseConduit.java:402)
	at org.xnio.conduits.ConduitStreamSinkChannel.flush(ConduitStreamSinkChannel.java:162)
	at io.undertow.server.protocol.framed.AbstractFramedChannel.flushSenders(AbstractFramedChannel.java:609)
	at io.undertow.server.protocol.framed.AbstractFramedChannel$5.run(AbstractFramedChannel.java:724)
	at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:612)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:479)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:473)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
--------------------------------------------------------------------------------------------
-- WARNING: The above stack trace is not a real stack trace, it is a theoretical call tree---
-- If an interface has multiple implementations SVM will just display one potential call  ---
-- path to the interface. This is often meaningless, and what you actually need to know is---
-- the path to the constructor of the object that implements this interface.              ---
-- Quarkus has attempted to generate a more meaningful call flow analysis below          ---
---------------------------------------------------------------------------------------------

Possible path to io.undertow.server.protocol.ajp.AjpServerResponseConduit.flush():b
	io.undertow.server.protocol.ajp.AjpServerResponseConduit.flush():b
This is an implementation of org.xnio.conduits.SinkConduit printing path to constructors of io.undertow.server.protocol.ajp.AjpServerResponseConduit


Possible path to io.undertow.server.protocol.ajp.AjpServerResponseConduit.<init>(org.xnio.conduits.StreamSinkConduit, io.undertow.connector.ByteBufferPool, io.undertow.server.HttpServerExchange, io.undertow.conduits.ConduitListener, boolean):v
	io.undertow.server.protocol.ajp.AjpServerResponseConduit.<init>(org.xnio.conduits.StreamSinkConduit, io.undertow.connector.ByteBufferPool, io.undertow.server.HttpServerExchange, io.undertow.conduits.ConduitListener, boolean):v
	io.undertow.server.protocol.ajp.AjpReadListener.handleEvent(org.xnio.channels.StreamSourceChannel):v
	io.undertow.server.protocol.ajp.AjpReadListener.handleEvent(java.nio.channels.Channel):v
This is an implementation of org.xnio.ChannelListener printing path to constructors of io.undertow.server.protocol.ajp.AjpReadListener


Possible path to io.undertow.server.protocol.ajp.AjpReadListener.<init>(io.undertow.server.protocol.ajp.AjpServerConnection, java.lang.String, io.undertow.server.protocol.ajp.AjpRequestParser, io.undertow.server.ConnectorStatisticsImpl):v
	io.undertow.server.protocol.ajp.AjpReadListener.<init>(io.undertow.server.protocol.ajp.AjpServerConnection, java.lang.String, io.undertow.server.protocol.ajp.AjpRequestParser, io.undertow.server.ConnectorStatisticsImpl):v
	io.undertow.server.protocol.ajp.AjpOpenListener.handleEvent(org.xnio.StreamConnection):v
	io.undertow.server.protocol.ajp.AjpOpenListener.handleEvent(org.xnio.StreamConnection):v
	io.undertow.server.protocol.ajp.AjpOpenListener.handleEvent(java.nio.channels.Channel):v
This is an implementation of org.xnio.ChannelListener printing path to constructors of io.undertow.server.protocol.ajp.AjpOpenListener


Possible path to io.undertow.server.protocol.ajp.AjpOpenListener.<init>(io.undertow.connector.ByteBufferPool, org.xnio.OptionMap):v
	io.undertow.server.protocol.ajp.AjpOpenListener.<init>(io.undertow.connector.ByteBufferPool, org.xnio.OptionMap):v
	io.undertow.Undertow.start():v
	io.quarkus.undertow.runtime.UndertowDeploymentTemplate.doServerStart(io.quarkus.undertow.runtime.HttpConfig, io.quarkus.runtime.LaunchMode, javax.net.ssl.SSLContext, java.util.concurrent.ExecutorService):v
	io.quarkus.undertow.runtime.UndertowDeploymentTemplate.startUndertow(io.quarkus.runtime.ShutdownContext, java.util.concurrent.ExecutorService, io.undertow.servlet.api.DeploymentManager, io.quarkus.undertow.runtime.HttpConfig, java.util.List, io.quarkus.runtime.LaunchMode):i
	io.quarkus.deployment.steps.UndertowBuildStep$boot12.deploy(io.quarkus.runtime.StartupContext):v
	io.quarkus.runner.ApplicationImpl1.doStart(java.lang.String[]):v
	io.quarkus.runtime.Application.doStart(java.lang.String[]):v
	io.quarkus.runtime.Application.start(java.lang.String[]):v
	io.quarkus.runtime.Application.run(java.lang.String[]):v
	io.quarkus.runner.GeneratedMain.main(java.lang.String[]):v
	com.oracle.svm.core.JavaMainWrapper.run(int, org.graalvm.nativeimage.c.type.CCharPointerPointer):i
	com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(int, org.graalvm.nativeimage.c.type.CCharPointerPointer):i


	at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:133)
	at com.oracle.graal.pointsto.BigBang.finish(BigBang.java:564)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:684)
	... 7 more
Error: Image build request failed with exit status 1
```

### LINKED ISSUE #2563: Native image fails for Hibernate Validator (Graal 19)
```
[INFO] [io.quarkus.creator.phase.nativeimage.NativeImagePhase] /home/david/local/jdk/graalvm-ce-19.0.0/bin/native-image -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -H:+ReportExceptionStackTraces -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime --initialize-at-build-time= -jar quarkus-integration-test-hibernate-validator-999-SNAPSHOT-runner.jar -J-Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:+PrintAnalysisCallTree -H:-AddAllCharsets -H:EnableURLProtocols=http -H:NativeLinkerOption=-no-pie -H:-SpawnIsolates -H:-JNI --no-server -H:-UseServiceLoaderFeature -H:+StackTrace
[quarkus-integration-test-hibernate-validator-999-SNAPSHOT-runner:3037]    classlist:   4,227.60 ms
[quarkus-integration-test-hibernate-validator-999-SNAPSHOT-runner:3037]        (cap):   1,025.14 ms
[quarkus-integration-test-hibernate-validator-999-SNAPSHOT-runner:3037]        setup:   2,277.93 ms
java.lang.ClassNotFoundException: com.fasterxml.jackson.module.jaxb.JaxbAnnotationIntrospector
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at io.quarkus.runner.AutoFeature.registerClass9(Unknown Source)
	at io.quarkus.runner.AutoFeature.beforeAnalysis(Unknown Source)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$7(NativeImageGenerator.java:667)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:64)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:667)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:523)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:441)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.ser.std.SqlDateSerializer
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at io.quarkus.runner.AutoFeature.registerClass10(Unknown Source)
	at io.quarkus.runner.AutoFeature.beforeAnalysis(Unknown Source)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$7(NativeImageGenerator.java:667)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:64)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:667)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:523)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:441)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
11:45:47,990 INFO  [org.hib.val.int.uti.Version] HV000001: Hibernate Validator 6.1.0.Alpha4
11:45:49,059 INFO  [org.jbo.threads] JBoss Threads version 3.0.0.Beta4
11:45:49,484 INFO  [org.xnio] XNIO version 3.7.1.Final
11:45:49,531 INFO  [org.xni.nio] XNIO NIO Implementation Version 3.7.1.Final
Warning: RecomputeFieldValue.FieldOffset automatic substitution failed. The automatic substitution registration was attempted because a call to sun.misc.Unsafe.objectFieldOffset(Field) was detected in the static initializer of org.jboss.threads.ThreadLocalResettingRunnable$Resetter. Detailed failure reason(s): The argument of Unsafe.objectFieldOffset(Field) is not a constant field., Could not determine the field where the value produced by the call to sun.misc.Unsafe.objectFieldOffset(Field) for the field offset computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store. 
Warning: RecomputeFieldValue.FieldOffset automatic substitution failed. The automatic substitution registration was attempted because a call to sun.misc.Unsafe.objectFieldOffset(Field) was detected in the static initializer of org.jboss.threads.ThreadLocalResettingRunnable$Resetter. Detailed failure reason(s): The argument of Unsafe.objectFieldOffset(Field) is not a constant field., Could not determine the field where the value produced by the call to sun.misc.Unsafe.objectFieldOffset(Field) for the field offset computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store. 
[quarkus-integration-test-hibernate-validator-999-SNAPSHOT-runner:3037]   (typeflow):  13,823.69 ms
[quarkus-integration-test-hibernate-validator-999-SNAPSHOT-runner:3037]    (objects):  14,861.74 ms
[quarkus-integration-test-hibernate-validator-999-SNAPSHOT-runner:3037]   (features):     665.15 ms
[quarkus-integration-test-hibernate-validator-999-SNAPSHOT-runner:3037]     analysis:  30,114.23 ms
Printing call tree to /home/david/src/java/quarkus/integration-tests/hibernate-validator/target/reports/call_tree_quarkus-integration-test-hibernate-validator-999-SNAPSHOT-runner_20190522_114620.txt
Printing list of used classes to /home/david/src/java/quarkus/integration-tests/hibernate-validator/target/reports/used_classes_quarkus-integration-test-hibernate-validator-999-SNAPSHOT-runner_20190522_114622.txt
Printing list of used packages to /home/david/src/java/quarkus/integration-tests/hibernate-validator/target/reports/used_packages_quarkus-integration-test-hibernate-validator-999-SNAPSHOT-runner_20190522_114622.txt
[quarkus-integration-test-hibernate-validator-999-SNAPSHOT-runner:3037]     (clinit):     578.99 ms
[quarkus-integration-test-hibernate-validator-999-SNAPSHOT-runner:3037]     universe:   1,462.22 ms
Fatal error: java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Cannot create java.lang.reflect.Method for class initializer
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:458)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:289)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:427)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:109)
Caused by: java.lang.IllegalArgumentException: Cannot create java.lang.reflect.Method for class initializer
	at jdk.vm.ci.hotspot.CompilerToVM.asReflectionExecutable(Native Method)
	at jdk.vm.ci.hotspot.HotSpotJDKReflection.getMethod(HotSpotJDKReflection.java:446)
	at jdk.vm.ci.hotspot.HotSpotJDKReflection.getMethodAnnotation(HotSpotJDKReflection.java:175)
	at jdk.vm.ci.hotspot.HotSpotResolvedJavaMethodImpl.getAnnotation(HotSpotResolvedJavaMethodImpl.java:540)
	at org.graalvm.util.GuardedAnnotationAccess.getAnnotation(GuardedAnnotationAccess.java:52)
	at org.graalvm.util.GuardedAnnotationAccess.isAnnotationPresent(GuardedAnnotationAccess.java:47)
	at com.oracle.svm.hosted.cenum.CEnumCallWrapperSubstitutionProcessor.lookup(CEnumCallWrapperSubstitutionProcessor.java:54)
	at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:128)
	at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:128)
	at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:128)
	at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:128)
	at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:128)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:396)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:376)
	at com.oracle.graal.pointsto.meta.AnalysisType.getClassInitializer(AnalysisType.java:962)
	at com.oracle.svm.hosted.classinitialization.TypeInitializerGraph.shouldPromoteToUnsafe(TypeInitializerGraph.java:196)
	at com.oracle.svm.hosted.classinitialization.TypeInitializerGraph.lambda$updateTypeInitializerSafety$3(TypeInitializerGraph.java:134)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1556)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.oracle.svm.hosted.classinitialization.TypeInitializerGraph.updateTypeInitializerSafety(TypeInitializerGraph.java:134)
	at com.oracle.svm.hosted.classinitialization.TypeInitializerGraph.computeInitializerSafety(TypeInitializerGraph.java:113)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.beforeCompilation(ClassInitializationFeature.java:215)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$doRun$2(NativeImageGenerator.java:572)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:64)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:572)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:441)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Image build request failed with exit status 1
```

### LINKED ISSUE #2792: GraalVM 19.0 Blocker List
- [x] oracle/graal/pull/649
- [x] oracle/graal/issues/1183
- [x] oracle/graal/issues/1320 (via oracle/graal/pulls/1321)
- [x] GraalVM 19 release with aforementioned fixes

Problems for post-19:
- [ ] oracle/graal/pull/1371

### LINKED ISSUE #2876: Update docs for Graal 19
`native-image` is no longer included by default. Need to install it by running `gu install native-image`, adapt documentation, adapt CI, adapt container images.

### PR DESCRIPTION
**Pull request by dmlloyd**
Fixes #2792, fixes #2412, fixes #2563, fixes #2438, fixes #2428, fixes #2410, fixes #2876.

### CODE REVIEW

**Comment by dmlloyd** [comment]
This is a draft because we still have a number of docs updates to do.  In particular #2876 is still outstanding.

File: core/deployment/src/main/java/io/quarkus/deployment/steps/SubstrateAutoFeatureStep.java [hunk 1]
```diff
@@ -29,7 +34,17 @@
 
 public class SubstrateAutoFeatureStep {
 
-    private static final String GRAAL_AUTOFEATURE = "io.quarkus/runner/AutoFeature";
+    private static final String GRAAL_AUTOFEATURE = "io/quarkus/runner/AutoFeature";
```
Comment (FroMage) [inline core/deployment/src/main/java/io/quarkus/deployment/steps/SubstrateAutoFeatureStep.java]: Oh WOW, we're replacing a partly binary class name. Can we introduce a convension for constant class names that lets us know if it's a class name, or a class binary name ('.' or '/')?

File: core/creator/src/main/java/io/quarkus/creator/phase/nativeimage/NativeImagePhase.java [hunk 2]
```diff
@@ -390,7 +390,10 @@ public void provideOutcome(AppCreator ctx) throws AppCreatorException {
             if (additionalBuildArgs != null) {
                 command.addAll(additionalBuildArgs);
             }
+            command.add("--initialize-at-build-time");
+            command.add("-H:+ReportExceptionStackTraces");
             command.add("-H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime"); //the default collection policy results in full GC's 50% of the time
+            command.add("--initialize-at-build-time=");
```
[the remark this answers is not in the document]
Comment (dmlloyd) [reply core/creator/src/main/java/io/quarkus/creator/phase/nativeimage/NativeImagePhase.java]: Ah no, this was a rebase error.  Will fix

File: core/deployment/src/main/java/io/quarkus/deployment/steps/SubstrateAutoFeatureStep.java [hunk 3]
```diff
@@ -241,12 +253,12 @@ SubstrateOutputBuildItem generateFeature(ClassOutputBuildItem output,
...
                     tc.writeArrayValue(farray, 0, fhandle);
                     tc.invokeStaticMethod(
-                            ofMethod("org/graalvm/nativeimage/RuntimeReflection", "register", void.class, Field[].class),
+                            ofMethod(RUNTIME_REFLECTION, "register", void.class, Field[].class),
                             farray);
                 }
             }
             CatchBlockCreator cc = tc.addCatch(Throwable.class);
-            //cc.invokeVirtualMethod(ofMethod(Throwable.class, "printStackTrace", void.class), cc.getCaughtException());
+            cc.invokeVirtualMethod(ofMethod(Throwable.class, "printStackTrace", void.class), cc.getCaughtException());
```
Comment (FroMage) [inline core/deployment/src/main/java/io/quarkus/deployment/steps/SubstrateAutoFeatureStep.java]: Is this meant to stay, or a debug thing that should stay commented out ?

Comment (dmlloyd) [reply core/deployment/src/main/java/io/quarkus/deployment/steps/SubstrateAutoFeatureStep.java]: I don't know really.  It does produce an exception from Jackson.  But I think that might be a legitimate problem.

File: core/creator/src/main/java/io/quarkus/creator/phase/nativeimage/NativeImagePhase.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (dmlloyd) [reply core/creator/src/main/java/io/quarkus/creator/phase/nativeimage/NativeImagePhase.java]: I've pushed up the fix for this.

**Comment by dmlloyd** [comment]
The native image failures are expected as CI isn't running 19.0.2 yet.

**Comment by FroMage** [comment]
This is waiting for @cescoffier to create a docker image.

File: core/creator/src/main/java/io/quarkus/creator/phase/nativeimage/NativeImagePhase.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (FroMage) [reply core/creator/src/main/java/io/quarkus/creator/phase/nativeimage/NativeImagePhase.java]: Cool

File: core/deployment/src/main/java/io/quarkus/deployment/steps/SubstrateAutoFeatureStep.java (hunk 1 above)
Comment (FroMage) [reply core/deployment/src/main/java/io/quarkus/deployment/steps/SubstrateAutoFeatureStep.java]: I know, I'm just saying we should once and for all decide on a suffix/terminology for these constants.  I've the same problem in my extensions.

**Comment by gsmet** [comment]
@dmlloyd there is a conflict now, can you rebase?
@cescoffier I think you have built an image? Could you reference its name here so that @dmlloyd can update the Azure pipelines with it?

**Comment by dmlloyd** [comment]
Rebased.   FYI I have no idea how to do anything with the Azure pipelines; we might have to ping @n1hility for that.

**Comment by gsmet** [comment]
OK, I think we can take care of it. My current understanding is that changing the image would be a code update. Not yet sure if we have to update the pipelines. I'll check that tomorrow once @cescoffier has prepared the image.

File: bom/pom.xml [hunk 4]
```diff
@@ -66,7 +66,7 @@
         <plexus-component-annotations.version>1.7.1</plexus-component-annotations.version>
         <!-- What we actually depend on for the annotations, as latest Graal
            is not available in Maven fast enough: -->
-        <graal-sdk.version>1.0.0-rc16</graal-sdk.version>
+        <graal-sdk.version>19.0.0</graal-sdk.version>
```
Comment (gsmet) [inline bom/pom.xml]: Shouldn't it be `19.0.2`?

File: core/creator/src/main/java/io/quarkus/creator/phase/nativeimage/NativeImagePhase.java [hunk 5]
```diff
@@ -390,6 +390,8 @@ public void provideOutcome(AppCreator ctx) throws AppCreatorException {
             if (additionalBuildArgs != null) {
                 command.addAll(additionalBuildArgs);
             }
+            command.add("--initialize-at-build-time=");
```
Comment (gsmet) [inline core/creator/src/main/java/io/quarkus/creator/phase/nativeimage/NativeImagePhase.java]: When you don't have a value, it initializes everything at build time?

File: core/creator/src/main/java/io/quarkus/creator/phase/nativeimage/NativeImagePhase.java [hunk 6]
```diff
@@ -390,6 +390,8 @@ public void provideOutcome(AppCreator ctx) throws AppCreatorException {
...
+            command.add("-H:+ReportExceptionStackTraces");
```
Comment (gsmet) [inline core/creator/src/main/java/io/quarkus/creator/phase/nativeimage/NativeImagePhase.java]: We have the same line conditioned by `if (reportExceptionStackTraces) {` a few lines below. I think we should just change the default value of `reportExceptionStackTraces` to `true`.

File: integration-tests/kogito/javax.inject.Named [hunk 7]
```diff
@@ -0,0 +1,4 @@
+org.drools.project.model.SessionRuleUnit_canDrinkKS
+org.drools.project.model.SessionRuleUnit_simpleKS
+io.quarkus.it.kogito.jbpm.OrdersProcess
+io.quarkus.it.kogito.jbpm.OrderItemsProcess
```
Comment (gsmet) [inline integration-tests/kogito/javax.inject.Named]: This file shouldn't be committed.

**Review by gsmet — CHANGES_REQUESTED** [review]
@dmlloyd I added a few comments/questions. Could you take care of them?

Thanks!

File: bom/pom.xml (hunk 4 above)
Comment (dmlloyd) [reply bom/pom.xml]: Those artifacts were not available last time I checked.

File: core/creator/src/main/java/io/quarkus/creator/phase/nativeimage/NativeImagePhase.java (hunk 5 above)
Comment (dmlloyd) [reply core/creator/src/main/java/io/quarkus/creator/phase/nativeimage/NativeImagePhase.java]: Right you have to give an empty value to indicate that build time init is the default.

File: core/creator/src/main/java/io/quarkus/creator/phase/nativeimage/NativeImagePhase.java (hunk 6 above)
Comment (dmlloyd) [reply core/creator/src/main/java/io/quarkus/creator/phase/nativeimage/NativeImagePhase.java]: OK I'll make that change.

File: integration-tests/kogito/javax.inject.Named (hunk 7 above)
Comment (dmlloyd) [reply integration-tests/kogito/javax.inject.Named]: Hmm I wonder what's generating this file.  It probably ought to be in `target`.

Comment (dmlloyd) [reply integration-tests/kogito/javax.inject.Named]: Fixed

File: core/creator/src/main/java/io/quarkus/creator/phase/nativeimage/NativeImagePhase.java (hunk 6 above)
Comment (dmlloyd) [reply core/creator/src/main/java/io/quarkus/creator/phase/nativeimage/NativeImagePhase.java]: Fixed

**Comment by dmlloyd** [comment]
All fixed @gsmet

File: bom/pom.xml (hunk 4 above)
Comment (gsmet) [reply bom/pom.xml]: I think it's there now: https://search.maven.org/artifact/org.graalvm.sdk/graal-sdk/19.0.2/jar ? Or is it a different one?

Comment (dmlloyd) [reply bom/pom.xml]: I can give it a try again.

Comment (dmlloyd) [reply bom/pom.xml]: Sure enough, seems to work.  Pushed

**Review by gsmet — APPROVED** [review]

**Comment by machi1990** [comment]
I remember asking here https://github.com/quarkusio/quarkus/pull/1602#discussion_r267631476 about the `FIXME..` comment in this method https://github.com/quarkusio/quarkus/blob/688ee16b0641ac60239c0c7970ce23b6cbff35ff/core/creator/src/main/java/io/quarkus/creator/phase/nativeimage/NativeImagePhase.java#L515-L528
. Is this the right moment to deal with the comment? 
If not, should we update the code in question to take into consideration `19.0.2`?

**Comment by dmlloyd** [comment]
> I remember asking here [#1602 (comment)](https://github.com/quarkusio/quarkus/pull/1602#discussion_r267631476) about the `FIXME..` comment in this method
> 
> https://github.com/quarkusio/quarkus/blob/688ee16b0641ac60239c0c7970ce23b6cbff35ff/core/creator/src/main/java/io/quarkus/creator/phase/nativeimage/NativeImagePhase.java#L515-L528
> 
> 
> . Is this the right moment to deal with the comment?
> If not, should we update the code in question to take into consideration `19.0.2`?

Let's address it in a follow-up PR.
