### PR TITLE
Make ArC intercept default methods

### LINKED ISSUE #7188: PanacheRepository injected methods cannot be made transactional
**Describe the bug**
If a class implementing the PanacheRepository is marked as `@Transactional`, methods injected by Quarkus are not transactional.

**Expected behavior**
All public methods should be transactional. When calling e.g. persist, a transaction should be created and operation should succeed.

**Actual behavior**
App throws `javax.persistence.TransactionRequiredException: Transaction is not active, consider adding @Transactional to your method to automatically activate one.`

**To Reproduce**
1. Create a class implementing PanacheRepository and mark it as `@Transactional`
2. Create test class, with non-transactional test method and injected repository
3. Call `persist` from a non-transactional method.

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Windows 10
 - Output of `java -version`: 1.8
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.3.0.Alpha1

**Additional context**
(Add any other context about the problem here.)

### PR DESCRIPTION
**Pull request by stuartwdouglas**
Fixes #7188

### CODE REVIEW

**Comment by mkouba** [comment]
This should resolve https://github.com/quarkusio/quarkus/issues/3533 too.

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Methods.java [hunk 1]
```diff
@@ -186,6 +186,13 @@ public MethodVisitor visitMethod(int access, String name, String descriptor, Str
                         classLevelBindings, bytecodeTransformerConsumer, transformUnproxyableClasses));
```
Comment (FroMage) [inline independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Methods.java:186]: OK, my bad, I didn't know interceptors also applied to superclass methods, otherwise I'd have suggested to handle interface default methods too. Great move.

**Review by FroMage — APPROVED** [review]

**Comment by FroMage** [comment]
AMQP test failed, but I don't really know if it could be related to this change. @cescoffier are you using ArC interceptors in AMQP? Could they be affected with interface default methods suddenly being intercepted? I'll restart the test to see if it changes.

**Review by mkouba — APPROVED** [review]
Looks good but I'd like to wait for the review from @manovotn too...

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Methods.java [hunk 2]
```diff
@@ -186,6 +186,13 @@ public MethodVisitor visitMethod(int access, String name, String descriptor, Str
...
             }
         }
+        for (DotName i : classInfo.interfaceNames()) {
+            ClassInfo interfaceInfo = getClassByName(beanDeployment.getIndex(), i);
+            if (interfaceInfo != null) {
+                finalMethodsFoundAndNotChanged.addAll(addInterceptedMethodCandidates(beanDeployment, interfaceInfo, candidates,
```
Comment (manovotn) [inline independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Methods.java:192]: Interface methods cannot be final.
It should be enough to call `addInterceptedMethodCandidates()` here.

**Review by manovotn — CHANGES_REQUESTED** [review]
Just one minor comment, otherwise looks good.

**Comment by stuartwdouglas** [comment]
Fixed.

**Review by manovotn — APPROVED** [review]
