### PR TITLE
Optimize OIDC tenant id resolution

### LINKED ISSUE #39417: OIDC `TenantConfigResolver` and `TenantResolver` are called even if the tenant id is already resolved
### Describe the bug

There are 2 cases right now where the OIDC tenant id is resolved before the tenant resolution code calling either `TenantConfigResolver` or `TenantResolver`, and other default resolvers starts runnning:
* When `@Tenant("sometenant")` annotation is used to resolve the tenant
* When the OIDC code flow session cookie is used to resolve it

In both cases, `TenantConfigResolver` or `TenantResolver` will still be called.

With `TenantResolver`,  the side-effect is minor, it just has to repeat the boilerplate:

```
String tenantId = getIdFromRoutingContext(rc);
if ((tenant != null) {
    return tenant;
}
``` 

but with `TenantConfigResolver` which returns an OidcTenantConfig instance, it is much worse, because unless it is a very limited number of configurations which can be just stored easily in the Map, users have to reread this config from some external source, or think of some more involved caching support. This is why I'm qualifying it as a bug.

But it should not be required since Quarkus already has the knowledge of the resolved OIDC tenants.

CC @calvernaz

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sberyozkin**
Fixes #39417

This requires some tests and actually setting the extra attribute during the annotation processing :-)

### CODE REVIEW

**Comment by sberyozkin** [comment]
@michalvavrik I've updated tests now to verify that the tenant config resolver is called only during the first request or when the session cookie resolves the tenant with the resolver choosing to let this tenant id stay (this is what I wanted to retain, to let the resolvers block the possibly bogus tenant ids on some paths), as well as added log messages which can help tracing how exactly the tenant id has been set.

**Review by michalvavrik — APPROVED** [review]
looks very good

**Comment by sberyozkin** [comment]
Thanks @michalvavrik.
Hi @gastaldi Can you please have a look and approve if it also looks fine to you ? It should be ready to go since @michalvavrik approved.

The PR is primarily about avoiding calling custom OIDC `TenantConfigResolver` and `TenantResolver` tenant resolvers if the tenant id is already known to be set by the `@Tenant` annotation. It also ensures that if the tenant id has already been deduced from the OIDC session cookie, all the available OIDC resolvers, including `TenantConfigResolver` and `TenantResolver` but also the path based resolvers get a chance to overwrite that tenant id if needed. And also adds logs to make it easy to trace where the tenant id was set up.

**Review by gastaldi — APPROVED** [review]

**Comment by sberyozkin** [comment]
Thanks @gastaldi

**Comment by sberyozkin** [comment]
@gsmet Hi, I proposed backports, but I've just noticed a related quickstart failure, I'll have a look and re-add the backport suggestions once I figure out what is wrong with that test

**Comment by sberyozkin** [comment]
@michalvavrik @gastaldi I'm removing the release breaking change, because using a shared session cookie path for more than one OIDC `web-app` application makes no practical sense at all, I don't think anyone would allow it. The failing test in the quickstarts was passing due to some luck before because currently, the session cookie split into chunks leads to the wrong tenant calculation - in fact that multi-tenancy demo does not work even with 3.9 if you access it from the browser.
I have the PR sorting out that coming soon.
I'll add a backport to 3.9 back but will keep 3.8 off the list for now

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/DefaultTenantConfigResolver.java [hunk 1]
```diff
@@ -166,7 +180,11 @@ private TenantConfigContext getStaticTenantContext(RoutingContext context) {
     }
 
     private String resolveStaticTenantId(RoutingContext context) {
-        String tenantId;
+        String tenantId = context.get(OidcUtils.TENANT_ID_ATTRIBUTE);
+        if (isTenantSetByAnnotation(context, tenantId)) {
```
Comment (michalvavrik) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/DefaultTenantConfigResolver.java:184]: @sberyozkin you changed the order of resolvers. Annotation-based should be behind `tenantResolver` according to the https://quarkus.io/version/main/guides/security-openid-connect-multitenancy#static-tenant-resolution. I remember this change was discussed, but effectively documented order is different now?

I am asking because I did some tweaks to this code and need to know if this order should be kept now. I think it's fine, we just should change docs. Your call.

Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/DefaultTenantConfigResolver.java:184]: @michalvavrik Sure, somewhere, as part of discussing this issue, I suggested the annotation based resolution check should be made before asking the custom resolvers to do the work, I'll tweak the docs

Comment (michalvavrik) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/DefaultTenantConfigResolver.java:184]: Thank you, I wasn't sure.

Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/DefaultTenantConfigResolver.java:184]: As otherwise it would defeat the purpose of using those annotations :-)

**Comment by gsmet** [comment]
This doesn't apply cleanly so I will skip backporting.

**Comment by sberyozkin** [comment]
@gsmet OK, I'll have a look if it can work for 3.9.3
