### PR TITLE
Populate ingress fields (annotations and rules) for kind and minikube resources

### LINKED ISSUE #42294: quarkus-kind does not add ingress annotations
### Describe the bug

Having dependencies on `quarkus-kubernetes` and `quarkus-kind`, and defining an Ingress annotation, annotation is not
present in `target/kubernetes/kind.yml`

### Expected behavior

`kind.yml` should contain ingress annotation, as `kubernetes.yml` contains it

### Actual behavior

`kind.yml` does not contains ingress annotation.

### How to Reproduce?

1. Add dependencies to ` quarkus-kubernetes` and to `quakus-kind` :
```
<dependency>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-kubernetes</artifactId>
</dependency>
<dependency>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-kind</artifactId>
</dependency>
```

2. Expose ingress and define an ingress annotation in `application.properties`
```
quarkus.kubernetes.ingress.expose=true
quarkus.kubernetes.ingress.annotations."nginx.ingress.kubernetes.io/rewrite-target"=/$2
```
4. Build application, with `mvn package`
5. Check `target/kubernetes/kubernetes.xml`, it contains ingress annotation
```
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.12.3
    app.quarkus.io/vcs-uri: https://git...
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  labels:
```
7. Check `target/kubernetes/kind.xml`, it **does not** contains ingress annotation
```
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.12.3
    app.quarkus.io/vcs-uri: https://git.clever-age.net/oxiane/gitlab-oxiane/formation/accessoires_cours/tp-quarkus-essentiel.git
  labels:
```

### Output of `uname -a` or `ver`

Darwin paris-105.local 22.6.0 Darwin Kernel Version 22.6.0: Mon Apr 22 20:54:28 PDT 2024; root:xnu-8796.141.3.705.2~1/RELEASE_X86_64 x86_64

### Output of `java -version`

java version "21" 2023-09-19 LTS Java(TM) SE Runtime Environment (build 21+35-LTS-2513) Java HotSpot(TM) 64-Bit Server VM (build 21+35-LTS-2513, mixed mode, sharing)

### Quarkus version or git rev

3.12.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

$ mvn -v Apache Maven 3.9.3 (21122926829f1ead511c958d89bd2f672198ae9f) Maven home: /Users/cmarchand/applications/apache-maven-3.9.3 Java version: 21, vendor: Oracle Corporation, runtime: /Users/cmarchand/applications/java/jdk-21.jdk/Contents/Home Default locale: fr_FR, platform encoding: UTF-8 OS name: "mac os x", version: "13.6.7", arch: "x86_64", family: "mac"

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mcruzdev**
- Fixes: #42294

### CODE REVIEW

File: extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/DevClusterHelper.java [hunk 1]
```diff
@@ -153,6 +157,23 @@ public static List<DecoratorBuildItem> createDecorators(String clusterKind,
                         ports,
                         config.ports));
 
+        for (Map.Entry<String, String> annotation : config.getIngress().getAnnotations().entrySet()) {
+            result.add(new DecoratorBuildItem(clusterKind,
+                    new AddAnnotationDecorator(name, annotation.getKey(), annotation.getValue(), INGRESS)));
+        }
+
+        for (IngressRuleConfig rule : config.ingress.rules.values()) {
```
Comment (metacosm) [inline extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/DevClusterHelper.java:165]: Why use the getter in one instance and not in the other one?

File: extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/DevClusterHelper.java [hunk 2]
```diff
@@ -153,6 +157,23 @@ public static List<DecoratorBuildItem> createDecorators(String clusterKind,
...
+            result.add(new DecoratorBuildItem(clusterKind, new AddIngressRuleDecorator(name, port,
```
Comment (metacosm) [inline extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/DevClusterHelper.java:166]: This is also doing more than just dealing with the annotations since it also adds ingress rules (which is fine, by the way, at least in my opinion)

**Review by metacosm — APPROVED** [review]

**Review by iocanel — APPROVED** [review]
LGTM

**Review by cescoffier — APPROVED** [review]
