### PR TITLE
Normalize uri template name to be a valid regex groupname

### LINKED ISSUE #25258: RESTEasy reactive illegally restricts JAX-RSpath parameter names
### Describe the bug

Consider the following JAX-RS resource:
```
@Produces(MediaType.APPLICATION_JSON)
@Path("/")
public class ContextNotWorking {
    @GET
    @Path("foo/{something-with-dash:[^a]*}")
	public Response doSomething(@PathParam("something-with-dash") String param) {
	    return Response.noContent().build();
	}
}
```
Note that path parameter _something-with-dash_. According to the Javadoc of @Path the dash is an allowed character in a parameter name. However, if you try to run this with resteasy-reactive startup fails with
```
Caused by: java.lang.IllegalArgumentException: Path '/foo/{something-with-dash:[^a]*}' of method 'org.knime.xxx.ContextNotWorking#doSomething' is not a valid expression
	at org.jboss.resteasy.reactive.server.processor.ServerEndpointIndexer.validateMethodPath(ServerEndpointIndexer.java:226)
	at org.jboss.resteasy.reactive.server.processor.ServerEndpointIndexer.handleAdditionalMethodProcessing(ServerEndpointIndexer.java:218)
	at io.quarkus.resteasy.reactive.server.deployment.QuarkusServerEndpointIndexer.handleAdditionalMethodProcessing(QuarkusServerEndpointIndexer.java:164)
	at io.quarkus.resteasy.reactive.server.deployment.QuarkusServerEndpointIndexer.handleAdditionalMethodProcessing(QuarkusServerEndpointIndexer.java:32)
	at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.createResourceMethod(EndpointIndexer.java:657)
	... 14 more
Caused by: java.util.regex.PatternSyntaxException: named capturing group is missing trailing '>' near index 12
(?<something-with-dash>[^a]*)$
            ^
	at java.base/java.util.regex.Pattern.error(Pattern.java:2027)
	at java.base/java.util.regex.Pattern.groupname(Pattern.java:2949)
	at java.base/java.util.regex.Pattern.group0(Pattern.java:2995)
	at java.base/java.util.regex.Pattern.sequence(Pattern.java:2123)
	at java.base/java.util.regex.Pattern.expr(Pattern.java:2068)
	at java.base/java.util.regex.Pattern.compile(Pattern.java:1782)
	at java.base/java.util.regex.Pattern.<init>(Pattern.java:1428)
	at java.base/java.util.regex.Pattern.compile(Pattern.java:1068)
	at org.jboss.resteasy.reactive.server.mapping.URITemplate.<init>(URITemplate.java:157)
	at org.jboss.resteasy.reactive.server.processor.ServerEndpointIndexer.validateMethodPath(ServerEndpointIndexer.java:223)
	... 18 more
```
It seems he reactive extension does not comply with the JAX-RS specification.
The same class works fine with the non-reactive version of RESTEasy.
Patterns in Java indeed do *not* allow dashes in capture group names.

### Expected behavior

Code that is legal according to the JAX-RS specification should work in Quarkus.

### Actual behavior

Quarkus startup fails with the error above.

### How to Reproduce?

Try to run the provided JAX-RS resource class with _quarkus-resteasy-reactive_.

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

17

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.8.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Postremus**
See https://github.com/quarkusio/quarkus/issues/25258#issuecomment-1113714298 for a description of what is allowed in a uri template.

These changes add support for `_-.\d` in the component's name.

Previosly, the component name was directly used as a capture group name.
The above mentioned characters however are not allowed at some positions in groupnames however.

Therefore I added a simple normalization, making sure the component name only contains characters in the range `A-Za-z0-9`.

Also, I added support for spaces in before and after the name, and before and after the regex part.
The ABNF (see comment above) allows WSP in these cases, which is 0x09 (HTAB) or 0x20 (SPACE). I don't believe however that tabs are that often used inside an `@Path`.

fixes #25258

### CODE REVIEW

File: independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/mapping/URITemplate.java [hunk 1]
```diff
@@ -124,38 +125,52 @@ public URITemplate(String template, boolean prefixMatch) {
...
+                String normalizedCaptureGroupName = "capture";
+                // ensure uniqueness in cases where normalization would result in the same name being used.
+                normalizedCaptureGroupName += component.name.hashCode();
+                normalizedCaptureGroupName += component.name;
+                normalizedCaptureGroupName = normalizedCaptureGroupName.replaceAll("[^a-zA-Z\\d]", "");
+
+                regexAggregator.append("(?<").append(normalizedCaptureGroupName).append(">")
+                        .append(component.literalText.trim())
                         .append(")");
+                groupAggregator.add(normalizedCaptureGroupName + "");
```
Comment (gsmet) [inline independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/mapping/URITemplate.java:164]: Might be stupid as I haven't looked at the whole thing but could we simply use index based groups such as `group1` instead of generating something complex?

Comment (stuartwdouglas) [reply independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/mapping/URITemplate.java:165]: I think for valid names you can reference them later in the regex, so you definitely need to preserve the valid ones. For invalid ones I think anything unique would be fine.

Comment (gsmet) [reply independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/mapping/URITemplate.java:165]: But you use the pattern to reference them? It looks extremely weird.

Comment (stuartwdouglas) [reply independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/mapping/URITemplate.java:165]: So technically if you have @Path("someName:{someRegex}") on the class, you can then use @Path("otherName:{\\ksomeName}") to match whatever the original regex matched.

I don't think this is very common, but its why you need to actually use the name in the regex rather than just an index.

**Comment by gsmet** [comment]
@Postremus is it ready for review? @stuartwdouglas any chance you could have a look, we build the 2.9.0.Final core artifacts tomorrow morning Paris time.

File: independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/mapping/URITemplate.java (hunk 1 above)
Comment (Postremus) [reply independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/mapping/URITemplate.java]: I implemented the requested changes. Now the groupname is by default the component name, and only changed to be `group1` (and so on) if it is invalid.

**Review by stuartwdouglas — APPROVED** [review]
LGTM assuming the tests pass
