### PR TITLE
Exit in dev mode if port is in use

### LINKED ISSUE #8416: if something is already running on port startup has no warning /signs of problems
**Describe the bug**
Start two quarkus:dev or something else confilciting on port 8080 and your second run will not show any warning/errors.

**Expected behavior**
Warning or even full error if ports cannot be bound.

### PR DESCRIPTION
**Pull request by stuartwdouglas**
If it is not possible to start a HTTP endpoint to listen
for changes we just immediatly exit with a non-zero exit
code.

Fixes #8416

### CODE REVIEW

**Review by geoand — APPROVED** [review]

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/VertxHttpRecorder.java [hunk 1]
```diff
@@ -154,7 +154,13 @@ public static void startServerAfterFailedStart() {
         }
         VertxConfiguration vertxConfiguration = new VertxConfiguration();
         ConfigInstantiator.handleObject(vertxConfiguration);
```
Comment (gsmet) [inline extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/VertxHttpRecorder.java:156]: Maybe move the two lines above to the `if` too?

BTW, this change seems unrelated to the issue at hand. Just checking it was meant for this patch?

**Review by gsmet — CHANGES_REQUESTED** [review]

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/VertxHttpRecorder.java (hunk 1 above)
Comment (stuartwdouglas) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/VertxHttpRecorder.java:156]: This stops an extra vert.x hanging around, before I resorted to the System.exit() blunt instrument I was looking for a normal JVM shutdown, but this extra vert.x was stopping it.

**Review by gastaldi — APPROVED** [review]
LGTM

**Review by gsmet — APPROVED** [review]
