### PR TITLE
Prevent multiple contributions to Panache's "entityToPersistenceUnit"  from overriding each other

### LINKED ISSUE #50955: Entity not found?
### Describe the bug

I have an app (https://github.com/edeandrea/non-deterministic-no-problem) that builds/tests fine with Quarkus 3.28.4, but when upgrading to 3.29.x it starts breaking with

`Entity 'org.parasol.model.audit.ServiceCompleteAuditEvent' was not found. Did you forget to annotate your Panache Entity classes with '@Entity'?`

The entities have `@Entity` and use inheritance with discriminator values

https://github.com/edeandrea/non-deterministic-no-problem/blob/main/src/main/java/org/parasol/model/audit/ServiceStartedAuditEvent.java for example is one of the entities

I didn't see anything related in the release notes

### Expected behavior

I would expect upgrading to Quarkus 3.29.x to work

### Actual behavior

It doesn't

### How to Reproduce?

1. Clone https://github.com/edeandrea/non-deterministic-no-problem)
2. `./mvnw test -Dtest=AuditEventRepositoryTests`
3. Run `./mvnw test -Dtest=AuditEventRepositoryTests -Dquarkus.platform.version=3.28.4` to see it succeed

### Output of `uname -a` or `ver`

`Darwin edeandrea-m4max 25.0.0 Darwin Kernel Version 25.0.0: Wed Sep 17 21:41:26 PDT 2025; root:xnu-12377.1.9~141/RELEASE_ARM64_T6041 arm64`

### Output of `java -version`

```
openjdk 21.0.8 2025-07-15 LTS
OpenJDK Runtime Environment Temurin-21.0.8+9 (build 21.0.8+9-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.8+9 (build 21.0.8+9-LTS, mixed mode, sharing)
```

### Quarkus version or git rev

3.29.x

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

```
Apache Maven 3.9.11 (3e54c93a704957b63ee3494413a2b544fd3d825b)
Maven home: /Users/edeandre/.m2/wrapper/dists/apache-maven-3.9.11/a2d47e15
Java version: 21.0.8, vendor: Eclipse Adoptium, runtime: /Users/edeandre/.sdkman/candidates/java/21.0.8-tem
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "26.0.1", arch: "aarch64", family: "mac"
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by yrodiere**
This should fix the seemingly random "Entity not found" when using Kotlin.

* Fixes #50955

### CODE REVIEW

**Review by lucamolteni — APPROVED** [review]

**Comment by yrodiere** [comment]
Thanks for the review @lucamolteni . @FroMage, mind adding your stamp here so I can merge? :)

File: extensions/panache/hibernate-orm-panache-common/runtime/src/main/java/io/quarkus/hibernate/orm/panache/common/runtime/AbstractJpaOperations.java [hunk 1]
```diff
@@ -25,12 +25,22 @@
...
-    public static void setEntityToPersistenceUnit(Map<String, String> map, boolean incomplete) {
-        entityToPersistenceUnit = Collections.unmodifiableMap(map);
-        entityToPersistenceUnitIsIncomplete = incomplete;
+    private static final Map<String, String> entityToPersistenceUnit = new HashMap<>();
+    private static volatile Boolean entityToPersistenceUnitIsIncomplete = null;
+
+    // Putting synchronized here because fields involved were marked as volatile initially,
+    // so I expect recorders can be called concurrently?
+    public static synchronized void addEntityTypesToPersistenceUnit(Map<String, String> map, boolean incomplete) {
+        // Note: this may be called multiple times if an app uses both Java and Kotlin.
```
Comment (FroMage) [inline extensions/panache/hibernate-orm-panache-common/runtime/src/main/java/io/quarkus/hibernate/orm/panache/common/runtime/AbstractJpaOperations.java:34]: But what is the rationale for allowing this, though?
Why not collect entities in a shared build item and call this recorder from a shared build step?
This would feel more proper and solid.

Comment (yrodiere) [reply extensions/panache/hibernate-orm-panache-common/runtime/src/main/java/io/quarkus/hibernate/orm/panache/common/runtime/AbstractJpaOperations.java:34]: > But what is the rationale for allowing this, though?

The rationale is "that's already what we're doing"

> Why not collect entities in a shared build item and call this recorder from a shared build step?
> This would feel more proper and solid.

I suppose it could work as well, but I really don't see how it would be better. It's just two possible solutions?

Comment (FroMage) [reply extensions/panache/hibernate-orm-panache-common/runtime/src/main/java/io/quarkus/hibernate/orm/panache/common/runtime/AbstractJpaOperations.java:34]: I think we're currently doing that by accident, and the current bug is proof that this was not by design, because nobody would design a system on purpose that works randomly.

I would prefer it if the recorder method was only called once. Unless we know for sure that the Java processor records only Java entities, and the Koltin processor records only Kotlin entities, and they both compose and they should really be combined, and the contract is that every extention calls the recorder to keep adding to the list.

Which is probably what you're saying.

Comment (yrodiere) [reply extensions/panache/hibernate-orm-panache-common/runtime/src/main/java/io/quarkus/hibernate/orm/panache/common/runtime/AbstractJpaOperations.java:34]: Yes, I know for sure the recorder gets called twice, because both the Java and Kotlin side call it even if they have no entities to contribute.

I'm saying we can combine this stuff through new build items, or in the AbstractJpaOperations static method, and it amounts to the same result, with the notable difference that one of these solutions is already implemented and ready to merge :)

Comment (yrodiere) [reply extensions/panache/hibernate-orm-panache-common/runtime/src/main/java/io/quarkus/hibernate/orm/panache/common/runtime/AbstractJpaOperations.java:34]: > Yes, I know for sure the recorder gets called twice, because both the Java and Kotlin side call it even if they have no entities to contribute.

Though it's not too far-fetched to imagine an application with Kotlin entities + some Java entities (e.g. from a legacy, imported library)

Comment (FroMage) [reply extensions/panache/hibernate-orm-panache-common/runtime/src/main/java/io/quarkus/hibernate/orm/panache/common/runtime/AbstractJpaOperations.java:34]: Well, whatever.

**Review by FroMage — APPROVED** [review]

**Comment by yrodiere** [comment]
Thank you @FroMage!

**Comment by rsvoboda** [comment]
@yrodiere why is this proposed for 3.27?

https://github.com/quarkusio/quarkus/issues/50955 says that the app builds/tests fine with Quarkus 3.28.4, problem was in 3.29.z.

**Comment by yrodiere** [comment]
@rsvoboda the problem I fixed was probably present in 3.27 given the code involved, which is why I proposed to backport to 3.27.
But it turned out the problem I fixed was not actually #50955 -- which was fixed in https://github.com/quarkusio/quarkus/pull/51213 instead.

So... we can probably skip backporting this, especially if it conflicts.
