### PR TITLE
Bring JBossNettyLoggerFactory implementation in line with other implementations

### LINKED ISSUE #27605: Malformed DNS message on MacOS
### Describe the bug

When starting on macOS this message is printed:
> Can not find {} in the classpath, fallback to system defaults. This may result in incorrect DNS resolutions on MacOS.

Notice the `{}` in the final message.

### Expected behavior

Message tells me what can't be found.

### Actual behavior

☝️

### How to Reproduce?

Start an application in dev mode on macOS.

### Output of `uname -a` or `ver`

macOS 12

### Output of `java -version`

OpenJDK 17.0.2

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.12.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.4.2

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
This change essentially makes all the method implementations behave in the same
way Netty's built-in implementations do.

Fixes: #27605

### CODE REVIEW

File: extensions/netty/deployment/src/main/java/io/quarkus/netty/deployment/JBossNettyLoggerFactory.java [hunk 1]
```diff
@@ -149,29 +221,466 @@ public boolean isErrorEnabled() {
...
+            }
+        }
+
+        private void error0(String msg, Throwable t) {
             log.error(msg, t);
         }
 
     }
 
+    // MessageFormatter class copied from Netty because its methods are package private
```
Comment (dmlloyd) [inline extensions/netty/deployment/src/main/java/io/quarkus/netty/deployment/JBossNettyLoggerFactory.java:266]: 😩 Can we also put in an enhancement request upstream to Netty to make these public? Otherwise it defeats the purpose of having the logger be pluggable after all.

**Review by dmlloyd — APPROVED** [review]

File: extensions/netty/deployment/src/main/java/io/quarkus/netty/deployment/JBossNettyLoggerFactory.java (hunk 1 above)
Comment (geoand) [reply extensions/netty/deployment/src/main/java/io/quarkus/netty/deployment/JBossNettyLoggerFactory.java:266]: Yup: https://github.com/netty/netty/issues/12761

Comment (geoand) [reply extensions/netty/deployment/src/main/java/io/quarkus/netty/deployment/JBossNettyLoggerFactory.java:266]: Once https://github.com/netty/netty/pull/12763 is in and we have new Netty version in Quarkus that makes the methods public, we can delete the copied code

Comment (geoand) [reply extensions/netty/deployment/src/main/java/io/quarkus/netty/deployment/JBossNettyLoggerFactory.java:266]: https://github.com/quarkusio/quarkus/pull/28126 now removes the copied code
