### PR TITLE
ArC - enable implementing all types of interception with single method

### LINKED ISSUE #15570: @PostConstruct interceptor method returning Object works only if it's private
InterceptorGenerator incorrectly assumes that return type from a @PostConstruct method is void, but the specification allows Object too (https://docs.oracle.com/javaee/7/api/javax/annotation/PostConstruct.html).

When the method is private, it will work because InterceptorGenerator will use a reflection fallback and find the method to invoke by name and param types only (so the return type doesn't matter): https://github.com/quarkusio/quarkus/blob/1.12/independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/InterceptorGenerator.java#L246

### PR DESCRIPTION
**Pull request by mkouba**
- resolves #15570

### CODE REVIEW

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/InterceptorInfo.java [hunk 1]
```diff
@@ -103,6 +91,22 @@
         }
     }
 
+    private MethodInfo validateSignature(MethodInfo method) {
+        List<Type> parameters = method.parameters();
+        if (parameters.size() != 1 || !parameters.get(0).name().equals(DotNames.INVOCATION_CONTEXT)) {
```
Comment (manovotn) [inline independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/InterceptorInfo.java:96]: Shouldn't we also allow `ArcInvocationContext`?

**Review by manovotn — CHANGES_REQUESTED** [review]

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/InterceptorInfo.java (hunk 1 above)
Comment (mkouba) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/InterceptorInfo.java:96]: That's a good point but I don't think it would work right now... let me check.

Comment (mkouba) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/InterceptorInfo.java:96]: Hm, this would actually require some more work, because we also generate the interceptor beans that implement `javax.enterprise.inject.spi.Interceptor.intercept(InterceptionType, T, InvocationContext)` etc. We can create a feature request though. Currently, you would need to cast the `InvocationContext` inside the interceptor method. @manovotn WDYT?

Comment (manovotn) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/InterceptorInfo.java:96]: Fair enough, it just occurred to me when I saw the code :)

**Review by manovotn — APPROVED** [review]

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/InterceptorInfo.java (hunk 1 above)
Comment (manovotn) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/InterceptorInfo.java:96]: Created https://github.com/quarkusio/quarkus/issues/15660
