### PR TITLE
Hibernate Validator: don't skip interface annotation lookup if impl method has annotations

### LINKED ISSUE #11341: @InterceptorBinding based annotation disables ReST validation
**Describe the bug**
1) I have a rest Interface "IGreetingResource" which defines a method annotated with @Valid and @Size
2) there is a rest controller "GreetingResource" which implements "TestApi" annotated with @Override

Validation works like expected unless I add a custom annotation to GreetingResource. That annotation itself is marked with @InterceptorBinding. Validation is not executed anymore unless I add the @Valid annotation explicitly to "GreetingResource". If I remove @InterceptorBinding validation works again so it seems to be connected to @InterceptorBinding.

It also seems to be a difference whether the @Valid annotation is placed in the interface or in the implementing class. In the interface it returns a 500 status code - in the class it returns a 400 which looks better to me. Maybe this issue is a little bit bigger than I describe here.

**Expected behavior**
Validation works.

**Actual behavior**
Validation is deactivated in combination with custom annotation.

**To Reproduce**
1. clone https://github.com/harthorst/quarkus-reproducer-interceptorbinding
2. run it and see the failing GreetingResourceTest

### PR DESCRIPTION
**Pull request by famod**
Fixes #11341 (the main problem, not the [400 vs. 500 problem](https://github.com/quarkusio/quarkus/issues/11341#issuecomment-673146350)).

This basically just drops the `method.annotations().isEmpty()` check in `MethodValidatedAnnotationsTransformer`.

Before this fix the added test yielded:
```
[ERROR] Failures:
[ERROR]   HibernateValidatorFunctionalityTest.testRestEndPointInterfaceValidationWithAnnotationOnImplMethod:93 1 expectation failed.
Expected status code <500> but was <200>.
```

Turns out that the custom annotation _does indeed_ have to be annotated with `@InterceptorBinding`, otherwise the test will _not_ show the behaviour as reported in #11341 (results in 400 instead of 200). I did _not_ dig deeper to find out why this makes a difference (maybe some jandex thing).

### CODE REVIEW

File: integration-tests/hibernate-validator/src/test/java/io/quarkus/it/hibernate/validator/HibernateValidatorFunctionalityTest.java [hunk 1]
```diff
@@ -69,6 +69,36 @@ public void testRestEndPointValidation() {
                 .body(is("42"));
     }
 
+    @Test
+    public void testRestEndPointInterfaceValidation() {
+        RestAssured.when()
+                .get("/hibernate-validator/test/rest-end-point-interface-validation/plop/")
+                .then()
+                // 500 until this is fixed: https://github.com/quarkusio/quarkus/issues/11341#issuecomment-673146350
```
Comment (famod) [inline integration-tests/hibernate-validator/src/test/java/io/quarkus/it/hibernate/validator/HibernateValidatorFunctionalityTest.java:77]: So we could discuss this 400 vs. 500 problem in this PR (as suggested here: https://github.com/quarkusio/quarkus/issues/11341#issuecomment-673434667) or we could do it separately (Zulip?).

The main challenge I see is that `MethodValidatedAnnotationsTransformer` is only aware of a single transformation target at a time but to check potentially present interfaces for JAX-RS annotations, the transformer needs `MethodInfo`/`ClassInfo` for those interfaces.
I guess the constructor of `MethodValidatedAnnotationsTransformer` has to be extended with more context...

**Comment by famod** [comment]
I don't think those `[Add|Remove][Gradle|Maven]ExtensionsTest` failures are related to my change.

/cc @gsmet

**Comment by gsmet** [comment]
@famod no the issue is fixed in master, could you rebase?

File: integration-tests/hibernate-validator/src/test/java/io/quarkus/it/hibernate/validator/HibernateValidatorFunctionalityTest.java (hunk 1 above)
Comment (gsmet) [reply integration-tests/hibernate-validator/src/test/java/io/quarkus/it/hibernate/validator/HibernateValidatorFunctionalityTest.java:77]: I **think** you could do something like `method.declaringClass().interfaceTypes()` and call `.annotations()` on the items of the list.

Comment (gsmet) [reply integration-tests/hibernate-validator/src/test/java/io/quarkus/it/hibernate/validator/HibernateValidatorFunctionalityTest.java:77]: The issue with it is that you basically only has a view of all the annotations of the type, they are not split by method.

I **think** you could make calls to the bean archive index by getting it through the `BeanArchiveIndexBuildItem`. But I'm not entirely sure it's safe to use it in the `AnnotationsTransformer`. @mkouba WDYT?

**Review by gsmet — APPROVED** [review]

**Comment by famod** [comment]
Not sure what's wrong with this JDK14 job. Seems like an infra problem.

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Merged, thanks! Let's wait for @mkouba 's advice for the remaining issue.

File: integration-tests/hibernate-validator/src/test/java/io/quarkus/it/hibernate/validator/HibernateValidatorFunctionalityTest.java (hunk 1 above)
Comment (famod) [reply integration-tests/hibernate-validator/src/test/java/io/quarkus/it/hibernate/validator/HibernateValidatorFunctionalityTest.java:77]: Let's continue in #11506.

Comment (mkouba) [reply integration-tests/hibernate-validator/src/test/java/io/quarkus/it/hibernate/validator/HibernateValidatorFunctionalityTest.java:77]: So in theory, you should be able to do `TransformationContext#get(io.quarkus.arc.processor.BuildExtension.Key.INDEX)` inside the `AnnotationsTransformer.transform()` method... or even `TransformationContext#get(io.quarkus.arc.processor.BuildExtension.Key.ANNOTATION_STORE)` but this could be tricky (I can smell stack overflow ;-).
