### PR TITLE
Ensure the narayana-jta extension fully shuts down the recovery manager

### LINKED ISSUE #34576: Live reload stopped working on 3.2 when using XA transactions
### Describe the bug

When upgrading from 3.1 to 3.2, using quarkus:dev mode, the application will no longer reload on code changes, but fail with an exception, if an XA transaction manager is used (`quarkus.datasource.jdbc.transactions=xa`). 

### Expected behavior

Application reloads as before

### Actual behavior

```
023-07-06 14:42:10,384 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile [dev]) [Error Occurred After Shutdown]: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:104)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.IllegalStateException: ARJUNA012400: Cannot terminate the recovery manager as the implementation is not known. Could be the recovery manager was not started yet?
	at com.arjuna.ats.arjuna.recovery.RecoveryManager.checkState(RecoveryManager.java:489)
	at com.arjuna.ats.arjuna.recovery.RecoveryManager.getModules(RecoveryManager.java:355)
	at com.arjuna.ats.jbossatx.jta.RecoveryManagerService.addXAResourceRecovery(RecoveryManagerService.java:97)
	at io.quarkus.narayana.jta.runtime.QuarkusRecoveryService.addXAResourceRecovery(QuarkusRecoveryService.java:30)
	at io.agroal.narayana.NarayanaTransactionIntegration.addResourceRecoveryFactory(NarayanaTransactionIntegration.java:132)
	at io.agroal.pool.ConnectionPool.init(ConnectionPool.java:133)
	at io.agroal.pool.DataSource.<init>(DataSource.java:42)
	at io.quarkus.agroal.runtime.DataSources.doCreateDataSource(DataSources.java:246)
	at io.quarkus.agroal.runtime.DataSources$1.apply(DataSources.java:129)
	at io.quarkus.agroal.runtime.DataSources$1.apply(DataSources.java:126)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at io.quarkus.agroal.runtime.DataSources.getDataSource(DataSources.java:126)
	at io.quarkus.agroal.runtime.DataSources.fromName(DataSources.java:122)
	at io.quarkus.agroal.runtime.AgroalRecorder.agroalDataSourceSupplier(AgroalRecorder.java:23)
	at io.quarkus.deployment.steps.AgroalProcessor$generateDataSourceBeans109901991.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.AgroalProcessor$generateDataSourceBeans109901991.deploy(Unknown Source)
	... 11 more
```

### How to Reproduce?

```
modules: agroal, narayana-jta, postgres jdbc driver

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/postgres
quarkus.datasource.jdbc.transactions=xa
quarkus.transaction-manager.enable-recovery=true

    @Inject
    DataSource ds;

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() throws Exception{
        QuarkusTransaction.requiringNew()
                .run(()->{
                    try(var c = ds.getConnection()) {

                    } catch (Exception e) {
                        throw new RuntimeException(e);
                    }
                });
        return "blah"; // <-- change output to test live reload
    }
```

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

20

### GraalVM version (if different from Java)

20

### Quarkus version or git rev

3.2.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mmusgrov**
Fixes #34576

### CODE REVIEW

File: extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/NarayanaJtaRecorder.java [hunk 1]
```diff
@@ -158,7 +157,12 @@ public void startRecoveryService(final TransactionManagerConfiguration transacti
     public void handleShutdown(ShutdownContext context, TransactionManagerConfiguration transactions) {
         context.addLastShutdownTask(() -> {
             if (transactions.enableRecovery) {
-                RecoveryManager.manager().terminate(true);
+                try {
+                    QuarkusRecoveryService.getInstance().stop();
+                } catch (Exception e) {
+                    throw new RuntimeException(e);
+                }
+                QuarkusRecoveryService.getInstance().destroy();
```
Comment (gsmet) [inline extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/NarayanaJtaRecorder.java:165]: Shouldn't this be part of a finally clause?

I'm a bit worried of the state we will end up in if something wrong happens when we stop the service.

File: extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/QuarkusRecoveryService.java [hunk 2]
```diff
@@ -51,4 +51,11 @@ public void create() {
         }
         xaResources.clear();
     }
+
+    @Override
+    public void destroy() {
+        super.destroy();
+        isCreated = false;
+        recoveryManagerService = null;
```
Comment (Sanne) [inline extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/QuarkusRecoveryService.java:59]: this looks good for the purposes of this specific issue, but shouldn't this `QuarkusRecoveryService` be mindful about concurrency?
I see neither the initialization/destruction being safeguarded against racy invocations, nor the overriden instance methods - are these methods protected externally?

File: extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/NarayanaJtaRecorder.java (hunk 1 above)
Comment (mmusgrov) [reply extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/NarayanaJtaRecorder.java]: Good call on both counts.

The Narayana RecoveryManager#terminate call [1] checks the state [2] and throws IllegalStateException if it has previously been shutdown so it's really a sanity check telling the caller not to call it twice.

[1] https://github.com/jbosstm/narayana/blob/6.0.1.Final/ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/recovery/RecoveryManager.java#L206
[2] https://github.com/jbosstm/narayana/blob/6.0.1.Final/ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/recovery/RecoveryManager.java#L489

File: extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/QuarkusRecoveryService.java (hunk 2 above)
Comment (mmusgrov) [reply extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/QuarkusRecoveryService.java:59]: @zhfeng will you respond to Sanne's point about lack of protection against concurrent access, thanks.

Comment (zhfeng) [reply extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/QuarkusRecoveryService.java:59]: Well, I think the real working codes are in [RecoveryManager.java](https://github.com/jbosstm/narayana/blob/main/ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/recovery/RecoveryManager.java#L173-L207). Both of initialize/terminate methods are protected by `synchronized`. So it should be safe for concurrency access.

**Review by zhfeng — APPROVED** [review]
Thanks @mmusgrov - LGTM!

File: extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/QuarkusRecoveryService.java [hunk 3]
```diff
@@ -51,4 +51,11 @@ public void create() {
...
+    }
```
Comment (yrodiere) [inline extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/QuarkusRecoveryService.java:60]: Could you please add a non-regression test for this?

You can find an example of a hot reload test in Hibernate ORM tests:

* Resource: https://github.com/quarkusio/quarkus/blob/ebee0a4b66d1b4dba9c51165e78d22fbf3b90d3e/extensions/hibernate-orm/deployment/src/test/java/io/quarkus/hibernate/orm/xml/orm/OrmXmlHotReloadTestResource.java#L13
* Test: https://github.com/quarkusio/quarkus/blob/01bee6969efe374d4489d35189c65f34106cea87/extensions/hibernate-orm/deployment/src/test/java/io/quarkus/hibernate/orm/xml/orm/OrmXmlHotReloadExplicitFileTestCase.java#L13

In your case you'd probably just have a resource that runs an transaction and check that the resource still works after changing it (and automatically triggering a hot reload)

File: extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/QuarkusRecoveryService.java (hunk 2 above)
Comment (yrodiere) [reply extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/QuarkusRecoveryService.java:59]: As far as I can tell, `RecoveryManagerService` calls `RecoveryManager`. So it's possible in theory to have `destroy` being executed concurrently to e.g. `create`, which could result in the recovery manager being in a "stopped" status while the service is in a "running" status (`isCreated == true`). Adding `synchronized` to lifecycle methods would prevent that.

That being said, the superclass `RecoveryManagerService` seems to have the same problem, so I suppose if nobody ever reported a problem in other projects... it may be safe in practice.

File: extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/NarayanaJtaRecorder.java [hunk 4]
```diff
@@ -158,7 +157,14 @@ public void startRecoveryService(final TransactionManagerConfiguration transacti
     public void handleShutdown(ShutdownContext context, TransactionManagerConfiguration transactions) {
         context.addLastShutdownTask(() -> {
             if (transactions.enableRecovery) {
-                RecoveryManager.manager().terminate(true);
+                try {
+                    QuarkusRecoveryService.getInstance().stop();
+                } catch (Exception e) {
+                    // the recovery manager throws IllegalStateException if it has already been shutdown
+                    log.warn("The recovery manager has already been shutdown", e);
```
[the remark this answers is not in the document]
Comment (mmusgrov) [reply extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/NarayanaJtaRecorder.java:164]: @yrodiere The signature of the method that throws the IllegalStateException is `public void stop() throws Exception` [1] so that's what I need to catch .

Note that `QuarkusRecoveryService extends RecoveryManagerService` and RecoveryManagerService is a narayana integration class. In my response to Guillaume I was just pointing out what the actual exception thrown is, I gave links to the code in my response to him.

[1] https://github.com/jbosstm/narayana/blob/6.0.1.Final/ArjunaJTS/integration/src/main/java/com/arjuna/ats/jbossatx/jta/RecoveryManagerService.java#L69

File: extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/QuarkusRecoveryService.java (hunk 3 above)
Comment (mmusgrov) [reply extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/QuarkusRecoveryService.java:60]: I doubt that I will have time today, but do note that the clock is ticking on this fix. But we can merge it now and I can come back to it later though.

File: extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/NarayanaJtaRecorder.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (yrodiere) [reply extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/NarayanaJtaRecorder.java:164]: I think I get what you mean.

But you only know that `IllegalStateException` is about the recovery manager already being shut down.

Any other exception would be unexpected, so even if you have to catch them, you probably shouldn't log a warning saying the recovery manager has already been shut down... ?

File: extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/QuarkusRecoveryService.java (hunk 3 above)
Comment (yrodiere) [reply extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/QuarkusRecoveryService.java:60]: I agree that the comment about concurrency in particular is not urgent at all.

As to whether we should add non-regression tests when fixing bugs, well, I'll let whoever wants the fix urgently decide.

Comment (mmusgrov) [reply extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/QuarkusRecoveryService.java:60]: Actually on second thoughts, regression tests ought to be non-negotiable so I will prioritise that ahead of other stuff today, thanks.

Comment (mmusgrov) [reply extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/QuarkusRecoveryService.java:60]: In the example you gave. what is it that triggers the hot reload?

Comment (yrodiere) [reply extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/QuarkusRecoveryService.java:60]: That would be this:

https://github.com/quarkusio/quarkus/blob/01bee6969efe374d4489d35189c65f34106cea87/extensions/hibernate-orm/deployment/src/test/java/io/quarkus/hibernate/orm/xml/orm/OrmXmlHotReloadExplicitFileTestCase.java#L31-L32

Comment (yrodiere) [reply extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/QuarkusRecoveryService.java:60]: In your case you'll probably want to modify some java file instead, maybe the endpoint, to have it return a different value, so that your assertion can check it's been updated?

**Review by marcosgopen — APPROVED** [review]

File: extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/QuarkusRecoveryService.java (hunk 3 above)
Comment (mmusgrov) [reply extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/QuarkusRecoveryService.java:60]: @yrodiere If I added a dummy `application.properties` file in the test/resources directory and changed it via the regression test, would that trigger a reload?

Comment (yrodiere) [reply extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/QuarkusRecoveryService.java:60]: You'd need to include it in the resources of your test, like here https://github.com/quarkusio/quarkus/blob/01bee6969efe374d4489d35189c65f34106cea87/extensions/hibernate-orm/deployment/src/test/java/io/quarkus/hibernate/orm/xml/orm/OrmXmlHotReloadExplicitFileTestCase.java#L21.

But yes.

I'd be careful that changing the properties changes the behavior of your endpoint though, so that your second assertion checks both that 1. a hot-reload actually occurred and 2. that narayana still works.

Comment (mmusgrov) [reply extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/QuarkusRecoveryService.java:60]: And do I need to set `quarkus.devservices.enabled` to true in the application.properties that I use with the test?

Comment (yrodiere) [reply extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/QuarkusRecoveryService.java:60]: Probably not, since you don't want to test devservices here.

You'll probably want to set the JDBC URL though. But it looks like you use a test profile for that in other tests, not `application.properties`... for some reason (I don't know why): 

https://github.com/quarkusio/quarkus/blob/fd02a43d4b80fe60a3ad5bdaf1e54652c4796bdd/integration-tests/narayana-jta/src/test/java/io/quarkus/narayana/jta/JdbcObjectStoreTestProfile.java 

https://github.com/quarkusio/quarkus/blob/6fc835025144f8d235fb98a94b2e7070bdeba101/integration-tests/narayana-jta/src/test/java/io/quarkus/narayana/jta/TransactionJdbcObjectStoreTest.java#L11

Comment (mmusgrov) [reply extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/QuarkusRecoveryService.java:60]: I think I've figured it out, I'll let you know if I hit any issues with it ...

Comment (yrodiere) [reply extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/QuarkusRecoveryService.java:60]: @mmusgrov The PR build is failing, so I think we'll need to fix that before we merge, at least.
The failure seems unrelated though. I'll try to rebase the PR...

@gsmet I'll let you approve the PR if you're fine with @mmusgrov 's proposal.

**Comment by gsmet** [comment]
The CI failure is not related, I'll restart CI once the issue is fixed in main.

**Comment by gsmet** [comment]
Rebased to get a CI fix.

**Comment by mmusgrov** [comment]
@yrodiere I tried unsuccessfully most of yesterday to create a hot reload test. I've started [a zulipt topic](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Hot.20reload.20.2B.20transactions) to get some more eyes on my problem.

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
I merged it. Please continue the work on the test in a separate PR.

**Comment by zhfeng** [comment]
@gsmet I think it needs to backport to `3.2`, is it right?

**Comment by yrodiere** [comment]
@zhfeng yes, that's what the `triage/backport?` label on this PR means.

**Comment by zanella** [comment]
👋 I had to dig to find this issue, Quartz was failing after a live reload, might be a good idea to refer to this error on the 3.2 migration guide (I was on 3.2**.2**, which was the latest when I started the migration process)
