### PR TITLE
Use final SecurityIdentity augmented with all the augmentors in @PermissionChecker methods

### LINKED ISSUE #44990: PermissionChecker method sometimes receives unaugmented SecurityIdentity even though augmentor did run successfully
### Describe the bug

I'm trying out the new `@PermissionChecker` mechanism on a method. Every once in a while something happens and the annotated method starts receiving an unaugmented `SecurityIdentity` argument from Quarkus for all future invocations of that method, even though previously (some minutes ago) it did receive the augmented identity.

After the breakage, the `SecurityIdentity` received by the PermissionChecker contains the following attributes (as seen by `identity.attributes.forEach(::println)`:
```
configuration-metadata: io.quarkus.oidc.OidcConfigurationMetadata@1db376bd
io.quarkus.security.identity.AuthenticationRequestContext: io.quarkus.security.runtime.QuarkusIdentityProviderManagerImpl$1@1fd28ed3
io.vertx.ext.web.RoutingContext: io.vertx.ext.web.impl.RoutingContextImpl@5c29dcc
userinfo: io.quarkus.oidc.UserInfo@51da717f
tenant-id: Default
```
It's authenticated and contains OIDC `UserInfo`, but my custom attributes are missing.

The behavior happens consistently, but I have not yet been able to find reproduction conditions. For some time after server starts, the secured method receives the correct, augmented identity. I have been able to observe the behavior when I come back to the server after yet-unknown amount of time passes.

In the same controller as this `@PermissionsAllowed`-annotated method, there are sibling request handlers which perform their own permission checks manually. For these checks they use `SecurityIdentity` which is constructor-injected into the controller. This injected identity is always correctly augmented.

So far logging shows that the augmentor _does run_ for the affected requests and completes successfully, along with the entire authentication chain.

My current line of inquiry is OIDC userinfo cache expiration or something similar, related to OIDC. The one shared observation so far is that it happens after "some time" passes between consecutive requests made by an authenticated user using a still-valid Bearer token.

I'll keep investigating and will try to find a minimal shareable reproducer project, but I'm currently extremely busy.

Here's my general setup, maybe something can be gleaned from it:

Quarkus: `3.17.2`
installed extensions:
```kotlin
implementation(libs.quarkus.arc)
implementation(libs.quarkus.flyway)
implementation(libs.quarkus.hibernate.orm)
implementation(libs.quarkus.hibernate.orm.panache.kotlin)
implementation(libs.quarkus.hibernate.validator)
implementation(libs.quarkus.jdbc.postgresql)
implementation(libs.quarkus.kotlin)
implementation(libs.quarkus.logging.json)
implementation(libs.quarkus.micrometer.registry.prometheus)
implementation(libs.quarkus.oidc)
implementation(libs.quarkus.rest)
implementation(libs.quarkus.rest.kotlinserialization)
implementation(libs.quarkus.rest.qute)
implementation(libs.quarkus.smallrye.health)
```

OIDC config from `application.properties`:
```
quarkus.oidc.auth-server-url=${AUTH0_SERVER_URL}
quarkus.oidc.application-type=service
quarkus.oidc.client-id=${AUTH0_CLIENT_ID}
quarkus.oidc.credentials.secret=${AUTH0_CLIENT_SECRET}
quarkus.oidc.token.verify-access-token-with-user-info=true
quarkus.oidc.authentication.force-redirect-https-scheme=true
# Must enable token cache to not exhaust the Auth0 rate limits!
# If not set, Quarkus would perform UserInfo request on each access,
# leading to immediate UserInfo limit exhaustion
# https://auth0.com/docs/troubleshoot/customer-support/operational-policies/rate-limit-policy/rate-limit-configurations
quarkus.oidc.token-cache.max-size=1000
quarkus.oidc.token-cache.time-to-live=5M
```

```kotlin
@ApplicationScoped
class PermissionChecker(private val repository: MyRepository) {
    private fun performCheck(identity: SecurityIdentity, arg1: String): Boolean {
        // FAIL: cannot extract expected attribute from the identity!   <================
        val user = identity.extractUser() ?: throw UnauthorizedException()
    }

    @PermissionChecker("permission-check-read")
    @Blocking
    fun decadeRead(identity: SecurityIdentity, arg1: String): Boolean =
        performCheck(identity, arg1)
}

@Path("/api/stuff")
@RolesAllowed("\${myroles.floor-manager-and-above}")
@Blocking
class ApiController(
    private val repo: Repository1,
    private val securityIdentity: SecurityIdentity, // <=== This SecurityIdentity is ALWAYS correct
) {

    @Path("/endpoint")
    @GET
    fun getData(@RestQuery arg1: String, ): ApiDto {
        return constructResponse(arg1)
    }

    @PermissionsAllowed("permission-check-read")
    protected fun constructResponse(arg1: String): ApiDto {
        // ...
    }
    
}

=================================================================================

@ApplicationScoped
class IdentityAugmentor : SecurityIdentityAugmentor {

    @Inject
    internal lateinit var identitySupplierInstance: Instance<IdentitySupplier>

    override fun augment(
        identity: SecurityIdentity,
        context: AuthenticationRequestContext,
        attributes: Map<String, Any>
    ): Uni<SecurityIdentity> = doAugment(identity, context, HttpSecurityUtils.getRoutingContextAttribute(attributes))

    override fun augment(identity: SecurityIdentity, context: AuthenticationRequestContext): Uni<SecurityIdentity> =
        doAugment(identity, context, null)

    private fun doAugment(identity: SecurityIdentity, context: AuthenticationRequestContext, routingContext: RoutingContext?): Uni<SecurityIdentity> {
        val identitySupplier: IdentitySupplier = identitySupplierInstance.get()
        identitySupplier.originalIdentity = identity
        return context.runBlocking(identitySupplier)
    }
}

@Dependent
internal class IdentitySupplier(private val userRepository: UserRepository) : Supplier<SecurityIdentity> {
    lateinit var originalIdentity: SecurityIdentity

    @ActivateRequestContext
    override fun get(): SecurityIdentity = topLevelAugmentIdentity(originalIdentity, userRepository)
}

internal fun topLevelAugmentIdentity(
    originalIdentity: SecurityIdentity,
    userRepository: UserRepository
): SecurityIdentity {
    // Augmentation runs without issues
}
```

-------------------------------------------

I will keep tinkering and looking for reproduction steps

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

Unfortunately I have not found reproduction steps as this doesn't happen immediately and involves real world 3rd party authentication. I'll post steps if and when I do.

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

3.17.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

```
------------------------------------------------------------
Gradle 8.11.1
------------------------------------------------------------

Build time:    2024-11-20 16:56:46 UTC
Revision:      481cb05a490e0ef9f8620f7873b83bd8a72e7c39

Kotlin:        2.0.20
Groovy:        3.0.22
Ant:           Apache Ant(TM) version 1.10.14 compiled on August 16 2023
Launcher JVM:  19.0.2 (Oracle Corporation 19.0.2+7-44)
Daemon JVM:    /Users/ondra/Library/Java/JavaVirtualMachines/openjdk-19.0.2/Contents/Home (no JDK specified, using current Java home)
OS:            Mac OS X 15.1.1 aarch64
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by michalvavrik**
- closes: https://github.com/quarkusio/quarkus/issues/44990
- changes in the IdentityMock class ensure that added tests actualy verify the issue
- fixes the issue when augmentors order were not deterministic (when users use default augmentor priority), which resulted in a fact that `SecurityIdentity` passed as a method argument of a `@PermissionChecker` wasn't always augmented with all the augmentors

### CODE REVIEW

**Comment by sberyozkin** [comment]
Thanks @michalvavrik , will have a look tomorrow,  finding it difficult to review on the phone

**Comment by michalvavrik** [comment]
> Thanks @michalvavrik , will have a look tomorrow, finding it difficult to review on the phone

I can only imagine :-D We are in no hurry.

File: extensions/security/runtime/src/main/java/io/quarkus/security/runtime/QuarkusIdentityProviderManagerImpl.java [hunk 1]
```diff
@@ -206,7 +207,11 @@ public Builder addProvider(IdentityProvider<? extends AuthenticationRequest> pro
          * @return this builder
          */
         public Builder addSecurityIdentityAugmentor(SecurityIdentityAugmentor augmentor) {
-            augmentors.add(augmentor);
+            if (augmentor instanceof QuarkusPermissionSecurityIdentityAugmentor quarkusPermissionAugmentor) {
```
Comment (sberyozkin) [inline extensions/security/runtime/src/main/java/io/quarkus/security/runtime/QuarkusIdentityProviderManagerImpl.java:210]: Hi @michalvavrik The fact that we have to modify this class in a couple of places to do some special processing around the internal security augmentor implies, IMHO, that may be that original solution has to be revisited. Recall we discussed it.

Would it simplify things, if, instead of having the special internal `QuarkusPermission` and the special augmentor, we'd make this `QuarkusPermission` be an actual custom permission that will be passed to possessed permissions ? I believe the reason we have the current solution is that it was meant to make it easier for users to correctly write custom permission checkers, but we now have `addPermission(...)`  identity builder methods...

We don't have to do it now as the bug has to be fixed, and it may require more discussion, but at least I'd ask for `//Revisit` comments

Comment (sberyozkin) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/QuarkusIdentityProviderManagerImpl.java:210]: @michalvavrik I can open an enhancement or housekeeping issue for us to discuss. `QuarkusPermissionSecurityIdentityAugmentor` plus current `QuarkusPermission` combination is sound, but I hope we can avoid doing `QuarkusPermissionSecurityIdentityAugmentor` specific processing...
Thanks

**Review by sberyozkin — APPROVED** [review]

File: extensions/security/runtime/src/main/java/io/quarkus/security/runtime/QuarkusIdentityProviderManagerImpl.java (hunk 1 above)
Comment (michalvavrik) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/QuarkusIdentityProviderManagerImpl.java:210]: I don't mind rewriting this at all, I'll do it if you insist. IMO will not gain anything. What you see is in this PR is internal Quarkus Security code and following operations needs to be done in one way or another:

- we need to augment security identity (hence the augmentor)
- we need add permission checker in that augmentor

We can drop `QuarkusPermissionSecurityIdentityAugmentor` and `QuarkusPermission` and call it differently, but nothing will change from the perspective of what the code does. This PR could had been avoided 100 % if the `SecurityIdentity` is taken from `Arc`, but that has following downsides:

- it requires more operations (call Arc, whatver it does inside)
- I think it could be a blocking operation at some scenarios, we can improve that to avoid it (because obviously we will have the identity for authorization, but ATM that can be a case)

> QuarkusPermission be an actual custom permission that will be passed to possessed permissions ? 

I think QuarkusPermission is actual required permission and if it is passed to a possessed permission, you need:

- add new possessed permission in augmentor (that we already do)
- get the identity from somewhere (probably arc, see above my comments)

So I respect that changes in this PR can look bad, we can avoid such exceptions if it needs to be done.
