### PR TITLE
Option to try all OIDC JWK keys as fallback

### LINKED ISSUE #41931: OIDC: List of JWKS is not checked without specified kid
### Describe the bug

I want to protect my resource with the `@Authenticated` annotation and have an oidc `quarkus.oidc.auth-server-url` defined.
From the `jwks_uri` endpoint I have these keys:

``` JSON
{
    "keys": [
        {
            "n": "value for n",
            "e": "AQAB",
            "kty": "RSA",
            "kid": "fQ-Uyjg7QvTpf_mn9yKXmeYPsPE",
            "x5t": "fQ-Uyjg7QvTpf_mn9yKXmeYPsPE",
            "use": "sig"
        },
        {
            "n": "value for n",
            "e": "AQAB",
            "kty": "RSA",
            "kid": "sgw",
            "x5t": "sgw",
            "use": "sig"
        },
        {
            "n": "value for n",
            "e": "AQAB",
            "kty": "RSA",
            "kid": "msgw",
            "x5t": "msgw",
            "use": "sig"
        }
    ]
}
```

My JWS looks like this:

``` JSON
{
    "alg": "RS256"
}
{
    "iss": "https://example.domain.com/openid",
    "sub": "",
    "exp": 1721139705,
    "nbf": 1721138805,
    "iat": 1721138805,
    "jti": "d9e88d72-78fe-430f-8ff3-391161622986",
    "aud": "1234423458943498493883498432348293"
}
<signature>
```

Not completely sure, whether this is a but or intended behaviour, but regarding the [JWS documentation](https://datatracker.ietf.org/doc/html/rfc7515#appendix-D) multiple keys could be used to verify the signature.

The "issue" seems to be, that the keys are not checked for best effort, but Quarkus is rather looking for a matching kid or falls back to `keyWithoutKeyIdAndThumbprint` (OidcProvider.java:480), which is empty, because all keys have an id set.

Would it make sense, to take all available keys into account before OidcProvider.java:492 to have another fallback for verifying the signature?

### Expected behavior

The JWS is correctly verified with one of the provided keys.

### Actual behavior

No key is selected for verification, therefore failing with this message (decoded token content can be seen above):

```
Unable to process JOSE object (cause: org.jose4j.lang.UnresolvableKeyException: JWK is not available, neither 'kid' nor 'x5t#S256' nor 'x5t' token headers are set): JsonWebSignature{"alg":"RS256"}->{token content}
```

### How to Reproduce?

1. Have multiple JWKS keys all with a `kid`
2. Don't specify `kid` in the JWS
3. JWS verification will fail, because no key will be selected for verification

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.22631.3880]

### Output of `java -version`

openjdk version "21.0.3" 2024-04-16 LTS OpenJDK Runtime Environment Corretto-21.0.3.9.1 (build 21.0.3+9-LTS) OpenJDK 64-Bit Server VM Corretto-21.0.3.9.1 (build 21.0.3+9-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.12.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

------------------------------------------------------------ Gradle 8.8 ------------------------------------------------------------   Build time:   2024-05-31 21:46:56 UTC Revision:     4bd1b3d3fc3f31db5a26eecb416a165b8cc36082   Kotlin:       1.9.22 Groovy:       3.0.21 Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023 JVM:          21.0.3 (Amazon.com Inc. 21.0.3+9-LTS) OS:           Windows 11 10.0 amd64

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by c15yi**
Instead of changing more logic to check multiple keys as fallback, which would mean bigger changes and also negatively impact performance, I added the option to specify a specific key as a fallback key in case no key could be determined.

- Fixes: #41931

### CODE REVIEW

**Comment by sberyozkin** [comment]
Thanks for the effort, @c15yi, PR looks neat. 
But does it really work beyond the moment OIDC server recycles JWKs keys ? 
I feel we have to give it a bit more thinking. If we have 2/3 keys only, the performance impact may or may not be noticeable, you may as well get the first key matching the signing key... In fact I think I recall now that this situation is optionally tested during the OIDC RP conformance testing, it is OK not to support it but they do offer it as an optional test...

**Comment by c15yi** [comment]
In my case, the `kid` would stay the same after recycling the keys, but you are correct, that might not always be the case. 

Do I understand your suggestion correctly, to try out the keys with `JsonWebSignature:verifySignature` until a matching one was found in `OidcProvider.JsonWebKeyResolver:resolveKey` and then return that key, if one could be found?

I would create an option to check all keys, but only if there is no `kid` or `x5t` set in the JOSE header. If a key is specified in the JOSE header, then it doesn't make sense to check all keys, if that key isn't present in the `jwks`, does it?

**Comment by c15yi** [comment]
@sberyozkin updated the PR 🙂

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/JsonWebKeySet.java [hunk 1]
```diff
@@ -27,6 +27,7 @@ public class JsonWebKeySet {
     private Map<String, Key> keysWithThumbprints = new HashMap<>();
     private Map<String, Key> keysWithS256Thumbprints = new HashMap<>();
     private Map<String, List<Key>> keysWithoutKeyIdAndThumbprint = new HashMap<>();
+    private List<Key> keys = new ArrayList<>();
```
Comment (sberyozkin) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/JsonWebKeySet.java:30]: It should be a map IMHO, key is the algorithm, if JWK does not even have an algorithm property then we just ignore such keys for the purpose of the try-all fallback. Otherwise we may end up running EC keys against RSA signatures etc etc which will have time and possibly security  consequences

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcProvider.java [hunk 2]
```diff
@@ -503,6 +510,25 @@ public Key resolveKey(JsonWebSignature jws, List<JsonWebStructure> nestingContex
             }
         }
 
+        private Key findKeyByBruteForce(JsonWebSignature jws) {
```
Comment (sberyozkin) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcProvider.java:513]: Not a bad idea but then even in the best case scenario, we'll run the signature verification twice.

I think we'll need to a higher level retry after a signature exception is thrown, inside verifyTokenInternal function. It can become a bit messy. I guess, if it is a `try-all` then a new instance of key resolver which remembers the already tried keys (or even the last index in the values collection) should be used.

**Comment by sberyozkin** [comment]
@c15yi, I guess something like this:
```
public OidcProvider(OidcProviderClient client, OidcTenantConfig oidcConfig, JsonWebKeySet jwks,
            TokenCustomizer tokenCustomizer, Key tokenDecryptionKey, List<Validator> customValidators) {
        if (jwks != null) {
            VerificationKeyResolver resolver = new JsonWebKeyResolver(jwks, oidcConfig.token.forcedJwkRefreshInterval);
            this.asymmetricKeyResolver = oidcConfig.jwks.tryAll ? : new TryAllJsonWebKeyResolver(jwks.getAllKeys(), resolver) : resolver;
        }
  ...
}
``` 

and then, 

```
public TokenVerificationResult verifyJwtToken(String token, boolean enforceAudienceVerification, boolean subjectRequired,  String nonce)  throws InvalidJwtException {
        if (asymmetricKeyResolver instanceof TryAllJsonWebKeyResolver) {
               TryAllJsonWebKeyResolver resolver = (TryAllJsonWebKeyResolver)asymmetricKeyResolver;
               for (int i = 0; i < resolver.allKeysSize(); i++) {
                   try {
                      return verifyJwtTokenInternal(customizeJwtToken(token), enforceAudienceVerification, subjectRequired, nonce,  (requiredAlgorithmConstraints != null ? requiredAlgorithmConstraints : ASYMMETRIC_ALGORITHM_CONSTRAINTS), asymmetricKeyResolver, true, oidcConfig.token.isIssuedAtRequired());
                   } catch (InvalidJsonJsonWebKeyException ex) {
                        if (signatureFailure(ex) && resolver.keyIndex() != -1) {
                             continue;
                        }
                        throw ex;
                   }
              }
       } else {
            return verifyJwtTokenInternal(customizeJwtToken(token), enforceAudienceVerification, subjectRequired, nonce,
                    (requiredAlgorithmConstraints != null ? requiredAlgorithmConstraints : ASYMMETRIC_ALGORITHM_CONSTRAINTS), asymmetricKeyResolver, true, oidcConfig.token.isIssuedAtRequired());
       }
    }
```

where `TryAllJsonWebKeyResolver` provides an index based access to the algorithm specific list of keys but only if the `JsonWebKeyResolver` which it delegates to produced `null` key...

Please think about it

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/JsonWebKeySet.java (hunk 1 above)
Comment (c15yi) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/JsonWebKeySet.java:30]: In the implementation of the PR only keys which have a supported type will be stored.

Using a map with the algorithm as the key wouldn't be practical, as we need the list of keys while we only have a string representation of the jwt, so we cannot easily determine the algorithm and therefore the list of keys to use.

**Comment by sberyozkin** [comment]
@c15yi This is only a very rough prototype

>Is it worth (in terms of runtime) to cycle through verifyJwtTokenInternal multiple times until a valid key was found?

As far as I understand, it could be the most effective, albeit the messy one. In this case, given 3 keys, you'll get at most 3 verifications in the worst case but only 1 in the best case. While with your last update, with 3 keys, in the worst case, you'll get 4 and in the best case 2 verifications. I've typed it and I think it is indeed not a big deal, so let's scrap my proposal, thanks for raising concerns about it.

But it really should a Map of algorithm to the list of keys. You can get an algorithm from a token header to acquire a matching List of keys to check with the brute force try...

Thanks

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcProvider.java (hunk 2 above)
Comment (c15yi) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcProvider.java:513]: Adapted it, to check only the keys matching the key type.

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcTenantConfig.java [hunk 3]
```diff
@@ -539,6 +538,13 @@ public static class Jwks {
         @ConfigItem
         public Optional<Duration> cleanUpTimerInterval = Optional.empty();
 
+        /**
+         * In case there is no kid or x5t specified in the JOSE header and no key could be determined, check all available keys. Defaults to: false.
```
Comment (sberyozkin) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcTenantConfig.java:542]:
```suggestion
         * In case there is no 'kid' or 'x5t' specified in the JOSE header and no key could be determined, check all available keys matching a token algorithm ('alg') header value.```

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/JsonWebKeySet.java [hunk 4]
```diff
@@ -27,6 +27,7 @@ public class JsonWebKeySet {
     private Map<String, Key> keysWithThumbprints = new HashMap<>();
     private Map<String, Key> keysWithS256Thumbprints = new HashMap<>();
     private Map<String, List<Key>> keysWithoutKeyIdAndThumbprint = new HashMap<>();
+    private Map<String, List<Key>> keys = new HashMap<>();
```
Comment (sberyozkin) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/JsonWebKeySet.java:30]:
```suggestion
    private Map<String, List<Key>> allKeys = new HashMap<>();
```

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/JsonWebKeySet.java [hunk 5]
```diff
@@ -37,6 +38,9 @@ private void initKeys(String json) {
             org.jose4j.jwk.JsonWebKeySet jwkSet = new org.jose4j.jwk.JsonWebKeySet(json);
             for (JsonWebKey jwkKey : jwkSet.getJsonWebKeys()) {
                 if (isSupportedJwkKey(jwkKey)) {
+                    List<Key> keysForAlgorithm = keys.computeIfAbsent(jwkKey.getKeyType(), k -> new ArrayList<>());
```
Comment (sberyozkin) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/JsonWebKeySet.java:41]: This is fine but there is a general preference to avoid lambda expressions of all kind. Can you please consider pushing the code used to handle such a Map just below into a private function that can be reused for collecting all keys as well ?

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/JsonWebKeySet.java [hunk 6]
```diff
@@ -71,6 +75,10 @@ private static boolean isSupportedJwkKey(JsonWebKey jwkKey) {
                 && (SIGNATURE_USE.equals(jwkKey.getUse()) || jwkKey.getUse() == null);
     }
 
+    public List<Key> getKeysForKeyType(String keyType) {
+        return keys.getOrDefault(keyType, new ArrayList<>());
```
Comment (sberyozkin) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/JsonWebKeySet.java:79]:
```suggestion
        return keys.getOrDefault(keyType, List.of());
```

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcProvider.java [hunk 7]
```diff
@@ -495,6 +496,12 @@ public Key resolveKey(JsonWebSignature jws, List<JsonWebStructure> nestingContex
                 key = chainResolverFallback.resolveKey(jws, nestingContext);
             }
 
+            if (key == null && oidcConfig.jwks.tryAll && kid == null && thumbprint == null) {
```
Comment (sberyozkin) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcProvider.java:499]: Can you please move it just above the chainResolverFallback block above ?

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcProvider.java [hunk 8]
```diff
@@ -503,6 +510,33 @@ public Key resolveKey(JsonWebSignature jws, List<JsonWebStructure> nestingContex
...
+            for (Key key : jwks.getKeysForKeyType(keyType)) {
+                jws.setKey(key);
+
+                try {
+                    if (jws.verifySignature()) {
+                        jws.setKey(initialKey);
+                        return key;
+                    }
+                } catch (JoseException e) {
+                    LOG.debug("Verifying signature with key " + key + " failed.", e);
```
Comment (sberyozkin) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcProvider.java:532]: Please use `debugf`. 
It would also likely make it easier to understand that these are insignificant failures if you add a log message above saying that a signature verification check is used to find a matching key and confirm the result (key found or not)

**Comment by sberyozkin** [comment]
Thanks for your work on this PR, @c15yi, it really looks good already, but I've asked for a few minor updates, thanks

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcTenantConfig.java (hunk 3 above)
Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcTenantConfig.java:542]: The generated doc will show what a default value is

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcProvider.java (hunk 7 above)
Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcProvider.java:499]: Also, can you give me a favor and add the same block [here](https://github.com/quarkusio/quarkus/blob/main/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/DynamicVerificationKeyResolver.java#L117). I'll look into getting rid of the duplication a bit later, it has been on my map.
I suppose you can make the brute force check a method  on JsonWebKeySet itself for now... thanks

**Comment by sberyozkin** [comment]
@c15yi FYI, I'll be going on PTO later today so we'll continue in mid of August, talk to you then

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcTenantConfig.java (hunk 3 above)
Comment (c15yi) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcTenantConfig.java:542]: Updated

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/JsonWebKeySet.java (hunk 4 above)
Comment (c15yi) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/JsonWebKeySet.java:30]: renamed

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/JsonWebKeySet.java (hunk 5 above)
Comment (c15yi) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/JsonWebKeySet.java:41]: removed lambda usage and added a reusable method for the "list in a map" case.

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/JsonWebKeySet.java (hunk 6 above)
Comment (c15yi) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/JsonWebKeySet.java:79]: changed

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcProvider.java (hunk 7 above)
Comment (c15yi) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcProvider.java:499]: I moved the brute force part into `JsonWebKeySet` and added the code as a comment into `Dynamic VerificationKeyResolver` as there is nothing to verify the signature for, so the method cannot be called there.

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcProvider.java (hunk 8 above)
Comment (c15yi) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcProvider.java:532]: Added more elaborate logging into the method.

**Comment by c15yi** [comment]
@sberyozkin, in case you are still available, I just implemented your suggestions.

Otherwise, have a great PTO, thanks for the reviews and talk to you then.

**Comment by c15yi** [comment]
Because our application is depending on this, would it be possible for someone else to take over the PR review, @sberyozkin? In the issue I created @pedroigor was mentioned for oidc, too. What do you think?

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/DynamicVerificationKeyResolver.java [hunk 9]
```diff
@@ -115,6 +117,12 @@ public Uni<? extends VerificationKeyResolver> apply(JsonWebKeySet jwks) {
                             newKey = jwks.getKeyWithoutKeyIdAndThumbprint("RSA");
                         }
 
+//                        if (newKey == null && tryAll && kid == null && thumbprint == null) {
```
Comment (sberyozkin) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/DynamicVerificationKeyResolver.java:120]: @c15yi Can you please uncomment this one ?

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/DynamicVerificationKeyResolver.java [hunk 10]
```diff
@@ -115,6 +117,12 @@ public Uni<? extends VerificationKeyResolver> apply(JsonWebKeySet jwks) {
...
+//                            LOG.debug("JWK is not available, neither 'kid' nor 'x5t#S256' nor 'x5t' token headers are set,"
+//                                    + " falling back to trying all available keys");
+//                            newKey = jwks.findKeyInAllKeys(jws); // there is nothing to check the signature for in this method
```
Comment (sberyozkin) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/DynamicVerificationKeyResolver.java:123]: Can you clarify this comment ?

**Review by sberyozkin — APPROVED** [review]
I believe it's ready to go, dynamic resolver update can wait, no need to rush

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/DynamicVerificationKeyResolver.java (hunk 10 above)
Comment (c15yi) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/DynamicVerificationKeyResolver.java:123]: In the code of the `DynamicVerificationKeyResolver` there is no `JsonWebSignature`, but it need such object to perform the brute force algorithm on it with the different keys.
Therefore, I commented out the code, because it's not functional and I didn't see an easy solution to getting this to work there.

**Comment by c15yi** [comment]
@sberyozkin squashed the commits and added an explanation to your question on the `DynamicVerificationKeyResolver`. :)

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/DynamicVerificationKeyResolver.java (hunk 10 above)
Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/DynamicVerificationKeyResolver.java]: @c15yi ok, a jose4j instance for verifying a signature can be built manually for this case with some custom basic resolver delegating to your new method,  but I can take care of it later

**Comment by geoand** [comment]
@sberyozkin should this be merged?

**Comment by c15yi** [comment]
@geoand, @sberyozkin is currently on vacation and will be back mid of August. He approved it, but the pipelines failed, because I missed an unused import. Now everything should be ready I guess.

**Comment by geoand** [comment]
Thanks. 

Let's wait for @sberyozkin to re-check

**Comment by sberyozkin** [comment]
Thanks @c15yi, @geoand, sorry but did not really have good options for merging it since heading to the airport on 27th July, but we still have a few days to have it merged and backported :-)
I'll keep the commented out code in place for now, it is on a non-critical path as far as this issue is concerned and I'll clean it up a bit later

**Comment by sberyozkin** [comment]
No need to backport, it is just in time for 3.14 CR1

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/DynamicVerificationKeyResolver.java [hunk 11]
```diff
@@ -32,10 +32,12 @@ public class DynamicVerificationKeyResolver {
 
     private final OidcProviderClient client;
     private final MemoryCache<Key> cache;
+    private final boolean tryAll;
     final CertChainPublicKeyResolver chainResolverFallback;
 
     public DynamicVerificationKeyResolver(OidcProviderClient client, OidcTenantConfig config) {
         this.client = client;
+        this.tryAll = config.jwks.tryAll;
```
Comment (michalvavrik) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/DynamicVerificationKeyResolver.java:40]: this variable is never used

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/DynamicVerificationKeyResolver.java [hunk 12]
```diff
@@ -115,6 +117,12 @@ public Uni<? extends VerificationKeyResolver> apply(JsonWebKeySet jwks) {
                             newKey = jwks.getKeyWithoutKeyIdAndThumbprint("RSA");
                         }
 
+                        //                        if (newKey == null && tryAll && kid == null && thumbprint == null) {
```
Comment (michalvavrik) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/DynamicVerificationKeyResolver.java:120]: I think this is not useful to have this commented out code.
