### PR TITLE
More Jakarta progress

### LINKED ISSUE #27570: Jakarta - EE 10 - Support JAX-RS 3.1.0 in RESTEasy Reactive
JAX-RS 3.1.0 introduces some new methods and classes and we will need to implement them in RESTEasy Reactive.

How to reproduce:
- get the `jakarta-rewrite` branch from the upstream repository (this branch is already transformed to Jakarta) - it is rewritten daily (but these parts are not moving parts so it shouldn't be a problem)
- `mvn -Dquickly`
- `cd independent-projects/resteasy-reactive`
- change `jakarta.ws.rs-api.version` to `3.1.0` in `pom.xml`
- `mvn clean install`

First failure will be:

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project resteasy-reactive-common: Compilation failure
> [ERROR] /data/home/gsmet/git/quarkus-jakarta/independent-projects/resteasy-reactive/common/runtime/src/main/java/org/jboss/resteasy/reactive/common/jaxrs/RuntimeDelegateImpl.java:[30,8] org.jboss.resteasy.reactive.common.jaxrs.RuntimeDelegateImpl is not abstract and does not override abstract method createEntityPartBuilder(java.lang.String) in jakarta.ws.rs.ext.RuntimeDelegate
[ERROR]

Once this is done, I know there is another one related to the bootstrap and I think that's pretty much it - but I wasn't able to experiment fully.

Note: the tree won't function fully if you fix that because RESTEasy Classic is pointing to the EE 9 version for now but the idea is to have a compilable RESTEasy Reactive in `independent-projects` so that I can upgrade RESTEasy Classic and JAX-RS in the main bom _(I will handle that part)_.

I think the easiest way to work on that would be to create a branch in one's fork and push a commit on top of the `jakarta-rewrite` branch. 

Then I would get it and apply it on top of the transformation each night. And we would have an error if the patch doesn't apply cleanly but I don't think these areas change a lot. _(I will handle that part)_

These methods/classes have already been implemented in RESTEasy Classic 6.1.0.Final so that could be a source of inspiration.

Ideally, the `jakarta.ws.rs-api.version` upgrade will be done in a separate first commit as I think I will rely on OpenRewrite to change the version so that everything is centralized.

/cc @geoand

### LINKED ISSUE #27642: Jakarta - EE 10 - Upgrade Quarkus HTTP to Servlet 6.0.0 and Websockets 2.1.0
I have no idea how much work it will be for now.

The rewrite code is here: https://github.com/quarkusio/quarkus-http/tree/main/jakarta .

But I suspect we will have to adjust some APIs...

### LINKED ISSUE #27643: Jakarta - EE 10 - Update Jakarta Authorization API to 2.1.0 and Authentication API to 3.0.0
I think it's Elytron Security which is supposed to implement these but I haven't found a version that actually targets EE 10.

I need to ping some WildFly people.

### PR DESCRIPTION
**Pull request by gsmet**
- JAX-RS 3.1
- Authorization 2.1 and Authentication 3.0
- Servlet 6.0 and Websocket 2.1

Fixes https://github.com/quarkusio/quarkus/issues/27570
Fixes https://github.com/quarkusio/quarkus/issues/27643
Fixes https://github.com/quarkusio/quarkus/issues/27642

### CODE REVIEW

File: extensions/websockets/client/runtime/src/main/java/io/quarkus/websockets/BearerTokenClientEndpointConfigurator.java [hunk 1]
```diff
@@ -53,4 +54,8 @@ public List<Class<? extends Decoder>> getDecoders() {
     public Map<String, Object> getUserProperties() {
         return Collections.emptyMap();
     }
+
+    public SSLContext getSSLContext() {
+        return null;
+    }
```
Comment (gsmet) [inline extensions/websockets/client/runtime/src/main/java/io/quarkus/websockets/BearerTokenClientEndpointConfigurator.java:60]: @sberyozkin this one is interesting. `ClientEndpointConfig` introduces a new `getSSLContext()` method that should return a non-null SSLContext if you want to usee wss.
That being said, I have no idea how you are supposed to use this one? Should people only use the configurator?

**Comment by gsmet** [comment]
@geoand FYI, the JAX-RS 3.1 upgrade is included in this PR.

**Comment by geoand** [comment]
Excellent 👌
