### PR TITLE
Fix @NoClassInterceptor and RestClient Reactive mocking

### LINKED ISSUE #26953: 2.10.3.Final -> ServiceConfigurationError: SmallRyeConfigFactory: QuarkusConfigFactory not a subtype
### Describe the bug

When moving from 2.10.2.Final to 2.10.3.Final, I see that some of our tests fails with this error, see test output below.

https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/2.2E10.2E3.2EFinal.20-.3E.20ServiceConfigurationError.3A.20SmallRyeConfigFac

### Expected behavior

The test should run ok as in previous version 2.10.2.Final 

### Actual behavior

The test fails:
[ERROR] app.ArkivControllerMockTest.tst  Time elapsed: 0.772 s  <<< ERROR!
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
Caused by: java.lang.reflect.InvocationTargetException
Caused by: java.util.ServiceConfigurationError: io.smallrye.config.SmallRyeConfigFactory: io.quarkus.runtime.configuration.QuarkusConfigFactory not a subtype

### How to Reproduce?

run the provided test and observer the error
The test run will succeed if you revert back to: 2.10.2.Final 
The test will also succeed if the CircuitBreaker are removed from the interface
[bsf-online2.zip](https://github.com/quarkusio/quarkus/files/9195673/bsf-online2.zip)

### Output of `uname -a` or `ver`

Linux hty80028.sb1a.sparebank1.no 4.18.0-372.16.1.el8_6.x86_64 #1 SMP Tue Jun 28 03:02:21 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.3" 2022-04-19 OpenJDK Runtime Environment Temurin-17.0.3+7 (build 17.0.3+7) OpenJDK 64-Bit Server VM Temurin-17.0.3+7 (build 17.0.3+7, mixed mode, sharing)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.10.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Ladicek**
Fixes #26953

### CODE REVIEW

**Comment by Ladicek** [comment]
Adding @mkouba and @manovotn for the ArC changes and @michalszynkiewicz and @geoand for the RestClient Reactive mocking changes.

The test in the 2nd commit actually verifies both fixes (we currently only use `@NoClassInterceptors` for RestClient Reactive).

**Review by geoand — APPROVED** [review]
Thanks!

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Methods.java [hunk 1]
```diff
@@ -216,16 +217,27 @@ static Set<MethodInfo> addInterceptedMethodCandidates(BeanDeployment beanDeploym
...
+
+        MethodKey key = new MethodKey(method);
+        if (beanDeployment.getAnnotation(method, DotNames.NO_CLASS_INTERCEPTORS) != null
+                || noClassInterceptorsMethods.contains(key)) {
+            // The set of methods with `@NoClassInterceptors` is shared in the traversal of class hierarchy,
+            // so once a method with the annotation is found, all subsequent occurences of the "same" method
+            // are treated as if they also had it. Given that we traverse classes bottom-up, this works as
+            // expected (presence of `@NoClassInterceptors` on subclass overrides absence on superclass).
+            // We process interfaces after all superclasses, but we inspect interfaces implemented by classes
+            // in a top-down manner, so `@NoClassInterceptors` on interfaces may behave weirdly. It shouldn't
```
Comment (manovotn) [inline independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Methods.java:238]: Would it make sense to detect `@NoClassInterceptors` on interfaces and throw an exception?

**Review by manovotn — APPROVED** [review]
Added one minor question, otherwise looks good.

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Methods.java (hunk 1 above)
Comment (Ladicek) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Methods.java:238]: Thinking about it again, I can see a use case for `default` method on interfaces (and it would work correctly if such method wasn't overridden), so I'd be a little cautious.

We could detect it on abstract methods on interfaces, probably.

Comment (manovotn) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Methods.java:238]: Depends how exactly we need this to work.
In a true CDI manner, you should probably ignore any annotation on interfaces and avoid carrying in over to bean definition (an interceptor binding wouldn't carry over from interface as well). However, that might block too many use cases for this annotation? TBF I don't know what exactly are we using this for so maybe I am just creating noise here :-)

Comment (Ladicek) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Methods.java:238]: That is a good point, but we already do apply interceptors to default methods on interfaces. I'll think a bit more about this.

Comment (manovotn) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Methods.java:238]: > but we already do apply interceptors to default methods on interfaces

Hm, that's true and we only apply class-level ones, right? I mean, class-level annotation from a bean applies to inherited default interface method. So technically, there is no other way to prevent that other than this annotation.
With that in mind, you're right that we could only ignore abstract interface methods.
I'll also give it some more thought

Comment (Ladicek) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Methods.java]: I took a look at this and added a test and adjusted the comment. Basically, this works fine as is even for `default` methods, when they are inherited only once. The current code only behaves weirdly when "the same" `default` method is inherited multiple times. IMHO, we can just leave that be and get back to it when it becomes problematic.

**Comment by gsmet** [comment]
@manovotn all good for you, we can merge?

**Comment by manovotn** [comment]
@gsmet yes, all good
