### PR TITLE
Handle multiple output directories in Kotlin projects

### LINKED ISSUE #6561: QuarkusDev does not start with Kotlin subprojects
To see the full disucssion on this subject, please refer to this chat: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Quarkus.20Dev.20not.20working.20with.20Kotlin.20and.20Subprojects

**Describe the bug**
I have a Quarkus gradle project with two modules `project-a` and `project-a-models`. `project-a` is a quarkus project having a dependency on the plain Kotlin `project-a-models` module.
I can compile this configuration (see sample project linked below). However, when I run `gradlew quarkusDev`, it fails searching a Java path. This is error fixed with the PR #6551. However, when I now run `gradlew quarkusDev`, the server never starts up but hangs after starting the debugger port. 

I ran jstack on gradlew: https://gist.github.com/andreas-eberle/28c3d1438292ab636f6c374988f95f22

And jstack on the built and executed project-a-1.0.0-SNAPSHOT-dev.jar: https://gist.github.com/andreas-eberle/7393cf44da1952d622c0d6383ea09a65

The last part of the output of `gradlew quarkusDev --stacktrace --debug` is here: https://gist.github.com/andreas-eberle/6c074e8f10c2a7514b323430b9f504ed

**Expected behavior**
Server starts up without an exception.

**Actual behavior**
Dev server hangs with PR #6551 or crashes with quarkus 1.1.1-Final

**To Reproduce**
1. Download the reproducer project [quarkus-experiments.zip](https://github.com/quarkusio/quarkus/files/4064951/quarkus-experiments.zip)
2. Install quarkus locally from PR https://github.com/quarkusio/quarkus/pull/6551/files
2. run `./gradlew :project-a:quarkusDev --stacktrace --info`
3. the server won't start up

**Platform**
- Windows 10 x64
- Oracle JDK 64bit Version 1.8.0_231

### PR DESCRIPTION
**Pull request by stuartwdouglas**
Fixes #6561

### CODE REVIEW

File: core/devmode/src/main/java/io/quarkus/dev/IsolatedDevModeMain.java [hunk 1]
```diff
@@ -242,7 +247,7 @@ public void run() {
                     synchronized (DevModeMain.class) {
                         if (runner != null) {
                             try {
-                                runner.close();
```
Comment (stuartwdouglas) [inline core/devmode/src/main/java/io/quarkus/dev/IsolatedDevModeMain.java]: @gsmet I think this might be the root cause of the bind failures on windows

**Review by gastaldi — APPROVED** [review]
LGTM
