### PR TITLE
Initialize the main WorkspaceModule during the configuration time

### LINKED ISSUE #47760: Quarkus 3.22: Test classes w/ superclasses fail with `IllegalAccessError`
### Describe the bug

We're running into a class-loader issue in Quarkus 3.22.2 (worked fine w/ 3.19.3). Seems to be related to but doesn't look like the same as in #47692.

The issue happens for test classes that extend another class, something like this:
```
@QuarkusTest
@TestProfile(QuarkusTestProfilePersistInmemory.class)
class TestBasicOperations extends AbstractTestBasicOperations {
```
...
```
@ExtendWith(QuarkusNessieClientResolver.class)
abstract class AbstractTestBasicOperations {
```
[TestBasicOperations](https://github.com/projectnessie/nessie/blob/main/servers/quarkus-server/src/test/java/org/projectnessie/server/TestBasicOperations.java) + [AbstractTestBasicOperations](https://github.com/projectnessie/nessie/blob/main/servers/quarkus-server/src/testFixtures/java/org/projectnessie/server/AbstractTestBasicOperations.java)
Reproducible via `./gradlew :nessie-quarkus:test --tests TestBasicOperations --info` against [this branch](https://github.com/projectnessie/nessie/tree/renovate/quarkus-platform-and-group)

(leads to `java.lang.IllegalAccessError: class org.projectnessie.server.TestBasicOperations cannot access its abstract superclass ...AbstractTestBasicOperations (...TestBasicOperations is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @9dbb1d9; org.projectnessie.server.AbstractTestBasicOperations is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @e4e1ef5`)

If that test class doesn't have a superclass, it works fine. It happens for quite a bunch of tests.

It's also unrelated to our special ThreadPerTestClassExecutionExecutorService - same issue with the "vanilla JUnit engine/executor".

```
java.lang.ExceptionInInitializerError
java.lang.RuntimeException: java.lang.ExceptionInInitializerError
    at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:693)
    at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:791)
    at java.base/java.util.Optional.orElseGet(Optional.java:364)
    at org.projectnessie.junit.engine.ThreadPerTestClassExecutionExecutorService.executeTask(ThreadPerTestClassExecutionExecutorService.java:109)
    at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
    at org.projectnessie.junit.engine.ThreadPerTestClassExecutionExecutorService.invokeAll(ThreadPerTestClassExecutionExecutorService.java:75)
    at org.projectnessie.junit.engine.ThreadPerTestClassExecutionExecutorService.lambda$executeTask$0(ThreadPerTestClassExecutionExecutorService.java:88)
    at java.base/java.lang.Thread.run(Thread.java:1575)
Caused by: java.lang.ExceptionInInitializerError
    at java.base/java.lang.Class.forName0(Native Method)
    at java.base/java.lang.Class.forName(Class.java:578)
    at java.base/java.lang.Class.forName(Class.java:557)
    at io.quarkus.runner.bootstrap.StartupActionImpl.run(StartupActionImpl.java:294)
    at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:232)
    at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:660)
    at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:712)
    ... 2 more
Caused by: java.lang.RuntimeException: Failed to start quarkus
    at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
    ... 9 more
Caused by: java.lang.IllegalAccessError: class org.projectnessie.server.TestBasicOperations cannot access its abstract superclass org.projectnessie.server.AbstractTestBasicOperations (org.projectnessie.server.TestBasicOperations is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @9dbb1d9; org.projectnessie.server.AbstractTestBasicOperations is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @e4e1ef5)
    at java.base/java.lang.ClassLoader.defineClass1(Native Method)
    at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1026)
    at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:565)
    at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:523)
    at org.projectnessie.server.TestBasicOperations_Bean.<init>(Unknown Source)
    at io.quarkus.arc.setup.Default_ComponentsProvider.addBeans9(Unknown Source)
    at io.quarkus.arc.setup.Default_ComponentsProvider.getComponents(Unknown Source)
    at io.quarkus.arc.impl.ArcContainerImpl.<init>(ArcContainerImpl.java:129)
    at io.quarkus.arc.Arc.initialize(Arc.java:38)
    at io.quarkus.arc.runtime.ArcRecorder.initContainer(ArcRecorder.java:52)
    at io.quarkus.runner.recorded.ArcProcessor$initializeContainer1770303700.deploy_0(Unknown Source)
    at io.quarkus.runner.recorded.ArcProcessor$initializeContainer1770303700.deploy(Unknown Source)
    ... 10 more
```

Also seeing another variant that's also related to class-loading for the Renovate-PR for Apache Polaris [CI run](https://github.com/apache/polaris/actions/runs/14852969957/job/41699929543?pr=1483)

We suspect it's related to the [test classloading rewrite](https://quarkus.io/blog/test-classloading-rewrite/).

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### LINKED ISSUE #48137: ClientExceptionMapper incorrectly detected as duplicate when using java-test-fixtures plugin
### Describe the bug

When using the `java-test-fixtures` Gradle plugin in a project with a REST client that has a `@ClientExceptionMapper` annotated method, Quarkus incorrectly reports that there are multiple instances of the ClientExceptionMapper in the same interface, even though only one exists.

The error occurs because Quarkus detects the same class in both the main sources and test fixtures, treating them as separate instances of the mapper.

### Expected behavior

The `@ClientExceptionMapper` should work correctly when the `java-test-fixtures` plugin is present, as there is only one actual mapper method defined in the interface.

### Actual behavior

The build fails with the following error:

```
java.lang.IllegalStateException: Only a single instance of 'io.quarkus.rest.client.reactive.ClientExceptionMapper' is allowed per REST Client interface. Offending class is 'org.example.MyRemoteService'
	at io.quarkus.rest.client.reactive.deployment.RestClientReactiveProcessor.populateClientExceptionMapperFromAnnotations(RestClientReactiveProcessor.java:707)
```

### How to Reproduce?

Run the test in the reproducer. Note its failure.

[quarkus-client-exception-mapper-reproducer.zip](https://github.com/user-attachments/files/20511526/quarkus-client-exception-mapper-reproducer.zip)

### Output of `uname -a` or `ver`

Darwin MacBookPro.localdomain 24.4.0 Darwin Kernel Version 24.4.0: Fri Apr 11 18:33:47 PDT 2025; root:xnu-11417.101.15~117/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "21.0.6" 2025-01-21 LTS OpenJDK Runtime Environment Temurin-21.0.6+7 (build 21.0.6+7-LTS) OpenJDK 64-Bit Server VM Temurin-21.0.6+7 (build 21.0.6+7-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.23.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

 ------------------------------------------------------------ Gradle 8.14.1 ------------------------------------------------------------  Build time:    2025-05-22 13:44:09 UTC Revision:      c174b82566a79e3575bac8c7648c7b36cd815e94  Kotlin:        2.0.21 Groovy:        3.0.24 Ant:           Apache Ant(TM) version 1.10.15 compiled on August 25 2024 Launcher JVM:  21.0.6 (Eclipse Adoptium 21.0.6+7-LTS) Daemon JVM:    /Library/Java/JavaVirtualMachines/temurin-21.jdk/Contents/Home (no JDK specified, using current Java home) OS:            Mac OS X 15.4.1 aarch64

### Additional information

This behavior is observed in 3.23.0 but not in 3.21.4.

### LINKED ISSUE #48157: Regression causing runtime link error in tests with gradle testFixtures
### Describe the bug

Using recent versions of quarkus with gradle and testing with a dependency on testFixtures results in runtime link errors apparently due to different class loaders used for sourceSet=`src/test` and sourceSet=`src/testFixtures`.

This problem first appeared with `3.22.0.CR1`.

### Expected behavior

Tests should be able to rely on dependencies in `src/testFixtures`.

### Actual behavior

```
classloader(ExampleTest): QuarkusClassLoader:Quarkus Runtime ClassLoader: TEST for JUnitQuarkusTest-no-profile (QuarkusTest) restart no:0@4c1d59cd
classloader(TestFixture): QuarkusClassLoader:Quarkus Base Runtime ClassLoader: TEST for JUnitQuarkusTest-no-profile (QuarkusTest)@4baf352a
```

```
    java.lang.IllegalAccessError: class org.acme.ExampleTest tried to access method 'java.lang.String org.acme.TestFixture.toString(java.lang.Object)' (org.acme.ExampleTest is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @4c1d59cd; org.acme.TestFixture is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @4baf352a)
```

### How to Reproduce?

There is a reproducer here:

https://github.com/matteriben/quarkus-gradle-test-fixtures-reproducer/actions/runs/15354184191

### Output of `uname -a` or `ver`

Linux toolbx 6.12.4-200.fc41.aarch64 #1 SMP PREEMPT_DYNAMIC Mon Dec  9 20:24:04 UTC 2024 aarch64 GNU/Linux

### Output of `java -version`

```
openjdk version "21.0.6" 2025-01-21
OpenJDK Runtime Environment (Red_Hat-21.0.6.0.7-1) (build 21.0.6+7)
OpenJDK 64-Bit Server VM (Red_Hat-21.0.6.0.7-1) (build 21.0.6+7, mixed mode, sharing)
```

### Quarkus version or git rev

3.22.0.CR1 or newer

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

```
------------------------------------------------------------
Gradle 8.13
------------------------------------------------------------

Build time:    2025-02-25 09:22:14 UTC
Revision:      073314332697ba45c16c0a0ce1891fa6794179ff

Kotlin:        2.0.21
Groovy:        3.0.22
Ant:           Apache Ant(TM) version 1.10.15 compiled on August 25 2024
Launcher JVM:  21.0.6 (Red Hat, Inc. 21.0.6+7)
Daemon JVM:    /usr/lib/jvm/java-21-openjdk (no JDK specified, using current Java home)
OS:            Linux 6.12.4-200.fc41.aarch64 aarch64
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by aloubyansky**
- Fixes: https://github.com/quarkusio/quarkus/issues/48157
- Fixes: https://github.com/quarkusio/quarkus/issues/48137
- Fixes https://github.com/quarkusio/quarkus/issues/47760

### CODE REVIEW

**Comment by aloubyansky** [comment]
I need to run the update extension dependencies script

File: devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/QuarkusApplicationModelTask.java [hunk 1]
```diff
@@ -55,34 +51,30 @@
 import org.gradle.api.tasks.OutputFile;
 import org.gradle.api.tasks.PathSensitive;
 import org.gradle.api.tasks.PathSensitivity;
-import org.gradle.api.tasks.SourceSet;
 import org.gradle.api.tasks.TaskAction;
-
-import com.google.common.base.Preconditions;
+import org.gradle.internal.component.external.model.ModuleComponentArtifactIdentifier;
+import org.jetbrains.annotations.NotNull;
```
Comment (geoand) [inline devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/QuarkusApplicationModelTask.java]: Let's try to get rid of these (which I am pretty sure you didn't add yourself as IntelliJ does this automatically)

**Review by geoand — APPROVED** [review]

File: devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/QuarkusApplicationModelTask.java (hunk 1 above)
Comment (aloubyansky) [reply devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/QuarkusApplicationModelTask.java]: Ah, yes

Comment (holly-cummins) [reply devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/QuarkusApplicationModelTask.java]: SO annoying. I spent a while trying to figure out what the config was to disable it, and couldn't find any. I wonder if we want a PR validation step to check for them?

Comment (geoand) [reply devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/QuarkusApplicationModelTask.java]: 👍🏽

File: integration-tests/gradle/src/test/java/io/quarkus/gradle/TestFixtureModuleWithPackagePrivateParentTest.java [hunk 2]
```diff
@@ -6,12 +6,11 @@
 import java.io.IOException;
 import java.net.URISyntaxException;
 
-import org.junit.jupiter.api.Disabled;
 import org.junit.jupiter.api.Test;
 
 public class TestFixtureModuleWithPackagePrivateParentTest extends QuarkusGradleWrapperTestBase {
 
-    @Disabled("See https://github.com/quarkusio/quarkus/issues/47760")
+    //@Disabled("See https://github.com/quarkusio/quarkus/issues/47760")
```
Comment (holly-cummins) [inline integration-tests/gradle/src/test/java/io/quarkus/gradle/TestFixtureModuleWithPackagePrivateParentTest.java:13]: Can we delete the line entirely, instead of commenting it out?

File: devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/QuarkusApplicationModelTask.java (hunk 1 above)
Comment (geoand) [reply devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/QuarkusApplicationModelTask.java]: Does the following work for you @holly-cummins ?

Screenshot from 2025-06-03 11-28-20

and

Screenshot from 2025-06-03 11-28-32

Comment (holly-cummins) [reply devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/QuarkusApplicationModelTask.java]: Ah, yes, will try that. Thank you! While I was trying to replicate your screenshot I also just found this setting, which I've also disabled:

image

File: integration-tests/gradle/src/test/java/io/quarkus/gradle/TestFixtureModuleWithPackagePrivateParentTest.java (hunk 2 above)
Comment (aloubyansky) [reply integration-tests/gradle/src/test/java/io/quarkus/gradle/TestFixtureModuleWithPackagePrivateParentTest.java:13]: Sure, I'll delete it in a follow up.
