### PR TITLE
Class loading fixes around CT

### LINKED ISSUE #23355: Run ArchUnit tests using extended support for JUnit 5 in continuous testing
### Description

ArchUnit tests written in the following manner are not picked up by continuous testing:
```java
@AnalyzeClasses(packages = "com.myapp")
public class ArchitectureTest {

    // ArchRules can just be declared as static fields and will be evaluated
    @ArchTest
    public static final ArchRule rule1 = classes().should()...

    @ArchTest
    public static final ArchRule rule2 = classes().should()...

    @ArchTest
    public static void rule3(JavaClasses classes) {
        // The runner also understands static methods with a single JavaClasses argument
        // reusing the cached classes
    }
}
```
(taken from https://www.archunit.org/userguide/html/000_Index.html#_junit_support)

[q_ct-archunit.zip](https://github.com/quarkusio/quarkus/files/7982708/q_ct-archunit.zip) contains a single AU test and continous testing displays: "No tests found". `mvn test` does execute the test (and it fails deliberately).

I played around with `JunitTestRunner` and with a few additional lines the class is discovered, but somewhere in the depths of JUnit something doesn't work as expected and the `TestPlan` seems to be empty.
I also tried loading AU parent-first, because there is a special engine: https://github.com/TNG/ArchUnit/blob/main/archunit-junit/junit5/engine/src/main/java/com/tngtech/archunit/junit/ArchUnitTestEngine.java
But no luck so far.

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by stuartwdouglas**
- Scan for @Testable annotations that are not in the deployment
- Make sure that the engine is part of the same CL heirachy as unit
  tests

Fixes #23355 when combined with https://github.com/TNG/ArchUnit/pull/781

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
@famod these changes almost get it working but it also needs the linked PR in ArchUnit

File: core/deployment/src/main/java/io/quarkus/deployment/dev/testing/JunitTestRunner.java [hunk 1]
```diff
@@ -556,6 +556,15 @@ private DiscoveryResult discoverTestClasses() {
                             enclosingClasses.put(classInfo.name(), enclosing);
                         }
                     }
+                } else if (instance.target().kind() == AnnotationTarget.Kind.FIELD) {
+                    ClassInfo classInfo = instance.target().asField().declaringClass();
+                    allTestClasses.add(classInfo.name());
+                    if (classInfo.classAnnotation(NESTED) != null) {
```
Comment (famod) [inline core/deployment/src/main/java/io/quarkus/deployment/dev/testing/JunitTestRunner.java:562]: Not sure if `@Nested` is even supported for field-style AU tests, but I guess it doesn't hurt.

File: core/deployment/src/main/java/io/quarkus/deployment/dev/testing/JunitTestRunner.java [hunk 2]
```diff
@@ -673,6 +682,24 @@ public String apply(Class<?> aClass) {
                 }
             }
         }
+        Set<DotName> processed = new HashSet<>();
+        processed.addAll(ret);
+        for (ClassInfo clazz : index.getKnownClasses()) {
+            for (DotName annotation : clazz.annotations().keySet()) {
```
Comment (famod) [inline core/deployment/src/main/java/io/quarkus/deployment/dev/testing/JunitTestRunner.java:688]: Isn't loading _all_ (used) annotations a bit expensive? OTOH I have no suggestion how to improve that (except for checking only for specific annotations).

**Review by famod — COMMENTED** [review]
Cool, thanks!

But it seems this really has to wait for the ArchUnit fix to be released because with this change on top of 2.7 (main is broken elsewhere for my project), _all_ my `quarkus:test` and `quarkus:dev` CT scenarios are failing with `ClassNotFoundException: org.acme.MyArchTest`.

File: core/deployment/src/main/java/io/quarkus/deployment/dev/testing/JunitTestRunner.java (hunk 2 above)
Comment (stuartwdouglas) [reply core/deployment/src/main/java/io/quarkus/deployment/dev/testing/JunitTestRunner.java:688]: Not really, it is only loading a single instance for each annotation type, and already skips JUnit ones. I would not expect tests to be using a large amount of distinct annotations.

**Comment by stuartwdouglas** [comment]
There is nothing I can do about the ClassNotFoundException unfortunately, it really needs to be fixed in ArchUnit

**Comment by famod** [comment]
No worries, you've done a lot already! 🙂 
I just wanted to point out that we unfortunately cannot (should not) merge this is until AU released the fix. That wasn't entirely clear to me until I actually tested it.

**Comment by famod** [comment]
FTR, even `-Dquarkus.test.exclude-pattern='.*ArchTest'` doesn't help.

**Comment by stuartwdouglas** [comment]
@famod I don't suppose you know anyone from the ArchUnit side that could look at the PR?

**Comment by famod** [comment]
@stuartwdouglas no, unfortunately. I've just pinged the maintainer.

**Comment by famod** [comment]
So with that 0.23-SNAPSHOT of archunit things _are_ looking better, but two things are odd:
screenshot

First, I'd expected the test to fail - just like when running via surefire. It might not be "seeing" the class in `main/java`?
I'l try to get more log output.

Second, it says "No tests found". It shows somethign different for the breif moment when it's actually running that test, but the final state is as shown in the screenshot.

**Comment by famod** [comment]
[q_ct-archunit_SNAPSHOT.zip](https://github.com/quarkusio/quarkus/files/8075394/q_ct-archunit_SNAPSHOT.zip) contains 0.23-SNAPSHOT of AU.

**Comment by famod** [comment]
So the problem with that unreported failure is not related to class loading. Instead, the problem is that with such a field style AU test, `testIdentifier.getSource()` returns a [`com.tngtech.archunit.junit.FieldSource`](https://github.com/TNG/ArchUnit/blob/v0.22.0/archunit-junit/junit5/engine-api/src/main/java/com/tngtech/archunit/junit/FieldSource.java).
Unsurprisingly, `JunitTestRunner` doesn't handle this special source implementation.

At this point, the only thing that comes to my mind is reflection which is pretty...meh!

**Comment by famod** [comment]
I got something ready, will push another commit.

**Comment by famod** [comment]
@stuartwdouglas I rebased and added a fix for the reporting of ArchUnit field style tests.
Not pretty, but WDYT?

File: core/deployment/src/main/java/io/quarkus/deployment/dev/testing/JunitTestRunner.java [hunk 3]
```diff
@@ -419,15 +384,64 @@ public void reportingEntryPublished(TestIdentifier testIdentifier, ReportEntry e
...
+
+    private String getDisplayNameFromIdentifier(TestIdentifier testIdentifier) {
+        if (testIdentifier.getSource().isPresent()) {
+            var testSource = testIdentifier.getSource().get();
+            if (testSource instanceof MethodSource) {
+                var methodSource = (MethodSource) testSource;
+                return methodSource.getJavaClass().getSimpleName() + "#" + testIdentifier.getDisplayName();
+            } else if (testSource.getClass().getName().equals("com.tngtech.archunit.junit.FieldSource")) {
+                try {
+                    return (String) testSource.getClass().getMethod("getFieldName").invoke(testSource)
```
Comment (famod) [inline core/deployment/src/main/java/io/quarkus/deployment/dev/testing/JunitTestRunner.java:426]: Just realized that this needs to get the class name, not the field name.

Comment (stuartwdouglas) [reply core/deployment/src/main/java/io/quarkus/deployment/dev/testing/JunitTestRunner.java:426]: I don't like it, but maybe it is ok for the short term. The only other option I can think of is to make this pluggable and create a quarkus-archunit Quarkiverse extension to support it. 

If this is all that is needed then maybe we can live with it, but if there are any other hacks required then this should be pulled into its own module IMHO.

Comment (famod) [reply core/deployment/src/main/java/io/quarkus/deployment/dev/testing/JunitTestRunner.java:426]: AFAICS, this is the only necessary "hack" for AU (actually only the `className` call, `fieldName` is not relevant and I will remove it).

For a quarkiverse extension we would need to denfine an SPI, right?

Alternatively, it would be nice if JUnit would offer either an optional method in `TestSource` returning the class name or a separate interface that a source can implement additionally.

Comment (famod) [reply core/deployment/src/main/java/io/quarkus/deployment/dev/testing/JunitTestRunner.java]: I removed that second reflective call (`fieldName`) and fixed a regression w.r.t. `testClassUsages.updateTestData(...)`.

I could improve that workaround if we decide to actually _load_ the class via the name that is provided by `com.tngtech.archunit.junit.FieldSource`. This way we could stick with `Class<?>` as before.
But I'm not sure this is a good idea.
Maybe AU can provide the actual class object via that `FieldSource`. We'd still need to get it via reflection, but we wouldn't need to juggle with a `String` class name.

Comment (famod) [reply core/deployment/src/main/java/io/quarkus/deployment/dev/testing/JunitTestRunner.java]: > Maybe AU can provide the actual class object via that `FieldSource`. We'd still need to get it via reflection, but we wouldn't need to juggle with a `String` class name.

https://github.com/TNG/ArchUnit/pull/800

Comment (famod) [reply core/deployment/src/main/java/io/quarkus/deployment/dev/testing/JunitTestRunner.java]: @geoand do you have anything to add to this?

Comment (famod) [reply core/deployment/src/main/java/io/quarkus/deployment/dev/testing/JunitTestRunner.java]: > > Maybe AU can provide the actual class object via that `FieldSource`. We'd still need to get it via reflection, but we wouldn't need to juggle with a `String` class name.
> 
> [TNG/ArchUnit#800](https://github.com/TNG/ArchUnit/pull/800)

This was just merged and will be part of 0.23 which will be released this weekend. I'll adjust this PR afterwards.
@stuartwdouglas Would be nice to agree (or not) on the (temporary) hackish workaround.

Comment (famod) [reply core/deployment/src/main/java/io/quarkus/deployment/dev/testing/JunitTestRunner.java]: I pushed an adjustment to ArchUnit 0.23.0 which was released today. It's still a reflection hack, but since we can now get the full class object, the change is less invasive than previously.
I double checked with my actual, more complex project (not just the small reproducer).

@stuartwdouglas please have a look. I won't merge before your "ok".

I'll also add the backport label (IIRC @gsmet was planning to release 2.7.2 very soon).
With that we would be pressing 2.7.2+ users to update to AU 0.23.0 (given they use continuous testing), which might be slighty debatable, but I think it's ok. I'll also add something to the migration guide.

**Review by famod — APPROVED** [review]

**Comment by famod** [comment]
Test failures are not related.

File: core/deployment/src/main/java/io/quarkus/deployment/dev/testing/JunitTestRunner.java (hunk 3 above)
Comment (stuartwdouglas) [reply core/deployment/src/main/java/io/quarkus/deployment/dev/testing/JunitTestRunner.java]: I think the hack is ok for now. If we end up needing more of this sort of thing then we should add a SPI.

Comment (famod) [reply core/deployment/src/main/java/io/quarkus/deployment/dev/testing/JunitTestRunner.java]: Turns out all those filters (e.g. `JunitTestRunner.RegexFilter`) don't cover that `FieldSource` yet (obviously), so there is no way to exclude a certain field-style ArchUnit test. So SPI it is... 😒 
Also, I'm seeing more strange classloading issues in some of my tests (which is the actual motivation for the exclusion attempt).
E.g. one fails right away not finding an interface (which is used in `org.mapstruct.Mapper.config()`) and other tests working with class objects are failing after a reload (caused by code changes). The latter might show a general issue, not only related to ArchUnit.
I'm also seeing an annotation class loading issue in a custom `org.junit.jupiter.api.extension.BeforeEachCallback` (only CT).

Time to create some issues and reproducers...
