### PR TITLE
Use Arc features in Hibernate extensions for eager startup and active/inactive

### LINKED ISSUE #43594: Use Arc features in Hibernate extensions for eager startup and active/inactive
### Description

https://github.com/quarkusio/quarkus/pull/41810 introduces a way for extensions to declare beans as "inactive", so that:

1. Any attempt to access those beans, triggering instantiation, will raise an exception with an actionable message (e.g. "you forgot to set the datasource JDBC URL")
2. An application that injects these beans statically (e.g. `@Inject InactiveBean inactiveBean;`) in a non-synthetic bean will fail on startup with the same message, along with a list of problematic injection points.
3. An application that does not inject these beans statically in a non-synthetic bean will start up just fine, and work fine as long as it doesn't access those beans.

We should try to leverage this in Hibernate extensions that allow marking beans as inactive and/or depend on other, potentially inactive beans:

* If `quarkus.hibernate-orm.active = false`, the corresponding `SessionFactory`/`Session` beans would be inactive
* If a datasource used by Hibernate ORM is inactive (explicitly or because its URL is not set), the corresponding `SessionFactory`/`Session` beans would be inactive
* If `quarkus.hibernate-search-orm-elasticsearch.active = false`, the corresponding `SearchMapping`/`SearchSession` beans would be inactive
* If an Elasticsearch client [used by Hibernate Search](https://github.com/quarkusio/quarkus/issues/26991) is inactive (explicitly or because its URL is not set), the corresponding `SearchMapping`/`SearchSession` beans would be inactive
* Same for named PUs

### Implementation ideas

Problems to be solved:

1. What happens in applications that use Panache, where the session possibly only gets retrieved dynamically in `io.quarkus.hibernate.orm.panache.common.runtime.AbstractJpaOperations#getSession(java.lang.String)`? Shouldn't these applications fail on startup too? Maybe we need some synthetic injection point, and we need Arc to take synthetic injection points into account?
2. What happens in Hibernate Search when multiple backends are defined, and only one points to an inactive Elasticsearch client?

### PR DESCRIPTION
**Pull request by yrodiere**
Draft for now.

To do:

- [x] Implement basic functionality for Hibernate ORM/Reactive
- [x] Run basic tests locally for Hibernate ORM/Reactive
- [x] Handle FIXME in the code about initialization (one-by-one vs. parallel threads)
- [x] Handle FIXME in the code about Panache
- [x] Run the whole test suite and not just a few tests in the ORM extension
- [x] Handle Hibernate Envers
- [x] Handle Hibernate Search
- [x] ~~Handle Hibernate Validator ([remove `JPATraversableResolver` if ORM deactivated?](https://github.com/quarkusio/quarkus/blob/28a73f6652d1129cd78f677256060ccee16f367d/extensions/hibernate-validator/runtime/src/main/java/io/quarkus/hibernate/validator/runtime/HibernateValidatorRecorder.java#L299))~~ => Bad idea, this would be complex to implement, and also to use (if entity types are used outside of PUs, why should the PU active/inactive status matter?
- [x] Update documentation
- [x] Write migration guide entry

* Closes #43594 

Migration guide entry:

`````asciidoc
== Hibernate ORM

[[hibernate-orm-inactive-fail-fast]]
=== Hibernate ORM usage fails fast if persistence unit is deactivated

In previous versions of Quarkus, when the persistence unit was deactivated (`quarkus.hibernate-orm.active=false`), the application would be allowed to start successfully, but could fail much later upon first access to a Hibernate bean (`EntityManager`, `Session`, `SessionFactory`, ...).

Starting with this version of Quarkus, persistence units that are deactivated will lead to a startup failure if Quarkus can detect they are used:

* Static CDI injection points involving the persistence unit (`@Inject Session session`, `@Inject SessionFactory sessionFactory`, ...) will cause application startup to fail with an explicit, actionable message.
* Dynamic retrieval of the persistence unit (e.g. through `CDI.getBeanContainer()`/`Arc.instance()`, or by injecting an `Instance<Session>`) will not be detected on startup, but will cause an exception to be thrown with an explicit, actionable message.

The <<hibernate-reactive-inactive-fail-fast,Hibernate Reactive>> and <<hibernate-search-inactive-fail-fast,Hibernate Search>> extensions implement a similar behavior for their `Mutiny.SessionFactory`/`SearchSession`/`SearchMapping` CDI beans.

If your application needs to inject a `EntityManager/`Session`/`EntityManagerFactory`/`SessionFactory` or related bean for a persistence unit that can potentially be deactivated or have no URL, you may encounter a startup failure similar to this:

```
io.quarkus.arc.InactiveBeanException: Bean is not active: SYNTHETIC bean [class=org.hibernate.Session, id=QdxvhYUzh5cgfepxgL43K9-OFvU]
Reason: Persistence unit '<default>' was deactivated through configuration properties. To activate the persistence unit, set configuration property 'quarkus.hibernate-orm.active' to 'true' and configure datasource '<default>'. Refer to https://quarkus.io/guides/datasource for guidance.
To avoid this exception while keeping the bean inactive:
	- Configure all extensions consuming this bean as inactive as well, if they allow it, e.g. 'quarkus.someextension.active=false'
	- Make sure that custom code only accesses this bean if it is active
	- Inject the bean with 'Instance<org.hibernate.Session>' instead of 'org.hibernate.Session'
This bean is injected into:
	- io.quarkus.hibernate.orm.config.ConfigActiveFalseStaticInjectionTest$MyBean#session
[...]
```

To avoid this failure, follow the instructions in the exception message.
In particular, consider injecting the problematic bean as an `InjectableInstance` (for example `@Inject InjectableInstance<Session> session`) instead.
You can check whether that bean is active using `.getHandle().getBean().isActive().result()` on the `InjectableInstance`, and retrieve the bean instance using `InjectableInstance#get()`.
See https://quarkus.io/guides/hibernate-orm#persistence-unit-active for an example of such a setup for `Session`.

== Hibernate Reactive

[[hibernate-reactive-inactive-fail-fast]]
=== Hibernate Reactive usage fails fast if persistence unit is deactivated

Starting with this version of Quarkus, Hibernate Reactive persistence units that are deactivated will lead to a startup failure if Quarkus can detect they are used.

See the <<hibernate-orm-inactive-fail-fast,datasources,similar migration guide entry for Hibernate ORM>> for more information.

== Hibernate Search

[[hibernate-search-inactive-fail-fast]]
=== Hibernate Search usage fails fast if persistence unit is deactivated

Starting with this version of Quarkus, Hibernate Search mappings that are deactivated will lead to a startup failure if Quarkus can detect they are used.

See the <<hibernate-orm-inactive-fail-fast,datasources,similar migration guide entry for Hibernate ORM>> for more information.
`````

### CODE REVIEW

**Comment by yrodiere** [comment]
Hey @Sanne I remember discussing this with you: silently deactivating the PU when the datasource has no URL and proceeding with startup if the PU beans (session, session factory, ...) are not injected anywhere. I remember you had some conceerns, probably because this would be a very breaking change and/or simply inconvenient behavior.

Well, if that was your opinion, I'm starting to think like you. For example in the Panache case, where the session might not even be injected anywhere, this would be pretty bad.

So, I'm rolling this back a bit: I'll only silently deactivate the PU if _there are no entity types in the PU_ (which we intend to make possible through #48732). In that case it's likely that Hibernate ORM is being used as a simple wrapper of JDBC with more convenient querying capabilities (with projections, ...), so I think it makes more sense.

This means in the vast majority of cases we'll get pretty much the same behavior as today, so it's much safer, too.

**Comment by yrodiere** [comment]
Hey @marko-bekhta or @lucamolteni can I please ask one of you review this? If you skip the first commit it's _almost_ a reasonable amount of code (and the vast majority is just tests that look very similar).

EDIT: No need for _both_ of you to review of course :)

File: extensions/hibernate-envers/deployment/src/test/java/io/quarkus/hibernate/orm/envers/config/ConfigOrmActiveFalseAndAuditedEntityTest.java [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+            .withApplicationRoot((jar) -> jar.addClass(MyAuditedEntity.class))
+            .withConfigurationResource("application.properties")
+            .overrideConfigKey("quarkus.hibernate-orm.active", "false");
+
+    @Test
+    public void test() {
+        SessionFactory sessionFactory = Arc.container().instance(SessionFactory.class).get();
+
+        // The bean is always available to be injected during static init
+        // since we don't know whether Hibernate Reactive will be active at runtime.
```
Comment (marko-bekhta) [inline extensions/hibernate-envers/deployment/src/test/java/io/quarkus/hibernate/orm/envers/config/ConfigOrmActiveFalseAndAuditedEntityTest.java]:
```suggestion
        // since we don't know whether Hibernate ORM will be active at runtime.
```

🙈

File: extensions/hibernate-search-orm-elasticsearch/deployment/src/test/java/io/quarkus/hibernate/search/orm/elasticsearch/test/configuration/ConfigOrmActiveFalseAndIndexedEntityTest.java [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+                    () -> ShrinkWrap.create(JavaArchive.class).addClass(IndexedEntity.class))
+            .withConfigurationResource("application.properties")
+            .overrideConfigKey("quarkus.hibernate-orm.active", "false");
+
+    @Test
+    public void test() {
+        SessionFactory sessionFactory = Arc.container().instance(SessionFactory.class).get();
+
+        // The bean is always available to be injected during static init
+        // since we don't know whether Hibernate Reactive will be active at runtime.
```
Comment (marko-bekhta) [inline extensions/hibernate-search-orm-elasticsearch/deployment/src/test/java/io/quarkus/hibernate/search/orm/elasticsearch/test/configuration/ConfigOrmActiveFalseAndIndexedEntityTest.java]:
```suggestion
        // since we don't know whether Hibernate ORM will be active at runtime.
```

🙈

File: extensions/hibernate-reactive/deployment/src/test/java/io/quarkus/hibernate/reactive/config/datasource/MultiplePUAsAlternativesWithBeanProducerTest.java [hunk 3]
```diff
@@ -0,0 +1,149 @@
...
+                .overrideConfigKey("quarkus.hibernate-orm.pu-1.schema-management.strategy", "drop-and-create")
+                .overrideConfigKey("quarkus.hibernate-orm.pu-1.active", "false")
+                .overrideConfigKey("quarkus.datasource.ds-1.db-kind", "postgresql")
+                .overrideConfigKey("quarkus.datasource.ds-1.active", "false")
+                .overrideConfigKey("quarkus.hibernate-orm.pu-2.packages", MyEntity.class.getPackageName())
+                .overrideConfigKey("quarkus.hibernate-orm.pu-2.datasource", "ds-2")
+                .overrideConfigKey("quarkus.hibernate-orm.pu-2.schema-management.strategy", "drop-and-create")
+                .overrideConfigKey("quarkus.hibernate-orm.pu-2.active", "false")
+                .overrideConfigKey("quarkus.datasource.ds-2.db-kind", "postgresql")
+                .overrideConfigKey("quarkus.datasource.ds-2.active", "false")
```
Comment (marko-bekhta) [inline extensions/hibernate-reactive/deployment/src/test/java/io/quarkus/hibernate/reactive/config/datasource/MultiplePUAsAlternativesWithBeanProducerTest.java:65]: Just a question 🙂 since you've created the `application-postgres-reactive-url-only.properties` just for this test, why didn't you want to list these properties in there? 🙈

File: docs/src/main/asciidoc/datasource.adoc [hunk 4]
```diff
@@ -454,7 +454,7 @@ If a datasource is not active:
 * Other Quarkus extensions that consume the datasource may cause application startup to fail.
 +
 In this case, you must also deactivate those other extensions.
-To see an example of this scenario, refer to xref:hibernate-orm.adoc#persistence-unit-active[this section of the Hibernate ORM guide].
+To see an example of this scenario, refer to xref:hibernate-orm.adoc#persistence-unit-active[this section of the Hibernate ORM guide]. For Hibernate ORM, deactivation of the persistence unit is automatic when the datasource is inactive.
```
Comment (marko-bekhta) [inline docs/src/main/asciidoc/datasource.adoc:457]: Are there any other extensions we can reference here?
I'm just thinking, since the ORM one will deactivate the PU automatically now, users won't really need to add that `active=false` on the ORM's side anymore 🤔

File: docs/src/main/asciidoc/hibernate-orm.adoc [hunk 5]
```diff
@@ -543,15 +543,19 @@ CriteriaBuilder criteriaBuilder;
...
 
 To deactivate a persistence unit at runtime, set `quarkus.hibernate-orm[.optional name].active` to `false`.
+
 If a persistence unit is not active:
 
-* The `SessionFactory` will not start during application startup.
-* Accessing the `EntityManagerFactory`/`EntityManager` or `SessionFactory`/`Session` will cause an exception to be thrown.
+* The `SessionFactory` does not start during application startup.
+* Static CDI injection points involving the persistence unit, such as `@Inject SessionFactory sf` or `@Inject Session session`, cause application startup to fail.
+* Dynamic retrieval of the persistence unit, such as through `CDI.getBeanContainer()`, `Arc.instance()`, or by injecting an `Instance<Session>`, causes an exception to be thrown.
```
Comment (marko-bekhta) [inline docs/src/main/asciidoc/hibernate-orm.adoc]: maybe? 
```suggestion
* Dynamic retrieval of the persistence unit, such as through `CDI.getBeanContainer()`, `Arc.instance()`, or from an injected `Instance<Session>`, causes an exception to be thrown.
```
That is if my understanding is correct: the user can still have the `Instance<Session>` injected but it's when they try to get the bean out of it when things would fail 🙈

File: docs/src/main/asciidoc/hibernate-orm.adoc [hunk 6]
```diff
@@ -543,15 +543,19 @@ CriteriaBuilder criteriaBuilder;
...
+* Other Quarkus extensions that consume the persistence unit may cause application startup to fail.
++
+In this case, you must also deactivate those other extensions.
```
Comment (marko-bekhta) [inline docs/src/main/asciidoc/hibernate-orm.adoc:558]: I was going to ask if we'd want to link to Search or some other extension to show how to deactivate them, but noticed we don't have a section in the Search guide 🙈 do we want to add something there ?(in a different PR 🙂)

File: docs/src/main/asciidoc/hibernate-orm.adoc [hunk 7]
```diff
@@ -602,37 +606,49 @@ xref:config-reference.adoc#multiple-profiles[setting `quarkus.profile`]:
 ----
```
Comment (marko-bekhta) [inline docs/src/main/asciidoc/hibernate-orm.adoc:606]:
```suggestion
# Add any oracle-related runtime configuration here, prefixed with "%oracle."
----
```
noticed a typo from before 🙈

File: extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/HibernateOrmRecorder.java [hunk 8]
```diff
@@ -116,6 +117,27 @@ public void startAllPersistenceUnits(BeanContainer beanContainer, ShutdownContex
         jpaConfig.startAll();
     }
 
+    public Supplier<ActiveResult> checkActiveSupplier(String persistenceUnitName, Optional<String> dataSourceName,
+            boolean isFromPersistenceXml) {
+        return new Supplier<>() {
+            @Override
+            public ActiveResult get() {
+                if (isFromPersistenceXml) {
+                    // We don't support inactive persistence units when they are defined through persistence.xml.
```
Comment (marko-bekhta) [inline extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/HibernateOrmRecorder.java:126]: maybe it's worth pointing to something that explains why we don't ?

File: extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmCdiProcessor.java [hunk 9]
```diff
@@ -382,94 +383,91 @@ private static <T> ExtendedBeanConfigurator createSyntheticBean(String persisten
...
     private void produceFactoryDependentBeans(
             BuildProducer<SyntheticBeanBuildItem> producer,
             HibernateOrmRecorder recorder,
-            String persistenceUnitName,
-            boolean isDefaultPU,
-            boolean isNamedPU,
-            AnnotationInstance sessionFactoryQualifier) {
+            PersistenceUnitReference puRef) {
+        AnnotationInstance sessionFactoryQualifier;
+        if (PersistenceUnitUtil.isDefaultPersistenceUnit(puRef.persistenceUnitName)) {
```
Comment (marko-bekhta) [inline extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmCdiProcessor.java:420]: do we need `puRef.forceAllQualifiers` or something similar here as above in the `createSyntheticBean(..)`?

File: extensions/hibernate-orm/deployment/src/test/java/io/quarkus/hibernate/orm/config/ConfigActiveFalseStaticInjectionTest.java [hunk 10]
```diff
@@ -19,18 +19,23 @@ public class ConfigActiveFalseStaticInjectionTest {
...
+                            "Persistence unit '<default>' was deactivated through configuration properties",
+                            "To avoid this exception while keeping the bean inactive", // Message from Arc with generic hints
+                            "To activate the persistence unit, set configuration property 'quarkus.hibernate-orm.active'"
+                                    + " to 'true' and configure datasource '<default>'.",
+                            "Refer to https://quarkus.io/guides/datasource for guidance.",
+                            "This bean is injected into",
+                            MyBean.class.getName() + "#session"));
 
     @Inject
     MyBean myBean;
```
Comment (marko-bekhta) [inline extensions/hibernate-orm/deployment/src/test/java/io/quarkus/hibernate/orm/config/ConfigActiveFalseStaticInjectionTest.java]: since the test does not need the reference anymore, if we'd add the bean to the jar would the test be fine ? 🙈

File: extensions/hibernate-reactive/deployment/src/test/java/io/quarkus/hibernate/reactive/config/NoConfigNoEntitiesTest.java [hunk 11]
```diff
@@ -18,7 +18,7 @@ public class NoConfigNoEntitiesTest {
             .overrideConfigKey("quarkus.devservices.enabled", "false");
 
     // When having no entities, no configuration, no datasource,
-    // as long as the Hibernate Reactive beans are not injected anywhere,
+    // as long as the Hibernate ORM beans are not injected anywhere,
```
Comment (marko-bekhta) [inline extensions/hibernate-reactive/deployment/src/test/java/io/quarkus/hibernate/reactive/config/NoConfigNoEntitiesTest.java:21]: this one seems to be for reactive though 🙈 🙈

File: extensions/hibernate-search-orm-elasticsearch/deployment/src/main/java/io/quarkus/hibernate/search/orm/elasticsearch/deployment/HibernateSearchElasticsearchCdiProcessor.java [hunk 12]
```diff
@@ -33,33 +34,37 @@ void generateSearchBeans(HibernateSearchElasticsearchRecorder recorder,
...
+                .setRuntimeInit()
+                // Note persistence units _actually_ get started a bit earlier, each in its own thread. See JPAConfig#startAll.
+                // This startup() call is only necessary in order to trigger Arc's usage checks (fail startup if bean injected when inactive).
+                .startup()
+                .checkActive(checkActiveSupplier);
 
-        if (isDefaultPersistenceUnit) {
+        if (PersistenceUnitUtil.isDefaultPersistenceUnit(persistenceUnitName)) {
             configurator.addQualifier(Default.class);
         }
```
Comment (marko-bekhta) [inline extensions/hibernate-search-orm-elasticsearch/deployment/src/main/java/io/quarkus/hibernate/search/orm/elasticsearch/deployment/HibernateSearchElasticsearchCdiProcessor.java:69]: for Search we always add the named qualifiers (just below) and for ORM those seem to be conditional, I wonder if we should be consistent 🤔

File: extensions/hibernate-search-orm-elasticsearch/deployment/src/test/java/io/quarkus/hibernate/search/orm/elasticsearch/test/configuration/ConfigOrmActiveFalseAndIndexedEntityTest.java (hunk 2 above)
Comment (marko-bekhta) [reply extensions/hibernate-search-orm-elasticsearch/deployment/src/test/java/io/quarkus/hibernate/search/orm/elasticsearch/test/configuration/ConfigOrmActiveFalseAndIndexedEntityTest.java]: btw do we want to fetch some search session or something to see that it also got deactivated ?

File: extensions/hibernate-reactive/deployment/pom.xml [hunk 13]
```diff
@@ -137,6 +137,14 @@
...
                 </configuration>
             </plugin>
+            <plugin>
+                <groupId>org.apache.maven.plugins</groupId>
+                <artifactId>maven-compiler-plugin</artifactId>
+                <configuration>
+                    <source>8</source>
+                    <target>8</target>
+                </configuration>
+            </plugin>
```
Comment (marko-bekhta) [inline extensions/hibernate-reactive/deployment/pom.xml]: just checking .. if this was intentional 🙈

**Review by marko-bekhta — COMMENTED** [review]
Thanks! Looks nice 😃 🎉 

I had some questions, but feel free to ignore those 😄

File: extensions/hibernate-search-orm-elasticsearch/deployment/src/test/java/io/quarkus/hibernate/search/orm/elasticsearch/test/configuration/ConfigOrmActiveFalseAndIndexedEntityTest.java (hunk 2 above)
Comment (yrodiere) [reply extensions/hibernate-search-orm-elasticsearch/deployment/src/test/java/io/quarkus/hibernate/search/orm/elasticsearch/test/configuration/ConfigOrmActiveFalseAndIndexedEntityTest.java]: Yes I apparently forgot, good catch.

File: extensions/hibernate-reactive/deployment/src/test/java/io/quarkus/hibernate/reactive/config/datasource/MultiplePUAsAlternativesWithBeanProducerTest.java (hunk 3 above)
Comment (yrodiere) [reply extensions/hibernate-reactive/deployment/src/test/java/io/quarkus/hibernate/reactive/config/datasource/MultiplePUAsAlternativesWithBeanProducerTest.java:65]: Because I hate to have to go to a different file to see which configuration properties are set in a test...

Eventually I'd like to _only_ use `application-postgres-reactive-url-only.properties` in every test, but I didn't want to add a refactoring to this (already large and relatively confusing) changeset.

Comment (yrodiere) [reply extensions/hibernate-reactive/deployment/src/test/java/io/quarkus/hibernate/reactive/config/datasource/MultiplePUAsAlternativesWithBeanProducerTest.java:65]: Alternatively, once we use dev services, `application-postgres-reactive-url-only.properties` won't even be needed.

File: docs/src/main/asciidoc/datasource.adoc (hunk 4 above)
Comment (yrodiere) [reply docs/src/main/asciidoc/datasource.adoc:457]: The ORM extension will not deactivate the PU when the datasource is inactive.

I initially wanted that, but changed my mind considering the risk of not detecting missing configuration: for example with Panache you might not be injecting the `Session` anywhere, so Quarkus won't fail on startup if a PU is inactive, even if you have entities all over the place, and it'll fail on the first request to the DB. Not great.

File: docs/src/main/asciidoc/hibernate-orm.adoc (hunk 5 above)
Comment (yrodiere) [reply docs/src/main/asciidoc/hibernate-orm.adoc]: Good catch. It's a pre-existing mistake in the datasource guide, too. Will fix.

File: docs/src/main/asciidoc/hibernate-orm.adoc (hunk 7 above)
Comment (yrodiere) [reply docs/src/main/asciidoc/hibernate-orm.adoc:606]: Good catch.

File: docs/src/main/asciidoc/hibernate-orm.adoc (hunk 6 above)
Comment (yrodiere) [reply docs/src/main/asciidoc/hibernate-orm.adoc:558]: I added a small bit of documentation. Should be enough for now?

File: extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/HibernateOrmRecorder.java (hunk 8 above)
Comment (yrodiere) [reply extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/HibernateOrmRecorder.java:126]: I added a link to the documentation.

File: extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmCdiProcessor.java (hunk 9 above)
Comment (yrodiere) [reply extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmCdiProcessor.java:420]: This qualifier is the one used to _retrieve_ the session factory when creating derived beans. This qualifier is enough.
The derived beans will also have "all qualifiers forced" if necessary.

File: extensions/hibernate-orm/deployment/src/test/java/io/quarkus/hibernate/orm/config/ConfigActiveFalseStaticInjectionTest.java (hunk 10 above)
Comment (yrodiere) [reply extensions/hibernate-orm/deployment/src/test/java/io/quarkus/hibernate/orm/config/ConfigActiveFalseStaticInjectionTest.java]: The bean is always in the JAR, as evidenced by the statup failure that references its name.
In general, inner classes in a test are implicitly added to the JAR.

File: extensions/hibernate-search-orm-elasticsearch/deployment/src/main/java/io/quarkus/hibernate/search/orm/elasticsearch/deployment/HibernateSearchElasticsearchCdiProcessor.java (hunk 12 above)
Comment (yrodiere) [reply extensions/hibernate-search-orm-elasticsearch/deployment/src/main/java/io/quarkus/hibernate/search/orm/elasticsearch/deployment/HibernateSearchElasticsearchCdiProcessor.java:69]: I would like to, and if so I'd change what we do in ORM, but that seems out of scope. Want to create an issue?

File: extensions/hibernate-reactive/deployment/pom.xml (hunk 13 above)
Comment (yrodiere) [reply extensions/hibernate-reactive/deployment/pom.xml]: Absolutely not, thanks for the heads-up. Removed.

**Review by yrodiere — COMMENTED** [review]
I addressed your comments @marko-bekhta , thank you!

**Comment by yrodiere** [comment]
We're good to go, I just need an approval from someone with push access... @Sanne would you please do that? @marko-bekhta reviewed already and (I think) is happy :)

**Review by marko-bekhta — APPROVED** [review]

**Comment by lucamolteni** [comment]
> Hey @marko-bekhta or @lucamolteni can I please ask one of you review this? If you skip the first commit it's _almost_ a reasonable amount of code (and the vast majority is just tests that look very similar).
> 
> EDIT: No need for _both_ of you to review of course :)


Impressive changes thank you

**Review by Sanne — APPROVED** [review]

**Comment by Sanne** [comment]
> We're good to go, I just need an approval from someone with push access... @Sanne would you please do that?

Done. Let's propose expanding the push access team with them both?

**Comment by yrodiere** [comment]
Thank you.

> Done. Let's propose expanding the push access team with them both?

I'll try again. Last time I did it didn't go well due to missing official processes for that and/or the Commonhaus transfer. Let's hope that's settled.
