### PR TITLE
WebSockets Next: fix the server autoPing timer

### LINKED ISSUE #47235: Logs full of "Unable to send auto-ping for WebSocket connection. WebSocket is closed"
### Describe the bug

We're using websockets-next with `quarkus.websockets-next.server.auto-ping-interval=10s`.
And sometimes it starts spamming logs with 	
`Unable to send auto-ping for WebSocket connection [endpointId=..., path=/api/v1/..., id=...]: io.vertx.core.impl.NoStackTraceThrowable: WebSocket is closed`

It seems that the timer sometimes is not canceled on connection close. It's even possible that it's even worse and no close callbacks are called or there's some connection leak.
I have logs on each type of callbacks, and I only see `@OnOpen` and then `WebSocket is closed` is right after that. No `@OnError` or `@OnClose`

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mkouba**
- only send the ping if connection is open
- make sure we always try to cancel the timer
- fixes #47235

### CODE REVIEW

File: extensions/websockets-next/runtime/src/main/java/io/quarkus/websockets/next/runtime/Endpoints.java [hunk 1]
```diff
@@ -220,7 +220,12 @@ public void handle(Void event) {
             timerId = vertx.setPeriodic(autoPingInterval.get().toMillis(), new Handler<Long>() {
                 @Override
                 public void handle(Long timerId) {
-                    connection.sendAutoPing();
+                    if (connection.isOpen()) {
+                        connection.sendAutoPing();
+                    } else {
+                        LOG.debugf("Try to cancel the autoPing timer for a closed connection: %s", connection.id());
+                        vertx.cancelTimer(timerId);
```
Comment (mkouba) [inline extensions/websockets-next/runtime/src/main/java/io/quarkus/websockets/next/runtime/Endpoints.java:227]: Is it ok to cancel the timer from within the callback? @vietj

Comment (gsmet) [reply extensions/websockets-next/runtime/src/main/java/io/quarkus/websockets/next/runtime/Endpoints.java:227]: I think this is important as my understanding is that you will have the connection closed before executing the code below that cancels the timer?

Or am I mistaken?

**Review by gsmet — APPROVED** [review]
I will let @vietj answer the question you asked but the code looks good and in line with what I had in mind.

I added a small comment though.

File: extensions/websockets-next/runtime/src/main/java/io/quarkus/websockets/next/runtime/Endpoints.java (hunk 1 above)
Comment (michalvavrik) [reply extensions/websockets-next/runtime/src/main/java/io/quarkus/websockets/next/runtime/Endpoints.java:227]: FWIW we (or at least I) did it in some OIDC stuff and we didn't detect issues.

**Review by michalvavrik — APPROVED** [review]
LGTM

File: extensions/websockets-next/runtime/src/main/java/io/quarkus/websockets/next/runtime/Endpoints.java (hunk 1 above)
Comment (mkouba) [reply extensions/websockets-next/runtime/src/main/java/io/quarkus/websockets/next/runtime/Endpoints.java:227]: > I think this is important as my understanding is that you will have the connection closed before executing the code below that cancels the timer?
> 
> Or am I mistaken?

Yes, when the timer is invoked and the connection is closed then we cancel timer completely.

**Comment by mkouba** [comment]
> I will let @vietj answer the question you asked but the code looks good and in line with what I had in mind.
> 
> I added a small comment though.

I'm going to merge this PR and if we get some negative feedback from @vietj we'll create a follow-up.

File: extensions/websockets-next/runtime/src/main/java/io/quarkus/websockets/next/runtime/Endpoints.java (hunk 1 above)
Comment (vietj) [reply extensions/websockets-next/runtime/src/main/java/io/quarkus/websockets/next/runtime/Endpoints.java:227]: timers can be canceled any time from any thread
