### PR TITLE
Fix lambda http base64 encoding and binary types

### LINKED ISSUE #18356: quarkus-amazon-lambda-rest:  wrong base64 encoding and unable to add binary type by configuration
## Describe the bug

Quarkus version: 2.0.0
Environment:  AWS ALB -> Quarkus

When downloading binary content from ALB you will receive a HTTP 502. 
See also: https://github.com/awslabs/aws-serverless-java-container/issues/339

In the following class:

_https://github.com/quarkusio/quarkus/blob/main/extensions/amazon-lambda-rest/runtime/src/main/java/io/quarkus/amazon/lambda/http/LambdaHttpHandler.java_

the body is encoded using the MimeEncoder:
`responseBuilder.setBody(Base64.getMimeEncoder().encodeToString(baos.toByteArray()));`

This should be changed to
`
responseBuilder.setBody(Base64.getEncoder().encodeToString(baos.toByteArray()));`

Don't forget the other way around!

Also it would be very nice to be able to add binary content by a config property.

 Now i have to do it myself by using the following code:

```
    //also base64 encode http application/pdf content
    LambdaContainerHandler.getContainerConfig().addBinaryContentTypes(.........);    
    //default charset should be UTF-8
    LambdaContainerHandler.getContainerConfig().setDefaultContentCharset(StandardCharsets.UTF_8.name());
```

### PR DESCRIPTION
**Pull request by patriot1burke**
Lambda http/rest plugins were not correctly base64 encoding binary types.  Also, treat everything as a binary type unless it is "text", xml", "json", or "yaml".

### CODE REVIEW

File: extensions/amazon-lambda-http/runtime/src/main/java/io/quarkus/amazon/lambda/http/LambdaHttpHandler.java [hunk 1]
```diff
@@ -213,23 +211,14 @@ private ByteArrayOutputStream createByteStream() {
...
-    static {
-        binaryTypes.add("application/octet-stream");
-        binaryTypes.add("image/jpeg");
-        binaryTypes.add("image/png");
-        binaryTypes.add("image/gif");
-    }
-
     private boolean isBinary(String contentType) {
         if (contentType != null) {
+            String ct = contentType.toLowerCase();
```
Comment (kenyee) [inline extensions/amazon-lambda-http/runtime/src/main/java/io/quarkus/amazon/lambda/http/LambdaHttpHandler.java:216]: variable name could be better... maybe lowercaseContentType?

File: extensions/amazon-lambda-rest/runtime/src/main/java/io/quarkus/amazon/lambda/http/LambdaHttpHandler.java [hunk 2]
```diff
@@ -221,14 +220,13 @@ private ByteArrayOutputStream createByteStream() {
...
         if (contentType != null) {
+            String ct = contentType.toLowerCase();
             int index = contentType.indexOf(';');
             if (index >= 0) {
-                return LambdaContainerHandler.getContainerConfig().isBinaryContentType(contentType.substring(0, index));
-            } else {
-                return LambdaContainerHandler.getContainerConfig().isBinaryContentType(contentType);
+                ct = contentType.substring(0, index);
             }
+            return !(ct.startsWith("text") || ct.contains("json") || ct.contains("xml") || ct.contains("yaml"));
```
Comment (kenyee) [inline extensions/amazon-lambda-rest/runtime/src/main/java/io/quarkus/amazon/lambda/http/LambdaHttpHandler.java:228]: this comparison is repeated above..should be a util method?

**Review by kenyee — APPROVED** [review]

File: extensions/amazon-lambda-http/runtime/src/main/java/io/quarkus/amazon/lambda/http/LambdaHttpHandler.java (hunk 1 above)
Comment (gastaldi) [inline extensions/amazon-lambda-http/runtime/src/main/java/io/quarkus/amazon/lambda/http/LambdaHttpHandler.java:216]:
```suggestion
            String ct = contentType.toLowerCase(Locale.ROOT);
```

File: extensions/amazon-lambda-rest/runtime/src/main/java/io/quarkus/amazon/lambda/http/LambdaHttpHandler.java [hunk 3]
```diff
@@ -221,14 +220,13 @@ private ByteArrayOutputStream createByteStream() {
 
     private boolean isBinary(String contentType) {
         if (contentType != null) {
+            String ct = contentType.toLowerCase();
```
Comment (gastaldi) [inline extensions/amazon-lambda-rest/runtime/src/main/java/io/quarkus/amazon/lambda/http/LambdaHttpHandler.java:223]:
```suggestion
            String ct = contentType.toLowerCase(Locale.ROOT);
```

File: extensions/amazon-lambda-http/runtime/src/main/java/io/quarkus/amazon/lambda/http/LambdaHttpHandler.java [hunk 4]
```diff
@@ -213,23 +212,15 @@ private ByteArrayOutputStream createByteStream() {
...
         if (contentType != null) {
+            String ct = contentType;
             int index = contentType.indexOf(';');
             if (index >= 0) {
-                return binaryTypes.contains(contentType.substring(0, index));
-            } else {
-                return binaryTypes.contains(contentType);
+                ct = contentType.substring(0, index);
             }
+            ct.toLowerCase(Locale.ROOT);
```
Comment (gastaldi) [inline extensions/amazon-lambda-http/runtime/src/main/java/io/quarkus/amazon/lambda/http/LambdaHttpHandler.java:222]: You need to assign the result of this method call to `ct`

**Review by cescoffier — APPROVED** [review]
