### PR TITLE
Fixes #3949

### LINKED ISSUE #3949: Unable to map exceptions other than `Exception` and `ApplicationException`
**Describe the bug**
I am trying to adjust the response for errors provided by quarkus extensions but it does not seem to be possible to capture those in ExceptionMappers.
Also, this issue (https://github.com/quarkusio/quarkus/issues/3253) mentions that `WebApplicationExceptions` works, but that's not the case for me. So I cannot easily capture javax.ws.rs.core.Response exceptions easily.

**Expected behavior**
For example, I would expect to be able to capture hibernate exceptions with either a `ExceptionMapper<PersistenceException>` or `ExceptionMapper<RollbackException>`.

**Actual behavior**

For example, violating a database constraint produces the stacktrace:
```
RuntimeException 
-> javax.transaction.RollBackException 
-> javax.persistence.PersistenceException 
-> org.hibernate.exception.ConstraintViolationException
```
But I am only able to capture it with a `ExceptionMapper<Exception>`.

**To Reproduce**
1. Build a project with `hibernate-orm`
2. Create a service to insert the following entity twice.

```
@Entity
@Table(name = "DEMO")
@Data
public class Demo {
	@Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    private Long id;

    @Column(unique = true)
    private String name;
}
```

3. Add the following ExceptionMappers to the project

```java
@Slf4j
@Provider
public class PersistenceExceptionMapper implements ExceptionMapper<PersistenceException> {

    @Override
    public Response toResponse(PersistenceException exception) {
        logger.error("PersistenceException error", exception);
        return Response.status(500)
            .entity(Json.createObjectBuilder()
                .add("message", exception.getMessage())
                .build())
            .build();
    }

}
```

```java
@Slf4j
@Provider
public class RollbackExceptionMapper implements ExceptionMapper<RollbackException> {

    @Override
    public Response toResponse(RollbackException exception) {
        logger.error("RollbackException error", exception);
        return Response.status(500)
            .entity(Json.createObjectBuilder()
                .add("message", exception.getMessage())
                .build())
            .build();
    }

}
```

You will see none of them triggers and the response is a HTML, if in DEV mode.

**Configuration**
N/A

**Screenshots**
N/A

**Environment (please complete the following information):**
Quarkus vers: 0.20.1 & 0.20.2
Quarkus extensions: [agroal, cdi, hibernate-orm, hibernate-validator, jdbc-postgresql, narayana-jta, resteasy, resteasy-jsonb, security, smallrye-jwt]
Maven & Java:
```
Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T21:00:29+02:00)
Maven home: /home/---/.sdkman/candidates/maven/current
Java version: 1.8.0_222, vendor: Oracle Corporation, runtime: /home/---/.sdkman/candidates/java/19.2.0-grl/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.1.21-1-manjaro", arch: "amd64", family: "unix"
```

**Additional context**
(Add any other context about the problem here.)

### PR DESCRIPTION
**Pull request by stuartwdouglas**
If a checked exception is thrown from an interceptor allow RESTeasy
exception mappers to unwrap it.

### CODE REVIEW

File: independent-projects/arc/runtime/src/main/java/io/quarkus/arc/ArcUndeclaredThrowableException.java [hunk 1]
```diff
@@ -0,0 +1,28 @@
+package io.quarkus.arc;
+
+/**
+ * Exception that is thrown from generated arc classes if a checked exception cannot be propagated
+ */
+public class ArcUndeclaredThrowableException extends RuntimeException {
+
+    public ArcUndeclaredThrowableException(Throwable cause) {
```
Comment (mkouba) [inline independent-projects/arc/runtime/src/main/java/io/quarkus/arc/ArcUndeclaredThrowableException.java]: I'm wondering if the name shouldn't be more general, something like `ArcException` so that we could use it for similar use cases. Note that we have such exception in Weld too: `org.jboss.weld.exceptions.WeldException`.

**Review by gsmet — APPROVED** [review]
@mkouba it looks good to me but I let you merge it as it's ArC-related.

**Review by mkouba — APPROVED** [review]
Ok. Makes sense then.
