### PR TITLE
Only create the Reactive PoolProducers and health check beans if we produce a pool

### LINKED ISSUE #12043: Unsatisfied dependency for type io.vertx.db2client.DB2Pool and qualifiers with Quarkus master, works with 1.8.0.Final
I see Unsatisfied dependency for type io.vertx.db2client.DB2Pool and qualifiers with Quarkus master (6588419c63) when running daily GH CI check on https://github.com/quarkus-qe/beefy-scenarios. Works well with 1.8.0.Final.

```java
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type io.vertx.db2client.DB2Pool and qualifiers [@Default]
	- java member: io.quarkus.reactive.db2.client.runtime.DB2PoolProducer#db2Pool
	- declared on CLASS bean [types=[java.lang.Object, io.quarkus.reactive.db2.client.runtime.DB2PoolProducer], qualifiers=[@Default, @Any], target=io.quarkus.reactive.db2.client.runtime.DB2PoolProducer]
	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1018)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:238)
	at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:122)
	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:393)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:936)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
Caused by: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type io.vertx.db2client.DB2Pool and qualifiers [@Default]
	- java member: io.quarkus.reactive.db2.client.runtime.DB2PoolProducer#db2Pool
	- declared on CLASS bean [types=[java.lang.Object, io.quarkus.reactive.db2.client.runtime.DB2PoolProducer], qualifiers=[@Default, @Any], target=io.quarkus.reactive.db2.client.runtime.DB2PoolProducer]
	at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:504)
	at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:363)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:230)
	... 14 more

```

Reproducer (expecting Quarkus master was built beforehand):
```bash
git clone https://github.com/quarkus-qe/beefy-scenarios.git
cd beefy-scenarios
mvn clean verify -pl 002-quarkus-all-extensions  
```

Running with Quarkus 1.8.0.Final works fine (`mvn clean verify -pl 002-quarkus-all-extensions/ -Dquarkus.platform.version=1.8.0.Final -Dquarkus-plugin.version=1.8.0.Final`).

### PR DESCRIPTION
**Pull request by gsmet**
Fixes #12043

/cc @rsvoboda @geoand

### CODE REVIEW

File: extensions/reactive-db2-client/deployment/src/main/java/io/quarkus/reactive/db2/client/deployment/ReactiveDB2ClientProcessor.java [hunk 1]
```diff
@@ -30,9 +31,24 @@
...
+            DataSourcesBuildTimeConfig dataSourcesBuildTimeConfig,
+            DataSourceReactiveBuildTimeConfig dataSourceReactiveBuildTimeConfig) {
+        if (!createPool(dataSourcesBuildTimeConfig, dataSourceReactiveBuildTimeConfig)) {
+            return;
+        }
+
+        additionalBeans.produce(new AdditionalBeanBuildItem.Builder()
+                .addBeanClass(DB2PoolProducer.class)
+                .setUnremovable()
+                .setDefaultScope(DotNames.APPLICATION_SCOPED)
```
Comment (geoand) [inline extensions/reactive-db2-client/deployment/src/main/java/io/quarkus/reactive/db2/client/deployment/ReactiveDB2ClientProcessor.java:50]: Is this the default when no scope is used?

File: extensions/reactive-db2-client/deployment/src/main/java/io/quarkus/reactive/db2/client/deployment/ReactiveDB2ClientProcessor.java [hunk 2]
```diff
@@ -82,8 +93,30 @@ ServiceStartBuildItem build(BuildProducer<FeatureBuildItem> feature,
...
+        if (!createPool(dataSourcesBuildTimeConfig, dataSourceReactiveBuildTimeConfig)) {
+            return;
+        }
+
+        healthChecks
+                .produce(new HealthBuildItem("io.quarkus.reactive.db2.client.runtime.health.ReactiveDB2DataSourceHealthCheck",
+                        dataSourcesBuildTimeConfig.healthEnabled));
+    }
+
+    private static boolean createPool(DataSourcesBuildTimeConfig dataSourcesBuildTimeConfig,
```
Comment (geoand) [inline extensions/reactive-db2-client/deployment/src/main/java/io/quarkus/reactive/db2/client/deployment/ReactiveDB2ClientProcessor.java:109]: Can we have a comment on what the rationale is behind this?

**Review by geoand — COMMENTED** [review]
Looks good but added a comment about explaining the rationale of one of the creation of the pool.

Also, how hard would it be to add a test similar to the original issue?

File: extensions/reactive-db2-client/deployment/src/main/java/io/quarkus/reactive/db2/client/deployment/ReactiveDB2ClientProcessor.java (hunk 1 above)
Comment (gsmet) [reply extensions/reactive-db2-client/deployment/src/main/java/io/quarkus/reactive/db2/client/deployment/ReactiveDB2ClientProcessor.java:50]: Yeah, well, I don't know but if the default changes one day, at least it will be OK.

File: extensions/reactive-db2-client/deployment/src/main/java/io/quarkus/reactive/db2/client/deployment/ReactiveDB2ClientProcessor.java (hunk 2 above)
Comment (gsmet) [reply extensions/reactive-db2-client/deployment/src/main/java/io/quarkus/reactive/db2/client/deployment/ReactiveDB2ClientProcessor.java:109]: It looks simple enough to me? It just checks the config to know if we should create the pool.

File: extensions/reactive-db2-client/deployment/src/main/java/io/quarkus/reactive/db2/client/deployment/ReactiveDB2ClientProcessor.java (hunk 1 above)
Comment (geoand) [reply extensions/reactive-db2-client/deployment/src/main/java/io/quarkus/reactive/db2/client/deployment/ReactiveDB2ClientProcessor.java:50]: But does this change, change what it **is** today?

File: extensions/reactive-db2-client/deployment/src/main/java/io/quarkus/reactive/db2/client/deployment/ReactiveDB2ClientProcessor.java (hunk 2 above)
Comment (geoand) [reply extensions/reactive-db2-client/deployment/src/main/java/io/quarkus/reactive/db2/client/deployment/ReactiveDB2ClientProcessor.java:109]: What I don't get is why, not how it's done. Maybe it's just because I have no knowledge of this part of the code. Feel free to ignore

Comment (gsmet) [reply extensions/reactive-db2-client/deployment/src/main/java/io/quarkus/reactive/db2/client/deployment/ReactiveDB2ClientProcessor.java:109]: Yeah. The why is that you don't want to create the pool if it's not configured or targets another database type than the one supported by this extension :).

Keep in mind that the idea is to support multiple datasources here too at some point so we need to support the case where we have multiple reactive client extensions at the same time.

It's probably going to be more obvious once we add support for multiple datasources there too.

I wouldn't mind an approval so that I can get this one in and fix @rsvoboda 's issue :).

**Review by geoand — APPROVED** [review]

**Review by rsvoboda — APPROVED** [review]

**Comment by rsvoboda** [comment]
I have verified that the issue I reported is gone with this fix.

File: extensions/reactive-db2-client/deployment/src/main/java/io/quarkus/reactive/db2/client/deployment/ReactiveDB2ClientProcessor.java (hunk 1 above)
Comment (gsmet) [reply extensions/reactive-db2-client/deployment/src/main/java/io/quarkus/reactive/db2/client/deployment/ReactiveDB2ClientProcessor.java:50]: Ah OK, I misunderstood your question. Yes, exactly.

I always prefer to remove the scope annotation from the additional beans in case at some point we index the extensions.

Comment (mkouba) [reply extensions/reactive-db2-client/deployment/src/main/java/io/quarkus/reactive/db2/client/deployment/ReactiveDB2ClientProcessor.java:50]: > I always prefer to remove the scope annotation from the additional beans in case at some point we index the extensions.

That would not help - a class that contains a producer is automatically picked up. If a bean should be `@ApplicationScoped` then the class should IMO contain the annotation. The primary purpose of `AdditionalBeanBuildItem` is to register a class for discovery (i.e. take it as it is). AFAIR the ``AdditionalBeanBuildItem``s default scope was intended for the cases where we need to change the scope for a class that we don't control.

NOTE: In this particular case we should consider making the bean `@Dependent` as the produced `io.vertx.mutiny.db2client.DB2Pool` is singleton, i.e. the producer method is only called once, i.e. this should work fine...

```java
@Dependent
public class DB2PoolProducer {

    /**
     * @return the <em>mutiny</em> DB2 Pool instance. The instance is created lazily.
     */
    @Singleton
    @Produces
    public io.vertx.mutiny.db2client.DB2Pool mutinyDB2Pool(DB2Pool db2Pool) {
        return io.vertx.mutiny.db2client.DB2Pool.newInstance(db2Pool);
    }
}
```

Comment (mkouba) [reply extensions/reactive-db2-client/deployment/src/main/java/io/quarkus/reactive/db2/client/deployment/ReactiveDB2ClientProcessor.java:50]: Also ``AdditionalBeanBuildItem``s default scope requires unnecessary transformation and a special "stereotype hack". So it's always better to avoid it (if possible)...

Comment (mkouba) [reply extensions/reactive-db2-client/deployment/src/main/java/io/quarkus/reactive/db2/client/deployment/ReactiveDB2ClientProcessor.java:50]: @gsmet @geoand ^

Comment (geoand) [reply extensions/reactive-db2-client/deployment/src/main/java/io/quarkus/reactive/db2/client/deployment/ReactiveDB2ClientProcessor.java:50]: Good to know @mkouba, thanks!
