### PR TITLE
Propagate OpenTelemetry context to Blocking gRPC services

### LINKED ISSUE #24395: gRPC service throw warning when using @Blocking and OpenTelemetry gRPC interceptor
### Describe the bug

Calling a gRPC method with @Blocking annotation with gRPC interceptor produces warnings when enabling [io.opentelemetry.instrumentation:opentelemetry-grpc-1.6:1.10.0-alpha](https://mvnrepository.com/artifact/io.opentelemetry.instrumentation/opentelemetry-grpc-1.6/1.10.0-alpha) and io.quarkus:quarkus-opentelemetry-exporter-otlp.

It does not affect gRPC methods without @Blocking annotation.

### Expected behavior

no warning

### Actual behavior

a warning `Context in storage not the expected context, Scope.close was not called correctly`

### How to Reproduce?

1. Clone https://github.com/XSAM/quarkus-issue-24395-reproducer
2. Checkout https://github.com/XSAM/quarkus-issue-24395-reproducer/commit/a28bc52d28720c89303e2bce4b52ca848bb6c74f
3. Run `mvn test` to see the warning

### Output of `uname -a` or `ver`

21.2.0

### Output of `java -version`

openjdk version "17.0.2" 2022-01-18 OpenJDK Runtime Environment (build 17.0.2+8-86) OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.7.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.3.3

### Additional information

Related to https://github.com/quarkusio/quarkus/issues/23805

### PR DESCRIPTION
**Pull request by radcortez**
- Fixes #24395

### CODE REVIEW

File: extensions/opentelemetry/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/grpc/GrpcTracingServerInterceptor.java [hunk 1]
```diff
@@ -99,65 +98,87 @@ public String get(final GrpcRequest carrier, final String key) {
...
         }
 
         @Override
         public void onHalfClose() {
-            try (Scope ignored = spanContext.makeCurrent()) {
+            try {
                 super.onHalfClose();
             } catch (Exception e) {
-                instrumenter.end(spanContext, grpcRequest, null, e);
+                try (scope) {
```
Comment (brunobat) [inline extensions/opentelemetry/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/grpc/GrpcTracingServerInterceptor.java:121]: this is just to close the scope on exit right?

File: extensions/opentelemetry/opentelemetry/deployment/src/test/java/io/quarkus/opentelemetry/deployment/GrpcOpenTelemetryTest.java [hunk 2]
```diff
@@ -237,10 +239,57 @@ void stream() {
         assertEquals(server.getTraceId(), client.getTraceId());
     }
 
+    @Test
+    void streamingBlocking() {
+        Multi<Item> request = Multi.createFrom().items(item("Goku"), item("Vegeta"), item("Piccolo"), item("Beerus"),
+                item("Whis"));
+        Multi<Item> response = streamingStub.pipeBlocking(request);
```
Comment (brunobat) [inline extensions/opentelemetry/opentelemetry/deployment/src/test/java/io/quarkus/opentelemetry/deployment/GrpcOpenTelemetryTest.java:246]: This is basically the same as previous streaming() test, not sure what you are resting here...

Comment (radcortez) [reply extensions/opentelemetry/opentelemetry/deployment/src/test/java/io/quarkus/opentelemetry/deployment/GrpcOpenTelemetryTest.java:246]: It uses the `pipeBlocking` method, which has a `@Blocking` annotation. This will force gRPC to block, and the blocking code will be executed in another thread, so we lose the context. We need to also propagate the `Scope` with the gRPC invocation to ensure you are in the right OTel Context.

File: extensions/opentelemetry/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/grpc/GrpcTracingServerInterceptor.java (hunk 1 above)
Comment (radcortez) [reply extensions/opentelemetry/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/grpc/GrpcTracingServerInterceptor.java:121]: Yes, we need to close to scope on every possible exit.

File: extensions/opentelemetry/opentelemetry/deployment/src/test/java/io/quarkus/opentelemetry/deployment/GrpcOpenTelemetryTest.java (hunk 2 above)
Comment (brunobat) [reply extensions/opentelemetry/opentelemetry/deployment/src/test/java/io/quarkus/opentelemetry/deployment/GrpcOpenTelemetryTest.java:246]: got it, thanks!

**Review by brunobat — APPROVED** [review]
Looks good to me. Thanks @radcortez .
