### PR TITLE
Build and Runtime fixed properties only from default and built step sources

### LINKED ISSUE #8145: Config sources are loaded and invoked multiple times
**Describe the bug**
We are trying to implement custom `org.eclipse.microprofile.config.spi.ConfigSource` implementation for AWS Systems Manager Parameter Store(SSM)

Everything works well, but we noticed that configSources are created and invoked 3 times and 3 

calls are performed to SSM accordingly(first time during the maven build phase).

We use serverless architecture in AWS with native images and as you can

imagine, multiple calls to the external system are not the desired behavior for us because they affect startup time. 

**Expected behavior**
Config sources should be loaded only once

**Actual behavior**
Config sources are loaded multiple times(in our case 3 times)

### PR DESCRIPTION
**Pull request by radcortez**
- Fixes #8145

The `Config` instance for static init will only add the `BuildTimeRunTimeDefaultValuesConfigSource`, the default sources from `Config` (system, env and properties) and registered sources with `BuildTimeRunTimeDefaultValuesConfigSource`. This will prevent user discovered sources to be doubled initialised (once for static init and another for run).

The downside of this, is that some libraries that require static init (like RESTEasy) require their sources to be registered with the build step to work properly, so extension developers will need to keep this in mind.

We shouldn't require the default sources of (system, env and properties), but some extensions are relying on specific configuration that are not in the quarkus namespace, so these are not recorded as defaults and they are not available in the `BuildTimeRunTimeDefaultValuesConfigSource`.  We should probably review them. I ended up doing a minor refactor to the Tracing extension because of this, but there are others (SR Messaging).

ConfigRoot objects values that may be overridden by the system, env and properties (when they should only use the `BuildTimeRunTimeDefaultValuesConfigSource`). This needs to be fixed.

Overall, this seems to solve the original issue, but I'm not completely sure if I'm happy with the end result.

### CODE REVIEW

**Comment by lburgazzoli** [comment]
@gsmet can we get some review on this PR ?

**Comment by gsmet** [comment]
@geoand is it something you understand? I'm not really sure I understand all the implications of this PR.

**Comment by geoand** [comment]
Let me take a look

File: extensions/resteasy-classic/resteasy/deployment/src/test/java/io/quarkus/resteasy/test/ProviderConfigInjectionTest.java [hunk 1]
```diff
@@ -47,11 +48,11 @@ public String getFoo() {
     public static class FooProvider implements ContextResolver<String> {
 
         @ConfigProperty(name = "foo")
-        String foo;
+        Instance<String> foo;
```
Comment (geoand) [inline extensions/resteasy-classic/resteasy/deployment/src/test/java/io/quarkus/resteasy/test/ProviderConfigInjectionTest.java:51]: Is this necessary? I know we tell people to do it, but does it not work otherwise with this PR?

**Comment by geoand** [comment]
I had a look (and also read the initial issue to get the context) and yeah, this PR makes perfect sense. I did have a question though

File: extensions/resteasy-classic/resteasy/deployment/src/test/java/io/quarkus/resteasy/test/ProviderConfigInjectionTest.java (hunk 1 above)
Comment (radcortez) [reply extensions/resteasy-classic/resteasy/deployment/src/test/java/io/quarkus/resteasy/test/ProviderConfigInjectionTest.java:51]: In my initial proposal it didn't work, because I was only adding the `BuildTimeRunTimeDefaultValuesConfigSource` plus the sources registered with the build step at static init (basically, there was not system, env or `application.properties` present).

In the end it become too much problematic to remove those sources. For instance, reactive messaging which is also static initialized, requires some configs in the `smallrye` namespace, but because we only record the `quarkus` namespace they are not available in the `BuildTimeRunTimeDefaultValuesConfigSource` and we need to search them in the other sources.

Additional to this, probably on a separate PR, we need to analyze which configuration properties are required for static init and either move them to the `quarkus` namespace or allow other namespaces to be recorded. Once we have that in place, then we can remove the system, env and `application.properties` from static int.

Comment (geoand) [reply extensions/resteasy-classic/resteasy/deployment/src/test/java/io/quarkus/resteasy/test/ProviderConfigInjectionTest.java:51]: I'm just concerned that this might break plenty of users

Comment (radcortez) [reply extensions/resteasy-classic/resteasy/deployment/src/test/java/io/quarkus/resteasy/test/ProviderConfigInjectionTest.java:51]: Yes, that is a possibility if the configuration is in a user custom source and they use a direct injection in a Provider. I don't see a way to work around this.

Comment (geoand) [reply extensions/resteasy-classic/resteasy/deployment/src/test/java/io/quarkus/resteasy/test/ProviderConfigInjectionTest.java:51]: OK, let's just mark this a breaking change and make sure to add a note in the migration guide

**Review by geoand — APPROVED** [review]

**Comment by gsmet** [comment]
@radcortez could you rebase please? There is a conflict.

**Comment by radcortez** [comment]
> @radcortez could you rebase please? There is a conflict.

Done!

**Comment by renegrob** [comment]
@radcortez I'm trying to understand this PR. Just to be sure. It will still be possible to do two builds with different build time properties provided by system properties or environment variables and result in two different augmentation outputs, right? It is more about ignoring the properties that are not prefixed with `quarkus.` / are not in the set of all build time property names?

**Comment by machi1990** [comment]
@radcortez I am reading the description and it says 

> The downside of this, is that some libraries that require static init (like RESTEasy) require their sources to be registered with the build step to work properly, so extension developers will need to keep this in mind.

Do/Can we have this info documented somewhere e.g in the writing extensions guide?

**Comment by radcortez** [comment]
> @radcortez I'm trying to understand this PR. Just to be sure. It will still be possible to do two builds with different build time properties provided by system properties or environment variables and result in two different augmentation outputs, right?

Yes, this does not touch the build time config. What we do here, on runtime at static init, to not discover sources (which causes double init), when we create the final Config instance at application start.

> It is more about ignoring the properties that are not prefixed with `quarkus.` / are not in the set of all build time property names?

Not exactly. The ConfigRoot object instance, are also available at runtime at static init, but because we had additional source at this stage, a property that was build time fixed could have a different value in the ConfigRoot instance. This is not a big deal, because usually no one uses the ConfigRoot instances at runtime, but if someone does their values might be different (which shouldn't happen).

**Comment by radcortez** [comment]
> @radcortez I am reading the description and it says
> 
> > The downside of this, is that some libraries that require static init (like RESTEasy) require their sources to be registered with the build step to work properly, so extension developers will need to keep this in mind.
> 
> Do/Can we have this info documented somewhere e.g in the writing extensions guide?

Yes, I'll add that piece in the extension guide.

**Review by machi1990 — APPROVED** [review]
