### PR TITLE
Save using stream(s) to retrieve Http Headers

### LINKED ISSUE #46949: Save using stream(s) to retrieve Http Headers in ClassRoutingHandler
### Describe the bug

https://github.com/quarkusio/quarkus/pull/42468 - in particular cb63fb601fa4a0b0644c66ed198240ac9accee72 has introduced the usage of stream(s) in the hot path of handling HTTP requests, see 

Image

which is quite costly for public benchmarks like Techempower, see in violet the global effect

Image

Stream(s) are not as optimized as many believe and we should avoid using them in the hot path unless perfectly sure of the effects 🙏 

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by franz1981**
It optimizes the list filtering for the empty/single element case

- Fixes: https://github.com/quarkusio/quarkus/issues/46949

### CODE REVIEW

**Comment by franz1981** [comment]
I have to fix the commit message 😞

**Comment by franz1981** [comment]
@blazmrak too

**Comment by blazmrak** [comment]
@franz1981 My exact thoughts were that it might become a problem at some point, but didn't want to screw around with the code too much and optimize something that might not be an issue... `filterEmptyOnNonTinyList` is a little overcomplicated for my taste, but if it works I don't really care. LGTM if that counts for anything.

**Comment by franz1981** [comment]
> filterEmptyOnNonTinyList is a little overcomplicated for my taste

Please feel free to explain/comment in the PR so I can make it better :pray: 

> but if it works I don't really care.

I'll soon publish the improvement we observed by fixing it :pray:

File: independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/ResteasyReactiveRequestContext.java [hunk 1]
```diff
@@ -850,13 +842,47 @@ public Object getHeader(String name, boolean single) {
...
+            }
+            return list;
+        }
+        // this shouldn't be common both on query params and header values
+        return filterEmptyOnNonTinyList(list);
+    }
+
+    private static List<String> filterEmptyOnNonTinyList(List<String> list) {
+        assert list.size() > 1;
+        List<String> nonEmptyList = null;
```
Comment (blazmrak) [inline independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/ResteasyReactiveRequestContext.java:869]: This is a huge edge case of an edge case imo. If you have a list of params, it's almost guaranteed that at least one will be non empty. It would be easier to just make `new ArrayList(list.size());` and filter the empty strings out.

If you want to keep your idea, I'd flip it around - make a copy only if you land on empty, otherwise you can just return `list`. I'm don't know if it would make a difference, but it should make less allocs in theory. It's an edge case though, so I wouldn't bother with this.

Using traditional for loops would also avoid that `remaining` counter and might improve performance a bit.

Comment (franz1981) [reply independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/ResteasyReactiveRequestContext.java:869]: >  It would be easier to just make new ArrayList(list.size()); and filter the empty strings out.

Since it's slow path I can make it, if it keeps the code more compact and simpler, thanks!

> If you want to keep your idea, I'd flip it around - make a copy only if you land on empty, otherwise you can just return list

I was thinking about it as well - but that means readding the non-empty ones already processed, from the beginning - which can be a waste for lil advantage - since it's already a slow path

> Using traditional for loops

I didn't do it because having `List:.get(index)` can be pretty bad with `LinkedList`s and it is what is been used by Vertx (sigh!). Iterating will just chase the next element instead - saving O(N^2) to happen

**Comment by franz1981** [comment]
As said, the improvement reflect in saving (if not for a small perf panalty) the cost of using streams, as reflected by

image

where, in violet you can see the cost of filtering the collection

**Comment by franz1981** [comment]
@geoand I think this is ready to go - it is still "slow" for uncommon cases but better than before!

File: independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/ResteasyReactiveRequestContext.java [hunk 2]
```diff
@@ -8,13 +8,7 @@
...
 import java.net.URI;
 import java.net.URISyntaxException;
-import java.util.ArrayList;
-import java.util.Arrays;
-import java.util.Collections;
-import java.util.Deque;
-import java.util.LinkedList;
-import java.util.List;
-import java.util.Map;
+import java.util.*;
```
Comment (gsmet) [inline independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/ResteasyReactiveRequestContext.java:11]: Please no star imports.

**Review by gsmet — COMMENTED** [review]
The code is a bit convoluted and maybe we could make it simpler and get a relatively similar boost but... it's not that hard to follow either so I think we can probably go with it.

I added a very minor gripe inline though, it would be nice if you could address it (and adjust your IDE config, unfortunately our tooling can't catch that atm).

**Comment by geoand** [comment]
Once the star import issue is addressed, we can merge this

**Comment by geoand** [comment]
I updated and force-pushed the change

**Review by geoand — APPROVED** [review]

**Comment by franz1981** [comment]
thanks @geoand yesterday I had some tough day and I couldn't fix it :pray:
