### PR TITLE
Duplicate endpoint detection

### LINKED ISSUE #14910: Resteasy-reactive duplicate path exception not detected
**Describe the bug**
If multiple targets are declared for the same path, one of them will be picked as the runtime target for the endpoint

**Expected behavior**
The duplication should be detected at build time, and an exception triggered to prevent application startup

 - Quarkus version : 1.11.1.FINAL

### PR DESCRIPTION
**Pull request by jtama**
Resolves: #14910

### CODE REVIEW

**Comment by jtama-op** [comment]
@FroMage, @geoand, @stuartwdouglas

**Comment by geoand** [comment]
Thanks for this effort.

Can you explain the rules you applied to determine duplicates?

**Comment by jtama-op** [comment]
Yes of course:
2 resources are considered duplicate if :
- They have the same verb
- They have the same path (Class and method combined)
- They can be matched on both consumes and produces values : one of theme has '*' or they are equals.

**Comment by geoand** [comment]
What was the result of the `Quarkus CI / MicroProfile TCKs Tests` job on your fork?

Asking because I am not exactly sure that what you consider a configuration error is what the spec expects as well

**Comment by jtama-op** [comment]
I saw the build is failing I have to check

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Georgios Andrianakis <notifications@github.com>
Envoyé : Monday, February 15, 2021 1:12:01 PM
À : quarkusio/quarkus <quarkus@noreply.github.com>
Cc : Jérôme TAMA <j.tama@groupeonepoint.com>; Author <author@noreply.github.com>
Objet : Re: [quarkusio/quarkus] Duplicate endpoint detection (#15037)


What was the result of the Quarkus CI / MicroProfile TCKs Tests job on your fork?

Asking because I am not exactly sure that what you consider a configuration error is what the spec expects as well

**Comment by jtama-op** [comment]
So, I finally had time to check the MicroProfile TCKs Tests. 

Letting the code as is, leads to 2 failures : 

JAXRSClient0147 : 
`io.quarkus.deployment.configuration.ConfigurationError: GET /GetTest/sub is declared by :
com.sun.ts.tests.jaxrs.ee.rs.get.HttpMethodGetTest#getSub consumes *, produces *
com.sun.ts.tests.jaxrs.ee.rs.get.HttpMethodGetTest#headSub consumes *, produces text/html
GET /GetTest/ is declared by :
com.sun.ts.tests.jaxrs.ee.rs.get.HttpMethodGetTest#getPlain consumes *, produces *
com.sun.ts.tests.jaxrs.ee.rs.get.HttpMethodGetTest#getHtml consumes *, produces text/html`

This one is understandable as the spec says the most specific resource is to be selected.

And JAXRSClient0012
`io.quarkus.deployment.configuration.ConfigurationError: GET /resource/subresource/sub/ is declared by :
com.sun.ts.tests.jaxrs.spec.resource.requestmatching.AnotherSubResource#get consumes *, produces text/plain
com.sun.ts.tests.jaxrs.spec.resource.requestmatching.AnotherSubResource#getget consumes *, produces text/plain`

What bothers me is that I can't reasonably explain how the two sub-resources could be differentiated, and reading the spec page 22, I saw that :

>  Implementations SHOULD report an error if there is more than one sub-resource locator that satisfies this condition.

I pushed a version that fixes the JAXRSClient0147 failure, but as for the JAXRSClient0012 I don't know what to do.

In any case, I think work will be needed on the endpoint score page... But that will be in an other MR.

**Comment by jtama-op** [comment]
@geoand any ideas ?

**Comment by geoand** [comment]
> Ok so I have pushed a bit further :
> When no `@Produces` annotation is found, Quarkus (or whoever) automatically defaults to the text/plain media type.
> 

For a string return type, that is correct. For other objects, we default to JSON.

> * I re-ran the tests with the 1.12.0.Final versions, and they wont fail even if there is a perfect duplicate resource.
> * They also won't fail If one endpoint has no `@Produce` annotation and one has with text/plain media type. And this is because the tests validates the response body contains a given string, not that it is equal to that string.
> 
> For me there is a bug AND a hole in the TCKs tests. @geoand any ideas ?

What hole and what bug are you referring to?
If there is a hole in TCK tests, there isn't much we can do honestly :)

**Comment by jtama-op** [comment]
Well perfect duplicate are not detected, that's the bug, and logically, no tests exist to cover this,that's the hole ;)

**Comment by geoand** [comment]
Most likely yes. I'll try to take a closer look soon and get back to you.

**Comment by stuartwdouglas** [comment]
Produces TEXT_PLAIN is different to producing nothing. By default we have a config option to make Quarkus automatically produce test/plain if the return type is String, but this TCK test turns that off. This means the annotated one is producing * (which will return application/octet-stream if selected), while the other one is producing text/plain.

**Comment by geoand** [comment]
@jtama are you interested in moving this forward?

**Comment by jtama** [comment]
Yes of course, though if I am not wrong, everything we do on Quarkus side would break TCK... What would you suggest we can do ?

**Comment by geoand** [comment]
Basically we should just log a warning when duplicates (in the strictest sense) are detected.

**Comment by jtama** [comment]
Ok, I can just change the exception for a log.

I will check if the dev-ui is also still throwing exceptions

**Comment by jtama** [comment]
I just pushed some code that will trigger exceptions for duplicates except when explicitly turned off as suggested here https://github.com/quarkusio/quarkus/issues/14910#issuecomment-871412024.

As a developer I sure would like to be informed in such case. If I really want random behaviour then I can still ask.

The documentation needs to be updated, but as long as there no agreement on the behaviour I hold it.

Also the resteasy-reactive-testsuite will. to be updated with the given flag. I ran them locally and they're all green.

**Comment by jtama** [comment]
TCK tests will pass once we update the fail on duplicate to false.

@geoand, @FroMage, @mkouba could you please review ?

File: extensions/resteasy-reactive/quarkus-resteasy-reactive-common/runtime/src/main/java/io/quarkus/resteasy/reactive/common/runtime/ResteasyReactiveConfig.java [hunk 1]
```diff
@@ -47,4 +47,10 @@
      */
     @ConfigItem(name = "deny-unannotated-endpoints")
     public boolean denyJaxRs;
+
+    /**
+     * Wether or not duplicate endpoints should trigger error at startup
```
Comment (gastaldi) [inline extensions/resteasy-reactive/quarkus-resteasy-reactive-common/runtime/src/main/java/io/quarkus/resteasy/reactive/common/runtime/ResteasyReactiveConfig.java:52]:
```suggestion
     * Whether or not duplicate endpoints should trigger error at startup
```

File: extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/ResteasyReactiveProcessor.java [hunk 2]
```diff
@@ -24,6 +26,7 @@
 import javax.ws.rs.ext.MessageBodyReader;
 import javax.ws.rs.ext.MessageBodyWriter;
 
+import org.apache.commons.lang3.ArrayUtils;
```
Comment (gastaldi) [inline extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/ResteasyReactiveProcessor.java:29]: Not sure if depending on commons-lang is necessary here. Perhaps it's easier to just copy/paste the `ArrayUtils.isEmpty` method to here to avoid the dependency

File: extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/test/java/io/quarkus/resteasy/reactive/server/test/duplicate/DuplicateResourceWarningTest.java [hunk 3]
```diff
@@ -0,0 +1,36 @@
...
+
+import io.quarkus.test.QuarkusUnitTest;
+
+public class DuplicateResourceWarningTest {
+
+    @RegisterExtension
+    static QuarkusUnitTest runner = new QuarkusUnitTest()
+            .setArchiveProducer(() -> ShrinkWrap.create(JavaArchive.class)
+                    .addClasses(GreetingResource.class, GreetingResource2.class, GreetingResource3.class))
+            .overrideConfigKey("quarkus.resteasy-reactive.fail-on-duplicate", "false")
```
Comment (geoand) [inline extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/test/java/io/quarkus/resteasy/reactive/server/test/duplicate/DuplicateResourceWarningTest.java:22]: So far these properties have been prefixed with `quarkus.rest` instead of `quarkus.resteasy-reactive`. Let's keep it like that for consistence

Comment (jtama) [reply extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/test/java/io/quarkus/resteasy/reactive/server/test/duplicate/DuplicateResourceWarningTest.java:22]: I didn't changed the config prefic, it's fixed by `ResteasyReactiveConfig` class

File: extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/EndpointConfig.java [hunk 4]
```diff
@@ -0,0 +1,46 @@
...
+        if (o == null || getClass() != o.getClass()) {
+            return false;
+        }
+        EndpointConfig that = (EndpointConfig) o;
+        return consumes.equals(that.consumes) && produces.equals(that.produces);
+    }
+
+    @Override
+    public int hashCode() {
+        return Objects.hash(consumes, produces);
```
Comment (FroMage) [inline extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/EndpointConfig.java:44]: Same question here.

File: extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/EndpointConfig.java [hunk 5]
```diff
@@ -0,0 +1,46 @@
...
+import java.util.Objects;
+import java.util.function.BiPredicate;
+
+public class EndpointConfig {
+
+    private String consumes;
+    private String produces;
+    private String endpoint;
+
+    private static final BiPredicate<String, String> isEquivalentMimeType = (item1, item2) -> item1.equals("*")
```
Comment (FroMage) [inline extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/EndpointConfig.java:12]: This doesn't appear to be used, and it seems simplistic too.

File: extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/ResteasyReactiveProcessor.java [hunk 6]
```diff
@@ -415,19 +424,44 @@ private boolean hasAnnotation(MethodInfo method, short paramPosition, DotName an
...
             serverEndpointIndexer = serverEndpointIndexerBuilder.build();
+            Map<String, List<List<EndpointConfig>>> allMethods = new HashMap<>();
 
             for (ClassInfo i : scannedResources.values()) {
                 if (!appResult.keepClass(i.name().toString())) {
                     continue;
                 }
                 ResourceClass endpoints = serverEndpointIndexer.createEndpoints(i);
+                List<ResourceMethod> resourceMethods = endpoints.getMethods();
+                getResourceMethodByPath(endpoints.getPath(),
```
Comment (FroMage) [inline extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/ResteasyReactiveProcessor.java:435]: I have a very hard time reviewing this due to all the stream usage. Perhaps it's just my fault, though. What do you think @geoand ?

File: extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/test/java/io/quarkus/resteasy/reactive/server/test/duplicate/DuplicateResourceWarningTest.java (hunk 3 above)
Comment (FroMage) [reply extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/test/java/io/quarkus/resteasy/reactive/server/test/duplicate/DuplicateResourceWarningTest.java:22]: Yup: https://quarkus.io/guides/all-config#quarkus-resteasy-reactive-common_quarkus-resteasy-reactive-common-resteasy-reactive-common

File: extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/test/java/io/quarkus/resteasy/reactive/server/test/resource/basic/resource/MatchedResource.java [hunk 7]
```diff
@@ -60,7 +60,7 @@ public String start() {
         return "started";
     }
 
-    @Path("start")
+    @Path("startXML")
```
Comment (FroMage) [inline extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/test/java/io/quarkus/resteasy/reactive/server/test/resource/basic/resource/MatchedResource.java:63]: Wait a minute, this is a false positive, isn't it? This endpoint consumes XML, while the other will be selected for non-XML since it's less specific.

**Review by FroMage — CHANGES_REQUESTED** [review]
Thanks, this is very nice, but I think it needs a lot more tests, including with negociation and endpoints without any mime types (inferred from their return type, for example) and wildcards too, just to make sure we're not going to produce errors on legitimate endpoints.

File: extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/ResteasyReactiveProcessor.java (hunk 6 above)
Comment (geoand) [reply extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/ResteasyReactiveProcessor.java:435]: I didn't want to be the person who beat that drum again...
I wanted first to see if someone else would raise this same concern (to ensure it wasn't just a weird personal taste of mine)... Since now you have, I'll just say it:

I dislike stream usage like this very much... I don't think it brings any value, but instead most of the time makes reading the code harder...

Comment (jtama) [reply extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/ResteasyReactiveProcessor.java:435]: ok, i didn't liked them at first, but now that I am used to it I find them more clear. Any way I am not religious about it, so I can refactor to classical loop.

File: extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/EndpointConfig.java [hunk 8]
```diff
@@ -0,0 +1,46 @@
+package io.quarkus.resteasy.reactive.server.deployment;
+
+import java.util.Objects;
+import java.util.function.BiPredicate;
+
+public class EndpointConfig {
+
+    private String consumes;
+    private String produces;
+    private String endpoint;
```
[the remark this answers is not in the document]
Comment (jtama) [reply extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/EndpointConfig.java:10]: Not really, it contains a string following this pattern : fully_qualified_class#method_name. Though it's probably not a really good name...

File: extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/EndpointConfig.java [hunk 9]
```diff
@@ -0,0 +1,46 @@
...
+    @Override
+    public boolean equals(Object o) {
+        if (this == o) {
+            return true;
+        }
+        if (o == null || getClass() != o.getClass()) {
+            return false;
+        }
+        EndpointConfig that = (EndpointConfig) o;
+        return consumes.equals(that.consumes) && produces.equals(that.produces);
```
[the remark this answers is not in the document]
Comment (jtama) [reply extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/EndpointConfig.java:39]: because the endpoint is the method that expose the endpoint, I need to do a refactoring here, I see the code is not really readable...

File: extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/EndpointConfig.java (hunk 5 above)
Comment (jtama) [reply extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/EndpointConfig.java:12]: Ok. 
So indeed, i have to delete the predicate, and add tests to validate produce mimetype if not explicitely set depending on the method return type...

Comment (jtama) [reply extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/EndpointConfig.java:12]: so do we agree that by default if a method doesn't specify it's produce mimetype, it will default to _text/plain_ for primitive type + there object equivalent and String, otherwise it will default to _application/json_ ?

File: extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/ResteasyReactiveProcessor.java (hunk 6 above)
Comment (jtama) [reply extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/ResteasyReactiveProcessor.java:435]: So the basic rule is no stream ?

Comment (geoand) [reply extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/ResteasyReactiveProcessor.java:435]: We don't have a hard rule (for build time code like this). But we really think that using streams in streams and then more streams does not make the code more readable, if anything it makes it less readable.

File: extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/EndpointConfig.java (hunk 5 above)
Comment (jtama) [reply extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/EndpointConfig.java:12]: If yes, I would like to be able to access https://github.com/quarkusio/quarkus/blob/main/independent-projects/resteasy-reactive/common/processor/src/main/java/org/jboss/resteasy/reactive/common/processor/EndpointIndexer.java#L100 which is a map of all primitive types that will bepicked up as _plain/text_, or maybe there is another map available ?

**Comment by jtama** [comment]
ok those tests don't fail locally, is there a way to restart the job ?

**Comment by geoand** [comment]
We can, but if you rebase the PR onto the latest main, the jobs will be rerun

**Comment by geoand** [comment]
Can you please rebase the PR onto `main`? It seems a little to scary to even think about merging :)

**Comment by jtama** [comment]
> Can you please rebase the PR onto `main`? It seems a little to scary to even think about merging :)

I sure will ;)

**Comment by geoand** [comment]
Thanks for this.

Please see https://github.com/quarkusio/quarkus/blob/main/tcks/resteasy-reactive/README.md and update to https://github.com/quarkusio/resteasy-reactive-testsuite/commit/7858acda035bd807715420992e990df680d6ccd7

**Comment by geoand** [comment]
@FroMage mind re-reviewing now that everything is addressed?

**Review by FroMage — DISMISSED** [review]
This is better, but I still think it needs more tests wrt. mime types including wildcards, no?

**Comment by jtama** [comment]
@FroMage 
So I have tests over : 

- Path.
- Verbs.
- Mime types explicitly set.
- Not set at all.

I think I could try and resolve for missing mimetype if we should default on plain/text or application/json.  I am sure, such a thing already exists, but I don't know where and if it's accessible...

File: extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/ResteasyReactiveProcessor.java [hunk 10]
```diff
@@ -577,6 +592,75 @@ private boolean hasAnnotation(MethodInfo method, short paramPosition, DotName an
...
+                .collect(Collectors.joining());
+        if (message.length() > 0) {
+            if (config.failOnDuplicate) {
+                throw new ConfigurationError(message);
+            }
+            log.warning(message);
+        }
+    }
+
+    private void addRessourceMethodByPath(Map<String, List<EndpointConfig>> allMethods, String path, ClassInfo info,
```
Comment (gastaldi) [inline extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/ResteasyReactiveProcessor.java:608]:
```suggestion
    private void addResourceMethodByPath(Map<String, List<EndpointConfig>> allMethods, String path, ClassInfo info,
```

**Comment by FroMage** [comment]
> I think I could try and resolve for missing mimetype if we should default on plain/text or application/json. I am sure, such a thing already exists, but I don't know where and if it's accessible...

Yes but could you add tests over wildcards please/ Also you have a conflict, could you rebase?
Thanks a lot.

**Comment by geoand** [comment]
This need to be rebased

**Comment by jtama** [comment]
Yes, and i also need to implement the tests expected by @FroMage

**Comment by jtama** [comment]
@FroMage I added a ressource with */* mime type, that doesn't break the test. This is because when nothing is present the mime the string used to replace `null` is `'*'`. Is this the expected result ?

**Comment by jtama** [comment]
@geoand @FroMage Now that I have merged, PR seems a bit unreadable. I don't know how to fix that.

**Comment by geoand** [comment]
Likely all that you need to do is rebase the Pull Request onto the latest `main` and force push to your branch.

**Comment by jtama** [comment]
> Done, we only need @FroMage to check if it's fine for him.
What should be done for this PR to pass ?

**Comment by geoand** [comment]
I think we want this.

Can you please rebase so I can then approve and we can merge?

Thanks

**Comment by jtama** [comment]
@geoand I will do this

**Review by geoand — APPROVED** [review]

**Comment by geoand** [comment]
Damn it... I merged this when CI was restarting and GH allowed the PR to be merged...

**Comment by jtama** [comment]
The build was restarting because I made a push to correct the test errors... Which introduced import error.

I just forced push to correct this.

**Comment by geoand** [comment]
Yeah, it was my mistake in not making sure that GitHub had run all the tasks

**Comment by geoand** [comment]
We fixed the importing sorting in [another](https://github.com/quarkusio/quarkus/pull/22858)
