### PR TITLE
Consuming multiple media types from a resource method does not work

### LINKED ISSUE #29732: Consuming multiple media types from a resource method does not work
### Describe the bug

Consuming multiple media types from a JAX-RS resource method does not work with RR:

```
@Path("postMultiMediaTypeConsumer")
    @Consumes({"application/soap+xml", MediaType.TEXT_XML})
    @POST
    public Response postMultiMediaTypeConsumer() throws Exception {
        return Response.ok().build();
    }
```

The reason why it does not work is that [MediaTypeMapper](https://github.com/quarkusio/quarkus/blob/main/independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/handlers/MediaTypeMapper.java#L38) is only resolving the first media type from the resource method.

### Expected behavior

Resolve a JAX-RS method when multiple consume media types are set.

### Actual behavior

RR fails to resolve multiple consume media types and only resolves the first one.

### How to Reproduce?

```
@Path("postMultiMediaTypeConsumer")
    @Consumes({"application/soap+xml", MediaType.TEXT_XML})
    @POST
    public Response postMultiMediaTypeConsumer() throws Exception {
        return Response.ok().build();
    }
```

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by pedroigor**
Closes #29732

### CODE REVIEW

File: independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/handlers/MediaTypeMapper.java [hunk 1]
```diff
@@ -116,6 +113,17 @@ public MediaType selectMediaType(ResteasyReactiveRequestContext requestContext,
         return selected;
     }
 
+    private MediaType[] getProducesMediaTypes(RuntimeResource runtimeResource) {
+        return runtimeResource.getProduces() != null
+                ? runtimeResource.getProduces().getSortedOriginalMediaTypes()
+                : new MediaType[] { MediaType.WILDCARD_TYPE };
```
Comment (geoand) [inline independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/handlers/MediaTypeMapper.java:119]: `new MediaType[] { MediaType.WILDCARD_TYPE }` can be a constant

File: independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/handlers/MediaTypeMapper.java [hunk 2]
```diff
@@ -116,6 +113,17 @@ public MediaType selectMediaType(ResteasyReactiveRequestContext requestContext,
...
+    }
+
+    private List<MediaType> getConsumesMediaTypes(RuntimeResource runtimeResource) {
+        return runtimeResource.getConsumes().isEmpty() ? List.of(MediaType.WILDCARD_TYPE)
```
Comment (geoand) [inline independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/handlers/MediaTypeMapper.java:123]: `List.of(MediaType.WILDCARD_TYPE)` can be a constant

**Review by geoand — APPROVED** [review]
Thanks for this!

I made some minor suggestions.
