### PR TITLE
Copy Content-Type from Netty HttpResponse to APIGatewayV2HTTPResponse

### LINKED ISSUE #15909: AWS Lambda HTTP Content-Type is lost
## Describe the bug
Quarkus RestEasy AWS Lambda's Content-Types don't get returned by AWS API Gateway.

### Expected behavior
The content type returned by the API Gateway is the one set by RESTEasy (ie 'application/json' unless set otherwise via @Produces)

### Actual behavior
The content type is `text/plain`.

## To Reproduce

1. Generate the Amazon Lambda HTTP example at https://quarkus.io/guides/amazon-lambda-http
2. Delete the `GreetingVertx`, `GreetingFunction` and `GreetingServlet` classes, and modify the pom accordingly to remove the corrresponding dependencies
3. Modify `GreetingResource`. Change the `@Produces` annotation to `APPLICATION_JSON` (RestEasy defaults to `application/json` but at least like that it is explicit) and modify the returned String to be a valid piece of JSON
4. Build the native Lambda: `mvn clean install -DskipTests=true -Pnative -Dnative-image.docker-build=true`
5. Upload it to AWS: `aws lambda create-function --function-name mynativefunction --zip-file fileb://target/function.zip --handler not.used.in.provided.runtimei --runtime provided --role arn:aws:iam::1234567890123:role/MyAppropriateRole`
6. Create an API on the API Gateway:
  6.1. Create a new HTTP API
  6.2. Choose the lambda integration uploaded in 5
  6.3. Configure a `GET /hello` route
  6.4. Configure the `$default` stage and create the API
7. Copy the Invoke URL and invoke it: `wget -S https://abcdef.execute-api.zone.amazonaws.com/hello`

Inspect the content-type returned by the invocation - it is `text/plain` despite the content type being `application/json` in the `GreetingResource` class.

### Configuration
NA

### Screenshots
NA

### Output of `uname -a` or `ver`
`Linux DESKTOP-GJJ95MV 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

### Output of `java -version`
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)

### GraalVM version (if different from Java)
NA

### Quarkus version or git rev
1.12.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/rich/.sdkman/candidates/maven/current
Java version: 11.0.10, vendor: AdoptOpenJDK, runtime: /home/rich/.sdkman/candidates/java/11.0.10.hs-adpt
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "4.19.104-microsoft-standard", arch: "amd64", family: "unix"
```

## Additional context
I have managed to fix this locally by adding the following hacky code to the `msg instanceof HttpResponse` clause of the `LambdaHttpHandler` class. I will try to get a pull request done soon.

```java
final List<Entry<String, String>> entries = res.headers().entries();
final Map<String, String> responseHeaders = new HashMap<>();
for (final Iterator<Entry<String, String>> i = entries.iterator(); i.hasNext();) {
	final Entry<String, String> e = i.next();
	log.info(e.getKey() + " : " + e.getValue());
	responseHeaders.put(e.getKey(), e.getValue());
}
responseBuilder.setHeaders(responseHeaders);
```

### PR DESCRIPTION
**Pull request by richiethom**
Fixes #15909 

If the Netty response is an HttpResponse, retrieve its Content-Type and set it on the APIGatewayV2HTTPResponse.

(my first pull request for a long time, a lot has changed, please don't hesitate to fix/squash if necessary)

### CODE REVIEW

File: extensions/amazon-lambda-http/runtime/src/main/java/io/quarkus/amazon/lambda/http/LambdaHttpHandler.java [hunk 1]
```diff
@@ -92,6 +94,16 @@ public void handleMessage(Object msg) {
                     HttpResponse res = (HttpResponse) msg;
                     responseBuilder.setStatusCode(res.status().code());
 
+                    final HttpHeaders responseHeaders = res.headers();
+                    if (responseHeaders != null) {
+                        final String contentType = responseHeaders.getAsString(HttpHeaderNames.CONTENT_TYPE);
+                        if (contentType != null && contentType.trim().length() > 0) {
+                            final Map<String, String> headers = new HashMap<>();
+                            headers.put("Content-Type", contentType);
```
Comment (gsmet) [inline extensions/amazon-lambda-http/runtime/src/main/java/io/quarkus/amazon/lambda/http/LambdaHttpHandler.java:102]: Shouldn't you use the constant here too?

Also could you squash the commits? Thanks!

**Review by gsmet — DISMISSED** [review]

File: extensions/amazon-lambda-http/runtime/src/main/java/io/quarkus/amazon/lambda/http/LambdaHttpHandler.java (hunk 1 above)
Comment (richiethom) [reply extensions/amazon-lambda-http/runtime/src/main/java/io/quarkus/amazon/lambda/http/LambdaHttpHandler.java:102]: I wasn't sure about using the constant there too. The constant is an `AsciiString`, not a `String` so I need to call `toString()` on it. In addition, the constant is from Netty, whereas the `Map` is being put into AWS. Very unlikely I know, but if the Netty headers started being named differently, in a Netty-specific way, it might not work properly on AWS.

If you still want me to use the constant, I can:

`headers.put(HttpHeaderNames.CONTENT_TYPE.toString(), contentType);`

Once you've confirmed one way or the other, I'll work out how to squash the commits!

Comment (gsmet) [reply extensions/amazon-lambda-http/runtime/src/main/java/io/quarkus/amazon/lambda/http/LambdaHttpHandler.java:102]: Yeah, keep it as it is, I totally agree with you it's better this way.

**Comment by richiethom** [comment]
@gsmet finally worked out how to do squash the PR, hopefully it's all ok now

File: extensions/amazon-lambda-http/runtime/src/main/java/io/quarkus/amazon/lambda/http/LambdaHttpHandler.java [hunk 2]
```diff
@@ -92,6 +94,16 @@ public void handleMessage(Object msg) {
...
+                            responseBuilder.setHeaders(headers);
+                        }
+                    }
+
                     Headers multiValueHeaders = new Headers();
                     responseBuilder.setMultiValueHeaders(multiValueHeaders);
                     for (String name : res.headers().names()) {
```
[the remark this answers is not in the document]
Comment (richiethom) [reply extensions/amazon-lambda-http/runtime/src/main/java/io/quarkus/amazon/lambda/http/LambdaHttpHandler.java:109]: I saw that, but without my change the Lambda is returning 'text/plain' rather than 'application/json'. Digging a bit further I found ["Format 2.0 doesn't have multiValueHeaders or multiValueQueryStringParameters fields"](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html) on the AWS API Gateway documentation.

(as stated in #15909 I'm using API Gateway v2)

If you'd rather I used your approach to copy across all headers, but use the setHeaders() method instead, I can easily do this.

**Comment by richiethom** [comment]
I've changed it all, the MultiValueHeaders stuff is now replaced with 'normal' headers. If the Header returned from Netty is multi-valued, it is concatenated with commas, as explained in the [AWS API Gateway 2 documentation](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html):

> Format 2.0 doesn't have multiValueHeaders or multiValueQueryStringParameters fields. Duplicate headers are combined with commas and included in the headers field. Duplicate query strings are combined with commas and included in the queryStringParameters field.

Let me know what you think.

**Comment by richiethom** [comment]
hi @patriot1burke and @gsmet this is now ready for a review.

File: extensions/amazon-lambda-http/runtime/src/main/java/io/quarkus/amazon/lambda/http/LambdaHttpHandler.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (patriot1burke) [reply extensions/amazon-lambda-http/runtime/src/main/java/io/quarkus/amazon/lambda/http/LambdaHttpHandler.java:100]: Richie,

The code uses com.amazonaws.services.lambda.runtime.events.APIGatewayV2HTTPResponse which does have a multivalueheaders property.   I guess when they run within Lambda runtime without our wrapper they marshal this correctly?  Oh well, your fix looks good.

**Review by patriot1burke — APPROVED** [review]

**Comment by patriot1burke** [comment]
@richiethom Great job on this.  Thank you.
