### PR TITLE
Utilize Vert.x Tracing SPI in OpenTelemetry

### LINKED ISSUE #17117: Switch OpenTelemetry extension to use Vert.x 4 Tracing SPI
## Description

With the switch to Vert.x 4, there is now a dedicated SPI for tracing we can hook into, as opposed to writing our own handlers. We should switch to this approach as then it's "everywhere" vs us needing to add it in more places.

## Implementation ideas

Implement SPI as defined by https://github.com/eclipse-vertx/vert.x/tree/master/src/main/java/io/vertx/core/spi/tracing

### LINKED ISSUE #17386: Dev mode hot reload fails with OpenTelemetry in dependencies
## Describe the bug

Use OpenTelemetry as dependency and use Quarkus dev mode. Make a change in a source file and see Quarkus trying to reload

### Expected behavior

Reload works

### Actual behavior

Reload fails with

```
2021-05-20 15:17:52,375 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (Timer-0) Failed to start quarkus: java.lang.RuntimeException: java.lang.IllegalStateException: GlobalOpenTelemetry.set has already been called. GlobalOpenTelemetry.set must be called only once before any calls to GlobalOpenTelemetry.get. If you are using the OpenTelemetrySdk, use OpenTelemetrySdkBuilder.buildAndRegisterGlobal instead. Previous invocation set to cause of this exception.
        at io.quarkus.dev.appstate.ApplicationStateNotification.waitForApplicationStart(ApplicationStateNotification.java:51)
        at io.quarkus.runner.bootstrap.StartupActionImpl.runMainClass(StartupActionImpl.java:145)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.restartApp(IsolatedDevModeMain.java:191)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.restartCallback(IsolatedDevModeMain.java:175)
        at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:254)
        at org.apache.camel.quarkus.core.devmode.CamelHotReplacementSetup$1.run(CamelHotReplacementSetup.java:36)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
        at java.base/java.util.TimerThread.run(Timer.java:506)
Caused by: java.lang.IllegalStateException: GlobalOpenTelemetry.set has already been called. GlobalOpenTelemetry.set must be called only once before any calls to GlobalOpenTelemetry.get. If you are using the OpenTelemetrySdk, use OpenTelemetrySdkBuilder.buildAndRegisterGlobal instead. Previous invocation set to cause of this exception.
        at io.opentelemetry.api.GlobalOpenTelemetry.set(GlobalOpenTelemetry.java:83)
        at io.opentelemetry.sdk.OpenTelemetrySdkBuilder.buildAndRegisterGlobal(OpenTelemetrySdkBuilder.java:62)
        at io.quarkus.opentelemetry.OpenTelemetryRecorder.createOpenTelemetry(OpenTelemetryRecorder.java:24)
        at io.quarkus.deployment.steps.OpenTelemetryProcessor$createOpenTelemetry-192994636.deploy_0(OpenTelemetryProcessor$createOpenTelemetry-192994636.zig:74)
        at io.quarkus.deployment.steps.OpenTelemetryProcessor$createOpenTelemetry-192994636.deploy(OpenTelemetryProcessor$createOpenTelemetry-192994636.zig:40)
        at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:479)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/java.lang.Class.newInstance(Class.java:584)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:65)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.runner.bootstrap.StartupActionImpl$3.run(StartupActionImpl.java:134)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.Throwable
        at io.opentelemetry.api.GlobalOpenTelemetry.set(GlobalOpenTelemetry.java:91)
        at io.opentelemetry.sdk.OpenTelemetrySdkBuilder.buildAndRegisterGlobal(OpenTelemetrySdkBuilder.java:62)
        at io.quarkus.opentelemetry.OpenTelemetryRecorder.createOpenTelemetry(OpenTelemetryRecorder.java:24)
        at io.quarkus.deployment.steps.OpenTelemetryProcessor$createOpenTelemetry-192994636.deploy_0(OpenTelemetryProcessor$createOpenTelemetry-192994636.zig:74)
        at io.quarkus.deployment.steps.OpenTelemetryProcessor$createOpenTelemetry-192994636.deploy(OpenTelemetryProcessor$createOpenTelemetry-192994636.zig:40)
        at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:466)
        ... 15 more

2021-05-20 15:17:52,375 ERROR [io.qua.run.boo.StartupActionImpl] (Quarkus Main Thread) Error running Quarkus: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.runner.bootstrap.StartupActionImpl$3.run(StartupActionImpl.java:134)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ExceptionInInitializerError
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/java.lang.Class.newInstance(Class.java:584)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:65)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
        ... 6 more
Caused by: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:532)
        ... 15 more
Caused by: java.lang.IllegalStateException: GlobalOpenTelemetry.set has already been called. GlobalOpenTelemetry.set must be called only once before any calls to GlobalOpenTelemetry.get. If you are using the OpenTelemetrySdk, use OpenTelemetrySdkBuilder.buildAndRegisterGlobal instead. Previous invocation set to cause of this exception.
        at io.opentelemetry.api.GlobalOpenTelemetry.set(GlobalOpenTelemetry.java:83)
        at io.opentelemetry.sdk.OpenTelemetrySdkBuilder.buildAndRegisterGlobal(OpenTelemetrySdkBuilder.java:62)
        at io.quarkus.opentelemetry.OpenTelemetryRecorder.createOpenTelemetry(OpenTelemetryRecorder.java:24)
        at io.quarkus.deployment.steps.OpenTelemetryProcessor$createOpenTelemetry-192994636.deploy_0(OpenTelemetryProcessor$createOpenTelemetry-192994636.zig:74)
        at io.quarkus.deployment.steps.OpenTelemetryProcessor$createOpenTelemetry-192994636.deploy(OpenTelemetryProcessor$createOpenTelemetry-192994636.zig:40)
        at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:479)
        ... 15 more
Caused by: java.lang.Throwable
        at io.opentelemetry.api.GlobalOpenTelemetry.set(GlobalOpenTelemetry.java:91)
        at io.opentelemetry.sdk.OpenTelemetrySdkBuilder.buildAndRegisterGlobal(OpenTelemetrySdkBuilder.java:62)
        at io.quarkus.opentelemetry.OpenTelemetryRecorder.createOpenTelemetry(OpenTelemetryRecorder.java:24)
        at io.quarkus.deployment.steps.OpenTelemetryProcessor$createOpenTelemetry-192994636.deploy_0(OpenTelemetryProcessor$createOpenTelemetry-192994636.zig:74)
        at io.quarkus.deployment.steps.OpenTelemetryProcessor$createOpenTelemetry-192994636.deploy(OpenTelemetryProcessor$createOpenTelemetry-192994636.zig:40)
        at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:466)
        ... 15 more

2021-05-20 15:17:52,439 INFO  [io.qua.dep.dev.RuntimeUpdatesProcessor] (Timer-0) Hot replace total time: 2.420s 


```

(btw, it is funny to see how this tells `Caused by: java.lang.RuntimeException: Failed to start quarkus` and in the last line it pretends that the Hot replace worked, which it did not. Quarkus has to be stopped and restarted.

### Quarkus version or git rev

1.13.4

cc @kenfinnigan

### PR DESCRIPTION
**Pull request by kenfinnigan**
Fixes #17117 and fixes #17386.

- Implement Vert.x Tracing SPIs for OpenTelemetry
- Update OpenTelemetry to 1.2.0
- Update package names to reflect the usual naming pattern
- Implement OpenTelemetry context storage backed by Vert.x Context

### CODE REVIEW

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/vertx/VertxTracingAdapter.java [hunk 1]
```diff
@@ -0,0 +1,289 @@
...
+public class VertxTracingAdapter extends TracingOptions implements VertxTracer<Span, Span>, VertxTracerFactory {
+    private static final String SCOPE_KEY = VertxTracingAdapter.class.getName() + ".scope";
+    private static final String SPAN_KEY = VertxTracingAdapter.class.getName() + ".activeSpan";
+    private static TextMapPropagator TEXT_MAP_PROPAGATOR;
+
+    private Tracer tracer;
+
+    public void init() {
+        Instance<Tracer> tracerInstance = CDI.current().select(Tracer.class);
+        if (tracerInstance.isResolvable()) {
```
Comment (ebullient) [inline extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/vertx/VertxTracingAdapter.java:55]: what happens if it isn't?

**Review by ebullient — APPROVED** [review]

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/vertx/VertxTracingAdapter.java (hunk 1 above)
Comment (kenfinnigan) [reply extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/vertx/VertxTracingAdapter.java:55]: In theory it will never reach that point, as it would mean the `Producer` for `Tracer` is not present but this class is.

Enable/Disable tracing should mean both are present or both are missing.

Comment (ebullient) [reply extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/vertx/VertxTracingAdapter.java:55]: ok. so why bother checking? You don't test for null anywhere else in here. If you're going to bother checking, you need to handle what happens if it isn't resolvable. Does that mean you throw? You turn it off? Cause an NPE is waiting (however unlikely, I will grant)

**Comment by kenfinnigan** [comment]
@michalszynkiewicz @cescoffier I think there must be some kind of race in the gRPC test as with this PR the JDK 11 one passes and the JDK 16 one fails.

File: extensions/opentelemetry/deployment/src/main/java/io/quarkus/opentelemetry/deployment/OpenTelemetryProcessor.java [hunk 2]
```diff
@@ -51,9 +58,21 @@ void registerOpenTelemetryContextStorage(
 
     @BuildStep(onlyIf = OpenTelemetryEnabled.class)
     @Record(ExecutionTime.STATIC_INIT)
-    void createOpenTelemetry(OpenTelemetryRecorder recorder, Optional<TracerProviderBuildItem> tracerProviderBuildItem) {
+    void createOpenTelemetry(OpenTelemetryRecorder recorder, Optional<TracerProviderBuildItem> tracerProviderBuildItem,
+            LaunchModeBuildItem launchMode) {
+        if (launchMode.getLaunchMode() == LaunchMode.DEVELOPMENT) {
```
Comment (radcortez) [inline extensions/opentelemetry/deployment/src/main/java/io/quarkus/opentelemetry/deployment/OpenTelemetryProcessor.java:63]: I think this could go into a separate step with an `onlyIf=IsDevelopment`, plus the OT check. But not a big deal.

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/vertx/VertxTracingAdapter.java [hunk 3]
```diff
@@ -0,0 +1,293 @@
...
+
+            SpanBuilder builder;
+
+            // Create new span
+            builder = tracer.spanBuilder(operationName(request, operation))
+                    .setParent(propagatedContext)
+                    .setSpanKind(SpanKind.RPC.equals(kind) ? io.opentelemetry.api.trace.SpanKind.SERVER
+                            : io.opentelemetry.api.trace.SpanKind.CONSUMER);
+
+            //TODO - Figure out how to handle span name in a better way.
```
Comment (radcortez) [inline extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/vertx/VertxTracingAdapter.java:95]: Isn't the span name given by `operationName`? Is there any convention on how a span should be named?

**Review by radcortez — APPROVED** [review]

**Review by gsmet — DISMISSED** [review]
Please squash the commits before merging.

File: extensions/opentelemetry/deployment/src/main/java/io/quarkus/opentelemetry/deployment/OpenTelemetryProcessor.java (hunk 2 above)
Comment (kenfinnigan) [reply extensions/opentelemetry/deployment/src/main/java/io/quarkus/opentelemetry/deployment/OpenTelemetryProcessor.java:63]: I wanted to have them together so it was clear we were resetting the OT instance in dev mode before we set it again

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/vertx/VertxTracingAdapter.java (hunk 3 above)
Comment (kenfinnigan) [reply extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/vertx/VertxTracingAdapter.java:95]: `operationName` is driven by Vert.x, which uses the OpenTracing naming conventions, and we need the OpenTelemetry semantic conventions.

OpenTelemetry conventions are here: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md

We still need to fix the cardinality of the name as at present we're not removing parameter values, but that's up next

**Comment by kenfinnigan** [comment]
@gsmet all of them, or just the last two by me into one?

**Comment by michalszynkiewicz** [comment]
> @michalszynkiewicz @cescoffier I think there must be some kind of race in the gRPC test as with this PR the JDK 11 one passes and the JDK 16 one fails.

this commit should fix the problem with gRPC: https://github.com/quarkusio/quarkus/pull/17442/commits/385106711bcdc6ec41b583457f9d96e0084b4789

**Comment by kenfinnigan** [comment]
Thanks @michalszynkiewicz!
