### PR TITLE
Change security annotations to use recorders

### LINKED ISSUE #11075: Large numbers of security annotations will cause deployment to fail
I noticed this when playing around with my large deployment generator, if you have more than around 1k security annotations you will get the following:

    [ERROR] 	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#generateResources threw an exception: org.objectweb.asm.MethodTooLargeException: Method too large: io/quarkus/security/runtime/interceptor/SecurityCheckStorage_878ea92f854303317df5146707e738a696454a31_Synthetic_Bean.create (Ljavax/enterprise/context/spi/CreationalContext;)Lio/quarkus/security/runtime/interceptor/SecurityCheckStorage;

### PR DESCRIPTION
**Pull request by stuartwdouglas**
Recorders automatically break up large methods

Fixes #11075

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]
LGTM

File: extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/check/SupplierRolesAllowedCheck.java [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+
+import io.quarkus.security.ForbiddenException;
+import io.quarkus.security.UnauthorizedException;
+import io.quarkus.security.identity.SecurityIdentity;
+
+public class SupplierRolesAllowedCheck implements SecurityCheck {
+
+    private final Supplier<String[]> allowedRolesSupplier;
+
+    private volatile String[] allowedRoles;
```
Comment (geoand) [inline extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/check/SupplierRolesAllowedCheck.java:14]: Minor nitpick: This doesn't need to be `volatile` unless I am missing something. It could just be `final`.

Comment (geoand) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/check/SupplierRolesAllowedCheck.java:14]: NEvermind, read the code wrong :facepalm:

**Review by geoand — APPROVED** [review]
This is great! Not only does it fix an issue that we were bound to run into at some point, but it also gets rid of a lot of bytecode generation, :+1: :+1: :+1:
