### PR TITLE
Enhance OpenTelemetry's DropTargetsSampler

### LINKED ISSUE #27452: Fix TODO in DropTargetsSampler.java
See https://github.com/quarkusio/quarkus/pull/26898/files#r952770353

(Opening an issue as Roberto is on PTO)

### LINKED ISSUE #34376: swagger-ui endpoint is traced by OTel
### Describe the bug

By default, `quarkus-opentelemetry` does not trace non-application endpoints, unless this is explicitly enabled (`quarkus.otel.traces.suppress-non-application-uris=false`)

`quarkus-smallrye-openapi` has 2 non-application endpoints:
- `/q/openapi`
- `/q/swagger-ui/`

While `/q/openapi` is by default not traced, `/q/swagger-ui/` is.

Btw. `/q/swagger-ui/` is only included in dev mode, unless stated otherwise (`quarkus.swagger-ui.always-include=true`), so maybe the tracing is intentional?

### Expected behavior

No tracing of `/q/swagger-ui/` endpoint by default.

### Actual behavior

`/q/swagger-ui/` endpoint is traced regardless of `quarkus.otel.traces.suppress-non-application-uris`, just like a regular application endpoint.

### How to Reproduce?

```
git clone https://github.com/jsmrcka/reproducers.git -b swagger-ui-otel
mvn -f ./reproducers clean verify
```

### Output of `uname -a` or `ver`

Linux 6.2.15-200.fc37.x86_64

### Output of `java -version`

openjdk 17.0.7 2023-04-18

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

3.1.2.Final, 999-SNAPSHOT 2023-06-27

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.8.8

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
This allows us to move effectively drop traces
belonging to SwaggerUI and other framework endpoints

Fixes: #34376
Fixes: #27452

### CODE REVIEW

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/DropTargetsSampler.java [hunk 1]
```diff
@@ -25,15 +25,44 @@ public SamplingResult shouldSample(Context parentContext, String traceId, String
...
         }
 
         return sampler.shouldSample(parentContext, traceId, name, spanKind, attributes, parentLinks);
     }
 
+    /**
+     * Determines whether a path should be dropped
+     * TODO: this can certainly be optimized if we find that it's a hot-path
+     */
+    private boolean shouldDrop(String target) {
```
Comment (brunobat) [inline extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/DropTargetsSampler.java:40]: Do you think you can add a unit test to this method with some target patterns?

Comment (geoand) [reply extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/DropTargetsSampler.java:40]: Done

**Review by brunobat — APPROVED** [review]
Thanks very much for your help @geoand

**Comment by geoand** [comment]
🙏🏼

**Review by radcortez — APPROVED** [review]
