### PR TITLE
fix: use own AddEnvVarDecorator to prevent it from being skipped

### LINKED ISSUE #12063: Quarkus kubernetes sidecars EnvVar do not work
**Describe the bug**
Hi,

I am trying to generate sidecar configs with env variables using quarkus application.properties. I have below in my application.properties.

quarkus.kubernetes-client.trust-certs=true
quarkus.container-image.name=supersonicjava
quarkus.container-image.registry=quay.io
quarkus.container-image.group=arturobrzut

quarkus.kubernetes.sidecars.mariadb.image= mariadb:10.5.5
quarkus.kubernetes.sidecars.mariadb.env-vars.MYSQL_DATABASE.name=my
quarkus.kubernetes.sidecars.mariadb.env-vars.MYSQL_ROOT_PASSWORD.name=pass
quarkus.kubernetes.sidecars.mariadb.env-vars.MYSQL_USER.name=root
quarkus.hibernate-orm.database.generation = drop-and-create

It is supposed to configure env var inside container mariadb in kubernetes.yml. But it is not. 
When I set mount points in sidecar or command in sidecar it works, but env variables not
Env variable works on POD level also, but inside sidecar not

**Expected behavior**
Sidecar container should contain env variable in kubernetes.yml

**Actual behavior**
Sidecar container does not contain env var

```
      - image: mariadb:10.5.5
        imagePullPolicy: IfNotPresent
        name: mariadb
        workingDir: ""
      serviceAccount: supersonicjava
```

**To Reproduce**
1. Copy below configs in application.properties of a quarkus Kubernetes project

```
quarkus.container-image.name=supersonicjava
quarkus.container-image.registry=quay.io
quarkus.container-image.group=arturobrzut

quarkus.kubernetes.sidecars.mariadb.image= mariadb:10.5.5
quarkus.kubernetes.sidecars.mariadb.env-vars.MYSQL_DATABASE.name=my
quarkus.kubernetes.sidecars.mariadb.env-vars.MYSQL_ROOT_PASSWORD.name=pass
quarkus.kubernetes.sidecars.mariadb.env-vars.MYSQL_USER.name=root
quarkus.hibernate-orm.database.generation = drop-and-create

```
2. Build project
3. check kuberneties.yaml

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
    uname -a
   Linux my 4.18.0-193.14.3.el8_2.x86_64 #1 SMP Mon Jul 20 15:02:29 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: 
java -version                             
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment 18.9 (build 11.0.8+10)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.8+10, mixed mode)

 - GraalVM version (if different from Java): 
GraalVM and Java the same mandrel-java11-20.1.0.1.Final
 - Quarkus version or git rev: 
    <quarkus-plugin.version>1.7.3.Final</quarkus-plugin.version>

 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
./mvnw --version                                                                                                                                                                           ✔ 
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/aobrzut/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3
Java version: 11.0.8, vendor: N/A, runtime: /home/aobrzut/tools/graalvm/mandrel/mandrel-java11-20.1.0.1.Final
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.18.0-193.14.3.el8_2.x86_64", arch: "amd64", family: "unix"

**Additional context**
based on doc 
https://quarkus.io/guides/kubernetes

### PR DESCRIPTION
**Pull request by metacosm**
Fixes #12063. This occurs because the dekorate version of
AddEnvVarDecorator inherits from ApplicationContainerDecorator
which expects metadata to be present, which doesn't happen in our
context. We sidestep the issue by wrapping the original behavior and
calling its andThenVisit method, which does the work when not skipped.

### CODE REVIEW

File: extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/ContainerAdapter.java [hunk 1]
```diff
@@ -5,7 +5,6 @@
 import io.dekorate.kubernetes.config.Env;
 import io.dekorate.kubernetes.config.Mount;
 import io.dekorate.kubernetes.config.Port;
-import io.dekorate.kubernetes.decorator.AddEnvVarDecorator;
```
Comment (geoand) [inline extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/ContainerAdapter.java:8]: LOL - This really through me off regarding where your `AddEnvVarDecorator` was being used :)

File: integration-tests/kubernetes/quarkus-standard-way/src/test/java/io/quarkus/it/kubernetes/KubernetesWithSidecarAndJibTest.java [hunk 2]
```diff
@@ -91,6 +91,10 @@ private void assertSidecar(io.fabric8.kubernetes.api.model.PodSpec podSpec) {
                     assertThat(c.getPorts()).singleElement().satisfies(p -> {
                         assertThat(p.getContainerPort()).isEqualTo(3000);
                     });
+                    assertThat(c.getEnv()).singleElement().satisfies(e -> {
```
Comment (geoand) [inline integration-tests/kubernetes/quarkus-standard-way/src/test/java/io/quarkus/it/kubernetes/KubernetesWithSidecarAndJibTest.java:94]: Can we also assert that the env vars are **not** added to the application container?

**Review by geoand — APPROVED** [review]
Thanks!

File: integration-tests/kubernetes/quarkus-standard-way/src/test/java/io/quarkus/it/kubernetes/KubernetesWithSidecarAndJibTest.java (hunk 2 above)
Comment (metacosm) [reply integration-tests/kubernetes/quarkus-standard-way/src/test/java/io/quarkus/it/kubernetes/KubernetesWithSidecarAndJibTest.java:95]: Done.

**Comment by geoand** [comment]
Seems like some of the tests are failing:

```
KubernetesWithSidecarAndJibTest.assertGeneratedResources:47->lambda$assertGeneratedResources$7:52->lambda$assertGeneratedResources$6:53->lambda$assertGeneratedResources$5:54->lambda$assertGeneratedResources$4:57->assertApplicationContainer:66->lambda$assertApplicationContainer$10:76 
2020-09-15T20:58:50.0993746Z Expecting empty but was:<[EnvVar(name=KUBERNETES_NAMESPACE, value=null, valueFrom=EnvVarSource(configMapKeyRef=null, fieldRef=ObjectFieldSelector(apiVersion=null, fieldPath=metadata.namespace, additionalProperties={}), resourceFieldRef=null, secretKeyRef=null, additionalProperties={}), additionalProperties={})]>
```

File: extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/AddEnvVarDecorator.java [hunk 3]
```diff
@@ -0,0 +1,30 @@
...
+/**
+ * Delegate to dekorate's version to sidestep the fact that the dekorate version of AddEnvVarDecorator inherits from
+ * ApplicationContainerDecorator which expects metadata to be present, which doesn't happen in our context. We sidestep the
+ * issue by wrapping the original behavior and calling its andThenVisit method, which does the work when not skipped.
+ */
+public class AddEnvVarDecorator extends Decorator<ContainerBuilder> {
+    private final io.dekorate.kubernetes.decorator.AddEnvVarDecorator delegate;
+
+    public AddEnvVarDecorator(Env env) {
+        delegate = new io.dekorate.kubernetes.decorator.AddEnvVarDecorator(env);
```
Comment (iocanel) [inline extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/AddEnvVarDecorator.java:19]: I like it!

**Review by iocanel — APPROVED** [review]
LGTM

**Comment by metacosm** [comment]
Who's deciding if this gets merged or not?

**Comment by geoand** [comment]
Decision made 😉
