### PR TITLE
Fix missing method in native mode when an SSE endpoint returns a Flow.Publisher

### LINKED ISSUE #33106: Quarkus 3.0.1 behaves different in reactive native mode
This is a reminder for @maxandersen for 

https://github.com/quarkiverse/quarkus-neo4j/pull/161#issuecomment-1532797679

and https://github.com/quarkiverse/quarkus-neo4j/issues/165#issuecomment-1533188428

We didn't change anything on hour side between 3.0.0 and 3.0.1 and I am out of options for that.

Issues persists with 3.0.2, too

### PR DESCRIPTION
**Pull request by cescoffier**
Fix https://github.com/quarkusio/quarkus/issues/33106.

### CODE REVIEW

**Review by geoand — APPROVED** [review]

File: extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/ResteasyReactiveProcessor.java [hunk 1]
```diff
@@ -4,8 +4,7 @@
 import static io.quarkus.resteasy.reactive.common.deployment.QuarkusResteasyReactiveDotNames.HTTP_SERVER_RESPONSE;
 import static io.quarkus.resteasy.reactive.common.deployment.QuarkusResteasyReactiveDotNames.ROUTING_CONTEXT;
 import static java.util.stream.Collectors.toList;
-import static org.jboss.resteasy.reactive.common.processor.ResteasyReactiveDotNames.DATE_FORMAT;
-import static org.jboss.resteasy.reactive.common.processor.ResteasyReactiveDotNames.MULTI;
+import static org.jboss.resteasy.reactive.common.processor.ResteasyReactiveDotNames.*;
```
Comment (gsmet) [inline extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/ResteasyReactiveProcessor.java:7]: No no.

**Review by gsmet — COMMENTED** [review]
Looks good to me except for the star import.
