### PR TITLE
Clarify documentation of Hibernate ORM dialects wrt database multi-tenancy

### LINKED ISSUE #41754: Hibernate ORM - Database multitenancy example from documentation does not work
### Describe the bug

Hi,

I'm trying to set up multitenancy using the DATABASE approach, as described here : https://quarkus.io/guides/hibernate-orm#multitenancy but it seems it is not working.

Here is my configuration : 

```
quarkus.hibernate-orm.database.generation=none

quarkus.hibernate-orm.multitenant=DATABASE

quarkus.datasource.a.db-kind=postgresql
quarkus.datasource.a.username=a
quarkus.datasource.a.password=a
quarkus.datasource.a.jdbc.url=jdbc:postgresql://localhost:5432/a

quarkus.datasource.b.db-kind=postgresql
quarkus.datasource.b.username=b
quarkus.datasource.b.password=b
quarkus.datasource.b.jdbc.url=jdbc:postgresql://localhost:5432/b
```

But I'm getting this error at startup : 

`io.quarkus.runtime.configuration.ConfigurationException: The Hibernate ORM extension could not infer the dialect for persistence unit '<default>'. When using database multi-tenancy, you must either configure a datasource for that persistence unit (refer to https://quarkus.io/guides/datasource for guidance), or set the dialect explicitly through property 'quarkus.hibernate-orm.dialect'.`

The error is not very clear and I cannot find any reference to 'quarkus.hibernate-orm.dialect' in https://quarkus.io/guides/datasource

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19045.4529]

### Output of `java -version`

21.0.3

### Quarkus version or git rev

3.12.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6 

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by yrodiere**
Fixes #41754

### CODE REVIEW

File: integration-tests/hibernate-orm-tenancy/connection-resolver-legacy-qualifiers/src/main/resources/application.properties [hunk 1]
```diff
@@ -3,7 +3,7 @@ quarkus.hibernate-orm.database.generation=none
 quarkus.hibernate-orm.multitenant=database
 # Necessary because we're creating datasources dynamically,
 # which means the extension can't rely on a static datasource to guess the dialect
-quarkus.hibernate-orm.dialect=org.hibernate.dialect.MariaDBDialect
+quarkus.hibernate-orm.dialect=MariaDB
```
Comment (marko-bekhta) [inline integration-tests/hibernate-orm-tenancy/connection-resolver-legacy-qualifiers/src/main/resources/application.properties:6]: How about updating the `quarkus.hibernate-orm."inventory".dialect` or did you keep it an FQCN so that we test both scenarios?

File: extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmConfigPersistenceUnit.java [hunk 2]
```diff
@@ -276,11 +276,15 @@ default boolean isAnyPropertySet() {
...
         /**
-         * Class name of the Hibernate ORM dialect.
+         * Name of the Hibernate ORM dialect.
          *
-         * The complete list of bundled dialects is available in the
-         * https://docs.jboss.org/hibernate/stable/orm/javadocs/org/hibernate/dialect/package-summary.html[Hibernate ORM
-         * JavaDoc].
+         * For built-in dialects, the expected value is one of the names
+         * in the link:{hibernate-orm-dialect-docs-url}[official list of dialects],
+         * **without the `Dialect` suffix,
```
Comment (marko-bekhta) [inline extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmConfigPersistenceUnit.java:294]:
```suggestion
         * *without* the `Dialect` suffix,
```

File: docs/src/main/asciidoc/hibernate-orm.adoc [hunk 3]
```diff
@@ -84,15 +84,15 @@ then add the relevant configuration properties in `{config-file}`.
...
 quarkus.datasource.username = hibernate
 quarkus.datasource.password = hibernate
 quarkus.datasource.jdbc.url = jdbc:postgresql://localhost:5432/hibernate_db
 
-# drop and create the database at startup (use `update` to only update the schema)
-quarkus.hibernate-orm.database.generation=drop-and-create
+quarkus.hibernate-orm.database.generation=drop-and-create <2>
 ----
+<1> xref:datasources[Configure the datasource].
+<2> Drop and create the database at startup (use `update` to only update the schema).
```
Comment (marko-bekhta) [inline docs/src/main/asciidoc/hibernate-orm.adoc:95]: Maybe a silly question ... shouldn't we be hinting users towards flyway/liquibase for schema management and suggesting `quarkus.hibernate-orm.database.generation` more for "testing purposes"? 🙈🙈🙈

File: docs/src/main/asciidoc/hibernate-orm.adoc [hunk 4]
```diff
@@ -1127,32 +1127,37 @@ In general, it is not possible to use the Hibernate ORM database generation feat
 Therefore, you have to disable it, and you need to make sure that the tables are created per schema.
 The following setup will use the xref:flyway.adoc[Flyway] extension to achieve this goal.
 
+[[schema-approach]]
 ==== SCHEMA approach
 
 The same data source will be used for all tenants and a schema has to be created for every tenant inside that data source.
+
 CAUTION: Some databases like MariaDB/MySQL do not support database schemas. In these cases you have to use the DATABASE approach below.
```
Comment (marko-bekhta) [inline docs/src/main/asciidoc/hibernate-orm.adoc:1152]:
```suggestion
CAUTION: Some databases like MariaDB/MySQL do not support database schemas. In these cases you have to use the <<database-approach,DATABASE approach>> below.
```

maybe let's have a link ?

**Review by marko-bekhta — COMMENTED** [review]
Looks nice 😃 👍🏻 

I've added a couple of comments and the CI seems to complain about formatting 😖 😕

File: docs/src/main/asciidoc/hibernate-orm.adoc (hunk 3 above)
Comment (yrodiere) [reply docs/src/main/asciidoc/hibernate-orm.adoc:95]: Good idea, PR welcome! :)

**Comment by yrodiere** [comment]
Thanks @marko-bekhta , I addressed your comments!

**Review by marko-bekhta — APPROVED** [review]
thanks 😃 🎉

**Review by gastaldi — APPROVED** [review]
