### PR TITLE
Register generated output dir for kotlin gradle plugin

### LINKED ISSUE #12874: A gradle project with kotlin and grpc fails compilation
**Describe the bug**
Following the [gRPC getting started guid](https://quarkus.io/guides/grpc-getting-started) but using gradle and kotlin, the code fails compilation, because it doesn't find the generated proto classes. The protoc compiler does generate them successfully.

Using the same helloworld.proto and HelloService.kt on a maven project compiles and starts a gRPC server successfully.

**Expected behavior**
Running `./gradlew quarkusDev` compiles successfully and starts a gRPC server.

**Actual behavior**
The compile fails with unresolved references
> Task :compileKotlin FAILED
e: .../HelloService.kt: (4, 19): Unresolved reference: example
e: .../HelloService.kt: (5, 19): Unresolved reference: example
e: .../HelloService.kt: (6, 19): Unresolved reference: example
e: .../HelloService.kt: (11, 22): Unresolved reference: GreeterGrpc
e: .../HelloService.kt: (12, 5): 'sayHello' overrides nothing
e: .../HelloService.kt: (12, 36): Unresolved reference: HelloRequest
e: .../HelloService.kt: (12, 83): Unresolved reference: HelloReply
e: .../HelloService.kt: (15, 33): Unresolved reference: HelloReply

**To Reproduce**

[Reproducer project](https://github.com/lmagomes/gradle-grpc-kotlin).

1. clone the reproducer
2. run `./gradlew quarkusDev`
3. inspect result

**Configuration**
Empty configuration, using the default settings

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
```
Linux tux 5.4.0-7642-generic #46~1598628707~20.04~040157c-Ubuntu SMP Fri Aug 28 18:02:16 UTC  x86_64 x86_64 x86_64 GNU/Linux
```
 - Output of `java -version`: 
```
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu120.04, mixed mode)
```

 - GraalVM version (if different from Java): 
Not relevant

 - Quarkus version or git rev: 
* 1.9.0-Final
* c49f38eb5aecccbe4b78d27e4bc2109e02a14cc4

 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
```
------------------------------------------------------------
Gradle 6.5.1
------------------------------------------------------------

Build time:   2020-06-30 06:32:47 UTC
Revision:     66bc713f7169626a7f0134bf452abde51550ea0a

Kotlin:       1.3.72
Groovy:       2.5.11
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          11.0.8 (Ubuntu 11.0.8+10-post-Ubuntu-0ubuntu120.04)
OS:           Linux 5.4.0-7642-generic amd64
```

**Additional context**

### PR DESCRIPTION
**Pull request by glefloch**
It looks like when no `src/main/java` is present, the kotlin task does not trigger the `compileJava`. 

This register the `build/classes/java/quarkus-generated-sources/grpc` directory in the main sourceset (it does the same thing for tests). 

The only thing that I don't like, is that I cannot load the provider name (e.g. grpc) dynamically has done in the extension. 

Also, I re enabled the `KotlinGRPCProjectBuildTest`, it pass on my machine and on the Release build Test job on my fork. 

close #12874

### CODE REVIEW

**Review by aloubyansky — APPROVED** [review]
Thanks @glefloch

**Comment by glefloch** [comment]
@michalszynkiewicz do you think you could have a look ?

File: devtools/gradle/src/main/java/io/quarkus/gradle/tasks/QuarkusGenerateCode.java [hunk 1]
```diff
@@ -29,6 +29,7 @@
 
     public static final String QUARKUS_GENERATED_SOURCES = "quarkus-generated-sources";
     public static final String QUARKUS_TEST_GENERATED_SOURCES = "quarkus-test-generated-sources";
+    public static final String[] CODE_GENERATION_PROVIDER = new String[] { "grpc" };
```
Comment (michalszynkiewicz) [inline devtools/gradle/src/main/java/io/quarkus/gradle/tasks/QuarkusGenerateCode.java:32]: could you add a `TODO` to get this list dynamically (if it's not easy enough to just do it ;) )?

**Comment by michalszynkiewicz** [comment]
@glefloch I added one comment. It would be great if the list could be "not hardcoded".
I know the kogito team is looking into using the code generation mechanism. In their case it wouldn't even live in the quarkus-core repository to my knowledge

**Comment by michalszynkiewicz** [comment]
But it could be done in a separate change.

**Review by michalszynkiewicz — APPROVED** [review]
