### PR TITLE
POST not working in dev mode

### LINKED ISSUE #3624: Request parameters not injected in POST/PUT REST methods
**Describe the bug**
When running the rest-json and hibernate-orm-resteasy quickstarts in dev mode, the `Fruit` param isn't injected, causing an NPE in the ORM example, causing null to be appended to the fruit list in the former. This only happens during dev mode, but not when running the actually built JAR. As per @gsmet, things work as expected on 0.21.1.

**Expected behavior**
The fruit parameter is injected also in dev mode.

**Actual behavior**
The fruit parameter is *not* injected  in dev mode.

**To Reproduce**
check out either example from master/develop, then run `mvn compile quarkus:dev`. Open localhost:8080/fruits.html (index.html for the ORM example) and observe how adding a fruit fails.

**Configuration**
See the repo.

**Screenshots**
n/a

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by stuartwdouglas**
Fixes #3624.

### CODE REVIEW

**Comment by geoand** [comment]
@stuartwdouglas seems like something broke with this PR

File: extensions/vertx-web/deployment/src/main/java/io/quarkus/vertx/web/deployment/devmode/VertxHotReplacementSetup.java [hunk 1]
```diff
@@ -35,26 +36,39 @@ void handleHotReplacementRequest(RoutingContext routingContext) {
...
+                            restart = hotReplacementContext.doScan(true);
+                        } catch (Exception e) {
+                            throw new IllegalStateException("Unable to perform hot replacement scanning", e);
+                        }
+                        nextUpdate = System.currentTimeMillis() + HOT_REPLACEMENT_INTERVAL;
+                    }
+                }
+                if (hotReplacementContext.getDeploymentProblem() != null) {
+                    handleDeploymentProblem(routingContext, hotReplacementContext.getDeploymentProblem());
+                    return;
```
Comment (cescoffier) [inline extensions/vertx-web/deployment/src/main/java/io/quarkus/vertx/web/deployment/devmode/VertxHotReplacementSetup.java]: you need to complete the promise.

Comment (cescoffier) [reply extensions/vertx-web/deployment/src/main/java/io/quarkus/vertx/web/deployment/devmode/VertxHotReplacementSetup.java]: It's not necessarily required because you don't have any completion handler.

File: extensions/vertx-web/deployment/src/main/java/io/quarkus/vertx/web/deployment/devmode/VertxHotReplacementSetup.java [hunk 2]
```diff
@@ -35,26 +36,39 @@ void handleHotReplacementRequest(RoutingContext routingContext) {
...
+        routingContext.vertx().executeBlocking(new Handler<Promise<Object>>() {
+            @Override
+            public void handle(Promise<Object> event) {
+                boolean restart = false;
+                synchronized (this) {
+                    if (nextUpdate < System.currentTimeMillis() || hotReplacementContext.isTest()) {
+                        try {
+                            restart = hotReplacementContext.doScan(true);
+                        } catch (Exception e) {
+                            throw new IllegalStateException("Unable to perform hot replacement scanning", e);
```
Comment (cescoffier) [inline extensions/vertx-web/deployment/src/main/java/io/quarkus/vertx/web/deployment/devmode/VertxHotReplacementSetup.java]: that should be reported to the promise.

Comment (cescoffier) [reply extensions/vertx-web/deployment/src/main/java/io/quarkus/vertx/web/deployment/devmode/VertxHotReplacementSetup.java]: should the request be resume in this case?

**Review by cescoffier — COMMENTED** [review]
It's mostly a question of taste. Generally, we report failures and completion with the passed promise and perform the user reporting action in the callback. Now, here it's not required as the callback is `null`.

**Comment by cescoffier** [comment]
@vietj can you have a quick look?

File: extensions/vertx-web/deployment/src/main/java/io/quarkus/vertx/web/deployment/devmode/VertxHotReplacementSetup.java (hunk 1 above)
Comment (vietj) [reply extensions/vertx-web/deployment/src/main/java/io/quarkus/vertx/web/deployment/devmode/VertxHotReplacementSetup.java]: ideally we should complete the promise and in the completion handler of execute blocking then resume the request

Comment (cescoffier) [reply extensions/vertx-web/deployment/src/main/java/io/quarkus/vertx/web/deployment/devmode/VertxHotReplacementSetup.java]: Much better! Thanks @stuartwdouglas

**Review by cescoffier — APPROVED** [review]
