### PR TITLE
Undeprecate 'quarkus.otel.traces.enabled' property

### LINKED ISSUE #49527: Undeprecate 'quarkus.otel.traces.enabled' property
### Describe the bug

The `quarkus.otel.traces.enabled' property is marked as deprecated, but there's no information like why it was deprecated and what's the intention. Moreover, in the [docs](https://quarkus.io/guides/opentelemetry#disable-all-or-parts-of-the-opentelemetry-extension), the property is listed there as the official way on how to disable OTel Traces. 

For Keycloak, we need to also disable OTel Traces if not explicitly turned on. Deprecating or even removing the property, we will not be able to control it. I like having the unified approach for OTel Logs, Metrics and Traces as `quarkus.otel.<component>.enabled`.

I'd consider this issue a bug as AFAIK there's no mention of deprecating it, or suggested different approach on how to control it. It kinda seems it was done unintentionally.

@brunobat Could you please check it? Thanks!

I'll provide a PR.

### Expected behavior

`quarkus.otel.traces.enabled` is NOT deprecated

### Actual behavior

`quarkus.otel.traces.enabled` is deprecated

### PR DESCRIPTION
**Pull request by mabartos**
- Closes #49527

@brunobat Could you please check it? Thanks!

Would it be possible to include it into Quarkus 3.27 LTS? Thanks!

### CODE REVIEW

**Comment by mabartos** [comment]
@brunobat @radcortez Any opinion on this? 

I'm just worried about deadlines for the 3.27 LTS, so sorry to urge you with this :)

**Comment by gsmet** [comment]
No need to worry. If it has to go in 3.26/27, it will go in them.

**Review by radcortez — APPROVED** [review]

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/config/build/TracesBuildConfig.java [hunk 1]
```diff
@@ -24,7 +24,6 @@ public interface TracesBuildConfig {
      * The OpenTelemetry SDK ( {@link io.quarkus.opentelemetry.runtime.config.build.OTelBuildConfig#enabled()} )
      * is enabled by default and if disabled, OpenTelemetry Tracing will also be disabled.
      */
-    @Deprecated
     @WithDefault("true")
     Optional<Boolean> enabled();
```
Comment (gastaldi) [inline extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/config/build/TracesBuildConfig.java:28]: This already has a default value, shouldn't it just return `boolean`?

Comment (mabartos) [reply extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/config/build/TracesBuildConfig.java:28]: Whatever works for you; I'm just interested to get rid of the nasty word 'Deprecated' :P

Comment (gsmet) [reply extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/config/build/TracesBuildConfig.java:28]: From what I can see it was introduced as deprecated from the beginning: https://github.com/quarkusio/quarkus/pull/30033/files#diff-1d0492b33fd8f99c29a0be782f3a5d7402dcf8771853aec0a3cc586c81509e55R28-R30

**Review by gsmet — APPROVED** [review]
I will merge this for now and we will rediscuss this with @brunobat when he's back.

**Comment by brunobat** [comment]
This is fine. 
I was considering this myself as well because when I added this, the OTel wiring was completely different and right now it makes more sense to keep it around.
