### PR TITLE
Fix Spring Data JPA case where 'First' was misinterpreted as Top query

### LINKED ISSUE #23771: Spring data JPA, can't find by FirstName
### Describe the bug

for a method like this:

findByLastNameContainingAndFirstNameContainingAndEmailContainingAllIgnoreCase

and we have this error:

### Expected behavior

It automatically implements the query

### Actual behavior

The given error is thrown:

Caused by: io.quarkus.spring.data.deployment.UnableToParseMethodException: Unable to parse query with limiting results clause.

### How to Reproduce?

1. Create a Quarkus Project: version 2.7.1

2. Follow the guide provided by quarkus on how to use the quarkus spring data extension

3. create an entity containing the field 
```java
String firstName;
```
4. try to compile

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

This line attempts to parse the field FirstName as a top like utility
(https://github.com/quarkusio/quarkus/blob/7aef8dfb215f2c7c75179de29f58d0c1d82368ec/extensions/spring-data-jpa/deployment/src/main/java/io/quarkus/spring/data/deployment/MethodNameParser.java#L99)

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #23771

### CODE REVIEW

File: extensions/spring-data-jpa/deployment/src/main/java/io/quarkus/spring/data/deployment/MethodNameParser.java [hunk 1]
```diff
@@ -97,18 +97,23 @@ public Result parse(MethodInfo methodInfo) {
...
-            try {
-                String topCountStr = methodName.substring(Math.max(firstIndex, topIndex), byIndex)
-                        .replace("Top", "").replace("First", "");
-                if (topCountStr.isEmpty()) {
-                    topCount = 1;
-                } else {
-                    topCount = Integer.valueOf(topCountStr);
+            int maxFirstAndTopIndex = Math.max(firstIndex, topIndex);
+            // 'First' and 'Top' could be part of a field name, so we only considering them as part of a top query
+            // if they are found be 'By'
```
Comment (famod) [inline extensions/spring-data-jpa/deployment/src/main/java/io/quarkus/spring/data/deployment/MethodNameParser.java:102]:
```suggestion
            // if they are found before 'By'
```
?

File: extensions/spring-data-jpa/deployment/src/main/java/io/quarkus/spring/data/deployment/MethodNameParser.java [hunk 2]
```diff
@@ -97,18 +97,23 @@ public Result parse(MethodInfo methodInfo) {
...
         int topIndex = methodName.indexOf("Top");
         if ((firstIndex != -1) || (topIndex != -1)) {
-            try {
-                String topCountStr = methodName.substring(Math.max(firstIndex, topIndex), byIndex)
-                        .replace("Top", "").replace("First", "");
-                if (topCountStr.isEmpty()) {
-                    topCount = 1;
-                } else {
-                    topCount = Integer.valueOf(topCountStr);
+            int maxFirstAndTopIndex = Math.max(firstIndex, topIndex);
```
Comment (famod) [inline extensions/spring-data-jpa/deployment/src/main/java/io/quarkus/spring/data/deployment/MethodNameParser.java:100]: Hum, what about something like `findTop3ByFirstName`?
`firstIndex` would be 10 and `topIndex` would be 4 , resulting in `maxFirstAndTopIndex` 10.
This in turn would _not_ match `maxFirstAndTopIndex < byIndex` and so no `topCount` would be parsed.
Am I missing something?

Comment (geoand) [reply extensions/spring-data-jpa/deployment/src/main/java/io/quarkus/spring/data/deployment/MethodNameParser.java:100]: Good point. I'll make the checks more robust

Comment (geoand) [reply extensions/spring-data-jpa/deployment/src/main/java/io/quarkus/spring/data/deployment/MethodNameParser.java]: Should be better now

File: extensions/spring-data-jpa/deployment/src/main/java/io/quarkus/spring/data/deployment/MethodNameParser.java [hunk 3]
```diff
@@ -97,18 +97,24 @@ public Result parse(MethodInfo methodInfo) {
...
         if ((firstIndex != -1) || (topIndex != -1)) {
-            try {
-                String topCountStr = methodName.substring(Math.max(firstIndex, topIndex), byIndex)
-                        .replace("Top", "").replace("First", "");
-                if (topCountStr.isEmpty()) {
-                    topCount = 1;
-                } else {
-                    topCount = Integer.valueOf(topCountStr);
+            int effectiveFirstOrTopIndex = (topIndex > -1 && firstIndex > -1) ? Math.max(topIndex, firstIndex)
+                    : Math.max(firstIndex, topIndex);
```
Comment (famod) [inline extensions/spring-data-jpa/deployment/src/main/java/io/quarkus/spring/data/deployment/MethodNameParser.java:101]: How is `Math.max(topIndex, firstIndex)` significantly different from `Math.max(firstIndex, topIndex)`?

This will still favor a "First" or "Top" in the back of the name instead of taking the very first one.
IMO `min()` is the right way, but with filtering out -1.

File: integration-tests/spring-data-jpa/src/main/resources/import.sql [hunk 4]
```diff
@@ -77,9 +77,10 @@ INSERT INTO unit(id, name) VALUES (1, 'Delivery Unit');
 INSERT INTO unit(id, name) VALUES (2, 'Sales and Marketing Unit');
 INSERT INTO team(id, name, unit_id) VALUES (10, 'Development Team', 1);
 INSERT INTO team(id, name, unit_id) VALUES (11, 'Sales Team', 2);
-INSERT INTO employee(id, user_id, first_name, last_name, team_id) VALUES (100, 'johdoe', 'John', 'Doe', 10);
-INSERT INTO employee(id, user_id, first_name, last_name, team_id) VALUES (101, 'petdig', 'Peter', 'Digger', 10);
-INSERT INTO employee(id, user_id, first_name, last_name, team_id) VALUES (102, 'stesmi', 'Stella', 'Smith', 11);
+INSERT INTO employee(id, user_id, first_name, last_name, team_id, email) VALUES (100, 'johdoe', 'John', 'Doe', 10, 'johdoe@acme.com');
+INSERT INTO employee(id, user_id, first_name, last_name, team_id, email) VALUES (101, 'petdig', 'Peter', 'Digger', 10, 'petdig@acme.com');
+INSERT INTO employee(id, user_id, first_name, last_name, team_id, email) VALUES (102, 'stesmi', 'Stella', 'Smith', 11, 'stesmi@acme.com');
+INSERT INTO employee(id, user_id, first_name, last_name, team_id, email) VALUES (100, 'jd', 'John', 'Doe', 12, 'jd@acme.com');
```
Comment (famod) [inline integration-tests/spring-data-jpa/src/main/resources/import.sql:83]: There is a mixup in ids here. `id` 100 is already taken and `team_id` 12 doesn't exist.

**Review by famod — COMMENTED** [review]
I'll push what I have in mind in a separte commit. We can then squash if we have agreed on a solution.

File: extensions/spring-data-jpa/deployment/src/main/java/io/quarkus/spring/data/deployment/MethodNameParser.java [hunk 5]
```diff
@@ -94,34 +94,29 @@ public Result parse(MethodInfo methodInfo) {
...
+                } else {
+                    topCount = Integer.valueOf(topCountStr);
                 }
+            } catch (Exception e) {
+                throw new UnableToParseMethodException(
+                        "Unable to parse query with limiting results clause. Offending method is "
+                                + repositoryMethodDescription + ".");
             }
         }
-        if ((topCount != null) && (queryType != QueryType.SELECT)) {
```
Comment (famod) [inline extensions/spring-data-jpa/deployment/src/main/java/io/quarkus/spring/data/deployment/MethodNameParser.java:114]: I moved this up into the `minFirstOrTopIndex < byIndex` block because that's the ony place where `topCount` is set to something != null.

Comment (geoand) [reply extensions/spring-data-jpa/deployment/src/main/java/io/quarkus/spring/data/deployment/MethodNameParser.java:114]: Sounds good

**Review by famod — APPROVED** [review]
Squash and merge as you will. 🙂
