### PR TITLE
Core: ignore attempts to on-demand index primitive types and arrays

### LINKED ISSUE #37452: "Failed to index long" warning in MongodbPanacheTransactionTest
When running `MongodbPanacheTransactionTest`, we end up with the following warning:

```
[INFO] Running io.quarkus.it.mongodb.panache.transaction.MongodbPanacheTransactionTest
2023-12-01 14:26:59,905 WARN  [io.qua.dep.ste.CombinedIndexBuildStep] (build-5) Failed to index long: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: TEST for MongodbPanacheTransactionTest (QuarkusTest)@11cdf948
```

The warning is in fact coming from `IndexWrapper` (I will fix the logger in an upcoming PR) but I think we should try to get rid of it.
I don't know if it's something I should fix in the MongoDB Panache extension or if it's something that we should take care of globally at the Quarkus level.

It could be by indexing all the primitive types? Or ignoring them when trying to index?

/cc @Ladicek @mkouba

### PR DESCRIPTION
**Pull request by Ladicek**
This is to avoid a warning log message in cases that cannot possibly succeed; there are no class files for primitive types and arrays.

Also fix the logger name in `IndexWrapper`.

Fixes #37452

### CODE REVIEW

File: core/deployment/src/main/java/io/quarkus/deployment/index/IndexWrapper.java [hunk 1]
```diff
@@ -35,6 +35,16 @@ public class IndexWrapper implements IndexView {
 
     private static final Logger LOGGER = Logger.getLogger(CombinedIndexBuildStep.class);
```
Comment (gsmet) [inline core/deployment/src/main/java/io/quarkus/deployment/index/IndexWrapper.java:36]:
```suggestion
    private static final Logger LOGGER = Logger.getLogger(IndexWrapper.class);
```

**Review by gsmet — COMMENTED** [review]
If you could fix that, that would be awesome. It was confusing at first.

File: core/deployment/src/main/java/io/quarkus/deployment/index/IndexWrapper.java (hunk 1 above)
Comment (Ladicek) [reply core/deployment/src/main/java/io/quarkus/deployment/index/IndexWrapper.java:36]: Ah sure!

Comment (Ladicek) [reply core/deployment/src/main/java/io/quarkus/deployment/index/IndexWrapper.java]: Done.

**Review by gsmet — APPROVED** [review]
Cool, thanks!
