### PR TITLE
Fix Otel logging message formatting

### LINKED ISSUE #44440: Replacement in logs (log formatting) doesn't work in OpenTelemetry Logging
### Describe the bug

Logs are not resolved when using `MessageFormat` variant of logs. Using `String.format` variant works as expected:
```java
var replacement = "replaced!";
Log.infov("infov {0}", replacement); // results in OpenTelemetry log message "infov {0}"
Log.infof("infof %s", replacement); // results in OpenTelemetry log message "infov replaced!"
```

### Expected behavior

`Log.infov` produces formatted messages in OpenTelemetry logs.

### Actual behavior

Format string (template) is being sent to OpenTelemetry.

### How to Reproduce?

Attached quick start example may be used as a reproducer.

1. start the application in dev mode
2. call the endpoint http://localhost:8080/hello
3. check logs in Grafana dev service

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

3.16.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

Reproducer:
[opentelemetry-quickstart.zip](https://github.com/user-attachments/files/17715888/opentelemetry-quickstart.zip)

### PR DESCRIPTION
**Pull request by brunobat**
Fixes https://github.com/quarkusio/quarkus/issues/44440

### CODE REVIEW

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/logs/OpenTelemetryLogHandler.java [hunk 1]
```diff
@@ -52,7 +53,15 @@ protected void doPublish(ExtLogRecord record) {
         }
 
         if (record.getMessage() != null) {
-            logRecordBuilder.setBody(record.getMessage());
+            // Get the message
+            final Formatter formatter = getFormatter();
+            String logMsg;
+            if (formatter != null) {
```
Comment (dmlloyd) [inline extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/logs/OpenTelemetryLogHandler.java:59]: Under what circumstances would the formatter be `null`?

**Review by dmlloyd — APPROVED** [review]

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/logs/OpenTelemetryLogHandler.java (hunk 1 above)
Comment (ylemoigne) [reply extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/logs/OpenTelemetryLogHandler.java:59]: here, it is always null. OpenTelemetryLogRecorder doesn't set any formatter and output is not formatted

Comment (brunobat) [reply extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/logs/OpenTelemetryLogHandler.java:59]: Have you enabled OTel Logs with `quarkus.otel.logs.enabled=true`?

Comment (ylemoigne) [reply extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/logs/OpenTelemetryLogHandler.java:59]: Yes. Excuse me, i was not clear. I have otel log enable and working. I was looking at code because I was not able to setup the otel log pattern like with `quarkus.log.console.format`.

The formatting as expressed in https://github.com/quarkusio/quarkus/issues/44440 is done, because `logMsg = record.getFormattedMessage();` do it.

But the `getFormatter()` will always be null. At least when I run in debug, the formatter is null and I did not find any code setting it. The OpenTelemetryLogRecorder at least to not set formatter after OpenTelemetryLogHandler instanciation as other logging recorder do (`LoggingSetupRecorder.configureSocketHandler` or `LoggingSetupRecorder.configureSyslogHandler` for example).

So it seems impossible for now to format the log sended to otel collector.

Comment (brunobat) [reply extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/logs/OpenTelemetryLogHandler.java:59]: Not sure if I understand. The logged message is just another attribute of the OTel Log entry.
Anything that you could set in with formatter is probably on the log entry already... This is structured logging.
What kind of formatting would you like to do? Can you please provide an example?

Comment (ylemoigne) [reply extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/logs/OpenTelemetryLogHandler.java:59]: In the otel log, the logger name is not in the structure. I have `code_namespace` that's the class where the logger is invoked, and
`log_logger_namespace:org.slf4j.impl.Slf4jLogger` but I don't have the logger name, so I was trying to work around this.

Comment (brunobat) [reply extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/logs/OpenTelemetryLogHandler.java:59]: The logger name is open for debate in the OTel Semantic Conventions: https://github.com/open-telemetry/semantic-conventions/issues/1550

We can add a new attribute for it but it might change in the future. Also, most times `code_namespace` and `logger_name`will have the same values.

Will create a PR.

Comment (brunobat) [reply extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/logs/OpenTelemetryLogHandler.java:59]: created this: https://github.com/quarkusio/quarkus/pull/47454

Comment (ylemoigne) [reply extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/logs/OpenTelemetryLogHandler.java:59]: Cool. Thanks you. :)
