### PR TITLE
Fix @ApplicationScoped ValueExtractors

### LINKED ISSUE #20375: Hibernate Validator: `@ApplicationScoped` custom `ValueExtractor` bean lead to `ValueExtractorDefinitionException`
### Describe the bug

Even after we fix #20347, custom `ValueExtractor` implementations provided as CDI beans can only have the `@Singleton` scope or `@Dependent` pseudo-scope. Any scope requiring instantiation will lead to an exception on startup complaining about "parallel definitions of value extractors on a given class", even though that's not the case.

### Expected behavior

A value extractor annotated with `@ApplicationScoped` should be correctly added to the `ValidatorFactory`, and be used automatically to constraints on extracted elements (e.g. `Container<@NotBlank String>`).

### Actual behavior

Exception on startup:

```
java.lang.ExceptionInInitializerError
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at io.quarkus.runner.bootstrap.StartupActionImpl.run(StartupActionImpl.java:215)
        at io.quarkus.test.QuarkusUnitTest.beforeAll(QuarkusUnitTest.java:509)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$10(ClassBasedTestDescriptor.java:381)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:381)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:205)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:80)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:148)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
        at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
        at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:188)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:154)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:128)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
        at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
Caused by: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:236)
        ... 46 more
Caused by: javax.validation.valueextraction.ValueExtractorDefinitionException: HV000218: Having parallel definitions of value extractors on a given class is not allowed: io.quarkus.hibernate.validator.test.valueextractor.ApplicationScopedCustomValueExtractorTest_ApplicationScopedContainerValueExtractor_ClientProxy.
        at org.hibernate.validator.internal.engine.valueextraction.ValueExtractorDescriptor.getValueExtractorDefinition(ValueExtractorDescriptor.java:142)
        at org.hibernate.validator.internal.engine.valueextraction.ValueExtractorDescriptor.<init>(ValueExtractorDescriptor.java:45)
        at org.hibernate.validator.internal.engine.AbstractConfigurationImpl.addValueExtractor(AbstractConfigurationImpl.java:271)
        at org.hibernate.validator.internal.engine.AbstractConfigurationImpl.addValueExtractor(AbstractConfigurationImpl.java:80)
        at io.quarkus.hibernate.validator.runtime.HibernateValidatorRecorder$2.created(HibernateValidatorRecorder.java:143)
        at io.quarkus.arc.runtime.ArcRecorder.initBeanContainer(ArcRecorder.java:70)
        at io.quarkus.deployment.steps.ArcProcessor$generateResources-1025303321.deploy_0(ArcProcessor$generateResources-1025303321.zig:128)
        at io.quarkus.deployment.steps.ArcProcessor$generateResources-1025303321.deploy(ArcProcessor$generateResources-1025303321.zig:40)
        at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:194)
        ... 46 more
```

### How to Reproduce?

I'm going to add a disabled test as part of the PR for #20347. Look for `ApplicationScopedCustomValueExtractorTest` in the codebase.

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.3.0.CR1, f0aba8594140c708c7c477d3b1efd4a0b29a3095

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

I believe the cause is a bug in `org.hibernate.validator.internal.engine.valueextraction.ValueExtractorDescriptor#determineValueExtractorDefinitions`. It gets passed the proxy class, which extends the actual implementation class. And for some reason, when passed a class that extends another class that implements `ValueExtractor`, it behaves as if `ValueExtractor` was implemented multiple times, both by the superclass and the subclass.

It seems caused by the fact that `java.lang.Class#getAnnotatedInterfaces` returns annotated interfaces of the class **and its superclasses**, which means `determineValueExtractorDefinitions` should not be walking through superclasses to collect all annotated interfaces (when it does, it collects duplicates).

### PR DESCRIPTION
**Pull request by yrodiere**
Fixes #20375.

It turns out the problem was how we generate class signatures in client proxies.

"class signatures" are the metadata in Java classes that provides un-erased type information, such as type parameters for implemented interfaces. See https://docs.oracle.com/javase/specs/jvms/se14/html/jvms-4.html#jvms-4.7.9.1 for more information.

Some time ago, we had to add some feature to generate those class signatures in generated client proxies. IIUC, the hack was necessary for Kotlin class generation. See https://github.com/quarkusio/quarkus/pull/10769#issuecomment-683694819 for more information.

However, that signature generation was incorrect: it was essentially copy-pasting the signature of the parent (proxied) class. Consequently, the generic info of the proxy class was identical to that of the proxied class. If the parent class implemented `ValueExtractor<List<?>>`, then the signature of the proxied class looked as if the proxied class implemented that interface directly, too. Which is incorrect.

It gets worse, though: the proxied class appeared as if it implemented that interface... but only when querying generic-aware methods, such as `getAnnotatedInterfaces()`. When querying non-generic-aware methods, such as `getInterfaces()`, it would appear that the proxied class did *not* implement `ValueExtractor`, at least not directly.

As you can imagine, that was a lot of fun to debug.

This PR changes signature generation for client proxy classes so that:

1. We only generate a signature if the proxied class/interface has type parameters: this means the proxy class will have type parameters as well (at least it should have), and also that it will extend/implement a parameterized version of the proxied class.
2. Whenever we generate a proxy for `class MyClass<T> implements SomeInterface<T>`, the generated proxy has a signature that matches a declaration similar to `class MyClass_ClientProxy<T> extends MyClass<T>`. That will, at least, be consistent with the non-generic-aware class metadata.

In the case of Hibernate Validator, a value extractor declared as `MyExtractor implements ValueExtractor<List<?>>` will yield a proxy without any signature at all, since the proxy does not need type parameters and `MyExtractor` cannot be parameterized. Thus the Hibernate Validator test now passes.

Let's see if it's enough to make all tests added in #10769 pass.

### CODE REVIEW

**Comment by yrodiere** [comment]
Note : this PR is based on  #20382, which should be merged first. I will mark this one as draft in the meantime, even though CI passes just fine.

**Comment by yrodiere** [comment]
#20382 has been merged; I rebased this PR on `main` and marked as ready for review.

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/AsmUtilCopy.java [hunk 1]
```diff
@@ -224,21 +211,6 @@ private static void toSignature(StringBuilder sb, List<TypeVariable> typeParamet
             sb.append(">");
     }
 
-    /**
-     * Returns true if the given class has type parameters or if its superclass or superinterfaces require a signature
-     */
-    public static boolean needsSignature(ClassInfo klass) {
```
Comment (gsmet) [inline independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/AsmUtilCopy.java:230]: Do we really need to remove this method? It looks orthogonal to the issue at hand?

But I'll let @mkouba decide about all this anyway.

Comment (yrodiere) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/AsmUtilCopy.java:230]: It's not orthogonal; it was used in `ClientProxyGenerator` to know whether we need to create a signature for a proxy. We used to pass the proxied class as a parameter. But that was wrong: a proxy class needing a signature is not the same as its parent class needing a signature.

For example:

```java
class MyClass implements Supplier<Integer> {
}

class MyClass_Proxy extends MyClass {
}
```

The proxied class (`MyClass`) needs a signature, since it extends a parameterized type, but the proxy class (`MyClass_Proxy`) doesn't.

Since this method was being misused, and the only use was in `ClientProxyGenerator`, and it very much looks like internal code, I think it should be removed.

**Comment by yrodiere** [comment]
The test failure in the MicroProfile TCK seems unrelated; I certainly cannot reproduce it locally. I rebased on `main` and force-pushed, let's see if it happens again.

**Comment by mkouba** [comment]
I'll let @FroMage review this one as he's the author of the original code.

**Review by gsmet — APPROVED** [review]
I had a closer look and the changes make sense to me.

Let's wait a few days to see if @FroMage has some feedback. If not, I'll merge.
