### PR TITLE
Always start dev services before getting the dev services properties

### LINKED ISSUE #49208: KafkaCompanion no longer works with DevServices (3.25.0)
### Describe the bug

KafkaCompanion, which is initialized via `@WithTestResource(value = KafkaCompanionResource.class)`, no longer works correctly since upgrading from Quarkus 3.24.5 to 3.25.0.

On the one hand, the “CommonClientConfig” is no longer completely filled, and on the other hand, additional TestContainers are started.

It appears that the property “kafka.bootstrap.servers” is not set correctly from the perspective of [KafkaCompanionResource](https://github.com/quarkusio/quarkus/blob/main/test-framework/kafka-companion/src/main/java/io/quarkus/test/kafka/KafkaCompanionResource.java#L30), and it therefore ignores the started DevServices.

Reproducer for the issue: https://github.com/vonatzigenc/reproducer_quarkus_kafka_companion

### Expected behavior

KafkaCompanion is initialized correctly for DevServices.

### Actual behavior

- KafkaCompanion is not initialized correctly for DevServices.
- In addition to DevServices, a “quay.io/strimzi-test-container/test-container:0.109.2-kafka-3.9.0” is started.

### How to Reproduce?

Preproducer repo: https://github.com/vonatzigenc/reproducer_quarkus_kafka_companion#

- Reproducer is based on [kafka-avro-schema-quickstart](https://github.com/quarkusio/quarkus-quickstarts/tree/main/kafka-avro-schema-quickstart) with added quarkus-test-kafka-companion and simplified test
- Execute [MovieWithKafkaCompanionTest](https://github.com/vonatzigenc/reproducer_quarkus_kafka_companion/blob/main/src/test/java/org/acme/kafka/MovieWithKafkaCompanionTest.java)

(With downgrade to 3.24.5 the test is green

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

openjdk version "21.0.7" 2025-04-15 LTS

### Quarkus version or git rev

3.25.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by holly-cummins**
Resolves https://github.com/quarkusio/quarkus/issues/49208

This builds on @vonatzigenc's fix, and generalises it. When calling code asks for dev services properties, we should always make sure dev services are started by that point. If nothing asks for those properties, we should start dev services as the first step of the startup sequence. 

This does have the ickiness that the getter method has side effects, and it also means it's a bit loosely-defined when dev services start. The alternative was to have calling code explicitly request dev services be started before calling the getter. On balance, I decided that was more risky. 

I was surprised that we didn't catch this, since the original code broke a quickstart. I haven't investigated that yet, to see if there's anything we can do, but I did add a couple of tests in the main repo which show the problem.

### CODE REVIEW

**Comment by Sanne** [comment]
no strong objections, but I'd be a bit concerned that going forward we might have situations in which some code (inadvertently or not) triggers starting of services which aren't actually necessary?  That could become a painful UX, and not necessarily propagate the feedback to us.

What about throing an exception if the getter is triggered but the state of the services isn't valid? It might be more irky to develop with, but we'd benefit from such guidance during development of extensions, or worst case we'd get actionable bug reports.

**Comment by holly-cummins** [comment]
> no strong objections, but I'd be a bit concerned that going forward we might have situations in which some code (inadvertently or not) triggers starting of services which aren't actually necessary? That could become a painful UX, and not necessarily propagate the feedback to us.

I know what you mean, but I think that's not too much of a concern. In the old model, all dev services would have been started in the augmentation phase. In the new model, all dev services get started as the first step of `run()`. So in the old model, we *always* would have started dev services before the `getDevServicesProperties` method was available. In the new model, you'd only get unnecessary dev services start if an augmentation was run without any intention of starting an application (which is kind of weird anyway), and then after running the augmentation, calling code wanted to know dev services properties that could only be read after dev service startup, but wanted all the dev services to stay stopped. In that situation, I think the calling code deserves what it gets. :) 

> What about throing an exception if the getter is triggered but the state of the services isn't valid? It might be more irky to develop with, but we'd benefit from such guidance during development of extensions, or worst case we'd get actionable bug reports.

Developers of extensions shouldn't be calling the method on `StartupAction`, I don't think (although it may be exposed to them). So the complexity worry is more than we have about five different start paths internally, all subtly different. Making it harder to reliably start Quarkus (by forcing calling code to explicitly start dev services as well as starting the application) increases the risk of things falling through our testing and getting into situations where on some paths, dev services that should have been started weren't started.

**Comment by Sanne** [comment]
thanks Holly - that all makes sense, looks like my mental model of the internals is way out of date :)

Still it irks me a bit that an "innocently looking getter" would have such a wild side-effect as e.g. having to wait minutes to start some heavy weight DBs - wondering if that should be made more explicit.

**Comment by holly-cummins** [comment]
> Still it irks me a bit that an "innocently looking getter" would have such a wild side-effect as e.g. having to wait minutes to start some heavy weight DBs - wondering if that should be made more explicit.

Yeah, I know what you mean. I wondered about something like a method called `initialiseDevServicesProperties` which returns the properties, and `initialiseDevServicesNetworkId` to return the properties. But then that's a bit confusing for the case where they're no-op getters (and one of those two methods always would be). So it could get be `getOrInitialiseDevServicesProperties` and `getOrInitialiseDevServicesNetworkId`, which is correct, but awkwardly verbose. But maybe correct is the most important thing. WDYT?

**Comment by Sanne** [comment]
> But maybe correct is the most important thing.

+1

**Comment by holly-cummins** [comment]
> > But maybe correct is the most important thing.
> 
> +1

Ok, done! The other disadvantage is that it makes the changeset bigger and changes an interface, but that should be ok.

File: core/deployment/src/main/java/io/quarkus/runner/bootstrap/StartupActionImpl.java [hunk 1]
```diff
@@ -58,6 +58,7 @@ public class StartupActionImpl implements StartupAction {
     private final String mainClassName;
     private final String applicationClassName;
     private final Map<String, String> devServicesProperties;
+    private volatile boolean devServicesStarted = false;
```
Comment (Sanne) [inline core/deployment/src/main/java/io/quarkus/runner/bootstrap/StartupActionImpl.java:61]: should we also have any guard to not start the services concurrently?

Comment (holly-cummins) [reply core/deployment/src/main/java/io/quarkus/runner/bootstrap/StartupActionImpl.java:61]: Hm, I see your point. I assumed the boolean would be enough, but I suppose it technically isn't. Simultaneous start attempts would only happen if tests are run in parallel which we don't support, but we know people do run tests that way, and it mostly works, so we don't want to regress it. 

On the other hand, we don't have any guard to prevent starting the application concurrently, which would be a lot worse, and would (I think) be a risk in the scenario I just described. So maybe that shows there isn't a problem?

Comment (Sanne) [reply core/deployment/src/main/java/io/quarkus/runner/bootstrap/StartupActionImpl.java:61]: ok

**Review by Sanne — APPROVED** [review]
