### PR TITLE
Null normal scoped producers throw IllegalProductException

### LINKED ISSUE #3829: Normal scoped producer method that returns null value at runtime should throw IllegalProductException
See https://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#producer_method.

### PR DESCRIPTION
**Pull request by mkouba**
- resolves #3829

### CODE REVIEW

File: independent-projects/arc/tests/src/test/java/io/quarkus/arc/test/producer/illegal/IllegalProducerTest.java [hunk 1]
```diff
@@ -0,0 +1,59 @@
...
+import io.quarkus.arc.test.ArcTestContainer;
+
+public class IllegalProducerTest {
+
+    @Rule
+    public ArcTestContainer container = new ArcTestContainer(IllegalProducer.class);
+
+    @Test
+    public void testNormalScopedProducerMethodReturnsNull() {
+        Serializable serializable = Arc.container().instance(Serializable.class).get();
```
Comment (mkouba) [inline independent-projects/arc/tests/src/test/java/io/quarkus/arc/test/producer/illegal/IllegalProducerTest.java]: @gastaldi Note that the invocation of `Instance.get()` does not result in `IllegalProductException` because the producers are called lazily. In other words, a proxy is returned and the producer is invoked when a proxy method is called -> a proxy is required to lookup the current bean instance per each invocation. This behavior is the same as in Weld.

**Comment by gastaldi** [comment]
Thanks for picking this ;) LGTM

**Review by manovotn — APPROVED** [review]

**Comment by manovotn** [comment]
@mkouba apparently you have commited the crime of not sorting the imports ;)

**Comment by mkouba** [comment]
Oops. I need to stop using auto-imports in my IDE ;-)
