### PR TITLE
OpenAPI build failure with mp.openapi.scan.packages

### LINKED ISSUE #53471: Index does not contain the annotation definition: `io.quarkus.security.PermissionsAllowed`
### Describe the bug

Im trying to update some apps from Quarkus 3.34.1 to 3.34.2 and they all fail to build with the following exception:

```
Caused by: java.lang.IllegalArgumentException: Index does not contain the annotation definition: io.quarkus.security.PermissionsAllowed
        at org.jboss.jandex.Index.getAnnotationsWithRepeatable(Index.java:343)
        at org.jboss.jandex.CompositeIndex.getAnnotationsWithRepeatable(CompositeIndex.java:87)
        at org.jboss.jandex.CompositeIndex.getAnnotationsWithRepeatable(CompositeIndex.java:87)
        at org.jboss.jandex.CompositeIndex.getAnnotationsWithRepeatable(CompositeIndex.java:87)
        at io.smallrye.openapi.runtime.scanner.FilteredIndexView.getAnnotationsWithRepeatable(FilteredIndexView.java:335)
        at io.quarkus.security.spi.SecurityTransformerBuildItem$SecurityTransformerImpl.getAnnotations(SecurityTransformerBuildItem.java:488)
        at io.quarkus.security.spi.SecurityTransformerBuildItem$SecurityTransformerImpl.getAnnotationsWithRepeatable(SecurityTransformerBuildItem.java:359)
        at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor$2.getAnnotationsWithRepeatable(SmallRyeOpenApiProcessor.java:1564)
        at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.getPermissionsAllowedMethodReferences(SmallRyeOpenApiProcessor.java:876)
        at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.getAuthorizedMethods(SmallRyeOpenApiProcessor.java:824)
        at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.getOperlter(SmallRyeOpenApiProcessor.java:805)
        at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.lambda$addAutoFilters$10(SmallRyeOpenApiProcessor.java:589)
        at java.base/java.util.HashMap.forEach(HashMap.java:1430)
        at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.addAutoFilters(SmallRyeOpenApiProcessor.java:575)
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:735)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:898)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:242)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2651)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2630)
        at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1622)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1589)
        at java.base/java.lang.Thread.run(Thread.java:1474)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

Create an app on https://code.quarkus.io/

Add the following extensions:
- quarkus-rest
- quarkus-smallrye-openapi

Check that it works with `quarkus dev`

Next update it from 3.34.1 to 3.34.2 and you will see the exception in dev mode.

### Output of `uname -a` or `ver`

`Darwin Willem-Jans-MBP 25.4.0 Darwin Kernel Version 25.4.0: Thu Mar 19 19:33:25 PDT 2026; root:xnu-12377.101.15~1/RELEASE_ARM64_T6041 arm64`

### Output of `java -version`

`openjdk 25.0.2 2026-01-20 LTS`

### Quarkus version or git rev

`3.34.2`

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

`Apache Maven 3.9.12 (848fbb4bf2d427b72bdb2471c22fced7ebd9a7a1)`

### Additional information

cc @phillip-kruger

### PR DESCRIPTION
**Pull request by phillip-kruger**
When `mp.openapi.scan.packages` is configured, the `FilteredIndexView` only includes classes from the specified packages. When `getAnnotationsWithRepeatable()` is called, Jandex needs to resolve the annotation class definition in the index to find its `@Repeatable` container. If the scan packages filter excludes the annotation's package (e.g. `io.quarkus.security`), Jandex throws `IllegalArgumentException: Index does not contain the annotation definition`.

Instead of relying on Jandex's `getAnnotationsWithRepeatable()` (which requires the annotation definition in the index), directly look for both `@PermissionsAllowed` and its `@PermissionsAllowed.List` container by name, unwrapping nested instances with proper target propagation. This avoids the index dependency entirely.

- Fixes: #53471

### CODE REVIEW

File: extensions/smallrye-openapi/deployment/src/main/java/io/quarkus/smallrye/openapi/deployment/SmallRyeOpenApiProcessor.java [hunk 1]
```diff
@@ -1560,13 +1560,14 @@ public Collection<AnnotationInstance> getAnnotations(DotName securityAnnotationN
 
             @Override
             public Collection<AnnotationInstance> getAnnotationsWithRepeatable(DotName securityAnnotationName) {
-                if (securityTransformer != null) {
-                    return securityTransformer.getAnnotationsWithRepeatable(securityAnnotationName);
-                }
-                // the annotation definition may not be in the index if the security extension is not on the classpath
+                // the annotation definition may not be in the index if the security extension is not on the
```
Comment (michalvavrik) [inline extensions/smallrye-openapi/deployment/src/main/java/io/quarkus/smallrye/openapi/deployment/SmallRyeOpenApiProcessor.java]: I don't understand this comment - how is it possible that if the security extension is not on the classpath, there is `SecurityTransformerBuildItem` which is only produced by the security extension? have you investigated what produces it?

Comment (michalvavrik) [reply extensions/smallrye-openapi/deployment/src/main/java/io/quarkus/smallrye/openapi/deployment/SmallRyeOpenApiProcessor.java]: I am referring to the `if (securityTransformer != null)` when it is evaluated as a `true`.

And if the scanning path changes what is in your index, you cannot reliably show secured paths, but that could be alright, as long as users are aware - maybe some warning?

**Review by michalvavrik — APPROVED** [review]
That makes much more sense to me, thanks for the fix. IIRC when `PermissionsAllowed` is used as a repeatable, OpenAPI doesn't handle it correctly unless Mike fixed it in the meanwhile, so this PR is basically just about avoiding the build-time failure.

File: extensions/smallrye-openapi/deployment/src/main/java/io/quarkus/smallrye/openapi/deployment/SmallRyeOpenApiProcessor.java [hunk 2]
```diff
@@ -545,6 +545,13 @@ public boolean accepts(DotName className) {
 
                 return false;
             }
+
+            @Override
+            public Collection<AnnotationInstance> getAnnotationsWithRepeatable(DotName name, IndexView annotationIndex) {
+                // Use the unfiltered composite index for annotation definition lookup, so that
+                // @Repeatable containers can be resolved even when mp.openapi.scan.packages is set
+                return super.getAnnotationsWithRepeatable(name, compositeIndex);
```
Comment (Ladicek) [inline extensions/smallrye-openapi/deployment/src/main/java/io/quarkus/smallrye/openapi/deployment/SmallRyeOpenApiProcessor.java]: This doesn't seem right. You don't know what `annotationIndex` the caller passed. I _assume_ the caller typically only has access to the filtered index, in which case the `compositeIndex` is the right index to use, but that's heavily dependent on the usage patterns. To me, it would feel better to include the `compositeIndex` in the `OpenApiFilteredIndexViewBuildItem`, which would give callers access to the right index to use when calling `getAnnotationsWithRepeatable()`.

But I'm not familiar with this part of the code base, like, at all, so I can't really object.

Comment (michalvavrik) [reply extensions/smallrye-openapi/deployment/src/main/java/io/quarkus/smallrye/openapi/deployment/SmallRyeOpenApiProcessor.java]: If users do `io.smallrye.openapi.runtime.scanner.FilteredIndexView#getAnnotations` they are already using the composite index, aren't they? In which case, how does it make sense to use a different index for the repeatable?

Comment (Ladicek) [reply extensions/smallrye-openapi/deployment/src/main/java/io/quarkus/smallrye/openapi/deployment/SmallRyeOpenApiProcessor.java]: `getAnnotations()` doesn't need an external index for looking up the annotation class, unlike `getAnnotationsWithRepeatable()`.

If the expected usage pattern is that the `annotationIndex` here is `this` (i.e. the filtered index), we could at least do:

```java
if (annotationIndex == this) {
    annotationIndex = compositeIndex;
}
```

and then pass `annotationIndex` as before, allowing callers to pass a _different_ index.

But as I mentioned above, I'm not familiar with this part of the code base at all, so feel free to ignore me.

Comment (michalvavrik) [reply extensions/smallrye-openapi/deployment/src/main/java/io/quarkus/smallrye/openapi/deployment/SmallRyeOpenApiProcessor.java]: > getAnnotations() doesn't need an external index for looking up the annotation class, unlike getAnnotationsWithRepeatable().

Yes, it is clear it is a different result, but think about it what is it doing - you are just searching annotations and you want them from a different index than non-repeatable? The fact it accepts the index as method param is just your design choice for repeatable annotations (or default annotation values), semantically, when I do `getAnnotations` I expect to get same results as for `getAnnotationsWithRepeatable` unless I am doing something unusual. 

I am not familiar either, so I'll not comment or review further. I am most likely wrong anyway.

Comment (Ladicek) [reply extensions/smallrye-openapi/deployment/src/main/java/io/quarkus/smallrye/openapi/deployment/SmallRyeOpenApiProcessor.java]: The design choice here is not that `getAnnotationsWithRepeatable()` accepts an index from the outside. The design choice is that Jandex indices represent incomplete classpaths. Literally all of them (or a vast majority) out there contain references to types they don't contain. From Jandex perspective, you can't know if the index you're calling `getAnnotationsWithRepeatable()` on includes the declaration of the repeatable annotation, but you _need_ the declaration (unlike non-repeatable annotations). Therefore, you must accept an index from the outside.

Now, in Quarkus, we're in a different position. Our combined index still doesn't include a complete classpath (because at the very least, it doesn't include the JDK), but it should contain most of it. The bean archive index is in a similar situation. If you can guarantee that the combined index or the bean archive index contain declarations of all annotations you can ever ask for through this filtered index, this change is correct. I don't know if you can guarantee that.

EDIT: I think we can actually guarantee that _if we use the computing index_, but I don't think we do. See `CombinedIndexBuildItem.getIndex()` vs. `CombinedIndexBuildItem.getComputingIndex()`.

Comment (michalvavrik) [reply extensions/smallrye-openapi/deployment/src/main/java/io/quarkus/smallrye/openapi/deployment/SmallRyeOpenApiProcessor.java]: Thanks for the context regarding `getAnnotationsWithRepeatable` index.I definitely can't answer what is expected here. I just wanted it to be noted that if we find other security annotations (which are not repeatable) like `Authenticated`, it is strange to make a difference to the repeatable security annotations. I'll leave this to others.

\cc  @MikeEdgar

File: extensions/smallrye-openapi/deployment/src/main/java/io/quarkus/smallrye/openapi/deployment/SmallRyeOpenApiProcessor.java [hunk 3]
```diff
@@ -1563,7 +1570,7 @@ public Collection<AnnotationInstance> getAnnotationsWithRepeatable(DotName secur
                 if (securityTransformer != null) {
                     return securityTransformer.getAnnotationsWithRepeatable(securityAnnotationName);
                 }
-                // the annotation definition may not be in the index if the security extension is not on the classpath
+                // the annotation definition may not be in the index
```
Comment (MikeEdgar) [inline extensions/smallrye-openapi/deployment/src/main/java/io/quarkus/smallrye/openapi/deployment/SmallRyeOpenApiProcessor.java]: Given that there is some uncertainty around which index is being used where, I wonder whether the OpenAPI processor should just solve for `@PermissionsAllowed` and `@PermissionsAllowed.List` by directly looking for both and unwrapping the contents of the list, if found.

```suggestion
                // the annotation definition may not be in the index or visible when MicroProfile filter options are in use, e.g. `mp.openapi.scan.*`.
```

File: extensions/smallrye-openapi/deployment/src/main/java/io/quarkus/smallrye/openapi/deployment/SmallRyeOpenApiProcessor.java (hunk 2 above)
Comment (MikeEdgar) [reply extensions/smallrye-openapi/deployment/src/main/java/io/quarkus/smallrye/openapi/deployment/SmallRyeOpenApiProcessor.java]: Longer term solution, but would it make sense to overload `getAnnotationsWithRepeatable` with another version that takes the `DotName` of the container annotation, allowing the lookup to side-step the index dependency? Basically, promote the private `getRepeatableAnnotations` method to from `Index` to the `IndexView` interface. That would help in cases where the container annotation name is already known, which might be a lot of them.

File: extensions/smallrye-openapi/deployment/src/main/java/io/quarkus/smallrye/openapi/deployment/SmallRyeOpenApiProcessor.java [hunk 4]
```diff
@@ -1563,11 +1581,20 @@ public Collection<AnnotationInstance> getAnnotationsWithRepeatable(DotName secur
...
+                for (AnnotationInstance container : index.getAnnotations(containerName)) {
+                    AnnotationValue value = container.value();
+                    if (value != null) {
+                        for (AnnotationInstance nested : value.asNestedArray()) {
+                            results.add(AnnotationInstance.create(nested.name(), container.target(), nested.values()));
+                        }
+                    }
                 }
-                return index.getAnnotationsWithRepeatable(securityAnnotationName, index);
+                return results;
```
Comment (MikeEdgar) [inline extensions/smallrye-openapi/deployment/src/main/java/io/quarkus/smallrye/openapi/deployment/SmallRyeOpenApiProcessor.java]: Can this simply be `return index.getAnnotationsWithRepeatable(securityAnnotationName, index);` since `index` here should be the `FilteredIndexView` with the same logic?

File: extensions/smallrye-openapi/deployment/src/main/java/io/quarkus/smallrye/openapi/deployment/SmallRyeOpenApiProcessor.java [hunk 5]
```diff
@@ -545,6 +545,24 @@ public boolean accepts(DotName className) {
 
                 return false;
             }
+
+            @Override
+            public Collection<AnnotationInstance> getAnnotationsWithRepeatable(DotName name, IndexView annotationIndex) {
```
Comment (MikeEdgar) [inline extensions/smallrye-openapi/deployment/src/main/java/io/quarkus/smallrye/openapi/deployment/SmallRyeOpenApiProcessor.java]: This should do the trick for `@PermissionsAllowed`, but my only hesitation is that it's breaking the `IndexView` contract and could potentially cause some unintended effects. For example, we allow the index to be injected into user-provided readers and filters at build time and if they're depending on that contract they may break. If you agree, maybe reading `@PermissionsAllowed` and `@PermissionsAllowed.List` separately from outside of the index would be safer.

File: extensions/smallrye-openapi/deployment/src/main/java/io/quarkus/smallrye/openapi/deployment/SmallRyeOpenApiProcessor.java (hunk 2 above)
Comment (Ladicek) [reply extensions/smallrye-openapi/deployment/src/main/java/io/quarkus/smallrye/openapi/deployment/SmallRyeOpenApiProcessor.java]: That seems somewhat risky, but it also makes a lot of sense. Filed https://github.com/smallrye/jandex/issues/663

**Review by MikeEdgar — APPROVED** [review]
LGTM, thanks @phillip-kruger

**Comment by phillip-kruger** [comment]
Thanks @MikeEdgar !! I still need a green check from someone else to merge this. @Ladicek  ?

**Review by Ladicek — APPROVED** [review]
I don't really understand what's going on here, but it seems we have an approval from security perspective (@michalvavrik) and from OpenAPI perspective (@MikeEdgar), so all's good :-)

**Comment by phillip-kruger** [comment]
Thanks everyone :)

**Comment by j-white** [comment]
latest 3.33 branch is affected as well. could we backport to LTS? :)

**Comment by geoand** [comment]
Is that safe to do @phillip-kruger ?

**Comment by phillip-kruger** [comment]
Yes @geoand this is safe to backport. I added the label. Thanks :)

**Comment by geoand** [comment]
Great, thanks!
