### PR TITLE
Dedicated Dev UI interface to execute HQL (Hibernate ORM) queries

### LINKED ISSUE #39584: Dedicated Dev UI interface to execute (and "log"?) Hibernate ORM queries
### Description

When developing, It can be quite useful to:

1. Execute queries manually and see their effect/results.
2. See the history of executed by the app, and potentially re-execute them with some changes.

Currently, the only options to do so are:

1. For execution, through a JDBC-level Dev UI -- which is a bit too low-level
2. For query history, the logs.

I think a dedicated Dev UI interface could increase developer joy significantly, especially if we introduce additional features.

Initially it could be just about executing queries, like https://github.com/quarkusio/quarkus/pull/43618. If we go that route we can move the query history + "extra" features to a follow-up issue.

A few "extra" features that come to mind (though we may not end up implementing all of them):

* More user-friendly display: e.g. show SQL and bind parameter values next to each other, instead of in separate log lines
* Easy export: "copy" buttons, e.g. raw SQL that can be executed directly on the DB.
* Replay: re-run HQL/SQL requests, possibly after a manual edit, and display results
* Context: show the stack trace that led to a particular query. Or maybe just rely on some OpenTelemetry tracing integration?
* Timing: how long did a given query take?
* Search: filter query history by datasource, sort by query time, ... Though that could require rather heavy infrastructure.

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by mbellade**
Fixes #39584, allowing execution of arbitrary HQL queries in the current Hibernate ORM context.

HQL_demo

The UI is very similar to the [existing Agroal (SQL) database view](https://github.com/quarkusio/quarkus/pull/43618) (many thanks to @phillip-kruger for the inspiration 🙏) but allows selecting Hibernate persistence units and their entities, displaying existing data and executing custom HQL queries. 

Data is rendered using native marshalling _for now_; this is ok for basic result types or simple entities, but it will not do for more complex models (e.g. circular associations, laziness, et.al.). I'm also working on a custom Hibernate tool that allows transforming query results to a textual (JSON) format and account for these complexities - I will update this interface to use that once it's available.

### CODE REVIEW

**Comment by phillip-kruger** [comment]
I like the input at the top. I think we should change the JDBC one to work/look the same

**Review by melloware — APPROVED** [review]

**Comment by yrodiere** [comment]
> I like the input at the top. I think we should change the JDBC one to work/look the same

+1. Also, I was wondering if these consoles would be work a direct link in the "main menu" on the left? Is that possible @phillip-kruger ?

**Comment by phillip-kruger** [comment]
@yrodiere any link on a card van be dragged to the menu and then it will be there as a shortcut

**Comment by yrodiere** [comment]
> @yrodiere any link on a card can be dragged to the menu and then it will be there as a shortcut

Wow, that's convenient.

But I meant as a default, to ensure the consoles are more visible. I suspect most people won't care at all about the list of entities, but they will very much care about SQL/HQL consoles, so we probably want all developers to be aware these consoles exist.

**Comment by phillip-kruger** [comment]
Yes you can also add that there always. Rather than a Card builder you will use a Menu Builder. The rest is the same
See https://quarkus.io/guides/dev-ui#add-a-section-menu

**Comment by yrodiere** [comment]
> Yes you can also add that there always. Rather than a Card builder you will use a Menu Builder. The rest is the same See https://quarkus.io/guides/dev-ui#add-a-section-menu

Created #46759

**Comment by yrodiere** [comment]
Also created #46760 to address the inconsistent structure of Hibernate Dev UI (which is a pre-existing problem I think, so not strictly related to this PR)

**Comment by mbladel** [comment]
> Also created https://github.com/quarkusio/quarkus/issues/46760 to address the inconsistent structure of Hibernate Dev UI (which is a pre-existing problem I think, so not strictly related to this PR)

If we want this to be consistent with the existing Hibernate ORM views, i.e. persistence unit selection in a tabsheet instead of a combo box, that's a pretty easy change. I felt the drop-down would be a bit nicer / less intrusive, but I don't have a strong opinion on it.

**Comment by yrodiere** [comment]
> > Also created #46760 to address the inconsistent structure of Hibernate Dev UI (which is a pre-existing problem I think, so not strictly related to this PR)
> 
> If we want this to be consistent with the existing Hibernate ORM views, i.e. persistence unit selection in a tabsheet instead of a combo box, that's a pretty easy change. I felt the drop-down would be a bit nicer / less intrusive, but I don't have a strong opinion on it.

Yes I also think your solution is better, that's why I'd rather we merge it and fix the consistency later :)

File: extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmConfig.java [hunk 1]
```diff
@@ -182,4 +189,18 @@ default boolean isAnyPropertySet() {
         }
     }
 
+    @ConfigGroup
+    interface HibernateOrmConfigDevUI {
+        /**
+         * Activate or disable the HQL console dev ui page.
+         */
+        @WithDefault("true")
+        boolean enableHqlConsole();
```
Comment (yrodiere) [inline extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmConfig.java:198]: I'm not sure what this is for... If people don't want to use it, they can just ignore it?

File: extensions/hibernate-orm/deployment/src/test/java/io/quarkus/hibernate/orm/dev/HibernateOrmDevJsonRpcServiceTest.java [hunk 2]
```diff
@@ -0,0 +1,127 @@
...
+    }
+
+    @Test
+    public void testGetNumberOfNamedQueries() throws Exception {
+        JsonNode queries = super.executeJsonRPCMethod("getNumberOfNamedQueries");
+
+        assertThat(queries).isNotNull();
+        assertThat(queries.isNumber()).isTrue();
+        assertThat(queries.intValue()).isEqualTo(2);
+    }
```
Comment (yrodiere) [inline extensions/hibernate-orm/deployment/src/test/java/io/quarkus/hibernate/orm/dev/HibernateOrmDevJsonRpcServiceTest.java:80]: FWIW this is already tested in integration tests, e.g. https://github.com/quarkusio/quarkus/blob/4834e06c752639ad4a547622d5541775a6d3e8b8/integration-tests/devmode/src/test/java/io/quarkus/test/devui/AbstractDevUIHibernateOrmTest.java#L20-L19

@phillip-kruger should we move all these tests to the `deployment` module instead?

File: extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/dev/HibernateOrmDevJsonRpcService.java [hunk 3]
```diff
@@ -18,4 +34,53 @@ public int getNumberOfNamedQueries() {
...
+    public DataSet executeHQL(String persistenceUnit, String hql, Integer pageNumber, Integer pageSize) {
+        if (isDev && hqlIsValid(hql)) {
+            Optional<HibernateOrmDevInfo.PersistenceUnit> pu = findPersistenceUnit(persistenceUnit);
+            if (pu.isPresent()) {
+                //noinspection resource
+                SessionFactoryImplementor sf = pu.get().sessionFactory();
+                return sf.fromSession(session -> {
+                    try {
+                        // Hibernate ensures the provided HQL is a selection statement, no pre-validation needed
+                        SelectionQuery<Object> query = session.createSelectionQuery(hql, Object.class);
```
Comment (yrodiere) [inline extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/dev/HibernateOrmDevJsonRpcService.java:50]: Is the "read-only" limitation on purpose?
I wonder if it's a good idea in this case, because:

1. The Agroal console allows inserts/updates.
2. For now, the HQL is completely controlled by the developer, so there's no reason to fear unwanted insert/update/deletes.

AI-generated HQL would be another story, but then we can ensure such HQL _does_ get limited to `SelectionQuery` (while still allowing any query here).

File: extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/dev/HibernateOrmDevJsonRpcService.java [hunk 4]
```diff
@@ -18,4 +34,53 @@ public int getNumberOfNamedQueries() {
         return getInfo().getNumberOfNamedQueries();
     }
 
+    private Optional<HibernateOrmDevInfo.PersistenceUnit> findPersistenceUnit(String persistenceUnitName) {
+        return getInfo().getPersistenceUnits().stream().filter(pu -> persistenceUnitName.equals(pu.getName())).findFirst();
+    }
+
+    public DataSet executeHQL(String persistenceUnit, String hql, Integer pageNumber, Integer pageSize) {
+        if (isDev && hqlIsValid(hql)) {
```
Comment (yrodiere) [inline extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/dev/HibernateOrmDevJsonRpcService.java:42]: The Agroal console has this additional requirement that it only works on local datasources by default.
See: https://github.com/quarkusio/quarkus/blob/bedb8c5769951624e92a9a4f2f48c37413c34083/extensions/agroal/runtime-dev/src/main/java/io/quarkus/agroal/runtime/dev/ui/DatabaseInspector.java#L327-L353

This safety net doesn't exist here. Is it because you added a read-only limitation? Because that's not enough; the main concern that led to adding checks on the Agroal side was this (extracted from private chats with Philip, sorry...):

> a malicious program getting access to port 8080 (somehow) would instantly gain full read/write access to a DB, potentially hosted in a totally different place and protected by authentication
> DB access is protected by authentication
> the dev UI is not, and allows tunneling through the DB connection unauthenticated

So I tend to think we would want some protection similar to what we have for Agroal... It's more complex in the case of Hibernate, but I think we can handle it at least when a PU is assigned a single datasource. For database multitenancy with custom connection providers, we might have to drop the ball and ask that users "allow all hosts" though.

**Review by yrodiere — COMMENTED** [review]
It sure looks great! Thank you.

I have a few security concerns, and added a few more minor remarks. See below.

File: extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/dev/HibernateOrmDevJsonRpcService.java (hunk 4 above)
Comment (mbladel) [reply extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/dev/HibernateOrmDevJsonRpcService.java:42]: I was starting to look into this, and I think it should be doable though I have some doubts. In particular wrt to this phrase:

> It's more complex in the case of Hibernate, but I think we can handle it at least when a PU is assigned a single datasource. For database multitenancy [...]

From what I can see, it looks like we are always using a `QuarkusConnectionProvider`, created through `QuarkusConnectionProvider`. I might be wrong, but if that's the case we could easily retrieve the `AgroalDataSource` object from there and just copy the host-checking code from the existing extension.

File: extensions/hibernate-orm/deployment/src/main/resources/dev-ui/hibernate-orm-hql-console.js [hunk 5]
```diff
@@ -0,0 +1,465 @@
...
+        this._selectPersistenceUnit(this._persistenceUnits.find(unit => unit.name === selectedValue))
+    }
+
+    _selectPersistenceUnit(pu) {
+        this._selectedPersistenceUnit = pu;
+        this._selectedEntityIndex = 0;
+        this._selectedEntity = pu && pu.managedEntities[0] || null;
+    }
+
+    _renderTablesAndData() {
```
[the remark this answers is not in the document]
Comment (mbladel) [reply extensions/hibernate-orm/deployment/src/main/resources/dev-ui/hibernate-orm-hql-console.js:226]: > 1. Can you move rendering to within the transaction?

I am actually not sure. I guess if we had a reference to the json mapper used to serialize json RPC responses we could manually invoke it while in the open session that executed the query. Is that possible?

> 2. If you intend to merge this without having solved the rendering for more complex entities, could you catch such exceptions and fall back to toString(), or to just showing the ID, 

I'm not sure how to catch this kind of exception, as it happens outside of the Hibernate rpc service, after returning the result. To use `toString()` or render only the ID we would need to inspect all properties of the result object trees, which is not easily done. Also, that's part of what the "enhanced serializer" will do so I wouldn't spend time on this unless it's fairly simple to do here.

[the remark this answers is not in the document]
Comment (yrodiere) [reply extensions/hibernate-orm/deployment/src/main/resources/dev-ui/hibernate-orm-hql-console.js:226]: > > 1. Can you move rendering to within the transaction?
> 
> I am actually not sure. I guess if we had a reference to the json mapper used to serialize json RPC responses we could manually invoke it while in the open session that executed the query. Is that possible?

Anything is possible, since you can change the Quarkus Core DevUI code :D 
More seriously, @phillip-kruger would know. Hopefully he's sleeping by now, though, so we'll know tomorrow.


> I'm not sure how to catch this kind of exception, as it happens outside of the Hibernate rpc service, after returning the result.

I think catching only makes sense if you manage to move the rendering within your method.


> To use `toString()` or render only the ID we would need to inspect all properties of the result object trees, which is not easily done. Also, that's part of what the "enhanced serializer" will do so I wouldn't spend time on this unless it's fairly simple to do here.

I meant simply calling `toString` on the root entity. A.k.a. "rendering something potentially useless because that's arguably slightly better than failing".

[the remark this answers is not in the document]
Comment (phillip-kruger) [reply extensions/hibernate-orm/deployment/src/main/resources/dev-ui/hibernate-orm-hql-console.js:226]: Not sleeping yet. I am not following what you want to do ? Can you explain a bit ?

[the remark this answers is not in the document]
Comment (mbladel) [reply extensions/hibernate-orm/deployment/src/main/resources/dev-ui/hibernate-orm-hql-console.js:226]: @phillip-kruger invoke the serialization of the json rpc method (i.e. transform the `DataSet` object to JSON) within the `executeHQL` method itself, allowing us to do it within the open session. That would allow lazy attributes to be loaded automatically while serializing the object tree.

[the remark this answers is not in the document]
Comment (phillip-kruger) [reply extensions/hibernate-orm/deployment/src/main/resources/dev-ui/hibernate-orm-hql-console.js:226]: @mbladel Where in the code is this ?

[the remark this answers is not in the document]
Comment (mbladel) [reply extensions/hibernate-orm/deployment/src/main/resources/dev-ui/hibernate-orm-hql-console.js:226]: @phillip-kruger sorry here: https://github.com/quarkusio/quarkus/pull/46728/files#diff-d3c226687e0a73bb5064c1c43b648371d8439ff143d5f0264d374245fadc62cfR47-R71

File: extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/dev/HibernateOrmDevJsonRpcService.java (hunk 3 above)
Comment (mbladel) [reply extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/dev/HibernateOrmDevJsonRpcService.java:50]: > Is the "read-only" limitation on purpose?

Yes, I thought the purpose of this console (also as it was proposed on the original issue) would be mostly for data access and visualization, more than mutating data. If we want to also support mutation statements though that's certainly possible, especially after implementing the datasource checking as you suggested in the following comment. LMK what you'd prefer.

File: extensions/hibernate-orm/deployment/src/main/resources/dev-ui/hibernate-orm-hql-console.js (hunk 5 above)
[the remark this answers is not in the document]
Comment (phillip-kruger) [reply extensions/hibernate-orm/deployment/src/main/resources/dev-ui/hibernate-orm-hql-console.js:226]: (Going to bed now - i'll check in in the morning)

[the remark this answers is not in the document]
Comment (yrodiere) [reply extensions/hibernate-orm/deployment/src/main/resources/dev-ui/hibernate-orm-hql-console.js:226]: There's a function somewhere in the Dev UI that does the JSON serialization, something like `JsonNode serialize(Object) { ... }`. We just need to call that ourselves, in the context of our own method, because when the Dev UI code does it, it's too late (the session is closed).

File: extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmConfig.java (hunk 1 above)
Comment (mbladel) [reply extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmConfig.java]: Removed.

File: extensions/hibernate-orm/deployment/src/main/resources/dev-ui/hibernate-orm-hql-console.js [hunk 6]
```diff
@@ -0,0 +1,465 @@
...
+    _handleAllowHqlChange() {
+        this.configJsonRpc.updateProperty({
+            'name': '%dev.quarkus.hibernate-orm.dev-ui.allow-hql',
+            'value': 'true'
+        }).then(e => {
+            this._allowHql = true;
+        });
+    }
+
+    _shiftEnterPressed(event) {
```
[the remark this answers is not in the document]
Comment (mbladel) [reply extensions/hibernate-orm/deployment/src/main/resources/dev-ui/hibernate-orm-hql-console.js:346]: I think Shift+Enter is what's officially supported by the `qui-code-block` ui element, see [here](https://www.npmjs.com/package/@qomponent/qui-code-block).

File: extensions/hibernate-orm/deployment/src/test/java/io/quarkus/hibernate/orm/dev/HibernateOrmDevJsonRpcServiceTest.java (hunk 2 above)
Comment (mbladel) [reply extensions/hibernate-orm/deployment/src/test/java/io/quarkus/hibernate/orm/dev/HibernateOrmDevJsonRpcServiceTest.java]: I've completely missed the existing test. I've moved the tests for the `executeHQL` method there for now.

+1 from me to move the test, maybe not under `deployment` but under `hibernate-orm/runtime`, where `HibernateOrmDevJsonRpcService` is. Though I'm fine with keeping it under ITs as well.

File: extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/dev/HibernateOrmDevJsonRpcService.java (hunk 4 above)
Comment (mbladel) [reply extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/dev/HibernateOrmDevJsonRpcService.java]: I've implemented an initial check based on this assumption, waiting to hear your feedback on it.

File: extensions/hibernate-orm/deployment/src/main/resources/dev-ui/hibernate-orm-hql-console.js (hunk 5 above)
[the remark this answers is not in the document]
Comment (phillip-kruger) [reply extensions/hibernate-orm/deployment/src/main/resources/dev-ui/hibernate-orm-hql-console.js:226]: A, ok, that will be a bigger change... luckily it's in this code (I think) originally authored by @yrodiere :)
https://github.com/quarkusio/quarkus/blame/main/extensions/vertx-http/deployment/src/main/java/io/quarkus/devui/deployment/jsonrpc/DevUIDatabindCodec.java

File: extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/dev/HibernateOrmDevJsonRpcService.java (hunk 3 above)
Comment (yrodiere) [reply extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/dev/HibernateOrmDevJsonRpcService.java]: I'd personally prefer having it all, but it depends how complex it is. Feel free to do whatever is more realistic: support inserts/updates, or just add a reasonably simple error message ("inserts/updates not supported in this console at the moment" or something like that).

File: extensions/hibernate-orm/deployment/src/main/resources/dev-ui/hibernate-orm-hql-console.js (hunk 6 above)
[the remark this answers is not in the document]
Comment (yrodiere) [reply extensions/hibernate-orm/deployment/src/main/resources/dev-ui/hibernate-orm-hql-console.js:346]: Ok, then let's not bother. Thanks for looking into it.

File: extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/dev/HibernateOrmDevJsonRpcService.java [hunk 7]
```diff
@@ -18,4 +46,100 @@ public int getNumberOfNamedQueries() {
...
+        // Check the connection for this persistence unit points to an allowed datasource
+        ConnectionProvider connectionProvider = sf.getServiceRegistry().requireService(ConnectionProvider.class);
+        if (connectionProvider instanceof QuarkusConnectionProvider quarkusConnectionProvider) {
+            if (!isAllowedDatabase(quarkusConnectionProvider.getDataSource())) {
+                return errorDataSet("The persistence unit datasource points to a non-allowed datasource " +
+                        "(by default, only local databases are allowed).");
+            }
+        } else {
+            return errorDataSet("Unsupported Connection Provider type for specified persistence unit.");
+        }
```
Comment (yrodiere) [inline extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/dev/HibernateOrmDevJsonRpcService.java:79]: LGTM.

Maybe you could add (and document) a special value (`*`?) for the `allowed-host` property, so that these two error cases can be avoided when people are fine with allowing all hosts? Since that'd be opt-in, it'd still be relatively safe.

File: extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/dev/HibernateOrmDevJsonRpcService.java [hunk 8]
```diff
@@ -18,4 +46,100 @@ public int getNumberOfNamedQueries() {
...
+
+        //noinspection resource
+        SessionFactoryImplementor sf = pu.get().sessionFactory();
+
+        // Check the connection for this persistence unit points to an allowed datasource
+        ConnectionProvider connectionProvider = sf.getServiceRegistry().requireService(ConnectionProvider.class);
+        if (connectionProvider instanceof QuarkusConnectionProvider quarkusConnectionProvider) {
+            if (!isAllowedDatabase(quarkusConnectionProvider.getDataSource())) {
+                return errorDataSet("The persistence unit datasource points to a non-allowed datasource " +
+                        "(by default, only local databases are allowed).");
```
Comment (yrodiere) [inline extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/dev/HibernateOrmDevJsonRpcService.java:75]: Maybe make this actionable by mentioning the configuration property to allow non-local DBs?

**Comment by yrodiere** [comment]
Just so you know @mbladel the flaky test above is unrelated (though it's causing me much despair); see https://github.com/quarkusio/quarkus/issues/42479

**Comment by mbladel** [comment]
@yrodiere thanks for the heads up, I did see that test failing enough times to guess it was just flaky. I might try to reproduce it as well, though seeing your several attempts without much success doesn't give me much hope :sweat_smile:

**Comment by yrodiere** [comment]
> @yrodiere thanks for the heads up, I did see that test failing enough times to guess it was just flaky. I might try to reproduce it as well, though seeing your several attempts without much success doesn't give me much hope 😅

Yeah I'll gladly let someone else take that one, but if you do, be warned it might take a few days...

File: extensions/hibernate-orm/deployment/src/main/resources/dev-ui/hibernate-orm-hql-console.js (hunk 5 above)
[the remark this answers is not in the document]
Comment (mbladel) [reply extensions/hibernate-orm/deployment/src/main/resources/dev-ui/hibernate-orm-hql-console.js:228]: Alright, I tried hacking together something: now I retrieve the `JsonRpcRouter` instance using CDI, and use its `JsonMapper` to serialize results within the session, allowing for lazy loading to function correctly. I also implemented a way to tell the router not to serialize the message, since it has already been transformed to JSON (`JsonRpcMessage#alreadySerialized`).

File: extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/dev/HibernateOrmDevJsonRpcService.java (hunk 3 above)
Comment (mbladel) [reply extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/dev/HibernateOrmDevJsonRpcService.java]: Implemented support for mutations as well.

File: extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/dev/HibernateOrmDevJsonRpcService.java (hunk 7 above)
Comment (mbladel) [reply extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/dev/HibernateOrmDevJsonRpcService.java]: Done (for both the Hibernate and Agroal Dev UI back-ends).

File: extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/dev/HibernateOrmDevJsonRpcService.java (hunk 8 above)
Comment (mbladel) [reply extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/dev/HibernateOrmDevJsonRpcService.java]: Changed to a more verbose message, mentioning the configuration property.

File: extensions/agroal/runtime-dev/src/main/java/io/quarkus/agroal/runtime/dev/ui/DatabaseInspector.java [hunk 9]
```diff
@@ -5,20 +5,9 @@
 import java.io.UncheckedIOException;
 import java.net.URI;
 import java.net.URISyntaxException;
-import java.sql.Connection;
-import java.sql.DatabaseMetaData;
+import java.sql.*;
```
Comment (yrodiere) [inline extensions/agroal/runtime-dev/src/main/java/io/quarkus/agroal/runtime/dev/ui/DatabaseInspector.java:8]: I think wildcard imports are forbidden. See https://github.com/quarkusio/quarkus/blob/main/CONTRIBUTING.md#ide-config-and-code-style : 

> Next, disable wildcard imports: navigate to Editor -> Code Style -> Java -> Imports and set Class count to use import with '*' to 999. Do the same with Names count to use static import with '*'.

You can try `./mvnw process-sources` to run automatic formatting, but I'm not sure that will solve the wildcard import issue; you might need your IDE to solve that.

File: extensions/agroal/runtime-dev/src/main/java/io/quarkus/agroal/runtime/dev/ui/DatabaseInspector.java [hunk 10]
```diff
@@ -223,7 +212,10 @@ public DataSet executeSQL(String datasource, String sql, Integer pageNumber, Int
                         }
                     }
                 } else {
-                    return new DataSet(null, null, "Only supported for Local Databases", null, -1);
+                    return new DataSet(null, null,
+                            "Datasource access not allowed. By default only local databases are enabled; you can use the"
+                                    + " 'quarkus.datasource.dev-ui.allowed-db-host' configuration property to configure allowed hosts ('*' to allow all).",
+                            null, -1);
```
Comment (yrodiere) [inline extensions/agroal/runtime-dev/src/main/java/io/quarkus/agroal/runtime/dev/ui/DatabaseInspector.java:218]: Great idea to improve the Agroal side as well; thanks for that!

File: extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/dev/HibernateOrmDevJsonRpcService.java [hunk 11]
```diff
@@ -18,4 +55,146 @@ public int getNumberOfNamedQueries() {
...
+                        while (hasNext && i++ < pageSize) {
+                            results.add(scroll.get());
+                            hasNext = scroll.next();
+                        }
+
+                        // manually serialize data within the transaction to ensure lazy-loading can function
+                        String result = writeValueAsString(new DataSet(results, resultCount, null, null));
+                        JsonRpcMessage<Object> message = new JsonRpcMessage<>(result, MessageType.Response);
+                        message.setAlreadySerialized(true);
+                        return message;
```
Comment (yrodiere) [inline extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/dev/HibernateOrmDevJsonRpcService.java:142]: So we still have a limitation: circular associations will result in a serialization error:

```
io.vertx.core.json.EncodeException: Failed to encode as JSON: Document nesting depth (1002) exceeds the maximum allowed (1000, from `StreamWriteConstraints.getMaxNestingDepth()`) (through reference chain: java.util.ArrayList[0]->org.acme.hibernate.orm.Color["fruits"]->org.hibernate.collection.spi.PersistentBag[0]->org.acme.hibernate.orm.Fruit["colors"]->org.hibernate.collection.spi.PersistentBag[0]->org.acme.hibernate.orm.Color["fruits"]->org.hibernate.collection.spi.PersistentBag[0]->org.acme.hibernate.orm.Fruit["colors"]->org.hibernate.collection.spi.PersistentBag[0]->org.acme.hibernate.orm.Color["fruits"]->org.hibernate.collection.spi.PersistentBag[0]-
[...]
```

I understand that's something you intend to solve by switching to a different form of serialization, later.

I would have suggested to serialize row-by-row, so that an error serializing one row won't prevent us from displaying the whole thing, especially since your future serialization method will require serializing row-by-row anyway. But... I suspect handling of "errored-out" rows will be challenging. So okay, let's give up on this.

But could you at least catch such exception and provide a better error message, such as:

```
Unable to encode results as JSON. Note circular associations are not supported at the moment, use `@JsonIgnore` to break circles.
Exception:
io.vertx.core.json.EncodeException: Failed to encode as JSON: Document nesting depth (1002) exceeds the maximum allowed (1000, from `StreamWriteConstraints.getMaxNestingDepth()`) (through reference chain: java.util.ArrayList[0]->org.acme.hibernate.orm.Color["fruits"]->org.hibernate.collection.spi.PersistentBag[0]->org.acme.hibernate.orm.Fruit["colors"]->org.hibernate.collection.spi.PersistentBag[0]->org.acme.hibernate.orm.Color["fruits"]->org.hibernate.collection.spi.PersistentBag[0]->org.acme.hibernate.orm.Fruit["colors"]->org.hibernate.collection.spi.PersistentBag[0]-
[...]
```

**Review by yrodiere — APPROVED** [review]
Thank you! LGTM, we can merge any time you want IMO.

I have a suggestion for error handling, but I'll let you judge if it's necessary.

Maybe @phillip-kruger will want to have a look at the serialization part, too.

File: extensions/agroal/runtime-dev/src/main/java/io/quarkus/agroal/runtime/dev/ui/DatabaseInspector.java (hunk 10 above)
Comment (mbladel) [reply extensions/agroal/runtime-dev/src/main/java/io/quarkus/agroal/runtime/dev/ui/DatabaseInspector.java:218]: Of course, the setting is the same so we should keep consistent messaging.

File: extensions/agroal/runtime-dev/src/main/java/io/quarkus/agroal/runtime/dev/ui/DatabaseInspector.java (hunk 9 above)
Comment (mbladel) [reply extensions/agroal/runtime-dev/src/main/java/io/quarkus/agroal/runtime/dev/ui/DatabaseInspector.java]: Yeah, it feels like I already did that multiple times but maybe IJ loses the config 🤔 `process-sources` does not fix that indeed, should be fixed now.

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/devui/runtime/jsonrpc/JsonRpcCodec.java [hunk 12]
```diff
@@ -39,8 +39,11 @@ public void writeErrorResponse(ServerWebSocket socket, int id, String jsonRpcMet
                         "Method [" + jsonRpcMethodName + "] failed: " + exception.getMessage())));
     }
 
-    private void writeResponse(ServerWebSocket socker, JsonRpcResponse response) {
-        socker.writeTextMessage(jsonMapper.toString(response, true));
+    private void writeResponse(ServerWebSocket socket, JsonRpcResponse response) {
+        socket.writeTextMessage(jsonMapper.toString(response, true));
```
Comment (phillip-kruger) [inline extensions/vertx-http/runtime/src/main/java/io/quarkus/devui/runtime/jsonrpc/JsonRpcCodec.java:43]: Ha ha. Good catch :)

**Review by phillip-kruger — APPROVED** [review]
LGTM

**Comment by omasseau** [comment]
I updated my Quarkus project to the latest version (3.22.1) and it is not working.
I get this error displayed by the DevUI page : 

`Error executing query: Unable to encode results as JSON. Note circular associations are not supported at the moment, use `@JsonIgnore` to break circles.`

image

File: extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/dev/HibernateOrmDevJsonRpcService.java [hunk 13]
```diff
@@ -18,4 +55,152 @@ public int getNumberOfNamedQueries() {
...
+        return new JsonRpcMessage<>(new DataSet(null, -1, null, errorMessage), MessageType.Response);
+    }
+
+    private static String writeValueAsString(DataSet value) {
+        try {
+            JsonRpcRouter jsonRpcRouter = CDI.current().select(JsonRpcRouter.class).get();
+            return jsonRpcRouter.getJsonMapper().toString(value, true);
+        } catch (Exception ex) {
+            throw new RuntimeException(
+                    "Unable to encode results as JSON. Note circular associations are not supported at the moment, use `@JsonIgnore` to break circles.",
```
Comment (omasseau) [inline extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/dev/HibernateOrmDevJsonRpcService.java:161]: This error message is misleading. It let people think that the cause of the exception is always a circular association, while it may not always be the case.

This error message is also only displayed in the dev UI (very briefly) and not logged at all in the application logs.
