### PR TITLE
Fix for Context Propagation on Reactive Messaging

### LINKED ISSUE #27166: Connection pool exhaustion for lazy entity association (acquisition timeout)
### Describe the bug

Hi guys!
I've noticed that some async processing in our project exhausts a database connection pool, and it never recovers.
The problem can be fixed by adding @Transactional annotation to @Incoming event handler, but 
1) I am not changing anything in the database during this process, using only "findById" method and getting some info from an entity
2) for some methods, performance is the case, so I would rather not add transactional processing there

Please check the reproducer.
There are two related entities and two tests: 
1) GreetingResourceTest: we are calling the HTTP endpoint repeatedly 50 times, and everything is ok. The connection pool works fine and gives us all entities to process
2) GreetingKafkaTest: we are sending an event to the topic and waiting for it to be processed. After the 4th repeat, it starts to fail because the connection pool max-size is set to 5

Please notice that when you set EAGER association between two entities, everything works fine for both tests.
I believe something is wrong with releasing DB connection during async execution.

### Expected behavior

LAZY association between entities works the same as EAGER one for non-transactional processing: connections are reused in the pool

### Actual behavior

"Unable to acquire JDBC Connection" after some calls (max pool size)
Caused by: java.sql.SQLException: Sorry, acquisition timeout!

### How to Reproduce?

[cp-reproducer.zip](https://github.com/quarkusio/quarkus/files/9275380/cp-reproducer.zip)

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

java version "11.0.12" 2021-07-20 LTS Java(TM) SE Runtime Environment 18.9 (build 11.0.12+8-LTS-237) Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.12+8-LTS-237, mixed mode)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.11.2 and smaller

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ozangunalp**
The issue revealed by @Sanne in https://github.com/Sanne/quarkus-scope-tests

Reactive Messaging doesn't handle CDI request scope, it only ensures that consumer methods are dispatched on a duplicated vert.x context per message.
When a request scoped bean is used in consumer methods, the request context should not be active by default and can be activated through the `@ActivateRequestContext` annotation, properly creating request scoped beans and destroying them on completion.

The fix involves:
- Run reactive messaging wiring without RequestContext
- `ActivateRequestContextInterceptor` terminates request context properly on returning Uni.
- `ActivateRequestContextInterceptor` destroys request context state properly when reactive method completes on a different thread (or a different Vert.x context)

A separate PR will follow on smallrye-reactive-messaging for returning message (n)ack's on the message context.

Fixes #27166

### CODE REVIEW

File: extensions/smallrye-reactive-messaging/runtime/src/main/java/io/quarkus/smallrye/reactivemessaging/runtime/SmallRyeReactiveMessagingLifecycle.java [hunk 1]
```diff
@@ -37,13 +38,22 @@ void onStaticInit(@Observes @Initialized(ApplicationScoped.class) Object event,
     }
 
     void onApplicationStart(@Observes @Priority(Interceptor.Priority.LIBRARY_BEFORE) StartupEvent event) {
+        // We do not want a request scope during the wiring, or it will be propagated and never terminated.
+        boolean isRequestScopeActive = Arc.container().requestContext().isActive();
```
Comment (Sanne) [inline extensions/smallrye-reactive-messaging/runtime/src/main/java/io/quarkus/smallrye/reactivemessaging/runtime/SmallRyeReactiveMessagingLifecycle.java:42]: could you extract `Arc.container().requestContext()` into a local variable?

File: extensions/smallrye-reactive-messaging/runtime/src/main/java/io/quarkus/smallrye/reactivemessaging/runtime/SmallRyeReactiveMessagingLifecycle.java [hunk 2]
```diff
@@ -37,13 +38,22 @@ void onStaticInit(@Observes @Initialized(ApplicationScoped.class) Object event,
...
         try {
             mediatorManager.start();
         } catch (Exception e) {
             if (e instanceof DeploymentException || e instanceof DefinitionException) {
                 throw e;
             }
             throw new DeploymentException(e);
+        } finally {
+            if (isRequestScopeActive) {
+                Arc.container().requestContext().activate();
```
Comment (Sanne) [inline extensions/smallrye-reactive-messaging/runtime/src/main/java/io/quarkus/smallrye/reactivemessaging/runtime/SmallRyeReactiveMessagingLifecycle.java:55]: I really don't know, but I'm wondering if the initial request context shouldn't be restored rather than a new one being activated? Are we ok to throw a way to context state?

**Comment by Sanne** [comment]
Thank you so much for digging! I'll let others review though, my knowledge of CDI semantic expectations is too limited.

File: extensions/smallrye-reactive-messaging/runtime/src/main/java/io/quarkus/smallrye/reactivemessaging/runtime/SmallRyeReactiveMessagingLifecycle.java (hunk 2 above)
Comment (ozangunalp) [reply extensions/smallrye-reactive-messaging/runtime/src/main/java/io/quarkus/smallrye/reactivemessaging/runtime/SmallRyeReactiveMessagingLifecycle.java]: When you say it, it makes sense. I've done as you suggest, but I didn't resolve the conversation to double check

File: independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl/ActivateRequestContextInterceptor.java [hunk 3]
```diff
@@ -38,14 +39,16 @@ private CompletionStage<?> invokeStage(InvocationContext ctx) {
         }
 
         return activate(requestContext)
-                .thenCompose(v -> proceedWithStage(ctx))
-                .whenComplete((r, t) -> requestContext.terminate());
+                .thenCompose(state -> proceedWithStage(ctx).whenComplete((r, t) -> {
+                    requestContext.destroy(state);
+                    requestContext.deactivate();
+                }));
```
Comment (Ladicek) [inline independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl/ActivateRequestContextInterceptor.java:45]: I was wondering what's the difference here, as `terminate()` == `destroy()` + `deactivate()`. It's that you explicitly pass `state` to `destroy`, right?

Comment (Ladicek) [reply independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl/ActivateRequestContextInterceptor.java:45]: Ah all changes in this file do this same thing. I wonder if it's just a precaution, or if `destroy()` without parameters finds (and destroys) a different context than it should...

In any case, being explicit can't hurt.

**Review by Ladicek — APPROVED** [review]

File: extensions/smallrye-reactive-messaging/runtime/src/main/java/io/quarkus/smallrye/reactivemessaging/runtime/SmallRyeReactiveMessagingLifecycle.java (hunk 2 above)
Comment (Ladicek) [reply extensions/smallrye-reactive-messaging/runtime/src/main/java/io/quarkus/smallrye/reactivemessaging/runtime/SmallRyeReactiveMessagingLifecycle.java]: I think this makes sense.

**Comment by Sanne** [comment]
There seems to be a problem in my reproducer still; although I'm not sure if my test is valid or perhaps I have some invalid assumptions.

W/o this PR, I was having `org.acme.GreetingResourceTest` passing, and `org.acme.GreetingKafkaTest` fail.

But with this patch appied, while the Kafka one seems fixed, the other one starts failing - I need to look better into it but it seems to indicate a new leak.

**Comment by Sanne** [comment]
Nevermind, I had a problem in my test.
Thanks!

**Comment by ozangunalp** [comment]
@Sanne I forked your test and added some more here: https://github.com/ozangunalp/quarkus-scope-tests, with this branch they all pass for me.

**Comment by Sanne** [comment]
Right, seems all good. I'm verifying now if it also fixes https://github.com/quarkusio/quarkus/issues/27166

**Comment by Sanne** [comment]
@gsmet N.B. I've marked this both as **candidate for backporting** and as **breaking change** (!).

 - I'd consider it for backporting as it fixes nasty a leak, of both resources and memory (see e.g. now fixed #27166 ) 
 - it's breaking as with this change, people having a listener might need to start a request scope explicitly; for example they might need to add `@ActivateRequestContext` on the receiving method. Essentially the lifespan of the scope is safer to be made explicit by the user in this case.
