### PR TITLE
QuarkusTest: handle beans declared on test profile specifically

### LINKED ISSUE #36554: TestProfile specific CDI beans
### Description

It would be beneficial if we could generate beans in custom test profiles. These beans would then take the place of the existing beans, but only for the current @QuarkusTest, as demonstrated below:
```

@QuarkusTest
@TestProfile(MyIT.Profile.class)
class MyIT {

    @Inject
    CustomBean custom;
    @Inject
    ExistingBean existing;


    @Test
    void aTest() throws Exception {
      //
    }

    static class CustomBean {
    }

    public static class Profile implements QuarkusTestProfile {
        
        @ApplicationScoped
        @Produces
        public CustomBean customBean() {
            //add new bean to context, exists only in MyIT
            return new CustomBean();
        }
        @ApplicationScoped
        @Produces
        public ExistingBean existingBean() {
            //replace existing bean in context only in MyIT
            return new ExistingBean();
        }
        
        @Override
        public Map<String, String> getConfigOverrides() {
            return Map.of("my.property", "false");
        }
    }
}


```

### Implementation ideas

I believe something like that exists in spring

### PR DESCRIPTION
**Pull request by mkouba**
- beans declared on a test profile implementation are only taken into account if the test profile is used
- resolves #36554

### CODE REVIEW

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/TestsAsBeansProcessor.java [hunk 1]
```diff
@@ -31,4 +46,92 @@ public void testClassBeans(List<TestClassBeanBuildItem> items, BuildProducer<Add
...
+                if (target.kind() == Kind.METHOD) {
+                    vetoProducerIfNecessary(target.asMethod().declaringClass(), context);
+                } else if (target.kind() == Kind.FIELD) {
+                    vetoProducerIfNecessary(target.asField().declaringClass(), context);
+                } else if (target.kind() == Kind.CLASS) {
+                    ClassInfo clazz = target.asClass();
+                    if (clazz.nestingType() == NestingType.INNER && Modifier.isStatic(clazz.flags())) {
+                        ClassInfo enclosing = index.getComputingIndex().getClassByName(clazz.enclosingClass());
+                        if (customScopes.isScopeIn(context.getAnnotations())
+                                && isTestProfileClass(enclosing, index.getComputingIndex())
```
Comment (Ladicek) [inline extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/TestsAsBeansProcessor.java:72]: Technically this will only veto nested classes of test profile classes, but not nested classes of nested classes of test profile classes :-), but I guess that's not a big deal.

**Review by Ladicek — APPROVED** [review]
Nice!

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/TestsAsBeansProcessor.java (hunk 1 above)
Comment (mkouba) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/TestsAsBeansProcessor.java:72]: Yes, nested classes of nested classes of test profile classes are not supported :shrug:

**Review by Ladicek — APPROVED** [review]
