### PR TITLE
Do not copy `quarkus` configuration to Gradle plugin forced properties

### LINKED ISSUE #46456: Gradle project properties have higher priority than system properties
### Describe the bug

According to the [Configuring Quarkus builds](https://quarkus.io/guides/gradle-tooling#configuring-quarkus-builds) guide, system properties should have higher priority than Gradle project properties but actually this is not the case.

### Expected behavior

`./gradlew clean build -Dquarkus.package.type=native -Pquarkus.package.type=uber-jar --info` produces a native executable.

### Actual behavior

`./gradlew clean build -Dquarkus.package.type=native -Pquarkus.package.type=uber-jar --info` creates an uber JAR.

### How to Reproduce?

1. Download and extract a sample project from https://code.quarkus.io/ with Gradle as build tool.
2. Run `./gradlew build` with the same config property specified as system property (`-D`) and project property (`-P`).

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by radcortez**
For some reason, we were copying `quarkus.*` configuration to the Gradle plugin forced properties Config Source, which is set to `600` in ordinality, being the highest of all sources.

I believe this started with https://github.com/quarkusio/quarkus/pull/41337, where I've copied what was already there in https://github.com/quarkusio/quarkus/commit/f10a208b09a8b50f48c6724586876e74436ecacd#diff-2c6f0d62b0763af665a1bc242ad078ce25794f20632651181549d838e3452998R113-R118

Now, I don't think this is required, because Project Properties also contains the same configuration, so we shouldn't be missing anything, but this approach causes #46456.

Subsequent code changes probably just followed the same pattern. Also, in #48769 added yet a new way of doing things and a `quarkusRelevantProjectProperties`, which filters `quarkus.*` properties from Project Properties, causing inconsistencies in the available configuration when used. I've changed that to just pass all Project Properties like we are doing in other places.

- Fixes #46456

### CODE REVIEW

File: devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/AbstractQuarkusExtension.java [hunk 1]
```diff
@@ -172,65 +150,6 @@ protected EffectiveConfig buildEffectiveConfiguration(ApplicationModel appModel)
...
 
-    /**
-     * Filters resolved Gradle configuration for properties in the Quarkus namespace
-     * (as in start with <code>quarkus.</code>). This avoids exposing configuration that may contain secrets or
-     * passwords not related to Quarkus (for instance environment variables storing sensitive data for other systems).
-     *
-     * @param appArtifact the application dependency to retrive the quarkus application name and version.
-     * @return a filtered view of the configuration only with <code>quarkus.</code> names.
-     */
-    protected Map<String, String> buildSystemProperties(ResolvedDependency appArtifact, Map<String, String> quarkusProperties) {
```
Comment (radcortez) [inline devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/AbstractQuarkusExtension.java:183]: This was removed because the method was copied in https://github.com/quarkusio/quarkus/pull/48769/files#diff-c7c4670b6f52fa54bf95459cc59308526b7b4331fe8bfb512245ba93413344f5R384, but the original code was not deleted.

File: devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/EffectiveConfigProvider.java [hunk 2]
```diff
@@ -87,7 +80,7 @@ public EffectiveConfig buildEffectiveConfiguration(ApplicationModel appModel,
                 .withForcedProperties(forced)
                 .withTaskProperties(properties)
                 .withBuildProperties(quarkusBuildProperties.get())
-                .withProjectProperties(quarkusRelevantProjectProperties.get())
```
Comment (radcortez) [inline devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/EffectiveConfigProvider.java:90]: Unsure why we have these `quarkusRelevantProjectProperties`, created from:
https://github.com/quarkusio/quarkus/blob/f06d87135f0206628e2d2e05294a0ba4e1fdb10e/devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/QuarkusPluginExtensionView.java#L70-L80

And was being passed down as Project Properties, where in every other place we don't do that filter and pass Project Properties directly:

https://github.com/quarkusio/quarkus/blob/88bfd6658b461f0c6da25798f783344de80cbe57/devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/AbstractQuarkusExtension.java#L71-L86

https://github.com/quarkusio/quarkus/blob/88bfd6658b461f0c6da25798f783344de80cbe57/devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/AbstractQuarkusExtension.java#L125-L151

**Comment by geoand** [comment]
What’s the current status on this?

**Comment by radcortez** [comment]
Waiting for a review :)

**Comment by aloubyansky** [comment]
It'd be good to include a test to make sure a subsequent change doesn't break the fix.

**Comment by radcortez** [comment]
Rebased with main and added a test.

**Review by aloubyansky — APPROVED** [review]
