### PR TITLE
Runtime init the cleaner instance in ResourceCleaner

### LINKED ISSUE #31440: Several quarkus integration tests fail to compile to native with latest GraalVM master
### Describe the bug

`oidc-client` is one, `main` integration-test is another. Fails the same way with JDK 17-based build as well as JDK 20-base build.

It looks like `ResourceCleaner.CLEANER` from reasteasy becomes newly? reachable? `native-image` generation fails with:
```
[INFO] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Building native image source jar: /home/runner/work/mandrel/mandrel/quarkus/integration-tests/oidc-client/target/quarkus-integration-test-oidc-client-999-SNAPSHOT-native-image-source-jar/quarkus-integration-test-oidc-client-999-SNAPSHOT-runner.jar
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Building native image from /home/runner/work/mandrel/mandrel/quarkus/integration-tests/oidc-client/target/quarkus-integration-test-oidc-client-999-SNAPSHOT-native-image-source-jar/quarkus-integration-test-oidc-client-999-SNAPSHOT-runner.jar
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on native-image 23.0.0-devc2e5c2c9 Mandrel Distribution (Java Version 17.0.7-beta+3-202302240048)
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildRunner] /home/runner/work/mandrel/mandrel/openjdk/bin/native-image -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dlogging.initial-configurator.min-level=400 -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.noUnsafe=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=3 -J-Duser.language=en -J-Duser.country=US -J-Dfile.encoding=UTF-8 --features=io.quarkus.runner.Feature,io.quarkus.runtime.graal.DisableLoggingFeature -J--add-exports=java.security.jgss/sun.security.krb5=ALL-UNNAMED -J--add-opens=java.base/java.text=ALL-UNNAMED -J--add-opens=java.base/java.io=ALL-UNNAMED -J--add-opens=java.base/java.lang.invoke=ALL-UNNAMED -J--add-opens=java.base/java.util=ALL-UNNAMED -H:BuildOutputJSONFile=quarkus-integration-test-oidc-client-999-SNAPSHOT-runner-build-output-stats.json -H:+AllowFoldMethods -J-Djava.awt.headless=true --no-fallback --link-at-build-time -H:+ReportExceptionStackTraces -J-Xmx5g -H:-AddAllCharsets --enable-url-protocols=http,https -H:NativeLinkerOption=-no-pie -H:-UseServiceLoaderFeature -H:+StackTrace -J--add-exports=org.graalvm.sdk/org.graalvm.nativeimage.impl=ALL-UNNAMED --exclude-config io\.netty\.netty-codec /META-INF/native-image/io\.netty/netty-codec/generated/handlers/reflect-config\.json --exclude-config io\.netty\.netty-handler /META-INF/native-image/io\.netty/netty-handler/generated/handlers/reflect-config\.json quarkus-integration-test-oidc-client-999-SNAPSHOT-runner -jar quarkus-integration-test-oidc-client-999-SNAPSHOT-runner.jar
========================================================================================================================
GraalVM Native Image: Generating 'quarkus-integration-test-oidc-client-999-SNAPSHOT-runner' (executable)...
========================================================================================================================
Warning: Could not register io.quarkus.oidc.client.filter.runtime.AbstractOidcClientRequestFilter_nondefaultclient for serialization as it does not implement Serializable.
[1/8] Initializing...                                                                                   (14.3s @ 0.22GB)
 Version info: 'GraalVM 23.0.0-devc2e5c2c9 Java 17.0.7-beta+3-202302240048 Mandrel Distribution'
 Java version info: '17.0.7-beta+3-202302240048'
 C compiler: gcc (linux, x86_64, 11.3.0)
 Garbage collector: Serial GC (max heap size: unlimited)
 3 user-specific feature(s)
 - io.quarkus.runner.Feature: Auto-generated class by Quarkus from the existing extensions
 - io.quarkus.runtime.graal.DisableLoggingFeature: Disables INFO logging during the analysis phase
 - org.eclipse.angus.activation.nativeimage.AngusActivationFeature
[2/8] Performing analysis...  [******]                                                                 (121.6s @ 2.32GB)
  14,722 (89.06%) of 16,530 types reachable
  23,726 (63.19%) of 37,545 fields reachable
  76,107 (60.10%) of 126,631 methods reachable
   4,574 types,   176 fields, and 2,938 methods registered for reflection
      63 types,    68 fields, and    55 methods registered for JNI access
       4 native libraries: dl, pthread, rt, z

Error: Detected a java.lang.ref.Cleaner object in the image heap which uses a daemon thread that invokes cleaning actions, but threads running in the image generator are no longer running at image runtime.  To see how this object got instantiated use --trace-object-instantiation=java.lang.ref.Cleaner. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Detailed message:
Trace: Object was reached by
  trying to constant fold static field org.jboss.resteasy.spi.ResourceCleaner.CLEANER
    at org.jboss.resteasy.spi.ResourceCleaner.register(ResourceCleaner.java:48)
  parsing method org.jboss.resteasy.spi.ResourceCleaner.register(ResourceCleaner.java:48) reachable via the parsing context
    at static root method.(Unknown Source)


------------------------------------------------------------------------------------------------------------------------
com.oracle.svm.core.util.UserError$UserException: Detected a java.lang.ref.Cleaner object in the image heap which uses a daemon thread that invokes cleaning actions, but threads running in the image generator are no longer running at image runtime.  To see how this object got instantiated use --trace-object-instantiation=java.lang.ref.Cleaner. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Detailed message:
Trace: Object was reached by
  trying to constant fold static field org.jboss.resteasy.spi.ResourceCleaner.CLEANER
    at org.jboss.resteasy.spi.ResourceCleaner.register(ResourceCleaner.java:48)
  parsing method org.jboss.resteasy.spi.ResourceCleaner.register(ResourceCleaner.java:48) reachable via the parsing context
    at static root method.(Unknown Source)


	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:85)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:248)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:821)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:605)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:562)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:408)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:616)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:134)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:94)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Detected a java.lang.ref.Cleaner object in the image heap which uses a daemon thread that invokes cleaning actions, but threads running in the image generator are no longer running at image runtime.  To see how this object got instantiated use --trace-object-instantiation=java.lang.ref.Cleaner. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Detailed message:
Trace: Object was reached by
  trying to constant fold static field org.jboss.resteasy.spi.ResourceCleaner.CLEANER
    at org.jboss.resteasy.spi.ResourceCleaner.register(ResourceCleaner.java:48)
  parsing method org.jboss.resteasy.spi.ResourceCleaner.register(ResourceCleaner.java:48) reachable via the parsing context
    at static root method.(Unknown Source)


	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:126)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:816)
	... 6 more
                        7.2s (5.2% of total time) in 27 GCs | Peak RSS: 3.12GB | CPU load: 1.94
------------------------------------------------------------------------------------------------------------------------
```

### Expected behavior

Native image generation passes.

### Actual behavior

Fails as above.

### How to Reproduce?

Run integration-tests `main` or `oidc-client` with a GraalVM/Mandrel build from latest master. E.g. from here:
https://github.com/graalvm/mandrel/suites/11215681139/artifacts/573900606

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

17.0.7+1

### GraalVM version (if different from Java)

lastest master

### Quarkus version or git rev

main

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

See also:
https://github.com/graalvm/mandrel/actions/runs/4278105893/jobs/7447740912#step:11:324

### PR DESCRIPTION
**Pull request by jerboaa**
Inject an accessor for the ResourceCleaner.CLEANER static variable so that the associated cleaner won't get initialized at build time and ends up being in the native image heap.

Closes: #31440

### CODE REVIEW

**Comment by jerboaa** [comment]
Mandrel workflow with this is running here: https://github.com/graalvm/mandrel/actions/runs/4285051293

**Comment by jerboaa** [comment]
It should probably be in the resteasy-common extension rather than resteasy-client as I had it before.

**Comment by jerboaa** [comment]
@zakkak Please take a look when you get a chance! Thanks.

File: extensions/resteasy-classic/resteasy-common/runtime/src/main/java/io/quarkus/resteasy/common/runtime/graal/ResourceCleanerReplacement.java [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+            return result;
+        }
+
+        private static synchronized Cleaner initializeOnce() {
+            Cleaner result = INSTANCE;
+            if (result == null) {
+                // double checked locking is ok as INSTANCE is volatile
+                result = INSTANCE = Cleaner.create();
+            }
+            return result;
```
Comment (zakkak) [inline extensions/resteasy-classic/resteasy-common/runtime/src/main/java/io/quarkus/resteasy/common/runtime/graal/ResourceCleanerReplacement.java:40]: Styling nitpick

```suggestion
            if (INSTANCE == null) {
                // double checked locking is ok as INSTANCE is volatile
                INSTANCE = Cleaner.create();
            }
            return INSTANCE;
```

**Review by zakkak — COMMENTED** [review]
LGTM, but did you try just reinitializing the class instead?

File: extensions/resteasy-classic/resteasy-common/runtime/src/main/java/io/quarkus/resteasy/common/runtime/graal/ResourceCleanerReplacement.java (hunk 1 above)
Comment (jerboaa) [reply extensions/resteasy-classic/resteasy-common/runtime/src/main/java/io/quarkus/resteasy/common/runtime/graal/ResourceCleanerReplacement.java]: Done.

**Comment by jerboaa** [comment]
> ... but did you try just reinitializing the class instead?

I did not. Then again, wouldn't for runtime-reinited classes the same restrictions apply (instances of those classes are disallowed in the image heap)? I'll have a look and will report back.

**Comment by zakkak** [comment]
> > ... but did you try just reinitializing the class instead?
> 
> I did not. Then again, wouldn't for runtime-reinited classes the same restrictions apply (instances of those classes are disallowed in the image heap)? 

No, fields of reinited classes are treated differently. The issue with instances of certain classes being present in the native heap is that those instances were generated at build time and they are thus not valid at runtime. When reiniting a class the said fields are "uninitialized" in the initial native heap and get initialized at run time which is valid.

**Comment by zakkak** [comment]
> I thought this is for **runtime** initialized classes. Runtime **re-inited** classes are initialized both at build time and again at runtime: https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/classinitialization/InitKind.java#L44..L45
> 

Correct, they are initialized at build time for the build to proceed and to increase the level of optimization, but the values from the static fields are not used at runtime (if I am not mistaken they are not even placed in the generated native heap), instead they get re-initialized at run time. Because of this they are allowed to be _present_ in the heap.

> Anyway, in this case both seem to work.

I didn't suggest pure runtime initialization because I thought the class needed to be build-time initialized. Great that you tried both.

> Runtime-reinit: https://github.com/quarkusio/quarkus/compare/main...jerboaa:quarkus:runtime-reinit-resource?expand=1 Runtime-init: https://github.com/quarkusio/quarkus/compare/main...jerboaa:quarkus:runtime-init-resource?expand=1
> 
> Shall I update this patch with the last (runtime-init) option?

Yes, please.

**Comment by zakkak** [comment]
> Runtime-init: https://github.com/quarkusio/quarkus/compare/main...jerboaa:quarkus:runtime-init-resource?expand=1

@jerboaa I suggest doing the runtime initialization registration in https://github.com/quarkusio/quarkus/blob/main/extensions/resteasy-classic/resteasy-common/deployment/src/main/java/io/quarkus/resteasy/common/deployment/ResteasyCommonProcessor.java instead of creating a new class.

**Comment by jerboaa** [comment]
@zakkak Done now. Thanks for the reviews. I've also rescheduled a run of the mandrel tests with this:
https://github.com/graalvm/mandrel/actions/runs/4285051293

**Review by zakkak — APPROVED** [review]
LGTM, thanks!

**Comment by jerboaa** [comment]
@gsmet Hi! Could you please help approving the workflow and getting this integrated? It fixes many broken integration tests on the mandrel CI side. Thanks!

**Comment by gsmet** [comment]
@zakkak just to be sure, you have the permission to approve a workflow run, right? Wondering if it's only admins.

**Comment by zakkak** [comment]
> @zakkak just to be sure, you have the permission to approve a workflow run, right? Wondering if it's only admins.

Yes, I was the one who approved it this morning. I am also going to merge this once the CI completes. @jerboaa was probably not aware that I have the power to do both :)

Probably it didn't help that I didn't notice that the workflow was blocked for some unknown (since this is not the first contribution of @jerboaa) reason.

**Comment by zakkak** [comment]
The failure is unrelated to the PR. Merging it.

**Comment by zakkak** [comment]
Marking this for backport since although [the Cleaner instances were disallowed only recently](https://github.com/oracle/graal/pull/6062) the issue is actually present in older versions as well.

**Comment by gsmet** [comment]
Actually, AFAICS, `ResourceCleaner` doesn't exist in 2.16.

**Comment by zakkak** [comment]
Indeed, the ResourceCleaner was [added in 6.1.0.Final](https://github.com/resteasy/resteasy/commit/4dbae7119a3966a244cfe1629077cef29ea2fd8f) and 2.16 is [using 4.7.7](https://github.com/quarkusio/quarkus/blob/0865c6a050c07e8543582cc9bb7e5c6b82593602/bom/application/pom.xml#L22).
