### PR TITLE
When propagating the duplicated context, drop the request scope

### LINKED ISSUE #29017: Request Context Race condition in quarkus 2.13
### Describe the bug

when firing an async CDI Event, the request context from the emitter briefly exists for the observer and is then terminated.
This prevents to create a new Request context for the Async observer since the emitter context still exist.

This was working in Quarkus 2.12

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

reproducer: 

https://github.com/rmanibus/quarkus_29017

execute the ReproducerTest

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.13.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by cescoffier**
Fix #29017

### CODE REVIEW

File: extensions/vertx/runtime/src/main/java/io/quarkus/vertx/core/runtime/VertxCoreRecorder.java [hunk 1]
```diff
@@ -558,7 +560,25 @@ public void runWith(Runnable task, Object context) {
...
                 if (context != null && context != currentContext) {
                     // Only do context handling if it's non-null
-                    final ContextInternal vertxContext = (ContextInternal) context;
+                    ContextInternal vertxContext = (ContextInternal) context;
+                    // The request scope must not be propagated
+                    Object requestScope = null;
+                    ConcurrentMap<Object, Object> local = vertxContext.localContextData();
+                    for (Object k : local.keySet()) {
+                        if (k.getClass().getName()
+                                .equals("io.quarkus.vertx.runtime.VertxCurrentContextFactory$VertxCurrentContext")) {
```
Comment (gsmet) [inline extensions/vertx/runtime/src/main/java/io/quarkus/vertx/core/runtime/VertxCoreRecorder.java:569]: Can't say I'm excited about this very brittle dark magic :).

**Comment by mkouba** [comment]
I can confirm that this pull request fixed the problem mentioned in https://github.com/quarkusio/quarkus/issues/29017.

**Review by mkouba — APPROVED** [review]

**Comment by mkouba** [comment]
Should we backport this into 2.13?
