### PR TITLE
fixes #3215 CORS bug when preflight request is made to REST resource

### LINKED ISSUE #3215: CORS bug when preflight request is made to REST resource
**Describe the bug**
When you enable CORS and your REST endpoints are installed in root, the RESTEasyFilter overlaps the CORSFilter and it nevers get called.

**Expected behavior**
The CORS headers should be added to the reponse.

**Actual behavior**
No CORS headers added to the response.

**To Reproduce**
1. Create a REST Enpoint located in the root [@]Path("/") or [@]ApplicationPath("/")
2. Enable cors quarkus.http.cors=true
3. Make a preflight request to the endpoint curl -v -X OPTIONS -H "Origin: whatever" http://localhost:8080/

**Configuration**
```properties
# Add your application.properties here, if applicable.
quarkus.http.cors=true
```

**Screenshots**
Screen Shot 2019-07-13 at 9 52 18 AM

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: macOS
 - Output of `java -version`:  11.0.3
 - GraalVM version (if different from Java):  19.0.2
 - Quarkus version or git rev:  0.19.1 / or master

**Additional context**
Found this while trying to help to resolve this question: https://groups.google.com/forum/#!topic/quarkus-dev/zrXlgRgdoD4

### PR DESCRIPTION
**Pull request by cristhiank**
Please review if this approach is right to allow CORS preflight request pass through the Filter chain.

see #3215

### CODE REVIEW

**Comment by cristhiank** [comment]
The pipeline is failing in the MongoDB extension for some reason:

image

**Comment by machi1990** [comment]
> The pipeline is failing in the MongoDB extension for some reason:
> 
> image

Seems to be related to https://github.com/quarkusio/quarkus/issues/3210

**Comment by gsmet** [comment]
@cescoffier any idea on the MongoDB CI issue?

File: extensions/resteasy/deployment/src/test/java/io/quarkus/resteasy/test/RestEasyCORSTestCase.java [hunk 1]
```diff
@@ -17,6 +17,21 @@
...
 
+    @Test
+    public void testCORSPreflightRootResource() {
+        String origin = "http://custom.origin.quarkus";
+        String methods = "GET,POST";
+        String headers = "X-Custom";
+        RestAssured.given()
+                .header("Origin", origin)
+                .header("Access-Control-Request-Method", methods)
+                .header("Access-Control-Request-Headers", headers)
```
Comment (gsmet) [inline extensions/resteasy/deployment/src/test/java/io/quarkus/resteasy/test/RestEasyCORSTestCase.java]: Quick question: these 2 headers are always defined?

Comment (cristhiank) [reply extensions/resteasy/deployment/src/test/java/io/quarkus/resteasy/test/RestEasyCORSTestCase.java]: According to the spec they should be defined. see https://fetch.spec.whatwg.org/#http-requests

Comment (cristhiank) [reply extensions/resteasy/deployment/src/test/java/io/quarkus/resteasy/test/RestEasyCORSTestCase.java]: See also: https://developer.mozilla.org/en-US/docs/Glossary/preflight_request

Comment (cristhiank) [reply extensions/resteasy/deployment/src/test/java/io/quarkus/resteasy/test/RestEasyCORSTestCase.java]: I did it this way because I wanted this to be independent of the cors config and it is based on a standard. The other alternative would be making the ResteasyFilter aware of the HttpConfig and check if CORS was enable... but I think it is too invasive and we would start having CORS logic all around the web extensions.

**Comment by aloubyansky** [comment]
Now, when I restarted the the failed build, it passed. Looks like an issue with the test. There is another PR with the same failure. I am going to re-start it one more time.

**Comment by aloubyansky** [comment]
Hm, I don't see how I can restart a successful build.

**Review by aloubyansky — APPROVED** [review]
Looks good to me. Thanks!
