### PR TITLE
Fix SimpleScheduler pause functionality

### LINKED ISSUE #13512: SimpleScheduler: pause doesn't work
**Describe the bug**
When you try to inject SimpleScheduler and then call SimpleScheduler::pause nothing happens.

**Expected behavior**
Scheduled jobs should be paused

**Actual behavior**
Nothing happens

**To Reproduce**
Add some method annotated by @Scheduled
Then try to pause scheduler using SimpleScheduler::pause method.

Screenshot 2020-11-27 at 12 26 40
looks like bug is here.

### PR DESCRIPTION
**Pull request by sultansoy**
Fix [#13512](https://github.com/quarkusio/quarkus/issues/13512)
Add return in SimpleScheduler::checkTriggers method if !running.

### CODE REVIEW

**Review by machi1990 — CHANGES_REQUESTED** [review]
Good catch and thank you for the PR @sultansoy. Do you think we can add a test for this?

We can take inspiration from  https://github.com/quarkusio/quarkus/blob/04842681f5f46f3ef4be84921838a2a10bf22ecf/extensions/scheduler/deployment/src/test/java/io/quarkus/scheduler/test/DisabledSchedulerTest.java by enabling `quarkus.scheduler.enabled=true` and pausing the scheduler and check that no scheduled method was called.

**Review by gsmet — DISMISSED** [review]
Just a quick note that this needs to be squashed before merging. Please dismiss when done.

File: extensions/scheduler/deployment/src/test/java/io/quarkus/scheduler/test/PausedSchedulerTest.java [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+import io.quarkus.scheduler.Scheduled;
+import io.quarkus.scheduler.Scheduler;
+import io.quarkus.test.QuarkusUnitTest;
+
+public class PausedSchedulerTest {
+
+    @RegisterExtension
+    static final QuarkusUnitTest test = new QuarkusUnitTest()
+            .setArchiveProducer(() -> ShrinkWrap.create(JavaArchive.class)
+                    .addClasses(DisabledSchedulerTest.Jobs.class)
```
Comment (machi1990) [inline extensions/scheduler/deployment/src/test/java/io/quarkus/scheduler/test/PausedSchedulerTest.java:25]:
```suggestion
                    .addClasses(PausedSchedulerTest.Jobs.class)
```

Thank you for adding a test. I think we added a wrong job class. It should be `PausedSchedulerTest #Jobs`.  Can you have a look at this, once it is done please squash the commits into one commit as suggested by @gsmet and this will be good for merging.

**Review by machi1990 — APPROVED** [review]

**Comment by machi1990** [comment]
Thanks @sultansoy. LGTM

File: extensions/scheduler/deployment/src/test/java/io/quarkus/scheduler/test/PausedSchedulerTest.java (hunk 1 above)
Comment (sultansoy) [reply extensions/scheduler/deployment/src/test/java/io/quarkus/scheduler/test/PausedSchedulerTest.java]: thanks for review.
i've replaced with PausedSchedulerTest and squashed commits.

**Comment by sultansoy** [comment]
> Just a quick note that this needs to be squashed before merging. Please dismiss when done.

squashed

**Review by gsmet — APPROVED** [review]
Nice work, thanks!

**Comment by RustamSultansoy** [comment]
@machi1990 sorry, should I retrigger the CI?

**Comment by sultansoy** [comment]
@machi1990 @gsmet  sorry, should I retrigger the CI?

**Comment by gsmet** [comment]
No, it's OK, merged, thanks!
