### PR TITLE
Autowiring of GraphQL clients in TEST mode

### LINKED ISSUE #26365: Integrate GraphQL Typesafe Client into QuarkusTest
### Description

I'd like to directly inject a GraphQL Client into a test, i.e.:

```java
@QuarkusTest
class UserTest {

    @GraphQLClientApi interface Api {
        @Query User user(int id);
    }

    public static class User {
        String name;
    }

    @Inject Api api;

    @Test void shouldGetJane() {
        var jane = api.user(1);

        then(jane.name).isEqualTo("Jane");
    }
}
```

But then I get a `RuntimeException`: "URL not configured for client."

The workaround I have to use is:

```java
    @TestHTTPResource("graphql")
    URI uri;

    Api api() {return TypesafeGraphQLClientBuilder.newBuilder().endpoint(uri).build(Api.class);}

    @Test void shouldGetJane() {
        var jane = api().user(1);

        then(jane.name).isEqualTo("Jane");
    }
}
```

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by jmartisk**
fixes https://github.com/quarkusio/quarkus/issues/26365

### CODE REVIEW

File: extensions/smallrye-graphql-client/runtime/src/main/java/io/quarkus/smallrye/graphql/client/runtime/GraphQLClientConfigurationMergerBean.java [hunk 1]
```diff
@@ -80,6 +113,13 @@ private GraphQLClientConfiguration toSmallRyeNativeConfiguration(GraphQLClientCo
         return transformed;
     }
 
+    private String getTestingServerUrl() {
+        Config config = ConfigProvider.getConfig();
+        // the client extension doesn't have dependencies on neither the server extension nor quarkus-vertx-http, so guessing
+        // is somewhat limited
+        return "http://localhost:" + config.getOptionalValue("quarkus.http.test-port", int.class).orElse(8081) + "/graphql";
```
Comment (jmartisk) [inline extensions/smallrye-graphql-client/runtime/src/main/java/io/quarkus/smallrye/graphql/client/runtime/GraphQLClientConfigurationMergerBean.java:120]: I welcome suggestions how to improve it. Because we don't want to introduce dependencies on `quarkus-vertx-http` or `quarkus-smallrye-graphql` extensions just for this, we can't directly read their configuration, and they might not be present at all

Comment (phillip-kruger) [reply extensions/smallrye-graphql-client/runtime/src/main/java/io/quarkus/smallrye/graphql/client/runtime/GraphQLClientConfigurationMergerBean.java:120]: Can you not get this from a BuildItem (and pass in here via some recorder ?)

Comment (jmartisk) [reply extensions/smallrye-graphql-client/runtime/src/main/java/io/quarkus/smallrye/graphql/client/runtime/GraphQLClientConfigurationMergerBean.java:120]: The problem is the non-existent dependencies, such BuildItem would probably have to exist in some shared module (Quarkus core probably), and I'm not so sure we want to complicate stuff this much just for this, and add graphql-specific stuff into Quarkus core. In 98 % of cases this should work, and we also log a message explaining how to fix it if it doesn't work.

**Review by phillip-kruger — APPROVED** [review]
