### PR TITLE
Check for invalid characters when adding an extension

### LINKED ISSUE #49895: Quarkus CLI does not check for special characters when adding an extension
### Describe the bug

quarkus ext add io.quarkiverse.businessscore:quarkus-business-score-health~:1.0.0.Alpha4 

[SUCCESS] ✅  Extension io.quarkiverse.businessscore:quarkus-business-score-health~:1.0.0.Alpha4 has been installed

Resulting pom.xml
```
        <dependency>
            <groupId>io.quarkiverse.businessscore</groupId>
            <artifactId>quarkus-business-score-health~</artifactId>
            <version>1.0.0.Alpha4</version>
        </dependency>
```

### Expected behavior

Error message from the CLI:

[ERROR] ❗  Cannot find a dependency matching 'quarkus-business-score-health~:1.0.0.Alpha4', maybe a typo?
[ERROR] ❗  Unable to create project: Failed to create project because of invalid extensions

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by nderwin**
* Fixes #49895
* use a pattern matcher to validate the groupId and artifactId for a fully qualified extension name (group, artifact, and version)

Signed-off-by:Nathan Erwin <nathan.d.erwin@gmail.com>

### CODE REVIEW

**Comment by nderwin** [comment]
I'm not sure I'm fully happy with this as it still can lead to bad dependencies being added because when given a GAV, it just adds it, and you'll find out it's bad with your first Maven command.

Regardless, some testing scenarios...

```bash
java -jar quarkus-cli-999-SNAPSHOT-runner.jar ext add io.quarkiverse.businessscore:quarkus-business-score-health~:1.0.0.Alpha4
[ERROR] ❗  Nothing installed because keyword(s) 'io.quarkiverse.businessscore:quarkus-business-score-health~:1.0.0.Alpha4' were not matched in the catalog.
```

Note an invalid dependency, but it has valid characters in it:

```bash
java -jar quarkus-cli-999-SNAPSHOT-runner.jar ext add io.quarkus:quarkus-info-:3.20.1
[SUCCESS] ✅  Extension io.quarkus:quarkus-info-:3.20.1 has been installed
```

Note a really invalid dependency:

```bash
java -jar quarkus-cli-999-SNAPSHOT-runner.jar ext add group:artifact:version
[SUCCESS] ✅  Extension group:artifact:version has been installed
```

If you leave off the version, then the dependency is validated against the catalog, so it would have given an error for adding `'io.quarkiverse.businessscore:quarkus-business-score-health~`

**Review by gsmet — COMMENTED** [review]
I haven't checked the code but is there a reason why we don't send an explicit error?

**Comment by gsmet** [comment]
Thanks for having a look at this one btw :)

**Comment by nderwin** [comment]
> I haven't checked the code but is there a reason why we don't send an explicit error?

Yeah, that would be nicer, right?  Unfortunately, it goes back to `ExtensionInstallPlan` - it has a provision for just a collection of unmatched keys, no collection of errors.

I stopped short of adding that as it touches many more classes, but if you think it's worth it, I can take a look at that.

**Comment by nderwin** [comment]
@gsmet Meh, it was easier than I thought, so I just went ahead and added it.  Example now:

```bash
java -jar quarkus-cli-999-SNAPSHOT-runner.jar ext add io.quarkiverse.businessscore:quarkus-business-score-health~:1.0.0.Alpha4
[FAILURE] ❌  Nothing installed because keyword(s) 'io.quarkiverse.businessscore:quarkus-business-score-health~:1.0.0.Alpha4' were invalid.
```

**Comment by gastaldi** [comment]
Can you include some tests to justify the change?

File: independent-projects/tools/devtools-common/src/main/java/io/quarkus/devtools/commands/handlers/AddExtensionsCommandHandler.java [hunk 1]
```diff
@@ -99,6 +110,7 @@ public ExtensionInstallPlan planInstallation(QuarkusCommandInvocation invocation
         final String quarkusCore = catalog.getQuarkusCoreVersion();
         final Collection<ArtifactCoords> importedPlatforms = invocation.getQuarkusProject().getExtensionManager()
                 .getInstalledPlatforms();
+        final Pattern validId = Pattern.compile("[A-Za-z0-9_.-]+");
```
Comment (gastaldi) [inline independent-projects/tools/devtools-common/src/main/java/io/quarkus/devtools/commands/handlers/AddExtensionsCommandHandler.java]: Make it a private static final attribute in this class.

Comment (nderwin) [reply independent-projects/tools/devtools-common/src/main/java/io/quarkus/devtools/commands/handlers/AddExtensionsCommandHandler.java]: Done.

**Comment by nderwin** [comment]
> Can you include some tests to justify the change?

Sure, just as soon as I figure out where to put 'em.

**Comment by nderwin** [comment]
Ok @gastaldi I took a swipe at adding tests, maybe it's ok?  Not really sure...

**Review by gastaldi — APPROVED** [review]
LGTM, thanks!

**Comment by aloubyansky** [comment]
@nderwin It's ok to split the task into validating the strings and where an artifact is actually resolvable.

I am not sure why
```
java -jar quarkus-cli-999-SNAPSHOT-runner.jar ext add io.quarkiverse.businessscore:quarkus-business-score-health~:1.0.0.Alpha4
[ERROR] ❗  Nothing installed because keyword(s) 'io.quarkiverse.businessscore:quarkus-business-score-health~:1.0.0.Alpha4' were not matched in the catalog.
```
is not reported as invalid in terms of pattern.

Is `-` at the end actually allowed? I don't see it being documented, e.g. here https://maven.apache.org/guides/mini/guide-naming-conventions.html, but i guess, it wouldn't be. The same for a `.` at the end of a groupId.
```
java -jar quarkus-cli-999-SNAPSHOT-runner.jar ext add io.quarkus:quarkus-info-:3.20.1
[SUCCESS] ✅  Extension io.quarkus:quarkus-info-:3.20.1 has been installed
```

Could we adjust the regex pattern to account for that? Thanks!

**Comment by nderwin** [comment]
@aloubyansky The issue with the first error you mention isn't the position, it's the `~` (tilde) - that's not a valid character for a Maven groupId or artifactId.

True, it's weird to have one of those values end with a `-` or `.`, but at least they are valid characters, and will be validated when you try to reference the artifact during a Maven lifecycle.

I'll do some further digging to see how Maven itself validates this, maybe there's something that can be shared there (if not code, then at least ideas).

**Comment by aloubyansky** [comment]
Is
> java -jar quarkus-cli-999-SNAPSHOT-runner.jar ext add io.quarkiverse.businessscore:quarkus-business-score-health~:1.0.0.Alpha4
[ERROR] ❗  Nothing installed because keyword(s) 'io.quarkiverse.businessscore:quarkus-business-score-health~:1.0.0.Alpha4' were not matched in the catalog.

The expected outcome though?

**Comment by nderwin** [comment]
@aloubyansky No, this should be the expected output for that case:

```shell
java -jar quarkus-cli-999-SNAPSHOT-runner.jar ext add io.quarkiverse.businessscore:quarkus-business-score-health~:1.0.0.Alpha4
[FAILURE] ❌  Nothing installed because keyword(s) 'io.quarkiverse.businessscore:quarkus-business-score-health~:1.0.0.Alpha4' were invalid.
```

I had updated the PR from the comment by @gsmet wondering why it was mixed in with the other errors.

**Comment by aloubyansky** [comment]
Perfect, thanks!
Would you like to adjust the regex to make sure groupIds don't end with `.` and artifactIds don't end with `-`?

**Comment by nderwin** [comment]
@aloubyansky Well...  I'm not sure we should?  Based on what I found for how Maven does it's validation, it doesn't actually care, even though the documentation talks about the conventions.

https://github.com/apache/maven/blob/maven-3.9.11/maven-model-builder/src/main/java/org/apache/maven/model/validation/DefaultModelValidator.java

I do see in there that it's also validating some wildcard characters, `?` and `*`, so maybe those do need to be added to the regex?

**Comment by aloubyansky** [comment]
Unless I'm mistaken, this is the check https://github.com/apache/maven/blob/maven-3.9.11/maven-model-builder/src/main/java/org/apache/maven/model/validation/DefaultModelValidator.java#L1158-L1170

```
    private boolean isValidId(String id) {
        for (int i = 0; i < id.length(); i++) {
            char c = id.charAt(i);
            if (!isValidIdCharacter(c)) {
                return false;
            }
        }
        return true;
    }

    private boolean isValidIdCharacter(char c) {
        return c >= 'a' && c <= 'z' || c >= 'A' && c <= 'Z' || c >= '0' && c <= '9' || c == '-' || c == '_' || c == '.';
    }
```

**Comment by nderwin** [comment]
Agreed, that's what I saw;  I also saw this in there:  https://github.com/apache/maven/blob/maven-3.9.11/maven-model-builder/src/main/java/org/apache/maven/model/validation/DefaultModelValidator.java#L1200-L1212

```java
    private boolean isValidIdWithWildCards(String id) {
        for (int i = 0; i < id.length(); i++) {
            char c = id.charAt(i);
            if (!isValidIdWithWildCardCharacter(c)) {
                return false;
            }
        }
        return true;
    }


    private boolean isValidIdWithWildCardCharacter(char c) {
        return isValidIdCharacter(c) || c == '?' || c == '*';
    }
```

**Comment by aloubyansky** [comment]
Alright, let's get this in for now. Thanks a lot @nderwin !

**Comment by nderwin** [comment]
Though it looks like the wildcard validation is for dependency _exclusions_, which is not what the `add ext` command does, so maybe that can be ignored.
