### PR TITLE
Lock liquibase between validate and update

### LINKED ISSUE #25335: Liquibase lock not working correctly anymore
### Describe the bug

Since the change in https://github.com/quarkusio/quarkus/pull/24515 the Liquibase lock is not working correctly anymore when starting two instances at the same time. 

I also created an issue in the liquibase project for this bug:
https://github.com/liquibase/liquibase/issues/2816

I don't know how you handle this kind of bug coming from an upstream project, so I created this issue,.

### Expected behavior

The lock should prevent to run the changesets more than once.

### Actual behavior

The changesets are applied twice

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.8.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by joggeli34**
Lock liquibase for validate and update as suggested by:
https://github.com/liquibase/liquibase/issues/2816#issuecomment-1297539028

Closes #25335

### CODE REVIEW

**Comment by geoand** [comment]
Thanks for the contribution.

Please format the code change according to the message above.

File: extensions/liquibase/runtime/src/main/java/io/quarkus/liquibase/runtime/LiquibaseRecorder.java [hunk 1]
```diff
@@ -58,10 +58,16 @@ public void doStartActions() {
                             liquibase.dropAll();
                         }
                         if (config.migrateAtStart) {
-                            if (config.validateOnMigrate) {
-                                liquibase.validate();
+                            var lockService = LockServiceFactory.getInstance().getLockService(liquibase.getDatabase());
+                            try {
+                                lockService.waitForLock();
```
Comment (famod) [inline extensions/liquibase/runtime/src/main/java/io/quarkus/liquibase/runtime/LiquibaseRecorder.java:63]: Is `releaseLock()` "lenient" in that it does _not_ throw an exception if the lock has not been acquired?
What I have in mind is:
- `waitForLock()` fails with an exception
- `finally` kicks in
- `releaseLock()` fails (assumption!) because the lock has not been acquired
- the exception from `finally` shadows the one from `waitForLock()`, confusing the user

I'd move `waitForLock()` out of the `try` block or add a `catch` + `addSuppressed()` to the `finally` block.

This might seem like overengineering, but I had similar cases more often than not.

File: extensions/liquibase/runtime/src/main/java/io/quarkus/liquibase/runtime/LiquibaseRecorder.java [hunk 2]
```diff
@@ -58,10 +58,16 @@ public void doStartActions() {
...
+                                if (config.validateOnMigrate) {
```
Comment (famod) [inline extensions/liquibase/runtime/src/main/java/io/quarkus/liquibase/runtime/LiquibaseRecorder.java:64]: So we're adding the overhead(?) of locking even in the case where we don't validate.

But given `validate-on-migrate` ist true by default it should be alright.

**Review by famod — COMMENTED** [review]
I'm a bit puzzled by what is going to happen if this is run in conjunction with the upstream PR that resets some caches.
Do we have to roll back this change when that liquibase version lands?

File: extensions/liquibase/runtime/src/main/java/io/quarkus/liquibase/runtime/LiquibaseRecorder.java (hunk 2 above)
Comment (joggeli34) [reply extensions/liquibase/runtime/src/main/java/io/quarkus/liquibase/runtime/LiquibaseRecorder.java:64]: The overhead should be minimal, as the first thing `liquibase.update()` does is to acquire the lock. But if it already has it, it will result more or less in a map lookup, this should not generate much overhead.

**Comment by joggeli34** [comment]
The code must not be rollbacked after the upstream fix, as with this change it will prevent to load the changelog twice, once for validate and once for update

**Review by famod — APPROVED** [review]
Ok, so that upstream change (the reset) will not kick in with explicit locking because it'll bail out earlier because it detects that the db is already locked (by the locking approach of this PR).

Let's see what CI has to say.

**Comment by gsmet** [comment]
Thanks!
