### PR TITLE
SmallRye GraphQL - Allow execution model annotations on @Resolver methods

### LINKED ISSUE #46893: Graphql federation @Resolver and @Blocking do not work
### Describe the bug

If I use those two annotations on a method

```
import io.smallrye.common.annotation.Blocking
import io.smallrye.graphql.api.federation.Resolver
```

I get this error on build:

```
 The @Blocking, @NonBlocking and @RunOnVirtualThread annotations may only be used on "entrypoint" methods (methods invoked by various frameworks in Quarkus)
13:58:33   Using the @Blocking, @NonBlocking and @RunOnVirtualThread annotations on methods that can only be invoked by application code is invalid
13:58:33     at io.quarkus.deployment.execannotations.ExecutionModelAnnotationsProcessor.check(ExecutionModelAnnotationsProcessor.java:55)
13:58:33     at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
13:58:33     at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)
13:58:33     at io.quarkus.builder.BuildContext.run(BuildContext.java:255)
13:58:33     at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
13:58:33     at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)
13:58:33     at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)
13:58:33     at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)
13:58:33     at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)
13:58:33     at java.base/java.lang.Thread.run(Thread.java:1583)
13:58:33     at org.jboss.threads.JBossThread.run(JBossThread.java:499)
```

But the resolver is only called from the Federation Data Fetcher like a query., so blocking should be supported.

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by gsmet**
Fixes #46893

### CODE REVIEW

File: extensions/smallrye-graphql/deployment/src/main/java/io/quarkus/smallrye/graphql/deployment/GraphqlMethodsProcessor.java [hunk 1]
```diff
@@ -10,21 +10,23 @@
...
     private static final DotName MUTATION = DotName.createSimple(Mutation.class);
     private static final DotName SUBSCRIPTION = DotName.createSimple(Subscription.class);
+    private static final DotName RESOLVER = DotName.createSimple(Resolver.class);
 
     @BuildStep
     ExecutionModelAnnotationsAllowedBuildItem graphqlMethods() {
         return new ExecutionModelAnnotationsAllowedBuildItem(new Predicate<MethodInfo>() {
             @Override
             public boolean test(MethodInfo method) {
-                // maybe just look for `@GraphQLApi` on the declaring class?
```
Comment (gsmet) [inline extensions/smallrye-graphql/deployment/src/main/java/io/quarkus/smallrye/graphql/deployment/GraphqlMethodsProcessor.java:24]: The annotation I added is not annotated with `@GraphQLApi` thus why I removed the comment.

It might make sense to add it? If so, we could keep the comment.

**Review by jmartisk — APPROVED** [review]
