### PR TITLE
Set proper content type for DevUI template rendering

### LINKED ISSUE #24366: DEV UI not working with nosniff http header
### Describe the bug

If the _quarkus.http.header."X-Content-Type-Options".value_ set to nosniff the DEV UI will be not rendered. 

### Expected behavior

It should be as html rendered.

### Actual behavior

It shows plain html text. 

### How to Reproduce?

Set application property
`quarkus.http.header."X-Content-Type-Options".value = nosniff`

### Output of `uname -a` or `ver`

MINGW64_NT-10.0-19042 3.0.7-338.x86_64 2019-11-21 23:07 UTC x86_64 Msys

### Output of `java -version`

openjdk version "17.0.2" 2022-01-18 LTS OpenJDK Runtime Environment Corretto-17.0.2.8.1 (build 17.0.2+8-LTS) OpenJDK 64-Bit Server VM Corretto-17.0.2.8.1 (build 17.0.2+8-LTS, mixed mode, sharing)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.7.5.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #24366

### CODE REVIEW

File: extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/devmode/console/DevConsole.java [hunk 1]
```diff
@@ -174,7 +176,7 @@ public Object apply(String s, Throwable throwable) {
                 if (throwable != null) {
                     event.fail(throwable);
                 } else {
-                    event.response().end(s);
+                    event.response().putHeader(HttpHeaderNames.CONTENT_TYPE, HTML_CONTENT_TYPE).end(s);
```
Comment (mkouba) [inline extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/devmode/console/DevConsole.java:179]: You don't need to set the contentType header again, or?

Comment (mkouba) [reply extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/devmode/console/DevConsole.java:179]: Hm, the `renderTemplate()` method is called from the `handle()` above...

Comment (geoand) [reply extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/devmode/console/DevConsole.java]: Okay, changed to make it a little more clear

**Review by mkouba — APPROVED** [review]
