### PR TITLE
Fix the inclusion of the built-in serializers and deserializers

### LINKED ISSUE #2944: Kafka - JsonObject serializer and deserializer not included in native image
The issue has been reported by @michalszynkiewicz. So just re-transcribing:

It seems that in 0.17.0, the (Vert.x) JsonObject serializer and deserializer are not embedded in the native image. 

https://gist.github.com/michalszynkiewicz/d527479cc4ce72a1addc61801ba34458

```
2019-06-24 13:50:52,040 ERROR [io.sma.rea.mes.imp.ConfiguredChannelFactory] (main) Unable to create the publisher or subscriber during initialization: org.apache.kafka.common.config.ConfigException: Invalid value io.vertx.kafka.client.serialization.JsonObjectDeserializer for configuration value.deserializer: Class io.vertx.kafka.client.serialization.JsonObjectDeserializer could not be found.
        at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:718)
        at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:471)
        at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:464)
        at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:62)
        at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:75)
        at org.apache.kafka.clients.consumer.ConsumerConfig.<init>(ConsumerConfig.java:511)
        at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:624)
        at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:605)
        at io.vertx.kafka.client.consumer.KafkaReadStream.create(KafkaReadStream.java:98)
        at io.vertx.kafka.client.consumer.KafkaConsumer.create(KafkaConsumer.java:74)
        at io.vertx.reactivex.kafka.client.consumer.KafkaConsumer.create(KafkaConsumer.java:180)
        at io.smallrye.reactive.messaging.kafka.KafkaSource.<init>(KafkaSource.java:49)
        at io.smallrye.reactive.messaging.kafka.KafkaConnector.getPublisherBuilder(KafkaConnector.java:65)
        at io.smallrye.reactive.messaging.kafka.KafkaConnector_ClientProxy.getPublisherBuilder(Unknown Source)
        at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory.createPublisherBuilder(ConfiguredChannelFactory.java:147)
        at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory.lambda$register$5(ConfiguredChannelFactory.java:125)
        at java.util.HashMap.forEach(HashMap.java:1289)
        at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory.register(ConfiguredChannelFactory.java:125)
        at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory.initialize(ConfiguredChannelFactory.java:120)
        at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory_ClientProxy.initialize(Unknown Source)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
        at io.smallrye.reactive.messaging.extension.MediatorManager.initializeAndRun(MediatorManager.java:104)
        at io.smallrye.reactive.messaging.extension.MediatorManager_ClientProxy.initializeAndRun(Unknown Source)
        at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle.onApplicationStart(SmallRyeReactiveMessagingLifecycle.java:18)
        at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle_Observer_onApplicationStart_4e8937813d9e8faff65c3c07f88fa96615b70e70.notify(Unknown Source)
        at io.quarkus.arc.EventImpl$Notifier.notify(EventImpl.java:228)
        at io.quarkus.arc.EventImpl.fire(EventImpl.java:69)
        at io.quarkus.arc.runtime.LifecycleEventRunner.fireStartupEvent(LifecycleEventRunner.java:23)
        at io.quarkus.arc.runtime.ArcDeploymentTemplate.handleLifecycleEvents(ArcDeploymentTemplate.java:99)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent24.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent24.deploy(Unknown Source)
        at io.quarkus.runner.ApplicationImpl1.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:84)
        at io.quarkus.runtime.Application.run(Application.java:196)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)

java.lang.RuntimeException: org.apache.kafka.common.config.ConfigException: Invalid value io.vertx.kafka.client.serialization.JsonObjectDeserializer for configuration value.deserializer: Class io.vertx.kafka.client.serialization.JsonObjectDeserializer could not be found.
        at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle.onApplicationStart(SmallRyeReactiveMessagingLifecycle.java:20)
        at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle_Observer_onApplicationStart_4e8937813d9e8faff65c3c07f88fa96615b70e70.notify(Unknown Source)
        at io.quarkus.arc.EventImpl$Notifier.notify(EventImpl.java:228)
        at io.quarkus.arc.EventImpl.fire(EventImpl.java:69)
        at io.quarkus.arc.runtime.LifecycleEventRunner.fireStartupEvent(LifecycleEventRunner.java:23)
        at io.quarkus.arc.runtime.ArcDeploymentTemplate.handleLifecycleEvents(ArcDeploymentTemplate.java:99)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent24.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent24.deploy(Unknown Source)
        at io.quarkus.runner.ApplicationImpl1.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:84)
        at io.quarkus.runtime.Application.run(Application.java:196)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
```

### PR DESCRIPTION
**Pull request by cescoffier**
Fix  #2944.

### CODE REVIEW

File: extensions/smallrye-reactive-messaging-kafka/deployment/src/main/java/io/quarkus/smallrye/reactivemessaging/kafka/deployment/KafkaCodecProcessor.java [hunk 1]
```diff
@@ -24,10 +23,9 @@
     };
 
     @BuildStep
-    public void build(CombinedIndexBuildItem indexBuildItem, BuildProducer<ReflectiveClassBuildItem> reflectiveClass) {
-
+    public void build(BuildProducer<ReflectiveClassBuildItem> reflectiveClass) {
         for (Class<?> s : BUILT_INS) {
-            reflectiveClass.produce(new ReflectiveClassBuildItem(true, false, s.toString()));
+            reflectiveClass.produce(new ReflectiveClassBuildItem(true, false, s.getName()));
```
Comment (gsmet) [inline extensions/smallrye-reactive-messaging-kafka/deployment/src/main/java/io/quarkus/smallrye/reactivemessaging/kafka/deployment/KafkaCodecProcessor.java]: Outch :).

**Review by gsmet — APPROVED** [review]

**Review by emmanuelbernard — APPROVED** [review]

**Comment by michalszynkiewicz** [comment]
thanks @cescoffier !
