### PR TITLE
Properly include logging filters in named handlers

### LINKED ISSUE #32291: Logging: filter not set on named handler
### Describe the bug

As per the documentation, we could use the following property to set a filter on a Named Handler:
```
quarkus.log.handler.console."console-handlers".filter
```

I tried this:
```properties
quarkus.log.handler.console."my-handler".format=HANDLED: %d{dd/MM/yyyy HH:mm:ss.SSS} %-5p %X{APP_UUID} [%c{1.}] (%t) %s%e%n
quarkus.log.handler.console."my-handler".filter=my-filter
quarkus.log.category."io.my.tool".handlers=my-handler
```

with the filter:
```java
@LoggingFilter(name = "my-filter")
public final class MyFilter implements Filter {
    
    public MyFilter() {
        super();
    }

    @Override
    public boolean isLoggable(LogRecord record) {
        if(record instanceof ExtLogRecord) {
            ExtLogRecord extRecord = (ExtLogRecord) record;
            extRecord.setMessage("Filtered: " + extRecord.getMessage());
            return true;
        }
        
        return false;
    }

}
```
Unfortunately, the filter is not set on the in the named handler so I get:
```
HANDLED: [...] my message
```
i was expected:
```
HANDLED: [...] Filtered: my message
```

### Expected behavior

The filter should be set in the named handler

### Actual behavior

The filter is not set in the named handler

### How to Reproduce?

1. define a filter class with @LoggingFilter annotation.
2. define a console named handler that use this filter.
3. use the named handler on a category to get some logs processed by the handler.

### Output of `uname -a` or `ver`

windows 10

### Output of `java -version`

java 11

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.16.4.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn 3.8.4

### Additional information

The name handler is created in the method LoggingSetupRecorder.initializeLogging and the filter are not set because validateFilters is false: https://github.com/quarkusio/quarkus/blob/5ec91a97418bbeb48069b932d5916f67d35728dd/core/runtime/src/main/java/io/quarkus/runtime/logging/LoggingSetupRecorder.java#L220

I don't know if it should be true or if the filters should be set latter in the method.

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #32291

### CODE REVIEW

File: core/runtime/src/main/java/io/quarkus/runtime/logging/LoggingSetupRecorder.java [hunk 1]
```diff
@@ -327,7 +327,7 @@ public static void initializeBuildTimeLogging(LogConfig config, LogBuildTimeConf
 
         Map<String, Handler> namedHandlers = createNamedHandlers(config, consoleConfig, Collections.emptyList(),
                 Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), errorManager, logCleanupFilter,
-                Collections.emptyMap(), launchMode, dummy, true);
+                Collections.emptyMap(), launchMode, dummy, false);
```
Comment (geoand) [inline core/runtime/src/main/java/io/quarkus/runtime/logging/LoggingSetupRecorder.java:330]: In the build time initialization we don't want filters, as can be seen in line `323` already.
If we don't make this `false`, JBossLogManager rightly complains about not being able to find a filter.

**Review by gsmet — APPROVED** [review]
