### PR TITLE
Compatibility with configuration cache for image tasks

### LINKED ISSUE #42256: Gradle early task configuration causes ` quarkus.container-image.` properties to be ignored
### Describe the bug

When resolving early a project's configurations in gradle build for exemple with 
```kotlin
tasks.all {
    println("Hello")
}
```
the properties related to ` quarkus.container-image.` cannot be overriden by the usual means.
Setting a system property, a build property through the `quarkus` extension, or in a application.properties does not override it.

The only way to override the property is through `project.ext.set`.

### Expected behavior

Setting a system property or a build property through the `quarkus` extension,or in a application.properties should override the container properties, no matter if an early task configuration occured.

### Actual behavior

Properties cannot be overriden

### How to Reproduce?

A reproducer is available here [https://github.com/Malandril/quarkus-image-properties](https://github.com/Malandril/quarkus-image-properties).
You can run `./gradlew quarkusShowEffectiveConfig -Dquarkus.container-image.push=false` and see that the property is still set to true although it was set to false in application.properties, quarkus build properties and system properties.

Removing the `tasks.all` in the gradle build file, the build behaves as expected.

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

3.13.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by cdsap**
**ImageTask Compatibility with Configuration Cache:**
The current issues identified are:
* When the task configuration is incorrect, the abort method in `QuarkusBuildTask` is called. This method accesses the incompatible object getProject().
* Disabling the task execution during runtime is also not compatible with the configuration cache.
* Accessing project dependencies to retrieve extensions to get the builder name.
* The ImageTasks are finalized by `QuarkusBuild`.

The proposal includes:
* Creating a new task(`ImageCheckRequirementsTask`) that checks for the extensions. These extensions are retrieved from the Application Model, which was previously serialized with the extensions included and is compatible with the configuration cache.
ImagePush/ImageBuild will depend on this new task. If the required extension is not found, we can safely fail the build without mutating the state of quarkusBuild.
* Introducing a new BuildService(`ForcedPropertieBuildService`) to represent the additional forcedProperties used across different tasks in the QuarkusBuildTasks family. This shared object is used during the build to add additional properties, such as those used by the ImageTasks, and could be utilized for future tasks (the next step will involve evaluating Deploy tasks).
* The proposal also includes new integration tests for the ImageBuild task, testing for incorrect configurations due to the lack of extensions, and verifying the configuration cache compatibility when building the Docker image, covering isolated projects as well.

Fixes https://github.com/quarkusio/quarkus/issues/42256

### CODE REVIEW

**Comment by Malandril** [comment]
This also fixes #42256

File: devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/ImageCheckRequirementsTask.java [hunk 1]
```diff
@@ -0,0 +1,121 @@
...
+    }
+
+    Optional<ImageCheckRequirementsTask.Builder> builderFromSystemProperties() {
+        return Optional.ofNullable(System.getProperty(QUARKUS_CONTAINER_IMAGE_BUILDER))
+                .filter(BUILDERS::containsKey)
+                .map(BUILDERS::get);
+    }
+
+    List<ImageCheckRequirementsTask.Builder> availableBuilders() throws IOException {
+        // This will only pickup direct dependencies and not transitives
```
Comment (aloubyansky) [inline devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/ImageCheckRequirementsTask.java:64]: The way it looks it will iterate over all the dependencies, not just the direct ones.

**Comment by aloubyansky** [comment]
@cdsap thanks! I added a minor comment, could you please check? I'd like to make sure we are on the same page on dependency processing.

File: devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/ImageCheckRequirementsTask.java (hunk 1 above)
Comment (cdsap) [reply devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/ImageCheckRequirementsTask.java:64]: I think you're right, the dependencies used here are the ones set in the ApplicationModel(through the `QuarkusApplicationModelTask`).
The original code(that was implemented in the `ImageTask`) was:
```
        // This will only pickup direct dependencies and not transitives
        // This means that extensions like quarkus-container-image-openshift via quarkus-openshift are not picked up
        // So, let's relax our filters a bit so that we can pickup quarkus-openshift directly (relax the prefix requirement).
        return getProject().getConfigurations()
                .getByName(ToolingUtils.toDeploymentConfigurationName(
                        ApplicationDeploymentClasspathBuilder.getFinalRuntimeConfigName(LaunchMode.NORMAL)))
                .getDependencies().stream()
```
So I understand `appModel.getDependencies()` include dependencies and extension dependencies. I could filter by deployment flags, what do you think?

Comment (aloubyansky) [reply devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/ImageCheckRequirementsTask.java:64]: Those already are all the deployment dependencies. So perhaps simply the comment needs to be adjusted?

Comment (cdsap) [reply devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/ImageCheckRequirementsTask.java]: 881b93757db4b7b1d95f0b5494ff7548fc774da1

**Review by aloubyansky — APPROVED** [review]

**Comment by aloubyansky** [comment]
It doesn't seem like these changes should cause those CI failures.
