### PR TITLE
Trim container-image configuration values

### LINKED ISSUE #19956: Automatically remove trailing spaces in the application.properties file
### Description

Trailing spaces after property in the `application.properties` file can cause unwanted errors.
Example:
1. generate an application with the `quarkus-openshift` extension
2. specify `quarkus.application.name=myservice ` (with a trailing space)
3. mvn clean package 
4. Build error 
```
Build step io.quarkus.container.image.deployment.ContainerImageProcessor#publishImageInfo threw an exception: java.lang.IllegalArgumentException: The supplied combination of container-image group 'kshpak' and name 'myservice ' is invalid
```

Is there a reason to leave trimming on developers?

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by geoand**
These values must be trimmed or else the container-image build fails.

Fixes: #19956

### CODE REVIEW

**Review by gsmet — APPROVED** [review]

**Comment by geoand** [comment]
Failures are related.
I'll take a look later

**Review by iocanel — APPROVED** [review]
LGTM

File: extensions/container-image/deployment/src/main/java/io/quarkus/container/image/deployment/ContainerImageConfig.java [hunk 1]
```diff
@@ -102,6 +106,9 @@
         if (group.isPresent()) {
             String originalGroup = group.get();
             if (originalGroup.equals(System.getProperty("user.name"))) {
+                if (originalGroup.isEmpty()) {
```
Comment (gsmet) [inline extensions/container-image/deployment/src/main/java/io/quarkus/container/image/deployment/ContainerImageConfig.java:109]: Hmmm. So the converter makes the string always present?

Comment (geoand) [reply extensions/container-image/deployment/src/main/java/io/quarkus/container/image/deployment/ContainerImageConfig.java:109]: Seems to be the case...

Comment (gsmet) [reply extensions/container-image/deployment/src/main/java/io/quarkus/container/image/deployment/ContainerImageConfig.java:109]: If it is, that's definitely not what I expected. I would have expected the Optional to stay empty if no string is defined. Let's wait for @radcortez 's opinion on this :).

Comment (geoand) [reply extensions/container-image/deployment/src/main/java/io/quarkus/container/image/deployment/ContainerImageConfig.java:109]: Yeah, I agree

Comment (radcortez) [reply extensions/container-image/deployment/src/main/java/io/quarkus/container/image/deployment/ContainerImageConfig.java:109]: The issue here is that the Converter must return `null` if there is no value. From the Config rules, an empty String `""` is automatically converted to `null`, but in the case of this `TrimmedStringConverter` the conversion is the empty String again, which is then passed to the Optional, so you get a non empty Optional.

The `TrimmedStringConverter` must return a `null` if the resulting String is an empty String. Now we may need to recheck other usages of this converter to make sure we don't break it.
