### PR TITLE
Workaround graal#3003 by passing IncludeResources via AutomaticFeature

### LINKED ISSUE #13472: Workaround graal#3003 by passing IncludeResources via AutomaticFeature instead of command line argument
https://github.com/oracle/graal/issues/3003 makes our ResourcesITCase fail on GraalVM 20.3.0
A workaround is possible to pass the IncludeResources via AutomaticFeature instead of command line argument. 
The workaround would unblock the upgrade to GraalVM 20.3.0.

A PR follows.

### PR DESCRIPTION
**Pull request by ppalaga**
instead of command line argument

Fix #13472

### CODE REVIEW

File: core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageAutoFeatureStep.java [hunk 1]
```diff
@@ -62,44 +53,25 @@
...
+            "com.oracle.svm.core.configure.ResourcesRegistry",
+            "ignoreResources", void.class, String.class);
     static final String RUNTIME_REFLECTION = RuntimeReflection.class.getName();
     static final String JNI_RUNTIME_ACCESS = "com.oracle.svm.core.jni.JNIRuntimeAccess";
     static final String BEFORE_ANALYSIS_ACCESS = Feature.BeforeAnalysisAccess.class.getName();
     static final String DYNAMIC_PROXY_REGISTRY = "com.oracle.svm.core.jdk.proxy.DynamicProxyRegistry";
     static final String LOCALIZATION_FEATURE = "com.oracle.svm.core.jdk.LocalizationFeature";
 
-    @BuildStep
-    List<NativeImageResourceBuildItem> registerPackageResources(
```
Comment (mkouba) [inline core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageAutoFeatureStep.java:72]: Why do you remove this method? `NativeImageResourceDirectoryBuildItem` does not seem to be related to the `-H:IncludeResources` problem, or?

Comment (mkouba) [reply core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageAutoFeatureStep.java:72]: Ah, I see the method was just moved..

File: core/deployment/src/main/java/io/quarkus/deployment/builditem/nativeimage/NativeImageResourcePatternsBuildItem.java [hunk 2]
```diff
@@ -0,0 +1,76 @@
...
+import java.util.Collections;
+import java.util.List;
+import java.util.stream.Stream;
+
+import io.quarkus.builder.item.MultiBuildItem;
+import io.quarkus.deployment.util.GlobUtil;
+
+/**
+ * A build item that indicates that a set of resource paths defined by regular expression patterns or globs should be
+ * included in the native image. This uses native-image's {@code -H:IncludeResources} under the hood.
```
Comment (mkouba) [inline core/deployment/src/main/java/io/quarkus/deployment/builditem/nativeimage/NativeImageResourcePatternsBuildItem.java:14]: I thought that the purpose of this PR is to avoid `-H:IncludeResources` completely?

File: core/deployment/src/main/java/io/quarkus/deployment/builditem/nativeimage/NativeImageResourcePatternsBuildItem.java [hunk 3]
```diff
@@ -0,0 +1,76 @@
...
+import java.util.Collection;
+import java.util.Collections;
+import java.util.List;
+import java.util.stream.Stream;
+
+import io.quarkus.builder.item.MultiBuildItem;
+import io.quarkus.deployment.util.GlobUtil;
+
+/**
+ * A build item that indicates that a set of resource paths defined by regular expression patterns or globs should be
```
Comment (mkouba) [inline core/deployment/src/main/java/io/quarkus/deployment/builditem/nativeimage/NativeImageResourcePatternsBuildItem.java:13]: Maybe it wouldn't hurt to explain what `globs` means...

File: core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageAutoFeatureStep.java (hunk 1 above)
Comment (ppalaga) [reply core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageAutoFeatureStep.java:72]: Yes, I only move it to another class, where I add another related method.

File: core/deployment/src/main/java/io/quarkus/deployment/builditem/nativeimage/NativeImageResourcePatternsBuildItem.java (hunk 2 above)
Comment (ppalaga) [reply core/deployment/src/main/java/io/quarkus/deployment/builditem/nativeimage/NativeImageResourcePatternsBuildItem.java:14]: Haha, true, I have added the comment some time ago, when the migration away from the CLI was not planned yet. I should change the wording. I should say something like "it is using the same mechanism as native-image's -H:IncludeResources command line option".

File: core/deployment/src/main/java/io/quarkus/deployment/builditem/nativeimage/NativeImageResourcePatternsBuildItem.java (hunk 3 above)
Comment (ppalaga) [reply core/deployment/src/main/java/io/quarkus/deployment/builditem/nativeimage/NativeImageResourcePatternsBuildItem.java:13]: Yeah, let me do that. I should also add some JavaDoc to the builder methods.

**Comment by ppalaga** [comment]
I have improved the comments in f671833. Could you please re-review, @mkouba ?

**Review by mkouba — APPROVED** [review]
LGTM but it would be good if someone more specialized on native image generation could review this PR as well. Maybe @machi1990 or @gwenneg?

**Comment by machi1990** [comment]
> LGTM but it would be good if someone more specialized on native image generation could review this PR as well. Maybe @machi1990 or @gwenneg?

Me neither, my knowledge on this (especially usage of automatic feature) is basic. Perhaps we could get one of @dmlloyd @zakkak @galderz to review this?

**Comment by ppalaga** [comment]
Any gizmo expert could please review this?

File: core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageAutoFeatureStep.java [hunk 4]
```diff
@@ -201,6 +173,21 @@ public void write(String s, byte[] bytes) {
...
 
+        /* Resource includes and excludes */
+        if (!resourcePatterns.isEmpty()) {
+            ResultHandle resourcesRegistrySingleton = overallCatch.invokeStaticMethod(IMAGE_SINGLETONS_LOOKUP,
+                    overallCatch.loadClass("com.oracle.svm.core.configure.ResourcesRegistry"));
+            TryBlock tc = overallCatch.tryBlock();
+            for (NativeImageResourcePatternsBuildItem resourcePatternsItem : resourcePatterns) {
+                for (String pattern : resourcePatternsItem.getIncludePatterns()) {
+                    tc.invokeInterfaceMethod(RESOURCES_REGISTRY_ADD_RESOURCES, resourcesRegistrySingleton,
+                            overallCatch.load(pattern));
```
Comment (gsmet) [inline core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageAutoFeatureStep.java:184]: you should use `tc` here to load the pattern.

**Review by gsmet — CHANGES_REQUESTED** [review]
Added a small comment.

Shouldn't we have a test for that?

Because we are generating code that we don't test? Or is there an existing test for that?

File: core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageAutoFeatureStep.java (hunk 4 above)
Comment (ppalaga) [reply core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageAutoFeatureStep.java:184]: Thanks, let me have a look.

**Comment by ppalaga** [comment]
> houldn't we have a test for that?
> 
> Because we are generating code that we don't test? Or is there an existing test for that?

Yes, there is `io.quarkus.it.main.ResourcesTestCase`. It is passing on GraalVM 20.2.0 and failing on GraalVM 20.3.0 before this fix and passing again after this fix.

File: core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageAutoFeatureStep.java (hunk 4 above)
Comment (ppalaga) [reply core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageAutoFeatureStep.java]: fixed in 8f5c2b5

**Review by gsmet — APPROVED** [review]

**Review by zakkak — APPROVED** [review]
I don't feel qualified to comment on the code, but the changes look good to me.
I have also tested the changes with mandrel 20.3.0.0.Beta2 and they do fix the issue with ResourcesITCase

**Comment by ppalaga** [comment]
@zakkak our of my curiosity: are there more tests failing on GraalVM/Mandrel 20.3.0?

**Comment by zakkak** [comment]
> @zakkak our of my curiosity: are there more tests failing on GraalVM/Mandrel 20.3.0?

Yes, Redis Client (https://github.com/quarkusio/quarkus/issues/12434) and from the Main suite `io.quarkus.it.main.ImageIOITCase` are failing (probably https://github.com/quarkusio/quarkus/issues/13567 related)

**Comment by ppalaga** [comment]
Is this still waiting for a Gizmo expert review? (Sorry @gsmet, I don't know if you count as one.)

**Comment by gsmet** [comment]
I don't really count as one but it's simple enough for me to check :).
