### PR TITLE
Re-authenticate users if the OIDC session cookie can not be read

### LINKED ISSUE #46765: OIDC session cookie format changed in 3.18 causing it to be incompatible to 3.17.x
### Describe the bug

The format of the quarkus oidc session cookie changed from version 3.17.x to 3.18 which causes a breaking change.

Format in Quarkus 3.17.x: idToken | accessToken | refreshToken
Format in Quarkus 3.18.x:  idToken | accessToken | accessTokenExpiresIn | refreshToken

When a user stil has a cookie created by quarkus 3.17, but the applicaiton is already on quarkus 3.18 (typically happens when deploying a new version), then quarkus throws an unhandled exception:

````
Unhandled exception: java.lang.NumberFormatException: For input string: "XXXXXXXXXXXXXXXXXXXXXXXXXX"
    at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
    at java.base/java.lang.Long.parseLong(Long.java:708)
    at java.base/java.lang.Long.valueOf(Long.java:1156)
    at io.quarkus.oidc.runtime.DefaultTokenStateManager.getTokens(DefaultTokenStateManager.java:128)
    at io.quarkus.oidc.runtime.DefaultTokenStateManager_ClientProxy.getTokens(Unknown Source)
    at io.quarkus.oidc.runtime.CodeAuthenticationMechanism.reAuthenticate(CodeAuthenticationMechanism.java:338)
    at io.quarkus.oidc.runtime.CodeAuthenticationMechanism$1.apply(CodeAuthenticationMechanism.java:102)
    at io.quarkus.oidc.runtime.CodeAuthenticationMechanism$1.apply(CodeAuthenticationMechanism.java:99)
    at io.smallrye.context.impl.wrappers.SlowContextualFunction.apply(SlowContextualFunction.java:21)
````
 

### Expected behavior

If a user arrives with a session cookie that is for whatever reason not valid (old format, malicious format, ...), then quarkus deletes the session cookie such that the user can re-authenticate.

### Actual behavior

User receives an unexpected error message.
The session cookie is not deleted.
User cannot recover easily from this failure.
User has to delete the cookie activly to recover from this failure. (which is something a normal user cannot do)

### How to Reproduce?

1) Run an application with Quarkus 3.17
2) Login into this application.
3) Keep your browser session open
4) Upgrade your application to Quarkus 3.18 and run it
5) Refresh your browser session from step 2) => you see an exception 

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

3.18.x

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sberyozkin**
Fixes #46765.

The internal session cookie format changed in 3.18, which, given it is not part of the API, should not have caused any issues. However, in advanced OIDC applications, what happens, as explained by @sschellh, is that there could be a large number of currently logged in users  possibly in different regions, which have not had time to logout before the new Quarkus release is deployed. thus keeping the existing session cookies. 

For example, a user logged in the morning, the session is active for 8 hours, new Quarkus is deployed at lunch time, and the user can not access the application after lunch.

In such cases,  if the internal session format changes, currently, Quarkus, after failing to parse the cookie content, stops users in their tracks with `401` which is not a good user experience.

Instead, Quarkus should remove the session cookie it can not parse and request re-authentication - the user may not even notice if the OIDC provider's own session cookies still valid.

This is what this simple PR does - deletes the session cookie (this is already done on main and tested) but instead of terminating the flow with 401, it forces the re-authentication with 302.

### CODE REVIEW

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/DefaultTokenStateManager.java [hunk 1]
```diff
@@ -149,7 +159,15 @@ public Uni<AuthorizationCodeTokens> getTokens(RoutingContext routingContext, Oid
                     try {
                         accessTokenExpiresIn = accessTokenData[1].isEmpty() ? null : Long.valueOf(accessTokenData[1]);
                     } catch (ArrayIndexOutOfBoundsException ex) {
-                        return Uni.createFrom().failure(new AuthenticationCompletionException("Session cookie is malformed"));
+                        final String error = "Session cookie is malformed";
+                        LOG.debug(ex);
+                        // Make this error message visible in the dev mode
+                        return Uni.createFrom().failure(new AuthenticationFailedException(error));
+                    } catch (NumberFormatException ex) {
+                        final String error = "Access token expires_in property in the session cookie must be a number";
```
Comment (gastaldi) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/DefaultTokenStateManager.java:167]: It would be nice if we had the value that was found, for debugging purposes
```suggestion
                        final String error = "Access token expires_in property in the session cookie must be a number, found %s";
```

**Review by gastaldi — APPROVED** [review]
Approved, but I wonder if we can improve that error message with some useful data

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/DefaultTokenStateManager.java (hunk 1 above)
Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/DefaultTokenStateManager.java]: @gastaldi Sure, took me a little while to experiment with getting to that value from different branches, so I wrapped the actual parsing cal in a function to make it easier, hope it looks better
