### PR TITLE
Fix combination of multiple `@Nested` tests with root lifecycle methods

### LINKED ISSUE #19843: JUnit @Nested with @QuarkusTest with @BeforeEach on Root-Class fails (Since 2.2.1.Final)
### Describe the bug

The error is present only since the upgrade from `2.2.0.CR1` to `2.2.1.Final`

If there is a `@BeforeEach` at the top level in a test with `@Nested` classes, only the first test runs through. The rest fail due to an IllegalArgumentException.

The error occurs from the second test on, no matter if multiple  `@Nested` with one test each or one  `@Nested` class with multiple tests.

**Example multiple Nested**
```
@QuarkusTest
public class NestedQuarkusTest {

    @BeforeEach
    void generalBeforeEach() {
    }

    @Nested
    class Foo {
        @Test
        void check() {
            Assertions.assertTrue(true);
        }
    }

    @Nested
    class Bar {
        @Test
        void check() {
            Assertions.assertTrue(true);
        }
    }

}
```

**Example one Nested with multiple tests**
```
@QuarkusTest
public class OneNestedQuarkusTestWithBeforeEach {
   
    @BeforeEach
    void generalBeforeEach() {
    }

    @Nested
    class Foo {
        @Test
        void checkA() {
            Assertions.assertTrue(true);
        }

        @Test
        void checkB() {
            Assertions.assertTrue(true);
        }
    }

}
```

### Expected behavior

`@BeforeEach` should be performed for each test and the tests above should pass.

### Actual behavior

```
java.lang.IllegalArgumentException: object is not an instance of declaring class

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:1084)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptBeforeEachMethod(QuarkusTestExtension.java:905)
	...
```

In `io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:1084)` the `@BeforeEach` method is invoked on the nested class instead of the "root class".

### How to Reproduce?

Reproducer: https://github.com/vonatzigenc/reproducer-nested-quarkustest

Run tests:
- https://github.com/vonatzigenc/reproducer-nested-quarkustest/blob/main/src/test/java/org/acme/OneNestedQuarkusTestWithBeforeEach.java
- https://github.com/vonatzigenc/reproducer-nested-quarkustest/blob/main/src/test/java/org/acme/MultipleNestedQuarkusTestWithBeforeEach.java

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.2.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by famod**
Fixes #19843

Also enhances `tcclMethodCache` to cover negative lookups.

### CODE REVIEW

**Comment by famod** [comment]
Btw, I actually created that new test _without_ `@QuarkusTest` and only added it when all was green with plain JUnit.

**Review by geoand — APPROVED** [review]

**Comment by famod** [comment]
That failure doesn't look related, the test failed here as well: #19914

**Comment by stuartwdouglas** [comment]
Yea, there is a continuous testing race that is causing failures that I have not been able to track down yet.

File: test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java [hunk 1]
```diff
@@ -1102,10 +1101,16 @@ private Object runExtensionMethod(ReflectiveInvocationContext<Method> invocation
 
     private Method determineTCCLExtensionMethod(Method originalMethod, Class<?> c)
             throws ClassNotFoundException {
-        Method newMethod = tcclMethodCache.get(originalMethod);
-        if (newMethod != null) {
-            return newMethod;
+
+        // cacheKey contains identity hash code of the method instead of the more expensive toString
+        // and it has to be "contextualized" with the given class (here, name is good enough)
+        final String cacheKey = System.identityHashCode(originalMethod) + "_" + c.getName();
```
Comment (stuartwdouglas) [inline test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java:1107]: Hash codes are not really guaranteed to be unique, so there is the possibility here for this to go wrong.

**Review by stuartwdouglas — DISMISSED** [review]

File: test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java (hunk 1 above)
Comment (famod) [reply test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java:1107]: Are you sure the _identity_ hash code can clash? This is _not_ the regular hash code of `method` that doesn't contain method parameters (which can clash easily).

Comment (gsmet) [reply test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java:1107]: Are we sure this cache brings something to the plate? Because I see a lot of questions and adjustments and I haven't seen any proof this was any useful?

Comment (famod) [reply test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java:1107]: It does cut down the invocation quantity quite a bit: https://github.com/quarkusio/quarkus/pull/19751#discussion_r698059833
But I haven't done any runtime measurements, so call it premature optimization if you like.
Let me check real quick...

Comment (famod) [reply test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java]: I decided to remove the cache as the benefit is barely measurable and there seems to be no "efficient" cache key that covers all concerns.

**Comment by famod** [comment]
None of those tests fail locally. I'll go ahead and merge this to get the 2.2.1 regression fixed in 2.2.2.
