### PR TITLE
QuarkusTest: veto all test classes belonging to a different test profile

### LINKED ISSUE #45308: IfBuildProfile does not work on scheduler classes
I have the following class

```java
@IfBuildProfile(anyOf = {"dev", "prod", "RateLimitSchedulerProfile"})
public class RateLimitScheduler {

    @Scheduled(every = "1s")
    public void schedule() {
        System.out.println("hello " + System.currentTimeMillis());
    }
}
```

And the following test

```java
public class RateLimitSchedulerProfile implements QuarkusTestProfile {
    @Override
    public String getConfigProfile() {
        return "test,RateLimitSchedulerProfile";
    }
}

@QuarkusTest
@TestProfile(RateLimitSchedulerProfile.class)
class RateLimitSchedulerTest {

    @Inject
    RateLimitScheduler rateLimitScheduler;

    @Test
    void test() {
        System.out.println("RateLimitSchedulerTest:");
        rateLimitScheduler.schedule();
    }

}
```

This test fails with 

```text
[ERROR] Errors: 
[ERROR]   HelloResourceTest.testHelloEndpoint » Runtime java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: jakarta.enterprise.inject.spi.DeploymentException: jakarta.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type gr.RateLimitScheduler and qualifiers [@Default]
	- injection target: gr.RateLimitSchedulerTest#rateLimitScheduler
	- declared on CLASS bean [types=[gr.RateLimitSchedulerTest, java.lang.Object], qualifiers=[@Default, @Any], target=gr.RateLimitSchedulerTest]
	The following classes match by type, but have been skipped during discovery:
	- gr.RateLimitScheduler was annotated with @Vetoed


	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1576)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:338)
	at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:178)
	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:492)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)
	at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)
	at java.base/java.lang.Thread.run(Thread.java:1583)
	at org.jboss.threads.JBossThread.run(JBossThread.java:499)
Caused by: jakarta.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type gr.RateLimitScheduler and qualifiers [@Default]
	- injection target: gr.RateLimitSchedulerTest#rateLimitScheduler
	- declared on CLASS bean [types=[gr.RateLimitSchedulerTest, java.lang.Object], qualifiers=[@Default, @Any], target=gr.RateLimitSchedulerTest]
	The following classes match by type, but have been skipped during discovery:
	- gr.RateLimitScheduler was annotated with @Vetoed


	at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:547)
	at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:697)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:323)
	... 12 more
```

In order to "fix" it i would have to use the `%test.quarkus.scheduler.enabled=false` and delete the `@IfBuildProfile` from RateLimitSchedulerProfile class.

Note: The test which fails is not the RateLimitSchedulerTest but the HelloResourceTest. If i disable the HelloResourceTest it works.

[Reproducer](https://github.com/gbourant/quarkus-scheduler-bug)

### PR DESCRIPTION
**Pull request by mkouba**
- fixes #45308

Zulip discussion: https://quarkusio.zulipchat.com/#narrow/channel/187038-dev/topic/QuarkusTest.20-.20all.20tests.20classes.20always.20registered.20as.20beans

### CODE REVIEW

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/TestsAsBeansProcessor.java [hunk 1]
```diff
@@ -46,6 +55,36 @@ public void testClassBeans(List<TestClassBeanBuildItem> items, BuildProducer<Add
...
+                                return true;
+                            }
+                            String testProfileClassName = testProfile.get().getTestProfileClassName();
+                            String annotationProfileClassName = testProfileAnnotation.value().asClass().name().toString();
+                            return !testProfileClassName.equals(annotationProfileClassName);
+                        }
+                    }
+                    return false;
+                })
+                .transform(tc -> tc.add(AnnotationInstance.builder(DotNames.VETOED).buildWithTarget(tc.declaration()))));
```
Comment (Ladicek) [inline extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/TestsAsBeansProcessor.java:85]: It doesn't hurt, but `buildWithTarget(tc.declaration())` isn't be necessary, that's done behind the scenes automatically. Just a note, no need to change.

**Review by Ladicek — APPROVED** [review]
LGTM!

**Review by manovotn — APPROVED** [review]
LGTM, thank you for diving into it :)

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/TestsAsBeansProcessor.java (hunk 1 above)
Comment (mkouba) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/TestsAsBeansProcessor.java:85]: I don't think it does when you build a new `AnnotationInstance` using a builder. You're talking about `org.jboss.jandex.AnnotationOverlayImpl.TransformationContextImpl.add(Class<? extends Annotation>)`, right?

Comment (Ladicek) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/TestsAsBeansProcessor.java:85]: Right.

**Comment by manovotn** [comment]
@mkouba the CI failures are related.
For nested test classes we automatically assume the outer class is a CDI bean and attempt to initialize it as such which fails with the changes present here (the outer class will be vetoed).

**Comment by mkouba** [comment]
> @mkouba the CI failures are related. For nested test classes we automatically assume the outer class is a CDI bean and attempt to initialize it as such which fails with the changes present here (the outer class will be vetoed).

Well, that's a bit weird because in this particular test the enclosing test class has a different profile...

**Review by manovotn — APPROVED** [review]
