### PR TITLE
Adjusted ArcProxyBeanMetaDataClassNormalizer.normalize() work with to deeper hierarchies

### LINKED ISSUE #18388: @InjectSpy and @InjectMock cause @Valid behaviour change
## Describe the bug

When using `@io.quarkus.test.junit.mockito.InjectMock` or `@io.quarkus.test.junit.mockito.InjectSpy` for a bean that has methods using `@javax.validation.Valid`, validations are being skipped.

### Expected behavior

If `@InjectMock` along with `.callRealMethod()`, or if `@InjectSpy` are used on a method that has `@Valid`, I expect the system to validate the bean accordingly.

### Actual behavior

The system is running as if no validations were set up, leading to errors and failing tests.

## To Reproduce

I built a [project](https://github.com/tioback/quarkus-mock-and-validate) to reproduce the problem, so just `mvn test` it.

### Configuration

It's all in the project.

### Output of `uname -a` or `ver`

    Darwin Renatos-MacBook-Pro-2.local 19.6.0 Darwin Kernel Version 19.6.0: Thu May  6 00:48:39 PDT 2021; root:xnu-6153.141.33~1/RELEASE_X86_64 x86_64

### Output of `java -version`

```console
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10)
OpenJDK 64-Bit Server VM (build 11.0.7+10, mixed mode)
```

### Quarkus version or git rev

    2.0.0.Final
    1.13.7.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

```console
--2021-07-04 21:27:08--  https://repo.maven.apache.org/maven2/io/takari/maven-wrapper/0.5.6/maven-wrapper-0.5.6.jar
Resolving repo.maven.apache.org... 199.232.192.215, 199.232.196.215
Connecting to repo.maven.apache.org|199.232.192.215|:443... connected.
OpenSSL: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Unable to establish SSL connection.
Error: Could not find or load main class org.apache.maven.wrapper.MavenWrapperMain
Caused by: java.lang.ClassNotFoundException: org.apache.maven.wrapper.MavenWrapperMain
```

## Additional context
(Add any other context about the problem here.)

I'm running this through `IntelliJ IDEA 2021.1.3`. 

Despite the sample project using 2.0.0.Final, the same problem happens on 1.13.7.Final.

From what I could tell, when either `InjectMock` or `InjectSpy` are used, the generated subclasses are called in an order that affects the Validation behaviour.

More specifically, at `validateParameters(T, java.lang.reflect.Executable, java.lang.Object[], java.lang.Class<?>...)`:

```java
// Dependency: hibernate-validator-6.2.0.Final.jar
package org.hibernate.validator.internal.engine;

public class ValidatorImpl {

    private <T> Set<ConstraintViolation<T>> validateParameters(T object, Executable executable, Object[] parameterValues, Class<?>... groups) {
        sanityCheckGroups(groups);

        @SuppressWarnings("unchecked")
        Class<T> rootBeanClass = object != null ? (Class<T>) object.getClass() : (Class<T>) executable.getDeclaringClass();
        BeanMetaData<T> rootBeanMetaData = beanMetaDataManager.getBeanMetaData(rootBeanClass);

        if (!rootBeanMetaData.hasConstraints()) {
            return Collections.emptySet();
        }

        ExecutableValidationContext<T> validationContext = getValidationContextBuilder().forValidateParameters(
                rootBeanClass,
                rootBeanMetaData,
                object,
                executable,
                parameterValues
        );

        ValidationOrder validationOrder = determineGroupValidationOrder(groups);

        validateParametersInContext(validationContext, parameterValues, validationOrder);

        return validationContext.getFailingConstraints();
    }
}
```

At the `rootBeanMetaData.hasConstraints()` check, when using Spies or Mocks, the variable is false.

After some debugging, I noticed that this happens because Spies and Mocks cause the use of `org.hibernate.validator.internal.metadata.PredefinedScopeBeanMetaDataManager.UninitializedBeanMetaData.hasConstraints` as the BeanMetadData implementation.
Which in turn led me to this:

```java
// Dependency: hibernate-validator-6.2.0.Final.jar
package org.hibernate.validator.internal.metadata;

public class PredefinedScopeBeanMetaDataManager implements BeanMetaDataManager {
    
    @Override
    public <T> BeanMetaData<T> getBeanMetaData(Class<T> beanClass) {
        Class<?> normalizedBeanClass = beanMetaDataClassNormalizer.normalize( beanClass );
        BeanMetaData<T> beanMetaData = (BeanMetaData<T>) beanMetaDataMap.get( normalizedBeanClass );
        if ( beanMetaData == null ) {
            // note that if at least one element of the hierarchy is constrained, the child classes should really be initialized
            // otherwise they will be considered unconstrained.
            beanMetaData = (BeanMetaData<T>) beanMetaDataMap.computeIfAbsent( normalizedBeanClass, UninitializedBeanMetaData::new );
        }
        return beanMetaData;
    }
}
```

That comment about child classes seems to be the reason this is happening.

Before I start working on a solution, I was wondering if someone has a word on that.

### PR DESCRIPTION
**Pull request by tioback**
Fixes #18388 by allowing `javax.validation` to work with multi-level hierarchies.

From: Class (1) - (?) Subclass
To: Class (1) - (*) Subclass

### CODE REVIEW

**Comment by tioback** [comment]
I'm having some issues with the formatter properly ordering the imports at the Test class.
I'll push a new commit when I figure out what's going on.

File: integration-tests/hibernate-validator/src/test/java/io/quarkus/hibernate/validator/runtime/ArcProxyBeanMetaDataClassNormalizerTest.java [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+
+import io.quarkus.arc.Subclass;
+import io.quarkus.test.junit.QuarkusTest;
+import org.junit.jupiter.api.DisplayName;
+import org.junit.jupiter.api.Test;
+
+import static org.junit.jupiter.api.Assertions.assertEquals;
+
+/**
+ * Tests class normalization, which translates int:o getting the "original" class, without all the specializations instances of
```
Comment (gsmet) [inline integration-tests/hibernate-validator/src/test/java/io/quarkus/hibernate/validator/runtime/ArcProxyBeanMetaDataClassNormalizerTest.java:11]:
```suggestion
 * Tests class normalization, which translates into getting the "original" class, without all the specializations instances of
```

File: extensions/hibernate-validator/runtime/src/main/java/io/quarkus/hibernate/validator/runtime/ArcProxyBeanMetaDataClassNormalizer.java [hunk 2]
```diff
@@ -6,16 +6,21 @@
...
     @Override
     public <T> Class<? super T> normalize(Class<T> beanClass) {
-        if (Subclass.class.isAssignableFrom(beanClass)) {
-            return beanClass.getSuperclass();
+        if (!Subclass.class.isAssignableFrom(beanClass)) {
+            return beanClass;
         }
 
-        return beanClass;
+        return normalize(beanClass.getSuperclass());
```
Comment (gsmet) [inline extensions/hibernate-validator/runtime/src/main/java/io/quarkus/hibernate/validator/runtime/ArcProxyBeanMetaDataClassNormalizer.java:23]: Any chance you could implement it with a loop rather than recursion? I agree that we should have things nested too much but it's good practice to avoid recursion when you can.

**Review by gsmet — CHANGES_REQUESTED** [review]
Thanks! Indeed that's a good idea.

I added a few comments. As for the formatting, following https://github.com/quarkusio/quarkus/blob/main/CONTRIBUTING.md#ide-config-and-code-style should work.

File: extensions/hibernate-validator/runtime/src/main/java/io/quarkus/hibernate/validator/runtime/ArcProxyBeanMetaDataClassNormalizer.java (hunk 2 above)
Comment (tioback) [reply extensions/hibernate-validator/runtime/src/main/java/io/quarkus/hibernate/validator/runtime/ArcProxyBeanMetaDataClassNormalizer.java:23]: I was avoiding loops because it looked uglier.

In this case, in don't see I scenario where the recursion could go bad, but sure, I'll rewrite it.

**Comment by tioback** [comment]
> Thanks! Indeed that's a good idea.
> 
> I added a few comments. As for the formatting, following https://github.com/quarkusio/quarkus/blob/main/CONTRIBUTING.md#ide-config-and-code-style should work.

I've followed it to the letter since my previous contribution.

I thought it had something to do with some recent IntelliJ update, but I've just tested it again and found out the issue:

image

If you check that little ticker, then this happens:

1. Original unformatted code
```java
// before formatting
package io.quarkus.hibernate.validator.runtime;import org.junit.jupiter.api.DisplayName;import static org.junit.jupiter.api.Assertions.assertEquals;import io.quarkus.test.junit.QuarkusTest;import org.junit.jupiter.api.Test;import io.quarkus.arc.Subclass;
```

2. Eclipse Code Formatter runs correctly

```java
package io.quarkus.hibernate.validator.runtime;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import io.quarkus.arc.Subclass;
import io.quarkus.test.junit.QuarkusTest;
```

3. _Optimize imports on the fly_ messes it all up

```java
package io.quarkus.hibernate.validator.runtime;

import io.quarkus.arc.Subclass;
import io.quarkus.test.junit.QuarkusTest;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
```

I've disabled the _Optimize imports on the fly_ and now it works as expected.

File: extensions/hibernate-validator/runtime/src/main/java/io/quarkus/hibernate/validator/runtime/ArcProxyBeanMetaDataClassNormalizer.java [hunk 3]
```diff
@@ -6,16 +6,21 @@
 
 /**
  * In the case of a proxy generated by Arc, return the parent class.
+ * <br />
+ * This can have more than one level of hierarchy, in example:
+ * <ul>
+ * <li>When using @{@link InjectMock} or @{@link InjectSpy}</li>
```
Comment (mkouba) [inline extensions/hibernate-validator/runtime/src/main/java/io/quarkus/hibernate/validator/runtime/ArcProxyBeanMetaDataClassNormalizer.java:12]: I don't think that this javadoc is rendered correctly. I think that you should use a FQCN here, i.e. something like `{@link io.quarkus.test.junit.mockito.InjectMock}`.

File: extensions/hibernate-validator/runtime/src/main/java/io/quarkus/hibernate/validator/runtime/ArcProxyBeanMetaDataClassNormalizer.java (hunk 2 above)
Comment (gsmet) [reply extensions/hibernate-validator/runtime/src/main/java/io/quarkus/hibernate/validator/runtime/ArcProxyBeanMetaDataClassNormalizer.java]: Yeah, I agree it's uglier but that's a good habit to have.

**Review by gsmet — APPROVED** [review]
Thanks for the contribution! I'll backport it to the next 2.0.x.

**Comment by geoand** [comment]
Are we good to go with this one?
