### PR TITLE
GeneratedResourceBuildItem may also be filtered and ignoredEntries from plugins is now used

### LINKED ISSUE #10406: Specifying ignoredEntries for quarkus-maven-plugin has no effect
**Describe the bug**
Specifying `<ignoredEntries><ignoredEntry>` settings in quarkus-maven-plugin maven configuration has no effect.
The resulting uberJar still contains all files that are marked for exclusion.

**Expected behavior**
Specified exclusions are processed and the listed files are excluded from the uberJar.

**Actual behavior**
Files matching specified exclusions are excluded from resulting jar.

**To Reproduce**
1. mvn clean package

**Configuration**
Plugin configuration in the pom.xml:
```xml
         <plugin>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-maven-plugin</artifactId>
            <version>${quarkus.version}</version>
            <executions>
               <execution>
                  <goals>
                     <goal>build</goal>
                  </goals>
                  <configuration>
                     <uberJar>true</uberJar>
                     <ignoredEntries>
                        <ignoredEntry>META-INF/swagger-ui-files/swagger-ui-bundle.js.map</ignoredEntry>
                        <ignoredEntry>META-INF/swagger-ui-files/swagger-ui-standalone-preset.js.map</ignoredEntry>
                     </ignoredEntries>
                  </configuration>
               </execution>
            </executions>
         </plugin>
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Windows 10x64
 - Output of `java -version`: 
   ```
   openjdk version "11.0.7" 2020-04-14
   OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
   OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)
   ```
 - GraalVM version (if different from Java): n/a
 - Quarkus version or git rev: 1.5.2.Final and 1.6.0.CR1
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3 

**Additional information:**
Looking at the source code of the Quarkus Maven Build Goal, it seems like someone forgot to actually implement processing of `ignoredEntries`: https://github.com/quarkusio/quarkus/blob/1.6.0.CR1/devtools/maven/src/main/java/io/quarkus/maven/BuildMojo.java#L126 
A private field `ignoredEntries` is defined but it is not used in the code.

### PR DESCRIPTION
**Pull request by gastaldi**
Fixes #10406

### CODE REVIEW

**Comment by gsmet** [comment]
I'm in the process of finalizing 1.6.0. This is too much of a change to be included last minute IMO and needs proper review.

**Comment by gastaldi** [comment]
It shouldn't impact the existing behavior (much) AFAIK, but that's fine, we can put in a 1.6.1 or 1.7.x if you prefer

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/JarResultBuildStep.java [hunk 1]
```diff
@@ -784,21 +787,24 @@ private void doLegacyThinJarGeneration(CurateOutcomeBuildItem curateOutcomeBuild
         final Map<String, List<byte[]>> services = new HashMap<>();
 
         final List<AppDependency> appDeps = curateOutcomeBuildItem.getEffectiveModel().getUserDependencies();
+        final Set<String> finalIgnoredEntries = new HashSet<>(IGNORED_ENTRIES);
+        packageConfig.userConfiguredIgnoredEntries.ifPresent(finalIgnoredEntries::addAll);
```
Comment (aloubyansky) [inline core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/JarResultBuildStep.java:791]: Aren't we supporting ignored entries only for the uber jar packaging?

**Review by aloubyansky — CHANGES_REQUESTED** [review]
Unless we are rushing it in we need a test this time.

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/JarResultBuildStep.java (hunk 1 above)
Comment (gastaldi) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/JarResultBuildStep.java:791]: Yes, I added support for thin JARs too (when the resource is inside the project). This may be useful for files that should be ignored while creating the JAR

**Comment by gastaldi** [comment]
> Unless we are rushing it in we need a test this time.

Agreed, I'll add for Gradle and Maven as well

**Review by aloubyansky — APPROVED** [review]
Great
