### PR TITLE
Fix DefaultTokenIntrospectionUserInfoCache injection

### LINKED ISSUE #21925: DefaultTokenIntrospectionUserInfoCache is not injected
### Describe the bug

@FroMage has found it can not be injected as a default cache bean as the synthetic bean only provides `DefaultTokenIntrospectionUserInfoCache.class`.

Adding `UserInfoCache.class` and `TokenIntrospectionCache.class` with the synthetic bean will do it. 

We already have a test but `DefaultTokenIntrospectionUserInfoCache` is injected into a custom alternative priority bean implementing `UserInfoCache` and `TokenIntrospectionCache`.  So a test involving a default cache has to be added

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sberyozkin**
Fixes #21925

This cache is already tested in `integration-tests/oidc-tenancy` [here](https://github.com/quarkusio/quarkus/blob/main/integration-tests/oidc-tenancy/src/test/java/io/quarkus/it/keycloak/BearerTokenAuthorizationTest.java#L347) and [here](https://github.com/quarkusio/quarkus/blob/main/integration-tests/oidc-tenancy/src/test/java/io/quarkus/it/keycloak/BearerTokenAuthorizationTest.java#L374). But it is injected into a [custom bean](https://github.com/quarkusio/quarkus/blob/main/integration-tests/oidc-tenancy/src/main/java/io/quarkus/it/keycloak/CustomIntrospectionUserInfoCache.java) to also verify it can be replaced - the custom bean is injected as an alternative implementation.

It has been confirmed twice by @FroMage and reported by a user on Zulip that it can not be injected as either `UserInfoCache` or `TokenIntrospectionCache`. As Steph confirmed the problem was using the `DefaultTokenIntrospectionUserInfoCache.class` alone with the synthetic bean (I assumed its interfaces would be used as well).

So this PR does a simple update to the `DefaultTokenIntrospectionUserInfoCache` bean registration and updates `oidc-wiremock` test to verify the default cache is activated. This cache is activated globally (and uses a single entry to store both the introspection and userinfo data) but individual tenants can disable either the token introspection or useinfo cache or both - so in the test I disable the token introspection for the bearer token tests - without it, depending on which order tests run, one of the CodeFlow tests expecting a `0` cache size will get `1` instead even though it does not use the cache.

Also did another clarification to the docs.

@FroMage Steph, I've reviewed the guide and Java docs and with the latest Java doc update IMHO it is all very clear and non-ambiguous. Note the cache can't start taking entries by default nor can it grow unconstrained, but I also did not want users to type 2 properties to activate it (enable, max-size), hence it is only `token-cache.max-size` which is enough to have it activated.

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]

**Review by stuartwdouglas — APPROVED** [review]

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcConfig.java [hunk 1]
```diff
@@ -30,7 +30,9 @@
     public Map<String, OidcTenantConfig> namedTenants;
 
     /**
-     * Default TokenIntrospection and UserInfo Cache configuration which is used for all the tenants if it is enabled.
+     * Default TokenIntrospection and UserInfo Cache configuration which is used for all the tenants if it is enabled
+     * with the build-time 'quarkus.oidc.default-token-cache-enabled' property ('true' by default) and also activated,
+     * see its `max-size` property.
```
Comment (FroMage) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcConfig.java:35]: Sorry I think this is too schizophreniac for me: the cache is enabled by default, but also disabled because its max-size is 0. I have no idea how you can justify this.

Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcConfig.java:35]: Hi @FroMage Sure lets continue, I'll be happy to adjust, if we agree on what has to be adjusted :-)
So the build time enable property is only about making this default cache available, it is like we have `enabled` property for different extensions, incl. OIDC. So it makes this bean available around, no more. 
We can't have it starting accumulating the data OOB - it would be a security risk - the users have to decide themselves if they'd like to cache - i.e, avoid re-verifying the token or refreshing the user info.
So this bean is around, and now if they users want to activate it then they'd to configure the size. I've checked the docs, everywhere there is a distinction between enabling and activating it.

How would you expect it to be enabled/activated in the configuration ? Please keep it in mind - it can't get the data by default, the data  size have to be constrained.

Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcConfig.java:35]: @FroMage,

```
@ConfigRoot
public class OidcBuildTimeConfig {
    ...
    /**
     * Enable the registration of the Default TokenIntrospection and UserInfo Cache implementation bean.
     * Note it only allows to use the default implementation, one needs to configure it in order to activate it,
     * please see {@link OidcConfig#tokenCache}.
     */
    @ConfigItem(defaultValue = "true")
    public boolean defaultTokenCacheEnabled;
}
```

Does it clarify it ? It s really the same way with `quarkus-oidc` and other extensions where we can enable it (default is enabled) but unless you configure them they won't do any useful work...
