### PR TITLE
Use specific case for Lambda's `ObjectMapper`

### LINKED ISSUE #24284: AWS Lambda throws IllegalStateException: Missing HTTP method in request event
### Describe the bug

Every time a HTTP request hits the AWS Lambda, we are receiving the following error: 

```
java.lang.IllegalStateException: Missing HTTP method in request event
at io.quarkus.amazon.lambda.http.LambdaHttpHandler.nettyDispatch(LambdaHttpHandler.java:176)
at io.quarkus.amazon.lambda.http.LambdaHttpHandler.handleRequest(LambdaHttpHandler.java:63)
at io.quarkus.amazon.lambda.http.LambdaHttpHandler.handleRequest(LambdaHttpHandler.java:43)
at io.quarkus.amazon.lambda.runtime.AmazonLambdaRecorder$1.processRequest(AmazonLambdaRecorder.java:164)
at io.quarkus.amazon.lambda.runtime.AbstractLambdaPollLoop$1.run(AbstractLambdaPollLoop.java:126)
at java.lang.Thread.run(Thread.java:829)
at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:600)
at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
```

We use the latest Quarkus version.

### Expected behavior

Lambda is starting and handeling the request

### Actual behavior

java.lang.IllegalStateException: Missing HTTP method in request event whenever a request hits the Lambda

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

11

### GraalVM version (if different from Java)

graalvm-ce-java11-linux-amd64-21.3.1

### Quarkus version or git rev

2.7.4.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
- Fixes: #24284

### CODE REVIEW

File: extensions/amazon-lambda/common-runtime/src/main/java/io/quarkus/amazon/lambda/runtime/AmazonLambdaMapperRecorder.java [hunk 1]
```diff
@@ -25,7 +26,8 @@ public void initObjectMapper() {
                 .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)
                 .configure(MapperFeature.ACCEPT_CASE_INSENSITIVE_PROPERTIES, true)
                 .registerModule(new JodaModule())
-                .registerModule(new DateModule());
+                .registerModule(new DateModule())
+                .setPropertyNamingStrategy(PropertyNamingStrategies.LOWER_CAMEL_CASE);
```
Comment (gsmet) [inline extensions/amazon-lambda/common-runtime/src/main/java/io/quarkus/amazon/lambda/runtime/AmazonLambdaMapperRecorder.java:30]: Won't you affect the default `ObjectMapper` by doing this, or does it create a copy?

From what I can see, the OP was complaining about interactions between the main `ObjectMapper` and this one.

Comment (geoand) [reply extensions/amazon-lambda/common-runtime/src/main/java/io/quarkus/amazon/lambda/runtime/AmazonLambdaMapperRecorder.java:30]: > Won't you affect the default ObjectMapper by doing this, or does it create a copy?

Nope because  `getObjectMapper()` is already a copy

> From what I can see, the OP was complaining about interactions between the main ObjectMapper and this one.

Exactly. Because this was a copy of the main one, when the case on the main one was changed, this mapper inherited the change

Comment (gsmet) [reply extensions/amazon-lambda/common-runtime/src/main/java/io/quarkus/amazon/lambda/runtime/AmazonLambdaMapperRecorder.java:30]: Raaaaaah, I read the code and missed the `.copy()` :)

**Review by gsmet — APPROVED** [review]

File: extensions/amazon-lambda/common-runtime/src/main/java/io/quarkus/amazon/lambda/runtime/AmazonLambdaMapperRecorder.java (hunk 1 above)
Comment (geoand) [reply extensions/amazon-lambda/common-runtime/src/main/java/io/quarkus/amazon/lambda/runtime/AmazonLambdaMapperRecorder.java:30]: 🙏🏽
