### PR TITLE
Correctly handle REST field injection

### LINKED ISSUE #45789: [resteasy-reactive] [3.8.6] Header not reset between request
### Describe the bug

When a header is injected directy in a Endpoint class, this header is not clean between two request.

Exemple:
```java
@Path("/hello")
public class GreetingResource {

    @HeaderParam("filter")
    String filter;

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        return "Header: %s".formatted(filter);
    }
}
```

On first call without the header `filter`, the value of `filter` is `null`.
On second call with the header `filter` with the value 'my filter', the value of `filter` is 'my filter'.
On third call without the header `filter`, the value of `filter` is 'my filter'.

FI: I have the same issue with the 3.15.3

### Expected behavior

On third call without the header `filter`, the value should be `null`.

### Actual behavior

The third call keep the value of the second one

### How to Reproduce?

[repro-header.zip](https://github.com/user-attachments/files/18505606/repro-header.zip)

Small reproducer. Use the `/hello` with a header `header` once with a value, and without a value.

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

openjdk version "17.0.12" 2024-07-16

### Quarkus version or git rev

3.8.6

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

apache-maven-3.9.0

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
This is done by converting the Resource class to
`@RequestScoped` when possible and failing the build when it's not

- Fixes: #45789

### CODE REVIEW

File: extensions/resteasy-reactive/rest/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/QuarkusServerEndpointIndexer.java [hunk 1]
```diff
@@ -274,4 +277,24 @@ protected void warnAboutMissUsedBodyParameter(DotName httpMethod, MethodInfo met
         super.warnAboutMissUsedBodyParameter(httpMethod, methodInfo);
     }
 
+    /**
+     * At this point we know exactly which resources will require field injection and therefore a required to be
```
Comment (FroMage) [inline extensions/resteasy-reactive/rest/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/QuarkusServerEndpointIndexer.java:281]:
```suggestion
     * At this point we know exactly which resources will require field injection and therefore are required to be
```

File: extensions/resteasy-reactive/rest/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/QuarkusServerEndpointIndexer.java [hunk 2]
```diff
@@ -274,4 +277,24 @@ protected void warnAboutMissUsedBodyParameter(DotName httpMethod, MethodInfo met
...
+     * {@link RequestScoped}.
+     * We can't create change anything CDI related at this point (because it would create build cycles), so all we can do
```
Comment (FroMage) [inline extensions/resteasy-reactive/rest/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/QuarkusServerEndpointIndexer.java:283]:
```suggestion
     * We can't change anything CDI related at this point (because it would create build cycles), so all we can do
```

File: extensions/resteasy-reactive/rest/deployment/src/test/java/io/quarkus/resteasy/reactive/server/test/injection/HeaderFieldInSuperClassNoScopeTest.java [hunk 3]
```diff
@@ -0,0 +1,48 @@
...
+                org.junit.jupiter.api.Assertions.assertEquals(DeploymentException.class, t.getClass());
+            });
+
+    @Test
+    public void test() {
+        Assertions.fail("should never have run");
+    }
+
+    @Path("/test")
+    public static class Resource extends AbstractResource {
```
Comment (FroMage) [inline extensions/resteasy-reactive/rest/deployment/src/test/java/io/quarkus/resteasy/reactive/server/test/injection/HeaderFieldInSuperClassNoScopeTest.java:32]: Why is this not `@RequestScoped`-implied?

**Review by FroMage — APPROVED** [review]
I'm not sure why the inherited fields don't make the class auto-`@RequestScoped`.

**Comment by geoand** [comment]
> I'm not sure why the inherited fields don't make the class auto-@RequestScoped.

The point of the test is to show that the auto-conversion mechanism is best effort. In this specific case we could do extra work to figure out that field injection is needed, but it will never be as complete as the EndpointIndexer and thus we need to be able to fail the build when the best effort conversion was not enough

**Comment by geoand** [comment]
This is a breaking change, but I think it's backport is warranted @gsmet @cescoffier

**Comment by FroMage** [comment]
> The point of the test is to show that the auto-conversion mechanism is best effort. In this specific case we could do extra work to figure out that field injection is needed, but it will never be as complete as the EndpointIndexer and thus we need to be able to fail the build when the best effort conversion was not enough

OK, we can always improve later

**Comment by geoand** [comment]
I actually might have to do it now because some of the TCK tests are failing...

**Comment by geoand** [comment]
PR updated

**Review by FroMage — APPROVED** [review]
