### PR TITLE
Controller advice exception content type

### LINKED ISSUE #5816: Take controller method into account for setting content-type in @RestControllerAdvice
Currently the generated `javax.ws.rs.ext.ExceptionMapper` set `application/json` as the content type of the response when the handler method of the `@RestControllerAdvice` returns an object.

This is fine for most cases, but there can be a case where the controller method needs to return say XML (which is specified in the `@RequestMapping`) then the generated `ExceptionMapper` should not force JSON.

The proper way to handle this is to include 

`@Context ResourceInfo resourceInfo` 

in generated the `ExceptionMapper` and use that to if there are any annotations on the original controller method (that threw the exception) that set the content type. 

This is a follow up from [this](https://github.com/quarkusio/quarkus/pull/5803#discussion_r351340721) discussion

### PR DESCRIPTION
**Pull request by gytis**
Fixes https://github.com/quarkusio/quarkus/issues/5816

cc @geoand

### CODE REVIEW

**Comment by geoand** [comment]
Thanks Gytis!

I'll take a look soon. 

Can you please squash the commits though?

**Comment by gytis** [comment]
I was planning to squash them after the review, thought it make it easier for you to review the changes. But if you prefer, I could squash them now.

**Comment by geoand** [comment]
You can go ahead and squash, reviewing shouldn't be a problem.

**Comment by geoand** [comment]
I took a quick look at it and it looks good! But of course I'll need to spend more time with it.

File: extensions/spring-web/deployment/src/main/java/io/quarkus/spring/web/deployment/ControllerAdviceAbstractExceptionMapperGenerator.java [hunk 1]
```diff
@@ -27,12 +29,17 @@
...
 import io.quarkus.spring.web.runtime.ResponseEntityConverter;
 
 class ControllerAdviceAbstractExceptionMapperGenerator extends AbstractExceptionMapperGenerator {
 
     private static final DotName RESPONSE_ENTITY = DotName.createSimple("org.springframework.http.ResponseEntity");
-    private static final DotName STRING = DotName.createSimple(String.class.getName());
+
+    private static final List<String> TEXT_MEDIA_TYPES = Arrays.asList(
+            MediaType.TEXT_PLAIN, MediaType.APPLICATION_JSON, MediaType.APPLICATION_XML, MediaType.TEXT_XML);
+    private static final List<String> OBJECT_MEDIA_TYPES = Arrays.asList(
```
Comment (geoand) [inline extensions/spring-web/deployment/src/main/java/io/quarkus/spring/web/deployment/ControllerAdviceAbstractExceptionMapperGenerator.java]: I am not sure I understand the distinction betweem `TEXT_MEDIA_TYPES` and `OBJECT_MEDIA_TYPES`. They seem to contains the same values?

File: extensions/spring-web/deployment/src/main/java/io/quarkus/spring/web/deployment/ResponseBuilder.java [hunk 2]
```diff
@@ -0,0 +1,46 @@
...
+
+import static io.quarkus.gizmo.MethodDescriptor.ofMethod;
+
+import javax.ws.rs.core.MediaType;
+import javax.ws.rs.core.Response;
+
+import io.quarkus.gizmo.MethodCreator;
+import io.quarkus.gizmo.ResultHandle;
+
+final class ResponseBuilder {
```
Comment (geoand) [inline extensions/spring-web/deployment/src/main/java/io/quarkus/spring/web/deployment/ResponseBuilder.java]: +1

File: extensions/spring-web/runtime/src/main/java/io/quarkus/spring/web/runtime/ResponseContentTypeResolver.java [hunk 3]
```diff
@@ -0,0 +1,56 @@
...
+        ServerDrivenNegotiation negotiation = new ServerDrivenNegotiation();
+        negotiation.setAcceptHeaders(acceptHeaders);
+
+        return negotiation.getBestMatch(variants);
+    }
+
+    private static List<Variant> getMediaTypeVariants(String... mediaTypes) {
+        Variant.VariantListBuilder variantListBuilder = Variant.VariantListBuilder.newInstance();
+
+        Arrays.stream(mediaTypes)
```
Comment (geoand) [inline extensions/spring-web/runtime/src/main/java/io/quarkus/spring/web/runtime/ResponseContentTypeResolver.java]: Generally we try to stay away from lambdas in code that exists in runtime. The reason is that they introduce a small memory overhead.
Now of course this code is not on the critical, but I think we should try and get rid of the lambdas nonetheless in this case, since it will very use a for loop that will be just as readable

File: integration-tests/spring-web/src/main/java/io/quarkus/it/spring/web/ExceptionThrowingController.java [hunk 4]
```diff
@@ -10,49 +11,63 @@
...
-        throw new IllegalArgumentException("hello from error");
+    @GetMapping("/re/void/xml")
+    public void voidWithResponseEntityExceptionAsXml() {
+        throw new HandledResponseEntityException("bad state", MediaType.APPLICATION_XML);
     }
 
-    @GetMapping("/re")
-    public ResponseEntity<Greeting> responseEntityWithIllegalArgumentException() {
-        throw new IllegalStateException("hello from error");
+    @GetMapping(value = "/pojo/re")
```
Comment (geoand) [inline integration-tests/spring-web/src/main/java/io/quarkus/it/spring/web/ExceptionThrowingController.java]: Perhaps drop `value`?

File: integration-tests/spring-web/src/main/java/io/quarkus/it/spring/web/ExceptionThrowingController.java [hunk 5]
```diff
@@ -10,49 +11,63 @@
...
+    public ResponseEntity responseEntityWithPojoException() {
+        throw new HandledPojoException("bad state");
     }
 
+    @GetMapping(value = "/pojo/pojo")
```
Comment (geoand) [inline integration-tests/spring-web/src/main/java/io/quarkus/it/spring/web/ExceptionThrowingController.java]: Same here

File: integration-tests/spring-web/src/main/java/io/quarkus/it/spring/web/ExceptionThrowingController.java [hunk 6]
```diff
@@ -10,49 +11,63 @@
...
+    public Greeting pojoWithPojoException() {
+        throw new HandledPojoException("bad state");
+    }
+
+    @GetMapping("/pojo/void")
+    public void voidWithPojoException() {
+        throw new HandledPojoException("bad state");
+    }
+
+    @GetMapping(value = "/string")
```
Comment (geoand) [inline integration-tests/spring-web/src/main/java/io/quarkus/it/spring/web/ExceptionThrowingController.java]: And here

**Comment by geoand** [comment]
Seems like the imports are not sorted:

```
[ERROR] Failed to execute goal net.revelc.code:impsort-maven-plugin:1.2.0:check (check-imports) on project quarkus-spring-web: Imports are not sorted in /home/vsts/work/1/s/extensions/spring-web/runtime/src/main/java/io/quarkus/spring/web/runtime/ResponseContentTypeResolver.java -> [Help 1]
```

So what you need to do is basically do an `mvn process-resources` and the just commit the changes

File: extensions/spring-web/deployment/src/main/java/io/quarkus/spring/web/deployment/ControllerAdviceAbstractExceptionMapperGenerator.java (hunk 1 above)
Comment (geoand) [reply extensions/spring-web/deployment/src/main/java/io/quarkus/spring/web/deployment/ControllerAdviceAbstractExceptionMapperGenerator.java]: Aha, gotcha! Perhaps a comment in the code is in order? Because now it looks like a prime target for refactoring 😂

**Comment by geoand** [comment]
Thanks for the updates @gytis!

I'll try and a proper review soon

**Comment by gsmet** [comment]
@geoand I'll let you tell me if you want that backported.

**Comment by geoand** [comment]
@gsmet I hope to be able to review tomorrow and hopefully we can get it in for backporting

**Comment by geoand** [comment]
@gytis this part of the docs should also be updated: https://github.com/quarkusio/quarkus/blob/master/docs/src/main/asciidoc/spring-web.adoc#L247

File: extensions/spring-web/deployment/src/main/java/io/quarkus/spring/web/deployment/ControllerAdviceAbstractExceptionMapperGenerator.java [hunk 7]
```diff
@@ -104,89 +113,87 @@ protected void preGenerateMethodBody(ClassCreator cc) {
                     "Parameter type " + parameterTypes.get(notAllowedParameterIndex).name() + " is not supported for method"
                             + controllerAdviceMethod.name() + " of class" + controllerAdviceMethod.declaringClass().name());
         }
+
+        injectHttpHeadersField(cc);
+    }
+
+    private void injectHttpHeadersField(ClassCreator classCreator) {
```
Comment (geoand) [inline extensions/spring-web/deployment/src/main/java/io/quarkus/spring/web/deployment/ControllerAdviceAbstractExceptionMapperGenerator.java]: Minor complaint: I would call this `createHttpHeadersField`. The reason is that this part of the is actually creating a field in bytecode, it's not actually doing any injection which you obvisouly know happens at runtime.

**Comment by geoand** [comment]
Excellent work if I may say so @gytis! Once you take care of the minor comments I have we can get this in.

**Comment by gytis** [comment]
> @gytis this part of the docs should also be updated: https://github.com/quarkusio/quarkus/blob/master/docs/src/main/asciidoc/spring-web.adoc#L247

Hmm, it's a bit tricky, because we've only changed @ExceptionHandler content type for controller advice.

**Comment by geoand** [comment]
> > @gytis this part of the docs should also be updated: https://github.com/quarkusio/quarkus/blob/master/docs/src/main/asciidoc/spring-web.adoc#L247
> 
> Hmm, it's a bit tricky, because we've only changed @ExceptionHandler content type for controller advice.

OK let's leave it as is for now

**Review by geoand — APPROVED** [review]
Thanks a lot @gytis!!!
