### PR TITLE
Use a stack to store the TCCL

### LINKED ISSUE #47657: Using nested JUnit test classes with QuarkusTest breaks non-Quarkus tests
### Describe the bug

I have a test annotated with `@QuarkusTest` which includes some `@Nested` classes. This is fine on its own but it breaks non-Quarkus tests in some weird and wonderful ways.

For example:

```
✗ ./gradlew test       

> Task :test FAILED

GreetingResourceTest > testHelloEndpoint() FAILED
    java.util.ServiceConfigurationError: io.smallrye.config.SmallRyeConfigFactory: io.quarkus.runtime.configuration.QuarkusConfigFactory not a subtype
        at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:593)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1244)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
        at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
        at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
        at io.smallrye.config.SmallRyeConfigProviderResolver.getFactoryFor(SmallRyeConfigProviderResolver.java:102)
        at io.smallrye.config.SmallRyeConfigProviderResolver.getConfig(SmallRyeConfigProviderResolver.java:78)
        at io.smallrye.config.SmallRyeConfigProviderResolver.getConfig(SmallRyeConfigProviderResolver.java:66)
        at io.quarkus.test.config.TestConfigProviderResolver.getConfig(TestConfigProviderResolver.java:36)
        at org.eclipse.microprofile.config.ConfigProvider.getConfig(ConfigProvider.java:85)
        at org.acme.GreetingResource.<init>(GreetingResource.kt:12)
        at org.acme.GreetingResourceTest.testHelloEndpoint(GreetingResourceTest.kt:8)

2 tests completed, 1 failed
```

This is in Quarkus 3.22.0; earlier versions are not affected.

### Expected behavior

Having nested test classes in a Quarkus test should not affect other tests.

### Actual behavior

Having nested test classes in a Quarkus test breaks non-Quarkus tests.

### How to Reproduce?

Reproducer: [quarkus-reproducer.zip](https://github.com/user-attachments/files/20008450/quarkus-reproducer.zip)

** Steps to reproduce **

1. Run `./gradlew test`

** Expected result **

The build succeeds.

** Actual result **

The build fails due to failing tests.

Note that ` ./gradlew test --tests GreetingResourceTest` and `./gradlew test --tests GreetingResourceQuarkusTest` both succeed.

### Output of `uname -a` or `ver`

Darwin Rods-MacBook-Pro.local 24.4.0 Darwin Kernel Version 24.4.0: Fri Apr 11 18:33:40 PDT 2025; root:xnu-11417.101.15~117/RELEASE_ARM64_T6031 arm64

### Output of `java -version`

openjdk version "21.0.6" 2025-01-21 OpenJDK Runtime Environment Homebrew (build 21.0.6) OpenJDK 64-Bit Server VM Homebrew (build 21.0.6, mixed mode, sharing)

### Quarkus version or git rev

3.22.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.14

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by holly-cummins**
Used for resetting at the end of QuarkusTests and avoid having two code paths both trying to do TCCL-ing.

At first glance, #47657 looked simple. The cause was that we weren't resetting the TCCL back to to the system classloader at the end of quarkus test execution, so plain tests were then being run with the `QuarkusClassLoader`, which did not work well. 

Digging into it, it became clear it was a bit more complex. By the time the `QuarkusTestExtension` methods run, the TCCL is already set to be a runtime classloader, so any resetting is pointless. The pre-set of the TCCL was introduced in https://github.com/quarkusio/quarkus/pull/47379. Even though it was my code it took me a while in the debugger to figure out where it was being set, so I've added some comments. The un-set in the extension listener should work to reset everything, but in nested tests, the 'old' classloader gets overwritten. I've switched to using a stack, which should help with this. 

I've also removed a whole bunch of TCCL-setting in `QuarkusTestExtension`, since we now have the 'super-wrapper' around the whole test which sets and resets the TCCL. Having other TCCL-setting is a no-op and just adds to the code complexity.

- Resolves #47657

### CODE REVIEW

**Comment by geoand** [comment]
Thanks a lot for this!

I've relaunched CI in order to see if the failures are related or just flaky tests

**Comment by holly-cummins** [comment]
> Thanks a lot for this!
> 
> I've relaunched CI in order to see if the failures are related or just flaky tests

I had a green CI, but then I switched from `Stack` to `Deque`, and added the platform tests. We run the platform ci rather rarely, so it could be something else which has caused the failures (although, let's face it, it's a classloading failure in tests, so this change is the most likely suspect :) ). The spring failure looks like a GitHub CI glitch. 

I'll have a go at reproducing the camel failures locally.

**Comment by geoand** [comment]
👌🏽

**Comment by holly-cummins** [comment]
Actually, having looked at these failures locally, I'm confident it's unrelated to my changes. I'm not seeing the runtime error, instead I'm seeing a compilation error: 

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.14.0:testCompile (default-testCompile) on project camel-quarkus-integration-test-kubernetes: Compilation failure: Compilation failure: 
[ERROR] /Users/holly/Code/quarkus/camel-quarkus/integration-tests/kubernetes/src/test/java/org/apache/camel/quarkus/component/kubernetes/it/KubernetesConfigMapTest.java:[24,48] cannot find symbol
[ERROR]   symbol:   class KubernetesServer
[ERROR]   location: package io.fabric8.kubernetes.client.server.mock
```

In the CI, `java.lang.NoClassDefFoundError: io/fabric8/kubernetes/client/server/mock/KubernetesServer` happens because `KubernetesServer` has gone away. The commit that moved quarkus to a version of the kubernetes client without that file is https://github.com/quarkusio/quarkus/commit/e114f81cb5d74f589059add21492c9a2fe80294c; camel-quarkus will need updates to adjust to the new file name.

File: test-framework/junit5/src/main/java/io/quarkus/test/junit/launcher/ExecutionListener.java [hunk 1]
```diff
@@ -44,12 +46,22 @@ public void executionFinished(TestIdentifier testIdentifier, TestExecutionResult
...
-                if (origCl != null) {
-                    // If execution is parallel this could produce odd results, but if execution is parallel any kind of TCCL manipulation will be ill-fated
-                    Thread.currentThread().setContextClassLoader(origCl);
+            if (source instanceof ClassSource cs) {
+                ClassLoader classLoader = cs.getJavaClass().getClassLoader();
+                // Only pop if we meet the conditions under which we pushed
+                if (isQuarkusTest(classLoader)) {
+                    ClassLoader cl = origCl.pop();
+                    if (cl != null) {
+                        System.out.println("HOLLY resetting to " + cl);
```
Comment (geoand) [inline test-framework/junit5/src/main/java/io/quarkus/test/junit/launcher/ExecutionListener.java:55]: We probably don't want this :)

Comment (holly-cummins) [reply test-framework/junit5/src/main/java/io/quarkus/test/junit/launcher/ExecutionListener.java:55]: zomg, good spot, thank you!

Comment (geoand) [reply test-framework/junit5/src/main/java/io/quarkus/test/junit/launcher/ExecutionListener.java]: 🙏🏽

**Review by geoand — APPROVED** [review]
Thanks!

**Comment by holly-cummins** [comment]
> @holly-cummins does it make sense to keep the platform tests around if they are just going to be failing until Camel releases? I can imagine this will cause folks some confusion...

I agree it's not ideal. They're only run if people opt-in by setting the `ci/test-platform` label, so most people wouldn't see them. It might be that @gsmet and @jamesnetherton can work out a 'next' branch to run against that would be clean. The Camel team are pro-active about monitoring their version of the platform CI and doing fixes, so the fix is there, just ... not here. :)

**Comment by geoand** [comment]
Got it, makes sense.
