### PR TITLE
Distrust maven settings location from system properties

### LINKED ISSUE #28090: cli test fails without settings.xml
### Describe the bug

If no settings.xml is present in the maven user location, cli test will fail with 3 failures and 3 errors.

```shell
./mvnw -f devtools/cli test
...
[ERROR] Tests run: 79, Failures: 3, Errors: 3, Skipped: 0
```
[Full Maven Log](https://github.com/quarkusio/quarkus/files/9607348/maven.log)

### Expected behavior

cli test should be able to run without settings.xml

### Actual behavior

Fails without settings.xml

### How to Reproduce?

1. Ensure that no user settings.xml is defined
2. Run `./mvnw -f devtools/cli test`

### Output of `uname -a` or `ver`

Darwin mavenrunner-mac 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "17.0.2" 2022-01-18

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

e19f65e535

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by AdlerFleurant**
Check if maven settings file exists when getting from system properties.
Null check on mavenSettings.
Fix nearby typos.

Fixes #28090

### CODE REVIEW

File: devtools/cli/src/test/java/io/quarkus/cli/RegistryClientBuilderTestBase.java [hunk 1]
```diff
@@ -59,7 +60,8 @@ static void setup() throws Exception {
 
         final BootstrapMavenContext mavenContext = new BootstrapMavenContext(
                 BootstrapMavenContext.config().setWorkspaceDiscovery(false));
-        final Settings settings = getBaseMavenSettings(mavenContext.getUserSettings().toPath());
+        var userSettings = mavenContext.getUserSettings();
+        final Settings settings = Objects.nonNull(userSettings) ? getBaseMavenSettings(userSettings.toPath()) : new Settings();
```
Comment (aloubyansky) [inline devtools/cli/src/test/java/io/quarkus/cli/RegistryClientBuilderTestBase.java:64]:
```suggestion
        final Settings settings = userSettings != null ? getBaseMavenSettings(userSettings.toPath()) : new Settings();
```

Alternatively, we could pass a `File` to `getBaseMavenSettings(f)` and let it handle it all.

Comment (AdlerFleurant) [reply devtools/cli/src/test/java/io/quarkus/cli/RegistryClientBuilderTestBase.java]: Change this to your alternative suggestion.

**Review by aloubyansky — APPROVED** [review]

**Comment by aloubyansky** [comment]
Thanks a lot @AdlerFleurant

File: build-parent/pom.xml [hunk 2]
```diff
@@ -1281,5 +1279,39 @@
...
+            </activation>
+            <build>
+                <pluginManagement>
+                    <plugins>
+                        <plugin>
+                            <artifactId>maven-surefire-plugin</artifactId>
+                            <version>${version.surefire.plugin}</version>
+                            <configuration>
+                                <!-- combine.self suppresses warnings about java.io.tmpdir being defined twice -->
+                                <systemPropertyVariables combine.self="override">
```
Comment (gsmet) [inline build-parent/pom.xml:1298]: And it doesn't override anything that could be useful? It looks a bit weird to me?

File: .github/workflows/ci-actions-incremental.yml [hunk 3]
```diff
@@ -42,7 +42,7 @@ concurrency:
 env:
   # Workaround testsuite locale issue
   LANG: en_US.UTF-8
-  COMMON_MAVEN_ARGS: "-e -B --settings .github/mvn-settings.xml --fail-at-end"
+  COMMON_MAVEN_ARGS: "-e -B --settings ${{ github.workspace }}/.github/mvn-settings.xml --fail-at-end"
```
Comment (gsmet) [inline .github/workflows/ci-actions-incremental.yml:45]: Is this change (and all the other similar changes) really needed?

File: core/runtime/src/main/java/io/quarkus/runtime/Quarkus.java [hunk 4]
```diff
@@ -65,7 +65,7 @@ public static void run(Class<? extends QuarkusApplication> quarkusApplication, B
             //we already have an application, run it directly
             Class<? extends Application> appClass = (Class<? extends Application>) Class.forName(Application.APP_CLASS_NAME,
                     false, Thread.currentThread().getContextClassLoader());
-            Application application = appClass.newInstance();
+            Application application = appClass.getDeclaredConstructor().newInstance();
```
Comment (gsmet) [inline core/runtime/src/main/java/io/quarkus/runtime/Quarkus.java:68]: Really, you need to refrain from including changes that have nothing to do with the issue you're fixing in a PR. It should be a different PR. You can create a PR with the various cleanups you made that is clearly identified as such.

File: devtools/cli/src/test/java/io/quarkus/cli/CliProjectJBangTest.java [hunk 5]
```diff
@@ -51,9 +51,9 @@ public void testCreateAppDefaults() throws Exception {
                 CreateProjectHelper.DEFAULT_ARTIFACT_ID,
                 CreateProjectHelper.DEFAULT_VERSION);
 
-        Path javaMain = valdiateJBangSourcePackage(project, ""); // no package name
+        Path javaMain = validateJBangSourcePackage(project, ""); // no package name
```
Comment (gsmet) [inline devtools/cli/src/test/java/io/quarkus/cli/CliProjectJBangTest.java:54]: Same here, this change has nothing to do with this PR.

I won't mark all of them but all the unrelated changes needs to be done in another PR.

**Review by gsmet — CHANGES_REQUESTED** [review]
I won't comment on the change itself, @aloubyansky already did, but I have a problem with you mixing this change with a bunch of cleanup that is totally unrelated.

If you're not able to do the split the PR easily yourself using your Git superpowers, I can do it myself.

File: .github/workflows/ci-actions-incremental.yml (hunk 3 above)
Comment (AdlerFleurant) [reply .github/workflows/ci-actions-incremental.yml:45]: This is needed because it will fail some builds due to missing settings.xml. I had this in my ci run.


2022-09-21 20:26:22 (20.9 MB/s) - ‘/home/runner/work/quarkus/quarkus/integration-tests/devtools/target/quarkus-codestart-test/quarkus-jdbc-h2-hibernate-orm-a56eccb5-3f4c-41a1-95ca-1dcadc683908/real-data/java/.mvn/wrapper/maven-wrapper.jar’ saved [59925/59925]

Error:  Error executing Maven.
Error:  The specified user settings file does not exist: /home/runner/work/quarkus/quarkus/integration-tests/devtools/target/quarkus-codestart-test/quarkus-jdbc-h2-hibernate-orm-a56eccb5-3f4c-41a1-95ca-1dcadc683908/real-data/java/.github/mvn-settings.xml

So I avoided it by adding the full path to the argument.

Comment (gsmet) [reply .github/workflows/ci-actions-incremental.yml:45]: Ah, OK, it makes sense then. Thanks for the explanation.

File: devtools/cli/src/test/java/io/quarkus/cli/CliProjectJBangTest.java (hunk 5 above)
Comment (AdlerFleurant) [reply devtools/cli/src/test/java/io/quarkus/cli/CliProjectJBangTest.java]: Updated to remove unrelated changes.

File: core/runtime/src/main/java/io/quarkus/runtime/Quarkus.java (hunk 4 above)
Comment (AdlerFleurant) [reply core/runtime/src/main/java/io/quarkus/runtime/Quarkus.java]: Updated to remove unrelated changes.

File: build-parent/pom.xml (hunk 2 above)
Comment (AdlerFleurant) [reply build-parent/pom.xml]: Instead of adding this to the global pom, I changed the code to distrust maven settings when coming from system properties.

**Comment by AdlerFleurant** [comment]
@gsmet . I think the latest changes should address your concern. I have reduced the scope of the change. I will submit another change for not using the deprecated API.

**Comment by AdlerFleurant** [comment]
@gsmet, how can I help this move forward?

**Comment by AdlerFleurant** [comment]
@gsmet, @aloubyansky,  I think we can remove some of these labels as the scope of the change was reduced to just cli.

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Yeah sorry I was busy on other things.

BTW, maybe I wasn't clear, but please push the other changes to another pull request. Cleanup is always welcome.

**Comment by gsmet** [comment]
I will rebase as somehow CI didn't start.
