### PR TITLE
Register String constructors for reflection

### LINKED ISSUE #10873: Yasson is unable to deserialize an Optional<String> in native
**Describe the bug**
Yasson is unable to deserialize a POJO with an  `Optional<String>` attribute in native mode.
There is no issue in JVM mode.

There is no stacktrace, only the following SEVER log:
```
2020-07-15 15:15:49,462 SEVERE [org.ecl.yas.int.Unmarshaller] (executor-thread-1) Unable to deserialize property 'optionalString' because of: Cannot create instance of a class: class java.lang.String, No default constructor found.
```

**Expected behavior**
Deserializing an `Optional<String>` works in both native and JVM mode.

**To Reproduce**
Running the mongodb-client integration test from the following branch: https://github.com/loicmathieu/quarkus/tree/mongodb/property-codec-provider/integration-tests/mongodb-client

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Linux 5.4.0-40-generic #44-Ubuntu SMP Tue Jun 23 00:01:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: openjdk version "11.0.7" 2020-04-14
 - GraalVM version (if different from Java): GraalVM Version 20.1.0 (Java Version 11.0.7)
 - Quarkus version or git rev: current master

### PR DESCRIPTION
**Pull request by loicmathieu**
Workaround for #10873 waiting on a fix on Yasson side

### CODE REVIEW

**Review by geoand — APPROVED** [review]
Makes sense.

But let's hope we can get rid of this soon by having Yasson provide better Optional<String> support

**Comment by loicmathieu** [comment]
@gsmet you was in the original discussion, are you OK with this fix as well ?

**Comment by gsmet** [comment]
Well, not really but better than having it failing I suppose, if we don't get a Yasson fix.

Please let the Yasson issue open as it's really something that should be fixed there.

**Comment by gsmet** [comment]
I marked this for backport as it's really something we will want in both 1.8 and 1.7.

File: extensions/jsonb/deployment/src/main/java/io/quarkus/jsonb/deployment/JsonbProcessor.java [hunk 1]
```diff
@@ -90,6 +90,10 @@ void build(BuildProducer<ReflectiveClassBuildItem> reflectiveClass,
         for (AnnotationInstance deserializeInstance : index.getAnnotations(JSONB_TYPE_DESERIALIZER)) {
             registerInstance(reflectiveClass, deserializeInstance);
         }
+
+        // register String constructors for reflection as they may not have been properly registered by default
+        // see https://github.com/quarkusio/quarkus/issues/10873
```
Comment (machi1990) [inline extensions/jsonb/deployment/src/main/java/io/quarkus/jsonb/deployment/JsonbProcessor.java:95]: Can we add the corresponding link to the Yasson issue too so that it is easier to quickly check it ?

Comment (loicmathieu) [reply extensions/jsonb/deployment/src/main/java/io/quarkus/jsonb/deployment/JsonbProcessor.java:95]: There is no corresponding fix on Yasson.
In fact, we don't know why it didn't works so it's difficult to provides a fix on Yasson because Optionnal seems to be correctly handled there.

Comment (machi1990) [reply extensions/jsonb/deployment/src/main/java/io/quarkus/jsonb/deployment/JsonbProcessor.java:95]: Yes, I understand that this is not fixed yet in Yasson. What I meant is to add the "corresponding upstream issue" in the comment.

Comment (loicmathieu) [reply extensions/jsonb/deployment/src/main/java/io/quarkus/jsonb/deployment/JsonbProcessor.java:95]: Sorry, I said fix instead of issue.
There is no corresponding issue upstream.

Comment (machi1990) [reply extensions/jsonb/deployment/src/main/java/io/quarkus/jsonb/deployment/JsonbProcessor.java:95]: Ah no worries. 

I was hoping that there is an upstream issue for better support of `Optional<String>`. It makes tracking easier but I suppose we can live with what we have.

**Review by machi1990 — APPROVED** [review]

File: extensions/jsonb/deployment/src/main/java/io/quarkus/jsonb/deployment/JsonbProcessor.java (hunk 1 above)
Comment (gsmet) [reply extensions/jsonb/deployment/src/main/java/io/quarkus/jsonb/deployment/JsonbProcessor.java:95]: > There is no corresponding issue upstream.

Well, shouldn't we create one and add a link pointing to it?

Comment (loicmathieu) [reply extensions/jsonb/deployment/src/main/java/io/quarkus/jsonb/deployment/JsonbProcessor.java:95]: Already merge this one.
I'll copy your comment to the original issue so we can continue working on the root cause inside it.
