### PR TITLE
JaCoCo: resolve data-file and report-location against the project root

### LINKED ISSUE #52264: Quarkus Jacoco 0% coverage when changing data-file name
### Describe the bug

When you put the following property in your src/test/resources/application.properties:
```
#When you enable this you will get 0 coverage
quarkus.jacoco.data-file=jacoco.exec
```

The report will always be generated with 0% coverage. I think this bug has been introduced in https://github.com/quarkusio/quarkus/commit/ed4dd955c0b5d24b4903bc48878e164d71940f48 / https://github.com/quarkusio/quarkus/issues/30264

### Expected behavior

You should get the correct coverage

### Actual behavior

You get 0% coverage

### How to Reproduce?

[rest-kotlin-quickstart.zip](https://github.com/user-attachments/files/24938554/rest-kotlin-quickstart.zip)

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

openjdk 25.0.1 2025-10-21 LTS

### Quarkus version or git rev

3.31.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.12

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mkouba**
- this commit reverts a change introduced in #30315 which caused regression by resolving the data-file and report-location against the build output dir (e.g. target)
- we also clarify the config docs
- fixes #52264

To be honest I'm not 100% sure this would not break anything. I only verified this PR with the reproducer from #52264 and the https://github.com/mkouba/quarkus-mcp-server/tree/jacoco branch in the MCP server.

It would be great if someone else could try it as well. CC @snazy @wesleysalimansdvb @vsevel @famod

### CODE REVIEW

File: test-framework/jacoco/deployment/src/main/java/io/quarkus/jacoco/deployment/JacocoProcessor.java [hunk 1]
```diff
@@ -325,4 +345,24 @@ public static boolean dependencyMatches(ResolvedDependency dependency, String gr
 
     record GAC(String groupId, String artifactId, String classifier) {
     }
+
+    private static Path findProjectRoot(Path outputDirectory) {
+        // Note that we don't have a better way to find the project root
+        // See https://github.com/quarkusio/quarkus/issues/44013
```
Comment (geoand) [inline test-framework/jacoco/deployment/src/main/java/io/quarkus/jacoco/deployment/JacocoProcessor.java:351]: Are we sure about this @aloubyansky ?

Comment (mkouba) [reply test-framework/jacoco/deployment/src/main/java/io/quarkus/jacoco/deployment/JacocoProcessor.java:351]: It seems that @aloubyansky proposed a solution but it didn't work for all configs: https://github.com/quarkusio/quarkus/pull/44104#issuecomment-2509638334

**Review by geoand — APPROVED** [review]

**Comment by vsevel** [comment]
hello. we are trying to upgrade to `3.31.2`  (from `3.31.1)` , and our extensions fail with:
```
[2026-02-04T17:58:05.076Z] java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[2026-02-04T17:58:05.076Z] 	[error]: Build step io.quarkus.jacoco.deployment.JacocoProcessor#transform threw an exception: java.lang.IllegalStateException: Unable to find the project root
[2026-02-04T17:58:05.076Z] 	at io.quarkus.jacoco.deployment.JacocoProcessor.transform(JacocoProcessor.java:74)
[2026-02-04T17:58:05.076Z] 	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:735)
[2026-02-04T17:58:05.076Z] 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:898)
[2026-02-04T17:58:05.076Z] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:255)
[2026-02-04T17:58:05.076Z] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[2026-02-04T17:58:05.076Z] 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2651)
[2026-02-04T17:58:05.076Z] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2630)
[2026-02-04T17:58:05.076Z] 	at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1622)
[2026-02-04T17:58:05.076Z] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1589)
[2026-02-04T17:58:05.076Z] 	at java.base/java.lang.Thread.run(Thread.java:1474)
[2026-02-04T17:58:05.076Z] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[2026-02-04T17:58:05.076Z] 
[2026-02-04T17:58:05.076Z] 	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:389)
[2026-02-04T17:58:05.076Z] 	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:306)
[2026-02-04T17:58:05.076Z] 	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:62)
[2026-02-04T17:58:05.076Z] 	at io.quarkus.test.junit.AppMakerHelper.getStartupAction(AppMakerHelper.java:253)
[2026-02-04T17:58:05.076Z] 	at io.quarkus.test.junit.classloading.FacadeClassLoader.getOrCreateRuntimeClassLoader(FacadeClassLoader.java:599)
[2026-02-04T17:58:05.076Z] 	at io.quarkus.test.junit.classloading.FacadeClassLoader.getQuarkusClassLoader(FacadeClassLoader.java:496)
[2026-02-04T17:58:05.076Z] 	at io.quarkus.test.junit.classloading.FacadeClassLoader.loadClass(FacadeClassLoader.java:378)
[2026-02-04T17:58:05.076Z] 	at java.base/java.lang.Class.forName0(Native Method)
[2026-02-04T17:58:05.076Z] 	at java.base/java.lang.Class.forName(Class.java:547)
[2026-02-04T17:58:05.076Z] 	at org.junit.platform.commons.util.ReflectionUtils.lambda$tryToLoadClass$0(ReflectionUtils.java:771)
[2026-02-04T17:58:05.076Z] 	at org.junit.platform.commons.function.Try.lambda$call$0(Try.java:61)
[2026-02-04T17:58:05.076Z] 	at org.junit.platform.commons.function.Try.of(Try.java:98)
[2026-02-04T17:58:05.076Z] 	at org.junit.platform.commons.function.Try.call(Try.java:61)
[2026-02-04T17:58:05.076Z] 	at org.junit.platform.commons.util.ReflectionUtils.tryToLoadClass(ReflectionUtils.java:758)
[2026-02-04T17:58:05.076Z] 	at org.junit.platform.commons.util.ReflectionUtils.tryToLoadClass(ReflectionUtils.java:714)
[2026-02-04T17:58:05.076Z] 	at org.junit.platform.commons.support.ReflectionSupport.tryToLoadClass(ReflectionSupport.java:78)
[2026-02-04T17:58:05.076Z] 	at org.junit.platform.engine.discovery.ClassSelector.getJavaClass(ClassSelector.java:97)
[2026-02-04T17:58:05.076Z] 	at org.junit.jupiter.engine.discovery.ClassSelectorResolver.resolve(ClassSelectorResolver.java:86)
[2026-02-04T17:58:05.076Z] 	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.lambda$resolve$0(EngineDiscoveryRequestResolution.java:137)
[2026-02-04T17:58:05.076Z] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:214)
[2026-02-04T17:58:05.076Z] 	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1693)
[2026-02-04T17:58:05.076Z] 	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:147)
[2026-02-04T17:58:05.076Z] 	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:588)
[2026-02-04T17:58:05.076Z] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:574)
[2026-02-04T17:58:05.076Z] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)
[2026-02-04T17:58:05.076Z] 	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
[2026-02-04T17:58:05.076Z] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
[2026-02-04T17:58:05.076Z] 	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:683)
[2026-02-04T17:58:05.076Z] 	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolve(EngineDiscoveryRequestResolution.java:191)
[2026-02-04T17:58:05.076Z] 	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolve(EngineDiscoveryRequestResolution.java:128)
[2026-02-04T17:58:05.076Z] 	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolveCompletely(EngineDiscoveryRequestResolution.java:94)
[2026-02-04T17:58:05.076Z] 	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.run(EngineDiscoveryRequestResolution.java:85)
[2026-02-04T17:58:05.076Z] 	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolver.resolve(EngineDiscoveryRequestResolver.java:150)
[2026-02-04T17:58:05.076Z] 	at org.junit.jupiter.engine.discovery.DiscoverySelectorResolver.resolveSelectors(DiscoverySelectorResolver.java:62)
[2026-02-04T17:58:05.076Z] 	at org.junit.jupiter.engine.JupiterTestEngine.discover(JupiterTestEngine.java:74)
[2026-02-04T17:58:05.076Z] 	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:195)
[2026-02-04T17:58:05.076Z] 	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverSafely(EngineDiscoveryOrchestrator.java:174)
[2026-02-04T17:58:05.076Z] 	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:119)
[2026-02-04T17:58:05.076Z] 	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:84)
[2026-02-04T17:58:05.076Z] 	at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:119)
[2026-02-04T17:58:05.076Z] 	at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:85)
[2026-02-04T17:58:05.076Z] 	at org.junit.platform.launcher.core.DelegatingLauncher.discover(DelegatingLauncher.java:43)
[2026-02-04T17:58:05.076Z] 	at org.junit.platform.launcher.core.InterceptingLauncher.lambda$discover$0(InterceptingLauncher.java:35)
[2026-02-04T17:58:05.076Z] 	at org.junit.platform.launcher.core.ClasspathAlignmentCheckingLauncherInterceptor.intercept(ClasspathAlignmentCheckingLauncherInterceptor.java:25)
[2026-02-04T17:58:05.076Z] 	at org.junit.platform.launcher.core.InterceptingLauncher.discover(InterceptingLauncher.java:35)
[2026-02-04T17:58:05.076Z] 	at org.junit.platform.launcher.core.DelegatingLauncher.discover(DelegatingLauncher.java:43)
[2026-02-04T17:58:05.076Z] 	at org.apache.maven.surefire.junitplatform.LauncherAdapter.discover(LauncherAdapter.java:47)
[2026-02-04T17:58:05.076Z] 	at org.apache.maven.surefire.junitplatform.TestPlanScannerFilter.accept(TestPlanScannerFilter.java:51)
[2026-02-04T17:58:05.076Z] 	at org.apache.maven.surefire.api.util.DefaultScanResult.applyFilter(DefaultScanResult.java:87)
[2026-02-04T17:58:05.076Z] 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.scanClasspath(JUnitPlatformProvider.java:156)
[2026-02-04T17:58:05.076Z] 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:136)
[2026-02-04T17:58:05.076Z] 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
[2026-02-04T17:58:05.076Z] 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
[2026-02-04T17:58:05.076Z] 	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
[2026-02-04T17:58:05.076Z] 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
[2026-02-04T17:58:05.076Z] Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[2026-02-04T17:58:05.076Z] 	[error]: Build step io.quarkus.jacoco.deployment.JacocoProcessor#transform threw an exception: java.lang.IllegalStateException: Unable to find the project root
[2026-02-04T17:58:05.076Z] 	at io.quarkus.jacoco.deployment.JacocoProcessor.transform(JacocoProcessor.java:74)
[2026-02-04T17:58:05.076Z] 	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:735)
[2026-02-04T17:58:05.076Z] 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:898)
[2026-02-04T17:58:05.076Z] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:255)
[2026-02-04T17:58:05.076Z] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[2026-02-04T17:58:05.076Z] 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2651)
[2026-02-04T17:58:05.076Z] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2630)
[2026-02-04T17:58:05.076Z] 	at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1622)
[2026-02-04T17:58:05.076Z] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1589)
[2026-02-04T17:58:05.076Z] 	at java.base/java.lang.Thread.run(Thread.java:1474)
[2026-02-04T17:58:05.076Z] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[2026-02-04T17:58:05.076Z] 
[2026-02-04T17:58:05.076Z] 	at io.quarkus.builder.Execution.run(Execution.java:139)
[2026-02-04T17:58:05.076Z] 	at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:78)
[2026-02-04T17:58:05.076Z] 	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:171)
[2026-02-04T17:58:05.076Z] 	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:385)
[2026-02-04T17:58:05.076Z] 	... 54 more
[2026-02-04T17:58:05.076Z] Caused by: java.lang.IllegalStateException: Unable to find the project root
[2026-02-04T17:58:05.076Z] 	at io.quarkus.jacoco.deployment.JacocoProcessor.transform(JacocoProcessor.java:74)
[2026-02-04T17:58:05.076Z] 	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:735)
[2026-02-04T17:58:05.076Z] 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:898)
[2026-02-04T17:58:05.076Z] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:255)
[2026-02-04T17:58:05.076Z] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[2026-02-04T17:58:05.076Z] 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2651)
[2026-02-04T17:58:05.076Z] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2630)
[2026-02-04T17:58:05.076Z] 	at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1622)
[2026-02-04T17:58:05.076Z] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1589)
[2026-02-04T17:58:05.076Z] 	at java.base/java.lang.Thread.run(Thread.java:1474)
[2026-02-04T17:58:05.076Z] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
``` 

@mkouba could this be related to this change?

**Comment by mkouba** [comment]
> could this be related to this change?

@vsevel Yes, it's related. How does the project structure look like?

**Comment by vsevel** [comment]
this is on our monorepo of extensions. at the very top we have:
```
        <!-- jacoco -->
        <jacoco-maven-plugin.version>0.8.14</jacoco-maven-plugin.version>
        <!-- Jacoco -->
        <jacoco.binary.file>${maven.multiModuleProjectDirectory}/target/jacoco.exec</jacoco.binary.file>
        <!-- tells sonarqube where to get the jacoco xml file -->
        <jacoco.xml.file>${maven.multiModuleProjectDirectory}/target/coverage/jacoco.xml</jacoco.xml.file>
        <sonar.coverage.jacoco.xmlReportPaths>${jacoco.xml.file}</sonar.coverage.jacoco.xmlReportPaths>
        ...

    <dependencies>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-jacoco</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
    
    ...
    
                    <plugin>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>${surefire-plugin.version}</version>
                    <executions>
                        <execution>
                            <id>default-test</id>
                            <goals>
                                <goal>test</goal>
                            </goals>
                            <configuration>
                                <excludedGroups>io.quarkus.test.junit.QuarkusTest</excludedGroups>
                            </configuration>
                        </execution>
                        <execution>
                            <id>quarkus-test</id>
                            <goals>
                                <goal>test</goal>
                            </goals>
                            <configuration>
                                <groups>io.quarkus.test.junit.QuarkusTest</groups>
                            </configuration>
                        </execution>
                    </executions>
                    <configuration>
                        <skipTests>${skipUTs}</skipTests>
                        <!-- @{argLine} to keep jacoco config -->
                        <!-- add-opens java.base/java.lang=ALL-UNNAMED for JDK 24+ -->
                        <!-- may be removed in the future; see https://github.com/quarkusio/quarkus/pull/50653 -->
                        <argLine>@{argLine} ${surefire.argLine.additional} --add-opens java.base/java.lang=ALL-UNNAMED</argLine>
                        <systemPropertyVariables>
                            <maven.home>${maven.home}</maven.home>
                            <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
                            <quarkus.jacoco.data-file>${jacoco.binary.file}</quarkus.jacoco.data-file>
                            <quarkus.jacoco.reuse-data-file>true</quarkus.jacoco.reuse-data-file>
                            <quarkus.jacoco.report-location>${maven.multiModuleProjectDirectory}/target/coverage</quarkus.jacoco.report-location>
                        </systemPropertyVariables>
                        <excludes>
                            <exclude>**/*IT.java</exclude>
                        </excludes>
                    </configuration>
                </plugin>

...

        <profile>
            <id>codecoverage</id>
            <build>
                <plugins>
                    <!-- Jacoco is used by Sonar for codecoverage -->
                    <plugin>
                        <groupId>org.jacoco</groupId>
                        <artifactId>jacoco-maven-plugin</artifactId>
                        <version>${jacoco-maven-plugin.version}</version>
                        <configuration>
                            <append>true</append>
                            <includes>
...
                            </includes>
                            <excludes>
                                <exclude>**/generated/**</exclude>
...
                            </excludes>
                        </configuration>
                        <executions>
                            <execution>
                                <id>agent</id>
                                <goals>
                                    <goal>prepare-agent</goal>
                                </goals>
                                <configuration>
                                    <append>true</append>
                                    <destFile>${jacoco.binary.file}</destFile>
                                    <exclClassLoaders>*QuarkusClassLoader</exclClassLoaders>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>

```

this is failing on the integration extension of a module with command `mvn clean package -U --batch-mode -V -e -Dformat.skip=true -Dimpsort.skip=true -Dlicense.skip -Pcodecoverage`

and it is failing on the surefire plugin:
```
[2026-02-04T17:58:01.822Z] [INFO] --- surefire:3.5.4:test (default-test) @ my-ext-integration-tests ---
[2026-02-04T17:58:01.822Z] [INFO] Surefire report directory: my-extj/integration-tests/target/surefire-reports
[2026-02-04T17:58:01.822Z] [INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
[2026-02-04T17:58:01.822Z] [INFO] 
[2026-02-04T17:58:01.822Z] [INFO] -------------------------------------------------------
[2026-02-04T17:58:01.822Z] [INFO]  T E S T S
[2026-02-04T17:58:01.822Z] [INFO] -------------------------------------------------------
[2026-02-04T17:58:01.822Z] Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
[2026-02-04T17:58:05.076Z] java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[2026-02-04T17:58:05.076Z] 	[error]: Build step io.quarkus.jacoco.deployment.JacocoProcessor#transform threw an exception: java.lang.IllegalStateException: Unable to find the project root
```

**Comment by vsevel** [comment]
@mkouba it happens that some of our extensions have an `integration-tests` module with no `src/main` , whether this makes sense or not.
the way `private static Path findProjectRoot(Path outputDirectory)` is written, it never finds anything.
I have added a `src/main/java/.../GreetingResource.java`, and it seems to work. waiting for a full build in CI.

**Comment by mkouba** [comment]
> it happens that some of our extensions have an `integration-tests` module with no `src/main` , whether this makes sense or not.

Hm, no `src/main`, no `config/application.properties`, etc. What does the integration test module contain then?

@ia3andy @aloubyansky Any idea how to improve the [`JacocoProcessor#findProjectRoot()`](https://github.com/quarkusio/quarkus/blob/main/test-framework/jacoco/deployment/src/main/java/io/quarkus/jacoco/deployment/JacocoProcessor.java#L351-L368)?

**Comment by aloubyansky** [comment]
I'll look into this.

**Comment by mkouba** [comment]
> I'll look into this.

Thanks!

**Comment by vsevel** [comment]
> What does the integration test module contain then?

I think this is an anti-pattern. I am not sure this is worth improving.

**Comment by aloubyansky** [comment]
@mkouba I think https://github.com/quarkusio/quarkus/pull/52485 should work. I tested on a project structure @vsevel described too.
