### PR TITLE
Fix @Blocking method in gRPC Mutiny services

### LINKED ISSUE #30075: Blocking anotation does not work with Mutiny and gRPC
### Describe the bug

When using Blocking on a Mutiny style gRPC service it fails with 

```
WARN  [io.qua.grp.stu.ServerCalls] (vert.x-eventloop-thread-0) gRPC service threw an exception other than StatusRuntimeException: org.jboss.resteasy.reactive.common.core.BlockingNotAllowedException
```

### Expected behavior

I expect it to work the same as Non-Mutiny style - without failing with the above exception and returning the answer.

```
@GrpcService
public class SteamService  extends GameServiceGrpc.GameServiceImplBase{
    @Inject
    GameFetch gameFetch;

    @Blocking
    @Override
    public void getGamesBySearchString(GetGamesBySearchStringRequest request, StreamObserver<GetGamesBySearchStringResponse> responseObserver) {
        List<GamesBySearchResponse> gameBySearch = gameFetch.getGameBySearch(request.getSearchString());
        responseObserver.onNext(GetGamesBySearchStringResponse.newBuilder()
                .addAllGames(() -> gameBySearch.stream()
                        .map(gbsr ->
                                GameBySearchDto.newBuilder()
                                        .setAppid(gbsr.appid())
                                        .setName(gbsr.name())
                                        .setStoreEnum(StoreEnum.STEAM)
                                        .build()
                        ).iterator())
                .build());
        responseObserver.onCompleted();
    }

}

```

### Actual behavior

Example code where gameFetch is blocking the method fails with org.jboss.resteasy.reactive.common.core.BlockingNotAllowedException.

```
@GrpcService
public class MutinyStreamService implements GameService {

    @Inject
    GameFetch gameFetch;

    @Blocking
    @Override
    public Uni<GetGamesBySearchStringResponse> getGamesBySearchString(GetGamesBySearchStringRequest request) {
        List<GamesBySearchResponse> gameBySearch = gameFetch.getGameBySearch(request.getSearchString());
        return Uni.createFrom().item(() ->
                GetGamesBySearchStringResponse.newBuilder()
                        .addAllGames(() -> gameBySearch.stream()
                                .map(gbsr ->
                                        GameBySearchDto.newBuilder()
                                                .setAppid(gbsr.appid())
                                                .setName(gbsr.name())
                                                .setStoreEnum(StoreEnum.STEAM)
                                                .build()
                                ).iterator())
                        .build()
        );
    }
}
```

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

Linux pop-os 6.0.12-76060006-generic #202212290932~1671652965~22.04~452ea9d SMP PREEMPT_DYNAMIC Wed D x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk-19 (19.0.1)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.15.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

GameFetch is a simple Bean that calls a RestClient

```
@RequestScoped
public class GameFetch {

    @RestClient
    SteamCommunityService steamCommunityService;

    @PostConstruct
    void init() {
        ObjectMapper objectMapper = Arc.container().instance(ObjectMapper.class).get();
        objectMapper.enable(DeserializationFeature. ACCEPT_SINGLE_VALUE_AS_ARRAY);
    }

    public List<GamesBySearchResponse> getGameBySearch(String searchString) {
        return steamCommunityService.getGameBySearch(searchString);
    }
}
```

And the .proto

```
syntax = "proto3";

option java_multiple_files = true;
option java_package = "com.acme";
option java_outer_classname = "GameSearchProto";

package game.search;

enum StoreEnum {
  STORE_ENUM_UNSPECIFIED = 0;
  STEAM = 1;
  GOG = 2;
}

message GameBySearchDto {
  string name = 1;
  string appid = 2;
  StoreEnum store_enum = 3;
}

service GameService {
  rpc GetGamesBySearchString(GetGamesBySearchStringRequest) returns (GetGamesBySearchStringResponse);
}

message GetGamesBySearchStringRequest {
  string search_string = 1;
}

message GetGamesBySearchStringResponse {
  repeated GameBySearchDto games = 1;
}
```

### PR DESCRIPTION
**Pull request by cescoffier**
Fix #30075

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Comment by alesj** [comment]
Ah, so we only checked for ImplBase, and not for the direct interface impls ... good catch!

**Review by alesj — APPROVED** [review]

File: extensions/grpc/deployment/src/test/java/io/quarkus/grpc/server/services/BlockingMutinyHelloService.java [hunk 1]
```diff
@@ -14,6 +14,10 @@ public class BlockingMutinyHelloService implements Greeter {
     @Override
     @Blocking
     public Uni<HelloReply> sayHello(HelloRequest request) {
+
+        // Force failure if awaiting
+        Uni.createFrom().nullItem().await().indefinitely();
```
Comment (alesj) [inline extensions/grpc/deployment/src/test/java/io/quarkus/grpc/server/services/BlockingMutinyHelloService.java:19]: So @Blocking will timeout this `await::indefinitely` ?

Comment (cescoffier) [reply extensions/grpc/deployment/src/test/java/io/quarkus/grpc/server/services/BlockingMutinyHelloService.java:19]: No, it will return bill immediately, which is fine.

However, await is forbidden from an event loop thread (it throws an exception), so the call would fail if we call it on an event loop thread.
