### PR TITLE
Avoid a possible NPE during application stop

### LINKED ISSUE #42207: Possible NPE during shutdown
### Describe the bug

There's a race condition in `ApplicationLifecycleManager` which manifests as an NPE being logged during shutdown.

Omitting further details as I have a PR to send.

### PR DESCRIPTION
**Pull request by Sanne**
Fixes #42207

### CODE REVIEW

File: core/runtime/src/main/java/io/quarkus/runtime/ApplicationLifecycleManager.java [hunk 1]
```diff
@@ -429,13 +429,15 @@ public void run() {
...
+            final Application app = currentApplication;
+            if (app.isStarted()) {
                 // On CLI apps, SIGINT won't call io.quarkus.runtime.Application#stop(),
                 // making the awaitShutdown() below block the application termination process
                 // It should be a noop if called twice anyway
-                currentApplication.stop();
+                app.stop();
             }
-            currentApplication.awaitShutdown();
+            app.awaitShutdown();
```
Comment (Sanne) [inline core/runtime/src/main/java/io/quarkus/runtime/ApplicationLifecycleManager.java:440]: This is the line were it would NPE: the "stop" process invoked above would set the `currentApplication` field to `null`, asynchronously.
On my machine this would result in an NPE being thrown sometimes (not always).

**Review by aloubyansky — APPROVED** [review]

**Review by geoand — APPROVED** [review]
