### PR TITLE
XStream substitutions to avoid @Delete paths #7422

### LINKED ISSUE #7422: Unsupported type MethodAccessorGenerator reachable error
quarkus master (bbb2329ae) w/ graal master (https://github.com/oracle/graal/commit/ee232b09e21e) failing with Java 11 in `integration-tests/optaplanner-jackson`:

```
$ mvn clean install -Dnative -pl integration-tests/optaplanner-jackson
...
Error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported type jdk.internal.reflect.MethodAccessorGenerator is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Detailed message:
Trace:
	at parsing jdk.internal.reflect.ReflectionFactory.generateConstructor(ReflectionFactory.java:513)
Call path from entry point to jdk.internal.reflect.ReflectionFactory.generateConstructor(Class, Constructor):
	at jdk.internal.reflect.ReflectionFactory.generateConstructor(ReflectionFactory.java:513)
	at jdk.internal.reflect.ReflectionFactory.newConstructorForSerialization(ReflectionFactory.java:506)
	at java.io.ObjectStreamClass.getSerializableConstructor(ObjectStreamClass.java:1516)
	at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:509)
	at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:484)
	at com.oracle.svm.core.jdk.Target_java_security_AccessController.doPrivileged(SecuritySubstitutions.java:81)
	at sun.security.pkcs11.SunPKCS11.initToken(SunPKCS11.java:1028)
	at sun.security.pkcs11.SunPKCS11$TokenPoller.run(SunPKCS11.java:852)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
```

Console output can be found [here](https://gist.github.com/galderz/b57a0d7f8214348649c2541fa488c8f2).

### PR DESCRIPTION
**Pull request by galderz**
Fixes: https://github.com/quarkusio/quarkus/issues/7422

Essentially cutting off paths that could lead to new classes being created on the fly during Serializable object serialization/deserialization using xstream (see [path](https://gist.github.com/galderz/34cbc3df6709e90233dfd2309fd7367b)). 

Recent graalvm master changes made paths leading to `jdk.internal.reflect.ReflectionFactory` forbidden (see discussion in [graalvm issue](https://github.com/quarkusio/quarkus/issues/7422)).

Reached this fix through chats with @ge0ffrey (thx!!). Kogito (@mariofusco) also has a dependency on xstream, and hence it should also be validated/approved by that component owner (@mariofusco?).

### CODE REVIEW

**Comment by galderz** [comment]
[Zulip discussion](https://quarkusio.zulipchat.com/login/#narrow/stream/187038-dev/topic/Serialization.20won't.20be.20allowed)

**Comment by gsmet** [comment]
If Kogito requires this too, don't we need some internal XStreams extension to share the subtitution?

**Review by ge0ffrey — APPROVED** [review]

**Comment by ge0ffrey** [comment]
Mario mentioned that the XStream dependency in kogito-drools was possibly obsolete, IIRC.
@mariofusco Any chance kogito-drools can delete that dependency?

File: extensions/optaplanner/runtime/src/main/java/io/quarkus/optaplanner/nativeimage/XStreamSubstitutions.java [hunk 1]
```diff
@@ -0,0 +1,52 @@
+package io.quarkus.optaplanner.nativeimage;
```
Comment (gsmet) [inline extensions/optaplanner/runtime/src/main/java/io/quarkus/optaplanner/nativeimage/XStreamSubstitutions.java]: Could you move this class to `io.quarkus.optaplanner.runtime.graal` so it's consistent with our conventions?

**Review by gsmet — CHANGES_REQUESTED** [review]

File: extensions/optaplanner/runtime/src/main/java/io/quarkus/optaplanner/nativeimage/XStreamSubstitutions.java (hunk 1 above)
Comment (galderz) [reply extensions/optaplanner/runtime/src/main/java/io/quarkus/optaplanner/nativeimage/XStreamSubstitutions.java]: Sure I can, but shouldn't `KogitoSubstitutions` (in the same folder) move too? I just followed whatever was done in that module.

**Comment by galderz** [comment]
@gsmet Refactored substitutions as asked. Waiting for @mariofusco input to decide the final place for this.

**Comment by galderz** [comment]
@ge0ffrey This has been lingering for quite a while now. Do we really need to wait for @mariofusco? If Kogito ends up suffering from same issue, we can evaluate again what to do. I've been blocked by Camel's failures testing Quarkus Platform.

**Review by gsmet — APPROVED** [review]

**Comment by ge0ffrey** [comment]
@galderz For the record, this wasn't blocked for Drools - I think that can be handled as a separate issue. Just potentially related.
