### PR TITLE
Fix deprecation warnings related to ORM dialects and add `quarkus.datasource.db-version` as a dialect version hint

### LINKED ISSUE #31474: Configuration property to give a hint to Quarkus/Hibernate ORM regarding the database version
### Description

Hibernate ORM 6 takes advantage of database metadata to determine the "kind" and version of the database, and configures its dialect accordingly.

When the database metadata is not available, it defaults to the oldest supported version.

We already have a property to set the "database kind", though we probably need to wire it to the corresponding property in Hibernate ORM 6, if appropriate (currently we use the db-kind to set the dialect).

More importantly, we need to expose a property to allow configuring the version of the database explicitly. There's a corresponding property in Hibernate ORM 6 for that.

Related to #13522

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by yrodiere**
Fixes #31474 

Draft because this PR is based on #31697 , which must be merged first.

In short:

* We stop relying on deprecated, version-specific dialects.
* Instead, we use version-independent dialects and pass a version to Hibernate ORM through configuration properties.
* We set the versionin particular for dialects where the default version in Hibernate ORM is older than the version we were targeting in Quarkus 2.
* In the last commit, we also set the version for other supported dialects. That's not strictly necessary, but it might make sense? Sanne was in favor, personally I'm still debating it.
* We now have tests to check that Hibernate ORM doesn't issue any warning on startup, for all databases. Though only with a rather simple model. This will allow us to detect when ORM no longer supports our default versions, so that's nice.
* We also expose a configuration property `quarkus.datasource.db-version` to set that version explicitly, so that users can now do this instead of setting version-specific dialects.
* When `db-version` is set, we try to check the version on runtime init:
  * if the actual version is higher than or equal to `db-version` we do nothing
  * if the actual version is lower than `db-version` we throw an exception (startup fails)
  * if we can't retrieve the actual version we just log a warning
  * Note this check is only enabled when the version is set explicitly; we don't check default versions because that would break too many applications.

I didn't add documentation beyond the javadoc on the configuration properties (`dialect` and `db-version`) because I'm not sure how useful that would be. I imagine people would mostly end up using this property because they tried a custom dialect and saw a deprecation warning... In which case the javadoc on `dialect` might be enough to point them in the right direction. Thoughts?

### CODE REVIEW

File: extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/config/DialectVersions.java [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+ * Constants exposing the default versions of various DBs in Quarkus.
+ * <p>
+ * If, one day, Hibernate ORM's defaults catch up with all our default versions,
+ * we could consider relying on ORM's defaults going forward.
+ * <p>
+ * For H2, we will probably have to keep a constant here forever,
+ * as H2 is embedded and thus Quarkus determines its default version through the BOM.
+ * See https://github.com/quarkusio/quarkus/issues/1886
+ *
+ * @author Emmanuel Bernard emmanuel@hibernate.org
```
Comment (gsmet) [inline extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/config/DialectVersions.java:15]: ?

File: extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/config/DialectVersions.java [hunk 2]
```diff
@@ -0,0 +1,47 @@
...
+ */
+public final class DialectVersions {
```
Comment (gsmet) [inline extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/config/DialectVersions.java:17]: I think I would have called it `DefaultDialectVersions` to be extra clear but the presence of `toString(DatabaseVersion version)` is not really in line with this.

Maybe rename the constant with `MARIADB_DEFAULT` or something similar?

It might just be me being over cautious but I find the intent not as clear as it should be. Feel free to ignore though if you think otherwise.

File: extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/config/DialectVersions.java [hunk 3]
```diff
@@ -16,10 +16,13 @@
  */
 public final class DialectVersions {
     // The following constants must be at least equal to the default dialect version in Hibernate ORM
+    public static final String DB2 = "10.5";
+    public static final String DERBY = "10.14";
     public static final String MARIADB = "10.6";
     public static final String MSSQL = "13"; // 2016
     public static final String MYSQL = "8";
     public static final String ORACLE = "12";
+    public static final String POSTGRESQL = "10.0";
```
Comment (gsmet) [inline extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/config/DialectVersions.java:25]: I think I would rather defer to ORM than enforcing all versions but that's just my 2 cents.

**Review by gsmet — COMMENTED** [review]
Looks very good, thanks. I added a few comments.

File: extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/config/DialectVersions.java (hunk 1 above)
Comment (yrodiere) [reply extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/config/DialectVersions.java:15]: Ah right. That's because I originally renamed the `QuarkusH2Dialect` class. Will fix.

File: extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/config/DialectVersions.java (hunk 2 above)
Comment (yrodiere) [reply extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/config/DialectVersions.java:17]: I'll wrap this in a static `Defaults` class :)

File: extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/config/DialectVersions.java (hunk 3 above)
Comment (yrodiere) [reply extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/config/DialectVersions.java:25]: Yeah, I was on the fence. It seems nobody has a strong opinion though... hard call :)

**Comment by yrodiere** [comment]
I rebased, addressed your comments and renamed `db-min-version` to `db-version` as discussed [on Zulip](https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/datasource.2Edb-version). Let's see what CI has to say...

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
As a follow-up, I think we should add something in the documentation as it radically changes how users are supposed to handle dialects.
I know the property will be documented in the table but I think a specific paragraph would be welcome to explain how versioned dialects are now working and that you should use `db-version` to point to a specific version.

**Comment by yrodiere** [comment]
The test failures are unrelated.

I'll go ahead and merge this; feel free to comment on the documentation and I'll send another PR to amend it if necessary.

Thanks for the review!
