### PR TITLE
Copy duplicated local context to the event loop context

### LINKED ISSUE #22568: OpenTelemetry not working with RESTEasy reactive mode
### Describe the bug

I am trying to setup OpenTelementry on two on Kotlin 1.6.10 and Quarkus 2.6.1. I have a trivial application that takes an input and then makes an HTTP call to another endpoint (on the same application).

If I use RESTEasy Reactive with a synchronous function it works fine. I get a full trace from the HTTP end.

Here is my server:

```properties
quarkus.opentelemetry.enabled=true 
quarkus.opentelemetry.propagators=b3,b3multi,tracecontext
quarkus.opentelemetry.tracer.sampler=on
quarkus.opentelemetry.tracer.sampler.parent-based=true
```

```kotlin
@Path("/hello")
class GreetingController(
    private val tracer: Tracer,

    @RestClient
    private val repeaterClient: RepeaterClient
) {
    @Path("sync")
    @POST
    @Produces(MediaType.TEXT_PLAIN)
    fun sync(name: String): String {
        val span = tracer.spanBuilder("inside sync").startSpan()

        try {
            val repeat = repeaterClient.sync(name)
            return "Hello $name $repeat - sync"
        } finally {
            span.end()
        }
    }

    @Path("async")
    @POST
    @Produces(MediaType.TEXT_PLAIN)
    fun async(name: String): Uni<String> {
        val span = tracer.spanBuilder("inside async").startSpan()

        try {
            return repeaterClient.async(name).onItem()
                .transform { repeat -> "Hello $name $repeat - async" } //.await().indefinitely()
        } finally {
            span.end()
        }
    }

    @Path("coroutine")
    @POST
    @Produces(MediaType.TEXT_PLAIN)
    suspend fun coroutine(name: String): String {
        val span = tracer.spanBuilder("inside coroutine").startSpan()

        try {
            val repeat = repeaterClient.coroutine(name)

            return "Hello $name $repeat - coroutine"
        } finally {
            span.end()
        }
    }
}

@Path("/repeat")
@RegisterRestClient(configKey = "repeater-api")
interface RepeaterClient {
    @Path("repeat")
    @POST
    fun sync(repeat: String): String

    @Path("repeat")
    @POST
    fun async(repeat: String): Uni<String>

    @Path("repeat")
    @POST
    suspend fun coroutine(repeat: String): String
}

@Path("repeat")
class RepeaterController(
    private val tracer: Tracer
) {
    @Path("repeat")
    @POST
    @Produces(MediaType.TEXT_PLAIN)
    fun repeat(repeat: String): String {
        val span = tracer.spanBuilder("inside repeat").startSpan()

        try {
            return repeat
        } finally {
            span.end()
        }
    }
}
```

If I call `/hello/sync` I get a single trace that includes the original HTTP POST, `inside sync`, the HTTP repeat client, the HTTP repeat POST server, and `inside repeat`.

If I call `/hello/async`, I get three traces. The first trace is a single space of the HTTP POST (`hello/async`). The second trace is `inside async`. And the third trace includes 3 spans the HTTP repeat client, the HTTP repeat POST server, and `inside repeat`

Using `/hello/coroutine` gave me the exact same results.

I previously tried Quarkus 2.5.x and it gave slightly different results. Instead of three traces, I got two traces. The first two traces were a single trace.

### Expected behavior

I expect a single trace.

### Actual behavior

My request is split into three different traces.

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

Darwin MacBook-Pro 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "17.0.1" 2021-10-19

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.1.1-final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.3

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by radcortez**
- Fixes #22568

### CODE REVIEW

File: integration-tests/opentelemetry-reactive/src/main/java/io/quarkus/it/opentelemetry/reactive/ReactiveResource.java [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+@Path("/reactive")
+public class ReactiveResource {
+    @Inject
+    Tracer tracer;
+
+    @GET
+    public Uni<String> helloGet(@QueryParam("name") String name) {
+        Span span = tracer.spanBuilder("helloGet").startSpan();
+        try {
+            return Uni.createFrom().item("Hello " + name);
```
Comment (cescoffier) [inline integration-tests/opentelemetry-reactive/src/main/java/io/quarkus/it/opentelemetry/reactive/ReactiveResource.java:22]: This is not async. You should try with something leaving the event loop with be coming back. 

As a result you would not be able to use the try /finally.

File: integration-tests/opentelemetry-reactive/src/main/java/io/quarkus/it/opentelemetry/reactive/SpanData.java [hunk 2]
```diff
@@ -0,0 +1,28 @@
+package io.quarkus.it.opentelemetry.reactive;
+
+import io.quarkus.runtime.annotations.RegisterForReflection;
+
+@RegisterForReflection(classNames = {
+        "io.opentelemetry.sdk.trace.data.SpanData",
```
Comment (cescoffier) [inline integration-tests/opentelemetry-reactive/src/main/java/io/quarkus/it/opentelemetry/reactive/SpanData.java:6]: Any reason to not do it in the extension ?

**Review by cescoffier — CHANGES_REQUESTED** [review]

File: integration-tests/opentelemetry-reactive/src/main/java/io/quarkus/it/opentelemetry/reactive/ReactiveResource.java (hunk 1 above)
Comment (radcortez) [reply integration-tests/opentelemetry-reactive/src/main/java/io/quarkus/it/opentelemetry/reactive/ReactiveResource.java:22]: Yes, I know. This was enough to reproduce the problem since it would still execute the rest call in the resteasy reactive context. I guess I can write a more realistic test.

File: integration-tests/opentelemetry-reactive/src/main/java/io/quarkus/it/opentelemetry/reactive/SpanData.java (hunk 2 above)
Comment (radcortez) [reply integration-tests/opentelemetry-reactive/src/main/java/io/quarkus/it/opentelemetry/reactive/SpanData.java:6]: This is just for us to retrieve the Span data for assertion over a rest endpoint with the jackson serialization. It is not intended to be used for real application, since telemetry data is pushed to an OTLP exporter.

**Review by cescoffier — APPROVED** [review]

**Comment by radcortez** [comment]
Thanks @cescoffier

File: independent-projects/resteasy-reactive/server/vertx/src/main/java/org/jboss/resteasy/reactive/server/vertx/VertxResteasyReactiveRequestContext.java [hunk 3]
```diff
@@ -60,6 +61,8 @@ public VertxResteasyReactiveRequestContext(Deployment deployment, ProvidersImpl
         context.addHeadersEndHandler(this);
         String expect = request.getHeader(HttpHeaderNames.EXPECT);
         ContextInternal internal = ((ConnectionBase) context.request().connection()).getContext();
+        ContextInternal current = (ContextInternal) Vertx.currentContext();
+        internal.localContextData().putAll(current.localContextData());
```
Comment (gsmet) [inline independent-projects/resteasy-reactive/server/vertx/src/main/java/org/jboss/resteasy/reactive/server/vertx/VertxResteasyReactiveRequestContext.java:65]: @geoand @Sanne I wanted you to be aware of this change as it could have consequences on RESTEasy Reactive performances.

Comment (geoand) [reply independent-projects/resteasy-reactive/server/vertx/src/main/java/org/jboss/resteasy/reactive/server/vertx/VertxResteasyReactiveRequestContext.java:65]: Interesting, thanks for the heads up!

Question for @cescoffier: Do we always need to do this, or is this something we perhaps can do conditionally, if for example an extension needs it?

Comment (Sanne) [reply independent-projects/resteasy-reactive/server/vertx/src/main/java/org/jboss/resteasy/reactive/server/vertx/VertxResteasyReactiveRequestContext.java:65]: Thanks .. yes that doesn't look very efficient. I'll add it to my list of things to check for the next round of performance work.

Comment (radcortez) [reply independent-projects/resteasy-reactive/server/vertx/src/main/java/org/jboss/resteasy/reactive/server/vertx/VertxResteasyReactiveRequestContext.java:65]: For additional context: https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/VertxResteasyReactiveRequestContext.

We could probably only copy the context if OTel is available (for now, it seems that it is the only case where the local context is required).

Comment (geoand) [reply independent-projects/resteasy-reactive/server/vertx/src/main/java/org/jboss/resteasy/reactive/server/vertx/VertxResteasyReactiveRequestContext.java:65]: Exactly. This should be controlled by a flag that is set only if some extension needs this capability.

I'll come up with something

Comment (geoand) [reply independent-projects/resteasy-reactive/server/vertx/src/main/java/org/jboss/resteasy/reactive/server/vertx/VertxResteasyReactiveRequestContext.java:65]: https://github.com/quarkusio/quarkus/pull/22766 is what I had in mind
