### PR TITLE
Revert how readers and writers are registered for REST clients

### LINKED ISSUE #8223: Using the REST Client with Multipart not working in all cases
**Describe the bug**
(Describe the problem clearly and concisely.)
Proxying multipart call using `@RestClient` is not working with only GET resource, you have to have at least one POST.

**Expected behavior**
(Describe the expected behavior clearly and concisely.)
Expected behavior is successful multipart call toward another service even when there is only GET resource.

**Actual behavior**
(Describe the actual behavior clearly and concisely.)
Results is:
RESTEASY003215: could not find writer for content-type multipart/form-data type: org.acme.rest.client.multipart.MultipartBody

**To Reproduce**
1.  Follow this guide till end: https://quarkus.io/guides/rest-client-multipart
2. At this point everything should work so run test to confirm everything is working as intended.
3. Replace only `@POST` with `@GET` at
Class: `MultipartClientResource `
Method: `public String sendFile() throws Exception`

So, from:
```
@POST
@Path("/multipart")
@Produces(MediaType.TEXT_PLAIN)
public String sendFile() throws Exception {
    MultipartBody body = new MultipartBody();
    body.fileName = "greeting.txt";
    body.file = new ByteArrayInputStream("HELLO WORLD".getBytes(StandardCharsets.UTF_8));
    return service.sendMultipartData(body);
}
```
to:
```
@GET
@Path("/multipart")
@Produces(MediaType.TEXT_PLAIN)
public String sendFile() throws Exception {
    MultipartBody body = new MultipartBody();
    body.fileName = "greeting.txt";
    body.file = new ByteArrayInputStream("HELLO WORLD".getBytes(StandardCharsets.UTF_8));
    return service.sendMultipartData(body);
}
```

Now if you run it, it should fail with:

> RESTEASY003215: could not find writer for content-type multipart/form-data type: org.acme.rest.client.multipart.MultipartBody

To make it work, leave sendFile as GET and add another simple POST method in same class. Such as:
```
@POST
@Path("/temp")
@Produces(MediaType.TEXT_PLAIN)
public String simplePost() throws Exception {
    return "something";
}
```
Now it should work with GET.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Microsoft Windows [Version 10.0.18363.720]
 - Output of `java -version`: openjdk version "1.8.0_202"
 - Quarkus version or git rev: 1.3.0
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

### PR DESCRIPTION
**Pull request by gsmet**
They used to be registered as for the JAX-RS resources but they should
be registered the opposite way.

Fixes #8223

### CODE REVIEW

**Comment by gsmet** [comment]
I discussed with @irenakezic , she will provide an integration test as another PR.

File: extensions/resteasy-common/deployment/src/main/java/io/quarkus/resteasy/common/deployment/RestClientBuildItem.java [hunk 1]
```diff
@@ -0,0 +1,16 @@
+package io.quarkus.resteasy.common.deployment;
+
+import io.quarkus.builder.item.MultiBuildItem;
+
+public final class RestClientBuildItem extends MultiBuildItem {
```
Comment (geoand) [inline extensions/resteasy-common/deployment/src/main/java/io/quarkus/resteasy/common/deployment/RestClientBuildItem.java:5]: Can we have some Javadoc on this one?

It seems pretty generic to be able to understand what it's used for

**Review by geoand — APPROVED** [review]

File: extensions/resteasy-common/deployment/src/main/java/io/quarkus/resteasy/common/deployment/RestClientBuildItem.java (hunk 1 above)
Comment (gsmet) [reply extensions/resteasy-common/deployment/src/main/java/io/quarkus/resteasy/common/deployment/RestClientBuildItem.java:10]: Done.
