### PR TITLE
Warn about interceptors on private methods

### LINKED ISSUE #21046: Quarkus instrumentation warns about use of @Transactional on private methods
### Description

The `@Transactional` annotation does not work, if it's annotated on a `private` method:
```
@Transactional
private void doSomething() {
  A a = new A();
  a.persist();
}
```
Because the method is `private` the entity will not be persisted.

Even though I know about the rule, it does happen that the `private` sneaks in...

Would it be possible for Quarkus to detect this situation and warn the user? There are already warning about split packages and other potential problems...

### Implementation ideas

Warn the user about the usage of `private` and `@Transactional` - maybe even error and fail the build.

### PR DESCRIPTION
**Pull request by geoand**
Resolves: #21046

P.S. Another solution would be to remove the `private` modifier from the method same as we do for `final`, but I am not sure if we want that.

### CODE REVIEW

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Methods.java [hunk 1]
```diff
@@ -197,17 +197,31 @@ static boolean isObjectToString(MethodInfo method) {
                 }
             }
             if (!merged.isEmpty()) {
-                boolean addToCandidates = true;
-                if (Modifier.isFinal(method.flags())) {
-                    if (transformUnproxyableClasses) {
-                        methodsFromWhichToRemoveFinal.add(NameAndDescriptor.fromMethodInfo(method));
+                if (Modifier.isPrivate(method.flags())) {
+                    if (merged.size() == 1) {
+                        LOGGER.warn(String.format(
```
Comment (mkouba) [inline independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Methods.java:202]: How about the `Logger.warnf()` method instead of `String.format()`?

**Comment by mkouba** [comment]
> P.S. Another solution would be to remove the `private` modifier from the method same as we do for `final`, but I am not sure if we want that.

-1

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Methods.java (hunk 1 above)
Comment (geoand) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Methods.java]: Good idea, done

**Review by mkouba — APPROVED** [review]

**Comment by famod** [comment]
Thanks a lot for this! It's too easy to run into this problem, e.g. when refactoring existing code.

**Comment by geoand** [comment]
Indeed it is :)

**Comment by famod** [comment]
@geoand I colleague just lost quite a bit of time because he had `@Tranasctional(REQUIRES_NEW)` on a private method and he didn't see the warning (I did spot quickly when he asked for help but I guess not everyone is so "sensitive" to warnings).

So I'm wondering if we should provide a config property to control whether to just warn _or_ throw an exception?

**Comment by geoand** [comment]
Sure, that sounds like a good idea

**Comment by geoand** [comment]
Do you or your colleague want to open a PR for that? I can certainly do it.

**Comment by famod** [comment]
You are very welcome to do that! We are a bit in a rush for a release next week.

**Comment by geoand** [comment]
Hm... Actually the idea of this sort of conflicts with the `quarkus.arc.transform-unproxyable-classes`. 
We don't try to transform the private method case (and we do mention this in the docs of the property), but I am not sure it will be intuitive to users if we have something like `quarkus.arc.transform-unproxyable-classes=true` and `quarkus.arc.fail-on-private-interceptors=true`...

**Comment by mkouba** [comment]
Well, private intercepted observer/producer methods are legal and should work just fine so we would have to ignore these.

> but I am not sure it will be intuitive to users if we have something like quarkus.arc.transform-unproxyable-classes=true and quarkus.arc.fail-on-private-interceptors=true...

Private methods don't turn a class into an unproxyable type so it should be ok I think...

**Comment by geoand** [comment]
Understood, thanks

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/22185 takes care of it
