### PR TITLE
quarkus:create-extension fixes and enhancements

### LINKED ISSUE #3321: create-extension Maven mojo should allow creating from scratch
A followup of #2113 .

create-extension Maven mojo added via #3191 allows creating new extension modules inside an existing source tree. It should be enhanced to be able to create new extension projects from scratch.

cc @aloubyansky @Dufgui

### PR DESCRIPTION
**Pull request by aloubyansky**
This change includes the following improvements:
* make sure the generated extension project can actually be built (by adding if necessary the maven compiler plugin version, quarkus version property, importing quarkus-bom-deployment);
* support creating an extension project in an empty dir with a single command, e.g. mvn io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:create-extension -DgroupId=org.acme -DartifactId=my-ext -Dversion=1.0-SNAPSHOT;
* simplifies and aligns certain mojo parameter property names with quarkus:create.

Fixes #3321

### CODE REVIEW

**Comment by aloubyansky** [comment]
@gsmet @geoand how far is this on the list for review? Just so I can plan subsequent related tasks. Thanks!

**Comment by geoand** [comment]
@aloubyansky I was planning on taking a look today :)

**Comment by aloubyansky** [comment]
Great :) Thanks!

**Comment by geoand** [comment]
@aloubyansky One question for starters: is `-Dquarkus.version=1.2.0.Final` supposed to work? Because I tried it but the `quarkus.version` in the pom remained `999-SNAPSHOT`

**Comment by aloubyansky** [comment]
@geoand it's `quarkus.quarkusVersion` actually. All the props originally were prefixed with `quarkus.` in this mojo. Do you want me to deprecate `quarkus.quarkusVersion` and introduce `quarkus.version` (similarly to I did to `quarkus.groupId`, etc)? I'd probably go for that.

**Comment by geoand** [comment]
@aloubyansky I think that makes a lot of sense, I am +1 for that

**Comment by aloubyansky** [comment]
Ok, done and rebased.

**Comment by geoand** [comment]
Thanks!

File: devtools/maven/src/main/java/io/quarkus/maven/CreateExtensionMojo.java [hunk 1]
```diff
@@ -411,123 +558,318 @@ public void execute() throws MojoExecutionException, MojoFailureException {
...
+                                    + rootModel.getPackaging() + "");
+                }
+
+                if (rootPom.equals(project.getFile())) {
+                    importDeploymentBom = !hasQuarkusDeploymentBom();
+                    setCompilerPluginVersion = !project.getPluginManagement().getPluginsAsMap()
+                            .containsKey(COMPILER_PLUGIN_KEY);
+                    setQuarkusVersionProp = !project.getProperties().containsKey(QUARKUS_VERSION_PROP);
+                } else {
+                    // aloubyansky: not sure we should support this case and not sure it ever worked properly
```
Comment (geoand) [inline devtools/maven/src/main/java/io/quarkus/maven/CreateExtensionMojo.java]: I am also not sure about this... Can we be sure it will work? If not, I think we should focus on the simple use case for now that we know will work.

File: devtools/maven/src/main/java/io/quarkus/maven/CreateExtensionMojo.java [hunk 2]
```diff
@@ -411,123 +558,318 @@ public void execute() throws MojoExecutionException, MojoFailureException {
...
+                        final ArtifactDescriptorResult rootDescr = mvn.resolveDescriptor(rootArtifact);
+                        importDeploymentBom = !hasQuarkusDeploymentBom(rootDescr.getManagedDependencies());
+                        // TODO determine whether the compiler plugin is configured for the project
+                        setQuarkusVersionProp = !rootDescr.getProperties().containsKey(QUARKUS_VERSION_PROP);
+                    } catch (Exception e) {
+                        throw new MojoExecutionException("Failed to resolve " + rootArtifact + " descriptor", e);
+                    }
+                }
+            } else if (this.grandParentRelativePath != null) {
+                // aloubyansky: not sure we should support this case, same as above
```
Comment (geoand) [inline devtools/maven/src/main/java/io/quarkus/maven/CreateExtensionMojo.java]: Same as above as well :)

File: devtools/maven/src/main/java/io/quarkus/maven/CreateExtensionMojo.java [hunk 3]
```diff
@@ -370,18 +446,89 @@
...
+
+    Charset charset;
+
     @Override
     public void execute() throws MojoExecutionException, MojoFailureException {
 
         if (this.basedir == null) {
-            this.basedir = Paths.get(".").toAbsolutePath().normalize();
+            currentProjectIsBaseDir = true;
+            this.basedir = new File(".").getAbsoluteFile();
```
Comment (geoand) [inline devtools/maven/src/main/java/io/quarkus/maven/CreateExtensionMojo.java]: This does work on Windows too, right? 

I see it's also used in one other place in Quarkus so I guess it's OK. But I would like to know why this is prefered instead of what the previous incarnation of the code did.

Comment (aloubyansky) [reply devtools/maven/src/main/java/io/quarkus/maven/CreateExtensionMojo.java]: I haven't tested it on Windows actually. But I remember I had issues initializing it as `Path`, switching to File seemed to have fixed them. I'll try again now to be sure.

Comment (aloubyansky) [reply devtools/maven/src/main/java/io/quarkus/maven/CreateExtensionMojo.java]: Here is what I get by simply changing the type of `basedir` from `File` to `Path`:
```
[aloubyansky@lenora newdir]$ mvn io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:create-extension -DartifactId=my-ext -Dquarkus.basedir=../my-ext -e
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------< org.apache.maven:standalone-pom >-------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- quarkus-maven-plugin:999-SNAPSHOT:create-extension (default-cli) @ standalone-pom ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.139 s
[INFO] Finished at: 2020-01-30T12:01:07+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:create-extension (default-cli) on project standalone-pom: Unable to parse configuration of mojo io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:create-extension for parameter basedir: Cannot create instance of interface java.nio.file.Path: java.nio.file.Path.<init>() -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:create-extension (default-cli) on project standalone-pom: Unable to parse configuration of mojo io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:create-extension for parameter basedir: Cannot create instance of interface java.nio.file.Path
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.maven.plugin.PluginConfigurationException: Unable to parse configuration of mojo io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:create-extension for parameter basedir: Cannot create instance of interface java.nio.file.Path
    at org.apache.maven.plugin.internal.DefaultMavenPluginManager.populatePluginFields (DefaultMavenPluginManager.java:665)
    at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo (DefaultMavenPluginManager.java:597)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:124)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.codehaus.plexus.component.configurator.ComponentConfigurationException: Cannot create instance of interface java.nio.file.Path
    at org.codehaus.plexus.component.configurator.converters.AbstractConfigurationConverter.instantiateObject (AbstractConfigurationConverter.java:147)
    at org.codehaus.plexus.component.configurator.converters.composite.ObjectWithFieldsConverter.fromConfiguration (ObjectWithFieldsConverter.java:54)
    at org.eclipse.sisu.plexus.CompositeBeanHelper.convertProperty (CompositeBeanHelper.java:273)
    at org.eclipse.sisu.plexus.CompositeBeanHelper.setProperty (CompositeBeanHelper.java:210)
    at org.codehaus.plexus.component.configurator.converters.composite.ObjectWithFieldsConverter.processConfiguration (ObjectWithFieldsConverter.java:101)
    at org.codehaus.plexus.component.configurator.BasicComponentConfigurator.configureComponent (BasicComponentConfigurator.java:34)
    at org.apache.maven.plugin.internal.DefaultMavenPluginManager.populatePluginFields (DefaultMavenPluginManager.java:635)
    at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo (DefaultMavenPluginManager.java:597)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:124)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: java.lang.InstantiationException: java.nio.file.Path
    at java.lang.Class.newInstance (Class.java:427)
    at org.codehaus.plexus.component.configurator.converters.AbstractConfigurationConverter.instantiateObject (AbstractConfigurationConverter.java:143)
    at org.codehaus.plexus.component.configurator.converters.composite.ObjectWithFieldsConverter.fromConfiguration (ObjectWithFieldsConverter.java:54)
    at org.eclipse.sisu.plexus.CompositeBeanHelper.convertProperty (CompositeBeanHelper.java:273)
    at org.eclipse.sisu.plexus.CompositeBeanHelper.setProperty (CompositeBeanHelper.java:210)
    at org.codehaus.plexus.component.configurator.converters.composite.ObjectWithFieldsConverter.processConfiguration (ObjectWithFieldsConverter.java:101)
    at org.codehaus.plexus.component.configurator.BasicComponentConfigurator.configureComponent (BasicComponentConfigurator.java:34)
    at org.apache.maven.plugin.internal.DefaultMavenPluginManager.populatePluginFields (DefaultMavenPluginManager.java:635)
    at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo (DefaultMavenPluginManager.java:597)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:124)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: java.lang.NoSuchMethodException: java.nio.file.Path.<init>()
    at java.lang.Class.getConstructor0 (Class.java:3082)
    at java.lang.Class.newInstance (Class.java:412)
    at org.codehaus.plexus.component.configurator.converters.AbstractConfigurationConverter.instantiateObject (AbstractConfigurationConverter.java:143)
    at org.codehaus.plexus.component.configurator.converters.composite.ObjectWithFieldsConverter.fromConfiguration (ObjectWithFieldsConverter.java:54)
    at org.eclipse.sisu.plexus.CompositeBeanHelper.convertProperty (CompositeBeanHelper.java:273)
    at org.eclipse.sisu.plexus.CompositeBeanHelper.setProperty (CompositeBeanHelper.java:210)
    at org.codehaus.plexus.component.configurator.converters.composite.ObjectWithFieldsConverter.processConfiguration (ObjectWithFieldsConverter.java:101)
    at org.codehaus.plexus.component.configurator.BasicComponentConfigurator.configureComponent (BasicComponentConfigurator.java:34)
    at org.apache.maven.plugin.internal.DefaultMavenPluginManager.populatePluginFields (DefaultMavenPluginManager.java:635)
    at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo (DefaultMavenPluginManager.java:597)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:124)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
```

Comment (aloubyansky) [reply devtools/maven/src/main/java/io/quarkus/maven/CreateExtensionMojo.java]: This same command works if `basedir` is a `File`.

Comment (geoand) [reply devtools/maven/src/main/java/io/quarkus/maven/CreateExtensionMojo.java]: OK, thanks for checking!

File: devtools/maven/src/main/java/io/quarkus/maven/CreateExtensionMojo.java [hunk 4]
```diff
@@ -411,123 +558,318 @@ public void execute() throws MojoExecutionException, MojoFailureException {
...
+            pomTransformer(basePomXml).transform(Transformation.addModule(templateParams.artifactIdBase));
+        }
+    }
+
+    private void generateExtensionProjects(Configuration cfg, TemplateParams templateParams)
+            throws IOException, TemplateException, MojoExecutionException {
+        evalTemplate(cfg, "parent-pom.xml", getExtensionProjectBaseDir().resolve("pom.xml"), templateParams);
+
+        Files.createDirectories(
+                getExtensionRuntimeBaseDir().resolve("src/main/java")
```
Comment (geoand) [inline devtools/maven/src/main/java/io/quarkus/maven/CreateExtensionMojo.java]: I also want to see if this work on Windows, but CI should give us an answer soon enough :)

**Comment by geoand** [comment]
I tried the basics and it works great!

I am in favor of getting this in now so @aloubyansky can continue his work in this area. If any problems do arise they can of course be fixed promptly.

**Comment by aloubyansky** [comment]
Just in case, one context in which this command has been useful is creating a new extension project in the Quarkus repo (adding the artifacts to the BOMs and adding the corresponding IT module). I did try that, it still seems to work as before.

**Review by geoand — APPROVED** [review]
