### PR TITLE
Declare all test source directories in gradle model

### LINKED ISSUE #15618: Java resource classes in src/test/java are not properly loaded
**Describe the bug**
It seems that resource classes that are written in Java and placed in the `src/test/java` directory are not properly loaded into Quarkus when running tests.

This was discovered when I was trying to figure out a problem with null values appearing in my `@PathParam` method parameters. I created a comprehensive test project here:
https://github.com/StFS/quarkus-test-resources

Check this project out and run `./gradlew test` to see how unit tests that try to reach resources that are defined in Java classes within the `test/src/java` directory encounter a 404 response from Quarkus.

**Expected behavior**
Unit tests that access resources defined by Java resource classes in `src/test/java` should get a response from those resources.

**Actual behavior**
Unit tests trying to access resources from Java classes within the `src/test/java` directory get a 404 response and the resource classes are never invoked.

**To Reproduce**

(sorry, this is a gradle project, but I don't believe the issue has anything to do with gradle)
https://github.com/StFS/quarkus-test-resources

1. Check out the project
2. Run `./gradlew test`

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
`Darwin Stefans-MBP.localdomain 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64`

 - Output of `java -version`:
```
openjdk version "15" 2020-09-15
OpenJDK Runtime Environment AdoptOpenJDK (build 15+36)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15+36, mixed mode, sharing) 
``` 
 - GraalVM version (if different from Java): `N/A`

 - Quarkus version or git rev: 
`1.12.1.Final`

 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
```
------------------------------------------------------------
Gradle 6.8.3
------------------------------------------------------------

Build time:   2021-02-22 16:13:28 UTC
Revision:     9e26b4a9ebb910eaa1b8da8ff8575e514bc61c78

Kotlin:       1.4.20
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          15 (AdoptOpenJDK 15+36)
OS:           Mac OS X 10.16 x86_64
```

### PR DESCRIPTION
**Pull request by glefloch**
By default, we look for CDI beans in the directory that contains de test. In multi language project, CDI beans in `src/test/java` are not loaded if run a test from `src/test/kotlin`. 

This branch add all test dirs in the model when we are in test mode.

close #15618

### CODE REVIEW

File: devtools/gradle/src/main/java/io/quarkus/gradle/extension/QuarkusPluginExtension.java [hunk 1]
```diff
@@ -193,8 +194,11 @@ public SourceSetExtension sourceSetExtension() {
         return getSourceSets().getByName(SourceSet.MAIN_SOURCE_SET_NAME).getResources().getSrcDirs();
     }
 
-    public Set<File> outputSourcesDir() {
-        return getSourceSets().getByName(SourceSet.MAIN_SOURCE_SET_NAME).getOutput().getClassesDirs().getFiles();
+    public Set<File> combinedOutputSourceDirs() {
+        Set<File> sourcesDirs = new HashSet<>();
```
Comment (gastaldi) [inline devtools/gradle/src/main/java/io/quarkus/gradle/extension/QuarkusPluginExtension.java:198]: Do order matter here?

Comment (glefloch) [reply devtools/gradle/src/main/java/io/quarkus/gradle/extension/QuarkusPluginExtension.java:198]: I don't think so, but we can definitely add the test directories after main source sets.

**Review by gastaldi — APPROVED** [review]
LGTM

**Review by aloubyansky — APPROVED** [review]
