### PR TITLE
Gradle: avoid resolving deprecated compileOnly configuration

### LINKED ISSUE #11182: Gradle 6.5.1 quarkusDev  fails with Quarkus 1.6.1
Apologies, if this has been reported already/fixed in 1.7RC. The **quarkusDev** task uses the deprecated **compileOnly** scope.

**./gradlew quarkusDev --warning-mode all**

Task :recres-webapp:quarkusDev FAILED
**The compileOnly configuration has been deprecated for resolution. This will fail with an error in Gradle 7.0. Please resolve the compileClasspath configuration instead. Consult the upgrading guide for further information: https://docs.gradle.org/6.5.1/userguide/upgrading_version_5.html#dependencies_should_no_longer_be_declared_using_the_compile_and_runtime_configurations**

FAILURE: Build failed with an exception.

### PR DESCRIPTION
**Pull request by aloubyansky**
Fixes #11182

Besides avoiding resolution of `compileOnly` configuration which is deprecated for resolution, this change includes a better (proper) approach to resolve devmode classpath by defining a custom configuration that extends from compile and runtime configurations.
Lombok-based project is included as a testcase.

### CODE REVIEW

**Comment by aloubyansky** [comment]
@gsmet do you think we can include it in 1.7.0?

File: devtools/gradle/src/main/java/io/quarkus/gradle/builder/QuarkusModelBuilder.java [hunk 1]
```diff
@@ -48,17 +46,27 @@
 import io.quarkus.gradle.tasks.QuarkusGradleUtils;
 import io.quarkus.runtime.LaunchMode;
 
-public class QuarkusModelBuilder implements ParameterizedToolingModelBuilder {
+public class QuarkusModelBuilder implements ParameterizedToolingModelBuilder<ModelParameter> {
 
-    private static final List<String> scannedConfigurations = new LinkedList();
```
Comment (aloubyansky) [inline devtools/gradle/src/main/java/io/quarkus/gradle/builder/QuarkusModelBuilder.java:53]: This static field is in fact critical a critical issue because an instance of this class will be shared between builds (and probably also projects).

**Review by gastaldi — APPROVED** [review]
LGTM, good job on removing that static field

**Review by gsmet — DISMISSED** [review]
Added a small question we need to sort out before merging.

File: devtools/gradle/src/main/java/io/quarkus/gradle/builder/QuarkusModelBuilder.java [hunk 2]
```diff
@@ -48,17 +46,27 @@
...
+    private static Configuration classpathConfig(Project project, LaunchMode mode) {
+        if (LaunchMode.TEST.equals(mode)) {
+            return project.getConfigurations().getByName(JavaPlugin.TEST_RUNTIME_CLASSPATH_CONFIGURATION_NAME);
+        }
+        if (LaunchMode.DEVELOPMENT.equals(mode)) {
+            return project.getConfigurations().create("quarkusDevMode").extendsFrom(
+                    project.getConfigurations().getByName(JavaPlugin.COMPILE_CLASSPATH_CONFIGURATION_NAME),
+                    project.getConfigurations().getByName(JavaPlugin.RUNTIME_CLASSPATH_CONFIGURATION_NAME));
```
[the remark this answers is not in the document]
Comment (aloubyansky) [reply devtools/gradle/src/main/java/io/quarkus/gradle/builder/QuarkusModelBuilder.java:58]: The order doesn't matter. We are after a combined set of those.

File: integration-tests/gradle/build.gradle [hunk 3]
```diff
@@ -34,6 +34,7 @@ dependencies {
     testImplementation 'org.assertj:assertj-core:3.16.1'
     testImplementation 'org.junit.jupiter:junit-jupiter:5.6.2'
     testImplementation 'org.awaitility:awaitility:4.0.3'
+    testImplementation "org.projectlombok:lombok:${lombokVersion}"
```
Comment (glefloch) [inline integration-tests/gradle/build.gradle:37]: Is this dependency needed here?

**Review by glefloch — APPROVED** [review]
LGTM, just a small question on the `lombok` dependency added in the module

File: integration-tests/gradle/build.gradle (hunk 3 above)
Comment (aloubyansky) [reply integration-tests/gradle/build.gradle:37]: The only reason I added it here was to pre-download it. But it's not needed. I'll probably remove it. Figuring out why the CI fails. Perhaps another maven local repo path related issue.

**Comment by aloubyansky** [comment]
Interesting, so the testcase stumbles on 
```
2020-08-06 15:40:44,209 INFO  [io.qua.dep.dev.RuntimeUpdatesProcessor] (vert.x-worker-thread-1) Changed source files detected, recompiling [/tmp/compile-only-lombok8685283865026176289/src/main/java/io/playground/HelloResource.java, /tmp/compile-only-lombok8685283865026176289/src/main/java/io/playground/MyData.java, /tmp/compile-only-lombok8685283865026176289/src/main/java/io/playground/MyDataProducer.java]
```
Perhaps it should be waiting a longer time.

**Comment by gsmet** [comment]
This will have to wait for 1.7.1.Final.

**Comment by aloubyansky** [comment]
I disabled the test for now, We need this in 1.7.0.Final.
