### PR TITLE
Don't open the HTTP socket until late in the startup process

### LINKED ISSUE #8269: OIDC initialization race condition in DefaultTenantConfigResolver in the native image
**Describe the bug**
Guillaume has reported it earlier, so we added some checks, and the latest #7940 [native build](https://github.com/quarkusio/quarkus/pull/7940/checks?check_run_id=543714208) failed with:
```
020-03-29 20:07:01,611 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-2) HTTP Request to /public-web-app/access failed, error id: 98f49e48-e695-4598-b7c3-db893cc57fa3-1: java.lang.IllegalStateException: staticTenantsConfig is null
	at io.quarkus.oidc.runtime.DefaultTenantConfigResolver.getTenantConfigFromTenantResolver(DefaultTenantConfigResolver.java:81)
	at io.quarkus.oidc.runtime.DefaultTenantConfigResolver.resolve(DefaultTenantConfigResolver.java:61)
	at io.quarkus.oidc.runtime.DefaultTenantConfigResolver_ClientProxy.resolve(DefaultTenantConfigResolver_ClientProxy.zig:208)
	at io.quarkus.oidc.runtime.OidcAuthenticationMechanism.isWebApp(OidcAuthenticationMechanism.java:42)
	at io.quarkus.oidc.runtime.OidcAuthenticationMechanism.authenticate(OidcAuthenticationMechanism.java:31)
	at io.quarkus.oidc.runtime.OidcAuthenticationMechanism_ClientProxy.authenticate(OidcAuthenticationMechanism_ClientProxy.zig:284)
	at io.quarkus.vertx.http.runtime.security.HttpAuthenticator.attemptAuthentication(HttpAuthenticator.java:96)
	at io.quarkus.vertx.http.runtime.security.HttpAuthenticator_ClientProxy.attemptAuthentication(HttpAuthenticator_ClientProxy.zig:150)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$1.handle(HttpSecurityRecorder.java:47)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$1.handle(HttpSecurityRecorder.java:36)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:130)
	at io.quarkus.vertx.http.runtime.cors.CORSFilter.handle(CORSFilter.java:80)
	at io.quarkus.vertx.http.runtime.cors.CORSFilter.handle(CORSFilter.java:17)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:130)
	at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:54)
	at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:36)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:290)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$1.handle(VertxHttpRecorder.java:99)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$1.handle(VertxHttpRecorder.java:90)
```

`staticTenantsConfig` is initialized in `oidcRecorder` and then set as a `DefaultTenantConfigResolver` property. 

I think what I can try to do is to pass it to `DefaultTenantConfigResolver` constructor.

CC @stuartwdouglas

### PR DESCRIPTION
**Pull request by stuartwdouglas**
This makes sure that we don't open the HTTP socket until
all start events have been run and all ServiceStartBuildItem
events have been run.

This also makes sure that the runtime bean map has been initialized
by this point.

Fixes #8269

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
@cescoffier we should try and do something similar for messaging to make sure message processing does not start until after the app is fully initialised.

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/DefaultTenantConfigResolver.java [hunk 1]
```diff
@@ -27,18 +26,17 @@
     @Inject
     Instance<TenantConfigResolver> tenantConfigResolver;
 
-    private volatile Map<String, TenantConfigContext> staticTenantsConfig;
-    private volatile TenantConfigContext defaultTenant;
-    private volatile Function<OidcTenantConfig, TenantConfigContext> tenantConfigContextFactory;
-    private volatile Map<String, TenantConfigContext> dynamicTenantsConfig;
+    private final Map<String, TenantConfigContext> dynamicTenantsConfig = new ConcurrentHashMap<>();
```
Comment (sberyozkin) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/DefaultTenantConfigResolver.java]: @stuartwdouglas I'm not sure a concurrent map is needed since we still synchronize on it, the sync block is needed to avoid the concurrent connection requests. But I suppose it is performing better anyway, the concurrent map.

File: extensions/oidc/deployment/src/main/java/io/quarkus/oidc/deployment/OidcBuildStep.java [hunk 2]
```diff
@@ -66,9 +69,15 @@ EnableAllSecurityServicesBuildItem security() {
...
     @Record(ExecutionTime.RUNTIME_INIT)
     @BuildStep(onlyIf = IsEnabled.class)
-    public void setup(OidcConfig config, OidcRecorder recorder, CoreVertxBuildItem vertxBuildItem,
-            BeanContainerBuildItem bc) {
-        recorder.setup(config, vertxBuildItem.getVertx(), bc.getValue());
+    public SyntheticBeanBuildItem setup(
+            OidcConfig config,
+            OidcRecorder recorder,
+            CoreVertxBuildItem vertxBuildItem) {
+        return SyntheticBeanBuildItem.configure(TenantConfigBean.class).unremovable().types(TenantConfigBean.class)
```
Comment (sberyozkin) [inline extensions/oidc/deployment/src/main/java/io/quarkus/oidc/deployment/OidcBuildStep.java]: Interesting, so this is how one can register the application scoped like singletons at runtime

**Review by sberyozkin — APPROVED** [review]
@stuartwdouglas Thanks for a super fast fix

**Comment by sberyozkin** [comment]
@gsmet @pedroigor I'd not mind merging this one soon as all OIDC related PRs would be failing pretty frequently without it :-), it looks good.

**Comment by sberyozkin** [comment]
Hi All let me go ahead - please reopen if there are any concerns; I'd like to rebase the other pending PR against it

File: extensions/vertx-core/deployment/src/main/java/io/quarkus/vertx/core/deployment/VertxCoreProcessor.java [hunk 3]
```diff
@@ -69,12 +64,19 @@ IOThreadDetectorBuildItem ioThreadDetector(VertxCoreRecorder recorder) {
...
             LaunchModeBuildItem launchMode, ShutdownContextBuildItem shutdown, VertxConfiguration config,
+            BuildProducer<SyntheticBeanBuildItem> syntheticBeanBuildItemBuildProducer,
             BuildProducer<ServiceStartBuildItem> serviceStartBuildItem) {
 
-        Supplier<Vertx> vertx = recorder.configureVertx(beanContainer.getValue(), config,
+        Supplier<Vertx> vertx = recorder.configureVertx(config,
                 launchMode.getLaunchMode(), shutdown);
+        syntheticBeanBuildItemBuildProducer.produce(SyntheticBeanBuildItem.configure(Vertx.class)
+                .types(Vertx.class)
+                .scope(ApplicationScoped.class)
```
Comment (cescoffier) [inline extensions/vertx-core/deployment/src/main/java/io/quarkus/vertx/core/deployment/VertxCoreProcessor.java:76]: @stuartwdouglas I need it to be a Singleton. Many clients are casting it to VertxInternal (I know it's bad). With ApplciaitonScoped it does not work anymore.

Comment (stuartwdouglas) [reply extensions/vertx-core/deployment/src/main/java/io/quarkus/vertx/core/deployment/VertxCoreProcessor.java:76]: https://github.com/quarkusio/quarkus/pull/8339
