### PR TITLE
Include sun.security.util.Resources bundle in native image

### LINKED ISSUE #6236: quarkus-integration-test-infinispan-embedded tests execution fails in native mode with JDK 11
**Describe the bug**
```
2019-12-17 19:31:24,132 ERROR [io.qua.application] (main) Failed to start application: java.lang.RuntimeException: Error injecting org.infinispan.manager.EmbeddedCacheManager io.quarkus.it.infinispan.embedded.TestServlet.emc
	at io.quarkus.it.infinispan.embedded.TestServlet_Bean.create(TestServlet_Bean.zig:280)
	at io.quarkus.it.infinispan.embedded.TestServlet_Bean.create(TestServlet_Bean.zig:189)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:80)
	at io.quarkus.arc.impl.ComputingCache$CacheFunction.lambda$apply$0(ComputingCache.java:99)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.getValue(ComputingCache.java:41)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:25)
	at io.quarkus.it.infinispan.embedded.TestServlet_Bean.get(TestServlet_Bean.zig:73)
	at io.quarkus.it.infinispan.embedded.TestServlet_Bean.get(TestServlet_Bean.zig:218)
	at io.quarkus.it.infinispan.embedded.TestServlet_Observer_onStart_fd71b5e0b207b7d1ef838b94eaeff75e52b8f463.notify(TestServlet_Observer_onStart_fd71b5e0b207b7d1ef838b94eaeff75e52b8f463.zig:40)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:224)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:65)
	at io.quarkus.arc.runtime.LifecycleEventRunner.fireStartupEvent(LifecycleEventRunner.java:23)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:108)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent56.deploy_0(LifecycleEventsBuildStep$startupEvent56.zig:77)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent56.deploy(LifecycleEventsBuildStep$startupEvent56.zig:36)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:180)
	at io.quarkus.runtime.Application.start(Application.java:87)
	at io.quarkus.runtime.Application.run(Application.java:210)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:41)
Caused by: org.infinispan.manager.EmbeddedCacheManagerStartupException: org.infinispan.commons.CacheConfigurationException: Error starting component org.infinispan.xsite.BackupReceiverRepository
	at org.infinispan.manager.DefaultCacheManager.internalStart(DefaultCacheManager.java:746)
	at org.infinispan.manager.DefaultCacheManager.start(DefaultCacheManager.java:712)
	at org.infinispan.manager.DefaultCacheManager.<init>(DefaultCacheManager.java:390)
	at io.quarkus.infinispan.embedded.runtime.InfinispanEmbeddedProducer.manager(InfinispanEmbeddedProducer.java:47)
	at io.quarkus.infinispan.embedded.runtime.InfinispanEmbeddedProducer_ProducerMethod_manager_ed18b755467e1c5fdc8a90c62127a21080a24841_Bean.create(InfinispanEmbeddedProducer_ProducerMethod_manager_ed18b755467e1c5fdc8a90c62127a21080a24841_Bean.zig:90)
	at io.quarkus.infinispan.embedded.runtime.InfinispanEmbeddedProducer_ProducerMethod_manager_ed18b755467e1c5fdc8a90c62127a21080a24841_Bean.create(InfinispanEmbeddedProducer_ProducerMethod_manager_ed18b755467e1c5fdc8a90c62127a21080a24841_Bean.zig:134)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:80)
	at io.quarkus.arc.impl.ComputingCache$CacheFunction.lambda$apply$0(ComputingCache.java:99)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.getValue(ComputingCache.java:41)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:25)
	at io.quarkus.infinispan.embedded.runtime.InfinispanEmbeddedProducer_ProducerMethod_manager_ed18b755467e1c5fdc8a90c62127a21080a24841_Bean.get(InfinispanEmbeddedProducer_ProducerMethod_manager_ed18b755467e1c5fdc8a90c62127a21080a24841_Bean.zig:43)
	at io.quarkus.infinispan.embedded.runtime.InfinispanEmbeddedProducer_ProducerMethod_manager_ed18b755467e1c5fdc8a90c62127a21080a24841_Bean.get(InfinispanEmbeddedProducer_ProducerMethod_manager_ed18b755467e1c5fdc8a90c62127a21080a24841_Bean.zig:343)
	at io.quarkus.it.infinispan.embedded.TestServlet_Bean.create(TestServlet_Bean.zig:263)
	... 19 more
Caused by: org.infinispan.commons.CacheConfigurationException: Error starting component org.infinispan.xsite.BackupReceiverRepository
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:555)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.access$700(BasicComponentRegistryImpl.java:30)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:770)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startDependencies(BasicComponentRegistryImpl.java:605)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:569)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:547)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.access$700(BasicComponentRegistryImpl.java:30)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:770)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startDependencies(BasicComponentRegistryImpl.java:605)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:569)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:547)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.access$700(BasicComponentRegistryImpl.java:30)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:770)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startDependencies(BasicComponentRegistryImpl.java:605)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:569)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:547)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.access$700(BasicComponentRegistryImpl.java:30)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:770)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startDependencies(BasicComponentRegistryImpl.java:605)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:569)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:547)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.access$700(BasicComponentRegistryImpl.java:30)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:770)
	at org.infinispan.factories.AbstractComponentRegistry.internalStart(AbstractComponentRegistry.java:344)
	at org.infinispan.factories.AbstractComponentRegistry.start(AbstractComponentRegistry.java:240)
	at org.infinispan.manager.DefaultCacheManager.internalStart(DefaultCacheManager.java:741)
	... 32 more
Caused by: java.util.MissingResourceException: Resource bundle not found sun.security.utException in thread "main" il.Resources. Register the resource bundle using the option -H:IncludeResourceBundles=sun.security.ujava.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:210)
	at io.quarkus.runtime.Application.start(Application.java:87)
	at io.quarkus.til.Resources.
	at com.oracle.svm.core.jdk.LocalizationSupport.getCached(LocalizationSupport.java:66)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:53)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at sun.security.util.ResourcesMgr.getBundle(ResourcesMgr.java:54)
	at sun.security.util.ResourcesMgr.getString(ResourcesMgr.java:40)
	at javax.security.auth.Subject.getSubject(Subject.java:292)
	at org.infinispan.security.Security.getSubject(Security.java:147)
	at org.infinispan.notifications.impl.AbstractListenerImpl.validateAndAddListenerInvocations(AbstractListenerImpl.java:215)
	at org.infinispan.notifications.cachemanagerlistener.CacheManagerNotifierImpl.addListenerAsync(CacheManagerNotifierImpl.java:172)
	at org.infinispan.notificatioruntime.Application.run(Application.java:210)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:41)
Caused by: java.lang.RuntimeException: Error injecting org.infinispan.manager.EmbeddedCacheManager io.quarkus.it.infinispan.embedded.TestServlet.emc
	at io.quarkus.it.infinispan.embedded.TestServlet_Bean.create(TestServlet_Bean.zig:280)
	at io.quarkus.it.infinispan.embedded.TestServlet_Bean.create(TestServlet_Bean.zig:189)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:80)
	at io.quarkus.arc.impl.ComputingCache$CacheFunction.lambda$apply$0(ComputingCache.java:99)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.getValue(ComputingCache.java:41)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:25)
	at io.quarkus.it.infinispan.embedded.TestServlet_Bean.get(TestSerns.Listenable.addListener(Listenable.java:26)
	at org.infinispan.xsite.BackupReceiverRepositoryImpl.start(BackupReceiverRepositoryImpl.java:41)
	at org.infinispan.xsite.CorePackageImpl$1.start(CorePackageImpl.java:39)
	at org.infinispan.xsite.CorePackageImpl$1.start(CorePackageImpl.java:31)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeStart(BasicComponentRegistryImpl.java:587vlet_Bean.zig:73)
	at io.quarkus.it.infinispan.embedded.TestServlet_Bean.get(TestServlet_Bean.zig:218)
	at io.quarkus.it.infinispan.embedded.TestServlet_Observer_onStart_fd71b5e0b207b7d1ef838b94eaeff75e52b8f463.notify(TestServlet_Observer_onStart_fd71b5e0b207b7d1ef838b94eaeff75e52b8f463.zig:40)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:224)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:65)
	at io.quarkus.arc.runtime.LifecycleEventRunner.fireStartupEvent(LifecycleEventRunner.java:23)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:108)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent56.deploy_0(LifecycleEventsBuildStep$startupEvent56.zig:77)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent56.deploy(LifecycleEventsBuildStep$startupEvent56.zig:36)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:180)
	... 3 more
Caused by: org.infinispan.manager.EmbeddedCacheManagerStartupException: org.infinispan.commons.CacheConfigurationException: Error starting component org.infinispan.xsite.BackupReceiverRepository
	at org.infinispan.manager.DefaultCacheManager.internalStart(DefaultCacheManager.java:746)
	at org.infinispan.manager.DefaultCacheManager.start(DefaultCacheManager.java:712)
	at org.infinispan.manager.DefaultCacheManager.<init>(DefaultCacheManager.java:390)
	at io.quarkus.infinispan.embedded.runtime.InfinispanEmbeddedProducer.manager(InfinispanEmbeddedProducer.java:47)
	at io.quarkus.infinispan.embedded.runtime.InfinispanEmbeddedProducer_ProducerMethod_manager_ed18b755467e1c5fdc8a90c62127a21080a24841_Bean.create(InfinispanEmbeddedProducer_ProducerMethod_manager_ed18b755467e1c5fdc8a90c62127a21080a24841_Bean.zig:90)
	at io.quarkus.infinispan.embedded.runtime.InfinispanEmbeddedProducer_ProducerMethod_manager_ed18b755467e1c5fdc8a90c62127a21080a24841_Bean.create(InfinispanEmbeddedProducer_ProducerMethod_manager_ed18b755467e1c5fdc8a90c62127a21080a24841_Bean.zig:134)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.ja)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:578)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponva:80)
	at io.quarkus.arc.impl.ComputingCache$CacheFunction.lambda$apply$0(ComputingCache.java:99)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.getValue(ComputingCache.java:41)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:25)
	at io.quarkus.infinispan.embedded.runtime.InfinispanEmbeddedProducer_ProducerMethod_manageentRegistryImpl.java:547)
	... 57 more

r_ed18b755467e1c5fdc8a90c62127a21080a24841_Bean.get(InfinispanEmbeddedProducer_ProducerMethod_manager_ed18b755467e1c5fdc8a90c62127a21080a24841_Bean.zig:43)
	at io.quarkus.infinispan.embedded.runtime.InfinispanEmbeddedProducer_ProducerMethod_manager_ed18b755467e1c5fdc8a90c62127a21080a24841_Bean.get(InfinispanEmbeddedProducer_ProducerMethod_manager_ed18b755467e1c5fdc8a90c62127a21080a24841_Bean.zig:343)
	at io.quarkus.it.infinispan.embedded.TestServlet_Bean.create(TestServlet_Bean.zig:263)
	... 19 more
Caused by: org.infinispan.commons.CacheConfigurationException: Error starting component org.infinispan.xsite.BackupReceiverRepository
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:555)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.access$700(BasicComponentRegistryImpl.java:30)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:770)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startDependencies(BasicComponentRegistryImpl.java:605)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:569)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:547)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.access$700(BasicComponentRegistryImpl.java:30)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:770)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startDependencies(BasicComponentRegistryImpl.java:605)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:569)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:547)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.access$700(BasicComponentRegistryImpl.java:30)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:770)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startDependencies(BasicComponentRegistryImpl.java:605)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:569)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:547)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.access$700(BasicComponentRegistryImpl.java:30)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:770)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startDependencies(BasicComponentRegistryImpl.java:605)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:569)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:547)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.access$700(BasicComponentRegistryImpl.java:30)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:770)
	at org.infinispan.factories.AbstractComponentRegistry.internalStart(AbstractComponentRegistry.java:344)
	at org.infinispan.factories.AbstractComponentRegistry.start(AbstractComponentRegistry.java:240)
	at org.infinispan.manager.DefaultCacheManager.internalStart(DefaultCacheManager.java:741)
	... 32 more
Caused by: java.util.MissingResourceException: Resource bundle not found sun.security.util.Resources. Register the resource bundle using the option -H:IncludeResourceBundles=sun.security.util.Resources.
	at com.oracle.svm.core.jdk.LocalizationSupport.getCached(LocalizationSupport.java:66)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:53)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at sun.security.util.ResourcesMgr.getBundle(ResourcesMgr.java:54)
	at sun.security.util.ResourcesMgr.getString(ResourcesMgr.java:40)
	at javax.security.auth.Subject.getSubject(Subject.java:292)
	at org.infinispan.security.Security.getSubject(Security.java:147)
	at org.infinispan.notifications.impl.AbstractListenerImpl.validateAndAddListenerInvocations(AbstractListenerImpl.java:215)
	at org.infinispan.notifications.cachemanagerlistener.CacheManagerNotifierImpl.addListenerAsync(CacheManagerNotifierImpl.java:172)
	at org.infinispan.notifications.Listenable.addListener(Listenable.java:26)
	at org.infinispan.xsite.BackupReceiverRepositoryImpl.start(BackupReceiverRepositoryImpl.java:41)
	at org.infinispan.xsite.CorePackageImpl$1.start(CorePackageImpl.java:39)
	at org.infinispan.xsite.CorePackageImpl$1.start(CorePackageImpl.java:31)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeStart(BasicComponentRegistryImpl.java:587)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:578)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:547)
	... 57 more
```

**To Reproduce**
Steps to reproduce the behavior from the `master` branch:
1. (Optional) Set the `JAVA_HOME` environment variable to a JDK 11 installation directory (OpenJDK 11 or GraalVM 19.3.0 JDK 11 edition). Add the JDK 11 `bin` directory to the path.
2. (Optional) Run `./mvnw clean install -Dmaven.test.skip=true` to build all the Quarkus sources with the JDK 11.
3. Run `./mvnw clean install --projects :quarkus-integration-test-infinispan-embedded -Dquarkus.native.container-build=true -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-native-image:19.3.0-java11`.

### PR DESCRIPTION
**Pull request by gwenneg**
Fixes #6236 

This was successfully tested locally with GraalVM 19.3.0 and JDK 11. Let's see if CI is happy as well (it wasn't tested with JDK 8 locally).

### CODE REVIEW

File: extensions/infinispan-embedded/deployment/src/main/java/io/quarkus/infinispan/embedded/deployment/InfinispanEmbeddedProcessor.java [hunk 1]
```diff
@@ -209,4 +210,9 @@ private void addReflectionForName(String className, boolean isInterface, IndexVi
     void configureRuntimeProperties(InfinispanRecorder recorder, InfinispanEmbeddedRuntimeConfig runtimeConfig) {
         recorder.configureRuntimeProperties(runtimeConfig);
     }
+
+    @BuildStep
+    public NativeImageResourceBundleBuildItem nativeImageResourceBundle() {
+        return new NativeImageResourceBundleBuildItem("sun.security.util.Resources");
```
Comment (gsmet) [inline extensions/infinispan-embedded/deployment/src/main/java/io/quarkus/infinispan/embedded/deployment/InfinispanEmbeddedProcessor.java]: I think I would do that somewhere in the core. Not in a specific extension. Given that's a JDK class and there's a good chance we might need this for other extensions.

**Review by gsmet — CHANGES_REQUESTED** [review]

File: extensions/infinispan-embedded/deployment/src/main/java/io/quarkus/infinispan/embedded/deployment/InfinispanEmbeddedProcessor.java (hunk 1 above)
Comment (gwenneg) [reply extensions/infinispan-embedded/deployment/src/main/java/io/quarkus/infinispan/embedded/deployment/InfinispanEmbeddedProcessor.java]: I thought about it too, but since I have no idea of the impact it can have on the native image (in termes of size, memory, etc.), I went for the cautious way. I'll move it to `quarkus-core-deployment`.

**Comment by jaikiran** [comment]
Hello @gwenneg, I think additionally, we should raise this as a question/ issue to the graal team. Looking at the stacktrace in the linked issue, it's coming from within a JRE internal class ('sun.security.util.ResourceMgr') so I think the resource bundle for such usages should be auto included by substratevm itself (ofcourse if that class is considered reachable).

Furthermore, do you know why this happens only with Java 11?  I would have checked these details myself but I dont have access to any of this codebase for a couple of days.

Having said all that, I think what you propose in this PR is fine and we can decide if this needs to be removed if this happens to be something that graal handles in any of their subsequent release.

**Comment by gwenneg** [comment]
@jaikiran Your auto-inclusion question is a good one, I relayed it here: https://github.com/oracle/graal/issues/2005. Let's give them a chance to answer before moving the fix to `quarkus-core-deployment`.

Regarding the reason why it's happening with JDK 11 only, I don't know for now, but I'll take a look at it today or tomorrow.

**Comment by gsmet** [comment]
So we had a few issues similar to that where an exception is raised and the exception message is translated using a resource bundle.

Dunno if it's the case here but that's how it manifested a few times.

**Comment by gwenneg** [comment]
@gsmet I moved the fix to `quarkus-core-deployment`. Can you review this again please?

**Comment by gwenneg** [comment]
@jaikiran I don't if that's related, but it seems the `ResourcesMgr` code in JDK 9. The bundle was loaded in JDK 8 using a `doPrivileged` block which was removed in JDK 9: http://hg.openjdk.java.net/jdk9/jdk9/jdk/rev/5c7dda0aa8ce

**Review by gsmet — APPROVED** [review]
