### PR TITLE
ArC: proper validation of abstract methods on decorators

### LINKED ISSUE #51196: ArC: imprecise check for abstract methods in decorators
### Describe the bug

The check for `abstract` methods declared in decorators, as present in `Decorators.createDecorator()`, is imprecise. We check that decorators do not declare _any_ `abstract` methods, but the spec says that decorators may not declare `abstract` methods that do not belong to a decorated type. Also, we only check methods declared on the decorator class itself, not inherited methods. (We can probably ignore `abstract` methods inherited from interfaces, because those are decorated types, but a decorator can inherit `abstract` methods from a superclass, and those do not necessarily have to be present on decorated types.)

That doesn't cause any TCK failures, because decorators are not present in CDI Lite (plus I'm not sure this is actually tested by the TCK), and so far there hasn't been any issues filed about this, so this is purely of a theoretical concern (I only stumbled upon this by writing test cases for various corner cases). Still, it is a deviation from the specification, so I believe we should fix it. It's a lower priority kind of thing, though.

### Expected behavior

Only fail when an `abstract` method that doesn't belong to a decorated type is explicitly declared on a decorator or inherited (and not implemented!) from a supertype.

### Actual behavior

Fail whenever an `abstract` method is explicitly declared on a decorator; `abstract` methods declared on supertypes are ignored.

### How to Reproduce?

N/A

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Ladicek**
Per the CDI specification, an `abstract` decorator may not have `abstract` methods that are not declared on one of the decorated types (implemented interfaces). Until now, ArC didn't perform this validation properly; instead, it just checked whether the decorator class declared any `abstract` method.

With this commit, the validation is more precise. The implementation doesn't use the existing ArC facilities for dealing with parameterized types; instead, it contains a prototype of a Jandex "type system", which will hopefully one day be stabilized in Jandex itself.

Fixes #51196

### CODE REVIEW

**Comment by manovotn** [comment]
I've rerun the failed jobs as the failures were artifact resolutions:

> Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: The following artifacts could not be resolved: io.quarkus:quarkus-security:jar

**Comment by manovotn** [comment]
Oh, my bad, that test actually does a manual resolution of the dependency.
A rebase should fix this problem; it seems to have been resolved in https://github.com/quarkusio/quarkus/pull/51826

**Comment by Ladicek** [comment]
Rebased, thanks @manovotn for the investigations :-)

**Comment by geoand** [comment]
@mkouba @manovotn Are you good with this?

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/JandexTypeSystem.java [hunk 1]
```diff
@@ -0,0 +1,296 @@
...
+        } else {
+            return substituted;
+        }
+    }
+
+    private ClassInfo requireClass(Type type) {
+        return requireClass(type.name());
+    }
+
+    private ClassInfo requireClass(DotName name) {
```
Comment (manovotn) [inline independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/JandexTypeSystem.java:287]: I recall we had a util class that did Jandex class load with logging, take a look at `IndexClassLookupUtils#getClassByName`

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/JandexTypeSystem.java [hunk 2]
```diff
@@ -0,0 +1,296 @@
...
+     * of the supertype.
+     * <p>
+     * The result order is:
+     * <ol>
+     * <li>the given {@code type} (always)</li>
+     * <li>all superclass types in the bottom-up order (if the given {@code type} is a class type)</li>
+     * <li>superinterface types, in an unspecified order (if {@code skipInterfaces == false})</li>
+     * </ol>
+     */
+    List<Type> typeWithSuperTypes(Type type, boolean skipInterfaces) {
```
Comment (manovotn) [inline independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/JandexTypeSystem.java:53]: ATM the only use is always skipping interfaces, we could therefore remove the parameter and the relevant bit of code.

However if you intend to keep this as a template for the API ([as per your code comment](https://github.com/quarkusio/quarkus/pull/51893/changes#diff-89c0580a229553bea73c770a460babd648088803fc801e32a1c5a5188ea978feR27)), that's also fine. Just checking if it was intentional :)

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/JandexTypeSystem.java [hunk 3]
```diff
@@ -0,0 +1,296 @@
...
+import org.jboss.jandex.ClassType;
+import org.jboss.jandex.DotName;
+import org.jboss.jandex.IndexView;
+import org.jboss.jandex.MethodInfo;
+import org.jboss.jandex.ParameterizedType;
+import org.jboss.jandex.Type;
+import org.jboss.jandex.TypeVariable;
+import org.jboss.jandex.WildcardType;
+
+// this is a prototype; one day, it will become a public API in Jandex itself
```
Comment (mkouba) [inline independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/JandexTypeSystem.java]: Is there a Jandex issue to include a similar functionality?

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/JandexTypeSystem.java (hunk 1 above)
Comment (Ladicek) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/JandexTypeSystem.java:287]: I'm not interested in logging; it's always gonna be an exception if the class is missing. The entire type system API will require "complete" indices, which today practically always means on-demand indexing, unfortunately.

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/JandexTypeSystem.java (hunk 2 above)
Comment (Ladicek) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/JandexTypeSystem.java:53]: I actually wanted to change that parameter to an enum "only classes, only interfaces, all", but that would require bigger changes to the code, so I backed off for now. I'll probably change that to a `Predicate<ClassInfo>` or something when moving (which will probably require even bigger changes :-) ).

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/JandexTypeSystem.java (hunk 3 above)
Comment (Ladicek) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/JandexTypeSystem.java]: https://github.com/smallrye/jandex/issues/625

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/JandexTypeSystem.java (hunk 1 above)
Comment (manovotn) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/JandexTypeSystem.java:287]: Fair enough :+1:

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/JandexTypeSystem.java (hunk 3 above)
Comment (mkouba) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/JandexTypeSystem.java]: Cool, it would make sense to add a link to the javadoc then ;-).

Comment (manovotn) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/JandexTypeSystem.java]: +1, something along the lines of

> To be replaced by a dedicated Jandex API, see ....

Comment (Ladicek) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/JandexTypeSystem.java]: Will do.

**Review by manovotn — APPROVED** [review]

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/JandexTypeSystem.java (hunk 3 above)
Comment (Ladicek) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/JandexTypeSystem.java]: Done.

**Comment by Ladicek** [comment]
All test failures seem intermittent:

> Failed connecting to the daemon in 4 retries

> Failed to get latest Mandrel release for Java 21 from DISCO API: TypeError: Cannot read properties of undefined (reading 'links')

> ```
> 2026-01-19T14:11:43.4835449Z [ERROR] org.eclipse.microprofile.lra.tck.TckRecoveryTests.testCancelWhenParticipantIsRestarted -- Time elapsed: 4.358 s <<< ERROR!
> 2026-01-19T14:11:43.4843002Z java.lang.IllegalArgumentException: argument type mismatch
> 2026-01-19T14:11:43.4843747Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 2026-01-19T14:11:43.4844588Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> 2026-01-19T14:11:43.4845582Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 2026-01-19T14:11:43.4846596Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
> 2026-01-19T14:11:43.4847241Z 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
> 2026-01-19T14:11:43.4848101Z 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
> 2026-01-19T14:11:43.4848977Z 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
> 2026-01-19T14:11:43.4849779Z 	at org.jboss.arquillian.junit.Arquillian$8$1.invokeMethod(Arquillian.java:325)
> 2026-01-19T14:11:43.4850467Z 	at org.jboss.arquillian.junit.MethodInvoker$1.invoke(MethodInvoker.java:18)
> 2026-01-19T14:11:43.4851384Z 	at org.jboss.arquillian.container.test.impl.execution.LocalTestExecuter.execute(LocalTestExecuter.java:57)
> 2026-01-19T14:11:43.4852382Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 2026-01-19T14:11:43.4853292Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> 2026-01-19T14:11:43.4854473Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 2026-01-19T14:11:43.4855342Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
> 2026-01-19T14:11:43.4856431Z 	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
> 2026-01-19T14:11:43.4857316Z 	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
> 2026-01-19T14:11:43.4858263Z 	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:90)
> 2026-01-19T14:11:43.4859078Z 	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:133)
> 2026-01-19T14:11:43.4859800Z 	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:105)
> 2026-01-19T14:11:43.4860494Z 	at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:62)
> 2026-01-19T14:11:43.4861430Z 	at org.jboss.arquillian.container.test.impl.execution.ClientTestExecuter.execute(ClientTestExecuter.java:50)
> 2026-01-19T14:11:43.4862454Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 2026-01-19T14:11:43.4863352Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> 2026-01-19T14:11:43.4864566Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 2026-01-19T14:11:43.4865410Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
> 2026-01-19T14:11:43.4866254Z 	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
> 2026-01-19T14:11:43.4867172Z 	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
> 2026-01-19T14:11:43.4867980Z 	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:90)
> 2026-01-19T14:11:43.4869025Z 	at org.jboss.arquillian.container.test.impl.client.ContainerEventController.createContext(ContainerEventController.java:128)
> 2026-01-19T14:11:43.4870345Z 	at org.jboss.arquillian.container.test.impl.client.ContainerEventController.createTestContext(ContainerEventController.java:
> ```

Gonna try rerunning failed jobs.

**Comment by Ladicek** [comment]
OMG this is Sparta :laughing:

**Review by mkouba — APPROVED** [review]
