### PR TITLE
Panache Next – remove HR types from PanacheOperations generic signature

### LINKED ISSUE #52270: Panache Next: warnings when HR is not present
I'm getting these warnings on compiling a project without HR:

```
2026-01-29 15:19:30,071 WARN  [io.quarkus.arc.processor.BeanArchives] (build-7) Failed to index org.hibernate.reactive.mutiny.Mutiny$Session: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: DEV for panache2-test-1.0.0-SNAPSHOT@13b6aecc
2026-01-29 15:19:30,075 WARN  [io.quarkus.arc.processor.BeanArchives] (build-7) Failed to index org.hibernate.reactive.mutiny.Mutiny$StatelessSession: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: DEV for panache2-test-1.0.0-SNAPSHOT@13b6aecc
2026-01-29 15:19:30,096 WARN  [io.quarkus.deployment.steps.ReflectiveHierarchyStep] (build-7) Unable to properly register the hierarchy of the following classes for reflection as they are not in the Jandex index:
	- org.hibernate.reactive.mutiny.Mutiny$Session (source: ResteasyReactiveProcessor > org.acme.test.Endpoint[java.lang.String foo(org.acme.test.Review review)] > org.acme.test.Review > org.acme.test.Review > io.quarkus.hibernate.panache.managed.blocking.PanacheManagedBlockingEntity > io.quarkus.hibernate.panache.managed.PanacheManagedEntityOperations > io.quarkus.hibernate.panache.PanacheEntityMarker > io.quarkus.hibernate.panache.managed.reactive.PanacheManagedReactiveEntity > io.quarkus.hibernate.panache.runtime.spi.PanacheReactiveOperations > io.quarkus.hibernate.panache.runtime.spi.PanacheOperations > io.smallrye.mutiny.Uni > org.hibernate.reactive.mutiny.Mutiny$Session)
	- org.hibernate.reactive.mutiny.Mutiny$StatelessSession (source: ResteasyReactiveProcessor > org.acme.test.Endpoint[java.lang.String foo(org.acme.test.Review review)] > org.acme.test.Review > org.acme.test.Review > io.quarkus.hibernate.panache.managed.blocking.PanacheManagedBlockingEntity > io.quarkus.hibernate.panache.managed.PanacheManagedEntityOperations > io.quarkus.hibernate.panache.PanacheEntityMarker > io.quarkus.hibernate.panache.managed.reactive.PanacheManagedReactiveEntity > io.quarkus.hibernate.panache.runtime.spi.PanacheReactiveOperations > io.quarkus.hibernate.panache.runtime.spi.PanacheOperations > io.smallrye.mutiny.Uni > org.hibernate.reactive.mutiny.Mutiny$StatelessSession)
Consider adding them to the index either by creating a Jandex index for your dependency via the Maven plugin, an empty META-INF/beans.xml or quarkus.index-dependency properties.
```

These should not happen, since HR is optional.

### PR DESCRIPTION
**Pull request by basteez**
Fix #52270: Panache Next – remove HR types from PanacheOperations generic signature

Remove Session and StatelessSession as generic type parameters from
PanacheOperations, reducing the number of type parameters from 8 to 6.
This prevents spurious build-time WARN logs about Mutiny.Session and
Mutiny.StatelessSession when Hibernate Reactive is not on the classpath.

Root cause
PanacheReactiveOperations extended PanacheOperations using
Uni<Mutiny.Session> and Uni<Mutiny.StatelessSession> as type arguments.
This effectively embedded Hibernate Reactive types in the common SPI
generic signature.

Since PanacheEntityMarker (present on all entities) references
PanacheReactiveOperations transitively, Jandex and ReflectiveHierarchyStep
would always encounter these types, even in blocking-only projects.

Fix
Move getSession() and getStatelessSession() as concrete typed methods
into the specialized sub-interfaces:

- PanacheBlockingOperations: returns org.hibernate.Session and
  org.hibernate.StatelessSession
- PanacheReactiveOperations: returns Uni<Mutiny.Session> and
  Uni<Mutiny.StatelessSession>

The four implementation classes already exposed the correct concrete
return types and required no changes.

Tests
Add PanacheOperationsSpiTest with five reflection-based regression tests
to verify the SPI structure (e.g. no Mutiny types in PanacheOperations
generic parameters).

Fixes: #52270

### CODE REVIEW

**Comment by cescoffier** [comment]
🤖 Automatically associated with the **WG - Panache.Next** Working Group based on AI classification.

**Comment by gsmet** [comment]
I rebased it, please don't rebase with merge commits :).

@fromage this one is for you.

**Comment by FroMage** [comment]
Thanks for the fix, but when I tried it, I could not reproduce the issue, even without the fix. And your test does not check the logs for warnings.
How did you reproduce it?

**Comment by basteez** [comment]
> Thanks for the fix, but when I tried it, I could not reproduce the issue, even without the fix. And your test does not check the logs for warnings. How did you reproduce it?

@FroMage I made a repo to reproduce it, you can find it here https://github.com/basteez/quarkus-issue-52270-reprod

The problem appears only on native compilation

**Comment by basteez** [comment]
@FroMage just in case you missed my reply

**Comment by FroMage** [comment]
Yes, sorry, I did see it. I tried again, thanks for the pointer, I should have guessed from the logs, but I could also have written it in the original issue it would have saved us both time, sorry about that.

So, yeah, this fix removes the original logs, but produces these instead (well, not sure if it's instead or they were already there):

```
[WARNING] [io.quarkus.deployment.pkg.jar.ParallelCommonsCompressArchiveCreator] Duplicate entry 'io/quarkus/hibernate/panache/managed/blocking/PanacheManagedBlockingEntity.class': already added from 'Unknown source', ignoring entry from 'Current application'
[WARNING] [io.quarkus.deployment.pkg.jar.ParallelCommonsCompressArchiveCreator] Duplicate entry 'io/quarkus/hibernate/panache/stateless/blocking/PanacheStatelessBlockingEntity.class': already added from 'Unknown source', ignoring entry from 'Current application'
```

But now I have a bigger problem which is that the application does not compile:

```
Error: Class initialization of io.quarkus.hibernate.panache.runtime.hr.ManagedReactiveOperations failed. This error is reported at image build time because class io.quarkus.hibernate.panache.runtime.hr.ManagedReactiveOperations is registered for linking at image build time by command line and command line. Use the option 

    '--initialize-at-run-time=io.quarkus.hibernate.panache.runtime.hr.ManagedReactiveOperations'

 to explicitly request initialization of this class at run time.
Caused by: java.lang.NoClassDefFoundError: io/quarkus/hibernate/reactive/panache/common/runtime/AbstractManagedJpaOperations
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:962)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:144)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageClassLoader.defineClass(NativeImageClassLoader.java:490)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageClassLoader.findClassViaClassPath(NativeImageClassLoader.java:442)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageClassLoader.loadClass(NativeImageClassLoader.java:629)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:490)
	at io.quarkus.hibernate.panache.runtime.hr.ManagedReactiveOperations.<clinit>(ManagedReactiveOperations.java:21)
…
```

So there's more to it. Though perhaps we could merge this PR and open another issue for the remaining problem.

File: extensions/panache/hibernate-panache-next/runtime/src/test/java/io/quarkus/hibernate/panache/runtime/spi/PanacheOperationsSpiTest.java [hunk 1]
```diff
@@ -0,0 +1,110 @@
...
+        }
+        Assertions.assertNotNull(genericSuperinterface,
+                "PanacheReactiveOperations must extend PanacheOperations");
+
+        Type[] typeArgs = ((ParameterizedType) genericSuperinterface).getActualTypeArguments();
+        Assertions.assertEquals(6, typeArgs.length,
+                "PanacheReactiveOperations must pass exactly 6 type args to PanacheOperations");
+
+        for (Type typeArg : typeArgs) {
+            String typeStr = typeArg.getTypeName();
```
Comment (FroMage) [inline extensions/panache/hibernate-panache-next/runtime/src/test/java/io/quarkus/hibernate/panache/runtime/spi/PanacheOperationsSpiTest.java]: I'm not sure this tests things properly. Here the `typeArg` will be `Uni<Mutiny.Session>`, so I think even in the previous case (before this PR), `typeArg.getTypeName()` would return `Uni` and not include `Mutiny`, it should perhaps look for it recursively, or cheat and look for it in `typeArg.toString()`.

**Review by FroMage — CHANGES_REQUESTED** [review]
Honestly I think we should drop this test entirely, we usually don't check for type hierarchies in our code, because it's static.

This will be tested when we have a Panache Next integration test that we will compile natively. Or two: one with HR and one without.

File: extensions/panache/hibernate-panache-next/runtime/src/test/java/io/quarkus/hibernate/panache/runtime/spi/PanacheOperationsSpiTest.java (hunk 1 above)
Comment (basteez) [reply extensions/panache/hibernate-panache-next/runtime/src/test/java/io/quarkus/hibernate/panache/runtime/spi/PanacheOperationsSpiTest.java]: Test removed as requested

**Comment by FroMage** [comment]
Could you merge your commits please?

**Comment by basteez** [comment]
@FroMage  done, squashed my commits

**Review by FroMage — APPROVED** [review]

**Comment by FroMage** [comment]
Thanks.
