### PR TITLE
Fix CDI request context activation race when Quarkus REST and Reactive Routes are used during the same request

### LINKED ISSUE #51230: ContextNotActiveException in the middle of a request handler
### Describe the bug

We are seeing random errors caused by `ContextNotActiveException` when we are in fact in the middle of a request handler. It's not reliably reproducible but happens a lot. Here is a stack trace from one of the occurences (`CID` is a request-scoped bean, `DeploymentImpl.createJob` is a `@POST` method):
```
2025-11-25 14:09:21.044 ERROR [com.knime.enterprise.cloud.services.rest.providers.exception.GenericExceptionMapper] [||] [b828df26-8d35-486b-a3a7-b6b1f24ddd88|b828df26-8d35-486b-a3a7-b6b1f24ddd88|be0db219-6ddf-4db7-b216-cbb6fed5fdb4] (executor-thread-11) (Error ID: 'error_0fdcdddc-b4a1-4310-a2fa-ebde474ac41e') An internal error occurred.: jakarta.enterprise.context.ContextNotActiveException: RequestScoped context was not active when trying to obtain a bean instance for a client proxy of CLASS bean [class=com.knime.enterprise.cloud.services.rest.providers.CID, id=MW9NdRFz_a7BApr8HmNChEk0gwg]
	- you can activate the request context for a specific method using the @ActivateRequestContext interceptor binding
	at io.quarkus.arc.impl.ClientProxies.notActive(ClientProxies.java:76)
	at io.quarkus.arc.impl.ClientProxies.getSingleContextDelegate(ClientProxies.java:32)
	at com.knime.enterprise.cloud.services.rest.providers.CID_ClientProxy.arc$delegate(Unknown Source)
	at com.knime.enterprise.cloud.services.rest.providers.CID_ClientProxy.getCorrelationId(Unknown Source)
	at com.knime.enterprise.cloud.services.execution.rest.impl.AbstractJobService.loadWorkflow(AbstractJobService.java:642)
	at com.knime.enterprise.cloud.services.execution.rest.impl.AbstractJobService.createAndConfigureDeploymentJob(AbstractJobService.java:531)
	at com.knime.enterprise.cloud.services.execution.rest.impl.v4.DeploymentImpl_Subclass.createAndConfigureDeploymentJob$$superforward(Unknown Source)
	at com.knime.enterprise.cloud.services.execution.rest.impl.v4.DeploymentImpl_Subclass$$function$$8.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext$NextAroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:97)
	at io.quarkus.security.runtime.interceptor.SecurityHandler.handle(SecurityHandler.java:47)
	at io.quarkus.security.runtime.interceptor.AuthenticatedInterceptor.intercept(AuthenticatedInterceptor.java:29)
	at io.quarkus.security.runtime.interceptor.AuthenticatedInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:70)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
	at io.quarkus.resteasy.reactive.server.runtime.StandardSecurityCheckInterceptor.intercept(StandardSecurityCheckInterceptor.java:44)
	at io.quarkus.resteasy.reactive.server.runtime.StandardSecurityCheckInterceptor_AuthenticatedInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
	at com.knime.enterprise.cloud.services.execution.rest.impl.v4.DeploymentImpl_Subclass.createAndConfigureDeploymentJob(Unknown Source)
	at com.knime.enterprise.cloud.services.execution.rest.impl.v4.DeploymentImpl.createJob(DeploymentImpl.java:904)
	at com.knime.enterprise.cloud.services.execution.rest.impl.v4.DeploymentImpl_Subclass.createJob$$superforward(Unknown Source)
	at com.knime.enterprise.cloud.services.execution.rest.impl.v4.DeploymentImpl_Subclass$$function$$25.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext$NextAroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:97)
	at io.quarkus.security.runtime.interceptor.SecurityHandler.handle(SecurityHandler.java:27)
	at io.quarkus.security.runtime.interceptor.AuthenticatedInterceptor.intercept(AuthenticatedInterceptor.java:29)
	at io.quarkus.security.runtime.interceptor.AuthenticatedInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:70)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
	at io.quarkus.resteasy.reactive.server.runtime.StandardSecurityCheckInterceptor.intercept(StandardSecurityCheckInterceptor.java:44)
	at io.quarkus.resteasy.reactive.server.runtime.StandardSecurityCheckInterceptor_AuthenticatedInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
	at com.knime.enterprise.cloud.services.execution.rest.impl.v4.DeploymentImpl_Subclass.createJob(Unknown Source)
	at com.knime.enterprise.cloud.services.execution.rest.impl.v4.DeploymentImpl$quarkusrestinvoker$createJob_4ec944c18a78659ccbef61c98ed14edfebdd77f5.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$15.runWith(VertxCoreRecorder.java:638)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)
	at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
```
This code path is run many times but only sometimes fails.
Subsequently try to access other request-scoped beans in an `ExceptionMapper` (Jakarta RS `HttpHeaders`) fails with a similar exception:
```
2025-11-25 14:09:21.045 ERROR [io.quarkus.vertx.http.runtime.QuarkusErrorHandler] [||] [b828df26-8d35-486b-a3a7-b6b1f24ddd88|b828df26-8d35-486b-a3a7-b6b1f24ddd88|be0db219-6ddf-4db7-b216-cbb6fed5fdb4] (executor-thread-11) HTTP Request to /deployments/data-app:fc77d0b1-0977-499a-ae3c-609e8d53ef5e/jobs?asyncLoading=true&wizardExecution=false failed, error id: 4de58767-d1e9-480b-a92b-5540246177c1-5: jakarta.enterprise.context.ContextNotActiveException: RequestScoped context was not active when trying to obtain a bean instance for a client proxy of PRODUCER_METHOD bean [class=org.jboss.resteasy.reactive.server.injection.ContextProducers, id=aqrlVKLOXX76sGCBcY1BgxfDVfU]
	- you can activate the request context for a specific method using the @ActivateRequestContext interceptor binding
	at io.quarkus.arc.impl.ClientProxies.notActive(ClientProxies.java:76)
	at io.quarkus.arc.impl.ClientProxies.getSingleContextDelegate(ClientProxies.java:32)
	at jakarta.ws.rs.core.ContextProducers_ProducerMethod_headers_VA74pGGn-tu4h7_tlI2NceCHbzU_ClientProxy.arc$delegate(Unknown Source)
	at jakarta.ws.rs.core.ContextProducers_ProducerMethod_headers_VA74pGGn-tu4h7_tlI2NceCHbzU_ClientProxy.getRequestHeader(Unknown Source)
	at com.knime.enterprise.cloud.services.rest.providers.exception.AbstractRFC9457ExceptionMapper.requestAcceptsProblemJson(AbstractRFC9457ExceptionMapper.java:191)
	at com.knime.enterprise.cloud.services.rest.providers.exception.AbstractRFC9457ExceptionMapper.toResponse(AbstractRFC9457ExceptionMapper.java:163)
	at org.jboss.resteasy.reactive.server.core.RuntimeExceptionMapper.mapException(RuntimeExceptionMapper.java:96)
	at org.jboss.resteasy.reactive.server.core.ResteasyReactiveRequestContext.mapExceptionIfPresent(ResteasyReactiveRequestContext.java:361)
	at org.jboss.resteasy.reactive.server.handlers.ExceptionHandler.handle(ExceptionHandler.java:15)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:150)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
```

We cannot clearly tell but we believe this has started when we switched from quarkus-reasteasy to quarkus-rest a few weeks ago.

### Expected behavior

No error about missing request context when we are clearly in the middle of a request.

### Actual behavior

See description

### How to Reproduce?

Not reliably reproducible yet.

### Output of `uname -a` or `ver`

Linux rest-interface-69b4559566-ktmqc 6.8.0-1039-aws #41~22.04.1-Ubuntu SMP Thu Sep 11 10:54:48 UTC 2025 x86_64 GNU/Linux

### Output of `java -version`

21.0.9+10-LTS

### Quarkus version or git rev

3.20.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.11

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by michalvavrik**
- closes https://github.com/quarkusio/quarkus/issues/51230

### CODE REVIEW

**Comment by michalvavrik** [comment]
@geoand I have run the reproducer and the test I added couple of times and this fixes the issue. I tried to run few related modules like RR and Quarkus REST and didn't see anything failing. Let's see what CI does. @mkouba may also be interested.

**Comment by geoand** [comment]
Cool!

I'll have a look soon

**Review by geoand — APPROVED** [review]
Thanks a lot!

File: extensions/reactive-routes/runtime/src/main/java/io/quarkus/vertx/web/runtime/RouteHandler.java [hunk 1]
```diff
@@ -90,14 +92,18 @@ public void handle(RoutingContext context) {
...
+                                requestContext.destroy(endState);
+                            }
                         }
                     });
                 }
                 invoke(context);
             } finally {
-                // Deactivate the context, i.e. cleanup the thread locals
-                requestContext.deactivate();
+                if (RoutingUtils.isCdiRequestContextOwner(context, REACTIVE_ROUTES_KEY)) {
```
Comment (mkouba) [inline extensions/reactive-routes/runtime/src/main/java/io/quarkus/vertx/web/runtime/RouteHandler.java:103]: Isn't this check unnecessary? I mean, at this point the owner must be `quarkus-reactive-routes` (unless something replaced the CURRENT_CDI_REQUEST_CTX_OWNER)...

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/RoutingUtils.java [hunk 2]
```diff
@@ -10,10 +11,35 @@
...
 
+    /**
+     * Assumes ownership of the currently active CDI request context.
+     * Thus, code invoked (even asynchronously) from previous route handlers shouldn't deactivate it.
+     *
+     * @param ctx RoutingContext
+     * @param owner typically a route handler that needs CDI request context active
+     */
+    public static void assumeCdiRequestContext(RoutingContext ctx, String owner) {
+        ctx.put(CURRENT_CDI_REQUEST_CTX_OWNER, Objects.requireNonNull(owner));
```
Comment (mkouba) [inline extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/RoutingUtils.java]: Shouldn't we throw an exception if the owner is already set?

File: extensions/reactive-routes/runtime/src/main/java/io/quarkus/vertx/web/runtime/RouteHandler.java (hunk 1 above)
Comment (michalvavrik) [reply extensions/reactive-routes/runtime/src/main/java/io/quarkus/vertx/web/runtime/RouteHandler.java:103]: > Isn't this check unnecessary? I mean, at this point the owner must be `quarkus-reactive-routes` (unless something replaced the CURRENT_CDI_REQUEST_CTX_OWNER)...

That is not how I read the situation. When `routingContext.next()` happens, other route handlers are called synchronously until some code is scheduled (like run blocking), at which point this can be invoked. So it can easily be Quarkus REST.

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/RoutingUtils.java (hunk 2 above)
Comment (michalvavrik) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/RoutingUtils.java]: > Shouldn't we throw an exception if the owner is already set?

The idea is to recognize which route handler is handling request if and only if it is reusing the CDI request context. So what happens right now, for example also due to this PR https://github.com/quarkusio/quarkus/pull/40408 is that we are reusing already active CDI request context (I think Martin solved some issue that way).

File: extensions/reactive-routes/runtime/src/main/java/io/quarkus/vertx/web/runtime/RouteHandler.java (hunk 1 above)
Comment (michalvavrik) [reply extensions/reactive-routes/runtime/src/main/java/io/quarkus/vertx/web/runtime/RouteHandler.java:103]: Sorry, I meant "synchronously".

Comment (mkouba) [reply extensions/reactive-routes/runtime/src/main/java/io/quarkus/vertx/web/runtime/RouteHandler.java:103]: > > Isn't this check unnecessary? I mean, at this point the owner must be `quarkus-reactive-routes` (unless something replaced the CURRENT_CDI_REQUEST_CTX_OWNER)...
> 
> That is not how I read the situation. When `routingContext.next()` happens, other route handlers are called synchronously until some code is scheduled (like run blocking), at which point this can be invoked. So it can easily be Quarkus REST.

Yes, but all those handlers share the same `RoutingContext`...

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/RoutingUtils.java (hunk 2 above)
Comment (mkouba) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/RoutingUtils.java]: I'm sorry but I don't undertand how it's supposed to work.

**Comment by mkouba** [comment]
CC @manovotn

File: extensions/reactive-routes/runtime/src/main/java/io/quarkus/vertx/web/runtime/RouteHandler.java (hunk 1 above)
Comment (michalvavrik) [reply extensions/reactive-routes/runtime/src/main/java/io/quarkus/vertx/web/runtime/RouteHandler.java:103]: The point is that `finally` is run when Quarkus REST is processing because `routingContext.next()` is run before.

> Yes, but all those handlers share the same RoutingContext...

I don't know how to answer that :-) You will need to elaborate.

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/RoutingUtils.java (hunk 2 above)
Comment (michalvavrik) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/RoutingUtils.java]: Well, at this point I'll only repeat myself. I am happy to explain it differently, but I don't know what part you don't understand.  `assumeCdiRequestContext` method is called by Quarkus REST before Reactive Routes tries to destroy our state in the `endHandler`. Whether `finally` itself runs depends on what next route handlers do.

> I'm sorry but I don't undertand how it's supposed to work.

I have added tests. Maybe you can run them and see what they solve?

File: extensions/reactive-routes/runtime/src/main/java/io/quarkus/vertx/web/runtime/RouteHandler.java (hunk 1 above)
Comment (mkouba) [reply extensions/reactive-routes/runtime/src/main/java/io/quarkus/vertx/web/runtime/RouteHandler.java:103]: > The point is that `finally` is run when Quarkus REST is processing because `routingContext.next()` is run before.

Ok, so we don't want to deactivate the context either. Small note - if Vertx is used then `requestContext.deactivate()` is a NOOP if duplicated context is used: https://github.com/quarkusio/quarkus/blob/main/extensions/vertx/runtime/src/main/java/io/quarkus/vertx/runtime/VertxCurrentContextFactory.java#L99

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/RoutingUtils.java (hunk 2 above)
Comment (mkouba) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/RoutingUtils.java]: > `assumeCdiRequestContext` method is called by Quarkus REST before Reactive Routes tries to destroy our state in the `endHandler`

So Quarkus REST can intentionally replace the original owner (Reactive Routes)? If that's expected then it might make sense to add some debug logging in ` assumeCdiRequestContext()`..

File: extensions/reactive-routes/runtime/src/main/java/io/quarkus/vertx/web/runtime/RouteHandler.java (hunk 1 above)
Comment (michalvavrik) [reply extensions/reactive-routes/runtime/src/main/java/io/quarkus/vertx/web/runtime/RouteHandler.java:103]: > > The point is that `finally` is run when Quarkus REST is processing because `routingContext.next()` is run before.
> 
> Ok, so we don't want to deactivate the context either. Small note - if Vertx is used then `requestContext.deactivate()` is a NOOP if duplicated context is used: https://github.com/quarkusio/quarkus/blob/main/extensions/vertx/runtime/src/main/java/io/quarkus/vertx/runtime/VertxCurrentContextFactory.java#L99

I didn't know, thanks. I thought that the bug is about the `endHandler` where is `destroy` invoked, but during the debugging I saw my breakpoint on `deactivate` called after Quarkus REST started doing stuff, so I'd keep it here just in case you change how `deactivate` works in the future.

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/RoutingUtils.java (hunk 2 above)
Comment (michalvavrik) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/RoutingUtils.java]: > > `assumeCdiRequestContext` method is called by Quarkus REST before Reactive Routes tries to destroy our state in the `endHandler`
> 
> So Quarkus REST can intentionally replace the original owner (Reactive Routes)?

Exactly. The way it works (sorry if I am repeating myself):

1. Reactive Routes activate CDI request context for the callback with user code (e.g. `@RouteFilter`)
2. user code calls `routingContext.next()`
3. some other handlers run depending on the order until Quarkus REST handler runs, it detects active CDI request context and reuses it
4. next depends on what is done:
  - the `finally` block in the Reactive Routes may run in some scenarios like when blocking code is scheduled and so on; but you already explained it is NOOP, funny I saw context not active in stacktrace for CDI interceptors where it failed; anyway, this fixed it
  - the `endHandler` may run before all code in Quarkus REST is finished, as shown by the user reproducer with socket timeout on the client side; we need Quarkus REST to take responsibility on when it is destroys CDI context state

> If that's expected then it might make sense to add some debug logging in ` assumeCdiRequestContext()`..

I'll add it, so that we can keep track of it. Thanks.

Comment (michalvavrik) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/RoutingUtils.java]: I have added a debug logging to track the ownership.

**Comment by michalvavrik** [comment]
I don't think that failures are related, I only added a debug log message and CIs fail over OOM in unmodified modules.

**Comment by geoand** [comment]
Very odd indeed... I restarted those jobs - let's see what happens

**Comment by Ladicek** [comment]
I don't have the full context and I think I never really looked into how the CDI request context is activated/deactivated during HTTP request processing, but I would hope that we have exactly 1 Vert.x Web router handler with suitably low priority that would activate/deactivate the CDI request context and all other frameworks built on top of that would just _not touch the CDI request context at all costs_. I'm sure there's a reason for why it's done the way it's done, but is there a reason for why it's not done the way I described?

**Comment by michalvavrik** [comment]
> I don't have the full context and I think I never really looked into how the CDI request context is activated/deactivated during HTTP request processing, but I would hope that we have exactly 1 Vert.x Web router handler with suitably low priority that would activate/deactivate the CDI request context and all other frameworks built on top of that would just _not touch the CDI request context at all costs_.

CDI request context is only activated when needed. There is no such a handler ATM.

> I'm sure there's a reason for why it's done the way it's done, but is there a reason for why it's not done the way I described?

I think that is a question for each stack owner. I remember few arguments mentioned in the past (like you may never need CDI request context, or that you may need your own like WS Next OnMessage callbacks), but I don't want to advocate either.

Unless we make general change as you describe, this PR is pretty uninvasive, it only does something if Reactive Routes activated CDI request context, so for 99 % use cases, it should be NOOP.

**Comment by michalvavrik** [comment]
@geoand that CI error is strange and I don't think it is related, but I'll rebase on the current main.

**Comment by mkouba** [comment]
> > I don't have the full context and I think I never really looked into how the CDI request context is activated/deactivated during HTTP request processing, but I would hope that we have exactly 1 Vert.x Web router handler with suitably low priority that would activate/deactivate the CDI request context and all other frameworks built on top of that would just _not touch the CDI request context at all costs_.
> 
> CDI request context is only activated when needed. There is no such a handler ATM.
> 
> > I'm sure there's a reason for why it's done the way it's done, but is there a reason for why it's not done the way I described?
> 
> I think that is a question for each stack owner. I remember few arguments mentioned in the past (like you may never need CDI request context, or that you may need your own like WS Next OnMessage callbacks), but I don't want to advocate either.

I believe that there are cases where you don't want to activate the CDI request context (think about static resources or high performance endpoints). But I also think that the main reason is historical development. There were times when Vertx duplicated context was not a thing and threadlocals were used instead, stacks used different thread pool strategies, etc. It was easier to manage the activation separately. Also keep in mind that it's not a common use case to combine the stacks :shrug:.

**Comment by geoand** [comment]
> Also keep in mind that it's not a common use case to combine the stacks 

Sure, but it doesn't mean we can't make it work, at the end of day, all the HTTP stuff is backed by Vert.x (and one of the reasons was to be able to mix such kinds of things)

**Comment by mkouba** [comment]
> > Also keep in mind that it's not a common use case to combine the stacks
> 
> Sure, but it doesn't mean we can't make it work, at the end of day, all the HTTP stuff is backed by Vert.x (and one of the reasons was to be able to mix such kinds of things)

I'm not saying we can't... I was talking about why we don't have a common activation handler.

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/RoutingUtils.java [hunk 3]
```diff
@@ -10,10 +13,39 @@
...
     }
 
+    /**
+     * Assumes ownership of the currently active CDI request context.
+     * Thus, code invoked (even asynchronously) from previous route handlers shouldn't deactivate it.
+     *
+     * @param ctx RoutingContext
+     * @param newOwner typically a route handler that needs CDI request context active
+     */
+    public static void assumeCdiRequestContext(RoutingContext ctx, String newOwner) {
```
Comment (manovotn) [inline extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/RoutingUtils.java:30]: @michalvavrik is there any guarantee that the last handler to claim the context as their own is always going to be the last to actually attempt to use it?

I am not familiar enough with the code to be able to tell so maybe I am missing something obvious.
However, my thinking was that I would capture a collection of all handlers when they attempt to activate it. Later on, when a handler attempts to deactivate context, remove the handler from the collection and only the last to be removed actually performs the cleanup.
Then again, I am probably just missing something, so take it with a pinch of salt please :)

**Comment by manovotn** [comment]
> CC @manovotn

I do not know how exactly do routing handlers juggle with CDI contexts but what Michal proposes here seems sensible to me particularly because of his earlier comment:

> the `endHandler` may run before all code in Quarkus REST is finished, as shown by the user reproducer with socket timeout on the client side; we need Quarkus REST to take responsibility on when it is destroys CDI context state

The only thing I added as a comment is related my limited knowledge of whether this solution is "generic enough".

> I don't have the full context and I think I never really looked into how the CDI request context is activated/deactivated during HTTP request processing, but I would hope that we have exactly 1 Vert.x Web router handler with suitably low priority that would activate/deactivate the CDI request context and all other frameworks built on top of that would just not touch the CDI request context at all costs. I'm sure there's a reason for why it's done the way it's done, but is there a reason for why it's not done the way I described?

This gives me a bit of a déjà vu feeling, I think we discussed this at some point although I only recall there were some cases where that would be undesirable :shrug: 
That was a long time ago and much has changed since though (such as using Vert.x duplicated context for CP).

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/RoutingUtils.java (hunk 3 above)
Comment (michalvavrik) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/RoutingUtils.java:30]: > @michalvavrik is there any guarantee that the last handler to claim the context as their own is always going to be the last to actually attempt to use it?

It is for the scenario I am trying to solve, but if we treat this method  as SPI that theoretically anyone could reuse, then probably no. IMO there should be always only one route handler actively handling the incoming request, because if there were multiple handlers using the same request, we would be in for whole lot of issues like this one https://github.com/quarkusio/quarkus/issues/49468.

So what I meant to solve is:

- avoid code executed after user callback runs `routingContext.next()`, such as
  - the `finally` block running `requestContext.deactivate()`
  - the `endHandler` code destroying CDI context state

And if in the future (or in `quarkiverse`) someone does things like these, we cannot guarantee we will be the last ones.

> However, my thinking was that I would capture a collection of all handlers when they attempt to activate it. Later on, when a handler attempts to deactivate context, remove the handler from the collection and only the last to be removed actually performs the cleanup.

I think that would be a solution covering all eventualities, but the only way to keep it safe (be sure it is cleaned) would be synchronization (or other locking) which could have performance impact if it was hot path? I think there is a reason why `RoutingContext` data are not kept in the synchronized map and not in volatile field, and that is that we don't expect things to happen concurrently. But I can be wrong, not an expert on this matter.

IMO current code in Quarkus REST doesn't expect that someone else is handling active CDI request context and I have seen the same thing in gRPC. I'd keep it simple (as is, or just rename method / adjust javadoc if you have some suggestion) @manovotn , but I can do what you want if you deem it important.

**Comment by michalvavrik** [comment]
@geoand CI failures in https://github.com/quarkusio/quarkus/pull/51314 looks same as the failures we saw in this one.

**Comment by geoand** [comment]
Agreed,  I'll have a closer look tomorrow

**Comment by geoand** [comment]
The OpenAPI failure is something that has been happening on CI the last few days, it has nothing to do with this PR

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/RoutingUtils.java (hunk 3 above)
Comment (Ladicek) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/RoutingUtils.java:30]: First off, I don't think this should be just a local discussion, all relevant people need to be involved.

I think we've established that there may be multiple users (as in, Quarkus components) that want to access the same request context. We've also established that we want the request context created on demand, not eagerly. (Thanks for those remarks! It also feels like déjà vu to me. And I'm sure it will happen again.)

I'm gonna claim a simple `int` (or `AtomicInteger`) stored on a shared location (the Vert.x context probably? What about non-Vert.x threads though?) would be enough. If someone wants to create the request context, two things may happen.

1. If they don't see the `int` on the shared location, they are the first to activate the request context. They do so and set the value to `1`.
2. If they do see the `int` on the shared location, the request context already exist and they just increment the value.

Conversely, if someone wants to destroy the request context, two (or three, depending how thorough we are) things may happen:

1. They see the `int` on the shared location, they decrement the value and the result is `> 0`. They don't do anything more.
2. They see the `int` on the shared location, they decrement the value and the result is `0`. They destroy the request context.
3. They don't see the `int` on the shared location. The request context wasn't activated, so there's no point in destroying it.

I think the above should be enough to ensure that the request context can be activated on-demand and destroyed only after all possible users are done with it.

I think either this could be put into a utility class, probably in ArC, or perhaps this could be done in the ArC implementation of request context itself?

Comment (mkouba) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/RoutingUtils.java:30]: > 1. They see the `int` on the shared location, they decrement the value and the result is `> 0`. They don't do anything more.

AFAIU this would not help with the use case @michalvavrik is trying to fix. This sentence from https://github.com/quarkusio/quarkus/pull/51299#discussion_r2582251160 is important: _"IMO current code in Quarkus REST doesn't expect that someone else is handling active CDI request context and I have seen the same thing in gRPC"_

Comment (Ladicek) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/RoutingUtils.java:30]: > AFAIU this would not help with the use case @michalvavrik is trying to fix. This sentence from [#51299 (comment)](https://github.com/quarkusio/quarkus/pull/51299#discussion_r2582251160) is important: _"IMO current code in Quarkus REST doesn't expect that someone else is handling active CDI request context and I have seen the same thing in gRPC"_

Yeah, but that assumption is wrong, otherwise the issue and this PR wouldn't exist. We clearly have multiple components assuming they own the request context, which is _wrong_.

Comment (Ladicek) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/RoutingUtils.java:30]: Alternatively, we could just forbid multiple components sharing the request context. This should be relatively straightforward to detect, but super unfriendly, so I didn't even consider it originally.

Comment (manovotn) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/RoutingUtils.java:30]: > I think that would be a solution covering all eventualities, but the only way to keep it safe (be sure it is cleaned) would be synchronization (or other locking) which could have performance impact if it was hot path? I think there is a reason why RoutingContext data are not kept in the synchronized map and not in volatile field, and that is that we don't expect things to happen concurrently. But I can be wrong, not an expert on this matter.

I don't think the impact would be that huge but I am not sure it would solve all the problems either :thinking: 
Namely the fact that in some places we don't want to *destroy* but context but merely *deactivate* it and for that such simple tracker might not be enough.

> IMO current code in Quarkus REST doesn't expect that someone else is handling active CDI request context and I have seen the same thing in gRPC. I'd keep it simple (as is, or just rename method / adjust javadoc if you have some suggestion) @manovotn , but I can do what you want if you deem it important.

No, I just wanted to get some clarity about how and why this works.
Personally, I am fine with this change and its local scope.

I also agree with @Ladicek that we'd ideally have some synchronization approach but that's IMO out of scope of this PR. We can create a tracking issue but I am not sure who's going to voluntarily open that can of worms :)

Comment (Ladicek) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/RoutingUtils.java:30]: > Personally, I am fine with this change and its local scope.

I know I'm not the one to decide here, but I'm personally not. This PR is a result of great investigation, but the solution presented is a band-aid applied on a wrong abstraction level.

If we actually want to support multiple "owners" of the same request context, I think something like I describe above is what we should do, and the more I think about it, the more I'm convinced the request context implementation itself should do it. (This is obviously performance sensitive...)

Now, there's a difference between deactivation and destruction and I didn't think through this distinction, so there would be more work to do. Still, it feels better to do it properly once, rather than doing it improperly (at least once, but possibly multiple times) and then having to do it properly and undoing the hacks.

Comment (michalvavrik) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/RoutingUtils.java:30]: Frankly, ATM I don't even have time to carefully read all your comments, but I got a gist that @Ladicek have in mind solid solution and @manovotn agree in principle.

I'd be fine to close this PR if you will handle the linked issue @Ladicek ? You can reuse that test, I wrote a lot of comments about re-running it, but it actually reproduced the issue pretty well from my workstation. I just don't know how stable reproducing will be from your laptop.

Anyway, if noone else handles the issue, I can go back to it by the end of this week, read all  your comments and try to come up with something.

Comment (Ladicek) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/RoutingUtils.java:30]: I just talked to @mkouba and @manovotn and we concluded that concurrency in Quarkus is pretty much a mess (in how `DuplicatedContext` is passed around and duplicated/triplicated/whatever, in how SmallRye Context Propagation works/is integrated, in how Vert.x and non-Vert.x thread are different). I certainly don't aim to fix _that_.

We also briefly discussed the difference between context deactivation and destruction and concluded that deactivation itself shouldn't "unregister" the owner, only destruction should. We didn't discuss what should constitute the "registration" of the request context owner, but it seems logical to me that it's the call to `activate()` with no initial state (that is, zero-param `activate()` or one-param `activate()` with `null` argument).

Looking at the implementation of `CurrentManagedContext`, it seems relatively straightforward to support multiple owners. It should only affect these places:

- method `ContextState activate(ContextState initialState)`
- method `void destroy(ContextState state)`
- member class `CurrentContextState` (we need to track the number of current owners, but that should always be small, so it should fit into the `state` field -- it seems safe to me to assume that there will never be more than 32 owners, in fact I think we can assume there will never more than 16 owners to leave 1 bit reserved for future use)

I'll try to figure something out.

In the meantime, I'm certainly not blocking the merge of this PR, because both @mkouba and @manovotn are fine with it.

Comment (michalvavrik) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/RoutingUtils.java:30]: Thanks for all your comments and expertise everyone.

Comment (Ladicek) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/RoutingUtils.java:30]: > We didn't discuss what should constitute the "registration" of the request context owner, but it seems logical to me that it's the call to `activate()` with no initial state (that is, zero-param `activate()` or one-param `activate()` with `null` argument).

OK, so _that_ is clearly wrong. (I knew there was a hurdle!) Activating a request context with no initial state is _creating a new request context_. That only happens once. Registration of an additional owner may only happen when activating with _non-`null`_ initial state, and at that point, there's no way to know if that means a _newly registered_ owner, or an _already registered_ owner. So my nice and simple idea makes no sense :-)

**Comment by michalvavrik** [comment]
I think this PR is backportable while if I think most of the suggestions, if implemented, should only stay in the main. Considering 3.27 will be around for 5 years, I think this (in some form) should be initial fix and improvements can come later.

**Comment by geoand** [comment]
Unless anyone objects, I will merge this soon

**Comment by Ladicek** [comment]
Even after the 2 or 3 days I spent looking into this, I don't have a satisfactory solution, so I'm retracting any possible objections I might have raised before :-)

I experimented with a single-owner policy and multiple-owners policy, but my implementations are not suitable to implementing what this PR does, which is essentially a handover of the CDI request context ownership from Reactive Routes to RESTEasy Reactive. In order for them to _be_ suitable, I would have to:

- either introduce the notion of an _identity_ of an owner, which would entail:
    - either more overhead in a performance sensitive piece of code,
    - or at least shared constants (whose number would be severely limited),
- or implement a single-purpose solution, which would hardly be any better than this PR and would pollute the API.

Too bad :-/

**Comment by geoand** [comment]
That's great information to have for posterity

**Comment by FroMage** [comment]
If I had a euro for every time we had a context issue…

**Comment by edeweerd1A** [comment]
Would it be possible to ask for a backport in the 3.27 LTS?

**Comment by geoand** [comment]
I believe we can, as this has seen significant bake time

**Comment by michalvavrik** [comment]
@geoand I think you chose wrong backport label.

**Comment by geoand** [comment]
Oops, thanks for catching that!
