### PR TITLE
Take max-chunk-size config into account for programmatic client

### LINKED ISSUE #37786: MaxChunkSize not taken into account for Quarkus Reasteasy Reactive client
### Describe the bug

According to the documentation, setting the following should change the chunk size for the client.

    quarkus.resteasy-reactive.output-buffer-size=65536
    quarkus.resteasy-reactive.input-buffer-size=65536
    quarkus.http.limits.max-chunk-size=65536

Howver, during my tests, using a Netty server to trace and then going in debug mode, the reactive client uses 8KB chunk size, whatever the configuration. Following the code, I think I discover that the current client is taking its configuration from (defined in QuarkusRestClientProperties):

    "io.quarkus.rest.client.max-chunk-size"

Which is possibly (not sure)  associated with non reactive clients (not validated by Quarkus if not getting non reactive clients into the pom):

    quarkus.rest-client.multipart.max-chunk-size

I didn't find a way to define this value in the properties file.

It seems, according to my search, that the following are intend for Server side mainly.

    quarkus.resteasy-reactive.output-buffer-size=65536
    quarkus.resteasy-reactive.input-buffer-size=65536
    quarkus.http.limits.max-chunk-size=65536

I found a way to set this value by using the programmatic builder as the following:

    QuarkusRestClientBuilder.newBuilder().baseUri(uri)
        .property("io.quarkus.rest.client.max-chunk-size",65536).build(apiClass);

I believe something is missing in the configuration that should take at least the `quarkus.http.limits.max-chunk-size` to set this value `io.quarkus.rest.client.max-chunk-size` for the resteasy reactive client.

Side not : it seems the reactive server side is honoring those configuration, even if for an unknown reason it is not possible to go further than 64 KB (even if I set 128KB, the chunk size remains at 64 KB). But the main issue there is on reactive client side.

### Expected behavior

When setting `quarkus.http.limits.max-chunk-size`, the corresponding  value `io.quarkus.rest.client.max-chunk-size` for the resteasy reactive client (or other ways to do it) should be set such that Resteasy reactive client uses the correct chunk size instead of default 8K.

### Actual behavior

Ignore all settings, except in programmatic building way by passing the internal property `io.quarkus.rest.client.max-chunk-size`.

### How to Reproduce?

A simple client sending an array of bytes greater than 64KB to a server in reactive resteasy mode with configuration as described in the documentation will ignore the chunk size (while server in response seems to honore it).

### Output of `uname -a` or `ver`

6.5.0-14-generic #14-Ubuntu SMP PREEMPT_DYNAMIC Tue Nov 14 14:59:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "21.0.1" 2023-10-17 LTS OpenJDK Runtime Environment Temurin-21.0.1+12 (build 21.0.1+12-LTS) OpenJDK 64-Bit Server VM Temurin-21.0.1+12 (build 21.0.1+12-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.6.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.7 Maven home: /usr/share/maven Java version: 21.0.1, vendor: Eclipse Adoptium, runtime: /usr/lib/jvm/temurin-21-jdk-amd64 Default locale: fr_FR, platform encoding: UTF-8 OS name: "linux", version: "6.5.0-14-generic", arch: "amd64", family: "unix"

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
- Fixes: https://github.com/quarkusio/quarkus/issues/37786

### CODE REVIEW

File: extensions/resteasy-reactive/rest-client-reactive/runtime/src/main/java/io/quarkus/rest/client/reactive/runtime/RestClientBuilderImpl.java [hunk 1]
```diff
@@ -386,6 +386,10 @@ public <T> T build(Class<T> aClass) throws IllegalStateException, RestClientDefi
         Integer maxChunkSize = (Integer) getConfiguration().getProperty(QuarkusRestClientProperties.MAX_CHUNK_SIZE);
         if (maxChunkSize != null) {
             clientBuilder.maxChunkSize(maxChunkSize);
+        } else if (restClientsConfig.maxChunkSize.isPresent()) {
+            clientBuilder.maxChunkSize(restClientsConfig.maxChunkSize.get());
+        } else if (restClientsConfig.multipart.maxChunkSize.isPresent()) {
+            clientBuilder.maxChunkSize(restClientsConfig.multipart.maxChunkSize.get());
```
Comment (fredericBregier) [inline extensions/resteasy-reactive/rest-client-reactive/runtime/src/main/java/io/quarkus/rest/client/reactive/runtime/RestClientBuilderImpl.java:392]: Question, not necessarily a change: should it be a cumulative Math.max instead of successive if/then/Else ? I understand there is an order in configuration, then documentation should be clear on that ?

Comment (geoand) [reply extensions/resteasy-reactive/rest-client-reactive/runtime/src/main/java/io/quarkus/rest/client/reactive/runtime/RestClientBuilderImpl.java:392]: Why would be a math max?

The point here is to support the new configuration over the old one, the old one is just a fallback until it's removed completely

**Comment by geoand** [comment]
@cescoffier can you have a look at this one when you get a chance? It's probably easier to do a per-commit review.

File: extensions/resteasy-classic/rest-client-config/runtime/src/main/java/io/quarkus/restclient/config/RestClientConfig.java [hunk 2]
```diff
@@ -250,6 +252,15 @@ public class RestClientConfig {
...
     public Optional<Boolean> http2;
 
+    /**
+     * The max HTTP chunk size (8096 bytes by default).
+     * <p>
+     * This property is applicable to reactive REST clients only.
+     */
+    @ConfigItem
+    @ConfigDocDefault("8096")
+    public Optional<Integer> maxChunkSize;
```
Comment (cescoffier) [inline extensions/resteasy-classic/rest-client-config/runtime/src/main/java/io/quarkus/restclient/config/RestClientConfig.java:262]: Don't we have a memory type?

File: extensions/resteasy-classic/rest-client-config/runtime/src/main/java/io/quarkus/restclient/config/RestClientsConfig.java [hunk 3]
```diff
@@ -292,6 +293,15 @@ public class RestClientsConfig {
...
     public boolean http2;
 
+    /**
+     * The max HTTP chunk size (8096 bytes by default).
+     * <p>
+     * Can be overwritten by client-specific settings.
+     */
+    @ConfigItem
+    @ConfigDocDefault("8096")
+    public Optional<Integer> maxChunkSize;
```
Comment (cescoffier) [inline extensions/resteasy-classic/rest-client-config/runtime/src/main/java/io/quarkus/restclient/config/RestClientsConfig.java:303]: Don't we have a memory/size type?

File: extensions/resteasy-classic/rest-client-config/runtime/src/test/java/io/quarkus/restclient/config/RestClientConfigTest.java [hunk 4]
```diff
@@ -51,7 +51,7 @@ private void verifyConfig(RestClientConfig config) {
         assertThat(config.connectionTTL.get()).isEqualTo(30000);
         assertThat(config.connectionPoolSize).isPresent();
         assertThat(config.connectionPoolSize.get()).isEqualTo(10);
-        assertThat(config.multipart.maxChunkSize.get()).isEqualTo(1024);
```
Comment (cescoffier) [inline extensions/resteasy-classic/rest-client-config/runtime/src/test/java/io/quarkus/restclient/config/RestClientConfigTest.java:54]: should we consider this as a breaking change?

File: extensions/resteasy-reactive/rest-client-reactive/runtime/src/test/java/io/quarkus/rest/client/reactive/runtime/RestClientCDIDelegateBuilderTest.java [hunk 5]
```diff
@@ -227,7 +227,7 @@ private static RestClientConfig createSampleClientConfig() {
         clientConfig.maxRedirects = Optional.of(104);
         clientConfig.followRedirects = Optional.of(true);
         clientConfig.multipart = new RestClientMultipartConfig();
-        clientConfig.multipart.maxChunkSize = Optional.of(1024);
+        clientConfig.maxChunkSize = Optional.of(1024);
```
Comment (cescoffier) [inline extensions/resteasy-reactive/rest-client-reactive/runtime/src/test/java/io/quarkus/rest/client/reactive/runtime/RestClientCDIDelegateBuilderTest.java:230]: Should we update the value to be the default from the config?

**Review by cescoffier — CHANGES_REQUESTED** [review]

File: extensions/resteasy-classic/rest-client-config/runtime/src/main/java/io/quarkus/restclient/config/RestClientConfig.java (hunk 2 above)
Comment (geoand) [reply extensions/resteasy-classic/rest-client-config/runtime/src/main/java/io/quarkus/restclient/config/RestClientConfig.java:262]: Good point, I think we do!

File: extensions/resteasy-classic/rest-client-config/runtime/src/test/java/io/quarkus/restclient/config/RestClientConfigTest.java (hunk 4 above)
Comment (geoand) [reply extensions/resteasy-classic/rest-client-config/runtime/src/test/java/io/quarkus/restclient/config/RestClientConfigTest.java:54]: There isn't anything breaking in this chance for now. We just add a new property that takes precedence over the old one.

File: extensions/resteasy-reactive/rest-client-reactive/runtime/src/test/java/io/quarkus/rest/client/reactive/runtime/RestClientCDIDelegateBuilderTest.java (hunk 5 above)
Comment (geoand) [reply extensions/resteasy-reactive/rest-client-reactive/runtime/src/test/java/io/quarkus/rest/client/reactive/runtime/RestClientCDIDelegateBuilderTest.java:230]: This test actually tests that the value loaded from an `application.properties` is reflected onto the config object

File: extensions/resteasy-classic/rest-client-config/runtime/src/test/java/io/quarkus/restclient/config/RestClientConfigTest.java (hunk 4 above)
Comment (geoand) [reply extensions/resteasy-classic/rest-client-config/runtime/src/test/java/io/quarkus/restclient/config/RestClientConfigTest.java:54]: Applied

File: extensions/resteasy-classic/rest-client-config/runtime/src/main/java/io/quarkus/restclient/config/RestClientsConfig.java (hunk 3 above)
Comment (geoand) [reply extensions/resteasy-classic/rest-client-config/runtime/src/main/java/io/quarkus/restclient/config/RestClientsConfig.java]: Applied

**Review by cescoffier — APPROVED** [review]
