### PR TITLE
Forward gRPC context when using @blocking

### LINKED ISSUE #14665: gRPC Context lost when using @Blocking
**Describe the bug**
I use a grpc service with some interceptors. One of the goal of those interceptors is to forward the JWT token from the gRPC service to any client calls later in the code. For this is use the gRPC context. This works fine if I don't use the `@Blocking` annotation.

As expected the `@Blocking` annotation makes my code run into a worker thread. But since I have other grpc calls in this code the JWT is null since the context was lost.

I tried `@ActivateRequestContext` on my method but it seems that it's not compatible with `@Blocking` (see #13358).

This issue sounds similar to #13959 but there is no mention of blocking. And for me the context set in the interceptor works so I don't think if it's related.

**Expected behavior**

I can use the gRPC context in blocking method.

**Actual behavior**
Context is lost when using `@Blocking`

**To Reproduce**

If it make sense I can try to create a small reproducer, but I cannot share my current code. Let me know.

1.  Have a grpc service 
2. Have a grpc interceptor that change the gRPC Context
3. Annotation a gRPC method with `@Blocking`
4. Try to use this context in your blocking method. 

**Configuration**
irrelevant 

**Screenshots**
irrelevant 

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:  `Linux gaetan-desktop 5.4.0-64-generic #72-Ubuntu SMP Fri Jan 15 10:27:54 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
 - Output of `java -version`:  
 ```
 openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment GraalVM CE 21.0.0 (build 11.0.10+8-jvmci-21.0-b06)
OpenJDK 64-Bit Server VM GraalVM CE 21.0.0 (build 11.0.10+8-jvmci-21.0-b06, mixed mode, sharing)
```
 - Quarkus version or git rev: `1.11.0.Final`
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
 ```
 Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 11.0.10, vendor: GraalVM Community, runtime: /home/gaetan/.sdkman/candidates/java/21.0.0.r11-grl
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-64-generic", arch: "amd64", family: "unix"
```

**Additional context**
none

### PR DESCRIPTION
**Pull request by gaetancollaud**
closes #14665 

Since #14687 seems rather complicated for nothing I created this PR.

It simply captures the gRPC context and inject it in the blocking handler.

### CODE REVIEW

**Review by gsmet — CHANGES_REQUESTED** [review]
Could you squash the 2 commits?

Also would it be possible to add a test?

**Review by cescoffier — APPROVED** [review]

**Review by cescoffier — APPROVED** [review]

**Comment by gaetancollaud** [comment]
> Could you squash the 2 commits?
> 
> Also would it be possible to add a test?

I squashed manually my commits. Just out of curiosity, why don't you enable the "Squash mergin" option of github ? It would make thinks easier for developer, no ?

I added some tests, but I had to mock a lot to just test this interceptor. Is it ok for you like this ?

**Comment by gsmet** [comment]
> I squashed manually my commits. Just out of curiosity, why don't you enable the "squash merging" option of github ? It would make thinks easier for developer, no ?

It doesn't work with merge commits.

**Comment by gsmet** [comment]
@cescoffier I let you have a look at the test? I wonder if we should backport this to 1.11 given it's more or less a bugfix. WDYT?

**Review by cescoffier — APPROVED** [review]
You would have preferred a real test, but it's good for now.

File: extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/BlockingServerInterceptor.java [hunk 1]
```diff
@@ -96,11 +97,17 @@ synchronized void setDelegate(ServerCall.Listener<ReqT> delegate) {
...
                 vertx.executeBlocking(new Handler<Promise<Object>>() {
                     @Override
                     public void handle(Promise<Object> f) {
+                        final Context previous = Context.current();
+                        grpcContext.attach();
+
                         consumer.accept(delegate);
                         f.complete();
+
+                        grpcContext.detach(previous);
```
Comment (gsmet) [inline extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/BlockingServerInterceptor.java:110]: @cescoffier maybe it's not mandatory in this case but we usually restore previous contexts in a finally block. It's not needed here?

**Review by gsmet — CHANGES_REQUESTED** [review]

File: extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/BlockingServerInterceptor.java (hunk 1 above)
Comment (gaetancollaud) [reply extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/BlockingServerInterceptor.java:110]: I think it's best to keep it. In my opinion this part of the code is responsible to wrap the context. And it should not rely on any other code that will eventually drop the context. This could have sever security implication. I use the context to store the JWT token. If the context is not cleared correctly and somehow the jwt end up in another request it's a security leak.

Comment (gsmet) [reply extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/BlockingServerInterceptor.java:110]: Maybe I wasn't clear.

My question was: shouldn't this code look like:
```java
final Context previous = Context.current();
grpcContext.attach();
try {
    consumer.accept(delegate);
    f.complete();
} finally {
    grpcContext.detach(previous);
}
```

Comment (gsmet) [reply extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/BlockingServerInterceptor.java:110]: (you might want to put the `attach` in the `try` too, no idea what it does :))

Comment (gaetancollaud) [reply extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/BlockingServerInterceptor.java:110]: Hoo my bad, then I agree, we should do the detach in the finally.

Not sure about the attach. But in the javadoc example it's outside the try: https://grpc.github.io/grpc-java/javadoc/io/grpc/Context.html#attach--

Comment (gaetancollaud) [reply extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/BlockingServerInterceptor.java]: @gsmet done

**Review by gsmet — APPROVED** [review]
Thanks!

**Comment by gsmet** [comment]
And merged, thanks!
