### PR TITLE
Honor Cache and NoCache annotations on implementations of a JAX-RS interface

### LINKED ISSUE #39002: @Cache annotation not honored on reactive REST resource beans with separate interface
### Describe the bug

The org.jboss.resteasy.reactive.Cache annotation is only honored, if it is put on a JaxRS bean or a JaxRS interface itself.
If put on a bean that *implements* a JaxRS interface, the annotation is ignored.

Reasoning: We have lots of services where the JaxRS interfaces are generated from OpenAPI specification. We provide beans that implement these interfaces and Quarkus. We would like to add @Cache annotations to some of the implemented methods to control generated "Cache-Control" headers. But the annotation is ignored.
We cannot put the annotation of the JaxRS interface itself, because that is generated from an OpenAPI spec.

### Expected behavior

When putting a @Cache annotation on a bean method that implements a JaxRS interface, the appropriate "Cache-Control" header should be generated.

### Actual behavior

@Cache annotation is only honored when put on the JaxRS interface itself.

### How to Reproduce?

See attached maven project with failing unit test.

### Output of `uname -a` or `ver`

Mac OS 14 (on MacBook Pro M1)

### Output of `java -version`

openjdk version "17.0.2"

### Quarkus version or git rev

3.7.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn 3.9.6

### Additional information

[resteasy-reactive-cache.zip](https://github.com/quarkusio/quarkus/files/14403472/resteasy-reactive-cache.zip)

### PR DESCRIPTION
**Pull request by danielbobbert**
- Fixes #39002

### CODE REVIEW

**Comment by geoand** [comment]
Nice!

Can you please rebase the commit on top of the latest `main`?
Alternatively, I can do it for you

**Comment by danielbobbert** [comment]
Done

**Comment by geoand** [comment]
Thanks! I'll review tomorrow

File: independent-projects/resteasy-reactive/server/processor/src/main/java/org/jboss/resteasy/reactive/server/processor/scanning/CacheControlScanner.java [hunk 1]
```diff
@@ -27,32 +29,55 @@ public class CacheControlScanner implements MethodScanner {
...
+                // if no annotations where found on implementation, check the interface
+                customizers = scanImpl(method, currentClassInfo, methodContext);
+            }
+            return customizers;
+        } else {
+            return scanImpl(method, actualEndpointClass, methodContext);
+        }
+    }
+
+    private List<HandlerChainCustomizer> scanImpl(MethodInfo methodInfo, ClassInfo classInfo,
```
Comment (geoand) [inline independent-projects/resteasy-reactive/server/processor/src/main/java/org/jboss/resteasy/reactive/server/processor/scanning/CacheControlScanner.java:53]: Can we rename this to `scanImpl`?

**Review by geoand — COMMENTED** [review]
Looks good!

I just added a small comment.
Let's also squash the two commits into a single one

File: independent-projects/resteasy-reactive/server/processor/src/main/java/org/jboss/resteasy/reactive/server/processor/scanning/CacheControlScanner.java (hunk 1 above)
Comment (danielbobbert) [reply independent-projects/resteasy-reactive/server/processor/src/main/java/org/jboss/resteasy/reactive/server/processor/scanning/CacheControlScanner.java:53]: I don't quite understand your comment. I have
- moved the original implementation of scan() to a new private method scanImpl() and renamed the parameters to something more general, because scanImpl is called with different arguments now
- changed the implementation of scan() to recognize the "bean-implements-interface" case and then call scanImpl once with the method&class of the implementation and then with the method&class of the interface
- in the else case, scanImpl is called with the original arguments, so it behaves exactly like the original implementation of scan()

What exactly should we rename?

Comment (geoand) [reply independent-projects/resteasy-reactive/server/processor/src/main/java/org/jboss/resteasy/reactive/server/processor/scanning/CacheControlScanner.java:53]: Oops, sorry I misstyped the comment. I meant rename `scanImpl` to `doScan`

Comment (danielbobbert) [reply independent-projects/resteasy-reactive/server/processor/src/main/java/org/jboss/resteasy/reactive/server/processor/scanning/CacheControlScanner.java]: Done, commits squashed and rebased to current main.

**Review by geoand — APPROVED** [review]
Thanks!

**Comment by danielbobbert** [comment]
Build was complaining about unordered imports. I have fixed these just now.

**Comment by danielbobbert** [comment]
Fixed formatting in tests

**Comment by danielbobbert** [comment]
When reordering imports, I skipped one class, introducing a compile error. Sorry! This is fixed now.

**Comment by geoand** [comment]
Great job!

**Comment by danielbobbert** [comment]
These sanity checks are driving me crazy. Had to remove an unused import in a test class...
How can I run those checks locally before pushing?

**Comment by geoand** [comment]
`mvn process-sources -f extensions/resteasy-reactive` should be enough to get the formatter to do its work on your changes

**Comment by danielbobbert** [comment]
No errors/warnings locally, so we should be fine now.
