### PR TITLE
Select the right default version for a dialect  when  using Hibernate Reactive

### LINKED ISSUE #34032: Wrong hibernate dialect version detected for MS Sql Server
### Describe the bug

It's possible to see this [updating one of the quickstart to use MS SQL Server](https://github.com/DavideD/quarkus-quickstarts/tree/mssql-sequence-final/hibernate-reactive-quickstart).

Quarkus will start an instance of MS SQL server 2019-latest (shouldn't we update it to 2022?) and use as dialect:
```
HHH035001: Using dialect: org.hibernate.dialect.SQLServerDialect, version: 10.0
```

The workaround is to set a custom dialect using the property `quarkus.hibernate-orm.dialect=org.acme.hibernate.reactive.SqlServerDialect`:

```java
package org.acme.hibernate.reactive;

import org.hibernate.dialect.DatabaseVersion;
import org.hibernate.dialect.SQLServerDialect;

public class SqlServerDialect extends SQLServerDialect {
	public SqlServerDialect() {
		super( DatabaseVersion.make( 15 ) );
	}
}
```

I've tested this with Hibernate Reactive and Quarkus 3.1.1

### PR DESCRIPTION
**Pull request by DavideD**
Fix #34032 

It also adds a new `integration-tests/hibernate-reactive-mssql` that's similar to `integration-tests/jpa-mssql`.

### CODE REVIEW

File: integration-tests/hibernate-reactive-mssql/src/main/java/io/quarkus/it/jpa/mssql/HibernateReactiveFunctionalityTestEndpoint.java [hunk 1]
```diff
@@ -0,0 +1,179 @@
...
+        sb.append("\nList complete.\n");
+        System.out.print(sb);
+    }
+
+    private static void persistNewPerson(EntityManager entityManager, String name) {
+        Person person = new Person();
+        person.setName(name);
+        person.setAddress(new SequencedAddress("Street " + randomName()));
+        entityManager.persist(person);
+    }
```
Comment (yrodiere) [inline integration-tests/hibernate-reactive-mssql/src/main/java/io/quarkus/it/jpa/mssql/HibernateReactiveFunctionalityTestEndpoint.java:161]: These tests are using JPA instead of the Hibernate Reactive API... ?

File: integration-tests/hibernate-reactive-mssql/src/test/java/io/quarkus/it/jpa/mssql/DeafultDialectVersionTest.java [hunk 2]
```diff
@@ -0,0 +1,27 @@
...
+
+import io.quarkus.hibernate.orm.runtime.config.DialectVersions;
+import io.quarkus.test.junit.QuarkusTest;
+import io.restassured.RestAssured;
+
+/**
+ * Test the dialect used by default in Quarkus.
+ */
+@QuarkusTest
+public class DeafultDialectVersionTest {
```
Comment (yrodiere) [inline integration-tests/hibernate-reactive-mssql/src/test/java/io/quarkus/it/jpa/mssql/DeafultDialectVersionTest.java:15]: Typo in the class name.

File: integration-tests/hibernate-reactive-mssql/src/test/java/io/quarkus/it/jpa/mssql/DeafultDialectVersionTest.java
Comment (yrodiere) [inline integration-tests/hibernate-reactive-mssql/src/test/java/io/quarkus/it/jpa/mssql/DeafultDialectVersionTest.java:1]: FYI, for Hibernate ORM we duplicated this test for every supported DB. I see we already have integration tests for Hibernate Reactive with postgres, db2 and mysql; you may want to copy/paste the test and corresponding endpoint there.

File: integration-tests/hibernate-reactive-mssql/README.md [hunk 3]
```diff
@@ -0,0 +1,47 @@
+# JPA example with Microsoft SQL Server
```
Comment (yrodiere) [inline integration-tests/hibernate-reactive-mssql/README.md:1]: IMO we should either remove the README or update it to talk about HR instead of JPA.

**Review by yrodiere — DISMISSED** [review]
Thanks! The implementation looks good, but the test is using JPA, so that looks wrong to me.

File: integration-tests/hibernate-reactive-mssql/README.md (hunk 3 above)
Comment (gsmet) [reply integration-tests/hibernate-reactive-mssql/README.md:1]: I would drop it.

File: integration-tests/hibernate-reactive-mssql/src/main/java/io/quarkus/it/hibernate/reactive/mssql/HibernateReactiveMySQLAlternativeTestEndpoint.java [hunk 4]
```diff
@@ -0,0 +1,101 @@
...
+import io.vertx.mutiny.mssqlclient.MSSQLPool;
+import io.vertx.mutiny.sqlclient.Row;
+import io.vertx.mutiny.sqlclient.RowSet;
+import io.vertx.mutiny.sqlclient.Tuple;
+import jakarta.inject.Inject;
+import jakarta.ws.rs.GET;
+import jakarta.ws.rs.Path;
+
+@Path("/alternative-tests")
+public class HibernateReactiveMySQLAlternativeTestEndpoint {
```
Comment (yrodiere) [inline integration-tests/hibernate-reactive-mssql/src/main/java/io/quarkus/it/hibernate/reactive/mssql/HibernateReactiveMySQLAlternativeTestEndpoint.java:15]: This is the MS SQL module, though... not MySQL.

File: integration-tests/hibernate-reactive-mssql/src/main/java/io/quarkus/it/hibernate/reactive/mssql/HibernateReactiveMySQLTestEndpoint.java [hunk 5]
```diff
@@ -0,0 +1,100 @@
...
+import io.vertx.mutiny.mssqlclient.MSSQLPool;
+import io.vertx.mutiny.sqlclient.Row;
+import io.vertx.mutiny.sqlclient.RowSet;
+import io.vertx.mutiny.sqlclient.Tuple;
+import jakarta.inject.Inject;
+import jakarta.ws.rs.GET;
+import jakarta.ws.rs.Path;
+
+@Path("/tests")
+public class HibernateReactiveMySQLTestEndpoint {
```
Comment (yrodiere) [inline integration-tests/hibernate-reactive-mssql/src/main/java/io/quarkus/it/hibernate/reactive/mssql/HibernateReactiveMySQLTestEndpoint.java:15]: This is the MS SQL module, though... not MySQL.

File: integration-tests/hibernate-reactive-mssql/src/main/java/io/quarkus/it/hibernate/reactive/mssql/HibernateReactiveMySQLAlternativeTestEndpoint.java
Comment (yrodiere) [inline integration-tests/hibernate-reactive-mssql/src/main/java/io/quarkus/it/hibernate/reactive/mssql/HibernateReactiveMySQLAlternativeTestEndpoint.java:1]: As far as I can see, the only difference between `HibernateReactiveMySQLAlternativeTestEndpoint` `HibernateReactiveMySQLTestEndpoint` is the name of the class and some formatting... Are you sure this is what you wanted?

**Review by yrodiere — COMMENTED** [review]
Thanks. Tests look fine, but I think there are some oversights. I'll let you decide what you want to do...

File: integration-tests/hibernate-reactive-mssql/src/main/java/io/quarkus/it/hibernate/reactive/mssql/HibernateReactiveMySQLAlternativeTestEndpoint.java
Comment (DavideD) [reply integration-tests/hibernate-reactive-mssql/src/main/java/io/quarkus/it/hibernate/reactive/mssql/HibernateReactiveMySQLAlternativeTestEndpoint.java:1]: I've just copied all the classes from the MySQL module (And I forgot to rename a couple of classes). 
I guess the integration tests need some clean up everywhere.

Comment (DavideD) [reply integration-tests/hibernate-reactive-mssql/src/main/java/io/quarkus/it/hibernate/reactive/mssql/HibernateReactiveMySQLAlternativeTestEndpoint.java:1]: Ah, these alternative endpoint were introduced when it was possible to use the `CompletionStage` API. I will remove them

**Comment by DavideD** [comment]
I've renamed the classes and remove the tests with the alternative end-point

**Review by yrodiere — APPROVED** [review]
LGTM, thanks!
