### PR TITLE
Make sure extension metadata properties are not including timestamps

### LINKED ISSUE #38364: extension-maven-plugin does not support reproducible builds
### Describe the bug

We need to make [OptaPlanner](https://github.com/apache/incubator-kie-optaplanner) builds [reproducible](https://cwiki.apache.org/confluence/display/SECURITY/Reproducible+Builds). OptaPlanner has a few Quarkus extension modules that are built using the Quarkus `extension-maven-plugin`. This plugin produces several properties that contain **timestamps**. This goes against the requirement for the JARs to be identical bit by bit.

The binary and the sources JAR artifacts of the `optaplanner-quarkus` extension are affected:
```
[INFO] --- maven-artifact-plugin:3.5.1-SNAPSHOT:compare (default-cli) @ optaplanner-quarkus ---
[WARNING] SCM source tag in buildinfo source.scm.tag=HEAD does not permit rebuilders reproducible source checkout
[INFO] Reference buildinfo file not found: it will be generated from downloaded reference artifacts
[INFO] Reference build java.version: 18 (from MANIFEST.MF Build-Jdk-Spec)
[INFO] Reference build os.name: Unix (from pom.properties newline)
[INFO] Minimal buildinfo generated from downloaded artifacts: /var/home/jlocker/src/github.com/kiegroup/optaplanner/optaplanner-quarkus-integration/optaplanner-quarkus/runtime/target/reference/optaplanner-quarkus-999-SNAPSHOT.buildinfo
[ERROR] size mismatch optaplanner-quarkus-999-SNAPSHOT.jar: investigate with diffoscope optaplanner-quarkus-integration/optaplanner-quarkus/runtime/target/reference/org.optaplanner/optaplanner-quarkus-999-SNAPSHOT.jar optaplanner-quarkus-integration/optaplanner-quarkus/runtime/target/optaplanner-quarkus-999-SNAPSHOT.jar
[ERROR] size mismatch optaplanner-quarkus-999-SNAPSHOT-sources.jar: investigate with diffoscope optaplanner-quarkus-integration/optaplanner-quarkus/runtime/target/reference/org.optaplanner/optaplanner-quarkus-999-SNAPSHOT-sources.jar optaplanner-quarkus-integration/optaplanner-quarkus/runtime/target/optaplanner-quarkus-999-SNAPSHOT-sources.jar
[ERROR] Reproducible Build output summary: 2 files ok, 2 different
[ERROR] see diff optaplanner-quarkus-integration/optaplanner-quarkus/runtime/target/reference/optaplanner-quarkus-999-SNAPSHOT.buildinfo optaplanner-quarkus-integration/optaplanner-quarkus/runtime/target/optaplanner-quarkus-999-SNAPSHOT.buildinfo
[ERROR] see also https://maven.apache.org/guides/mini/guide-reproducible-builds.html
[INFO] Reproducible Build output comparison saved to /var/home/jlocker/src/github.com/kiegroup/optaplanner/optaplanner-quarkus-integration/optaplanner-quarkus/runtime/target/optaplanner-quarkus-999-SNAPSHOT.buildcompare
[INFO] Aggregate buildcompare copied to /var/home/jlocker/src/github.com/kiegroup/optaplanner/target/optaplanner-parent-999-SNAPSHOT.buildcompare
```

When I extract the archives and run a diff, I can see the timestamp difference in `quarkus-extension.properties` and `quarkus-javadoc.properties` files inside the binary JAR:
```diff
diff -r reference/META-INF/quarkus-extension.properties current/META-INF/quarkus-extension.properties
2c2
< #Tue Jan 23 12:24:21 CET 2024
---
> #Tue Jan 23 12:39:19 CET 2024
diff -r reference/META-INF/quarkus-javadoc.properties current/META-INF/quarkus-javadoc.properties
2c2
< #Tue Jan 23 12:24:21 CET 2024
---
> #Tue Jan 23 12:39:19 CET 2024
```

and also some `.jdp` properties files inside the sources JAR:
```diff
diff -r reference/org/optaplanner/quarkus/config/OptaPlannerRuntimeConfig.jdp current/org/optaplanner/quarkus/config/OptaPlannerRuntimeConfig.jdp
2c2
< #Tue Jan 23 12:24:21 CET 2024
---
> #Tue Jan 23 12:39:19 CET 2024
diff -r reference/org/optaplanner/quarkus/config/SolverManagerRuntimeConfig.jdp current/org/optaplanner/quarkus/config/SolverManagerRuntimeConfig.jdp
2c2
< #Tue Jan 23 12:24:21 CET 2024
---
> #Tue Jan 23 12:39:19 CET 2024
diff -r reference/org/optaplanner/quarkus/config/SolverRuntimeConfig.jdp current/org/optaplanner/quarkus/config/SolverRuntimeConfig.jdp
2c2
< #Tue Jan 23 12:24:21 CET 2024
---
> #Tue Jan 23 12:39:19 CET 2024
diff -r reference/org/optaplanner/quarkus/config/TerminationRuntimeConfig.jdp current/org/optaplanner/quarkus/config/TerminationRuntimeConfig.jdp
2c2
< #Tue Jan 23 12:24:21 CET 2024
---
> #Tue Jan 23 12:39:19 CET 2024
```

I haven't found where the `.jdp` and `-javadoc.properties` files come from, but the `quarkus-extension.properties` file is produce by `extension-maven-plugin` here:

https://github.com/quarkusio/quarkus/blob/b7159fc5558a87035d3f50a7c332e253b2ab1326/independent-projects/extension-maven-plugin/src/main/java/io/quarkus/maven/ExtensionDescriptorMojo.java#L393

### Expected behavior

In order to support reproducible builds of user Quarkus extensions, the `extension-maven-plugin` should avoid storing timestamps in any of the three types of properties files:
- `META-INF/quarkus-extension.properties`,
- `META-INF/quarkus-javadoc.properties`,
- and `com/example/myproject/MyExtensionConfig.jdp`.

### Actual behavior

Timestamps are present in the properties files mentioned above.

### How to Reproduce?

I can prepare a minimal reproducer (a toy Quarkus extension project) upon request.

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

See https://reproducible-builds.org/ why reproducible builds are important and why it is a good idea to support them in any kind of open-source project, including Quarkus extensions.

### PR DESCRIPTION
**Pull request by aloubyansky**
Fixes https://github.com/quarkusio/quarkus/issues/38364

### CODE REVIEW

File: independent-projects/bootstrap/app-model/src/main/java/io/quarkus/bootstrap/util/PropertyUtils.java [hunk 1]
```diff
@@ -67,4 +77,166 @@ public static final boolean getBoolean(String name, boolean notFoundValue) {
         final String value = getProperty(name, (notFoundValue ? TRUE : FALSE));
         return value.isEmpty() ? true : Boolean.parseBoolean(value);
     }
+
+    /**
+     * Stores properties into a file sorting the keys alphabetically and following
+     * {@link Properties#store(Writer, String)} format but skipping the timestamp and comments.
```
Comment (gsmet) [inline independent-projects/bootstrap/app-model/src/main/java/io/quarkus/bootstrap/util/PropertyUtils.java:83]: How exactly do you skip the timestamps?

Comment (aloubyansky) [reply independent-projects/bootstrap/app-model/src/main/java/io/quarkus/bootstrap/util/PropertyUtils.java:83]: By writing each line in the methods below instead of calling `Properties.store(...)`

Comment (gsmet) [reply independent-projects/bootstrap/app-model/src/main/java/io/quarkus/bootstrap/util/PropertyUtils.java:83]: Ah OK. It's `Properties.store()` adding the timestamps!

**Review by gsmet — APPROVED** [review]

File: independent-projects/bootstrap/app-model/src/main/java/io/quarkus/bootstrap/util/PropertyUtils.java (hunk 1 above)
Comment (gastaldi) [reply independent-projects/bootstrap/app-model/src/main/java/io/quarkus/bootstrap/util/PropertyUtils.java:83]: You can bypass that by running with `-Djava.properties.date=`, but I think the current solution is easier to understand
