### PR TITLE
CLI: fix file handling in registry remove; more feedback

### LINKED ISSUE #22911: CLI cannot remove registry from the list
### Describe the bug

Registries added to cli cannot be removed

### Expected behavior

Attempts to remove registries from config should be successfull

### Actual behavior

Attempt to remove a registry from the list leads to error `Can only remove registries from an existing configuration. The specified config file does not exist: null`

### How to Reproduce?

1.  `quarkus registry add quarkus.example.com`
2. Check the list:
``` 
$ quarkus registry
Configured Quarkus extension registries:
registry.quarkus.io
quarkus.example.com
(Config source: file: ~/.quarkus/config.yaml)
```
2. `$ quarkus registry remove quarkus.example.com`

### Output of `uname -a` or `ver`

OS name: "linux", version: "5.15.6-100.fc34.x86_64"

### Output of `java -version`

11.0.13, vendor: Eclipse Adoptium

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.6.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ebullient**
Resolves #22911

### CODE REVIEW

File: devtools/cli/src/main/java/io/quarkus/cli/RegistryRemoveCommand.java [hunk 1]
```diff
@@ -31,26 +32,29 @@ public Integer call() throws Exception {
...
-        if (existingConfig) {
-            registryClient.refreshRegistryCache(output);
-            config = registryClient.resolveConfig().mutable();
-            if (config.getSource().getFilePath() == null) {
-                output.error("Can only modify file-based configuration. Config source is " + config.getSource().describe());
-                return CommandLine.ExitCode.SOFTWARE;
-            }
+        if (configYaml != null && !existingConfig) {
+            // we're creating a new configuration for a new file
+            config = RegistriesConfig.builder();
```
Comment (aloubyansky) [inline devtools/cli/src/main/java/io/quarkus/cli/RegistryRemoveCommand.java:37]: Does it make sense for remove? Shouldn't the error removed below be moved here instead?

Comment (ebullient) [reply devtools/cli/src/main/java/io/quarkus/cli/RegistryRemoveCommand.java:37]: In the interest of avoiding a lot of unnecessary null checks, I made this more similar to what happens with add. So if that condition is true, you'd attempt to remove a registry from the default configuration, and would write the result to the specified location (which would cause the file to be created). While perhaps not particularly useful, it isn't an error.

**Review by aloubyansky — APPROVED** [review]
