### PR TITLE
Fix documentation for quarkus.hibernate-orm.enabled

### LINKED ISSUE #31418: Fix doc generation for quarkus.hibernate-orm.enabled
We have `<strong>...</strong>` in the configuration reference, this needs fixing.

### PR DESCRIPTION
**Pull request by gsmet**
We use the AsciiDoc format but we have HTML markups.

Fixes https://github.com/quarkusio/quarkus/issues/31418

### CODE REVIEW

File: core/processor/src/main/java/io/quarkus/annotation/processor/generate_doc/JavaDocParser.java [hunk 1]
```diff
@@ -220,11 +221,12 @@ private void appendHtml(StringBuilder sb, Node node) {
                     sb.append(BACKTICK);
                     break;
                 case BOLD_NODE:
-                case EMPHASIS_NODE:
+                case STRONG_NODE:
                     sb.append(STAR);
                     appendHtml(sb, childNode);
                     sb.append(STAR);
                     break;
```
Comment (yrodiere) [inline core/processor/src/main/java/io/quarkus/annotation/processor/generate_doc/JavaDocParser.java:228]: I assume this makes it so that `<strong>` is rendered correctly by our Javadoc doclet?

**Review by yrodiere — APPROVED** [review]
LGTM, thanks

**Comment by yrodiere** [comment]
Looks like `JavaDocConfigDescriptionParserTest` needs adjusting, though

File: core/processor/src/main/java/io/quarkus/annotation/processor/generate_doc/JavaDocParser.java (hunk 1 above)
Comment (gsmet) [reply core/processor/src/main/java/io/quarkus/annotation/processor/generate_doc/JavaDocParser.java:228]: Yes. I thought it was the problem initially as it wasn't handled at all. And then I had the good idea to have a look at the actual javadoc :).

I fixed the tests.

**Review by yrodiere — APPROVED** [review]
