### PR TITLE
Forward protoc log to console for gradle project

### LINKED ISSUE #11552: quarkus 1.7.0.Final gradle plugin hides errors from protoc compilation
**Description**
Gradle build with quarkus plugin and 'io.quarkus:quarkus-grpc' dependency tries to compile protoc files in src/main/proto. It failed for me because of issue #11550 , but finding the real reason wasn't easy task because protoc compilation process errors is not printed anywhere.

**Implementation ideas**
Gradle should print command before executing it when --debug is passed to the gradle.
protoc process output should get to the console when --debug or even --info is passed to the gradle.

### PR DESCRIPTION
**Pull request by glefloch**
This branch make sure `protoc` output are redirected to console when running a gradle build. 

This reuse the same `ProcessUtil` class used to forward `native-image` log to console. 

close #11552

### CODE REVIEW

**Comment by jaikiran** [comment]
Hello @glefloch, this looks OK to me. The only question I have is about the `CodeGenContext` which I've mentioned inline.

File: core/deployment/src/main/java/io/quarkus/deployment/CodeGenerator.java [hunk 1]
```diff
@@ -26,6 +26,7 @@ public static void initAndRun(ClassLoader classLoader,
             AppModel appModel) throws CodeGenException {
         List<CodeGenData> generators = init(classLoader, sourceParentDirs, generatedSourcesDir, buildDir, sourceRegistrar);
         for (CodeGenData generator : generators) {
+            generator.setRedirectIO(true);
```
Comment (jaikiran) [inline core/deployment/src/main/java/io/quarkus/deployment/CodeGenerator.java:29]: Does this `initAndRun` get called _only_ for Gradle build? In which case this change looks good. The reason why the `ProcessUtil` has been conditionally used is to avoid streaming the STDOUT and STDERR when Maven tool is being used and instead just rely on inheriting IO. So as long as this gets called only for Gradle, the change looks fine to me.

Comment (glefloch) [reply core/deployment/src/main/java/io/quarkus/deployment/CodeGenerator.java:29]: Yes, I ran a search on all the project and this is only used by gradle. Maven OTOH, uses the `init` and the `trigger` method.

**Comment by glefloch** [comment]
@jaikiran thanks for the review!

File: core/deployment/src/main/java/io/quarkus/deployment/CodeGenerator.java (hunk 1 above)
Comment (jaikiran) [reply core/deployment/src/main/java/io/quarkus/deployment/CodeGenerator.java:29]: Thank you for confirming that.

File: core/deployment/src/main/java/io/quarkus/deployment/CodeGenContext.java [hunk 2]
```diff
@@ -9,12 +9,14 @@
...
     private final Path inputDir;
+    private final boolean redirectIO;
 
-    public CodeGenContext(AppModel model, Path outDir, Path workDir, Path inputDir) {
+    public CodeGenContext(AppModel model, Path outDir, Path workDir, Path inputDir, boolean redirectIO) {
         this.model = model;
         this.outDir = outDir;
         this.workDir = workDir;
         this.inputDir = inputDir;
+        this.redirectIO = redirectIO;
```
Comment (michalszynkiewicz) [inline core/deployment/src/main/java/io/quarkus/deployment/CodeGenContext.java:19]: why `redirectIO` and not `inheritIO` ?

Comment (glefloch) [reply core/deployment/src/main/java/io/quarkus/deployment/CodeGenContext.java:19]: At the beginning named it like that. But after updating the `ProcessUtil` class from: 

    public static Process launchProcess(final ProcessBuilder builder, final Optional<ProcessInheritIODisabled> processInheritIODisabled)

to have this method signature:

    public static Process launchProcess(final ProcessBuilder builder, final boolean shouldRedirectIO)

calling this method from the native build step wth a `ProcessInheritIODisabled` would have give something like :

    launch(p, !processInheritIODisabled.isPresent())

So I preferred moving the negation in the `launchProcess` method.

**Review by jaikiran — APPROVED** [review]

**Comment by glefloch** [comment]
is it ok for you @michalszynkiewicz ?

**Comment by glefloch** [comment]
@jaikiran are you ok to merge this one?

**Comment by jaikiran** [comment]
Hello @glefloch, I've merged this now. @michalszynkiewicz, let us know if you still think the `redirectIO` should instead be `inheritIO`. We can take that up separately in a new PR if necessary.

**Comment by glefloch** [comment]
Thanks @jaikiran, and yes I can update the code @michalszynkiewicz if you want to.

**Comment by michalszynkiewicz** [comment]
It's okay to me, sorry for being unresponsive, I have been neck-deep in other tasks :(

**Comment by glefloch** [comment]
No problem ;) don't hesitate to ping me if I can help ;)
