### PR TITLE
Fix missing include clause in the gRPC proto compilation

### LINKED ISSUE #36078: gRPC: Built in quarkus-maven compiler doesn't seem to handle subfolders of protos in external dependency
### Describe the bug

In a nutshell, we have an external dependency that has our base protos under a subfolder and we want to pull those into our project and  compile those and the project specific ones.

However, the protoc/grpc compiler doesn't appear to handle subfolders like expected.

Or we are just configuring things wrong based on our understanding of the docs.

I've explained it all here with a reproducer.

https://github.com/tmulle/quarkus-grpc-import-test

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

3.4.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by cescoffier**
Fix missing include statements in the proto compilation and also improve the syntax of the proto include/exclude clauses (comma-separated list accepting spaces)

Fix https://github.com/quarkusio/quarkus/issues/36078

### CODE REVIEW

File: extensions/grpc/codegen/src/main/java/io/quarkus/grpc/deployment/GrpcCodeGen.java [hunk 1]
```diff
@@ -100,11 +101,14 @@ public boolean trigger(CodeGenContext context) throws CodeGenException {
...
-                protoFilesFromDependencies.stream()
-                        .map(Path::normalize)
-                        .map(Path::toAbsolutePath)
-                        .map(Path::toString)
-                        .forEach(protoFiles::add);
+                for (Path files : protoFilesFromDependencies) {
+                    var pathToProtoFile = files.normalize().toAbsolutePath();
+                    var pathToParentDir = files.getParent();
+                    // Add the proto file to the list of proto to compile, but also add the directory containing the
+                    // proto file to the list of directories to include (it's a set, so no duplicate).
```
Comment (alesj) [inline extensions/grpc/codegen/src/main/java/io/quarkus/grpc/deployment/GrpcCodeGen.java:108]: Why also the dir?

Comment (cescoffier) [reply extensions/grpc/codegen/src/main/java/io/quarkus/grpc/deployment/GrpcCodeGen.java:108]: Because if you don't, it cannot resolve import statements from proto files included in the application. That was the bug.

**Review by alesj — APPROVED** [review]

**Comment by cescoffier** [comment]
The failure is related, investigating...

**Comment by cescoffier** [comment]
I fixed the problem. It was more a CI issue than a real issue. 

We were computing a directory location. With our CI we had 2 distinct locations (one from the first build and one from the IT build) leading to duplicate proto files. I fixed it to generate unique but conservative locations.

**Review by geoand — APPROVED** [review]

**Comment by gsmet** [comment]
@cescoffier should we consider backporting this for 3.4.2?

**Comment by cescoffier** [comment]
No I think it's fine. Also, this Pr introduced a regression I fixed in another PR.
