### PR TITLE
Use addHeadersEndHandler instead of addEndHandler for Undertow compression

### LINKED ISSUE #6063: ConnectionBase::queueForWrite is not loom friendly
### Version

4.x

### Context

This is a sister of https://github.com/netty/netty/issues/16158 and affecting Quarkus while running with VirtualThread(s) because the mentioned synchronized block is not loom friendly and inflate the lock, causing increases in native memory usage, background deflation activity and leading to native mutex contention as well.

Replacing it with a reentrant lock could be a better option.

### Steps to reproduce

_No response_

### Do you have a reproducer?

_No response_

### LINKED ISSUE #53645: Undertow compression uses `addEndHandler` instead of `addHeadersEndHandler`
The Undertow servlet integration uses `RoutingContext.addEndHandler()` to remove the `Content-Encoding: identity` header for compressible responses. This handler fires **after** the response has been written to the channel. The correct API is `RoutingContext.addHeadersEndHandler()`, which fires during `prepareHeaders()` **before** the response message is created and written.

With the current code, compression works by accident on Vert.x 4.x because `synchronized(this)` in `ConnectionBase.writeToChannel()` shares the same monitor as `synchronized(conn)` in `Http1xServerResponse.end()`. When a virtual thread calls `end()`, the event loop write lambda blocks on the monitor until the VT exits `end()`, giving the end handler time to fire before the actual write.

This coupling breaks with any lock-free or decoupled-lock write path, which is needed to fix [eclipse-vertx/vert.x#6063](https://github.com/eclipse-vertx/vert.x/issues/6063) (monitor inflation under virtual threads). It will also break with Vert.x 5.x, which uses `OutboundMessageQueue` (MPSC-based) - I built a dirty backport of it, to make sure (FYI @jponge ).

To clarify. with any lock-free approach, the write executes before the end handler, and the encoder sees `Content-Encoding: identity` and skips compression.

This is the same bug that caused the revert of [eclipse-vertx/vert.x#5619](https://github.com/eclipse-vertx/vert.x/pull/5619) (see [#5687](https://github.com/eclipse-vertx/vert.x/pull/5687)). That fix was correct but exposed this Quarkus bug.

### PR DESCRIPTION
**Pull request by franz1981**
This is necessary to re-revert https://github.com/eclipse-vertx/vert.x/pull/5619 and fix https://github.com/eclipse-vertx/vert.x/issues/6063#issuecomment-4247345661 as well.

In `UndertowDeploymentRecorder.java` (around line 443):

```java
// Note that we can't add an end handler in a separate HttpCompressionHandler because VertxHttpExchange does set
// its own end handler and so the end handlers added previously are just ignored...
if (!compressMediaTypes.isEmpty()) {
    event.addEndHandler(new Handler<AsyncResult<Void>>() {
        @Override
        public void handle(AsyncResult<Void> result) {
            if (result.succeeded()) {
                HttpCompressionHandler.compressIfNeeded(event, compressMediaTypes);
            }
        }
    });
}
```

The comment explains why `HttpCompressionHandler` (which correctly uses `addHeadersEndHandler`) can't be used as a separate handler: `VertxHttpExchange` sets its own end handler on the response, which replaces previously added end handlers.

However, `addHeadersEndHandler` does **not** have this problem because `VertxHttpExchange` does not set `headersEndHandler` on the response.

FYI other handlers, does it right already: https://github.com/quarkusio/quarkus/blob/1cb7a63b55d120b909d38afc92c2da828c72cf7e/extensions/smallrye-graphql/runtime/src/main/java/io/quarkus/smallrye/graphql/runtime/SmallRyeGraphQLCompressionHandler.java

- Fixes: #53645

### CODE REVIEW

File: extensions/undertow/deployment/src/test/java/io/quarkus/undertow/test/compress/CompressionEnabledTestCase.java [hunk 1]
```diff
@@ -16,7 +16,7 @@ public class CompressionEnabledTestCase {
                     .addClasses(SimpleServlet.class))
             .overrideConfigKey("quarkus.http.enable-compression", "true");
 
-    @Test
+    @RepeatedTest(1000)
```
Comment (franz1981) [inline extensions/undertow/deployment/src/test/java/io/quarkus/undertow/test/compress/CompressionEnabledTestCase.java:19]: This has been temporarly added @gsmet because this test [was used](https://github.com/eclipse-vertx/vert.x/pull/5619#issuecomment-3232613123) to revert https://github.com/eclipse-vertx/vert.x/pull/5619 and I want to make sure the CI is green with the "worst way" to run it

**Comment by franz1981** [comment]
I've run the spring vs quarkus benchmark with virtual thread and JDK 25, and found something unlucky, but expected - no throughput changes :"( but...

```
                            BASELINE           PATCHED                                                                                                                  
  Throughput:               13,537 req/s       13,391 req/s  (~same)                                                                                                    
                                                                                                                                                                        
  Lock contention (10s):                                                                                                                                                
    java.lang.Object                                                                                                                                                    
      (clearInterrupt):     1,010 ms           2,522 ms  ← WORSE (+150%)                                                                                                
        event loops:          996 ms           1,493 ms                                                                                                                 
        FJP workers:            0 ms           1,040 ms  ← NEW                                                                                                          
                                                                                                                                                                        
    Http1xServerConnection:  588 ms             660 ms  ← similar                                                                                                       
      queueForWrite:          588 ms  (11,297)    0 ms  ← ELIMINATED                                                                                                    
      enqueueRequest:           0 ms             ~260 ms  ← newly visible                                                                                               
      onEnd/drain:              0 ms             ~400 ms  ← newly visible                                                                                               
                                                                                                                                                                        
    TOTAL:                  ~1,598 ms          ~3,182 ms  ← WORSE
```

**before:** 
[lock-baseline-j25-threads.html](https://github.com/user-attachments/files/26764435/lock-baseline-j25-threads.html)

**after re-reverting https://github.com/eclipse-vertx/vert.x/pull/5619:**
[lock-fix-j25-threads.html](https://github.com/user-attachments/files/26764449/lock-fix-j25-threads.html)

In short: the patch worked (!!!), but it has exposed (and made worse, since is now...alone!) the more severe contention on the NIO selector's `synchronized` :
<img width="1911" height="821" alt="image" src="https://github.com/user-attachments/assets/2fa27b22-31e2-4e29-b36f-51264b99401c" />

which has been already reported at https://github.com/netty/netty/issues/16158#issuecomment-4229657185
with the variation that the different fork-join workers (VirtualThreads mounted on it) they contend with each other(s) AND the target Vertx/Netty EventLoop's `synchronized` - and this can be solved mostly on Netty itself, similar to what other native transports do.

and, minor, https://github.com/quarkusio/quarkus/issues/37907

**Comment by franz1981** [comment]
@vietj can you please take a look as well? :pray:

**Review by melloware — APPROVED** [review]

**Review by jponge — COMMENTED** [review]
What I see makes sense for the headers management but I'll leave it to someone who understands Undertow better.

**Review by geoand — APPROVED** [review]

**Comment by gsmet** [comment]
I'm surprised we are still benchmarking Undertow?

**Comment by franz1981** [comment]
> I'm surprised we are still benchmarking Undertow?

We're not, good point. 
I'm using our Spring vs Quarkus benchmark, with Loom.
While working on it, I've found that we have few synchronized among VirtualThread (running the "blocking" code) and the EventLoop(s) of Netty and I'm diligently removing all of them, as they impact performance.

During this work I've discovered that https://github.com/eclipse-vertx/vert.x/pull/5619 has been reverted and I wanted to know why: while investigating on it, I've found this issue as the main reason why it has been reverted.
So, I've investigated if it was a legit issue and found out it was a Quarkus issue instead.
If we fix this Quarkus issue, it would allow us to re-revert https://github.com/eclipse-vertx/vert.x/pull/5619 and remove this `sychronized` hit while using Loom - and not only - as you can see in https://github.com/eclipse-vertx/vert.x/pull/5619#issue-3160080871 it improves performance outside of Loom as well ^^

As a bonus: Vertx 5 is similarly splitting the lock-free enqueue of work with the header settings, so we will hit the same problem while moving to it: fixing this issue (in this pr) is going to be beneficial while moving to Vertx 5 as well.

**Comment by melloware** [comment]
As a heavy user of Undertow I appreciate it!!

**Review by jponge — APPROVED** [review]

**Comment by franz1981** [comment]
So @gsmet @geoand if we proceed with this, I am going to ask @vietj to re-revert https://github.com/eclipse-vertx/vert.x/pull/5619

**Comment by geoand** [comment]
Let's get it in

**Comment by franz1981** [comment]
thanks @geoand !

**Comment by geoand** [comment]
Thanks for finding and fixing this!

**Comment by melloware** [comment]
@gsmet any chance you can backport this to 3.35.1 ?

**Comment by franz1981** [comment]
It has worked @melloware ?

**Comment by melloware** [comment]
well i wanted an official version so we could announce it to a larger group to test it out and verify if it fixes our JSF compression issues

**Comment by melloware** [comment]
a lot of our users won't test on a SNAPSHOT.

**Comment by geoand** [comment]
I'd prefer to have this in `3.36.0.CR1` first before backporting

**Comment by melloware** [comment]
ok understood we can test when CR1 is published
