### PR TITLE
IBM Db2 - Register resource bundle classes for reflection

### LINKED ISSUE #36399: quarkus-jdbc-db2: resource bundle missing
### Describe the bug

I'm using quarkus-jdbc-db2 with xa-transactions (version 3.2.6.Final) + camel. 

When an exception occurs and the application executes a rollback, I can see some logs that point to a missing resource bundle: 

```
WARN: Datasource 'DB2DB': [jcc]Missing resource bundle: A resource bundle could not be found in the com.ibm.db2.jcc package for IBM Data Server Driver for JDBC and SQLJ ERRORCODE=-4201, SQLSTATE=2D521
```
```
WARN: ARJUNA016045: attempted rollback of < formatId=131077, gtrid_length=35, bqual_length=36, tx_uid=0:ffff7f000101:cbed:652644ec:16, node_name=quarkus, branch_uid=0:ffff7f000101:cbed:652644ec:18, subordinatenodename=null, eis_name=0 > (io.agroal.narayana.BaseXAResource@42665326) failed with exception code ARJUNA016099: Unknown error code:0
: javax.transaction.xa.XAException: Error trying to end xa transaction: [jcc]Missing resource bundle: A resource bundle could not be found in the com.ibm.db2.jcc package for IBM Data Server Driver for JDBC and SQLJ ERRORCODE=-4228, SQLSTATE=null
```
This happens in native mode, but not in jvm mode. 

I have also found other tickets in which this behaviour is mentioned in different contexts. 
- https://github.com/quarkusio/quarkus/issues/22711#issuecomment-1007494676
- https://github.com/quarkusio/quarkus/issues/11395#issuecomment-674153928

In the first ticket, someone has posted a file where the missing resource bundles seem to be listed: https://github.com/quarkusio/quarkus/issues/22711#issuecomment-1010052100

related zulip topic: 
https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Db2.20resource.20bundle

### Expected behavior

It would be good, if there were no missing resource bundle logs. 

### Actual behavior

_No response_

### How to Reproduce?

Reproducer: 
https://github.com/louisa-fr/quarkus-db2-resource-bundle-reproducer
(see README of repository)

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by gsmet**
As usual with Db2, we are shooting in the dark a bit but it seems to solve the OP's issue.

Fixes #36399

### CODE REVIEW

File: extensions/jdbc/jdbc-db2/deployment/src/main/java/io/quarkus/jdbc/db2/deployment/JDBCDB2Processor.java [hunk 1]
```diff
@@ -55,12 +65,23 @@ void configureAgroalConnection(BuildProducer<AdditionalBeanBuildItem> additional
...
+        // register resource bundles for reflection (they are apparently classes...)
+        reflectiveClass.produce(ReflectiveClassBuildItem.builder(Resources.class).build());
+        reflectiveClass.produce(ReflectiveClassBuildItem.builder(ResourceKeys.class).build());
+        reflectiveClass.produce(ReflectiveClassBuildItem.builder(SqljResources.class).build());
+        reflectiveClass.produce(ReflectiveClassBuildItem.builder(T2uResourceKeys.class).build());
+        reflectiveClass.produce(ReflectiveClassBuildItem.builder(T2uResources.class).build());
+        reflectiveClass.produce(ReflectiveClassBuildItem.builder(T2zResourceKeys.class).build());
+        reflectiveClass.produce(ReflectiveClassBuildItem.builder(T2zResources.class).build());
+        reflectiveClass.produce(ReflectiveClassBuildItem.builder(T4ResourceKeys.class).build());
+        reflectiveClass.produce(ReflectiveClassBuildItem.builder(T4Resources.class).build());
```
Comment (turing85) [inline extensions/jdbc/jdbc-db2/deployment/src/main/java/io/quarkus/jdbc/db2/deployment/JDBCDB2Processor.java:84]: I played around with this, and it seems we also need `oracle.net.mesg.Message`. @gsmet are you ok with me opening a PR and adding that class?
