### PR TITLE
Make the remote dev mode type more accessible

### LINKED ISSUE #14152: Remote-Dev triggers an entire redeployment(S2I Processor) with OpenShift Extension
**Describe the bug**
(Describe the problem clearly and concisely.)
Quarkus remote-dev always triggers an entire redeployment using the S2I processor rather than sending changed code when Quarkus application is deployed to OpenShift using OpenShift extension. This causes removing an existing environment variable(QUARKUS_LAUNCH_DEVMODE=true) in the DeploymentConfig so the remote-dev breaks. Furthermore, it takes quite a time to send changed code rather than using binary deployment.

**Expected behavior**
(Describe the expected behavior clearly and concisely.)
Sending only changed code just like using binary build(i.e. oc new-build, oc start-build, oc new-app) when I do livecoding.

**Actual behavior**
(Describe the actual behavior clearly and concisely.)
Rebuild an entire project via OpenShift extension then package it for redeployment. after that, the following error is happened when I try to live coding:

2021-01-04 15:46:29,661 ERROR [io.qua.ver.htt.dep.dev.HttpRemoteDevClient] (Remote dev client thread) Remote dev request failed: java.io.IOException: Server did not start a remote dev session
at io.quarkus.vertx.http.deployment.devmode.HttpRemoteDevClient$Session.doConnect(HttpRemoteDevClient.java:128)
at io.quarkus.vertx.http.deployment.devmode.HttpRemoteDevClient$Session.run(HttpRemoteDevClient.java:169)
at java.base/java.lang.Thread.run(Thread.java:832)

2021-01-04 15:46:29,662 ERROR [io.qua.ver.htt.dep.dev.HttpRemoteDevClient] (Remote dev client thread) Connection failed after 10 retries, exiting

This seems to be caused by removing "QUARKUS_LAUNCH_DEVMODE=true".

**To Reproduce**

Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific).

Or attach an archive containing the reproducer to the issue.

1. Use a getting-started project like helloword
2. Add an quarkus-openshift extension
3. Add the below configurations

**Configuration**
```properties
quarkus.package.type=mutable-jar
quarkus.live-reload.password=REPLACE_WITH_YOUR_PASSWORD
quarkus.live-reload.url=REPLACE_WITH_YOUR_ROUTE_URL
quarkus.container-image.build=true
quarkus.kubernetes-client.trust-certs=true
quarkus.kubernetes.deployment-target=openshift
quarkus.kubernetes.deploy=true
quarkus.openshift.expose=true
```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: OpenJDK 11
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.10.5.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 

**Additional context**
(Add any other context about the problem here.)

### PR DESCRIPTION
**Pull request by stuartwdouglas**
Also make sure that deployment is not triggered when
running the remote dev mode client.

Fixes #14152

### CODE REVIEW

File: independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/app/QuarkusBootstrap.java [hunk 1]
```diff
@@ -486,6 +486,8 @@ public Builder addClassLoaderEventListeners(List<ClassLoaderEventListener> class
     public enum Mode {
         DEV,
         TEST,
-        PROD;
+        PROD,
+        REMOTE_DEV_SERVER,
+        REMOTE_DEV_CLIENT;
```
Comment (aloubyansky) [inline independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/app/QuarkusBootstrap.java:491]: I was wondering whether the LaunchMode could be enhanced in this manner as well. That could make it less confusing for remote dev.

Comment (stuartwdouglas) [reply independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/app/QuarkusBootstrap.java:491]: I thought about this, but there is already lots of code that tests for specific launch modes. If we add additional dev mode types any existing code that checks if launchmode == DEV will break in remote dev mode.

Comment (aloubyansky) [reply independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/app/QuarkusBootstrap.java:491]: Isn't the remote dev mode represented as NORMAL? isn't it supposed to be checked by calling `isRemoteDev()` currently? DEVELOPMENT would remain as is.

Comment (stuartwdouglas) [reply independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/app/QuarkusBootstrap.java:491]: REMOTE_DEV_CLIENT is normal, REMOTE_DEV_SERVER is DEVELOPMENT

Comment (aloubyansky) [reply independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/app/QuarkusBootstrap.java:491]: Would adding only the REMOTE_DEV_CLIENT to LaunchMode and keeping DEVELOPMENT for actual dev mode launch be a bit less confusing? I don't see `DevModeType.REMOTE_SERVER_SIDE` being checked anywhere.

Comment (stuartwdouglas) [reply independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/app/QuarkusBootstrap.java:491]: If we add an extra LaunchMode we need to update everywhere that LaunchMode is used in every extension, including downstream platform extensions. Because remote dev is not heavily tested in isolation I think the end result would be lots of extensions not handling the REMOTE_DEV_CLIENT mode properly and remote dev being very broken.

This is not really a different launch mode, the client generates a production app, the server runs a development app, the only place where this really matters is in how you handle what happens after the app is generated (i.e. deployment/container image building).

**Review by aloubyansky — APPROVED** [review]
