### PR TITLE
Arc - Validate qualifiers for array typed member that lack @Nonbinding annotation

### LINKED ISSUE #49646: ClassCastException while creating Rest Client for annotations with primitive type array. example:io.micrometer.core.annotation.Timed
### Describe the bug

 
When using a custom CDI qualifier annotation that has a primitive array (e.g., int[], double[]) as a member, Quarkus Arc’s Qualifiers class fails with a ClassCastException. This happens because the hasQualifier method blindly casts arrays to Object[], which is invalid for primitive arrays.
 
I encountered this issue while using Micrometer’s `@Timed` annotation, which internally has primitive array members.

Quarkus fails to compare annotations with primitive array members in CDI qualifiers.
 
The exact exception:
 
 ```posh
java.lang.ClassCastException: class [D cannot be cast to class [Ljava.lang.Object;
([D and [Ljava.lang.Object; are in module java.base of loader 'bootstrap')
 (..
This occurs in io.quarkus.arc.impl.Qualifiers.hasQualifier(..)
```

### Expected behavior

The framework should correctly compare annotation members, including primitive arrays, without throwing a ClassCastException.
 
Both object arrays and primitive arrays should be handled safely.

### Actual behavior

A ClassCastException is thrown when a CDI qualifier has a primitive array member.
 
Bean resolution fails, and the application cannot start if such a qualifier is used.

### How to Reproduce?

Annotate any REST client with `io.micrometer.core.annotation.Timed` in Quarkus 3.25 and Java 21
 

### Output of `uname -a` or `ver`

PROD

### Output of `java -version`

21

### Quarkus version or git rev

3.25

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by manovotn**
Fixes #49646 

Arc now validates qualifiers, both discovered and registered synthetically, for all members that have array/annotation-valued types and are not annotated `@Nonbinding`. The error looks something like this:

> [ERROR]   Qualifier annotation 'io.quarkus.arc.test.validation.SyntheticQualifierWithBindingAnnotationTest$ToBeQualifier' contains a member 'value' with annotation-valued return type. All such members have to be annotated with @jakarta.enterprise.util.Nonbinding

### CODE REVIEW

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanDeployment.java [hunk 1]
```diff
@@ -188,6 +188,13 @@ public class BeanDeployment {
                     if (nonbindingMembers == null) {
                         nonbindingMembers = Collections.emptySet();
                     }
+                    for (MethodInfo mi : classInfo.methods()) {
+                        if (mi.returnType().kind().equals(Type.Kind.ARRAY) && !nonbindingMembers.contains(mi.name())) {
+                            throw new DefinitionException("Qualifier annotation '" + classInfo + "' contains a method '"
```
Comment (mkouba) [inline independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanDeployment.java]: I wonder if we should detect annotation-valued members as well...

Also I think that for annotations it's more common to use the term `member` instead of `method`.

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanDeployment.java [hunk 2]
```diff
@@ -854,6 +861,14 @@ private Map<DotName, ClassInfo> findQualifiers() {
             if (isExcluded(qualifierClass)) {
                 continue;
             }
+            // check that all array typed methods are @Nonbinding
+            for (MethodInfo mi : qualifierClass.methods()) {
+                if (mi.returnType().kind().equals(Type.Kind.ARRAY) && mi.annotation(DotNames.NONBINDING) == null) {
+                    throw new DefinitionException("Qualifier annotation '" + qualifierClass + "' contains a method '"
```
Comment (mkouba) [inline independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanDeployment.java]: Would it make sense to resuse the logic from above?

File: extensions/arc/deployment/src/test/java/io/quarkus/arc/test/stereotype/DoubleScopedStereotypeTestCase.java [hunk 3]
```diff
@@ -32,6 +35,7 @@ public void runTest() {
     @SessionScoped
     @RequestScoped
     @Stereotype
+    @Retention(RetentionPolicy.RUNTIME)
```
Comment (mkouba) [inline extensions/arc/deployment/src/test/java/io/quarkus/arc/test/stereotype/DoubleScopedStereotypeTestCase.java:38]: This apparently breaks the `DoubleScopedStereotypeTestCase` :thinking:

Comment (manovotn) [reply extensions/arc/deployment/src/test/java/io/quarkus/arc/test/stereotype/DoubleScopedStereotypeTestCase.java:38]: The `DoubleScopedStereotypeTestCase` wasn't really testing anything - without the retention annotation, the test was failing with unsatisfied dep instead of (expected) double scope detection.

The CI failures are from `BeanRegistrarTest` and I am looking into that as we speak.

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanDeployment.java (hunk 2 above)
Comment (manovotn) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanDeployment.java]: It would be only for the exception message which I considered but found awkward.
The detection logic is slightly  different as synthetic qualifiers don't inspect the annotation but instead the data provided by user.

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanDeployment.java (hunk 1 above)
Comment (manovotn) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanDeployment.java]: > I wonder if we should detect annotation-valued members as well...

Right, I forgot spec also mentions those.
I'll add that as well.

> Also I think that for annotations it's more common to use the term member instead of method.

Fair point, will change the message :+1:

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanDeployment.java (hunk 2 above)
Comment (mkouba) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanDeployment.java]: > which I considered but found awkward

Why? I would just add a private method like `DefinitionException newQualifierArrayValuedMemberException(ClassInfo qualifierClass, MethodInfo member)` to remove the duplicate error message...

File: extensions/arc/deployment/src/test/java/io/quarkus/arc/test/stereotype/DoubleScopedStereotypeTestCase.java (hunk 3 above)
Comment (manovotn) [reply extensions/arc/deployment/src/test/java/io/quarkus/arc/test/stereotype/DoubleScopedStereotypeTestCase.java:38]: So, the `BeanRegistrarTest` actually has a [qualifier](https://github.com/quarkusio/quarkus/blob/main/independent-projects/arc/tests/src/test/java/io/quarkus/arc/test/buildextension/beans/BeanRegistrarTest.java#L278) violating this new check :)

Comment (mkouba) [reply extensions/arc/deployment/src/test/java/io/quarkus/arc/test/stereotype/DoubleScopedStereotypeTestCase.java:38]: > So, the `BeanRegistrarTest` actually has a [qualifier](https://github.com/quarkusio/quarkus/blob/main/independent-projects/arc/tests/src/test/java/io/quarkus/arc/test/buildextension/beans/BeanRegistrarTest.java#L278) violating this new check :)

Ah, it was "fixed" five years ago :facepalm:

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanDeployment.java (hunk 2 above)
Comment (manovotn) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanDeployment.java]: I have extracted the whole detection into a separate method

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanDeployment.java (hunk 1 above)
Comment (manovotn) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanDeployment.java]: I have added a check for the annotation-valued members as well as automated tests for both - discovered and registered qualifiers.
The logic is bit more complex now so I extracted it into a separate method.

File: extensions/arc/deployment/src/test/java/io/quarkus/arc/test/stereotype/DoubleScopedStereotypeTestCase.java (hunk 3 above)
Comment (manovotn) [reply extensions/arc/deployment/src/test/java/io/quarkus/arc/test/stereotype/DoubleScopedStereotypeTestCase.java:38]: > This apparently breaks the `DoubleScopedStereotypeTestCase`

Actually, this one had another problem too - it was expecting deployment exception when in reality we throw definition exception if two scopes are present. I'll correct that as well.

**Review by mkouba — APPROVED** [review]

**Comment by manovotn** [comment]
Hm, the red CI is indeed related. 
It appears we have usage in place for the array-valued member of annotation in `TenantFeature`.

>  Caused by: jakarta.enterprise.inject.spi.DefinitionException: Qualifier annotation 'io.quarkus.oidc.TenantFeature' contains a member 'value' with array-valued return type. All such members have to be annotated with @jakarta.enterprise.util.Nonbinding

This was added as part of https://github.com/quarkusio/quarkus/pull/48529
@michalvavrik @sberyozkin can the member value of this annotation be marked as [`@Nonbinding`](https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0#qualifier_annotation_members) or is that a problem?

**Comment by michalvavrik** [comment]
> > Caused by: jakarta.enterprise.inject.spi.DefinitionException: Qualifier annotation 'io.quarkus.oidc.TenantFeature' contains a member 'value' with array-valued return type. All such members have to be annotated with @jakarta.enterprise.util.Nonbinding
> 
> This was added as part of #48529 @michalvavrik @sberyozkin can the member value of this annotation be marked as [`@Nonbinding`](https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0#qualifier_annotation_members) or is that a problem?

I think the only reason it remains a qualifier registered by a build item is that we couldn't exactly agree on adjusting one test. We use `io.quarkus.arc.InjectableBean#getQualifiers` but it should be fine to switch to inspection of a class annotations as we think that users don't have many of `TenantFeature` annotations. @sberyozkin is not around and I am busy, can this wait 2 weeks? If `Nonbinding` fixes CI, I am fine using it, but it doesn't seem like a proper solution.

**Comment by michalvavrik** [comment]
I looked up `@Nonbinding` explanation in https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0#qualifier_annotation_members and considering how we use the annotation, I think it is safe to annotate it with that. Let's try it.

**Comment by michalvavrik** [comment]
But there could be one test that will start failing, I am not sure if it will be the same case as when we tried to drop it as a qualifier. You can try and see ....

**Comment by manovotn** [comment]
> I looked up `@Nonbinding` explanation in https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0#qualifier_annotation_members and considering how we use the annotation, I think it is safe to annotate it with that. Let's try it.

I linked it in the initial comment but I probably should have expanded on it.
The annotation will still work as a qualifier, but its member value is disregarded when performing typesafe resolution,
I'll give it a spin tomorrow, I just wanted to ask first as the commit changing it seemed deliberate on having the array as binding :)

**Comment by michalvavrik** [comment]
> I linked it in the initial comment but I probably should have expanded on it.

yeah, I mentioned after I commented :-) 

> The annotation will still work as a qualifier, but its member value is disregarded when performing typesafe resolution

sounds alright as we don't really use it as a qualifier in practice anymore

**Comment by manovotn** [comment]
The CI doesn't seem to indicate it would cause any issues :tada:

File: independent-projects/arc/tests/src/test/java/io/quarkus/arc/test/validation/SyntheticQualifierWithBindingAnnotationTest.java [hunk 4]
```diff
@@ -0,0 +1,65 @@
...
+    }
+
+    @Dependent
+    @ToBeQualifier(@SomeAnnotation("foo"))
+    static class Alpha {
+
+    }
+
+    // not marked as @Qualifier, instead it is added via registrar
+    @Qualifier
```
Comment (Ladicek) [inline independent-projects/arc/tests/src/test/java/io/quarkus/arc/test/validation/SyntheticQualifierWithBindingAnnotationTest.java:55]: You really say this is _not marked as @Qualifier_? :-)

Comment (manovotn) [reply independent-projects/arc/tests/src/test/java/io/quarkus/arc/test/validation/SyntheticQualifierWithBindingAnnotationTest.java:55]: :facepalm: 
Sending a PR to fix it...
