### PR TITLE
ArC - improve automatic registration for reflection

### LINKED ISSUE #6898: Metrics extension causes issues with Resteasy in native runtime
**Describe the bug**
I followed the [Creating Your First Application](https://quarkus.io/guides/getting-started) guide and created a simple JAX-RS/Resteasy app. I have my code uploaded on [Github](https://github.com/saharsh-samples/sample-quarkus-app). The app runs fine doing a JVM based build. However if I do a native build using the [multi stage Dockerfile](https://quarkus.io/guides/building-native-image#creating-a-container-with-a-multi-stage-docker-build), I start getting MethodNotFoundException errors. After some debugging it looks like the issue is inclusion of the metrics extension. Creating the app as is with the exception of adding the metrics stuff causes the native app to behave just fine.

**Expected behavior**
Runtime of native app behaves the way runtime of the jvm app does.

**Actual behavior**
Any HTTP requests (including readiness health check) results in a MethodNotFoundException in the runtime of the native app.

**To Reproduce**
1. Clone [my repo](https://github.com/saharsh-samples/sample-quarkus-app)
2. Build native executable for the app (e.g. `./mvnw clean package -Pnative -Dquarkus.native.container-runtime=podman`)
3. Run the app (will run on port 8080) - `./target/sample-quarkus-app-1.0-SNAPSHOT-runner &`
4. Consume the app's endpoints:
    - curl localhost:8080/api/values (causes exception - see [relevant code](https://github.com/saharsh-samples/sample-quarkus-app/blob/master/src/main/java/org/saharsh/samples/quarkus/resources/ValuesResource.java))
    - curl localhost:8080/health/ready (causes exception - see [relevant code](https://github.com/saharsh-samples/sample-quarkus-app/blob/master/src/main/java/org/saharsh/samples/quarkus/health/ReadinessCheck.java))
    - curl curl localhost:8080/health/live (works OK - see [relevant code](https://github.com/saharsh-samples/sample-quarkus-app/blob/master/src/main/java/org/saharsh/samples/quarkus/health/LivenessCheck.java))

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `Linux sahsingh 5.3.16-300.fc31.x86_64 #1 SMP Fri Dec 13 17:59:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
 - Output of `java -version`: 
```
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)
```
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: `1.2.0.Final`

**Additional context**
(Add any other context about the problem here.)

### PR DESCRIPTION
**Pull request by mkouba**
- previously we did not register constructor for reflection when an @AroundConstruct interceptor was used
- resolves #6898

### CODE REVIEW

**Comment by mkouba** [comment]
@geoand  @saharshsingh It would be great if you could review/test this PR ;-).

**Comment by gsmet** [comment]
Any chance we could add a test in the Metrics extension IT? Or it's too complicated?

**Comment by geoand** [comment]
Yeah, a small test would be great :)

**Comment by mkouba** [comment]
Well, we would need a test for native image only... I can try to prepare something later today.

**Comment by geoand** [comment]
Maybe just add something in the `main` integration test?

**Comment by mkouba** [comment]
@geoand I'm not quite sure I want to tease this monster but yeah, I can try it... ;-)

**Comment by mkouba** [comment]
`DummyGauge` added to the main integration test. This bean should demonstrate the issue.

**Review by geoand — APPROVED** [review]

File: integration-tests/main/src/main/java/io/quarkus/it/metrics/DummyGauge.java [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+
+/**
+ * The purpose of this bean is to test that ArC automatically registers the constructor for reflection if an
+ * {@link AroundConstruct} interceptors is used. We use a dedicated bean to make sure the class is not registered by another
+ * extension, ie. by resteasy in case of JAX-RS resource.
+ * 
+ * See https://github.com/quarkusio/quarkus/issues/6898
+ */
+@ApplicationScoped
+public class DummyGauge {
```
Comment (jmartisk) [inline integration-tests/main/src/main/java/io/quarkus/it/metrics/DummyGauge.java]: Shouldn't we add an assertion in `io.quarkus.it.main.MetricsTestCase` or somewhere to make sure the gauge really gets registered?

Comment (mkouba) [reply integration-tests/main/src/main/java/io/quarkus/it/metrics/DummyGauge.java]: Hm, we should. But we will have to add `@RegisterForReflection` too, due to https://github.com/quarkusio/quarkus/issues/6993. @jmartisk would you care to add this assertion to my PR? ;-)

Comment (jmartisk) [reply integration-tests/main/src/main/java/io/quarkus/it/metrics/DummyGauge.java]: Oh, I thought the changes in this PR mean we don't need that annotation anymore. Ok.
How do I add something to your PR? I don't think I have permissions for that.

Comment (mkouba) [reply integration-tests/main/src/main/java/io/quarkus/it/metrics/DummyGauge.java]: Nope, this PR merely fixes the problem in ArC where we did not register the constructor for reflection if `@AroundConstruct` was used...

Comment (geoand) [reply integration-tests/main/src/main/java/io/quarkus/it/metrics/DummyGauge.java]: @jmartisk as a member of the project you can push changes to any PR.

Comment (jmartisk) [reply integration-tests/main/src/main/java/io/quarkus/it/metrics/DummyGauge.java]: But how? Which remote repo and branch should I push to? It won't allow me to push into Martin's fork.
Per https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/committing-changes-to-a-pull-request-branch-created-from-a-fork it seems it could work if I had push access to Quarkus repo, which I don't

Comment (geoand) [reply integration-tests/main/src/main/java/io/quarkus/it/metrics/DummyGauge.java]: I am pretty sure you and I have the same push access and pushing to a PR works for me.
This is what I do:

* Add a git remote for the user's fork (using ssh, not https as the protocol) - for example `foo`
* Check out the PR in a branch, say `pull/1234`
* Make changes and commit
* Push like so: `git push foo pull/1234:name-of-branch-in-users-fork`

Comment (jmartisk) [reply integration-tests/main/src/main/java/io/quarkus/it/metrics/DummyGauge.java]: Well, that's what I did and receive this on push
```
ERROR: Permission to mkouba/quarkus.git denied to jmartisk.
```
The document explicitly says that I can do this if the PR is opened against a repository where I have push access to - that's probably the issue.
Anyway I pushed it to my own branch https://github.com/jmartisk/quarkus/commit/7025a983a5aba54e5ba5c7bb6eba8d88199fe3e0 so I guess you guys can cherry-pick it

Comment (mkouba) [reply integration-tests/main/src/main/java/io/quarkus/it/metrics/DummyGauge.java]: Ok, will do. Apparently you don't have the permissions. Thanks!

**Comment by gsmet** [comment]
@mkouba @jmartisk everybody happy? We can merge?

**Comment by jmartisk** [comment]
+1
