### PR TITLE
Fail to start when service binding is enabled and Kafka boostrap servers not set

### LINKED ISSUE #16682: ServiceBinding for Kafka should not use localhost values if no bindings are present and fail fast when starting with invalid values
## Describe the bug

The typical approach for Kubernetes is to fail fast. If there is Kubernetes service binding plugin used proper behavior would 
be to look for the values and if they are not present fail application fast. 

This way application can stop etc. Currently app will try to connect to localhost (which is due to values being undefined).
My take is that I would love this to be consistent with behaviour without service binding plugin present (without kafka.* properties/profile/env app will fail to start)

(Note this is improvement and not blocking anything right now)

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #16682

### CODE REVIEW

File: extensions/kafka-client/runtime/src/main/java/io/quarkus/kafka/client/runtime/KafkaRecorder.java [hunk 1]
```diff
@@ -71,4 +74,16 @@ private static File extractLibraryFile(URL library, String name) {
         return extractedLibFile;
     }
 
+    public void checkBoostrapServers() {
+        Config config = ConfigProvider.getConfig();
+        Boolean serviceBindingEnabled = config.getValue("quarkus.kubernetes-service-binding.enabled", Boolean.class);
+        if (!serviceBindingEnabled) {
+            return;
+        }
+        Optional<String> boostrapServersOptional = config.getOptionalValue("kafka.bootstrap.servers", String.class);
```
Comment (cescoffier) [inline extensions/kafka-client/runtime/src/main/java/io/quarkus/kafka/client/runtime/KafkaRecorder.java:83]: Hum... that won't work when using multiple brokers. But let's forget this for now.

**Review by cescoffier — APPROVED** [review]

File: extensions/kafka-client/runtime/src/main/java/io/quarkus/kafka/client/runtime/KafkaRecorder.java (hunk 1 above)
Comment (geoand) [reply extensions/kafka-client/runtime/src/main/java/io/quarkus/kafka/client/runtime/KafkaRecorder.java:83]: Good point! Something to keep in mind for the future

Comment (geoand) [reply extensions/kafka-client/runtime/src/main/java/io/quarkus/kafka/client/runtime/KafkaRecorder.java:83]: Good point! Something to keep in mind for the future
