### PR TITLE
Fix dev console paths. Add Builder to HttpRootPathBuildItem

### LINKED ISSUE #15535: HttpRootPathBuildItem has changed his `path` format several times.
**Describe the bug**

On version 1.11.1.Final or  1.12.0.Final `HttpRootPathBuildItem` returns a path like  `http://test-http-advanced-pablo-http-advanced.apps.ocp46.dynamic.quarkus/api` but on version 1.11.5.Final or 1.12.1.Final  `HttpRootPathBuildItem` returns a path like  `http://test-http-advanced-pablo-http-advanced.apps.ocp46.dynamic.quarkus/api/` 

**note** that on version 1.11.5.Final the paths end with "/".

I am not sure if these inconsistencies are related to this commit: https://github.com/quarkusio/quarkus/commit/e0f8ec94ef9b6882a60a4f7299c9db9b17893fe2

I think that should not end with "/" at the end. 

Could you clarify the expected behavior?

### PR DESCRIPTION
**Pull request by ebullient**
Resolves #15535 regarding dev console usage

### CODE REVIEW

File: extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/RouteBuildItem.java [hunk 1]
```diff
@@ -192,17 +224,39 @@ public Builder displayOnNotFoundPage(String notFoundPageTitle) {
...
+        public Builder routeConfigKey(String attributeName) {
+            this.routeConfigKey = attributeName;
+            return this;
+        }
+
         public RouteBuildItem build() {
             return new RouteBuildItem(this, RouteType.APPLICATION_ROUTE, false);
         }
 
+        protected ConfiguredPathInfo getRouteConfigInfo() {
```
Comment (kenfinnigan) [inline extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/RouteBuildItem.java:249]: Wondering if it's beneficial to pass a value for "absolute" or not into the Builder so that this method doesn't need to be overridden with the same content in the two children?

File: extensions/smallrye-graphql/deployment/src/main/resources/dev-templates/embedded.html [hunk 2]
```diff
@@ -1,7 +1,7 @@
-<a href="{config:property('quarkus.smallrye-graphql.root-path')}/schema.graphql" class="badge badge-light">
+<a href="{config:http-path('quarkus.smallrye-graphql.root-path')}/schema.graphql" class="badge badge-light">
   <i class="fa fa-project-diagram fa-fw"></i>
   GraphQL Schema</a>
 <br>
-<a href="{frameworkRootPath}{config:property('quarkus.smallrye-graphql.ui.root-path')}/" class="badge badge-light">
+<a href="{config:http-path('quarkus.smallrye-graphql.ui.root-path')}/" class="badge badge-light">
```
Comment (kenfinnigan) [inline extensions/smallrye-graphql/deployment/src/main/resources/dev-templates/embedded.html:5]: Does this mean it hangs off the HTTP root and not the framework root?

I'm not sure what `config:http-path()` converts to so I could be missing it

**Review by kenfinnigan — CHANGES_REQUESTED** [review]

File: extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/RouteBuildItem.java (hunk 1 above)
Comment (ebullient) [reply extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/RouteBuildItem.java:249]: It's a little more complicated than that because of where/how the absolutely resolved path is known/stored

File: extensions/smallrye-graphql/deployment/src/main/resources/dev-templates/embedded.html (hunk 2 above)
Comment (kenfinnigan) [reply extensions/smallrye-graphql/deployment/src/main/resources/dev-templates/embedded.html:5]: cool, thanks

Comment (ebullient) [reply extensions/smallrye-graphql/deployment/src/main/resources/dev-templates/embedded.html:5]: This was _added_ in this PR. See DevConsoleProcessor line 325-ish

File: extensions/smallrye-health/deployment/src/main/java/io/quarkus/smallrye/health/deployment/SmallRyeHealthProcessor.java [hunk 3]
```diff
@@ -409,9 +402,8 @@ void registerUiExtension(
                         "quarkus.smallrye-health.root-path-ui was set to \"/\", this is not allowed as it blocks the application from serving anything else.");
             }
 
-            String healthPath = httpRootPath.resolvePath(nonApplicationRootPathBuildItem.resolvePath(healthConfig.rootPath));
```
Comment (kenfinnigan) [inline extensions/smallrye-health/deployment/src/main/java/io/quarkus/smallrye/health/deployment/SmallRyeHealthProcessor.java:411]: good catch

File: extensions/swagger-ui/deployment/src/main/java/io/quarkus/swaggerui/deployment/SwaggerUiProcessor.java [hunk 4]
```diff
@@ -93,9 +93,8 @@ public void getSwaggerUiFinalDestination(
                         "quarkus.swagger-ui.path was set to \"/\", this is not allowed as it blocks the application from serving anything else.");
             }
 
-            String openApiPath = httpRootPathBuildItem.resolvePath(nonApplicationRootPathBuildItem.resolvePath(openapi.path));
```
Comment (kenfinnigan) [inline extensions/swagger-ui/deployment/src/main/java/io/quarkus/swaggerui/deployment/SwaggerUiProcessor.java:96]: Can `httpRootPathBuildItem` be removed from the method parameters as well?

Comment (ebullient) [reply extensions/swagger-ui/deployment/src/main/java/io/quarkus/swaggerui/deployment/SwaggerUiProcessor.java:96]: yes. thought I had,

**Review by kenfinnigan — APPROVED** [review]
