### PR TITLE
Fix HTTP Security policies when OIDC tenant is selected with the @Tenant annotation on Jakarta REST resources

### LINKED ISSUE #37485: OIDC multi-tenancy @Tenant annotation not selecting tenant
### Describe the bug

Using `@Tenant` annotation on controller or controller method does not select the OIDC tenant.

### Expected behavior

```properties
quarkus.oidc.auth-server-url=https://example.com

quarkus.oidc.foo.auth-server-url=https://example.com/foo

quarkus.oidc.bar.auth-server-url=https://example.com/bar
```

```java
...
@Path("foo")
@Tenant("foo")
public class FooController {
    @Path("")
    @Get()
    public void foo() {
    }
}
```

```java
...
@Path("bar")
@Tenant("bar")
public class BarController {
    @Path("")
    @Get()
    public void bar() {
    }
}
```

GET "/foo"
should resolve tenant foo and use https://example.com/foo as authorization server

### Actual behavior

GET "/foo"
resolves default tenant and uses https://example.com as authorization server

### How to Reproduce?

see expected behavior

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

11

### Quarkus version or git rev

3.4.3,3.6.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle 8.3

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by michalvavrik**
- Fixes: #37485
- Unblocks https://github.com/quarkusio/quarkus/pull/36504

We are in the difficult situation with HTTP Security policies as we need to run authentication and authorization as the first thing, but when the policies are used with the Jakarta REST stack and authentication feature that require endpoint match is used, we would need to postpone authN/authZ to when RESTEasy Reactive starts processing. That can be done, but there can (and are) filters with higher priority that can preceed RR processing and needs to be secured as well. Just imagine that request is consumed by gRPC but we postponed check to JAX-RS phase. That is why for now, this PR propose explicitly marking HTPT Security policies that are only applied on JAX-RS. This feature is closely couple with use cases - it will work for `@Tenant` and for other annotations resolved to `EagerSecurityInterceptor`s, but it doesn't make sense and is not supported to just delay it for no reason (in short: we need build time detection of annotations to know we should add respective REST handlers).

### CODE REVIEW

**Comment by sberyozkin** [comment]
Thanks @michalvavrik, I did look earlier, and thought it was good, but I'll need to go through it again, thanks

**Comment by michalvavrik** [comment]
> Thanks @michalvavrik, I did look earlier, and thought it was good, but I'll need to go through it again, thanks

If you have any questions, please shoot. Personally, I'd suggest area covered by `EagerSecurityHandler` and `EagerSecurityFilter` has already had good test coverage before this PR, therefore I have confidence I'm not breaking anything. Please take your time.

**Comment by gsmet** [comment]
Probably a good idea to have @geoand having a look.

**Comment by michalvavrik** [comment]
> Probably a good idea to have @geoand having a look.

@geoand please have a look if you find a time

**Comment by geoand** [comment]
Sure, I'll have a look tomorrow

**Comment by geoand** [comment]
RR part LGTM

**Comment by michalvavrik** [comment]
> RR part LGTM

Thanks for the review

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/PolicyMappingConfig.java [hunk 1]
```diff
@@ -67,4 +67,30 @@ public class PolicyMappingConfig {
...
+    /**
+     * Specifies additional criteria on paths that should be checked.
+     */
+    public enum AppliesTo {
+        /**
+         * Apply on all matching paths.
+         */
+        ALL,
+        /**
+         * Declares the permission check is only applied on the Jakarta REST request paths.
```
Comment (sberyozkin) [inline extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/PolicyMappingConfig.java:86]:
```suggestion
         * Declares that a permission check must only be applied on the Jakarta REST request paths.
```

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/PolicyMappingConfig.java [hunk 2]
```diff
@@ -67,4 +67,30 @@ public class PolicyMappingConfig {
...
+         * This option must only be used in cases when authentication must happen after Jakarta REST endpoint
```
Comment (sberyozkin) [inline extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/PolicyMappingConfig.java:87]:
```suggestion
         * Use this option to delay the permission check if an authentication mechanism is chosen with an annotation on the matching Jakarta REST endpoint.
```

Not sure it reads great but I'm trying to clarify somehow why exactly this option must be selected

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/PolicyMappingConfig.java [hunk 3]
```diff
@@ -67,4 +67,30 @@ public class PolicyMappingConfig {
...
+         * has been matched with the HTTP request path. Only use this option when a permission check should only secure
+         * Jakarta REST endpoint annotated with one of following annotations:
```
Comment (sberyozkin) [inline extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/PolicyMappingConfig.java:89]:
```suggestion
         * This option must be used if the following REST endpoint annotations are used:
```

File: docs/src/main/asciidoc/security-openid-connect-multitenancy.adoc [hunk 4]
```diff
@@ -724,6 +724,18 @@ public class HelloResource {
 ----
 <1> The `io.quarkus.oidc.Tenant` annotation must be placed on either the resource class or resource method.
 
+[[TIP]]
+In the example above, authentication of the `sayHello` endpoint is enforced with the `@Authenticated` annotation.
+Alternatively, you can define the xref:security-authorize-web-endpoints-reference.adoc#authorization-using-configuration[HTTP Security policy] like in the example below:
```
Comment (sberyozkin) [inline docs/src/main/asciidoc/security-openid-connect-multitenancy.adoc:729]:
```suggestion
Alternatively, if you use an xref:security-authorize-web-endpoints-reference.adoc#authorization-using-configuration[HTTP Security policy] to secure the endpoint, then, for the `@Tenant` annotation be effective,  you must delay this policy's permission check as shown in the example below:
```

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/PolicyMappingConfig.java [hunk 5]
```diff
@@ -67,4 +67,30 @@ public class PolicyMappingConfig {
...
+         * <ul>
+         * <li>`io.quarkus.oidc.Tenant` annotation which selects OIDC tenant</li>
```
Comment (sberyozkin) [inline extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/PolicyMappingConfig.java:91]:
```suggestion
         * <li>`io.quarkus.oidc.Tenant` annotation which selects an OIDC authentication mechanism with an OIDC tenant identifier</li>
```

File: docs/src/main/asciidoc/security-openid-connect-multitenancy.adoc (hunk 4 above)
Comment (michalvavrik) [reply docs/src/main/asciidoc/security-openid-connect-multitenancy.adoc]: I've tried to avoid using word `delay` as I think there can be negative feeling about _delaying security policies_ but it's true, that was it does and your suggestion makes things clearer, so I'll change it. Thank you

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/PolicyMappingConfig.java (hunk 2 above)
Comment (michalvavrik) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/PolicyMappingConfig.java]: Yeah I get it. I tried to avoid delay for negative connotations, but now I can see it's fine. Let's use your suggestion.

**Comment by sberyozkin** [comment]
Thanks @michalvavrik Let me do one more round in the next few days, enjoy the weekend.

**Comment by sberyozkin** [comment]
@michalvavrik I've looked again, I believe a good part of this PR is about the general refactoring as well, the code related checking if the JAXRS permission checker should be applied appears to be quite simple, thanks

**Review by sberyozkin — APPROVED** [review]
