### PR TITLE
Ensure that ServerStringMessageBodyHandler doesn't affect build time resolution of builders

### LINKED ISSUE #14720: Resteasy Reactive detects multiple writers, but only one response type is present
**Describe the bug**
I have a GET method annotated with `@Produces(MediaType.APPLICATION_JSON)`.
In the Score Console it says however that I have 2 writers for this method:
```
[io.quarkus.resteasy.reactive.jackson.runtime.serialisers.JacksonMessageBodyWriter@5a21df38, 
org.jboss.resteasy.reactive.server.providers.serialisers.ServerStringMessageBodyHandler@7a97f70c]
```

This negativly affects the score of this method. See screenshot.

**Expected behavior**
RR should not detect a simple Produces(MediaType.APPLICATION_JSON) as multiple writers.

**To Reproduce**

1. Download the reproducer
2. mvn quarkus:dev
3. Go to http://localhost:8080/q/dev/io.quarkus.quarkus-resteasy-reactive/scores

**Screenshots**
image

Environment (please complete the following information):

* Output of uname -a or ver:
Linux martin 5.8.0-41-generic #46~20.04.1-Ubuntu SMP Mon Jan 18 17:52:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* Output of java -version:
openjdk 11.0.7 2020-04-14 LTS
OpenJDK Runtime Environment Zulu11.39+15-CA (build 11.0.7+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.39+15-CA (build 11.0.7+10-LTS, mixed mode)
* Quarkus version or git rev:
1.11.1.Final
* Build tool (ie. output of mvnw --version or gradlew --version):
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/martin/.sdkman/candidates/maven/current
Java version: 11.0.7, vendor: Azul Systems, Inc., runtime: /home/martin/.sdkman/candidates/java/11.0.7-zulu
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.8.0-41-generic", arch: "amd64", family: "unix"

### PR DESCRIPTION
**Pull request by geoand**
By making certain writers extend AllWriteableMessageBodyWriter we can be certain that even in the presense
of multiple writers, RESTEasy Reactive can optimize itself to use only the first one

Fixes: #14720

### CODE REVIEW

File: independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/startup/RuntimeResourceDeployment.java [hunk 1]
```diff
@@ -366,6 +364,16 @@ public RuntimeResource buildResourceMethod(ResourceClass clazz,
         return runtimeResource;
     }
 
+    private boolean isSingleEffectiveWriter(List<MessageBodyWriter<?>> buildTimeWriters) {
+        if (buildTimeWriters.size() == 1) { // common case of single writer
+            return true;
+        }
+
+        // in the where the first Writer is an instance of AllWriteableMessageBodyWriter,
```
Comment (gsmet) [inline independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/startup/RuntimeResourceDeployment.java:372]:
```suggestion
        // in the case where the first Writer is an instance of AllWriteableMessageBodyWriter,
```

File: independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/spi/ServerMessageBodyWriter.java [hunk 2]
```diff
@@ -15,4 +16,22 @@
 
     void writeResponse(T o, Type genericType, ServerRequestContext context) throws WebApplicationException, IOException;
 
+    /**
+     * A special super-class of MessageBodyWriters that accepts all types of input.
+     * The main purpose of this class is to allow runtime code to discard
```
Comment (gsmet) [inline independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/spi/ServerMessageBodyWriter.java:21]:
```suggestion
     * The main purpose of this class is to allow runtime code
```

File: independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/startup/RuntimeResourceDeployment.java [hunk 3]
```diff
@@ -366,6 +364,16 @@ public RuntimeResource buildResourceMethod(ResourceClass clazz,
...
+        // it doesn't matter that we have multiple writers as the first will also always be used to serialize
```
Comment (gsmet) [inline independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/startup/RuntimeResourceDeployment.java:373]:
```suggestion
        // it doesn't matter that we have multiple writers as the first one will always be used to serialize
```

**Review by gsmet — DISMISSED** [review]
Spotted some small issues in the comments.

**Comment by gsmet** [comment]
@geoand should we backport it or it's not worth it?

**Comment by geoand** [comment]
We probably should as it can affect performance in a small way.
Also as reported, it has a negative psychological effect on users as for even simple cases there is nothing they can do to get the maximum out of RESTEasy Reactive

File: independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/spi/ServerMessageBodyWriter.java [hunk 4]
```diff
@@ -15,4 +16,22 @@
...
 
+    /**
+     * A special super-class of MessageBodyWriters that accepts all types of input.
+     * The main purpose of this class is to allow runtime code
+     * to optimize for the case when there are multiple providers determined at build time
+     * but the first one will always be used
+     */
+    abstract class AllWriteableMessageBodyWriter implements ServerMessageBodyWriter<Object> {
+
+        public final boolean isWriteable(Class<?> type, Type genericType, ResteasyReactiveResourceInfo target,
```
Comment (gsmet) [inline independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/spi/ServerMessageBodyWriter.java:27]: Could you add the `@Override` annotation?

File: independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/spi/ServerMessageBodyWriter.java [hunk 5]
```diff
@@ -15,4 +16,22 @@
...
+                MediaType mediaType) {
+            return true;
+        }
+
+        public final boolean isWriteable(Class<?> type, Type genericType,
```
Comment (gsmet) [inline independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/spi/ServerMessageBodyWriter.java:32]: Same here.

**Review by gsmet — DISMISSED** [review]
Added a minor gripe. Otherwise it looks good to go.

**Comment by stuartwdouglas** [comment]
LGTM

**Review by stuartwdouglas — APPROVED** [review]

**Review by gsmet — APPROVED** [review]
