### PR TITLE
Qute message bundles - fix application class predicate

### LINKED ISSUE #20064: io.quarkus.qute.i18n.MessageBundle annotated class *__Bundle not found for multi-module gradle project in test mode
### Describe the bug

Kind of related to [this](https://github.com/quarkusio/quarkus/issues/20063)

In a similar multi-module gradle setup, 
when we use a @MessageBundle annotated class

@MessageBundle(value = "alert")
public interface AlertMessages {

    @Message("")
    String withoutParams();

    @Message("")
    String withParams(String name);
}
with several localized implementations generated from the provided messages/alert_xx.properties files
we get the following error when trying to run the integration tests in the `integration-test` sub-module  in test mode
> Caused by: java.lang.NoClassDefFoundError: org/acme/AlertMessages_Bundle

This error does not affect single module projects.

### Expected behavior

The integration tets should be able to be executed in test mode as it happens in a single module project.

### Actual behavior

The application fails to start in test mode

> Caused by: java.lang.RuntimeException: Failed to start quarkus
...
> Caused by: java.lang.NoClassDefFoundError: org/acme/AlertMessages_Bundle

### How to Reproduce?

clone the following repo https://github.com/nikosk686/quarkus-message-bundle-poc
checkout the `2.2.0-multi-module-integration-tests-error` branch
and try to run the test located in the `integration-test` sub-module

You can also check the master branch which is a single module application and test runs correctly.

### Output of `uname -a` or `ver`

Linux dell-desktop 5.10.0-1045-oem #47-Ubuntu SMP Wed Aug 18 10:41:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.10" 2021-01-19 LTS OpenJDK Runtime Environment Corretto-11.0.10.9.1 (build 11.0.10+9-LTS) OpenJDK 64-Bit Server VM Corretto-11.0.10.9.1 (build 11.0.10+9-LTS, mixed mode)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.2.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 6.9

### Additional information

The problem is not present in quarkus v1 (run the test in the `integration-test` sub-module in  the `1.13.7-working-single-module` branch of the above repo, it should pass)

### PR DESCRIPTION
**Pull request by mkouba**
- resolves #20064

### CODE REVIEW

File: extensions/qute/deployment/src/main/java/io/quarkus/qute/deployment/MessageBundleProcessor.java [hunk 1]
```diff
@@ -1041,8 +1035,7 @@ public boolean test(String name) {
             }
             // E.g. to match the bundle class generated for a localized file; org.acme.Foo_en -> org.acme.Foo
             className = additionalClassNameSanitizer.apply(className);
-            return applicationArchives.containingArchive(className) != null
-                    || GeneratedClassGizmoAdaptor.isApplicationClass(name);
+            return GeneratedClassGizmoAdaptor.isApplicationClass(className);
```
Comment (mkouba) [inline extensions/qute/deployment/src/main/java/io/quarkus/qute/deployment/MessageBundleProcessor.java:1038]: The main part of the fix is `GeneratedClassGizmoAdaptor.isApplicationClass(name)` -> `GeneratedClassGizmoAdaptor.isApplicationClass(className)`!

**Review by gastaldi — APPROVED** [review]
LGTM

**Review by geoand — APPROVED** [review]

**Comment by geoand** [comment]
I assume this should be backported, right?
