### PR TITLE
OpenAPI: Always run OpenIDConnectSecurityFilter at runtime

### LINKED ISSUE #38101: smallrye-openapi property `oidc-open-id-connect-url` might not be fixed at build time
### Describe the bug

Openapi spec requires (or at least, strict openapi spec validators require) the `components.securitySchemes.SecurityScheme.openIdConnectUrl` value to be present in the openapi spec. This can be provided at build time by the property described in this swagger-ui [doc](https://quarkus.io/guides/openapi-swaggerui#quarkus-smallrye-openapi_quarkus.smallrye-openapi.oidc-open-id-connect-url)

We might want to provide different urls depending on the deployment environment or the same app, without requiring rebuilding the whole app specifically per environment. Making it runtime-bound would fix the problem easily.

But there is maybe something more to this issue:

We are actually using the OIDC extension here together with openapi extension so we are setting up the `QUARKUS_OIDC_AUTH_SERVER_URL` env var (or equivalent property) which is basically bound at runtime. This feature is highly correlated to the property mentioned in the title, I think there might be something extra to be done here like automatically setting up the openIdConnectUrl in the spec when using the oidc auth server url .

### Expected behavior

The OpenApi spec has the runtime provided `openIdConnectUrl` (ex: https://example.com)

```
    servers:
      - url: https://api.example.com/v2
    components:
      securitySchemes:
        openId:
      type: openIdConnect
      openIdConnectUrl: https://example.com/.well-known/openid-configuration
```

### Actual behavior

There is no way to provide the openIdConnectUrl at runtime.

### How to Reproduce?

Create a project with oidc: https://quarkus.io/guides/security-oidc-bearer-token-authentication-tutorial
and some rest endpoints or openapi spec.
Then add the openapi extension (`./mvnw quarkus:add-extension -Dextensions='quarkus-smallrye-openapi'`) to produce an openapi spec

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

3.6.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by MikeEdgar**
Closes #38101 

The referenced issue is resolved by ensuring that the OpenAPI document will use the runtime value of `quarkus.oidc.auth-server-url`, regardless of the presence of security annotations in the application.

Also, there is some clean-up/re-factoring of some pieces of the OpenAPI processor a change to update the auto-security scheme if it is already present under the same name/key rather than overwriting an existing one that may have already been provided by the user via the `OASModelReader` or static model.

### CODE REVIEW

File: extensions/smallrye-openapi/deployment/src/test/java/io/quarkus/smallrye/openapi/test/jaxrs/OIDCSecurityAutoAddTestTest.java [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+                                    + "quarkus.smallrye-openapi.security-scheme-description=OIDC Authentication\n"
+                                    + "quarkus.smallrye-openapi.oidc-open-id-connect-url=BUILD-TIME-OVERRIDDEN\n"
+                                    + "quarkus.http.auth.permission.\"oidc\".policy=authenticated\n"
+                                    + "quarkus.http.auth.permission.\"oidc\".paths=/resource/*\n"
+                                    + "quarkus.oidc.auth-server-url=BUILD-TIME-OVERRIDDEN\n"
+                                    + "quarkus.devservices.enabled=false"),
+                            "application.properties"))
+            .setForcedDependencies(List.of(
+                    Dependency.of("io.quarkus", "quarkus-oidc", Version.getVersion())))
+            .overrideRuntimeConfigKey("quarkus.oidc.auth-server-url", "http://localhost:8081/auth/realms/OpenAPIOIDC");
```
Comment (michalvavrik) [inline extensions/smallrye-openapi/deployment/src/test/java/io/quarkus/smallrye/openapi/test/jaxrs/OIDCSecurityAutoAddTestTest.java:30]: I think this is great PR, but isn't it bit strange that you can override `quarkus.smallrye-openapi.oidc-open-id-connect-url=BUILD-TIME-OVERRIDDEN` with `quarkus.oidc.auth-server-url`? If users want to override it, why are setting it at the first place? If they set the `quarkus.smallrye-openapi.oidc-open-id-connect-url` maybe they want to generate OpenAPI document for different environment from local computer?

I can find arguments against my suggestion, but at least you should document this behavior.
Users can always go wild and do something like `quarkus.smallrye-openapi.oidc-open-id-connect-url=${dev-env-url:${quarkus.oidc.auth-server-url}}`

**Comment by michalvavrik** [comment]
@MikeEdgar does this PR also fixes https://github.com/quarkusio/quarkus/issues/26615 ? I thought Swagger UI relies on OpenAPI document so it could, can you check please or I confused problems?

File: extensions/smallrye-openapi/deployment/src/test/java/io/quarkus/smallrye/openapi/test/jaxrs/OIDCSecurityAutoAddTestTest.java (hunk 1 above)
Comment (michalvavrik) [reply extensions/smallrye-openapi/deployment/src/test/java/io/quarkus/smallrye/openapi/test/jaxrs/OIDCSecurityAutoAddTestTest.java:30]: copy that, thanks

**Comment by MikeEdgar** [comment]
> @MikeEdgar does this PR also fixes #26615 ? I thought Swagger UI relies on OpenAPI document so it could, can you check please or did I confused problems?

I believe it does fix that one too. I've commented there to have someone confirm their use of annotations, but reading through the comments, it matches.

**Comment by MikeEdgar** [comment]
@phillip-kruger please take a look.

**Review by phillip-kruger — APPROVED** [review]
