### PR TITLE
Replaced registry 'disabled' option with 'enabled'

### LINKED ISSUE #18770: `disabled:true` in config should be `enabled:false`
### Describe the bug

we missed this - everywhere else we used "enabled" to turn on/off things.

In  quarkus/config.yml we have used `disabled: false`.

it should be `enabled: true`
 

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by aloubyansky**
Fixes https://github.com/quarkusio/quarkus/issues/18770

### CODE REVIEW

**Review by ebullient — APPROVED** [review]

**Comment by aloubyansky** [comment]
@gastaldi fyi

**Review by gastaldi — APPROVED** [review]

File: independent-projects/tools/registry-client/src/main/java/io/quarkus/registry/config/json/JsonRegistryConfig.java [hunk 1]
```diff
@@ -170,11 +171,21 @@ public boolean equals(Object obj) {
...
                 && Objects.equals(extra, other.extra) && Objects.equals(id, other.id)
                 && Objects.equals(mavenConfig, other.mavenConfig)
                 && Objects.equals(nonPlatformExtensions, other.nonPlatformExtensions)
                 && Objects.equals(platforms, other.platforms) && Objects.equals(updatePolicy, other.updatePolicy)
                 && Objects.equals(versionsConfig, other.versionsConfig);
     }
+
+    public static class BooleanTrueFilter {
+        @Override
+        public boolean equals(Object obj) {
```
Comment (gastaldi) [inline independent-projects/tools/registry-client/src/main/java/io/quarkus/registry/config/json/JsonRegistryConfig.java:184]: Are you sure this is the method you want to override?

Comment (gastaldi) [reply independent-projects/tools/registry-client/src/main/java/io/quarkus/registry/config/json/JsonRegistryConfig.java:184]: Ah ignore me, just read in the javadocs: 

>Filter object's equals() method is called with value to serialize; if it returns true value is excluded (that is, filtered out); if false value is included.

File: independent-projects/tools/registry-client/src/main/java/io/quarkus/registry/config/json/JsonRegistryConfig.java [hunk 2]
```diff
@@ -46,13 +46,14 @@ public void setId(String id) {
         this.id = Objects.requireNonNull(id);
     }
 
+    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = BooleanTrueFilter.class)
```
Comment (gastaldi) [inline independent-projects/tools/registry-client/src/main/java/io/quarkus/registry/config/json/JsonRegistryConfig.java:49]: Why do you need this?

File: independent-projects/tools/registry-client/src/main/java/io/quarkus/registry/config/json/JsonRegistryConfig.java [hunk 3]
```diff
@@ -46,13 +46,14 @@ public void setId(String id) {
         this.id = Objects.requireNonNull(id);
     }
 
+    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = JsonBooleanTrueFilter.class)
```
Comment (gastaldi) [inline independent-projects/tools/registry-client/src/main/java/io/quarkus/registry/config/json/JsonRegistryConfig.java:49]: I still don't get why this is needed

Comment (aloubyansky) [reply independent-projects/tools/registry-client/src/main/java/io/quarkus/registry/config/json/JsonRegistryConfig.java:49]: This is applying the the filter. Is there something redundant?

Comment (gastaldi) [reply independent-projects/tools/registry-client/src/main/java/io/quarkus/registry/config/json/JsonRegistryConfig.java:49]: I don't get why do you need `@JsonInclude` and a filter here? The filter doesn't seem to do anything special?

Comment (aloubyansky) [reply independent-projects/tools/registry-client/src/main/java/io/quarkus/registry/config/json/JsonRegistryConfig.java:49]: Oh, it does. W/o it it will be always serializing `enabled: true`. With the filter it switches the default for the boolean that should be skipped during serialization.

**Review by ebullient — APPROVED** [review]
