### PR TITLE
Fix config properties validation

### LINKED ISSUE #2350: Config properties validation - ConfigProperty#name() is not mandatory
If not specified, the name is derived automatically.

### PR DESCRIPTION
**Pull request by mkouba**
- ConfigProperty#name() is not mandatory
- resolves #2350

### CODE REVIEW

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ConfigBuildStep.java [hunk 1]
```diff
@@ -63,7 +65,28 @@ public void validate(ValidationContext validationContext) {
                             // No need to validate properties with default values
                             continue;
                         }
-                        String propertyName = configProperty.value("name").asString();
+                        AnnotationValue nameValue = configProperty.value("name");
+                        String propertyName;
+                        if (nameValue != null) {
+                            propertyName = nameValue.asString();
+                        } else {
+                            // org.acme.Foo.config
```
Comment (manovotn) [inline extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ConfigBuildStep.java]: It would be nice to have a test.
If, for some reason, the spec decides to change how default names are deduced, we won't be able to detect the need for change here.

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ConfigBuildStep.java [hunk 2]
```diff
@@ -63,7 +65,28 @@ public void validate(ValidationContext validationContext) {
...
+                            if (injectionPoint.isField()) {
+                                FieldInfo field = injectionPoint.getTarget().asField();
+                                propertyName = (field.declaringClass().enclosingClass() == null ? field.declaringClass().name()
+                                        : field.declaringClass().enclosingClass() + "." + field.declaringClass().simpleName())
+                                        + "." + field.name();
```
Comment (manovotn) [inline extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ConfigBuildStep.java]: I know this is nitpicking but I'd probably turn the dot `.` into a a constant you then reuse. E.g. `final string DOT = "."`

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ConfigBuildStep.java (hunk 1 above)
Comment (mkouba) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ConfigBuildStep.java]: There is a TCK test for this and since we aim to run the TCK soon I thought another test would be redundant?

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ConfigBuildStep.java (hunk 2 above)
Comment (mkouba) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ConfigBuildStep.java]: A constant is probably not necessary but I'll extract the logic into a shared util method.

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ConfigBuildStep.java (hunk 1 above)
Comment (manovotn) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ConfigBuildStep.java]: Ok, in that case, it should be fine

**Review by manovotn — APPROVED** [review]
Looks good
