### PR TITLE
Don't warn about missing json extension for SubResources

### LINKED ISSUE #23762: RR endpoints analysis treats subresource as JSON serializable entity
### Describe the bug

During analysis phase declaring a resource method returning an subresource will result in a warning about missing JSON extension

### Expected behavior

Compilation should complete without warning because code is returning a subresource and not an entity to serialize

### Actual behavior

`WARN  [io.qua.res.rea.ser.dep.QuarkusServerEndpointIndexer] (build-56) Quarkus detected the use of JSON in JAX-RS method 'reactivedevmode.Resource#subresource' but no JSON extension has been added. Consider adding 'quarkus-resteasy-reactive-jackson' or 'quarkus-resteasy-reactive-jsonb'.`

### How to Reproduce?

Link to reproducer https://github.com/luca-bassoricci/subresource-problem
mvn quarkus:dev to start

With 2.7.1 compilation will fail due to another error already fixed, but in console warning is present

### Output of `uname -a` or `ver`

Microsoft Windows [Versione 10.0.19042.1469]

### Output of `java -version`

openjdk version "11.0.6" 2020-01-14 LTS

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.7.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3

### Additional information

Using the non-reactive version of Resteasy works without warning

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #23762

### CODE REVIEW

**Comment by geoand** [comment]
@mkouba this one is similar to the one you had found 😉

File: extensions/resteasy-reactive/quarkus-resteasy-reactive-common/deployment/src/main/java/io/quarkus/resteasy/reactive/common/deployment/JsonDefaultProducersHandler.java [hunk 1]
```diff
@@ -30,6 +30,11 @@
     }
 
     private boolean isJsonCompatibleType(Context context) {
+        if (context.httpMethod() == null) {
```
Comment (mkouba) [inline extensions/resteasy-reactive/quarkus-resteasy-reactive-common/deployment/src/main/java/io/quarkus/resteasy/reactive/common/deployment/JsonDefaultProducersHandler.java:33]: So I guess that this PR is about ignoring the warning for _sub-resource locators_, right? Because if a request method is present then it's called a _sub-resource method_. ;-)

**Review by mkouba — APPROVED** [review]

File: extensions/resteasy-reactive/quarkus-resteasy-reactive-common/deployment/src/main/java/io/quarkus/resteasy/reactive/common/deployment/JsonDefaultProducersHandler.java (hunk 1 above)
Comment (geoand) [reply extensions/resteasy-reactive/quarkus-resteasy-reactive-common/deployment/src/main/java/io/quarkus/resteasy/reactive/common/deployment/JsonDefaultProducersHandler.java:33]: Right. I am not clear myself about the terminology... It's just confusing IMHO :)
