### PR TITLE
Qute: Allow to specify default bundle message file without language tag

### LINKED ISSUE #32354: Defining message in msg.properties file doesn't work with default locale
### Describe the bug

I  have defined an AppMessages like this:

```java
@MessageBundle
public interface AppMessages {

    @Message("Hello {name ?: 'Qute'}")
    String hello_name(String name);
}
```

In my template I use it like this:

`{msg:hello_name('Lucie')}`

it works perfectly.

Now I want to manage message in msg.properties. So I define a `src/main/resources/messages/msg.properties`like this:

`hello_name=Hello {name ?: 'Qute'}`

and I remove the message value from the class:

```java
@MessageBundle
public interface AppMessages {

    @Message
    String hello_name(String name);
}
```

It throws the following error:

`io.quarkus.qute.deployment.MessageBundleException: Message template for key [hello_name] is missing for default locale`

Please note if I define `src/main/resources/messages/msg_fr.properties` and I configure `quarkus.default-locale=fr` in `application.properties` it works perfecly.

`

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by michalvavrik**
closes: #32354

It is now possible to omit language tag from default message file name.

### CODE REVIEW

File: extensions/qute/deployment/src/main/java/io/quarkus/qute/deployment/MessageBundleProcessor.java [hunk 1]
```diff
@@ -207,13 +207,24 @@ List<MessageBundleBuildItem> processBundles(BeanArchiveIndexBuildItem beanArchiv
...
                         if (fileName.startsWith(name)) {
-                            // msg_en.txt -> en
-                            // msg_Views_Index_cs.properties -> cs
-                            // msg_Views_Index_cs-CZ.properties -> cs-CZ
-                            // msg_Views_Index_cs_CZ.properties -> cs_CZ
-                            String locale = fileName.substring(name.length() + 1, fileName.indexOf('.'));
-                            // Support resource bundle naming convention
-                            locale = locale.replace('_', '-');
+                            final String locale;
+                            int postfixSeparatorIx = fileName.indexOf('.');
```
Comment (mkouba) [inline extensions/qute/deployment/src/main/java/io/quarkus/qute/deployment/MessageBundleProcessor.java:211]: How about just `postfixIndex` or `postfixIdx`? It took me a few seconds to realize that `Ix` stands for index ;-)

**Review by mkouba — COMMENTED** [review]
Looks great. I've just added two minor comments. Thanks.

**Review by mkouba — APPROVED** [review]
