### PR TITLE
Fixes #2622 clear some state during reload

### LINKED ISSUE #2622: RxJava1ContextPropagator does not work correctly in the dev mode
Quarkus build: https://github.com/quarkusio/quarkus/commit/ef71554148994a2e43e619dc4f5e2b3f692be5eb

# Stack trace:
```
Caused by: java.lang.IllegalStateException: Container not running: ArcContainerImpl [id=ff6e4c3c-6b02-424a-8290-37430a072755, running=false, beans=0, observers=0, scopes=[interface javax.inject.Singleton, interface javax.enterprise.context.ApplicationScoped]]
	at io.quarkus.arc.ArcContainerImpl.requireRunning(ArcContainerImpl.java:548)
	at io.quarkus.arc.ArcContainerImpl.requestContext(ArcContainerImpl.java:239)
	at io.quarkus.arc.runtime.context.ArcContextProvider.lambda$currentContext$4(ArcContextProvider.java:42)
	at io.smallrye.context.impl.ActiveContextState.<init>(ActiveContextState.java:18)
	at io.smallrye.context.impl.CapturedContextState.begin(CapturedContextState.java:35)
	at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$0(SmallRyeThreadContext.java:213)
	at io.smallrye.context.propagators.rxjava1.ContextPropagatorOnObservableCreateAction$ContextCapturerObservable$OnAssemblyObservableSubscriber.onNext(ContextPropagatorOnObservableCreateAction.java:62)
	at rx.internal.operators.NotificationLite.accept(NotificationLite.java:135)
```

# Steps to reproduce:
1. clone https://github.com/mkouba/pulls
2. run `mvn compile quarkus:dev`
3. hit `http://localhost:8080/pulls`
4. make some irrelevant change
5. hit `http://localhost:8080/pulls`

It seems that SM CP is using some outdated `ThreadContextSnapshot` returned from `ArcContextProvider#currentContext()` - this snapshot is referencing the stopped ArC container instance. A quick solution might be to use `Arc.container()` in the returned lambda.

### PR DESCRIPTION
**Pull request by stuartwdouglas**
After a reload we need to clear out old ThreadLocal data,
and Hystrix is also caching some things in statics

### CODE REVIEW

**Comment by gsmet** [comment]
@dmlloyd any chance you could review this one?

File: core/runtime/src/main/java/io/quarkus/runtime/CleanableExecutor.java [hunk 1]
```diff
@@ -0,0 +1,254 @@
...
+import sun.misc.Unsafe;
+
+/**
+ * An executor that can be 'cleaned'. Each clean increments an internal generation number. When a task is executed by
+ * a thread that has a different generation number to the last task executed by the thread then the threads ThreadLocal's
+ * will be cleared. This means that thread locals from a previous deployment cannot interfere with the current deployment.
+ *
+ * This is only for development mode, it must not be used for production applications.
+ *
+ * TODO: should this just provide a facacde that simply starts a new thread pool instead?
```
Comment (dmlloyd) [inline core/runtime/src/main/java/io/quarkus/runtime/CleanableExecutor.java]: Maybe that would be a bot cleaner: just start a new pool, swap it in, and shut down the old one.

File: core/runtime/src/main/java/io/quarkus/runtime/CleanableExecutor.java [hunk 2]
```diff
@@ -0,0 +1,254 @@
...
+        return submit;
+    }
+
+    @Override
+    public void execute(Runnable command) {
+        executor.submit(new CleaningRunnable(command));
+    }
+
+    /**
+     * copied from JBoss threads
```
Comment (dmlloyd) [inline core/runtime/src/main/java/io/quarkus/runtime/CleanableExecutor.java]: Maybe there should be an API for this.

**Review by dmlloyd — COMMENTED** [review]
I'm not so sure about this approach (see comments).

File: core/runtime/src/main/java/io/quarkus/runtime/CleanableExecutor.java (hunk 1 above)
Comment (stuartwdouglas) [reply core/runtime/src/main/java/io/quarkus/runtime/CleanableExecutor.java]: you would need to also re-dispatch the current HTTP thread to the new pool, to prevent old context from hanging around.

Comment (stuartwdouglas) [reply core/runtime/src/main/java/io/quarkus/runtime/CleanableExecutor.java]: This approach works for now, this approach was listed as a todo because it would need a lot more testing (which is mostly manual testing at the moment as we do not have a good way to test dev mode). 

This is a very low risk approach as it is basically the status quo with some fixes. Changing the behaviour of dev mode and hot reload has much more potential for regressions, which is why I left it as a TODO item.

File: extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/SmallryeFaultToleranceTemplate.java [hunk 3]
```diff
@@ -0,0 +1,30 @@
...
+        context.addShutdownTask(new Runnable() {
+            @Override
+            public void run() {
+                HystrixCommandCompletionStream.reset();
+                HystrixCollapserEventStream.reset();
+                HystrixCommandStartStream.reset();
+                HystrixThreadPoolCompletionStream.reset();
+                HystrixCommandStartStream.reset();
+                HystrixThreadEventStream.getInstance().shutdown();
+                Hystrix.reset();
```
Comment (mkouba) [inline extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/SmallryeFaultToleranceTemplate.java]: `Hystrix.reset()` should not be necessary as we call it when the CDI app context is destroyed - https://github.com/smallrye/smallrye-fault-tolerance/blob/master/implementation/src/main/java/io/smallrye/faulttolerance/HystrixInitializer.java#L64. I'm not sure about the streams though. But better safe than sorry.

**Review by gsmet — APPROVED** [review]
Let's go for the safe approach first and revisit that later.

@stuartwdouglas could you open an issue drafting the approach we should follow in the future. Better that than having a comment buried in the code.
