### PR TITLE
Make hot deployment work reliably for newly added resources in QuarkusDevModeTest

### LINKED ISSUE #5424: NotFoundExceptionMapperTestCase fails on some environments
**Describe the bug**
The two tests in `io.quarkus.resteasy.test.NotFoundExceptionMapperTestCase` added by @machi1990 which replace resources and expect to see the changed resources fail in some environments and not in others.

@kenfinnigan added some sleeps to these tests which seemed to fix the problems sometimes, yet the problem is still not consistently fixed.

The problem may be due to inadequate resolution of file and/or directory time stamps.  This was a known problem in Java 8 (where the test fails for me) that was fixed in Java 11 (where the test does not fail for me).

The commit which introduced the problematic test was d81e508b6fb543724bd526c01304c28ebedc3d8f.  The commit which added the sleeps was 24876d0b7a9be4445f4ee4188f97aba4dc9cd1cb.

**To Reproduce**
1. Run this test class on Java 8, hopefully the problem reappears.  Removing the sleeps might be necessary.

### PR DESCRIPTION
**Pull request by jaikiran**
Fixes https://github.com/quarkusio/quarkus/issues/5424

The `QuarkusDevModeTest` is currently equipped to deal with _modifying_  existing files to trigger hot deployment reliably. It does so by dealing with last modification timestamps on files through https://github.com/quarkusio/quarkus/blob/master/test-framework/junit5-internal/src/main/java/io/quarkus/test/QuarkusDevModeTest.java#L341 where it internally waits for the file timestamps to change, before letting the test execution to proceed. This `sleepForFileChanges` is currently getting called from within the `QuarkusDevModeTest` whenever a "modification" API (on that class) is being called. However, this `sleepForFileChanges` is missing when new resources get added to the application. As a result, the test framework doesn't wait for enough amount of time before letting the test proceed. This ultimately causes Quarkus hot deployment process to get triggered (through the test case), with the "old" file timestamp on the directories containing this newly added resource. As a result, the directory where this new resource was added isn't considered as a hot deployment change.

The commit here fixes this issue by calling the `sleepForFileChanges` in the test framework whenever a new resource gets added.

I have also re-enabled the 2 `@Disabled` test methods in `NotFoundExceptionMapperTestCase` since they should now pass consistently. I had used `@RepeatedTest(5)` on these 2 test methods to locally reproduce this issue and then verify the fix. I could reproduce that issue locally without this fix and now with this fix the tests consistently pass.

### CODE REVIEW

**Comment by machi1990** [comment]
Thanks @jaikiran LGTM. 

I’ll run the tests locally and report back a bit later.

File: extensions/resteasy/deployment/src/test/java/io/quarkus/resteasy/test/NotFoundExceptionMapperTestCase.java [hunk 1]
```diff
@@ -54,7 +53,6 @@ public void testJsonResourceNotFound() {
                 .contentType(ContentType.JSON);
     }
 
-    @Disabled("https://github.com/quarkusio/quarkus/issues/5424")
     @Test
     public void shouldDisplayNewAddedFileIn404ErrorPage() throws InterruptedException {
```
Comment (machi1990) [inline extensions/resteasy/deployment/src/test/java/io/quarkus/resteasy/test/NotFoundExceptionMapperTestCase.java]: nit: We can remove the `throws InterruptedException` from method signature signature

File: extensions/resteasy/deployment/src/test/java/io/quarkus/resteasy/test/NotFoundExceptionMapperTestCase.java [hunk 2]
```diff
@@ -74,7 +72,6 @@ public void shouldDisplayNewAddedFileIn404ErrorPage() throws InterruptedExceptio
                 .body(containsString("index2.html")); // check that index2.html is displayed
     }
 
-    @Disabled("https://github.com/quarkusio/quarkus/issues/5424")
     @Test
     public void shouldNotDisplayDeletedFileIn404ErrorPage() throws InterruptedException {
```
Comment (machi1990) [inline extensions/resteasy/deployment/src/test/java/io/quarkus/resteasy/test/NotFoundExceptionMapperTestCase.java]: likewise here

**Review by machi1990 — APPROVED** [review]
I tested this locally (several runs) without any problem. 

LGTM other than the minor comment I have added. 

Thanks @jaikiran

File: extensions/resteasy/deployment/src/test/java/io/quarkus/resteasy/test/NotFoundExceptionMapperTestCase.java (hunk 2 above)
Comment (jaikiran) [reply extensions/resteasy/deployment/src/test/java/io/quarkus/resteasy/test/NotFoundExceptionMapperTestCase.java]: Done - PR updated

**Review by stuartwdouglas — APPROVED** [review]
