### PR TITLE
Log how OIDC session age is calculated

### LINKED ISSUE #51332: Setting `QUARKUS_OIDC_AUTHENTICATION_SESSION_AGE_EXTENSION` no longer works
### Describe the bug

It was always possible to set certain options for OIDC with environment variables. This is especially useful for setting some options for your production environment.

In our case we set `QUARKUS_OIDC_AUTHENTICATION_SESSION_AGE_EXTENSION=23h` to extend the lifetime of the cookie to make sure we can refresh tokens accordingly with Azure Entra ID (those tokens are valid for 1 hour by default). See https://quarkus.io/guides/security-oidc-configuration-properties-reference#quarkus-oidc_quarkus-oidc-authentication-session-age-extension

Setting this via normal application properties or yaml config does work. However it no longer works with the environment variable in Quarkus 3.29.4 after updating from 3.26.3

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

17

### Quarkus version or git rev

3.29.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.9.11

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sberyozkin**
Fixes #51332.

This PR attempts to make it clearer how the session age is calculated, tries to highlight it set to the ID token age initially but can be extended.

It also warns if a user has configured the session age extension but did not allow to have tokens refreshed, for this warning to work I had to make the session age extension property optional to detect it was set by a user

### CODE REVIEW

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcTenantConfig.java [hunk 1]
```diff
@@ -917,10 +917,10 @@ String directive() {
          * the user is redirected to the OIDC provider to re-authenticate once the session has expired.
          * If this property is set to a nonzero value, then the expired ID token can be refreshed before
          * the session has expired.
-         * This property is ignored if the `token.refresh-expired` property has not been enabled.
+         * This property is effective only if the `token.refresh-expired` property is enabled and a refresh token is available.
+         * It is set to 5 minutes by default.
          */
```
Comment (wjglerum) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcTenantConfig.java:922]: You can add `@ConfigDocDefault` here to still provide the default value

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/TenantContextFactory.java [hunk 2]
```diff
@@ -291,6 +291,11 @@ private Uni<TenantConfigContext> createTenantContext(OidcTenantConfig oidcTenant
             if (oidcConfig.token().refreshTokenTimeSkew().isPresent()) {
                 oidcConfig.token.setRefreshExpired(true);
             }
+            if (oidcConfig.authentication().sessionAgeExtension().isPresent()
+                    && !oidcConfig.token().refreshExpired()) {
+                LOG.warn(
+                        "Session age extension will not be effective because 'quarkus.oidc.token.refresh-expired=true' is not set");
```
Comment (wjglerum) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/TenantContextFactory.java:297]: Great this would save me the next time!

**Review by wjglerum — COMMENTED** [review]
thanks!

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java [hunk 3]
```diff
@@ -1065,23 +1065,35 @@ public Uni<? extends Void> apply(Void t) {
...
+                            int lifespanGrace = configContext.oidcConfig().token().lifespanGrace().getAsInt();
+                            LOG.debugf("Adding token lifespan grace of %d seconds to the session age", lifespanGrace);
+                            sessionAge += lifespanGrace;
                         }
-                        if (configContext.oidcConfig().token().refreshExpired() && tokens.getRefreshToken() != null) {
-                            maxAge += configContext.oidcConfig().authentication().sessionAgeExtension().getSeconds();
+                        if (configContext.oidcConfig().token().refreshExpired()) {
+                            if (tokens.getRefreshToken() != null) {
+                                long sessionAgeExtension = configContext.oidcConfig().authentication().sessionAgeExtension()
+                                        .orElse(Duration.ofMinutes(5)).getSeconds();
```
Comment (gastaldi) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java:1079]: I honestly don't see how making it `Optional` changes anything, you're still expecting a value here and defaulting to 5min.

**Review by gastaldi — APPROVED** [review]
The messages are useful, but I don't understand why changing to a Optional changes anything in this case

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java (hunk 3 above)
Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java:1079]: Hi @gastaldi, if it set by default, we can't detect if a user cares at all about extending the session age, 5 mins makes no real difference, while enabling a token refresh is a policy decision (without it a user has to re-authenticate when the session expires, with it it can last for a very long time), so in those cases users may get surprised to see a warning...

Does it clarify it ?

Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java:1079]: I.e, we can keep it as it is, with a default value, but then we won't be able to warn that a user configured session extension won't work unless the tokens can be refreshed

Comment (gastaldi) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java:1079]: > I.e, we can keep it as it is, with a default value, but then we won't be able to warn that a user configured session extension won't work unless the tokens can be refreshed

Maybe I am missing something,  but can you point me to where you check if the `configContext.oidcConfig().authentication().sessionAgeExtension()` is present?

Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java:1079]: It guess it can actually help to optimize the configuration, I won't do it in this PR, but if we know the user has configured this property then we know the user cares about refreshing tokens and we note in OIDC docs and java docs, so with this change, users would eventually be able to set the session age extension only, without worrying to also enable token refresh

**Comment by sberyozkin** [comment]
What perhaps might be of some concern is that a `deprecated` public access property in the deprecated `io.quarkus.oidc.OidcTenantConfig` class is now Optional but I don't think it is worth marking this PR as release breaking due to update to the deprecated property, as it has been deprecated for a while and a setter on that deprecated class is  available, and it is very very unlikely anyone still has OIDC code that tries to work directly with that deprecated property.

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java (hunk 3 above)
Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java:1079]: @gastaldi Sorry, missed your question, it is in TenantContextFactory, typing on my mobile, but it is in this PR

Comment (michalvavrik) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java:1079]: AFAICT:

-  change of `@WithDefault("5M")` to `@ConfigDocDefault("5M")` covers scenarios where users set the same value as is configuration default
- switch to `Optional` is there because otherwise, the `sessionAgeExtension` would become required property, which we do not want

So I agree with Sergey's early comment, I don't understand the latter (something about the optimization of the configuration). That change makes sense, even though I consider that `5M` match as unimportant scenario.

Comment (michalvavrik) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java:1079]: And `extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/TenantContextFactory.java` is where the `Optional` type makes the difference.

**Review by michalvavrik — APPROVED** [review]
LGTM

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java (hunk 3 above)
Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java:1079]: Thanks @michalvavrik, @gastaldi  Right there could be indeed a case where a user sets 5M, but from the Quarkus OIDC perspective the actual value provided by a user is not important, it only needs an indication the user expects a session extension so that it can warn in advance in won't be effective unless token refresh is allowed - the warning is issued at the start up time in this case.

I meant that if a user wants to extend a cookie/session age then the only practical reason for that must be because the user wants a session refresh, just extending the cookie session age by itself won't change the fact that the effective session expiry time is that of the ID token... So if the user will explicitly configure the sessio age extension we can automatically enable token refresh - and we'll doc in the session age extension JavaDocs about it

**Comment by sberyozkin** [comment]
Thanks for reviews everyone, I'll merge soon unless there will be further comments
