### PR TITLE
Make sure request resumes on correct thread

### LINKED ISSUE #9693: Hot reload crashes using dev mode with vert.x-web extension
Hot reload crashes intermittently when making changes to vert.x-web routes. The application becomes unresponsive to new requests and dev mode requires restarting. 

An example stack trace is below;

```
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2020-05-30 10:31:58,066 WARN  [io.qua.ver.web.dep.VertxWebProcessor] (build-3) Route io.quarkus.benchmark.resource.pgclient.JsonResource#json() can match the same request and has the same order [0] as:
        - io.quarkus.benchmark.resource.JsonResource#json()
2020-05-30 10:31:58,066 WARN  [io.qua.ver.web.dep.VertxWebProcessor] (build-3) Route io.quarkus.benchmark.resource.PlaintextResource#plaintext() can match the same request and has the same order [0] as:
        - io.quarkus.benchmark.resource.pgclient.PlaintextResource#plaintext()
2020-05-30 10:31:58,066 WARN  [io.qua.ver.web.dep.VertxWebProcessor] (build-3) You can use @Route#order() to ensure the routes are not executed in random order
2020-05-30 10:31:58,167 INFO  [io.quarkus] (Quarkus Main Thread) pgclient 1.0-SNAPSHOT (powered by Quarkus 1.4.2.Final) started in 0.043s. Listening on: http://0.0.0.0:8080
2020-05-30 10:31:58,167 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2020-05-30 10:31:58,167 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, jdbc-postgresql, mutiny, reactive-pg-client, resteasy-jackson, scheduler, vertx, vertx-web]
2020-05-30 10:31:58,167 INFO  [io.qua.dep.dev] (vert.x-worker-thread-0) Hot replace total time: 0.510s 
2020-05-30 10:31:58,170 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-1) HTTP Request to /updates?queries=2 failed, error id: dc58213c-5c11-4aa6-998e-aca1d14c6bd8-1: java.lang.IllegalStateException: Request has already been read
        at io.vertx.core.http.impl.HttpServerRequestImpl.checkEnded(HttpServerRequestImpl.java:600)
        at io.vertx.core.http.impl.HttpServerRequestImpl.handler(HttpServerRequestImpl.java:307)
        at io.quarkus.vertx.http.runtime.ResumingRequestWrapper.handler(ResumingRequestWrapper.java:18)
        at io.vertx.ext.web.impl.HttpServerRequestWrapper.handler(HttpServerRequestWrapper.java:78)
        at io.quarkus.vertx.http.runtime.ResumingRequestWrapper.handler(ResumingRequestWrapper.java:18)
        at io.vertx.ext.web.impl.HttpServerRequestWrapper.handler(HttpServerRequestWrapper.java:78)
        at io.vertx.ext.web.handler.impl.BodyHandlerImpl.handle(BodyHandlerImpl.java:86)
        at io.vertx.ext.web.handler.impl.BodyHandlerImpl.handle(BodyHandlerImpl.java:42)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$14.handle(VertxHttpRecorder.java:958)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$14.handle(VertxHttpRecorder.java:936)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:130)
        at io.quarkus.vertx.http.runtime.devmode.VertxHotReplacementSetup.handleHotReplacementRequest(VertxHotReplacementSetup.java:39)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:130)
        at io.quarkus.benchmark.resource.pgclient.ServerHeaderFilter.myFilter(ServerHeaderFilter.java:33)
        at io.quarkus.benchmark.resource.pgclient.ServerHeaderFilter_RouteHandler_myFilter_cef5c00e3333622174f01380528df26e19f4b101.invoke(ServerHeaderFilter_RouteHandler_myFilter_cef5c00e3333622174f01380528df26e19f4b101.zig:64)
        at io.quarkus.vertx.web.runtime.RouteHandler.handle(RouteHandler.java:40)
        at io.quarkus.vertx.web.runtime.RouteHandler.handle(RouteHandler.java:15)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:130)
        at io.quarkus.vertx.http.runtime.devmode.VertxHotReplacementSetup.handleHotReplacementRequest(VertxHotReplacementSetup.java:39)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:130)
        at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:54)
        at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:36)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$7.handle(VertxHttpRecorder.java:334)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$7.handle(VertxHttpRecorder.java:331)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$1.handle(VertxHttpRecorder.java:112)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$1.handle(VertxHttpRecorder.java:103)
        at io.quarkus.vertx.http.runtime.devmode.VertxHotReplacementSetup$2.handle(VertxHotReplacementSetup.java:72)
        at io.quarkus.vertx.http.runtime.devmode.VertxHotReplacementSetup$2.handle(VertxHotReplacementSetup.java:63)
        at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:330)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

1. Add vertx-web extension
2. Define a @Route endpoint
3. Start dev mode
4. make changes to vertx route endpoint that does not contain errors 
5. hit endpoint with http client
6. introduce something that will cause compilation error 
7. hit end point
8. remove code introduced in step 5
9. Hit endpoint a few times and exception should be thrown

### PR DESCRIPTION
**Pull request by stuartwdouglas**
Fixes #9693

### CODE REVIEW

**Comment by gastaldi** [comment]
Your PR failed because of a code formatting failure which was pushed to master (weird that the PR checks didn't catch them). I fixed in https://github.com/quarkusio/quarkus/pull/10175

**Comment by gastaldi** [comment]
Thanks, now please rebase this PR ;)

**Comment by geoand** [comment]
It seems like `CustomRoleDecoderDevModeTest` is failing

**Comment by tsegismont** [comment]
@stuartwdouglas this change works around the issue with `BodyHandler`, but we may still have problems if, for example, user or extension code invokes `executeBlocking` on the Vert.x instance bound to the `Router`.

**Comment by gsmet** [comment]
This looks like something we really want in CR1.

**Comment by phillip-kruger** [comment]
> This looks like something we really want in CR1.

Yes please !!

**Comment by phillip-kruger** [comment]
This will also fix #10452

**Comment by gsmet** [comment]
I just rebased that one.

Stuart, where are we on this one? AFAICS the tests were failing and given the error message, I think it's related.

**Comment by tsegismont** [comment]
@gsmet there's an ongoing [discussion on Zulip](https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Hot.20reload.20and.20Vert.2Ex.20context) about what's the proper fix for the issue. In a few words, the changes in this PR fix the symptom observed in #9693 but not the cause.

**Comment by stuartwdouglas** [comment]
I think I have a fix for these failing tests, but we also need to look at preserving the vert.x instance. This will be a seperate PR though, as this is more complex.

**Comment by stuartwdouglas** [comment]
I have added another commit that will limit us to a single vert.x, lets see what CI says

**Comment by stuartwdouglas** [comment]
@gsmet should be good to go now.

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/devmode/VertxHttpHotReplacementSetup.java [hunk 1]
```diff
@@ -39,7 +40,8 @@ void handleHotReplacementRequest(RoutingContext routingContext) {
             routingContext.next();
             return;
         }
-        routingContext.vertx().executeBlocking(new Handler<Promise<Boolean>>() {
+        ConnectionBase connectionBase = (ConnectionBase) routingContext.request().connection();
```
Comment (tsegismont) [inline extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/devmode/VertxHttpHotReplacementSetup.java:43]: This change shouldn't be needed anymore.

File: extensions/vertx-web/deployment/src/test/java/io/quarkus/vertx/web/VertxWebDevModeTestCase.java [hunk 2]
```diff
@@ -0,0 +1,44 @@
...
+
+    @Test
+    public void testRunningInDevMode() {
+        RestAssured.given()
+                .body("OK")
+                .post("/test")
+                .then().statusCode(200)
+                .body(Matchers.equalTo("test route"));
+
+        runner.modifySourceFile(TestRoute.class, new Function<String, String>() {
```
Comment (tsegismont) [inline extensions/vertx-web/deployment/src/test/java/io/quarkus/vertx/web/VertxWebDevModeTestCase.java:29]: How about updating `TestRoute` so that the handler calls executing blocking, and we verify that the context when calling `executingBlocking` and when the callback is involved is the same:

```java
Vertx vertx = rc.vertx()
expected = vertx.getOrCreateContext();
vertx.executeBlocking(Promise::complete, ar -> {
  actual = vertx.getOrCreateContext();
  // expected should be the same as actual
  // before AND after hot reload
})
```

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/devmode/VertxHttpHotReplacementSetup.java (hunk 1 above)
Comment (stuartwdouglas) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/devmode/VertxHttpHotReplacementSetup.java:43]: It is, the old code could resume on a different IO thread in the same vert.x instance, this makes sure it is the same thread that will be delivering the IO notifications.

Comment (tsegismont) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/devmode/VertxHttpHotReplacementSetup.java:43]: Sorry I can't see how, do you have a simple example in mind?

Comment (tsegismont) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/devmode/VertxHttpHotReplacementSetup.java:43]: OK

File: extensions/vertx-web/deployment/src/test/java/io/quarkus/vertx/web/VertxWebDevModeTestCase.java (hunk 2 above)
Comment (stuartwdouglas) [reply extensions/vertx-web/deployment/src/test/java/io/quarkus/vertx/web/VertxWebDevModeTestCase.java]: I have updated the test to verify the connection vertx instance matches the current vertx instance.

**Review by tsegismont — APPROVED** [review]
Thanks @stuartwdouglas !
