### PR TITLE
CLI: correct behavior of --tests and --no-tests

### LINKED ISSUE #18391: Quarkus CLI test are run even if `--no-tests` is specified
## Describe the bug
When building using the CLI with command `quarkus build --no-tests`  the tests are still executed.

### Expected behavior
No tests should be run

### Actual behavior
Tests are run 

## To Reproduce

Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific).

Or attach an archive containing the reproducer to the issue.

1.  `quarkus create app -a bug-reproducer` 
2.  `cd bug-reproducer`
3.  `quarkus build --no-tests`

### Screenshots
(If applicable, add screenshots to help explain your problem.)

### Output of `uname -a` or `ver`
Darwin tqvarnst-mac 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64

### Output of `java -version`
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-16.0.1+9 (build 16.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-16.0.1+9 (build 16.0.1+9, mixed mode, sharing)

### Quarkus version or git rev
2.0.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Quarkus CLI
```
> quarkus --version
Client Version 2.0.0.Final
```

## Additional context
(Add any other context about the problem here.)

### PR DESCRIPTION
**Pull request by ebullient**
Resolves #18391

### CODE REVIEW

File: devtools/cli/src/main/java/io/quarkus/cli/common/BuildOptions.java [hunk 1]
```diff
@@ -13,10 +13,17 @@
     @CommandLine.Option(order = 5, names = { "--offline" }, description = "Work offline.", defaultValue = "false")
     public boolean offline = false;
 
-    @CommandLine.Option(order = 6, names = { "--tests" }, description = "Run tests.", negatable = true)
-    public boolean runTests = true;
+    @CommandLine.Option(order = 6, names = {
+            "--no-tests" }, description = "Run tests.", negatable = true, defaultValue = "false")
+    public boolean skipTests = false;
```
Comment (maxandersen) [inline devtools/cli/src/main/java/io/quarkus/cli/common/BuildOptions.java:18]: i thought you didn't like double negations :) 

had exepcted to still be called runTests.

Comment (ebullient) [reply devtools/cli/src/main/java/io/quarkus/cli/common/BuildOptions.java:18]: the way it is actually set, it ends up matching the positive skipTests in usage.

**Review by maxandersen — APPROVED** [review]
