### PR TITLE
Don't assume generated sources directory exists

### LINKED ISSUE #51178: Quarkus should not assume generated sources exists
### Describe the bug

do this:

```
jbang init -t qrest rest.java
jbang -Dquarkus.dev --fresh rest.java
```

which boots up the app in devmode so you have devui working etc.

Do a request (changing nothing about it) and quarkus will fail with this:

```
java.io.FileNotFoundException: /var/folders/rb/jl238yks5xg62d0brw32jbd40000gn/T/quarkus-jbang13907878571349382093/target/generated-sources/annotations: does not exist
	at jdk.compiler/com.sun.tools.javac.file.Locations$BasicLocationHandler.checkDirectory(Locations.java:560)
	at jdk.compiler/com.sun.tools.javac.file.Locations$BasicLocationHandler.checkSingletonDirectory(Locations.java:553)
	at jdk.compiler/com.sun.tools.javac.file.Locations$OutputLocationHandler.setPaths(Locations.java:616)
	at jdk.compiler/com.sun.tools.javac.file.Locations.setLocation(Locations.java:2156)
	at jdk.compiler/com.sun.tools.javac.file.JavacFileManager.setLocation(JavacFileManager.java:992)
	at io.quarkus.deployment.dev.filesystem.QuarkusFileManager.&lt;init&gt;(QuarkusFileManager.java:22)
	at io.quarkus.deployment.dev.filesystem.StaticFileManager.&lt;init&gt;(StaticFileManager.java:22)
	at io.quarkus.deployment.dev.JavaCompilationProvider.compile(JavaCompilationProvider.java:82)
	at io.quarkus.deployment.dev.QuarkusCompiler.compile(QuarkusCompiler.java:232)
	at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.checkForChangedClasses(RuntimeUpdatesProcessor.java:776)
	at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:475)
	at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:455)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$6.call(VertxHttpHotReplacementSetup.java:163)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$6.call(VertxHttpHotReplacementSetup.java:150)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$4(ContextImpl.java:192)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:270)
	at io.vertx.core.impl.ContextImpl$1.execute(ContextImpl.java:221)
	at io.vertx.core.impl.WorkerTask.run(WorkerTask.java:56)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2651)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2630)
	at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1622)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1589)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Resulted in: java.lang.RuntimeException: Cannot initialize file manager
	at io.quarkus.deployment.dev.filesystem.QuarkusFileManager.&lt;init&gt;(QuarkusFileManager.java:30)
	... 21 more
```

and yes, its true - that folder does not exist - it probably should but it shouldn't fail hard on it missing.

related to https://github.com/quarkusio/quarkus/issues/42908 where the "fix" was to force create it no matter if needed/used or not - which does not work here.

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
- Fixes: #51178

### CODE REVIEW

**Review by phillip-kruger — APPROVED** [review]

File: core/deployment/src/main/java/io/quarkus/deployment/dev/filesystem/QuarkusFileManager.java [hunk 1]
```diff
@@ -52,11 +56,14 @@ public void reset(Context context) {
...
-            if (!directory.exists()) {
-                final boolean success = directory.mkdirs();
-                if (!success) {
-                    throw new RuntimeException("Cannot create directory " + directory);
-                }
+            ensureDirectory(directory);
+        }
+    }
+
+    private void ensureDirectory(File directory) {
```
Comment (gastaldi) [inline core/deployment/src/main/java/io/quarkus/deployment/dev/filesystem/QuarkusFileManager.java:63]:
```suggestion
    private void ensureDirectoryExists(File directory) {
```
