### PR TITLE
Transaction support for MongoDB with Panache

### LINKED ISSUE #11294: Transactions for MongoDB with Panache
**Description**
MongoDB has multi-document ACID transactions and has for some time.  This has come in handy in many of our use cases.  Please add transaction handling to the Panache add-on.

**Implementation ideas**

A couple of ideas.

1) Allow for the passing of a MongoSession when performing any of the Panache CRUD actions.  If you look at frameworks like MongoJack and Morphia, they allow the passing of a session in its different operations.  This way, the framework doesn't need to worry about managing the session or the transaction.  it would be up to the developer to make sure that the session is appropriately started and either committed or rolled back.

2) Use annotation interceptors like Spring.  You can annotate any method with the @Transaction annotation to start and commit a transaction if the method completes without an exception.

From a thread regarding this topic:

Justin Lee - Here's what I did for Morphia.  In Morphia, the main point of interaction with the database is via the Datastore interface.  In 2.0, I added a startSession() method that returns a MorphiaSession instance and the implementation was a subclass that tracked the transaction.  MorphiaSession implements the Datastore interface so the developer can continue to treat it as a normal Datastore.  It's Autoclosable so they can use try-with-resources to properly close the session once it's done.  The implementation is largely just a wrapper around the original Datastore instance that passes around the session information to the necessary methods.  All told, it was a pretty light weight approach that literally took maybe half an hour to implement.  The bytecode instrumentation we do will probably make that slightly more complex but not overly so I don't think.

### PR DESCRIPTION
**Pull request by loicmathieu**
Fixes #11294

### CODE REVIEW

**Comment by loicmathieu** [comment]
@FroMage I made this new prototype for Transaction support for MongoDB with Panache with some adjustements based on your feedbacks on https://github.com/quarkusio/quarkus/pull/10097#issuecomment-717372582

> @loicmathieu we could perhaps skip supporting the reactive ones at first, and offer an equivalent to the transactional API that we have for HR+Panache. As for the initialisation of the client in the interceptor, I think you should be able to skip the interceptor entirely and delay the bit which registers your client to the TM until it's used. I'm pretty sure ORM does it this way: when you call an operation (not just obtain a client) we look at whether we have a current JTA transaction and if yes, we create a mongo transaction and register it to the TM (the same part you currently do in the interceptor).

So now, I don't use a CDI interceptor and I create the session when needed.

I need to re-implement everything as due to the changes for Kotlin support, my old branch cannot be rebased, as it'll take some time I want to be sure that this is the good direction before going on so I just implement one method to show you how it will be used.

If you validate the design, I'll report all the changes from my old branch.

With this design, I'll still need to find a way to pass the transaction options from the calling method (to be discussed later).

**Comment by FroMage** [comment]
Sorry it took such a long time. This looks just fine to me :)

**Comment by loicmathieu** [comment]
OK great !
I'll finish the implementation and we can discuss it more

**Comment by loicmathieu** [comment]
@gytis I implemented transaction support for MongoDB with Panache and it crashed the integration test of rest data support for MongoDB with Panache.

Apparently, you add the `@Transactional` annotation even for MongoDB, perviously it has no effect, not it uses a transaction so if the user didn't use a replicat set (and a version that support transaction) it failed.

I think the best would be to disabled transaction for MongoDB via Rest Data Panache, I'm not sure how to do this.

File: extensions/panache/mongodb-panache-common/runtime/src/main/java/io/quarkus/mongodb/panache/transaction/MongoTransactionException.java [hunk 1]
```diff
@@ -0,0 +1,7 @@
+package io.quarkus.mongodb.panache.transaction;
+
+public class MongoTransactionException extends RuntimeException {
```
Comment (evanchooly) [inline extensions/panache/mongodb-panache-common/runtime/src/main/java/io/quarkus/mongodb/panache/transaction/MongoTransactionException.java:3]: This doesn't appear to be used.

**Review by evanchooly — APPROVED** [review]
Just had the one question about that exception but otherwise looks nice.

File: integration-tests/mongodb-panache/src/test/java/io/quarkus/it/mongodb/panache/MongoReplicaSetTestResource.java [hunk 2]
```diff
@@ -0,0 +1,160 @@
...
+import de.flapdoodle.embed.mongo.MongodStarter;
+import de.flapdoodle.embed.mongo.config.IMongodConfig;
+import de.flapdoodle.embed.mongo.config.MongoCmdOptionsBuilder;
+import de.flapdoodle.embed.mongo.config.MongodConfigBuilder;
+import de.flapdoodle.embed.mongo.config.Net;
+import de.flapdoodle.embed.mongo.distribution.Version;
+import de.flapdoodle.embed.process.runtime.Network;
+import io.quarkus.test.common.QuarkusTestResourceLifecycleManager;
+
+public class MongoReplicaSetTestResource implements QuarkusTestResourceLifecycleManager {
```
Comment (FroMage) [inline integration-tests/mongodb-panache/src/test/java/io/quarkus/it/mongodb/panache/MongoReplicaSetTestResource.java:32]: Is this something that could be useful to other people?

**Review by FroMage — CHANGES_REQUESTED** [review]
LGTM, but you may want to add the following methods?

```java
public class Panache {

     /**
     * Returns the current {@link TransactionManager}
     *
     * @return the current {@link TransactionManager}
     */
    public static TransactionManager getTransactionManager() {
        return AbstractJpaOperations.getTransactionManager();
    }

   /**
     * Marks the current transaction as "rollback-only", which means that it will not be
     * committed: it will be rolled back at the end of this transaction lifecycle.
     */
    public static void setRollbackOnly() {
        AbstractJpaOperations.setRollbackOnly();
    }

}
```

I'm not sure if `TransactionManager` is visible in Mongo, now that you depend on narayana.

File: extensions/panache/mongodb-panache-common/runtime/src/main/java/io/quarkus/mongodb/panache/transaction/MongoTransactionException.java (hunk 1 above)
Comment (loicmathieu) [reply extensions/panache/mongodb-panache-common/runtime/src/main/java/io/quarkus/mongodb/panache/transaction/MongoTransactionException.java:3]: This is used to encapsulate the JTA SystemException into a RuntimeException here: https://github.com/quarkusio/quarkus/pull/14002/files#diff-d003b221f9b819da503954b1f03c63b8ddc7fb18b78c6921cc9ae4d9e1483d1aR370

File: integration-tests/mongodb-panache/src/test/java/io/quarkus/it/mongodb/panache/MongoReplicaSetTestResource.java (hunk 2 above)
Comment (loicmathieu) [reply integration-tests/mongodb-panache/src/test/java/io/quarkus/it/mongodb/panache/MongoReplicaSetTestResource.java:32]: I plan to create a MongoDB test library later on with the two ressources and refactor some integration test to use them.
I'll do it as a followup issue to avoid a too big PR but it's on my todo list ;)

**Comment by loicmathieu** [comment]
@FroMage there is no global `Panache` helper class on MongoDB with Panache and I'm reluctant to add one to only provide a shorter path for this. One can simply inject the `TransactionManager` if he want to do it.

File: integration-tests/mongodb-panache/src/test/java/io/quarkus/it/mongodb/panache/MongoReplicaSetTestResource.java (hunk 2 above)
Comment (FroMage) [reply integration-tests/mongodb-panache/src/test/java/io/quarkus/it/mongodb/panache/MongoReplicaSetTestResource.java:32]: OK

**Comment by FroMage** [comment]
> @FroMage there is no global Panache helper class on MongoDB with Panache and I'm reluctant to add one to only provide a shorter path for this. One can simply inject the TransactionManager if he want to do it.

Oh, I didn't know.

**Review by FroMage — APPROVED** [review]

**Comment by loicmathieu** [comment]
@gytis can you have a look at the following commit: https://github.com/quarkusio/quarkus/pull/14002/commits/3fe2a97863794f5eef8ddf3b8cf8ec4fc7457a19

I manage to make the REST data impl working for both Hibernate and Mongo by allowing to use a different update operator to void haging a transaction for MongoDB.

@FroMage if you know this part, maybe you can also have a look at it.

**Comment by gytis** [comment]
@loicmathieu sorry for a delay. I was on PTO since the middle of the last week.
I wasn't aware of this MongoDB transaction effort, I would have taken it into account when adding the transactional executor. I only added it a couple of weeks ago. In any case, I think your fix looks good.

**Comment by loicmathieu** [comment]
@gytis thanks for looking at it

> @loicmathieu sorry for a delay. I was on PTO since the middle of the last week.

No problem for the delay, it gives me the opportunity to have a look at the impl of rest data and it's an interesting piece of code ;)
