### PR TITLE
Panache: Only change field visibility and move JAXB annotations from field to getter when we actually generate the getter

### LINKED ISSUE #33832: Panache adding @XmlTransient to fields breaks (de)serialization in RestAssured
### Describe the bug

If I define an entity like so:

```
@Entity
@XmlRootElement(name = "myentity")
public class MyEntity extends PanacheEntity {
    public String field;

    public String getField() {
        return field;
    }

    public void setField(String field) {
        this.field = field;
    }
}
```

And use RestEasy classic with Jackson serialization in my resource:

```
    @GET
    @Path("/{id}")
    @Produces(MediaType.APPLICATION_JSON)
    public MyEntity get(@PathParam("id") Long id) {
        return MyEntity.findById(id);
    }
```

And try to use RestAssured's serialization in my tests:

```
        MyEntity deserializedEntity = given()
                .when().get("/hello/1")
                .then()
                .statusCode(200)
                .extract().body().as(MyEntity.class);
        assertThat(deserializedEntity).isNotNull();
        assertThat(deserializedEntity.getField()).isEqualTo("field-1");
```

Then everything on the server side will work fine, but RestAssured's serialization will always return an empty instance (all fields null).

NOTE: This example is admitedly contrived, but relevant because we have [similar code in our integration tests](https://github.com/quarkusio/quarkus/blob/af90b6301dd96c4ff03adc0b9dd20da400155fc3/integration-tests/hibernate-orm-tenancy/connection-resolver/src/main/java/io/quarkus/it/hibernate/multitenancy/fruit/Fruit.java) that starts failing because of this bug in another PR of mine that extends when Panache comes to play (#32876).

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

See https://github.com/yrodiere/quarkus-playground/tree/panache-xml-transient

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

I have reasons to believe the problem is related to Panache adding `@XmlTransient` automatically to public fields it transforms:

```java
@Entity
@XmlRootElement(
   name = "myentity"
)
@EnhancementInfo(
   version = "6.2.1.Final"
)
public class MyEntity extends PanacheEntity implements ManagedEntity, PersistentAttributeInterceptable, SelfDirtinessTracker {
   @XmlTransient
   protected String field;

   // [...]

   public String getField() {
      return this.$$_hibernate_read_field();
   }

   public void setField(String field) {
      this.$$_hibernate_write_field(field);
   }

   // [...]
}
```

Maybe the serialization that RestAssured relies on does not handle `@XmlTransient` correctly... Regardless, I think `@XmlAccessorType(PROPERTY)` would better fit Panache's intent, and may not cause this bug?

I'll try that and send a PR.

### PR DESCRIPTION
**Pull request by yrodiere**
If the getter already exists, we should trust users to do the right thing.

Fixes #33832

### CODE REVIEW

File: extensions/panache/panache-common/deployment/src/main/java/io/quarkus/panache/common/deployment/visitors/PanacheEntityClassAccessorGenerationVisitor.java [hunk 1]
```diff
@@ -239,4 +243,7 @@ private boolean isAnnotatedWithJsonIgnore(EntityField entityField) {
         return false;
     }
 
+    private boolean hasGetterForField(EntityField entityField) {
+        return entityInfo.firstMethod(entityField.getGetterName()) != null;
```
Comment (FroMage) [inline extensions/panache/panache-common/deployment/src/main/java/io/quarkus/panache/common/deployment/visitors/PanacheEntityClassAccessorGenerationVisitor.java:247]: This is a bit optimistic because it doesn't check that it's a getter method (zero parameter, returns the same type).

**Review by FroMage — CHANGES_REQUESTED** [review]
Looks good, except the getter optimism :)

File: extensions/panache/panache-common/deployment/src/main/java/io/quarkus/panache/common/deployment/visitors/PanacheEntityClassAccessorGenerationVisitor.java (hunk 1 above)
Comment (yrodiere) [reply extensions/panache/panache-common/deployment/src/main/java/io/quarkus/panache/common/deployment/visitors/PanacheEntityClassAccessorGenerationVisitor.java:247]: Ah, indeed I should use `method` instead.

As to checking for the return type... I'll try to implement a check, but I'll have to retrieve a "type descriptor" from the return type (to compare it with the field's type descriptor), and I'm not sure how easy that is.

Relatedly, assuming there's a `getMyProperty()` method, but its type is different, we will generate a new getter returning the field type. See https://github.com/quarkusio/quarkus/blob/51cb9667c303d62b5c7ffb0c40e47f2d57213f42/extensions/panache/panache-common/deployment/src/main/java/io/quarkus/panache/common/deployment/visitors/PanacheEntityClassAccessorGenerationVisitor.java#L128-L130. So we'll have two getters with different return types. I'd say we are screwed in that case anyway? :thinking:

**Comment by yrodiere** [comment]
Thanks @FroMage , I addressed your comment.

File: extensions/panache/panache-common/deployment/src/main/java/io/quarkus/panache/common/deployment/visitors/PanacheEntityClassAccessorGenerationVisitor.java (hunk 1 above)
Comment (FroMage) [reply extensions/panache/panache-common/deployment/src/main/java/io/quarkus/panache/common/deployment/visitors/PanacheEntityClassAccessorGenerationVisitor.java]: Hah. Good point. Not sure what to do in this case. It never happened. Let's pretend it won't happen until it does ;)

Just check the signature, I guess?

**Review by FroMage — APPROVED** [review]
