### PR TITLE
Ensure that all AutoCloseable binders are closed

### LINKED ISSUE #42355: OOM in tests since Quarkus 3.13.0 (Part 2)
### Describe the bug

As described in https://github.com/quarkusio/quarkus/issues/42303 we get an OOM in our tests.

Because https://github.com/quarkusio/quarkus/issues/42303 doesn't fix the problem completly i've opened a new issue with a new reproducer. 

Compared to the reproducer in  https://github.com/quarkusio/quarkus/issues/42303 i have added more dependencies.

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

[oom-reproducer2.zip](https://github.com/user-attachments/files/16522904/oom-reproducer2.zip)

`./gradlew test --console=plain`

⚠️ The reproducer uses 999-SNAPSHOT instead of 3.13.1 because 3.13.1 is not available in Maven Central yet.

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

Java 21

### Quarkus version or git rev

Quarkus 3.13.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.8

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
The OOM in the issue was caused by a class being help in a notification listener queue for JMX messages. 
The fix is simply to remove close the binder that then removes the listener.

- Fixes: #42355

### CODE REVIEW

File: extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/MicrometerRecorder.java [hunk 1]
```diff
@@ -107,15 +107,21 @@ public void configureRegistries(MicrometerConfig config,
...
+            jvmHeapPressureMetrics.bindTo(Metrics.globalRegistry);
+            autoCloseables.add(jvmHeapPressureMetrics);
             new JvmMemoryMetrics().bindTo(Metrics.globalRegistry);
             new JvmThreadMetrics().bindTo(Metrics.globalRegistry);
             new JVMInfoBinder().bindTo(Metrics.globalRegistry);
             if (ImageMode.current() == ImageMode.JVM) {
-                new JvmGcMetrics().bindTo(Metrics.globalRegistry);
+                JvmGcMetrics jvmGcMetrics = new JvmGcMetrics();
+                jvmGcMetrics.bindTo(Metrics.globalRegistry);
+                autoCloseables.add(jvmGcMetrics);
```
Comment (gsmet) [inline extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/MicrometerRecorder.java:124]: I wonder if I would add all the listeners to a List and then close them if they are Closeable or AutoCloseable. That might be more future proof.

**Review by gsmet — APPROVED** [review]
I added a thought but feel free to ignore and merge :).

Thanks for tracking this!

File: extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/MicrometerRecorder.java (hunk 1 above)
Comment (geoand) [reply extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/MicrometerRecorder.java:124]: I understand where the desire for defensiveness against such OOMs is coming from, but in this case, I think it's overkill.

In reality, this issue **was**  being flagged by IntelliJ (as the auto-closable was never being closed), we just didn't pay attention - and we absolutely should next time :)
