### PR TITLE
Consolidate all UI related extensions.

### LINKED ISSUE #12577: SwaggerUiProcessor leaves behind non-empty temporary directories in dev mode
**Describe the bug**
If swagger-ui extension is active, each app start creates a `quarkus-swagger-ui_*` folder in `/tmp`, e.g. `quarkus-swagger-ui_31789176944326801422565934992530930`, containing all the webjar files:
```
-rw-r--r--. 1 jenkins jenkins     665 Oct  6 19:00 favicon-16x16.png
-rw-r--r--. 1 jenkins jenkins     628 Oct  6 19:00 favicon-32x32.png
-rw-r--r--. 1 jenkins jenkins    1421 Oct  6 19:00 index.html
-rw-r--r--. 1 jenkins jenkins     639 Oct  6 19:00 index.html.gz
-rw-r--r--. 1 jenkins jenkins    2431 Oct  6 19:00 oauth2-redirect.html
-rw-r--r--. 1 jenkins jenkins     864 Oct  6 19:00 oauth2-redirect.html.gz
-rw-r--r--. 1 jenkins jenkins  986342 Oct  6 19:00 swagger-ui-bundle.js
-rw-r--r--. 1 jenkins jenkins  300057 Oct  6 19:00 swagger-ui-bundle.js.gz
-rw-r--r--. 1 jenkins jenkins 4309533 Oct  6 19:00 swagger-ui-bundle.js.map
-rw-r--r--. 1 jenkins jenkins  142933 Oct  6 19:00 swagger-ui.css
-rw-r--r--. 1 jenkins jenkins   22648 Oct  6 19:00 swagger-ui.css.gz
-rw-r--r--. 1 jenkins jenkins  281392 Oct  6 19:00 swagger-ui.css.map
-rw-r--r--. 1 jenkins jenkins  424281 Oct  6 19:00 swagger-ui-es-bundle-core.js
-rw-r--r--. 1 jenkins jenkins  118554 Oct  6 19:00 swagger-ui-es-bundle-core.js.gz
-rw-r--r--. 1 jenkins jenkins 1533198 Oct  6 19:00 swagger-ui-es-bundle-core.js.map
-rw-r--r--. 1 jenkins jenkins  985915 Oct  6 19:00 swagger-ui-es-bundle.js
-rw-r--r--. 1 jenkins jenkins  299885 Oct  6 19:00 swagger-ui-es-bundle.js.gz
-rw-r--r--. 1 jenkins jenkins 4308096 Oct  6 19:00 swagger-ui-es-bundle.js.map
-rw-r--r--. 1 jenkins jenkins  424485 Oct  6 19:00 swagger-ui.js
-rw-r--r--. 1 jenkins jenkins  118616 Oct  6 19:00 swagger-ui.js.gz
-rw-r--r--. 1 jenkins jenkins 1532710 Oct  6 19:00 swagger-ui.js.map
-rw-r--r--. 1 jenkins jenkins  311804 Oct  6 19:00 swagger-ui-standalone-preset.js
-rw-r--r--. 1 jenkins jenkins   97541 Oct  6 19:00 swagger-ui-standalone-preset.js.gz
-rw-r--r--. 1 jenkins jenkins 1384709 Oct  6 19:00 swagger-ui-standalone-preset.js.map
```
Such folders are *not* removed when the app is terminated (even not when terminated gracefully), filling up `/tmp`.

**Expected behavior**
Nothing should be left behind after the Quarkus app terminated.

**Actual behavior**
`/tmp` is "spammed" until all space is depleted.

**To Reproduce**

1. git clone https://github.com/quarkusio/quarkus-quickstarts.git
2. cd openapi-swaggerui-quickstart
3. mvn clean package -DskipTests
4. mvn quarkus:dev
5. CTRL + C
6. check `/tmp`

**Configuration**
Not relevant.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `MINGW64_NT-10.0-18363 XXX 3.0.7-338.x86_64 2019-11-21 23:07 UTC x86_64 Msys`
 - Output of `java -version`: `OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)`
 - GraalVM version (if different from Java): n/a
 - Quarkus version or git rev: `1.8.0.Final`
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): `Apache Maven 3.6.3`

**Additional context**

See also: https://stackoverflow.com/questions/15022219/does-files-createtempdirectory-remove-the-directory-after-jvm-exits-normally

These processors are also affected:
- `SmallRyeHealthProcessor`
- `SmallRyeGraphQLProcessor`

Other potentially affected, non-processor classes are mentioned here: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Various.20temp.20dirs.20are.20not.20cleaned.20up.3F/near/212540339

I'm also wondering wether this:
```
private static final String TEMP_DIR_PREFIX = "quarkus-swagger-ui_" + System.nanoTime();
```
could be more something like `"quarkus-swagger-ui_" + artifact.getVersion()`?
This would require something like `java.nio.channels.FileLock` though.

### PR DESCRIPTION
**Pull request by phillip-kruger**
This PR consolidate all UI related extensions.

### Consolidate
Before this PR, Swagger UI, GraphQL and Health all use some Web resources that is
handled specifically in Dev Mode and Production Mode. This code has been consolidated, as they all
do the same thing. So mostly this is deleting code in the extensions and all using the code from core-deployment.

### Temp
This also fix #12577 - or rather bypass it.
Code is changed to store the webjar contents in the temp folder using appName/groupId/artifactId/version.
This means that all instances using this in dev and test mode will serve from that content. The directory gets cleaned on test mode start, and does not grow on windows any more as the name is not a random id (problem bypassed).

### Branding
This PR also changed the Swagger UI to pull the content from [SmallRye](https://github.com/smallrye/smallrye-open-api/tree/master/ui/open-api-ui) rather than webjars. This allow us to brand the Swagger UI. This will also allow for example that we can brand the Red Hat build with Red Hat branding, and it will allow customers/users to add their own branding. See example screenshots below.

The swagger-ui version used in SmallRye is the same as what is used here before the PR. This will also allow us to do more custom 
things with swagger-ui in the future. The upgrade in versions for SmallRye GraphQL, OpenAPI and Health is just for the UI component to allow this branding.

**Default branding:** 

rest
graphql
health

**Possible Red Hat Branding:**

Screenshot_redhat

The red hat build can replace the default logo, favicon and css in `META-INF/branding` with Red Hat files. So the users will get Red Hat Branding by default, but can still override with their own as below.

**Example customer override:**

Screenshot_customer

Developers can supply their own `logo.png`, `favicon.ico` and `style.css` in `/src/main/resources/META-INF/branding/` that will allow basic custom branding.

Signed-off-by:Phillip Kruger <phillip.kruger@gmail.com>

### CODE REVIEW

File: core/deployment/src/main/java/io/quarkus/deployment/util/WebJarUtil.java [hunk 1]
```diff
@@ -0,0 +1,129 @@
...
+    private static final List<String> IGNORE_LIST = Arrays.asList("logo.png", "favicon.ico");
+
+    private WebJarUtil() {
+    }
+
+    public static Path devOrTest(AppArtifact artifact, String rootFolderInJar)
+            throws IOException {
+
+        Path path = createDir(artifact.getGroupId(), artifact.getArtifactId(), artifact.getVersion());
+        if (isEmpty(path)) {
```
Comment (famod) [inline core/deployment/src/main/java/io/quarkus/deployment/util/WebJarUtil.java:38]: What about multiple concurrenly running Quarkus instances? They might overwrite each other.
The safest thing would be to use `FileLock`, but this is not going to work for a directory, I fear...

Comment (phillip-kruger) [reply core/deployment/src/main/java/io/quarkus/deployment/util/WebJarUtil.java:38]: This is for dev mode, so we are saying that a developer will run concurrent versions of the same app at the exact same time ? I do not think we have to worry too much about this but I might be wrong.

Comment (phillip-kruger) [reply core/deployment/src/main/java/io/quarkus/deployment/util/WebJarUtil.java:42]: Ok I added a lock for the file when we create it.

**Comment by phillip-kruger** [comment]
@gsmet - CI get errors on Vertx, even after I rebased. Not sure how to proceed.

File: core/deployment/src/main/java/io/quarkus/deployment/util/WebJarUtil.java (hunk 1 above)
Comment (famod) [reply core/deployment/src/main/java/io/quarkus/deployment/util/WebJarUtil.java:42]: > This is for dev mode

And for tests, no?
Tests might be eve more prone to this. Imagine multiple concurrent builds on a Jenkins CI server (which doesn't run each build in a container).

> the same app

Doesn't need to be the same app. As long as those multiple apps use the same swagger-ui (etc.) version, a clash ist possible.

Btw, we are developing a (very) modular monolith and we in fact fire up multiple dev mode instances (in different submodules) in CI because they broke too often unnoticed.

Comment (phillip-kruger) [reply core/deployment/src/main/java/io/quarkus/deployment/util/WebJarUtil.java:42]: True. There is a lock in place now. Let's handle issues (if any) as we get them ?

Comment (famod) [reply core/deployment/src/main/java/io/quarkus/deployment/util/WebJarUtil.java:42]: > Ok I added a lock for the file when we create it.

This is now done per file? Hm, how many files are there on average?
`FileLock` imposes some overhead so it would be good to limit it to one lock for all files but then again we already have the path check so I might be over-optimizing here...

Comment (phillip-kruger) [reply core/deployment/src/main/java/io/quarkus/deployment/util/WebJarUtil.java:42]: openapi = 8 files
graphql = 9 files
health = 9 files

I think it's ok like this ?

Comment (famod) [reply core/deployment/src/main/java/io/quarkus/deployment/util/WebJarUtil.java:42]: > I think it's ok like this ?

Should be. You don't have any runtime numbers (in ms), do you?

Comment (phillip-kruger) [reply core/deployment/src/main/java/io/quarkus/deployment/util/WebJarUtil.java:42]: Nope

File: core/deployment/src/main/java/io/quarkus/deployment/util/WebJarUtil.java [hunk 2]
```diff
@@ -0,0 +1,150 @@
...
+            ClassLoader classLoader = WebJarUtil.class.getClassLoader();
+            for (Path p : artifact.getPaths()) {
+                File artifactFile = p.toFile();
+                try (JarFile jarFile = new JarFile(artifactFile)) {
+                    Enumeration<JarEntry> entries = jarFile.entries();
+                    while (entries.hasMoreElements()) {
+                        JarEntry entry = entries.nextElement();
+                        if (entry.getName().startsWith(rootFolderInJar) && !entry.isDirectory()) {
+                            try (InputStream inputStream = jarFile.getInputStream(entry)) {
+                                String filename = entry.getName().replace(rootFolderInJar, "");
```
Comment (famod) [inline core/deployment/src/main/java/io/quarkus/deployment/util/WebJarUtil.java:52]: To reduce the overhead for "concurrent access" case, I would pull this line up (out of the `try (InputStream inputStream = ...`) and call `continue` in case the file already exists.

Comment (phillip-kruger) [reply core/deployment/src/main/java/io/quarkus/deployment/util/WebJarUtil.java:52]: Feels like premature optimization.... let's wait and see if it's so bad that people complain ? w.d.y.t ?

Comment (famod) [reply core/deployment/src/main/java/io/quarkus/deployment/util/WebJarUtil.java:52]: Yeah, sure.

**Comment by wtrocki** [comment]
@phillip-kruger Can i help with verification?

**Comment by phillip-kruger** [comment]
@wtrocki - that would be great thanks !!

File: core/deployment/src/main/java/io/quarkus/deployment/util/WebJarUtil.java [hunk 3]
```diff
@@ -0,0 +1,174 @@
...
+import io.quarkus.deployment.pkg.builditem.CurateOutcomeBuildItem;
+
+/**
+ * Utility for Web resource related operations
+ */
+public class WebJarUtil {
+
+    private final static String tmpDir = System.getProperty("java.io.tmpdir");
+    private static final String OWN_MEDIA_FOLDER = "META-INF/branding/";
+    private static final List<String> IGNORE_LIST = Arrays.asList("logo.png", "favicon.ico");
```
Comment (wtrocki) [inline core/deployment/src/main/java/io/quarkus/deployment/util/WebJarUtil.java:35]: Do we see this changing with updates of UI? Maybe having it as property will be better

**Comment by wtrocki** [comment]
Sorry for noob question. How I can start health UI?

File: core/deployment/src/main/java/io/quarkus/deployment/util/WebJarUtil.java (hunk 3 above)
Comment (phillip-kruger) [reply core/deployment/src/main/java/io/quarkus/deployment/util/WebJarUtil.java:35]: Nope. This is added manually by us in SmallRye. All 3 of the current UI's. In SmallRye it's the SmallRye logo. There is a 3rd one coming in later releases, style.css. That will allows users to do better custom branding

**Comment by phillip-kruger** [comment]
> Sorry for noob question. How I can start health UI?

https://quarkus.io/guides/microprofile-health#health-ui

**Comment by wtrocki** [comment]
All seems to be working for me

File: core/deployment/src/main/java/io/quarkus/deployment/util/WebJarUtil.java [hunk 4]
```diff
@@ -0,0 +1,300 @@
...
+        // Clean on non dev mode
+        if (!launch.getLaunchMode().equals(LaunchMode.DEVELOPMENT)) {
+            IoUtils.recursiveDeleteAndThenCreate(path);
+        }
+
+        if (isEmpty(path)) {
+            ClassLoader classLoader = WebJarUtil.class.getClassLoader();
+            for (Path p : artifact.getPaths()) {
+                File artifactFile = p.toFile();
+                try (JarFile jarFile = new JarFile(artifactFile)) {
```
Comment (gastaldi) [inline core/deployment/src/main/java/io/quarkus/deployment/util/WebJarUtil.java:68]: Use `JarFiles.create` from Smallrye Common IO to support MR jars here

File: core/deployment/src/main/java/io/quarkus/deployment/util/WebJarUtil.java [hunk 5]
```diff
@@ -0,0 +1,300 @@
...
+        AppArtifact userApplication = curateOutcomeBuildItem.getEffectiveModel().getAppArtifact();
+
+        Map<String, byte[]> map = new HashMap<>();
+        //we are including in a production artifact
+        //just stick the files in the generated output
+        //we could do this for dev mode as well but then we need to extract them every time
+
+        ClassLoader classLoader = WebJarUtil.class.getClassLoader();
+        for (Path p : artifact.getPaths()) {
+            File artifactFile = p.toFile();
```
Comment (gastaldi) [inline core/deployment/src/main/java/io/quarkus/deployment/util/WebJarUtil.java:127]: Same as above

**Comment by gastaldi** [comment]
@phillip-kruger will this PR supersede https://github.com/quarkusio/quarkus/pull/6314?

**Comment by phillip-kruger** [comment]
Hi @gastaldi - I will probably build that features into SmallRye. But at the moment it does not supersede it. I can look at getting that done in the next PR ?

File: core/deployment/src/main/java/io/quarkus/deployment/util/WebJarUtil.java (hunk 4 above)
Comment (phillip-kruger) [reply core/deployment/src/main/java/io/quarkus/deployment/util/WebJarUtil.java]: Thanks ! Fixed.

File: core/deployment/src/main/java/io/quarkus/deployment/util/WebJarUtil.java (hunk 5 above)
Comment (phillip-kruger) [reply core/deployment/src/main/java/io/quarkus/deployment/util/WebJarUtil.java:128]: Same as above :)

**Comment by phillip-kruger** [comment]
@gastaldi and @gsmet - I made the changes as suggested. Using JarFiles from SR commons and added padding to the default image. Let me know if there is anything else.

**Review by gastaldi — APPROVED** [review]
LGTM. Great job!

**Comment by gastaldi** [comment]
> Hi @gastaldi - I will probably build that features into SmallRye. But at the moment it does not supersede it. I can look at getting that done in the next PR ?

Yes, that would be great! Thank you
