### PR TITLE
QuarkusSecurityTestExtension fails to read class annotation

### LINKED ISSUE #11465: QuarkusSecurityTestExtension fails to read class annotation
**Describe the bug**
In QuarkusSecurityTestExtension#beforeEach() the code tries to load the TestSecurity annotation from the method and falls back to the class if not present on the method. The variable "test" unfortunately is a subclass (e.g. if the test is "mypackage.MyTest" the class will be "mypackage.MyTest_Subclass". Therefore the annotations on the class level is not evaluated.

**Expected behavior**
The class-annotation should be read. A solution for doing so properly in JUnit 5 was described in https://stackoverflow.com/questions/59068813/how-to-obtain-a-field-from-my-test-in-a-junit-5-jupiter-extension

**Actual behavior**
The annotations on the class level is not evaluated.

**To Reproduce**
```
@QuarkusTest
@TestSecurity(user = "tom", roles = { "A","B" })
public class MyTest {
  @BeforeEach
  void beforeEach() {
    // Manual way to show what will fail as this.getClass() return _Subclass
    assertNotNull(this.getClass().getAnnotation(TestSecurity.class));
  }
  @Test
  void mytest() {
    // code showing the effect of trying to read the annotation from _Subclass where it is not present.
    assertNotNull(CDI.current().select(SecurityIdentity.class).get());
  }
}
```

### PR DESCRIPTION
**Pull request by stuartwdouglas**
Fixes #11465

### CODE REVIEW

File: test-framework/security/src/main/java/io/quarkus/test/security/QuarkusSecurityTestExtension.java [hunk 1]
```diff
@@ -37,7 +36,10 @@ public void beforeEach(QuarkusTestMethodContext context) {
                     }).toArray(Class<?>[]::new));
             TestSecurity testSecurity = method.getAnnotation(TestSecurity.class);
             if (testSecurity == null) {
-                testSecurity = test.getAnnotation(TestSecurity.class);
+                testSecurity = original.getAnnotation(TestSecurity.class);
+                while (testSecurity == null && original != Object.class) {
+                    original = original.getSuperclass();
+                }
```
Comment (jaikiran) [inline test-framework/security/src/main/java/io/quarkus/test/security/QuarkusSecurityTestExtension.java:42]: Is this while loop missing an assignment to `testSecurity`? In other words, should that `testSecurity = original.getAnnotation(TestSecurity.class)` be moved into the while loop?

Comment (stuartwdouglas) [reply test-framework/security/src/main/java/io/quarkus/test/security/QuarkusSecurityTestExtension.java:42]: Ah, oops. It still fixes it in this specific case as it is checking the original, however this was supposed to make it work for superclasses as well.

**Review by jaikiran — APPROVED** [review]
