### PR TITLE
Only check if docker is running when redis devservice is needed

### LINKED ISSUE #19599: Setting quarkus.redis.devservices.enabled to false does not work
### Describe the bug

Hi,
Although I set quarkus.redis.devservices.enabled to false, looks like still redis database is tried to be started using docker and start up time goes up to 100 secs in a hello world application. Though, this does not prevent redis client connect to configured database on localhost.

application.properties
`quarkus.redis.devservices.enabled=false`

console log
`Unable to connect to DOCKER_HOST URI tcp://192.168.XX.XXX:2376, make sure docker is running on the specified host`

`2021-08-23 22:01:16,068 WARN  [io.qua.dep.IsDockerWorking] (main) Unable to connect to DOCKER_HOST URI tcp://192.168.99.100:2376, make sure docker is running on the specified host
2021-08-23 22:02:34,924 INFO  [io.quarkus] (Quarkus Main Thread) code-with-quarkus 1.0.0-SNAPSHOT on JVM (powered by Quarkus 2.1.3.Final) started in 101.368s. Listening on: http://localhost:8080
2021-08-23 22:02:34,929 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2021-08-23 22:02:34,931 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [agroal, cdi, hibernate-orm, jdbc-mysql, narayana-jta, redis-client, resteasy, resteasy-jackson, smallrye-context-propagation, vertx]
`

I removed all redis client dependencies and code, left only a simple rest endpoint, I did not see above log happen and start up time was around 1 sec as I expected

### Expected behavior

Skip invoking a redis database using docker. 

### Actual behavior

Run docker to invoke a redis db

### How to Reproduce?

1. Set up local or connect to remote redis
2. Add redis client to gradle.properties
3. Add quarkus.redis.devservices.enabled=false in application.properties
4. Add redis config details of an existing redis db
5. Run the application on IntelliJ using gradle's quarkusDev task

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19043.1165]

### Output of `java -version`

openjdk version "14.0.1" 2020-04-14

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.1.1.Final, 2.1.3.Final and 2.2.0.CR1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 6.9

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by machi1990**
Closes https://github.com/quarkusio/quarkus/issues/19599

### CODE REVIEW

File: extensions/redis-client/deployment/src/main/java/io/quarkus/redis/client/deployment/DevServicesRedisProcessor.java [hunk 1]
```diff
@@ -138,6 +140,15 @@ private StartResult startContainer(String connectionName, DevServicesConfig devS
...
         }
 
+        if (dockerRunning == null) {
+            dockerRunning = new IsDockerRunningSilent().getAsBoolean();
+        }
+
+        if (!dockerRunning) {
+            log.warn("Docker isn't working, please configure the Redis server.");
+            return null;
+        }
```
Comment (gsmet) [inline extensions/redis-client/deployment/src/main/java/io/quarkus/redis/client/deployment/DevServicesRedisProcessor.java:150]: Is it something we do in the other dev services?

Comment (machi1990) [reply extensions/redis-client/deployment/src/main/java/io/quarkus/redis/client/deployment/DevServicesRedisProcessor.java:150]: Good question. I've seen it for Mongo and Kafka but the logs are different.
- https://github.com/quarkusio/quarkus/blob/main/extensions/mongodb-client/deployment/src/main/java/io/quarkus/mongodb/deployment/DevServicesMongoProcessor.java#L134
-  https://github.com/quarkusio/quarkus/blob/main/extensions/kafka-client/deployment/src/main/java/io/quarkus/kafka/client/deployment/DevServicesKafkaProcessor.java#L205

**Review by gsmet — APPROVED** [review]
