### PR TITLE
Ignore Jandex WARNING for all BSON types

### LINKED ISSUE #21949: MongoDB BsonDateTime is not in the Jandex index
### Describe the bug

When building a Quarkus application that is using mongodb-client and mongodb-panache extentions, ReflectiveHierarchyStep outputs:

```
WARN  [io.qua.dep.ste.ReflectiveHierarchyStep] (build-7) Unable to properly register the hierarchy of the following classes for reflection as they are not in the Jandex index:
	- org.bson.BsonDateTime (source: <unknown>)
```

### Expected behavior

Expected behavior after looking at "MongoDB BSON types are not in the Jandex index #17893 " is that there should be NO warning! 

### Actual behavior

A warning is logged stating the following:

```
WARN  [io.qua.dep.ste.ReflectiveHierarchyStep] (build-7) Unable to properly register the hierarchy of the following classes for reflection as they are not in the Jandex index:
	- org.bson.BsonDateTime (source: <unknown>)
```

### How to Reproduce?

To reproduce:

Create a sample application with the  "mongodb-panache" extension

```
mvn io.quarkus:quarkus-maven-plugin:2.5.0.Final:create \
    -DprojectGroupId=com.example\
    -DprojectArtifactId=demo \
    -Dextensions=resteasy,mongodb-client,mongodb-panache
```

Add a sample entity:

```
package com.example;

import io.quarkus.mongodb.panache.common.MongoEntity;
import org.bson.BsonDateTime;
import org.bson.codecs.pojo.annotations.BsonProperty;

@MongoEntity
public class Entity {
    @BsonProperty("time")
    public BsonDateTime time;
}
```

Add sample repository:

```
package com.example;

import io.quarkus.mongodb.panache.PanacheMongoRepositoryBase;

public class Repo implements PanacheMongoRepositoryBase<Entity, String> {
}
```

Build project and observe mentioned message:

`mvn clean package -DskipTests
`

### Output of `uname -a` or `ver`

-

### Output of `java -version`

11

### GraalVM version (if different from Java)

-

### Quarkus version or git rev

2.5.0.final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

`Java version: 11, vendor: Oracle Corporation, runtime: /opt/jdk-11 Default locale: en_US, platform encoding: UTF-8 OS name: "linux", version: "3.10.0-693.17.1.el7.x86_64", arch: "amd64", family: "unix"`

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by loicmathieu**
Fixes #21949

### CODE REVIEW

File: extensions/panache/mongodb-panache-common/deployment/src/main/java/io/quarkus/mongodb/panache/deployment/BasePanacheMongoResourceProcessor.java [hunk 1]
```diff
@@ -381,8 +381,8 @@ protected void processTypes(CombinedIndexBuildItem index,
     }
 
     @BuildStep
-    ReflectiveClassBuildItem registerForReflection() {
-        return new ReflectiveClassBuildItem(true, true, OBJECT_ID.toString());
+    ReflectiveHierarchyIgnoreWarningBuildItem ignoreBsonTypes() {
+        return new ReflectiveHierarchyIgnoreWarningBuildItem(dotname -> dotname.packagePrefix().startsWith("org.bson"));
```
Comment (gsmet) [inline extensions/panache/mongodb-panache-common/deployment/src/main/java/io/quarkus/mongodb/panache/deployment/BasePanacheMongoResourceProcessor.java:385]: I don't remember the specifics but I had some issue with packagePrefix(). I would recommend to do `dotname.toString().startsWith("org.bson.")` (with a dot at the end). Also probably a good idea to make the string a constant.

**Review by gsmet — CHANGES_REQUESTED** [review]

File: extensions/panache/mongodb-panache-common/deployment/src/main/java/io/quarkus/mongodb/panache/deployment/BasePanacheMongoResourceProcessor.java (hunk 1 above)
Comment (loicmathieu) [reply extensions/panache/mongodb-panache-common/deployment/src/main/java/io/quarkus/mongodb/panache/deployment/BasePanacheMongoResourceProcessor.java]: Done

**Review by gsmet — APPROVED** [review]
