### PR TITLE
Fix NPE when setting the logger level to null

### LINKED ISSUE #24358: NullPointer when setting logger level to null
### Describe the bug

_Reported in https://github.com/quarkiverse/quarkus-logging-manager/issues/82 by @survivant_ 

I want to reset a level log.  (LogController.updateLogLevel(loggerName, null);)

in LoggerHandler
````java
private void handlePost(HttpServerRequest request, HttpServerResponse response) {

        String loggerName = request.getFormAttribute(LOGGER_NAME_PARAM);
        String loggerLevel = request.getFormAttribute(LOGGER_LEVEL_PARAM);
        if (loggerLevel == null || loggerLevel.isEmpty()) {
            LogController.updateLogLevel(loggerName, null);
        } else {
            LogController.updateLogLevel(loggerName, loggerLevel);
        }

        response.setStatusCode(201).end();

    }
````

We have this error

````
2021-06-08 13:48:08,608 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-8) HTTP Request to /q/logging-manager/ failed, error id: bd220dfe-9714-481d-a2c0-e1b8318efdd2-1: java.lang.NullPointerException
        at java.logging/java.util.logging.Level.parse(Level.java:478)
        at io.quarkus.vertx.http.runtime.logstream.LogController.updateLogLevel(LogController.java:82)
        at io.quarkiverse.loggingmanager.LoggerHandler.handlePost(LoggerHandler.java:47)
        at io.quarkiverse.loggingmanager.LoggerHandler.handle(LoggerHandler.java:27)
        at io.quarkiverse.loggingmanager.LoggerHandler.handle(LoggerHandler.java:13)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1038)
````

in LogController.updateLogLevel
````java
public static void updateLogLevel(String loggerName, String levelValue) {
        LogContext logContext = LogContext.getLogContext();
        org.jboss.logmanager.Logger logger = logContext.getLogger(loggerName);
        if (logger != null) {
            Level level = org.jboss.logmanager.Level.parse(levelValue);
            logger.setLevel(level);
            LOG.info("Log level updated [" + loggerName + "] changed to [" + levelValue + "]");
        }

    }
````

### Expected behavior

When null is specified, use the parent logger level

### Actual behavior

A NullPointerException is thrown

### How to Reproduce?

Invoke `LogController.updateLogLevel("foo.bar", null);`

### Output of `uname -a` or `ver`

Darwin MacBook-Pro-de-George 21.4.0 Darwin Kernel Version 21.4.0: Mon Feb 21 20:35:58 PST 2022; root:xnu-8020.101.4~2/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

17

### GraalVM version (if different from Java)

None

### Quarkus version or git rev

2.7.5.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8.4

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by gastaldi**
The logger level is set to the parent level if null.

- Fixes #24358

### CODE REVIEW

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/logstream/LogController.java [hunk 1]
```diff
@@ -78,11 +78,18 @@ private LogController() {
     public static void updateLogLevel(String loggerName, String levelValue) {
         LogContext logContext = LogContext.getLogContext();
         Logger logger = logContext.getLogger(loggerName);
-        if (logger != null) {
-            java.util.logging.Level level = Level.parse(levelValue);
-            logger.setLevel(level);
-            LOG.info("Log level updated [" + loggerName + "] changed to [" + levelValue + "]");
+        java.util.logging.Level level;
+        if (levelValue == null || levelValue.trim().isEmpty()) {
```
Comment (gsmet) [inline extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/logstream/LogController.java:82]:
```suggestion
        if (levelValue == null || levelValue.isBlank()) {
```

**Review by gsmet — APPROVED** [review]

**Comment by gastaldi** [comment]
Errors are unrelated
