### PR TITLE
If the node name is longer than 28 bytes, shorten it with SHA-224

### LINKED ISSUE #30491: Generate right-length node name
### Background

Currently, when we pass a value to `quarkus.transaction-manager.node-name` that is too long, the application fails to start with an exception:

```
2023-01-19 17:37:06,788 WARN  [com.arj.ats.arjuna] (Quarkus Main Thread) ARJUNA012138: Node name cannot exceed 28 bytes!
2023-01-19 17:37:06,788 WARN  [com.arj.ats.arjuna] (Quarkus Main Thread) ARJUNA012138: Node name cannot exceed 28 bytes!
2023-01-19 17:37:06,797 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile dev): java.lang.IllegalArgumentException
	at com.arjuna.ats.arjuna.coordinator.TxControl.setXANodeName(TxControl.java:178)
	at io.quarkus.narayana.jta.runtime.NarayanaJtaRecorder.setNodeName(NarayanaJtaRecorder.java:36)
	at io.quarkus.deployment.steps.NarayanaJtaProcessor$build75739834.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.NarayanaJtaProcessor$build75739834.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:110)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:69)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:122)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:103)
	at java.base/java.lang.Thread.run(Thread.java:1589)

2023-01-19 17:37:06,797 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile dev): java.lang.IllegalArgumentException
	at com.arjuna.ats.arjuna.coordinator.TxControl.setXANodeName(TxControl.java:178)
	at io.quarkus.narayana.jta.runtime.NarayanaJtaRecorder.setNodeName(NarayanaJtaRecorder.java:36)
	at io.quarkus.deployment.steps.NarayanaJtaProcessor$build75739834.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.NarayanaJtaProcessor$build75739834.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:110)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:69)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:122)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:103)
	at java.base/java.lang.Thread.run(Thread.java:1589)
```
It would be a better developer experience when if `quarkus-narayana-jta` transformed the value to a valid value.

---

### Story

**AS** a developer
**WHEN** I provide a value for `quarkus.transaction-manager.node-name`
**THEN** the extension `quarkus-narayana-jta` guarantees that the value is transformed to a valid node name if necessary.

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by turing85**
Resolves #30491

### CODE REVIEW

**Review by mmusgrov — APPROVED** [review]
Thanks

**Comment by turing85** [comment]
@mmusgrov you're welcome :slightly_smiling_face:

**Review by mmusgrov — CHANGES_REQUESTED** [review]
Since approving the PR I've received some concerns about this change. The requests are:
  - to change the log message from info to warn
  - to ask users to opt into the change via a config property that controls whether or not shortening of the node id should be allowed

In addition, we have a similar problem in WildFly and Narayana so I will start a discussion in the [narayana-users forum](https://groups.google.com/g/narayana-users) about adding the feature to Narayana so that all runtimes can benefit from the change.

**Comment by turing85** [comment]
> Since approving the PR I've received some concerns about this change. The requests are:
> 
>     * to change the log message from info to warn
> 
>     * to ask users to opt into the change via a config property that controls whether or not shortening of the node id should be allowed
> 
> 
> In addition, we have a similar problem in WildFly and Narayana so I will start a discussion in the [narayana-users forum](https://groups.google.com/g/narayana-users) about adding the feature to Narayana so that all runtimes can benefit from the change.

So... should I implement those changes, or do we want to wait for the result of the discussion?

**Comment by mmusgrov** [comment]
> So... should I implement those changes, or do we want to wait for the result of the discussion?

Personally I'd say that the only one up for debate is the default value for the property. If the default is to fail the boot, the current behaviour, then the user will detect the issue during the commissioning phase so I'd maybe lean a little in that direction, besides, it would minimise surprise for existing users. Let's give people a couple of days to respond and if nothing is forthcoming then we should decide.

**Comment by marcosgopen** [comment]
> > So... should I implement those changes, or do we want to wait for the result of the discussion?
> 
> Personally I'd say that the only one up for debate is the default value for the property. If the default is to fail the boot, the current behaviour, then the user will detect the issue during the commissioning phase so I'd maybe lean a little in that direction, besides, it would minimise surprise for existing users. Let's give people a couple of days to respond and if nothing is forthcoming then we should decide.

I agree with Mike. I think that the default behaviour of the property is to fail the boot. If user want to change this behaviour they need to change the value of the property, in this way they will be aware that the 'node name' might change from the expected one because it will be shorten with SHA-224.

**Comment by turing85** [comment]
@mmusgrov I added the changes (they were minimal). The property name is of course up to debate, but the change is trivial.

**Review by mmusgrov — APPROVED** [review]
Looks great.

@turing85 There were no comments on the message that I posted to the narayana google users group so I think this is ready for merging.

**Comment by turing85** [comment]
> Looks great.
> 
> @turing85 There were no comments on the message that I posted to the narayana google users group so I think this is ready for merging.

Okay, then all that is left to do is an approval (github still says that merging is blocked and that an approval is needed). @maxandersen Can you approve this one?

**Review by gastaldi — APPROVED** [review]

**Comment by gsmet** [comment]
Thanks!

File: extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/TransactionManagerConfiguration.java [hunk 1]
```diff
@@ -16,10 +16,24 @@
...
+    /**
+     * Whether the node name should be shortened if necessary.
+     * The node name must not exceed a length of 28 bytes. If this property is set to {@code true}, and the node name exceeds 28
+     * bytes, the node name is shortened by calculating the <a href="https://en.wikipedia.org/wiki/SHA-2">SHA-224</a> hash,
+     * which has a length of 28 bytes.
+     *
+     * @see #nodeName
+     */
+    @ConfigItem(defaultValue = "false")
+    public boolean shortenNodeNameIfNecessary;
```
Comment (gastaldi) [inline extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/TransactionManagerConfiguration.java:35]: How about naming it simply `truncateNodeName`? The `ifNecessary` makes my chin itch a bit 😀

Comment (gastaldi) [reply extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/TransactionManagerConfiguration.java:35]: How about making it true by default as a precaution?

Comment (maxandersen) [reply extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/TransactionManagerConfiguration.java:35]: this is not truncation. Truncate is rather abrupt/finite in nature.

maybe compress as this will be a lossy-but-hopefully-not-significant-compression ?


btw. why the "ifNecessary" part ? if its necessary why is it not true by default?

Comment (maxandersen) [reply extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/TransactionManagerConfiguration.java:35]: i.e. since this seems necessary I would argue it should be default on and possible to turn off. At least in main with good release note metnion - if this was for LTS branch I could see how one could argue it should stay off.

Am I missing something?

Comment (gastaldi) [reply extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/TransactionManagerConfiguration.java:35]: > this is not truncation. Truncate is rather abrupt/finite in nature.
> 
> maybe compress as this will be a lossy-but-hopefully-not-significant-compression ?

Right, `compress` makes more sense

> 
> btw. why the "ifNecessary" part ? if its necessary why is it not true by default?

+1

Comment (gastaldi) [reply extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/TransactionManagerConfiguration.java:35]: Maybe it's less unlikely to happen, but would it truncating be a problem if the algorithm isn't available?

Comment (turing85) [reply extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/TransactionManagerConfiguration.java:35]: > How about making it true by default as a precaution?

@gastaldi https://github.com/quarkusio/quarkus/pull/36752#pullrequestreview-1703877795

Comment (turing85) [reply extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/TransactionManagerConfiguration.java:35]: > Maybe it's less unlikely to happen, but would truncating be a problem if the algorithm isn't available?

Hard to say. This depends how the node names are constructed. If one has long names and a common prefix, then this might lead to name duplication.

Comment (mmusgrov) [reply extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/TransactionManagerConfiguration.java:35]: > > btw. why the "ifNecessary" part ? if its necessary why is it not true by default?

Historically the default is to fail startup if the nodeIdentifier, set by the user or the platform, is too long. Since the use of a hash incurs the risk of collisions and can result in non ACID behaviour it should not be the default - the user has to opt in to the added risk of using a hash since only they can quantify the risk to their application.

Comment (maxandersen) [reply extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/TransactionManagerConfiguration.java:35]: ok, how about simply "hashNodeNameIfNecessary" or simply "hashNodeName" which still will only happen if needed but with hash it at least signals what happens and collision awareness could be necessary.

Comment (mmusgrov) [reply extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/TransactionManagerConfiguration.java:35]: Sounds reasonable.
