### PR TITLE
ArC - ignore decorators during bean discovery

### LINKED ISSUE #18200: Decorating QuarkusApplication won't build
## Describe the bug
Creating a decorator for the `QuarkusApplication` interface gives a build error about only decorators can declare a delegate (even if the decorator is properly marked as `@Decorator`)

### Expected behavior
According to conversation on Zulip, this should work, so the app should build and the whole Quarkus execution decorated

### Actual behavior
Build error:
```java
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:2.0.0.CR3:build (default) on project app: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: Only decorators can declare a delegate injection point: CLASS bean [types=[io.quarkus.runtime.QuarkusApplication, java.lang.Object, AppDecorator], qualifiers=[@Default, @Any], target=AppDecorator]
[ERROR] 	at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:457)
```

## To Reproduce

Reproducer: [main-decorator.zip](https://github.com/quarkusio/quarkus/files/6726011/main-decorator.zip)

1. Just build with Maven

### Output of `uname -a` or `ver`
`Darwin xtaixe 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64`

### Output of `java -version`
```
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment GraalVM CE 21.1.0 (build 11.0.11+8-jvmci-21.1-b05)
OpenJDK 64-Bit Server VM GraalVM CE 21.1.0 (build 11.0.11+8-jvmci-21.1-b05, mixed mode, sharing)
```

### Quarkus version or git rev
`2.0.0.CR3`

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
```
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: /Users/xtaixe/.mvnvm/apache-maven-3.8.1
Java version: 11.0.11, vendor: GraalVM Community, runtime: /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.1.0/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "11.4", arch: "x86_64", family: "mac"
```

### PR DESCRIPTION
**Pull request by mkouba**
- also fail the build if a decorator declares any other scope than
Dependent
- do not register QuarkusApplication decorators as additional beans
- resolves #18200

### CODE REVIEW

File: independent-projects/arc/tests/src/test/java/io/quarkus/arc/test/decorators/validation/NonDependentScopeTest.java [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+        assertNotNull(container.getFailure());
+        assertTrue(
+                container.getFailure().getMessage()
+                        .contains("DecoratorWithWrongScope must be @Dependent: javax.enterprise.context.ApplicationScoped"),
+                container.getFailure().getMessage());
+    }
+
+    interface Converter<T, U> {
+
+        T convert(T value);
```
Comment (Ladicek) [inline independent-projects/arc/tests/src/test/java/io/quarkus/arc/test/decorators/validation/NonDependentScopeTest.java:32]: One of the `T`s here should probably be `U` :rofl:

Comment (mkouba) [reply independent-projects/arc/tests/src/test/java/io/quarkus/arc/test/decorators/validation/NonDependentScopeTest.java:32]: Yeah, but that's not the point of this test, right? :D

**Review by Ladicek — APPROVED** [review]
LGTM, though I'd probably change the error message for non-dependent decorators slightly. `The decorator com.example.MyDecorator must be @Dependent: javax.enterprise.context.ApplicationScoped` reads weird. At least add "was" or something like that: `The decorator com.example.MyDecorator must be @Dependent, was: javax.enterprise.context.ApplicationScoped`

File: independent-projects/arc/tests/src/test/java/io/quarkus/arc/test/decorators/validation/NonDependentScopeTest.java (hunk 1 above)
Comment (Ladicek) [reply independent-projects/arc/tests/src/test/java/io/quarkus/arc/test/decorators/validation/NonDependentScopeTest.java:32]: Sure, I don't really understand decorators, so I have to look for things like this :laughing:

**Review by Ladicek — APPROVED** [review]

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Decorators.java [hunk 2]
```diff
@@ -49,6 +49,11 @@ static DecoratorInfo createDecorator(ClassInfo decoratorClass, BeanDeployment be
                 priority = annotation.value().asInt();
                 priorityDeclared = true;
             }
+            ScopeInfo scopeAnnotation = beanDeployment.getScope(annotation.name());
+            if (scopeAnnotation != null && !BuiltinScope.DEPENDENT.is(scopeAnnotation)) {
+                throw new DefinitionException(
```
Comment (manovotn) [inline independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Decorators.java:54]: Speaking of what decorator can and cannot do - what about decorators for `BeanManager` type? Specification [forbids that](https://jakarta.ee/specifications/cdi/2.0/cdi-spec-2.0.html#decorators) as well; should we make sure it doesn't work as part of this PR?

**Review by manovotn — APPROVED** [review]
Looks good, added just one question which is not even fully related to the problem solved in this PR :)

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Decorators.java (hunk 2 above)
Comment (mkouba) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Decorators.java:54]: Hm, I think that `BeanManager` is not even injectable in ArC, i.e. there is no built-in bean of that type and so you won't be able to decorate it unless you explicitly produce it.

Comment (manovotn) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Decorators.java:54]: Oh, I automatically assumed that we have such bean. My bad, forget I said anything :)

**Comment by mkouba** [comment]
Ping @sberyozkin. Do you happen to know why these `io.quarkus.elytron.security.jdbc.CustomRoleDecoderDevModeTest` tests failed?

**Comment by stuartwdouglas** [comment]
I will look into it, I have made changes there recently.

**Comment by stuartwdouglas** [comment]
https://github.com/quarkusio/quarkus/pull/18261
