### PR TITLE
Register `oracle.jdbc.OracleDriver` for reflection

### LINKED ISSUE #53517: Native build cannot detect Flyway Oracle support for manual Flyway.configure() usage from a dependency JAR, while JVM works
### Describe the bug

I have a Quarkus application that depends on an internal library. That library creates Flyway instances programmatically with `Flyway.configure()` instead of using Quarkus-managed Flyway/datasource wiring, because we need custom tenant-specific migration flows.

This works on JVM, but the native executable fails at startup with:

```text
org.flywaydb.core.api.FlywayException: No database found to handle jdbc:oracle:thin:@localhost:1521/XEPDB1
```

What is confusing is:

- Oracle Flyway support works fine on JVM
- the dependency JAR contains flyway-database-oracle
- the dependency JAR also contains META-INF/native-image/... metadata
- the failure only happens in the downstream Quarkus app when building/running native
- I would like to understand whether this is expected for manual Flyway usage in native mode, or whether Quarkus should honor dependency-provided native metadata for this case.

Expected behavior
If a Quarkus app includes:

- quarkus-flyway
- quarkus-jdbc-oracle
- quarkus-flyway-oracle
- flyway-database-oracle

and a dependency JAR provides the required native metadata under META-INF/native-image/..., then a manually created Flyway instance like this should also work in a native build:

```java
Flyway.configure()
    .dataSource(jdbcUrl, username, password)
    .baselineOnMigrate(true)
    .locations("classpath:flyway-migrate/org/0_baseline")
    .load()
    .migrate();
```

This is not using Quarkus-managed Flyway beans intentionally. The library needs to:

- resolve tenant DB URLs dynamically
- run multiple migration phases
- use custom history table names per tenant/phase

So switching back to Quarkus-managed Flyway/datasource wiring is not the path I am trying to take.

What I tried
In the library JAR, I added native metadata under:

```text
META-INF/native-image/org.acme/commons/
```

including:

- reflect-config.json
- resource-config.json
- native-image.properties
- reachability-metadata.json

The metadata includes:

reflection for:
- org.flywaydb.database.oracle.OracleDatabaseType
- org.flywaydb.database.oracle.OracleConfigurationExtension

resource/service inclusion for:
- META-INF/services/org.flywaydb.core.extensibility.Plugin

runtime init for:
- org.flywaydb.core.internal.database.DatabaseTypeRegister
- org.flywaydb.core.internal.plugin.PluginRegister

The metadata is definitely present in the built dependency JAR.

Even with that, the downstream Quarkus app still fails in native mode.

### Expected behavior

Manually created Flyway instance like this should also work in a native build
```java
Flyway.configure()
    .dataSource(jdbcUrl, username, password)
    .baselineOnMigrate(true)
    .locations("classpath:flyway-migrate/emsd/0_baseline")
    .load()
    .migrate();
```

### Actual behavior

JVM mode works:

```
Database: jdbc:oracle:thin:@localhost:1521/XEPDB1 (Oracle 21.3)
...
Successfully applied 1 migration
```

Native mode fails very early:

```
Caused by: org.flywaydb.core.api.FlywayException: No database found to handle jdbc:oracle:thin:@localhost:1521/XEPDB1
    at org.flywaydb.core.internal.jdbc.DriverDataSource.<init>(DriverDataSource.java:158)
    at org.flywaydb.core.api.configuration.ClassicConfiguration.setDataSource(ClassicConfiguration.java:1547)
    at org.flywaydb.core.api.configuration.FluentConfiguration.dataSource(FluentConfiguration.java:635)
```

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by gastaldi**
- Flyway expects `oracle.jdbc.OracleDriver` when using unmanaged datasources
- Fixes #53517
- Follow-up from #53528

### CODE REVIEW

File: extensions/jdbc/jdbc-oracle/deployment/src/main/java/io/quarkus/jdbc/oracle/deployment/OracleNativeImage.java [hunk 1]
```diff
@@ -28,8 +28,10 @@ void reflection(BuildProducer<ReflectiveClassBuildItem> reflectiveClass,
         //We register it for the sake of people not using Agroal.
         // "oracle.jdbc.OracleDriver" is what's listed in the serviceloader resource from Oracle,
         // but it delegates all use to "oracle.jdbc.driver.OracleDriver" - which is also what's recommended by the docs.
-        final String driverName = "oracle.jdbc.driver.OracleDriver";
-        reflectiveClass.produce(ReflectiveClassBuildItem.builder(driverName).build());
+        // Flyway's OracleDatabaseType also returns "oracle.jdbc.OracleDriver" as the driver class name,
+        // so we need to make sure both are registered for reflection.
+        reflectiveClass.produce(ReflectiveClassBuildItem.builder("oracle.jdbc.driver.OracleDriver",
+                "oracle.jdbc.OracleDriver").build());
```
Comment (gastaldi) [inline extensions/jdbc/jdbc-oracle/deployment/src/main/java/io/quarkus/jdbc/oracle/deployment/OracleNativeImage.java:34]: Another solution would be to substitute `org.flywaydb.database.oracle.OracleDatabaseType#getDriverClass` but I believe there would be other cases requiring it

**Review by gsmet — APPROVED** [review]
I think it makes sense to register both.

**Comment by gsmet** [comment]
From what I can see, the user posted a reproducer here: https://github.com/reevelau/reproducer-53517

**Comment by gastaldi** [comment]
Yes, I tested with his reproducer before submitting this PR

**Comment by gsmet** [comment]
Awesome, let's merge then!
