### PR TITLE
Make sure that Funqy types are registered for reflection

### LINKED ISSUE #12019: Funqy QueryObjectReader not working in native image.
**Describe the bug**

Funqy QueryObjectReader not working in native image.

Note that jackson object reader works fine.

**Expected behavior**

```shell
curl -v "http://localhost:8080/greet?name=Matej" 
*   Trying ::1:8080...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> GET /greet?name=Matej HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.66.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: application/json
< content-length: 41
< 
* Connection #0 to host localhost left intact
{"name":"Matej","message":"Hello Matej!"}
```

**Actual behavior**
To reproduce call sample greeting function:
```shell
curl -v "http://localhost:8080/greet?name=Matej"              
*   Trying ::1:8080...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> GET /greet?name=Matej HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.66.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< content-length: 0
< 
* Connection #0 to host localhost left intact

```

In the application log:
```
2020-09-10 01:00:37,280 INFO  [io.quarkus] (main) funq-demo 1.0-SNAPSHOT native (powered by Quarkus 1.8.0.CR1) started in 0.029s. Listening on: http://0.0.0.0:8080
2020-09-10 01:00:37,280 INFO  [io.quarkus] (main) Profile prod activated. 
2020-09-10 01:00:37,280 INFO  [io.quarkus] (main) Installed features: [cdi, funqy-http]
2020-09-10 01:00:39,752 ERROR [io.qua.funqy] (vert.x-eventloop-thread-0) Failed to unmarshal input: java.lang.RuntimeException: java.lang.InstantiationException: Type `org.funqy.demo.Identity` can not be instantiated reflectively as it does not have a no-parameter constructor or the no-parameter constructor has not been added explicitly to the native image.                                                 











        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:133)
        at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:54)
        at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:36)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$9.handle(VertxHttpRecorder.java:392)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$9.handle(VertxHttpRecorder.java:389)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$1.handle(VertxHttpRecorder.java:133)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$1.handle(VertxHttpRecorder.java:122)
        at io.vertx.core.http.impl.WebSocketRequestHandler.handle(WebSocketRequestHandler.java:50)
        at io.vertx.core.http.impl.WebSocketRequestHandler.handle(WebSocketRequestHandler.java:32)
        at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:136)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
        at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
        at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:229)
        at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:173)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
        at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:101)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.vertx.core.http.impl.Http1xUpgradeToH2CHandler.channelRead(Http1xUpgradeToH2CHandler.java:109)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.vertx.core.http.impl.Http1xOrH2CHandler.end(Http1xOrH2CHandler.java:61)
        at io.vertx.core.http.impl.Http1xOrH2CHandler.channelRead(Http1xOrH2CHandler.java:38)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:834)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
Caused by: java.lang.InstantiationException: Type `org.funqy.demo.Identity` can not be instantiated reflectively as it does not have a no-parameter constructor or the no-parameter constructor has not been added explicitly to the native image.
        at java.lang.Class.newInstance(DynamicHub.java:830)
        at io.quarkus.funqy.runtime.query.QueryObjectReader.create(QueryObjectReader.java:22)
        ... 69 more
```

### PR DESCRIPTION
**Pull request by geoand**
Done in a way very similar to what we do for RESTEasy

Fixes: #12019

cc @matejvasek

### CODE REVIEW

**Comment by geoand** [comment]
No test was added because it looks like we don't have an integration test for funqy-http

File: extensions/funqy/funqy-server-common/deployment/src/main/java/io/quarkus/funqy/deployment/FunctionScannerBuildStep.java [hunk 1]
```diff
@@ -63,6 +70,34 @@ public void scanFunctions(BeanArchiveIndexBuildItem beanArchiveIndexBuildItem,
             if (functionName != null && functionName.isEmpty())
                 functionName = null;
             functions.produce(new FunctionBuildItem(className, methodName, functionName));
+
+            String source = FunctionScannerBuildStep.class.getSimpleName() + " > " + method.declaringClass() + "[" + method
+                    + "]";
+
+            Type returnType = method.returnType();
+            if (returnType.kind() != Type.Kind.VOID) {
+                reflectiveHierarchy.produce(new ReflectiveHierarchyBuildItem.Builder()
```
Comment (matejvasek) [inline extensions/funqy/funqy-server-common/deployment/src/main/java/io/quarkus/funqy/deployment/FunctionScannerBuildStep.java:79]: If the return type Uni<T> doesn't this register whole Uni<T>  instead of just T?
We do some processing related to this in `FunctionInvoker`.

If possible maybe registration of FunctionInvoker::inputType and FunctionInvoker::outputType should be sufficient.

Comment (geoand) [reply extensions/funqy/funqy-server-common/deployment/src/main/java/io/quarkus/funqy/deployment/FunctionScannerBuildStep.java:79]: I'll check it out later on today or tomorrow morning

Comment (geoand) [reply extensions/funqy/funqy-server-common/deployment/src/main/java/io/quarkus/funqy/deployment/FunctionScannerBuildStep.java:79]: PR updated to exclude Mutiny types (the generics types **do** get registered however).

We don't need the output of `FunctionInvoker::inputType` or `FunctionInvoker::outputType` as we already know the types that need to be registered at build time by just looking at the method signatures (same as RESTEasy)

File: extensions/funqy/funqy-server-common/deployment/src/main/java/io/quarkus/funqy/deployment/ReflectionRegistrationUtil.java [hunk 2]
```diff
@@ -0,0 +1,64 @@
...
+        @Override
+        public boolean test(MethodInfo methodInfo) {
+            return methodInfo.hasAnnotation(JSON_IGNORE)
+                    || methodInfo.hasAnnotation(JSONB_TRANSIENT);
+        }
+    }
+
+    private static final String[] PACKAGES_IGNORED_FOR_REFLECTION = {
+            // Mutiny
+            // TODO: should this be in ReflectiveHierarchyBuildItem.DefaultIgnoreTypePredicate?
```
Comment (gsmet) [inline extensions/funqy/funqy-server-common/deployment/src/main/java/io/quarkus/funqy/deployment/ReflectionRegistrationUtil.java:61]: I don't think so. It should be in the RESTEasy ones though.

Basically, we need to ignore them if we have some special handling for them, which is the case for RESTEasy.

**Review by gsmet — COMMENTED** [review]
Looks good overall I think. I just added a small comment for the TODO.

File: extensions/funqy/funqy-server-common/deployment/src/main/java/io/quarkus/funqy/deployment/ReflectionRegistrationUtil.java (hunk 2 above)
Comment (geoand) [reply extensions/funqy/funqy-server-common/deployment/src/main/java/io/quarkus/funqy/deployment/ReflectionRegistrationUtil.java:61]: I don't see us ignoring the Mutiny types in RESTEasy, or perhaps I am just missing something?

**Comment by geoand** [comment]
This is good to go from my point of view

File: extensions/funqy/funqy-server-common/deployment/src/main/java/io/quarkus/funqy/deployment/ReflectionRegistrationUtil.java (hunk 2 above)
Comment (gsmet) [reply extensions/funqy/funqy-server-common/deployment/src/main/java/io/quarkus/funqy/deployment/ReflectionRegistrationUtil.java:61]: Yeah, what I was saying is that we probably should. And definitely not do it in the generic ReflectiveHierarchyBuildItem.

Comment (geoand) [reply extensions/funqy/funqy-server-common/deployment/src/main/java/io/quarkus/funqy/deployment/ReflectionRegistrationUtil.java:61]: Okay, I'll update the PR later on

Comment (geoand) [reply extensions/funqy/funqy-server-common/deployment/src/main/java/io/quarkus/funqy/deployment/ReflectionRegistrationUtil.java]: Done

**Review by gsmet — APPROVED** [review]
