### PR TITLE
Dispatch Mutiny scheduled operations using Vert.x timers when possible

### LINKED ISSUE #50918: Delaying a `Uni` should not move the context to an executor thread in Quarkus
When writing some reactive code you can delay a `Uni` by a certain duration:

```java
Uni.createFrom().item("item").onItem().delayIt().by(Duration.ofSeconds(1))
```

See https://smallrye.io/smallrye-mutiny/latest/guides/delaying-events/

If you then start combining this with Hibernate Reactive you will get big stacktraces telling you not to do this as it's not allowed.

```
HR000069: Detected use of the reactive Session from a different Thread than the one which was used to open the reactive Session - this suggests an invalid integration; original thread [222]: 'vert.x-eventloop-thread-2' current Thread [214]: 'executor-thread-1'
```

And the error is correct, as the delay gets scheduled on a worker thread and not on the event loop, see https://github.com/smallrye/smallrye-mutiny/blob/main/implementation/src/main/java/io/smallrye/mutiny/groups/UniOnItemDelay.java#L34

I created a small reproducer based on a quickstart to showcase this, see https://github.com/quarkusio/quarkus-quickstarts/compare/main...wjglerum:panache-transaction-delay

Here you can see that after the delay it now runs on a worker thread:

```
2025-11-05 16:12:32,724 INFO  [org.acm.hib.orm.pan.FruitResource] (vert.x-eventloop-thread-2) Fruit<1>
2025-11-05 16:12:33,730 INFO  [org.acm.hib.orm.pan.FruitResource] (executor-thread-1) Fruit<1>
```

After discussing on Zulip (see https://quarkusio.zulipchat.com/#narrow/channel/187030-users/topic/Quarkus.20Hibernate.20Reactive.20Panache.20with.20a.20delay.20in.20a.20Uni/with/554127730) we figured out that you can set a custom executor to fix this:

```java
.onItem().delayIt()
.onExecutor(ContextAwareScheduler.delegatingTo(Infrastructure.getDefaultWorkerPool()).withCurrentContext())
.by(Duration.ofSeconds(1))
```

Also see the docs here https://quarkus.io/guides/vertx-reference#use-a-vert-x-context-aware-scheduler

And now you can see both log statements are printed from the event loop thread:

```
2025-11-06 15:57:20,740 INFO  [org.acm.hib.orm.pan.FruitResource] (vert.x-eventloop-thread-2) Fruit<1>
2025-11-06 15:57:21,745 INFO  [org.acm.hib.orm.pan.FruitResource] (vert.x-eventloop-thread-2) Fruit<1>
```

This can be very confusing for users while programming, as it happens quite unexpectedly. 

Could we somehow make Quarkus either do this automatically for us with the `ContextAwareScheduler` for delays? Or leverage Vertx somehow under the hood to schedule the delay with Vertx timers on the event loop?

### PR DESCRIPTION
**Pull request by jponge**
Some Mutiny operations such as delaying an item, performing a retry, or generating streams
from periodic ticks all require a ScheduledExecutorService.

This introduces a wrapper ScheduledExecutorService that dispatches some of the operations
to Vert.x timers when called from a Vert.x event-loop, offering a more natural threading
mental model as well as avoiding thread hops between worker threads and event-loops.

The implementation only tunes Mutiny with that Vert.x-aware wrapper ScheduledExecutorService
from the quarkus-vertx extension because non-server applications might not have Vert.x available.

We also introduce an artificial build item in the Mutiny extension to ensure that the Vert.x build
items always execute after those from Mutiny, or else we could have cases where Mutiny re-installs
a non-Vert.x aware scheduler in its own configuration.

- Fixes: #50918

### CODE REVIEW

**Comment by wjglerum** [comment]
Thank you for this improvement! Just tried it out locally and I can remove my workaround :)

**Comment by jponge** [comment]
Thanks @wjglerum that's good news!

I'm waiting for some CI runs to see if anything suspicious is here.

**Review by FroMage — APPROVED** [review]

**Comment by jponge** [comment]
Thanks @FroMage 

It worked on my local CI

**Comment by jponge** [comment]
Also ping @vietj

**Review by geoand — APPROVED** [review]

**Review by cescoffier — APPROVED** [review]

File: extensions/vertx/runtime/src/main/java/io/quarkus/vertx/core/runtime/VertxTimerAwareScheduledExecutorService.java [hunk 1]
```diff
@@ -0,0 +1,199 @@
...
+import io.vertx.core.Vertx;
+
+/**
+ * A wrapper for {@link ScheduledExecutorService} that dispatches some of the operations using Vert.x timers
+ * when called from Vert.x event-loops, else it just dispatches to a delegate {@link ScheduledExecutorService}.
+ *
+ * This class is used to keep some Mutiny scheduled operations on a Vert.x event-loop thread rather than hop
+ * to a worker thread: delaying items, retries on failures, streams of periodic ticks, etc.
+ */
+public final class VertxTimerAwareScheduledExecutorService implements ScheduledExecutorService {
```
Comment (ozangunalp) [inline extensions/vertx/runtime/src/main/java/io/quarkus/vertx/core/runtime/VertxTimerAwareScheduledExecutorService.java]: In Quarkus core Utils we've `ForwardingExecutorService` and `ForwardingScheduledExecutorService` for the delegation.

**Review by ozangunalp — APPROVED** [review]
A small note for the ExecutorService delegation, otherwise looks good!

File: extensions/vertx/runtime/src/main/java/io/quarkus/vertx/core/runtime/VertxTimerAwareScheduledExecutorService.java (hunk 1 above)
Comment (jponge) [reply extensions/vertx/runtime/src/main/java/io/quarkus/vertx/core/runtime/VertxTimerAwareScheduledExecutorService.java]: Good catch, I didn't knew about this one!

Comment (jponge) [reply extensions/vertx/runtime/src/main/java/io/quarkus/vertx/core/runtime/VertxTimerAwareScheduledExecutorService.java]: Let me fix that, less lines of code is always better.

Comment (jponge) [reply extensions/vertx/runtime/src/main/java/io/quarkus/vertx/core/runtime/VertxTimerAwareScheduledExecutorService.java]: Done, @ozangunalp if you want to have a look
