### PR TITLE
Fix quarkus-quartz duplicating clustered jobs

### LINKED ISSUE #8661: quarkus-quartz duplicating clustered jobs
**Describe the bug**
When more than one job is configured with quarkus-quartz in a clustered environment we are seeing a duplication on the registered db jobs.

The jobs are registred like this:
```
 @Scheduled(cron = "{full.qualified.classA.cron}")
  void schedule()
...
 @Scheduled(cron = "{full.qualified.classB.cron}")
 void executeJob()
```
Then, 2 instances of the service are started but the problem also happens with just a single instance.

On the the qrtz_triggers.trigger_name column we will see new jobs like this:
```
0_full.qualified.classA_ScheduledInvoker_executeJob_952519a823738725fb11b965dd917e07b656fb4d
1_full.qualified.classB_ScheduledInvoker_schedule_dce0524c3f1de653f83719900424446459b7c471
```
If we stop the service and start it again enough times, at some point we will see:
```
0_full.qualified.classA_ScheduledInvoker_executeJob_952519a823738725fb11b965dd917e07b656fb4d
1_full.qualified.classB_ScheduledInvoker_schedule_dce0524c3f1de653f83719900424446459b7c471
0_full.qualified.classB_ScheduledInvoker_schedule_dce0524c3f1de653f83719900424446459b7c471
0_full.qualified.classA_ScheduledInvoker_executeJob_952519a823738725fb11b965dd917e07b656fb4d
```
As you can see, the first digit changes, thus dupluting the jobs.

After inspecting the code here:
https://github.com/quarkusio/quarkus/blob/ffc1c5b9423a47cf441d0f860f82312dbb266658/extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java#L97

We can see that the 1st digit is an increment. We can asusme that the job order is not always the same and this increment later causes the duplication.

Job creation is not deterministic. 

We are using quarkus 1.2.1.Final, but the above link is from the latest and seems to have the issue as well.

**Expected behavior**
Clustered jobs should not be duplicated.

**Actual behavior**
Clustered jobs are being duplicated.

**To Reproduce**
see description

**Configuration**
```properties
full.qualified.classA.cron=0 0 * * * ?
full.qualified.classB.cron=0 0 * * * ?
```

**Screenshots**
no need

**Environment (please complete the following information):**
 - PostgreSQL 11.2-alpine 
 - Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T20:00:29+01:00)
Maven home: /Users/joao.rafael/Software/apache-maven-latest
Java version: 14, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/adoptopenjdk-14.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.6", arch: "x86_64", family: "mac"
- This also happens with Java 11.

**Additional context**
none

### PR DESCRIPTION
**Pull request by machi1990**
Fix #8661 

The first commit should fix the issue. Upon my attempt to reproduce it I came to a conclusion that this only occurs if you re-build the application but once the application is built, the name ("identity") is maintained across several runs as the list of triggers (methods) has already been recorded - during deployment time. 

/cc @mkouba @gsmet opening as draft to get feedback

/cc @brunobat & @joao-rafael-tdx this should address the issue.

### CODE REVIEW

File: extensions/scheduler/deployment/src/main/java/io/quarkus/scheduler/deployment/SchedulerProcessor.java [hunk 1]
```diff
@@ -117,27 +115,21 @@ public void transform(TransformationContext context) {
...
 
     @BuildStep
-    void collectScheduledMethods(
-            SchedulerConfig config,
-            BeanArchiveIndexBuildItem beanArchives,
-            BeanRegistrationPhaseBuildItem beanRegistrationPhase,
-            BuildProducer<ScheduledBusinessMethodItem> scheduledBusinessMethods,
-            BuildProducer<BeanConfiguratorBuildItem> beans) {
+    void collectScheduledMethods(BeanArchiveIndexBuildItem beanArchives, BeanRegistrationPhaseBuildItem beanRegistrationPhase,
+            BuildProducer<ScheduledBusinessMethodItem> scheduledBusinessMethods) {
```
Comment (mkouba) [inline extensions/scheduler/deployment/src/main/java/io/quarkus/scheduler/deployment/SchedulerProcessor.java:119]: You can't remove the `BuildProducer<BeanConfiguratorBuildItem> beans` even though it's unused. This ensures this build step is executed before `ArcProcessor#validate()`. See the `BeanRegistrationPhaseBuildItem` javadoc.

File: extensions/scheduler/runtime/src/main/java/io/quarkus/scheduler/Scheduled.java [hunk 2]
```diff
@@ -39,6 +39,16 @@
...
 
+    /**
+     * Optionally defines a unique identifier for this job.
+     * <p>
+     * If the value is not given, Quarkus will generate a unique id.
+     * <p>
+     * 
+     * @return the unique identity of the schedule
+     */
+    String identity() default "";
```
Comment (mkouba) [inline extensions/scheduler/runtime/src/main/java/io/quarkus/scheduler/Scheduled.java:50]: We should also use `Scheduled.identity()` in the `SimpleScheduler`.

File: extensions/scheduler/deployment/src/main/java/io/quarkus/scheduler/deployment/SchedulerProcessor.java (hunk 1 above)
Comment (machi1990) [reply extensions/scheduler/deployment/src/main/java/io/quarkus/scheduler/deployment/SchedulerProcessor.java:119]: Good catch. I might have gone a bit fast on that one. Let's keep it.

File: extensions/scheduler/runtime/src/main/java/io/quarkus/scheduler/Scheduled.java (hunk 2 above)
Comment (machi1990) [reply extensions/scheduler/runtime/src/main/java/io/quarkus/scheduler/Scheduled.java:50]: Yes, I forgot about that one. Should be good now.

**Comment by machi1990** [comment]
@mkouba I have taken into account the your comments. What do you think about the approach? Can this PR be promoted?

File: extensions/scheduler/runtime/src/main/java/io/quarkus/scheduler/runtime/SimpleScheduler.java [hunk 3]
```diff
@@ -148,7 +148,10 @@ public void resume() {
     }
 
     SimpleTrigger createTrigger(String invokerClass, CronParser parser, Scheduled scheduled) {
-        String id = triggerNameSequence.getAndIncrement() + "_" + invokerClass;
+        String id = scheduled.identity().trim();
+        if (id.isEmpty()) {
+            id = triggerNameSequence.getAndIncrement() + "_" + invokerClass;
```
Comment (mkouba) [inline extensions/scheduler/runtime/src/main/java/io/quarkus/scheduler/runtime/SimpleScheduler.java:153]: We could probably get rid of `SimpleScheduler.triggerNameSequence` and `SimpleScheduler.config` fields as they are only used in the constructor, in `createTrigger()`...

File: extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java [hunk 4]
```diff
@@ -92,11 +89,15 @@ public QuartzScheduler(SchedulerContext context, QuartzSupport quartzSupport, Co
                 for (ScheduledMethodMetadata method : context.getScheduledMethods()) {
 
                     invokers.put(method.getInvokerClassName(), context.createInvoker(method.getInvokerClassName()));
+                    AtomicInteger triggerNameSequence = new AtomicInteger();
```
Comment (mkouba) [inline extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java:92]: Hm, we don't need `AtomicInteger` here, right? We could use `int` and `triggerNameSequence++`...

**Review by mkouba — COMMENTED** [review]
+1 for promoting the PR.

I've added two small improvement proposals ;-).

Thanks!

File: extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java [hunk 5]
```diff
@@ -92,11 +88,15 @@ public QuartzScheduler(SchedulerContext context, QuartzSupport quartzSupport, Co
                 for (ScheduledMethodMetadata method : context.getScheduledMethods()) {
 
                     invokers.put(method.getInvokerClassName(), context.createInvoker(method.getInvokerClassName()));
+                    int nameSequence = 0;
 
                     for (Scheduled scheduled : method.getSchedules()) {
-                        String name = triggerNameSequence.getAndIncrement() + "_" + method.getInvokerClassName();
+                        String identity = scheduled.identity().trim();
+                        if (identity.isEmpty()) {
+                            identity = ++nameSequence + "_" + method.getInvokerClassName();
```
Comment (gsmet) [inline extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java:96]: I'm not sure I see how this solves the issue?

**Review by gsmet — DISMISSED** [review]
Could you explain why it solves the issue?

I want to be sure I understand what's going on before merging this.

Thanks!

File: extensions/scheduler/deployment/src/main/java/io/quarkus/scheduler/deployment/SchedulerProcessor.java (hunk 1 above)
Comment (Ladicek) [reply extensions/scheduler/deployment/src/main/java/io/quarkus/scheduler/deployment/SchedulerProcessor.java]: Off topic: should we have a documentation-only annotation, called e.g. `@Ordering`, that would be added to such places to let people know what's the purpose of the dependency?

File: extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java (hunk 5 above)
Comment (machi1990) [reply extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java:96]: Because of the way beans are registered (in an unordered data structure), the list of scheduled methods (invoked methods) did not guarantee that the order is respected in between builds. So instead of having a global sequence strategy for the whole list - whose order can change in between builds, we just maintain a separate sequence for each method which does not change unless otherwise multiple `@Scheduled` annotations are re-arranged (source code change) for a given scheduled method which won't be a problem because of - https://github.com/quarkusio/quarkus/blob/master/extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java#L150-L152.

Comment (gsmet) [reply extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java:96]: OK. An important thing is: https://stackoverflow.com/questions/26086538/order-of-automatically-wrapped-repeatable-annotations .

**Comment by gsmet** [comment]
@mkouba I dismissed my review as @machi1990 answered. I let you drive this one home? We need it for 1.4 IMHO.

File: extensions/scheduler/deployment/src/main/java/io/quarkus/scheduler/deployment/SchedulerProcessor.java (hunk 1 above)
Comment (machi1990) [reply extensions/scheduler/deployment/src/main/java/io/quarkus/scheduler/deployment/SchedulerProcessor.java]: Sounds like a very good idea.

**Comment by brunobat** [comment]
Any chance of backporting this to 1.2.* as well? We are still fighting with classloading issues and could not upgrade yet.

**Comment by gsmet** [comment]
@brunobat no, we won't backport to 1.2 but you can do it.

I would say it's high time for you to report your class loader issues so that we can help you solving them and you can upgrade to the latest version :).

**Review by mkouba — APPROVED** [review]

**Comment by mkouba** [comment]
@machi1990 Merged. Thanks for the contribution!
