### PR TITLE
Ensure to check the runtime log level for RequestContext tracing needs

### LINKED ISSUE #27735: Performance regression in RequestContext activations
### Describe the bug

There is a performance regression caused by #27249 : the logging statements are allocating various `java.util.stream.SliceOps$1` and `byte[]` + `StringBuilder` to encode numbers as hex, capturing and  formatting the stacktraces.

These logging statements are protected by a check for TRACE being enabled, but it would seem the value of this is true at the point it's captured (during Arc recorder) even when not configured.

### Expected behavior

No significant overhead should be introduced.

### LINKED ISSUE #27743: Throughput of Resteasy Reactive's significantly decreased in 2.12.0.Final
### Describe the bug

when i use 2.11.3.Final, the endpoint's throughput would be 410k rps

```
wrk -t10 -c500 -d60s http://localhost:8080/bench
Running 1m test @ http://localhost:8080/bench
  10 threads and 500 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.90ms    4.52ms  94.42ms   87.86%
    Req/Sec    41.19k     5.32k   93.90k    72.64%
  24591994 requests in 1.00m, 1.86GB read
Requests/sec: 409195.71
Transfer/sec:     31.61MB
```

when upgrade to 2.12.0.Final, throughput would decrease to 46k rps

```
wrk -t10 -c500 -d60s http://localhost:8080/bench
Running 1m test @ http://localhost:8080/bench
  10 threads and 500 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    11.41ms    6.35ms  88.30ms   71.20%
    Req/Sec     4.55k   349.58     7.88k    71.64%
  2714402 requests in 1.00m, 209.68MB read
Requests/sec:  45169.21
Transfer/sec:      3.49MB

```

#### dependencies
```
    implementation("io.quarkus:quarkus-resteasy-reactive-jackson")
    implementation("io.quarkus:quarkus-kotlin")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    implementation("io.quarkus:quarkus-arc")
    implementation("io.quarkus:quarkus-resteasy-reactive")
```

#### test endpoint 
`fun uni(): Uni<String> = Uni.createFrom().item("uni")`

#### cpu 
intel 10400 6c12t

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

Linux yazi-m820 5.15.57-2-MANJARO #1 SMP PREEMPT Mon Jul 25 01:32:51 UTC 2022 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.2" 2022-01-18 LTS

### GraalVM version (if different from Java)

OpenJDK Runtime Environment GraalVM 22.0.0.2 (build 17.0.2+9-LTS)

### Quarkus version or git rev

[2.12.0.Final]

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle-7.4.2

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Sanne**
Fixes #27735 
Fixes #27743

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]

**Review by manovotn — APPROVED** [review]

File: independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl/RequestContext.java [hunk 1]
```diff
@@ -126,7 +122,7 @@ public void destroy(Contextual<?> contextual) {
 
     @Override
     public void activate(ContextState initialState) {
-        if (traceEnabled) {
+        if (LOG.isTraceEnabled()) {
             String stack = Arrays.stream(Thread.currentThread().getStackTrace())
```
Comment (franz1981) [inline independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl/RequestContext.java:126]: Unrelated but useful: always move away "unlikely" paths ie cold ones out of the "main" method logic: it would improve the change to inline it (see http://normanmaurer.me/blog_in_progress/2013/11/07/Inline-all-the-Things/ that's still very actual and these things hasn't changed across JDK versions, really)

**Review by franz1981 — APPROVED** [review]
I've verified in our perf lab that's going to fix the performance regression seen on current master.

**Comment by geoand** [comment]
Thanks for the fix @Sanne!

This also fixed https://github.com/quarkusio/quarkus/issues/27743, which initially had me really worried 😌 .

**Comment by geoand** [comment]
It goes without saying that this should be most important thing we backport to `2.12` :)

File: independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl/RequestContext.java (hunk 1 above)
Comment (Sanne) [reply independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl/RequestContext.java:126]: Very true, but in this case I preferred the simplest patch to expedite integration & minimize friction for backports.

Definitely something to consider if someone wants to get back to this and improve further.

Comment (franz1981) [reply independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl/RequestContext.java:126]: Agree!
