### PR TITLE
Replacing quarkus.properties with quarkus.platform.version

### LINKED ISSUE #4744: Generated maven project should have a property for quarkus platform and version
**Describe the bug**
when mvn project generated and quarkus version != platform version we fall back to hardcoded values.
Should use property replacements instead., i.e. ${quarkus.platform.version} and ${quarkus.platform.id} 

**To Reproduce**
use latest master/0.26 with universe platform with a version number updated to be 998-SNAPSHOT in all its pom.xml files and run:

`mvn io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:create -DprojectGroupId=org.acme -DprojectArtifactId=application-configuratxio557 -DclassName="org.acme.config.GreetingResource" -Dpath="/greeting" -DplatformArtifactId=quarkus-universe-bom -DplatformVersion=998-SNAPSHOT`

### PR DESCRIPTION
**Pull request by aloubyansky**
...and quarkus-plugin.version in Maven templates and quarkusVersion with quarkusPluginVersion in the Gradle ones, also adding quarkus.platform.group-is and quarkus.platform.artifact-id to pom.xml templates and sorting of properties before persisting pom.xml.

Fixes #4744

### CODE REVIEW

File: independent-projects/tools/common/src/test/java/io/quarkus/cli/commands/ListExtensionsTest.java [hunk 1]
```diff
@@ -36,7 +36,7 @@ public void listWithBom() throws IOException {
 
         FileProjectWriter writer = new FileProjectWriter(pom.getParentFile());
         new CreateProject(writer)
-                .groupId(getPluginGroupId())
+                .groupId("org.acme")
```
Comment (maxandersen) [inline independent-projects/tools/common/src/test/java/io/quarkus/cli/commands/ListExtensionsTest.java]: why are all these "org.acme" reference replaced? shouldn't they stay the same for this test ?

File: core/deployment/src/main/java/io/quarkus/deployment/configuration/ConfigDefinition.java [hunk 2]
```diff
@@ -71,6 +71,10 @@
             .asList(QUARKUS_NAMESPACE + ".live-reload.password", QUARKUS_NAMESPACE + ".live-reload.url",
                     QUARKUS_NAMESPACE + ".debug.generated-classes-dir", QUARKUS_NAMESPACE + ".debug.reflection",
                     QUARKUS_NAMESPACE + ".build.skip",
+                    QUARKUS_NAMESPACE + ".platform.group-id",
+                    QUARKUS_NAMESPACE + ".platform.artifact-id",
+                    QUARKUS_NAMESPACE + ".platform.version",
+                    QUARKUS_NAMESPACE + "-plugin.version",
```
Comment (maxandersen) [inline core/deployment/src/main/java/io/quarkus/deployment/configuration/ConfigDefinition.java]: hmm - when seeing it here and in the lower pom.xml's then the `quarkus-plugin` does feel out of place as one would expect `quarkus.plugin`. 

should we make it `quarkus.plugin.version` just to not trigger other peoples OCD ? :)

Comment (maxandersen) [reply core/deployment/src/main/java/io/quarkus/deployment/configuration/ConfigDefinition.java]: okey - just did a quick search on github and "-plugin.version" seems waay more prominent (millions vs thousands) than ".plugin.version" so lets just keep it as is.

**Review by maxandersen — CHANGES_REQUESTED** [review]
i tested it with and without `-o` and for mvn/gradle and it works.

Just want to know if those org.acme changes in the test was really intended.

File: core/deployment/src/main/java/io/quarkus/deployment/configuration/ConfigDefinition.java (hunk 2 above)
Comment (dmlloyd) [inline core/deployment/src/main/java/io/quarkus/deployment/configuration/ConfigDefinition.java]: I'm pretty sure that this entry isn't needed.  The config subsystem should only warn on properties whose name starts with `quarkus.`

File: independent-projects/tools/common/src/test/java/io/quarkus/cli/commands/ListExtensionsTest.java (hunk 1 above)
Comment (aloubyansky) [reply independent-projects/tools/common/src/test/java/io/quarkus/cli/commands/ListExtensionsTest.java]: Because the groupId of quarkus-maven-plugin is not related to the groupId of a random test project. Or am I missing something?

File: core/deployment/src/main/java/io/quarkus/deployment/configuration/ConfigDefinition.java (hunk 2 above)
Comment (aloubyansky) [reply core/deployment/src/main/java/io/quarkus/deployment/configuration/ConfigDefinition.java]: Ok, removing it from here. Thanks.

File: independent-projects/tools/common/src/test/java/io/quarkus/cli/commands/ListExtensionsTest.java (hunk 1 above)
Comment (maxandersen) [reply independent-projects/tools/common/src/test/java/io/quarkus/cli/commands/ListExtensionsTest.java]: ooooh - I misread the diff. you are right. your fix is correct.

**Review by maxandersen — APPROVED** [review]
