### PR TITLE
Apply user filter when storing OpenAPI document

### LINKED ISSUE #15097: OASFilter set by mp.openapi.filter not processing file created with store-schema-directory
**Describe the bug**
When a filter is configured with the configuration property mp.openapi.filter it is correctly picked up an processes the openapi file created from the openapi endpoint of the running application.   When the quarkus.smallrye-openapi.store-schema-directory property is set, the file is created without being processed with the configured custom OASFilter.   

This seems to be a regression side effect to the fix for "OASFilter is called twice #13683. "   Processing was moved to runtime in Apply OASFilter at runtime to modify security schemes in openapi #13714  that caused the endpoint to process the filter twice.   The fix removed the line doing the compile-time processing but the runtime processing is not being hit when the stored file is being generated so after this change the stored file is not processed properly.    

**Expected behavior**
Expect the stored schema file to have all the same processing and be exactly the same as the file from the openapi endpoint at runtime

**Actual behavior**
Custom filter is not run on file stored in configured directory making the output different.

Error was introduced in https://github.com/quarkusio/quarkus/pull/13715/commits/7d4eb83945ee8429858bf523a322e4b5f62aa2e7  and was caused by the removal of line 468 in SmallRyeOpenApiProcessor.java     document.filter(filter(openApiConfig));

### PR DESCRIPTION
**Pull request by phillip-kruger**
Fix #15097

Signed-off-by:Phillip Kruger <phillip.kruger@gmail.com>

### CODE REVIEW

File: extensions/smallrye-openapi/deployment/src/main/java/io/quarkus/smallrye/openapi/deployment/SmallRyeOpenApiProcessor.java [hunk 1]
```diff
@@ -492,6 +494,36 @@ private Result findStaticModel(ApplicationArchivesBuildItem archivesBuildItem) {
...
+
+        for (Format format : Format.values()) {
+            String name = OpenApiConstants.BASE_NAME + format;
+            byte[] schemaDocument = OpenApiSerializer.serialize(document.get(), format).getBytes(StandardCharsets.UTF_8);
+            storeGeneratedSchema(smallRyeOpenApiConfig, out, schemaDocument, format);
+        }
+
+    }
+
+    private OpenApiDocument prepateOpenApiDocument(OpenAPI staticModel,
```
Comment (gsmet) [inline extensions/smallrye-openapi/deployment/src/main/java/io/quarkus/smallrye/openapi/deployment/SmallRyeOpenApiProcessor.java:524]:
```suggestion
    private OpenApiDocument prepareOpenApiDocument(OpenAPI staticModel,
```

**Review by gsmet — CHANGES_REQUESTED** [review]

**Comment by phillip-kruger** [comment]
Thanks @gsmet - typo fixed

**Review by gsmet — APPROVED** [review]
