### PR TITLE
Fix StoredProcedure call with cursor in native mode

### LINKED ISSUE #17295: Oracle StoredProcedure call with cursor in native mode raises a NullPointerException
Calling an Oracle StoredProcedure with cursor as out parameter raises a NullPointerException in native mode:
```
Caused by: java.lang.NullPointerException
       at org.hibernate.engine.jdbc.cursor.internal.StandardRefCursorSupport.registerRefCursorParameter(StandardRefCursorSupport.java:67)
       at org.hibernate.query.procedure.internal.ProcedureParameterImpl.prepare(ProcedureParameterImpl.java:283)
       at org.hibernate.procedure.internal.ProcedureCallImpl$3.accept(ProcedureCallImpl.java:397)
```
The reproducer (a maven project) is available at https://github.com/draccagni/quarkus-hibernate-orm-oracle.git . All the instructions are explained in the ```README.md``` file

### PR DESCRIPTION
**Pull request by yrodiere**
Fixes #17295

### CODE REVIEW

File: extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmProcessor.java [hunk 1]
```diff
@@ -664,6 +664,20 @@ public void registerStaticMetamodelClassesForReflection(CombinedIndexBuildItem i
         }
     }
 
+    /*
+     * Enable reflection for methods annotated with @InjectService,
+     * such as org.hibernate.engine.jdbc.cursor.internal.StandardRefCursorSupport.injectJdbcServices.
+     * We only deal with built-in service classes here;
+     * integrators relying on @InjectService must declare reflection on their own classes.
```
Comment (gsmet) [inline extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmProcessor.java:671]: Is there a reason why you don't scan the index for additional ones? Wouldn't cost much.

Comment (yrodiere) [reply extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmProcessor.java:671]: It seems Hibernate ORM is not indexed by Jandex for some reason...

Comment (yrodiere) [reply extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmProcessor.java:671]: Ah, you mean for the integrators. Sure I can do it. I don't particularly want to test this, though :)

Comment (yrodiere) [reply extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmProcessor.java]: Done

Comment (gsmet) [reply extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmProcessor.java]: Yes, I mean for the integrators. And sure, no need to test it. I would add everything to a `Set` to be sure we don't have duplicates in case someone indexes ORM for some reason.

Comment (yrodiere) [reply extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmProcessor.java]: > I would add everything to a Set to be sure we don't have duplicates in case someone indexes ORM for some reason.

Done

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Not backporting this one as we would need a whole other patch as a lot of things were changed. Not sure it's worth it?

**Comment by yrodiere** [comment]
@gsmet There is a workaround (it's mentioned on the issue), so if it's too much work I think we can skip backporting.
