### PR TITLE
Fixed non-working delay for oidc-client

### LINKED ISSUE #14959: OIDC Client does not use connection-delay property
**Describe the bug**
When using the OID Client and starting the app without running Keycloak it crashes instantly and does not respect the connection-delay property as the normal OIDC stuff does.

**Expected behavior**
OIDC Client should wait and retry the connection for the configured connection-delay

**Actual behavior**
App tries to start and crashes instantly:
```
Attaching to ingest
ingest           | exec java -Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -XX:+ExitOnOutOfMemoryError -cp . -jar /deployments/app.jar
ingest           | Feb 10, 2021 8:46:01 AM org.jboss.threads
ingest           | INFO: JBoss Threads version %s
ingest           | Feb 10, 2021 8:46:02 AM io.quarkus.oidc.client.runtime.OidcClientRecorder
ingest           | INFO: Connecting to IDP for up to %d times every 2 seconds
ingest           | Feb 10, 2021 8:46:03 AM io.quarkus.runtime.ApplicationLifecycleManager run
ingest           | ERROR: Failed to start application (with profile prod)
ingest           | java.net.ConnectException: Connection refused
ingest           | 	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
ingest           | 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:779)
ingest           | 	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
ingest           | 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
ingest           | 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
ingest           | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
ingest           | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
ingest           | 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
ingest           | 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
ingest           | 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
ingest           | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
ingest           | 	at java.base/java.lang.Thread.run(Thread.java:834)
ingest           | 
ingest exited with code 1
```
Startup when Keycloak is already running:
```
Attaching to ingest
ingest           | exec java -Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -XX:+ExitOnOutOfMemoryError -cp . -jar /deployments/app.jar
ingest           | __  ____  __  _____   ___  __ ____  ______ 
ingest           |  --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
ingest           |  -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
ingest           | --\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
ingest           | 2021-02-10 08:44:58,953 INFO  [io.qua.oid.cli.run.OidcClientRecorder] (main) Connecting to IDP for up to 60 times every 2 seconds
ingest           | 2021-02-10 08:44:59,772 INFO  [io.qua.oid.run.OidcRecorder] (main) Connecting to IDP for up to 60 times every 2 seconds
ingest           | 2021-02-10 08:45:00,558 INFO  [com.im.flo.ing.bou.BuildInfoService] (main) ingest V1.0-SNAPSHOT (build at 2021-02-10T09:30:32+0100, commit: 6424ac65bc03a8ae633148bd051ce44825562dc9/6424ac65bc03a8ae633148bd051ce44825562dc9 at 2021-02-10T09:22:52+0100)
ingest           | 2021-02-10 08:45:00,625 INFO  [io.quarkus] (main) ingest 1.0-SNAPSHOT on JVM (powered by Quarkus 1.11.2.Final) started in 3.857s. Listening on: http://0.0.0.0:8091
ingest           | 2021-02-10 08:45:00,626 INFO  [io.quarkus] (main) Profile prod activated. 
ingest           | 2021-02-10 08:45:00,626 INFO  [io.quarkus] (main) Installed features: [cdi, oidc, oidc-client, oidc-client-filter, rest-client, resteasy, resteasy-jsonb, security, smallrye-context-propagation, smallrye-fault-tolerance, smallrye-health, smallrye-metrics, smallrye-openapi, swagger-ui]
```

**To Reproduce**
1. Create a project using OIDC client. 
2 Add delay properties quarkus.oidc.connection-delay=120S and quarkus.oidc-client.connection-delay=120S
3. Start App without running Keycloak
4. App instantly crashes.

**Configuration**
```properties
quarkus.oidc.auth-server-url=http://keycloak:8080/auth/realms/flows
quarkus.oidc.client-id=ingest
quarkus.oidc.credentials.secret=b398b8ee-dcb9-4a55-a1ae-eed6c4332406
quarkus.oidc.connection-delay=120S
quarkus.oidc-client.auth-server-url=${quarkus.oidc.auth-server-url}
quarkus.oidc-client.client-id=${quarkus.oidc.client-id}
quarkus.oidc-client.credentials.secret=${quarkus.oidc.credentials.secret}
quarkus.oidc-client.connection-delay=${quarkus.oidc.connection-delay}
```
Does not work when I use the 120S and not a placeholder.

**Environment (please complete the following information):** 
 - Output of `java -version`: openjdk version "11.0.2" 2019-01-15
 - Quarkus version or git rev: 1.11.2-FINAL

### PR DESCRIPTION
**Pull request by steel-judoka**
Fixes  #14959

I also removed the wrong log info that stated "Connecting to IDP for up to %d times every 2 seconds" in fact according to the original idea, the code should have worked in such a way that after each unsuccessful request there should be a delay of 2 seconds.

### CODE REVIEW

**Comment by sberyozkin** [comment]
@Yelzhasdev thanks for the PR.
The way you collapsed all that manual iteration code into a backoff function looks neat.

But I'd like you to keep 
`"Connecting to IDP for up to %d times every 2 seconds"` - it has been around for a while (in `quarkus-oidc` which is where this code has been copied from) and no-one has said it has been confusing - `every 2 sec` implies a delay of 2 seconds.
Please also consider applying the same code (once we settle on the final approach) to `quarkus-oidc`, see other comments as well
thanks

File: extensions/oidc-client/runtime/src/main/java/io/quarkus/oidc/client/runtime/OidcClientRecorder.java [hunk 1]
```diff
@@ -157,41 +159,10 @@ private static void setGrantClientParams(OidcClientConfig oidcConfig, MultiMap g
...
-                    throw new OidcClientException(throwable);
-                }
-            }
-        }
-        return Uni.createFrom().nullItem();
-    }
-
-    private static Uni<String> discoverTokenEndpoint(WebClient client, String authServerUrl) {
-        String discoveryUrl = authServerUrl + "/.well-known/openid-configuration";
+        final String discoveryUrl = authServerUrl + "/.well-known/openid-configuration";
```
Comment (sberyozkin) [inline extensions/oidc-client/runtime/src/main/java/io/quarkus/oidc/client/runtime/OidcClientRecorder.java:162]: @Yelzhasdev Can you push this code to `OidcCommonUtils` - it may already have this check there - if not - please remove other connection-delay related code from `OidcCommonUtils`

File: extensions/oidc-client/runtime/src/main/java/io/quarkus/oidc/client/runtime/OidcClientRecorder.java [hunk 2]
```diff
@@ -200,7 +171,10 @@ private static void setGrantClientParams(OidcClientConfig oidcConfig, MultiMap g
                 LOG.tracef("Discovery has failed, status code: %d", resp.statusCode());
                 return null;
             }
-        });
+        }).onFailure()
```
Comment (sberyozkin) [inline extensions/oidc-client/runtime/src/main/java/io/quarkus/oidc/client/runtime/OidcClientRecorder.java:174]: @Yelzhasdev what happens if it is an HTTP-level response error, for example, 401 ? This block must only run if it is a connection error

File: extensions/oidc-client/runtime/src/main/java/io/quarkus/oidc/client/runtime/OidcClientRecorder.java (hunk 1 above)
Comment (Yelzhasdev) [reply extensions/oidc-client/runtime/src/main/java/io/quarkus/oidc/client/runtime/OidcClientRecorder.java:162]: Yep, sure

Comment (Yelzhasdev) [reply extensions/oidc-client/runtime/src/main/java/io/quarkus/oidc/client/runtime/OidcClientRecorder.java:162]: fixed

File: extensions/oidc-client/runtime/src/main/java/io/quarkus/oidc/client/runtime/OidcClientRecorder.java (hunk 2 above)
Comment (Yelzhasdev) [reply extensions/oidc-client/runtime/src/main/java/io/quarkus/oidc/client/runtime/OidcClientRecorder.java]: fixed

**Comment by sberyozkin** [comment]
@Yelzhasdev I just thought while I was offline that we should not touch `quarkus-oidc` for now - I'll take care of optimizing it later once I complete some other major refactoring there, hope you haven't started yet.

File: extensions/oidc-client/runtime/src/main/java/io/quarkus/oidc/client/runtime/OidcClientRecorder.java (hunk 1 above)
Comment (sberyozkin) [reply extensions/oidc-client/runtime/src/main/java/io/quarkus/oidc/client/runtime/OidcClientRecorder.java:162]: @Yelzhasdev, thanks - note there is another function returning it in seconds just above there :-), so can you reuse that one and converts secs to millisecs here ?

File: extensions/oidc-client/runtime/src/main/java/io/quarkus/oidc/client/runtime/OidcClientRecorder.java [hunk 3]
```diff
@@ -157,41 +159,12 @@ private static void setGrantClientParams(OidcClientConfig oidcConfig, MultiMap g
     }
 
     private static Uni<String> discoverTokenRequestUri(WebClient client, String authServerUrl, OidcClientConfig oidcConfig) {
+        final String discoveryUrl = authServerUrl + "/.well-known/openid-configuration";
         final long connectionRetryCount = OidcCommonUtils.getConnectionRetryCount(oidcConfig);
```
Comment (sberyozkin) [inline extensions/oidc-client/runtime/src/main/java/io/quarkus/oidc/client/runtime/OidcClientRecorder.java:163]: @Yelzhasdev `connectionRetryCount` is not used anymore

Comment (sberyozkin) [reply extensions/oidc-client/runtime/src/main/java/io/quarkus/oidc/client/runtime/OidcClientRecorder.java:163]: @Yelzhasdev Ignore it please :-)

File: extensions/oidc-common/runtime/src/main/java/io/quarkus/oidc/common/runtime/OidcCommonUtils.java [hunk 4]
```diff
@@ -93,6 +93,12 @@ private static long getConnectionDelay(OidcCommonConfig oidcConfig) {
                 : 0;
     }
 
+    public static long getConnectionDelayInMillis(OidcCommonConfig oidcConfig) {
```
Comment (sberyozkin) [inline extensions/oidc-common/runtime/src/main/java/io/quarkus/oidc/common/runtime/OidcCommonUtils.java:96]: @Yelzhasdev Or if you prefer to keep this function for millis specifically then still please consider reusing the one above it and only div by 1000 here...

File: extensions/oidc-client/runtime/src/main/java/io/quarkus/oidc/client/runtime/OidcClientRecorder.java (hunk 2 above)
Comment (sberyozkin) [reply extensions/oidc-client/runtime/src/main/java/io/quarkus/oidc/client/runtime/OidcClientRecorder.java]: @Yelzhasdev, nice - can you confirm please this is what vert.x  web client throws in case of the connection failure ? I was referring to `ConnectionException` as a general connection exception... vert.x might wrap it, etc...

File: extensions/oidc-common/runtime/src/main/java/io/quarkus/oidc/common/runtime/OidcCommonUtils.java (hunk 4 above)
Comment (Yelzhasdev) [reply extensions/oidc-common/runtime/src/main/java/io/quarkus/oidc/common/runtime/OidcCommonUtils.java:96]: Sorry, my bad, now I just reuse getConnectionDelay and multiply it by 1000 to get a millis

File: extensions/oidc-client/runtime/src/main/java/io/quarkus/oidc/client/runtime/OidcClientRecorder.java (hunk 2 above)
Comment (Yelzhasdev) [reply extensions/oidc-client/runtime/src/main/java/io/quarkus/oidc/client/runtime/OidcClientRecorder.java]: Yes, for example for connection timeout there is an exception io.netty.channel.ConnectTimeoutException, which is a child of java.net.ConnectException

**Comment by Yelzhasdev** [comment]
> @Yelzhasdev I just thought while I was offline that we should not touch `quarkus-oidc` for now - I'll take care of optimizing it later once I complete some other major refactoring there, hope you haven't started yet.

@sberyozkin I didn't quite understand you, I was not going to touch quarkus-oidc, only quarkus-oidc-client in this pr

File: extensions/oidc-common/runtime/src/main/java/io/quarkus/oidc/common/runtime/OidcCommonUtils.java (hunk 4 above)
Comment (sberyozkin) [reply extensions/oidc-common/runtime/src/main/java/io/quarkus/oidc/common/runtime/OidcCommonUtils.java:96]: Good idea about multiply, glad you did not decide to go with mine about div :-)

**Comment by sberyozkin** [comment]
@Yelzhasdev I just thought, in my very first comment, that it makes sense to apply the same code to `quarkus-oidc`, but all is good, I'll take care of it separately

**Comment by sberyozkin** [comment]
@Yelzhasdev Last step remains, please squash your commits, thanks

**Comment by Yelzhasdev** [comment]
@sberyozkin Thanks! All done.

**Review by sberyozkin — APPROVED** [review]
