### PR TITLE
Properly handle char and Character parameter types in JAX-RS methods

### LINKED ISSUE #24541: RESTEasy Reactive: issues with `char` parameter
### Describe the bug

When I have an endpoint with a `char` parameter, native-image doesn't work:

```
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: java.lang.Character.valueOf(java.lang.String). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
Trace: 
	at parsing io.quarkus.generated.char$quarkusrestparamConverter$.convert(Unknown Source)
Call path from entry point to io.quarkus.generated.char$quarkusrestparamConverter$.convert(Object): 
	at io.quarkus.generated.char$quarkusrestparamConverter$.convert(Unknown Source)
	at org.jboss.resteasy.reactive.server.core.parameters.converters.RuntimeResolvedConverter.convert(RuntimeResolvedConverter.java:23)
	at org.jboss.resteasy.reactive.server.handlers.ParameterHandler.handleResult(ParameterHandler.java:92)
	at org.jboss.resteasy.reactive.server.handlers.ParameterHandler.handle(ParameterHandler.java:55)
	at org.jboss.resteasy.reactive.server.handlers.ParameterHandler.handle(ParameterHandler.java:15)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:141)
	at java.lang.Thread.run(Thread.java:829)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:597)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:194)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
```

This is due to https://github.com/quarkusio/quarkus/blob/main/independent-projects/resteasy-reactive/server/processor/src/main/java/org/jboss/resteasy/reactive/server/processor/generation/converters/GeneratedConverterIndexerExtension.java because `Character.valueOf(String)` doesn't exist.

If you don't compile natively, endpoints with a `char` parameter return a 404 because some converter is needed:

```java
package io.quarkiverse.renarde.util;

import java.lang.annotation.Annotation;
import java.lang.reflect.Type;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.ws.rs.ext.ParamConverter;
import javax.ws.rs.ext.ParamConverterProvider;
import javax.ws.rs.ext.Provider;

@Provider
public class MyParamConverters implements ParamConverterProvider {

    public static class CharacterParamConverter implements ParamConverter<Character> {

        @Override
        public Character fromString(String value) {
            if (StringUtils.isEmpty(value))
                return null;
            if (value.length() != 1)
                throw new RuntimeException("Invalid character: " + value);
            return value.charAt(0);
        }

        @Override
        public String toString(Character value) {
            if (value == null)
                return null;
            return value.toString();
        }
    }

    @Override
    public <T> ParamConverter<T> getConverter(Class<T> rawType, Type genericType, Annotation[] annotations) {
        if (rawType == Character.class || rawType == char.class)
            return (ParamConverter<T>) new CharacterParamConverter();
        return null;
    }

}

```

I don't think this converter should be required, so it's probably a bug.

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #24541

### CODE REVIEW

File: independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/parameters/converters/CharacterParamConverter.java [hunk 1]
```diff
@@ -0,0 +1,26 @@
+package org.jboss.resteasy.reactive.server.core.parameters.converters;
+
+public class CharacterParamConverter implements ParameterConverter {
+
+    @Override
+    public Object convert(Object parameter) {
+        String str = parameter.toString();
```
Comment (FroMage) [inline independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/parameters/converters/CharacterParamConverter.java:7]: This should allow `null` values, no?

File: independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/parameters/converters/CharParamConverter.java [hunk 2]
```diff
@@ -0,0 +1,26 @@
+package org.jboss.resteasy.reactive.server.core.parameters.converters;
+
+public class CharParamConverter implements ParameterConverter {
+
+    @Override
+    public Object convert(Object parameter) {
+        String str = parameter.toString();
```
Comment (FroMage) [inline independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/parameters/converters/CharParamConverter.java:7]: For `char` it's not clear what a null value is, though I guess the same null value as for `int`? If missing `int` params produce a `0` value, then, probably so should `int` params, no?

File: independent-projects/resteasy-reactive/server/vertx/src/test/java/org/jboss/resteasy/reactive/server/vertx/test/simple/SimpleQuarkusRestResource.java [hunk 3]
```diff
@@ -75,8 +75,10 @@ public String get(@PathParam("id") String id) {
     public String params(@PathParam("p") String p,
             @QueryParam("q") String q,
             @HeaderParam("h") int h,
+            @HeaderParam("h2") char h2,
+            @HeaderParam("h3") Character h3,
             @FormParam("f") String f) {
```
Comment (FroMage) [inline independent-projects/resteasy-reactive/server/vertx/src/test/java/org/jboss/resteasy/reactive/server/vertx/test/simple/SimpleQuarkusRestResource.java:80]: I know the other primitive types work, because I have tests for them, but I'm surprised that we don't here.

**Review by FroMage — CHANGES_REQUESTED** [review]

File: independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/parameters/converters/CharacterParamConverter.java (hunk 1 above)
Comment (geoand) [reply independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/parameters/converters/CharacterParamConverter.java:7]: `null` doesn't reach this point AFAIK

Comment (geoand) [reply independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/parameters/converters/CharacterParamConverter.java:7]: Just checked, the other converters don't check for null either.

File: independent-projects/resteasy-reactive/server/vertx/src/test/java/org/jboss/resteasy/reactive/server/vertx/test/simple/SimpleQuarkusRestResource.java (hunk 3 above)
Comment (geoand) [reply independent-projects/resteasy-reactive/server/vertx/src/test/java/org/jboss/resteasy/reactive/server/vertx/test/simple/SimpleQuarkusRestResource.java:80]: ?

File: independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/parameters/converters/CharParamConverter.java (hunk 2 above)
Comment (geoand) [reply independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/parameters/converters/CharParamConverter.java:7]: The value is never `null` so this does not apply

File: independent-projects/resteasy-reactive/server/vertx/src/test/java/org/jboss/resteasy/reactive/server/vertx/test/simple/SimpleQuarkusRestResource.java (hunk 3 above)
Comment (FroMage) [reply independent-projects/resteasy-reactive/server/vertx/src/test/java/org/jboss/resteasy/reactive/server/vertx/test/simple/SimpleQuarkusRestResource.java:80]: I mean `boolean`, `byte`, `short`, `long`, `float`, `double` and all that junk.

Comment (geoand) [reply independent-projects/resteasy-reactive/server/vertx/src/test/java/org/jboss/resteasy/reactive/server/vertx/test/simple/SimpleQuarkusRestResource.java:80]: We could add them, but there is not much point I would say due the existence of `valueOf`

File: independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/parameters/converters/CharParamConverter.java (hunk 2 above)
Comment (FroMage) [reply independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/parameters/converters/CharParamConverter.java:7]: Oh, so it's the injector which produces `0` for missing `char` params? OK, fine.

**Review by FroMage — APPROVED** [review]

**Comment by FroMage** [comment]
@gsmet This would be great to backport, it's preventing me from releasing the Renarde extension because I test for this, and it doesn't compile natively without this.

**Comment by geoand** [comment]
The label is present, so it will be backported 😉

**Comment by geoand** [comment]
Curious though, what Renarde feature needs a char?

**Comment by FroMage** [comment]
> Curious though, what Renarde feature needs a char?

It doesn't, but it's an existing test, so CI can't pass without this, or I need to disable the test.
