### PR TITLE
Ensure that the name generated in opentelemetry matches the endpoint being called

### LINKED ISSUE #44524: Traces are generated with an inconsistent operationName value when combining multiple unis
### Describe the bug

When combining multiple unis, the operationName field retains the last uni processed instead of retaining the value it was initialized with. As a result, the generated spans are not consistent.

I found that the same context instance is being shared and modified by different instances of ClientObservabilityHandler

- https://github.com/quarkusio/quarkus/blob/main/independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/impl/ClientRequestContextImpl.java#L71
- https://github.com/quarkusio/quarkus/blob/main/independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/handlers/ClientObservabilityHandler.java#L21

Also, different instances of WebTargetImpl are sharing the same HandlerChain instance. This should not happen because the setPreClientSendHandler method is called multiple times with different instances of ClientObservabilityHandler.

- https://github.com/quarkusio/quarkus/blob/main/independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/impl/HandlerChain.java#L50
- https://github.com/quarkusio/quarkus/blob/main/extensions/resteasy-reactive/rest-client-jaxrs/deployment/src/main/java/io/quarkus/jaxrs/client/reactive/deployment/JaxrsClientReactiveProcessor.java#L961

### Expected behavior

<details><summary>Trace Data</summary>
<p>

```
{
  "data": [
    {
      "traceID": "4d7d7d25e47e2e8ee4ed9056c3892539",
      "spans": [
        {
          "traceID": "4d7d7d25e47e2e8ee4ed9056c3892539",
          "spanID": "e3ecee88cc741899",
          "operationName": "GET /wizard-server/start",
          "references": [
            {
              "refType": "CHILD_OF",
              "traceID": "4d7d7d25e47e2e8ee4ed9056c3892539",
              "spanID": "04d3bf6a57dca42f"
            }
          ],
          "startTime": 1731645575679604,
          "duration": 2024898,
          "tags": [
            {
              "key": "url.scheme",
              "type": "string",
              "value": "http"
            },
            {
              "key": "http.response.body.size",
              "type": "int64",
              "value": 10
            },
            {
              "key": "http.route",
              "type": "string",
              "value": "/wizard-server/start"
            },
            {
              "key": "http.response.status_code",
              "type": "int64",
              "value": 200
            },
            {
              "key": "http.request.method",
              "type": "string",
              "value": "GET"
            },
            {
              "key": "code.function",
              "type": "string",
              "value": "start"
            },
            {
              "key": "url.path",
              "type": "string",
              "value": "/wizard-server/start"
            },
            {
              "key": "code.namespace",
              "type": "string",
              "value": "org.acme.server.WizardServerResource"
            },
            {
              "key": "server.address",
              "type": "string",
              "value": "localhost"
            },
            {
              "key": "server.port",
              "type": "int64",
              "value": 8080
            },
            {
              "key": "client.address",
              "type": "string",
              "value": "127.0.0.1"
            },
            {
              "key": "user_agent.original",
              "type": "string",
              "value": "Quarkus REST Client"
            },
            {
              "key": "span.kind",
              "type": "string",
              "value": "server"
            },
            {
              "key": "internal.span.format",
              "type": "string",
              "value": "otlp"
            }
          ],
          "logs": [],
          "processID": "p1",
          "warnings": null
        },
        {
          "traceID": "4d7d7d25e47e2e8ee4ed9056c3892539",
          "spanID": "f75295bb442800ac",
          "operationName": "GET /wizard-server/step_3",
          "references": [
            {
              "refType": "CHILD_OF",
              "traceID": "4d7d7d25e47e2e8ee4ed9056c3892539",
              "spanID": "682f9b7414832f43"
            }
          ],
          "startTime": 1731645577720739,
          "duration": 1006705,
          "tags": [
            {
              "key": "url.scheme",
              "type": "string",
              "value": "http"
            },
            {
              "key": "http.response.body.size",
              "type": "int64",
              "value": 11
            },
            {
              "key": "http.route",
              "type": "string",
              "value": "/wizard-server/step_3"
            },
            {
              "key": "http.response.status_code",
              "type": "int64",
              "value": 200
            },
            {
              "key": "http.request.method",
              "type": "string",
              "value": "GET"
            },
            {
              "key": "code.function",
              "type": "string",
              "value": "step3"
            },
            {
              "key": "url.path",
              "type": "string",
              "value": "/wizard-server/step_3"
            },
            {
              "key": "code.namespace",
              "type": "string",
              "value": "org.acme.server.WizardServerResource"
            },
            {
              "key": "server.address",
              "type": "string",
              "value": "localhost"
            },
            {
              "key": "server.port",
              "type": "int64",
              "value": 8080
            },
            {
              "key": "client.address",
              "type": "string",
              "value": "127.0.0.1"
            },
            {
              "key": "user_agent.original",
              "type": "string",
              "value": "Quarkus REST Client"
            },
            {
              "key": "span.kind",
              "type": "string",
              "value": "server"
            },
            {
              "key": "internal.span.format",
              "type": "string",
              "value": "otlp"
            }
          ],
          "logs": [],
          "processID": "p1",
          "warnings": null
        },
        {
          "traceID": "4d7d7d25e47e2e8ee4ed9056c3892539",
          "spanID": "04d3bf6a57dca42f",
          "operationName": "GET /start",
          "references": [
            {
              "refType": "CHILD_OF",
              "traceID": "4d7d7d25e47e2e8ee4ed9056c3892539",
              "spanID": "b074666abd57caee"
            }
          ],
          "startTime": 1731645575677360,
          "duration": 2032231,
          "tags": [
            {
              "key": "url.full",
              "type": "string",
              "value": "http://localhost:8080/wizard-server/start"
            },
            {
              "key": "http.response.status_code",
              "type": "int64",
              "value": 200
            },
            {
              "key": "http.request.method",
              "type": "string",
              "value": "GET"
            },
            {
              "key": "server.address",
              "type": "string",
              "value": "localhost"
            },
            {
              "key": "server.port",
              "type": "int64",
              "value": 8080
            },
            {
              "key": "span.kind",
              "type": "string",
              "value": "client"
            },
            {
              "key": "internal.span.format",
              "type": "string",
              "value": "otlp"
            }
          ],
          "logs": [],
          "processID": "p1",
          "warnings": null
        },
        {
          "traceID": "4d7d7d25e47e2e8ee4ed9056c3892539",
          "spanID": "391193cd534c7407",
          "operationName": "GET /wizard-server/step_1",
          "references": [
            {
              "refType": "CHILD_OF",
              "traceID": "4d7d7d25e47e2e8ee4ed9056c3892539",
              "spanID": "ae90dff874de7198"
            }
          ],
          "startTime": 1731645577718967,
          "duration": 1008079,
          "tags": [
            {
              "key": "url.scheme",
              "type": "string",
              "value": "http"
            },
            {
              "key": "http.response.body.size",
              "type": "int64",
              "value": 11
            },
            {
              "key": "http.route",
              "type": "string",
              "value": "/wizard-server/step_1"
            },
            {
              "key": "http.response.status_code",
              "type": "int64",
              "value": 200
            },
            {
              "key": "http.request.method",
              "type": "string",
              "value": "GET"
            },
            {
              "key": "code.function",
              "type": "string",
              "value": "step1"
            },
            {
              "key": "url.path",
              "type": "string",
              "value": "/wizard-server/step_1"
            },
            {
              "key": "code.namespace",
              "type": "string",
              "value": "org.acme.server.WizardServerResource"
            },
            {
              "key": "server.address",
              "type": "string",
              "value": "localhost"
            },
            {
              "key": "server.port",
              "type": "int64",
              "value": 8080
            },
            {
              "key": "client.address",
              "type": "string",
              "value": "127.0.0.1"
            },
            {
              "key": "user_agent.original",
              "type": "string",
              "value": "Quarkus REST Client"
            },
            {
              "key": "span.kind",
              "type": "string",
              "value": "server"
            },
            {
              "key": "internal.span.format",
              "type": "string",
              "value": "otlp"
            }
          ],
          "logs": [],
          "processID": "p1",
          "warnings": null
        },
        {
          "traceID": "4d7d7d25e47e2e8ee4ed9056c3892539",
          "spanID": "682f9b7414832f43",
          "operationName": "GET /step_3",
          "references": [
            {
              "refType": "CHILD_OF",
              "traceID": "4d7d7d25e47e2e8ee4ed9056c3892539",
              "spanID": "b074666abd57caee"
            }
          ],
          "startTime": 1731645577720240,
          "duration": 1010181,
          "tags": [
            {
              "key": "url.full",
              "type": "string",
              "value": "http://localhost:8080/wizard-server/step_3"
            },
            {
              "key": "http.response.status_code",
              "type": "int64",
              "value": 200
            },
            {
              "key": "http.request.method",
              "type": "string",
              "value": "GET"
            },
            {
              "key": "server.address",
              "type": "string",
              "value": "localhost"
            },
            {
              "key": "server.port",
              "type": "int64",
              "value": 8080
            },
            {
              "key": "span.kind",
              "type": "string",
              "value": "client"
            },
            {
              "key": "internal.span.format",
              "type": "string",
              "value": "otlp"
            }
          ],
          "logs": [],
          "processID": "p1",
          "warnings": null
        },
        {
          "traceID": "4d7d7d25e47e2e8ee4ed9056c3892539",
          "spanID": "ae90dff874de7198",
          "operationName": "GET /step_1",
          "references": [
            {
              "refType": "CHILD_OF",
              "traceID": "4d7d7d25e47e2e8ee4ed9056c3892539",
              "spanID": "b074666abd57caee"
            }
          ],
          "startTime": 1731645577718383,
          "duration": 1009752,
          "tags": [
            {
              "key": "url.full",
              "type": "string",
              "value": "http://localhost:8080/wizard-server/step_1"
            },
            {
              "key": "http.response.status_code",
              "type": "int64",
              "value": 200
            },
            {
              "key": "http.request.method",
              "type": "string",
              "value": "GET"
            },
            {
              "key": "server.address",
              "type": "string",
              "value": "localhost"
            },
            {
              "key": "server.port",
              "type": "int64",
              "value": 8080
            },
            {
              "key": "span.kind",
              "type": "string",
              "value": "client"
            },
            {
              "key": "internal.span.format",
              "type": "string",
              "value": "otlp"
            }
          ],
          "logs": [],
          "processID": "p1",
          "warnings": null
        },
        {
          "traceID": "4d7d7d25e47e2e8ee4ed9056c3892539",
          "spanID": "49227e2e820e2f95",
          "operationName": "GET /wizard-server/step_2",
          "references": [
            {
              "refType": "CHILD_OF",
              "traceID": "4d7d7d25e47e2e8ee4ed9056c3892539",
              "spanID": "12d37b8c17445089"
            }
          ],
          "startTime": 1731645577720761,
          "duration": 4007636,
          "tags": [
            {
              "key": "url.scheme",
              "type": "string",
              "value": "http"
            },
            {
              "key": "http.response.body.size",
              "type": "int64",
              "value": 11
            },
            {
              "key": "http.route",
              "type": "string",
              "value": "/wizard-server/step_2"
            },
            {
              "key": "http.response.status_code",
              "type": "int64",
              "value": 200
            },
            {
              "key": "http.request.method",
              "type": "string",
              "value": "GET"
            },
            {
              "key": "code.function",
              "type": "string",
              "value": "step2"
            },
            {
              "key": "url.path",
              "type": "string",
              "value": "/wizard-server/step_2"
            },
            {
              "key": "code.namespace",
              "type": "string",
              "value": "org.acme.server.WizardServerResource"
            },
            {
              "key": "server.address",
              "type": "string",
              "value": "localhost"
            },
            {
              "key": "server.port",
              "type": "int64",
              "value": 8080
            },
            {
              "key": "client.address",
              "type": "string",
              "value": "127.0.0.1"
            },
            {
              "key": "user_agent.original",
              "type": "string",
              "value": "Quarkus REST Client"
            },
            {
              "key": "span.kind",
              "type": "string",
              "value": "server"
            },
            {
              "key": "internal.span.format",
              "type": "string",
              "value": "otlp"
            }
          ],
          "logs": [],
          "processID": "p1",
          "warnings": null
        },
        {
          "traceID": "4d7d7d25e47e2e8ee4ed9056c3892539",
          "spanID": "12d37b8c17445089",
          "operationName": "GET /step_2",
          "references": [
            {
              "refType": "CHILD_OF",
              "traceID": "4d7d7d25e47e2e8ee4ed9056c3892539",
              "spanID": "b074666abd57caee"
            }
          ],
          "startTime": 1731645577719843,
          "duration": 4010205,
          "tags": [
            {
              "key": "url.full",
              "type": "string",
              "value": "http://localhost:8080/wizard-server/step_2"
            },
            {
              "key": "http.response.status_code",
              "type": "int64",
              "value": 200
            },
            {
              "key": "http.request.method",
              "type": "string",
              "value": "GET"
            },
            {
              "key": "server.address",
              "type": "string",
              "value": "localhost"
            },
            {
              "key": "server.port",
              "type": "int64",
              "value": 8080
            },
            {
              "key": "span.kind",
              "type": "string",
              "value": "client"
            },
            {
              "key": "internal.span.format",
              "type": "string",
              "value": "otlp"
            }
          ],
          "logs": [],
          "processID": "p1",
          "warnings": null
        },
        {
          "traceID": "4d7d7d25e47e2e8ee4ed9056c3892539",
          "spanID": "6194ddf9fcc8147f",
          "operationName": "GET /complete",
          "references": [
            {
              "refType": "CHILD_OF",
              "traceID": "4d7d7d25e47e2e8ee4ed9056c3892539",
              "spanID": "b074666abd57caee"
            }
          ],
          "startTime": 1731645581735629,
          "duration": 1011297,
          "tags": [
            {
              "key": "url.full",
              "type": "string",
              "value": "http://localhost:8080/wizard-server/complete"
            },
            {
              "key": "http.response.status_code",
              "type": "int64",
              "value": 200
            },
            {
              "key": "http.request.method",
              "type": "string",
              "value": "GET"
            },
            {
              "key": "server.address",
              "type": "string",
              "value": "localhost"
            },
            {
              "key": "server.port",
              "type": "int64",
              "value": 8080
            },
            {
              "key": "span.kind",
              "type": "string",
              "value": "client"
            },
            {
              "key": "internal.span.format",
              "type": "string",
              "value": "otlp"
            }
          ],
          "logs": [],
          "processID": "p1",
          "warnings": null
        },
        {
          "traceID": "4d7d7d25e47e2e8ee4ed9056c3892539",
          "spanID": "96b1ed0d1fc6f3a6",
          "operationName": "GET /wizard-server/complete",
          "references": [
            {
              "refType": "CHILD_OF",
              "traceID": "4d7d7d25e47e2e8ee4ed9056c3892539",
              "spanID": "6194ddf9fcc8147f"
            }
          ],
          "startTime": 1731645581737274,
          "duration": 1009286,
          "tags": [
            {
              "key": "url.scheme",
              "type": "string",
              "value": "http"
            },
            {
              "key": "http.response.body.size",
              "type": "int64",
              "value": 13
            },
            {
              "key": "http.route",
              "type": "string",
              "value": "/wizard-server/complete"
            },
            {
              "key": "http.response.status_code",
              "type": "int64",
              "value": 200
            },
            {
              "key": "http.request.method",
              "type": "string",
              "value": "GET"
            },
            {
              "key": "code.function",
              "type": "string",
              "value": "complete"
            },
            {
              "key": "url.path",
              "type": "string",
              "value": "/wizard-server/complete"
            },
            {
              "key": "code.namespace",
              "type": "string",
              "value": "org.acme.server.WizardServerResource"
            },
            {
              "key": "server.address",
              "type": "string",
              "value": "localhost"
            },
            {
              "key": "server.port",
              "type": "int64",
              "value": 8080
            },
            {
              "key": "client.address",
              "type": "string",
              "value": "127.0.0.1"
            },
            {
              "key": "user_agent.original",
              "type": "string",
              "value": "Quarkus REST Client"
            },
            {
              "key": "span.kind",
              "type": "string",
              "value": "server"
            },
            {
              "key": "internal.span.format",
              "type": "string",
              "value": "otlp"
            }
          ],
          "logs": [],
          "processID": "p1",
          "warnings": null
        },
        {
          "traceID": "4d7d7d25e47e2e8ee4ed9056c3892539",
          "spanID": "b074666abd57caee",
          "operationName": "GET /wizard-client/work",
          "references": [],
          "startTime": 1731645575621021,
          "duration": 7126393,
          "tags": [
            {
              "key": "url.scheme",
              "type": "string",
              "value": "http"
            },
            {
              "key": "http.response.status_code",
              "type": "int64",
              "value": 200
            },
            {
              "key": "code.function",
              "type": "string",
              "value": "work"
            },
            {
              "key": "server.port",
              "type": "int64",
              "value": 8080
            },
            {
              "key": "user_agent.original",
              "type": "string",
              "value": "IntelliJ HTTP Client/IntelliJ IDEA 2024.2.3"
            },
            {
              "key": "http.request.body.size",
              "type": "int64",
              "value": 0
            },
            {
              "key": "http.response.body.size",
              "type": "int64",
              "value": 10
            },
            {
              "key": "http.route",
              "type": "string",
              "value": "/wizard-client/work"
            },
            {
              "key": "http.request.method",
              "type": "string",
              "value": "GET"
            },
            {
              "key": "url.path",
              "type": "string",
              "value": "/wizard-client/work"
            },
            {
              "key": "code.namespace",
              "type": "string",
              "value": "org.acme.client.WizardClientResource"
            },
            {
              "key": "server.address",
              "type": "string",
              "value": "localhost"
            },
            {
              "key": "client.address",
              "type": "string",
              "value": "127.0.0.1"
            },
            {
              "key": "span.kind",
              "type": "string",
              "value": "server"
            },
            {
              "key": "internal.span.format",
              "type": "string",
              "value": "otlp"
            }
          ],
          "logs": [],
          "processID": "p1",
          "warnings": null
        }
      ],
      "processes": {
        "p1": {
          "serviceName": "quarkus-open-telemetry-bug",
          "tags": [
            {
              "key": "host.name",
              "type": "string",
              "value": "....local"
            },
            {
              "key": "otel.library.name",
              "type": "string",
              "value": "io.quarkus.opentelemetry"
            },
            {
              "key": "service.version",
              "type": "string",
              "value": "1.0.0-SNAPSHOT"
            },
            {
              "key": "telemetry.sdk.language",
              "type": "string",
              "value": "java"
            },
            {
              "key": "telemetry.sdk.name",
              "type": "string",
              "value": "opentelemetry"
            },
            {
              "key": "telemetry.sdk.version",
              "type": "string",
              "value": "1.42.1"
            },
            {
              "key": "webengine.name",
              "type": "string",
              "value": "Quarkus"
            },
            {
              "key": "webengine.version",
              "type": "string",
              "value": "999-SNAPSHOT"
            }
          ]
        }
      },
      "warnings": null
    }
  ],
  "total": 0,
  "limit": 0,
  "offset": 0,
  "errors": null
}
``` 

</p>
</details> 

### Actual behavior

<details><summary>Trace Data</summary>
<p>

```
{
  "data": [
    {
      "traceID": "6e10a4f88b501f26142756421dcb40a9",
      "spans": [
        {
          "traceID": "6e10a4f88b501f26142756421dcb40a9",
          "spanID": "cf4b4eba5509e2e8",
          "operationName": "GET /start",
          "references": [
            {
              "refType": "CHILD_OF",
              "traceID": "6e10a4f88b501f26142756421dcb40a9",
              "spanID": "795b9fe4719c53b3"
            }
          ],
          "startTime": 1731644785471718,
          "duration": 2033385,
          "tags": [
            {
              "key": "server.address",
              "type": "string",
              "value": "localhost"
            },
            {
              "key": "http.request.method",
              "type": "string",
              "value": "GET"
            },
            {
              "key": "http.response.status_code",
              "type": "int64",
              "value": 200
            },
            {
              "key": "url.full",
              "type": "string",
              "value": "http://localhost:8080/wizard-server/start"
            },
            {
              "key": "server.port",
              "type": "int64",
              "value": 8080
            },
            {
              "key": "span.kind",
              "type": "string",
              "value": "client"
            },
            {
              "key": "internal.span.format",
              "type": "string",
              "value": "otlp"
            }
          ],
          "logs": [],
          "processID": "p1",
          "warnings": null
        },
        {
          "traceID": "6e10a4f88b501f26142756421dcb40a9",
          "spanID": "2eb0c9b358ffdc06",
          "operationName": "GET /wizard-server/start",
          "references": [
            {
              "refType": "CHILD_OF",
              "traceID": "6e10a4f88b501f26142756421dcb40a9",
              "spanID": "cf4b4eba5509e2e8"
            }
          ],
          "startTime": 1731644785474250,
          "duration": 2025914,
          "tags": [
            {
              "key": "server.address",
              "type": "string",
              "value": "localhost"
            },
            {
              "key": "client.address",
              "type": "string",
              "value": "127.0.0.1"
            },
            {
              "key": "user_agent.original",
              "type": "string",
              "value": "Quarkus REST Client"
            },
            {
              "key": "url.path",
              "type": "string",
              "value": "/wizard-server/start"
            },
            {
              "key": "code.namespace",
              "type": "string",
              "value": "org.acme.server.WizardServerResource"
            },
            {
              "key": "http.request.method",
              "type": "string",
              "value": "GET"
            },
            {
              "key": "code.function",
              "type": "string",
              "value": "start"
            },
            {
              "key": "http.route",
              "type": "string",
              "value": "/wizard-server/start"
            },
            {
              "key": "http.response.body.size",
              "type": "int64",
              "value": 10
            },
            {
              "key": "http.response.status_code",
              "type": "int64",
              "value": 200
            },
            {
              "key": "url.scheme",
              "type": "string",
              "value": "http"
            },
            {
              "key": "server.port",
              "type": "int64",
              "value": 8080
            },
            {
              "key": "span.kind",
              "type": "string",
              "value": "server"
            },
            {
              "key": "internal.span.format",
              "type": "string",
              "value": "otlp"
            }
          ],
          "logs": [],
          "processID": "p1",
          "warnings": null
        },
        {
          "traceID": "6e10a4f88b501f26142756421dcb40a9",
          "spanID": "11ece084954f6977",
          "operationName": "GET /step_3",
          "references": [
            {
              "refType": "CHILD_OF",
              "traceID": "6e10a4f88b501f26142756421dcb40a9",
              "spanID": "795b9fe4719c53b3"
            }
          ],
          "startTime": 1731644787515208,
          "duration": 1007025,
          "tags": [
            {
              "key": "server.address",
              "type": "string",
              "value": "localhost"
            },
            {
              "key": "http.request.method",
              "type": "string",
              "value": "GET"
            },
            {
              "key": "http.response.status_code",
              "type": "int64",
              "value": 200
            },
            {
              "key": "url.full",
              "type": "string",
              "value": "http://localhost:8080/wizard-server/step_1"
            },
            {
              "key": "server.port",
              "type": "int64",
              "value": 8080
            },
            {
              "key": "span.kind",
              "type": "string",
              "value": "client"
            },
            {
              "key": "internal.span.format",
              "type": "string",
              "value": "otlp"
            }
          ],
          "logs": [],
          "processID": "p1",
          "warnings": null
        },
        {
          "traceID": "6e10a4f88b501f26142756421dcb40a9",
          "spanID": "a7389ddf3f36d643",
          "operationName": "GET /wizard-server/step_1",
          "references": [
            {
              "refType": "CHILD_OF",
              "traceID": "6e10a4f88b501f26142756421dcb40a9",
              "spanID": "11ece084954f6977"
            }
          ],
          "startTime": 1731644787515778,
          "duration": 1005606,
          "tags": [
            {
              "key": "server.address",
              "type": "string",
              "value": "localhost"
            },
            {
              "key": "client.address",
              "type": "string",
              "value": "127.0.0.1"
            },
            {
              "key": "user_agent.original",
              "type": "string",
              "value": "Quarkus REST Client"
            },
            {
              "key": "url.path",
              "type": "string",
              "value": "/wizard-server/step_1"
            },
            {
              "key": "code.namespace",
              "type": "string",
              "value": "org.acme.server.WizardServerResource"
            },
            {
              "key": "http.request.method",
              "type": "string",
              "value": "GET"
            },
            {
              "key": "code.function",
              "type": "string",
              "value": "step1"
            },
            {
              "key": "http.route",
              "type": "string",
              "value": "/wizard-server/step_1"
            },
            {
              "key": "http.response.body.size",
              "type": "int64",
              "value": 11
            },
            {
              "key": "http.response.status_code",
              "type": "int64",
              "value": 200
            },
            {
              "key": "url.scheme",
              "type": "string",
              "value": "http"
            },
            {
              "key": "server.port",
              "type": "int64",
              "value": 8080
            },
            {
              "key": "span.kind",
              "type": "string",
              "value": "server"
            },
            {
              "key": "internal.span.format",
              "type": "string",
              "value": "otlp"
            }
          ],
          "logs": [],
          "processID": "p1",
          "warnings": null
        },
        {
          "traceID": "6e10a4f88b501f26142756421dcb40a9",
          "spanID": "d84715cac324505a",
          "operationName": "GET /wizard-server/step_3",
          "references": [
            {
              "refType": "CHILD_OF",
              "traceID": "6e10a4f88b501f26142756421dcb40a9",
              "spanID": "e25b894b1492fd55"
            }
          ],
          "startTime": 1731644787517348,
          "duration": 1005729,
          "tags": [
            {
              "key": "server.address",
              "type": "string",
              "value": "localhost"
            },
            {
              "key": "client.address",
              "type": "string",
              "value": "127.0.0.1"
            },
            {
              "key": "user_agent.original",
              "type": "string",
              "value": "Quarkus REST Client"
            },
            {
              "key": "url.path",
              "type": "string",
              "value": "/wizard-server/step_3"
            },
            {
              "key": "code.namespace",
              "type": "string",
              "value": "org.acme.server.WizardServerResource"
            },
            {
              "key": "http.request.method",
              "type": "string",
              "value": "GET"
            },
            {
              "key": "code.function",
              "type": "string",
              "value": "step3"
            },
            {
              "key": "http.route",
              "type": "string",
              "value": "/wizard-server/step_3"
            },
            {
              "key": "http.response.body.size",
              "type": "int64",
              "value": 11
            },
            {
              "key": "http.response.status_code",
              "type": "int64",
              "value": 200
            },
            {
              "key": "url.scheme",
              "type": "string",
              "value": "http"
            },
            {
              "key": "server.port",
              "type": "int64",
              "value": 8080
            },
            {
              "key": "span.kind",
              "type": "string",
              "value": "server"
            },
            {
              "key": "internal.span.format",
              "type": "string",
              "value": "otlp"
            }
          ],
          "logs": [],
          "processID": "p1",
          "warnings": null
        },
        {
          "traceID": "6e10a4f88b501f26142756421dcb40a9",
          "spanID": "e25b894b1492fd55",
          "operationName": "GET /step_3",
          "references": [
            {
              "refType": "CHILD_OF",
              "traceID": "6e10a4f88b501f26142756421dcb40a9",
              "spanID": "795b9fe4719c53b3"
            }
          ],
          "startTime": 1731644787516839,
          "duration": 1007112,
          "tags": [
            {
              "key": "server.address",
              "type": "string",
              "value": "localhost"
            },
            {
              "key": "http.request.method",
              "type": "string",
              "value": "GET"
            },
            {
              "key": "http.response.status_code",
              "type": "int64",
              "value": 200
            },
            {
              "key": "url.full",
              "type": "string",
              "value": "http://localhost:8080/wizard-server/step_3"
            },
            {
              "key": "server.port",
              "type": "int64",
              "value": 8080
            },
            {
              "key": "span.kind",
              "type": "string",
              "value": "client"
            },
            {
              "key": "internal.span.format",
              "type": "string",
              "value": "otlp"
            }
          ],
          "logs": [],
          "processID": "p1",
          "warnings": null
        },
        {
          "traceID": "6e10a4f88b501f26142756421dcb40a9",
          "spanID": "6117ee1b325348df",
          "operationName": "GET /step_3",
          "references": [
            {
              "refType": "CHILD_OF",
              "traceID": "6e10a4f88b501f26142756421dcb40a9",
              "spanID": "795b9fe4719c53b3"
            }
          ],
          "startTime": 1731644787516408,
          "duration": 4008008,
          "tags": [
            {
              "key": "server.address",
              "type": "string",
              "value": "localhost"
            },
            {
              "key": "http.request.method",
              "type": "string",
              "value": "GET"
            },
            {
              "key": "http.response.status_code",
              "type": "int64",
              "value": 200
            },
            {
              "key": "url.full",
              "type": "string",
              "value": "http://localhost:8080/wizard-server/step_2"
            },
            {
              "key": "server.port",
              "type": "int64",
              "value": 8080
            },
            {
              "key": "span.kind",
              "type": "string",
              "value": "client"
            },
            {
              "key": "internal.span.format",
              "type": "string",
              "value": "otlp"
            }
          ],
          "logs": [],
          "processID": "p1",
          "warnings": null
        },
        {
          "traceID": "6e10a4f88b501f26142756421dcb40a9",
          "spanID": "981ba4af000341fc",
          "operationName": "GET /wizard-server/step_2",
          "references": [
            {
              "refType": "CHILD_OF",
              "traceID": "6e10a4f88b501f26142756421dcb40a9",
              "spanID": "6117ee1b325348df"
            }
          ],
          "startTime": 1731644787517409,
          "duration": 4006274,
          "tags": [
            {
              "key": "server.address",
              "type": "string",
              "value": "localhost"
            },
            {
              "key": "client.address",
              "type": "string",
              "value": "127.0.0.1"
            },
            {
              "key": "user_agent.original",
              "type": "string",
              "value": "Quarkus REST Client"
            },
            {
              "key": "url.path",
              "type": "string",
              "value": "/wizard-server/step_2"
            },
            {
              "key": "code.namespace",
              "type": "string",
              "value": "org.acme.server.WizardServerResource"
            },
            {
              "key": "http.request.method",
              "type": "string",
              "value": "GET"
            },
            {
              "key": "code.function",
              "type": "string",
              "value": "step2"
            },
            {
              "key": "http.route",
              "type": "string",
              "value": "/wizard-server/step_2"
            },
            {
              "key": "http.response.body.size",
              "type": "int64",
              "value": 11
            },
            {
              "key": "http.response.status_code",
              "type": "int64",
              "value": 200
            },
            {
              "key": "url.scheme",
              "type": "string",
              "value": "http"
            },
            {
              "key": "server.port",
              "type": "int64",
              "value": 8080
            },
            {
              "key": "span.kind",
              "type": "string",
              "value": "server"
            },
            {
              "key": "internal.span.format",
              "type": "string",
              "value": "otlp"
            }
          ],
          "logs": [],
          "processID": "p1",
          "warnings": null
        },
        {
          "traceID": "6e10a4f88b501f26142756421dcb40a9",
          "spanID": "40d15e4143e4ed6f",
          "operationName": "GET /wizard-server/complete",
          "references": [
            {
              "refType": "CHILD_OF",
              "traceID": "6e10a4f88b501f26142756421dcb40a9",
              "spanID": "28c7dc7067a25965"
            }
          ],
          "startTime": 1731644791527162,
          "duration": 1006097,
          "tags": [
            {
              "key": "server.address",
              "type": "string",
              "value": "localhost"
            },
            {
              "key": "client.address",
              "type": "string",
              "value": "127.0.0.1"
            },
            {
              "key": "user_agent.original",
              "type": "string",
              "value": "Quarkus REST Client"
            },
            {
              "key": "url.path",
              "type": "string",
              "value": "/wizard-server/complete"
            },
            {
              "key": "code.namespace",
              "type": "string",
              "value": "org.acme.server.WizardServerResource"
            },
            {
              "key": "http.request.method",
              "type": "string",
              "value": "GET"
            },
            {
              "key": "code.function",
              "type": "string",
              "value": "complete"
            },
            {
              "key": "http.route",
              "type": "string",
              "value": "/wizard-server/complete"
            },
            {
              "key": "http.response.body.size",
              "type": "int64",
              "value": 13
            },
            {
              "key": "http.response.status_code",
              "type": "int64",
              "value": 200
            },
            {
              "key": "url.scheme",
              "type": "string",
              "value": "http"
            },
            {
              "key": "server.port",
              "type": "int64",
              "value": 8080
            },
            {
              "key": "span.kind",
              "type": "string",
              "value": "server"
            },
            {
              "key": "internal.span.format",
              "type": "string",
              "value": "otlp"
            }
          ],
          "logs": [],
          "processID": "p1",
          "warnings": null
        },
        {
          "traceID": "6e10a4f88b501f26142756421dcb40a9",
          "spanID": "28c7dc7067a25965",
          "operationName": "GET /complete",
          "references": [
            {
              "refType": "CHILD_OF",
              "traceID": "6e10a4f88b501f26142756421dcb40a9",
              "spanID": "795b9fe4719c53b3"
            }
          ],
          "startTime": 1731644791526528,
          "duration": 1007556,
          "tags": [
            {
              "key": "server.address",
              "type": "string",
              "value": "localhost"
            },
            {
              "key": "http.request.method",
              "type": "string",
              "value": "GET"
            },
            {
              "key": "http.response.status_code",
              "type": "int64",
              "value": 200
            },
            {
              "key": "url.full",
              "type": "string",
              "value": "http://localhost:8080/wizard-server/complete"
            },
            {
              "key": "server.port",
              "type": "int64",
              "value": 8080
            },
            {
              "key": "span.kind",
              "type": "string",
              "value": "client"
            },
            {
              "key": "internal.span.format",
              "type": "string",
              "value": "otlp"
            }
          ],
          "logs": [],
          "processID": "p1",
          "warnings": null
        },
        {
          "traceID": "6e10a4f88b501f26142756421dcb40a9",
          "spanID": "795b9fe4719c53b3",
          "operationName": "GET /wizard-client/work",
          "references": [],
          "startTime": 1731644781619844,
          "duration": 10915466,
          "tags": [
            {
              "key": "user_agent.original",
              "type": "string",
              "value": "IntelliJ HTTP Client/IntelliJ IDEA 2024.2.3"
            },
            {
              "key": "code.function",
              "type": "string",
              "value": "work"
            },
            {
              "key": "http.response.status_code",
              "type": "int64",
              "value": 200
            },
            {
              "key": "url.scheme",
              "type": "string",
              "value": "http"
            },
            {
              "key": "server.port",
              "type": "int64",
              "value": 8080
            },
            {
              "key": "http.request.body.size",
              "type": "int64",
              "value": 0
            },
            {
              "key": "server.address",
              "type": "string",
              "value": "localhost"
            },
            {
              "key": "client.address",
              "type": "string",
              "value": "127.0.0.1"
            },
            {
              "key": "url.path",
              "type": "string",
              "value": "/wizard-client/work"
            },
            {
              "key": "code.namespace",
              "type": "string",
              "value": "org.acme.client.WizardClientResource"
            },
            {
              "key": "http.request.method",
              "type": "string",
              "value": "GET"
            },
            {
              "key": "http.route",
              "type": "string",
              "value": "/wizard-client/work"
            },
            {
              "key": "http.response.body.size",
              "type": "int64",
              "value": 10
            },
            {
              "key": "span.kind",
              "type": "string",
              "value": "server"
            },
            {
              "key": "internal.span.format",
              "type": "string",
              "value": "otlp"
            }
          ],
          "logs": [],
          "processID": "p1",
          "warnings": null
        }
      ],
      "processes": {
        "p1": {
          "serviceName": "quarkus-open-telemetry-bug",
          "tags": [
            {
              "key": "host.name",
              "type": "string",
              "value": "....local"
            },
            {
              "key": "otel.library.name",
              "type": "string",
              "value": "io.quarkus.opentelemetry"
            },
            {
              "key": "service.version",
              "type": "string",
              "value": "1.0.0-SNAPSHOT"
            },
            {
              "key": "telemetry.sdk.language",
              "type": "string",
              "value": "java"
            },
            {
              "key": "telemetry.sdk.name",
              "type": "string",
              "value": "opentelemetry"
            },
            {
              "key": "telemetry.sdk.version",
              "type": "string",
              "value": "1.42.1"
            },
            {
              "key": "webengine.name",
              "type": "string",
              "value": "Quarkus"
            },
            {
              "key": "webengine.version",
              "type": "string",
              "value": "999-SNAPSHOT"
            }
          ]
        }
      },
      "warnings": null
    }
  ],
  "total": 0,
  "limit": 0,
  "offset": 0,
  "errors": null
}
``` 
</p>
</details> 

We have three operation names where `"operationName": "GET /step_3"` but we should have only one. And in two of them, the url.full tag corresponds to another url that was called previously.

### How to Reproduce?

Reproducer: `https://github.com/jcuero/quarkus-open-telemetry-bug`

Run the project and execute: 

`curl -X GET --location "http://localhost:8080/wizard-client/work"
`

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jcuero**
When combining multiple unis, the operationName field retains the last uni processed instead of retaining the value it was initialized with.

- Fixes: #44524

### CODE REVIEW

**Comment by geoand** [comment]
Thanks a lot for this!

I agree the problem needs to be fixed, but I am not convinced this is the proper solution. I will spend some time looking into it as I think the way `ClientObservabilityHandler` is being used was incorrect from the start.

File: independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/impl/HandlerChain.java [hunk 1]
```diff
@@ -47,9 +47,27 @@ public HandlerChain(boolean captureStacktrace, int maxChunkSize, boolean followR
...
+        return new HandlerChain(clientCaptureCurrentContextRestHandler, clientSwitchToRequestContextRestHandler,
+                clientSendHandler, clientSetResponseEntityRestHandler, clientResponseCompleteRestHandler, clientErrorHandler);
+    }
+
     HandlerChain setPreClientSendHandler(ClientRestHandler preClientSendHandler) {
-        this.preClientSendHandler = preClientSendHandler;
-        return this;
+        HandlerChain newHandlerChain = newInstance();
+        newHandlerChain.preClientSendHandler = preClientSendHandler;
+        return newHandlerChain;
```
Comment (geoand) [inline independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/impl/HandlerChain.java:70]: Wouldn't the changes here alone be enough to fix the problem? Asking because the change to `ClientRequestContextImpl` don't seem necessary (although the might be correct)

File: independent-projects/resteasy-reactive/client/runtime/src/test/java/org/jboss/resteasy/reactive/client/impl/HandlerChainTest.java [hunk 2]
```diff
@@ -15,16 +12,18 @@
 import org.jboss.resteasy.reactive.common.jaxrs.ConfigurationImpl;
 import org.junit.jupiter.api.Test;
 
+import static org.junit.jupiter.api.Assertions.*;
```
Comment (geoand) [inline independent-projects/resteasy-reactive/client/runtime/src/test/java/org/jboss/resteasy/reactive/client/impl/HandlerChainTest.java:15]: Please avoid star imports

**Comment by geoand** [comment]
I am also interested to know if CI passed on your fork with this change

**Review by brunobat — CHANGES_REQUESTED** [review]
This makes sense to me and the test is thorough. 
Left just a minor thingy.

File: independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/impl/ClientRequestContextImpl.java [hunk 3]
```diff
@@ -63,16 +62,10 @@ public ClientRequestContextImpl(RestClientRequestContext restClientRequestContex
...
         // A separate context allows integrations like OTel to create a separate Span for each invocation (expected)
-        Context ctxt = Vertx.currentContext();
-        if (ctxt != null && VertxContext.isDuplicatedContext(ctxt)) {
-            this.context = ctxt;
-        } else {
-            Context current = client.vertx.getOrCreateContext();
-            this.context = VertxContext.createNewDuplicatedContext(current);
-        }
+        Context current = client.vertx.getOrCreateContext();
+        this.context = VertxContext.createNewDuplicatedContext(current);
```
Comment (geoand) [inline independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/impl/ClientRequestContextImpl.java:68]: I'm actually unsure of this. I would really like to know if the tests pass without this change

Comment (brunobat) [reply independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/impl/ClientRequestContextImpl.java:68]: It fails, I tried the test with no main changes.

Comment (jcuero) [reply independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/impl/ClientRequestContextImpl.java:68]: Note that if I do not ensure that a DuplicateContext instance is created, the result in the trace is still inconsistent.

Now, without modifying this logic and only keeping the changes made in HandlerChain, the only thing different is that there are two traces where `"operationName": "GET /step_3"`. but still inconsistent.

<details><summary>Trace Data</summary>
<p>

```
{
  "data": [
    {
      "traceID": "f839289a74ed082f3839bc6968765708",
      "spans": [
        {
          "traceID": "f839289a74ed082f3839bc6968765708",
          "spanID": "f1cf382a3d83054f",
          "operationName": "GET /wizard-server/start",
          "references": [
            {
              "refType": "CHILD_OF",
              "traceID": "f839289a74ed082f3839bc6968765708",
              "spanID": "298e03112df3e297"
            }
          ],
          "startTime": 1731672920394667,
          "duration": 2020218,
          "tags": [
            {
              "key": "server.address",
              "type": "string",
              "value": "localhost"
            },
            {
              "key": "client.address",
              "type": "string",
              "value": "127.0.0.1"
            },
            {
              "key": "user_agent.original",
              "type": "string",
              "value": "Quarkus REST Client"
            },
            {
              "key": "url.path",
              "type": "string",
              "value": "/wizard-server/start"
            },
            {
              "key": "code.namespace",
              "type": "string",
              "value": "org.acme.server.WizardServerResource"
            },
            {
              "key": "http.response.body.size",
              "type": "int64",
              "value": 10
            },
            {
              "key": "http.request.method",
              "type": "string",
              "value": "GET"
            },
            {
              "key": "code.function",
              "type": "string",
              "value": "start"
            },
            {
              "key": "http.route",
              "type": "string",
              "value": "/wizard-server/start"
            },
            {
              "key": "server.port",
              "type": "int64",
              "value": 8080
            },
            {
              "key": "url.scheme",
              "type": "string",
              "value": "http"
            },
            {
              "key": "http.response.status_code",
              "type": "int64",
              "value": 200
            },
            {
              "key": "span.kind",
              "type": "string",
              "value": "server"
            },
            {
              "key": "internal.span.format",
              "type": "string",
              "value": "otlp"
            }
          ],
          "logs": [],
          "processID": "p1",
          "warnings": null
        },
        {
          "traceID": "f839289a74ed082f3839bc6968765708",
          "spanID": "9aabd1c958cde2cc",
          "operationName": "GET /step_3",
          "references": [
            {
              "refType": "CHILD_OF",
              "traceID": "f839289a74ed082f3839bc6968765708",
              "spanID": "97a9eae6612ae05c"
            }
          ],
          "startTime": 1731672922433087,
          "duration": 1004952,
          "tags": [
            {
              "key": "server.address",
              "type": "string",
              "value": "localhost"
            },
            {
              "key": "http.request.method",
              "type": "string",
              "value": "GET"
            },
            {
              "key": "server.port",
              "type": "int64",
              "value": 8080
            },
            {
              "key": "url.full",
              "type": "string",
              "value": "http://localhost:8080/wizard-server/step_3"
            },
            {
              "key": "http.response.status_code",
              "type": "int64",
              "value": 200
            },
            {
              "key": "span.kind",
              "type": "string",
              "value": "client"
            },
            {
              "key": "internal.span.format",
              "type": "string",
              "value": "otlp"
            }
          ],
          "logs": [],
          "processID": "p1",
          "warnings": null
        },
        {
          "traceID": "f839289a74ed082f3839bc6968765708",
          "spanID": "298e03112df3e297",
          "operationName": "GET /start",
          "references": [
            {
              "refType": "CHILD_OF",
              "traceID": "f839289a74ed082f3839bc6968765708",
              "spanID": "97a9eae6612ae05c"
            }
          ],
          "startTime": 1731672920392373,
          "duration": 2026956,
          "tags": [
            {
              "key": "server.address",
              "type": "string",
              "value": "localhost"
            },
            {
              "key": "http.request.method",
              "type": "string",
              "value": "GET"
            },
            {
              "key": "server.port",
              "type": "int64",
              "value": 8080
            },
            {
              "key": "url.full",
              "type": "string",
              "value": "http://localhost:8080/wizard-server/start"
            },
            {
              "key": "http.response.status_code",
              "type": "int64",
              "value": 200
            },
            {
              "key": "span.kind",
              "type": "string",
              "value": "client"
            },
            {
              "key": "internal.span.format",
              "type": "string",
              "value": "otlp"
            }
          ],
          "logs": [],
          "processID": "p1",
          "warnings": null
        },
        {
          "traceID": "f839289a74ed082f3839bc6968765708",
          "spanID": "34bbf1dbe559e321",
          "operationName": "GET /wizard-server/step_3",
          "references": [
            {
              "refType": "CHILD_OF",
              "traceID": "f839289a74ed082f3839bc6968765708",
              "spanID": "9aabd1c958cde2cc"
            }
          ],
          "startTime": 1731672922434013,
          "duration": 1003499,
          "tags": [
            {
              "key": "server.address",
              "type": "string",
              "value": "localhost"
            },
            {
              "key": "client.address",
              "type": "string",
              "value": "127.0.0.1"
            },
            {
              "key": "user_agent.original",
              "type": "string",
              "value": "Quarkus REST Client"
            },
            {
              "key": "url.path",
              "type": "string",
              "value": "/wizard-server/step_3"
            },
            {
              "key": "code.namespace",
              "type": "string",
              "value": "org.acme.server.WizardServerResource"
            },
            {
              "key": "http.response.body.size",
              "type": "int64",
              "value": 11
            },
            {
              "key": "http.request.method",
              "type": "string",
              "value": "GET"
            },
            {
              "key": "code.function",
              "type": "string",
              "value": "step3"
            },
            {
              "key": "http.route",
              "type": "string",
              "value": "/wizard-server/step_3"
            },
            {
              "key": "server.port",
              "type": "int64",
              "value": 8080
            },
            {
              "key": "url.scheme",
              "type": "string",
              "value": "http"
            },
            {
              "key": "http.response.status_code",
              "type": "int64",
              "value": 200
            },
            {
              "key": "span.kind",
              "type": "string",
              "value": "server"
            },
            {
              "key": "internal.span.format",
              "type": "string",
              "value": "otlp"
            }
          ],
          "logs": [],
          "processID": "p1",
          "warnings": null
        },
        {
          "traceID": "f839289a74ed082f3839bc6968765708",
          "spanID": "f4af771e76197e50",
          "operationName": "GET /wizard-server/step_1",
          "references": [
            {
              "refType": "CHILD_OF",
              "traceID": "f839289a74ed082f3839bc6968765708",
              "spanID": "e83972f0306f2118"
            }
          ],
          "startTime": 1731672922432499,
          "duration": 1007849,
          "tags": [
            {
              "key": "server.address",
              "type": "string",
              "value": "localhost"
            },
            {
              "key": "client.address",
              "type": "string",
              "value": "127.0.0.1"
            },
            {
              "key": "user_agent.original",
              "type": "string",
              "value": "Quarkus REST Client"
            },
            {
              "key": "url.path",
              "type": "string",
              "value": "/wizard-server/step_1"
            },
            {
              "key": "code.namespace",
              "type": "string",
              "value": "org.acme.server.WizardServerResource"
            },
            {
              "key": "http.response.body.size",
              "type": "int64",
              "value": 11
            },
            {
              "key": "http.request.method",
              "type": "string",
              "value": "GET"
            },
            {
              "key": "code.function",
              "type": "string",
              "value": "step1"
            },
            {
              "key": "http.route",
              "type": "string",
              "value": "/wizard-server/step_1"
            },
            {
              "key": "server.port",
              "type": "int64",
              "value": 8080
            },
            {
              "key": "url.scheme",
              "type": "string",
              "value": "http"
            },
            {
              "key": "http.response.status_code",
              "type": "int64",
              "value": 200
            },
            {
              "key": "span.kind",
              "type": "string",
              "value": "server"
            },
            {
              "key": "internal.span.format",
              "type": "string",
              "value": "otlp"
            }
          ],
          "logs": [],
          "processID": "p1",
          "warnings": null
        },
        {
          "traceID": "f839289a74ed082f3839bc6968765708",
          "spanID": "e83972f0306f2118",
          "operationName": "GET /step_1",
          "references": [
            {
              "refType": "CHILD_OF",
              "traceID": "f839289a74ed082f3839bc6968765708",
              "spanID": "97a9eae6612ae05c"
            }
          ],
          "startTime": 1731672922431589,
          "duration": 1009121,
          "tags": [
            {
              "key": "server.address",
              "type": "string",
              "value": "localhost"
            },
            {
              "key": "http.request.method",
              "type": "string",
              "value": "GET"
            },
            {
              "key": "server.port",
              "type": "int64",
              "value": 8080
            },
            {
              "key": "url.full",
              "type": "string",
              "value": "http://localhost:8080/wizard-server/step_1"
            },
            {
              "key": "http.response.status_code",
              "type": "int64",
              "value": 200
            },
            {
              "key": "span.kind",
              "type": "string",
              "value": "client"
            },
            {
              "key": "internal.span.format",
              "type": "string",
              "value": "otlp"
            }
          ],
          "logs": [],
          "processID": "p1",
          "warnings": null
        },
        {
          "traceID": "f839289a74ed082f3839bc6968765708",
          "spanID": "97a9eae6612ae05c",
          "operationName": "GET /wizard-client/work",
          "references": [],
          "startTime": 1731672920336452,
          "duration": 7116351,
          "tags": [
            {
              "key": "server.address",
              "type": "string",
              "value": "localhost"
            },
            {
              "key": "client.address",
              "type": "string",
              "value": "127.0.0.1"
            },
            {
              "key": "url.path",
              "type": "string",
              "value": "/wizard-client/work"
            },
            {
              "key": "code.namespace",
              "type": "string",
              "value": "org.acme.client.WizardClientResource"
            },
            {
              "key": "http.response.body.size",
              "type": "int64",
              "value": 10
            },
            {
              "key": "http.request.method",
              "type": "string",
              "value": "GET"
            },
            {
              "key": "http.route",
              "type": "string",
              "value": "/wizard-client/work"
            },
            {
              "key": "user_agent.original",
              "type": "string",
              "value": "IntelliJ HTTP Client/IntelliJ IDEA 2024.2.3"
            },
            {
              "key": "code.function",
              "type": "string",
              "value": "work"
            },
            {
              "key": "server.port",
              "type": "int64",
              "value": 8080
            },
            {
              "key": "http.request.body.size",
              "type": "int64",
              "value": 0
            },
            {
              "key": "url.scheme",
              "type": "string",
              "value": "http"
            },
            {
              "key": "http.response.status_code",
              "type": "int64",
              "value": 200
            },
            {
              "key": "span.kind",
              "type": "string",
              "value": "server"
            },
            {
              "key": "internal.span.format",
              "type": "string",
              "value": "otlp"
            }
          ],
          "logs": [],
          "processID": "p1",
          "warnings": null
        },
        {
          "traceID": "f839289a74ed082f3839bc6968765708",
          "spanID": "ed26d8a51091431c",
          "operationName": "GET /wizard-server/step_2",
          "references": [
            {
              "refType": "CHILD_OF",
              "traceID": "f839289a74ed082f3839bc6968765708",
              "spanID": "6ef91de78192d16b"
            }
          ],
          "startTime": 1731672922433616,
          "duration": 4006163,
          "tags": [
            {
              "key": "server.address",
              "type": "string",
              "value": "localhost"
            },
            {
              "key": "client.address",
              "type": "string",
              "value": "127.0.0.1"
            },
            {
              "key": "user_agent.original",
              "type": "string",
              "value": "Quarkus REST Client"
            },
            {
              "key": "url.path",
              "type": "string",
              "value": "/wizard-server/step_2"
            },
            {
              "key": "code.namespace",
              "type": "string",
              "value": "org.acme.server.WizardServerResource"
            },
            {
              "key": "http.response.body.size",
              "type": "int64",
              "value": 11
            },
            {
              "key": "http.request.method",
              "type": "string",
              "value": "GET"
            },
            {
              "key": "code.function",
              "type": "string",
              "value": "step2"
            },
            {
              "key": "http.route",
              "type": "string",
              "value": "/wizard-server/step_2"
            },
            {
              "key": "server.port",
              "type": "int64",
              "value": 8080
            },
            {
              "key": "url.scheme",
              "type": "string",
              "value": "http"
            },
            {
              "key": "http.response.status_code",
              "type": "int64",
              "value": 200
            },
            {
              "key": "span.kind",
              "type": "string",
              "value": "server"
            },
            {
              "key": "internal.span.format",
              "type": "string",
              "value": "otlp"
            }
          ],
          "logs": [],
          "processID": "p1",
          "warnings": null
        },
        {
          "traceID": "f839289a74ed082f3839bc6968765708",
          "spanID": "b320954bb3eadbb7",
          "operationName": "GET /complete",
          "references": [
            {
              "refType": "CHILD_OF",
              "traceID": "f839289a74ed082f3839bc6968765708",
              "spanID": "97a9eae6612ae05c"
            }
          ],
          "startTime": 1731672926443614,
          "duration": 1007537,
          "tags": [
            {
              "key": "server.address",
              "type": "string",
              "value": "localhost"
            },
            {
              "key": "http.request.method",
              "type": "string",
              "value": "GET"
            },
            {
              "key": "server.port",
              "type": "int64",
              "value": 8080
            },
            {
              "key": "url.full",
              "type": "string",
              "value": "http://localhost:8080/wizard-server/complete"
            },
            {
              "key": "http.response.status_code",
              "type": "int64",
              "value": 200
            },
            {
              "key": "span.kind",
              "type": "string",
              "value": "client"
            },
            {
              "key": "internal.span.format",
              "type": "string",
              "value": "otlp"
            }
          ],
          "logs": [],
          "processID": "p1",
          "warnings": null
        },
        {
          "traceID": "f839289a74ed082f3839bc6968765708",
          "spanID": "a92ac52b7309b7e6",
          "operationName": "GET /wizard-server/complete",
          "references": [
            {
              "refType": "CHILD_OF",
              "traceID": "f839289a74ed082f3839bc6968765708",
              "spanID": "b320954bb3eadbb7"
            }
          ],
          "startTime": 1731672926444862,
          "duration": 1005187,
          "tags": [
            {
              "key": "server.address",
              "type": "string",
              "value": "localhost"
            },
            {
              "key": "client.address",
              "type": "string",
              "value": "127.0.0.1"
            },
            {
              "key": "user_agent.original",
              "type": "string",
              "value": "Quarkus REST Client"
            },
            {
              "key": "url.path",
              "type": "string",
              "value": "/wizard-server/complete"
            },
            {
              "key": "code.namespace",
              "type": "string",
              "value": "org.acme.server.WizardServerResource"
            },
            {
              "key": "http.response.body.size",
              "type": "int64",
              "value": 13
            },
            {
              "key": "http.request.method",
              "type": "string",
              "value": "GET"
            },
            {
              "key": "code.function",
              "type": "string",
              "value": "complete"
            },
            {
              "key": "http.route",
              "type": "string",
              "value": "/wizard-server/complete"
            },
            {
              "key": "server.port",
              "type": "int64",
              "value": 8080
            },
            {
              "key": "url.scheme",
              "type": "string",
              "value": "http"
            },
            {
              "key": "http.response.status_code",
              "type": "int64",
              "value": 200
            },
            {
              "key": "span.kind",
              "type": "string",
              "value": "server"
            },
            {
              "key": "internal.span.format",
              "type": "string",
              "value": "otlp"
            }
          ],
          "logs": [],
          "processID": "p1",
          "warnings": null
        },
        {
          "traceID": "f839289a74ed082f3839bc6968765708",
          "spanID": "6ef91de78192d16b",
          "operationName": "GET /step_3",
          "references": [
            {
              "refType": "CHILD_OF",
              "traceID": "f839289a74ed082f3839bc6968765708",
              "spanID": "97a9eae6612ae05c"
            }
          ],
          "startTime": 1731672922432678,
          "duration": 4007676,
          "tags": [
            {
              "key": "server.address",
              "type": "string",
              "value": "localhost"
            },
            {
              "key": "http.request.method",
              "type": "string",
              "value": "GET"
            },
            {
              "key": "server.port",
              "type": "int64",
              "value": 8080
            },
            {
              "key": "url.full",
              "type": "string",
              "value": "http://localhost:8080/wizard-server/step_2"
            },
            {
              "key": "http.response.status_code",
              "type": "int64",
              "value": 200
            },
            {
              "key": "span.kind",
              "type": "string",
              "value": "client"
            },
            {
              "key": "internal.span.format",
              "type": "string",
              "value": "otlp"
            }
          ],
          "logs": [],
          "processID": "p1",
          "warnings": null
        }
      ],
      "processes": {
        "p1": {
          "serviceName": "quarkus-open-telemetry-bug",
          "tags": [
            {
              "key": "host.name",
              "type": "string",
              "value": "....local"
            },
            {
              "key": "otel.library.name",
              "type": "string",
              "value": "io.quarkus.opentelemetry"
            },
            {
              "key": "service.version",
              "type": "string",
              "value": "1.0.0-SNAPSHOT"
            },
            {
              "key": "telemetry.sdk.language",
              "type": "string",
              "value": "java"
            },
            {
              "key": "telemetry.sdk.name",
              "type": "string",
              "value": "opentelemetry"
            },
            {
              "key": "telemetry.sdk.version",
              "type": "string",
              "value": "1.42.1"
            },
            {
              "key": "webengine.name",
              "type": "string",
              "value": "Quarkus"
            },
            {
              "key": "webengine.version",
              "type": "string",
              "value": "999-SNAPSHOT"
            }
          ]
        }
      },
      "warnings": null
    }
  ],
  "total": 0,
  "limit": 0,
  "offset": 0,
  "errors": null
}
``` 

</p>
</details>

Comment (jcuero) [reply independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/impl/ClientRequestContextImpl.java:68]: When ClientObservabilityHandler calls this constructor, It does this for each of the identified template paths. So if you reuse the instance, some ClientObservabilityHandler will override the ClientUrlPathTemplate which is used to construct the correct operationName value. 

https://github.com/quarkusio/quarkus/blob/main/independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/handlers/ClientObservabilityHandler.java#L21

Comment (geoand) [reply independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/impl/ClientRequestContextImpl.java:68]: In any case, you've done excellent work here! 

Initially we did do it way you are proposing here, but it was changed in #27629

Comment (jcuero) [reply independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/impl/ClientRequestContextImpl.java:68]: Sounds good. Thank you so much for your support. I appreciate it. 

I found that change (https://github.com/quarkusio/quarkus/commit/ac1a11e274b281c291933c394258d8caeae2ecc1) two days ago but I didn't find the reasons why it was reverted. Please let me know if you find a better solution.

Comment (geoand) [reply independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/impl/ClientRequestContextImpl.java:68]: I will keep you updated

**Comment by jcuero** [comment]
> Can you please squash the commits and force push?
> 
> I would like to take this out of draft and see what CI says about it, because the more I look at it, the more I think the context handling here is correct

Done!

**Review by brunobat — APPROVED** [review]
All tests pass. This seems ok to me.

**Comment by brunobat** [comment]
@geoand What do you think?

**Comment by geoand** [comment]
Let's include it but definitely not backport it as this needs a lot of bake time

**Comment by jcuero** [comment]
Thank you so much! @brunobat and @geoand

**Comment by geoand** [comment]
Thank you!

File: independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/impl/ClientRequestContextImpl.java (hunk 3 above)
Comment (geoand) [reply independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/impl/ClientRequestContextImpl.java:68]: This change did indeed cause a breakage: https://github.com/quarkusio/quarkus/issues/46798

Comment (jcuero) [reply independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/impl/ClientRequestContextImpl.java:68]: I'm sorry about that, @geoand . I didn't mean to.

Comment (geoand) [reply independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/impl/ClientRequestContextImpl.java:68]: No problem at all! I added the comment only for posterity so we can have a link of what caused what. There is absolutely no reason to apologize!
