### PR TITLE
REST Client Reactive: support POJO as non-file fields in multipart messages

### LINKED ISSUE #19892: Support for serializing POJOs to multipart forms in REST Client Reactive
### Description

Using server side REST or REST reactive multipart forms, you can include POJOs and deserialize them from JSON payloads. Using REST client (non-reactive) this works as well in the other direction (POJOs get serialized as JSON). But using the REST Client Reactive, this is not possible as (right now) only Strings or binaries can be used:

```
// test endpoint in REST client
@Path("/test")
@Consumes(MediaType.MULTIPART_FORM_DATA)
@POST
Response test(@MultipartForm MyForm form);
```

..with the following “form“:

```
class MyForm {
   @FormParam("data")
   @PartType(MediaType.APPLICATION_JSON)
   public Data data;
   @FormParam("document")
   @PartType("application/pdf")
   public File document;
}
```
…while "Data“ is a POJO that should be serialized as JSON:
```
class Data {
   public String foo;
   public LocalDate bar;
}
```
Results in an error: org.jboss.resteasy.reactive.client.api.InvalidRestClientDefinitionException: Failed to generate client for class interface ...: Unsupported multipart form field on: …Data . Supported types are: java.lang.String, java.io.File, java.nio.Path and io.vertx.core.Buffer

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by michalszynkiewicz**
fixes #19892

### CODE REVIEW

File: independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/impl/multipart/QuarkusMultipartFormUpload.java [hunk 1]
```diff
@@ -0,0 +1,202 @@
...
+import io.vertx.core.http.impl.headers.HeadersAdaptor;
+import io.vertx.core.streams.ReadStream;
+import io.vertx.core.streams.impl.InboundBuffer;
+import java.io.File;
+import java.nio.charset.Charset;
+
+/**
+ * based on {@link io.vertx.ext.web.client.impl.MultipartFormUpload}
+ */
+public class QuarkusMultipartFormUpload implements ReadStream<Buffer> {
```
Comment (geoand) [inline independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/impl/multipart/QuarkusMultipartFormUpload.java:28]: I sure hope this is a straight copy of `io.vertx.ext.web.client.impl.MultipartFormUpload`, otherwise it will be impossible to vouch for :)

Comment (michalszynkiewicz) [reply independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/impl/multipart/QuarkusMultipartFormUpload.java:28]: the only different thing is https://github.com/quarkusio/quarkus/pull/20127/files/106b744f930cdafb9f6e0cb545501bff9a2d9669#diff-4ceae636c50f58f65afb1a870e6887596574811b729893add5b4b13a64840fb9R73-R78

Comment (geoand) [reply independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/impl/multipart/QuarkusMultipartFormUpload.java:28]: Great!

**Comment by geoand** [comment]
My only real question is whether all the codepaths are tested

**Comment by michalszynkiewicz** [comment]
The integration test we had tested all the cases but passing a POJO.
I added a case for POJO. I'll add one more for the case where the POJO field is null

**Comment by michalszynkiewicz** [comment]
done

**Review by geoand — APPROVED** [review]

**Comment by jsmrcka** [comment]
Do you plan a backport to 2.2? If not, for what reason? @geoand @michalszynkiewicz

**Comment by geoand** [comment]
Not really as it could introduce regressions we don't want in patch releases.
