### PR TITLE
Fix resolution of media type for Hibernate Validator in Resteasy Reactive

### LINKED ISSUE #20888: Hibernate Validator: Wrong MediaType resolution in Resteasy Reactive
### Describe the bug

The hibernate validator extension only takes into account the `@Produces` annotation set at Method/Class level. The `accept` header set by users is ignored. For example, having:

```
@GET
@Path("/rest-end-point-validation/{id}/")
@Produces({ MediaType.APPLICATION_JSON, MediaType.TEXT_PLAIN })
public String testRestEndPointValidation(@Digits(integer = 5, fraction = 0) @RestPath("id") String id) {
    return id;
}
```

When there is validation errors, the result will always be JSON, regardless if the user calls it with the HTTP header `ACCEPT=text/plain`. 

### Expected behavior

The hibernate validator should take into account the header ACCEPT to serialise the validator errors.
This affects to the RESTEASY classic and reactive extensions.

### Actual behavior

_No response_

### How to Reproduce?

1.- `git clone https://github.com/Sgitario/quarkus-test-suite`
2.- `cd quarkus-test-suite`
3.- `git checkout reproducer_20859`
4.- `cd http-minimum`
5.- `mvn clean verify` to use 999-SNAPSHOT
or `mvn clean verify -Dquarkus.platform.version=2.4.0.CR1` to use 2.4.0.CR1

See commit https://github.com/Sgitario/quarkus-test-suite/commit/fbad513377bac62c3e81a1e45ee5e99b5e378b6e

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Sgitario**
As the Resteasy Reactive is adding the `text/plain` media type for endpoints returning String, we can't infer the media type that is defined in the produces annotation. Therefore, we'll always supply the media type from the user accept header if it's supported, or JSON by default (as it was working before).

Fix https://github.com/quarkusio/quarkus/issues/20888

### CODE REVIEW

File: extensions/hibernate-validator/runtime/src/main/java/io/quarkus/hibernate/validator/runtime/jaxrs/ResteasyReactiveViolationExceptionMapper.java [hunk 1]
```diff
@@ -75,9 +90,15 @@ private Response buildViolationReportResponse(ConstraintViolationException cve)
      * This also what Reactive Routes uses
      */
     public static class ViolationReport {
```
Comment (Sgitario) [inline extensions/hibernate-validator/runtime/src/main/java/io/quarkus/hibernate/validator/runtime/jaxrs/ResteasyReactiveViolationExceptionMapper.java:92]: Converting the ViolationReport into a mutable object, so some serializers like JAXB can work fine with it.

File: extensions/hibernate-validator/runtime/src/main/java/io/quarkus/hibernate/validator/runtime/jaxrs/ResteasyReactiveViolationExceptionMapper.java [hunk 2]
```diff
@@ -89,17 +110,44 @@ public String getTitle() {
...
             return violations;
         }
 
+        public void setViolations(List<Violation> violations) {
+            this.violations = violations;
+        }
+
+        @Override
+        public String toString() {
+            return "ViolationReport{" +
```
Comment (Sgitario) [inline extensions/hibernate-validator/runtime/src/main/java/io/quarkus/hibernate/validator/runtime/jaxrs/ResteasyReactiveViolationExceptionMapper.java:135]: This is to not having to have difference behaviours when using `text/plain`.

File: extensions/hibernate-validator/runtime/src/main/java/io/quarkus/hibernate/validator/runtime/jaxrs/ResteasyReactiveViolationExceptionMapper.java [hunk 3]
```diff
@@ -56,17 +64,24 @@ private boolean isReturnValueViolation(ConstraintViolation<?> violation) {
...
-    }
-
     private Response buildViolationReportResponse(ConstraintViolationException cve) {
+        Status status = Status.BAD_REQUEST;
+        Response.ResponseBuilder builder = Response.status(status);
+        builder.header(Validation.VALIDATION_HEADER, "true");
+
+        // Check standard media types.
+        MediaType mediaType = ValidatorMediaTypeUtil.getAcceptMediaType(
+                headers.getAcceptableMediaTypes())
```
Comment (Sgitario) [inline extensions/hibernate-validator/runtime/src/main/java/io/quarkus/hibernate/validator/runtime/jaxrs/ResteasyReactiveViolationExceptionMapper.java:74]: I can't use the produces from `ResteasyReactiveRequestContext` because it seems that a `fake` text/plain media item is being added (when return type is string).

File: extensions/hibernate-validator/runtime/src/main/java/io/quarkus/hibernate/validator/runtime/jaxrs/ResteasyReactiveViolationExceptionMapper.java [hunk 4]
```diff
@@ -56,17 +64,25 @@ private boolean isReturnValueViolation(ConstraintViolation<?> violation) {
...
-        return Response.status(status).entity(entity).build();
-    }
-
     private Response buildViolationReportResponse(ConstraintViolationException cve) {
+        Status status = Status.BAD_REQUEST;
+        Response.ResponseBuilder builder = Response.status(status);
+        builder.header(Validation.VALIDATION_HEADER, "true");
+
+        // Check standard media types.
+        MediaType mediaType = ValidatorMediaTypeUtil.getAcceptMediaTypeFromSupported(headers.getAcceptableMediaTypes());
```
Comment (geoand) [inline extensions/hibernate-validator/runtime/src/main/java/io/quarkus/hibernate/validator/runtime/jaxrs/ResteasyReactiveViolationExceptionMapper.java:73]: Wasn't this the one that did a bunch of reflection?

Comment (Sgitario) [reply extensions/hibernate-validator/runtime/src/main/java/io/quarkus/hibernate/validator/runtime/jaxrs/ResteasyReactiveViolationExceptionMapper.java:73]: No, this method is simply checking whether the list of media items provided by the user via the ACCEPT header is supported. 
The method that was using reflection was removed from this util.

**Review by geoand — APPROVED** [review]
