### PR TITLE
Micrometer @Timed and @Counted

### LINKED ISSUE #12343: io.micrometer.core.annotation.Timed doesn't work
quarkus version: 1.8.1

I'm using quarkus-smallrye-reactive-messaging-kafka and quarkus-resteasy-mutiny
When I add that annotation to a resteasy endpoint nothing happens

`@Timed(value = ".my.endpoint")`

later when I open prometious metrics endpoint `curl localhost:8080/metrics/` I don't see my meters there. How can I time my endpoints?

Same happens when I try to time my kafka consumer. Nothing happens...

```
@Timed(value = ".my.consumer")
@Incoming("my-kafka-topic")
```

### PR DESCRIPTION
**Pull request by ebullient**
Resolves #12343

### CODE REVIEW

File: extensions/micrometer/deployment/src/main/java/io/quarkus/micrometer/deployment/MicrometerProcessor.java [hunk 1]
```diff
@@ -84,6 +99,12 @@ UnremovableBeanBuildItem registerAdditionalBeans(CombinedIndexBuildItem indexBui
                 .addBeanClass(CompositeRegistryCreator.class)
                 .addBeanClass(MeterFilterConstraint.class)
                 .addBeanClass(MeterFilterConstraints.class)
+                .addBeanClass(TIMED_ANNOTATION.toString())
```
Comment (kenfinnigan) [inline extensions/micrometer/deployment/src/main/java/io/quarkus/micrometer/deployment/MicrometerProcessor.java:102]: [nit] Just a thought I had from a general perspective and not specific to this PR only, but can we get smarter about registering beans as being unremovable?

For instance, can we check for usage of `@Timed` in application code before marking the classes for it as unremovable?

Maybe the cost of that search isn't worth the small amount of marking classes as unremovable, but I'm curious

File: extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/MicrometerCountedInterceptor.java [hunk 2]
```diff
@@ -0,0 +1,111 @@
+package io.quarkus.micrometer.runtime;
+
+import java.lang.reflect.Method;
+import java.util.concurrent.CompletionStage;
+
```
Comment (kenfinnigan) [inline extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/MicrometerCountedInterceptor.java:5]: Wondering if, long term, there's a better home for this kind of thing so other projects can get this OOTB?

**Review by kenfinnigan — APPROVED** [review]

File: extensions/micrometer/deployment/src/main/java/io/quarkus/micrometer/deployment/MicrometerProcessor.java (hunk 1 above)
Comment (ebullient) [reply extensions/micrometer/deployment/src/main/java/io/quarkus/micrometer/deployment/MicrometerProcessor.java:102]: yea.. I can chew on it

File: extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/MicrometerCountedInterceptor.java (hunk 2 above)
Comment (ebullient) [reply extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/MicrometerCountedInterceptor.java:5]: I don't follow. This is specific to what the @Timed / @Counted implementation for Micrometer annotations expect.. 

And I'm not sure I entirely love this. This is probably where the most changes might come as it stews.

Comment (kenfinnigan) [reply extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/MicrometerCountedInterceptor.java:5]: Agree it's specific to those annotations, but thinking from a perspective of other projects using Micrometer directly, do they need this too? If so, where should it go?

Maybe the answer is they don't, and it's fine to be only here.

File: extensions/micrometer/deployment/src/main/java/io/quarkus/micrometer/deployment/MicrometerProcessor.java (hunk 1 above)
Comment (jkschneider) [reply extensions/micrometer/deployment/src/main/java/io/quarkus/micrometer/deployment/MicrometerProcessor.java:102]: If it's speed of search that's a consideration (and assuming this can be some sort of compile-only dependency) I cannot recommend https://github.com/classgraph/classgraph enough. So fast...

File: extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/MicrometerCountedInterceptor.java (hunk 2 above)
Comment (jkschneider) [reply extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/MicrometerCountedInterceptor.java:5]: I think this commit disappeared. Happy to pull something into Micrometer core if it's generally useful.

File: extensions/micrometer/deployment/src/main/java/io/quarkus/micrometer/deployment/MicrometerProcessor.java (hunk 1 above)
Comment (ebullient) [reply extensions/micrometer/deployment/src/main/java/io/quarkus/micrometer/deployment/MicrometerProcessor.java:105]: Moved annotations (and interceptors) to a different set of additional beans that are removable. Everything still works (I added more tests to an IT bucket to make sure)

**Review by kenfinnigan — APPROVED** [review]

File: extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/MicrometerCountedInterceptor.java (hunk 2 above)
Comment (ebullient) [reply extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/MicrometerCountedInterceptor.java:5]: I think I'll keep it for now.. I just don't like it. I don't believe there is anything here that can be pulled out to somewhere more generic.
