### PR TITLE
Fix thread safety of TransactionEntityManagers

### LINKED ISSUE #2848: ConcurrentModificationException in TransactionEntityManagers.getEntityManager
**Describe the bug**

I get `ConcurrentModificationException` at the start of a `ab` (https://httpd.apache.org/docs/2.4/programs/ab.html) benchmark session if the benchmarked REST endpoint needs database access. The issue only seems to appear if a concurrency level > 4 (i.e. `ab -c 5`) is used for the benchmark and `ab` is started prior to any request involving database access.

I think the concurrency value may depend on your machine - I am testing this on an Intel Core i7-6700HQ (4 cores, 8 threads) and with 5 I am able to trigger the bug ~90% of the time.

I wrote a little application displaying the issue. It uses:

* `quarkus-hibernate-orm-panache`
* `quarkus-jdbc-h2`
* `quarkus-resteasy-jsonb`

It can be found at https://github.com/j-be/quarkus-concurrent-modification-bug

I did NOT yet check native images yet, just the good-old ` java -jar`. I will update this report if I find out anything on that front.

I am working on a pull-request and will publish it shortly.

**Expected behavior**
No `ConcurrentModificationException` when running 

**Actual behavior**
```
2019-06-16 14:29:19,306 ERROR [io.und.request] (executor-thread-3) UT005023: Exception handling request to /genre: org.jboss.resteasy.spi.UnhandledException: java.util.ConcurrentModificationException
	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106)
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:372)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:209)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:496)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:252)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:153)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:362)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:156)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:238)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:234)
	at io.quarkus.resteasy.runtime.ResteasyFilter$ResteasyResponseWrapper.sendError(ResteasyFilter.java:72)
	at io.undertow.servlet.handlers.DefaultServlet.doGet(DefaultServlet.java:175)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:686)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:791)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at io.quarkus.resteasy.runtime.ResteasyFilter.doFilter(ResteasyFilter.java:43)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.quarkus.undertow.runtime.UndertowDeploymentTemplate$7$1$1.call(UndertowDeploymentTemplate.java:469)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleRequest(ServletInitialHandler.java:197)
	at io.undertow.server.handlers.HttpContinueReadHandler.handleRequest(HttpContinueReadHandler.java:65)
	at io.quarkus.undertow.runtime.UndertowDeploymentTemplate$1.handleRequest(UndertowDeploymentTemplate.java:104)
	at io.undertow.server.handlers.CanonicalPathHandler.handleRequest(CanonicalPathHandler.java:49)
	at io.quarkus.undertow.deployment.devmode.UndertowHotReplacementSetup.handleHotDeploymentRequest(UndertowHotReplacementSetup.java:77)
	at io.quarkus.undertow.deployment.devmode.UndertowHotReplacementSetup$1$1.handleRequest(UndertowHotReplacementSetup.java:56)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:364)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
	at io.quarkus.runtime.CleanableExecutor$CleaningRunnable.run(CleanableExecutor.java:243)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1395)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:32)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
Caused by: java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
	at io.quarkus.hibernate.orm.runtime.TransactionEntityManagers.getEntityManager(TransactionEntityManagers.java:51)
	at io.quarkus.hibernate.orm.runtime.JPAResourceReferenceProvider$1.delegate(JPAResourceReferenceProvider.java:54)
	at io.quarkus.hibernate.orm.runtime.entitymanager.ForwardingEntityManager.createQuery(ForwardingEntityManager.java:158)
	at io.quarkus.hibernate.orm.panache.runtime.JpaOperations.count(JpaOperations.java:293)
	at org.duckdns.owly.quarkus.service.GerneService.count(GerneService.java)
	at org.duckdns.owly.quarkus.service.GerneService_ClientProxy.count(Unknown Source)
	at org.duckdns.owly.quarkus.resources.GenreResource.getCount(GenreResource.java:23)
	at org.duckdns.owly.quarkus.resources.GenreResource_ClientProxy.getCount(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:151)
	at org.jboss.resteasy.core.MethodInjectorImpl.lambda$invoke$3(MethodInjectorImpl.java:122)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:680)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2094)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:143)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:122)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:568)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:442)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:396)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:362)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:398)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:367)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invoke$1(ResourceMethodInvoker.java:341)
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:143)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:341)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:477)
	... 56 more
```

**To Reproduce**
Prerequisits:
* Ubuntu Linux 18.04 LTS with:
  * `mvn 3.6.0` from package repositories
  *  `openJDK 11` from package repositories
  * `apache2-utils` from package repositories

1. clone https://github.com/j-be/quarkus-concurrent-modification-bug
2. Run `mvn clean package quarkus:dev` (you may `-DskipTests` if you want)
3. Open a second terminal and run `ab -n 100 -c 5 localhost:8080/genre`
4. You should now see a `java.util.ConcurrentModificationException`. If not, stop the quarkus server, start it again and increase `ab`'s concurrency.

**Configuration**
I doubt this is of any relevance, yet for completeness sake: 
```properties
# Configuration file
# key = value

# configure your datasource
quarkus.datasource.url = jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE
quarkus.datasource.driver = org.h2.Driver
quarkus.datasource.username = sa
quarkus.datasource.password =

# drop and create the database at startup (use `update` to only update the schema)
quarkus.hibernate-orm.database.generation = create
```

**Screenshots**
Not applicable.

**Environment (please complete the following information):**
 - Output of `uname -a`:
Linux albatros 4.15.0-51-generic #55-Ubuntu SMP Wed May 15 14:27:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux 
 - Output of `java -version`: 
openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+7-Ubuntu-1ubuntu218.04.1)
OpenJDK 64-Bit Server VM (build 11.0.3+7-Ubuntu-1ubuntu218.04.1, mixed mode, sharing)
 - GraalVM version (if different from Java): 
Not applicable (yet)
 - Quarkus version or git rev: 
both `0.16.1` from Maven Central and current HEAD of master (59c85e3ba31535be5ef9bfe1566304d3ae31bb1a)

**Additional context**
Not applicable (I guess)

### PR DESCRIPTION
**Pull request by j-be**
Without this, it is possible to trigger ConcurrentModificationException if
sending parallel requests before TransactionEntityManagers.managers was
filled. One way to do so would be to invoke ab (ApacheBench) with a
concurrency level > 4 on a fresh started instance of Quarkus.

For further details see #2848

fixes #2848

### CODE REVIEW

File: extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/TransactionEntityManagers.java [hunk 1]
```diff
@@ -32,9 +32,18 @@ public TransactionEntityManagers() {
     }
 
     public EntityManager getEntityManager(String unitName) {
-        return managers.computeIfAbsent(unitName,
-                un -> new TransactionScopedEntityManager(tm, tsr, jpaConfig.getEntityManagerFactory(un), unitName,
-                        requestScopedEntityManagers));
+        TransactionScopedEntityManager ret = managers.get(unitName);
```
Comment (stuartwdouglas) [inline extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/TransactionEntityManagers.java]: This should just be changed to be a concurrent hash map, and TransactionEntityManagers should really be explicitly marked as being ApplicationScoped to make it clear how the lifecycle works.

**Review by stuartwdouglas — DISMISSED** [review]

File: extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/TransactionEntityManagers.java (hunk 1 above)
Comment (j-be) [reply extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/TransactionEntityManagers.java]: From what I saw (i.e. 3 `ConcurrentModificationException` being thrown in a very short amount of time) I concluded, that this is a very often invoked code-path. But the bug only affects the first few invocations, after that it should be fine (I guess).

I did NOT benchmark this solution against a `ConcurrentHashMap` one, but I can if needed. My strain of thought was to just avoid `ConcurrentModificationException` without affecting performance to much.  Therefore I went for the least intrusive way (i.e. a double-checked write lock) to avoid a major performance hit, as I guessed a `null` check is quicker then a fully fledged `ConcurrentHashMap`.

Comment (gsmet) [reply extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/TransactionEntityManagers.java]: In Hibernate Validator, we switched to the following pattern for this sort of things:
```
private ConcurrentHashMap map...;
```

And then:
```
Object entry = map.get("");
if (map != null) {
    return entry;
}
return map.computeIfAbsent(...);
```

From the benchmarks we run, it's faster than using `computeIfAbsent()` directly (at least with JDK 8).

Comment (j-be) [reply extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/TransactionEntityManagers.java]: @gsmet That seems like a decent approach.

The thing I am most skeptic about is, if `ConcurrentHashMap.get()` is measurably slower then `HashMap.get()`, which would mean that performance is slower on every call, not just on the first few.

I will try to find some time to run some benchmarks against all 3 approaches (plain `HashMap`, my pull-request, `ConcurrentHashMap` with @gsmet extension). I'll let you know what I find out.

Comment (gsmet) [reply extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/TransactionEntityManagers.java]: @j-be would you mind implementing the approach I presented and run the benchmark afterwards?

The code is obviously wrong so I think we should fix it for 0.17.0 with a decent approach. Then we can run benchmarks and tune the approach.

0.17.0 is planned for Wednesday so we would need a patch for tomorrow. If you can't make it, I'll do it.

Thanks!

Comment (j-be) [reply extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/TransactionEntityManagers.java]: Sure thing. Implemented as @gsmet proposed. First (nothing more then a smoke-test) benchmarks show no difference between the `ConcurrentHashMap` implementation and my initial one (Requests per second: 8784.85 vs. 8755.22 is well within the margin of error).

**Review by gsmet — APPROVED** [review]
Thanks!

I squashed the 2 commits and made a few other adjustments.

The only interesting one is that I prefer we use the `ConcurrentMap` interface in this case so that the map is clearly marked as concurrent.

Let's wait for CI and merge.

**Comment by j-be** [comment]
Great!

Thanks for the support. I went for a bit more benchmarking yesterday after pushing and did not find any performance difference between the initial `HashMap` based implementation and the `ConcurrentHashMap` implementation. The differences between 2 runs on the same codebase was around 3%, the difference between the implementations was well within that range.

Environment was:

- h2 InMemory with a single, empty table (`jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE`)
- `PanacheRepository`'s count as the only executed function
- Result is wrapped in an Object and serialized to JSON (I thought that is a more realistic scenario)

**Comment by gsmet** [comment]
Thanks for checking! Merging now...
