### PR TITLE
Include RowSet properties file in native image

### LINKED ISSUE #5666: JdbcTemplate is missing a resource bunde for native
### Bug description

When we use `JdbcTemplate.queryForRowSet(...)`, the application will fail in native mode with the following stack trace:
```
2024-01-23 22:18:22,146 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /foo failed, error id: 06c0ccc2-ed4f-4822-b478-e00e33ba3a61-1: java.util.MissingResourceException: Can't find bundle for base name com.sun.rowset.RowSetResourceBundle, locale en_US
	at java.base@21/java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:2059)
	at java.base@21/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1697)
	at java.base@21/java.util.ResourceBundle.getBundleFromModule(ResourceBundle.java:1617)
	at java.base@21/java.util.ResourceBundle.getBundle(ResourceBundle.java:1017)
	at java.sql.rowset@21/com.sun.rowset.JdbcRowSetResourceBundle.<init>(JdbcRowSetResourceBundle.java:105)
	at java.sql.rowset@21/com.sun.rowset.JdbcRowSetResourceBundle.getJdbcRowSetResourceBundle(JdbcRowSetResourceBundle.java:124)
	at java.sql.rowset@21/com.sun.rowset.CachedRowSetImpl.<init>(CachedRowSetImpl.java:364)
	at java.sql.rowset@21/com.sun.rowset.RowSetFactoryImpl.createCachedRowSet(RowSetFactoryImpl.java:49)
	at org.springframework.jdbc.core.SqlRowSetResultSetExtractor.newCachedRowSet(SqlRowSetResultSetExtractor.java:90)
	at org.springframework.jdbc.core.SqlRowSetResultSetExtractor.createSqlRowSet(SqlRowSetResultSetExtractor.java:74)
	at org.springframework.jdbc.core.SqlRowSetResultSetExtractor.extractData(SqlRowSetResultSetExtractor.java:58)
	at org.springframework.jdbc.core.SqlRowSetResultSetExtractor.extractData(SqlRowSetResultSetExtractor.java:42)
	at org.springframework.jdbc.core.JdbcTemplate$1QueryStatementCallback.doInStatement(JdbcTemplate.java:454)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:383)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:466)
	at org.springframework.jdbc.core.JdbcTemplate.queryForRowSet(JdbcTemplate.java:531)
	at de.turing85.quarkus.jdbc.template.Resource.get(Resource.java:28)
	at de.turing85.quarkus.jdbc.template.Resource$quarkusrestinvoker$get_bd3a803a64f67f513762962949efcedfd340aa43.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@21/java.lang.Thread.runWith(Thread.java:1596)
	at java.base@21/java.lang.Thread.run(Thread.java:1583)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:833)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211)
```

---
Reproducer: 
- clone https://github.com/turing85/quarkus-jdbc-template: 
  ```bash
  git clone https://github.com/turing85/quarkus-jdbc-template.git && cd quarkus-jdbc-template
  ```
- build & run in JVM mode: 
  ```bash
  ./mvnw clean verify
  ```
- observe that the integration test passes
- build & run in native mode: 
  ```bash
  ./mvnw -Dnative clean verify
  ```
- observe that the integration test fails, and that the above stack trace can be found in the application logs

---
Affected quarkus versions: at least `3.2.8.Final` to `3.6.7`.

---
Comment: I opened the issue here since the dependency that provides `JdbcTemplate` (`spring-jdbc`) is a transitive dependency of, e.g., `camel-quarkus-sql`. As far as I know, the quarkus core does not import `spring-jdbc` anywhere.

### PR DESCRIPTION
**Pull request by gastaldi**
Follow-up on #38362. This fixes the `Resource javax/sql/rowset/rowset.properties not found` error.

I've tested with the reproducer project in https://github.com/apache/camel-quarkus/issues/5666#issue-2097032589 provided by @turing85 and it works.

- Fixes https://github.com/apache/camel-quarkus/issues/5666

### CODE REVIEW

File: extensions/agroal/deployment/src/main/java/io/quarkus/agroal/deployment/AgroalProcessor.java [hunk 1]
```diff
@@ -411,7 +411,14 @@ void adaptOpenTelemetryJdbcInstrumentationForNative(BuildProducer<RemovedResourc
...
-        return new NativeImageResourceBundleBuildItem("com.sun.rowset.RowSetResourceBundle");
+    void registerRowSetSupport(
+            BuildProducer<NativeImageResourceBundleBuildItem> resourceBundleProducer,
+            BuildProducer<NativeImageResourceBuildItem> nativeResourceProducer,
+            BuildProducer<ReflectiveClassBuildItem> reflectiveClassProducer) {
+        resourceBundleProducer.produce(new NativeImageResourceBundleBuildItem("com.sun.rowset.RowSetResourceBundle"));
+        nativeResourceProducer.produce(new NativeImageResourceBuildItem("javax/sql/rowset/rowset.properties"));
+        reflectiveClassProducer.produce(ReflectiveClassBuildItem.builder(
+                "com.sun.rowset.providers.RIOptimisticProvider",
+                "com.sun.rowset.providers.RIXMLProvider").build());
```
Comment (gsmet) [inline extensions/agroal/deployment/src/main/java/io/quarkus/agroal/deployment/AgroalProcessor.java:422]: This I'm not totally sure as it might bring a lot of XML classes with it.

This needs to be checked by compiling a small app with Agroal (and a datasource) and check the size of the native executable before and after the commit.

**Review by gsmet — CHANGES_REQUESTED** [review]
Pending checking the native executable size.

**Comment by gastaldi** [comment]
After the change: 

```
  33.76MB (42.65%) for code area:    52,442 compilation units
  44.47MB (56.19%) for image heap:  407,253 objects and 741 resources
 938.98kB ( 1.16%) for other data
  79.14MB in total
``` 

Before the change: 

```
  33.75MB (42.65%) for code area:    52,438 compilation units
  44.47MB (56.19%) for image heap:  407,193 objects and 739 resources
 941.20kB ( 1.16%) for other data
  79.14MB in total
```

File: extensions/agroal/deployment/src/main/java/io/quarkus/agroal/deployment/AgroalProcessor.java (hunk 1 above)
Comment (gastaldi) [reply extensions/agroal/deployment/src/main/java/io/quarkus/agroal/deployment/AgroalProcessor.java:422]: Added the output here: https://github.com/quarkusio/quarkus/pull/38370#issuecomment-1908307782

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Yeah, I agree it's not worth the effort given the very small size increase.

Thanks for checking!
