### PR TITLE
Dont use Facade ClassLoader as TCCL for interacting with profiles

### LINKED ISSUE #47850: Quarkus 3.22 regression - Classloader issue with ConfigProvider used in Test
### Describe the bug

When using a QuarkusTestProfile, if we used ConfigProvider.getConfig(), it's start detecting Config via ServiceLoader.

But it seems that ServiceLoader are impacted by the refactoring of @QuarkusTest in 3.22.

```
 java.util.ServiceConfigurationError: io.smallrye.config.SmallRyeConfigFactory: io.quarkus.runtime.configuration.QuarkusConfigFactory not a subtype
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:593)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1244)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
```

That cause Junit to not detect tests and failed 

````
Error: [ERROR] There was an error in the forked process
Error:  TestEngine with ID 'junit-jupiter' failed to discover tests
Error:  org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
Error:  TestEngine with ID 'junit-jupiter' failed to discover tests
```




### Expected behavior

The Test are executed normally (as  in Quarkus < 3.22 )

### Actual behavior

Tests are not detected and make the build failed

### How to Reproduce?

See : https://github.com/gcuisinier/quarkus-regression-3.22-maven-junit/

### Output of `uname -a` or `ver`

Darwin gcAirM3.local 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:14:59 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T8122 arm64

### Output of `java -version`

openjdk version "21" 2023-09-19

### Quarkus version or git rev

3.22.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by holly-cummins**
Profiles might access smallrye config, so need a sensible TCCL set. As a general rule, anytime we invoke user code, that user code might do something with config, and so the TCCL needs to be not-the-facade-classloader.

We set the TCCL to be the runtime CL nice and early as a result of the fix for #47081, but it's not early enough.  When we create the startup action, it reads config from the test profile. 

We do end up calling 

```
        final Runnable configCleanup = prepareResult.profileInstance() == null ? null
                : setExtraProperties(profile, prepareResult.profileInstance());
```

twice, once in the `AppMakerHelper` and once in the `QuarkusTestExtension`. I'm a bit suspicious of that, but not brave enough to remove the extra call. 

- Resolves: https://github.com/quarkusio/quarkus/issues/47850

### CODE REVIEW

**Comment by holly-cummins** [comment]
On the other hand, the more I stare at [this code](https://github.com/search?q=repo%3Aquarkusio%2Fquarkus%20setExtraProperties&type=code), the less I understand it. 

image

I think maybe some variables have been misnamed. Why do we set the profile's config as the last thing we do before closing an app? Why is there a variable called `configCleanup` which gets run as part of app startup? 

Looking at the code-before-the-rewrite, the relevant section is this:

File: test-framework/junit5/src/main/java/io/quarkus/test/junit/classloading/FacadeClassLoader.java [hunk 1]
```diff
@@ -546,10 +546,19 @@ private QuarkusClassLoader getOrCreateBaseClassLoader(String key, Class<?> requi
...
+
+        // Before interacting with the profiles, set the TCCL to one which is not the FacadeClassloader
+        // This could also go in AppMakerHelper.setExtraProperties, but then it affects more code paths
+        if (profile != null) {
+            Thread.currentThread().setContextClassLoader(profile.getClassLoader());
+        }
         StartupAction startupAction = AppMakerHelper.getStartupAction(requiredTestClass,
                 curatedApplication, profile);
 
+        Thread.currentThread().setContextClassLoader(old);
```
Comment (aloubyansky) [inline test-framework/junit5/src/main/java/io/quarkus/test/junit/classloading/FacadeClassLoader.java:560]: Should we do it in a `finally` block?

Comment (holly-cummins) [reply test-framework/junit5/src/main/java/io/quarkus/test/junit/classloading/FacadeClassLoader.java:560]: Yes, good idea. I had it in a finally block and took it out because the code was easier to read with less indentation, and I decided if an exception happened everything was terrible and so it wouldn't matter if the TCCL was wrong. Will update.

Comment (holly-cummins) [reply test-framework/junit5/src/main/java/io/quarkus/test/junit/classloading/FacadeClassLoader.java:560]: Oh, I remember why I did it without the finally block. If I want to minimise the scope of when we're using the other classloader, and set it back before ` QuarkusClassLoader loader = startupAction.getClassLoader()`,  I'd have to move the `startupAction` out of the scope of the try, and initialise it to null. It adds a bit of cognitive load about why there's no NPE risk.

**Comment by holly-cummins** [comment]
> > On the other hand, the more I stare at [this code](https://github.com/search?q=repo%3Aquarkusio%2Fquarkus%20setExtraProperties&type=code), the less I understand it.
> > image
> > I think maybe some variables have been misnamed. Why do we set the profile's config as the last thing we do before closing an app? Why is there a variable called `configCleanup` which gets run as part of app startup?
> > Looking at the code-before-the-rewrite, the relevant section is this:
> > https://github.com/quarkusio/quarkus/blob/0ff22e458b418f7f23e1236a8894c0b0e32c65ab/test-framework/junit5/src/main/java/io/quarkus/test/junit/AbstractJvmQuarkusTestExtension.java#L154-L175
> > 
> > The new code is less clear, because `AppMakerHelper.setExtraProperties` calls out to `RestorableProperties` (thus making it a 'self-cleaning' property setting) but it's hidden inside the method. And I think both calls are needed, because one is before augmentation, and one is before startup, and config is needed in both cases. Cleanup is also needed in both cases, although in the `AppMakerHelper` case it cleans up immediately after doing its work.
> > So having stared at the code for some time, I've now decided it's confusing, but seems to be doing the right thing. Which is a shame, since it would have been nice to get rid of that first call to `getAdditionalConfig`.
> 
> AFAICS, all this bootstrap is just to create a classloader and put it in `FacadeClassLoader.runtimeClassLoaders`? Should we replace `StartupAction` there with `QuarkusClassLoader`?

I had to think about this, because the `StartupAction` actually holds references to two classloaders, the base runtime classloader (indirectly, via the curated application), and the runtime classloader. But certainly `FacadeClassLoader.runtimeClassLoaders` is badly named. And I can't see any time where we get a `startupAction` and do something other than immediately call `getClassLoader()` on it. I'll try the experiment in another branch.

**Comment by holly-cummins** [comment]
Hmm, I'm troubled by the windows failure. Develocity says it [first appeared](https://ge.quarkus.io/scans/tests?search.timeZoneId=Europe%2FLondon&tests.container=io.quarkus.vertx.http.proxy.TrustedForwarderDnsResolveTest&tests.test=testTrustedProxyResolved#) in https://github.com/quarkusio/quarkus/pull/47904. So I think it's unrelated to this change. Interestingly, I haven't rebased, so this branch doesn't actually have #47904 in it. So it seems maybe there's a third common factor? Or my jobs are the ones that gib has running all of the tests in the windows CI?

**Comment by aloubyansky** [comment]
I don't see how https://github.com/quarkusio/quarkus/pull/47904 could be related changes-wise.
It also doesn't look like this change is the cause of the failure on Windows to me.

**Review by aloubyansky — APPROVED** [review]

**Comment by gsmet** [comment]
@holly-cummins there is a conflict AFAICS.

**Comment by aloubyansky** [comment]
The Gradle failures should be fixed with https://github.com/quarkusio/quarkus/pull/47955
