### PR TITLE
Do not validate configs in unused beans

### LINKED ISSUE #19388: Service attempts to find a config value for an unused bean
### Describe the bug

I have a library with multiple beans in it, each containing config values. I also have a service that only injects one of those beans. But at runtime there is an error attempting to find the config value for the bean that is not used in the service.

Note: I'd like to not use default config values so that anyone actually injecting the bean is required to add it to the config.

### Expected behavior

Successful run.

### Actual behavior

Error find config value for unused bean.

### How to Reproduce?

Reproducer: `service4` in https://github.com/mweber03/quarkus-test

1. `./gradlew service4:quarkusBuild`
2. `docker build -t service4 -f modules/service4/Dockerfile .`
3. `docker run -it -p 8080:8080 service4`

Library with beans: `lib2`

### Output of `uname -a` or `ver`

Ubuntu 20.04

### Output of `java -version`

OpenJDK 11.0.11

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.1.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.1.1

### Additional information

_No response_

### LINKED ISSUE #20275: Allow to disable MP ConfigProperties and ConfigMapping
### Description

Up to now, if we want to ease the mapping of the configuration, we can rely on the annotations `@ConfigProperties` from MicroProfile Config and/or `@ConfigMapping` from SmallRye Config. If used, Quarkus will check at runtime that the corresponding properties are available in the configuration which can be a problem if this part of the configuration only makes sense for production but not for the tests. 

### Implementation ideas

The idea could be to rely on build time conditions to enable or not the annotations `@ConfigProperties` and/or `@ConfigMapping`.

### PR DESCRIPTION
**Pull request by radcortez**
- Fixes #19388
- Fixes #20275

This removes config validations and registrations of mappings / properties if the beans are unused. This may break existent applications if they only use programmatic lookups. In this case, mappings / properties need to be annotated with `@Unremoveable` or use the arc config to not remove beans.

### CODE REVIEW

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ConfigBuildStep.java [hunk 1]
```diff
@@ -103,6 +102,41 @@ void analyzeConfigPropertyInjectionPoints(BeanDiscoveryFinishedBuildItem beanDis
...
+                    .creator(ConfigBeanCreator.class)
+                    .providerType(type)
+                    .types(type)
+                    .addQualifier(MP_CONFIG_PROPERTY_NAME)
+                    .param("requiredType", type.name().toString()).done());
+        }
+    }
+
+    @BuildStep
+    void validateConfigProperties(ValidationPhaseBuildItem validationPhase,
```
Comment (mkouba) [inline extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ConfigBuildStep.java:132]: The method name is a bit misleading and there's already a method called `validateConfigProperties`.

**Review by mkouba — COMMENTED** [review]
I've added one minor comment. Otherwise looks good!

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ConfigBuildStep.java (hunk 1 above)
Comment (radcortez) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ConfigBuildStep.java:132]: Sure, let me find a better name :)

**Comment by mweber03** [comment]
Will this make it into 2.3?

**Comment by radcortez** [comment]
> Will this make it into 2.3?

Yes. I need to update this for something else and it should be good to go.

**Comment by mkouba** [comment]
There are some conflicting files. @radcortez Could you resolve the conflicts first? I will need to check out the PR locally because the list of changes is quite long...

**Comment by radcortez** [comment]
> There are some conflicting files. @radcortez Could you resolve the conflicts first? I will need to check out the PR locally because the list of changes is quite long...

Done. The additional changes are to cover `@ConfigMapping` and `@ConfigProperties` usages.

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ConfigBuildStep.java [hunk 2]
```diff
@@ -250,40 +273,77 @@ void generateConfigClasses(
...
             List<ConfigClassBuildItem> configClasses,
-            BeanRegistrationPhaseBuildItem beanRegistrationPhase,
             CombinedIndexBuildItem combinedIndex,
-            BuildProducer<BeanConfiguratorBuildItem> beanConfigurationRegistry) {
+            BuildProducer<BeanConfiguratorBuildItem> beanConfigurator) {
+
+        Set<ConfigClassBuildItem> configMappings = new HashSet<>();
+        for (InjectionPointInfo injectionPoint : beanRegistration.getInjectionPoints()) {
+            Type type = injectionPoint.getType();
+            for (ConfigClassBuildItem configClass : configClasses) {
```
Comment (mkouba) [inline extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ConfigBuildStep.java:285]: This does not seem to be very efficient for an application with a large number of beans and injection points. I'd probably collect all config classes first, store them in a `Set<DotName> configClasses` and then simply test `configClasses.contains(type.name())` for each injection point.

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ConfigBuildStep.java [hunk 3]
```diff
@@ -315,23 +375,108 @@ private static void collectInterfacesRec(ClassInfo current, IndexView index, Set
...
     }
 
+    @BuildStep
+    void validateConfigMappingsInjectionPoints(
+            ValidationPhaseBuildItem validationPhase,
+            List<ConfigClassBuildItem> configClasses,
+            BuildProducer<ConfigMappingBuildItem> configMappings) {
+
+        Set<ConfigMappingBuildItem> toRegister = new HashSet<>();
+        for (InjectionPointInfo injectionPoint : validationPhase.getContext().getInjectionPoints()) {
```
Comment (mkouba) [inline extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ConfigBuildStep.java:385]: This iteration is also suboptimal. First of all, we don't need to iterate over all injection points if no `configClasses` are defined. Furthermore, we could avoid the nested loop using a similar technique as described in https://github.com/quarkusio/quarkus/pull/19965/files#r719992140/

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ConfigBuildStep.java [hunk 4]
```diff
@@ -315,23 +375,108 @@ private static void collectInterfacesRec(ClassInfo current, IndexView index, Set
...
+                    String prefix = annotationPrefix != null ? annotationPrefix.asString() : configClass.getPrefix();
+                    configMappings.produce(new ConfigMappingBuildItem(configClass.getConfigClass(), prefix));
+                }
+            }
+        }
+
+        boolean noRemovedBeans = validationPhase.getContext().removedBeans().isEmpty();
+        for (ConfigClassBuildItem configClass : configClasses) {
+            if (configClass.isMapping()
+                    && (noRemovedBeans || configClass.getConfigClass().isAnnotationPresent(Unremovable.class))) {
```
Comment (mkouba) [inline extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ConfigBuildStep.java:421]: I'm not sure I understand the condition here. We produce a `ConfigMappingBuildItem` if `quarkus.arc.remove-unused-beans=false` (because otherwise there will be at least one removed bean in 99.99% cases) or if the config class is annotated with `@Unremovable`? That's probably not correct. I think that we should not produce the build item if the relevant synthetic bean was removed. So in theory, we should be able to match the relevant `BeanInfo`.

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ConfigBuildStep.java [hunk 5]
```diff
@@ -250,40 +273,77 @@ void generateConfigClasses(
...
+                }
+            }
+        }
 
-        for (ConfigClassBuildItem configClass : configClasses) {
-            if (configClass.getGeneratedClasses().isEmpty()) {
+        for (ConfigClassBuildItem configClass : configMappings) {
+            beanConfigurator.produce(new BeanConfiguratorBuildItem(
+                    beanRegistration.getContext()
+                            .configure(configClass.getConfigClass())
```
Comment (mkouba) [inline extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ConfigBuildStep.java:297]: You should also make it unremovable via `configurator.unremovable()` if the config interface is annotated with `@Unremovable` because ArC ignores annotations when registering a synthetic bean...

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ConfigBuildStep.java (hunk 2 above)
Comment (mkouba) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ConfigBuildStep.java:285]: Hm, I'm talking about replacement of `type.name().equals(DotName.createSimple(configClass.getConfigClass().getName())`... so no prefix is involved here.

Comment (radcortez) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ConfigBuildStep.java:285]: Yes. I'm already changing the code. I'll send an update soon.

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ConfigBuildStep.java (hunk 4 above)
Comment (radcortez) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ConfigBuildStep.java:421]: I guess I was trying to be too smart by only looking for the annotation if no beans were removed.

Comment (radcortez) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ConfigBuildStep.java]: Ah, I added that, because the Config TCK expects a `DeploymentException`. On the TCK we have `quarkus.arc.remove-unused-beans=false`.

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ConfigBuildStep.java (hunk 5 above)
Comment (radcortez) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ConfigBuildStep.java]: Sure.

**Comment by radcortez** [comment]
@mkouba thanks for the review. I've tried to address all the comments.

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ConfigBuildStep.java (hunk 4 above)
Comment (mkouba) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ConfigBuildStep.java]: I still can't understand ;-). Currently, it reads: "register the config mapping if no bean was removed OR the mapping is annotated with `@Unremovable`". 

You should probably inject the `io.quarkus.arc.deployment.ArcConfig` in the build step and test `ArcConfig.shouldEnableBeanRemoval()` intead of `validationPhase.getContext().removedBeans().isEmpty()`. 

Also even a mapping bean that is not annotated with `@Unremovable` may be considered "unremovable", i.e. when it's injected somewhere. Such a config mapping should be registered as well, or?

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ConfigBuildStep.java (hunk 2 above)
Comment (mkouba) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ConfigBuildStep.java:287]: I'm sorry but I don't see any improvement here. You're still iterating over all `configClasses` for each injection point.
 
Also what's the reason to store `ConfigClassBuildItem` in a set? I mean the class itself does not define `equals()`/`hashCode()` so a list would be probably more appropriate...

BTW we could also skip processing completely if `configClasses.isEmpty()`.

Comment (radcortez) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ConfigBuildStep.java:287]: Ah sorry, nvm. I've changed the validate* methods but not this one.

**Review by mkouba — APPROVED** [review]
Looks good.

**Comment by radcortez** [comment]
Thanks! Sorry for the bumps!

**Comment by mweber03** [comment]
@radcortez any chance this will be in 2.3.1?

**Comment by radcortez** [comment]
Not likely, but 2.4.0 is not far. I'm sorry for the inconvenience :(
