### PR TITLE
Avoid warning on analytics

### LINKED ISSUE #42058: In some context, `NoSuchElementException: No line found` error thrown from telemetry
### Describe the bug

It can be reproduced when using the devfile from the devfile registry and starting the remote dev

see https://github.com/devfile/api/issues/1611

### Expected behavior

no stacktrace

### Actual behavior

there is a stacktrace logged:

```
tools: ----------------------------
tools: --- Help improve Quarkus ---
tools: ----------------------------
tools: * Learn more: https://quarkus.io/usage/
tools: * Do you agree to contribute anonymous build time data to the Quarkus community? (y/n and enter) 
tools: [WARNING] Failed to collect user input for analytics
tools: java.util.NoSuchElementException: No line found
tools:     at java.util.Scanner.nextLine (Scanner.java:1660)
tools:     at io.quarkus.maven.DevMojo.lambda$execute$0 (DevMojo.java:445)
tools:     at io.quarkus.analytics.ConfigService.lambda$userAcceptance$0 (ConfigService.java:79)
tools:     at java.util.concurrent.CompletableFuture$AsyncSupply.run (CompletableFuture.java:1768)
tools:     at java.lang.Thread.run (Thread.java:1583)
tools: [info] [Quarkus build analytics] Didn't receive a valid user's answer: `y` or `n`. The question will be asked again next time.
```

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

I wasn't able to reproduce with a local build https://github.com/devfile/api/issues/1611#issuecomment-2210420139

### PR DESCRIPTION
**Pull request by brunobat**
fixes https://github.com/quarkusio/quarkus/issues/42058

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Comment by geoand** [comment]
Did we have telemetry in LTS? If so, please add the proper backport label

File: devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java [hunk 1]
```diff
@@ -444,7 +444,7 @@ public void close() throws IOException {
             })) {
                 return scanner.nextLine();
```
Comment (apupier) [inline devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java:445]: What about checking if the scanner.hasNextLine() before trying to read the line? It would allow to provide a warn explaining that no prompt was read

Comment (brunobat) [reply devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java:445]: `scanner.hasNextLine()` seems to block waiting for user input.

**Review by gsmet — APPROVED** [review]
