### PR TITLE
Properly ensure that transfer-encoding is not set when content-length exists

### LINKED ISSUE #26464: Resteasy Reactive adds transfer-encoding header though content-length is present
### Describe the bug

I want to stream filedownloads. The filesize is already known (stored in db on upload).
The filesize is important to me, since I can use it as content-length header, which allows the browser to show a progress bar for the download instead of just spinning.

e.g.
image

Without the content-length header, browser would simply show a spinning progress.

In resteasy-classic, this worked without problems.
In resteasy-reactive however, I found that the "Transfer-Encoding: Chunked" header is always added to the response when I am stream, even though I manually set content-length.

```
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public Response hello() {
        String longText = String.join(";", Collections.nCopies(10000000, UUID.randomUUID().toString()));

        byte[] bytes = longText.getBytes(StandardCharsets.UTF_8);

        return Response.ok(new ByteArrayInputStream(bytes), "text/plain")
                .header("Content-length", bytes.length)
                .build();
    }
```

According to the RFC 2616, this behaviour is not allowed.
```
Messages must not include both a Content-Length header field and a non-identity transfer-coding. If the message does include a non-identity transfer-coding, the Content-Length must be ignored.
```
https://greenbytes.de/tech/webdav/rfc2616.html#rfc.section.4.4

### Expected behavior

No Transfer-Encoding header is present if a content-length was already manually set.
The response should still be streamed.

### Actual behavior

image

### How to Reproduce?

Reproducer:
[transfer-encoding-clash.zip](https://github.com/quarkusio/quarkus/files/9017534/transfer-encoding-clash.zip)
 
1. mvn quarkus:dev
2. Open a Browser and the network tools to see response headers
3. Visit http://localhost:8080/hello
4. Inspect the response. With resteasy-reactive, it contains both transfer-encoding and content-length.
5. Change dependency resteasy-reactive to resteasy classic.
6. Visit http://localhost:8080/hello. Only content-length is now present in the response

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19044.1766]

### Output of `java -version`

openjdk 18.0.1 2022-04-19 OpenJDK Runtime Environment Temurin-18.0.1+10 (build 18.0.1+10) OpenJDK 64-Bit Server VM Temurin-18.0.1+10 (build 18.0.1+10, mixed mode, sharing)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.10.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537) Maven home: C:\eclipse\tools\java\maven Java version: 18.0.1, vendor: Eclipse Adoptium, runtime: C:\eclipse\tools\java\18 Default locale: de_DE, platform encoding: UTF-8 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #26464

### CODE REVIEW

File: independent-projects/resteasy-reactive/server/vertx/src/main/java/org/jboss/resteasy/reactive/server/vertx/ResteasyReactiveOutputStream.java [hunk 1]
```diff
@@ -233,12 +236,24 @@ private void prepareWrite(ByteBuf buffer, boolean finished) throws IOException {
...
+    private boolean contentLengthSet() {
+        if (request.response().headers().contains(HttpHeaderNames.CONTENT_LENGTH)) {
+            return true;
+        }
+        LazyResponse lazyResponse = context.getResponse();
+        if (!lazyResponse.isCreated()) {
+            return false;
+        }
+        MultivaluedMap<String, Object> responseHeaders = lazyResponse.get().getHeaders();
+        return (responseHeaders != null) && responseHeaders.containsKey(HttpHeaders.CONTENT_LENGTH);
```
Comment (gsmet) [inline independent-projects/resteasy-reactive/server/vertx/src/main/java/org/jboss/resteasy/reactive/server/vertx/ResteasyReactiveOutputStream.java:254]: You're using `HttpHeaderNames` for one and `HttpHeaders` for the other. Is it normal (just checking)?

Comment (geoand) [reply independent-projects/resteasy-reactive/server/vertx/src/main/java/org/jboss/resteasy/reactive/server/vertx/ResteasyReactiveOutputStream.java:254]: Yes, it's expected. The former is from `Netty` and is of type `CharSequence` (which Vert.x expects) while the latter comes from JAX-RS and is of type `String` (which is what JAX-RS use everywhere)/

**Review by gsmet — APPROVED** [review]
