### PR TITLE
Netty requires more classes to be runtime initialized

### LINKED ISSUE #236: JFRTest#jfrPerfTest fails with Quarkus `main`
## How to reproduce

```
git clone https://github.com/quarkusio/quarkus.git
cd quarkus
./mvnw -Dquickly
cd ../
git clone https://github.com/Karm/mandrel-integration-tests
cd mandrel-integration-tests
mvn clean verify -Dquarkus.version=999-SNAPSHOT -Ptestsuite -Dtest=JFRTest#jfrPerfTest
```

## Failure:

```
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 78.177 s <<< FAILURE! - in org.graalvm.tests.integration.JFRTest
[ERROR] jfrPerfTest{TestInfo}  Time elapsed: 77.691 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: Timeout 10s was reached. Empty webpage does not contain string: `hello' ==> expected: <true> but was: <false>
	at org.graalvm.tests.integration.JFRTest.runBenchmarkForApp(JFRTest.java:355)
	at org.graalvm.tests.integration.JFRTest.startComparisonForBenchmark(JFRTest.java:254)
	at org.graalvm.tests.integration.JFRTest.jfrPerfTestRun(JFRTest.java:214)
	at org.graalvm.tests.integration.JFRTest.jfrPerfTest(JFRTest.java:176)
```

## Additional info

The regression is not caused by a GraalVM change, building with Mandrel 23.1.1.0 also doesn't work.
Setting `quarkus.version` to `3.6.0` makes the test fail in a different stage (possibly a local issue?)

### PR DESCRIPTION
**Pull request by zakkak**
In https://github.com/quarkusio/quarkus/pull/37347 we moved
`PlatformDependent` and `PlatformDependent0` classes to
run-time-initialization as they are platform-dependent and thus need to
be initialized on the target platform. It looks like there are more
classes like these that need to be runtime initialized as they
transitively rely on platform dependent values.

Closes https://github.com/Karm/mandrel-integration-tests/issues/236

Supersedes https://github.com/quarkusio/quarkus/pull/37628

CI run with latest Mandrel 24.0-dev https://github.com/graalvm/mandrel/actions/runs/7147836492

### CODE REVIEW

File: extensions/netty/deployment/src/main/java/io/quarkus/netty/deployment/NettyProcessor.java [hunk 1]
```diff
@@ -162,8 +162,13 @@ NativeImageConfigBuildItem build(
...
 
-        builder.addRuntimeReinitializedClass("io.netty.util.internal.PlatformDependent");
-        builder.addRuntimeReinitializedClass("io.netty.util.internal.PlatformDependent0");
+        builder.addRuntimeReinitializedClass("io.netty.util.internal.PlatformDependent")
+                .addRuntimeReinitializedClass("io.netty.util.internal.PlatformDependent0")
+                .addRuntimeReinitializedClass("io.netty.buffer.PooledByteBufAllocator")
+                .addRuntimeReinitializedClass("io.netty.buffer.UnpooledByteBufAllocator")
+                .addRuntimeReinitializedClass("io.netty.buffer.Unpooled")
+                .addRuntimeReinitializedClass("io.vertx.core.http.impl.Http1xServerResponse")
+                .addRuntimeReinitializedClass("io.netty.handler.codec.http.HttpObjectAggregator");
```
Comment (franz1981) [inline extensions/netty/deployment/src/main/java/io/quarkus/netty/deployment/NettyProcessor.java:171]: I am surprised, we use it? In theory Vertx should handle the whole http 1.1 stack  with https://github.com/eclipse-vertx/vert.x/blob/4.x/src/main/java/io/vertx/core/http/impl/HttpServerWorker.java#L284

Comment (cescoffier) [reply extensions/netty/deployment/src/main/java/io/quarkus/netty/deployment/NettyProcessor.java:171]: +1 - who's loading this?

Comment (zakkak) [reply extensions/netty/deployment/src/main/java/io/quarkus/netty/deployment/NettyProcessor.java:171]: I will have a look next week (along with the rest of the failing tests).

Comment (cescoffier) [reply extensions/netty/deployment/src/main/java/io/quarkus/netty/deployment/NettyProcessor.java:171]: hum it may have found a path that is actually not used. However, adding a substitution might be a bit overkill. So, +1 to re-initialize it.

**Comment by zakkak** [comment]
I ended up adding even more classes to the set of runtime initialized ones. All native tests look good now.

**Review by cescoffier — APPROVED** [review]

File: extensions/netty/deployment/src/main/java/io/quarkus/netty/deployment/NettyProcessor.java (hunk 1 above)
Comment (zakkak) [reply extensions/netty/deployment/src/main/java/io/quarkus/netty/deployment/NettyProcessor.java]: @cescoffier FYI to our so far understanding this happens because when using `--enable-monitoring=jfr` (i.e. `-Dquarkus.native.monitoring=jfr`) GraalVM opens all packages of `java.base` to the unnamed module, which appears to have side-effects on the code reachability of netty.

https://github.com/Karm/mandrel-integration-tests/issues/236#issuecomment-1848206787

**Comment by jerboaa** [comment]
> CI run with latest Mandrel 24.0-dev https://github.com/graalvm/mandrel/actions/runs/7147836492

@zakkak Could you please trigger another run. Many of the shown failures should be gone with a later run. Thanks!

**Comment by zakkak** [comment]
> @zakkak Could you please trigger another run. Many of the shown failures should be gone with a later run. Thanks!

I scheduled a re-run https://github.com/graalvm/mandrel/actions/runs/7147836492 (same url).

**Comment by jerboaa** [comment]
Mandrel IT tests are OK with this now, so +1.

**Comment by zakkak** [comment]
@gsmet it looks like we should have backported this to 3.6 but missed it.

**Comment by ThoSap** [comment]
@zakkak @gsmet do we have to wait until Quarkus 3.7.0 releases on January 31st, or will there be a 3.6.6 release?

**Comment by gsmet** [comment]
This is important enough that I'll try to release a 3.6.6 next Tuesday. Still unsure about my availability to do it but I'll try.

**Comment by gsmet** [comment]
That was for @ThoSap ^
