### PR TITLE
Preserve expected semantics of Maven execution with native profile enabled

### LINKED ISSUE #14320: Native tests fail when quarkus.package.type=uber-jar
**Describe the bug**
Using a brand new project, adding the property `quarkus.package.type=uber-jar` to the `application.properties` so to create an uber jar, the native tests fail to start the native image for an IOException. 

```
[INFO] Running org.acme.getting.started.NativeGreetingResourceIT
Executing [/home/jrota/vagrant/bionic64/issues-reproducers/uber-jar-native-tests-fail/target/uber-jar-native-tests-fail-1.0.0-SNAPSHOT-runner, -Dquarkus.http.port=8081, -Dquarkus.http.ssl-port=8444, -Dtest.url=http://localhost:8081, -Dquarkus.log.file.path=target/target/quarkus.log]
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.112 s <<< FAILURE! - in org.acme.getting.started.NativeGreetingResourceIT
[ERROR] org.acme.getting.started.NativeGreetingResourceIT  Time elapsed: 0.111 s  <<< ERROR!
org.junit.platform.commons.JUnitException: Quarkus native image start failed, original cause: java.io.IOException: Cannot run program "/home/jrota/vagrant/bionic64/issues-reproducers/uber-jar-native-tests-fail/target/uber-jar-native-tests-fail-1.0.0-SNAPSHOT-runner": error=2, No such file or directory
Caused by: java.io.IOException: Cannot run program "/home/jrota/vagrant/bionic64/issues-reproducers/uber-jar-native-tests-fail/target/uber-jar-native-tests-fail-1.0.0-SNAPSHOT-runner": error=2, No such file or directory
Caused by: java.io.IOException: error=2, No such file or directory

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   NativeGreetingResourceIT » JUnit Quarkus native image start failed, original c...
[INFO] 
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
```
The only workaround I found was to create a new default profile to create the uber jar so that the native profile stays clean (see https://github.com/kiegroup/kogito-apps/pull/597/commits/950c7f1123c086889a176c623fc1052092463d7b ). 

**Expected behavior**
The native tests should not fail? 

**Actual behavior**
I guess that the property
```
<properties>
        <quarkus.package.type>native</quarkus.package.type>
</properties>
```
is somehow ignored and the native tests try to use the uber jar as well? 

**To Reproduce**
```
mvn io.quarkus:quarkus-maven-plugin:1.10.5.Final:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=uber-jar-native-tests-fail \
    -DclassName="org.acme.getting.started.GreetingResource" \
    -Dpath="/hello"
cd uber-jar-native-tests-fail
mvn clean verify <- no native tests are executed, ok
mvn clean verify -Pnative <- native tests are executed, ok
```
Add `quarkus.package.type=uber-jar` to `application.properties` and then 
```
mvn clean verify -Pnative <- crash
```
See the exception above

Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific).

https://github.com/r00ta/issues-reproducers/tree/main/uber-jar-native-tests-fail

Or attach an archive containing the reproducer to the issue.

1. Create a new application
2. Add `quarkus.package.type=uber-jar` to `application.properties`
3. run `mvn clean verify -Pnative`

**Configuration**
```properties
quarkus.package.type=uber-jar
```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Linux jrota.remote.csb 4.18.0-80.11.2.el8_0.x86_64 #1 SMP Sun Sep 15 11:24:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: 
 ```
 openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)
```
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: `1.10.5.Final`
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): `mvn`

**Additional context**
(Add any other context about the problem here.)

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #14320

This is certainly a hack, but I believe it is warranted by the fact that users expect `mvn package -Dnative` to work regardless of what they have configured in `application.properties`. Users most likely don't notice that 

```
      <properties>
        <quarkus.package.type>native</quarkus.package.type>
      </properties>
``` 

is being set in the `native` maven profile and certainly don't expect that it will not take effect if the same property is set in `application.properties`.

The reason we haven't encountered this before is because it only manifests if `quarkus.package.type` is set in `application.properties` **and** `pom.xml` is configured in the new style of using the `<quarkus.package.type>` Maven property (which most of our integration tests and quickstarts do not)

### CODE REVIEW

File: integration-tests/spring-data-jpa/src/main/resources/application.properties [hunk 1]
```diff
@@ -1,3 +1,4 @@
+quarkus.package.type=fast-jar
```
Comment (geoand) [inline integration-tests/spring-data-jpa/src/main/resources/application.properties:1]: This was added to trigger the problematic condition that existed before this PR

**Comment by aloubyansky** [comment]
This looks like a general issue, not specific to quarkus.package.type.

**Comment by geoand** [comment]
Sure, the general issue is that the build system properties have lower priority than `application.properties`, but I am not sure if we want to change that entirely (it would be very easy to do) but would potentially be a breaking change) - actually it would be very problematic for the `quarkus.application.name` and similar properties).

I think we should simply deal with the package type which definitely does not behave as expected now, whereas other properties set from build system properties (`quarkus.application.name`) do behave as expected.

**Comment by aloubyansky** [comment]
What about other properties defined in the native profile?

**Comment by aloubyansky** [comment]
By default there are no other properties. But in case somebody wants to add some other properties in there.

**Comment by geoand** [comment]
Yeah exactly, there are no other ones.

Things could get really tricky if users add their own properties there, but I don't think it's something we advertise anyway. The current problem only manifests because **we** add the `quarkus.package.type` in the `native` profile.

**Comment by aloubyansky** [comment]
Perhaps, instead of always prioritizing `quarkus.package.type` from the POM over the app config it should check whether the native profile is activated. It could be done from BuildMojo by checking `mavenProject().getActiveProfiles()`.
I guess we need the equivalent check in the Gradle tasks.

**Comment by geoand** [comment]
I thought of that as well and it is probably a better idea indeed. I'll follow up in a while

**Comment by geoand** [comment]
PR updated.

For Gradle I don't think we have to do anything because according to https://quarkus.io/guides/gradle-tooling#building-a-native-executable the proper way to build a native binary is by executing:

```
./gradlew build -Dquarkus.package.type=native
```

**Comment by famod** [comment]
So, with the lastest push, you _have to_ use `<id>native</id>`?
You cannot use `<id>build-native-image</id>` or `<id>linux-image</id>` etc.?

**Comment by geoand** [comment]
You don't **have** to use anything :). 
It just makes the common case where `quarkus.package.type=native` is set in the `native` profile (as that is what we generate OOTB).
If you need to have more elaborate profile handling, I suggest using Maven's resource filtering, as there is no good way to solve all related use cases in a proper manner (see my comments above on why we don't want to make the build tool properties have higher priority than the `application.properties`).

**Comment by famod** [comment]
I see, thanks for clarifying!

File: devtools/maven/src/main/java/io/quarkus/maven/BuildMojo.java [hunk 2]
```diff
@@ -78,6 +81,17 @@ protected boolean beforeExecute() throws MojoExecutionException {
     protected void doExecute() throws MojoExecutionException {
 
         try {
+            boolean isNativeProfileEnabled = isNativeProfileEnabled();
+            boolean clearPackageTypeSysProp = false;
+            // Essentially what this does is to enable the native package type even if a different package type is set
+            // in application properties. This is done to preserve what users expect to happen when
+            // they execute "mvn package -Dnative" even if quarkus.package.type has been set in application.properties
+            if (isNativeProfileEnabled
+                    && !System.getProperties().containsKey(PACKAGE_TYPE_PROP)) {
```
Comment (aloubyansky) [inline devtools/maven/src/main/java/io/quarkus/maven/BuildMojo.java:90]: Kind of a minor remark, the system property could be checked first, if it's not set there won't be a need to go through the profiles.

File: integration-tests/spring-data-jpa/src/main/resources/application.properties (hunk 1 above)
Comment (aloubyansky) [inline integration-tests/spring-data-jpa/src/main/resources/application.properties:1]: I am wondering whether uber-jar would be a better choice here, considering that fast-jar will soon become the default one? And perhaps be renamed to just 'jar' or something?

**Review by aloubyansky — APPROVED** [review]
I added to minor remarks. But it's ok.

**Comment by aloubyansky** [comment]
Thanks for your efforts @geoand

File: devtools/maven/src/main/java/io/quarkus/maven/BuildMojo.java (hunk 2 above)
Comment (geoand) [reply devtools/maven/src/main/java/io/quarkus/maven/BuildMojo.java]: Done

**Comment by geoand** [comment]
> Thanks for your efforts @geoand

Sure thing!

**Review by aloubyansky — APPROVED** [review]
