### PR TITLE
Avoid trying to set permissions on the cache directory on windows

### LINKED ISSUE #16895: Unable to make the Vert.x cache directory in Windows
## Describe the bug
When running a Quarkus application in Windows, this warning is sometimes printed:

```
{"timestamp":"2021-04-28 13:02:58","sequence":346,"loggerClassName":"org.jboss.logging.Logger","loggerName":"io.quarkus.vertx.core.runtime.VertxCoreRecorder","level":"WARN","message":"Unable to make the Vert.x cache directory (C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\vertx-cache) world readable and writable","threadName":"main","threadId":1,"mdc":{},"ndc":"","hostName":"fv-az158-860","processName":"target/quarkus-app/quarkus-run.jar","processId":3172}
```

Which is unexpected as it should create a temporary folder. 
I think this is related to the changes made in https://github.com/quarkusio/quarkus/issues/7678. Concretely: https://github.com/quarkusio/quarkus/pull/15541/files#diff-a38e0d86cf6a637c19b6e0a0e23959f644886bdcc0f0e5615ce7cfa0e6bc9909R244

### Expected behavior
The Vert.x cache directory should work in Windows

## To Reproduce

A windows based machine is needed.

1. git clone `https://github.com/Sgitario/quarkus-startstop`
2. cd `quarkus-startstop`
3. git checkout `reproducer_16895`
4. `mvn clean verify -Ptestsuite -Dtest=ArtifactGeneratorBOMTest#quarkusUniverseBomExtensionsA`

The test should pass, but it's failing.

### Quarkus version or git rev
1.13.2

### PR DESCRIPTION
**Pull request by cescoffier**
Fix #16895

@rsvoboda This is the approach not trying to set the permission on windows. However, not sure it works on Windows using the WSL emulation.

### CODE REVIEW

File: extensions/vertx-core/runtime/src/main/java/io/quarkus/vertx/core/runtime/VertxCoreRecorder.java [hunk 1]
```diff
@@ -259,9 +259,13 @@ private static VertxOptions convertToVertxOptions(VertxConfiguration conf, Vertx
                 if (!tmp.mkdirs()) {
                     LOGGER.warnf("Unable to create Vert.x cache directory : %s", tmp.getAbsolutePath());
                 }
-                if (!(tmp.setReadable(true, false) && tmp.setWritable(true, false))) {
-                    LOGGER.warnf("Unable to make the Vert.x cache directory (%s) world readable and writable",
-                            tmp.getAbsolutePath());
+                String os = System.getProperty("os.name").toLowerCase();
+                if (!os.contains("win")) {
```
Comment (gsmet) [inline extensions/vertx-core/runtime/src/main/java/io/quarkus/vertx/core/runtime/VertxCoreRecorder.java:263]: Are you sure macOS won't be flagged (Darwin)?

Probably better to have a look how it's done in Smallrye Common here: https://github.com/smallrye/smallrye-common/blob/main/os/src/main/java/io/smallrye/common/os/OS.java#L46 .

**Review by gsmet — DISMISSED** [review]

**Comment by famod** [comment]
@cescoffier 
> However, not sure it works on Windows using the WSL emulation.

FWIW, WSL2 Ubuntu reports `Linux` as `os.name`. I don't have a WSL1 dist around, but I'm 90% sure it'll do the same.

**Comment by rsvoboda** [comment]
I don't have Windows with WSL around to double check this :/
Even if WSL is not handled well I think this is move in the right direction for vanilla Windows.

File: extensions/vertx-core/runtime/src/main/java/io/quarkus/vertx/core/runtime/VertxCoreRecorder.java (hunk 1 above)
Comment (cescoffier) [reply extensions/vertx-core/runtime/src/main/java/io/quarkus/vertx/core/runtime/VertxCoreRecorder.java]: Fixed, using the same approach.

File: extensions/vertx-core/runtime/src/main/java/io/quarkus/vertx/core/runtime/VertxCoreRecorder.java [hunk 2]
```diff
@@ -259,9 +260,13 @@ private static VertxOptions convertToVertxOptions(VertxConfiguration conf, Vertx
...
                     LOGGER.warnf("Unable to create Vert.x cache directory : %s", tmp.getAbsolutePath());
                 }
-                if (!(tmp.setReadable(true, false) && tmp.setWritable(true, false))) {
-                    LOGGER.warnf("Unable to make the Vert.x cache directory (%s) world readable and writable",
-                            tmp.getAbsolutePath());
+                String os = System.getProperty("os.name").toLowerCase(Locale.ENGLISH);
+                if (!os.contains("windows")) {
+                    // Do not execute the following on windows.
+                    if (!(tmp.setReadable(true, false) && tmp.setWritable(true, false))) {
+                        LOGGER.warnf("Unable to make the Vert.x cache directory (%s) world readable and writable",
```
Comment (gsmet) [inline extensions/vertx-core/runtime/src/main/java/io/quarkus/vertx/core/runtime/VertxCoreRecorder.java:267]: Unrelated question but why are we trying to make it world writable? Shouldn't it be only writable by the current user? Am I missing something?

Comment (cescoffier) [reply extensions/vertx-core/runtime/src/main/java/io/quarkus/vertx/core/runtime/VertxCoreRecorder.java:267]: There is a structure. The first level is world writable as multiple Quarkus app started by multiple users will write into it. The nested level is limited to the user.

**Review by rsvoboda — APPROVED** [review]
