### PR TITLE
Vertx: use NoopShutdownExecutorService and DevModeExecutorService

### LINKED ISSUE #16833: quarkus scheduler does not await termination of scheduledExecutor
## Describe the bug
I execute the following code inspired from https://quarkus.io/guides/scheduler:
```
@ApplicationScoped
public class MyTimer {

    public static Logger log = Logger.getLogger(MyTimer.class);

    private final String start = new Date().toString();

    private final AtomicInteger count = new AtomicInteger();

    @Scheduled(every = "10S")
    public void run() {
        for (int i = 0; i < 10; i++) {
            log.info("execute " + start + " => " + count.incrementAndGet());
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
                log.error("timer interrupted", e);
                break;
            }
        }
    }
}
```

When hot code replace happens in dev mode, the scheduler extension does not wait for the `scheduledExecutor` to terminate.
as a result, the old timer continues executing the tasks that are in progress in parallel with the new tasks scheduler by the new timer.
Eventually, the old code finishes up, and only the new timer remains. 

For instance, here is how it looks like with the previous example:
```
...
2021-04-27 14:29:32,002 INFO  [org.acm.get.sta.MyTimer] (executor-thread-1) execute Tue Apr 27 14:29:17 CEST 2021 => 16
2021-04-27 14:29:33,003 INFO  [org.acm.get.sta.MyTimer] (executor-thread-1) execute Tue Apr 27 14:29:17 CEST 2021 => 17
2021-04-27 14:29:34,004 INFO  [org.acm.get.sta.MyTimer] (executor-thread-1) execute Tue Apr 27 14:29:17 CEST 2021 => 18
2021-04-27 14:29:35,004 INFO  [org.acm.get.sta.MyTimer] (executor-thread-1) execute Tue Apr 27 14:29:17 CEST 2021 => 19
2021-04-27 14:29:36,005 INFO  [org.acm.get.sta.MyTimer] (executor-thread-1) execute Tue Apr 27 14:29:17 CEST 2021 => 20
2021-04-27 14:29:37,000 INFO  [org.acm.get.sta.MyTimer] (executor-thread-198) execute Tue Apr 27 14:29:17 CEST 2021 => 21
2021-04-27 14:29:38,000 INFO  [org.acm.get.sta.MyTimer] (executor-thread-198) execute Tue Apr 27 14:29:17 CEST 2021 => 22
2021-04-27 14:29:39,001 INFO  [org.acm.get.sta.MyTimer] (executor-thread-198) execute Tue Apr 27 14:29:17 CEST 2021 => 23
2021-04-27 14:29:40,001 INFO  [org.acm.get.sta.MyTimer] (executor-thread-198) execute Tue Apr 27 14:29:17 CEST 2021 => 24
2021-04-27 14:29:41,002 INFO  [org.acm.get.sta.MyTimer] (executor-thread-198) execute Tue Apr 27 14:29:17 CEST 2021 => 25
2021-04-27 14:29:42,002 INFO  [org.acm.get.sta.MyTimer] (executor-thread-198) execute Tue Apr 27 14:29:17 CEST 2021 => 26
2021-04-27 14:29:42,509 INFO  [io.qua.dep.dev.RuntimeUpdatesProcessor] (vert.x-worker-thread-10) File change detected: E:\tmp\quarkus\test_timer\getting-started\src\main\resources\application.properties
2021-04-27 14:29:42,540 INFO  [io.quarkus] (Quarkus Main Thread) getting-started stopped in 0.027s
2021-04-27 14:29:43,003 INFO  [org.acm.get.sta.MyTimer] (executor-thread-198) execute Tue Apr 27 14:29:17 CEST 2021 => 27
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2021-04-27 14:29:43,859 INFO  [io.quarkus] (Quarkus Main Thread) getting-started 1.0.0-SNAPSHOT on JVM (powered by Quarkus 1.13.2.Final) started in 1.315s. Listening on: http://localhost:8081
2021-04-27 14:29:43,860 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2021-04-27 14:29:43,860 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, resteasy, scheduler]
2021-04-27 14:29:43,865 INFO  [io.qua.dep.dev.RuntimeUpdatesProcessor] (vert.x-worker-thread-10) Hot replace total time: 1.366s
2021-04-27 14:29:44,002 INFO  [org.acm.get.sta.MyTimer] (executor-thread-1) execute Tue Apr 27 14:29:44 CEST 2021 => 1
2021-04-27 14:29:44,004 INFO  [org.acm.get.sta.MyTimer] (executor-thread-198) execute Tue Apr 27 14:29:17 CEST 2021 => 28
2021-04-27 14:29:45,010 INFO  [org.acm.get.sta.MyTimer] (executor-thread-1) execute Tue Apr 27 14:29:44 CEST 2021 => 2
2021-04-27 14:29:45,011 INFO  [org.acm.get.sta.MyTimer] (executor-thread-198) execute Tue Apr 27 14:29:17 CEST 2021 => 29
2021-04-27 14:29:46,010 INFO  [org.acm.get.sta.MyTimer] (executor-thread-1) execute Tue Apr 27 14:29:44 CEST 2021 => 3
2021-04-27 14:29:46,011 INFO  [org.acm.get.sta.MyTimer] (executor-thread-198) execute Tue Apr 27 14:29:17 CEST 2021 => 30
2021-04-27 14:29:47,011 INFO  [org.acm.get.sta.MyTimer] (executor-thread-1) execute Tue Apr 27 14:29:44 CEST 2021 => 4
2021-04-27 14:29:47,012 ERROR [io.qua.sch.run.SimpleScheduler] (executor-thread-198) Error occured while executing task for trigger IntervalTrigger [id=1_org.acme.getting.started.MyTimer_ScheduledInvoker_run_72e66771a77415a7284d3ae42331659c186071de, interval=10000]:
 javax.enterprise.context.ContextNotActiveException
        at io.quarkus.arc.impl.ClientProxies.getDelegate(ClientProxies.java:40)
        at io.quarkus.arc.runtime.devconsole.InvocationTree_ClientProxy.arc$delegate(InvocationTree_ClientProxy.zig:42)
        at io.quarkus.arc.runtime.devconsole.InvocationTree_ClientProxy.invocationCompleted(InvocationTree_ClientProxy.zig:128)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:74)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(InvocationInterceptor_Bean.zig:521)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
        at org.acme.getting.started.MyTimer_Subclass.run(MyTimer_Subclass.zig:147)
        at org.acme.getting.started.MyTimer_ClientProxy.run(MyTimer_ClientProxy.zig:126)
        at org.acme.getting.started.MyTimer_ScheduledInvoker_run_72e66771a77415a7284d3ae42331659c186071de.invokeBean(MyTimer_ScheduledInvoker_run_72e66771a77415a7284d3ae42331659c186071de.zig:46)
        at io.quarkus.arc.runtime.BeanInvoker.invoke(BeanInvoker.java:20)
        at io.quarkus.scheduler.runtime.SimpleScheduler$ScheduledTask$1.run(SimpleScheduler.java:204)
        at io.quarkus.runtime.CleanableExecutor$CleaningRunnable.run(CleanableExecutor.java:231)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

Note that this behavior is less visible, but happens also in production mode: in [Graceful shutdown](https://quarkus.io/guides/lifecycle#graceful-shutdown), we should also wait for the termination of tasks that are in progress.

I think here is the relevant [code](https://github.com/quarkusio/quarkus/blob/main/extensions/scheduler/runtime/src/main/java/io/quarkus/scheduler/runtime/SimpleScheduler.java#L117).

### Expected behavior
Stopping the timer, awaiting termination, then restart the application.

### Actual behavior
Old timers keep running until they finish up normally.
If we do not await termination, another option would be to interrupt the threads.

## To Reproduce

Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific).
Execute the above code in a [scheduler](https://quarkus.io/guides/scheduler) application

### Configuration
```properties
# Add your application.properties here, if applicable.

```

### Screenshots
(If applicable, add screenshots to help explain your problem.)

### Quarkus version or git rev
 Quarkus 1.13.2.Final

## Additional context
(Add any other context about the problem here.)

### PR DESCRIPTION
**Pull request by mkouba**
This PR attempts to fix two problems described in https://github.com/quarkusio/quarkus/issues/16833#issuecomment-1917042589. Both are related to the Vertx worker thread pool implementation.

### NoopShutdownExecutorService
In prod mode, we wrap the `ExecutorService` and the `shutdown()` and `shutdownNow()` methods are deliberately not delegated. This is a workaround to solve the problem described in https://github.com/quarkusio/quarkus/issues/16833#issuecomment-1917042589. The problem: the Vertx instance is closed before `io.quarkus.runtime.ExecutorRecorder.createShutdownTask()` is used and when it's closed the underlying worker thread pool (which is in the prod mode backed by the `ExecutorBuildItem`) is closed as well. As a result the `quarkus.thread-pool.shutdown-interrupt` config property and logic defined in `ExecutorRecorder.createShutdownTask()` is completely ignored.

### DevModeExecutorService
In dev mode we use a special executor for the worker pool where the underlying executor can be shut down and then replaced with a new re-initialized executor. This is a workaround to solve the problem described in https://github.com/quarkusio/quarkus/issues/16833#issuecomment-1917042589. The problem: the Vertx instance is reused between restarts but we must attempt to shut down this executor, for example to cancel/interrupt the scheduled methods.

Fixes https://github.com/quarkusio/quarkus/issues/16833

### CODE REVIEW

File: extensions/vertx/runtime/src/main/java/io/quarkus/vertx/core/runtime/QuarkusExecutorFactory.java [hunk 1]
```diff
@@ -28,20 +30,51 @@ public QuarkusExecutorFactory(VertxConfiguration conf, LaunchMode launchMode) {
 
     @Override
     public ExecutorService createExecutor(ThreadFactory threadFactory, Integer concurrency, Integer maxConcurrency) {
+        // The current Vertx impl creates two external executors during initialization
+        // The first one is used for the worker thread pool, the second one is used internally,
+        // and additional executors may be created on demand
+        // Unfortunately, there is no way to distinguish the particular executor types
+        // Therefore, we only consider the first one as the worker thread pool
```
Comment (mkouba) [inline extensions/vertx/runtime/src/main/java/io/quarkus/vertx/core/runtime/QuarkusExecutorFactory.java:37]: This is IMO quite risky but the Vertx API does not provide a way to distinguish the particular executor types... :shrug:

Comment (cescoffier) [reply extensions/vertx/runtime/src/main/java/io/quarkus/vertx/core/runtime/QuarkusExecutorFactory.java:37]: The internal one is for file system operations only.

Comment (cescoffier) [reply extensions/vertx/runtime/src/main/java/io/quarkus/vertx/core/runtime/QuarkusExecutorFactory.java:37]: ok, I think it was already broken... 

We could change the Vert.x SPI to get the "type" (worker, internal, custom)

**Review by cescoffier — APPROVED** [review]

File: extensions/vertx/runtime/src/main/java/io/quarkus/vertx/core/runtime/QuarkusExecutorFactory.java (hunk 1 above)
Comment (mkouba) [reply extensions/vertx/runtime/src/main/java/io/quarkus/vertx/core/runtime/QuarkusExecutorFactory.java:37]: > We could change the Vert.x SPI to get the "type" (worker, internal, custom)

Yes, that would be helpful.

CC @jponge

File: extensions/vertx/runtime/src/main/java/io/quarkus/vertx/core/runtime/DevModeExecutorService.java [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+class DevModeExecutorService extends ForwardingExecutorService {
+
+    private static final Logger LOG = Logger.getLogger(DevModeExecutorService.class);
+
+    private final Supplier<ExecutorService> initializer;
+    private volatile ExecutorService executor;
+
+    DevModeExecutorService(Supplier<ExecutorService> initializer) {
+        this.initializer = initializer;
+        this.executor = initializer.get();
```
Comment (gastaldi) [inline extensions/vertx/runtime/src/main/java/io/quarkus/vertx/core/runtime/DevModeExecutorService.java:22]: It would be nice to add an `Objects.requireNonNull()` here for safety check purposes

Comment (mkouba) [reply extensions/vertx/runtime/src/main/java/io/quarkus/vertx/core/runtime/DevModeExecutorService.java:22]: It's a package-private class so I slacked off a bit :D

File: extensions/vertx/runtime/src/main/java/io/quarkus/vertx/core/runtime/ForwardingExecutorService.java [hunk 3]
```diff
@@ -0,0 +1,83 @@
...
+import java.util.Collection;
+import java.util.List;
+import java.util.concurrent.Callable;
+import java.util.concurrent.ExecutionException;
+import java.util.concurrent.ExecutorService;
+import java.util.concurrent.Future;
+import java.util.concurrent.TimeUnit;
+import java.util.concurrent.TimeoutException;
+
+abstract class ForwardingExecutorService implements ExecutorService {
```
[the remark this answers is not in the document]
Comment (mkouba) [reply extensions/vertx/runtime/src/main/java/io/quarkus/vertx/core/runtime/ForwardingExecutorService.java:12]: Hm, we cannot reuse it as is (many methods are not delegated and the delegate is stored in a private final field) but maybe we could move the `ForwardingExecutorService` to the core and reuse it from this `DelegatingExecutorService`...

**Review by gastaldi — APPROVED** [review]
LGTM, good job!
