### PR TITLE
Fix gRPC Server port configuration in kubernetes descriptor

### LINKED ISSUE #13416: gRPC port not well configured in kubernetes.yml
**Describe the bug**
The gRPC port defined in the application.properties is not reported in the kubernetes.yml generated. It’s only the default one that is used (9000)

**Expected behavior**
The specific gRPC port defined in the application.properties is used to defined service and container ports in the kubernetes.yml generated.

**Actual behavior**
The default gRPC port (9000) is defined in the kubernetes.yml for the service and the container port 

Kubernetes. yml generated : 
```properties
---
apiVersion: v1
kind: Service
....
spec:
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  - name: grpc-server
    port: 9000
    targetPort: 9000
...
spec:
....
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        - containerPort: 9000
          name: grpc-server
          protocol: TCP
```

**To Reproduce**

https://github.com/elamotte7/mk8s-quarkus-ac/tree/main/grpc-server-k8s

1. ./mvnw clean install -Dquarkus.profile=microk8s
2. Look at /target/kubernetes/kubernetes.yml  

**Configuration**
```properties
quarkus.http.port=3000

## gRPC server
quarkus.grpc.server.port=3001
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
Darwin linux-d02699e69504.home 20.1.0 Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64 x86_64
 - Output of `java -version`: 
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.4+11, mixed mode)
 - GraalVM version (if different from Java): 
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment GraalVM CE 20.2.0 (build 11.0.8+10-jvmci-20.2-b03)
OpenJDK 64-Bit Server VM GraalVM CE 20.2.0 (build 11.0.8+10-jvmci-20.2-b03, mixed mode, sharing)
 - Quarkus version or git rev: 
1.9.2.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /Users/coloneld/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3
Java version: 11.0.4, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home
Default locale: fr_FR, platform encoding: UTF-8
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"

Thanks for your help

### PR DESCRIPTION
**Pull request by cescoffier**
Fix the name of the property to retrieve the gRPC server port when computing the Kubernetes descriptor.

Fixes #13416.

### CODE REVIEW

**Review by geoand — APPROVED** [review]

File: extensions/grpc/deployment/src/main/java/io/quarkus/grpc/deployment/GrpcServerProcessor.java [hunk 1]
```diff
@@ -64,7 +64,7 @@ void discoverBindableServices(BuildProducer<BindableServiceBuildItem> bindables,
     @BuildStep(onlyIf = IsNormal.class)
     public KubernetesPortBuildItem registerGrpcServiceInKubernetes(List<BindableServiceBuildItem> bindables) {
         if (!bindables.isEmpty()) {
-            int port = ConfigProvider.getConfig().getOptionalValue("quarkus.grpc-server.port", Integer.class)
+            int port = ConfigProvider.getConfig().getOptionalValue("quarkus.grpc.server.port", Integer.class)
```
Comment (gsmet) [inline extensions/grpc/deployment/src/main/java/io/quarkus/grpc/deployment/GrpcServerProcessor.java:67]: We are in a build step. Why don't we inject the configuration object to avoid this sort of issues?

**Review by gsmet — DISMISSED** [review]

File: extensions/grpc/deployment/src/main/java/io/quarkus/grpc/deployment/GrpcServerProcessor.java (hunk 1 above)
Comment (cescoffier) [reply extensions/grpc/deployment/src/main/java/io/quarkus/grpc/deployment/GrpcServerProcessor.java:67]: Because that creates a cycle. Vert.x HTTP does the same for the HTTP port.

If we use the configuration, the augmentation fails with:
```
Caused by: java.lang.IllegalArgumentException: Run time configuration cannot be consumed here unless the method is a @Recorder at io.quarkus.grpc.runtime.config.GrpcConfiguration conf of public io.quarkus.kubernetes.spi.KubernetesPortBuildItem io.quarkus.grpc.deployment.GrpcServerProcessor.registerGrpcServiceInKubernetes(java.util.List,io.quarkus.grpc.runtime.config.GrpcConfiguration) of class io.quarkus.grpc.deployment.GrpcServerProcessor
```

Comment (gsmet) [reply extensions/grpc/deployment/src/main/java/io/quarkus/grpc/deployment/GrpcServerProcessor.java:67]: Ah yes, forgot about this issue: we are consuming runtime configuration at build time. I withdraw my comment.

**Comment by gsmet** [comment]
Rebased to fix CI.

**Review by michalszynkiewicz — APPROVED** [review]

**Review by gsmet — APPROVED** [review]
