### PR TITLE
Fix rendering of documentation tooltip when enum description contains paragraphs

### LINKED ISSUE #36401: Tooltips for enum values are rendered incorrectly in documentation of configuration properties
### Describe the bug

See for example https://quarkus.io/guides/scheduler#scheduler-configuration-reference

### Expected behavior

All enum values should be rendered correctly.

### Actual behavior

Only the first enum value is rendered correctly, the other ones seem off:

image

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by michalvavrik**
fixes: #36401
supersedes: #36769

### CODE REVIEW

File: core/processor/src/main/java/io/quarkus/annotation/processor/generate_doc/ConfigDocItemFinder.java [hunk 1]
```diff
@@ -494,7 +494,19 @@ private List<String> extractEnumValues(TypeMirror realTypeMirror, boolean useHyp
...
+                        String stripped = rawJavaDoc.replaceAll("<p>", Constants.EMPTY);
+                        if (stripped.contains("</p>")) {
+                            stripped = stripped.replaceAll("</p>", Constants.EMPTY);
+                        }
+                        javaDoc = enumJavaDocParser.parseConfigDescription(stripped);
+                    } else {
+                        javaDoc = enumJavaDocParser.parseConfigDescription(rawJavaDoc);
+                    }
+
                     acceptedValues.add(String.format(Constants.TOOLTIP, enumValue, javaDoc));
```
Comment (gsmet) [inline core/processor/src/main/java/io/quarkus/annotation/processor/generate_doc/ConfigDocItemFinder.java:510]: I don't think it's worth overoptimizing things in this case. And also, I wouldn't use `replaceAll`.

```suggestion
                    acceptedValues.add(String.format(Constants.TOOLTIP, enumValue, javaDoc.replace("<p>", Constants.EMPTY).replace("</p>", Constants.EMPTY));
```
should do it?

**Review by gsmet — COMMENTED** [review]
Thanks for having a look at that, I added a comment inline.

File: core/processor/src/main/java/io/quarkus/annotation/processor/generate_doc/ConfigDocItemFinder.java (hunk 1 above)
Comment (michalvavrik) [reply core/processor/src/main/java/io/quarkus/annotation/processor/generate_doc/ConfigDocItemFinder.java:510]: > I don't think it's worth overoptimizing things in this case.

I'd say in 99 % there will be no replacing (and for example `SchedulerRuntimeConfig` does not contain `</p>`). Judging by implementation I use, the `contains` method should be better than `replace` because it doesn't recreate String.

> And also, I wouldn't use replaceAll.

I agree, `replaceAll` was my mistake.

Comment (michalvavrik) [reply core/processor/src/main/java/io/quarkus/annotation/processor/generate_doc/ConfigDocItemFinder.java:510]: I forgot to say I'll commit your suggestion (or you can do it).

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Thanks!
