### PR TITLE
Make substitution of JMX#createProxy conditional on inclusion of jmxserver feature

### LINKED ISSUE #46506: javax.management.JMX.createProxy is not implemented in native mode
### Describe the bug

In the Quarkus Core there is this substitution for `javax.management.JMX.createProxy`:

https://github.com/quarkusio/quarkus/blob/1ba5ca13b724079df3e63b6c14df212a4b5a5542/core/runtime/src/main/java/io/quarkus/runtime/graal/Target_javax_management_JMX.java

I wonder if this could be removed or be made conditional based on whether native JMX support is enabled?

Camel has a comprehensive JMX based management layer and there's a few code paths that trigger activation of `javax.management.JMX`. Which leads to runtime exceptions like this:

```
java.lang.IllegalStateException: Not Implemented in native mode
	at java.management@21.0.2/javax.management.JMX.createProxy(JMX.java:19)
	at java.management@21.0.2/javax.management.JMX.newMBeanProxy(JMX.java:216)
	at java.management@21.0.2/javax.management.MBeanServerInvocationHandler.newProxyInstance(MBeanServerInvocationHandler.java:240)
	at org.apache.camel.management.DefaultManagementAgent.newProxyClient(DefaultManagementAgent.java:396)
	at org.apache.camel.management.mbean.ManagedCamelContext.dumpRoutesStatsAsXml(ManagedCamelContext.java:646)
```

I tested with removing the substitution and my previously failing JMX operation invocations started working fine.

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Mandrel or GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by roberttoyonaga**
This is a fix for: https://github.com/quarkusio/quarkus/issues/46506

This change makes the substitution that prevents use of ` JMX#createProxy ` conditional. The substitution should only be enabled if the `jmxserver` feature is not included in the image build.

### CODE REVIEW

**Comment by roberttoyonaga** [comment]
Currently, the `BooleanSupplier` `JmxServerNotIncluded` always seems to evaluate to `true` because the `Class.forName` reflection checks always pass. I don't know why these checks always pass because the remote JMX specific reflection registrations should only happen if [`--enable-monitoring=jmxserver`](https://github.com/oracle/graal/blob/jdk-25%2B12/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/jdk/JmxServerFeature.java#L53) is used. Is it possible that Quarkus is registering these classes for reflection (however, I don't see that happening anywhere)? I've tried to follow the pattern of [other `BooleanSupplier`s](https://github.com/quarkusio/quarkus/blob/95c58a856c6461304d3be100aa056d5756a27a1d/extensions/undertow/runtime/src/main/java/io/quarkus/undertow/runtime/graal/VertxSubstitutions.java#L51) used by Quarkus. Another thing that I am confused about is that the `BooleanSupplier`s used in this pattern are evaluated at runtime, which means that `Class.forName` is evaluated by the host VM building the Quarkus app (which doesn't require reflection registration). @zakkak if you have time, can you please have a quick look to see if I've overlooked something? 

A better way to toggle this substitution would be to directly check whether the JMXSERVER feature is included in the build. However, that information doesn't seem accessible outside of NativeImageBuildStep.java.

**Comment by zakkak** [comment]
The reason this doesn't work is because you are setting the value at deployment time and then try to read it at native-image build time.

When compiling a Quarkus native application the following two phases/steps take place:

1. **Deployment**: at this step Quarkus generates application-specific bytecode to handle/optimize things and packages all necessary bits in a jar.
2. **Native-image compilation**: this happens right after the deployment phase is completed. The jar generated in step 1 is passed to GraalVM/Mandrel as the application to be compiled to native code.

Any code in `*.deployment.*` packages is only available during the deployment phase. The addition you made in [NativeImageBuildStep.java](https://github.com/quarkusio/quarkus/pull/46592/files#diff-bbea232d6b9141ad313658b2587f9ec7e23d90c93cd79994dd14086a769d52d0) will only run during the deployment phase so the value being set in [RemoteJmxHelper.java](https://github.com/quarkusio/quarkus/pull/46592/files#diff-e21a7f276d86390d566026b37d09c97e3cd698523820d3de6f13bb6e7111b63b) will only be available during the deployment phase, but GraalVM/Mandrel performs the substitutions at native-image compilation time, at which point it will be running in a different JVM process and thus accessing a different `RemoteJmxHelper` instance.

The best way IMHO would be to see if jmx-server is included in `com.oracle.svm.core.VMInspectionOptions#EnableMonitoringFeatures`, but unfortunately it's not available in the public API.

The simplest way I can think of is to use a property, e.g. `quarkus.native.jmxserver.included` which `NativeImageBuildStep.java` will set accordingly and `RemoteJmxHelper` will read.

**Comment by roberttoyonaga** [comment]
Thank you @zakkak for the detailed explanation! I hadn't realized there were two separate processes.  I'll give your suggestion a try.

File: core/runtime/src/main/java/io/quarkus/runtime/graal/Target_javax_management_JMX.java [hunk 1]
```diff
@@ -19,4 +21,12 @@ private static <T> T createProxy(MBeanServerConnection connection,
         throw new IllegalStateException("Not Implemented in native mode");
     }
 
+    static final class JmxServerNotIncluded implements BooleanSupplier {
+
+        @Override
+        public boolean getAsBoolean() {
+            String result = System.getProperty("quarkus.native.jmxserver.included");
+            return !"true".equals(result);
```
Comment (zakkak) [inline core/runtime/src/main/java/io/quarkus/runtime/graal/Target_javax_management_JMX.java:29]: You may also use [`Boolean.html#getBoolean(java.lang.String)`](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/Boolean.html#getBoolean(java.lang.String))

```suggestion
            return Boolean.getBoolean("quarkus.native.jmxserver.included");
```

**Review by zakkak — APPROVED** [review]
LGTM. Please squash the two commits and have a look at my suggestion.

Thanks for the contribution!

File: core/runtime/src/main/java/io/quarkus/runtime/graal/Target_javax_management_JMX.java (hunk 1 above)
Comment (roberttoyonaga) [reply core/runtime/src/main/java/io/quarkus/runtime/graal/Target_javax_management_JMX.java]: good idea! Done

**Review by zakkak — APPROVED** [review]
Thank you @roberttoyonaga !

**Comment by jamesnetherton** [comment]
@gsmet @zakkak  Is it possible to have this change backported for inclusion in the 3.20 LTS release?

**Comment by zakkak** [comment]
> @gsmet @zakkak Is it possible to have this change backported for inclusion in the 3.20 LTS release?

Yes it seems reasonable.

**Comment by zakkak** [comment]
@roberttoyonaga unfortunately this introduced the following warning:

```
00:53:09,694 WARN  [io.qua.config] Unrecognized configuration key "quarkus.native.jmxserver.included" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo 
```

We need to either use a different property, not under `quarkus.native.jmxserver` or have Quarkus aware of it.

cc @gsmet @geoand wdyt would be the best approach (thinking about consistency)?
