### PR TITLE
SmallRye OpenApi update to 2.1.17

### LINKED ISSUE #21173: OpenAPI: auto-add-tags feature uses superclass/interface name, rather than actual class name
### Describe the bug

Consider the following:

```java
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
public interface AbstractReadOnlyResource<T> {
    @GET
    @Path("/{id}")
    T getById(@PathParam("id") long id);
}
```

and

```java
@Path("/address")
public class AddressResource implements AbstractReadOnlyResource<Address> {
    @Override
    public Address getById(long id) {
        // Removed for brevity
    }
}
```

### Expected behavior

The `get` operation of the `/address/{id}` path  is tagged with `Address Resource`.

### Actual behavior

The resource is tagged with `Abstract Read Only Resource`.

OpenAPI JSON contains

```json
"paths" : {
  "/address/{id}" : {
    "get" : {
      "tags" : [ "Abstract Read Only Resource" ],
      "parameters" : [ {
        "name" : "id",
        "in" : "path",
        "required" : true,
        "schema" : {
          "format" : "int64",
          "type" : "integer"
        }
      } ],
    }
  }
}
```

 Swagger UI shows:

image

### How to Reproduce?

~Will add a link to a GitHub repo shortly.~

EDIT: A small reproducer project can be found [here](https://github.com/j-be/quarkus-21173).

### Output of `uname -a` or `ver`

Linux jbe-desktop 5.4.0-89-generic #100-Ubuntu SMP Fri Sep 24 14:50:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.11" 2021-04-20

### GraalVM version (if different from Java)

none

### Quarkus version or git rev

2.4.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.3 (ff8e977a158738155dc465c6a97ffaf31982d739)

### Additional information

_No response_

### LINKED ISSUE #21567: Extend openapi with support for `.json` and `.yaml` extension besides the current content negotiation mechanism
### Description

The  [swagger documentation](https://swagger.io/docs/open-source-tools/swagger-ui/usage/cors/) refers to a mechanism were `.json` and `.yaml` is used as extension on the openapi  / swagger URL .

Other standards like [this one](https://publicatie.centrumvoorstandaarden.nl/api/adr/#api-51), seem to extend upon that. 

See also discussion in: #21457

### Implementation ideas

Currently, I have implemented this as a `vertx.RouteFilter`. That does the trick. I've found this solution on other places, like this [one](https://itnext.io/how-to-mangle-http-headers-in-quarkus-d91a904adea7).  So I guess there's more demand for this feature.

```java
    @RouteFilter
    public void modifyAcceptHeader(RoutingContext rc) {
        String url = rc.normalizedPath();
        if ( url.endsWith( "openapi.json" ) ) {
            String acceptHeader = rc.request().headers().get( ACCEPT );
            if ( acceptHeader != null && !acceptHeader.contains( "yaml" ) ) {
                rc.request().headers().set( ACCEPT, "application/json" );
            }
            rc.reroute(  url.substring( 0, url.lastIndexOf( '.' ) ) );
            return;
        }
        else if ( url.endsWith( "openapi.yaml" ) ) {
            rc.reroute(  url.substring( 0, url.lastIndexOf( '.' ) ) );
            return;
        }
        rc.next();
    }

```

### LINKED ISSUE #22349: Smallrye OpenAPI Additional Docs Missing in Native Image
### Describe the bug

I require Quarkus to present different OpenAPI securitySchemes in different deployment environments.  I'm attempting to do this by using the `quarkus.smallrye-openapi.additional-docs-directory` and an environment variable (one of "qa" or "prod").  The securitySchemes are stored in subdirectories of META-INF/openapi and my application.yaml instructs the native executable builder to use these resources:
```yaml
quarkus:
  smallrye-openapi:
    auto-add-security: false
    additional-docs-directory: META-INF/openapi/${openapi-security:prod}
  native:
    builder-image:
      quay.io/quarkus/ubi-quarkus-native-image:21.3-java17
    resources:
      includes: "META-INF/openapi/**"
```
This works when running in the JVM (OpenJDK Runtime Environment 21.9 (build 17.0.1+12-LTS)), but not in the native executable.  I've created a [reproducible test](https://github.com/watermelonjam/openapi-docs-bug) of the behaviour.  I know the native resource includes are having some effect, running `strings` on the executable and grepping for tokenUrl shows me what I want to see.  quarkus-smallrye-openapi can't seem to load them though.

### Expected behavior

Native executable should produce an OpenAPI spec at /q/openapi that includes the securityScheme defined in META-INF/openapi/prod/security-scheme.yaml

### Actual behavior

Native executable produces no securitySchemes at all.

### How to Reproduce?

```shell
git clone https://github.com/watermelonjam/openapi-docs-bug.git
mvn clean verify -Pnative
```

### Output of `uname -a` or `ver`

Linux vpn-netw-90-232.ipreg.mcmaster.ca 4.18.0-348.2.1.el8_5.x86_64 #1 SMP Mon Nov 8 13:30:15 EST 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.1" 2021-10-19 LTS OpenJDK Runtime Environment 21.9 (build 17.0.1+12-LTS) OpenJDK 64-Bit Server VM 21.9 (build 17.0.1+12-LTS, mixed mode, sharing)

### GraalVM version (if different from Java)

quay.io/quarkus/ubi-quarkus-native-image:21.3-java17

### Quarkus version or git rev

2.5.2-Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven home: /home/arnoldd/apache-maven-3.8.3 Java version: 17.0.1, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-17-openjdk-17.0.1.0.12-2.el8_5.x86_64 Default locale: en_US, platform encoding: UTF-8 OS name: "linux", version: "4.18.0-348.2.1.el8_5.x86_64", arch: "amd64", family: "unix"

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by phillip-kruger**
- Fix #21173 - Auto Tag fix for interfaces
- Fix #21567 - Content negotiation with file extension
- Fix #22349 - Make sure the additional static docs is also included in native (do not use class loader)
- Add nonce parameter for OIDC connection in Swagger UI
- Upgrade to 2.1.17: https://github.com/smallrye/smallrye-open-api/releases/tag/2.1.17

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Comment by geoand** [comment]
Does it make sense to backport this? Is it safe enough?

File: extensions/swagger-ui/deployment/src/main/java/io/quarkus/swaggerui/deployment/SwaggerUiProcessor.java [hunk 1]
```diff
@@ -377,10 +385,27 @@ public void registerSwaggerUiHandler(SwaggerUiRecorder recorder,
...
+        Map<String, String> oauthAdditionalQueryStringParamMap = new HashMap<>();
         if (swaggerUiConfig.oauthAdditionalQueryStringParams.isPresent()) {
             String oauthAdditionalQueryStringParams = swaggerUiConfig.oauthAdditionalQueryStringParams.get();
-            options.put(Option.oauthAdditionalQueryStringParams, oauthAdditionalQueryStringParams);
+            Map<String, String> map = objectMapper.readValue(oauthAdditionalQueryStringParams, Map.class);
+            if (map == null || map.isEmpty()) {
+                LOG.warn(
+                        "Property 'quarkus.swagger-ui.oauth-additional-query-string-params' should be a map, example: quarkus.swagger-ui.oauth-additional-query-string-params='{\"foo\": \"bar\"}' ");
+            } else {
+                oauthAdditionalQueryStringParamMap.putAll(map);
```
Comment (gsmet) [inline extensions/swagger-ui/deployment/src/main/java/io/quarkus/swaggerui/deployment/SwaggerUiProcessor.java:398]: Why don't we make it a Map in the config instead of using JSON?

**Review by gsmet — CHANGES_REQUESTED** [review]
I would like for @phillip-kruger to clarify one thing before merging.

File: extensions/swagger-ui/deployment/src/main/java/io/quarkus/swaggerui/deployment/SwaggerUiProcessor.java (hunk 1 above)
Comment (phillip-kruger) [reply extensions/swagger-ui/deployment/src/main/java/io/quarkus/swaggerui/deployment/SwaggerUiProcessor.java:398]: Hi @gsmet , yes I thought about that, but that is a breaking change, so I decided to go with this. We can always deprecate this config and add one that has the map, so that older config still works. W.d.y.t?

Comment (gsmet) [reply extensions/swagger-ui/deployment/src/main/java/io/quarkus/swaggerui/deployment/SwaggerUiProcessor.java:398]: As long as it breaks cleanly (e.g. with an error message), I'd say we should fix the format and add a note to the migration guide.

But better do it in a separate PR anyway.

**Review by gsmet — APPROVED** [review]
