### PR TITLE
Fix OpenTelemetry Metrics and Logs endpoint resolution

### LINKED ISSUE #46351: Otel logging does not respond to it's config property.
### Describe the bug

Related to https://github.com/quarkusio/quarkus/pull/38239 and docs https://quarkus.io/version/main/guides/opentelemetry-logging
Testing with quarkus main snapshot

According to docs, collector endpoint should be configured by property `quarkus.otel.exporter.otlp.logs.endpoint`. But extension does not react to this property. Instead it actually is configured by "quarkus.otel.exporter.otlp.**traces**.endpoint".

In my setup I changed the grafana-otel-lgtm service to use different port than default 4317. Even when I configure it to the `quarkus.otel.exporter.otlp.logs.endpoint=http://localhost:32791` no logs arrive to the backend and app complains about not being able to connect to the port 4317:
```
Failed to export TraceRequestMarshalers. The request could not be executed. Full error message: Connection refused: localhost/127.0.0.1:4317
Failed to export LogsRequestMarshalers. The request could not be executed. Full error message: Connection refused: localhost/127.0.0.1:4317
```

Problems with both logs and traces export is fixed, when I configure quarkus.otel.exporter.otlp.**traces**.endpoint.

From my testing it seems like property `quarkus.otel.exporter.otlp.logs.endpoint` is ignored entirely. Even when I set it to complete bogus like `quarkus.otel.exporter.otlp.logs.endpoint=http://wtfWhatisThis:456123748` it works, as long as *traces* property is set correctly.

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

999-SNAPSHOT

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by gsmet**
Fixes #46351

@brunobat I'm not entirely sure if we can easily add tests for it?

### CODE REVIEW

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/exporter/otlp/OTelExporterRecorder.java [hunk 1]
```diff
@@ -262,7 +262,7 @@ public MetricExporter apply(SyntheticCreationalContext<MetricExporter> context)
 
     public Function<SyntheticCreationalContext<LogRecordExporter>, LogRecordExporter> createLogRecordExporter(
             OTelRuntimeConfig otelRuntimeConfig, OtlpExporterRuntimeConfig exporterRuntimeConfig, Supplier<Vertx> vertx) {
-        final URI baseUri = getMetricsUri(exporterRuntimeConfig);
+        final URI baseUri = getLogsUri(exporterRuntimeConfig);
```
Comment (gsmet) [inline extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/exporter/otlp/OTelExporterRecorder.java:265]: The Logs endpoint was incorrect but it wasn't the only one.

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/exporter/otlp/OTelExporterRecorder.java [hunk 2]
```diff
@@ -398,7 +398,15 @@ private URI getTracesUri(OtlpExporterRuntimeConfig exporterRuntimeConfig) {
     }
 
     private URI getMetricsUri(OtlpExporterRuntimeConfig exporterRuntimeConfig) {
-        String endpoint = resolveTraceEndpoint(exporterRuntimeConfig);
+        String endpoint = resolveMetricEndpoint(exporterRuntimeConfig);
```
Comment (gsmet) [inline extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/exporter/otlp/OTelExporterRecorder.java:401]: The Metrics one was also using the Trace one instead.

**Comment by brunobat** [comment]
Let me have a look

**Comment by brunobat** [comment]
Looks like I implemented the metrics endpoint resolver, created unit tests for it and forgot to actually use it.🙄 
The Logs one is just a copy/paste error. 
Manually testing this for now.

**Review by brunobat — APPROVED** [review]
Manually tested.
Tried Wiremock but got nowhere as the payloads are protobuf and Wiremock doesn't seem to detect the calls. 
The IT test setup is complex with test containers but will give it a try in the future. I think we can  merge this for now.

**Review by geoand — APPROVED** [review]
