### PR TITLE
Arc - mention that decorating built-in types is not supported; log a warning if we detect such case

### LINKED ISSUE #23713: ArC: Decorator for built-In Bean Event<T> broken
### Describe the bug

It seems that with 2.7.1.Final it is no longer possible to decorate the built-in bean `Event<T>`. This was still possible in October, with version 2.2.3.Final.

### Expected behavior

The built-in bean `Event<T>` should be decorate-able as per the [CDI Spec](https://jakarta.ee/specifications/cdi/2.0/cdi-spec-2.0.html#decorators)

> Decorators may be associated with any managed bean that is not itself an interceptor or decorator, or with any built-in bean other than the built-in bean with type `BeanManager` and qualifier `@Default`.

### Actual behavior

The decorator is picked up by Quarkus, because if I remove the `@Priority`, then the log-message
`INFO: The decorator com.example.EventDecorator does not declare any @Priority. It will be assigned a default priority value of 0.`
appears. But it is not applied to the bean, because the test fails.

### How to Reproduce?

Define two classes like so:
```
@Decorator
@Priority(Interceptor.Priority.APPLICATION)
public abstract class EventDecorator<T> implements Event<T>, Serializable {

    @Inject
    @Delegate
    @Any
    Event<T> delegate;

    @Inject
    EventCollector eventCollector;

    @Override
    public void fire(final T event) {
        eventCollector.collect(event);
        delegate.fire(event);
    }
}
```
and
```

@ApplicationScoped
public class EventCollector {

    List<Object> firedEvents = new ArrayList<>();

    public List<Object> getFiredEvents() {
        return firedEvents;
    }

    public <T> void collect(final T event) {
        firedEvents.add(event);
    }
}
```
And run the following Test:
```

@QuarkusTest
class EventDecoratorTest {

    @Inject
    EventCollector eventCollector;

    @Inject
    Event<Integer> event;

    @Test
    void testDecorator(){
        event.fire(42);

        assertThat(eventCollector.getFiredEvents()).contains(42);
    }
}
```

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

11.0.11, vendor: AdoptOpenJDK, runtime: C:\Program Files\AdoptOpenJDK\jdk-11.0.11.9-hotspot

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.7.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by manovotn**
Note that in this PR I choose to skip the creation of decorator component with this delegate injection point type.
Instead, we could throw an error.

I tried this with a test but didn't include it here since it is just a log message.

Fixes #23713

### CODE REVIEW

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Decorators.java [hunk 1]
```diff
@@ -17,6 +18,8 @@
 
     static final Logger LOGGER = Logger.getLogger(Decorators.class);
 
+    private static final Set<DotName> builtInBeanTypes = Set.of(DotNames.BEAN_MANAGER, DotNames.INSTANCE, DotNames.EVENT);
```
Comment (JHahnHRO) [inline independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Decorators.java:21]: What about other built-in beans like `Bean<T>`, `@Intercepted Bean<?>`, `@Decorated Bean<?>`, `Interceptor<T>`, `Decorator<T>`,  `InjectionPoint`,  `RequestContextController`, `InterceptionFactory` ? (Maybe more, these are just the ones I remember off the top of my head)

Comment (manovotn) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Decorators.java:21]: I am well aware of them and I was planning to discuss this with @mkouba once he gets back from PTO.
I only added these three since they are "most common" candidates for this scenario. I am not sure the other built in beans would make much sense with decorators.

File: docs/src/main/asciidoc/cdi-reference.adoc [hunk 2]
```diff
@@ -214,6 +214,7 @@ public class CounterBean {
 * Passivation and passivating scopes are not supported
 * Interceptor methods on superclasses are not implemented yet
 * `@Interceptors` is not supported
+* Decoration of built-in beans, such as `Event`, is not implemented yet
```
Comment (mkouba) [inline docs/src/main/asciidoc/cdi-reference.adoc:217]: I'd rather replace _"is not implemented yet"_ with _"is not supported"._ The current wording implies that it will be supported in the future and that does not have to be the case.

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Decorators.java [hunk 3]
```diff
@@ -80,6 +83,14 @@ static DecoratorInfo createDecorator(ClassInfo decoratorClass, BeanDeployment be
                 throw new DefinitionException("The delegate type " + delegateInjectionPoint.getRequiredType()
                         + " does not implement the decorated type: " + decoratedType);
             }
+            for (DotName builtInBeanName : builtInBeanTypes) {
+                if (builtInBeanName.equals(decoratedType.name())) {
+                    LOGGER.warn("Decorating built-in bean types is not supported! Decorator " + decoratorClass +
```
Comment (mkouba) [inline independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Decorators.java:88]: Hm, I think that we should fail the build instead of a warning...

Comment (manovotn) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Decorators.java:88]: As per my initial comment, this is perfectly fine with me. I'll adjust the PR :)

File: docs/src/main/asciidoc/cdi-reference.adoc (hunk 2 above)
Comment (manovotn) [reply docs/src/main/asciidoc/cdi-reference.adoc:217]: Ok, will change the wording.

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Decorators.java (hunk 1 above)
Comment (manovotn) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Decorators.java:21]: @mkouba do you think we should make an exhaustive list of all built-in beans or keep it as is?
Personally, I don't see anyone trying to decorate anything else than BM, event and instance but I might be wrong.

**Comment by manovotn** [comment]
Rebased onto main and changed as per comments. The PR now throws UOE instead of just logging a warning.

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Decorators.java (hunk 1 above)
Comment (mkouba) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Decorators.java:21]: > do you think we should make an exhaustive list of all built-in beans or keep it as is?

I think that we could just reuse the `io.quarkus.arc.processor.BuiltinBean` enum and `BuiltinBean.getRawTypeDotNames()` but exclude the `BuiltinBean.RESOURCE`.

**Comment by manovotn** [comment]
Updated to make use of the `BuiltInBean` enum and added automated test for failure.

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Decorators.java [hunk 4]
```diff
@@ -80,6 +80,16 @@ static DecoratorInfo createDecorator(ClassInfo decoratorClass, BeanDeployment be
                 throw new DefinitionException("The delegate type " + delegateInjectionPoint.getRequiredType()
                         + " does not implement the decorated type: " + decoratedType);
             }
+            for (BuiltinBean bean : BuiltinBean.values()) {
+                if (bean.equals(BuiltinBean.RESOURCE)) {
+                    // do not take Resource into consideration
+                    continue;
+                }
+                if (bean.hasRawTypeDotName(decoratedType.name())) {
+                    throw new UnsupportedOperationException("Decorating built-in bean types is not supported! " +
```
Comment (mkouba) [inline independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Decorators.java:89]: Just out of curiosity why `UnsupportedOperationException`? I would expect ISE or something like that... Although any RuntimeException is OK.

**Review by mkouba — APPROVED** [review]

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Decorators.java (hunk 4 above)
Comment (manovotn) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Decorators.java:89]: My line of thought was that this is technically possible but we just don't support it. But I am fine with any exception really.

**Comment by mkouba** [comment]
`RegistrySnapshotCatalogCompatibilityTest.testRegistrySnapshotPlatformCatalog()` is very likely not related - failed in other recent PRs as well...
