### PR TITLE
Fix gradle devui NoClassDefFound

### LINKED ISSUE #45112: Exception about missing maven classes when opening the dev-ui (gradle based project)
### Describe the bug

When you generate the most simple quarkus app using Gradle:
https://code.quarkus.io/?b=GRADLE

Start it in dev mode with `./gradlew quarkusDev`

Open the dev ui http://localhost:8080/q/dev-ui/

### Expected behavior

No Exception, everything is working

### Actual behavior

I got different errors about missing Maven classes:

```
2024-12-13 10:05:26,851 ERROR [io.qua.dev.run.jso.JsonRpcCodec] (ForkJoinPool.commonPool-worker-9) Error in JsonRPC Call: java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: org/apache/maven/settings/building/SettingsBuildingException
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: java.lang.NoClassDefFoundError: org/apache/maven/settings/building/SettingsBuildingException
        at io.quarkus.bootstrap.resolver.maven.MavenArtifactResolver.<init>(MavenArtifactResolver.java:90)
        at io.quarkus.bootstrap.resolver.maven.MavenArtifactResolver$Builder.build(MavenArtifactResolver.java:74)
        at io.quarkus.devtools.project.buildfile.MavenProjectBuildFile.getMavenResolver(MavenProjectBuildFile.java:151)
        at io.quarkus.devtools.project.buildfile.MavenProjectBuildFile.getProject(MavenProjectBuildFile.java:54)
        at io.quarkus.devtools.project.QuarkusProjectHelper.getCachedProject(QuarkusProjectHelper.java:59)
        at io.quarkus.devui.deployment.menu.ExtensionsProcessor.getQuarkusProject(ExtensionsProcessor.java:202)
        at io.quarkus.devui.deployment.menu.ExtensionsProcessor.lambda$getInstalledNamespaces$4(ExtensionsProcessor.java:124)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
        ... 6 more
Caused by: java.lang.ClassNotFoundException: org.apache.maven.settings.building.SettingsBuildingException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        ... 14 more
```

Or:

```
2024-12-13 09:18:42,853 ERROR [io.qua.dev.run.jso.JsonRpcCodec] (ForkJoinPool.commonPool-worker-15) Error in JsonRPC Call: java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: org/apache/maven/model/profile/activation/ProfileActivator
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: java.lang.NoClassDefFoundError: org/apache/maven/model/profile/activation/ProfileActivator
        at io.quarkus.bootstrap.resolver.maven.MavenArtifactResolver.<init>(MavenArtifactResolver.java:90)
        at io.quarkus.bootstrap.resolver.maven.MavenArtifactResolver$Builder.build(MavenArtifactResolver.java:74)
        at io.quarkus.devtools.project.buildfile.MavenProjectBuildFile.getMavenResolver(MavenProjectBuildFile.java:151)
        at io.quarkus.devtools.project.buildfile.MavenProjectBuildFile.getProject(MavenProjectBuildFile.java:54)
        at io.quarkus.devtools.project.QuarkusProjectHelper.getCachedProject(QuarkusProjectHelper.java:59)
        at io.quarkus.devui.deployment.menu.ExtensionsProcessor.getQuarkusProject(ExtensionsProcessor.java:202)
        at io.quarkus.devui.deployment.menu.ExtensionsProcessor.lambda$getInstalledNamespaces$4(ExtensionsProcessor.java:124)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
        ... 6 more
Caused by: java.lang.ClassNotFoundException: org.apache.maven.model.profile.activation.ProfileActivator
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        ... 14 more
```

Screenshot of the dev ui:

Image

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

3.17.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Malandril**
This PR fixes #45112.
It fixes the devui NoClassDefFound errors triggered when using the gradle build tool in dev mode and disables the Add extension button.

When #43840 was merged it allowed to dynamically add new extensions using the dev ui but it doesn't work nicelly with gradle projects:

1. It did'nt correctly identify the path of the project with gradle as the current working dir in gradle retrieved here https://github.com/quarkusio/quarkus/blob/43c95ab7714af941a82299dfb4ff903d61b5b5c0/extensions/vertx-http/deployment/src/main/java/io/quarkus/devui/deployment/menu/ExtensionsProcessor.java#L201 will be in the `build/classes/java/main` directory and not the project directory and as such will always detect a gradle project as being a maven project
2. In the gradle dev mode task we only explicitly add parentFirstDependencies and as such the maven resolver dependencies are absent from the classpath https://github.com/quarkusio/quarkus/blob/43c95ab7714af941a82299dfb4ff903d61b5b5c0/devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/QuarkusDev.java#L498
3. One all the above is resolved, the `io.quarkus.devtools.project.buildfile.GenericGradleBuildFile` extensionManager cannot neither list nor add any new extension as it doesn't work outside of the gradle plugin.

### CODE REVIEW

File: devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/QuarkusDev.java [hunk 1]
```diff
@@ -465,11 +464,14 @@ private DevModeCommandLine newLauncher(final AnalyticsService analyticsService)
         builder.extensionDevModeConfig(appModel.getExtensionDevModeConfig())
                 .extensionDevModeJvmOptionFilter(extensionJvmOptions);
 
+        builder.jvmArgs("-Dgradle.project.path="
```
Comment (Malandril) [inline devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/QuarkusDev.java:467]: The only way I found to findthe correct gradle project path independent of build language or sourceSet name is to send it as a system property

File: devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/QuarkusDev.java [hunk 2]
```diff
@@ -465,11 +464,14 @@ private DevModeCommandLine newLauncher(final AnalyticsService analyticsService)
...
+                + getProject().getLayout().getProjectDirectory().getAsFile().getAbsolutePath());
+
         analyticsService.sendAnalytics(
                 DEV_MODE,
                 appModel,
                 Map.of(GRADLE_VERSION, getProject().getGradle().getGradleVersion()),
-                getProject().getBuildDir().getAbsoluteFile());
+                getProject().getLayout().getBuildDirectory().getAsFile().get());
```
Comment (Malandril) [inline devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/QuarkusDev.java:474]: `getBuildDir()` is deprecated

File: extensions/vertx-http/dev-ui-resources/src/main/resources/dev-ui/qwc/qwc-continuous-testing.js [hunk 3]
```diff
@@ -150,7 +150,9 @@ export class QwcContinuousTesting extends QwcHotReloadElement {
 
     _cancelObservers(){
         this._streamStateObserver.cancel();
-        this._streamResultsObserver.cancel();
+        if(this._streamResultsObserver){
```
Comment (Malandril) [inline extensions/vertx-http/dev-ui-resources/src/main/resources/dev-ui/qwc/qwc-continuous-testing.js:153]: Was undefined when switching tabs without running tests

File: extensions/vertx-http/dev-ui-resources/src/main/resources/dev-ui/qwc/qwc-extensions.js [hunk 4]
```diff
@@ -96,12 +97,20 @@ export class QwcExtensions extends observeState(LitElement) {
...
         this._selectedFilters = this._getStoredFilters();
+        this._addExtensionsEnabled = true;
     }
 
     connectedCallback() {
         super.connectedCallback();
         this.jsonRpc.getInstalledNamespaces().then(jsonRpcResponse => {
             this._installedExtensions = jsonRpcResponse.result;
+        }).catch(e => {
+            if (e?.error?.message?.includes("java.lang.IllegalStateException")){
```
Comment (Malandril) [inline extensions/vertx-http/dev-ui-resources/src/main/resources/dev-ui/qwc/qwc-extensions.js:108]: Kind of dirty but works

File: core/runtime/pom.xml [hunk 5]
```diff
@@ -184,9 +184,37 @@
...
+                        <parentFirstArtifact>org.apache.maven:maven-settings-builder</parentFirstArtifact>
+                        <parentFirstArtifact>org.apache.maven:maven-settings</parentFirstArtifact>
+                        <parentFirstArtifact>org.codehaus.plexus:plexus-cipher</parentFirstArtifact>
+                        <parentFirstArtifact>org.codehaus.plexus:plexus-interpolation</parentFirstArtifact>
+                        <parentFirstArtifact>org.codehaus.plexus:plexus-classworlds</parentFirstArtifact>
+                        <parentFirstArtifact>org.codehaus.plexus:plexus-sec-dispatcher</parentFirstArtifact>
                         <parentFirstArtifact>org.codehaus.plexus:plexus-utils</parentFirstArtifact>
+                        <parentFirstArtifact>org.codehaus.plexus:plexus-xml</parentFirstArtifact>
+                        <parentFirstArtifact>org.eclipse.sisu:org.eclipse.sisu.plexus</parentFirstArtifact>
+
```
Comment (Malandril) [inline core/runtime/pom.xml:217]: All of these are need to be added to the gradle devmode as gradle does not have all of these dependencies by defautl contrary to maven

Comment (Malandril) [reply core/runtime/pom.xml:217]: This actually breaks the elasticsearch rest tests i'll try to find another way

**Comment by aloubyansky** [comment]
@Malandril thanks a lot for looking into this. Perhaps try
```
diff --git a/devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/QuarkusDev.java b/devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/QuarkusDev.java
index 44457c4fc2..6558f19e77 100644
--- a/devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/QuarkusDev.java
+++ b/devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/QuarkusDev.java
@@ -465,11 +465,14 @@ private DevModeCommandLine newLauncher(final AnalyticsService analyticsService)
         builder.extensionDevModeConfig(appModel.getExtensionDevModeConfig())
                 .extensionDevModeJvmOptionFilter(extensionJvmOptions);
 
+        builder.jvmArgs(
+                "-Dgradle.project.path=" + getProject().getLayout().getProjectDirectory().getAsFile().getAbsolutePath());
+
         analyticsService.sendAnalytics(
                 DEV_MODE,
                 appModel,
                 Map.of(GRADLE_VERSION, getProject().getGradle().getGradleVersion()),
-                getProject().getBuildDir().getAbsoluteFile());
+                getProject().getLayout().getBuildDirectory().getAsFile().get());
 
         final Set<ArtifactKey> projectDependencies = new HashSet<>();
         for (ResolvedDependency localDep : DependenciesFilter.getReloadableModules(appModel)) {
@@ -562,6 +565,7 @@ private void addQuarkusDevModeDeps(DevModeCommandLineBuilder builder, Applicatio
                         configuration.setCanBeConsumed(false);
                         configuration.extendsFrom(platformConfig);
                         configuration.getDependencies().add(getQuarkusGradleBootstrapResolver());
+                        configuration.getDependencies().add(getQuarkusMavenBootstrapResolver());
                         configuration.getDependencies().add(getQuarkusCoreDeployment(appModel));
                     });
             devModeDependencyConfiguration = getProject().getConfigurations()
@@ -585,7 +589,15 @@ private void addQuarkusDevModeDeps(DevModeCommandLineBuilder builder, Applicatio
     }
 
     private Dependency getQuarkusGradleBootstrapResolver() {
-        final String pomPropsPath = "META-INF/maven/io.quarkus/quarkus-bootstrap-gradle-resolver/pom.properties";
+        return getQuarkusBootstrapResolver("quarkus-bootstrap-gradle-resolver");
+    }
+
+    private Dependency getQuarkusMavenBootstrapResolver() {
+        return getQuarkusBootstrapResolver("quarkus-bootstrap-maven-resolver");
+    }
+
+    private Dependency getQuarkusBootstrapResolver(String artifactId) {
+        final String pomPropsPath = "META-INF/maven/io.quarkus/" + artifactId + "/pom.properties";
```
to add the Maven resolver classes for the extension catalog resolver.

**Comment by Malandril** [comment]
Thanks @aloubyansky its a lot simpler

**Review by aloubyansky — APPROVED** [review]
@Malandril thanks a lot!

@phillip-kruger the change look good to me. Are you ok with it as well?

**Comment by phillip-kruger** [comment]
Yes
