### PR TITLE
Fix NoSuchElementException on `@Before/AfterAll` with TestInfo

### LINKED ISSUE #19800: JUnit: Exception in BeforeAll/AfterAll with TestInfo parameter
### Describe the bug

An exception is thrown on JUnit Before/AfterAll methods:

```
@QuarkusTest
public class AnnotatedTest {

    @BeforeAll
    public static void beforeAll(TestInfo testInfo) {
        Assertions.assertEquals(AnnotatedTest.class, testInfo.getTestClass().get());
        Assertions.assertFalse(testInfo.getTestMethod().isPresent());
    }

    @Test
    public void testInfoTestCase() {
    }

    @AfterAll
    public static void afterAll(TestInfo testInfo) {
        Assertions.assertEquals(AnnotatedTest.class, testInfo.getTestClass().get());
        Assertions.assertFalse(testInfo.getTestMethod().isPresent());
    }
}
```

### Expected behavior

Above test passes.

### Actual behavior

```
java.util.NoSuchElementException: No value present

	at java.base/java.util.Optional.get(Optional.java:148)
	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:1041)
        ...
```

### How to Reproduce?

Run the above test.

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.2.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

Relates to #19751

### PR DESCRIPTION
**Pull request by famod**
Fixes #19800

I hope this gift has now stopped giving. 😉

### CODE REVIEW

File: test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java [hunk 1]
```diff
@@ -1039,9 +1039,11 @@ private Object runExtensionMethod(ReflectiveInvocationContext<Method> invocation
                         cloneRequired = false;
                     } else if (TestInfo.class.isAssignableFrom(theclass)) {
                         TestInfo info = (TestInfo) arg;
-                        Method newTestMethod = determineTCCLExtensionMethod(info.getTestMethod().get(), testClassFromTCCL);
+                        Method newTestMethod = info.getTestMethod().isPresent()
+                                ? determineTCCLExtensionMethod(info.getTestMethod().get(), testClassFromTCCL)
```
Comment (famod) [inline test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java:1043]: Note: I'm usually a fan of `Optional.map()` but `determineTCCLExtensionMethod()` throws a checked exception and I didn't want to change that.

**Review by geoand — APPROVED** [review]

**Review by gsmet — APPROVED** [review]
