### PR TITLE
Honor application class predicate in QuarkusInvokerFactory

### LINKED ISSUE #47473: Quarkus (REST) behaves differently when having a parent POM
### Describe the bug

I have the problem described in #47471 

Now I had the problem, that I wasn't able to reproduce the problem outside of our library projects - so in completely new projects. After some hours I figured out, that the problem (#47471) is only reproducible when I don't have a parent POM.

With the parent POM, the problem is not reproducible. When I delete the parent POM, the tests fail. So depending on the project structure, the behavior is different. This is pretty critical in my opinion.

### Expected behavior

The behavior should always be the same. Regardless of the project structure.

When I create a library, I will write tests in this library. And these tests should work in the same way as when I put the tests in another project. Otherwise, I cannot guarantee the functionality without creating additional test projects (with other parent POM) and put the tests in there.

### Actual behavior

The behavior differs depending on the project structure.

* With parent POM: The tests fail because of the HTTP 404
* Without parent POM: The tests are running fine

So it assume, that Quarkus scans the file system (depending on the projects structure) and behaves then differently if some information can be found there. But I don't know.

### How to Reproduce?

Reproducer: https://github.com/timonzi/path-and-query-param/tree/with-parent-pom

1. Build the projects via the parent / top level POM (`mvn clean install`) => All tests are working
2. Delete the top level POM or comment out the modules
3. Build project `path-and-query-param-usage` (`mvn clean install`) => The tests will fail

See also the README.md

### Output of `uname -a` or `ver`

Linux nb-timonz 6.8.0-52-generic #53~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jan 15 19:18:46 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

OpenJDK 64-Bit Server VM Temurin-21.0.5+11 (build 21.0.5+11-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.20.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6

### Additional information

_No response_

### LINKED ISSUE #47744: IllegalAccessError with REST Resources outside of the application module
> I'm having the same issue as the one described by @kevinross. In my case I have a `@QuarkusTest` calling the controller `GreetingResource`, the later being a package-private class found in another module. 
> 
> In module A:
> ```java
> @QuarkusTest
> // the issue appears no matter if this annotation is present
> @TestHTTPEndpoint(GreetingResource.class)
> class GreetingResourceTest {
> 	@Test
> 	void testHelloEndpoint() {...}
> }
> ```
> 
> In module B:
> ```java
> @Path("/hello")
> class GreetingResource {
> 
>     @GET
>     public String hello() {...}
> }
> ```
> 
> The above code will fail with a similar error:
> ```
> 2025-05-05 13:12:39,360 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /hello failed, error id: d1aab7de-f82a-43ac-bd36-d7719092e410-1: java.lang.IllegalAccessError: failed to access class org.acme.GreetingResource from class org.acme.GreetingResource$quarkusrestinvoker$hello_df324e1539083188359af68039a7afafb7b77cdb (org.acme.GreetingResource is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @553f1d75; org.acme.GreetingResource$quarkusrestinvoker$hello_df324e1539083188359af68039a7afafb7b77cdb is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @479ac2cb)
> 	at org.acme.GreetingResource$quarkusrestinvoker$hello_df324e1539083188359af68039a7afafb7b77cdb.invoke(Unknown Source)
> 	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
> 	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
> 	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
> 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$15.runWith(VertxCoreRecorder.java:637)
> 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)
> 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)
> 	at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)
> 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)
> 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
> 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
> 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> 	at java.base/java.lang.Thread.run(Thread.java:1583)
> ```
> 
> Making `GreetingResource` public resolves the issue.
> 
> A reproducer can be found here:
> [classloader-issue.zip](https://github.com/user-attachments/files/20040887/classloader-issue.zip) 

 _Originally posted by @celcius112 in [#47692](https://github.com/quarkusio/quarkus/issues/47692#issuecomment-2851706581)_

### PR DESCRIPTION
**Pull request by gsmet**
Fixes #47744
Fixes #47473
Related to #47563

@Postremus it was really handy to have the test case all ready, thanks! :).

### CODE REVIEW

**Comment by geoand** [comment]
CI failures seem related

**Comment by gsmet** [comment]
@geoand yeah, I just pushed a second commit. My first one apparently discovered a bug that was here all along.

File: extensions/resteasy-reactive/rest-common/spi-deployment/src/main/java/io/quarkus/resteasy/reactive/spi/GeneratedJaxRsResourceBuildItem.java [hunk 1]
```diff
@@ -8,16 +8,38 @@
...
 
-    private final String name;
+    private final String binaryName;
+    private final String internalName;
     private final byte[] data;
 
     public GeneratedJaxRsResourceBuildItem(String name, byte[] data) {
-        this.name = name;
+        this.internalName = name.replace('.', '/');
+        this.binaryName = name.replace('/', '.');
```
Comment (gsmet) [inline extensions/resteasy-reactive/rest-common/spi-deployment/src/main/java/io/quarkus/resteasy/reactive/spi/GeneratedJaxRsResourceBuildItem.java:17]: This change is to make things more consistent with `GeneratedClassBuildItem` and have the same methods available.

**Review by geoand — APPROVED** [review]
Thanks!

**Comment by gsmet** [comment]
@geoand yeah this issue already happened a few times. Using a fixed port for the TLS reload test is probably not a good idea but not sure how we could do better.

**Comment by gsmet** [comment]
@holly-cummins while the previous behavior was indeed buggy, do you know why these problems started to pop, everywhere in the code base?

**Comment by holly-cummins** [comment]
> @holly-cummins while the previous behavior was indeed buggy, do you know why these problems started to pop, everywhere in the code base?

I don't. :( 

Here are some possible perturbations triggered by my changes that could be surfacing these: 

- Tests run in a different order [not a bug, but different, so can expose bugs]
- Different TCCL during some stage of the process [usually a bug but there's no one 'correct' TCCL to aim for]
- Config badness, such as config arriving too late, or being attached to the wrong classloader, so some behaviour-changing config isn't right [usually a bug]
- Extension processors all run at the beginning, instead of just before the test (where there's profiles, so I don't think that change would apply here) [as designed, but needs other code changes to not break stuff]
