### PR TITLE
Respect docker api version when present

### LINKED ISSUE #51095: TestContainers fail to run on Docker 24.x (3.29.3)
### Describe the bug

https://github.com/quarkusio/quarkus/pull/51009 hardcodes docker api version to 1.44 (change done with https://github.com/quarkusio/quarkus/issues/51002).

`ResettableSystemProperties` were used to instantiate TestContainers and 
[DefaultDockerClientConfig](https://github.com/docker-java/docker-java/blob/main/docker-java-core/src/main/java/com/github/dockerjava/core/DefaultDockerClientConfig.java#L236) takes system properties with highest priority.

This is unfortunately a breaking and non-fixable change for Docker < 25 due to api incompatibility as there is no way for me to influence the `api.version` property passed to `docker-java`.

I can not currently use newer Docker engine version as I am running builds on BuildJet.

Would it be possible to at least respect `api.version` system property if it is set? Or provide an alternative property / env var.

I have also mentioned this issue in testcontainers repo (https://github.com/testcontainers/testcontainers-java/issues/11232), as they have also made a breaking change with 2.0.2 (but in that case I was able to overwrite `api.version` property). Seems the best course of action would be if they implemented version negotiation.

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

9.29.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jakub-pietrzak**
* Fixes https://github.com/quarkusio/quarkus/issues/51095

### CODE REVIEW

File: core/deployment/src/main/java/io/quarkus/deployment/IsContainerRuntimeWorking.java [hunk 1]
```diff
@@ -64,7 +64,10 @@ public Result get() {
             // this runs in threads that start with 'ducttape'
             StartupLogCompressor compressor = new StartupLogCompressor("Checking Docker Environment", Optional.empty(), null,
                     (s) -> s.getName().startsWith("ducttape"));
-            try (ResettableSystemProperties ignored = ResettableSystemProperties.of("api.version", "1.44")) {
+
+            String dockerApiVersion = System.getProperty("api.version");
+
+            try (ResettableSystemProperties ignored = dockerApiVersion == null ? ResettableSystemProperties.of("api.version", "1.44") : null) {
```
Comment (geoand) [inline core/deployment/src/main/java/io/quarkus/deployment/IsContainerRuntimeWorking.java]:
```suggestion
            try (ResettableSystemProperties ignored = dockerApiVersion == null ? ResettableSystemProperties.of("api.version", "1.44") : ResettableSystemProperties.empty()) {
```

**Comment by geoand** [comment]
Can you please squash the commits when you are done?

**Comment by gsmet** [comment]
Hey. I handled it as I think it's something I need for today's release. Please don't push anymore, CI is running! Thanks!

**Comment by geoand** [comment]
💪🏽

**Comment by bvarner** [comment]
@geoand will this be making it to a LTS 3.27 release?

**Comment by geoand** [comment]
Likely

**Comment by bvarner** [comment]
Please do. I have LTS builds breaking on newer docker updates. How can I assist?

**Comment by geoand** [comment]
Understood.

There is nothing to do ATM, the appropriate backport label has been added, so when we do a new LTS release, we plan to include the PR
