### PR TITLE
Register provided classes in RESTClient RegisterProvider for reflection

### LINKED ISSUE #1748: User provided Rest client @RegisterProvider does not work
I am running into a problem for the following in native
```
@Path("/")
@RegisterRestClient
@RegisterProvider(GitHubApiExceptionMapper.class)
public interface GitHubApiService {

```
which gives
```
Caused by: java.lang.InstantiationException: Type `org.overbaard.review.tool.rest.client.github.GitHubApiExceptionMapper` can not be instantiated reflectively as it does not have a no-parameter constructor or the no-parameter constructor has not been added explicitly to the native image.
	at java.lang.Class.newInstance(DynamicHub.java:678)
	at io.quarkus.smallrye.restclient.runtime.RestClientBuilderImpl.newInstanceOf(RestClientBuilderImpl.java:342)
	... 69 more
```
Kabir Khan: I tried adding a default constructor but get the same error. How do I add the constructor to the native image? I think I know how to do it in an extension (https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/UUIDGenerator.20(native)/near/161981147) but don't see how to do it for user-provided code

**Ken Finnigan: please raise an issue, it likely means we need to register constructors of classes in that annotation for native image**

### PR DESCRIPTION
**Pull request by geoand**
Fixes #1748

### CODE REVIEW

File: extensions/smallrye-rest-client/deployment/src/main/java/io/quarkus/smallrye/restclient/deployment/SmallRyeRestClientProcessor.java [hunk 1]
```diff
@@ -216,14 +224,29 @@ public void register(RegistrationContext registrationContext) {
...
         }
+
+        // now we register all values of @RegisterProvider for constructor reflection
+
+        IndexView index = combinedIndexBuildItem.getIndex();
+        List<AnnotationInstance> allInstances = new ArrayList<>(index.getAnnotations(REGISTER_PROVIDER));
+        for (AnnotationInstance annotation : index.getAnnotations(REGISTER_PROVIDERS)) {
+            allInstances.addAll(Arrays.asList(annotation.value().asNestedArray()));
+        }
+        Set<String> providers = new HashSet<>();
```
Comment (kenfinnigan) [inline extensions/smallrye-rest-client/deployment/src/main/java/io/quarkus/smallrye/restclient/deployment/SmallRyeRestClientProcessor.java]: Any reason for the intermediary `providers`?

What value does it add over just iterating over `allInstances`?

**Comment by kenfinnigan** [comment]
Did this come as a result of a problem?

Would be good to have an issue reflecting the problem.

Also, looks like the code changes are formatted incorrectly.

**Comment by geoand** [comment]
@kenfinnigan It should be a fix for #1748 (it should be part of the description). I'll fix the formatting issue and re-push

File: extensions/smallrye-rest-client/deployment/src/main/java/io/quarkus/smallrye/restclient/deployment/SmallRyeRestClientProcessor.java (hunk 1 above)
Comment (geoand) [reply extensions/smallrye-rest-client/deployment/src/main/java/io/quarkus/smallrye/restclient/deployment/SmallRyeRestClientProcessor.java]: I wanted to avoid potentially registering the same provider multiple times. Do you think we shouldn't be worrying about that?

**Comment by kenfinnigan** [comment]
Somehow I missed the fix reference

**Comment by geoand** [comment]
No problem :)

File: extensions/smallrye-rest-client/deployment/src/main/java/io/quarkus/smallrye/restclient/deployment/SmallRyeRestClientProcessor.java (hunk 1 above)
Comment (kenfinnigan) [reply extensions/smallrye-rest-client/deployment/src/main/java/io/quarkus/smallrye/restclient/deployment/SmallRyeRestClientProcessor.java]: @stuartwdouglas or @dmlloyd should be able to confirm, but I would imagine that because there could be duplicate classes added to reflection from different extensions, that the core de-dupes them for us.

Could be wrong though

Comment (geoand) [reply extensions/smallrye-rest-client/deployment/src/main/java/io/quarkus/smallrye/restclient/deployment/SmallRyeRestClientProcessor.java]: I'll obviously change it if the core doesn't dedup

Comment (geoand) [reply extensions/smallrye-rest-client/deployment/src/main/java/io/quarkus/smallrye/restclient/deployment/SmallRyeRestClientProcessor.java]: Looks like the core does dedup: https://github.com/quarkusio/quarkus/blob/master/core/deployment/src/main/java/io/quarkus/deployment/steps/SubstrateAutoFeatureStep.java#L317. I will proceed to remove the superfluous code

Comment (geoand) [reply extensions/smallrye-rest-client/deployment/src/main/java/io/quarkus/smallrye/restclient/deployment/SmallRyeRestClientProcessor.java]: Removed

**Review by kenfinnigan — APPROVED** [review]
