### PR TITLE
1.7.0.Final quarkus.package.output-directory causes NPE running tests

### LINKED ISSUE #11400: 1.7.0.Final quarkus.package.output-directory causes NPE running tests
**Describe the bug**
NPE running JUnit test when `quarkus.package.output-directory` is set:

    java.lang.RuntimeException: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.deployment.pkg.steps.JarResultBuildStep#outputTarget threw an exception: java.lang.NullPointerException
	at io.quarkus.deployment.pkg.steps.JarResultBuildStep.lambda$outputTarget$0(JarResultBuildStep.java:147)
	at java.base/java.util.Optional.map(Optional.java:265)
	at io.quarkus.deployment.pkg.steps.JarResultBuildStep.outputTarget(JarResultBuildStep.java:147)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:932)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)

**Environment**
 - Quarkus version or git rev: 1.7.0.Final
 
**Additional context**
`io.quarkus.deployment.pkg.steps.JarResultBuildStep` is blowing up here because `packageConfig.outputDirectory` has a value but `bst.getOutputDirectory()` does not.  

    @BuildStep
    OutputTargetBuildItem outputTarget(BuildSystemTargetBuildItem bst, PackageConfig packageConfig) {
        String name = packageConfig.outputName.orElseGet(bst::getBaseName);
        Path path = packageConfig.outputDirectory.map(s -> bst.getOutputDirectory()*NPE*.resolve(s))
                .orElseGet(bst::getOutputDirectory);
        return new OutputTargetBuildItem(path, name, bst.isRebuild(), bst.getBuildSystemProps());
    }

Using `%test.quarkus.package.output-directory=` to clear the setting allows the tests to run.

### PR DESCRIPTION
**Pull request by aloubyansky**
Fixes #11400

### CODE REVIEW

File: test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java [hunk 1]
```diff
@@ -171,18 +171,27 @@ private ExtensionState doJavaStart(ExtensionContext context, Class<? extends Qua
...
-            runnerBuilder.setProjectRoot(Paths.get("").normalize().toAbsolutePath());
+            final Path projectRoot = Paths.get("").normalize().toAbsolutePath();
+            runnerBuilder.setProjectRoot(projectRoot);
+            Path outputDir;
+            try {
+                // this should work for both maven and gradle
+                outputDir = projectRoot.resolve(projectRoot.relativize(testClassLocation).getName(0));
+            } catch (Exception e) {
+                // this shouldn't happen since testClassLocation is usually found under the project dir
+                outputDir = projectRoot;
```
Comment (gastaldi) [inline test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java:182]: It would be nice to log.debug this exception, just in case

Comment (aloubyansky) [reply test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java:182]: I am not sure it's worth it. It would mean the project has an usual layout and if so, the user is very much aware of that w/o us logging stacktraces. There is a lot of garbage in the debug output w/o it. Second, this outputDir for QuarkusTest's isn't normally used at all, we are not packaging anything.

**Review by gastaldi — APPROVED** [review]

**Comment by gsmet** [comment]
@aloubyansky I saw you force pushed a few times, is this one ready to go in?

**Comment by aloubyansky** [comment]
Yes, i did that just to restart the CI hoping it'd pass.

**Comment by gsmet** [comment]
Yeah, no need for that, it won't, unfortunately.
