### PR TITLE
Make the Jackson mapper of Amazon Lambda case insensitive

### LINKED ISSUE #3481: Extension quarkus-amazon-lambda does not consume SQS payload correctly
**Describe the bug**
When we invoke our Lambda with an SQS event payload we get the events but the records are null.

The code below can be used to see the problem

`
public class ExampleLambdaSqs implements RequestHandler<SQSEvent, Void> {

    private static final Logger LOG = Logger.getLogger(ExampleLambdaSqs.class);

    @Override
    public Void handleRequest(SQSEvent input, Context context) {
        LOG.info("SQS request received");
        LOG.info(input);    
        LOG.info(input.getRecords()); // This is null    
        return null;
    }
}
`

**Expected behavior**
The data within the Records field is correctly mapped to the records field of SQSEvent.

**Actual behavior**
The records field in SQSEvent remains null

**To Reproduce**
Invoke the lambda function with sam local via the following command

`
sam local invoke -e src/test/resources/event.json
`

The contents of this event.json is 

`
{
  "Records": [
    {
      "messageId": "c80e8021-a70a-42c7-a470-796e1186f753",
      "receiptHandle": "AQEBJQ+/u6NsnT5t8Q/VbVxgdUl4TMKZ5FqhksRdIQvLBhwNvADoBxYSOVeCBXdnS9P+erlTtwEALHsnBXynkfPLH3BOUqmgzP25U8kl8eHzq6RAlzrSOfTO8ox9dcp6GLmW33YjO3zkq5VRYyQlJgLCiAZUpY2D4UQcE5D1Vm8RoKfbE+xtVaOctYeINjaQJ1u3mWx9T7tork3uAlOe1uyFjCWU5aPX/1OHhWCGi2EPPZj6vchNqDOJC/Y2k1gkivqCjz1CZl6FlZ7UVPOx3AMoszPuOYZ+Nuqpx2uCE2MHTtMHD8PVjlsWirt56oUr6JPp9aRGo6bitPIOmi4dX0FmuMKD6u/JnuZCp+AXtJVTmSHS8IXt/twsKU7A+fiMK01NtD5msNgVPoe9JbFtlGwvTQ==",
      "body": "{ \"propertyName\": \"propertyValue\"}",
      "attributes": {
        "ApproximateReceiveCount": "3",
        "SentTimestamp": "1529104986221",
        "SenderId": "594035263019",
        "ApproximateFirstReceiveTimestamp": "1529104986230"
      },
      "messageAttributes": {},
      "md5OfBody": "9bb58f26192e4ba00f01e2e7b136bbd8",
      "eventSource": "aws:sqs",
      "eventSourceARN": "arn:aws:sqs:us-west-2:594035263019:QUEUE",
      "awsRegion": "us-west-2"
    }
  ]
}
`

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin APRXJGH6D5D5F9 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64
 - Output of `java -version`: 1.8.0_211
 - GraalVM version (if different from Java): 19.0.2
 - Quarkus version or git rev: 0.20.0

**Additional context**
(Add any other context about the problem here.)

### PR DESCRIPTION
**Pull request by debae**
I tried to create a unit test for the AmazonLambdaRecorder but was not possible ( for me ... ) to have it tested. It creates a URLConnection with no possibility to mock this.

I noticed there is a LambdaResourceManager which can be used to achieve this, but I could not add this as a dependency because it would end up as a cyclic dependency.

Fixes https://github.com/quarkusio/quarkus/issues/3481

### CODE REVIEW

**Comment by gsmet** [comment]
I'm not totally sure we would this enabled by default.

What's the rationale of this change exactly?

**Comment by geoand** [comment]
Also there is a formatting issue

**Comment by gsmet** [comment]
@debae to fix the formatting issue, just run `mvn process-sources` and amend your commit.

**Comment by gsmet** [comment]
OK, I saw your message on Zulip, saw the issue and understood the rationale. Makes sense to me now.

Can you please fix the formatting issue? Thanks!

**Comment by geoand** [comment]
@debae can you please squash to a single commit?

Thanks!

**Review by evanchooly — APPROVED** [review]

**Comment by gsmet** [comment]
@debae I think there's a formatting issue here: `mvn process-sources` should fix it.

Could you amend your commit with the fix?

File: extensions/amazon-lambda/runtime/src/main/java/io/quarkus/amazon/lambda/runtime/AmazonLambdaRecorder.java [hunk 1]
```diff
@@ -6,12 +6,14 @@
 import java.net.URL;
 import java.util.concurrent.atomic.AtomicBoolean;
 
+import com.fasterxml.jackson.databind.MapperFeature;
```
Comment (gastaldi) [inline extensions/amazon-lambda/runtime/src/main/java/io/quarkus/amazon/lambda/runtime/AmazonLambdaRecorder.java]:
```suggestion
```

Comment (debae) [reply extensions/amazon-lambda/runtime/src/main/java/io/quarkus/amazon/lambda/runtime/AmazonLambdaRecorder.java]: made a mistake with the squash and reverted my commit that contained the `mvn process-sources` by mistake. It's fixed now in one commit.

**Comment by gsmet** [comment]
Merged, thanks!
