### PR TITLE
Make WebClientApplicationException usable from application code

### LINKED ISSUE #17397: Reactive Rest Client should allow extracting response status from WebClientApplicationException
## Describe the bug
When the rest client makes a call to an external service, that call can fail with a non-OK status code (e.g. 401 when a token timed out). In such a case, the reactive rest client creates a `WebClientApplicationException` (see https://github.com/quarkusio/quarkus/blob/e21b6c2ed8971be0e8f575fde7706839ed118651/independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/handlers/ClientSetResponseEntityRestHandler.java#L24). However, it only provides a message with the status code to the exception. 

Thus, the only way to find out the status code of the response of the call is to parse the message of the `WebClientApplicationException`. In my case I need the status because I implement a service similar to a "proxy" and therefore need to return the same status code from my service to my clients.

Is there a reason not to use the standard `javax.ws.rs.WebApplicationException`? If I recall correctly, that was used by the standard rest client.

Furthermore, there is a difference in the type of Exception you get depending on the return type of your rest client method. If you return a `Uni<MyDto>` and the call receives a non-OK status, you get a `WebClientApplicationException`. However, if you return a `Uni<Response>` in the rest client method, you get a `ProcessingException` that contains a standard `javax.ws.rs.WebApplicationException`. See the reproducer for more details.

### Expected behavior
1. It must be easily possible to get the causing status code from the thrown exception.
2. You should get the same error no matter if the rest client method returns a `Uni<Dto>` or `Uni<Response>`. 

### Actual behavior
1. The `WebClientApplicationException` only contains the status code in the message from which we would need to parse it. 
2. The thrown exception differs depending on the return type of your rest client method.

## To Reproduce

1. Download and unzip reproducer project 
[2021-05-20-reactive-restclient-exceptions.zip](https://github.com/quarkusio/quarkus/files/6518759/2021-05-20-reactive-restclient-exceptions.zip). 
2. Start the project with `./gradlew quarkusDev`
3. Open your browser and open http://localhost:8080/test-dto . This will make a call with the rest client which receives a 401 status. The rest client method has a return Type of `Uni<Dto>`. You will receive the following error object:
```
{"exceptionClass":"WebClientApplicationException","message":"Message: 'Server response status was: 401' ;;; Response Object: null"}
```
4. Open your browser and open http://localhost:8080/test-response . This makes a call with the rest client and also receives a status 401. However, this time the rest client method returns `Uni<Response>`. You will now receive the following error object:
```
{"exceptionClass":"ProcessingException","message":"javax.ws.rs.WebApplicationException: Unknown error, status code 401"}
```

## Additional context
* Tested with Quarkus 1.13.4.Final. 
* In `main`, the `WebClientApplicationException` also only takes the message argument. So issue 1 persists. Issue 2 I haven't tested yet.

### PR DESCRIPTION
**Pull request by geoand**
This is done by making the response code queryable.

This is technically a breaking change, but as RESTEasy Reactive is still in experimental phase, it's fine.

Fixes: #17397

### CODE REVIEW

File: independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/api/WebClientApplicationException.java [hunk 1]
```diff
@@ -24,35 +25,36 @@
...
 
-    @Override
-    public final Response getResponse() {
-        return null;
-    }
-
-    // used in order to avoid depending on the server parts just for generating the exception
+    /**
+     * Used in order to avoid depending on the server parts just for generating the exception
+     * The
```
Comment (famod) [inline independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/api/WebClientApplicationException.java:38]: Premature EOL? 😉

Comment (geoand) [reply independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/api/WebClientApplicationException.java]: It doesn't surprise me one bit that I did this :)

**Review by michalszynkiewicz — APPROVED** [review]
