### PR TITLE
Support for the fixed redirect URI

### LINKED ISSUE #5733: OIDC Redirect URL should be static absolute URL
**Describe the bug**
Currently Quarkus is including the full [request path](https://github.com/quarkusio/quarkus/blob/21cd452f7efe9936cd0cbc104a8644d872d13815/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java#L162) in the redirect URL. According to the OAuth 2.0 specification that OIDC is based on the redirect URL should be [absolute](https://tools.ietf.org/html/rfc6749#section-3.1.2).

Without a constant redirect path it is not possible to configure a single whitelisted login redirect URI in the OIDC IDP. 

For example if http://localhost:5000/ is added to the IDP allowed redirect URLs if an unauthenticated user access http://localhost:5000/profile the redirect URL is sent as http://localhost:5000/profile which is not allowed in the IDP and the IDP displays an error.

**Expected behavior**
The redirect URL should have a static path like / or /oidc. The initially requested path should be stored in the web session or relayState and after the OAuth code authentication is performed the response should be redirected back to the initially requested path. 

**Actual behavior**
Whatever unauthenticated request path that is submitted to Quarkus is set as the redirect URL. There are an infinite possible request path variations and it is not possible to include them all or configure wildcards in the IDP which would be a violation of the OAuth standard.

**To Reproduce**
1. Enable the OIDC extension
2. In the IDP add the application's base URL as the redirect URL, i.e. http://localhost:5000
3. Access the local application, OIDC authentication works as expected.
4. Open an anonymous browser session, access http://localhost:5000/test
5. http://localhost:5000/test is sent as the redirect URL, this value is not in the applications approved redirect URL list, the IDP rejects the login request.

**Configuration**
```
quarkus.oidc.auth-server-url=https://xxxxxxx.okta.com
quarkus.oidc.client-id=XXXXXXXXXXXXXXX
quarkus.oidc.credentials.secret=XXXXXXXXXXXXXXXXX
quarkus.oidc.authentication.scopes=openid,profile,groups
quarkus.oidc.application-type=web-app


quarkus.http.auth.permission.authenticated1.paths=/*
quarkus.http.auth.permission.authenticated1.policy=authenticated

quarkus.http.auth.permission.permit1.paths=/health/*
quarkus.http.auth.permission.permit1.policy=permit
quarkus.http.auth.permission.permit1.methods=GET

```

### PR DESCRIPTION
**Pull request by sberyozkin**
Fixes #5733 . 
This PR introduces a (relative) `redirect-path` property, which, if set, will be used to calculate a static `redirect_uri` parameter. The remaining (dynamic part) of the current request URI will be stored in a `q_auth` state cookie (queries parameters can also be saved but it can be done in a follow up PR).

Right now the problem is that a `RoutingContext.reroute` method does not seem to work.
Note a 'state' parameter (as well as a state cookie) are not added unless a dynamic path is available because there is nothing else at the moment that is being saved.

### CODE REVIEW

**Comment by sberyozkin** [comment]
CC @stianst @pedroigor @stuartwdouglas

**Comment by sberyozkin** [comment]
note I've updated the test `application.properties` with `quarkus.oidc.authentication.redirect-path=/web-app/refresh` - this does not affect any of the tests and tests that unless this value is a subset of the actual request raw path then nothing is affected.
If I set this value to `quarkus.oidc.authentication.redirect-path=/web-app` then the newly added test fails because the `reroute` code from `web-app` to `web-app/refresh` does not seem to work

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java [hunk 1]
```diff
@@ -105,9 +110,27 @@ private static QuarkusSecurityIdentity augmentIdentity(SecurityIdentity security
...
+        Cookie stateCookie = removeCookie(context, STATE_COOKIE_NAME);
+        if (stateCookie != null) {
+            List<String> values = context.queryParam("state");
+            if (values == null || values.size() != 1 || !stateCookie.getValue().startsWith(values.get(0))) {
+                cf.completeExceptionally(new AuthenticationFailedException());
+                return cf;
+            } else {
+                String extraPath = stateCookie.getValue().split(COOKIE_DELIM)[1];
+                // This code does not work
+                context.reroute(absoluteUri.getRawPath() + extraPath);
```
Comment (pedroigor) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java]: Isn't enough to send a redirect ?

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java [hunk 2]
```diff
@@ -89,8 +88,14 @@ private static QuarkusSecurityIdentity augmentIdentity(SecurityIdentity security
...
         params.put("scopes", new JsonArray(scopes));
-        params.put("redirect_uri", buildRedirectUri(context));
-        params.put("state", generateState(context));
+
+        URI absoluteUri = URI.create(context.request().absoluteURI());
+        String dynamicPath = getDynamicPath(context, absoluteUri);
+        params.put("redirect_uri", buildRedirectUri(context, absoluteUri, dynamicPath));
+
+        if (dynamicPath != null) {
+            params.put("state", generateState(context, dynamicPath));
```
Comment (pedroigor) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java]: I think we should always send the state parameter. It provides a barrier to CSRF.

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java [hunk 3]
```diff
@@ -129,46 +152,63 @@ private static QuarkusSecurityIdentity augmentIdentity(SecurityIdentity security
...
+            if (requestPath.startsWith(redirectPath) && requestPath.length() > redirectPath.length()) {
+                return requestPath.substring(redirectPath.length());
+            }
+        }
+        return null;
+    }
+
+    private String generateState(RoutingContext context, String dynamicPath) {
+        String uuid = UUID.randomUUID().toString();
+        String cookieValue = uuid + COOKIE_DELIM + dynamicPath;
```
Comment (pedroigor) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java]: You could probably reuse the state parameter to bind the callback uri.

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java [hunk 4]
```diff
@@ -129,46 +152,63 @@ private static QuarkusSecurityIdentity augmentIdentity(SecurityIdentity security
...
+
+        CookieImpl cookie = new CookieImpl(STATE_COOKIE_NAME, cookieValue);
 
         cookie.setHttpOnly(true);
         cookie.setSecure(context.request().isSSL());
-        cookie.setMaxAge(-1);
+        cookie.setMaxAge(60 * 5);
```
Comment (pedroigor) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java]: Is this really necessary given that we always reset the cookie when doing challenges? Assuming that the user may take more time than usual to log in at the AS, the cookie will be automatically removed and the redirect will fail.

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java (hunk 2 above)
Comment (pedroigor) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java]: In fact, a future improvement here would be to support PKCE. Just a side comment :)

**Comment by gastaldi** [comment]
@sberyozkin are you sure that this PR fixes #5773 ? The changes seem unrelated

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java (hunk 1 above)
Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java]: @pedroigor yeah, that should be enough actually, will try :-)

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java (hunk 2 above)
Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java]: @pedroigor You are right, I'll just keep a check that compares it with the the cookie on the way back

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java (hunk 3 above)
Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java]: @pedroigor yeah, I thought about it but if it goes in the URL it be encoded so it may end up being double encoded and as such we can lose the original percent encoding if any in the original path, hence I added it to the cookie. Going forward I guess we can expect the cookie become a (secured) container of various properties...

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java (hunk 4 above)
Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java]: @pedroigor I updated it because when a `security-oidc-web-app-authentication-quickstart` is built a lot of warnings is displayed about an invalid `max-age=-1` cookie parameter :-). I set to to 5 mins, but we can set it to 30 mins, that should be enough, what do you think ?

**Comment by sberyozkin** [comment]
@gastaldi sorry, fixed it

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java (hunk 2 above)
Comment (stianst) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java]: PKCE is aimed at public clients. Confidential clients should use state and nonce though.

**Comment by stianst** [comment]
This should be the default behaviour, and not something that requires redirect-path option to enable.

**Comment by sberyozkin** [comment]
@stianst I tried to approach it this way originally, I did not even had this property, and wrote the code which would settle on the 1st path segment and save the remaining part in the state cookie as per my comment in the issue, but it proved impossible to fix generically, as there could be the static resources sitting on the URI paths which are not overlapping with the JAX-RS paths.

For example, a request may start with an access to a protected resource `http://localhost:8081/pages/index.html` (I've found it while trying to come up with a test) and the JAX-RS endpoint paths are starting from `/web-app`. My code would set a `redirect_uri` to `http://localhost:8081/pages` but then on the way back a 404 is reported before the OIDC adapter gets a chance to restore a complete path.
It did work for the existing tests starting from a `http://localhost:8081/index.html` request but only because on the way back Quarkus would resolve `http://localhost:8081/` to the root index.html but it is a special case.

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java (hunk 4 above)
Comment (pedroigor) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java]: It should be fine, maybe we can also add an additional step after successfully obtaining the ID Token and remove the cookie ?

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java (hunk 2 above)
Comment (pedroigor) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java]: My point is you can still have `web-app` type applications as public (although much more secure would be if people just configure their clients as confidential).

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java (hunk 4 above)
Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java]: @pedroigor yes, it is removed in this PR, but before the code step is started but I'll tweak it

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java (hunk 1 above)
Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java]: done

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java (hunk 2 above)
Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java]: State cookie is always used now

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java (hunk 4 above)
Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java]: It is now removed only after the local redirect

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpSecurityRecorder.java [hunk 5]
```diff
@@ -47,6 +48,11 @@ public void run() {
                                         event.response().end();
                                     }
                                 });
+                            } else if (throwable instanceof AuthenticationRedirectException) {
```
Comment (stuartwdouglas) [inline extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpSecurityRecorder.java]: I don't think this is correct. As I understand it this is basically a challenge, so it should be send as part of sendChallenge()? 

Otherwise you loose the ability to have unprotected resources, as this will attempt to log in on every request even if the page is supposed to be public.

**Review by stuartwdouglas — CHANGES_REQUESTED** [review]

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpSecurityRecorder.java (hunk 5 above)
Comment (sberyozkin) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpSecurityRecorder.java]: @stuartwdouglas This exception may only be thrown on the return leg of the OIDC code flow, not when the user is initially trying to access a resource. (Ex, user accesses a protected resource, user is redirected, with some of the original path saved in the cookie, user is redirected back - and now if the original path needs to be restored the user will be redirect to it)
FYI, `CodeFlowTest` test accessing an `UnprotectedResource` which you added passes with this PR.

Comment (stuartwdouglas) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpSecurityRecorder.java]: ah, ok. In that case I think it is ok.

**Comment by sberyozkin** [comment]
@pedroigor, @stianst Hi, I'm hoping to merge it soon for it to make it to 1.1.0 now that Stuart @stuartwdouglas 's concern about the unprotected resources has been resolved :-), if you have some other concerns then let me know today

**Review by stuartwdouglas — APPROVED** [review]
