### PR TITLE
Funqy - fix constructor injection for normal scoped beans

### LINKED ISSUE #27671: Classes with @Funq methods fail in constructor injection for normal scoped bean
### Describe the bug

When class that is normal scoped bean has method annotated with `@Funq` and uses constructor injection, an exception is thrown. I looked into this and the reason is that when (and only when!) class does extend SomeClass and there is no default constructor without args, Funqy generates it for us here https://github.com/quarkusio/quarkus/blob/b9d7536effc07f08f119eea292673da6e0826057/extensions/funqy/funqy-server-common/deployment/src/main/java/io/quarkus/funqy/deployment/FunctionScannerBuildStep.java#L176

but Quarkus Arc does too for normal scoped beans unless a bean class extends a class that does not declare a no-args constructor.

### Expected behavior

Constructor injection for normal scoped beans works just fine.

### Actual behavior

An exception is thrown: `Exception in thread "main" java.lang.reflect.InvocationTargetException`
`Caused by: java.lang.ClassFormatError: Duplicate method name "<init>" with signature "()V" in class file io/quarkus/funqy/deployment/DependencyInjectionTest$HiFunction`

### How to Reproduce?

1. `git clone https://github.com/michalvavrik/funqy-knative-events-constructor-injection-reproducer.git`
2. `mvn clean verify`

### Output of `uname -a` or `ver`

Linux fedora 5.19.4-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Aug 25 17:42:04 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.3" 2022-04-19

### GraalVM version (if different from Java)

GraalVM CE 22.1.0

### Quarkus version or git rev

999-SNAPSHOT

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by michalvavrik**
fixes: #27671

Default no-args constructor is not generated for normal scoped beans anymore.

### CODE REVIEW

**Review by manovotn — APPROVED** [review]
I am not familiar with funqy so I'll let someone else also review as well but from Arc/CDI perspective, this looks good!

**Review by geoand — APPROVED** [review]

File: extensions/funqy/funqy-server-common/deployment/src/main/java/io/quarkus/funqy/deployment/FunctionScannerBuildStep.java [hunk 1]
```diff
@@ -172,6 +172,12 @@ private static void generateDefaultConstructors(BuildProducer<BytecodeTransforme
             Set<ClassInfo> withoutDefaultCtor) {
 
         for (ClassInfo classInfo : withoutDefaultCtor) {
+            // don't generate constructor for normal scoped beans as the Quarkus Arc does that for us
```
Comment (mkouba) [inline extensions/funqy/funqy-server-common/deployment/src/main/java/io/quarkus/funqy/deployment/FunctionScannerBuildStep.java:175]: So in theory, custom scopes can be normal as well. On the other hand, this solution probably covers 99% of use cases. Also the `CustomScopeAnnotationsBuildItem` can only be used to test the scope annotations and not whether they represent a normal scope.

Comment (michalvavrik) [reply extensions/funqy/funqy-server-common/deployment/src/main/java/io/quarkus/funqy/deployment/FunctionScannerBuildStep.java:175]: Didn't know that, thank you.
