### PR TITLE
Re-enable MutinyTest

### LINKED ISSUE #11687: MutinyTest#testSSE can be unstable
Just got this failure on CI. Don't know if the timeout is just not enough or if there is a more problematic issue.

I disabled the test for now.

In this run https://github.com/quarkusio/quarkus/pull/11679/checks?check_run_id=1038350811 , I got the error for both the JDK 14 build and the Windows build.

```
2020-08-27T21:08:08.0316811Z [INFO] Running io.quarkus.it.resteasy.mutiny.MutinyTest
2020-08-27T21:08:13.5016662Z 2020-08-27 21:08:13,486 INFO  [io.quarkus] (main) Quarkus 999-SNAPSHOT on JVM started in 2.199s. Listening on: http://0.0.0.0:8081
2020-08-27T21:08:13.5017074Z 2020-08-27 21:08:13,487 INFO  [io.quarkus] (main) Profile test activated. 
2020-08-27T21:08:13.5017471Z 2020-08-27 21:08:13,487 INFO  [io.quarkus] (main) Installed features: [cdi, mutiny, rest-client, resteasy, resteasy-jsonb, resteasy-mutiny, smallrye-context-propagation]
2020-08-27T21:08:25.6885373Z 2020-08-27 21:08:25,681 ERROR [org.jbo.res.res.i18n] (executor-thread-1) RESTEASY002020: Unhandled asynchronous exception, sending back 500: java.io.IOException: boom
2020-08-27T21:08:25.6886170Z 	at io.quarkus.it.resteasy.mutiny.MutinyResource.fail(MutinyResource.java:33)
2020-08-27T21:08:25.6886511Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-08-27T21:08:25.6886944Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-08-27T21:08:25.6888837Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-08-27T21:08:25.6889774Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
2020-08-27T21:08:25.6891229Z 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:167)
2020-08-27T21:08:25.6892896Z 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
2020-08-27T21:08:25.6894706Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:638)
2020-08-27T21:08:25.6897212Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:504)
2020-08-27T21:08:25.6899073Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:454)
2020-08-27T21:08:25.6901649Z 	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
2020-08-27T21:08:25.6903082Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:456)
2020-08-27T21:08:25.6904663Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:417)
2020-08-27T21:08:25.6906280Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:391)
2020-08-27T21:08:25.6907923Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:68)
2020-08-27T21:08:25.6909596Z 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:488)
2020-08-27T21:08:25.6911296Z 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:259)
2020-08-27T21:08:25.6913093Z 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:160)
2020-08-27T21:08:25.6915649Z 	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
2020-08-27T21:08:25.6917258Z 	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:163)
2020-08-27T21:08:25.6928616Z 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:245)
2020-08-27T21:08:25.6929509Z 	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
2020-08-27T21:08:25.6931330Z 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:131)
2020-08-27T21:08:25.6933059Z 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:37)
2020-08-27T21:08:25.6934673Z 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:94)
2020-08-27T21:08:25.6936400Z 	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
2020-08-27T21:08:25.6937802Z 	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
2020-08-27T21:08:25.6939575Z 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
2020-08-27T21:08:25.6941145Z 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
2020-08-27T21:08:25.6942408Z 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
2020-08-27T21:08:25.6944145Z 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
2020-08-27T21:08:25.6944981Z 	at java.base/java.lang.Thread.run(Thread.java:832)
2020-08-27T21:08:25.6946010Z 	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
2020-08-27T21:08:25.6946281Z 
2020-08-27T21:08:25.8616649Z 2020-08-27 21:08:25,752 WARN  [org.jbo.res.cli.jax.i18n] (Finalizer) RESTEASY004687: Closing a class org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient43Engine instance for you. Please close clients yourself.
2020-08-27T21:08:26.1391639Z [ERROR] Tests run: 9, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 18.095 s <<< FAILURE! - in io.quarkus.it.resteasy.mutiny.MutinyTest
2020-08-27T21:08:26.1392396Z [ERROR] io.quarkus.it.resteasy.mutiny.MutinyTest.testSSE  Time elapsed: 10.126 s  <<< ERROR!
2020-08-27T21:08:26.1394414Z org.awaitility.core.ConditionTimeoutException: Condition with lambda expression in io.quarkus.it.resteasy.mutiny.MutinyTest that uses java.util.List was not fulfilled within 10 seconds.
2020-08-27T21:08:26.1395696Z 	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:165)
2020-08-27T21:08:26.1397100Z 	at org.awaitility.core.CallableCondition.await(CallableCondition.java:78)
2020-08-27T21:08:26.1398236Z 	at org.awaitility.core.CallableCondition.await(CallableCondition.java:26)
2020-08-27T21:08:26.1428205Z 	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:895)
2020-08-27T21:08:26.1428739Z 	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:864)
2020-08-27T21:08:26.1430000Z 	at io.quarkus.it.resteasy.mutiny.MutinyTest.testSSE(MutinyTest.java:95)
2020-08-27T21:08:26.1431711Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-08-27T21:08:26.1433366Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-08-27T21:08:26.1435421Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-08-27T21:08:26.1436512Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
2020-08-27T21:08:26.1438327Z 	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:753)
2020-08-27T21:08:26.1440407Z 	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestMethod(QuarkusTestExtension.java:660)
2020-08-27T21:08:26.1441840Z 	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
2020-08-27T21:08:26.1443732Z 	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
2020-08-27T21:08:26.1446357Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
2020-08-27T21:08:26.1448005Z 	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
2020-08-27T21:08:26.1449936Z 	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
2020-08-27T21:08:26.1451727Z 	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
2020-08-27T21:08:26.1454245Z 	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
2020-08-27T21:08:26.1455980Z 	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
2020-08-27T21:08:26.1458477Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
2020-08-27T21:08:26.1460415Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
2020-08-27T21:08:26.1462482Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
2020-08-27T21:08:26.1464422Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
2020-08-27T21:08:26.1466026Z 	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
2020-08-27T21:08:26.1467626Z 	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
2020-08-27T21:08:26.1469966Z 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:212)
2020-08-27T21:08:26.1471786Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-08-27T21:08:26.1474105Z 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:208)
2020-08-27T21:08:26.1476184Z 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:137)
2020-08-27T21:08:26.1478251Z 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:71)
2020-08-27T21:08:26.1625783Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
2020-08-27T21:08:26.1633910Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-08-27T21:08:26.1646240Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
2020-08-27T21:08:26.1655618Z 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
2020-08-27T21:08:26.1690073Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
2020-08-27T21:08:26.1697548Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-08-27T21:08:26.1704947Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
2020-08-27T21:08:26.1710927Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
2020-08-27T21:08:26.1715222Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
2020-08-27T21:08:26.1724706Z 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
2020-08-27T21:08:26.1731828Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
2020-08-27T21:08:26.1738431Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-08-27T21:08:26.1747977Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
2020-08-27T21:08:26.1753538Z 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
2020-08-27T21:08:26.1761536Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
2020-08-27T21:08:26.1768656Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-08-27T21:08:26.1776191Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
2020-08-27T21:08:26.1782662Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
2020-08-27T21:08:26.1787150Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
2020-08-27T21:08:26.1796295Z 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
2020-08-27T21:08:26.1807786Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
2020-08-27T21:08:26.1814467Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-08-27T21:08:26.1829281Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
2020-08-27T21:08:26.1834448Z 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
2020-08-27T21:08:26.1843206Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
2020-08-27T21:08:26.1850218Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-08-27T21:08:26.1857311Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
2020-08-27T21:08:26.1864311Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
2020-08-27T21:08:26.1898210Z 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
2020-08-27T21:08:26.1906361Z 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
2020-08-27T21:08:26.1914309Z 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
2020-08-27T21:08:26.1920674Z 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
2020-08-27T21:08:26.1928404Z 	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
2020-08-27T21:08:26.1936789Z 	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
2020-08-27T21:08:26.1942511Z 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
2020-08-27T21:08:26.1948202Z 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
2020-08-27T21:08:26.1954745Z 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:188)
2020-08-27T21:08:26.1962280Z 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:154)
2020-08-27T21:08:26.1968806Z 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:128)
2020-08-27T21:08:26.1974591Z 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
2020-08-27T21:08:26.1979798Z 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
2020-08-27T21:08:26.1984806Z 	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
2020-08-27T21:08:26.1989855Z 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
```

### LINKED ISSUE #11711: ReactiveMongodbPanacheResourceTest is regularly failing
ReactiveMongodbPanacheResourceTest has been failing in our CI jobs. Initially the `await` timeout used in that test was 1 second. Given our CI issues, I thought it was just a case of the runtime being slow, so I increased the timeout to 10 seconds, but it still fails:

```
2020-08-28T12:07:01.1800062Z [ERROR] Tests run: 6, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 23.519 s <<< FAILURE! - in io.quarkus.it.mongodb.panache.reactive.ReactiveMongodbPanacheResourceTest
2020-08-28T12:07:01.1899699Z [ERROR] io.quarkus.it.mongodb.panache.reactive.ReactiveMongodbPanacheResourceTest.testReactiveBookEntity  Time elapsed: 10.922 s  <<< ERROR!
2020-08-28T12:07:01.2022093Z org.awaitility.core.ConditionTimeoutException: Condition returned by method "callReactiveBookEndpoint" in class io.quarkus.it.mongodb.panache.reactive.ReactiveMongodbPanacheResourceTest was not fulfilled within 10 seconds.
2020-08-28T12:07:01.2039988Z 	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:165)
2020-08-28T12:07:01.2040849Z 	at org.awaitility.core.CallableCondition.await(CallableCondition.java:78)
2020-08-28T12:07:01.2041735Z 	at org.awaitility.core.CallableCondition.await(CallableCondition.java:26)
2020-08-28T12:07:01.2042449Z 	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:895)
2020-08-28T12:07:01.2159429Z 	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:864)
2020-08-28T12:07:01.2266484Z 	at io.quarkus.it.mongodb.panache.reactive.ReactiveMongodbPanacheResourceTest.callReactiveBookEndpoint(ReactiveMongodbPanacheResourceTest.kt:203)
2020-08-28T12:07:01.2327458Z 	at io.quarkus.it.mongodb.panache.reactive.ReactiveMongodbPanacheResourceTest.testReactiveBookEntity(ReactiveMongodbPanacheResourceTest.kt:46)
2020-08-28T12:07:01.2627127Z 	at 
```

### PR DESCRIPTION
**Pull request by kenfinnigan**
- Fixes #11687
 - Moved JAX-RS ClientBuilder service file for native to RESTClientProcessor
 - Use existing ResteasyProviderFactory to register client providers with if it exists, and don't replace the provider directly

### CODE REVIEW

File: extensions/rest-client/runtime/src/main/java/io/quarkus/restclient/runtime/RestClientRecorder.java [hunk 1]
```diff
@@ -59,25 +59,36 @@ public InjectorFactory getInjectorFactory() {
             }
         };
 
-        if (useBuiltIn) {
-            RegisterBuiltin.register(clientProviderFactory);
-            registerProviders(clientProviderFactory, contributedProviders, false);
+        registerProviders(clientProviderFactory, useBuiltIn, providersToRegister, contributedProviders);
+
+        if (ResteasyProviderFactory.peekInstance() != null) {
```
Comment (gsmet) [inline extensions/rest-client/runtime/src/main/java/io/quarkus/restclient/runtime/RestClientRecorder.java:64]: Does the execution order play a role here? @jaikiran reported that sometimes the server one was initialized first and sometimes the client one.

I think we should have a build item ensuring that the order of operations is fully determined.

**Review by gsmet — DISMISSED** [review]
Added a suggestion. Let's wait for @jaikiran 's opinion on this one as he's the one having the details on the execution order.

File: extensions/rest-client/runtime/src/main/java/io/quarkus/restclient/runtime/RestClientRecorder.java (hunk 1 above)
Comment (kenfinnigan) [reply extensions/rest-client/runtime/src/main/java/io/quarkus/restclient/runtime/RestClientRecorder.java:64]: To my understanding, the only time there's a problem is when the server one is created first and the REST Client one clobbers it.

I don't think the reverse situation poses any problems.

In addition, there are many times where only the server or only REST Client is present, so I'm not sure how a BuildItem helps in that situation

Comment (kenfinnigan) [reply extensions/rest-client/runtime/src/main/java/io/quarkus/restclient/runtime/RestClientRecorder.java:64]: Another point to note is that the provider factory for server or client side are actually different instances of the same class, where the "server" instance has a no-op for all client operations, and the "client" instance the reverse.

Comment (gsmet) [reply extensions/rest-client/runtime/src/main/java/io/quarkus/restclient/runtime/RestClientRecorder.java:64]: We could have a build item in one of the artifacts common to the two, the server would produce it and the client optionally consume it.

This way, if the server is present, we would be sure the client code would be executed after the server code.

Obviously, we can also do the opposite if it makes more sense.

Comment (kenfinnigan) [reply extensions/rest-client/runtime/src/main/java/io/quarkus/restclient/runtime/RestClientRecorder.java:64]: Another option, which will take some time, is to add the functionality we have for `RestClientBuilderImpl` to `ResteasyClientBuilderImpl` that can use a static method to set the provider directly into the instance.

Then ordering isn't an issue. I've raised https://issues.redhat.com/browse/RESTEASY-2684 to discuss this option with the RESTEasy team

Comment (gsmet) [reply extensions/rest-client/runtime/src/main/java/io/quarkus/restclient/runtime/RestClientRecorder.java:64]: While fixing things in RESTEasy would be nice, I think we need a reasonable fix for 1.8.

Let's wait for @jaikiran 's opinion on this.

**Review by cescoffier — DISMISSED** [review]
I would be curious if it also fixes #11711

**Comment by cescoffier** [comment]
Sorry wrong button, please ignore the approval.

File: extensions/rest-client/runtime/src/main/java/io/quarkus/restclient/runtime/RestClientRecorder.java (hunk 1 above)
Comment (cescoffier) [reply extensions/rest-client/runtime/src/main/java/io/quarkus/restclient/runtime/RestClientRecorder.java:64]: Yes, we need to be sure it fixes the random ordering.

**Review by cescoffier — COMMENTED** [review]
I would be curious if it also fixes #11711

File: extensions/rest-client/runtime/src/main/java/io/quarkus/restclient/runtime/RestClientRecorder.java (hunk 1 above)
Comment (jaikiran) [reply extensions/rest-client/runtime/src/main/java/io/quarkus/restclient/runtime/RestClientRecorder.java:64]: So this change still leaves the chance for the ordering issue to occur. The order I'm talking about is as follows:

1. There are 2 separate extensions in play here - `quarkus-rest-client` and `quarkus-resteasy`.

2. Each of them have multiple build steps (which is fine). Both of these extensions, in one of their build steps "setup" a `@Recorder` of their own to call some method which ultimately leads to a call to `ResteasyProviderFactory.setInstance` method. In case of the `quarkus-rest-client` extension, the recorder in question is the `RestClientRecorder` and for `quarkus-resteasy` extension it is the `ResteasyStandaloneRecorder`. So far all is fine.

3. In Quarkus, these recorders get invoked upon application initialization. It so happens that the order in which these are recorders are invoked isn't deterministic (from what I saw). So a few times the `quarkus-resteasy` recorder might get invoked first and in some cases the `quarkus-rest-client` recorder might get invoked first. Ultimately, whichever recorder gets invoked last "wins" the call to `ResteasyProviderFactory.setInstance` by overwriting the instance.

This issue still exists with this change because if the `quarkus-rest-client` recorder gets invoked first it will peek and see that the `instance` is null (assuming no other extension within the Quarkus ecosystem ended up setting it). Since it is null, it will go ahead and set the instance to `clientProviderFactory`. Now next, after a while, the `quarkus-resteasy` recorder gets invoked its recorder ultimately invokes certain method which leads to[1] which will overwrite this instance, which was set by the `rest-client` recorder.
So the ordering issue remains. Having said that, to answer this:

> To my understanding, the only time there's a problem is when the server one is created first and the REST Client one clobbers it.
> I don't think the reverse situation poses any problems

I'm not too sure, because outside of the current issue, I don't have much idea about how resteasy behaves internally with these provider factory instances.

@gsmet, does ordering (via build item dependencies) of build steps (across extensions) also order their recorder execution?

[1] https://github.com/resteasy/Resteasy/blob/4.5.6.Final/resteasy-core/src/main/java/org/jboss/resteasy/core/ResteasyDeploymentImpl.java#L373

Comment (gsmet) [reply extensions/rest-client/runtime/src/main/java/io/quarkus/restclient/runtime/RestClientRecorder.java:64]: @jaikiran the recorder executions will be executed in the order they are recorded. So as soon as the build steps are properly ordered, it's going to work.

So, in conclusion, please make sure the build steps playing with `ResteasyProviderFactory` are executed in order via build items dependencies.

Comment (kenfinnigan) [reply extensions/rest-client/runtime/src/main/java/io/quarkus/restclient/runtime/RestClientRecorder.java:64]: @jaikiran I know what you've outlined. However, the server provider factory overriding the rest client created one is not actually an issue as far as I've seen.

In such a situation, the providers rest client needs are registered by the server provider factory, and rest client works as expected.

The only problem situation is when rest client overrides the server provider factory, which this PR solves

Comment (jaikiran) [reply extensions/rest-client/runtime/src/main/java/io/quarkus/restclient/runtime/RestClientRecorder.java:64]: > In such a situation, the providers rest client needs are registered by the server provider factory, and rest client works as expected.

Hello @kenfinnigan, that sounds fine to me then.

**Review by jaikiran — APPROVED** [review]

File: extensions/rest-client/runtime/src/main/java/io/quarkus/restclient/runtime/RestClientRecorder.java (hunk 1 above)
Comment (gsmet) [reply extensions/rest-client/runtime/src/main/java/io/quarkus/restclient/runtime/RestClientRecorder.java:64]: Again, I want to be sure we properly control the execution order.

@kenfinnigan I can do the work and push an additional commit to your PR if you don't think it's useful.

Comment (kenfinnigan) [reply extensions/rest-client/runtime/src/main/java/io/quarkus/restclient/runtime/RestClientRecorder.java:64]: I don't see it as necessary or useful

Comment (kenfinnigan) [reply extensions/rest-client/runtime/src/main/java/io/quarkus/restclient/runtime/RestClientRecorder.java:64]: To reiterate, with this change it's not necessary to control the execution order. And I'm looking to properly fix it in RESTEasy so this wouldn't be needed long term either.

I don't see the need to further complicate the code for a change that isn't permanent

Comment (gsmet) [reply extensions/rest-client/runtime/src/main/java/io/quarkus/restclient/runtime/RestClientRecorder.java:64]: > And I'm looking to properly fix it in RESTEasy so this wouldn't be needed long term either.

Yeah but that won't be for 1.8 and we need a fix now.

And I really think having a deterministic execution order for things that interact with each other is important.

If just for the sake of not spending hours debugging weird issues.

I think adding the build item should be very easy. I'll take a look tomorrow. Either it's easy and don't add boilerplate or I will give up.

Comment (kenfinnigan) [reply extensions/rest-client/runtime/src/main/java/io/quarkus/restclient/runtime/RestClientRecorder.java:64]: I know it won't be done for 1.8, but why add more code that needs to be removed when it's there in 1.9?

When the change is done in RESTEasy, there is no longer a need for a build item

**Comment by cescoffier** [comment]
@kenfinnigan can you re-enable the tests from #11711 and see how it behaves?

**Review by cescoffier — APPROVED** [review]

**Comment by kenfinnigan** [comment]
I've re-enabled that test as well, let's see what CI says

File: integration-tests/mongodb-panache/src/test/java/io/quarkus/it/mongodb/panache/reactive/ReactiveMongodbPanacheResourceTest.java [hunk 2]
```diff
@@ -43,7 +42,6 @@
 
 @QuarkusTest
 @QuarkusTestResource(MongoTestResource.class)
-@Disabled("See https://github.com/quarkusio/quarkus/issues/11711")
```
Comment (jaikiran) [inline integration-tests/mongodb-panache/src/test/java/io/quarkus/it/mongodb/panache/reactive/ReactiveMongodbPanacheResourceTest.java:46]: There's also `NativeMongodbPanacheResourceIT` in `integration-tests/mongodb-panache` which has been disabled for this same reason. That one needs to be re-enabled too, either in this PR or as a separate one.

Comment (kenfinnigan) [reply integration-tests/mongodb-panache/src/test/java/io/quarkus/it/mongodb/panache/reactive/ReactiveMongodbPanacheResourceTest.java:46]: Sorry, missed that, thought it was just the one.

I'm loathed to re-trigger the full CI build, can it be in a followup if this is ok?

Comment (jaikiran) [reply integration-tests/mongodb-panache/src/test/java/io/quarkus/it/mongodb/panache/reactive/ReactiveMongodbPanacheResourceTest.java:46]: > I'm loathed to re-trigger the full CI build, 

Same here.

> can it be in a followup if this is ok?

I think that's OK since if this re-enabled regular test passes, it's almost guaranteed the native one too will, given the context of this issue. So we just need to see how this one goes.
