### PR TITLE
Handle trailing/leading spaces in all relevant datasource configuration properties

### LINKED ISSUE #39395: Invalid warnings about SQL Server version "0.0.0" on startup
### Describe the bug

In certain circumstances, Hibernate ORM issues a warning about an unsupported SQL Server version "0.0.0"

### Expected behavior

No warning when using `quarkus.datasource.db-version=14`  with Quarkus 3.8.

### Actual behavior

A weird warning when using `quarkus.datasource.db-version=14`  with Quarkus 3.8:

```
2024-03-13 11:43:03,217 WARN [org.hib.dia.Dialect] (Quarkus Main Thread) HHH000511: The 0.0.0 version for [org.hibernate.dialect.SQLServerDialect] is no longer supported, hence certain features may not work properly. The minimum supported version is 11.0.0. Check the community dialects project for available legacy versions.
```

Note the warning comes from Hibernate ORM, not from Quarkus.

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

See https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Compatibility.20mode.20for.20hibernate/near/426307824

Note the warning comes from Hibernate ORM, not from Quarkus.

### PR DESCRIPTION
**Pull request by yrodiere**
Fixes #39395 

I didn't change the converter for:

* `username`/`password` for devservices, because @gsmet specifically avoided doing that for the non-devservice `username`/`password` in a previous PR: https://github.com/quarkusio/quarkus/commit/bfabc1c06609c99115cb4dc78a73c96c6f3c2df9
* Paths, because who knows what weird paths people use
* `Map<String,String>` config, e.g. properties, environment variables, volumes, for the same reason

I'm on the fence for `command`. I can drop it if you want.

### CODE REVIEW

File: extensions/datasource/runtime/src/main/java/io/quarkus/datasource/runtime/DevServicesBuildTimeConfig.java [hunk 1]
```diff
@@ -57,6 +60,7 @@ public interface DevServicesBuildTimeConfig {
      * <p>
      * This has no effect if the provider is not a container-based database, such as H2 or Derby.
      */
+    @WithConverter(TrimmedStringConverter.class)
     Optional<String> command();
```
Comment (gsmet) [inline extensions/datasource/runtime/src/main/java/io/quarkus/datasource/runtime/DevServicesBuildTimeConfig.java:64]: I think it should be fine. We can do it and see if people complain.

**Review by gsmet — APPROVED** [review]
