### PR TITLE
Small Dev UI Fixes

### LINKED ISSUE #23498: Add support for Test source in open in IDE in DEV UI
### Description

At the moment, you can open in source from DEV, but test source is not supported. Add test source.

### Implementation ideas

_No response_

### LINKED ISSUE #23500: Open in IDE not going to the source
### Describe the bug

The "open in IDE" only opens the IDE but does not navigate to the source file in question. This might be IntilliJ specific.

### Expected behavior

Open the correct file and navigate to the correct line

### Actual behavior

just open the IDE

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by phillip-kruger**
This PR fix some small issues in Dev UI:

Fix #23498 (Test source in Dev UI)
Fix #23500 (Although this might still be an issue on Mac)

Also added to open in at least one IDE if multiple is running
Also removed un-linkable source that was made a link in Dev UI

Here the test source opening:
test_source

### CODE REVIEW

**Review by geoand — APPROVED** [review]

File: core/deployment/src/main/java/io/quarkus/deployment/ide/Ide.java [hunk 1]
```diff
@@ -18,7 +18,7 @@
     IDEA("idea", List.of("--line", "{lineNumber}", "{fileName}"), List.of("--help")),
     ECLIPSE("eclipse", List.of("--launcher.openFile", "{fileName}:{lineNumber}"), Collections.emptyList()),
     VSCODE("code", List.of("--goto", "{fileName}:{lineNumber}"), List.of("--version")),
-    NETBEANS("netbeans", Collections.emptyList(), List.of("--help"));
+    NETBEANS("netbeans", List.of("{fileName}:{lineNumber}"), List.of("--help"));
```
Comment (gsmet) [inline core/deployment/src/main/java/io/quarkus/deployment/ide/Ide.java:21]: Ah thanks! I wasn't sure what the format was.
