### PR TITLE
Hibernate Reactive session and connection leaks

### LINKED ISSUE #10015: Hibernate Reactive: sessions are not closed, connections leak
ATM, we have the following method to produce `Stage.Session` and `Mutiny.Session` tied to the request scope:

```java
package io.quarkus.hibernate.reactive.runtime;

import java.util.concurrent.CompletionStage;

import javax.enterprise.context.ApplicationScoped;
import javax.enterprise.context.RequestScoped;
import javax.enterprise.inject.Disposes;
import javax.enterprise.inject.Produces;
import javax.inject.Inject;

import org.hibernate.reactive.mutiny.Mutiny;
import org.hibernate.reactive.stage.Stage;

import io.quarkus.arc.DefaultBean;
import io.smallrye.mutiny.Uni;

@ApplicationScoped
public class ReactiveSessionProducer {

    @Inject
    private Stage.SessionFactory reactiveSessionFactory;

    @Inject
    private Mutiny.SessionFactory mutinySessionFactory;

    @Produces
    @RequestScoped
    @DefaultBean
    public CompletionStage<Stage.Session> stageSession() {
        return reactiveSessionFactory.openSession();
    }

    @Produces
    @RequestScoped
    @DefaultBean
    public Uni<Mutiny.Session> mutinySession() {
        return mutinySessionFactory.openSession();
    }

    public void disposeStageSession(@Disposes CompletionStage<Stage.Session> reactiveSession) {
        reactiveSession.whenComplete((s, t) -> {
            if (s != null)
                s.close();
        });
    }

    public void disposeMutinySession(@Disposes Uni<Mutiny.Session> reactiveSession) {
        // TODO: @AGG this is not working, need to check w/ Clement to figure out the proper way
        reactiveSession.on().termination((session, ex, cancelled) -> {
            if (session != null)
                session.close();
        });
    }

}
```

Now, the problem is that we're tying a `CompletionStage<Stage.Session>` (and respectively same for Mutiny) to the request, which is a promise of a session.

The `disposeStageSession` cannot work, because `CompletionStage` are immutable, and the value returned by `reactiveSession.whenComplete()` is never used, so this `s.close()` will never be called.

A similar issue exists for `disposeMutinySession` except it's possible that the `Uni<Mutiny.Session>` opens a new session for each call to `subscribe` (unless `cache()` is called on it, I don't know if it is) whereas for `CompletionStage` it's eager and will have a single session by design.

We can't do `whenComplete`/`on().termination` in `stageSession`/`mutinySession` either because that would close the session before we return it to the user.

To be frank, ATM I don't know how to register a way to auto-close what is lazily obtained by a CS/Uni and tied to the request scope.

### PR DESCRIPTION
**Pull request by tsegismont**
Fixes #10015

### CODE REVIEW

**Comment by tsegismont** [comment]
cc @FroMage cc @aguibert

**Comment by FroMage** [comment]
Related to #10015

**Review by FroMage — APPROVED** [review]

**Comment by tsegismont** [comment]
@gsmet @FroMage please do not merge yet. I will push more changes to this PR, including the fix for #10015

**Comment by tsegismont** [comment]
@FroMage @aguibert PTAL

In the producer, the mutiny session `Uni` item must be cached because we don't want to create a session anytime someone subscribes to the `Uni`.

In tests, connection borrowed from the pool is never returned after the DB is populated.

File: extensions/hibernate-reactive/runtime/src/main/java/io/quarkus/hibernate/reactive/runtime/ReactiveSessionProducer.java [hunk 1]
```diff
@@ -34,7 +34,7 @@
     @RequestScoped
     @DefaultBean
     public Uni<Mutiny.Session> mutinySession() {
-        return mutinySessionFactory.openSession();
+        return mutinySessionFactory.openSession().cache();
```
Comment (FroMage) [inline extensions/hibernate-reactive/runtime/src/main/java/io/quarkus/hibernate/reactive/runtime/ReactiveSessionProducer.java:37]: I think this is a justifiable limitation of the `Uni<Mutiny.Session>` functionality, because `CompletionStage<Stage.Session>` behaves in the same way, so we make it cached and use the same session in the entire request.

File: extensions/hibernate-reactive/runtime/src/main/java/io/quarkus/hibernate/reactive/runtime/ReactiveSessionProducer.java [hunk 2]
```diff
@@ -45,11 +45,7 @@ public void disposeStageSession(@Disposes CompletionStage<Stage.Session> reactiv
     }
 
     public void disposeMutinySession(@Disposes Uni<Mutiny.Session> reactiveSession) {
-        // TODO: @AGG this is not working, need to check w/ Clement to figure out the proper way
-        reactiveSession.on().termination((session, ex, cancelled) -> {
-            if (session != null)
-                session.close();
-        });
+        reactiveSession.subscribe().with(Mutiny.Session::close);
```
Comment (FroMage) [inline extensions/hibernate-reactive/runtime/src/main/java/io/quarkus/hibernate/reactive/runtime/ReactiveSessionProducer.java:48]: At this point it could be interesting to figure out if the `reactiveSession` has already been subscribed to, because if not, it will never have been produced and doesn't need to be closed. We might be creating it just to close it.
But I'm pretty sure that the current implementation is based on `CompletionStage` so it's eager and will always be created, so we can forget this optimisation for now.

**Review by FroMage — APPROVED** [review]

**Review by aguibert — APPROVED** [review]

**Comment by FroMage** [comment]
CI failed with error that is a bit weird, because it is related to SSL and vertx, but not to this particular PR in theory:

```
2020-06-15T21:43:56.7706037Z Caused by: java.lang.LinkageError: loader io.quarkus.bootstrap.runner.RunnerClassLoader @66048bfd attempted duplicate class definition for io.vertx.core.net.impl.SSLHelper. (io.vertx.core.net.impl.SSLHelper is in unnamed module of loader io.quarkus.bootstrap.runner.RunnerClassLoader @66048bfd, parent loader 'app')
2020-06-15T21:43:56.7708527Z 	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
2020-06-15T21:43:56.7710770Z 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
2020-06-15T21:43:56.7713268Z 	at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:79)
2020-06-15T21:43:56.7715686Z 	at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:44)
2020-06-15T21:43:56.7718259Z 	at io.vertx.core.http.impl.HttpServerImpl.<init>(HttpServerImpl.java:93)
2020-06-15T21:43:56.7720769Z 	at io.vertx.core.impl.VertxImpl.createHttpServer(VertxImpl.java:310)
2020-06-15T21:43:56.7723388Z 	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.start(VertxHttpRecorder.java:759)
2020-06-15T21:43:56.7725311Z 	at io.vertx.core.Verticle.start(Verticle.java:66)
2020-06-15T21:43:56.7727722Z 	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$9(DeploymentManager.java:556)
2020-06-15T21:43:56.7730263Z 	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
2020-06-15T21:43:56.7733198Z 	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
2020-06-15T21:43:56.7736078Z 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
2020-06-15T21:43:56.7738859Z 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
2020-06-15T21:43:56.7741256Z 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
2020-06-15T21:43:56.7744281Z 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
2020-06-15T21:43:56.7747935Z 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2020-06-15T21:43:56.7750831Z 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2020-06-15T21:43:56.7753149Z 	at java.base/java.lang.Thread.run(Thread.java:834)
```

I've restarted it.

File: extensions/hibernate-reactive/runtime/src/main/java/io/quarkus/hibernate/reactive/runtime/ReactiveSessionProducer.java (hunk 1 above)
Comment (tsegismont) [reply extensions/hibernate-reactive/runtime/src/main/java/io/quarkus/hibernate/reactive/runtime/ReactiveSessionProducer.java:37]: It is not a limitation, it is a bug fix :smile: 

The purpose of a request scoped session producer is to have a single session for the request. But if you don't add the `cache` operator, another session will be created anytime someone subscribes to the `Uni` that is injected in the users `beans`.

File: extensions/hibernate-reactive/runtime/src/main/java/io/quarkus/hibernate/reactive/runtime/ReactiveSessionProducer.java (hunk 2 above)
Comment (tsegismont) [reply extensions/hibernate-reactive/runtime/src/main/java/io/quarkus/hibernate/reactive/runtime/ReactiveSessionProducer.java:48]: Keep in mind that when you inject the stage version of the session, it will be eagerly created. So the Mutiny version is not less efficient.

I had a look at the session implementation code. It seems that a connection is acquired as soon as the session is created. Perhaps this should be delayed until a connection is actually needed. But I don't know if this is possible in practice.

**Comment by tsegismont** [comment]
@FroMage how did you get the logs? I browsed to https://github.com/quarkusio/quarkus/pull/10016/checks?check_run_id=775744706 and https://github.com/quarkusio/quarkus/pull/10016/checks?check_run_id=775744722 but the Maven build step logs are unavailable to me.

**Comment by FroMage** [comment]
Top right corner of the big black box, click on the `...`

**Comment by tsegismont** [comment]
I tried that but  `Build with Maven` logs are not present in the archive.

**Comment by FroMage** [comment]
I click on "View raw logs"

**Comment by tsegismont** [comment]
:crying_cat_face: sorry, the only thing I get when I do it is:

```
2020-06-16T08:30:21.2743093Z ##[section]Starting: Request a runner to run this job
2020-06-16T08:30:21.6630999Z Can't find any online and idle self-hosted runner in current repository that matches the required labels: 'ubuntu-latest'
2020-06-16T08:30:21.6631044Z Can't find any online and idle self-hosted runner in current repository's account/organization that matches the required labels: 'ubuntu-latest'
2020-06-16T08:30:21.6631090Z Can't find any online and idle hosted runner in current repository's account/organization that matches the required labels: 'ubuntu-latest'
2020-06-16T08:30:21.6631250Z Found online and busy hosted runners in current repository's account/organization that matches the required labels: 'ubuntu-latest'. Waiting for one of them to get assigned for this job.
2020-06-16T08:30:21.9516064Z ##[section]Finishing: Request a runner to run this job
```

**Comment by FroMage** [comment]
Well OK that's the new issue. This is a pure CI failure. I heard that `master` has a fix for that. Can you rebase?

**Comment by tsegismont** [comment]
@FroMage done 🤞

File: extensions/hibernate-reactive/runtime/src/main/java/io/quarkus/hibernate/reactive/runtime/ReactiveSessionProducer.java (hunk 1 above)
Comment (aguibert) [reply extensions/hibernate-reactive/runtime/src/main/java/io/quarkus/hibernate/reactive/runtime/ReactiveSessionProducer.java:37]: so even if the uni gets subscribed to twice in the same request, that would trigger two different sessions by default? That seems rather confusing, but perhaps necessary since a subscription could happen after the original request has completed?

Comment (FroMage) [reply extensions/hibernate-reactive/runtime/src/main/java/io/quarkus/hibernate/reactive/runtime/ReactiveSessionProducer.java:37]: Well, with `.cache` you would in fact get the same session, which is what makes the most sense in this context.

**Comment by FroMage** [comment]
Failure is in Scala test in Windows: unrelated. Let's merge.
