### PR TITLE
Generate a substitution for the usage of MethodHandle in kafka-client

### LINKED ISSUE #2914: Java 11+GraalVM: Kafka Crc32C uses method handle
**Describe the bug**
The `org.apache.kafka.common.utils.Crc32C` class is using a method handle under Java 9+ to access the public constructor of `java.util.zip.CRC32C`; this fails with `native-image`.

Ideally the Kafka library would utilize a multi-release JAR to just call the constructor directly instead of resorting to reflection to solve this issue.  Failing that, we should just do it ourselves using a MR-JAR substitution.

### PR DESCRIPTION
**Pull request by dmlloyd**
Fixes #2914

### CODE REVIEW

File: extensions/kafka-client/deployment/src/main/java/io/quarkus/kafka/client/deployment/KafkaProcessor.java [hunk 1]
```diff
@@ -91,4 +98,35 @@ public void build(CombinedIndexBuildItem indexBuildItem, BuildProducer<Reflectiv
...
+            cc.addAnnotation("com/oracle/svm/core/annotate/TargetClass").addValue("className",
+                    "org.apache.kafka.common.utils.Crc32C$Java9ChecksumFactory");
+            cc.addAnnotation("com/oracle/svm/core/annotate/Substitute");
+
+            try (MethodCreator mc = cc.getMethodCreator("create", Checksum.class)) {
+                mc.addAnnotation("com/oracle/svm/core/annotate/Substitute");
+                mc.returnValue(mc.newInstance(MethodDescriptor.ofConstructor("java.util.zip.CRC32C")));
+            }
+        }
+        return new GeneratedClassBuildItem(false, TARGET_JAVA_9_CHECKSUM_FACTORY, holder[0]);
```
Comment (gsmet) [inline extensions/kafka-client/deployment/src/main/java/io/quarkus/kafka/client/deployment/KafkaProcessor.java]: I might be missing the obvious but I don't understand why you need to generate the class?

Comment (dmlloyd) [reply extensions/kafka-client/deployment/src/main/java/io/quarkus/kafka/client/deployment/KafkaProcessor.java]: Because we build with Java 8, so we can't directly reference the class.  It was either this or switching from `MethodHandle` to reflection; this seemed the better choice.

Once we switch to Java 11 as a baseline, we can replace this with a trivial substitution class in the runtime module instead.

Comment (dmlloyd) [reply extensions/kafka-client/deployment/src/main/java/io/quarkus/kafka/client/deployment/KafkaProcessor.java]: This wouldn't be necessary at all if the upstream project just built an MR-jar.

Comment (gsmet) [reply extensions/kafka-client/deployment/src/main/java/io/quarkus/kafka/client/deployment/KafkaProcessor.java]: Even with a `TargetClass#onlyWith` checking that the class exists?

Comment (dmlloyd) [reply extensions/kafka-client/deployment/src/main/java/io/quarkus/kafka/client/deployment/KafkaProcessor.java]: It doesn't matter what annotations I use; if I try to reference `java.util.zip.CRC32C` and then build with Java 8, it's a compile error.  The class wasn't added until Java 9.

Comment (gsmet) [reply extensions/kafka-client/deployment/src/main/java/io/quarkus/kafka/client/deployment/KafkaProcessor.java]: Ah OK, sorry, I thought it was the substituted class that was a problem.

**Review by gsmet — APPROVED** [review]
