### PR TITLE
Ignore the default import.sql when specifying a different file

### LINKED ISSUE #49075: Spring Data:  `quarkus.hibernate-orm.sql-load-script` is run twice after 47338 PR got merged
### Describe the bug

I use `quarkus.hibernate-orm.sql-load-script=import.sql` in my Spring Data application and it seems that when https://github.com/quarkusio/quarkus/pull/47338 got merged, the script is run more than once, otherwise I don't understand the error messages.

### Expected behavior

Works as before.

### Actual behavior

I can see logged: 

```
19:59:19,688 INFO  [app] 19:59:18,915 GenerationTarget encountered exception accepting command : Error executing DDL "INSERT INTO address(id, zipCode) VALUES (1, '28080')" via JDBC [ERROR: duplicate key value violates unique constraint "address_pkey"
19:59:19,688 INFO  [app]   Detail: Key (id)=(1) already exists.]: org.hibernate.tool.schema.spi.CommandAcceptanceException: Error executing DDL "INSERT INTO address(id, zipCode) VALUES (1, '28080')" via JDBC [ERROR: duplicate key value violates unique constraint "address_pkey"
19:59:19,688 INFO  [app]   Detail: Key (id)=(1) already exists.]
19:59:19,688 INFO  [app] 	at org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.accept(GenerationTargetToDatabase.java:93)
19:59:19,689 INFO  [app] 	at org.hibernate.tool.schema.internal.Helper.applySqlString(Helper.java:221)
19:59:19,689 INFO  [app] 	at org.hibernate.tool.schema.internal.Helper.applyScript(Helper.java:244)
19:59:19,689 INFO  [app] 	at org.hibernate.tool.schema.internal.AbstractSchemaPopulator.applyImportFiles(AbstractSchemaPopulator.java:150)
19:59:19,689 INFO  [app] 	at org.hibernate.tool.schema.internal.AbstractSchemaPopulator.applyImportSources(AbstractSchemaPopulator.java:58)
19:59:19,689 INFO  [app] 	at org.hibernate.tool.schema.internal.SchemaCreatorImpl.performCreation(SchemaCreatorImpl.java:172)
19:59:19,689 INFO  [app] 	at org.hibernate.tool.schema.internal.SchemaCreatorImpl.doCreation(SchemaCreatorImpl.java:130)
19:59:19,690 INFO  [app] 	at org.hibernate.tool.schema.internal.SchemaCreatorImpl.doCreation(SchemaCreatorImpl.java:106)
19:59:19,690 INFO  [app] 	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:237)
19:59:19,690 INFO  [app] 	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.lambda$process$5(SchemaManagementToolCoordinator.java:142)
19:59:19,690 INFO  [app] 	at java.base/java.util.HashMap.forEach(HashMap.java:1429)
19:59:19,690 INFO  [app] 	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:139)
19:59:19,691 INFO  [app] 	at io.quarkus.hibernate.orm.runtime.observers.SessionFactoryObserverForSchemaExport.sessionFactoryCreated(SessionFactoryObserverForSchemaExport.java:21)
19:59:19,691 INFO  [app] 	at org.hibernate.internal.SessionFactoryObserverChain.sessionFactoryCreated(SessionFactoryObserverChain.java:33)
19:59:19,691 INFO  [app] 	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:350)
19:59:19,691 INFO  [app] 	at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:92)
19:59:19,691 INFO  [app] 	at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.createEntityManagerFactory(FastBootHibernatePersistenceProvider.java:74)
19:59:19,692 INFO  [app] 	at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:90)
19:59:19,692 INFO  [app] 	at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:66)
19:59:19,693 INFO  [app] 	at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:165)
19:59:19,694 INFO  [app] 	at io.quarkus.hibernate.orm.runtime.JPAConfig$1.run(JPAConfig.java:61)
19:59:19,694 INFO  [app] 	at java.base/java.lang.Thread.run(Thread.java:1583)
```

### How to Reproduce?

Reproducer:

1. `git clone git@github.com:quarkus-qe/quarkus-test-suite.git`
2. `cd quarkus-test-suite/spring/spring-data`
3. `mvn clean verify -Dit.test=PagingAndSortingRepositoryRestResourceIT#create`

### Output of `uname -a` or `ver`

Fedora 41, Ubuntu latest

### Output of `java -version`

Temurin 21 and 17

### Quarkus version or git rev

999-SNAPSHOT

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.9.9

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by yrodiere**
This fixes a regression caused by the switch from `hibernate.hbm2ddl.import_files` to `jakarta.persistence.sql-load-script-source` #46789 

* Fixes #49075

### CODE REVIEW

File: extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/util/HibernateProcessorUtil.java [hunk 1]
```diff
@@ -4,14 +4,7 @@
...
 import java.nio.file.Path;
-import java.util.Collections;
-import java.util.List;
-import java.util.Locale;
-import java.util.Map;
-import java.util.Optional;
-import java.util.OptionalInt;
-import java.util.Properties;
-import java.util.Set;
+import java.util.*;
```
Comment (geoand) [inline extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/util/HibernateProcessorUtil.java]: Star import :)

Comment (yrodiere) [reply extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/util/HibernateProcessorUtil.java]: Sorry, new IDEA setup... Will fix.

**Review by gsmet — APPROVED** [review]
