### PR TITLE
Arc - make sure exceptions from async events are always among suppressed exceptions and alter existing test to assert that

### LINKED ISSUE #24646: Async Events behave inconsistently on Exceptions
### Describe the bug

If an event is fired (and observed) asynchronously, the returned CompletionStage behaves differently in the case of exceptions depending on the number of observers that threw exceptions. This violates the [CDI Spec, 10.5.1](https://jakarta.ee/specifications/cdi/3.0/jakarta-cdi-spec-3.0.html#async_exception).

### Expected behavior

Both test methods should be green.

### Actual behavior

The test case  `testSingleFailure` fails, because the `CompletionStage` contains the `IllegalArgumentException` directly instead of a `CompletionException` containing the `IllegalArgumentException` as the spec requires.

```
java.lang.AssertionError: 
Expecting actual throwable to be an instance of:
  java.util.concurrent.CompletionException
but was:
  java.lang.IllegalArgumentException
	at com.example.EventTest$Observer1.failOn42And47(EventDecoratorTest.java:71)
	at com.example.EventTest_Observer1_Observer_failOn42And47_df18bd4f87120ec5a98ebc09b259d85482e10edc.notify(Unknown Source)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:320)
	...(10 remaining lines not displayed - this can be changed with Assertions.setMaxStackTraceElementsDisplayed)

	at com.example.EventTest.testSingleFailure(EventDecoratorTest.java:43)
```

### How to Reproduce?

```
// imports

@QuarkusTest
class EventTest {

    @Inject
    Observer1 observer1;

    @Inject
    Observer2 observer2;

    @Inject
    Event<Integer> event;

    @Test
    void testSingleFailure() throws InterruptedException, TimeoutException {
        final CompletionStage<Integer> stage = event.fireAsync(42);

        try {
            stage.toCompletableFuture().get(30, TimeUnit.SECONDS);
            failBecauseExceptionWasNotThrown(ExecutionException.class);
        } catch (ExecutionException ex) {
            assertThat(ex.getCause()).isInstanceOf(CompletionException.class)
                    .extracting(Throwable::getSuppressed, as(ARRAY))
                    .hasSize(1)
                    .hasAtLeastOneElementOfType(IllegalArgumentException.class);
        }
    }

    @Test
    void testTwoFailures() throws InterruptedException, TimeoutException {
        final CompletionStage<Integer> stage = event.fireAsync(47);

        try {
            stage.toCompletableFuture().get(30, TimeUnit.SECONDS);
            failBecauseExceptionWasNotThrown(ExecutionException.class);
        } catch (ExecutionException ex) {
            assertThat(ex.getCause()).isInstanceOf(CompletionException.class)
                    .extracting(Throwable::getSuppressed, as(ARRAY))
                    .hasSize(2)
                    .hasAtLeastOneElementOfType(IllegalArgumentException.class)
                    .hasAtLeastOneElementOfType(IllegalStateException.class);
        }
    }

    @ApplicationScoped
    static class Observer1 {

        void failOn42And47(@ObservesAsync int value) {
            if (value == 42 || value == 47) {
                throw new IllegalArgumentException();
            }
        }
    }

    @ApplicationScoped
    static class Observer2 {

        void failOn47(@ObservesAsync int value) {
            if (value == 47) {
                throw new IllegalStateException();
            }
        }
    }
}
```

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

11.0.11, vendor: AdoptOpenJDK, runtime: C:\Program Files\AdoptOpenJDK\jdk-11.0.11.9-hotspot

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.7.5.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by manovotn**
Fixes #24646

This behavior is equivalent to what Weld does and should capture that specification expects.

### CODE REVIEW

File: independent-projects/arc/tests/src/test/java/io/quarkus/arc/test/observers/async/AsyncObserverExceptionTest.java [hunk 1]
```diff
@@ -31,19 +32,28 @@
...
 
         Object exception = synchronizer.poll(10, TimeUnit.SECONDS);
+
+        // assert suppressed exception is always present
+        assertEquals(1, suppressed.size());
+        assertTrue(suppressed.get(0) instanceof RuntimeException);
+
+        // assert actual cause, always a CompletionException
         assertNotNull(exception);
+        assertTrue(exception instanceof CompletionException);
```
Comment (mkouba) [inline independent-projects/arc/tests/src/test/java/io/quarkus/arc/test/observers/async/AsyncObserverExceptionTest.java:56]: I believe that the assertion on the next line should verify the cause instead, i.e. `assertTrue(exception.getCause() instanceof RuntimeException);`

Comment (manovotn) [reply independent-projects/arc/tests/src/test/java/io/quarkus/arc/test/observers/async/AsyncObserverExceptionTest.java:56]: True, in case of single exception this is correct.
I will actually also add a test for multiple exceptions thanks for the remainder.

**Comment by manovotn** [comment]
@mkouba added test for multiple exception and both tests are now asserting the cause of `CompletionException`. That should hopefully cover all cases :)

**Review by mkouba — APPROVED** [review]
