### PR TITLE
Only expose the Dev UI Routes if Vert.x HTTP is present

### LINKED ISSUE #33804: Dev Mode fails with Quarkus 3.1 and Kafka client (no vert.x http extension on the classpath)
### Describe the bug

When starting devservices with `io.quarkus:quarkus-kafka-client:3.1.0.Final`, I get this error:

```
2023-06-02 22:48:36,647 INFO  [io.qua.kaf.cli.dep.DevServicesKafkaProcessor] (build-24) Dev Services for Kafka started. Other Quarkus applications in dev mode will find the broker automatically. For Quarkus applications in production mode, you can connect to this by starting your application with -Dkafka.bootstrap.servers=OUTSIDE://localhost:32769
2023-06-02 22:48:36,832 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile [dev]): java.lang.ClassNotFoundException: io.vertx.core.Handler
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:516)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:466)
	at io.quarkus.deployment.steps.KafkaProcessor$registerKafkaUiExecHandler1228376192.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.KafkaProcessor$registerKafkaUiExecHandler1228376192.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:104)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

To reproduce is simple. Create a Quarkus 3 project, add `io.quarkus:quarkus-kafka-client` extension.
Run the app in devMode.

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by cescoffier**
Fix https://github.com/quarkusio/quarkus/issues/33804

### CODE REVIEW

File: extensions/kafka-client/deployment/src/main/java/io/quarkus/kafka/client/deployment/KafkaProcessor.java [hunk 1]
```diff
@@ -561,14 +561,17 @@ public AdditionalBeanBuildItem kafkaClientBeans() {
...
+            Capabilities capabilities,
             BuildProducer<DevConsoleRouteBuildItem> routeProducer,
             KafkaUiRecorder recorder) {
-        routeProducer.produce(DevConsoleRouteBuildItem.builder()
-                .method("POST")
-                .handler(recorder.kafkaControlHandler())
-                .path(KAFKA_ADMIN_PATH)
-                .bodyHandlerRequired()
-                .build());
+        if (capabilities.isPresent("io.quarkus.vertx.http")) {
```
Comment (ozangunalp) [inline extensions/kafka-client/deployment/src/main/java/io/quarkus/kafka/client/deployment/KafkaProcessor.java:567]: There is a `Capability.VERTX_HTTP`

**Review by ozangunalp — CHANGES_REQUESTED** [review]

File: extensions/kafka-client/deployment/src/main/java/io/quarkus/kafka/client/deployment/KafkaProcessor.java (hunk 1 above)
Comment (cescoffier) [reply extensions/kafka-client/deployment/src/main/java/io/quarkus/kafka/client/deployment/KafkaProcessor.java:567]: Yes, but didn't find where/how it's exposed - there is nothing in the Vert.x HTTP extension.

@geoand any idea? Is it safe to provide and reuse this one, or was it intended for another purpose?

Comment (geoand) [reply extensions/kafka-client/deployment/src/main/java/io/quarkus/kafka/client/deployment/KafkaProcessor.java:567]: Capabilities get "produced" by the configuration of the Maven plugin since they need to be present before the Quarkus build system determined the processing graph.

Comment (cescoffier) [reply extensions/kafka-client/deployment/src/main/java/io/quarkus/kafka/client/deployment/KafkaProcessor.java:567]: Yes, but normally, it's declared in the extension descriptor, and it's not in this case.

Comment (cescoffier) [reply extensions/kafka-client/deployment/src/main/java/io/quarkus/kafka/client/deployment/KafkaProcessor.java:567]: Ok, found it, it's in the maven plug-in configuration.

Comment (cescoffier) [reply extensions/kafka-client/deployment/src/main/java/io/quarkus/kafka/client/deployment/KafkaProcessor.java]: All fixed!

**Review by ozangunalp — APPROVED** [review]

**Comment by zbendhiba** [comment]
Many thanks for the fix !
