### PR TITLE
Handle new format of used_classes_* reports in GraalVM for JDK 24

### LINKED ISSUE #41917: PostgresQL IT tests failing with Mandrel 24.2 (for JDK 24)
### Describe the bug

Integration tests:

* JPA - PostgreSQL
* JPA - PostgreSQL with XML 

fail with the latest mandrel builds (for JDK 24)

### Expected behavior

Tests should pass

### Actual behavior

```
 Error:  Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 3.111 s <<< FAILURE! -- in io.quarkus.it.jpa.postgresql.JPAFunctionalityInGraalITCase
Error:  io.quarkus.it.jpa.postgresql.JPAFunctionalityInGraalITCase.verifyJdkXmlParsersHavebeenEcludedFromNative -- Time elapsed: 0.083 s <<< FAILURE!
org.opentest4j.AssertionFailedError: Type 'org.postgresql.jdbc.PgSQLXML' was not found in the report in target/quarkus-integration-test-jpa-postgresql-999-SNAPSHOT-native-image-source-jar/reports/used_classes_quarkus-integration-test-jpa-postgresql-999-SNAPSHOT-runner_20240716_005849.txt
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:38)
	at org.junit.jupiter.api.Assertions.fail(Assertions.java:138)
	at io.quarkus.test.junit.nativeimage.ClassInclusionReport.assertContains(ClassInclusionReport.java:59)
	at io.quarkus.test.junit.nativeimage.ClassInclusionReport.assertContains(ClassInclusionReport.java:49)
	at io.quarkus.it.jpa.postgresql.JPAFunctionalityInGraalITCase.verifyJdkXmlParsersHavebeenEcludedFromNative(JPAFunctionalityInGraalITCase.java:21)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestMethod(QuarkusTestExtension.java:812)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

See https://github.com/graalvm/mandrel/actions/runs/9948658053/job/27484292339

### How to Reproduce?

```
./mvnw -Dnative -pl integration-tests/jpa-postgresql-withxml,integration-tests/jpa-postgresql -Dnative.surefire.skip -Dformat.skip -Dno-descriptor-tests clean package
```

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Mandrel or GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by zakkak**
Starting with GraalVM for JDK 24 the format of the report has changed
prefixing each line with the class loader name and a colon, e.g.:

GraalVM for JDK 22 (and 23 which is not released yet):
```
org.postgresql.jdbc.PgSQLXML
```

GraalVM for JDK 24:
```
com.oracle.svm.hosted.NativeImageClassLoader:org.postgresql.jdbc.PgSQLXML
```

See https://github.com/oracle/graal/commit/1d769c7ffe3fec32a6738ba96d803bf06cf9f444#diff-01f83a129b979abfb9acd79deb25f1db51df940f9d4ca968c301cd9718bf627bR347

Closes https://github.com/quarkusio/quarkus/issues/41917

### CODE REVIEW

File: test-framework/junit5/src/main/java/io/quarkus/test/junit/nativeimage/ClassInclusionReport.java [hunk 1]
```diff
@@ -37,7 +37,10 @@ public static ClassInclusionReport load() {
         TreeSet<String> set = new TreeSet<>();
         try (Scanner scanner = new Scanner(usedClassesReport.toFile())) {
             while (scanner.hasNextLine()) {
-                set.add(scanner.nextLine());
+                // Starting with GraalVM for JDK 24 the format of the report has changed prefixing each line with
+                // the class loader name and a colon. We need to strip that part.
+                String[] line = scanner.nextLine().split(":");
+                set.add(line[line.length - 1]);
```
Comment (gsmet) [inline test-framework/junit5/src/main/java/io/quarkus/test/junit/nativeimage/ClassInclusionReport.java:43]: Given the comment, I would rather use `indexOf()` and `substring()`? Or you are absolutely sure there won't be any other colon?

**Review by gsmet — COMMENTED** [review]
Ah nice to have it handled before we switch to it!

I added a small question.

File: test-framework/junit5/src/main/java/io/quarkus/test/junit/nativeimage/ClassInclusionReport.java (hunk 1 above)
Comment (zakkak) [reply test-framework/junit5/src/main/java/io/quarkus/test/junit/nativeimage/ClassInclusionReport.java:43]: For the time being it's at most one colon, something like `[<classloader>:]<classname>`, that's why I went for the simplest approach. If more colons show up in the future it will still work as long as the classname still appears last in the sequence (and the classname can't contain a colon). If something gets added after the classname then the test will break and we will notice.

I don't think it's worth "validating" the file's format, at least not for the time being.

**Review by gsmet — APPROVED** [review]
Let's merge then, thanks for the confirmation!
