### PR TITLE
Fix combination of @QuarkusMain and Kotlin native application

### LINKED ISSUE #29754: Kotlin QuarkusMain native build does not work
### Describe the bug

Hello,

I have a main application class and want to compile everything in native mode.

### Main Class

```kotlin
package com.github

import io.quarkus.runtime.Quarkus.run
import io.quarkus.runtime.annotations.QuarkusMain

@QuarkusMain
class GreetingApplication

fun main(args: Array<String>) {
    run(*args)
}
```

during initializing phase it breaks with the following exception:

```
./gradlew build -Dquarkus.package.type=native

.
.
.

========================================================================================================================
GraalVM Native Image: Generating 'quarkus-kotlin-native-1.0.0-SNAPSHOT-runner' (executable)...
========================================================================================================================
[1/7] Initializing...                                                                                    (0.0s @ 0.15GB)
Error: Method 'com.github.GreetingApplication.main' is declared as the main entry point but it can not be found. Make sure that class 'com.github.GreetingApplication' is on the classpath and that method 'main(String[])' exists in that class.
com.oracle.svm.core.util.UserError$UserException: Method 'com.github.GreetingApplication.main' is declared as the main entry point but it can not be found. Make sure that class 'com.github.GreetingApplication' is on the classpath and that method 'main(String[])' exists in that class.
 
```

### Expected behavior

native build works also with a kotlin main class

### Actual behavior

Build breaks during Initialization Phase with this error message:

[1/7] Initializing...                                                                                    (0.0s @ 0.15GB)
Error: Method 'com.github.GreetingApplication.main' is declared as the main entry point but it can not be found. Make sure that class 'com.github.GreetingApplication' is on the classpath and that method 'main(String[])' exists in that class.
com.oracle.svm.core.util.UserError$UserException: Method 'com.github.GreetingApplication.main' is declared as the main entry point but it can not be found. Make sure that class 'com.github.GreetingApplication' is on the classpath and that method 'main(String[])' exists in that class.

### How to Reproduce?

1) clone the sample repo: https://github.com/arolfes/quarkus-kotlin-native
2) run nativeBuild `./gradlew build -Dquarkus.package.type=native`

### Output of `uname -a` or `ver`

Linux fedora 6.0.11-300.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Dec 2 20:47:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

OpenJDK Runtime Environment GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.14.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.5.1

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #29754

### CODE REVIEW

File: core/deployment/src/main/java/io/quarkus/deployment/steps/MainClassBuildStep.java [hunk 1]
```diff
@@ -410,6 +412,14 @@ public MainClassBuildItem mainClassBuildStep(BuildProducer<GeneratedClassBuildIt
         return new MainClassBuildItem(mainClassName);
     }
 
+    private static String sanitizeMainClassName(ClassInfo classInfo) {
+        String className = classInfo.name().toString();
+        if (isKotlinClass(classInfo)) {
+            className += "Kt";
```
Comment (evanchooly) [inline core/deployment/src/main/java/io/quarkus/deployment/steps/MainClassBuildStep.java:418]: I don't think this is safe at all.  There will be plenty of case (the majority in all likelihood) where `main()` will be part of a class definition and not a top level function as it is in the originating bug.

File: core/deployment/src/main/java/io/quarkus/deployment/steps/RegisterForReflectionBuildStep.java [hunk 2]
```diff
@@ -1,5 +1,7 @@
 package io.quarkus.deployment.steps;
 
+import static io.quarkus.deployment.steps.KotlinUtil.*;
```
Comment (evanchooly) [inline core/deployment/src/main/java/io/quarkus/deployment/steps/RegisterForReflectionBuildStep.java:3]: imported but not used?

File: integration-tests/kotlin-serialization/src/main/kotlin/io/quarkus/it/kotser/GreetingApplication.kt [hunk 3]
```diff
@@ -0,0 +1,11 @@
+package io.quarkus.it.kotser
+
+import io.quarkus.runtime.Quarkus.run
+import io.quarkus.runtime.annotations.QuarkusMain
+
+@QuarkusMain
```
Comment (evanchooly) [inline integration-tests/kotlin-serialization/src/main/kotlin/io/quarkus/it/kotser/GreetingApplication.kt:6]: Create a case like this:

```kotlin
@QuarkusMain
class GreetingApplication {
   fun main(args: Array<String>) {
       run(*args)
   }
}
```
and see how things fare.  I have hunch it will break.

**Review by evanchooly — CHANGES_REQUESTED** [review]

File: core/deployment/src/main/java/io/quarkus/deployment/steps/RegisterForReflectionBuildStep.java (hunk 2 above)
Comment (geoand) [reply core/deployment/src/main/java/io/quarkus/deployment/steps/RegisterForReflectionBuildStep.java:3]: It is used

File: core/deployment/src/main/java/io/quarkus/deployment/steps/MainClassBuildStep.java (hunk 1 above)
Comment (geoand) [reply core/deployment/src/main/java/io/quarkus/deployment/steps/MainClassBuildStep.java]: Fixed

**Review by evanchooly — APPROVED** [review]
This fix is better but it makes assumptions about the name the class matching the file name.  It creates subtle holes (subtler than the original issue in some ways) that are likely to crop up later.  I don't like this approach and am generally opposed but if users expect this kind of behavior when coming from Spring then I can plug my nose and move past it.

**Comment by geoand** [comment]
If this pattern where not proposed on the Kotlin page itself, I would not insist.
The way things are now, I would say that if we don't do it, users will be frustrated (for what they see as no good reason)
