### PR TITLE
Arc - synthetic bean improvements

### LINKED ISSUE #44887: ArC: make it possible to restrict the bean types of a synthetic bean
### Description

It should be possible to **_restrict_** the bean types of a synthetic bean with the same semantics as `@jakarta.enterprise.inject.Typed`.

Currently, it's not possible to create a synthetic alternative to the [following producer method](https://github.com/quarkusio/quarkus/blob/main/extensions/hibernate-reactive/runtime/src/main/java/io/quarkus/hibernate/reactive/runtime/ReactiveSessionFactoryProducer.java#L27-L43):
```java
    @Produces
    @ApplicationScoped
    @DefaultBean
    @Unremovable
    @Typed({ Mutiny.SessionFactory.class, Implementor.class })
    public MutinySessionFactoryImpl mutinySessionFactory() {
        if (jpaConfig.getDeactivatedPersistenceUnitNames()
                .contains(HibernateReactive.DEFAULT_REACTIVE_PERSISTENCE_UNIT_NAME)) {
            throw new IllegalStateException(
                    "Cannot retrieve the Mutiny.SessionFactory for persistence unit "
                            + HibernateReactive.DEFAULT_REACTIVE_PERSISTENCE_UNIT_NAME
                            + ": Hibernate Reactive was deactivated through configuration properties");
        }
        return (MutinySessionFactoryImpl) emf.unwrap(Mutiny.SessionFactory.class);
    }
```

### Implementation ideas

Add the `restrictTypes()` method to the configurator API.

### LINKED ISSUE #44888: ArC: make it possible to discover the bean types of a synthetic bean
### Description

Currently, all types must be added manually. It might make sense to add an alternative to `jakarta.enterprise.inject.spi.configurator.BeanConfigurator.addTransitiveTypeClosure(Type)`.

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by manovotn**
Adds a new method for synth. bean registration that does not automatically register the impl class as bean type.
Allows adding type closures to synth beans and also restricting their types.

Resolves https://github.com/quarkusio/quarkus/issues/44887
Resolves https://github.com/quarkusio/quarkus/issues/44888

### CODE REVIEW

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/SyntheticBeanBuildItem.java [hunk 1]
```diff
@@ -32,6 +32,9 @@
 public final class SyntheticBeanBuildItem extends MultiBuildItem {
 
     /**
+     * Returns a configurator object allowing for further customization of the synthetic bean.
+     * <p>
+     * The implementation class is automatically registered as a resulting bean type.
```
Comment (manovotn) [inline extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/SyntheticBeanBuildItem.java:37]: @mkouba @Ladicek I did not `@Deprecate` this yet, should we do that?
While I would prefer to have a single way of registering the bean here, I can see use in both approaches.

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanConfiguratorBase.java [hunk 2]
```diff
@@ -134,6 +142,74 @@ public THIS addType(Class<?> type) {
...
+        return self();
+    }
+
+    /**
+     * Removes listed types from the resulting types of the synthetic bean.
+     *
+     * @param types types that should be removed from the resulting set of bean types
+     * @return self
+     */
+    public THIS restrictTypes(DotName... types) {
```
Comment (manovotn) [inline independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanConfiguratorBase.java:195]: Note that this is different from the discussion in https://github.com/quarkusio/quarkus/issues/44887.

Instead of listing all the types you want to end up with, I choose to instead list the types that you want removed from the set of types. My reasoning is that this is mostly useful when combined with `addTypeClosure` where you want to add bigger amount of types and here you just want to exclude a few.
If you need to list an excessive list of types here, you might as well not register the whole closure and have these types under `addTypes` directly.

Comment (mkouba) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanConfiguratorBase.java:195]: In that case, it might make more sense to rename the method to something like `removeTypes()`.

File: extensions/arc/deployment/src/test/java/io/quarkus/arc/test/synthetic/typeClosure/SyntheticBeanBuildItemAddTypeClosureTest.java [hunk 3]
```diff
@@ -0,0 +1,106 @@
...
+        return new Consumer<BuildChainBuilder>() {
+
+            @Override
+            public void accept(BuildChainBuilder builder) {
+                builder.addBuildStep(new BuildStep() {
+
+                    @Override
+                    public void execute(BuildContext context) {
+                        context.produce(SyntheticBeanBuildItem.create(FooSubclass.class)
+                                .addTypeClosure(FooInterface.class)
```
Comment (mkouba) [inline extensions/arc/deployment/src/test/java/io/quarkus/arc/test/synthetic/typeClosure/SyntheticBeanBuildItemAddTypeClosureTest.java:43]: I know that `Types.getClassUnrestrictedTypeClosure()` existed for a long time but shouldn't we add at least a simple test for generics?

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/SyntheticBeanBuildItem.java (hunk 1 above)
Comment (Ladicek) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/SyntheticBeanBuildItem.java:37]: Agreed, it seems to me that both cases have value.

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanConfiguratorBase.java (hunk 2 above)
Comment (Ladicek) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanConfiguratorBase.java:195]: Agree with `removeTypes()`. [Restricting the bean types of a bean](https://jakarta.ee/specifications/cdi/4.1/jakarta-cdi-spec-4.1.html#restricting_bean_types) is a well defined operation and this is not it.

Comment (Ladicek) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanConfiguratorBase.java:195]: Also, if this was `restrictTypes()` as defined by the spec, I would disagree with adding the overload accepting `Type...`. Restriction accepts a set of classes and keeps only the types whose erasures are included in the set. This is important in case of parameterized types.

With `removeTypes()`, we can be more direct and expect users to explicitly remove parameterized types if they want.

Comment (manovotn) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanConfiguratorBase.java:195]: > In that case, it might make more sense to rename the method to something like `removeTypes()`.

Agreed, that's definitely a more fitting name.

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/SyntheticBeanBuildItem.java (hunk 1 above)
Comment (manovotn) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/SyntheticBeanBuildItem.java:37]: Ok, let's keep it then.

File: extensions/arc/deployment/src/test/java/io/quarkus/arc/test/synthetic/typeClosure/SyntheticBeanBuildItemAddTypeClosureTest.java (hunk 3 above)
Comment (manovotn) [reply extensions/arc/deployment/src/test/java/io/quarkus/arc/test/synthetic/typeClosure/SyntheticBeanBuildItemAddTypeClosureTest.java:43]: I've added `SyntheticBeanBuildItemAddTypeClosureGenericsTest`

File: extensions/arc/deployment/src/test/java/io/quarkus/arc/test/synthetic/typeClosure/SyntheticBeanBuildItemAddTypeClosureGenericsTest.java [hunk 4]
```diff
@@ -0,0 +1,135 @@
...
+        return new Consumer<BuildChainBuilder>() {
+
+            @Override
+            public void accept(BuildChainBuilder builder) {
+                builder.addBuildStep(new BuildStep() {
+
+                    @Override
+                    public void execute(BuildContext context) {
+                        context.produce(SyntheticBeanBuildItem.create(FooSubclass.class)
+                                .addTypeClosure(ParameterizedType.create(FooSubclass.class, Type.create(Beta.class)))
```
Comment (mkouba) [inline extensions/arc/deployment/src/test/java/io/quarkus/arc/test/synthetic/typeClosure/SyntheticBeanBuildItemAddTypeClosureGenericsTest.java:46]: Just FYI there's a convenient builder for `ParameterizedType`: `ParameterizedType.builder(FooSubclass.class).addArgument(Beta.class).build()`. It's not shorter but a little bit cleaner.

**Review by mkouba — APPROVED** [review]

File: extensions/arc/deployment/src/test/java/io/quarkus/arc/test/synthetic/restrictTypes/SyntheticBeanBuildItemRestrictTypesTest.java [hunk 5]
```diff
@@ -0,0 +1,109 @@
...
+
+    @Vetoed
+    public static class Foo extends Charlie implements BazInterface {
+    }
+
+    @Vetoed
+    public static class CharlieSubclass extends Charlie {
+    }
+
+    @Vetoed
```
Comment (Ladicek) [inline extensions/arc/deployment/src/test/java/io/quarkus/arc/test/synthetic/restrictTypes/SyntheticBeanBuildItemRestrictTypesTest.java:85]: I don't think you have to veto all these classes?

File: extensions/arc/deployment/src/test/java/io/quarkus/arc/test/synthetic/restrictTypes/SyntheticBeanBuildItemRestrictTypesTest.java [hunk 6]
```diff
@@ -0,0 +1,109 @@
...
+                                .creator(FooCreator.class)
+                                .done());
+                    }
+                }).produces(SyntheticBeanBuildItem.class).build();
+            }
+        };
+    }
+
+    @Test
+    public void testRestrictingBeanTypes() {
```
Comment (Ladicek) [inline extensions/arc/deployment/src/test/java/io/quarkus/arc/test/synthetic/restrictTypes/SyntheticBeanBuildItemRestrictTypesTest.java:59]: The class name and the test method name still refere to "restricting" types, which is probably not intentional?

File: extensions/arc/deployment/src/test/java/io/quarkus/arc/test/synthetic/restrictTypes/SyntheticBeanBuildItemRestrictTypesTest.java [hunk 7]
```diff
@@ -0,0 +1,109 @@
...
+    @Vetoed
+    public static class FooSubclass extends Foo implements FooInterface {
+    }
+
+    @Vetoed
+    public static class Foo extends Charlie implements BazInterface {
+    }
+
+    @Vetoed
+    public static class CharlieSubclass extends Charlie {
```
Comment (Ladicek) [inline extensions/arc/deployment/src/test/java/io/quarkus/arc/test/synthetic/restrictTypes/SyntheticBeanBuildItemRestrictTypesTest.java:82]: This is not in the type closure of `FooSubclass`. Is that intended? Just wondering.

**Review by Ladicek — APPROVED** [review]
LGTM. All my comments are just minutiae.

File: extensions/arc/deployment/src/test/java/io/quarkus/arc/test/synthetic/restrictTypes/SyntheticBeanBuildItemRestrictTypesTest.java (hunk 6 above)
Comment (manovotn) [reply extensions/arc/deployment/src/test/java/io/quarkus/arc/test/synthetic/restrictTypes/SyntheticBeanBuildItemRestrictTypesTest.java:59]: Good point, so does the package name - will change :+1:

File: extensions/arc/deployment/src/test/java/io/quarkus/arc/test/synthetic/restrictTypes/SyntheticBeanBuildItemRestrictTypesTest.java (hunk 7 above)
Comment (manovotn) [reply extensions/arc/deployment/src/test/java/io/quarkus/arc/test/synthetic/restrictTypes/SyntheticBeanBuildItemRestrictTypesTest.java:82]: Yes, this was intentional.

File: extensions/arc/deployment/src/test/java/io/quarkus/arc/test/synthetic/restrictTypes/SyntheticBeanBuildItemRestrictTypesTest.java (hunk 5 above)
Comment (manovotn) [reply extensions/arc/deployment/src/test/java/io/quarkus/arc/test/synthetic/restrictTypes/SyntheticBeanBuildItemRestrictTypesTest.java:85]: Good point, Weld habits got in the way :)

**Comment by manovotn** [comment]
Addressed all of the remaining minor comments, the PR should be good to go once CI gives us the green light.

File: extensions/arc/deployment/src/test/java/io/quarkus/arc/test/synthetic/restrictTypes/SyntheticBeanBuildItemRestrictTypesTest.java (hunk 7 above)
Comment (Ladicek) [reply extensions/arc/deployment/src/test/java/io/quarkus/arc/test/synthetic/restrictTypes/SyntheticBeanBuildItemRestrictTypesTest.java]: Gotcha, thanks!
