### PR TITLE
fix: Dev mode - 404 Page - Live reloaded list of static files

### LINKED ISSUE #5201: Dev mode - 404 - List of static files not reloaded
Launch dev mode, go to an unknown page, you get the 404 with a list of static html files.

Create a new html file, reload the 404, the file is not there.

### PR DESCRIPTION
**Pull request by machi1990**
/cc @gsmet 

Fixes #5201

### CODE REVIEW

File: extensions/resteasy/deployment/src/test/java/io/quarkus/resteasy/test/NotFoundExceptionMapperTestCase.java [hunk 1]
```diff
@@ -45,4 +53,46 @@ public void testJsonResourceNotFound() {
                 .contentType(ContentType.JSON);
     }
 
+    @Test
+    public void shouldDisplayNewAddedFileIn404ErrorPage() {
+        String CONTENT = "html content";
+        test.addResourceFile(META_INF_RESOURCES + "index2.html", CONTENT);
+
+        RestAssured.get("/index2.html")
```
Comment (aguibert) [inline extensions/resteasy/deployment/src/test/java/io/quarkus/resteasy/test/NotFoundExceptionMapperTestCase.java]: Is any sort of wait needed here between adding the resource file and invoking the `GET /index2.html` to ensure that dev mode has processed the new file?

Comment (machi1990) [reply extensions/resteasy/deployment/src/test/java/io/quarkus/resteasy/test/NotFoundExceptionMapperTestCase.java]: Hi @aguibert. No, it is not needed. Changes will be picked detected and picked automatically as indicated in the line 63 and 64.

**Review by aguibert — APPROVED** [review]
LGTM

**Comment by machi1990** [comment]
@gwenneg would also gave some time to review this? Related to improving the not found page in dev mode as #5235 thanks.

**Comment by gwenneg** [comment]
Sure, I'll take a look at it tonight.

File: core/devmode/src/main/java/io/quarkus/dev/RuntimeUpdatesProcessor.java [hunk 2]
```diff
@@ -354,7 +353,7 @@ private String getFileExtension(File file) {
                         if (value > existing) {
                             ret.add(path);
                             log.infof("File change detected: %s", file);
-                            if (doCopy) {
+                            if (doCopy && !Files.isDirectory(file)) {
```
Comment (gwenneg) [inline core/devmode/src/main/java/io/quarkus/dev/RuntimeUpdatesProcessor.java]: It makes sense to add this condition for files, but it also makes me wondering if directories would need to be created. WDYT?

File: core/devmode/src/main/java/io/quarkus/dev/RuntimeUpdatesProcessor.java [hunk 3]
```diff
@@ -354,7 +353,7 @@ private String getFileExtension(File file) {
...
                                 Path target = classesDir.resolve(path);
                                 byte[] data = Files.readAllBytes(file);
```
Comment (gwenneg) [inline core/devmode/src/main/java/io/quarkus/dev/RuntimeUpdatesProcessor.java]: That's not part of your PR and I'm not even sure that's a problem since static files are usually small, but this won't work for large files. Is that an acceptable risk? There are two occurences of this method call in this class.

File: extensions/resteasy/deployment/src/test/java/io/quarkus/resteasy/test/NotFoundExceptionMapperTestCase.java [hunk 4]
```diff
@@ -45,4 +53,46 @@ public void testJsonResourceNotFound() {
...
+    @Test
+    public void shouldNotDisplayDeletedFileIn404ErrorPage() {
+        String TEST_CONTENT = "test html content";
+        test.addResourceFile(META_INF_RESOURCES + "test.html", TEST_CONTENT);
+
+        RestAssured
+                .get("/test.html")
+                .then()
+                .statusCode(200)
+                .body(containsString(TEST_CONTENT)); // check that another.html is reloaded
```
Comment (gwenneg) [inline extensions/resteasy/deployment/src/test/java/io/quarkus/resteasy/test/NotFoundExceptionMapperTestCase.java]:
```suggestion
                .body(containsString(TEST_CONTENT)); // check that test.html is live reloaded
```

**Review by gwenneg — COMMENTED** [review]
That's unrelated with your changes, but I've seen a few `IOException` being caught and rethrown encapsulated into a `RuntimeException` in `RuntimeUpdatesProcessor`. It would be nice to throw an `UncheckedIOException` instead while we're at it.

File: extensions/resteasy/deployment/src/test/java/io/quarkus/resteasy/test/NotFoundExceptionMapperTestCase.java (hunk 4 above)
Comment (machi1990) [reply extensions/resteasy/deployment/src/test/java/io/quarkus/resteasy/test/NotFoundExceptionMapperTestCase.java]: Good catch.

File: core/devmode/src/main/java/io/quarkus/dev/RuntimeUpdatesProcessor.java (hunk 2 above)
Comment (machi1990) [reply core/devmode/src/main/java/io/quarkus/dev/RuntimeUpdatesProcessor.java]: A directory is only watched for changes. 

It will be created when coping its files resource files here - https://github.com/quarkusio/quarkus/blob/27381651e25fd30febf3017e04c9a73c96273aaf/core/devmode/src/main/java/io/quarkus/dev/RuntimeUpdatesProcessor.java#L323

File: core/devmode/src/main/java/io/quarkus/dev/RuntimeUpdatesProcessor.java (hunk 3 above)
Comment (machi1990) [reply core/devmode/src/main/java/io/quarkus/dev/RuntimeUpdatesProcessor.java]: Yes, the static file will have to be bigger than 2GB. I bet it is safe to keep it this way for now.

**Comment by machi1990** [comment]
> That's unrelated with your changes, but I've seen a few `IOException` being caught and rethrown encapsulated into a `RuntimeException` in `RuntimeUpdatesProcessor`. It would be nice to throw an `UncheckedIOException` instead while we're at it.

Yes, let me do it in a separate refactoring commit.

File: extensions/resteasy/deployment/src/test/java/io/quarkus/resteasy/test/NotFoundExceptionMapperTestCase.java (hunk 4 above)
Comment (machi1990) [reply extensions/resteasy/deployment/src/test/java/io/quarkus/resteasy/test/NotFoundExceptionMapperTestCase.java]: done

**Comment by machi1990** [comment]
@gwenneg thanks for the review. I pushed a second refactoring commit - WDYT?

File: core/devmode/src/main/java/io/quarkus/dev/RuntimeUpdatesProcessor.java (hunk 3 above)
Comment (gwenneg) [reply core/devmode/src/main/java/io/quarkus/dev/RuntimeUpdatesProcessor.java]: If I'm not mistaken, the exact value depends on the heap size. But we're talking about dev mode and a very unlikely static file size, I agree to leave it that way.

**Review by gwenneg — APPROVED** [review]
LGTM, thanks!

**Comment by gsmet** [comment]
In the end I decided to not backport it. It's not critical enough to justify touching the hot reload logic now.

**Comment by machi1990** [comment]
Thanks @gsmet for the update. It will give me time (during the weekend) to look on why the test case added was failing in JDK 8, as pointed out by @dmlloyd here https://github.com/quarkusio/quarkus/issues/5424.
