### PR TITLE
Fail deployment when unable to create the vertx httpServer

### LINKED ISSUE #4124: Stuck Quarkus process when port 8080 is already assigned, kill -9 needs to be used, user not informed about used port
Stuck Quarkus process when port 8080 is already assigned, `kill -9` needs to be used, user not informed about used port.

This is regression comparing to 0.22.0 when user is informed via `Caused by: java.net.BindException: Address already in use` and user can press Ctrl+C to stop the process.

Master based app doesn't react to Ctrl+C and `kill -9` needs to be used.
Stacktrace informs just about NPE, nothing about already used port.

```
java -jar getting-started-two/target/getting-started-two-1.0-SNAPSHOT-runner.jar
2019-09-20 09:37:26,984 SEVERE [io.ver.cor.imp.ContextImpl] (vert.x-eventloop-thread-15) Unhandled exception: java.lang.NullPointerException
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.lambda$start$0(VertxHttpRecorder.java:382)
	at io.vertx.core.http.impl.HttpServerImpl.lambda$null$5(HttpServerImpl.java:277)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

2019-09-20 09:37:26,984 SEVERE [io.ver.cor.imp.ContextImpl] (vert.x-eventloop-thread-9) Unhandled exception: java.lang.NullPointerException
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.lambda$start$0(VertxHttpRecorder.java:382)
	at io.vertx.core.http.impl.HttpServerImpl.lambda$null$5(HttpServerImpl.java:277)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

2019-09-20 09:37:26,984 SEVERE [io.ver.cor.imp.ContextImpl] (vert.x-eventloop-thread-1) Unhandled exception: java.lang.NullPointerException
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.lambda$start$0(VertxHttpRecorder.java:382)
	at io.vertx.core.http.impl.HttpServerImpl.lambda$null$5(HttpServerImpl.java:277)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

2019-09-20 09:37:26,984 SEVERE [io.ver.cor.imp.ContextImpl] (vert.x-eventloop-thread-8) Unhandled exception: java.lang.NullPointerException
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.lambda$start$0(VertxHttpRecorder.java:382)
	at io.vertx.core.http.impl.HttpServerImpl.lambda$null$5(HttpServerImpl.java:277)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

2019-09-20 09:37:26,984 SEVERE [io.ver.cor.imp.ContextImpl] (vert.x-eventloop-thread-4) Unhandled exception: java.lang.NullPointerException
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.lambda$start$0(VertxHttpRecorder.java:382)
	at io.vertx.core.http.impl.HttpServerImpl.lambda$null$5(HttpServerImpl.java:277)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

2019-09-20 09:37:26,984 SEVERE [io.ver.cor.imp.ContextImpl] (vert.x-eventloop-thread-14) Unhandled exception: java.lang.NullPointerException
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.lambda$start$0(VertxHttpRecorder.java:382)
	at io.vertx.core.http.impl.HttpServerImpl.lambda$null$5(HttpServerImpl.java:277)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

2019-09-20 09:37:26,984 SEVERE [io.ver.cor.imp.ContextImpl] (vert.x-eventloop-thread-12) Unhandled exception: java.lang.NullPointerException
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.lambda$start$0(VertxHttpRecorder.java:382)
	at io.vertx.core.http.impl.HttpServerImpl.lambda$null$5(HttpServerImpl.java:277)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

2019-09-20 09:37:26,984 SEVERE [io.ver.cor.imp.ContextImpl] (vert.x-eventloop-thread-10) Unhandled exception: java.lang.NullPointerException
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.lambda$start$0(VertxHttpRecorder.java:382)
	at io.vertx.core.http.impl.HttpServerImpl.lambda$null$5(HttpServerImpl.java:277)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

2019-09-20 09:37:26,984 SEVERE [io.ver.cor.imp.ContextImpl] (vert.x-eventloop-thread-11) Unhandled exception: java.lang.NullPointerException
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.lambda$start$0(VertxHttpRecorder.java:382)
	at io.vertx.core.http.impl.HttpServerImpl.lambda$null$5(HttpServerImpl.java:277)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

2019-09-20 09:37:26,984 SEVERE [io.ver.cor.imp.ContextImpl] (vert.x-eventloop-thread-3) Unhandled exception: java.lang.NullPointerException
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.lambda$start$0(VertxHttpRecorder.java:382)
	at io.vertx.core.http.impl.HttpServerImpl.lambda$null$5(HttpServerImpl.java:277)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

2019-09-20 09:37:26,984 SEVERE [io.ver.cor.imp.ContextImpl] (vert.x-eventloop-thread-13) Unhandled exception: java.lang.NullPointerException
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.lambda$start$0(VertxHttpRecorder.java:382)
	at io.vertx.core.http.impl.HttpServerImpl.lambda$null$5(HttpServerImpl.java:277)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

2019-09-20 09:37:26,984 SEVERE [io.ver.cor.imp.ContextImpl] (vert.x-eventloop-thread-6) Unhandled exception: java.lang.NullPointerException
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.lambda$start$0(VertxHttpRecorder.java:382)
	at io.vertx.core.http.impl.HttpServerImpl.lambda$null$5(HttpServerImpl.java:277)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

2019-09-20 09:37:26,984 SEVERE [io.ver.cor.imp.ContextImpl] (vert.x-eventloop-thread-5) Unhandled exception: java.lang.NullPointerException
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.lambda$start$0(VertxHttpRecorder.java:382)
	at io.vertx.core.http.impl.HttpServerImpl.lambda$null$5(HttpServerImpl.java:277)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

2019-09-20 09:37:26,984 SEVERE [io.ver.cor.imp.ContextImpl] (vert.x-eventloop-thread-0) Unhandled exception: java.lang.NullPointerException
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.lambda$start$0(VertxHttpRecorder.java:382)
	at io.vertx.core.http.impl.HttpServerImpl.lambda$null$5(HttpServerImpl.java:277)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

2019-09-20 09:37:26,984 SEVERE [io.ver.cor.imp.ContextImpl] (vert.x-eventloop-thread-2) Unhandled exception: java.lang.NullPointerException
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.lambda$start$0(VertxHttpRecorder.java:382)
	at io.vertx.core.http.impl.HttpServerImpl.lambda$null$5(HttpServerImpl.java:277)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

2019-09-20 09:37:26,984 SEVERE [io.ver.cor.imp.ContextImpl] (vert.x-eventloop-thread-7) Unhandled exception: java.lang.NullPointerException
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.lambda$start$0(VertxHttpRecorder.java:382)
	at io.vertx.core.http.impl.HttpServerImpl.lambda$null$5(HttpServerImpl.java:277)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

Killed: 9
```

Steps to reproduce:
```

mvn io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=getting-started-one \
    -DclassName="org.acme.quickstart.GreetingResource" \
    -Dpath="/hello"


mvn io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=getting-started-two \
    -DclassName="org.acme.quickstart.GreetingResource" \
    -Dpath="/hello"


mvn clean package -f getting-started-one/pom.xml
mvn clean package -f getting-started-two/pom.xml

java -jar getting-started-one/target/getting-started-one-1.0-SNAPSHOT-runner.jar &
java -jar getting-started-two/target/getting-started-two-1.0-SNAPSHOT-runner.jar
```

Run following command in new terminal to kill the stuck process
```
jps -l | grep started-two | cut -d" " -f1 | xargs kill -9
```

Don't forget to stop the first app
```
jps -l | grep started-one | cut -d" " -f1 | xargs kill
```

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #4124

### CODE REVIEW

**Comment by geoand** [comment]
If #4096 makes it into `0.23`, then this (or an effectively similar fix) needs to make it in as well :)

**Comment by gsmet** [comment]
@geoand the issue is only if `#4096` is in? It doesn't solve an issue already present in the 0.23 branch in a different way?

**Comment by geoand** [comment]
@gsmet The issue of not exists even without #4096 I am pretty sure. But with #4096 thing are worse because a NPE is thrown that completely breaks everything down

**Comment by geoand** [comment]
@gsmet I just tested. Without #4096 things are different - but still broken. No port clash is displayed and both application report success when starting up.

**Comment by geoand** [comment]
Force pushed to polish the code a little

**Review by rsvoboda — APPROVED** [review]
looks good to me, now the app report port already in use and stops the execution

```
java -jar getting-started-two/target/getting-started-two-1.0-SNAPSHOT-runner.jar
java.lang.RuntimeException: Unable to start HTTP server
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder.doServerStart(VertxHttpRecorder.java:228)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder.initializeRouter(VertxHttpRecorder.java:124)
	at io.quarkus.deployment.steps.VertxHttpProcessor$initializeRouter8.deploy_0(VertxHttpProcessor$initializeRouter8.zig:94)
	at io.quarkus.deployment.steps.VertxHttpProcessor$initializeRouter8.deploy(VertxHttpProcessor$initializeRouter8.zig:119)
	at io.quarkus.runner.ApplicationImpl1.doStart(ApplicationImpl1.zig:84)
	at io.quarkus.runtime.Application.start(Application.java:91)
	at io.quarkus.runtime.Application.run(Application.java:204)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:34)
Caused by: java.util.concurrent.ExecutionException: java.net.BindException: Address already in use
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder.doServerStart(VertxHttpRecorder.java:198)
	... 7 more
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:132)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:551)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1345)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:503)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:488)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:984)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:247)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:355)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasksFrom(SingleThreadEventExecutor.java:392)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:367)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:506)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "main" java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl1.doStart(ApplicationImpl1.zig:144)
	at io.quarkus.runtime.Application.start(Application.java:91)
	at io.quarkus.runtime.Application.run(Application.java:204)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:34)
Caused by: java.lang.RuntimeException: Unable to start HTTP server
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder.doServerStart(VertxHttpRecorder.java:228)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder.initializeRouter(VertxHttpRecorder.java:124)
	at io.quarkus.deployment.steps.VertxHttpProcessor$initializeRouter8.deploy_0(VertxHttpProcessor$initializeRouter8.zig:94)
	at io.quarkus.deployment.steps.VertxHttpProcessor$initializeRouter8.deploy(VertxHttpProcessor$initializeRouter8.zig:119)
	at io.quarkus.runner.ApplicationImpl1.doStart(ApplicationImpl1.zig:84)
	... 3 more
Caused by: java.util.concurrent.ExecutionException: java.net.BindException: Address already in use
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder.doServerStart(VertxHttpRecorder.java:198)
	... 7 more
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:132)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:551)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1345)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:503)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:488)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:984)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:247)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:355)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasksFrom(SingleThreadEventExecutor.java:392)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:367)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:506)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by geoand** [comment]
Thanks for confirming @rsvoboda !

**Comment by gsmet** [comment]
OK, the random port commit is already in 0.23 so we need to backport this one too. I added the label.

**Comment by geoand** [comment]
Cool, thanks

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/VertxHttpRecorder.java [hunk 1]
```diff
@@ -375,24 +375,15 @@ public WebDeploymentVerticle(int port, int httpsPort, String host, HttpServerOpt
         @Override
         public void start(Future<Void> startFuture) throws Exception {
             final AtomicInteger remainingCount = new AtomicInteger(httpsOptions != null ? 2 : 1);
+            final HttpServerStartHandler httpServerStartHandler = new HttpServerStartHandler(startFuture, httpOptions,
+                    remainingCount);
```
Comment (gsmet) [inline extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/VertxHttpRecorder.java]: I think you went a bit fast here with the refactoring. One deals with `httpOptions`, the other with `httpsOptions`.

**Review by gsmet — DISMISSED** [review]

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/VertxHttpRecorder.java (hunk 1 above)
Comment (geoand) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/VertxHttpRecorder.java]: You're right! Let me fix that

Comment (geoand) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/VertxHttpRecorder.java]: Fixed

Comment (geoand) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/VertxHttpRecorder.java]: I had to revert the refactoring because there are now changes in the handling of the 2 cases. So grouping them doesn't make a whole lot of sense anymore

**Review by gsmet — APPROVED** [review]

**Comment by gwenneg** [comment]
Don't pay attention to the pull request mentioned above my comment, I made a typo, it is related to another issue.
