### PR TITLE
Fix off-by-one issue caused by ObservabilityIntegrationRecorder using its own method for getting path without prefix

### LINKED ISSUE #41854: REST request fails after adding maven dependency to quarkus-opentelemetry
### Describe the bug

After adding the _quarkus-opentelemetry_ dependency to our maven project, we have experienced endpoints using URL prefix and a default empty path is failing.

If we don't use URL prefix we don't see the error, and this is currently our workaround.

Apparently the way URLs are evaluated in _quarkus-opentelemetry_ is different from _resteasy reactive_
I expect the solution to this issue is to use the same _getPathWithoutPrefix_ method both places.

Please have a look at https://github.com/quarkusio/quarkus/blob/main/extensions/resteasy-reactive/rest/runtime/src/main/java/io/quarkus/resteasy/reactive/server/runtime/observability/ObservabilityIntegrationRecorder.java#L119
and
 https://github.com/quarkusio/quarkus/blob/main/independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/ResteasyReactiveRequestContext.java#L431

When the path evaluation is out of sync, we will get an error when calling _substring_ here: https://github.com/quarkusio/quarkus/blob/main/independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/mapping/RequestMapper.java#L112

### Expected behavior

We expect existing rest endpoint to keep working after adding the _quarkus-opentelemetry_ dependency

### Actual behavior

Our rest request fails after the _quarkus-opentelemetry_ dependency was added.

This is the returned stacktrace:
`{
    "details": "Error id 657d1068-0aae-47f2-9bf6-f98dab005dc9-1, java.lang.StringIndexOutOfBoundsException: Range [1, 1) out of bounds for length 0",
    "stack": "java.lang.StringIndexOutOfBoundsException: Range [1, 1) out of bounds for length 0\r\n\tat java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)\r\n\tat java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)\r\n\tat java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)\r\n\tat java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)\r\n\tat java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)\r\n\tat java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112)\r\n\tat java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349)\r\n\tat java.base/java.lang.String.checkBoundsBeginEnd(String.java:4865)\r\n\tat java.base/java.lang.String.substring(String.java:2834)\r\n\tat org.jboss.resteasy.reactive.server.mapping.RequestMapper.mapFromPathMatcher(RequestMapper.java:112)\r\n\tat org.jboss.resteasy.reactive.server.mapping.RequestMapper.map(RequestMapper.java:53)\r\n\tat io.quarkus.resteasy.reactive.server.runtime.observability.ObservabilityIntegrationRecorder.setTemplatePath(ObservabilityIntegrationRecorder.java:56)\r\n\tat io.quarkus.resteasy.reactive.server.runtime.ResteasyReactiveRecorder$13.handle(ResteasyReactiveRecorder.java:352)\r\n\tat io.quarkus.resteasy.reactive.server.runtime.ResteasyReactiveRecorder$13.handle(ResteasyReactiveRecorder.java:347)\r\n\tat io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1285)\r\n\tat io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)\r\n\tat io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:137)\r\n\tat io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$AuthenticationHandler$3$1.onItem(HttpSecurityRecorder.java:311)\r\n\tat io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$AuthenticationHandler$3$1.onItem(HttpSecurityRecorder.java:301)\r\n\tat io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:60)\r\n\tat io.smallrye.mutiny.operators.uni.builders.DefaultUniEmitter.complete(DefaultUniEmitter.java:37)\r\n\tat io.smallrye.mutiny.groups.UniOnNull.lambda$failWith$1(UniOnNull.java:46)\r\n\tat io.smallrye.context.impl.wrappers.SlowContextualBiConsumer.accept(SlowContextualBiConsumer.java:21)\r\n\tat io.smallrye.mutiny.groups.UniOnItem.lambda$transformToUni$4(UniOnItem.java:177)\r\n\tat io.smallrye.context.impl.wrappers.SlowContextualConsumer.accept(SlowContextualConsumer.java:21)\r\n\tat io.smallrye.mutiny.operators.uni.builders.UniCreateWithEmitter.subscribe(UniCreateWithEmitter.java:22)\r\n\tat io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)\r\n\tat io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.performInnerSubscription(UniOnItemTransformToUni.java:81)\r\n\tat io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:57)\r\n\tat io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem$KnownItemSubscription.forward(UniCreateFromKnownItem.java:38)\r\n\tat io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem.subscribe(UniCreateFromKnownItem.java:23)\r\n\tat io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)\r\n\tat io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni.subscribe(UniOnItemTransformToUni.java:25)\r\n\tat io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)\r\n\tat io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:51)\r\n\tat io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$AuthenticationHandler$3.onItem(HttpSecurityRecorder.java:301)\r\n\tat io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$AuthenticationHandler$3.onItem(HttpSecurityRecorder.java:286)\r\n\tat io.smallrye.mutiny.operators.uni.UniMemoizeOp.forwardTo(UniMemoizeOp.java:123)\r\n\tat io.smallrye.mutiny.operators.uni.UniMemoizeOp.notifyAwaiters(UniMemoizeOp.java:135)\r\n\tat io.smallrye.mutiny.operators.uni.UniMemoizeOp.onItem(UniMemoizeOp.java:97)\r\n\tat io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:60)\r\n\tat io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem$KnownItemSubscription.forward(UniCreateFromKnownItem.java:38)\r\n\tat io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem.subscribe(UniCreateFromKnownItem.java:23)\r\n\tat io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)\r\n\tat io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.performInnerSubscription(UniOnItemTransformToUni.java:81)\r\n\tat io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:57)\r\n\tat io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:60)\r\n\tat io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem$KnownItemSubscription.forward(UniCreateFromKnownItem.java:38)\r\n\tat io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem.subscribe(UniCreateFromKnownItem.java:23)\r\n\tat io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)\r\n\tat io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.performInnerSubscription(UniOnItemTransformToUni.java:81)\r\n\tat io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:57)\r\n\tat io.smallrye.mutiny.operators.uni.UniOnItemTransform$UniOnItemTransformProcessor.onItem(UniOnItemTransform.java:43)\r\n\tat io.smallrye.mutiny.operators.uni.UniOnItemTransform$UniOnItemTransformProcessor.onItem(UniOnItemTransform.java:43)\r\n\tat io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem$KnownItemSubscription.forward(UniCreateFromKnownItem.java:38)\r\n\tat io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem.subscribe(UniCreateFromKnownItem.java:23)\r\n\tat io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)\r\n\tat io.smallrye.mutiny.operators.uni.UniOnItemTransform.subscribe(UniOnItemTransform.java:22)\r\n\tat io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)\r\n\tat io.smallrye.mutiny.operators.uni.UniOnItemTransform.subscribe(UniOnItemTransform.java:22)\r\n\tat io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)\r\n\tat io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni.subscribe(UniOnItemTransformToUni.java:25)\r\n\tat io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)\r\n\tat io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni.subscribe(UniOnItemTransformToUni.java:25)\r\n\tat io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)\r\n\tat io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:51)\r\n\tat io.smallrye.mutiny.operators.uni.UniMemoizeOp.subscribe(UniMemoizeOp.java:59)\r\n\tat io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)\r\n\tat io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:51)\r\n\tat io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$AuthenticationHandler.handle(HttpSecurityRecorder.java:286)\r\n\tat io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$AuthenticationHandler.handle(HttpSecurityRecorder.java:233)\r\n\tat io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1285)\r\n\tat io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)\r\n\tat io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:137)\r\n\tat io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$5.handle(VertxHttpHotReplacementSetup.java:204)\r\n\tat io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$5.handle(VertxHttpHotReplacementSetup.java:192)\r\n\tat io.vertx.core.impl.future.FutureImpl$4.onSuccess(FutureImpl.java:176)\r\n\tat io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:60)\r\n\tat io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)\r\n\tat io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)\r\n\tat io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)\r\n\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)\r\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)\r\n\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\r\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\r\n\tat java.base/java.lang.Thread.run(Thread.java:1583)"
}`

### How to Reproduce?

I have created a small project that reproduces the issue.

Start the server and make a request for http://localhost:8080/demo
Notice the issue only occur when we have another rest endpoint defined that takes URL parameters. 
[rest-json-quickstart.zip](https://github.com/user-attachments/files/16190422/rest-json-quickstart.zip)

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19045.4529]

### Output of `java -version`

openjdk version "21.0.2" 2024-01-16 LTS

### Quarkus version or git rev

3.12.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.2 (c9616018c7a021c1c39be70fb2843d6f5f9b8a1c)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by bechhansen**
* Fix #41854

### CODE REVIEW

File: extensions/resteasy-reactive/rest/runtime/src/test/java/io/quarkus/resteasy/reactive/runtime/mapping/ObservabilityIntegrationRecorderTest.java [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+import org.junit.jupiter.api.BeforeAll;
+import org.junit.jupiter.api.Test;
+
+import java.util.ArrayList;
+
+import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
+import static org.mockito.Mockito.mock;
+import static org.mockito.Mockito.when;
+
+public class ObservabilityIntegrationRecorderTest {
```
Comment (geoand) [inline extensions/resteasy-reactive/rest/runtime/src/test/java/io/quarkus/resteasy/reactive/runtime/mapping/ObservabilityIntegrationRecorderTest.java:18]: I was afraid of this :)

We actually don't want tests like this, because they are super hard to maintain and don't test the actual issue.
What we need is a test `QuarkusUnitTest` (of which we have a huge number already in the codebase) that represents the scenario you found that causes the bug.

**Review by geoand — COMMENTED** [review]
Thanks a lot for this!

I added a comment about the test - we essentially need a different testing strategy

File: extensions/resteasy-reactive/rest/runtime/src/test/java/io/quarkus/resteasy/reactive/runtime/mapping/ObservabilityIntegrationRecorderTest.java (hunk 1 above)
Comment (bechhansen) [reply extensions/resteasy-reactive/rest/runtime/src/test/java/io/quarkus/resteasy/reactive/runtime/mapping/ObservabilityIntegrationRecorderTest.java:18]: Yes that would be better. Do you want me to try to write some?

Comment (geoand) [reply extensions/resteasy-reactive/rest/runtime/src/test/java/io/quarkus/resteasy/reactive/runtime/mapping/ObservabilityIntegrationRecorderTest.java:18]: If you want to give it a go, that would be nice. Otherwise, I can do it

Comment (brunobat) [reply extensions/resteasy-reactive/rest/runtime/src/test/java/io/quarkus/resteasy/reactive/runtime/mapping/ObservabilityIntegrationRecorderTest.java:18]: Yeah, apart from the `QuarkusUnitTest`, I would probably skip this `ObservabilityIntegrationRecorderTest` and create one simple one for `PathHelper` because a test like that doesn't need any mocking and you can easily test multiple combinations of paths.

Comment (gsmet) [reply extensions/resteasy-reactive/rest/runtime/src/test/java/io/quarkus/resteasy/reactive/runtime/mapping/ObservabilityIntegrationRecorderTest.java:18]: @bechhansen any chance you could adjust your PR following @brunobat 's recommendation? It looks like something we want in soonish.

Comment (gsmet) [reply extensions/resteasy-reactive/rest/runtime/src/test/java/io/quarkus/resteasy/reactive/runtime/mapping/ObservabilityIntegrationRecorderTest.java:18]: Thanks!

**Comment by brunobat** [comment]
@bechhansen are you still thinking on working on this PR?

**Comment by bechhansen** [comment]
> @bechhansen are you still thinking on working on this PR?

Hi @brunobat 

Sorry for the missing activity. I have been away for some weeks moving and vacationing. I'm afraid I don't expect to have time to look into doing more and different tests on this for the next month.

**Comment by gsmet** [comment]
@brunobat is this one on your radar? I really think we should fix it before we release the LTS.

**Comment by brunobat** [comment]
It is but I have no bandwidth.

**Comment by geoand** [comment]
I will fix it soon

**Comment by geoand** [comment]
PR updated

File: extensions/resteasy-reactive/rest/runtime/pom.xml [hunk 2]
```diff
@@ -41,6 +41,11 @@
             <artifactId>junit-jupiter</artifactId>
             <scope>test</scope>
         </dependency>
+        <dependency>
+            <groupId>org.mockito</groupId>
```
Comment (brunobat) [inline extensions/resteasy-reactive/rest/runtime/pom.xml:45]: We don't need this dependency.

Comment (brunobat) [reply extensions/resteasy-reactive/rest/runtime/pom.xml:45]: And there's the squash thingy...

Comment (geoand) [reply extensions/resteasy-reactive/rest/runtime/pom.xml:45]: Oops, good point

Comment (geoand) [reply extensions/resteasy-reactive/rest/runtime/pom.xml]: Dep removed. 

> And there's the squash thingy...

what  squash thing?

Comment (brunobat) [reply extensions/resteasy-reactive/rest/runtime/pom.xml]: sorry, squash the commits.

Comment (geoand) [reply extensions/resteasy-reactive/rest/runtime/pom.xml]: No need to. One commit contains the author's original fix (with my amendment) and the other is just a minor code cleanup

**Review by brunobat — APPROVED** [review]
Thanks @geoand and @bechhansen
