### PR TITLE
Configure the HTTP host when domain sockets are used

### LINKED ISSUE #24739: Quarkus unix domain socket path no longer used but placed onto 0.0.0.0 instead
### Describe the bug

Quarkus supports listening on a unix domain socket instead of a TCP socket for the HTTP server.
The path for the socket is no longer correctly used.

Config sample:
https://quarkus.io/guides/vertx-reference#listening-to-a-unix-domain-socket
https://quarkus.io/guides/all-config#quarkus-vertx-http_quarkus.http.domain-socket

```yaml
quarkus.http.host-enabled = false
quarkus.http.domain-socket = /var/run/io.quarkus.app.socket
quarkus.http.domain-socket-enabled = true
quarkus.vertx.prefer-native-transport = true
```

After upgrading to Quarkus 2.7.5 the unix domain socket is no longer correctly placed on the selected path location. Also the default path is not used. 

Quarkus startup log message prints:
`(...) Listening on: unix:0.0.0.0`

Also `netstat` shows that the domain socket is now placed on "0.0.0.0" instead of the proper path:
`unix  2      [ ACC ]     STREAM     LISTENING     28944    1/java               0.0.0.0`

### Expected behavior

The unix domain socket should be placed onto the correct path e.g. `/var/run/io.quarkus.app.socket`.

### Actual behavior

The unix domain socket is always placed onto `0.0.0.0`.

### How to Reproduce?

Reproducer:

Generate a fresh Quarkus project and configure it to use a unix domain socket instead of TCP for the HTTP server.

https://quarkus.io/guides/vertx-reference#listening-to-a-unix-domain-socket

### Output of `uname -a` or `ver`

Linux 6832a73e6fed 5.10.104-linuxkit #1 SMP Wed Mar 9 19:05:23 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk 17.0.2 2022-01-18 LTS

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

Quarkus 2.7.5.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.5

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by cescoffier**
Fix https://github.com/quarkusio/quarkus/issues/24739.

### CODE REVIEW

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/VertxHttpRecorder.java [hunk 1]
```diff
@@ -906,6 +906,8 @@ private static HttpServerOptions createDomainSocketOptions(HttpConfiguration htt
         HttpServerOptions options = new HttpServerOptions();
 
         applyCommonOptions(options, httpConfiguration, websocketSubProtocols);
+        // Override the host (0.0.0.0 by default) with the configured domain socket.
+        options.setHost(httpConfiguration.domainSocket);
```
Comment (gsmet) [inline extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/VertxHttpRecorder.java:910]: Ah so that would be my bug :). Thanks for the fix!

**Review by gsmet — APPROVED** [review]
