### PR TITLE
Move to JLine 3.x to avoid Jansi 1.x dependency/usage

### LINKED ISSUE #19491: Crash during mvn io.quarkus-maven-plugin:2.1.2.Final:create
### Describe the bug

The maven plugin crashes in Windows Powershell when I try to create a new project. 

### Expected behavior

_No response_

### Actual behavior

The maven process crashes with the following exception:

```
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.NoSuchMethodError: 'java.io.OutputStream org.fusesource.jansi.AnsiConsole.wrapOutputStream(java.io.OutputStream)'
  at io.quarkus.maven.components.Prompter.<init>(Unknown Source)
  while locating io.quarkus.maven.components.Prompter
  while locating io.quarkus.maven.CreateProjectMojo

...
```

### How to Reproduce?

Open up a Powershell instance.
Then execute the following command:

```
mvn io.quarkus:quarkus-maven-plugin:2.1.2.Final:create `
-DprojectGroupId="com.infosupport.pitstop.customermanagement" `
-DprojectArtifactId="customer-management" `
-DclassName="com.infosupport.pitstop.customermanagement.CustomersResource" `
-Dpath="customer-management"clear
```

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19043.1110]

### Output of `java -version`

openjdk version "16.0.1" 2021-04-20 OpenJDK Runtime Environment AdoptOpenJDK-16.0.1+9 (build 16.0.1+9) OpenJDK 64-Bit Server VM AdoptOpenJDK-16.0.1+9 (build 16.0.1+9, mixed mode, sharing)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.1.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.2 (ea98e05a04480131370aa0c110b8c54cf726c06f)

### Additional information

Powershell version: 5.1.19041.1023

### PR DESCRIPTION
**Pull request by jaikiran**
Potential fix for https://github.com/quarkusio/quarkus/issues/19491

As noted in that discussion, the JLine 2.x is EOLed and its usage it leading to issues described in that bug.

I've done absolutely zero testing of this change. I have only ensured that the whole build compiles and builds fine. I want to make sure there are no basic issues with this change and see how CI reacts. Tomorrow, I will try and get hold of the Windows box again and see if this fixes that original issue.

In the meantime, there are a couple of things to sort out:

-  I see there's a `CreateProjectMojoIT` testcase in the project. I wonder why it didn't catch this issue on our Windows CI setup
- I see that @gastaldi noted in the issue that he might have a way to get rid of the JLine usage in this code altogether, which I think would be the best/ideal thing. I have no historical knowledge of this code, so if that's possible, then I will close this PR and let's go with @gastaldi's approach. One less library dependency to maintain.

### CODE REVIEW

**Comment by gsmet** [comment]
There's a good chance we will want to backport this so I would be in favor of not making too big changes here (and maybe have a followup PR later to remove JLine support). I have no idea how to test that this works though. I'll let @gastaldi chime in.

**Comment by jaikiran** [comment]
> I have no idea how to test that this works though

This `Prompter` gets used only in 2 Mojos (the CreateProjectMojo and CreateExtensionMojo), so I will run a basic manual test on the Windows box once I get access to it tomorrow.

I'll also check tomorrow why our automated test(s) didn't catch this.

**Comment by gastaldi** [comment]
I'm building this PR in my Windows VirtualBox and will let you know

**Comment by jaikiran** [comment]
>I'll also check tomorrow why our automated test(s) didn't catch this.

Ha! Turns out our CI (rightly) uses Maven 3.8.1[1]. I just downloaded this version to do a basic check and turns out 3.8.1 version of Maven ships with `jansi-1.71.1` of Jansi, which is why I believe we didn't see this issue in our CI. It looks like 3.8.2 of Maven brought in this new jansi-2.x version. Release notes don't show anything related to this https://maven.apache.org/docs/3.8.2/release-notes.html. I will have to dig more into their complete changes to see if this is intentional upgrade.

[1] https://github.com/quarkusio/quarkus/blob/main/.mvn/wrapper/maven-wrapper.properties#L1

**Comment by gastaldi** [comment]
> Release notes don't show anything related to this

@jaikiran looks like it's only mentioned in JIRA: https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12316922&version=12349965

**Comment by jaikiran** [comment]
Yes, it looks like it first got upgrade in Maven 4.x and then was backported into 3.8.2 for this https://issues.apache.org/jira/browse/MNG-6239.

It's probably not a bad thing though. This gives us a chance to move away from JLine 2.x.

**Comment by jaikiran** [comment]
> I can confirm this works:

Excellent. Thank you for running the tests with this PR. I'll let the GitHub action jobs complete and in a separate personal branch of mine will trigger a GitHub job by upgrading to Maven 3.8.2 to see if there are any other issues that we need to be aware of.

File: independent-projects/tools/devtools-common/src/main/java/io/quarkus/devtools/utils/Prompter.java [hunk 1]
```diff
@@ -14,22 +13,10 @@
  */
 public class Prompter {
 
-    private final ConsoleReader console;
+    private final LineReader lineReader;
 
     public Prompter() throws IOException {
```
Comment (gastaldi) [inline independent-projects/tools/devtools-common/src/main/java/io/quarkus/devtools/utils/Prompter.java:18]: `IOException` is no longer thrown here

**Review by gastaldi — APPROVED** [review]

**Comment by famod** [comment]
FWIW, I'm working on updating to Maven 3.8.2. This is currently waiting for the Uograde to Gradle 7.2 (sic!).

Btw, we could add `jline:jline` to `bannedDependencies`.

**Comment by jaikiran** [comment]
The failures in this PR look unrelated. 

As for adding jline:jline as a banned dependency, is that a common thing we do for outdated libraries? Given that the new version of JLine that we are using in this PR uses a completely different package namespace, is banning necessary?

Hello @famod, I'll let you continue with the 3.8.2 work. I was merely interested in a complete run of this PR against 3.8.2, but it doesn't look straightforward given certain other unrelated dependency issues.

**Comment by gastaldi** [comment]
It makes sense to ban it because it is incompatible with Maven 3.8.2, so +1 to that

**Comment by jaikiran** [comment]
Done. I've updated the PR to ban `jline:jline`

**Review by gastaldi — APPROVED** [review]

**Review by gsmet — CHANGES_REQUESTED** [review]
Thanks for this but I really think that we should try to get rid of the warning `WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)`. We fight hard to get our output as clean as possible.

**Comment by jaikiran** [comment]
> Thanks for this but I really think that we should try to get rid of the warning `WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)`. We fight hard to get our output as clean as possible.

I'll take a look what this warning is about.

**Comment by jaikiran** [comment]
@gsmet, Done. I've now updated this PR with a change that should prevent that warning message.

**Comment by jaikiran** [comment]
These latest Microprofile TCK job failures with `NullPointerException` is surprising. My guess is they are not related to the change in this PR. Have these failed before with this exception? I can trigger a fresh run for this PR to see if they go away but I don't want to lose the logs and context from this current failed run, so just checking.

**Comment by gsmet** [comment]
Yeah, I have seen them failing many times. /cc @radcortez

**Review by gsmet — APPROVED** [review]
Perfect, thanks.
