### PR TITLE
Fix a bug where the Mutiny context is lost on caching

### LINKED ISSUE #40274: Context is lost when using caching
### Describe the bug

I recently upgraded a project from Quarkus 2.16.5.Final to 3.9.4.

We use contexts in mutiny to pass around data:
```java
var uni = greetingsService.doSomething();
return Uni.createFrom().emitter(em -> uni.subscribe().with(Context.of("hello", "world"), em::complete, em::fail));
```

The context is then accessed in the service:
```java
@CacheResult(cacheName = "test")
Uni<String> doSomething() {
    return Uni.createFrom().context(c -> {
        System.out.println(c);
        return Uni.createFrom().item("Hello from Quarkus REST");
    });
}
```

Something seems to have changed in the Quarkus when upgrading versions, code that worked before is no longer working. More specifically, if we have the `@CachedResult` annotation the context will be empty. If the annotation is removed, the context will contain the data as expected.

I've created a project here to reproduce the issue: https://github.com/AntonFagerberg/quarkus-cache-context

### Expected behavior

In `GreetingsService` this code:

```java
return Uni.createFrom().context(c -> {
    System.out.println(c);
    return Uni.createFrom().item("Hello from Quarkus REST");
});
```

Should print this in the console:
```
Context{entries={hello=world}}
```

### Actual behavior

In `GreetingsService` this code:

```java
return Uni.createFrom().context(c -> {
    System.out.println(c);
    return Uni.createFrom().item("Hello from Quarkus REST");
});
```

Should print this in the console:
```
Context{entries=null}
```

If the `@CacheResult(cacheName = "test")` annotation is removed, the context contains the data.

### How to Reproduce?

Project to reproduce is found here:

https://github.com/AntonFagerberg/quarkus-cache-context

Run it and visit `http://localhost:8080/hello`

`Context{entries=null}` will be printed in the console.

Remove the annotation `@CacheResult(cacheName = "test")` in `GreetingsService`. Re-run and access the same end-point and `Context{entries={hello=world}}` will be printed.

### Output of `uname -a` or `ver`

Darwin <redacted>.local 23.4.0 Darwin Kernel Version 23.4.0: Wed Feb 21 21:44:31 PST 2024; root:xnu-10063.101.15~2/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "21.0.3" 2024-04-16 LTS OpenJDK Runtime Environment Corretto-21.0.3.9.1 (build 21.0.3+9-LTS) OpenJDK 64-Bit Server VM Corretto-21.0.3.9.1 (build 21.0.3+9-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.9.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

8.6

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jponge**
This removes a bug where the Mutiny context was not passed on to some CompletionStage-based operation.

I also took the chance to remove UnresolvedUniValue.java that was long deprecated (target was Quarkus 3) and unused.

- Fixes: #40274

### CODE REVIEW

File: extensions/cache/runtime/src/main/java/io/quarkus/cache/runtime/UnresolvedUniValue.java [hunk 1]
```diff
@@ -1,16 +0,0 @@
-package io.quarkus.cache.runtime;
-
-/**
- * This value acts as a placeholder in the cache. It will be eventually replaced by the item emitted by the
- * {@link io.smallrye.mutiny.Uni Uni} when it has been resolved.
- *
- * @deprecated This placeholder is not used anymore and will be removed at some time after Quarkus 3.0.
- */
-@Deprecated
-public class UnresolvedUniValue {
```
Comment (geoand) [inline extensions/cache/runtime/src/main/java/io/quarkus/cache/runtime/UnresolvedUniValue.java:10]: Can we have this in a separate commit (or even PR)?

The reason is that I want to backport the other changes in this PR

Comment (jponge) [reply extensions/cache/runtime/src/main/java/io/quarkus/cache/runtime/UnresolvedUniValue.java:10]: Sure I can do that. I'll split into 2 commits so you can cherry-pick

**Comment by geoand** [comment]
I have a feeling that this will fix more than the linked issue, but we'll find our eventually :)

File: extensions/cache/runtime/src/main/java/io/quarkus/cache/runtime/UnresolvedUniValue.java (hunk 1 above)
Comment (geoand) [reply extensions/cache/runtime/src/main/java/io/quarkus/cache/runtime/UnresolvedUniValue.java:10]: :pray:

**Comment by jponge** [comment]
@geoand here are your 2 commits 👨‍🍳

**Comment by geoand** [comment]
Thanks!

**Review by geoand — APPROVED** [review]

**Review by mkouba — APPROVED** [review]
I have to admit that I got lost in this CS/Uni patchwork but I trust Julien so 👍.
