### PR TITLE
OpenAPI: ignore build-time excluded classes from annotation scan

### LINKED ISSUE #16218: Excluded JAX-RS classes are visible in openapi
## Describe the bug
When JAX-RS classes are excluded via `@IfBuildProfile` (#15215), it is still visible in the generated openapi document.

### Expected behavior
When a JAX-RS class is excluded from the current build via an `IfBuildProperty` annotation (or similar), it should also be excluded from openapi document generation.

### Actual behavior
The endpoints of the JAX-RS class are visible in openapi and swagger, but can not be called.

## To Reproduce

1. Create a JAX-RS class
2. include `quarkus-smallrye-openapi` extension
3. add `@IfBuildProfile("foo")` to the class
4. run in dev mode
5. open swagger ui
6. see that the JAX-RS class is visible

### Quarkus version or git rev
`1.13.0.Final`

### PR DESCRIPTION
**Pull request by MikeEdgar**
Fixes #16218

### CODE REVIEW

File: extensions/smallrye-openapi/deployment/src/main/java/io/quarkus/smallrye/openapi/deployment/SmallRyeOpenApiProcessor.java [hunk 1]
```diff
@@ -308,13 +309,31 @@ void additionalBean(BuildProducer<AdditionalBeanBuildItem> additionalBeanProduce
 
     @BuildStep
     OpenApiFilteredIndexViewBuildItem smallryeOpenApiIndex(CombinedIndexBuildItem combinedIndexBuildItem,
-            BeanArchiveIndexBuildItem beanArchiveIndexBuildItem) {
-        CompositeIndex compositeIndex = CompositeIndex.create(combinedIndexBuildItem.getIndex(),
+            BeanArchiveIndexBuildItem beanArchiveIndexBuildItem,
+            BuildExclusionsBuildItem buildExclusionsBuildItem) {
```
Comment (MikeEdgar) [inline extensions/smallrye-openapi/deployment/src/main/java/io/quarkus/smallrye/openapi/deployment/SmallRyeOpenApiProcessor.java:313]: I couldn't find `BuildExclusionsBuildItem` used anywhere else in Quarkus, but it seems like the perfect fit for this fix...

**Review by phillip-kruger — APPROVED** [review]
Nice. Thanks @MikeEdgar
