### PR TITLE
QuarkusComponentTest: make sure the "test" profile is used

### LINKED ISSUE #51574: QuarkusComponentTest does not use the config profile test
### Describe the bug

The QuarkusComponentTest's do not seem to use the configuration profiles (e.g. test) correctly.

For example, in the attached reproducer, I have configured in src/test/resources/application.properties:
```
%test.app.greeting=hello from application.properties
```

And my ConfigMapping:
```
@ConfigMapping(prefix = "app")
public interface GreetingMapping {
    @WithDefault("hello from mapping default")
    String greeting();
}
```

The test then uses the value from the default. I would have expected that the value from application.properties gets used, since a test is run.

If I change the application.properties as follows:
```
app.greeting=hello from application.properties
```
(i.e. remove the test profile), only then the value from the config gets used

### Expected behavior

config profile test is used by quarkuscomponenenttest

### Actual behavior

config profile test is used

### How to Reproduce?

Reproducer: https://github.com/Postremus/componenenttest-config-profile

Execute GreetingServiceTest -> failure
Change src/test/resources/application.properties, remove the %test.
Execute GreetingServiceTest again -> success

### Output of `uname -a` or `ver`

MINGW64_NT-10.0-26100 NANBCHL9NG3 3.3.6-341.x86_64 2022-09-05 20:28 UTC x86_64 Msys

### Output of `java -version`

openjdk 25.0.1 2025-10-21 LTS OpenJDK Runtime Environment Temurin-25.0.1+8 (build 25.0.1+8-LTS) OpenJDK 64-Bit Server VM Temurin-25.0.1+8 (build 25.0.1+8-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.30.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.11 (3e54c93a704957b63ee3494413a2b544fd3d825b) Maven home: C:\eclipse\tools\java\maven Java version: 25.0.1, vendor: Eclipse Adoptium, runtime: C:\eclipse\tools\java\25-temurin Default locale: de_DE, platform encoding: UTF-8 OS name: "windows 11", version: "10.0", arch: "amd64", family: "windows"

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mkouba**
- fixes #51574

### CODE REVIEW

File: test-framework/junit-component/src/main/java/io/quarkus/test/component/QuarkusComponentTestExtension.java [hunk 1]
```diff
@@ -513,7 +522,28 @@ private void startContainer(ExtensionContext context, Lifecycle testInstanceLife
 
         // TCCL is now the QuarkusComponentTestClassLoader set during initialization
         ClassLoader tccl = Thread.currentThread().getContextClassLoader();
-        SmallRyeConfigBuilder configBuilder = new SmallRyeConfigBuilder().forClassLoader(tccl)
+        LaunchMode testMode = LaunchMode.TEST;
+        LaunchMode.set(testMode);
+        SmallRyeConfigBuilder configBuilder = new SmallRyeConfigBuilder()
+                .forClassLoader(tccl)
+                // Make sure the "test" profile is used
+                .withDefaultValue(testMode.getProfileKey(), testMode.getDefaultProfile())
```
Comment (mkouba) [inline test-framework/junit-component/src/main/java/io/quarkus/test/component/QuarkusComponentTestExtension.java]: @radcortez Hopefully, this is enough to make the "test" profile work...

Comment (radcortez) [reply test-framework/junit-component/src/main/java/io/quarkus/test/component/QuarkusComponentTestExtension.java]: Yes.

Did you check https://github.com/quarkusio/quarkus/blob/6b71c874ef8a3056e60bc22003a7a05a795716f7/core/runtime/src/main/java/io/quarkus/runtime/configuration/ConfigUtils.java#L26-L35

And:
https://github.com/quarkusio/quarkus/blob/88c46b4ad60ad6330d35477c706c9ea6bff83d39/core/runtime/src/main/java/io/quarkus/runtime/configuration/QuarkusConfigBuilderCustomizer.java#L24

If you can't use `io.quarkus.runtime.configuration.ConfigUtils#emptyConfigBuilder`, you should be able to use `.withCustomizers(new QuarkusConfigBuilderCustomizer())` which will handle all the relocation with profiles, so `SmallRyeConfig` will look into the right ones, and you shouldn't need to register a default.

Comment (mkouba) [reply test-framework/junit-component/src/main/java/io/quarkus/test/component/QuarkusComponentTestExtension.java]: Thanks Roberto, `withCustomizers(new QuarkusConfigBuilderCustomizer())` is the best solution!

**Review by radcortez — APPROVED** [review]
