### PR TITLE
Warn if Runtime configuration is used in BuildSteps and without a RuntimeValue in Recorders

### LINKED ISSUE #5514: Run time config objects should be disallowed in build steps completely
**Describe the bug**
Users are using run time configuration object values in build steps, expecting the effects to happen at run time.  See https://github.com/quarkusio/quarkus/issues/5457#issuecomment-554270894 for some examples.

Usage of fields of run time configuration objects during build steps should be marked as an error.  However this is impossible unfortunately.  So the next best thing would be to ban run time configuration objects completely from build steps.  Their only use is to be passed in to recorder instances; the recorders should be able to directly inject the run time config instead.  Then, any usage of a run time configuration object in a build step can be marked as an error.

### PR DESCRIPTION
**Pull request by radcortez**
Historically, the way to use a Config object, which is Runtime in a Recorder, was to inject it in the BuildStep and call the recorder method with a reference to the config. Obviously, you would get an instance at the BuildStep level that was not initialized. In most cases, these instances were not being used, but I did find a couple of places where it was, which is incorrect.

The correct way to retrieve Runtime configuration at the Recorder level is via injection via a constructor.

Even in such cases, There was also another misleading pattern, which was to use the Config object directly without being wrapped in a `RuntimeValue`.

This PR, adds a warning about injecting Runtime Config objects in BuildSteps, or using Config objects without being wrapped in `RuntimeValue` at the Recorder. This can be changed to an error via `quarkus.extension-loader.runtime-config-at-deployment=fail`. Most likely, many extensions out there are still using the old pattern, and we will need a transition period until we completely disallow such behaviour.

This PR also changed all the BuildSteps and Recorders to follow the pattern of Runtime config injection via constructor with `RuntimeValue`.

This only applies to config objects like `@ConfigRoot` and `@ConfigMapping`. We know there are places where extensions directly query for runtime config (which we should also disallow), but it will be done separately.

- Fixes https://github.com/quarkusio/quarkus/issues/5514

### CODE REVIEW

**Comment by michalvavrik** [comment]
Injection of runtime config via buildsteps established expectation that whenever this method is recorder, the runtime config is ready. How will you know now that code recorded at runtime requires runtime configuration now that you introduced this indirection?

**Comment by radcortez** [comment]
The runtime config is always ready and available when we call the Recorders' methods with `@Record(ExecutionTime.RUNTIME_INIT)`.

**Comment by michalvavrik** [comment]
> The runtime config is always ready and available when we call the Recorders' methods with `@Record(ExecutionTime.RUNTIME_INIT)`.

I didn't know, I would swear I hit issues with accessing config in the past when not using `RuntimeConfigSetupCompleteBuildItem` and no runtime config class. I probably misinterpreted that, thanks for the information.

**Review by dmlloyd — APPROVED** [review]
Looks good to me in general. One thing about these kinds of changes which include significant cleanup that I've found is that it's good to split them up into many commits if possible, so that if there's a problem, it would be possible to `git bisect` and find the exact responsible change.

**Comment by radcortez** [comment]
@gsmet are you ok to merge this as is?

File: core/deployment/src/main/java/io/quarkus/deployment/ExtensionLoader.java [hunk 1]
```diff
@@ -634,11 +651,26 @@ private static Consumer<BuildChainBuilder> loadStepsFromClass(Class<?> clazz,
...
                                         if (recordAnnotation.value() == ExecutionTime.STATIC_INIT) {
+                                            // TODO - Check for runtime config is done in another place, we may want to make things more consistent. Rewrite once we disallow the injection of runtime objects in build steps
                                             methodConsumingConfigPhases.add(ConfigPhase.BUILD_AND_RUN_TIME_FIXED);
                                         } else {
                                             methodConsumingConfigPhases.add(annotation.phase());
+                                            if (annotation.phase().isReadAtMain() && !isRuntimeValue) {
+                                                if (extensionLoaderConfig.runtimeConfigAtDeployment().equals(warn)) {
+                                                    loadLog.warn(reportError(parameter, annotation.phase() + " configuration "
+                                                            + type.getTypeName()
+                                                            + " should be injected in a @Recorder constructor as a Runtime<"
```
Comment (gsmet) [inline core/deployment/src/main/java/io/quarkus/deployment/ExtensionLoader.java]: Is it `Runtime` or `RuntimeValue`?

TBH I didn't know you could inject it in the `@Recorder` constructor, it's news to me.

This makes things still a bit confusing though as you can have static init recorded methods too and the field won't be available then. Not saying we should change anything but it's still not completely ideal.

TBH, I wondered a few times if we should split the recorder in two as it's very confusing to have static init and runtime init methods mixed. But that's something for the future.

File: core/deployment/src/main/java/io/quarkus/deployment/ExtensionLoader.java [hunk 2]
```diff
@@ -634,11 +651,26 @@ private static Consumer<BuildChainBuilder> loadStepsFromClass(Class<?> clazz,
...
+                                                            + type.getTypeName() + ">").getMessage());
+                                                } else {
+                                                    throw reportError(parameter, annotation.phase() + " configuration "
+                                                            + type.getTypeName()
+                                                            + " can only be injected in a @Recorder constructor as a Runtime<"
```
Comment (gsmet) [inline core/deployment/src/main/java/io/quarkus/deployment/ExtensionLoader.java]: Same here about `RuntimeValue`.

File: core/deployment/src/main/java/io/quarkus/deployment/ExtensionLoaderConfig.java [hunk 3]
```diff
@@ -0,0 +1,20 @@
...
+import io.smallrye.config.WithDefault;
+
+@ConfigMapping(prefix = "quarkus.extension-loader")
+@ConfigRoot
+public interface ExtensionLoaderConfig {
+    /**
+     * Report runtime Config objects used during deployment time.
+     */
+    @WithDefault("warn")
+    RuntimeConfigAtDeployment runtimeConfigAtDeployment();
```
Comment (gsmet) [inline core/deployment/src/main/java/io/quarkus/deployment/ExtensionLoaderConfig.java]: Could you rename it to `reportRuntimeConfigAtDeployment`? Because as it is, it looks like you can enable the runtime config at deployment.

Same for the enum.

File: core/deployment/src/main/java/io/quarkus/deployment/builditem/RunTimeConfigurationProxyBuildItem.java [hunk 4]
```diff
@@ -7,6 +7,7 @@
 /**
  * A build item that carries all the "fake" run time config objects for use by recorders.
  */
+@Deprecated(forRemoval = true, since = "3.24")
```
Comment (gsmet) [inline core/deployment/src/main/java/io/quarkus/deployment/builditem/RunTimeConfigurationProxyBuildItem.java]:
```suggestion
@Deprecated(forRemoval = true, since = "3.25")
```

File: core/deployment/src/main/java/io/quarkus/deployment/configuration/ConfigMappingUtils.java [hunk 5]
```diff
@@ -191,9 +191,9 @@ private static void registerImplicitConverter(
         }
     }
 
+    @Deprecated(forRemoval = true, since = "3.24")
```
Comment (gsmet) [inline core/deployment/src/main/java/io/quarkus/deployment/configuration/ConfigMappingUtils.java]:
```suggestion
    @Deprecated(forRemoval = true, since = "3.25")
```

**Review by gsmet — COMMENTED** [review]
I'm fine with merging this as is but I spotted a few minor things that need adjustments.

File: core/deployment/src/main/java/io/quarkus/deployment/ExtensionLoaderConfig.java (hunk 3 above)
Comment (radcortez) [reply core/deployment/src/main/java/io/quarkus/deployment/ExtensionLoaderConfig.java]: Sure.

File: core/deployment/src/main/java/io/quarkus/deployment/ExtensionLoader.java (hunk 2 above)
Comment (radcortez) [reply core/deployment/src/main/java/io/quarkus/deployment/ExtensionLoader.java]: Yes, it's `RuntimeValue`.

File: core/deployment/src/main/java/io/quarkus/deployment/ExtensionLoader.java (hunk 1 above)
Comment (radcortez) [reply core/deployment/src/main/java/io/quarkus/deployment/ExtensionLoader.java]: > TBH I didn't know you could inject it in the @Recorder constructor, it's news to me.

The injection at the Recorder constructor has been there for a while. It was added here: https://github.com/quarkusio/quarkus/pull/18983

> This makes things still a bit confusing though as you can have static init recorded methods too and the field won't be available then. Not saying we should change anything but it's still not completely ideal.

That is why we want to mandate the use of  `RuntimeValue`. If you try to use it in static init, it will give you an exception.

> TBH, I wondered a few times if we should split the recorder in two as it's very confusing to have static init and runtime init methods mixed. But that's something for the future.

I agree that is something that we should discuss and improve.

Comment (dmlloyd) [reply core/deployment/src/main/java/io/quarkus/deployment/ExtensionLoader.java]: FWIW I have a mid- to long-term goal to completely get rid of recorders altogether and replace it with something easier to use and harder to mess up. So I wouldn't worry a whole lot about making them perfect.

**Review by gsmet — APPROVED** [review]
