### PR TITLE
OIDC: Fix IllegalStateException when processing opaque tokens

### LINKED ISSUE #12755: OIDC introspection of opaque access-token does not fill principal of SecurityIdentity
**Describe the bug**
My service uses OIDC (application-type=service) and is called with an **opaque access-token**. The REST endpoints are protected with @RolesAllowed annotations.

Because of the opaque access-token, the introspect endpoint is called by Quarkus/Vert.x to get the JWT.
Because my identity-provider is **ForgeRock** the response of the introspection endpoint does not contain a key "username" but "user_id".

Response:
```json
{
  "active": true,
  "scope": "openid profile email myroles",
  "client_id": "***",
  "user_id": "***",
  "token_type": "Bearer",
  "exp": 1602839252,
  "sub": "***",
  "iss": "***",
  "auth_level": 1000,
  "auditTrackingId": "***"
}
```

The Vert.x and Quarkus-implementation expect the "username" key, so the principal of the SecurityIdentity is not filled.
image

See:
- io.quarkus.oidc.runtime.OidcIdentityProvider.validateTokenWithOidcServer
- io.vertx.ext.auth.oauth2.impl.OAuth2TokenImpl.introspect

**Expected behavior**
Principal of SecurityIdentity gets filled.

**Actual behavior**
Principal is null

**Configuration**
```properties
quarkus.oidc.application-type=service
quarkus.oidc.auth-server-url=***
quarkus.oidc.client-id=***
quarkus.oidc.credentials.client-secret.value=***
quarkus.oidc.token.issuer=***

quarkus.oidc.authentication.user-info-required=true
quarkus.oidc.roles.source=userinfo
quarkus.oidc.roles.role-claim-path=myroles
quarkus.oidc.discovery-enabled=false
quarkus.oidc.introspection-path=/introspect
quarkus.oidc.user-info-path=/userinfo
```

**Environment (please complete the following information):**
 - Quarkus version or git rev: 1.9.0.CR1

### PR DESCRIPTION
**Pull request by KarstenWintermann**
OIDC: Fix IllegalStateException when processing opaque tokens from OIDC providers which do not fill the "username" field in the response from "introspect" call, falls back to "sub" field instead (fixes #12755)

### CODE REVIEW

**Comment by sberyozkin** [comment]
@KarstenWintermann Thanks for this PR. Having a fallback to `sub` makes perfect sense to me. I've been considering to support detecting a user name in the introspection response similarly to the way it is done for JWT (`upn` -> `sub` -> `preferredUserName`, etc) and indeed as you also suggested to get it configured (such that it can be picked up even from the complex JSON object, ex, `/a/b/sub` as we do for roles). However that would need to be taken care of as part of a dedicated issue.

Given the side-effect of not setting a principal which you reported about at #12755, I was considering to suggest enable an `anonymous` status if the name is not detected - but it would be wrong since the principal is active, we just have no name.
So - please make Principal registration non-optional - otherwise, if we have roles picked up - it would be confusing anonymous or null principal and yet RBAC works :-).

Thanks

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java [hunk 1]
```diff
@@ -169,9 +169,16 @@
...
                             OidcUtils.setSecurityIdentityUserInfo(builder, userInfo);
                             OidcUtils.setSecurityIdentityConfigMetadata(builder, resolvedContext);
+                            String principalMember;
                             if (result.introspectionResult.containsKey(OidcConstants.INTROSPECTION_TOKEN_USERNAME)) {
+                                principalMember = OidcConstants.INTROSPECTION_TOKEN_USERNAME;
+                            } else if (result.introspectionResult.containsKey(OidcConstants.INTROSPECTION_TOKEN_SUB)) {
+                                // fallback to "sub", if "username" is not present
+                                principalMember = OidcConstants.INTROSPECTION_TOKEN_SUB;
+                            }
+                            if (!principalMember.isEmpty()) {
```
Comment (sberyozkin) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java:179]: @KarstenWintermann Please remove this condition - this will avoid all the side-effects in case some other provider sets `preferredUserName` for example, etc

**Comment by KarstenWintermann** [comment]
Hello @sberyozkin, I have now changed the PR so that in case neither "username" nor "sub" are present in the response from the "introspect" call, then the principal name will be just "authenticated".

**Comment by sberyozkin** [comment]
Hi @KarstenWintermann Thanks - I'd not be concerned about making sure about a non-empty name is returned - the important indicator is that a SecurityIdentiy would not be anonymous and its roles would not be empty - in such cases - when the name is empty - but it is required - it can give a hint then it was not auto picked up from the introspection response - and the augmentor or endpoint can check it from `UserInfo` or - from the injected introspection response (this one will be supported shortly). 
So I propose to revert this bit (but keep it an empty value)
thanks

**Comment by sberyozkin** [comment]
CC @stuartwdouglas FYI, here, we have a situation where a token has been successfully verified remotely - but the principal name may not be extracted - hence `null` `Principal` - @KarstenWintermann's PR improves the OIDC code to avoid  `QuarkusSecurityIdentityBuilder` failing with ISA (principal is `null`, anonymous is `false`).
I thought OIDC should set `anonymous=true` in such cases - but it would have side-effects - as the token has been verified, roles are available. So now the proposal is for OIDC to return a Principal with an empty name (as opposed to a conventional name like `authenticated`, etc) - the endpoint can then try to get this name from other OIDC content.

**Comment by KarstenWintermann** [comment]
OK, now the principal name will be an emtpy string in case both `username` and `sub` aren't present.

**Comment by sberyozkin** [comment]
@KarstenWintermann Can you please squash ?

**Comment by KarstenWintermann** [comment]
Hello @sberyozkin, please tell me if it looks right now. If not, I'll start over.

**Comment by gsmet** [comment]
Hi Karsten,

I fixed your branch and made it one commit.

For your next contributions, I recommend you to create a specific branch per fix, and also use `rebase` to rebase your PR.

@sberyozkin I'll let you review it.

**Comment by sberyozkin** [comment]
@gsmet Thanks for your help
@KarstenWintermann It all goods now, thanks

**Review by sberyozkin — APPROVED** [review]
It is hard to test it since Keycloak does return `username` - but I might try to add a test when I start working on the introspection response injection
