### PR TITLE
Use initial Quarkus Dev config for test tags and engines

### LINKED ISSUE #42714: Continuous testing exclude-tags or exclude-engines cannot be configured via pom.xml anymore in 3.13
### Describe the bug

Imagine a test with `@Tag("slow")` and the following in `pom.xml`:
```xml
<quarkus.test.exclude-tags>slow</quarkus.test.exclude-tags>
```
As expected, Quarkus 3.12.3 does not execute this test in continuous testing, but Quarkus 3.13.3 (or 3.13.0) does.

Same goes for `quarkus.test.exclude-engines`.

### Expected behavior

Test excluded

### Actual behavior

Test not excluded

### How to Reproduce?

[q_ct-tags.zip](https://github.com/user-attachments/files/16717385/q_ct-tags.zip)

- `mvn quarkus:test` -> test is executed 🔴 
- `mvn quarkus:test -Dquarkus.platform.version=3.12.3` -> test is not executed 🟢 

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

3.13.0-.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.9.8

### Additional information

First discussed here: https://github.com/quarkusio/quarkus/discussions/42326

https://github.com/quarkusio/quarkus/commit/00350b7a84a3a1ec0aee49be9e848c84cda2bafd broke it.

You cannot use `application-test.properties` either, but that has never worked AFAICS.

`mvn ... -Dquarkus.test.exclude-tags=slow` does work.

A workaround can be found here: https://github.com/quarkusio/quarkus/discussions/42326#discussioncomment-10276264

### PR DESCRIPTION
**Pull request by radcortez**
- Fixes #42714

It worked before because https://github.com/quarkusio/quarkus/blob/7206ac0ba8156f5e0f23642457b4999bc6e5c586/core/deployment/src/main/java/io/quarkus/deployment/dev/testing/TestTracingProcessor.java#L95-L102 sets the tags and engines config from the Quarkus Dev config (which includes the configuration coming from the build system).

With the change in https://github.com/quarkusio/quarkus/pull/41317, `handleApplicationPropertiesChange` now sets the reading properties to empty `List` instead of `null`, which makes `Object.equals` to behave differently and override the configuration.

For now, let's fallback to the configuration set by `TestTracingProcessor`, but the goal is to improve this.

Related to:
- https://github.com/quarkusio/quarkus/pull/42715
- https://github.com/quarkusio/quarkus/issues/35693
- https://github.com/quarkusio/quarkus/issues/10233

### CODE REVIEW

**Review by gsmet — APPROVED** [review]

File: core/deployment/src/main/java/io/quarkus/deployment/dev/testing/TestSupport.java [hunk 1]
```diff
@@ -513,20 +513,20 @@ public void addListener(TestListener listener) {
...
-        List<String> includeEngines = getTrimmedListFromConfig(updatedConfig, "quarkus.test.include-engines").orElse(List.of());
-        List<String> excludeEngines = getTrimmedListFromConfig(updatedConfig, "quarkus.test.exclude-engines").orElse(List.of());
+        List<String> includeEngines = getTrimmedListFromConfig(updatedConfig, "quarkus.test.include-engines").orElse(null);
+        List<String> excludeEngines = getTrimmedListFromConfig(updatedConfig, "quarkus.test.exclude-engines").orElse(null);
         TestType testType = updatedConfig.getOptionalValue("quarkus.test.type", TestType.class).orElse(TestType.ALL);
 
         if (!firstRun) {
             if (!Objects.equals(includeTags, appPropertiesIncludeTags)) {
-                this.includeTags = includeTags;
+                this.includeTags = Objects.requireNonNullElse(includeTags, Collections.emptyList());
```
Comment (gsmet) [inline core/deployment/src/main/java/io/quarkus/deployment/dev/testing/TestSupport.java:526]: Merged it but in the future, let's use `List.of()` for empty lists (no need to update it here, it's just a comment for future patches). Thanks!
