### PR TITLE
Fix Flyway & SQL Server native compilation

### LINKED ISSUE #40551: Quarkus 3.10 - Flyway with SQL Server DB failed to compile in native
### Describe the bug

Problem in flyway subsitution with SQL Server database.
Cannot compile in native mode.

### Expected behavior

The native compilation should be possible

### Actual behavior

Native compilation failed with "return type mismatch"

`Error: Return type mismatch:
    public java.lang.Object io.quarkus.flyway.runtime.graal.SQLServerDatabaseTypeSubstitutions.createDatabase(org.flywaydb.core.api.configuration.Configuration,org.flywaydb.core.internal.jdbc.JdbcConnectionFactory,org.flywaydb.core.internal.jdbc.StatementInterceptor)
    public org.flywaydb.core.internal.database.base.Database org.flywaydb.database.sqlserver.SQLServerDatabaseType.createDatabase(org.flywaydb.core.api.configuration.Configuration,org.flywaydb.core.internal.jdbc.JdbcConnectionFactory,org.flywaydb.core.internal.jdbc.StatementInterceptor)
com.oracle.svm.core.util.UserError$UserException: Return type mismatch:
    public java.lang.Object io.quarkus.flyway.runtime.graal.SQLServerDatabaseTypeSubstitutions.createDatabase(org.flywaydb.core.api.configuration.Configuration,org.flywaydb.core.internal.jdbc.JdbcConnectionFactory,org.flywaydb.core.internal.jdbc.StatementInterceptor)
    public org.flywaydb.core.internal.database.base.Database org.flywaydb.database.sqlserver.SQLServerDatabaseType.createDatabase(org.flywaydb.core.api.configuration.Configuration,org.flywaydb.core.internal.jdbc.JdbcConnectionFactory,org.flywaydb.core.internal.jdbc.StatementInterceptor)
`

### How to Reproduce?

Reproducer can be found here : https://github.com/Vinche59/flyawy-sqlserver-native-reproducer

Just try to compile in native: mvn -Pnative clean package

### Output of `uname -a` or `ver`

Linux Asguard 5.15.0-106-generic #116-Ubuntu SMP Wed Apr 17 09:17:56 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "22" 2024-03-19 OpenJDK Runtime Environment Temurin-22+36 (build 22+36) OpenJDK 64-Bit Server VM Temurin-22+36 (build 22+36, mixed mode, sharing)

### Mandrel or GraalVM version (if different from Java)

Mandrel 24

### Quarkus version or git rev

3.10

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.1

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Vinche59**
- Fixes: #40551

### CODE REVIEW

File: extensions/flyway/runtime/src/main/java/io/quarkus/flyway/runtime/graal/SQLServerDatabaseTypeSubstitutions.java [hunk 1]
```diff
@@ -15,9 +16,11 @@
...
 
     @Substitute
-    public Object createDatabase(Configuration configuration, JdbcConnectionFactory jdbcConnectionFactory,
+    public Database createDatabase(Configuration configuration,
+            JdbcConnectionFactory jdbcConnectionFactory,
             StatementInterceptor statementInterceptor) {
-        return new SQLServerDatabaseSubstitution(configuration, jdbcConnectionFactory, statementInterceptor);
+        return ((Database) (Object) new SQLServerDatabaseSubstitution(configuration, jdbcConnectionFactory,
+                statementInterceptor));
     }
```
Comment (geoand) [inline extensions/flyway/runtime/src/main/java/io/quarkus/flyway/runtime/graal/SQLServerDatabaseTypeSubstitutions.java:24]: I assume that all is needed is:

```java
    @Substitute
    public Database createDatabase(Configuration configuration, JdbcConnectionFactory jdbcConnectionFactory,
            StatementInterceptor statementInterceptor) {
        return new SQLServerDatabaseSubstitution(configuration, jdbcConnectionFactory, statementInterceptor);
    }
```

correct?

File: extensions/flyway/runtime/src/main/java/io/quarkus/flyway/runtime/graal/SQLServerDatabaseTypeSubstitutions.java [hunk 2]
```diff
@@ -15,9 +16,11 @@
 public final class SQLServerDatabaseTypeSubstitutions {
```
Comment (gastaldi) [inline extensions/flyway/runtime/src/main/java/io/quarkus/flyway/runtime/graal/SQLServerDatabaseTypeSubstitutions.java:16]: I wonder if the substitution class can be removed. @Vinche59 Can you give it a try?

Comment (gsmet) [reply extensions/flyway/runtime/src/main/java/io/quarkus/flyway/runtime/graal/SQLServerDatabaseTypeSubstitutions.java:16]: Yeah I think we would just get rid of this class entirely.

Comment (gastaldi) [reply extensions/flyway/runtime/src/main/java/io/quarkus/flyway/runtime/graal/SQLServerDatabaseTypeSubstitutions.java:16]: I just tested locally. Removing the class entirely resolves the problem

Comment (geoand) [reply extensions/flyway/runtime/src/main/java/io/quarkus/flyway/runtime/graal/SQLServerDatabaseTypeSubstitutions.java:16]: Nice!

**Review by gsmet — APPROVED** [review]
I adjusted the PR to drop the class entirely.

Thanks a lot for raising the issue and creating the PR. We will make sure it's in the next 3.10.

File: extensions/flyway/runtime/src/main/java/io/quarkus/flyway/runtime/graal/SQLServerDatabaseTypeSubstitutions.java (hunk 2 above)
Comment (Vinche59) [reply extensions/flyway/runtime/src/main/java/io/quarkus/flyway/runtime/graal/SQLServerDatabaseTypeSubstitutions.java]: Sorry was afk this afternoon.
I confirm that removing the class entirely fixes also my problem.
Thank you.
