### PR TITLE
Document and validate Quarkus Security extension must be present for CSRF programmatic set up

### LINKED ISSUE #51330: CSRF programmatic API doesn't work
### Describe the bug

Using CSRF programmatic setup API from https://github.com/quarkusio/quarkus/pull/49618. When I setup an app with programmatic CSRF setup, as described [here](https://quarkus.io/guides/security-csrf-prevention#csrf-prevention-programmatic-set-up). After starting the app it will fail with:
```
...
Caused by: java.lang.IllegalStateException: Please add an extension that provides a CSRF prevention feature, for example the Quarkus REST Cross-Site Request Forgery Prevention `quarkus-rest-csrf` extension
...
```
even though I have the extension `io.quarkus:quarkus-rest-csrf` added.

### Expected behavior

App will start without problem.

### Actual behavior

App crashes during start.

### How to Reproduce?

Reproducer - https://github.com/mocenas/reproducer-quarkus-csrf-not-working
Try to run it with `quarkus dev`

Reproducer created from guide https://quarkus.io/guides/security-csrf-prevention just by steps:
```
quarkus create app org.acme:security-csrf-prevention \
    --extension='rest-csrf' \
    --no-code
cd security-csrf-prevention
```
Add `csrfToken.html` and `UserNameResource`.
Add class [CsrfProgrammaticConfig](https://quarkus.io/guides/security-csrf-prevention#csrf-prevention-programmatic-set-up).
Run with `quarkus dev`

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

17

### Quarkus version or git rev

3.30.1  (or also 999-SNAPSHOT)

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by michalvavrik**
- closes https://github.com/quarkusio/quarkus/issues/51330

### CODE REVIEW

File: extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/HttpSecurityProcessor.java [hunk 1]
```diff
@@ -303,21 +303,30 @@ void createHttpAuthenticationHandler(HttpSecurityRecorder recorder, Capabilities
...
+                                //     return new io.quarkus.something.CsfrBuilder();
+                                // }
+                                var builderInstance = mc.newInstance(MethodDescriptor.ofConstructor(csrfBuilderClass));
+                                mc.returnValue(mc.checkCast(builderInstance, CSRF.Builder.class));
+                            } else {
+                                // static Builder builder() {
+                                //     throw new IllegalStateException("The 'security' capability is missing. Please add the Quarkus Security extension");
+                                // }
+                                mc.throwException(IllegalStateException.class,
+                                        "The 'security' capability is missing. Please add the Quarkus Security extension");
```
Comment (geoand) [inline extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/HttpSecurityProcessor.java]:
```suggestion
                                mc.throwException(IllegalStateException.class,
                                        "Please add the `quarkus-security` extension");
```

Comment (michalvavrik) [reply extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/HttpSecurityProcessor.java]: Makes sense, I had something like that originally, just wasn't sure if some explanation is needed.

**Review by geoand — APPROVED** [review]

**Review by sberyozkin — APPROVED** [review]
