### PR TITLE
Copy RestClient interface annotations to generated class

### LINKED ISSUE #22764: interceptor bindings on RestClient interfaces don't work with RestClient Reactive
### Describe the bug

If I have a RestClient interface like this:

```java
@RegisterRestClient(baseUri = "http://localhost:8080")
@CircuitBreaker(requestVolumeThreshold = 4)
public interface HelloClient {
    @GET
    @Path("/ft-hello")
    String hello();
}
```

and use RestClient Reactive together with Fault Tolearnce, the circuit breaker doesn't work. If I put the `@CircuitBreaker` annotation on the `hello` method, the circuit breaker works just fine.

This is caused by RestClient Reactive not copying annotations from the interface itself to the generated class (though annotations from RestClient methods are copied to the generated methods).

### Expected behavior

Interceptor bindings declared on the RestClient interface itself work with RestClient Reactive.

### Actual behavior

Interceptor bindings declared on the RestClient interface itself _don't_ work with RestClient Reactive.

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Ladicek**
When RestClient Reactive generates the implementation class, it does
not copy interface-level annotations to the generated class (though
it does copy annotations from RestClient methods). This means that
interceptor bindings declared on the interface itself don't work.

With this commit, RestClient Reactive will copy all annotations
declared on the RestClient interface (with the exception of
a scope annotation and some MicroProfile RestClient annotations)
to the generated class. This includes interceptor bindings, too.

Fixes #22764

### CODE REVIEW

File: extensions/resteasy-reactive/rest-client-reactive/deployment/src/main/java/io/quarkus/rest/client/reactive/deployment/RestClientReactiveProcessor.java [hunk 1]
```diff
@@ -94,6 +96,14 @@
     private static final String DISABLE_SMART_PRODUCES_QUARKUS = "quarkus.rest-client.disable-smart-produces";
     private static final String KOTLIN_INTERFACE_DEFAULT_IMPL_SUFFIX = "$DefaultImpls";
 
+    private static final Set<DotName> SKIP_COPYING_ANNOTATIONS_TO_GENERATED_CLASS = Set.of(
+            REGISTER_REST_CLIENT,
+            REGISTER_PROVIDER,
+            REGISTER_PROVIDERS,
+            CLIENT_HEADER_PARAM,
+            CLIENT_HEADER_PARAMS,
+            REGISTER_CLIENT_HEADERS);
```
Comment (Ladicek) [inline extensions/resteasy-reactive/rest-client-reactive/deployment/src/main/java/io/quarkus/rest/client/reactive/deployment/RestClientReactiveProcessor.java:105]: Hi @michalszynkiewicz, I could use your help here :-)

Basically what I do in this PR is that I take _all_ annotations from the RestClient interface and copy them to the generated class, with the exception of several well-known RestClient annotations defined here. Does that list make sense to you?

(Alternatively, I could only copy interceptor binding annotations. That would fix the original bug as well, but I have this hunch that some other cases would be left uncovered. Technically, thinking about it, in the present state, one could even put a scope annotation on the interface and it would be propagated to the generated class, which I'm not sure is expected, but it feels kinda nice :-) )

Comment (Ladicek) [reply extensions/resteasy-reactive/rest-client-reactive/deployment/src/main/java/io/quarkus/rest/client/reactive/deployment/RestClientReactiveProcessor.java:105]: (Actually looking at it, if someone added a scope annotation to the interface, it would indeed be copied to the generated class, where it would clash with another scope annotation generated by this processor. So that's a terrible example and perhaps a reason to reconsider...)

File: extensions/resteasy-reactive/rest-client-reactive/deployment/src/main/java/io/quarkus/rest/client/reactive/deployment/RestClientReactiveProcessor.java [hunk 2]
```diff
@@ -525,7 +550,7 @@ private ScopeInfo computeDefaultScope(Capabilities capabilities, Config config,
             if (scopeToUse == null) {
                 log.warnf("Unsupported default scope {} provided for rest client {}. Defaulting to {}",
                         scope, restClientInterface.name(), globalDefaultScope.getName());
-                scopeToUse = BuiltinScope.DEPENDENT.getInfo();
+                scopeToUse = globalDefaultScope.getInfo();
```
Comment (Ladicek) [inline extensions/resteasy-reactive/rest-client-reactive/deployment/src/main/java/io/quarkus/rest/client/reactive/deployment/RestClientReactiveProcessor.java:553]: As I was going over the Cork and Kerry Mountains, eh, over the code in this processor, this seemed like an obvious bug, so I thought I could just fix it.

**Comment by Ladicek** [comment]
Rebased to give me an excuse to ping @michalszynkiewicz again :-)

File: extensions/resteasy-reactive/rest-client-reactive/deployment/src/main/java/io/quarkus/rest/client/reactive/deployment/RestClientReactiveProcessor.java (hunk 1 above)
Comment (michalszynkiewicz) [reply extensions/resteasy-reactive/rest-client-reactive/deployment/src/main/java/io/quarkus/rest/client/reactive/deployment/RestClientReactiveProcessor.java:106]: I think it would be nice to support scope annotations on interfaces, the interceptor can be modified to not add in this case, no?

Comment (Ladicek) [reply extensions/resteasy-reactive/rest-client-reactive/deployment/src/main/java/io/quarkus/rest/client/reactive/deployment/RestClientReactiveProcessor.java:106]: Scope annotations are already supported, the `computeDefaultScope` method looks for them on the interface (unless there's a configuration override).

**Review by michalszynkiewicz — APPROVED** [review]

**Comment by michalszynkiewicz** [comment]
thanks @Ladicek !
