### PR TITLE
Clear the /tmp folder on first dev mode start

### LINKED ISSUE #15537: Quarkus 1.12.1.Final swagger-ui endpoint under /q is broken: stale content in tmp
I have issue with swagger-ui endpoint

````
2021-03-08 07:46:18,870 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, hibernate-validator, kubernetes, kubernetes-client, logging-manager, rest-client, resteasy, resteasy-jackson, smallrye-context-propagation, smallrye-fault-tolerance, smallrye-health, smallrye-metrics, smallrye-openapi, swagger-ui]

mvn clean quarkus:dev
````

with swagger-ui I obtain a white page with those errors
````
GET http://localhost:8383/q/swagger-ui/style.css net::ERR_ABORTED 404 (Not Found)
(index):16 GET http://localhost:8383/q/swagger-ui/swagger-ui-bundle.js net::ERR_ABORTED 404 (Not Found)
(index):17 GET http://localhost:8383/q/swagger-ui/swagger-ui-standalone-preset.js net::ERR_ABORTED 404 (Not Found)
(index):6 GET http://localhost:8383/q/swagger-ui/swagger-ui.css net::ERR_ABORTED 404 (Not Found)
(index):7 GET http://localhost:8383/q/swagger-ui/theme-feeling-blue.css net::ERR_ABORTED 404 (Not Found)
(index):17 GET http://localhost:8383/q/swagger-ui/swagger-ui-standalone-preset.js net::ERR_ABORTED 404 (Not Found)
(index):21 Uncaught ReferenceError: SwaggerUIBundle is not defined
    at window.onload ((index):21)
window.onload @ (index):21
load (async)
(anonymous) @ (index):20
favicon.ico:1 GET http://localhost:8383/q/swagger-ui/favicon.ico 404 (Not Found)
````

image

with http://localhost:8383/q/dev/

in the browser console we have this : 
````
http://localhost:8383/q//dev/resources/css/bootstrap.min.css net::ERR_ABORTED 404 (Not Found)
````
image

### PR DESCRIPTION
**Pull request by phillip-kruger**
As discussed in #15537, this PR will also clean the /tmp folder on the first mvn quarkus:dev run.

Fix #15537

Signed-off-by:Phillip Kruger <phillip.kruger@gmail.com>

### CODE REVIEW

**Comment by gsmet** [comment]
Frankly, I think in dev mode, we should push that content to the build dir e.g. `target/` for Maven and whatever it is for Gradle.

We would probably have to clean it anyway but at least a clean would clean it too.

**Comment by phillip-kruger** [comment]
@gsmet thanks. Do you want me to do that now as part of this PR? Or as a follow up?

File: core/deployment/src/main/java/io/quarkus/deployment/util/WebJarUtil.java [hunk 1]
```diff
@@ -121,7 +125,10 @@ public static Path copyResourcesForDevOrTest(CurateOutcomeBuildItem curateOutcom
 
         // Clean if not in dev mode or if the resources jar is a snapshot version
         if (!launchMode.getLaunchMode().equals(LaunchMode.DEVELOPMENT)
-                || resourcesArtifact.getVersion().contains(SNAPSHOT_VERSION)) {
+                || resourcesArtifact.getVersion().contains(SNAPSHOT_VERSION)
+                || (launchMode.getLaunchMode().equals(LaunchMode.DEVELOPMENT) && !liveReloadBuildItem.isLiveReload())) {
+
+            LOG.info("Clearing static content in [" + deploymentPath + "]");
```
Comment (gsmet) [inline core/deployment/src/main/java/io/quarkus/deployment/util/WebJarUtil.java:131]: I would remove the info.

**Review by gsmet — APPROVED** [review]
