### PR TITLE
Quartz - Defer driver discovery to runtime in order to provide more flexibility to users

### LINKED ISSUE #48545: Quartz select datasource at runtime
### Describe the bug

My quarkus application has two datasources (postgres, mssql), but I activate only one at runtime.

I want quartz to use the active datasource as well. So I created a `ConfigSourceInterceptor`for `quarkus.quartz.datasource`, so that quartz also uses the active datasource. However, the datasource seems to be determined at build time instead of runtime. 

Configuration in `application.properties`
```
quarkus.datasource.postgresql.active=false
quarkus.datasource.postgresql.db-kind=postgresql
quarkus.datasource.postgresql.username=foo
quarkus.datasource.postgresql.jdbc.url=jdbc:postgresql://localhost:5432/test

quarkus.datasource.mssql.active=false
quarkus.datasource.mssql.db-kind=mssql
quarkus.datasource.mssql.username=foo
quarkus.datasource.mssql.jdbc.url=jdbc:sqlserver://localhost:1433;databaseName=test

quarkus.scheduler.start-mode=forced
quarkus.quartz.store-type=jdbc-cmt
quarkus.quartz.clustered=true
quarkus.quartz.serialize-job-data=true
```

```
@Priority(Priorities.APPLICATION + 200)
public class QuartzDatasourceInterceptor implements ConfigSourceInterceptor
{
	@Serial
	private static final long serialVersionUID = 367246512037404779L;

	private static final String QUARTZ_DATASOURCE_CONFIG_PROPERTY = "quarkus.quartz.datasource";

	@Override
	public ConfigValue getValue(final ConfigSourceInterceptorContext context, final String name)
	{
		if(QUARTZ_DATASOURCE_CONFIG_PROPERTY.equals(name))
		{
			if(isDatasourceActive(context, "postgresql"))
			{
				return new ConfigValue.ConfigValueBuilder()
					.withName(QUARTZ_DATASOURCE_CONFIG_PROPERTY)
					.withValue("postgresql")
					.build();
			}

			if(isDatasourceActive(context, "mssql"))
			{
				return new ConfigValue.ConfigValueBuilder()
					.withName(QUARTZ_DATASOURCE_CONFIG_PROPERTY)
					.withValue("mssql")
					.build();
			}

			ConfigLogging.log.fatal("Could not find active datasource");
			return null;
		}
		else
		{
			return doLocked(() -> context.proceed(name));
		}
	}

	private boolean isDatasourceActive(final ConfigSourceInterceptorContext context, String datasourceName)
	{
		ConfigValue configValue = doLocked(() -> context.restart("quarkus.datasource." + datasourceName + ".active"));
		boolean isActive = Boolean.parseBoolean(configValue.getValue());
		ConfigLogging.log.info(datasourceName + " active: " + isActive);
		return isActive;
	}
}
```

### Expected behavior

There is a way to choose `quarkus.quartz.datasource` at runtime

### Actual behavior

If i build with both datasources inactive I get `Build step io.quarkus.quartz.deployment.QuartzProcessor#driver threw an exception: io.quarkus.runtime.configuration.ConfigurationException: JDBC Store configured but the 'default' datasource is not configured properly. You can configure your datasource by following the guide available at: https://quarkus.io/guides/datasource`.

If I build with one datasource enabled, `quarkus.quartz.datasource` seems to be fixed to that datasource. If changed at runtime I get SQL exceptions such as `Failure obtaining db row lock: ERROR: syntax error at or near "WITH"`

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`
```
openjdk version "21.0.6" 2025-01-21 LTS
OpenJDK Runtime Environment Temurin-21.0.6+7 (build 21.0.6+7-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.6+7 (build 21.0.6+7-LTS, mixed mode, sharing)
```

### Quarkus version or git rev

3.20.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

```
Apache Maven 3.9.9 (8e8579a9e76f7d015ee5ec7bfcdc97d260186937)
Maven home: /opt/homebrew/Cellar/maven/3.9.9/libexec
Java version: 21.0.6, vendor: Eclipse Adoptium, runtime: /Library/Java/JavaVirtualMachines/temurin-21.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "15.5", arch: "aarch64", family: "mac"
```
### Additional information

_No response_

### PR DESCRIPTION
**Pull request by manovotn**
Resolves #48545

### CODE REVIEW

**Comment by manovotn** [comment]
~~Deliberately kept a draft for now as I have yet to verify this with a case similar to what was reported in the issue.
Our own testing does not contain a dual DB setup.~~

EDIT: I have tested this with the reproducer provided by the user (see [this comment](https://github.com/quarkusio/quarkus/issues/48545#issuecomment-3003935472)) and it passes.

File: extensions/quartz/deployment/src/main/java/io/quarkus/quartz/deployment/QuartzProcessor.java [hunk 1]
```diff
@@ -250,7 +224,20 @@ List<ReflectiveClassBuildItem> reflectiveClasses(QuartzBuildTimeConfig config,
             reflectiveClasses.add(ReflectiveClassBuildItem.builder(Connection.class)
                     .reason(getClass().getName()).methods()
                     .fields().build());
-            reflectiveClasses.add(ReflectiveClassBuildItem.builder(driverDialect.getDriver().get())
+            // Since we determine driver delegate at runtime, we need to register all of them
```
Comment (manovotn) [inline extensions/quartz/deployment/src/main/java/io/quarkus/quartz/deployment/QuartzProcessor.java]: Now that I think about it, my change is incorrect.
For a custom driver, we still need to register its class for reflection and if there is none, we should register all of the built-in classes.

**Comment by manovotn** [comment]
I am aware that this PR does not move the build time config property into runtime config because I am frankly not sure if that would be breaking - technically it will have the same name but anything operating with the build time config might be affected by it. We could also temporarily duplicate them in both and deprecate one.

Anyhow, @mkouba thoughts on the approach in this PR and the config change? :)

File: extensions/quartz/deployment/src/main/java/io/quarkus/quartz/deployment/QuartzProcessor.java [hunk 2]
```diff
@@ -250,12 +224,32 @@ List<ReflectiveClassBuildItem> reflectiveClasses(QuartzBuildTimeConfig config,
...
-            reflectiveClasses.add(ReflectiveClassBuildItem.builder("io.quarkus.quartz.runtime.QuartzSchedulerImpl$InvokerJob")
-                    .reason(getClass().getName())
-                    .methods().fields().build());
+            // For a custom delegate, register its class; otherwise, register all built-in delegates
+            if (driverDialect.getDriver().isPresent()) {
+                reflectiveClasses.add(ReflectiveClassBuildItem.builder(driverDialect.getDriver().get())
+                        .reason(getClass().getName())
+                        .methods().build());
+            } else {
+                reflectiveClasses.add(ReflectiveClassBuildItem.builder(QuarkusDBv8Delegate.class.getName())
```
Comment (gsmet) [inline extensions/quartz/deployment/src/main/java/io/quarkus/quartz/deployment/QuartzProcessor.java]: Can't you register for reflection only the dialects that could be triggered by the available `JdbcDataSourceBuildItem`?

**Comment by mkouba** [comment]
I can't say that I completely understand the use case :thinking:. 

If a user sets the `quarkus.quartz.datasource` then we should IMO still try to use this DS and fail at build time if not available. If the `quarkus.quartz.datasource` is not set (i.e. the default DS should be used) then we could defer the driver discovery to runtime. Am I missing something?

File: extensions/quartz/deployment/src/main/java/io/quarkus/quartz/deployment/QuartzProcessor.java (hunk 2 above)
Comment (manovotn) [reply extensions/quartz/deployment/src/main/java/io/quarkus/quartz/deployment/QuartzProcessor.java]: Not sure I follow.
The use case here is to delay choosing the datasource until runtime, so how would I know which one to register?

**Comment by manovotn** [comment]
> I can't say that I completely understand the use case 🤔.

Take a look at the discussion on the issue - https://github.com/quarkusio/quarkus/issues/48545#issuecomment-2997012387
The reproducer is also a nice depiction of it.

> If a user sets the `quarkus.quartz.datasource` then we should IMO still try to use this DS and fail at build time if not available. If the `quarkus.quartz.datasource` is not set (i.e. the default DS should be used) then we could defer the driver discovery to runtime. Am I missing something?

Maybe I don't fully understand but it seems that wouldn't work here.
In this case, the reproducer contains `ConfigSourceInterceptor` - an interceptor for config value of `quarkus.quartz.datasource`. And it returns either `postgresql` or `mssql` based on which datasource is active.
And the activity of datasource is determined at runtime.
So whatever information about `quarkus.quartz.datasource` you read during build time might not reflect reality at runtime.

Of course it is a matter of how much runtime flexibility we want to give it. This PR is just my attempt at grasping the use case and coming up with something that would make the reproducer pass.

**Comment by mkouba** [comment]
> > I can't say that I completely understand the use case 🤔.
> 
> Take a look at the discussion on the issue - [#48545 (comment)](https://github.com/quarkusio/quarkus/issues/48545#issuecomment-2997012387) The reproducer is also a nice depiction of it.
> 
> > If a user sets the `quarkus.quartz.datasource` then we should IMO still try to use this DS and fail at build time if not available. If the `quarkus.quartz.datasource` is not set (i.e. the default DS should be used) then we could defer the driver discovery to runtime. Am I missing something?
> 
> Maybe I don't fully understand but it seems that wouldn't work here. In this case, the reproducer contains `ConfigSourceInterceptor` - an interceptor for config value of `quarkus.quartz.datasource`. And it returns either `postgresql` or `mssql` based on which datasource is active. And the activity of datasource is determined at runtime. So whatever information about `quarkus.quartz.datasource` you read during build time might not reflect reality at runtime.
> 
> Of course it is a matter of how much runtime flexibility we want to give it. This PR is just my attempt at grasping the use case and coming up with something that would make the reproducer pass.

My point is - if a user sets `quarkus.quartz.datasource=foo` then the `foo` DS should be used no matter what. Currently, it's a build time property so we can validate the existence of DS etc. If no DS is set then we fall back to the default DS. Which is also fine. 

Now, it seems that the user needs to define multiple data sources, deactivate some and select one  for Quartz at runtime. This means we would need to relax the validation at build time. Which is :-1:.

Also I think it's breaking because the behavior's changed. And the `ConfigSourceInterceptor` completely ignores the value set by the user which is IMO weird.

The question is: could we introduce two new config properties that would be used if no DS is selected at build time (`quarkus.quartz.datasource` is not used). I.e. something like `quarkus.quartz.datasource.none-selected-strategy` (buildtime) with values `default` - use the default DS (current behavior), `defer` - select the DS at runtime. And then `quarkus.quartz.datasource.deferred-name` (runtime), only used if `quarkus.quartz.datasource.none-selected-strategy=defer`, that could be set by the `ConfigSourceInterceptor` or even build item. WDYM?

File: extensions/quartz/deployment/src/main/java/io/quarkus/quartz/deployment/QuartzProcessor.java (hunk 2 above)
Comment (gsmet) [reply extensions/quartz/deployment/src/main/java/io/quarkus/quartz/deployment/QuartzProcessor.java]: A `JdbcDataSourceBuildItem` has a `dbKind` that is fixed at build time. So from them, you can deduce the list of databases that you have to support.

E.g. you have two datasources, one MySQL, one PostgreSQL, the `dbKind` of the datasources is defined at build so you know which ones might be useful, you don't need to register for reflection all of them.

Note: we also need to support when the kind is something we don't know, but I think we currently push something generic in this case? And you can hardcode it anyway.

**Comment by manovotn** [comment]
> And the `ConfigSourceInterceptor` completely ignores the value set by the user which is IMO weird.

Yes but that's not what the reproducer does. In it, there is no value set by user and only the interceptor exists so that it can give you the config value "dynamically", so to speak.

> Also I think it's breaking because the behavior's changed. 

Breaking in what way? Currently you'd only not get as fast failure if you misconfigured it but otherwise it should appear to behave equally on the outside?

> Now, it seems that the user needs to define multiple data sources, deactivate some and select one for Quartz at runtime. This means we would need to relax the validation at build time. Which is 👎.

It is not the first time we hear about the need to have multiple DS, it's just that Quartz bit didn't have to deal with it yet.
I agree that having as much as possible done in build time is the way to go of course.

> The question is: could we introduce two new config properties that would be used if no DS is selected at build time (quarkus.quartz.datasource is not used). I.e. something like quarkus.quartz.datasource.none-selected-strategy (buildtime) with values default - use the default DS (current behavior), defer - select the DS at runtime. And then quarkus.quartz.datasource.deferred-name (runtime), only used if quarkus.quartz.datasource.none-selected-strategy=defer, that could be set by the ConfigSourceInterceptor or even build item. WDYM?

Hm, interesting idea. However, in such a case, wouldn't it be easier to keep `quarkus.quartz.datasource` as is and just add something like `quarkus.quartz.datasource.defer-resolution` (default `false` of course)? The latter would just control whether we attempt to read and resolve the datasource property in build or runtime.
As far as I am concerned, the less configuration knobs, the better :)

**Comment by mkouba** [comment]
> However, in such a case, wouldn't it be easier to keep quarkus.quartz.datasource as is as is...

The idea is to keep `quarkus.quartz.datasource` as is, which means a build time config property.

> The latter would just control whether we attempt to read and resolve the datasource property in build or runtime.

I don't think it's a good idea. You can't treat a build config property as runtime and vice versa. They are processed differently. I.e. there is no way to tell Quarkus that `quarkus.quartz.datasource` is a build time property when `quarkus.quartz.datasource.defer-resolution=false`.

File: extensions/quartz/deployment/src/main/java/io/quarkus/quartz/deployment/QuartzProcessor.java (hunk 2 above)
Comment (manovotn) [reply extensions/quartz/deployment/src/main/java/io/quarkus/quartz/deployment/QuartzProcessor.java]: Ah, right I get it now.
+1, that makes sense

**Comment by manovotn** [comment]
> You can't treat a build config property as runtime and vice versa. 

Well, it is available in both and we'd mostly process it in build time anyway but I get that it's not right on the theoretical level.
Guess I am simply not a fan of having two extra properties just for this one special case.

Either way, I will revert this to draft, circle back to it early next week and try to come up with something more profound :)

**Comment by mkouba** [comment]
> Well, it is available in both and we'd mostly process it in build time anyway but I get that it's not right on the theoretical level.

There is more to it. Runtime and build-time properties are processed differently which might lead to strange and/or well-hidden errors. There are things like `RunTimeConfigurationDefaultBuildItem` etc. :shrug:

**Comment by manovotn** [comment]
I've reworked the PR and there are now two new config knobs:
* Build time boolean config `deferDatasourceCheck` (default `false`) which can be used to indicate that DS resolution should be deferred
  * Combining this with the definition of DS at build time results in an exception
* Runtime config `deferredDatasourceName` (`String`) which can be used to specify the name of the DS at runtime
  * This will only be used if the resolution wasn't completed in build time already

Furthermore the classes registered for reflection in case of deferred resolution are now curated based on the set of known JDBC DS build items (as per Guillaume's comment).

I've also tested this with the user provided dual-DB [reproducer](https://github.com/manovotn/quarkus-reproducer-48545) and got a pass.

**Comment by manovotn** [comment]
The CI failure is definitely related, taking a look...

**Review by mkouba — COMMENTED** [review]
It looks very good but I wonder if we shouldn't add a test as well?

**Comment by manovotn** [comment]
> It looks very good but I wonder if we shouldn't add a test as well?

Done, the following changes are now part of the PR:
* Additional config validation for when runtime DS name is missing and should be present
* Tests for invalid combinations of config knobs
  * Defining a build time DS name and using the defer config at the same time
  * Deferring resolution and not defining the runtime DS name
* Integration test (as a separate commit) with all the knobs for deferred DS setup
  * Unlike the original reproducer, this is simplified and uses only a single non-default DB/DS setup
  * Test-wise this is a clone of the existing `quartz` module, the idea is to assert the same but use runtime DS setup
  * This also exposed a needed extra change in `QuartzSchedulerImpl` which now correctly recognizes the runtime DS config

File: extensions/quartz/deployment/src/main/java/io/quarkus/quartz/deployment/QuartzJDBCDriverDialectBuildItem.java [hunk 3]
```diff
@@ -1,20 +1,40 @@
...
 /**
- * Holds the SQL driver dialect {@link org.quartz.impl.jdbcjobstore.StdJDBCDelegate driver delegate} to use.
+ * Holds the necessary information to determine SQL driver dialect.
+ * <p>
+ * This can mean either a custom driver registered by user or one of Quarkus built-in drivers.
+ * If it is the latter, we defer discovering the driver to runtime, see also {@link io.quarkus.quartz.runtime.QuartzSupport}.
  */
 final class QuartzJDBCDriverDialectBuildItem extends SimpleBuildItem {
     private final Optional<String> driver;
+    private List<JDBCDataSource> dataSources;
```
Comment (mkouba) [inline extensions/quartz/deployment/src/main/java/io/quarkus/quartz/deployment/QuartzJDBCDriverDialectBuildItem.java]:
```suggestion
    private final List<JDBCDataSource> dataSources;
```

File: extensions/quartz/deployment/src/test/java/io/quarkus/quartz/test/InvalidDeferredDatasourceConfigurationTest.java [hunk 4]
```diff
@@ -0,0 +1,54 @@
...
+    static final QuarkusUnitTest test = new QuarkusUnitTest()
+            // add a mock pretending to provide Agroal Capability to pass our validation
+            .addBuildChainCustomizer(new Consumer<BuildChainBuilder>() {
+                @Override
+                public void accept(BuildChainBuilder buildChainBuilder) {
+                    buildChainBuilder.addBuildStep(new BuildStep() {
+                        @Override
+                        public void execute(BuildContext context) {
+                            context.produce(
+                                    new CapabilityBuildItem(Capability.AGROAL, "fakeProvider"));
```
Comment (mkouba) [inline extensions/quartz/deployment/src/test/java/io/quarkus/quartz/test/InvalidDeferredDatasourceConfigurationTest.java:32]: Oh, this mock is actually pretty smart ;-).

File: integration-tests/quartz-deferred-datasource/pom.xml [hunk 5]
```diff
@@ -0,0 +1,164 @@
...
+    <description>The Quartz integration test module for runtime resolved datasource</description>
+
+    <dependencies>
+        <dependency>
+            <groupId>io.quarkus</groupId>
+            <artifactId>quarkus-arc</artifactId>
+        </dependency>
+        <dependency>
+            <groupId>io.quarkus</groupId>
+            <artifactId>quarkus-resteasy</artifactId>
```
Comment (mkouba) [inline integration-tests/quartz-deferred-datasource/pom.xml]: You should probably use `quarkus-rest` instead...

Comment (manovotn) [reply integration-tests/quartz-deferred-datasource/pom.xml]: Ah, thanks for noticing.
This is just copy paste from the other integration test - meaning I will change it in both :)

**Comment by manovotn** [comment]
Addressed all of the comments and rebased onto main.

**Review by mkouba — APPROVED** [review]
