### PR TITLE
Jakarta - Make Infinispan work by using artifacts with the jakarta classifier

### LINKED ISSUE #26984: Jakarta - EE 9 - Infinispan Client IT fails because javax.annotation.Generated is not available
When building the Infinispan Client IT in the `jakarta-rewrite` branch, we get the following failure:

```
Caused by: java.lang.ClassNotFoundException: javax.annotation.Generated
    at java.net.URLClassLoader.findClass (URLClassLoader.java:471)
    at java.lang.ClassLoader.loadClass (ClassLoader.java:589)
    at java.lang.ClassLoader.loadClass (ClassLoader.java:522)
    at org.infinispan.protostream.annotations.impl.processor.AutoProtoSchemaBuilderAnnotationProcessor.addGeneratedClassHeader (AutoProtoSchemaBuilderAnnotationProcessor.java:578)
    at org.infinispan.protostream.annotations.impl.processor.MarshallerSourceCodeGenerator.generateMessageMarshaller (MarshallerSourceCodeGenerator.java:170)
    at org.infinispan.protostream.annotations.impl.processor.MarshallerSourceCodeGenerator.generateMarshaller (MarshallerSourceCodeGenerator.java:58)
    at org.infinispan.protostream.annotations.impl.BaseProtoSchemaGenerator.generateMarshallers (BaseProtoSchemaGenerator.java:203)
    at org.infinispan.protostream.annotations.impl.BaseProtoSchemaGenerator.generateAndRegister (BaseProtoSchemaGenerator.java:174)
    at org.infinispan.protostream.annotations.impl.processor.AutoProtoSchemaBuilderAnnotationProcessor.processClass (AutoProtoSchemaBuilderAnnotationProcessor.java:333)
    at org.infinispan.protostream.annotations.impl.processor.AutoProtoSchemaBuilderAnnotationProcessor.processElement (AutoProtoSchemaBuilderAnnotationProcessor.java:263)
    at org.infinispan.protostream.annotations.impl.processor.AutoProtoSchemaBuilderAnnotationProcessor.process (AutoProtoSchemaBuilderAnnotationProcessor.java:186)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor (JavacProcessingEnvironment.java:980)

```

Several options to fix that:
- test which `@Generated` annotation is available via reflection and use it, instead of blindly use the `javax` one
- switch to a custom `@Generated` annotation hosted in an Infinispan package - this is what Clément did for gRPC
- detect the JDK version and starting from 11 (or use reflection to detect the availability of the annotation), use `javax.annotation.processing.Generated` which is available in the JDK starting 11 instead of the `javax.annotation.Generated` (given only the name of the class is used, it should be an easy switch - obviously you would need to drop the import and use the class names directly)

Note that I have no idea if it's the only problem we will have with Infinispan Client :).

### LINKED ISSUE #27030: Jakarta - EE 9 - Upgrade to Infinispan 14 DEV and use Jakarta artifacts

### PR DESCRIPTION
**Pull request by gsmet**
And also various other fixes related to Infinispan.

Fixes #27030
Fixes #26984

### CODE REVIEW

File: extensions/infinispan-client/deployment/src/main/java/io/quarkus/infinispan/client/deployment/InfinispanClientProcessor.java [hunk 1]
```diff
@@ -71,6 +74,11 @@ class InfinispanClientProcessor {
      */
     InfinispanClientBuildTimeConfig infinispanClient;
 
+    @BuildStep(onlyIf = NativeOrNativeSourcesBuild.class)
```
Comment (Sanne) [inline extensions/infinispan-client/deployment/src/main/java/io/quarkus/infinispan/client/deployment/InfinispanClientProcessor.java:77]: just curious, but isn't this "onlyIf" condition redundant since I'd assume none would otherwise consume a `NativeImageFeatureBuildItem` ?

**Review by Sanne — APPROVED** [review]

File: extensions/infinispan-client/deployment/src/main/java/io/quarkus/infinispan/client/deployment/InfinispanClientProcessor.java (hunk 1 above)
Comment (gsmet) [reply extensions/infinispan-client/deployment/src/main/java/io/quarkus/infinispan/client/deployment/InfinispanClientProcessor.java:77]: I just copied the pattern used elsewhere.

**Comment by tristantarrant** [comment]
Infinispan 14.0.0.CR2 removes the Jakarta classifier and introduces artifacts suffixed by `-jakarta`
