### PR TITLE
Prevent server's OpenTelemetry Context getting lost on client read timeout

### LINKED ISSUE #52239: OpenTelemetry: Context get lost when hitting rest client read timeout
### Describe the bug

OpenTelemetry traceId is not being propagated correctly between two Quarkus applications (A and B) when a downstream API call from A to B exceeds a 30-second response time.
When application A calls an API on application B, and B takes longer than 30 seconds to respond, the traceId is correctly logged in application A, but it appears to be lost in application B. Application B logs the following warning:
`Context in storage not the expected context, Scope.close was not called correctly. Details: OTel context before: {}. OTel context toAttach: {spanId=..., traceId=..., sampled=true, parentId=...}`

### Expected behavior

The expected behavior is that the traceId should be consistently propagated and tracked across both applications for the entire duration of the request, regardless of the response time from the downstream service.

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

3.27.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by brunobat**
The `tryEndSpan()` is needed to avoid double closing the span, if a server side response is made available. 
Additional debug logging was added.

- Fixes: https://github.com/quarkusio/quarkus/issues/52239

### CODE REVIEW

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/instrumentation/vertx/InstrumenterVertxTracer.java [hunk 1]
```diff
@@ -68,8 +68,20 @@ default <R> void sendResponse(
...
-        try (scope) {
-            instrumenter.end(spanOperation.getSpanContext(), (REQ) request, (RESP) response, failure);
+
+        if (failure != null && response == null) {
+            // Connection reset (e.g. client read timeout) can be triggered while a worker is still be running.
+            // Will end the span to record the failure but don't close the scope yet because it would erase the OTel context
+            // and mess with ongoing child spans
+            if (spanOperation.tryEndSpan()) {
+                instrumenter.end(spanOperation.getSpanContext(), (REQ) request, (RESP) response, failure);
+            }
```
Comment (gsmet) [inline extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/instrumentation/vertx/InstrumenterVertxTracer.java]: When will the scope be closed?

**Comment by geoand** [comment]
I can't say I understand this change at all, so I would request that the code be commented more

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/instrumentation/vertx/InstrumenterVertxTracer.java (hunk 1 above)
Comment (brunobat) [reply extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/instrumentation/vertx/InstrumenterVertxTracer.java]: In theory, the scope is stored in the `spanOperation` which will be garbage collected at the end of the request and the close() called at that point.

**Comment by brunobat** [comment]
> I can't say I understand this change at all, so I would request that the code be commented more

Will do. Context propagation is not obvious at all.

**Comment by geoand** [comment]
🙏🏽

**Comment by brunobat** [comment]
Using the provided test this is what happens when the connection is closed on the client side. 

The test executes:
/caller (event-loop thread A) -> rest client (executor thread B) ->  /slow (event-loop thread C) -> sleep (executor thread D)

1. The client call on thread B will timeout
2. This triggers a connection reset in thread C
3. `io.vertx.core.http.impl.Http1xServerRequest#reportRequestReset()` -> `tracer.sendResponse(context, null, trace, err, TagExtractor.empty());` on thread C
4. This causes a scope.close() on thread C

5. Thread A finishes ok with `io.vertx.core.http.impl.Http1xServerConnection#reportResponseComplete` -> `      tracer.sendResponse(request.context, request.response(), trace, null, HttpUtils.SERVER_RESPONSE_TAG_EXTRACTOR);`.
6. Scope.close() happens on thread A

7. Thread D eventually returns and triggers a  `io.vertx.core.http.impl.Http1xServerConnection#reportResponseComplete` -> `tracer.sendResponse(request.context, request.response(), trace, null, HttpUtils.SERVER_RESPONSE_TAG_EXTRACTOR);` on thread C
8. This calls scope.close() again but by this time, the DuplicatedContext was already cleared of the OTel context on step 4.


The PR prevents step 4, therefore not closing the scope and preserving the OTel Context needed for later on step 7
We can discuss whether if a `reportResponseComplete()` should happen after a `reportRequestReset()` but I think that is probably something @vietj can comment on.

This is a record of what happens when we allow the /slow failure to close the scope:
```
11:44:21 DEBUG traceId=, spanId= [io.qu.op.ru.tr.in.ve.HttpInstrumenterVertxTracer] (vert.x-eventloop-thread-1) Server uri path: /caller
11:44:21 DEBUG traceId=, spanId= [io.qu.op.ru.QuarkusContextStorage] (vert.x-eventloop-thread-1) Setting Otel context: {spanId=c65be0192d246d92, traceId=266d88cd6b3d9866fe1b58dc13be7a80, sampled=true}
11:44:21 DEBUG traceId=, spanId= [io.qu.op.ru.OpenTelemetryUtil] (vert.x-eventloop-thread-1) Setting span in MDC: {spanId=c65be0192d246d92, traceId=266d88cd6b3d9866fe1b58dc13be7a80, sampled=true} with otel data in vertx context: {spanId=c65be0192d246d92, traceId=266d88cd6b3d9866fe1b58dc13be7a80, sampled=true}

11:44:21 DEBUG traceId=, spanId= [io.qu.op.ru.tr.in.ve.HttpInstrumenterVertxTracer] (vert.x-eventloop-thread-0) Server uri path: /slow
11:44:21 DEBUG traceId=, spanId= [io.qu.op.ru.QuarkusContextStorage] (vert.x-eventloop-thread-0) Setting Otel context: {spanId=cbe4da89f6f31d22, traceId=266d88cd6b3d9866fe1b58dc13be7a80, sampled=true, parentId=075fa99728edae59}
11:44:21 DEBUG traceId=, spanId= [io.qu.op.ru.OpenTelemetryUtil] (vert.x-eventloop-thread-0) Setting span in MDC: {spanId=cbe4da89f6f31d22, traceId=266d88cd6b3d9866fe1b58dc13be7a80, sampled=true, parentId=075fa99728edae59} with otel data in vertx context: {spanId=cbe4da89f6f31d22, traceId=266d88cd6b3d9866fe1b58dc13be7a80, sampled=true, parentId=075fa99728edae59}

11:44:21 INFO  traceId=266d88cd6b3d9866fe1b58dc13be7a80, spanId=cbe4da89f6f31d22 [io.qu.op.de.in.RestClientReadTimeoutOpenTelemetryTest$SlowResource] (executor-thread-2) Span before sleep: {spanId=cbe4da89f6f31d22, traceId=266d88cd6b3d9866fe1b58dc13be7a80, sampled=true, parentId=075fa99728edae59}

11:44:24 DEBUG traceId=, spanId= [io.qu.op.ru.tr.in.ve.HttpInstrumenterVertxTracer] (vert.x-eventloop-thread-0) http failure: io.vertx.core.http.HttpClosedException: Connection was closed
11:44:24 DEBUG traceId=, spanId= [io.qu.op.ru.QuarkusContextStorage] (vert.x-eventloop-thread-0) Closing Otel context: {spanId=cbe4da89f6f31d22, traceId=266d88cd6b3d9866fe1b58dc13be7a80, sampled=true, parentId=075fa99728edae59}
11:44:24 DEBUG traceId=, spanId= [io.qu.op.ru.OpenTelemetryUtil] (vert.x-eventloop-thread-0) Removing from MDC the span id: cbe4da89f6f31d22, with otel data in vertx context: {spanId=cbe4da89f6f31d22, traceId=266d88cd6b3d9866fe1b58dc13be7a80, sampled=true, parentId=075fa99728edae59}

11:44:24 DEBUG traceId=, spanId= [io.qu.op.ru.tr.in.ve.HttpInstrumenterVertxTracer] (vert.x-eventloop-thread-1) http failure: null
11:44:24 DEBUG traceId=, spanId= [io.qu.op.ru.QuarkusContextStorage] (vert.x-eventloop-thread-1) Closing Otel context: {spanId=c65be0192d246d92, traceId=266d88cd6b3d9866fe1b58dc13be7a80, sampled=true}
11:44:24 DEBUG traceId=, spanId= [io.qu.op.ru.OpenTelemetryUtil] (vert.x-eventloop-thread-1) Removing from MDC the span id: c65be0192d246d92, with otel data in vertx context: {spanId=c65be0192d246d92, traceId=266d88cd6b3d9866fe1b58dc13be7a80, sampled=true}

11:44:26 INFO  traceId=, spanId= [io.qu.op.de.in.RestClientReadTimeoutOpenTelemetryTest$SlowResource] (executor-thread-2) Span after sleep: {}

11:44:26 DEBUG traceId=, spanId= [io.qu.op.ru.tr.in.ve.HttpInstrumenterVertxTracer] (vert.x-eventloop-thread-0) http failure: null
11:44:26 DEBUG traceId=, spanId= [io.qu.op.ru.QuarkusContextStorage] (vert.x-eventloop-thread-0) Closing Otel context: {spanId=cbe4da89f6f31d22, traceId=266d88cd6b3d9866fe1b58dc13be7a80, sampled=true, parentId=075fa99728edae59}
11:44:26 DEBUG traceId=, spanId= [io.qu.op.ru.OpenTelemetryUtil] (vert.x-eventloop-thread-0) Removing from MDC the span id: null, with otel data in vertx context: {} 
```

**Comment by brunobat** [comment]
Updated the PR and added more helpful logging

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/instrumentation/vertx/OpenTelemetryVertxTracer.java [hunk 2]
```diff
@@ -97,6 +98,7 @@ static class SpanOperation {
         private final MultiMap headers;
         private final io.opentelemetry.context.Context spanContext;
         private final Scope scope;
+        private final AtomicBoolean spanEnded = new AtomicBoolean();
```
Comment (geoand) [inline extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/instrumentation/vertx/OpenTelemetryVertxTracer.java]: This could be replaced with an `AtomicIntegerFieldUpdater` and a `volatile int` field to avoid having the extra allocation

Comment (brunobat) [reply extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/instrumentation/vertx/OpenTelemetryVertxTracer.java]: To tell you the truth, I had this with a volatile and I changed it to an AtomicBoolean because the compateAndSet. using if and then set can be open to race conditions.
About `AtomicIntegerFieldUpdater`, doesn't it use reflection?

Comment (geoand) [reply extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/instrumentation/vertx/OpenTelemetryVertxTracer.java]: > doesn't it use reflection?

It uses `Unsafe`. 

> because the compateAndSet

Right, `AtomicIntegerFieldUpdater` allows you to continue to use it

Comment (brunobat) [reply extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/instrumentation/vertx/OpenTelemetryVertxTracer.java]: Got it. Should be better now.

**Review by geoand — APPROVED** [review]
Thanks!

**Comment by brunobat** [comment]
Added a fix for the transient test failure

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/instrumentation/vertx/InstrumenterVertxTracer.java (hunk 1 above)
Comment (brunobat) [reply extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/instrumentation/vertx/InstrumenterVertxTracer.java]: @gsmet, let's give it a try?

**Comment by brunobat** [comment]
@gsmet, we've been asked to please backport this to the 3.33 LTS
