### PR TITLE
Register ConfigSources directly with the builder

### LINKED ISSUE #5492: RestEasy ServletConfigSourceImpl is broken
**Describe the bug**
`org.jboss.resteasy.microprofile.config.ServletConfigSourceImpl` is essentially nonfunctional in a native image.  In addition it is context-sensitive which can lead to unexpected behaviors (specifically that two reads of the same key from the same configuration object will yield the same value).

For now I've blacklisted this implementation from being registered to the native image, but it really needs to be revamped or removed.

If we want to support context-sensitive configuration then we need to add that support to Quarkus in such a way that each context gets its own `Config` instance.

### LINKED ISSUE #18375: Custom config source is not working in Quarkus 2.0.0
## Describe the bug
Custom config source is loaded but afterward,

 the exception is thrown:
 java.util.NoSuchElementException: SRCFG00014: The config property some.key is required but it could not be found in any config source. 

### Expected behavior
Config values must be loaded and used

### Actual behavior
Config values are loaded but not used, NoSuchElementException is thrown

## To Reproduce

[rest-json-quickstart.tar.gz](https://github.com/quarkusio/quarkus/files/6758120/rest-json-quickstart.tar.gz)
Custom config source selects application-*.properties file based on CONFIG_TYPE env variable:

1. unset CONFIG_TYPE && mvn clean package
2. export CONFIG_TYPE=b && mvn quarkus:dev
3. see log

### PR DESCRIPTION
**Pull request by radcortez**
The idea here is to register sources directly with the `SmallRyeConfigBuilder` instead of relying on the `ServiceLoader`. One of the main motivations is to better control what we add to `Config`, avoid adding problematic sources and avoid discovery at runtime.

One other issue is related with https://github.com/quarkusio/quarkus/issues/5492. Even with the guard added by https://github.com/quarkusio/quarkus/blob/a9d9a69c59791ac74e77cbcc39f5769723c40a93/core/deployment/src/main/java/io/quarkus/deployment/steps/ConfigBuildSteps.java#L96-L98 
Graal is still able to reach the source entries but fails because they are not registered for reflection. Check https://github.com/smallrye/smallrye-config/issues/580 and https://groups.google.com/g/quarkus-dev/c/yP7QsNRgYxY

The PR adds a check if servlet APIs and implementations are available to either include the RESTEasy config sources or rewrite them to not use their servlet-based implementation. Ideally, the RESTEasy config sources should be fixed.

It also adds the `@StaticInitSafe` annotation to mark sources that can be safely added and started during static init.

- Fixes https://github.com/quarkusio/quarkus/issues/18375
- Fixes https://github.com/quarkusio/quarkus/issues/5492
- Related https://github.com/quarkusio/quarkus/issues/18237

### CODE REVIEW

**Comment by gsmet** [comment]
@radcortez I rebased the PR but the failure in `io.quarkus.it.main.JaxRSITCase.testGzipConfig` looks a bit suspicious given it could be config-related.

**Comment by radcortez** [comment]
Sure, let me check.

**Comment by geoand** [comment]
Interesting!

I'll take a look on Monday

**Comment by radcortez** [comment]
Thanks! This also includes the work we talked about with the safe static init sources.

File: core/runtime/src/main/java/io/quarkus/runtime/configuration/StaticInitSafe.java [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+
+import static java.lang.annotation.ElementType.TYPE;
+import static java.lang.annotation.RetentionPolicy.RUNTIME;
+
+import java.lang.annotation.Documented;
+import java.lang.annotation.Retention;
+import java.lang.annotation.Target;
+
+/**
+ * Used to mark a ConfigSource, ConfigSourceProvider or ConfigSourceFactory as safe to be initialized during STATIC
```
Comment (geoand) [inline core/runtime/src/main/java/io/quarkus/runtime/configuration/StaticInitSafe.java:11]: I think we need to explain what static-init is here, as I am sure a lot of users won't know it. Also having a small example in the javadoc would be extremely useful I think

File: core/deployment/src/main/java/io/quarkus/deployment/builditem/StaticInitConfigSourceProviderBuildItem.java [hunk 2]
```diff
@@ -2,10 +2,13 @@
 
 import io.quarkus.builder.item.MultiBuildItem;
 
-public final class AdditionalStaticInitConfigSourceProviderBuildItem extends MultiBuildItem {
+/**
+ * Provides a way to register a ConfigSourceProvider in STATIC INIT.
+ */
+public final class StaticInitConfigSourceProviderBuildItem extends MultiBuildItem {
```
Comment (geoand) [inline core/deployment/src/main/java/io/quarkus/deployment/builditem/StaticInitConfigSourceProviderBuildItem.java:8]: Do we know if this class is being used by anybody but us? If so, we can't just rename it, we'll need a new build item and deprecate the old one

File: core/deployment/src/main/java/io/quarkus/deployment/configuration/RunTimeConfigurationGenerator.java [hunk 3]
```diff
@@ -406,11 +406,22 @@ public static void generate(
             // build time defaults
             clinit.writeArrayValue(array, 1, buildTimeRunTimeDefaultValuesConfigSource);
             clinit.invokeVirtualMethod(SRCB_WITH_SOURCES, buildTimeBuilder, array);
-            // add static init sources
-            for (String providerClass : additionalStaticInitConfigSourceProviders) {
-                ResultHandle providerInstance = clinit.newInstance(MethodDescriptor.ofConstructor(providerClass));
-                clinit.invokeStaticMethod(CU_ADD_SOURCE_PROVIDER, buildTimeBuilder, providerInstance);
+            // add safe static sources
```
Comment (geoand) [inline core/deployment/src/main/java/io/quarkus/deployment/configuration/RunTimeConfigurationGenerator.java:409]: If an reading line `400` correctly, it seems like we are still doing discovery. Did I get that wrong?

File: docs/src/main/asciidoc/writing-extensions.adoc [hunk 4]
```diff
@@ -71,7 +71,7 @@ But many properties like enable caching or setting the JDBC driver can safely re
 
 ==== Static Init Config
 
-If the extension provides additional Config Sources and if these are required during Static Init, these must be registered with `AdditionalStaticInitConfigSourceProviderBuildItem`. Configuration in Static Init does not scan for additional sources to avoid double initialization at application startup time.
```
Comment (geoand) [inline docs/src/main/asciidoc/writing-extensions.adoc:74]: See my comment about the renaming the build item

**Review by geoand — COMMENTED** [review]
Great work!

I added a few comments

File: core/deployment/src/main/java/io/quarkus/deployment/builditem/StaticInitConfigSourceProviderBuildItem.java (hunk 2 above)
Comment (radcortez) [reply core/deployment/src/main/java/io/quarkus/deployment/builditem/StaticInitConfigSourceProviderBuildItem.java:8]: I don't believe so, but we can do it to be on the safe side.

File: core/runtime/src/main/java/io/quarkus/runtime/configuration/StaticInitSafe.java (hunk 1 above)
Comment (radcortez) [reply core/runtime/src/main/java/io/quarkus/runtime/configuration/StaticInitSafe.java:11]: Sure, I'll clarify.

File: core/deployment/src/main/java/io/quarkus/deployment/builditem/StaticInitConfigSourceProviderBuildItem.java (hunk 2 above)
Comment (geoand) [reply core/deployment/src/main/java/io/quarkus/deployment/builditem/StaticInitConfigSourceProviderBuildItem.java:8]: Yeah, let's be safe on this one as it has the potential to be pretty catastrophic for say Camel :)

File: core/deployment/src/main/java/io/quarkus/deployment/configuration/RunTimeConfigurationGenerator.java (hunk 3 above)
Comment (radcortez) [reply core/deployment/src/main/java/io/quarkus/deployment/configuration/RunTimeConfigurationGenerator.java:409]: The method signature have a boolean value to turn the discovery true / false. This call is set to false:

I want to refactor that code one of these days. It is super confusing to deal with the flags and read them on the generator code. I think it would be better if we have a separate method for each `Config` initialization phase so you can see exactly what is going on and if needed change it safely without fear of affecting any of the other modes.

Comment (geoand) [reply core/deployment/src/main/java/io/quarkus/deployment/configuration/RunTimeConfigurationGenerator.java:409]: Gotcha, thanks!

**Review by geoand — APPROVED** [review]
Awesome, thanks!
