### PR TITLE
Fix dev mode launch on Windows, replace jline with Aesh in the quarkus-maven-plugin

### LINKED ISSUE #19673: Regression: Quarkus 2.2.0 breaks Dev Mode on Windows
### Describe the bug

When trying to start a Quarkus 2.2.0 application in dev-mode (using `mvn quarkus:dev`) I get the following error printed to the console and the application fails to start:
```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:2.2.0.Final:dev (default-cli) on project gluon-smoketest-runner: Execution default-cli of goal io.quarkus:quarkus-maven-plugin:2.2.0.Final:dev failed: A required class was missing while executing io.quarkus:quarkus-maven-plugin:2.2.0.Final:dev: org/fusesource/jansi/internal/Kernel32
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>io.quarkus:quarkus-maven-plugin:2.2.0.Final
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/C:/Users/knutw/.m2/repository/io/quarkus/quarkus-maven-plugin/2.2.0.Final/quarkus-maven-plugin-2.2.0.Final.jar
[ERROR] urls[1] = file:/C:/Users/knutw/.m2/repository/io/quarkus/quarkus-bootstrap-core/2.2.0.Final/quarkus-bootstrap-core-2.2.0.Final.jar
[ERROR] urls[2] = file:/C:/Users/knutw/.m2/repository/io/quarkus/quarkus-bootstrap-app-model/2.2.0.Final/quarkus-bootstrap-app-model-2.2.0.Final.jar
[ERROR] urls[3] = file:/C:/Users/knutw/.m2/repository/org/jboss/logging/jboss-logging/3.4.2.Final/jboss-logging-3.4.2.Final.jar
[ERROR] urls[4] = file:/C:/Users/knutw/.m2/repository/org/jboss/logging/commons-logging-jboss-logging/1.0.0.Final/commons-logging-jboss-logging-1.0.0.Final.jar
[ERROR] urls[5] = file:/C:/Users/knutw/.m2/repository/io/quarkus/quarkus-bootstrap-maven-resolver/2.2.0.Final/quarkus-bootstrap-maven-resolver-2.2.0.Final.jar
[ERROR] urls[6] = file:/C:/Users/knutw/.m2/repository/org/jboss/logmanager/jboss-logmanager-embedded/1.0.9/jboss-logmanager-embedded-1.0.9.jar
[ERROR] urls[7] = file:/C:/Users/knutw/.m2/repository/org/apache/maven/maven-embedder/3.8.1/maven-embedder-3.8.1.jar
[ERROR] urls[8] = file:/C:/Users/knutw/.m2/repository/commons-cli/commons-cli/1.4/commons-cli-1.4.jar
[ERROR] urls[9] = file:/C:/Users/knutw/.m2/repository/org/apache/maven/resolver/maven-resolver-connector-basic/1.6.2/maven-resolver-connector-basic-1.6.2.jar
[ERROR] urls[10] = file:/C:/Users/knutw/.m2/repository/org/apache/maven/resolver/maven-resolver-transport-wagon/1.6.2/maven-resolver-transport-wagon-1.6.2.jar
[ERROR] urls[11] = file:/C:/Users/knutw/.m2/repository/org/apache/maven/wagon/wagon-http/3.4.3/wagon-http-3.4.3.jar
[ERROR] urls[12] = file:/C:/Users/knutw/.m2/repository/org/apache/maven/wagon/wagon-http-shared/3.4.3/wagon-http-shared-3.4.3.jar
[ERROR] urls[13] = file:/C:/Users/knutw/.m2/repository/org/jsoup/jsoup/1.12.1/jsoup-1.12.1.jar
[ERROR] urls[14] = file:/C:/Users/knutw/.m2/repository/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
[ERROR] urls[15] = file:/C:/Users/knutw/.m2/repository/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
[ERROR] urls[16] = file:/C:/Users/knutw/.m2/repository/org/apache/httpcomponents/httpcore/4.4.14/httpcore-4.4.14.jar
[ERROR] urls[17] = file:/C:/Users/knutw/.m2/repository/org/apache/maven/wagon/wagon-file/3.4.3/wagon-file-3.4.3.jar
[ERROR] urls[18] = file:/C:/Users/knutw/.m2/repository/io/quarkus/quarkus-bootstrap-gradle-resolver/2.2.0.Final/quarkus-bootstrap-gradle-resolver-2.2.0.Final.jar
[ERROR] urls[19] = file:/C:/Users/knutw/.m2/repository/io/smallrye/common/smallrye-common-io/1.6.0/smallrye-common-io-1.6.0.jar
[ERROR] urls[20] = file:/C:/Users/knutw/.m2/repository/io/quarkus/quarkus-core-deployment/2.2.0.Final/quarkus-core-deployment-2.2.0.Final.jar
[ERROR] urls[21] = file:/C:/Users/knutw/.m2/repository/org/aesh/readline/2.1/readline-2.1.jar
[ERROR] urls[22] = file:/C:/Users/knutw/.m2/repository/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
[ERROR] urls[23] = file:/C:/Users/knutw/.m2/repository/org/wildfly/common/wildfly-common/1.5.4.Final-format-001/wildfly-common-1.5.4.Final-format-001.jar
[ERROR] urls[24] = file:/C:/Users/knutw/.m2/repository/io/quarkus/gizmo/gizmo/1.0.9.Final/gizmo-1.0.9.Final.jar
[ERROR] urls[25] = file:/C:/Users/knutw/.m2/repository/org/ow2/asm/asm-util/9.1/asm-util-9.1.jar
[ERROR] urls[26] = file:/C:/Users/knutw/.m2/repository/org/ow2/asm/asm-tree/9.1/asm-tree-9.1.jar
[ERROR] urls[27] = file:/C:/Users/knutw/.m2/repository/org/ow2/asm/asm-analysis/9.1/asm-analysis-9.1.jar
[ERROR] urls[28] = file:/C:/Users/knutw/.m2/repository/org/jboss/jandex/2.3.1.Final/jandex-2.3.1.Final.jar
[ERROR] urls[29] = file:/C:/Users/knutw/.m2/repository/org/ow2/asm/asm/9.1/asm-9.1.jar
[ERROR] urls[30] = file:/C:/Users/knutw/.m2/repository/io/quarkus/quarkus-development-mode-spi/2.2.0.Final/quarkus-development-mode-spi-2.2.0.Final.jar
[ERROR] urls[31] = file:/C:/Users/knutw/.m2/repository/io/quarkus/quarkus-class-change-agent/2.2.0.Final/quarkus-class-change-agent-2.2.0.Final.jar
[ERROR] urls[32] = file:/C:/Users/knutw/.m2/repository/io/quarkus/quarkus-devtools-utilities/2.2.0.Final/quarkus-devtools-utilities-2.2.0.Final.jar
[ERROR] urls[33] = file:/C:/Users/knutw/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.4/org.eclipse.sisu.inject-0.3.4.jar
[ERROR] urls[34] = file:/C:/Users/knutw/.m2/repository/io/quarkus/quarkus-core/2.2.0.Final/quarkus-core-2.2.0.Final.jar
[ERROR] urls[35] = file:/C:/Users/knutw/.m2/repository/jakarta/annotation/jakarta.annotation-api/1.3.5/jakarta.annotation-api-1.3.5.jar
[ERROR] urls[36] = file:/C:/Users/knutw/.m2/repository/io/smallrye/config/smallrye-config/2.4.4/smallrye-config-2.4.4.jar
[ERROR] urls[37] = file:/C:/Users/knutw/.m2/repository/io/smallrye/config/smallrye-config-core/2.4.4/smallrye-config-core-2.4.4.jar
[ERROR] urls[38] = file:/C:/Users/knutw/.m2/repository/org/eclipse/microprofile/config/microprofile-config-api/2.0/microprofile-config-api-2.0.jar
[ERROR] urls[39] = file:/C:/Users/knutw/.m2/repository/io/smallrye/common/smallrye-common-annotation/1.6.0/smallrye-common-annotation-1.6.0.jar
[ERROR] urls[40] = file:/C:/Users/knutw/.m2/repository/io/smallrye/common/smallrye-common-expression/1.6.0/smallrye-common-expression-1.6.0.jar
[ERROR] urls[41] = file:/C:/Users/knutw/.m2/repository/io/smallrye/common/smallrye-common-function/1.6.0/smallrye-common-function-1.6.0.jar
[ERROR] urls[42] = file:/C:/Users/knutw/.m2/repository/io/smallrye/common/smallrye-common-constraint/1.6.0/smallrye-common-constraint-1.6.0.jar
[ERROR] urls[43] = file:/C:/Users/knutw/.m2/repository/io/smallrye/common/smallrye-common-classloader/1.6.0/smallrye-common-classloader-1.6.0.jar
[ERROR] urls[44] = file:/C:/Users/knutw/.m2/repository/io/smallrye/config/smallrye-config-common/2.4.4/smallrye-config-common-2.4.4.jar
[ERROR] urls[45] = file:/C:/Users/knutw/.m2/repository/org/jboss/logging/jboss-logging-annotations/2.2.1.Final/jboss-logging-annotations-2.2.1.Final.jar
[ERROR] urls[46] = file:/C:/Users/knutw/.m2/repository/org/jboss/threads/jboss-threads/3.4.2.Final/jboss-threads-3.4.2.Final.jar
[ERROR] urls[47] = file:/C:/Users/knutw/.m2/repository/io/quarkus/quarkus-bootstrap-runner/2.2.0.Final/quarkus-bootstrap-runner-2.2.0.Final.jar
[ERROR] urls[48] = file:/C:/Users/knutw/.m2/repository/io/quarkus/quarkus-builder/2.2.0.Final/quarkus-builder-2.2.0.Final.jar
[ERROR] urls[49] = file:/C:/Users/knutw/.m2/repository/org/graalvm/sdk/graal-sdk/21.2.0/graal-sdk-21.2.0.jar
[ERROR] urls[50] = file:/C:/Users/knutw/.m2/repository/org/junit/platform/junit-platform-launcher/1.7.2/junit-platform-launcher-1.7.2.jar
[ERROR] urls[51] = file:/C:/Users/knutw/.m2/repository/org/apiguardian/apiguardian-api/1.1.0/apiguardian-api-1.1.0.jar
[ERROR] urls[52] = file:/C:/Users/knutw/.m2/repository/org/junit/platform/junit-platform-engine/1.7.2/junit-platform-engine-1.7.2.jar
[ERROR] urls[53] = file:/C:/Users/knutw/.m2/repository/org/opentest4j/opentest4j/1.2.0/opentest4j-1.2.0.jar
[ERROR] urls[54] = file:/C:/Users/knutw/.m2/repository/org/junit/platform/junit-platform-commons/1.7.2/junit-platform-commons-1.7.2.jar
[ERROR] urls[55] = file:/C:/Users/knutw/.m2/repository/org/junit/jupiter/junit-jupiter/5.7.2/junit-jupiter-5.7.2.jar
[ERROR] urls[56] = file:/C:/Users/knutw/.m2/repository/org/junit/jupiter/junit-jupiter-api/5.7.2/junit-jupiter-api-5.7.2.jar
[ERROR] urls[57] = file:/C:/Users/knutw/.m2/repository/org/junit/jupiter/junit-jupiter-params/5.7.2/junit-jupiter-params-5.7.2.jar
[ERROR] urls[58] = file:/C:/Users/knutw/.m2/repository/org/junit/jupiter/junit-jupiter-engine/5.7.2/junit-jupiter-engine-5.7.2.jar
[ERROR] urls[59] = file:/C:/Users/knutw/.m2/repository/io/quarkus/quarkus-project-core-extension-codestarts/2.2.0.Final/quarkus-project-core-extension-codestarts-2.2.0.Final.jar
[ERROR] urls[60] = file:/C:/Users/knutw/.m2/repository/io/quarkus/quarkus-devtools-common/2.2.0.Final/quarkus-devtools-common-2.2.0.Final.jar
[ERROR] urls[61] = file:/C:/Users/knutw/.m2/repository/io/quarkus/quarkus-devtools-registry-client/2.2.0.Final/quarkus-devtools-registry-client-2.2.0.Final.jar
[ERROR] urls[62] = file:/C:/Users/knutw/.m2/repository/io/quarkus/quarkus-devtools-artifact-api/2.2.0.Final/quarkus-devtools-artifact-api-2.2.0.Final.jar
[ERROR] urls[63] = file:/C:/Users/knutw/.m2/repository/io/quarkus/quarkus-devtools-message-writer/2.2.0.Final/quarkus-devtools-message-writer-2.2.0.Final.jar
[ERROR] urls[64] = file:/C:/Users/knutw/.m2/repository/io/smallrye/common/smallrye-common-os/1.6.0/smallrye-common-os-1.6.0.jar
[ERROR] urls[65] = file:/C:/Users/knutw/.m2/repository/io/quarkus/quarkus-devtools-base-codestarts/2.2.0.Final/quarkus-devtools-base-codestarts-2.2.0.Final.jar
[ERROR] urls[66] = file:/C:/Users/knutw/.m2/repository/io/quarkus/quarkus-devtools-codestarts/2.2.0.Final/quarkus-devtools-codestarts-2.2.0.Final.jar
[ERROR] urls[67] = file:/C:/Users/knutw/.m2/repository/io/quarkus/qute/qute-core/2.2.0.Final/qute-core-2.2.0.Final.jar
[ERROR] urls[68] = file:/C:/Users/knutw/.m2/repository/io/smallrye/reactive/mutiny/1.0.0/mutiny-1.0.0.jar
[ERROR] urls[69] = file:/C:/Users/knutw/.m2/repository/org/reactivestreams/reactive-streams/1.0.3/reactive-streams-1.0.3.jar
[ERROR] urls[70] = file:/C:/Users/knutw/.m2/repository/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
[ERROR] urls[71] = file:/C:/Users/knutw/.m2/repository/org/jline/jline/3.20.0/jline-3.20.0.jar
[ERROR] urls[72] = file:/C:/Users/knutw/.m2/repository/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
[ERROR] urls[73] = file:/C:/Users/knutw/.m2/repository/io/fabric8/maven-model-helper/18/maven-model-helper-18.jar
[ERROR] urls[74] = file:/C:/Users/knutw/.m2/repository/org/jdom/jdom/1.1.3/jdom-1.1.3.jar
[ERROR] urls[75] = file:/C:/Users/knutw/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/2.12.4/jackson-dataformat-yaml-2.12.4.jar
[ERROR] urls[76] = file:/C:/Users/knutw/.m2/repository/org/yaml/snakeyaml/1.29/snakeyaml-1.29.jar
[ERROR] urls[77] = file:/C:/Users/knutw/.m2/repository/org/codehaus/plexus/plexus-utils/3.2.1/plexus-utils-3.2.1.jar
[ERROR] urls[78] = file:/C:/Users/knutw/.m2/repository/jakarta/inject/jakarta.inject-api/1.0/jakarta.inject-api-1.0.jar
[ERROR] urls[79] = file:/C:/Users/knutw/.m2/repository/jakarta/enterprise/jakarta.enterprise.cdi-api/2.0.2/jakarta.enterprise.cdi-api-2.0.2.jar
[ERROR] urls[80] = file:/C:/Users/knutw/.m2/repository/jakarta/el/jakarta.el-api/3.0.3/jakarta.el-api-3.0.3.jar
[ERROR] urls[81] = file:/C:/Users/knutw/.m2/repository/jakarta/interceptor/jakarta.interceptor-api/1.2.5/jakarta.interceptor-api-1.2.5.jar
[ERROR] urls[82] = file:/C:/Users/knutw/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.25/plexus-interpolation-1.25.jar
[ERROR] urls[83] = file:/C:/Users/knutw/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.4/plexus-sec-dispatcher-1.4.jar
[ERROR] urls[84] = file:/C:/Users/knutw/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
[ERROR] urls[85] = file:/C:/Users/knutw/.m2/repository/org/apache/maven/maven-builder-support/3.8.1/maven-builder-support-3.8.1.jar
[ERROR] urls[86] = file:/C:/Users/knutw/.m2/repository/org/apache/maven/resolver/maven-resolver-util/1.6.2/maven-resolver-util-1.6.2.jar
[ERROR] urls[87] = file:/C:/Users/knutw/.m2/repository/org/apache/maven/shared/maven-shared-utils/3.3.3/maven-shared-utils-3.3.3.jar
[ERROR] urls[88] = file:/C:/Users/knutw/.m2/repository/com/google/inject/guice/4.2.1/guice-4.2.1-no_aop.jar
[ERROR] urls[89] = file:/C:/Users/knutw/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar
[ERROR] urls[90] = file:/C:/Users/knutw/.m2/repository/com/google/guava/guava/30.1.1-jre/guava-30.1.1-jre.jar
[ERROR] urls[91] = file:/C:/Users/knutw/.m2/repository/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
[ERROR] urls[92] = file:/C:/Users/knutw/.m2/repository/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar
[ERROR] urls[93] = file:/C:/Users/knutw/.m2/repository/com/google/errorprone/error_prone_annotations/2.2.0/error_prone_annotations-2.2.0.jar
[ERROR] urls[94] = file:/C:/Users/knutw/.m2/repository/com/google/j2objc/j2objc-annotations/1.3/j2objc-annotations-1.3.jar
[ERROR] urls[95] = file:/C:/Users/knutw/.m2/repository/org/codehaus/plexus/plexus-component-annotations/2.1.0/plexus-component-annotations-2.1.0.jar
[ERROR] urls[96] = file:/C:/Users/knutw/.m2/repository/org/apache/maven/shared/maven-artifact-transfer/0.10.0/maven-artifact-transfer-0.10.0.jar
[ERROR] urls[97] = file:/C:/Users/knutw/.m2/repository/org/apache/maven/shared/maven-common-artifact-filters/3.0.1/maven-common-artifact-filters-3.0.1.jar
[ERROR] urls[98] = file:/C:/Users/knutw/.m2/repository/org/sonatype/sisu/sisu-inject-bean/1.4.2/sisu-inject-bean-1.4.2.jar
[ERROR] urls[99] = file:/C:/Users/knutw/.m2/repository/org/sonatype/sisu/sisu-guice/2.1.7/sisu-guice-2.1.7-noaop.jar
[ERROR] urls[100] = file:/C:/Users/knutw/.m2/repository/org/freemarker/freemarker/2.3.31/freemarker-2.3.31.jar
[ERROR] urls[101] = file:/C:/Users/knutw/.m2/repository/org/glassfish/jakarta.json/1.1.6/jakarta.json-1.1.6.jar
[ERROR] urls[102] = file:/C:/Users/knutw/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.12.4/jackson-databind-2.12.4.jar
[ERROR] urls[103] = file:/C:/Users/knutw/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.12.4/jackson-annotations-2.12.4.jar
[ERROR] urls[104] = file:/C:/Users/knutw/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.12.4/jackson-core-2.12.4.jar
[ERROR] urls[105] = file:/C:/Users/knutw/.m2/repository/org/twdata/maven/mojo-executor/2.3.1/mojo-executor-2.3.1.jar
[ERROR] urls[106] = file:/C:/Users/knutw/.m2/repository/org/jboss/slf4j/slf4j-jboss-logmanager/1.1.0.Final/slf4j-jboss-logmanager-1.1.0.Final.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR]
[ERROR] -----------------------------------------------------
[ERROR] : org.fusesource.jansi.internal.Kernel32
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException
```
With Quarkus 2.1.3 the same application works without issues.

### Expected behavior

Dev Mode should also work on Windows.

### Actual behavior

See description.

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

MSYS_NT-10.0-22000 WIN10-KNUT 3.1.7-340.x86_64 2020-10-23 13:08 UTC x86_64 Msys

### Output of `java -version`

openjdk version "11.0.9" 2020-10-20 LTS OpenJDK Runtime Environment Zulu11.43+22-SA (build 11.0.9+11-LTS) OpenJDK 64-Bit Server VM Zulu11.43+22-SA (build 11.0.9+11-LTS, mixed mode)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.2.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.2 (ea98e05a04480131370aa0c110b8c54cf726c06f)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by aloubyansky**
Fixes #19673

* replaced jline with Aesh in the `quarkus-maven-plugin` (Aesh is already present on the classpath as the `quarkus-core-deployment` dependency)
* moved the Prompter class back to the quarkus-maven-plugin (otherwise we'll need extra dependencies in devtools-common for no reason)
* shaded jansi into the `quarkus-maven-plugin` (to fix classloading on Windows)
* Made the `Prompter` a regular class, not a Maven `Component`

### CODE REVIEW

File: devtools/maven/src/main/java/io/quarkus/maven/components/Prompter.java [hunk 1]
```diff
@@ -1,18 +1,72 @@
...
+    public void collectInput() throws IOException {
+        if (prompts.isEmpty()) {
+            return;
+        }
+        final TerminalConnection connection = new TerminalConnection();
+        try {
+            read(connection, ReadlineBuilder.builder().enableHistory(false).build(), prompts.iterator());
+            connection.openBlocking();
+        } finally {
+            connection.close();
```
Comment (aloubyansky) [inline devtools/maven/src/main/java/io/quarkus/maven/components/Prompter.java:56]: @stuartwdouglas quick question. I've switched the Maven plugin's prompter from jline to Aesh (since it's already on the classpath anyway). I was wondering whether i should restore the terminal's state like you do in the DevMojo (https://github.com/quarkusio/quarkus/blob/main/devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java#L445) or is it ok to simply close the connection. I am not doing anything fancy here, simply collecting the input. Thanks!

Comment (stuartwdouglas) [reply devtools/maven/src/main/java/io/quarkus/maven/components/Prompter.java:56]: Then you should be ok. I put the terminal in raw mode so if the process crashes I need to restore it to the original state.

**Review by gastaldi — APPROVED** [review]
LGTM

**Comment by gastaldi** [comment]
Funny, I thought Aesh was permanently removed from Quarkus, looks like I was wrong 😛

File: devtools/maven/pom.xml [hunk 2]
```diff
@@ -191,6 +191,34 @@
...
+                <executions>
+                    <execution>
+                        <phase>package</phase>
+                        <goals>
+                            <goal>shade</goal>
+                        </goals>
+                        <configuration>
+                            <artifactSet>
+                                <includes>
+                                    <include>org.fusesource.jansi:jansi</include>
```
Comment (gastaldi) [inline devtools/maven/pom.xml:207]: Will this work with Maven 3.8.2?

Comment (aloubyansky) [reply devtools/maven/pom.xml:207]: @knutwannheden just confirmed to me it works for both 3.8.1 and 3.8.2.
This change actually reduces the number of Jansi versions on the classpath by removing JLine which shades a Jansi version. With change we shade the Jansi version which is already on the classpath. Why exactly we have to do this to make it work is mystery to me though.
