### PR TITLE
Make access logging work in native mode

### LINKED ISSUE #9047: Logging access log with native dont work.
**Describe the bug**
We can activate access log by setting property quarkus.http.access-log.enabled to true
When access-log is enabled. it work fine with jvm, but failed in native 

**Expected behavior (jvm output)**
```
2020-05-04 14:19:57,434 INFO  [io.quarkus] (Quarkus Main Thread) code-with-quarkus 1.0.0-SNAPSHOT (powered by Quarkus 1.4.1.Final) started in 1.361s. Listening on: http://0.0.0.0:8080
2020-05-04 14:19:57,436 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2020-05-04 14:19:57,436 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, kotlin, resteasy, resteasy-jackson, smallrye-health, smallrye-metrics, smallrye-openapi, swagger-ui]
2020-05-04 14:20:09,791 INFO  [io.qua.htt.access-log] (vert.x-worker-thread-1) 127.0.0.1 - - [04/May/2020:14:20:09 +0200] "GET /health HTTP_1_1" 200 46
```

**Actual behavior (native output)**
```
2020-05-04 14:26:26,236 ERROR [io.qua.ver.htt.run.att.ExchangeAttributeParser] (main) Unknown token %h
2020-05-04 14:26:26,236 ERROR [io.qua.ver.htt.run.att.ExchangeAttributeParser] (main) Unknown token %l
2020-05-04 14:26:26,236 ERROR [io.qua.ver.htt.run.att.ExchangeAttributeParser] (main) Unknown token %u
2020-05-04 14:26:26,236 ERROR [io.qua.ver.htt.run.att.ExchangeAttributeParser] (main) Unknown token %t
2020-05-04 14:26:26,236 ERROR [io.qua.ver.htt.run.att.ExchangeAttributeParser] (main) Unknown token %r
2020-05-04 14:26:26,236 ERROR [io.qua.ver.htt.run.att.ExchangeAttributeParser] (main) Unknown token %s
2020-05-04 14:26:26,236 ERROR [io.qua.ver.htt.run.att.ExchangeAttributeParser] (main) Unknown token %b
2020-05-04 14:26:26,238 INFO  [io.quarkus] (main) code-with-quarkus 1.0.0-SNAPSHOT (powered by Quarkus 1.4.1.Final) started in 0.016s. Listening on: http://0.0.0.0:8080
2020-05-04 14:26:26,238 INFO  [io.quarkus] (main) Profile prod activated. 
2020-05-04 14:26:26,238 INFO  [io.quarkus] (main) Installed features: [cdi, kotlin, resteasy, resteasy-jackson, smallrye-health, smallrye-metrics, smallrye-openapi]
2020-05-04 14:26:33,294 INFO  [io.qua.htt.access-log] (executor-thread-1) %h %l %u %t "%r" %s %b
```
**To Reproduce**
1. create a web project 
2. activate the access log : quarkus.http.access-log.enabled=true
3. compile in native : mvn package -Pnative
4. run the project: target/code-with-quarkus-1.0.0-SNAPSHOT-runner
5. call any endpoint, ex : http://127.0.0.1:8080/health
6. check the log output

**Configuration**
```properties
quarkus.http.access-log.enabled=true
```

**Example of project that failed**
[code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/4574697/code-with-quarkus.zip)

**Environment:**
 - Output of `uname -a` or `ver`:  Darwin pc-79.home 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
 - Output of `java -version`: 
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment GraalVM CE 20.0.0 (build 11.0.6+9-jvmci-20.0-b02)
OpenJDK 64-Bit Server VM GraalVM CE 20.0.0 (build 11.0.6+9-jvmci-20.0-b02, mixed mode, sharing)
 - Quarkus version or git rev: 1.4.1
 - mvn version 3.6.3

### PR DESCRIPTION
**Pull request by jaikiran**
Fixes https://github.com/quarkusio/quarkus/issues/9047

Right now, access logging isn't working in native mode as reported in the issue. This is because the `ExchangeAttributeBuilder`(s) which are responsible for handling the access log format specifier are `ServiceLoader` based interfaces and as such need to be explicitly registered in native image for them to be available.

The commit here explicitly makes them available in native mode and also includes a test to reproduce the issue and verify the fix.

### CODE REVIEW

File: core/deployment/src/main/java/io/quarkus/deployment/builditem/nativeimage/ServiceProviderBuildItem.java [hunk 1]
```diff
@@ -18,6 +27,50 @@
...
+     *        this method uses the {@link Thread#getContextClassLoader() thread context classloader}
+     * @return
+     * @throws IOException
+     */
+    public static Optional<ServiceProviderBuildItem> allProviders(final String serviceInterfaceClassName, final ClassLoader cl)
+            throws IOException {
+        if (serviceInterfaceClassName == null || serviceInterfaceClassName.trim().isEmpty()) {
+            throw new IllegalArgumentException("service interface name cannot be null or blank");
+        }
+        final ClassLoader classLoaderToUse = cl == null ? Thread.currentThread().getContextClassLoader() : cl;
```
Comment (stuartwdouglas) [inline core/deployment/src/main/java/io/quarkus/deployment/builditem/nativeimage/ServiceProviderBuildItem.java:47]: An issue with this approach is that if there are additional service implementations on the deployment class path that are not on the runtime class path this will cause failures. Not sure how likely this in practice.

File: extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/VertxHttpProcessor.java [hunk 2]
```diff
@@ -185,4 +188,25 @@ void openSocket(ApplicationStartBuildItem start,
...
         return new RuntimeInitializedClassBuildItem("io.vertx.ext.web.handler.sockjs.impl.XhrTransport");
     }
+
+    /**
+     * Register the {@link ExchangeAttributeBuilder} services for native image consumption
+     * 
+     * @param exchangeAttributeBuilderService
+     * @throws BuildException
+     */
+    @BuildStep(onlyIf = NativeBuild.class)
```
Comment (stuartwdouglas) [inline extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/VertxHttpProcessor.java:198]: This should actually happen automatically, as ServiceProviderBuildItem should only be consumed in a native build so it will only run if doing a native build.

**Review by stuartwdouglas — APPROVED** [review]
LGTM, I don't think the ClassLoader issue will actually be a problem in practice.

File: core/deployment/src/main/java/io/quarkus/deployment/builditem/nativeimage/ServiceProviderBuildItem.java (hunk 1 above)
Comment (jaikiran) [reply core/deployment/src/main/java/io/quarkus/deployment/builditem/nativeimage/ServiceProviderBuildItem.java:47]: You are right. I hadn't thought of this scenario. I think I might have a slightly different way to achieve this same functionality without having to run into the issue that you note here. I'll try it out and update the PR shortly.

File: extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/VertxHttpProcessor.java (hunk 2 above)
Comment (jaikiran) [reply extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/VertxHttpProcessor.java:198]: That makes sense. I'll take care of this while updating this PR.

Comment (jaikiran) [reply extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/VertxHttpProcessor.java]: Updated

**Comment by jaikiran** [comment]
Hello @stuartwdouglas, given that the goal of this change was to register the "core" `ExchangeAttributeBuilder`(s) which are part of `vertx-http`, I've updated this PR to very selectively find that service descriptor file and load only those providers. This should avoid the classloader problem that you rightly raised previously.

**Review by stuartwdouglas — APPROVED** [review]

**Comment by stuartwdouglas** [comment]
Thanks Jaikiran

**Comment by rousseau-christopher** [comment]
thx guys for working on this issue
