### PR TITLE
Do not turn fields into accessors in Hibernate ORM entity constructors

### LINKED ISSUE #7721: Unable to build Hibernate SessionFactory due NPE
**Describe the bug**

Failed to start Quarkus:
Unable to build Hibernate SessionFactory due NPE  for a simple entity with a set(ter) method and a declaration level initialization of the member var.

    @OneToMany(fetch = FetchType.EAGER, cascade = CascadeType.ALL, orphanRemoval = true)
    @JoinColumn(name = "customer", unique = false, nullable = true)
    public Set<Product> products = new HashSet<>();
    public void setProducts(Set<Product> references) {
        this.products.clear();
        if (references == null || references.size() == 0) {
            return;
        } else {
            for (Product reference : references) {
                reference.customer = this;
                this.products.add(reference);
            }
        }

    }

Quarkus version is 1.3.0.CR2

**To Reproduce**

Reproducer can be found here: https://github.com/suchwerk/quarkus-jpa-npe-on-entity

**Stacktrace**

Stacktrace:
```

2020-03-10 10:14:05,720 ERROR [io.qua.application] (main) Failed to start application: javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory
    at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.persistenceException(FastBootEntityManagerFactoryBuilder.java:113)
    at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:67)
    at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.createEntityManagerFactory(FastBootHibernatePersistenceProvider.java:54)
    at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
    at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
    at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:110)
    at io.quarkus.hibernate.orm.runtime.JPAConfig.startAll(JPAConfig.java:58)
    at io.quarkus.hibernate.orm.runtime.HibernateOrmRecorder.startAllPersistenceUnits(HibernateOrmRecorder.java:82)
    at io.quarkus.deployment.steps.HibernateOrmProcessor$startPersistenceUnits29.deploy_0(HibernateOrmProcessor$startPersistenceUnits29.zig:51)
    at io.quarkus.deployment.steps.HibernateOrmProcessor$startPersistenceUnits29.deploy(HibernateOrmProcessor$startPersistenceUnits29.zig:70)
    at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:159)
    at io.quarkus.runtime.Application.start(Application.java:90)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at io.quarkus.runner.bootstrap.StartupActionImpl.run(StartupActionImpl.java:96)
    at io.quarkus.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:60)
    at io.quarkus.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:236)
    at io.quarkus.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:39)
    at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:131)
    at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:84)
    at io.quarkus.dev.DevModeMain.start(DevModeMain.java:104)
    at io.quarkus.dev.DevModeMain.main(DevModeMain.java:46)
Caused by: org.hibernate.MappingException: Could not get constructor for org.hibernate.persister.entity.SingleTableEntityPersister
    at org.hibernate.persister.internal.PersisterFactoryImpl.createEntityPersister(PersisterFactoryImpl.java:123)
    at org.hibernate.persister.internal.PersisterFactoryImpl.createEntityPersister(PersisterFactoryImpl.java:77)
    at org.hibernate.metamodel.internal.MetamodelImpl.initialize(MetamodelImpl.java:181)
    at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:299)
    at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:468)
    at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:65)
    ... 22 more
Caused by: org.hibernate.InstantiationException: could not instantiate test object : de.suchwerk.Customer
    at org.hibernate.engine.internal.UnsavedValueFactory.instantiate(UnsavedValueFactory.java:43)
    at org.hibernate.engine.internal.UnsavedValueFactory.getUnsavedIdentifierValue(UnsavedValueFactory.java:68)
    at org.hibernate.tuple.PropertyFactory.buildIdentifierAttribute(PropertyFactory.java:62)
    at org.hibernate.tuple.entity.EntityMetamodel.<init>(EntityMetamodel.java:136)
    at org.hibernate.persister.entity.AbstractEntityPersister.<init>(AbstractEntityPersister.java:601)
    at org.hibernate.persister.entity.SingleTableEntityPersister.<init>(SingleTableEntityPersister.java:125)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
    at org.hibernate.persister.internal.PersisterFactoryImpl.createEntityPersister(PersisterFactoryImpl.java:96)
    ... 27 more
Caused by: java.lang.reflect.InvocationTargetException
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
    at org.hibernate.engine.internal.UnsavedValueFactory.instantiate(UnsavedValueFactory.java:40)
    ... 37 more
Caused by: java.lang.NullPointerException
    at de.suchwerk.Customer.setProducts(Customer.java:32)
    at de.suchwerk.Customer.<init>(Customer.java:27)
    ... 42 more
```

### PR DESCRIPTION
**Pull request by FroMage**

### CODE REVIEW

**Comment by gsmet** [comment]
There's probably a formatting issue given the build failed early.

`mvn process-sources`

**Comment by FroMage** [comment]
Now with 100% more correct formatting.

File: extensions/panache/panache-common/deployment/src/main/java/io/quarkus/panache/common/deployment/PanacheFieldAccessMethodVisitor.java [hunk 1]
```diff
@@ -28,6 +28,10 @@ public void visitFieldInsn(int opcode, String owner, String fieldName, String de
         // FIXME: do not substitute to accessors to this or super fields inside constructor?
```
Comment (Sanne) [inline extensions/panache/panache-common/deployment/src/main/java/io/quarkus/panache/common/deployment/PanacheFieldAccessMethodVisitor.java]: Should the FIXME be removed?

File: extensions/panache/panache-common/deployment/src/main/java/io/quarkus/panache/common/deployment/PanacheFieldAccessMethodVisitor.java [hunk 2]
```diff
@@ -28,6 +28,10 @@ public void visitFieldInsn(int opcode, String owner, String fieldName, String de
...
         if ((opcode == Opcodes.GETFIELD
                 || opcode == Opcodes.PUTFIELD)
+                // if we're in the constructor, do not replace field accesses to this type and its supertypes
+                // otherwise we risk running setters that depend on initialisation
+                && (!this.methodName.equals("<init>")
+                        || !targetIsInHierarchy(this.owner.replace('/', '.'), owner.replace('/', '.')))
```
Comment (Sanne) [inline extensions/panache/panache-common/deployment/src/main/java/io/quarkus/panache/common/deployment/PanacheFieldAccessMethodVisitor.java]: the code `owner.replace('/', '.'))` could be extracted since you need it twice?

While at it, might be useful to extract the regex into a constant? Entirely optional of course: I'm aware I'm nitpicking.

Comment (FroMage) [reply extensions/panache/panache-common/deployment/src/main/java/io/quarkus/panache/common/deployment/PanacheFieldAccessMethodVisitor.java]: It's not a regex ;) But I have moved it up.

File: extensions/panache/panache-common/deployment/src/main/java/io/quarkus/panache/common/deployment/PanacheFieldAccessMethodVisitor.java (hunk 1 above)
Comment (FroMage) [reply extensions/panache/panache-common/deployment/src/main/java/io/quarkus/panache/common/deployment/PanacheFieldAccessMethodVisitor.java]: ah yes :)

**Review by Sanne — APPROVED** [review]
Awesome, and appreciate all the extra tests!

**Comment by Sanne** [comment]
Fixes #7721
