### PR TITLE
Fix potential NPE in RESTEasy Classic build time processing

### LINKED ISSUE #17854: NullPointerException in build when denying unannotated endpoints
In a project without endpoints, a NullPointerException is thrown during build if the property `quarkus.security.jaxrs.deny-unannotated-endpoints` is set to `true`. 

Of course, without endpoints the property makes no sense, but probably no NullPointerException should be thrown either.

``` 
io.quarkus.builder.BuildException: Build failure: Build failed due to errors
  	[error]: Build step io.quarkus.resteasy.deployment.ResteasyBuiltinsProcessor#setUpDenyAllJaxRs threw an exception: java.lang.NullPointerException
  	at io.quarkus.resteasy.deployment.ResteasyBuiltinsProcessor.setUpDenyAllJaxRs(ResteasyBuiltinsProcessor.java:57)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:820)
  	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
  	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
  	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2442)
  	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1476)
  	at java.base/java.lang.Thread.run(Thread.java:829)
  	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #17854

### CODE REVIEW

File: extensions/resteasy-classic/resteasy/deployment/src/main/java/io/quarkus/resteasy/deployment/ResteasyBuiltinsProcessor.java [hunk 1]
```diff
@@ -51,7 +51,7 @@ void setUpDenyAllJaxRs(CombinedIndexBuildItem index,
             JaxRsSecurityConfig config,
             ResteasyDeploymentBuildItem resteasyDeployment,
             BuildProducer<AdditionalSecuredClassesBuildItem> additionalSecuredClasses) {
-        if (config.denyJaxRs) {
+        if ((config.denyJaxRs) && (resteasyDeployment != null)) {
```
Comment (gsmet) [inline extensions/resteasy-classic/resteasy/deployment/src/main/java/io/quarkus/resteasy/deployment/ResteasyBuiltinsProcessor.java:54]: Isn’t the build item mandatory in this case? I’m surprised you don’t have an error instead of a null value.

Comment (gsmet) [reply extensions/resteasy-classic/resteasy/deployment/src/main/java/io/quarkus/resteasy/deployment/ResteasyBuiltinsProcessor.java:54]: @stuartwdouglas is it normal that an injected build item can be null? I thought we needed to use Optional in this case to avoid dependency injection issues?

**Review by gsmet — APPROVED** [review]
Let's merge it but I'd like to understand what's going on.

File: extensions/resteasy-classic/resteasy/deployment/src/main/java/io/quarkus/resteasy/deployment/ResteasyBuiltinsProcessor.java (hunk 1 above)
Comment (geoand) [reply extensions/resteasy-classic/resteasy/deployment/src/main/java/io/quarkus/resteasy/deployment/ResteasyBuiltinsProcessor.java:54]: I don't remember what the behavior is, but I can certainly look into it if this becomes an issue
