### PR TITLE
Process OIDC code query param only if the state cookie exists

### LINKED ISSUE #22195: OIDC: do not inspect every unauthenticated request for a `code` param
### Describe the bug

ATM I have the impression that I hit the `CodeAuthenticationMechanism.authenticate` code path in every unauthenticated request, even when it wasn't called by the OIDC server as a callback.

This means that user applications are banned from ever using a `code` query param on all their unauthenticated endpoints, which is not acceptable.

This inspection of the `code` query param (or the form POST) should only ever happen when an OIDC server is calling us via a redirect, so this should be checked. Perhaps it should be a referrer check, but we can't simply look at `code` query params that are not related to OIDC, that's wrong. I even wonder if it's not a security bug TBH, because anyone can call any endpoint with `?code=something` and trigger an OIDC callback when there wasn't one.

I have a commit which fixed it trivially for my application: https://github.com/FroMage/quarkus/commit/9985e30de0a7dbe24cca15dc5b2a04f5bef45294

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sberyozkin**
Fixes #22195 (and next it will be straightforward to resolve both #22189 and #22029).

So Steph reported the issue with the custom `code` parameter triggering the code flow completion process and he was not the first one, I looked at the earlier issue but decided to avoid fixing it back then because of the ambiguity - what to do if the state cookie is missing but the `code` is not - is it a faulty redirect or just an initial custom request.

However, after seeing #22195, and then also #22189, I thought it was not cool to ask users to replace the custom `code` and also `error` query parameters. And especially after seeing #22029, where the post request parameters should not be even checked if it is not an OIDC redirect, I thought it was the right time to address the problem.

So here is what this PR does:
* Makes sure the `code` is checked only if the state cookie exists and valid, confirming it came from the OIDC provider. it really makes sense to make it conditional on the presence of this cookie before deciding to start processing this `code` (and as I said, the same would apply to the `error` and also the form_post response mode processing)
* Right now on main, if no state cookie is found but `code` is then 401 is returned to prevent the redirect loops (i.e, the user successfully logged in, redirect to Quarkus, the state cookie is lost due to the wrong configuration - cookie domain or path is not set correctly, without 401 but with a 302 challenge the user goes back to the provider which already has the user session, send the user back to Quarkus, and the loop starts). I had to introduce a simple property to retain this behavior of reporting `401` if no state cookie is available but `code` is. 
 ** Steph - I did look at your proposal of checking `Referer` which is a good idea and I started coding - but unfortunately it does not work in all the cases , it is not guaranteed to match the actual authorization provider URL with the various port, http vs https translations, I just did not feel it would be a reliable solution. I also think that controlling it with the property is more flexible as some users will want 401, some users - the redirect again (see below why)
 * So if one needs to support custom `code` (or `error`) query parameters during the initial auth request then the only thing they should do is to set `quarkus.oidc.authentication.redirect-without-state-cookie=true`. In this case, if the state cookie is absent, the usual challenge with a redirect to OIDC will occur. The important thing is, it does not compromise on anything really, the only reason `401` is returned by default when no `state cookie` is present but the `code` is is to avoid a redirect loop in case of the bad configuration. So enabling this property will only have an extra `requirement` to make sure the configuration is correct to avoid losing the state cookie - and even it is not correct - what will happen is that if the state cookie is missing then instead of 401 the browser will fail with the redirect loop - unless the loop is prevented with requiring the provider to always challenge even the already authenticated users.

IMHO this is the best compromise we can do to let users supply custom `code` and soon `error` query parameters - but also by making the code processing conditional on the availability of the state cookie is a better approach in any case

### CODE REVIEW

**Comment by sberyozkin** [comment]
@FroMage @pedroigor After a walk I decided I was may be exaggerating the problem related to what to return in case of a missing state cookie but with the `code` missing.

I think the Steph's idea of checking the referer is in fact the simplest as opposed to adding a property. If it ever happens that the referer does not match the discover authorization uri then the `worst` what will happen is that the challenge with a redirect will start again as opposed to 401, and the main point here is that this can only happen in a faulty configuration situation...

So, I'll update the PR a bit - and the important part is - the current Quarkus OIDC behavior won't change a bit but will only become better prepared for dealing with the next related issues :-). And the property option will still be open...

Note I've updated some of the existing tests for them to pass, these are the cases where the test disables the auto redirect from the quarkus challenge,  checks something and then calls Quarkus with the auto-redirect re-enabled - here the state cookie returned with the 1st call persists between these 2 calls which is causing a failure - so I just clean the cookies in between these 2 calls

**Comment by sberyozkin** [comment]
@FroMage @pedroigor 

This is now better IMHO, in fact I actually start seeing easily now what is going in `CodeAuthenticationMechanism` :-)

It is all easy to understand now
 1) if the session token is the - reauthenticate 
 2) if the state cookie is there - complete the exchange and start a new session
 3) if neither cookie is there - return a challenge
 4) in the challenge - if it is detected it is a redirect from Keycloak/etc - 401 (as per the current expectations) - else - redirect to the provider. Note I had to do this detection in the challenge method because it is there where the OIDC provider metadata are visible for us to compare it against the Referer

I've also fixed one more incorrect test which was exposed by the refactoring - the idea there was to simulate the code exchange failure by returning wrong redirect uri on the return leg - by returning different configurations - but this test was in fact failing much earlier - because by returning different tenant ids every time the state cookie could not be in fact detected, so I cleaned the corresponding setup...

So IMHO it is looking better now

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java [hunk 1]
```diff
@@ -76,21 +77,50 @@
...
-                });
+    }
 
+    private boolean isStateCookieValid(RoutingContext context, Cookie stateCookie) {
+        List<String> values = context.queryParam("state");
+        // IDP must return a 'state' query parameter and the value of the state cookie must start with this parameter's value
+        if (values.size() != 1) {
+            LOG.debug("State parameter can not be empty or multi-valued");
+            return false;
+        } else if (!stateCookie.getValue().startsWith(values.get(0))) {
```
Comment (pedroigor) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java:119]: Isn't more secure an exact match?

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java [hunk 2]
```diff
@@ -250,43 +290,31 @@ private boolean shouldAutoRedirect(TenantConfigContext configContext, RoutingCon
                 });
     }
 
-    private Uni<SecurityIdentity> performCodeFlow(IdentityProviderManager identityProviderManager,
-            RoutingContext context, TenantConfigContext configContext, String code) {
+    private boolean isRedirectFromProvider(RoutingContext context, TenantConfigContext configContext) {
```
Comment (pedroigor) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java:293]: I'm not 100% sure how reliable is this. Is it really needed?

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java (hunk 1 above)
Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java:119]: Hi @pedroigor This is not specific to this PR, I just moved some of the state check here but see on main [here](https://github.com/quarkusio/quarkus/blob/main/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java#L266), it has been like that for ever. The state cookie value has the format `state|path-to-restore-after-redirect` (the 2nd part can hold query parameters and supports the old case where the callback URI is only used different to the actual destination URI - that can probably be dropped - but it would be too sensitive right now). This is why it is `startsWith` check.
However, good you've spotted it as we should follow up with the exact match on the 1st part of the value. I'll update

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java (hunk 2 above)
Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java:293]: @pedroigor Good point, I've been contemplating above about it, it is the best effort at trying to figure out how to fail the request best if the state cookie is missing.

On the `main` it is an immediate 401. But  on the `main` it is also the problem that if the `code` is detected then it is assumed it is the redirect from KC - but with the `error` and the Apple's `form_post` response mode to be supported next it just does not work - especially with `form_post` - we can't start checking the post data without asserting the state cookie exists, so this refactoring is making these checks dependent on the availability of the state cookie.

So now, if the state cookie is missing and 1)  If no `code` is there - we fail indirectly by challenging the user with a redirect to KC - this is how it works on `main`, if `code` is there - we check `Referer` and if proved it comes from KC only then do we stop everything with 401. 

So if the `Referer` check fails then instead of 401 the user will be redirected to KC to re-authenticate. And as I said above, we can follow up with adding the property what to do if the state cookie is missing, the `code` (`error`) (query or form post) present - do 401 or redirect to KC. In fact I started with the property first but then thought it was unnecessary yet.

Does it clarify it ?

 
We have a test expecting 401 in case of a missing state cookie and this code properly gives 401 as expected.

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java [hunk 3]
```diff
@@ -76,21 +77,52 @@
                     });
         }
 
-        final String code = context.request().getParam("code");
-        if (code == null) {
-            return Uni.createFrom().optional(Optional.empty());
+        final Cookie stateCookie = context.request().getCookie(getStateCookieName(oidcTenantConfig));
```
Comment (FroMage) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java:80]: This looks fine, but my opinion is still that this should be conditional to the current request being a callback URI and not just _any_ URI. That's what I do in my branch. What's the reason you don't check that?

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java [hunk 4]
```diff
@@ -250,43 +292,31 @@ private boolean shouldAutoRedirect(TenantConfigContext configContext, RoutingCon
                 });
     }
 
-    private Uni<SecurityIdentity> performCodeFlow(IdentityProviderManager identityProviderManager,
-            RoutingContext context, TenantConfigContext configContext, String code) {
+    private boolean isRedirectFromProvider(RoutingContext context, TenantConfigContext configContext) {
+        String referer = context.request().getHeader(HttpHeaders.REFERER);
+        return referer != null && referer.startsWith(configContext.provider.getMetadata().getAuthorizationUri());
```
Comment (FroMage) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java:297]: I'll have to check IRL if the referer URIs are the same ones we go to, IIRC there often are quite a lot of redirects before we get back.

**Review by FroMage — CHANGES_REQUESTED** [review]

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java (hunk 3 above)
Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java:80]: @FroMage Let me thinks about it

Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java:80]: @FroMage Ok, I don't see it making any difference in which order to start checking it as both actions: recalculating the redirect URI and checking if the state cookie exists and valid, have to be done to complete the code exchange (the redirect uri has to be sent with the code grant alongside the code).
 
If it an initial non-authenticated request then it is no more expensive to start with checking if the state cookie with the given name exists (which means it is a redirect which must've come from the provider) than starting with recalculating the absolute redirect URI and comparing it with the current absolute one, even a bit cheaper I'd say.

I think it is safer to start from checking the state cookie, to avoid breaking some user authentications where the recalculated and redirect uris differ in some trailing `/` - because if we start comparing them then we'd need to do what the OIDC spec requires, do the exact match, while some providers might be lenient enough to handle these minor differences and they have to compare it anyway when the code to token exchange is requested.

All in all, IMHO, it is better to leave it as is. It is not going affect the treatment of the non-authenticated requests with `code`, `error`, etc. if this code fails where we have a state cookie, `code` but it is not a redirect from OIDC provider then it will mean there is a bug in removing the state cookies - but I don't think it is going to happen, we test the cookies are being removed

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java (hunk 4 above)
Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java:297]: @FroMage Right, but the `referer` header has a single value, or have I missed your point ? I mean, this is check is not guaranteed to succeed, but it is not a big problem - since the only thing we are deciding upon here is how to fail, see my response to Pedro as well: whether to return `401` immediately or redirect the user back to the OIDC provider to sign in again

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java (hunk 3 above)
Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java:80]: @FroMage  I nearly started coding again :-) around replacing the referrer check with the redirect uri check, but again, I don't think it will work reliably, apart from the minor `/` differences, the issue with forcing `https`, we have to compare the absolute URI, it is just too messy, i.e Routing Context provides the `http:` based one, we calculate it as `https:` based one, etc.
I'll just leave things as they are

Comment (FroMage) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java:80]: Well, it's not an issue of speed but correctness: if we have a state cookie but we land for some reason on a page which is not a callback URI, the OIDC code will be invoked and read the `code` param (which may not be related to OIDC) and possibly read the form body when it shouldn't. I just don't see why we even look at anything if we're not in a callback URI.

Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java:80]: @FroMage I know, my comments can be long, but please read through them, I've gone through all of it; the speed was only mentioned to support the fact the state cookie is checked first, but both the cookie and the redirect URI have to be checked.

>  if we have a state cookie but we land for some reason on a page which is not a callback URI

`quarkus-oidc` does not have uncertainties like this one. It won't happen. As I said above, if it does happen - then it has a bug but we do test the state cookies are removed - they are removed immediately after a redirect. So a case where an unauthenticated user calls with a custom `code` but the state cookie is there is theoretical and does not apply to quarkus-oidc.

>  I just don't see why we even look at anything if we're not in a callback URI.

We do calculate it to complete the code exchange if the state cookie exists. If the state cookie exists then it must mean only one thing - it is a redirect from OIDC
 
if you'd like you can test this PR to verify.

Comment (FroMage) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java:80]: OK whatever.

Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java:80]: @FroMage Have a look at `CodeAuthenticationMechanism` in this PR, the `absolute` redirect URI is recalculated pretty much immediately after the state cookie is checked - it is submitted to the code to token exchange request - it will fail if it does not match the absolute  one registered in the provider. See also my concerns on doing the comparing the redirect URIs in quarkus-oidc - it can be messy and not very reliable - we let the provider compare it which is required in any case.

I think the current approach is sound, it has really worked well until now so I don't think we should start changing it. And this PR fixes the `code` bug in the unauthenticated request - and the `form_post` support will flow from it

**Review by FroMage — APPROVED** [review]

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java (hunk 3 above)
Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java:80]: @FroMage So if you also check the redirect URI in your branch then you basically do it twice in a row (and if you check the relative paths then it is not reliable)

**Comment by sberyozkin** [comment]
@FroMage It will work fine, I promise :-).

I'll need to wait for Pedro @pedroigor to finalize if he is OK with the best effort check for the referer

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java (hunk 2 above)
Comment (pedroigor) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java:295]: I see. I'm still trying to figure out if this has some security implication because the header can be easily forged into the request. But don't think there is and it should improve UX.

Makes sense?

Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java:295]: @pedroigor Hi Pedro, 

> I'm still trying to figure out if this has some security implication because the header can be easily forged into the request. But don't think there is and it should improve UX. Makes sense?

I'm not sure I follow, can you clarify please ?

This header is only checked in the `getChallenge` method. We don't do any positive decision based on its match - we only check it to decide how to fail if `session cookie is not available but 'code' is`.

If it matches the Keycloak authorization URL then it is 401 (meaning the authentication has failed, no retries), if it does not match it - it is a new unauthenticated request, the user goes to Keycloak/etc. This referer won't be used to redirect the user.

We can totally drop this check, but that will mean it will always be only a redirect to Keycloak `if the state cookie is absent but the code is there`; the referer check it gives us an option to react to this case in a more nuanced way.
It is really about this use case, `how to fail when the code is available but the state cookie is not`.

I'm not sure, may be I will just drop this Referer check. We have a test where a state cookie is missing but the code is, and 401 is expected. Without this check I'll have to tweak the test to expect `302` to Keycloak in this case though.

**Comment by sberyozkin** [comment]
@FroMage @pedroigor Yet again I've started experimenting with the idea of checking the redirect path (though only instead of checking the referer), when deciding if the challenge should end the flow with 401 (scenario: state cookie is lost, code is there), and stopped - because what prevents a user sending an initial unauthenticated request with the custom code to the URI which matches the one the OIDC Provider will also use to redirect the user to ? All in all, starting with checking the redirect path does not work.
I think it is totally safe just to check the referrer and fail with 401 in case of a match, to avoid the redirect loops when the state cookie was lost after the redirect.
