### PR TITLE
Fix WithSpan uni and multi

### LINKED ISSUE #25453: Mutiny is not compatible with quarkus opentelemetry
### Describe the bug

Hello there,

we are currently trying to implement opentelemetry using the quarkus opentelemetry package. We are using mutiny in a lot of places in our application. Now we are facing the following issue:
Every time we are using Uni/Multi in our Code, the tracing information is wrong. There are 2 main issues:

- The recorded duration takes only the synchronous part of the method into account
- methods called inside of the Uni/Multi, for example transformation or invoke blocks, are not correlated to the parent span

We think these issues are there due to the threading nature of Mutiny and that the opentelemetry context is lost during those thread switches. Do you have any idea on compatibility? I know there is a smallrye-opentelemetry package here on github, however it is labeled as a POC so not sure what the current situation is

We have opened an issue with Mutiny directly already, but they redirected us here
https://github.com/smallrye/smallrye-mutiny/issues/911

### PR DESCRIPTION
**Pull request by brunobat**
- Fixes #25453

### CODE REVIEW

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/cdi/WithSpanInterceptor.java [hunk 1]
```diff
@@ -61,18 +63,27 @@ public Object span(final ArcInvocationContext invocationContext) throws Exceptio
...
         }
+        final Context currentSpanContext = spanContext;
 
         try {
             Object result = invocationContext.proceed();
-
             if (shouldStart) {
-                instrumenter.end(spanContext, methodRequest, null, null);
+                if (result instanceof Uni<?>) {
+                    ((Uni<?>) result).subscribe().with(
```
Comment (cescoffier) [inline extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/cdi/WithSpanInterceptor.java:72]: That's not correct. 
This is going to lead to 2 subscription on the Uni/Multi - which will likely executing the logic emitting the value twice. For Multi it's even worse, as you may end up with consuming an unbounded stream without back pressure.

The solution is:

```
return uni.onTermination().invoke((item, failure, cancelled) -> instrumenter.end ....)
```

For Multi:

```
return  multi.onTermination().invoke((failure, cancellation) -> instrumenter...)
```

For Uni, if failure != null && ! cancelled -> Success. I'm not sure how cancellation should be represented in the span. Do **not** check if the item is `null`, a Uni can emit `null`.

Same for Multi (failure != null. && ! cancelled)

**Review by cescoffier — CHANGES_REQUESTED** [review]

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/cdi/WithSpanInterceptor.java (hunk 1 above)
Comment (brunobat) [reply extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/cdi/WithSpanInterceptor.java:72]: Thanks. Will update the PR.

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/cdi/WithSpanInterceptor.java [hunk 2]
```diff
@@ -53,35 +57,100 @@ public Object span(final ArcInvocationContext invocationContext) throws Exceptio
                 invocationContext.getParameters(),
                 invocationContext.getInterceptorBindings());
 
+        final Class<?> returnType = invocationContext.getMethod().getReturnType();
         Context parentContext = Context.current();
```
Comment (brunobat) [inline extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/cdi/WithSpanInterceptor.java:61]: @cescoffier On the WithSpanInterceptorTest, the parent context is not cleaned up after calling the 1st test, verifying the Uni. 
The next test, instead of seeing no parent, will see the 1st created span. 
Not sure if this is a problem of the test setup itself...

Comment (brunobat) [reply extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/cdi/WithSpanInterceptor.java:61]: Yeah... start in one thread and end in a different one. 
would be nice to start the span in the same thread as the Uni...

File: extensions/opentelemetry/deployment/src/test/java/io/quarkus/opentelemetry/deployment/interceptor/WithSpanInterceptorTest.java [hunk 3]
```diff
@@ -179,6 +241,26 @@ public void spanChild() {
         public void spanRestClient() {
             spanRestClient.spanRestClient();
         }
+
+        @WithSpan(value = "withSpanAndUni")
+        public Uni<String> spanUni() {
+            return Uni.createFrom().item("hello Uni");
```
Comment (cescoffier) [inline extensions/opentelemetry/deployment/src/test/java/io/quarkus/opentelemetry/deployment/interceptor/WithSpanInterceptorTest.java:247]: I would duplicate all these to have truly async responses and not only items emitted immediately.

Something like:

```java
@Inject Vertx vertx;

public Uni<String> spanUniAsync() {
        return Uni.createFrom().emitter(e -> {
            vertx.setTimer(100, x -> e.complete("hello Uni");
        });
}
```

None of these run on a duplicated context, too, which might make propagation tricky. I recommend also testing with and without duplicated context.

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/cdi/WithSpanInterceptor.java (hunk 2 above)
Comment (cescoffier) [reply extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/cdi/WithSpanInterceptor.java:61]: There is no duplicated context in these tests. So, we are back to regular thread locals. 
But, yes, in the current state of the tests, I do not see where we switch to a different thread as the emission are synchronous.

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/cdi/WithSpanInterceptor.java [hunk 4]
```diff
@@ -53,35 +57,100 @@ public Object span(final ArcInvocationContext invocationContext) throws Exceptio
...
+            return invocationContext.proceed();
+        }
 
-            if (shouldStart) {
-                instrumenter.end(spanContext, methodRequest, null, null);
+        if (isUni(returnType)) {
+            final Context currentSpanContext = instrumenter.start(parentContext, methodRequest);
+            final Scope currentScope = currentSpanContext.makeCurrent();
+            try {
+                return ((Uni<Object>) invocationContext.proceed()).onTermination().invoke((o, throwable, aCancelled) -> {
```
Comment (cescoffier) [inline extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/cdi/WithSpanInterceptor.java:72]: Avoid the lambda.

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/cdi/WithSpanInterceptor.java [hunk 5]
```diff
@@ -53,35 +57,100 @@ public Object span(final ArcInvocationContext invocationContext) throws Exceptio
...
+                    if (aCancelled) {
+                        instrumenter.end(currentSpanContext, methodRequest, null, new RuntimeException("Cancelled"));
```
Comment (cescoffier) [inline extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/cdi/WithSpanInterceptor.java:74]: Not sure it makes sense, but the JDK has a cancellation exception.

File: integration-tests/opentelemetry-reactive/src/main/java/io/quarkus/it/opentelemetry/reactive/ReactiveResource.java [hunk 6]
```diff
@@ -25,10 +27,17 @@ public class ReactiveResource {
...
-        return Uni.createFrom().item("Hello " + name).onItem().delayIt().by(Duration.ofSeconds(2))
+        return Uni.createFrom().item("Hello " + name).onItem().delayIt().by(Duration.ofSeconds(SECONDS_DELAY))
                 .eventually((Runnable) span::end);
     }
 
+    @GET
+    @Path("/hello-get-uni")
+    @WithSpan("helloGetUni")
+    public Uni<String> helloGetUni() {
+        return Uni.createFrom().item("helloGetUni").onItem().delayIt().by(Duration.ofSeconds(SECONDS_DELAY));
```
Comment (cescoffier) [inline integration-tests/opentelemetry-reactive/src/main/java/io/quarkus/it/opentelemetry/reactive/ReactiveResource.java:38]: Ah ah, here comes the thread! 
Delay uses a scheduler underneath (the Quarkus scheduler). We do not propagate the duplicated context in these cases (we discussed it, and to avoid leaks we didn't do it).

So, if you want to use delay, either capture the context and use a ContextScheduler (`.delayIt().on(executor).by(...)`) or use the approach I mentioned above using `vertx.timer(...)` - or both to cover every cases.

File: integration-tests/opentelemetry-reactive/src/main/java/io/quarkus/it/opentelemetry/reactive/ReactiveResource.java [hunk 7]
```diff
@@ -12,10 +12,12 @@
 
 import io.opentelemetry.api.trace.Span;
 import io.opentelemetry.api.trace.Tracer;
+import io.opentelemetry.instrumentation.annotations.WithSpan;
 import io.smallrye.mutiny.Uni;
 
 @Path("/reactive")
 public class ReactiveResource {
+    public static final int SECONDS_DELAY = 1;
```
Comment (cescoffier) [inline integration-tests/opentelemetry-reactive/src/main/java/io/quarkus/it/opentelemetry/reactive/ReactiveResource.java:20]: Too long—When I do such tests, I only delay them by 10 or 100ms. The delay itself introduces the I/O / thread switch you want. The duration just makes the test longer.

**Review by cescoffier — CHANGES_REQUESTED** [review]

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/cdi/WithSpanInterceptor.java (hunk 4 above)
Comment (brunobat) [reply extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/cdi/WithSpanInterceptor.java:72]: yes... will do a cleanup later.

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/cdi/WithSpanInterceptor.java (hunk 5 above)
Comment (brunobat) [reply extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/cdi/WithSpanInterceptor.java:74]: will try

File: integration-tests/opentelemetry-reactive/src/main/java/io/quarkus/it/opentelemetry/reactive/ReactiveResource.java (hunk 7 above)
Comment (brunobat) [reply integration-tests/opentelemetry-reactive/src/main/java/io/quarkus/it/opentelemetry/reactive/ReactiveResource.java:20]: yes... I decreased it already... Will check how brittle is the setup

File: integration-tests/opentelemetry-reactive/src/main/java/io/quarkus/it/opentelemetry/reactive/ReactiveResource.java (hunk 6 above)
Comment (brunobat) [reply integration-tests/opentelemetry-reactive/src/main/java/io/quarkus/it/opentelemetry/reactive/ReactiveResource.java:38]: got it

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/cdi/WithSpanInterceptor.java (hunk 4 above)
Comment (brunobat) [reply extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/cdi/WithSpanInterceptor.java]: done

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/cdi/WithSpanInterceptor.java (hunk 5 above)
Comment (brunobat) [reply extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/cdi/WithSpanInterceptor.java]: done

File: integration-tests/opentelemetry-reactive/src/main/java/io/quarkus/it/opentelemetry/reactive/ReactiveResource.java (hunk 6 above)
Comment (brunobat) [reply integration-tests/opentelemetry-reactive/src/main/java/io/quarkus/it/opentelemetry/reactive/ReactiveResource.java]: done

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/cdi/WithSpanInterceptor.java (hunk 2 above)
Comment (brunobat) [reply extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/cdi/WithSpanInterceptor.java:69]: updated the above OpenTelemetryMpContextPropagationProvider to not restore the previous context only if there is an open span.

File: extensions/opentelemetry/deployment/src/test/java/io/quarkus/opentelemetry/deployment/interceptor/WithSpanInterceptorTest.java [hunk 8]
```diff
@@ -59,6 +63,20 @@ public class WithSpanInterceptorTest {
     @AfterEach
     void tearDown() {
         spanExporter.reset();
+        // All tests execute in the same thread. For the ones using Uni/Multi, there is no automatic Duplicated context,
```
Comment (cescoffier) [inline extensions/opentelemetry/deployment/src/test/java/io/quarkus/opentelemetry/deployment/interceptor/WithSpanInterceptorTest.java:66]: Let's remove it.

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/propagation/OpenTelemetryMpContextPropagationProvider.java [hunk 9]
```diff
@@ -26,7 +27,10 @@ public ThreadContextController begin() {
                     return new ThreadContextController() {
                         @Override
                         public void endContext() throws IllegalStateException {
-                            QuarkusContextStorage.INSTANCE.attach(currentContext);
+                            Span span = Span.fromContext(currentContext);
```
Comment (cescoffier) [inline extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/propagation/OpenTelemetryMpContextPropagationProvider.java:30]: Ok, that's the trick!

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/cdi/WithSpanInterceptor.java [hunk 10]
```diff
@@ -53,35 +65,108 @@ public Object span(final ArcInvocationContext invocationContext) throws Exceptio
...
+            final Context currentSpanContext = instrumenter.start(parentContext, methodRequest);
+            final Scope currentScope = currentSpanContext.makeCurrent();
+            return ((Uni<Object>) invocationContext.proceed()).onTermination()
+                    .invoke(new Functions.TriConsumer<Object, Throwable, Boolean>() {
+                        @Override
+                        public void accept(Object o, Throwable throwable, Boolean aCancelled) {
+                            try {
+                                if (aCancelled) {
+                                    instrumenter.end(currentSpanContext, methodRequest, null,
+                                            new CancellationException("Cancelled"));
```
Comment (cescoffier) [inline extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/cdi/WithSpanInterceptor.java:86]: Do you need to pass a String? A cancellation exception is only thrown on cancellation

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/cdi/WithSpanInterceptor.java [hunk 11]
```diff
@@ -53,35 +65,108 @@ public Object span(final ArcInvocationContext invocationContext) throws Exceptio
...
-                scope.close();
+        if (isUni(returnType)) {
+            final Context currentSpanContext = instrumenter.start(parentContext, methodRequest);
+            final Scope currentScope = currentSpanContext.makeCurrent();
+            return ((Uni<Object>) invocationContext.proceed()).onTermination()
+                    .invoke(new Functions.TriConsumer<Object, Throwable, Boolean>() {
+                        @Override
+                        public void accept(Object o, Throwable throwable, Boolean aCancelled) {
+                            try {
+                                if (aCancelled) {
```
Comment (cescoffier) [inline extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/cdi/WithSpanInterceptor.java:84]: isCancelled maybe?

**Review by cescoffier — APPROVED** [review]
Few minor comments

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/cdi/WithSpanInterceptor.java (hunk 11 above)
Comment (brunobat) [reply extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/cdi/WithSpanInterceptor.java:84]: sure

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/cdi/WithSpanInterceptor.java (hunk 10 above)
Comment (brunobat) [reply extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/cdi/WithSpanInterceptor.java:86]: yes, no need

File: extensions/opentelemetry/deployment/src/test/java/io/quarkus/opentelemetry/deployment/interceptor/WithSpanInterceptorTest.java (hunk 8 above)
Comment (brunobat) [reply extensions/opentelemetry/deployment/src/test/java/io/quarkus/opentelemetry/deployment/interceptor/WithSpanInterceptorTest.java:66]: ok

**Comment by luneo7** [comment]
Can this be backported to 3.8?

**Comment by brunobat** [comment]
I don't see any inconvenient, added the tag, @luneo7
