### PR TITLE
Qute - fix template extensions regression

### LINKED ISSUE #26306: Qute: Template extensions regresion in Quarkus 2.10.0
### Describe the bug

The following code works with Quarkus 2.9.x but it is not working with Quarkus 2.10.0

```java

import io.quarkus.qute.TemplateExtension;

import java.time.format.DateTimeFormatter;
import java.time.temporal.TemporalAccessor;

@TemplateExtension(namespace = "datetime")
public class DateTimeExtensions {

    public static String formatDate(TemporalAccessor date) {
        return DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss").format(date);
    }
}    
```

```html
<small>{datetime:formatDate(it.creationDate)}</small>
```            

creationDate has type ```java,time.LocalDateTime``` 

If I replace TemporalAccessor with LocalDateTime template extension is working as expected, but now it is not working when I'm using interface in extension method.

### Expected behavior

This extension should be working not only with classes but also with interfaces.

### Actual behavior

Quarkus  is throwing exception

```
{datetime:formatDate(it.creationDate)}: No matching namespace [datetime] extension method found
```

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mkouba**
- resolves #26306

### CODE REVIEW

**Comment by mkouba** [comment]
@kucharzyk It would be great if you could test this PR.

File: extensions/qute/deployment/src/main/java/io/quarkus/qute/deployment/Types.java [hunk 1]
```diff
@@ -180,6 +180,18 @@ static boolean isAssignableFrom(DotName class1, DotName class2, IndexView index,
         return assignableInfo.isAssignableFrom(class2);
     }
 
+    static void indexHierarchy(ClassInfo classInfo, IndexView index) {
```
Comment (gastaldi) [inline extensions/qute/deployment/src/main/java/io/quarkus/qute/deployment/Types.java:183]: Shouldn't this method return something?

Comment (mkouba) [reply extensions/qute/deployment/src/main/java/io/quarkus/qute/deployment/Types.java:183]: Not really. We just need to make sure all interfaces and subclasses are part of the bean archive index...

Comment (gastaldi) [reply extensions/qute/deployment/src/main/java/io/quarkus/qute/deployment/Types.java:183]: Ah okay. I didn't know that you could add interfaces and subclasses to the bean archive by calli g `index.getClassByName`

**Review by gastaldi — APPROVED** [review]
LGTM

File: extensions/qute/deployment/src/main/java/io/quarkus/qute/deployment/Types.java (hunk 1 above)
Comment (gsmet) [reply extensions/qute/deployment/src/main/java/io/quarkus/qute/deployment/Types.java:183]: TBH, I don't understand either how this is supposed to work? Does it really index something when calling a method of an `IndexView`?

Comment (mkouba) [reply extensions/qute/deployment/src/main/java/io/quarkus/qute/deployment/Types.java:183]: So the bean archive index is "computing": https://github.com/quarkusio/quarkus/blob/main/independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanArchives.java#L114-L120, i.e. something like [`CombinedIndexBuildItem#getComputingIndex()`](https://github.com/quarkusio/quarkus/blob/main/core/deployment/src/main/java/io/quarkus/deployment/builditem/CombinedIndexBuildItem.java#L39) that was probably inspired by the bean archive functionality. The problem is that methods like `getKnownImplementors()` do not compute/index additional classes.

Comment (gastaldi) [reply extensions/qute/deployment/src/main/java/io/quarkus/qute/deployment/Types.java:183]: Looking at the sources, I believe it's because the `IndexView` implementation may be a `io.quarkus.arc.processor.BeanArchives.IndexWrapper` class, which adds some additional classes to the other method calls, but I may have misinterpreted that :)

Comment (mkouba) [reply extensions/qute/deployment/src/main/java/io/quarkus/qute/deployment/Types.java:183]: You're correct and this particular `IndexView` IS an instance of `BeanArchives.IndexWrapper`.
