### PR TITLE
Hot reload logging fixes

### LINKED ISSUE #6209: IllegalArgumentException: workerPoolSize must be > 0 if quarkus:dev fails to start
While developing an extension, if any error is thrown during initialization, the following misleading exception appears in the logs when running quarkus:dev: 

```
15:27:48,255 ERROR [io.qua.dev.DevModeMain] Failed to start quarkus: java.lang.IllegalArgumentException: workerPoolSize must be > 0
	at io.vertx.core.VertxOptions.setWorkerPoolSize(VertxOptions.java:275)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder.convertToVertxOptions(VertxCoreRecorder.java:151)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder.initializeWeb(VertxCoreRecorder.java:104)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder.startServerAfterFailedStart(VertxHttpRecorder.java:115)
	at io.quarkus.vertx.http.deployment.devmode.VertxHotReplacementSetup.handleFailedInitialStart(VertxHotReplacementSetup.java:30)
	at io.quarkus.dev.RuntimeUpdatesProcessor.startupFailed(RuntimeUpdatesProcessor.java:451)
	at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:192)
	at io.quarkus.dev.DevModeMain.start(DevModeMain.java:96)
	at io.quarkus.dev.DevModeMain.main(DevModeMain.java:67)
```

### PR DESCRIPTION
**Pull request by stuartwdouglas**
Fixes various logging problems on failed starts, including:
- Vert.x error about undeploying verticles before vert.x was initialized
- No logging if restart fails until issue is fixed
- Startup failure reason being logged twice

Fixes #6209

### CODE REVIEW

File: extensions/vertx/runtime/src/main/java/io/quarkus/vertx/runtime/VertxProducer.java [hunk 1]
```diff
@@ -115,6 +110,8 @@ void undeployVerticles(@Observes @BeforeDestroyed(ApplicationScoped.class) Objec
                     // Only existing instances are considered
                     try {
                         AbstractVerticle verticle = (AbstractVerticle) instance;
+                        io.vertx.mutiny.core.Vertx mutiny = beanManager.createInstance()
```
Comment (mkouba) [inline extensions/vertx/runtime/src/main/java/io/quarkus/vertx/runtime/VertxProducer.java:113]: So the only difference compared to the injected observer param is that the `Vertx` instance is only obtained if there is at least one bean that extends `AbstractVerticle`?

File: extensions/vertx/runtime/src/main/java/io/quarkus/vertx/runtime/VertxProducer.java [hunk 2]
```diff
@@ -34,25 +33,22 @@
 
     private static final Logger LOGGER = Logger.getLogger(VertxProducer.class);
 
-    @Inject
-    Vertx vertx;
-
     @Singleton
     @Produces
-    public EventBus eventbus() {
+    public EventBus eventbus(Vertx vertx) {
```
Comment (mkouba) [inline extensions/vertx/runtime/src/main/java/io/quarkus/vertx/runtime/VertxProducer.java:38]: So what happens if a user code injects `Vertx`?

**Comment by mkouba** [comment]
Hm, it would be useful to add some comments _why_ these changes fix the problems with logging in the dev mode...

File: extensions/vertx/runtime/src/main/java/io/quarkus/vertx/runtime/VertxProducer.java (hunk 1 above)
Comment (stuartwdouglas) [reply extensions/vertx/runtime/src/main/java/io/quarkus/vertx/runtime/VertxProducer.java:113]: One already created bean, which generally won't happen until runtime when you actually have vert.x. 

Currently if you fail in static init then this method is called, but vert.x is not ready yet (as it is a runtime bean), so you get an extra unrelated exception in your logs (and possible unclean shutdown).

File: extensions/vertx/runtime/src/main/java/io/quarkus/vertx/runtime/VertxProducer.java (hunk 2 above)
Comment (stuartwdouglas) [reply extensions/vertx/runtime/src/main/java/io/quarkus/vertx/runtime/VertxProducer.java:38]: It's undeployVerticles that is the problem, if it was in a different class these would be fine.

File: extensions/vertx/runtime/src/main/java/io/quarkus/vertx/runtime/VertxProducer.java (hunk 1 above)
Comment (mkouba) [reply extensions/vertx/runtime/src/main/java/io/quarkus/vertx/runtime/VertxProducer.java:113]: I see. That makes sense.

File: extensions/vertx/runtime/src/main/java/io/quarkus/vertx/runtime/VertxProducer.java (hunk 2 above)
Comment (mkouba) [reply extensions/vertx/runtime/src/main/java/io/quarkus/vertx/runtime/VertxProducer.java:38]: OK.

**Review by mkouba — APPROVED** [review]
