### PR TITLE
Check for null context (oidc logout flow)

### LINKED ISSUE #12029: Micrometer extension didn't work with the security-oauth2 extension
**Describe the bug**
When using micrometer extension and security-oauth2 I have the following exception:

```
 java.lang.NullPointerException
	at io.quarkus.micrometer.runtime.binder.vertx.MetricsContext.addRoutingContext(MetricsContext.java:44)
	at io.quarkus.micrometer.runtime.binder.vertx.VertxMeterFilter.handle(VertxMeterFilter.java:18)
	at io.quarkus.micrometer.runtime.binder.vertx.VertxMeterFilter.handle(VertxMeterFilter.java:10)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:133)
	at io.quarkus.vertx.http.runtime.security.HttpAuthorizer.doPermissionCheck(HttpAuthorizer.java:116)
	at io.quarkus.vertx.http.runtime.security.HttpAuthorizer.checkPermission(HttpAuthorizer.java:99)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$3.handle(HttpSecurityRecorder.java:214)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$3.handle(HttpSecurityRecorder.java:206)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:133)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$2$2.onItem(HttpSecurityRecorder.java:139)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$2$2.onItem(HttpSecurityRecorder.java:100)
```

The exception didn't occurs if I remove the security extensions.
The exception didn' occurs with smallrye-metrics.

This is the complete list of extensions I use: agroal, cdi, flyway, hibernate-orm, hibernate-orm-panache, hibernate-validator, jaeger, jdbc-postgresql, micrometer, mutiny, narayana-jta, rest-client, resteasy, resteasy-jsonb, security, security-oauth2, security-properties-file, smallrye-context-propagation, smallrye-fault-tolerance, smallrye-health, smallrye-openapi, smallrye-opentracing, swagger-ui

The same issue occurs with security-properties-file so it should occurs on all security extensions.

Adding DEBUG logging on Quarkus shows where the errors comes from:
```
DEBUG [io.qua.mic.run.bin.ver.VertxMeterFilter] (executor-thread-1) Handling event io.vertx.ext.web.impl.RoutingContextImpl@40da89c3 with context null
```
The Vert.x Context is null on this line this the NPE: https://github.com/quarkusio/quarkus/blob/master/extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/binder/vertx/VertxMeterFilter.java#L15

### PR DESCRIPTION
**Pull request by ebullient**
Resolves #12029

### CODE REVIEW

File: extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/binder/vertx/VertxHttpServerMetrics.java [hunk 1]
```diff
@@ -77,12 +77,14 @@
     @Override
     public MetricsContext responsePushed(MetricsContext socketMetric, HttpMethod method, String uri,
             HttpServerResponse response) {
-        String path = VertxMetricsTags.parseUriPath(matchPatterns, ignorePatterns, uri);
-        if (path != null) {
-            registry.counter(nameHttpServerPush,
-                    Tags.of(VertxMetricsTags.uri(path, response.getStatusCode()), VertxMetricsTags.method(method),
-                            VertxMetricsTags.outcome(response), VertxMetricsTags.status(response.getStatusCode())))
-                    .increment();
+        if (socketMetric != null) {
```
Comment (gsmet) [inline extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/binder/vertx/VertxHttpServerMetrics.java:80]: It's minor and you don't have to fix it this time but we usually recommend to do:
```
if (socketMetric == null) {
    return socketMetric; // or return null
}
```
rather than nesting ifs.

It's far more readable to just take care of the exceptional cases at the beginning of your method and then do your logic.

Comment (ebullient) [reply extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/binder/vertx/VertxHttpServerMetrics.java:80]: I actually thought of doing that first as I prefer positive checks, too. Give me a few minutes

Comment (gsmet) [reply extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/binder/vertx/VertxHttpServerMetrics.java:80]: Yeah it's not really about positive checks, I would have said the same thing if it would have been a negative one. The idea is to keep the normal flow as simple as possible by evacuating special cases first.

Comment (ebullient) [reply extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/binder/vertx/VertxHttpServerMetrics.java]: I simplified a few, and clarified javadoc re: null params & return values.

**Review by kenfinnigan — APPROVED** [review]

**Review by gsmet — APPROVED** [review]
