### PR TITLE
Resteasy Reactive: Fix support of media types with suffixes

### LINKED ISSUE #15982: Resteasy Reactive: Enhance support for media types with suffix
## Description

Follow-up to #15042. Media types with suffixes such as `application/hal+json` behave counterintuitively in Resteasy Reactive. For example, a `MessageBodyWriter` for `application/hal+json` is never used, but instead the normal provider for `json` is used since the suffix (`json`) is prioritized over the actual subtype (`hal`).

## Implementation ideas

See discussion in #15042, or more specifically, research regarding spec done by @FroMage: https://github.com/quarkusio/quarkus/issues/15042#issuecomment-780468801

## Reproducer

I have created a small reproducer to demonstrate the current state:

https://github.com/markusdlugi/mediatype-reproducer

The behavior is as follows:

- GET Request to http://localhost:8080/ with `Accept: json` returns `application/json`
  - --> as expected
- GET Request  to http://localhost:8080/ with `Accept: hal` returns `application/hal` and uses `HalProvider`
  - --> as expected
- GET Request  to http://localhost:8080/ with `Accept: hal+json` returns `application/json` and does **not** use `HalJsonProvider`
  - --> **not as expected**

Expected behavior would most likely be that a provider for `hal+json` is used, and if none exists, then it should fallback to using  a provider for `hal`. It should not fallback to `json`, at least not before trying the better fitting alternatives.

### PR DESCRIPTION
**Pull request by Sgitario**
Given a media type with suffix, for example: "application/test+json".

Before these changes, Resteasy Reactive was trying to find the writer/reader using only the suffix. For example, with a media type "application/test+json", it would only use "json" to locate the right writer/reader. 

Spite of this has been working well so far, if users provide a custom writer/reader for a concrete media type with suffix:

```java
@Provider
    @Produces("text/test+suffix")
    public static class SuffixMessageBodyWriter implements ServerMessageBodyWriter<Object> {

        @Override
        public boolean isWriteable(Class<?> type, Type genericType, ResteasyReactiveResourceInfo target, MediaType mediaType) {
           // ...
        }

        @Override
        public void writeResponse(Object o, Type genericType, ServerRequestContext context) {
            // ...
        }

        // ...
    }
```

The above writer will never be used. 

After these changes, we will use the media type with suffix, plus the split parts of the suffix. For example, if the media type with suffix is: "application/test+json", it will try to find the best writer/reader for "application/test+json", "application/test" and then "application/json" (In this order).

Fix https://github.com/quarkusio/quarkus/issues/15982

### CODE REVIEW

**Comment by Sgitario** [comment]
cc @markusdlugi @geoand

File: independent-projects/resteasy-reactive/common/runtime/src/main/java/org/jboss/resteasy/reactive/common/core/Serialisers.java [hunk 1]
```diff
@@ -76,18 +76,24 @@ public List<MessageBodyReader<?>> findReaders(ConfigurationImpl configuration, C
...
+            readerLookup(mediaType, runtimeType, desired, ret, goodTypeReaders);
             if (klass.isInterface()) {
                 klass = Object.class;
             } else {
                 klass = klass.getSuperclass();
             }
         } while (klass != null);
 
-        return ret;
+        List<MessageBodyReader<?>> matchingReaders = new ArrayList<>();
```
Comment (geoand) [inline independent-projects/resteasy-reactive/common/runtime/src/main/java/org/jboss/resteasy/reactive/common/core/Serialisers.java:87]: Can we specify the size here?

File: independent-projects/resteasy-reactive/common/runtime/src/main/java/org/jboss/resteasy/reactive/common/core/Serialisers.java [hunk 2]
```diff
@@ -76,18 +76,24 @@ public List<MessageBodyReader<?>> findReaders(ConfigurationImpl configuration, C
...
+        for (ResourceReader mediaTypeMatchingReader : ret) {
```
Comment (geoand) [inline independent-projects/resteasy-reactive/common/runtime/src/main/java/org/jboss/resteasy/reactive/common/core/Serialisers.java:88]: Can we avoid the use of the iterator here? We do that in various parts of the code in order to cut down on the number of objects created while serving a request

File: independent-projects/resteasy-reactive/common/runtime/src/main/java/org/jboss/resteasy/reactive/common/util/MediaTypeHelper.java [hunk 3]
```diff
@@ -267,20 +277,74 @@ public static boolean isUnsupportedWildcardSubtype(MediaType mediaType) {
...
-            mediaType = new MediaType(mediaType.getType(),
-                    mediaType.getSubtype().substring(plusIndex + 1),
-                    mediaType.getParameters());
+
+        if (mediaType.getSubtype() == null || !mediaType.getSubtype().contains(MEDIA_TYPE_SUFFIX_DELIM)) {
+            return Collections.singletonList(mediaType);
         }
-        return mediaType;
+
+        List<MediaType> effectiveMediaTypes = new ArrayList<>();
```
Comment (geoand) [inline independent-projects/resteasy-reactive/common/runtime/src/main/java/org/jboss/resteasy/reactive/common/util/MediaTypeHelper.java:327]: Can we specify a size here?

File: independent-projects/resteasy-reactive/common/runtime/src/main/java/org/jboss/resteasy/reactive/common/util/MediaTypeHelper.java [hunk 4]
```diff
@@ -267,20 +277,74 @@ public static boolean isUnsupportedWildcardSubtype(MediaType mediaType) {
...
+        for (String subType : subTypes) {
+            effectiveMediaTypes.add(new MediaType(mediaType.getType(), subType, mediaType.getParameters()));
+        }
+
+        return Collections.unmodifiableList(effectiveMediaTypes);
+    }
+
+    private static int countMatchingMediaTypes(List<MediaType> produces, List<MediaType> mediaTypes) {
+        int count = 0;
+        for (MediaType mediaType : mediaTypes) {
```
Comment (geoand) [inline independent-projects/resteasy-reactive/common/runtime/src/main/java/org/jboss/resteasy/reactive/common/util/MediaTypeHelper.java:339]: Same comment about the iterator here

**Review by geoand — COMMENTED** [review]
Great! I added a couple small comments

File: independent-projects/resteasy-reactive/common/runtime/src/main/java/org/jboss/resteasy/reactive/common/core/Serialisers.java (hunk 1 above)
Comment (Sgitario) [reply independent-projects/resteasy-reactive/common/runtime/src/main/java/org/jboss/resteasy/reactive/common/core/Serialisers.java:87]: Done

File: independent-projects/resteasy-reactive/common/runtime/src/main/java/org/jboss/resteasy/reactive/common/core/Serialisers.java (hunk 2 above)
Comment (Sgitario) [reply independent-projects/resteasy-reactive/common/runtime/src/main/java/org/jboss/resteasy/reactive/common/core/Serialisers.java:88]: Done. To be precise, I reverted this change.

File: independent-projects/resteasy-reactive/common/runtime/src/main/java/org/jboss/resteasy/reactive/common/util/MediaTypeHelper.java (hunk 3 above)
Comment (Sgitario) [reply independent-projects/resteasy-reactive/common/runtime/src/main/java/org/jboss/resteasy/reactive/common/util/MediaTypeHelper.java:327]: Done

File: independent-projects/resteasy-reactive/common/runtime/src/main/java/org/jboss/resteasy/reactive/common/util/MediaTypeHelper.java (hunk 4 above)
Comment (Sgitario) [reply independent-projects/resteasy-reactive/common/runtime/src/main/java/org/jboss/resteasy/reactive/common/util/MediaTypeHelper.java]: Fixed

**Comment by Sgitario** [comment]
@geoand I think I've addressed all your comments. Thanks!

**Review by geoand — APPROVED** [review]
Great, thanks!

**Comment by markusdlugi** [comment]
Thanks a lot for the fix @Sgitario, much appreciated!

**Comment by geoand** [comment]
Good point
