### PR TITLE
Resolve nested type variables correctly

### LINKED ISSUE #4039: Invalid dependency / injection resolution for producers
```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:0.21.1:build (default) on project apicurio-registry-storage-kafka: Failed to build a runnable JAR: Failed to build a runner jar: Failed to augment application classes: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: Found 2 deployment problems: 
[ERROR] [1] Ambiguous dependencies for type java.util.function.Function<org.apache.kafka.clients.producer.ProducerRecord<io.apicurio.registry.kafka.proto.Reg$UUID, io.apicurio.registry.kafka.proto.Reg$RegistryValue>, java.util.concurrent.CompletableFuture<org.apache.kafka.clients.producer.RecordMetadata>> and qualifiers [@Default]
[ERROR] 	- java member: io.apicurio.registry.kafka.KafkaRegistryStorage#registryProducer
[ERROR] 	- declared on CLASS bean [types=[io.apicurio.registry.kafka.KafkaRegistryStorageHandle, io.apicurio.registry.storage.RegistryStorage, io.apicurio.registry.storage.impl.SimpleMapRegistryStorage, java.lang.Object, io.apicurio.registry.kafka.KafkaRegistryStorage, io.apicurio.registry.storage.impl.AbstractMapRegistryStorage], qualifiers=[@Default, @Any], target=io.apicurio.registry.kafka.KafkaRegistryStorage]
[ERROR] 	- available beans:
[ERROR] 		- PRODUCER METHOD bean [types=[java.lang.AutoCloseable, java.util.function.Function<org.apache.kafka.clients.producer.ProducerRecord<K, V>, java.util.concurrent.CompletableFuture<org.apache.kafka.clients.producer.RecordMetadata>>, io.apicurio.registry.kafka.utils.ProducerActions<io.apicurio.registry.kafka.proto.Reg$UUID, io.apicurio.registry.kafka.proto.Reg$RegistryValue>, java.lang.Object], qualifiers=[@Default, @Any], target=io.apicurio.registry.kafka.utils.ProducerActions<io.apicurio.registry.kafka.proto.Reg$UUID, io.apicurio.registry.kafka.proto.Reg$RegistryValue> registryProducer(java.util.Properties properties), declaringBean=io.apicurio.registry.kafka.KafkaRegistryConfiguration]
[ERROR] 		- PRODUCER METHOD bean [types=[java.lang.AutoCloseable, java.util.function.Function<org.apache.kafka.clients.producer.ProducerRecord<K, V>, java.util.concurrent.CompletableFuture<org.apache.kafka.clients.producer.RecordMetadata>>, java.lang.Object, io.apicurio.registry.kafka.utils.ProducerActions<java.lang.Long, io.apicurio.registry.kafka.snapshot.StorageSnapshot>], qualifiers=[@Default, @Any], target=io.apicurio.registry.kafka.utils.ProducerActions<java.lang.Long, io.apicurio.registry.kafka.snapshot.StorageSnapshot> snapshotProducer(java.util.Properties properties), declaringBean=io.apicurio.registry.kafka.KafkaRegistryConfiguration]
[ERROR] [2] Ambiguous dependencies for type java.util.function.Function<org.apache.kafka.clients.producer.ProducerRecord<java.lang.Long, io.apicurio.registry.kafka.snapshot.StorageSnapshot>, java.util.concurrent.CompletableFuture<org.apache.kafka.clients.producer.RecordMetadata>> and qualifiers [@Default]
[ERROR] 	- java member: io.apicurio.registry.kafka.KafkaRegistryStorage#snapshotProducer
[ERROR] 	- declared on CLASS bean [types=[io.apicurio.registry.kafka.KafkaRegistryStorageHandle, io.apicurio.registry.storage.RegistryStorage, io.apicurio.registry.storage.impl.SimpleMapRegistryStorage, java.lang.Object, io.apicurio.registry.kafka.KafkaRegistryStorage, io.apicurio.registry.storage.impl.AbstractMapRegistryStorage], qualifiers=[@Default, @Any], target=io.apicurio.registry.kafka.KafkaRegistryStorage]
[ERROR] 	- available beans:
[ERROR] 		- PRODUCER METHOD bean [types=[java.lang.AutoCloseable, java.util.function.Function<org.apache.kafka.clients.producer.ProducerRecord<K, V>, java.util.concurrent.CompletableFuture<org.apache.kafka.clients.producer.RecordMetadata>>, io.apicurio.registry.kafka.utils.ProducerActions<io.apicurio.registry.kafka.proto.Reg$UUID, io.apicurio.registry.kafka.proto.Reg$RegistryValue>, java.lang.Object], qualifiers=[@Default, @Any], target=io.apicurio.registry.kafka.utils.ProducerActions<io.apicurio.registry.kafka.proto.Reg$UUID, io.apicurio.registry.kafka.proto.Reg$RegistryValue> registryProducer(java.util.Properties properties), declaringBean=io.apicurio.registry.kafka.KafkaRegistryConfiguration]
[ERROR] 		- PRODUCER METHOD bean [types=[java.lang.AutoCloseable, java.util.function.Function<org.apache.kafka.clients.producer.ProducerRecord<K, V>, java.util.concurrent.CompletableFuture<org.apache.kafka.clients.producer.RecordMetadata>>, java.lang.Object, io.apicurio.registry.kafka.utils.ProducerActions<java.lang.Long, io.apicurio.registry.kafka.snapshot.StorageSnapshot>], qualifiers=[@Default, @Any], target=io.apicurio.registry.kafka.utils.ProducerActions<java.lang.Long, io.apicurio.registry.kafka.snapshot.StorageSnapshot> snapshotProducer(java.util.Properties properties), declaringBean=io.apicurio.registry.kafka.KafkaRegistryConfiguration]
```

```java
    @Produces
    @ApplicationScoped
    public ProducerActions<Long, StorageSnapshot> snapshotProducer(
        @KafkaProperties("registry.kafka.snapshot-producer.") Properties properties
    ) {
        return new AsyncProducer<>(
            properties,
            Serdes.Long().serializer(),
            new StorageSnapshotSerde()
        );
    }

    @Produces
    @ApplicationScoped
    public ProducerActions<Reg.UUID, Reg.RegistryValue> registryProducer(
        @KafkaProperties("registry.kafka.registry-producer.") Properties properties
    ) {
        return new AsyncProducer<>(
            properties,
            ProtoSerde.parsedWith(Reg.UUID.parser()),
            ProtoSerde.parsedWith(Reg.RegistryValue.parser())
        );
    }

    @Inject
    Function<ProducerRecord<Reg.UUID, Reg.RegistryValue>, CompletableFuture<RecordMetadata>> registryProducer;

    @Inject
    Function<ProducerRecord<Long, StorageSnapshot>, CompletableFuture<RecordMetadata>> snapshotProducer;


public interface ProducerActions<K, V> extends Function<ProducerRecord<K, V>, CompletableFuture<RecordMetadata>>, AutoCloseable {
}

public class AsyncProducer<K, V> implements ProducerActions<K, V> {

```

### PR DESCRIPTION
**Pull request by mkouba**
- resolves #4039

### CODE REVIEW

**Comment by mkouba** [comment]
@alesj it would be great if you could verify that this PR fixes your problem.

**Comment by mkouba** [comment]
@gsmet do you happen to know why this PR did not trigger a CI build? Is it possible to trigger CI manually?

**Comment by gsmet** [comment]
It happens from time to time. The only way I found to trigger the build in this case was to force-push again.

**Comment by mkouba** [comment]
@gsmet ok, it worked. Thanks.

**Comment by alesj** [comment]
@mkouba nope, still doesn't work: https://gist.github.com/alesj/c9d497fae16ae114ba8275a9be7e62ff

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Types.java [hunk 1]
```diff
@@ -302,7 +302,7 @@ static Type resolveTypeParam(Type typeParam, Map<TypeVariable, Type> resolvedTyp
                         resolvedTypeParameters, index);
                 Type[] typeParams = new Type[typeParameters.size()];
                 for (int i = 0; i < typeParameters.size(); i++) {
-                    typeParams[i] = resolveTypeParam(arguments.get(0), resolvedMap, index);
+                    typeParams[i] = resolveTypeParam(arguments.get(i), resolvedMap, index);
```
Comment (mkouba) [inline independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Types.java]: @alesj Nice catch! And this was the cause ;-). Could you try it again?

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Types.java [hunk 2]
```diff
@@ -277,20 +279,37 @@ static Type getProviderType(ClassInfo classInfo) {
...
         return resolvedMap;
     }
 
+    static Type resolveTypeParam(Type typeParam, Map<TypeVariable, Type> resolvedTypeParameters, IndexView index) {
+        if (typeParam.kind() == Kind.TYPE_VARIABLE) {
+            return resolvedTypeParameters.getOrDefault(typeParam, typeParam);
+        } else if (typeParam.kind() == Kind.PARAMETERIZED_TYPE) {
+            ParameterizedType parameterizedType = typeParam.asParameterizedType();
+            ClassInfo classInfo = index.getClassByName(parameterizedType.name());
+            if (classInfo != null) {
```
Comment (manovotn) [inline independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Types.java]: If the class isn't on index, shouldn't we throw an exception or at least log something?
An injection scenario relying on this structure and not having the class indexed would give user an hard-to-read unsatisfied dependency then.

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Types.java [hunk 3]
```diff
@@ -208,6 +209,7 @@ static Type getProviderType(ClassInfo classInfo) {
             // Canonical ParameterizedType with unresolved type variables
             Type[] typeParams = new Type[typeParameters.size()];
             for (int i = 0; i < typeParameters.size(); i++) {
+                // TODO more complicated hierarchy
```
Comment (manovotn) [inline independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Types.java]: What hierarchy do you mean?

Comment (mkouba) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Types.java]: Oops, I thought I removed this TODO...

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Types.java (hunk 2 above)
Comment (mkouba) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Types.java]: That's a good point. However, it should be probably addressed in a separate issue because it's a more general problem. Currently, our `io.quarkus.arc.processor.BeanArchives.IndexWrapper` attempts to index classes that are not part of the index. As a result, it's very unlikely that `null` is returned.

Comment (manovotn) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Types.java]: @mkouba https://github.com/quarkusio/quarkus/issues/4080 feel free to drop a comment.

**Review by manovotn — APPROVED** [review]
Looks good, I've created separate issue for the note I added.
Ideally, we would like @alesj to confirm this works for him before merging :)

**Comment by alesj** [comment]
@mkouba @manovotn it works! :-)
