### PR TITLE
Use SelectionQuery/MutationQuery wherever possible in Panache + avoid warning HHH000104

### LINKED ISSUE #41459: PanacheQuery: singleResultOptional() gives hibernate warning "HHH000104"
### Describe the bug

When a query involves `JOIN FETCH ` on one to many relation and use singleResultOptional() to query the data, below warning is coming in the logs
`"HHH000104: firstResult/maxResults specified with collection fetch; applying in memory!"`

This is because the function applies limit of 2 on the query and hence trigger the warning. 

### Expected behavior

Remove the limit which will avoid the warning as for a user this might be confusing as no pagination or range is specified.
It will throw 'NonUniqueResultException' anyway if more than one results are found. 

### Actual behavior

`"HHH000104: firstResult/maxResults specified with collection fetch; applying in memory!"` 
warning in logs even though there is only one entity in the result set.

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

jdk 21

### Quarkus version or git rev

3.8.5

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by yrodiere**
1. Moves to `SelectionQuery`/`MutationQuery`, which are the recommended way to create queries in Hibernate when using native APIs (`Session`).
   * Side effect: works around https://hibernate.atlassian.net/browse/HHH-18306 in the upcoming ORM 6.6 upgrade -- hopefully we won't care because the problem will be fixed in 6.6.0.Final, but it's convenient for me in [my draft PR](https://github.com/quarkusio/quarkus/pull/41359) using 6.6.0.CR1.
2. Fixes #41459

Migration guide entry:

```adoc
== Hibernate ORM with Panache

=== Move to `SelectionQuery`/`MutationQuery`

Panache now relies on different methods to run queries:
instead of calling `Session#createQuery`, which returns a `Query` object,
Panache now calls `Session#createSelectionQuery`/`Session#createMutationQuery`,
which returns a `SelectionQuery`/`MutationQuery`.

This may affect applications in the following way:

* _Some_ exceptions thrown in case of misuse won't get wrapped anymore.
For example an invalid query `String` may result in a `SemanticException`,
whereas it used to result in an `IllegalArgumentException` whose cause was a `SemanticException`.
Exceptions thrown in case of unexpected database content are unaffected.
For example `NoResultException` will still be thrown as it used to be.
* Application tests using Panache and relying on a mocked `Session` may not work anymore,
until they adjust their mocking to mock `Session#createSelectionQuery`/`Session#createMutationQuery`
instead of `Session#createQuery`.
```

### CODE REVIEW

File: extensions/panache/hibernate-orm-panache-common/runtime/src/main/java/io/quarkus/hibernate/orm/panache/common/runtime/CommonPanacheQueryImpl.java [hunk 1]
```diff
@@ -336,14 +335,9 @@ public <T extends Entity> T singleResult() {
 
     @SuppressWarnings("unchecked")
     public <T extends Entity> Optional<T> singleResultOptional() {
-        SelectionQuery hibernateQuery = createQuery(2);
```
Comment (yrodiere) [inline extensions/panache/hibernate-orm-panache-common/runtime/src/main/java/io/quarkus/hibernate/orm/panache/common/runtime/CommonPanacheQueryImpl.java]: Interestingly, we were using a limit for `singleResultOptional`, but not for `singleResult` :|

**Review by gsmet — APPROVED** [review]
