### PR TITLE
close handlers and free all associated resources.

### LINKED ISSUE #5522: LogManager GENERIC_FAILURE on Windows 10
**Describe the bug**
when auto redeploy occurs, an exception with log file rises

> 10:48:55 INFO  [io.quarkus] Quarkus stopped in 0.020s
> 10:48:55 INFO  [io.quarkus.deployment.QuarkusAugmentor] Beginning quarkus augmentation
> 10:48:55 INFO  [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 179ms
> LogManager error of type GENERIC_FAILURE: Failed to move file log\dataprocessor.log to log\dataprocessor.log.2019-11-15.1.
> java.nio.file.FileSystemException: log\dataprocessor.log -> log\dataprocessor.log.2019-11-15.1: The process cannot access the file because it is being used by another process.
> 
>         at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
>         at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
>         at java.base/sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:395)
>         at java.base/sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:292)
>         at java.base/java.nio.file.Files.move(Files.java:1421)
>         at org.jboss.logmanager.handlers.SuffixRotator.move(SuffixRotator.java:239)
>         at org.jboss.logmanager.handlers.SuffixRotator.rotate(SuffixRotator.java:167)
>         at org.jboss.logmanager.handlers.SuffixRotator.rotate(SuffixRotator.java:226)
>         at org.jboss.logmanager.handlers.PeriodicSizeRotatingFileHandler.setFile(PeriodicSizeRotatingFileHandler.java:154)
>         at io.quarkus.runtime.logging.LoggingSetupRecorder.configureFileHandler(LoggingSetupRecorder.java:173)
>         at io.quarkus.runtime.logging.LoggingSetupRecorder.initializeLogging(LoggingSetupRecorder.java:90)
>         at io.quarkus.deployment.steps.LoggingResourceProcessor$setupLoggingRuntimeInit33.deploy_0(LoggingResourceProcessor$setupLoggingRuntimeInit33.zig:59)
>         at io.quarkus.deployment.steps.LoggingResourceProcessor$setupLoggingRuntimeInit33.deploy(LoggingResourceProcessor$setupLoggingRuntimeInit33.zig:78)
>         at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:57)
>         at io.quarkus.runtime.Application.start(Application.java:94)
>         at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:143)
>         at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:177)
>         at io.quarkus.dev.DevModeMain.restartApp(DevModeMain.java:207)
>         at io.quarkus.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:134)
>         at io.quarkus.vertx.http.deployment.devmode.VertxHotReplacementSetup$1.handle(VertxHotReplacementSetup.java:51)
>         at io.quarkus.vertx.http.deployment.devmode.VertxHotReplacementSetup$1.handle(VertxHotReplacementSetup.java:43)
>         at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
>         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
>         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
>         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
>         at java.base/java.lang.Thread.run(Thread.java:834)
> 10:48:55 INFO  [io.quarkus] Quarkus 1.0.0.CR1 started in 0.260s. Listening on: http://0.0.0.0:8092
> 10:48:55 INFO  [io.quarkus] Profile dev activated. Live Coding activated.
> 10:48:55 INFO  [io.quarkus] Installed features: [cdi, rest-client, resteasy, resteasy-jsonb]
> 10:48:55 INFO  [io.quarkus.dev] Hot replace total time: 0.295s

**To Reproduce**
1.  deploy the app
2. change some thing relevant

**Configuration**
```properties
quarkus.log.file.enable=true
quarkus.log.file.path=log/dataprocessor.log
quarkus.log.file.level=TRACE
quarkus.log.file.format=%d{HH:mm:ss} %-5p [%c{2.}]] (%t) %s%e%n
quarkus.log.file.rotation.max-file-size=1024
quarkus.log.file.rotation.file-suffix=.yyyy-MM-dd
```

**Environment (please complete the following information):**
 - Output of `java -version`: 11, project based on 8
 - Quarkus version: 1.0.0.CR1
 - OS: Windows 10

### PR DESCRIPTION
**Pull request by machi1990**
I noticed that the handlers were never closed while trying to figure out the causes for
https://github.com/quarkusio/quarkus/issues/5522.

Fixes https://github.com/quarkusio/quarkus/issues/5522

### CODE REVIEW

**Review by gsmet — APPROVED** [review]
Makes sense to me but let's have @dmlloyd check it.

File: core/runtime/src/main/java/io/quarkus/runtime/Timing.java [hunk 1]
```diff
@@ -79,6 +81,10 @@ public static void printStopTime(String name) {
                 (UNSET_VALUE.equals(name) || name == null || name.trim().isEmpty()) ? "Quarkus" : name,
                 secondsRepresentation);
         bootStopTime = -1;
+        /**
+         * We can safely close log handlers after stop time has been printed.
+         */
+        InitialConfigurator.DELAYED_HANDLER.close();
```
Comment (dmlloyd) [inline core/runtime/src/main/java/io/quarkus/runtime/Timing.java]: I would instead do something like:

```java
for (Handler h : InitialConfigurator.DELAYED_HANDLER.clearHandlers()) {
    try {
        h.close();
    } catch (Throwable ignored) {
    }
}
```

This way a subsequent dev mode iteration is more likely to work correctly.

**Review by dmlloyd — CHANGES_REQUESTED** [review]

File: core/runtime/src/main/java/io/quarkus/runtime/Timing.java (hunk 1 above)
Comment (machi1990) [reply core/runtime/src/main/java/io/quarkus/runtime/Timing.java]: Okay, thanks for the feedback David. Let me do the change.

**Review by dmlloyd — APPROVED** [review]

**Comment by dmlloyd** [comment]
Just waiting for CI now.

**Comment by gastaldi** [comment]
I tested in my Windows 10 VM and I still see the error. It seems to be a bug in JBoss Logging ? (I managed to reproduce it by reducing the `quarkus.log.file.rotation.max-file-size`):
```
2019-11-18 10:58:48,064 ERROR [null] (main) Failed to publish log record (GENERIC_FAILURE[0]): Failed to move file log\dataprocessor.log to log\dataprocessor.log.2019-11-18.1.: java.nio.file.FileSystemException: log\dataprocessor.log -> log\dataprocessor.log.2019-11-18.1: O arquivo já está sendo usado por outro processo.

        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
        at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387)
        at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
        at java.nio.file.Files.move(Files.java:1395)
        at org.jboss.logmanager.handlers.SuffixRotator.move(SuffixRotator.java:239)
        at org.jboss.logmanager.handlers.SuffixRotator.rotate(SuffixRotator.java:167)
        at org.jboss.logmanager.handlers.SuffixRotator.rotate(SuffixRotator.java:226)
        at org.jboss.logmanager.handlers.PeriodicSizeRotatingFileHandler.setFile(PeriodicSizeRotatingFileHandler.java:154)
        at org.jboss.logmanager.handlers.PeriodicSizeRotatingFileHandler.preWrite(PeriodicSizeRotatingFileHandler.java:224)
        at org.jboss.logmanager.handlers.WriterHandler.doPublish(WriterHandler.java:57)
        at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:66)
        at org.jboss.logmanager.handlers.DelayedHandler.publishToChildren(DelayedHandler.java:208)
        at org.jboss.logmanager.handlers.DelayedHandler.doPublish(DelayedHandler.java:49)
        at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:66)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:316)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:324)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:324)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:324)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:324)
        at org.jboss.logmanager.Logger.logRaw(Logger.java:748)
        at org.jboss.logmanager.Logger.log(Logger.java:706)
        at org.jboss.logmanager.Logger.log(Logger.java:719)
        at org.jboss.logging.JBossLogManagerLogger.doLog(JBossLogManagerLogger.java:42)
        at org.jboss.logging.Logger.error(Logger.java:1507)
        at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:200)
        at io.quarkus.dev.DevModeMain.start(DevModeMain.java:95)
        at io.quarkus.dev.DevModeMain.main(DevModeMain.java:66)
```

**Comment by dmlloyd** [comment]
I guess we must be missing this recent commit: https://github.com/jboss-logging/jboss-logmanager/commit/f2e0eb3da1c15add1f69c32cacd55dbc3023a3d2

**Comment by dmlloyd** [comment]
I'll cherry-pick it and prep a release to go along with this change.

**Comment by gastaldi** [comment]
Stupid question, but isn't it easier to bump Quarkus to JBoss Logging 2.1.14.Final?

**Comment by dmlloyd** [comment]
No, this bug is in the JBoss LogManager, not in the logging API.  We have a fork of the JBoss LogManager with changes to support embedded bootstrapping that has to be brought up to date.

Before you ask, yes, I am working on upstreaming the changes so that we can go back to the upstream LogManager code at some point.

**Comment by gastaldi** [comment]
Awesome, I corrected my comment above after I realized it's JBoss Logmanager. Thanks!

**Comment by dmlloyd** [comment]
I've released `jboss-logmanager-embedded` version 1.0.4 with three rotation-related bug fixes picked from upstream.  It should be up on central within 24 hours; feel free to update this PR with the updated version once it appears.

**Comment by gastaldi** [comment]
@machi1990 let me know when the PR is updated so I can test the changes in my Windows VM :wink:

**Comment by machi1990** [comment]
Thanks @dmlloyd @gastaldi I'll update the PR once `jboss-logmanager-embedded` is on central.

**Comment by gsmet** [comment]
@machi1990 just FYI, better refresh this page than rely on the various Maven Central UIs (they are lagging a bit): https://repo1.maven.org/maven2/org/jboss/logmanager/jboss-logmanager-embedded/

**Comment by machi1990** [comment]
Thanks for the heads up @gsmet

**Comment by gastaldi** [comment]
@machi1990 You can also use https://www.artifact-listener.org/ to receive library updates in your e-mail or (as I do) use bash to do that for you :wink:   https://gist.github.com/gastaldi/41bd76a2b539711a81943e3ff8254b1b

**Comment by machi1990** [comment]
> @machi1990 You can also use https://www.artifact-listener.org/ to receive library updates in your e-mail or (as I do) use bash to do that for you 😉 https://gist.github.com/gastaldi/41bd76a2b539711a81943e3ff8254b1b

Okay, this is super handy. Bookmarked. Thanks @gastaldi :-)

**Comment by gsmet** [comment]
Artifact Listener is updated at ~2:30pm Paris time every day so you have a delay too. I would know it, I created the project :).

**Comment by machi1990** [comment]
I have updated the PR with the log manager update. CI should fail, until we have `jboss-logmanager-embedded` in central. I did this for convenience, this way I would just have to re-launch CI.

**Comment by machi1990** [comment]
https://repo1.maven.org/maven2/org/jboss/logmanager/jboss-logmanager-embedded/ is up to date and version 1.0.4 is available. Asked for a CI re-run. Let's wait and see. 

FYI @gsmet

**Comment by machi1990** [comment]
CI green, let's merge this. @gsmet @dmlloyd

**Comment by machi1990** [comment]
> @machi1990 let me know when the PR is updated so I can test the changes in my Windows VM 😉

@gastaldi  you wanted to test this. 

Also @mcrose confirmed that this fixed the issue for him https://github.com/quarkusio/quarkus/issues/5522#issuecomment-555096982

**Comment by machi1990** [comment]
Thanks @gsmet
