### PR TITLE
ArC - introduce immutable bean archive index

### LINKED ISSUE #29575: Unexpected beans added to the index and affecting restarting the application
### Describe the bug

I did not manage to come up with a reproducer using a regular Quarkus application. But the issue happens if you try out this branch https://github.com/pedroigor/keycloak/tree/tmp-reactive.

That branch is about switching from Resteasy Classic to Reactive in Keycloak. The issue does not happen if using Resteasy Classic and I'm not sure what is the relation, if any.

Basically, when reloading the application in dev mode or when running tests using the `QuarkusMainTestExtension`, reloading the application fails with this error:

```
org.junit.jupiter.api.extension.ParameterResolutionException: Failed to resolve parameter [io.quarkus.test.junit.main.LaunchResult arg0] in method [void org.keycloak.it.cli.StartCommandTest.testHttpEnabled(io.quarkus.test.junit.main.LaunchResult)]: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
    [error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: Found 8 deployment problems: 
[1] Ambiguous dependencies for type javax.transaction.TransactionManager and qualifiers [@Default]
    - java member: io.quarkus.agroal.runtime.DataSources():transactionManager
    - declared on CLASS bean [types=[io.quarkus.agroal.runtime.DataSources, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkus.agroal.runtime.DataSources]
    - available beans:
        - CLASS bean [types=[java.io.Serializable, javax.transaction.TransactionManager, com.arjuna.ats.jta.cdi.NarayanaTransactionManager, com.arjuna.ats.jta.cdi.DelegatingTransactionManager, java.lang.Object], qualifiers=[@Default, @Any], target=com.arjuna.ats.jta.cdi.NarayanaTransactionManager]
        - CLASS bean [types=[javax.transaction.TransactionManager, java.io.Serializable, io.quarkus.narayana.jta.runtime.CDIDelegatingTransactionManager, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkus.narayana.jta.runtime.CDIDelegatingTransactionManager]
```

The first start of the application works fine and only `CDIDelegatingTransactionManager` is available to resolve `TransactionManager` bean types. However, reloading the application causes the 
`com.arjuna.ats.jta.cdi.NarayanaTransactionManager` to also be recognized as a potential resolver hence failing with that error.

If we remove the `com.arjuna.ats.jta.cdi.NarayanaTransactionManager` at build time from our extension, the issue does not happen:

```
buildTimeConditionBuildItemBuildProducer.produce(new BuildTimeConditionBuildItem(index.getIndex().getClassByName(DotName.createSimple("com.arjuna.ats.jta.cdi.NarayanaTransactionManager")), false));`
```

### Expected behavior

Being able to reload the application without introducing beans that otherwise should be excluded.

### Actual behavior

Failing to reload the application as per the description.

### How to Reproduce?

* Checkout this branch https://github.com/pedroigor/keycloak/tree/tmp-reactive-bean-issue
* mvn -Pdistribution -DskipTests clean install
* cd quarkus/server
* mvn quarkus:dev -Dquarkus.args=start-dev
* After starting Keycloak in dev mode, force a restart (type `s`)

### Output of `uname -a` or `ver`

Linux fedora 6.0.9-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Nov 16 17:50:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "18.0.2.1" 2022-08-18 OpenJDK Runtime Environment (build 18.0.2.1+1-1) OpenJDK 64-Bit Server VM (build 18.0.2.1+1-1, mixed mode, sharing)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.14.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mkouba**
- this is index is mandatory and is used to discover beans
- the computing index is optional and can be used for other tasks, e.g. during type-safe resolution
- if the computing index is not present the immutable index is used instead
- fixes #29575

### CODE REVIEW

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanProcessor.java [hunk 1]
```diff
@@ -91,15 +91,17 @@ private BeanProcessor(Builder builder) {
         this.applicationClassPredicate = builder.applicationClassPredicate;
         this.name = builder.name;
         this.output = builder.output;
-        this.annotationLiterals = new AnnotationLiteralProcessor(builder.beanArchiveIndex, applicationClassPredicate);
+        this.annotationLiterals = new AnnotationLiteralProcessor(builder.beanArchiveComputingIndex, applicationClassPredicate);
```
Comment (Ladicek) [inline independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanProcessor.java:94]: I don't think `AnnotationLiteralProcessor` can deal with a `null` index.

**Comment by Ladicek** [comment]
Interesting approach, but makes sense. I guess the intent is that the computing index should be used most of the time (or fallback to the immutable one if the computing doesn't exist), but there are certain occasions where the immutable index must be used unconditionally? It would be nice to have a little more detailed explanation of when the 2nd condition occurs.

Aside: I _so_ wish we had a complete index of everything (both the Quarkus combined index and the ArC bean archive index) so that we don't have to do on-demand indexing at all...

**Comment by mkouba** [comment]
> It would be nice to have a little more detailed explanation of when the 2nd condition occurs.

Yes, well it's described [here](https://github.com/quarkusio/quarkus/pull/29641/files#diff-c9b2b8f7f82a42a3270b51243922c82ca8e6617e554a67788a60ac8381701391R528) and [here](https://github.com/quarkusio/quarkus/pull/29641/files#diff-c9b2b8f7f82a42a3270b51243922c82ca8e6617e554a67788a60ac8381701391R516) but I can try to add more description to the `BeanArchiveIndexBuildItem`.

 > Aside: I so wish we had a complete index of everything (both the Quarkus combined index and the ArC bean archive index) so that we don't have to do on-demand indexing at all...

That would be nice but in that case we would have index the whole classpath (including jdk classes) which is probably unrealistic.

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanProcessor.java (hunk 1 above)
Comment (mkouba) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanProcessor.java:94]: Good catch!

**Review by stuartwdouglas — APPROVED** [review]

**Comment by Ladicek** [comment]
> > It would be nice to have a little more detailed explanation of when the 2nd condition occurs.
> 
> Yes, well it's described [here](https://github.com/quarkusio/quarkus/pull/29641/files#diff-c9b2b8f7f82a42a3270b51243922c82ca8e6617e554a67788a60ac8381701391R528) and [here](https://github.com/quarkusio/quarkus/pull/29641/files#diff-c9b2b8f7f82a42a3270b51243922c82ca8e6617e554a67788a60ac8381701391R516) but I can try to add more description to the `BeanArchiveIndexBuildItem`.

Those are exactly the descriptions that should be more detailed in my opinion. I mean, as ArC contributor, how do I know which index should I use? The optional one most of the time, _probably_, but I'm not really sure :-)

> > Aside: I so wish we had a complete index of everything (both the Quarkus combined index and the ArC bean archive index) so that we don't have to do on-demand indexing at all...
> 
> That would be nice but in that case we would have index the whole classpath (including jdk classes) which is probably unrealistic.

It wouldn't have to be the _entire_ JDK, we'd just have to index the transitive closure of the application classes. I didn't try, so I don't know how crazy that would eventually become :-)

**Comment by mkouba** [comment]
> Those are exactly the descriptions that should be more detailed in my opinion. I mean, as ArC contributor, how do I know which index should I use? The optional one most of the time, probably, but I'm not really sure :-)

And my answer would be "it depends" :-). In general, you should use the immutable index to _discover the components_ (beans, observers, etc.) - that's the case we're trying to fix with this PR - and the computing index for any other stuff. That's why we return the computing index from the `BeanDeployment.getBeanArchiveIndex()`.

We should also clarify that the computing index is built on top of the immutable index, i.e. only classes that are not part of the immutable index can be computed.

**Comment by Ladicek** [comment]
Okay, so basically type discovery should use the immutable index, and bean discovery should use the computing index? Or something like that.

> We should also clarify that the computing index is built on top of the immutable index, i.e. only classes that are not part of the immutable index can be computed.

Great point. The `BeanProcessor` builder currently has 2 setters, so we rely on its caller to maintain this invariant. I guess we can't really build the computing index internally and have to obtain it from the outside?

**Review by Ladicek — APPROVED** [review]

**Review by manovotn — APPROVED** [review]
