### PR TITLE
Fix trustStore handling in native-image

### LINKED ISSUE #9713: Adding a self-signed certificate to keystore and setting `-Djavax.net.ssl.trustStore` gives PKIX path building failed message
**Describe the bug**

I have a quarkus native executable that needs to communicate with an endpoint secured with a self signed certificate.  When building a container for this, I add my self-signed cert to the trust store and attempt to run the application.

**Expected behavior**

My executable should see that the self-signed certificate is available in the trust store and use it for communication.

**Actual behavior**

Fails to find a valid certification path to the target.

**To Reproduce**

Given a dockerfile similar to this:

```Dockerfile
FROM quay.io/quarkus/centos-quarkus-maven:19.3.1-java11 AS build
RUN mkdir -p /tmp/ssl \    
  && cp /opt/graalvm/lib/security/cacerts /tmp/ssl
COPY custom-cert.crt /tmp/ssl
RUN keytool -import -alias self-signed -noprompt -storepass changeit -file /tmp/ssl/custom-cert.crt -keystore /tmp/ssl/cacerts
COPY . /usr/src/app/
RUN mvn --settings /usr/src/app/settings.xml -f /usr/src/app/pom.xml -Pnative clean package                                                                                                                                                                                                                                                                                                                                                                 

FROM registry.access.redhat.com/ubi8/ubi-minimal
WORKDIR /work/                                                                                                                                                                                                                              
COPY --from=build /usr/src/app/target/*-runner /work/application
COPY --from=build /tmp/ssl/ /work
RUN chmod 775 /work /work/application \
        && chown -R 1001 /work \
        && chmod -R "g+rwX" /work \
        && chown -R 1001:root /work
EXPOSE 8080
USER 1001                                                                                                                                                                                                                                              
CMD ["./application", "-Dquarkus.http.host=0.0.0.0", "-Djavax.net.ssl.trustStore=/work/cacerts"]
```

And an endpoint secured with a self-signed certificate, when the client code attempts to make a connection, you should see PKIX path building failed messages:

```
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:320)
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:263)
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:258)
        at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:641)
        at sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:460)
        at sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:360)
        at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
        at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
        at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:421)
        at sun.security.ssl.TransportContext.dispatch(TransportContext.java:177)
        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
        at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1151)
        at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1062)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334)
        at org.eclipse.che.api.core.rest.DefaultHttpJsonRequest.doRequest(DefaultHttpJsonRequest.java:250)
        at org.eclipse.che.api.core.rest.DefaultHttpJsonRequest.request(DefaultHttpJsonRequest.java:164)
        at org.eclipse.che.incubator.workspace.telemetry.base.AbstractAnalyticsManager.getWorkspace(AbstractAnalyticsManager.java:156)
        ... 27 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:385)
        at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:290)
        at sun.security.validator.Validator.validate(Validator.java:264)
        at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:222)
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
        at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:625)
        ... 46 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
        at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
        at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:380)
        ... 52 more

```

**Configuration**
```properties
# Add your application.properties here, if applicable.
quarkus.ssl.native=true
```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: 
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 

**Additional context**
(Add any other context about the problem here.)

### PR DESCRIPTION
**Pull request by geoand**
Closes: #9713 

This is a draft for now since there is a lot more that needs to be done (our handling of the trustStore seems to be at odds with what GraalVM native-image does).

### CODE REVIEW

**Comment by geoand** [comment]
Ah.. the new test fails because of Docker... I need to see if / how this can be fixed

**Comment by geoand** [comment]
The test actually uncovered an issue that was fixed :sunglasses:

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java [hunk 1]
```diff
@@ -359,6 +365,40 @@ public NativeImageBuildItem build(NativeConfig nativeConfig, NativeImageSourceJa
...
 
+    private void handleAdditionalProperties(NativeConfig nativeConfig, List<String> command, boolean isContainerBuild,
+            Path outputDir) {
+        if (nativeConfig.additionalBuildArgs.isPresent()) {
+            List<String> strings = nativeConfig.additionalBuildArgs.get();
+            for (String buildArg : strings) {
+                String trimmedBuildArg = buildArg.trim();
+                if (trimmedBuildArg.contains(TRUST_STORE_SYSTEM_PROPERTY_MARKER) && isContainerBuild) {
+                    /*
+                     * When the native binary is being built with a docker container, because a volume is create,
```
Comment (gsmet) [inline core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java:376]:
```suggestion
                     * When the native binary is being built with a docker container, because a volume is created,
```

File: docs/src/main/asciidoc/native-and-ssl.adoc [hunk 2]
```diff
@@ -161,71 +161,36 @@ And let's build the native executable again:
...
+The easiest way to do so is by setting `quarkus.native.additional-build-args`. For example:
 
-To make it work, you need to manually set `javax.net.ssl.trustStore` to point to the new GraalVM home:
 ```
-./target/rest-client-1.0-SNAPSHOT-runner -Djavax.net.ssl.trustStore=<new-graalvm-home>/jre/lib/security/cacerts
+quarkus.native.additional-build-args=-J-Djavax.net.ssl.trustStore=/tmp/mycerts,-J-Djavax.net.ssl.trustStorePassword=changeit
 ```
 
-Now, the application should work as expected:
+will ensure that the contents of `/tmp/mycerts` are baked into the native binary and used *in addition* to the default cacerts.
```
Comment (gsmet) [inline docs/src/main/asciidoc/native-and-ssl.adoc:183]:
```suggestion
will ensure that the certificates of `/tmp/mycerts` are baked into the native binary and used *in addition* to the default cacerts.
```
?

File: docs/src/main/asciidoc/native-and-ssl.adoc [hunk 3]
```diff
@@ -161,71 +161,36 @@ And let's build the native executable again:
...
+[IMPORTANT]
 ====
-The root certificates file of GraalVM might not be totally up to date.
-If you have issues with some certificates, your best bet is to include the `cacerts` file of a regular JDK instead.
-====
-
-[WARNING]
-====
-Don't forget to move your GraalVM directory back to where it was.
+The file containing the custom TrustStore does *not* have to be present at runtime as its contents have been baked into the native binary.
```
Comment (gsmet) [inline docs/src/main/asciidoc/native-and-ssl.adoc:187]:
```suggestion
The file containing the custom TrustStore does *not* have to be present at runtime as its content has been baked into the native binary.
```

File: docs/src/main/asciidoc/native-and-ssl.adoc [hunk 4]
```diff
@@ -161,71 +161,36 @@ And let's build the native executable again:
...
-  && chmod -R "g+rwX" /work \
-  && chown -R 1001:root /work
-
-EXPOSE 8080
-USER 1001
-
-CMD ["./application", "-Dquarkus.http.host=0.0.0.0", "-Djavax.net.ssl.trustStore=/work/cacerts"]
-----
+No special action needs to be taken when running the native binary in a container. If the native binary was properly built with the custom TrustStore
+as described in the previous section, it will properly in container as well.
```
Comment (gsmet) [inline docs/src/main/asciidoc/native-and-ssl.adoc:193]: > it will properly in container as well

Looks like some word is missing here? Or maybe not but the meaning is not exactly obvious when you read it.

**Review by gsmet — COMMENTED** [review]
Thanks a lot for this work. I spotted a few doc issues, nothing major.

File: docs/src/main/asciidoc/native-and-ssl.adoc (hunk 4 above)
Comment (geoand) [reply docs/src/main/asciidoc/native-and-ssl.adoc]: Of course I was missing the verb :)

**Comment by geoand** [comment]
> Thanks a lot for this work. I spotted a few doc issues, nothing major.

Thanks for the thorough review! The comments have been addressed

**Review by gsmet — APPROVED** [review]

**Comment by geoand** [comment]
@gsmet this isn't a notable feature, but I think that it should be mentioned in the release somehow, WDYT?

**Comment by gsmet** [comment]
Agreed, I had the same idea.
