### PR TITLE
Maven Resolver: initialize Maven properly, especially the local repository

### LINKED ISSUE #44484: Quarkus Build with Maven Artefact Resolver Configuration Options
### Describe the bug

We use Maven with the quarkus-maven-plugin to build Quarkus applications on our CI system.

To improve caching, we attempted to use the enhanced local repository management (LRM) feature by separating the local repository for snapshots and releases (see [Maven Local Repository Documentation](https://maven.apache.org/resolver-archives/resolver-LATEST-1.x/local-repository.html)).

Following the configuration guide [here](https://maven.apache.org/resolver-archives/resolver-LATEST-1.x/configuration.html), we specified the following properties in the settings.xml:

````
<settings ...>
...
    <profiles>
	<profile>
            <id>split-repository</id>
            <properties>
                <aether.enhancedLocalRepository.split>true</aether.enhancedLocalRepository.split>
                <aether.enhancedLocalRepository.splitLocal>true</aether.enhancedLocalRepository.splitLocal>
                <aether.enhancedLocalRepository.splitRemote>true</aether.enhancedLocalRepository.splitRemote>
            </properties>
        </profile>
    </profiles>
    <activeProfiles>
        <activeProfile>split-repository</activeProfile>
    </activeProfiles>
</settings>
````

### Expected behavior

The quarkus-maven-plugin or quarkus-maven-resolver should support all Maven artifact resolver options as outlined in [this documentation](https://maven.apache.org/resolver-archives/resolver-LATEST/configuration.html).

### Actual behavior

For most of the build process, this configuration works as expected, with artifacts resolving to either ~/.m2/repository/cached/releases or ~/.m2/repository/cached/snapshots.

However, during the quarkus:3.8.6:generate-code-tests phase, the build starts resolving all dependencies again under ~/.m2/repository/. We also attempted unsuccessfully to set these options in a .mvn/.jvm.config file in the project root.

Could you confirm if the quarkus-maven-plugin or quarkus-maven-resolver fully supports all Maven artifact resolver options?

### How to Reproduce?

To reproduce this issue:

1. Configure Maven's settings.xml as shown above to split the local repository for snapshots and releases.
2. Add a sample Quarkus project with the quarkus-maven-plugin in the pom.xml, using version 3.8.6 or 3.15.1.
3. delete ~/.m2/repository/
4. Run the build command:
mvn clean install

Observe that during the generate-code-tests phase, dependencies are unexpectedly resolved under ~/.m2/repository/ instead of the configured split directories.

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Ladicek**
The `BootstrapMavenContext.newRepositorySystemSession()` method is now a lot closer to `DefaultRepositorySystemSessionFactory.newRepositorySession()`, especially around how it initializes the `LocalRepositoryManager`. It is now done _after_ setting up the config properties on the `RepositorySystemSession`, which has also been fixed (to include the properties of all active profiles, including those in `settings.xml`).

Furhter, this commit renames 2 files to match the name of the (non-`public`) class declared in them, and fixes self type emulation in `BootstrapMavenContextConfig`.

Fixes #44484

### CODE REVIEW

File: independent-projects/bootstrap/maven-resolver/src/main/java/io/quarkus/bootstrap/resolver/maven/BootstrapMavenContext.java [hunk 1]
```diff
@@ -488,33 +488,28 @@ private File resolveSettingsFile(String settingsArg, String alternatePomDir, Str
...
-            final List<LocalRepositoryManager> tail = new ArrayList<>(localRepoTailPaths.length);
-            for (final String tailPath : localRepoTailPaths) {
-                tail.add(getRepositorySystem().newLocalRepositoryManager(session, new LocalRepository(tailPath)));
-            }
-            session.setLocalRepositoryManager(
-                    new ChainedLocalRepositoryManager(head, tail, getLocalRepoTailIgnoreAvailability()));
+        Map<Object, Object> configProps = new LinkedHashMap<>();
+        configProps.put(ConfigurationProperties.USER_AGENT, getUserAgent());
+        configProps.put(ConfigurationProperties.INTERACTIVE, settings.isInteractiveMode());
+        configProps.put("maven.startTime", new Date());
```
Comment (aloubyansky) [inline independent-projects/bootstrap/maven-resolver/src/main/java/io/quarkus/bootstrap/resolver/maven/BootstrapMavenContext.java:501]: Not sure we need this one.

**Review by aloubyansky — APPROVED** [review]
Great work @Ladicek Thanks a lot!

File: independent-projects/bootstrap/maven-resolver/src/main/java/io/quarkus/bootstrap/resolver/maven/BootstrapMavenContext.java (hunk 1 above)
Comment (Ladicek) [reply independent-projects/bootstrap/maven-resolver/src/main/java/io/quarkus/bootstrap/resolver/maven/BootstrapMavenContext.java:501]: Yeah, we probably don't. I copied this from MIMA, because in Maven proper, the `maven.startTime` comes from the Maven startup request (not sure about the name), which we obviously don't have. But I can remove it if you wish.

Comment (aloubyansky) [reply independent-projects/bootstrap/maven-resolver/src/main/java/io/quarkus/bootstrap/resolver/maven/BootstrapMavenContext.java:501]: I'd probably remove it but it's not critical. We can do that later.

Comment (Ladicek) [reply independent-projects/bootstrap/maven-resolver/src/main/java/io/quarkus/bootstrap/resolver/maven/BootstrapMavenContext.java]: Removed.
