### PR TITLE
Ensure that ObjectMapperCustomizer impls are used in runtime init

### LINKED ISSUE #32969: ObjectMapperCustomizer only evaluated at build time if resteasy-reactive-jackson or rest-client-reactive-jackson present
### Describe the bug

I would like to customize my object mapper depending on a configproperty. When I use the `quarkus-jackson` dependency it all works well, but if I use or `quarkus-resteasy-reactive-jackson` or `quarkus-rest-client-reactive-jackson` , it then make it evaluated only at build time using native, and it does not execute while running the app anymore.

The only workaround I found is to have a basic singleton `@Startup` bean that re-customizes the Objectmapper.

### Expected behavior

ObjectMapperCustomizer should run at runtime event it it ran at buildtime so it can work with configproperty/configmapping.

via logs it should look like this at compile time;
[2/7] Performing analysis...  [*******]

and running the app; 
```
MY_VARIABLE=prod ./target/jackson-customize-issue-1.0.0-SNAPSHOT-runner
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2023-04-27 15:55:48,906 INFO  [org.acm.RegisterCustomModuleCustomizer] (main) Customizing objectMapper for prod
```

### Actual behavior

ObjectMapper gets customized at buildtime only;

grallvm build;

`[2/7] Performing analysis...  [15:44:59,592 INFO  [org.acm.RegisterCustomModuleCustomizer] Customizing objectMapper for default`

app log;
nothing gets logged from the customizer

### How to Reproduce?

Reproduce: https://github.com/manofthepeace/quarkus-jackson-buildtime-issue

Steps to reproduce
1. mvn clean package -Pnative
2. ./target/jackson-customize-issue-1.0.0-SNAPSHOT-runner (should print default at runtime)
3.  MY_VARIABLE=prod ./target/jackson-customize-issue-1.0.0-SNAPSHOT-runner (should print prod at runtime)
4. Modify the pom.xml, remove the quarkus-jackson dependency and uncomment one or both of the resteasy-reactive ones
5. recompile via mvn clean package -Pnative
6. observes the log at build time during the graalvm processing phase
7. rerun step 2 and 3, will not print, and default is always actually used

### Output of `uname -a` or `ver`

Darwin Kernel Version 21.6.0

### Output of `java -version`

OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7)

### GraalVM version (if different from Java)

21.3.1

### Quarkus version or git rev

2.16.6

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.7

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #32969

### CODE REVIEW

File: extensions/resteasy-reactive/rest-client-reactive-jackson/deployment/src/main/java/io/quarkus/rest/client/reactive/jackson/deployment/RestClientReactiveJacksonProcessor.java [hunk 1]
```diff
@@ -37,6 +38,12 @@ void feature(BuildProducer<FeatureBuildItem> features) {
         features.produce(new FeatureBuildItem(REST_CLIENT_REACTIVE_JACKSON));
     }
 
+    @BuildStep
+    void nativeSupport(BuildProducer<RuntimeReinitializedClassBuildItem> runtimeReinitializedClassProducer) {
+        runtimeReinitializedClassProducer
+                .produce(new RuntimeReinitializedClassBuildItem(io.vertx.core.json.Json.class.getName()));
```
Comment (Sgitario) [inline extensions/resteasy-reactive/rest-client-reactive-jackson/deployment/src/main/java/io/quarkus/rest/client/reactive/jackson/deployment/RestClientReactiveJacksonProcessor.java:44]: I had no idea about `RuntimeReinitializedClassBuildItem`.
What I don't see and would like to understand is why using `io.vertx.core.json.Json.class.getName()` causes that the custom object mapper customisers to be re-init? since I think the object mapper has nothing to do with Vert.x Json :/

**Review by Sgitario — APPROVED** [review]
The changes look good to me as long as the new test works.
I have only one question, but this is for my curiosity only :)

File: extensions/resteasy-reactive/rest-client-reactive-jackson/deployment/src/main/java/io/quarkus/rest/client/reactive/jackson/deployment/RestClientReactiveJacksonProcessor.java (hunk 1 above)
Comment (geoand) [reply extensions/resteasy-reactive/rest-client-reactive-jackson/deployment/src/main/java/io/quarkus/rest/client/reactive/jackson/deployment/RestClientReactiveJacksonProcessor.java:44]: `io.vertx.core.json.Json` uses Jackson under the hood. The reason ObjectMapper comes into play in native-image build time is because `io.vertx.core.json.Json` has a static field that looks up a `JsonCodec` that is backed by Jackson.

I was  able to find the root cause (`Json` class) is because I tried `RuntimeReinitializedClassBuildItem` on `ObjectMapperCustomizer` which failed (and the cause of failure could be found using `quarkus.native.additional-build-args=--trace-object-instantiation=org.acme.RegisterCustomModuleCustomizer`)

Comment (Sgitario) [reply extensions/resteasy-reactive/rest-client-reactive-jackson/deployment/src/main/java/io/quarkus/rest/client/reactive/jackson/deployment/RestClientReactiveJacksonProcessor.java:44]: I see, many thanks for the clarification!

Comment (geoand) [reply extensions/resteasy-reactive/rest-client-reactive-jackson/deployment/src/main/java/io/quarkus/rest/client/reactive/jackson/deployment/RestClientReactiveJacksonProcessor.java:44]: 👍🏼

**Comment by geoand** [comment]
The failure **is** related and I'm looking into it.

**Comment by geoand** [comment]
Should be good now
