### PR TITLE
Redis Client: fix *SCAN cursor handling

### LINKED ISSUE #49492: Redis SCAN cursor exceeds Long.MAX_VALUE resulting in NumberFormatException
### Describe the bug

I'm using AWS ElastiCache (Valkey) serverless, and ran into a `NumberFormatException` with the `ReactiveRedisDataSource` when trying to do a `SCAN`. The cursor returned by Redis/Valkey after the SCAN operation is greater than `Long.MAX_VALUE` (this is in line with the [redis documentation](https://redis.io/docs/latest/commands/scan/#return-information) which says that the cursor is a uint_64). But `ScanReactiveCursorImpl` which is used by `ReactiveRedisDataSourceImpl` tries to parse the cursor it receives from Redis to a long value.

Similar issue as https://github.com/spring-projects/spring-data-redis/issues/2796

### Expected behavior

Given that the data in Redis looks like this

```
> SCAN 0
1) "9223372036854775808"
2)  1) "key1"

> SCAN 9223372036854775808
1) "0"
2) 1) "key2"
```

I would expect `reactiveRedisDataSource.key().scan().toMulti().subscribe().asStream().toList();` to return a list like `["key1", "key2"]`

### Actual behavior

I wasn't able to reproduce the issue using `ReactiveRedisDataSource` because of difficulties mocking the response from Redis. Instead I had to use the `ScanReactiveCursorImpl` directly to force the error. It throws an exception similar to this one. 
```
java.lang.NumberFormatException: For input string: "9223372036854775808"

	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Long.parseLong(Long.java:713)
	at java.base/java.lang.Long.parseLong(Long.java:832)
	at io.vertx.redis.client.Response.toLong(Response.java:143)
	at io.vertx.mutiny.redis.client.Response.toLong(Response.java:140)
	at io.quarkus.redis.runtime.datasource.ScanReactiveCursorImpl.lambda$next$0(ScanReactiveCursorImpl.java:41)
	at io.smallrye.mutiny.operators.uni.UniOnItemConsume$UniOnItemComsumeProcessor.invokeEventHandler(UniOnItemConsume.java:77)
	at io.smallrye.mutiny.operators.uni.UniOnItemConsume$UniOnItemComsumeProcessor.onItem(UniOnItemConsume.java:42)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem$KnownItemSubscription.forward(UniCreateFromKnownItem.java:38)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem.subscribe(UniCreateFromKnownItem.java:23)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:35)
	at io.smallrye.mutiny.operators.uni.UniOnItemConsume.subscribe(UniOnItemConsume.java:30)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:35)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransform.subscribe(UniOnItemTransform.java:22)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:35)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromDeferredSupplier.subscribe(UniCreateFromDeferredSupplier.java:36)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:35)
	at io.smallrye.mutiny.converters.uni.UniToMultiPublisher$UniToMultiSubscription.request(UniToMultiPublisher.java:74)
	at io.smallrye.mutiny.subscription.SwitchableSubscriptionSubscriber.setOrSwitchUpstream(SwitchableSubscriptionSubscriber.java:205)
	at io.smallrye.mutiny.subscription.SwitchableSubscriptionSubscriber.onSubscribe(SwitchableSubscriptionSubscriber.java:107)
	at io.smallrye.mutiny.converters.uni.UniToMultiPublisher.subscribe(UniToMultiPublisher.java:25)
	at io.smallrye.mutiny.groups.MultiCreate$1.subscribe(MultiCreate.java:165)
	at io.smallrye.mutiny.operators.multi.MultiRepeatWhilstOp.subscribe(MultiRepeatWhilstOp.java:29)
	at io.smallrye.mutiny.operators.AbstractMulti.subscribe(AbstractMulti.java:61)
	at io.smallrye.mutiny.operators.multi.MultiConcatMapOp.subscribe(MultiConcatMapOp.java:54)
	at io.smallrye.mutiny.operators.AbstractMulti.subscribe(AbstractMulti.java:61)
	at io.smallrye.mutiny.helpers.BlockingIterable.lambda$stream$0(BlockingIterable.java:59)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

```

### How to Reproduce?

Steps to reproduce issue:
1) Run `./mvnw test`

[redis-issue.zip](https://github.com/user-attachments/files/21743670/redis-issue.zip)

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

openjdk version "21.0.8" 2025-07-15 LTS

### Quarkus version or git rev

3.25.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.

### Additional information

It fails here https://github.com/quarkusio/quarkus/blob/main/extensions/redis-client/runtime/src/main/java/io/quarkus/redis/runtime/datasource/ScanReactiveCursorImpl.java#L41 because the cursor can be bigger than Long.MAX_VALUE

https://github.com/quarkusio/quarkus/blob/main/extensions/redis-client/runtime/src/main/java/io/quarkus/redis/runtime/datasource/ReactiveRedisDataSourceImpl.java#L264
https://github.com/quarkusio/quarkus/blob/main/extensions/redis-client/runtime/src/main/java/io/quarkus/redis/runtime/datasource/ReactiveKeyCommandsImpl.java#L211
https://github.com/quarkusio/quarkus/blob/main/extensions/redis-client/runtime/src/main/java/io/quarkus/redis/runtime/datasource/ScanReactiveCursorImpl.java#L48
https://github.com/quarkusio/quarkus/blob/main/extensions/redis-client/runtime/src/main/java/io/quarkus/redis/runtime/datasource/ScanReactiveCursorImpl.java#L41

### PR DESCRIPTION
**Pull request by Ladicek**
`*SCAN` cursors in Redis are strings that contain _unsigned_ 64-bit integers. Until this commit, we ignored that and treated cursors as _signed_ integers, which may lead to an exception when parsing the number. Further, this allowed us to devise a sentinel value, `-1`, to mark the "not yet started" situation.

Since this commit, we parse and serialize cursors as unsigned integers. This disallows using -1 as a special value, so we add a special flag `initial` to mark the "not yet started" situation instead.

This commit also deprecates (for removal) the access to cursor values. This is specifically:

- `Cursor.INITIAL_CURSOR_ID`
- `Cursor.cursorId()`
- `ReactiveCursor.INITIAL_CURSOR_ID`
- `ReactiveCursor.cursorId()`

The `INITIAL_CURSOR_ID` value used to be `-1`, which is incorrect. The initial _and_ final value of a cursor is always `0`.

The `cursorId()` returns the cursor value as `long`, which makes it super easy to treat it as a signed integer, which is wrong.

We would be able to add a `cursor()`/`cursorValue()`/`cursorString()` method that returns the cursor value as a `String`, but I'm not sure there's any actual need for access to the underlying value, so I'm refraining from this for now.

Fixes #49492

### CODE REVIEW

**Comment by Ladicek** [comment]
I'm not sure who can review since @cescoffier is on PTO. I'm also not sure what the correct `since` value is for deprecation -- I added 3.28 for now, but I guess we might want to backport this commit (to 3.26 or 3.27).

Other than that, this PR should be complete, so I'd welcome any help with the above :-)

File: extensions/redis-client/runtime/src/main/java/io/quarkus/redis/datasource/Cursor.java [hunk 1]
```diff
@@ -4,12 +4,24 @@ public interface Cursor<T> {
...
      */
+    @Deprecated(forRemoval = true, since = "3.28")
     long INITIAL_CURSOR_ID = ReactiveCursor.INITIAL_CURSOR_ID;
 
     boolean hasNext();
 
     T next();
 
+    /**
+     * @deprecated see {@link #INITIAL_CURSOR_ID}
```
Comment (gsmet) [inline extensions/redis-client/runtime/src/main/java/io/quarkus/redis/datasource/Cursor.java:23]: I don't understand this. Shouldn't this method return the current cursor id? Why point to a constant?

FWIW, I have seen below that it's not as simple but it seems quite odd.

File: extensions/redis-client/runtime/src/main/java/io/quarkus/redis/datasource/ReactiveCursor.java [hunk 2]
```diff
@@ -6,12 +6,24 @@ public interface ReactiveCursor<T> {
...
-    long INITIAL_CURSOR_ID = -1L;
+    @Deprecated(forRemoval = true, since = "3.28")
+    long INITIAL_CURSOR_ID = 0L;
 
     boolean hasNext();
 
     Uni<T> next();
 
+    /**
+     * @deprecated see {@link #INITIAL_CURSOR_ID}
```
Comment (gsmet) [inline extensions/redis-client/runtime/src/main/java/io/quarkus/redis/datasource/ReactiveCursor.java:25]: Same question here?

**Review by gsmet — APPROVED** [review]
Looks good to me but I added a question for my education.

File: extensions/redis-client/runtime/src/main/java/io/quarkus/redis/datasource/Cursor.java (hunk 1 above)
Comment (gsmet) [reply extensions/redis-client/runtime/src/main/java/io/quarkus/redis/datasource/Cursor.java:23]: Raaaaah, I should have read the description entirely... Sorry about that!

File: extensions/redis-client/runtime/src/main/java/io/quarkus/redis/datasource/Cursor.java [hunk 3]
```diff
@@ -4,12 +4,24 @@ public interface Cursor<T> {
...
      * The cursor id when no operations have been emitted yet.
+     *
+     * @deprecated Previously, this value was -1, assuming that this value is never produced by Redis as an actual cursor.
+     *             However, Redis uses unsigned 64-bit integers as cursor values, so the assumption was wrong
+     *             (-1 as 64-bit signed integer is 0xFFFF_FFFF_FFFF_FFFF, which is the biggest unsigned 64-bit integer).
+     *             This should have never been exposed publicly and should not be relied upon.
+     *             <p>
+     *             The current value is 0, which is the correct initial <em>and</em> final cursor value in Redis.
      */
+    @Deprecated(forRemoval = true, since = "3.28")
```
Comment (gsmet) [inline extensions/redis-client/runtime/src/main/java/io/quarkus/redis/datasource/Cursor.java]: I thought about it and please make it 3.26, we will backport this one.

**Review by gsmet — CHANGES_REQUESTED** [review]

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
I adjusted the `since` to `3.26`. Thanks for the fix!
