### PR TITLE
Hibernate Validator - Allow setting the expression language feature level

### LINKED ISSUE #23838: java validation errors in graphql
### Describe the bug

I'm experiensing validation in GraphQL inputs with the Java Bean Validation API and I tried to customize message errors by using the expression language (EL) as below :

```java
@Size(value = 5, message = "{ '${validatedValue}' must be at least {value} characters long. Length found : '${validatedValue.length()}'}")
private String civility;
```
Then in the graphql playground if we added a wrong civility with an invalid charachter long, here must be at least 5 we get this message error :

```
"message": "validation failed: updateAdherent.adherent.civility : 'TESTEST' must be at least 5 characters long. Length found : '${validatedValue.length()}'
```

### Expected behavior

In the message error should be :
```
"message": "validation failed: updateAdherent.adherent.civility : 'TESTEST' must be at least 5 characters long. Length found : '7'
```

### Actual behavior

```
"message": "validation failed: updateAdherent.adherent.civility : 'TESTEST' must be at least 5 characters long. Length found : '${validatedValue.length()}'
```

### How to Reproduce?

As a reproducer  we start by the GraphQL input 
```java
import java.time.LocalDate;
import javax.json.bind.annotation.JsonbDateFormat;
import javax.validation.constraints.Email;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.Past;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Builder
@Data
@AllArgsConstructor
@NoArgsConstructor
public class CreatePersonUseCaseInput {
    @NotBlank(message="'${validatedValue}' cannot be null")
    private String name;
    @Past(message="Date must be in past. found '${validatedValue}'")
    @JsonbDateFormat(value = "dd/MM/yyyy")
    private LocalDate dateOfBirth;
    @Email(message="email should be valid")
    private String email;
  @Size(value = 5, message = "{ '${validatedValue}' must be at least {value} characters long. Length found : '${validatedValue.length()}'}")
  private String civility;
}
```

then the mutation code:
```Java
@Mutation
    @Description("create person")
    public String createPerson(@Valid @Name("person")CreatePersonUseCaseInput input) {
        /*
         * do something
         * */
        return "successful creation";
    }
```
Lastly the query in the graphql playground is
```graphql
mutation{
  createPerson(
    person:{
      name:"test"
      dateOfBirth: "12/03/2002"
      email: "test.test@gg"
      civility: "TESTEST"
    }
  )
}
```

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

 "1.8.0_265"

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.5.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by gsmet**
I only exposed the constraint one and not the custom violation one as I
think it is bad practice to globally change the custom violation one.

Fix #23838

### CODE REVIEW

File: extensions/hibernate-validator/runtime/src/main/java/io/quarkus/hibernate/validator/runtime/HibernateValidatorBuildTimeConfig.java [hunk 1]
```diff
@@ -72,4 +82,19 @@
...
+    @ConfigGroup
+    public static class HibernateValidatorExpressionLanguageBuildTimeConfig {
+
+        /**
+         * Configure the Expression Language feature level for constraints, allowing to define which
+         * Expression Language features are available for message interpolation.
+         * <p>
+         * This property only affects the EL feature level of "static" constraint violation messages. In particular, it
+         * doesn't affect the default EL feature level for custom violations. Refer to
+         * <code>custom-violation-expression-feature-level</code> to configure that.
```
Comment (yrodiere) [inline extensions/hibernate-validator/runtime/src/main/java/io/quarkus/hibernate/validator/runtime/HibernateValidatorBuildTimeConfig.java:95]: Maybe this would be clearer to the uninitiated?

Also, I think you decided against adding `custom-violation-expression-feature-level`,
so the "Refer to" part is probably no longer relevant?

```suggestion
         * This property only affects the EL feature level of "static" constraint violation messages set through the <code>message</code> attribute of constraint annotations.
         * <p>
         * In particular, it doesn't affect the default EL feature level for custom violations
         * created programmatically in validator implementations.
         * The feature level for those can only be configured directly in the validator implementation.
```

**Review by yrodiere — COMMENTED** [review]
My two cents. Looks good otherwise.

**Comment by gsmet** [comment]
@yrodiere I merged your suggestions.

**Review by yrodiere — APPROVED** [review]
I rebased and applied autoformat. LGTM!
