### PR TITLE
Vertx - Allow @ConsumeEvent methods to receive message headers

### LINKED ISSUE #21621: @ConsumeEvent can return `Uni<R>` if parameter is `T` but throws error for `Message<T>`
### Describe the bug

The ["Using the event bus" documentation](https://quarkus.io/guides/reactive-event-bus#replying) has examples of methods annotated with `@ConsumesEvent` returning `void`, `R`, and  `Uni<R>`:

```java
@ConsumeEvent("greeting")
public String consume(String name) {
    return name.toUpperCase();
}

@ConsumeEvent("greeting")
public Uni<String> consume2(String name) {
    return Uni.createFrom().item(() -> name.toUpperCase()).emitOn(executor);
}
````

Based on the examples I'd expect the same to work for `Message<T>`, but attempting to consume an event from `EventBus.send` or `EventBus.request` results in a `NoSuchMethodError`. 

This occurs with both Kotlin and Java.

### Expected behavior

A method annotated with `@ConsumesEvent` can return either `void` or `Uni<R>` regardless of whether the parameter is `T` or `Message<T>`.

### Actual behavior

If the method parameter is `Message<T>`, the Vertx event bus only works if the return type is `void`.

```
2021-11-22 11:16:11,566 ERROR [io.qua.ver.cor.run.VertxCoreRecorder] (vert.x-eventloop-thread-2) Uncaught exception received by Vert.x: java.lang.NoSuchMethodError: 'void org.acme.Example.onMessageUni(io.vertx.core.eventbus.Message)'
        at org.acme.Example_VertxInvoker_onMessage_a71f19d99a55f26778e6ec15e5768a5d955c7f96.invokeBean(WebhookImportService_VertxInvoker_onMessageUni_a71f19d99a55f26778e6ec15e5768a5d955c7f96.zig:68)
        at io.quarkus.vertx.runtime.EventConsumerInvoker.invoke(EventConsumerInvoker.java:28)
        at io.quarkus.vertx.runtime.VertxRecorder$3$1.handle(VertxRecorder.java:118)
        at io.quarkus.vertx.runtime.VertxRecorder$3$1.handle(VertxRecorder.java:95)
        at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:50)
        at io.vertx.core.impl.DuplicatedContext.emit(DuplicatedContext.java:168)
        at io.vertx.core.eventbus.impl.MessageConsumerImpl.dispatch(MessageConsumerImpl.java:177)
        at io.vertx.core.eventbus.impl.HandlerRegistration$InboundDeliveryContext.next(HandlerRegistration.java:169)
        at io.vertx.core.eventbus.impl.HandlerRegistration$InboundDeliveryContext.dispatch(HandlerRegistration.java:134)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:111)
        at io.vertx.core.eventbus.impl.HandlerRegistration.dispatch(HandlerRegistration.java:105)
        at io.vertx.core.eventbus.impl.MessageConsumerImpl.deliver(MessageConsumerImpl.java:183)
        at io.vertx.core.eventbus.impl.MessageConsumerImpl.doReceive(MessageConsumerImpl.java:168)
        at io.vertx.core.eventbus.impl.HandlerRegistration.lambda$receive$0(HandlerRegistration.java:56)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

### How to Reproduce?

**Code**

```kotlin
@ConsumeEvent("json")
fun onJsonObject(json: JsonObject) {
    println("[Void] Received JsonObject: ${json.encode()}")
}

@ConsumeEvent("jsonUni")
fun onJsonObjectUni(json: JsonObject): Uni<String> {
    println("[Uni] Received JsonObject: ${json.encode()}")
    return Uni.createFrom().item("JsonObject")
}

@ConsumeEvent("message")
fun onMessage(message: Message<JsonObject>) {
    println("[Void] Received message: [headers=${message.headers()}, body=${message.body().encode()}]")
}

@ConsumeEvent("messageUni")
fun onMessageUni(message: Message<JsonObject>): Uni<String> {
    println("[Uni] Received message: [headers=${message.headers()}, body=${message.body().encode()}]")
    return Uni.createFrom().item("Message")
}

// Elsewhere in the code
val json = JsonObject().put("name", "quarkus")
val options = DeliveryOptions().addHeader("version", "2.5.0.CR1")
bus.send("json", json)
bus.request<String>("jsonUni", json).awaitSuspending()
bus.send("message", json, options)
bus.request<String>("messageUni", json, options).awaitSuspending()
```

**Output**

```
2021-11-22 11:54:28,308 ERROR [io.qua.ver.cor.run.VertxCoreRecorder] (vert.x-eventloop-thread-6) Uncaught exception received by Vert.x: java.lang.NoSuchMethodError: 'void org.acme.Example.onMessageUni(io.vertx.core.eventbus.Message)'
        at org.acme.Example_VertxInvoker_onMessageUni_17549bde5566bd9bd4470ce93824889fee55004c.invokeBean(WebhookImportService_VertxInvoker_onMessageUni_17549bde5566bd9bd4470ce93824889fee55004c.zig:68)
... (rest of the stacktrace)
[Uni] Received JsonObject: {"name":"quarkus"}
[Void] Received message: [headers=version=2.5.0.CR1, body={"name":"quarkus"}]
[Void] Received JsonObject: {"name":"quarkus"}
````

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.5.0.CR1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by rgmz**
Resolves #21621. I can make a separate issue for this feature, if desirable.

### CODE REVIEW

File: extensions/vertx/deployment/src/main/java/io/quarkus/vertx/deployment/EventBusConsumer.java [hunk 1]
```diff
@@ -156,7 +161,22 @@ private static void implementInvoke(BeanInfo bean, MethodInfo method, ClassCreat
...
+        // https://github.com/quarkusio/quarkus/issues/21621
+        Optional<Type> headerType = Optional.empty();
+        Type paramType;
+        if (method.parameters().size() == 2) {
+            Type firstParamType = method.parameters().get(0);
+            if (firstParamType.name().equals(MESSAGE_HEADERS) || firstParamType.name().equals(MUTINY_MESSAGE_HEADERS)) {
+                headerType = Optional.of(firstParamType);
+            } else {
+                // TODO: Throw exception if the 1st param isn't headers,
+                // or assume that the 1st param is the payload?
```
Comment (rgmz) [inline extensions/vertx/deployment/src/main/java/io/quarkus/vertx/deployment/EventBusConsumer.java:174]: Should we validate that a method only has 1 parameter (body) or 2 parameters (header, body)?

File: extensions/vertx/deployment/src/main/java/io/quarkus/vertx/deployment/EventBusConsumer.java [hunk 2]
```diff
@@ -175,10 +195,20 @@ private static void implementInvoke(BeanInfo bean, MethodInfo method, ClassCreat
...
             // Parameter is payload
             ResultHandle bodyHandle = invoke.invokeInterfaceMethod(MESSAGE_BODY, messageHandle);
-            ResultHandle returnHandle = invoke.invokeVirtualMethod(
-                    MethodDescriptor.ofMethod(bean.getImplClazz().name().toString(), method.name(),
-                            method.returnType().name().toString(), paramType.name().toString()),
-                    beanInstanceHandle, bodyHandle);
+            ResultHandle returnHandle;
+            if (headerType.isPresent()) {
+                // TODO: Handle headers from both mutiny and non-mutiny? Will it always be mutiny?
+                ResultHandle headerHandle = invoke.invokeInterfaceMethod(MESSAGE_HEADERS, messageHandle);
```
Comment (rgmz) [inline extensions/vertx/deployment/src/main/java/io/quarkus/vertx/deployment/EventBusConsumer.java:201]: Presumably this should handle both Vertx and Mutiny `MultiMap`.

File: extensions/vertx/deployment/src/main/java/io/quarkus/vertx/deployment/EventBusConsumer.java [hunk 3]
```diff
@@ -175,10 +195,20 @@ private static void implementInvoke(BeanInfo bean, MethodInfo method, ClassCreat
...
+                returnHandle = invoke.invokeVirtualMethod(
+                        MethodDescriptor.ofMethod(bean.getImplClazz().name().toString(), method.name(),
+                                method.returnType().name().toString(), headerType.get().name().toString(), paramType.name().toString()),
+                        beanInstanceHandle, headerHandle, bodyHandle);
```
Comment (rgmz) [inline extensions/vertx/deployment/src/main/java/io/quarkus/vertx/deployment/EventBusConsumer.java:205]: I _think_ adding `headerHandle` before `bodyHandle` is correct?

File: extensions/vertx/deployment/src/main/java/io/quarkus/vertx/deployment/EventBusConsumer.java (hunk 1 above)
Comment (rgmz) [reply extensions/vertx/deployment/src/main/java/io/quarkus/vertx/deployment/EventBusConsumer.java:174]: Nevermind, I see this is handled in `VertxProcessor`.

File: extensions/vertx/deployment/src/main/java/io/quarkus/vertx/deployment/EventBusConsumer.java (hunk 2 above)
Comment (mkouba) [reply extensions/vertx/deployment/src/main/java/io/quarkus/vertx/deployment/EventBusConsumer.java:201]: Yes, you'll need to wrap the original `MultiMap` with `io.vertx.mutiny.core.MultiMap.MultiMap(MultiMap)`.

@cescoffier What's the point of `io.vertx.mutiny.core.MultiMap` anyway? I mean it does not even use any mutiny type...

File: extensions/vertx/deployment/src/main/java/io/quarkus/vertx/deployment/EventBusConsumer.java (hunk 3 above)
Comment (mkouba) [reply extensions/vertx/deployment/src/main/java/io/quarkus/vertx/deployment/EventBusConsumer.java:206]: Yes, given the fact that we validate that headers must be first.

**Comment by mkouba** [comment]
There are some conflicts, pls rebase.

**Comment by rgmz** [comment]
> There are some conflicts, pls rebase.

Done. 

I'm waiting for the CI to run but all test pass locally so I think this is 99% there. :)

File: extensions/vertx/deployment/src/main/java/io/quarkus/vertx/deployment/VertxProcessor.java [hunk 4]
```diff
@@ -114,7 +115,14 @@ void collectEventConsumers(
                 if (consumeEvent != null) {
                     // Validate method params and return type
                     List<Type> params = method.parameters();
-                    if (params.size() != 1) {
+                    if (params.size() == 2) {
+                        if (!isMessageHeaders(params.get(0).name())) {
+                            // If there are two parameters, the first must be message headers.
```
Comment (mkouba) [inline extensions/vertx/deployment/src/main/java/io/quarkus/vertx/deployment/VertxProcessor.java:120]: I think that we should either validate that the second param is not `Message` or modify the `EventBusConsumer` appropriately.  My guess is that `@ConsumeEvent void consume(MultiMap headers, Message<String> message)` would currently fail at runtime...

File: extensions/vertx/runtime/src/main/java/io/quarkus/vertx/ConsumeEvent.java [hunk 5]
```diff
@@ -7,17 +7,23 @@
...
- * {@link io.vertx.core.eventbus.Message#body()} is passed as the parameter value and the method
- * may return an object that is passed to {@link io.vertx.core.eventbus.Message#reply(Object)}, either directly or via
- * {@link java.util.concurrent.CompletionStage#thenAccept(java.util.function.Consumer)} in case of the method returns a
- * completion stage.
- * 
+ * The method can accept the following parameter types:
+ * <ul>
+ * <li>{@link io.vertx.core.eventbus.Message} or {@link io.vertx.mutiny.core.eventbus.Message}</li>
+ * <li>{@code T} ({@link Message#body() message body})</li>
+ * <li>{@link Message#headers() MultiMap (message headers)}, {@code T}</li>
```
Comment (mkouba) [inline extensions/vertx/runtime/src/main/java/io/quarkus/vertx/ConsumeEvent.java:19]: Hm, I think that we should clarify the required number of params and ordering. E.g. currently, we require the headers param to be the first.

**Review by mkouba — COMMENTED** [review]
I've added two comments. Otherwise looks good!

File: extensions/vertx/deployment/src/main/java/io/quarkus/vertx/deployment/EventBusConsumer.java (hunk 2 above)
Comment (cescoffier) [reply extensions/vertx/deployment/src/main/java/io/quarkus/vertx/deployment/EventBusConsumer.java]: @mkouba This is a class generated from the Vert.x MultiMap (because that class a the @VertxGen annotation - see https://github.com/eclipse-vertx/vert.x/blob/master/src/main/java/io/vertx/core/MultiMap.java).

File: extensions/vertx/deployment/src/main/java/io/quarkus/vertx/deployment/VertxProcessor.java (hunk 4 above)
Comment (cescoffier) [reply extensions/vertx/deployment/src/main/java/io/quarkus/vertx/deployment/VertxProcessor.java:120]: We would need to verify with test all the supported parameter permutations (and document them)

File: extensions/vertx/deployment/src/main/java/io/quarkus/vertx/deployment/EventBusConsumer.java (hunk 2 above)
Comment (mkouba) [reply extensions/vertx/deployment/src/main/java/io/quarkus/vertx/deployment/EventBusConsumer.java]: > This is a class generated from the Vert.x MultiMap

I know but I was just wondering why is a similar class needed anyway?

File: extensions/vertx/deployment/src/main/java/io/quarkus/vertx/deployment/VertxProcessor.java (hunk 4 above)
Comment (mkouba) [reply extensions/vertx/deployment/src/main/java/io/quarkus/vertx/deployment/VertxProcessor.java:120]: Hm, if we require the headers to be always the first param (current behavior) then the tests are in place, except for validation. And yes, we need to document this better - see my comment https://github.com/quarkusio/quarkus/pull/21653#discussion_r756659303.

**Comment by gsmet** [comment]
@rgmz could you have a look at @mkouba 's latest comments? Or if you're not going to pursue this, could you tell us? Thanks!

**Comment by rgmz** [comment]
Hey @gsmet, I'll try to finish this up within the next week. I moved to a new city in December — and then Log4J happened. :sweat:

**Comment by cescoffier** [comment]
@rgmz any news?

**Comment by cescoffier** [comment]
@rgmz ping?

**Comment by rgmz** [comment]
Appolgies @cescoffier, due to an unfortunate series of events I've been living quite sparsely for the past few months, and I'm only now settling into my place.

I'll work on rebasing this and applying the suggestions by Monday.

File: extensions/vertx/deployment/src/main/java/io/quarkus/vertx/deployment/VertxProcessor.java (hunk 4 above)
Comment (rgmz) [reply extensions/vertx/deployment/src/main/java/io/quarkus/vertx/deployment/VertxProcessor.java:121]: @mkouba I've added a check to handle `@ConsumeEvent void consume(MultiMap headers, Message<String> message)`, and updated the JavaDoc for `@ConsumeEvent` to explicitly specify valid parameters.

**Review by mkouba — APPROVED** [review]
Looks good.

**Comment by mkouba** [comment]
The CI failure does not seem to be related but there are two conflicting files again :-(.

@rgmz would you care to rebase your PR once again?

**Comment by rgmz** [comment]
> @rgmz would you care to rebase your PR once again?

Done.
