### PR TITLE
Solves quarkus kakfa-streams extension devmode issue

### LINKED ISSUE #12223: Kafka-streams dev mode broken
**Describe the bug**
Kafka-streams dev mode is not working anymore when an update of the application is detected.

**Expected behavior**
If a project source file is updated, the dev-mode recompiles the project and is able to relaunch the application to continue to work

**Actual behavior**
The PR #11540 introduced a [boolean flag](https://github.com/quarkusio/quarkus/pull/11540/files#diff-b1ea2a75cf0dc3e000fb088c2e58d4e8R55) to prevent kafka-streams to start if the application is stopping prematurely. Once this flag set kafka-streams won't be restarted in any situation.  

**To Reproduce**
This would be reproductible with the kafka-streams quickstart

### PR DESCRIPTION
**Pull request by vietk**
Fixes #12223

### CODE REVIEW

File: extensions/kafka-streams/runtime/src/main/java/io/quarkus/kafka/streams/runtime/KafkaStreamsProducer.java [hunk 1]
```diff
@@ -54,6 +54,8 @@
     private static final Logger LOGGER = Logger.getLogger(KafkaStreamsProducer.class.getName());
     private static volatile boolean shutdown = false;
 
+    public static volatile boolean ignoreShutdownFlag = false;
```
Comment (gunnarmorling) [inline extensions/kafka-streams/runtime/src/main/java/io/quarkus/kafka/streams/runtime/KafkaStreamsProducer.java:57]: Instead of having to reason about the two booleans, how about establishing an enum which exposes all the potential states the producer can be in, e.g. `enum State { RUNNING, RUNNING_NON_STOPPABLE, STOPPED}`?

File: extensions/kafka-streams/runtime/src/main/java/io/quarkus/kafka/streams/runtime/devmode/KafkaStreamsHotReplacementSetup.java [hunk 2]
```diff
@@ -32,11 +33,14 @@ public void run() {
                             @Override
                             public void run() {
                                 try {
+                                    KafkaStreamsProducer.ignoreShutdownFlag = true;
```
Comment (gunnarmorling) [inline extensions/kafka-streams/runtime/src/main/java/io/quarkus/kafka/streams/runtime/devmode/KafkaStreamsHotReplacementSetup.java:36]: Won't this cause things to not shut down properly? If a shutdown request comes in while this flag is set, this request will be ignored, but it seems we'd never do the shutdown later on then?

**Review by gunnarmorling — COMMENTED** [review]
Two questions/suggestions inline.

File: extensions/kafka-streams/runtime/src/main/java/io/quarkus/kafka/streams/runtime/KafkaStreamsProducer.java [hunk 3]
```diff
@@ -103,7 +105,9 @@ public KafkaStreamsTopologyManager kafkaStreamsTopologyManager() {
     }
 
     void onStop(@Observes ShutdownEvent event) {
-        shutdown = true;
+        if (!ignoreShutdownFlag) {
```
Comment (rquinio) [inline extensions/kafka-streams/runtime/src/main/java/io/quarkus/kafka/streams/runtime/KafkaStreamsProducer.java:108]: It may be simpler to set _shutdown_ to false in KafkaStreamsProducer constructor ?
If injection is being re-triggered, I suppose it means a restart is happening in same classloader.

File: extensions/kafka-streams/runtime/src/main/java/io/quarkus/kafka/streams/runtime/devmode/KafkaStreamsHotReplacementSetup.java (hunk 2 above)
Comment (vietk) [reply extensions/kafka-streams/runtime/src/main/java/io/quarkus/kafka/streams/runtime/devmode/KafkaStreamsHotReplacementSetup.java:36]: I think @rquinio's [comment](https://github.com/quarkusio/quarkus/pull/12224#discussion_r492005054) make sense in fact.
The producer bean is recreated however, the class is still the same as loaded before, however shutdown flag is set to true because if the first shutdown from dev mode. So putting the state back to the initial value in the constructor should make the trick

File: extensions/kafka-streams/runtime/src/main/java/io/quarkus/kafka/streams/runtime/KafkaStreamsProducer.java (hunk 1 above)
Comment (vietk) [reply extensions/kafka-streams/runtime/src/main/java/io/quarkus/kafka/streams/runtime/KafkaStreamsProducer.java:57]: I'll drop the 2nd boolean

File: extensions/kafka-streams/runtime/src/main/java/io/quarkus/kafka/streams/runtime/KafkaStreamsProducer.java (hunk 3 above)
Comment (vietk) [reply extensions/kafka-streams/runtime/src/main/java/io/quarkus/kafka/streams/runtime/KafkaStreamsProducer.java]: makes sense, tested it works

**Comment by gsmet** [comment]
@stuartwdouglas I'm intrigued by this one? I would have expected the class to be reloaded in a new CL when dev mode restarts the app?

**Comment by vietk** [comment]
@gsmet : Was wondering the same before submitting a PR. But I saw that the dev mode is 'playing' with many classloaders, looking at the code. 
I end thinking that there's an "application" classloader and an "extension" classloader, but I would like to understand it all too.

**Comment by stuartwdouglas** [comment]
We don't reload the extensions, just the user code. Class loading is really expensive, you don't want to have to reload everything on dev mode restart (and you needs lots of things to stick around anyway like the HTTP connection).

**Review by gsmet — APPROVED** [review]
