### PR TITLE
Show image pull output when using a builder image

### LINKED ISSUE #6892: Using -Dquarkus.native.container-build to build container native build should display progress logs
**Describe the bug**
I was trying to create a container native build using:
```
$  mvn package -Pnative -Dquarkus.native.container-build=true 
````
It got stuck for a while without any info, it was pulling the 400MB image in background (which can take a while on a slow network).

**Expected behavior**
It should display docker output in the console.

**Actual behavior**
It doesn't show anything

**To Reproduce**
1. Have slow connection
2. Remove the `quay.io/quarkus/ubi-quarkus-native-image` from your docker cache
3. Run `mvn package -Pnative -Dquarkus.native.container-build=true `

**Environment (please complete the following information):**
 - Quarkus version or git rev: 1.2.0.Final

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #6892

### CODE REVIEW

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java [hunk 1]
```diff
@@ -108,6 +108,22 @@ public NativeImageBuildItem build(NativeConfig nativeConfig, NativeImageSourceJa
...
+            if ("docker".equals(containerRuntime) || "podman".equals(containerRuntime)) {
+                // we pull the docker image in order to give users an indication of which step the process is at
+                // it's not strictly necessary we do this, however if we don't the subsequent version command
+                // will appear to block and no output will be shown
+                log.info("Pulling image " + nativeConfig.builderImage);
+                try {
+                    Process pullProcess = new ProcessBuilder(Arrays.asList(containerRuntime, "pull", nativeConfig.builderImage))
+                            .inheritIO()
+                            .start();
+                    pullProcess.waitFor();
```
Comment (gastaldi) [inline core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java]: Better call process.destroy() in a finally block just in case

Comment (geoand) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java]: Good idea

Comment (geoand) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java]: Done

Comment (gsmet) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java]: Maybe have a look at that change by Stuart: https://github.com/quarkusio/quarkus/pull/6031 .

Comment (geoand) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java]: Hm... In this case we aren't really reading anything from the process output, we just want to wait for it, so I don't think the change is needed, right?

**Review by gastaldi — APPROVED** [review]
LGTM

**Comment by geoand** [comment]
I also verified manually that the output does show up.

Plus since we use docker builds in CI, one can always look there when it's done to see the expected output

**Comment by ia3andy** [comment]
@geoand I will test it in a few minutes ;-) thanks!!

**Comment by geoand** [comment]
@ia3andy you should see something like:

```
2020-01-31T07:17:19.8338408Z [INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Pulling image quay.io/quarkus/ubi-quarkus-native-image:19.3.1-java8
2020-01-31T07:17:21.0472365Z 19.3.1-java8: Pulling from quarkus/ubi-quarkus-native-image
2020-01-31T07:17:21.0481614Z 57de4da701b5: Pulling fs layer
2020-01-31T07:17:21.0500610Z cf0f3ebe9f53: Pulling fs layer
2020-01-31T07:17:21.0506723Z 74e4ceac2598: Pulling fs layer
2020-01-31T07:17:21.4158146Z cf0f3ebe9f53: Verifying Checksum
2020-01-31T07:17:21.4158656Z cf0f3ebe9f53: Download complete
2020-01-31T07:17:21.6920223Z 57de4da701b5: Verifying Checksum
2020-01-31T07:17:21.6921583Z 57de4da701b5: Download complete
2020-01-31T07:17:23.7386786Z 57de4da701b5: Pull complete
2020-01-31T07:17:23.8816428Z cf0f3ebe9f53: Pull complete
2020-01-31T07:17:24.9466170Z 74e4ceac2598: Verifying Checksum
2020-01-31T07:17:24.9467331Z 74e4ceac2598: Download complete
2020-01-31T07:17:39.8790892Z 74e4ceac2598: Pull complete
```

**Comment by ia3andy** [comment]
It works great! It looks like a small thing but it look less buggy now :) Very good job
