### PR TITLE
Fix flaky recovery lra

### LINKED ISSUE #51016: Flaky test org.eclipse.microprofile.lra.tck.TckRecoveryTests.testCancelWhenParticipantIsUnavailable
### Describe the bug

Fix the lra tck flaky test: https://ge.quarkus.io/scans/tests?search.timeZoneId=Europe%2FPrague&tests.container=org.eclipse.microprofile.lra.tck.TckRecoveryTests&tests.test=testCancelWhenParticipantIsUnavailable 

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by marcosgopen**
Fixes the flaky recovery test in Develocity: https://ge.quarkus.io/scans/tests?search.timeZoneId=Europe%2FPrague&tests.container=org.eclipse.microprofile.lra.tck.TckRecoveryTests&tests.test=testCancelWhenParticipantIsUnavailable

- Fixes: https://github.com/quarkusio/quarkus/issues/51016

### CODE REVIEW

**Comment by marcosgopen** [comment]
cc @xstefank @Sanne

**Review by Sanne — APPROVED** [review]

File: tcks/microprofile-lra/src/main/java/io/quarkus/tck/lra/NarayanaLRARecovery.java [hunk 1]
```diff
@@ -32,17 +32,33 @@
...
     private static final Logger log = Logger.getLogger(NarayanaLRARecovery.class);
+    private static final long WAIT_CALLBACK_TIMEOUT = initWaitForCallbackTimeout();
+    private static final String WAIT_CALLBACK_TIMEOUT_PROPERTY = "lra.tck.callback.timeout";
 
+    /*
+     * Wait for the participant to return the callback. This method does not
+     * guarantee callbacks to finish. The Participant status is not immediately
+     * reflected to the LRA status, but only after a recovery scan which executes an
+     * enlistment. The waiting time can be configurable by
+     * LRAConstants.WAIT_CALLBACK_TIMEOUT property.
```
Comment (xstefank) [inline tcks/microprofile-lra/src/main/java/io/quarkus/tck/lra/NarayanaLRARecovery.java]: I would rather say `lra.tck.callback.timeout` config propery" but not a big issue

File: tcks/microprofile-lra/src/main/java/io/quarkus/tck/lra/NarayanaLRARecovery.java [hunk 2]
```diff
@@ -83,4 +99,18 @@ private boolean recoverLRAs(URI lraId) {
             recoveryCoordinatorClient.close();
         }
     }
+
+    private static Integer initWaitForCallbackTimeout() {
+        Config config = ConfigProvider.getConfig();
+        int defaultValue = 1000;
```
Comment (xstefank) [inline tcks/microprofile-lra/src/main/java/io/quarkus/tck/lra/NarayanaLRARecovery.java]: This could be a final field rather so we don't need to search for the default buried here

**Review by xstefank — APPROVED** [review]
I'm not heavily set on these so approving, thanks!

File: tcks/microprofile-lra/src/main/java/io/quarkus/tck/lra/NarayanaLRARecovery.java (hunk 1 above)
Comment (marcosgopen) [reply tcks/microprofile-lra/src/main/java/io/quarkus/tck/lra/NarayanaLRARecovery.java]: Updated thanks!

File: tcks/microprofile-lra/src/main/java/io/quarkus/tck/lra/NarayanaLRARecovery.java (hunk 2 above)
Comment (marcosgopen) [reply tcks/microprofile-lra/src/main/java/io/quarkus/tck/lra/NarayanaLRARecovery.java]: Updated thanks!

**Review by Sanne — APPROVED** [review]
Thanks @marcosgopen !

**Comment by Sanne** [comment]
hum it literally failed the same flaky test that it was supposed to fix?  @geoand why would you merge it :D

**Comment by geoand** [comment]
Trigger happy finger 😉

**Comment by Sanne** [comment]
it's a great example of how those flaky tests become almost invisible :laughing:  It's proving my point that deleting them would be more effective.

**Comment by geoand** [comment]
Agreed

**Comment by Sanne** [comment]
@marcosgopen sorry we shouldn't have merged it yet - but we did. I've re-opened the issue, apparently this wasn't enough. Could you have another look?

**Comment by marcosgopen** [comment]
> @marcosgopen sorry we shouldn't have merged it yet - but we did. I've re-opened the issue, apparently this wasn't enough. Could you have another look?

Yes, I will have another look and in case I find a solution I will open a new PR with another fix and revert this PR's changes.

**Comment by xstefank** [comment]
@geoand @Sanne yeaaaah, about that, deleting MP TCK tests won't be thaaaat easy :D
