### PR TITLE
CDI security determined at build time

### LINKED ISSUE #4992: CDI security: Unannotated inherited methods may be restricted when they should not
**Describe the bug**
For the case in the $subject, `determineSecurityAnnotationFromBindings#determineSecurityAnnotationFromBindings` returns annotations from the subclass even if the method is not overriden

**Expected behavior**
If we want to be consistent with JSR 250 section 2.1 point 4, constraint from the subclass should not be applied here.

**To Reproduce**
 Run `CDIAccessDefaultTest.shouldAccessInheritedAllowedMethod` separately

### PR DESCRIPTION
**Pull request by michalszynkiewicz**
Fixes #4992

### CODE REVIEW

**Comment by michalszynkiewicz** [comment]
@stuartwdouglas do we want it now?

**Comment by gsmet** [comment]
Marking it for 0.28.0 so that we don't forget to decide what to do with this PR but I will let @stuartwdouglas  decide if it should go in or not.

**Comment by gsmet** [comment]
Rebased and force-pushed to get the higher timeout for TCK tests I pushed to master.

**Comment by michalszynkiewicz** [comment]
thanks @gsmet !

**Comment by michalszynkiewicz** [comment]
There is a test failure in microprofile-jwt tck. The failure seems to be due to the fact that role mappings are not applied.
What's strange is that the same test is in the smallrye-jwt/deployment module, it's called `RolesAllowedUnitTest` and it passes.
The most outstanding difference is arquillian vs `QuarkusUnitTest`.

**Comment by michalszynkiewicz** [comment]
For the successful test (in smallrye-jwt), the mapped "role" is provided by the security identity which makes it hard to believe this PR is the cause.
I tried a couple other revisions of Quarkus that didn't contain my changes and they failed for me too but maybe I have some leftovers in `.m2/repository`

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanGenerator.java [hunk 1]
```diff
@@ -130,6 +131,9 @@ public BeanGenerator(AnnotationLiteralProcessor annotationLiterals, Predicate<Do
         }
         baseNameBuilder.append("_");
         baseNameBuilder.append(bean.getIdentifier());
+        if (Boolean.TRUE.toString().equals(System.getProperty("quarkus.random-synthetic-bean-names"))) {
```
Comment (michalszynkiewicz) [inline independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanGenerator.java]: @mkouba @manovotn  wdyt?

Comment (michalszynkiewicz) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanGenerator.java]: (this is to allow running tests that need to generate different synthetic beans in one JVM)

Comment (mkouba) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanGenerator.java]: I think it's a bad idea. We should try to find a different way to fix this.

Comment (manovotn) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanGenerator.java]: How come you need the property when I see you added `<reuseForks>false</reuseForks>`?
But to be fair, I don't really like this either. +1 for different way but I have to admit I don't have one at hand...

Comment (michalszynkiewicz) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanGenerator.java]: the property is only used in MP JWT TCK where `reuseForks = false` doesn't work out of the box because the tests are using testng xml. 
I tried working this around by removing the testng xml and listing the tests in the surefire plugin configuration but then one of the tests starts failing

Comment (michalszynkiewicz) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanGenerator.java]: I don't treat this as the ultimate solution but a workaround until we handle reloading synthetic beans properly. But if this fix can wait until that is fixed, I'm okay with waiting.
BTW, does the fact that synthetic beans are not in the application classloader also impact live reload?

File: build-parent/pom.xml [hunk 2]
```diff
@@ -155,6 +157,7 @@
             <plugins>
                 <plugin>
                     <artifactId>maven-surefire-plugin</artifactId>
+                    <version>${surefire-plugin.version}</version>
```
Comment (stuartwdouglas) [inline build-parent/pom.xml]: This should already be defined by the jboss-parent pom. overriding the version.surefire.plugin should be all that is needed to get the newer version.

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanGenerator.java (hunk 1 above)
Comment (stuartwdouglas) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanGenerator.java]: You can fix it like this for now: https://github.com/quarkusio/quarkus/commit/d85e2d58af1594892bacd84dc3fbd7c5520468c0

**Review by stuartwdouglas — CHANGES_REQUESTED** [review]

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanGenerator.java (hunk 1 above)
Comment (michalszynkiewicz) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanGenerator.java]: works like a charm, thank you @stuartwdouglas !
I'll update the PR soon.

File: build-parent/pom.xml (hunk 2 above)
Comment (michalszynkiewicz) [reply build-parent/pom.xml]: done

**Review by manovotn — APPROVED** [review]
Looks good now!
I didn't even know we have `ApplicationClassPredicateBuildItem`, that's really neat way to circumvent the problem.

**Comment by manovotn** [comment]
The CI failure doesn't look related. It is a `NoSuchElementException` coming from Kafka integration tests (`KafkaConsumerTest`).

**Comment by michalszynkiewicz** [comment]
yay! all green!

File: extensions/security/deployment/src/main/java/io/quarkus/security/deployment/SecurityProcessor.java [hunk 3]
```diff
@@ -85,6 +109,147 @@ void registerSecurityInterceptors(BuildProducer<InterceptorBindingRegistrarBuild
...
+        return result;
+    }
+
+    private Map<MethodInfo, AnnotationInstance> gatherSecurityAnnotations(ApplicationIndexBuildItem indexBuildItem,
+            BeanRegistrar.RegistrationContext registrationContext) {
+        Set<DotName> securityAnnotations = SecurityAnnotationsRegistrar.SECURITY_BINDINGS.keySet();
+        AnnotationStore annotationStore = registrationContext.get(BuildExtension.Key.ANNOTATION_STORE);
+        Set<ClassInfo> classesWithSecurity = new HashSet<>();
+
+        Collection<ClassInfo> classes = indexBuildItem.getIndex().getKnownClasses();
```
Comment (stuartwdouglas) [inline extensions/security/deployment/src/main/java/io/quarkus/security/deployment/SecurityProcessor.java]: Does this really need to iterate over all the classes? Can't you just look for security annotations in the index?

**Review by stuartwdouglas — CHANGES_REQUESTED** [review]
Other than iterating over all the classes I think it looks good. If this could be changed to just look up the relevant annotations from the index then it should be good to go.

File: extensions/security/deployment/src/main/java/io/quarkus/security/deployment/SecurityProcessor.java (hunk 3 above)
Comment (michalszynkiewicz) [reply extensions/security/deployment/src/main/java/io/quarkus/security/deployment/SecurityProcessor.java]: The problem with using the index is with the synthetic annotations (like the `@DenyAll` when the specific switches are enabled or the `@Secured` transalted to `@RolesAllowed` that @aureamunoz is working on).
I was trying to work around it by emitting build items that would contain such information. But it led to build step cycle with resteasy. I think it was because I use ResteasyDeployment for denying JAX-RS by default.
I'm not 100% sure if it cannot be worked around but thought going through the application index only shouldn't be that costly.

Comment (michalszynkiewicz) [reply extensions/security/deployment/src/main/java/io/quarkus/security/deployment/SecurityProcessor.java]: Plus annotationStore is populated lazily. That's why I could not get a list of classes with synthetic annotations from it.

Comment (geoand) [reply extensions/security/deployment/src/main/java/io/quarkus/security/deployment/SecurityProcessor.java]: I haven't followed this PR lately, but from the start I thought that the BuildItem approach would be the cleanest way to go. 
I'll look into the PR more tomorrow and see if / how it can be done

File: extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityConstrainer.java [hunk 4]
```diff
@@ -1,188 +1,35 @@
...
  * @author Michal Szynkiewicz, michal.l.szynkiewicz@gmail.com
  */
 @Singleton
 public class SecurityConstrainer {
 
-    private static final List<Class<? extends Annotation>> SECURITY_ANNOTATIONS = asList(Authenticated.class, DenyAll.class,
-            PermitAll.class, RolesAllowed.class);
-
-    private final Map<Method, Optional<Check>> checkForMethod = new ConcurrentHashMap<>();
+    private final Map<Method, Optional<SecurityCheck>> checkForMethod = new ConcurrentHashMap<>();
```
Comment (geoand) [inline extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityConstrainer.java]: I think this is no longer needed, correct?

File: extensions/security/deployment/src/main/java/io/quarkus/security/deployment/SecurityProcessor.java [hunk 5]
```diff
@@ -85,6 +109,147 @@ void registerSecurityInterceptors(BuildProducer<InterceptorBindingRegistrarBuild
...
+        }
+        return methodAnnotations;
+    }
+
+    private AnnotationInstance getSingle(Collection<AnnotationInstance> classAnnotations, Set<DotName> securityAnnotations) {
+        AnnotationInstance result = null;
+        for (AnnotationInstance annotation : classAnnotations) {
+            if (securityAnnotations.contains(annotation.name())) {
+                if (result != null) {
+                    throw new IllegalStateException("Duplicate security annotations on class " + annotation.target());
```
Comment (geoand) [inline extensions/security/deployment/src/main/java/io/quarkus/security/deployment/SecurityProcessor.java]: I think the error message can be improved. `Duplicate` isn't the correct word here IMHO because a developer could do:

```
    @RolesAllowed("admin")
    @DenyAll
    public void doSomething() {
    }
```

and get this error

File: extensions/security/deployment/src/main/java/io/quarkus/security/deployment/SecurityProcessor.java [hunk 6]
```diff
@@ -85,6 +109,147 @@ void registerSecurityInterceptors(BuildProducer<InterceptorBindingRegistrarBuild
...
+    }
+
+    private ResultHandle annotationValues(MethodCreator methodCreator, AnnotationInstance instance) {
+        AnnotationValue value = instance.value();
+        if (value != null && value.asStringArray() != null) {
+            String[] values = value.asStringArray();
+            ResultHandle result = methodCreator.newArray(String.class, methodCreator.load(values.length));
+            int i = 0;
+            for (String val : values) {
+                methodCreator.writeArrayValue(result, i, methodCreator.load(val));
```
Comment (geoand) [inline extensions/security/deployment/src/main/java/io/quarkus/security/deployment/SecurityProcessor.java]: `i` needs to be incremented

**Comment by geoand** [comment]
I am pretty close - I still need to fix a few failing tests but I'll do that later on.
@michalszynkiewicz would you like me to open a PR against your PR when done or would you like me to check push to just to your branch?

**Comment by michalszynkiewicz** [comment]
PR to my branch would be optimal for me

**Comment by geoand** [comment]
Cool. I'll open a PR today or tomorrow if all goes well

**Comment by geoand** [comment]
Actually it seems that I spoke too soon. The `config.denyUnannotated` is creating problems when trying to remove the dependency on the annotation store and the loop over all classes in the index.
I'll keep digging

**Comment by geoand** [comment]
I was able to get around the problems I had and the updated I have passes the security tests. The change seems however to be failing in random HTTP tests which is something I'll need to check out.

File: extensions/security/deployment/src/main/java/io/quarkus/security/deployment/SecurityProcessor.java (hunk 5 above)
Comment (michalszynkiewicz) [reply extensions/security/deployment/src/main/java/io/quarkus/security/deployment/SecurityProcessor.java]: yeah, and I thought duplicate covers that. Would be grateful for some tips on new name

Comment (geoand) [reply extensions/security/deployment/src/main/java/io/quarkus/security/deployment/SecurityProcessor.java]: I would just say that multiple security annotations are present

File: extensions/security/deployment/src/main/java/io/quarkus/security/deployment/SecurityProcessor.java (hunk 6 above)
Comment (michalszynkiewicz) [reply extensions/security/deployment/src/main/java/io/quarkus/security/deployment/SecurityProcessor.java]: done

File: extensions/security/deployment/src/main/java/io/quarkus/security/deployment/SecurityProcessor.java (hunk 5 above)
Comment (michalszynkiewicz) [reply extensions/security/deployment/src/main/java/io/quarkus/security/deployment/SecurityProcessor.java]: done

File: extensions/security/deployment/src/main/java/io/quarkus/security/deployment/SecurityProcessor.java (hunk 3 above)
Comment (michalszynkiewicz) [reply extensions/security/deployment/src/main/java/io/quarkus/security/deployment/SecurityProcessor.java]: @geoand suggested looping through the index only if there are synthetically added annotations (only if the config options that result in adding `@DenyAll`'s are present).
The newest patchset does it. 
WDYT @stuartwdouglas ?

**Comment by michalszynkiewicz** [comment]
Thank you @geoand !

**Comment by geoand** [comment]
Looks good!

File: extensions/security/deployment/src/main/java/io/quarkus/security/deployment/SecurityProcessor.java (hunk 3 above)
Comment (geoand) [reply extensions/security/deployment/src/main/java/io/quarkus/security/deployment/SecurityProcessor.java]: The reason we need to loop through the index when denyAll is enabled is because like @michalszynkiewicz mentione above, the annotation store doesn't provide a way to give all the instances of an annotation in the way the Jandex index does.
And the implementation of denyAll is based on the annotation store, since it's the easient way to do it and be sure that `@DenyAll` is only added to CDI beans an not everything under the sun.

**Comment by geoand** [comment]
@michalszynkiewicz can you please rebase your PR onto the latest master?

**Comment by michalszynkiewicz** [comment]
@geoand done, let's see

**Comment by geoand** [comment]
@michalszynkiewicz can you do another rebase please? It looks like CI is holding on to an old version of the spring artifacts

**Comment by geoand** [comment]
Another Spring related PR was merged into master and leaked into the native artifacts. Another rebase is needed...

**Comment by michalszynkiewicz** [comment]
rebased once again...

**Comment by gsmet** [comment]
@stuartwdouglas could you have another look at that one?

TBH, I'm a bit torn about this as it's a big patch but it seems like a fix we need. I marked it as `backport?` so that we try to take care of it before Final but we need to be sure it won't break anything.

**Comment by geoand** [comment]
Once this is in a I have a change ready that will target `1.1` and will pave the way for easier custom security integration (it will change the way https://github.com/quarkusio/quarkus/pull/5225 is implemented and make it possible to implement things like `@PreAuthorize`)

File: extensions/security/deployment/src/main/java/io/quarkus/security/deployment/SecurityProcessor.java [hunk 7]
```diff
@@ -85,6 +114,168 @@ void registerSecurityInterceptors(BuildProducer<InterceptorBindingRegistrarBuild
...
+
+    private Map<MethodInfo, AnnotationInstance> gatherSecurityAnnotationsByLooping(ApplicationIndexBuildItem indexBuildItem,
+            BeanRegistrar.RegistrationContext registrationContext,
+            boolean loopThroughIndex) {
+        Set<DotName> securityAnnotations = SecurityAnnotationsRegistrar.SECURITY_BINDINGS.keySet();
+        AnnotationStore annotationStore = registrationContext.get(BuildExtension.Key.ANNOTATION_STORE);
+        Set<ClassInfo> classesWithSecurity = new HashSet<>();
+
+        Index index = indexBuildItem.getIndex();
+        if (loopThroughIndex) { // only needed when synthetic security annotations are added
```
Comment (stuartwdouglas) [inline extensions/security/deployment/src/main/java/io/quarkus/security/deployment/SecurityProcessor.java]: I don't really like this approach with two different code paths. IMHO a better approach would be to DenyAllBuildItem  be AdditionalSecuredClassesBuildIem, and have it just direct provide the class names of the JAX-RS endpoints, so no iteration is required and there is only one code path.

**Review by stuartwdouglas — CHANGES_REQUESTED** [review]
LGTM except for that one issue I mentioned

File: extensions/security/deployment/src/main/java/io/quarkus/security/deployment/SecurityProcessor.java (hunk 7 above)
Comment (geoand) [reply extensions/security/deployment/src/main/java/io/quarkus/security/deployment/SecurityProcessor.java]: How would you handle the other denyAll case though, I mean the one that applies to all CDI beans? There isn't a way to get all beans as far as I know.

Comment (stuartwdouglas) [reply extensions/security/deployment/src/main/java/io/quarkus/security/deployment/SecurityProcessor.java]: Look up @DenyAll from the annotation index

Comment (stuartwdouglas) [reply extensions/security/deployment/src/main/java/io/quarkus/security/deployment/SecurityProcessor.java]: Basically for the other case where we want to deny it only applies if there is another security annotation on the CdI bean. This means the existing logic in the other branch should discover them.

Comment (geoand) [reply extensions/security/deployment/src/main/java/io/quarkus/security/deployment/SecurityProcessor.java]: That won't work for the `quarkus.securitu.deny-unannotated` option.
It won't work because that option means that we need to implicitly add DenyAll to all beans that don't have any security annotation, therefore there is nothing to look up in the index.

Comment (geoand) [reply extensions/security/deployment/src/main/java/io/quarkus/security/deployment/SecurityProcessor.java]: Now that raises the question of whether this config option makes sense at all. I personally don't understand it, but I am assuming it's been discussed before and there was good reason to add it.

Comment (michalszynkiewicz) [reply extensions/security/deployment/src/main/java/io/quarkus/security/deployment/SecurityProcessor.java]: for CDI beans, the synthetic deny all only applies to beans that have some security annotations, so that shouldn't be a problem.
Testing once again. I had problems with build steps cycle but that clearly shouldn't be a problem since `DenyAllBuildItem` is passed from step consuming a RestEasy deployment...

Comment (stuartwdouglas) [reply extensions/security/deployment/src/main/java/io/quarkus/security/deployment/SecurityProcessor.java]: It adds DenyAll to methods of a bean that have at least one security annotation:

```
class Foo {
@RolesAllowed("foo")
 void doStuff1() {}

void doOtherStuff() {}

}
```
In this case it will mark doOtherStuff as DenyAll. Basically it is a failsafe against forgetting to add security metadata to a secured bean, you need to explicitly use @PermitAll to state your intentions.

Comment (geoand) [reply extensions/security/deployment/src/main/java/io/quarkus/security/deployment/SecurityProcessor.java]: @michalszynkiewicz if you can get rid of the loop for CDI beans, then the JAX-RS case could be easily handled like @stuartwdouglas proposes.
I am however sceptical that the CDI case can be handled without the loop, but I'd like it very much if it can

Comment (geoand) [reply extensions/security/deployment/src/main/java/io/quarkus/security/deployment/SecurityProcessor.java]: Aha! Know I see what I misunderstood... I thought that DenyAll applies to ALL beans, ever without any security annotation.
So yeah I agree this should be easy and there is no need for the loop

File: extensions/security/deployment/src/main/java/io/quarkus/security/deployment/SecurityProcessor.java [hunk 8]
```diff
@@ -85,6 +112,158 @@ void registerSecurityInterceptors(BuildProducer<InterceptorBindingRegistrarBuild
...
 
+    @BuildStep
+    void gatherSecurityChecks(BuildProducer<BeanRegistrarBuildItem> beanRegistrars,
+            ApplicationIndexBuildItem indexBuildItem,
+            BuildProducer<ApplicationClassPredicateBuildItem> classPredicate,
+            List<AdditionalSecuredClassesBuildIem> additionalSecuredClasses) {
+        classPredicate.produce(new ApplicationClassPredicateBuildItem(new SecurityCheckStorage.AppPredicate()));
+
+        Set<ClassInfo> additionalSecured = new HashSet<>();
+        if (additionalSecuredClasses != null) {
```
Comment (stuartwdouglas) [inline extensions/security/deployment/src/main/java/io/quarkus/security/deployment/SecurityProcessor.java]: This will never be null

**Review by stuartwdouglas — APPROVED** [review]
Lgtm, except for one minor comment that is not worth holding the pr over

File: extensions/security/deployment/src/main/java/io/quarkus/security/deployment/SecurityProcessor.java (hunk 8 above)
Comment (geoand) [reply extensions/security/deployment/src/main/java/io/quarkus/security/deployment/SecurityProcessor.java]: I'll be changing this in a subsequent PR anyway

**Comment by gsmet** [comment]
This one was a pain to backport but it's done. I will run the tests a bit later.

**Comment by geoand** [comment]
Thanks so much @gsmet! A true Quarkus hero :)

**Comment by michalszynkiewicz** [comment]
@gsmet sorry to hear that it was difficult and thank you for doing it :)
