### PR TITLE
Fix working directory property in quarkusDev task

### LINKED ISSUE #9653: Gradle: setWorkingDir not working in 1.5.0
**Describe the bug**
I'm setting the working directory in for `quarkusDev` task in my Gradle build file via
```
tasks {
  quarkusDev {
    setWorkingDir(projectDir.path)
  }
}
```
After updating to any 1.5.0 version of Quarkus I get `${proejct.path}\build\classes\java\main\.` as working dir in the app.

**Expected behavior**
The working directory of the application is set properly.

**Actual behavior**
The setting is ignored and the classes path is used.

**To Reproduce**
1. Create a new project.
2. Set a working directory in task configuration (e.g. `C:\tmp` on Windows).
3. Access current working directory in Java (e.g. `System.getProperty("user.dir")` or `Path.of("")`).

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `Microsoft Windows [Version 10.0.18363.836]`
 - Output of `java -version`: 
```
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02)
OpenJDK 64-Bit Server VM GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02, mixed mode, sharing)
```
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.5.0.Final and 1.5.0.CR1 
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`):  6.4.1

**Additional context**
This does also not work on a Linux machine.

### PR DESCRIPTION
**Pull request by glefloch**
Use `workingDir` property from `quarkusDev` task if set or fallback to extension property if not.

Also fix a minor typo in the `README.md` :) 

Close #9653

### CODE REVIEW

**Comment by glefloch** [comment]
@aloubyansky, could you have a look ?

**Comment by aloubyansky** [comment]
That looks good. Let's wait for the CI. Thanks @glefloch

**Review by gastaldi — APPROVED** [review]

**Comment by aloubyansky** [comment]
@glefloch I think you are running into an issue I was running into before which was the reason I went for the extension workDir. Do the tests pass for you locally?

**Comment by glefloch** [comment]
Yes, just saw that, I will have a look, it seems that the path is always evaluated.

File: devtools/gradle/src/main/java/io/quarkus/gradle/tasks/QuarkusDev.java [hunk 1]
```diff
@@ -111,9 +111,8 @@ public void setSourceDir(String sourceDir) {
         this.sourceDir = sourceDir;
     }
 
-    @Option(description = "Set working directory", option = "working-dir")
-    @Deprecated
     @Input
+    @Deprecated
     // @InputDirectory this breaks kotlin projects, the working dir at this stage will be evaluated to 'classes/java/main' instead of 'classes/kotlin/main'
```
Comment (aloubyansky) [inline devtools/gradle/src/main/java/io/quarkus/gradle/tasks/QuarkusDev.java:116]: Looks like you got it right! Probably a path issue on windows?
If it's fully working, perhaps, we shouldn't be deprecating the method.

Comment (glefloch) [reply devtools/gradle/src/main/java/io/quarkus/gradle/tasks/QuarkusDev.java:115]: @aloubyansky you are right, this is a path issue on windows, I updated the code to use `java.io.tmpdir` instead. 
Using the getter to get `workingDir` instead of accessing it directly fix the issue.

**Review by aloubyansky — APPROVED** [review]
Great, waiting for the CI.
