### PR TITLE
Fix RedisClientName and MongoClientName can't be applied to parameters

### LINKED ISSUE #12898: `@RedisClientName` can't be applied to parameters
`@RedisClientName` can't be applied to parameters and thus named redis clients can't be injected to constructors or producer methods.

### PR DESCRIPTION
**Pull request by machi1990**
Fixes https://github.com/quarkusio/quarkus/issues/12898

### CODE REVIEW

File: integration-tests/redis-client/src/main/java/io/quarkus/redis/it/RedisWithNamedClientResource.java [hunk 1]
```diff
@@ -18,13 +18,15 @@
 @Path("/quarkus-redis-with-named")
 @ApplicationScoped
 public class RedisWithNamedClientResource {
-    @Inject
-    @RedisClientName("named-client")
-    RedisClient redisClient;
+    private RedisClient redisClient;
+    private ReactiveRedisClient reactiveRedisClient;
```
Comment (cescoffier) [inline integration-tests/redis-client/src/main/java/io/quarkus/redis/it/RedisWithNamedClientResource.java:22]: I would test both.

File: extensions/redis-client/runtime/src/main/java/io/quarkus/redis/client/RedisClientName.java [hunk 2]
```diff
@@ -26,7 +26,7 @@
  *     RedisClient client;
  * </pre>
  */
-@Target({ ElementType.TYPE, ElementType.METHOD, ElementType.FIELD })
+@Target({ ElementType.TYPE, ElementType.METHOD, ElementType.FIELD, ElementType.PARAMETER })
 @Retention(RUNTIME)
 @Documented
 @Qualifier
```
Comment (cescoffier) [inline extensions/redis-client/runtime/src/main/java/io/quarkus/redis/client/RedisClientName.java:32]: We need @mkouba opinion. The last time I used a qualifier, I heard him shouting at me and I'm living more than 1000 km away from him :-)

It seems ok here, but better check.

**Review by cescoffier — CHANGES_REQUESTED** [review]

File: integration-tests/redis-client/src/main/java/io/quarkus/redis/it/RedisWithNamedClientResource.java [hunk 3]
```diff
@@ -18,13 +18,15 @@
...
 
     @Inject
-    @RedisClientName("named-client")
-    ReactiveRedisClient reactiveRedisClient;
+    public RedisWithNamedClientResource(@RedisClientName("named-client") ReactiveRedisClient reactiveRedisClient,
+            @RedisClientName("named-client") RedisClient redisClient) {
+        this.reactiveRedisClient = reactiveRedisClient;
+        this.redisClient = redisClient;
+    }
```
Comment (gsmet) [inline integration-tests/redis-client/src/main/java/io/quarkus/redis/it/RedisWithNamedClientResource.java:29]: I would add a specific test rather than fiddling with an existing one.

**Review by gsmet — CHANGES_REQUESTED** [review]
And shouldn't we do exactly the same for `MongoClientName`? I think this one comes from there?

File: integration-tests/redis-client/src/main/java/io/quarkus/redis/it/RedisWithNamedClientResource.java (hunk 3 above)
Comment (machi1990) [reply integration-tests/redis-client/src/main/java/io/quarkus/redis/it/RedisWithNamedClientResource.java:30]: I've changed it the way @cescoffier suggested here https://github.com/quarkusio/quarkus/pull/12902#discussion_r510853452 with constructor and field injection.

File: extensions/redis-client/runtime/src/main/java/io/quarkus/redis/client/RedisClientName.java (hunk 2 above)
Comment (gsmet) [reply extensions/redis-client/runtime/src/main/java/io/quarkus/redis/client/RedisClientName.java:32]: Hmm, this is OK. This is what we use everywhere for named whatever.

**Comment by machi1990** [comment]
> And shouldn't we do exactly the same for `MongoClientName`? I think this one comes from there?

Okay to do it for MongoClientName too. I wanted confirmation first here https://github.com/quarkusio/quarkus/issues/12898#issuecomment-715316176. I can add a separate commit. WDYT? @gsmet

**Comment by gsmet** [comment]
+1 for a separate commit. Let's add separate tests for both to be sure.

File: integration-tests/redis-client/src/main/java/io/quarkus/redis/it/RedisWithNamedClientResource.java (hunk 3 above)
Comment (gsmet) [reply integration-tests/redis-client/src/main/java/io/quarkus/redis/it/RedisWithNamedClientResource.java:30]: It's really better to add an entirely separate test, testing both clients for each injection type.

Just copy/paste the existing one and change the injection.

File: extensions/redis-client/runtime/src/main/java/io/quarkus/redis/client/RedisClientName.java (hunk 2 above)
Comment (mkouba) [reply extensions/redis-client/runtime/src/main/java/io/quarkus/redis/client/RedisClientName.java:32]: This should be fine as the annotation is used as a CDI qualifier (@cescoffier do you spot the difference? Also I don't remember this incident and BTW you live approx. 1000km away from me, or? ;-)

**Comment by machi1990** [comment]
> +1 for a separate commit. Let's add separate tests for both to be sure.

@gsmet suggestions applied. Let me know what you think.

**Review by cescoffier — APPROVED** [review]

**Review by gsmet — APPROVED** [review]

**Comment by xtaixe** [comment]
@machi1990 tested redis (with SNAPSHOT, since it's already merged). Worked fine. Thanks.

**Comment by machi1990** [comment]
@xtaixe thanks for verification.

**Comment by gsmet** [comment]
I haven't backported this one given too many conflicts.

Once again, better not fiddle with existing tests as it makes backporting a nightmare.

**Comment by machi1990** [comment]
> I haven't backported this one given too many conflicts.

Ah I think it's the Mongo related tests that might have caused an issue since I noticed some duplication and decided to deal with them.
 
> Once again, better not fiddle with existing tests as it makes backporting a nightmare.

Noted. Sorry for the nightmare.
