### PR TITLE
Warn when a profile aware configuration file cannot be loaded due to the missing main configuration file

### LINKED ISSUE #44871: Fail or warn on build when `application.properties`/`application.yaml` is missing but `application-<profile>.properties`/`application-<profile>.yaml` is present
### Description

When using profile aware files, we require the main file also to be present: https://quarkus.io/guides/config-reference#profile-aware-files

There's an actual reason for that, see here for an explanation: https://github.com/quarkusio/quarkus/issues/37574#issuecomment-2302246885

However:

1. This requirement is easy to miss, and missing from some relevant places, e.g. YAML config documentation: https://quarkus.io/guides/config-yaml#profiles
2. The behavior when someone missed that requirement can be very confusing... the profile-aware file is simply ignored.

We should probably add a build-time check (at least) that detects profile-aware files, and fails the build (or warns... but I'd personally prefer a failure) if the corresponding `application.properties`/`application.yaml`  file is missing, causing the profile-aware file to be ignored.

See #44807. 

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by radcortez**
- Fixes #44871

### CODE REVIEW

File: core/runtime/src/main/java/io/quarkus/runtime/configuration/ConfigDiagnostic.java [hunk 1]
```diff
@@ -186,22 +186,24 @@ public static Set<String> getErrorKeys() {
     private static final DirectoryStream.Filter<Path> CONFIG_FILES_FILTER = new DirectoryStream.Filter<>() {
         @Override
         public boolean accept(final Path entry) {
-            // Ignore .properties, because we know these are have a default loader in core
-            // Ignore profile files. The loading rules require the main file to be present, so we only need the type
             String filename = entry.getFileName().toString();
-            return Files.isRegularFile(entry) && filename.startsWith("application.") && !filename.endsWith(".properties");
+            // Include application files with any extension and profiled files
+            return Files.isRegularFile(entry)
+                    && filename.length() > 11
```
Comment (geoand) [inline core/runtime/src/main/java/io/quarkus/runtime/configuration/ConfigDiagnostic.java]: Can we replace `11` with a meaningfully named constant? Asking because it's sprinkled in a few places

Comment (radcortez) [reply core/runtime/src/main/java/io/quarkus/runtime/configuration/ConfigDiagnostic.java]: Sure!

**Review by geoand — APPROVED** [review]
