### PR TITLE
Hibernate Validator: status 400 instead of 500 if JAX-RS method is defined in interface

### LINKED ISSUE #11341: @InterceptorBinding based annotation disables ReST validation
**Describe the bug**
1) I have a rest Interface "IGreetingResource" which defines a method annotated with @Valid and @Size
2) there is a rest controller "GreetingResource" which implements "TestApi" annotated with @Override

Validation works like expected unless I add a custom annotation to GreetingResource. That annotation itself is marked with @InterceptorBinding. Validation is not executed anymore unless I add the @Valid annotation explicitly to "GreetingResource". If I remove @InterceptorBinding validation works again so it seems to be connected to @InterceptorBinding.

It also seems to be a difference whether the @Valid annotation is placed in the interface or in the implementing class. In the interface it returns a 500 status code - in the class it returns a 400 which looks better to me. Maybe this issue is a little bit bigger than I describe here.

**Expected behavior**
Validation works.

**Actual behavior**
Validation is deactivated in combination with custom annotation.

**To Reproduce**
1. clone https://github.com/harthorst/quarkus-reproducer-interceptorbinding
2. run it and see the failing GreetingResourceTest

### PR DESCRIPTION
**Pull request by famod**
Follow up to #11429, fixes https://github.com/quarkusio/quarkus/issues/11341#issuecomment-673146350.
See also: https://github.com/quarkusio/quarkus/pull/11429#discussion_r471786768

I basically just gather all JAX-RS methods (whether or not defined in interfaces).

This is my first time working with the Quarkus deployment framework so please bear with me in case I did something stupid or inefficient. 😉

### CODE REVIEW

**Comment by jaikiran** [comment]
Failure looks related:

```
2020-08-21T01:07:48.2222974Z [INFO] Running io.quarkus.it.spring.web.ExceptionHandlingTest
2020-08-21T01:07:53.2554499Z [ERROR] Tests run: 18, Failures: 0, Errors: 1, Skipped: 17, Time elapsed: 5.016 s <<< FAILURE! - in io.quarkus.it.spring.web.ExceptionHandlingTest
2020-08-21T01:07:53.2555409Z [ERROR] io.quarkus.it.spring.web.ExceptionHandlingTest.testUnhandledAnnotatedException  Time elapsed: 0.013 s  <<< ERROR!
2020-08-21T01:07:53.2556172Z java.lang.RuntimeException: 
2020-08-21T01:07:53.2561661Z java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
2020-08-21T01:07:53.2563752Z 	[error]: Build step io.quarkus.hibernate.validator.deployment.HibernateValidatorProcessor#build threw an exception: java.lang.IllegalArgumentException: Not a method
2020-08-21T01:07:53.2564427Z 	at org.jboss.jandex.ClassInfo.asMethod(ClassInfo.java:611)
2020-08-21T01:07:53.2566323Z 	at io.quarkus.hibernate.validator.deployment.HibernateValidatorProcessor.gatherJaxRsMethods(HibernateValidatorProcessor.java:362)
2020-08-21T01:07:53.2568112Z 	at io.quarkus.hibernate.validator.deployment.HibernateValidatorProcessor.build(HibernateValidatorProcessor.java:251)
2020-08-21T01:07:53.2568861Z 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-08-21T01:07:53.2570134Z 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-08-21T01:07:53.2571713Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-08-21T01:07:53.2572370Z 	at java.lang.reflect.Method.invoke(Method.java:498)
2020-08-21T01:07:53.2573493Z 	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:936)
2020-08-21T01:07:53.2574286Z 	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
2020-08-21T01:07:53.2575744Z 	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
2020-08-21T01:07:53.2576915Z 	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
2020-08-21T01:07:53.2578307Z 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
2020-08-21T01:07:53.2579587Z 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
2020-08-21T01:07:53.2580052Z 	at java.lang.Thread.run(Thread.java:748)
2020-08-21T01:07:53.2581294Z 	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
2020-08-21T01:07:53.2581607Z 
```

File: extensions/hibernate-validator/deployment/src/main/java/io/quarkus/hibernate/validator/deployment/MethodValidatedAnnotationsTransformer.java [hunk 1]
```diff
@@ -96,11 +81,10 @@ private boolean requiresValidation(MethodInfo method) {
...
-            if (method.hasAnnotation(jaxrsMethodAnnotation)) {
-                return true;
-            }
-        }
-        return false;
+        ClassInfo clazz = method.declaringClass();
+        return Stream.concat(Stream.of(clazz.name()), clazz.interfaceNames().stream())
+                .anyMatch(dotName -> Optional.ofNullable(jaxRsMethods.get(dotName))
+                        .map(methodNames -> methodNames.contains(method.name()))
+                        .orElse(false));
```
Comment (gsmet) [inline extensions/hibernate-validator/deployment/src/main/java/io/quarkus/hibernate/validator/deployment/MethodValidatedAnnotationsTransformer.java:88]: Please use standard imperative code. This is far less readable.

File: extensions/hibernate-validator/deployment/src/main/java/io/quarkus/hibernate/validator/deployment/HibernateValidatorProcessor.java [hunk 2]
```diff
@@ -327,6 +339,34 @@ private static void contributeMethodsWithInheritedValidation(Map<DotName, Set<St
...
     }
 
+    private static Map<DotName, Set<String>> gatherJaxRsMethods(
+            List<AdditionalJaxRsResourceMethodAnnotationsBuildItem> additionalJaxRsResourceMethodAnnotations,
+            IndexView indexView) {
+        Map<DotName, Set<String>> jaxRsMethods = new HashMap<>();
+
+        Collection<DotName> effectiveJaxRsMethodDefiningAnnotations = new ArrayList<>(
+                JAXRS_METHOD_ANNOTATIONS.length + additionalJaxRsResourceMethodAnnotations.size());
+        effectiveJaxRsMethodDefiningAnnotations.addAll(Arrays.asList(JAXRS_METHOD_ANNOTATIONS));
```
Comment (gsmet) [inline extensions/hibernate-validator/deployment/src/main/java/io/quarkus/hibernate/validator/deployment/HibernateValidatorProcessor.java:349]: I think it would be better conceptually to pass the full list to the method rather than building it inside.

File: extensions/hibernate-validator/deployment/src/main/java/io/quarkus/hibernate/validator/deployment/HibernateValidatorProcessor.java [hunk 3]
```diff
@@ -327,6 +339,34 @@ private static void contributeMethodsWithInheritedValidation(Map<DotName, Set<St
...
+        for (AdditionalJaxRsResourceMethodAnnotationsBuildItem additionalJaxRsResourceMethodAnnotation : additionalJaxRsResourceMethodAnnotations) {
+            effectiveJaxRsMethodDefiningAnnotations.addAll(additionalJaxRsResourceMethodAnnotation.getAnnotationClasses());
+        }
+
+        for (DotName jaxRsAnnotation : effectiveJaxRsMethodDefiningAnnotations) {
+            Collection<AnnotationInstance> annotationInstances = indexView.getAnnotations(jaxRsAnnotation);
+
+            if (annotationInstances.isEmpty()) {
+                continue;
+            }
```
Comment (gsmet) [inline extensions/hibernate-validator/deployment/src/main/java/io/quarkus/hibernate/validator/deployment/HibernateValidatorProcessor.java:359]: You also need to check that the kind of the target is a method.

File: extensions/hibernate-validator/deployment/src/main/java/io/quarkus/hibernate/validator/deployment/HibernateValidatorProcessor.java [hunk 4]
```diff
@@ -327,6 +339,34 @@ private static void contributeMethodsWithInheritedValidation(Map<DotName, Set<St
...
+
+            for (AnnotationInstance annotation : annotationInstances) {
+                MethodInfo method = annotation.target().asMethod();
+                jaxRsMethods.computeIfAbsent(method.declaringClass().name(), k -> new HashSet<String>())
+                        .add(method.name().toString());
```
Comment (gsmet) [inline extensions/hibernate-validator/deployment/src/main/java/io/quarkus/hibernate/validator/deployment/HibernateValidatorProcessor.java:364]: The name is not sufficient, you need to build the signature.

File: extensions/hibernate-validator/deployment/src/main/java/io/quarkus/hibernate/validator/deployment/MethodValidatedAnnotationsTransformer.java [hunk 5]
```diff
@@ -96,11 +81,10 @@ private boolean requiresValidation(MethodInfo method) {
...
-        for (DotName jaxrsMethodAnnotation : effectiveJaxRsMethodDefiningAnnotations) {
-            if (method.hasAnnotation(jaxrsMethodAnnotation)) {
-                return true;
-            }
-        }
-        return false;
+        ClassInfo clazz = method.declaringClass();
+        return Stream.concat(Stream.of(clazz.name()), clazz.interfaceNames().stream())
+                .anyMatch(dotName -> Optional.ofNullable(jaxRsMethods.get(dotName))
+                        .map(methodNames -> methodNames.contains(method.name()))
```
Comment (gsmet) [inline extensions/hibernate-validator/deployment/src/main/java/io/quarkus/hibernate/validator/deployment/MethodValidatedAnnotationsTransformer.java:87]: Same here, you need to use the signature.

File: extensions/hibernate-validator/deployment/src/main/java/io/quarkus/hibernate/validator/deployment/HibernateValidatorProcessor.java [hunk 6]
```diff
@@ -92,6 +94,16 @@
...
 
+    private static final DotName[] JAXRS_METHOD_ANNOTATIONS = {
+            DotName.createSimple("javax.ws.rs.GET"),
+            DotName.createSimple("javax.ws.rs.HEAD"),
+            DotName.createSimple("javax.ws.rs.DELETE"),
+            DotName.createSimple("javax.ws.rs.OPTIONS"),
+            DotName.createSimple("javax.ws.rs.PATCH"),
+            DotName.createSimple("javax.ws.rs.POST"),
+            DotName.createSimple("javax.ws.rs.PUT"),
+    };
```
Comment (gsmet) [inline extensions/hibernate-validator/deployment/src/main/java/io/quarkus/hibernate/validator/deployment/HibernateValidatorProcessor.java:105]: I have another patch moving `ResteasyDotNames` to a common SPI so we will be able to use the constants there rather than have a copy.

File: extensions/hibernate-validator/deployment/src/main/java/io/quarkus/hibernate/validator/deployment/MethodValidatedAnnotationsTransformer.java [hunk 7]
```diff
@@ -96,11 +81,10 @@ private boolean requiresValidation(MethodInfo method) {
...
 
     private boolean isJaxrsMethod(MethodInfo method) {
-        for (DotName jaxrsMethodAnnotation : effectiveJaxRsMethodDefiningAnnotations) {
-            if (method.hasAnnotation(jaxrsMethodAnnotation)) {
-                return true;
-            }
-        }
-        return false;
+        ClassInfo clazz = method.declaringClass();
+        return Stream.concat(Stream.of(clazz.name()), clazz.interfaceNames().stream())
```
Comment (gsmet) [inline extensions/hibernate-validator/deployment/src/main/java/io/quarkus/hibernate/validator/deployment/MethodValidatedAnnotationsTransformer.java:85]: Don't you also need to consider the superclasses?

**Review by gsmet — CHANGES_REQUESTED** [review]
I think this is mostly right, thanks!

I added some comments inline.

File: extensions/hibernate-validator/deployment/src/main/java/io/quarkus/hibernate/validator/deployment/HibernateValidatorProcessor.java (hunk 4 above)
Comment (gsmet) [reply extensions/hibernate-validator/deployment/src/main/java/io/quarkus/hibernate/validator/deployment/HibernateValidatorProcessor.java:364]: Getting the `parameters()` then building something with the `name()` of the type should be good enough.

**Comment by famod** [comment]
CI has been really flaky in the last days. Latest failures don't look related.

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
It needs some more tweaking as we discussed on Zulip but it's already a very good step in the right direction so let's merge it! Thanks!

**Comment by famod** [comment]
Thanks for merging!

> It needs some more tweaking as we discussed on Zulip

I'll extend #11536.
