### PR TITLE
Infinispan Cache Extension

### LINKED ISSUE #29571: Infinispan - unable to cache uni values with @CacheResult annotation
### Describe the bug

I'm trying to use infinispan in a 100% reactive project. The method i need to cache with `@CacheResult` return an `Uni` and when it is called it never completes. It ends if i set `lockTimeout` but my values are never cached.

### Expected behavior

Be able to cache values returned from a method with `Uni` with or without `lockTimeout`.

### Actual behavior

The method never completes without `lockTimeout` parameter, and with it doesn't cache values.

### How to Reproduce?

I've made a reproduction project: https://github.com/Sirz3chs/quarkus-infinispan-client-issue

It just need to create a ressource with a method annotated with `@CacheResult(cacheName = "foo")` that returns an `Uni`.

### Output of `uname -a` or `ver`

Linux 5.4.0-132-generic #148-Ubuntu SMP Mon Oct 17 16:02:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

OpenJDK Runtime Environment Temurin-17+35 (build 17+35)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.14.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)

### Additional information

While testing, i supposed that the `UnresolvedUniValue` in [InfinispanGetWrapper.java](https://github.com/quarkusio/quarkus/blob/main/extensions/infinispan-client/runtime/src/main/java/io/quarkus/infinispan/client/runtime/cache/InfinispanGetWrapper.java) is never cached, so it is never replaced. But i'm not really confident while debugging reactive.

Moreover it seems ifinispan keeps dead transations after my method was called. [out.log](https://github.com/quarkusio/quarkus/files/10122236/out.log)
```
2022-11-30 10:39:13,341 WARN  (ForkJoinPool.commonPool-worker-1) [org.infinispan.server.core.transport.NettyTransport] ISPN005007: [id: 0x91d097c7, L:/172.17.0.2:11222 - R:/172.17.0.1:47424] is still connected to /172.17.0.1:47424
```

### LINKED ISSUE #31896: Integrate Infinispan with the Quarkus Cache
### Description

Implement the SPI
#31865

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by karesti**
* Deprecates custom annotations
* Implements the cache extension SPI

Closes https://github.com/quarkusio/quarkus/issues/31896
Closes https://github.com/quarkusio/quarkus/issues/29571

Depends on https://github.com/quarkusio/quarkus/pull/40038

### CODE REVIEW

File: extensions/infinispan-cache/deployment/src/test/java/io/quarkus/cache/infinispan/InfinispanCacheTest.java [hunk 1]
```diff
@@ -0,0 +1,341 @@
...
+import java.util.concurrent.ThreadPoolExecutor;
+import java.util.concurrent.TimeUnit;
+import java.util.concurrent.atomic.AtomicInteger;
+
+import jakarta.inject.Inject;
+
+import org.infinispan.client.hotrod.RemoteCache;
+import org.infinispan.commons.jdkspecific.ThreadCreator;
+import org.infinispan.commons.util.NullValue;
+import org.jetbrains.annotations.NotNull;
```
Comment (geoand) [inline extensions/infinispan-cache/deployment/src/test/java/io/quarkus/cache/infinispan/InfinispanCacheTest.java:23]: I know that IntelliJ adds these automatically, but we don;t really want them, so please make sure to remove them.

File: extensions/infinispan-client/runtime/src/main/java/io/quarkus/infinispan/client/CacheInvalidate.java [hunk 2]
```diff
@@ -18,11 +18,14 @@
...
  * be executed in the same order: {@link CacheInvalidateAll} first, then {@link CacheInvalidate} and finally
  * {@link CacheResult}.
+ *
+ * @deprecated Use Infinispan Cache Extension
  */
 @InterceptorBinding
 @Target({ ElementType.TYPE, ElementType.METHOD })
 @Retention(RetentionPolicy.RUNTIME)
 @Repeatable(List.class)
+@Deprecated
```
Comment (geoand) [inline extensions/infinispan-client/runtime/src/main/java/io/quarkus/infinispan/client/CacheInvalidate.java:28]: Are these going to be removed?
If so, please add `forRemoval=true`

**Review by geoand — COMMENTED** [review]
I don't know a ton about the Infinispan implementation, but the integration with Quarkus seems to do what we are doing in Redis, so it makes sense

File: extensions/infinispan-cache/deployment/src/test/java/io/quarkus/cache/infinispan/InfinispanCacheTest.java (hunk 1 above)
Comment (karesti) [reply extensions/infinispan-cache/deployment/src/test/java/io/quarkus/cache/infinispan/InfinispanCacheTest.java:23]: oh did not see that thanks!!

File: extensions/infinispan-client/runtime/src/main/java/io/quarkus/infinispan/client/CacheInvalidate.java (hunk 2 above)
Comment (karesti) [reply extensions/infinispan-client/runtime/src/main/java/io/quarkus/infinispan/client/CacheInvalidate.java:28]: yes, need to decide when. next major I guess

File: extensions/infinispan-cache/runtime/src/main/java/io/quarkus/cache/infinispan/runtime/CompositeCacheKeyMarshaller.java [hunk 3]
```diff
@@ -0,0 +1,47 @@
...
+public class CompositeCacheKeyMarshaller implements MessageMarshaller<CompositeCacheKey> {
+    public static final String PACKAGE = "io.quarkus.cache.infinispan.internal";
+    public static final String NAME = "CompositeCacheKey";
+    public static final String FULL_NAME = PACKAGE + "." + NAME;
+    public static final String KEYS = "keys";
+
+    @Override
+    public CompositeCacheKey readFrom(ProtoStreamReader reader) throws IOException {
+        Object[] compositeKeys = reader.readCollection(KEYS, new ArrayList<>(), WrappedMessage.class).stream()
+                .map(we -> we.getValue()).collect(Collectors.toList()).toArray();
```
Comment (wburns) [inline extensions/infinispan-cache/runtime/src/main/java/io/quarkus/cache/infinispan/runtime/CompositeCacheKeyMarshaller.java:26]:
```suggestion
                .map(we -> we.getValue()).toArray();
```

File: extensions/infinispan-cache/runtime/src/main/java/io/quarkus/cache/infinispan/runtime/InfinispanCacheImpl.java [hunk 4]
```diff
@@ -0,0 +1,211 @@
...
+    public Uni<Void> invalidateAll() {
+        return Uni.createFrom().completionStage(remoteCache.clearAsync());
+    }
+
+    @Override
+    public Uni<Void> invalidateIf(Predicate<Object> predicate) {
+        return Uni.createFrom().item(new Supplier<Void>() {
+            @Override
+            public Void get() {
+                remoteCache.keySet().removeIf(predicate);
```
Comment (wburns) [inline extensions/infinispan-cache/runtime/src/main/java/io/quarkus/cache/infinispan/runtime/InfinispanCacheImpl.java:166]: This is blocking, which I am guessing will be an issue :(

Comment (wburns) [reply extensions/infinispan-cache/runtime/src/main/java/io/quarkus/cache/infinispan/runtime/InfinispanCacheImpl.java:166]: Is there a way to mark this as required to be offloaded to a blocking thread?

**Review by wburns — COMMENTED** [review]
I can't really comment on the Quarkus parts as I am out of the loop at this point, but looks good in general to me.

File: extensions/infinispan-cache/runtime/src/main/java/io/quarkus/cache/infinispan/runtime/InfinispanCacheImpl.java (hunk 4 above)
Comment (karesti) [reply extensions/infinispan-cache/runtime/src/main/java/io/quarkus/cache/infinispan/runtime/InfinispanCacheImpl.java:166]: @cescoffier @geoand

Comment (geoand) [reply extensions/infinispan-cache/runtime/src/main/java/io/quarkus/cache/infinispan/runtime/InfinispanCacheImpl.java:166]: Is there to way to have `removeCache.keySetAsync()`?

Comment (karesti) [reply extensions/infinispan-cache/runtime/src/main/java/io/quarkus/cache/infinispan/runtime/InfinispanCacheImpl.java:166]: Unrelated to this PR, I'll look more close, the RedisImpl implementation uses "Keys" 
https://redis.io/commands/keys/

Comment (geoand) [reply extensions/infinispan-cache/runtime/src/main/java/io/quarkus/cache/infinispan/runtime/InfinispanCacheImpl.java:166]: Right, but in the RedisClient we use, all operations are async.

This (and any other cache implementation) will also have to ensure that all Network IO is non-blocking.

Comment (karesti) [reply extensions/infinispan-cache/runtime/src/main/java/io/quarkus/cache/infinispan/runtime/InfinispanCacheImpl.java:166]: I know, I'm just pointing we are using a command that is not recommended for this use case. The command is executed in the server after all

Comment (karesti) [reply extensions/infinispan-cache/runtime/src/main/java/io/quarkus/cache/infinispan/runtime/InfinispanCacheImpl.java:166]: for what is the blocking of the client, as I mentioned above, I believed this method was not blocking underneath. We will do it in another way :)
In any case the this invalidation with predicate, does not look as something that I would use to be honest, but that's my call

Comment (geoand) [reply extensions/infinispan-cache/runtime/src/main/java/io/quarkus/cache/infinispan/runtime/InfinispanCacheImpl.java:166]: > In any case this invalidation with predicate, does not look as something that I would use to be honest, but that's my call

Right, I totally understand that, But for better or worse it's part of the API

Comment (karesti) [reply extensions/infinispan-cache/runtime/src/main/java/io/quarkus/cache/infinispan/runtime/InfinispanCacheImpl.java]: I changed the method using the executor

Comment (geoand) [reply extensions/infinispan-cache/runtime/src/main/java/io/quarkus/cache/infinispan/runtime/InfinispanCacheImpl.java]: I am not sure @cescoffier will like that 🙂

Comment (karesti) [reply extensions/infinispan-cache/runtime/src/main/java/io/quarkus/cache/infinispan/runtime/InfinispanCacheImpl.java]: I would never recommend to use this method xD

**Comment by karesti** [comment]
@cescoffier @wburns @geoand I implemented the method with the executor, wondering if not implementing the method at all would be better

**Comment by geoand** [comment]
I would say that both solutions are far from optimal, but I'll let @cescoffier decide

**Comment by karesti** [comment]
@geoand @cescoffier I'm doing another implementation

**Comment by geoand** [comment]
?

**Comment by karesti** [comment]
@geoand pushing a change soon

**Comment by karesti** [comment]
ready for review again

File: extensions/infinispan-cache/runtime/pom.xml [hunk 5]
```diff
@@ -0,0 +1,83 @@
...
+            <artifactId>quarkus-infinispan-client</artifactId>
+        </dependency>
+        <dependency>
+            <groupId>io.quarkus</groupId>
+            <artifactId>quarkus-cache</artifactId>
+        </dependency>
+        <dependency>
+            <groupId>io.smallrye.reactive</groupId>
+            <artifactId>mutiny-rxjava3</artifactId>
+        </dependency>
```
Comment (geoand) [inline extensions/infinispan-cache/runtime/pom.xml:27]: Is this really required?

Comment (karesti) [reply extensions/infinispan-cache/runtime/pom.xml:27]: I'm going to do another implentation, I forgot about the FlowAdapters

**Comment by karesti** [comment]
@geoand change pushed for invalidateIf

**Review by geoand — COMMENTED** [review]
Seems reasonable to me but we would also need the blessing of @wburns for the Infinispan part

**Review by cescoffier — CHANGES_REQUESTED** [review]

File: integration-tests/infinispan-cache/pom.xml [hunk 6]
```diff
@@ -0,0 +1,144 @@
+<?xml version="1.0" encoding="UTF-8" ?>
+<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
+    <modelVersion>4.0.0</modelVersion>
+    <parent>
+        <groupId>io.quarkus</groupId>
```
[the remark this answers is not in the document]
Comment (karesti) [reply integration-tests/infinispan-cache/pom.xml:5]: I don't know where is that, would you mind pointing out where it is please ?

[the remark this answers is not in the document]
Comment (karesti) [reply integration-tests/infinispan-cache/pom.xml:5]: done

File: .github/native-tests.json [hunk 7]
```diff
@@ -87,7 +87,7 @@
         {
             "category": "Cache",
             "timeout": 65,
```
Comment (cescoffier) [inline .github/native-tests.json:89]: increase the timeout. My rule is 5 minutes per module.

File: extensions/infinispan-cache/deployment/src/test/java/io/quarkus/cache/infinispan/InfinispanCacheTest.java [hunk 8]
```diff
@@ -0,0 +1,339 @@
...
+
+    @Test
+    public void testGetWithParallelCalls() throws Exception {
+        CyclicBarrier barrier = new CyclicBarrier(2);
+        Cache cache = getCache();
+        String id = generateId();
+        Future<Uni<String>> thread1 = fork(() -> cache.get(id, key -> {
+            try {
+                barrier.await(10, TimeUnit.SECONDS);
+                barrier.await(10, TimeUnit.SECONDS);
```
Comment (cescoffier) [inline extensions/infinispan-cache/deployment/src/test/java/io/quarkus/cache/infinispan/InfinispanCacheTest.java:174]: why twice?

File: extensions/infinispan-cache/deployment/src/test/java/io/quarkus/cache/infinispan/InfinispanCacheTest.java [hunk 9]
```diff
@@ -0,0 +1,339 @@
...
+
+    private Cache getCache(int lifespan, int maxidle) {
+        InfinispanCacheInfo info = new InfinispanCacheInfo();
+        info.name = CACHE_NAME;
+        info.lifespan = Optional.of(Duration.ofSeconds(lifespan));
+        info.maxIdle = Optional.of(Duration.ofSeconds(maxidle));
+        return new InfinispanCacheImpl(info, remoteCache);
+    }
+
+    private static Object awaitUni(Uni uni) {
```
Comment (cescoffier) [inline extensions/infinispan-cache/deployment/src/test/java/io/quarkus/cache/infinispan/InfinispanCacheTest.java:336]:
```suggestion
    private static <T> T awaitUni(Uni<T> uni) {
```

File: extensions/infinispan-cache/runtime/src/main/java/io/quarkus/cache/infinispan/runtime/InfinispanCacheImpl.java [hunk 10]
```diff
@@ -0,0 +1,215 @@
...
+                                    });
+                        }
+                    });
+            return resultAsync;
+        }));
+    }
+
+    @Override
+    public Uni<Void> invalidate(Object key) {
+        return Uni.createFrom().completionStage(remoteCache.removeAsync(key));
```
Comment (cescoffier) [inline extensions/infinispan-cache/runtime/src/main/java/io/quarkus/cache/infinispan/runtime/InfinispanCacheImpl.java:156]: That is not correct.
This invokes the "removeAsync" method immediately, and not at subscription time. 

You need `() -> removeCache.removeAsync(key))` (for all methods)

In addition, you may have to deal with the context, as your event is going to be emitted on a  infinispan thread, which is not the caller context. At least add tests (the interceptor is likely going to do that already, but better verify).

File: extensions/infinispan-cache/runtime/src/main/java/io/quarkus/cache/infinispan/runtime/InfinispanCacheImpl.java [hunk 11]
```diff
@@ -0,0 +1,215 @@
...
+
+    @Override
+    public Uni<Void> invalidateIf(Predicate<Object> predicate) {
+        Flow.Publisher<Map.Entry> entriesPublisher = FlowAdapters
+                .toFlowPublisher(remoteCache.publishEntries(Codec27.EMPTY_VALUE_CONVERTER, null, null, 512));
+        return Uni.createFrom().multi(Multi.createFrom().publisher(entriesPublisher)
+                .map(e -> ((Map.Entry<Object, Object>) e).getKey())
+                .filter(key -> predicate.test(key))
+                .onItem()
+                .call(key -> Uni.createFrom().completionStage(remoteCache.removeAsync(key))))
```
Comment (cescoffier) [inline extensions/infinispan-cache/runtime/src/main/java/io/quarkus/cache/infinispan/runtime/InfinispanCacheImpl.java:172]: I thing this can be simplify by merging the `call` and the `map`

File: extensions/infinispan-cache/runtime/src/main/java/io/quarkus/cache/infinispan/runtime/InfinispanCacheImpl.java [hunk 12]
```diff
@@ -0,0 +1,215 @@
...
+            try {
+                return handleFunction.apply(value, null);
+            } catch (Throwable t) {
+                return CompletableFuture.failedFuture(t);
+            }
+        }
+        return stage.handle(handleFunction).thenCompose(Function.identity());
+    }
+
+    public static <R> R join(CompletionStage<R> stage) {
```
Comment (cescoffier) [inline extensions/infinispan-cache/runtime/src/main/java/io/quarkus/cache/infinispan/runtime/InfinispanCacheImpl.java:201]: I don't believe this is the right place for such a dangerous method.

File: extensions/infinispan-cache/runtime/src/main/java/io/quarkus/cache/infinispan/runtime/InfinispanCacheImpl.java [hunk 13]
```diff
@@ -0,0 +1,215 @@
...
+        try {
+            return CompletableFutures.await(stage.toCompletableFuture());
+        } catch (ExecutionException e) {
+            throw new CompletionException(e.getCause());
+        } catch (InterruptedException e) {
+            throw new CompletionException(e);
+        }
+    }
+
+    private static boolean isCompletedSuccessfully(CompletionStage<?> stage) {
```
Comment (cescoffier) [inline extensions/infinispan-cache/runtime/src/main/java/io/quarkus/cache/infinispan/runtime/InfinispanCacheImpl.java:211]: Same here. It should not be there.

**Review by cescoffier — CHANGES_REQUESTED** [review]

File: extensions/infinispan-cache/runtime/src/main/java/io/quarkus/cache/infinispan/runtime/InfinispanCacheImpl.java (hunk 10 above)
Comment (karesti) [reply extensions/infinispan-cache/runtime/src/main/java/io/quarkus/cache/infinispan/runtime/InfinispanCacheImpl.java:156]: There is a new integration test, what else should I add to test about the context ?

File: extensions/infinispan-cache/runtime/src/main/java/io/quarkus/cache/infinispan/runtime/InfinispanCacheImpl.java (hunk 11 above)
Comment (cescoffier) [reply extensions/infinispan-cache/runtime/src/main/java/io/quarkus/cache/infinispan/runtime/InfinispanCacheImpl.java:168]: You can replace the map(r -> null) with .replaceWithNull().

Comment (karesti) [reply extensions/infinispan-cache/runtime/src/main/java/io/quarkus/cache/infinispan/runtime/InfinispanCacheImpl.java:169]: I added replaceWithVoid()

File: extensions/infinispan-cache/deployment/src/test/java/io/quarkus/cache/infinispan/InfinispanCacheTest.java (hunk 8 above)
Comment (karesti) [reply extensions/infinispan-cache/deployment/src/test/java/io/quarkus/cache/infinispan/InfinispanCacheTest.java:181]: this is a test coming from Spring integration in the infinispan repo. As explained by @jabolina one is to first make sure we are inside the lambda, for line 189. The second to wait inside the lambda until we issue the second request on line 192

**Comment by karesti** [comment]
@cescoffier I pushed changes

File: extensions/infinispan-cache/deployment/src/test/java/io/quarkus/cache/infinispan/InfinispanCacheTest.java [hunk 14]
```diff
@@ -0,0 +1,353 @@
...
+import io.quarkus.logging.Log;
+import io.quarkus.test.QuarkusUnitTest;
+import io.smallrye.mutiny.Uni;
+
+public class InfinispanCacheTest {
+
+    @RegisterExtension
+    static final QuarkusUnitTest config = new QuarkusUnitTest()
+            .withEmptyApplication()
+            .withConfigurationResource("empty-application-infinispan-client.properties");
```
Comment (cescoffier) [inline extensions/infinispan-cache/deployment/src/test/java/io/quarkus/cache/infinispan/InfinispanCacheTest.java:43]: We may have a better way to create empty assets, but I can't remember the API.

File: extensions/infinispan-cache/deployment/src/test/java/io/quarkus/cache/infinispan/InfinispanCacheTest.java (hunk 8 above)
Comment (cescoffier) [reply extensions/infinispan-cache/deployment/src/test/java/io/quarkus/cache/infinispan/InfinispanCacheTest.java:181]: I would add that explanation in the code - because you can be sure I would ask the same question in 1 month... or one week, or even maybe tomorrow.

**Review by cescoffier — APPROVED** [review]

**Comment by karesti** [comment]
@cescoffier I'm going to add the comment in the test and push. 
Is there anything else preventing the merge at this point ?

**Review by cescoffier — APPROVED** [review]

**Comment by karesti** [comment]
@geoand hey, do you spot anything missing at this point preventing the merge ?

**Review by geoand — APPROVED** [review]
LGTM
