### PR TITLE
Fix issue with Opentracing and Servlet in native

### LINKED ISSUE #9086: Native Image with Custom Config and OpenTracing
**Describe the bug**
There seems to be a weird combination between custom MP Config Source and Opentracing in Quarkus that fails to run the project in native mode.

**Expected behavior**
Native image should run as normal.

**Actual behavior**
Native image runs fails with:

```
ERROR: Failed to start application
java.util.ServiceConfigurationError: org.eclipse.microprofile.config.spi.ConfigSource: Provider org.jboss.resteasy.microprofile.config.ServletConfigSource could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:581)
	at java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:803)
	at java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:721)
	at java.util.ServiceLoader$3.next(ServiceLoader.java:1394)
	at java.lang.Iterable.forEach(Iterable.java:74)
	at io.smallrye.config.SmallRyeConfigBuilder.discoverSources(SmallRyeConfigBuilder.java:74)
	at io.smallrye.config.SmallRyeConfigBuilder.build(SmallRyeConfigBuilder.java:175)
	at io.quarkus.runtime.generated.Config.readConfig(Config.zig:32805)
	at io.quarkus.deployment.steps.RuntimeConfigSetup.deploy(RuntimeConfigSetup.zig:38)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:94)
	at io.quarkus.runtime.Application.start(Application.java:89)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:90)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:61)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:106)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
Caused by: java.lang.RuntimeException: java.lang.InstantiationException: Type `org.jboss.resteasy.microprofile.config.ServletConfigSourceImpl` can not be instantiated reflectively as it does not have a no-parameter constructor or the no-parameter constructor has not been added explicitly to the native image.
	at org.jboss.resteasy.microprofile.config.BaseServletConfigSource.<init>(BaseServletConfigSource.java:26)
	at org.jboss.resteasy.microprofile.config.ServletConfigSource.<init>(ServletConfigSource.java:21)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:779)
	... 14 more
Caused by: java.lang.InstantiationException: Type `org.jboss.resteasy.microprofile.config.ServletConfigSourceImpl` can not be instantiated reflectively as it does not have a no-parameter constructor or the no-parameter constructor has not been added explicitly to the native image.
	at java.lang.Class.newInstance(DynamicHub.java:796)
	at org.jboss.resteasy.microprofile.config.BaseServletConfigSource.<init>(BaseServletConfigSource.java:23)
	... 17 more

May 05, 2020 12:06:49 PM io.quarkus.runtime.ApplicationLifecycleManager run
ERROR: Error running Quarkus application
java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:307)
	at io.quarkus.runtime.Application.start(Application.java:89)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:90)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:61)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:106)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
Caused by: java.util.ServiceConfigurationError: org.eclipse.microprofile.config.spi.ConfigSource: Provider org.jboss.resteasy.microprofile.config.ServletConfigSource could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:581)
	at java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:803)
	at java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:721)
	at java.util.ServiceLoader$3.next(ServiceLoader.java:1394)
	at java.lang.Iterable.forEach(Iterable.java:74)
	at io.smallrye.config.SmallRyeConfigBuilder.discoverSources(SmallRyeConfigBuilder.java:74)
	at io.smallrye.config.SmallRyeConfigBuilder.build(SmallRyeConfigBuilder.java:175)
	at io.quarkus.runtime.generated.Config.readConfig(Config.zig:32805)
	at io.quarkus.deployment.steps.RuntimeConfigSetup.deploy(RuntimeConfigSetup.zig:38)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:94)
	... 6 more
Caused by: java.lang.RuntimeException: java.lang.InstantiationException: Type `org.jboss.resteasy.microprofile.config.ServletConfigSourceImpl` can not be instantiated reflectively as it does not have a no-parameter constructor or the no-parameter constructor has not been added explicitly to the native image.
	at org.jboss.resteasy.microprofile.config.BaseServletConfigSource.<init>(BaseServletConfigSource.java:26)
	at org.jboss.resteasy.microprofile.config.ServletConfigSource.<init>(ServletConfigSource.java:21)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:779)
	... 14 more
Caused by: java.lang.InstantiationException: Type `org.jboss.resteasy.microprofile.config.ServletConfigSourceImpl` can not be instantiated reflectively as it does not have a no-parameter constructor or the no-parameter constructor has not been added explicitly to the native image.
	at java.lang.Class.newInstance(DynamicHub.java:796)
	at org.jboss.resteasy.microprofile.config.BaseServletConfigSource.<init>(BaseServletConfigSource.java:23)
	... 17 more
```
**To Reproduce**
Sample project here:
https://github.com/radcortez/microprofile-samples

1. Build project with `mvn verify`
2. Move to the folder `services\number-api`.
3. Run mvn verify -Pnative
4. Run ./target/number-api-runner

**Configuration**
```properties
# Add your application.properties here, if applicable.
quarkus.http.port=8081

# Logging
quarkus.log.console.enable=true
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss} %-5p [%c{3.}]] (%t) %s%e%n
quarkus.log.console.level=DEBUG
quarkus.log.console.color=true

# Tracking
quarkus.jaeger.service-name=number-api
quarkus.jaeger.sampler-type=const
quarkus.jaeger.sampler-param=1
quarkus.jaeger.propagation=b3

quarkus.swagger-ui.always-include=true
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
 - Output of `java -version`: openjdk version "11.0.7" 2020-04-14
 - GraalVM version (if different from Java): GraalVM CE 19.3.1 (build 11.0.6+9-jvmci-19.3-b07)
 - Quarkus version or git rev: 1.4.1.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

**Additional context**
If we remove the dependency for `quarkus-smallrye-opentracing`, project runs fine in native. If we remove the registration of the custom Config Source in `org.eclipse.microprofile.config.spi.ConfigSource` it also works. Both together fail with the exception detailed above.

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #9086

### CODE REVIEW

**Comment by geoand** [comment]
cc @radcortez @pavolloffay

**Comment by pavolloffay** [comment]
I cannot review this one, I don't have that deep quarkus knowledge.

**Comment by geoand** [comment]
No worries, I just wanted to make you aware

**Comment by geoand** [comment]
Windows failure is completely unrelated

**Comment by radcortez** [comment]
I can give it a try in the project I was using this.

**Comment by geoand** [comment]
@radcortez I did try this fix against the reproducer you had in the original issue and it fixed it.

File: extensions/smallrye-opentracing/runtime/src/main/java/io/quarkus/smallrye/opentracing/runtime/graal/Target_org_jboss_resteasy_microprofile_config_ServletContextConfigSource.java [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+import org.jboss.resteasy.microprofile.config.ServletContextConfigSource;
+import org.jboss.resteasy.microprofile.config.ServletContextConfigSourceImpl;
+
+import com.oracle.svm.core.annotate.Alias;
+import com.oracle.svm.core.annotate.RecomputeFieldValue;
+import com.oracle.svm.core.annotate.TargetClass;
+
+/**
+ * We need this class to ensure that {@link ServletContextConfigSourceImpl}
+ * isn't loaded unless it's Undertow has been explicitly added.
```
Comment (gsmet) [inline extensions/smallrye-opentracing/runtime/src/main/java/io/quarkus/smallrye/opentracing/runtime/graal/Target_org_jboss_resteasy_microprofile_config_ServletContextConfigSource.java:12]:
```suggestion
 * isn't loaded unless Undertow has been explicitly added.
```

File: extensions/smallrye-opentracing/runtime/src/main/java/io/quarkus/smallrye/opentracing/runtime/graal/Target_org_jboss_resteasy_microprofile_config_ServletContextConfigSource.java [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+ *
+ * This is done because the OpenTracing extension depends on javax.servlet which results in
+ * {@link ServletContextConfigSourceImpl}
+ * being loaded (due to what {@link ServletContextConfigSource} checks for), which in turns leads to the
```
Comment (gsmet) [inline extensions/smallrye-opentracing/runtime/src/main/java/io/quarkus/smallrye/opentracing/runtime/graal/Target_org_jboss_resteasy_microprofile_config_ServletContextConfigSource.java:16]:
```suggestion
 * being loaded (due to what {@link ServletContextConfigSource} checks for), which in turns leads to
```

File: extensions/smallrye-opentracing/runtime/src/main/java/io/quarkus/smallrye/opentracing/runtime/graal/Target_org_jboss_resteasy_microprofile_config_FilterConfigSource.java [hunk 3]
```diff
@@ -0,0 +1,22 @@
+package io.quarkus.smallrye.opentracing.runtime.graal;
+
+import org.jboss.resteasy.microprofile.config.FilterConfigSource;
```
Comment (gsmet) [inline extensions/smallrye-opentracing/runtime/src/main/java/io/quarkus/smallrye/opentracing/runtime/graal/Target_org_jboss_resteasy_microprofile_config_FilterConfigSource.java:3]: I'm not particularly excited to have RESTEasy related substitutions in the opentracing extension?

Shouldn't this be part of the RESTEasy extension itself?

**Review by gsmet — CHANGES_REQUESTED** [review]
Added one important question.

File: extensions/smallrye-opentracing/runtime/src/main/java/io/quarkus/smallrye/opentracing/runtime/graal/Target_org_jboss_resteasy_microprofile_config_FilterConfigSource.java (hunk 3 above)
Comment (geoand) [reply extensions/smallrye-opentracing/runtime/src/main/java/io/quarkus/smallrye/opentracing/runtime/graal/Target_org_jboss_resteasy_microprofile_config_FilterConfigSource.java:3]: It wouldn't hurt, but it's not really necessary because the problem only surfaces because of how OpenTracing relies on some servlet stuff being available.
IMHO, we should leave it here, but keep it mind for the future (but I seriously doubt it would ever be needed because we would have long have run into the problem).

Comment (gsmet) [reply extensions/smallrye-opentracing/runtime/src/main/java/io/quarkus/smallrye/opentracing/runtime/graal/Target_org_jboss_resteasy_microprofile_config_FilterConfigSource.java:3]: I suppose I'll keep my "I told you so" for later :).

**Review by gsmet — APPROVED** [review]

File: extensions/smallrye-opentracing/runtime/src/main/java/io/quarkus/smallrye/opentracing/runtime/graal/Target_org_jboss_resteasy_microprofile_config_FilterConfigSource.java (hunk 3 above)
Comment (geoand) [reply extensions/smallrye-opentracing/runtime/src/main/java/io/quarkus/smallrye/opentracing/runtime/graal/Target_org_jboss_resteasy_microprofile_config_FilterConfigSource.java:3]: Well you know that if it happens, I'll fix it ASAP :)
