### PR TITLE
Reflect all of DescriptorProtos

### LINKED ISSUE #52436: Running Grpc in native throw `missing method "getCtype"`
### Describe the bug

When running one of our test which tests the grpc enum serverside error logging (overwrite of `triggerEnumError`) the `io.grpc.StatusRuntimeException: UNKNOWN: java.lang.IllegalStateException - Generated message class "com.google.protobuf.DescriptorProtos$FieldOptions" missing method "getCtype".` is thrown. This happening only with main and not the 3.31.2

Please see the reproducer for more details and code

### Expected behavior

Work without throwing the `missing method "getCtype"`

### Actual behavior

```
io.grpc.StatusRuntimeException: UNKNOWN: java.lang.IllegalStateException - Generated message class "com.google.protobuf.DescriptorProtos$FieldOptions" missing method "getCtype".
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:368)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:349)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:174)
        at org.acme.demo.DemoGrpc$DemoBlockingStub.triggerEnumError(DemoGrpc.java:168)
        at org.acme.GreetingResourceIT.testHelloEndpoint(GreetingResourceIT.java:41)
```

### How to Reproduce?

1. `git clone -b grpc-getctype https://github.com/jedla97/quarkus-reproducers.git`
2. `cd quarkus-reproducers`
3. `quarkus build -Dnative`
4. The error is shown when running the test

### Output of `uname -a` or `ver`

Linux fedowa 6.18.6-200.fc43.x86_64 #1 SMP PREEMPT_DYNAMIC Sun Jan 18 18:57:00 UTC 2026 x86_64 GNU/Linux

### Output of `java -version`

_No response_

### Mandrel or GraalVM version (if different from Java)

quay.io/quarkus/ubi9-quarkus-mandrel-builder-image:jdk-25, quay.io/quarkus/ubi9-quarkus-mandrel-builder-image:jdk-21

### Quarkus version or git rev

main

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by alesj**
In native all info from protobuf DescriptorProtos is erased, but it looks like it is used / needed when accessing protobuf enums.

This fixes #52436 issue.

### CODE REVIEW

File: extensions/grpc-common/deployment/src/main/java/io/quarkus/grpc/common/deployment/GrpcCommonProcessor.java [hunk 1]
```diff
@@ -67,6 +70,9 @@ public void configureNativeExecutable(CombinedIndexBuildItem combinedIndex,
                     .build());
         }
 
+        // reflect all of it -- it's a lot
+        reflectiveClasses(reflectiveClass, combinedIndex.getComputingIndex(), GrpcDotNames.DESRIPTOR_PROTOS);
```
Comment (geoand) [inline extensions/grpc-common/deployment/src/main/java/io/quarkus/grpc/common/deployment/GrpcCommonProcessor.java]: I'm pretty sure you don't need the computing index

Comment (alesj) [reply extensions/grpc-common/deployment/src/main/java/io/quarkus/grpc/common/deployment/GrpcCommonProcessor.java]: I had plain index before, hence the NPE check ... let me try again ...

**Comment by alesj** [comment]
@geoand I have `methods` atm and the reported issue now work ... should I, to just make sure, also add `fields` to reflection ... ?

File: extensions/grpc-common/deployment/src/main/java/io/quarkus/grpc/common/deployment/GrpcCommonProcessor.java (hunk 1 above)
Comment (alesj) [reply extensions/grpc-common/deployment/src/main/java/io/quarkus/grpc/common/deployment/GrpcCommonProcessor.java]: Yup, I need computing index ... from

```
        ClassInfo classByName = index.getClassByName(className);
        if (classByName == null) {
            System.out.println("className = " + className);
```

I get this when I use the plain index 

```
[INFO] --- quarkus:999-SNAPSHOT:build (default-build) @ quarkus-reproducers ---
className = com.google.protobuf.DescriptorProtos
```

... and the test / reproducer fails

**Review by geoand — APPROVED** [review]

File: extensions/grpc-common/deployment/src/main/java/io/quarkus/grpc/common/deployment/GrpcDotNames.java [hunk 2]
```diff
@@ -15,6 +16,7 @@ public class GrpcDotNames {
     static final DotName MESSAGE_BUILDER = DotName.createSimple(GeneratedMessage.Builder.class.getName());
     static final DotName MESSAGE_BUILDER_V3 = DotName.createSimple(GeneratedMessageV3.Builder.class.getName());
     static final DotName PROTOCOL_MESSAGE_ENUM = DotName.createSimple(ProtocolMessageEnum.class.getName());
+    static final DotName DESRIPTOR_PROTOS = DotName.createSimple(DescriptorProtos.class.getName());
```
Comment (cescoffier) [inline extensions/grpc-common/deployment/src/main/java/io/quarkus/grpc/common/deployment/GrpcDotNames.java]:
```suggestion
    static final DotName DESCRIPTOR_PROTOS = DotName.createSimple(DescriptorProtos.class.getName());
```

File: extensions/grpc-common/deployment/src/main/java/io/quarkus/grpc/common/deployment/GrpcCommonProcessor.java [hunk 3]
```diff
@@ -67,6 +69,9 @@ public void configureNativeExecutable(CombinedIndexBuildItem combinedIndex,
                     .build());
         }
 
+        // reflect all of it -- it's a lot
+        reflectiveClasses(reflectiveClass, combinedIndex, GrpcDotNames.DESRIPTOR_PROTOS);
```
Comment (cescoffier) [inline extensions/grpc-common/deployment/src/main/java/io/quarkus/grpc/common/deployment/GrpcCommonProcessor.java]:
```suggestion
        reflectiveClasses(reflectiveClass, combinedIndex, GrpcDotNames.DESCRIPTOR_PROTOS);
```

**Review by cescoffier — CHANGES_REQUESTED** [review]

File: extensions/grpc-common/deployment/src/main/java/io/quarkus/grpc/common/deployment/GrpcDotNames.java (hunk 2 above)
Comment (alesj) [reply extensions/grpc-common/deployment/src/main/java/io/quarkus/grpc/common/deployment/GrpcDotNames.java]: Fixed, good catch @cescoffier !

**Review by gsmet — COMMENTED** [review]
I think what you want is to index the descriptor protos class. There’s a build item for that but I’m on my phone. Something like AdditionalIndexedClassBuildItem. 

Once this is done I think you can use the regular index as I don’t see the computing index bringing anything. 

Also you say there are a lot? There’s no way to easily know at build time which ones will be useful?

Also it is possible to add custom ones?

**Comment by alesj** [comment]
> I think what you want is to index the descriptor protos class. There’s a build item for that but I’m on my phone. Something like AdditionalIndexedClassBuildItem.
> 
> Once this is done I think you can use the regular index as I don’t see the computing index bringing anything.

OK, let me try this ...
 
> Also you say there are a lot? There’s no way to easily know at build time which ones will be useful?
> 
> Also it is possible to add custom ones?

I tried adding them one-by-one, and I stopped at 7-8 of them, when things were still failing.
I think we need all of the DescriptorProtos inner classes to be reflection-able.

**Comment by alesj** [comment]
> > I think what you want is to index the descriptor protos class. There’s a build item for that but I’m on my phone. Something like AdditionalIndexedClassBuildItem.
> > Once this is done I think you can use the regular index as I don’t see the computing index bringing anything.
> 
> OK, let me try this ...

If I do this
```
    @BuildStep
    public void indexProtobuf(BuildProducer<AdditionalIndexedClassesBuildItem> producer) {
        // add classes as needed
        producer.produce(
                new AdditionalIndexedClassesBuildItem(GrpcDotNames.DESCRIPTOR_PROTOS.toString()));
    }
```

then all inner classes are still missing:
* https://gist.github.com/alesj/69b21ebc120b52c0b552d4fc2974edc2

From
```
        ClassInfo classByName = combinedIndex.getIndex().getClassByName(className);
        if (classByName == null) {
            System.out.println("className = " + className);
            return; // should not be here, but let's just make sure no NPE
        }
```

And that's exactly what I don't want -- listing them one-by-one ...

**Comment by alesj** [comment]
OK, with this

```
    @BuildStep
    public IndexDependencyBuildItem indexProtobuf() {
        return new IndexDependencyBuildItem("com.google.protobuf", "protobuf-java");
    }
```

plain index works as well.

@gsmet should we go with this?

**Comment by geoand** [comment]
That sounds good

**Review by cescoffier — APPROVED** [review]
