### PR TITLE
Arc - Do not validate static members in inner non-static classes for CDI annotations

### LINKED ISSUE #31558: JUnit @Nested Inner Classes with @BeforeAll and @Transactional annotations fail on initialization after upgrading to 2.16.3.Final
### Describe the bug

After upgrading from version `2.15.3.Final` to `2.16.3.Final`, Tests on Inner Classes annotated with `@Nested` and methods annotated with `@BeforeAll` and `@Transactional` fail on initialization.

### Expected behavior

Tests on Inner Classes annotated with JUnit @Nested annotation should keep working as in the previous version (`2.15.3.Final`).

### Actual behavior

After upgrading from version 2.15.3.Final to 2.16.3.Final, Tests on Inner Classes annotated with `@Nested` and methods annotated with `@BeforeAll` and `@Transactional` fail on initialization.

```shell
java.lang.RuntimeException: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#generateResources threw an exception: javax.enterprise.inject.spi.DeploymentException: Found 2 deployment problems: 
[1] The INNER class org.acme.FruitResourceTest$AnotherFruitInnerClass declares an interceptor binding but it must be ignored per CDI rules
[2] The INNER class org.acme.FruitResourceTest$AFruitInnerClass declares an interceptor binding but it must be ignored per CDI rules
	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1231)
	at io.quarkus.arc.processor.BeanProcessor.processValidationErrors(BeanProcessor.java:161)
	at io.quarkus.arc.deployment.ArcProcessor.generateResources(ArcProcessor.java:559)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
	Suppressed: java.lang.IllegalStateException: The INNER class org.acme.FruitResourceTest$AnotherFruitInnerClass declares an interceptor binding but it must be ignored per CDI rules
		at io.quarkus.arc.deployment.WrongAnnotationUsageProcessor.detect(WrongAnnotationUsageProcessor.java:100)
		... 11 more
	Suppressed: java.lang.IllegalStateException: The INNER class org.acme.FruitResourceTest$AFruitInnerClass declares an interceptor binding but it must be ignored per CDI rules
		at io.quarkus.arc.deployment.WrongAnnotationUsageProcessor.detect(WrongAnnotationUsageProcessor.java:100)
		... 11 more
```

## Test Class:
```java
package org.acme;

import io.quarkus.test.common.QuarkusTestResource;
import io.quarkus.test.junit.QuarkusTest;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;

import javax.transaction.Transactional;

import static io.restassured.RestAssured.given;
import static org.hamcrest.CoreMatchers.containsString;
import static org.junit.jupiter.api.TestInstance.Lifecycle.PER_CLASS;

@QuarkusTest
@QuarkusTestResource(PostgresTestResource.class)
@TestInstance(PER_CLASS)
class FruitResourceTest {

    @BeforeAll
    void doSomeImportantStuffBeforeAllTests() {
        //
    }

    @Nested
    @DisplayName("This is a special Test in an Inner class")
    @TestInstance(PER_CLASS)
    class AFruitInnerClass {

        @BeforeAll
        // Commenting out @Transactional annotations makes tests to pass.
        @Transactional
        static void doSomeImportantStuffBeforeAllTests() {
            //
        }

        @Test
        void testGetFruitByIdEndpoint() {
            given()
                    .when().get("/fruits/1")
                    .then()
                    .statusCode(200)
                    .body(containsString("Banana"));
        }
    }

    @Nested
    @DisplayName("This is a special Test in an Inner class")
    @TestInstance(PER_CLASS)
    class AnotherFruitInnerClass {

        @BeforeAll
        // Commenting out @Transactional annotations makes tests to pass.
        @Transactional
        static void doSomeImportantStuffBeforeAllTests() {
            //
        }

        @Test
        void testGetFruitByIdEndpointAgain() {
            given()
                    .when().get("/fruits/1")
                    .then()
                    .statusCode(200)
                    .body(containsString("Banana"));
        }
    }
}

```

### How to Reproduce?

Steps to reproduce the issue:
Reproducer repository: https://github.com/fernandobalieiro/quarkus-nested-test-error

1. `git clone https://github.com/fernandobalieiro/quarkus-nested-test-error`
2. `cd quarkus-nested-test-error`
3. Run `./mvnw clean test `
4. Tests will fail with the following result:
```shell
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   FruitResourceTest » Runtime java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.arc.deployment.ArcProcessor#generateResources threw an exception: javax.enterprise.inject.spi.DeploymentException: Found 2 deployment problems: 
[1] The INNER class org.acme.FruitResourceTest$AnotherFruitInnerClass declares an interceptor binding but it must be ignored per CDI rules
[2] The INNER class org.acme.FruitResourceTest$AFruitInnerClass declares an interceptor binding but it must be ignored per CDI rules
        at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1231)
        at io.quarkus.arc.processor.BeanProcessor.processValidationErrors(BeanProcessor.java:161)
        at io.quarkus.arc.deployment.ArcProcessor.generateResources(ArcProcessor.java:559)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:833)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
        Suppressed: java.lang.IllegalStateException: The INNER class org.acme.FruitResourceTest$AnotherFruitInnerClass declares an interceptor binding but it must be ignored per CDI rules
                at io.quarkus.arc.deployment.WrongAnnotationUsageProcessor.detect(WrongAnnotationUsageProcessor.java:100)
                ... 11 more
        Suppressed: java.lang.IllegalStateException: The INNER class org.acme.FruitResourceTest$AFruitInnerClass declares an interceptor binding but it must be ignored per CDI rules
                at io.quarkus.arc.deployment.WrongAnnotationUsageProcessor.detect(WrongAnnotationUsageProcessor.java:100)
                ... 11 more

[INFO] 
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  15.029 s
[INFO] Finished at: 2023-03-02T17:26:30Z
[INFO] ------------------------------------------------------------------------
```

### Output of `uname -a` or `ver`

Linux neo 5.19.0-35-generic #36~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb 17 15:17:25 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk 17.0.1 2021-10-19
OpenJDK Runtime Environment GraalVM CE 21.3.0 (build 17.0.1+12-jvmci-21.3-b05)
OpenJDK 64-Bit Server VM GraalVM CE 21.3.0 (build 17.0.1+12-jvmci-21.3-b05, mixed mode, sharing)

### GraalVM version (if different from Java)

CE 21.3.0 (build 17.0.1+12-jvmci-21.3-b05, mixed mode, sharing)

### Quarkus version or git rev

2.16.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)
Maven home: /home/neo/.m2/wrapper/dists/apache-maven-3.8.4-bin/52ccbt68d252mdldqsfsn03jlf/apache-maven-3.8.4
Java version: 17.0.2, vendor: GraalVM Community, runtime: /home/neo/.asdf/installs/java/graalvm-22.0.0.2+java17
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.19.0-35-generic", arch: "amd64", family: "unix"

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by manovotn**
Fixes #31558 

In order to properly check this, we now need to verify class-level and member-level annotations separately.

I did not add any tests because with JDK lower than 16, such case would not even compile (static method in non-static inner class).
However, I did test this against the original reproducer to verify that it works as expected.

### CODE REVIEW

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/WrongAnnotationUsageProcessor.java [hunk 1]
```diff
@@ -72,35 +75,72 @@ void detect(ArcConfig config, ApplicationIndexBuildItem applicationIndex, Custom
...
             if (NestingType.ANONYMOUS == nestingType || NestingType.LOCAL == nestingType
                     || (NestingType.INNER == nestingType && !Modifier.isStatic(clazz.flags()))) {
-                // Annotations declared on the class, incl. the annotations added via transformers
-                Collection<AnnotationInstance> classAnnotations = transformedAnnotations.getAnnotations(clazz);
-                if (classAnnotations.isEmpty() && clazz.annotationsMap().isEmpty()) {
-                    continue;
-                }
-                if (scopeAnnotations.isScopeIn(classAnnotations)) {
+                // Annotations declared on the class level, incl. the annotations added via transformers
+                List<AnnotationInstance> classLevelAnnotations = transformedAnnotations.getAnnotations(clazz).stream()
```
Comment (mkouba) [inline extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/WrongAnnotationUsageProcessor.java:79]: There is no need for filtering - `transformedAnnotations.getAnnotations(clazz)` only returns the annotation instances declared on the class.

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/WrongAnnotationUsageProcessor.java [hunk 2]
```diff
@@ -72,35 +75,72 @@ void detect(ArcConfig config, ApplicationIndexBuildItem applicationIndex, Custom
...
+                    // detect interceptor bindings declared at nested class level
                     validationErrors.produce(new ValidationErrorBuildItem(
                             new IllegalStateException(String.format(
                                     "The %s class %s declares an interceptor binding but it must be ignored per CDI rules",
                                     clazz.nestingType().toString(), clazz.name().toString()))));
                 }
+
+                // iterate over methods and verify those
+                // since JDK 16, you can have static method inside inner non-static class - skip those
+                for (MethodInfo methodInfo : clazz.methods()) {
```
Comment (mkouba) [inline extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/WrongAnnotationUsageProcessor.java:97]: Hm, so previously we only detected annotations declared on the class and now we also detect annotations added through transformers, right? I think that the previous check was good enough and it could be reimplemented so that you obtain all annotations from the `clazz.annotationsMap()`, find those that target methods and skip `static` methods. That could be much more efficient but if you think it's important to include transformers then we should maybe also think about inherited methods ;-).

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/WrongAnnotationUsageProcessor.java [hunk 3]
```diff
@@ -72,35 +75,72 @@ void detect(ArcConfig config, ApplicationIndexBuildItem applicationIndex, Custom
...
+                    if (Modifier.isStatic(methodInfo.flags())) {
+                        continue;
+                    }
+                    // annotations declared on method level, incl. the annotations added via transformers
+                    Collection<AnnotationInstance> methodAnnotations = transformedAnnotations.getAnnotations(methodInfo);
+                    if (methodAnnotations.isEmpty()) {
+                        continue;
+                    }
+                    if (Annotations.contains(methodAnnotations, DotNames.OBSERVES)) {
```
Comment (Ladicek) [inline extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/WrongAnnotationUsageProcessor.java:106]: Should also look for `DotNames.OBSERVES_ASYNC` :-)

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/WrongAnnotationUsageProcessor.java (hunk 1 above)
Comment (manovotn) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/WrongAnnotationUsageProcessor.java:79]: Good point, I was too paranoid here

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/WrongAnnotationUsageProcessor.java (hunk 3 above)
Comment (mkouba) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/WrongAnnotationUsageProcessor.java:106]: Good point... although my "educated" guess is that adoption of async observers is rather minimal :D

**Comment by Ladicek** [comment]
There's a module `integration-tests/java-17` that we could add a test to.

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/WrongAnnotationUsageProcessor.java (hunk 2 above)
Comment (mkouba) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/WrongAnnotationUsageProcessor.java:97]: We don't have a test for either so I'm not quite sure about the word "support"...

**Comment by mkouba** [comment]
> There's a module `integration-tests/java-17` that we could add a test to.

Go ahead and send a pull request ;-)

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/WrongAnnotationUsageProcessor.java (hunk 2 above)
Comment (Ladicek) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/WrongAnnotationUsageProcessor.java:97]: In that case, I propose we limit that to interceptors (due to a historical accident, it certainly wasn't intentional, was it?), and reject everything else.

**Comment by Ladicek** [comment]
You're killing me :joy: I was merely commenting on @manovotn's reasoning for why he didn't add a test :-)

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/WrongAnnotationUsageProcessor.java (hunk 2 above)
Comment (manovotn) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/WrongAnnotationUsageProcessor.java:97]: I definitely don't think it's worth the hassle to delve into inherited methods...

> Hm, so previously we only detected annotations declared on the class...

Not really, for observers and producers you are right - for bindings we actually checked both, see [this code](https://github.com/quarkusio/quarkus/blob/main/extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/WrongAnnotationUsageProcessor.java#L95-L97).
I decided to use transformed versions wherever applicable as that makes to code more consistent and foolproof.
However, if you are truly so much against it @mkouba, I could do it the way you suggest :)

Comment (mkouba) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/WrongAnnotationUsageProcessor.java:97]: > In that case, I propose we limit that to interceptors (due to a historical accident, it certainly wasn't intentional, was it?), and reject everything else.

What historical accident do you have in mind??

**Comment by mkouba** [comment]
> You're killing me joy I was merely commenting on @manovotn's reasoning for why he didn't add a test :-)

I see. Then go ahead and send separate pull request anyway ;-)

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/WrongAnnotationUsageProcessor.java (hunk 2 above)
Comment (mkouba) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/WrongAnnotationUsageProcessor.java:97]: > However, if you are truly so much against it @mkouba, I could do it the way you suggest :)

I'm not against it. It's more like _"ok, this seems to be a little bit more correct but does not bring any real benefit"_ ;-)

Comment (Ladicek) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/WrongAnnotationUsageProcessor.java:97]: > > In that case, I propose we limit that to interceptors (due to a historical accident, it certainly wasn't intentional, was it?), and reject everything else.
> 
> What historical accident do you have in mind??

When adding support for `static` methods interception, we certainly didn't have `static` methods on inner classes in mind (because they didn't exist yet). It is a historical accident that interception of `static` methods on inner classes used to work (and then we broke it).

I suggest we keep that case working, but still validate `static` methods on inner classes for observers and producers, because we never intended for those to work, IIUC?

Comment (manovotn) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/WrongAnnotationUsageProcessor.java:97]: > In that case, I propose we limit that to interceptors (due to a historical accident, it certainly wasn't intentional, was it?), and reject everything else.

Supporting static interceptors was intentional (the fact that it now works in this setup is an accident though).
I am also unsure what the status of observers and producers is so you're right we can keep those as it was.
I'll modify the code.

Comment (mkouba) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/WrongAnnotationUsageProcessor.java:95]: > When adding support for static methods interception, we certainly didn't have static methods on inner classes in mind (because they didn't exist yet). It is a historical accident that interception of static methods on inner classes used to work (and then we broke it).

Hm, but the same would apply to observers and producers... except that static producers/observers declared on inner classes never worked because we only find the producers/observers declared on bean classes and inner classes are not considered beans.

So +1 for your proposal!

**Comment by manovotn** [comment]
@mkouba @Ladicek updated as per comments.

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/WrongAnnotationUsageProcessor.java (hunk 2 above)
Comment (mkouba) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/WrongAnnotationUsageProcessor.java:95]: > Supporting static interceptors was intentional (the fact that it now works in this setup is an accident though).

I think that Ladislav meant _"interception of static method declared on inner classes was not intentional"_ ;-)

Comment (Ladicek) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/WrongAnnotationUsageProcessor.java:95]: Yeah, exactly. Sorry, it's Friday and my communication skills are even worse than usual :-)

**Review by Ladicek — APPROVED** [review]

**Comment by manovotn** [comment]
@mkouba can we merge this or are there some additional changes needed?

**Comment by fernandobalieiro** [comment]
Greetings @manovotn! Is there an ETA for this to be released? It seems it's still not part of the new tags.
Regards.

**Comment by manovotn** [comment]
Hello @fernandobalieiro 

It's part of the code since 3.0.0.Alpha5.
If you're still having experiencing problems with this, please create new issue with a reproducer and I'll take a look at it :)

**Comment by manovotn** [comment]
Not adding the backport label seems likely to be the cause :)
@gsmet is it too late now to backport this to 2.16.6?

**Comment by fernandobalieiro** [comment]
Hello again @gsmet  and @manovotn!
Will it be possible to have the backport?

**Comment by manovotn** [comment]
I've added backport label, let's see if @gsmet likes that or not :-)

**Comment by gsmet** [comment]
I suppose we could backport it. I built 2.16.6.Final yesterday though so it will have to wait for the next one.

**Comment by fernandobalieiro** [comment]
OK, no problem :)
Thanks @gsmet!
