### PR TITLE
Qute: do not register TemplateInstance as non-blocking type by default

### LINKED ISSUE #39971: Discrepancy between Quarkus REST behavior and Cache @CacheInvalidateAll behavior
I have the following endpoint using Quarkus REST (I was trying to update from RESTEasy Classic):

```java
    @GET
    @Produces(MediaType.TEXT_HTML)
    @CacheInvalidateAll(cacheName = CacheNames.MILESTONES_CACHE_NAME)
    public TemplateInstance index() throws IOException {
        return Templates.index(gitHub.getOpenMilestones());
    }
```

Note the `TemplateInstance` return type.

When I load this resource, I get:
```
java.lang.IllegalStateException: The current thread cannot be blocked: vert.x-eventloop-thread-1
	at io.smallrye.mutiny.operators.uni.UniBlockingAwait.await(UniBlockingAwait.java:30)
	at io.smallrye.mutiny.groups.UniAwait.atMost(UniAwait.java:65)
	at io.smallrye.mutiny.groups.UniAwait.indefinitely(UniAwait.java:46)
	at io.quarkus.cache.runtime.CacheInvalidateAllInterceptor.invalidateAllBlocking(CacheInvalidateAllInterceptor.java:74)
	at io.quarkus.cache.runtime.CacheInvalidateAllInterceptor.intercept(CacheInvalidateAllInterceptor.java:38)
	at io.quarkus.cache.runtime.CacheInvalidateAllInterceptor_Bean.intercept(Unknown Source)
```

Which seems in line with the code in `CacheInvalidateAllInterceptor`:

```java
    @AroundInvoke
    public Object intercept(InvocationContext invocationContext) throws Exception {
        CacheInterceptionContext<CacheInvalidateAll> interceptionContext = getInterceptionContext(invocationContext,
                CacheInvalidateAll.class, false);

        if (interceptionContext.getInterceptorBindings().isEmpty()) {
            // This should never happen.
            LOGGER.warn(INTERCEPTOR_BINDINGS_ERROR_MSG);
            return invocationContext.proceed();
        }
        ReturnType returnType = determineReturnType(invocationContext.getMethod().getReturnType());
        if (returnType == ReturnType.NonAsync) {
            return invalidateAllBlocking(invocationContext, interceptionContext);

        } else {
            return invalidateAllNonBlocking(invocationContext, interceptionContext, returnType);
        }
    }

// ...

    protected static ReturnType determineReturnType(Class<?> returnType) {
        if (Uni.class.isAssignableFrom(returnType)) {
            return ReturnType.Uni;
        }
        if (CompletionStage.class.isAssignableFrom(returnType)) {
            return ReturnType.CompletionStage;
        }
        return ReturnType.NonAsync;
    }
```

AFAICS, Quarkus REST decides to make the endpoint reactive and `CacheInvalidateAllInterceptor` decides that it's blocking and thus there's a mismatch in behavior.

I'm a bit unsure how we should fix this. I'm also surprised that we don't consider the `@Blocking`/`@NonBlocking` annotations in this code. And same question for handling `Multi`?

I worked around it for now by adding a `@Blocking annotation` to the endpoints.

### PR DESCRIPTION
**Pull request by mkouba**
- make it possible to enable the old behavior (for backrward compatibility)
- deprecate NonBlockingReturnTypeBuildItem
- related to #39971

### CODE REVIEW

File: extensions/resteasy-reactive/rest-qute/deployment/src/main/java/io/quarkus/resteasy/reactive/qute/deployment/RestQuteConfig.java [hunk 1]
```diff
@@ -0,0 +1,22 @@
+package io.quarkus.resteasy.reactive.qute.deployment;
+
+import io.quarkus.runtime.annotations.ConfigPhase;
+import io.quarkus.runtime.annotations.ConfigRoot;
+import io.smallrye.config.ConfigMapping;
+import io.smallrye.config.WithDefault;
+
+@ConfigMapping(prefix = "quarkus.rest-qute")
```
Comment (geoand) [inline extensions/resteasy-reactive/rest-qute/deployment/src/main/java/io/quarkus/resteasy/reactive/qute/deployment/RestQuteConfig.java:8]:
```suggestion
@ConfigMapping(prefix = "quarkus.rest.qute")
```

**Comment by gsmet** [comment]
I don't think it fully resolves #39971 as the cache extension doesn't seem to take into account `@Blocking`/`@NonBlocking` annotations to determine if it should go the reactive way or not (at least not the interceptor I pointed out). (Unless I missed something...).

My understanding is that we should take into account the return type AND the annotations. And probably try to be as in line as possible as what Quarkus REST does.

**Comment by geoand** [comment]
> My understanding is that we should take into account the return type AND the annotations. And probably try to be as in line as possible as what Quarkus REST does.

I am not so sure about this... This would complicate the rules further...
@cescoffier WDYT?

**Comment by mkouba** [comment]
> I don't think it fully resolves #39971 as the cache extension doesn't seem to take into account `@Blocking`/`@NonBlocking` annotations to determine if it should go the reactive way or not (at least not the interceptor I pointed out). (Unless I missed something...).

Ah sorry, yes of course this does not solve the problem in general. I should have used `related to` instead of `resolves`. Will fix it.
  
> My understanding is that we should take into account the return type AND the annotations. And probably try to be as in line as possible as what Quarkus REST does.

If we want to unify the logic we should provide some util classes in the core, e.g. to detect an asynchronous type, or to determine if a method is blocking or not. Right now, every extension does handle this stuff separately. Which is a lot of WET code.

**Review by geoand — APPROVED** [review]

**Comment by cescoffier** [comment]
I'm not totally sure I undersatand the role of that annotation.
If that annotation does an "extra" action, it could detect whether or not we are on an event loop, but should not change the execution model of the called method.

**Comment by mkouba** [comment]
> I'm not totally sure I undersatand the role of that annotation. If that annotation does an "extra" action, it could detect whether or not we are on an event loop, but should not change the execution model of the called method.

Which annotation do you have in mind? `@CacheInvalidateAll`? This PR does not touch the cache interceptors at all. It merely removes the `TemplateInstance` from the set of async types used for REST resources. It's a breaking change and we'll add a note the the migration guide.

**Comment by mkouba** [comment]
FTR: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.10#qute-rest-integration
