### PR TITLE
Fix narayana-jta ClassNotFoundException in native mode

### LINKED ISSUE #10180: ClassNotFoundException when using narayana-jta extension in the native mode
**Describe the bug**
There is a ClassNotFoundException when running the application with the narayana-jta extension in the native mode.

**Expected behavior**
It should not throw a ClassNotFoundException

**Actual behavior**
```
2020-06-23 13:57:13,671 WARN  [com.arj.ats.common] (executor-thread-1) ARJUNA048004: attempt to load com.arjuna.ats.internal.arjuna.utils.SocketProcessId threw ClassNotFound. Wrong classloader?: java.lang.ClassNotFoundException: com.arjuna.ats.internal.arjuna.utils.SocketProcessId
	at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:60)
	at java.lang.Class.forName(DynamicHub.java:1184)
	at com.arjuna.common.internal.util.ClassloadingUtility.loadClass(ClassloadingUtility.java:57)
	at com.arjuna.common.internal.util.ClassloadingUtility.loadClass(ClassloadingUtility.java:85)
	at com.arjuna.common.internal.util.ClassloadingUtility.loadAndInstantiateClass(ClassloadingUtility.java:117)
	at com.arjuna.ats.arjuna.common.CoreEnvironmentBean.getProcessImplementation(CoreEnvironmentBean.java:232)
	at com.arjuna.ats.arjuna.utils.Utility.initDefaultProcess(Utility.java:329)
	at com.arjuna.ats.arjuna.utils.Utility.getProcess(Utility.java:340)
	at com.arjuna.ats.arjuna.utils.Utility.getpid(Utility.java:285)
	at com.arjuna.ats.arjuna.common.Uid.<init>(Uid.java:79)
	at com.arjuna.ats.arjuna.StateManager.<init>(StateManager.java:812)
	at com.arjuna.ats.arjuna.StateManager.<init>(StateManager.java:801)
	at com.arjuna.ats.arjuna.coordinator.BasicAction.<init>(BasicAction.java:72)
	at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.<init>(TwoPhaseCoordinator.java:55)
	at com.arjuna.ats.arjuna.AtomicAction.<init>(AtomicAction.java:74)
	at com.arjuna.ats.internal.jta.transaction.arjunacore.AtomicAction.<init>(AtomicAction.java:38)
	at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.<init>(TransactionImple.java:101)
	at com.arjuna.ats.internal.jta.transaction.arjunacore.BaseTransaction.begin(BaseTransaction.java:98)
	at io.quarkus.narayana.jta.runtime.CDIDelegatingTransactionManager.begin(CDIDelegatingTransactionManager.java:74)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:106)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:92)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:32)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:53)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:26)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(TransactionalInterceptorRequired_Bean.zig:339)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at org.acme.getting.started.GreetingResource_Subclass.hello(GreetingResource_Subclass.zig:160)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:167)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:621)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:487)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:437)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:362)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:439)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:400)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:374)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:67)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:488)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:259)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:160)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:362)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:163)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:245)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:132)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:37)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:94)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:497)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)

2020-06-23 13:57:13,671 WARN  [com.arj.ats.arjuna] (executor-thread-1) ARJUNA012209: Utility.getDefaultProcess failed

```
**To Reproduce**
1. create a simple quickstart example
```
mvn io.quarkus:quarkus-maven-plugin:1.5.2.Final:create     
    -DprojectGroupId=org.acme
    -DprojectArtifactId=getting-started
    -DclassName="org.acme.getting.started.GreetingResource"
    -Dpath="/hello"
cd getting-quickstart
```
2. add the narayana-jta extension
```
mvn quarkus:add-extension -Dextensions="narayana-jta"
```
3. modify the GreetingResource.java to add the Transactional
```java
package org.acme.getting.started;

import javax.transaction.Transactional;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

@Path("/hello")
public class GreetingResource {

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    @Transactional
    public String hello() throws Exception {
        return "hello";
    }
}
```
4. run the native test
```
mvn -Pnative clean install
```

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
```
Linux 192.168.0.110 5.6.19-300.fc32.x86_64 #1 SMP Wed Jun 17 16:10:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
 - Output of `java -version`: 
```
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
```
 - GraalVM version (if different from Java): 
```
graalvm-ce-java8-19.3.1
```
 - Quarkus version or git rev: 
```
1.5.2.Final
```
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/zhfeng/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3
Java version: 1.8.0_252, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.252.b09-1.fc32.x86_64/jre
Default locale: zh_CN, platform encoding: UTF-8
OS name: "linux", version: "5.6.19-300.fc32.x86_64", arch: "amd64", family: "unix"
```

**Additional context**
(Add any other context about the problem here.)

### PR DESCRIPTION
**Pull request by zhfeng**
This replaces https://github.com/quarkusio/quarkus/pull/10429

Fix #10180

### CODE REVIEW

**Comment by Sanne** [comment]
Looks good, thanks @zhfeng . But I think it should it include an integration test? I'd like to check if it doesn indeed solve a problem, and we need to make sure that we have some safeguard against future regressions for the same problem.

**Comment by zhfeng** [comment]
@Sanne sure, I'm working on some integration tests. It just shows the warning message and will not fail the test. The SocketProcessId is a internal implement in the narayana-jta, so I'm investgating to see if there is a way to check the process id.

**Comment by zhfeng** [comment]
Hi @Sanne , I just update to add the TransacionalTestCase in the integration/narayana-jta. You should verify this issue in the native mode by running ```./mvnw -f integration-tests/narayana-jta/pom.xml clean verify -Dnative```. The output looks like
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running io.quarkus.narayana.jta.TransactionalITCase
Executing [/home/zhfeng/work/zhfeng/quarkus/integration-tests/narayana-jta/target/quarkus-integration-test-narayana-jta-999-SNAPSHOT-runner, -Dquarkus.http.port=8081, -Dquarkus.http.ssl-port=8444, -Dtest.url=http://localhost:8081, -Dquarkus.log.file.path=target/target/quarkus.log]
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2020-11-04 23:09:17,339 INFO  [io.quarkus] (main) quarkus-integration-test-narayana-jta 999-SNAPSHOT native (powered by Quarkus 999-SNAPSHOT) started in 0.009s. Listening on: http://0.0.0.0:8081
2020-11-04 23:09:17,339 INFO  [io.quarkus] (main) Profile prod activated. 
2020-11-04 23:09:17,339 INFO  [io.quarkus] (main) Installed features: [cdi, mutiny, narayana-jta, resteasy, smallrye-context-propagation]
2020-11-04 23:09:18,755 WARN  [com.arj.ats.common] (executor-thread-1) ARJUNA048004: attempt to load com.arjuna.ats.internal.arjuna.utils.SocketProcessId threw ClassNotFound. Wrong classloader?: java.lang.ClassNotFoundException: com.arjuna.ats.internal.arjuna.utils.SocketProcessId
	at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:60)
	at java.lang.Class.forName(DynamicHub.java:1214)
	at com.arjuna.common.internal.util.ClassloadingUtility.loadClass(ClassloadingUtility.java:57)
	at com.arjuna.common.internal.util.ClassloadingUtility.loadClass(ClassloadingUtility.java:85)
	at com.arjuna.common.internal.util.ClassloadingUtility.loadAndInstantiateClass(ClassloadingUtility.java:117)
	at com.arjuna.ats.arjuna.common.CoreEnvironmentBean.getProcessImplementation(CoreEnvironmentBean.java:232)
	at com.arjuna.ats.arjuna.utils.Utility.initDefaultProcess(Utility.java:329)
	at com.arjuna.ats.arjuna.utils.Utility.getProcess(Utility.java:340)
	at com.arjuna.ats.arjuna.utils.Utility.getpid(Utility.java:285)
	at com.arjuna.ats.arjuna.common.Uid.<init>(Uid.java:79)
	at com.arjuna.ats.arjuna.StateManager.<init>(StateManager.java:813)
	at com.arjuna.ats.arjuna.StateManager.<init>(StateManager.java:802)
	at com.arjuna.ats.arjuna.coordinator.BasicAction.<init>(BasicAction.java:72)
	at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.<init>(TwoPhaseCoordinator.java:55)
	at com.arjuna.ats.arjuna.AtomicAction.<init>(AtomicAction.java:74)
	at com.arjuna.ats.internal.jta.transaction.arjunacore.AtomicAction.<init>(AtomicAction.java:38)
	at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.<init>(TransactionImple.java:101)
	at com.arjuna.ats.internal.jta.transaction.arjunacore.BaseTransaction.begin(BaseTransaction.java:98)
	at io.quarkus.narayana.jta.runtime.CDIDelegatingTransactionManager.begin(CDIDelegatingTransactionManager.java:74)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:114)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:100)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:32)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:53)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:26)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(TransactionalInterceptorRequired_Bean.zig:340)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at io.quarkus.narayana.jta.TransactionalResource_Subclass.txuid(TransactionalResource_Subclass.zig:160)
	at java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:643)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:507)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:457)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:459)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:419)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:393)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:68)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:133)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:38)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:95)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)

2020-11-04 23:09:18,755 WARN  [com.arj.ats.arjuna] (executor-thread-1) ARJUNA012209: Utility.getDefaultProcess failed
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.668 s <<< FAILURE! - in io.quarkus.narayana.jta.TransactionalITCase
[ERROR] io.quarkus.narayana.jta.TransactionalITCase.test  Time elapsed: 1.275 s  <<< FAILURE!
java.lang.AssertionError: 
1 expectation failed.
Response body doesn't match expectation.
Expected: a string matching the pattern '[:0-9a-z]+'
  Actual: 0:ffffc0a8006e:-1:5fa2c41e:0


[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   TransactionalITCase>TransactionalTestCase.test:16 1 expectation failed.
Response body doesn't match expectation.
Expected: a string matching the pattern '[:0-9a-z]+'
  Actual: 0:ffffc0a8006e:-1:5fa2c41e:0

[INFO] 
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
```
The third part splitted by ":" is **-1** references to the process_id which used by the narayana Uid. Normally this should be larger than zero. But it follows to the default value **-1** if it can not finding the process implemention.

**Comment by zhfeng** [comment]
@mmusgrov can you take a review about the TransationalTestCase ? or is there anything I might misunderstand about the ProcessId ?

**Comment by zhfeng** [comment]
It looks like that we should clean the counts before running the TransactionScopedTest.scopeEventsAreEmitted()

File: integration-tests/narayana-jta/src/main/java/io/quarkus/narayana/jta/TransactionalResource.java [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+@Path("/txuid")
+public class TransactionalResource {
+
+    @GET
+    @Produces(MediaType.TEXT_PLAIN)
+    @Transactional
+    public String txuid() throws javax.transaction.SystemException {
+        Transaction txn = TransactionManager.transactionManager().getTransaction();
+        Uid uid = ((com.arjuna.ats.jta.transaction.Transaction) txn).get_uid();
+        return uid.toString();
```
Comment (mmusgrov) [inline integration-tests/narayana-jta/src/main/java/io/quarkus/narayana/jta/TransactionalResource.java:22]: This test only says that there is a transaction. A more comprehensive test is to check that there is both a transaction and that it is active/running. So if you return `String.valueOf(txn.getStatus());` then that will test much more than the presence of a transaction. Then `TransactionalTestCase` can verify that it was running by checking that the response body has the value  `javax.transaction.Status.STATUS_ACTIVE (ie `given().when().get("/hello").then().body(is("0"));`). Here the value zero corresponds to STATUS_ACTIVE. To make the test clearer you could use the enum constant instead of "0".

**Review by mmusgrov — CHANGES_REQUESTED** [review]

File: integration-tests/narayana-jta/src/main/java/io/quarkus/narayana/jta/TransactionalResource.java (hunk 1 above)
Comment (zhfeng) [reply integration-tests/narayana-jta/src/main/java/io/quarkus/narayana/jta/TransactionalResource.java:22]: Thanks @mmusgrov - good pointing here !
I will add a new test case to check the transaction status.

Comment (mmusgrov) [reply integration-tests/narayana-jta/src/main/java/io/quarkus/narayana/jta/TransactionalResource.java:22]: And if there is no transaction then the spec says that txn.getStatus() will throw SystemException and the test will fail.
Otherwise the PR looks good to go.

Comment (zhfeng) [reply integration-tests/narayana-jta/src/main/java/io/quarkus/narayana/jta/TransactionalResource.java:22]: > if there is no transaction associated with the calling thread then the spec says that txn.getStatus() will throw SystemException

@mmusgrov I can not find this describtion in the JTA spec. Also from the [javaee docs](https://docs.oracle.com/javaee/7/api/javax/transaction/Transaction.html#getStatus--)
```
int getStatus()
       throws SystemException
Obtain the status of the transaction associated with the target Transaction object.
Returns:
The transaction status. If no transaction is associated with the target object, this method returns the Status.NoTransaction value.
Throws:
SystemException - Thrown if the transaction manager encounters an unexpected error condition.
```
Do I miss something ?

Comment (mmusgrov) [reply integration-tests/narayana-jta/src/main/java/io/quarkus/narayana/jta/TransactionalResource.java:22]: Ah yes, it will return Status.NoTransaction so the test will fail which is what we want.
Similarly if the call to getStatus throws a SystemException.

Comment (mmusgrov) [reply integration-tests/narayana-jta/src/main/java/io/quarkus/narayana/jta/TransactionalResource.java:22]: But basically if the call to `getStatus` does not return `STATUS_ACTIVE` then the test will fail because the later test which checks the response will not match.

Comment (zhfeng) [reply integration-tests/narayana-jta/src/main/java/io/quarkus/narayana/jta/TransactionalResource.java:22]: sure, it makes sense.

File: integration-tests/narayana-jta/src/test/java/io/quarkus/narayana/jta/TransactionalTestCase.java [hunk 2]
```diff
@@ -0,0 +1,22 @@
...
+import io.quarkus.test.junit.QuarkusTest;
+import io.restassured.RestAssured;
+
+@QuarkusTest
+@TestHTTPEndpoint(TransactionalResource.class)
+public class TransactionalTestCase {
+
+    @Test
+    public void test() {
+        RestAssured.when().get("/uid").then().assertThat().body(MatchesPattern.matchesPattern("[:0-9a-f]+"));
```
Comment (mmusgrov) [inline integration-tests/narayana-jta/src/test/java/io/quarkus/narayana/jta/TransactionalTestCase.java:18]: Our Uid format is internal and if we change then this will break.
What advantage does testing uid format provide.
However the test that verifies that the `@Transactional` annotation correctly starts a transaction is sufficient,

Comment (zhfeng) [reply integration-tests/narayana-jta/src/test/java/io/quarkus/narayana/jta/TransactionalTestCase.java:18]: Yeah, I see. It is just used to verify the fix for https://github.com/quarkusio/quarkus/issues/10180. We can only see the warning messages when the ```SocketProcessId``` can not be loaded in the native mode, but the test will not fail. So I just use the ```[:0-9a-f]+``` to check there is not ```-1``` in the uid which means the process_id is correct. Do you have any better way to check the value of process_id ?

Comment (mmusgrov) [reply integration-tests/narayana-jta/src/test/java/io/quarkus/narayana/jta/TransactionalTestCase.java:18]: The test method TransactionalResource.status() is marked with `@Transactional` so we will try to start a transaction.
Starting a transaction will then attempt to load the `SocketProcessId` class and if the class is not available then we throw an exception. This will cause the test that invokes `TransactionalResource.status()` to fail which again is what you want.

In other words there is no need for any more tests since the test `TransactionalTestCase#test()` is sufficient.

Note also that the calls `arjPropertyManager.getCoreEnvironmentBean().getProcessImplementation();`, `Utility.getpid()` and `new Uid()` would all do the same but *we do not need to test any of those* since starting a transaction is enough.

Comment (zhfeng) [reply integration-tests/narayana-jta/src/test/java/io/quarkus/narayana/jta/TransactionalTestCase.java:18]: Just as I said, it will not throw an exception if the ```SocketProcessId``` is not available and only show the warning mesage. So the test does not fail. The process_id will follow to ```-1``` and that is the reason I try to check the uid.

Comment (zhfeng) [reply integration-tests/narayana-jta/src/test/java/io/quarkus/narayana/jta/TransactionalTestCase.java:18]: see https://github.com/jbosstm/narayana/blob/master/ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/utils/Utility.java#L287

Comment (mmusgrov) [reply integration-tests/narayana-jta/src/test/java/io/quarkus/narayana/jta/TransactionalTestCase.java:18]: I'm still not clear on why you want to test our process id class, it's private.
You should only be testing that you are able to start a new transaction.

If you really did need to check SocketProcessId (though I don't see any benefit in doing so, notice that we don't test any of the many other classes that we configure in the deployment processor, `NarayanaJtaProcessor`) then something like following would test it:

```java
        try {
            int pid = com.arjuna.ats.arjuna.utils.Utility.getpid();
            Assertions.assertNotEquals(-1, pid);
            Class clazz = arjPropertyManager.getCoreEnvironmentBean().getProcessImplementation().getClass();
            com.arjuna.ats.internal.arjuna.utils.SocketProcessId.class.getName();
            // success
        } catch (Exception e) {
            Assertions.fail("expectation failed", e);
        }
```

But like I say I would advise against testing it like this.

Comment (zhfeng) [reply integration-tests/narayana-jta/src/test/java/io/quarkus/narayana/jta/TransactionalTestCase.java:18]: OK, I undrestand.

Yeah, it should be better to remove this case for Uid in the integration tests since it is just the internal one in Narayana. Also note there is only WARN messages in the surefire tests output when the SocketProcessId can not be loaded in the native mode without this fix, the status test case will not fail.

**Review by mmusgrov — APPROVED** [review]
It's a good fix.

Out of interest will you explain why you excluded all of the transitive dependencies of the artefact `io.quarkus:quarkus-resteasy-deployment`?

**Comment by zhfeng** [comment]
I think it is related to a rule of quarkus to check the order of the deployment dependency building.
```
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce-deployment-deps) @ quarkus-integration-test-narayana-jta ---
[WARNING] Rule 0: io.quarkus.enforcer.RequiresMinimalDeploymentDependency failed with message:
1 *-deployment dependencies are missing/configured incorrectly:
    io.quarkus:quarkus-resteasy-deployment:999-SNAPSHOT

To fix this issue, add the following dependencies to pom.xml:

        <!-- Minimal test dependencies to *-deployment artifacts for consistent build order -->
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-resteasy-deployment</artifactId>
            <version>${project.version}</version>
            <type>pom</type>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>*</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

```

**Comment by zhfeng** [comment]
@Sanne I think this fix is in a good shape for merging, can you take a review please ?

**Comment by gsmet** [comment]
Rebased and squashed.

@Sanne it looks good to me but I prefer having your blessing on this. Thanks.

**Comment by Sanne** [comment]
Looks great!

I noticed we've lost some Narayana optimisations, but that's independently from this PR - I'll follow up separately, need to investigate a bit more.

**Review by Sanne — APPROVED** [review]

**Comment by gsmet** [comment]
Merged, thanks!
