### PR TITLE
Micrometer: Fix Client Filter + tests

### LINKED ISSUE #25951: RestClient errors statuscode are not shown in micrometer
### Describe the bug

When using rest-client reactive with micrometer-registry-prometheus. We can see the following metrics for 200 calls, and the one that have runtime exceptions (not `javax.ws.rs.WebApplicationException` or the ones custom with ExceptionMapper)

```
# HELP http_client_requests_seconds  
# TYPE http_client_requests_seconds summary
http_client_requests_seconds_count{clientName="httpstat.us",method="GET",outcome="SUCCESS",status="200",uri="/{statusCode}",} 1.0
http_client_requests_seconds_sum{clientName="httpstat.us",method="GET",outcome="SUCCESS",status="200",uri="/{statusCode}",} 0.480164288
http_client_requests_seconds_count{clientName="httpstat.us",method="GET",outcome="UNKNOWN",status="UNKNOWN",uri="/{statusCode}",} 1.0
http_client_requests_seconds_sum{clientName="httpstat.us",method="GET",outcome="UNKNOWN",status="UNKNOWN",uri="/{statusCode}",} 2.009740992
# HELP http_client_requests_seconds_max  
# TYPE http_client_requests_seconds_max gauge
http_client_requests_seconds_max{clientName="httpstat.us",method="GET",outcome="SUCCESS",status="200",uri="/{statusCode}",} 0.480164288
http_client_requests_seconds_max{clientName="httpstat.us",method="GET",outcome="UNKNOWN",status="UNKNOWN",uri="/{statusCode}",} 2.009740992
```
The ones for error status codes (4xx/5xx) are missing. 

### Expected behavior

400 errors and others should show in the metrics endpoint. Something like that;
```
# HELP http_client_requests_seconds  
# TYPE http_client_requests_seconds summary
http_client_requests_seconds_count{clientName="httpstat.us",method="GET",outcome="FAILURE",status="400",uri="/{statusCode}",} 1.0
# HELP http_client_requests_seconds_max  
# TYPE http_client_requests_seconds_max gauge
http_client_requests_seconds_max{clientName="httpstat.us",method="GET",outcome="FAILURE",status="400",uri="/{statusCode}",} 0.480164288

```

### Actual behavior

Error status codes are not shown in the metrics

### How to Reproduce?

Reproducer; https://github.com/manofthepeace/quarkus-restclient-micrometer

Steps to reproduce;

1.run the app via mvn quarkus:dev
2.Wait about 10 sec for all calls to go through (there should be 2 stacktraces in the logs)
3. go to http://localhost:8080/q/metrics
4. The reproducer does 3 calls, 
   - 200 OK, will show in metrics endpoint
   - TimeoutException, will show in metrics endpoint
   - 400, wont show in the metrics api

### Output of `uname -a` or `ver`

Darwin Kernel Version 21.5.0

### Output of `java -version`

OpenJDK Runtime Environment Temurin-17.0.3+7 (build 17.0.3+7)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.9.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4

### Additional information

When trying similar test with the resteasy server I can see all status code printed to the metrics.

### PR DESCRIPTION
**Pull request by ebullient**
This replaces the serviceloader + rest client listener with a more straight-forward registration of a client request/response filter that also more closely resembles what OpenTelemetry is doing w/ the rest client.

Also adds tests (deployment & integration-test) to verify that non-SUCCESS outcomes are recorded.

Resolves #25951

### CODE REVIEW

File: extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/binder/RestClientMetricsFilter.java [hunk 1]
```diff
@@ -0,0 +1,104 @@
...
+import io.micrometer.core.instrument.Tags;
+import io.micrometer.core.instrument.Timer;
+import io.quarkus.arc.Arc;
+import io.quarkus.arc.Unremovable;
+
+/**
+ * A client filter for the JAX-RS Client and MicroProfile REST Client that records OpenTelemetry data.
+ */
+@Unremovable
+@Provider
```
Comment (brunobat) [inline extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/binder/RestClientMetricsFilter.java:22]: This will get wired only at runtime when JAX-RS starts... Just thinking out loud.

File: extensions/micrometer/deployment/src/main/java/io/quarkus/micrometer/deployment/binder/HttpBinderProcessor.java [hunk 2]
```diff
@@ -110,12 +105,10 @@ void enableHttpServerSupport(Capabilities capabilities,
     }
 
     @BuildStep(onlyIf = HttpClientBinderEnabled.class)
-    void registerRestClientListener(BuildProducer<NativeImageResourceBuildItem> resource,
-            BuildProducer<ReflectiveClassBuildItem> reflectiveClass) {
-        resource.produce(new NativeImageResourceBuildItem(
-                "META-INF/services/org.eclipse.microprofile.rest.client.spi.RestClientListener"));
-        reflectiveClass
-                .produce(new ReflectiveClassBuildItem(true, true, REST_CLIENT_METRICS_LISTENER));
+    void registerProvider(BuildProducer<AdditionalIndexedClassesBuildItem> additionalIndexed,
```
Comment (brunobat) [inline extensions/micrometer/deployment/src/main/java/io/quarkus/micrometer/deployment/binder/HttpBinderProcessor.java:108]: This replaces a service loader listener responsible by registering the filters by a JAX-RS provider that implements the filters itself, right?
This looks much simpler to me but I fail to understand the priority that will be assigned to this provider...

Comment (ebullient) [reply extensions/micrometer/deployment/src/main/java/io/quarkus/micrometer/deployment/binder/HttpBinderProcessor.java:108]: the priority assigned to the filters registered the other way is _exactly_ why they weren't called. (If you want a simple verification to check this, which I'm happy to have you try!, just remove the priority from the filter registration... )

This mechanism is exactly what the OTel RestClient support is using. I think making instantiation more similar between the two will make it easier to keep them aligned.

Comment (brunobat) [reply extensions/micrometer/deployment/src/main/java/io/quarkus/micrometer/deployment/binder/HttpBinderProcessor.java:108]: ok... efective priority is still subject to research

**Comment by manofthepeace** [comment]
Thank you for tackling this @ebullient. Any chance this could be backported to 2.11?

**Comment by ebullient** [comment]
> Thank you for tackling this @ebullient. Any chance this could be backported to 2.11?

@gsmet -- does it look safe enough to you?

File: extensions/micrometer/deployment/src/main/java/io/quarkus/micrometer/deployment/binder/HttpBinderProcessor.java (hunk 2 above)
Comment (ebullient) [reply extensions/micrometer/deployment/src/main/java/io/quarkus/micrometer/deployment/binder/HttpBinderProcessor.java:108]: Clarified with @radcortez -- OpenTelemetry is no longer trying to use the templated URI for rest client traces, so we don't have an ordering concern between the two any more (as of #26694).

**Review by brunobat — APPROVED** [review]
Checked out the code and debugged the new assertions. 
The PR looks good to me.
