### PR TITLE
Adapts AWT extension to the new dynamic .so loading [JDK 17, 19, 20]

### LINKED ISSUE #31596: ImageIO AWT Quarkus IT test fails with GraalVM 23.0.0-dev build after AWT change
### Describe the bug

The `awt` integration test `io.quarkus.awt.it.ImageDecodersIT.testComplexImages` fails like so:

```
[INFO] Running io.quarkus.awt.it.ImageDecodersIT
Executing "/home/runner/work/mandrel/mandrel/quarkus/integration-tests/awt/target/quarkus-integration-test-awt-999-SNAPSHOT-runner -Dquarkus.http.port=8081 -Dquarkus.http.ssl-port=8444 -Dtest.url=http://localhost:8081 -Dquarkus.log.file.path=/home/runner/work/mandrel/mandrel/quarkus/integration-tests/awt/target/quarkus.log -Dquarkus.log.file.enable=true -Dquarkus.native.native-image-xmx=5g"
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2023-03-03 04:16:16,770 ERROR [io.qua.run.Application] (main) Failed to start application (with profile [prod]): java.lang.UnsatisfiedLinkError: no awt in java.library.path
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.NativeLibrarySupport.loadLibraryRelative(NativeLibrarySupport.java:136)
	at java.base@20-beta/java.lang.ClassLoader.loadLibrary(ClassLoader.java:50)
	at java.base@20-beta/java.lang.Runtime.loadLibrary0(Runtime.java:880)
	at java.base@20-beta/java.lang.System.loadLibrary(System.java:2051)
	at java.desktop@20-beta/java.awt.Toolkit$2.run(Toolkit.java:1384)
	at java.desktop@20-beta/java.awt.Toolkit$2.run(Toolkit.java:1382)
	at java.base@20-beta/java.security.AccessController.executePrivileged(AccessController.java:171)
	at java.base@20-beta/java.security.AccessController.doPrivileged(AccessController.java:319)
	at java.desktop@20-beta/java.awt.Toolkit.loadLibraries(Toolkit.java:1381)
	at java.desktop@20-beta/java.awt.Toolkit.initStatic(Toolkit.java:1419)
	at java.desktop@20-beta/java.awt.Toolkit.<clinit>(Toolkit.java:1393)
	at java.base@20-beta/java.lang.Class.ensureInitialized(DynamicHub.java:550)
	at java.desktop@20-beta/sun.awt.AppContext$2.run(AppContext.java:273)
	at java.desktop@20-beta/sun.awt.AppContext$2.run(AppContext.java:262)
	at java.base@20-beta/java.security.AccessController.executePrivileged(AccessController.java:171)
	at java.base@20-beta/java.security.AccessController.doPrivileged(AccessController.java:319)
	at java.desktop@20-beta/sun.awt.AppContext.initMainAppContext(AppContext.java:262)
	at java.desktop@20-beta/sun.awt.AppContext$3.run(AppContext.java:315)
	at java.desktop@20-beta/sun.awt.AppContext$3.run(AppContext.java:298)
	at java.base@20-beta/java.security.AccessController.executePrivileged(AccessController.java:171)
	at java.base@20-beta/java.security.AccessController.doPrivileged(AccessController.java:319)
	at java.desktop@20-beta/sun.awt.AppContext.getAppContext(AppContext.java:297)
	at java.desktop@20-beta/javax.imageio.spi.IIORegistry.getDefaultInstance(IIORegistry.java:123)
	at io.quarkus.awt.it.Application.init(Application.java:54)
	at io.quarkus.awt.it.Application_Bean.doCreate(Unknown Source)
	at io.quarkus.awt.it.Application_Bean.create(Unknown Source)
	at io.quarkus.awt.it.Application_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:113)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:37)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:34)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:34)
	at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:21)
	at io.quarkus.awt.it.Application_ClientProxy.arc$delegate(Unknown Source)
	at io.quarkus.awt.it.Application_ClientProxy.arc_contextualInstance(Unknown Source)
	at io.quarkus.awt.it.Application_Observer_Synthetic_c3d8ba8d0ca6557d80114d16f47388b320fb6386.notify(Unknown Source)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:344)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:326)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:82)
	at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:142)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:102)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)

Failed to launch the application. The application logs can be found at: /home/runner/work/mandrel/mandrel/quarkus/integration-tests/awt/target/quarkus.log
Error:  Tests run: 33, Failures: 0, Errors: 1, Skipped: 32, Time elapsed: 6.176 s <<< FAILURE! - in io.quarkus.awt.it.ImageDecodersIT
Error:  io.quarkus.awt.it.ImageDecodersIT.testComplexImages(String)[1]  Time elapsed: 0.017 s  <<< ERROR!
java.lang.RuntimeException: java.lang.RuntimeException: Unable to successfully launch process '2573'. Exit code is: '1'.
	at io.quarkus.test.junit.QuarkusIntegrationTestExtension.throwBootFailureException(QuarkusIntegrationTestExtension.java:347)
```

### Expected behavior

Test passes.

### Actual behavior

Test fails.

### How to Reproduce?

Run the `awt` integration-test with a JDK 20-based GraalVM master build. Eg. from here: 

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

`20+36`

### GraalVM version (if different from Java)

master

### Quarkus version or git rev

main

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

Might be related to https://github.com/oracle/graal/pull/6088 that got merged recently.

### PR DESCRIPTION
**Pull request by Karm**
Fixes #31596 (JDK 17)

### CODE REVIEW

File: core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageJNIConfigStep.java [hunk 1]
```diff
@@ -47,6 +49,13 @@ void generateJniConfig(BuildProducer<GeneratedResourceBuildItem> jniConfig,
             root.add(json);
         }
 
+        // Add raw, unescaped, unprocessed nodes for user's fine-grained control.
+        for (JniRuntimeAccessJSONBuildItem jniRuntimeAccessJSONBuildItem : jniRuntimeJSON) {
+            for (String j : jniRuntimeAccessJSONBuildItem.jsonNodes) {
+                root.addRaw(j);
+            }
+        }
+
```
Comment (zakkak) [inline core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageJNIConfigStep.java:58]: @Karm why did you choose to go with raw JSON instead of doing something similar to what we do for reflection?
It feels fragile to me.

https://github.com/quarkusio/quarkus/blob/da625e30ffe4a4875c023b69ca41c133bfacf50a/core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageReflectConfigStep.java#L92-L106

I can prepare a commit on top of this PR to implement the latter if you agree.

**Comment by Karm** [comment]
@zakkak JDK 20 is fine, but I need to add version conditions to maintain compatibility with older 22.x Mandrel/GraalVM....

File: core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageJNIConfigStep.java (hunk 1 above)
Comment (zakkak) [reply core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageJNIConfigStep.java:58]: > How exactly is it more or less fragile than calling method by names one by one?

I find it more fragile in the sense that we rely on hand-crafted raw json. It's not really a blocker for me but I would like to see what others thing as well.

> Please, postpone modifications until I push the JDK 20 port as thre might be more changes....

:+1:

Comment (zakkak) [reply core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageJNIConfigStep.java:58]: cc usual suspects @gsmet @geoand ^^

Comment (geoand) [reply core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageJNIConfigStep.java:58]: I'd really like to avoid the raw json please

Comment (Karm) [reply core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageJNIConfigStep.java:58]: @geoand @zakkak @gsmet  I am not sure I am making a good job at painting the full picture. Let me make an attempt to defend this approach :-D

* You cannot use the current level of granularity, i.e. you have to have a way to mark single methods or even single fields.
* We are using the JSON already, exactly the same format. We are generating it from what extension developers mark with respective builder items.

Now, you spent considerable time with native agent and doing manual work in gdb to arrive at a JSON *x*.

Why would you re-type that JSON snippets native agent got you into some new Quarkus specific API....only to generate JSON *y* (of the exactly the same format you already had in the first place)?

It feels like you have one JSON in your left hand, the same type of JSON in your right hand and somehow you are re-processing it in the middle uselessly.

I propose that we leave this "raw" or "advance" option open so as one can directly inject JSON without having Quarkus re-process it again.

The alternative is that I create an API that allows you to specify single methods and single fields, some arrays of methods and arrays of fields and re-type everything native-agent generates for me...all of it again serialized into the same JSON.

## JSON

You already have some JSON snippets from your native agent, so you make it correct (complete) for Quarkus and copy paste into a file:

```java
@BuildStep
JniRuntimeAccessJSONBuildItem setupAWTInit() throws URISyntaxException, IOException {
    final String jsonArray = Files.readString(Paths.get(getClass().getResource("/jni-json-snippet.json").toURI()));
    // Strip leading [ and trailing ] as we are injecting these elements into an already existing JSON array.
    return new JniRuntimeAccessJSONBuildItem(jsonArray.substring(1, jsonArray.length() - 1));
}
```

The file might look like this:

```json
[
  {
    "name": "java.lang.System",
    "methods": [
      {
        "name": "load",
        "parameterTypes": [
          "java.lang.String"
        ]
      },
      {
        "name": "setProperty",
        "parameterTypes": [
          "java.lang.String",
          "java.lang.String"
        ]
      }
    ]
  },
  {
    "name": "sun.awt.SunToolkit",
    "methods": [
      {
        "name": "awtLock",
        "parameterTypes": []
      },
      {
        "name": "awtLockNotify",
        "parameterTypes": []
      },
      {
        "name": "awtLockNotifyAll",
        "parameterTypes": []
      },
      {
        "name": "awtLockWait",
        "parameterTypes": [
          "long"
        ]
      },
      {
        "name": "awtUnlock",
        "parameterTypes": []
      }
    ],
    "fields": [
      {
        "name": "AWT_LOCK"
      },
      {
        "name": "AWT_LOCK_COND"
      }
    ]
  },
  {
    "name": "sun.awt.X11.XErrorHandlerUtil",
    "methods": [
      {
        "name": "init",
        "parameterTypes": [
          "long"
        ]
      }
    ]
  },
  {
    "name": "sun.awt.X11.XToolkit",
    "allDeclaredFields": true
  },
  {
    "name": "java.lang.Thread",
    "methods": [
      {
        "name": "yield",
        "parameterTypes": []
      }
    ]
  }
]
```
Those nodes are then injected into the bigger jni conf JSON generated by Quarkus.
While doing this work, you are inspecting the generated JSON files anyway, to make sure you are not chasing ghosts.

## API

You have to either manually type stuff from JSON file native agent gave you or have s script that transforms that into this Java code.
An example of an API I came up with minutes ago while eating lunch. Perhaps it could be made more user friendly:

```java
List<Klass> c...
c.add(new KlassBuilder("java.lang.System")
        .addMethods(Map.of("load", List.of("java.lang.String"),
                "setProperty", List.of("java.lang.String", "java.lang.String")))
        .build()
);
c.add(new KlassBuilder("sun.awt.SunToolkit")
        .addMethods(Map.of("awtLock", Collections.emptyList(),
                 "awtLockNotify", Collections.emptyList(),
                "awtLockNotifyAll", Collections.emptyList(),
                "awtLockWait", List.of("long"),
                "awtUnlock", Collections.emptyList()))
        .addFields(List.of("AWT_LOCK", "AWT_LOCK_COND"))
        .build()
);
c.add(new KlassBuilder("sun.awt.X11.XErrorHandlerUtil")
        .addMethod(Map.of("init", List.of("long")))
        .build()
);
c.add(new KlassBuilder("sun.awt.X11.XToolkit")
        .addAllFields()
        .build()
);
c.add(new KlassBuilder("java.lang.Thread")
        .addMethod(Map.of("yield", List.of()))
        .build()
);
```

The thing is that Quarkus then takes this, and generates *the same JSON you already had*.


## All in all

I would very well understand any opposition to "raw JSON" snippets prior to https://github.com/quarkusio/quarkus/pull/29886,
but we are already using JSON config files now.

I hope to be able to contribute to native agent at some point in not so distant future so as it could take over this for Quarkus, at least for JNI access.

If you guys feel like it's a better option, I'll provide the aforementioned API and a jbang script that generates that Java code.

Comment (zakkak) [reply core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageJNIConfigStep.java:58]: @Karm please see https://github.com/Karm/quarkus/pull/106

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java [hunk 2]
```diff
@@ -273,6 +274,24 @@ public NativeImageBuildItem build(NativeConfig nativeConfig, LocalesBuildTimeCon
...
+                                src.getFileName().toString());
+                        log.debugf("Copying a shared lib from %s to %s.", src, dst);
+                        Files.copy(src, dst, StandardCopyOption.REPLACE_EXISTING);
+                    } catch (IOException e) {
+                        log.errorf("Could not copy shared lib from %s to %s. Continuing. Error: %s", src, dst, e);
+                    }
+                });
+            } catch (IOException e) {
+                log.errorf("Could not list files in directory %s. Continuing. Error: %s", outputDir, e);
+            }
```
Comment (zakkak) [inline core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java:293]: Shouldn't we only do this starting with GraalVM / Mandrel 23.0?

Comment (Karm) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java:295]: Indeed. Addressed.

**Comment by Karm** [comment]
@zakkak I've got the version condition in. I'll adapt your PR about removing raw JSON and test again. THX  :+1:

**Comment by Karm** [comment]
I am testing it now again with the latest changes purging raw JSON and there are some backward compatibility issues atm...

|Version|Status|
|-|-|
|GraalVM 22.3.1 Java 17 CE (Java Version 17.0.6+10-jvmci-22.3-b13)|:red_circle:|
|GraalVM 23.0.0-dev Java 17.0.7+4-jvmci-23.0-b09 CE (Java Version 17.0.7+4-jvmci-23.0-b09)|:green_circle:|

File: core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageJNIConfigStep.java (hunk 1 above)
Comment (Karm) [reply core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageJNIConfigStep.java]: Adopted.

File: extensions/awt/runtime/src/main/java/io/quarkus/awt/runtime/JDKSubstitutions.java [hunk 3]
```diff
@@ -25,5 +29,36 @@ private void verifyPFB(ByteBuffer bb) throws FontFormatException {
...
+     * substitution.
+     */
+    @Substitute
+    protected void setOsNameAndVersion() {
+        final Path javaHome = Path.of(System.getProperty("java.io.tmpdir"), "quarkus-awt-tmp-fonts");
+        try {
+            Files.createDirectories(Path.of(javaHome.toString(), "conf", "fonts"));
+            Files.createDirectories(Path.of(javaHome.toString(), "lib"));
+        } catch (IOException e) {
+            throw new RuntimeException("Unable to set tmp java.home for FontConfig Quarkus AWT usage in " + javaHome, e);
```
Comment (gastaldi) [inline extensions/awt/runtime/src/main/java/io/quarkus/awt/runtime/JDKSubstitutions.java:55]:
```suggestion
            throw new UncheckedIOException("Unable to set tmp java.home for FontConfig Quarkus AWT usage in " + javaHome, e);
```

File: extensions/awt/deployment/src/main/java/io/quarkus/awt/deployment/AwtProcessor.java [hunk 4]
```diff
@@ -31,181 +36,242 @@ void nativeImageFeatures(BuildProducer<NativeImageFeatureBuildItem> nativeImageF
...
 
     @BuildStep(onlyIf = NativeOrNativeSourcesBuild.class)
-    void i18NProperties(
+    void resources(
             BuildProducer<NativeImageResourcePatternsBuildItem> resourcePatternsBuildItemBuildProducer) {
         resourcePatternsBuildItemBuildProducer
-                .produce(NativeImageResourcePatternsBuildItem.builder().includePattern(".*/iio-plugin.*properties$").build());
+                .produce(NativeImageResourcePatternsBuildItem.builder()
+                        .includePattern(".*/iio-plugin.*properties$") // Texts for e.g. exceptions strings
+                        .includePattern(".*/.*pf$") // Default colour profiles
```
Comment (jerboaa) [inline extensions/awt/deployment/src/main/java/io/quarkus/awt/deployment/AwtProcessor.java:59]: Please double check with `-H:Log=registerResource:3` whether or not this is in fact needed. It seemed to get included by default for my builds when testing https://github.com/Karm/mandrel-integration-tests/pull/146

**Review by jerboaa — APPROVED** [review]
LGTM, but please double check the color profile resources aren't included by default already.

File: extensions/awt/deployment/src/main/java/io/quarkus/awt/deployment/AwtProcessor.java (hunk 4 above)
Comment (Karm) [reply extensions/awt/deployment/src/main/java/io/quarkus/awt/deployment/AwtProcessor.java:59]: @jerboaa Mandrel Integration Tests don't stress this path at all. The AWT TS here contains a very robust test bank, e.g. https://github.com/quarkusio/quarkus/blob/main/integration-tests/awt/src/test/resources/encoders_test_config.txt

It is in fact needed.

The way I work on PRs like this is that I change things one by one until it passes the test suite, i.e. it fails several encoders tests without it. I stepped it in gdb and I also did some printf "debugging" to confirm and the encoders tests fail due to missing colour profiles files.

That debug session also lead me to an idea of providing my own colour profile files and it will come in a separate PR as I keep having troubles to make it work with Quarkus even in HotSpot mode (works in a simple non Q app though).

**Comment by Karm** [comment]
|Version|Status|
|-|-|
|GraalVM 22.3.1 Java 17 CE (Java Version 17.0.6+10-jvmci-22.3-b13)|:green_circle:|
|GraalVM 22.3.1 Java 19 CE (Java Version 19.0.2+7-jvmci-22.3-b12)|:green_circle:|
|GraalVM 23.0.0-dev Java 17.0.7+4-jvmci-23.0-b09 CE (Java Version 17.0.7+4-jvmci-23.0-b09)|:green_circle:|
|GraalVM 23.0.0-dev Java 19.0.1+10-jvmci-23.0-b04 CE (Java Version 19.0.1+10-jvmci-23.0-b04)|:green_circle:|
|GraalVM 23.0.0-dev Java 20+34-jvmci-23.0-b09 CE (Java Version 20+34-jvmci-23.0-b09)|:green_circle:|
|native-image 17.0.7 2023-04-18
GraalVM Runtime Environment GraalVM CE 17.0.7-dev+4.1 (build 17.0.7+4-jvmci-23.0-b10)
Substrate VM GraalVM CE 17.0.7-dev+4.1 (build 17.0.7+4, serial gc)|:green_circle:|
|native-image 20 2023-03-21
GraalVM Runtime Environment GraalVM CE 20-dev+34.1 (build 20+34-jvmci-23.0-b10)
Substrate VM GraalVM CE 20-dev+34.1 (build 20+34, serial gc)|:green_circle:|
|native-image 23.0.0-deva81ecbe6def2 Mandrel Distribution (Java Version 17.0.8-internal+0-adhoc.karm.jdk17u-dev)|:green_circle:|
|native-image 23.0.0-deva81ecbe6def2 Mandrel Distribution (Java Version 20-internal-adhoc.karm.jdk20)|:green_circle:|
|native-image 22.3.1.0-Final Mandrel Distribution (Java Version 17.0.6+10)|:green_circle:|


I am content with it now. It's IMHO ready for a review @geoand @gastaldi @zakkak

File: core/deployment/src/main/java/io/quarkus/deployment/builditem/nativeimage/JniRuntimeAccessFieldBuildItem.java [hunk 5]
```diff
@@ -0,0 +1,36 @@
+package io.quarkus.deployment.builditem.nativeimage;
+
+import java.lang.reflect.Field;
+
+import org.jboss.jandex.FieldInfo;
+
+import io.quarkus.builder.item.MultiBuildItem;
+
+public final class JniRuntimeAccessFieldBuildItem extends MultiBuildItem {
```
Comment (gastaldi) [inline core/deployment/src/main/java/io/quarkus/deployment/builditem/nativeimage/JniRuntimeAccessFieldBuildItem.java:9]: Mind adding a Javadoc to this class?

File: core/deployment/src/main/java/io/quarkus/deployment/builditem/nativeimage/JniRuntimeAccessMethodBuildItem.java [hunk 6]
```diff
@@ -0,0 +1,93 @@
...
+
+import java.lang.reflect.Method;
+import java.util.Arrays;
+import java.util.Objects;
+
+import org.jboss.jandex.MethodInfo;
+
+import io.quarkus.builder.item.MultiBuildItem;
+
+public final class JniRuntimeAccessMethodBuildItem extends MultiBuildItem {
```
Comment (gastaldi) [inline core/deployment/src/main/java/io/quarkus/deployment/builditem/nativeimage/JniRuntimeAccessMethodBuildItem.java:11]: Javadoc here would be nice too

**Review by gastaldi — APPROVED** [review]
LGTM, it would be nice to have a Javadoc on the new BuildItems

File: core/deployment/src/main/java/io/quarkus/deployment/builditem/nativeimage/JniRuntimeAccessFieldBuildItem.java (hunk 5 above)
Comment (Karm) [reply core/deployment/src/main/java/io/quarkus/deployment/builditem/nativeimage/JniRuntimeAccessFieldBuildItem.java:13]: Done

**Comment by gastaldi** [comment]
Awesome! Please squash them all before we merge it. Good job!

**Comment by geoand** [comment]
Yes, that's a flaky test

File: extensions/awt/deployment/src/main/java/io/quarkus/awt/deployment/AwtProcessor.java (hunk 4 above)
Comment (jerboaa) [reply extensions/awt/deployment/src/main/java/io/quarkus/awt/deployment/AwtProcessor.java:59]: OK. Thanks for checking!

**Review by jerboaa — APPROVED** [review]
LGTM.
