### PR TITLE
Change how JPAConfig cleans up its resources

### LINKED ISSUE #34547: Exception on application shutdown with quarkus-hibernate-search-orm-coordination-outbox-polling
### Describe the bug

When using the extension `quarkus-hibernate-search-orm-coordination-outbox-polling` and stopping the application in dev mode, exception gets thrown, caused by Hibernate Search not being able to create a connection to the database (it needs to in order to re-register agents).

### Expected behavior

No exception.

### Actual behavior

```
2023-07-05 13:57:12,576 ERROR [org.hib.sea.eng.rep.spi.RootFailureCollector] (Shutdown thread) HSEARCH000521: Hibernate Search encountered a failure during %1$s; continuing for now to list all problems, but the process will ultimately be aborted.
Context: %2$s
Failure: [Error Occurred After Shutdown]: org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection [This pool is closed and does not handle any more connections!] [n/a]
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:61)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:108)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:94)
        at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:116)
        at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:143)
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.connection(StatementPreparerImpl.java:51)
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$1.doPrepare(StatementPreparerImpl.java:91)
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:177)
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareStatement(StatementPreparerImpl.java:76)
        at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.lambda$list$0(JdbcSelectExecutorStandardImpl.java:102)
        at org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.executeQuery(DeferredResultSetAccess.java:226)
        at org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.getResultSet(DeferredResultSetAccess.java:163)
        at org.hibernate.sql.results.jdbc.internal.JdbcValuesResultSetImpl.advanceNext(JdbcValuesResultSetImpl.java:254)
        at org.hibernate.sql.results.jdbc.internal.JdbcValuesResultSetImpl.processNext(JdbcValuesResultSetImpl.java:134)
        at org.hibernate.sql.results.jdbc.internal.AbstractJdbcValues.next(AbstractJdbcValues.java:19)
        at org.hibernate.sql.results.internal.RowProcessingStateStandardImpl.next(RowProcessingStateStandardImpl.java:66)
        at org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:178)
        at org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:33)
        at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.doExecuteQuery(JdbcSelectExecutorStandardImpl.java:361)
        at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.executeQuery(JdbcSelectExecutorStandardImpl.java:168)
        at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.list(JdbcSelectExecutorStandardImpl.java:93)
        at org.hibernate.sql.exec.spi.JdbcSelectExecutor.list(JdbcSelectExecutor.java:31)
        at org.hibernate.loader.ast.internal.LoaderHelper.loadByArrayParameter(LoaderHelper.java:215)
        at org.hibernate.loader.ast.internal.EntityBatchLoaderArrayParam.initializeEntities(EntityBatchLoaderArrayParam.java:141)
        at org.hibernate.loader.ast.internal.EntityBatchLoaderArrayParam.load(EntityBatchLoaderArrayParam.java:98)
        at org.hibernate.loader.ast.internal.EntityBatchLoaderArrayParam.load(EntityBatchLoaderArrayParam.java:170)
        at org.hibernate.persister.entity.AbstractEntityPersister.doLoad(AbstractEntityPersister.java:3481)
        at org.hibernate.persister.entity.AbstractEntityPersister.load(AbstractEntityPersister.java:3471)
        at org.hibernate.event.internal.DefaultLoadEventListener.loadFromDatasource(DefaultLoadEventListener.java:581)
        at org.hibernate.event.internal.DefaultLoadEventListener.loadFromCacheOrDatasource(DefaultLoadEventListener.java:567)
        at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:536)
        at org.hibernate.event.internal.DefaultLoadEventListener.doLoad(DefaultLoadEventListener.java:529)
        at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:202)
        at org.hibernate.event.internal.DefaultLoadEventListener.loadWithRegularProxy(DefaultLoadEventListener.java:282)
        at org.hibernate.event.internal.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:237)
        at org.hibernate.event.internal.DefaultLoadEventListener.doOnLoad(DefaultLoadEventListener.java:106)
        at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:78)
        at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:138)
        at org.hibernate.internal.SessionImpl.fireLoadNoChecks(SessionImpl.java:1231)
        at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:1219)
        at org.hibernate.loader.internal.IdentifierLoadAccessImpl.doLoad(IdentifierLoadAccessImpl.java:194)
        at org.hibernate.loader.internal.IdentifierLoadAccessImpl.lambda$load$1(IdentifierLoadAccessImpl.java:160)
        at org.hibernate.loader.internal.IdentifierLoadAccessImpl.perform(IdentifierLoadAccessImpl.java:107)
        at org.hibernate.loader.internal.IdentifierLoadAccessImpl.load(IdentifierLoadAccessImpl.java:160)
        at org.hibernate.internal.SessionImpl.find(SessionImpl.java:2406)
        at org.hibernate.internal.SessionImpl.find(SessionImpl.java:2372)
        at org.hibernate.search.mapper.orm.coordination.outboxpolling.cluster.impl.DefaultAgentRepository.find(DefaultAgentRepository.java:31)
        at org.hibernate.search.mapper.orm.coordination.outboxpolling.cluster.impl.AgentPersister.leaveCluster(AgentPersister.java:61)
        at org.hibernate.search.mapper.orm.coordination.outboxpolling.event.impl.AbstractAgentClusterLink.leaveCluster(AbstractAgentClusterLink.java:138)
        at org.hibernate.search.mapper.orm.coordination.outboxpolling.event.impl.AgentClusterLinkContextProvider.lambda$inTransaction$0(AgentClusterLinkContextProvider.java:31)
        at org.hibernate.search.mapper.orm.coordination.outboxpolling.event.impl.AgentClusterLinkContextProvider.inTransaction(AgentClusterLinkContextProvider.java:42)
        at org.hibernate.search.mapper.orm.coordination.outboxpolling.event.impl.AgentClusterLinkContextProvider.inTransaction(AgentClusterLinkContextProvider.java:30)
        at org.hibernate.search.mapper.orm.coordination.outboxpolling.event.impl.OutboxPollingEventProcessor.leaveCluster(OutboxPollingEventProcessor.java:216)
        at org.hibernate.search.util.common.impl.AbstractCloser.push(AbstractCloser.java:53)
        at org.hibernate.search.util.common.impl.AbstractCloser.push(AbstractCloser.java:33)
        at org.hibernate.search.mapper.orm.coordination.outboxpolling.event.impl.OutboxPollingEventProcessor.stop(OutboxPollingEventProcessor.java:211)
        at org.hibernate.search.util.common.impl.AbstractCloser.push(AbstractCloser.java:53)
        at org.hibernate.search.util.common.impl.AbstractCloser.pushAll(AbstractCloser.java:92)
        at org.hibernate.search.util.common.impl.AbstractCloser.pushAll(AbstractCloser.java:73)
        at org.hibernate.search.mapper.orm.coordination.outboxpolling.impl.OutboxPollingCoordinationStrategy.stop(OutboxPollingCoordinationStrategy.java:197)
        at org.hibernate.search.util.common.impl.AbstractCloser.push(AbstractCloser.java:53)
        at org.hibernate.search.mapper.orm.mapping.impl.HibernateOrmMapping.doStop(HibernateOrmMapping.java:196)
        at org.hibernate.search.util.common.impl.AbstractCloser.push(AbstractCloser.java:53)
        at org.hibernate.search.util.common.impl.AbstractCloser.push(AbstractCloser.java:33)
        at org.hibernate.search.mapper.pojo.mapping.spi.AbstractPojoMappingImplementor.stop(AbstractPojoMappingImplementor.java:68)
        at org.hibernate.search.engine.common.impl.SearchIntegrationImpl.lambda$close$2(SearchIntegrationImpl.java:132)
        at org.hibernate.search.engine.common.impl.SearchIntegrationImpl.stopAllSafely(SearchIntegrationImpl.java:178)
        at org.hibernate.search.engine.common.impl.SearchIntegrationImpl.close(SearchIntegrationImpl.java:131)
        at org.hibernate.search.mapper.orm.mapping.impl.HibernateSearchContextProviderService.close(HibernateSearchContextProviderService.java:36)
        at org.hibernate.search.mapper.orm.bootstrap.impl.HibernateOrmIntegrationBooterImpl.lambda$orchestrateBootAndShutdown$5(HibernateOrmIntegrationBooterImpl.java:156)
        at java.base/java.util.concurrent.CompletableFuture.biAccept(CompletableFuture.java:1386)
        at java.base/java.util.concurrent.CompletableFuture$BiAccept.tryFire(CompletableFuture.java:1355)
        at java.base/java.util.concurrent.CompletableFuture$CoCompletion.tryFire(CompletableFuture.java:1219)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
        at org.hibernate.search.mapper.orm.bootstrap.impl.HibernateSearchSessionFactoryObserver.sessionFactoryClosing(HibernateSearchSessionFactoryObserver.java:50)
        at org.hibernate.internal.SessionFactoryObserverChain.sessionFactoryClosing(SessionFactoryObserverChain.java:48)
        at org.hibernate.internal.SessionFactoryImpl.close(SessionFactoryImpl.java:869)
        at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.close(JPAConfig.java:168)
        at io.quarkus.hibernate.orm.runtime.JPAConfig$Destroyer.destroy(JPAConfig.java:130)
        at io.quarkus.hibernate.orm.runtime.JPAConfig$Destroyer.destroy(JPAConfig.java:125)
        at io.quarkus.hibernate.orm.runtime.JPAConfig_b44400079827d7cae558c390d8d94cadbd711498_Synthetic_Bean.doDestroy(Unknown Source)
        at io.quarkus.hibernate.orm.runtime.JPAConfig_b44400079827d7cae558c390d8d94cadbd711498_Synthetic_Bean.destroy(Unknown Source)
        at io.quarkus.hibernate.orm.runtime.JPAConfig_b44400079827d7cae558c390d8d94cadbd711498_Synthetic_Bean.destroy(Unknown Source)
        at io.quarkus.arc.impl.AbstractInstanceHandle.destroyInternal(AbstractInstanceHandle.java:82)
        at io.quarkus.arc.impl.ContextInstanceHandleImpl.destroy(ContextInstanceHandleImpl.java:21)
        at io.quarkus.arc.impl.AbstractSharedContext.destroy(AbstractSharedContext.java:96)
        at io.quarkus.arc.impl.ArcContainerImpl.shutdown(ArcContainerImpl.java:468)
        at io.quarkus.arc.Arc.shutdown(Arc.java:66)
        at io.quarkus.arc.runtime.ArcRecorder$1.run(ArcRecorder.java:53)
        at io.quarkus.runtime.StartupContext.runAllInReverseOrder(StartupContext.java:84)
        at io.quarkus.runtime.StartupContext.close(StartupContext.java:73)
        at io.quarkus.runner.ApplicationImpl.doStop(Unknown Source)
        at io.quarkus.runtime.Application.stop(Application.java:208)
        at io.quarkus.runtime.Application.stop(Application.java:155)
        at io.quarkus.runtime.ApplicationLifecycleManager$ShutdownHookThread.run(ApplicationLifecycleManager.java:436)
Caused by: java.sql.SQLException: This pool is closed and does not handle any more connections!
        at io.agroal.pool.ConnectionPool.beforeAcquire(ConnectionPool.java:209)
        at io.agroal.pool.ConnectionPool.getConnection(ConnectionPool.java:235)
        at io.agroal.pool.DataSource.getConnection(DataSource.java:86)
        at io.quarkus.hibernate.orm.runtime.customized.QuarkusConnectionProvider.getConnection(QuarkusConnectionProvider.java:23)
        at org.hibernate.internal.NonContextualJdbcConnectionAccess.obtainConnection(NonContextualJdbcConnectionAccess.java:38)
        at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:113)
        ... 92 more

2023-07-05 13:57:12,581 ERROR [org.hib.sea.map.orm.boo.imp.HibernateOrmIntegrationBooterImpl] (Shutdown thread) HSEARCH800035: Unable to shut down Hibernate Search: %1$s [Error Occurred After Shutdown]: org.hibernate.search.util.common.SearchException: HSEARCH000520: Hibernate Search encountered failures during shutdown. Failures:

    Hibernate ORM mapping: 
        failures: 
          - Unable to acquire JDBC Connection [This pool is closed and does not handle any more connections!] [n/a]
        at org.hibernate.search.engine.reporting.spi.RootFailureCollector.checkNoFailure(RootFailureCollector.java:53)
        at org.hibernate.search.engine.common.impl.SearchIntegrationImpl.close(SearchIntegrationImpl.java:168)
        at org.hibernate.search.mapper.orm.mapping.impl.HibernateSearchContextProviderService.close(HibernateSearchContextProviderService.java:36)
        at org.hibernate.search.mapper.orm.bootstrap.impl.HibernateOrmIntegrationBooterImpl.lambda$orchestrateBootAndShutdown$5(HibernateOrmIntegrationBooterImpl.java:156)
        at java.base/java.util.concurrent.CompletableFuture.biAccept(CompletableFuture.java:1386)
        at java.base/java.util.concurrent.CompletableFuture$BiAccept.tryFire(CompletableFuture.java:1355)
        at java.base/java.util.concurrent.CompletableFuture$CoCompletion.tryFire(CompletableFuture.java:1219)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
        at org.hibernate.search.mapper.orm.bootstrap.impl.HibernateSearchSessionFactoryObserver.sessionFactoryClosing(HibernateSearchSessionFactoryObserver.java:50)
        at org.hibernate.internal.SessionFactoryObserverChain.sessionFactoryClosing(SessionFactoryObserverChain.java:48)
        at org.hibernate.internal.SessionFactoryImpl.close(SessionFactoryImpl.java:869)
        at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.close(JPAConfig.java:168)
        at io.quarkus.hibernate.orm.runtime.JPAConfig$Destroyer.destroy(JPAConfig.java:130)
        at io.quarkus.hibernate.orm.runtime.JPAConfig$Destroyer.destroy(JPAConfig.java:125)
        at io.quarkus.hibernate.orm.runtime.JPAConfig_b44400079827d7cae558c390d8d94cadbd711498_Synthetic_Bean.doDestroy(Unknown Source)
        at io.quarkus.hibernate.orm.runtime.JPAConfig_b44400079827d7cae558c390d8d94cadbd711498_Synthetic_Bean.destroy(Unknown Source)
        at io.quarkus.hibernate.orm.runtime.JPAConfig_b44400079827d7cae558c390d8d94cadbd711498_Synthetic_Bean.destroy(Unknown Source)
        at io.quarkus.arc.impl.AbstractInstanceHandle.destroyInternal(AbstractInstanceHandle.java:82)
        at io.quarkus.arc.impl.ContextInstanceHandleImpl.destroy(ContextInstanceHandleImpl.java:21)
        at io.quarkus.arc.impl.AbstractSharedContext.destroy(AbstractSharedContext.java:96)
        at io.quarkus.arc.impl.ArcContainerImpl.shutdown(ArcContainerImpl.java:468)
        at io.quarkus.arc.Arc.shutdown(Arc.java:66)
        at io.quarkus.arc.runtime.ArcRecorder$1.run(ArcRecorder.java:53)
        at io.quarkus.runtime.StartupContext.runAllInReverseOrder(StartupContext.java:84)
        at io.quarkus.runtime.StartupContext.close(StartupContext.java:73)
        at io.quarkus.runner.ApplicationImpl.doStop(Unknown Source)
        at io.quarkus.runtime.Application.stop(Application.java:208)
        at io.quarkus.runtime.Application.stop(Application.java:155)
```

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

We should probably shut down Agroal *after* Hibernate ORM to avoid this exception.

### PR DESCRIPTION
**Pull request by marko-bekhta**
this is an alternative to https://github.com/quarkusio/quarkus/pull/45451.

Adding a priority to shutdown tasks allows us to have a better understanding of how those will be executed. Having the task firing the shutdown event as the first one in that queue seemed reasonable; that way, those handling this event will not be in a situation where something gets shut down before the event handler can use it.

Then, for the ORM-specific part, we add a shutdown task when we create a JPA config, and the cleanup of PUs will only close those that actually correctly started.

I thought about removing the `lastShutdownTasks` queue and just handling that through priority, but then ... I didn't want to change too much 😄 so I've kept it for now.

- Closes: https://github.com/quarkusio/quarkus/issues/34547

### CODE REVIEW

File: core/runtime/src/main/java/io/quarkus/runtime/ShutdownContext.java [hunk 1]
```diff
@@ -12,10 +14,21 @@
  */
 public interface ShutdownContext {
 
-    void addShutdownTask(Runnable runnable);
+    int DEFAULT_PRIORITY = Interceptor.Priority.LIBRARY_AFTER;
```
Comment (yrodiere) [inline core/runtime/src/main/java/io/quarkus/runtime/ShutdownContext.java:17]: I wonder if you need your own `Priority` class with its own set of constants... Because here the "library after" wording is kind of confusing: applying an interceptor "after" the application has quite different implications than what we're doing here. A dedicated class with constants would at least be able to only provide a few constants that make sense, and document them.

File: core/runtime/src/main/java/io/quarkus/runtime/StartupContext.java [hunk 2]
```diff
@@ -20,26 +20,26 @@ public class StartupContext implements Closeable {
     // For example, the raw command line args and ShutdownContext are set when the StartupContext is created
     private final Map<String, Object> values = new HashMap<>();
 
-    private final Deque<Runnable> shutdownTasks = new ConcurrentLinkedDeque<>();
-    private final Deque<Runnable> lastShutdownTasks = new ConcurrentLinkedDeque<>();
+    private final PriorityBlockingQueue<ShutdownTask> shutdownTasks = new PriorityBlockingQueue<>();
+    private final PriorityBlockingQueue<ShutdownTask> lastShutdownTasks = new PriorityBlockingQueue<>();
```
Comment (yrodiere) [inline core/runtime/src/main/java/io/quarkus/runtime/StartupContext.java:24]: From the javadoc of `PriorityBlockingQueue`:

> Operations on this class make no guarantees about the ordering of elements with equal priority

This looks problematic for backwards compatibility, where all tasks will share the same "default" priority, but will (probably) be added in a specific order that just happens to work?

FWIW they also provide a solution in that same javadoc:

> If you need to enforce an ordering, you can define custom classes or comparators that use a secondary key to break ties in primary priority values.

File: integration-tests/hibernate-search-orm-elasticsearch-outbox-polling/pom.xml [hunk 3]
```diff
@@ -50,6 +50,11 @@
             <artifactId>quarkus-junit5</artifactId>
             <scope>test</scope>
         </dependency>
+        <dependency>
+            <groupId>io.quarkus</groupId>
+            <artifactId>quarkus-junit5-internal</artifactId>
+            <scope>test</scope>
+        </dependency>
```
Comment (yrodiere) [inline integration-tests/hibernate-search-orm-elasticsearch-outbox-polling/pom.xml:57]: This is suspicious... integration tests should be like an application, so shouldn't need to rely on "internal" modules?

Did you try putting these tests in `extensions/hibernate-search-orm-elasticsearch-outbox-polling/deployment` instead?

File: extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/HibernateOrmRecorder.java [hunk 4]
```diff
@@ -92,8 +93,18 @@ public DataSourceTenantConnectionResolver get() {
         };
     }
 
-    public Supplier<JPAConfig> jpaConfigSupplier(HibernateOrmRuntimeConfig config) {
-        return () -> new JPAConfig(config);
+    public Supplier<JPAConfig> jpaConfigSupplier(HibernateOrmRuntimeConfig config, ShutdownContext shutdownContext) {
+        return () -> {
+            JPAConfig jpaConfig = new JPAConfig(config);
+            shutdownContext.addShutdownTask(
+                    ShutdownContext.DEFAULT_PRIORITY + 1, new Runnable() {
```
Comment (yrodiere) [inline extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/HibernateOrmRecorder.java:100]: See this is precisely where more descriptive constants would help understand what we're doing :)

File: core/runtime/src/main/java/io/quarkus/runtime/StartupContext.java [hunk 5]
```diff
@@ -97,4 +97,19 @@ public String getCurrentBuildStepName() {
     public void setCurrentBuildStepName(String currentBuildStepName) {
         this.currentBuildStepName = currentBuildStepName;
     }
+
+    private record ShutdownTask(int priority, Runnable action) implements Runnable, Comparable<ShutdownTask> {
+
+        @Override
+        public int compareTo(ShutdownTask task) {
+            // with a regular int compare we'll get the asc ordered queue [1,2,3,4]
+            //  but we want the desc order [4,3,2,1] so that the task with the higher priority is polled first:
```
Comment (yrodiere) [inline core/runtime/src/main/java/io/quarkus/runtime/StartupContext.java:106]: Yeah that needs some javadoc :]

Also... shouldn't it be the opposite for `lastShutdownTasks`... Maybe? Though maybe your change is making that concept obsolete, I don't know.

**Review by yrodiere — COMMENTED** [review]
Thanks.

IMO introducing priorities makes sense and we definitely should go in this direction.

But...

First, we'd need more careful definition/documentation :)

Second, and more importantly, I wonder if this isn't stopping short of what we really need. For example shouldn't we tie startup order to this? It kind of makes sense that components should be shut down in the opposite order they started in, especially for synthetic beans using `.startup()` (like datasources).

We could imagine something like:

1. Startup of components outside of CDI
2. Startup of Quarkus "core" CDI beans
3. Startup of Quarkus "extension" CDI beans, in particular:
    1. Startup of Datasources
    2. Startup of Hibernate
4. Startup of application beans
6. Shutdown of application beans
7. Shutdown of Quarkus "extension" CDI beans, in particular:
    1. Shutdown of Hibernate
    2. Shutdown of Datasources
8. Shutdown of Quarkus "core" CDI beans
9. Shutdown of components outside of CDI

... which looks a lot like `Intereceptor.Priority`, but probably shouldn't be based on it, because I think items 1 & 9 are extra.

What your PR covers is, I think, items 5/6. I'm fine with starting with that, but we should probably raise the issue to others, and perhaps make sure that the priorities we'll pick here will make sense when/if we extend your work to all startup/shutdown.

**Comment by marko-bekhta** [comment]
> First, we'd need more careful definition/documentation :)

1000000000000000000% 😄 I just wanted to push this out as an idea and have something to start the discussion around 😃.

> Second, and more importantly ....

yeah, there are all sorts of flavours for these shutdown things, there are observers for a shutdown event, there are shutdown 
tasks, and then also bean destroyers (if it's a CDI bean...) and maybe something else I'm unaware 😃.

so my thinking here was that on shutdown we:
- fire the shutdown event, so user-defined observers would get a chance to do their work while all the things are not yet closed
- shutdown extensions in a required order. e.g. we know that we want to shutdown ORM while CDI is still up, so we give it a higher priority and keep the CDI shutdown as a last one in this batch. Shutting down CDI will trigger calling all the bean  destroyers (in a random order)
- and then shut down the last batch (things currently in lastShutdownTasks e.g. vertx etc..)

so I'd create a priority range for these groups and then use that.

**Comment by yrodiere** [comment]
> so my thinking here was that on shutdown we:
> 
>     * fire the shutdown event, so user-defined observers would get a chance to do their work while all the things are not yet closed
> 
>     * shutdown extensions in a required order. e.g. we know that we want to shutdown ORM while CDI is still up, so we give it a higher priority and keep the CDI shutdown as a last one in this batch. Shutting down CDI will trigger calling all the bean  destroyers (in a random order)
> 
>     * and then shut down the last batch (things currently in lastShutdownTasks e.g. vertx etc..)
> 
> 
> so I'd create a priority range for these groups and then use that.

Fine by me, but like I said this needs to take into account future changes, because changing these constants later will be painful.

In particular:

1. Make sure the constants would still make sense if we generalized priorities to "startup + shutdown". A bit like interceptors: the priority is more about "nesting" order than about sequential order. So for example a lower priority means startup happens sooner, but shutdown happens later. Or the opposite, whatever makes sense.
2. Make sure priority 0 has special meaning that will stand future evolutions. It could be what gets started up up very first, and shut down very last. It could be application priority.
3. Leave room for Quarkus-defined things that need to start after the app or shut down before it. E.g. Vert.x could start accepting requests after startup observers get called, and stop accepting requests before shutdown observers get called. Theoretically.

With that in mind, something similarly generic to `Interceptor.Priority` might make sense...

```
CORE_BEFORE
EXTENSION_BEFORE
APPLICATION
EXTENSION_AFTER
CORE_AFTER
```

We'd get this startup order:

```
CORE_BEFORE
EXTENSION_BEFORE
APPLICATION
EXTENSION_AFTER
CORE_AFTER
```

And this shutdown order:

```
CORE_AFTER
EXTENSION_AFTER
APPLICATION
EXTENSION_BEFORE
CORE_BEFORE
```

Obviously calling it "Shutdown priorities" will be a bit weird :]

But... would that fit what you're trying to do with shutdown?

Ah, also... I suspect this is something that needs discussing on the quarkus-dev mailing list. Let's plan that on Zulip.

**Comment by mmusgrov** [comment]
+1 I think ordering the transaction recovery system early during startup and late during shutdown is needed (for example it should help with https://github.com/quarkusio/quarkus/issues/35839#issuecomment-2871864919

File: extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/HibernateOrmRecorder.java [hunk 6]
```diff
@@ -105,8 +106,16 @@ public Supplier<JPAConfig> jpaConfigSupplier(HibernateOrmRuntimeConfig config) {
...
-        beanContainer.beanInstance(JPAConfig.class).startAll();
+    public void startAllPersistenceUnits(BeanContainer beanContainer, ShutdownContext shutdownContext) {
+        JPAConfig jpaConfig = beanContainer.beanInstance(JPAConfig.class);
+        // NOTE:
+        //  - We register the shutdown task before we start any PUs,
+        //    This way we'll be able to clean up even if one of the PUs fails to start while others already did.
+        //  - The step that starts the PUs returns the ServiceStartBuildItem, this in turn ensures that
+        //    the shutdown task that triggers the ShutdownEvent will be registered after this one,
+        //    and users will have access to the "ORM stuff" in their listeners.
+        shutdownContext.addShutdownTask(jpaConfig::shutdown);
```
Comment (yrodiere) [inline extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/HibernateOrmRecorder.java:118]: Do you know what guarantees that datasources are stopped after JPA exactly?

Comment (marko-bekhta) [reply extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/HibernateOrmRecorder.java:118]: mmm so the datasources we use here are coming from CDI, right ? 
and since CDI container starts (and adds it's shutdown task) before ORM does, all beans are still around. So as long as the datasource does not have it's own shutdown we should be ok. 
Also we depend on `List<JdbcDataSourceBuildItem> dataSourcesConfigured` in `startPersistenceUnits` so that means the bean producer was created. And there are no shutdown tasks in agroal (at least none that I could find).

Comment (marko-bekhta) [reply extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/HibernateOrmRecorder.java:118]: If we'd want to get some better "guarantees" here ... we'd need to force-start the datasources' beans in some runtime step (register the shutdown task for the datasource, which essenntaillty be the same as destroying that bean ???) and add the dependency on that step to starting the PUs ...  but ... I guess I'm not as familiar with agroal extension to be convinced that that's the way to do it 😃

Comment (yrodiere) [reply extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/HibernateOrmRecorder.java:118]: Ok, so you're saying the shutdown order is this?

1. CDI shutdown event observers
2. JPAConfig shutdown
3. CDI beans destruction (including agroal)

Comment (marko-bekhta) [reply extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/HibernateOrmRecorder.java:118]: yes

Comment (marko-bekhta) [reply extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/HibernateOrmRecorder.java:118]: well it's probably "Shutdown event is fired and all observers process the event" (1)

but yes, that's the order 🙂

File: integration-tests/hibernate-search-orm-elasticsearch-outbox-polling/pom.xml (hunk 3 above)
Comment (yrodiere) [reply integration-tests/hibernate-search-orm-elasticsearch-outbox-polling/pom.xml]: This is apparently still relevant... maybe?

**Comment by yrodiere** [comment]
FYI @mmusgrov Marko changed the approach completely, to only address the specific case of Hibernate.

This follows the discussion on quarkus-dev: https://groups.google.com/g/quarkus-dev/c/CMq7i4EZMXY/m/vy956nJjBwAJ

EDIT: Sorry, wrong link -- I fixed it.

File: integration-tests/hibernate-search-orm-elasticsearch-outbox-polling/pom.xml (hunk 3 above)
Comment (marko-bekhta) [reply integration-tests/hibernate-search-orm-elasticsearch-outbox-polling/pom.xml]: good point, thanks 😃 
moved them around and it worked (at least locally) let's see what CI says 🤞🏻 🙂

Comment (marko-bekhta) [reply integration-tests/hibernate-search-orm-elasticsearch-outbox-polling/pom.xml]: ohh and there are more changes in main now 😁 let me rebase ....

**Review by yrodiere — APPROVED** [review]

File: integration-tests/hibernate-search-orm-elasticsearch-outbox-polling/pom.xml (hunk 3 above)
Comment (yrodiere) [reply integration-tests/hibernate-search-orm-elasticsearch-outbox-polling/pom.xml]: > ohh and there are more changes in main now 😁 let me rebase ....

And there are some more now... sorry.

**Review by yrodiere — APPROVED** [review]
