### PR TITLE
Take native-sources build into account for various extensions

### LINKED ISSUE #25762: Compiling a `quarkus-cli` application to a static binary breaks `picocli`
### Describe the bug

Trying to compile a Quarkus Cli application to fully static binaries "breaks" `picocli`.

cc. @remkop

### Expected behavior

The executable should run in the same way with Java and when compiled.

### Actual behavior

```
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2022-05-24 16:00:11,702 INFO  [io.quarkus] (main) code-with-quarkus 1.0.0-SNAPSHOT native (powered by Quarkus 2.9.1.Final) started in 0.012s. 
2022-05-24 16:00:11,705 INFO  [io.quarkus] (main) Profile prod activated. 
2022-05-24 16:00:11,705 INFO  [io.quarkus] (main) Installed features: [cdi, picocli]
2022-05-24 16:00:11,706 ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): picocli.CommandLine$InitializationException: picocli.CommandLine$AutoHelpMixin@483680e0 is not a command: it has no @Command, @Option, @Parameters or @Unmatched annotations
        at picocli.CommandLine$Model$CommandReflection.validateCommandSpec(CommandLine.java:11680)
        at picocli.CommandLine$Model$CommandReflection.extractCommandSpec(CommandLine.java:11510)
        at picocli.CommandLine$Model$CommandSpec.forAnnotatedObject(CommandLine.java:6236)
        at picocli.CommandLine$Model$CommandSpec.mixinStandardHelpOptions(CommandLine.java:7220)
        at picocli.CommandLine$Model$CommandReflection.extractCommandSpec(CommandLine.java:11505)
        at picocli.CommandLine$Model$CommandSpec.forAnnotatedObject(CommandLine.java:6236)
        at picocli.CommandLine.<init>(CommandLine.java:227)
        at picocli.CommandLine.<init>(CommandLine.java:221)
        at io.quarkus.picocli.runtime.DefaultPicocliCommandLineFactory.create(DefaultPicocliCommandLineFactory.java:43)
        at io.quarkus.picocli.runtime.DefaultPicocliCommandLineFactory_ClientProxy.create(Unknown Source)
        at io.quarkus.picocli.runtime.PicocliCommandLineProducer.picocliCommandLine(PicocliCommandLineProducer.java:23)
        at io.quarkus.picocli.runtime.PicocliCommandLineProducer_ProducerMethod_picocliCommandLine_9215511af8bf79a5b9761758f9829960bca3fec0_Bean.create(Unknown Source)
        at io.quarkus.picocli.runtime.PicocliCommandLineProducer_ProducerMethod_picocliCommandLine_9215511af8bf79a5b9761758f9829960bca3fec0_Bean.get(Unknown Source)
        at io.quarkus.picocli.runtime.PicocliCommandLineProducer_ProducerMethod_picocliCommandLine_9215511af8bf79a5b9761758f9829960bca3fec0_Bean.get(Unknown Source)
        at io.quarkus.picocli.runtime.PicocliRunner_Bean.create(Unknown Source)
        at io.quarkus.picocli.runtime.PicocliRunner_Bean.get(Unknown Source)
        at io.quarkus.picocli.runtime.PicocliRunner_Bean.get(Unknown Source)
        at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:467)
        at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:480)
        at io.quarkus.arc.impl.BeanManagerImpl.getReference(BeanManagerImpl.java:59)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:120)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)

2022-05-24 16:00:11,707 INFO  [io.quarkus] (main) code-with-quarkus stopped in 0.001s
```

### How to Reproduce?

- clone this repo using the `quarkus-picocli` branch: https://github.com/andreaTP/test_graal_zig_cc/tree/quarkus-picocli
- run `docker build . -t graal_zigcc --progress=plain`
- and execute the static binary: `docker run --rm -it graal_zigcc`

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #25762

### CODE REVIEW

**Comment by geoand** [comment]
We probably want to backport this to 2.7 as well, but I am not sure it will apply cleanly. If so, I can easily create a 2.7 specific PR.

**Comment by maxandersen** [comment]
How long has it been broken?
+1 on the fix and back porting.

**Comment by geoand** [comment]
> How long has it been broken?

It's likely forever always been broken for the native-source build (which however is a very very niche feature)

File: extensions/jdbc/jdbc-oracle/deployment/src/main/java/io/quarkus/jdbc/oracle/deployment/ExtendedCharactersSupport.java [hunk 1]
```diff
@@ -5,13 +5,13 @@
...
 import io.quarkus.deployment.pkg.NativeConfig;
-import io.quarkus.deployment.pkg.steps.NativeBuild;
+import io.quarkus.deployment.pkg.steps.NativeOrNativeSourcesBuild;
 import io.quarkus.jdbc.oracle.runtime.OracleInitRecorder;
 
 public final class ExtendedCharactersSupport {
 
     @Record(STATIC_INIT)
-    @BuildStep(onlyIf = NativeBuild.class)
+    @BuildStep(onlyIf = NativeOrNativeSourcesBuild.class)
```
Comment (gsmet) [inline extensions/jdbc/jdbc-oracle/deployment/src/main/java/io/quarkus/jdbc/oracle/deployment/ExtendedCharactersSupport.java:14]: I think this is going to be confusing. We should at least add a comment in `NativeBuild` to tell it should be used in very specific cases and the other should be preferred. But I'm even wondering if we should merge the two and always in `NativeBuild`. Or do we envision having to run something only for the native compilation and not the native sources build?

Comment (geoand) [reply extensions/jdbc/jdbc-oracle/deployment/src/main/java/io/quarkus/jdbc/oracle/deployment/ExtendedCharactersSupport.java:14]: Agreed about the comment, but we can't merge the two as there are cases where we need to differentiate (like in the container-image extensions)

**Comment by andreaTP** [comment]
I acknowledge that `native-sources` is a niche feature, but, could it be tested in CI? something like:  https://github.com/quarkusio/quarkus/blob/29467c3d7b94f5a2603931c89123081bba52ffd1/integration-tests/maven/src/test/java/io/quarkus/maven/it/NativeImageIT.java#L34 .
Especially because is pretty hard to track down bugs in that area 😅

**Comment by geoand** [comment]
That would not help terribly, we would theoretically have to run a whole battery of such tests

**Comment by andreaTP** [comment]
I think that ppl trying out the functionality and hitting bugs are just going to assume "it doesn't work" and move on without reporting, but I have no objection to going ahead without tests as I agree it's a niche feature.

Anyhow, just to share all of my findings, also the `native-image` command is slightly different:
https://www.diffchecker.com/H7uixwGG

Using `native-image.args` is missing `--link-at-build-time` and `-H:NativeLinkerOption=-no-pie` options (not sure if it's intended).
The basic cli I am testing on looks to be not affected i.e. it compiles and run with and without.

Additional question, I got a few (Docker)configurations working for building [fully statically linked binaries](https://github.com/andreaTP/test_graal_zig_cc/blob/ee71e6b92b01ae62b0c7c940b2b7cd4eda046fb2/Dockerfile#L49-L53) (e.g. no need for external `libc` and can run on plain `scratch` images) any interest in it or you are leaving those bits out intentionally?

**Comment by geoand** [comment]
The link at build time flag I saw as well and will fix subsequently.

The no pie flag depends on the machine that will ultimately run the build, can't do anything about it

**Comment by geoand** [comment]
About the scratch images, i would suggest writing an email to the quarkus-dev mailing list

File: extensions/jdbc/jdbc-oracle/deployment/src/main/java/io/quarkus/jdbc/oracle/deployment/ExtendedCharactersSupport.java (hunk 1 above)
Comment (gsmet) [reply extensions/jdbc/jdbc-oracle/deployment/src/main/java/io/quarkus/jdbc/oracle/deployment/ExtendedCharactersSupport.java:14]: I think I would rather have `NativeBuild` targeting the two and having something like `NativeBuildOnly` or something similar for the other.
Otherwise my guess is that we will keep hitting that wall.

Comment (geoand) [reply extensions/jdbc/jdbc-oracle/deployment/src/main/java/io/quarkus/jdbc/oracle/deployment/ExtendedCharactersSupport.java:14]: I'm -0.5 on that. I won't make that change myself, but won't object to it being made by anyone else

Comment (gsmet) [reply extensions/jdbc/jdbc-oracle/deployment/src/main/java/io/quarkus/jdbc/oracle/deployment/ExtendedCharactersSupport.java:14]: OK, well, I suppose we will see how it goes then. Please add a big warning in the Javadoc though.

Comment (geoand) [reply extensions/jdbc/jdbc-oracle/deployment/src/main/java/io/quarkus/jdbc/oracle/deployment/ExtendedCharactersSupport.java:14]: Will do

**Comment by andreaTP** [comment]
@geoand 

> The no pie flag depends on the machine that will ultimately run the build, can't do anything about it

Do you wanna elaborate? I would expect the same flags to be applied on a build with the same machine/architecture/tools by `-Pnative` and `native-sources`, is it a wrong assumption?

**Comment by geoand** [comment]
> Do you wanna elaborate? I would expect the same flags to be applied on a build with the same machine/architecture/tools by -Pnative and native-sources, is it a wrong assumption?

The whole point of the `native-sources` is that you run the native-image part on a different machine. That means that the Quarkus part could run a Mac for example and the `native-image` run on Linux.
`no-pie` is only used when the machine running `native-image`  is a Linux box (see [this](https://github.com/quarkusio/quarkus/blob/2.9.2.Final/core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java#L176)).

File: extensions/jdbc/jdbc-oracle/deployment/src/main/java/io/quarkus/jdbc/oracle/deployment/ExtendedCharactersSupport.java (hunk 1 above)
Comment (geoand) [reply extensions/jdbc/jdbc-oracle/deployment/src/main/java/io/quarkus/jdbc/oracle/deployment/ExtendedCharactersSupport.java:14]: Done

**Comment by geoand** [comment]
> Using native-image.args is missing --link-at-build-time and -H:NativeLinkerOption=-no-pie options (not sure if it's intended).

This has actually been addressed in `main` already

**Comment by andreaTP** [comment]
Thanks for the explanation @geoand appreciated!

**Comment by geoand** [comment]
YW!

**Review by gastaldi — APPROVED** [review]

**Comment by maxandersen** [comment]
Thanks for explanation. 

I wouldn't call it niche feature though as key part in tekton/buildpack setups. 

Not much used yet - but should/will be :)

**Comment by geoand** [comment]
Looking forward to it 🙂
