### PR TITLE
Fix various usability issues in Spring @RestControllerAdvice handling

### LINKED ISSUE #5796: @RestControllerAdvice that returns an object but handles errors from a void controller method does not return json
A simple way to reproduce this error is to change the existing spring-web integration to use : 

```
    @GetMapping("/responseEntity")
    public Greeting handledByResponseEntity() {
        throw new IllegalStateException("bad state");
    }
```

to:

```
    @GetMapping("/responseEntity")
    public void handledByResponseEntity() {
        throw new IllegalStateException("bad state");
    }
``` 

in the `ExceptionThrowingController` class

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #5796

### CODE REVIEW

**Comment by geoand** [comment]
@gsmet this should be easy to review commit by commit

File: extensions/spring-web/runtime/src/main/java/io/quarkus/spring/web/runtime/ResponseEntityConverter.java [hunk 1]
```diff
@@ -22,7 +22,7 @@ public static Response toResponse(ResponseEntity responseEntity) {
     private static Headers<Object> toHeaders(HttpHeaders springHeaders) {
         Headers<Object> jaxRsHeaders = new Headers<>();
         for (Map.Entry<String, List<String>> entry : springHeaders.entrySet()) {
-            jaxRsHeaders.addAll(entry.getKey(), entry.getValue());
+            jaxRsHeaders.addAll(entry.getKey(), entry.getValue().toArray(new Object[0]));
```
Comment (gsmet) [inline extensions/spring-web/runtime/src/main/java/io/quarkus/spring/web/runtime/ResponseEntityConverter.java]: Maybe let's properly initialize the size of the array to avoid creating a new one?

File: extensions/spring-web/runtime/src/main/java/io/quarkus/spring/web/runtime/ResponseEntityConverter.java [hunk 2]
```diff
@@ -4,26 +4,38 @@
...
+    private static Headers<Object> toHeaders(HttpHeaders springHeaders, boolean addJsonContentTypeIfNotSet) {
         Headers<Object> jaxRsHeaders = new Headers<>();
         for (Map.Entry<String, List<String>> entry : springHeaders.entrySet()) {
             jaxRsHeaders.addAll(entry.getKey(), entry.getValue().toArray(new Object[0]));
         }
+        /*
+         * We add the default application/json content type if no content type is specified
+         * since this is the default value when returning an object from a Spring RestController
+         */
+        if (!jaxRsHeaders.containsKey(javax.ws.rs.core.HttpHeaders.CONTENT_TYPE) && addJsonContentTypeIfNotSet) {
```
Comment (gsmet) [inline extensions/spring-web/runtime/src/main/java/io/quarkus/spring/web/runtime/ResponseEntityConverter.java]: It's very minor as it's probably the default case but I would revert the condition to avoid the map lookup when we can.

File: extensions/spring-web/deployment/src/main/java/io/quarkus/spring/web/deployment/ControllerAdviceAbstractExceptionMapperGenerator.java [hunk 3]
```diff
@@ -135,17 +137,39 @@ void generateMethodBody(MethodCreator toResponse) {
...
             if (RESPONSE_ENTITY.equals(returnType.name())) {
+                /*
+                 * By default we will send JSON back unless the ResponseEntity has a String body
+                 */
+                boolean addDefaultJsonContentType = true;
+                if (returnType.kind() == Type.Kind.PARAMETERIZED_TYPE) {
+                    if (returnType.asParameterizedType().arguments().size() == 1) {
+                        Type responseEntityParameterType = returnType.asParameterizedType().arguments().get(0);
+                        if (STRING.equals(responseEntityParameterType.name())) {
+                            addDefaultJsonContentType = false;
```
Comment (gsmet) [inline extensions/spring-web/deployment/src/main/java/io/quarkus/spring/web/deployment/ControllerAdviceAbstractExceptionMapperGenerator.java]: There's no way in Spring to explicitly define the response media type?

File: extensions/spring-web/deployment/src/main/java/io/quarkus/spring/web/deployment/SpringWebProcessor.java [hunk 4]
```diff
@@ -338,7 +338,7 @@ public void generateExceptionMapperProviders(BeanArchiveIndexBuildItem beanArchi
         // Look for all exception classes that are annotated with @ResponseStatus
 
         IndexView index = beanArchiveIndexBuildItem.getIndex();
-        ClassOutput classOutput = new GeneratedClassGizmoAdaptor(generatedExceptionMappers, false);
+        ClassOutput classOutput = new GeneratedClassGizmoAdaptor(generatedExceptionMappers, true);
```
Comment (gsmet) [inline extensions/spring-web/deployment/src/main/java/io/quarkus/spring/web/deployment/SpringWebProcessor.java]: Oops :).

**Review by gsmet — CHANGES_REQUESTED** [review]
I added a few very minor comments and a question.

Feel free to ignore some of them if you don't feel like it but I'd like an answer to my question :).

File: extensions/spring-web/runtime/src/main/java/io/quarkus/spring/web/runtime/ResponseEntityConverter.java (hunk 2 above)
Comment (geoand) [reply extensions/spring-web/runtime/src/main/java/io/quarkus/spring/web/runtime/ResponseEntityConverter.java]: Makes sense

File: extensions/spring-web/deployment/src/main/java/io/quarkus/spring/web/deployment/SpringWebProcessor.java (hunk 4 above)
Comment (geoand) [reply extensions/spring-web/deployment/src/main/java/io/quarkus/spring/web/deployment/SpringWebProcessor.java]: Yeah, that cost me a good hour or so to figure out... Paying for my own mistakes :P

File: extensions/spring-web/deployment/src/main/java/io/quarkus/spring/web/deployment/ControllerAdviceAbstractExceptionMapperGenerator.java (hunk 3 above)
Comment (geoand) [reply extensions/spring-web/deployment/src/main/java/io/quarkus/spring/web/deployment/ControllerAdviceAbstractExceptionMapperGenerator.java]: For the regular controller method sure there is and we handle it. But for error handler you either return an object and rely on the default or return a `ResponseEntity` where you can set whatever you like.

File: extensions/spring-web/runtime/src/main/java/io/quarkus/spring/web/runtime/ResponseEntityConverter.java (hunk 1 above)
Comment (geoand) [reply extensions/spring-web/runtime/src/main/java/io/quarkus/spring/web/runtime/ResponseEntityConverter.java]: Not sure I follow. We just need to convert a list to an array and according to http://shipilev.net/blog/2016/arrays-wisdom-ancients/#_conclusion this is the proper way to do it.
Am I missing something?

File: extensions/spring-web/runtime/src/main/java/io/quarkus/spring/web/runtime/ResponseEntityConverter.java (hunk 2 above)
Comment (geoand) [reply extensions/spring-web/runtime/src/main/java/io/quarkus/spring/web/runtime/ResponseEntityConverter.java]: Fixed

File: extensions/spring-web/deployment/src/main/java/io/quarkus/spring/web/deployment/ControllerAdviceAbstractExceptionMapperGenerator.java (hunk 3 above)
Comment (gsmet) [reply extensions/spring-web/deployment/src/main/java/io/quarkus/spring/web/deployment/ControllerAdviceAbstractExceptionMapperGenerator.java]: Are you sure about that? Wouldn't it use the content type defined in the `@RequestMapping` annotation of the original method?

And just to be clear, we don't support overriding the content-type in the `ResponseEntity` response of the exception mapper?

File: extensions/spring-web/runtime/src/main/java/io/quarkus/spring/web/runtime/ResponseEntityConverter.java (hunk 1 above)
Comment (gsmet) [reply extensions/spring-web/runtime/src/main/java/io/quarkus/spring/web/runtime/ResponseEntityConverter.java]: I don't know. The List javadoc clearly pushes towards using the size but I suppose it's not critical enough here to have us waste our time discussing it :).

File: extensions/spring-web/deployment/src/main/java/io/quarkus/spring/web/deployment/ControllerAdviceAbstractExceptionMapperGenerator.java (hunk 3 above)
Comment (geoand) [reply extensions/spring-web/deployment/src/main/java/io/quarkus/spring/web/deployment/ControllerAdviceAbstractExceptionMapperGenerator.java]: > Are you sure about that? Wouldn't it use the content type defined in the `@RequestMapping` annotation of the original method?
> 

Yes it would, and that is what causes the problem, since the controller method uses a type that doesn't match what the exception handler returns.

> And just to be clear, we don't support overriding the content-type in the `ResponseEntity` response of the exception mapper?

That's part of the responsibility of the application code. If the application sets it, we don't change it: https://github.com/quarkusio/quarkus/blob/63673a7189713c822366b518550248778ab4a66d/extensions/spring-web/runtime/src/main/java/io/quarkus/spring/web/runtime/ResponseEntityConverter.java#L36

File: extensions/spring-web/runtime/src/main/java/io/quarkus/spring/web/runtime/ResponseEntityConverter.java (hunk 1 above)
Comment (geoand) [reply extensions/spring-web/runtime/src/main/java/io/quarkus/spring/web/runtime/ResponseEntityConverter.java]: Yeah, this isn't on a critical path anyway so it doesn't really matter.

File: extensions/spring-web/deployment/src/main/java/io/quarkus/spring/web/deployment/ControllerAdviceAbstractExceptionMapperGenerator.java (hunk 3 above)
Comment (gsmet) [reply extensions/spring-web/deployment/src/main/java/io/quarkus/spring/web/deployment/ControllerAdviceAbstractExceptionMapperGenerator.java]: We discussed this on Zulip with @geoand. Our current support is a bit limited as we will always return JSON (except in some edge cases), even if the original method was pushing some XML.

That's not very user friendly and we will probably need to improve that. But that can probably wait so we decided to merge that one first.

**Review by gsmet — APPROVED** [review]

File: extensions/spring-web/deployment/src/main/java/io/quarkus/spring/web/deployment/ControllerAdviceAbstractExceptionMapperGenerator.java (hunk 3 above)
Comment (geoand) [reply extensions/spring-web/deployment/src/main/java/io/quarkus/spring/web/deployment/ControllerAdviceAbstractExceptionMapperGenerator.java]: As discussed I will research this a bit more and open an issue for a follow-up implementation

**Comment by geoand** [comment]
@gsmet all commits from the PR can be back-ported except: 324a213be6f34651182f9fd69f92070a3a0ce835
