### PR TITLE
Detect basic authentication is implicitly required when it can be safely determined and enable the basic auth by default for such scenarios

### LINKED ISSUE #39912: When multiple authentication mechanisms are available, http path permission is not working properly
### Describe the bug

I have an issue with how the http path permission works when I have multiple auth. mechanisms.

Basically I have 2 endpoints with different auth. mechanisms:
- /auth : basic auth
- /gateway/* : bearer auth

And when I configure it like this:

```
quarkus.http.auth.permission.basic.paths=/auth/*
quarkus.http.auth.permission.basic.policy=authenticated
quarkus.http.auth.permission.basic.auth-mechanism=basic

quarkus.http.auth.permission.bearer.paths=/gateway/*
quarkus.http.auth.permission.bearer.policy=authenticated
quarkus.http.auth.permission.bearer.auth-mechanism=bearer
```

The `Principal` object has no username when I call the `/auth` endpoint.

And if I replace the config above with implementing `HttpAuthenticationMechanism` interface then everything works fine.

See also the reproducer here:
https://github.com/Serkan80/quarkus-issue-reproducers/tree/master/http-path-permission-issue

### Expected behavior

I expect that the provided config above should work, without the need to implement a custom `HttpAuthenticationMechanism`.

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

jdk 17

### Quarkus version or git rev

3.8.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8.6

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by michalvavrik**
closes: #39912

Adds basic auth when it is already a default bean and we can quite safely say it is needed (it is selected via HTTP Perms or `@BasicAuthentication` and there is no HTTP Auth Mechanisms provided by the application itsels). I didn't dare to cover all cases because the credential transport type is determined dynamically during the HTTP request and there would be potential for breaking changes. Users have very simple alternative when we do not manage to detect that basic auth is needed, just use `quarkus.http.auth.basic=true`.

- changes in `quarkus-integration-test-oidc-code-flow` helps to test auto enabling for `@BasicAuthentication`

Situation in management interface is blocked for now, one of the reasons is #39926.

### CODE REVIEW

File: integration-tests/oidc-code-flow/src/main/resources/application.properties [hunk 1]
```diff
@@ -204,3 +204,9 @@ quarkus.log.category."io.quarkus.vertx.http.runtime.security.HttpAuthenticator".
 quarkus.log.category."io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder".level=DEBUG
 
 quarkus.log.category."com.gargoylesoftware.htmlunit.javascript.host.css.CSSStyleSheet".level=FATAL
+
+# make code flow default for all paths expect for 'test-security-annotation' path to test annotations
+quarkus.http.auth.permission.use-code-flow-by-default.paths=/web-app*,/web-app2*,/web-app3*,/tenant-autorefresh*,/tenant-https*,/tenant-logout*,/tenant-nonce*,/tenant-refresh*,/public-web-app*,/index.html,/,/tenant-cookie-path-header,/tenant-javascript
```
Comment (sberyozkin) [inline integration-tests/oidc-code-flow/src/main/resources/application.properties:209]: I'm a little bit concerned about it, as it introduces a new direction into how the whole set of tests is running, and we have this big list of paths. I'd rather add a dedicated `extensions/oidc/deployment` test with a clear definition of what is tested.

File: integration-tests/oidc/src/main/resources/application.properties [hunk 2]
```diff
@@ -14,7 +14,6 @@ quarkus.native.additional-build-args=-H:IncludeResources=.*\\.jks
 quarkus.http.cors=true
 quarkus.http.cors.origins=*
```
Comment (sberyozkin) [inline integration-tests/oidc/src/main/resources/application.properties:16]: See the OIDC code flow related comment, I propose to have a dedicated test in the oidc extension. Lets say one where the basic is set in the HTTP policy path and the bearer token is used, another one - with BasicAuthentication and also the bearer token being used

Comment (michalvavrik) [reply integration-tests/oidc/src/main/resources/application.properties:16]: > See the OIDC code flow related comment, I propose to have a dedicated test in the oidc extension.

In this particular test, I don't find the comment reasonable because it has zero impact on OIDC code flow.

> Lets say one where the basic is set in the HTTP policy path and the bearer token is used, another one - with BasicAuthentication and also the bearer token being used

really, here, I'm just dropping `quarkus.http.auth.basic=true` because there is a `quarkus.http.auth.permission.basic.auth-mechanism=basic`, I don't get it why it concerns you. Maybe you confused it with the `integration-tests/oidc-code-flow` where I did that refactoring?

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpAuthenticator.java [hunk 3]
```diff
@@ -41,6 +45,24 @@
...
+     * - not explicitly disabled or enabled
+     * - is default bean and not programmatically looked up because there are other authentication mechanisms
+     * - no custom auth mechanism is defined because then, we can't tell if user didn't provide custom impl.
+     * - there is a provider that supports it (if not, we inform user via the log)
+     * <p>
+     * Presence of this system property means that we need to test whether:
+     * - there are HTTP Permissions using explicitly this mechanism
+     * - or {@link io.quarkus.vertx.http.runtime.security.annotation.BasicAuthentication}
+     */
+    public static final String TEST_IF_BASIC_AUTH_IMPLICITLY_REQUIRED = "io.quarkus.security.http.test-if-basic-auth-implicitly-required";
```
Comment (sberyozkin) [inline extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpAuthenticator.java:59]: In the linked issue, the problem is that the user has noticed there was no need to enable basic authentication, when no other mechanisms was used - and then was surprised the basic authentication had to be enabled manually even though the HTTP Policy says the basic authentication is required.
So asking users to set this property will make harder to the users, if we know `BASIC_AUTH_ANNOTATION_DETECTED`. Can we avoid it ?
We also have a case of HTTP policy saying Basic is required

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpAuthenticator.java [hunk 4]
```diff
@@ -377,6 +400,42 @@ public void accept(HttpCredentialTransport t) {
...
 
+    private static void addBasicAuthMechanismIfImplicitlyRequired(
+            Instance<HttpAuthenticationMechanism> httpAuthenticationMechanism,
+            List<HttpAuthenticationMechanism> mechanisms, Instance<IdentityProvider<?>> providers) {
+        if (!Boolean.getBoolean(TEST_IF_BASIC_AUTH_IMPLICITLY_REQUIRED) || isBasicAuthNotRequired()) {
+            return;
+        }
+
+        var basicAuthMechInstance = httpAuthenticationMechanism.select(BasicAuthenticationMechanism.class);
+        if (basicAuthMechInstance.isResolvable() && !mechanisms.contains(basicAuthMechInstance.get())) {
```
Comment (sberyozkin) [inline extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpAuthenticator.java:411]: This is a useful check, but I believe it should be running all the time, it will save time to users who forgot to add the right identity provider's configuration

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpAuthenticator.java (hunk 3 above)
Comment (michalvavrik) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpAuthenticator.java:59]: We are not asking user to do anything. It's just a way to propagate information because creating the HTTP Authenticator as a synthetic bean is not a suitable (at least for now, we need to be extremely careful when is it created as I mentioned that some extensions like Elytron fails if the bean is initialized too early).

User needs to do nothing. I have tests that proves it (and I'll add the one requested by you).

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpAuthenticator.java (hunk 4 above)
Comment (michalvavrik) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpAuthenticator.java:411]: here is BasicAuthentication or auth-mechanism=basic I think that's what you mean. we don't do that for other mechanisms either. some validation would be nice, sure. IMO not at this place of the `Httpauthenticator` because that needs to be done during the app startup.

Comment (michalvavrik) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpAuthenticator.java:411]: I'll add some additional validation that will inform user.

Comment (michalvavrik) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpAuthenticator.java:411]: Hmm, thinking about it. I think this debug message does it for cases where it is safe to done. We can't really be sure to log anything if we don't know that basic auth is required and there is no other mechanism that provides it.

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpAuthenticator.java (hunk 3 above)
Comment (michalvavrik) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpAuthenticator.java:59]: > In the linked issue, the problem is that the user has noticed there was no need to enable basic authentication, when no other mechanisms was used - and then was surprised the basic authentication had to be enabled manually even though the HTTP Policy says the basic authentication is required.

this PR solves user issue as shown in the `integration-tests/oidc` module without doing anything

File: integration-tests/oidc/src/main/resources/application.properties (hunk 2 above)
Comment (michalvavrik) [reply integration-tests/oidc/src/main/resources/application.properties:16]: Anyway, even though I disagree I'll drop this change.

Comment (sberyozkin) [reply integration-tests/oidc/src/main/resources/application.properties]: @michalvavrik Sorry I missed it, I did not realize the basic mechanism was enabled at the policy level

File: extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/HttpSecurityProcessor.java [hunk 5]
```diff
@@ -127,13 +134,46 @@ void setMtlsCertificateRoleProperties(
...
+            boolean noCustomAuthMechanismsDetected = beanRegistrationPhaseBuildItem
+                    .getContext()
+                    .beans()
+                    .filter(b -> b.hasType(AUTH_MECHANISM_NAME))
+                    .filter(BeanInfo::isClassBean)
+                    .filter(b -> appIndex.getClassByName(b.getBeanClass()) != null)
+                    .isEmpty();
+            // we can't decide whether custom mechanisms support basic auth or not
+            if (noCustomAuthMechanismsDetected) {
+                systemPropertyProducer
```
Comment (sberyozkin) [inline extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/HttpSecurityProcessor.java:153]: @michalvavrik Oh I see, so you keep it so that when custom Basic mechanisms are used, users can set this property ? I'd just drop it, this is a theoretically possible case but no more at this stage IMHO, I've never heard anyone attempt to customize the basic authentication

**Review by sberyozkin — COMMENTED** [review]
LGTM, the only minor suggestion is to drop `TEST_IF_BASIC_AUTH_IMPLICITLY_REQUIRED`

File: extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/HttpSecurityProcessor.java (hunk 5 above)
Comment (sberyozkin) [reply extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/HttpSecurityProcessor.java:153]: Or what else this option for ?

Comment (michalvavrik) [reply extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/HttpSecurityProcessor.java:153]: > Oh I see, so you keep it so that when custom Basic mechanisms are used, users can set this property ?
> Or what else is this option for ?

no no no, we are much didn't understand each other. during the build time I detect that we produce BasicAuthenticationMechanism and there is no custom authentication mechanism. This information needs to be propagated to the runtime to the HTTPAuthenticator so I used the system property. normally if you want to propagate build time information you use synthetic beans, but doing anything with HTTPAuthenticator would be sensitive now.

So to conclude this: this is Quarkus telling Quarkus what it detected during the build time. I think it's acceptable for such the edge case considering alternative is bigger refactoring.

> I'd just drop it, this is a theoretically possible case but no more at this stage IMHO, I've never heard anyone attempt to customize the basic authentication

- user that opened this issue #39912 did it https://github.com/Serkan80/quarkus-issue-reproducers/blob/1d7e988835f9e7772188b05bb237c4f1764c459a/http-path-permission-issue/src/main/java/com/acme/gateway/AuthenticationSelector.java
- I certainly do it in some of the tests
- most importantly, I simply don't know if someone doesn't delegate

if you are confident that users do not delegate to the basic auth, I will drop it. just be warned as there is slight potential for the breaking change @sberyozkin , please confirm

Comment (michalvavrik) [reply extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/HttpSecurityProcessor.java:153]: > LGTM, the only minor suggestion is to drop TEST_IF_BASIC_AUTH_IMPLICITLY_REQUIRED

I can create alternative mechanism to propagate the information, but if what you really mean is that you want to always check whether the basic auth is there, then it won't bring any information, there are just 2 states:

- bean is there and programmatic lookup works -> that is already covered, we have Basic auth mechanism listed as a bean, we try to add it and warn if there is no identity provider
- bean is there and programmatic lookup excluded if for it is a default bean and there are other mechanisms -> it is covered by this PR and this condition.

Comment (sberyozkin) [reply extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/HttpSecurityProcessor.java:153]: @michalvavrik Using the system property build item to propagate this info has been confusing

**Review by sberyozkin — APPROVED** [review]
