### PR TITLE
Fix wrong TestInfo test method in @Before/AfterEach

### LINKED ISSUE #19747: JUnit: Wrong test method passed in TestInfo parameter of BeforeEach/AfterEach methods
### Describe the bug

Consider the following test class:
```
package com.esri.karl.api;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInfo;

import io.quarkus.test.junit.QuarkusTest;

@QuarkusTest
public final class TestInfoTest {

	@BeforeEach
	void before(TestInfo testInfo) {
		testInfo.getTestMethod().ifPresent(m -> System.out.println(m.getName())); // prints "before", should print "testMethod"
	}

	@AfterEach
	void after(TestInfo testInfo) {
		testInfo.getTestMethod().ifPresent(m -> System.out.println(m.getName())); // prints "after", should print "testMethod"
	}

	@Test
	void testMethod() {}

}
```

### Expected behavior

The currently running test method annotated with `@Test` (`testMethod` in the test class above) should be passed via `testInfo` in `before` and `after`.

### Actual behavior

The methods `before` and `after` are passed in respectively, which is wrong.

### How to Reproduce?

Repro: Just run the test class provided above in Quarkus `2.2.0.Final`.

### Additional information

Quarkus version `2.1.4.Final` works as expected. This is likely a regression introduced with PR #19518.

Likely also related: the class of the passed test method has a different class loader than the class of the currently executing `before`/`after` method.
```
package com.esri.karl.api;

import java.lang.annotation.Annotation;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInfo;
import org.junit.platform.commons.util.AnnotationUtils;

import io.quarkus.test.junit.QuarkusTest;

@QuarkusTest
public final class TestInfoTest {

	@Target(ElementType.METHOD)
	@Retention(RetentionPolicy.RUNTIME)
	public @interface TestAnnotation { }

	@BeforeEach
	void before(TestInfo testInfo) throws ClassNotFoundException {
		System.out.println(AnnotationUtils.isAnnotated(testInfo.getTestMethod(), TestAnnotation.class)); // prints "false", should print "true"
		System.out.println(AnnotationUtils.isAnnotated(testInfo.getTestMethod(),
				(Class<? extends Annotation>) testInfo.getTestMethod().get().getDeclaringClass().getClassLoader().loadClass(TestAnnotation.class.getName()))); // prints "true"
	}

	@AfterEach
	void after(TestInfo testInfo) throws ClassNotFoundException {
		System.out.println(AnnotationUtils.isAnnotated(testInfo.getTestMethod(), TestAnnotation.class)); // prints "false", should print "true"
		System.out.println(AnnotationUtils.isAnnotated(testInfo.getTestMethod(),
				(Class<? extends Annotation>) testInfo.getTestMethod().get().getDeclaringClass().getClassLoader().loadClass(TestAnnotation.class.getName()))); // prints "true"
	}

	@Test
	@TestAnnotation
	void testAnnotation() {}

}
```

### PR DESCRIPTION
**Pull request by famod**
Fixes #19747

### CODE REVIEW

File: test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java [hunk 1]
```diff
@@ -1035,8 +1035,12 @@ private Object runExtensionMethod(ReflectiveInvocationContext<Method> invocation
                         cloneRequired = false;
                     } else if (TestInfo.class.isAssignableFrom(theclass)) {
                         TestInfo info = (TestInfo) arg;
+                        Method originalTestMethod = info.getTestMethod().get();
+                        Method newTestMethod = originalTestMethod.hashCode() == newMethod.hashCode()
```
Comment (famod) [inline test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java:1039]: This is just a tiny optimization to avoid calling `determineTCCLExtensionMethod()` again when we have a "regular" test method (not before/after).
To avoid even more calls, we would need something like an `IdentiyHashMap` member in this class, but that felt like overkill for now.

Comment (jonathan-meier) [reply test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java:1039]: I'm not sure whether comparing hash codes is a good idea here. The current implementation of `Method.hashCode` in OpenJDK is only based on the class and method name, but not on the entire method signature (https://github.com/openjdk/jdk/blob/1fb798d320c708dfcbc0bb157511a2937fafb9e6/src/java.base/share/classes/java/lang/reflect/Method.java#L380), so if for some (stupid) reason someone writes a test class with the following two equally named methods:
```
@BeforeEach
public void method(TestInfo testInfo) {}

@Test
public void method() {}
```
the wrong method will be passed via `testInfo`.

I suggest comparing `originalTestMethod` with `invocationContext.getExecutable()` or `originalTestMethod.toString()` with `newMethod.toString()` instead. Both suggestions should work more reliable, though note that I did not test them.

Comment (famod) [reply test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java:1039]: I was on the fence about this. Overloaded methods are not supported by Junit5, but I didn't think of the exact scenario you mentioned. I'd need to check what happens then.

If we want to be extra sure, we should probably drop that optimization entirely since Method.toString is not particularly cheap.

Comment (gsmet) [reply test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java:1039]: I would just drop it and only adjust if it becomes a problem.

Comment (famod) [reply test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java:1039]: Yeah, later today I plan to have a quick look at the IdentityHashMap solution and if that feels awkward I'll just go without any "caching".

Comment (famod) [reply test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java]: I pushed the `IdentityHashMap` approach. I like it, YMMV!

It avoids rescanning for methods that have already been determined before, also for non-TestInfo cases.
E.g. `@BeforeEach` methods are now looked up only once, not before _each_ actual test method execution.
Before that, a test with 10 actual test methods and one `@BeforeEach` and one `@AfterEach` method would trigger the reflective scan 30 times, with the cache it's only 12 times.

Since `QuarkusTestExtension` is recreated for each test class and that new cache is _not_ static, there is also no leak.

Comment (famod) [reply test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java]: PS, if in that example above those two `@BeforeEach` and `@AfterEach` methods had a `TestInfo` parameter, there would be 50 calls without a cache, but still only 12 with that cache.

File: test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java [hunk 2]
```diff
@@ -1089,13 +1093,16 @@ private Object runExtensionMethod(ReflectiveInvocationContext<Method> invocation
         }
     }
 
-    private Method determineTCCLExtensionMethod(ReflectiveInvocationContext<Method> invocationContext, Class<?> c)
+    private Method determineTCCLExtensionMethod(Method orginalMethod, Class<?> c)
```
Comment (jonathan-meier) [inline test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java:1096]: small typo, should be `originalMethod` 😉

Comment (famod) [reply test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java:1096]: 🤦‍♂️, thanks. I'll wait until others have reviewed to address everything in one go.

File: test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java [hunk 3]
```diff
@@ -196,6 +197,8 @@ public void run() {
         }
     };
 
+    private final IdentityHashMap<Method, Method> tcclMethodCache = new IdentityHashMap<>();
```
Comment (stuartwdouglas) [inline test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java:200]: This needs to be cleared at the end of the run, otherwise continuous testing will leak ClassLoaders.

**Review by stuartwdouglas — DISMISSED** [review]

File: test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java (hunk 3 above)
Comment (famod) [reply test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java:200]: Ok, where is the best place to do that? Here in `afterAll`? https://github.com/quarkusio/quarkus/blob/2.2.0.Final/test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java#L1134

Comment (stuartwdouglas) [reply test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java:200]: I think here: https://github.com/stuartwdouglas/quarkus/blob/78226e2971feea96fc2a63362529413b957aa120/test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java#L277

Comment (gsmet) [reply test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java:200]: Please do it just before the `GroovyCacheCleaner` call given we have little control on this one and we want to make sure this cache is reset.

Comment (famod) [reply test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java:200]: Done. I must say though it's a bit surprising that this non-static cache causes cl leaks, given that it should be GC-able as soon as the next test class is executed (= new instance of `QuarkusTestExtension` is created).
But then again I know little about the internals of continuous testing and I guess it's always safer to clear things eagerly, if possible.

**Comment by famod** [comment]
I've addressed all remarks and CI is green. This should be part of 2.2.1 @gsmet.

**Review by gastaldi — APPROVED** [review]
Looks good to me! Great job!
