### PR TITLE
Prevent AccessDeniedException in DEV mode when DEV UI is locating workspace item

### LINKED ISSUE #48310: AccessDeniedException in quarkus dev mode
### Describe the bug

I tried to upgrade to the newest version of quarkus. If I want to start it with `mvn clean compile quarkus:dev` I'm getting the error  java.nio.file.AccessDeniedException: /home/xyz/projects/my-project/database. This database folder has the rights `drwx------` as root, and that should not be changed.

Thanks in advance!

### Expected behavior

If I have not accessible folders outside `src`-folder should not end in access denied if I want to start quarkus in dev mode. If that is the case, there should be a possible exclude of folders/files.

### Actual behavior

Full stacktrace:
Caused by: java.io.UncheckedIOException: java.nio.file.AccessDeniedException: /home/xyz/projects/my-project/database
	at io.quarkus.devui.deployment.menu.WorkspaceProcessor.locateWorkspaceItems(WorkspaceProcessor.java:95)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:255)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2651)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2630)
	at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1622)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1589)
	at java.base/java.lang.Thread.run(Thread.java:1583)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.nio.file.AccessDeniedException: /home/vagrant/projects/chronapp/core-backend/database
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
	at java.base/sun.nio.fs.UnixException.asIOException(UnixException.java:115)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:501)
	at java.base/java.nio.file.Files.newDirectoryStream(Files.java:482)
	at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:301)
	at java.base/java.nio.file.FileTreeWalker.next(FileTreeWalker.java:374)
	at java.base/java.nioiles.walkFileTree(Files.java:2833)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2870)
	at io.quarkus.devui.deployment.menu.WorkspaceProcessor.locateWorkspaceItems(WorkspaceProcessor.java:70)
	... 10 more

### How to Reproduce?

1. Creating a quarkus project with dev ui and version 3.23.2.
2. Create a folder with permissions `drwx------` as root at the same directory level as `pom.xml`.
3. Starting quarkus with `mvn clean compile quarkus:dev`

### PR DESCRIPTION
**Pull request by michalvavrik**
- closes https://github.com/quarkusio/quarkus/issues/48310

### CODE REVIEW

File: extensions/vertx-http/deployment/src/main/java/io/quarkus/devui/deployment/menu/WorkspaceProcessor.java [hunk 1]
```diff
@@ -74,7 +75,8 @@ void locateWorkspaceItems(BuildSystemTargetBuildItem buildSystemTarget,
                 Files.walkFileTree(projectRoot, new SimpleFileVisitor<Path>() {
                     @Override
                     public FileVisitResult preVisitDirectory(Path dir, BasicFileAttributes attrs) throws IOException {
-                        if (Files.isHidden(dir) || ignoreFolders.contains(dir.getFileName().toString())) {
+                        if (Files.isHidden(dir) || ignoreFolders.contains(dir.getFileName().toString())
+                                || !Files.isReadable(dir)) {
```
Comment (gsmet) [inline extensions/vertx-http/deployment/src/main/java/io/quarkus/devui/deployment/menu/WorkspaceProcessor.java]: For a directory, you also need executable. At least on Unix. Not sure how Windows reacts when checking for executable...

**Comment by gsmet** [comment]
Thanks for having a look at this one, I had it on my list and then forgot!

File: extensions/vertx-http/deployment/src/main/java/io/quarkus/devui/deployment/menu/WorkspaceProcessor.java (hunk 1 above)
Comment (michalvavrik) [reply extensions/vertx-http/deployment/src/main/java/io/quarkus/devui/deployment/menu/WorkspaceProcessor.java]: Thanks, maybe that's why I had to add `visitFileFailed` (although I'll probably keep it anyway). I'll try it.

Comment (gsmet) [reply extensions/vertx-http/deployment/src/main/java/io/quarkus/devui/deployment/menu/WorkspaceProcessor.java]: Yes keep it, it’s nice to have a safe guard.

Comment (michalvavrik) [reply extensions/vertx-http/deployment/src/main/java/io/quarkus/devui/deployment/menu/WorkspaceProcessor.java]: I have added a check for "executable" file permission and it is in the PR now. But when I tried to reproduce it without `visitFileFailed`, application still failed to start. So I'll keep it as you are OK with it.

**Comment by michalvavrik** [comment]
I don't think these failures are related at all, I push the same code again (as it is already rebased on current main) so that we get idea if these failures are stable.

**Review by phillip-kruger — APPROVED** [review]
LGTM ! Thanks
