### PR TITLE
MongoDB Update : Allow all update operators

### LINKED ISSUE #9956: Quarkus 1.5.0.Final - Mongo Panache - Native update queries create invalid MongoDB statements
**Describe the bug**
When performing an update in a `MongoPanacheRepository` using a native query such as
```
update("{
  $push: {
    someList: { ... }
  }
}");
```
the final statement sent to the MongoDB contains a wrapper:
```
{'$set': {
  $push: {
    someList: { ... }
  }
}}
```
The wrapper is created in `ReactiveMongoOperations::bindUpdate`:
```
static String bindUpdate(Class<?> clazz, String query, Map<String, Object> params) {
  String bindUpdate = bindQuery(clazz, query, params);
  if (!bindUpdate.contains("$set")) {
    bindUpdate = "{'$set':" + bindUpdate + "}";
  }
  LOGGER.debug(bindUpdate);
  return bindUpdate;
}
```
Although this might be convenient for some users who don't want to deal with the MongoDB query details it corrupts those native queries that instead of a $set operation wants to perform any other such as `$push`, `$inc`, etc. (cf. https://docs.mongodb.com/manual/reference/operator/update/)

**Workaround**
Since the code of `bindUpdate` performs a string search for `$set` you could add a no-op `$set` instruction to avoid the wrapper creation, e.g.:
```
update("{
  $push: {
    someList: { ... }
  },
  $set: {
    someField: '$someField'
  }
}");
```

**Expected behavior**
The final statement does not contain the `$set` wrapper.

**Actual behavior**
The `$set` wrapper is created producing an invalid mongo statement.

### PR DESCRIPTION
**Pull request by loicmathieu**
Fixes #9956

### CODE REVIEW

File: extensions/panache/mongodb-panache-common/runtime/src/main/java/io/quarkus/mongodb/panache/reactive/runtime/ReactiveMongoOperations.java [hunk 1]
```diff
@@ -42,6 +42,11 @@
 public abstract class ReactiveMongoOperations<QueryType, UpdateType> {
     public final String ID = "_id";
     private static final Logger LOGGER = Logger.getLogger(ReactiveMongoOperations.class);
+
+    // update operators: https://docs.mongodb.com/manual/reference/operator/update/
+    private static final List<String> UPDATE_OPERATORS = Arrays.asList(
+            "$currentDate", "$inc", "$min", "$max", "$mul", "$rename", "$set", "$setOnInsert", "$unset");
```
Comment (evanchooly) [inline extensions/panache/mongodb-panache-common/runtime/src/main/java/io/quarkus/mongodb/panache/reactive/runtime/ReactiveMongoOperations.java:48]: There are a lot more operators than this...

File: extensions/panache/mongodb-panache-common/runtime/src/main/java/io/quarkus/mongodb/panache/reactive/runtime/ReactiveMongoOperations.java [hunk 2]
```diff
@@ -383,11 +394,17 @@ String bindUpdate(Class<?> clazz, String query, Object[] params) {
     /**
      * We should have a query like <code>{'firstname': :firstname, 'lastname': :lastname}</code> for native one
      * and like <code>firstname = :firstname and lastname = :lastname</code> for PanacheQL one.
-     * As update document needs a <code>$set</code> operator we add it if needed.
+     * As update document needs an update operator, we add <code>$set</code> if none is provided.
      */
     String bindUpdate(Class<?> clazz, String query, Map<String, Object> params) {
         String bindUpdate = bindQuery(clazz, query, params);
-        if (!bindUpdate.contains("$set")) {
+        boolean containsOperator = false;
```
Comment (evanchooly) [inline extensions/panache/mongodb-panache-common/runtime/src/main/java/io/quarkus/mongodb/panache/reactive/runtime/ReactiveMongoOperations.java:401]: duplicated code could probably be moved to a method

**Review by evanchooly — CHANGES_REQUESTED** [review]
i don't see a test that actually executes the updated update statement.  one thing i'm trying to remember from my morphia work is the nuance around `$set`.  iirc, with `$set` it will do a full document replacement in the database rather than updating just the fields listed but i can't recall exactly.  I would like to see a test that 1) actually executes the updates in the database and 2) makes sure we're not replacing whole documents when we're not intending to do so.

File: extensions/panache/mongodb-panache-common/runtime/src/main/java/io/quarkus/mongodb/panache/reactive/runtime/ReactiveMongoOperations.java (hunk 1 above)
Comment (loicmathieu) [reply extensions/panache/mongodb-panache-common/runtime/src/main/java/io/quarkus/mongodb/panache/reactive/runtime/ReactiveMongoOperations.java]: Oh yes, I didn't scroll down the page :(
I added the missing operators, I didn't add `.$` as I'm afraid it could causes too much false positive.

File: extensions/panache/mongodb-panache-common/runtime/src/main/java/io/quarkus/mongodb/panache/reactive/runtime/ReactiveMongoOperations.java (hunk 2 above)
Comment (loicmathieu) [reply extensions/panache/mongodb-panache-common/runtime/src/main/java/io/quarkus/mongodb/panache/reactive/runtime/ReactiveMongoOperations.java]: I move the code on a dedicated method.
There is still duplication between the reactive and imperative variant but it is consistent with other methods/params that are duplicated between the two.

**Comment by loicmathieu** [comment]
> i don't see a test that actually executes the updated update statement. one thing i'm trying to remember from my morphia work is the nuance around $set. 

I didn't add a new one as we already have one inside the integration test: https://github.com/quarkusio/quarkus/blob/master/integration-tests/mongodb-panache/src/main/java/io/quarkus/it/mongodb/panache/test/TestResource.java#L132 but I agree we can add more tests.

> iirc, with $set it will do a full document replacement in the database rather than updating just the fields listed but i can't recall exactly. I would like to see a test that 1) actually executes the updates in the database and 2) makes sure we're not replacing whole documents when we're not intending to do so.

$set is a partial update, from the documentation: _The $set operator replaces the value of a field with the specified value._

Again, I agree we should have more test, but testing the behaviour of $set is something the MongoDB team should do, what we need to do is assert that we generates the right query. That's why I only added tests on the MongoOperationsTest.

**Comment by evanchooly** [comment]
Agreed about not testing `$set` directly.   I was mostly just trying to make sure it does what we want and that's the docs say.

As for testing the rest, I wanted to make sure the doc shape is correct but if there's an integration test that executes this code branch, that's great.  but I'm not seeing one that exercises the new code.  The test you link seems to only update fields and not update operators.  Am I missing that? That code's pretty dense but I didn't see any $ operators when I scanned it.

**Comment by loicmathieu** [comment]
> The test you link seems to only update fields and not update operators.

Yes, it updates fields without specifying any operator, so the $set operator will be added.

> That code's pretty dense but I didn't see any $ operators when I scanned it.

I only add tests to our update document binding test case, I'll add more tests on the integration test including some $ operators.

**Comment by loicmathieu** [comment]
@evanchooly I added tests inside the integration test with both $set and $inc.

**Review by evanchooly — APPROVED** [review]
