### PR TITLE
Better handling for null or empty authority

### LINKED ISSUE #51845: Inconsistent error behavior with an empty host header
### Describe the bug

UriInfoImpl.getBaseUri will throw an exception in some circumstances with an empty host header.

Reported in https://github.com/keycloak/keycloak/issues/45204

### Expected behavior

We see several different behaviors when issuing curl http or https requests with -H "Host:" or -H "Host: ", and using --http1.0, --http1.1, or --http2.

For example, if you issue an https request with --http1.1 and -H "Host:" you get:

```
2026-01-07 13:24:03,645 ERROR [io.quarkus.vertx.http.runtime.QuarkusErrorHandler] (vert.x-eventloop-thread-4) HTTP Request to /realms/master failed, error id: 43993d1b-c01c-4186-a894-89ff52464fbd-6: io.vertx.core.VertxException: For HTTP/1.x requests, the 'Host' header is required
```

Ideally all invalid situations could be handled like this - if an uncaught exception is thrown in a way that is handled by the Keycloak error handler, we instead end up with a stacktrace logged.

### Actual behavior

If you instead use -H "Host: ", there is now a stacktrace in the logs:

```
2026-01-07 13:25:10,272 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-1) Uncaught server error: java.lang.RuntimeException: java.net.URISyntaxException: Expected authority at index 8: https://
        at org.jboss.resteasy.reactive.server.jaxrs.LocationUtil.getUri(LocationUtil.java:34)
        at org.jboss.resteasy.reactive.server.jaxrs.UriInfoImpl.getBaseUri(UriInfoImpl.java:124)
        at org.jboss.resteasy.reactive.server.jaxrs.UriInfoImpl.getBaseUriBuilder(UriInfoImpl.java:129)
        at org.keycloak.url.HostnameV2Provider.getFrontUriBuilder(HostnameV2Provider.java:118)
        ...
org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$15.runWith(VertxCoreRecorder.java:645)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2651)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2630)
        at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1622)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1589)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.net.URISyntaxException: Expected authority at index 8: https://
        at java.base/java.net.URI$Parser.fail(URI.java:2995)
        at java.base/java.net.URI$Parser.failExpecting(URI.java:3001)
        at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3245)
        at java.base/java.net.URI$Parser.parse(URI.java:3196)
        at java.base/java.net.URI.<init>(URI.java:807)
        at org.jboss.resteasy.reactive.server.jaxrs.LocationUtil.getUri(LocationUtil.java:32)
        ... 21 more
```

As far as I can tell some kind of error handling is appropriate here - we are trying to construct an invalid URI with an empty authority. 

However in prior versions of quarkus at times this didn't matter. There was a subtle change with https://github.com/quarkusio/quarkus/issues/50293 - the old logic was doing https://github.com/quarkusio/quarkus/pull/50299/files#diff-daa425eb55bd2d8c8aba02c3d05803f5df14b85704f2fd377eb03da20df3c7a5L134 which passed the path in the URI constuctor. The new logic in LocationUtils, uses resolve instead:

```
new URI(request.getScheme(), request.getAuthority(), null, null, null).resolve(prefix + path)
```

When the authority is null or effectively "", the new logic will fail URI validation, but the old logic will work because the path was non-empty and you get a URI like http:/// - which of cousre is not valid.

### How to Reproduce?

1. Create an endpoint that calls UriInfo.getBaseUri
2. make a call to that endpoint like 'curl --insecure --http1.0 -v -H "Host: "  https://...', 'curl --insecure --http1.1 -v -H "Host: "  https://...', 'curl --http1.0 -v -H "Host: "  http://localhost...', 'curl --http1.1 -v -H "Host: "  http://localhost...' - observe a stacktrace in each of these scenarios.

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

http1.0 issues seem to have been in quarkus for a while. http1.1 has this behavior starting with 3.27.1.

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by shawkins**
http 1.0 allows for no host header, while http 1.1 allows for an empty one respectively. Several places need updated to account for those cases.

* Fixes #51845

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Comment by gsmet** [comment]
The CI error looks related to the changes.

**Comment by geoand** [comment]
Definitely

**Comment by shawkins** [comment]
@geoand @gsmet made the logic more explicit in the handling or relative uris.

**Comment by cescoffier** [comment]
Could you rebase to try to see if we can get a green build?

File: independent-projects/resteasy-reactive/server/vertx/src/main/java/org/jboss/resteasy/reactive/server/vertx/VertxResteasyReactiveRequestContext.java [hunk 1]
```diff
@@ -205,7 +207,11 @@ public String getRequestScheme() {
 
     @Override
     public String getRequestHost() {
-        return request.authority().toString();
+        HostAndPort authority = request.authority();
+        if (authority == null) {
+            return null;
+        }
+        return authority.toString();
```
Comment (cescoffier) [inline independent-projects/resteasy-reactive/server/vertx/src/main/java/org/jboss/resteasy/reactive/server/vertx/VertxResteasyReactiveRequestContext.java]: shouldn't it be just the host here? Do you also need the port? 
I found a bit dangerous to rely on toString. I would rebuild it.

**Review by cescoffier — CHANGES_REQUESTED** [review]

File: independent-projects/resteasy-reactive/server/vertx/src/main/java/org/jboss/resteasy/reactive/server/vertx/VertxResteasyReactiveRequestContext.java (hunk 1 above)
Comment (shawkins) [reply independent-projects/resteasy-reactive/server/vertx/src/main/java/org/jboss/resteasy/reactive/server/vertx/VertxResteasyReactiveRequestContext.java]: > shouldn't it be just the host here?

From the ServerHttpRequest.getRequestHost method name that is what I'd naturally expect. However that was not the behavior - it did return host:port when a non-default port is used.

> I found a bit dangerous to rely on toString. I would rebuild it.

Do you mean adding a explicit method to HostAndPort? And would you like to see ServerHttpRequest.getRequestHost documented or even deprecated?

Comment (shawkins) [reply independent-projects/resteasy-reactive/server/vertx/src/main/java/org/jboss/resteasy/reactive/server/vertx/VertxResteasyReactiveRequestContext.java]: @cescoffier adding the conversion to string inline and deprecated the getRequestHost method in favor of one called getRequestHostAndPort. If that's not what you had in mind, let me know.

Comment (cescoffier) [reply independent-projects/resteasy-reactive/server/vertx/src/main/java/org/jboss/resteasy/reactive/server/vertx/VertxResteasyReactiveRequestContext.java]: I would add the second method and deprecate `getRequestHost` explaining how to migrate.

Comment (shawkins) [reply independent-projects/resteasy-reactive/server/vertx/src/main/java/org/jboss/resteasy/reactive/server/vertx/VertxResteasyReactiveRequestContext.java]: Added the missing handling to ServletRequestContext and squashed the commits.

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
Thanks!

**Comment by mabartos** [comment]
@cescoffier @geoand Hey guys! Would it be possible to backport it to 3.27.x?

cc: @shawkins

**Comment by geoand** [comment]
As https://github.com/quarkusio/quarkus/issues/50293 was included in 3.27, this should be as well.
