### PR TITLE
Do not record active profile configuration name if a profile one exists

### LINKED ISSUE #39313: prod-profile configuration pollutes test profile in integration tests
### Describe the bug

The bug was introduces in Quarkus version `3.5.2`; it was not present in version `3.5.1`.

When we have configuration values for the `prod` profile in the `application.properties`, they "pollute" the profile set for `quarkus.test.integration-test-profile`, possibly leading to the test failing because the application fails to start.

An example:

We use an application with a postgres database, `quarkus-smallrye-health` and the following `application.properties`:

```properties
quarkus.http.test-port=-1
quarkus.test.integration-test-profile=test
quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.username=${DB_USER}
%prod.quarkus.datasource.password=${DB_PASSWORD}
%prod.quarkus.datasource.jdbc.additional-jdbc-properties.foo=${FOO}
```

We test that the database connection (provided by a devservice) is established with the following `@QuarkusTest`:

```java
package de.turing85.quarkus.properties;

import io.quarkus.test.junit.QuarkusTest;
import io.restassured.RestAssured;
import org.junit.jupiter.api.Test;

import static org.hamcrest.CoreMatchers.is;

@QuarkusTest
class HealthTest {
  @Test
  void healthTest() {
    // @formatter:off
    RestAssured
        .when().get("/q/health")
        .then()
            .body("checks.find { it.name = 'Database connections health check' }.status", is("UP"))
            .body("checks.find { it.name = 'Database connections health check' }.data.'<default>'", is("UP"));
    // @formatter:on
  }
}
```

and the following `@QuarkusIntegrationTest`:

```java
package de.turing85.quarkus.properties;

import io.quarkus.test.junit.QuarkusIntegrationTest;

@QuarkusIntegrationTest
class HealthTestIT extends HealthTest {
}
```

When we now run the tests, the application fails to start in the failsafe tests (the surefire tests work fine):

```bash
$ ./mvnw clean verify
...
[INFO] [stdout] ERROR: Failed to start application (with profile [test])
[INFO] [stdout] java.lang.RuntimeException: Failed to start quarkus
[INFO] [stdout] 	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
[INFO] [stdout] 	at io.quarkus.runtime.Application.start(Application.java:101)
[INFO] [stdout] 	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
[INFO] [stdout] 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
[INFO] [stdout] 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
[INFO] [stdout] 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
[INFO] [stdout] 	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
[INFO] [stdout] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[INFO] [stdout] 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[INFO] [stdout] 	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
[INFO] [stdout] 	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
[INFO] [stdout] Caused by: java.util.NoSuchElementException: SRCFG00011: Could not expand value FOO in property quarkus.datasource.jdbc.additional-jdbc-properties.foo
[INFO] [stdout] 	at io.smallrye.config.ExpressionConfigSourceInterceptor$1.accept(ExpressionConfigSourceInterceptor.java:85)
[INFO] [stdout] 	at io.smallrye.config.ExpressionConfigSourceInterceptor$1.accept(ExpressionConfigSourceInterceptor.java:61)
[INFO] [stdout] 	at io.smallrye.common.expression.ExpressionNode.emit(ExpressionNode.java:22)
[INFO] [stdout] 	at io.smallrye.common.expression.Expression.evaluateException(Expression.java:56)
[INFO] [stdout] 	at io.smallrye.common.expression.Expression.evaluate(Expression.java:70)
[INFO] [stdout] 	at io.smallrye.config.ExpressionConfigSourceInterceptor.getValue(ExpressionConfigSourceInterceptor.java:61)
[INFO] [stdout] 	at io.smallrye.config.ExpressionConfigSourceInterceptor.getValue(ExpressionConfigSourceInterceptor.java:35)
[INFO] [stdout] 	at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
[INFO] [stdout] 	at io.smallrye.config.SecretKeysHandlerConfigSourceInterceptor.getValue(SecretKeysHandlerConfigSourceInterceptor.java:25)
[INFO] [stdout] 	at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
[INFO] [stdout] 	at io.smallrye.config.FallbackConfigSourceInterceptor.getValue(FallbackConfigSourceInterceptor.java:24)
[INFO] [stdout] 	at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
[INFO] [stdout] 	at io.smallrye.config.SmallRyeConfig.getConfigValue(SmallRyeConfig.java:322)
[INFO] [stdout] 	at io.smallrye.config.SmallRyeConfig.getValue(SmallRyeConfig.java:229)
[INFO] [stdout] 	at io.smallrye.config.ConfigMappingProvider.lambda$processLazyMapValue$0(ConfigMappingProvider.java:504)
[INFO] [stdout] 	at io.smallrye.config.ConfigMappingProvider.mapConfigurationInternal(ConfigMappingProvider.java:990)
[INFO] [stdout] 	at io.smallrye.config.ConfigMappingProvider.lambda$mapConfiguration$3(ConfigMappingProvider.java:962)
[INFO] [stdout] 	at io.smallrye.config.SecretKeys.doUnlocked(SecretKeys.java:28)
[INFO] [stdout] 	at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:962)
[INFO] [stdout] 	at io.smallrye.config.ConfigMappings.mapConfiguration(ConfigMappings.java:91)
[INFO] [stdout] 	at io.smallrye.config.SmallRyeConfigBuilder.build(SmallRyeConfigBuilder.java:699)
[INFO] [stdout] 	at io.quarkus.runtime.generated.Config.readConfig(Unknown Source)
[INFO] [stdout] 	at io.quarkus.runtime.generated.Config.createRunTimeConfig(Unknown Source)
[INFO] [stdout] 	at io.quarkus.deployment.steps.RuntimeConfigSetup.deploy(Unknown Source)
[INFO] [stdout] 	... 11 more
...
```

### Expected behavior

The tests should succeed.

### Actual behavior

The application fails to start with the above error

### How to Reproduce?

Reproducer:
- clone https://github.com/turing85/quarkus-properties:
  ```bash
  git clone https://github.com/turing85/quarkus-properties.git && quarkus-properties
  ```
- build the application, run the tests:
  ```bash
  ./mvnw clean verify
  ```
- Observe the error mentioned above
- Open `pom.xml`, set `quarkus.platform.version` from `3.5.2` to `3.5.1`
- Re-run the tests:
  ```bash
  ./mvnw clean verify
  ```
- Observe that the build succeeds

### Output of `uname -a` or `ver`
```
Linux XXX 5.15.0-52-generic #58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

### Output of `java -version`
```
openjdk version "21.0.2" 2024-01-16 LTS
OpenJDK Runtime Environment Temurin-21.0.2+13 (build 21.0.2+13-LTS) 
OpenJDK 64-Bit Server VM Temurin-21.0.2+13 (build 21.0.2+13-LTS, mixed mode, sharing)
```
### Quarkus version or git rev

`3.5.2` onwards

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
```
Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae) 
Maven home: /home/marco/.m2/wrapper/dists/apache-maven-3.9.6-bin/3311e1d4/apache-maven-3.9.6
Java version: 21.0.2, vendor: Eclipse Adoptium, runtime: /opt/java/mandrel/23.1.2.0-java21
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.15.0-52-generic", arch: "amd64", family: "unix"
```
### Additional information

_No response_

### PR DESCRIPTION
**Pull request by radcortez**
- Fixes #39313

### CODE REVIEW

File: core/deployment/src/main/java/io/quarkus/deployment/configuration/BuildTimeConfigurationReader.java [hunk 1]
```diff
@@ -1108,8 +1108,10 @@ public Set<String> getPropertyNames() {
                             return Collections.emptySet();
                         }
                     });
+
+            String[] profiles = config.getProfiles().toArray(new String[] {});
```
Comment (dmlloyd) [inline core/deployment/src/main/java/io/quarkus/deployment/configuration/BuildTimeConfigurationReader.java:1112]:
```suggestion
            String[] profiles = config.getProfiles().toArray(String[]::new);
```

File: core/deployment/src/main/java/io/quarkus/deployment/steps/ConfigGenerationBuildStep.java [hunk 2]
```diff
@@ -217,6 +218,14 @@ void generateBuilders(
             defaultValues.put(e.getKey(), e.getValue());
         }
         // Recorded values from build time from any other source (higher ordinal then defaults, so override)
+        String[] profiles = ConfigProvider.getConfig().unwrap(SmallRyeConfig.class).getProfiles().toArray(new String[] {});
```
Comment (dmlloyd) [inline core/deployment/src/main/java/io/quarkus/deployment/steps/ConfigGenerationBuildStep.java:221]:
```suggestion
        String[] profiles = ConfigProvider.getConfig().unwrap(SmallRyeConfig.class).getProfiles().toArray(String[]::new);
```

**Review by dmlloyd — APPROVED** [review]
LGTM other than a couple minor details.
