### PR TITLE
Take RestMulti headers and status into account when using SSE resource method

### LINKED ISSUE #44902: Setting headers for SSE annotated Multi resources is ignoring headers
### Describe the bug

Setting response headers as shown below does not work when the resource is annotated with `@Produces(MediaType.SERVER_SENT_EVENTS)` or `@RestStreamElementType(MediaType.APPLICATION_JSON)`. 

```java
        @POST
        @Path("sse-multi")
        @Produces(MediaType.SERVER_SENT_EVENTS)
        public Multi<String> sseMulti() {
            return RestMulti.fromMultiData(Multi.createFrom().items("hello", "world")).header("Foo", "Bar").build();
        }

```

See also https://github.com/quarkusio/quarkus/issues/44898#issuecomment-2514837180 

### Expected behavior

headers are set as in 

```java
        @POST
        @Path("multi")
        public Multi<String> multi() {
            return RestMulti.fromMultiData(Multi.createFrom().items("hello", "world")).header("Foo", "Bar").build();
        }

```

### Actual behavior

header is ignored 

### How to Reproduce?

I will provide a draft PR with a unit test. 

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by dastrobu**
- Fixes: #44902

### CODE REVIEW

**Comment by dastrobu** [comment]
I am not sure I find the time right now. There is quite a bit of code to understand. The way you proposed does not seem to work out of the box, as there is some header handling going on in `handleSse` already: https://github.com/quarkusio/quarkus/blob/72302396092053fa648ab7d0300843634f66c73d/independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/handlers/PublisherResponseHandler.java#L346

There are also quite a few FIXME comments from @FroMage in this code section.

**Comment by geoand** [comment]
Some adjustments will probably be needed, but my guess is that it shouldn't require figuring out much of what the test of the code does

**Comment by geoand** [comment]
I have updated this PR to include a fix for the issue

File: independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/handlers/PublisherResponseHandler.java [hunk 1]
```diff
@@ -312,38 +317,39 @@ private boolean requiresChunkedStream(MediaType mediaType) {
...
-            RestMulti.SyncRestMulti rest = (RestMulti.SyncRestMulti) result;
+        if (result instanceof RestMulti.SyncRestMulti rest) {
             demand = rest.getDemand();
         } else {
             demand = 1L;
         }
 
-        SseUtil.setHeaders(requestContext, requestContext.serverResponse(), streamingResponseCustomizers);
+        List<StreamingResponseCustomizer> customizers = determineCustomizers(result, true, streamingResponseCustomizers);
+        SseUtil.setHeaders(requestContext, requestContext.serverResponse(), customizers);
```
Comment (dastrobu) [inline independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/handlers/PublisherResponseHandler.java:352]: I think we need to subscribe first and write headers on the first item, as done in `StreamingMultiSubscriber`. Otherwise customizers from `upstream` in `AsyncRestMulti` won't pick up. See test case `testReturnRestSse3`.

File: extensions/resteasy-reactive/rest/deployment/src/test/java/io/quarkus/resteasy/reactive/server/test/customproviders/MultiResponseHeadersTest.java [hunk 2]
```diff
@@ -0,0 +1,64 @@
+package io.quarkus.resteasy.reactive.server.test.customproviders;
```
Comment (dastrobu) [inline extensions/resteasy-reactive/rest/deployment/src/test/java/io/quarkus/resteasy/reactive/server/test/customproviders/MultiResponseHeadersTest.java:1]: shall I delete this in favor of `ResponseHeaderTest` cases?

**Comment by dastrobu** [comment]
@geoand thanks, I did no look through the code in detail, but I think its not handling all cases correctly. I extended `ResponseHeaderTest` to cover the same cases as for non-SSE Multis. I can probably delete `MultiResponseHeadersTest` as it seems to be redundant.

**Comment by geoand** [comment]
If you have cases which don't work with the current implementation, please add tests for them

File: extensions/resteasy-reactive/rest/deployment/src/test/java/io/quarkus/resteasy/reactive/server/test/customproviders/MultiResponseHeadersTest.java (hunk 2 above)
Comment (geoand) [reply extensions/resteasy-reactive/rest/deployment/src/test/java/io/quarkus/resteasy/reactive/server/test/customproviders/MultiResponseHeadersTest.java:1]: It probably makes sense to merge them, yeah

Comment (dastrobu) [reply extensions/resteasy-reactive/rest/deployment/src/test/java/io/quarkus/resteasy/reactive/server/test/customproviders/MultiResponseHeadersTest.java]: removed, all cases are covered by ResponseHeaderTest

**Comment by geoand** [comment]
@dastrobu let me know when you are done so I can check the latest tests.

Thanks

**Comment by dastrobu** [comment]
I had to rebase and force push, as quarkus-bot was complaining about the merge: 

quarkus-bot
/ Check Pull Request - Merge commits

Error - Pull request commit check
[sha=2f089a593200bd8c229aa53ca9e8671238d9744a ; message="Merge remote-tracking branch 'dastrobu/test/sse-response-header-test' into test/sse-response-header-test"]

I think I am done, but let's wait for CI to see the test cases. 
Locally, there are two cases that are not passing: 

* testReturnRestSse3()
* testReturnRestSse5()

We probably need to squash commits before merging in the end, but I don't want to do that right now as long as contributing from both ends.

**Comment by geoand** [comment]
Don't worry about the bot and squashing the commits, I'll take care of that. 

> I think I am done

Okay, thanks

**Comment by geoand** [comment]
This is now ready to go. Thanks a lot @dastrobu!

**Comment by dastrobu** [comment]
@geoand thanks for implementing the fix. It was a pleasure to collaborate on a PR that quickly. It's a rare experience in the open-source universe.

**Comment by geoand** [comment]
🙏🥰

**Comment by geoand** [comment]
The test failure is related, I'll have a look tomorrow

**Review by gastaldi — APPROVED** [review]

File: independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/handlers/PublisherResponseHandler.java [hunk 3]
```diff
@@ -46,32 +47,98 @@ public void setStreamingResponseCustomizers(List<StreamingResponseCustomizer> st
...
         SseMultiSubscriber(ResteasyReactiveRequestContext requestContext, List<StreamingResponseCustomizer> staticCustomizers,
-                long demand) {
+                Publisher publisher, long demand) {
             super(requestContext, staticCustomizers, demand);
+            this.publisher = publisher;
+        }
+
+        @Override
+        public void onSubscribe(Subscription s) {
+            this.subscription = s;
```
Comment (cescoffier) [inline independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/handlers/PublisherResponseHandler.java:67]: You need to ensure that you do not receive a subscription twice. In this case, you need to cancel the new one. Obviously, it means that the subscription must be stored in an atomic reference or in a volatile with the atomic companion object.

File: independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/handlers/PublisherResponseHandler.java [hunk 4]
```diff
@@ -46,32 +47,98 @@ public void setStreamingResponseCustomizers(List<StreamingResponseCustomizer> st
...
+                doSend(item);
             }
-            SseUtil.send(requestContext, event, staticCustomizers).whenComplete((v, t) -> {
+        }
+
+        private void doSend(Object item) {
+            SseUtil.send(requestContext, fromItem(item), staticCustomizers).whenComplete((v, t) -> {
                 if (t != null) {
                     // need to cancel because the exception didn't come from the Multi
                     subscription.cancel();
```
Comment (cescoffier) [inline independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/handlers/PublisherResponseHandler.java:116]: If you cancel, onComplete and onNext should not be called anymore - so you may need a proper terminal state.

**Review by cescoffier — CHANGES_REQUESTED** [review]
@jponge please have a look - I'm not sure the control flow is totally correct.

File: independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/handlers/PublisherResponseHandler.java [hunk 5]
```diff
@@ -46,32 +47,98 @@ public void setStreamingResponseCustomizers(List<StreamingResponseCustomizer> st
...
             super(requestContext, staticCustomizers, demand);
+            this.publisher = publisher;
+        }
+
+        @Override
+        public void onSubscribe(Subscription s) {
+            this.subscription = s;
+            // we only request one item initially because we need to use that item to create the headers
+            // that will be sent in the first empty response
+            s.request(1);
```
[the remark this answers is not in the document]
Comment (geoand) [reply independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/handlers/PublisherResponseHandler.java:70]: I am yes

File: independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/handlers/PublisherResponseHandler.java [hunk 6]
```diff
@@ -46,32 +47,98 @@ public void setStreamingResponseCustomizers(List<StreamingResponseCustomizer> st
...
+        public void onComplete() {
+            // make sure we don't trigger cancel with our onCloseHandler
+            weClosed = true;
+            // in this case the stream only had one item that we have yet to send (as we are waiting for the empty buffer to be sent)
+            if (state == 1) {
+                // do nothing as we still need to send the first item
+                // the connection will be closed by doSend when the item is sent
+            } else {
+                // no need to cancel on complete
+                // FIXME: are we interested in async completion?
```
[the remark this answers is not in the document]
Comment (geoand) [reply independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/handlers/PublisherResponseHandler.java:83]: This is an old comment I just copied over. I can clean it up in a follow up as I really don't know what it means (I think @FroMage added it when he did the initial implementation)

File: independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/handlers/PublisherResponseHandler.java (hunk 3 above)
Comment (jponge) [reply independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/handlers/PublisherResponseHandler.java:67]: It depends, you might want your operator to support fan-out, but it's not what we usually do indeed, so storing the subscription in a `AtomicReference<Flow.Subscription>` and cancelling when already subscribed is a common idiom.

File: independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/handlers/PublisherResponseHandler.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (jponge) [reply independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/handlers/PublisherResponseHandler.java:70]: Yep, that's fine here

File: independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/handlers/PublisherResponseHandler.java [hunk 7]
```diff
@@ -46,32 +47,98 @@ public void setStreamingResponseCustomizers(List<StreamingResponseCustomizer> st
...
+            // that will be sent in the first empty response
+            s.request(1);
+        }
+
+        @Override
+        public void onComplete() {
+            // make sure we don't trigger cancel with our onCloseHandler
+            weClosed = true;
+            // in this case the stream only had one item that we have yet to send (as we are waiting for the empty buffer to be sent)
+            if (state == 1) {
```
[the remark this answers is not in the document]
Comment (jponge) [reply independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/handlers/PublisherResponseHandler.java:78]: An `int` + `volatile` might be fine, just make sure you don't have any interleaving or read/writes with other concurrent signals (e.g., cancelling ,etc).

File: independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/handlers/PublisherResponseHandler.java [hunk 8]
```diff
@@ -46,32 +47,98 @@ public void setStreamingResponseCustomizers(List<StreamingResponseCustomizer> st
...
+                            // now we can actually send the first item
+                            doSend(item);
+                        } else {
+                            requestContext.resume(throwable);
+                        }
+                    }
+                });
             } else {
-                event = new OutboundSseEventImpl.BuilderImpl().data(item).build();
+                doSend(item);
```
[the remark this answers is not in the document]
Comment (jponge) [reply independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/handlers/PublisherResponseHandler.java:108]: That shall be captured by the state machine (e.g., have I been cancelled? have I been errored? have I completed?)

**Review by jponge — DISMISSED** [review]
We can have another look after changes have been made (mostly to the state machine side of things).

That being said what we should do here is a check with the RS TCK (see https://github.com/reactive-streams/reactive-streams-jvm/blob/master/tck-flow/README.md).

A few pointers:

- using TestNG in JUnit5, because the TCK is in TestNG https://github.com/smallrye/smallrye-mutiny-zero/blob/main/mutiny-zero/pom.xml#L50
- a few examples https://github.com/smallrye/smallrye-mutiny-zero/blob/main/mutiny-zero/src/test/java/mutiny/zero/tck

File: independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/handlers/PublisherResponseHandler.java (hunk 3 above)
Comment (geoand) [reply independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/handlers/PublisherResponseHandler.java:67]: This can't happen in this case as we explicitly control when the subscription is made.

**Comment by geoand** [comment]
PR updated

File: independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/handlers/PublisherResponseHandler.java (hunk 6 above)
[the remark this answers is not in the document]
Comment (FroMage) [reply independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/handlers/PublisherResponseHandler.java]: 🤷

**Comment by cescoffier** [comment]
@jponge can you have another quick look?

**Review by cescoffier — APPROVED** [review]

**Review by jponge — COMMENTED** [review]
Looks ok to me, you can go ahead. 

But a TCK check of the custom subscribers would be good to have one day.
