### PR TITLE
Ensure YAML configuration is taken into account for DynamicFeatures

### LINKED ISSUE #18237: YAML configuration ignored for JAX-RS Dynamic Features
## Describe the bug
In my projects, I use the YAML extension and after migrating to Quarkus 2.0, I realized that my YAML configuration is no more taken into account in case of JAX-RS Dynamic Features. 

Indeed in my projects, I use a `DynamicFeature` to manage dynamically the authentication / authorization, and this feature is configured indirectly thanks to a couple of `@ConfigProperty` whose value is located into YAML configuration file. With migrating to Quarkus 1.13 and before, the value of the properties could be retrieved from the YAML file, since Quarkus 2.0, I end up with an error of type `java.util.NoSuchElementException: SRCFG00014: The config property <property name> is required but it could not be found in any config source`

### Expected behavior
The value of my properties can be retrieved from the YAML as before

### Actual behavior
The value of my properties can not be retrieved from the YAML file since [this change](https://github.com/quarkusio/quarkus/commit/abb7978101f98ebfc8eba201140395347f526137#) because the initialization of the `DynamicFeature`s is done during the static init phase while "Discovered Sources" (sources retrieved thanks to the `ServiceLoader` via `ConfigSource` or `ConfigSourceProvider`) are now only added at startup time such that the YAML files are not taken into account to initialize the `DynamicFeature`'s instance.

## To Reproduce

Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific).

Or attach an archive containing the reproducer to the issue.

1.  Adds the yaml extension to your project
2. Adds a `DynamicFeature` containing a field annotated with a `@ConfigProperty`
3. Adds a file `application.yaml` containing a value of the property defined in step 2

### Output of `uname -a` or `ver`

`Darwin MBP-A36950NF 18.7.0 Darwin Kernel Version 18.7.0: Mon May  3 20:41:19 PDT 2021; root:xnu-4903.278.68~1/RELEASE_X86_64 x86_64`

### Output of `java -version`

```
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9)
OpenJDK 64-Bit Server VM (build 11.0.10+9, mixed mode)

```

### Quarkus version or git rev

`2.0.0.Final`

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

```
Maven home: /usr/local/Cellar/maven/3.6.3_1/libexec
Java version: 11.0.10, vendor: Oracle Corporation, runtime: /usr/local/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home
Default locale: fr_FR, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.6", arch: "x86_64", family: "mac"
```

### PR DESCRIPTION
**Pull request by essobedo**
fixes #18237 

## Motivation

Value of properties defined into a YAML file cannot be used anymore since Quarkus 2.0 in case of JAX-RS `DynamicFeature`s

## Modifications:

* Adds a test case showing the problem
* Proposes a potential fix to define the `ConfigPropertyProvider` of the yaml extension as `StaticInitConfigSourceProviderBuildItem `

### CODE REVIEW

**Comment by geoand** [comment]
This seems perfectly reasonable to me

**Comment by essobedo** [comment]
@geoand 
> This seems perfectly reasonable to me

Not for @radcortez as he prefers a solution that would work with all `ConfigPropertyProvider`s. See the discussion in the original ticket for more details https://github.com/quarkusio/quarkus/issues/18237#issuecomment-870980141

@radcortez Do I close this PR?

**Comment by geoand** [comment]
Of course Roberto is the subject matter expert here, so it's up to him

**Comment by radcortez** [comment]
> @geoand
> 
> > This seems perfectly reasonable to me
> 
> Not for @radcortez as he prefers a solution that would work with all `ConfigPropertyProvider`s. See the discussion in the original ticket for more details [#18237 (comment)](https://github.com/quarkusio/quarkus/issues/18237#issuecomment-870980141)
> 
> @radcortez Do I close this PR?

If you can work around with my proposal, yes :) Did that work?

**Comment by essobedo** [comment]
@radcortez If your workaround is to initialize "manually" the Bean that I inject into my DynamicFeature as next:

My class file
```
@Singleton
public class MyBean {

    String property;

    @Inject
    void init(Config config) {
        this.property = config.getValue("property.value", String.class);
    }
}
```

My file `config/application.yml`

```
property:
   value: foo

```

The answer is no, it doesn't work as it still uses a `Config` instance created during the static init phase which does use the "discovered" config sources.

My current workaround is to somehow fork the config-yaml extension with this fix, I could not found any better way for now 😞

**Comment by radcortez** [comment]
No, that was not what I was thinking.

You need to do the lookup in the `filter` method with `ConfigProvider.getConfig` and retrieve the value there. Yes, this adds some extra calls on each call, but it should be ok. An alternative is to just lazy load the field in an `AtomicReference` on the first `filter` call and then you avoid additional calls to `Config`.

**Comment by essobedo** [comment]
> No, that was not what I was thinking.
> 
> You need to do the lookup in the `filter` method with `ConfigProvider.getConfig` and retrieve the value there. Yes, this adds some extra calls on each call, but it should be ok. An alternative is to just lazy load the field in an `AtomicReference` on the first `filter` call and then you avoid additional calls to `Config`.

Ah I see, your idea is to delay the initialization to make it happen during at worse the startup time but in my use case I cannot do that, I need my bean to be initialized when calling the configure method of my DynamicFeature which happens during the static init phase.

**Comment by radcortez** [comment]
Not exactly. You let the bean initialize without any value (or a default). Then inside the `filter` method, you do a lookup of the right configuration value (this will only be called when the filter is called and way beyond startup). 

Something like:
```
@Priority(1001)
 public class GreetingFilter implements ContainerResponseFilter {
     private AtomicReference<String> message = new AtomicReference();
     private CountDownLatch init = new CountDownLatch(1);

     @Override
     public void filter(ContainerRequestContext containerRequestContext, ContainerResponseContext containerResponseContext)
             throws IOException {

        ensureInit();

         containerResponseContext.getHeaders().add("X-MESSAGE", message);
     }

     private void ensureInit( {
            if (message.compareAndSet(null, "some-default"))) {
                ConfigProvider.getConfig().getOptionalValue("my.property", String.class).ifPresent(message::set);
                init.countDown();
            } else {
                try {
                    init.await();
                } catch (final InterruptedException e) {
                    // log
                }
            }
        }
 }
```

I did by memory, so I hope I didn't forget anything, but I hope you get the idea :)

**Comment by essobedo** [comment]
@radcortez Yeah it is what I understood from your previous comment but unfortunately my real use case is not exactly what I put in the PR, I added a filter just to be able to easily test the value injected into the DynamicFeature.

My real use case is more:

```
@Provider
public class MyDynamicFeature implements DynamicFeature {

    @Inject
    MyBean bean;

    @Override
    public void configure(ResourceInfo resourceInfo, FeatureContext featureContext) {
        if ("foo".equals(bean.property)) {
            // Do something in case of foo
        } else if ("bar".equals(bean.property)) {
            // Do something in case of bar
        }
    }
}
```

I'm afraid that your workaround is not applicable in my use case since the bean needs to be initialized when calling the configure method and the configure method is called during the static init phase 😢

**Comment by radcortez** [comment]
Ok, let's work on this PR and try to solve this use case while we think of another solution for the overall problem.

File: extensions/config-yaml/deployment/src/main/java/io/quarkus/config/yaml/deployment/ConfigYamlProcessor.java [hunk 1]
```diff
@@ -17,10 +17,10 @@ public FeatureBuildItem feature() {
 
     @BuildStep
     public void bootstrap(
-            BuildProducer<AdditionalBootstrapConfigSourceProviderBuildItem> additionalBootstrapConfigSourceProvider) {
-        additionalBootstrapConfigSourceProvider.produce(new AdditionalBootstrapConfigSourceProviderBuildItem(
+            BuildProducer<AdditionalStaticInitConfigSourceProviderBuildItem> additionalBootstrapConfigSourceProvider) {
```
Comment (radcortez) [inline extensions/config-yaml/deployment/src/main/java/io/quarkus/config/yaml/deployment/ConfigYamlProcessor.java:20]: We cannot replace the provider build item. It needs a new step to produce the `AdditionalStaticInitConfigSourceProviderBuildItem` and keep the `AdditionalBootstrapConfigSourceProviderBuildItem`.

I guess we don't have a test for the bootstrap part, so it would be great to add it as well to make sure it works on both phases.

File: integration-tests/resteasy-jackson/src/main/java/io/quarkus/it/resteasy/jackson/GreetingDynamicFeature.java [hunk 2]
```diff
@@ -0,0 +1,21 @@
...
+import javax.enterprise.inject.Instance;
+import javax.ws.rs.container.DynamicFeature;
+import javax.ws.rs.container.ResourceInfo;
+import javax.ws.rs.core.FeatureContext;
+import javax.ws.rs.ext.Provider;
+
+import org.eclipse.microprofile.config.inject.ConfigProperty;
+
+@Provider
+public class GreetingDynamicFeature implements DynamicFeature {
```
Comment (radcortez) [inline integration-tests/resteasy-jackson/src/main/java/io/quarkus/it/resteasy/jackson/GreetingDynamicFeature.java:12]: I'll prefer it if the test is moved to `integration-tests/smallrye-config`. I know that this is not smallrye-config related, but I would like to have a central piece where all (or most) of the config stuff is tested, so we don't have to go around and run multiple projects.

**Review by radcortez — CHANGES_REQUESTED** [review]

**Comment by essobedo** [comment]
@radcortez remarks addressed, please check again

**Review by radcortez — APPROVED** [review]
Better. Thank you. Let's wait for CI now.

**Comment by essobedo** [comment]
@radcortez the CI seems to be happy, is something missing before being merged?

**Comment by radcortez** [comment]
Yes. This one should go first: https://github.com/quarkusio/quarkus/pull/17483 and then this one rebased on.

**Comment by gsmet** [comment]
@radcortez I merged #17483 . It appears this one still applies cleanly. Should we merge or it requires additional adjustments?

**Comment by radcortez** [comment]
The used `AdditionalStaticInitConfigSourceProviderBuildItem` is now deprecated in favour of `StaticInitConfigSourceProviderBuildItem`. If @essobedo wants to update it it :)

**Comment by essobedo** [comment]
> The used `AdditionalStaticInitConfigSourceProviderBuildItem` is now deprecated in favour of `StaticInitConfigSourceProviderBuildItem`. If @essobedo wants to update it it :)

No PBR, I will

**Comment by radcortez** [comment]
> > The used `AdditionalStaticInitConfigSourceProviderBuildItem` is now deprecated in favour of `StaticInitConfigSourceProviderBuildItem`. If @essobedo wants to update it it :)
> 
> No PBR, I will

Thanks!

**Comment by essobedo** [comment]
Should be done, let's see what the CI says

**Comment by gsmet** [comment]
CI looks happy :). @radcortez I let you check that everything is OK and merge? Thanks!
