### PR TITLE
Handle gradle multiple source directories in test extension

### LINKED ISSUE #13155: Gradle + mixed Kotlin/Java application: @QuarkusTest ignores annotations on classes implemented in Java
**Describe the bug**
When an application relies on Gradle to compile code implemented in both Kotlin and Java, then any Quarkus test (`@QuarkusTest`) will ignore annotations on classes implemented in Java.

Only `./gradlew test` with `@QuarkusTest` is affected:

* `./gradlew quarkusDev` works perfectly
* Maven works perfectly too, be it with `./mvnw test` or `./mvnw initialize quarkus:dev`.

**Expected behavior**

I expected annotations on Java classes to be detected.

**Actual behavior**

Annotations on Java classes are ignored. For example, a bean annotated with `@ApplicationScoped` will be ignored and attempting to inject it will fail:

```
                javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type io.quarkus.bugs.java.JavaComponent and qualifiers [@Default]
                        - java member: io.quarkus.bugs.KotlinService#javaComponent
                        - declared on CLASS bean [types=[io.quarkus.bugs.KotlinService, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkus.bugs.KotlinService]
```

**To Reproduce**

Reproducer with Gradle: https://github.com/yrodiere/quarkus-bug-mixed-kotlin-java

Run `./gradlew clean test`: it fails.

```
                javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type io.quarkus.bugs.java.JavaComponent and qualifiers [@Default]
                        - java member: io.quarkus.bugs.KotlinService#javaComponent
                        - declared on CLASS bean [types=[io.quarkus.bugs.KotlinService, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkus.bugs.KotlinService]
```

Run `./gradlew quarkus:dev`, then `curl http://0.0.0.0:8080/hello`: it works.

```
hello from JavaComponent
```

See the branch `maven` on the same repository for a proof that it works with Maven.

Run `mvn initialize quarkus:dev` (`initialize` is necessary to add another source directory), then `curl http://0.0.0.0:8080/hello`: it works.

```
hello from JavaComponent
```

Run `mvn clean test`: it works.

```
[INFO] BUILD SUCCESS
```

**Configuration**
N/A

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `Linux yrodiere.redhat 5.8.17-200.fc32.x86_64 #1 SMP Thu Oct 29 18:14:53 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
 - Output of `java -version`: 
  ```
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9+11, mixed mode)
  ```
 - GraalVM version (if different from Java): N/A
 - Quarkus version or git rev: 1.9.2
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 

**Additional context**

I believe the culprit is in how `QuarkusTestExtension` infers the location of classes. What it does:

* Take the test class, retrieve its location (`io.quarkus.test.common.PathTestHelper#getTestClassesLocation`)
* Use a hardcoded map to infer the location of main classes (`io.quarkus.test.common.PathTestHelper#getAppClassLocationForTestLocation`).

But in the case of Gradle with Kotlin*and* Java code, the source code is in two different directories (`src/main/kotlin` and `src/main/java`), and the compiled classes as well (`build/classes/java` and `build/classes/kotlin`). `QuarkusTestExtension` only uses `build/classes/kotlin`, which explains the problem.

Regarding the use case, it may seem exotic, but for Kotlin, I don't think it is:

* Gradle seems rather popular in the Kotlin world, so I'd expect it to be the default choice for Kotlin projects? At the very least, [Kotlin projects generated by Intellij IDEA are based on Gradle](https://kotlinlang.org/docs/tutorials/jvm-get-started.html).
* That the main annotation processor for Kotlin ([kapt](https://kotlinlang.org/docs/reference/kapt.html)) produces Java code by default. So if you write only Kotlin code in a Quarkus application, and you need to generate beans or otherwise annotated classes through an annotation processor, you will be affected.
* Even if you don't use annotation processors, [Java interop](https://kotlinlang.org/docs/tutorials/mixing-java-kotlin-intellij.html), and the ability to mix Java and Kotlin code in the same project, is apparently an important feature of Kotlin.

On example of annotation processors that produce CDI beans: MapStruct, frequently used to map between DTO and entities. It generates "mapper" classes that [can be injected using CDI](https://mapstruct.org/documentation/stable/reference/html/#retrieving-mapper).

### PR DESCRIPTION
**Pull request by glefloch**
Gradle source output depends on the language: 

- `java` output goes to `build/classes/java/main`
- `kotlin` output goes to `build/classes/kotlin/main`
- `scala` output goes to `build/classes/scala/main`

In the `QuarkusTestExtension`, there is a one-to-one matching that is done from the test class directory to find the corresponding `main` source directory. 
In a gradle project, if there is more than just one language, only one source output will be added to the context.

close #13155

### CODE REVIEW

**Comment by geoand** [comment]
Seems like CI is grumpy :)

File: test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java [hunk 1]
```diff
@@ -195,7 +198,21 @@ private ExtensionState doJavaStart(ExtensionContext context, Class<? extends Qua
...
-                BuildToolHelper.enableGradleAppModelForTest(projectRoot);
+                QuarkusModel model = BuildToolHelper.enableGradleAppModelForTest(projectRoot);
+                final Set<File> classDirectories = model.getWorkspace().getMainModule().getSourceSet().getSourceDirectories();
+                for (File classes : classDirectories) {
+                    if (!rootBuilder.contains(classes.toPath())) {
+                        rootBuilder.add(classes.toPath());
+                    }
+                }
+            } else if (System.getProperty(BootstrapConstants.OUTPUT_SOURCES_DIR) != null) {
+                final String[] sourceDirectories = System.getProperty(BootstrapConstants.OUTPUT_SOURCES_DIR).split(",");
```
Comment (aloubyansky) [inline test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java:209]: If a project has only one output test dir, wouldn't this dir be added twice? I.e. through this property and the default test dir that would have been added w/o this code?

**Comment by glefloch** [comment]
@geoand yes, I forgot to check if we were in a gradle project. Looks better now :)

**Comment by geoand** [comment]
Seems good to me. Up to @aloubyansky since he has comments about the bootstrap related things

File: test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java (hunk 1 above)
Comment (aloubyansky) [reply test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java:211]: Yes, that's ok.

However, could you remind me why we did `BuildToolHelper.enableGradleAppModelForTest(projectRoot)`? Is this to support IDEs?

Comment (aloubyansky) [reply test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java:211]: `BuildToolHelper.enableGradleAppModelForTest(projectRoot)` is already checking whether it's a gradle project, btw.

Comment (glefloch) [reply test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java:211]: Yes exactly if you come from the IDE the model has not been serialized yet. This is why there is those two similar blocks. 
I added the check in the `if` because the `BuildToolHelper.enableGradleAppModelForTest(projectRoot)` returns `null` if it's not a Gradle project. You are right, it's better to check if the returned model is not null rather than checking if this a Gradle project (as the method recursively look for a build file). I will update the code

**Review by aloubyansky — APPROVED** [review]

**Review by aloubyansky — APPROVED** [review]
