### PR TITLE
Fix url encoding issue for Dev UI Page with unusual chars

### LINKED ISSUE #39992: () breaks title in devui
### Describe the bug

```
card.addPage(Page.externalPageBuilder("HomeAssistant (admin/secret)")
                        .url(uiPath, uiPath)
                        .isHtmlContent()
                        .icon("font-awesome-solid:house"));
```

result in url generated to have () in it and then not work.

raises 3 questions:

1) should ( and / and ) not be escape or at least properly routed?
2) is there a better way to handle adding info in the label/title
3) i.e. should I be able to set componentName separate from the human readable title?

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by phillip-kruger**
Fix #39992

This PR does:
1) Removes a unused line of JS.
2) Encode the page id
3) Allow multiple static labels

### CODE REVIEW

**Review by cescoffier — APPROVED** [review]
I would not use the term funny, maybe `unusual`?

**Comment by geoand** [comment]
Please add the proper labels in that case.

Thanks

File: extensions/vertx-http/dev-ui-spi/src/main/java/io/quarkus/devui/spi/page/Page.java [hunk 1]
```diff
@@ -61,6 +64,12 @@ protected Page(String icon,
 
     public String getId() {
         String id = this.title.toLowerCase().replaceAll(SPACE, DASH);
+        try {
+            id = URLEncoder.encode(id, StandardCharsets.UTF_8.toString());
```
Comment (gsmet) [inline extensions/vertx-http/dev-ui-spi/src/main/java/io/quarkus/devui/spi/page/Page.java:68]: Is it used for all pages? I would expect the URL to be stable, regardless of the changes in the title?

Should we provide a clean and stable id instead?

If we don't, maybe we could still use something a bit cleaner and an approach similar to https://github.com/slugify/slugify (without necessarily using this library).

Comment (gsmet) [reply extensions/vertx-http/dev-ui-spi/src/main/java/io/quarkus/devui/spi/page/Page.java:68]: Yes. Exactly my thought.

I'm not saying we cannot merge this. But I'm not sure it's the ideal solution. URLs should be stable as much as possible.

Comment (phillip-kruger) [reply extensions/vertx-http/dev-ui-spi/src/main/java/io/quarkus/devui/spi/page/Page.java:68]: Let's open a separate issue for that, it's a bigger piece of work
