### PR TITLE
Configuration properties references for keycloak-authorization extension

### LINKED ISSUE #8469: documentation for Keycloak authorization is insufficient
**Describe the bug**
I've spent some time investigating usage of the `quarkus-keycloak-authorization` extension in the OpenShift context and found a few insufficiencies in the documentation. Specifically:

- [ ] 1. In OpenShift, the `/health` endpoint (and possibly also `/metrics`) must always be accessible. However, if I use `quarkus-keycloak-authorization`, it takes over the entire URL space, OpenShift can't reach the health endpoint and the application is never ready. (Yes, I always include health checks. If I omitted them, this wouldn't be a problem, but that's always a bad idea.) This behavior is probably correct from Keycloak perspective, but it took me a long time to figure out how to make my application work.

    I first tried to configure the Keycloak realm to let anyone and everyone access `/health/*`. But I wasn't able to figure out the correct Keycloak configuration. I'm certainly no Keycloak expert, for sure. Then, I spent some time in the debugger and in the end, I have found some undocumented configuration options that let me disable authz for the `/health` endpoint:

    ```properties
    quarkus.keycloak.policy-enforcer.enable=true
    quarkus.keycloak.policy-enforcer.paths.health.path=/health/*
    quarkus.keycloak.policy-enforcer.paths.health.enforcement-mode=DISABLED
    ```

    There should be a reference for all these additional options (unless they are not documented because the config shape is experimental and will change in the future, in which case I'd suggest something needs to be stabilized at least for the health check usecase). I'd also say there should be an example -- ideally with this exact usecase.

- [ ] 2. The documentation also says (https://quarkus.io/guides/security-keycloak-authorization#mapping-protected-resources) that `quarkus.keycloak.policy-enforcer.lazy-load-paths` defaults to `false`, which wrong. It clearly defaults to `true`: https://github.com/quarkusio/quarkus/blob/73fc9276ae/extensions/keycloak-authorization/runtime/src/main/java/io/quarkus/keycloak/pep/runtime/KeycloakPolicyEnforcerConfig.java#L67-L68 That documentation section should be rewritten.

- [x] 3. In OpenShift, it is rather easy for a small clock skew to happen between the Keycloak server and the Quarkus application. In my case, I've seen Keycloak being cca 10 seconds _ahead_ of the Quarkus app. In such case, I had weird 403 errors, because the token _wasn't yet valid_. It is possible to setup some leeway using `quarkus.oidc.token.expiration-grace`, but the documentation isn't really clear in this regard. It sounds like it only affects token expiration check, but it also affects token issue time check. This should be at least clearly mentioned in https://quarkus.io/guides/security-openid-connect#quarkus-oidc_quarkus.oidc.token.expiration-grace, but if the property had a more accurate name, that would be better.

### PR DESCRIPTION
**Pull request by pedroigor**
Fixes #8469

### CODE REVIEW

File: extensions/keycloak-authorization/runtime/src/main/java/io/quarkus/keycloak/pep/runtime/KeycloakPolicyEnforcerConfig.java [hunk 1]
```diff
@@ -41,7 +41,7 @@
          * Specifies how policies are enforced.
          */
         @ConfigItem(defaultValue = "ENFORCING")
```
Comment (gsmet) [inline extensions/keycloak-authorization/runtime/src/main/java/io/quarkus/keycloak/pep/runtime/KeycloakPolicyEnforcerConfig.java:43]: Could you make `enforcing` lowercase? For enums, the doc will advertise the values in lowercase with dashes so better have the default value consistent.

**Review by gsmet — CHANGES_REQUESTED** [review]

**Review by sberyozkin — APPROVED** [review]
@pedroigor Hey Pedro, thanks for a quick fix

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
I pushed an additional commit with the case change. Let's wait for CI.
