### PR TITLE
ArC: use a separate lock for each bean in generated ContextInstances

### LINKED ISSUE #37958: Upgrading from 3.5.3 to 3.6.1 ,3.6.3,3.6.4 Quakust test will not start with Thread Thread[vert.x-eventloop-thread-6,5,main] has been blocked for 2460 m
### Describe the bug

Starting a quarkus test it will not start because it will block the following exception. We have at the same time smallrye-jwt and oidc installed. Using quarkus.arc.optimize-contexts=false it starts correctly and works . 
 
```posh
at java.base@17.0.9/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@17.0.9/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
	at java.base@17.0.9/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:715)
	at java.base@17.0.9/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:938)
	at java.base@17.0.9/java.util.concurrent.locks.ReentrantLock$Sync.lock(ReentrantLock.java:153)
	at java.base@17.0.9/java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:322)
	at io.quarkus.arc.generator.Default_jakarta_enterprise_context_ApplicationScoped_ContextInstances.c319(Unknown Source)
	at io.quarkus.arc.generator.Default_jakarta_enterprise_context_ApplicationScoped_ContextInstances.computeIfAbsent(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:38)
	at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:21)
	at io.quarkus.oidc.runtime.OidcAuthenticationMechanism_ClientProxy.arc$delegate(Unknown Source)
	at io.quarkus.oidc.runtime.OidcAuthenticationMechanism_ClientProxy.getCredentialTypes(Unknown Source)
	at io.quarkus.vertx.http.runtime.security.HttpAuthenticator.<init>(HttpAuthenticator.java:43)
	at io.quarkus.vertx.http.runtime.security.HttpAuthenticator_Bean.doCreate(Unknown Source)
	at io.quarkus.vertx.http.runtime.security.HttpAuthenticator_Bean.create(Unknown Source)
	at io.quarkus.vertx.http.runtime.security.HttpAuthenticator_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:117)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:41)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:38)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:32)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.ComputingCacheContextInstances.computeIfAbsent(ComputingCacheContextInstances.java:18)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:38)
	at io.quarkus.vertx.http.runtime.security.HttpAuthenticator_Bean.get(Unknown Source)
	at io.quarkus.vertx.http.runtime.security.HttpAuthenticator_Bean.get(Unknown Source)
	at io.quarkus.arc.impl.InstanceImpl.getBeanInstance(InstanceImpl.java:325)
	at io.quarkus.arc.impl.InstanceImpl.getInternal(InstanceImpl.java:309)
	at io.quarkus.arc.impl.InstanceImpl.get(InstanceImpl.java:190)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$AbstractAuthenticationHandler.handle(HttpSecurityRecorder.java:220)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$AbstractAuthenticationHandler.handle(HttpSecurityRecorder.java:208)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1286)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:144)
	at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:68)
	at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:37)
	at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$2.handle(HttpServerCommonHandlers.java:83)
	at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$2.handle(HttpServerCommonHandlers.java:66)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$1.handle(VertxHttpRecorder.java:162)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$1.handle(VertxHttpRecorder.java:138)
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:55)
	at io.vertx.core.impl.DuplicatedContext.emit(DuplicatedContext.java:179)
	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:174)
	at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:159)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:153)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1471)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1334)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1383)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@17.0.9/java.lang.Thread.run(Thread.java:840)
```

### Expected behavior

quarkus should start 

### Actual behavior

_No response_

### How to Reproduce?

using the following feature Installed features: [cache, cdi, hibernate-validator, kafka-client, micrometer, mongodb-client, oidc, opentelemetry, reactive-routes, rest-client, rest-client-jackson, resteasy, resteasy-jackson, resteasy-multipart, scheduler, security, servlet, smallrye-context-propagation, smallrye-fault-tolerance, smallrye-health, smallrye-jwt, smallrye-openapi, smallrye-reactive-messaging, smallrye-reactive-messaging-kafka, swagger-ui, vertx]

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mkouba**
- fixes #37958

I'd like to stress that I would still recommend users to avoid things like calling external services in the `@PostConstruct`/`@PreDestroy` callbacks. Very often it's not clear when exactly a bean will be instantiated and since the API is blocking an undesired behavior may occur.

CC @franz1981 - I've replaced the `forEach()` method with `removeEach()` which is more useful for the request context destruction. It would be great if you could run some perf benchmarks so that we can be sure that this PR does not cause any significant perf regression. Although I expect a perf drop because we must use a separate lock for each bean...

### CODE REVIEW

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/ContextInstancesGenerator.java [hunk 1]
```diff
@@ -63,226 +63,222 @@ Collection<Resource> generate(DotName scope) {
...
-        ResultHandle ret = tryBlock.newInstance(MethodDescriptor.ofConstructor(HashSet.class));
-        for (FieldDescriptor field : idToField.values()) {
-            ResultHandle copy = tryBlock.readInstanceField(field, tryBlock.getThis());
-            tryBlock.ifNotNull(copy).trueBranch().invokeInterfaceMethod(MethodDescriptors.SET_ADD, ret, copy);
+        getAllPresent.invokeVirtualMethod(MethodDescriptor.ofMethod(contextInstances.getClassName(), "lockAll", void.class),
+                getAllPresent.getThis());
+        ResultHandle ret = getAllPresent.newInstance(MethodDescriptor.ofConstructor(HashSet.class));
+        for (InstanceAndLock fields : idToFields.values()) {
+            ResultHandle copy = getAllPresent.readInstanceField(fields.instance, getAllPresent.getThis());
+            getAllPresent.ifNotNull(copy).trueBranch().invokeInterfaceMethod(MethodDescriptors.SET_ADD, ret, copy);
```
Comment (Ladicek) [inline independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/ContextInstancesGenerator.java:123]: This could in theory throw `OutOfMemoryError` or something similarly unlikely, so maybe we should wrap this all in a `try/catch` and `unlockAll` in the `catch` block?

**Comment by Ladicek** [comment]
LGTM, just wondering how [un]likely is it that we reach the method bytecode size limit. Have you checked?

**Comment by mkouba** [comment]
> LGTM, just wondering how [un]likely is it that we reach the method bytecode size limit. Have you checked?

Nope. I only used your https://github.com/Ladicek/arc-crazybeans with 500 `@ApplicationScoped` beans to test the generated `ContextInstances`...

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/ContextInstancesGenerator.java (hunk 1 above)
Comment (mkouba) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/ContextInstancesGenerator.java:123]: Well, if there's an `OutOfMemoryError` I don't think it would help a lot...

**Comment by Ladicek** [comment]
I would expect 500 beans to be fine, but wouldn't be sure about 5000 beans :-)

**Comment by franz1981** [comment]
I'm still in vacation, but...do we really need any lock?
We cannot use atomic ref set release/get acquire?
In theory we just care about visibility, because we have no defined any expected behaviour with concurrent updates...this will solve any potential problem, would improve performance, and guarantee visibility rules to work (at the expense of atomicity, which I don't still see why we should enforce).

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/ContextInstancesGenerator.java (hunk 1 above)
Comment (Ladicek) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/ContextInstancesGenerator.java:123]: We could alternatively do what `removeEach` does: under the lock, only copy the fields into local variables, and do everything else after unlocking.

**Comment by mkouba** [comment]
> I would expect 500 beans to be fine, but wouldn't be sure about 5000 beans :-)

Hm, so 1500 beans is OK but somewhere above this number I get an `org.objectweb.asm.MethodTooLargeException`. But I believe that we would get the same even before this PR.

I can try to reduce the size of the relevant methods but honestly, I'd rather document to use `quarkus.arc.optimize-contexts=false` for this kind of "microservice" ;-).

**Comment by Ladicek** [comment]
IIUC, we need to guarantee (at least for normal scopes) that if a contextual instance is needed, exactly one is created, even if multiple threads ask for it at the "same" time.

**Comment by mkouba** [comment]
> I'm still in vacation, but...do we really need any lock? We cannot use atomic ref set release/get acquire? In theory we just care about visibility, because we have nor defined any expected behaviour with concurrent updates...this will solve any potential problem, would improve performance, and guarantee visibility rules to work (at the expense of atomicity, which I don't still see why we should enforce).

It's not only about visibility. We need to make sure that exactly one bean instance is created.

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/ContextInstancesGenerator.java (hunk 1 above)
Comment (mkouba) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/ContextInstancesGenerator.java]: Done.

**Comment by franz1981** [comment]
@mkouba which translate in N getAndSet/compareAndSet/getVolatile based on the case..mwhixh still means saving a MonitorExit-volatile store op, per instance (which I am checking now if is a volatile store as I fear).

Additionally it means saving memory too, because you can have atomic ref field updaters saving any additional lock instance.

**Comment by franz1981** [comment]
> IIUC, we need to guarantee (at least for normal scopes) that if a contextual instance is needed, exactly one is created, even if multiple threads ask for it at the "same" time.

The allocation happen in the critical protected region, or we assume we can produce more then one but let just one to win?
I'd the former we just need to have 2 states and a loop.

eg
1. getVolatile and eventually CompareAndSet(none, alloc)
2. Loss: exit
3. Win: allocate bean and putRelease(bean)

In this way you still have a single volatile op

**Comment by mkouba** [comment]
> @mkouba which translate in N getAndSet/compareAndSet/getVolatile based on the case, saving a MonitorExit-volatile store op, per instance (which I am checking now if is a volatile store as I fear).
> 
> Additionally it means saving memory too, because you can have N static final atomic ref field updaters saving any additional lock instance and a generic util method which just need to bass the atomic reference as param and perform the expected pattern. Additionally, by doing it right, we would preserve the same behaviour of CHM, while now we perform a lock/unlock while reading vs being lock free.

I cannot say I completely understand that "perf gibberish" above :D but `compareAndSet()` from `AtomicReference` and `AtomicReferenceFieldUpdater` is not usable here because we need to compute the bean instance lazily and only once...

**Comment by franz1981** [comment]
On @https://github.com/quarkusio/quarkus/pull/37982#issuecomment-1875378251 I have expressed a potential protocol in 2 phases (claim + commit value)

**Comment by Ladicek** [comment]
> > IIUC, we need to guarantee (at least for normal scopes) that if a contextual instance is needed, exactly one is created, even if multiple threads ask for it at the "same" time.
> 
> The allocation happen in the critical protected region, or we assume we can produce more then one but let just one to win and be set? I'd the former we just need to have 2 states and a loop.
> 
> eg
> 
>     1. getVolatile and eventually CompareAndSet(none, alloc)
> 
>     2. Loss: exit
> 
>     3. Win: allocate bean and putRelease(bean)

If I understand you correctly, the `alloc` thing is a sentinel that marks "some thread won a CAS and is in the process of creating an instance". This doesn't work, because CAS losers cannot simply exit (returning `null` I suppose). They must wait in one way or another. Maybe spinning wouldn't be so bad in this situation, but we're calling an external callback to create the instance, so I would be cautious about that.

**Comment by franz1981** [comment]
@Ladicek if the guarantee is to return what ever is set or setting ourself, yep, the loop is the appropriate behaviour. Consider that in case the caller thread is virtual we can still accept using Thread.yield while waiting, which would work fine. Given that the allocation is not supposed to perform I/O (I hope!! Correct me please if I am wrong) it shouldn't be a big deal

**Comment by Ladicek** [comment]
So if I understand you correctly, `computeIfAbsent` would look roughly like this:

```java
Object value = this.1; // volatile read
if (value != null && value != SENTINEL) {
    return value;
}
if (CAS(this.1, null, SENTINEL) {
    value = instanceSupplier.get();
    this.1 = value; // volatile write
    return value;
} else {
    while (value == null || value == SENTINEL) {
        Thread.onSpinWait();
        value = this.1; // volatile read
    }
}
```

This could even be written as a `static` method in some util class, accepting a `VarHandle` or `AtomicReferenceFieldUpdater`, it wouldn't need to be generated with Gizmo.

I guess that's doable, but we'd have to make sure that `getIfPresent` and `remove` handle the presence of `SENTINEL` correctly.

I'm not sure how the bulk-processing methods (`getAllPresent`, `clear` / `forEach` or `removeEach`) would work. Clearing probably isn't too big of a deal, if someone accesses a context that is being destroyed, they are doing something wrong. Now, `getAllPresent` is used to do 2 things: create a `Map<Bean<?>, Object` and destroy an instance. The `Map` cannot possibly be "accurate at the end" in case of concurrent access, but we should easily be able to guarantee "accurate at the beginning", which should be enough. The usage of `getAllPresent` to destroy an instance is IMHO an oversight and should be reimplemented using `remove`.

Which leaves me wondering about spinning. I didn't look at what the suppliers do. I'll check.

**Comment by franz1981** [comment]
Yep, the only suggestion is to replace the volatile store with a lazySet/setRelease, because it doesn't need any Store load barrier and still work fine, because it should be translated as

X = supplier.get();
LoadStore
StoreStore
Store X

The 2 barriers are a nop in x86 and are mostly compiler barriers which doesn't cost.
It will still guarantee safe publication of the value X even if it is not immutable.

**Comment by Ladicek** [comment]
OK so the supplier does 2 things:

1. Call `Contextual.create()`
2. Create a `ContextInstanceHandleImpl`

The second step is very cheap, and the first one is usually also fairly cheap, but in case of synthetic beans, `Contextual.create()` can do _anything_. So that's a bit worrying.

**Comment by franz1981** [comment]
@Ladicek given that the provided util method is written just once, I think adding a local counter for the number of spin and then force a LockSupport::parkNanos(50000L) to be the safer choice. It would save burning too much CPU while waiting the value to be available.

**Comment by mkouba** [comment]
> OK so the supplier does 2 things:
> 
>     1. Call `Contextual.create()`
> 
>     2. Create a `ContextInstanceHandleImpl`
> 
> 
> The second step is very cheap, and the first one is usually also fairly cheap, but in case of synthetic beans, `Contextual.create()` can do _anything_. So that's a bit worrying.

Also in case of #37958 it calls an external service...

**Comment by mkouba** [comment]
So I'm not against experimenting with the lock-less approach described above. But:

1. It should be discussed in a separate PR.
2. It's even less readable/maintainable. Which is OK since it's an implementation detail of a perf optimization. OTOH it means fewer people will be able to maintain this code.
3. In any case, I'd like to see some numbers before we make a sacrifice.

**Comment by franz1981** [comment]
@mkouba 
For 

> In any case, I'd like to see some numbers before we make a sacrifice.

Do you already have a micro benchmark with a non-trivial but still realistic number of beans?
If yes, we can just compare this PR as it is vs existing approach, and we can first evaluate what is the impact.
What we could extract from this is that by cutting in half the number of volatile operations, meaning that it can just improve over the existing approach.

Just an hint: to make such microbenchmark more realistic, add a configurable parameter `work` (with 0, 10, 100 values) which can be used to call `BlackHole.consumeCpu(work)` in the benchmarking method, to simulate user work between atomic operations (or could be used inside the supplier too, to emulate longer bean creations, even better).

**Comment by mkouba** [comment]
> > > OK so the supplier does 2 things:
> > > ```
> > > 1. Call `Contextual.create()`
> > > 
> > > 2. Create a `ContextInstanceHandleImpl`
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > The second step is very cheap, and the first one is usually also fairly cheap, but in case of synthetic beans, `Contextual.create()` can do _anything_. So that's a bit worrying.
> > 
> > 
> > Also in case of #37958 it calls an external service...
> 
> That's in `@PostConstruct`, that should be outside of the code path we're interested in here, right?

I don't think so. A `@PostConstruct` callback is executed within `Contextual#create()`. `@PostConstruct` and  `@AroundConstruct` interceptors will be called too.

**Comment by Ladicek** [comment]
Ouch, I didn't realize that. In that case, I'm against spinning, as we basically allow running arbitrary user code there.

**Comment by mkouba** [comment]
> @Ladicek @mkouba Couldn't we know that upfront? synthetic beans could make use of a lock, given that we expect them to call alien/long ops, and rather spinning in the other case?

Like I mentioned in https://github.com/quarkusio/quarkus/pull/37982#issuecomment-1875564908 it's not only about synthetic beans. We cannot simply detect all those cases...

**Comment by Ladicek** [comment]
I was thinking we possibly _could_ detect all the cases that involve custom user code (synthetic beans, beans with lifecycle callbacks or lifecycle interceptors), but then looking at `BeanGenerator.implementCreate()`, our implementation of `Contextual.create()` also runs `Contextual.create()` for all beans injected into the one we're creating, possibly recursively. So this can be quite a lot of code that needs to be executed.

**Comment by mkouba** [comment]
> I was thinking we possibly _could_ detect all the cases that involve custom user code (synthetic beans, beans with lifecycle callbacks or lifecycle interceptors), but then looking at `BeanGenerator.implementCreate()`, our implementation of `Contextual.create()` also runs (EDIT: _may_ run) `Contextual.create()` for all beans injected into the one we're creating, possibly recursively. So this can be quite a lot of code that needs to be executed.

That code would be quite complex. Don't forget that the fact that a bean `@ApplicationScoped Foo` has the `@ApplicationScoped Bar` dependency does not necesarilly mean that `Bar` will be instantiated when `Foo` is created - that depends on the state of the app.

**Comment by franz1981** [comment]
If is too conplex let's give it on this, but maybe we can still make the instances volatile and allow a first volatile read without using any locks before entering the lock, if null; it won't help benchmarks but probably the real world (under a certain definition of such...there are bigger problems in users code usually :P)

**Comment by gsmet** [comment]
@mkouba we just got a second report of this causing issues, should we make the default `false` for next 3.6 micro and make further progress for 3.7?

**Comment by manovotn** [comment]
> @mkouba we just got a second report of this causing issues, should we make the default `false` for next 3.6 micro and make further progress for 3.7?

I haven't had the time to fully delve into the details here but it seems it might be better to apply the fix suggested here and then continue iterating on it based on what Francesco and Ladislav wrote. My understading was that the current fix is not inherently wrong, just perhaps not optimal. Or did I miss something?

**Comment by mkouba** [comment]
> My understading was that the current fix is not inherently wrong, just perhaps not optimal. Or did I miss something?

@manovotn That is my understanding as well ;-). At least we know that it fixes #37958 and #38040. My [simple benchmarks](https://github.com/mkouba/arc-benchmarks) do not show a significant regression either. 

> @mkouba we just got a second report of this causing issues, should we make the default false for next 3.6 micro and make further progress for 3.7?

@gsmet I'd rather get this fix in and backport to 3.6 if needed.

Of course, I'd like to continue with investigation in this area. First, we need some more benchmarks...

**Comment by gsmet** [comment]
@mkouba oh I think I wasn't very clear: I completely agree we should pursue with the fix. My only worry is that it might be too complex to backport thus why I proposed to switch the default in 3.6.

But maybe it's better to push the fix to 3.6 to have some more bake time before the LTS.

Let me know what you prefer.

**Comment by mkouba** [comment]
> My only worry is that it might be too complex to backport thus why I proposed to switch the default in 3.6.

@gsmet Would it help if we prepare a separate branch for 3.6?

**Review by Ladicek — APPROVED** [review]
LGTM, just wondering if this thing fell through the cracks:

> I can try to reduce the size of the relevant methods but honestly, I'd rather document to use quarkus.arc.optimize-contexts=false for this kind of "microservice" ;-).

**Comment by mkouba** [comment]
> LGTM, just wondering if this thing fell through the cracks:
> 
> > I can try to reduce the size of the relevant methods but honestly, I'd rather document to use quarkus.arc.optimize-contexts=false for this kind of "microservice" ;-).

It didn't but I cannot find a good place in the docs. I mean, currently we don't generate the docs for the `optimize-contexts` config property (https://github.com/quarkusio/quarkus/pull/36626#discussion_r1370149491) :shrug:

**Review by manovotn — APPROVED** [review]
I tried to go through this mainly by comparing the generated `ContextInstances` class before and after this code change and I think it looks good.
Given that it fixes the two reported scenarios, I'd get this merged and discuss further optimizations in separate PRs/issues.

**Comment by gsmet** [comment]
@mkouba I will try to backport it once it's merged and will let you know if we need a specific branch. No need to do the work if it's not required.

**Comment by mkouba** [comment]
> @mkouba I will try to backport it once it's merged and will let you know if we need a specific branch. No need to do the work if it's not required.

There is a `record` in this PR so I'm prettty sure it won't be that easy :-(

**Comment by gsmet** [comment]
Ah, yes so we will need a separate branch. FWIW, I would be a bit cautious about using Java 17 features in fixes for now.

**Comment by mkouba** [comment]
@gsmet FYI https://github.com/mkouba/quarkus/tree/issue-37982-36. It contains 2 commits (from this PR and https://github.com/quarkusio/quarkus/pull/37529)

**Comment by gsmet** [comment]
This has been backported as part of https://github.com/quarkusio/quarkus/pull/38069 .

**Comment by Ladicek** [comment]
> > LGTM, just wondering if this thing fell through the cracks:
> > > I can try to reduce the size of the relevant methods but honestly, I'd rather document to use quarkus.arc.optimize-contexts=false for this kind of "microservice" ;-).
> 
> It didn't but I cannot find a good place in the docs. I mean, currently we don't generate the docs for the `optimize-contexts` config property ([#36626 (comment)](https://github.com/quarkusio/quarkus/pull/36626#discussion_r1370149491)) 🤷

Just got this silly idea this morning: how about we disable this optimization automatically in case there's more than, say, 1000 beans in the application? It could be per context, but I think globally would be fine too.

**Comment by mkouba** [comment]
> > > LGTM, just wondering if this thing fell through the cracks:
> > > > I can try to reduce the size of the relevant methods but honestly, I'd rather document to use quarkus.arc.optimize-contexts=false for this kind of "microservice" ;-).
> > 
> > 
> > It didn't but I cannot find a good place in the docs. I mean, currently we don't generate the docs for the `optimize-contexts` config property ([#36626 (comment)](https://github.com/quarkusio/quarkus/pull/36626#discussion_r1370149491)) 🤷
> 
> Just got this silly idea this morning: how about we disable this optimization automatically in case there's more than, say, 1000 beans in the application? It could be per context, but I think globally would be fine too.

That is actually a good idea. And 1000 is a nice number. Hm, maybe we could change the type of the property to string and do something similar to `ArcConfig.removeUnusedBeans`. The set of supported values would be `true`, `false` and `auto`. Where if the `auto` value is used the optimization would be disabled if more than 1000 beans is found. WDYT?

**Comment by Ladicek** [comment]
That makes sense to me.

**Comment by manovotn** [comment]
> Just got this silly idea this morning: how about we disable this optimization automatically in case there's more than, say, 1000 beans in the application? It could be per context, but I think globally would be fine too.

That's great idea! +1

**Comment by mkouba** [comment]
For the record: https://github.com/quarkusio/quarkus/pull/38121
