### PR TITLE
ArC - include logging category in "enable debug logging" messages

### LINKED ISSUE #42575: state which category to enable debugging for
### Description

I get this in log:

```
2024-08-15 15:47:14,095 ERROR [io.qua.arc.imp.DefaultAsyncObserverExceptionHandler] (executor-thread-1) Failure occurred while notifying an async Observer [method=org.acme.GreetingResource#onStateChanged(io.quarkiverse.homeassistant.runtime.events.GenericEvent)] for event of type io.quarkiverse.homeassistant.runtime.events.GenericEvent 
- please enable debug logging to see the full stack trace
```

...but what category is it I need to enable debug logging for ? doing it for all generates *a lot* of noise.

### Implementation ideas

have the errror message actually print what needs to be put in applicaiton.properties to log the right thing.

### PR DESCRIPTION
**Pull request by manovotn**
Fixes #42575

### CODE REVIEW

File: independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl/EventImpl.java [hunk 1]
```diff
@@ -493,14 +493,14 @@ public void run() {
             } catch (Exception e) {
                 // swallow exception and log errors for every problematic OM
                 LOG.errorf(
-                        "Failure occurred while notifying a transational %s for event of type %s " +
-                                "\n- please enable debug logging to see the full stack trace" +
-                                "\n %s",
-                        observerMethod, eventContext.getMetadata().getType().getTypeName(),
+                        "Failure occurred while notifying a transactional %s for event of type %s"
+                                + "\n- to see the full stack trace, add quarkus.log.category.\"%s\".level=DEBUG " +
```
Comment (Ladicek) [inline independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl/EventImpl.java:497]: Not super psyched about inconsistent position of `+` at the beginning/end of line here :-)

**Review by Ladicek — APPROVED** [review]
LGTM

**Review by mkouba — APPROVED** [review]

**Comment by gsmet** [comment]
Thanks!
