### PR TITLE
Carriover data after vert.x mdc reinitialization

### LINKED ISSUE #51808: [Regression:3.30.5] Using Otel results in losing MDC data set in RequestFilters
### Describe the bug

When using OpenTelemetry's `@WithSpan` annotation (e.g. in a normal method and/or in an `HttpAuthenticationMechanism`), MDC (Mapped Diagnostic Context) values set in JAX-RS **request** filters are lost . This appears to be a regression introduced in Quarkus 3.30.5.

The issue occurs when:

1.  A method (e.g. on an HttpAuthenticationMechanism)with @WithSpan annotation executes during request processing
2. A JAX-RS `ContainerRequestFilter` sets MDC values
3. The MDC values set in the request filter are no longer present (e.g. when the access log is written)

Interestingly, MDC values set in `ContainerResponseFilter`(note req vs resp...)  are preserved correctly.

This may be related to changes in https://github.com/quarkusio/quarkus/pull/51641 and/or https://github.com/quarkusio/quarkus/issues/43134 (cc @brunobat  ), introduced in version 3.30.5 (see release notes: https://github.com/quarkusio/quarkus/releases/tag/3.30.5)

Note that I have 2 PRs in my repro repo that illustrate going back to 3.30.4 _or_ not using Otel fixes things https://github.com/lloydmeta/quarkus-mdc-bug/pulls

### Expected behavior

MDC values set in request filters should be preserved throughout the entire request lifecycle.

### Actual behavior

MDC values set in request filters are lost in requests that go through methods with @WithSpan completes execution.

### How to Reproduce?

Reproducer: https://github.com/lloydmeta/quarkus-mdc-bug

Run `./gradlew test`

The tests fails with:

```
org.opentest4j.AssertionFailedError: MDC field set in request filter should be available. MDC contents:
    {spanId=0b45b58e38976741, response.filter.field=from the response filter,
    traceId=0126307879c80193f6577629fe9e035d, sampled=true} ==> expected: <from the request filter> but was: <null>
          at com.beachape.MdcCaptureTest.authedEndpoint_shouldHaveExpectedMdcFields_fromRequestFilter(MdcCaptureTes
    t.java:36)
```

Note that response.filter.field is present, but request.filter.field is missing.

### Output of `uname -a` or `ver`

Darwin Mac 25.2.0 Darwin Kernel Version 25.2.0: Tue Nov 18 21:07:05 PST 2025; root:xnu-12377.61.12~1/RELEASE_ARM64_T6020 arm64

### Output of `java -version`

openjdk 25.0.1 2025-10-21

### Quarkus version or git rev

3.30.5

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 9.1.9

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by brunobat**
Fixes https://github.com/quarkusio/quarkus/issues/51808

Created a new method on VertxMDC to copy non tracing data when we clear the MDC object reference. See `VertxMDC.reinitializeVertxMdc()`
Log scope close inconsistency only on debug. 

This is a continuation of https://github.com/quarkusio/quarkus/pull/51641
And also replaces https://github.com/quarkusio/quarkus/pull/51810

### CODE REVIEW

**Comment by brunobat** [comment]
I'll be creating more tests... We have almost no VertxMDC related tests.

**Comment by Ladicek** [comment]
I'm honestly not quite sure what we do in `VertxMDC` and it seems to me our reliance on Vert.x `DuplicatedContext` to do context propagation has reached far beyond its actual usefulness. It is clear to me now that the `DuplicatedContext` usefulness ends where contexts shorter than the request context begin. MDC seems to be one of those cases. I'm not gonna block this PR, but I'm also gonna say that we need to stop this and figure out an actual solution.

File: extensions/vertx/runtime/src/main/java/io/quarkus/vertx/core/runtime/VertxMDC.java [hunk 1]
```diff
@@ -239,6 +257,20 @@ public boolean isEmpty() {
...
+     * @param vertxContext
+     * @return
+     */
+    public boolean isEmpty(Context vertxContext) {
+        return contextualDataMap(vertxContext).isEmpty();
+    }
+
+    public Set<String> getKeys() {
+        return contextualDataMap(getContext()).keySet();
+    }
```
Comment (dmlloyd) [inline extensions/vertx/runtime/src/main/java/io/quarkus/vertx/core/runtime/VertxMDC.java:273]: Would this key set be mutable? Is that intentional?

File: extensions/vertx/runtime/src/main/java/io/quarkus/vertx/core/runtime/VertxMDC.java [hunk 2]
```diff
@@ -289,12 +321,45 @@ public void clear(Context vertxContext) {
      *
      * @param vertxContext
      */
-    public void clearVertxMdcFromContext(Context vertxContext) {
+    void clearVertxMdcFromContext(Context vertxContext) {
```
Comment (dmlloyd) [inline extensions/vertx/runtime/src/main/java/io/quarkus/vertx/core/runtime/VertxMDC.java:325]: I guess this is technically an API change that could feasibly break compatibility.

File: extensions/vertx/runtime/src/main/java/io/quarkus/vertx/core/runtime/VertxMDC.java [hunk 3]
```diff
@@ -289,12 +321,45 @@ public void clear(Context vertxContext) {
...
     }
 
+    /**
+     * Clears out the object ref from the context to force a new one to be created and prevent thread crosstalk.
+     * Also copies to the new reference any previous data not in the set of MDC keys to discard.
+     *
+     * @param vertxContext
+     * @param discardMdcKeys Entries not to be copied over to the new MDC
+     */
+    public void reinitializeVertxMdc(Context vertxContext, Set<String> discardMdcKeys) {
```
Comment (dmlloyd) [inline extensions/vertx/runtime/src/main/java/io/quarkus/vertx/core/runtime/VertxMDC.java:338]: Is this guaranteed to be called while no other threads are messing with the Vert.x context and/or its MDC? If not, there is a lot of racing that could happen here.

**Comment by brunobat** [comment]
> I'm honestly not quite sure what we do in `VertxMDC` and it seems to me our reliance on Vert.x `DuplicatedContext` to do context propagation has reached far beyond its actual usefulness. It is clear to me now that the `DuplicatedContext` usefulness ends where contexts shorter than the request context begin. MDC seems to be one of those cases. I'm not gonna block this PR, but I'm also gonna say that we need to stop this and figure out an actual solution.

That's a fair assessment of the limitations but please beware that there are no other mechanisms to propagate state in a reliable way. This VertxMDC is inspired in the recommended way Vert.x propagates MDC. See: https://github.com/reactiverse/reactiverse-contextual-logging/tree/release/1.2.1

File: extensions/vertx/runtime/src/main/java/io/quarkus/vertx/core/runtime/VertxMDC.java (hunk 1 above)
Comment (brunobat) [reply extensions/vertx/runtime/src/main/java/io/quarkus/vertx/core/runtime/VertxMDC.java:273]: No, will fix.

File: extensions/vertx/runtime/src/main/java/io/quarkus/vertx/core/runtime/VertxMDC.java (hunk 2 above)
Comment (brunobat) [reply extensions/vertx/runtime/src/main/java/io/quarkus/vertx/core/runtime/VertxMDC.java:325]: No worries, I introduced the method on Quarkus 3.30.4. No one is using this.

File: extensions/vertx/runtime/src/main/java/io/quarkus/vertx/core/runtime/VertxMDC.java (hunk 3 above)
Comment (brunobat) [reply extensions/vertx/runtime/src/main/java/io/quarkus/vertx/core/runtime/VertxMDC.java:338]: Honestly, I'm not sure. In theory, when it's a Vert.x managed thread there is no concurrent access... Unless object references are leaking between contexts, which is the purpose of `void clearVertxMdcFromContext(Context vertxContext)` introduced on the previous PR. When Thread pools are involved, I'm not sure.
Beware all these are Duplicated Contexts.

**Comment by Ladicek** [comment]
> That's a fair assessment of the limitations but please beware that there are no other mechanisms to propagate state in a reliable way.

There is (MP Context Propagation), but it comes with other downsides.

> This VertxMDC is inspired in the recommended way Vert.x propagates MDC. See: https://github.com/reactiverse/reactiverse-contextual-logging/tree/release/1.2.1

Note that the way Vert.x / Reactiverse Contextual Logging propagates MDC only works if:

- all threads are Vert.x threads
- there's no concurrency (there may be thread switches, but all request processing is essentially serial)
- the Vert.x `Context` identity is maintained (which it usually is, but not always)

This is the Vert.x concurrency model, to the best of my knowledge.

The Quarkus concurrency model is ... well, I can't say what it is, because it has never been actually defined, but it is different. As far as I can tell, anything goes today -- and we're left with a ton of problems we're trying to fix without actually defining the concurrency primitives users are allowed to use and rely on contexts being propagated correctly. I believe this is the underlying issue we need to solve.

**Comment by brunobat** [comment]
+1, 
In any case, this PR is needed to improve user experience in the current spaghetti, while we discuss.

**Comment by brunobat** [comment]
@gsmet Do you know what's happening with the scheduler build that is causing these failures?

**Comment by geoand** [comment]
@brunobat can you try rebasing again?

**Comment by brunobat** [comment]
Done

**Comment by brunobat** [comment]
Looking at the failures. They look suspicious.

**Comment by brunobat** [comment]
Looks ok now @geoand

**Review by geoand — APPROVED** [review]
