### PR TITLE
Fix for Integration Tests with test profiles: dev services config overrides

### LINKED ISSUE #48615: Integration tests cannot use fixed port for dev services
We're seeing this with the Redis devservices tests, but assume it applies elsewhere, too. 

Reproducer: https://github.com/ozangunalp/quarkus/tree/redis_devservices_integration_tests

This reproduces on 3.21, so it isn't related to the test classloading work or to the dev services lifecycle changes.

I've popped this into WG #49 for now, but we may wish to move it out for scope reasons.

@ozangunalp says: "We are doing a custom augmentation run for starting devservices. And it is not taking into account overrides from profiles."

### PR DESCRIPTION
**Pull request by ozangunalp**
`QuarkusIntegrationTest` and `QuarkusMainIntegrationTest` prepare dev services after determining the test profile and applying config overrides (using system properties). 

Added QuarkusIntegrationTest to redis-devservices IT module and enabled integration test execution.

- Resolves: #48615

### CODE REVIEW

**Comment by ozangunalp** [comment]
Rebasing after #48614

**Comment by ozangunalp** [comment]
@alesj @brunobat  The failure in `integration-tests/observability-lgtm` `LgtmResourcesIT` is related. 
I can't understand what it is supposed to test. 

For context, before `getConfigOverrides` in a profile were passed to the application, but NOT to the augmentation step to start dev services.

With this change config overrides are also "active" on custom augmentation to start dev services.

**Comment by ozangunalp** [comment]
Failing opentelemetry tests are flaky, and I cannot reproduce the failing `VertxVirtualThreadTest` locally. I don't expect that they are related.

For the `LgtmResourceIT` I think we need to remove that test. Dev resources can't work with `QuarkusIntegrationTest` s because they rely on a custom runtime config source to create services at first config get (or property names get). 

It did seemed like working before because the profile config wasn't read. So observability dev service was active, not the dev resource mechanism.

File: integration-tests/redis-devservices/src/test/java/io/quarkus/redis/devservices/it/DevServicesRedisIT.java [hunk 1]
```diff
@@ -0,0 +1,10 @@
+package io.quarkus.redis.devservices.it;
+
+import io.quarkus.test.junit.QuarkusIntegrationTest;
+
+@QuarkusIntegrationTest
+//@Disabled
+// TODO
```
Comment (holly-cummins) [inline integration-tests/redis-devservices/src/test/java/io/quarkus/redis/devservices/it/DevServicesRedisIT.java]: I think we can remove these two comments, right?

File: integration-tests/redis-devservices/pom.xml [hunk 2]
```diff
@@ -165,6 +165,14 @@
...
                             <skip>false</skip>
                         </configuration>
+                        <executions>
+                            <execution>
+                                <goals>
+                                    <goal>integration-test</goal>
+                                    <goal>verify</goal>
+                                </goals>
+                            </execution>
+                        </executions>
```
Comment (holly-cummins) [inline integration-tests/redis-devservices/pom.xml]: I'd like to see a more generic solution for this, so that we have consistent behaviour in integration tests rather than per-project adjustments to try and ensure integration tests run. But we may not be able to achieve that.

**Comment by holly-cummins** [comment]
> Failing opentelemetry tests are flaky, and I cannot reproduce the failing `VertxVirtualThreadTest` locally. I don't expect that they are related.
>

I agree. 

> For the `LgtmResourceIT` I think we need to remove that test. Dev resources can't work with `QuarkusIntegrationTest` s because they rely on a custom runtime config source to create services at first config get (or property names get).
> 
> It did seemed like working before because the profile config wasn't read. So observability dev service was active, not the dev resource mechanism.

Ohhh, that's so subtle! I wonder how often that happens. Often, I suspect. I had to work quite hard in the dev service tests to check the test was connected to the right one, and normal tests wouldn't necessarily do that. That might explain why this test is known to be flaky, though.

**Comment by ozangunalp** [comment]
> I wonder how often that happens. 

This is only for LGTM Dev Resource, as it is the only dev resource implementation we've.

**Comment by brunobat** [comment]
I'll let @alesj comment on this.

**Review by holly-cummins — APPROVED** [review]

File: integration-tests/redis-devservices/pom.xml (hunk 2 above)
Comment (holly-cummins) [reply integration-tests/redis-devservices/pom.xml]: Confirmed that this isn't the right way to get integration tests running; we only want them to run in native CIs. I've fixed and updated the native matrix instead.

**Review by geoand — APPROVED** [review]

**Comment by ozangunalp** [comment]
I rebased this, once the CI is green I think it is good to go

**Comment by ozangunalp** [comment]
Second try, first rebase didn't compile
