### PR TITLE
Use proper priority to deploy Vert.x Filter used for legacy websockets

### LINKED ISSUE #48812: Duplicate key -100 in GrpcServerProcessor after upgrading to Quarkus 3.20.0
After upgrading from Quarkus 3.17.8 to 3.20.0 (LTS), our application fails to build due to a Duplicate key error during gRPC server initialization. This issue does not occur in 3.17.8 and appears to be a regression or a stricter validation introduced in 3.20.0.

Stack Trace (excerpt):
```
Build step io.quarkus.grpc.deployment.GrpcServerProcessor#initializeServer threw an exception: 
java.lang.IllegalStateException: Duplicate key -100 (attempted merging values Runtime proxy of interface io.vertx.core.Handler with id proxykey89 and Runtime proxy of interface io.vertx.core.Handler with id proxykey280)
```

**Steps to Reproduce**
Use Quarkus 3.20.0 with quarkus-grpc and multiple gRPC services.
Build the project using mvn clean install.
Observe failure during the GrpcServerProcessor build step.

**Expected Behavior** 

The application should build successfully as it does in Quarkus 3.17.8.

**Actual Behavior** 

Build fails with IllegalStateException due to duplicate proxy key registration.

**Environment**

Quarkus version: 3.20.0
Java version: 21
gRPC: quarkus-grpc
Build tool: Maven

**Additional Notes**
No duplicate @GrpcService implementations for the same proto service.
No custom Vert.x Handler beans registered manually.
Issue appears to be related to CDI proxy generation or Vert.x handler registration.
Works fine in 3.17.8.

### PR DESCRIPTION
**Pull request by geoand**
We should never use the same priority value that
Authorization or Authentication use as that can 
cause problems to other extensions 

- Fixes: #48812

### CODE REVIEW

**Review by cescoffier — APPROVED** [review]

File: extensions/websockets/server/deployment/src/main/java/io/quarkus/websockets/deployment/ServerWebSocketProcessor.java [hunk 1]
```diff
@@ -110,10 +110,11 @@ public FilterBuildItem deploy(final CombinedIndexBuildItem indexBuildItem,
         final IndexView index = indexBuildItem.getIndex();
         WebsocketClientProcessor.registerCodersForReflection(reflection, index.getAnnotations(SERVER_ENDPOINT));
 
+        int priority = 1 + FilterBuildItem.AUTHORIZATION;
```
Comment (michalvavrik) [inline extensions/websockets/server/deployment/src/main/java/io/quarkus/websockets/deployment/ServerWebSocketProcessor.java:113]: This is (old) WebSocket so it shouldn't matter and I don't know anything about it, but for record, I think it would be better if this was the opposite - `1-FilterBuildItem.AUTHORIZATION` because this priority is multiplied by `-1` and it means that this handler will run before the authorization handler. If they have some HTTP permissions, they will not run before WS handler.

Comment (geoand) [reply extensions/websockets/server/deployment/src/main/java/io/quarkus/websockets/deployment/ServerWebSocketProcessor.java:113]: Feel free to open a PR in that case

Comment (michalvavrik) [reply extensions/websockets/server/deployment/src/main/java/io/quarkus/websockets/deployment/ServerWebSocketProcessor.java:113]: I'd have to analyze why it worked this way before (why was the priority same), how the legacy WS works etc. I don't think I'll do that. I just tried to provide information, I have no problem with keeping what you have.
