### PR TITLE
Reactive MongoDB Change Streams - Add Support for Databases using custom ChangeStreamOptions

### LINKED ISSUE #27549: Null Pointer Exception Attempting to Watch Change Stream in Database with ChangeStreamOptions
### Describe the bug

If you supply a ChangeStreamOptions parameter to the watch() method of a Reactive Mongo Database for example in order to resume a change stream after a certain token the watch method returns null.

This appears to be an oversight in the implementation, as the Collection equivalent works as expected.

I.e. this works:

```
this.mongoClient
                .getDatabase(databaseName)
                .getCollection(collectionName)
                .watch(pipeline, Document.class, options);
```

But this returns null:
```
this.mongoClient
                .getDatabase(databaseName)
                .watch(pipeline, Document.class, options);
```

### Expected behavior

Supplying a ChangeStreamOptions parameter to the watch method, e.g.:

```
this.mongoClient
                .getDatabase(databaseName)
                .watch(pipeline, Document.class, options);
```

Would create a watch on the change stream of the database, and return a valid Multi.

### Actual behavior

The method returns null.

### How to Reproduce?

To reproduce:

```
        ChangeStreamOptions options = new ChangeStreamOptions();
        var watch = this.reactiveMongoClient
                .getDatabase(databaseName)
                .getCollection(collectionName)
                .watch(Document.class, options);
        Assertions.notNull("Change Stream Watch", watch);
```

### Output of `uname -a` or `ver`

Darwin ip-192-168-1-4.eu-central-1.compute.internal 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 arm64

### Output of `java -version`

java version "17.0.1" 2021-10-19 LTS Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39) Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.11.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63) Maven home: /Users/lthompson/.m2/wrapper/dists/apache-maven-3.8.6-bin/67568434/apache-maven-3.8.6 Java version: 17.0.1, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk-17.0.1.jdk/Contents/Home Default locale: en_AU, platform encoding: UTF-8 OS name: "mac os x", version: "12.4", arch: "aarch64", family: "mac"

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by luketn**
Add support for watching databases using custom ChangeStreamOptions in Reactive Mongo change streams.

This follows the exact pattern used in ReactiveMongoCollectionImpl, applied to databases. 

Fixes #27549

### CODE REVIEW

File: extensions/mongodb-client/runtime/src/main/java/io/quarkus/mongodb/impl/ReactiveMongoDatabaseImpl.java [hunk 1]
```diff
@@ -9,10 +9,7 @@
 import com.mongodb.client.model.CreateCollectionOptions;
 import com.mongodb.client.model.CreateViewOptions;
 import com.mongodb.client.model.changestream.ChangeStreamDocument;
-import com.mongodb.reactivestreams.client.AggregatePublisher;
-import com.mongodb.reactivestreams.client.ClientSession;
-import com.mongodb.reactivestreams.client.ListCollectionsPublisher;
-import com.mongodb.reactivestreams.client.MongoDatabase;
+import com.mongodb.reactivestreams.client.*;
```
Comment (geoand) [inline extensions/mongodb-client/runtime/src/main/java/io/quarkus/mongodb/impl/ReactiveMongoDatabaseImpl.java:12]: Please avoid star imports

Comment (luketn) [reply extensions/mongodb-client/runtime/src/main/java/io/quarkus/mongodb/impl/ReactiveMongoDatabaseImpl.java]: Done

**Review by cescoffier — APPROVED** [review]

**Comment by geoand** [comment]
Please also squash the commits

**Comment by cescoffier** [comment]
Can you squash your commits? 

(see https://github.com/quarkusio/quarkus/wiki/Git-commands-(to-be-added-to-CONTRIBUTING.md)

**Comment by luketn** [comment]
> Can you squash your commits?
> 
> (see https://github.com/quarkusio/quarkus/wiki/Git-commands-(to-be-added-to-CONTRIBUTING.md)

Done. Also addressed the sort order of the imports.

**Comment by luketn** [comment]
@cescoffier I couldn't see any unit / integration tests for Change Streams in the project. It's a bit tricky to test (especially to test disrupted change streams) but would you like me to add some unit tests for the collection, client and database watch() functionality here (or perhaps submit a separate PR with some general integration tests)?
