### PR TITLE
Fix NPE when handling circular dependencies

### LINKED ISSUE #3990: NPE when handling circular dependencies
If there is a normal scoped bean that declares a normal scoped producer and the bean depends on the producer method a NPE is thrown. See for example [MPConfigBean from the MP CP TCK](https://github.com/eclipse/microprofile-context-propagation/blob/master/tck/src/main/java/org/eclipse/microprofile/context/tck/MPConfigBean.java)

The producer bean can be added before the declaring bean and so a null `ResultHandle` is passed to Gizmo: https://github.com/quarkusio/quarkus/blob/master/independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/ComponentsProviderGenerator.java#L248.

### PR DESCRIPTION
**Pull request by mkouba**
- resolves #3990

### CODE REVIEW

**Comment by mkouba** [comment]
@gsmet This is probably another candidate for backport to 0.22.0.

File: independent-projects/arc/runtime/src/main/java/io/quarkus/arc/MapBeanSupplier.java [hunk 1]
```diff
@@ -8,17 +8,18 @@
  *
  * @author Maarten Mulders
  */
-public class MapBeanSupplier implements Supplier {
-    private final Map map;
+public class MapBeanSupplier implements Supplier<Object> {
```
Comment (mthmulders) [inline independent-projects/arc/runtime/src/main/java/io/quarkus/arc/MapBeanSupplier.java]: Why not make it a `Supplier<Supplier<InjectableBean<?>>`, so the type parameter corresponds with the `beanIdToBeanSupplier` map?

Comment (mkouba) [reply independent-projects/arc/runtime/src/main/java/io/quarkus/arc/MapBeanSupplier.java]: Good point. It has no importance but I can change it... ;-)

File: independent-projects/arc/runtime/src/main/java/io/quarkus/arc/FixedValueSupplier.java [hunk 2]
```diff
@@ -7,7 +7,8 @@
  *
  * @author Maarten Mulders
  */
-public class FixedValueSupplier implements Supplier {
+public class FixedValueSupplier implements Supplier<Object> {
```
Comment (mthmulders) [inline independent-projects/arc/runtime/src/main/java/io/quarkus/arc/FixedValueSupplier.java]: Maybe we should give this `Supplier` a more specific type parameter, too. Although it doesn't really add much value at runtime ;-)

Comment (mkouba) [reply independent-projects/arc/runtime/src/main/java/io/quarkus/arc/FixedValueSupplier.java]: I'd keep this universal.

File: independent-projects/arc/runtime/src/main/java/io/quarkus/arc/MapBeanSupplier.java (hunk 1 above)
Comment (mkouba) [reply independent-projects/arc/runtime/src/main/java/io/quarkus/arc/MapBeanSupplier.java]: In fact, we could change it to `Map<String,T>` so that it could be theoretically reused.

Comment (mthmulders) [reply independent-projects/arc/runtime/src/main/java/io/quarkus/arc/MapBeanSupplier.java]: Even better :-)

File: independent-projects/arc/runtime/src/main/java/io/quarkus/arc/FixedValueSupplier.java (hunk 2 above)
Comment (mthmulders) [reply independent-projects/arc/runtime/src/main/java/io/quarkus/arc/FixedValueSupplier.java]: Then maybe make this one a `FixedValueSupplier<T>`, just like the `MapBeanSupplier`. Still universal, but cleaner when it comes to using generics, I'd say?

**Review by manovotn — APPROVED** [review]
Went over some bits with Martin on Zulip and I think it looks good.

**Review by stuartwdouglas — APPROVED** [review]
