### PR TITLE
Re-enable Agroal datasource metrics

### LINKED ISSUE #50956: Agroal metrics are no longer available when only `quarkus.datasource.metrics.enabled=true` is set
### Describe the bug

Having a project with the extensions `quarkus-jdbc-postgresql` and `quarkus-smallrye-metrics` and `quarkus.datasource.metrics.enabled=true` in the `application.properties`, in 3.29.2, the `agroal` vendor metrics are displayed

Image

However they are not shown in main

### Expected behavior

Agroal vendor metrics should be displayed

### Actual behavior

Agroal metrics are not displayed

### How to Reproduce?

1. `quarkus create app -x jdbc-postgresql,rest-jackson,smallrye-metrics`
2. Go to http://localhost:8080/q/metrics and check if there are any `agroal` entries (eg. `vendor_agroal_awaiting_count`)

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

main

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

It might have been introduced after https://github.com/quarkusio/quarkus/pull/50825 was merged

### PR DESCRIPTION
**Pull request by gastaldi**
- Introduce a new test to validate Agroal metrics functionality when metrics are enabled.
- Remove default `false` value for `enabled` configuration in `DataSourceJdbcMetrics` to allow explicit control.
- Fixes #50956

### CODE REVIEW

**Comment by gastaldi** [comment]
Also this fixes the issue reported by QE in https://issues.redhat.com/browse/QQE-1982

**Comment by Sanne** [comment]
> * Remove default `false` value for `enabled` configuration in `DataSourceJdbcMetrics` to allow explicit control.

Could you elaborate please? I'm confused on why removing a *default* setting would allow expliciy control - wasn't this the case already?

Is the goal to change the default? In that case perhaps the test shouldn't be setting a value explicitly?

**Comment by gastaldi** [comment]
The method returns a `Optional<Boolean>`, so with `@WithDefault("false")` `optional.isPresent()` would never return `false`, never reaching this statement: 
 https://github.com/quarkusio/quarkus/blob/main/extensions/agroal/runtime/src/main/java/io/quarkus/agroal/runtime/DataSources.java#L283.

File: extensions/agroal/deployment/src/test/java/io/quarkus/agroal/test/AgroalMetricsOnlyTestCase.java [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+import io.quarkus.test.QuarkusUnitTest;
+
+/**
+ * Test to verify that Agroal metrics are exposed when only quarkus.datasource.metrics.enabled=true is set
+ */
+public class AgroalMetricsOnlyTestCase {
+
+    @RegisterExtension
+    static final QuarkusUnitTest config = new QuarkusUnitTest()
+            .withConfigurationResource("application-metrics-only-enabled.properties");
```
Comment (Sanne) [inline extensions/agroal/deployment/src/test/java/io/quarkus/agroal/test/AgroalMetricsOnlyTestCase.java]: It would be nice to use `.overrideConfigKey( )` on some basic configuration e.g. `base.properties`, so to avoid an explosion of properties files with all permutations.

It also makes it better maintainable, as then people understand which property exactly is this particular test focusing on.

**Comment by gastaldi** [comment]
Note that this behavior was changed when #50825 was merged, this just reverts to the same behavior we had working in 3.29.2

File: extensions/agroal/runtime/src/main/java/io/quarkus/agroal/runtime/DataSourceJdbcBuildTimeConfig.java [hunk 2]
```diff
@@ -45,7 +45,6 @@ interface DataSourceJdbcMetrics {
         /**
          * Enable metrics collection for this datasource.
          */
-        @WithDefault("false")
```
Comment (brunobat) [inline extensions/agroal/runtime/src/main/java/io/quarkus/agroal/runtime/DataSourceJdbcBuildTimeConfig.java:48]: Why change this?
Metrics are usually disabled by default

**Review by brunobat — CHANGES_REQUESTED** [review]
It means we didn't have any metrics agroal test... Thanks @gastaldi

File: extensions/agroal/runtime/src/main/java/io/quarkus/agroal/runtime/DataSourceJdbcBuildTimeConfig.java (hunk 2 above)
Comment (brunobat) [reply extensions/agroal/runtime/src/main/java/io/quarkus/agroal/runtime/DataSourceJdbcBuildTimeConfig.java:48]: We have to find a way to explicitly check if the property is being overridden.

File: extensions/agroal/deployment/src/test/java/io/quarkus/agroal/test/AgroalMetricsOnlyTestCase.java (hunk 1 above)
Comment (gastaldi) [reply extensions/agroal/deployment/src/test/java/io/quarkus/agroal/test/AgroalMetricsOnlyTestCase.java]: I agree it makes it better maintainable, however, when I tried that, for some obscure reason it simply doesn't work. Maybe that's the reason other tests are also using their own properties file? 

```java
            .withConfigurationResource("base.properties")
            .overrideConfigKey("quarkus.datasource.metrics.enabled", "true");
```

Comment (gastaldi) [reply extensions/agroal/deployment/src/test/java/io/quarkus/agroal/test/AgroalMetricsOnlyTestCase.java]: Ignore my previous statement, apparently my IDE was not picking up the changes in the sources. I'll update the test

File: extensions/agroal/runtime/src/main/java/io/quarkus/agroal/runtime/DataSourceJdbcBuildTimeConfig.java (hunk 2 above)
Comment (gastaldi) [reply extensions/agroal/runtime/src/main/java/io/quarkus/agroal/runtime/DataSourceJdbcBuildTimeConfig.java:48]: @brunobat see https://github.com/quarkusio/quarkus/pull/50957#issuecomment-3512200318, this is already being tested in the `DataSources` class. Adding `@WithDefault` in an `Optional` method is pointless

**Review by Sanne — APPROVED** [review]
Thanks!

**Review by brunobat — APPROVED** [review]
