### PR TITLE
Fix registration of backchannel logout route

### LINKED ISSUE #42990: ``logout.backchannel.path`` fails when ``http.root-path`` is present - Again
### Describe the bug

Basically the same problem as in https://github.com/quarkusio/quarkus/issues/42483 happens again with the latest release (3.14.1).
The fix was likely incomplete, as we also encountered the problem in 3.13.3.

### How to Reproduce?

We created a full PoC repo with detailed information, how the bug can be reproduced:
https://github.com/AB-xdev/quarkus-backchannel-logout-poc

### Quarkus version or git rev

3.14.1

### PR DESCRIPTION
**Pull request by AB-xdev**
_Disclaimer I couldn't build it locally / had no time to setup the 22 DIN A4 pages of the contribution guide ;)_

- Fixes: #42990

### CODE REVIEW

**Comment by sberyozkin** [comment]
Thanks @AB-xdev, I'll look now at confirming with the test that this route is accessible with the root path configured, I avoided it previous time trying to minimize impact on all the surrounding tests in the test suite, but I'll isolate it now to a dedicated test

**Comment by sberyozkin** [comment]
@AB-xdev 

>had no time to setup the 22 DIN A4 pages of the contribution guide

What that is about ? And how is it relevant to the issue at hand ?

**Comment by sberyozkin** [comment]
I'm starting looking at adding a back channel test with the http root set

**Comment by sberyozkin** [comment]
After spending a lot of time trying to add a dedicated test in `extensions/oidc-deployment` only, I'm resorting to adding `integration-tests/oidc-wiremock-logout`.  It appears there are some test class loading issues which are not visible because all the tests there now use the same realm. 
When a wiremock test is added, the properties like `quarkus.oidc.auth-server-url` registered by other tests impact the wiremock test...

**Comment by sberyozkin** [comment]
Hi @gsmet @cescoffier  I added a test. FYI, if I the route path is relative, example, `quarkus.oidc.logout.backchannel.path=back-channel-logout`, then, even with `quarkus.http.root-path=/service`, the route registration fails.

Only having both `quarkus.http.root-path=/service` and `quarkus.oidc.logout.backchannel.path=/service` works.

It also took me a bit of time to realize RestAuured integration will prepend the root path itself for non-absolute URLs :-)

**Comment by cescoffier** [comment]
Why do you need to repeat the root path? Is the route registered correctly?

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/BackChannelLogoutHandler.java [hunk 1]
```diff
@@ -46,7 +46,7 @@ public void setup(@Observes Router router) {
 
     private void addRoute(Router router, OidcTenantConfig oidcTenantConfig) {
         if (oidcTenantConfig.isTenantEnabled() && oidcTenantConfig.logout.backchannel.path.isPresent()) {
-            router.route(getRootPath() + oidcTenantConfig.logout.backchannel.path.get())
+            router.route(oidcTenantConfig.logout.backchannel.path.get())
```
Comment (cescoffier) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/BackChannelLogoutHandler.java:49]: Who is calling this method? Which router is it? Why it's not a route registered in the processor?

Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/BackChannelLogoutHandler.java:49]: Hi @cescoffier 

>Who is calling this method?

It is called from just above from `setup(@Observes Router router) `, [here](https://github.com/quarkusio/quarkus/blob/228883027f96ba285a1ff9e75e7bacc3369dc041/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/BackChannelLogoutHandler.java#L39).

>Which router is it?

The main application one, since it works when accessed from the tests and for example, from Keycloak.

>Why it's not a route registered in the processor?

Do you mean the recorder, similar to how it is done [WebAuthnRecorder](https://github.com/quarkusio/quarkus/blob/main/extensions/security-webauthn/runtime/src/main/java/io/quarkus/security/webauthn/WebAuthnRecorder.java#L35) ?

I don't recall now, probably I did not know how to do it at a time, and chose `setup(@Observers Router router)`, or may be because the way it is done now is easier to handle in a multi-tenant setup. I can certainly rework it and move the registration to the recorder. I guess, to have this PR backportable, I should do it as a follow up PR a bit later, does it sound reasonable ?

**Comment by sberyozkin** [comment]
@cescoffier 

> Why do you need to repeat the root path? Is the route registered correctly?

Do you mean why the route was registered with the explicit root path ? It was a mistake, the PR from @AB-xdev fixes it, or do you mean something else ?

**Comment by cescoffier** [comment]
Ok, so it's an applicatoin router receiving the application router. For sure you must not prefix the root path. 

I think we would need to switch to a route declared in the extension instead of this, but as you said, for backport reason, let's go with this.

**Review by cescoffier — APPROVED** [review]

**Comment by sberyozkin** [comment]
Merging now, @AB-xdev, thanks again for initiating this PR :+1: , we look forward for more :-)

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/BackChannelLogoutHandler.java (hunk 1 above)
Comment (gsmet) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/BackChannelLogoutHandler.java:49]: Yeah, please let's try to get the simple version of this PR verified, tested and merged.

I need a backportable fix very soon.
