### PR TITLE
Fixes related to Maven projects using the 'revision' property as the project version

### LINKED ISSUE #7747: "Maven CI Friendly Versions" are not (fully) supported, application is incomplete/broken
**Describe the bug**
The `build` goal of the `quarkus-maven-plugin` builds an incomplete application in case ["Maven CI Friendly Versions"](https://maven.apache.org/maven-ci-friendly.html) are used.

E.g.:

Parent `pom.xml`:
```xml
    <groupId>some.project</groupId>
    <artifactId>root</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>
    <properties>
        <!-- This is only the default for local development, CI will override it! -->
        <revision>0.1-SNAPSHOT</revision>
    </properties>
```

Submodule `pom.xml` (the one with the `quarkus-maven-plugin` execution):
```xml
  <parent>
    <groupId>some.project</groupId>
    <artifactId>root</artifactId>
    <version>${revision}</version>
  </parent>

  <artifactId>dist</artifactId>
```

As described on  ["Maven CI Friendly Versions"](https://maven.apache.org/maven-ci-friendly.html) (paragraph "Install / Deploy"), `flatten-maven-plugin` is configured properly.

**Expected behavior**
The application is built normally/fully. There should be no difference to e.g. `<version>0.1-SNAPSHOT</version>`.

**Actual behavior**
The runner jar is missing most (all?) of the application classes and the following is logged:
```
[INFO] --- quarkus-maven-plugin:1.3.0.CR2:build (default) @ dist ---
[WARNING] The POM for some.project:dist:jar:${revision} is missing, no dependency information available
[WARNING] The POM for some.project:dist:jar:${revision} is missing, no dependency information available
[INFO] [org.jboss.threads] JBoss Threads version 3.0.1.Final
[INFO] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Building thin jar: C:\Develop\some-project\dist\target\dist-0.1-SNAPSHOT-runner.jar
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 1106ms
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

**To Reproduce**
1. set up a small multi module project (parent + one module)
2. introduce `${revision}`
3. introduce `flatten-maven-plugin`
4. try to build the Quarkus application (e.g. `mvn clean install` on root level)

I am pretty swamped at the moment so I cannot provide a sample project right away.
But please do let me know if you need one.

_Update:_ Reproducer created, see https://github.com/quarkusio/quarkus/issues/7747#issuecomment-597336269

**Configuration**
none

**Screenshots**
none

**Environment:**
 - Output of `uname -a` or `ver`: `MINGW64_NT-10.0-18363 W4DEUMSY9003463 3.0.7-338.x86_64 2019-11-21 23:07 UTC x86_64 Msys`
 - Output of `java -version`: `OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)`
 - GraalVM version (if different from Java): none
 - Quarkus version or git rev: 1.3.0.CR2
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): `Apache Maven 3.6.3`

**Additional context**

I think I already found the source of the problem:
`io.quarkus.bootstrap.resolver.maven.workspace.LocalProject` is re-reading the `pom.xml` via `ModelUtils` / `MavenXpp3Reader`. This simple XML parsing does _not_ take care of the property interpolation that is required for the resolution of `${revision}`.

_One_ solution might be to prefer a possibly existing `.flattened-pom.xml` to the regular `pom.xml`.
I did something similar here: https://github.com/shrinkwrap/resolver/pull/142
Since the name and location of the flattened file is configurable, Quarkus should probably provide a config option to reflect that.

### PR DESCRIPTION
**Pull request by aloubyansky**
Fixes #7747

### CODE REVIEW

**Comment by famod** [comment]
Thanks again for the quick reaction. Any chance to get this into 1.3.0.Final?

Btw, is there a SNAPSHOT version available with this fix or do I have to build it myself?

**Comment by aloubyansky** [comment]
Yes, it should end up in 1.3.0.Final. We do upload SNAPSHOT every day. I'm not sure at what time though.

**Comment by aloubyansky** [comment]
It has to get merged first though to end up in a deployed SNAPSHOT.

**Comment by famod** [comment]
> Yes, it should end up in 1.3.0.Final. 

Great!

> It has to get merged first though to end up in a deployed SNAPSHOT.

I see! Then I'll give it a shot once it is merged.

PS: I am getting SNAPSHOTs with different timestamps when using 999-SNAPSHOT and the test in my sample project hangs. I guess this is not normal?

File: independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/resolver/maven/workspace/LocalProject.java [hunk 1]
```diff
@@ -28,17 +28,24 @@
 
     private static final String PROJECT_BASEDIR = "${project.basedir}";
     private static final String POM_XML = "pom.xml";
+    private static final String REVISION = "revision";
```
Comment (famod) [inline independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/resolver/maven/workspace/LocalProject.java]: Just a heads up: https://maven.apache.org/maven-ci-friendly.html does not only support `revision` but also `sha1` and/or `changelist`.

**Comment by aloubyansky** [comment]
> PS: I am getting SNAPSHOTs with different timestamps when using 999-SNAPSHOT and the test in my sample project hangs. I guess this is not normal?

Not sure, tbh. Perhaps it's in the process of being updated?

File: independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/resolver/maven/workspace/LocalProject.java (hunk 1 above)
Comment (aloubyansky) [reply independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/resolver/maven/workspace/LocalProject.java]: Thanks for pointing this out. I'll probably add support for those in another PR just to get this one in quicker. Unless you tell me you absolutely need them :)

Comment (famod) [reply independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/resolver/maven/workspace/LocalProject.java]: I'm fine with just `revision`!

File: independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/resolver/maven/workspace/LocalProject.java [hunk 2]
```diff
@@ -136,10 +143,30 @@ private LocalProject(Model rawModel, LocalWorkspace workspace) throws BootstrapE
         this.workspace = workspace;
         this.groupId = ModelUtils.getGroupId(rawModel);
         this.artifactId = rawModel.getArtifactId();
-        this.version = ModelUtils.getVersion(rawModel);
+
+        String version = ModelUtils.getVersion(rawModel);
+        final boolean revisionVersion;
+        if (revisionVersion = REVISION_EXPR.equals(version)) {
+            version = rawModel.getProperties().getProperty(REVISION);
```
Comment (famod) [inline independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/resolver/maven/workspace/LocalProject.java]: Does this also cover `-Drevision=<something_different_than_in_pom>`?
This is important, because that is what CI (e.g. Jenkins via `Jenkinsfile`) would be passing to `mvn` to override the default revision.

A variation is of that would be:
- ```xml
  <properties>
      <revision>0.1-${revisionSuffix}</revision>
      <revisionSuffix>SNAPSHOT</revisionSuffix>
  </properties>
  ```
- CI passes `-DrevisionSuffix=build-${BUILD_NUMBER}`

This way local build produces `0.1-SNAPSHOT` and CI produces something like `0.1-build-123`.

**Comment by geoand** [comment]
@aloubyansky is this safe for `1.3.0.Final`?

**Comment by aloubyansky** [comment]
Yes, which is why I requested a backport. However, I'm about to commit one more enhancement in a bit.

File: independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/resolver/maven/workspace/LocalProject.java (hunk 2 above)
Comment (aloubyansky) [reply independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/resolver/maven/workspace/LocalProject.java]: Actually according to the Maven doc you referenced this is not supported by Maven itself, isn't it?

Comment (aloubyansky) [reply independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/resolver/maven/workspace/LocalProject.java]: I tried adding support for sha1 and changelist but strangely it also didn't work in Maven itself. Unless I somehow did it wrong.

Comment (aloubyansky) [reply independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/resolver/maven/workspace/LocalProject.java]: > Does this also cover `-Drevision=<something_different_than_in_pom>`?

This will work though.

**Comment by gsmet** [comment]
Please ping us when this is ready.

**Comment by aloubyansky** [comment]
It's ready @gsmet I can always follow up with enhancements.

**Review by gastaldi — APPROVED** [review]

File: independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/resolver/maven/workspace/LocalProject.java (hunk 2 above)
Comment (famod) [reply independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/resolver/maven/workspace/LocalProject.java]: > Actually according to the Maven doc you referenced this is not supported by Maven itself, isn't it?

Which part do you mean? `-Drevision=...` is mentioned explicitly multiple times.

The `revisionSuffix` is not mentioned but IMHO this is just basic Maven interpolation logic, no?
You could also have `myFancySomethingProperty` instead of `revisionSuffix`, doesn't matter.

> I tried adding support for sha1 and changelist but strangely it also didn't work in Maven itself.

I swapped `revision` with `sha1` locally in my sample project and it worked (apart from the Quarkus build problem). I even changed the default value from `1.0-SNAPSHOT` to `0.2-SNAPSHOT` and I also tried `-Drevision=1.1-SNAPSHOT`.

> > Does this also cover `-Drevision=<something_different_than_in_pom>`?
> 
> This will work though.

Ok, as long as this works the main problem is solved. The rest could be adressed separately.

Comment (aloubyansky) [reply independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/resolver/maven/workspace/LocalProject.java]: > You could also have `myFancySomethingProperty` instead of `revisionSuffix`, doesn't matter.

Arbitrary property interpolation is not allowed in the version elements. There is an example in that doc.

> I swapped `revision` with `sha1` locally in my sample project and it worked

Ah, I need to try that. I tried combining the three mentioned properties like they had in the doc, which for some reason didn't work.

Comment (famod) [reply independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/resolver/maven/workspace/LocalProject.java]: > > You could also have `myFancySomethingProperty` instead of `revisionSuffix`, doesn't matter.
> 
> Arbitrary property interpolation is not allowed in the version elements. There is an example in that doc.

You are right, I have totally missed that!

> > I swapped `revision` with `sha1` locally in my sample project and it worked
> 
> Ah, I need to try that. I tried combining the three mentioned properties like they had in the doc, which for some reason didn't work.

I just tried the following and everything works as expected (in Maven itself):
```diff
$ git diff
diff --git a/core/pom.xml b/core/pom.xml
index ea45976..b52f070 100644
--- a/core/pom.xml
+++ b/core/pom.xml
@@ -5,7 +5,7 @@
   <parent>
     <groupId>com.github.famod.modmono-quarkus</groupId>
     <artifactId>modmono-quarkus-parent</artifactId>
-    <version>${revision}</version>
+    <version>${revision}${sha1}</version>
   </parent>
   <artifactId>modmono-quarkus-core</artifactId>
   <dependencies>
diff --git a/dist/pom.xml b/dist/pom.xml
index 278e9c5..e0df457 100644
--- a/dist/pom.xml
+++ b/dist/pom.xml
@@ -5,7 +5,7 @@
   <parent>
     <groupId>com.github.famod.modmono-quarkus</groupId>
     <artifactId>modmono-quarkus-parent</artifactId>
-    <version>${revision}</version>
+    <version>${revision}${sha1}</version>
   </parent>
   <artifactId>modmono-quarkus-dist</artifactId>
   <dependencies>
diff --git a/pom.xml b/pom.xml
index b895c66..f72103c 100644
--- a/pom.xml
+++ b/pom.xml
@@ -4,10 +4,11 @@
   <modelVersion>4.0.0</modelVersion>
   <groupId>com.github.famod.modmono-quarkus</groupId>
   <artifactId>modmono-quarkus-parent</artifactId>
-  <version>${revision}</version>
+  <version>${revision}${sha1}</version>
   <packaging>pom</packaging>
   <properties>
-    <revision>1.0-SNAPSHOT</revision>
+    <revision>0.3</revision>
+    <sha1>-SNAPSHOT</sha1>

     <compiler-plugin.version>3.8.1</compiler-plugin.version>
```
