### PR TITLE
Fix native image generated static resources index

### LINKED ISSUE #867: Single-page application functionality is lost when compiling a Quarkus + Quinoa + Svelte project with a non-default HTTP root path to a GraalVM native image
### Describe the bug

When packaging and executing a Quarkus + Quinoa + SvelteKit project with a *non-default HTTP root path* as a GraalVM native image, the Svelte single-page application does not work.
The single-page application *does* work as expected when compiling the GraalVM image with the default (empty) HTTP root path or when packaging and executing the project as a JAR.

### Quinoa version

2.5.4

### Quarkus version

3.21.4

### Build / Runtime

Vite

### Package Manager

NPM

#### Environment

- macOS 15.4.1
- Rancher Desktop 1.18.2
- Quarkus CLI 3.21.4
- Quinoa 2.5.4
- Node 22.15.0
- npm 10.9.2

#### Create a project

With the Quarkus CLI installed, create a Quarkus + Quinoa + Svelte project using the following commands:

```shell
quarkus create app -P io.quarkus.platform:quarkus-bom:3.21.4 quinoa-native
cd quinoa-native
quarkus extension add io.quarkiverse.quinoa:quarkus-quinoa:2.5.4

cd src/main
npx sv@0.8.1 create --template=minimal --types=ts --no-add-ons --install=npm webui
cd webui
npm i -D @sveltejs/adapter-static@3.0.8
echo "export const ssr = false;" > src/routes/+layout.js
cd ../../..
```

Configure SvelteKit according to [this Quinoa guide](https://docs.quarkiverse.io/quarkus-quinoa/dev/web-frameworks.html#svelte-kit-config) by changing `src/main/webui/svelte.config.js` to:

```js
import adapter from '@sveltejs/adapter-static';
import { vitePreprocess } from '@sveltejs/vite-plugin-svelte';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	preprocess: vitePreprocess(),

	kit: {
		adapter: adapter({
			fallback: 'index.html'
		}),
		paths: {
			base: '/root',
			relative: false
		}
	}
};

export default config;
```

Additionally, extend `src/main/resources/application.properties` by:

```properties
quarkus.http.root-path=/root

quinoa.package-manager-install=true
quinoa.package-manager-install.node-version=22.15.0

quarkus.quinoa.build-dir=build
quarkus.quinoa.enable-spa-routing=true
```

Finally, to prevent errors with missing libraries like

```
./application: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by ./application)
```

when executing the GraalVM native image, change the used image in `src/main/docker/Dockerfile.native` from `registry.access.redhat.com/ubi8/ubi-minimal:8.10` to `registry.access.redhat.com/ubi9/ubi-minimal:9.5`.

#### Package and execute the project as a GraalVM native image

Build a GraalVM native image using a Docker container:

```shell
quarkus build --no-tests -Dnative -Dquarkus.native.container-build=true
```

This process may take a few minutes.

Then, wrap the native image in a Docker container:

```shell
docker build -f src/main/docker/Dockerfile.native -t quarkus/quinoa-native .
```

The GraalVM native image of our application can now be executed with:

```shell
docker run -i --rm -p 8080:8080 quarkus/quinoa-native
```

All should be fine thus far.

Finally, open an incognito tab in your browser and navigate to <http://localhost:8080/root/>.

> ❌ Instead of the Svelte welcome page, Quarkus shows a 404 error.

Then, navigate to the (non-existing) route <http://localhost:8080/root/page>.

> ❌ Quarkus returns a 404 error and we do not see Svelte's default 404 page.

Note that the example endpoint <http://localhost:8080/root/hello> works as expected.
Additionally, the single-page application root, <http://localhost:8080/root/index.html>, the favicon, <http://localhost:8080/root/favicon.png>, and Svelte's scripts can be fetched directly. 

### Expected behavior

When packaging and executing a Quarkus + Quinoa + Svelte project with a non-default HTTP root path as a GraalVM native image, the Svelte single-page application should work properly at that root path.

#### Note: The GraalVM native application is successful *without* a root path

The single-page web application *does* work as expected when packaging and executing the GraalVM native image without an HTTP root path:

- Remove the property `quarkus.http.root-path=/root` from `src/main/resources/application.properties`.
- Change the `config.kit.paths.base` property in `src/main/webui/svelte.config.js` from `'/root'` to the empty string `''`.
- Again run the last three commands to package and execute the project as a GraalVM native image.
- Open an incognito tab in your browser and navigate to <http://localhost:8080/>.

  > ✅ You should see the Svelte welcome page.

- Similarly, navigate to the (non-existing) route <http://localhost:8080/page>.

  > ✅ You should see Svelte's default 404 error page.

#### Note: Regular JAR execution is successful *with* a root path

Unlike is the case with the GraalVM native image, the single-page web application with a non-default root path *does* work as expected when executed from the regular JAR:

- Reinstate the property `quarkus.http.root-path=/root` in `src/main/resources/application.properties`.
- Reset the `config.kit.paths.base` property in `src/main/webui/svelte.config.js` to `'/root'`.
- Package and execute the project as a JAR by running the following commands:

    ```shell
    quarkus build
    java -jar target/quarkus-app/quarkus-run.jar
    ```

- Open an incognito tab in your browser and navigate to <http://localhost:8080/root/>. (The trailing slash is important!)

  > ✅ You should see the Svelte welcome page.

- Similarly, navigate to the (non-existing) route <http://localhost:8080/root/page>.

  > ✅ You should see Svelte's default 404 error page.

### PR DESCRIPTION
**Pull request by ia3andy**
Fixes https://github.com/quarkiverse/quarkus-quinoa/issues/867

The issue is affecting all native apps on any sub-directory (index won't be resolved)

### CODE REVIEW

File: extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/GeneratedStaticResourcesProcessor.java [hunk 1]
```diff
@@ -73,6 +73,11 @@ public void produceResources(List<GeneratedStaticResourceBuildItem> generatedSta
                 additionalStaticResourcesProducer.produce(
                         new AdditionalStaticResourceBuildItem(generatedStaticResource.getEndpoint(), false));
                 nativeImageResourcesProducer.produce(new NativeImageResourceBuildItem(generatedStaticResourceLocation));
+                int lastSep = generatedStaticResourceLocation.lastIndexOf('/');
+                if (lastSep > 0) {
+                    String parent = generatedStaticResourceLocation.substring(0, lastSep);
+                    nativeImageResourcesProducer.produce(new NativeImageResourceBuildItem(parent));
+                }
```
Comment (gsmet) [inline extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/GeneratedStaticResourcesProcessor.java]: Could you also check if `generatedStaticResourceLocation` doesn't end with `/`? You can just check that `lastSep` is also `< generatedStaticResourceLocation.length() - 1`

Also, maybe I would add a small comment: `if the resource is somehow an index page, we need the parent directory to also be added as a native resource so that we can resolve both /path/index.html and /path/`.

Comment (ia3andy) [reply extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/GeneratedStaticResourcesProcessor.java]: That makes total sense to check that it's a file path (i.e. `generatedStaticResourceLocation` doesn't end with `/`) and same for the comment.. thanks!

**Comment by ia3andy** [comment]
I suppose we should backport  this to the 3.20 LTS?

**Comment by gsmet** [comment]
> I suppose we should backport this to the 3.20 LTS?

Yeah, I suppose it makes sense to include it in the next one. I added the label.

I let you finalize the PR and we can first include it in this week's 3.25.3 release.

File: extensions/vertx-http/deployment-spi/src/main/java/io/quarkus/vertx/http/deployment/spi/GeneratedStaticResourceBuildItem.java [hunk 2]
```diff
@@ -28,8 +28,14 @@ public final class GeneratedStaticResourceBuildItem extends MultiBuildItem {
...
-        if (!requireNonNull(endpoint, "endpoint is required").startsWith("/")) {
-            throw new IllegalArgumentException("endpoint must start with '/'");
+        requireNonNull(endpoint, "endpoint is required");
+        if (!endpoint.startsWith("/")) {
+            throw new IllegalArgumentException(
+                    "GeneratedStaticResourceBuildItem endpoint must start with '/': %s".formatted(endpoint));
+        }
+        if (endpoint.endsWith("/")) {
+            throw new IllegalArgumentException(
+                    "GeneratedStaticResourceBuildItem endpoint must not end with '/': %s".formatted(endpoint));
```
Comment (gsmet) [inline extensions/vertx-http/deployment-spi/src/main/java/io/quarkus/vertx/http/deployment/spi/GeneratedStaticResourceBuildItem.java:38]: Hmmm, sorry, but I'm not very comfortable doing that.

I think you should tweak the condition as I was suggesting before.

My main reason is that people might have decided to generate a `GeneratedStaticResourceBuildItem` for the directory themselves to work around the issue and it might contain a `/`. If we want it to be backportable, we need to be less aggressive.

Does it make sense?

Comment (ia3andy) [reply extensions/vertx-http/deployment-spi/src/main/java/io/quarkus/vertx/http/deployment/spi/GeneratedStaticResourceBuildItem.java:38]: Not really, it should have been checked in the first place. We are reading the file on disk, adding a directory does not make sense and would fail another way..

Comment (ia3andy) [reply extensions/vertx-http/deployment-spi/src/main/java/io/quarkus/vertx/http/deployment/spi/GeneratedStaticResourceBuildItem.java:38]: I suppose we should even add a check that the file exists (and print an error if not) before reading it in the processor

Comment (gsmet) [reply extensions/vertx-http/deployment-spi/src/main/java/io/quarkus/vertx/http/deployment/spi/GeneratedStaticResourceBuildItem.java:38]: I'm specifically talking about other producers of `GeneratedStaticResourceBuildItem`.

A build item can be generated by any extension around. You can't be sure that all the extensions out there are not pushing something with `/`. Especially since they might do that to work around this very issue and get the directory referenced in the native image. And also because it's actually not that big of a deal to have an ending `/`, except for the newly added code, or am I missing something?

We can't break compatibility in back branches as easily as that.

Now if you absolutely want to check this in main, but I don't really understand the value of being so strict tbh so maybe you could explain, we will need two patches, one for main, and one for the back branches.

Comment (ia3andy) [reply extensions/vertx-http/deployment-spi/src/main/java/io/quarkus/vertx/http/deployment/spi/GeneratedStaticResourceBuildItem.java:38]: I pasted the code of what is done with this BuildItem, we read the file. It won't work if it ends with `/` whether after or before this PR (this code is just to ensure we have the proper error and check as soon as possible).

https://github.com/quarkusio/quarkus/pull/49455/files#diff-7bd378a321691086398f7630d2e5cf0a810695723812e4d2dbffe959201e200aR56-R70

**Review by gsmet — APPROVED** [review]
