### PR TITLE
Fix Qute ValueResolver generated in wrong CL

### LINKED ISSUE #11007: Qute dev-mode Classloader issue
**Describe the bug**
Getting java.lang.NoClassDefFoundError when running Qute project with a separate jar dependency in dev-mode.

Was OK in 1.5.2 but failing in 1.6.1 (1.6.0 not tested).

Reproducer attached.

**To Reproduce**
Reproducer is a parent pom with two modules. One is a jar library. The other is a Quarkus REST service:

- tar xvf qute-classloader-issue.tar
- cd qute-classloader-issue
- mvn clean install
- cd getting_started
- mvn quarkus:dev
- curl -w “\n” http://localhost:8080/hello

It will fail. Change the quarkus version in getting-started/pom.xml to 1.5.2.Final and it works.

[qute-classloader-issue.tar.zip](https://github.com/quarkusio/quarkus/files/4985086/qute-classloader-issue.tar.zip)

### PR DESCRIPTION
**Pull request by stuartwdouglas**
Fixes #11007

### CODE REVIEW

File: extensions/qute/deployment/src/main/java/io/quarkus/qute/deployment/QuteProcessor.java [hunk 1]
```diff
@@ -700,15 +701,13 @@ public boolean test(String name) {
...
                 if (className.contains(ValueResolverGenerator.NESTED_SEPARATOR)) {
                     className = className.replace(ValueResolverGenerator.NESTED_SEPARATOR, "$");
                 }
-                if (applicationArchivesBuildItem.getRootArchive().getIndex()
-                        .getClassByName(DotName.createSimple(className)) != null) {
-                    return true;
-                }
-                return false;
+                //if the class is (directly) in the TCCL (and not its parent) then it is an application class
+                QuarkusClassLoader cl = (QuarkusClassLoader) Thread.currentThread().getContextClassLoader();
```
Comment (mkouba) [inline extensions/qute/deployment/src/main/java/io/quarkus/qute/deployment/QuteProcessor.java:709]: Do we have this documented somewhere? Maybe _Class Loading Reference_?

**Review by mkouba — APPROVED** [review]
LGTM.
