### PR TITLE
ArC dev mode - fix business method invocations monitoring

### LINKED ISSUE #17322: Quarkus random ConcurrentModificationException
## Issue 
After upgrading from `1.12.2.Final` to `1.13.4.Final` a lot of **random** `java.util.ConcurrentModificationException`  are thrown when a rest API call is done. For example, it happens between FE(Angular) and BE communication, but also between micro-services(all Quarkus based). This makes local environment(dev mode) almost unusable. 

**P.S. This is reproducible only on local, running the dev mode.**

Is something changed in this direction between mentioned Quarkus version? How can I debug it further? 

Please feel free to ask for more information.

## Example
Here is an example, when FE calls the BE `/myc/api/user/me`
```
021-05-18 10:08:05,388 ERROR [io.und.req.io] (executor-thread-37) Exception handling request e981e92b-df4b-4526-8b03-fd23e4e08faf-5 to /myc/api/user/me: java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1043)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:997)
	at io.quarkus.arc.runtime.devconsole.Invocation$Builder.build(Invocation.java:173)
	at io.quarkus.arc.runtime.devconsole.Invocation$Builder.build(Invocation.java:174)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:71)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(InvocationInterceptor_Bean.zig:521)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at com.connectis.myconnectis.adapters.web.infra.filters.AngularResourcesFilter_Subclass.doFilter(AngularResourcesFilter_Subclass.zig:1090)
	at com.connectis.myconnectis.adapters.web.infra.filters.AngularResourcesFilter_ClientProxy.doFilter(AngularResourcesFilter_ClientProxy.zig:444)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:63)
	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:67)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:133)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:65)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:247)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:56)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:111)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:108)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$9$1.call(UndertowDeploymentRecorder.java:587)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:227)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleRequest(ServletInitialHandler.java:152)
	at io.undertow.server.handlers.PathHandler.handleRequest(PathHandler.java:91)
	at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$1.handleRequest(UndertowDeploymentRecorder.java:119)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:290)
	at io.undertow.server.DefaultExchangeHandler.handle(DefaultExchangeHandler.java:18)
	at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$5$1.run(UndertowDeploymentRecorder.java:413)
	at io.quarkus.runtime.CleanableExecutor$CleaningRunnable.run(CleanableExecutor.java:231)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.base/java.lang.Thread.run(Thread.java:836)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)


```

### Java version
```
openjdk 11.0.10 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.24.0, JRE 11 Linux amd64-64-Bit Compressed References 20210120_910 (JIT enabled, AOT enabled)
OpenJ9   - 345e1b09e
OMR      - 741e94ea8
JCL      - 0a86953833 based on jdk-11.0.10+9)
```

### PR DESCRIPTION
**Pull request by mkouba**
- a ConcurrentModificationException may be thrown if async processing
and the request context is not propagated
- resolves #17322

### CODE REVIEW

File: extensions/arc/runtime/src/main/java/io/quarkus/arc/runtime/devconsole/Invocation.java [hunk 1]
```diff
@@ -108,7 +109,8 @@ public String getPackageName(String name) {
         private long start;
         private long duration;
         private Method method;
-        private List<Builder> children;
+        // If async processing and the request context is not propagated a new child can be added when/after the builder is built
+        private final List<Builder> children = new CopyOnWriteArrayList<>();
```
Comment (gsmet) [inline extensions/arc/runtime/src/main/java/io/quarkus/arc/runtime/devconsole/Invocation.java:113]: Wouldn't it make more sense to have a volatile boolean called `built` or similar that is set to true at the very beginning of `build()` and exit from `addChild()` if it's true?

**Review by gsmet — CHANGES_REQUESTED** [review]
Added a question. Not sure I fully grasp this but better clarify before merging.

File: extensions/arc/runtime/src/main/java/io/quarkus/arc/runtime/devconsole/Invocation.java (hunk 1 above)
Comment (mkouba) [reply extensions/arc/runtime/src/main/java/io/quarkus/arc/runtime/devconsole/Invocation.java:113]: I think that `volatile` would not be enough in this case, we would have to synchronize the access anyway. `CopyOnWriteArrayList` should be safe although not so efficient, but that should not be a big problem in the dev mode.

**Review by gsmet — APPROVED** [review]
