### PR TITLE
Isolate Avro schema code generation when using multiple schema files

### LINKED ISSUE #39344: Avro schemas aren't generated in isolation
### Describe the bug

When generating source files from Avro schema (.avsc) files, if no import option is set, schemas should remain isolated from each other.

Commit [Add backward compatible support for multiple extensions in CodeGenProvider](https://github.com/quarkusio/quarkus/commit/8af488dbd96f902872171d76b69bd48971897067) introduced a new way to create an (empty) list from a non-set `avro.codegen.*.imports` setting, breaking evaluation with static `EMPTY` object [here](https://github.com/quarkusio/quarkus/blob/5c25ff5a2d23eb634fc1a0d01ca2357a24222fc7/extensions/avro/deployment/src/main/java/io/quarkus/avro/deployment/AvroSchemaCodeGenProvider.java#L50).

### Expected behavior

When setting `avro.codegen.*.imports` is undefined or empty, all Avro files should be regarded as separate schemas

### Actual behavior

When setting `avro.codegen.*.imports` is undefined or empty, all Avro files aren't regarded as separate schemas. This causes the generate-sources process to fail if 2 or more Avro schema files are present defining the same named Avro-structure.

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

Linux 6.7.9-arch1-1 x86_64 GNU/Linux

### Output of `java -version`

openjdk 21.0.2

### Quarkus version or git rev

3.7.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.7

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by MThomassen**
- Fixes: #39344

### CODE REVIEW

File: extensions/avro/deployment/src/main/java/io/quarkus/avro/deployment/AvroSchemaCodeGenProvider.java [hunk 1]
```diff
@@ -47,7 +48,7 @@ void compileSingleFile(Path filePath,
         // allow them to share a single schema so reuse and sharing of schema
         // is possible.
         try {
-            if (options.imports == EMPTY) {
+            if (ArrayUtils.isEmpty(options.imports)) {
```
Comment (gsmet) [inline extensions/avro/deployment/src/main/java/io/quarkus/avro/deployment/AvroSchemaCodeGenProvider.java:51]: We try to avoid depending on commons things in Quarkus (even if it's in the classpath because of other dependencies forcing it on us). Could you rewrite that with plain Java?

**Review by gsmet — CHANGES_REQUESTED** [review]
Thanks for this PR and sorry it took so much time to review it.

Could you have a look at my suggestion? Once fixed, I think we are good to go (and we will backport it)

**Comment by MThomassen** [comment]
Thanks for your effort! Suggestions are included now

**Review by gsmet — APPROVED** [review]
I squashed and rebased.

LGTM, let's see what CI has to say!

**Comment by gsmet** [comment]
I see you force pushed, let's run CI again to be extra safe.

**Comment by gsmet** [comment]
Thanks for the PR (and your patience!).
