### PR TITLE
Send SentMail Instances When Sending Emails

### LINKED ISSUE #45135: Accessing the Mail object from MailTemplateInstance without using Reflection
### Description

Hello,

I'm sending emails via MailTemplateInstance and at the moment i'm tracking the emails being sent (from, to, cc, bcc, attachments etc).

In order to do that i'm doing the following which uses reflection.

```java
      mailTemplateInstance
                .subject(subject)
                .data("pixel", uri)
                .send()
                .await()
                .atMost(Duration.ofSeconds(10));

        // Should be done here (after email being sent), since MailTemplateInstance sets the html/text at later time
        String from; // mail object does not have the from field set
        String bounceAddress; // mail object does not have the bounceAddress field set
        Mail mail;

        try {
            Field mailerField = mailTemplateInstance.getClass().getDeclaredField("mailer");
            mailerField.setAccessible(true);

            var mailer = (MutinyMailerImpl) mailerField.get(mailTemplateInstance);
            var fromField = mailer.getClass().getDeclaredField("from");
            fromField.setAccessible(true);
            from = fromField.get(mailer).toString();

            var bounceAddressField = mailer.getClass().getDeclaredField("bounceAddress");
            bounceAddressField.setAccessible(true);
            bounceAddress = bounceAddressField.get(mailer).toString();

            Field mailField = mailTemplateInstance.getClass().getDeclaredField("mail");
            mailField.setAccessible(true);
            mail = (Mail) mailField.get(mailTemplateInstance);

        } catch (NoSuchFieldException | IllegalAccessException e) {
            throw new RuntimeException(e);
        }
```

Is there a way to get the actual Mail object from the mailTemplateInstance without reflection and with all fields properly being set in the mail object?

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by cescoffier**
This PR introduces the use of CDI events to emit instances of SentMail whenever an email is successfully sent.

The SentMail class is an immutable representation of the sent email, preventing unintended modifications. This approach avoids the need to introduce a new API by leveraging CDI events.

Fixes https://github.com/quarkusio/quarkus/issues/45135.

### CODE REVIEW

File: extensions/mailer/runtime/src/main/java/io/quarkus/mailer/SentMail.java [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+ * @param textBody the text body
+ * @param htmlBody the HTML body
+ * @param headers the headers
+ * @param attachments the attachments
+ */
+public record SentMail(String from,
+        List<String> to, List<String> cc, List<String> bcc,
+        String replyTo, String bounceAddress,
+        String subject, String textBody, String htmlBody,
+        Map<String, List<String>> headers, List<Attachment> attachments) {
```
Comment (gsmet) [inline extensions/mailer/runtime/src/main/java/io/quarkus/mailer/SentMail.java:26]: I think you will also need an immutable version of `Attachment`.

File: extensions/mailer/runtime/src/main/java/io/quarkus/mailer/SentMail.java [hunk 2]
```diff
@@ -0,0 +1,27 @@
...
+ * @param bcc the list of BCC recipients
+ * @param replyTo the list of reply-to addresses
+ * @param bounceAddress the bounce address
+ * @param subject the subject
+ * @param textBody the text body
+ * @param htmlBody the HTML body
+ * @param headers the headers
+ * @param attachments the attachments
+ */
+public record SentMail(String from,
```
Comment (gastaldi) [inline extensions/mailer/runtime/src/main/java/io/quarkus/mailer/SentMail.java:22]: How about renaming to `MailSent` to facilitate finding it during the IDE auto-completion?

Comment (gastaldi) [reply extensions/mailer/runtime/src/main/java/io/quarkus/mailer/SentMail.java:22]: Or maybe call it `Receipt` if you are feeling adventurous :)

Comment (gastaldi) [reply extensions/mailer/runtime/src/main/java/io/quarkus/mailer/SentMail.java:24]: > It's not a Receipt - it does not guarantee that the mail was delivered; it was just sent.

I just wanted to find a common term that would illustrate that a Mail was sent. A receipt doesn't necessarily guarantee that it was delivered, just a proof that the package was dispatched (making an analogy to snail mail)

File: extensions/mailer/runtime/src/main/java/io/quarkus/mailer/runtime/MutinyMailerImpl.java [hunk 3]
```diff
@@ -64,6 +70,11 @@ public class MutinyMailerImpl implements ReactiveMailer {
         this.approvedRecipients = approvedRecipients;
         this.logRejectedRecipients = logRejectedRecipients;
         this.logInvalidRecipients = logInvalidRecipients;
+        if (Arc.container() != null) {
+            this.sentEmailEvent = Arc.container().beanManager().getEvent().select(SentMail.class);
```
[the remark this answers is not in the document]
Comment (cescoffier) [reply extensions/mailer/runtime/src/main/java/io/quarkus/mailer/runtime/MutinyMailerImpl.java]: Done.

**Comment by gsmet** [comment]
@mkouba I let you do a final check on this one.

**Review by mkouba — APPROVED** [review]
