### PR TITLE
ArC - make it possible to exclude types and dependencies

### LINKED ISSUE #9545: Ability to exclude 3rd party CDI beans/factories from Quarkus Arc bean resolution
**Description**
Currently using some 3rh party libraries that have CDI annotated classes can crash Quarkus Arc container. In order to use such libraries we need class/artifact exclusion mechanism for Arc scanner.

See https://stackoverflow.com/questions/61952174

**Implementation ideas**
Config properties would be enough:

    # for fine grained exclusion 
    quarkus.arc.exclude-classes=class list like in .selected-alternatives

    # for coarse grained exclusion 
    quarkus.arc.exclude-dependency."exclude-dependency".group-id
    quarkus.arc.exclude-dependency."exclude-dependency".artifact-id

Related issue - https://github.com/apache/camel-quarkus/issues/1197

### PR DESCRIPTION
**Pull request by mkouba**
- resolves #9545

### CODE REVIEW

File: core/deployment/src/main/java/io/quarkus/deployment/index/IndexDependencyConfig.java [hunk 1]
```diff
@@ -12,18 +12,18 @@
      * The maven groupId of the artifact to index
      */
     @ConfigItem
-    String groupId;
+    public String groupId;
```
Comment (aloubyansky) [inline core/deployment/src/main/java/io/quarkus/deployment/index/IndexDependencyConfig.java:15]: Could this be made an immutable class, btw? Not necessarily in this PR.

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanProcessor.java [hunk 2]
```diff
@@ -471,13 +474,24 @@ public Builder setAlternativePriorities(AlternativePriorities priorities) {
...
+        }
+
         public BeanProcessor build() {
             return new BeanProcessor(name, index, additionalBeanDefiningAnnotations, output, sharedAnnotationLiterals,
                     reflectionRegistration, annotationTransformers, injectionPointTransformers, observerTransformers,
                     resourceAnnotations, beanRegistrars, observerRegistrars, contextRegistrars, beanDeploymentValidators,
                     applicationClassPredicate, removeUnusedBeans, removalExclusions, additionalStereotypes,
                     additionalInterceptorBindingRegistrars, transformUnproxyableClasses, jtaCapabilities, generateSources,
-                    allowMocking, alternativePriorities);
+                    allowMocking, alternativePriorities, excludeTypes);
```
Comment (aloubyansky) [inline independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanProcessor.java:494]: To avoid this crazy ctor you can make BeanProcessor(Builder builder) ctor instead in which init fields like `this.field = builder.field`.

Comment (aloubyansky) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanProcessor.java:494]: and/or apply some other processing.

**Review by aloubyansky — APPROVED** [review]
It looks ok to me. A note on paths not associated with a key. I'm wondering whether that could be viewed as an incomplete support of this feature. It could be improved though. If the additional path is a JAR, in the majority of cases it will include Maven metadata which could be used to extract its key. Something to keep in mind.

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ArcConfig.java [hunk 3]
```diff
@@ -94,6 +96,28 @@
...
+     * <li>a package name with suffix {@code .**}, i.e. {@code org.acme.**}, matches a package that starts with the value</li>
+     * </ul>
+     * If any element value matches a discovered type then the type is excluded from discovery, i.e. no beans and observer
+     * methods are created from this type.
+     */
+    @ConfigItem
+    public Optional<List<String>> excludeTypes;
+
+    /**
+     * Artifacts on the class path that should be excluded from discovery even though the .
```
Comment (geoand) [inline extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ArcConfig.java:116]: Something seems to be missing in the comment here :)

**Review by geoand — APPROVED** [review]
LGTM, I only added a small comment

File: core/deployment/src/main/java/io/quarkus/deployment/index/IndexDependencyConfig.java (hunk 1 above)
Comment (mkouba) [reply core/deployment/src/main/java/io/quarkus/deployment/index/IndexDependencyConfig.java:15]: It's a config group. I'm not sure it's possible to make config groups immutable?

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanProcessor.java (hunk 2 above)
Comment (mkouba) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanProcessor.java:494]: Yeah, the builder param is a good idea. I'll update the PR.

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ArcConfig.java (hunk 3 above)
Comment (mkouba) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ArcConfig.java:116]: Good catch ;-)

**Review by manovotn — APPROVED** [review]
LGTM
