### PR TITLE
Properly pass Kotlin compiler plugin options to dev-mode

### LINKED ISSUE #2811: Recompilation kotlin sources in dev mode should use compiler plugins
**Description**
Using quarkus 0.16.0 in a kotlin project, when hot reloading is triggered it seems like the kotlin files are recompiled without any kotlin compiler plugins. Consider a resource like the following

    @Path("/greeting")
    @ApplicationScoped
    class GreetingResource @Inject constructor(val greetingService: GreetingService) { ... }

In order for this class to work correctly, it needs to not be final and to have a default constructor. Both can be achieved by configuring the maven kotlin-maven-plugin

    <configuration>
        <compilerPlugins>
            <plugin>all-open</plugin>
            <plugin>no-arg</plugin>
        </compilerPlugins>
        <pluginOptions>
            <option>all-open:annotation=javax.enterprise.context.ApplicationScoped</option>
            <option>no-arg:annotation=javax.enterprise.context.ApplicationScoped</option>
        </pluginOptions>
    </configuration>

And indeed the application is working when initially starting with

    mvn compile quarkus:dev

But as soon as the source is modified the reload fails with

    Caused by: javax.enterprise.inject.spi.DeploymentException: Found 2 deployment problems: 
    [1] Normal scoped bean must not be final: CLASS bean [types=[GreetingResource, java.lang.Object], qualifiers=[@Default, @Any], target=GreetingResource]
    [2] Normal scoped beans must declare a non-private constructor with no parameters: CLASS bean [types=[GreetingResource, java.lang.Object], qualifiers=[@Default, @Any], target=GreetingResource]

**Implementation ideas**
Ideally the kotlin extension would reuse the configuration of the kotlin-maven-plugin from pom.xml. Alternatively there would need to be a separate configuration option for plugins of the quarkus-kotlin extension.

Issue #1157 is related, but this issue is actually more generic as there might be more classes or annotations that  need special treatment by the kotlin compiler, which would then break after hot reloading.

### PR DESCRIPTION
**Pull request by geoand**
Partially fixes: #2811 (Gradle support will be part of #6035)

### CODE REVIEW

**Comment by geoand** [comment]
I tested this and it worked great on a generated project. I also updated the Kotlin integration test to reflect the test case it's supposed to solve.

Feedback more than welcome :)

**Comment by geoand** [comment]
@ia3andy this doesn't fix your Java 11 issue with Kotlin, but it should make it a lot easier for you or anyone else to implement it. Did you ever open an issue for that?

File: core/devmode/src/main/java/io/quarkus/dev/DevModeContext.java [hunk 1]
```diff
@@ -120,6 +123,14 @@ public void setTargetJvmVersion(String targetJvmVersion) {
         this.targetJvmVersion = targetJvmVersion;
     }
 
+    public List<String> getCompilerPluginArtifacts() {
+        return compilerPluginArtifacts;
+    }
+
+    public List<String> getCompilerPluginsOptions() {
+        return compilerPluginsOptions;
+    }
```
Comment (gsmet) [inline core/devmode/src/main/java/io/quarkus/dev/DevModeContext.java]: I would prefer having setters for those two. Similar to `setCompilerOptions`.

File: extensions/kotlin/deployment/pom.xml [hunk 2]
```diff
@@ -31,7 +31,7 @@
 
         <dependency>
             <groupId>org.jetbrains.kotlin</groupId>
-            <artifactId>kotlin-compiler-embeddable</artifactId>
+            <artifactId>kotlin-compiler</artifactId>
```
Comment (gsmet) [inline extensions/kotlin/deployment/pom.xml]: Why that change?

File: devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java [hunk 3]
```diff
@@ -638,6 +648,49 @@ void prepare() throws Exception {
...
+            }
+
+            getLog().debug("Kotlin Maven plugin detected");
+
+            // get the absolute path of the all-open plugin
+            String fullPath = null;
+            List<Dependency> dependencies = kotlinMavenPlugin.getDependencies();
+            for (Dependency dependency : dependencies) {
+                // TODO do we actually need this to resolve the artifact or can we use the repoSystem?
+                Artifact artifact = system.createDependencyArtifact(dependency);
```
Comment (geoand) [inline devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java]: I would like if I didn't have to add `system` to `DevMojo` and just use `repoSystem`. Is that possible @aloubyansky ?

What I added here I pretty much copied from [here](https://github.com/JetBrains/kotlin/blob/v1.3.41/libraries/tools/kotlin-maven-plugin/src/main/java/org/jetbrains/kotlin/maven/KotlinCompileMojoBase.java#L294)

**Review by gsmet — COMMENTED** [review]
I added a suggestion and a question.

File: extensions/kotlin/deployment/pom.xml (hunk 2 above)
Comment (geoand) [reply extensions/kotlin/deployment/pom.xml]: This is needed otherwise the Kotlin compiler plugins can't integrate with the compiler (you get some kind of incompatibility exception).
FWIW, we probably should have had this dependency from the start.

File: core/devmode/src/main/java/io/quarkus/dev/DevModeContext.java (hunk 1 above)
Comment (geoand) [reply core/devmode/src/main/java/io/quarkus/dev/DevModeContext.java]: OK, I'll update

Comment (geoand) [reply core/devmode/src/main/java/io/quarkus/dev/DevModeContext.java]: Fixed

**Comment by geoand** [comment]
@gsmet I updated per your suggestion and added an answer to your question

File: devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java (hunk 3 above)
Comment (aloubyansky) [reply devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java]: Yes, sure, here is how https://github.com/quarkusio/quarkus/blob/master/independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/resolver/maven/MavenArtifactResolver.java#L197

Comment (geoand) [reply devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java]: Thanks! I'll update the PR to use this

File: bom/runtime/pom.xml [hunk 4]
```diff
@@ -2261,6 +2261,11 @@
                 <artifactId>kotlin-compiler-embeddable</artifactId>
                 <version>${kotlin.version}</version>
             </dependency>
+            <dependency>
+                <groupId>org.jetbrains.kotlin</groupId>
+                <artifactId>kotlin-compiler</artifactId>
+                <version>${kotlin.version}</version>
+            </dependency>
```
Comment (aloubyansky) [inline bom/runtime/pom.xml]: Do we still need `kotlin-compiler-embeddable`? AFAICS, it's used only in `kotlin/deployment/pom.xml`. Which also raises a question why it is in the runtime BOM instead of the deployment one.

Comment (geoand) [reply bom/runtime/pom.xml]: Nice catches, thanks! 
I think we can remove `embeddable`. I'll also check and see if moving it to the deployment BOM works.

Comment (geoand) [reply bom/runtime/pom.xml]: Actually, are you sure it should in the deployment BOM? I don't see any other non-quarkus artifacts thee

Comment (geoand) [reply bom/runtime/pom.xml]: I removed the embeddable dependency

File: devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java (hunk 3 above)
Comment (geoand) [reply devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java]: Fixed

File: bom/runtime/pom.xml (hunk 4 above)
Comment (aloubyansky) [reply bom/runtime/pom.xml]: > Actually, are you sure it should in the deployment BOM? I don't see any other non-quarkus artifacts there

The runtime BOM is for runtime dependencies. It is also imported directly by user applications to align application runtime dependencies with the Quarkus platform's runtime dependencies.
Theoretically, if the artifact is only a deployment dependency then it belongs to the deployment BOM. One caveat in the current implementation (and afaict in the to be implemented classloading model) if there are difference versions of the artifact in the runtime CP and the deployment CP then the runtime one will end up being used during the augmentation.
In this given case, however, I'd probably put it in the deployment BOM. If you are not comfortable doing that then don't :) Could be a separate issue.
The BOMs should probably go through a thorough review.

**Review by aloubyansky — APPROVED** [review]

File: bom/runtime/pom.xml (hunk 4 above)
Comment (geoand) [reply bom/runtime/pom.xml]: I did a test that moved the dependency to the deployment BOM and as you expected it worked. The only caveat however is that we need to redeclare the kotlin version and keep it in sync with the runtime BOM.
Should we go for that or keep it as it is?

Comment (aloubyansky) [reply bom/runtime/pom.xml]: Ah, the properties. I think the properties should move to the root pom.xml so that they can be shared across all the subprojects including the tests. Some tests define/duplicate those versions, which is not a good thing.

Comment (geoand) [reply bom/runtime/pom.xml]: @aloubyansky makes sense!

@gsmet I think that what @aloubyansky proposes should be handled in a dedicated issue, WDYT?

Comment (gsmet) [reply bom/runtime/pom.xml]: I fully agree about having the properties in their own pom. I suggested that a while ago.

Not entirely sure it will work to have them in the root pom, depends if all the pom requiring them has it as parent. Otherwise, it can be a specific pom.

I agree it should be done in a separate issue.

**Review by gsmet — APPROVED** [review]

File: bom/runtime/pom.xml (hunk 4 above)
Comment (geoand) [reply bom/runtime/pom.xml]: Thanks both of you for your input!

**Comment by gastaldi** [comment]
Looks good. Haven't fully tested yet, but does it work in Gradle?

**Comment by geoand** [comment]
> Looks good. Haven't fully tested yet, but does it work in Gradle?

Nope, it will require a lot of work to get it working in Gradle as well. That is because in Gradle we can't just read the configuration, we'll need to read the Kotlin Gradle plugin data. It should definitely be done when all the other Gradle improvements things are in place.

**Comment by geoand** [comment]
@gastaldi would you be interested in doing a follow up for Gradle as some point?

File: bom/runtime/pom.xml (hunk 4 above)
Comment (aloubyansky) [reply bom/runtime/pom.xml]: > Not entirely sure it will work to have them in the root pom, depends if all the pom requiring them has it as parent. Otherwise, it can be a specific pom.

Either way that properties pom will have to be a parent pom for every subproject. Which is what the root pom is supposed to be, otherwise the hierarchy for the project is going to break which effectively means independent projects.

**Comment by gastaldi** [comment]
I created #6035 And referenced it in #5101

**Review by gastaldi — APPROVED** [review]

**Comment by geoand** [comment]
> I created #6035 And referenced it in #5101

Excellent!
