### PR TITLE
Optimize conditional dependencies resolution in Gradle

### LINKED ISSUE #19022: Quarkus Gradle plugin 2.1.0.Final configuration time is slow
### Describe the bug

I am upgrading our project from Quarkus 1.3.x to 2.x.x. I saw that 2.1.0.Final is on Gradle plugin portal so I tried it out, even though I know 2.1.0.Final is not released yet. I found out that 2.1.0.Final increases gradle configuration time substantially. Even gradle help now takes cca. 8s. Quarkus Gradle plugin 2.0.3.Final works ok.

It seems that problem is, that dependencies are resolved in configuration time (so in plugin.apply()) and not at execution time of the plugin as before. Since Gradle does not parallelise configuration time that well that can result in longer task startup times on multi-module projects. So every start of Gradle task is slow and can take multiple seconds even if it's not related to Quarkus plugin: imagine debugging unit tests where every test task start takes additional 8+ seconds.

We have project with 23 modules which is not that much and from gradle scan it can be seen that configuration phase for Quarkus takes 8 seconds.

Screenshot from `gradle help --scan`:
Screenshot 2021-07-25 at 11 40 53

### Expected behavior

Quarkus Gradle plugin configures in sub second

### Actual behavior

Quarkus Gradle plugin takes long time to configure

### How to Reproduce?

[quarkus-configuration.zip](https://github.com/quarkusio/quarkus/files/6885886/quarkus-configuration.zip)

Steps:
1. Run gradle help multiple times -> it takes cca. 5s everytime
2. Change version of Quarkus plugin to 2.0.3.Final in settings.gradle
3. Run gradle help multiple times -> it takes 1s (it takes more on first run)

### Output of `uname -a` or `ver`

MacBook-Pro 19.6.0

### Output of `java -version`

openjdk version "11.0.11" 2021-04-20

### GraalVM version (if different from Java)

/

### Quarkus version or git rev

2.1.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.1.1

### Additional information

I know 2.1.0.Final is not released yet, but it might be good to know. Feel free to close it, if it is a known issue.

### LINKED ISSUE #20153: Gradle - quarkusDependency runs for all submodules when attempting to build one
### Describe the bug

In a monorepo with multiple subprojects, any build will cause `quarkusDependency` and `quarkusDependencyCopy` tasks to always run for all subprojects. This is particularly concerning in a 30 project monorepo when trying to build a single project (i.e. `./gradlew project:build`), which takes 3-4 minutes on every build.

### Expected behavior

The `quarkusDependency` and `quarkusDependencyCopy`  taks should only run for the individual project and any project dependencies.

### Actual behavior

All subprojects run `quarkusDependency` and `quarkusDependencyCopy`  always.

### How to Reproduce?

1. Create a multiproject repository
2. Run a single project: `./gradlew project:build`

### Output of `uname -a` or `ver`

Ubuntu 20.04

### Output of `java -version`

OpenJDK 11.0.11

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.2.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.1.1

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by glefloch**
This aim to simplify and optimize conditional dependency resolution in the gradle plugin: 

- The `quarkusDev` configuration does not extends the `compileClasspath` anymore, this avoid resolving the compile classpath twice (for the `implementation` configuration and for the `quarkusDev` configuration)
- Limitation of the number of dependency to resolve, I try to minimise the number of dependencies to resolve. The less we have, faster we are. 
- I moved the code, in a block (`beforeResolve`) that is only executed if the compile classpath is needed

close #20153

### CODE REVIEW

**Comment by aloubyansky** [comment]
Just curious, have you measured the effects of the change on some project?

**Comment by glefloch** [comment]
I'm trying to compare sample between 2.0, 2.1, and my branch.

**Comment by glefloch** [comment]
@aloubyansky I tried to measure performance improvements but with not a lot of dependencies, I don't see a difference. 
The main thing is that now, the resolution is not part of the configuration anymore (which was the main pain point I think). In case of task that don't require the compile classpath, there is no more overhead.
In case of multi module projects, the resolution will only apply to module that needs the compile classpath and not apply on all module.

**Comment by aloubyansky** [comment]
We should not be closing the issue unless we know we fixed it. It could still be ok to merge the change though.

**Comment by glefloch** [comment]
sure, I edited the PR to remove the reference to the first one. However the second one should be closed as this fix the fact that we not trigger resolution for every module.

**Comment by aloubyansky** [comment]
Here is something that could be useful for you investigating these kind of issues @glefloch. Here is a code snippet that is supposed to generate a project with as many extensions as possible:
````
		final ExtensionCatalog catalog = QuarkusProjectHelper.getCatalogResolver().resolveExtensionCatalog();
		final Set<String> extensions = catalog.getExtensions().stream()
				// filter out extensions that make the set incompatible
				.filter(e -> {
					final String artifactId = e.getArtifact().getArtifactId();
					return !artifactId.contains("kotlin") && !artifactId.contains("scala")
						&& !artifactId.contains("reactive")
						&& !artifactId.contains("openshift") && !artifactId.contains("minikube")
						&& !artifactId.contains("azure") && !artifactId.contains("google-cloud")
						&& !artifactId.contains("prometheus") && !artifactId.contains("micrometer")
						&& !artifactId.endsWith("-container-image-docker") && !artifactId.endsWith("-container-image-s2i")
						&& !artifactId.contains("opentelemetry")
						&& !artifactId.contains("lambda")
						&& !artifactId.contains("splunk")
						&& !artifactId.contains("jooq")
						&& !artifactId.contains("unleash")
						&& !artifactId.contains("datadog")
						&& !artifactId.contains("doma")
						&& !artifactId.contains("mybatis")
						&& !e.getArtifact().getGroupId().contains("loggingjson");
					})
				// for testing quarkus core, we can filter out non-core extensions
				.filter(e -> e.getArtifact().getGroupId().equals("io.quarkus")
						// adding quarkiverse results in OME || e.getArtifact().getGroupId().contains("quarkiverse")
						)
				.map(e -> e.getArtifact().getGroupId() + ":" + e.getArtifact().getArtifactId()).collect(Collectors.toSet());
		final QuarkusProject project = QuarkusProjectHelper.getProject(
				Paths.get(System.getProperty("user.home")).resolve("playground").resolve("test-project"), catalog,
				BuildTool.GRADLE);
		new CreateProject(project).extensions(extensions).noCode().execute();

````
The only dependency that should be necessary is `io.quarkus:quarkus-devtools-common`. You can turn it into a jbang script.

If I don't filter quarkiverse or not limit it to the `io.quarkus` extensions, I get either
````
[aloubyansky@localhost test-project]$ ./gradlew clean build
Expiring Daemon because JVM heap space is exhausted
Daemon will be stopped at the end of the build after running out of JVM memory
Expiring Daemon because JVM heap space is exhausted
Expiring Daemon because JVM heap space is exhausted

FAILURE: Build failed with an exception.

* What went wrong:
Gradle build daemon has been stopped: JVM garbage collector thrashing and after running out of JVM memory
````
or
````
[INFO] Checking for existing resources in: /home/aloubyansky/playground/test-project/src/main/kubernetes.
Exception in thread "Daemon client event forwarder" java.lang.OutOfMemoryError: Java heap space
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.addConditionWaiter(AbstractQueuedSynchronizer.java:1896)
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2114)
        at java.base/java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:458)
        at org.gradle.launcher.daemon.server.exec.DaemonConnectionBackedEventConsumer$ForwardEvents.getNextEvent(DaemonConnectionBackedEventConsumer.java:72)
        at org.gradle.launcher.daemon.server.exec.DaemonConnectionBackedEventConsumer$ForwardEvents.run(DaemonConnectionBackedEventConsumer.java:59)
````

Which is not necessarily an issue with your code resolving dependencies.

**Comment by aloubyansky** [comment]
It would be great to be testing multimodule projects though as well.

File: devtools/gradle/src/main/java/io/quarkus/gradle/QuarkusPlugin.java [hunk 1]
```diff
@@ -239,6 +233,30 @@ public void execute(Task test) {
...
+        project.getConfigurations().getByName(JavaPlugin.COMPILE_CLASSPATH_CONFIGURATION_NAME).getIncoming()
+                .beforeResolve((dependencies) -> {
+
+                    Set<ExtensionDependency> implementationExtensions = conditionalDependenciesEnabler
+                            .declareConditionalDependencies(JavaPlugin.IMPLEMENTATION_CONFIGURATION_NAME);
+                    deploymentClasspathBuilder.createBuildClasspath(implementationExtensions,
+                            JavaPlugin.IMPLEMENTATION_CONFIGURATION_NAME, true);
+                    Set<ExtensionDependency> devModeExtensions = conditionalDependenciesEnabler
+                            .declareConditionalDependencies(DEV_MODE_CONFIGURATION_NAME);
+                    deploymentClasspathBuilder.createBuildClasspath(devModeExtensions, DEV_MODE_CONFIGURATION_NAME, false);
```
Comment (aloubyansky) [inline devtools/gradle/src/main/java/io/quarkus/gradle/QuarkusPlugin.java:249]: Just to clarify, are we going to be resolving the dev classpath even if the launch mode isn't DEV?

Comment (glefloch) [reply devtools/gradle/src/main/java/io/quarkus/gradle/QuarkusPlugin.java:249]: This configuration only contains specific `quarkusDev` dependency. But even for test we are going to resolve them. I don't think we have a way to get the launch mode here.

**Comment by glefloch** [comment]
I'm going to try out your script.

File: devtools/gradle/src/main/java/io/quarkus/gradle/QuarkusPlugin.java (hunk 1 above)
Comment (aloubyansky) [reply devtools/gradle/src/main/java/io/quarkus/gradle/QuarkusPlugin.java:249]: We create DEV_MODE_CONFIGURATION_NAME, could we handle it in the same manner as the COMPILE_CLASSPATH_CONFIGURATION_NAME and TEST_COMPILE_CLASSPATH_CONFIGURATION_NAME? i.e. do the beforeResolve thing?

Comment (glefloch) [reply devtools/gradle/src/main/java/io/quarkus/gradle/QuarkusPlugin.java:249]: That’s true, we can definitely do that in the before resolve. I will test that

File: devtools/gradle/src/main/java/io/quarkus/gradle/QuarkusPlugin.java [hunk 2]
```diff
@@ -193,9 +189,7 @@ public void execute(Task test) {
                                     .plus(testSourceSet.getOutput()));
 
                     // create a custom configuration for devmode
-                    configurations.create(DEV_MODE_CONFIGURATION_NAME).extendsFrom(
-                            configurations.getByName(JavaPlugin.COMPILE_ONLY_CONFIGURATION_NAME),
-                            configurations.getByName(JavaPlugin.RUNTIME_CLASSPATH_CONFIGURATION_NAME));
+                    configurations.create(DEV_MODE_CONFIGURATION_NAME);
```
Comment (aloubyansky) [inline devtools/gradle/src/main/java/io/quarkus/gradle/QuarkusPlugin.java:192]: What does this configuration contain now?

File: devtools/gradle/src/main/java/io/quarkus/gradle/QuarkusPlugin.java (hunk 1 above)
Comment (glefloch) [reply devtools/gradle/src/main/java/io/quarkus/gradle/QuarkusPlugin.java]: fixed !

File: devtools/gradle/src/main/java/io/quarkus/gradle/QuarkusPlugin.java (hunk 2 above)
Comment (glefloch) [reply devtools/gradle/src/main/java/io/quarkus/gradle/QuarkusPlugin.java:192]: only dependency with the `quarkusDev` scope. So in most case nothing.

File: devtools/gradle/src/main/java/io/quarkus/gradle/QuarkusPlugin.java [hunk 3]
```diff
@@ -239,6 +233,31 @@ public void execute(Task test) {
...
     }
 
+    private void registerConditionalDependencies(Project project) {
+        ConditionalDependenciesEnabler conditionalDependenciesEnabler = new ConditionalDependenciesEnabler(project);
+        ApplicationDeploymentClasspathBuilder deploymentClasspathBuilder = new ApplicationDeploymentClasspathBuilder(
+                project);
+        project.getConfigurations().getByName(JavaPlugin.COMPILE_CLASSPATH_CONFIGURATION_NAME).getIncoming()
+                .beforeResolve((dependencies) -> {
+                    Set<ExtensionDependency> implementationExtensions = conditionalDependenciesEnabler
+                            .declareConditionalDependencies(JavaPlugin.IMPLEMENTATION_CONFIGURATION_NAME);
```
Comment (aloubyansky) [inline devtools/gradle/src/main/java/io/quarkus/gradle/QuarkusPlugin.java:243]: In case of the other two configs below, the config name matches but not in this case. We find the COMPILE_CLASSPATH_CONFIGURATION_NAME but looking for the conditional dependencies in IMPLEMENTATION_CONFIGURATION_NAME. Should we be using IMPLEMENTATION_CONFIGURATION_NAME in both cases?

File: devtools/gradle/src/main/java/io/quarkus/gradle/builder/QuarkusModelBuilder.java [hunk 4]
```diff
@@ -56,13 +56,21 @@
     private static final String MAIN_RESOURCES_OUTPUT = "build/resources/main";
     private static final String CLASSES_OUTPUT = "build/classes";
     private static final String DEPLOYMENT_CONFIGURATION = "deploymentConfiguration";
+    private static final String CLASSPATH_CONFIGURATION = "classpathConfiguration";
```
Comment (aloubyansky) [inline devtools/gradle/src/main/java/io/quarkus/gradle/builder/QuarkusModelBuilder.java:59]: Is this a Quarkus-specific classpath config?

File: devtools/gradle/src/main/java/io/quarkus/gradle/builder/QuarkusModelBuilder.java [hunk 5]
```diff
@@ -56,13 +56,21 @@
...
         if (LaunchMode.DEVELOPMENT.equals(mode)) {
-            return project.getConfigurations().getByName(QuarkusPlugin.DEV_MODE_CONFIGURATION_NAME);
+            Configuration classpathConfiguration = project.getConfigurations().findByName(CLASSPATH_CONFIGURATION);
+            if (classpathConfiguration != null) {
+                project.getConfigurations().remove(classpathConfiguration);
+            }
+
+            return project.getConfigurations().create(CLASSPATH_CONFIGURATION).extendsFrom(
+                    project.getConfigurations().getByName(QuarkusPlugin.DEV_MODE_CONFIGURATION_NAME),
+                    project.getConfigurations().getByName(JavaPlugin.IMPLEMENTATION_CONFIGURATION_NAME));
```
Comment (aloubyansky) [inline devtools/gradle/src/main/java/io/quarkus/gradle/builder/QuarkusModelBuilder.java:73]: Just to confirm, this will include compile-only, runtime and quarkusDev scopes?

Comment (glefloch) [reply devtools/gradle/src/main/java/io/quarkus/gradle/builder/QuarkusModelBuilder.java:73]: I will update it has it effectively should.

File: devtools/gradle/src/main/java/io/quarkus/gradle/builder/QuarkusModelBuilder.java (hunk 4 above)
Comment (glefloch) [reply devtools/gradle/src/main/java/io/quarkus/gradle/builder/QuarkusModelBuilder.java:59]: Yes this the configuration I to combine `quarkusDev` / `compileOnly` / `runtime`dependencies

Comment (aloubyansky) [reply devtools/gradle/src/main/java/io/quarkus/gradle/builder/QuarkusModelBuilder.java:59]: Perhaps we should call it `quarkus`SomethingConfiguration then.

File: devtools/gradle/src/main/java/io/quarkus/gradle/QuarkusPlugin.java (hunk 3 above)
Comment (aloubyansky) [reply devtools/gradle/src/main/java/io/quarkus/gradle/QuarkusPlugin.java:243]: Let's not modify the original compileClasspath.

**Comment by glefloch** [comment]
@aloubyansky, I updated the code and CI is green, should we merge this one?

**Review by aloubyansky — APPROVED** [review]

**Comment by aloubyansky** [comment]
Yes, thanks @glefloch
