### PR TITLE
Copy attributes from Elytron SecurityIdentity to Quarkus SecurityIdentity

### LINKED ISSUE #44804: ElytronPasswordIdentityProvider does not forward attributes from SecurityIdentity
### Describe the bug

In Wildfly Elytron it is possible to request additional attributes using attribute mappings. Quarkus does also enable this [via the configs](https://quarkus.io/guides/security-ldap#configuring-the-application) (example for ldap). 

Quarkus SecurityIdentity interface and [implementation](https://github.com/quarkusio/quarkus/blob/main/extensions/security/runtime/src/main/java/io/quarkus/security/runtime/QuarkusSecurityIdentity.java#L73-L81) has getAttribute and getAttributes methods available and likewise the builder used to construct it has [setAttribute and setAttributes methods](https://github.com/quarkusio/quarkus/blob/main/extensions/security/runtime/src/main/java/io/quarkus/security/runtime/QuarkusSecurityIdentity.java#L195-L209), however [ElytronPasswordIdentityProvider](https://github.com/quarkusio/quarkus/blob/main/extensions/elytron-security/runtime/src/main/java/io/quarkus/elytron/security/runtime/ElytronPasswordIdentityProvider.java#L54-L60) does not forward the attributes from the retrieved Wildfly [SecrutityIdentity](https://wildfly-security.github.io/wildfly-elytron/documentation/api/upstream/org/wildfly/security/auth/server/SecurityIdentity.html#getAttributes())to it. 

### Expected behavior

The attributes should be set on the builder and thus ultimately be available on the injected SecurityIdentity.

### Actual behavior

The attributes are not available on injected SecurityIdentity.

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sberyozkin**
Fixes #44804 

This PR is completely based on contribution from @MelkorCC (see #44880), I've only tweaked a couple of tests to test Elytron attributes are copied

### CODE REVIEW

**Comment by sberyozkin** [comment]
@MelkorCC I've update the standard user LDAP entry (thanks for showing how to do it) as it looks like existing tests have successful checks for the standard user only, so it was easier for me to update it

File: extensions/elytron-security-ldap/deployment/src/test/java/io/quarkus/elytron/security/ldap/LdapSecurityRealmTest.java [hunk 1]
```diff
@@ -128,15 +128,19 @@ public void testJaxrsUserRoleSuccess() {
         setupAuth("standardUser", "standardUserPassword")
                 .when().get("/jaxrs-secured/subject/secured").then()
                 .statusCode(200)
-                .body(equalTo("standardUser"));
+                .body(equalTo(expectedStandardUserName()));
```
Comment (sberyozkin) [inline extensions/elytron-security-ldap/deployment/src/test/java/io/quarkus/elytron/security/ldap/LdapSecurityRealmTest.java:131]: I had to do it because there are 4 concrete test suite classes extending this abstract class

**Review by geoand — APPROVED** [review]
👌🏽

**Review by gastaldi — APPROVED** [review]
