### PR TITLE
Config - Avoid producing duplicate GeneratedClassBuildItem

### LINKED ISSUE #50265: 3.28.1: `java.util.zip.ZipException: duplicate entry` in Quarkus generated jar(s)
### Describe the bug

For Quarkus 3.28.1, CI reports `j,u.z.ZipException: duplicate entry...` errors for every `quarkusBuild` Gradle task execution. 3.27.0 looks fine.

[Renovate Quarkus 3.28.1 bump PR](https://github.com/apache/polaris/pull/2648). Can be reproduced locally as well.

The issue is _not_ particularly in the `quarkusBuild` task implementation, but raised in a [custom Gradle code](https://github.com/apache/polaris/blob/091fe6f6a269528d95e4d43f7aa2ef90f90cd093/build-logic/src/main/kotlin/Utilities.kt#L76-L106) to make the `quarkus-run.jar`, `generated-bytecode.jar` and `transformed-bytecode.jar` files a (bit more) reproducible by re-recreating those with a fixed file modification timestamp for all zip entries.

However, the exception is thrown because there is a duplicate entry in at least one of the jars created by Quarkus.

In the particular case it is `duplicate entry: io/quarkus/opentelemetry/runtime/config/runtime/exporter/OtlpExporterConfig$$CMImpl.class`.

Reproducer: checkout the renovate-PR branch, run `./gradlew :polaris-server:quarkusBuild --stacktrace`.

The above works fine up to Quarkus 3.27.0.

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by gsmet**
Also guard against it in the Jar generation to make sure we don't end up with duplicate entries.

Fixes #50265

### CODE REVIEW

**Comment by gsmet** [comment]
@radcortez I would appreciate if you could prioritize the review as we need the fix in 3.28.2.

**Review by radcortez — APPROVED** [review]

**Comment by radcortez** [comment]
The check seems to be failing with other generated classes.

**Comment by gsmet** [comment]
> The check seems to be failing with other generated classes.

I'll have a look once I get a full CI report.

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ConfigBuildStep.java [hunk 1]
```diff
@@ -268,8 +268,13 @@ void generateConfigProperties(
             BuildProducer<ConfigClassBuildItem> configClasses,
             BuildProducer<AdditionalConstrainedClassBuildItem> additionalConstrainedClasses) {
 
-        processConfigClasses(combinedIndex, generatedClasses, reflectiveClasses, reflectiveMethods, configClasses,
+        Map<String, GeneratedClassBuildItem> generatedConfigClasses = new HashMap<>();
```
Comment (snazy) [inline extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ConfigBuildStep.java:273]: (Not very familiar with the code-generation code, so ignore my comment, if it doesn't apply)

Should this be a `LinkedHashMap` for reproducibility?

File: core/deployment/src/main/java/io/quarkus/deployment/steps/ConfigGenerationBuildStep.java [hunk 2]
```diff
@@ -204,20 +204,27 @@ void generateMappings(
             BuildProducer<ConfigClassBuildItem> configClasses,
             BuildProducer<AdditionalConstrainedClassBuildItem> additionalConstrainedClasses) {
 
-        processConfigMapping(combinedIndex, generatedClasses, reflectiveClasses, reflectiveMethods, configClasses,
+        Map<String, GeneratedClassBuildItem> generatedConfigClasses = new HashMap<>();
```
Comment (snazy) [inline core/deployment/src/main/java/io/quarkus/deployment/steps/ConfigGenerationBuildStep.java:207]: (Not very familiar with the code-generation code, so ignore my comment, if it doesn't apply)

Should this be a `LinkedHashMap` for reproducibility?

File: core/deployment/src/main/java/io/quarkus/deployment/configuration/ConfigMappingUtils.java [hunk 3]
```diff
@@ -121,8 +122,8 @@ private static void processConfigClass(
             generatedClassesNames.add(mappingMetadata.getClassName());
             // This is the generated implementation of the mapping by SmallRye Config.
             byte[] classBytes = mappingMetadata.getClassBytes();
-            generatedClasses.produce(new GeneratedClassBuildItem(isApplicationClass, mappingMetadata.getClassName(),
-                    classBytes));
+            generatedConfigClasses.put(mappingMetadata.getClassName(),
```
Comment (snazy) [inline core/deployment/src/main/java/io/quarkus/deployment/configuration/ConfigMappingUtils.java:129]: Wonder if it's sufficient to check for `generatedConfigClasses.put() != null` instead of doing a `Stream.sorted().count()` in `AbstractJarBuilder`.

**Review by snazy — COMMENTED** [review]
Thanks for the quick fix :)

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ConfigBuildStep.java (hunk 1 above)
Comment (gsmet) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ConfigBuildStep.java:273]: The elements are sorted when necessary i.e. later when assembling the jar.

Build steps are generating classes in parallel so the list is not really ordered.

File: core/deployment/src/main/java/io/quarkus/deployment/configuration/ConfigMappingUtils.java (hunk 3 above)
Comment (gsmet) [reply core/deployment/src/main/java/io/quarkus/deployment/configuration/ConfigMappingUtils.java:129]: I want the full list of problematic classes, otherwise it makes fixing issues very annoying.
