### PR TITLE
Ensure the refreshed CSRF cookie retains the original value

### LINKED ISSUE #38225: CSRF Token is refreshed on every request
### Describe the bug

As far as I know the token expiry should be extended but not the token itself shouldn't be changed on new request. Currently this makes requests with htmx fails as after the first request the token is wrong.

### Expected behavior

The token expiry should be increased but the token should be the same

### Actual behavior

it changes the token

### How to Reproduce?

clone https://github.com/ia3andy/renotes/
start with `quarkus dev`
load the page and refresh many times, keep a look on the body tag, you will see the token getting updated

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

 3.6.5

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sberyozkin**
Fixes #38225.

I'm feeling totally wrecked after working on another CSRF PR and it is only a middle of Jan :-)

IMHO this PR should fix all the issues.

Here is what it does when the CSRF cookie is present for safe requests:

* If the token header is also present then verify it and it will ensure the original header value is fed into the code which will refresh the cookie with the same value but new expiry
* If the token header is not present then the new cookie will be created if the signature is also required to avoid double signing issue for HTML forms
* Otherwise the cookie value is reused
* Tests: for HTML forms it is verified the cookie has the the same value after 2 submissions, with the 1st cookie expiry date being before the 2nd one; for the headers only the cookie values are checked to be the same - we use Vertx WebClient to test `//` in the path and it has no Cookie objects, so I'm just comparing the values, the dates check in the HTML forms should be enough though

@gsmet I'm not sure you'd like to wait till @FroMage and @ia3andy can confirm it resolves the reported HTMX issue with multiple forms but CC-ing just in case.

Also CC @BarDweller

### CODE REVIEW

**Review by ia3andy — APPROVED** [review]
Tested on the renotes app with success. Thanks

File: extensions/csrf-reactive/runtime/src/main/java/io/quarkus/csrf/reactive/runtime/CsrfRequestResponseReactiveFilter.java [hunk 1]
```diff
@@ -87,12 +87,26 @@ public void filter(ResteasyReactiveContainerRequestContext requestContext, Routi
...
-
+                if (cookieToken == null) {
+                    generateNewCsrfToken(routing, config);
+                } else {
+                    String csrfTokenHeaderParam = requestContext.getHeaderString(config.tokenHeaderName);
+                    if (csrfTokenHeaderParam != null) {
+                        LOG.debugf("CSRF token found in the token header");
+                        // Verify the header, make sure the header value, possibly signed, is returned as the next cookie value
+                        verifyCsrfToken(requestContext, routing, config, cookieToken, csrfTokenHeaderParam);
+                    } else if (!config.tokenSignatureKey.isEmpty()) {
```
Comment (ia3andy) [inline extensions/csrf-reactive/runtime/src/main/java/io/quarkus/csrf/reactive/runtime/CsrfRequestResponseReactiveFilter.java:98]:
```suggestion
                    } else if (config.tokenSignatureKey.isPresent()) {
```

**Review by gsmet — APPROVED** [review]

**Comment by sberyozkin** [comment]
Thanks @ia3andy for a quick check, sorry I missed your suggestion, I'll simplify as you propose during some other fix which will be probably needed soon enough :-)

File: extensions/csrf-reactive/runtime/src/main/java/io/quarkus/csrf/reactive/runtime/CsrfRequestResponseReactiveFilter.java [hunk 2]
```diff
@@ -87,12 +87,26 @@ public void filter(ResteasyReactiveContainerRequestContext requestContext, Routi
...
+                        // If the signature is required, then we can not use the current cookie value
+                        // as the HTML form token key because it represents a signed value of the previous key
+                        // and it will lead to the double-signing issue if this value is reused as the key.
+                        // It should be fine for simple HTML forms anyway
```
Comment (FroMage) [inline extensions/csrf-reactive/runtime/src/main/java/io/quarkus/csrf/reactive/runtime/CsrfRequestResponseReactiveFilter.java:102]: I do not understand this comment. We have two ways to get a token: cookie or header. Here we're in a situation where we have a signed cookie, and we don't have a header. Why do we have to regenerate a token? Why would the previous signature be invalid?

**Review by FroMage — COMMENTED** [review]
OK, so it's too late for a review, too bad.

I think there's something that can potentially go bad here, if a client is stuck with a non-expired cookie or a header and the token is signed with a previous signature: in this case we always generate a bad request, even for safe methods, and so we never renew the token or fix the situation.

If that happens, the only way users can recover is by waiting for the cookie to expire, or manually clean cookies.

I think for safe methods, token issues should auto-recover, no?

**Comment by FroMage** [comment]
@sberyozkin any opinion about the comments?

File: extensions/csrf-reactive/runtime/src/main/java/io/quarkus/csrf/reactive/runtime/CsrfRequestResponseReactiveFilter.java (hunk 2 above)
Comment (takesson) [reply extensions/csrf-reactive/runtime/src/main/java/io/quarkus/csrf/reactive/runtime/CsrfRequestResponseReactiveFilter.java:102]: I guess this would lead to double-signing given that signing is done in the ResponseFilter. 

Is there a specific reason why signing cannot be done in generateNewCsrfToken(..) and use a single routing parameter?

File: extensions/csrf-reactive/runtime/src/main/java/io/quarkus/csrf/reactive/runtime/CsrfRequestResponseReactiveFilter.java [hunk 3]
```diff
@@ -87,12 +87,26 @@ public void filter(ResteasyReactiveContainerRequestContext requestContext, Routi
...
-                routing.put(CSRF_TOKEN_KEY, Base64.getUrlEncoder().withoutPadding().encodeToString(tokenBytes));
-
+                if (cookieToken == null) {
+                    generateNewCsrfToken(routing, config);
+                } else {
+                    String csrfTokenHeaderParam = requestContext.getHeaderString(config.tokenHeaderName);
+                    if (csrfTokenHeaderParam != null) {
+                        LOG.debugf("CSRF token found in the token header");
+                        // Verify the header, make sure the header value, possibly signed, is returned as the next cookie value
+                        verifyCsrfToken(requestContext, routing, config, cookieToken, csrfTokenHeaderParam);
```
Comment (takesson) [inline extensions/csrf-reactive/runtime/src/main/java/io/quarkus/csrf/reactive/runtime/CsrfRequestResponseReactiveFilter.java:97]: Should this situation really abort the request if token is incorrect? I think it should verify and generate a new cookie if verification fails. I think it would resolve @FroMage 's concern about changed signature key (stuck cookie).

What is the reason for converting a request header to a cookie? Based on my understanding, the important part is preserving the cookie token btw requests.
