### PR TITLE
Ensure that MessageBodyWriter is passed the proper media type

### LINKED ISSUE #41354: MessageBodyWriter not selected went no Accept header is set
### Describe the bug

In the recent Quarkus patch version ( >= `3.11.2`) we noticed a change in behaviour in how MessageBodyWriter selection occurred when the HTTP `Accept` header is not set. When the header is not present our custom MessageBodyWriter will no longer be selected and applied for the response.

This change in behaviour seems like a bug.

### Expected behavior

Even if the `Accept` header was not set is should default to the most appropriate MessageBodyWriter.

### Actual behavior

When the `Accept` header is not set is will default to and internal default MessageBodyWriter.

One solution to this is to add a `@Produces` annotation to the custom  MessageBodyWriter but this seems like duplication as its on the endpoint:
image

### How to Reproduce?

Clone: https://github.com/jholleran/message-body-writer-selection
Run: `./mvnw clean test`
The tests that fail reproduce this issue.

Changing the `quarkus.platform.version` to 3.11.1 in the pom.xml and the tests will now pass

### Output of `uname -a` or `ver`

Linux triton 6.1.0-1029-oem #29-Ubuntu SMP PREEMPT_DYNAMIC Tue Jan  9 21:07:34 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

17.0.11

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)

### Additional information

This change in behaviour seems to have been caused by this change: https://github.com/quarkusio/quarkus/pull/41111

### PR DESCRIPTION
**Pull request by geoand**
- Fixes: #41354

### CODE REVIEW

File: independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/serialization/DynamicEntityWriter.java [hunk 1]
```diff
@@ -41,22 +42,27 @@ public void write(ResteasyReactiveRequestContext context, Object entity) throws
...
                 List<String> accepts = context.getHttpHeaders().getRequestHeader(HttpHeaders.ACCEPT);
                 for (String accept : accepts) {
-                    negotiatedMediaType = context.getTarget().getProduces().negotiateProduces(accept).getKey();
+                    negotiatedMediaType = producesServerMediaType.negotiateProduces(accept).getKey();
                     if (negotiatedMediaType != null) {
                         break;
                     }
                 }
+                if (negotiatedMediaType == null) { // fallback to ensure that MessageBodyWriter is passed the proper media type
+                    negotiatedMediaType = producesServerMediaType
```
Comment (gastaldi) [inline independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/serialization/DynamicEntityWriter.java:55]: How is this different from what is done in the loop above? Would it make sense to replace the loop with this call only?

Comment (geoand) [reply independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/serialization/DynamicEntityWriter.java:55]: It uses the original HTTP headers, not the ones that filters can add to.

At some point this needs to be cleaned up, but not today :)

**Review by gastaldi — APPROVED** [review]
