### PR TITLE
Use a Quarkus-specific clock provider that is reinitialized at runtime

### LINKED ISSUE #32831: Hibernate Validator Failure When TZ Set to Non-UTC
### Describe the bug

Annotation-based validation via the Hibernate Validator module can fail in native mode if the time zone is set to anything but UTC. This only applies to running a native build inside a container. The container's OS time zone is set to local time, but in order to make the Quarkus application run in local time, too, setting the `TZ` environment variable is necessary. However, if this variable is set to anything but `UTC`, validation on time-based types can fail.

Specifically, I am using `@PastOrPresent`  on a `LocalDateTime` field that is part of an entity class. The `LocalDateTime` is set to `LocalDateTime.now()`, so this should not fail when validation is being run. However, under the aforementioned circumstances of having set `TZ` to anything that has a positive offset to UTC, an exception is thrown, stating that the time must be in the past or present. 

Seemingly, the explanation for this is that validation is internally still using UTC while the rest of the Quarkus application is running with the TZ that has been set. I have tried setting `quarkus.hibernate-orm.jdbc.timezone` to the same TZ, but this has no effect.

The issue only occurs for native builds, and does not occur for JVM-based images.

I am using the `quarkus-micro-image:2.0` as the base.

The issue occurs when building for Java 17 with the Mandel builder image (v22.3) as well as when using Java 19 with GraalVM CE (v22.3).

### Expected behavior

Validation should pass, because the field is valid.

### Actual behavior

Validation throws an exception.

### How to Reproduce?

https://github.com/this-user/quarkus-hibernate-validation-issue-tz

Steps to reproduces:

 1. Comment out `quarkus.test.arg-line` that sets the TZ in `application.properties`
 2. Run `./gradlew testNative --info`
 3. Integration tests pass
 4. Remove comment from 1. and run tests again, now with non-UTC TZ
 5. Tests will fail because validation of `TestEntity` fails

### Output of `uname -a` or `ver`

Linux 6.2.11-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 13 Apr 2023 16:59:24 +0000 x86_64 GNU/Linux

### Output of `java -version`

17.0.6

### GraalVM version (if different from Java)

22.3.1.0

### Quarkus version or git rev

2.16.6 Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.0.2

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by marko-bekhta**
fixes https://github.com/quarkusio/quarkus/issues/32831

So that reloading at runtime, we've discussed in the issue comments,  worked! 

I've also added another execution to the native tests to pass a non-default timezone to get that scenario tested. But if there's a simpler way to achieve that -- please let me know 😃

### CODE REVIEW

File: extensions/hibernate-validator/runtime/src/main/java/io/quarkus/hibernate/validator/runtime/clockprovider/HibernateValidatorClockProvider.java [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+
+    private HibernateValidatorClockProvider() {
+    }
+
+    @Override
+    public Clock getClock() {
+        return clock;
+    }
+
+    private static class HibernateClock extends Clock {
```
Comment (gsmet) [inline extensions/hibernate-validator/runtime/src/main/java/io/quarkus/hibernate/validator/runtime/clockprovider/HibernateValidatorClockProvider.java:26]: Don't you think the constant could live in this very class and we could avoid having one additional class?

Also, maybe we need a better name `RuntimeReinitializedDefaultClock`?

**Review by gsmet — COMMENTED** [review]
The principle LGTM thanks!

I added a small comment though.

File: extensions/hibernate-validator/runtime/src/main/java/io/quarkus/hibernate/validator/runtime/clockprovider/HibernateValidatorClockProvider.java (hunk 1 above)
Comment (marko-bekhta) [reply extensions/hibernate-validator/runtime/src/main/java/io/quarkus/hibernate/validator/runtime/clockprovider/HibernateValidatorClockProvider.java:26]: You mean the timezone constant right?
I've started with that but the native build failed in that case. I don't have the exact message, but essentially it was saying that the clock provider / clock instances were created and such class cannot be reinitialised (at least that was my understanding of the failure 🙈)
I'll update the clock class name and add the error I've seen once I'm around the workstation 

Thanks for taking a look 😊

Comment (gsmet) [reply extensions/hibernate-validator/runtime/src/main/java/io/quarkus/hibernate/validator/runtime/clockprovider/HibernateValidatorClockProvider.java:26]: Yeah OK, no need to dig if it wasn't working. Maybe add a comment in the code so that our futur selves don't try to simplify it later.

Comment (marko-bekhta) [reply extensions/hibernate-validator/runtime/src/main/java/io/quarkus/hibernate/validator/runtime/clockprovider/HibernateValidatorClockProvider.java]: An error (if we try to reinit the clock provider itself) for the history 😃:
```
Error: An object of type 'io.quarkus.hibernate.validator.runtime.clockprovider.HibernateValidatorClockProvider' was found in the image heap. This type, however, is marked for initialization at image run time for the following reason: classes are initialized at run time by default.
This is not allowed for correctness reasons: All objects that are stored in the image heap must be initialized at build time.

You now have two options to resolve this:

1) If it is intended that objects of type 'io.quarkus.hibernate.validator.runtime.clockprovider.HibernateValidatorClockProvider' are persisted in the image heap, add 

    '--initialize-at-build-time=io.quarkus.hibernate.validator.runtime.clockprovider.HibernateValidatorClockProvider'

to the native-image arguments. Note that initializing new types can store additional objects to the heap. It is advised to check the static fields of 'io.quarkus.hibernate.validator.runtime.clockprovider.HibernateValidatorClockProvider' to see if they are safe for build-time initialization,  and that they do not contain any sensitive data that should not become part of the image.

2) If these objects should not be stored in the image heap, you can use 

    '--trace-object-instantiation=io.quarkus.hibernate.validator.runtime.clockprovider.HibernateValidatorClockProvider'

to find classes that instantiate these objects. Once you found such a class, you can mark it explicitly for run time initialization with 

    '--initialize-at-run-time=<culprit>'

to prevent the instantiation of the object.

If you are seeing this message after enabling '--strict-image-heap', this means that some objects ended up in the image heap without their type being marked with --initialize-at-build-time.
To fix this, include '--initialize-at-build-time=io.quarkus.hibernate.validator.runtime.clockprovider.HibernateValidatorClockProvider' in your configuration. If the classes do not originate from your code, it is advised to update all library or framework dependencies to the latest version before addressing this error.
Please address this problem to be prepared for future releases of GraalVM.

The following detailed trace displays from which field in the code the object was reached.
Trace: Object was reached by
  reading field org.hibernate.validator.internal.engine.constraintvalidation.HibernateConstraintValidatorInitializationContextImpl.clockProvider of constant 
    org.hibernate.validator.internal.engine.constraintvalidation.HibernateConstraintValidatorInitializationContextImpl@127ff225: org.hibernate.validator.internal.engine.constraintvalidation.HibernateConstraint...
  reading field org.hibernate.validator.internal.engine.ValidatorFactoryScopedContext.constraintValidatorInitializationContext of constant 
    org.hibernate.validator.internal.engine.ValidatorFactoryScopedContext@41d08dc7: org.hibernate.validator.internal.engine.ValidatorFactoryScopedContext@41d08dc7
  reading field org.hibernate.validator.internal.engine.PredefinedScopeValidatorFactoryImpl.validatorFactoryScopedContext of constant 
    org.hibernate.validator.internal.engine.PredefinedScopeValidatorFactoryImpl@3743cd98: org.hibernate.validator.internal.engine.PredefinedScopeValidatorFactoryImpl@3743...
  reading field io.quarkus.hibernate.validator.runtime.HibernateValidatorRecorder$2$1.val$validatorFactory of constant 
    io.quarkus.hibernate.validator.runtime.HibernateValidatorRecorder$2$1@4a89722e: io.quarkus.hibernate.validator.runtime.HibernateValidatorRecorder$2$1@4a89722e
  reading field java.util.concurrent.ConcurrentLinkedDeque$Node.item of constant 
    java.util.concurrent.ConcurrentLinkedDeque$Node@368bcdb6: java.util.concurrent.ConcurrentLinkedDeque$Node@368bcdb6
  reading field java.util.concurrent.ConcurrentLinkedDeque$Node.prev of constant 
    java.util.concurrent.ConcurrentLinkedDeque$Node@38f22cb4: java.util.concurrent.ConcurrentLinkedDeque$Node@38f22cb4
  reading field java.util.concurrent.ConcurrentLinkedDeque.head of constant 
    java.util.concurrent.ConcurrentLinkedDeque@55bfd898: [io.quarkus.hibernate.validator.runtime.HibernateValidatorRecorder$2$1@4a89722e,...
  reading field io.quarkus.runtime.StartupContext.shutdownTasks of constant 
    io.quarkus.runtime.StartupContext@5b8adfe6: io.quarkus.runtime.StartupContext@5b8adfe6
  reading static field io.quarkus.runner.ApplicationImpl.STARTUP_CONTEXT
    at io.quarkus.runner.ApplicationImpl.doStop(Unknown Source)
  parsing method io.quarkus.runner.ApplicationImpl.doStop(Unknown Source) reachable via the parsing context
    at io.quarkus.runtime.Application.stop(Application.java:208)
    at io.quarkus.runtime.Application.close(Application.java:137)
    at java.io.FileDescriptor.closeAll(FileDescriptor.java:352)
    at java.io.FileInputStream.close(FileInputStream.java:524)
    at jdk.xml.internal.SecuritySupport.loadProperties(SecuritySupport.java:239)
    at jdk.xml.internal.SecuritySupport.readConfig(SecuritySupport.java:217)
    at com.sun.org.apache.xerces.internal.utils.XMLSecurityPropertyManager.getSystemProperty(XMLSecurityPropertyManager.java:234)
    at com.sun.org.apache.xerces.internal.utils.XMLSecurityPropertyManager.readSystemProperties(XMLSecurityPropertyManager.java:215)
    at com.sun.org.apache.xerces.internal.utils.XMLSecurityPropertyManager.<init>(XMLSecurityPropertyManager.java:96)
    at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl.<init>(DocumentBuilderFactoryImpl.java:58)
    at com.oracle.svm.core.code.FactoryMethodHolder.DocumentBuilderFactoryImpl_constructor_fe18771c43c781794fd627c47aabb2c91c25ceff(generated:0)
    at static root method.(Unknown Source)
```

**Review by gsmet — APPROVED** [review]
