### PR TITLE
Fix oidc-client token retrieval under concurrency

### LINKED ISSUE #40923: `@OidcClientFilter` triggers several tokens in concurrency conditions 💣
### Describe the bug

When the [rest client](https://quarkus.io/guides/security-openid-connect-client-reference#resteasy-client-oidc-filter) is used for the first time, or when the token is being refreshed, multiple concurrent calls cause multiple request to retrieve the token.

It happens when the concurrency could even come from : 
- outside of the application _(through concurrent REST/gRPC calls)_ during a burst period
- or from the application itself as well, when concurrent calls are made _(throughout a `Uni.join()`)_

### Expected behavior

The token be retrieved once and shared for all customer calls, like in no concurrency conditions

### Actual behavior

Each concurrent call triggers a token retrieval 

### How to Reproduce?

I made a [test-case](https://github.com/Dougniel/quarkus-rest-client-oidc-race-condition/blob/main/src/test/java/org/acme/GreetingResourceTest.java) that simulates concurrency from outside the application and from inside. The test fails as only one call is expected to the `/oauth2/token`

### Output of `uname -a` or `ver`

Darwin Kernel Version 23.5.0 arm64

### Output of `java -version`

openjdk version "21.0.2" 2024-01-16 LTS OpenJDK Runtime Environment Temurin-21.0.2+13 (build 21.0.2+13-LTS) OpenJDK 64-Bit Server VM Temurin-21.0.2+13 (build 21.0.2+13-LTS, mixed mode)

### Quarkus version or git rev

3.11.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.9.6

### Additional information

I had a look at [`TokensHelper.java`](https://github.com/quarkusio/quarkus/blob/main/extensions/oidc-client/runtime/src/main/java/io/quarkus/oidc/client/runtime/TokensHelper.java) and it seems that the problem is between the first call to get the token and the reply : subsequent clients calls subscribes the same `Uni<Tokens>` thought the filter and so, triggers again the call to get the token. 

So I made a [patch](https://github.com/Dougniel/quarkus-rest-client-oidc-race-condition/blob/f3e28fba42da3fda2edcdaa32752e304c2520e5f/src/main/java/org/acme/runtime/PatchedTokensHelper.java#L79) by doing a `.memorize()` on `Uni<Tokens>` before `prepareUni(Uni<Tokens> uni)` returns

### PR DESCRIPTION
**Pull request by Dougniel**
Hi there 👋,

This PR fix a bug that leads to retrieve as much as tokens than the number of concurrent calls to the REST Client (more details: #40923)

The correction consist of using the `Uni.memorize()` to prevent a second call to the same `Uni<Tokens>` to trigger a new request to the auth server.

Such race conditions cases are tricky to test, so I did a new end-to-end case with Wiremock to have a clear and reproducible state  with : 
- a separate oidc-client configuration in order to not affect other tests cases
- [`early-tokens-acquisition`](https://quarkus.io/guides/security-openid-connect-client-reference#quarkus-oidc-client_quarkus-oidc-client-early-tokens-acquisition) feature disabled, because it was hiding this bug the first time the token was retrieved after application starts (except in reactive favour)
- Some delay defined in Wiremock to ensure the race condition case happens

Following [the advices](https://github.com/quarkusio/quarkus/issues/40923#issuecomment-2142947483) of @sberyozkin
/cc @michalvavrik, @stuartwdouglas, @cescoffier, @jponge

Thx

- Fixes: #40923

### CODE REVIEW

**Comment by gsmet** [comment]
@cescoffier I would prefer you have a look at this one. Thanks!

**Review by sberyozkin — APPROVED** [review]
Thanks @Dougniel

The spec of `memoize` fits fixing the problem perfectly, to prevent issuing multiple parallel token acquisition requests for the same OIDC client. 
We have a few other uses of memoize in the oidc code, ex, in the tenant resolution case.

I plan to merge next Tue when I'm back from PTO, unless @cescoffier has other comments.

File: extensions/oidc-client/runtime/src/main/java/io/quarkus/oidc/client/runtime/TokensHelper.java [hunk 1]
```diff
@@ -77,7 +77,9 @@ public void accept(Tokens tokens, Throwable throwable) {
                     tokenRequestStateUpdater.set(TokensHelper.this, null);
                 }
             }
-        });
+        })
+                // prevent next subscriptions to trigger multiple times the HTTP request before the end of the first one
+                .memoize().indefinitely();
```
Comment (cescoffier) [inline extensions/oidc-client/runtime/src/main/java/io/quarkus/oidc/client/runtime/TokensHelper.java:82]: Is this Uni reused or recreated every time? 

Without this information, this could have dramatic consequences.
Also, it may cause a duplicated context issue.

**Review by cescoffier — DISMISSED** [review]
Mostly clarification.

File: extensions/oidc-client/runtime/src/main/java/io/quarkus/oidc/client/runtime/TokensHelper.java (hunk 1 above)
Comment (Dougniel) [reply extensions/oidc-client/runtime/src/main/java/io/quarkus/oidc/client/runtime/TokensHelper.java:82]: Hi @cescoffier, in my understanding this Uni is created when a new request to get a new token is made and is replaced by the new token as soon as it's received. A new token is requested when the previous one expires every _N_ seconds.

Do you agree with that @sberyozkin ?

Comment (sberyozkin) [reply extensions/oidc-client/runtime/src/main/java/io/quarkus/oidc/client/runtime/TokensHelper.java:82]: @Dougniel Yes, I do, only a minor clarification is that a new token is requested if the current one expires not every N seconds, but only when it is found that the  current one has expired at  the moment it is required. But otherwise, indeed, Uni is only used to acquire new tokens, once the tokens are available, they are accessed directly, https://github.com/quarkusio/quarkus/blob/main/extensions/oidc-client/runtime/src/main/java/io/quarkus/oidc/client/runtime/TokensHelper.java#L62

@cescoffier Does what @Dougniel explained and my comment above address your concern ?

**Comment by sberyozkin** [comment]
@cescoffier Let me merge now, and see how it settles on main for a few days, should be fine given that Unis are not reused. If we observe any side-effects over a while we can revert
