### PR TITLE
Fix Quarkus REST issue where HEAD returned 405

### LINKED ISSUE #49172: Resteasy-reactive: HEAD returns 405 in the REST resource in some cases
### Describe the bug

Assume that I have:
- JAX-RS REST resource class with the GET method and some @Path like for example this:

```
    @GET
    @Path("/subpath")
    public String get() {
        return "y";
    }
```

As long as this is the only method on the resource (or there are some other "resource" methods with the HTTP method annotations), then HTTP method HEAD method works as expected and returns the headers for this resource. However when this class has another resource *without* HTTP method. For example something like this:

```
    @Path("/zpath")
    public ZResource getAnotherResource() {
        return CDI.current()
                .select(ZResource.class)
                .get();
    }
```

Then method HEAD on the original resource (with path `/subpath`) returns "405 Method not allowed" . The `GET` method on the `/subpath` works as expected and returns 200 and successful response. Only the method `HEAD` is broken.

### Expected behavior

Method `HEAD` works and returns 200

### Actual behavior

Method `HEAD` does not work and returns 405

### How to Reproduce?

Created reproducer project here: https://github.com/mposolda/quarkus-reproducer-resteasy-head-bug

When running `mvnw test` there is failing test due this bug

### Output of `uname -a` or `ver`

Linux mposolda-ThinkPad-P1-Gen-7 6.14.0-24-generic #24~24.04.3-Ubuntu SMP PREEMPT_DYNAMIC Mon Jul  7 16:39:17 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "21.0.8" 2025-07-15 OpenJDK Runtime Environment (build 21.0.8+9-Ubuntu-0ubuntu124.04.1) OpenJDK 64-Bit Server VM (build 21.0.8+9-Ubuntu-0ubuntu124.04.1, mixed mode, sharing)

### Quarkus version or git rev

3.24.5

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.8

### Additional information

- I consider this a bug as when `@HEAD` annotation is not present, there should be fallback to the `@GET` according to [this section of jax-rs specification - point 2](https://jakarta.ee/specifications/restful-ws/3.0/jakarta-restful-ws-spec-3.0#head_and_options)

- This was originally created as a bug in Keycloak - https://github.com/keycloak/keycloak/issues/41537

- This is likely related to this issue https://github.com/quarkusio/quarkus/issues/43422 . This is a follow-up to that as that issue did not fixed everything. There is probably some more tweaks needed in the class `ResourceLocatorHandler` . Basically when the [line 84](https://github.com/quarkusio/quarkus/blob/3.24.5/independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/handlers/ResourceLocatorHandler.java#L84) returns non-null mapper, then [this block](https://github.com/quarkusio/quarkus/blob/3.24.5/independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/handlers/ResourceLocatorHandler.java#L91-L105) is not executed, which causes `HEAD` to return 405.

### PR DESCRIPTION
**Pull request by mposolda**
- Fixes: #49172

### CODE REVIEW

File: independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/handlers/ResourceLocatorHandler.java [hunk 1]
```diff
@@ -79,15 +79,17 @@ public void onComplete(Throwable throwable) {
...
         RequestMapper<RuntimeResource> mapper = target.get(requestContext.getMethod());
+        RequestMapper.RequestMatch<RuntimeResource> res = findRequestMatch(mapper, requestContext);
         boolean hadNullMethodMapper = false;
         if (mapper == null) {
             mapper = target.get(null); //another layer of resource locators maybe
             // we set this without checking if we matched, but we only use it after
             // we check for a null mapper, so by the time we use it, it must have meant that
             // we had a matcher for a null method
             hadNullMethodMapper = true;
+            res = findRequestMatch(mapper, requestContext);
```
Comment (FroMage) [inline independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/handlers/ResourceLocatorHandler.java]: Here it seems we're invoking `findRequestMatch()` again discarding the first value of `res`, but probably this only happens when `mapper` was `null` so `res` was also `null`. It makes it a bit hard to read, though.

File: independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/handlers/ResourceLocatorHandler.java [hunk 2]
```diff
@@ -109,8 +111,9 @@ public void onComplete(Throwable throwable) {
         if (mapper == null) {
             throw new WebApplicationException(Response.status(Response.Status.METHOD_NOT_ALLOWED.getStatusCode()).build());
         }
-        RequestMapper.RequestMatch<RuntimeResource> res = mapper
-                .map(requestContext.getRemaining().isEmpty() ? "/" : requestContext.getRemaining());
+        if (res == null) {
+            res = findRequestMatch(mapper, requestContext);
```
Comment (FroMage) [inline independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/handlers/ResourceLocatorHandler.java]: This again looks like we could invoke `findRequestMatch()` twice with the same parameters, if it returned `null` the first time.

**Review by FroMage — CHANGES_REQUESTED** [review]
This is probably correct, but I find the repeated calls to `findRequestMatch` hard to read, in two cases it looks like we may be invoking it several times in a row with the same parameters. Perhaps there's a way to rewrite it more clearly?

**Comment by mposolda** [comment]
@FroMage Thanks for the review! I've tried to make it that `findRequestMatch` is not called multiple times with the same mapper, but agree that code was maybe harder to follow and could possibly happen that it is called with same mapper two times in the 2nd case you mentioned.

I've rewrote this block a bit. It is more changes in the PR, but hopefully now it is more clear that `findRequestMatch` is never called multiple times with same mapper argument. What do you think now?

**Review by FroMage — APPROVED** [review]
Thanks, that's easier to understand :)

**Comment by geoand** [comment]
The CI failures are likely unrelated to the PR  as similar failures can be seen in other PRs as well

**Comment by FroMage** [comment]
That's a lot of failures, though 😲
