### PR TITLE
Ensure @JsonProperty value on Panache Entity is honored

### LINKED ISSUE #11505: Value of @JsonProperty on a field inside a subclass of PanacheEntityBase is ignored
**Describe the bug**
Having a class extend `PanacheEntityBase` and annotating a (column) field with `@JsonProperty("something_else")` (so as to rename the field to `something_else` in json) does not work. The value in `JsonProperty` gets ignored and the name of the field is used.
Sample class
```java
public class Something extends PanacheEntityBase {
    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long id;
    @Column(name = "something_else") @JsonProperty("something_else")
    public String somethingElse;
}
```

**Expected behavior**
given the sample class, I would expect a json similar to the format:
```json
{"id": 5, "something_else": "this is something else"}
```

**Actual behavior**
the actual json generated from jackson is similar to the format:
```json
{"id": 5, "somethingElse": "this is something else"}
```

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #11505

See https://github.com/quarkusio/quarkus/issues/11505#issuecomment-726578099 for a full explanation of why this is needed

### CODE REVIEW

**Review by FroMage — APPROVED** [review]
That looks like the right fix, but I think we may want to move the `visitEnd()` call to the common path, no? I mean, it worked before without calling it, but it's probably more correct to always call it in both cases…

**Comment by geoand** [comment]
Right, that makes perfect sense. I'll update the PR

**Comment by geoand** [comment]
Done

**Review by FroMage — APPROVED** [review]

File: extensions/panache/panache-common/deployment/src/main/java/io/quarkus/panache/common/deployment/PanacheEntityEnhancer.java [hunk 1]
```diff
@@ -23,6 +23,7 @@
     public static final String JSON_PROPERTY_SIGNATURE = "L" + JSON_PROPERTY_BINARY_NAME + ";";
 
     public static final DotName JSON_IGNORE_DOT_NAME = DotName.createSimple("com.fasterxml.jackson.annotation.JsonIgnore");
+    public static final DotName JSON_PROPERTY_DOT_NAME = DotName.createSimple("com.fasterxml.jackson.annotation.JsonProperty");
```
Comment (gsmet) [inline extensions/panache/panache-common/deployment/src/main/java/io/quarkus/panache/common/deployment/PanacheEntityEnhancer.java:26]: Is there a reason why we don't have the same mechanism for `@JsonbProperty`?

Comment (geoand) [reply extensions/panache/panache-common/deployment/src/main/java/io/quarkus/panache/common/deployment/PanacheEntityEnhancer.java:26]: Good question.

The reason is that these `@JsonProperty` shenanigans are only needed because of the `@XmlTransient` shenanigans - which Jsonb doesn't seem to care about at all.
