### PR TITLE
ORM/HR/Panache: rely on ORM getResultCount

### LINKED ISSUE #40962: Specifying parameters in sorting will throw an exception
### Describe the bug

I'm using Panache to simplify Hibernate queries. When I use the following query, I get an exception:

`find("name = :name ORDER BY ST_Distance(location, :location) DESC", Map.of("name", "Demo","location", point))`

> point is a `org.locationtech.jts.geom.Point`

But, If I create the query directly using Hibernate, everything is fine.

```
this.getEntityManager().createQuery("FROM Store ORDER BY ST_Distance(location, :location)")
    .setParameter("name", "Demo")
    .setParameter("location", point);
```

### Expected behavior

Set the parameters correctly

### Actual behavior

UnknownParameterException: No parameter named ':location' in query with named parameters []

```
java.lang.IllegalArgumentException: No parameter named ':location' in query with named parameters []
	at org.hibernate.query.internal.ParameterMetadataImpl.getQueryParameter(ParameterMetadataImpl.java:262)
	at org.hibernate.query.spi.AbstractCommonQueryContract.setParameter(AbstractCommonQueryContract.java:826)
	at org.hibernate.query.spi.AbstractSelectionQuery.setParameter(AbstractSelectionQuery.java:882)
	at org.hibernate.query.sqm.internal.QuerySqmImpl.setParameter(QuerySqmImpl.java:1200)
	at org.hibernate.query.sqm.internal.QuerySqmImpl.setParameter(QuerySqmImpl.java:136)
	at io.quarkus.hibernate.orm.panache.common.runtime.AbstractJpaOperations.bindParameters(AbstractJpaOperations.java:162)
	at io.quarkus.hibernate.orm.panache.common.runtime.CommonPanacheQueryImpl.count(CommonPanacheQueryImpl.java:290)
	at io.quarkus.hibernate.orm.panache.runtime.PanacheQueryImpl.count(PanacheQueryImpl.java:144)
//// MORE ////
```

### How to Reproduce?

In the description part gives a simple query, only need to create a table, containing the Point/geom type field;

Regardless of the database, the behavior is the same in MySQL and Postgresql

### Output of `uname -a` or `ver`

Linux  5.15.146.1-microsoft-standard-WSL2 Ubuntu

### Output of `java -version`

OpenJDK Runtime Environment Temurin-21.0.3+9

### Quarkus version or git rev

3.11.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven 3.9.7

### Additional information

The sort is not part of the query

image

### PR DESCRIPTION
**Pull request by FroMage**
This allows us to not care about which parameters are set on the count query, since order by parameters are ignored by ORM. Which is not the case if we write our own count query.

Fixes https://github.com/quarkusio/quarkus/issues/40962

Supercedes #41019

### CODE REVIEW

**Comment by FroMage** [comment]
Finally, everything is released upstream I can finish this :)

File: extensions/panache/hibernate-orm-panache-common/runtime/src/main/java/io/quarkus/hibernate/orm/panache/common/runtime/CommonPanacheQueryImpl.java [hunk 1]
```diff
@@ -267,35 +273,27 @@ public void withHint(String hintName, Object value) {
 
     // Results
 
-    @SuppressWarnings("unchecked")
     public long count() {
         if (count == null) {
```
Comment (yrodiere) [inline extensions/panache/hibernate-orm-panache-common/runtime/src/main/java/io/quarkus/hibernate/orm/panache/common/runtime/CommonPanacheQueryImpl.java:277]: Unrelated to this PR, but caching the `count` could lead to really nasty surprises for users... not sure it's a great idea.

File: extensions/panache/panache-hibernate-common/runtime/src/main/java/io/quarkus/panache/hibernate/common/runtime/PanacheJpaUtil.java [hunk 2]
```diff
@@ -36,81 +29,6 @@ public class PanacheJpaUtil {
...
-            return visitor.result();
-        } catch (RequiresSubqueryException x) {
-            // no luck
-            SubQueryAliasParserVisitor visitor = new SubQueryAliasParserVisitor();
-            statement.accept(visitor);
-            String ret = visitor.result();
-            return "select count( * ) from ( " + ret + " )";
-        }
-    }
-
```
Comment (yrodiere) [inline extensions/panache/panache-hibernate-common/runtime/src/main/java/io/quarkus/panache/hibernate/common/runtime/PanacheJpaUtil.java:113]: Definitely an improvement to get rid of this :fearful:

**Review by yrodiere — APPROVED** [review]
LGTM, thanks!

File: extensions/panache/panache-hibernate-common/runtime/src/main/java/io/quarkus/panache/hibernate/common/runtime/PanacheJpaUtil.java (hunk 2 above)
Comment (FroMage) [reply extensions/panache/panache-hibernate-common/runtime/src/main/java/io/quarkus/panache/hibernate/common/runtime/PanacheJpaUtil.java:113]: Yeah, and now it's ORM's job to handle fast/slow cases :)

File: extensions/panache/hibernate-orm-panache-common/runtime/src/main/java/io/quarkus/hibernate/orm/panache/common/runtime/CommonPanacheQueryImpl.java (hunk 1 above)
Comment (FroMage) [reply extensions/panache/hibernate-orm-panache-common/runtime/src/main/java/io/quarkus/hibernate/orm/panache/common/runtime/CommonPanacheQueryImpl.java:277]: I often wondered about this. Funny that nobody reported issues with this. This is mostly useful because any calls to paging info (number of pages, etc) would cause extra calls to `count()` but I wonder if ORM caches that itself, perhaps I don't need to cache.

Comment (yrodiere) [reply extensions/panache/hibernate-orm-panache-common/runtime/src/main/java/io/quarkus/hibernate/orm/panache/common/runtime/CommonPanacheQueryImpl.java:277]: Hibernate ORM doesn't cache counts by default AFAICS. It can probably cache them, but that would be through the same mechanism as other queries (`Query#setCacheable`) -- and in the second-level cache, so would affect other sessions.

I suppose a first-level cache for query execution is an interesting ideas for some scenarios, such as query counts. Maybe we should open a feature request.

Comment (FroMage) [reply extensions/panache/hibernate-orm-panache-common/runtime/src/main/java/io/quarkus/hibernate/orm/panache/common/runtime/CommonPanacheQueryImpl.java:277]: Honestly, I don't know how important that is. Or how usable/realistic.
