### PR TITLE
Use builder image's objcopy when building with quarkus.native.container-build=true and quarkus.native.debug.enabled=true

### LINKED ISSUE #13754: Building native images with quarkus.native.container-build=true and quarkus.native.debug.enabled=true depends on host tools for splitting the debug info
**Describe the bug**
Currently, when using `quarkus.native.container-build=true` in combination with `quarkus.native.debug.enabled=true` Quarkus uses the container image to build the native image but relies on the host to provide the `objcopy` utility to split the debug info from the native image. Since the purpose of using a container image is to avoid having to install specific tooling on the host, this results in bad user experience (see #13517).

**Expected behavior**
Users shouldn't need to install anything special/extra on the host to build native images when using `quarkus.native.container-build=true`.

**Actual behavior**
Users need to make sure `objcopy` is available on the host (see #13517).

**To Reproduce**

On a system without `objcopy` installed run:
```
mvn io.quarkus:quarkus-maven-plugin:1.9.2.Final:create     -DprojectGroupId=org.acme     -DprojectArtifactId=getting-started     -DclassName="org.acme.getting.started.GreetingResource"     -Dpath="/hello"
cd getting-started
mvn dependency:sources
mvn clean package -Dquarkus.native.container-build=true -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel:20.2-java11 -Dnative -Dquarkus.native.debug.enabled=true
ls target/getting-started-1.0-SNAPSHOT-runner.debug  ## not present when using macOS for the docker based build
```
(Mostly copied from #13517)

**Configuration**
```properties
quarkus.native.container-build=true
quarkus.native.debug.enabled=true
```

**Additional context**
Possible approaches to solving this:

**1. Since the container image is currently defined to run `native-image` we could extend `native-image` to accept a flag that dumps the symbols in a separate `.debug` file.**

This benefits both GraalVM users and Quarkus users but it will need to go through upstream Graal and it will take some time to make it to Quarkus.

**2. We can use the container image to actually call `objcopy` in some "ugly" way.**

E.g.:
```
podman run --rm --user $(id -u):$(id -u) --userns=keep-id --entrypoint /bin/bash quay.io/quarkus/ubi-quarkus-mandrel:20.2-java11 -c "objcopy --version"
```
This seems the most straight forward approach and will be directly accessible.

**3. Change the container image to use as the entrypoint a wrapper script instead of `native-image`**

This will move the `objcopy` part out of Quarkus' source code for the case of `quarkus.native.container-build=true` but it will still require the logic to be present for native builds on the host system.

### LINKED ISSUE #13856: Native application gets Killed: 9 on macOS Big Sur with binutils on the path
I have a simple project created by maven extension as described in https://quarkus.io/guides/getting-started#bootstrapping-the-project. Running `mvn clean verify -Dnative` ends with `Failed to start native image, process has exited` on macOS Big Sur.
EDIT: the main problem is in `binutils`, see https://github.com/quarkusio/quarkus/issues/13856#issuecomment-755178876

I didn't have this problem on the previous macOS version 10.15 Catalina. I noticed this issue only on macOS Big Sur.

Using GraalVM 20.3.0
```
native-image --version
GraalVM Version 20.3.0 (Java Version 11.0.9+10-jvmci-20.3-b06)
```

Running just the native binary gives `Killed: 9`
```
target/getting-started-1.0.0-SNAPSHOT-runner
Killed: 9
```

I tried to remove some metadata from the generated native binary, but that didn't help
```
sudo xattr -d -r com.apple.quarantine  target/getting-started-1.0.0-SNAPSHOT-runner
target/getting-started-1.0.0-SNAPSHOT-runner
Killed: 9
```

Native image build went well:
```
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on GraalVM Version 20.3.0 (Java Version 11.0.9+10-jvmci-20.3-b06)
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] /Users/rsvoboda/.sdkman/candidates/java/20.3.0.r11-grl/bin/native-image -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=1 -J-Duser.language=en -J-Dfile.encoding=UTF-8 --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy\$BySpaceAndTime -H:+JNI -jar getting-started-1.0.0-SNAPSHOT-runner.jar -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:EnableURLProtocols=http --no-server -H:-UseServiceLoaderFeature -H:+StackTrace getting-started-1.0.0-SNAPSHOT-runner
[getting-started-1.0.0-SNAPSHOT-runner:1817]    classlist:   2,235.29 ms,  0.96 GB
[getting-started-1.0.0-SNAPSHOT-runner:1817]        (cap):   3,473.40 ms,  1.18 GB
[getting-started-1.0.0-SNAPSHOT-runner:1817]        setup:   5,182.05 ms,  1.18 GB
22:07:27,877 INFO  [org.jbo.threads] JBoss Threads version 3.1.1.Final
[getting-started-1.0.0-SNAPSHOT-runner:1817]     (clinit):     538.76 ms,  2.30 GB
[getting-started-1.0.0-SNAPSHOT-runner:1817]   (typeflow):  11,338.02 ms,  2.30 GB
[getting-started-1.0.0-SNAPSHOT-runner:1817]    (objects):  10,285.37 ms,  2.30 GB
[getting-started-1.0.0-SNAPSHOT-runner:1817]   (features):     479.63 ms,  2.30 GB
[getting-started-1.0.0-SNAPSHOT-runner:1817]     analysis:  23,489.96 ms,  2.30 GB
[getting-started-1.0.0-SNAPSHOT-runner:1817]     universe:   1,402.86 ms,  3.25 GB
[getting-started-1.0.0-SNAPSHOT-runner:1817]      (parse):   3,104.44 ms,  3.25 GB
[getting-started-1.0.0-SNAPSHOT-runner:1817]     (inline):   6,345.91 ms,  3.86 GB
[getting-started-1.0.0-SNAPSHOT-runner:1817]    (compile):  23,821.26 ms,  5.24 GB
[getting-started-1.0.0-SNAPSHOT-runner:1817]      compile:  35,269.13 ms,  5.24 GB
[getting-started-1.0.0-SNAPSHOT-runner:1817]        image:   4,033.51 ms,  5.25 GB
[getting-started-1.0.0-SNAPSHOT-runner:1817]        write:     986.77 ms,  5.25 GB
[getting-started-1.0.0-SNAPSHOT-runner:1817]      [total]:  72,858.51 ms,  5.25 GB
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 75495ms
```

### PR DESCRIPTION
**Pull request by zakkak**
Closes #13754 
Closes #13856

### CODE REVIEW

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java [hunk 1]
```diff
@@ -101,166 +101,60 @@ public NativeImageBuildItem build(NativeConfig nativeConfig, NativeImageSourceJa
...
-                command.add("-H:+TraceServiceLoaderFeature");
+            List<String> buildCommand = getBuildCommand(nativeConfig, nativeImageProperties,
+                    outputDir, runnerJarName, nativeImage, noPIE, isContainerBuild, graalVMVersion,
+                    executableName);
+            buildCommand = maybeRunInContainer(containerCommand, buildCommand);
+            if (isContainerBuild) {
+                log.info(String.join(" ", buildCommand).replace("$", "\\$"));
             } else {
-                command.add("-H:-UseServiceLoaderFeature");
+                log.info(String.join(" ", buildCommand));
```
Comment (jerboaa) [inline core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java:154]: Why is the `log.info()` conditionalized on `isContainerBuild`? Why `...replace("$", "\\$"))` only then? AFAIK, this is shell-escaping the GC policy in use which might be an inner class (`$` separation). I believe it's because `maybeRunInContainer` conditionally already replaces the `$`. It makes the code overly complicated to read.

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java [hunk 2]
```diff
@@ -269,17 +163,34 @@ public NativeImageBuildItem build(NativeConfig nativeConfig, NativeImageSourceJa
...
+                log.warn("objcopy executable not found in PATH. Debug symbols will not be separated from executable.");
+                log.warn("That will result in a larger native image with debug symbols embedded in it.");
+            } else {
+                assert !(isContainerBuild && containerCommand == null);
+                if (nativeConfig.debug.enabled) {
+                    objcopy(containerCommand, outputDir, "--only-keep-debug", executableName, symbols);
+                    objcopy(containerCommand, outputDir, String.format("--add-gnu-debuglink=%s", symbols), executableName);
+                }
+                // Strip debug symbols regardless, because the underlying JDK might contain them
+                objcopy(containerCommand, outputDir, "--strip-debug", executableName);
```
Comment (jerboaa) [inline core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java:184]: Wouldn't this spin up a container 3 times? Ideally, we'd stitch them together so that we can get away with a one time container invocation. I.e. `podman run ... --entrypoint=/bin/bash <container> -c 'objcopy --only-keep-debug ... ; objcopy --add-gnu-debuglink=....; objcopy --strip-debug ...` or `podman run ... --entrypoint=/bin/bash <container> -c 'objcopy --strip-debug ...` depending on the `-g` option.

**Review by jerboaa — COMMENTED** [review]
A couple of comments...

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java (hunk 1 above)
Comment (zakkak) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java:154]: Correct, and it indeed complicates the code. I wanted the log output to be copy-pasteable so. Suggestions on how to improve this are welcome! Do you think keeping the `log.info` outside of the if and only do the replace in there would make things better?

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java (hunk 2 above)
Comment (zakkak) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java:184]: It will, but that's fairly fast in comparison to the native-image build step. Keeping it this way we don't have to have two different code paths for container and host builds, thus keeping it simple and more readable.

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java (hunk 1 above)
Comment (jerboaa) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java:154]: Perhaps don't do the `replace()` call in `maybeRunInContainer` and do the escaping of `$` only when you need it.

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java (hunk 2 above)
Comment (jerboaa) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java:184]: I haven't tested this myself, but apparently running containers on non-Linux isn't as quick. Perhaps mac and windows use-cases with building with the container should be tested.

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java (hunk 1 above)
Comment (zakkak) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java:154]: This means that I will need to check before the invocation if this is a container or not and do the replace. It feels like doing it inside maybeRunInContainer is better. What if I move the log in there?

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java (hunk 2 above)
Comment (zakkak) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java:184]: AFAIK Mac is almost as fast, and windows docker using WSL2 as the backend should also be pretty fast. I can do some testing on Windows, but unfortunately not on Mac.

Comment (jerboaa) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java:184]: This maybe an optimization to do as a later step (once we know this actually is a problem?)

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java (hunk 1 above)
Comment (jerboaa) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java:154]: sounds good.

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java (hunk 2 above)
Comment (zakkak) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java:184]: FTR: I tested this on two laptops with similar specs.
I tested the "combined" (single docker container for all 3 processes) vs the "split" (1 container per process) approach and the results were:

| | Windows | Linux |
| -- | -- | -- |
| Combined | ~16s | ~0.8s |
| Split | 3.5 + 13 + 6.5 = ~23s | 0.5 + 0.5 + 0.6 = ~1.1s |

Although the benefit of using the "combined" approach is pretty clear, the overhead of the "split" approach (~7s) is still relatively low given that the image build took ~260s.

**Comment by zakkak** [comment]
@gsmet can you please review?

**Comment by gsmet** [comment]
@zakkak can you fix the conflict?

Frankly, I can't backport it as is. We can't refactor everything in a PR we want to backport...

**Comment by zakkak** [comment]
> @zakkak can you fix the conflict?

Done

> Frankly, I can't backport it as is. We can't refactor everything in a PR we want to backport...

I understand. I should have actually added this PR to 1.11.0.Final in the first place.
How would you like to proceed with this since we would like it in 1.11.x? Is it OK if I create a new PR with branch `1.11` as the base?
Unfortunately the refactoring is necessary to make this change in a sensible way, otherwise we would have to duplicate a lot of code and some processing.

**Comment by gsmet** [comment]
As I said I'm uncomfortable backporting something that rewrites a whole class. So either we find a finer-grained approach or we don't backport it. The current approach is not safe for a backport. I don't want to break something else to fix an issue.

Now if someone really wants this, they will have to review this VERY closely to be sure everything is safe.

/cc @maxandersen @tqvarnst

**Comment by rsvoboda** [comment]
@zakkak can you please rebase?

**Comment by zakkak** [comment]
> @zakkak can you please rebase?

@rsvoboda this is not worth rebasing before https://github.com/quarkusio/quarkus/pull/14635 gets merged, unless it's a real blocker for you.

**Comment by geoand** [comment]
This need a rebase

**Comment by zakkak** [comment]
> This need a rebase but we need a decision on
> 
>     1. Whether or needs to be backported or not (based on what @gsmet mentioned)

We have concluded that this does not need to be backported.

>     2. If we want this or #15233 to go in first

I would prefer #15233 to go in first.

**Comment by geoand** [comment]
OK, then I will take #15233 out of draft so it can get a proper review

**Comment by zakkak** [comment]
> OK, then I will take #15233 out of draft so it can get a proper review.
> 
> Furthermore, I'll add a test for it

Can we please make sure #14635 goes in first, then #15233 and finally #13963 (this PR)?

**Comment by geoand** [comment]
Ouch... I just saw #14635... Rebasing my PR onto that one won't be fun :(

**Comment by zakkak** [comment]
> Ouch... I just saw #14635... Rebasing my PR onto that one won't be fun :(

I feel you, if it eases your pain it will be more or less the same for this PR ;)

**Comment by geoand** [comment]
> > Ouch... I just saw #14635... Rebasing my PR onto that one won't be fun :(
> 
> I feel you, if it eases your pain it will be more or less the same for this PR ;)

Yeah, we are in the same boat :)

**Comment by geoand** [comment]
Turned out to be easier than I thought :)

**Comment by zakkak** [comment]
> Turned out to be easier than I thought :)

I wish I could say the same :)

This is now ready for review. I tested it locally with all three configurations and GraalVM CE 21.0:
1. Host build with `-Dquarkus.native.debug.enabled=true -Dquarkus.native.graalvm-home=/opt/jvms/graalvm-ce-java11-21.0.0`
2. Builder image with `-Dquarkus.native.debug.enabled=true`
3. Remote buidler image with `-Dquarkus.native.remote-container-build=true -Dquarkus.native.debug.enabled=true`

@jonathan-meier FYI (It would also be great if you could give this a spin on your "remote" docker setup)

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildRemoteContainerRunner.java [hunk 3]
```diff
@@ -13,6 +15,7 @@
 public class NativeImageBuildRemoteContainerRunner extends NativeImageBuildContainerRunner {
 
     private static final Logger log = Logger.getLogger(NativeImageBuildRemoteContainerRunner.class);
+    private static final String CONTAINER_BUILD_VOLUME_NAME = "quarkus-native-builder-image-project-volume";
```
Comment (zakkak) [inline core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildRemoteContainerRunner.java:18]: Ideally I would prefer a dynamically generated unique volume name, but I am not sure it's worth the effort.
We could also do something like `fixed-name-YYYY-MM-DD-HHMM` to avoid potential conflicts with existing volumes.
WDYT?

**Comment by jonathan-meier** [comment]
Works like a charm! I tested various combinations of local/remote builds with debug enabled/disabled both natively on Windows and inside WSL.

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildRemoteContainerRunner.java (hunk 3 above)
Comment (jonathan-meier) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildRemoteContainerRunner.java:18]: It's straightforward to let docker generate the unique volume id, I quickly tested it locally:
```
final String[] createVolumeCommand = new String[] { containerRuntime.getExecutableName(), "volume", "create" };
volumeId = runCommandAndReadOutput(createVolumeCommand, "Failed to create temp volume.");
```
Using this as a first step in `preBuild` and replacing all `CONTAINER_BUILD_VOLUME_NAME` with `volumeId`.

Comment (zakkak) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildRemoteContainerRunner.java:18]: Unfortunately it's not that simple. If you manually create the volume before starting the container, the volume (when mount) is owned by `root:root` and `native-image` fails to write to it in subsequent steps.

## Creating the volume explicitly
```
$ podman volume create test-volume                         
test-volume
$ podman create --name temp -v test-volume:/project quay.io/quarkus/ubi-quarkus-native-image:21.0.0-java11                         
bfa2406d5fa0a003af99c91f077ed989006eb2441004135773429c425f9ce997
$ podman run --rm --entrypoint /bin/bash -it -v test-volume:/project quay.io/quarkus/ubi-quarkus-native-image:21.0.0-java11 -c "ls -la"
total 0
drwxr-xr-x.  2 root root 6 Mar  3 11:40 .
drwxr-xr-x. 19 root root 6 Mar  3 11:41 ..
```

## Creating the volume implicitly
```
$ podman create --name temp -v test-volume:/project quay.io/quarkus/ubi-quarkus-native-image:21.0.0-java11
e30ffb76aa320448a3e645d7030c4dcf76b0efb83b68e3bc58a2e655c683d1de
$ podman run --rm --entrypoint /bin/bash -it -v test-volume:/project quay.io/quarkus/ubi-quarkus-native-image:21.0.0-java11 -c "ls -la"
total 0
drwxr-xr-x.  2 quarkus quarkus 6 Mar  3 11:42 .
drwxr-xr-x. 19 root    root    6 Mar  3 11:42 ..
```

I am not a containers expert though so I'll be happy to be corrected :)

**Comment by zakkak** [comment]
> Works like a charm! I tested various combinations of local/remote builds with debug enabled/disabled both natively on Windows and inside WSL.

Thank you @jonathan-meier, I really appreciate it :)

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildRemoteContainerRunner.java (hunk 3 above)
Comment (jonathan-meier) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildRemoteContainerRunner.java:18]: Interesting! I checked the following:

- docker 19.03.13 on Ubuntu 20.10
- docker 20.10.2 on Ubuntu 20.10 in WSL
- podman 2.0.6 on Ubuntu 20.10
- podman 1.6.4 on CentOS 7.9
- podman 3.0.1 on CentOS 7.9

in all but the last case, the `/project` folder was owned by the `quarkus` user also when creating the volume _explicitly_. So something seems to have changed for podman 3. I'm guessing you're running on podman 3 as well?

Comment (zakkak) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildRemoteContainerRunner.java:18]: Indeed I am using podman 3.0.1 on Fedora 33.

Thanks for the additional info @jonathan-meier, I created https://github.com/containers/podman/issues/9608.

**Comment by gsmet** [comment]
@zakkak @jonathan-meier I rebased this PR and also added an additional commit to fix (again) the confusion between native image name and executable name. Could you both have a look?

**Comment by zakkak** [comment]
Thanks @gsmet. It looks like the issue (which appears only in podman 3.0.x) I am working around in this PR (see https://github.com/quarkusio/quarkus/pull/13963#discussion_r585610810) is fixed in podman 3.1.0 (which was released 2 days ago) so I was thinking about waiting for it to land in fedora and rework the PR to avoid the work-around. WDYT?

**Comment by gsmet** [comment]
If the workaround doesn't break Podman 3.1, I would get it in anyway. People don't always keep things updated.

**Comment by zakkak** [comment]
> If the workaround doesn't break Podman 3.1, I would get it in anyway. People don't always keep things updated.

OK, I added a comment to explain that we follow this approach due to the Podman 3.0.x issue. It looks good to me (at least the linux part). It would be nice if someone could confirm that everything works as expected on windows as well.

**Comment by jonathan-meier** [comment]
Looks good to me too! I again tested various combinations of containerized local/remote docker builds with debug enabled/disabled both natively on Windows and inside WSL.

Please note that I did *not* test direct local builds on Windows producing a Windows binary (i.e. without docker, as I don't have GraalVM installed on Windows). I did *not* do any *podman* tests either.

**Comment by zakkak** [comment]
@gsmet I rebased this (cleanly). I think it's good to go (after the CI completes).

**Comment by zakkak** [comment]
CI looks good @gsmet @geoand can you please merge?

**Review by gsmet — APPROVED** [review]
