### PR TITLE
Only add json content-type when necessary

### LINKED ISSUE #14045: resteasy-reactive: When using own Content-Type for @Produces then quarkus will set 'application/json' as Content-Type header
**Describe the bug**
When. using `@Produces` with non-standard content type with resteasy-reactive  will result in 'application/json' being set as Content-Type header instead of the requested type.

**Expected behavior**
It should set the requested content type that was requested in the Accept header.

**Actual behavior**
'application/json' is always set.

**To Reproduce**

1. Checkout https://github.com/quarkusio/quarkus-quickstarts/tree/development/hibernate-reactive-quickstart
3. Add `@Produces("application/vnd.quarkus.fruit-v1+json")` to POST method
4. Call `curl -H "Accept: application/vnd.quarkus.fruit-v1+json"  http://localhost:8080/fruits -d'{"name": "apple"}' -v`

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #14045

### CODE REVIEW

**Comment by geoand** [comment]
Also one for `Beta2` @gsmet

**Review by gsmet — APPROVED** [review]

File: independent-projects/resteasy-reactive/server/vertx/src/main/java/org/jboss/resteasy/reactive/server/vertx/providers/serialisers/json/JsonMessageBodyWriterUtil.java [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+                }
+            }
+        }
+        if (isNotJson(currentContentType)) {
+            context.serverResponse().setResponseHeader(HttpHeaders.CONTENT_TYPE, MediaType.APPLICATION_JSON);
+        }
+    }
+
+    private static boolean isNotJson(Object contentType) {
+        return (contentType == null) || !contentType.toString().contains("json");
```
Comment (FroMage) [inline independent-projects/resteasy-reactive/server/vertx/src/main/java/org/jboss/resteasy/reactive/server/vertx/providers/serialisers/json/JsonMessageBodyWriterUtil.java:41]: Pretty sure that's not how media type mapping works, as it will even match `application/stef-hates-json` which is not JSON at all ;)

Comment (geoand) [reply independent-projects/resteasy-reactive/server/vertx/src/main/java/org/jboss/resteasy/reactive/server/vertx/providers/serialisers/json/JsonMessageBodyWriterUtil.java:41]: Fair point. When someone comes to us with such an example, you can tell me: `I told you so` :)

Comment (FroMage) [reply independent-projects/resteasy-reactive/server/vertx/src/main/java/org/jboss/resteasy/reactive/server/vertx/providers/serialisers/json/JsonMessageBodyWriterUtil.java:41]: Sure, but just remember that media type matching doesn't work like this, we don't want to oversimplify stuff everywhere ;)

Comment (geoand) [reply independent-projects/resteasy-reactive/server/vertx/src/main/java/org/jboss/resteasy/reactive/server/vertx/providers/serialisers/json/JsonMessageBodyWriterUtil.java:41]: Definitely.

Made a mental note, so when this comes up, I'll know where to look :)
