### PR TITLE
Scheduler - scheduled methods are not inherited

### LINKED ISSUE #24212: @Scheduled method invoked both on original bean and @Alternative bean
### Describe the bug

If `@Scheduled` is applied to a function and an `@Alternative` subclass is created for the bean containing the annotated method, the method is invoked twice by the scheduler, once for each bean. This means that when the alternative bean is being used the scheduled method is invoked twice, which is unexpected.

A reproducer is attached with the minimal changes necessary to show this, applied on the scheduler-quickstart project.

Our use case is we are creating a bean like `CounterBean` in the attached example that lives inside a library.  This `CounterBean` could be subclassed and customized by providing an alternative like `AlternativeCounterBean` in different projects that use the library, and if that is done at the moment we find multiple invocations of the scheduled method, one immediately after the other.

### Expected behavior

Only one invocation of the `@Scheduled` method should be performed on the alternative bean; the original bean's invocation should not be performed.  In the given example, only `AlternativeCounterBean#increment()` should be invoked by the scheduler.

### Actual behavior

As can be seen in the log output, both the `CounterBean#increment()` and the `AlternativeCounterBean#increment()` are invoked by the scheduler.

> [INFO] Running org.acme.scheduler.CountResourceTest
2022-03-09 12:40:11,111 INFO  [org.jbo.threads] (main) JBoss Threads version 3.4.2.Final
2022-03-09 12:40:12,757 INFO  [io.quarkus] (main) Quarkus 2.7.3.Final on JVM started in 2.108s. Listening on: http://localhost:8081
2022-03-09 12:40:12,758 INFO  [io.quarkus] (main) Profile test activated. 
2022-03-09 12:40:12,758 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy, scheduler, smallrye-context-propagation, vertx]
2022-03-09 12:40:13,011 INFO  [org.acm.sch.CounterBean] (executor-thread-1) Invoked from: org.acme.scheduler.CounterBean
2022-03-09 12:40:13,011 INFO  [org.acm.sch.CounterBean] (executor-thread-0) Invoked from: org.acme.scheduler.AlternativeCounterBean
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 6.313 s - in org.acme.scheduler.CountResourceTest
2022-03-09 12:40:13,968 INFO  [io.quarkus] (main) Quarkus stopped in 0.048s

### How to Reproduce?

[scheduler-quickstart-reproducer.zip](https://github.com/quarkusio/quarkus/files/8216991/scheduler-quickstart-reproducer.zip)

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19042.1526]

### Output of `java -version`

openjdk version "11.0.9.1" 2020-11-04 LTS OpenJDK Runtime Environment Corretto-11.0.9.12.1 (build 11.0.9.1+12-LTS) OpenJDK 64-Bit Server VM Corretto-11.0.9.12.1 (build 11.0.9.1+12-LTS, mixed mode)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.7.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537) Maven home: C:\ProgramData\Chocolatey\lib\maven\apache-maven-3.8.4 Java version: 11.0.9.1, vendor: Amazon.com Inc., runtime: C:\Program Files\Amazon Corretto\jdk11.0.9_12 Default locale: en_US, platform encoding: Cp1252 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mkouba**
- this is a breaking change
- however, the current behavior is undocumented and inconsistent; e.g.
if Scheduled#identity() is used then the build always fails
- also the scope annotation is not added automatically to a subclass of a class that
declares a Scheduled annotation, i.e. the class would be ignored and would
result in runtime error
- resolves #24212

### CODE REVIEW

**Comment by mkouba** [comment]
I'm going to update the migration guide once this PR is merged..

File: extensions/scheduler/deployment/src/test/java/io/quarkus/scheduler/test/inheritance/ScheduledMethodNotInheritedTest.java [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+
+import javax.inject.Singleton;
+
+import org.junit.jupiter.api.Test;
+import org.junit.jupiter.api.extension.RegisterExtension;
+
+import io.quarkus.scheduler.Scheduled;
+import io.quarkus.test.QuarkusUnitTest;
+
+public class ScheduledMethodNotInheritedTest {
```
Comment (machi1990) [inline extensions/scheduler/deployment/src/test/java/io/quarkus/scheduler/test/inheritance/ScheduledMethodNotInheritedTest.java:18]: Thanks for adding the test along side the change.

**Review by machi1990 — APPROVED** [review]
lgtm

Thanks

File: extensions/scheduler/deployment/src/test/java/io/quarkus/scheduler/test/inheritance/ScheduledMethodNotInheritedTest.java (hunk 1 above)
Comment (mkouba) [reply extensions/scheduler/deployment/src/test/java/io/quarkus/scheduler/test/inheritance/ScheduledMethodNotInheritedTest.java:18]: Uf, I forgot to update the docs ;-)

Comment (mkouba) [reply extensions/scheduler/deployment/src/test/java/io/quarkus/scheduler/test/inheritance/ScheduledMethodNotInheritedTest.java:18]: Done.

**Comment by mkouba** [comment]
> I'm going to update the migration guide once this PR is merged..

Done: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.8#scheduler
