### PR TITLE
Verify build tool file presence based on all build tool possible values

### LINKED ISSUE #19049: CLI "quarkus dev" command is not working with gradle kotlin
### Describe the bug

quarkus dev command is not working with gradle kotlin

### Expected behavior

should work

### Actual behavior

```
[ERROR] ❗  Unable to launch project in dev mode: Was not able to find a build file in: /Users/ia3andy/Downloads/code-with-quarkus
````

### How to Reproduce?

1. Generate some project with code.quarkus using Gradle Kotlin: https://stage.code.quarkus.io/?b=GRADLE_KOTLIN_DSL&e=resteasy&e=resteasy-jackson&e=hibernate-validator
2. Copy `quarkus dev` command in the popup
3. Unzip and cd
4.
```shell
$ quarkus dev
[ERROR] ❗  Unable to launch project in dev mode: Was not able to find a build file in: /Users/ia3andy/Downloads/code-with-quarkus
```

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by glefloch**
This make sure build file is present based on the buildtool file list.
close #19049

### CODE REVIEW

File: devtools/cli/src/main/java/io/quarkus/cli/build/GradleRunner.java [hunk 1]
```diff
@@ -235,9 +235,12 @@ void setGradleProperties(ArrayDeque<String> args, boolean batchMode) {
...
-        File buildFile = projectRoot.resolve("build.gradle").toFile();
-        if (!buildFile.isFile()) {
-            throw new IllegalStateException("Was not able to find a build file in: " + projectRoot);
+        for (String buildFileName : buildTool.getBuildFiles()) {
+            File buildFile = projectRoot.resolve(buildFileName).toFile();
+            if (buildFile.exists()) {
+                return;
+            }
         }
+        throw new IllegalStateException("Was not able to find a build file in: " + projectRoot);
```
Comment (ia3andy) [inline devtools/cli/src/main/java/io/quarkus/cli/build/GradleRunner.java:244]: Maybe we could show the list of required build files here?

**Review by ia3andy — APPROVED** [review]
LGTM, just added a suggestion to improve the error

File: devtools/cli/src/main/java/io/quarkus/cli/build/GradleRunner.java (hunk 1 above)
Comment (glefloch) [reply devtools/cli/src/main/java/io/quarkus/cli/build/GradleRunner.java]: Yes this is a good idea, I pushed an update.
