### PR TITLE
OpenTelemetry Jaeger Substitutions - Remove shaded netty references

### LINKED ISSUE #22275: Native build error when using `quarkus-opentelemetry-exporter-jaeger`
### Describe the bug

Native build fails when using
```
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-opentelemetry-exporter-jaeger</artifactId>
    </dependency>
```

### Expected behavior

Successful build.

### Actual behavior

```
[opentelemetry-jaeger-reproducer-1.0.0-SNAPSHOT-runner:710862]   (typeflow):  19,343.80 ms,  5.21 GB
[opentelemetry-jaeger-reproducer-1.0.0-SNAPSHOT-runner:710862]    (objects):  22,479.84 ms,  5.21 GB
[opentelemetry-jaeger-reproducer-1.0.0-SNAPSHOT-runner:710862]   (features):   1,129.85 ms,  5.21 GB
[opentelemetry-jaeger-reproducer-1.0.0-SNAPSHOT-runner:710862]     analysis:  45,383.01 ms,  5.21 GB
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Detailed message:
Trace: 
	at parsing io.opentelemetry.exporter.otlp.internal.grpc.ManagedChannelUtil.setTrustedCertificatesPem(ManagedChannelUtil.java:73)
Call path from entry point to io.opentelemetry.exporter.otlp.internal.grpc.ManagedChannelUtil.setTrustedCertificatesPem(ManagedChannelBuilder, byte[]): 
	at io.opentelemetry.exporter.otlp.internal.grpc.ManagedChannelUtil.setTrustedCertificatesPem(ManagedChannelUtil.java:59)
	at io.opentelemetry.exporter.otlp.internal.grpc.DefaultGrpcExporterBuilder.build(DefaultGrpcExporterBuilder.java:145)
	at io.opentelemetry.exporter.jaeger.JaegerGrpcSpanExporterBuilder.build(JaegerGrpcSpanExporterBuilder.java:92)
	at io.quarkus.opentelemetry.exporter.jaeger.runtime.JaegerRecorder.installBatchSpanProcessorForJaeger(JaegerRecorder.java:29)
	at io.quarkus.deployment.steps.JaegerExporterProcessor$installBatchSpanProcessorForJaeger1237208624.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.JaegerExporterProcessor$installBatchSpanProcessorForJaeger1237208624.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:104)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:146)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:182)
	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

```

### How to Reproduce?

```
mvn io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:create -DplatformGroupId=io.quarkus -DplatformVersion=999-SNAPSHOT -DprojectArtifactId=opentelemetry-jaeger-reproducer -Dextensions=opentelemetry-exporter-jaeger
cd ./opentelemetry-jaeger-reproducer/
mvn clean package -Dnative
```

### Output of `uname -a` or `ver`

Linux 5.15.6-200.fc35.x86_64

### Output of `java -version`

openjdk version "11.0.11" 2021-04-20 OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9) OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

### GraalVM version (if different from Java)

GraalVM 21.2.0 Java 16 CE (Java Version 16.0.2+7-jvmci-21.2-b08)

### Quarkus version or git rev

999-SNAPSHOT (2.6 - main)

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.3 (ff8e977a158738155dc465c6a97ffaf31982d739)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by radcortez**
- Fixes #22275

### CODE REVIEW

File: extensions/opentelemetry/opentelemetry-exporter-jaeger/runtime/src/main/java/io/quarkus/opentelemetry/exporter/jaeger/runtime/JaegerSubstitutions.java [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+
+import com.oracle.svm.core.annotate.Substitute;
+import com.oracle.svm.core.annotate.TargetClass;
+
+import io.grpc.ManagedChannelBuilder;
+import io.grpc.netty.GrpcSslContexts;
+import io.grpc.netty.NettyChannelBuilder;
+import io.opentelemetry.exporter.otlp.internal.grpc.ManagedChannelUtil;
+
+final class JaegerSubstitutions {
```
Comment (gsmet) [inline extensions/opentelemetry/opentelemetry-exporter-jaeger/runtime/src/main/java/io/quarkus/opentelemetry/exporter/jaeger/runtime/JaegerSubstitutions.java:16]: Any change you could add a comment with the purpose of this substitution?

Comment (radcortez) [reply extensions/opentelemetry/opentelemetry-exporter-jaeger/runtime/src/main/java/io/quarkus/opentelemetry/exporter/jaeger/runtime/JaegerSubstitutions.java:16]: Sure.

**Review by gsmet — APPROVED** [review]
Thanks!
