### PR TITLE
Initialize datasources at startup again

### LINKED ISSUE #35238: Narayana automatic recovery of JDBC XA resources only works after datasources was initialized manually
### Describe the bug

If I want periodic recovery module to recover my failed transaction stored in JDBC object store, I need first to have datasources initialized (e.g. when I sent request or with startevent I use datasources).

### Expected behavior

When app starts, failed transactions recover.

### Actual behavior

Exception and no recovery:

```
2023-08-06 23:56:26,715 WARN  [com.arj.ats.jta] (Periodic Recovery) ARJUNA016037: Could not find new XAResource to use for recovering non-serializable XAResource XAResourceRecord < resource:null, txid:< formatId=131077, gtrid_length=46, bqual_length=36, tx_uid=0:ffff0a0000b9:af1b:64d01657:11, node_name=quarkus-quickstart, branch_uid=0:ffff0a0000b9:af1b:64d01657:17, subordinatenodename=null, eis_name=0 >, heuristic: TwoPhaseOutcome.FINISH_OK com.arjuna.ats.internal.jta.resources.arjunacore.XAResourceRecord@55ea0fec >
2023-08-06 23:56:26,719 WARN  [com.arj.ats.jta] (Periodic Recovery) ARJUNA016038: No XAResource to recover < formatId=131077, gtrid_length=46, bqual_length=36, tx_uid=0:ffff0a0000b9:af1b:64d01657:11, node_name=quarkus-quickstart, branch_uid=0:ffff0a0000b9:af1b:64d01657:13, subordinatenodename=null, eis_name=0 >
```

Recovery doesn't work till I use datasources myself. @zhfeng explained to me here https://github.com/quarkusio/quarkus-quickstarts/pull/1311#issuecomment-1667031126 that there was changes in Agroal regarding ds initialization https://github.com/quarkusio/quarkus/blob/main/extensions/agroal/runtime/src/main/java/io/quarkus/agroal/runtime/AgroalRecorder.java#L28-L30.

I've tested Zheng suggestion with following code that did a trick (I do not propose use such thing! it's just for context):
https://github.com/quarkusio/quarkus-quickstarts/pull/1311#issuecomment-1667606419

### How to Reproduce?

Reproducer:

follow readme added here https://github.com/quarkusio/quarkus-quickstarts/pull/1311. There are steps that you need to follow, you will see that if you don't do `curl -v localhost:8080/transaction-logs/annotation-way`, transaction is never recovered and an exception is repeatedly logged.

### Output of `uname -a` or `ver`

Fedora

### Output of `java -version`

OpenJDK Runtime Environment Temurin-17.0.7+7

### GraalVM version (if different from Java)

22.3

### Quarkus version or git rev

999-SNAPSHOT

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.3

### Additional information

Related to https://github.com/quarkusio/quarkus/pull/34545 ? Didn't check (on PTO).

### PR DESCRIPTION
**Pull request by gsmet**
Prior to
https://github.com/quarkusio/quarkus/pull/34545/commits/3f9de0c8af37a6bf9a869af117f95b5ae206dd28, datasources were initialized at startup and this is a property we want to keep.
ArC will now take care of the initialization.

Fixes #35238

### CODE REVIEW

File: extensions/agroal/deployment/src/main/java/io/quarkus/agroal/deployment/AgroalProcessor.java [hunk 1]
```diff
@@ -233,11 +234,15 @@ void generateDataSourceSupportBean(AgroalRecorder recorder,
...
 
-        // make a DataSourceProducer bean
+        // make a DataSources bean
         additionalBeans.produce(AdditionalBeanBuildItem.builder().addBeanClasses(DataSources.class).setUnremovable()
                 .setDefaultScope(DotNames.SINGLETON).build());
         // add the @DataSource class otherwise it won't be registered as a qualifier
         additionalBeans.produce(AdditionalBeanBuildItem.builder().addBeanClass(DataSource.class).build());
+        // make source datasources are initialized at startup
+        additionalBeans.produce(AdditionalBeanBuildItem.builder().addBeanClasses(AgroalDataSourcesInitializer.class)
+                .setUnremovable()
```
Comment (mkouba) [inline extensions/agroal/deployment/src/main/java/io/quarkus/agroal/deployment/AgroalProcessor.java:244]: This is not necessary - a bean with an observer method is never removed.

File: extensions/agroal/deployment/src/main/java/io/quarkus/agroal/deployment/AgroalProcessor.java [hunk 2]
```diff
@@ -233,11 +234,15 @@ void generateDataSourceSupportBean(AgroalRecorder recorder,
...
+                .setDefaultScope(DotNames.SINGLETON).build());
```
Comment (mkouba) [inline extensions/agroal/deployment/src/main/java/io/quarkus/agroal/deployment/AgroalProcessor.java:245]: Why this default scope? I'd keep `@Dependent` (class with no scope but an observer method) so that the bean is destroyed right after the notification.

**Comment by gsmet** [comment]
@mkouba I think I addressed your concerns.

**Review by michalvavrik — APPROVED** [review]

**Review by mkouba — APPROVED** [review]

File: extensions/agroal/deployment/src/main/java/io/quarkus/agroal/deployment/AgroalProcessor.java [hunk 3]
```diff
@@ -233,11 +234,13 @@ void generateDataSourceSupportBean(AgroalRecorder recorder,
             return;
         }
 
-        // make a DataSourceProducer bean
+        // make a DataSources bean
         additionalBeans.produce(AdditionalBeanBuildItem.builder().addBeanClasses(DataSources.class).setUnremovable()
                 .setDefaultScope(DotNames.SINGLETON).build());
         // add the @DataSource class otherwise it won't be registered as a qualifier
         additionalBeans.produce(AdditionalBeanBuildItem.builder().addBeanClass(DataSource.class).build());
+        // make source datasources are initialized at startup
```
Comment (geoand) [inline extensions/agroal/deployment/src/main/java/io/quarkus/agroal/deployment/AgroalProcessor.java:242]: Too late now, but I am pretty sure you meant to say `make sure`

Comment (gsmet) [reply extensions/agroal/deployment/src/main/java/io/quarkus/agroal/deployment/AgroalProcessor.java:242]: Raaaah. Fixed in https://github.com/quarkusio/quarkus/pull/35273 .
