### PR TITLE
Unify how Arc attemps to load classes from Index, add logging for missing classes

### LINKED ISSUE #4080: Arc - add better handling of non-indexed classes we encounter
Currently, Arc in many places tries to search a class from index and while we check for `null`, we don't really log anything and we mostly silently proceed. This can lead to some puzzling user output, as was pointed out on another PR https://github.com/quarkusio/quarkus/pull/4060#discussion_r325540679.

The likelihood of this happening is small as `io.quarkus.arc.processor.BeanArchives.IndexWrapper` tries to index additional classes, so in most cases, all classes should be there.
It would still be worth it to add a single util class which would be used throughout Arc - this class would then attempt loading from Jandex index. Should it fail, we can choose to either log something, or straight up fail with an exception.

### PR DESCRIPTION
**Pull request by manovotn**
…sing classes.

Fixes #4080 

@mkouba looking at what we had in Arc now, we sometimes blow up, sometimes silently continue and at other times we logged something. So in the end I added a util class that does _info_ logging but still allows to return `null` as in some cases blowing up might be a tad bit too harsh?

### CODE REVIEW

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/IndexClassLookupUtils.java [hunk 1]
```diff
@@ -0,0 +1,41 @@
+package io.quarkus.arc.processor;
+
+import org.jboss.jandex.ClassInfo;
+import org.jboss.jandex.DotName;
+import org.jboss.jandex.IndexView;
+import org.jboss.logging.Logger;
+
+public class IndexClassLookupUtils {
```
Comment (mkouba) [inline independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/IndexClassLookupUtils.java]: This class should be probably package-private and final.

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/IndexClassLookupUtils.java [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+
+    private static final Logger LOGGER = Logger.getLogger(IndexClassLookupUtils.class);
+
+    private IndexClassLookupUtils() {
+    }
+
+    public static ClassInfo getClassByName(IndexView index, DotName dotName) {
```
Comment (mkouba) [inline independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/IndexClassLookupUtils.java]: Package-private as well...

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanDeployment.java [hunk 3]
```diff
@@ -123,12 +125,9 @@
         this.interceptorBindings = findInterceptorBindings(index);
         for (InterceptorBindingRegistrar registrar : bindingRegistrars) {
             for (DotName dotName : registrar.registerAdditionalBindings()) {
-                ClassInfo classInfo = index.getClassByName(dotName);
+                ClassInfo classInfo = getClassByName(index, dotName);
```
Comment (mkouba) [inline independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanDeployment.java]: Shouldn't we use the logging variant here? I mean we threw runtime exception before and now silently ignore the problem?

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/IndexClassLookupUtils.java [hunk 4]
```diff
@@ -0,0 +1,41 @@
...
+        if (dotName == null) {
+            throw new IllegalArgumentException("Cannot lookup class, provided DotName was null.");
+        }
+        if (index == null) {
+            throw new IllegalArgumentException("Cannot lookup class, provided Jandex Index was null.");
+        }
+        ClassInfo info = index.getClassByName(dotName);
+        if (info == null && withLogging) {
+            // class not in index, log warning as this may cause the application to blow up or behave weirdly
+            LOGGER.info("Class for name: " + dotName + " was not found in Jandex index. Please ensure the class " +
```
Comment (mkouba) [inline independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/IndexClassLookupUtils.java]: Shouldn't we use the WARN level instead?

**Review by mkouba — CHANGES_REQUESTED** [review]

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/IndexClassLookupUtils.java (hunk 4 above)
Comment (manovotn) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/IndexClassLookupUtils.java]: That's what I had there originally, but since some pieces of code just choose to "silently" proceed now, WARN felt a bit too strong. But  I wouldn't mind...

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanDeployment.java (hunk 3 above)
Comment (manovotn) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanDeployment.java]: This is the logging variant.

But yes, we threw exception before, but since we will now have logging, in this case I reconsidered and thought that should be enough instead of hard fail. WDYT?

Comment (mkouba) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanDeployment.java]: Ah sorry, these Fridays...

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/IndexClassLookupUtils.java (hunk 4 above)
Comment (mkouba) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/IndexClassLookupUtils.java]: Hm, that's a tricky question. Let's keep INFO for now...

Comment (manovotn) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/IndexClassLookupUtils.java]: I mean, even `INFO` was noticeable enough for me to fix all those `arc/processor` tests ;)

Comment (manovotn) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/IndexClassLookupUtils.java]: I mean, even INFO made me notice and fix those `arc/processor` tests which were having unindexed classes ;-)

**Comment by manovotn** [comment]
@mkouba addressed all your comments

**Review by mkouba — APPROVED** [review]

**Comment by mkouba** [comment]
Looks good now. Let's wait for CI ;-).
