### PR TITLE
Delegate striping of debug symbols to GraalVM/Mandrel when >23.0

### LINKED ISSUE #138: debugSymbolsQuarkus fails with latest GraalVM master
There are failures in GDB flows on the latest Ubuntu GHA runners, e.g.:

```
2023-02-14T03:27:08.3302784Z [ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 520.46 s <<< FAILURE! - in org.graalvm.tests.integration.DebugSymbolsTest
2023-02-14T03:27:08.3307172Z [ERROR] debugSymbolsQuarkus{TestInfo}  Time elapsed: 428.272 s  <<< FAILURE!
2023-02-14T03:27:08.3307792Z org.opentest4j.AssertionFailedError: 
2023-02-14T03:27:08.3308675Z There were errors in the GDB session. Note that commands in the session might depend on each other. Errors: 
2023-02-14T03:27:08.3309479Z Command 'b ConfigTestController.java:33' did not match the expected pattern '.*Breakpoint 1 at .*: file com/example/quarkus/config/ConfigTestController.java, line 33.*'.
2023-02-14T03:27:08.3309895Z Output was:
2023-02-14T03:27:08.3310228Z (gdb) (gdb) (gdb) GNU gdb (Ubuntu 12.1-0ubuntu1~22.04) 12.1
2023-02-14T03:27:08.3310521Z Copyright (C) 2022 Free Software Foundation, Inc.
2023-02-14T03:27:08.3310854Z License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
2023-02-14T03:27:08.3311417Z This is free software: you are free to change and redistribute it.
2023-02-14T03:27:08.3311729Z There is NO WARRANTY, to the extent permitted by law.
2023-02-14T03:27:08.3312012Z Type "show copying" and "show warranty" for details.
2023-02-14T03:27:08.3312352Z This GDB was configured as "x86_64-linux-gnu".
2023-02-14T03:27:08.3312631Z Type "show configuration" for configuration details.
2023-02-14T03:27:08.3312902Z For bug reporting instructions, please see:
2023-02-14T03:27:08.3313177Z <https://www.gnu.org/software/gdb/bugs/>.
2023-02-14T03:27:08.3313520Z Find the GDB manual and other documentation resources online at:
2023-02-14T03:27:08.3313831Z     <http://www.gnu.org/software/gdb/documentation/>.
2023-02-14T03:27:08.3314004Z 
2023-02-14T03:27:08.3314091Z For help, type "help".
2023-02-14T03:27:08.3314340Z Type "apropos word" to search for commands related to "word".
2023-02-14T03:27:08.3314635Z (gdb) No symbol table is loaded.  Use the "file" command.
2023-02-14T03:27:08.3314853Z , 
2023-02-14T03:27:08.3315279Z Command 'bt' did not match the expected pattern '.*at.*com/example/quarkus/config/ConfigTestController.java:33.*'.
2023-02-14T03:27:08.3315597Z Output was:
2023-02-14T03:27:08.3315793Z Selected thread is running.
2023-02-14T03:27:08.3316026Z (gdb) [New Thread 0x7fffdaffe640 (LWP 4316)]
2023-02-14T03:27:08.3316273Z [New Thread 0x7fffd9ffd640 (LWP 4317)]
2023-02-14T03:27:08.3316510Z [New Thread 0x7fffc3fff640 (LWP 4318)]
2023-02-14T03:27:08.3316731Z [New Thread 0x7fffc2ffe640 (LWP 4319)]
2023-02-14T03:27:08.3317513Z 2023-02-14 03:25:07,347 WARN  [io.jae.int.rep.RemoteReporter] (jaeger.RemoteReporter-QueueProcessor) FlushCommand execution failed! Repeated errors of this command will not be logged.: io.jaegertracing.internal.exceptions.SenderException: Failed to flush spans.
2023-02-14T03:27:08.3318223Z 	at io.jaegertracing.thrift.internal.senders.ThriftSender.flush(ThriftSender.java:116)
2023-02-14T03:27:08.3318738Z 	at io.jaegertracing.internal.reporters.RemoteReporter$FlushCommand.execute(RemoteReporter.java:158)
2023-02-14T03:27:08.3319240Z 	at io.jaegertracing.internal.reporters.RemoteReporter$QueueProcessor.run(RemoteReporter.java:179)
2023-02-14T03:27:08.3319714Z 	at java.base@17.0.7-beta/java.lang.Thread.run(Thread.java:833)
2023-02-14T03:27:08.3320196Z 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:807)
2023-02-14T03:27:08.3320875Z 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211)
2023-02-14T03:27:08.3321556Z Caused by: io.jaegertracing.internal.exceptions.SenderException: Could not send 1 spans
2023-02-14T03:27:08.3322026Z 	at io.jaegertracing.thrift.internal.senders.HttpSender.send(HttpSender.java:70)
2023-02-14T03:27:08.3322509Z 	at io.jaegertracing.thrift.internal.senders.ThriftSender.flush(ThriftSender.java:114)
2023-02-14T03:27:08.3322822Z 	... 5 more
2023-02-14T03:27:08.3323145Z Caused by: java.net.ConnectException: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:14268
2023-02-14T03:27:08.3323576Z 	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:265)
2023-02-14T03:27:08.3324143Z 	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:183)
2023-02-14T03:27:08.3324595Z 	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
2023-02-14T03:27:08.3325104Z 	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
2023-02-14T03:27:08.3325575Z 	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
2023-02-14T03:27:08.3325998Z 	at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
2023-02-14T03:27:08.3326463Z 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
2023-02-14T03:27:08.3326943Z 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
2023-02-14T03:27:08.3327408Z 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
2023-02-14T03:27:08.3327896Z 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
2023-02-14T03:27:08.3328333Z 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
2023-02-14T03:27:08.3328772Z 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
2023-02-14T03:27:08.3329203Z 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
2023-02-14T03:27:08.3329653Z 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
2023-02-14T03:27:08.3330154Z 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
2023-02-14T03:27:08.3330647Z 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
2023-02-14T03:27:08.3331084Z 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
2023-02-14T03:27:08.3331516Z 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
2023-02-14T03:27:08.3331866Z 	at okhttp3.RealCall.execute(RealCall.java:81)
2023-02-14T03:27:08.3332237Z 	at io.jaegertracing.thrift.internal.senders.HttpSender.send(HttpSender.java:68)
2023-02-14T03:27:08.3332544Z 	... 6 more
2023-02-14T03:27:08.3332790Z Caused by: java.net.ConnectException: Connection refused
2023-02-14T03:27:08.3333177Z 	at java.base@17.0.7-beta/sun.nio.ch.Net.pollConnect(Net.java)
2023-02-14T03:27:08.3333579Z 	at java.base@17.0.7-beta/sun.nio.ch.Net.pollConnectNow(Net.java:672)
2023-02-14T03:27:08.3334067Z 	at java.base@17.0.7-beta/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
2023-02-14T03:27:08.3334567Z 	at java.base@17.0.7-beta/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
2023-02-14T03:27:08.3335025Z 	at java.base@17.0.7-beta/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
2023-02-14T03:27:08.3335449Z 	at java.base@17.0.7-beta/java.net.Socket.connect(Socket.java:633)
2023-02-14T03:27:08.3335831Z 	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:130)
2023-02-14T03:27:08.3336267Z 	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:263)
2023-02-14T03:27:08.3336580Z 	... 25 more
2023-02-14T03:27:08.3336692Z 
2023-02-14T03:27:08.3336751Z , 
2023-02-14T03:27:08.3337137Z Command 'list' did not match the expected pattern '.*String value = config.getValue\("value", String.class\);.*'.
2023-02-14T03:27:08.3337433Z Output was:
2023-02-14T03:27:08.3337726Z 1	../sysdeps/x86/abi-note.c: No such file or directory.
2023-02-14T03:27:08.3338019Z , 
2023-02-14T03:27:08.3338309Z Command 'c&' did not match the expected pattern '.*Continuing.*'.
2023-02-14T03:27:08.3338558Z Output was:
2023-02-14T03:27:08.3338819Z (gdb) Cannot execute this command while the selected thread is running.
2023-02-14T03:27:08.3339084Z  ==> expected: <true> but was: <false>
2023-02-14T03:27:08.3339488Z 	at org.graalvm.tests.integration.DebugSymbolsTest.carryOutGDBSession(DebugSymbolsTest.java:394)
2023-02-14T03:27:08.3340048Z 	at org.graalvm.tests.integration.DebugSymbolsTest.debugSymbolsQuarkus(DebugSymbolsTest.java:219)
2023-02-14T03:27:08.3340405Z 
```

See https://github.com/Karm/mandrel-integration-tests/issues/102#issuecomment-1429085930

The Mandrel CI runs on Ubuntu-latest (i.e. 22.04): https://github.com/graalvm/mandrel/blob/default/.github/workflows/base.yml#L88

Whereas our IT CI runs on Ubuntu 20.04: https://github.com/Karm/mandrel-integration-tests/blob/master/.github/workflows/local_tests.yml#L29

FYI @zakkak I think there might be some devel package missing to make gdb happy with glibc stuff. I will eventually spin up a VM and investigate unless you know from the top of your head what it is...

### LINKED ISSUE #31258: Synchronize GraalVM upstream's and Quarkus'-only debug info stripping
### Describe the bug

GraalVM 23.0 will gain functionality to [strip debuginfo](https://github.com/oracle/graal/pull/5691). This is turned on by default when debuginfo generation is being turned on. As a result, quarkus applications trying to turn on debuginfo and then trying to use it in a debugger results in a CRC mismatch when loading them with gdb (for example):

```
warning: the debug information found in "/disk/graal/upstream-sources/mandrel-integration-tests/apps/quarkus-full-microprofile/target/quarkus-native-image-source-jar/quarkus-runner.debug" does not match "/disk/graal/upstream-sources/mandrel-integration-tests/apps/quarkus-full-microprofile/target/quarkus-native-image-source-jar/quarkus-runner" (CRC mismatch).
```

This is caused by two `.gnu_debuglink` sections trying to get created. The first one by GraalVM, the second by quarkus's native image build steps. The second attempt will fail and then the debuginfo won't match the CRC.

### Expected behavior

Either use upstream's feature or turn it off using `-H:-StripDebugInfo` and keep using quarkus's approach.

### Actual behavior

Debuginfo isn't working. See:
https://github.com/Karm/mandrel-integration-tests/issues/138

### How to Reproduce?

Build a quarkus up in native with a GraalVM 23.0.0 snapshot build with debuginfo. Try to debug the binary in gdb. Observe the CRC warning and debuginfo not usable for source-file-based break points.

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

17.0.7+1

### GraalVM version (if different from Java)

23.0.0

### Quarkus version or git rev

main

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by zakkak**
Starting with GraalVM/Mandrel 23.0, native-image strips debug info in a separate file by default.
    
Fixes #31258
Fixes https://github.com/Karm/mandrel-integration-tests/issues/138

cc @jerboaa

### CODE REVIEW

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java [hunk 1]
```diff
@@ -712,6 +712,15 @@ public NativeImageInvokerInfo build() {
                      * See https://github.com/quarkusio/quarkus/issues/30772 for more details.
                      */
                     nativeImageArgs.add("-H:+TrackNodeSourcePosition");
+                    /*
+                     * Starting with GraalVM/Mandrel 23.0, native-image strips debug info in a separate file by default.
+                     * Quarkus already does this, so for the time being we disable GraalVM/Mandrel's splitting as in
+                     * contrast to Quarkus it uses absolute paths which makes debugging harder especially for
+                     * in-container builds.
```
Comment (jerboaa) [inline core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java:719]: I was too quick, sorry. There is no proof of this container issue. Even though the paths passed to `objcopy` are absolute, the links in the files end up being relative. So there seems to be no issue with upstream as far as I could tell. I'm not sure what the man page of `objcopy` alludes to, though. Anyway, perhaps we should use GraalVM's upstream version instead if it passes the failing integration tests?

Comment (zakkak) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java:719]: Still there is another difference between the GraalVM and the Quarkus approach. The former strips all info (including symbols which it keeps in a different file though) from the image while Quarkus strips only debug info.

Comment (jerboaa) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java]: That's right. I agree that it should be OK to do slightly different debuginfo handling between 22.3 and 23.x.

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildRunner.java [hunk 2]
```diff
@@ -66,21 +66,25 @@ public Result build(List<String> args, String nativeImageName, String resultingE
...
-                if (debugSymbolsEnabled) {
+                if (debugSymbolsEnabled && graalVMVersion.compareTo(GraalVM.Version.VERSION_23_0_0) < 0) {
+                    // Need to explicitly split debug symbols prior to GraalVM/Mandrel 23.0
                     splitDebugSymbols(nativeImageName, resultingExecutableName);
                 }
-                // Strip debug symbols regardless, because the underlying JDK might contain them
-                objcopy("--strip-debug", resultingExecutableName);
+                if (!debugSymbolsEnabled || graalVMVersion.compareTo(GraalVM.Version.VERSION_23_0_0) < 0) {
+                    // Strip debug symbols even if not generated by GraalVM/Mandrel, because the underlying JDK might
+                    // contain them
```
Comment (jerboaa) [inline core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildRunner.java:79]: Could you please expand on the comment here? In particular we do not want to strip debuginfo on `>= GraalVM 23.x` when debug symbols are turned on, since in that case `native-image` itself would do the stripping.

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildRunner.java [hunk 3]
```diff
@@ -66,21 +66,25 @@ public Result build(List<String> args, String nativeImageName, String resultingE
...
+                    objcopy("--strip-debug", resultingExecutableName);
+                }
             } else if (SystemUtils.IS_OS_LINUX) {
```
Comment (jerboaa) [inline core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildRunner.java:82]: So on a system without `objcopy` and GraalVM  `>= 23.0` and debuginfo turned on, we'd get duplicate warnings about `objcopy` missing. Once by quarkus a second time from `native-image`.

**Review by jerboaa — COMMENTED** [review]
Looks good. Two minor things...

**Comment by zakkak** [comment]
> Looks good. Two minor things...

@jerboaa I Added a new commit to address these two as well. Please have a look.

**Review by jerboaa — APPROVED** [review]
Looks fine to me. Thanks!

**Comment by zakkak** [comment]
Once reviewed by someone else as well and the CI passes I will squash the commits and merge.

**Comment by jerboaa** [comment]
@gsmet Could you please help get this reviewed and integrated? Thanks! This issue is causing some noise in our mandrel CI. I've verified the fix works, fwiw.

**Review by geoand — APPROVED** [review]

**Comment by geoand** [comment]
We have a job failing due to one of the commits being a fixup commit. Let's address it before merging :)

**Comment by jerboaa** [comment]
Thanks all!
