### PR TITLE
Provide correct generic type and annotations in ParamConverterProvider

### LINKED ISSUE #32765: RR client: annotations on `@*Param` fields present in `@BeanParam` class unavailable to custom `ParamConverterProvider`
### Describe the bug

I wrote a custom type with generic parameter
```
class Operation<T> {
  String name;
  String op;
  T value;
}
```
a custom annotation 
```
interface @OperationParam {
  String value();
  Class<?> boundedType();
}
```
and custom ParamConverterProvider + ParamConverter
```
public class OperationConverter<T> implements ParamConverter<Operation<T>>
{
  ParamConverter<T> valueConverter;
  String name;
}

@Provider
public class OperationConverterProvider implements ParamConverterProvider {
  @Override
  public <T> ParamConverter<T> getConverter(Class<T> rawType, Type genericType, Annotation[] annotations) {
    if (rawType.isAssignableFrom(Operation.class)) {
      OperationParam  annot = getOperationParamAnnot(annotations);
      String name = /* extract information from annotation or method parameters */;
      ParamConverter<T> valueConverter = /* extract information from annotation or method parameters to create right implementation */;
      return new OperationConverter<T>(name, valueConverter);
    }
    return null;
  }
}
```

Given
```
@RegisterRestClient(configKey = "client")
interface Client {
  @Path("call-with-bean")
  @GET
  void callWithBean(@BeanParam MultipleFilterRuleBean bean);
}

class MultipleFilterRuleBean {
  @OperationParam(value = "int_from_annot")
  @QueryParam("i")
  public Operation<Integer> integer;
  @OperationParam(value = "enum_from_annot", boundedType = MyEnum.class)
  @QueryParam("e")
  public Operation myEnum;
}
```
in my `OperationConverterProvider` the only available annotation in `annotations` param is `@BeanParam`, not `@OperationParam` not `@QueryParam` are available as I expected.

### Expected behavior

First error: accessing annotations on every annotated properties and not client only annotations attached to @RestClient method.

### Actual behavior

as described above

### How to Reproduce?

- https://github.com/luca-bassoricci/custom-provider/tree/main : reproducer for annotation problem

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Sgitario**
These changes will provide the correct generic type and array of annotations when the JAX-RS annotation is present on a field or a method of a Bean Param class. 

The solution is similar to what was being done for the parameters of a REST Client method: it will load the metadata (generic type and annotations from fields and methods) of a BeanParam class using reflection only if there is a ParamConverterProvider present.

Fix https://github.com/quarkusio/quarkus/issues/32765

### CODE REVIEW

File: extensions/resteasy-reactive/jaxrs-client-reactive/deployment/src/main/java/io/quarkus/jaxrs/client/reactive/deployment/ClassRestClientContext.java [hunk 1]
```diff
@@ -125,4 +129,43 @@ protected Supplier<FieldDescriptor> getLazyJavaMethodGenericParametersField(int
...
+
+            beanTypesParameterDescriptorsStaticFields.put(beanClass, field);
+
+            beanParamIndex++;
+
+            return field;
+        };
+    }
+
+    private ResultHandle loadClass(String className) {
```
Comment (Sgitario) [inline extensions/resteasy-reactive/jaxrs-client-reactive/deployment/src/main/java/io/quarkus/jaxrs/client/reactive/deployment/ClassRestClientContext.java:161]: This method is to avoid loading the same class only once, so we avoid a performance penalty here.

File: extensions/resteasy-reactive/rest-client-reactive/deployment/src/test/java/io/quarkus/rest/client/reactive/converter/ParamConverterProviderTest.java [hunk 2]
```diff
@@ -117,7 +117,7 @@ interface Client {
 
         @GET
         @Path("/cookie")
-        String getWithCookie(@HeaderParam("cookie-param") Param param);
+        String getWithCookie(@CookieParam("cookie-param") Param param);
```
Comment (Sgitario) [inline extensions/resteasy-reactive/rest-client-reactive/deployment/src/test/java/io/quarkus/rest/client/reactive/converter/ParamConverterProviderTest.java:120]: This change is unrelated to this pull request, but I saw it was originally wrong, so I fix it to use the `@CookieParam` annotation.

**Review by geoand — APPROVED** [review]
