### PR TITLE
Register JPA static metamodel classes for reflection

### LINKED ISSUE #45503: Hibernate tries to reflectively access metamodel classes not registered for reflection
### Describe the bug
Hibernate seems to be reflectively accessing some metamodel classes that we don't register for reflection in native-mode.

The classes are accessed in https://github.com/hibernate/hibernate-orm/blob/9d52e3c9dfc49a9be804220c2382055d5901daa9/hibernate-core/src/main/java/org/hibernate/metamodel/internal/MetadataContext.java#L728-L731

Relates to https://github.com/quarkusio/quarkus/issues/41995

### Expected behavior

All reflective accesses should be registered.

### Actual behavior

Reflective accesses are not registered resulting in warnings like the following when using `-H:ThrowMissingRegistrationErrors=`:

```
...
org.graalvm.nativeimage.MissingReflectionRegistrationError: The program tried to reflectively access class

   io.quarkus.it.jpa.db2.Human_

without it being registered for runtime reflection. Add io.quarkus.it.jpa.db2.Human_ to the reflection metadata to solve this problem. See https://www.graalvm.org/latest/reference-manual/native-image/metadata/#reflection for help.
  java.base@23.0.1/java.lang.Class.forName(DynamicHub.java:1475)
  io.quarkus.hibernate.orm.runtime.service.FlatClassLoaderService.classForName(FlatClassLoaderService.java:36)
  org.hibernate.metamodel.internal.MetadataContext.populateStaticMetamodel(MetadataContext.java:722)
  org.hibernate.metamodel.internal.MetadataContext.wrapUp(MetadataContext.java:395)
org.graalvm.nativeimage.MissingReflectionRegistrationError: The program tried to reflectively access class

   io.quarkus.it.jpa.db2.Customer_

without it being registered for runtime reflection. Add io.quarkus.it.jpa.db2.Customer_ to the reflection metadata to solve this problem. See https://www.graalvm.org/latest/reference-manual/native-image/metadata/#reflection for help.
  java.base@23.0.1/java.lang.Class.forName(DynamicHub.java:1475)
  io.quarkus.hibernate.orm.runtime.service.FlatClassLoaderService.classForName(FlatClassLoaderService.java:36)
  org.hibernate.metamodel.internal.MetadataContext.populateStaticMetamodel(MetadataContext.java:722)
  org.hibernate.metamodel.internal.MetadataContext.wrapUp(MetadataContext.java:345)
org.graalvm.nativeimage.MissingReflectionRegistrationError: The program tried to reflectively access class

   io.quarkus.it.jpa.db2.Person_

without it being registered for runtime reflection. Add io.quarkus.it.jpa.db2.Person_ to the reflection metadata to solve this problem. See https://www.graalvm.org/latest/reference-manual/native-image/metadata/#reflection for help.
  java.base@23.0.1/java.lang.Class.forName(DynamicHub.java:1475)
  io.quarkus.hibernate.orm.runtime.service.FlatClassLoaderService.classForName(FlatClassLoaderService.java:36)
  org.hibernate.metamodel.internal.MetadataContext.populateStaticMetamodel(MetadataContext.java:722)
  org.hibernate.metamodel.internal.MetadataContext.wrapUp(MetadataContext.java:345)
...
```

### How to Reproduce?

```
./mvnw clean package -Dnative -Dnative.surefire.skip \
  -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-23 \
  -pl integration-tests/jpa-db2/ \
  -Dquarkus.native.additional-build-args=-H:ThrowMissingRegistrationErrors=

./integration-tests/jpa-db2/target/quarkus-integration-test-jpa-db2-999-SNAPSHOT-runner -XX:MissingRegistrationReportingMode=Warn
```

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

21.0.5

### Mandrel or GraalVM version (if different from Java)

Mandrel-24.1.1.0-Final

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by yrodiere**
Fixes #45503 

So that Hibernate ORM can populate their `class_` attribute.

Alternatively we could have prevented Hibernate ORM from populating the class_ attribute, but this would have been a breaking change in JVM mode or for applications that already enabled reflection on the static metamodel. This is safer.

I'm not adding a test because another pending PR is going to tighten up native compilation checks, and those would fail if this PR doesn't work, so we'll know.

### CODE REVIEW

File: extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/JpaJandexScavenger.java [hunk 1]
```diff
@@ -108,6 +108,11 @@ public JpaModelBuildItem discoverModelAndRegisterForReflection() throws BuildExc
         managedClassNames.addAll(collector.modelTypes);
         for (String className : managedClassNames) {
             reflectiveClass.produce(ReflectiveClassBuildItem.builder(className).methods().fields().build());
+            // Register static metamodel classes as well, so that their `class_` attribute can be populated.
+            // See org.hibernate.metamodel.internal.MetadataContext.populateStaticMetamodel
+            // Note: registering classes that do not exist is not a problem -- and is necessary if the application
+            //       tries to access these classes via reflection anyway (which it will, through Hibernate ORM).
+            reflectiveClass.produce(ReflectiveClassBuildItem.builder(className + "_").fields().build());
```
Comment (gsmet) [inline extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/JpaJandexScavenger.java:115]: We are positive these classes will exist?

Comment (yrodiere) [reply extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/JpaJandexScavenger.java:115]: On the contrary, we're positive they won't exist most of the time.

But Hibernate ORM tries to load them to see if they exist, and @zakkak 's changes require that we register unexisting classes too, if an attempt to load them is done.

Alternatively we could patch Hibernate ORM to catch and ignore whatever weird exception GraalVM will throw upon attempting to load classes that are not registered for reflection. But frankly, that seems like tainting the ORM codebase with things it should not have to worry about.

**Review by zakkak — APPROVED** [review]
LGTM thanks @yrodiere.

**Comment by zakkak** [comment]
@gsmet I will let you merge this to make sure you have no further concerns.
