### PR TITLE
Prevent startup failing when having mismatched datasource types

### LINKED ISSUE #47036: Hibernate Extension: Check the error message when multiple JDBC Driver
### Description

See https://github.com/quarkusio/quarkus/pull/44473#discussion_r2010068208

After https://github.com/quarkusio/quarkus/pull/44473 I found out that to get this error message, we need to have both JDBC drivers, when including only pgsql the error message is different. Investigate why

### Implementation ideas

See

```
        Optional<String> dbKindOptional = DefaultDataSourceDbKindBuildItem.resolve(
                defaultDataSourceBuildTimeConfig.dbKind(),
                defaultDataSourceDbKindBuildItems,
                defaultDataSourceBuildTimeConfig.devservices().enabled()
                        .orElse(!dataSourcesBuildTimeConfig.hasNamedDataSources()),
                curateOutcomeBuildItem);

```

### LINKED ISSUE #50634: Hibernate default blocking PU + named reactive PU causes errors
### Describe the bug

I created a Quarkus application using both Hibernate ORM and Reactive. I configured the blocking side with the default (unnamed) datasource pointing to the JDBC database URL, and a default (unnamed) ORM persistence unit. Then, I tried adding a named reactive datasource and a named reactive persistence unit using it. This resulted in an error when trying to start the application in dev mode, as the blocking persistence unit seems to look for a JDBC datasource with the same name as the configured reactive one.

From some initial troubleshooting, with the help of @lucamolteni, a couple of things stood out as possible causes: first, the check for whether to enable the default ORM persistence unit or not uses the `HibernateOrmConfig#namedPersistenceUnits` map, regardless if those PUs are blocking or reactive:

https://github.com/quarkusio/quarkus/blob/4811438a48074bf8ee3e62442dd9423dec762a31/extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmProcessor.java#L891-L893

When trying to filter this map, based on the PU's configured datasource, we found that a blocking datasource with the same name as the configured reactive one was present in the `JdbcDataSourceBuildItem` list. In the Agroal extension, we noticed the configuration for the blocking default datasource was always returned here:

https://github.com/quarkusio/quarkus/blob/2191f01cd843798b6e5a5df6707aa964e14cba11/extensions/agroal/deployment/src/main/java/io/quarkus/agroal/deployment/AgroalProcessor.java#L309-L313

Even when looking up with the named reactive datasource name. This should be caused by the fact that `DataSourcesJdbcBuildTimeConfig#dataSources` is a map with default value, so if an entry for a specific key is not found the default datasource configuration is returned.

### Expected behavior

The application works with both blocking and reactive PUs available as expected.

### Actual behavior

Applications fails to start due to Agroal failing to find a named blocking datasource with the name of the configured reactive one.

### How to Reproduce?

Here is a link to a Quarkus [unit test case](https://github.com/mbellade/quarkus/blob/053a0df6818b76744cfa7cd6bd8806d605bed196/extensions/hibernate-reactive/deployment/src/test/java/io/quarkus/hibernate/reactive/compatibility/ORMReactiveCompatibilityNamedReactiveDefaultBlockingUnitTest.java) similar to the existing ones reproducing the problem.

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by lucamolteni**
Prevent startup failing when having mismatched datasource types between Hibernate ORM (blocking) and Hibernate Reactive by validating datasource configuration at build time.

- Blocking persistence units are not created when only reactive datasources are configured
- Reactive persistence units are not created when only blocking datasources are configured
- Clear error messages are provided when datasources are missing

- Created HibernateDataSourceUtil with shared datasource lookup logic
- Extracted ReactiveDataSourceBuildItem to new `quarkus-reactive-datasource-spi` module to enable reactive data source checking in the Hibernate ORM extension
- Refactored HibernateOrmProcessor and HibernateReactiveProcessor to validate datasource types and don't create the PU when there's no appropriate DS
- Fail correctly when using a single extension but the datasource name is mismatched
- Fixed ORMReactiveCompatbilityDifferentNamedDataSourceNamedPersistenceUnitBothUnitTest which was incorrectly passing due to dev services
- Added new test cases for mixed datasource scenarios

* Fixes #50634 
* Fixes #47036

### CODE REVIEW

File: extensions/reactive-datasource/deployment/src/main/java/io/quarkus/reactive/datasource/deployment/ReactiveDataSourceProcessor.java [hunk 1]
```diff
@@ -97,14 +97,23 @@ private List<AggregatedDataSourceBuildTimeConfigBuildItem> getAggregatedConfigBu
     @BuildStep
     void produceReactiveDataSourceBuildItem(
             List<AggregatedDataSourceBuildTimeConfigBuildItem> aggregatedBuildTimeConfigBuildItems,
-            BuildProducer<ReactiveDataSourceBuildItem> dataSource) {
+            BuildProducer<ReactiveDataSourceBuildItem> deprecatedDataSourceBuildItem,
+            BuildProducer<io.quarkus.reactive.datasource.spi.ReactiveDataSourceBuildItem> dataSource) {
```
Comment (yrodiere) [inline extensions/reactive-datasource/deployment/src/main/java/io/quarkus/reactive/datasource/deployment/ReactiveDataSourceProcessor.java]: No need to change the code, but just so you know: the usual solution is to create an additional build step that takes the new build item as input, and creates the old build item as output.

It technically allows skipping the creation of old build items if they aren't used anywhere, though I don't think it matters much in practice.

File: extensions/reactive-datasource/deployment/src/main/java/io/quarkus/reactive/datasource/deployment/ReactiveDataSourceBuildItem.java [hunk 2]
```diff
@@ -3,15 +3,18 @@
...
  * A build item for Reactive Datasources, a.k.a. Verx {@link Pool}s.
  * <p>
  * If you inject this build item when recording runtime init template calls, you are guaranteed the Pool configuration
  * has been injected. Pools are created witihin their own extensions
  * Similar to VertxPoolBuildItem, but doesn't include the Pool itself, only the name.
+ *
+ * Deprecated: use io/quarkus/reactive/datasource/spi/ReactiveDataSourceBuildItem.java instead
  */
+// TODO Luca add deprecation version
+@Deprecated(since = "version")
```
Comment (yrodiere) [inline extensions/reactive-datasource/deployment/src/main/java/io/quarkus/reactive/datasource/deployment/ReactiveDataSourceBuildItem.java]: Adding a comment here so that we don't merge this unfixed.

File: extensions/hibernate-reactive/deployment/src/test/resources/application-unittest-both-named-reactive-and-default-blocking.properties [hunk 3]
```diff
@@ -0,0 +1,2 @@
+quarkus.datasource.jdbc.url=${postgres.blocking.url}
+quarkus.datasource."named-datasource".reactive.url=${postgres.reactive.url}
```
Comment (yrodiere) [inline extensions/hibernate-reactive/deployment/src/test/resources/application-unittest-both-named-reactive-and-default-blocking.properties:2]: Beware ; this will likely conflict with #51066 , but only on `main` -- older branches will still need this to deal with the Maven Docker Plugin.

Either this gets merged before #51066, and @holly-cummins will need to update her PR, or it gets merged after #51066, and you'll need two separate changesets for `main` and older branches.

File: extensions/hibernate-reactive/deployment/src/test/java/io/quarkus/hibernate/reactive/compatibility/ORMReactiveCompatibilityNamedReactiveDefaultBlockingUnitTest.java [hunk 4]
```diff
@@ -0,0 +1,59 @@
...
+    @RegisterExtension
+    static final QuarkusUnitTest config = new QuarkusUnitTest()
+            .withApplicationRoot((jar) -> jar
+                    .addClasses(Hero.class)
+                    .addAsResource("complexMultilineImports.sql", "import.sql"))
+            .setForcedDependencies(List.of(
+                    Dependency.of("io.quarkus", "quarkus-jdbc-postgresql-deployment", Version.getVersion()) // this triggers Agroal
+            ))
+            .withConfigurationResource("application-unittest-both-named-reactive-and-default-blocking.properties")
+            // To have the named PU is reactive we need to explicitly disable the blocking the JDBC data source
```
Comment (yrodiere) [inline extensions/hibernate-reactive/deployment/src/test/java/io/quarkus/hibernate/reactive/compatibility/ORMReactiveCompatibilityNamedReactiveDefaultBlockingUnitTest.java]:
```suggestion
            // To have the named PU be reactive only, we need to explicitly disable the blocking the JDBC data source
```

File: extensions/hibernate-reactive/deployment/src/test/java/io/quarkus/hibernate/reactive/compatibility/ORMReactiveCompatibilityNamedReactiveDefaultBlockingUnitTest.java [hunk 5]
```diff
@@ -0,0 +1,59 @@
...
+            .overrideConfigKey("quarkus.datasource.\"named-datasource\".jdbc", "false")
+            .overrideConfigKey("quarkus.datasource.\"named-datasource\".reactive", "true")
+            .overrideConfigKey("quarkus.hibernate-orm.\"named-pu\".schema-management.strategy", SCHEMA_MANAGEMENT_STRATEGY)
+            .overrideConfigKey("quarkus.hibernate-orm.\"named-pu\".datasource", "named-datasource")
+            .overrideConfigKey("quarkus.hibernate-orm.\"named-pu\".packages", "io.quarkus.hibernate.reactive.entities")
+            .overrideConfigKey("quarkus.datasource.\"named-datasource\".db-kind", POSTGRES_KIND)
+            .overrideConfigKey("quarkus.datasource.\"named-datasource\".username", USERNAME_PWD)
+            .overrideConfigKey("quarkus.datasource.\"named-datasource\".password", USERNAME_PWD)
+            // Default blocking will need to disable the reactive one, JDBC is enabled by default.
+            .overrideConfigKey("quarkus.datasource.reactive", "false")
```
Comment (yrodiere) [inline extensions/hibernate-reactive/deployment/src/test/java/io/quarkus/hibernate/reactive/compatibility/ORMReactiveCompatibilityNamedReactiveDefaultBlockingUnitTest.java]:
```suggestion
            // The default PU is intended as blocking only, so we need to disable reactive on the datasource.
            // JDBC is enabled by default.
            .overrideConfigKey("quarkus.datasource.reactive", "false")
```

File: extensions/hibernate-reactive/deployment/src/test/java/io/quarkus/hibernate/reactive/compatibility/ORMReactiveCompatbilityDifferentNamedDataSourceNamedPersistenceUnitBothUnitTest.java [hunk 6]
```diff
@@ -27,9 +27,10 @@ public class ORMReactiveCompatbilityDifferentNamedDataSourceNamedPersistenceUnit
             .setForcedDependencies(List.of(
                     Dependency.of("io.quarkus", "quarkus-jdbc-postgresql-deployment", Version.getVersion()) // this triggers Agroal
             ))
-            .withConfigurationResource("application-unittest-both-named.properties")
+            .withConfigurationResource("application-unittest-both-named-different.properties")
 
             // Reactive named datasource
+            .overrideConfigKey("quarkus.datasource.\"named-datasource-reactive\".jdbc", "false")
```
Comment (yrodiere) [inline extensions/hibernate-reactive/deployment/src/test/java/io/quarkus/hibernate/reactive/compatibility/ORMReactiveCompatbilityDifferentNamedDataSourceNamedPersistenceUnitBothUnitTest.java:33]: This is the test that you told me was incorrect to begin with and giving a false positive, right?
The one that was supposed to detect the bug you're fixing?

Just trying to make sure I understand why a pre-existing test is getting changed :)

File: extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmProcessor.java [hunk 7]
```diff
@@ -968,8 +974,32 @@ private static void producePersistenceUnitDescriptorFromConfig(
...
+            return;
+        }
+
+        boolean explicitDataSource = persistenceUnitConfig.datasource().isPresent();
+        if (jdbcDataSource.isEmpty() && explicitDataSource) {
+            String dataSourceName = persistenceUnitConfig.datasource().get();
+            throw PersistenceUnitUtil.unableToFindDataSource(persistenceUnitName, dataSourceName,
+                    DataSourceUtil.dataSourceNotConfigured(dataSourceName));
+        }
+
```
Comment (yrodiere) [inline extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmProcessor.java:1002]: IIUC this is the crux of this patch: we still throw an exception at build time when pointing to an explicit JDBC datasource if that datasource doesn't exist... _except_ if that datasource is reactive-only, in which case we assume the user wants a reactive-only PU.

This makes sense to me, and doesn't seem _too_ dangerous considering that:

1. For a datasource to be reactive-only, you need to either not include a JDBC driver (in which case Hibernate ORM blocking doesn't make sense) or to explicitly set `.jdbc=false`.
2. If our assumption is wrong, the user will most likely get a different error at build time because there are no matching beans for injections points of type `Session`.

So the risk of not properly reporting a true user mistake is rather slim.

Now, we probably want to improve on this, for example by making sure that when no matching bean is found for `Session`, we explain why ("the datasource is reactive only"). But that's not something we can easily do here, so I opened #51198 to investigate improvements.

**Review by yrodiere — COMMENTED** [review]
Thanks! LGTM except for some comments that I had a hard time understanding, and of course the deprecation version that you mentioned in the PR's description.

File: extensions/hibernate-reactive/deployment/src/test/resources/application-unittest-both-named-reactive-and-default-blocking.properties (hunk 3 above)
Comment (yrodiere) [reply extensions/hibernate-reactive/deployment/src/test/resources/application-unittest-both-named-reactive-and-default-blocking.properties:2]: Sorry @lucamolteni , you lose, @holly-cummins was faster. So:



> or it gets merged after #51066, and you'll need two separate changesets for `main` and older branches.

Comment (holly-cummins) [reply extensions/hibernate-reactive/deployment/src/test/resources/application-unittest-both-named-reactive-and-default-blocking.properties:2]: Oops, sorry, @lucamolteni!

File: extensions/hibernate-reactive/deployment/src/test/java/io/quarkus/hibernate/reactive/compatibility/ORMReactiveCompatbilityDifferentNamedDataSourceNamedPersistenceUnitBothUnitTest.java (hunk 6 above)
Comment (lucamolteni) [reply extensions/hibernate-reactive/deployment/src/test/java/io/quarkus/hibernate/reactive/compatibility/ORMReactiveCompatbilityDifferentNamedDataSourceNamedPersistenceUnitBothUnitTest.java:33]: Yes exactly

File: extensions/hibernate-reactive/deployment/src/test/resources/application-unittest-both-named-reactive-and-default-blocking.properties (hunk 3 above)
Comment (yrodiere) [reply extensions/hibernate-reactive/deployment/src/test/resources/application-unittest-both-named-reactive-and-default-blocking.properties:2]: This was wrong:

> As with #51059, I left the `extensions/*` project using an independently-managed container, since the test exercises `application.properties` a lot.

Thus the relevant tests are not affected by Holly's PR.

File: extensions/reactive-datasource/deployment/src/main/java/io/quarkus/reactive/datasource/deployment/ReactiveDataSourceProcessor.java (hunk 1 above)
Comment (lucamolteni) [reply extensions/reactive-datasource/deployment/src/main/java/io/quarkus/reactive/datasource/deployment/ReactiveDataSourceProcessor.java]: I've done it anyway just to make sure I understand the flow

**Review by yrodiere — APPROVED** [review]
LGTM! Please set the `@Deprecated(since)` and we're good to merge.

**Comment by yrodiere** [comment]
Also please squash :)

**Comment by lucamolteni** [comment]
> LGTM! Please set the `@Deprecated(since)` and we're good to merge.


3.29.5

File: extensions/reactive-datasource/spi/pom.xml [hunk 8]
```diff
@@ -0,0 +1,21 @@
+<?xml version="1.0" encoding="UTF-8"?>
+<project xmlns="http://maven.apache.org/POM/4.0.0"
+         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
+         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
+    <modelVersion>4.0.0</modelVersion>
+    <parent>
+        <groupId>io.quarkus</groupId>
+        <artifactId>quarkus-reactive-datasource-parent</artifactId>
+        <version>999-SNAPSHOT</version>
```
Comment (gsmet) [inline extensions/reactive-datasource/spi/pom.xml:9]: @jmartisk note that we will need to change this one to `3.27.999-SNAPSHOT` when we backport to `3.27`. I will probably remember and worst case CI will catch it!

**Comment by jmartisk** [comment]
We tried backporting it to 3.27 but there were some conflicts we weren't quite confident to resolve, @lucamolteni if you do think it should go to 3.27, could you prepare a separate backport pull request? Thanks

**Comment by lucamolteni** [comment]
> We tried backporting it to 3.27 but there were some conflicts we weren't quite confident to resolve, @lucamolteni if you do think it should go to 3.27, could you prepare a separate backport pull request? Thanks

I'll create a separate PR for back porting today

**Comment by lucamolteni** [comment]
> We tried backporting it to 3.27 but there were some conflicts we weren't quite confident to resolve, @lucamolteni if you do think it should go to 3.27, could you prepare a separate backport pull request? Thanks

https://github.com/jmartisk/quarkus/pull/45

**Comment by fedinskiy** [comment]
@jmartisk I can reproduce this error even with current 3.27.999-SNAPSHOT (4d35b6f23883d770543a1680f7cdb47d39b45ce5), but not with 3.30.6. Was this patch backported?

**Comment by jmartisk** [comment]
@fedinskiy Oh no, it seems that I accidentally removed it from my backport PR :cry: 
It's too late for 3.27.2 now, I'll create a PR to be added to 3.27.3 then.
Thanks for noticing...
