### PR TITLE
Change HV validator interceptor to dynamically resolve Validator bean instance

### LINKED ISSUE #26931: Hibernate-validator won't properly work when using @Observes for ApplicationScoped.class
### Describe the bug

When using hibernate-validator on a class containing a `@Observes @Initialized(ApplicationScoped.class)` method, all the methods containing constraint annotations throw a NullPointerException:

```
java.lang.NullPointerException: Cannot invoke "javax.validation.Validator.forExecutables()" because "this.validator" is null

	at io.quarkus.hibernate.validator.runtime.interceptor.AbstractMethodValidationInterceptor.validateMethodInvocation(AbstractMethodValidationInterceptor.java:59)
	at io.quarkus.hibernate.validator.runtime.interceptor.MethodValidationInterceptor.validateMethodInvocation(MethodValidationInterceptor.java:17)
	at io.quarkus.hibernate.validator.runtime.interceptor.MethodValidationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
        ...
```

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

One can reproduce the problem with a QuarkusTest: 

```java
@QuarkusTest
class HibernateValidatorTest {

    @Inject
    TestClass testClass;

    @Test
    void test() {
        testClass.call(null); // or testClass.call("");
    }

    @ApplicationScoped
    static final class TestClass {

        void startUp(@Observes @Initialized(ApplicationScoped.class) final Object event) {

        }

        void call(@NotNull final Object o) {

        }

    }
}
```

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by manovotn**
Fixes #26931 

This is what I had in mind - it will delay resolution to always happen in runtime where the `Validator` bean is present and ready.
The `@WithCaching` annotation caches results of dependent beans and avoid trying to re-resolve them every time so it perhaps can save a few method invocations but it would work without it as well.

The attached test is just a twist on the reproducer in mentioned issue.

### CODE REVIEW

File: extensions/hibernate-validator/runtime/src/main/java/io/quarkus/hibernate/validator/runtime/interceptor/AbstractMethodValidationInterceptor.java [hunk 1]
```diff
@@ -101,7 +107,8 @@ protected void validateConstructorInvocation(InvocationContext ctx) throws Excep
         ctx.proceed();
         Object createdObject = ctx.getTarget();
 
-        violations = validator.forExecutables().validateConstructorReturnValue(ctx.getConstructor(), createdObject);
+        violations = validatorInstance.get().forExecutables().validateConstructorReturnValue(ctx.getConstructor(),
```
Comment (gsmet) [inline extensions/hibernate-validator/runtime/src/main/java/io/quarkus/hibernate/validator/runtime/interceptor/AbstractMethodValidationInterceptor.java:110]: Noticed while working on a similar patch and a good opportunity to fix it:
```suggestion
        violations = executableValidator.validateConstructorReturnValue(ctx.getConstructor(),
```

File: extensions/hibernate-validator/runtime/src/main/java/io/quarkus/hibernate/validator/runtime/interceptor/AbstractMethodValidationInterceptor.java [hunk 2]
```diff
@@ -37,9 +40,12 @@ public abstract class AbstractMethodValidationInterceptor implements Serializabl
      * field here. Upon passivation not the validator itself will be serialized, but
      * the proxy injected here, which in turn is serializable.
      * </p>
+     * {@link Instance} is used to make the resolution dynamic and working at runtime, this delays {@link Validator}
+     * injection enough to enable it to work for beans that observe {@code @Initialized(ApplicationScoped.class)} event.
      */
     @Inject
-    Validator validator;
+    @WithCaching
```
Comment (gsmet) [inline extensions/hibernate-validator/runtime/src/main/java/io/quarkus/hibernate/validator/runtime/interceptor/AbstractMethodValidationInterceptor.java:47]: If I move to singleton beans for ValidatorFactory and Validator, I can remove this, right? I'll check later today if something complains in the tree.

Comment (manovotn) [reply extensions/hibernate-validator/runtime/src/main/java/io/quarkus/hibernate/validator/runtime/interceptor/AbstractMethodValidationInterceptor.java:47]: That's correct (and even if you kept it here, it would simply have zero effect, it only affects resolution of dependent beans).

**Review by gsmet — APPROVED** [review]
Let's merge it and I will apply the minor improvement in the upcoming PR.

**Review by mkouba — COMMENTED** [review]
Nice!

**Comment by prateeksharma2988** [comment]
I am using 3.15.4 quarkus and while start-up of application i am intermittently getting NullPointerException 
@ApplicationScoped
public class CassandraConsistencyResolver extends ConsistencyResolver {

public DefaultConsistencyLevel getConsistencyLevel(Table table, Action action,
            @NotNull
                    Consistency consistency) {
    }
} this is sample code which being initialized and causing the issue. 

@NotNull annotation is not getting initialized properly and thus giving null pointer .
