### PR TITLE
Make OIDC CodeAuthenticationMechanism work with the proactive-auth disabled

### LINKED ISSUE #12090: OIDC CodeAuthenticationMechanism does not work if the proactive authentication is disabled
**Describe the bug**

Adding `quarkus.http.auth.proactive=false` breaks the OIDC adapter code flow (ex, adding this property to `integration-tests/oidc-code-flow/..../application.properties` breaks the tests)
Reported originally at https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/OIDC.20BearerAuthenticationMechanism.20for.20unproteced.20resources

### PR DESCRIPTION
**Pull request by sberyozkin**
Fixes #12090

### CODE REVIEW

**Comment by sberyozkin** [comment]
@pedroigor FYI, no OIDC changes are made here, we just need to have JAX-RS mappers for the OIDC exceptions to be caught properly in the proactive-auth disabled case

**Comment by pedroigor** [comment]
@sberyozkin LGTM.

**Comment by sberyozkin** [comment]
@pedroigor Thanks, I'd also like @stuartwdouglas to confirm, `CompositeExcepitonMapper` is a strange one but the original exception can be wrapped in it

File: extensions/resteasy/runtime/src/main/java/io/quarkus/resteasy/runtime/CompositeExceptionMapper.java [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+@Provider
+public class CompositeExceptionMapper implements ExceptionMapper<CompositeException> {
+
+    @Context
+    Providers p;
+
+    @SuppressWarnings("unchecked")
+    @Override
+    public Response toResponse(CompositeException ex) {
+        Throwable t = ex.getCauses().get(0);
```
Comment (stuartwdouglas) [inline extensions/resteasy/runtime/src/main/java/io/quarkus/resteasy/runtime/CompositeExceptionMapper.java:21]: This feels fragile, as there is no guarantee which exceptions will be first.

If you want to prioritise security exceptions I think you need to scan the list first to look for security exceptions that need special handling.

Comment (sberyozkin) [reply extensions/resteasy/runtime/src/main/java/io/quarkus/resteasy/runtime/CompositeExceptionMapper.java:21]: Hi @stuartwdouglas, I actually did not plan to do any specific filtering of the security exceptions in this mapper, as it is meant to be a generic mapper which would work for `CompositeException`.
As far as the OIDC exceptions are concerned, it can only be the OIDC-related exception, I've also confirmed it in the debug mode the other day.
In some other flows, not even related to OIDC, `CompositeException` may also happen I guess (example, the user code throws the exception in the Uni exception recovery block), so this mapper will work there too.
If we have a case where the user wants a cause at index 1 be mapped then they'd just register their own custom `CompositeExceptionMapper` mapper.
I reckon that for Quarkus in general we just need to look at the top cause and review it if there will be a case where it won't be sufficient, for now it seems to be fine.

Do you agree :-) ?

Comment (sberyozkin) [reply extensions/resteasy/runtime/src/main/java/io/quarkus/resteasy/runtime/CompositeExceptionMapper.java]: @stuartwdouglas I've updated this mapper to check for the 1st non-null cause, but for now I'd still rather prefer it be a generic mapper. Does it work for you ?

**Review by stuartwdouglas — APPROVED** [review]

**Comment by gsmet** [comment]
This cannot be backported easily as it requires a Quarkus Security upgrade and some exceptions have moved from Quarkus to Quarkus Security.
