### PR TITLE
Adjust WrongAnnotationUsageProcessor to recognize interceptor bindings on nested classes

### LINKED ISSUE #20034: @TestTransaction in combination with Junit5 @Nested does not roll back
### Describe the bug

In a `@QuarkusTest` placing `@TestTransaction` on methods inside a Junit5 `@Nested` class does not roll back the transaction - the test data stays in the database. Moving the test method out of the `@Nested class` makes it work.

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.0.2.Final and latest

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by manovotn**
Fixes #20034 

Tested on quickstarts, the output looks like this:

```
[ERROR]   GreetingServiceTest.testGreetingService » Runtime java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#generateResources threw an exception: javax.enterprise.inject.spi.DeploymentException: java.lang.IllegalStateException: The INNER class org.acme.getting.started.testing.GreetingServiceTest$NestedClassTest declares an interceptor binding but it must be ignored per CDI rules

```

### CODE REVIEW

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/WrongAnnotationUsageProcessor.java [hunk 1]
```diff
@@ -90,6 +91,16 @@ public String apply(AnnotationInstance annotationInstance) {
                             new IllegalStateException(String.format(
                                     "The %s class %s declares a producer but it must be ignored per the CDI rules",
                                     clazz.nestingType().toString(), clazz.name().toString()))));
+                } else {
+                    // detect interceptor bindings on nested classes
+                    for (DotName interceptorBinding : interceptorResolverBuildItem.getInterceptorBindings()) {
```
Comment (mkouba) [inline extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/WrongAnnotationUsageProcessor.java:96]: We should rather use `io.quarkus.arc.processor.Annotations.containsAny(Collection<AnnotationInstance>, Iterable<DotName>)` with the transformed annotations (i.e. `classAnnotations`) as the first argument and `interceptorResolverBuildItem.getInterceptorBindings()` as the second argument.

Comment (manovotn) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/WrongAnnotationUsageProcessor.java]: Using `classAnnotations` isn't enough as those are only for class-level annotation and we need method-level as well. I have combined the two approaches.

**Review by mkouba — APPROVED** [review]
