### PR TITLE
Ensure REST Data Panache updates happens in a single transaction

### LINKED ISSUE #15369: Panache Data REST: Update method requires at least two connections
**Describe the bug**
I have a resource called:

```java
public interface ApplicationResource extends PanacheEntityResource<ApplicationEntity, Long> {
}
```

This endpoint exposes all the REST methods. The problem is that the PUT method (update) requires a minimal of two connections. So, if we limit the amount of connections using this property:

```
quarkus.datasource.jdbc.max-size=1
```

The update method will fail with:

```
Caused by: org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:47)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:111)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:138)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.connection(StatementPreparerImpl.java:50)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:149)
```

This is a regression issue that was entered as part of this commit: https://github.com/quarkusio/quarkus/commit/8c76e39060f6b288eaaeeb28bc477b33a972a40f. In this commit, the `@Transactional` annotations were removed from the REST methods and added into the inner methods. The problem with the update implementation is that is calling two inner methods (get and update). 

**Expected behavior**
All REST methods should use only one connection.

**Actual behavior**
PUT REST method needs at least two connections.

**To Reproduce**
1- git clone `https://github.com/Sgitario/beefy-scenarios`
2- cd beefy-scenarios/014-quarkus-panache-with-transactions-xa
3- git checkout reproducer_15369
4-mvn clean install (it needs to have built quarkus master locally)

This example is basically doing this:

1. Create a resource
2. Update the existing resource -> here it fails

**Environment (please complete the following information):**
 - Quarkus version or git rev: 999-SNAPSHOT (1.12.1.Final)

### PR DESCRIPTION
**Pull request by gytis**
A couple of weeks ago I've removed the @Transactional annotations from the generated JAX-RS resource methods and added them on the RestDataPanache resources that perform data access and modification operations. However, this caused an update endpoint to execute two transactions: one for checking if an entity exists and another to update it. I removed the annotation from the JAX-RS in order to be able to wrap all exceptions (including transaction exceptions) in a custom exception to allow custom error mapping. Therefore, I didn't want to bring it back. 
In order to work around this issue I've added a `TransactionalExecutor` bean which takes an instance that implements a functional interface and executes it inside a transaction. I thought that this approach is clearer that a bean managed transaction.

fixes https://github.com/quarkusio/quarkus/issues/15369

### CODE REVIEW

File: extensions/panache/rest-data-panache/runtime/src/main/java/io/quarkus/rest/data/panache/runtime/jta/TransactionalExecutor.java [hunk 1]
```diff
@@ -0,0 +1,15 @@
+package io.quarkus.rest.data.panache.runtime.jta;
+
+import java.util.function.Supplier;
+
+import javax.enterprise.context.ApplicationScoped;
+import javax.transaction.Transactional;
+
+@ApplicationScoped
```
Comment (geoand) [inline extensions/panache/rest-data-panache/runtime/src/main/java/io/quarkus/rest/data/panache/runtime/jta/TransactionalExecutor.java:8]: Can this be made `@Singleton`?
We generally prefer it as it has less overhead. If it can't, no worries

Comment (gytis) [reply extensions/panache/rest-data-panache/runtime/src/main/java/io/quarkus/rest/data/panache/runtime/jta/TransactionalExecutor.java:8]: It can. I'll change it.

**Comment by geoand** [comment]
Hm...

It seems like now there are a bunch of conflicts because I merged your other PR

**Comment by gytis** [comment]
Yes that was expected. I had an identical test in another PR that was merged this morning. I'll rebase it.

**Review by geoand — APPROVED** [review]
