### PR TITLE
Mark UBI9_JAVA25 as containsJavaRun

### LINKED ISSUE #53786: Latest LTS and Java 25 -  jib container entrypoint changed from run-java.sh regardless of aot or jar type
### Describe the bug

In the latest lts 3.33.1 buliding a container image with the Jib extension and JDK25 the container entrypoint changed from run-java.sh to java -jar etc regadless of setting any aot or jar type. This seems to be caused by the containsRunJava in the JibProcessor which doesn't have a case for UBI9_JAVA_25_IMAGE_NAME, which does have a run-java.sh. 
I think this might lose any container memory optimization that we get from the run-java.sh.

### Expected behavior

Building a container using jib on java 25 would use the run-java.sh entrypoint (unless using aot).

### Actual behavior

The entrypoint is set to:
            "java",
            "-Djava.util.logging.manager=org.jboss.logmanager.LogManager",
            "-jar",
            "quarkus-run.jar"

And theres no JAVA_APP_DIR env var defined.

### How to Reproduce?

Build a container image using jib on java 25.

### Output of `uname -a` or `ver`

25.4.0 Darwin Kernel Version 25.4.0:

### Output of `java -version`

openjdk version "25.0.1" 2025-10-21 LTS

### Quarkus version or git rev

3.33.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 9.3.1

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by tomas1885**
Adding UBI9_JAVA25 to containerJavaRun in JibProcessor so it would default to the java-run.sh entrypoint.

* Fixes #53786

### CODE REVIEW

**Review by gsmet — COMMENTED** [review]
Good catch and thanks for the PR.

I think this is a good sign this approach doesn't scale very well :).

I think we should have a `Pattern` in `ContainerImages`  that matches all of them and use that. I would even make the `-runtime` part optional and make sure we support UBI 10 and beyond.

Would you be up for it?

**Comment by tomas1885** [comment]
@gsmet I guess it depends on whether UBI 10 plan on supporting java-run.sh no?

**Comment by gsmet** [comment]
@tomas1885 yes, I can confirm that I expect all UBI OpenJDK images to contain this script for the foreseeable future thus why I was pushing for a regexp.

**Comment by tomas1885** [comment]
@gsmet I think that the -runtime suffix should still be used, otherwise s2i base images would also start using the run-java.sh entrypoint, right now they are not included in the containsJavaRun check, am I missing something?

**Comment by gsmet** [comment]
My idea was to catch `registry.access.redhat.com/ubi[0-9]+/openjdk-[0-9]+(-runtime)?`. So I don't think s2i images would get impacted?

**Comment by tomas1885** [comment]
@gsmet How about something like this?
Pattern.compile("^registry\\.access\\.redhat\\.com/ubi\\d+/openjdk-\\d+-runtime(?::[\\w.\\-]+)?$");
So optional image tags would also match?

**Comment by geoand** [comment]
Sounds reasonable to me

**Comment by gsmet** [comment]
Looks good!

**Comment by tomas1885** [comment]
@gsmet I squashed rebased and update the PR with the regex pattern

File: extensions/container-image/container-image-jib/deployment/src/main/java/io/quarkus/container/image/jib/deployment/JibProcessor.java [hunk 1]
```diff
@@ -107,6 +108,7 @@ public class JibProcessor {
     // The source for this can be found at https://github.com/jboss-container-images/openjdk/blob/ubi9/modules/run/artifacts/opt/jboss/container/java/run/run-java.sh
     // A list of env vars that affect this script can be found at https://rh-openjdk.github.io/redhat-openjdk-containers/ubi9/ubi9-openjdk-17.html
     private static final String RUN_JAVA_PATH = "/opt/jboss/container/java/run/run-java.sh";
+    private static final Pattern RUN_JAVA_IMAGE_MATCHER = Pattern.compile("^registry\\.access\\.redhat\\.com/ubi\\d+/openjdk-\\d+-runtime(?::[\\w.\\-]+)?$");
```
Comment (gsmet) [inline extensions/container-image/container-image-jib/deployment/src/main/java/io/quarkus/container/image/jib/deployment/JibProcessor.java]: As I previously mentioned, I think it would be a good idea to have this constant in `ContainerImages`. I don't expect this to change but who knows. And it will be easier to think about it if one day it goes.

I would add it at the top of the runtime section here: https://github.com/quarkusio/quarkus/blob/07db4826323d7fb956778c2dc9278f586469b377/core/deployment/src/main/java/io/quarkus/deployment/images/ContainerImages.java#L75 .

**Review by gsmet — COMMENTED** [review]
Thanks I added a small comment inline.

File: extensions/container-image/container-image-jib/deployment/src/main/java/io/quarkus/container/image/jib/deployment/JibProcessor.java (hunk 1 above)
Comment (gsmet) [reply extensions/container-image/container-image-jib/deployment/src/main/java/io/quarkus/container/image/jib/deployment/JibProcessor.java]: BTW, this above points to the right line if you click on the link :).

Comment (tomas1885) [reply extensions/container-image/container-image-jib/deployment/src/main/java/io/quarkus/container/image/jib/deployment/JibProcessor.java]: @gsmet Are you sure it should be in the ContainerImages.java? Only the JibProcessor actually inspects the container image name. And if the answer is yes, does the whole containerJavaRun method should be there or only the pattern?

Comment (geoand) [reply extensions/container-image/container-image-jib/deployment/src/main/java/io/quarkus/container/image/jib/deployment/JibProcessor.java]: I assume @gsmet proposed it as it makes it easier to look at one place when checking which constants to update. I guess we could move the entire `containerJavaRun` method

Comment (gsmet) [reply extensions/container-image/container-image-jib/deployment/src/main/java/io/quarkus/container/image/jib/deployment/JibProcessor.java]: Yeah, the thing is that we will never think about updating the Jib thing when we change the images.

All this machinery has nothing to do with Jib, it's all about the images so as long as it's totally generic, I think we'd better move it in an area where we will think about it next time we update the images.

The fact that it's only used by Jib is not that important and it could change in the future.

As long as this is solely related to the images and their content, I think we can move it to ContainerImages. My point is that I would like us to avoid missing this the next time we have to change something significant in the images. It's obviously easy to miss given we missed it :)

Comment (tomas1885) [reply extensions/container-image/container-image-jib/deployment/src/main/java/io/quarkus/container/image/jib/deployment/JibProcessor.java]: So should I move the whole containsJavaRun to the ContainerImages? The method naming does convey the purpose

Comment (gsmet) [reply extensions/container-image/container-image-jib/deployment/src/main/java/io/quarkus/container/image/jib/deployment/JibProcessor.java]: Yeah it's probably a good idea.

Sorry it's so painful but the idea is to avoid getting the same issue next time.

Thanks for your patience!

**Review by geoand — DISMISSED** [review]
Thanks!

**Comment by tomas1885** [comment]
When I run the formatter:format I get more changes than expected in the JibProcessor

**Comment by geoand** [comment]
You could run `mvn process-source T 1C` to get the formatter to run for the entire project.

In any case, please squash the commits when you are done

**Comment by tomas1885** [comment]
@geoand I squashed it

**Review by geoand — DISMISSED** [review]
Thanks!

**Comment by tomas1885** [comment]
Sorry I formatted the other change and squash now

**Review by geoand — DISMISSED** [review]

**Review by gsmet — DISMISSED** [review]
Perfect, thanks a lot!

**Review by geoand — APPROVED** [review]
