### PR TITLE
Remove customizer mappings from runtime recording Config

### LINKED ISSUE #44246: Runtime property being resolved at build time
### Describe the bug

Some configuration properties which are supposed to be resolved at runtime are being resolved at build time, resulting in build errors when referencing runtime properties such as `user.home`. This appears to be a regression on main and does not affect the released version 3.15.1.

### Expected behavior

`quarkus.log.file.path` is resolved at runtime.

### Actual behavior

`quarkus.log.file.path` is resolved at build time.

### How to Reproduce?

Reproducer: [quarkus-reproducer.zip](https://github.com/user-attachments/files/17595956/quarkus-reproducer.zip)

**Steps to reproduce**

Add or edit this line in `application.properties`:

```
quarkus.log.file.path=${user.home}/quarkus-reproducer.log
```

Run `./gradlew quarkusAppPartsBuild`.

The following error is reported:

```
> Task :quarkusAppPartsBuild FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':quarkusAppPartsBuild'.
> There was a failure while executing work items
   > A failure occurred while executing io.quarkus.gradle.tasks.worker.BuildWorker
      > Configuration validation failed:
                java.util.NoSuchElementException: SRCFG00011: Could not expand value user.home in property quarkus.log.file.path
```

### Output of `uname -a` or `ver`

Darwin Rods-MacBook-Pro.local 24.0.0 Darwin Kernel Version 24.0.0: Tue Sep 24 23:35:10 PDT 2024; root:xnu-11215.1.12~1/RELEASE_ARM64_T6031 arm64

### Output of `java -version`

openjdk version "21.0.4" 2024-07-16 OpenJDK Runtime Environment Homebrew (build 21.0.4) OpenJDK 64-Bit Server VM Homebrew (build 21.0.4, mixed mode, sharing)

### Quarkus version or git rev

e81fa0c828aab38ffb50a0adf61aacb6d376c43c

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.9

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by radcortez**
- Fixes #44246

Caused by #42157.

In #42157, we added https://github.com/radcortez/quarkus/blob/9eff425f2b6ad59e6e205b736ce2611417971d60/core/deployment/src/main/java/io/quarkus/deployment/configuration/BuildTimeConfigBuilderCustomizer.java to register the log config which is required in both build time and runtime.

The customizer now applies to the stripped-down version of a config instance we use to record configuration (where we have to remove the system sources):
https://github.com/quarkusio/quarkus/blob/ada7e07ff98abf80371b5f58ebf4bd8e482816a6/core/deployment/src/main/java/io/quarkus/deployment/configuration/BuildTimeConfigurationReader.java#L1101-L1110

This instance does not require any mappings at all, and it is only used to query configuration names to proceed with the recording.

### CODE REVIEW

File: core/deployment/src/main/java/io/quarkus/deployment/configuration/BuildTimeConfigurationReader.java [hunk 1]
```diff
@@ -1112,6 +1113,17 @@ private SmallRyeConfig getConfigForRuntimeRecording() {
             builder.getProfiles().add("");
             builder.getSources().clear();
             builder.getSourceProviders().clear();
+            builder.withCustomizers(new SmallRyeConfigBuilderCustomizer() {
```
Comment (gsmet) [inline core/deployment/src/main/java/io/quarkus/deployment/configuration/BuildTimeConfigurationReader.java:1116]: Could you clarify how the customizers could have registered `quarkus.log.file.path`?

**Review by gsmet — APPROVED** [review]
