### PR TITLE
Fix CDI app context lifecycle events

### LINKED ISSUE #1433: Incorrect behaviour for @ApplicationScoped lifecycle events
To `application-lifecycle-events/src/main/java/org/acme/events/AppLifecycleBean.java` add methods
```
    public void init (@Observes @Initialized(ApplicationScoped.class) Object init) {
        LOGGER.info("Init");
    }

    public void shutdown(@Observes @Destroyed(ApplicationScoped.class) Object init) {
        LOGGER.info("Shutdown");
    }
```

The result of quickstart is
```
2019-03-12 15:31:42,224 INFO  [ListenerBean] (main) Shutdown
2019-03-12 15:31:42,224 INFO  [ListenerBean] (main) Init
2019-03-12 15:31:42,368 INFO  [ListenerBean] (main) Shutdown
2019-03-12 15:31:42,368 INFO  [ListenerBean] (main) Init
2019-03-12 15:31:42,369 INFO  [ListenerBean] (main) The application is starting...hello
```
Please note that both shutdown and init methods were called multiple times and shutdown was call even before the application was started.

### PR DESCRIPTION
**Pull request by mkouba**
- resolves #1433

### CODE REVIEW

File: independent-projects/arc/runtime/src/main/java/io/quarkus/arc/ArcContainerImpl.java [hunk 1]
```diff
@@ -247,8 +249,18 @@ synchronized void shutdown() {
...
                 arcCdi.destroy();
             }
+            // Fire an event with qualifier @BeforeDestroyed(ApplicationScoped.class)
+            Set<Annotation> beforeDestroyQualifiers = new HashSet<>(4);
+            beforeDestroyQualifiers.add(BeforeDestroyed.Literal.APPLICATION);
+            beforeDestroyQualifiers.add(Any.Literal.INSTANCE);
+            EventImpl.createNotifier(Object.class, Object.class, beforeDestroyQualifiers, this).notify(toString());
             // Destroy contexts
             applicationContext.destroy();
+            // Fire an event with qualifier @BeforeDestroyed(ApplicationScoped.class)
```
Comment (Ladicek) [inline independent-projects/arc/runtime/src/main/java/io/quarkus/arc/ArcContainerImpl.java]: `@BeforeDestroyed` -> `@Destroyed` :-)

Comment (mkouba) [reply independent-projects/arc/runtime/src/main/java/io/quarkus/arc/ArcContainerImpl.java]: Thanks! :-)

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanProcessor.java [hunk 2]
```diff
@@ -240,6 +243,9 @@ private static IndexView addBuiltinClasses(IndexView index) {
             index(indexer, Default.class.getName());
             index(indexer, Any.class.getName());
             index(indexer, Named.class.getName());
+            index(indexer, Initialized.class.getName());
+            index(indexer, BeforeDestroyed.class.getName());
+            index(indexer, Destroyed.class.getName());
```
Comment (gsmet) [inline independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanProcessor.java]: I suppose you have the full list now but I wonder if it would be more future proof to index the full API jar instead of specifying each element manually?

Comment (mkouba) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanProcessor.java]: Yes, you're right. This is just a temporary fix. We need a better solution because CDI API is not the only jar that could contain qualifiers.

**Comment by mkouba** [comment]
Hm, the build failed with:
```
[ERROR] Failed to execute goal on project quarkus-smallrye-openapi-runtime: Could not resolve dependencies for project io.quarkus:quarkus-smallrye-openapi-runtime:jar:999-SNAPSHOT: Could not transfer artifact com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.9.8 from/to jboss-public-repository-group (http://repository.jboss.org/nexus/content/groups/developer/): Connect to repository.jboss.org:80 timed out -> [Help 1]
```
I'll try to re-run.

**Review by gsmet — APPROVED** [review]
Let's wait for CI.
