### PR TITLE
TestHostLauncher to return the default ListeningAddress

### LINKED ISSUE #52310: RestAssured.baseURI is not set when using `quarkus.http.test-host` after update to Quarkus 3.31
### Describe the bug

[Change ArtifactLauncher.start to return the listening address](https://github.com/quarkusio/quarkus/commit/26e0418fca6d6c1e6a5e23fd4e8b6ce5f0203d4d#diff-323c8ba4b6cc9fda3f5dd03bed7c35e7300c50d9ef984f0d3ae24213308be84e)

introduced following regressions:

test-framework/junit/src/main/java/io/quarkus/test/junit/QuarkusIntegrationTestExtension.java
RestAssuredStateManager.setURL() is only called when state.getListeningAddress() is set.

test-framework/common/src/main/java/io/quarkus/test/common/TestHostLauncher.java
The start method returns Optional.empty().

This means when running QuarkusIntegrationTest against a running application (via quarkus.http.test-host) RestAzzured does use localhost(default) instead of the provided URL.

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by radcortez**
- Fixes #52310

### CODE REVIEW

File: test-framework/common/src/main/java/io/quarkus/test/common/TestHostLauncher.java [hunk 1]
```diff
@@ -15,9 +19,15 @@ public class TestHostLauncher implements ArtifactLauncher {
...
     public Optional<ListeningAddress> start() throws IOException {
+        Config config = ConfigProvider.getConfig();
+        // TODO - Remove this SystemProperty set / get
         // set 'quarkus.http.host' to ensure that RestAssured targets the proper host
         previousHost = System.setProperty("quarkus.http.host", System.getProperty("quarkus.http.test-host"));
-        return Optional.empty();
+
+        // Before https://github.com/quarkusio/quarkus/pull/51367, this assumed it was always http
+        int port = config.getValue("quarkus.http.test-port", OptionalInt.class).orElse(8081);
+        String protocol = "http";
```
Comment (bonneval) [inline test-framework/common/src/main/java/io/quarkus/test/common/TestHostLauncher.java]: Is it possible to support https via `quarkus.http.test-ssl-enabled` as well?

**Review by bonneval — COMMENTED** [review]
Thanks a lot for your effort!

**Review by geoand — APPROVED** [review]

File: test-framework/common/src/main/java/io/quarkus/test/common/TestHostLauncher.java (hunk 1 above)
Comment (gsmet) [reply test-framework/common/src/main/java/io/quarkus/test/common/TestHostLauncher.java]: @radcortez can you answer this one? Ideally, I would like to backport it tonight if possible.

Comment (radcortez) [reply test-framework/common/src/main/java/io/quarkus/test/common/TestHostLauncher.java]: Yes, we can add that.

**Review by gsmet — APPROVED** [review]
Awesome, thanks!
