### PR TITLE
Handle trailing slashes for endpoints with regex path params

### LINKED ISSUE #42687: Reactive REST endpoints do not handle trailing slashes for paths w/ regex
### Describe the bug

When attempting to navigate to endpoints that use regex within the path expression (i.e. `@Path("{somePath:[a-z]{2}}")`), trailing slashes do not properly route to the resource and instead return an error that the path cannot be matched. This impacts any paths that contain regex, not just those ending with regex.

This impacts the Reactive REST `quarkus-resteasy-reactive` package in 3.8, and in quick testing this also impacts the current 3.13.3 release `quarkus-rest` package as well.

This seems to be a regression/missed aspect for the fix associated with https://github.com/quarkusio/quarkus/issues/26016.

### Expected behavior

In cases where there are regex expressions within the `@Path` value, adding trailing slashes to the endpoint should route to the same endpoint.

### Actual behavior

When a trailing slash is present for endpoints that contain a regex in the path, the endpoint doesn't properly route. 

### How to Reproduce?

Using [reproducer project](https://github.com/autumnfound/quarkus-regex-trailing-slashes):

1. With server started, open the following URLs in browser to confirm that endpoints do properly exist + route:
- http://localhost:8080/hello/working/123
- http://localhost:8080/hello/non-working/123
- http://localhost:8080/hello/non-working/123/second-test
2. In browser, open the following links to observe behaviour with trailing slashes
- http://localhost:8080/hello/working/123/
- http://localhost:8080/hello/non-working/123/
- http://localhost:8080/hello/non-working/123/second-test/  

All 3 URLs in step 2 should pass, but only the first link does

### Output of `uname -a` or `ver`

Linux pop-os 6.9.3-76060903-generic #202405300957~1721174657~22.04~abb7c06 SMP PREEMPT_DYNAMIC Wed J x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.11" 2024-04-16 OpenJDK Runtime Environment Temurin-17.0.11+9 (build 17.0.11+9) OpenJDK 64-Bit Server VM Temurin-17.0.11+9 (build 17.0.11+9, mixed mode, sharing)

### Quarkus version or git rev

3.8.5

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae) Maven home: /home/****/bin/apache-maven-3.9.6 Java version: 17.0.11, vendor: Eclipse Adoptium, runtime: /home/****/bin/mandrel-java17-23.0.4.1-Final Default locale: en_CA, platform encoding: UTF-8 OS name: "linux", version: "6.9.3-76060903-generic", arch: "amd64", family: "unix"

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jonomorris**
For Reactive REST endpoints don't include the path end slash when performing regex path param matches.

- Fixes: #42687

### CODE REVIEW

**Comment by gsmet** [comment]
@jonomorris Thanks for the PR! I think the test failures above look related ^

**Comment by jonomorris** [comment]
[gsmet](https://github.com/gsmet) yeah there are some problems, I'll look into it.

**Comment by jonomorris** [comment]
@gsmet and @stuartwdouglas, I made a small update and the unit tests pass locally in `independent-projects/resteasy-reactive` and `extensions/resteasy-reactive`.

**Comment by geoand** [comment]
cc @FroMage

File: independent-projects/resteasy-reactive/server/vertx/src/test/java/org/jboss/resteasy/reactive/server/vertx/test/matching/RegexPathTest.java [hunk 1]
```diff
@@ -0,0 +1,114 @@
...
+        get("/hello/")
+                .then()
+                .statusCode(404);
+
+        get("/hello/1")
+                .then()
+                .statusCode(200)
+                .body(equalTo("Hello! 1"));
+
+        get("/hello/1/")
```
Comment (FroMage) [inline independent-projects/resteasy-reactive/server/vertx/src/test/java/org/jboss/resteasy/reactive/server/vertx/test/matching/RegexPathTest.java:53]: What happens if you do get `/hello/1////`?

File: independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/mapping/RequestMapper.java [hunk 2]
```diff
@@ -76,12 +76,18 @@ private RequestMatch<T> mapFromPathMatcher(String path, PathMatcher.PathMatch<Ar
             for (int i = 1; i < potentialMatch.template.components.length; ++i) {
                 URITemplate.TemplateComponent segment = potentialMatch.template.components[i];
                 if (segment.type == URITemplate.Type.CUSTOM_REGEX) {
-                    Matcher matcher = segment.pattern.matcher(path);
+                    // exclude any path end slash when matching a subdir, but include it in the matched length
+                    boolean endSlash = matchPos < path.length() && path.charAt(path.length() - 1) == '/';
```
Comment (FroMage) [inline independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/mapping/RequestMapper.java:80]: Perhaps we need to consider more than one slash at the end? See my next question for how this behaves for non-regexes.

File: independent-projects/resteasy-reactive/server/vertx/src/test/java/org/jboss/resteasy/reactive/server/vertx/test/matching/RegexPathTest.java (hunk 1 above)
Comment (jonomorris) [reply independent-projects/resteasy-reactive/server/vertx/src/test/java/org/jboss/resteasy/reactive/server/vertx/test/matching/RegexPathTest.java:53]: Intermediate slashes are encoded, for instance the path becomes `/1%2F%2F%2F%2F/`, which doesn't match the regex path matcher `\\d+`.

Comment (FroMage) [reply independent-projects/resteasy-reactive/server/vertx/src/test/java/org/jboss/resteasy/reactive/server/vertx/test/matching/RegexPathTest.java:53]: So, we only alow a single optional slash at the end, then?

Comment (jonomorris) [reply independent-projects/resteasy-reactive/server/vertx/src/test/java/org/jboss/resteasy/reactive/server/vertx/test/matching/RegexPathTest.java:53]: Yes, that's correct.

Comment (FroMage) [reply independent-projects/resteasy-reactive/server/vertx/src/test/java/org/jboss/resteasy/reactive/server/vertx/test/matching/RegexPathTest.java:53]: I'm not sure how I feel about this.
It feels special-casy.

Also, I looked for articles about tailing slashes, and I only find SEO articles that advise to only serve one variant (with, or without).

And last, I've come across this issue https://github.com/spring-projects/spring-framework/issues/28552 where Sprint went the other way around and removed the default of allowing optional trailing slashes by default.

So, I'll ask for more comments from HTTP/REST colleagues who might have a relevant opinion: @cescoffier @vietj:

Do you think we should allow trailing slashes for routes defined without one?

Now, on the other hand, this issue is about fixing the particular difference of assuming a trailing slash for regex paths, so that it's coherent with normal paths, which already assume a trailing slash. And I agree both should be the same. I'm not entirely sure regex matches are right, though, I wonder if non-regex path matching might be in the wrong here and the one that needs fixing. WDYT @geoand ?

Comment (geoand) [reply independent-projects/resteasy-reactive/server/vertx/src/test/java/org/jboss/resteasy/reactive/server/vertx/test/matching/RegexPathTest.java:53]: > And I agree both should be the same. I'm not entirely sure regex matches are right, though, I wonder if non-regex path matching might be in the wrong here and the one that needs fixing. WDYT @geoand ?

I really have not looked at it at all, so I trust you completely on this one

Comment (cescoffier) [reply independent-projects/resteasy-reactive/server/vertx/src/test/java/org/jboss/resteasy/reactive/server/vertx/test/matching/RegexPathTest.java:53]: /foo and /foo/ are not equivalent. They refer to different resources due to the trailing slash:

* /foo refers to a resource.
* /foo/ often suggests that it’s a collection or directory-like structure containing resources.

Comment (FroMage) [reply independent-projects/resteasy-reactive/server/vertx/src/test/java/org/jboss/resteasy/reactive/server/vertx/test/matching/RegexPathTest.java:53]: So @cescoffier you're saying we should change the current behaviour of Quarkus REST to not treat these as the same when routing?

I suppose making the change and running the TCK will tell us what JAX-RS thinks about that :)

Comment (cescoffier) [reply independent-projects/resteasy-reactive/server/vertx/src/test/java/org/jboss/resteasy/reactive/server/vertx/test/matching/RegexPathTest.java:53]: That's the problem - many servers consider them equivalent, but the "theory" says they are not.

Comment (jonomorris) [reply independent-projects/resteasy-reactive/server/vertx/src/test/java/org/jboss/resteasy/reactive/server/vertx/test/matching/RegexPathTest.java:53]: There was a similar conversation here https://github.com/quarkusio/quarkus/issues/26016#issuecomment-1152953876

Comment (FroMage) [reply independent-projects/resteasy-reactive/server/vertx/src/test/java/org/jboss/resteasy/reactive/server/vertx/test/matching/RegexPathTest.java:53]: Well, OK, so the TCK did not test this, and the spec says we have to treat them equivalent. Probably people rely on that now, so let's just harmonize and make sure regexes also behave in a similar way, and if we want to change the default later, we'll wait for users reporting an issue and revisit if required, for both regular and regex.

**Review by FroMage — APPROVED** [review]

**Comment by FroMage** [comment]
Agreed @cescoffier @geoand ?

**Comment by jorsol** [comment]
Will this fix match more complex regex like in https://github.com/quarkusio/quarkus/issues/44242?

**Review by jorsol — APPROVED** [review]

**Comment by jorsol** [comment]
Can this be backported to 3.15 too? 🙏🏽

**Comment by geoand** [comment]
New features do not get backported to LTS releases

**Comment by geoand** [comment]
Forgot about this one, sorry.

Can the PR be rebased on main so we can get a recent CI run?

**Comment by geoand** [comment]
@FroMage mind taking a last peak to make sure nothing changed?

**Review by FroMage — APPROVED** [review]
LGTM, let's see how this pans out

**Comment by geoand** [comment]
Perhaps down the line when this patch has been stress tested by later non LTS versions
