### PR TITLE
AWT Extension, Decoders, Encoders, Geometry and Fonts

### LINKED ISSUE #8605: Evaluate ImageIO compatibility with GraalVM Native Image
**Describe the bug**
ImageIO is now enabled in Quarkus 1.4.0. 
https://github.com/quarkusio/quarkus/pull/8453

However, not all is good, as ImageIO has a plugin architecture and not all plugins work that are normally installed in the JRE, such as `com.sun.imageio.plugins.jpeg.JPEGImageReader`

According to the comment in this thread, PNGImageReader is working, however:
https://stackoverflow.com/questions/60527663/is-javax-imageio-supported-by-graalvm-native-image

**Expected behavior**
All ImageIO plugins work.

**Actual behavior**
Unknown how many plugins work by default with Native Image, or if the GraalVM is tracking.

**To Reproduce**
1. Try using ImageIO.read on a JPEG
2. Observe java.lang.UnsatisfiedLinkError: com.sun.imageio.plugins.jpeg.JPEGImageReader

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: 11
 - GraalVM version (if different from Java): 20.0.0
 - Quarkus version or git rev: 1.4.0.CR1
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 

**Additional context**

This is a GraalVM issue, but filing at the request of George Gastaldi.

### LINKED ISSUE #12393: Implement graphics for JAXB
**Description**
I've implemented camel-quarkus extension for FOP (https://github.com/apache/camel-quarkus/tree/master/extensions/fop2).

I ran into following error using native-image:
>java.lang.UnsupportedOperationException: Not implemented yet for GraalVM native images
	at sun.java2d.cmm.lcms.LCMS.getTagNative(LCMS.java:28)
	at sun.java2d.cmm.lcms.LCMSProfile$TagCache.getTag(LCMSProfile.java:70)
	at sun.java2d.cmm.lcms.LCMSProfile.getTag(LCMSProfile.java:51)
	at sun.java2d.cmm.lcms.LCMS.getTagSize(LCMS.java:88)
	at java.awt.color.ICC_Profile.getData(ICC_Profile.java:1355)
	at java.awt.color.ICC_Profile.getData(ICC_Profile.java:1343)
	at org.apache.xmlgraphics.java2d.color.profile.ColorProfileUtil.getICCProfileDescription(ColorProfileUtil.java:46)
	at org.apache.fop.pdf.PDFResources.addColorSpace(PDFResources.java:160)
	at org.apache.fop.pdf.PDFFactory.makeICCBasedColorSpace(PDFFactory.java:1550)
	at org.apache.fop.pdf.PDFICCBasedColorSpace.setupsRGBAsDefaultRGBColorSpace(PDFICCBasedColorSpace.java:116)
	at org.apache.fop.render.pdf.PDFRenderingUtil.addsRGBColorSpace(PDFRenderingUtil.java:187)
	at org.apache.fop.render.pdf.PDFRenderingUtil.setupPDFDocument(PDFRenderingUtil.java:604)
	at org.apache.fop.render.pdf.PDFDocumentHandler.startDocument(PDFDocumentHandler.java:159)
	at org.apache.fop.render.intermediate.util.IFDocumentHandlerProxy.startDocument(IFDocumentHandlerProxy.java:105)
	at org.apache.fop.render.intermediate.IFRenderer.startRenderer(IFRenderer.java:263)
	at org.apache.fop.area.RenderPagesModel.<init>(RenderPagesModel.java:81)
	at org.apache.fop.area.AreaTreeHandler.setupModel(AreaTreeHandler.java:135)
	at org.apache.fop.area.AreaTreeHandler.<init>(AreaTreeHandler.java:105)
	at org.apache.fop.render.RendererFactory.createFOEventHandler(RendererFactory.java:363)
	at org.apache.fop.fo.FOTreeBuilder.<init>(FOTreeBuilder.java:107)
	at org.apache.fop.apps.Fop.createDefaultHandler(Fop.java:104)
	at org.apache.fop.apps.Fop.<init>(Fop.java:78)
	at org.apache.fop.apps.FOUserAgent.newFop(FOUserAgent.java:182)
	at org.apache.fop.apps.FopFactory.newFop(FopFactory.java:239)
	at org.apache.camel.component.fop.FopProducer.transform(FopProducer.java:92)

I've issued bug for graal VM (https://github.com/oracle/graal/issues/2850), but then I was corrected, that issue is not caused by graal VM but by quarkus.

Disabled feature could be seen **here** - https://github.com/quarkusio/quarkus/pull/3246/files#diff-0e389a06405b679615dee1750de18d4eR15

Would it be possible to implement this feature?

**Steps to simulate the missing feature**

You can use integration test in camel-quarkus fop extension - https://github.com/apache/camel-quarkus/blob/master/integration-tests/fop/src/test/java/org/apache/camel/quarkus/component/fop/it/FopTest.java
To make test fail with the reported `UnsupportdOperationException`, you have to change value in substitution to `false` (https://github.com/apache/camel-quarkus/blob/master/extensions/fop/runtime/src/main/java/org/apache/camel/quarkus/component/fop/PDFRendererOptionsConfigSubstitution.java#L29)

### LINKED ISSUE #12972: Quarkus-native failure: Can't load standard profile: GRAY.pf
**Describe the bug**
During implementation of camel-quarkus extension of camel-barcode, I've faced an issue linked to awt profile: `Can't load standard profile: GRAY.pf`

**Expected behavior**
No error is happening and profile is loaded.

**Actual behavior**
See reproducer. Stacktrace of the exception is:
>2020-10-27 10:25:19,819 ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): java.lang.IllegalArgumentException: Can't load standard profile: GRAY.pf
	at java.awt.color.ICC_Profile$2.run(ICC_Profile.java:942)
	at java.awt.color.ICC_Profile$2.run(ICC_Profile.java:936)
	at java.security.AccessController.doPrivileged(AccessController.java:83)
	at java.awt.color.ICC_Profile.getStandardProfile(ICC_Profile.java:935)
	at java.awt.color.ICC_Profile.getDeferredInstance(ICC_Profile.java:1067)
	at java.awt.color.ICC_Profile.getInstance(ICC_Profile.java:902)
	at java.awt.color.ColorSpace.getInstance(ColorSpace.java:333)
	at javax.imageio.ImageTypeSpecifier$Grayscale.<init>(ImageTypeSpecifier.java:604)
	at javax.imageio.ImageTypeSpecifier.createGrayscale(ImageTypeSpecifier.java:685)
	at javax.imageio.ImageTypeSpecifier.createSpecifier(ImageTypeSpecifier.java:1211)
	at javax.imageio.ImageTypeSpecifier.getSpecifier(ImageTypeSpecifier.java:1118)
	at javax.imageio.ImageTypeSpecifier.createFromRenderedImage(ImageTypeSpecifier.java:931)
	at javax.imageio.ImageIO.getWriter(ImageIO.java:1608)
	at javax.imageio.ImageIO.write(ImageIO.java:1594)
	at com.google.zxing.client.j2se.MatrixToImageWriter.writeToStream(MatrixToImageWriter.java:159)
	at com.google.zxing.client.j2se.MatrixToImageWriter.writeToStream(MatrixToImageWriter.java:144)
	at org.acme.commandmode.HelloCommando.run(HelloCommando.java:36)
	at org.acme.commandmode.HelloCommando_ClientProxy.run(HelloCommando_ClientProxy.zig:157)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:115)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:62)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:30)

**To Reproduce**

Here is a simple roproducer: https://github.com/JiriOndrusek/cannot-find-gray-pf-reproducer
Dev mode works correctly, but native mode fails with above exception.

**Additional context**
I was looking into some graalvm jdks for java 8 and there was a file `/jre/lib/cmm/GRAY.pf` which is not present in graalvm jdk for java 11. But the same problem is happening if **graalvm-ce-java8-20.2.0** is used, so there is probably no influence.
But just the fact that file existin graalvm-ce-java8-20.2.0, shows that it should work.

### LINKED ISSUE #13567: Support AWT Image IO in native image
An extension, new or existing, should add the following to support AWT Image IO in native image. See attached JSON files containing write and read registration registrations.

[imageio-read-native-image-config.zip](https://github.com/quarkusio/quarkus/files/5617323/imageio-read-native-image-config.zip)
[imageio-write-native-image-config.zip](https://github.com/quarkusio/quarkus/files/5617328/imageio-write-native-image-config.zip)

### LINKED ISSUE #20565: Enable watermarking images, fonts rendering and all JDK supported image formats in AWT Extension
### Description

Use case:
 - watermarking images
 - drawing, server side generated graphics

Status:
 - polishing an update into a PR
 - wrapping up a new quickstart to open a PR in https://github.com/quarkusio/quarkus-quickstarts too

WIP:
Done means there is a suite of rigorous tests exercising the relevant code paths, e.g. for encoders only it's 964 test cases of image type:image format:colour space:compression.

- [x] Showcase in a Quick start: [awt-graphics-rest-quickstart](https://github.com/Karm/quarkus-quickstarts/tree/quarkus-awt/awt-graphics-rest-quickstart/#readme) (needs not yet published AWT extension update)
- [x] TIFF Decoder; all compressors; metadata
- [x] TIFF Encoder; all compressors; metadata; multiple images in a container
- [x] PNG Decoder; all compressors; layers; metadata
- [x] PNG Encoder; all compressors; metadata
- [x] GIF Decoder; all compressors; animations; metadata
- [x] GIF Encoder; all compressors; metadata
- [x] JPEG Decoder; metadata
- [x] JPEG Encoder; metadata
- [x] BMP Decoder; all compressors; metadata
- [x] BMP Encoder; all compressors; (metadata immutable, so just the default)
- [x] WBMP Decoder; metadata
- [x] WBMP Encoder; (metadata immutable, so just the default)
- [x] Fonts, both embedded and loading one's own: It's done in the aforementioned Quick start, I just need to do some streamlined copy-pasting :) to the extension's integration tests.
- [x] Geometry, full Java2D suite, building on the foundation I have in [/mandrel-integration-tests](https://github.com/Karm/mandrel-integration-tests/tree/master/apps/imageio)
- [x] Rinse and repeat on JDK 17 as all the above work is being done with JDK 11.0.13 ea.
- [x] Rinse and repeat on Windows, which will bring some additional changes. All the aforementioned work in being done on Linux.
- [x] README me for the test suite
- [x] Docs for the extension 

Implementation affects:
 - recent awt extension
 - core, switching Quarkus to be headless by default , i.e.
```diff
@@ -52,6 +52,13 @@ public class NativeConfig {
     @ConfigItem(defaultValue = "true")
     public boolean enableJni;
 
+    /**
+     * The default value for java.awt.headless JVM option.
+     * Switching this option affects linking of awt libraries.
+     */
+    @ConfigItem(defaultValue = "true")
+    public boolean headless;
+
...
@@ -597,6 +597,10 @@ public class NativeImageBuildStep {
                 nativeImageArgs.add("-H:+JNI");
                 nativeImageArgs.add("-H:+AllowFoldMethods");
 
+                if (nativeConfig.headless) {
+                    nativeImageArgs.add("-J-Djava.awt.headless=true");
+                }
+
```

### Implementation ideas

@gastaldi Assign the issue to me, please.

### LINKED ISSUE #21726: Graalvm native Compile Error
### Describe the bug

Graalvm native compile error after upgrading to `2.5.0.Final`, `2.4.1.Final` is ok.

```log
[qunar-wh-policy-sync-bin:1603]    classlist:   2,945.80 ms,  0.96 GB
[qunar-wh-policy-sync-bin:1603]        (cap):   1,630.65 ms,  0.96 GB
[qunar-wh-policy-sync-bin:1603]        setup:   3,156.07 ms,  0.96 GB
16:09:03,286 INFO  [org.jbo.threads] JBoss Threads version 3.4.2.Final
[qunar-wh-policy-sync-bin:1603]     (clinit):   1,317.19 ms,  5.88 GB
[qunar-wh-policy-sync-bin:1603]   (typeflow):   8,025.14 ms,  5.88 GB
[qunar-wh-policy-sync-bin:1603]    (objects):  36,579.45 ms,  5.88 GB
[qunar-wh-policy-sync-bin:1603]   (features):  15,439.03 ms,  5.88 GB
[qunar-wh-policy-sync-bin:1603]     analysis:  64,534.34 ms,  5.88 GB
[qunar-wh-policy-sync-bin:1603]     universe:   3,537.22 ms,  5.88 GB
[qunar-wh-policy-sync-bin:1603]      (parse):  12,050.41 ms,  5.56 GB
[qunar-wh-policy-sync-bin:1603]     (inline):  20,814.87 ms,  6.39 GB
[qunar-wh-policy-sync-bin:1603]    (compile):  44,066.67 ms,  6.33 GB
[qunar-wh-policy-sync-bin:1603]      compile:  81,027.26 ms,  6.33 GB
[qunar-wh-policy-sync-bin:1603]        image:   5,066.49 ms,  6.33 GB
[qunar-wh-policy-sync-bin:1603]        write:   1,223.43 ms,  6.33 GB
Fatal error:java.lang.RuntimeException: There was an error linking the native image: Linker command exited with 1

Based on the linker command output, possible reasons for this include:
1. It appears as though libfreetype.a is missing. Please install it.

Linker command executed:
/usr/bin/gcc -z noexecstack -Wl,--gc-sections -Wl,--dynamic-list -Wl,/tmp/SVM-16506476398039308040/exported_symbols.list -Wl,--exclude-libs,ALL -Wl,-x -o /mnt/d/IdeaProjects/zlzl/ota-q
unar-policy/qunar-wh-policy-sync/target/qunar-wh-policy-sync-native-image-source-jar/qunar-wh-policy-sync-bin qunar-wh-policy-sync-bin.o /mnt/d/Java/graalvm-ce-java17-linux-21.3.0/lib/
static/linux-amd64/glibc/libnet.a /mnt/d/Java/graalvm-ce-java17-linux-21.3.0/lib/static/linux-amd64/glibc/libjavajpeg.a /mnt/d/Java/graalvm-ce-java17-linux-21.3.0/lib/static/linux-amd6
4/glibc/libextnet.a /mnt/d/Java/graalvm-ce-java17-linux-21.3.0/lib/static/linux-amd64/glibc/libnio.a /mnt/d/Java/graalvm-ce-java17-linux-21.3.0/lib/svm/clibraries/linux-amd64/liblibche
lper.a /mnt/d/Java/graalvm-ce-java17-linux-21.3.0/lib/static/linux-amd64/glibc/libjava.a /mnt/d/Java/graalvm-ce-java17-linux-21.3.0/lib/static/linux-amd64/glibc/liblcms.a /mnt/d/Java/g
raalvm-ce-java17-linux-21.3.0/lib/static/linux-amd64/glibc/libfontmanager.a /mnt/d/Java/graalvm-ce-java17-linux-21.3.0/lib/static/linux-amd64/glibc/libawt_headless.a /mnt/d/Java/graalv
m-ce-java17-linux-21.3.0/lib/static/linux-amd64/glibc/libawt.a /mnt/d/Java/graalvm-ce-java17-linux-21.3.0/lib/static/linux-amd64/glibc/libfdlibm.a /mnt/d/Java/graalvm-ce-java17-linux-2
1.3.0/lib/static/linux-amd64/glibc/libzip.a /mnt/d/Java/graalvm-ce-java17-linux-21.3.0/lib/svm/clibraries/linux-amd64/libjvm.a -v -L/tmp/SVM-16506476398039308040 -L/mnt/d/Java/graalvm-
ce-java17-linux-21.3.0/lib/static/linux-amd64/glibc -L/mnt/d/Java/graalvm-ce-java17-linux-21.3.0/lib/svm/clibraries/linux-amd64 -lstdc++ -lm -lfreetype -lpthread -ldl -lz -lrt -no-pie

Linker command output:
Using built-in specs.
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.3.0-17ubuntu1~20.04' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortr
an,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --
without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=ne
w --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --d
isable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-9-HskZEa/gcc-9-9
.3.0/debian/tmp-nvptx/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)
COMPILER_PATH=/usr/lib/gcc/x86_64-linux-gnu/9/:/usr/lib/gcc/x86_64-linux-gnu/9/:/usr/lib/gcc/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/9/:/usr/lib/gcc/x86_64-linux-gnu/
LIBRARY_PATH=/usr/lib/gcc/x86_64-linux-gnu/9/:/usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/:/lib/x86_64-linux-gnu/:/lib/..
/lib/:/usr/lib/x86_64-linux-gnu/:/usr/lib/../lib/:/usr/lib/gcc/x86_64-linux-gnu/9/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-z' 'noexecstack' '-o' '/mnt/d/IdeaProjects/zlzl/ota-qunar-policy/qunar-wh-policy-sync/target/qunar-wh-policy-sync-native-image-source-jar/qunar-wh-policy-sync-bin
' '-v' '-L/tmp/SVM-16506476398039308040' '-L/mnt/d/Java/graalvm-ce-java17-linux-21.3.0/lib/static/linux-amd64/glibc' '-L/mnt/d/Java/graalvm-ce-java17-linux-21.3.0/lib/svm/clibraries/li
nux-amd64' '-no-pie' '-mtune=generic' '-march=x86-64'
 /usr/lib/gcc/x86_64-linux-gnu/9/collect2 -plugin /usr/lib/gcc/x86_64-linux-gnu/9/liblto_plugin.so -plugin-opt=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper -plugin-opt=-fresolution=/tmp
/cc5yzrm1.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s --build-
id --eh-frame-hdr -m elf_x86_64 --hash-style=gnu --as-needed -dynamic-linker /lib64/ld-linux-x86-64.so.2 -z relro -o /mnt/d/IdeaProjects/zlzl/ota-qunar-policy/qunar-wh-policy-sync/targ
et/qunar-wh-policy-sync-native-image-source-jar/qunar-wh-policy-sync-bin -z noexecstack /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/crt1.o /usr/lib/gcc/x86_64-linux-gnu/9
/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/9/crtbegin.o -L/tmp/SVM-16506476398039308040 -L/mnt/d/Java/graalvm-ce-java17-linux-21.3.0/lib/static/linux-amd64/glibc -
L/mnt/d/Java/graalvm-ce-java17-linux-21.3.0/lib/svm/clibraries/linux-amd64 -L/usr/lib/gcc/x86_64-linux-gnu/9 -L/usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu -L/usr/lib/gcc/
x86_64-linux-gnu/9/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/9/../../.. --gc-sections --dynami
c-list /tmp/SVM-16506476398039308040/exported_symbols.list --exclude-libs ALL -x qunar-wh-policy-sync-bin.o /mnt/d/Java/graalvm-ce-java17-linux-21.3.0/lib/static/linux-amd64/glibc/libn
et.a /mnt/d/Java/graalvm-ce-java17-linux-21.3.0/lib/static/linux-amd64/glibc/libjavajpeg.a /mnt/d/Java/graalvm-ce-java17-linux-21.3.0/lib/static/linux-amd64/glibc/libextnet.a /mnt/d/Ja
va/graalvm-ce-java17-linux-21.3.0/lib/static/linux-amd64/glibc/libnio.a /mnt/d/Java/graalvm-ce-java17-linux-21.3.0/lib/svm/clibraries/linux-amd64/liblibchelper.a /mnt/d/Java/graalvm-ce
-java17-linux-21.3.0/lib/static/linux-amd64/glibc/libjava.a /mnt/d/Java/graalvm-ce-java17-linux-21.3.0/lib/static/linux-amd64/glibc/liblcms.a /mnt/d/Java/graalvm-ce-java17-linux-21.3.0
/lib/static/linux-amd64/glibc/libfontmanager.a /mnt/d/Java/graalvm-ce-java17-linux-21.3.0/lib/static/linux-amd64/glibc/libawt_headless.a /mnt/d/Java/graalvm-ce-java17-linux-21.3.0/lib/
static/linux-amd64/glibc/libawt.a /mnt/d/Java/graalvm-ce-java17-linux-21.3.0/lib/static/linux-amd64/glibc/libfdlibm.a /mnt/d/Java/graalvm-ce-java17-linux-21.3.0/lib/static/linux-amd64/
glibc/libzip.a /mnt/d/Java/graalvm-ce-java17-linux-21.3.0/lib/svm/clibraries/linux-amd64/libjvm.a -lstdc++ -lm -lfreetype -lpthread -ldl -lz -lrt -lgcc --push-state --as-needed -lgcc_s
 --pop-state -lc -lgcc --push-state --as-needed -lgcc_s --pop-state /usr/lib/gcc/x86_64-linux-gnu/9/crtend.o /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/crtn.o
/usr/bin/ld: cannot find -lfreetype
collect2: error: ld returned 1 exit status
        at com.oracle.svm.hosted.image.NativeImageViaCC.handleLinkerFailure(NativeImageViaCC.java:502)
        at com.oracle.svm.hosted.image.NativeImageViaCC.write(NativeImageViaCC.java:449)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:657)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:488)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:569)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:122)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:599)
[qunar-wh-policy-sync-bin:1603]      [total]: 162,020.49 ms,  6.33 GB
# Printing build artifacts to: /mnt/d/IdeaProjects/zlzl/ota-qunar-policy/qunar-wh-policy-sync/target/qunar-wh-policy-sync-native-image-source-jar/qunar-wh-policy-sync-bin.build_artifac
ts.txt
Error: Image build request failed with exit status 1
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for ota-qunar-policy 1.1-SNAPSHOT:
[INFO]
[INFO] ota-qunar-policy ................................... SUCCESS [  0.144 s]
[INFO] qunar-international-policy ......................... SUCCESS [  7.276 s]
[INFO] qunar-internal-policy .............................. SUCCESS [  4.234 s]
[INFO] qunar-wh-policy-sync ............................... FAILURE [03:02 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:16 min
[INFO] Finished at: 2021-11-26T16:11:24+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:2.5.0.Final:build (default) on project qunar-wh-policy-sync: Failed to build quarkus application: io.quarkus.builder.Buil
dException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: java.lang.RuntimeException: Failed to build native image
[ERROR]         at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:233)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:887)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR]         at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:833)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] Caused by: java.lang.RuntimeException: Image generation failed. Exit code: 1
[ERROR]         at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.imageGenerationFailed(NativeImageBuildStep.java:369)
[ERROR]         at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:213)
[ERROR]         ... 11 more
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
```

### 

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

Ubuntu 20.04 64bit

### Output of `java -version`

17

### GraalVM version (if different from Java)

21.3.0

### Quarkus version or git rev

2.5.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.3

### Additional information

_No response_

### LINKED ISSUE #21729: native image fails to start due to missing libfreetype.so.6 library
### Describe the bug

Running a quarkus native application (2.5.0.Final) fails with following error at startup:

```log
./application: error while loading shared libraries: libfreetype.so.6: cannot open shared object file: No such file or directory
```

With 2.4.2.Final it was working correctly

### Expected behavior

The application should just start.

### Actual behavior

The application can not start.

In the application.properties we have following settings for the native build:

```properties
quarkus.jib.base-native-image=quay.io/quarkus/quarkus-micro-image:1.0
quarkus.native.additional-build-args=\
  -J--add-exports=java.security.jgss/sun.security.krb5=ALL-UNNAMED
```

as build image we use `quay.io/quarkus/ubi-quarkus-native-image:21.3-java17`

and the build.gradle has following dependendies:

```gradle
plugins {
    id 'java'
    id 'io.quarkus'
    id 'com.github.ben-manes.versions'
}

dependencies {
    implementation enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")

    implementation 'io.quarkus:quarkus-jdbc-postgresql'
    implementation 'io.quarkus:quarkus-container-image-jib'
    implementation 'io.quarkus:quarkus-smallrye-openapi'
    implementation 'io.quarkus:quarkus-smallrye-health'
    implementation 'io.quarkus:quarkus-hibernate-orm-panache'
    implementation 'io.quarkus:quarkus-resteasy'
    implementation 'io.quarkus:quarkus-resteasy-jackson'
    implementation 'io.quarkus:quarkus-rest-client'
    implementation 'io.quarkus:quarkus-rest-client-jackson'
    implementation 'io.quarkus:quarkus-liquibase'
    implementation 'io.quarkus:quarkus-arc'
    implementation 'io.quarkus:quarkus-micrometer-registry-prometheus'
    implementation 'io.quarkus:quarkus-scheduler'

    implementation 'org.apache.commons:commons-lang3'
    implementation 'io.quarkiverse.hibernatetypes:quarkus-hibernate-types:0.2.0'

    compileOnly "org.projectlombok:lombok:$lombokVersion"
    annotationProcessor "org.projectlombok:lombok:$lombokVersion"
    testCompileOnly "org.projectlombok:lombok:$lombokVersion"
    testAnnotationProcessor "org.projectlombok:lombok:$lombokVersion"

    compileOnly 'org.osgi:osgi.annotation:8.0.1'
    testCompileOnly 'org.osgi:osgi.annotation:8.0.1'

    testImplementation 'at.favre.lib:bcrypt:0.9.0'
    testImplementation 'io.quarkus:quarkus-junit5'
    testImplementation 'io.rest-assured:rest-assured'
}

group 'com.qumea'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

quarkusDev {
    workingDir = rootProject.projectDir
}

compileJava {
    options.encoding = 'UTF-8'
    options.compilerArgs << '-parameters'
    options.compilerArgs << '-Xlint:all'
    options.compilerArgs << '-Xlint:-exports'
    options.compilerArgs << '-Xlint:-requires-automatic'
    options.compilerArgs << '-Xlint:-processing'
    options.deprecation = true
}

compileTestJava {
    options.encoding = 'UTF-8'
}

quarkusBuild {
    nativeArgs {
        containerBuild = System.env.BITBUCKET_BRANCH == null
        builderImage = "quay.io/quarkus/ubi-quarkus-native-image:21.3-java17"
    }
}
```

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

Java 17.0.1

### GraalVM version (if different from Java)

quay.io/quarkus/ubi-quarkus-native-image:21.3-java17

### Quarkus version or git rev

2.5.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.3

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Karm**
Fixes #20565 
Fixes #13567 
Fixes #12972 
Fixes #12393 
Fixes #8605
Fixes #21729
Fixes #21726

# The good
## Test suite
The actual merit of this PR is the test suite that takes all encoders and decoders for all supported JDK formats for a spin, plus exercises a fair portion of headless-relevant basic Java2D operations, including fonts loading and rendering. There is a [README.md](https://github.com/Karm/quarkus/blob/awt-extension-proper/integration-tests/awt/doc/README.md) in the integration-tests/awt/doc dir.

Classes for reflection and JNI access were added step by step, with JDK 11 sources opened, until the TS started to pass with flying colors, pun intended.

## Works on my machine ™️
I tested the extension with Mandrel 21.3 and  native-image built with JDK 11.0.13+7 (early access) and 22.0 (dev) Mandrel 22.0 (dev) JDK 17.0.x (head [92ff652](https://github.com/adoptium/jdk17u/commit/92ff6524167)).
The test suite requires JDK 11.0.13 based native-image as its minimal version due to [JDK-8254024](https://bugs.openjdk.java.net/browse/JDK-8254024). The TS runs on Windows in HotSpot mode, but the extension terminates in Native mode as AWT in native-image is not yet ready for Windows. Enabling AWT with native-image on Windows goes beyond the scope of Quarkus into GraalVM/Mandrel codebase.

The TS runs well on Centos 8 and I also tried it in a Github action with latest Mandrel dev on Ubuntu:

```yaml

      matrix:
        mandrel-version: ['21.3-JDK11', '21.3-JDK17', '22.0-JDK11']
        os: [ubuntu-20.04]
```

I don't have a modern enough Mac handy, so any feedback from running natively on Mac is much appreciated (when there is JDK 11.0.13 based GraalVM on that platform and if AWT headless is supposed to work there...).

# Quickstart
See Quickstart [README.md](https://github.com/quarkusio/quarkus-quickstarts/blob/dd13fbe5f785f0da4a32c629ab1984fe0cc2615e/awt-graphics-rest-quickstart/README.md).

PR: https://github.com/quarkusio/quarkus-quickstarts/pull/961

# The bad

The extension is inherently fragile with respect to *any* changes in JDK codebase. The test suite coves some selected code paths to enable users to do common image operations, but it is by no means exhaustive. We will be running the AT TS in CI with new JDK updates and monitor regressions.

## Call for help

I would like to kindly ask for hints in these Quarkus build flow related topics, marked with TODO in the source:

 * ~~Terminate before native-image build starts on an unsupported platform (Windows ATTOW). [This](https://github.com/Karm/quarkus/blob/awt-extension-proper/extensions/awt/deployment/src/main/java/io/quarkus/awt/deployment/AwtProcessor.java#L40) is how I do it. Is it an idiomatic way to do such a thing with Quarkus?~~
 * ~~When the JDK version the native-image distribution was based on is not what is expected, I would like to print a warning **before** the native image build starts. That seems to be a chicken-egg problem to me, see [the current implementation that prints the warning after it's built](https://github.com/Karm/quarkus/blob/awt-extension-proper/extensions/awt/deployment/src/main/java/io/quarkus/awt/deployment/AwtProcessor.java#L62).  Perhaps refactoring the GraalVM Version would be an option. It is certain that these issues with particular JDK compatibility will occur in future, so the work wouldn't be just to accommodate one warning.~~
 * How do I handle if a class within JDK loads a property file within JDK, unexported module? The [current implementation](https://github.com/Karm/quarkus/blob/awt-extension-proper/extensions/awt/deployment/src/main/java/io/quarkus/awt/deployment/AwtProcessor.java#L85) yanks the file from the actual jmod file and substitutes the class. It seems very crude and it doesn't solve the problem of taking the file from *host* JDK, while the built could potentially run in a container with a native-image based on a different JDK.  In this particular case the problem is harmless as it is just a property file with error messages and null is returned if no message is found, although a similar problem might arise with more sinister assets in future.

THX @galderz for kicking off the AWT extension.
FYI @jerboaa @zakkak @geoand

### CODE REVIEW

**Comment by jerboaa** [comment]
@Karm There are these tika integration test failures. Does that ring any bell?

```
2021-10-19T00:55:56.4476498Z [quarkus-integration-test-tika-999-SNAPSHOT-runner:25]      [total]: 108,956.13 ms,  2.79 GB
2021-10-19T00:55:56.4479021Z # Printing build artifacts to: /project/quarkus-integration-test-tika-999-SNAPSHOT-runner.build_artifacts.txt
2021-10-19T00:55:56.4537021Z Fatal error:com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing sun.nio.cs.ext.ISO2022_CN$Decoder.<init>(java.nio.charset.Charset) 
2021-10-19T00:55:56.4538834Z Parsing context:
2021-10-19T00:55:56.4539557Z    at sun.nio.cs.ext.ISO2022_CN.newDecoder(ISO2022_CN.java:74)
2021-10-19T00:55:56.4540553Z    at sun.nio.cs.StreamDecoder.<init>(StreamDecoder.java:232)
2021-10-19T00:55:56.4542025Z    at sun.nio.cs.StreamDecoder.forInputStreamReader(StreamDecoder.java:78)
2021-10-19T00:55:56.4543806Z    at java.io.InputStreamReader.<init>(InputStreamReader.java:112)
2021-10-19T00:55:56.4545680Z    at java.util.ServiceLoader$LazyClassPathLookupIterator.parse(ServiceLoader.java:1166)
2021-10-19T00:55:56.4547849Z    at java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1206)
2021-10-19T00:55:56.4550375Z    at com.oracle.svm.core.jdk.Target_java_util_ServiceLoader_LazyClassPathLookupIterator.hasNextService(Target_java_util_ServiceLoader.java:105)
2021-10-19T00:55:56.4552763Z    at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1265)
2021-10-19T00:55:56.4554253Z    at java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1300)
2021-10-19T00:55:56.4555500Z    at java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1385)
2021-10-19T00:55:56.4557056Z    at javax.enterprise.inject.spi.CDI.findAllProviders(CDI.java:120)
2021-10-19T00:55:56.4558789Z    at javax.enterprise.inject.spi.CDI.getCDIProvider(CDI.java:82)
2021-10-19T00:55:56.4560428Z    at javax.enterprise.inject.spi.CDI.current(CDI.java:64)
2021-10-19T00:55:56.4562490Z    at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:109)
2021-10-19T00:55:56.4564271Z    at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
2021-10-19T00:55:56.4565434Z    at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
2021-10-19T00:55:56.4566023Z 
2021-10-19T00:55:56.4567395Z 	at com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:126)
2021-10-19T00:55:56.4570137Z 	at com.oracle.graal.pointsto.flow.MethodTypeFlow.createTypeFlow(MethodTypeFlow.java:307)
2021-10-19T00:55:56.4579290Z 	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureTypeFlowCreated(MethodTypeFlow.java:282)
2021-10-19T00:55:56.4582095Z 	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:103)
2021-10-19T00:55:56.4585422Z 	at com.oracle.graal.pointsto.DefaultAnalysisPolicy$DefaultSpecialInvokeTypeFlow.onObservedUpdate(DefaultAnalysisPolicy.java:363)
2021-10-19T00:55:56.4588499Z 	at com.oracle.graal.pointsto.flow.TypeFlow.notifyObservers(TypeFlow.java:471)
2021-10-19T00:55:56.4590481Z 	at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:540)
2021-10-19T00:55:56.4593771Z 	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:539)
2021-10-19T00:55:56.4595975Z 	at com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:188)
2021-10-19T00:55:56.4598862Z 	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:172)
2021-10-19T00:55:56.4601144Z 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
2021-10-19T00:55:56.4602912Z 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
2021-10-19T00:55:56.4604805Z 	at java.base/java.util.concurrent.ForkJoinPool.awaitQuiescence(ForkJoinPool.java:2984)
2021-10-19T00:55:56.4606981Z 	at com.oracle.graal.pointsto.util.CompletionExecutor.complete(CompletionExecutor.java:238)
2021-10-19T00:55:56.4608947Z 	at com.oracle.graal.pointsto.BigBang.doTypeflow(BigBang.java:602)
2021-10-19T00:55:56.4610348Z 	at com.oracle.graal.pointsto.BigBang.finish(BigBang.java:577)
2021-10-19T00:55:56.4613016Z 	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:707)
2021-10-19T00:55:56.4615847Z 	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:532)
2021-10-19T00:55:56.4618490Z 	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:491)
2021-10-19T00:55:56.4622844Z 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:380)
2021-10-19T00:55:56.4626882Z 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:543)
2021-10-19T00:55:56.4630372Z 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:119)
2021-10-19T00:55:56.4633905Z 	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:573)
2021-10-19T00:55:56.4638044Z Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: org.graalvm.compiler.debug.GraalError: com.oracle.svm.core.util.VMError$HostedError: Registering and initializing a type that was not yet marked as reachable: AnalysisType<sun.nio.cs.EUC_CN, allocated: false, inHeap: false, reachable: false>
2021-10-19T00:55:56.4641141Z 	at parsing sun.nio.cs.EUC_CN.newDecoder(EUC_CN.java:52)
2021-10-19T00:55:56.4643671Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2578)
2021-10-19T00:55:56.4649322Z 	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.throwParserError(SharedGraphBuilderPhase.java:111)
2021-10-19T00:55:56.4652818Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3439)
2021-10-19T00:55:56.4656092Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.handleBytecodeBlock(BytecodeParser.java:3391)
2021-10-19T00:55:56.4658975Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3236)
2021-10-19T00:55:56.4764503Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1122)
2021-10-19T00:55:56.4767102Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:1007)
2021-10-19T00:55:56.4769740Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
2021-10-19T00:55:56.4772284Z 	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase.run(SharedGraphBuilderPhase.java:81)
2021-10-19T00:55:56.4774678Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.run(Phase.java:49)
2021-10-19T00:55:56.4776543Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:212)
2021-10-19T00:55:56.4778444Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
2021-10-19T00:55:56.4780224Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
2021-10-19T00:55:56.4782655Z 	at com.oracle.graal.pointsto.flow.AnalysisParsedGraph.parseBytecode(AnalysisParsedGraph.java:131)
2021-10-19T00:55:56.4785201Z 	at com.oracle.svm.hosted.SVMHost.parseBytecode(SVMHost.java:709)
2021-10-19T00:55:56.4787427Z 	at com.oracle.graal.pointsto.meta.AnalysisMethod.ensureGraphParsed(AnalysisMethod.java:605)
2021-10-19T00:55:56.4791206Z 	at com.oracle.graal.pointsto.phases.InlineBeforeAnalysisGraphDecoder.lookupEncodedGraph(InlineBeforeAnalysis.java:161)
2021-10-19T00:55:56.4795145Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.doInline(PEGraphDecoder.java:1109)
2021-10-19T00:55:56.4798242Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.tryInline(PEGraphDecoder.java:1092)
2021-10-19T00:55:56.4801688Z 	at com.oracle.graal.pointsto.phases.InlineBeforeAnalysisGraphDecoder.tryInline(InlineBeforeAnalysis.java:176)
2021-10-19T00:55:56.4805411Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.trySimplifyInvoke(PEGraphDecoder.java:950)
2021-10-19T00:55:56.4808759Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.handleInvoke(PEGraphDecoder.java:904)
2021-10-19T00:55:56.4811719Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.GraphDecoder.processNextNode(GraphDecoder.java:791)
2021-10-19T00:55:56.4815573Z 	at com.oracle.graal.pointsto.phases.InlineBeforeAnalysisGraphDecoder.processNextNode(InlineBeforeAnalysis.java:228)
2021-10-19T00:55:56.4818893Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.GraphDecoder.decode(GraphDecoder.java:532)
2021-10-19T00:55:56.4821403Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.decode(PEGraphDecoder.java:776)
2021-10-19T00:55:56.4825472Z 	at com.oracle.graal.pointsto.phases.InlineBeforeAnalysis.decodeGraph(InlineBeforeAnalysis.java:99)
2021-10-19T00:55:56.4828476Z 	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:171)
2021-10-19T00:55:56.4831232Z 	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:321)
2021-10-19T00:55:56.4833932Z 	at com.oracle.graal.pointsto.flow.MethodTypeFlow.createTypeFlow(MethodTypeFlow.java:293)
2021-10-19T00:55:56.4835434Z 	... 21 more
2021-10-19T00:55:56.4837398Z Caused by: org.graalvm.compiler.debug.GraalError: com.oracle.svm.core.util.VMError$HostedError: Registering and initializing a type that was not yet marked as reachable: AnalysisType<sun.nio.cs.EUC_CN, allocated: false, inHeap: false, reachable: false>
2021-10-19T00:55:56.4840300Z 	at com.oracle.graal.pointsto.util.AnalysisFuture.setException(AnalysisFuture.java:49)
2021-10-19T00:55:56.4842250Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:269)
2021-10-19T00:55:56.4844149Z 	at com.oracle.graal.pointsto.util.AnalysisFuture.ensureDone(AnalysisFuture.java:64)
2021-10-19T00:55:56.4846801Z 	at com.oracle.graal.pointsto.meta.AnalysisType.ensureInitialized(AnalysisType.java:631)
2021-10-19T00:55:56.4849762Z 	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:371)
2021-10-19T00:55:56.4852570Z 	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:340)
2021-10-19T00:55:56.4854943Z 	at com.oracle.graal.pointsto.meta.AnalysisType.convertFields(AnalysisType.java:1032)
2021-10-19T00:55:56.4857422Z 	at com.oracle.graal.pointsto.meta.AnalysisType.getStaticFields(AnalysisType.java:1052)
2021-10-19T00:55:56.4859973Z 	at com.oracle.graal.pointsto.meta.AnalysisType.getStaticFields(AnalysisType.java:76)
2021-10-19T00:55:56.4862995Z 	at com.oracle.svm.core.jdk.localization.LocalizationFeature$CharsetNodePlugin.findStaticField(LocalizationFeature.java:216)
2021-10-19T00:55:56.4866273Z 	at com.oracle.svm.core.jdk.localization.LocalizationFeature$CharsetNodePlugin.handleInvoke(LocalizationFeature.java:198)
2021-10-19T00:55:56.4869581Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.tryNodePluginForInvocation(BytecodeParser.java:2209)
2021-10-19T00:55:56.4872700Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.appendInvoke(BytecodeParser.java:1876)
2021-10-19T00:55:56.4875460Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1649)
2021-10-19T00:55:56.4878294Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1629)
2021-10-19T00:55:56.4881117Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5373)
2021-10-19T00:55:56.4884376Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3431)
2021-10-19T00:55:56.4886264Z 	... 48 more
2021-10-19T00:55:56.4887677Z Caused by: com.oracle.svm.core.util.VMError$HostedError: Registering and initializing a type that was not yet marked as reachable: AnalysisType<sun.nio.cs.EUC_CN, allocated: false, inHeap: false, reachable: false>
2021-10-19T00:55:56.4889976Z 	at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:68)
2021-10-19T00:55:56.4891726Z 	at com.oracle.svm.hosted.SVMHost.initializeType(SVMHost.java:273)
2021-10-19T00:55:56.4893655Z 	at com.oracle.graal.pointsto.meta.AnalysisType.lambda$new$0(AnalysisType.java:235)
2021-10-19T00:55:56.4895536Z 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
2021-10-19T00:55:56.4897101Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2021-10-19T00:55:56.4897991Z 	... 63 more
2021-10-19T00:55:56.7705242Z Error: Image build request failed with exit status 1
```

**Comment by jerboaa** [comment]
> @jerboaa The charset issues have already been spotted independent of this PR, see #20837 and #20839

OK.

**Comment by Karm** [comment]
Calling
```
$ ./mvnw -o clean verify -f integration-tests/pom.xml -pl main -Pnative
```

Causes a failure in building native image:

```
Fatal error:org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: java.lang.NullPointerException
        at parsing java.desktop@11.0.13/sun.java2d.pipe.BufferedRenderPipe.<init>(BufferedRenderPipe.java:68)
        at method: void sun.java2d.pipe.BufferedRenderPipe.<init>(RenderQueue)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2624)
```

I wonder whether the fact that there is `AwtFeature.java` in code *and* Tika depending on AWT has something to do with it :-|   /me looking 

Full context: https://gist.github.com/Karm/819fcc75a71418819b204d754667e382

**Comment by Karm** [comment]
I can confirm the failure also locally now:

```
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildContainerRunner] Checking image status quay.io/quarkus/ubi-quarkus-mandrel:21.2-java11
21.2-java11: Pulling from quarkus/ubi-quarkus-mandrel
Digest: sha256:a3c20622ff350cb179600d677086c7a3013964832485cb374081a7fb408b8853
Status: Image is up to date for quay.io/quarkus/ubi-quarkus-mandrel:21.2-java11
quay.io/quarkus/ubi-quarkus-mandrel:21.2-java11
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on native-image 21.2.0.2-Final Mandrel Distribution (Java Version 11.0.13+8)
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildRunner] docker run --env LANG=C --rm --user 1000:1000 -v /home/karm/workspaceRH/quarkus/integration-tests/awt/target/quarkus-awt-integration-tests-999-SNAPSHOT-native-image-source-jar:/project:z --name build-native-EKNLl quay.io/quarkus/ubi-quarkus-mandrel:21.2-java11 -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=3 -J-Duser.language=en -J-Duser.country=US -J-Dfile.encoding=UTF-8 -H:-ParseOnce -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy\$BySpaceAndTime -H:+JNI -H:+AllowFoldMethods -J-Djava.awt.headless=true -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:EnableURLProtocols=http -H:+InlineBeforeAnalysis -H:-UseServiceLoaderFeature -H:+StackTrace quarkus-awt-integration-tests-999-SNAPSHOT-runner -jar quarkus-awt-integration-tests-999-SNAPSHOT-runner.jar
[quarkus-awt-integration-tests-999-SNAPSHOT-runner:59]    classlist:   1,924.49 ms,  0.96 GB
[quarkus-awt-integration-tests-999-SNAPSHOT-runner:59]        (cap):     541.67 ms,  0.96 GB
[quarkus-awt-integration-tests-999-SNAPSHOT-runner:59]        setup:   2,178.25 ms,  1.19 GB
The bundle named: messages, has not been found. If the bundle is part of a module, verify the bundle name is a fully qualified class name. Otherwise verify the bundle path is accessible in the classpath.
08:03:40,928 INFO  [org.jbo.threads] JBoss Threads version 3.4.2.Final
[quarkus-awt-integration-tests-999-SNAPSHOT-runner:59]     (clinit):     729.67 ms,  5.65 GB
[quarkus-awt-integration-tests-999-SNAPSHOT-runner:59]   (typeflow):  15,640.21 ms,  5.65 GB
[quarkus-awt-integration-tests-999-SNAPSHOT-runner:59]    (objects):  16,225.95 ms,  5.65 GB
[quarkus-awt-integration-tests-999-SNAPSHOT-runner:59]   (features):   1,684.36 ms,  5.65 GB
[quarkus-awt-integration-tests-999-SNAPSHOT-runner:59]     analysis:  35,556.93 ms,  5.65 GB
[quarkus-awt-integration-tests-999-SNAPSHOT-runner:59]     universe:   2,607.76 ms,  5.68 GB
[quarkus-awt-integration-tests-999-SNAPSHOT-runner:59]      (parse):   3,373.72 ms,  5.68 GB
[quarkus-awt-integration-tests-999-SNAPSHOT-runner:59]      compile:   3,388.74 ms,  5.68 GB
Fatal error:org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: java.lang.NullPointerException
        at parsing java.desktop@11.0.13/sun.java2d.pipe.BufferedRenderPipe.<init>(BufferedRenderPipe.java:68)
        at method: void sun.java2d.pipe.BufferedRenderPipe.<init>(RenderQueue)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2578)
        at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.throwParserError(SharedGraphBuilderPhase.java:111)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3439)
        at com.oracle.svm.hosted.phases.HostedBytecodeParser.iterateBytecodesForBlock(HostedGraphBuilderPhase.java:190)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.handleBytecodeBlock(BytecodeParser.java:3391)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3236)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1122)
        at com.oracle.svm.hosted.phases.HostedBytecodeParser.build(HostedGraphBuilderPhase.java:134)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:1007)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
        at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase.run(SharedGraphBuilderPhase.java:81)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.run(Phase.java:49)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:212)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
        at com.oracle.svm.hosted.code.CompileQueue.defaultParseFunction(CompileQueue.java:930)
        at com.oracle.svm.hosted.code.CompileQueue.doParse(CompileQueue.java:736)
        at com.oracle.svm.hosted.code.CompileQueue$ParseTask.run(CompileQueue.java:331)
        at com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:188)
        at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:172)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.NullPointerException
        at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.java.RegisterFinalizerNode.mayHaveFinalizer(RegisterFinalizerNode.java:105)
        at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.StandardGraphBuilderPlugins$31.apply(StandardGraphBuilderPlugins.java:919)
        at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.graphbuilderconf.InvocationPlugin.execute(InvocationPlugin.java:166)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.applyInvocationPlugin(BytecodeParser.java:2197)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.tryInvocationPlugin(BytecodeParser.java:2183)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.appendInvoke(BytecodeParser.java:1889)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeSpecial(BytecodeParser.java:1780)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeSpecial(BytecodeParser.java:1772)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5372)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3431)
        ... 23 more
[quarkus-awt-integration-tests-999-SNAPSHOT-runner:59]      [total]:  46,079.26 ms,  5.68 GB
```

Made as:
```
$ ./mvnw -o clean verify -f integration-tests/pom.xml -pl awt -Pnative -Dquarkus.native.container-build=true -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel:21.2-java11 | tee log.log
```

This was definitely passing at the time I opened the PR, so I will try to hunt down the change in Quarkus that made it fail recently....

FYI @galderz

**Comment by Karm** [comment]
/me WIP on making it work again...

**Comment by Karm** [comment]
The main suite passes for me now with these failures that I have both with `main` and with my branch, thus unrelated to this PR: 

```
[ERROR] Failures: 
[ERROR]   JPAReflectionInGraalITCase.testFieldAndGetterReflectionOnEntityFromServlet:21 1 expectation failed.
Response body doesn't match expectation.
Expected: is "OK"
  Actual: Should not be able to find a non referenced non entity classOK

[ERROR]   RegisterForReflectionITCase.testSelfWithoutNested:21->assertRegistration:56 1 expectation failed.
Response body doesn't match expectation.
Expected: is "FAILED"
  Actual: InnerClassOfA

[ERROR]   RegisterForReflectionITCase.testTargetWithNested:41->assertRegistration:56 1 expectation failed.
Response body doesn't match expectation.
Expected: is "FAILED"
  Actual: ResourceC

[ERROR]   RegisterForReflectionITCase.testTargetWithoutNested:50->assertRegistration:56 1 expectation failed.
Response body doesn't match expectation.
Expected: is "FAILED"
  Actual: ResourceD

[ERROR]   ResourcesITCase.excludedNative:16 1 expectation failed.
Expected status code <404> but was <200>.

[INFO] 
[ERROR] Tests run: 126, Failures: 5, Errors: 0, Skipped: 3
```

Looking forward to seeing the CI results on GitHub Actions now :)

**Comment by Karm** [comment]
@gsmet  Do you happen to have any idea why Hibernate Validator builds Native image on Windows with AWT extension in it?

```
2021-11-08T12:28:14.9260945Z [ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:build (default) on project quarkus-integration-test-hibernate-validator: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
2021-11-08T12:28:14.9372268Z [ERROR] 	[error]: Build step io.quarkus.awt.deployment.AwtProcessor#osSupportCheck threw an exception: java.lang.UnsupportedOperationException: Windows AWT integration is not ready in native-image and would result in java.lang.UnsatisfiedLinkError: no awt in java.library.path.
2021-11-08T12:28:14.9376577Z [ERROR] 	at io.quarkus.awt.deployment.AwtProcessor.osSupportCheck(AwtProcessor.java:45)
```

It is probably started by  https://github.com/quarkusio/quarkus/blob/main/.github/native-tests.json#L136, although I cannot see any clear reason why it pulls AWT in it. The hibernate-extension does not seem to be depending on AWT extension...

The bottom line is I am trying to remove this false negative. AWT is not supported on Windows in native image as per current AWT Windows Graal limitations.

**Comment by Karm** [comment]
@geoand  Related dependent AWT PR is merged now https://github.com/quarkusio/quarkus-quickstarts/pull/961

**Comment by gsmet** [comment]
Sorry for the delay. I'll have a look.

**Comment by Karm** [comment]
Updated https://github.com/quarkusio/quarkus/pull/20850#issuecomment-964160149 with JAXB/AWT :-( 

@galderz WDYT?

**Comment by Karm** [comment]
This is the AWT Windows support Graal issue: https://github.com/oracle/graal/issues/3084
I am experimenting with it to see if we could make it work at least in Mandrel until Graal settles on a long-term solution.

**Comment by gsmet** [comment]
@Karm so the answer is simple, the HV ITs are depending on `quarkus-jaxb` and you added a dependency to `quarkus-awt` there.

I tried to exclude it but somehow the `native-image` process gets stuck (no CPU usage and no output) once I set up the exclusion.

And when I try to build it locally as is, I now have a `/usr/bin/ld: cannot find -lfreetype` error which I didn't have before. So somehow, you're bringing much more than what it used to be.

**Comment by Karm** [comment]
> @Karm so the answer is simple, the HV ITs are depending on `quarkus-jaxb` and you added a dependency to `quarkus-awt` there.
> 
> I tried to exclude it but somehow the `native-image` process gets stuck (no CPU usage and no output) once I set up the exclusion.
> 
> And when I try to build it locally as is, I now have a `/usr/bin/ld: cannot find -lfreetype` error which I didn't have before. So somehow, you're bringing much more than what it used to be.

Hello @gsmet,

The freetype dependency is documented in the QuickStart, see https://github.com/quarkusio/quarkus-quickstarts/tree/development/awt-graphics-rest-quickstart#usage-with-a-client-code 
See also our build images that have it installed (dev for build time): 
https://github.com/quarkusio/quarkus-images/blob/main/modules/graalvm/21.3.0-java11/module.yaml#L29
https://github.com/quarkusio/quarkus-images/blob/main/modules/mandrel/21.3.0.0-Final-java11/module.yaml#L27

Ad bringing more than it used to be: The current AWT extension is a POC, a stub. All it can do is to decode a particular selected type of PNG image and resize it. That's all. 

If you use it in your Quarkus application as it is now, all it takes to start causing a horrible cascade of JNI exceptions and CNF exceptions is to send you a *different* kind of PNG image. A different image type obviously doesn't work at all either.

What this PR does is that it brings support for really *all* JDK supported image types, their compression types, colour profiles etc. and it allows the application to deal with fonts too, thus encompassing glyphs rendering too. See the integration tests code.

I see 3 options for image processing (ImageIO/AWT) in Quarkus:

1) Merging AWT extension as presented in this PR and expanding it if needed

2) Making the AWT extension presented in this PR configurable, e.g. let it switch off/on certain functionality e.g. related to fonts for "powerusers". It is somewhat sketchy though and it makes the fragility of the extension even more prone to changes on the JDK side.

3) Removing AWT altogether and stating that nothing ImageIO/AWT related is supported in Quarkus.   That brings us back to issues with as basal things as XML deserialization where images might be encoded in CDATA etc.
  

This PR is not an enhancement to an already working extension, it is the actual implementation for what is currently a POC.

**Comment by Karm** [comment]
It seems to me we could do some opt-in configuration where if you know your app does not need to decode any images in XML files you are processing etc., you won't switch ImageIO/AWT support on and Quarkus adds all those UnsupportedOperationException substitutions for you.  
On the other hand, if you would like ImageIO/AWT capabilities, you switch it on and all those JNI access/reflection initializations presented in this PR kick in.

**Comment by gsmet** [comment]
@Karm couldn't we just react depending on if the `quarkus-awt` extension is around (instead of making it a hard dependency and having config)?

**Comment by Karm** [comment]
It might lift the burden of AWT dependency from JAXB (WDYT @galderz  ?).
Extension like Tika should depend on AWT by default anyway, because decoding documents (and inherently working with image formats) is kinda the point of Tika in the first place.

**Comment by galderz** [comment]
> @Karm couldn't we just react depending on if the quarkus-awt extension is around (instead of making it a hard dependency and having config)?

I like this suggestion, but don't know how it would be done. @gsmet et al we need your expertise in Quarkus to see how to best achieve this.

> Extension like Tika should depend on AWT by default anyway, because decoding documents (and inherently working with image formats) is kinda the point of Tika in the first place.

Yeah, that's fine there. But for things like JAXB is an optional part since it's dependant on whether the XML being parsed contains images. This means that maybe JAXB needs to depend on enough `quarkus-awt` to satisfy any AWT...etc classpath and setting runtime-init requirements, but anything else should be pushed to only do when the graphics libraries need to actually be used.

**Comment by Sanne** [comment]
Many document formats parsed by Tika won't need AWT either. Would be nice
to see if that can be optimised as well.

As a different issue of course.

**Comment by galderz** [comment]
> Many document formats parsed by Tika won't need AWT either. Would be nice to see if that can be optimised as well.

Yeah, I guess if we crack we can crack the other... however, don't pretty much all documents require font access? That's either coming from imageio or awt?

**Comment by Sanne** [comment]
> Yeah, I guess if we crack we can crack the other... however, don't pretty much all documents require font access? That's either coming from imageio or awt?

I've used Tika to export data into spreadsheets... I might be wrong as spreadsheets also could use fonts so maybe you're right, but you don't have to render stuff as images to export one so I would expect it to be unnecessary.

**Comment by Karm** [comment]
> > Many document formats parsed by Tika won't need AWT either. Would be nice to see if that can be optimised as well.
> 
> Yeah, I guess if we crack we can crack the other... however, don't pretty much all documents require font access? That's either coming from imageio or awt?

Depends on what it does, if it's just *reading* doc formats, it might do with its own implementations. It might not need to *render* anyting, hence won't need fonts supports. I am not a Tika user.

Even for some image decoding, it is apparently trying to use `J2KImageReader` library instead of the stock JDK libraries, e.g. in the Tika log: `J2KImageReader not loaded. JPEG2000 files will not be processed.`.  Which is odd on its own as JDK contains JPEG2000 *decoder*, although no *encoder*.

I am sort of fine with substituting everything one possibly could and throwing `UnsupportedOperationException` messages "You must include AWT dependency if you want to do this.".  It definitely feels right for JAXB.
Optimizing Tika, I could take a jab at that in another PR. For the time being I would disable *Native* Tika on Windows and let it depend on AWT.

**Comment by Christopher-Chianelli** [comment]
@Karm 
FYI, to check if an extension is active, Capabilities can be used:
```
@BuildStep
void myBuildStep(Capabilities capabilities) {
    boolean isAwtPresent = capabilities.isPresent("awt");
}
```

**Comment by gsmet** [comment]
@Karm IF disabling the features when the extension is not around is doable - i.e. it doesn't require heavy surgery substitutions for a ton of classes - that would be my preferred option as I think people don't use AWT that often and it comes with a big cost. But it really needs to be maintainable or it's going to be a nightmare.

I would first focus on JAXB as Tika might require some heavy surgery later as they apparently reorganized Tika in modules for the new version.

You can condition substitutions to a class being present or not so you could pick a class of the AWT extension (preferably a stable one as you might not notice it being gone) and do something similar to https://github.com/quarkusio/quarkus/blob/main/extensions/flyway/runtime/src/main/java/io/quarkus/flyway/runtime/graal/ClassPathScannerSubstitutions.java#L18 to register the substitutions only if the class is absent.

You don't have access to our build step framework in substitutions so you can't really use the proposal of @Christopher-Chianelli but it might be useful for other things if you need to condition things in the build steps.

**Comment by Karm** [comment]
The ball is in my court now, WIP....

**Comment by Karm** [comment]
It is going well. I am following the path of *not* depending on AWT and showing users UnsupportedOperationException with a message that they need to depend on AWT extension if they want to do such and such at native-image runtime.
The number of entrypoints into the ImageIO/Java2D/AWT libs is finite, i.e. one does not seem to have to substitute too many things.
Still somewhat laborious as I am adding negative tests (supposed to throw exception) to jaxb integration tests.  
Be back soon

**Comment by Sanne** [comment]
Just a thought: would be nice if you could throw the `UnsupportedOperationException` with the hint based on reachability analysis rather than a substitution? So to have the error hit immediately, rather than needing to have the right kind of integration tests to catch the mistake.

But I haven't looked at how feasible this approach might be or how prone this would be to false positives - just my 2c :)

**Comment by Karm** [comment]
Hmm... no formatting failures locally.
```
[INFO] ------------< io.quarkus:quarkus-no-awt-integration-tests >-------------
[INFO] Building Quarkus - No Awt - Integration Tests 999-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- formatter-maven-plugin:2.17.0:validate (default-cli) @ quarkus-no-awt-integration-tests ---
[INFO] Processed 3 files in 423ms (Formatted: 0, Unchanged: 3, Failed: 0, Readonly: 0)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

**Comment by Karm** [comment]
> Just a thought: would be nice if you could throw the `UnsupportedOperationException` with the hint based on reachability analysis rather than a substitution? So to have the error hit immediately, rather than needing to have the right kind of integration tests to catch the mistake.
> 
> But I haven't looked at how feasible this approach might be or how prone this would be to false positives - just my 2c :)

Hello @Sanne @gsmet,
CI is running. It looks as I expected on both my local Centos workstation and bare Ubuntu VM (testing missing libs) and on Windows VM. Looking forward to seeing what GitHub would say :) 


*Problem:* Don't depend on AWT extension, prompt user to install it only when needed.

*The current solution in the latest commit:*  It is based on `substitution` rather than the `reachability` analysis, because I wanted the undermentioned behaviour to be a valid scenario:

User has a POJO like this one: https://github.com/Karm/quarkus/blob/awt-extension-proper/integration-tests/jaxb/src/main/java/io/quarkus/it/jaxb/Book.java#L12 with:
```
public class Book {

    private String title;

    private Image cover;
...
```
As long as all that is posted and deserialized is something without any actual images, there is no AWT related problem:

```
curl -X POST -H "Content-Type: application/xml" 
  --data '<book><title>Foundation</title></book>' 
  http://localhost:8080/jaxb/book
```

if and only if JAXB attempts to deserialize an actual image, error pops up in the log, prompting user to install AWT:

```
curl -X POST -H "Content-Type: application/xml" 
  --data '<book><cover>iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAYAAACNMs+9AAAAIElEQVR4XmNgGCngPxSgi6MAZAU4FeOUQAdEKwQBdKsBOgof4SXid6kAAAAASUVORK5CYII=</cover><title>Foundation</title></book>' 
  http://localhost:8080/jaxb/book
```
 
The current wording of the ERROR log:

```
Add AWT Quarkus extension to enable Java2D/ImageIO. Additional system libraries such as `freetype' and `fontconfig' might be needed.
```

In my understanding, if I work with reachablility, the aforementioned example would pop up the ERROR unnecessarily. The user might have some "Thumbnail" or such attribute somewhere, without  actually using it as it depends on user's data.

Lemme know what you think.

Cheers
K.

**Comment by Karm** [comment]
# CI
1) Neither AWT integrations tests nor Tika integration tests are meant for Windows. Could you help excluding them elegantlyy in the GitHub actions config, please?  ping @gsmet 

2) 
 ```2021-11-29T13:08:11.9248386Z [ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:build 
 (default) on project quarkus-awt-integration-tests: Failed to build quarkus application: io.quarkus.builder.BuildException: 
 Build failure: Build failed due to errors
2021-11-29T13:08:11.9263701Z [ERROR] 	[error]: Build step 
io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: java.lang.RuntimeException:
 Cannot find the `native-image.cmd` in the GRAALVM_HOME, JAVA_HOME and System PATH. 
 Install it using `gu install native-image
```
This looks like an env issue. Graal not installed properly?

**Comment by Karm** [comment]
@gsmet , eh, Micrometer? Mailer? 
Also, browsing raw logs, it's not clear to me what is the complaint about awt run and why there is Tika again on windows. 
Could you take a look at the config attempt in b375e77 and suggest a better angle?

Cheers
K.

**Comment by Karm** [comment]
(rebase)

**Comment by gsmet** [comment]
@Karm let me have a look today, there's something fishy in what your ITs do during the JVM build.

File: extensions/awt/deployment/src/main/java/io/quarkus/awt/deployment/AwtProcessor.java [hunk 1]
```diff
@@ -56,20 +293,23 @@ JniRuntimeAccessBuildItem setupJava2DClasses() {
...
-
-    @BuildStep
-    FeatureBuildItem feature() {
-        return new FeatureBuildItem(FEATURE);
+                "sun.java2d.pipe.RegionIterator",
+                "sun.java2d.pipe.ShapeSpanIterator",
+                "sun.java2d.pipe.SpanClipRenderer",
+                "sun.java2d.pipe.ValidatePipe",
+                "sun.java2d.SunGraphics2D",
+                "sun.java2d.SurfaceData");
```
Comment (cescoffier) [inline extensions/awt/deployment/src/main/java/io/quarkus/awt/deployment/AwtProcessor.java:313]: Wow, That's a huge list! Did you some kind of tool to generate it?

**Review by cescoffier — COMMENTED** [review]
The runtime image documentation (freshly merged) would need to be updated.

File: extensions/awt/deployment/src/main/java/io/quarkus/awt/deployment/AwtProcessor.java (hunk 1 above)
Comment (Karm) [reply extensions/awt/deployment/src/main/java/io/quarkus/awt/deployment/AwtProcessor.java:313]: @cescoffier I used a bio-robot.  JDK 11 source code in one terminal, JDK 17 source code in another terminal, Java2D/ImageIO/AWT pet projects and examples to touch relevant code paths.
That created the testing corpus. Then records to AwtProcessor were added one by one or in small couples/handfuls as it made sense according to the JDK source code.

The extension is done safely, so unless your application does something rather exotic, you are covered.

In future, especially due to fontconfig/freetype, I might make it configurable so as experienced users can switch something off, e.g. to keep processing TIFF/PNG/JPEG/GIF/BMP/WBMP files, but having nothing to do with fonts.
Opinions differ though, as it would add more knobs and buttons to the Quarkus config and it would make the integration more fragile. Not part of this PR I would say.

File: integration-tests/no-awt/pom.xml [hunk 2]
```diff
@@ -90,27 +90,4 @@
         </plugins>
     </build>
```
Comment (Karm) [inline integration-tests/no-awt/pom.xml:91]: @gsmet Hmm, would the `quarkus-integration-test-no-awt` keep running in native? The point is to run it in native mode only, no JVM mode tests. 
It tests that the correct error is logged for users that do something with ImageIO/AWT without having AWT extension installed.

**Review by gsmet — CHANGES_REQUESTED** [review]
I added a commit to fix the main issue you had (you were triggering the native build with your extension even if not explicitly asked).

I also added a couple of recommendations about how to improve this particular area. Let me know if you have questions, I'll be happy to help.

Feel free to squash my commit into yours, I kept it separate so that you could have a look at the changes.

File: extensions/awt/deployment/src/main/java/io/quarkus/awt/deployment/AwtProcessor.java [hunk 3]
```diff
@@ -60,7 +65,7 @@ public void osSupportCheck(NativeConfig nativeConfig) {
      * Do I have to go and refactor NativeImageBuildItem to move GraalVMInfo up the chain,
      * to e.g. NativeImageResourceBuildItem...?
      */
-    @BuildStep
+    @BuildStep(onlyIf = NativeBuild.class)
```
[the remark this answers is not in the document]
Comment (gsmet) [reply extensions/awt/deployment/src/main/java/io/quarkus/awt/deployment/AwtProcessor.java:68]: BTW, FYI, we are not actively supporting all the quirks of native images of Windows - we are in best effort mode to not break it. So I wouldn't be shocked if you dropped the error altogether. People will get the underlying error and that's probably good enough for them to understand it's not working on Windows.

File: integration-tests/no-awt/pom.xml (hunk 2 above)
Comment (gsmet) [reply integration-tests/no-awt/pom.xml:91]: Yes. The native tests are run with a profile coming from the parent.

**Comment by Karm** [comment]
* `NativeMinimalJavaVersionBuildItem` done ✅, pending some parsing unit test cleanup.
* `NativeUnsupportedOnPlatformBuildItem` WIP 
* Docs update WIP

**Comment by Karm** [comment]
# NativeMinimalJavaVersionBuildItem :heavy_check_mark: 

If the JDK version in Native image is insufficient:
```
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] 
  Running Quarkus native-image plugin on GraalVM 21.2.0 Java 11 CE (Java Version 11.0.12+6-jvmci-21.2-b08)
[WARNING] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] 
  Expected: Java 11, update 13, Actual: Java 11, update 12. AWT: Some MLib related operations, 
  such as filter in awt.image.ConvolveOp will not work. See https://bugs.openjdk.java.net/browse/JDK-8254024
```

Weird versions, checks are skipped:
```
[WARNING] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep]
  Unable to parse used Java version from native-image version string 
  `native-image 21.3.0.0-Final Mandrel Distribution (Java Version 17-internal+0-adhoc.karm.jdk17u)'. 
  Java version checks will be skipped.
```

**Comment by Karm** [comment]
I did the same mistake as before, with running native build needlessly in JVM tests. Refactoring...

**Comment by Karm** [comment]
Hello @gsmet, I added two build steps, one to check JDK version used in native-image and the other to check for an unsupported OS.

Could you re-review and merge if satisfied, please?

**Review by gsmet — APPROVED** [review]
Things look good now but the CI issue is concerning. I haven't seen any other build failing with a Java heap space on Windows.

@famod any chance you could have a look and see if something rings a bell? I will be very busy these next two days and we really want to merge this before tomorrow evening.

**Comment by Karm** [comment]
@gsmet @famod So, it seems the heap on Windows is an intermittent instability...? Hard to tell on GitHub executors.

**Comment by Karm** [comment]
I wonder what could have been the last straw in those last two commits for the heap on Windows. I hope it's (not) just the CI.

The test is somewhat intensive in what is does with images (regarding quantity), it might be possible that it's too much for the GitHub Windows host and that those JVM AWT tests eat resources that are never freed.

I will try to measure the difference on my Windows VM.

**Comment by gsmet** [comment]
I'm trying something: not reusing forks for the AWT tests. Let's see how it goes.

If the move of some extensions to the Quarkiverse is approved, it might also help with this issue.

**Comment by famod** [comment]
https://github.com/quarkusio/quarkus/pull/20850#issuecomment-986821370 looks exactly like https://github.com/quarkusio/quarkus/pull/21761#issuecomment-986064847, so I don't think this PR has introduced this problem (might make it worse though, dunno).

See also: https://github.com/quarkusio/quarkus/pulls?q=is%3Apr+%22Java+heap+space%22

**Comment by Karm** [comment]
@gsmet Thx for looking into it. I updated the spreadsheet with a row

|                                   |main :heavy_check_mark: | awt-extension-proper :heavy_check_mark: 
|                               -- |                 -- | --
ALL                            |[main_all.log](https://github.com/quarkusio/quarkus/files/7664269/main_all.log)  | [awt-extension-proper_all.log](https://github.com/quarkusio/quarkus/files/7664275/awt-extension-proper_all.log)

and while both completed successfully without a single failure, and took about the same amount of time ( 01:24h and 1:29h ), the gc log for `main` is like 1.2M while the one for `awt-extension-proper` is cca 20M :scream:   

```
set "MODULES=-pl !gradle,!maven,!devtools"
set "MAVEN_OPTS=-Xmx1500m -XX:MaxMetaspaceSize=1g -Xlog:gc*=debug:file=windows-java-11.txt"
mvnw install -Dquickly & mvnw verify -f integration-tests/pom.xml --fail-at-end --batch-mode -DfailIfNoTests=false %MODULES%
```

**Comment by Karm** [comment]
```41 Successful Checks``` ✅
@gsmet @famod 

Do we merge it as it is now or would you like me to squash it?

**Comment by gsmet** [comment]
@Karm let's keep it this way, in this case, I think the history has a lot of value.

**Comment by gsmet** [comment]
@Karm congrats for this nice work and thanks!
