### PR TITLE
Narayana JTA - Auto-enable recovery service when XA datasources are configured

### LINKED ISSUE #28144: Narayana JTA - Enabling Recovery service by default
During the 2.13 development cycle, there was an attempt to enable the Narayana JTA recovery service by default. Not having it enabled was apparently an oversight and is considered a bug by the Narayana team.

In the end, we disabled it by default in 2.13 because we didn't have time to properly sort things out.

Enabling the recovery service by default comes with a few questions/problems:

- Are we clear that the recovery service is required for a consistent behavior even when XA is not used? Could we have a description of a problem that could happen without XA and that the recovery service is supposed to fix?
- Enabling the recovery service requires the `ObjectStore` directory to be created. At the moment, if we do so, an `ObjectStore` directory is created at the current path. Meaning if you run tests creating an `ObjectStore` you end up with an `ObjectStore` directory created at the root of your project (i.e. in the case of Maven, outside of `target` and thus ready to get committed to your Git repository). Creating this directory in a temp directory doesn't seem like a good idea (at least from what I understood of the purpose of this service) but we need to solve the directory location for all cases:
  - tests (both Maven and Gradle, they have different output directories)
  - execution
  - execution inside containers - we need to make sure this works with the permissions defined in our Dockerfiles.
Note that it's not so simple as we definitely don't want the location to be defined at build time.
- Are we sure enabling this service doesn't cause any performance regressions? If so, are they acceptable or not?

/cc @zhfeng @mmusgrov @Sanne @yrodiere

### PR DESCRIPTION
**Pull request by marcosgopen**
addresses https://github.com/quarkusio/quarkus/issues/28144 
See doc reference https://quarkus.io/guides/transaction#jdbcstore

This PR automatically enables the Narayana JTA transaction recovery service when XA datasources are detected at build time, removing the need for users to manually set
quarkus.transaction-manager.enable-recovery=true.
Without recovery enabled, XA transactions that fail mid-commit (e.g. due to a crash) can leave data in an inconsistent state.

Changes

Auto-detection of XA datasources at build time:

The enable-recovery config property has been moved from a runtime boolean (defaulting to false) to a build-time Optional. When unset, it defaults to true if  any XA datasource is configured, false otherwise.

Users retain full control:

- Setting quarkus.transaction-manager.enable-recovery=true forces recovery on (even without XA datasources).
- Setting quarkus.transaction-manager.enable-recovery=false forces recovery off (even with XA datasources).

Known limitations

- Auto-detection currently covers JDBC XA datasources only. Other transactional resources (e.g. JMS resource adapters) will still require manual configuration.
- The decision is made at build time, so datasources configured purely at runtime won't trigger auto-enablement.

### CODE REVIEW

**Review by tomjenkinson — COMMENTED** [review]
@marcosgopen - please may I suggest to add a test?

**Comment by marcosgopen** [comment]
> @marcosgopen - please may I suggest to add a test?

Thanks @tomjenkinson , I had written some tests to verify this solution by I couldn't find a "clean" way to check whether the QuarkusRecoveryService was running or not. So in order to check that I added a method in the QuarkusRecoveryService to query the status of the service. Then I thought it was not a nice solution so I removed the tests and the method. I will add them in a second commit and let you decide whether we want to keep them or not.

**Review by gsmet — APPROVED** [review]
At a quick glance, it looks fine, thanks.

I would very much like to have @yrodiere have a look though (or someone else from the Hibernate team)

File: extensions/agroal/deployment/src/main/java/io/quarkus/agroal/deployment/AgroalProcessor.java [hunk 1]
```diff
@@ -300,6 +302,7 @@ void generateDataSourceBeans(AgroalRecorder recorder,
                     aggregatedBuildTimeConfigBuildItem.getDbKind(),
                     aggregatedBuildTimeConfigBuildItem.getDataSourceConfig().dbVersion(),
                     aggregatedBuildTimeConfigBuildItem.getJdbcConfig().transactions() != TransactionIntegration.DISABLED,
+                    aggregatedBuildTimeConfigBuildItem.getJdbcConfig().transactions() == TransactionIntegration.XA,
```
Comment (yrodiere) [inline extensions/agroal/deployment/src/main/java/io/quarkus/agroal/deployment/AgroalProcessor.java:303]: You might as well replace the argument with one of type `TransactionIntegration` at this point. No?

File: extensions/narayana-jta/deployment/src/main/java/io/quarkus/narayana/jta/deployment/NarayanaJtaProcessor.java [hunk 2]
```diff
@@ -199,7 +212,11 @@ public void startRecoveryService(NarayanaJtaRecorder recorder, List<JdbcDataSour
                 .map(j -> j.getName())
                 .collect(Collectors.toSet());
 
-        recorder.startRecoveryService(configuredDataSourcesConfigKeys, dataSourcesWithTransactionIntegration);
+        recorder.validateObjectStoreConfiguration(configuredDataSourcesConfigKeys, dataSourcesWithTransactionIntegration);
+
+        if (recoveryEnabledBuildItem.isEnabled()) {
+            recorder.startRecoveryService(shutdownContextBuildItem);
+        }
```
Comment (yrodiere) [inline extensions/narayana-jta/deployment/src/main/java/io/quarkus/narayana/jta/deployment/NarayanaJtaProcessor.java]: Are you sure you want to validate recovery configuration even when recovery is disabled? That seems a bit too strict?

File: extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/TransactionManagerConfiguration.java [hunk 3]
```diff
@@ -39,12 +39,6 @@ public interface TransactionManagerConfiguration {
     @WithDefault("60")
     Duration defaultTransactionTimeout();
 
-    /**
-     * Start the recovery service on startup.
-     */
-    @WithDefault("false")
-    boolean enableRecovery();
-
     /**
```
Comment (yrodiere) [inline extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/TransactionManagerConfiguration.java:52]: Do you really want to move this from runtime to build time?

If you think it just makes more sense and nobody is using the ability to enable/disable it at runtime, that's perfectly fine.

If you just did that to allow implementing this feature, though... please be aware that you could have implemented what you wanted without moving the property to build time. You would have to change the return type of this property to `Optional<Boolean>` and passed the build-time information ("default for enableRecovery") to the bytecode recorder.

**Review by yrodiere — COMMENTED** [review]
The implementation looks good, but I'm not sure about the decision to move recovery enablement from runtime to build-time. Please confirm you really think it's the right way? See also my comments below.

File: extensions/narayana-jta/deployment/src/main/java/io/quarkus/narayana/jta/deployment/NarayanaJtaProcessor.java (hunk 2 above)
Comment (marcosgopen) [reply extensions/narayana-jta/deployment/src/main/java/io/quarkus/narayana/jta/deployment/NarayanaJtaProcessor.java]: Actually if the recovery is disabled it will not start the recovery service (even when xaResources are present): https://github.com/quarkusio/quarkus/pull/53018/changes#diff-9a5bb2161e115a07a5b036dd7227f9bfadd43f82ab939a989a5d2044ba97312eR194
see doc: https://github.com/quarkusio/quarkus/pull/53018/changes#diff-b86c4389d1f3659cbf608fadee4fbad6863020687d3f102c24b44dd00028c10bR414
see test: https://github.com/quarkusio/quarkus/pull/53018/changes#diff-ebc95a5b359d38bd40ee6d161681aa83e66eb134410a8542ee9cbae9e8cf70c6R16-R17

Comment (yrodiere) [reply extensions/narayana-jta/deployment/src/main/java/io/quarkus/narayana/jta/deployment/NarayanaJtaProcessor.java]: I think we agree on that. I was pointing out that if the recovery service does not start, you probably don't care about the object store configuration being correct. So I'd expect this code to be something like:

```suggestion
        if (recoveryEnabledBuildItem.isEnabled()) {
            recorder.validateObjectStoreConfiguration(configuredDataSourcesConfigKeys, dataSourcesWithTransactionIntegration);
            recorder.startRecoveryService(shutdownContextBuildItem);
        }
```

Comment (marcosgopen) [reply extensions/narayana-jta/deployment/src/main/java/io/quarkus/narayana/jta/deployment/NarayanaJtaProcessor.java]: Sorry, you are talking about validateObjectStoreConfiguration. I am not sure, but I kept it as at the moment it is always executed.

Comment (yrodiere) [reply extensions/narayana-jta/deployment/src/main/java/io/quarkus/narayana/jta/deployment/NarayanaJtaProcessor.java]: Okay, well if you are not sure... I'll mention this is a change you introduced in this PR, by moving validation out of startRecoveryService into a dedicated method :)

File: extensions/agroal/deployment/src/main/java/io/quarkus/agroal/deployment/AgroalProcessor.java (hunk 1 above)
Comment (marcosgopen) [reply extensions/agroal/deployment/src/main/java/io/quarkus/agroal/deployment/AgroalProcessor.java:303]: Do you mean changing the constructor of  JdbcDataSourceBuildItem and pass a TransactionIntegration argument? I think it makes sense, but that would mean adding quarkus-agroal dependency to quarkus-agroal-spi (so that it resolves TransactionIntegration class). Should I do that or we want to keep more isolation?

Comment (yrodiere) [reply extensions/agroal/deployment/src/main/java/io/quarkus/agroal/deployment/AgroalProcessor.java:303]: > Do you mean changing the constructor of JdbcDataSourceBuildItem and pass a TransactionIntegration argument

Yes

> quarkus-agroal dependency to quarkus-agroal-spi

It is already there:

https://github.com/quarkusio/quarkus/blob/bf2a10f7c433ae174445f404923e4b104aa8beb8/extensions/agroal/deployment/pom.xml#L40-L43

File: extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/TransactionManagerConfiguration.java (hunk 3 above)
Comment (marcosgopen) [reply extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/TransactionManagerConfiguration.java:52]: I thought moving it to build time was the only way. Actually if we could keep it as a runtime configuration it would be better. I will update the PR. Thanks

File: extensions/agroal/deployment/src/main/java/io/quarkus/agroal/deployment/AgroalProcessor.java (hunk 1 above)
Comment (marcosgopen) [reply extensions/agroal/deployment/src/main/java/io/quarkus/agroal/deployment/AgroalProcessor.java:303]: Actually it is the other way around: quarkus-agroal dependency to quarkus-agroal-spi
It makes sense to have quarkus-agroal-spi into quarkus-agroal. Not sure quarkus-agroal into quarkus-agroal-spi 
Please note that  JdbcDataSourceBuildItem is in quarkus-agroal-spi, and TransactionIntegration in quarkus-agroal.

Comment (yrodiere) [reply extensions/agroal/deployment/src/main/java/io/quarkus/agroal/deployment/AgroalProcessor.java:303]: >  Please note that JdbcDataSourceBuildItem is in quarkus-agroal-spi, and TransactionIntegration in quarkus-agroal.

In that case you could move `TransactionIntegration` to `quarkus-agroal-spi`.

Or just ignore and close this whole thread because it's starting to look like more trouble than it's worth :grin:

File: extensions/narayana-jta/deployment/src/main/java/io/quarkus/narayana/jta/deployment/NarayanaJtaProcessor.java (hunk 2 above)
Comment (marcosgopen) [reply extensions/narayana-jta/deployment/src/main/java/io/quarkus/narayana/jta/deployment/NarayanaJtaProcessor.java]: Yes, you are right. I moved validation out of the startRecoveryService to make the code clearer. But skipping the configuration validation is a different change. And what I meant is that I am not sure if we want that change in this PR.

File: extensions/agroal/deployment/src/main/java/io/quarkus/agroal/deployment/AgroalProcessor.java (hunk 1 above)
Comment (marcosgopen) [reply extensions/agroal/deployment/src/main/java/io/quarkus/agroal/deployment/AgroalProcessor.java:303]: Yes, i'd rather resolve this thread as I wanted to make just a simple PR but it is already bigger than I thought.

Comment (marcosgopen) [reply extensions/agroal/deployment/src/main/java/io/quarkus/agroal/deployment/AgroalProcessor.java:303]: Thanks

File: extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/NarayanaJtaRecorder.java [hunk 4]
```diff
@@ -206,25 +206,28 @@ public void startRecoveryService(Map<String, String> configuredDataSourcesConfig
...
-            QuarkusRecoveryService.getInstance().start();
-        }
     }
 
-    public void handleShutdown(ShutdownContext context) {
+    public void startRecoveryService(ShutdownContext context, boolean xaResourcesPresent) {
+        boolean recoveryEnabled = transactions.getValue().enableRecovery().orElse(xaResourcesPresent);
+        if (!recoveryEnabled) {
+            return;
+        }
```
Comment (yrodiere) [inline extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/NarayanaJtaRecorder.java:212]: If you still want to move validation to a separate method, and want to preserve past behavior, you will need code like this in `validateObjectStoreConfiguration`

File: extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/TransactionManagerConfiguration.java [hunk 5]
```diff
@@ -41,9 +41,11 @@ public interface TransactionManagerConfiguration {
 
     /**
      * Start the recovery service on startup.
+     * <p>
+     * If not set, the recovery service will be started automatically if XA datasources are configured.
+     * Set to {@code true} to always enable recovery, or {@code false} to explicitly disable it.
      */
-    @WithDefault("false")
-    boolean enableRecovery();
+    Optional<Boolean> enableRecovery();
```
Comment (yrodiere) [inline extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/TransactionManagerConfiguration.java:50]:
```suggestion
    @ConfigDocDefault("`true` if XA datasources are configured, `false` otherwise")
    Optional<Boolean> enableRecovery();
```

\+ you may need to add an import for `io.quarkus.runtime.annotations.ConfigDocDefault`

**Review by yrodiere — COMMENTED** [review]
Thanks. Still not sure about the change of behavior for validation, and I have a suggestion for documenting the default, but otherwise looks good :)

File: extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/TransactionManagerConfiguration.java (hunk 5 above)
Comment (marcosgopen) [reply extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/TransactionManagerConfiguration.java:50]: Thanks, updated.

File: extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/NarayanaJtaRecorder.java (hunk 4 above)
Comment (marcosgopen) [reply extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/NarayanaJtaRecorder.java:212]: I now believe that moving the validation to a separate method is not beneficial, so I will be using the startRecoveryService method only. Thanks

File: extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/NarayanaJtaRecorder.java [hunk 6]
```diff
@@ -206,25 +206,25 @@ public void startRecoveryService(Map<String, String> configuredDataSourcesConfig
                         objectStoreDataSourceName, configuredDataSourcesConfigKeys.get(objectStoreDataSourceName)));
             }
         }
-        if (transactions.getValue().enableRecovery()) {
-            QuarkusRecoveryService.getInstance().create();
-            QuarkusRecoveryService.getInstance().start();
+        boolean recoveryEnabled = transactions.getValue().enableRecovery().orElse(xaResourcesPresent);
+        if (!recoveryEnabled) {
+            return;
```
Comment (yrodiere) [inline extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/NarayanaJtaRecorder.java:211]: This should be at the top of the method? So that you skip validation if recovery is disabled.

Comment (marcosgopen) [reply extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/NarayanaJtaRecorder.java:211]: I would not do that. I checked https://quarkus.io/guides/transaction#jdbcstore and potentially the user can disable the recovery but wanting to configure the object store (or at least it is not documented that is not allowed). As such I would recommend to always validate the object store configuration.

Comment (yrodiere) [reply extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/NarayanaJtaRecorder.java:211]: I don't get this but I'm officially giving up.

**Review by yrodiere — APPROVED** [review]
Let's merge, thank you.
