### PR TITLE
WebSockets Next: support OpenTelemetry's SpanAttribute annotation placed on endpoint callback arguments

### LINKED ISSUE #43412: Can't use `@SpanAttribute` annotation with Websockets.NEXT `@OnTextMessage`
### Describe the bug

When combining WebSockets.NEXT & OpenTelemetry, I can't seem to be able to add an `@SpanAttribute` annotation to a method parameter of an `@OnTextMessage`, like this:

```java
@OnTextMessage
@WithSpan("ChatMessage")
public ClaimBotQueryResponse onMessage(@SpanAttribute("arg.chatQuery") ClaimBotQuery query) {
    Log.infof("Got chat query: %s", query);
    var response = new ClaimBotQueryResponse("token", this.bot.chat(query), "");
    Log.debugf("Got chat response: %s", response);

    return response;
}
```

### Expected behavior

_No response_

### Actual behavior

I get this error when trying to run dev mode:

```
2024-09-20 11:21:44,087 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.websockets.next.deployment.WebSocketProcessor#collectEndpoints threw an exception: io.quarkus.websockets.next.WebSocketException: Unable to inject @OnTextMessage callback parameter 'query' declared on org.parasol.resources.ClaimWebsocketChatBot#onMessage(): no injector found
        at io.quarkus.websockets.next.deployment.Callback.collectArguments(Callback.java:208)
        at io.quarkus.websockets.next.deployment.Callback.<init>(Callback.java:65)
        at io.quarkus.websockets.next.deployment.WebSocketProcessor.findCallback(WebSocketProcessor.java:1425)
        at io.quarkus.websockets.next.deployment.WebSocketProcessor.findCallback(WebSocketProcessor.java:1410)
        at io.quarkus.websockets.next.deployment.WebSocketProcessor.collectEndpoints(WebSocketProcessor.java:355)
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
        at java.base/java.lang.Thread.run(Thread.java:1583)
        at org.jboss.threads.JBossThread.run(JBossThread.java:483)

        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:354)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:272)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:62)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:91)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:430)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:57)
        at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:138)
        at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:93)
        at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:131)
        at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.websockets.next.deployment.WebSocketProcessor#collectEndpoints threw an exception: io.quarkus.websockets.next.WebSocketException: Unable to inject @OnTextMessage callback parameter 'query' declared on org.parasol.resources.ClaimWebsocketChatBot#onMessage(): no injector found
        at io.quarkus.websockets.next.deployment.Callback.collectArguments(Callback.java:208)
        at io.quarkus.websockets.next.deployment.Callback.<init>(Callback.java:65)
        at io.quarkus.websockets.next.deployment.WebSocketProcessor.findCallback(WebSocketProcessor.java:1425)
        at io.quarkus.websockets.next.deployment.WebSocketProcessor.findCallback(WebSocketProcessor.java:1410)
        at io.quarkus.websockets.next.deployment.WebSocketProcessor.collectEndpoints(WebSocketProcessor.java:355)
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
        at java.base/java.lang.Thread.run(Thread.java:1583)
        at org.jboss.threads.JBossThread.run(JBossThread.java:483)

        at io.quarkus.builder.Execution.run(Execution.java:123)
        at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
        at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:161)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:350)
        ... 9 more
Caused by: io.quarkus.websockets.next.WebSocketException: Unable to inject @OnTextMessage callback parameter 'query' declared on org.parasol.resources.ClaimWebsocketChatBot#onMessage(): no injector found
        at io.quarkus.websockets.next.deployment.Callback.collectArguments(Callback.java:208)
        at io.quarkus.websockets.next.deployment.Callback.<init>(Callback.java:65)
        at io.quarkus.websockets.next.deployment.WebSocketProcessor.findCallback(WebSocketProcessor.java:1425)
        at io.quarkus.websockets.next.deployment.WebSocketProcessor.findCallback(WebSocketProcessor.java:1410)
        at io.quarkus.websockets.next.deployment.WebSocketProcessor.collectEndpoints(WebSocketProcessor.java:355)
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
        at java.base/java.lang.Thread.run(Thread.java:1583)
        at org.jboss.threads.JBossThread.run(JBossThread.java:483)
```

### How to Reproduce?

Reproducer: [parasol-insurance.zip](https://github.com/user-attachments/files/17077309/parasol-insurance.zip)

1. Download & unzip reproducer
2. `cd parasol-insurance`
3. `./mvnw clean quarkus:dev`
4. Observe above stack trace

### Output of `uname -a` or `ver`

`Darwin edeandrea-m1pro 24.0.0 Darwin Kernel Version 24.0.0: Mon Aug 12 20:51:54 PDT 2024; root:xnu-11215.1.10~2/RELEASE_ARM64_T6000 arm64`

### Output of `java -version`

```
openjdk version "21.0.4" 2024-07-16 LTS
OpenJDK Runtime Environment Temurin-21.0.4+7 (build 21.0.4+7-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.4+7 (build 21.0.4+7-LTS, mixed mode)
```

### Quarkus version or git rev

3.14.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

```
Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)
Maven home: /Users/edeandre/.m2/wrapper/dists/apache-maven-3.9.6/a53741d1
Java version: 21.0.4, vendor: Eclipse Adoptium, runtime: /Users/edeandre/.sdkman/candidates/java/21.0.4-tem
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "15.0", arch: "aarch64", family: "mac"
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by michalvavrik**
- closes https://github.com/quarkusio/quarkus/issues/43412

### CODE REVIEW

**Comment by michalvavrik** [comment]
Strange thing, I have run all the WS Next tests and they were green (multiple times). When I saw failures in this PR CI, I rebased on the current main and all the tests I added started failing. Something has changed in the main branch, I'll investigate and fix it.

**Comment by michalvavrik** [comment]
Ah, new OTel semantic https://github.com/quarkusio/quarkus/pull/50501.

**Comment by brunobat** [comment]
Yeah... sorry for the inconvenience...

**Comment by michalvavrik** [comment]
> Yeah... sorry for the inconvenience...

No problem :-) I was just surprised.

**Review by melloware — APPROVED** [review]

**Review by brunobat — APPROVED** [review]
Looks good to me

File: extensions/websockets-next/deployment/src/main/java/io/quarkus/websockets/next/deployment/WebSocketConstants.java [hunk 1]
```diff
@@ -0,0 +1,11 @@
+package io.quarkus.websockets.next.deployment;
+
+public final class WebSocketConstants {
+
+    /**
+     * Hardcoding the "SpanAttribute" annotation name so that we don't have to introduce a deployment module SPI.
+     * There is a test that fails if this name ever changes.
+     */
+    public static final String OPEN_TELEMETRY_SPAN_ATTRIBUTE = "io.opentelemetry.instrumentation.annotations.SpanAttribute";
```
Comment (mkouba) [inline extensions/websockets-next/deployment/src/main/java/io/quarkus/websockets/next/deployment/WebSocketConstants.java]: I think that this should be a `DotName` located in `WebSocketDotNames`.

File: extensions/websockets-next/deployment/src/main/java/io/quarkus/websockets/next/deployment/MessageCallbackArgument.java [hunk 2]
```diff
@@ -1,12 +1,23 @@
...
     public boolean matches(ParameterContext context) {
-        return context.acceptsMessage() && context.parameterAnnotations().isEmpty();
+        if (!context.acceptsMessage()) {
+            return false;
+        }
+        if (context.parameterAnnotations().isEmpty()) {
+            return true;
+        }
+        // allow OpenTelemetry @SpanAttribute annotation on the method callback argument
+        return context.parameterAnnotations().stream().map(AnnotationInstance::name).map(DotName::toString)
```
Comment (mkouba) [inline extensions/websockets-next/deployment/src/main/java/io/quarkus/websockets/next/deployment/MessageCallbackArgument.java]: I wonder if it would make more sense to remove the `context.parameterAnnotations().isEmpty()` condition instead.

The `MessageCallbackArgument` has the lowest priority so it should not cause ambiguous injectors.

Also it could help for other interceptors (not only the OTel one).

File: extensions/websockets-next/deployment/src/main/java/io/quarkus/websockets/next/deployment/WebSocketConstants.java (hunk 1 above)
Comment (michalvavrik) [reply extensions/websockets-next/deployment/src/main/java/io/quarkus/websockets/next/deployment/WebSocketConstants.java]: > I think that this should be a `DotName` located in `WebSocketDotNames`.

That is package-private class and I didn't want to "expose" these constants. If you are fine with "exposing them" ( :smile: ), I'll move it.

File: extensions/websockets-next/deployment/src/main/java/io/quarkus/websockets/next/deployment/MessageCallbackArgument.java (hunk 2 above)
Comment (michalvavrik) [reply extensions/websockets-next/deployment/src/main/java/io/quarkus/websockets/next/deployment/MessageCallbackArgument.java]: I had considered it, but it is more question on how much lenient you want to be. Personally, I think it makes sense to expect that if the message payload type matches and there are no annotations, you match the `MessageCallbackArgument`. If someone adds an annotation, maybe they misunderstood how it works, like if it was a qualifier?

Anyway, I guess this is quite theoretical discussion because how many users could be affected, I'll leave decision to you, I am fine dropping it.

Comment (mkouba) [reply extensions/websockets-next/deployment/src/main/java/io/quarkus/websockets/next/deployment/MessageCallbackArgument.java]: > If someone adds an annotation, maybe they misunderstood how it works, like if it was a qualifier?

Qualifiers cannot be used at this location.

> Anyway, I guess this is quite theoretical discussion because how many users could be affected, I'll leave decision to you, I am fine dropping it.

I'd try to remove it completely and run the CI. We can always revert the change if needed.

File: extensions/websockets-next/deployment/src/main/java/io/quarkus/websockets/next/deployment/WebSocketConstants.java (hunk 1 above)
Comment (mkouba) [reply extensions/websockets-next/deployment/src/main/java/io/quarkus/websockets/next/deployment/WebSocketConstants.java]: Why do you need to expose them?

Comment (michalvavrik) [reply extensions/websockets-next/deployment/src/main/java/io/quarkus/websockets/next/deployment/WebSocketConstants.java]: I cannot access that class from tests because it is different package and I'd like to check that the constant is up to date (as I do in added tests). By exposing I mean that I'd have to make wider visibility, `final class WebSocketDotNames` -> `public final class WebSocketDotNames`.

Comment (michalvavrik) [reply extensions/websockets-next/deployment/src/main/java/io/quarkus/websockets/next/deployment/WebSocketConstants.java]: but it doesn't matter since you want to remove checking for empty annotations anyway

File: extensions/websockets-next/deployment/src/main/java/io/quarkus/websockets/next/deployment/MessageCallbackArgument.java (hunk 2 above)
Comment (michalvavrik) [reply extensions/websockets-next/deployment/src/main/java/io/quarkus/websockets/next/deployment/MessageCallbackArgument.java]: Ok. Failing CI wasn't my concern, it was getting information soon to users they may doing something that won't work. I'll remove it and run tests.

File: extensions/websockets-next/deployment/src/main/java/io/quarkus/websockets/next/deployment/WebSocketConstants.java (hunk 1 above)
Comment (mkouba) [reply extensions/websockets-next/deployment/src/main/java/io/quarkus/websockets/next/deployment/WebSocketConstants.java]: Ok, I see. We usually don't test constants like this. Still you can place the unit tests like this in the same package - see for example `io.quarkus.websockets.next.deployment.WebSocketProcessorTest`.

File: extensions/websockets-next/deployment/src/main/java/io/quarkus/websockets/next/deployment/MessageCallbackArgument.java (hunk 2 above)
Comment (mkouba) [reply extensions/websockets-next/deployment/src/main/java/io/quarkus/websockets/next/deployment/MessageCallbackArgument.java]: I believe that it could only happen very rarely.

Comment (michalvavrik) [reply extensions/websockets-next/deployment/src/main/java/io/quarkus/websockets/next/deployment/MessageCallbackArgument.java]: Agreed. Tests are green.

**Review by mkouba — APPROVED** [review]
