### PR TITLE
WebSockets Next Security: use identity stored on connection for @TestSecurity and fallback to deferred identity for lazy authentication in all situations

### LINKED ISSUE #52094: Testing authentication with `quarkus-websocket-next` breaks if you have `quarkus-test-security` enabled too
### Describe the bug

We have full end-to-end tests for our web app with Quarkus Playwright. This works fine to tests webpages protected with OIDC security, and also for WebSockets with `quarkus-websocket-next`. We leverage OIDC Dev Services and Playwright to obtain a cookie and the browser will use this to authenticate the HTTP requests and to the WebSockets.

For another use case in this app we also leverage the `quarkus-test-security` extension. For example when we want to test some custom security without doing the full web app login to get some cookies like we do with Playwright.

However we just learned that some of our end-to-end tests with WebSockets stopped working when we enabled the `quarkus-test-security` extension.

The cookie is propagated on the WebSockets (it works totally fine in dev & prod mode). The WebSocket is also allowed to open even if it has `@RolesAllowed` annotations. However in test mode we now always get an anonymous identity on the WebSocket when we define the `@OnTextMessage` method. When we remove the `quarkus-test-security` extension everything works fine again in test mode.

### Expected behavior

Quarkus returns a security identity that's associated and not anonymous for WebSockets.

```java
@WebSocket(path = "/heartbeat")
@RolesAllowed("admin")
public class HeartbeatSocket {

    @Inject
    SecurityIdentity identity;

    @OnTextMessage
    public void onMessage(String message) {
        Log.infof("Message from %s: %s", identity.getPrincipal().getName(), message);
    }
}
```

### Actual behavior

The associated security identity is anonymous on the WebSocket, however it's properly associated with the actual identity for the HTTP requests.

### How to Reproduce?

I attached a small reproducer.
1) In dev mode you will see the message from the WebSocket coming from a user in the logs
2) In test mode you will see that the messages are propagated, however that the associated identity is null

```
2026-01-20 10:38:34,335 INFO  [io.quarkus.devservices.oidc.OidcDevServicesProcessor] (build-10) Starting Dev Services for OIDC
2026-01-20 10:38:34,789 INFO  [io.quarkus.devservices.oidc.OidcDevServicesProcessor] (build-10) Dev Services for OIDC started on http://localhost:49866
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2026-01-20 10:38:35,551 INFO  [io.quarkus] (Quarkus Main Thread) quarkus-websocket-auth 1.0.0-SNAPSHOT on JVM (powered by Quarkus 3.30.6) started in 1.523s. Listening on: http://localhost:8080/openid-configuration
2026-01-20 10:38:35,552 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2026-01-20 10:38:35,552 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, compose, oidc, security, smallrye-context-propagation, vertx, websockets-next]
2026-01-20 10:38:41,601 INFO  [org.acme.HeartbeatSocket] (vert.x-worker-thread-1) Message from alice: heartbeat
2026-01-20 10:38:42,594 INFO  [org.acme.HeartbeatSocket] (vert.x-worker-thread-1) Message from alice: heartbeat
2026-01-20 10:38:43,594 INFO  [org.acme.HeartbeatSocket] (vert.x-worker-thread-1) Message from alice: heartbeat
2026-01-20 10:38:44,662 INFO  [org.acme.HeartbeatSocket] (vert.x-worker-thread-1) Message from alice: heartbeat
2026-01-20 10:38:45,761 INFO  [org.acme.HeartbeatSocket] (vert.x-worker-thread-1) Message from alice: heartbeat
2026-01-20 10:38:46,861 INFO  [org.acme.HeartbeatSocket] (vert.x-worker-thread-1) Message from alice: heartbeat
2026-01-20 10:38:47,960 INFO  [org.acme.HeartbeatSocket] (vert.x-worker-thread-1) Message from alice: heartbeat
2026-01-20 10:38:49,482 INFO  [org.acme.HeartbeatSocket] (vert.x-worker-thread-1) Message from alice: heartbeat
2026-01-20 10:38:50,484 INFO  [org.acme.HeartbeatSocket] (vert.x-worker-thread-1) Message from alice: heartbeat
2026-01-20 10:38:53,193 INFO  [io.quarkus.test] (Aesh InputStream Reader) Test output enabled
2026-01-20 10:38:54,686 INFO  [io.quarkus.devservices.oidc.OidcDevServicesProcessor] (build-18) Starting Dev Services for OIDC
2026-01-20 10:38:55,176 INFO  [io.quarkus.devservices.oidc.OidcDevServicesProcessor] (build-18) Dev Services for OIDC started on http://localhost:49918
2026-01-20 10:38:55,292 INFO  [io.quarkus.test] (Test runner thread) Running 1/1. Running: #JUnit Jupiter
2026-01-20 10:38:55,299 INFO  [io.quarkus.test] (Test runner thread) Running 1/1. Running: org.acme.HeartbeatSocketTest#HeartbeatSocketTest
2026-01-20 10:38:57,826 INFO  [io.quarkus] (Test runner thread) quarkus-websocket-auth 1.0.0-SNAPSHOT on JVM (powered by Quarkus 3.30.6) started in 3.299s. Listening on: http://localhost:8081
2026-01-20 10:38:57,827 INFO  [io.quarkus] (Test runner thread) Profile test activated. 
2026-01-20 10:38:57,828 INFO  [io.quarkus] (Test runner thread) Installed features: [cdi, compose, oidc, playwright, security, smallrye-context-propagation, vertx, websockets-next]
2026-01-20 10:38:57,833 INFO  [io.quarkus.test] (Test runner thread) Running 1/1. Running: org.acme.HeartbeatSocketTest#test()
2026-01-20 10:38:58,381 INFO  [org.acme.HeartbeatSocket] (executor-thread-1) Message from : heartbeat
2026-01-20 10:38:59,378 INFO  [org.acme.HeartbeatSocket] (executor-thread-1) Message from : heartbeat
2026-01-20 10:39:00,378 INFO  [org.acme.HeartbeatSocket] (executor-thread-1) Message from : heartbeat
2026-01-20 10:39:01,379 INFO  [org.acme.HeartbeatSocket] (executor-thread-1) Message from : heartbeat
2026-01-20 10:39:02,377 INFO  [org.acme.HeartbeatSocket] (executor-thread-1) Message from : heartbeat
2026-01-20 10:39:02,416 INFO  [io.quarkus] (Quarkus Main Thread) quarkus-websocket-auth stopped in 0.012s
```

3) Remove the `quarkus-test-security` extension and it works again

```
2026-01-20 10:40:03,306 INFO  [io.quarkus.devservices.oidc.OidcDevServicesProcessor] (build-5) Starting Dev Services for OIDC
2026-01-20 10:40:04,092 INFO  [io.quarkus.devservices.oidc.OidcDevServicesProcessor] (build-5) Dev Services for OIDC started on http://localhost:50104
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2026-01-20 10:40:04,909 INFO  [io.quarkus] (Quarkus Main Thread) quarkus-websocket-auth 1.0.0-SNAPSHOT on JVM (powered by Quarkus 3.30.6) started in 1.938s. Listening on: http://localhost:8080/openid-configuration
2026-01-20 10:40:04,909 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2026-01-20 10:40:04,909 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, compose, oidc, security, smallrye-context-propagation, vertx, websockets-next]
2026-01-20 10:40:07,886 INFO  [org.acme.HeartbeatSocket] (vert.x-worker-thread-1) Message from alice: heartbeat
2026-01-20 10:40:08,880 INFO  [org.acme.HeartbeatSocket] (vert.x-worker-thread-1) Message from alice: heartbeat
2026-01-20 10:40:12,549 INFO  [io.quarkus.test] (Aesh InputStream Reader) Test output enabled
2026-01-20 10:40:13,332 INFO  [io.quarkus.devservices.oidc.OidcDevServicesProcessor] (build-28) Starting Dev Services for OIDC
2026-01-20 10:40:13,830 INFO  [io.quarkus.devservices.oidc.OidcDevServicesProcessor] (build-28) Dev Services for OIDC started on http://localhost:50136
2026-01-20 10:40:13,986 INFO  [io.quarkus.test] (Test runner thread) Running 1/1. Running: #JUnit Jupiter
2026-01-20 10:40:13,994 INFO  [io.quarkus.test] (Test runner thread) Running 1/1. Running: org.acme.HeartbeatSocketTest#HeartbeatSocketTest
2026-01-20 10:40:16,559 INFO  [io.quarkus] (Test runner thread) quarkus-websocket-auth 1.0.0-SNAPSHOT on JVM (powered by Quarkus 3.30.6) started in 3.383s. Listening on: http://localhost:8081
2026-01-20 10:40:16,561 INFO  [io.quarkus] (Test runner thread) Profile test activated. 
2026-01-20 10:40:16,562 INFO  [io.quarkus] (Test runner thread) Installed features: [cdi, compose, oidc, playwright, security, smallrye-context-propagation, vertx, websockets-next]
2026-01-20 10:40:16,566 INFO  [io.quarkus.test] (Test runner thread) Running 1/1. Running: org.acme.HeartbeatSocketTest#test()
2026-01-20 10:40:17,093 INFO  [org.acme.HeartbeatSocket] (executor-thread-1) Message from alice: heartbeat
2026-01-20 10:40:18,091 INFO  [org.acme.HeartbeatSocket] (executor-thread-1) Message from alice: heartbeat
2026-01-20 10:40:19,090 INFO  [org.acme.HeartbeatSocket] (executor-thread-1) Message from alice: heartbeat
2026-01-20 10:40:20,091 INFO  [org.acme.HeartbeatSocket] (executor-thread-1) Message from alice: heartbeat
2026-01-20 10:40:20,186 INFO  [io.quarkus] (Shutdown thread) quarkus-websocket-auth stopped in 0.010s
```

[quarkus-websocket-auth.zip](https://github.com/user-attachments/files/24734101/quarkus-websocket-auth.zip)

### Output of `uname -a` or `ver`

Darwin Willem-Jans-MBP.i.btp34.nl 25.2.0 Darwin Kernel Version 25.2.0: Tue Nov 18 21:09:56 PST 2025; root:xnu-12377.61.12~1/RELEASE_ARM64_T6041 arm64

### Output of `java -version`

openjdk version "21.0.9" 2025-10-21 LTS OpenJDK Runtime Environment Temurin-21.0.9+10 (build 21.0.9+10-LTS) OpenJDK 64-Bit Server VM Temurin-21.0.9+10 (build 21.0.9+10-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.30.6

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.12 (848fbb4bf2d427b72bdb2471c22fced7ebd9a7a1)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by michalvavrik**
* Closes https://github.com/quarkusio/quarkus/issues/52094
* Before this PR:
  * With `@TestSecurity` we ignored the `SecurityIdentity` stored on the connection and served anonymous identity in some situations (it is not as easy to reproduce as you may think, I'd say main scenarios worked)
    * it was probably caused by https://github.com/quarkusio/quarkus/pull/48845 (Quarkus 3.29) and only Quarkus Test Security (in test mode) was affected; tested by `TestSecurityWebSocketsNextTest#testInjectionPoint_bearerTokenMechanism`
  * We only used the `SecurityIdentity` that was ready on HTTP upgrade and the deferred identity wasn't used as a source when proactive authentication was disabled
    * I think to certain extent, this was also true before 3.29, but the issues is hard to separate as it also affects reported issue with the `@TestSecurity` as well; tested by `TestSecurityWebSocketsNextTest#testSecuredInjectionPoint_bearerTokenMechanism`
* Basic test coverage is added in this PR for combination of `@TestSecurity` and the WebSockets Next, which showed me:
  * There were some (not all) scenarios where `@PermissionChecker` didn't work with `@TestSecurity`, namely when path-based authentication wasn't and when user did not use access token explicitly, so this PR makes sure the proper augmentor is applied in the test; see `TestSecurityWebSocketsNextTest#testPayloadAuthorization`

### CODE REVIEW

File: extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/AbstractSecurityIdentityAssociation.java [hunk 1]
```diff
@@ -10,6 +11,15 @@
 
 public abstract class AbstractSecurityIdentityAssociation implements CurrentIdentityAssociation {
 
+    /**
+     * {@link ValueRegistry} key that allows extensions to register their own request-scoped delegate
+     * to the @TestSecurity identity association.
+     * This only makes sense in very special cases, like in case of WebSockets Next, when the identity provided
+     * by authentication mechanisms is stored on the WebSocket connection.
+     */
+    public static ValueRegistry.RuntimeKey<CurrentIdentityAssociation> TEST_SECURITY_DELEGATE_RUNTIME_KEY = ValueRegistry.RuntimeKey
```
Comment (sberyozkin) [inline extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/AbstractSecurityIdentityAssociation.java]: Hi Michal, @michalvavrik, thanks for a quick PR.

You mentioned it can only be backported to 3.31 but it is also a problem on 3.30 which might get another release...

The other thing is I'm not sure the abstract security identity association is a medium for coordinating between WS Next Security and TestSecurity, can we think about some other approach...
Well, how about a few cosmetic updates, making it a `private static ... SECURITY_DELEGATE_RUNTIME_KEY`, and add a static getter/setter like `setSecurityDelegateRuntimeKey`, `getSecurityDelegateRuntimeKey` ?

Comment (michalvavrik) [reply extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/AbstractSecurityIdentityAssociation.java]: >  it is also a problem on 3.30 which might get another release...

It is minor problem, it does not affect many scenarios, though I understand that someone like @wjglerum can be affected heavily. I don't think we need to care about 3.30 as 3.31 will be released soon. The `ValueRegistry` is convenient, so that we avoid reflective class loading.

But there are other solutions, we could declare just new interface in security spi, if it is implemented, we use it in `TestSecurity`, otherwise we go with default. If you don't like the current idea, we can do it...

> The other thing is I'm not sure the abstract security identity association is a medium for coordinating between WS Next Security and TestSecurity, can we think about some other approach...
Well, how about a few cosmetic updates, making it a private static ... SECURITY_DELEGATE_RUNTIME_KEY, and add a static getter/setter like setSecurityDelegateRuntimeKey, getSecurityDelegateRuntimeKey ?

hmm, well I only put it onto the abstract security identity association because we don't have proper constants class for security stuff. there is something called (from top of my head) `SecurityHandlerConstants`, but it doesn't fit. so the setter and getter doesn't make sense as the `TestSecurityAssociation` does not extend it.

Comment (sberyozkin) [reply extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/AbstractSecurityIdentityAssociation.java]: Thanks @michalvavrik, can you please experiment with a security runtime delegate spi idea with a separate commit ? 
IMHO tightening it across both impacted streams would be better

Comment (michalvavrik) [reply extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/AbstractSecurityIdentityAssociation.java]: > Thanks @michalvavrik, can you please experiment with a security runtime delegate spi idea with a separate commit ? IMHO tightening it across both impacted streams would be better

Sorry if I am bit slow, but the way I understand what you want is basically to introduce a new class in a security SPI that has nothing to do with `@TestSecurity` so that we can keep it it current main and also backport it to 3.30. I don't really mind, though I showed me preference in this PR. I'll just update this PR and that is it.

**Comment by wjglerum** [comment]
Thanks @michalvavrik! Much appreciated for such a quick fix!

Can't really judge the technical implementation, but would be good if this can somehow be backported to older versions too if possible (no big blocker for me though).

I just built your feature branch locally and tested it with my reproducer app and looks good again! 🎉 

```
2026-01-21 09:43:14,237 INFO  [io.quarkus] (main) quarkus-websocket-auth 1.0.0-SNAPSHOT on JVM (powered by Quarkus 999-SNAPSHOT) started in 3.121s. Listening on: http://localhost:8081
2026-01-21 09:43:14,237 INFO  [io.quarkus] (main) Profile test activated. 
2026-01-21 09:43:14,238 INFO  [io.quarkus] (main) Installed features: [cdi, compose, oidc, playwright, security, smallrye-context-propagation, vertx, websockets-next]
2026-01-21 09:43:14,605 INFO  [io.quarkus.http.access-log] (vert.x-eventloop-thread-2) 127.0.0.1 - - [21/Jan/2026:09:43:14 +0100] "GET / HTTP/1.1" 302 -
2026-01-21 09:43:14,665 INFO  [io.quarkus.http.access-log] (vert.x-eventloop-thread-2) 127.0.0.1 - - [21/Jan/2026:09:43:14 +0100] "GET / HTTP/1.1" 302 -
2026-01-21 09:43:14,780 INFO  [io.quarkus.http.access-log] (vert.x-eventloop-thread-2) 127.0.0.1 - - [21/Jan/2026:09:43:14 +0100] "GET /?state=44051b49-f273-4f75-9c33-8b873570c7c3&code=YWxpY2V8YWRtaW4sdXNlcg== HTTP/1.1" 302 -
2026-01-21 09:43:14,793 INFO  [io.quarkus.http.access-log] (vert.x-eventloop-thread-2) 127.0.0.1 - alice [21/Jan/2026:09:43:14 +0100] "GET / HTTP/1.1" 200 565
2026-01-21 09:43:14,799 INFO  [io.quarkus.http.access-log] (vert.x-eventloop-thread-2) 127.0.0.1 - alice [21/Jan/2026:09:43:14 +0100] "GET /favicon.ico HTTP/1.1" 404 53
2026-01-21 09:43:14,810 INFO  [org.acme.HeartbeatSocket] (executor-thread-1) Message from alice: heartbeat
2026-01-21 09:43:15,810 INFO  [org.acme.HeartbeatSocket] (executor-thread-1) Message from alice: heartbeat
2026-01-21 09:43:16,810 INFO  [org.acme.HeartbeatSocket] (executor-thread-1) Message from alice: heartbeat
2026-01-21 09:43:17,810 INFO  [org.acme.HeartbeatSocket] (executor-thread-1) Message from alice: heartbeat
```

**Comment by michalvavrik** [comment]
Thanks for the confirmation @wjglerum , I planned to actually check with it as I didn't run it yet. This will spare me some time.

File: extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/AbstractSecurityIdentityAssociation.java (hunk 1 above)
Comment (sberyozkin) [reply extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/AbstractSecurityIdentityAssociation.java]: We have a specific case of a mis-alignment between WS Next and test security associations, I just hope having a somewhat more generic solution would not be a bad idea; and indeed, a 3.30 line will remain in use for a while, we don't know who else may come across the same problem that Willem saw

Comment (michalvavrik) [reply extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/AbstractSecurityIdentityAssociation.java]: Oki.

Comment (michalvavrik) [reply extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/AbstractSecurityIdentityAssociation.java]: @sberyozkin 

1. I have pushed a new version, please have a look
2. I am not sure if the mis-alignment is right term, maybe it is just my bad English; so in longer version: basically when I wrote https://github.com/quarkusio/quarkus/pull/48845, I did not consider what Test Security does, which is my bad; this PR is also improvement on what was there before, the implementation will now cover the deferred identity. (and no, I can't split this PR unless it is really important :smiley:)

**Review by sberyozkin — APPROVED** [review]

File: extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/AbstractSecurityIdentityAssociation.java (hunk 1 above)
Comment (sberyozkin) [reply extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/AbstractSecurityIdentityAssociation.java]: Hey @michalvavrik IMHO this latest version is very good, and backportable all the way to 3.30, thanks very much

Comment (michalvavrik) [reply extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/AbstractSecurityIdentityAssociation.java]: > Hey @michalvavrik IMHO this latest version is very good, and backportable all the way to 3.30, thanks very much

cool!

**Review by mkouba — APPROVED** [review]
