### PR TITLE
Fix broken collection assignability check

### LINKED ISSUE #36170: RestEasyReactive Client no longer maps List items in query param as multivalued query field in JDK21
### Describe the bug

With quarkus-resteasy-reactive, the behavior of mapping a List<> to a query param appears to have changed when running on OpenJDK 21.

Example resteasy reactive interface client:

    @GET
    @Path("/exampleAPI")
    @Produces(APPLICATION_JSON)
    Uni<List<ResponseDTO>> doRequest(
        @RestQuery("status") List<EnumField> statuses,
    ) throws BaseException;

### Expected behavior

The above code snippet maps in OpenJdk17 to

http://service:8080/exampleAPI?status=PUBLISHED&status=RELEASED

### Actual behavior

After updating to JDK21 (Amazoncoretto), it maps to

http://service:8080/exampleAPI?status=%5BPUBLISHED%2C+RELEASED%5D

or URL-decoded:

http://service:8080/exampleAPI?status=[PUBLISHED,+RELEASED]

### How to Reproduce?

Create a RESTEASY Reactive Rest client method that accepts a List of enum fields.

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

openjdk version "21" 2023-09-19 OpenJDK Runtime Environment (build 21+35-2513) OpenJDK 64-Bit Server VM (build 21+35-2513, mixed mode, sharing)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

3.3.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven 3.9.4

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
The check that was being done is broken
in Java 21 as that version bring SequencedCollection which List now implements

Closes: #36170

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]

File: independent-projects/resteasy-reactive/common/processor/src/main/java/org/jboss/resteasy/reactive/common/processor/JandexUtil.java [hunk 1]
```diff
@@ -415,4 +417,42 @@ public static boolean isImplementorOf(IndexView index, ClassInfo info, DotName n
         return isImplementorOf(index, superClass, name, additionalIgnoredSuperClasses);
     }
 
+    public static boolean isAssignableFrom(DotName name1, DotName name2, IndexView index) {
```
Comment (FroMage) [inline independent-projects/resteasy-reactive/common/processor/src/main/java/org/jboss/resteasy/reactive/common/processor/JandexUtil.java:420]: Can we have better names than `name1` and `name2`? It's already hard enough to remember which of the two parameters should be subtype/supertype, this will be confusing later.

File: independent-projects/resteasy-reactive/common/processor/src/main/java/org/jboss/resteasy/reactive/common/processor/JandexUtil.java [hunk 2]
```diff
@@ -415,4 +417,42 @@ public static boolean isImplementorOf(IndexView index, ClassInfo info, DotName n
...
+            return true;
+        }
+        // type1 is a superclass
+        return findSupertypes(name2, index).contains(name1);
+    }
+
+    private static Set<DotName> findSupertypes(DotName name, IndexView index) {
+        Set<DotName> result = new HashSet<>();
+
+        Deque<DotName> workQueue = new ArrayDeque<>();
```
Comment (FroMage) [inline independent-projects/resteasy-reactive/common/processor/src/main/java/org/jboss/resteasy/reactive/common/processor/JandexUtil.java:436]: I have to admit I've never seen this sort of implementation. Usually it's a recursive function. I assume you're flattening it on purpose to save stack space?
Also, this is not efficient because you will iterate through the work queue's inheritance entirely to look for _all_ supertypes instead of stopping as soon as you find it.

**Review by FroMage — DISMISSED** [review]
This works, for sure, but I find the algo a bit confusing, and the parameter names really should be changed.

**Comment by FroMage** [comment]
Very interesting bug, for sure!

File: independent-projects/resteasy-reactive/common/processor/src/main/java/org/jboss/resteasy/reactive/common/processor/JandexUtil.java (hunk 1 above)
Comment (geoand) [reply independent-projects/resteasy-reactive/common/processor/src/main/java/org/jboss/resteasy/reactive/common/processor/JandexUtil.java:420]: Sure yeah

File: independent-projects/resteasy-reactive/common/processor/src/main/java/org/jboss/resteasy/reactive/common/processor/JandexUtil.java (hunk 2 above)
Comment (geoand) [reply independent-projects/resteasy-reactive/common/processor/src/main/java/org/jboss/resteasy/reactive/common/processor/JandexUtil.java:436]: I pretty much copied this from Arc

Comment (geoand) [reply independent-projects/resteasy-reactive/common/processor/src/main/java/org/jboss/resteasy/reactive/common/processor/JandexUtil.java:436]: We can of course optimize, but I didn't want to in the remote case we can at some point merge the various util classes

File: independent-projects/resteasy-reactive/common/processor/src/main/java/org/jboss/resteasy/reactive/common/processor/JandexUtil.java (hunk 1 above)
Comment (geoand) [reply independent-projects/resteasy-reactive/common/processor/src/main/java/org/jboss/resteasy/reactive/common/processor/JandexUtil.java]: Fixed

File: independent-projects/resteasy-reactive/common/processor/src/main/java/org/jboss/resteasy/reactive/common/processor/JandexUtil.java (hunk 2 above)
Comment (FroMage) [reply independent-projects/resteasy-reactive/common/processor/src/main/java/org/jboss/resteasy/reactive/common/processor/JandexUtil.java:436]: Yeah, I figured this came from _somewhere_ :( I also wondered why it was not using the existing `JandexUtil` from quarkus-core-deployment, but this is not usable from `independent-projects`, same as for Arc. Interestingly, that last util class has `isSubclassOf` but not for interfaces, which means it must already exist in many forms _elsewhere_.

@mkouba any reason why Arc's `isAssignableFrom` uses `findSupertypes` instead of stopping on success?

**Review by FroMage — APPROVED** [review]
Let's not block merging this for an optimisation, but I wonder how much is the accumulated cost of this sort of issue. Probably we're not noticing these because we don't analyse build times as much as startup times?

**Comment by geoand** [comment]
One solution I can think of is to have a smallrye jandez until library that all projects can use

File: independent-projects/resteasy-reactive/common/processor/src/main/java/org/jboss/resteasy/reactive/common/processor/JandexUtil.java (hunk 2 above)
Comment (Ladicek) [reply independent-projects/resteasy-reactive/common/processor/src/main/java/org/jboss/resteasy/reactive/common/processor/JandexUtil.java:436]: I rewrote this in ArC actually, so I can comment on this. The important thing that ArC does and this utility class does not is memoization. In ArC, we remember the full set of supertypes for each class, which allows us to later answer the "is subtype of" queries instantly - we do the traversal just once.

Comment (Ladicek) [reply independent-projects/resteasy-reactive/common/processor/src/main/java/org/jboss/resteasy/reactive/common/processor/JandexUtil.java:436]: See `io.quarkus.arc.processor.AssignabilityCheck`.

Comment (Ladicek) [reply independent-projects/resteasy-reactive/common/processor/src/main/java/org/jboss/resteasy/reactive/common/processor/JandexUtil.java:436]: Also, the work queue algorithm is very common in compilers, I just mangled the name a long time ago and it kinda stuck. In compilers, it is commonly known as "worklist".

**Comment by Ladicek** [comment]
I did think about providing a "type system" library in Jandex, but it's hard. Most of the time, we don't need the full JLS subtyping rules -- like here (and in ArC), that would be just overkill. And there are other rules than just JLS in some contexts (e.g. CDI has its own assignability rules that are in certain aspects quite different from JLS). So I never really got to doing it. The `AssignabilityCheck` class in ArC is pretty decent and could be just copied here, but it's important to just have a single instance to actually leverage the memoized computations.
