### PR TITLE
Handle glob pattern for live-reload resources

### LINKED ISSUE #15820: Quarkus doesn't refresh when resource files are updated
## Describe the bug
My project has a set of json configuration files in the resources directory. We'd like Quarkus to restart and load these files when they are updated. Currently, Quarkus sees the file updates but determines that a restart isn't necessary. We know this because we see the message 'Files changed but restart not needed' when we make modifications.

### Expected behavior
Quarkus is restarted when any resource file is modified.

### Actual behavior
Quarkus is only restarted when certain resources files are modified.     Not certain what these files are, but they include banner.txt.    

## To Reproduce
1.  Add file fields.json to resources directory 
2.  Start quarkus
3.  Edit fields.json
4.  See message "Files changed but restart not needed'

### Output of `java -version`
openjdk 11.0.10

### Quarkus version or git rev
1.10.5.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Apache Maven 3.6.3

## Additional context
None.

### PR DESCRIPTION
**Pull request by glefloch**
This branch add the ability to declare glob pattern in `quarkus.live-reload.watched-resources` such as:

* `*.json`
* `**/*.xml`

One limitation of this implementation is that we look for matching file only the first time. A new file matching the glob pattern won't be watched once devmode is started. Should we look for matching file everytime? 

close #15820

### CODE REVIEW

**Comment by glefloch** [comment]
The CI failure does not look related

File: core/deployment/src/main/java/io/quarkus/deployment/dev/RuntimeUpdatesProcessor.java [hunk 1]
```diff
@@ -666,4 +675,28 @@ public void close() throws IOException {
         FSWatchUtil.shutdown();
     }
 
+    private Map<Path, Long> expandGlobPattern(Path root, Path configFile) {
+        PathMatcher pathMatcher = FileSystems.getDefault().getPathMatcher("glob:" + configFile.toString());
+        Map<Path, Long> files = new HashMap<>();
+        try {
+            Files.walkFileTree(root, new SimpleFileVisitor<Path>() {
```
Comment (stuartwdouglas) [inline core/deployment/src/main/java/io/quarkus/deployment/dev/RuntimeUpdatesProcessor.java:682]: I think we should only call this if an exists() check fails, so we don't have to walk the file system for no reason.

**Review by stuartwdouglas — CHANGES_REQUESTED** [review]
It would also be good to expand io.quarkus.test.reload.AdditionalWatchedResourcesDevModeTest to cover this scenario.

File: core/deployment/src/main/java/io/quarkus/deployment/dev/RuntimeUpdatesProcessor.java (hunk 1 above)
Comment (glefloch) [reply core/deployment/src/main/java/io/quarkus/deployment/dev/RuntimeUpdatesProcessor.java:682]: Yes, this method is only called if the file does not exist.

**Review by stuartwdouglas — APPROVED** [review]

**Review by mkouba — APPROVED** [review]
