### PR TITLE
Fix service binding for SqlServer and Oracle

### LINKED ISSUE #27461: Service binding doesn't work with Oracle and SqlServer
### Describe the bug

The `kubernetes-service-binding` extension injects database connection url with the [format](https://github.com/quarkusio/quarkus/blob/709f09dab6b4549f8401f2238b0d0c819c1a1af7/extensions/kubernetes-service-binding/runtime/src/main/java/io/quarkus/kubernetes/service/binding/runtime/DatasourceServiceBindingConfigSourceFactory.java#L71-L82): `jdbc:type://host:port/db`.

But Oracle and SqlServer use different formats of connection url:
Oracle: `jdbc:oracle:thin:@host:port/db`
Vert.X Oracle client: `oracle:thin:@host:port/db`
SqlServer: `jdbc:sqlserver://host:port;databaseName=db`

As a result, the `kubernetes-service-binding` extension doesn't work when binding to Oracle or SqlServer.

****

### Expected behavior

The `kubernetes-service-binding` extension injects correct database connection url when binding to Oracle and SqlServer.

### Actual behavior

The `kubernetes-service-binding` extension injects database connection url which is incorrect when binding to Oracle and SqlServer.

### How to Reproduce?

1. Create a simple quarkus application which connects to Oracle or SqlServer database. For example, use an application similar to the [hibernate-orm-quickstart](https://github.com/quarkusio/quarkus-quickstarts/tree/main/hibernate-orm-quickstart), and change the SQL client to be `quarkus-jdbc-oracle`, `quarkus-jdbc-mssql` or `quarkus-reactive-oracle-client`.
2. Add the `kubernetes-service-binding` extension to the project.
3. Run the Oracle or SqlServer service.
4. Follow the [instructions](https://quarkus.io/guides/deploying-to-kubernetes#service_binding) to configure the binding for Oracle or SqlServer.
5. Build and run the quarkus application.

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by xieshenzh**
fixes https://github.com/quarkusio/quarkus/issues/27461
1. Update the connection url for Oracle and SqlServer that is generated by the `kubernetes-service-binding` extension.
2. Add a new service binding configuration option `jdbc-url` to allow user to customize connection url for service binding. This is similar to what [spring-service-binding](https://github.com/spring-cloud/spring-cloud-bindings/pull/56) supports.

### CODE REVIEW

**Review by geoand — APPROVED** [review]
Thanks!

**Comment by geoand** [comment]
@gsmet does the format also look good to you?

File: extensions/jdbc/jdbc-mssql/runtime/src/main/java/io/quarkus/jdbc/mssql/runtime/MsSQLServiceBindingConverter.java [hunk 1]
```diff
@@ -13,6 +13,6 @@ public class MsSQLServiceBindingConverter implements ServiceBindingConverter {
     @Override
     public Optional<ServiceBindingConfigSource> convert(List<ServiceBinding> serviceBindings) {
         return ServiceBinding.singleMatchingByType("sqlserver", serviceBindings)
-                .map(new DatasourceServiceBindingConfigSourceFactory.Jdbc());
+                .map(new DatasourceServiceBindingConfigSourceFactory.Jdbc("jdbc:%s://%s%s;databaseName=%s"));
```
Comment (gsmet) [inline extensions/jdbc/jdbc-mssql/runtime/src/main/java/io/quarkus/jdbc/mssql/runtime/MsSQLServiceBindingConverter.java:16]: Not related to your patch but this is really brittle and close to unreadable. But let's not slow down your patch because of that as it's preexisting.

I would rather have to implement a method that takes proper parameters with names.

**Review by gsmet — APPROVED** [review]
