### PR TITLE
CORS: Allow all HTTP methods for same-origin requests

### LINKED ISSUE #51541: CORS filter complains about "wrong" method on same-origin POST request
### Describe the bug

I run a Quarkus application on `https://settings.example.com` and an associated static web site on `https://www.example.com`.

Here's the CORS config:
``` properties
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=https://www.example.com
quarkus.http.cors.methods=GET
quarkus.http.cors.access-control-allow-credentials=true
```

Notice that I do not allow `POST`, `PUT` or `DELETE` requests via CORS.

The goal here is that the web site can `GET` certain data from the application despite that application having a different origin (`settings` subdomain vs `www` subdomain).

CORS works fine. The problem occurs when the user is on the `settings` subdomain and clicks a button to change something. This results in a same-origin `POST` request (see also [this comment](https://github.com/quarkusio/quarkus/issues/29542#issuecomment-1330518692) in #29542).

### Expected behavior

After noticing that it's dealing with a same-origin request, `io.quarkus.vertx.http.runtime.cors.CORSFilter` should skip checking the method.

### Actual behavior

1. `io.quarkus.vertx.http.runtime.cors.CORSFilter` detects that it's a same-origin request: `isSameOrigin(request, origin)` returns `true`.
2. The filter accepts the origin of the request, setting `allowsOrigin` to true.
3. The filter rejects this _**same-origin non-CORS**_ request because `POST` is not allowed _**for CORS requests**_.

### How to Reproduce?

I will try to write a reproducer as soon as I find the time.

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19045.6466]

### Output of `java -version`

OpenJDK Runtime Environment Corretto-21.0.8.9.1 (build 21.0.8+9-LTS)

### Quarkus version or git rev

3.30.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.9.11

### Additional information

Though the method check is what breaks my configuration, it's not only that: I suspect that all the logic about allowed headers and credentials also should not apply to _**same-origin non-CORS requests**_.

However, one should probably research that. The specs may or may not say something like "it's illegal / frowned upon / bandwidth wasting / harmless to return CORS-related response headers for non-CORS requests".

### PR DESCRIPTION
**Pull request by michalvavrik**
* Fixes https://github.com/quarkusio/quarkus/issues/51541

### CODE REVIEW

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/cors/CORSFilter.java [hunk 1]
```diff
@@ -236,7 +240,9 @@ static boolean isSameOrigin(HttpServerRequest request, String origin) {
                         request.absoluteURI(), origin);
                 return false;
             }
-            if (substringMatch(origin, request.scheme().length() + 3, request.host(), true)) {
+            var authority = request.authority();
+            if (authority != null && authority.host() != null
```
Comment (sberyozkin) [inline extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/cors/CORSFilter.java]: I guess it would be better to cover the move from `.host()` to `.authority` in a Vert.x 5 upgrade as I guess more code around uses it, there should be some tests confirming both are equivalent... Here it looks like it is not guaranteed to identity the same origin as two extra checks for null are added, may be we should not check for null at all as the host must be set, but I'd just keep `request.host()` for now

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/cors/CORSFilter.java [hunk 2]
```diff
@@ -346,11 +352,13 @@ private void processPreFlightMethods(HttpServerResponse response, String allowMe
         }
     }
 
-    private boolean isMethodAllowed(HttpMethod method) {
-        if (wildcardMethod) {
+    private boolean isMethodAllowed(Boolean isSameOrigin, HttpServerRequest request, String origin) {
```
Comment (sberyozkin) [inline extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/cors/CORSFilter.java]: IMHO we should not even call this method if it is the same origin

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/cors/CORSFilter.java (hunk 1 above)
Comment (michalvavrik) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/cors/CORSFilter.java]: I have no problem dropping this change, but I don't really agree with arguments. Let me drop it, but I'll comment on your comment anyway.

> I guess it would be better to cover the move from .host() to .authority in a Vert.x 5 upgrade as I guess more code around uses it, there should be some tests confirming both are equivalent...

Only this filter and `io.quarkus.vertx.http.runtime.ForwardedParser` are using it. If we were counting by invocations, which may not mean anything - sure, `authority()` winds.

> Here it looks like it is not guaranteed to identity the same origin as two extra checks for null are added, may be we should not check for null at all as the host must be set, but I'd just keep request.host() for now

It can be `null` as well as it can be `null` in the current situation when the host header is missing.

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/cors/CORSFilter.java (hunk 2 above)
Comment (michalvavrik) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/cors/CORSFilter.java]: What you suggest would mean that we need to always (at that point) determine whether it is the same origin, right? This is matter of what is efficient. Evaluating `wildcard` and whether method is explicitly allowed is quick. While evaluating whether it is same origin is probably slower as there is a lot of string operations and there is some "optimization" judging by the code, e.g. `isSameOriginSlowPath`.

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/cors/CORSFilter.java (hunk 1 above)
Comment (michalvavrik) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/cors/CORSFilter.java]: I've reverted this change.

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/cors/CORSFilter.java (hunk 2 above)
Comment (sberyozkin) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/cors/CORSFilter.java]: Hi Michal, what I was thinking, `isMethodAllowed` can only be called if `allowOrigin` is `true`, therefore if `allowOrigin` was set to `true` only because it is the same origin request then we already know we do not have to call `isMethodAllowed`, as we already have `sameOrigin==true` by the time `isMethodAllowed` is called

**Comment by sberyozkin** [comment]
LGTM overall, also forgot to ask to update JavaDocs of the allowed methods property to tell users this property is not used to restrict same origin requests.

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/cors/CORSFilter.java (hunk 2 above)
Comment (michalvavrik) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/cors/CORSFilter.java]: The `allowOrigin` can _also_ be `true` if:

- `wildcard` matches
- `originMatches` matches, e.g. how do you know that CORS regex (or even one of listed origins) doesn't also fit the same origin

In which case `isSameOrigin` was never called, therefore it can be `null` even though it could still be the same origin.

**Comment by michalvavrik** [comment]
> LGTM overall, also forgot to ask to update JavaDocs of the allowed methods property to tell users this property is not used to restrict same origin requests.

The `quarkus.http.cors.methods` doc (javadoc) says `The HTTP methods allowed for CORS requests.`, doesn't it imply it is not used to restrict the same origin requests? If you still think it has value, I can add it.

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/cors/CORSFilter.java (hunk 2 above)
Comment (michalvavrik) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/cors/CORSFilter.java]: You could say that:

- users don't use `wildcard` in production
- if `originMatches` based on configured origins, users misconfigured it to also include the same origin

I can't argue with that, but I think the current code is correct if you want to be sure that "it is not the same origin".

**Comment by michalvavrik** [comment]
```
2025-12-15T23:35:39.3573117Z [ERROR] Errors: 
2025-12-15T23:35:39.3573282Z [ERROR] io.quarkus.cli.MavenProjectInfoAndUpdateTest.testClean
2025-12-15T23:35:39.3573423Z [ERROR]   Run 1: MavenProjectInfoAndUpdateTest.testClean:63 
2025-12-15T23:35:39.3573500Z expected: 0
2025-12-15T23:35:39.3573565Z  but was: 1
2025-12-15T23:35:39.3573746Z [ERROR]   Run 2: MavenProjectInfoAndUpdateTest.testClean » StackOverflow
2025-12-15T23:35:39.3573902Z [ERROR]   Run 3: MavenProjectInfoAndUpdateTest.testClean » StackOverflow
2025-12-15T23:35:39.3574049Z [ERROR]   Run 4: MavenProjectInfoAndUpdateTest.testClean » StackOverflow
```

There are no CORS in action in `MavenProjectInfoAndUpdateTest`.

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/cors/CORSFilter.java (hunk 2 above)
Comment (sberyozkin) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/cors/CORSFilter.java]: @michalvavrik Sure

Comment (michalvavrik) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/cors/CORSFilter.java]: > @michalvavrik Sure

I need tiny little more :-). I can live with your suggestion, but since I think this (my) version covers all scenarios, I need to understand what is it that you require. I don't want to introduce something for scenarios that won't happen, but personally I can imagine what I wrote above could happen and I don't know what users do.

Comment (sberyozkin) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/cors/CORSFilter.java]: @michalvavrik Hi Michal, I've been looking at the code.

So by the time this methods check is called, `allowOrigin=true`, and indeed, as you rightly observed, it can be true if it is a configured wildcard or  `originMatches=true` (possibly due to the regex) or it is the same origin.

IMHO

```
if (wildcard || originMatches) {
    if (!isMethodAllowed(request.method())) {
                LOG.debugf("Method %s is not allowed", request.method());
                response.setStatusCode(403);
                response.setStatusMessage("CORS Rejected - Invalid method");
                response.end();
                return;
      }
}
```

will be cleaner, without you having to introduce a `Boolean sameOrigin=null` and pass it to `isMethodAllowed(...)`.

Indeed, it would not work for same origin cases where a configured origin is a wildcard or includes the same origin.

I'd not be worried at all about supporting this fine grained case for checking methods with the configured wildcard origin - if someone does it then they obviously don't care about CORS as such in any case.

As for the configured origin also including the same origin, sure, they will just remove it from the configured list or tune the regex - the linked issue represents an example of a fine grained control so the users may as well make an effort and tune the origins configuration accordingly. 


By the way
```
if (!allowsOrigin) {
                response.end();
                return;
            }
```

at the end of `handle()` can be dropped as a few lines above `403` is reported if `!allowsOrigin`

**Comment by sberyozkin** [comment]
>The quarkus.http.cors.methods doc (javadoc) says The HTTP methods allowed for CORS requests., doesn't it imply it is not used to restrict the same origin requests? If you still think it has value, I can add it.

Yeah, I'd say it would help. A lot of users are confused about CORS, is same origin part of CORS or not, who knows if you haven't looked into CORS before, and it was not even obvious to us given that we are fixing it now :-).

I'd just add `this property is not used to control same origin HTTP request methods` or something like that

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/cors/CORSFilter.java (hunk 2 above)
Comment (michalvavrik) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/cors/CORSFilter.java]: Alright, I'll avoid calling `isMethodAllowed`. I don't know why should `if (wildcard || originMatches) {`  work considering that it can still be true if `isSameOrigin` returned true, so it doesn't fix the reproducer, but I presume we either do not understand each other or you didn't write it correctly. Let me fix it and then you can comment again.

Comment (michalvavrik) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/cors/CORSFilter.java]: > if (wildcard || originMatches) {

I get it now.

> at the end of handle() can be dropped as a few lines above 403 is reported if !allowsOrigin

that is only a status, we need also `end` and that is only done once all relevant headers are set

Comment (sberyozkin) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/cors/CORSFilter.java]: @michalvavrik Oops, indeed, I missed there was no `end()` above

**Review by sberyozkin — APPROVED** [review]
Thanks @michalvavrik, we might tune it closer to your original code if someone says we have this super complex regex that catches the same origin, but until then we should be good, thanks
