### PR TITLE
InjectMock should not create a new contextual instance

### LINKED ISSUE #32944: Quarkus 3: `@InjectMock` with Producer
### Describe the bug

I just updated to Quarkus 3.0.1.Final. Now I have a problem with a `@QuarkusTest`. I have a CDI-producer which has a `@RequestScoped` producer-method. In the test, I'm trying to mock the bean which would otherwise be produced with `@InjectMock`. This does not work anymore with Quarkus 3, it complains:

`jakarta.enterprise.context.ContextNotActiveException: RequestScoped context was not active when trying to obtain a bean instance for a client proxy of PRODUCER_METHOD bean`

I do not see any reason why the producer needs to be called here? I just want a mock of the bean. I've tried to annotate the test-class with `@ActivateRequestScope` but that had no effect.

It worked with 2.13.3 (and also 2.16 in the reproducer).

### Expected behavior

The original producer should not be called and therefore it should not be needed to have an active request scope.

### Actual behavior

An exception is thrown.

### How to Reproduce?

1. Extract zip: [mock-producer-request.zip](https://github.com/quarkusio/quarkus/files/11341913/mock-producer-request.zip)
2. There are 2 projects in it with the same code: One with version 2.16.6.Final and one with 3.0.1.Final
3. Start the included test in both of them, it will work with 2.x, but not with 3.x

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19045.2728]

### Output of `java -version`

OpenJDK Runtime Environment Corretto-17.0.7.7.1 (build 17.0.7+7-LTS)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

3.0.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mkouba**
- resolves #32944
- follows up on #32409

### CODE REVIEW

**Review by geoand — APPROVED** [review]
Thanks!

File: test-framework/junit5-mockito/src/main/java/io/quarkus/test/junit/mockito/internal/CreateMockitoMocksCallback.java [hunk 1]
```diff
@@ -29,24 +27,25 @@ public void afterConstruct(Object testInstance) {
...
 
-    private Optional<Object> createMockAndSetTestField(Object testInstance, Field field, Object contextualReference,
+    private Optional<Object> createMockAndSetTestField(Object testInstance, Field field, InstanceHandle<?> beanHandle,
             MockConfiguration mockConfiguration) {
-        Class<?> implementationClass = getImplementationClass(contextualReference);
+        Class<?> implementationClass = beanHandle.getBean().getImplementationClass();
         Object mock;
         boolean isNew;
-        Optional<Object> currentMock = MockitoMocksTracker.currentMock(testInstance, contextualReference);
+        // Note that beanHandle.get() returns a client proxy for normal scoped beans; i.e. the contextual instance is not created
```
Comment (Ladicek) [inline test-framework/junit5-mockito/src/main/java/io/quarkus/test/junit/mockito/internal/CreateMockitoMocksCallback.java:47]: I had to figure this out on my own only to see this comment a few seconds later :-)

**Review by Ladicek — APPROVED** [review]
