### PR TITLE
Fix Quarkus CLI TLS command help option

### LINKED ISSUE #42877: Quarkus CLI subcommand `tls` is missing help option despite showing help
### Describe the bug

Whenever I try to print out help for `tls` subcommand the CLI complaining it doesn't exist. That is strange considering tls subcommand `generate-certificate` has help alright.

### Expected behavior

Help, I need somebody help., but not just anybody, I need `help` option on the `tls` subcommand. Help me if you can, I'm feeling down.

Please compare it with `tls generate-certificate` where help works just fine:

```
[mvavrik@fedora code-with-quarkus]$ quarkus tls generate-certificate -h
Usage: tls generate-certificate [-hrV] [-c=<cn>] [-d=<directory>] -n=<name>
                                [-p=<password>]
Generate a TLS certificate with the Quarkus Dev CA if available.
  -c, --cn=<cn>       The common name of the certificate. Default is 'localhost'
  -d, --directory=<directory>
                      The directory in which the certificates will be created.
                        Default is `.certs`
  -h, --help          Show this help message and exit.
  -n, --name=<name>   Name of the certificate. It will be used as file name and
                        alias in the keystore
  -p, --password=<password>
                      The password of the keystore. Default is 'password'
  -r, --renew         Whether existing certificates will need to be replaced
  -V, --version       Print version information and exit.
[mvavrik@fedora code-with-quarkus]$ quarkus tls generate-certificate --help
Usage: tls generate-certificate [-hrV] [-c=<cn>] [-d=<directory>] -n=<name>
                                [-p=<password>]
Generate a TLS certificate with the Quarkus Dev CA if available.
  -c, --cn=<cn>       The common name of the certificate. Default is 'localhost'
  -d, --directory=<directory>
                      The directory in which the certificates will be created.
                        Default is `.certs`
  -h, --help          Show this help message and exit.
  -n, --name=<name>   Name of the certificate. It will be used as file name and
                        alias in the keystore
  -p, --password=<password>
                      The password of the keystore. Default is 'password'
  -r, --renew         Whether existing certificates will need to be replaced
  -V, --version       Print version information and exit.
```

### Actual behavior

I get help, but also complain that the option doesn't exist :-)

```
[mvavrik@fedora code-with-quarkus]$ quarkus tls --help
Unknown option: '--help'
Install and Manage TLS development certificates
Usage: tls [COMMAND]
Commands:
  generate-quarkus-ca   Generate Quarkus Dev CA certificate and private key.
  generate-certificate  Generate a TLS certificate with the Quarkus Dev CA if
                          available.
  lets-encrypt          Prepare, generate and renew Let's Encrypt Certificates
[mvavrik@fedora code-with-quarkus]$ quarkus tls -h
Unknown option: '-h'
Install and Manage TLS development certificates
Usage: tls [COMMAND]
Commands:
  generate-quarkus-ca   Generate Quarkus Dev CA certificate and private key.
  generate-certificate  Generate a TLS certificate with the Quarkus Dev CA if
                          available.
  lets-encrypt          Prepare, generate and renew Let's Encrypt Certificates
[mvavrik@fedora code-with-quarkus]$ quarkus tls help
Unmatched argument at index 0: 'help'
Install and Manage TLS development certificates
Usage: tls [COMMAND]
Commands:
  generate-quarkus-ca   Generate Quarkus Dev CA certificate and private key.
  generate-certificate  Generate a TLS certificate with the Quarkus Dev CA if
                          available.
  lets-encrypt          Prepare, generate and renew Let's Encrypt Certificates
```

### How to Reproduce?

1. `quarkus create app --extensions=tls-registry`
2. `cd code-with-quarkus`
3. one of:
  - `quarkus tls --help`
  - `quarkus tls -h`

### Output of `uname -a` or `ver`

Fedora 40

### Output of `java -version`

Temurin-21.0.1+12

### Quarkus version or git rev

999-SNAPSHOT && 3.14.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.9

### Additional information

Quarkus CLI 3.14.1.

### PR DESCRIPTION
**Pull request by michalvavrik**
- Closes: #42877

### CODE REVIEW

**Review by gsmet — APPROVED** [review]
LGTM but I will let @cescoffier approve and merge.

File: extensions/tls-registry/cli/src/main/java/io/quarkus/tls/cli/GenerateCertificateCommand.java [hunk 1]
```diff
@@ -64,7 +64,7 @@ public class GenerateCertificateCommand implements Callable<Integer> {
         Security.addProvider(new org.bouncycastle.jce.provider.BouncyCastleProvider());
     }
 
-    static System.Logger LOGGER = System.getLogger("generate-quarkus-ca");
+    static System.Logger LOGGER = System.getLogger("generate-certificate");
```
Comment (cescoffier) [inline extensions/tls-registry/cli/src/main/java/io/quarkus/tls/cli/GenerateCertificateCommand.java:67]: Nice catch! That's what happens when you're so used to Quarkus.Log :-)

**Review by cescoffier — APPROVED** [review]
