### PR TITLE
Quarkus gRPC security interceptor + non-blocking security check

### LINKED ISSUE #20332: Security annotations with Mutiny
### Description

Security annotations, such as `@Authenticated` or `@RolesAllowed` should would with Mutiny. I'm not sure if they are working correctly with RESTEasy Reactive, but they are not working with other Mutiny methods such as gRPC implementations. When invoking non-blocking gRPC implementation annotated with `@RolesAllowed` this exception is thrown: 

```
io.quarkus.runtime.BlockingOperationNotAllowedException: Cannot call getIdentity() from the IO thread when lazy authentication is in use, as resolving the identity may block the thread. Instead you should inject the CurrentIdentityAssociation, call CurrentIdentityAssociation#getDeferredIdentity() and subscribe to the Uni.
	at io.quarkus.security.runtime.SecurityIdentityAssociation.getIdentity(SecurityIdentityAssociation.java:68)
	at io.quarkus.security.runtime.SecurityIdentityAssociation_Subclass.getIdentity$$superforward1(SecurityIdentityAssociation_Subclass.zig:193)
	at io.quarkus.security.runtime.SecurityIdentityAssociation_Subclass$$function$$1.apply(SecurityIdentityAssociation_Subclass$$function$$1.zig:24)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(InvocationInterceptor_Bean.zig:521)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at io.quarkus.security.runtime.SecurityIdentityAssociation_Subclass.getIdentity(SecurityIdentityAssociation_Subclass.zig:307)
	at io.quarkus.security.runtime.SecurityIdentityAssociation_ClientProxy.getIdentity(SecurityIdentityAssociation_ClientProxy.zig:250)
	at io.quarkus.security.runtime.SecurityIdentityProxy.hasRole(SecurityIdentityProxy.java:38)
	at io.quarkus.security.runtime.SecurityIdentityProxy_Subclass.hasRole$$superforward1(SecurityIdentityProxy_Subclass.zig:371)
	at io.quarkus.security.runtime.SecurityIdentityProxy_Subclass$$function$$4.apply(SecurityIdentityProxy_Subclass$$function$$4.zig:33)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(InvocationInterceptor_Bean.zig:521)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at io.quarkus.security.runtime.SecurityIdentityProxy_Subclass.hasRole(SecurityIdentityProxy_Subclass.zig:797)
	at io.quarkus.security.runtime.SecurityIdentityProxy_ClientProxy.hasRole(SecurityIdentityProxy_ClientProxy.zig:401)
	at io.quarkus.security.runtime.interceptor.check.RolesAllowedCheck.apply(RolesAllowedCheck.java:55)
	at io.quarkus.security.runtime.interceptor.SecurityConstrainer.check(SecurityConstrainer.java:28)
	at io.quarkus.security.runtime.interceptor.SecurityConstrainer_Subclass.check$$superforward1(SecurityConstrainer_Subclass.zig:100)
	at io.quarkus.security.runtime.interceptor.SecurityConstrainer_Subclass$$function$$1.apply(SecurityConstrainer_Subclass$$function$$1.zig:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(InvocationInterceptor_Bean.zig:521)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at io.quarkus.security.runtime.interceptor.SecurityConstrainer_Subclass.check(SecurityConstrainer_Subclass.zig:170)
	at io.quarkus.security.runtime.interceptor.SecurityHandler.handle(SecurityHandler.java:23)
	at io.quarkus.security.runtime.interceptor.SecurityHandler_Subclass.handle$$superforward1(SecurityHandler_Subclass.zig:137)
	at io.quarkus.security.runtime.interceptor.SecurityHandler_Subclass$$function$$2.apply(SecurityHandler_Subclass$$function$$2.zig:33)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(InvocationInterceptor_Bean.zig:521)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at io.quarkus.security.runtime.interceptor.SecurityHandler_Subclass.handle(SecurityHandler_Subclass.zig:296)
	at io.quarkus.security.runtime.interceptor.RolesAllowedInterceptor.intercept(RolesAllowedInterceptor.java:29)
	at io.quarkus.security.runtime.interceptor.RolesAllowedInterceptor_Bean.intercept(RolesAllowedInterceptor_Bean.zig:386)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at org.example.GreeterImpl_Subclass.hello(GreeterImpl_Subclass.zig:166)
	at org.example.api.GreeterBean.hello(GreeterBean.java:21)
	at io.quarkus.grpc.runtime.ServerCalls.oneToOne(ServerCalls.java:29)
	at org.example.api.MutinyGreeterGrpc$MethodHandlers.invoke(MutinyGreeterGrpc.java:116)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.quarkus.grpc.runtime.supports.context.GrpcRequestContextGrpcInterceptor$1.onHalfClose(GrpcRequestContextGrpcInterceptor.java:81)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:797)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at io.quarkus.grpc.runtime.GrpcServerRecorder$DevModeWrapper.run(GrpcServerRecorder.java:495)
	at io.quarkus.grpc.runtime.GrpcServerRecorder$9$2.handle(GrpcServerRecorder.java:388)
	at io.quarkus.grpc.runtime.GrpcServerRecorder$9$2.handle(GrpcServerRecorder.java:385)
	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
	at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### Implementation ideas

As there is more and more focus on reactive implementations, it would be useful if these annotations work with Mutiny (and similar references as CompletionStage). There is already a similar implementation for cache and transactions I think.

Sorry if this is a wrong kind of an issue.

### PR DESCRIPTION
**Pull request by michalszynkiewicz**
This PR introduces an abstract superclass to ease authentication of gRPC services.

Futhermore, it modifies the security check used everywhere to try to perform the check in a non-blocking manner if the return type is async (e.g. Uni). This way, even if we only have `defferedIdentity`, we can perform the check for async return types.

fixes #20332

### CODE REVIEW

**Comment by michalszynkiewicz** [comment]
cc @cescoffier

File: extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityConstrainer.java [hunk 1]
```diff
@@ -5,18 +5,21 @@
...
 /**
  * @author Michal Szynkiewicz, michal.l.szynkiewicz@gmail.com
  */
 @Singleton
 public class SecurityConstrainer {
 
+    public static final Uni<Object> CHECK_OK = Uni.createFrom().item(new Object());
     @Inject
-    SecurityIdentity identity;
+    SecurityIdentityAssociation identity;
```
Comment (sberyozkin) [inline extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityConstrainer.java:22]: `SecurtyIdentity` is injected from `SecurityIdentityAssociation#getIdentity` and the GRPC filter sets it, so why it has to be replaced ?

File: extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityHandler.java [hunk 2]
```diff
@@ -20,8 +27,42 @@ public Object handle(InvocationContext ic) throws Exception {
         if (alreadyHandled(ic)) {
             return ic.proceed();
         }
-        constrainer.check(ic.getMethod(), ic.getParameters());
-        return ic.proceed();
+        Class<?> returnType = ic.getMethod().getReturnType();
+        if (Uni.class.isAssignableFrom(returnType)) {
+            return constrainer.nonBlockingCheck(ic.getMethod(), ic.getParameters())
+                    .onItem().transformToUni(new Function<Object, Uni<?>>() {
+                        @Override
```
Comment (sberyozkin) [inline extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityHandler.java:34]: Minor one, may be this function can be an internal class parameterized by its return type, and statically created for these 3 types, in case creating a new instance every time might be of some concern

**Comment by sberyozkin** [comment]
@michalszynkiewicz Hi Michal - looks fine to me, linking GRPC to the identity providers is good, but I'm a bit conscious of missing some subtle performance problem here.
I think it is probably the first try at linking non-HTTP aware extension with `IdentityProviders` which is great. I wonder though if it makes to look at how `vertx-http/../HttpAuthenticator` orchestrates it to support the similar expectation. Though may be it is a task for the follow up PR

File: extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityConstrainer.java (hunk 1 above)
Comment (michalszynkiewicz) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityConstrainer.java:22]: for async invocation, we want to support security checks even if we don't have the entity set yet. That's why the `nonBlockingCheck` uses `SecurityIdentityAssociation#getDeferredIdentity()`.
This is not possible with using `SecurityIdentity` directly

Comment (sberyozkin) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityConstrainer.java:22]: Makes sense

**Comment by sberyozkin** [comment]
@michalszynkiewicz 

> do you mean having a single interceptor that would have a list of grpc authentication mechanisms? If yes, indeed, it makes sense. I thought of it as an improvement for later but it doesn't seem that complicated, I'll try to add it to this PR

Sounds good to have it for later - I'd indeed consider having a single GRPC authenticator driving the whole process, so that 1) say GRPC JWT mechanism would pick up JWT from GRPC metadata and submit the auth request to IdentityProiderManager, but also similarly to `HttpAuthenticator` 2) it would handle the proactive vs non-proactive auth - but it would significantly complicate this PR so IMHO it would be fine to follow up with 1 o2 2 PRs to align it with how `HttpAuthenticator` handles it

File: extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityHandler.java (hunk 2 above)
Comment (sberyozkin) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityHandler.java:34]: If you'd like you can resolve it, I don't really mind how it is handled, is probably very optimized once compiled with the functions

Comment (sberyozkin) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityHandler.java:34]: We have a ton of functions in the OIDC code the only difference is that they are all unique in their structure, but here they are the same hence I suggested it :-)

Comment (michalszynkiewicz) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityHandler.java]: not sure it changes a lot but I pulled them out

**Comment by michalszynkiewicz** [comment]
We'll need some documentation for it but I'd rather add it in a separate PR

File: extensions/grpc/deployment/pom.xml [hunk 3]
```diff
@@ -29,6 +29,10 @@
             <groupId>io.quarkus</groupId>
             <artifactId>quarkus-grpc</artifactId>
         </dependency>
+        <dependency>
+            <groupId>io.quarkus</groupId>
+            <artifactId>quarkus-security-deployment</artifactId>
```
Comment (mkouba) [inline extensions/grpc/deployment/pom.xml:34]: This basically means that the security extension is always added for a gPRC app. Shouldn't it be rather optional?

File: extensions/grpc/runtime/src/main/java/io/quarkus/grpc/auth/GrpcSecurityInterceptor.java [hunk 4]
```diff
@@ -0,0 +1,119 @@
...
+    IdentityProviderManager identityProviderManager;
+
+    @Inject
+    SecurityIdentityAssociation identityAssociation;
+
+    private final AuthExceptionHandlerProvider exceptionHandlerProvider;
+    private final List<GrpcSecurityMechanism> securityMechanisms;
+
+    @Inject
+    public GrpcSecurityInterceptor(Instance<GrpcSecurityMechanism> securityMechanisms,
```
Comment (mkouba) [inline extensions/grpc/runtime/src/main/java/io/quarkus/grpc/auth/GrpcSecurityInterceptor.java:49]: This is just nitpicking but why do you use both the field and constructor injection? I think it's reasonable to stick with one style. In this particular case, I'd go with constructor injection and make the `identityProviderManager` and `identityAssociation` fields `final` ;-).

**Review by mkouba — COMMENTED** [review]
+1 for some docs. It would help a little to understand the motivation and background...

File: extensions/grpc/runtime/src/main/java/io/quarkus/grpc/auth/GrpcSecurityInterceptor.java (hunk 4 above)
Comment (michalszynkiewicz) [reply extensions/grpc/runtime/src/main/java/io/quarkus/grpc/auth/GrpcSecurityInterceptor.java:49]: 👍🏻 If I do a rework, I'll change that

Comment (michalszynkiewicz) [reply extensions/grpc/runtime/src/main/java/io/quarkus/grpc/auth/GrpcSecurityInterceptor.java]: done

File: extensions/grpc/deployment/pom.xml [hunk 5]
```diff
@@ -29,6 +29,11 @@
             <groupId>io.quarkus</groupId>
             <artifactId>quarkus-grpc</artifactId>
         </dependency>
+        <dependency>
+            <groupId>io.quarkus</groupId>
```
Comment (stuartwdouglas) [inline extensions/grpc/deployment/pom.xml:33]: You should be able to depend on io.quarkus.security:quarkus-security, which should contain the interfaces etc you need.

File: extensions/grpc/runtime/pom.xml [hunk 6]
```diff
@@ -29,6 +29,11 @@
             <groupId>io.quarkus</groupId>
             <artifactId>quarkus-arc</artifactId>
         </dependency>
+        <dependency>
+            <groupId>io.quarkus</groupId>
```
Comment (stuartwdouglas) [inline extensions/grpc/runtime/pom.xml:33]: same here.

File: extensions/grpc/runtime/src/main/java/io/quarkus/grpc/auth/GrpcSecurityInterceptor.java [hunk 7]
```diff
@@ -0,0 +1,122 @@
...
+ * Security interceptor invoking {@link GrpcSecurityMechanism} implementations
+ */
+@GlobalInterceptor
+@Singleton
+public final class GrpcSecurityInterceptor implements ServerInterceptor, Prioritized {
+
+    private static final Logger log = Logger.getLogger(GrpcSecurityInterceptor.class);
+
+    private final IdentityProviderManager identityProviderManager;
+    private final SecurityIdentityAssociation identityAssociation;
```
Comment (stuartwdouglas) [inline extensions/grpc/runtime/src/main/java/io/quarkus/grpc/auth/GrpcSecurityInterceptor.java:40]: This should be able to just be the `io.quarkus.security.identity.CurrentIdentityAssociation` interface instead.

**Review by stuartwdouglas — CHANGES_REQUESTED** [review]

File: extensions/grpc/deployment/pom.xml (hunk 5 above)
Comment (michalszynkiewicz) [reply extensions/grpc/deployment/pom.xml]: done

File: extensions/grpc/runtime/pom.xml (hunk 6 above)
Comment (michalszynkiewicz) [reply extensions/grpc/runtime/pom.xml]: done

**Review by stuartwdouglas — APPROVED** [review]
