### PR TITLE
IdGeneration strategies initialized as part of the pre-recorded Metadata

### LINKED ISSUE #1743: Register Hibernate @GenericGenerator strategy implementations for reflective access
@Sanne (as discussed on Zulip):
I have an entity using org.hibernate.id.UUIDGenerator:
```
public class AuthenticationRequest {

    @Id
    @GeneratedValue(generator = "UUID")
    @GenericGenerator(
            name = "UUID",
            strategy = "org.hibernate.id.UUIDGenerator"
    )
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;
```
This works fine in Java but when running in native mode I get:
```
Caused by: org.hibernate.MappingException: Could not interpret id generator strategy [org.hibernate.id.UUIDGenerator]
    at org.hibernate.id.factory.internal.DefaultIdentifierGeneratorFactory.getIdentifierGeneratorClass(DefaultIdentifierGeneratorFactory.java:144)
    at org.hibernate.mapping.SimpleValue.isIdentityColumn(SimpleValue.java:378)
    at org.hibernate.tool.schema.internal.StandardTableExporter.getSqlCreateStrings(StandardTableExporter.java:60)
    at org.hibernate.tool.schema.internal.StandardTableExporter.getSqlCreateStrings(StandardTableExporter.java:30)
    at org.hibernate.tool.schema.internal.SchemaCreatorImpl.createFromMetadata(SchemaCreatorImpl.java:316)
    at org.hibernate.tool.schema.internal.SchemaCreatorImpl.performCreation(SchemaCreatorImpl.java:166)
    at org.hibernate.tool.schema.internal.SchemaCreatorImpl.doCreation(SchemaCreatorImpl.java:135)
    at org.hibernate.tool.schema.internal.SchemaCreatorImpl.doCreation(SchemaCreatorImpl.java:121)
    at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:155)
```
Kabir Khan: Is there some trick I need to perform, or is it a bug?
Kabir Khan: BTW I am planning on ripping out this entity so it isn't a huge deal
Sanne Grinovero: @Kabir Khan ah! thanks that's a useful bugreport :) Yes we probably need to register those strategy implementations for reflective access, didn't think of that.
Kabir Khan: Cool

### PR DESCRIPTION
**Pull request by Sanne**
replaces #1767 and fixes #1743

Many thanks to @geoand for giving it a shot. Sorry it wasn't as simple as I initially thought!

### CODE REVIEW

**Comment by geoand** [comment]
No problem at all!

File: extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/service/QuarkusMutableIdentifierGeneratorFactory.java [hunk 1]
```diff
@@ -0,0 +1,82 @@
...
+ * will look them up by either fully qualified name (and then reflection) or strategy name.
+ *
+ * Since all IdentifierGenerator types used by a model are accessed during the Metadata creation,
+ * just watching for these will provide the full list of Class instances we need to keep.
+ */
+public final class QuarkusMutableIdentifierGeneratorFactory
+        implements MutableIdentifierGeneratorFactory, Serializable, ServiceRegistryAwareService {
+
+    private final DefaultIdentifierGeneratorFactory original = new DefaultIdentifierGeneratorFactory();
+    private final ConcurrentHashMap<String, Class<? extends IdentifierGenerator>> typeCache = new ConcurrentHashMap<>();
```
Comment (gsmet) [inline extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/service/QuarkusMutableIdentifierGeneratorFactory.java]: Just wondering if we should clear this cache at some point, considering we keep references to the classes? Or is it taken care of somehow?

Comment (Sanne) [reply extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/service/QuarkusMutableIdentifierGeneratorFactory.java]: No we don't want to clear them as they are used by ORM at runtime:
- the instance is scoped for the specific SessionFactgory instance
- It will only contain references to Class instance of the few ID generators actually used (stuff which is going to be on the heap even if we don't refer to it)

**Comment by Sanne** [comment]
@gsmet approved? would be good to have this in

**Review by gsmet — APPROVED** [review]
