### PR TITLE
Small OpenAPI and Swagger UI enhancements

### LINKED ISSUE #18614: Swagger UI should automatically inject Authorization header when JWT is specified.
### Describe the bug

From https://stackoverflow.com/questions/68327095/how-do-i-properly-auth-with-jwt-to-openapi-ui-for-quarkus-smallyre-jwt

The UI doesn’t inject the Authorization header into the cURL command.

### Expected behavior

The UI should inject `-H “Authorization: <type> <JWT>”` into the cURL command.

### Actual behavior

CURL happens without a -H `”Authorization…”` entry.

### How to Reproduce?

1. application.yml:

```yml
    …
    smallrye-openapi:
      ...
      jwt-bearer-format: JWT
      jwt-security-scheme-value: Bearer
      security-scheme: jwt
```

1. Run using the dev profile, head to localhost, pull up the Swagger UI page, put anything into the authentication padlock, click on a secured endpoint, see missing header in CURL and 401 response. 

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

11.0.2 (OpenJDK)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.0.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

```sh
Gradle 6.8.3
------------------------------------------------------------

Build time:   2021-02-22 16:13:28 UTC
Revision:     9e26b4a9ebb910eaa1b8da8ff8575e514bc61c78

Kotlin:       1.4.20
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.2 (Oracle Corporation 11.0.2+9)
OS:           Windows 10 10.0 amd64
```

### Additional information

_No response_

### LINKED ISSUE #19113: quarkus.swagger-ui.oauth2-redirect-url documentation and default value
### Description

So I battled swagger-ui + oidc with auth code or implicit flow with redirects and such.
The problem was after successful login in oauth provider the redirect led to localhost:8080/oauth2-redirect.html
And there was 404.

The solution was found here in the last comment: https://github.com/quarkusio/quarkus/issues/4766 Many thanks to Phillip.

I set this property and it worked fine.
`quarkus.swagger-ui.oauth2-redirect-url=/q/swagger-ui/oauth2-redirect.html`

### Implementation ideas

I believe the setting `quarkus.swagger-ui.oauth2-redirect-url` should be set to `/q/swagger-ui/oauth2-redirect.html` by default. Or maybe if I'm wrong it might be good to add some more explanation to the property meaning in docs.

### LINKED ISSUE #19131: Allow multiple static openapi.yaml/json files
### Description

A service might implement multiple predefined APIs when using an API-first approach. I can also generate the appropriate model and API classes with the openapi generator by configuring multiple executions of the maven plugin with different input definition files. However, the ability of the openapi plugin for serving a static definition is currently limited to a single `openapi.yaml` or `openapi.json` file. Having the possibility to specify multiple files would aid when implementing several predefined API specifications and would avoid the need to manually merge them.

### Implementation ideas

Maybe extending the list of searched paths to something like

```
META-INF/openapi/*.json
META-INF/openapi/*.yaml
```

would already be sufficient.

The configuration property should probably also accept a list of file names.

### PR DESCRIPTION
**Pull request by phillip-kruger**
This PR contains some small enhancements to the OpenAPI and Swagger UI extensions:

- Auto add the `Security Requirement` for REST Endpoints that has `RolesAllowed` 
- Set a more appropriate default title and version
- Set the correct default `oauth2RedirectUrl ` in swagger-ui
- Allow multiple static OpenAPI model documents
- Upgrade to SmallRye OpenAPI 2.1.9 (see https://github.com/smallrye/smallrye-open-api/releases/tag/2.1.9)

Fix #18614
Fix #19113
Fix #19131

It might be easier to review per commit.

### CODE REVIEW

**Comment by gsmet** [comment]
@geoand the failure in `io.quarkus.resteasy.reactive.server.test.simple.SimpleQuarkusRestTestCase.testWriter` looks a bit suspicious.

**Comment by phillip-kruger** [comment]
@gsmet @geoand yes, I need to fix those, the default name is now the app name and not Generated API anymore. The tests needs to be updated. I did not run the integration tests locally so I missed that. I'll update soon

File: extensions/smallrye-openapi-common/deployment/src/main/java/io/quarkus/smallrye/openapi/common/deployment/SmallRyeOpenApiConfig.java [hunk 1]
```diff
@@ -50,6 +58,12 @@
     @ConfigItem(defaultValue = "Authentication")
     public String securitySchemeDescription;
 
+    /**
+     * This will automatically add the security requirement to all methods that has a `RolesAllowed` annotation.
```
Comment (geoand) [inline extensions/smallrye-openapi-common/deployment/src/main/java/io/quarkus/smallrye/openapi/common/deployment/SmallRyeOpenApiConfig.java:62]: How about classes that are annotated with this?

File: extensions/smallrye-openapi/deployment/src/main/java/io/quarkus/smallrye/openapi/deployment/SmallRyeOpenApiProcessor.java [hunk 2]
```diff
@@ -509,6 +595,14 @@ private Result findStaticModel() {
     private OpenApiDocument loadDocument(OpenAPI staticModel, OpenAPI annotationModel,
             List<AddToOpenAPIDefinitionBuildItem> openAPIBuildItems) {
         OpenApiDocument document = prepareOpenApiDocument(staticModel, annotationModel, openAPIBuildItems);
+
+        Config c = ConfigProvider.getConfig();
+        String title = c.getOptionalValue("quarkus.application.name", String.class).orElse("Generated");
+        String version = c.getOptionalValue("quarkus.application.version", String.class).orElse("1.0");
```
Comment (geoand) [inline extensions/smallrye-openapi/deployment/src/main/java/io/quarkus/smallrye/openapi/deployment/SmallRyeOpenApiProcessor.java:601]: Not important at all, but elsewhere we use `<<unset>>`

File: extensions/swagger-ui/deployment/src/test/java/io/quarkus/swaggerui/deployment/SwaggerOptionsTest.java [hunk 3]
```diff
@@ -31,7 +31,7 @@ public void customOptions() {
                         containsString("https://petstore.swagger.io/v2/swagger.json"),
                         containsString("theme-newspaper.css"),
                         containsString("docExpansion: 'full'"),
-                        containsString("oauth2RedirectUrl: '/somesecure/page/oauth.html'"),
+                        containsString("var oar = \"/somesecure/page/oauth.html\";"),
```
Comment (geoand) [inline extensions/swagger-ui/deployment/src/test/java/io/quarkus/swaggerui/deployment/SwaggerOptionsTest.java:34]: I have no idea about this, but I trust it's correct :)

File: extensions/smallrye-openapi-common/deployment/src/main/java/io/quarkus/smallrye/openapi/common/deployment/SmallRyeOpenApiConfig.java [hunk 4]
```diff
@@ -33,6 +34,13 @@
     @ConfigItem(defaultValue = "false")
     public boolean ignoreStaticDocument;
 
+    /**
+     * A list of local directories that should be scanned for yaml and/or json files to be included in the static model.
+     * Example: `META-INF/openapi/`
+     */
+    @ConfigItem
+    public Optional<List<Path>> additionalStaticDocumentsDirectory;
```
Comment (geoand) [inline extensions/smallrye-openapi-common/deployment/src/main/java/io/quarkus/smallrye/openapi/common/deployment/SmallRyeOpenApiConfig.java:42]: This is kind of a mouthful :). Maybe just `additionalDosDirectory`?

Comment (geoand) [inline extensions/smallrye-openapi-common/deployment/src/main/java/io/quarkus/smallrye/openapi/common/deployment/SmallRyeOpenApiConfig.java:42]: This is kind of a mouthful :). Maybe just `additionalDocsDirectory`?

File: extensions/smallrye-openapi-common/deployment/src/main/java/io/quarkus/smallrye/openapi/common/deployment/SmallRyeOpenApiConfig.java (hunk 1 above)
Comment (phillip-kruger) [reply extensions/smallrye-openapi-common/deployment/src/main/java/io/quarkus/smallrye/openapi/common/deployment/SmallRyeOpenApiConfig.java:62]: You mean what if the class already have the `@SecurityRequirement` annotation ? Then we just use the annotation value.

File: extensions/smallrye-openapi/deployment/src/main/java/io/quarkus/smallrye/openapi/deployment/SmallRyeOpenApiProcessor.java (hunk 2 above)
Comment (phillip-kruger) [reply extensions/smallrye-openapi/deployment/src/main/java/io/quarkus/smallrye/openapi/deployment/SmallRyeOpenApiProcessor.java:601]: What is `<<unset>>` ? You mean in the orElse ? I kept the orElse as it was previously. This only apply in tests where the application name is not set. This makes the test cases pass.

**Comment by geoand** [comment]
Good stuff!

I only added a few minor comments. Also, can we the last commit be squashed into whatever commit introduced the broken tests? 
That way we won't have intermediate state that doesn't build properly

File: extensions/smallrye-openapi-common/deployment/src/main/java/io/quarkus/smallrye/openapi/common/deployment/SmallRyeOpenApiConfig.java (hunk 1 above)
Comment (geoand) [reply extensions/smallrye-openapi-common/deployment/src/main/java/io/quarkus/smallrye/openapi/common/deployment/SmallRyeOpenApiConfig.java:62]: No, I mean if the class is annotated with `@RolesAllowed`. Is that currently handled? Because reading this Javadoc I would guess that it isn't

File: extensions/smallrye-openapi/deployment/src/main/java/io/quarkus/smallrye/openapi/deployment/SmallRyeOpenApiProcessor.java (hunk 2 above)
Comment (geoand) [reply extensions/smallrye-openapi/deployment/src/main/java/io/quarkus/smallrye/openapi/deployment/SmallRyeOpenApiProcessor.java:601]: Yeah, I meant for the `orElse`. But as I mentioned, it doesn't matter at all

File: extensions/swagger-ui/deployment/src/test/java/io/quarkus/swaggerui/deployment/SwaggerOptionsTest.java (hunk 3 above)
Comment (phillip-kruger) [reply extensions/swagger-ui/deployment/src/test/java/io/quarkus/swaggerui/deployment/SwaggerOptionsTest.java:34]: Yes, because the oauth redirect is now appending the host and port when relative I needed some javascript so, the value that gets replaced by the java code is not in the `const` anymore, but in the function. Hope that make sense

File: extensions/smallrye-openapi-common/deployment/src/main/java/io/quarkus/smallrye/openapi/common/deployment/SmallRyeOpenApiConfig.java (hunk 4 above)
Comment (phillip-kruger) [reply extensions/smallrye-openapi-common/deployment/src/main/java/io/quarkus/smallrye/openapi/common/deployment/SmallRyeOpenApiConfig.java:42]: Cool, I'll change that.

File: extensions/smallrye-openapi-common/deployment/src/main/java/io/quarkus/smallrye/openapi/common/deployment/SmallRyeOpenApiConfig.java (hunk 1 above)
Comment (phillip-kruger) [reply extensions/smallrye-openapi-common/deployment/src/main/java/io/quarkus/smallrye/openapi/common/deployment/SmallRyeOpenApiConfig.java:62]: Ok, so you can annotation a class with `RolesAllowed` and that applies to all methods ? I did not think of that ? Let me see if I can add that.

**Comment by phillip-kruger** [comment]
@geoand  - thanks for the review, I'll make the changes as requested soon

File: extensions/smallrye-openapi/deployment/src/main/java/io/quarkus/smallrye/openapi/deployment/SmallRyeOpenApiProcessor.java (hunk 2 above)
Comment (phillip-kruger) [reply extensions/smallrye-openapi/deployment/src/main/java/io/quarkus/smallrye/openapi/deployment/SmallRyeOpenApiProcessor.java:601]: Ok, I am keeping it as it, to make the tests pass without having to change them :)

Comment (geoand) [reply extensions/smallrye-openapi/deployment/src/main/java/io/quarkus/smallrye/openapi/deployment/SmallRyeOpenApiProcessor.java:601]: 👍🏼 . Sounds good

File: extensions/smallrye-openapi-common/deployment/src/main/java/io/quarkus/smallrye/openapi/common/deployment/SmallRyeOpenApiConfig.java (hunk 1 above)
Comment (phillip-kruger) [reply extensions/smallrye-openapi-common/deployment/src/main/java/io/quarkus/smallrye/openapi/common/deployment/SmallRyeOpenApiConfig.java]: This now also works for class level annotations

File: extensions/smallrye-openapi-common/deployment/src/main/java/io/quarkus/smallrye/openapi/common/deployment/SmallRyeOpenApiConfig.java (hunk 4 above)
Comment (phillip-kruger) [reply extensions/smallrye-openapi-common/deployment/src/main/java/io/quarkus/smallrye/openapi/common/deployment/SmallRyeOpenApiConfig.java]: Changed

**Review by geoand — APPROVED** [review]

**Comment by phillip-kruger** [comment]
@geoand @gsmet I am not sure if that failure is related, I do not think so. Can you check ?

**Comment by geoand** [comment]
I don't think they are, but best restart the tests to be sure

**Comment by phillip-kruger** [comment]
Is it possible to only restart for `JVM Tests - JDK 11 Windows` ?

**Comment by geoand** [comment]
Unfortunately that's not possible

**Comment by phillip-kruger** [comment]
@geoand - any advice ?

**Comment by geoand** [comment]
What is failing?

**Comment by phillip-kruger** [comment]
Not sure, seems likes it is timing out.

**Comment by geoand** [comment]
If it's not in a RESTEasy Reactive or OpenAPI related module, I wouldn't worry about it... The Windows build is pretty flaky...

**Comment by phillip-kruger** [comment]
Should we just merge then ?

**Comment by geoand** [comment]
Yup, go ahead

**Comment by phillip-kruger** [comment]
Thanks :)
