### PR TITLE
QuarkusComponentTest: class loading refactoring

### LINKED ISSUE #43339: QuarkusComponentTest: support simplified constructor injection
### Description

`QuarkusComponentTest` does not support bytecode transformations yet and thus [simplified constructor injection](https://quarkus.io/guides/cdi-reference#simplified-constructor-injection) does not work.

### Implementation ideas

We'll need something like https://github.com/quarkusio/quarkus/pull/35473 first to be able to implement this feature.

### PR DESCRIPTION
**Pull request by mkouba**
- resolves #43339

The goal of this pull request is to refactor the class loading used for `QuarkusComponentTest`, i .e. use a **transformation-aware class loader** to load a test class annotated with `@QuarkusComponentTest`. This way we can support things like simplified constructor injection.

Implementation-wise - we hook into the `FacaClassLoader` logic (if present) and similarly to how `@QuarkusTest` is handled, we build the container (ArC in case of `QuarkusComponentTest`) when the test classes are loaded (note that there must be a special handling for continuous testing where `io.quarkus.deployment.dev.testing.JunitTestRunner` is used to load the test classes).

When I discussed this PR with Ladislav and Matej, we had an idea that `quarkus-junit5` and `quarkus-junit5-component` could be merged in one artifact. However, it turns out we would have to add a bunch of dependencies to `quarkus-junit5` (including ArC, but what's worse also Mockito + bytebuddy - this combo has ~ 4MB of jars). So I decided to introduce the `io.quarkus.test.common.FacadeClassLoaders` SPI instead. It lives in the `quarkus-test-common` and the name is terrible, but it works soo :shrug:.

There's one use case where the new approach fails. It's a `QuarkusDevModeTest` iff quarkus-junit5 is not present, something along the lines of https://github.com/quarkusio/quarkus/blob/main/integration-tests/devmode/src/test/java/io/quarkus/test/component/ComponentContinuousTestingTest.java. I found that `quarkus-junit5` provides `QuarkusTestConfigProviderResolver` that somehow overrides `io.quarkus.test.config.TestConfigProviderResolver` to avoid Context ClassLoader mismatch. But I have no idea why/how and why `TestConfigProviderResolver` exists for the first place.

This change should not break any existing apps but the test coverage is limited..

### CODE REVIEW

File: test-framework/junit5-component/src/main/java/io/quarkus/test/component/QuarkusComponentTestClassLoader.java [hunk 1]
```diff
@@ -2,38 +2,142 @@
...
-    private final File resourceReferenceProviderFile;
+    private static final Logger LOG = Logger.getLogger(QuarkusComponentTestClassLoader.class);
 
-    public QuarkusComponentTestClassLoader(ClassLoader parent, File componentsProviderFile,
-            File resourceReferenceProviderFile) {
+    static {
+        ClassLoader.registerAsParallelCapable();
+    }
+
+    static final ConcurrentMap<String, Bytecode> BYTECODE_CACHE = new ConcurrentHashMap<>();
```
Comment (Ladicek) [inline test-framework/junit5-component/src/main/java/io/quarkus/test/component/QuarkusComponentTestClassLoader.java:30]: `byte[]` is a reference type, so it can be the value type of the map directly.

Comment (Ladicek) [reply test-framework/junit5-component/src/main/java/io/quarkus/test/component/QuarkusComponentTestClassLoader.java:30]: Hmm, but I see this field is not `private`, so it's probably used elsewhere too. Take my comment with a grain of salt :-)

**Comment by Ladicek** [comment]
> When I discussed this PR with Ladislav and Matej, we had an idea that `quarkus-junit5` and `quarkus-junit5-component` could be merged in one artifact. However, it turns out we would have to add a bunch of dependencies to `quarkus-junit5` (including ArC, but what's worse also Mockito + bytebuddy - this combo has ~ 4MB of jars). So I decided to introduce the `io.quarkus.test.common.FacadeClassLoaders` SPI instead. It lives in the `quarkus-test-common` and the name is terrible, but it works soo 🤷.

Not an expert, but could we maybe move the whole infrastructure to `quarkus-test-common`? (By infrastructure, I mean `CustomLauncherInterceptor`, `FacadeClassLoader`, the SPI you added here and maybe a few other classes.) This would require `quarkus-test-common` to actually depend on `junit-jupiter`, which doesn't necessarily have to be a problem, and it would let us ditch `ComponentLauncherSessionListener`. We would always have the same one present. The SPI you added here (`FacadeClassLoaders`) should be renamed (:laughing:) and provide at least some notion of lifecycle (to allow cleaning up at the end). Again, not an expert, perhaps that doesn't make much sense.

Also, I'm not sure I'm able to do a proper review here, certainly not without playing with this locally for a while :-)

File: test-framework/junit5-component/src/main/java/io/quarkus/test/component/QuarkusComponentTestClassLoader.java (hunk 1 above)
Comment (mkouba) [reply test-framework/junit5-component/src/main/java/io/quarkus/test/component/QuarkusComponentTestClassLoader.java:30]: We want to cache unsuccessful lookups as well... and `ConcurrentMap` cannot contain `null` values.

Comment (Ladicek) [reply test-framework/junit5-component/src/main/java/io/quarkus/test/component/QuarkusComponentTestClassLoader.java:30]: Ah, gotcha. I think you could create a sentinel value and use that as a marker, but I'm not sure how equality/hash code works on arrays, so what you're doing here makes sense.

**Comment by mkouba** [comment]
> > When I discussed this PR with Ladislav and Matej, we had an idea that `quarkus-junit5` and `quarkus-junit5-component` could be merged in one artifact. However, it turns out we would have to add a bunch of dependencies to `quarkus-junit5` (including ArC, but what's worse also Mockito + bytebuddy - this combo has ~ 4MB of jars). So I decided to introduce the `io.quarkus.test.common.FacadeClassLoaders` SPI instead. It lives in the `quarkus-test-common` and the name is terrible, but it works soo 🤷.
> 
> Not an expert, but could we maybe move the whole infrastructure to `quarkus-test-common`? (By infrastructure, I mean `CustomLauncherInterceptor`, `FacadeClassLoader`, the SPI you added here and maybe a few other classes.) This would require `quarkus-test-common` to actually depend on `junit-jupiter`, which doesn't necessarily have to be a problem, and it would let us ditch `ComponentLauncherSessionListener`. We would always have the same one present.

I'm not an expert either but I don't feel confident enough to do such a bold move. Also `FaceClassLoader` depends on many other classes from the `quarkus-junit` such as `io.quarkus.test.junit.AppMakerHelper` and I'm not really sure it will be that easy to move them without breaking stuff.

> The SPI you added here (`FacadeClassLoaders`) should be renamed (:laughing:) and provide at least some notion of lifecycle (to allow cleaning up at the end). Again, not an expert, perhaps that doesn't make much sense.

Right now, I think that we don't need any cleanup... which doesn't mean we won't need it in the future but I'd like to keep the SPI minimal. If possible, it should be considered _internal_. But AFAIK the only thing we could do is to add a sentence  in the javadoc.

Speaking of the name - do you have a better idea? Because I'm out of ideas...

> Also, I'm not sure I'm able to do a proper review here, certainly not without playing with this locally for a while :-)

No problem. Your feeedback is really appreciated! :pray:

**Comment by Ladicek** [comment]
> I'm not an expert either but I don't feel confident enough to do such a bold move. Also `FaceClassLoader` depends on many other classes from the `quarkus-junit` such as `io.quarkus.test.junit.AppMakerHelper` and I'm not really sure it will be that easy to move them without breaking stuff.

Makes sense.

> > The SPI you added here (`FacadeClassLoaders`) should be renamed (:laughing:) and provide at least some notion of lifecycle (to allow cleaning up at the end). Again, not an expert, perhaps that doesn't make much sense.
> 
> Right now, I think that we don't need any cleanup... which doesn't mean we won't need it in the future but I'd like to keep the SPI minimal. If possible, it should be considered _internal_. But AFAIK the only thing we could do is to add a sentence in the javadoc.

:+1: 

> Speaking of the name - do you have a better idea? Because I'm out of ideas...

Nothing extraordinary. I'd just call it `FacadeClassLoaderProvider` or something.

**Comment by manovotn** [comment]
I am going through the code now but in the meantime - I was thinking whether it would be worth adding a note to the [documentation](https://quarkus.io/guides/testing-components) stating that component tests now support transformations?

**Comment by mkouba** [comment]
> I am going through the code now but in the meantime - I was thinking whether it would be worth adding a note to the [documentation](https://quarkus.io/guides/testing-components) stating that component tests now support transformations?

Once we merge this pull request I'd like to write a blog post that would mention all recent improvements (incl. `@InjectMock Event`). Basically a follow-up of https://quarkus.io/blog/quarkus-component-test/. Speaking of the docs - we didn't mention it does not work so I'm not really sure it's important :shrug:.

**Comment by manovotn** [comment]
> > I am going through the code now but in the meantime - I was thinking whether it would be worth adding a note to the [documentation](https://quarkus.io/guides/testing-components) stating that component tests now support transformations?
> 
> Once we merge this pull request I'd like to write a blog post that would mention all recent improvements (incl. `@InjectMock Event`). Basically a follow-up of https://quarkus.io/blog/quarkus-component-test/. 

That's great idea! :+1: 

> Speaking of the docs - we didn't mention it does not work so I'm not really sure it's important 🤷.

I know, but fair enough.
My thinking was that users might have encountered this shortcoming before and gave up on using the extension; I was just looking for a way to rise awareness. I suppose a blogpost would work just as well :)

**Comment by mkouba** [comment]
BTW I think that this would open the door to other possibilities. For example, we could try to add support [Panache mocking for the active record pattern](https://quarkus.io/guides/hibernate-orm-panache#using-the-active-record-pattern).

File: test-framework/junit5/src/main/java/io/quarkus/test/junit/classloading/FacadeClassLoader.java [hunk 2]
```diff
@@ -253,6 +258,11 @@ public FacadeClassLoader(ClassLoader parent, boolean isAuxiliaryApplication, Cur
                 throw new RuntimeException(e);
             }
         }
+
+        facadeClassLoaderProviders = new ArrayList<>();
+        ServiceLoader<FacadeClassLoaderProvider> loader = ServiceLoader.load(FacadeClassLoaderProvider.class,
+                FacadeClassLoader.class.getClassLoader());
+        loader.forEach(facadeClassLoaderProviders::add);
```
Comment (manovotn) [inline test-framework/junit5/src/main/java/io/quarkus/test/junit/classloading/FacadeClassLoader.java:265]: I'd probably add a check (and a comment) for at most one such provider?
Just so that any future change is aware of how it works and that having multiple possibly means attempting to load a class with all of them?

File: test-framework/common/src/main/java/io/quarkus/test/common/FacadeClassLoaderProvider.java [hunk 3]
```diff
@@ -0,0 +1,16 @@
+package io.quarkus.test.common;
+
+/**
+ * This internal SPI is used by {@code io.quarkus.test.junit.classloading.FacadeClassLoader} from quarkus-junit5 to extend its
+ * functionality.
+ */
+public interface FacadeClassLoaderProvider {
```
Comment (manovotn) [inline test-framework/common/src/main/java/io/quarkus/test/common/FacadeClassLoaderProvider.java:7]: I was thinking about the name and I'd suggest something along the lines of "alternative CL", so perhaps `AlternativeQuarkusTestClassLoader`? It is not much better than the current one though :sweat_smile:

File: test-framework/common/src/main/java/io/quarkus/test/common/FacadeClassLoaderProvider.java [hunk 4]
```diff
@@ -0,0 +1,16 @@
...
+
+    /**
+     * @param name The binary name of a class
+     * @param parent
+     * @return the class loader or null if no dedicated CL exists for the given class
+     */
+    ClassLoader getClassLoader(String name, ClassLoader parent);
```
Comment (manovotn) [inline test-framework/common/src/main/java/io/quarkus/test/common/FacadeClassLoaderProvider.java:14]: You could probably change this to return the `Class` object or `null` instead as all usages are doing just that anyway.

File: test-framework/junit5-component/src/main/java/io/quarkus/test/component/ComponentContainer.java [hunk 5]
```diff
@@ -0,0 +1,888 @@
...
+
+        @Override
+        public MethodVisitor visitMethod(int access, String name, String descriptor,
+                String signature, String[] exceptions) {
+            MethodVisitor mv = super.visitMethod(access, name, descriptor, signature, exceptions);
+            if (name.equals("<init>") || name.equals("<clinit>")) {
+                return mv;
+            }
+            LOG.debugf("Trace method %s#%s:%s", className, name, descriptor);
+            return new MethodVisitor(Gizmo.ASM_API_VERSION, mv) {
```
Comment (manovotn) [inline test-framework/junit5-component/src/main/java/io/quarkus/test/component/ComponentContainer.java:876]: I am not sure I am reading this correctly - shouldn't the tracing trigger only for methods with `@Test` on them? If so, you should be able to override `visitAnnotation` method in the `MethodVisitor` to achieve that.

File: test-framework/junit5-component/src/main/java/io/quarkus/test/component/ComponentLauncherSessionListener.java [hunk 6]
```diff
@@ -0,0 +1,43 @@
...
+    @Override
+    public void launcherSessionOpened(LauncherSession session) {
+        if (Conditions.isFacadeLoaderUsed()) {
+            // Set the TCCL only if FacadeClassLoader is not used and outside continuous testing discovery
+            return;
+        }
+        LOG.debugf("Set the ComponentFacadeLoader as TCCL");
+        ClassLoader currentCl = Thread.currentThread().getContextClassLoader();
+        if (currentCl == null
+                || (currentCl != facadeLoader
```
Comment (manovotn) [inline test-framework/junit5-component/src/main/java/io/quarkus/test/component/ComponentLauncherSessionListener.java:24]: It this really needed? It seems to me that the follow up condition would be sufficient?
Unless, of course, you can repeatedly set different instances of `ComponentClassLoader` but that doesn't seem to be the case?

**Review by manovotn — COMMENTED** [review]
Added a few comments and questions.
Take them with a pinch of salt as while I understand what the PR does, I certainly do have hard time understanding *how exactly* with all the class loader juggling :)

File: test-framework/junit5/src/main/java/io/quarkus/test/junit/classloading/FacadeClassLoader.java (hunk 2 above)
Comment (mkouba) [reply test-framework/junit5/src/main/java/io/quarkus/test/junit/classloading/FacadeClassLoader.java:265]: But it's not meant to be "at most one provider". The first non-null value is taken.

File: test-framework/common/src/main/java/io/quarkus/test/common/FacadeClassLoaderProvider.java (hunk 3 above)
Comment (mkouba) [reply test-framework/common/src/main/java/io/quarkus/test/common/FacadeClassLoaderProvider.java:7]: I'd like to keep the `FacadeClassLoader` in the name. I used the `Exta` prefix in early versions of the POC but then I realized that the prefix does not help much. So we could use something like `AlternativeFacadeClassLoaderProvider` but given that it's considered an internal SPI I don't think it matters much.

File: test-framework/common/src/main/java/io/quarkus/test/common/FacadeClassLoaderProvider.java (hunk 4 above)
Comment (mkouba) [reply test-framework/common/src/main/java/io/quarkus/test/common/FacadeClassLoaderProvider.java:14]: I'd like to keep the `ClassLoader` as the return type for future development (e.g. if methods like `ClassLoader#getResource(String)` will also need to be delegated).

File: test-framework/junit5-component/src/main/java/io/quarkus/test/component/ComponentContainer.java (hunk 5 above)
Comment (mkouba) [reply test-framework/junit5-component/src/main/java/io/quarkus/test/component/ComponentContainer.java:876]: Nope, we need to add the tracing logic into all reloadable classes in the app so that a change in the class triggers a test re-launch.

File: test-framework/junit5-component/src/main/java/io/quarkus/test/component/ComponentLauncherSessionListener.java (hunk 6 above)
Comment (mkouba) [reply test-framework/junit5-component/src/main/java/io/quarkus/test/component/ComponentLauncherSessionListener.java:24]: I'm not sure TBH but `LauncherSessionListener#launcherSessionOpened()` is called differently in different environments (IDE, continuous testing, surefire, gradle, etc.). When I say "differently" I mean multiple times with some weird ordering...

File: test-framework/junit5-component/src/main/java/io/quarkus/test/component/ComponentLauncherSessionListener.java [hunk 7]
```diff
@@ -0,0 +1,43 @@
...
+    private static final Logger LOG = Logger.getLogger(ComponentLauncherSessionListener.class);
+
+    private static ComponentClassLoader facadeLoader;
+
+    private static ClassLoader oldCl = null;
+
+    @Override
+    public void launcherSessionOpened(LauncherSession session) {
+        if (Conditions.isFacadeLoaderUsed()) {
+            // Set the TCCL only if FacadeClassLoader is not used and outside continuous testing discovery
```
Comment (mkouba) [inline test-framework/junit5-component/src/main/java/io/quarkus/test/component/ComponentLauncherSessionListener.java]: This comment is outdated, we don't care about continuous testing here...

File: test-framework/junit5-component/src/main/java/io/quarkus/test/component/ComponentContainer.java (hunk 5 above)
Comment (manovotn) [reply test-framework/junit5-component/src/main/java/io/quarkus/test/component/ComponentContainer.java:876]: Ah, right, that makes sense. Thanks for explanation :)

**Comment by mkouba** [comment]
> Added a few comments and questions. Take them with a pinch of salt as while I understand what the PR does, I certainly do have hard time understanding _how exactly_ with all the class loader juggling :)

Totally understand, it took me a few days to understand at least part of the class loading code...

File: test-framework/common/src/main/java/io/quarkus/test/common/FacadeClassLoaderProvider.java (hunk 3 above)
Comment (manovotn) [reply test-framework/common/src/main/java/io/quarkus/test/common/FacadeClassLoaderProvider.java:7]: > but given that it's considered an internal SPI I don't think it matters much.

True, I just found it a bit out of place as is isn't really *the* facade class loader; that one is still in place and actually uses this API.
I can certainly live with the current name

File: test-framework/common/src/main/java/io/quarkus/test/common/FacadeClassLoaderProvider.java (hunk 4 above)
Comment (manovotn) [reply test-framework/common/src/main/java/io/quarkus/test/common/FacadeClassLoaderProvider.java:14]: Fair enough :+1:

File: test-framework/common/src/main/java/io/quarkus/test/common/FacadeClassLoaderProvider.java (hunk 3 above)
Comment (mkouba) [reply test-framework/common/src/main/java/io/quarkus/test/common/FacadeClassLoaderProvider.java:7]: It's an extension of the `FacadeClassLoader`... but _"extension"_ is a bit overloaded in this area ;-)

File: test-framework/junit5/src/main/java/io/quarkus/test/junit/classloading/FacadeClassLoader.java (hunk 2 above)
Comment (manovotn) [reply test-framework/junit5/src/main/java/io/quarkus/test/junit/classloading/FacadeClassLoader.java:265]: I get how it operates, it's just that at this point I'd consider it unexpected if more providers were found.

Comment (mkouba) [reply test-framework/junit5/src/main/java/io/quarkus/test/junit/classloading/FacadeClassLoader.java:265]: I wouldn't say it's unexpected. In theory, there could be another type of Quarkus test and it could contribute this SPI as well :shrug:. It works like this: first we try to load the class with the `FacadeClassLoader` and if it's not possible then try all the "extensions". I admit that it's not very well defined though...

**Comment by mkouba** [comment]
@Ladicek @manovotn @holly-cummins I'd like to merge this pull request today. It's not perfect but we could address potential issues in the follow ups. I already have a POC for extension points called `QuarkusComponentTestCallbacks` and integration with `quarkus-panache-mock` that makes it possible to mock Panache entitites in a QuarkusComponentTest.

**Review by manovotn — APPROVED** [review]

File: core/deployment/src/main/java/io/quarkus/deployment/dev/testing/JunitTestRunner.java [hunk 8]
```diff
@@ -613,6 +621,22 @@ private DiscoveryResult discoverTestClasses() {
...
+            for (ClassInfo subclass : index.getAllKnownSubclasses(name)) {
+                quarkusComponentTestClasses.add(subclass.name().toString());
+            }
+        }
+        for (ClassInfo clazz : index.getKnownUsers(QUARKUS_COMPONENT_TEST_EXTENSION)) {
+            DotName name = clazz.name();
+            quarkusComponentTestClasses.add(name.toString());
+            for (ClassInfo subclass : index.getAllKnownSubclasses(name)) {
+                quarkusComponentTestClasses.add(subclass.name().toString());
+            }
```
Comment (holly-cummins) [inline core/deployment/src/main/java/io/quarkus/deployment/dev/testing/JunitTestRunner.java:637]: This pattern is repeated several times. We may be able to extract common code by passing in the thing we're iterating over and the array to add it to.

File: test-framework/junit5-component/src/main/java/io/quarkus/test/component/QuarkusComponentTestClassLoader.java [hunk 9]
```diff
@@ -2,38 +2,142 @@
...
+                || name.startsWith("jdk.")
+                || name.startsWith("javax.")
+                || name.startsWith("jakarta.")
+                || name.startsWith("sun.")
+                || name.startsWith("com.sun.")
+                || name.startsWith("org.w3c.")
+                || name.startsWith("org.xml.")
+                || name.startsWith("org.junit.")
+                || name.startsWith("org.mockito.")
+                || PARENT_CL_CLASSES.contains(name);
```
Comment (holly-cummins) [inline test-framework/junit5-component/src/main/java/io/quarkus/test/component/QuarkusComponentTestClassLoader.java:117]: Is there any way to get this code more common with the QuarkusClassLoader? I seem to recall doing a few [hacky overrides](https://github.com/quarkusio/quarkus/blob/f16dd61a3ab3bcc6c54ccc75ef74792f0b800cad/independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/classloading/QuarkusClassLoader.java#L225) to what gets loaded parent-first over there to support dev services work. It might be (a) less code and (b) fewer confusing bugs if we had a common service.

File: core/deployment/src/main/java/io/quarkus/deployment/dev/testing/JunitTestRunner.java (hunk 8 above)
Comment (mkouba) [reply core/deployment/src/main/java/io/quarkus/deployment/dev/testing/JunitTestRunner.java:637]: Yep, we could try. However, it's out of the scope of this pull request. Added a new entry to my TODO list ;-).

File: test-framework/junit5-component/src/main/java/io/quarkus/test/component/QuarkusComponentTestClassLoader.java (hunk 9 above)
Comment (mkouba) [reply test-framework/junit5-component/src/main/java/io/quarkus/test/component/QuarkusComponentTestClassLoader.java:117]: I'm not sure TBH. But I admit that this does not look very smart (it's more or less a result of experimentation) and we should get back to that sometime.

Comment (Ladicek) [reply test-framework/junit5-component/src/main/java/io/quarkus/test/component/QuarkusComponentTestClassLoader.java:117]: The list here looks quite close to what I had in #35473 and that wasn't a result of experimentation -- that was a list of packages provided by the JDK. There's a few packages added here (`jakarta.*`, `org.junit.*`, `org.mockito.*`) which make perfect sense, but still -- it's a list of packages we know are never provided by the application and make no sense to be loaded by the application class loader.

Comment (mkouba) [reply test-framework/junit5-component/src/main/java/io/quarkus/test/component/QuarkusComponentTestClassLoader.java:117]: > it's a list of packages we know are never provided by the application and make no sense to be loaded by the application class loader.

On the other hand, I observed weird errors while adding other packages which are also never provided by the app :shrug:.

Comment (Ladicek) [reply test-framework/junit5-component/src/main/java/io/quarkus/test/component/QuarkusComponentTestClassLoader.java:117]: Well, that sounds strange then.
