### PR TITLE
Ensure that `quarkus.uuid` is not determined at native image build time

### LINKED ISSUE #45863: 3.18 regression: quarkus.uuid is the same for every run in native images
### Describe the bug

In 3.18.0.CR1, the `quarkus.uuid` has the same value for all application runs when compiled to a **native image**

### Expected behavior

It was working fine, and returned a unique value in 3.17 in native images

### Actual behavior

It is always the same, causing crashes in distributed systems applications that rely on a unique id.

Possible causes?
#45434 
#45610

### How to Reproduce?

 compile a simple app to native:

```
package org.acme;

import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;
import org.eclipse.microprofile.config.inject.ConfigProperty;

@Path("/hello")
public class GreetingResource {

    @ConfigProperty(name = "quarkus.uuid")
    String uuid;

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        return "Hello from Quarkus REST "+uuid;
    }
}
```

Start, call /hello, take note of uuid, shutdown
Repeat, will yield same uuid

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

21

### Mandrel or GraalVM version (if different from Java)

mandrel 21

### Quarkus version or git rev

3.18.0.CR1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
- Fixes: #45863

### CODE REVIEW

File: core/deployment/src/main/java/io/quarkus/deployment/steps/ConfigGenerationBuildStep.java [hunk 1]
```diff
@@ -114,6 +115,12 @@ public class ConfigGenerationBuildStep {
             SmallRyeConfigBuilder.class, "withSources",
             SmallRyeConfigBuilder.class, ConfigSource[].class);
 
+    @BuildStep
+    void nativeSupport(BuildProducer<RuntimeInitializedClassBuildItem> runtimeInitializedClassProducer) {
+        runtimeInitializedClassProducer.produce(new RuntimeInitializedClassBuildItem(
+                "io.quarkus.runtime.configuration.RuntimeConfigBuilder$UuidConfigSource$Holder"));
+    }
```
Comment (geoand) [inline core/deployment/src/main/java/io/quarkus/deployment/steps/ConfigGenerationBuildStep.java:122]: I'm not really satisfied with the class I put this in, so if you have any better suggestions @radcortez I'm all ears

**Comment by geoand** [comment]
If we want a test for this, I can probably add some kind of native test for a CLI

File: core/deployment/src/main/java/io/quarkus/deployment/steps/ConfigGenerationBuildStep.java (hunk 1 above)
Comment (radcortez) [reply core/deployment/src/main/java/io/quarkus/deployment/steps/ConfigGenerationBuildStep.java:122]: I think it is fine.

**Review by radcortez — APPROVED** [review]

**Comment by geoand** [comment]
Thanks a lot!
