### PR TITLE
Arc - log a WARN if we encounter unproxyable JDK class since we cannot transform it either

### LINKED ISSUE #33417: Custom cdi context not applied for certain bean types
### Describe the bug

When using a custom `InjectableContext` the context implementation is not beeing used for all bean types.

### Expected behavior

Either all beans that are annotated with my scope annotation should be handled over my context implementation or if not a clear feedback (visible log or exception) should be given from Quarkus.

### Actual behavior

When having certain beantype e.g. `AtomicBoolean `, the context implementation is ignored
```
@MyCustomScoped
@Produces
AtomicBoolean atomicBoolean(){
    return new AtomicBoolean();
```

It is still scoped as `@MyCustomScoped` when checking with `Arc.container().instance(AtomicBoolean.class).getBean().getScope();` but the bean is not beeing handled over my context implementation.

### How to Reproduce?

https://github.com/HerrDerb/extension-issues/tree/custom-context-issue

### Quarkus version or git rev

3.0.3Final

### PR DESCRIPTION
**Pull request by manovotn**
Fixes #33417 

An example of when this happens is creating an `@ApplicationScoped` bean for `AtomicBoolean` which has many methods `final`. For each such method, there will be a log looking something like this:

> 2023-05-17 13:31:33,401 WARN  [io.qua.arc.pro.Methods] (build-17) JDK class java.util.concurrent.atomic.AtomicBoolean with final method weakCompareAndSetVolatile() cannot be proxied and is not transformable. This method will be ignored during proxy generation and should never be invoked upon the proxy instance!

### CODE REVIEW

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Methods.java [hunk 1]
```diff
@@ -123,10 +123,16 @@ private static boolean skipForClientProxy(MethodInfo method, boolean transformUn
...
                 }
-
+                // in case we want to transform classes but are unable to, we log a WARN
                 LOGGER.warn(String.format(
                         "Final method %s.%s() is ignored during proxy generation and should never be invoked upon the proxy instance!",
                         className, method.name()));
+            } else {
+                // JDK classes with final method are not proxyable and not transformable, we skip those methods and log a WARN
+                LOGGER.warn(String.format(
+                        "JDK class %s with final method %s() cannot be proxied and is not transformable." +
```
Comment (Ladicek) [inline independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Methods.java:133]:
```suggestion
                        "JDK class %s with final method %s() cannot be proxied and is not transformable. " +
```

**Comment by Ladicek** [comment]
LGTM otherwise :-)

**Review by mkouba — APPROVED** [review]

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Methods.java (hunk 1 above)
Comment (manovotn) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Methods.java]: Good point, done :)

**Review by Ladicek — APPROVED** [review]

**Comment by manovotn** [comment]
The failures are unrelated.
