### PR TITLE
Properly initialize Maven profile options during bootstrap

### LINKED ISSUE #6383: Using mvn package -Pnative instead of -Dnative, leads to CCE
**Describe the bug**
When executing `./mvnw package -Pnative` against a newly generated project, instead of a getting a native image built, we get the following error:

```
org.junit.jupiter.api.extension.TestInstantiationException: TestInstanceFactory [io.quarkus.test.junit.QuarkusTestExtension] failed to instantiate test class [org.acme.GreetingResourceTest]: java.lang.String cannot be cast to [Ljava.lang.String;
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to [Ljava.lang.String;
```

This only happens with `master`, Quarkus `1.1.0.Final` works fine.

The issue was originally found by @aureamunoz when she was working on some Quarkus material.

There is a workaround which is to use `-Dnative`, but we should fix this nonetheless since using profiles is currently broken.

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #6383

### CODE REVIEW

File: independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/resolver/maven/options/BootstrapMavenOptions.java [hunk 1]
```diff
@@ -90,7 +90,14 @@ public String getOptionValue(String name) {
 
     public String[] getOptionValues(String name) {
         final Object o = options.get(name);
-        return o == null ? null : (String[]) o;
+        if (o == null) {
+            return null;
+        } else if (o instanceof String[]) {
+            return (String[]) o;
+        } else if (o instanceof String) {
+            return new String[]{(String)o};
```
Comment (geoand) [inline independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/resolver/maven/options/BootstrapMavenOptions.java]: I didn't perform a `((String) o).split(",");` here because the code that uses the returned array does that already, but I am wondering if it should be done here in addition...

**Comment by aloubyansky** [comment]
Would you mind changing it a bit? See my comment here https://github.com/quarkusio/quarkus/pull/6299#issuecomment-568099166

**Comment by geoand** [comment]
Sure thing, I'll fix it ASAP

**Comment by geoand** [comment]
@aloubyansky actually it is `getOptionValues` that is being called, however the call site is not the one you indicated, but this one: https://github.com/quarkusio/quarkus/blob/master/independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/resolver/maven/MavenRepoInitializer.java#L270

So I assume the fix is valid?

**Comment by aloubyansky** [comment]
Yes, but it's not properly initialized. It's initialized with `cmdLine.getOptionValue(name)` instead of `getOptionValues`.

**Comment by geoand** [comment]
Gotcha, I pushed the change

**Comment by aloubyansky** [comment]
That's actually not what I meant. I meant this only for the active profiles. On which option did it fail in your case?

**Comment by geoand** [comment]
It failed for me when using `-Pnative`.

With the initial fix the problem went away

**Comment by aloubyansky** [comment]
Right, so that's profiles. They should always be initialized as String[]. Instead of creating an array on every get.

**Comment by geoand** [comment]
Aha, I see what you mean

**Comment by aloubyansky** [comment]
map.put(String.valueOf(CLIManager.ACTIVE_PROFILES), cmdLine.getOptionValues(CLIManager.ACTIVE_PROFILES))

**Comment by geoand** [comment]
:+1:

**Comment by geoand** [comment]
@aloubyansky PR updated.

Thanks for your patience :)

**Review by aloubyansky — APPROVED** [review]
Thanks a lot @geoand!

**Comment by geoand** [comment]
You are welcome!
