### PR TITLE
Make it easy to access Neo4j browser

### LINKED ISSUE #20624: Need to publish Neo4J console for Dev Service
### Describe the bug

When a Neo4J database stands up by Quarkus dev service, the Neo4J console(http://localhost:7474/browser) can't be accessible since the 7474 port wasn't published. If I run the Noe4J container manually with "--publish=7474:7474", I can access the console.

### Expected behavior

The web console can be accessible via http://localhost:7474/browser/

### Actual behavior

The web console can't be accessible via http://localhost:7474/browser/

### How to Reproduce?

1. Clone https://github.com/quarkusio/quarkus-quickstarts/tree/main/neo4j-quickstart
2. Comment or remove all keys and values in the application.properties
3. Run Quarku Dev Mode
4. Access the Noe4J console via http://localhost:7474/browser/

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.3.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by michael-simons**
This changes the dev services for Neo4j in the following way:

- It adds an extension script to the Neo4j container (which is supported on all official images since 3.5) that waits until dev services adds a set of environment variables to the already running container
- At that moment, Neo4j has not yet been started and it's static configuration can be influenced. This is used to correctly configure the advertised bolt address needed by the Neo4j browser
- Several new log statements have been added: An explicit URL for the Neo4j browser to open and a copyable snippet to use the cypher-shell to connect to the container
- Last but not least the change adds two new config options to specify custom, fixed ports for both http and bolt

Logging will look like this:

```
INFO  [io.qua.neo.deployment] (build-30) Dev Services started a Neo4j container reachable at bolt://127.0.0.1:61766.
INFO  [io.qua.neo.deployment] (build-30) Neo4j Browser is reachable at http://127.0.0.1:61765/browser?dbms=bolt://neo4j@127.0.0.1:61766.
INFO  [io.qua.neo.deployment] (build-30) The username for both endpoints is `neo4j`, authenticated by `password`
INFO  [io.qua.neo.deployment] (build-30) Connect via Cypher-Shell: cypher-shell -u neo4j -p password -a bolt://127.0.0.1:61766
```

So that a user can click the browser URL in most IDEs.

This closes #20624

### CODE REVIEW

**Comment by michael-simons** [comment]
I think I take another iteration whether it is necessary to have the `bolt` port chosen by us from the outside to make this setup work… I would rather prefer not todo it. One more commit incoming.

File: extensions/neo4j/deployment/src/main/java/io/quarkus/neo4j/deployment/DevServicesBuildTimeConfig.java [hunk 1]
```diff
@@ -29,4 +29,18 @@
      */
     @ConfigItem
     public Map<String, String> additionalEnv;
+
+    /**
+     * This value will be used to expose the bolt-port of the container to the outside. It must be a free port,
+     * otherwise startup will fail. The dev services will try to allocate a free port by default.
+     */
+    @ConfigItem
+    public Optional<Integer> fixedBoltPort = Optional.empty();
```
Comment (gastaldi) [inline extensions/neo4j/deployment/src/main/java/io/quarkus/neo4j/deployment/DevServicesBuildTimeConfig.java:38]: You can use `OptionalInt` instead

Comment (michael-simons) [reply extensions/neo4j/deployment/src/main/java/io/quarkus/neo4j/deployment/DevServicesBuildTimeConfig.java]: Good point, I didn't know that it was supported in the config. Changed it.

File: extensions/neo4j/deployment/src/main/java/io/quarkus/neo4j/deployment/DevServicesBuildTimeConfig.java [hunk 2]
```diff
@@ -29,4 +30,18 @@
      */
     @ConfigItem
     public Map<String, String> additionalEnv;
+
+    /**
+     * This value will be used to expose the bolt-port of the container to the outside. It must be a free port,
+     * otherwise startup will fail. The dev services will try to allocate a free port by default.
+     */
+    @ConfigItem
+    public OptionalInt fixedBoltPort = OptionalInt.empty();
```
Comment (gastaldi) [inline extensions/neo4j/deployment/src/main/java/io/quarkus/neo4j/deployment/DevServicesBuildTimeConfig.java:39]: I think the `fixed` is implicit in the config? How about simply `boltPort` and `httpPort`?

Comment (michael-simons) [reply extensions/neo4j/deployment/src/main/java/io/quarkus/neo4j/deployment/DevServicesBuildTimeConfig.java:39]: Aaa yes, why not? I just followed this https://github.com/quarkusio/quarkus/blob/main/extensions/devservices/postgresql/src/main/java/io/quarkus/devservices/postgresql/deployment/PostgresqlDevServicesProcessor.java#L84 but didn't notice the config actually don't use the notion of "fixed"

Comment (michael-simons) [reply extensions/neo4j/deployment/src/main/java/io/quarkus/neo4j/deployment/DevServicesBuildTimeConfig.java]: Done.

**Comment by michael-simons** [comment]
Should I squash my commits for a merge, if you're done with the review @gastaldi ?

**Comment by gastaldi** [comment]
@michael-simons sure, that sounds good

**Comment by michael-simons** [comment]
Done :)

**Review by gastaldi — APPROVED** [review]

**Comment by gastaldi** [comment]
Good job!
