### PR TITLE
Load main sourceSet only if present for project dependencies

### LINKED ISSUE #27950: Generate Code fails if project dependencies do not include a main SourceSet
### Describe the bug

For Gradle, the task `quarkusGenerateCode` fails if a project dependency does not have a `sourceSet` called exactly `main`. 

### Expected behavior

Building a project should work even if a project dependency does not have a `sourceSet` called `main`.

### Actual behavior

Gradle fails with the following error:

```
Execution failed for task ':quarkus:quarkusGenerateCode'.
> Could not resolve all dependencies for configuration ':quarkus:quarkusProdRuntimeClasspathConfigurationDeployment'.
   > SourceSet with name 'main' not found
```

### How to Reproduce?

Reproducer: https://github.com/AdlerFleurant/quarkus-mpp-sample

1. Run `./gradlew quarkusGenerateCode` on the reproducer project.

### Output of `uname -a` or `ver`

Darwin xxxxxxxxxxxxx 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "17.0.2" 2022-01-18

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.12.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

7.5.1

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by AdlerFleurant**
Treating Extension Dependencies as optional

Fixes #27950

### CODE REVIEW

**Comment by aloubyansky** [comment]
@AdlerFleurant could you please run `mvn -Dquickly` on your repo and include the changes into your commit? Thanks.

File: devtools/gradle/gradle-application-plugin/src/test/java/io/quarkus/gradle/QuarkusPluginTest.java [hunk 1]
```diff
@@ -1,10 +1,13 @@
 package io.quarkus.gradle;
 
 import static org.assertj.core.api.Assertions.assertThat;
-import static org.junit.jupiter.api.Assertions.assertNotNull;
-import static org.junit.jupiter.api.Assertions.assertTrue;
+import static org.gradle.testkit.runner.TaskOutcome.SUCCESS;
+import static org.junit.jupiter.api.Assertions.*;
```
Comment (gsmet) [inline devtools/gradle/gradle-application-plugin/src/test/java/io/quarkus/gradle/QuarkusPluginTest.java:5]: We don't use star imports in Quarkus, please disable them.

And given a few other things I see in the PR, I wanted to point you to https://github.com/quarkusio/quarkus/blob/main/CONTRIBUTING.md#ide-config-and-code-style which might be useful if you plan to contribute regularly :).

Comment (AdlerFleurant) [reply devtools/gradle/gradle-application-plugin/src/test/java/io/quarkus/gradle/QuarkusPluginTest.java]: For some reason, the plugin does not pick up star static import. I updated the file.

**Comment by AdlerFleurant** [comment]
@aloubyansky star static imports seems to be ignored so I have changed it manually.

**Comment by aloubyansky** [comment]
@AdlerFleurant looks like the tests are failing in the CI. Could you please make sure they pass for you locally before push a new commit? [Running tests paragraph](https://github.com/quarkusio/quarkus/tree/main/devtools/gradle#running-tests) may help locating the relevant tests to run. Thanks!

**Comment by AdlerFleurant** [comment]
> @AdlerFleurant looks like the tests are failing in the CI. Could you please make sure they pass for you locally before push a new commit? [Running tests paragraph](https://github.com/quarkusio/quarkus/tree/main/devtools/gradle#running-tests) may help locating the relevant tests to run. Thanks!

Missed this. I will make sure to run the test successfully before my next push. However, part of this seems to be the CI. As it's trying to load some artifacts from the temporary test folder.

**Comment by AdlerFleurant** [comment]
@aloubyansky , fixed except optaplanner quickstart. We can temporarily exclude org.jboss:jandex  from optaplannerquickstart or wait for version 8.28.0 as it does remove the dependency on org.jboss:jandex at runtime: https://github.com/kiegroup/optaplanner/pull/2193

**Comment by AdlerFleurant** [comment]
I have also created https://github.com/quarkusio/quarkus-quickstarts/pull/1180 fixing the issue with optaplanner quickstart.

**Comment by Ladicek** [comment]
Thanks for submitting that quickstart fix :heart: I wanted to do it, but totally forgot.

**Comment by AdlerFleurant** [comment]
Do I need to rebase the branch before the merge?

**Comment by AdlerFleurant** [comment]
@Ladicek , @aloubyansky , the branch is rebased and the pull request that fixes optaplanner-quickstart was merged. This should run smoothly now.

**Comment by AdlerFleurant** [comment]
Not sure why this build failed on Windows. It seemed to be just a jitter.

File: devtools/gradle/gradle-application-plugin/src/test/java/io/quarkus/gradle/QuarkusPluginTest.java [hunk 2]
```diff
@@ -84,7 +95,67 @@ public void shouldReturnMutlipleOutputSourceDirectories() {
...
+                        ")");
+
+        Files.writeString(mppBuild,
+                "buildscript {\n" +
+                        "    repositories {\n" +
+                        "        mavenLocal()\n" +
+                        "        mavenCentral()\n" +
+                        "    }\n" +
+                        "    dependencies {\n" +
+                        "        classpath(\"org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.10\")\n" +
```
Comment (aloubyansky) [inline devtools/gradle/gradle-application-plugin/src/test/java/io/quarkus/gradle/QuarkusPluginTest.java:122]: Could we pass `${kotlin.version}` to the test as a system property so that we don't have to change the source code when `kotlin.version` is updated in the project?

**Comment by AdlerFleurant** [comment]
@gsmet @aloubyansky @glefloch, this is ready for review.

**Review by aloubyansky — APPROVED** [review]

**Comment by aloubyansky** [comment]
@glefloch could you please review this one? Thanks!

**Comment by gsmet** [comment]
@AdlerFleurant could you rebase and force push? We don't want merge commits in PRs.

**Review by glefloch — APPROVED** [review]
This looks good to me, thanks @AdlerFleurant

**Comment by AdlerFleurant** [comment]
@gsmet I have updated into a single commit.

**Comment by AdlerFleurant** [comment]
Is there another action needed on my side to get this merged in @gsmet

**Comment by aloubyansky** [comment]
No, all good, thanks a lot @AdlerFleurant!
