### PR TITLE
Restore the ability to use a system property for remote-dev

### LINKED ISSUE #6550: :remote-dev mode stopped working with 1.1.0.Final
**Describe the bug**
Since 1.1.0.Final, :remote-dev seems to have stopped working (unless I'm missing some additional steps that have to be taken with 1.1.0.Final). Connection from the local to the remote side times out with: 
```
Exception in thread "Websocket ping timer" java.lang.NullPointerException
	at io.quarkus.remotedev.AgentRunner$2.run(AgentRunner.java:62)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
```
Command on the "local" side:
```
./mvnw  quarkus:remote-dev -Dquarkus.live-reload.url=http://127.0.0.1:8080 -Dquarkus.live-reload.password=somepassword
```
Command on the "remote" side:
```
./mvnw compile quarkus:dev -Dquarkus.live-reload.password=somepassword 
```
(I have some more -D options set, but I left those out for the sake of conciseness.)

When starting with 1.0.1.Final, the console shows the following when starting:
```
Listening for transport dt_socket at address: 5005
2020-01-14 14:47:01,493 INFO  [io.qua.und.web.dep.WebsocketHotReloadSetup] (main) Using websocket based hot deployment
2020-01-14 14:47:01,519 INFO  [io.und.web.jsr] (main) UT026003: Adding annotated server endpoint class io.quarkus.undertow.websockets.deployment.HotReplacementWebsocketEndpoint for path /quarkus/live-reload
2020-01-14 14:47:04,162 INFO  [io.quarkus] (main) Quarkus 1.0.1.Final started in 2.863s. Listening on: http://0.0.0.0:8080
2020-01-14 14:47:04,162 INFO  [io.quarkus] (main) Profile dev activated. Live Coding activated.
2020-01-14 14:47:04,162 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, hibernate-orm-panache, jdbc-postgresql, narayana-jta, resteasy, resteasy-jackson, servlet, undertow-websockets]
```

When starting with 1.1.0.Final, the console shows
```
Listening for transport dt_socket at address: 5005
2020-01-14 14:48:08,959 INFO  [io.quarkus] (main) Quarkus 1.1.0.Final started in 2.980s. Listening on: http://0.0.0.0:8080
2020-01-14 14:48:08,962 INFO  [io.quarkus] (main) Profile dev activated. Live Coding activated.
2020-01-14 14:48:08,962 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, hibernate-orm-panache, jdbc-postgresql, narayana-jta, resteasy, resteasy-jackson, servlet, undertow-websockets]

```

Outside of version numbers, poms are exactly the same. _Notice that the websockets message is missing for version 1.1.0.Final._

**Expected behavior**
"Local" side of development setup shows "Connected to remote server" after a few seconds.

**Actual behavior**
"Local" side of development setup shows 
```
Exception in thread "Websocket ping timer" java.lang.NullPointerException
	at io.quarkus.remotedev.AgentRunner$2.run(AgentRunner.java:62)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
```
Connection is never made

**To Reproduce**
1. create pom.xml with Quarkus 1.1.0.Final
2. add undertow-websockets
3. try and use remote-dev

**Configuration**
For completeness sake, but don't think this helps much?
```properties
# Add your application.properties here, if applicable.
# Configuration file

# configure your datasource
quarkus.datasource.url = jdbc:postgresql://localhost:5432/mydatabase
quarkus.datasource.driver = org.postgresql.Driver
quarkus.datasource.username = sarah
quarkus.datasource.password = connor
quarkus.hibernate-orm.database.generation=drop-and-create
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `Linux taishogun.lan 5.4.8-200.fc31.x86_64 #1 SMP Mon Jan 6 16:44:18 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
 - Output of `java -version`: 
```
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)
```
 - GraalVM version (if different from Java): n/a
 - Quarkus version or git rev: 1.1.0.Final

**Additional context**
Switching the pom.xml to 1.0.1.Final makes remote-dev work again.

Hope I provided enough info :)

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #6550

### CODE REVIEW

File: extensions/undertow-websockets/deployment/src/main/java/io/quarkus/undertow/websockets/deployment/WebsocketHotReloadSetup.java [hunk 1]
```diff
@@ -31,17 +31,27 @@
...
+
+        if (password != null && !password.isEmpty()) {
+            replacementPassword = password;
+        } else {
+            List<Path> resources = hotReplacementContext.getResourcesDir();
+            if (!resources.isEmpty()) {
+                //TODO: fix this
+                File appConfig = resources.get(0).resolve("application.properties").toFile();
+                if (appConfig.isFile()) {
+                    try (InputStream pw = new FileInputStream(appConfig)) {
```
Comment (dmlloyd) [inline extensions/undertow-websockets/deployment/src/main/java/io/quarkus/undertow/websockets/deployment/WebsocketHotReloadSetup.java]: You also need an `InputStreamReader` explicitly set up with `UTF-8` here, and load the properties from the reader, else there will be encoding problems.

Comment (geoand) [reply extensions/undertow-websockets/deployment/src/main/java/io/quarkus/undertow/websockets/deployment/WebsocketHotReloadSetup.java]: Well I just copied what was already in place, I didn't change anything there.
The UI probably shows a change because I moved it inside else.

Comment (geoand) [reply extensions/undertow-websockets/deployment/src/main/java/io/quarkus/undertow/websockets/deployment/WebsocketHotReloadSetup.java]: Would you like me to fix it anyway?

Comment (gsmet) [reply extensions/undertow-websockets/deployment/src/main/java/io/quarkus/undertow/websockets/deployment/WebsocketHotReloadSetup.java]: Yes, please let's do it.

File: extensions/undertow-websockets/deployment/src/main/java/io/quarkus/undertow/websockets/deployment/HotReplacementWebsocketEndpoint.java [hunk 2]
```diff
@@ -36,6 +36,7 @@
     static final String QUARKUS_HOT_RELOAD = "/quarkus/live-reload";
     static final String QUARKUS_SECURITY_KEY = "quarkus-security-key";
     static final String QUARKUS_HOT_RELOAD_PASSWORD = "quarkus.live-reload.password";
+    static final String QUARKUS_HOT_RELOAD_PASSWORD_ENV = "QUARKUS_LIVE_RELOAD_PASSWORD";
```
Comment (gsmet) [inline extensions/undertow-websockets/deployment/src/main/java/io/quarkus/undertow/websockets/deployment/HotReplacementWebsocketEndpoint.java]: Should we rename the `_HOT_RELOAD` constants to `_LIVE_RELOAD` (it can be done in a separate commit/pr)

File: extensions/undertow-websockets/deployment/src/main/java/io/quarkus/undertow/websockets/deployment/WebsocketHotReloadSetup.java (hunk 1 above)
Comment (dmlloyd) [reply extensions/undertow-websockets/deployment/src/main/java/io/quarkus/undertow/websockets/deployment/WebsocketHotReloadSetup.java]: > Well I just copied what was already in place, I didn't change anything there.
> The UI probably shows a change because I moved it inside else.
> I just added the reading from the system property and env var

Ah, that's not good, it should be fixed in the original place too.

> Would you like me to fix it anyway?

Yes, please.

Comment (gsmet) [reply extensions/undertow-websockets/deployment/src/main/java/io/quarkus/undertow/websockets/deployment/WebsocketHotReloadSetup.java]: So I reckon this doesn't work with Yaml as we are playing with the properties file directly?

Comment (geoand) [reply extensions/undertow-websockets/deployment/src/main/java/io/quarkus/undertow/websockets/deployment/WebsocketHotReloadSetup.java]: Sorry I didn't mean copy - paste, I meant move into the else branch.

I'm only on my phone now so I can't really fix it, I'll do that later on tonight or tomorrow morning.

And yes it won't work with YAML. We could of course add the YAML dependency and try to locate that file as well. Should we do it now or wait until someone complains?

File: extensions/undertow-websockets/deployment/src/main/java/io/quarkus/undertow/websockets/deployment/HotReplacementWebsocketEndpoint.java (hunk 2 above)
Comment (geoand) [reply extensions/undertow-websockets/deployment/src/main/java/io/quarkus/undertow/websockets/deployment/HotReplacementWebsocketEndpoint.java]: Good idea, we use that terminology elsewhere so it makes sense to be consistent

File: extensions/undertow-websockets/deployment/src/main/java/io/quarkus/undertow/websockets/deployment/WebsocketHotReloadSetup.java (hunk 1 above)
Comment (dmlloyd) [reply extensions/undertow-websockets/deployment/src/main/java/io/quarkus/undertow/websockets/deployment/WebsocketHotReloadSetup.java]: It would be nice to fix the underlying problem...

Comment (geoand) [reply extensions/undertow-websockets/deployment/src/main/java/io/quarkus/undertow/websockets/deployment/WebsocketHotReloadSetup.java]: Underlying problem, meaning? 😅

Comment (dmlloyd) [reply extensions/undertow-websockets/deployment/src/main/java/io/quarkus/undertow/websockets/deployment/WebsocketHotReloadSetup.java]: I mean actually loading these values from config instead of using this outside channel to access the values.

Comment (geoand) [reply extensions/undertow-websockets/deployment/src/main/java/io/quarkus/undertow/websockets/deployment/WebsocketHotReloadSetup.java]: Oh, yeah! I'll give it a shot and see if I can come up with anything

Comment (geoand) [reply extensions/undertow-websockets/deployment/src/main/java/io/quarkus/undertow/websockets/deployment/WebsocketHotReloadSetup.java]: I pushed a fix to use `InputStreamReader` for now. I'll dig into the issue more to see if there is any change using the regular config infrastructure tomorrow morning

File: extensions/undertow-websockets/deployment/src/main/java/io/quarkus/undertow/websockets/deployment/HotReplacementWebsocketEndpoint.java (hunk 2 above)
Comment (geoand) [reply extensions/undertow-websockets/deployment/src/main/java/io/quarkus/undertow/websockets/deployment/HotReplacementWebsocketEndpoint.java]: Done

**Comment by geoand** [comment]
@dmlloyd I pushed a change that should fix things using MP-Config. When I ran the tests locally they passed, but let's see what CI says.

**Comment by geoand** [comment]
CI likes it and I also checked that system properties also work

**Comment by geoand** [comment]
@dmlloyd what do you think about the approach in the latest commit?

**Comment by dmlloyd** [comment]
I'm not sure it adds anything.  Without the config sources, you won't get (for example) YAML properties or anything like that.  Profiles won't work, and expressions won't work.  Default values won't work either.

It's probably best to stick with the original approach.

**Comment by geoand** [comment]
>
> It's probably best to stick with the original approach.

I reverted the last commit thus restoring the original approach

**Review by dmlloyd — APPROVED** [review]

**Comment by geoand** [comment]
CI failure seems completely unrelated. I'll try restart it in a few hours and see what happens

**Comment by geoand** [comment]
At last, CI passed after a rebase
