### PR TITLE
UserTransaction should fire CDI context lifecycle events

### LINKED ISSUE #28709: QuarkusTransaction does not fire @Initialized(TransactionScoped.class)
### Describe the bug

When starting a new transaction with `QuarkusTransaction.run`, listeners listening with `@Observes @Initialized(TransactionScoped.class) Object notUsed` are not notified.

### Expected behavior

Listeners should be notified.

### Actual behavior

Listeners are not notified.

### How to Reproduce?

1. Execute [transaction-event-reproducer.zip](https://github.com/quarkusio/quarkus/files/9827630/transaction-event-reproducer.zip)
2. Wait 10s
3. See log output...it is fired for `@Transactional`, but not for `QuarkusTransaction.run`

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19044.2006]

### Output of `java -version`

OpenJDK Runtime Environment Corretto-17.0.4.9.1 (build 17.0.4.1+9-LTS)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.13.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mkouba**
- such as @Initialized(TransactionScoped.class)
- resolves #28709

### CODE REVIEW

**Review by manovotn — COMMENTED** [review]
Looks good from CDI point of view!

File: extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/NotifyingUserTransaction.java [hunk 1]
```diff
@@ -0,0 +1,68 @@
...
+import javax.transaction.HeuristicMixedException;
+import javax.transaction.HeuristicRollbackException;
+import javax.transaction.NotSupportedException;
+import javax.transaction.RollbackException;
+import javax.transaction.SystemException;
+import javax.transaction.UserTransaction;
+
+import org.jboss.logging.Logger;
+
+public class NotifyingUserTransaction extends TransactionScopedNotifier implements UserTransaction {
```
Comment (mkouba) [inline extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/NotifyingUserTransaction.java:12]: Note that the `com.arjuna.ats.internal.jta.transaction.arjunacore.UserTransactionImple` that was used directly before and is used under the hood in this PR implements `Serializable`. So in theory this is a breaking change in the sense that a user might expect the contextual instance to be `Serializable`.

I tend not to implement `Serializable` for several reasons:
- Quarkus does not support CDI passivation and passivation scopes
- the producer bean for `UserTransaction` is `@ApplicationScoped` which means that a non-serializable client proxy is injected, i.e. a user would need to unwrap the bean instance first and then serialize (I doubt anyone does it)
- `javax.transaction.UserTransaction` is not serializable and the contract of the producer bean is clear - the set of bean types contains the return type and all interfaces it extends 

WDYT? @mmusgrov @manovotn

File: extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/NotifyingUserTransaction.java [hunk 2]
```diff
@@ -0,0 +1,68 @@
...
+    private final UserTransaction delegate;
+
+    public NotifyingUserTransaction(UserTransaction delegate) {
+        this.delegate = delegate;
+    }
+
+    @Override
+    public void begin() throws NotSupportedException, SystemException {
+        delegate.begin();
+        initialized(delegate);
```
Comment (mkouba) [inline extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/NotifyingUserTransaction.java:25]: I'm not so sure about the payload used. The original `CDIDelegatingTransactionManager` used the `javax.transaction.Transaction` and for the `@Destroyed` event the value of `this.toString()`. We should probably follow the same strategy...

File: extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/NotifyingUserTransaction.java (hunk 1 above)
Comment (mmusgrov) [reply extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/NotifyingUserTransaction.java:12]: I agree @mkouba - passivating a transaction does not make sense. Thanks for sorting out this issue.

File: extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/NotifyingUserTransaction.java (hunk 2 above)
Comment (mkouba) [reply extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/NotifyingUserTransaction.java:25]: I've replaced the `this.toString()` with `this`.

Comment (manovotn) [reply extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/NotifyingUserTransaction.java:25]: I'd go with what's directly in Narayana, as seen [here](https://github.com/jbosstm/narayana/blob/master/ArjunaJTA/cdi/classes/com/arjuna/ats/jta/cdi/NarayanaTransactionManager.java#L76-L97).
JTA spec doesn't seem concerned about this at all so it's just about not polluting other observer methods for which it is reasonable to use either JTA-specific class (`Transaction`) or plain `Object`.

File: extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/NotifyingUserTransaction.java (hunk 1 above)
Comment (manovotn) [reply extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/NotifyingUserTransaction.java:12]: Agreed, but shouldn't we be consistent in how we do this for `NotifyingTransactionManager` and `NotifyingUserTransaction`? Currently, one is serializable while the other isn't.

Comment (mkouba) [reply extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/NotifyingUserTransaction.java:12]: I don't think it's a problem because the serializability is not a part of the API contract.

File: extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/TransactionScopedNotifier.java [hunk 3]
```diff
@@ -0,0 +1,41 @@
...
+
+import io.quarkus.arc.Arc;
+
+abstract class TransactionScopedNotifier {
+
+    private transient Event<Object> initialized;
+    private transient Event<Object> beforeDestroyed;
+    private transient Event<Object> destroyed;
+
+    void initialized(Object payload) {
```
Comment (manovotn) [inline extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/TransactionScopedNotifier.java:17]: To stay aligned with what Narayana does internally, the argument here should be `Transaction`

**Review by manovotn — APPROVED** [review]
Looks good, only added one small comment.

File: extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/TransactionScopedNotifier.java (hunk 3 above)
Comment (mkouba) [reply extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/TransactionScopedNotifier.java:17]: Well, we reuse this component for both TM and UT so it can't be `Transaction`. That said, we could make this class a parameterized type and use `Transaction` for TM and `UserTransaction` for UT but it's IMO not worth the effort because the runtime type of the payload is used to resolve the observer methods anyway. So an `@Observes Transaction` should still be notified.

Comment (manovotn) [reply extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/TransactionScopedNotifier.java:17]: > because the runtime type of the payload is used to resolve the observer methods anyway

Good point, then it's fine as-is

**Comment by mkouba** [comment]
@mmusgrov feel free to push the "merge' button if you're ok with this fix.

**Comment by geoand** [comment]
@mmusgrov can you take a look at this?

File: extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/NotifyingUserTransaction.java (hunk 2 above)
Comment (mmusgrov) [reply extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/NotifyingUserTransaction.java:25]: I tried looking at the spec for a definitive answer for what the initialised and destroyed event payload should contain but the spec leaves it unspecified.

TBH if I was implementing it I'd put the narayana transaction id in the payload (for the initialized, beforeDestroyed and destroyed events).

The Quarkus implementation is using delegate which is an instance of `UserTransaction` which in the Narayana case delegates to our implementation, therefore the `toString()` method has no relationship to the actual transaction scope (the actual "scope" is the transaction that is bound to the current thread - except that there would be no actual transaction for the destroyed event). It is because of these ambiguities that I would just use the transaction id which the listener can use for all transaction scope events in order to uniquely identify the scope/transaction.

**Comment by mmusgrov** [comment]
@geoand sorry for the delay, I've added a comment to the conversation between @mkouba and @manovotn

**Comment by geoand** [comment]
Thanks @mmusgrov

File: extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/NotifyingUserTransaction.java (hunk 2 above)
Comment (mmusgrov) [reply extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/NotifyingUserTransaction.java:25]: You can construct the payload in a similar way that you do in `NotifyingTransactionManager`: 

By calling `getTransaction()` on the transaction manager you will get the current transaction bound to the calling thread and that object will uniquely correspond to the active transaction scope. In the commit method you will need to cache the transaction before calling `delegate.commit();` since the call may return null after the transaction gets committed. Similarly for rollback. You should be able to use that object directly in the payload since its' `toString()` method will be unique to the transaction or you can just use the result of calling `toString()` as the payload.

Comment (mmusgrov) [reply extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/NotifyingUserTransaction.java:25]: Another observation is that in `NotifyingTransactionManager#commit()` we use `this.getTransaction()` for the payload in the beforeDestroyed event but we use `destroyed(this);` for the payload in the destroyed event. If the payload is meant to be the same (which I think it should) then I think the call to `this.getTransaction()` should be cached and the same object used for both events

Comment (mkouba) [reply extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/NotifyingUserTransaction.java:25]: > If the payload is meant to be the same (which I think it should) then I think the call to this.getTransaction() should be cached and the same object used for both events

It doesn't have to be the same. And again, I was inspired by the original code: https://github.com/quarkusio/quarkus/blob/2.13.3.Final/extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/CDIDelegatingTransactionManager.java#L97-L111. My guess that the `this.getTransaction()` wasn't used because it's not usable after `commit()/rollback()`?

In any case, I agree that a transaction id makes more sense for all events.

Comment (mkouba) [reply extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/NotifyingUserTransaction.java:25]: > My guess that the `this.getTransaction()` wasn't used because it's not usable after `commit()/rollback()`?

FTR I've found this in the javadoc of `UserTransaction#commit()`: _"When this method completes, the thread is no longer associated with a transaction."_

**Comment by mkouba** [comment]
@mmusgrov comments resolved :-)

File: extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/NotifyingUserTransaction.java [hunk 4]
```diff
@@ -0,0 +1,72 @@
...
+        try {
+            delegate.commit();
+        } finally {
+            destroyed(id);
+        }
+    }
+
+    @Override
+    public void rollback() throws IllegalStateException, SecurityException, SystemException {
+        String id = TransactionImple.getTransaction().toString();
```
Comment (mkouba) [inline extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/NotifyingUserTransaction.java:44]: @mmusgrov I hope that this the correct way to obtain the transaction id ;-)

Comment (mmusgrov) [reply extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/NotifyingUserTransaction.java:44]: Yes, @mkouba , that get's the currently bound transaction context.

BTW if there is no active transaction then `TransactionImple.getTransaction().toString()` will fail with a NPE. So `throw new SystemException("The transaction is not active!");` would be preferable.

The same comment applies to the other usages (the commit method and the commit/rollback methods in `NotifyingTransactionManager.java`).

Comment (mkouba) [reply extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/NotifyingUserTransaction.java]: Done. @mmusgrov pls review.

**Review by mmusgrov — APPROVED** [review]
Nice

**Comment by wicksim** [comment]
@mkouba Is this included in any 2.15.X? Because I can not see it in the release notes.

**Comment by mkouba** [comment]
> @mkouba Is this included in any 2.15.X? Because I can not see it in the release notes.

Yes, it is. The release blog posts do not list all the bugfixes/features. You can find it in the full changelog of 2.15.0.CR1 though: https://github.com/quarkusio/quarkus/releases/tag/2.15.0.CR1
