### PR TITLE
Properly sort beans in DevUI beans page

### LINKED ISSUE #29723: Application beans are not shown first in Arc DevUI
### Describe the bug

Some RR beans are shown before application beans in the DevUI ArC tab.
2022-12-07-1670405973_1274x462

### Expected behavior

Applications beans used to be shown first.

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.14.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #29723

### CODE REVIEW

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/devconsole/DevBeanInfo.java [hunk 1]
```diff
@@ -49,42 +49,47 @@ public static DevBeanInfo from(BeanInfo bean, CompletedApplicationClassPredicate
...
             return new DevBeanInfo(bean.getIdentifier(), kind, isApplicationBean, providerType, memberName, types, qualifiers,
                     scope, declaringClass,
-                    interceptors);
+                    interceptors, isGenerated);
         } else {
             // Synthetic bean
             return new DevBeanInfo(bean.getIdentifier(), DevBeanKind.SYNTHETIC, false, providerType, null, types, qualifiers,
                     scope, null,
-                    interceptors);
+                    interceptors, true);
```
Comment (mkouba) [inline extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/devconsole/DevBeanInfo.java:85]: Hm, synthetic beans do not require a generated type. So it might be confusing. You can test the `bean.getProviderType()` instead.

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/devconsole/Name.java [hunk 2]
```diff
@@ -101,6 +101,11 @@ static String createSimple(AnnotationInstance annotation) {
 
     @Override
     public int compareTo(Name other) {
+        // Quarkus classes should be last
```
Comment (mkouba) [inline extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/devconsole/Name.java:104]: Is this really needed? I don't see a benefit of this change. I mean why should e.g. the `io.smallrye.config.inject.ConfigProducer` go before `io.quarkus.vertx.http.runtime.CurrentVertxRequest`?

Comment (geoand) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/devconsole/Name.java:104]: It is needed because you can have application beans that are generated.

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/devconsole/DevBeanInfo.java (hunk 1 above)
Comment (geoand) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/devconsole/DevBeanInfo.java:85]: I don't really understand this, can you elaborate?

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/devconsole/Name.java (hunk 2 above)
Comment (mkouba) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/devconsole/Name.java:104]: But _generated_ application beans are handled in the `DevBeanInfo#compare()`, or?

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/devconsole/DevBeanInfo.java (hunk 1 above)
Comment (mkouba) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/devconsole/DevBeanInfo.java:85]: For synthetic beans you can use `bean.getImplClazz().isSynthetic()` instead of `true`. Because you can have a synthetic bean that provides e.g. `org.acme.Foo` and not a generated/synthetic class.

Comment (geoand) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/devconsole/DevBeanInfo.java:85]: Okay thanks

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/devconsole/Name.java (hunk 2 above)
Comment (geoand) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/devconsole/Name.java:104]: My point is that you can have beans that are both application beans and generated beans and some come from Quarkus (with no user action).
So by doing this the Quarkus ones are moved to the bottom

Comment (mkouba) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/devconsole/Name.java:104]: Well, I don't think that ordering matters here because users are probably not interested in generated beans anyway (be it a quarkus class or not). 

In other words, this should be enough (and already quite confusing ;-):
1. application beans, non-generated, sorted by providerType name
2. application beans, generated, sorted by providerType name
3. non-app beans, non-generated, sorted by providerType name
4. non-app beans, generated, sorted by providerType name

Comment (geoand) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/devconsole/Name.java:104]: I did not add this for no reason. I added it because of what I saw in a sample application.

Without the name comparison, things are still not perfect

Comment (mkouba) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/devconsole/Name.java:104]: Hm, I wonder what these "application generated beans" are. Did you use a quickstart as a sample app?

Comment (geoand) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/devconsole/Name.java:104]: `io.quarkus.resteasy.reactive.server.runtime.NotFoundExceptionMapper$GeneratedExceptionHandlerFor$NotFoundException$OfMethod$toResponse`, `io.quarkus.resteasy.reactive.server.runtime.exceptionmappers.AuthenticationFailedExceptionMapper$GeneratedExceptionHandlerFor$AuthenticationFailedException$OfMethod$handle` among a few others.

These are always included with RESTEasy Reactive

Comment (mkouba) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/devconsole/Name.java:104]: Anyway, it's not a blocker so I'm going to approve this pr ;-)

**Review by mkouba — APPROVED** [review]

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/devconsole/Name.java (hunk 2 above)
Comment (geoand) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/devconsole/Name.java:104]: That's my point. Without this change, they are displayed before the generated beans that are a result of the user writing some code.
