### PR TITLE
OIDC token propagation: add option to select named OIDC client and token exchange per REST client with the @AccessToken annotation

### LINKED ISSUE #36458: Enhance OIDC token propagation filters to select named OIDC clients
### Description

OIDC token propagation filters, before propagating the tokens, can exchange them with the OIDC server to set the correct target service audience, with this token exchange supported by a named OIDC client. 
Right now, it is not possible to associate a specific named OIDC client with a specific REST Client annotated with the `@AccessToken` which enabled a token propagation filter for this REST Client, see #36440

### Implementation ideas

Allow to use `@AccessToken` like this:
```
@AccessToken("named-oidc-client")
interface MyRestClient {
   @GET
   String getData();
}
```

Similarly to how it can be done for `OidcClientFilter`.

Additionally it should be possible to use `@AccessToken` to customize an exchange token requirement when a default client is used as it is not really needed for named clients

### LINKED ISSUE #36994: OIDC AccessToken can lead to AmbiguousResolutionException
### Describe the bug

Using io.quarkus.oidc.token.propagation.AccessToken annotation on a OIDC client leads to AmbiguousResolutionException if any custom AccessTokenRequestFilter is defined. [example of it's definition](https://github.com/sberyozkin/quarkus/blob/3cc528b80122d69b394c1cba1872ee0f65cb2915/extensions/oidc-token-propagation/deployment/src/test/java/io/quarkus/oidc/token/propagation/CustomAccessTokenRequestFilter.java)

Exception is: jakarta.enterprise.inject.AmbiguousResolutionException: Beans: [CLASS bean [class=io.quarkus.ts.security.keycloak.oidcclient.extended.restclient.ping.filters.CustomTokenRequestFilter, id=oJQuCeYWIxp6j-Oe322IFp9iDbk], CLASS bean [class=io.quarkus.oidc.token.propagation.AccessTokenRequestFilter, id=uT_pr1MaC1nPZjXJ_ZSEFBRfYeY]]

This exception occurs, when I try to inject the client.

### Expected behavior

Quarkus will inject the client without problem. Annotation @AccessToken should work, even if custom filters are defined.

### Actual behavior

Injecting client will fail, because dependency injection can't resolve the filter class.

### How to Reproduce?

1. Define any client with @AccessToken annotation. e.g.
```
@RegisterRestClient
@AcessToken
public interface TokenClient{}
```
2. Define custom AccessTokenRequestFilter, e.g.
```
public class CustomAccessTokenRequestFilter extends AccessTokenRequestFilter{}
```
3. Try to inject the client into a http resource, e.g.
```
@Inject
@RestClient
TokenClient tokenClient;
```
4. Try to call the client.

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

openjdk 11.0.19

### Quarkus version or git rev

999-SNAPSHOT

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by michalvavrik**
closes: #36994
closes: #36458

### CODE REVIEW

File: extensions/oidc-client/runtime/src/main/java/io/quarkus/oidc/token/propagation/AccessToken.java [hunk 1]
```diff
@@ -17,4 +17,44 @@
...
 @Documented
 public @interface AccessToken {
+
+    /**
+     * Name of the configured OidcClient. Default OidcClient will be used when no value is specified.
+     */
+    String value() default "";
+
+    /**
+     * Exchange the current token with OpenId Connect Provider for a new token using either
```
Comment (sberyozkin) [inline extensions/oidc-client/runtime/src/main/java/io/quarkus/oidc/token/propagation/AccessToken.java:27]: Hi @michalvavrik 

So, if we do not specify the client name here, then the token propagation properties apply (exchange token required property only)...
I wonder if just having a client name is enough. I should've done it in the properties too, i.e, I have 2 duplicating properties there, `exchangeToken` and the `client` name - but the client name is only relevant if the `exchangeToken` is enabled.

So may be here, we only have an `exchangeTokenClient` property, if it it set (`Default`, or any other named client name value) we enabled the token exchange, if it is not set we don't...

I feel it can help us avoid adding all the exchange attributes just to regulate or disable the token exchange. 
For example, you have a `DISABLE` enum, but then setting the client name makes no sense as well...

So, I propose to have an `exchangeTokenClient` property with no default value, please consider it

Comment (michalvavrik) [reply extensions/oidc-client/runtime/src/main/java/io/quarkus/oidc/token/propagation/AccessToken.java:27]: Hey @sberyozkin ,

implementation wise I have no problem to do that. I think that `@AccessToken(exchangeTokenClient = "Default")` already does exactly same thing as the `@AccessToken("Default")`.IMO your proposal is not simplifying it, but I don't mind.

> For example, you have a DISABLE enum, but then setting the client name makes no sense as well...

but you can also disable token exchange for default client while it is enabled for all the others by configuration properties. While your proposal means you can't override configuration properties.

> So, I propose to have an exchangeTokenClient property with no default value, please consider it

No default value means the `exchangeTokenClient` would be required. You mean that default value will be an empty string I assume. So "" -> token exchange enabled/disabled depending on the configuration properties, while "Default" or any other value means enabled. np.

Comment (michalvavrik) [reply extensions/oidc-client/runtime/src/main/java/io/quarkus/oidc/token/propagation/AccessToken.java:27]: Let's settle on your suggestion as I want to make change now.

File: extensions/oidc-client/runtime/src/main/java/io/quarkus/oidc/token/propagation/AccessToken.java [hunk 2]
```diff
@@ -17,4 +17,13 @@
 @Retention(RetentionPolicy.RUNTIME)
 @Documented
 public @interface AccessToken {
+
+    /**
+     * Selects name of the configured OidcClient and activates token exchange for the annotated REST client.
+     * Default OidcClient is used when no value is specified, in which case the token exchange will only be active when
```
[the remark this answers is not in the document]
Comment (michalvavrik) [reply extensions/oidc-client/runtime/src/main/java/io/quarkus/oidc/token/propagation/AccessToken.java:23]: I'd hire you into docs team at once. Will fix that.

**Review by sberyozkin — APPROVED** [review]
Thanks @michalvavrik

**Comment by gsmet** [comment]
Added for consideration for backports after discussion with @gastaldi see QUARKUS-4318.
