### PR TITLE
Normalize the quarkus.http.root-path at config level

### LINKED ISSUE #19492: Static Content with quarkus.http-root-context
### Describe the bug

If I set the quarkus.http-root-context static content does not always work.

I have a Vue front end that is included from the src/main/ui directory.

When I run it from the command line

java -jar target/quarkus-app/quarkus-run.jar

The jax-rs call works but the static content does not.

### Expected behavior

quarkus.http-root-context = /testing/

Working:
http://127.0.0.1:8080/testing/hello

Not working:
http://127.0.0.1:8080/testing/
http://127.0.0.1:8080/testing/index.html

These should show the web page from the UI directory, note if I don't have the quarkus.http-root-context set it works correctly.

### Actual behavior

It should be displaying the index.html build from the ui directory, instead I get the error.

RESTEASY003210: Could not find resource for full path: http://127.0.0.1:8080/testing/index.html

### How to Reproduce?

[test-me.zip](https://github.com/quarkusio/quarkus/files/7012376/test-me.zip)

maven clean package
java -jar target/quarkus-app/quarkus-run.jar

Browser to 
http://127.0.0.1:8080/testing/index.html

Which will fail.

### Output of `uname -a` or `ver`

Darwin xxxxxx 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:27 PDT 2021; root:xnu-7195.141.2~5/RELEASE_ARM64_T8101 arm64

### Output of `java -version`

openjdk version "11.0.11" 2021-04-20 LTS OpenJDK Runtime Environment Zulu11.48+21-CA (build 11.0.11+9-LTS) OpenJDK 64-Bit Server VM Zulu11.48+21-CA (build 11.0.11+9-LTS, mixed mode)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.1.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d) Maven home: /Users/brent/.m2/wrapper/dists/apache-maven-3.8.1-bin/2l5mhf2pq2clrde7f7qp1rdt5m/apache-maven-3.8.1 Java version: 11.0.11, vendor: Azul Systems, Inc., runtime: /Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home Default locale: en_NZ, platform encoding: UTF-8 OS name: "mac os x", version: "11.5.2", arch: "aarch64", family: "mac"

### Additional information

It uses the following maven plugin to copy the UI into place, normally it would be a dist directory under ui build from VueJS, but I have simplified it down for this example.

      <plugin>
        <artifactId>maven-resources-plugin</artifactId>
        <version>3.1.0</version>
        <executions>
          <execution>
            <id>copy-resources</id>
            <phase>validate</phase>
            <goals>
              <goal>copy-resources</goal>
            </goals>
            <configuration>
              <outputDirectory>${basedir}/target/classes/META-INF/resources</outputDirectory>
              <resources>
                <resource>
                  <directory>src/main/ui</directory>
                </resource>
              </resources>
            </configuration>
          </execution>
        </executions>
      </plugin>

_No response_

### PR DESCRIPTION
**Pull request by gsmet**
Make sure the quarkus.http.root-path always starts and ends with a '/'
so that we don't have any risk of having logic working with '/test' and
not with '/test/'.

Fixes #19492

### CODE REVIEW

**Comment by gsmet** [comment]
Converting to draft for now. I'll have a closer look at what's going on.

**Comment by gsmet** [comment]
Should be ready now.

**Comment by gsmet** [comment]
This is a bit of a can of worms. I'm making additional adjustments.

**Review by ebullient — APPROVED** [review]

**Comment by stuartwdouglas** [comment]
LGTM in theory, but the failures look related.

**Comment by gsmet** [comment]
Yeah... the servlet part is quite a mess on this side and the Micrometer tests are using servlet. I'm trying to clean this up and will push an update tomorrow morning once I have run more tests.

**Comment by gsmet** [comment]
Removing the backport labels as it ends up being far more intrusive than I would have expected.

File: core/deployment/src/main/java/io/quarkus/deployment/util/UriNormalizationUtil.java [hunk 1]
```diff
@@ -91,14 +91,18 @@ public static URI toURI(String path, boolean trailingSlash) {
...
      * @param base URI to resolve relative paths. Use {@link #toURI(String, boolean)} to construct this parameter.
-     * 
+     *
      * @param segment Relative or absolute path
      * @param trailingSlash true if resulting URI must end with a '/'
      * @throws IllegalArgumentException if the path contains invalid characters or path segments.
      */
     public static URI normalizeWithBase(URI base, String segment, boolean trailingSlash) {
         if (segment == null || segment.trim().isEmpty()) {
-            return base;
```
Comment (gsmet) [inline core/deployment/src/main/java/io/quarkus/deployment/util/UriNormalizationUtil.java:101]: In this case, the method would have returned `/app/` for instance even if `trailingSlash` was false, which breaks the contract of a few of your methods that have a javadoc saying the path will never end with a `/`. I also had to fix a test that was incorrect.

File: extensions/resteasy-classic/resteasy/deployment/src/main/java/io/quarkus/resteasy/deployment/ResteasyServletProcessor.java [hunk 2]
```diff
@@ -53,9 +53,8 @@ public void jaxrsConfig(
             BuildProducer<io.quarkus.resteasy.server.common.spi.ResteasyJaxrsConfigBuildItem> resteasyJaxrsConfig,
             HttpRootPathBuildItem httpRootPathBuildItem) {
         if (resteasyServerConfig.isPresent()) {
-            String rp = resteasyServerConfig.get().getRootPath();
-            String rootPath = httpRootPathBuildItem.resolvePath(rp.startsWith("/") ? rp.substring(1) : rp);
-            String defaultPath = httpRootPathBuildItem.resolvePath(resteasyServerConfig.get().getPath());
```
Comment (gsmet) [inline extensions/resteasy-classic/resteasy/deployment/src/main/java/io/quarkus/resteasy/deployment/ResteasyServletProcessor.java:58]: I think this was completely incorrect and only worked because `resteasyServerConfig.get().getPath()` was always starting with a '/' and thus resolving just returned it.

That being said, this is all very confusing and unclear and the very generic variable names don't help to understand what these things are supposed to be.

**Review by gsmet — COMMENTED** [review]
@ebullient I tweaked a few more things as the servlet path was not happy (and you use it in your Micrometer tests). I think I whacked all the moles but let's see what CI has to say.

I added a few comments at your intention. Could you have a look?

Also, I'll squash everything once settled.

File: extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/HttpRootPathBuildItem.java [hunk 3]
```diff
@@ -66,6 +66,33 @@ public String resolvePath(String path) {
...
     }
 
+    /**
+     * Resolve path that is always relative into an absolute path.
+     * Whether the path is relative or absolute, it will be resolved against `quarkus.http.root-path`,
+     * by removing the '/' in the latter case.
+     * <p>
+     * Given {@literal quarkus.http.root-path=/}
+     * <ul>
+     * <li>{@code resolvePath("foo")} will return {@literal /foo}</li>
```
Comment (ebullient) [inline extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/HttpRootPathBuildItem.java:76]:
```suggestion
     * <li>{@code relativePath("foo")} will return {@literal /foo}</li>
```

File: extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/HttpRootPathBuildItem.java [hunk 4]
```diff
@@ -66,6 +66,33 @@ public String resolvePath(String path) {
...
+     * <li>{@code resolvePath("/foo")} will return {@literal /foo}</li>
```
Comment (ebullient) [inline extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/HttpRootPathBuildItem.java:77]:
```suggestion
     * <li>{@code relativePath("/foo")} will return {@literal /foo}</li>
```

File: extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/HttpRootPathBuildItem.java [hunk 5]
```diff
@@ -66,6 +66,33 @@ public String resolvePath(String path) {
...
+     * </ul>
+     * Given {@literal quarkus.http.root-path=/app}
+     * <ul>
+     * <li>{@code resolvePath("foo")} will return {@literal /app/foo}</li>
```
Comment (ebullient) [inline extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/HttpRootPathBuildItem.java:81]:
```suggestion
     * <li>{@code relativePath("foo")} will return {@literal /app/foo}</li>
```

File: extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/HttpRootPathBuildItem.java [hunk 6]
```diff
@@ -66,6 +66,33 @@ public String resolvePath(String path) {
...
+     * <li>{@code resolvePath("/foo")} will return {@literal /app/foo}</li>
```
Comment (ebullient) [inline extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/HttpRootPathBuildItem.java:82]:
```suggestion
     * <li>{@code relativePath("/foo")} will return {@literal /app/foo}</li>
```

**Comment by gsmet** [comment]
@ebullient I included your comments and squashed the whole thing. It should be ready now. Figuring out the purpose of the build items and properly documenting them is a task for another day.

File: extensions/resteasy-classic/resteasy-server-common/deployment/src/main/java/io/quarkus/resteasy/server/common/deployment/ResteasyServerCommonProcessor.java [hunk 7]
```diff
@@ -135,9 +137,17 @@
 
         /**
          * Set this to override the default path for JAX-RS resources if there are no
-         * annotated application classes.
+         * annotated application classes. This path is specified with a leading {@literal /}, but is resolved relative
+         * to {@literal quarkus.http.root-path}.
+         * <ul>
+         * <li>If {@literal quarkus.http.root-path=/} and {@code quarkus.resteasy.path=/bar}, the JAX-RS resource path will be
+         * {@literal /bar}</li>
+         * <li>If {@literal quarkus.http.root-path=/bar} and {@code quarkus.resteasy.path=/bar}, the JAX-RS resource path will
```
Comment (ebullient) [inline extensions/resteasy-classic/resteasy-server-common/deployment/src/main/java/io/quarkus/resteasy/server/common/deployment/ResteasyServerCommonProcessor.java:145]:
```suggestion
         * <li>If {@literal quarkus.http.root-path=/foo} and {@code quarkus.resteasy.path=/bar}, the JAX-RS resource path will
```

File: extensions/undertow/deployment/src/main/java/io/quarkus/undertow/deployment/ServletConfig.java [hunk 8]
```diff
@@ -1,22 +1,37 @@
...
+     * The context path for Servlet content. This will determine the path used to
+     * resolve all Servlet-based resources, including JAX-RS resources - when using the Undertow extension in conjunction with
+     * RESTEasy.
+     * <p>
+     * This path is specified with a leading {@literal /}, but is resolved relative
+     * to {@literal quarkus.http.root-path}.
+     * <ul>
+     * <li>If {@literal quarkus.http.root-path=/} and {@code quarkus.servlet.context-path=/bar}, the servlet path will be
+     * {@literal /bar}</li>
+     * <li>If {@literal quarkus.http.root-path=/bar} and {@code quarkus.servlet.context-path=/bar}, the servlet path will be
```
Comment (ebullient) [inline extensions/undertow/deployment/src/main/java/io/quarkus/undertow/deployment/ServletConfig.java:29]:
```suggestion
     * <li>If {@literal quarkus.http.root-path=/foo} and {@code quarkus.servlet.context-path=/bar}, the servlet path will be
```

**Review by ebullient — COMMENTED** [review]
I made the same mistake twice in my suggestions. 🙄  sorry.

**Comment by gsmet** [comment]
@ebullient fixed.

**Review by ebullient — APPROVED** [review]

**Review by stuartwdouglas — APPROVED** [review]
