### PR TITLE
Set owner's permission to execute manage.sh

### LINKED ISSUE #10386: Generated manage.sh script not executable
**Describe the bug**
When following the instructions in https://quarkus.io/guides/amazon-lambda#create-the-function, the generated manage.sh script is not executable.

**Expected behavior**
I can run the script.

**Actual behavior**
./target/manage.sh
zsh: permission denied: ./target/manage.sh

**To Reproduce**
Follow the guide

### PR DESCRIPTION
**Pull request by ejba**
Fixes: #10386

### CODE REVIEW

File: extensions/amazon-lambda/common-deployment/src/main/java/io/quarkus/amazon/lambda/deployment/LambdaUtil.java [hunk 1]
```diff
@@ -76,7 +90,7 @@ public static void generateScripts(String handler, OutputTargetBuildItem target)
         output = copyResource("lambda/manage.sh")
                 .replace("${handler}", handler)
                 .replace("${lambdaName}", lambdaName);
-        writeFile(target, "manage.sh", output);
+        writeExecutableFile(target, "manage.sh", output);
```
Comment (jaikiran) [inline extensions/amazon-lambda/common-deployment/src/main/java/io/quarkus/amazon/lambda/deployment/LambdaUtil.java:93]: Should the same be done for `bootstrap-example.sh` which gets created a few lines above this?

Comment (ejba) [reply extensions/amazon-lambda/common-deployment/src/main/java/io/quarkus/amazon/lambda/deployment/LambdaUtil.java:93]: done

**Review by gsmet — APPROVED** [review]

**Comment by jaikiran** [comment]
Failure (on Windows) looks related:
```
funqy-amazon-lambda: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
2020-07-01T08:50:37.8102736Z [ERROR] 	[error]: Build step io.quarkus.funqy.deployment.bindings.FunqyScriptGeneratorProcessor#buildScripts threw an exception: java.lang.UnsupportedOperationException
2020-07-01T08:50:37.8103068Z [ERROR] 	at java.base/java.nio.file.Files.setPosixFilePermissions(Files.java:2078)
2020-07-01T08:50:37.8103372Z [ERROR] 	at io.quarkus.amazon.lambda.deployment.LambdaUtil.writeExecutableFile(LambdaUtil.java:64)
2020-07-01T08:50:37.8103669Z [ERROR] 	at io.quarkus.amazon.lambda.deployment.LambdaUtil.generateScripts(LambdaUtil.java:86)
2020-07-01T08:50:37.8103985Z [ERROR] 	at io.quarkus.funqy.deployment.bindings.FunqyScriptGeneratorProcessor.buildScripts(FunqyScriptGeneratorProcessor.java:13)
2020-07-01T08:50:37.8104282Z [ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-07-01T08:50:37.8104693Z [ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-07-01T08:50:37.8105012Z [ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-07-01T08:50:37.8106327Z [ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-07-01T08:50:37.8106657Z [ERROR] 	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:932)
2020-07-01T08:50:37.8106950Z [ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
2020-07-01T08:50:37.8107244Z [ERROR] 	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
2020-07-01T08:50:37.8107547Z [ERROR] 	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
2020-07-01T08:50:37.8107850Z [ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
2020-07-01T08:50:37.8108144Z [ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
2020-07-01T08:50:37.8108429Z [ERROR] 	at java.base/java.lang.Thread.run(Thread.java:834)
2020-07-01T08:50:37.8108703Z [ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
2020-07-01T08:50:37.8108962Z [ERROR] -> [Help 1]
```

**Comment by gsmet** [comment]
Yeah, that was exactly the question I had when I reviewed the PR.

**Comment by ejba** [comment]
Oops, forgot to support Windows!

File: extensions/amazon-lambda/common-deployment/src/main/java/io/quarkus/amazon/lambda/deployment/LambdaUtil.java [hunk 2]
```diff
@@ -50,6 +53,17 @@ public static void writeFile(OutputTargetBuildItem target, String name, String o
...
 
+    public static void writeExecutableFile(OutputTargetBuildItem target, String name, String output) throws IOException {
+        writeFile(target, name, output);
+
+        Path artifact = target.getOutputDirectory().resolve(name);
+        Set<PosixFilePermission> permissions = new HashSet<>();
+        permissions.add(PosixFilePermission.OWNER_READ);
+        permissions.add(PosixFilePermission.OWNER_WRITE);
+        permissions.add(PosixFilePermission.OWNER_EXECUTE);
+        Files.setPosixFilePermissions(artifact, permissions);
```
Comment (jaikiran) [inline extensions/amazon-lambda/common-deployment/src/main/java/io/quarkus/amazon/lambda/deployment/LambdaUtil.java:64]: Given the failure on Windows, I think what you will have to do is conditionally set these PosixFilePermissions, something like:

```
if (Files.getFileAttributeView(artifact, PosixFilePermission.class) != null) {
... // setup the permissions
}
```

Comment (ejba) [reply extensions/amazon-lambda/common-deployment/src/main/java/io/quarkus/amazon/lambda/deployment/LambdaUtil.java:64]: According with documentation, I could do just this. Tell me what do you think. 

```
        Path artifact = target.getOutputDirectory().resolve(name);
        File file = new File(artifact.toString());
        file.setExecutable(true, true);
```

Comment (jaikiran) [reply extensions/amazon-lambda/common-deployment/src/main/java/io/quarkus/amazon/lambda/deployment/LambdaUtil.java:64]: I had forgotten about that one. Yes, that one looks much simpler and more relevant to what we want. One minor nit - instead of `new File(artifact.toString())` , you can just do `artifact.toFile().setExecutable(true, true);`

Comment (ejba) [reply extensions/amazon-lambda/common-deployment/src/main/java/io/quarkus/amazon/lambda/deployment/LambdaUtil.java]: Done!

**Comment by gsmet** [comment]
Merged, thanks!
