### PR TITLE
Intercepted subclasses generation - fix evaluation of skipped methods 

### LINKED ISSUE #19177: Regression v2.0.2.Final: RolesAllowed check skipped when endpoint method payload POJO class is private
### Describe the bug

`@RolesAllowed` annotation is ignored for endpoints, which methods have strongly-typed POJO as parameter, and if POJO class is inner and private. 
Quarkus v2.0.1.Final is the last version where it works correctly, staring from v2.0.2.Final it works as described.

### Expected behavior

REST service should return http 401/403 and endpoint method/implementation should not be called.  

### Actual behavior

Endpoint method/implementation is executed and response is sent to the client despite missing JWT/role.

#### Given
Quarkus: v2.0.2.Final or newer
Extensions: `cdi, oidc, resteasy, resteasy-jackson, security, smallrye-context-propagation`
POST endpoint accepting payload as strongly-typed POJO **private**  class, with `@RolesAllowed("some-group")` annotation

#### When 
When endpoint is requested without valid JWT or when 'groups' claim does not contain required group (role)

#### Sample code
Minimal reproducer project: https://github.com/lwitkowski/quarkus-role-bug/
Github Actions: https://github.com/lwitkowski/quarkus-role-bug/actions/runs/1090923795

### PR DESCRIPTION
**Pull request by mkouba**
- do not skip methods with a private param
- also do not evaluate methods that declare no interceptor bindings;
these methods are skipped automatically
- related to #19177

### CODE REVIEW

**Comment by mkouba** [comment]
This PR should supersede https://github.com/quarkusio/quarkus/pull/21625 and fix https://github.com/quarkusio/quarkus/issues/19177.

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Methods.java [hunk 1]
```diff
@@ -536,17 +549,24 @@ public boolean test(MethodInfo method) {
...
                 String originalClassPackage = DotNames.packageName(originalClazz.name());
                 for (Type type : parameters) {
-                    ClassInfo parameterClassInfo = beanArchiveIndex.getClassByName(type.name());
-                    if (parameterClassInfo == null) {
-                        continue; // hope for the best
+                    ClassInfo param = beanArchiveIndex.getClassByName(type.name());
+                    if (param == null) {
+                        // parameter type info is not available
+                        LOGGER.warn(String.format(
+                                "Parameter type info not available: %s - unable to validate the paremeter types visibility for method %s declared on %s",
```
Comment (Ladicek) [inline independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Methods.java:556]:
```suggestion
                                "Parameter type info not available: %s - unable to validate the parameter type's visibility for method %s declared on %s",
```

**Review by Ladicek — APPROVED** [review]
OK, it took me a while to realize that by "do not skip methods with a private param", you mean "do not skip methods with a private param _declared in the same package_", but that obviously makes sense.

**Review by geoand — APPROVED** [review]

**Review by manovotn — APPROVED** [review]

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Methods.java [hunk 2]
```diff
@@ -536,17 +549,30 @@ public boolean test(MethodInfo method) {
...
-                    if (!Modifier.isPublic(parameterClassInfo.flags())) {
-                        // parameters whose class is package-private and the package is not the same as the package of the method for which we are checking can not be loaded,
-                        // as we would end up with IllegalAccessError when trying to access the use the load the class
-                        return !DotNames.packageName(parameterClassInfo.name()).equals(originalClassPackage);
+                    if (Modifier.isPublic(param.flags()) || Modifier.isProtected(param.flags())) {
+                        continue;
+                    }
+                    // e.g. parameters whose class is package-private and the package is not the same as the package of the method for which we are checking can not be loaded,
+                    // as we would end up with IllegalAccessError when trying to access the use the load the class
+                    if (!DotNames.packageName(param.name()).equals(originalClassPackage)) {
```
Comment (stuartwdouglas) [inline independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Methods.java:571]: IMHO this should be an error rather than a warning. We have seen cases where security interceptors are not applied even though the user was expecting them to be.

Comment (mkouba) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Methods.java:571]: I agree but the problem is that if you annotate a class with an interceptor binding then all methods (incl. inherited ones) should be intercepted and sometimes you need to extend a class from a different package which you don't control. Such an extended class may declare e.g. a package-private method that accepts a private param type. And since you're not able to modify the extended class you'd be screwed. An example from the [original issue](https://github.com/quarkusio/quarkus/issues/18477) is `java.util.concurrent.ThreadPoolExecutor` and `ThreadPoolExecutor.runWorker(Worker)`.

Comment (mkouba) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Methods.java:571]: I'm going to merge this PR. @stuartwdouglas if you really think that the current behavior is wrong (actually, before this PR the method is ignored and no warning is logged) then pls file a new issue.

**Comment by kdubb** [comment]
@mkouba This PR seems to cause warnings for primitive arrays.

Specifically the check following this: https://github.com/quarkusio/quarkus/blob/277523b3d53a507334727bf9289d358fcfebe730/independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Methods.java#L559

Causes the following warnings.
> Parameter type info not available: [B - unable to validate the parameter type's visibility for method parse declared on io.outfoxx.cloud.security.jwt.jwk.JsonWebKeySetLoader

**Comment by manovotn** [comment]
@kdubb this should fix it - https://github.com/quarkusio/quarkus/pull/21900
