### PR TITLE
Set `quarkus.application.name` and `quarkus.application.version` in the default source for the Gradle plugin

### LINKED ISSUE #40444: Build-time configuration values for quarkus.application.name are ignored
### Describe the bug

According to https://quarkus.io/guides/gradle-tooling#configuring-quarkus-builds, build config can be provided by passing system properties to Gradle, but providing a value for `quarkus.application.name` does not have any effect. 

The output of the `quarkusShowEffectiveConfig` task shows that the value is ignored, and the banner printed on app start uses the default project name:  `2024-05-03 17:44:40,384 INFO  [io.quarkus] (main) code-with-quarkus 1.0.0-SNAPSHOT on JVM (powered by Quarkus 3.10.0) started in 0.395s. Listening on: http://0.0.0.0:8080`

### Expected behavior

The output of `./gradlew -Dquarkus.application.name=my-overridden-app-name quarkusShowEffectiveConfig` should show the value of the `quarkus.application.name` property to be `my-overridden-app-name`

### Actual behavior

The output of `./gradlew -Dquarkus.application.name=my-overridden-app-name quarkusShowEffectiveConfig` shows the value of the `quarkus.application.name` property to be the default, which is `code-with-quarkus`

### How to Reproduce?

1. Generate a Quarkus project via https://code.quarkus.io/ using Gradle as the build tool and add the Kotlin extension
2. Run the `quarkusShowEffectiveConfig` from the root, providing a value for `quarkus.application.name` via the system property: ```./gradlew -Dquarkus.application.name=my-overridden-app-name quarkusShowEffectiveConfig```

### Output of `uname -a` or `ver`

Darwin UKIMG9M7DG60QR 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "21.0.2" 2024-01-16 LTS OpenJDK Runtime Environment Corretto-21.0.2.13.1 (build 21.0.2+13-LTS) OpenJDK 64-Bit Server VM Corretto-21.0.2.13.1 (build 21.0.2+13-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.10.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.6

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by radcortez**
- Fixes #40444

### CODE REVIEW

File: devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/AbstractQuarkusExtension.java [hunk 1]
```diff
@@ -75,7 +75,24 @@ private BaseConfig buildBaseConfig() {
         // Using common code to construct the "base config", which is all the configuration (system properties,
         // environment, application.properties/yaml/yml, project properties) that is available in a Gradle task's
         // _configuration phase_.
-        EffectiveConfig effectiveConfig = buildEffectiveConfiguration(Collections.emptyMap());
+        Set<File> resourcesDirs = getSourceSet(project, SourceSet.MAIN_SOURCE_SET_NAME).getResources().getSourceDirectories()
+                .getFiles();
```
Comment (gsmet) [inline devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/AbstractQuarkusExtension.java:79]: I'm not sure `MAIN_SOURCE_SET_NAME` always exists? Or did we check that before?

Comment (radcortez) [reply devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/AbstractQuarkusExtension.java:79]: This was inlined from https://github.com/quarkusio/quarkus/pull/41337/files#diff-2c6f0d62b0763af665a1bc242ad078ce25794f20632651181549d838e3452998L118. I can revert that back and put it into two methods.

**Review by gsmet — APPROVED** [review]
OK. Let's see how it goes then :).
