### PR TITLE
Use a copy of compile classpath for panache annotation processor lookup

### LINKED ISSUE #23776: Running gradle quarkusDev fails in a multi-module Gradle project
### Describe the bug

I am learning the tutorial: [GETTING STARTED WITH REACTIVE](https://quarkus.io/guides/getting-started-reactive)

When I run `gradle :quarkus-reactive:quarkusDev` in a multi-module gradle project, I get an exception

> Execution failed for task ':quarkus-reactive:compileJava'.
> \> Cannot change dependencies of dependency configuration ':quarkus-reactive:annotationProcessor' after it has been included in dependency resolution. Use 'defaultDependencies' instead of 'beforeResolve' to specify default dependencies for a configuration.

When I comment out `implementation("io.quarkus:quarkus-hibernate-reactive-panache")` it works fine

### Expected behavior

This Quarkus plugin should work fine in other submodules

### Actual behavior

this Quarkus plugin doesn't seem to be able to execute `compileJava` task in submodule

### How to Reproduce?

Here is my example code:

[reproduce/quarkus at main · tabuyos/reproduce](https://github.com/tabuyos/reproduce/tree/main/quarkus)

Execute the `gradle :quarkus-reactive:quarkusDev` task in the quarkus directory

### Output of `uname -a` or `ver`

Microsoft Windows [version 10.0.19043.1466]

### Output of `java -version`

openjdk version "16" 2021-03-16

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.7.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.0.2

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by glefloch**
This change looks for panache dependency on a copy of the compile classpath instead of the real compile classpath.
 
In some case, the `annotationProcessor` configuration is configured to extend `compileOnly` configuration. When looking up for the `quarkus-panache-common` dependency, we resolve the `COMPILE_CLASSPATH` which then make it impossible to add a dependency to the `annotationProcessor` configuration as a part as already been resolved. 

close #23776

### CODE REVIEW

File: devtools/gradle/gradle-model/src/main/java/io/quarkus/gradle/dependency/ApplicationDeploymentClasspathBuilder.java [hunk 1]
```diff
@@ -70,10 +70,12 @@ public static void initConfigurations(Project project) {
                         configContainer.getByName(JavaPlugin.RUNTIME_CLASSPATH_CONFIGURATION_NAME));
 
         // enable the Panache annotation processor on the classpath, if it's found among the dependencies
-        configContainer.getByName(JavaPlugin.ANNOTATION_PROCESSOR_CONFIGURATION_NAME).getIncoming()
-                .beforeResolve(annotationProcessors -> {
-                    Set<ResolvedArtifact> compileClasspathArtifacts = configContainer
-                            .getByName(JavaPlugin.COMPILE_CLASSPATH_CONFIGURATION_NAME).getResolvedConfiguration()
+        configContainer.getByName(JavaPlugin.ANNOTATION_PROCESSOR_CONFIGURATION_NAME)
+                .defaultDependencies(annotationProcessors -> {
```
Comment (aloubyansky) [inline devtools/gradle/gradle-model/src/main/java/io/quarkus/gradle/dependency/ApplicationDeploymentClasspathBuilder.java:74]: Could you please explain the reason for changing to the `defaultDependencies(...)` here? The javadoc says
````
Execute the given action if the configuration has no defined dependencies when it first participates in dependency resolution.
````
Would it still work if there already are some default dependencies and the `quarkus-panache-common` is not among them?

Comment (glefloch) [reply devtools/gradle/gradle-model/src/main/java/io/quarkus/gradle/dependency/ApplicationDeploymentClasspathBuilder.java:74]: I followed the error message but as you mentioned this is not what we are looking for. 
The `withDependencies` should be ok. I will give it a try.

Comment (glefloch) [reply devtools/gradle/gradle-model/src/main/java/io/quarkus/gradle/dependency/ApplicationDeploymentClasspathBuilder.java]: I replace the `defaultDependencies` by the `withDependencies` which always runs before dependency resolution.

**Review by aloubyansky — APPROVED** [review]

**Comment by gsmet** [comment]
I wasn't able to backport this one as the modified file is just not around in 2.7. If we want this in 2.7, we need a specific backport targeting the 2.7 branch.
