### PR TITLE
Force reloadability of project dependencies in QuarkusApplicationModelTask

### LINKED ISSUE #48159: Gradle regression in tests when a module has a "sidecar" module
### Describe the bug

From Quarkus 3.22.0 to Quarkus 3.23.0 there is a regression in `@QuarkusTest` when a module `A` uses a class from module `B` that reference a class from module `A`. In this situation, a `ClassNotFoundException` is thrown. There is no problem in Quarkus 3.21.4.

Let's say module `A` has a class `Person`:
```java
public record Person(String id) {}
```

And module `B` a `PersonFactory`:
```java
public class PersonFactory {
	public static Person newRandomPerson() {
		return new Person(UUID.randomUUID().toString());
	}
}
```

module `A` imports `B` as a test dependency:
```kotlin
dependencies {
    ...
    testImplementation(project(":B"))
    testImplementation("io.quarkus:quarkus-junit5")
}
```

And module `B` imports `A` as a main dependency:
```kotlin
dependencies {
    implementation(project(":A"))
}
```

If module `A` uses `PersonFactory#newRandomPerson`  in a `@QuarkusTest`, a `ClassNotFoundException` is thrown:
```java
@QuarkusTest
class PersonTest {
	@Test
	void test() {
		PersonFactory.newRandomPerson();
	}
}
```

With the stacktrace being:
```
java.lang.NoClassDefFoundError: com/module/Person
	at com.module.test.PersonFactory.newRandomPerson(PersonFactory.java:9)
	at com.module.PersonTest.test(PersonTest.java:12)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:999)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestMethod(QuarkusTestExtension.java:847)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.ClassNotFoundException: com.module.Person
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:549)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:523)
	... 7 more
```

### How to Reproduce?

Here's a reproducer:
[test-classloader-issue.zip](https://github.com/user-attachments/files/20526481/test-classloader-issue.zip)

1. Go to `PersonFactory` and launch the test
    - A `ClassNotFoundException` should be thrown
2. In `gradle.properties` use the Quarkus version 3.21.4
3. Run the test again
   - The test should pass

### Output of `uname -a` or `ver`

Darwin MacBook-Pro.local 24.5.0 Darwin Kernel Version 24.5.0: Tue Apr 22 19:53:27 PDT 2025; root:xnu-11417.121.6~2/RELEASE_ARM64_T6041 arm64

### Output of `java -version`

openjdk version "21.0.5" 2024-10-15 LTS OpenJDK Runtime Environment Temurin-21.0.5+11 (build 21.0.5+11-LTS) OpenJDK 64-Bit Server VM Temurin-21.0.5+11 (build 21.0.5+11-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.22.0 to 3.23.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.13 and 8.14

### Additional information

May be related to https://github.com/quarkusio/quarkus/issues/48157, but I am not sure.

### PR DESCRIPTION
**Pull request by reaver585**
This new Gradle task does not have proper means for workspace discovery, so for now we optimistically setWorkspaceModule() for project dependencies.

- Fixes: #48159.

### CODE REVIEW

File: devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/QuarkusApplicationModelTask.java [hunk 1]
```diff
@@ -311,8 +315,15 @@ private static void collectDependencies(
...
-                    depBuilder.setFlags(DependencyFlags.RELOADABLE);
+                // Checking whether current dependency is a project module is a temporary workaround,
+                // that is required while projectModule for project dependencies is null (current
+                // deficiency of this task).
+                // That's why we set the workspace module flag explicitly via setWorkspaceModule().
+                // Once we have projectModule set for project dependencies, we can remove this workaround.
+                final boolean isProjectDependency = resolvedDependency.getSelected()
+                        .getId() instanceof ProjectComponentIdentifier;
+                if (projectModule != null || isProjectDependency) {
+                    depBuilder.setReloadable().setWorkspaceModule();
```
Comment (reaver585) [inline devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/QuarkusApplicationModelTask.java:326]: @aloubyansky please note that I added `.setWorkspaceModule()` here.

Comment (aloubyansky) [reply devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/QuarkusApplicationModelTask.java:326]: I think it shouldn't be necessary. But ok, I guess.

**Review by aloubyansky — APPROVED** [review]

File: devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/QuarkusApplicationModelTask.java (hunk 1 above)
Comment (reaver585) [reply devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/QuarkusApplicationModelTask.java:326]: I couldn't make it work without setting this flag - new test i added fails.
I think we need to set this flag, since it's not set elsewhere and without it, project dependency does not end up in the runtime classloader -> see [1](https://github.com/quarkusio/quarkus/blob/a1924dfebf2ebca2329f2e951e3bd6764454fa6f/independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/app/CuratedApplication.java#L436) -> [2](https://github.com/quarkusio/quarkus/blob/a1924dfebf2ebca2329f2e951e3bd6764454fa6f/independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/app/CuratedApplication.java#L394) -> [3](https://github.com/quarkusio/quarkus/blob/main/independent-projects/bootstrap/app-model/src/main/java/io/quarkus/maven/dependency/Dependency.java#L56)

**Comment by reaver585** [comment]
@aloubyansky I had to rebase the branch, could you please re-approve?

**Comment by aloubyansky** [comment]
Great work @reaver585 , thanks a lot!
