### PR TITLE
Explain semantics of quarkus.rest.path; add tests

### LINKED ISSUE #15458: Quarkus 1.12.1.Final doesnt honor the path declared in the javax.ws.rs.core.Application
**Describe the bug**
I chose to implement a javax.ws.rs.core.Application because of some OpenAPI values I would like define there (info, security and so on). I defined the base path of my application inside the javax.ws.rs.core.Application class, with the Path() annotation.  
Quarkus ignores the declared path. The resources still work with their declared path without the prefix path declared inside the javax.ws.rs.core.Application class.

Following an example:
*  javax.ws.rs.core.Application class with Path("/application")
*  resource with Path("/resource")

I can successfully call the rest resource with the path */resource*, but it doesnt work with the path */application/resource*.

**Expected behavior**
I should be able to successfully call the */application/resource* endpoint.

**Actual behavior**
I can successfully call the rest resource with the path */resource*, but **it doesnt work** with the path */application/resource*.

**To Reproduce**

Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific).  
https://github.com/dbl81/applicationpath.git

1.  clone the repo
2.  mvn compile quarkus:dev
3.  browse: http://localhost:8080/application/resource --> 404
4.  browse: http://localhost:8080/resource  --> 200 (plain text response "hello")

**Configuration**
```properties
```

**Screenshots**

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Windows 10 Home Edition
 - Output of `java -version`:
```
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)
```
 - Quarkus version or git rev: 1.12.1.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): mvn
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\Program Files\apache-maven-3.6.3
Java version: 11.0.7, vendor: AdoptOpenJDK, runtime: C:\Program Files\jdk-11.0.7.10-hotspot
Default locale: it_IT, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

**Additional context**

### PR DESCRIPTION
**Pull request by ebullient**
Since #15030, we now have a convention in our config that leading slashes in configured paths matter. 

Update doc for `quarkus.rest.path` to make clearer association with `@ApplicationPath` 

Add a few tests to make expected behavior more obvious (and ensure it keeps working that way)

### CODE REVIEW

File: extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/ResteasyReactiveServerConfig.java [hunk 1]
```diff
@@ -7,8 +7,11 @@
...
     /**
-     * Set this to override the default path for JAX-RS resources if there are no
-     * annotated application classes.
+     * Set this to define the application path that serves as the base URI for all
+     * JAX-RS resource URIs provided by Path annotations when there are no
+     * {@code @ApplicationPath} annotation defined on {@code Application} classes.
+     * <p>
+     * This value is always resolved relative to {@code quarkus.http.root-path}.
      */
     @ConfigItem(defaultValue = "/")
```
Comment (kenfinnigan) [inline extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/ResteasyReactiveServerConfig.java:16]: Is it confusing that we're saying it's a relative path and then the default is an absolute?

Comment (ebullient) [reply extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/ResteasyReactiveServerConfig.java:16]: This is a substitute for `@ApplicationPath` .. it is JAX-RS. It will ALWAYS be interpreted relative to http.root-path. Always

Comment (ebullient) [reply extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/ResteasyReactiveServerConfig.java:16]: I'm trying to make that unambiguous .. by reference more JAX-RS things in JAX-RS-y language.

Comment (ebullient) [reply extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/ResteasyReactiveServerConfig.java:16]: @stuartwdouglas .. we could remove the default or leave it empty or.. ?

File: extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/ResteasyReactiveServerConfig.java [hunk 2]
```diff
@@ -7,9 +7,12 @@
...
-     * annotated application classes.
+     * Set this to define the application path that serves as the base URI for all
+     * JAX-RS resource URIs provided by {@code @Path} annotations when there are no
+     * {@code @ApplicationPath} annotations defined on {@code Application} classes.
+     * <p>
+     * This value is always resolved relative to {@code quarkus.http.root-path}.
      */
-    @ConfigItem(defaultValue = "/")
+    @ConfigItem(defaultValue = "")
     String path;
```
Comment (stuartwdouglas) [inline extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/ResteasyReactiveServerConfig.java:17]: This needs to be Optional<String> if you have an empty default

**Review by stuartwdouglas — CHANGES_REQUESTED** [review]

File: extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/ResteasyReactiveServerConfig.java (hunk 2 above)
Comment (ebullient) [reply extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/ResteasyReactiveServerConfig.java]: yes. just fixed

**Review by stuartwdouglas — APPROVED** [review]

**Review by kenfinnigan — APPROVED** [review]
