### PR TITLE
Avoid XStream causing illegal access issues for internal JDK collections

### LINKED ISSUE #24492: Quarkus testing with `@ParameterizedTest` broken with Java 17 + 18 (xstream)
### Describe the bug

The following exception happens during tests using `@QuarkusTest` with Java 17 + 18.

The failing test case is a `@ParameterizedTest` with a `@MethodSource` that returns a `Stream` of objects that contain `List` instances created by `Arrays.asList()` - hence the `java.util.Collections$UnmodifiableCollection`.

Looks like it's not a direct fault of Quarkus, but xsteam not able to deal with those objects.

Adding `--add-opens=java.base/java.util=ALL-UNNAMED` does not help.

```
com.thoughtworks.xstream.converters.ConversionException: 
No converter available
---- Debugging information ----
message             : No converter available
type                : java.util.Collections$UnmodifiableRandomAccessList
converter           : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
message[1]          : Unable to make field private static final long java.util.Collections$UnmodifiableCollection.serialVersionUID accessible: module java.base does not "opens java.util" to unnamed module @7f1dd5e7
-------------------------------
	at com.thoughtworks.xstream.core.DefaultConverterLookup.lookupConverterForType(DefaultConverterLookup.java:88)
	at com.thoughtworks.xstream.XStream$1.lookupConverterForType(XStream.java:478)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:49)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:83)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshallField(AbstractReflectionConverter.java:270)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.writeField(AbstractReflectionConverter.java:174)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doMarshal(AbstractReflectionConverter.java:262)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshal(AbstractReflectionConverter.java:90)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:59)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:83)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshallField(AbstractReflectionConverter.java:270)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.writeField(AbstractReflectionConverter.java:174)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doMarshal(AbstractReflectionConverter.java:262)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshal(AbstractReflectionConverter.java:90)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:59)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:83)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshallField(AbstractReflectionConverter.java:270)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.writeField(AbstractReflectionConverter.java:174)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doMarshal(AbstractReflectionConverter.java:262)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshal(AbstractReflectionConverter.java:90)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:59)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:44)
	at com.thoughtworks.xstream.core.TreeMarshaller.start(TreeMarshaller.java:83)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.marshal(AbstractTreeMarshallingStrategy.java:37)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1266)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1255)
	at com.thoughtworks.xstream.XStream.toXML(XStream.java:1228)
	at com.thoughtworks.xstream.XStream.toXML(XStream.java:1215)
	at io.quarkus.test.junit.internal.XStreamDeepClone.doClone(XStreamDeepClone.java:49)
	at io.quarkus.test.junit.internal.XStreamDeepClone.clone(XStreamDeepClone.java:35)
	at io.quarkus.test.junit.internal.SerializationWithXStreamFallbackDeepClone.clone(SerializationWithXStreamFallbackDeepClone.java:33)
	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:981)
	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:896)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestTemplateMethod(QuarkusTestExtension.java:856)
```

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

17.0.2
18

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.7.5.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
Fixes #24492

### CODE REVIEW

File: test-framework/junit5/src/main/java/io/quarkus/test/junit/internal/CustomListConverter.java [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+ */
+public class CustomListConverter extends CollectionConverter {
+
+    public CustomListConverter(Mapper mapper) {
+        super(mapper);
+    }
+
+    @Override
+    public boolean canConvert(Class type) {
+        return List.class.isAssignableFrom(type);
```
Comment (geoand) [inline test-framework/junit5/src/main/java/io/quarkus/test/junit/internal/CustomListConverter.java:25]: We might need to be more strict here

File: test-framework/junit5/src/main/java/io/quarkus/test/junit/internal/CustomSetConverter.java [hunk 2]
```diff
@@ -0,0 +1,32 @@
...
+ */
+public class CustomSetConverter extends CollectionConverter {
+
+    public CustomSetConverter(Mapper mapper) {
+        super(mapper);
+    }
+
+    @Override
+    public boolean canConvert(Class type) {
+        return Set.class.isAssignableFrom(type);
```
Comment (geoand) [inline test-framework/junit5/src/main/java/io/quarkus/test/junit/internal/CustomSetConverter.java:25]: Same

File: test-framework/junit5/src/main/java/io/quarkus/test/junit/internal/CustomListConverter.java (hunk 1 above)
Comment (gsmet) [reply test-framework/junit5/src/main/java/io/quarkus/test/junit/internal/CustomListConverter.java:25]: Yeah, if doable, I think we'd better list the problematic ones rather than be too broad.
That won't be perfect but less dangerous.

**Comment by geoand** [comment]
@snazy do you mind if I borrow your commit and only keep the tests?

**Comment by snazy** [comment]
> @snazy do you mind if I borrow your commit and only keep the tests?

Sure! Take that one :)

I suspect, this change also needs a custom converter for `Map`?

**Comment by geoand** [comment]
Done, PR updated

**Review by snazy — APPROVED** [review]

**Review by gsmet — APPROVED** [review]
Woot!
We might have to add more in the future but with the infrastructure in place, that will be easy!

**Comment by geoand** [comment]
Thanks again for the idea! It was marvelously simple and effective

**Comment by famod** [comment]
I also do think making it work in general is more important than retaining immutability.

**Comment by gsmet** [comment]
Yeah, I think we are fine losing immutability for that. That's why I suggested this approach.
Worst case, you can wrap these in a `Collections.toUnmodifiable...` if these are supported by XStream.
