### PR TITLE
Fixes request context lost in Infinispan cache get/getasync

### LINKED ISSUE #48196: Infinispan cache does not propagate request context
### Describe the bug

Using 

```java
@Path("/expensive-resource")
public class ExpensiveResource {

    public static final String EXPENSIVE_RESOURCE_CACHE_NAME = "expensiveResourceCache";

    private int invocations;

    @Inject
    ClientRequestService clientRequestService;

 @GET
    @Path("/{keyElement1}/{keyElement2}/{keyElement3}")
    @CacheResult(cacheName = EXPENSIVE_RESOURCE_CACHE_NAME, lockTimeout = 5000)
    public ExpensiveResponse getExpensiveResponse(@PathParam("keyElement1") @CacheKey String keyElement1,
            @PathParam("keyElement2") @CacheKey String keyElement2, @PathParam("keyElement3") @CacheKey String keyElement3,
            @QueryParam("foo") String foo) {
        invocations++;
        clientRequestService.setData("request data");
        ExpensiveResponse response = new ExpensiveResponse();
        response.setResult(keyElement1 + " " + keyElement2 + " " + keyElement3 + " too!");
        return response;
    }
```

where 

```java
@RequestScoped
public class ClientRequestService {
    String data;

    public String data() {
        return data;
    }

    public ClientRequestService setData(String data) {
        this.data = data;
        return this;
    }
}
```

```java

@Provider
public class ClientRequestFilter implements jakarta.ws.rs.client.ClientRequestFilter {

    ClientRequestService requestService;

    @Inject
    public ClientRequestFilter(ClientRequestService requestService) {
        this.requestService = requestService;
    }

    @Override
    public void filter(ClientRequestContext requestContext) {
        if (requestService != null) {
            requestContext.getHeaders().add("extra", requestService.data());
        }
    }
}
```

Leads to a context propagation exception

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by karesti**
- Fixes: #48196

### CODE REVIEW

File: extensions/infinispan-cache/runtime/src/main/java/io/quarkus/cache/infinispan/runtime/InfinispanCacheImpl.java [hunk 1]
```diff
@@ -111,18 +111,15 @@ public <K, V> Uni<V> get(K key, Function<K, V> valueLoader) {
...
     @Override
     public <K, V> Uni<V> getAsync(K key, Function<K, Uni<V>> valueLoader) {
         Context context = Vertx.currentContext();
-
-        return Uni.createFrom().completionStage(CompletionStages.handleAndCompose(remoteCache.getAsync(key), (v1, ex1) -> {
-            if (ex1 != null) {
-                return CompletableFuture.failedFuture(ex1);
-            }
-
+        CompletableFuture<V> infinispanGet = threadContext.withContextCapture(remoteCache.getAsync(key)).thenApplyAsync(v1 -> {
```
Comment (karesti) [inline extensions/infinispan-cache/runtime/src/main/java/io/quarkus/cache/infinispan/runtime/InfinispanCacheImpl.java]: @cescoffier @geoand I need some of your time to check of this is ok. I could reproduce the issue and the issue is not failing now, but I'm unsure about the fix and if something else could be missing here.

File: extensions/infinispan-cache/runtime/src/main/java/io/quarkus/cache/infinispan/runtime/InfinispanCacheImpl.java [hunk 2]
```diff
@@ -47,6 +50,8 @@ public InfinispanCacheImpl(InfinispanCacheInfo cacheInfo, RemoteCache remoteCach
         this.remoteCache = remoteCache;
         this.lifespan = cacheInfo.lifespan.map(l -> l.toMillis()).orElse(-1L);
         this.maxIdle = cacheInfo.maxIdle.map(m -> m.toMillis()).orElse(-1L);
+        this.threadContext = Arc.container().select(ThreadContext.class).get();
```
Comment (cescoffier) [inline extensions/infinispan-cache/runtime/src/main/java/io/quarkus/cache/infinispan/runtime/InfinispanCacheImpl.java]: Are we sure we always had in instance, even when context propagation is disabled?

File: extensions/infinispan-cache/runtime/src/main/java/io/quarkus/cache/infinispan/runtime/InfinispanCacheImpl.java [hunk 3]
```diff
@@ -47,6 +50,8 @@ public InfinispanCacheImpl(InfinispanCacheInfo cacheInfo, RemoteCache remoteCach
...
+        this.managedExecutor = Arc.container().select(ManagedExecutor.class).get();
```
Comment (cescoffier) [inline extensions/infinispan-cache/runtime/src/main/java/io/quarkus/cache/infinispan/runtime/InfinispanCacheImpl.java]: Same here, it seems to assume context propagation is present.

File: extensions/infinispan-cache/runtime/src/main/java/io/quarkus/cache/infinispan/runtime/InfinispanCacheImpl.java [hunk 4]
```diff
@@ -81,16 +86,11 @@ private <T> T decodeNull(Object value) {
 
     @Override
     public <K, V> Uni<V> get(K key, Function<K, V> valueLoader) {
-        return Uni.createFrom()
-                .completionStage(() -> CompletionStages.handleAndCompose(remoteCache.getAsync(key), (v1, ex1) -> {
-                    if (ex1 != null) {
-                        return CompletableFuture.failedFuture(ex1);
-                    }
-
+        CompletableFuture<V> infinispanGet = threadContext.withContextCapture(remoteCache.getAsync(key))
```
Comment (cescoffier) [inline extensions/infinispan-cache/runtime/src/main/java/io/quarkus/cache/infinispan/runtime/InfinispanCacheImpl.java]: We need a supplier, as that code should run when the uni is subscribed to.

So, a supplier of completion stage would be more correct.

File: extensions/infinispan-cache/runtime/src/main/java/io/quarkus/cache/infinispan/runtime/InfinispanCacheImpl.java [hunk 5]
```diff
@@ -111,18 +111,15 @@ public <K, V> Uni<V> get(K key, Function<K, V> valueLoader) {
                                 computationResults.remove(key);
                             });
                     return resultAsync;
-                }));
+                }, managedExecutor).thenCompose(f -> f);
```
Comment (cescoffier) [inline extensions/infinispan-cache/runtime/src/main/java/io/quarkus/cache/infinispan/runtime/InfinispanCacheImpl.java]: Why do we need the executor here?

**Review by cescoffier — CHANGES_REQUESTED** [review]

**Comment by geoand** [comment]
My high level question is why are things being done with Context Propagation instead of the way that `io.quarkus.cache.redis.runtime.RedisCacheImpl` does them?

**Comment by karesti** [comment]
@geoand when I looked at the code of redis, I was under the impression that is because the client is the quarkus vert.x client, everything was working "automatically" comparing to the infinispan client. My personal issue is that I lack a bit of deep underlying knowledge at this point

File: extensions/infinispan-cache/runtime/src/main/java/io/quarkus/cache/infinispan/runtime/InfinispanCacheImpl.java (hunk 5 above)
Comment (karesti) [reply extensions/infinispan-cache/runtime/src/main/java/io/quarkus/cache/infinispan/runtime/InfinispanCacheImpl.java]: I was assuming that we wanted completeasync, and I grabbed this from the quarkus docs concerning completion stage and context propagation

File: extensions/infinispan-cache/runtime/src/main/java/io/quarkus/cache/infinispan/runtime/InfinispanCacheImpl.java (hunk 3 above)
Comment (karesti) [reply extensions/infinispan-cache/runtime/src/main/java/io/quarkus/cache/infinispan/runtime/InfinispanCacheImpl.java]: I assumed it was always the case

**Comment by geoand** [comment]
Okay, I was hoping that the Infinispan client had a Vert.x version... I know we can't do that now, but at some point we really should look into that.

File: extensions/infinispan-cache/runtime/src/main/java/io/quarkus/cache/infinispan/runtime/InfinispanCacheImpl.java (hunk 3 above)
Comment (geoand) [reply extensions/infinispan-cache/runtime/src/main/java/io/quarkus/cache/infinispan/runtime/InfinispanCacheImpl.java]: We'll need to know what brings it in.

**Comment by karesti** [comment]
@cescoffier does this seem good ?

**Comment by cescoffier** [comment]
Should we use the duplicated context instead of context propagation? 
I'm not sure if it would fix the issue, but I think it's worth trying.

In this case, you would need to create an executor at the beginning of each method:

```java
var context = Vertx.currentContext();
var executor = r -> {
  if (context == null) r.run();
  else context.runOnContext(x -> r.run());
}
```

(Avoid the lambdas in the real code)

Then, before returning the Uni: 

```
.emitOn(executor);
```

File: extensions/infinispan-cache/runtime/src/main/java/io/quarkus/cache/infinispan/runtime/InfinispanCacheImpl.java [hunk 6]
```diff
@@ -81,78 +82,35 @@ private <T> T decodeNull(Object value) {
...
-                .completionStage(() -> CompletionStages.handleAndCompose(remoteCache.getAsync(key), (v1, ex1) -> {
-                    if (ex1 != null) {
-                        return CompletableFuture.failedFuture(ex1);
-                    }
-
-                    if (v1 != null) {
-                        return CompletableFuture.completedFuture(decodeNull(v1));
-                    }
+        return Uni.createFrom().completionStage(() -> {
+            ThreadContext threadContext = Arc.container().select(ThreadContext.class).get();
```
Comment (cescoffier) [inline extensions/infinispan-cache/runtime/src/main/java/io/quarkus/cache/infinispan/runtime/InfinispanCacheImpl.java]: I think this throw an exception is CP is not enabled.

**Review by cescoffier — CHANGES_REQUESTED** [review]

**Comment by karesti** [comment]
> Should we use the duplicated context instead of context propagation? I'm not sure if it would fix the issue, but I think it's worth trying.
> 
> In this case, you would need to create an executor at the beginning of each method:
> 
> ```java
> var context = Vertx.currentContext();
> var executor = r -> {
>   if (context == null) r.run();
>   else context.runOnContext(x -> r.run());
> }
> ```
> 
> (Avoid the lambdas in the real code)
> 
> Then, before returning the Uni:
> 
> ```
> .emitOn(executor);
> ```

I tested and runned into the Suppressed: jakarta.enterprise.context.ContextNotActiveException: RequestScoped context was not active when trying to obtain a bean instance for a client proxy of CLASS bean [class=[io.quarkus.it](http://io.quarkus.it/).cache.infinispan.ClientRequestService, id=VcMhAzqfwnRsjHRm80Y_wUxTmRc]
[1653](https://github.com/quarkusio/quarkus/actions/runs/15564661895/job/43826157423?pr=48200#step:19:1654)

**Comment by karesti** [comment]
@cescoffier thanks for all your insights and help, let me know now

File: extensions/infinispan-cache/runtime/src/main/java/io/quarkus/cache/infinispan/runtime/InfinispanCacheImpl.java [hunk 7]
```diff
@@ -81,78 +81,46 @@ private <T> T decodeNull(Object value) {
...
     public <K, V> Uni<V> get(K key, Function<K, V> valueLoader) {
-        return Uni.createFrom()
-                .completionStage(() -> CompletionStages.handleAndCompose(remoteCache.getAsync(key), (v1, ex1) -> {
-                    if (ex1 != null) {
-                        return CompletableFuture.failedFuture(ex1);
-                    }
+        Context context = Vertx.currentContext();
+        Executor executor = duplicateContextExecutor(context);
 
+        return Uni.createFrom().completionStage(() -> remoteCache.getAsync(key))
```
Comment (cescoffier) [inline extensions/infinispan-cache/runtime/src/main/java/io/quarkus/cache/infinispan/runtime/InfinispanCacheImpl.java]: Would be better to avoid the lambdas.

**Review by cescoffier — APPROVED** [review]
It would have been nice to replace the lambdas

**Comment by karesti** [comment]
@cescoffier I removed the lambdas

File: extensions/infinispan-cache/runtime/src/main/java/io/quarkus/cache/infinispan/runtime/InfinispanCacheImpl.java (hunk 7 above)
Comment (karesti) [reply extensions/infinispan-cache/runtime/src/main/java/io/quarkus/cache/infinispan/runtime/InfinispanCacheImpl.java]: done

**Comment by cescoffier** [comment]
Added the backport-3.20 label to investigate if it's possible or not.
(I know that 3.20 is frozen, so it will be in the next one)

CC @karesti
