### PR TITLE
Fix deployment problem lost while re-scanning in dev-mode

### LINKED ISSUE #50876: Dev-Mode - 404 instead of the Dev Error page (500) on deployment error
### Describe the bug

In Dev-Mode, Quarkus randomly shows 404 instead of the Error 500 page in case of deployment error.

### Expected behavior

Always show the 500 error

### Actual behavior

Randomly shows 404 when requesting in burst (already experienced in browser)
It seems to be when a request arrive while the previous one is processed
Also it seems to processing is very slow as it show the loader while it should be instant

### How to Reproduce?

https://github.com/ia3andy/reproducer-resource-not-found.git

Clone the repo
Start dev mode
Run GreetingResourceTest.testHelloEndpoint (it could fail after a few run)

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

3.29

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mathias82**
### Related Issue

Fixes: https://github.com/quarkusio/quarkus/issues/50876

## PR Summary

This PR fixes an inconsistency in Quarkus dev mode where HTTP requests made during a failed application deployment could return **404 Not Found** instead of the expected **500 Internal Server Error**. The behavior was caused by the absence of a proper catch-all error handler during failed dev-mode startup, allowing unmatched routes to fall through Vert.x default routing.

## Related Issue

Fixes: https://github.com/quarkusio/quarkus/issues/50876

## Reproduction Steps

1. Create a Quarkus app with a failing injection (e.g. unresolved @ConfigProperty Boolean).
2. Run:
3. Send concurrent requests:

4. Observe mixed **404** and **500** responses.

## Expected vs Actual

| Scenario | Expected | Actual before PR | Actual after PR |
|---------|---------|-----------------|----------------|
| Dev mode deployment fails | Always 500 | Sometimes 404 | Always 500 |
| Browser access | Dev UI error | Works | Works |

## Fix Explanation

A final fallback route is now registered after the hot replacement handler, ensuring all requests during failed startup return a deterministic **500**:

```java
router.route().last().handler(rc -> {
 rc.response()
   .setStatusCode(500)
   .putHeader("Content-Type", "text/plain")
   .end("Dev mode startup failed – Application deployment did not complete successfully.");
});

### CODE REVIEW

**Comment by mathias82** [comment]
@ia3andy i fixed it

**Comment by geoand** [comment]
Thanks for looking into it, but before merging any changes, I would really like to know where those intermittent 404 responses are coming from

**Comment by mathias82** [comment]
> Thanks for looking into it, but before merging any changes, I would really like to know where those intermittent 404 responses are coming from

The intermittent 404 responses were caused by a race condition during application startup in dev mode. When the application fails to deploy, the Hot Replacement handler is registered, but no terminal fallback route exists at that point. 

As a result, incoming HTTP requests that arrive before the handler completes its setup fall through Vert.x’s default routing pipeline, which returns 404 Not Found.

Example sequence

1. Application starts in dev mode
2. Deployment fails due to an injection error (e.g. unresolved @ConfigProperty Boolean foo)
3. Hot Replacement Handler begins initialization
4. A request arrives before the handler finishes
5. No route matches yet , Vert.x default handler returns 404

Once the handler completes, further requests are handled correctly, which is why the behavior appeared intermittent.

By adding a deterministic fallback route before any user-defined handlers, we eliminate this timing window and ensure a consistent 500 Internal Server Error whenever deployment fails. @geoand 

So the intermittent 404s were not user-defined routes failing, but Vert.x’s default "no route found" handler taking over before Quarkus error routing was ready.

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/VertxHttpRecorder.java [hunk 1]
```diff
@@ -300,6 +300,13 @@ public void configBuilder(final SmallRyeConfigBuilder builder) {
                 router.route().order(RouteConstants.ROUTE_ORDER_HOT_REPLACEMENT).blockingHandler(hotReplacementHandler);
             }
 
+            router.route().last().handler(rc -> rc.response()
+                    .setStatusCode(500)
+                    .putHeader("Content-Type", "text/plain")
+                    .end("Dev mode startup failed – Application deployment did not complete successfully."));
```
Comment (geoand) [inline extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/VertxHttpRecorder.java]: As this is for dev-mode, the route should only be registered in dev-mode

**Comment by geoand** [comment]
Thanks for the change!

Can you please squash the commits?

**Comment by mathias82** [comment]
> Thanks for the change!
> 
> Can you please squash the commits?

done

**Comment by ia3andy** [comment]
I am still getting 404 in my reproducer, there might be an underlying question, why are we recreating the router on each request when we know there is no code change?

**Comment by mathias82** [comment]
> I am still getting 404 in my reproducer, there might be an underlying question, why are we recreating the router on each request when we know there is no code change?

The router is recreated on each failed startup by design, because the dev-mode pipeline
initializes the Hot Replacement handler and routing structure from scratch every time
Quarkus attempts to redeploy the application.

Even if there is no code change, the deployment loop still triggers a new routing
initialization step so that DevMode can apply configuration changes, reload modified
artifacts, and ensure the handler chain remains consistent.

Before this PR, there was a timing window where requests could hit Vert.x default routing
before the Hot Replacement handler finished its setup, which resulted in intermittent 404s.
The fix closes that gap by adding a deterministic fallback route, so the behavior is now
consistent and always returns 500 on failed deployment.

So the router recreation is expected, the missing fallback was the root cause of the 404s.

If you'd like, I can open a follow-up issue to explore whether router recreation could be
optimized in DevMode, but it's unrelated to the 404 problem this PR resolves.

**Comment by mathias82** [comment]
@geoand  I’ve pushed an updated version of the fix.

What changed
------------

When dev mode startup fails and `startServerAfterFailedStart()` is invoked, we now register a catch-all route on the Vert.x `Router` that always returns `500` in development:

- The hot replacement handler is still registered with its existing order.
- In dev mode, we add `router.route().handler(...)` that unconditionally responds with `500` and a plain text error message.
- `rootHandler` remains the `Router` instance, and for remote dev the existing `RemoteSyncHandler` still wraps it as before.

This logic only runs in `startServerAfterFailedStart()`, so it does not affect successful application startup in prod.

How to reproduce and verify
---------------------------

1. Use the reproducer project and intentionally force a dev mode startup failure, e.g. by injecting an unresolved `@ConfigProperty Boolean foo` (as in the original report).
2. Start dev mode:

   ```bash
   mvn quarkus:dev

While Quarkus is failing to start, repeatedly call the endpoint from another terminal:

for i in {1..20}; do \
  curl -o /dev/null -s -w "%{http_code}\n" http://localhost:8080/hello; \
done

<img width="1243" height="495" alt="image" src="https://github.com/user-attachments/assets/d402e482-b1ce-40ae-8850-6b85295b60de" />


Before this change, responses were intermittently 404 because Vert.x fell back to the default no-route handler.
With this change applied, all responses are consistently 500 while dev startup is in a failed state.


@ia3andy Why the test still sees a 404 instead of 500

The test triggers a build-time failure before startServerAfterFailedStart() ever runs.
Because dependency resolution fails (UnsatisfiedResolutionException for @ConfigProperty Boolean foo), Quarkus aborts during augmentation before Vert.x starts and before the router is created.

At that point:

- No HTTP server is started
- No Router exists yet
- startServerAfterFailedStart() is not invoked
- Therefore our catch-all 500 route is never installed

Our fallback 500 handler is applied only after a failed runtime startup, not before the router is constructed. This explains why the fix works when a dev mode runtime failure occurs, but the synthetic test fails.

You can put delay in your test and it will pass

**Review by ia3andy — CHANGES_REQUESTED** [review]
This issue is not with the fallback handler but with the fact that the `VertxHttpHotReplacementSetup` is loosing the exception every 2000ms during the time of the scan, here is a proposed patch that gives a consistent result until the scan is over:

```diff
diff --git a/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/VertxHttpRecorder.java b/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/VertxHttpRecorder.java
index d9170026531..d97ae42cc7a 100644
--- a/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/VertxHttpRecorder.java
+++ b/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/VertxHttpRecorder.java
@@ -300,15 +300,6 @@ public void configBuilder(final SmallRyeConfigBuilder builder) {
                 router.route().order(RouteConstants.ROUTE_ORDER_HOT_REPLACEMENT).blockingHandler(hotReplacementHandler);
             }

-            if (LaunchMode.current() == LaunchMode.DEVELOPMENT) {
-                router.route().handler(rc -> rc.response()
-                        .setStatusCode(500)
-                        .putHeader("Content-Type", "text/plain")
-                        .end("Dev mode startup failed – Application deployment did not complete successfully."));
-            }
-
-            rootHandler = router;
-
             Handler<HttpServerRequest> root = router;
             LiveReloadConfig liveReloadConfig = config.getConfigMapping(LiveReloadConfig.class);
             if (liveReloadConfig.password().isPresent()
diff --git a/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/devmode/VertxHttpHotReplacementSetup.java b/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/devmode/VertxHttpHotReplacementSetup.java
index d2e2ca3d626..5a9320aff9b 100644
--- a/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/devmode/VertxHttpHotReplacementSetup.java
+++ b/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/devmode/VertxHttpHotReplacementSetup.java
@@ -32,6 +32,7 @@
 public class VertxHttpHotReplacementSetup implements HotReplacementSetup {

     private volatile long nextUpdate;
+    private volatile Throwable tempDeploymentProblem;
     private HotReplacementContext hotReplacementContext;

     private static final long HOT_REPLACEMENT_INTERVAL = 2000;
@@ -104,6 +105,10 @@ public void handle(AsyncResult<Void> event) {
                 }
             });
         }
+        if (tempDeploymentProblem != null) {
+            handleDeploymentProblem(routingContext, tempDeploymentProblem);
+            return;
+        }
         if (hotReplacementContext.getDeploymentProblem() != null && routingContext.request().path().endsWith(CONFIG_FIX)) {

             routingContext.request().setExpectMultipart(true);
@@ -160,9 +165,12 @@ public Boolean call() {
                             nextUpdate = System.currentTimeMillis() + HOT_REPLACEMENT_INTERVAL;
                             Object currentState = VertxHttpRecorder.getCurrentApplicationState();
                             try {
+                                tempDeploymentProblem = hotReplacementContext.getDeploymentProblem();
                                 restart = hotReplacementContext.doScan(true);
                             } catch (Exception e) {
                                 throw new IllegalStateException("Unable to perform live reload scanning", e);
+                            } finally {
+                                tempDeploymentProblem = null;
                             }
                             if (currentState != VertxHttpRecorder.getCurrentApplicationState()) {


```

I have tested it on a few cases but we need to see if there can't be edge case where doing this is an issue. Also I am not 100% sure of where I added temp handler, it was more to experiment a solution which seems better.

**Comment by mathias82** [comment]
> This issue is not with the fallback handler but with the fact that the `VertxHttpHotReplacementSetup` is loosing the exception every 2000ms during the time of the scan, here is a proposed patch that gives a consistent result until the scan is over:
> 
> ```diff
> diff --git a/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/VertxHttpRecorder.java b/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/VertxHttpRecorder.java
> index d9170026531..d97ae42cc7a 100644
> --- a/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/VertxHttpRecorder.java
> +++ b/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/VertxHttpRecorder.java
> @@ -300,15 +300,6 @@ public void configBuilder(final SmallRyeConfigBuilder builder) {
>                  router.route().order(RouteConstants.ROUTE_ORDER_HOT_REPLACEMENT).blockingHandler(hotReplacementHandler);
>              }
> 
> -            if (LaunchMode.current() == LaunchMode.DEVELOPMENT) {
> -                router.route().handler(rc -> rc.response()
> -                        .setStatusCode(500)
> -                        .putHeader("Content-Type", "text/plain")
> -                        .end("Dev mode startup failed – Application deployment did not complete successfully."));
> -            }
> -
> -            rootHandler = router;
> -
>              Handler<HttpServerRequest> root = router;
>              LiveReloadConfig liveReloadConfig = config.getConfigMapping(LiveReloadConfig.class);
>              if (liveReloadConfig.password().isPresent()
> diff --git a/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/devmode/VertxHttpHotReplacementSetup.java b/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/devmode/VertxHttpHotReplacementSetup.java
> index d2e2ca3d626..5a9320aff9b 100644
> --- a/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/devmode/VertxHttpHotReplacementSetup.java
> +++ b/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/devmode/VertxHttpHotReplacementSetup.java
> @@ -32,6 +32,7 @@
>  public class VertxHttpHotReplacementSetup implements HotReplacementSetup {
> 
>      private volatile long nextUpdate;
> +    private volatile Throwable tempDeploymentProblem;
>      private HotReplacementContext hotReplacementContext;
> 
>      private static final long HOT_REPLACEMENT_INTERVAL = 2000;
> @@ -104,6 +105,10 @@ public void handle(AsyncResult<Void> event) {
>                  }
>              });
>          }
> +        if (tempDeploymentProblem != null) {
> +            handleDeploymentProblem(routingContext, tempDeploymentProblem);
> +            return;
> +        }
>          if (hotReplacementContext.getDeploymentProblem() != null && routingContext.request().path().endsWith(CONFIG_FIX)) {
> 
>              routingContext.request().setExpectMultipart(true);
> @@ -160,9 +165,12 @@ public Boolean call() {
>                              nextUpdate = System.currentTimeMillis() + HOT_REPLACEMENT_INTERVAL;
>                              Object currentState = VertxHttpRecorder.getCurrentApplicationState();
>                              try {
> +                                tempDeploymentProblem = hotReplacementContext.getDeploymentProblem();
>                                  restart = hotReplacementContext.doScan(true);
>                              } catch (Exception e) {
>                                  throw new IllegalStateException("Unable to perform live reload scanning", e);
> +                            } finally {
> +                                tempDeploymentProblem = null;
>                              }
>                              if (currentState != VertxHttpRecorder.getCurrentApplicationState()) {
> ```
> 
> I have tested it on a few cases but we need to see if there can't be edge case where doing this is an issue. Also I am not 100% sure of where I added temp handler, it was more to experiment a solution which seems better.

@ia3andy Thanks a lot for digging into this. Your insight about hotReplacementContext.getDeploymentProblem() temporarily becoming null during the scan window was something I would never have been able to infer from the code path alone. It explains perfectly why the fallback behaved inconsistently, even though the router logic was correct.

The tempDeploymentProblem snapshot approach makes total sense now that I understand the race condition inside the scan cycle. I was focusing on the HTTP layer determinism and didn't expect the problem reference itself to disappear mid-scan,that detail was definitely not obvious externally.

Great catch, and thanks again for identifying the underlying cause. With your patch, the behavior becomes consistent for the user without reopening the concurrency hole.

**Review by geoand — APPROVED** [review]

**Review by ia3andy — APPROVED** [review]
Thanks @mathias82
