### PR TITLE
Fix consistency of SmallRye Health config roots

### LINKED ISSUE #42382: Fix SmallRye Health config: two different roots
Parts of the config is under `quarkus.smallrye-health` and the other part is under `quarkus.health`.

This needs fixing (in a backward compatible way).

https://quarkus.io/version/main/guides/smallrye-health

### PR DESCRIPTION
**Pull request by gsmet**
Some properties were under the `quarkus.health` prefix and some under the `quarkus.smallrye-health` prefix.
I unified everything under `quarkus.smallrye-health` and kept the old properties for backward compatibility (except for the just introduced `enabled`).

Fixes #42382

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]

File: extensions/smallrye-health/deployment/src/test/java/io/quarkus/smallrye/health/test/DeprecatedHealthOpenAPITest.java [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+import org.hamcrest.Matchers;
+import org.jboss.shrinkwrap.api.asset.EmptyAsset;
+import org.jboss.shrinkwrap.api.asset.StringAsset;
+import org.junit.jupiter.api.Test;
+import org.junit.jupiter.api.extension.RegisterExtension;
+
+import io.quarkus.test.QuarkusUnitTest;
+import io.restassured.RestAssured;
+
+@Deprecated(since = "3.14", forRemoval = true)
```
Comment (xstefank) [inline extensions/smallrye-health/deployment/src/test/java/io/quarkus/smallrye/health/test/DeprecatedHealthOpenAPITest.java:12]: Well, the test can stay right, we just need to update the config? This test needs to be updated nevertheless. Just mentioning it so it's not removed.

**Comment by xstefank** [comment]
Otherwise approved. Sorry, you move too fast for my flow coding time off emails :)

File: extensions/smallrye-health/deployment/src/test/java/io/quarkus/smallrye/health/test/DeprecatedHealthOpenAPITest.java (hunk 1 above)
Comment (gsmet) [reply extensions/smallrye-health/deployment/src/test/java/io/quarkus/smallrye/health/test/DeprecatedHealthOpenAPITest.java:12]: No, the test will get dropped. I added another test with the updated config (but GitHub shows it to you the other way around).

Comment (xstefank) [reply extensions/smallrye-health/deployment/src/test/java/io/quarkus/smallrye/health/test/DeprecatedHealthOpenAPITest.java:12]: I see now.
