### PR TITLE
WebSockets Next: cancel returned Multi if the connection is closed

### LINKED ISSUE #41025: WebSocket Next Server-Side Streaming cancelation
### Describe the bug

If a server-side streaming connection is closed by the client, the subscription of Multi<T> should also be cancelled.

```java
@WebSocket(path = "/v1/products")
@RequestScoped
public class ProductSocket {

    @OnOpen
    public Multi<Product> onOpen() {
        return Multi.createFrom()
                .ticks()
                .every(Duration.ofSeconds(2))
                .map(aLong -> new Product(String.valueOf(aLong)));
    }
}
```

### Expected behavior

The returned `Multi<Product>` should be cancelled if the client closes the WebSocket connection.

### Actual behavior

The `Mutli<Product>` subscription stays active and produces following exceptions every tick:

```
2024-06-06 13:20:07,851 ERROR [io.qua.web.nex.run.WebSocketEndpointBase] (executor-thread-1) Unable to send text message from Multi: WebSocket connection [id=13bedb47-618f-4631-9a5a-164807c53572, path=/v1/products]: io.vertx.core.impl.NoStackTraceThrowable: WebSocket is closed
```

### How to Reproduce?

Created a reproducer: https://github.com/andlinger/quarkus-reproducer/tree/quarkus-41025

### PR DESCRIPTION
**Pull request by mkouba**
- fixes #41025

### CODE REVIEW

**Comment by mkouba** [comment]
@andlinger this should fix the problem :-)

**Review by geoand — APPROVED** [review]

File: extensions/websockets-next/runtime/src/main/java/io/quarkus/websockets/next/runtime/WebSocketEndpointBase.java [hunk 1]
```diff
@@ -319,41 +319,31 @@ public Uni<Void> sendText(String message, boolean broadcast) {
...
-                                    .subscribe()
-                                    .with(v -> LOG.debugf("Multi >> text message: %s", connection),
-                                            t -> LOG.errorf(t, "Unable to send text message from Multi: %s", connection));
-                        },
-                        t -> {
-                            LOG.errorf(t, "Unable to send text message from Multi: %s ", connection);
-                        });
+                        m -> LOG.debugf("Multi >> text message: %s", connection),
+                        t -> LOG.errorf(t, "Unable to send text message from Multi: %s ", connection));
         return Uni.createFrom().voidItem();
```
Comment (cescoffier) [inline extensions/websockets-next/runtime/src/main/java/io/quarkus/websockets/next/runtime/WebSocketEndpointBase.java:332]: Why are we returning Unis in these cases?

**Review by cescoffier — CHANGES_REQUESTED** [review]

File: extensions/websockets-next/runtime/src/main/java/io/quarkus/websockets/next/runtime/WebSocketEndpointBase.java (hunk 1 above)
Comment (mkouba) [reply extensions/websockets-next/runtime/src/main/java/io/quarkus/websockets/next/runtime/WebSocketEndpointBase.java:332]: Good question. It's for the sake of consitent API. We use this method inside the generated `WebSocketEndpointBase.doOnOpen()` method which is then used in `WebSocketEndpointBase.execute()` etc.

Once we have everything in a "good shape" we can think of some refactoring... esp. in the context of #39148.

**Review by cescoffier — APPROVED** [review]
