### PR TITLE
MongoDB Panache:  Update field access with appropriate get/set methods

### LINKED ISSUE #12514: IllegalAccessError with Panache MongoDB
**Describe the bug**
Given the following Entity class:

```java
package org.acme.db;

import io.quarkus.mongodb.panache.PanacheMongoEntity;

public class TestEntity extends PanacheMongoEntity {
  public String name;
}
```

When I use it in the following Resource:

```java
package org.acme;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import org.acme.db.TestEntity;

@Path("/hello")
public class ExampleResource {

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        TestEntity entity = new TestEntity();
        entity.name = "a";
        entity.persist();

        return "hello";
    }
}

```

I get the following error:

```
2020-10-05 11:37:48,098 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /hello failed,
error id: ba6ed126-bc40-491a-a01a-3e4b1fece1eb-1: org.jboss.resteasy.spi.UnhandledException:
java.lang.IllegalAccessError: class org.acme.ExampleResource tried to access protected field org.acme.db.Entity.name
(org.acme.ExampleResource and org.acme.db.Entity are in unnamed module of loader
io.quarkus.bootstrap.classloading.QuarkusClassLoader @6b975803)
```

Please note that `TestEntity` and `ExampleResource` are in different java packages.

**Expected behavior**
I can interact with the public fields of the entity from any other class. This is also what the panache documentation claims:
> Use public fields. Get rid of dumb getter and setters. Under the hood, we will generate all getters and setters that are missing, and rewrite every access to these fields to use the accessor methods. This way you can still write useful accessors when you need them, which will be used even though your entity users still use field accesses.
> — https://quarkus.io/guides/mongodb-panache#how-and-why-we-simplify-mongodb-api

**Actual behavior**
It crashes with an `IllegalAccessError` because the fields are now protected and the accessors from the other class don't seem to be rewritten. This behavior started with the 1.8.0.CR1 update and was caused by https://github.com/quarkusio/quarkus/commit/62505279fb59ce9f28db8abf7b81e9a1ae721fe0, though the root cause seems to be the not-executed rewriting of the accessors.

**To Reproduce**

1. Create a new project with the `quarkus-mongodb-panache` extension ([code.quarkus.io](https://code.quarkus.io/?g=org.acme&a=code-with-quarkus&v=1.0.0-SNAPSHOT&b=MAVEN&c=org.acme.ExampleResource&s=XZs&cn=code.quarkus.io))
2. Add a new entity and try to access a public field from a class in a different package.
3. Execute it / Run the tests.

Reproducable project: [code-with-quarkus-illegalaccess.zip](https://github.com/quarkusio/quarkus/files/5326655/code-with-quarkus-illegalaccess.zip). Just execute the tests.

**Environment (please complete the following information):**
 - Quarkus version or git rev: 1.8.1

### PR DESCRIPTION
**Pull request by evanchooly**
Scan the other classes in the jar to find and replace field access with get/set methods

fixes #12514

### CODE REVIEW

**Review by loicmathieu — APPROVED** [review]
LGTM

File: integration-tests/hibernate-orm-panache/src/main/java/io/quarkus/it/panache/resources/BookResource.java [hunk 1]
```diff
@@ -19,6 +22,11 @@
     @Path("/{name}/{author}")
     public List<Book> addAndListAll(@PathParam("name") String name, @PathParam("author") String author) {
         bookDao.persist(new Book(name, author));
-        return bookDao.listAll();
+        List<Book> books = bookDao.listAll();
+        // This is done to invoke the hopefully replaced field access with the getter access
+        books.forEach(book -> {
+            book.name.hashCode();
```
Comment (FroMage) [inline integration-tests/hibernate-orm-panache/src/main/java/io/quarkus/it/panache/resources/BookResource.java:28]: I don't understand how this tests for using the getters?

In ORM+Panache we have a lots of tests for that, which involve calling real getters and making sure they were called. Why don't you copy that?

File: extensions/panache/mongodb-panache-common/deployment/src/main/java/io/quarkus/mongodb/panache/deployment/BasePanacheMongoResourceProcessor.java [hunk 2]
```diff
@@ -87,7 +94,8 @@ public void buildReactive(CombinedIndexBuildItem index,
         List<PanacheMethodCustomizer> methodCustomizers = methodCustomizersBuildItems.stream()
                 .map(bi -> bi.getMethodCustomizer()).collect(Collectors.toList());
 
-        processTypes(index, transformers, reflectiveClass, propertyMappingClass, getReactiveTypeBundle(),
+        processTypes(index, transformers, reflectiveClass, propertyMappingClass,
```
Comment (FroMage) [inline extensions/panache/mongodb-panache-common/deployment/src/main/java/io/quarkus/mongodb/panache/deployment/BasePanacheMongoResourceProcessor.java:97]: I don't understand how come we're getting formatting here, isn't that auto-formatted?

**Review by FroMage — CHANGES_REQUESTED** [review]
LGTM except for testing.

File: integration-tests/hibernate-orm-panache/src/main/java/io/quarkus/it/panache/resources/BookResource.java (hunk 1 above)
Comment (evanchooly) [reply integration-tests/hibernate-orm-panache/src/main/java/io/quarkus/it/panache/resources/BookResource.java:28]: because this call (`getField`) replaced by `invokeVirtual` which is a public method where the field is private and so avoids the `IllegalAccessException`.

File: extensions/panache/mongodb-panache-common/deployment/src/main/java/io/quarkus/mongodb/panache/deployment/BasePanacheMongoResourceProcessor.java (hunk 2 above)
Comment (evanchooly) [reply extensions/panache/mongodb-panache-common/deployment/src/main/java/io/quarkus/mongodb/panache/deployment/BasePanacheMongoResourceProcessor.java:97]: it is.  there used to be an extra parameter there before I realized it wasn't necessary which probably cause the wrap there.

Comment (FroMage) [reply extensions/panache/mongodb-panache-common/deployment/src/main/java/io/quarkus/mongodb/panache/deployment/BasePanacheMongoResourceProcessor.java:97]: It's still weird, I thought formatting was deterministic. But whatever.

File: integration-tests/hibernate-orm-panache/src/main/java/io/quarkus/it/panache/resources/BookResource.java (hunk 1 above)
Comment (FroMage) [reply integration-tests/hibernate-orm-panache/src/main/java/io/quarkus/it/panache/resources/BookResource.java:28]: I'm sorry this doesn't parse.

**Review by FroMage — DISMISSED** [review]

File: integration-tests/hibernate-orm-panache/src/main/java/io/quarkus/it/panache/resources/BookResource.java (hunk 1 above)
Comment (evanchooly) [reply integration-tests/hibernate-orm-panache/src/main/java/io/quarkus/it/panache/resources/BookResource.java:28]: No worries.  I found the accessor tests on the hibernate side and I'm recreating them for mongodb.  this will all go away then.

File: extensions/panache/mongodb-panache-common/deployment/src/main/java/io/quarkus/mongodb/panache/deployment/BasePanacheMongoResourceProcessor.java (hunk 2 above)
Comment (evanchooly) [reply extensions/panache/mongodb-panache-common/deployment/src/main/java/io/quarkus/mongodb/panache/deployment/BasePanacheMongoResourceProcessor.java:97]: I had edited the source and added a parameter causing the new wrap.  then removed it when it turned up unnecessary (the mongodb case is simpler than hibernate's).  But i'll clean that up so the diff is smaller.

**Comment by evanchooly** [comment]
@FroMage do you want to look over the tests or shall I merge?

**Review by FroMage — APPROVED** [review]
LGTM but you have a CI failure
