### PR TITLE
Properly use headers set in Vert.x from RESTEasy Reactive

### LINKED ISSUE #25283: Combining @RouterFilter and JAX-RS ContainerResponseFilter does not work in reactive RESTEasy
### Describe the bug

Consider the following code running with _quarkus-resteasy-reactive_:

```java
@Produces(MediaType.TEXT_PLAIN)
@Path("/")
public class IncompleteVaryHeader {
    public static class VaryOriginFilter {
        @RouteFilter
        void checkForCSRF(final RoutingContext rc) {
            rc.response().headers().add("Vary", "Origin");
            rc.next();
        }
    }
    
    @Provider
    public static class NoCacheControlFilter implements ContainerResponseFilter {
        @Override
        public void filter(final ContainerRequestContext requestContext, final ContainerResponseContext responseContext)
            throws IOException {
            responseContext.getHeaders().add(HttpHeaders.VARY, "Prefer");
        }
    }

    @GET
    @Path("incomplete-vary-header")
    public Response doSometing() {
        return Response.ok("Test").type(MediaType.TEXT_PLAIN).build();
    }
}
```
There are two filter, a `@RouteFilter` and a JAX-RS `ContainerResponseFilter` which both add a `Vary` header. In classic RESTEasy both values - _Origin_ and _Prefer_ are in the response headers. In reactive RESTEasy the _Origin_ value is missing. The same code works as expected with classic RESTEasy.

### Expected behavior

The `Vary` response header should contain both _Origin_ and _Prefer_.

### Actual behavior

Only _Prefer_ is returned.

### How to Reproduce?

Run `VaryHeaderTest` from https://github.com/sithmein/bugs-in-quarkus.

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

17

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.8.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
Essentially this change makes sure RESTEasy Reactive does not
override the values of the headers that were set from
Vert.x Web Routes that ran before RESTEasy Reactive

Fixes: #25283

### CODE REVIEW

**Comment by geoand** [comment]
Can I get a review of this please?

Thanks

File: independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/ServerSerialisers.java [hunk 1]
```diff
@@ -502,4 +519,15 @@ public static void encodeResponseHeaders(ResteasyReactiveRequestContext requestC
...
+    private static boolean useSet(String header) {
+        if (!header.startsWith(CONTENT)) {
+            return false;
+        }
+        if (header.length() < CONTENT.length() + 2) {
+            return false;
+        }
+        String substring = header.substring(CONTENT.length() + 1);
+        return substring.equals(TYPE) || substring.equals(LENGTH);
+    }
```
Comment (gsmet) [inline independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/ServerSerialisers.java:531]: Just a preference but this seems very complicated, where:
```java
private static boolean useSet(String header) {
    return header.startsWith(CONTENT_TYPE) || header.startsWith(CONTENT_LENGTH);
}
```
would have done it.

Also you sure the header will have this exact case? Are they not partly out of our control? Given headers are case insensitive, I think it's safer to do the following as you never know:
```java
private static boolean useSet(String header) {
    String lowercaseHeader = header.toLowerCase(Locale.ROOT);
    return lowercaseHeader.startsWith(CONTENT_TYPE_LOWERCASE) || lowercaseHeader.startsWith(CONTENT_LENGTH_LOWERCASE);
}
```
where the constants are lowercase versions of the header.

**Review by gsmet — COMMENTED** [review]
I added a comment. Maybe it's just garbage though :).

File: independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/ServerSerialisers.java (hunk 1 above)
Comment (geoand) [reply independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/ServerSerialisers.java:531]: > would have done it.

It would, but I wanted to make it as fast as possible.

Comment (geoand) [reply independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/ServerSerialisers.java:531]: > Also you sure the header will have this exact case?

I'll do another check, but I am pretty sure that at this point, the case doesn't matter.

Comment (geoand) [reply independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/ServerSerialisers.java]: PR updated

**Comment by geoand** [comment]
@FroMage @stuartwdouglas can I get a review of this please?

Thanks

File: independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/ServerSerialisers.java [hunk 2]
```diff
@@ -502,4 +523,15 @@ public static void encodeResponseHeaders(ResteasyReactiveRequestContext requestC
         }
     }
 
+    private static boolean useSet(String header) {
```
Comment (gastaldi) [inline independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/ServerSerialisers.java:526]: This method looks too complex and confusing to me. Maybe rename it to something like: `requireSingleHeader`?

What about an `equalsIgnoreCase` for `Content-Type` and `Content-Length`?

**Review by gastaldi — COMMENTED** [review]
Added a comment. I admit I had to read it a couple of times until I finally figured out what the change is supposed to do :)

File: independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/ServerSerialisers.java (hunk 2 above)
Comment (geoand) [reply independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/ServerSerialisers.java:526]: Since this will be called for every request, and because `Content-` is common, I wanted to make this as light as possible

Comment (geoand) [reply independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/ServerSerialisers.java]: I renamed the method according to your suggestion

**Review by gastaldi — APPROVED** [review]

File: independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/ServerSerialisers.java [hunk 3]
```diff
@@ -502,4 +523,15 @@ public static void encodeResponseHeaders(ResteasyReactiveRequestContext requestC
...
+    private static boolean requireSingleHeader(String header) {
+        if (!(header.startsWith(CONTENT) || header.startsWith(CONTENT_LOWER))) {
+            return false;
+        }
+        if (header.length() < CONTENT.length() + 2) {
+            return false;
+        }
+        String substring = header.substring(CONTENT.length() + 1).toLowerCase(Locale.ROOT);
+        return substring.equals(TYPE_LOWER) || substring.equals(LENGTH_LOWER);
+    }
```
Comment (gastaldi) [inline independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/ServerSerialisers.java:535]: Not required to merge this PR, but this creates less Strings and performs less comparisons: 

```suggestion
    private static boolean requireSingleHeader(String header) {
        int contentLength = CONTENT.length();
        // Check if starts with "Content"
        if (!header.regionMatches(true, 0, CONTENT, 0, contentLength)) {
            return false;            
        }
        // Check if it ends with "Type" or "Length"
        return header.regionMatches(true, contentLength + 2, TYPE, 0, TYPE.length())
                || header.regionMatches(true, contentLength + 2, LENGTH, 0, LENGTH.length());
    }
```

Comment (gastaldi) [reply independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/ServerSerialisers.java:535]: And yet it can be slower when measured, nvm
