### PR TITLE
Fix log capturing for instances of Logger in QuarkusMainTests

### LINKED ISSUE #22302: QuarkusMainTest intercepts spurious strings
### Describe the bug

The `QuarkusMainTest`s are spuriously intercepting output coming from different sources.

### Expected behavior

The `QuarkusMainTest`s report back only the output from the specific launched `Process`.

### Actual behavior

_No response_

### How to Reproduce?

I started reducing the error down to a test in this codebase.

In `io.quarkus.it.picocli.PicocliTest` add the following test:

```java
    @Test
    public void testLogCapturing(QuarkusMainLauncher launcher) {
        org.jboss.logging.Logger.getLogger("test").error("error");
        LaunchResult result = launcher.launch("with-method-sub-command", "hello", "-n", "World!");
        assertThat(result.exitCode()).isZero();
        assertThat(result.getOutput()).isEqualTo("Hello World!");
    }
```

and the test will fail with an error similar to:

```bash
[ERROR] Failures: 
[ERROR]   PicocliTest.testLogCapturing:43 
expected: "Hello World!"
 but was: "2021-12-16 19:28:23,647 ERROR [test] (main) error
Hello World!"
[INFO] 
[ERROR] Tests run: 11, Failures: 1, Errors: 0, Skipped: 0
```

The expectation is that the test should pass.

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

`main`

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by andreaTP**
This is a problem that we found still present after the previous fix #22302 .

I can confirm that, with this fix we can remove the last workaround around the log capturing mechanism here (tested locally):
https://github.com/keycloak/keycloak/pull/9282/files#diff-aa081e5f62b9bbde53e18c058aae57608573561e504dedd279b1737badba3f64R77

cc. @pedroigor

### CODE REVIEW

**Comment by geoand** [comment]
This needs a formatting fix. `mvn install` should do the trick

**Comment by gsmet** [comment]
Fixed and force pushed.

BTW, the fastest way to format things is to use: `mvn -T C1 process-sources`

**Review by geoand — APPROVED** [review]
Seems pretty hacky, but I guess we can live with it..

**Comment by andreaTP** [comment]
Thanks for fixing the formatting for me @gsmet !

@geoand I agree it's pretty hacky, but the problem boils down to static initializations done:
 - [here in Quarkus](https://github.com/quarkusio/quarkus/blob/03d3f461e2c951f584d024dad941d27e304a14dd/core/devmode-spi/src/main/java/io/quarkus/dev/console/QuarkusConsole.java#L53-L54)
 - [here in Jboss Logging](https://github.com/jboss-logging/jboss-logmanager/blob/3e6eeb8bf4083ee3144e2d874579d10d193b5069/core/src/main/java/org/jboss/logmanager/handlers/ConsoleHandler.java#L37-L38)

I have attempted and failed alternative approaches and I'm completely open to proposals!

File: test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusMainTestExtension.java [hunk 1]
```diff
@@ -130,6 +129,35 @@ public void afterEach(ExtensionContext context) throws Exception {
         result = null;
     }
 
+    private static void setFinalStatic(Class clazz, Field field, Object newValue) throws Exception {
+        // WORKAROUND to prevent:
+        // "An illegal reflective access operation has occurred" warning to be shown
+        // this hack adds: --add-opens
+        // from: https://stackoverflow.com/questions/46454995/how-to-hide-warning-illegal-reflective-access-in-java-9-without-jvm-argument#comment110253314_46458447
+        clazz.getModule().addOpens(clazz.getPackageName(), QuarkusMainTestExtension.class.getModule());
```
Comment (stuartwdouglas) [inline test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusMainTestExtension.java:137]: This seems to be causing test failures.

Comment (andreaTP) [reply test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusMainTestExtension.java]: I discovered that this approach unfortunately doesn't work with Java >= 12.

Attempted with a different approach here: https://github.com/quarkusio/quarkus/pull/22455/commits/3168b210ffc9407ff32caa32498a2fd79f7ce318

please have a second review @stuartwdouglas since here we are "reversing" the logging handlers injected by Quarkus itself.

Comment (andreaTP) [reply test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusMainTestExtension.java]: cc. @geoand since your approval is based on a different implementation.

**Comment by geoand** [comment]
Can you squash the commits please?

**Comment by andreaTP** [comment]
@geoand sure, done!

**Comment by geoand** [comment]
Looks fine to me, but I'll let @stuartwdouglas give the final OK, since he is the author of this

**Comment by geoand** [comment]
Can you please resolve the conflict? Then I think we can merge this

**Comment by andreaTP** [comment]
Sure @geoand 👍  , rebased.
