### PR TITLE
Remove warning on no endpoint specified, as UDPSender is now working

### LINKED ISSUE #484: Jaeger: Fix core dump when using UdpSender (reproduce by not including the `JAEGER_ENDPOINT` system property)
To reproduce:
* Clone and build the protean repo master branch
* Clone the [quickstarts repo](https://github.com/jbossas/protean-quickstarts) and change to the `getting-started-native` folder
* Change the `shamrock.version` to `1.0.0.Alpha1-SNAPSHOT`
* Add the opentracing dependency:
```
        <dependency>
            <groupId>org.jboss.shamrock</groupId>
            <artifactId>shamrock-opentracing-deployment</artifactId>
            <scope>provided</scope>
            <version>${shamrock.version}</version>
        </dependency>
```
* Perform a native build, using `mvn package -Pnative`
* Run the native executable:
```
target/shamrock-quickstart-runner -DJAEGER_SERVICE_NAME=myservice -DJAEGER_SAMPLER_TYPE=const -DJAEGER_SAMPLER_PARAM=1
```
* Send a request to the app:
```
curl http://localhost:8080/app/hello
```

You should now see output similar to:
```
[ [ SubstrateSegfaultHandler caught signal 11 ] ]

General Purpose Register Set Values: 

  RAX 0000000000000001
  RBX 00007f9ec8111e10
  RCX 0000000000000000
  RDX 000000000000001c
  RBP 00007f9eb4bebda0
  RSI 00007f9eb4bebda8
  RDI 0000000000000000
  RSP 00007f9eb4bebdb8
  R8  0000000000000000
  R9  00007f9ec764a170
  R10 00007f9ec8111e10
  R11 0000000000000000
  R12 0000000000000012
  R13 0000000000000000
  R14 0000000000000031
  R15 00007f9e98000b20
  EFL 0000000000010206
  RIP 0000000000749d56
  

JavaFrameAnchor dump:

  No anchors
  
TopFrame info:

  Lookup TotalFrameSize in CodeInfoTable:
  SourceTotalFrameSize 144
  
VMThreads info:

  VMThread 00007f9e98000b20  STATUS_IN_JAVA (safepoints disabled)  java.lang.Thread@0x7f9ec4f02dc8
  VMThread 00007f9e94000b20  STATUS_IN_NATIVE  org.xnio.nio.WorkerThread@0x7f9ec73389f8
  VMThread 00007f9ea0000b20  STATUS_IN_NATIVE  org.xnio.nio.WorkerThread@0x7f9ec7336fd0
  VMThread 00007f9ea8000b20  STATUS_IN_NATIVE  org.xnio.nio.WorkerThread@0x7f9ec7333890
  VMThread 00007f9e9c000b20  STATUS_IN_NATIVE  org.xnio.nio.WorkerThread@0x7f9ec7335430
  VMThread 00007f9ea4000b20  STATUS_IN_NATIVE  org.xnio.nio.WorkerThread@0x7f9ec7331cf0
  VMThread 00007f9eac000b20  STATUS_IN_NATIVE  org.xnio.nio.WorkerThread@0x7f9ec7330150
  VMThread 00007f9eb0000b20  STATUS_IN_NATIVE  org.xnio.nio.WorkerThread@0x7f9ec732e5b0
  VMThread 00007f9ebc000b20  STATUS_IN_NATIVE  org.xnio.nio.WorkerThread@0x7f9ec732ca10
  VMThread 00007f9eb8000b20  STATUS_IN_NATIVE  org.xnio.nio.WorkerThread@0x7f9ec732ae70
  VMThread 00007f9ec0000b20  STATUS_IN_NATIVE  java.lang.Thread@0x7f9ec73022e8
  VMThread 0000000001a3e260  STATUS_IN_NATIVE  java.lang.Thread@0x17a7cb8
  
VM Thread State for current thread 00007f9e98000b20:

  0 (32 bytes): com.oracle.svm.core.genscavenge.ThreadLocalAllocation.pinnedTLAB = (bytes) 
    00007f9e98000b20: 0000000000000000 0000000000000000
    00007f9e98000b30: 0000000000000000 0000000000000000
    
  
  32 (32 bytes): com.oracle.svm.core.genscavenge.ThreadLocalAllocation.regularTLAB = (bytes) 
    00007f9e98000b40: 00007f9eb4200000 00007f9eb4300000
    00007f9e98000b50: 00007f9eb421a390 0000000000000000
    
  
  64 (8 bytes): com.oracle.svm.core.genscavenge.PinnedAllocatorImpl.openPinnedAllocator = (Object) null
  72 (8 bytes): com.oracle.svm.core.heap.NoAllocationVerifier.openVerifiers = (Object) null
  80 (8 bytes): com.oracle.svm.core.jdk.IdentityHashCodeSupport.hashCodeGeneratorTL = (Object) java.util.SplittableRandom  00007f9eb42013f0
  88 (8 bytes): com.oracle.svm.core.snippets.SnippetRuntime.currentException = (Object) null
  96 (8 bytes): com.oracle.svm.core.thread.JavaThreads.currentThread = (Object) java.lang.Thread  00007f9ec4f02dc8
  104 (8 bytes): com.oracle.svm.core.thread.ThreadingSupportImpl.activeTimer = (Object) null
  112 (8 bytes): com.oracle.svm.core.genscavenge.ThreadLocalAllocation.freeList = (Word) 0  0000000000000000
  120 (8 bytes): com.oracle.svm.core.stack.JavaFrameAnchors.lastAnchor = (Word) 0  0000000000000000
  128 (8 bytes): com.oracle.svm.core.thread.VMThreads.IsolateTL = (Word) 94598687557484880  0150150150150150
  136 (8 bytes): com.oracle.svm.core.thread.VMThreads.OSThreadIdTL = (Word) 140319613966080  00007f9eb4bed700
  144 (8 bytes): com.oracle.svm.core.thread.VMThreads.nextTL = (Word) 140319064591136  00007f9e94000b20
  152 (4 bytes): com.oracle.svm.core.thread.Safepoint.safepointRequested = (int) -18738  ffffb6ce
  156 (4 bytes): com.oracle.svm.core.thread.Safepoint.safepointRequestedValueBeforeSafepoint = (int) 0  00000000
  160 (4 bytes): com.oracle.svm.core.thread.ThreadingSupportImpl.currentPauseDepth = (int) 0  00000000
  164 (4 bytes): com.oracle.svm.core.thread.VMOperationControl.isLockOwner = (int) 0  00000000
  168 (4 bytes): com.oracle.svm.core.thread.VMThreads$StatusSupport.safepointsDisabledTL = (int) 1  00000001
  172 (4 bytes): com.oracle.svm.core.thread.VMThreads$StatusSupport.statusTL = (int) 1  00000001
  
VMOperation dump:

  No VMOperation in progress
  
Dump Counters:

  
Raw Stacktrace:

  00007f9eb4bebdb8: 0100007fffff0000 00007f9e00000000
  00007f9eb4bebdc8: 000000000074336b 00007f9eb421a0c8
  00007f9eb4bebdd8: 00000000b421a0a8 00007f9eb421a1e0
  00007f9eb4bebde8: 0000000000731fa1 00001aaf013582d0
  00007f9eb4bebdf8: 00007f9ec733af88 00007f9eb421a188
  00007f9eb4bebe08: 0000000000730f2f 00007f9ec733af88
  00007f9eb4bebe18: 0000000000000000 00000000013582d0
  00007f9eb4bebe28: 00007f9eb421a280 00007f9eb421a188
  00007f9eb4bebe38: 00000000004ebd87 00007f9eb421a028
  00007f9eb4bebe48: 00007f9eb421a280 00007f9eb421a188
  00007f9eb4bebe58: 00000000013582d0 00001aafb420a180
  00007f9eb4bebe68: 00000000004f160d 00000000012d8bd0
  00007f9eb4bebe78: c84d0050006cf6bc 00001aaf00000000
  00007f9eb4bebe88: 00000000013582d0 00007f9eb420a180
  00007f9eb4bebe98: 00000000004f0c8d 00007f9eb420a060
  00007f9eb4bebea8: 00000000012d8cc0 00007f9eb4208de8
  00007f9eb4bebeb8: 00000000004d9834 00000000017ae0b8
  00007f9eb4bebec8: 00000000006e3333 00007f9eb420a180
  00007f9eb4bebed8: 00007f9eb4209e30 00000000004d9e70
  00007f9eb4bebee8: 00007f9eb42081c0 00007f9eb420a170
  00007f9eb4bebef8: 00000000004cac51 00000000012d8cc0
  00007f9eb4bebf08: 00007f9eb4209d20 00007f9eb42090f0
  00007f9eb4bebf18: 00007f9eb420a060 00007f9eb42081c0
  00007f9eb4bebf28: 00007f9eb4208df8 00007f9eb4208208
  00007f9eb4bebf38: 00000000004cd069 00007f9eb4208dc0
  00007f9eb4bebf48: 000000000044296d 00007f9eb4208cf0
  00007f9eb4bebf58: 00000000004cc5d1 00007f9eb4208df8
  00007f9eb4bebf68: 00007f9eb4208208 00007f9eb4208d50
  00007f9eb4bebf78: 00000000004cce7e 00007f9ec7301670
  00007f9eb4bebf88: 00000000004cc1e9 000000000000002e
  00007f9eb4bebf98: 0000000000000000 00007f9eb4208d50
  00007f9eb4bebfa8: 0000000000bbd379 00000000013171a0
  00007f9eb4bebfb8: 00007f9eb4207a38 00007f9eb4207608
  00007f9eb4bebfc8: 00000000009552cb 00007f9eb42075c8
  00007f9eb4bebfd8: 00000000012dded8 00000000017a6e90
  00007f9eb4bebfe8: 00007f9eb42075e8 0000000000dba0b0
  00007f9eb4bebff8: 0000000000000000 00000000017b8d30
  00007f9eb4bec008: 0000000000bbd432 00007f9eb42075e8
  00007f9eb4bec018: 00007f9eb42075c8 00007f9ec7321e58
  00007f9eb4bec028: 0000000000bbd246 0000000fb4206588
  00007f9eb4bec038: 000000000132e938 00000000012dded8
  00007f9eb4bec048: 00007f9eb4207a38 00007f9ec7321e58
  00007f9eb4bec058: 00000000004feb92 0000000f008a85e0
  00007f9eb4bec068: 0000000000e1b6c0 00007f9eb4207588
  00007f9eb4bec078: 00000000013523c8 00000001b4204930
  00007f9eb4bec088: 00007f9eb4207508 00007f9eb42075a0
  00007f9eb4bec098: 00007f9eb4207a38 0000000000dba0c0
  00007f9eb4bec0a8: 00000000c4f02dc8 00000000012de4c0
  00007f9eb4bec0b8: 00007f9eb4207508 0000000001822360
  00007f9eb4bec0c8: 0000000000b387be 00000000013b3358
  00007f9eb4bec0d8: 00007f9eb4204930 000000000134c938
  00007f9eb4bec0e8: 0000000000af801c 00011337013b5468
  00007f9eb4bec0f8: 0000000001822360 00000001b42072f8
  00007f9eb4bec108: 000000000134c938 00007f9eb4207508
  00007f9eb4bec118: 0000000000aef573 0000000001822210
  00007f9eb4bec128: 0000000000aeeba0 00007f9eb4207508
  00007f9eb4bec138: 0000000000b7567e 0000000001822340
  00007f9eb4bec148: 00007f9eb42071c0 00007f9eb4204690
  00007f9eb4bec158: 00007f9eb4204788 0000000001822190
  00007f9eb4bec168: 0000000000aef258 00000000018257b8
  00007f9eb4bec178: 0000000000b6f407 00007f9eb4206de0
  00007f9eb4bec188: 0000000000bbb8c3 00007f9eb4202460
  00007f9eb4bec198: 00007f9eb42071c0 00007f9eb4204690
  00007f9eb4bec1a8: 00007f9eb4204788 0000000001822190
  
Stacktrace Stage0:

  RSP 00007f9eb4bebdb8 RIP 0000000000749d56 FrameSize 144
  VMError.shouldNotReachHere: Stack walk must walk only frames of known code
  Error: printDiagnostics already in progress.
  Trace/breakpoint trap (core dumped)
```

### PR DESCRIPTION
**Pull request by objectiser**
On retesting the UDPSender issue, with the latest version of graalvm (1.0.0-rc16), it appears the core dump no longer occurs.

To avoid the core dump using the default UDPSender, a warning message was output to direct the user to specific a HTTP endpoint, and therefore use the HTTPSender. This PR removes that warning message.

Resolves #484

### CODE REVIEW

**Review by gsmet — APPROVED** [review]
@objectiser thanks for testing this again. Always good to see an old issue fixed.

Let's wait for CI.

File: extensions/jaeger/runtime/src/main/java/io/quarkus/jaeger/runtime/JaegerDeploymentTemplate.java [hunk 1]
```diff
@@ -50,15 +49,9 @@ public void registerTracer(JaegerConfig jaeger) {
     private boolean isValidConfig(JaegerConfig jaeger) {
         Config mpconfig = ConfigProvider.getConfig();
         Optional<String> serviceName = mpconfig.getOptionalValue(JAEGER_SERVICE_NAME, String.class);
```
Comment (gsmet) [inline extensions/jaeger/runtime/src/main/java/io/quarkus/jaeger/runtime/JaegerDeploymentTemplate.java]: It's not related to this issue but why do you do that and get the MP config explicitly? Isn't the Quarkus config sufficient? Or you want to support the default configuration with MP Config too?

Comment (objectiser) [reply extensions/jaeger/runtime/src/main/java/io/quarkus/jaeger/runtime/JaegerDeploymentTemplate.java]: Yeah want to support the default configuration approach aswell.
