### PR TITLE
RESTEasy Reactive - fix exception mapping for security exceptions when proactive security is disabled

### LINKED ISSUE #26922: smallrye jwt returns Response despite exception being caught
### Describe the bug

I have a simple quarkus reactive resteasy server

```java
@Path("/")
@ApplicationScoped
public class Hello {

    @GET
    @Path("hello")
    @RolesAllowed({"roleYouNeed"})
    @Blocking
    public Uni<Response> hello(){
        return Uni.createFrom().item(Response.ok("hello").build());
    }
}
        
```

Following the documentation found here I create several exception mappers to return a response body which elaborates on the status code. This one for example works when you do not provide a JWT token to a request that needs it:

```java
@Provider//register as JAXRS provider
@Priority(1)//override the build-int mapper(which has 5001 prio)
@Slf4j
public class UnauthorizedExceptionMapper implements ExceptionMapper<UnauthorizedException> {
    @Override
    public Response toResponse(UnauthorizedException exception) {
        log.warn("There was an incoming request that did not have the correct Authorization");
        return Response.status(Response.Status.UNAUTHORIZED)
                .entity(new ErrorResponseObject().addErrorsItem(new ErrorResponseObjectErrorsInner()
                        .code(String.valueOf(Response.Status.UNAUTHORIZED.getStatusCode()))
                        .detail("Unauthorized")))
                .build();
    }

}
```

This works as expected on my endpoint that uses quarkus-smallrye-jwt with the annotation `@RolesAllowed({"roleYouNeed"})`

When someone sends a token that is truly worthless however a JWTParse Exception occurs and a different exception is raised, the `AuthenticationFailedException`

To catch this one I created 

```java
@Provider
@Priority(1)
@Slf4j
public class AuthenticationExceptionMapper implements ExceptionMapper<AuthenticationFailedException> {
    @Override
    public Response toResponse(AuthenticationFailedException exception) {
        log.warn("There was an incoming request that did not have the correct Authorization");
        return Response.status(Response.Status.UNAUTHORIZED)
                .entity(new ErrorResponseObject().addErrorsItem(new ErrorResponseObjectErrorsInner()
                        .code(String.valueOf(Response.Status.UNAUTHORIZED.getStatusCode()))
                        .detail("Unauthorized")))
                .build();
    }
}
```

This does catch the exception and my warning is logged: `[com.ene.odp.exc.AuthenticationExceptionMapper] (vert.x-eventloop-thread-0) There was an incoming request that did not have the correct Authorization
`. The problem here is that a response has already been returned and I see the following error occurring:

```
2022-07-25 16:22:03,812 ERROR [org.jbo.res.rea.com.cor.AbstractResteasyReactiveContext] (vert.x-eventloop-thread-1) Request failed: java.io.IOException: java.io.IOException: Failed to write
        at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveOutputStream.close(ResteasyReactiveOutputStream.java:272)
        at io.quarkus.resteasy.reactive.jackson.runtime.serialisers.BasicServerJacksonMessageBodyWriter.writeResponse(BasicServerJacksonMessageBodyWriter.java:44)
        at org.jboss.resteasy.reactive.server.core.ServerSerialisers.invokeWriter(ServerSerialisers.java:207)
        at org.jboss.resteasy.reactive.server.core.serialization.DynamicEntityWriter.write(DynamicEntityWriter.java:104)
        at org.jboss.resteasy.reactive.server.handlers.ResponseWriterHandler.handle(ResponseWriterHandler.java:31)
        at org.jboss.resteasy.reactive.server.handlers.ResponseWriterHandler.handle(ResponseWriterHandler.java:15)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:141)
        at org.jboss.resteasy.reactive.server.vertx.VertxResteasyReactiveRequestContext$1$1.handle(VertxResteasyReactiveRequestContext.java:73)
        at org.jboss.resteasy.reactive.server.vertx.VertxResteasyReactiveRequestContext$1$1.handle(VertxResteasyReactiveRequestContext.java:70)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
        at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.IOException: Failed to write
        at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveOutputStream.write(ResteasyReactiveOutputStream.java:109)
        at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveOutputStream.writeBlocking(ResteasyReactiveOutputStream.java:224)
        at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveOutputStream.close(ResteasyReactiveOutputStream.java:270)
        ... 18 more
Caused by: java.lang.IllegalStateException: Response has already been written
        at io.vertx.core.http.impl.Http1xServerResponse.checkValid(Http1xServerResponse.java:675)
        at io.vertx.core.http.impl.Http1xServerResponse.writeQueueFull(Http1xServerResponse.java:274)
        at io.quarkus.vertx.http.runtime.filters.AbstractResponseWrapper.writeQueueFull(AbstractResponseWrapper.java:486)
        at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveOutputStream.awaitWriteable(ResteasyReactiveOutputStream.java:116)
        at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveOutputStream.write(ResteasyReactiveOutputStream.java:82)
```

Why is the response already being returned while I catch this exception? How can I make sure nothing is returned except what I return from the `AuthenticationExceptionMapper`?

### Expected behavior

When I catch the exception in my AuthenticationExceptionMapper no response is returned except one that I return from the mapper. 

### Actual behavior

The smallrye-jwt extension returns a 401 before I can return an adequate response from my exception mapper

### How to Reproduce?

Create a simple server with an endpoint that uses the smallrye-jwt extension. Create an extension mapper that catches the AuthenticationFailedException and then call the endpoint with some gibberish Authorization: Bearer <Token>. 

### Output of `uname -a` or `ver`

21.0.1 Darwin Kernel Version 21.0.1: Tue Sep 14 20:56:24 PDT 2021; root:xnu-8019.30.61~4/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

OpenJDK 64-Bit Server VM GraalVM CE 22.1.0 (build 17.0.3+7-jvmci-22.1-b06, mixed mode, sharing)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.9.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

apache-maven-3.8.4

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by michalvavrik**
fixes: #26922

Currently the default auth failure handler sends response after it has sent challenge. However RESTEasy Reactive abort handlers still process the exception, pass it to exception mappers and tries to end event with response, which leads to an exception and impossibility to customize response. I've removed default auth failure handler when proactive security is disabled as RR already handles `AuthenticationFailedException`, `AuthenticationCompletionException`, `AuthenticationRedirectException` with built in mappers. This will give user an option to catch exception with custom ex. mapper and make reactive and classic extensions behave same.

### CODE REVIEW

**Comment by michalvavrik** [comment]
@stuartwdouglas I realize changes goes against your design, could you kindly have a look, please?

fyi @sberyozkin this is also POC for #5751

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpSecurityRecorder.java [hunk 1]
```diff
@@ -73,17 +78,28 @@ public void handle(RoutingContext event) {
                 //if proactive auth is used this is the only one
                 //if using lazy auth this can be modified downstream, to control authentication behaviour
                 event.put(QuarkusHttpUser.AUTH_FAILURE_HANDLER, new BiConsumer<RoutingContext, Throwable>() {
```
Comment (stuartwdouglas) [inline extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpSecurityRecorder.java:80]: Why can't RR just set it's own `AUTH_FAILURE_HANDLER`? This use case appears to be what it was designed for?

**Review by stuartwdouglas — CHANGES_REQUESTED** [review]

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpSecurityRecorder.java (hunk 1 above)
Comment (michalvavrik) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpSecurityRecorder.java:80]: Originally I did that, but sometimes response didn't end. This way, we are sure RR context is running so that exception is handled by them. I think I remember which tests where failing if that's important for you.

Comment (michalvavrik) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpSecurityRecorder.java:80]: I think `io.quarkus.jwt.test.RolesAllowedPostTest#postTextInvalidToken` and `io.quarkus.jwt.test.RolesAllowedPostTest#postTextWrongRole`. This way just feels safer.

Comment (michalvavrik) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpSecurityRecorder.java:80]: @stuartwdouglas Isn't there going to be a lot of duplication logic etc.? Only difference is what happens when we want to end it. But I think I could use inheritance so that only difference between the handlers is going to be how it ends. Good idea, I'll try it tomorrow.

Comment (michalvavrik) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpSecurityRecorder.java:80]: Thank you

Comment (stuartwdouglas) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpSecurityRecorder.java:80]: RESTEasy classic just removes it: https://github.com/stuartwdouglas/quarkus/blob/b76e53e23b60b48e9ca45ab6ea5e772e1186cc32/extensions/resteasy-classic/resteasy/runtime/src/main/java/io/quarkus/resteasy/runtime/standalone/VertxRequestHandler.java#L119

File: extensions/smallrye-jwt/deployment/pom.xml [hunk 2]
```diff
@@ -48,7 +48,7 @@
         </dependency>
         <dependency>
             <groupId>io.quarkus</groupId>
-            <artifactId>quarkus-resteasy-jsonb-deployment</artifactId>
+            <artifactId>quarkus-resteasy-reactive-jsonb-deployment</artifactId>
```
Comment (sberyozkin) [inline extensions/smallrye-jwt/deployment/pom.xml:51]: Not sure about this change - it is still expected to work with Resteasy Classic

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpSecurityRecorder.java (hunk 1 above)
Comment (michalvavrik) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpSecurityRecorder.java]: Sure, I checked and all the exceptions handled by the default auth failure handler are handled same by provided exception mappers. You were right, thanks!

File: extensions/smallrye-jwt/deployment/pom.xml (hunk 2 above)
Comment (michalvavrik) [reply extensions/smallrye-jwt/deployment/pom.xml:51]: Currently reactive stuff is not tested with `smallrye-jwt`, however classic is tested with `quarkus-integration-test-smallrye-jwt-token-propagation` and `quarkus-integration-test-smallrye-jwt-oidc-webapp`. I thought it's a good thing to know both reactive and classic work :-). I can change it if you like, but than I don't know where to put the test that actually verifies the issue.

**Comment by michalvavrik** [comment]
Apart of changes suggested by @stuartwdouglas I also added RESTEasy Reactive failure handler that covers `AuthenticationFailedException` failure when proactive auth is enabled and failure is before RR begin processing event. Thanks very much for review

File: extensions/smallrye-jwt/deployment/pom.xml (hunk 2 above)
Comment (sberyozkin) [reply extensions/smallrye-jwt/deployment/pom.xml:51]: @michalvavrik But does replacing a `jsonb` dependency forces the use of Resteasy Reactive in `quarkus-integration-test-smallrye-jwt-token-propagation` ?

Comment (michalvavrik) [reply extensions/smallrye-jwt/deployment/pom.xml:51]: @sberyozkin for `test` scope in `extension/smallrye-jwt` I replaced `quarkus-resteasy-jsonb-deployment` with `quarkus-resteasy-reactive-jsonb-deployment`, so should have no impact in integration modules as test dependencies are not transitive.

I'm not sure if there is not misunderstanding between us - I don't say certain module _must_ use RR, I just say there are 3 modules testing `smallrye-jwt` and if one of them had RR, I could add there a test and in general, I don't why should classic be preferred over reactive.

Comment (sberyozkin) [reply extensions/smallrye-jwt/deployment/pom.xml:51]: @michalvavrik Oh sorry, I missed it was a test scope.

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpSecurityRecorder.java [hunk 3]
```diff
@@ -69,44 +63,11 @@ public void handle(RoutingContext event) {
...
-                            event.response().headers().set(HttpHeaders.LOCATION, redirectEx.getRedirectUri());
-                            event.response().headers().set(HttpHeaders.CACHE_CONTROL, "no-store");
-                            event.response().headers().set("Pragma", "no-cache");
-                            event.response().end();
-                        } else {
-                            event.fail(throwable);
-                        }
-                    }
-                });
+                //register the default auth failure handler if no-one provided one up in the stream
```
Comment (sberyozkin) [inline extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpSecurityRecorder.java:66]: What I'm a bit concerned about here is that it is quite easy now for users to break things, for example, OIDC `AuthenticationFailedException`, if thrown by `quarkus-oidc` is better be handled by `quarkus-oidc` to prepare a correct challenge,  and if the user has registered a mapper then this mapper is in total control now. For ex, a few users combine Basic and OIDC code flow, so if the mapper will blindly return 401 then it is a problem.
I know, when it was not possible to customize with the proactive auth being on, it was a problem, and now that it is fixed, I'm looking for new problems :-).
I'm not sure, it feels like for some cases, we should just not allow intercepting it. If it is only 401 which is returned by default, then sure, why not let users customize it. If it is a redirect to Keycloak that has to be returned, then the custom mapper will not be able to form a redirect URL correctly - as the way it is done it depends on OIDC config, and other factors

Comment (michalvavrik) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpSecurityRecorder.java:66]: It makes sense, but then I think you'll have to accept that behavior will differ between enabled and disabled proactive security as you can't stop users from replacing `QuarkusHttpUser.AUTH_FAILURE_HANDLER` in the routing context. Doesn't it also means users are already (potentially) experiencing such problems if they are using disabled proactive sec.? IMHO such exceptions to behavior must be confusing for users (sometimes you can intercept ex. sometimes you can't..)

On level of `quarkus-vertx-http` we can't determine what is `quarkus-oidc` doing and such a feature as _you can only intercept exception if no-one has added headers_ or redirect didn't happen is not user friendly. BTW aren't they partially already able to adjust the behavior if they provide custom auth mechanism? I can drop a portion covering `proactive=true` if you like (as the issue reproducer had proactive disabled), but I can't define cases when we don't want to intercept ex. myself (at least not with required quality).

Comment (michalvavrik) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpSecurityRecorder.java:66]: btw even with custom mapping and `proactive=true`, they still can't hack (customize response) the redirect if the response has been sent, so that should be fine.

Comment (michalvavrik) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpSecurityRecorder.java:66]: but they can avoid sending a challenge, yeah, didn't think of that.

Comment (sberyozkin) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpSecurityRecorder.java:66]: Sure, but with custom HttpAuthenticationMechanism it is quite hard, and requires a real dedication if someone really wants to customize for ex the redirect.

>btw even with custom mapping and proactive=true, they still can't hack (customize response) the redirect if the response has been sent, so that should be fine.

Can you clarify please this point ?

Comment (michalvavrik) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpSecurityRecorder.java:66]: > I.e, if registering a custom Resteasy (Reactive) exception mapper can break the OIDC code flow then it is a flexibility which has become too flexible :-), users should be able to customize the response, ex, add some extra headers in case of redirects, if they want to, but if the clients access Quarkus which combines Basic and OIDC code flow, OIDC challenge is initiated, with `AuthenticatedFailedException` thrown and the user's mapper responds with 401 and the client instead of being redirected to Keycloak, then it will become a real problem, it is a user error, but the users should not be able just to get the whole mechanism down so easily, even unintentionally :-)
> 
> Not sure yet how to avoid, but it makes IMHO to think a bit more about it...

I agree, but than it's a breaking change that will reduce current behavior and should be same for proactive sec. disabled/enabled, but at least 2 extensions (undertow and resteasy classic) are not using the default auth failure handler at all (when disabled), so it will take a lot of changes.

Comment (michalvavrik) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpSecurityRecorder.java:66]: Please take your time.

Comment (sberyozkin) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpSecurityRecorder.java:66]: Thanks, let me think a bit more about it.
I think what might make sense is for the default auth handler to delegate to the custom one so that it can complete the challenge process if the custom one has not provided it (example, the custom exception mapper checks via RoutingContext if it is OIDC which initiated the challenge and if yes then it rethrows the exception ?)

Comment (stuartwdouglas) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpSecurityRecorder.java:66]: > I.e, if registering a custom Resteasy (Reactive) exception mapper can break the OIDC code flow then it is a flexibility which has become too flexible :-), 

No, this is just a simple case of letting the user handle an advanced use case how they will. If they deliberately try and override the security response and then OIDC no longer works that is on them. Users will always be able to break there app if they do the wrong thing, this is no different to any other feature.

File: extensions/resteasy-reactive/quarkus-resteasy-reactive/runtime/src/main/java/io/quarkus/resteasy/reactive/server/runtime/ResteasyReactiveRecorder.java [hunk 4]
```diff
@@ -271,4 +294,22 @@ public ServerSerialisers createServerSerialisers() {
         return new ServerSerialisers();
     }
 
+    public Consumer<Route> addAuthFailureHandler(RuntimeValue<RestInitialHandler> initialHandler, int order) {
```
Comment (stuartwdouglas) [inline extensions/resteasy-reactive/quarkus-resteasy-reactive/runtime/src/main/java/io/quarkus/resteasy/reactive/server/runtime/ResteasyReactiveRecorder.java:297]: What is this here for? Why is RR delegating to a vert.x failure route?

If we are going to do this IMHO there should be two options:

- Either a framework disables failure handling and takes over it themselves
- The framework leaves everything alone and the existing Quarkus handler takes care of it

E.g. with RESTEasy classic we have built in exception mappers, so when the user does not provide one these take over (which internally call the normal Quarkus auth methods to get the same behavior).

Any kind of hybrid approach IMHO has the potential to lead to confusion.

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/DefaultAuthFailureHandler.java [hunk 5]
```diff
@@ -0,0 +1,138 @@
...
+            // the response. This situation could happen if the default auth failure handler has been previously
+            // invoked without failing the event (via routingContext.get(AUTH_FAILURE_HANDLER) ...), therefore we skip
+            // the handling as despite its name, the default failure handler is invoked directly (not as event's failure
+            // handler) and calling next would skip actual failure handler.
+            return event.failure() instanceof AuthenticationFailedException
+                    && parseBoolean(event.get(AUTH_FAILED_EX_HANDLED));
+        }
+
+        @Override
+        protected void proceedAfterSendChallenge(AuthenticationFailedException authenticationFailedException,
```
Comment (stuartwdouglas) [inline extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/DefaultAuthFailureHandler.java:124]: I don't like the idea of this handler, after send challenge the request is done. If you want to customize it you need to contribute to the challenge sending process via an auth mechanism, or your need to completely take it over.

**Review by stuartwdouglas — DISMISSED** [review]

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/DefaultAuthFailureHandler.java (hunk 5 above)
Comment (michalvavrik) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/DefaultAuthFailureHandler.java:124]: If you are done after send challenge, it means it won't be possible to catch `AuthenticationFailedException` with failure handler in Reactive Routes. Isn't it reasonable to expect it can be caught? You are going to be able to do that in RESTEasy Reactive and Classic, why should Reactive Routes differ after all? Also I believe users are expecting to be able to customize the response https://github.com/quarkusio/quarkus/issues/5751#issuecomment-633749801

File: extensions/resteasy-reactive/quarkus-resteasy-reactive/runtime/src/main/java/io/quarkus/resteasy/reactive/server/runtime/ResteasyReactiveRecorder.java (hunk 4 above)
Comment (michalvavrik) [reply extensions/resteasy-reactive/quarkus-resteasy-reactive/runtime/src/main/java/io/quarkus/resteasy/reactive/server/runtime/ResteasyReactiveRecorder.java:297]: That's because when proactive security is enabled, RR didn't begin to process the event in the moment when the exception is thrown, thus it goes straight to the failure handler. I think RESTEasy Classic built in exception handlers are not able to catch these exception when proactive security is enabled as you only remove the default handler too late (https://github.com/stuartwdouglas/quarkus/blob/b76e53e23b60b48e9ca45ab6ea5e772e1186cc32/extensions/resteasy-classic/resteasy/runtime/src/main/java/io/quarkus/resteasy/runtime/standalone/VertxRequestHandler.java#L119, ATM it's not possible to do it sooner). This auth failure handler handles the exception over to the RR initial handler.

However we can work with "disabling" failure handling (handle this outside of the failure handlers).

File: extensions/reactive-routes/deployment/src/main/java/io/quarkus/vertx/web/deployment/ReactiveRoutesProcessor.java [hunk 6]
```diff
@@ -485,6 +485,12 @@ public boolean test(String name) {
                     priorityValue != null ? priorityValue.asInt() : RouteFilter.DEFAULT_PRIORITY));
         }
 
+        // user should be able to handle AuthenticationFailedException with a failure handler
+        // this filter adds the adjusted default handler to the event before authentication filter is run so that
+        // event is not ended in the default auth failure handler and other failure handlers are invoked
+        filterProducer.produce(
```
[the remark this answers is not in the document]
Comment (michalvavrik) [reply extensions/reactive-routes/deployment/src/main/java/io/quarkus/vertx/web/deployment/ReactiveRoutesProcessor.java:491]: Currently user-defined failure handlers won't be able to reach `AuthenticationFailedException` as:

1. Response ends in the default auth failure handler
2. Event has not failed at all, just the exception has been thrown and caught inside subscriber, existing default auth failure handler is not actually used as route failure handler (it's `BiConsumer`).

You can't register handler that calls `routingContext.fail()` as exception is caught and the default auth failure handler is invoked directly, there is no way for handler to intercept that.

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/DefaultAuthFailureHandler.java (hunk 5 above)
Comment (michalvavrik) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/DefaultAuthFailureHandler.java:124]: If Reactive Routes provided their own handler, it would probably make for cleaner solution than this `proceedAfterSendChallenge`.

File: extensions/resteasy-reactive/quarkus-resteasy-reactive/runtime/src/main/java/io/quarkus/resteasy/reactive/server/runtime/ResteasyReactiveRecorder.java (hunk 4 above)
Comment (stuartwdouglas) [reply extensions/resteasy-reactive/quarkus-resteasy-reactive/runtime/src/main/java/io/quarkus/resteasy/reactive/server/runtime/ResteasyReactiveRecorder.java:297]: Wait, so this is expected to work with non-proactive auth? I don't know if we actually want that, with proactive auth the expectation is that the request will never proceed past the security layer if auth is required. Letting it continue to be handled by the app would be a very big change of semantics.

IMHO proactive-auth=false should be a requirement to customize the response in framework code.

Comment (michalvavrik) [reply extensions/resteasy-reactive/quarkus-resteasy-reactive/runtime/src/main/java/io/quarkus/resteasy/reactive/server/runtime/ResteasyReactiveRecorder.java:297]: Yes, it's there just in order to make it work with `proactive=auth`.  I already wrote my opinion above, so if (@sberyozkin? please let me know) you both agree it's not desirable, I can simplify the PR heavily.

Comment (michalvavrik) [reply extensions/resteasy-reactive/quarkus-resteasy-reactive/runtime/src/main/java/io/quarkus/resteasy/reactive/server/runtime/ResteasyReactiveRecorder.java:297]: one else thing @sberyozkin - if it wasn't desirable to make this work for `quarkus.http.auth.proactive=true`, than I misunderstood this comment https://github.com/quarkusio/quarkus/issues/5751#issuecomment-1246913794

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpSecurityRecorder.java (hunk 3 above)
Comment (sberyozkin) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpSecurityRecorder.java:66]: @stuartwdouglas 

>If the user wants to handle this we should let them, and get out of their way, trying to 'helpfully' meddle in the process will just break things.

The realistic case I'm having in mind is this one: we have users combining `Basic` and `OIDC web-app`. If the user registers `AuthenticationFailedException` (to customize Basic response error) then two problems appear:
- The user has to figure out which mechanism has thrown the exception
- The user has no way not to pull out of creating OIDC redirect URL

The first one is actually resolvable because `RoutingContext` has an attribute set indicating which `HttpAuthenticationMechanism` initiated the challenge.
The second one is a real one though because it will be hard if not impossible to correctly calculate esp if PKCE is involved.

The same 2nd problem would exist for any combination of interactive and non-interactive mechanisms (basic + form, jwt+webauthn, etc) 

So my proposal is not about interfering into this process but letting users write the exception mappers which should return either null or rethrow the exception - indicating the mapping has not been done and for the default handler take over

File: extensions/resteasy-reactive/quarkus-resteasy-reactive/runtime/src/main/java/io/quarkus/resteasy/reactive/server/runtime/ResteasyReactiveRecorder.java (hunk 4 above)
Comment (sberyozkin) [reply extensions/resteasy-reactive/quarkus-resteasy-reactive/runtime/src/main/java/io/quarkus/resteasy/reactive/server/runtime/ResteasyReactiveRecorder.java:297]: Hi @stuartwdouglas, @michalvavrik 

>Stuart: Wait, so this is expected to work with non-proactive auth? I don't know if we actually want that, with proactive auth the expectation is that the request will never proceed past the security layer if auth is required. Letting it continue to be handled by the app would be a very big change of semantics. 

This is a good point I haven't thought about. However, are we talking only about the exception already thrown by the security layer going into the application exception chain trying to find its mapper ? This is probably OK. My understanding that the main difference between `proactive=true` and `proactive=false` is that in the former case the verification of the incoming credentials is always done - letting the security exception caught by application mappers does not seem to be a real problem...

However, @michalvavrik, I recall that for the `proactive=true` case, the option which was discussed at #5751, was to have `Vert.x` failure handlers involved, if they are registered then let them handle it, and if they don't then complete as usual.

Perhaps using the fault handlers for the proactive=true should be explored as well.

Comment (michalvavrik) [reply extensions/resteasy-reactive/quarkus-resteasy-reactive/runtime/src/main/java/io/quarkus/resteasy/reactive/server/runtime/ResteasyReactiveRecorder.java:297]: > However, @michalvavrik, I recall that for the `proactive=true` case, the option which was discussed at #5751, was to have `Vert.x` failure handlers involved, if they are registered then let them handle it, and if they don't then complete as usual.

That's exactly what I've done for Reactive Routes, please see https://github.com/quarkusio/quarkus/pull/28391/files/528a1b39d7f8df700caa003f41714cfaa5c8a790#diff-092deef4dddf1ef8bdd9c01923ae2537a68ad131cea60a8178949af0bc447f55

It can't be done per say for RESTEasy Reactive as there users doesn't register failure handlers but exception mappers. `addAuthFailureHandler`  I wanna add (see right above ^^^) catches such exception iff it's `AuthenticationFailedException` and begin processing reactive context with this throwable (so it goes straight away to its abort chain). If user defined their own custom mapper, then this one is used. If not, exception is caught by [AuthenticationFailedExceptionMapper](https://github.com/quarkusio/quarkus/blob/main/extensions/resteasy-reactive/quarkus-resteasy-reactive/runtime/src/main/java/io/quarkus/resteasy/reactive/server/runtime/exceptionmappers/AuthenticationFailedExceptionMapper.java) and [handled with authenticator](https://github.com/quarkusio/quarkus/blob/7d551fda0b38db8c33f953957567d0b40d43a4ff/extensions/resteasy-reactive/quarkus-resteasy-reactive/runtime/src/main/java/io/quarkus/resteasy/reactive/server/runtime/exceptionmappers/SecurityExceptionMapperUtil.java#L19). The last part is pity (I didn't mention before) as it calls for challenge again. I wonder if it makes sense for RR to use default failure handler at all as it already tries to handle these situations itself (and so does classic).

> Perhaps using the fault handlers for the proactive=true should be explored as well.

@sberyozkin I'm pretty far with using the fault handlers for the `proactive=true`, that's why I picked up this issue as proof of concept. Otherwise I'd already drop that portion (there is too much comments, we could have create a separate issue). I'll wait for response from @stuartwdouglas, but if we can't find agreement here, we could divide the PR to `proactive=true` and `proactive=false` (latter will be simplistic), but I won't be able to proceed with #5751 till it's discussed.

Comment (sberyozkin) [reply extensions/resteasy-reactive/quarkus-resteasy-reactive/runtime/src/main/java/io/quarkus/resteasy/reactive/server/runtime/ResteasyReactiveRecorder.java:297]: Hey @michalvavrik It might make sense to split it indeed, even into more than 2 PRs, as given the sensitivity of the changes it it is not easy to appreciate the consequences. 

I think using the fault handlers with `proactive=true` for all the cases should work, even for Resteasy Reactive, as even with  Resteasy Reactive, we will doc that in this case only using fault handlers will let you intercept the failures. In fact, I think using fault handlers is best when we 2 mechanisms like Basic and OIDC - because if the custom fault handler does not want to handle a given failure then it will just let it go further and then we don't have to complicate things and figuring out how to let Resteasy Reactive exception mappers choose not to map the exception in case of Basic and OIDC for ex.

So indeed, can you please consider for the `proactive=true` support the fault handlers for now only - it will still also let us do something along the lines of what you've done later anyway, but for now using the fault handlers will offer an option which can be used in the routes, Resteasy Reactive and Classic... IMHO it is a safe bet

**Comment by michalvavrik** [comment]
@stuartwdouglas @sberyozkin I changed PR title, description and reduced code (and scope). PR now fixes linked issue and allows exception mappers to catch security exceptions (these caught by the default auth failure handler) when proactive security is disabled.

I'm grateful for your reviews and I created separate issues for comments above: https://github.com/quarkusio/quarkus/issues/28489, https://github.com/quarkusio/quarkus/issues/28488.

**Comment by michalvavrik** [comment]
Went through failure, it's not related.

**Comment by sberyozkin** [comment]
@geoand Hey Georgios - can the TCK failure be related to the recent fix you did related to the cookie creation ?

**Review by sberyozkin — APPROVED** [review]
@michalvavrik Thanks, LGTM, lets see if Stuart will have something to add tomorrow, and can merge soon afterwards

**Comment by geoand** [comment]
Yes, it's already been fixed in main

**Comment by sberyozkin** [comment]
@geoand Cool, thanks
