### PR TITLE
Generate default constructor for RESTEasy classes if needed

### LINKED ISSUE #1314: Constructor injection does not work on RESTEasy component

### PR DESCRIPTION
**Pull request by geoand**
This allows users to use constructor injection in their RESTEasy resources.
For a complete background on why this is a proper solution, see:
https://issues.jboss.org/browse/RESTEASY-2183

Fixes: #1314

### CODE REVIEW

File: integration-tests/main/src/main/java/io/quarkus/example/rest/TestResourceWithConstructorInjection.java [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+
+import javax.ws.rs.GET;
+import javax.ws.rs.Path;
+
+@Path("/testCtor")
+public class TestResourceWithConstructorInjection {
+
+    final Someservice service;
+
+    public TestResourceWithConstructorInjection(Someservice service) {
```
Comment (gsmet) [inline integration-tests/main/src/main/java/io/quarkus/example/rest/TestResourceWithConstructorInjection.java]: @geoand could you add a test with a class having a default constructor and constructor injection too so that we can check it works OK?

Comment (geoand) [reply integration-tests/main/src/main/java/io/quarkus/example/rest/TestResourceWithConstructorInjection.java]: Of course, on it

Comment (geoand) [reply integration-tests/main/src/main/java/io/quarkus/example/rest/TestResourceWithConstructorInjection.java]: Fixed

File: extensions/resteasy/deployment/src/main/java/io/quarkus/resteasy/deployment/ResteasyScanningProcessor.java [hunk 2]
```diff
@@ -309,13 +316,18 @@ public void build(
...
+            Set<String> withoutDefaultCtor = new HashSet<>();
             for (AnnotationInstance annotation : paths) {
                 if (annotation.target().kind() == AnnotationTarget.Kind.CLASS) {
                     ClassInfo clazz = annotation.target().asClass();
                     if (!Modifier.isInterface(clazz.flags())) {
                         String className = clazz.name().toString();
                         resources.add(className);
                         reflectiveClass.produce(new ReflectiveClassBuildItem(true, true, className));
+
+                        if (!clazz.hasNoArgsConstructor()) {
```
Comment (mkouba) [inline extensions/resteasy/deployment/src/main/java/io/quarkus/resteasy/deployment/ResteasyScanningProcessor.java]: I'm quite sure we can do this for every resource class. JAX-RS does support some kind of constructor injection, or? Actually, I found a bug in our ArC integration - the following constructor results in unsatisfied dependency:
```java
public TestResourceWithConstructorInjection(@Context Application application) {
   this.application = application;
}
```
Because we automatically consider this a CDI bean constructor.

Comment (mkouba) [reply extensions/resteasy/deployment/src/main/java/io/quarkus/resteasy/deployment/ResteasyScanningProcessor.java]: Hm, by the way if I annotate the class with `@ApplicationScoped` I get: 
```
javax.enterprise.inject.spi.DefinitionException: Normal scoped beans must declare a non-private constructor with no parameters
```
Because ArC is analyzing the original class (jandex view) and not the modified one.

**Review by mkouba — CHANGES_REQUESTED** [review]

File: extensions/resteasy/deployment/src/main/java/io/quarkus/resteasy/deployment/ResteasyScanningProcessor.java (hunk 2 above)
Comment (mkouba) [reply extensions/resteasy/deployment/src/main/java/io/quarkus/resteasy/deployment/ResteasyScanningProcessor.java]: Finally, the generated no-arg constructor would not be usable - it does not initialize the final fields. So I would expect some ugly exception when it's used...

Comment (geoand) [reply extensions/resteasy/deployment/src/main/java/io/quarkus/resteasy/deployment/ResteasyScanningProcessor.java]: I think I am missing some context here. I there a reason one would annotate a `@Path` resource with `@ApplicationScoped`?

The tests currently pass with the `final` fields, there is no problem at all. I haven't tried with `@ApplicationScoped` however.

Also, I didn't really understand the first comment, do you mean "I',m *not* quite sure"? 

So could this all just boil down to the following: Only generate a default constructor when there is no `@ApplicationScoped` annotation (and perhaps a few other constraints)?

File: integration-tests/main/src/test/java/io/quarkus/example/test/TestResteasyConstructorsTestCase.java [hunk 3]
```diff
@@ -0,0 +1,22 @@
...
+
+import static org.hamcrest.Matchers.is;
+
+import org.junit.jupiter.api.Test;
+
+import io.quarkus.test.junit.QuarkusTest;
+import io.restassured.RestAssured;
+
+@QuarkusTest
+public class TestResteasyConstructorsTestCase {
```
[the remark this answers is not in the document]
Comment (geoand) [reply integration-tests/main/src/test/java/io/quarkus/example/test/TestResteasyConstructorsTestCase.java]: Yeah makes sense, I'll do that once we figure out how to address the rest of your comments :)

File: extensions/resteasy/deployment/src/main/java/io/quarkus/resteasy/deployment/ResteasyScanningProcessor.java (hunk 2 above)
Comment (mkouba) [reply extensions/resteasy/deployment/src/main/java/io/quarkus/resteasy/deployment/ResteasyScanningProcessor.java]: > I there a reason one would annotate a @Path resource with @ApplicationScoped?

It is allowed. In fact, in CDI world `@ApplicationScoped` is usually used instead of `@Singleton`.

> The tests currently pass...

Yep, I think it passes because the constructor is not used at all.

> Also, I didn't really understand the first comment...

Ah, sorry, yes it should be: "I'm NOT quite sure "

> So could this all just boil down to the following...

I'm not sure. We should think about it...

Comment (geoand) [reply extensions/resteasy/deployment/src/main/java/io/quarkus/resteasy/deployment/ResteasyScanningProcessor.java]: My idea is to make the common case easy for developes - meaning that when they write a JAX-RS resource they can use constuctor injection (this is basically what Spring MVC users expect). 
So I would propose that we find the most restricted set of use cases where this is possible ( for example no `@ApplicationScoped` and I don't know what else :) ) and then later on if possible lift these restrictions. WDYT?

Comment (kenfinnigan) [reply extensions/resteasy/deployment/src/main/java/io/quarkus/resteasy/deployment/ResteasyScanningProcessor.java]: Is it that bad to require a constructor be added?

Trying to see what the benefits are, and whether they're outweighed by adding "magic" all over the place

Comment (geoand) [reply extensions/resteasy/deployment/src/main/java/io/quarkus/resteasy/deployment/ResteasyScanningProcessor.java]: @kenfinnigan this is the first thing that my local JUG leader (and Java Champion Paris Apostolopoulos) complained about for Quarkus. Spring folks are soooooooo used to not needing the extra boilerplate.

Comment (kenfinnigan) [reply extensions/resteasy/deployment/src/main/java/io/quarkus/resteasy/deployment/ResteasyScanningProcessor.java]: Ok, but I don't necessarily like the idea of sprinkling magic all over the place just to get Spring folks to look at Quarkus

Comment (geoand) [reply extensions/resteasy/deployment/src/main/java/io/quarkus/resteasy/deployment/ResteasyScanningProcessor.java]: It's only magic on the implementation side. For a user perspective having constructor injection work all over the place, makes perfect sense I think. For example, Arc supports constructor injection OOTB, so why not have this support everywhere?

Comment (kenfinnigan) [reply extensions/resteasy/deployment/src/main/java/io/quarkus/resteasy/deployment/ResteasyScanningProcessor.java]: As we're trying to remove code as much as possible to reduce size, it's more a concern about this type of thing being added all over the place in Quarkus to support a specific use case, potentially at the detriment of others.

Now that may not be the case here. I'm just cautioning against adding "magic" everywhere without good cause

Comment (geoand) [reply extensions/resteasy/deployment/src/main/java/io/quarkus/resteasy/deployment/ResteasyScanningProcessor.java]: :+1: for not adding stuff were we don't need it! 
I am no expert in what overhead some constructors would add, but I would _guess_ that it wouldn't be too much - especially if we only add it under very certain circumstances. In this case I think the added developer joy, would warrant sprinkling a tiny bit of magic.

Comment (FroMage) [reply extensions/resteasy/deployment/src/main/java/io/quarkus/resteasy/deployment/ResteasyScanningProcessor.java]: Well, we're adding default constructors to JPA entities in `Panache` and we've already noticed that they're also useful for JSON entities. All this could be done in a new `RESTEasy with Panache` extension, but TBH I don't see how we can justify requiring the user write this constructor when it will be exactly the same as the generated one and it's required and enough to fix these use-cases. That seems to me to be the very definition of "boilerplate".

Comment (mkouba) [reply extensions/resteasy/deployment/src/main/java/io/quarkus/resteasy/deployment/ResteasyScanningProcessor.java]: I don't mind adding these constructors but they need to be valid, i.e. if a class declares a final field the constructor must initialize it to a default value as defined by JLS. 

The other problem is with re-indexing the modified class. I don't know how exactly do our bytecode transformers work but I suppose we don't replace the original `ClassInfo` from the index of a pre-indexed dependency? (which is one of the protomoted ways to add a dependency to the application index)

Comment (geoand) [reply extensions/resteasy/deployment/src/main/java/io/quarkus/resteasy/deployment/ResteasyScanningProcessor.java]: @mkouba Is it even worth the trouble to generate a proper constructor (instead of just default one) even if the tests never fail? Also, do we need to worry about indexing the class? Are we really gonna need to know about the synthetic no-arg constructor anywere?

Comment (mkouba) [reply extensions/resteasy/deployment/src/main/java/io/quarkus/resteasy/deployment/ResteasyScanningProcessor.java]: > Is it even worth the trouble to generate a proper constructor (instead of just default one) even if the tests never fail?

Have you tried to use the generated constructor? If you only want to fool validation logic of some framework the it's ok but for example in case of CDI we do use the no-args constructor to instantiate client proxies. 

> Also, do we need to worry about reindexing.

ArC validation is based on jandex. So if there is a bean class that has normal scope and does not declare a no-args constructor the validation should fail (no matter what the real class look like).

Comment (geoand) [reply extensions/resteasy/deployment/src/main/java/io/quarkus/resteasy/deployment/ResteasyScanningProcessor.java]: > > Is it even worth the trouble to generate a proper constructor (instead of just default one) even if the tests never fail?
> 
> Have you tried to use the generated constructor? If you only want to fool validation logic of some framework the it's ok but for example in case of CDI we do use the no-args constructor to instantiate client proxies.
> 

In this case it seems we are simply fooling RESTEasy - see [this](https://issues.jboss.org/browse/RESTEASY-2183?focusedCommentId=13715781). 

The more I think about it the more I think we should only be doing this if the resource is *not* annotated with `@ApplicationScoped` in order to avoid any suprises.
There should probably also be a restriction that there should not be a superclass other than `Object`.  

> > Also, do we need to worry about reindexing.
> 
> ArC validation is based on jandex. So if there is a bean class that has normal scope and does not declare a no-args constructor the validation should fail (no matter what the real class look like).

So if we only do this constructor generation for `Singleton` scope we can get around this restriction as well?

Comment (geoand) [reply extensions/resteasy/deployment/src/main/java/io/quarkus/resteasy/deployment/ResteasyScanningProcessor.java]: I pushed a change that now only adds the default constuctor if there is no other annotation other than `@Path` and the resource doesn't extend from any class - This is should be the strictect possible (but most common I would say) use case.
@mkouba Do you think it is safe now?

File: integration-tests/main/src/test/java/io/quarkus/example/test/TestResteasyConstructorsTestCase.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (geoand) [reply integration-tests/main/src/test/java/io/quarkus/example/test/TestResteasyConstructorsTestCase.java]: Added this test as well

File: extensions/resteasy/deployment/src/main/java/io/quarkus/resteasy/deployment/ResteasyScanningProcessor.java (hunk 2 above)
Comment (mkouba) [reply extensions/resteasy/deployment/src/main/java/io/quarkus/resteasy/deployment/ResteasyScanningProcessor.java]: > So if we only do this constructor generation for Singleton scope we can get around this restriction as well?

Yes, `@Singleton` does not require a client proxy.

> Do you think it is safe now?

Well, the constructor would still not be valid if a class contains some final fields but it should be safe enough to fool RESTEasy ;-).

Comment (geoand) [reply extensions/resteasy/deployment/src/main/java/io/quarkus/resteasy/deployment/ResteasyScanningProcessor.java]: My thoughts exactly :)

Comment (geoand) [reply extensions/resteasy/deployment/src/main/java/io/quarkus/resteasy/deployment/ResteasyScanningProcessor.java]: @mkouba WDYT, should we merge?

File: extensions/resteasy/deployment/src/main/java/io/quarkus/resteasy/deployment/ResteasyScanningProcessor.java [hunk 4]
```diff
@@ -344,6 +357,45 @@ public void build(
...
+            // generate default constructors for suitable concrete @Path classes that don't have them
+            // see https://issues.jboss.org/browse/RESTEASY-2183
+            for (ClassInfo classInfo : withoutDefaultCtor) {
+                // keep it super simple - only generate default constructor is the object is a direct descendant of Object
+                if (!(classInfo.superClassType() != null && classInfo.superClassType().name().equals(DotNames.OBJECT))) {
+                    return;
+                }
+                // again keep it very very simple, we know that there is the @Path annotation, so don't try to generate the
+                // default constructor if there are others (basically we want to avoid surprises with any CDI scopes)
+                if (classInfo.classAnnotations().size() > 1) {
```
Comment (mkouba) [inline extensions/resteasy/deployment/src/main/java/io/quarkus/resteasy/deployment/ResteasyScanningProcessor.java]: Hm, so it will stop working if I add e.g. `@Consumes("application/json")` which is a very common use case.

Comment (geoand) [reply extensions/resteasy/deployment/src/main/java/io/quarkus/resteasy/deployment/ResteasyScanningProcessor.java]: Good catch! What other common cases can you think of that we should take into account?

File: extensions/resteasy/deployment/src/main/java/io/quarkus/resteasy/deployment/ResteasyScanningProcessor.java (hunk 2 above)
Comment (mkouba) [reply extensions/resteasy/deployment/src/main/java/io/quarkus/resteasy/deployment/ResteasyScanningProcessor.java]: I'm +0. It looks like a lot of code to support only a very specific simple use case. @gsmet @kenfinnigan WDYT?

File: extensions/resteasy/deployment/src/main/java/io/quarkus/resteasy/deployment/ResteasyScanningProcessor.java (hunk 4 above)
Comment (mkouba) [reply extensions/resteasy/deployment/src/main/java/io/quarkus/resteasy/deployment/ResteasyScanningProcessor.java]: Any jax-rs annotation?

Comment (geoand) [reply extensions/resteasy/deployment/src/main/java/io/quarkus/resteasy/deployment/ResteasyScanningProcessor.java]: Makes sense!

Comment (geoand) [reply extensions/resteasy/deployment/src/main/java/io/quarkus/resteasy/deployment/ResteasyScanningProcessor.java]: Fixed

File: extensions/resteasy/deployment/src/main/java/io/quarkus/resteasy/deployment/ResteasyScanningProcessor.java (hunk 2 above)
Comment (geoand) [reply extensions/resteasy/deployment/src/main/java/io/quarkus/resteasy/deployment/ResteasyScanningProcessor.java]: One last thing if I may say so: The use case maybe simple and specific, but it goes a long way to create a consistent experience IMHO. Users should not have to add boilerplate (if that can be avoided) because of limitation of framework - they honestly don't care. Think of it this way: Why should a JAX-RS resource be any different from a user perspective than all the `Singleton` beans he/she adds to their app that work perfectly with constructor injection without requiring a no-arg constructor?

**Comment by gsmet** [comment]
@geoand where are we on this? Should @mkouba review it again?

**Comment by geoand** [comment]
@gsmet I have addressed the concerns that @mkouba put forth.

All we need is decision is wether we want this in or not (see https://github.com/quarkusio/quarkus/pull/1875#discussion_r273430725) I strongly believe that it should be (https://github.com/quarkusio/quarkus/pull/1875#discussion_r273814876)

**Review by mkouba — APPROVED** [review]
