### PR TITLE
Use Gizmo2 to generate REST Client's CDI wrapper

### LINKED ISSUE #48898: [Rest-Client] ConstraintDeclarationException HV000151 When using Validation Constraints on Container Elements
### Describe the bug

When using bean validation annotation on container elements e.g. `List<@Valid User> body` in a method of a RestClient interface under certain circumstances startup fails with:

`Caused by: jakarta.validation.ConstraintDeclarationException: HV000151: A method overriding another method must not redefine the parameter constraint configuration, but method ExampleRestClient$$CDIWrapper#post8(String, List) redefines the configuration of ExampleRestClient#post8(String, List).`

**Reproducer:**
add the following class to a quarkus project (and uncommenting the example methods) which uses quarkus-rest-client.
run quarkus -> startup fails
(issue is not present in quarkus-resteasy-client)

```
@Path("/example")
@RegisterRestClient
public interface ExampleRestClient {
	// OK
	@POST
	void post1(@QueryParam("a") @Size(min = 4, max = 32) String query);

	@POST void post2(@QueryParam("a") @Size(min = 4, max = 32) String query, @Valid User body);

	@POST void post3(List<@Size(min=4, max=64) String> body);

	@POST void post4(@Valid List<@Size(min=4, max=64) String> body);

	@POST void post5(@Valid User body);

	@POST void post6(List<@Valid User> body);

	@POST void post7(@QueryParam("a") String query, List<@Valid User> body);

	// NOT OK

	// @POST void post8(@NotNull List<@Valid User> body);

	// @POST void post9(@QueryParam("a") @Size(min = 4, max = 32) String query, List<@Valid User> body);

	// @POST void post10(@Valid List<@Valid User> body);
}
```

### Expected behavior

Quarkus starts, restclient works with bean validation

### Actual behavior

ERROR [io.qua.run.Quarkus] Error running Quarkus: java.lang.ExceptionInInitializerError
        at java.base/jdk.internal.misc.Unsafe.allocateInstance(Native Method)
        at java.base/java.lang.invoke.DirectMethodHandle.allocateInstance(DirectMethodHandle.java:501)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:79)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:51)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:144)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:121)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
        ... 10 more
Caused by: jakarta.enterprise.inject.CreationException: Error creating synthetic bean [cjc3qHBmUB1ZLkEsO6nVgOk3474]: jakarta.validation.ConstraintDeclarationException: HV000151: A method overriding another method must not redefine the parameter constraint configuration, but method ExampleRestClient$$CDIWrapper#post9(List) redefines the configuration of ExampleRestClient#post9(List).

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

Linux - 6.8.0-60-generic #63-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 15 19:04:15 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

 21.0.7+6-Ubuntu-0ubuntu124.04, mixed mode, sharing)openjdk version "21.0.7" 2025-04-15 OpenJDK Runtime Environment (build 21.0.7+6-Ubuntu-0ubuntu124.04) OpenJDK 64-Bit Server VM (build

### Quarkus version or git rev

3.24.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.9 (8e8579a9e76f7d015ee5ec7bfcdc97d260186937)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
- Fixes: https://github.com/quarkusio/quarkus/issues/48898

### CODE REVIEW

File: extensions/resteasy-reactive/rest-client/deployment/src/main/java/io/quarkus/rest/client/reactive/deployment/RestClientReactiveProcessor.java [hunk 1]
```diff
@@ -552,31 +567,41 @@ void addRestClientBeans(
...
+            final String configKeyValue = configKey.orElse(null);
+            final String baseUriValue = baseUri.orElse("");
+
+            ClassDesc interfaceClassDesc = classDescOf(jaxrsInterface);
+            ClassDesc wrapperBaseClassDesc = ClassDesc.of(RestClientReactiveCDIWrapperBase.class.getName());
+
+            Gizmo gizmo = Gizmo.create(new GeneratedBeanGizmo2Adaptor(generatedBeans));
+            gizmo.class_(wrapperClassName, cc -> {
+                cc.extends_(RestClientReactiveCDIWrapperBase.class);
+                cc.implements_(genericTypeOfClass(Type.create(jaxrsInterface.name(), Type.Kind.CLASS)));
```
Comment (Ladicek) [inline extensions/resteasy-reactive/rest-client/deployment/src/main/java/io/quarkus/rest/client/reactive/deployment/RestClientReactiveProcessor.java]:
```suggestion
                cc.implements_(interfaceClassDesc);
```

File: extensions/resteasy-reactive/rest-client/deployment/src/main/java/io/quarkus/rest/client/reactive/deployment/RestClientReactiveProcessor.java [hunk 2]
```diff
@@ -552,31 +567,41 @@ void addRestClientBeans(
...
 
-                final ScopeInfo scope = restClientsBuildTimeConfig.getScope(capabilities, jaxrsInterface)
-                        .orElse(BuiltinScope.APPLICATION).getInfo();
                 // add a scope annotation, e.g. @Singleton
-                classCreator.addAnnotation(scope.getDotName().toString());
-                classCreator.addAnnotation(RestClient.class);
+                cc.addAnnotation(ClassDesc.of(scope.getDotName().toString()), RetentionPolicy.RUNTIME, ab -> {
+                });
```
Comment (Ladicek) [inline extensions/resteasy-reactive/rest-client/deployment/src/main/java/io/quarkus/rest/client/reactive/deployment/RestClientReactiveProcessor.java]:
```suggestion
                cc.addAnnotation(classDescOf(scope.getDotName()));
```

File: extensions/resteasy-reactive/rest-client/deployment/src/main/java/io/quarkus/rest/client/reactive/deployment/RestClientReactiveProcessor.java [hunk 3]
```diff
@@ -622,50 +642,77 @@ void addRestClientBeans(
...
 
-                    if (Modifier.isAbstract(method.flags())) { // RestClient method
-                        ResultHandle delegate = methodCreator.invokeVirtualMethod(
-                                MethodDescriptor.ofMethod(RestClientReactiveCDIWrapperBase.class, "getDelegate",
-                                        Object.class),
-                                methodCreator.getThis());
+                        for (Type exception : method.exceptions()) {
+                            // declared exceptions are important in case the client is intercepted, because interception
+                            // subclasses wrap undeclared checked exceptions into `ArcUndeclaredThrowableException`
+                            mc.throws_(genericTypeOfThrows(exception, index));
```
Comment (Ladicek) [inline extensions/resteasy-reactive/rest-client/deployment/src/main/java/io/quarkus/rest/client/reactive/deployment/RestClientReactiveProcessor.java]: Exception types cannot be parameterized, so I guess you're just trying to copy possible type annotations? Are they even relevant in the `throws` clause? I guess not, so you could just do

```java
mc.throws_(classDescOf(exception));
```

But what you have here is fine too.

**Review by Ladicek — APPROVED** [review]
LGTM. Added just a few tiny comments that shorten the code slightly, but that's just cosmetics.

File: extensions/resteasy-reactive/rest-client/deployment/src/main/java/io/quarkus/rest/client/reactive/deployment/RestClientReactiveProcessor.java (hunk 2 above)
Comment (geoand) [reply extensions/resteasy-reactive/rest-client/deployment/src/main/java/io/quarkus/rest/client/reactive/deployment/RestClientReactiveProcessor.java]: This doesn't seem to work, perhaps it was added to a newer version of Gizmo2?

File: extensions/resteasy-reactive/rest-client/deployment/src/main/java/io/quarkus/rest/client/reactive/deployment/RestClientReactiveProcessor.java (hunk 3 above)
Comment (geoand) [reply extensions/resteasy-reactive/rest-client/deployment/src/main/java/io/quarkus/rest/client/reactive/deployment/RestClientReactiveProcessor.java]: Great point, thanks!

File: extensions/resteasy-reactive/rest-client/deployment/src/main/java/io/quarkus/rest/client/reactive/deployment/RestClientReactiveProcessor.java (hunk 2 above)
Comment (Ladicek) [reply extensions/resteasy-reactive/rest-client/deployment/src/main/java/io/quarkus/rest/client/reactive/deployment/RestClientReactiveProcessor.java]: Aaah you're right, my bad -- we have a simplified method for adding a member-less annotation, but it doesn't accept a `ClassDesc`, just a `Class`. We could simplify that even for `ClassDesc`, but for now, we don't. Sorry for the noise.

Comment (geoand) [reply extensions/resteasy-reactive/rest-client/deployment/src/main/java/io/quarkus/rest/client/reactive/deployment/RestClientReactiveProcessor.java]: NP, thanks for great suggestions all around!

**Comment by dankristensen** [comment]
@geoand Any chance this can be backported to 3.27.x stream?

**Comment by geoand** [comment]
No, it will be part of the next LTS

**Comment by dankristensen** [comment]
Great. We will look forward to that

**Comment by geoand** [comment]
👌

**Comment by brunobat** [comment]
Gizmo2 is not part of 3.27.x. Removing backport.
