### PR TITLE
Fix OidcClient duplicating the client_id for the public client

### LINKED ISSUE #26619: OIDC Client repeatedly adds client-id when no secret is specified
### Describe the bug

When configuring an OIDC client, if only the client-id is used for the request, then the client id will be concatenated to every request until an new instance of the client is created.

Issue comes from how the formBody is created.

OidcClientImpl.getJsonResponse(...) line 111

```
else if (!OidcCommonUtils.isClientSecretPostAuthRequired(oidcConfig.credentials)) {
    body.add(OidcConstants.CLIENT_ID, oidcConfig.clientId.get());
}
```

We are using Quarkus version 2.7.5.Final.

### Expected behavior

client-id should only be added to the request once.

As a workaround you can add a dummy client-secret to the oidc client configutration.

quarkus.oidc-client.credentials.client-secret.value=xxx
quarkus.oidc-client.credentials.client-secret.method=post

### Actual behavior

client-id is concatenated to every request.

```
public class OidcClass {

  @Inject
  @NamedOidcClient("test")
  OidcClient oidcClient;

  public Uni<String>getToken() {
    return oidcClient.getTokens().map(tokens -> BEARER_KEYWORD + tokens.getAccessToken())
  }
}
```

Calling getToken() multiple times results in the following form bodies for the http requests:

------------------- 1st request -----------------------

grant_type=password
username=xxx
password=xxx
client_id=public

 --------------------  2nd request -------------------

grant_type=password
username=xxx
password=xxx
client_id=public
client_id=public

------------------- 3rd request ---------------

grant_type=password
username=xxx
password=xxx
client_id=public
client_id=public
client_id=public

### How to Reproduce?

Configure an OidcClient with the following settings

quarkus.oidc-client.auth-server-url=xxx
quarkus.oidc-client.discovery-enabled=false
quarkus.oidc-client.token-path=/protocol/openid-connect/token
quarkus.oidc-client.client-id=public
quarkus.oidc-client.grant.type=password
quarkus.oidc-client.grant-options.password.username=xxx
quarkus.oidc-client.grant-options.password.password=xxx

### PR DESCRIPTION
**Pull request by sberyozkin**
Fixes #26619.

`OidcClient` has a cached `MultiMap` which keeps some properties which are reused across multiple token requests (ex, it has a client id and secret set if the client post authentication is required, and scopes) - but if the public client is used to request a token then the same client id is added to the same `MultiMap`. 

So this PR does a minor update, copies the map to have a request specific map if the client is public (as it does in other cases) and it fixes the problem, the test has been added.

### CODE REVIEW

File: extensions/oidc-client/runtime/src/main/java/io/quarkus/oidc/client/runtime/OidcClientImpl.java [hunk 1]
```diff
@@ -109,7 +109,7 @@ public Uni<Tokens> get() {
                         body.add(OidcConstants.CLIENT_ASSERTION, jwt);
                     }
                 } else if (!OidcCommonUtils.isClientSecretPostAuthRequired(oidcConfig.credentials)) {
-                    body.add(OidcConstants.CLIENT_ID, oidcConfig.clientId.get());
+                    body = copyMultiMap(body).add(OidcConstants.CLIENT_ID, oidcConfig.clientId.get());
```
Comment (gastaldi) [inline extensions/oidc-client/runtime/src/main/java/io/quarkus/oidc/client/runtime/OidcClientImpl.java:112]: Isn't changing to `set` enough here?

Comment (sberyozkin) [reply extensions/oidc-client/runtime/src/main/java/io/quarkus/oidc/client/runtime/OidcClientImpl.java:112]: @gastaldi Sorry, forgot to add a comment relating to `set`, since `OidcClient` will be reused by multiple threads, I decided to avoid `set`

Comment (gastaldi) [reply extensions/oidc-client/runtime/src/main/java/io/quarkus/oidc/client/runtime/OidcClientImpl.java:112]: Copying the MultiMap is fine, my question was more that if you call `add` again you will end up with more than one ClientID in the Map?

Comment (sberyozkin) [reply extensions/oidc-client/runtime/src/main/java/io/quarkus/oidc/client/runtime/OidcClientImpl.java:112]: Hey @gastaldi, sorry for asking to review on Sunday :-).
I see,  so, in the original map client id is not present,  this copy is created per every request and I guess, either `set` or `add` will do. I've added a test, as you can see in the original issue the duplication starts from a 2nd request (double `add`), so the test does 2 requests, without the fix the 2nd request was failing.
if you'd like I can replace `add` with `set`, would not be a problem at all

Comment (gastaldi) [reply extensions/oidc-client/runtime/src/main/java/io/quarkus/oidc/client/runtime/OidcClientImpl.java:112]: No biggie, just curious really ;)

**Review by gastaldi — APPROVED** [review]

File: extensions/oidc-client/runtime/src/main/java/io/quarkus/oidc/client/runtime/OidcClientImpl.java (hunk 1 above)
Comment (sberyozkin) [reply extensions/oidc-client/runtime/src/main/java/io/quarkus/oidc/client/runtime/OidcClientImpl.java]: Hi George, just pushed a minor update, it is quiet today, so an extra CI run will not be a problem, `set` reads better for setting a single value property :-), thanks for the time
