### PR TITLE
Register JBoss EnhancedQueueExecutor$RuntimeFields for runtime init

### LINKED ISSUE #43797: Native image builds with `main` print a warning about `RecomputeFieldValue.ArrayIndexScale`
### Describe the bug

Since https://github.com/quarkusio/quarkus/pull/43648 got merged native-image compilation prints warnings like the following:

```
Warning: RecomputeFieldValue.ArrayIndexScale automatic substitution failed. The automatic substitution registration was attempted because a call to jdk.internal.misc.Unsafe.arrayIndexScale(Class) was detected in the static initializer of org.jboss.threads.EnhancedQueueExecutor$RuntimeFields. Detailed failure reason(s): Could not determine the field where the value produced by the call to jdk.internal.misc.Unsafe.arrayIndexScale(Class) for the array index scale computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store. 
Warning: RecomputeFieldValue.ArrayIndexScale automatic substitution failed. The automatic substitution registration was attempted because a call to jdk.internal.misc.Unsafe.arrayIndexScale(Class) was detected in the static initializer of org.jboss.threads.EnhancedQueueExecutor$RuntimeFields. Detailed failure reason(s): Could not determine the field where the value produced by the call to jdk.internal.misc.Unsafe.arrayIndexScale(Class) for the array index scale computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store. 
Warning: RecomputeFieldValue.ArrayBaseOffset automatic substitution failed. The automatic substitution registration was attempted because a call to jdk.internal.misc.Unsafe.arrayBaseOffset(Class) was detected in the static initializer of org.jboss.threads.EnhancedQueueExecutor$RuntimeFields. Detailed failure reason(s): Could not determine the field where the value produced by the call to jdk.internal.misc.Unsafe.arrayBaseOffset(Class) for the array base offset computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store. 
Warning: RecomputeFieldValue.ArrayBaseOffset automatic substitution failed. The automatic substitution registration was attempted because a call to jdk.internal.misc.Unsafe.arrayBaseOffset(Class) was detected in the static initializer of org.jboss.threads.EnhancedQueueExecutor$RuntimeFields. Detailed failure reason(s): Could not determine the field where the value produced by the call to jdk.internal.misc.Unsafe.arrayBaseOffset(Class) for the array base offset computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store. 
Warning: RecomputeFieldValue.ArrayBaseOffset automatic substitution failed. The automatic substitution registration was attempted because a call to jdk.internal.misc.Unsafe.arrayBaseOffset(Class) was detected in the static initializer of org.jboss.threads.EnhancedQueueExecutor$RuntimeFields. Detailed failure reason(s): Could not determine the field where the value produced by the call to jdk.internal.misc.Unsafe.arrayBaseOffset(Class) for the array base offset computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store. 
Warning: RecomputeFieldValue.ArrayBaseOffset automatic substitution failed. The automatic substitution registration was attempted because a call to jdk.internal.misc.Unsafe.arrayBaseOffset(Class) was detected in the static initializer of org.jboss.threads.EnhancedQueueExecutor$RuntimeFields. Detailed failure reason(s): Could not determine the field where the value produced by the call to jdk.internal.misc.Unsafe.arrayBaseOffset(Class) for the array base offset computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store. 
```

See https://github.com/quarkusio/quarkus/actions/runs/11256143437/job/31312612207#step:16:399

### Expected behavior

Build should succeed without warnings.

### Actual behavior

Build succeeds with warnings.

### How to Reproduce?

```
./mvnw -Dnative -pl integration-tests/main -Dnative.surefire.skip -Dformat.skip -Dno-descriptor-tests clean package
```

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

21.0.4+7

### Mandrel or GraalVM version (if different from Java)

23.1.4.0

### Quarkus version or git rev

60f42105be07b48471509ac9498b605e573b06bb

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by zakkak**
As suggested in the source code
https://github.com/jbossas/jboss-threads/blob/60a6d35ec56e85f683ff45d89b29ea4f7b0e01aa/src/main/java/org/jboss/threads/EnhancedQueueExecutor.java#L325

Closes https://github.com/quarkusio/quarkus/issues/43797

### CODE REVIEW

File: core/deployment/src/main/java/io/quarkus/deployment/JBossProcessor.java [hunk 1]
```diff
@@ -0,0 +1,12 @@
+package io.quarkus.deployment;
+
+import io.quarkus.deployment.annotations.BuildStep;
+import io.quarkus.deployment.builditem.nativeimage.RuntimeInitializedClassBuildItem;
+
+public class JBossProcessor {
```
Comment (gsmet) [inline core/deployment/src/main/java/io/quarkus/deployment/JBossProcessor.java:6]: Minor nitpick but could we call this class `JBossThreadsProcessor` instead?

Comment (zakkak) [reply core/deployment/src/main/java/io/quarkus/deployment/JBossProcessor.java:6]: That was the initial name I used as well, but then I changed it so that in the future if anyone wants to add anything JBoss related they wouldn't create a new class for it as we don't seem to do much for jboss dependencies... I am OK with either name.

Comment (gastaldi) [reply core/deployment/src/main/java/io/quarkus/deployment/JBossProcessor.java:6]: +1 for `JBossThreadsProcessor`. Having a separate `Processor` class for each JBoss project is a better approach IMHO

**Comment by gastaldi** [comment]
Speaking of which, can't https://github.com/jbossas/jboss-threads provide its own `native-image.properties` inside the JAR? Maybe a question to @dmlloyd

**Review by dmlloyd — APPROVED** [review]

**Review by gastaldi — APPROVED** [review]
