### PR TITLE
Make LocaleConverter more lenient

### LINKED ISSUE #11430: java.lang.IllegalArgumentException: Unable to resolve locale: c.u-US
When I try to build the jar on a server I got  the next error
```
[INFO] --- quarkus-maven-plugin:1.7.0.Final:build (default) @ quarkus-cloud ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  32.095 s
[INFO] Finished at: 2020-08-17T22:05:49Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:1.7.0.Final:build (default) on project quarkus-cloud: Failed to build quarkus application: java.lang.IllegalArgumentException: Unable to resolve locale: c.u-US -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Additional context**
IBM cloud toolchain

On my computer works just fine: macos 10.15.6 (19G2021)

### PR DESCRIPTION
**Pull request by gastaldi**
This is necessary in environments where the C.UTF-8 locale is used (like in IBM Cloud toolchain environments).

Fixes #11430

### CODE REVIEW

**Comment by FcoJavierSainz** [comment]
Hey, I tested just by copying the class (isn't the cleanest but fast) and It works

```
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 3448ms
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  41.159 s
[INFO] Finished at: 2020-08-20T15:46:16Z
[INFO] ------------------------------------------------------------------------
```

**Review by FcoJavierSainz — APPROVED** [review]

File: core/runtime/src/main/java/io/quarkus/runtime/configuration/LocaleConverter.java [hunk 1]
```diff
@@ -29,11 +29,6 @@ public Locale convert(final String value) {
             return null;
         }
 
-        Locale locale = Locale.forLanguageTag(NORMALIZE_LOCALE_PATTERN.matcher(localeValue).replaceAll("-"));
-        if (locale.getLanguage() == null || locale.getLanguage().isEmpty()) {
```
Comment (gsmet) [inline core/runtime/src/main/java/io/quarkus/runtime/configuration/LocaleConverter.java:33]: I think I would prefer if we kept these tests but also check that the locale is not `Locale.ROOT`.

File: core/runtime/src/test/java/io/quarkus/runtime/configuration/LocaleConverterTest.java [hunk 2]
```diff
@@ -19,8 +20,16 @@ public void testStandardLocale() {
     @Test
     public void testUnderscoreLocale() {
         LocaleConverter localeConverter = new LocaleConverter();
-        Locale locale = localeConverter.convert("fr-FR");
+        Locale locale = localeConverter.convert("fr_FR");
```
Comment (gsmet) [inline core/runtime/src/test/java/io/quarkus/runtime/configuration/LocaleConverterTest.java:23]: Good catch.

File: core/runtime/src/main/java/io/quarkus/runtime/configuration/LocaleConverter.java (hunk 1 above)
Comment (gastaldi) [reply core/runtime/src/main/java/io/quarkus/runtime/configuration/LocaleConverter.java:33]: Done

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
I dunno :)

**Comment by gsmet** [comment]
To be honest, I think I had a good reason to do it that way but can't remember. If it's not a problem I would rather keep it the way it is.

**Comment by gsmet** [comment]
Thanks for taking care of that one!

**Comment by FcoJavierSainz** [comment]
Thanks guys
