### PR TITLE
Replace websockets example by extension codestart in java & kotlin

### LINKED ISSUE #20235: Websocket should have a codestarts instead of a singleton example
### Describe the bug

Currently, websocket is linked to a singleton example:
https://github.com/quarkusio/quarkus/tree/main/devtools/project-core-extension-codestarts/src/main/resources/codestarts/quarkus/examples/undertow-websockets-example

Instead we should provide a starter codestarts which can be combined with other codestarts.

### PR DESCRIPTION
**Pull request by ia3andy**
Closes #20235 

This replaces the previous websocket example which was blocking extensions combination.

### CODE REVIEW

File: devtools/project-core-extension-codestarts/src/main/resources/codestarts/quarkus/extension-codestarts/websockets-codestart/java/src/main/java/org/acme/StartWebSocket.java [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+     * @param session the websocket session
+     * @param message the message to send
+     * @throws IOException              if there is a communication error sending the message object.
+     * @throws EncodeException          if there was a problem encoding the message.
+     * @throws IllegalArgumentException if the message parameter is {@code null}
+     */
+    public void sendMessage(Session session, String message) throws EncodeException, IOException {
+        requireNonNull(session, "session is required");
+
+        session.getBasicRemote().sendObject(message);
```
Comment (ia3andy) [inline devtools/project-core-extension-codestarts/src/main/resources/codestarts/quarkus/extension-codestarts/websockets-codestart/java/src/main/java/org/acme/StartWebSocket.java:52]: @cescoffier it would be nice if you could give me the piece of code that your referred to for this (without the ugly `throws`)

Comment (ia3andy) [reply devtools/project-core-extension-codestarts/src/main/resources/codestarts/quarkus/extension-codestarts/websockets-codestart/java/src/main/java/org/acme/StartWebSocket.java]: I removed the sendMessage as it is not clear on the good solution. We will be able to add it in another PR if needed..

File: integration-tests/devtools/src/test/resources/__snapshots__/WebSocketsCodestartTest/testContent/src_main_kotlin_ilove_quark_us_StartWebSocket.kt [hunk 2]
```diff
@@ -0,0 +1,32 @@
...
+        println("onClose> $name")
+    }
+
+    @OnError
+    fun onError(session: Session?, @PathParam("name") name: String, throwable: Throwable) {
+        println("onError> $name: $throwable")
+    }
+
+    @OnMessage
+    fun onMessage(message: String, @PathParam("username") name: String) {
```
Comment (ia3andy) [inline integration-tests/devtools/src/test/resources/__snapshots__/WebSocketsCodestartTest/testContent/src_main_kotlin_ilove_quark_us_StartWebSocket.kt:29]: I will fix this "username" instead of "name"

**Review by aloubyansky — APPROVED** [review]

**Comment by rsvoboda** [comment]
Finally got to check it, running `rm -rf app-generated-skeleton && mvn io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:create -DprojectGroupId=my-groupId -DprojectArtifactId=app-generated-skeleton -DprojectVersion=1.0.0-SNAPSHOT -DpackageName=org.my.group -DplatformVersion=999-SNAPSHOT -Dextensions=spring-di,spring-web,websockets` gives both 🚀  spring-web-codestart and 🚀  websockets-codestart
