### PR TITLE
Fixes #2172, don't allow persist etc if no tx

### LINKED ISSUE #2172: PanacheEntityBase.persist() silently fails outside a transaction
If you call this method outside a transaction the entity is not added, and no error is thrown. I would expect one or the other, but not silent failure.

### PR DESCRIPTION
**Pull request by stuartwdouglas**

### CODE REVIEW

File: extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/entitymanager/TransactionScopedEntityManager.java [hunk 1]
```diff
@@ -112,20 +113,29 @@ private boolean isInTransaction() {
     @Override
     public void persist(Object entity) {
         try (EntityManagerResult emr = getEntityManager()) {
+            if (!emr.allowModification) {
+                throw new TransactionRequiredException("Transaction is not active");
```
Comment (FroMage) [inline extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/entitymanager/TransactionScopedEntityManager.java]: How about `Transaction is not active: add @Transactional to your method`?

**Review by FroMage — DISMISSED** [review]
That's much clearer for users, thanks!

**Comment by mkouba** [comment]
Looks good but let's wait for @Sanne ;-)

File: extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/entitymanager/TransactionScopedEntityManager.java (hunk 1 above)
Comment (mkouba) [reply extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/entitymanager/TransactionScopedEntityManager.java]: This would not work at the moment, right?

**Comment by stuartwdouglas** [comment]
I think Sanne is really busy at the moment, so maybe @emmanuelbernard could help with the review

**Review by gsmet — APPROVED** [review]
Looks OK to me.

File: extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/entitymanager/TransactionScopedEntityManager.java (hunk 1 above)
Comment (emmanuelbernard) [reply extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/entitymanager/TransactionScopedEntityManager.java]: @mkouba why not?

Comment (mkouba) [reply extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/entitymanager/TransactionScopedEntityManager.java]: Well, it will work once https://github.com/quarkusio/quarkus/pull/2629 is merged. Tests are not CDI beans ATM.
