### PR TITLE
Fix the Hibernate Search configuration documentation

### LINKED ISSUE #8993: hibernate search auto-indexing strategy not rendered perfectly in generated config doc
**Description**

Doc generator does not know how to render html table to asciidoc table which makes the rendered output of https://quarkus.io/guides/hibernate-search-elasticsearch#quarkus-hibernate-search-elasticsearch_quarkus.hibernate-search.automatic-indexing.synchronization.strategy  

**Implementation ideas**
use the `@ascidoclet` tag with the expected output instead here https://github.com/quarkusio/quarkus/blob/ce8bd8c47bc0fa12b4c4c9d5fd92de60e700e314/extensions/hibernate-search-elasticsearch/runtime/src/main/java/io/quarkus/hibernate/search/elasticsearch/runtime/HibernateSearchElasticsearchRuntimeConfig.java#L230-L393 example can be found here https://github.com/quarkusio/quarkus/blob/ce8bd8c47bc0fa12b4c4c9d5fd92de60e700e314/extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmConfig.java#L42-L76

/cc @gsmet WDYT?

### PR DESCRIPTION
**Pull request by gsmet**
Fixes #8993

I also made some adjustments to the website to allow proper nested tables in configuration.

### CODE REVIEW

**Review by machi1990 — APPROVED** [review]
Thanks for the quick fix. Tested it locally and looks much better.

File: extensions/hibernate-search-elasticsearch/runtime/src/main/java/io/quarkus/hibernate/search/elasticsearch/runtime/HibernateSearchElasticsearchRuntimeConfig.java [hunk 1]
```diff
@@ -227,168 +227,58 @@ public String getHibernateSearchString() {
...
-         * section of the reference documentation</a>
+         * https://docs.jboss.org/hibernate/search/6.0/reference/en-US/html_single/#mapper-orm-indexing-automatic-synchronization[this
+         * section of the reference documentation]
          * for more information.
+         *
+         * @asciidoclet
          */
+        // @formatter:on
         @ConfigItem(defaultValue = AutomaticIndexingSynchronizationStrategyNames.WRITE_SYNC)
         String strategy;
```
Comment (machi1990) [inline extensions/hibernate-search-elasticsearch/runtime/src/main/java/io/quarkus/hibernate/search/elasticsearch/runtime/HibernateSearchElasticsearchRuntimeConfig.java:283]: Not related but should this be an enum instead given that we only have four possible values?
