### PR TITLE
Fix the OIDC opaque token check

### LINKED ISSUE #46972: OIDC -Azure refresh token doesnt have expiration date
### Describe the bug

After upgrade from 2.16.12 to 3.19.4 we observe issues with offline_access and session prolonging. While debugging I found out refresh token is being ignored because it fails on this line https://github.com/quarkusio/quarkus/blob/8ca3d176f8989bca49b1879f0b7fed7982c2a6cd/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java#L426. Refresh token has 2 dots therefore is not treated as opaque but middle part cannot be parsed as JSON. Parsing fails and refresh is not happening. Can you please help me on resolution

### Expected behavior

Session should be prolong

### Actual behavior

ERROR 500

### How to Reproduce?

Add offline_access to scopes, configure azure as OIDC provider. Wait for IDtoken and accesstoken to expire

### Output of `uname -a` or `ver`

Windows 11

### Output of `java -version`

openjdk 21.0.3 2024-04-16 LTS
OpenJDK Runtime Environment Temurin-21.0.3+9 (build 21.0.3+9-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.3+9 (build 21.0.3+9-LTS, mixed mode, sharing)

### Quarkus version or git rev
3.19.4
### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Apache Maven 3.9.9 (8e8579a9e76f7d015ee5ec7bfcdc97d260186937)
Maven home: C:\ProgramData\chocolatey\lib\maven\apache-maven-3.9.9
Java version: 21.0.3, vendor: Eclipse Adoptium, runtime: C:\Program Files\Eclipse Adoptium\jdk-21.0.3.9-hotspot
Default locale: en_US, platform encoding: UTF-8
OS name: "windows 11", version: "10.0", arch: "amd64", family: "windows"
### Additional information
https://learn.microsoft.com/en-us/entra/identity-platform/refresh-tokens#token-lifetime

### PR DESCRIPTION
**Pull request by sberyozkin**
Fixes #46972.

The current OIDC opaque token check has been proved with #46990 to be incomplete.
Signed JWT tokens have 3 parts separated by 2 dots which is what the current light weight check does, but it can be just a concidence, the binary tokens may have random 2 dots in the sequence as well.
The side-effect highlighted by #46972 is that a binary refresh token with 2 dots is assumed to be JWT, and the parsing exception escapes causing a failure. 
While #46972 can be fixed by only adding another exception catch block as done in this PR, I've also updated the opaque token check which is done in other code branches - it did not cause side-effects so far but might if not fixed

### CODE REVIEW

File: extensions/oidc/runtime/src/test/java/io/quarkus/oidc/runtime/OidcUtilsTest.java [hunk 1]
```diff
@@ -241,7 +241,8 @@ public void testTokenWithCustomRolesWrongPath() throws Exception {
     public void testTokenIsOpaque() throws Exception {
         assertTrue(OidcUtils.isOpaqueToken("123"));
         assertTrue(OidcUtils.isOpaqueToken("1.23"));
-        assertFalse(OidcUtils.isOpaqueToken("1.2.3"));
```
Comment (sberyozkin) [inline extensions/oidc/runtime/src/test/java/io/quarkus/oidc/runtime/OidcUtilsTest.java:244]: This old test code shows that it was not even imaginable that a binary access token could have 2 dots, I have never seen it before, but that was wrong. But now it is checked properly

**Review by gastaldi — APPROVED** [review]

**Comment by gsmet** [comment]
Please also add the `triage/backport` label or this PR won't be included in 3.21 (and then won't be included in 3.20 as it won't have any bake time). Not doing it myself silently so that you get the memo :).

**Comment by sberyozkin** [comment]
Hi @JozefDropco 

>is it safe to modify the isJwtTokenExpired as its used even here https://github.com/sberyozkin/quarkus/blob/6a746d33e18bf52b0e330fb1eacffae2074e022f/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java#L388

`isJwtTokenExpired` has been updated in this PR to avoid a duplicate attempt to read claims since the `isOpaqueToken` check is also trying to read claims to correctly determine if the token is opaque or not
