### PR TITLE
Fix QuarkusSecurityIdentity.isAnonymous check

### LINKED ISSUE #15735: QuarkusSecurityIdentity.builder(identity) loses isAnonymous flag
## Describe the bug
If QuarkusSecurityIdentity.builder(identity) is called with an identity that is anonymous then the identity returned from the builder returns always `false` on `isAnonymous()`
This typcially happens in a `SecurityIdentityAugmentor` that doesn't check the identity for anonymous.

### Expected behavior
If QuarkusSecurityIdentity.builder(identity) is called with an anonymous identity (`isAnonymous()` returns true) the produced identity must be an anonymous identity too, if not specified otherwise. Or if that's not supported builder(identity) should throw an exception if the specified identity is anonymous.
Since `SecurityIdentity` is an interface, QuarkusSecurityIdentity.builder should not also work with other implementations of the interface.

### Actual behavior
(Describe the actual behavior clearly and concisely.)

## To Reproduce

See above 

See also #15730

### PR DESCRIPTION
**Pull request by sberyozkin**
Fixes #15735.

### CODE REVIEW

**Comment by renegrob** [comment]
@sberyozkin I would still check isAnonymous within the Builder because there can be other implementations of the `QuarkusSecurityIdentity` interface. I don't know if it is necessary to be able to create anonymous instances with the Builder or if it should throw an exception in case you provide an anonymous identity to `QuarkusSecurityIdentity.builder(SecurityIdentity identity)`. But if it is allowed then the `isAnonymous` flag should be retained.

**Comment by gsmet** [comment]
This PR is not properly rebased on main. Please make sure your PR has been rebased before creating them or you might not get the latest CI adjustments.

I will force push a rebase.

**Comment by sberyozkin** [comment]
@renegrob thanks; I think if someone creates `SecurityIdentity` with this flag set to `true` then it should be 'backed up` by the other properties - i.e, principal should be null or its name is empty or at the very least it it should be an `anonymous` name.
For ex, allowing returning `true` where a non-null Principal is available would make the `SecurityIdentity` API inconsistent IMHO.
Hence the users should be encouraged to use the builder but the `anonymous` status should not be a property but calculated - if the users avoid using the builder then retaining a status during the copy is only guaranteed if it matches the expectations of that calculation: i.e if the passed identity is set as anonymous while Principal is `alice` then it is not an anonymous identity, and similarly if it is not anonymous but Principal is null then it is also not consistent. Perhaps in such cases an exception should be thrown

**Comment by sberyozkin** [comment]
@gsmet Oh sorry, I may have forgotten to pull (with auto rebase), I'll cancel, as I need to tweak a few things, sorry

**Comment by sberyozkin** [comment]
@gsmet I see you've force-pushed :-), thanks

File: extensions/security/runtime/src/main/java/io/quarkus/security/runtime/QuarkusSecurityIdentity.java [hunk 1]
```diff
@@ -38,7 +38,7 @@ public Principal getPrincipal() {
 
     @Override
     public boolean isAnonymous() {
-        return false;
+        return principal == null || principal.getName() == null || principal.getName().trim().isEmpty();
```
Comment (renegrob) [inline extensions/security/runtime/src/main/java/io/quarkus/security/runtime/QuarkusSecurityIdentity.java:41]: I think trim() is a bit of an overkill but isEmpty() makes sense. All principal names will need to be trimmed on every call to isAnonymous...

Comment (sberyozkin) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/QuarkusSecurityIdentity.java]: @renegrob I don't mind, if I remove `trim` then one of the tests will pass, I'd use `isBlank` but we still support Java 8 :-)

**Comment by sberyozkin** [comment]
@renegrob I've updated the code and tests, see how it looks please; lets also wait for @stuartwdouglas to comment

**Comment by renegrob** [comment]
I think it covers everything - maybe even too much. I wonder if the isAnonymous logic could be a default implementation on the `SecurityIdentity` interface. Probably the `SecurityIdentity` interface should describe the contract of Principal vs isAnonymous (just like Object.equals() and Object.hashCode()). But the interface is defined in the quarkus-security project.

**Comment by sberyozkin** [comment]
having it as a default method would make sense; tests are failing - I underestimated the possible side-effects - will check tomorrow

**Review by stuartwdouglas — CHANGES_REQUESTED** [review]
This should be a boolean flag on QuarkusSecurityIdentity, we should not have special hard coded names that are considered to be anonymous.

**Comment by renegrob** [comment]
I agree with Steward. At first I liked that you did not introduce a new flag and I also agree that a non-anonymous identity should always have a principal set. However it is legitimate to have an anonymous identity with principal "anonymous-7b23ed61-2a1b-4708-bdd6-0cf1862cabe6". The flag makes things more explicit and easier. Also the builder can now have a setter setAnonymous(boolean).

**Comment by sberyozkin** [comment]
@renegrob You've asked for a case where `anonymous` is used as a Principal name, right ?
What is the point of qualifying the `anonymous` with something like `"anonymous-7b23ed61-2a1b-4708-bdd6-0cf1862cabe6"` ?

And I said, I'm not really sure what it would mean to have:
```
builder.setPrincipal(new SimplePrincipal("alice")).setAnonymous(true);
```
and then
```
@Inject SecurityIdentity identity;
identity.isAnounymous == `true`
```


this is not a good option to let the users to do it IMHO. @renegrob @stuartwdouglas, are you not convinced :-) ?

**Comment by sberyozkin** [comment]
@renegrob @stuartwdouglas the above example is a bit exaggerated because a user would not really do it - but if the API allows it is not very good IMHO. But the flag in general does help much.
Lets assume it is `false` by default and the user sets a null Principal or with the `anonymous` name and forgets to set the flag to true.
This PR fix may not seem flexible but it is really a Principal representation which tells us all about whether it is an anonymous identity or not. I'm not really concerned about variations like `xxx-anonymous-xxx` not being supported, it is enough to have a convention where we doc that if you want a non-null Principal with a non-null name be `anonymous` then set the name to `anonymous`.
Having said it all, I don't really want to have this issue becoming a big one :-). So if you prefer the flag alone then @renegrob please open a `quarkus-security` issue and I'll follow up later on with just checking that flag

Thanks

**Comment by renegrob** [comment]
You could define that an anonymous identity must not have a principal set and that probably makes sense. Currently this is not enforced and you might have all kind of strange effects if someone sets a principal on an anonymous identity. - That's what I meant. Sorry, I just threw an example at you without explaining what I meant.
Theoretically a principal could be still unauthenticated but then we would not have a SecurityIdentity.

**Comment by sberyozkin** [comment]
o@renegrob np, thanks

Perhaps there is some misunderstanding on my end but I'm not sure what you meant by

> Currently this is not enforced and you might have all kind of strange effects if someone sets a principal on an anonymous identity

Is it related to this PR or the main branch code ? I suggested some examples where exactly the same effect can be achieved with a flag :-)

As I said - if the flag is the solution you and Stuart would like to see then lets do it - please open a PR to `quarkus-security` to add a new method and I'll update this PR once @stuartwdouglas releases it to only check `anonymous` flag - ideally we should avoid a solution where we check the flag and also a principal state to decide if it is anonymous or not but les see how it goes.

thanks

**Comment by renegrob** [comment]
@sberyozkin I looked at the javadoc of `SecurityIdentity` and is says: "Instances of this class will always be available for injection even if no user is currently logged in. In this case isAnonymous() will return true, and the user will generally not have any roles (although some implementation may assign roles to anonymous users)." Hence a principal name could be present as long as the user is not logged in (e.g. during the login process).
I get your point and I totally agree that you could define that an anonymous user must not have a principal set. However the current contract is different and I don't see a strong reason to break it.

**Comment by stuartwdouglas** [comment]
The only condition we should enforce is that a non-anonymous user must have a principal set, the other way around is fine. Consider a scenario like a corporate intranet that allows access from the public internet. You might have two different anonymous identities, one that represents access from outside the office/VPN, and another that represents traffic from a trusted source. They are both still anonymous, but could be considered different.

**Comment by stuartwdouglas** [comment]
Also some systems may assign an arbitrary principal (like your hard coded 'anonymous' username) to the anonymous user.

**Comment by sberyozkin** [comment]
@stuartwdouglas @renegrob OK, thanks for the clarifications, I haven't actually checked JavaDocs before doing this PR :-)
So, I'll update with adding an internal flag, `SecurityIndentity.Builder.setAnonymous` can be added in parallel if needed as well but I guess it should not be a pre-requisite for completing this PR.
It is a day off tomorrow for me but I'll try to complete asap
thanks

**Comment by sberyozkin** [comment]
@renegrob @stuartwdouglas Have just updated the PR, how does it look now ? thanks

**Comment by sberyozkin** [comment]
JDK 11 Windows `resteasy-reactive` jsonb failure so it is not related

File: extensions/security/runtime/src/main/java/io/quarkus/security/runtime/QuarkusSecurityIdentity.java [hunk 2]
```diff
@@ -121,11 +123,16 @@ public static Builder builder() {
     }
 
     public static Builder builder(SecurityIdentity identity) {
-        return new Builder()
+        if (identity.getPrincipal() == null && !identity.isAnonymous()) {
```
Comment (renegrob) [inline extensions/security/runtime/src/main/java/io/quarkus/security/runtime/QuarkusSecurityIdentity.java:126]: I would check this condition in the build method and not here. With the builder you can manipulate all parameters and the input must not necessary be a valid SecurityIdentity.

Comment (sberyozkin) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/QuarkusSecurityIdentity.java:126]: @renegrob we can't reset the anonymous flag via the builder API right now - and also, should one expect a consistent `Securityidentity` state at this point ?

Comment (sberyozkin) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/QuarkusSecurityIdentity.java:126]: @renegrob I.e, even if `setAnonymous` is added, let the users start from a clean builder as opposed to pass the invalid `SecurityIdentity` instance (which is not modifiable)

Comment (stuartwdouglas) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/QuarkusSecurityIdentity.java:126]: @sberyozkin validation should be done at build(), not on a partially completed object, and the builder should have a `setAnonymous` method.

Comment (sberyozkin) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/QuarkusSecurityIdentity.java:126]: @stuartwdouglas there are 2 builder methods, this one takes a final `SecurityIdentity` so I don't agree that a completed `Securityidentity` should be accepted in the incorrect state - here once again we'd rely on the user to follow with the right sequence to fix a broken `Securityidentity`.

> and the builder should have a setAnonymous method.

@renegrob Can you open a PR please ?

Thanks

Comment (sberyozkin) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/QuarkusSecurityIdentity.java:126]: @stuartwdouglas @renegrob I've looked at it again. IMHO, without `setAnonymous` it does make sense to keep the current PR as is for the reasons suggested above (Input SecurityIdentity must be correct). `setAnonymous` would change everything, i.e, makes no sense to check at the start and the end - only at the end.
So I'll just push this check to the end and be done with it - this PR can then be merged for 1.13.0.Final or whenever Quarkus gets updated to use the updated `quarkus-security`

Comment (sberyozkin) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/QuarkusSecurityIdentity.java]: @stuartwdouglas @renegrob done - it is there (if we start without `setAnonymous`) or nearly there if not :-)

Comment (sberyozkin) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/QuarkusSecurityIdentity.java]: Hey @stuartwdouglas @renegrob Just one more line, not for the sake of continuing the argument but simply to add what I forgot to say earlier to explain better why I'm feeling not excited about dropping the early check: adding this copy constructor was the only contribution I had to `QuarkusSecurityIdentity` - the goal is about avoiding a boilerrplate code the custom `SecurityIdentityAugmentor` has to do in order to add a new attribute or credential type - we used to have all the demos showing a lot of copying from the original final identity which is what this copy constructor has eliminated. Custom `SecurityIdentityAugmentor` enhancing the existing `SecurityIdentity` (which was already prepared by `IdentityProvider` or a fellow higher priority `SecurityIdentityAugmentor`) is not about **fixing** it - it is about enhancing the already completed `SecurityIdentity`. The custom `SecurityIdentityAugmentor` which tries to enhance it does not know the existing state - it only adds something to it - hence the late check will `surprise` this current `SecurityIdentityAugmentor` which only added some custom credential if it happens it accepted an invalid `SecurityIdentity`.
Hence it is not a very sound approach IMHO - but I agree it is not a big deal since the check will be done anyway.
That was the last comment from me, promise :-)

File: extensions/security/runtime/src/main/java/io/quarkus/security/runtime/QuarkusSecurityIdentity.java [hunk 3]
```diff
@@ -212,6 +217,10 @@ public Builder addPermissionChecker(Function<Permission, Uni<Boolean>> function)
         }
```
Comment (renegrob) [inline extensions/security/runtime/src/main/java/io/quarkus/security/runtime/QuarkusSecurityIdentity.java:218]: I would put a setAnonymous(boolean anyonymous) method here. But maybe I need to checkout the code to see why this doesn't work.

File: extensions/security/runtime/src/main/java/io/quarkus/security/runtime/QuarkusSecurityIdentity.java (hunk 2 above)
Comment (renegrob) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/QuarkusSecurityIdentity.java]: Sorry, it was my fault that there was a detour. And I'm just a contributor and not owner of any code. Maybe I should just listen more and comment less. At least for me, I don't have a problem with your comments. They make sense and it is normal to have different point of views. Ideally we find a common agreement which can be different from anyones initial opinion or idea. And my opinion shouldn't have too much weight.

Comment (sberyozkin) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/QuarkusSecurityIdentity.java]: @renegrob You are very much welcome with your comments and I give them the same weight as to comments from @stuartwdouglas in this case - you are the author of this issue, have already contributed, so I'm CC-ing you and take what you say on board :-). Yes - we can sometimes have a rather long discussion but it can be worth it, especially, when it comes to the sec issues :-)

File: extensions/security/runtime/src/main/java/io/quarkus/security/runtime/QuarkusSecurityIdentity.java (hunk 3 above)
Comment (sberyozkin) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/QuarkusSecurityIdentity.java:218]: @renegrob Hey, ha-ha, sorry, I'm a bit all over the place - of course it has to be added here, for some reasons (may be because I was not excited about this option) - I thought it would have to be added in `quarkus-security`, will push an update shortly

**Comment by sberyozkin** [comment]
@stuartwdouglas @renegrob all is done now - hope it works for all. Note the the test with a `Fixed` suffix in the name shows an identity prepared without a builder and having a wrong `principal` + `anonymous` combination is `fixed` by `setAnoymous` - the test above it asserts the error is reported

File: extensions/security/runtime/src/main/java/io/quarkus/security/runtime/QuarkusSecurityIdentity.java [hunk 4]
```diff
@@ -121,11 +123,13 @@ public static Builder builder() {
     }
 
     public static Builder builder(SecurityIdentity identity) {
-        return new Builder()
+        Builder builder = new Builder()
                 .addAttributes(identity.getAttributes())
                 .addCredentials(identity.getCredentials())
                 .addRoles(identity.getRoles())
                 .setPrincipal(identity.getPrincipal());
+        builder.anonymous = identity.isAnonymous();
```
Comment (renegrob) [inline extensions/security/runtime/src/main/java/io/quarkus/security/runtime/QuarkusSecurityIdentity.java:131]: I would continue using the fluent API here

**Comment by renegrob** [comment]
There's just a tiny comment from my side. Else everything looks good to me. Thanks a lot and sorry again for the struggle.

File: extensions/security/runtime/src/main/java/io/quarkus/security/runtime/QuarkusSecurityIdentity.java (hunk 4 above)
Comment (sberyozkin) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/QuarkusSecurityIdentity.java:131]: @renegrob oh yes, that line has stayed there before I added `setAnonymous`, good catch

**Comment by sberyozkin** [comment]
@renegrob

> There's just a tiny comment from my side. Else everything looks good to me. Thanks a lot and sorry again for the struggle.

Np at all, and like I said, your comments have been welcomed and indeed helped - thank you :-)

File: extensions/security/runtime/src/main/java/io/quarkus/security/runtime/QuarkusSecurityIdentity.java [hunk 5]
```diff
@@ -211,7 +216,25 @@ public Builder addPermissionChecker(Function<Permission, Uni<Boolean>> function)
...
+            if (built) {
+                throw new IllegalStateException();
+            }
+            this.anonymous = anonymous;
+            return this;
+        }
+
         public QuarkusSecurityIdentity build() {
+            if (principal == null && !anonymous) {
+                throw new IllegalStateException("Principal is null but anonymous status is true");
```
Comment (stuartwdouglas) [inline extensions/security/runtime/src/main/java/io/quarkus/security/runtime/QuarkusSecurityIdentity.java:235]: This messages is wrong, anonymous is false not true.

**Review by stuartwdouglas — CHANGES_REQUESTED** [review]

File: extensions/security/runtime/src/main/java/io/quarkus/security/runtime/QuarkusSecurityIdentity.java (hunk 5 above)
Comment (sberyozkin) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/QuarkusSecurityIdentity.java]: @stuartwdouglas fixed

**Comment by sberyozkin** [comment]
Hmm, there was an oidc code flow test failure (which I can't reproduce) - I copied the raw logs - most likely not related - as I'm not sure there is any test there with the non-anonymous identity and null principal

**Review by stuartwdouglas — APPROVED** [review]
