### PR TITLE
Qute template records: fix the way the canonical constructor is found

### LINKED ISSUE #42411: Qute template records: fix the way the canonical constructor is found
### Describe the bug

https://github.com/quarkusio/quarkus/blob/main/extensions/qute/deployment/src/main/java/io/quarkus/qute/deployment/QuteProcessor.java#L437-L439

May result in:
```
[error]: Build step io.quarkus.qute.deployment.QuteProcessor#collectCheckedTemplates threw an exception: java.lang.NullPointerException: Cannot invoke "org.jboss.jandex.MethodInfo.parameterTypes()" because "canonicalConstructor" is null
```

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mkouba**
- also fix the problem with compact record constructor
- resolves #42411

### CODE REVIEW

File: extensions/qute/deployment/src/main/java/io/quarkus/qute/deployment/QuteProcessor.java [hunk 1]
```diff
@@ -434,9 +434,9 @@ && isNotLocatedByCustomTemplateLocator(locatorPatternsBuildItem.getLocationPatte
                 if (!recordClass.isRecord()) {
                     continue;
                 }
-                Type[] componentTypes = recordClass.recordComponents().stream().map(RecordComponentInfo::type)
-                        .toArray(Type[]::new);
-                MethodInfo canonicalConstructor = recordClass.method(MethodDescriptor.INIT, componentTypes);
+                MethodInfo canonicalConstructor = recordClass.method(MethodDescriptor.INIT,
```
Comment (mkouba) [inline extensions/qute/deployment/src/main/java/io/quarkus/qute/deployment/QuteProcessor.java:437]: I cannot use the new `ClassInfo#canonicalRecordConstructor()` here because we need to get this into 3.8.

File: extensions/qute/deployment/src/test/java/io/quarkus/qute/deployment/records/TemplateRecordTest.java [hunk 2]
```diff
@@ -69,6 +71,9 @@ public void testTemplateRecords() throws InterruptedException, ExecutionExceptio
 
         assertEquals("Hello Lu!", new helloWorld("Lu").render());
         assertEquals("Lu", new hello$name("Lu").render());
+
+        assertEquals("15:true:foo", new multiParams(true, 15, "foo").render());
+        // assertThrows(IllegalArgumentException.class, () -> new multiParams(false, 50, null));
```
Comment (Ladicek) [inline extensions/qute/deployment/src/test/java/io/quarkus/qute/deployment/records/TemplateRecordTest.java:76]: ?

File: extensions/qute/deployment/src/main/java/io/quarkus/qute/deployment/QuteProcessor.java (hunk 1 above)
Comment (Ladicek) [reply extensions/qute/deployment/src/main/java/io/quarkus/qute/deployment/QuteProcessor.java:437]: Too bad :-)

**Review by Ladicek — APPROVED** [review]
LGTM, just one question about the commented assertion.

File: extensions/qute/deployment/src/test/java/io/quarkus/qute/deployment/records/TemplateRecordTest.java (hunk 2 above)
Comment (mkouba) [reply extensions/qute/deployment/src/test/java/io/quarkus/qute/deployment/records/TemplateRecordTest.java:76]: Ah, I forgot to uncomment this assertion after I fixed the problem with compact record constructor...

**Review by Ladicek — APPROVED** [review]
