### PR TITLE
Set the target file in the Model

### LINKED ISSUE #40853: POM is not preserved when we add or remove extensions with CLI
### Describe the bug

I was testing the backport related to preserving POM integrity after adding an extension ( https://github.com/quarkusio/quarkus/pull/40663/commits/2bb40f94ac518a45a092054f42b06f4e60680b24).
However, it seems that POM integrity is still not preserved when we add or remove extensions through CLI commands.
I've created a reproducer to show you this behavior (`git clone -b pom-preserve-cli https://github.com/jcarranzan/quarkus-reproducer.git`).

### Expected behavior

The POM retains the same structure and comments after adding or removing an extension.

### Actual behavior

The POM is overwritten, and comments are not preserved.

### How to Reproduce?

`git clone -b pom-preserve-cli https://github.com/jcarranzan/quarkus-reproducer.git`

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

3.8.999-SNAPSHOT

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by gastaldi**
This is necessary so `maven-model-helper` can know which pom.xml the change refers to.

- Fixes #40853

### CODE REVIEW

File: independent-projects/bootstrap/maven-resolver/src/main/java/io/quarkus/bootstrap/resolver/maven/workspace/ModelUtils.java [hunk 1]
```diff
@@ -232,7 +232,9 @@ private static Properties loadPomProps(Path appJar, Path artifactIdPath) throws
     }
 
     public static Model readModel(final Path pomXml) throws IOException {
-        return readModel(Files.newInputStream(pomXml));
+        Model model = readModel(Files.newInputStream(pomXml));
+        model.setPomFile(pomXml.toFile());
+        return model;
     }
```
Comment (gsmet) [inline independent-projects/bootstrap/maven-resolver/src/main/java/io/quarkus/bootstrap/resolver/maven/workspace/ModelUtils.java:238]: I'm not sure I understand this change and how it could affect adding an extension? I thought this would be used only for the bootstrap and that we were using other calls for actually manipulating the pom file?

I suppose we missed something but it would be good to clarify what.

Comment (gsmet) [reply independent-projects/bootstrap/maven-resolver/src/main/java/io/quarkus/bootstrap/resolver/maven/workspace/ModelUtils.java:238]: Wouldn't the right fix be to avoid calling the bootstrap `ModelUtils.readModel()` in `MavenProjectBuildFile`? I would expect us to use the formatting-aware one here?

My guess is that it would fix the issue and be more future proof.

That being said, don't revert the change you made as I think it's good to do it anyway.

Comment (gastaldi) [reply independent-projects/bootstrap/maven-resolver/src/main/java/io/quarkus/bootstrap/resolver/maven/workspace/ModelUtils.java:238]: @gsmet the Model that is passed to the `quarkus extension add` is read here (bootstrap). When persisting the model the maven-model-helper library is called, but because it requires a path to the original file to compare with the model to be persisted, you need to set this attribute (you could also pass the path to the file when persisting but that would impact on the existing public method signature in Quarkus core). This is done in the library here: https://github.com/fabric8-launcher/maven-model-helper/blob/main/src/main/java/io/fabric8/maven/Maven.java#L66, but because the change was reverted, we need to explicitly invoke it

Comment (gastaldi) [reply independent-projects/bootstrap/maven-resolver/src/main/java/io/quarkus/bootstrap/resolver/maven/workspace/ModelUtils.java:238]: > Wouldn't the right fix be to avoid calling the bootstrap `ModelUtils.readModel()` in `MavenProjectBuildFile`? I would expect us to use the formatting-aware one here?

There is no need to change that now. The API to read the model is the same (except that the `setPomFile` isn't invoked). Formatting only applies when persisting so we're good

Comment (gsmet) [reply independent-projects/bootstrap/maven-resolver/src/main/java/io/quarkus/bootstrap/resolver/maven/workspace/ModelUtils.java:238]: > the Model that is passed to the quarkus extension add is read here (bootstrap).

Read where? I might have missed something (it's late for me and the day has been quite full) but from what I can see, when executing the installation plan, we do it in `MavenProjectBuildFile`. And that file is not part of the bootstrap?

> There is no need to change that now. The API to read the model is the same (except that the setPomFile isn't invoked). Formatting only applies when persisting so we're good

But do we have good reasons to not be consistent and use the same API for reading and writing?
If we consume the model from the bootstrap then fine. But from what I can see, we are reading it specifically for executing the installation plan.

(Don't hesitate to push back, again, it's late and I'm tired)

Comment (gastaldi) [reply independent-projects/bootstrap/maven-resolver/src/main/java/io/quarkus/bootstrap/resolver/maven/workspace/ModelUtils.java:238]: I'm not in my computer now (replying from mobile), but I'll confirm tomorrow

Comment (gastaldi) [reply independent-projects/bootstrap/maven-resolver/src/main/java/io/quarkus/bootstrap/resolver/maven/workspace/ModelUtils.java:238]: @gsmet I've now changed the `MavenProjectBuildFile` to `MojoUtils.readPom`.

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
It looks good to me but I'd like to give it a try since apparently CI didn't catch the issue. Probably not today though.
@gastaldi did you get why our core CI missed it? IIRC you added tests so I'm surprised we didn't catch the regression.

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Tested and it works!
