### PR TITLE
Caffeine - Automatically register metrics cache impls if Micrometer is around

### LINKED ISSUE #30744: [Quarkus Native] ClassNotFoundException: com.github.benmanes.caffeine.cache.SSSW
### Describe the bug

Using the Cache API with ``caffeine`` leads to the following exception when running ``Quarkus 2.16.0.Final`` in ```native``` mode:
```
2023-01-31 13:56:54,211 ERROR [io.qua.run.Application] (main) Failed to start application (with profile [prod]): java.lang.ClassNotFoundException: com.github.benmanes.caffeine.cache.SSSW
        at java.base@17.0.5/java.lang.Class.forName(DynamicHub.java:1132)
        at java.base@17.0.5/java.lang.Class.forName(DynamicHub.java:1105)
        at com.github.benmanes.caffeine.cache.LocalCacheFactory.loadFactory(LocalCacheFactory.java:84)
        at com.github.benmanes.caffeine.cache.LocalCacheFactory.newBoundedLocalCache(LocalCacheFactory.java:40)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalAsyncCache.<init>(BoundedLocalCache.java:4216)
        at com.github.benmanes.caffeine.cache.Caffeine.buildAsync(Caffeine.java:1096)
        at io.quarkus.cache.runtime.caffeine.CaffeineCacheImpl.<init>(CaffeineCacheImpl.java:71)
        at io.quarkus.cache.runtime.caffeine.CaffeineCacheManagerBuilder$1.get(CaffeineCacheManagerBuilder.java:56)
        at io.quarkus.cache.runtime.caffeine.CaffeineCacheManagerBuilder$1.get(CaffeineCacheManagerBuilder.java:34)
        at io.quarkus.cache.CacheManager_7ace4235729bbc654ace276b403267860dc707de_Synthetic_Bean.createSynthetic(Unknown Source)
        at io.quarkus.cache.CacheManager_7ace4235729bbc654ace276b403267860dc707de_Synthetic_Bean.create(Unknown Source)
        at io.quarkus.cache.CacheManager_7ace4235729bbc654ace276b403267860dc707de_Synthetic_Bean.create(Unknown Source)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:113)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:37)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:34)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
        at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:34)
        at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:21)
        at io.quarkus.cache.CacheManager_7ace4235729bbc654ace276b403267860dc707de_Synthetic_ClientProxy.arc$delegate(Unknown Source)
        at io.quarkus.cache.CacheManager_7ace4235729bbc654ace276b403267860dc707de_Synthetic_ClientProxy.getCacheNames(Unknown Source)
        at io.quarkus.cache.runtime.CacheManagerInitializer.onStartup(CacheManagerInitializer.java:14)
        at java.base@17.0.5/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.arc.impl.Reflections.invokeMethod(Reflections.java:170)
        at io.quarkus.cache.runtime.CacheManagerInitializer_Observer_onStartup_8dc69ad76cf9cc31e6928ed65580a8d3fd18a734.notify(Unknown Source)
        at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:328)
        at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:310)
        at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:78)
        at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:131)
        at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:100)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:108)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
```

### Expected behavior

_No response_

### Actual behavior

This issue is related to the ``native`` mode only. The ``JVM`` mode is working just fine. 
It also looks like it's just an issue with ```2.16.0.Final```, with ```2.15.3.Final``` everything works as expected, even in the ``native`` mode.

### How to Reproduce?

1. Define a ``Quarkus 2.16.0.Final`` dependency
2. Add the ``@CacheResult`` annotation to an interceptable method
3. Run your app in ``native`` mode

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

openjdk 17.0.2 2022-01-18

### GraalVM version (if different from Java)

GraalVM 22.3.0 Java 17 CE

### Quarkus version or git rev

Quarkus 2.16.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn

### Additional information

The native build is conducted with the help of ``quay.io/quarkus/ubi-quarkus-native-image:22.3-java17``

### PR DESCRIPTION
**Pull request by gsmet**
Fixes #30744

### CODE REVIEW

**Comment by gsmet** [comment]
I changed the implementation a bit to keep the optimizations in place.

**Comment by geoand** [comment]
The native tests seem to not like this change :)(

File: extensions/caffeine/deployment/src/main/java/io/quarkus/caffeine/deployment/CaffeineProcessor.java [hunk 1]
```diff
@@ -49,4 +52,15 @@ void cacheLoaders(CombinedIndexBuildItem combinedIndex, BuildProducer<Reflective
     NativeImageFeatureBuildItem nativeImageFeature() {
         return new NativeImageFeatureBuildItem(CacheConstructorsFeature.class);
     }
+
+    @BuildStep(onlyIf = NativeOrNativeSourcesBuild.class)
+    NativeImageSystemPropertyBuildItem registerRecordStatsImplementationsIfMicrometerAround(
+            MetricsCapabilityBuildItem metricsCapability) {
```
Comment (gwenneg) [inline extensions/caffeine/deployment/src/main/java/io/quarkus/caffeine/deployment/CaffeineProcessor.java:58]: This may help fix the native tests:
```suggestion
            Optional<MetricsCapabilityBuildItem> metricsCapability) {
```

Comment (gsmet) [reply extensions/caffeine/deployment/src/main/java/io/quarkus/caffeine/deployment/CaffeineProcessor.java:58]: Ah... yes... I tested the case exercising the new code but didn't test the other modules where Micrometer is not around...

File: extensions/caffeine/runtime/src/main/java/io/quarkus/caffeine/runtime/graal/CacheConstructorsFeature.java [hunk 2]
```diff
@@ -82,4 +93,16 @@ public static String[] typesNeedingConstructorsRegistered() {
...
+    public static String[] typesNeedingConstructorsRegisteredWhenRecordingStats() {
+        return new String[] {
+                "com.github.benmanes.caffeine.cache.SILSMS",
+                "com.github.benmanes.caffeine.cache.SSSA",
+                "com.github.benmanes.caffeine.cache.SSLSA",
+                "com.github.benmanes.caffeine.cache.SSLSMS",
+                "com.github.benmanes.caffeine.cache.SSSMS",
+                "com.github.benmanes.caffeine.cache.SSSMSA",
+                "com.github.benmanes.caffeine.cache.SSSMSW",
+                "com.github.benmanes.caffeine.cache.SSSW"
```
Comment (gwenneg) [inline extensions/caffeine/runtime/src/main/java/io/quarkus/caffeine/runtime/graal/CacheConstructorsFeature.java:105]: @ben-manes Could you please confirm that this list contains all caches that should be registered for reflection when the cache metrics are enabled?

**Review by gwenneg — APPROVED** [review]
I don't know Caffeine caches well enough to say if the new list contains everything it should.

Other than that, LGTM. Thanks!

File: extensions/caffeine/runtime/src/main/java/io/quarkus/caffeine/runtime/graal/CacheConstructorsFeature.java (hunk 2 above)
Comment (gsmet) [reply extensions/caffeine/runtime/src/main/java/io/quarkus/caffeine/runtime/graal/CacheConstructorsFeature.java:105]: FWIW, it doesn't contain all of them. But I think it contains all the ones corresponding to the ones we already have.

Comment (gwenneg) [reply extensions/caffeine/runtime/src/main/java/io/quarkus/caffeine/runtime/graal/CacheConstructorsFeature.java:105]: How did you determine which ones we need?

Comment (ben-manes) [reply extensions/caffeine/runtime/src/main/java/io/quarkus/caffeine/runtime/graal/CacheConstructorsFeature.java:105]: If possible, you might write a unit test to assert that the bundled configurations work in native image. I don't know the class mappings offhand as it is done by logic and a test would avoid regressions if the listing became stale. 

I use Guava's `Sets.cartesianProduct(features)` which has a 2^n growth rate, so each new feature might double the class listings. In reality that is pruned down by reusing classes if they match the required data shape, e.g. an entry with key/value/timestamp can share a single class by either expireAfterAccess, expireAfterWrite, or variable expiration configurations. Caffeine's unit tests likewise use this cartesian product trick for parameterized tests to avoid regressions as features can interact in subtle ways.
