### PR TITLE
Adapt locales support for GraalVM >= 24.2

### LINKED ISSUE #43436: Locales Some integration test fails with GraalVM for JDK 24
### Describe the bug

Starting with GraalVM for JDK 24 (24.2) native image will no longer set the locale default at build time. See https://github.com/oracle/graal/pull/9694. This apparently breaks the Locale Some integration test of Quarkus.

See https://github.com/graalvm/mandrel/issues/755#issuecomment-2367117119

### Expected behavior

The test should pass

### Actual behavior

The test fails with errors like the following:

```
 Error:  Tests run: 20, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 6.895 s <<< FAILURE! -- in io.quarkus.locales.it.LocalesIT
Error:  io.quarkus.locales.it.LocalesIT.testCurrencies(String, String, String)[3] -- Time elapsed: 0.033 s <<< FAILURE!
java.lang.AssertionError: 
1 expectation failed.
Response body doesn't match expectation.
Expected: is "česká koruna"
  Actual: Czech Republic Koruna
```

See https://github.com/graalvm/mandrel/actions/runs/10985696189/job/30498542041#step:12:3093

### How to Reproduce?

1. Build GraalVM for JDK 24
2. Run `locales/some` integration test in native mode

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Mandrel or GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

The regression is introduced by https://github.com/oracle/graal/pull/9694

### PR DESCRIPTION
**Pull request by zakkak**
Starting with GraalVM for JDK 24 (24.2) native image will no longer set the locale default at build time. As a result, the default locale won't be included by default in the native image unless explicitly specified and it will also not be set implicitly.

As discussed in https://github.com/quarkusio/quarkus/discussions/43533#discussioncomment-10797019 this PR updates the locales support so that:

- [x] if neither `quarkus.locales` nor `quarkus.default-locale` is set, the Quarkus applications should default to English (`en_US`), instead of the build systems locale (which is the current behavior), at run-time.
- [X] if `quarkus.default-locale` is set but `quarkus.locales` is not set, then we should only include the locale `quarkus.default-locale` is set to. This is the current behavior with GraalVM for JDK 21.
- [X] if both `quarkus.default-locale` and `quarkus.locales` are set, then we should include only the locales from `quarkus.locales` and the one from `quarkus.default-locale` (this is the current behavior).
- [X] if `quarkus.locales` is set but `quarkus.default-locale` is not set, then we should include only the locales from `quarkus.locales` and default to English, instead of the build systems locale (which is the current behavior), at run-time (similarly to point 1).
- [x] if `quarkus.default-locale` (which is build time fixed) is set, it is used to set the default `user.language` and `user.country` values at run-time, while users may still override them. 

For points 2 and 3 starting with graalVM for JDK 24 we will also include `en_US` which shouldn't be a big issue as mentioned in https://github.com/quarkusio/quarkus/discussions/43533#discussioncomment-10795928,

> [!CAUTION]
> Point 1 changes the current behavior, meaning we need to clearly document and communicate it.

The PR also updates the Locales integration tests accordingly.

See https://github.com/oracle/graal/pull/9694

Closes https://github.com/quarkusio/quarkus/issues/43436

Depends on https://github.com/quarkusio/quarkus/pull/43696

### CODE REVIEW

**Review by jerboaa — COMMENTED** [review]
Looks good. Should we amend the doc in `LocalesBuildTimeConfig` for `defaultLocale`. It currently mentions:

```
quarkus.default-locale

Default locale that can be consumed by the extensions.
The locale must be specified in the IETF BCP 47 format e.g. en-US or fr-FR.
For instance, the Hibernate Validator extension makes use of it.
Native-image build uses this property to derive user.language and user.country for the application’s runtime.
```

See: https://quarkus.io/guides/all-config

**Comment by zakkak** [comment]
Good point. I will update the doc and fix the style issue tomorrow.

**Comment by zakkak** [comment]
> Good point. I will update the doc and fix the style issue tomorrow.

Done, I also ended up moving the changes in `core/deployment/src/main/java/io/quarkus/deployment/steps/LocaleProcessor.java` where they seem to belong. Please have another look.

**Review by geoand — APPROVED** [review]

File: integration-tests/locales/some/src/test/java/io/quarkus/locales/it/LocalesIT.java [hunk 1]
```diff
@@ -94,6 +98,21 @@ public void testDefaultLocale() {
...
+    @Test
+    @DisableIfBuiltWithGraalVMOlderThan(value = GraalVMVersion.GRAALVM_24_2_0)
+    public void testDefaultLocaleAfter24_1() {
+        RestAssured.given().when()
+                .get("/default/de-CH")
+                .then()
+                .statusCode(HttpStatus.SC_OK)
+                /*
+                 * "Schweiz" is the correct name for Switzerland in German.
+                 * German is the default language as per the application.properties.
```
Comment (jerboaa) [inline integration-tests/locales/some/src/test/java/io/quarkus/locales/it/LocalesIT.java:110]:
```suggestion
                 * "Schweiz" is the correct name for Switzerland in German.
                 * German is the default language as per the `quarkus.test.arg-line` in application.properties.
```

File: core/deployment/src/main/java/io/quarkus/deployment/steps/LocaleProcessor.java [hunk 2]
```diff
@@ -139,13 +139,13 @@ public static String nativeImageIncludeLocales(NativeConfig nativeConfig, Locale
             return "all";
         }
 
-        // We subtract what we already declare for native-image's user.language or user.country.
+        // Ensure the default locale is included to ensure compatibility with GraalVM for JDK 24, which doesn't set the locale at build-time.
```
Comment (jerboaa) [inline core/deployment/src/main/java/io/quarkus/deployment/steps/LocaleProcessor.java:142]:
```suggestion
        // GraalVM for JDK 24 doesn't include the default locale used at build time. We must explicitly include all
        // locales - including the build-time locale. This might include more locales than necessary for older GraalVM
        // versions, but should be mostly OK.
```

File: core/deployment/src/main/java/io/quarkus/deployment/steps/LocaleProcessor.java [hunk 3]
```diff
@@ -139,13 +139,13 @@ public static String nativeImageIncludeLocales(NativeConfig nativeConfig, Locale
...
+        additionalLocales.add(localesBuildTimeConfig.defaultLocale);
         // Note the deprecated options still count.
-        additionalLocales.remove(localesBuildTimeConfig.defaultLocale);
         if (nativeConfig.userCountry().isPresent() && nativeConfig.userLanguage().isPresent()) {
-            additionalLocales.remove(new Locale(nativeConfig.userLanguage().get(), nativeConfig.userCountry().get()));
+            additionalLocales.add(new Locale(nativeConfig.userLanguage().get(), nativeConfig.userCountry().get()));
         } else if (nativeConfig.userLanguage().isPresent()) {
-            additionalLocales.remove(new Locale(nativeConfig.userLanguage().get()));
+            additionalLocales.add(new Locale(nativeConfig.userLanguage().get()));
         }
```
[the remark this answers is not in the document]
Comment (zakkak) [reply core/deployment/src/main/java/io/quarkus/deployment/steps/LocaleProcessor.java:149]: Yes, I intentionally went with this to be on the safe side. If the user sets both
`quarkus.default-locale` and the deprecated `quarkus.native.user-language` I would prefer them to be able to use both at run-time even if that slightly increases the image size. After all they shouldn't be using both in the first place, maybe we could add a warning about that (let me see what I can do about it). Currently, the deprecated locale takes precedence so if we want to keep the same "semantics" we should drop the `default-locale`, which I am OK with if we throw a warning.

[the remark this answers is not in the document]
Comment (zakkak) [reply core/deployment/src/main/java/io/quarkus/deployment/steps/LocaleProcessor.java:149]: Oh we actually do print a warning about it...

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/NativeConfig.java [hunk 4]
```diff
@@ -88,7 +88,8 @@ public interface NativeConfig {
 
     /**
      * Defines the user language used for building the native executable.
-     * It also serves as the default Locale language for the native executable application runtime.
+     * With GraalVM versiond prior to GraalVM for JDK 24 it also serves as the default Locale language for the native executable
```
Comment (gsmet) [inline core/deployment/src/main/java/io/quarkus/deployment/pkg/NativeConfig.java:91]:
```suggestion
     * With GraalVM versions prior to GraalVM for JDK 24, it also serves as the default Locale language for the native executable
```

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/NativeConfig.java [hunk 5]
```diff
@@ -100,7 +101,8 @@ public interface NativeConfig {
 
     /**
      * Defines the user country used for building the native executable.
-     * It also serves as the default Locale country for the native executable application runtime.
+     * With GraalVM versiond prior to GraalVM for JDK 24 it also serves as the default Locale country for the native executable
```
Comment (gsmet) [inline core/deployment/src/main/java/io/quarkus/deployment/pkg/NativeConfig.java:104]:
```suggestion
     * With GraalVM versions prior to GraalVM for JDK 24, it also serves as the default Locale country for the native executable
```

**Review by gsmet — CHANGES_REQUESTED** [review]
Spotted a typo in the config doc, other than that it looks good, thanks!

File: core/deployment/src/main/java/io/quarkus/deployment/steps/LocaleProcessor.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (jerboaa) [reply core/deployment/src/main/java/io/quarkus/deployment/steps/LocaleProcessor.java:149]: OK. Please consider the suggested changes to the comments.

File: core/runtime/src/main/java/io/quarkus/runtime/LocalesBuildTimeConfig.java [hunk 6]
```diff
@@ -44,7 +44,8 @@ public class LocalesBuildTimeConfig {
      * For instance, the Hibernate Validator extension makes use of it.
      * <p>
      * Native-image build uses this property to derive {@code user.language} and {@code user.country} for the application's
-     * runtime.
+     * runtime. Starting with GraalVM for JDK 24 this option will not result in setting the default runtime locale, and
+     * any usages of it should be re-evaluated.
      */
     @ConfigItem(defaultValue = DEFAULT_LANGUAGE + "-" + DEFAULT_COUNTRY, defaultValueDocumentation = "Build system locale")
```
[the remark this answers is not in the document]
Comment (zakkak) [reply core/runtime/src/main/java/io/quarkus/runtime/LocalesBuildTimeConfig.java:50]: > * System default locale at image runtime with GraalVM for JDK 24 and better

Note that this is not enforced though, i.e., if we compile with `-Dquarkus.default-locale=cs-CZ` we will still have to pass `-Duser.language=cs` and/or `-Duser.country=CZ` at runtime. Note that passing `-Dquarkus.default-locale=cs-CZ` won't do the trick as it's considered build-time fixed, which I guess I need to fix as well.

I added a new test for this ^

[the remark this answers is not in the document]
Comment (zakkak) [reply core/runtime/src/main/java/io/quarkus/runtime/LocalesBuildTimeConfig.java:50]: @gsmet any suggestions on how to approach this? To my understanding `quarkus.default-locale` should move to `RUN_TIME` config phase starting with GraalVM for JDK 24.

File: core/deployment/src/main/java/io/quarkus/deployment/steps/LocaleProcessor.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (zakkak) [reply core/deployment/src/main/java/io/quarkus/deployment/steps/LocaleProcessor.java:149]: :+1: I have applied most of them, just not pushing till I figure out what to do with https://github.com/quarkusio/quarkus/pull/43448#discussion_r1773253009 as well

File: core/runtime/src/main/java/io/quarkus/runtime/LocalesBuildTimeConfig.java (hunk 6 above)
[the remark this answers is not in the document]
Comment (gsmet) [reply core/runtime/src/main/java/io/quarkus/runtime/LocalesBuildTimeConfig.java:50]: Hum, I'm not sure we have a good way to achieve that. We moved some build time properties to runtime but it was an all or nothing thing.

I think we will have to keep it build time until we officially switch to a GraalVM/Mandrel version that is 24+.

Except if @radcortez comes up with some crazy ideas but I'm not entirely sure it's worth the hassle if we can live with it for now.

File: integration-tests/locales/some/src/test/java/io/quarkus/locales/it/LocalesIT.java (hunk 1 above)
Comment (Karm) [reply integration-tests/locales/some/src/test/java/io/quarkus/locales/it/LocalesIT.java:110]: +1 for mentioning the directive that is supposed to cause this change in behaviour

File: integration-tests/locales/some/src/test/resources/application.properties [hunk 7]
```diff
@@ -3,3 +3,4 @@ quarkus.locales=de,fr-FR,ja,uk-UA
 # used in your application properties. This test uses it only to verify compatibility.
 quarkus.native.user-language=cs
 quarkus.default-locale=en-US
+quarkus.test.arg-line=-Duser.language=de
```
Comment (Karm) [inline integration-tests/locales/some/src/test/resources/application.properties:6]: @zakkak Does it mean the user language  cs is ignored and should not be available in this case? Could you call https://github.com/quarkusio/quarkus/blob/main/integration-tests/locales/app/src/main/java/io/quarkus/locales/it/LocalesResource.java#L27 in > 24.2 test too then?

**Review by Karm — CHANGES_REQUESTED** [review]
Thx.

I'd add a test for 24.2 to see what happened with the "old" prop.
Other than that the only concern is Hibernate Validator and if it can handle that.

File: core/runtime/src/main/java/io/quarkus/runtime/LocalesBuildTimeConfig.java (hunk 6 above)
[the remark this answers is not in the document]
Comment (radcortez) [reply core/runtime/src/main/java/io/quarkus/runtime/LocalesBuildTimeConfig.java:50]: Mappings allow you to map the same property for both build and runtime. It can either be done by another mapping, or just by registering the `LocalesBuildTimeConfig` in the runtime config customizer. 

We had a similar case with logging:
https://github.com/quarkusio/quarkus/pull/42157

[the remark this answers is not in the document]
Comment (jerboaa) [reply core/runtime/src/main/java/io/quarkus/runtime/LocalesBuildTimeConfig.java:50]: > > * System default locale at image runtime with GraalVM for JDK 24 and better
> 
> Note that this is not enforced though, i.e., if we compile with `-Dquarkus.default-locale=cs-CZ` we will still have to pass `-Duser.language=cs` and/or `-Duser.country=CZ` at runtime. Note that passing `-Dquarkus.default-locale=cs-CZ` won't do the trick as it's considered build-time fixed, which I guess I need to fix as well.
> 
> I added a new test for this ^

I'm not sure I follow. What I meant is that the native image follows the system locale at runtime. Yeah it's no longer build-time static (the default locale). For latest GraalVM master I see this. Test with `Locale.getDefault()` in a native image.

On `de-AT` locale:
```
$ localectl status
System Locale: LANG=de_AT.UTF-8
    VC Keymap: us
   X11 Layout: us
    X11 Model: pc105
$ ./locale-test-24 
Default locale: de_AT
```

On `en-US` locale:
```
$ localectl status
System Locale: LANG=en_US.UTF-8
    VC Keymap: us
   X11 Layout: us
$ ./locale-test-24 
Default locale: en_US
```

So with GraalVM for JDK 24, native images behave more like `java` would.

File: core/deployment/src/main/java/io/quarkus/deployment/steps/LocaleProcessor.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (jerboaa) [reply core/deployment/src/main/java/io/quarkus/deployment/steps/LocaleProcessor.java:149]: OK.

File: integration-tests/locales/some/src/test/resources/application.properties (hunk 7 above)
Comment (jerboaa) [reply integration-tests/locales/some/src/test/resources/application.properties:6]: AFAIK, it'll be available since `cs` is being added as an additional locale. The difference to Mandrel for JDK 23 is that you can no longer fix the default locale at build time. If you want a fixed locale the image needs `-Duser.language=cs` passed at runtime to fix it to `cs`.

**Comment by zakkak** [comment]
> I'd add a test for 24.2 to see what happened with the "old" prop. 

Can you elaborate on that? What is the "old" prop? I added a new test to test the default locale when not using `quarkus.test.arg-line`, is that what you mean?

**Comment by jerboaa** [comment]
> I added (but didn't push yet) a new test to test the default locale when not using `quarkus.test.arg-line`, is that what you mean?

Sounds flaky, as it would depend on the system locale at runtime.

**Comment by zakkak** [comment]
> Sounds flaky, as it would depend on the system locale at runtime.

Yes, in the "new" approach were the locale is set at run-time instead of build-time we will probably need to set the locale at build time to something really exotic and just confirm that it's not used by default at run-time.

**Comment by jerboaa** [comment]
> > Sounds flaky, as it would depend on the system locale at runtime.
> 
> Yes, in the "new" approach were the locale is set at run-time instead of build-time we will probably need to set the locale at build time to something really exotic and just confirm that it's not used by default at run-time.

OK, fair enough.

File: core/runtime/src/main/java/io/quarkus/runtime/LocalesBuildTimeConfig.java (hunk 6 above)
[the remark this answers is not in the document]
Comment (zakkak) [reply core/runtime/src/main/java/io/quarkus/runtime/LocalesBuildTimeConfig.java:50]: Exactly, which means that `defaultLocale` currently has no effect at the native-image starting with GraalVM for JDK 24 (other than including the locale in the image). I am starting to believe that the best thing to do is to print a warning saying that `defaultLocale` is ignored (when using GraalVM for JDK 24) and deprecate it once GraalVM for JDK 25 is out.

I think adding the default locale to the list of included locales is still a good thing to do.

File: core/deployment/src/main/java/io/quarkus/deployment/steps/LocaleProcessor.java (hunk 2 above)
Comment (zakkak) [reply core/deployment/src/main/java/io/quarkus/deployment/steps/LocaleProcessor.java]: > This might include more locales than necessary for older GraalVM versions, but should be mostly OK.
        
I think that's not true. The default locale is/was included by default with older versions as well (due to the static analysis considering it reachable AFAIU)

I updated the doc excluding this part.

File: core/deployment/src/main/java/io/quarkus/deployment/steps/LocaleProcessor.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (zakkak) [reply core/deployment/src/main/java/io/quarkus/deployment/steps/LocaleProcessor.java]: Switched to only including one of the `default-locale` or `native.user-language` (preferring the latter).

File: integration-tests/locales/default/src/test/java/io/quarkus/locales/it/LocalesIT.java [hunk 8]
```diff
@@ -0,0 +1,84 @@
...
+ * For example, this package satisfies the dependency on a RHEL 9 type of OS: glibc-all-langpacks
+ */
+@QuarkusIntegrationTest
+public class LocalesIT {
+
+    private static final Logger LOG = Logger.getLogger(LocalesIT.class);
+
+    @Test
+    @DisableIfBuiltWithGraalVMNewerThan(value = GraalVMVersion.GRAALVM_24_1_0)
+    public void testDefaultLocaleBefore24_2() {
```
Comment (jerboaa) [inline integration-tests/locales/default/src/test/java/io/quarkus/locales/it/LocalesIT.java:32]:
```suggestion
    public void testDefaultLocaleBefore24_2_0() {
```

File: integration-tests/locales/default/src/test/java/io/quarkus/locales/it/LocalesIT.java [hunk 9]
```diff
@@ -0,0 +1,84 @@
...
+                 * "l-Iżvizzera" is the correct name for Switzerland in Maltese language.
+                 * Maltese is the default language as per quarkus.default-locale=mt-MT.
+                 */
+                .body(is("l-Iżvizzera"))
+                .log().all();
+    }
+
+    @Test
+    @DisableIfBuiltWithGraalVMOlderThan(value = GraalVMVersion.GRAALVM_24_2_0)
+    public void testDefaultLocaleAfter24_1() {
```
Comment (jerboaa) [inline integration-tests/locales/default/src/test/java/io/quarkus/locales/it/LocalesIT.java:47]:
```suggestion
    public void testDefaultLocale24_2_0Plus() {
```

File: integration-tests/locales/default/src/test/java/io/quarkus/locales/it/LocalesIT.java [hunk 10]
```diff
@@ -0,0 +1,84 @@
...
+        RestAssured.given().when()
+                .get("/default/de-CH")
+                .then()
+                .statusCode(HttpStatus.SC_OK)
+                /*
+                 * "l-Iżvizzera" is the correct name for Switzerland in Maltese language.
+                 * Maltese is the default build-time language as per quarkus.default-locale=mt-MT, but not at run-time.
+                 * Note that this test will fail if the default run-time language is Maltese on the test machine,
+                 * this is unfortunate but also unlikely given the small population of Malta.
```
Comment (jerboaa) [inline integration-tests/locales/default/src/test/java/io/quarkus/locales/it/LocalesIT.java:56]: :-)

File: integration-tests/locales/some/src/test/java/io/quarkus/locales/it/LocalesIT.java [hunk 11]
```diff
@@ -81,7 +84,8 @@ public void testTimeZones(String zone, String language, String name) {
     }
 
     @Test
-    public void testDefaultLocale() {
+    @DisableIfBuiltWithGraalVMNewerThan(value = GraalVMVersion.GRAALVM_24_1_0)
+    public void testDefaultLocaleBefore24_2() {
```
Comment (jerboaa) [inline integration-tests/locales/some/src/test/java/io/quarkus/locales/it/LocalesIT.java:88]:
```suggestion
    public void testDefaultLocaleBefore24_2_0() {
```

File: integration-tests/locales/some/src/test/java/io/quarkus/locales/it/LocalesIT.java [hunk 12]
```diff
@@ -94,6 +98,21 @@ public void testDefaultLocale() {
                 .log().all();
     }
 
+    @Test
+    @DisableIfBuiltWithGraalVMOlderThan(value = GraalVMVersion.GRAALVM_24_2_0)
+    public void testDefaultLocaleAfter24_1() {
```
Comment (jerboaa) [inline integration-tests/locales/some/src/test/java/io/quarkus/locales/it/LocalesIT.java:103]:
```suggestion
    public void testDefaultLocale24_2_0Plus() {
```

**Review by jerboaa — APPROVED** [review]
LGTM. Minor nits. Feel free to take the suggestions or leave it as is. Up to you.

**Comment by zakkak** [comment]
> LGTM. Minor nits. Feel free to take the suggestions or leave it as is. Up to you.

Thanks for the review @jerboaa!

I (unsuccessfully) tried sticking to [the existing _naming convention_](https://github.com/quarkusio/quarkus/blob/4f6c97e71d6db8455438e4aebd50478561af71bd/integration-tests/main/src/test/java/io/quarkus/it/main/RegisterForReflectionITCase.java#L61-L75). I will rename them if more changes are requested.

File: core/runtime/src/main/java/io/quarkus/runtime/LocalesBuildTimeConfig.java (hunk 6 above)
[the remark this answers is not in the document]
Comment (zakkak) [reply core/runtime/src/main/java/io/quarkus/runtime/LocalesBuildTimeConfig.java]: @gsmet @Karm WDYT about:

> I am starting to believe that the best thing to do is to print a warning saying that `defaultLocale` is ignored (when using GraalVM for JDK 24) and deprecate it once GraalVM for JDK 25 is out.

**Comment by geoand** [comment]
Where are we with this?

At the very least, it needs a rebase on `main`

**Comment by zakkak** [comment]
It's not clear yet how we should handle this (see https://github.com/quarkusio/quarkus/discussions/43533) so I think I will rebase to resolve the conflicts and only make the tests not fail for the time being. Once we reach a consensus in https://github.com/quarkusio/quarkus/discussions/43533 we can follow up with the proper fix.

**Comment by geoand** [comment]
🙏🏽

**Comment by zakkak** [comment]
> I think I will rebase to resolve the conflicts and only make the tests not fail for the time being. Once we reach a consensus in https://github.com/quarkusio/quarkus/discussions/43533 we can follow up with the proper fix.

Done in https://github.com/quarkusio/quarkus/pull/43604 and switched this PR to draft so that I can use it for the "follow up" in order to have all the history in one place.

File: core/runtime/src/main/java/io/quarkus/runtime/LocalesBuildTimeConfig.java [hunk 13]
```diff
@@ -44,8 +45,10 @@ public class LocalesBuildTimeConfig {
      * For instance, the Hibernate Validator extension makes use of it.
      * <p>
      * Native-image build uses this property to derive {@code user.language} and {@code user.country} for the application's
+     * runtime. Starting with GraalVM for JDK 24 {@code user.language} and {@code user.country} can also be overridden at
      * runtime.
```
Comment (jerboaa) [inline core/runtime/src/main/java/io/quarkus/runtime/LocalesBuildTimeConfig.java:49]:
```suggestion
     * runtime. Starting with GraalVM for JDK 24 {@code user.language} and {@code user.country} can also be overridden at
     * runtime, provided the selected locale was included at image build time.
```

File: core/runtime/src/main/java/io/quarkus/runtime/LocalesBuildTimeConfig.java (hunk 6 above)
[the remark this answers is not in the document]
Comment (zakkak) [reply core/runtime/src/main/java/io/quarkus/runtime/LocalesBuildTimeConfig.java:54]: @radcortez I made `defaultLocale` an `Optional` and thus removed the `defaultValue` from its annotation, but that resulted in the following exception:

```
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.Set.contains(Object)" because "this.val$localesBuildTimeConfig.locales" is null
	at io.quarkus.hibernate.validator.runtime.HibernateValidatorRecorder$2.created(HibernateValidatorRecorder.java:87)
	at io.quarkus.arc.runtime.ArcRecorder.initBeanContainer(ArcRecorder.java:80)
	at io.quarkus.deployment.steps.ArcProcessor$notifyBeanContainerListeners1304312071.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.ArcProcessor$notifyBeanContainerListeners1304312071.deploy(Unknown Source)
	... 42 more
```

See https://github.com/zakkak/quarkus/actions/runs/11203768674/job/31141630432#step:16:636

Note that the field it's complaining about is the `locales` one (which I didn't change and I kept its `defaultValue`) and not the `defaultLocale`.

Is that expected behavior? Am I missing some configuration?

File: integration-tests/locales/some/src/test/java/io/quarkus/locales/it/LocalesIT.java [hunk 14]
```diff
@@ -88,23 +83,38 @@ public void testTimeZones(String zone, String language, String name) {
...
-    @DisableIfBuiltWithGraalVMNewerThan(value = GraalVMVersion.GRAALVM_24_1_0)
-    public void testDefaultLocale() {
+    @DisableIfBuiltWithGraalVMNewerThan(value = GraalVMVersion.GRAALVM_24_1_999)
+    public void testDefaultLocalePre24_2() {
         RestAssured.given().when()
                 .get("/default/de-CH")
                 .then()
                 .statusCode(HttpStatus.SC_OK)
                 /*
+                 * Prior to GraalVM 24.2, the locale could not be changes at runtime.
```
Comment (jerboaa) [inline integration-tests/locales/some/src/test/java/io/quarkus/locales/it/LocalesIT.java:94]:
```suggestion
                 * Prior to GraalVM 24.2, the locale could not be changed at runtime.
```

**Review by jerboaa — APPROVED** [review]

**Review by Karm — APPROVED** [review]
@zakkak I'm glad for the updated tests :+1:  AFAIK all our GHA executors have `LANG: en_US.UTF-8` set. 
I'm gonna try vanilla Windows.

**Comment by Karm** [comment]
@zakkak  et al. https://ci.modcluster.io/view/Mandrel/job/mandrel-windows-quarkus-subset/ 
i.e. all three combinations that make sense passed O.K. on normal Windows servers with your branch, running:

 * https://ci.modcluster.io/view/Mandrel/job/mandrel-windows-quarkus-subset/JDK_RELEASE=ga,JDK_VERSION=21,LABEL=w2k19,MANDREL_BUILD=mandrel-23-1-windows-build-matrix,QUARKUS_VERSION=2024-09-23-fix-43436/
 * https://ci.modcluster.io/view/Mandrel/job/mandrel-windows-quarkus-subset/JDK_RELEASE=ga,JDK_VERSION=23,LABEL=w2k19,MANDREL_BUILD=mandrel-24-1-windows-build-matrix,QUARKUS_VERSION=2024-09-23-fix-43436/
 * https://ci.modcluster.io/view/Mandrel/job/mandrel-windows-quarkus-subset/JDK_RELEASE=ea,JDK_VERSION=24,LABEL=w2k19,MANDREL_BUILD=mandrel-master-windows-build-matrix,QUARKUS_VERSION=2024-09-23-fix-43436/

**Comment by zakkak** [comment]
@gsmet is there anything blocking this?

**Comment by gsmet** [comment]
Just the Devoxx train :). I'll have a look this week as I need some quality time to fully understand the consequences.

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
@zakkak LGTM, I pinged you on Zulip to clarify the HV potential issues mentioned here. If there's nothing concerning left, we can merge.

**Comment by zakkak** [comment]
@gsmet I guess you are referring to @Karm's comment

> Other than that the only concern is Hibernate Validator and if it can handle that.

TBH I don't fully grasp what it does, but [made sure to include a test](https://github.com/quarkusio/quarkus/pull/43448/files#diff-98562d41643311e5f55f5b9d456e58b0944d7f2c41069a586814f3cad891ff4fR37-R59) (hopefully testing the right thing) which seems to pass. @Karm seems happy with the new tests and the CI passing so if no one else has some specific concern about Hibernate Validator I guess we are good to go.

File: core/runtime/src/main/java/io/quarkus/runtime/LocalesBuildTimeConfig.java [hunk 15]
```diff
@@ -44,8 +45,12 @@ public class LocalesBuildTimeConfig {
...
-     * runtime.
+     * runtime. Starting with GraalVM for JDK 24 {@code user.language} and {@code user.country} can also be overridden at
+     * runtime, provided the selected locale was included at image build time.
+     * <p>
+     * Defaults to the JVM's default locale if not set. Starting with GraalVM for JDK 24, it defaults to {@code en-US}
+     * for native executables.
      */
     @ConfigItem(defaultValue = DEFAULT_LANGUAGE + "-" + DEFAULT_COUNTRY, defaultValueDocumentation = "Build system locale")
-    public Locale defaultLocale;
+    public Optional<Locale> defaultLocale;
```
Comment (gsmet) [inline core/runtime/src/main/java/io/quarkus/runtime/LocalesBuildTimeConfig.java:55]: You make it optional but you still have a `defaultValue` set so I fail to see when it's going to be empty?

You're mentioning an Hibernate Validator issue but it looks like you fixed it? Maybe you forgot to drop it afterwards?

Comment (zakkak) [reply core/runtime/src/main/java/io/quarkus/runtime/LocalesBuildTimeConfig.java:55]: Fixed with https://github.com/quarkusio/quarkus/pull/43448/commits/0ea1c6b63a00a491575a4d0da2c01d8cadc6d5cc PTAL (I will squash once you are OK with the changes and CI passes)

File: core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageFeatureStep.java [hunk 16]
```diff
@@ -118,6 +112,22 @@ public void write(String s, byte[] bytes) {
                 greaterEqual24_2.invokeStaticMethod(REGISTER_RUNTIME_SYSTEM_PROPERTIES,
                         greaterEqual24_2.load("user.language"),
                         greaterEqual24_2.load("en"));
+            }
+        }
+        // The deprecated option takes precedence for users who are already using it.
+        if (nativeConfig.userCountry().isPresent()) {
```
Comment (gsmet) [inline core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageFeatureStep.java:118]: Why exactly did you change that? Because for me, either you use the deprecated `nativeConfig.userLanguage` and then you also use `nativeConfig.userCountry` or you're using the new stuff.

I think the previous way of doing things was perfectly fine.

File: core/runtime/src/main/java/io/quarkus/runtime/LocalesBuildTimeConfig.java [hunk 17]
```diff
@@ -51,6 +51,6 @@ public class LocalesBuildTimeConfig {
      * Defaults to the JVM's default locale if not set. Starting with GraalVM for JDK 24, it defaults to {@code en-US}
      * for native executables.
```
Comment (gsmet) [inline core/runtime/src/main/java/io/quarkus/runtime/LocalesBuildTimeConfig.java:52]: I think this probably should be in `defaultValueDocumentation`.

**Review by gsmet — COMMENTED** [review]
I'm not sure I understand all the changes you made thus why I asked questions.

File: core/runtime/src/main/java/io/quarkus/runtime/LocalesBuildTimeConfig.java (hunk 17 above)
Comment (zakkak) [reply core/runtime/src/main/java/io/quarkus/runtime/LocalesBuildTimeConfig.java:52]: But can we have a `defaultValudeDocumentation` without a `defaultValue`?

File: core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageFeatureStep.java (hunk 16 above)
Comment (zakkak) [reply core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageFeatureStep.java:118]: In the previous version we would only respect userCountry if userLanguage was also used. With the new version the behavior is more consistent with the existing one https://github.com/quarkusio/quarkus/blob/2efe0aa43c0aeb55818d5077f2c52e61e531c0b3/core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java#L750-L757 and https://github.com/quarkusio/quarkus/blob/c025a1b29c02b6a4b8b773d6041c9e50119147a0/core/deployment/src/main/java/io/quarkus/deployment/steps/LocaleProcessor.java#L89-L124

Comment (zakkak) [reply core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageFeatureStep.java:118]: In other words this change is indeed not necessary to address your comment, but I feel like it's an improvement. Happy to revert if you prefer it the previous way.

File: core/runtime/src/main/java/io/quarkus/runtime/LocalesBuildTimeConfig.java (hunk 17 above)
Comment (zakkak) [reply core/runtime/src/main/java/io/quarkus/runtime/LocalesBuildTimeConfig.java]: Fixed.

Comment (gsmet) [reply core/runtime/src/main/java/io/quarkus/runtime/LocalesBuildTimeConfig.java]: @zakkak sorry, missed your question: yes you can, we use that a lot.

File: core/runtime/src/main/java/io/quarkus/runtime/LocalesBuildTimeConfig.java (hunk 15 above)
Comment (gsmet) [reply core/runtime/src/main/java/io/quarkus/runtime/LocalesBuildTimeConfig.java:56]: Ideally, you can remove the sentence starting with `Defaults to...` in the main javadoc as the `defaultValueDocumentation` will be printed in the doc.

Anyway, looks good to me. I let you squash things as you see fit and then we can merge!

**Review by gsmet — APPROVED** [review]

**Comment by Karm** [comment]
@zakkak  In the light of #43997, could you make sure those tests actually all run with the native executable in CI, please?

**Comment by zakkak** [comment]
> @zakkak In the light of #43997, could you make sure those tests actually all run with the native executable in CI, please?

Yes, you can see them running here https://github.com/quarkusio/quarkus/actions/runs/11401583858/job/31725538105?pr=43448#step:16:2568

**Comment by zakkak** [comment]
Squashed and rebased.

**Comment by gsmet** [comment]
@karesti the `InfinispanCacheTest` has been failing a few times lately with this exact error, could you have a look?

@mariofusco I have also seen this `ReflectionFreeSerializationTest` failing a few times lately, always with this error.

**Comment by zakkak** [comment]
FTR the change has been documented in the migration guide for 3.17 here https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.17#locales

**Comment by karesti** [comment]
@gsmet created the issue  https://github.com/quarkusio/quarkus/issues/44127
