### PR TITLE
Fix org.apache.kafka.common.utils.Crc32C substitution with JDK 11

### LINKED ISSUE #6009: quarkus-integration-test-kafka build fails in native mode with JDK 11
**Describe the bug**
```
[INFO] --- quarkus-maven-plugin:999-SNAPSHOT:native-image (native-image) @ quarkus-integration-test-kafka ---
[INFO] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Building native image source jar: /Users/Gwenneg/git/quarkus/integration-tests/kafka/target/quarkus-integration-test-kafka-999-SNAPSHOT-native-image-source-jar/quarkus-integration-test-kafka-999-SNAPSHOT-runner.jar
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Building native image from /Users/Gwenneg/git/quarkus/integration-tests/kafka/target/quarkus-integration-test-kafka-999-SNAPSHOT-native-image-source-jar/quarkus-integration-test-kafka-999-SNAPSHOT-runner.jar
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on GraalVM Version 19.3.0 CE
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] docker run -v /Users/Gwenneg/git/quarkus/integration-tests/kafka/target/quarkus-integration-test-kafka-999-SNAPSHOT-native-image-source-jar:/project:z --rm quay.io/quarkus/ubi-quarkus-native-image:19.3.0-java11 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=1 -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -H:+TraceClassInitialization --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime -jar quarkus-integration-test-kafka-999-SNAPSHOT-runner.jar -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:+AddAllCharsets -H:EnableURLProtocols=http -H:+JNI --no-server -H:-UseServiceLoaderFeature -H:+StackTrace quarkus-integration-test-kafka-999-SNAPSHOT-runner
[quarkus-integration-test-kafka-999-SNAPSHOT-runner:24]    classlist:  60,944.83 ms
[quarkus-integration-test-kafka-999-SNAPSHOT-runner:24]        (cap):   5,606.92 ms
[quarkus-integration-test-kafka-999-SNAPSHOT-runner:24]        setup:  13,967.52 ms
20:15:52,004 INFO  [org.jbo.threads] JBoss Threads version 3.0.0.Final
[quarkus-integration-test-kafka-999-SNAPSHOT-runner:24]   (typeflow): 163,639.69 ms
[quarkus-integration-test-kafka-999-SNAPSHOT-runner:24]    (objects):  98,546.11 ms
[quarkus-integration-test-kafka-999-SNAPSHOT-runner:24]   (features):   5,271.64 ms
[quarkus-integration-test-kafka-999-SNAPSHOT-runner:24]     analysis: 282,027.29 ms
[quarkus-integration-test-kafka-999-SNAPSHOT-runner:24]     (clinit):   6,708.41 ms
[quarkus-integration-test-kafka-999-SNAPSHOT-runner:24]     universe:  29,754.20 ms
[quarkus-integration-test-kafka-999-SNAPSHOT-runner:24]      (parse):  37,709.44 ms
[quarkus-integration-test-kafka-999-SNAPSHOT-runner:24]     (inline):  44,072.53 ms
[quarkus-integration-test-kafka-999-SNAPSHOT-runner:24]    (compile): 183,881.50 ms
[quarkus-integration-test-kafka-999-SNAPSHOT-runner:24]      compile: 267,364.97 ms
Fatal error: org.graalvm.compiler.debug.GraalError: java.lang.NullPointerException
	at method: Checksum org.apache.kafka.common.utils.Crc32C$Java9ChecksumFactory.create()  [Direct call from long DefaultRecord.computePartialChecksum(long, int, int)]
	at com.oracle.svm.hosted.code.CompileQueue.defaultCompileFunction(CompileQueue.java:991)
	at com.oracle.svm.hosted.code.CompileQueue.doCompile(CompileQueue.java:922)
	at com.oracle.svm.hosted.code.CompileQueue$CompileTask.run(CompileQueue.java:259)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:171)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.NullPointerException
	at com.oracle.svm.hosted.code.CompileQueue.defaultCompileFunction(CompileQueue.java:937)
	... 9 more
Error: Image build request failed with exit status 1
```

**To Reproduce**
Steps to reproduce the behavior from the `master` branch:
1. (Optional) Set the `JAVA_HOME` environment variable to a JDK 11 installation directory (OpenJDK 11 or GraalVM 19.3.0 JDK 11 edition). Add the JDK 11 `bin` directory to the path.
2. (Optional) Run `./mvnw clean install -Dmaven.test.skip=true` to build all the Quarkus sources with the JDK 11.
3. Run `./mvnw clean install --projects :quarkus-integration-test-kafka -Dquarkus.native.container-build=true -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-native-image:19.3.0-java11`.

### PR DESCRIPTION
**Pull request by gwenneg**
Fixes #6009.

I couldn't get the `KafkaProcessor` substitution to work with JDK 11, so I simply replaced it with a non-generated version.

Please note that these changes fixed the NPE locally, but I wasn't able to get successful tests results because the native image is not starting fast enough (an exception saying `Failed to start native image, process has exited` is thrown at some point). That's a problem I only have with JDK 11 native tests and with many integration tests modules. The native image generation, which was failing before this PR, ended successfully though.

### CODE REVIEW

File: extensions/kafka-client/runtime/src/main/java/io/quarkus/kafka/client/runtime/graal/Crc32CSubstitutions.java [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+import com.oracle.svm.core.annotate.Substitute;
+import com.oracle.svm.core.annotate.TargetClass;
+import com.oracle.svm.core.jdk.JDK11OrLater;
+
+/**
+ * The following substitution replaces the usage of {@code MethodHandle} in {@code Java9ChecksumFactory} with a plain
+ * constructor invocation when run under GraalVM. This is necessary because the native image generator does not support method
+ * handles.
+ */
+@TargetClass(value = Crc32C.class, innerClass = "Java9ChecksumFactory", onlyWith = JDK11OrLater.class)
```
Comment (jaikiran) [inline extensions/kafka-client/runtime/src/main/java/io/quarkus/kafka/client/runtime/graal/Crc32CSubstitutions.java]: Hello @gwenneg, since the `Java9ChecksumFactory` gets used for any version of Java 9 or more[1], this substitution's `onlyWith` should apply for Java version 9 and greater, isnt' it?

[1] https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/common/utils/Crc32C.java#L40

Comment (gwenneg) [reply extensions/kafka-client/runtime/src/main/java/io/quarkus/kafka/client/runtime/graal/Crc32CSubstitutions.java]: Thanks for reviewing this @jaikiran. I asked myself the same question, but GraalVM only supports JDK 8 and 11 AFAIK so it doesn't really make sense to use an `onlyWith` condition checking for Java 9 and greater. WDYT?

Comment (jaikiran) [reply extensions/kafka-client/runtime/src/main/java/io/quarkus/kafka/client/runtime/graal/Crc32CSubstitutions.java]: @gwenneg I hadn't thought of that aspect :) So yes, you are right, what you have here is fine IMO.

**Comment by gwenneg** [comment]
All CI tests were successful and yet the build failed. I rebase on master to trigger a new build.

**Review by gsmet — APPROVED** [review]

**Comment by gwenneg** [comment]
I just ran the Kafka integration tests successfully with JDK 11 thanks to #6090.
