### PR TITLE
fix(vertx): do not log a warning about missing json support when vertx extension is present

### LINKED ISSUE #5614: Vert.x also provides a JSON implementation so no warning should be emitted
Since https://github.com/quarkusio/quarkus/pull/4165 , we emit a warning if our REST services produce JSON and we don't have any of the RESTEasy JSON extensions:

> [WARNING] [io.quarkus.resteasy.common.deployment.ResteasyCommonProcessor] Quarkus detected the need of REST JSON support but you have not provided the necessary JSON extension for this. You can visit https://quarkus.io/guides/rest-json for more information on how to set one.

Problem is: Vert.x also has the ability to serialize JSON via the Vert.x JSON types.

I think we should drop the warning also when we have the full Vert.x extension around.

See the Reactive MySQL client IT for an example of this issue.

### PR DESCRIPTION
**Pull request by machi1990**
Vert.x also provides a JSON implementation so no warning should be emitted

Fixes #5614

/cc @geoand @gsmet

### CODE REVIEW

File: extensions/vertx/deployment/src/main/java/io/quarkus/vertx/deployment/VertxProcessor.java [hunk 1]
```diff
@@ -51,6 +52,11 @@
     @Inject
     BuildProducer<ReflectiveClassBuildItem> reflectiveClass;
 
+    @BuildStep(providesCapabilities = Capabilities.RESTEASY_JSON_EXTENSION)
```
Comment (gsmet) [inline extensions/vertx/deployment/src/main/java/io/quarkus/vertx/deployment/VertxProcessor.java]: It's not used for anything else?

Comment (geoand) [reply extensions/vertx/deployment/src/main/java/io/quarkus/vertx/deployment/VertxProcessor.java]: Which part do you mean? Sorry for my thick headedness :)

Comment (machi1990) [reply extensions/vertx/deployment/src/main/java/io/quarkus/vertx/deployment/VertxProcessor.java]: The `RESTEASY_JSON_EXTENSION` Capability is used in `jackson` and `jsonb` extension to indicate `json` be support in `ResteasyCommonProcessor`. It was added for that case IIRC.

Comment (geoand) [reply extensions/vertx/deployment/src/main/java/io/quarkus/vertx/deployment/VertxProcessor.java]: Yes it already exists which is I guess what @gsmet was asking :)

**Comment by geoand** [comment]
It looks good to me, but I'll refrain from approving since I @gsmet to clarify what he meant in his question

File: extensions/vertx/deployment/src/main/java/io/quarkus/vertx/deployment/VertxProcessor.java (hunk 1 above)
Comment (gsmet) [reply extensions/vertx/deployment/src/main/java/io/quarkus/vertx/deployment/VertxProcessor.java]: Well, I'm wondering if it's a good idea to reuse that one or if we should add a VERTX capability and alter the condition in the processor itself.

This capability was used to basically say "we have an extension to provide proper JSON support for RESTEasy" and this one is not exactly saying that. It's saying "Vert.x provides some sort of JSON support for its own types".

Maybe I'm overthinking it, I don't know.

Comment (geoand) [reply extensions/vertx/deployment/src/main/java/io/quarkus/vertx/deployment/VertxProcessor.java]: I think we are OK with that @machi1990 added for the time being. My view is that if we need something more complicated later, we can always improve things

**Comment by machi1990** [comment]
CI failure unrelated 
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0-jboss-2:compile (default-compile) on project quarkus-integration-test-hibernate-orm-panache: Compilation failure: Compilation failure: 
[ERROR] /home/vsts/work/1/s/integration-tests/hibernate-orm-panache/src/main/java/io/quarkus/it/panache/TestEndpoint.java:[91,51] cannot find symbol
[ERROR]   symbol:   method withLock(javax.persistence.LockModeType)
[ERROR]   location: interface io.quarkus.hibernate.orm.panache.PanacheQuery<io.quarkus.hibernate.orm.panache.PanacheEntityBase>
[ERROR] /home/vsts/work/1/s/integration-tests/hibernate-orm-panache/src/main/java/io/quarkus/it/panache/TestEndpoint.java:[141,22] method findById in class io.quarkus.hibernate.orm.panache.PanacheEntityBase cannot be applied to given types;
[ERROR]   required: java.lang.Object
[ERROR]   found: java.lang.Long,javax.persistence.LockModeType
[ERROR]   reason: cannot infer type-variable(s) T
[ERROR]     (actual and formal argument lists differ in length)
[ERROR] /home/vsts/work/1/s/integration-tests/hibernate-orm-panache/src/main/java/io/quarkus/it/panache/TestEndpoint.java:[371,54] cannot find symbol
[ERROR]   symbol:   method withLock(javax.persistence.LockModeType)
[ERROR]   location: interface io.quarkus.hibernate.orm.panache.PanacheQuery<io.quarkus.it.panache.Person>
[ERROR] /home/vsts/work/1/s/integration-tests/hibernate-orm-panache/src/main/java/io/quarkus/it/panache/TestEndpoint.java:[420,25] method findById in interface io.quarkus.hibernate.orm.panache.PanacheRepositoryBase<Entity,Id> cannot be applied to given types;
[ERROR]   required: java.lang.Long
[ERROR]   found: java.lang.Long,javax.persistence.LockModeType
[ERROR]   reason: actual and formal argument lists differ in length
[ERROR] -> [Help 1]
```

File: extensions/vertx/deployment/src/main/java/io/quarkus/vertx/deployment/VertxProcessor.java (hunk 1 above)
Comment (machi1990) [reply extensions/vertx/deployment/src/main/java/io/quarkus/vertx/deployment/VertxProcessor.java]: +1 @geoand 

WDYT @gsmet ?

**Comment by geoand** [comment]
@loicmathieu does the error ring a bell? Is there perhaps a flaky test?

**Comment by loicmathieu** [comment]
@geoand it has been introduced via #5583 and all test passed on this one.
And tests passed on JDK11 and JKD12 so ... this is very strange.

I advise to re-launch the CI

**Comment by geoand** [comment]
Oh OK, I might know the cause.

@machi1990 can you please rebase onto the latest master?

**Comment by machi1990** [comment]
I think it is more a cache thingy on the CI @geoand @loicmathieu I'll rebase with master

File: extensions/vertx/deployment/src/main/java/io/quarkus/vertx/deployment/VertxProcessor.java (hunk 1 above)
Comment (gsmet) [reply extensions/vertx/deployment/src/main/java/io/quarkus/vertx/deployment/VertxProcessor.java]: I think I agree with myself but let's do it your way and I'll keep my "I told you so" for later :).

**Review by gsmet — APPROVED** [review]

File: extensions/vertx/deployment/src/main/java/io/quarkus/vertx/deployment/VertxProcessor.java (hunk 1 above)
Comment (geoand) [reply extensions/vertx/deployment/src/main/java/io/quarkus/vertx/deployment/VertxProcessor.java]: It wouldn't be the first time 😁

Comment (machi1990) [reply extensions/vertx/deployment/src/main/java/io/quarkus/vertx/deployment/VertxProcessor.java]: > It wouldn't be the first time 😁

ha ha indeed :-)
