### PR TITLE
Fix Otel propagator for old property

### LINKED ISSUE #29879: Create an opentelemetry-aws IT test project
### Description

Move opentelemetry-aws contrib dependencies are only used in tests and should be moved to IT tests, out of core. 

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by brunobat**
Fix config mapping for legacy property `quarkus.opentelemetry.propagators`

Fixes: https://github.com/quarkusio/quarkus/issues/29879

Update documentation because the xray propagator was moved to OTel contrib

### CODE REVIEW

**Review by radcortez — APPROVED** [review]

**Review by alesj — APPROVED** [review]

**Comment by brunobat** [comment]
Had to dismiss the reviews guys... The native failure highlighted the need for additional changes and a lot of cleanup.

**Review by radcortez — APPROVED** [review]

File: integration-tests/opentelemetry-spi/src/main/java/io/quarkus/it/opentelemetry/spi/ExporterResource.java [hunk 1]
```diff
@@ -35,6 +41,13 @@ public List<SpanData> export() {
                 .collect(Collectors.toList());
     }
 
+    @GET
+    @Path("/export/propagation")
+    public List<String> exportPropagation() throws NoSuchFieldException, IllegalAccessException {
+        TextMapPropagator textMapPropagator = openTelemetry.getPropagators().getTextMapPropagator();
+        return new ArrayList<>(textMapPropagator.fields());
```
Comment (alesj) [inline integration-tests/opentelemetry-spi/src/main/java/io/quarkus/it/opentelemetry/spi/ExporterResource.java:48]: So no reflection needed at the end?
(since afair, previous version of this had it ... )

**Review by alesj — APPROVED** [review]

File: integration-tests/opentelemetry-spi/src/main/java/io/quarkus/it/opentelemetry/spi/ExporterResource.java (hunk 1 above)
Comment (brunobat) [reply integration-tests/opentelemetry-spi/src/main/java/io/quarkus/it/opentelemetry/spi/ExporterResource.java:48]: Yes, the reflection was not working well with the devmode test. This achieves the same validation.
