### PR TITLE
Deprecate fullStacktraces

### LINKED ISSUE #167: RuntimesSmokeTest.quarkusFullMicroProfile failing due to deprecated StackTrace option
Mandrel IT test `RuntimesSmokeTest.quarkusFullMicroProfile` is failing because of the now deprecated `-H:+StackTrace` option. See this graal commit: https://github.com/oracle/graal/pull/6763/commits/c8a0e7654dcab6a51dd66b4922e3626ad81496a3 part of https://github.com/oracle/graal/pull/6763

The test fails with:
```
Error:  Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 522.484 s <<< FAILURE! - in org.graalvm.tests.integration.RuntimesSmokeTest
Error:  quarkusFullMicroProfile{TestInfo}  Time elapsed: 348.144 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: 
build-and-run.log log should not contain error or warning lines that are not whitelisted. See /home/runner/work/mandrel/mandrel/mandrel-integration-tests/testsuite/target/archived-logs/org.graalvm.tests.integration.RuntimesSmokeTest/quarkusFullMicroProfile/build-and-run.log and check these offending lines: 
Warning: Option 'StackTrace' is deprecated and might be removed in a future release. Please refer to the GraalVM release notes. ==> expected: <true> but was: <false>
	at org.graalvm.tests.integration.RuntimesSmokeTest.testRuntime(RuntimesSmokeTest.java:166)
	at org.graalvm.tests.integration.RuntimesSmokeTest.quarkusFullMicroProfile(RuntimesSmokeTest.java:194)
```
See https://github.com/graalvm/mandrel/actions/runs/5227497104/jobs/9439379129#step:11:13392

This affects the Windows mandrel IT run as well.

### PR DESCRIPTION
**Pull request by jerboaa**
GraalVM 23.1+ will have this option deprecated doing nothing. Deprecate it in Quarkus as well.

See for example this CI run:
https://github.com/graalvm/mandrel/actions/runs/5227497104/jobs/9439379340#step:12:140

Fixes: https://github.com/Karm/mandrel-integration-tests/issues/167

### CODE REVIEW

**Comment by jerboaa** [comment]
CI failures seem unrelated.

**Comment by jerboaa** [comment]
@geoand FWIW, @zakkak is away for while. If somebody else could have a look too, it would be good. @galderz or @Karm perhaps?

**Review by galderz — APPROVED** [review]

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/NativeConfig.java [hunk 1]
```diff
@@ -285,8 +285,11 @@ default String getEffectiveImage() {
 
     /**
      * If full stack traces are enabled in the resulting image
+     *
+     * @deprecated GraalVM 23.1+ will always build with full stack traces.
      */
     @WithDefault("true")
+    @Deprecated
```
Comment (zakkak) [inline core/deployment/src/main/java/io/quarkus/deployment/pkg/NativeConfig.java:292]: Given that we are still on 23.0, shouldn't we delay the deprecation?

Comment (jerboaa) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/NativeConfig.java:292]: No, I think this is still fine. Users need a way to become aware. Deprecating it now is the right call, imo. On the next release using it would do nothing.
