### PR TITLE
Fix ClassLoader getParent() hack

### LINKED ISSUE #14898: InjectMock with package private method
've noticed that when using `@InjectMock` on a class that declares package-private methods, you do get a mocked instance but the methods that are declared package private can't be stubbed.

Given a class like this:

```java
package example;

import javax.enterprise.context.ApplicationScoped;

@ApplicationScoped
public class MyService {

    public String getPublic() {
        throw new NullPointerException();
    }

    protected String getProtected() {
        throw new NullPointerException();
    }

    String getPackagePrivate() {
        throw new NullPointerException();
    }

}
```

And a test like this:

```java
package example;

import static org.mockito.Mockito.when;

import org.junit.jupiter.api.Test;

import io.quarkus.test.junit.QuarkusTest;
import io.quarkus.test.junit.mockito.InjectMock;

@QuarkusTest
public class MyServiceTest {

    @InjectMock
    MyService myService;

    @Test
    void getPublic() {
        when(myService.getPublic()).thenReturn("hello");
    }

    @Test
    void getProtected() {
        when(myService.getProtected()).thenReturn("hello");
    }

    @Test
    void getPackagePrivate() {
        when(myService.getPackagePrivate()).thenReturn("hello");
    }

}
```

The `getPublic()` and `getProtected()` tests will work as expected but `getPackagePrivate()` will throw a null pointer since it's actually invoking `myService.getPackagePrivate()` inside then when clause.

Contrary to this, a "normal" Mockito test will work just fine:

```java
package example;

import static org.mockito.Mockito.when;
import static org.mockito.MockitoAnnotations.openMocks;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;

public class MyServiceTest {

    @Mock
    MyService myService;

    @BeforeEach
    void setup() {
        openMocks(this);
    }

    @Test
    void getPublic() {
        when(myService.getPublic()).thenReturn("hello");
    }

    @Test
    void getProtected() {
        when(myService.getProtected()).thenReturn("hello");
    }

    @Test
    void getPackagePrivate() {
        when(myService.getPackagePrivate()).thenReturn("hello");
    }

}
```

If it's for some reason not possible to stub package-private methods in Quarkus then at least a helpful error message would be appreciated - it took me a while to figure out why my mock wasn't working 😄

Java version:
```
openjdk version "11.0.10" 2021-01-19 LTS
OpenJDK Runtime Environment Corretto-11.0.10.9.1 (build 11.0.10+9-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.10.9.1 (build 11.0.10+9-LTS, mixed mode)
```

Quarkus version: `1.11.0.Final`

### PR DESCRIPTION
**Pull request by stuartwdouglas**
This replaces the hack where QuarkusClassLoader.getParent() returns
null, and fixes it with some smaller more limited hacks around the
problematic API's.

Fixes #14898

### CODE REVIEW

File: independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/classloading/QuarkusClassLoader.java [hunk 1]
```diff
@@ -706,4 +701,24 @@ public ClassLoader parent() {
             this.parentFirstResources = parentFirstResources;
         }
     }
+
+    /**
+     * Horrible JDK8 hack
```
Comment (famod) [inline independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/classloading/QuarkusClassLoader.java:706]: Just passing by, so feel free to ignore me 😉 but I wondered whether this hack could actually be limited to JDK8 only?
Right now it seems to be used generally?

**Review by geoand — APPROVED** [review]

**Comment by gsmet** [comment]
CI is not happy and it looks related:
```
java.util.ServiceConfigurationError: org.eclipse.microprofile.openapi.spi.OASFactoryResolver: io.smallrye.openapi.spi.OASFactoryResolverImpl not a subtype
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:589)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1237)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1265)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1300)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1385)
	at org.eclipse.microprofile.openapi.spi.OASFactoryResolver.loadSpi(OASFactoryResolver.java:96)
	at org.eclipse.microprofile.openapi.spi.OASFactoryResolver.loadSpi(OASFactoryResolver.java:92)
	at org.eclipse.microprofile.openapi.spi.OASFactoryResolver.loadSpi(OASFactoryResolver.java:92)
	at org.eclipse.microprofile.openapi.spi.OASFactoryResolver.instance(OASFactoryResolver.java:74)
	at org.eclipse.microprofile.openapi.OASFactory.createObject(OASFactory.java:81)
```

**Review by gsmet — DISMISSED** [review]
Let's hold off until the CI issue is resolved.

**Comment by stuartwdouglas** [comment]
Ugh, yet another broken MP spec API: https://github.com/eclipse/microprofile-open-api/pull/470

File: independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/classloading/QuarkusClassLoader.java (hunk 1 above)
Comment (stuartwdouglas) [reply independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/classloading/QuarkusClassLoader.java:706]: I would rather keep it consistent. If we only installed it for JDK8 it would just be one more difference between the environments. getPackage was deprecated in 9 anyway.

**Comment by stuartwdouglas** [comment]
I have added another workaround for the OpenAPI issues.

**Comment by gastaldi** [comment]
Can you separate this PR in 2 commits: one with the changes this PR is supposed to fix and another with the changes that can be reverted when Reactive Streams Operators 1.1 is merged?

**Comment by stuartwdouglas** [comment]
I think its fine, its just deleting a method, it can be done as part of the upgrade PR.
