### PR TITLE
Ensure that Ryuk does not get started when simply checking for Docker

### LINKED ISSUE #25852: Testcontainers ryuk abandoned during build without testing using Gradle
### Describe the bug

The ryuk container from the Testcontainers project is abandoned when building without running any tests.

We are experiencing this with Gradle, I cannot say wether this the same as for other build tools.

Also, we are using a multi-module Gradle project where we have many Quarkus micro-services under one parent project. If we build all the modules in one go, we get a ryuk container for each sub-module.

### Expected behavior

Preferably ryuk containers are not started but at the very least they should be cleaned up after the build is done.

### Actual behavior

Ryuk container(s) are abandoned and must be removed from docker manually.

### How to Reproduce?

Run a build without testing in a Gradle single or multi-module project.

Example:

     ./gradlew build -Dquarkus.profile=prod -Dquarkus.container-image.build=true -x test -x integrationTest

### Output of `uname -a` or `ver`

macOS 12

### Output of `java -version`

Java 17

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.9.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.4

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
Usually Ryuk containers started by TestContainers will be stopped, but there are cases when after a build such containers are left dangling.
With this change, we ensure that Ryuk is not started when all we are doing is checking whether docker is available.

Fixes: #25852

### CODE REVIEW

File: core/deployment/src/main/java/io/quarkus/deployment/IsDockerWorking.java [hunk 1]
```diff
@@ -80,11 +81,25 @@ public Result get() {
...
+                updateUserConfigMethod.invoke(configurationInstance, "testcontainers.reuse.enable", "true");
+
                 boolean isAvailable = (boolean) dockerClientFactoryClass.getMethod("isDockerAvailable")
                         .invoke(dockerClientFactoryInstance);
                 if (!isAvailable) {
                     compressor.closeAndDumpCaptured();
                 }
+
+                // restore the previous value
+                updateUserConfigMethod.invoke(configurationInstance, "testcontainers.reuse.enable", oldReusePropertyValue);
```
Comment (gsmet) [inline core/deployment/src/main/java/io/quarkus/deployment/IsDockerWorking.java:102]: Shouldn't this be done in a finally block?

Comment (geoand) [reply core/deployment/src/main/java/io/quarkus/deployment/IsDockerWorking.java:102]: Not really, because all failures happen before `isDockerAvailable`

**Review by gastaldi — APPROVED** [review]

**Review by gsmet — APPROVED** [review]
