### PR TITLE
QuarkusComponentTest: fix the cleanup for nested test classes

### LINKED ISSUE #47275: @Nested of Junit5 not working with @QuarkusComponentTest: Bean CDI is removed in compilation time
### Describe the bug

**When performing tests in IntelliJIdea with @Nested classes and @QuarkusComponentTest annotation then @Inject Bean CDI is removed of the context even being used in methods**

_MY CODE:_
 
```
@QuarkusComponentTest
@DisplayName("--- Authentication service tests ---")
public class AuthenticationServiceTest {

    @Inject
    AuthenticationService service;

    @InjectMock
    CredentialRepository credentialRepository;

    @InjectMock
    ForgotPasswordRepository forgotPasswordRepository;

    @InjectMock
    CredentialMapper credentialMapper = Mappers.getMapper(CredentialMapper.class);

    @InjectMock
    ForgotPasswordMapper forgotPasswordMapper = Mappers.getMapper(ForgotPasswordMapper.class);

    Validator hibernateValidator = Validation.buildDefaultValidatorFactory().getValidator();

    @Nested
    @DisplayName("--- CredentialRequest tests ")
    class CredentialRequestTests {

        @Test
        @DisplayName("Must have one violation when email is null")
        void givenPersistCredential_whenEmailIsNull_thenThrowConstraintViolationException() {

            final String password = "#Rayan12";
            final CredentialRequest request = new CredentialRequest(new EmailRequest(null), password);

            final Set<ConstraintViolation<CredentialRequest>> violations = hibernateValidator.validate(request);

            final String message = violations.iterator().next().getMessage(),
                    expectedMessage = "Email required!";

            final int size = violations.size(),
                    expectedSize = 1;

            assertEquals(expectedSize, violations.size());
            assertEquals(expectedMessage, message);

        }

        @ParameterizedTest
        @ValueSource(strings = {
                "", " ", "plainaddress", "@missingusername.com", "username@.com", "username@.com.", "username@domain..com",
                "username@domain.c", "username@domain.toolong", "username@domain,com", "username@domain@domain.com",
                "username@domain..com", "username@domain.com (Joe Smith)", "username@domain.com.", "username@domain.com-",
                "username@domain.com_", "username@domain.com+", "username@domain.com%", "username@domain.com#",
                "username@domain.com$", "username@domain.com!", "username@domain.com^", "username@domain.com&",
                "username@domain.com*", "username@domain.com(", "username@domain.com)", "username@domain.com=",
                "username@domain.com{", "username@domain.com}", "username@domain.com[", "username@domain.com]"
        })
        @DisplayName("Must have one violation when email is invalid in pattern xxx@domain.com")
        void givenPersistCredential_whenEmailIsInvalid_thenThrowConstraintViolationException(@SkipInject final String email) {

            final String password = "#Rayan12";
            final CredentialRequest request = new CredentialRequest(new EmailRequest(email), password);

            final Set<ConstraintViolation<CredentialRequest>> violations = hibernateValidator.validate(request);

            final String message = violations.iterator().next().getMessage(),
                    expectedMessage = "Invalid email! Pattern required: xxx@domain.com";

            final int size = violations.size(),
                    expectedSize = 1;

            assertEquals(expectedSize, size);
            assertEquals(expectedMessage, message);

        }

        @Test
        @DisplayName("Must have one violation when password is null")
        void givenPersistCredential_whenPasswordIsNull_thenThrowConstraintViolationException() {

            final String email = "admin@gmail.com";
            final CredentialRequest request = new CredentialRequest(new EmailRequest(email), null);

            final Set<ConstraintViolation<CredentialRequest>> violations = hibernateValidator.validate(request);

            final String message = violations.iterator().next().getMessage(),
                    expectedMessage = "Password required!";

            final int size = violations.size(),
                    expectedSize = 1;

            assertEquals(expectedSize, size);
            assertEquals(expectedMessage, message);
        }

        @ParameterizedTest
        @ValueSource(strings = {
                "abcde", "ABCDE", "12345", "abc123", "ABC123", "abc!@#", "123!@#", "abcABC", "abcABC123",
                "abcABC!@#", "123ABC!@#", "abc123!@#", "abcABC123!@#", "abcdE", "abcdE1",
                "abcdE1!@#", "abcdE1!@#2", "abcdE1!@#23", "abcdE1!@#234", "abcdE1!@#2345", "abcdE1!@#23456", "abcdE1!@#234567",
                "abcdE1!@#2345678", "abcdE1!@#23456789", "abcdE1!@#234567890", "abcdE1!@#2345678901"
        })
        @DisplayName("Must have one violation when password is invalid in pattern '5 and 8 characters, at least 1 special character and a capital letter'")
        void givenPersistCredential_whenPasswordIsInvalid_thenThrowConstraintViolationException(@SkipInject final String password) {

            final String email = "admin@gmail.com";
            final CredentialRequest request = new CredentialRequest(new EmailRequest(email), password);

            final Set<ConstraintViolation<CredentialRequest>> violations = hibernateValidator.validate(request);

            final String message = violations.iterator().next().getMessage(),
                    expectedMessage = "Invalid password! Between 5 and 8 characters, at least 1 special character and a capital letter!";

            final int size = violations.size(),
                    expectedSize = 1;

            assertEquals(expectedSize, size);
            assertEquals(expectedMessage, message);

        }
    }


    @Nested
    @DisplayName("---- Persist credential tests ----")
    class PersistCredentialTests {

        CredentialRequest request;

        @BeforeEach
        void setUp() {
            request = new CredentialRequest(new EmailRequest("admin@gmail.com"), "#Admin12");
        }

        @Test
        @DisplayName("Should be throw WebApplicationException with status code 409 Conflict when email already exists")
        void givenPersistCredential_whenRequestEmailIsPresent_thenThrowWebApplicationException() {

            final Credential credential = new Credential();

            when(credentialRepository.findCredentialByEmail(request.emailRequest().email()))
                    .thenReturn(Optional.of(credential));

            final WebApplicationException e = assertThrows(WebApplicationException.class,
                    () -> service.persistCredential(request));

            final String expectedMessage = format("Client with email %s already exists!", request.emailRequest().email());
            final Response.Status expectedStatusCode = CONFLICT;

            assertEquals(expectedMessage, e.getMessage());
            assertEquals(expectedStatusCode, e.getResponse().getStatusInfo().toEnum());

            verify(credentialRepository, times(1)).findCredentialByEmail(request.emailRequest().email());
        }

        @Test
        @DisplayName("Should persist and return CredentialResponse when request is valid")
        void givenPersistCredential_whenRequestIsValid_thenPersistAndReturnCredentialResponse() {

            final Credential credential = Credential.builder()
                    .id(UUID.randomUUID())
                    .email(request.emailRequest().email())
                    .password(CryptographyUtils.encrypt(request.password()))
                    .build();

            final CredentialResponse expectedResponse = CredentialResponse.builder()
                    .id(credential.getId())
                    .email(credential.getEmail())
                    .password(credential.getPassword())
                    .createdAt(credential.getCreatedAt())
                    .keycloakUserId(null)
                    .build();

            when(credentialRepository.findCredentialByEmail(request.emailRequest().email()))
                    .thenReturn(Optional.empty());

            when(credentialMapper.requestToCredential(request)).thenReturn(credential);
            doNothing().when(credentialRepository).persist(credential);
            when(credentialMapper.credentialToResponse(credential)).thenReturn(expectedResponse);

            final CredentialResponse response = service.persistCredential(request);

            assertEquals(response, expectedResponse);

            verify(credentialRepository).findCredentialByEmail(request.emailRequest().email());
            verify(credentialMapper).requestToCredential(request);
            verify(credentialRepository).persist(credential);
            verify(credentialMapper).credentialToResponse(credential);
        }
    }

```

_EXCEPTION TRACE_
```
java.lang.IllegalStateException: The injected field [dev.rayan.services.AuthenticationService dev.rayan.services.AuthenticationServiceTest.service] expects a real component; but no matching component was registered

	at io.quarkus.test.component.QuarkusComponentTestExtension$FieldInjector.<init>(QuarkusComponentTestExtension.java:1169)
	at io.quarkus.test.component.QuarkusComponentTestExtension.injectFields(QuarkusComponentTestExtension.java:1055)
	at io.quarkus.test.component.QuarkusComponentTestExtension.startContainer(QuarkusComponentTestExtension.java:501)
	at io.quarkus.test.component.QuarkusComponentTestExtension.beforeEach(QuarkusComponentTestExtension.java:237)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

_THE WARNING_

Image

### Expected behavior

Methods correctly executed with @Nested Junit5 classes

### Actual behavior

Exception throwning. @Unremoavable in beans is necessary: https://pt.quarkus.io/blog/unused-beans/

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

Quarkus 22

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.13

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mkouba**
- fixes #47275

### CODE REVIEW

**Comment by mkouba** [comment]
@RayanArgolo03 it would be great if you could test this PR with your example.

File: test-framework/junit5-component/src/main/java/io/quarkus/test/component/QuarkusComponentTestExtension.java [hunk 1]
```diff
@@ -1051,21 +1057,26 @@ static <T> T cast(Object obj) {
...
         if (deprecatedInjectMock != null) {
             injectAnnotations = List.of(Inject.class, InjectMock.class, deprecatedInjectMock);
         } else {
             injectAnnotations = List.of(Inject.class, InjectMock.class);
         }
-        return findFields(testClass, injectAnnotations);
+        List<Field> found = findFields(testClass, injectAnnotations);
+        if (scanEnclosingClasses && testClass.getEnclosingClass() != null) {
+            // @Nested test class
+            found.addAll(findFields(testClass.getEnclosingClass(), injectAnnotations));
```
Comment (Ladicek) [inline test-framework/junit5-component/src/main/java/io/quarkus/test/component/QuarkusComponentTestExtension.java:1077]: You should loop until there's no enclosing class to support multiple nesting.

Comment (mkouba) [reply test-framework/junit5-component/src/main/java/io/quarkus/test/component/QuarkusComponentTestExtension.java:1077]: Eh, you're right. I thought that it scans the classes recursively :facepalm:. Anyway, I will add a nested level 2 test ;-).

Comment (mkouba) [reply test-framework/junit5-component/src/main/java/io/quarkus/test/component/QuarkusComponentTestExtension.java]: Done.

**Review by Ladicek — APPROVED** [review]

**Review by manovotn — APPROVED** [review]

File: test-framework/junit5-component/src/main/java/io/quarkus/test/component/QuarkusComponentTestExtension.java [hunk 2]
```diff
@@ -218,6 +219,11 @@ public QuarkusComponentTestExtension(Class<?>... additionalComponentClasses) {
     @Override
     public void beforeAll(ExtensionContext context) throws Exception {
         long start = System.nanoTime();
+        if (context.getRequiredTestClass().isAnnotationPresent(Nested.class)) {
+            // There is no callback that runs after all tests in a test class but before any @Nested test classes run
```
[the remark this answers is not in the document]
Comment (mkouba) [reply test-framework/junit5-component/src/main/java/io/quarkus/test/component/QuarkusComponentTestExtension.java:223]: Ok, let's keep this solution as a backup if some other problems occur ;-)
