### PR TITLE
Fix generic type handling of body parameter in RESTEasy Reactive

### LINKED ISSUE #16905: Resteasy reactive  - Handling Generics in request body
## Describe the bug
Generics arguments are not getting mapped properly from request and throwing the below exception
```
java.lang.ClassCastException: class java.util.HashMap cannot be cast to class org.generictype.Item 
        (java.util.HashMap is in module java.base of loader 'bootstrap'; org.generictype.Item is in unnamed module of loader 
        io.quarkus.bootstrap.classloading.QuarkusClassLoader @1e1e0d04)
```

**Quarkus version:** 1.13.3.Final
**Zulip discussion:** [Discussion]( https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Using.20generics.20in.20Request.20Body/near/236664853)

## To Reproduce

**Reproducer link:**
[https://github.com/aravindtga/Quarkus-generic-request-body-jsonb](https://github.com/aravindtga/Quarkus-generic-request-body-jsonb)

1. Run the provided application
2. Hit the endpoint "/endpoint" with the request body
```
{
    "content": {
        "name":"firstname",
        "email":"myemail"
    }
}
```

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #16905

### CODE REVIEW

File: independent-projects/resteasy-reactive/common/processor/src/main/java/org/jboss/resteasy/reactive/common/processor/EndpointIndexer.java [hunk 1]
```diff
@@ -945,6 +945,10 @@ public PARAM extractParameterInfo(ClassInfo currentClassInfo, ClassInfo actualEn
                 builder.setOptional(true);
             } else if (convertible) {
                 throw new RuntimeException("Invalid parameter type '" + pt + "' used on method " + errorLocation);
+            } else {
+                elementType = toClassName(pt.arguments().get(0), currentClassInfo, actualEndpointInfo, index);
```
Comment (FroMage) [inline independent-projects/resteasy-reactive/common/processor/src/main/java/org/jboss/resteasy/reactive/common/processor/EndpointIndexer.java:949]: The next line is fine, but here you're saying that for a parameter of type `Foo<X>` the `elementType` will be `X` and I'm not sure that's true at all, no?

**Review by FroMage — CHANGES_REQUESTED** [review]

File: independent-projects/resteasy-reactive/common/processor/src/main/java/org/jboss/resteasy/reactive/common/processor/EndpointIndexer.java (hunk 1 above)
Comment (geoand) [reply independent-projects/resteasy-reactive/common/processor/src/main/java/org/jboss/resteasy/reactive/common/processor/EndpointIndexer.java:949]: Well, that's the whole point of the PR. It guarantees that we have both types at runtime so the `MessageBodyReader` can know this information (the fact that the element type was not being set properly was the cause of the original issue)

Comment (FroMage) [reply independent-projects/resteasy-reactive/common/processor/src/main/java/org/jboss/resteasy/reactive/common/processor/EndpointIndexer.java:949]: My point is that IMO the element type is not `X` but `Foo<X>`, or `Foo` in the erased case. I don't see how `X` can be considered an element type since it's not unwrapped.

Comment (geoand) [reply independent-projects/resteasy-reactive/common/processor/src/main/java/org/jboss/resteasy/reactive/common/processor/EndpointIndexer.java:949]: We already record Foo and the signature itself.
It's just that in this case we were not making use of the signature because X was not being recorded

Comment (geoand) [reply independent-projects/resteasy-reactive/common/processor/src/main/java/org/jboss/resteasy/reactive/common/processor/EndpointIndexer.java:949]: It's also worth noting that this is in line with how we have `List` for example

Comment (FroMage) [reply independent-projects/resteasy-reactive/common/processor/src/main/java/org/jboss/resteasy/reactive/common/processor/EndpointIndexer.java:949]: Well, for `List<X>` since it's a container, the element type makes sense to be `X` but this is not a container type. Who even makes use of this element type then? If we pass it to things like message writers then it's wrong: we need to match on `Foo<X>` and not `X`.

Comment (geoand) [reply independent-projects/resteasy-reactive/common/processor/src/main/java/org/jboss/resteasy/reactive/common/processor/EndpointIndexer.java:949]: my brains fails to see this, so if you want to do something different than this PR, I'm fine with that

Comment (geoand) [reply independent-projects/resteasy-reactive/common/processor/src/main/java/org/jboss/resteasy/reactive/common/processor/EndpointIndexer.java:949]: Reading this again, maybe is throwing you off is the name of the variable?
Because all this does down the line, is make RESTEasy Reactive use the signature to determine the proper types.

Comment (FroMage) [reply independent-projects/resteasy-reactive/common/processor/src/main/java/org/jboss/resteasy/reactive/common/processor/EndpointIndexer.java:949]: No, what's bothering me is the `pt.arguments().get(0)` (as in `X` if `pt == Foo<X>`) where I think it should either be `pt` (as in `Foo<X>`) or we should set `elementType` to some guard value that indicates this is not actually an element of a collection, if that's what we're using it for.

Comment (geoand) [reply independent-projects/resteasy-reactive/common/processor/src/main/java/org/jboss/resteasy/reactive/common/processor/EndpointIndexer.java]: How about now?

**Review by FroMage — APPROVED** [review]
Yes, much less error-prone: this dummy type will stick out like a sore thumb if it ends up in the wrong hands :)

**Comment by geoand** [comment]
Great, thanks!
