### PR TITLE
Override items from super classes when generating config documentation

### LINKED ISSUE #41892: Config docs generation error when inheritance is used
### Describe the bug

When generating the documentation from `@ConfigRoot`, if the interface extends another interface, the listed properties in the base interface will not include the prefix of the `@ConfigMapping` and are hardcoded to build time properties.

### Expected behavior

When having this interface definition:
```java
@ConfigMapping(prefix = "quarkus.otel.exporter.otlp")
@ConfigRoot(phase = ConfigPhase.RUN_TIME)
public interface OtlpExporterRuntimeConfig extends OtlpExporterConfig
```
Classes in the OtlpExporterConfig are displayed like:
`quarkus.otel.exporter.otlp.endpoint`

### Actual behavior

Properties show up without prefix and are built time.
Screenshot 2024-07-15 at 09 35 29

### How to Reproduce?

Override a property defined on a base interface and see the generated documentation

### Output of `uname -a` or `ver`

Darwin <myHost> 22.6.0 Darwin Kernel Version 22.6.0: Mon Apr 22 20:49:37 PDT 2024; root:xnu-8796.141.3.705.2~1/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

% java --version openjdk 21.0.2 2024-01-16 LTS OpenJDK Runtime Environment Temurin-21.0.2+13 (build 21.0.2+13-LTS) OpenJDK 64-Bit Server VM Temurin-21.0.2+13 (build 21.0.2+13-LTS, mixed mode)

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae) Maven home: /Users/<user>/.sdkman/candidates/maven/current Java version: 21.0.2, vendor: Eclipse Adoptium, runtime: /Users/<user>/.sdkman/candidates/java/21.0.2-tem Default locale: en_PT, platform encoding: UTF-8 OS name: "mac os x", version: "13.6.7", arch: "aarch64", family: "mac"

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by radcortez**
- Fixes #41892

The fix could be better by using a `Map` instead of a dumb `List` search, but we don't want to change the code too much due to some significant refactorings coming.

### CODE REVIEW

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/config/runtime/exporter/OtlpExporterConfig.java [hunk 1]
```diff
@@ -5,11 +5,9 @@
 import java.util.Optional;
 import java.util.OptionalInt;
 
-import io.quarkus.runtime.annotations.ConfigGroup;
 import io.smallrye.config.WithDefault;
 import io.smallrye.config.WithName;
 
-@ConfigGroup
```
Comment (gsmet) [inline extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/config/runtime/exporter/OtlpExporterConfig.java:12]: I know it's not mandatory but I would say it's a good practice to keep the annotation, given the annotation processor is annotation driven.
They get discovered anyway when analyzing the config but this makes it discovered right away by the AP.

File: core/processor/src/main/java/io/quarkus/annotation/processor/generate_doc/ConfigDocItemFinder.java [hunk 2]
```diff
@@ -396,6 +396,19 @@ private List<ConfigDocItem> recursivelyFindConfigItems(Element element, String r
...
+
+                // If there is already a config item with the same key it comes from a super type, and we need to override it
+                ConfigDocItem parent = null;
+                for (ConfigDocItem docItem : configDocItems) {
+                    if (docItem.getConfigDocKey().getKey().equals(configDocKey.getKey())) {
+                        parent = docItem;
+                        break;
+                    }
+                }
+                // We many want to merge the metadata, but let's keep this simple for now
```
Comment (gsmet) [inline core/processor/src/main/java/io/quarkus/annotation/processor/generate_doc/ConfigDocItemFinder.java:408]:
```suggestion
                // We may want to merge the metadata, but let's keep this simple for now
```

**Review by gsmet — APPROVED** [review]
I added two small non-blocking comments. Feel free to either edit the commit or merge it as is :).

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/config/runtime/exporter/OtlpExporterConfig.java (hunk 1 above)
Comment (radcortez) [reply extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/config/runtime/exporter/OtlpExporterConfig.java:12]: When this annotation is present in a super class relative to the mapping class, we do generate duplicate entries of the configuration, because we handle `@ConfigGroup` as a nested element and not an an inherited element.

We could also fix that in the code, but I think that super classes are not config groups, so it is a bit misleading to add that annotation.

**Review by brunobat — APPROVED** [review]
