### PR TITLE
Pass `--userns=keep-id` to podman only when in rootless mode

### LINKED ISSUE #31334: podman4 can't build any code with quarkus builder
podman info
```
[root@~]# podman version
Client:       Podman Engine
Version:      4.3.1
API Version:  4.3.1
Go Version:   go1.18.7
Built:        Fri Nov 11 10:24:13 2022
OS/Arch:      linux/amd64
```
build command incloud builder:
```
mvn -ntp -f /root/alarm-service/pom.xml -DskipTests clean package -Pnative -Dquarkus.container-image.build=false -Dquarkus.native.container-runtime=podman -Dquarkus.container-image.tag=v1.0.0_20230131 -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel-builder-image:22.3-java11
mvn -ntp -f /root/alarm-service/pom.xml -DskipTests clean package -Pnative -Dquarkus.container-image.build=false -Dquarkus.native.container-runtime=podman -Dquarkus.container-image.tag=v1.0.0_20230131 -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-graalvmce-builder-image:22.3-java11
mvn -ntp -f /root/alarm-service/pom.xml -DskipTests clean package -Pnative -Dquarkus.container-image.build=false -Dquarkus.native.container-runtime=podman -Dquarkus.container-image.tag=v1.0.0_20230131 -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-graalvmce-builder-image:22.1-java11
mvn -ntp -f /root/alarm-service/pom.xml -DskipTests clean package -Pnative -Dquarkus.container-image.build=false -Dquarkus.native.container-runtime=podman -Dquarkus.container-image.tag=v1.0.0_20230131 -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel-builder-image:22.1-java11
```

error info:
```
[ERROR] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Unable to get GraalVM version from the native-image binary.
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildRunner] podman run --env LANG=C --rm --user 0:0 --userns=keep-id -v /root/alarm-service/target/alarm-service-1.0-SNAPSHOT-native-image-source-jar:/project:z --name build-native-PTYgJ quay.io/quarkus/ubi-quarkus-mandrel-builder-image:22.1-java11 -J-DCoordinatorEnvironmentBean.transactionStatusManagerEnable=false -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dlogging.initial-configurator.min-level=500 -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=3 -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Duser.language=en -J-Duser.country=US -J-Dfile.encoding=UTF-8 --features=io.quarkus.runner.Feature,io.quarkus.jdbc.postgresql.runtime.graal.SQLXMLFeature,io.quarkus.runtime.graal.ResourcesFeature,io.quarkus.runtime.graal.DisableLoggingFeature -H:-ParseOnce -J--add-exports=java.security.jgss/sun.security.krb5=ALL-UNNAMED -J--add-opens=java.base/java.text=ALL-UNNAMED -J--add-opens=java.base/java.io=ALL-UNNAMED -J--add-opens=java.base/java.lang.invoke=ALL-UNNAMED -J--add-opens=java.base/java.util=ALL-UNNAMED -H:ResourceConfigurationFiles=resources-config.json -H:ReflectionConfigurationFiles=reflection-config.json -H:+AllowFoldMethods -J-Djava.awt.headless=true --no-fallback --link-at-build-time -H:+ReportExceptionStackTraces -H:-AddAllCharsets --enable-url-protocols=http,https -H:-UseServiceLoaderFeature -H:+StackTrace -J--add-exports=org.graalvm.sdk/org.graalvm.nativeimage.impl=ALL-UNNAMED -J--add-exports=org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk=ALL-UNNAMED -J--add-exports=org.graalvm.nativeimage.builder/com.oracle.svm.core.configure=ALL-UNNAMED -J--add-exports=org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.localization=ALL-UNNAMED --exclude-config io\.netty\.netty-codec /META-INF/native-image/io\.netty/netty-codec/generated/handlers/reflect-config\.json --exclude-config io\.netty\.netty-handler /META-INF/native-image/io\.netty/netty-handler/generated/handlers/reflect-config\.json alarm-service-1.0-SNAPSHOT-runner -jar alarm-service-1.0-SNAPSHOT-runner.jar
Error: keep-id is only supported in rootless mode
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  29.799 s
[INFO] Finished at: 2023-01-31T22:15:09-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:2.16.0.Final:build (default) on project alarm-service: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: io.quarkus.deployment.pkg.steps.NativeImageBuildStep$ImageGenerationFailureException: Image generation failed. Exit code: 125
[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.imageGenerationFailed(NativeImageBuildStep.java:421)
[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:262)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
[ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:834)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

The weird thing is that I dropped podman4 to podman3 but it worked

### PR DESCRIPTION
**Pull request by zakkak**
Fixes: #31334

@peter-777 @zzguang520520 can you please give this a try?

### CODE REVIEW

File: core/runtime/src/main/java/io/quarkus/runtime/util/ContainerRuntimeUtil.java [hunk 1]
```diff
@@ -59,15 +62,52 @@ private static String getVersionOutputFor(ContainerRuntime containerRuntime) {
         }
     }
 
+    private static boolean getRootlessStateFor(ContainerRuntime containerRuntime) {
+        Process rootlessProcess = null;
+        try {
+            ProcessBuilder pb = new ProcessBuilder(containerRuntime.getExecutableName(), "info")
+                    .redirectErrorStream(true);
+            rootlessProcess = pb.start();
+            rootlessProcess.waitFor();
```
Comment (gastaldi) [inline core/runtime/src/main/java/io/quarkus/runtime/util/ContainerRuntimeUtil.java:71]: Maybe check if the return code is zero?

File: core/runtime/src/main/java/io/quarkus/runtime/util/ContainerRuntimeUtil.java [hunk 2]
```diff
@@ -59,15 +62,52 @@ private static String getVersionOutputFor(ContainerRuntime containerRuntime) {
...
+            BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(rootlessProcess.getInputStream()));
```
Comment (gastaldi) [inline core/runtime/src/main/java/io/quarkus/runtime/util/ContainerRuntimeUtil.java:72]: It could be useful to close this InputStream (in a try-with-resources block)

**Review by gastaldi — APPROVED** [review]

**Comment by peter-777** [comment]
@zakkak
Thanks you for the quick fixes!

I confirmed that the native build in Gradle was successful  with this PR.
(I had to change the javax package to jakarta, but otherwise did not change my sources).

<details><summary>log</summary>
<p>

`./gradlew -i build -Dquarkus.package.type=native -Dquarkus.native.container-build=true -Dquarkus.container-image.build=true -Dquarkus.container-image.tag=native`

```
(Abbreviated)

> Task :quarkusBuild
Caching disabled for task ':quarkusBuild' because:
  Build cache is disabled
Task ':quarkusBuild' is not up-to-date because:
  Value of input property 'quarkusBuildSystemProperties' has changed for task ':quarkusBuild'
The configuration :quarkusProdRuntimeClasspathConfigurationDeployment is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration :quarkusProdRuntimeClasspathConfigurationDeployment is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
The configuration :detachedConfiguration2 is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration :detachedConfiguration2 is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
The configuration :detachedConfiguration2 is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration :detachedConfiguration2 is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
The configuration :quarkusProdRuntimeClasspathConfiguration is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration :quarkusProdRuntimeClasspathConfiguration is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
The configuration :detachedConfiguration3 is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration :detachedConfiguration3 is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
The configuration :detachedConfiguration3 is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration :detachedConfiguration3 is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
The configuration :quarkusProdRuntimeClasspathConfiguration is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration :quarkusProdRuntimeClasspathConfiguration is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
The configuration :detachedConfiguration4 is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration :detachedConfiguration4 is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
The configuration :detachedConfiguration4 is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration :detachedConfiguration4 is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
The configuration :quarkusProdRuntimeClasspathConfiguration is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration :quarkusProdRuntimeClasspathConfiguration is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
The configuration :detachedConfiguration5 is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration :detachedConfiguration5 is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
The configuration :detachedConfiguration5 is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration :detachedConfiguration5 is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
The configuration :quarkusProdRuntimeClasspathConfiguration is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration :quarkusProdRuntimeClasspathConfiguration is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
Cache entries evicted. In-memory cache of /workspaces/simple-app-q/.gradle/8.0.1/checksums/sha1-checksums.bin: Size{400} MaxSize{400}, CacheStats{hitCount=2836, missCount=680, loadSuccessCount=681, loadExceptionCount=0, totalLoadTime=543290700, evictionCount=241} 
Performance may suffer from in-memory cache misses. Increase max heap size of Gradle build process to reduce cache misses.
Cache entries evicted. In-memory cache of /workspaces/simple-app-q/.gradle/8.0.1/checksums/md5-checksums.bin: Size{400} MaxSize{400}, CacheStats{hitCount=107, missCount=710, loadSuccessCount=711, loadExceptionCount=0, totalLoadTime=546623050, evictionCount=281} 
Performance may suffer from in-memory cache misses. Increase max heap size of Gradle build process to reduce cache misses.
Cache entries evicted. In-memory cache of /workspaces/simple-app-q/.gradle/8.0.1/checksums/sha1-checksums.bin: Size{400} MaxSize{400}, CacheStats{hitCount=2969, missCount=720, loadSuccessCount=721, loadExceptionCount=0, totalLoadTime=559537314, evictionCount=281} 
Performance may suffer from in-memory cache misses. Increase max heap size of Gradle build process to reduce cache misses.
Cache entries evicted. In-memory cache of /workspaces/simple-app-q/.gradle/8.0.1/checksums/md5-checksums.bin: Size{400} MaxSize{400}, CacheStats{hitCount=107, missCount=750, loadSuccessCount=751, loadExceptionCount=0, totalLoadTime=565430360, evictionCount=321} 
Performance may suffer from in-memory cache misses. Increase max heap size of Gradle build process to reduce cache misses.
Cache entries evicted. In-memory cache of /workspaces/simple-app-q/.gradle/8.0.1/checksums/sha1-checksums.bin: Size{400} MaxSize{400}, CacheStats{hitCount=2971, missCount=760, loadSuccessCount=761, loadExceptionCount=0, totalLoadTime=588282941, evictionCount=321} 
Performance may suffer from in-memory cache misses. Increase max heap size of Gradle build process to reduce cache misses.
Cache entries evicted. In-memory cache of /workspaces/simple-app-q/.gradle/8.0.1/checksums/md5-checksums.bin: Size{400} MaxSize{400}, CacheStats{hitCount=107, missCount=790, loadSuccessCount=791, loadExceptionCount=0, totalLoadTime=609419893, evictionCount=361} 
Performance may suffer from in-memory cache misses. Increase max heap size of Gradle build process to reduce cache misses.
The configuration :quarkusProdRuntimeClasspathConfigurationPlatform is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration :quarkusProdRuntimeClasspathConfigurationPlatform is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
The configuration :detachedConfiguration6 is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration :detachedConfiguration6 is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
The configuration :detachedConfiguration6 is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration :detachedConfiguration6 is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
file or directory '/workspaces/simple-app-q/src/integrationTest/java', not found
file or directory '/workspaces/simple-app-q/build/classes/java/quarkus-generated-sources/grpc', not found
file or directory '/workspaces/simple-app-q/build/classes/java/quarkus-generated-sources/avdl', not found
file or directory '/workspaces/simple-app-q/build/classes/java/quarkus-generated-sources/avpr', not found
file or directory '/workspaces/simple-app-q/build/classes/java/quarkus-generated-sources/avsc', not found
file or directory '/workspaces/simple-app-q/src/quarkus-generated-sources/java', not found
file or directory '/workspaces/simple-app-q/src/quarkus-test-generated-sources/java', not found
file or directory '/workspaces/simple-app-q/src/integrationTest/resources', not found
file or directory '/workspaces/simple-app-q/src/native-test/resources', not found
file or directory '/workspaces/simple-app-q/src/quarkus-generated-sources/resources', not found
file or directory '/workspaces/simple-app-q/src/quarkus-test-generated-sources/resources', not found
file or directory '/workspaces/simple-app-q/src/test/resources', not found
The configuration :quarkusProdRuntimeClasspathConfiguration is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration :quarkusProdRuntimeClasspathConfiguration is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
The configuration :quarkusProdRuntimeClasspathConfigurationDeployment is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration :quarkusProdRuntimeClasspathConfigurationDeployment is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
JBoss Threads version 3.4.3.Final

Building native image source jar: /workspaces/simple-app-q/build/simple-app-q-1.0.0-SNAPSHOT-native-image-source-jar/simple-app-q-1.0.0-SNAPSHOT-runner.jar
Building native image from /workspaces/simple-app-q/build/simple-app-q-1.0.0-SNAPSHOT-native-image-source-jar/simple-app-q-1.0.0-SNAPSHOT-runner.jar
Using podman to run the native image builder
Checking image status quay.io/quarkus/ubi-quarkus-mandrel-builder-image:22.3-java17
Trying to pull quay.io/quarkus/ubi-quarkus-mandrel-builder-image:22.3-java17...
Getting image source signatures
Copying blob sha256:3550ee360766546a0eaca7c96269646f601a714ad8e63684f8ace09c2bbbfd19
Copying blob sha256:c5f4a7e2fa03761b49d82d93610545e40ac39b29d0675c363549753919e0d4c8
Copying blob sha256:cc8cfffc43311250a54aa1b545bd957e457a2e930e1b4fc0e5b93a737930597e
Copying blob sha256:e6fb0554f4075b0e1334395285686e7b091569111ac5bb9bb79be5ac68a6e8d8
Copying blob sha256:84df9b4951929fde40b6ed3b6239e893a680badbe62b9ad39ada5f8a848cd197
Copying blob sha256:5960b3a10983846b6661a8cdc99c111134ec130e9be67a35a2dc21e9787de8be
Copying blob sha256:7a8e296d4f186ddcaaa35194f2cfc7731f1336ddba9f08c3b8e6670cd1a30a23
Copying blob sha256:7953f6df1d7b385850e53e79a75ea9538ed130453322de1869eb1d624702ac5d
Copying blob sha256:09a4062d1274d2a48927fc5221c49b32b65576ec29dfa0352216c947821184e1
Copying blob sha256:5c1b332c5706742a9c74979b6d93ffcd713523b3bccbf1320fb1504157a277a6
Copying blob sha256:030471f4ed808af6ba30a73e39de68cc3f40814c6e5a225daf52ef5a4c462278
Copying blob sha256:40b790be7a61e3356cf11ead3a605881275fa5c5066d5f3f2b4a4204c06c9495
Copying blob sha256:6c31ad5ba21738d4a08543c939430554a7719b9aced1eaee931abda7c532934b
Copying blob sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1
Copying blob sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1
Copying config sha256:4b235d59d8893b1812c9831fd45690d4fa0a404081145437eefaa2faf71a0992
Writing manifest to image destination
Storing signatures
4b235d59d8893b1812c9831fd45690d4fa0a404081145437eefaa2faf71a0992
Running Quarkus native-image plugin on native-image 22.3.1.0-Final Mandrel Distribution (Java Version 17.0.6+10)
podman run --env LANG=C --rm --user 0:0 -v /workspaces/simple-app-q/build/simple-app-q-1.0.0-SNAPSHOT-native-image-source-jar:/project:z --name build-native-vYQUz quay.io/quarkus/ubi-quarkus-mandrel-builder-image:22.3-java17 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Dlogging.initial-configurator.min-level=500 -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.noUnsafe=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=3 -J-Duser.language=ja -J-Duser.country=JP -J-Dfile.encoding=UTF-8 --features=io.quarkus.runner.Feature,io.quarkus.runtime.graal.DisableLoggingFeature -J--add-exports=java.security.jgss/sun.security.krb5=ALL-UNNAMED -J--add-opens=java.base/java.text=ALL-UNNAMED -J--add-opens=java.base/java.io=ALL-UNNAMED -J--add-opens=java.base/java.lang.invoke=ALL-UNNAMED -J--add-opens=java.base/java.util=ALL-UNNAMED -H:+CollectImageBuildStatistics -H:ImageBuildStatisticsFile=simple-app-q-1.0.0-SNAPSHOT-runner-timing-stats.json -H:BuildOutputJSONFile=simple-app-q-1.0.0-SNAPSHOT-runner-build-output-stats.json -H:+AllowFoldMethods -J-Djava.awt.headless=true --no-fallback --link-at-build-time -H:+ReportExceptionStackTraces -H:-AddAllCharsets --enable-url-protocols=http -H:-UseServiceLoaderFeature -H:+StackTrace -J--add-exports=org.graalvm.sdk/org.graalvm.nativeimage.impl=ALL-UNNAMED --exclude-config io\.netty\.netty-codec /META-INF/native-image/io\.netty/netty-codec/generated/handlers/reflect-config\.json --exclude-config io\.netty\.netty-handler /META-INF/native-image/io\.netty/netty-handler/generated/handlers/reflect-config\.json simple-app-q-1.0.0-SNAPSHOT-runner -jar simple-app-q-1.0.0-SNAPSHOT-runner.jar
========================================================================================================================
GraalVM Native Image: Generating 'simple-app-q-1.0.0-SNAPSHOT-runner' (executable)...
========================================================================================================================
[1/7] Initializing...                                                                                   (20.6s @ 0.23GB)
 Version info: 'GraalVM 22.3.1.0-Final Java 17 Mandrel Distribution'
 Java version info: '17.0.6+10'
 C compiler: gcc (redhat, x86_64, 8.5.0)
 Garbage collector: Serial GC
 2 user-specific feature(s)
 - io.quarkus.runner.Feature: Auto-generated class by Quarkus from the existing extensions
 - io.quarkus.runtime.graal.DisableLoggingFeature: Disables INFO logging during the analysis phase for the [org.jboss.threads] categories
[2/7] Performing analysis...  [******]                                                                  (82.5s @ 1.20GB)
  10,430 (88.57%) of 11,776 classes reachable
  14,878 (57.47%) of 25,887 fields reachable
  51,369 (55.34%) of 92,821 methods reachable
     521 classes,   111 fields, and 2,383 methods registered for reflection
      63 classes,    68 fields, and    55 methods registered for JNI access
       4 native libraries: dl, pthread, rt, z
[3/7] Building universe...                                                                               (7.8s @ 1.08GB)
[4/7] Parsing methods...      [***]                                                                      (7.6s @ 2.04GB)
[5/7] Inlining methods...     [***]                                                                      (4.2s @ 1.44GB)
[6/7] Compiling methods...    [*******]                                                                 (54.2s @ 2.80GB)
[7/7] Creating image...                                                                                  (8.4s @ 1.79GB)
  19.46MB (46.98%) for code area:    32,863 compilation units
  21.64MB (52.25%) for image heap:  268,960 objects and 8 resources
 327.51KB ( 0.77%) for other data
  41.42MB in total
------------------------------------------------------------------------------------------------------------------------
Top 10 packages in code area:                               Top 10 object types in image heap:
   1.62MB sun.security.ssl                                     4.31MB byte[] for code metadata
 972.87KB java.util                                            2.46MB java.lang.Class
 733.90KB java.lang.invoke                                     2.44MB java.lang.String
 717.68KB com.sun.crypto.provider                              2.34MB byte[] for general heap data
 451.81KB io.netty.buffer                                      1.91MB byte[] for java.lang.String
 450.53KB sun.security.x509                                  896.33KB com.oracle.svm.core.hub.DynamicHubCompanion
 447.23KB java.lang                                          634.45KB java.util.HashMap$Node
 392.22KB java.io                                            544.70KB byte[] for reflection metadata
 381.60KB java.util.concurrent                               470.98KB java.lang.String[]
 343.08KB io.netty.handler.codec.http2                       391.46KB byte[] for embedded resources
  12.81MB for 389 more packages                                4.28MB for 2529 more object types
------------------------------------------------------------------------------------------------------------------------
                        8.3s (4.2% of total time) in 40 GCs | Peak RSS: 4.28GB | CPU load: 5.82
------------------------------------------------------------------------------------------------------------------------
Produced artifacts:
 /project/simple-app-q-1.0.0-SNAPSHOT-runner (executable)
 /project/simple-app-q-1.0.0-SNAPSHOT-runner-build-output-stats.json (json)
 /project/simple-app-q-1.0.0-SNAPSHOT-runner-timing-stats.json (raw)
 /project/simple-app-q-1.0.0-SNAPSHOT-runner.build_artifacts.txt (txt)
========================================================================================================================
Finished generating 'simple-app-q-1.0.0-SNAPSHOT-runner' in 3m 15s.
podman run --env LANG=C --rm --user 0:0 -v /workspaces/simple-app-q/build/simple-app-q-1.0.0-SNAPSHOT-native-image-source-jar:/project:z --entrypoint /bin/bash quay.io/quarkus/ubi-quarkus-mandrel-builder-image:22.3-java17 -c objcopy --strip-debug simple-app-q-1.0.0-SNAPSHOT-runner
Starting (local) container image build for native binary using docker.
Executing the following command to build docker image: 'docker build -f /workspaces/simple-app-q/src/main/docker/Dockerfile.native -t root/simple-app-q:native /workspaces/simple-app-q'
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
STEP 1/7: FROM registry.access.redhat.com/ubi8/ubi-minimal:8.6
Trying to pull registry.access.redhat.com/ubi8/ubi-minimal:8.6...
Getting image source signatures
Checking if image destination supports signatures
Copying blob sha256:a6577091999bb0bb54af7b808b41c58aa9a79a61f12310b734f235b548159d75
Copying config sha256:abb1ba1bceab1e5e1ce42e05d82bec44cd67484a7d21547d30aa1c52d3ca3114
Writing manifest to image destination
Storing signatures
STEP 2/7: WORKDIR /work/
--> ceaf5bc8a89
STEP 3/7: RUN chown 1001 /work     && chmod "g+rwX" /work     && chown 1001:root /work
--> 089819bebb5
STEP 4/7: COPY --chown=1001:root build/*-runner /work/application
--> a8295e8bafb
STEP 5/7: EXPOSE 8080
--> dbc4ed30e80
STEP 6/7: USER 1001
--> fa8d4b49dd7
STEP 7/7: CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
COMMIT root/simple-app-q:native
--> 72183384d0c
Successfully tagged localhost/root/simple-app-q:native
72183384d0cd49d8d60655e6ff8271eef6be5414f7b0bee129f0cbc443397495
Built container image root/simple-app-q:native (null)


> Task :quarkusBuild
Quarkus augmentation completed in 287057ms
Resolve mutations for :assemble (Thread[Execution worker Thread 7,5,main]) started.
:assemble (Thread[Execution worker Thread 5,5,main]) started.

> Task :assemble
Skipping task ':assemble' as it has no actions.
Resolve mutations for :check (Thread[Execution worker Thread 7,5,main]) started.
:check (Thread[Execution worker Thread 6,5,main]) started.

> Task :check UP-TO-DATE
Skipping task ':check' as it has no actions.
Resolve mutations for :build (Thread[Execution worker Thread 6,5,main]) started.
:build (Thread[Execution worker Thread 5,5,main]) started.

> Task :build
Skipping task ':build' as it has no actions.

BUILD SUCCESSFUL in 5m 6s
9 actionable tasks: 1 executed, 8 up-to-date
Some of the file system contents retained in the virtual file system are on file systems that Gradle doesn't support watching. The relevant state was discarded to ensure changes to these locations are properly detected. You can override this by explicitly enabling file system watching.
```

</p>
</details>
