### PR TITLE
Quartz - prevent memory leak when Job instance is a @Dependent bean

### LINKED ISSUE #38824: Memory leak when using FT Fallback with dependent beans
### Describe the bug

Not exactly sure if its with dependent beans per se, but we saw this in our application using quartz job. The reproducer uses something a bit similar using quartz as well.

When we create a job that uses or a fallback method, or a FallbackHandler class, the Job remains as an outgoing ref in `io.quarkus.arc.impl.EagerInstanceHandle`

So by running the reproducer we create 1000 jobs that runs instantly (should not exists after)  here's the result

**WITH FALLBACK**
Screen Shot 2024-02-16 at 1 37 29 PM

Screen Shot 2024-02-16 at 1 35 03 PM

**WITHOUT FALLBACK** (comment line 18 of MyJob.java in the reproducer)

Screen Shot 2024-02-16 at 1 43 01 PM

Screen Shot 2024-02-16 at 1 44 13 PM

### Expected behavior

Memory should not climb up without getting down each time a job run. GC should be able to clean it up

### Actual behavior

Memory remains taken forever

### How to Reproduce?

Reproducer: https://github.com/manofthepeace/ft-leak

Steps to reproduce:
1- mvn quarkus:dev (wait a couple sec until the 1000 job runs)
2- get a heapdump via `jps`+ `jmap -dump:live,file=/Users/alex/Desktop/dumps/dump.hprof <pid>`
3- analyze `EagerInstanceHandle` and `MyJob.*`

4- comment out line 18 (the fallback annotation) from MyJob.java
5- repeat step 1,2,3

### Output of `uname -a` or `ver`

Darwin Kernel Version 21.6.0

### Output of `java -version`

Temurin-21.0.2+13

### Quarkus version or git rev

3.7.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

apache-maven-3.9.5

### Additional information

Got around the leak by changing the fallback to a CDI decorator

### PR DESCRIPTION
**Pull request by manovotn**
Fixes #38824
As a side effect, this corrects the behavior in that it creates a new instance of `Job` (if it's a `@Dependent` bean) for every invocation of the `Trigger`. This is in accordance with Quartz's `JobFactory#newJob` documentation.

Note that `@Scheduled` tasks are handled (correctly) in `SchedulerProcessor#generateInvoker` and are unaffected by these changes.

### CODE REVIEW

File: extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/CdiAwareJob.java [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+
+/**
+ * An abstraction allowing proper destruction of Job instances in case they are dependent beans.
+ * According to {@link org.quartz.spi.JobFactory#newJob(TriggerFiredBundle, Scheduler)}, a new job instance is created for every
+ * trigger.
+ * We will therefore create a new dependent bean for every trigger and destroy it afterwards.
+ */
+public class CdiAwareJob implements Job {
+
+    final private Instance.Handle<? extends Job> jobInstanceHandle;
```
Comment (mkouba) [inline extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/CdiAwareJob.java:20]: I believe that the convention is to use `private final` but that's just nitpicking ;-)

**Review by mkouba — APPROVED** [review]

**Review by Ladicek — APPROVED** [review]

File: extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/CdiAwareJob.java (hunk 1 above)
Comment (manovotn) [reply extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/CdiAwareJob.java]: Done
