### PR TITLE
Security annotations for cdi

### LINKED ISSUE #4334: CDI security interceptor for @RolesAllowed, etc
> There are a few things to bear in mind here, one is that those annotations are not actually interceptor bindings, so you will need to use an ArC build time extension to do the bindings, the other is to figure out how it works with RESTEasy. At the moment there is a RESTeasy Filter thing that handles this, but it would be better to just have the interceptor handle everything and the filter just catch the exception and handle it appropriatle

The source of roles is `io.quarkus.security.identity.SecurityIdentity`

### LINKED ISSUE #4344: Handle non-binding fields for interceptor bindings from non-binding annotations
`InterceptorBindingRegistrar` makes it possible to make annotations binding even if they do not have `@InterceptorBinding`.

I'd like to use it `@RolesAllowed`. The problem is this annotation requires a `value`. 
An interceptor for it should be triggered regardless of the value. I'd like to have an option to specify that the `value` field is non-binding in this situation.

I have briefly discussed it with @mkouba and one option to achieve that would be to extend `InterceptorBindingRegistrar` to provide such information.

I'd like to implement it, creating the issue to provide a space to discuss the problem.

cc @manovotn

### PR DESCRIPTION
**Pull request by michalszynkiewicz**
fixes #4334 
fixes #4344

### CODE REVIEW

File: extensions/resteasy/runtime/src/main/java/io/quarkus/resteasy/runtime/RequestFailer.java [hunk 1]
```diff
@@ -1,78 +0,0 @@
...
-        } catch (Exception e) {
-
-        }
-        AUTHENTICATE = auth;
-        HTTP_SERVLET_REQUEST = httpServletReq;
-        HTTP_SERVLET_RESPONSE = httpServletResp;
-    }
-
-    public static void fail(ContainerRequestContext requestContext) {
-        if (requestContext.getSecurityContext().getUserPrincipal() == null) {
```
Comment (michalszynkiewicz) [inline extensions/resteasy/runtime/src/main/java/io/quarkus/resteasy/runtime/RequestFailer.java]: @stuartwdouglas what was the case in which this was needed? I moved the logic to https://github.com/quarkusio/quarkus/pull/4413/files#diff-cd55a2a1e7a26ebe9e639f503a059ef1R26 and it is working in the tests without it but I'd like to be sure I'm not missing some scenario in which this is still needed.

File: extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityHandler.java [hunk 2]
```diff
@@ -0,0 +1,34 @@
...
+public class SecurityHandler {
+
+    private static final String HANDLER_NAME = SecurityHandler.class.getName();
+    private static final String EXECUTED = "executed";
+
+    @Inject
+    SecurityConstrainer constrainer;
+
+    public Object handle(InvocationContext ic) throws Exception {
+        if (alreadyHandled(ic)) {
```
Comment (geoand) [inline extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityHandler.java]: This might be a stupid question, but why is this check needed?

File: extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityConstrainer.java [hunk 3]
```diff
@@ -0,0 +1,164 @@
...
+        if (securityAnnotation == null) {
+            Class<?> declaringClass = method.getDeclaringClass();
+            securityAnnotation = determineSecurityAnnotation(declaringClass.getDeclaredAnnotations(),
+                    declaringClass::getCanonicalName);
+        }
+        if (securityAnnotation == null) {
+            securityAnnotation = determineSecurityAnnotationFromBindings(interceptorBindings, method::toString);
+        }
+        return checkForAnnotation(securityAnnotation);
+    }
```
Comment (geoand) [inline extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityConstrainer.java]: So far the codebase has tried to not use lambdas in runtime code unless there is a very good reason to (for performance reasons). Would it be possible to change these instances to non-lambda code?

File: extensions/security/runtime/src/main/java/io/quarkus/security/runtime/SecurityBuildTimeConfig.java [hunk 4]
```diff
@@ -0,0 +1,39 @@
...
+     * </pre>
+     */
+    @ConfigItem(name = "deny.unannotated", defaultValue = "false")
+    public boolean denyUnannotated;
+
+    /**
+     * if set to true, access to all JAX-RS resources will be denied by default
+     */
+    @ConfigItem(name = "deny.jaxrs", defaultValue = "false")
+    public boolean denyJaxRs;
```
Comment (geoand) [inline extensions/security/runtime/src/main/java/io/quarkus/security/runtime/SecurityBuildTimeConfig.java]: I don't really see the usefulness of these TBH. Is this something that Thorntail had and proved useful for users?

Comment (stuartwdouglas) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/SecurityBuildTimeConfig.java]: It means that you cannot accidentally expose something because an annotation was forgotten. IMHO this is a useful feature as the 'public by default' approach can be a security risk.

File: extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityHandler.java (hunk 2 above)
Comment (michalszynkiewicz) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityHandler.java]: it's only for preventing the check to be triggered multiple times, e.g. if one annotation is on the class, another on the method

File: extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityConstrainer.java [hunk 5]
```diff
@@ -0,0 +1,164 @@
...
+    public void checkRoles(Method method, Collection<Annotation> interceptorBindings) {
+        getCheck(method, interceptorBindings)
+                .ifPresent(check -> check.apply(identity));
+    }
+
+    private Optional<Check> getCheck(Method method, Collection<Annotation> interceptorBindings) {
+        return checkForMethod.computeIfAbsent(method, m -> determineSecurityCheck(m, interceptorBindings));
+    }
+
+    private Optional<Check> determineSecurityCheck(Method method, Collection<Annotation> interceptorBindings) {
```
Comment (geoand) [inline extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityConstrainer.java]: Is there any thought to leveraging build time information for the types of checks that are being performed here?

Comment (michalszynkiewicz) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityConstrainer.java]: that would definitely be good. 
OTOH, determining the check is done only once for method.

File: extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityConstrainer.java (hunk 3 above)
Comment (michalszynkiewicz) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityConstrainer.java]: These are method references, are they forbidden too?
They can be translated without problem to classes but we'd lose on readability.
And it's executed only on failure, and only once for a method so not sure if it's worth it.

Comment (geoand) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityConstrainer.java]: `determineSecurityAnnotationFromBindings` however is full of lambdas :)

File: extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityConstrainer.java (hunk 5 above)
Comment (stuartwdouglas) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityConstrainer.java]: +1 to doing all this at build time, but I am not sure if our current API's really support it. @mkouba any ideas about this? We really want method level interceptors to be able to override class level interceptors, and also some way of passing in information to the interceptors (i.e. the roles allowed). At the moment this is not really possible with CDI but it would be great if we could support it somehow.

File: extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityConstrainer.java (hunk 3 above)
Comment (stuartwdouglas) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityConstrainer.java]: They use a lot more memory at runtime, and are slower to load which impacts startup time. It is best to avoid them.

File: extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityConstrainer.java [hunk 6]
```diff
@@ -0,0 +1,164 @@
...
+    private static class RolesAllowedCheck implements Check {
+        private final String[] allowedRoles;
+
+        private RolesAllowedCheck(String[] allowedRoles) {
+            this.allowedRoles = allowedRoles;
+        }
+
+        @Override
+        public void apply(SecurityIdentity identity) {
+            if (identity.isAnonymous()) {
```
Comment (stuartwdouglas) [inline extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityConstrainer.java]: I would skip this check. Potentially you can apply roles to unauthenticated identities (e.g. if a request comes from inside the company network you might want to give it slightly higher permissions). By default the role set will be empty anyway.

File: extensions/smallrye-openapi/runtime/pom.xml [hunk 7]
```diff
@@ -40,6 +40,10 @@
       <groupId>io.quarkus</groupId>
       <artifactId>quarkus-swagger-ui</artifactId>
     </dependency>
+    <dependency>
+      <groupId>io.quarkus</groupId>
+      <artifactId>quarkus-resteasy</artifactId>
```
Comment (stuartwdouglas) [inline extensions/smallrye-openapi/runtime/pom.xml]: Why was adding this dep nessesary?

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/BasicAuthenticationMechanism.java [hunk 8]
```diff
@@ -172,8 +172,18 @@ private static void clear(final char[] array) {
                 return CompletableFuture.completedFuture(false);
             }
         }
-        context.response().headers().set(HttpHeaderNames.WWW_AUTHENTICATE, challenge);
-        context.response().setStatusCode(HttpResponseStatus.UNAUTHORIZED.code());
+        context.response().headers().set(challengeHeader(), challengeContent());
```
Comment (stuartwdouglas) [inline extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/BasicAuthenticationMechanism.java]: I think all these changes to the mechanisms will need to be changed to support multiple authentication mechanisms. 

Also the API needs to be changed to allow returning an AuthResult with all the info, as this is much more flexible

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpAuthenticationMechanism.java [hunk 9]
```diff
@@ -15,4 +16,11 @@
 
     CompletionStage<Boolean> sendChallenge(RoutingContext context);
```
Comment (stuartwdouglas) [inline extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpAuthenticationMechanism.java]: Rather than adding these extra methods there should be a ComplectionStage<ChallengeResult> getChallenge(RoutingContext context). The result should contain this extra information. sendChallenge should have a default implementation added that delegates to the results of this method.

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanDeployment.java [hunk 10]
```diff
@@ -57,6 +57,8 @@
 
     private final Map<DotName, ClassInfo> interceptorBindings;
 
+    private final Map<DotName, Set<String>> nonBindingFields;
```
Comment (stuartwdouglas) [inline independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanDeployment.java]: @mkouba can you look over these ArC changes?

File: integration-tests/cdi-security-deny-all-jaxrs/pom.xml [hunk 11]
```diff
@@ -0,0 +1,117 @@
+<?xml version="1.0" encoding="UTF-8"?>
+<project xmlns="http://maven.apache.org/POM/4.0.0"
```
Comment (stuartwdouglas) [inline integration-tests/cdi-security-deny-all-jaxrs/pom.xml]: Does this really need its own integration test modules? Most of this testing should be done as unit testing using QuarkusUnitTest, and native image testing should be possible in one of the existing security modules that already use this functionality.

It is definitely not appropriate to have one integration test module per interceptor, that is way too fine grained an approach for integration tests.

File: test-framework/maven/src/main/java/io/quarkus/maven/it/MojoTestBase.java [hunk 12]
```diff
@@ -293,7 +293,7 @@ public static void assertThatOutputWorksCorrectly(String logs) {
         assertThat(logs.contains(infoLogLevel)).isTrue();
         Predicate<String> datePattern = Pattern.compile("\\d{4}-\\d{2}-\\d{2}\\s\\d{2}:\\d{2}:\\d{2},\\d{3}\\s").asPredicate();
         assertThat(datePattern.test(logs)).isTrue();
-        assertThat(logs.contains("features: [cdi, resteasy, servlet, undertow-websockets]")).isTrue();
+        assertThat(logs.contains("features: [cdi, resteasy, security, servlet, undertow-websockets]")).isTrue();
```
Comment (stuartwdouglas) [inline test-framework/maven/src/main/java/io/quarkus/maven/it/MojoTestBase.java]: I don't really like that JAX-RS now includes security by default, we should look at fixing this, usually we work around this by adding some kind of SPI module.

**Review by stuartwdouglas — CHANGES_REQUESTED** [review]

File: integration-tests/cdi-security-deny-all-jaxrs/pom.xml (hunk 11 above)
Comment (michalszynkiewicz) [reply integration-tests/cdi-security-deny-all-jaxrs/pom.xml]: Config switches for denying all JAX-RS or denying unnanotated, they have to be different for the tests. Is there a way to have one test module that would test different configuration combinations?
Or do you mean that the switches should not be tested in integration tests?

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpAuthenticationMechanism.java (hunk 9 above)
Comment (michalszynkiewicz) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpAuthenticationMechanism.java]: and then translate the exception in a vertx filter/handler instead of JAX-RS exception mapper?

File: integration-tests/cdi-security-deny-all-jaxrs/pom.xml (hunk 11 above)
Comment (stuartwdouglas) [reply integration-tests/cdi-security-deny-all-jaxrs/pom.xml]: Have a look at QuarkusUnitTest. These tests are in the deployment modules, and each test can start Quarkus with a different config. There are some security related ones in the vertx-http module.

File: extensions/smallrye-openapi/runtime/pom.xml (hunk 7 above)
Comment (michalszynkiewicz) [reply extensions/smallrye-openapi/runtime/pom.xml]: there's a dependency between deployments already, without it the TCK failed with missing `SecurityIdentityAssociation` class. That's probably because of the dependency between RestEasy and security extensions. I check if it's still needed after fixing all the issues in the PR

File: extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityConstrainer.java (hunk 6 above)
Comment (michalszynkiewicz) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityConstrainer.java]: don't we have to differentiate between 401 and 403?
Or should 401 be returned for a logged in user without roles too?

File: test-framework/maven/src/main/java/io/quarkus/maven/it/MojoTestBase.java (hunk 12 above)
Comment (michalszynkiewicz) [reply test-framework/maven/src/main/java/io/quarkus/maven/it/MojoTestBase.java]: could you write a bit more on that, or maybe give me an example?

File: extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityConstrainer.java (hunk 6 above)
Comment (stuartwdouglas) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityConstrainer.java]: Maybe do the check at the point you throw the exception.

**Comment by michalszynkiewicz** [comment]
so far having trouble reproducing the test failure locally, this is what happens there: https://gist.github.com/michalszynkiewicz/b69ab0f4b42dc08a4ecd733e80985bf9

File: test-framework/maven/src/main/java/io/quarkus/maven/it/MojoTestBase.java (hunk 12 above)
Comment (stuartwdouglas) [reply test-framework/maven/src/main/java/io/quarkus/maven/it/MojoTestBase.java]: Let's look at it when the other issues have been addressed, I am about to board a flight back to Australia so will be out of contact for a while.

File: extensions/resteasy/runtime/src/main/java/io/quarkus/resteasy/runtime/ForbiddenExceptionMapper.java [hunk 13]
```diff
@@ -0,0 +1,23 @@
...
+ * @author Michal Szynkiewicz, michal.l.szynkiewicz@gmail.com
+ *         <br>
+ *         Date: 05/10/2019
+ */
+@Provider
+@Priority(Priorities.USER + 1)
+public class ForbiddenExceptionMapper implements ExceptionMapper<ForbiddenException> {
+    @Override
+    public Response toResponse(ForbiddenException exception) {
+        return Response.status(403).entity("Access forbidden: role not allowed").build();
```
[the remark this answers is not in the document]
Comment (michalszynkiewicz) [reply extensions/resteasy/runtime/src/main/java/io/quarkus/resteasy/runtime/ForbiddenExceptionMapper.java]: done

File: extensions/security/deployment/src/main/java/io/quarkus/security/deployment/SecurityTransformerUtils.java [hunk 14]
```diff
@@ -0,0 +1,29 @@
...
+
+/**
+ * @author Michal Szynkiewicz, michal.l.szynkiewicz@gmail.com
+ *         <br>
+ *         Date: 11/10/2019
+ */
+public class SecurityTransformerUtils {
+    public static final DotName DENY_ALL = DotName.createSimple(DenyAll.class.getName());
+
+    public static boolean hasSecurityAnnotation(MethodInfo methodInfo) {
```
[the remark this answers is not in the document]
Comment (michalszynkiewicz) [reply extensions/security/deployment/src/main/java/io/quarkus/security/deployment/SecurityTransformerUtils.java]: done

File: extensions/security/runtime/src/main/java/io/quarkus/security/runtime/ForbiddenException.java [hunk 15]
```diff
@@ -0,0 +1,9 @@
+package io.quarkus.security.runtime;
+
+/**
+ * @author Michal Szynkiewicz, michal.l.szynkiewicz@gmail.com
+ *         <br>
+ *         Date: 07/10/2019
```
[the remark this answers is not in the document]
Comment (michalszynkiewicz) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/ForbiddenException.java]: done

File: extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityConstrainer.java [hunk 16]
```diff
@@ -0,0 +1,164 @@
...
+ *         <br>
+ *         Date: 03/10/2019
+ */
+@Singleton
+public class SecurityConstrainer {
+
+    private static final List<Class<? extends Annotation>> SECURITY_ANNOTATIONS = asList(Authenticated.class, DenyAll.class,
+            PermitAll.class, RolesAllowed.class);
+
+    private final Map<Method, Optional<Check>> checkForMethod = new HashMap<>();
```
[the remark this answers is not in the document]
Comment (michalszynkiewicz) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityConstrainer.java]: done

File: extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityConstrainer.java (hunk 3 above)
Comment (michalszynkiewicz) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityConstrainer.java]: true about `determineSecurityAnnotationFromBindings` :) I will de-lambdify it

File: extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityConstrainer.java (hunk 6 above)
Comment (michalszynkiewicz) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityConstrainer.java]: hmm... the exception is thrown here. Do you mean the point of translating the error to response?

File: extensions/security/deployment/src/main/java/io/quarkus/security/deployment/SecurityTransformerUtils.java (hunk 14 above)
[the remark this answers is not in the document]
Comment (michalszynkiewicz) [reply extensions/security/deployment/src/main/java/io/quarkus/security/deployment/SecurityTransformerUtils.java]: done

File: extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityConstrainer.java [hunk 17]
```diff
@@ -0,0 +1,164 @@
...
+
+    @Inject
+    SecurityIdentity identity;
+
+    public void checkRoles(Method method, Collection<Annotation> interceptorBindings) {
+        getCheck(method, interceptorBindings)
+                .ifPresent(check -> check.apply(identity));
```
[the remark this answers is not in the document]
Comment (michalszynkiewicz) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityConstrainer.java]: The next commit will remove the lambdas from here but I'm wondering about the `::toString` and `::getCanonicalName` method references for printing out the location of the error. Is it okay to keep them?

File: extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityConstrainer.java [hunk 18]
```diff
@@ -0,0 +1,164 @@
...
+        if (securityAnnotation instanceof PermitAll) {
+            return Optional.of(new PermitAllCheck());
+        }
+        if (securityAnnotation instanceof Authenticated) {
+            return Optional.of(new AuthenticatedCheck());
+        }
+        return Optional.empty();
+    }
+
+    private Annotation determineSecurityAnnotationFromBindings(Collection<Annotation> interceptorBindings,
```
[the remark this answers is not in the document]
Comment (michalszynkiewicz) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityConstrainer.java]: done

File: extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityConstrainer.java [hunk 19]
```diff
@@ -0,0 +1,164 @@
...
+            Supplier<String> annotationPlacement) {
+        List<Annotation> securityAnnotations = interceptorBindings.stream()
+                .filter(anno -> SECURITY_ANNOTATIONS.stream().anyMatch(c -> c.isInstance(anno)))
+                .collect(Collectors.toList());
+        return getExactlyOne(securityAnnotations, annotationPlacement);
+    }
+
+    private Annotation determineSecurityAnnotation(Annotation[] annotations, Supplier<String> annotationPlacement) {
```
[the remark this answers is not in the document]
Comment (michalszynkiewicz) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityConstrainer.java]: done

File: extensions/resteasy/deployment/src/main/java/io/quarkus/resteasy/deployment/DenyJaxRsTransformer.java [hunk 20]
```diff
@@ -0,0 +1,56 @@
...
+    @Override
+    public void transform(TransformationContext transformationContext) {
+        ClassInfo classInfo = transformationContext.getTarget().asClass();
+        if (!hasSecurityAnnotation(classInfo) && isJaxRsResource(classInfo)) {
+            transformationContext.transform().add(DENY_ALL).done();
+        }
+    }
+
+    private boolean isJaxRsResource(ClassInfo classInfo) {
+        return !Modifier.isInterface(classInfo.flags())
```
[the remark this answers is not in the document]
Comment (michalszynkiewicz) [reply extensions/resteasy/deployment/src/main/java/io/quarkus/resteasy/deployment/DenyJaxRsTransformer.java]: works and simplifies things a lot :)

File: extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/PermitAllInterceptor.java [hunk 21]
```diff
@@ -0,0 +1,27 @@
...
+import javax.interceptor.InvocationContext;
+
+/**
+ * @author Michal Szynkiewicz, michal.l.szynkiewicz@gmail.com
+ *         <br>
+ *         Date: 05/10/2019
+ */
+@Interceptor
+@PermitAll
+@Priority(1)
```
Comment (manovotn) [inline extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/PermitAllInterceptor.java]: Instead of magic numbers, you should probably use a combination of a predefined constant plus/minus a number (applies to all interceptors added here).
See the values here - https://javaee.github.io/javaee-spec/javadocs/javax/interceptor/Interceptor.Priority.html
I am not sure what would be appropriate for security interceptors though; I guess you want them to trigger very soon.

File: extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityConstrainer.java (hunk 5 above)
Comment (manovotn) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityConstrainer.java]: Normally you solve this simply by nature of interceptor resolution - by bindings. But the combinations here don't really allow that - there are 4 interceptors and they all share the same logic which only then decides what should be done.

> some way of passing in information to the interceptors (i.e. the roles allowed)

Not sure I follow? You can store anything inside `InvocationContext` and pass it around between the interceptors if that's what you mean.

As for method and class bindings, we could perhaps store them separately in arc and expose them as we now do the combined version? So at least user can see what was defined where. But otherwise I think interceptors spec already defined that method ones have a priority over class ones, so I suppose if you place the same annotation on a class and a method, then the method one will be taken into account. I would have to poke around the spec to verify that.

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanDeployment.java (hunk 10 above)
Comment (manovotn) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanDeployment.java]: I already did (in Michal's first version of the code and this bit doesn't seem to have changed). In general this is correct and will work. The question is whether we somehow want to weave in annotations transformer directly into the registrar so that we avoid hardcoding non-binding fields and allow others to view that change via annotation store. But I am not quite sure how what would work, WDYT @mkouba ?

File: extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/PermitAllInterceptor.java (hunk 21 above)
Comment (michalszynkiewicz) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/PermitAllInterceptor.java]: `LIBRARY_BEFORE` seems most appropriate, wdyt?

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpAuthenticationMechanism.java (hunk 9 above)
Comment (michalszynkiewicz) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpAuthenticationMechanism.java]: tried that, unfortunately doesn't play well with the undertow exception mapping.
Willadd the `getChallenge` and stay on resteasy exception mapper and read the challenge in a blocking manner for now.

File: extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityConstrainer.java (hunk 5 above)
Comment (mkouba) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityConstrainer.java]: > At the moment this is not really possible with CDI but it would be great if we could support it somehow.

@stuartwdouglas @michalszynkiewicz an interceptor can inject any bean so if we could collect/serialize the info (roles allowed) during build then we could inject/use it at runtime.

Comment (manovotn) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityConstrainer.java]: @mkouba you mean collect them and expose as a bean? That sounds interesting.

File: ci-templates/native-build-steps.yaml [hunk 22]
```diff
@@ -44,4 +44,4 @@ jobs:
       inputs:
         goals: 'install'
         mavenOptions: $(MAVEN_OPTS)
-        options: '-pl integration-tests/${{ join('',integration-tests/'', parameters.modules) }} -B --settings azure-mvn-settings.xml -Dnative-image.docker-build -Dtest-postgresql -Dtest-elasticsearch -Dtest-keycloak -Ddocker-keycloak -Dtest-dynamodb -Dtest-mysql -Dnative-image.xmx=6g -Dnative -Dno-format'
+        options: '-pl integration-tests/${{ join('',integration-tests/'', parameters.modules) }} -B --settings azure-mvn-settings.xml -Dnative-image.docker-build -Dtest-postgresql -Dtest-elasticsearch -Dtest-keycloak -Pdocker-keycloak -Dtest-dynamodb -Dtest-mysql -Dnative-image.xmx=6g -Dnative -Dno-format'
```
Comment (michalszynkiewicz) [inline ci-templates/native-build-steps.yaml]: the oidc tests use `docker-keycloak` as the profile name, the property to control it is `docker`. It seems to me that `-Ddocker-keycloak` was a typo here but maybe there's more magic here...

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpAuthenticationMechanism.java (hunk 9 above)
Comment (michalszynkiewicz) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpAuthenticationMechanism.java]: I added the first part of the rework and tried to address it. Is this what you meant @stuartwdouglas ?

File: integration-tests/cdi-security-deny-all-jaxrs/pom.xml (hunk 11 above)
Comment (michalszynkiewicz) [reply integration-tests/cdi-security-deny-all-jaxrs/pom.xml]: Anyway, will do it tomorrow

File: extensions/resteasy/runtime/src/main/java/io/quarkus/resteasy/runtime/UnauthorizedExceptionMapper.java [hunk 23]
```diff
@@ -0,0 +1,73 @@
...
+                    AUTHENTICATE.invoke(httpServletRequest, httpServletResponse);
+                } catch (Exception e) {
+                    throw new RuntimeException(e);
+                }
+            }
+        }
+        HttpAuthenticator authenticator = identity.getAttribute(HttpAuthenticator.class.getName());
+        RoutingContext context = ResteasyContext.getContextData(RoutingContext.class);
+        if (authenticator != null && context != null) {
+            return Response.status(authenticator.challengeStatus())
```
[the remark this answers is not in the document]
Comment (michalszynkiewicz) [reply extensions/resteasy/runtime/src/main/java/io/quarkus/resteasy/runtime/UnauthorizedExceptionMapper.java]: I think the changed one should be easier to adjust to multiple auth mechanisms, wdyt?

File: integration-tests/cdi-security-deny-all-jaxrs/pom.xml (hunk 11 above)
Comment (stuartwdouglas) [reply integration-tests/cdi-security-deny-all-jaxrs/pom.xml]: yea, so you should add a smoke test into one of the existing security integration tests. We can't add a new module for each discrete feature because otherwise our CI will take hours to run.

File: extensions/elytron-security-properties-file/deployment/src/test/java/io/quarkus/security/test/CustomAuth.java [hunk 24]
```diff
@@ -76,8 +76,18 @@
 
     @Override
     public CompletionStage<Boolean> sendChallenge(RoutingContext context) {
-        context.response().headers().set(HttpHeaderNames.WWW_AUTHENTICATE, "BASIC realm=CUSTOM");
```
[the remark this answers is not in the document]
Comment (michalszynkiewicz) [reply extensions/elytron-security-properties-file/deployment/src/test/java/io/quarkus/security/test/CustomAuth.java]: sendChallenge is not overriden here anymore

File: extensions/security/runtime/src/main/java/io/quarkus/security/runtime/SecurityBuildTimeConfig.java (hunk 4 above)
Comment (michalszynkiewicz) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/SecurityBuildTimeConfig.java]: moved

File: extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityConstrainer.java (hunk 5 above)
Comment (michalszynkiewicz) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityConstrainer.java]: I chatted with @mkouba and @manovotn about it: while it's doable to prepare the data for the check in the build time, it's not that straighforward and the perf impact of doing it as it is is not big.
For this PR I'd rather keep it in the runtime (it's already quite big now) and, if needed, create an issue to move it to build time later on/in a separate PR

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/VertxOAuth2AuthenticationMechanism.java [hunk 25]
```diff
@@ -80,11 +80,26 @@ public VertxOAuth2AuthenticationMechanism setAuth(OAuth2Auth auth) {
 
     @Override
     public CompletionStage<Boolean> sendChallenge(RoutingContext context) {
-        context.response().setStatusCode(302);
-        context.response().headers().set(HttpHeaders.LOCATION, authURI(authServerURI));
+        context.response().setStatusCode(challengeStatus());
```
[the remark this answers is not in the document]
Comment (michalszynkiewicz) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/VertxOAuth2AuthenticationMechanism.java]: the code change a lot there, I'm marking the comment as resolved

File: integration-tests/cdi-security-deny-all-jaxrs/pom.xml (hunk 11 above)
Comment (michalszynkiewicz) [reply integration-tests/cdi-security-deny-all-jaxrs/pom.xml]: done. One test added to the main integration tests, the rest is moved to deployment modules.

File: test-framework/maven/src/main/java/io/quarkus/maven/it/MojoTestBase.java (hunk 12 above)
Comment (michalszynkiewicz) [reply test-framework/maven/src/main/java/io/quarkus/maven/it/MojoTestBase.java]: Just to add some background: I added it to the resteasy extension because before the changes resteasy had RBAC for JAX-RS implemented.

File: docs/src/main/asciidoc/security-guide.adoc [hunk 26]
```diff
@@ -64,6 +64,15 @@ public class SubjectExposingResource {
 <4> This call to obtain the user principal will return null if the caller is unauthenticated, non-null if the caller is authenticated.
 <5> The `/subject/denied` endpoint disallows any access regardless of whether the call is authenticated by specifying the `@DenyAll` annotation.
 
+There are two configuration settings that alter the RBAC behavior:
+
+- `quarkus.security.deny.jaxrs=true|false` - if set to true, the access will be denied for all JAX-RS endpoints will be
```
[the remark this answers is not in the document]
Comment (michalszynkiewicz) [reply docs/src/main/asciidoc/security-guide.adoc]: The original text here was only about JAX-RS and the code example is about JAX-RS. Do you think the example should be changed to a pure CDI bean too? Or are you referring to the `deny.jaxrs` switch only?

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/BasicAuthenticationMechanism.java (hunk 8 above)
Comment (michalszynkiewicz) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/BasicAuthenticationMechanism.java]: I think, with the current changes, it should be easier to support multiple authentication mechanisms, but I'm not entirely sure how would that work so I'm not certain that's what you meant.
By AuthResult did you mean something like the added `ChallengeData`?

File: extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityConstrainer.java (hunk 6 above)
Comment (stuartwdouglas) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityConstrainer.java]: I mean change the code so it first checks the roles, as it is possible to have an anonymous identity that still has some roles (e.g. an anonymous identity from inside the company network might have more permissions than an external one). If the role check fails then decide which exception to throw.

Comment (michalszynkiewicz) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityConstrainer.java]: got it now, thanks.

Comment (michalszynkiewicz) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityConstrainer.java]: will be fixed in the next commit

File: extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityConstrainer.java (hunk 5 above)
Comment (michalszynkiewicz) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityConstrainer.java]: I created https://github.com/quarkusio/quarkus/issues/4695 to dicuss it further/implement it later

File: extensions/smallrye-openapi/runtime/pom.xml (hunk 7 above)
Comment (michalszynkiewicz) [reply extensions/smallrye-openapi/runtime/pom.xml]: still needed at this point.

File: docs/src/main/asciidoc/security-guide.adoc (hunk 26 above)
[the remark this answers is not in the document]
Comment (michalszynkiewicz) [reply docs/src/main/asciidoc/security-guide.adoc]: Turns out we don't have a Rest guid at the moment. There is one for REST+JSON, one for MP JWT that also touches REST security. 
Did you mean using one of these or creating a separate REST Security guide?
I'd be happy to do it (when I understand what :) ) but if you find it acceptable I'd rather do this change in a separate PR.

File: independent-projects/bootstrap/pom.xml [hunk 27]
```diff
@@ -85,8 +86,18 @@
                         <groupId>org.sonatype.plexus</groupId>
                         <artifactId>plexus-cipher</artifactId>
                     </exclusion>
+                    <exclusion>
```
Comment (michalszynkiewicz) [inline independent-projects/bootstrap/pom.xml]: needed because jsr250 brought in old security annotations (e.g. `@DenyAll` that couldn't be placed on classes)

**Comment by michalszynkiewicz** [comment]
I squashed the commits not to pollute the changelog. Hope it doesn't make reviewing more difficult

File: docs/src/main/asciidoc/security-guide.adoc (hunk 26 above)
[the remark this answers is not in the document]
Comment (stuartwdouglas) [reply docs/src/main/asciidoc/security-guide.adoc]: It's probably fine to keep it here, but maybe the property should be something like quarkus.jaxrs.deny-uncovered.

File: extensions/resteasy/deployment/pom.xml [hunk 28]
```diff
@@ -38,6 +38,10 @@
             <groupId>com.oracle.substratevm</groupId>
             <artifactId>svm</artifactId>
         </dependency>
+        <dependency>
+            <groupId>io.quarkus</groupId>
+            <artifactId>quarkus-security-deployment</artifactId>
```
Comment (stuartwdouglas) [inline extensions/resteasy/deployment/pom.xml]: RESTeasy should not have a hard dependency on the security extension. I think the exceptions should probably be moved to the quarkus-security project to avoid the runtime dependency, and just copy the trivial utility method used in the -deployment module.

File: extensions/smallrye-openapi/runtime/pom.xml (hunk 7 above)
Comment (stuartwdouglas) [reply extensions/smallrye-openapi/runtime/pom.xml]: Can you re-check after making the dependency changes I mention above?

**Review by stuartwdouglas — CHANGES_REQUESTED** [review]
Once the dependency issues are addressed we should be good to go.

File: docs/src/main/asciidoc/security-guide.adoc (hunk 26 above)
[the remark this answers is not in the document]
Comment (michalszynkiewicz) [reply docs/src/main/asciidoc/security-guide.adoc]: ok, I will switch deny.unannotated to deny-unannotated to be consistent

File: extensions/resteasy/deployment/pom.xml (hunk 28 above)
Comment (michalszynkiewicz) [reply extensions/resteasy/deployment/pom.xml]: done, now it's only a test dependency

Comment (michalszynkiewicz) [reply extensions/resteasy/deployment/pom.xml]: done

**Comment by michalszynkiewicz** [comment]
Requires a new release of Quarkus Security that would include https://github.com/quarkusio/quarkus-security/pull/2

**Review by stuartwdouglas — APPROVED** [review]
