### PR TITLE
Make sure the proper TCCL isn't lost in dev mode when static resource exist

### LINKED ISSUE #15164: Hibernate Reactive: NamedQuery fails after hot reload
**Describe the bug**
Same issue as already described by @cescoffier in #13355, but I was actually able to reproduce it reliably 😄 

After the application is reloaded in dev mode due to a code change, named queries do not work anymore. You don't even need to change something in the queried entity itself, just any change that leads to an entire reload of the application will be sufficient.

**Expected behavior**
NamedQuery should work just as before hot reload.

**Actual behavior**
Executing a NamedQuery leads to the following exception:

```
2021-02-18 10:46:11,037 ERROR [org.jbo.res.rea.ser.cor.ExceptionMapping] (vert.x-eventloop-thread-11) Request failed : java.lang.IllegalArgumentException: Type specified for TypedQuery [com.example.Fruit] is incompatible with query return type [class com.example.Fruit]
	at org.hibernate.internal.AbstractSharedSessionContract.resultClassChecking(AbstractSharedSessionContract.java:863)
	at org.hibernate.reactive.session.impl.ReactiveSessionImpl.createReactiveQuery(ReactiveSessionImpl.java:461)
	at org.hibernate.reactive.session.impl.ReactiveSessionImpl.buildReactiveQueryFromName(ReactiveSessionImpl.java:443)
	at org.hibernate.reactive.session.impl.ReactiveSessionImpl.createReactiveNamedQuery(ReactiveSessionImpl.java:430)
	at org.hibernate.reactive.mutiny.impl.MutinySessionImpl.createNamedQuery(MutinySessionImpl.java:222)
	at io.quarkus.hibernate.reactive.runtime.ReactiveSessionProducer_ProducerMethod_createMutinySession_1321d110ee9e92bda147899150401e0a136779c7_ClientProxy.createNamedQuery(ReactiveSessionProducer_ProducerMethod_createMutinySession_1321d110ee9e92bda147899150401e0a136779c7_ClientProxy.zig:997)
	at com.example.FruitDao.get(FruitDao.java:20)
	at com.example.FruitDao_ClientProxy.get(FruitDao_ClientProxy.zig:217)
	at com.example.FruitResource.get(FruitResource.java:32)
	at com.example.FruitResource_ClientProxy.get(FruitResource_ClientProxy.zig:217)
	at com.example.FruitResource$quarkusrestinvoker$get_2420412d5b210b3632823e74ede45d605c6ff069.invoke(FruitResource$quarkusrestinvoker$get_2420412d5b210b3632823e74ede45d605c6ff069.zig:33)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:7)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:117)
	at org.jboss.resteasy.reactive.server.handlers.RestInitialHandler.beginProcessing(RestInitialHandler.java:47)
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:17)
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:7)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1038)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:137)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:132)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder.lambda$start$1(StaticResourcesRecorder.java:62)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1038)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:101)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:132)
	at io.vertx.ext.web.handler.impl.StaticHandlerImpl.lambda$sendStatic$1(StaticHandlerImpl.java:206)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:327)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**To Reproduce**

Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific).

https://github.com/markusdlugi/hibernate-reactive-hot-swap

1. Start PostgreSQL database using `infrastructure/docker-compose.yml`
2. Start application in dev mode using `mvn quarkus:dev`
3. Execute `GET http://localhost:8080/fruits` - should still work with HTTP 200
4. Make a code change to trigger hot reload, e.g. by removing line 49 in `com.example.FruitDao`
5. Execute `GET http://localhost:8080/fruits` again - application will reload in the background and fail with exception

**Configuration**
```properties
# Add your application.properties here, if applicable.
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=test
quarkus.datasource.password=test
quarkus.datasource.reactive.url=vertx-reactive:postgresql://localhost:5432/hibernate-reactive-hot-swap
quarkus.hibernate-orm.database.generation=create
```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Microsoft Windows [Version 10.0.17763.1757]
 - Output of `java -version`: OpenJDK 64-Bit Server VM Corretto-11.0.10.9.1 (build 11.0.10+9-LTS, mixed mode)
 - GraalVM version (if different from Java): N/A
 - Quarkus version or git rev: 1.11.3.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

**Additional context**
For some reason, the issue only appears if both of the following conditions are met:

- The application has a dependency to `io.quarkus:quarkus-smallrye-health`
- The folder META-INF/resources exists (can be empty)

If either of these is removed, the issue just disappears. No idea why.

I don't think that these are the only conditions where this issue appears, most likely this can also happen under different circumstances, but those were the conditions where it failed in our application.

### LINKED ISSUE #15763: RESTEasy Reactive exception mapper issues
This one happens only in DEV mode. Start with this endpoint:

```java
@Path("/")
public class GreetingResource {

    @Path("fruit/{id}")
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    public Uni<Object> fruit(@PathParam("id") Long id){
        throw new NotFoundException();
    }
    
//    @ServerExceptionMapper(NotFoundException.class)
//    public Response handleNotFound() {
//        System.err.println("We're in there");
//        return Response.status(Response.Status.NOT_FOUND)
//                .entity(new JsonObject()
//                        .put("type", "https://example.com/probs/cant-touch-this")
//                        .put("title", "we could not find it :("))
//                .type(MediaType.APPLICATION_JSON)
//                .build();
//    }
}
```

Now trigger the 404 with `GET /fruit/123`, you get the DEV Mode 404 red page.

Now uncomment the exception mapper and reload the page, you get:

```
Error handling 56fcd1fd-68f3-4922-926f-a263fa4ab22c-2, java.lang.RuntimeException: java.lang.RuntimeException: java.lang.ClassNotFoundException: org.acme1.GreetingResource$GeneratedExceptionHandlerFor$NotFoundException$OfMethod$handleNotFound
```

This looks very similar to #15748, but only for DEV mode. Perhaps it's different?

Now, a more annoying thing is that if I change the endpoint method to:

```java
    @Path("fruit/{id}")
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    public Uni<Object> fruit(@PathParam("id") Long id){
        return Uni.createFrom().failure(() -> new NotFoundException());
    }
```

It behaves differently and doesn't even try to run my exception mapper, when it should be identical to the previous endpoint.

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #15763
Fixes: #15164

### CODE REVIEW

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/StaticResourcesRecorder.java [hunk 1]
```diff
@@ -52,13 +52,16 @@ public void staticInit(Set<String> knownPaths) {
...
         if (!knownPaths.isEmpty()) {
+            ClassLoader currentCl = Thread.currentThread().getContextClassLoader();
             StaticHandler staticHandler = StaticHandler.create(META_INF_RESOURCES).setDefaultContentEncoding("UTF-8");
             handlers.add(ctx -> {
                 String rel = ctx.mountPoint() == null ? ctx.normalisedPath()
                         : ctx.normalisedPath().substring(ctx.mountPoint().length());
                 if (knownPaths.contains(rel)) {
                     staticHandler.handle(ctx);
                 } else {
+                    // make sure we don't loose the correct TCCL to Vert.x...
```
Comment (gsmet) [inline extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/StaticResourcesRecorder.java:63]:
```suggestion
                    // make sure we don't lose the correct TCCL to Vert.x...
```

**Review by stuartwdouglas — APPROVED** [review]

**Comment by geoand** [comment]
After learning that #15164 was also fixed by this, I am assuming that there might be more subtly issues fixed by this PR that we don't know or have forgot about
