### PR TITLE
Propagate OpenTelemetry context to gRPC services

### LINKED ISSUE #26222: gRPC Context propagation does not work
### Describe the bug

We use OpenTelemetry with Quarkus version of 2.9.2 that already has a support for gRPC.
We has a gRPC server that get a request with OpenTelemetry's context and the context isn't propagated to the service's handler.

In addition, I used the `GrpcTracingServerInterceptor` interceptor and saw that the interceptor gets the context. 
I think the problem is that this interceptor close the scope `scope.close()` and doesn't pass any contextual data to the handler level.

### Expected behavior

I expect to be able to use `Context.current()` inside the gRPC service's handler and get the context.

### Actual behavior

`Context.current()` returns an empty context.

### How to Reproduce?

1. Setup a gRPC service
2. Send a request with context to the service
3. Debug and look on the value of `Context.current()` inside the service's handler

### Output of `uname -a` or `ver`

Darwin ShakharArad 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk 14.0.2 2020-07-14 OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.2+12) OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14.0.2+12, mixed mode, sharing)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.9.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

------------------------------------------------------------ Gradle 7.3.3 ------------------------------------------------------------  Build time:   2021-12-22 12:37:54 UTC Revision:     6f556c80f945dc54b50e0be633da6c62dbe8dc71  Kotlin:       1.5.31 Groovy:       3.0.9 Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021 JVM:          14.0.2 (AdoptOpenJDK 14.0.2+12) OS:           Mac OS X 10.16 x86_64

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by radcortez**
- Fixes #26222

### CODE REVIEW

**Review by c0va23 — APPROVED** [review]
I test this patch on ours projects. Its work.

File: extensions/opentelemetry/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/grpc/GrpcTracingServerInterceptor.java [hunk 1]
```diff
@@ -147,7 +145,8 @@ public void onComplete() {
 
         @Override
         public void onReady() {
-            try {
+            Scope scope = spanContext.makeCurrent();
+            try (scope) {
```
Comment (cescoffier) [inline extensions/opentelemetry/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/grpc/GrpcTracingServerInterceptor.java:149]: Can you check that `scope.close()` (which will be called automatically) is non-blocking?

**Review by cescoffier — CHANGES_REQUESTED** [review]

File: extensions/opentelemetry/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/grpc/GrpcTracingServerInterceptor.java (hunk 1 above)
Comment (radcortez) [reply extensions/opentelemetry/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/grpc/GrpcTracingServerInterceptor.java:149]: It is the same implementation we use for Vert.x, provided by https://github.com/quarkusio/quarkus/blob/main/extensions/opentelemetry/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/QuarkusContextStorage.java#L51-L83

**Review by cescoffier — APPROVED** [review]

File: extensions/opentelemetry/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/grpc/GrpcTracingServerInterceptor.java [hunk 2]
```diff
@@ -116,7 +111,8 @@ protected TracingServerCallListener(final ServerCall.Listener<ReqT> delegate, fi
 
         @Override
         public void onHalfClose() {
-            try {
+            Scope scope = spanContext.makeCurrent();
+            try (scope) {
```
Comment (brunobat) [inline extensions/opentelemetry/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/grpc/GrpcTracingServerInterceptor.java:115]:
```suggestion
            try (Scope scope = spanContext.makeCurrent()) {
```
Just to prevent someone to use a closed scope after the try.

File: extensions/opentelemetry/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/grpc/GrpcTracingServerInterceptor.java [hunk 3]
```diff
@@ -126,18 +122,20 @@ public void onHalfClose() {
 
         @Override
         public void onCancel() {
-            try {
+            Scope scope = spanContext.makeCurrent();
+            try (scope) {
```
Comment (brunobat) [inline extensions/opentelemetry/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/grpc/GrpcTracingServerInterceptor.java:126]:
```suggestion
            try (Scope scope = spanContext.makeCurrent()) {
```
Just to prevent someone to use a closed scope after the try.

**Review by brunobat — COMMENTED** [review]
Added some suggestions

File: extensions/opentelemetry/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/grpc/GrpcTracingServerInterceptor.java (hunk 3 above)
Comment (brunobat) [inline extensions/opentelemetry/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/grpc/GrpcTracingServerInterceptor.java:126]:
```suggestion
            try (Scope scope = spanContext.makeCurrent()) {
```
Just to prevent someone to use a closed scope after the try.

**Review by brunobat — APPROVED** [review]
