### PR TITLE
Move initial configuration setup out of build steps

### LINKED ISSUE #3008: No config value of type [java.lang.String] exists for: quarkus.application.name
**Describe the bug**
I have generated a config example file with `./mvnw quarkus:generate-config` and check that it has the properties:
```
#
# The name of the application.
# If not set, defaults to the name of the project.
#
#quarkus.application.name=

#
# The version of the application.
# If not set, defaults to the version of the project
#
#quarkus.application.version=
```

**Expected behavior**
These example file reads that if not set, defaults to the name/version of the project.

The defaults of the project is assumed to be from Maven `${project.version}` and `${project.artifactId}`.

**Actual behavior**
Trying to inject the value 
```
@ConfigProperty(name = "quarkus.application.name")
String appName;
```
leads to:
```
javax.enterprise.inject.spi.DeploymentException: No config value of type [java.lang.String] exists for: quarkus.application.name
	at io.quarkus.arc.runtime.ConfigDeploymentTemplate.validateConfigProperties(ConfigDeploymentTemplate.java:37)
	at io.quarkus.deployment.steps.ConfigBuildStep$validateConfigProperties10.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.ConfigBuildStep$validateConfigProperties10.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl1.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:84)
	at io.quarkus.runtime.Application.run(Application.java:196)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
Exception in thread "main" java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl1.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:84)
	at io.quarkus.runtime.Application.run(Application.java:196)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
Caused by: javax.enterprise.inject.spi.DeploymentException: No config value of type [java.lang.String] exists for: quarkus.application.name
	at io.quarkus.arc.runtime.ConfigDeploymentTemplate.validateConfigProperties(ConfigDeploymentTemplate.java:37)
	at io.quarkus.deployment.steps.ConfigBuildStep$validateConfigProperties10.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.ConfigBuildStep$validateConfigProperties10.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl1.doStart(Unknown Source)
	... 3 more
```

**Environment (please complete the following information):**
```
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-20190523183340.buildslave.jdk8u-src-tar--b03)
OpenJDK 64-Bit GraalVM CE 19.0.2 (build 25.212-b03-jvmci-19-b04, mixed mode)
```

### PR DESCRIPTION
**Pull request by dmlloyd**
Also fix handling of quarkus.application.*

Fixes #3008, groundwork for #3233

### CODE REVIEW

**Comment by dmlloyd** [comment]
Looks like a native failure I missed. Will look more tomorrow

File: devtools/gradle/src/main/java/io/quarkus/gradle/tasks/QuarkusBuild.java [hunk 1]
```diff
@@ -152,6 +152,8 @@ public void buildQuarkus() {
                 realProperties.setProperty(key, (String) value);
             }
         }
+        realProperties.putIfAbsent("quarkus.application.name", appArtifact.getArtifactId());
+        realProperties.putIfAbsent("quarkus.application.version", appArtifact.getVersion());
```
Comment (aloubyansky) [inline devtools/gradle/src/main/java/io/quarkus/gradle/tasks/QuarkusBuild.java]: BTW, these values most probably won't be meaningful. But we can review that later.

**Review by aloubyansky — APPROVED** [review]
