### PR TITLE
Prevent SSE writing from potentially causing accumulation of headers

### LINKED ISSUE #31559: `SseUtil` unexpectedly stores headers in `Serialisers.EMPTY_MULTI_MAP`
### Describe the bug

The `SseUtil` class is using `Serialisers.EMPTY_MULTI_MAP` variable, here:

https://github.com/quarkusio/quarkus/blob/ca208585b097c778c72f578a487c7263a74192fd/independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/SseUtil.java#L140-L141

This leads to storing of subsequent headers in this map `Serialisers.EMPTY_MULTI_MAP`. This leads to uncapped memory consumption, use of the whole available heap (possible DDoS). Also, invocations have access to previously set headers, which is a privacy concern.

### Expected behavior

Sending with `SseUtil` should be safe and not lead to data leaks or DDoS.

### Actual behavior

Sending with `SseUtil` will lead to data leaks or DDoS.

### How to Reproduce?

```java
@GET
@RestStreamElementType(MediaType.APPLICATION_JSON)
Multi<CloudEvent> events() {
  return Multi.createFrom().iterable(events);
}
```

See also: https://github.com/cardil/openshift-knative-showcase/commit/15e00429c459abf655fb483a27f467d598ae173e

### Output of `uname -a` or `ver`

Linux thinkpad-t590 6.1.13-200.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Feb 22 17:53:57 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

```
openjdk version "17.0.5" 2022-10-18
OpenJDK Runtime Environment Temurin-17.0.5+8 (build 17.0.5+8)
OpenJDK 64-Bit Server VM Temurin-17.0.5+8 (build 17.0.5+8, mixed mode, sharing)
```

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.13.5.Final-redhat-00002

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.7 (b89d5959fcde851dcb1c8946a785a163f14e1e29)

### Additional information

/area resteasy-reactive

### PR DESCRIPTION
**Pull request by geoand**
This could happen if a MessageBodyWriter writes the headers map (which does not make sense for streaming responses, but it's nevertheless allowed by the contract of the MessageBodyWriter)

Fixes: #31559

### CODE REVIEW

**Review by Sgitario — APPROVED** [review]

**Review by FroMage — APPROVED** [review]

File: independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/SseUtil.java [hunk 1]
```diff
@@ -138,7 +139,7 @@ private static String serialiseDataToString(ResteasyReactiveRequestContext conte
             if (writer.isWriteable(entityClass, entityType, Serialisers.NO_ANNOTATION, mediaType)) {
                 // FIXME: spec doesn't really say what headers we should use here
                 writer.writeTo(entity, entityClass, entityType, Serialisers.NO_ANNOTATION, mediaType,
-                        Serialisers.EMPTY_MULTI_MAP, baos);
+                        new QuarkusMultivaluedHashMap<>(), baos);
```
Comment (cardil) [inline independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/SseUtil.java:142]: Instead of passing empty map as headers, we should pass a copy of currently set headers.

In that way, an implementation of `MessageBodyWriter` could detect it should serialize the object for Server Sent Events, so it makes no sense to set headers.

Also, it makes sense to warn people that those headers will be dropped. For example, to check if the headers been changed after calling write, we can log a WARN message.

Comment (geoand) [reply independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/SseUtil.java:142]: If you can provide a test showing why this is important, we can certainly reconsider

Comment (cardil) [reply independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/SseUtil.java:142]: See https://github.com/quarkusio/quarkus/issues/31587 and https://github.com/cloudevents/sdk-java/issues/533 for more context
