### PR TITLE
Make Keycloak DevService work with @QuarkusIntegrationTest and container launches

### LINKED ISSUE #21935: Keycloak DevService not considered healthy when running in docker shared network mode
### Describe the bug

When running the QuarkusIntegrationTest against the keycloak dev service using docker network (e.g. by setting `quarkus.container-image.build=true`) the http based health check fails:
```
2021-12-05 19:07:47,923 ERROR [🐳 .io/.0.2]] (build-7) Could not start container: java.lang.IllegalArgumentException: Requested port (8080) is not mapped
	at org.testcontainers.containers.ContainerState.getMappedPort(ContainerState.java:153)
	at java.base/java.util.Optional.map(Optional.java:265)
	at org.testcontainers.containers.wait.strategy.HttpWaitStrategy.waitUntilReady(HttpWaitStrategy.java:177)
	at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:51)
	at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:929)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:468)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:331)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:329)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:317)
	at io.quarkus.oidc.deployment.devservices.keycloak.KeycloakDevServicesProcessor.lambda$startContainer$0(KeycloakDevServicesProcessor.java:303)
```

I tried a quick fix by adding:
```java
@Override
public Integer getMappedPort(int originalPort) {
    if (useSharedNetwork) {                      
        return KEYCLOAK_PORT;
    } else {
        return super.getMappedPort(originalPort);
    }
}
```

near https://github.com/quarkusio/quarkus/blob/main/extensions/oidc/deployment/src/main/java/io/quarkus/oidc/deployment/devservices/keycloak/KeycloakDevServicesProcessor.java#L489

This solves the above exception, but it reveals another issue: The health check still fails because it tries to reach the `/auth` url on the internal network address (e.g. http://keycloak-8yVNc:8080/auth):
```
Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for URL to be accessible (http://keycloak-8yVNc:8080/auth should return HTTP 200)
	at org.testcontainers.containers.wait.strategy.HttpWaitStrategy.waitUntilReady(HttpWaitStrategy.java:264)
```

This seems logical, since the healthcheck is made from outside the docker network. I also checked how other devservices are doing this, but none is using the HttpWaitStrategy.

### Expected behavior

Keycloak DevService gets recognized as healthy and the test can continue

### Actual behavior

Exception, see above

### How to Reproduce?

https://github.com/flo-02-mu/security-openid-connect-quickstart-networkerror

1. `mvn verify`

### Output of `uname -a` or `ver`

20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk 12.0.2 2019-07-16 OpenJDK Runtime Environment (build 12.0.2+10) OpenJDK 64-Bit Server VM (build 12.0.2+10, mixed mode, sharing)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.5.1.Final (also tried on latest master)

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.2 (40f52333136460af0dc0d7232c0dc0bcf0d9e117; 2019-08-27T17:06:16+02:00)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #21935

Supercedes: https://github.com/quarkusio/quarkus/pull/21995

P.S. The integration test was copied almost verbatim from the reproducer added in #21935

### CODE REVIEW

File: extensions/oidc/deployment/src/main/java/io/quarkus/oidc/deployment/devservices/keycloak/KeycloakDevServicesProcessor.java [hunk 1]
```diff
@@ -72,6 +74,8 @@
     private static final String CONFIG_PREFIX = "quarkus.oidc.";
     private static final String TENANT_ENABLED_CONFIG_KEY = CONFIG_PREFIX + "tenant-enabled";
     private static final String AUTH_SERVER_URL_CONFIG_KEY = CONFIG_PREFIX + "auth-server-url";
+    // avoid the Quarkus prefix in order to prevent warnings when the application starts in container integration tests
+    private static final String CLIENT_AUTH_SERVER_URL_CONFIG_KEY = "client." + CONFIG_PREFIX + "auth-server-url";
```
Comment (sberyozkin) [inline extensions/oidc/deployment/src/main/java/io/quarkus/oidc/deployment/devservices/keycloak/KeycloakDevServicesProcessor.java:78]: Will this property have the same value as `quarkus.oidc.auth-server-url` if no shared network is used ?

Comment (geoand) [reply extensions/oidc/deployment/src/main/java/io/quarkus/oidc/deployment/devservices/keycloak/KeycloakDevServicesProcessor.java:78]: It will be set, but to the proper value

File: extensions/oidc/deployment/src/main/java/io/quarkus/oidc/deployment/devservices/keycloak/KeycloakDevServicesProcessor.java [hunk 2]
```diff
@@ -363,20 +385,29 @@ public StartResult(String url, boolean createDefaultRealm, String realmNameToUse
...
+
             this.useSharedNetwork = useSharedNetwork;
             this.configuredRealmName = configuredRealmName;
             this.realmPath = realmPath;
             this.containerLabelValue = containerLabelValue;
             this.sharedContainer = sharedContainer;
             this.javaOpts = javaOpts;
             this.keycloakX = isKeycloakX(dockerImageName);
+
+            if (sharedContainer && fixedExposedPort.isEmpty()) {
```
Comment (sberyozkin) [inline extensions/oidc/deployment/src/main/java/io/quarkus/oidc/deployment/devservices/keycloak/KeycloakDevServicesProcessor.java:403]: It looks fine; I've been trying to figure out if it can be a problem but if I understand it correctly effectively you are doing what test containers do if no fixed port is set.

File: extensions/oidc/deployment/src/main/java/io/quarkus/oidc/deployment/devservices/keycloak/KeycloakDevServicesProcessor.java [hunk 3]
```diff
@@ -445,7 +477,15 @@ protected void configure() {
             }
 
             LOG.infof("Using %s powered Keycloak distribution", keycloakX ? "Quarkus" : "WildFly");
-            super.setWaitStrategy(Wait.forHttp(keycloakX ? "/" : "/auth").forPort(KEYCLOAK_PORT));
+            super.setWaitStrategy(Wait.forLogMessage(".*Keycloak.*started.*", 1));
```
Comment (sberyozkin) [inline extensions/oidc/deployment/src/main/java/io/quarkus/oidc/deployment/devservices/keycloak/KeycloakDevServicesProcessor.java:480]: Good stuff

File: test-framework/keycloak-server/src/main/java/io/quarkus/test/keycloak/client/KeycloakTestClient.java [hunk 4]
```diff
@@ -16,7 +16,7 @@
 
 public class KeycloakTestClient implements DevServicesContext.ContextAware {
 
-    private final static String AUTH_SERVER_URL_PROP = "quarkus.oidc.auth-server-url";
+    private final static String AUTH_SERVER_URL_PROP = "client.quarkus.oidc.auth-server-url";
```
Comment (sberyozkin) [inline test-framework/keycloak-server/src/main/java/io/quarkus/test/keycloak/client/KeycloakTestClient.java:19]: It may not be quite right to remove `quarkus.oidc.auth-server-url`, as it won't work if custom test resource factories set `quarkus.oidc.auth-server-url` after launching a container.

Can you please update the code to fallback to `quarkus.oidc.auth-server-url` if the `client.quarkus.oidc.auth-server-url` is not available ?
Or may be it is better to just ignore the warnings you've mentioned ? If it works with the warnings then I'd leave `quarkus.oidc.auth-server-url`...

**Comment by sberyozkin** [comment]
Thanks @geoand for the time, it looks good. I've left a few minor comments.
Also, if you don't mind, can you please run `quarkus-quickstarts/security-openid-connect-quickstart` which tests it without the shared network, might also be worth checking if you can login into Keycloak after `mvn quarkus-dev` and then selecting Keycloak from Dev UI console (as `alice:alice` for example), https://quarkus.io/guides/security-openid-connect-dev-services#dev-services-for-keycloak  (click on that green `Login into SPA` and you'll be redirected to Keycloak)...

File: extensions/oidc/deployment/src/main/java/io/quarkus/oidc/deployment/devservices/keycloak/KeycloakDevServicesProcessor.java (hunk 2 above)
Comment (geoand) [reply extensions/oidc/deployment/src/main/java/io/quarkus/oidc/deployment/devservices/keycloak/KeycloakDevServicesProcessor.java:403]: Exactly

File: extensions/oidc/deployment/src/main/java/io/quarkus/oidc/deployment/devservices/keycloak/KeycloakDevServicesProcessor.java (hunk 3 above)
Comment (geoand) [reply extensions/oidc/deployment/src/main/java/io/quarkus/oidc/deployment/devservices/keycloak/KeycloakDevServicesProcessor.java:480]: Thanks for looking into it!

File: test-framework/keycloak-server/src/main/java/io/quarkus/test/keycloak/client/KeycloakTestClient.java (hunk 4 above)
Comment (geoand) [reply test-framework/keycloak-server/src/main/java/io/quarkus/test/keycloak/client/KeycloakTestClient.java:19]: Sure, I'll update the code

**Comment by geoand** [comment]
> Thanks @geoand

You are welcome!

> Also, if you don't mind, can you please run `quarkus-quickstarts/security-openid-connect-quickstart` 

I already did that when testing the PR :). I ran both the tests and used the DevUI to test `alice` and `admin`

**Comment by sberyozkin** [comment]
Nice, thanks :-)

**Comment by geoand** [comment]
👍🏼

**Review by sberyozkin — APPROVED** [review]
LGTM, thanks.

I propose to wait till tomorrow for Stuart to have a quick look at the TCCL related update, I'll merge the first thing tomorrow morning if there will be no comments...

**Comment by geoand** [comment]
Let's also wait for the 👍 from @gsmet who is in the process of moving extensions, so we don't want to make his life harder

**Comment by gsmet** [comment]
@stuartwdouglas if you're good with this one, please merge it. I will start the release tomorrow morning early Paris time.

**Comment by geoand** [comment]
@stuartwdouglas could you take a look please?
It would be nice to get this in 2.6.0.CR1

**Comment by geoand** [comment]
Since this is something that would be good to have in for `2.6.0.CR1` to validate the approach and ensure that no new issues will creep up, I'm going to merge it now.
We can certainly improve on the specifics easily, but the various fixes themselves are necessary for a better `@QuarkusIntegrationTest` + `Keycloak DevServices` experience
