### PR TITLE
Move Dev UI Logging closer to Console logging

### LINKED ISSUE #18609: dev ui log does not respect the log cleanup filters
### Describe the bug

Some log entries are normally filtered in quarkus, see LogCleanupFilterBuildItem.

These entries are correctly filtered in the terminal running dev mode, but they are present in the log of dev ui.

For example, the following is additionally logged for resteasy:
```
 2021-07-12 13:42:06,453 INFO  [org.jbo.res.res.i18n] (too-much-logging-dev.jar) (Quarkus Main Thread) RESTEASY002225: Deploying javax.ws.rs.core.Application: class org.acme.RestApplication_Subclass
```

### Expected behavior

Following is the output from the terminal running dev mode.
```
2021-07-12 13:42:05,850 INFO  [io.qua.dep.dev.RuntimeUpdatesProcessor] (Aesh InputStream Reader) Restarting quarkus due to changes in .
2021-07-12 13:42:05,863 INFO  [io.quarkus] (Quarkus Main Thread) too-much-logging stopped in 0.012s
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2021-07-12 13:42:06,488 INFO  [io.quarkus] (Quarkus Main Thread) too-much-logging 1.0.0-SNAPSHOT on JVM (powered by Quarkus 2.0.1.Final) started in 0.621s. Listening on: http://localho
st:8080
2021-07-12 13:42:06,490 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2021-07-12 13:42:06,492 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, resteasy, smallrye-context-propagation]
2021-07-12 13:42:06,494 INFO  [io.qua.dep.dev.RuntimeUpdatesProcessor] (Aesh InputStream Reader) Live reload total time: 0.649s
```

### Actual behavior

In dev ui, there is an additional line from resteasy:
```
 2021-07-12 13:42:05,850 INFO  [io.qua.dep.dev.RuntimeUpdatesProcessor] (too-much-logging-dev.jar) (Aesh InputStream Reader) Restarting quarkus due to changes in .
 2021-07-12 13:42:05,863 INFO  [io.quarkus] (too-much-logging-dev.jar) (Quarkus Main Thread) too-much-logging stopped in 0.012s
 2021-07-12 13:42:06,453 INFO  [org.jbo.res.res.i18n] (too-much-logging-dev.jar) (Quarkus Main Thread) RESTEASY002225: Deploying javax.ws.rs.core.Application: class org.acme.RestApplication_Subclass
 2021-07-12 13:42:06,488 INFO  [io.quarkus] (too-much-logging-dev.jar) (Quarkus Main Thread) too-much-logging 1.0.0-SNAPSHOT on JVM (powered by Quarkus 2.0.1.Final) started in 0.621s. Listening on: http://localhost:8080
 2021-07-12 13:42:06,490 INFO  [io.quarkus] (too-much-logging-dev.jar) (Quarkus Main Thread) Profile dev activated. Live Coding activated.
 2021-07-12 13:42:06,492 INFO  [io.quarkus] (too-much-logging-dev.jar) (Quarkus Main Thread) Installed features: [cdi, resteasy, smallrye-context-propagation]
 2021-07-12 13:42:06,494 INFO  [io.qua.dep.dev.RuntimeUpdatesProcessor] (too-much-logging-dev.jar) (Aesh InputStream Reader) Live reload total time: 0.649s
```

### How to Reproduce?

1. Download the reproducer: [too-much-logging.zip](https://github.com/quarkusio/quarkus/files/6801028/too-much-logging.zip)
2. mvn quarkus:dev
3. open dev ui
4. open the log in dev ui
5. press "s" in the terminal running dev mode to force a restart
6. the log in dev ui shows additional lines compared to the terminal
7. This problem gets even worse when running other extensions like e.g. hibernate

### Output of `uname -a` or `ver`

MSYS_NT-10.0 NANB7NLNVP2 2.10.0(0.325/5/3) 2018-06-13 23:34 x86_64 Msys

### Output of `java -version`

openjdk version "11.0.7" 2020-04-14 LTS OpenJDK Runtime Environment Zulu11.39+15-CA (build 11.0.7+10-LTS) OpenJDK 64-Bit Server VM Zulu11.39+15-CA (build 11.0.7+10-LTS, mixed mode)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.0.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d) Maven home: C:\eclipse\tools\apache-maven\bin\.. Java version: 11.0.7, vendor: Azul Systems, Inc., runtime: C:\eclipse\tools\java\11 Default locale: de_DE, platform encoding: Cp1252 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by phillip-kruger**
This changes the way we create the log handler for Dev UI, so that it's being created when we create the other loggers (like console log). This allows us to set the same filters etc and also show the banner.

Fix #18609
Fix https://github.com/quarkiverse/quarkus-logging-manager/issues/91

logging-fix

Signed-off-by:Phillip Kruger <phillip.kruger@gmail.com>

### CODE REVIEW

File: core/runtime/src/main/java/io/quarkus/runtime/logging/ConsoleConfig.java [hunk 1]
```diff
@@ -15,6 +15,12 @@
     @ConfigItem(defaultValue = "true")
     boolean enable;
 
+    /**
+     * If web stream console logging should be enabled. Enabled by default in dev mode for Dev UI.
+     */
+    @ConfigItem(defaultValue = "false")
+    boolean enableWebStream;
+
```
Comment (phillip-kruger) [inline core/runtime/src/main/java/io/quarkus/runtime/logging/ConsoleConfig.java:23]: This config exits so that logger-manager (in Quarkiverse) use this in Non Dev Mode.

**Review by geoand — APPROVED** [review]

File: core/runtime/src/main/java/io/quarkus/runtime/logging/ConsoleConfig.java (hunk 1 above)
Comment (stuartwdouglas) [reply core/runtime/src/main/java/io/quarkus/runtime/logging/ConsoleConfig.java:23]: Then shouldn't this be a build item rather than a config option?

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/logstream/WebSocketLogHandler.java [hunk 2]
```diff
@@ -0,0 +1,100 @@
...
+
+import io.vertx.core.http.ServerWebSocket;
+
+/**
+ * Log handler for Logger Manager
+ */
+public class WebSocketLogHandler extends ExtHandler {
+    private final LinkedBlockingQueue<ExtLogRecord> history;
+
+    private static final Map<String, ServerWebSocket> SESSIONS = new HashMap<>();
```
Comment (stuartwdouglas) [inline extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/logstream/WebSocketLogHandler.java:20]: This should be a ConcurrentHashMap.

**Review by stuartwdouglas — CHANGES_REQUESTED** [review]

File: core/runtime/src/main/java/io/quarkus/runtime/logging/ConsoleConfig.java (hunk 1 above)
Comment (phillip-kruger) [reply core/runtime/src/main/java/io/quarkus/runtime/logging/ConsoleConfig.java:23]: Ok cool, how would that work ? An empty optional build item that if there, we should include in non-dev ?

Comment (geoand) [reply core/runtime/src/main/java/io/quarkus/runtime/logging/ConsoleConfig.java:23]: We usually use a  `MultiBuildItem` in this case in case multiple extensions try to enable the feature, In you build step you just check if the list of build items is empty or not to determine whether or not the feature has been turned on by some other extension

**Comment by phillip-kruger** [comment]
@geoand @stuartwdouglas - changes made as requested. Please check the new BuildItem that now, if included, will enable the logstream in prod

**Review by stuartwdouglas — APPROVED** [review]
