### PR TITLE
SSL support for Reactive SQL Clients

### LINKED ISSUE #552: vertx-quickstart with ssl
Hi 

I am trying to connect to my Postgresql instance on GCP with ssl, but  I keep getting different errors.
Does someone know how to connect with that quickstart vertx client project on quarkus?

I have the client-cert.pem the client-key.pem and server-ca.pem from GCP and I am using it like this:

quarkus.ssl.native=true
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=$USER
quarkus.datasource.password=$PASS
quarkus.datasource.reactive.url=postgresql://$PUBLIC_IP:5432/postgres?ssl=true&sslmode=verify-ca&sslcert=client-cert.pem&sslkey=client-key.pem&sslrootcert=server-ca.pem
myapp.schema.create=true

But I get this error:
Trust options must be specified under verify-full or verify-ca sslmode
If I change to require I get SSL Handshake error.

The connection works with the psql from commandline, but not from this vertx-quickstart from quarkus.

### LINKED ISSUE #6321: Mysql-reactive client is not working on native mode
I am trying to run mysql-reactive client in native mode and it is not working while it works fine in JVM mode.

I am receiving the below exception when I try to connect to it :
```
java.util.concurrent.CompletionException: java.security.NoSuchAlgorithmException: RSA KeyFactory not available
bookrx_1  | 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:164)
bookrx_1  | 	at org.jboss.resteasy.core.MethodInjectorImpl.lambda$invoke$3(MethodInjectorImpl.java:122)
bookrx_1  | 	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616)
bookrx_1  | 	at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:628)
bookrx_1  | 	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1996)
bookrx_1  | 	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:110)
bookrx_1  | 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:122)
bookrx_1  | 	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:594)
bookrx_1  | 	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:468)
bookrx_1  | 	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:421)
bookrx_1  | 	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:363)
bookrx_1  | 	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:423)
bookrx_1  | 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:391)
bookrx_1  | 	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invoke$1(ResourceMethodInvoker.java:365)
bookrx_1  | 	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:995)
bookrx_1  | 	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2137)
bookrx_1  | 	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:110)
bookrx_1  | 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:365)
bookrx_1  | 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:477)
bookrx_1  | 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:252)
bookrx_1  | 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:153)
bookrx_1  | 	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:363)
bookrx_1  | 	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:156)
bookrx_1  | 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:238)
bookrx_1  | 	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
bookrx_1  | 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:120)
bookrx_1  | 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:36)
bookrx_1  | 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:85)
bookrx_1  | 	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
bookrx_1  | 	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
bookrx_1  | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
bookrx_1  | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1395)
bookrx_1  | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
bookrx_1  | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
bookrx_1  | 	at java.lang.Thread.run(Thread.java:748)
bookrx_1  | 	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
bookrx_1  | 	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:460)
bookrx_1  | 	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
bookrx_1  | Caused by: java.util.concurrent.CompletionException: java.security.NoSuchAlgorithmException: RSA KeyFactory not available
bookrx_1  | 	at java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:375)
bookrx_1  | 	at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:1947)
bookrx_1  | 	at org.ibra.ebs.service.BookService.init(BookService.java:38)
bookrx_1  | 	at org.ibra.ebs.service.BookService_Bean.create(BookService_Bean.zig:149)
bookrx_1  | 	at org.ibra.ebs.service.BookService_Bean.create(BookService_Bean.zig:343)
bookrx_1  | 	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:80)
bookrx_1  | 	at io.quarkus.arc.impl.ComputingCache$CacheFunction.lambda$apply$0(ComputingCache.java:99)
bookrx_1  | 	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
bookrx_1  | 	at io.quarkus.arc.impl.ComputingCache.getValue(ComputingCache.java:41)
bookrx_1  | 	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:25)
bookrx_1  | 	at org.ibra.ebs.service.BookService_ClientProxy.arc$delegate(BookService_ClientProxy.zig:99)
bookrx_1  | 	at org.ibra.ebs.service.BookService_ClientProxy.getLastestRecords(BookService_ClientProxy.zig:248)
bookrx_1  | 	at org.ibra.ebs.resource.BookResource.get(BookResource.java:47)
bookrx_1  | 	at org.ibra.ebs.resource.BookResource_ClientProxy.get(BookResource_ClientProxy.zig:252)
bookrx_1  | 	at java.lang.reflect.Method.invoke(Method.java:498)
bookrx_1  | 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:151)
bookrx_1  | 	... 37 more
bookrx_1  | Caused by: java.security.NoSuchAlgorithmException: RSA KeyFactory not available
bookrx_1  | 	at java.security.KeyFactory.<init>(KeyFactory.java:138)
bookrx_1  | 	at java.security.KeyFactory.getInstance(KeyFactory.java:172)
bookrx_1  | 	at io.vertx.mysqlclient.impl.util.RsaPublicKeyEncryptor.generateRsaPublicKey(RsaPublicKeyEncryptor.java:34)
bookrx_1  | 	at io.vertx.mysqlclient.impl.util.RsaPublicKeyEncryptor.encrypt(RsaPublicKeyEncryptor.java:21)
bookrx_1  | 	at io.vertx.mysqlclient.impl.codec.AuthenticationCommandBaseCodec.sendEncryptedPasswordWithServerRsaPublicKey(AuthenticationCommandBaseCodec.java:76)
bookrx_1  | 	at io.vertx.mysqlclient.impl.codec.AuthenticationCommandBaseCodec.handleAuthMoreData(AuthenticationCommandBaseCodec.java:35)
bookrx_1  | 	at io.vertx.mysqlclient.impl.codec.InitialHandshakeCommandCodec.handleAuthentication(InitialHandshakeCommandCodec.java:188)
bookrx_1  | 	at io.vertx.mysqlclient.impl.codec.InitialHandshakeCommandCodec.decodePayload(InitialHandshakeCommandCodec.java:60)
bookrx_1  | 	at io.vertx.mysqlclient.impl.codec.MySQLDecoder.decodePayload(MySQLDecoder.java:62)
bookrx_1  | 	at io.vertx.mysqlclient.impl.codec.MySQLDecoder.decode(MySQLDecoder.java:51)
bookrx_1  | 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:505)
bookrx_1  | 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444)
bookrx_1  | 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283)
bookrx_1  | 	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
bookrx_1  | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
bookrx_1  | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
bookrx_1  | 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
bookrx_1  | 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
bookrx_1  | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
bookrx_1  | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
bookrx_1  | 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
bookrx_1  | 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
bookrx_1  | 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
bookrx_1  | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
bookrx_1  | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
bookrx_1  | 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
bookrx_1  | 	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
bookrx_1  | 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
bookrx_1  | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
bookrx_1  | 	at java.lang.Thread.run(Thread.java:748)
bookrx_1  | 	... 2 more
```

**Configuration**
```properties
quarkus.datasource.url = vertx-reactive:mysql://myhost:3306/ebs_book
quarkus.datasource.username = xxx
quarkus.datasource.password = xxx
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
18.7.0 Darwin Kernel Version 18.7.0: Sat Oct 12 00:02:19 PDT 2019; root:xnu-4903.278.12~1/RELEASE_X86_64 x86_64
 - Output of `java -version`: 
openjdk version "1.8.0_202"
OpenJDK Runtime Environment Corretto-8.202.08.2 (build 1.8.0_202-b08)
OpenJDK 64-Bit Server VM Corretto-8.202.08.2 (build 25.202-b08, mixed mode)
 - GraalVM version (if different from Java): 
graalvm-ce-19.0.2
 - Quarkus version or git rev: 
1.1.0.Final

Also tried this [enabling SSL for my image](https://quarkus.io/guides/native-and-ssl#working-with-containers) and it didn't work.

### PR DESCRIPTION
**Pull request by tsegismont**
Fixes https://github.com/quarkusio/quarkus-quickstarts/issues/552, Fixes #6321

### CODE REVIEW

**Comment by tsegismont** [comment]
@cescoffier can you please review?

I have been able to test locally with PEM trust store and PEM Key Cert, in both JVM and native modes.

I believe the build platform doesn't provide an SSL protected database for automated testing, does it?

**Comment by tsegismont** [comment]
The build failures look unrelated to the changes, they are probably due to a Quay outage.

**Comment by stuartwdouglas** [comment]
The current failure does look related.

File: extensions/reactive-pg-client/runtime/src/main/java/io/quarkus/reactive/pg/client/runtime/PgPoolRecorder.java [hunk 1]
```diff
@@ -2,6 +2,7 @@
 
 import static io.quarkus.credentials.CredentialsProvider.PASSWORD_PROPERTY_NAME;
 import static io.quarkus.credentials.CredentialsProvider.USER_PROPERTY_NAME;
+import static io.quarkus.vertx.core.runtime.SSLConfigHelper.*;
```
Comment (cescoffier) [inline extensions/reactive-pg-client/runtime/src/main/java/io/quarkus/reactive/pg/client/runtime/PgPoolRecorder.java:5]: We try to avoid import statements using `*`.

File: extensions/reactive-pg-client/runtime/src/main/java/io/quarkus/reactive/pg/client/runtime/PgPoolRecorder.java [hunk 2]
```diff
@@ -121,6 +122,18 @@ private PgConnectOptions toPgConnectOptions(DataSourceRuntimeConfig dataSourceRu
             pgConnectOptions.setPipeliningLimit(dataSourceReactivePostgreSQLConfig.pipeliningLimit.getAsInt());
         }
 
+        if (dataSourceReactivePostgreSQLConfig.sslMode.isPresent()) {
+            pgConnectOptions.setSslMode(dataSourceReactivePostgreSQLConfig.sslMode.get());
+        }
+
+        configurePemTrustOptions(pgConnectOptions, dataSourceReactivePostgreSQLConfig.trustCertificatePem);
```
Comment (cescoffier) [inline extensions/reactive-pg-client/runtime/src/main/java/io/quarkus/reactive/pg/client/runtime/PgPoolRecorder.java:129]: Shouldn't we break the chain if we already configured the options? 

If you use PEM, the chances to also use JKS PFX are 0, no?

File: extensions/vertx-core/runtime/src/main/java/io/quarkus/vertx/core/runtime/SSLConfigHelper.java [hunk 3]
```diff
@@ -0,0 +1,119 @@
...
+
+import io.quarkus.vertx.core.runtime.config.JksConfiguration;
+import io.quarkus.vertx.core.runtime.config.PemKeyCertConfiguration;
+import io.quarkus.vertx.core.runtime.config.PemTrustCertConfiguration;
+import io.quarkus.vertx.core.runtime.config.PfxConfiguration;
+import io.vertx.core.net.*;
+
+public class SSLConfigHelper {
+
+    private static final Pattern COMMA_PATTERN = Pattern.compile(",");
```
Comment (cescoffier) [inline extensions/vertx-core/runtime/src/main/java/io/quarkus/vertx/core/runtime/SSLConfigHelper.java:13]: This should be done directly in the config class. List are comma-separated by default. See the last example from https://github.com/eclipse/microprofile-config/blob/master/spec/src/main/asciidoc/configexamples.asciidoc.

**Review by cescoffier — CHANGES_REQUESTED** [review]

File: extensions/reactive-pg-client/runtime/src/main/java/io/quarkus/reactive/pg/client/runtime/PgPoolRecorder.java (hunk 1 above)
Comment (tsegismont) [reply extensions/reactive-pg-client/runtime/src/main/java/io/quarkus/reactive/pg/client/runtime/PgPoolRecorder.java:5]: Sorry, I will fix that

File: extensions/reactive-pg-client/runtime/src/main/java/io/quarkus/reactive/pg/client/runtime/PgPoolRecorder.java (hunk 2 above)
Comment (tsegismont) [reply extensions/reactive-pg-client/runtime/src/main/java/io/quarkus/reactive/pg/client/runtime/PgPoolRecorder.java:129]: Actually we do, this is done in `SSLHelper#ensureTrustOptionsNotSet`.

File: extensions/vertx-core/runtime/src/main/java/io/quarkus/vertx/core/runtime/SSLConfigHelper.java (hunk 3 above)
Comment (tsegismont) [reply extensions/vertx-core/runtime/src/main/java/io/quarkus/vertx/core/runtime/SSLConfigHelper.java:13]: Thanks for pointing this out, I will update the config object.

**Comment by tsegismont** [comment]
@cescoffier I've pushed the required changes.

@cescoffier @gsmet as I'm looking into adding the same capability to the reactive MySQL client, can I make all the changes in this PR?

**Comment by tsegismont** [comment]
@cescoffier @gsmet I went ahead and implemented SSL support for both SQL clients.

I have tested locally both Postgres and MySQL.

**Review by gsmet — APPROVED** [review]

File: extensions/reactive-datasource/runtime/src/main/java/io/quarkus/reactive/datasource/runtime/DataSourceReactiveRuntimeConfig.java [hunk 4]
```diff
@@ -24,4 +28,58 @@
...
+    /**
+     * Whether all server certificates should be trusted.
+     */
+    @ConfigItem(defaultValue = "false")
+    public boolean trustAll;
+
+    /**
+     * Trust configuration in the PEM format.
+     * <p>
+     * When enabled, {@link #trustCertificateJks} and {@link #trustCertificatePfx} must be disabled.
```
Comment (gsmet) [inline extensions/reactive-datasource/runtime/src/main/java/io/quarkus/reactive/datasource/runtime/DataSourceReactiveRuntimeConfig.java:41]: This javadoc is used in the configuration reference doc. Thus it's better to avoid link to properties and also use the "dash case" versions that are used in config (so `trust-certificate-jks` for instance).

**Review by gsmet — DISMISSED** [review]
It looks good overall, I just have a minor gripe for the javadoc. Could you adjust?

File: extensions/reactive-datasource/runtime/src/main/java/io/quarkus/reactive/datasource/runtime/DataSourceReactiveRuntimeConfig.java (hunk 4 above)
Comment (tsegismont) [reply extensions/reactive-datasource/runtime/src/main/java/io/quarkus/reactive/datasource/runtime/DataSourceReactiveRuntimeConfig.java]: Done

**Comment by tsegismont** [comment]
The failure looks unrelated

File: extensions/reactive-datasource/runtime/pom.xml [hunk 5]
```diff
@@ -26,6 +26,10 @@
             <groupId>io.quarkus</groupId>
             <artifactId>quarkus-datasource</artifactId>
         </dependency>
+        <dependency>
```
Comment (cescoffier) [inline extensions/reactive-datasource/runtime/pom.xml:29]: So we are adding this dependency because of the reuse of some configuration class. I just want to be sure there is not a dragon hidden under a stone.

File: extensions/vertx-core/runtime/src/main/java/io/quarkus/vertx/core/runtime/SSLConfigHelper.java [hunk 6]
```diff
@@ -0,0 +1,120 @@
...
+import io.vertx.core.net.JksOptions;
+import io.vertx.core.net.KeyCertOptions;
+import io.vertx.core.net.PemKeyCertOptions;
+import io.vertx.core.net.PemTrustOptions;
+import io.vertx.core.net.PfxOptions;
+import io.vertx.core.net.TCPSSLOptions;
+
+public class SSLConfigHelper {
+
+    public static void configurePemTrustOptions(TCPSSLOptions options, PemTrustCertConfiguration configuration) {
```
Comment (cescoffier) [inline extensions/vertx-core/runtime/src/main/java/io/quarkus/vertx/core/runtime/SSLConfigHelper.java:16]: @michalszynkiewicz Don't we have the same type of code in gRPC? Maybe we can reuse the same classes.

**Review by cescoffier — APPROVED** [review]
LGTM, I just made a few comments.

File: extensions/reactive-datasource/runtime/pom.xml (hunk 5 above)
Comment (tsegismont) [reply extensions/reactive-datasource/runtime/pom.xml:29]: Yes, the dependency was added to share the ssl helper class.

File: extensions/vertx-core/runtime/src/main/java/io/quarkus/vertx/core/runtime/SSLConfigHelper.java (hunk 6 above)
Comment (tsegismont) [reply extensions/vertx-core/runtime/src/main/java/io/quarkus/vertx/core/runtime/SSLConfigHelper.java:16]: @cescoffier can we do any follow-up work related to gRPC in another PR? If you and @gsmet are both fine with this one, it would be great to merge it so I can rebase #9644

**Comment by tsegismont** [comment]
@gsmet @cescoffier anything else needed in this PR?

File: extensions/vertx-core/runtime/src/main/java/io/quarkus/vertx/core/runtime/SSLConfigHelper.java (hunk 6 above)
Comment (cescoffier) [reply extensions/vertx-core/runtime/src/main/java/io/quarkus/vertx/core/runtime/SSLConfigHelper.java:16]: Yes @tsegismont, this is not an issue with this PR, it's a good idea to reuse them!

**Comment by tsegismont** [comment]
@cescoffier @gsmet rebased on `master`

**Comment by tsegismont** [comment]
@cescoffier failures again that look unrelated

**Comment by FroMage** [comment]
@gsmet can we dismiss your review? His change was implemented and CI is green.
