### PR TITLE
Check self-signed ID token when access token is verified

### LINKED ISSUE #43583: Generated ID token can be attempted to be verified as if it was issued by the OIDC/OAuth2 provider
### Describe the bug

OAuth2 providers such as Github do not issue `ID token` and in such cases Quarkus generates an `internal ID token` to be used for the session cookie. When this `internal ID` token has to be verified, its signature is verified using the secret which was used to sign in, for example, the client secret. 

Trying to verify such an `internal ID token` against Github or similar OAuth2 providers makes no sense.
The only token which must and can be verified against Github is the `access token` that is returned by Github. The Quarkus `github` provider is configured to verify by accessing a Github UserInfo endpoint.

However, and it can happen really mainly due to a user error, a Github access token verification can be triggered by the user adding `@Inject JsonWebToken jwt;` to the endpoint - which, by default, enforces the code flow access token verification.

As it happens, the `OidcIdentityProvider` code branch, which completes the initial code flow access token verification, and proceeds to completing the ID token verification, misses the fact that the ID token can be an internal, and attempts to verify it against Github which causes a confusing error. It does not happen on the main code branch where the internal ID token is correctly verified as a local self-signed token.

See #43545 for more context. 

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sberyozkin**
Fixes #43583.

This PR is about 

1) Avoiding an internal ID token verification when  `JsonWebToken` injected by mistake but `not accessed` from the code, even if the OAuth2 providers return binary/opaque access tokens 

2) Users getting a correct error message when they attempt to access the access token using `JsonWebToken` API but the OAuth2 providers return opaque/binary access tokens 

For example, in case of Github, when they have

```
class GithubService {
@Inject JsonWebToken jwt;
}
```
then any method which attempts to access the Githib binary access token as `jwt`, will get, instead of the confusing error such as:

```
2024-09-27 16:21:07,764 ERROR [io.qua.oid.run.CodeAuthenticationMechanism] (vert.x-eventloop-thread-2) ID token verification has failed:
Token issued to client 686026e8cf211de572f8 can not be introspected because the introspection endpoint address is unknown - please check if your OpenId Connect Provider supports the token introspection
```

a more appropriate, here in devmode:
```
Exception in GithubService.java:26
	  24      @Path("/login")
	  25      public String userinfo() {
	→ 26  	    return jwt.getName() + userInfo.getUserInfoString();
	  27  	}
	  28      

The stacktrace below has been reversed to show the root cause first. [See the original stacktrace](http://localhost:8080/login)

io.quarkus.oidc.OIDCException: Opaque access token can not be converted to JsonWebToken
	at io.quarkus.oidc.runtime.OidcJsonWebTokenProducer.getTokenCredential(OidcJsonWebTokenProducer.java:67)
```

It will make it possible nearly immediately identify the problem which is about the user attempting to use a wrong API to access the binary token. Unfortunately we can't detect it at build time, for ex, we know, Github returns binary access tokens, but this is not part of any contract, the format can change any time.

So PR just makes sure that a check for a self-signed ID token is done correctly in both of the code branches where an ID tokne verification is attempted, with and without the initial code flow access token verification.

The added test confirms that, with a provider returning an opaque access token (value = `alice` - to match the OidcWiremock stub rule), the endpoint method works as expected if an inject `JsonWebToken` is not accessed, but fails with the server error otherwise.

It all may be a bit confusing, but all in all, it is really about improving the user experience when they make a mistake with trying to access opaque access tokens as JSON web tokens. The fix is very simple - encapsulate the code which checks how to proceed with the ID token verification into  a utility method and call it from both places where it is necessary

### CODE REVIEW

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java [hunk 1]
```diff
@@ -196,6 +184,22 @@ public Uni<SecurityIdentity> apply(TokenVerificationResult result, Throwable t)
                 });
     }
 
+    private Uni<TokenVerificationResult> verifyPrimaryTokenUni(Map<String, Object> requestData,
+            TokenAuthenticationRequest request, TenantConfigContext resolvedContext, UserInfo userInfo) {
+        if (isInternalIdToken(request)) {
+            if (requestData.get(NEW_AUTHENTICATION) == Boolean.TRUE) {
```
Comment (gastaldi) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java:190]: This may not evaluate to true if the left call was created using `new Boolean(...)`

**Review by gastaldi — APPROVED** [review]
LGTM, added one minor nitpick. Feel free to ignore if you are certain that won't happen

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java (hunk 1 above)
Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java:190]: Thanks @gastaldi, yes, it won't happen, `CodeFlowAuthenticationMechanism` sets it [here](https://github.com/quarkusio/quarkus/blob/main/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java#L859)

Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java:190]: @gastaldi I may refactor it a bit later anyway :-), right now this particular code can't really work independently from CodeFlowAuthenticationMechanism, so it is safe for now
