### PR TITLE
Better handle registry referencing non-existing codestarts

### LINKED ISSUE #47783: `quarkus-maven-plugin:create` fails with missing codestart even for minimal project (no extensions)
### Describe the bug

Using the `quarkus-maven-plugin` version **3.22.1**, the `create` goal fails when generating a **minimal Quarkus project** with **no extensions explicitly requested**. The error is caused by a missing codestart artifact:

```
com.github.mcollovati:quarkus-hilla:jar:codestarts:24.8-SNAPSHOT
```

This happens even in a clean environment, and the extension in question is not part of the platform or requested by the user.

**Key Points**:

* No extensions are specified.
* The failure references a `SNAPSHOT` codestart from an external project (`quarkus-hilla`) that is not part of the platform BOM.
* The user has no control over this dependency being pulled.

### Expected behavior

* The CLI should never include codestarts for non-platform extensions unless explicitly requested.
* If codestarts are unavailable or broken, the plugin should **fail gracefully**, optionally with a warning or suggestion to use `-DnoCodestarts`.
* Project scaffolding should **succeed by default**, even if external codestarts are unavailable.

### Actual behavior

```
[ERROR] Failed to generate Quarkus project: Failed to resolve codestart artifact
com.github.mcollovati:quarkus-hilla:jar:codestarts:24.8-SNAPSHOT
(absent): Could not find artifact ...
```

### How to Reproduce?

```bash
mvn io.quarkus.platform:quarkus-maven-plugin:3.22.1:create \
  -DprojectGroupId=org.example \
  -DprojectArtifactId=my-app
```

### Output of `uname -a` or `ver`

Darwin ricferna-mac 24.4.0 Darwin Kernel Version 24.4.0: Fri Apr 11 18:33:47 PDT 2025; root:xnu-11417.101.15~117/RELEASE_ARM64_T6030 arm64

### Output of `java -version`

openjdk version "17.0.9" 2023-10-17 OpenJDK Runtime Environment GraalVM CE 17.0.9+9.1 (build 17.0.9+9-jvmci-23.0-b22) OpenJDK 64-Bit Server VM GraalVM CE 17.0.9+9.1 (build 17.0.9+9-jvmci-23.0-b22, mixed mode, sharing)

### Quarkus version or git rev

3.22

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven home: /opt/homebrew/Cellar/maven/3.9.9/libexec Java version: 17.0.9, vendor: GraalVM Community, runtime: /Users/ricferna/.sdkman/candidates/java/17.0.9-graalce Default locale: en_CA, platform encoding: UTF-8 OS name: "mac os x", version: "15.4.1", arch: "aarch64", family: "mac"

### Additional information

**Related Zulip Discussions**:

* [[Users thread](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/.60quarkus.20create.20cli.60.20is.20possibly.20broken.3F/near/517184095)](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/.60quarkus.20create.20cli.60.20is.20possibly.20broken.3F/near/517184095)
* [[Dev thread](https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Problem.20creating.20a.20new.20project.20with.20Quarkus.20Plugin/near/517185495)](https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Problem.20creating.20a.20new.20project.20with.20Quarkus.20Plugin/near/517185495)

### PR DESCRIPTION
**Pull request by gsmet**
We need to be a lot more solid when the registry is referencing non-existing codestarts.
Which can happen if an extension is pointing to a non-existing codestart.

The patch is extremely small but we have to push the logger there thus why patch is larger than expected.

Related to
https://quarkusio.zulipchat.com/#narrow/channel/187030-users/topic/.60quarkus.20create.20cli.60.20is.20possibly.20broken.3F/with/517462042

Fixes #47783

### CODE REVIEW

File: independent-projects/tools/devtools-common/src/main/java/io/quarkus/devtools/project/CodestartResourceLoadersBuilder.java [hunk 1]
```diff
@@ -146,10 +150,11 @@ private static List<ResourceLoader> getCodestartResourceLoaders(String baseCodes
         final List<ResourceLoader> codestartResourceLoaders = new ArrayList<>(codestartsArtifacts.size());
         for (Artifact a : codestartsArtifacts.values()) {
             try {
-                final File artifactFile = mvn.resolve(a).getArtifact().getFile();
+                final File artifactFile = mavenArtifactResolver.resolve(a).getArtifact().getFile();
                 codestartResourceLoaders.add(resolveFileResourceLoader(artifactFile));
             } catch (Exception e) {
-                throw new RuntimeException("Failed to resolve codestart artifact " + a, e);
+                log.warn("Unable to resolve codestart artifact for %s: %s", a, e.getMessage());
+                continue;
```
Comment (gsmet) [inline independent-projects/tools/devtools-common/src/main/java/io/quarkus/devtools/project/CodestartResourceLoadersBuilder.java:157]: This is the actual patch.

**Comment by maxandersen** [comment]
related to #47783

File: independent-projects/tools/devtools-common/src/main/java/io/quarkus/devtools/project/CodestartResourceLoadersBuilder.java (hunk 1 above)
Comment (ia3andy) [reply independent-projects/tools/devtools-common/src/main/java/io/quarkus/devtools/project/CodestartResourceLoadersBuilder.java:157]: Why the `continue`?

**Review by ia3andy — APPROVED** [review]
LGTM

File: independent-projects/tools/devtools-common/src/main/java/io/quarkus/devtools/project/CodestartResourceLoadersBuilder.java (hunk 1 above)
Comment (gsmet) [reply independent-projects/tools/devtools-common/src/main/java/io/quarkus/devtools/project/CodestartResourceLoadersBuilder.java:157]: It's not useful per se but you never know what might be added in the future so I wanted the intent to be extra clear.
