### PR TITLE
Quartz - Make jdbc store class configurable and use CMT store class by default

### LINKED ISSUE #8555: quarkus-quartz using JobStoreTX and not JobStoreCMT
Hi,
as per [discussion](https://groups.google.com/forum/#!msg/quarkus-dev/5E86jXmzzmY/ri0NbOO-CQAJ)

Stuart Douglas thinks this may be a bug.
Env: quarkus 1.3.2.Final + maven + Postgres

is it expected quakus uses JobStoreTX and not JobStoreCMT with clustered
Quartz and db store type?

We're implementing an application mixing Panache and Quartz, we should
have to handle a global transaction to persist both PanacheEntities and a
related quartz Job.

We can workaround but we'd like to know if we could set
org.quartz.jobStore.class in some way.
Pseudo code is

```
    @Transactional
    void doStuff() {
            ...
            anEntity.persist();
            try {
                //create job and trigger ...
                quartz.scheduleJob(job, trigger);
            } catch (SchedulerException e) {
                LOGGER.error("unable to set jobs" + e);
            }
        }
    }
```

```
15:12:39 ERROR [co.re.ce.co.ap.jo.JobBuilderBean]
(QuarkusQuartzScheduler_Worker-2)  -> unable to set
jobsorg.quartz.JobPersistenceException: Couldn't commit jdbc connection.
Attempting to commit while taking part in a transaction [See nested
exception: java.sql.SQLException: Attempting to commit while taking part in
a transaction]
org.quartz.JobPersistenceException: Couldn't commit jdbc connection.
Attempting to commit while taking part in a transaction [See nested
exception: java.sql.SQLException: Attempting to commit while taking part in
a transaction]

```

### PR DESCRIPTION
**Pull request by machi1990**
Fixes https://github.com/quarkusio/quarkus/issues/8555

### CODE REVIEW

File: extensions/quartz/deployment/src/main/java/io/quarkus/quartz/deployment/QuartzProcessor.java [hunk 1]
```diff
@@ -169,6 +168,10 @@ private String guessDriver(Optional<JdbcDataSourceBuildItem> jdbcDataSource) {
         return logCleanUps;
     }
 
+    private String getStoreClassSimpleName(String clazz) throws ClassNotFoundException {
+        return Class.forName(clazz).getSimpleName();
```
Comment (mkouba) [inline extensions/quartz/deployment/src/main/java/io/quarkus/quartz/deployment/QuartzProcessor.java:172]: Do we need to load the class here? We could use something like `String.lastIndexOf(".")`, or?

File: extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java [hunk 2]
```diff
@@ -256,6 +258,10 @@ private Properties getSchedulerConfigurationProperties(QuartzSupport quartzSuppo
                 props.put(StdSchedulerFactory.PROP_JOB_STORE_PREFIX + ".isClustered", "true");
                 props.put(StdSchedulerFactory.PROP_JOB_STORE_PREFIX + ".clusterCheckinInterval", "20000"); // 20 seconds
             }
+
+            if (storeClass.equals(JobStoreCMT.class.getName())) {
+                props.put(StdSchedulerFactory.PROP_JOB_STORE_PREFIX + ".nonManagedTXDataSource", dataSource);
```
Comment (mkouba) [inline extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java:263]: What is this used for? It wasn't used before, or?

**Review by mkouba — COMMENTED** [review]
Maybe we could also add a simple test?

File: extensions/quartz/deployment/src/main/java/io/quarkus/quartz/deployment/QuartzProcessor.java (hunk 1 above)
Comment (machi1990) [reply extensions/quartz/deployment/src/main/java/io/quarkus/quartz/deployment/QuartzProcessor.java:172]: Yes, thought about that but I assumed it is okay since we are at build time?

File: extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java (hunk 2 above)
Comment (machi1990) [reply extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java:263]: Yes, it was not need before since the non managed datasource was not configured. Now we need it so configure the `JobStoreCMT` class.

File: extensions/quartz/deployment/src/main/java/io/quarkus/quartz/deployment/QuartzProcessor.java (hunk 1 above)
Comment (mkouba) [reply extensions/quartz/deployment/src/main/java/io/quarkus/quartz/deployment/QuartzProcessor.java:172]: Yes, it's probably ok. But still, we load a class just to get the simple name...

File: extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java (hunk 2 above)
Comment (mkouba) [reply extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java:263]: I see. It was `JobStoreTX` before...

File: extensions/quartz/deployment/src/main/java/io/quarkus/quartz/deployment/QuartzProcessor.java (hunk 1 above)
Comment (machi1990) [reply extensions/quartz/deployment/src/main/java/io/quarkus/quartz/deployment/QuartzProcessor.java]: Okay, gotcha. I have updated the code to take into account this feedback.

**Comment by machi1990** [comment]
> Maybe we could also add a simple test?

Thanks for the review @mkouba I have added a test case. Let's se what CI has to say about it :-)

**Comment by mkouba** [comment]
@machi1990 shouldn't we make sure the TX is commited when `JobStoreCMT` is used and the jobs are scheduled inside the constructor of `QuartzScheduler`?

**Comment by machi1990** [comment]
> @machi1990 shouldn't we make sure the TX is commited when `JobStoreCMT` is used 

Do you mean we should make sure that the jobs (annotated ones) are scheduled within a TX? 

> and the jobs are scheduled inside the constructor of `QuartzScheduler`?

@mkouba I am not sure I follow you on this one.

**Comment by mkouba** [comment]
> Do you mean we should make sure that the jobs (annotated ones) are scheduled within a TX?

Yes.

I thought that Quartz stores the jobs in the DB when `org.quartz.Scheduler.scheduleJob(JobDetail, Trigger)` is invoked. And we do schedule `@Scheduled` methods inside the `QuartzScheduler `constructor. If `JobStoreCMT` is used then no commit/rollback is perfomed, or? Am I missing something?

**Comment by machi1990** [comment]
> > Do you mean we should make sure that the jobs (annotated ones) are scheduled within a TX?
> 
> Yes.
> 
> I thought that Quartz stores the jobs in the DB when `org.quartz.Scheduler.scheduleJob(JobDetail, Trigger)` is invoked. And we do schedule `@Scheduled` methods inside the `QuartzScheduler `constructor. If `JobStoreCMT` is used then no commit/rollback is perfomed, or? Am I missing something?

I get you now, you are not missing anything, just a good catch, thanks!!.
How would you suggest that we do that?

File: extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzBuildTimeConfig.java [hunk 3]
```diff
@@ -38,4 +42,29 @@
      */
     @ConfigItem(name = "datasource")
     public Optional<String> dataSourceName;
+
+    /**
+     * The jdbc store class to use when the `db` store type is set.
+     * <p>
+     * There are actually two seperate JDBCJobStore classes {@link org.quartz.impl.jdbcjobstore.JobStoreCMT}
```
Comment (gsmet) [inline extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzBuildTimeConfig.java:49]:
```suggestion
     * There are actually two separate JDBCJobStore classes {@link org.quartz.impl.jdbcjobstore.JobStoreCMT}
```

File: extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzBuildTimeConfig.java [hunk 4]
```diff
@@ -38,4 +42,29 @@
...
+     * and {@link org.quartz.impl.jdbcjobstore.JobStoreTX} that you can select between, depending on the transactional
+     * behaviour you need.
+     * <p>
+     * The {@link org.quartz.impl.jdbcjobstore.JobStoreCMT} is meant to be used in an application-server
+     * environment that provides container-managed-transactions. No commit / rollback will be handled by this class.
+     * <p>
+     * The {@link org.quartz.impl.jdbcjobstore.JobStoreTX} manages all transactions for you by handling commit and rollback.
+     * <p>
+     * If not specified, defaults to using {@link org.quartz.impl.jdbcjobstore.JobStoreCMT}.
```
Comment (gsmet) [inline extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzBuildTimeConfig.java:58]: You can remove that, the config doc generation will do that for you.

File: extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzBuildTimeConfig.java [hunk 5]
```diff
@@ -38,4 +42,29 @@
...
+     */
+    @ConfigItem(defaultValue = "org.quartz.impl.jdbcjobstore.JobStoreCMT")
+    public Optional<String> jdbcStoreClass;
```
Comment (gsmet) [inline extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzBuildTimeConfig.java:61]: I wonder if it should be more generic and not tied to jdbc. I could envision some customization even if not jdbc.

**Review by gsmet — CHANGES_REQUESTED** [review]
added a few comments/suggestion. I don't feel strongly about those things so feel free to ignore.

File: extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzBuildTimeConfig.java (hunk 3 above)
Comment (machi1990) [reply extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzBuildTimeConfig.java:49]: Good catch.

File: extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzBuildTimeConfig.java (hunk 5 above)
Comment (machi1990) [reply extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzBuildTimeConfig.java:61]: Since we have only two possible classes I was thinking of an enum:

```
enum TransactionStrategy {
  MANAGED, // this will be JobStoreTX
  UNMANAGED;  // this will be JobStoreCMT
}
```

The we could have a config property named like `quarkus.quartz.transaction-strategy`, I was just not sure if it is the good way to go. Are you thinking of something like that or along those lines?

Comment (mkouba) [reply extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzBuildTimeConfig.java:59]: I'm not sure it makes sense to use generic names here. It's Quartz-specific. On the other hand, it could make sense to use the enum. In fact, it could make sense to change the enum for the `QuartzBuildTimeConfig.storeType` to `RAM`, `DB`, `JDBC_TX` and `JDBC_CMT` (where `DB` is an alias of `JDBC_CMT`) or something like that.

File: extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java [hunk 6]
```diff
@@ -89,6 +98,19 @@ public QuartzScheduler(SchedulerContext context, QuartzSupport quartzSupport, Co
...
+                InstanceHandle<UserTransaction> handle = Arc.container().instance(UserTransaction.class);
+
+                boolean nonManagedTx = quartzSupport.getBuildTimeConfig().getStoreClass()
+                        .equals("org.quartz.impl.jdbcjobstore.JobStoreCMT");
+
+                if (nonManagedTx) {
+                    if (handle.isAvailable()) {
+                        handle.get().begin();
+                    } else {
+                        LOGGER.debugf("Unable to start transaction for JobStoreCMT job store class. " +
```
Comment (mkouba) [inline extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java:110]: I think that this should be an error, or?

File: extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java [hunk 7]
```diff
@@ -155,7 +177,18 @@ public QuartzScheduler(SchedulerContext context, QuartzSupport quartzSupport, Co
                                 scheduled);
                     }
                 }
-            } catch (SchedulerException e) {
+                if (nonManagedTx) {
+                    if (handle.isAvailable()) {
+                        try {
+                            handle.get().commit();
+                        } catch (HeuristicMixedException | HeuristicRollbackException | RollbackException e) {
+                            handle.get().rollback();
```
Comment (mkouba) [inline extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java:185]: I believe that we should always rollback if something goes wrong, ie. right before `throw new IllegalStateException("Unable to create Scheduler", e)`. Actually, we could change the catch block below to `catch Throwable`...

File: extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java (hunk 6 above)
Comment (machi1990) [reply extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java:110]: I think we can as well remove this message since, transaction support will be brought transitively by the agroal extension. In build time we have a check that the datasource is properly configured. 

WDYT?

File: extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzBuildTimeConfig.java (hunk 5 above)
Comment (machi1990) [reply extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzBuildTimeConfig.java:59]: +1, I like this better. 

Let's go this way and not add another configuration knob.

File: extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java [hunk 8]
```diff
@@ -155,8 +165,20 @@ public QuartzScheduler(SchedulerContext context, QuartzSupport quartzSupport, Co
...
+                if (manageTx) {
+                    try {
+                        handle.get().rollback();
+                    } catch (SystemException ex) {
+                        LOGGER.error("Unable to rollback transaction", ex);
+                    }
+                }
                 throw new IllegalStateException("Unable to create Scheduler", e);
+            } finally {
+                handle.close();
```
Comment (mkouba) [inline extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java:181]: `InstanceHandle` is `AutoCloseable` so you can just use try-with-catch (although it's not necessary in this case because the `UserTransaction` is `@ApplicationScoped`, but better safe than sorry ;-).

File: extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java [hunk 9]
```diff
@@ -256,6 +278,10 @@ private Properties getSchedulerConfigurationProperties(QuartzSupport quartzSuppo
                 props.put(StdSchedulerFactory.PROP_JOB_STORE_PREFIX + ".isClustered", "true");
                 props.put(StdSchedulerFactory.PROP_JOB_STORE_PREFIX + ".clusterCheckinInterval", "20000"); // 20 seconds
             }
+
+            if (buildTimeConfig.storeType.clazz.equals(JobStoreCMT.class.getName())) {
```
Comment (mkouba) [inline extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java:282]: I'd rather use the enum constants, i.e. `buildTimeConfig.storeType == DB || buildTimeConfig.storeType == JDBC_CMT`.

File: extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/StoreType.java [hunk 10]
```diff
@@ -1,17 +1,24 @@
 package io.quarkus.quartz.runtime;
 
-import org.quartz.impl.jdbcjobstore.JobStoreTX;
-import org.quartz.simpl.RAMJobStore;
-
 public enum StoreType {
-    RAM(RAMJobStore.class.getName(), RAMJobStore.class.getSimpleName()),
-    DB(JobStoreTX.class.getName(), JobStoreTX.class.getSimpleName());
+    RAM("org.quartz.simpl.RAMJobStore", "RAMJobStore"),
+    DB("org.quartz.impl.jdbcjobstore.JobStoreCMT", "JobStoreCMT"),
```
Comment (mkouba) [inline extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/StoreType.java:5]: I would deprecate this value and add a comment that it's retained for compatibility reasons and will be removed in 1.6 (or just "in future versions").

**Review by mkouba — COMMENTED** [review]
I added few comments. Otherwise looks good!

File: extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/StoreType.java (hunk 10 above)
Comment (machi1990) [reply extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/StoreType.java:5]: Great, I was not sure how to go about this. Thanks clarifying it. I'll do it and go ahead and upgrade the quickstarts too.

Comment (mkouba) [reply extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/StoreType.java:5]: Something like this should be OK:
https://github.com/quarkusio/quarkus/blob/master/independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanDeploymentValidator.java#L25-L36

Comment (machi1990) [reply extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/StoreType.java]: Done.

**Review by gsmet — APPROVED** [review]

**Comment by machi1990** [comment]
Thanks :-)
