### PR TITLE
DevMojo invoking other goals should filter out goal params that aren't supported

### LINKED ISSUE #13671: Cannot find 'jvmArgs' in class io.quarkus.maven.GenerateCodeMojo
Hi,

After upgrading to 1.10.2 (including maven plugin) from 1.9.2, I'm geting the following error when I run `mvn quarkus:dev` alone:

`[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:1.10.2.Final:dev (default-cli) on project btrdkr: Unable to execute mojo: Unable to parse configuration of mojo io.quarkus:quarkus-maven-plugin:1.10.2.Final:generate-code for parameter jvmArgs: Cannot find 'jvmArgs' in class io.quarkus.maven.GenerateCodeMojo -> [Help 1]`

...this is after I first run `mvn compile`. If I run them together with `mvn compile quarkus:dev`, I get the exception when starting up:

```
2020-12-03 16:11:56,003 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile dev): java.security.cert.CertificateException: No X509TrustManager implementation available
        at java.base/sun.security.ssl.DummyX509TrustManager.checkServerTrusted(SSLContextImpl.java:1652)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:632)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)
        at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480)
        at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1267)
        at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1254)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:691)
        at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1199)
        at io.netty.handler.ssl.SslHandler.runAllDelegatedTasks(SslHandler.java:1542)
...
```

This is because I use OIDC module and it tries to contact the OIDC server during startup using SSL. I have the following configuration for maven plugin:

```
            <plugin>
                <groupId>io.quarkus</groupId>
                <artifactId>quarkus-maven-plugin</artifactId>
                <version>${quarkus.platform.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>build</goal>
                            <goal>generate-code</goal>
                            <goal>generate-code-tests</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <jvmArgs>-Djavax.net.ssl.trustStoreType=JKS -Djavax.net.ssl.trustStore=${project.build.outputDirectory}/META-INF/security/cacerts -Djavax.net.ssl.trustStorePassword=changeit</jvmArgs>
                </configuration>
            </plugin>
```

It looks like the quarkus:dev mojo is not passing the jvmArgs to the JVM when starting it up. This used to work with 1.9.2 plugin. 

**To Reproduce**

Use `<jvmArgs>...</jvmArgs>` in configuration of quarkus-maven-plugin and see that they are either not applied or executing `mvn quarkus:dev` alone bails out with error.

### PR DESCRIPTION
**Pull request by aloubyansky**
Fixes #13671

### CODE REVIEW

File: devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java [hunk 1]
```diff
@@ -445,9 +446,16 @@ private Xpp3Dom getPluginConfig(Plugin plugin, String goal) {
...
         if (mergedConfig != null) {
+            Set<String> supportedParams = null;
             // Filter out `test*` configurations
             for (Xpp3Dom child : mergedConfig.getChildren()) {
-                if (!child.getName().startsWith("test")) {
+                if (child.getName().startsWith("test")) {
+                    continue;
+                }
+                if (supportedParams == null) {
+                    supportedParams = getMojoDescriptor(plugin, goal).getParameterMap().keySet();
```
Comment (gsmet) [inline devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java:456]: Is there any value in lazy loading the `supportedParams`? Looks like unneeded complexity to me but maybe I miss something?

Comment (aloubyansky) [reply devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java:456]: Not much value. E.g. in case the configuration elements are present but empty.

**Review by gsmet — APPROVED** [review]
