### PR TITLE
Fix Vert.x event bus codec registration

### LINKED ISSUE #29434: Application startup  fails using Lombok's @NonNull on a method annotated with @ConsumeEvent
### Describe the bug

When annotating a method parameter with @NonNull for a Vertx Consumer Method (means its annotated with @ConsumeEvent) then the application startup fails, throwing an exception.

Mentioned on: https://github.com/quarkusio/quarkus/discussions/29322

### Expected behavior

No exception is thrown when using @NonNull.

### Actual behavior

Exception is thrown when using @NonNull, application can not be started.

### How to Reproduce?

1. Clone the repo: https://github.com/benjaminrau/quarkus-nonnull-reproducer
2. Start the application

### Output of `uname -a` or `ver`

Linux br-builders-nb 5.14.0-1052-oem #59-Ubuntu SMP Fri Sep 9 09:37:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17" 2021-09-14 OpenJDK Runtime Environment (build 17+35-2724) OpenJDK 64-Bit Server VM (build 17+35-2724, mixed mode, sharing)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

>= 2.14.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3

### Additional information

Noticable is that @NonNull is included in the ClassName for EventBusCodec registration too:
`2022-11-23 10:29:52,634 INFO  [io.qua.ver.dep.EventBusCodecProcessor] (build-5) Local Message Codec registered for type org.acme.@NonNull HelloEvent
`

### PR DESCRIPTION
**Pull request by Ladicek**
The `EventBusCodecProcessor` used to create a map from Jandex `Type` of message to a `DotName` of the corresponding codec, and then expose that map as a repeatable `MessageCodecBuildItem`. When creating each build item, the code used to call `Type.toString()`, which is never the right thing to do when obtaining a class name from Jandex `Type`.

With this commit, the map is from type `DotName` to codec `DotName`, and the key in the map is obtained by `Type.name()`.

Fixes #29434

### CODE REVIEW

File: extensions/vertx/deployment/src/test/java/io/quarkus/vertx/EventBusCodecTest.java [hunk 1]
```diff
@@ -73,6 +77,11 @@ String getMessage() {
         }
     }
 
+    @Retention(RetentionPolicy.CLASS)
```
Comment (cescoffier) [inline extensions/vertx/deployment/src/test/java/io/quarkus/vertx/EventBusCodecTest.java:80]: Is this required?

**Review by cescoffier — APPROVED** [review]

File: extensions/vertx/deployment/src/test/java/io/quarkus/vertx/EventBusCodecTest.java (hunk 1 above)
Comment (Ladicek) [reply extensions/vertx/deployment/src/test/java/io/quarkus/vertx/EventBusCodecTest.java:80]: Not really, class retention is the default. I just wanted to be explicitly close to the original reproducer.

Comment (Ladicek) [reply extensions/vertx/deployment/src/test/java/io/quarkus/vertx/EventBusCodecTest.java:80]: It could be a runtime-retained annotation as well, that wouldn't make a difference.

**Review by mkouba — APPROVED** [review]

**Comment by syr** [comment]
Any chance or plan to get it in 2.13 as well? From 2.14 we got many breaking changes thanks to kubernetes-client update, which is why I cannot update atm.

**Comment by mkouba** [comment]
> Any chance or plan to get it in 2.13 as well? From 2.14 we got many breaking changes thanks to kubernetes-client update, which is why I cannot update atm.

Yes, this fix should land in the next 2.13 release.
