### PR TITLE
Print useful error message when browser cannot be opened

### LINKED ISSUE #24857: Open browser fails on github codespaces
Trying to open dev ui or website results in error: 

```
2022-04-10 13:33:08,848 ERROR Lio.qua.ver.htt.dep.dev.con.DevConsoleProcessor](AeshInputstreamReader)FailedtolatAch
[> GitHub Co.
browser: java.io.I0Exception: Cannot run program "xdg-open": error=2, No such file or directory
at java. base/java. lang.ProcessBuilder.start (ProcessBuilder.java:1128)
at java.base/java. lang.ProcessBuilder.start (ProcessBuilder.java:1071)
at java.base/java.lang.Runtime.exec (Runtime. java: 592)
at java.base/java. lang.Runtime.exec (Runtime. java: 451)
at io.quarkus.vertx.http.deployment.devmode.console.DevConsoleProcessor.openBrowser(DevConsoleProcessor.java:511)
at io.quarkus.vertx.http.deployment.devmode.console.DevConsoleProcessor.lambda$setupConsole$1(DevConsoleProcessor.
java: 483)
at io.quarkus.deployment.console.ConsoleStateManager$1.accept(ConsoleStateManager.java:73)
at io.quarkus.deployment.console. ConsoleStateManager$1.accept (ConsoleStateManager. java: 46)
at io.quarkus.deployment. console.AeshConsole. lambdassetups1 (AeshConsole. java:275)
at org.ash. terminal. EventDecoder.accept (EventDecoder.java:118)
at org.ash. terminal. EventDecoder.accept (EventDecoder. java: 31)
at org.aesh.terminal.io.Decoder.write(Decoder.java:133)
at org.aesh.readline.tty.terminal.TerminalConnection.openBlocking(TerminalConnection.java:216)
```

Would be great if

A) print url attempted to open rather than the raw error.

B) find way to open webpage in code or the surrounding browser

### PR DESCRIPTION
**Pull request by geoand**
Closes: #24857

### CODE REVIEW

File: extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/devmode/console/DevConsoleProcessor.java [hunk 1]
```diff
@@ -508,22 +508,29 @@ public static void openBrowser(HttpRootPathBuildItem rp, NonApplicationRootPathB
...
                     log.error("Cannot launch browser on this operating system");
             }
+            if (command != null) {
+                rt.exec(command);
+            }
         } catch (Exception e) {
-            log.error("Failed to launch browser", e);
+            log.debug("Failed to launch browser", e);
+            if (command != null) {
+                log.warn("Unable to open browser using command: '" + String.join(" ", command) + "'");
```
Comment (gastaldi) [inline extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/devmode/console/DevConsoleProcessor.java:532]: Maybe also log the reason why it failed (e.getMessage)?

Comment (geoand) [reply extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/devmode/console/DevConsoleProcessor.java:532]: Good idea. Done

**Review by gastaldi — APPROVED** [review]
