### PR TITLE
Overhauled handling of local extensions in Gradle DevTools

### LINKED ISSUE #29234: Better gradle composite build support
### Describe the bug

When using Quarkus on a composite build gradle project I noticed a couple of issues:
1. When including a multi-module gradle project as a composite build the dependency loading doesn't actually work.
2. Hot reloading doesn't work for composite builds (source directory isn't watched).
3. Using a local extension as a composite builds doesn't work

The current method of loading an included build in the Quarkus gradle plugin requires the included build to have a flat hierarchy, which prevents including a multi-module build, plus the workspacedirectory is never added to the dependency index.
I modified the Quarkus application gradle plugin and managed to get it working with both composite builds and multi-module projects. I have a branch for this "fix", tested on multiple project structures, if someone is willing to take a look and see if I haven't miss anything important. Thanks.

Here's the PR link:
https://github.com/quarkusio/quarkus/pull/29233

### Expected behavior

Using composite builds in gradle should work regardless of the project structure hierarchy, same for extensions

### Actual behavior

Using composite builds either doesn't pick up the required dependency, and if it does (when using flat module structure) hot reloading doesn't work for them.
Local extension local dependencies aren't picked up as deployment dependencies.

### How to Reproduce?

Create a composite build project with the following structure with a quarkus app depending on another multimodule gradle project

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

openjdk 11.0.13 2021-10-19

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.5.1

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by vemilyus**
This completely changes how local extensions are handled by the Gradle plugins (`io.quarkus` and `io.quarkus.extension`) by now also resolving deployment modules in included builds and properly adding them and their artifacts as dependencies to the respective Quarkus code generation tasks and configurations. This makes resolution also more resilient by largely depending on Gradle native constructs (`Project`, `ProjectDependency`, etc.) instead of `String` values or artifact coordinates.

The main enhancement is that extensions and deployment modules are now resolved across project boundaries (esp. in composite builds) and more parts of the module hierarchy are searched to find a match. Included build deployment modules are now more reliably detected, even if the extension build isn't explicitly included, and deployment modules that are siblings to the extension module are also more reliably found.

In addition it no longer depends on an extension descriptor file (`META-INF/quarkus-extension.properties`) to exist to determine the deployment module, conditional dependencies and dependency conditions. These are now read directly from the `QuarkusExtensionConfiguration` extension of any local (or included) extension module. Due to Gradle using different ClassLoaders for included builds this had to be done using Reflection. However, if such a properties file is provided by the developer it has precedence over any configuration done using the plugin.

To achieve this deeper integration with Gradle a bit more internal classes were used than I would normally be comfortable with, but they are pretty essential to the functioning of Gradle and Composite Builds so I'm fairly confident that they won't break in the foreseeable future (please give feedback on this).

I also enhanced `QuarkusGradleWrapperTestBase` to offer better usability for local development and testing by starting the test Gradle instance in debug mode if the test is run locally and with a debugger attached. It will then itself wait for a debugger to attach at the default port (`5005`) before doing what it's supposed to do. Also the output of the started Gradle process is printed immediately for better observability and the build is stopped if Quarkus DevMode failed to start three times in a row.

Fixes: #29234

Oh, and merry christmas! :christmas_tree: 

P.S.: Kudos to the people who wrote the Gradle test cases! I didn't have to touch most of them and they were really useful in sorting out most edge cases and bugs.

### CODE REVIEW

**Comment by snazy** [comment]
Can take a look a look at this.

**Comment by vemilyus** [comment]
Hi, not to be pushy, has there been any progress on the review? I'd really like some feedback on the changes and what needs to be changed/fixed to get this merged. Thanks :)

File: devtools/gradle/gradle-model/src/main/java/io/quarkus/gradle/tooling/ToolingUtils.java [hunk 1]
```diff
@@ -38,21 +43,100 @@ public static boolean isEnforcedPlatform(ModuleDependency module) {
                 || Category.REGULAR_PLATFORM.equals(category.getName()));
     }
 
-    public static IncludedBuild includedBuild(final Project project,
-            final ProjectComponentIdentifier projectComponentIdentifier) {
-        final String name = projectComponentIdentifier.getBuild().getName();
+    public static IncludedBuild includedBuild(final Project project, final String buildName) {
+        Gradle currentGradle = project.getRootProject().getGradle();
+        while (null != currentGradle) {
```
Comment (snazy) [inline devtools/gradle/gradle-model/src/main/java/io/quarkus/gradle/tooling/ToolingUtils.java:48]: When can this happen?

File: devtools/gradle/gradle-model/src/main/java/io/quarkus/gradle/tooling/ToolingUtils.java [hunk 2]
```diff
@@ -38,21 +43,100 @@ public static boolean isEnforcedPlatform(ModuleDependency module) {
...
+
+            return null;
+        }
+    }
+
+    public static Project findLocalProject(final Project project, final ArtifactCoords artifactCoords) {
+        for (Project subproject : project.getRootProject().getSubprojects()) {
+            if (subproject.getGroup().equals(artifactCoords.getGroupId()) &&
+                    subproject.getName().equals(artifactCoords.getArtifactId()) &&
+                    (artifactCoords.getVersion() == null || subproject.getVersion().equals(artifactCoords.getVersion()))) {
```
Comment (snazy) [inline devtools/gradle/gradle-model/src/main/java/io/quarkus/gradle/tooling/ToolingUtils.java:91]: Nit: Object.equals ?

File: devtools/gradle/gradle-model/src/main/java/io/quarkus/gradle/extension/ConfigurationUtils.java [hunk 3]
```diff
@@ -0,0 +1,50 @@
...
+import org.gradle.api.GradleException;
+import org.gradle.api.provider.ListProperty;
+import org.gradle.api.provider.Property;
+import org.jetbrains.annotations.NotNull;
+
+// This is necessary because in included builds the returned `Project` instance and
+// `QuarkusExtensionConfiguration` extension is provided by a different class loader
+// which prevents us from creating some interface or casting to it directly.
+public class ConfigurationUtils {
+    private static final ConcurrentHashMap<String, Method> methodCache = new ConcurrentHashMap<>();
```
Comment (snazy) [inline devtools/gradle/gradle-model/src/main/java/io/quarkus/gradle/extension/ConfigurationUtils.java:16]: Not sure whether a `static final` cache is good, because it would accumulate `Method` and with those `Class` and `ClassLoader` references. I suspect this would also not respect changes to the extensions and re-use old ones.

**Review by snazy — COMMENTED** [review]
Not a full review from my side, because I'm not familiar with the extensions plugin. The changes to the application-plugin look good. Not sure about the `static final` map in `ConfigurationUtils` wrt to multiple Gradle build invocations.

File: devtools/gradle/gradle-model/src/main/java/io/quarkus/gradle/tooling/ToolingUtils.java (hunk 2 above)
Comment (vemilyus) [reply devtools/gradle/gradle-model/src/main/java/io/quarkus/gradle/tooling/ToolingUtils.java:91]: Gradle projects can all have separate versions, so I want to only explicitly use the version for matching the projects when it is provided in the artifact coordinates. If there is no specified version it should just use the local project as a dependency, if there is a version it should only use the local project if the version matches. Otherwise it would refer to a remote artifact (e.g. Maven dependency)

File: devtools/gradle/gradle-model/src/main/java/io/quarkus/gradle/tooling/ToolingUtils.java (hunk 1 above)
Comment (vemilyus) [reply devtools/gradle/gradle-model/src/main/java/io/quarkus/gradle/tooling/ToolingUtils.java:48]: Calling `currentGradle.getParent()` at the bottom of the loop can return `null`, that's our exit condition for walking up the project tree.

File: devtools/gradle/gradle-model/src/main/java/io/quarkus/gradle/tooling/ToolingUtils.java (hunk 2 above)
Comment (snazy) [reply devtools/gradle/gradle-model/src/main/java/io/quarkus/gradle/tooling/ToolingUtils.java:91]: NVM - I had `Object.equals(artifactCoords.getVersion(), subproject.getVersion())` in mind - but that doesn't cover the `null` special case

File: devtools/gradle/gradle-model/src/main/java/io/quarkus/gradle/extension/ConfigurationUtils.java (hunk 3 above)
Comment (snazy) [reply devtools/gradle/gradle-model/src/main/java/io/quarkus/gradle/extension/ConfigurationUtils.java:16]: Yea - or if needed, cache it for a build, but that's quite tricky w/ Gradle

Comment (vemilyus) [reply devtools/gradle/gradle-model/src/main/java/io/quarkus/gradle/extension/ConfigurationUtils.java]: I removed the cache ;)

File: devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/QuarkusPlugin.java [hunk 4]
```diff
@@ -555,13 +559,40 @@ protected void visitProjectDependencies(Project project, Project dep, Set<String
...
+                        }
+
+                        if (depProject == null) {
+                            return;
+                        }
+
+                        if (depProject.getState().getExecuted()) {
+                            visitPossibleExtensionProject(project, depProject, visited);
+                        } else {
+                            depProject.afterEvaluate(p -> visitPossibleExtensionProject(project, p, visited));
```
Comment (aloubyansky) [inline devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/QuarkusPlugin.java:577]: Isn't this change limiting dependency processing to local extension subprojects compared to the current impl?

Comment (vemilyus) [reply devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/QuarkusPlugin.java:577]: This is called as part of the process of determining a local module's build dependencies, so that they also get built before building the module.

So if I have a module using the application plugin and want to use a local extension, I want to make sure that the local extension and its local module dependencies are also built before building the application.

This doesn't affect how external extensions (e.g. from Maven) are used in any way.

File: integration-tests/gradle/src/main/resources/basic-composite-build-extension-project/extensions/example-extension/deployment/src/main/java/org/acme/example/extension/deployment/QuarkusExampleProcessor.java [hunk 5]
```diff
@@ -34,13 +31,4 @@ void addLibABean(BuildProducer<AdditionalBeanBuildItem> additionalBeans) {
...
 
-
-	@BuildStep
-	@Record(ExecutionTime.STATIC_INIT)
-	EnabledBuildItem addLibABean(
-			final ExampleRecorder exampleRecorder) {
-		return new EnabledBuildItem(exampleRecorder.create().getValue());
-
-	}
-
```
Comment (aloubyansky) [inline integration-tests/gradle/src/main/resources/basic-composite-build-extension-project/extensions/example-extension/deployment/src/main/java/org/acme/example/extension/deployment/QuarkusExampleProcessor.java:45]: @tomas1885 would you like to review these changes?

File: devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/QuarkusPlugin.java (hunk 4 above)
Comment (aloubyansky) [reply devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/QuarkusPlugin.java:577]: Right, my question was about visiting non-extension local dependencies.

Comment (aloubyansky) [reply devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/QuarkusPlugin.java:577]: It looks like `visitProjectDep` is currently called for any local dependency, while with this change it will be called only for local extension dependencies?

Comment (aloubyansky) [reply devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/QuarkusPlugin.java]: Yeah, that makes sense now, thanks.

**Review by aloubyansky — APPROVED** [review]
Thanks a lot @vemilyus

File: integration-tests/gradle/src/main/resources/basic-composite-build-extension-project/extensions/example-extension/deployment/src/main/java/org/acme/example/extension/deployment/QuarkusExampleProcessor.java (hunk 5 above)
Comment (tomas1885) [reply integration-tests/gradle/src/main/resources/basic-composite-build-extension-project/extensions/example-extension/deployment/src/main/java/org/acme/example/extension/deployment/QuarkusExampleProcessor.java:45]: I think the recorder was there just to make sure that it's that nothing is broken between the runtime and deployment modules. It might be redundant so maybe it's ok to remove it, as long as we're sure the current test cases covers this.
