### PR TITLE
When REST Client @Consumes has multiple values, choose the first one

### LINKED ISSUE #51910: Improve REST client handling of multiple Consumes
### Description

Bumping `keycloak-client` version to `26.0.8` failed at #51903, after looking into it I noticed

```
org.jboss.resteasy.reactive.client.api.InvalidRestClientDefinitionException: Failed to generate client for class interface org.keycloak.admin.client.resource.RealmsResource : Multiple `@Consumes` values used in a MicroProfile Rest Client: org.keycloak.admin.client.resource.WorkflowsResource Unable to determine a single `Content-Type`.
2026-01-09T23:39:48.6425586Z 	at org.jboss.resteasy.reactive.client.impl.ClientProxies.get(ClientProxies.java:31)
2026-01-09T23:39:48.6426392Z 	at org.jboss.resteasy.reactive.client.impl.WebTargetImpl.proxy(WebTargetImpl.java:465)
2026-01-09T23:39:48.6427486Z 	at io.quarkus.keycloak.admin.rest.client.runtime.KeycloakAdminRestClientProvider.targetProxy(KeycloakAdminRestClientProvider.java:98)
```

Keycloak Admin Client's [RealmsResource](https://github.com/keycloak/keycloak/blob/main/integration/admin-client/src/main/java/org/keycloak/admin/client/resource/RealmsResource.java)  does indeed have 2 `Consumes` but they do no accumulate, one is on the class level, another one that overrides it is on the method level. 
They happen to be the same values but this is just not a good example, in general, class level set the `@Consumes` for all the methods and some specific ones can override it.

I also noticed #51813, the proposed solution there where an openapi generator creates a method per every consumes works, but IMHO the REST server API does not have to be actually designed like that, multiple Consumes on a single REST resource method is what most interfaces where multiple media types are accepted on a given path would do, have a single method, for example `@Consumes("application/json+x", "application/json+y")` - having two methods here with likely very strange names like `sendJsonX` would not be great.

### Implementation ideas

I have two proposals how to improve it

-  I doubt we can expect 3rd party API providers start changing their APIs by splitting a single method with `@Consumes({"a/b", "c/d"})` into multiple methods eagerly.
 Proposal here is for REST Client to simply take the first `@Consumes`  value, `a/b` in this case - which is valid according to the method spec that can take either `a/b` or `c/d` formatted data. I.e, REST client always takes the first `@Consumes` value as a `Content-Type`
 
* Keycloak Admin Client's [RealmsResource](https://github.com/keycloak/keycloak/blob/main/integration/admin-client/src/main/java/org/keycloak/admin/client/resource/RealmsResource.java) case is quite realistic where a main resource sets a class level `@Consumes`, and a subresource has some individual method `@Consumes` matching that of the parent resource's `Consumes` 

I can certainly open a PR to Keycloak Admin Client to remove the duplicate `application/json` but the justification for it will be rather weak, because `@Consume` does not accumulate, method level one overwrites a class level one. And it will take even if accepted many months for the `26.0.9` to be out, same as it took for `26.0.8`, we have an open issue in Quarkus that was blocked until `26.0.8` would be released...

Proposal here is to not try to accumulate class level and method level `@Consumes` - but if it is really important for Quarkus REST Client then eliminate duplicates first

### PR DESCRIPTION
**Pull request by sberyozkin**
- Fixes: #51910

This PR does the following updates:

* When REST Client `@Consumes` has multiple values, the first one is chosen from the set
* Added test confirming that a custom `ClientRequestFilter` can replace the `Content-Type`, the test emulates a situation where an interface advertizes that `application/json` is supported without syncing up with the actual REST server that is still on `text/plain` only, with REST Client still letting users handle such a buggy REST Client interface.
* Updated docs

### CODE REVIEW

File: extensions/resteasy-reactive/rest-client-jaxrs/deployment/src/main/java/io/quarkus/jaxrs/client/reactive/deployment/JaxrsClientReactiveProcessor.java [hunk 1]
```diff
@@ -2653,15 +2654,15 @@ private void handleReturn(ClassInfo restClientInterface, String defaultMediaType
             if (consumes != null && consumes.length > 0) {
 
                 if (consumes.length > 1) {
-                    Set<String> uniqueConsumes = new HashSet<>(Arrays.asList(consumes));
+                    Set<String> uniqueConsumes = new TreeSet<>(Arrays.asList(consumes));
```
Comment (michalvavrik) [inline extensions/resteasy-reactive/rest-client-jaxrs/deployment/src/main/java/io/quarkus/jaxrs/client/reactive/deployment/JaxrsClientReactiveProcessor.java]:
```suggestion
                    Set<String> uniqueConsumes = Set.of(consumes);
```

File: integration-tests/oidc-client-reactive/src/test/java/io/quarkus/it/keycloak/OidcClientTest.java [hunk 2]
```diff
@@ -132,6 +134,9 @@ public void run() throws Throwable {
                                 if (line.contains("Tokens have been refreshed")) {
                                     tokenRefreshResponseFilterLogCount++;
                                 }
+                                if (line.contains("Content-Type is set to application/json, replacing it with text/plain")) {
```
Comment (michalvavrik) [inline integration-tests/oidc-client-reactive/src/test/java/io/quarkus/it/keycloak/OidcClientTest.java:137]: This is not request for a change, just a comment. Since this is you logging it and this test is basically a CDI bean, you can simply inject the `RestClientContentType....` filter and check some flag (make it singleton/app scoped), rather than checking a log message. Or if you are lazy, just make it static flag.

**Review by michalvavrik — APPROVED** [review]
I think changes look good, and the docs look great. I don't really have any request for changes. Leaving the rest to @geoand .

File: integration-tests/oidc-client-reactive/src/test/java/io/quarkus/it/keycloak/OidcClientTest.java (hunk 2 above)
Comment (sberyozkin) [reply integration-tests/oidc-client-reactive/src/test/java/io/quarkus/it/keycloak/OidcClientTest.java:137]: Hi @michalvavrik Yes, I saw `@LogFile` injected as well, this is just the existing test code, so I thought I'd just add a single check there, alongside other checks done there

Comment (michalvavrik) [reply integration-tests/oidc-client-reactive/src/test/java/io/quarkus/it/keycloak/OidcClientTest.java:137]: Oki.

**Review by geoand — APPROVED** [review]
Thanks a lot!
