### PR TITLE
Prevent repeated Quarkus Security exception handling that lead to duplicate headers during OIDC redirect

### LINKED ISSUE #30011: Duplicate Location headers during OIDC redirection
### Describe the bug

For a Quarkus webapp using the `oidc` extension, during an OIDC authorization code flow, an app may be configured with a `quarkus.oidc.authentication.redirect-path` value.

When a client lands on the path defined in that configuration, as part of a standard OIDC flow, the Quarkus app will send a 302 redirect. In addition to the redirection status code, the response also includes _two_ `Location` headers (`Pragma` and `Cache-Control` are also duplicated). Chrome and FF seem to handle this duplicated Location header fine, but Safari attempts to concatenate the two URLs into a composite URL, which generally will result in a 404 on an app.

This issue was not present in 2.14.2, but has been present since.

The relevant commit appears to be related to https://github.com/quarkusio/quarkus/commit/07b1e09e29bfa7d80ca292727c46324266d0a936#diff-ff8824242a94a73be9ed56f63521b1d690e611927625d46c06d227a3e1846596R342 where the `AuthenticationRedirectException` proceeds to a further step instead of just ending, which was the earlier behavior.

### Expected behavior

The path defined at `quarkus.oidc.authentication.redirect-path` should produce a redirection response with a single `Location` header

### Actual behavior

The path defined at `quarkus.oidc.authentication.redirect-path` should produce a redirection response with a single `Location` header

### How to Reproduce?

https://github.com/acoburn/qurakus-oidc-demo

1. Build the project.
2.  Add the relevant configuration, pointing to a running authorization server as described in the README
3. Visit http://localhost:8080 and login, observing the network tab in a browser (or try using Safari)

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

openjdk version "11.0.17" 2022-10-18

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.15.1 (this affects versions after 2.14.3)

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)

### Additional information

Viewing the network tab while using Chrome on Ubuntu:

image

### PR DESCRIPTION
**Pull request by michalvavrik**
fixes: #30011

When proactive auth is enabled both default auth failure handler and builtin exception mappers were setting headers, which lead to duplicate headers that some browsers could not handle (Safari). Now repeated Quarkus Security exception handling is prevented as we only handle them (iff proactive = true) when custom exception mappers has been defined. There is no point running built in ex. mappers as they do exactly same as default auth failure handler had done.

I added tests that are independent on auth mechanism, but I checked fix with OIDC in both classic and reactive.

### CODE REVIEW

**Comment by michalvavrik** [comment]
`RedisClientMetricsTest` failing on MacOS is unrelated.

File: extensions/resteasy-reactive/quarkus-resteasy-reactive/runtime/src/main/java/io/quarkus/resteasy/reactive/server/runtime/ResteasyReactiveRecorder.java [hunk 1]
```diff
@@ -212,13 +212,48 @@ public void accept(RoutingContext routingContext) {
...
             @Override
             public void handle(RoutingContext event) {
 
+                // special handling when proactive auth is enabled as then we know default auth failure handler already run
+                if (proactive && event.get(QuarkusHttpUser.AUTH_FAILURE_HANDLER) instanceof DefaultAuthFailureHandler) {
+                    // we want to prevent repeated handling of exceptions if user don't want to handle exception himself
+                    // we do not pass exception to abort handlers if proactive auth is enabled and user did not
+                    // provide custom ex. mapper; we replace default auth failure handler as soon as we can, so that
+                    // we can handle Quarkus Security Exceptions ourselves
+                    if (event.failure() instanceof AuthenticationFailedException) {
```
Comment (sberyozkin) [inline extensions/resteasy-reactive/quarkus-resteasy-reactive/runtime/src/main/java/io/quarkus/resteasy/reactive/server/runtime/ResteasyReactiveRecorder.java:230]: Can you please consider, later, add a base `AuthenticationException` which these 3 exceptions will extend, to `quarkus-security`, it can simplify the code as in a few places we check all of these 3 exceptions and more can be added

Comment (michalvavrik) [reply extensions/resteasy-reactive/quarkus-resteasy-reactive/runtime/src/main/java/io/quarkus/resteasy/reactive/server/runtime/ResteasyReactiveRecorder.java:230]: that's clever, I didn't thought about it :-(, I'll look into it later (busy ATM).

Comment (sberyozkin) [reply extensions/resteasy-reactive/quarkus-resteasy-reactive/runtime/src/main/java/io/quarkus/resteasy/reactive/server/runtime/ResteasyReactiveRecorder.java:230]: @michalvavrik This is a limit of my Java related optimization ideas :-). Sure, later, I mean next year some time, really no rush at all :-)

**Comment by sberyozkin** [comment]
@michalvavrik Thanks for the fix, it looks good. What I'm somewhat uncertain about, is why do we have to do these essentially workarounds for the proactive auth case.
So, right now, the default handler is always run and then the exception mappers are checked and therefore, for these exceptions, we should now check if the default handler has already done its job. I see it works but I wonder if we are on the right path here. 
Should the exception mappers be checked first and only if no matching mapper has been found, then if it is an instance of AuthenticationException, do try the default handler ?

**Comment by sberyozkin** [comment]
Or run the default handler only if no authentication exceptions have been detected at the build time and just skip a non-default handler altogether ? May be it is a better option

**Comment by michalvavrik** [comment]
> @michalvavrik Thanks for the fix, it looks good. What I'm somewhat uncertain about, is why do we have to do these essentially workarounds for the proactive auth case. So, right now, the default handler is always run and then the exception mappers are checked and therefore, for these exceptions, we should now check if the default handler has already done its job. I see it works but I wonder if we are on the right path here. Should the exception mappers be checked first and only if no matching mapper has been found, then if it is an instance of AuthenticationException, do try the default handler ?

Hi Sergey @sberyozkin , in short I don't see this as workaround, this PR adds extra condition to RESTEasy Reactive and Classic failure handlers that says "only run exception mappers when proactive=true if user defined custom exception mapper", but we can discuss it. Below are my answers.

> default handler is always run

nope, it's only run when proactive auth is enabled, both RESTEasy Reactive and RESTEasy Classic removes it (that's not my change, it was there already) as they wanted exception mappers to handle exception

> we should now check if the default handler has already done its job

that's exactly what this change is doing; I can come with different mechanism to determine that default handler did it's job (event attribute with default handler signature or headers check), but I like this one as header check is prone to changes and I'm not sure default auth handler should add attribute we don't need, it doesn't provide any extra information. If it is there, we know it run as proactive auth is enabled.

> Should the exception mappers be checked first and only if no matching mapper has been found, then if it is an instance of AuthenticationException, do try the default handler

that would mean to add default auth failure handler as actual Vert.x failure handler, but it is not. The auth failure handler is called here when `proactive=true` and then event is failed. Yes, we could make your suggestion work, but it takes heavy refactoring and I strongly believe this is one of last changes needed for exception mappers/failure handlers of Quarkus Security exceptions to work. It was quite difficult to set up this flow as we need to thing of every eventuality.

> Or run the default handler only if no authentication exceptions have been detected at the build time and just skip a non-default handler altogether if the default handler has set a RouringContext property that it has handled the exception ? May be it is a better option

That could be done, but it was one of iterations we had and you basically said we should not allow extensions to stop default auth failure from running (at least that's how I understood it) - please don't make me to search for that comment, there was too many of them :-D. ATM that can't be done as:

1. RESTEasy Reactive can't prevent default auth failure handler when `proactive=true`, therefore it is always going to run
2. Vertx HTTP extension doesn't have knowledge of RESTEasy Reactive

**Comment by michalvavrik** [comment]
Btw. I think your justifiable - when Stuart wrote the default auth failure handler, it always ended event, therefore following situations could not happen. I turned how it is used little bit, but trying to keeping changes small I left default auth failure handler intact (except it does not end event).

**Comment by sberyozkin** [comment]
Sure, sounds like this is as best as we can have it, but what do you think about this one,

>RESTEasy Reactive can't prevent default auth failure handler when proactive=true, therefore it is always going to run

OK, I see what you based on the earlier comments

>Vertx HTTP extension doesn't have knowledge of RESTEasy Reactive

Sure, what I meant was not that Vertx HTTP extension would start checking Resteasy classic or reactive mappers, etc.
But something like this:
- resteasy classic/reactive build time processors check if authentication mappers are present, I think you might already be having some of such checks coded.
- if the proactive=true then a non-default handler is not even invoked after the default handler is run in case of the authentication exceptions

Can that work/be easy enough to support ?

**Comment by michalvavrik** [comment]
> * resteasy classic/reactive build time processors check if authentication mappers are present, I think you might already be having some of such checks coded.

True, we already have them, we could propagate them to Vert.x HTTP extension.

> * if the proactive=true then a non-default handler is not even invoked after the default handler is run in case of the authentication exceptions
> 
> Can that work/be easy enough to support ?

It works like this (I know you know this, but I need to provide context):

1. default auth _failure handler_ (not Vert.x failure handler, just piece of) fails event
2. RESTEasy Reactive Vert.x failure handler is called as it was added to the route and:
  - we always have to add this failure handler as it also handles `ForbiddenException` was thrown by permission checked
  - maybe (not sure without longer inspection TBH) it is possible some other handler throws auth exception. I believe saw situation when authentication didn't fail as route wasn't secured, but permission checker thrown auth failure exception. I think it was related to JWT validation, sorry to be vague here, maybe I got this one wrong.
  - it is possible to that there is custom AuthenticationFailedException so we need this failure handler to pass exception to exception mappers, but also AuthenticationRedicerException is throw and we don't want to invoke mappers for it. What then, should we have 4 failure handlers?
  - we could tell default auth failure handler do not fail one exception e.g. completion ex, but fail others as custom ex. mappers need to handle them. that is more complexity than this PR IMHO

**Comment by sberyozkin** [comment]
@michalvavrik OK, thanks, we need to fix this duplication problem asap anyway, and the fix is OK, so I'm going to merge.
But please think in the next while, if we can avoid Resteasy Reactive/Classic having to have dedicated protection against the duplicated authentication exception handling, it feels it can eventually go, I agree investigating this option can be done at some other time.
Thanks

**Review by sberyozkin — APPROVED** [review]

**Comment by sberyozkin** [comment]
@acoburn Hi Aaron, did you mean that you saw this problem with `2.14.3.Final` as well or only in the `2.15` stream ?

**Comment by michalvavrik** [comment]
> @michalvavrik OK, thanks, we need to fix this duplication problem asap anyway, and the fix is OK, so I'm going to merge. But please think in the next while, if we can avoid Resteasy Reactive/Classic having to have dedicated protection against the duplicated authentication exception handling, it feels it can eventually go, I agree investigating this option can be done at some other time. Thanks

Sure, I'm happy to do that. There have been many changes regarding exception mappers lately, let's keep it as is for a while.

**Comment by michalvavrik** [comment]
> @acoburn Hi Aaron, did you mean that you saw this problem with `2.14.3.Final` as well or only in the `2.15` stream ?

+1 to question, fyi Aaron - I tested your reproducer with 2.14.3.Final and could not reproduce it.

**Comment by sberyozkin** [comment]
Thanks, I was curious if a backport to 2.14 was needed, lets just have a backport (to 2.15) label for now only

**Comment by acoburn** [comment]
I definitely saw this problem in the 2.15 release. In our codebase where this issue appeared, I also saw it in 2.14.3, so it is curious that the reproducer on 2.14.3 doesn't surface the problem. In any case, fixing this for 2.15 would be great.

**Comment by michalvavrik** [comment]
Okay, thank you for letting us know, but @sberyozkin this fix can't be backported to 2.15 anyway, please don't do that, thanks.
