### PR TITLE
Print gradle error when test fails

### LINKED ISSUE #13382: CI is failing on Gradle tests MultiModuleUberJarTest.testUberJarForMultiModule()
**Describe the bug**
MultiModuleUberJarTest.testUberJarForMultiModule() is failing:
```
io.quarkus.gradle.MultiModuleUberJarTest > testUberJarForMultiModule() FAILED
    java.lang.AssertionError: 
    Expecting path:
      </home/runner/work/quarkus/quarkus/integration-tests/gradle/build/resources/test/uber-jar-for-multi-module-project/application/build>
    to exist (symbolic links were followed).
        at io.quarkus.gradle.MultiModuleUberJarTest.testUberJarForMultiModule(MultiModuleUberJarTest.java:29)

```

### PR DESCRIPTION
**Pull request by glefloch**
When a gradle test fails, it can be complicated to get the output. 

This prints the command output if the gradle wrapper process exit code is different from 0.

### CODE REVIEW

**Review by aloubyansky — APPROVED** [review]

File: integration-tests/gradle/src/test/java/io/quarkus/gradle/QuarkusGradleWrapperTestBase.java [hunk 1]
```diff
@@ -62,4 +65,9 @@ private String getGradleWrapperName() {
         }
         return systemProperties;
     }
+
+    private void printCommandOutput(List<String> command, BuildResult commandResult) {
+        System.err.println("Command : " + String.join(" ", command) + " failed with the following output :");
```
Comment (gsmet) [inline integration-tests/gradle/src/test/java/io/quarkus/gradle/QuarkusGradleWrapperTestBase.java:70]:
```suggestion
        System.err.println("Command: " + String.join(" ", command) + " failed with the following output:");
```

**Review by gsmet — CHANGES_REQUESTED** [review]
Sorry to be that guy :).

File: integration-tests/gradle/src/test/java/io/quarkus/gradle/QuarkusGradleWrapperTestBase.java (hunk 1 above)
Comment (glefloch) [reply integration-tests/gradle/src/test/java/io/quarkus/gradle/QuarkusGradleWrapperTestBase.java]: oh nice one! fixed.

**Comment by glefloch** [comment]
I rebased my branch last night, the failure is not related to GELF anymore but it does not looks related..

**Review by gsmet — APPROVED** [review]
