### PR TITLE
Make sure `quarkus.http.filter` headers don't remove existing headers

### LINKED ISSUE #38155: Using http filter config is disabling CORS options
### Describe the bug

When using a filter, it doesn't add the CORS headers anymore.

```properties
quarkus.resteasy-reactive.path=/api

quarkus.http.filter.api.header."X-Content-Type-Options"=nosniff
quarkus.http.filter.api.header."X-Frame-Options"=deny
quarkus.http.filter.api.header."Strict-Transport-Security"=max-age=31536000; includeSubDomains
quarkus.http.filter.api.header."Content-Security-Policy"=default-src 'none';
quarkus.http.filter.api.matches=/api/.+
quarkus.http.filter.api.order=1

quarkus.http.cors=true
quarkus.http.cors.origins=/.*/
```

### Expected behavior

The cors headers (**or any header that is set up elsewhere**) should be added in addition to the other headers

### Actual behavior

The cors headers are removed

### How to Reproduce?

Clone this and start https://github.com/ia3andy/reproducer-cors with `quarkus dev`

Use this in you browser console (on a tab with a different domain opened):
```javascript
fetch("http://localhost:8080/api/hello").then(r => r.text()).then(console.log)
```
It fails with CORS error.
Remove the filter from the properties and it works.

image

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

3.5+

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
The previous behavior would completely replace
existing response headers

Fixes: #38155

### CODE REVIEW

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/options/HttpServerCommonHandlers.java [hunk 1]
```diff
@@ -133,7 +133,7 @@ public void handle(RoutingContext event) {
                                 .handler(new Handler<RoutingContext>() {
                                     @Override
                                     public void handle(RoutingContext event) {
-                                        event.response().headers().setAll(headers);
+                                        event.response().headers().addAll(headers);
```
Comment (sberyozkin) [inline extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/options/HttpServerCommonHandlers.java:136]: I'm not too familiar with this code, but just in case, can this cause some headers (not even CORS related ) being duplicated ?

Comment (geoand) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/options/HttpServerCommonHandlers.java:136]: `add` does indeed add a header, not replace it, so it could theoretically duplicate a value. 

But I don't really think it's something this could should handle, I believe it's up to the user to ensure this doesn't happen.

Comment (cescoffier) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/options/HttpServerCommonHandlers.java:136]: We need to check how addAll handle duplicates. Headers are a multimap, so we may have multiple value for a single header. I'm not sure it's what we want in this case (but we need to verify).

Also, this should be considered as a breaking change.

**Review by cescoffier — CHANGES_REQUESTED** [review]
We need to verify how duplicates are handled.

Also, it needs to be marked as a breaking change.

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/options/HttpServerCommonHandlers.java (hunk 1 above)
Comment (geoand) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/options/HttpServerCommonHandlers.java:136]: > Also, this should be considered as a breaking change.

Yeah, I agree with this. It's breaking, although I argue that the intent was to do what is being done now.

Comment (cescoffier) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/options/HttpServerCommonHandlers.java:136]: I believe the reason behind `set` was this duplicate issue. 
With this PR, we cannot remove a value anymore or decide when we want a single or multiple values of a header (even if I agree that having multiple values of the same header is rarely used, this PR may introduce that case a lot more).

**Review by cescoffier — APPROVED** [review]

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/options/HttpServerCommonHandlers.java [hunk 2]
```diff
@@ -143,6 +147,27 @@ public void handle(RoutingContext event) {
...
+            if (oldValues.isEmpty()) {
+                responseHeaders.set(key, value);
+            } else {
+                // we need to make sure the new value is not duplicated
+                var newValues = new LinkedHashSet<String>(oldValues);
+                boolean added = newValues.add(value);
+                if (added) {
+                    responseHeaders.set(key, newValues);
+                } else {
+                    // we don't need to do anything here as the value was already in the set
```
Comment (gastaldi) [inline extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/options/HttpServerCommonHandlers.java:165]: Remove the unnecessary `else` block then?
```suggestion
                } else {
                    // we don't need to do anything here as the value was already in the set
```

Comment (gastaldi) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/options/HttpServerCommonHandlers.java:165]: I see, but it seems to be explicit in your code already and the IDE nags about empty else blocks 😜

Comment (geoand) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/options/HttpServerCommonHandlers.java:165]: I generally disable that inspection 😉

**Comment by ia3andy** [comment]
@gsmet it might make sense to backport this?

**Comment by geoand** [comment]
It's a breaking change, so best not to
