### PR TITLE
Ignore ContextNotActiveException in RESTEasy Reactive when clearing request

### LINKED ISSUE #25229: ContextNotActiveException in getDelegate
### Describe the bug

Related to #24626, I've seen the following error in a k8s pod running quarkus 2.8.1:

```
2022-04-28 13:34:05,364 ERROR [io.qua.ver.cor.run.VertxCoreRecorder] (vert.x-eventloop-thread-0) Uncaught exception received by Vert.x: javax.enterprise.context.ContextNotActiveException                                                                                      
    at io.quarkus.arc.impl.ClientProxies.getDelegate(ClientProxies.java:46)                                                                                                                                                                                                     
    at io.quarkus.vertx.http.runtime.CurrentVertxRequest_ClientProxy.arc$delegate(Unknown Source)                                                                                                                                                                               
    at io.quarkus.vertx.http.runtime.CurrentVertxRequest_ClientProxy.setOtherHttpContextObject(Unknown Source)                                                                                                                                                                  
    at io.quarkus.resteasy.reactive.server.runtime.QuarkusCurrentRequest.set(QuarkusCurrentRequest.java:25)                                                                                                                                                                     
    at org.jboss.resteasy.reactive.server.core.CurrentRequestManager.set(CurrentRequestManager.java:12)                                                                                                                                                                         
    at org.jboss.resteasy.reactive.server.core.ResteasyReactiveRequestContext.requestScopeDeactivated(ResteasyReactiveRequestContext.java:644)                                                                                                                                  
    at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:183)                                                                                                                                                    
    at org.jboss.resteasy.reactive.server.vertx.VertxResteasyReactiveRequestContext$1$1.handle(VertxResteasyReactiveRequestContext.java:73)                                                                                                                                     
    at org.jboss.resteasy.reactive.server.vertx.VertxResteasyReactiveRequestContext$1$1.handle(VertxResteasyReactiveRequestContext.java:70)                                                                                                                                     
    at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)                                                                                                                                                                                                    
    at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)                                                                                                                                                                                                     
    at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)                                                                                                                                                                                      
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)                                                                                                                                                                               
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)                                                                                                                                                                       
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)                                                                                                                                                                                                             
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)                                                                                                                                                                             
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)                                                                                                                                                                                                
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)                                                                                                                                                                                    
    at java.base/java.lang.Thread.run(Thread.java:829) 

```

I think this is also related to pipelining, but I can't reproduce it locally

### Expected behavior

No exception should be raised.

### Actual behavior

ContextNotActiveException is raised

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

5.13.0-40-generic

### Output of `java -version`

Java version: 11.0.13, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64

### GraalVM version (if different from Java)

N/A

### Quarkus version or git rev

2.8.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8.4

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #25229

### CODE REVIEW

File: extensions/resteasy-reactive/quarkus-resteasy-reactive/runtime/src/main/java/io/quarkus/resteasy/reactive/server/runtime/QuarkusCurrentRequest.java [hunk 1]
```diff
@@ -22,8 +24,12 @@ public ResteasyReactiveRequestContext get() {
     @Override
     public void set(ResteasyReactiveRequestContext set) {
         if (set == null) {
-            currentVertxRequest.setOtherHttpContextObject(null);
-            currentVertxRequest.setCurrent(null);
+            try {
+                currentVertxRequest.setOtherHttpContextObject(null);
+                currentVertxRequest.setCurrent(null);
+            } catch (ContextNotActiveException ignored) {
+
```
Comment (cescoffier) [inline extensions/resteasy-reactive/quarkus-resteasy-reactive/runtime/src/main/java/io/quarkus/resteasy/reactive/server/runtime/QuarkusCurrentRequest.java:31]: Maybe a comment explaining why we ignore it?

**Review by cescoffier — APPROVED** [review]

File: extensions/resteasy-reactive/quarkus-resteasy-reactive/runtime/src/main/java/io/quarkus/resteasy/reactive/server/runtime/QuarkusCurrentRequest.java (hunk 1 above)
Comment (geoand) [reply extensions/resteasy-reactive/quarkus-resteasy-reactive/runtime/src/main/java/io/quarkus/resteasy/reactive/server/runtime/QuarkusCurrentRequest.java:31]: Done
