### PR TITLE
Prevent false positive on quarkus.generate-code.grpc.kotlin.generate

### LINKED ISSUE #47134: Protobuf kotlin generation configuration produces `Unrecognized configuration key`
### Describe the bug

Quarkus 3.21 introduced Kotlin protobuf support, which is enabled by default if `quarkus-kotlin` is included. One can disable this via `quarkus.generate-code.grpc.kotlin.generate`.

However, in our project, when we set this value to false, we get the following log message during assembling:
```
Unrecognized configuration key "quarkus.generate-code.grpc.kotlin.generate" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
```

However, this is clearly false, because if we switch the value from false to true, the code breaks, which is expected for our codebase, since we want to disable the Kotlin protobuf for this specific module.

Note that we use `application.yml` to configure our Quarkus application

### Expected behavior

Setting `quarkus.generate-code.grpc.kotlin.generate` to false should disable kotlin protobuf generation, and not produce a log message

### Actual behavior

The value is correctly set and used, however the following log message is produced:
```
Unrecognized configuration key "quarkus.generate-code.grpc.kotlin.generate" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo

```

### How to Reproduce?

Reproducer:

Steps to reproduce this behaviour:
1. Go to https://gitlab.com/rug-digitallab/products/themis/runtimes/kotlin-runtimes and pull the develop branch
2. Run `./gradlew container-runtime:process-monitor:assemble`
3. Observe the log message

### Output of `uname -a` or `ver`

Ubuntu 24.10 Kernel version 6.11.0-21-generic

### Output of `java -version`

21.0.6

### Quarkus version or git rev

3.21.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.13

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
- Fixes: #47134

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]

File: extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/config/GrpcCodeGenConfig.java [hunk 1]
```diff
@@ -39,4 +42,11 @@ public interface GrpcCodeGenConfig {
      */
     @WithDefault("com.google.protobuf:protobuf-java")
     String scanForImports();
+
+    /**
+     * Controls whether Kotlin code is generated when the {@code quarkus-kotlin} extension is present (in which case the default
+     * is {@code true}).
+     */
+    @WithName("kotlin.generate")
+    Optional<Boolean> generateKotlin();
```
Comment (gastaldi) [inline extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/config/GrpcCodeGenConfig.java:51]: How about: 

```suggestion
    Optional<Boolean> kotlinGenerate();
```

Comment (geoand) [reply extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/config/GrpcCodeGenConfig.java:51]: Yeah that was the default IntelliJ suggested as well but I prefer methods to read with verb first (not that it really matters at all in this case).
