### PR TITLE
Fix WebSockets Next security context propagation in Tools when AI service returns `Multi`

### LINKED ISSUE #1418: Security context propagation in Tools
Hello,

I'm trying to get a `SecurityIdentity` injected into one of my AI tools but keeps coming as Anonymous. I'm wondering if it's something I'm doing wrong, or if there is an alternative way to go about it?

AI service:
```
@SessionScoped
@RegisterAiService (tools = DeviceTools.class)
public interface ChatbotAgentService {
	Multi<String> chat(@MemoryId String memoryId, @UserMessage String userMessage);
}
```

WebSocket:
```
@BearerTokenAuthentication
@WebSocket(path = "/api/v1")
public class ChatboxWebSocketV1  {
	@Inject SecurityIdentity securityIdentity;
	@Inject ChatbotAgentService chatbotAgentService;
	...
	@OnTextMessage
	@RolesAllowed(AppConstants.ROLE_USER)
	public Multi<ChatbotMessageDTO> onTextMessage(ChatbotMessageDTO message) {
		return chatbotAgentService.chat(securityIdentity.getPrincipal().getName(),
			message.getMessage()).map(
			reply -> new ChatbotMessageDTO()
				.setMessage(reply)
		);
	}
	
}
```

Tool:
```
@ApplicationScoped
public class DeviceTools {

	@Inject SecurityIdentity securityIdentity;

	@Tool("find the number of devices assigned to a specific status")
	public Uni<Long> devicesStatus(String status) {
		...
	}
```

In `ChatboxWebSocketV1` `SecurityIdentity` is properly populated, whereas in `DeviceTools` it's not (it produces an `AnonymousIdentityProvider`).

Thanks!

### PR DESCRIPTION
**Pull request by michalvavrik**
- closes: https://github.com/quarkiverse/quarkus-langchain4j/issues/1418

### CODE REVIEW

**Comment by sberyozkin** [comment]
Thanks @michalvavrik , also CC @geoand

**Review by gsmet — COMMENTED** [review]
I'm surprised we decide to not support the feature at all if the WebSockets.next extension is present?

You could have standard endpoints for which you want this feature and then a WS endpoint, where this is not supported?

Or am I mistaken?

**Comment by michalvavrik** [comment]
> You could have standard endpoints for which you want this feature and then a WS endpoint, where this is not supported?

That feature is basically this: "if you activate CDI request context that is not populated, we store RoutingContext on duplicated context and use it as source of truth", which in case of WS Next is not required. Now, can it be required for standard endpoint? No, there we prepare CDI request context for you. That is why `quarkus.http.auth.propagate-security-identity` is documented for use only with route handlers.

Since it was added, I suggested it as "workaround" in many edge cases before we fixed them, for example this one https://github.com/quarkusio/quarkus/issues/47259. I really don't mind making it work, it's just as far as we know, it is really edge case feature and it will require that we coordinate which `CurrentIdentityAssociation` has higher priority and WS Next implementing that feature for non-WS next endpoints.

TL;DR; if you feel it can be important, I can implement it quickly now. Let me know.

**Comment by michalvavrik** [comment]
Hmm, I'll just implement it, let me have a look now.

**Comment by michalvavrik** [comment]
Sorry for couple of pushes (CI triggers), I have mentioned few things when I triggered Quarkus build and edits using vi are not great. @gsmet done, thanks for the suggestion.

File: extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/AbstractSecurityIdentityAssociation.java [hunk 1]
```diff
@@ -14,9 +13,12 @@ public abstract class AbstractSecurityIdentityAssociation implements CurrentIden
 
     private volatile SecurityIdentity identity;
     private volatile Uni<SecurityIdentity> deferredIdentity;
+    private final IdentityProviderManager identityProviderManager;
 
-    @Inject
-    IdentityProviderManager identityProviderManager;
+    public AbstractSecurityIdentityAssociation() {
+        this.identityProviderManager = Arc.container() != null ? Arc.container().select(IdentityProviderManager.class).get()
```
Comment (mkouba) [inline extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/AbstractSecurityIdentityAssociation.java]: I don't have a context yet (didn't read all commetns and changes) but why this change? In general, we should try to avoid using `Arc.container()` instead of injection.

Comment (michalvavrik) [reply extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/AbstractSecurityIdentityAssociation.java]: Because https://github.com/quarkusio/quarkus/blob/main/test-framework/security/src/test/java/io/quarkus/test/security/TestIdentityAssociationTest.java is vanilla JUnit test that is run outside of Quarkus context. I don't want to rewrite some old test. Alternative is to require all subclasses to declare constructor and there is couple of them + it is part of SPI, I don't want to introduce breaking changes.

Comment (michalvavrik) [reply extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/AbstractSecurityIdentityAssociation.java]: I didn't add this abstract class so many releases back, I don't really believe there could be anyone else using it, so if you don't want this solution, I'll just add constructors to all subclasses. np

Comment (michalvavrik) [reply extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/AbstractSecurityIdentityAssociation.java]: Never mind, I chose a different solution. Let's have a look again. Thanks

**Comment by michalvavrik** [comment]
CI failures are unrelated, I can rebase again to trigger the build if required, but I'd rather wait if there are requests for change.

File: extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/HttpSecurityProcessor.java [hunk 2]
```diff
@@ -611,8 +611,12 @@ void generateAuthorizationPolicyStorage(BuildProducer<GeneratedBeanBuildItem> ge
     }
 
     @BuildStep(onlyIf = AlwaysPropagateSecurityIdentity.class)
-    AdditionalBeanBuildItem createSecurityIdentityAssociation() {
-        return AdditionalBeanBuildItem.unremovableOf(VertxSecurityIdentityAssociation.class);
+    AdditionalBeanBuildItem createSecurityIdentityAssociation(Capabilities capabilities) {
```
Comment (sberyozkin) [inline extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/HttpSecurityProcessor.java]: Can that cause side-effects when both WebSockets and regular HTTP are used independently of each other in the application ? For example, SPA offers a chat bot but also some other non-WS related things in another frame ?

Comment (michalvavrik) [reply extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/HttpSecurityProcessor.java]: Short answer is no. The principle is trivial, if the request is upgraded, we have connection and that connection has security identity. IF it is not WS next, we don't have the connection stored on duplicated context, so everything works as usual. There are tests (of course not covering every possible scenario, but it is the same code in action as when WS next is not present).

**Comment by michalvavrik** [comment]
I have rebased on the current main to see if CI is in a better state now.

**Comment by michalvavrik** [comment]
@mkouba could you review, please? I am open to suggestions regarding constructors etc., but it has been month since I opened this PR. Thanks

**Comment by michalvavrik** [comment]
I just rebased (twice), no changes. These failures seem unrelated, like `Error while binding on /127.0.0.1:53530 ..  Address already in use: bind`.

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/VertxSecurityIdentityAssociation.java [hunk 3]
```diff
@@ -16,6 +18,14 @@
 @RequestScoped
 public class VertxSecurityIdentityAssociation extends AbstractSecurityIdentityAssociation {
 
+    @Inject
+    public VertxSecurityIdentityAssociation() {
+    }
+
+    public VertxSecurityIdentityAssociation(IdentityProviderManager identityProviderManager) {
```
Comment (mkouba) [inline extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/VertxSecurityIdentityAssociation.java]: I think that you could just keep this constructor, annotate it with `@Inject`, and remove the no-args constructor from `AbstractSecurityIdentityAssociation` and `@Inject` from the  `AbstractSecurityIdentityAssociation#identityProviderManager` field.

**Review by mkouba — APPROVED** [review]
It looks good but my knowledge of security stuff is quite limited...

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/VertxSecurityIdentityAssociation.java (hunk 3 above)
Comment (michalvavrik) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/VertxSecurityIdentityAssociation.java]: > I think that you could just keep this constructor, annotate it with `@Inject`, and remove the no-args constructor from `AbstractSecurityIdentityAssociation` and `@Inject` from the `AbstractSecurityIdentityAssociation#identityProviderManager` field.

For the constructor injection I started getting:

```
Caused by: jakarta.enterprise.inject.spi.DeploymentException: It's not possible to automatically add a synthetic no-args constructor to an unproxyable bean class. You need to manually add a non-private no-args constructor to io.quarkus.security.runtime.SecurityIdentityAssociation in order to fulfill the requirements for normal scoped/intercepted/decorated beans.
	at io.quarkus.arc.processor.Beans.cannotAddSyntheticNoArgsConstructor(Beans.java:1104)
	at io.quarkus.arc.processor.Beans.validateBean(Beans.java:901)
	at io.quarkus.arc.processor.BeanInfo.validate(BeanInfo.java:666)
	at io.quarkus.arc.processor.BeanDeployment.validateBeans(BeanDeployment.java:1706)
	at io.quarkus.arc.processor.BeanDeployment.validate(BeanDeployment.java:520)
	at io.quarkus.arc.processor.BeanProcessor.validate(BeanProcessor.java:187)
```

so I went with no-args constructors and setters / abstract methods, it is more verbose but not really important

**Comment by michalvavrik** [comment]
> It looks good but my knowledge of security stuff is quite limited...

sure, this PR requires @sberyozkin approval, but we needed your WS Next expertise, thanks for the review.

**Comment by michalvavrik** [comment]
last ping @sberyozkin

File: extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/HttpSecurityProcessor.java (hunk 2 above)
Comment (sberyozkin) [reply extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/HttpSecurityProcessor.java]: @michalvavrik It stlll looks a little bit unusual that if it is a non-WS-Next request, it will be an instance of the WebSocketSecurityIdentityAssociation

File: extensions/websockets-next/runtime/src/main/java/io/quarkus/websockets/next/runtime/WebSocketSecurityIdentityAssociation.java [hunk 4]
```diff
@@ -0,0 +1,77 @@
...
+import io.quarkus.security.identity.SecurityIdentity;
+import io.quarkus.security.spi.runtime.AbstractSecurityIdentityAssociation;
+import io.quarkus.vertx.http.runtime.security.VertxSecurityIdentityAssociation;
+import io.smallrye.common.vertx.VertxContext;
+import io.smallrye.mutiny.Uni;
+import io.vertx.core.Context;
+import io.vertx.core.Vertx;
+
+@RequestScoped
+public class WebSocketSecurityIdentityAssociation implements CurrentIdentityAssociation {
```
Comment (sberyozkin) [inline extensions/websockets-next/runtime/src/main/java/io/quarkus/websockets/next/runtime/WebSocketSecurityIdentityAssociation.java:19]: @michalvavrik Can you clarify please why we can't extend the Vert.x one here and may be override some methods ? Just would like to understand pros and cons

**Comment by sberyozkin** [comment]
@michalvavrik Hi Michal, apologies for delaying reviewing it, it is never my intention to ignore PRs, I was trying to catch up with some easy fixes that I had to do, given this PR is rather complex, thanks

File: extensions/websockets-next/runtime/src/main/java/io/quarkus/websockets/next/runtime/WebSocketSecurityIdentityAssociation.java (hunk 4 above)
Comment (michalvavrik) [reply extensions/websockets-next/runtime/src/main/java/io/quarkus/websockets/next/runtime/WebSocketSecurityIdentityAssociation.java:19]: > @michalvavrik Can you clarify please why we can't extend the Vert.x one here and may be override some methods ? Just would like to understand pros and cons

I am aware it is complex and I have plenty of ideas to simplify it, but I can't remember issues related to this. So here is how it works:

- standard `SecurityIdentityAssociation` - primary source is CDI request context pre-populated from `RoutingContext` and whenever Quarkus updated CDI request context, we attempt to propagate it back to `RoutingContext`; however, users can and occasionally do weird stuff like setting identity association directly and which case they diverge
- association enabled when `quarkus.http.auth.propagate-security-identity` is set to `true` -`VertxSecurityIdentityAssociation` - differs from "standard association" in a sense that primary source for identity is `RoutingContext` stored on a duplicated context and users can't override it on CDI request context, but they can access it even when CDI context propagation fails them
- WebSockets identity association - here is situation different in a sense that CDI request context is pre-populated from `SecuritySupport` and users can change in the active CDI request context `CurrentIdentityAssociation` as before (makes no sense)
  - This PR keeps previous behavior for other stacks and for WebSockets Next it keeps `SecuritySupport` as a primary source. Nothing should change really. The main difference is "what happens after CDI request context activated in a WS Next endpoint callback was closed"? I say we need to rely on the identity we still can see on the WS Next connection instead of serving "anonymous identity".

> why we can't extend the Vert.x one here

1.  WebSockets Next can be used together with other stacks and they would effectively get `quarkus.http.auth.propagate-security-identity=true` in Quarkus REST and other stacks
2. adding items to duplicated context local data on hot path is expensive because it uses concurrent hash map and synchronize the addition, I try to avoid that, so I leveraged the fact that WebSockets connection is already stored on duplicated context

> may be override some methods

I looked into this based on your comment and I agree these codes are very similar, but we need to keep the WS Next class `SecuritySupport` because it handles stuff like `SecurityIdentity` update. I'd have to add another level of abstraction, I am not sure it that code would be easier to read than this PR, but yes, we can do that if you feel we should.

**Comment by michalvavrik** [comment]
I have rebased on the current main and made tiny little tweak to the WS Next identity association to assure that nothing really changes for users with this PR in case they do some custom stuff and change identity inside WS Next endpoint callbacks (no idea if someone does it, I just want to be safe).

File: extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/HttpSecurityProcessor.java (hunk 2 above)
Comment (michalvavrik) [reply extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/HttpSecurityProcessor.java]: > @michalvavrik It stlll looks a little bit unusual that if it is a non-WS-Next request, it will be an instance of the WebSocketSecurityIdentityAssociation

Agreed. We can't have 2 different beans based on which stack is invoked though.

I want to clarify that I think that some overall refactoring would help and I don't say this is pretty solution. My dream is to have one source on the duplicated context, which would simplify great deal of things, but I don't think we will be allowed to do that as it would happen for each request when security is present. As long as we have multiple sources of identity, we have to do something like I do in this PR. If you think it should be refactored in some way - suggest it.

Comment (michalvavrik) [reply extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/HttpSecurityProcessor.java]: I think I'll ask Clement why Vert.x couldn't start supporting something that would help us if/when I speak to him. It would help.

File: extensions/websockets-next/runtime/src/main/java/io/quarkus/websockets/next/runtime/WebSocketSecurityIdentityAssociation.java (hunk 4 above)
Comment (sberyozkin) [reply extensions/websockets-next/runtime/src/main/java/io/quarkus/websockets/next/runtime/WebSocketSecurityIdentityAssociation.java:19]: @michalvavrik The summary makes the difference between various associations clear, `VertxSecurityIdentityAssociation` should probably be renamed to `PropagatedSecurityIdentityAssociation`  or `DuplicatedContextSecurityIdentityAssociation` to make it clear what it is about, as it is really about supporting a specific case.

Comment (sberyozkin) [reply extensions/websockets-next/runtime/src/main/java/io/quarkus/websockets/next/runtime/WebSocketSecurityIdentityAssociation.java:19]: Though this renaming can be done later

File: extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/HttpSecurityProcessor.java (hunk 2 above)
Comment (sberyozkin) [reply extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/HttpSecurityProcessor.java]: @michalvavrik What I propose may be all rather cosmetic, but I think I'd prefer to read something like this here:
```
void buildStep(Optional<PropagatedSecurityIdentityAssociationItem> item) {
     if (!item.isPresent()) {
           return AdditionalBeanBuildItem.unremovableOf(PropagatedSecurityIdentityAssociation.class);
     }
}
```

This just reads a bit strange to me that here we explicitly rely to WS Next to support the identity prop even for non-WS requests...

File: extensions/websockets-next/runtime/src/main/java/io/quarkus/websockets/next/runtime/WebSocketSecurityIdentityAssociation.java (hunk 4 above)
Comment (michalvavrik) [reply extensions/websockets-next/runtime/src/main/java/io/quarkus/websockets/next/runtime/WebSocketSecurityIdentityAssociation.java:19]: I like the `DuplicatedContextSecurityIdentityAssociation` because it makes it clear what it does, but let's not do it in this PR, I think it should be dedicated PR.

File: extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/HttpSecurityProcessor.java (hunk 2 above)
Comment (michalvavrik) [reply extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/HttpSecurityProcessor.java]: Sure, I'll do that.

**Comment by sberyozkin** [comment]
Hi @michalvavrik I think it is ready to go, and now that you have summarized the difference between various associations, it is all actually rather straightforward, thanks for making it so clear.

So, at this stage, I'm only thinking about a couple of optional minor updates:
* Rename Vertx one as it is hard to see from the name how it differs from the default SecurityIdentityAssociation (can be done later)
* Make it read less WS-Next dependent at the Vert.x level when choosing whether we want to use the Vert.x one to support the security identity propagation or not

Do you think it may be worth tweaking it a bit more ?
I'm fine with considering doing it in a follow up PR later

File: extensions/websockets-next/runtime/src/main/java/io/quarkus/websockets/next/runtime/WebSocketSecurityIdentityAssociation.java (hunk 4 above)
Comment (michalvavrik) [reply extensions/websockets-next/runtime/src/main/java/io/quarkus/websockets/next/runtime/WebSocketSecurityIdentityAssociation.java:19]: Although as I'll already make related changes as for your build item proposal, I'll rename it.

File: extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/HttpSecurityProcessor.java (hunk 2 above)
Comment (sberyozkin) [reply extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/HttpSecurityProcessor.java]: @michalvavrik Thanks, if that proves tricky due to some ordering issues then let's keep it as is for now

Comment (michalvavrik) [reply extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/HttpSecurityProcessor.java]: > @michalvavrik Thanks, if that proves tricky due to some ordering issues then let's keep it as is for now

This code is gone, so I consider this comment thread resolved.

**Comment by michalvavrik** [comment]
@sberyozkin I think I have addressed your comments, though maybe not exactly as you suggested. If it looks good, let's wait for the full CI to run before you review, I only run tests I thought that were related.

File: extensions/websockets-next/runtime/src/main/java/io/quarkus/websockets/next/runtime/WebSocketSecurityIdentityAssociation.java (hunk 4 above)
Comment (michalvavrik) [reply extensions/websockets-next/runtime/src/main/java/io/quarkus/websockets/next/runtime/WebSocketSecurityIdentityAssociation.java:19]: Done.

File: extensions/security/deployment/src/main/java/io/quarkus/security/deployment/SecurityProcessor.java [hunk 5]
```diff
@@ -1116,12 +1118,21 @@ FeatureBuildItem feature() {
...
-        beans.produce(AdditionalBeanBuildItem.unremovableOf(SecurityIdentityAssociation.class));
+        beans.produce(AdditionalBeanBuildItem.unremovableOf(PrincipalProducer.class));
         beans.produce(AdditionalBeanBuildItem.unremovableOf(IdentityProviderManagerCreator.class));
         beans.produce(AdditionalBeanBuildItem.unremovableOf(SecurityIdentityProxy.class));
         beans.produce(AdditionalBeanBuildItem.unremovableOf(X509IdentityProvider.class));
     }
 
+    @BuildStep
+    AdditionalBeanBuildItem registerIdentityAssociationBean(
+            Optional<DefaultIdentityAssociationClassBuildItem> customDefaultIdentityClass) {
```
Comment (sberyozkin) [inline extensions/security/deployment/src/main/java/io/quarkus/security/deployment/SecurityProcessor.java]: @michalvavrik Would it make sense to rename `DefaultIdentityAssociationClassBuildItem` to `CurrentIdentityAssociationClassBuildItem` ? Given that the `SecurityIdentityAssociation` is an actual default association ?

File: extensions/security/spi/src/main/java/io/quarkus/security/spi/DefaultIdentityAssociationClassBuildItem.java [hunk 6]
```diff
@@ -0,0 +1,26 @@
...
+import io.quarkus.builder.item.SimpleBuildItem;
+import io.quarkus.security.identity.CurrentIdentityAssociation;
+
+/**
+ * Allows Quarkus core extensions to provide their default {@link io.quarkus.security.identity.CurrentIdentityAssociation}.
+ * This bean is used to synchronize the association produced by Quarkus core extensions and can change if needed.
+ * Other extensions and users can simply define alternative {@link io.quarkus.security.identity.CurrentIdentityAssociation}
+ * CDI bean.
+ */
+public final class DefaultIdentityAssociationClassBuildItem extends SimpleBuildItem {
```
Comment (sberyozkin) [inline extensions/security/spi/src/main/java/io/quarkus/security/spi/DefaultIdentityAssociationClassBuildItem.java]:
```suggestion
public final class CurrentIdentityAssociationClassBuildItem extends SimpleBuildItem {
```

File: extensions/security/spi/src/main/java/io/quarkus/security/spi/DefaultIdentityAssociationClassBuildItem.java [hunk 7]
```diff
@@ -0,0 +1,26 @@
+package io.quarkus.security.spi;
+
+import java.util.Objects;
+
+import io.quarkus.builder.item.SimpleBuildItem;
+import io.quarkus.security.identity.CurrentIdentityAssociation;
+
+/**
+ * Allows Quarkus core extensions to provide their default {@link io.quarkus.security.identity.CurrentIdentityAssociation}.
```
Comment (sberyozkin) [inline extensions/security/spi/src/main/java/io/quarkus/security/spi/DefaultIdentityAssociationClassBuildItem.java]:
```suggestion
 * Allows Quarkus core extensions to supply a {@link io.quarkus.security.identity.CurrentIdentityAssociation} implementation.
```

File: extensions/security/deployment/src/main/java/io/quarkus/security/deployment/SecurityProcessor.java (hunk 5 above)
Comment (michalvavrik) [reply extensions/security/deployment/src/main/java/io/quarkus/security/deployment/SecurityProcessor.java]: Yeah, I think that sounds better. Thanks

File: extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/HttpSecurityProcessor.java [hunk 8]
```diff
@@ -678,8 +678,8 @@ void generateAuthorizationPolicyStorage(BuildProducer<GeneratedBeanBuildItem> ge
     }
 
     @BuildStep(onlyIf = AlwaysPropagateSecurityIdentity.class)
-    AdditionalBeanBuildItem createSecurityIdentityAssociation() {
-        return AdditionalBeanBuildItem.unremovableOf(VertxSecurityIdentityAssociation.class);
+    DefaultIdentityAssociationClassBuildItem createSecurityIdentityAssociation() {
```
Comment (sberyozkin) [inline extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/HttpSecurityProcessor.java]: @michalvavrik Does it duplicate the WS Next association ? In your original code this step was skipped if the WS Next capability was present...

**Comment by sberyozkin** [comment]
Thanks @michalvavrik IMHO it looks more like it,  more like a pluggable approach, I proposed renaming the build item as I guess we should only associate `Default` with the `SecurityIdentityAssociation`.

Other than that, I was not sure if we do not duplicate it now between Vert.x and WS Next...

File: extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/HttpSecurityProcessor.java (hunk 8 above)
Comment (michalvavrik) [reply extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/HttpSecurityProcessor.java]: This changes `DuplicatedContextSecurityIdentityAssociation` to a default bean, similarly to what I made `SecurityIdentityAssociation` some time ago. When WS Next association defines its own `WebSocketSecurityIdentityAssociation`, then CDI just use that one instead of the Vert.X one.

We could take it further because WS Next still creates `DuplicatedContextSecurityIdentityAssociation` manually when `quarkus.http.auth.propagate-security-identity=true`. I tried to bytecode transform WS Next to create whatever is `CurrentIdentityAssociationClassBuildItem` value, but abandoned it because I didn't feel it was worth it. If you feel it is still not quite it, just comment more. No problem.

**Review by sberyozkin — APPROVED** [review]

File: extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/HttpSecurityProcessor.java (hunk 8 above)
Comment (sberyozkin) [reply extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/HttpSecurityProcessor.java]: @michalvavrik I see, it is fine as it is then, thanks
