### PR TITLE
Fix null logger

### LINKED ISSUE #34717: Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:3.2.0.Final:generate-code
### Describe the bug

My jenkins build failed with the error below after upgrading to `quarkus 3.2.0.Final`, the maven version is `3.9.1`

```
INFO] --- quarkus:3.2.0.Final:generate-code (default) @ lqa-service ---
[WARNING] Error injecting: io.quarkus.maven.GenerateCodeMojo
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) [Guice/ErrorInjectingConstructor]: NullPointerException: Cannot invoke "io.quarkus.devtools.messagewriter.MessageWriter.warn(String, Object[])" because "this.log" is null
  at BuildAnalyticsProvider.<init>(BuildAnalyticsProvider.java:35)
  at ClassRealm[plugin>io.quarkus.platform:quarkus-maven-plugin:Final, parent: URLClassLoader@723279cf]
      \_ installed by: WireModule -> PlexusBindingModule
  at BootstrapSessionListener.<init>(BootstrapSessionListener.java:26)
      \_ for 2nd parameter buildAnalyticsProvider
  at ClassRealm[plugin>io.quarkus.platform:quarkus-maven-plugin:Final, parent: URLClassLoader@723279cf]
      \_ installed by: WireModule -> PlexusBindingModule
  while locating BootstrapSessionListener
  while locating Object annotated with *
  while locating GenerateCodeMojo

Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR

1 error

======================
Full classname legend:
======================
....

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.655 s
[INFO] Finished at: 2023-07-13T02:21:32Z
[INFO] ------------------------------------------------------------------------
[INFO] [jenkins-event-spy] Generated ...abc.log
....

[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:3.2.0.Final:generate-code (default) on project xxx-service: Execution default of goal io.quarkus.platform:quarkus-maven-plugin:3.2.0.Final:generate-code failed: Unable to load the mojo 'generate-code' (or one of its required components) from the plugin 'io.quarkus.platform:quarkus-maven-plugin:3.2.0.Final': com.google.inject.ProvisionException: Unable to provision, see the following errors:
[ERROR] 
[ERROR] 1) [Guice/ErrorInjectingConstructor]: NullPointerException: Cannot invoke "io.quarkus.devtools.messagewriter.MessageWriter.warn(String, Object[])" because "this.log" is null
[ERROR]   at BuildAnalyticsProvider.<init>(BuildAnalyticsProvider.java:35)
[ERROR]   at ClassRealm[plugin>io.quarkus.platform:quarkus-maven-plugin:Final, parent: URLClassLoader@723279cf]
[ERROR]       \_ installed by: WireModule -> PlexusBindingModule
[ERROR]   at BootstrapSessionListener.<init>(BootstrapSessionListener.java:26)
[ERROR]       \_ for 2nd parameter buildAnalyticsProvider
[ERROR]   at ClassRealm[plugin>io.quarkus.platform:quarkus-maven-plugin:Final, parent: URLClassLoader@723279cf]
[ERROR]       \_ installed by: WireModule -> PlexusBindingModule
[ERROR]   while locating BootstrapSessionListener
[ERROR]   while locating Object annotated with *
[ERROR]   while locating GenerateCodeMojo
[ERROR]   at ClassRealm[plugin>io.quarkus.platform:quarkus-maven-plugin:Final, parent: URLClassLoader@723279cf]
[ERROR]       \_ installed by: WireModule -> PlexusBindingModule
[ERROR]   while locating Mojo annotated with @Named("io.quarkus.platform:quarkus-maven-plugin:3.2.0.Final:generate-code")
[ERROR] 
[ERROR] Learn more:
[ERROR]   https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR
[ERROR] 
[ERROR] 1 error
[ERROR] 
[ERROR] ======================
[ERROR] Full classname legend:
[ERROR] ======================
[ERROR] BootstrapSessionListener: "io.quarkus.maven.components.BootstrapSessionListener"
[ERROR] BuildAnalyticsProvider:   "io.quarkus.maven.BuildAnalyticsProvider"
[ERROR] Final:                    "3.2.0.Final"
[ERROR] GenerateCodeMojo:         "io.quarkus.maven.GenerateCodeMojo"
[ERROR] Mojo:                     "org.apache.maven.plugin.Mojo"
[ERROR] Named:                    "com.google.inject.name.Named"
[ERROR] PlexusBindingModule:      "org.eclipse.sisu.plexus.PlexusBindingModule"
[ERROR] URLClassLoader:           "java.net.URLClassLoader"
[ERROR] WireModule:               "org.eclipse.sisu.wire.WireModule"
[ERROR] ========================
[ERROR] End of classname legend:
[ERROR] ========================
[ERROR] 
[ERROR]       role: org.apache.maven.plugin.Mojo
[ERROR]   roleHint: io.quarkus.platform:quarkus-maven-plugin:3.2.0.Final:generate-code
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException
[Pipeline] }
```

### Output of `java -version`

17

### Quarkus version or git rev

3.2.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven 3.9.1, 3.9.2

### PR DESCRIPTION
**Pull request by brunobat**
fixes #34717 
Also introduces additional hardening in the AnalyticsService. 
Refactoring and adjust log levels.

### CODE REVIEW

File: independent-projects/tools/analytics-common/src/main/java/io/quarkus/analytics/AnalyticsService.java [hunk 1]
```diff
@@ -70,17 +70,22 @@ public class AnalyticsService implements AutoCloseable {
...
     final private ConfigService config;
-    final private AnonymousUserId userId;
+    final private AnonymousUserId anonymousUserId;
     final private MessageWriter log;
     final FileLocations fileLocations;
 
     public AnalyticsService(final FileLocations fileLocations, MessageWriter log) {
         this.fileLocations = fileLocations;
-        this.log = log;
+        if (log == null) {
```
Comment (aloubyansky) [inline independent-projects/tools/analytics-common/src/main/java/io/quarkus/analytics/AnalyticsService.java:79]: @brunobat in which case log could be null? Is it not a required argument?

Comment (brunobat) [reply independent-projects/tools/analytics-common/src/main/java/io/quarkus/analytics/AnalyticsService.java:79]: It is, I'm just making sure we don't have a null Pointer because of this.

Comment (aloubyansky) [reply independent-projects/tools/analytics-common/src/main/java/io/quarkus/analytics/AnalyticsService.java:79]: Do you know how it could end up being null?

Comment (brunobat) [reply independent-projects/tools/analytics-common/src/main/java/io/quarkus/analytics/AnalyticsService.java:79]: No, it shouldn't be. I'm just being extra cautious. I don't want ppl to have erros because of some exotic setup.

File: independent-projects/tools/analytics-common/src/main/java/io/quarkus/analytics/AnonymousUserId.java [hunk 2]
```diff
@@ -29,8 +29,8 @@ public static AnonymousUserId getInstance(final FileLocations fileLocations, fin
 
     // Singleton
     private AnonymousUserId(final FileLocations fileLocations, final MessageWriter log) {
-        this.uuid = loadOrCreate(fileLocations.getUUIDFile());
         this.log = log;
+        this.uuid = loadOrCreate(fileLocations.getUUIDFile());
```
Comment (aloubyansky) [inline independent-projects/tools/analytics-common/src/main/java/io/quarkus/analytics/AnonymousUserId.java:33]: Yes, this is the actual fix.

**Review by aloubyansky — APPROVED** [review]
