### PR TITLE
Fix vertx otel sdk reload in devmode

### LINKED ISSUE #29645: OpenTelemetry instrumentation stops working for resteasy-reactive resources and JDBC after dev mode reload
### Describe the bug

OTEL instrumentation seems to stop working for resteasy-reactive resources and JDBC calls when dev mode is reloaded (manually or due to a file change).
The reproducer further down demonstrates that via the logged MDC values, but it is *not* a mere MDC issue.
I first found this issue on my local Jaeger instance. I was missing some traces and spans and instead I got some unexpected traces that are supposed to be sub-spans of traces.
I also didn't see any JDBC sub-spans in my `@Scheduled` traces anymore (see also https://github.com/quarkusio/quarkus/issues/28552#issuecomment-1332546555).

### Expected behavior

Traces are generated just like before the dev mode reload

### Actual behavior

No proper traces are generated anymore after dev mode reload

### How to Reproduce?

1. start dev mode in the [OTEL-quickstart](https://github.com/quarkusio/quarkus-quickstarts/tree/main/opentelemetry-quickstart) via:
    ```
    mvn quarkus:dev -Dquarkus.log.console.format='%d{HH:mm:ss} %-5p (%X{traceId},%X{spanId}) [%c{2.}] (%t) %s%e%n'
    ```
2. call http://localhost:8080/hello
3. verify that trace and span ids are logged, e.g. (first bracket): 
    ```
   17:25:09 INFO  (f67e99e80328a210c23f58665ade8ffd,e561a98c8dcc9b37) [or.ac.op.TracedResource] (executor-thread-1) hello
    ```
4. hit `s` in dev mode (or change a file and call `/hello`)
5. call http://localhost:8080/hello
6. from this point on only zeros are logged for both ids:
    ```
   17:25:47 INFO  (00000000000000000000000000000000,0000000000000000) [or.ac.op.TracedResource] (executor-thread-0) hello
    ``` 

Note: This quickstart is a bit sparse ATM, see also: https://github.com/quarkusio/quarkus-quickstarts/pull/1120

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.14.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

Another user had the same issue a few months back: https://github.com/quarkusio/quarkus/issues/26804#issuecomment-1189713976

It's worth stressing that bean methods annotated with `@WithSpan` are still working after reload, but obviously, if those calls are sub-spans of REST calls they are shown as separate traces in Jaeger as there is no parent trace anymore.

### PR DESCRIPTION
**Pull request by brunobat**
- Fixes https://github.com/quarkusio/quarkus/issues/29645

Part of #26444
Currently OTel will not live reload, working only on first start. 

This PR includes: 
* Centralise instrumentation related classes in the Instrumentation processor and recorder.
* Create an OpenTelemetryWapper that will detect when the global OTel SDK has changed in development mode.

---------

Caveat: 
* On REST requests, the first instrumentation call after reload doesn't send span because OTEL is reloaded after the return of the call. The REST call starts with the old OTel SDK object in the vertx instrumentation and ends with the new one.

### CODE REVIEW

**Review by radcortez — CHANGES_REQUESTED** [review]
I think we need to avoid the check on each tracer method because this would only be useful for DEV mode, but we still are doing the check for runtime with no gain.

My recommendation is to produce a CDI Bean of `VertxTracer`, so we have updated Instrumenters with the correct OpenTelemetry instance. Then in the `OpenTelemetryVertxTracingFactory`, we just have a delegate to the CDI `VertTracer` and keep a reference to the one we pass to the factory, so we can update it by replacing the new CDI Bean on reload.

To make the span also works on the reload request, I think we can recreate the start of the span on `VertxHttpHotReplacementSetup` before the root handler dispatches the current request. We have the instance of `VertxTracer`, so we can call the `receiveRequest` method, and we should have everything available for it.

The tricky part is that the current request holds the state of the Trace object (created initially by the request that triggered the reload). In this case, we would need to access the request internal state directly to replace the Trace object. There are no API's for that, but I think that some bytecode transformations for this particular case (and only for DEV mode) are not going to hurt.

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/intrumentation/vertx/wrapper/DevModeOpenTelemetryWrapper.java [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+
+    @Override
+    public OpenTelemetry get() {
+        return openTelemetry;
+    }
+
+    @Override
+    public Boolean resetIfChanged() {
+        OpenTelemetry currentOpenTelemetry = GlobalOpenTelemetry.get();
+        if (this.openTelemetry != null && this.openTelemetry.equals(currentOpenTelemetry)) {
```
Comment (stuartwdouglas) [inline extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/intrumentation/vertx/wrapper/DevModeOpenTelemetryWrapper.java:21]: This should probably just be an `==`, as it is the identity that we care about.

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/intrumentation/vertx/wrapper/OpenTelemetryWrapper.java [hunk 2]
```diff
@@ -0,0 +1,11 @@
+package io.quarkus.opentelemetry.runtime.tracing.intrumentation.vertx.wrapper;
+
+import io.opentelemetry.api.OpenTelemetry;
+
+public interface OpenTelemetryWrapper {
+
+    OpenTelemetry get();
+
+    Boolean resetIfChanged();
```
Comment (stuartwdouglas) [inline extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/intrumentation/vertx/wrapper/OpenTelemetryWrapper.java:9]: Shouldn't this be `boolean` rather than `Boolean`

**Review by stuartwdouglas — CHANGES_REQUESTED** [review]

**Comment by stuartwdouglas** [comment]
> I think we need to avoid the check on each tracer method because this would only be useful for DEV mode, but we still are doing the check for runtime with no gain.
> 
> My recommendation is to produce a CDI Bean of `VertxTracer`, so we have updated Instrumenters with the correct OpenTelemetry instance. Then in the `OpenTelemetryVertxTracingFactory`, we just have a delegate to the CDI `VertTracer` and keep a reference to the one we pass to the factory, so we can update it by replacing the new CDI Bean on reload.
> 

The current check is basically just a volatile read. The CDI approach you are talking about will almost certainly be way more expensive per request.

**Comment by brunobat** [comment]
> > I think we need to avoid the check on each tracer method because this would only be useful for DEV mode, but we still are doing the check for runtime with no gain.
> > My recommendation is to produce a CDI Bean of `VertxTracer`, so we have updated Instrumenters with the correct OpenTelemetry instance. Then in the `OpenTelemetryVertxTracingFactory`, we just have a delegate to the CDI `VertTracer` and keep a reference to the one we pass to the factory, so we can update it by replacing the new CDI Bean on reload.
> 
> The current check is basically just a volatile read. The CDI approach you are talking about will almost certainly be way more expensive per request.

I would prefer the current strategy and maybe simplify the detection to setup instrumenters in a helper method. The resetIfChanged() in prod mode is a constant anyway... I bet this will get optimised. 
I would prefer to avoid anything CDI related, if possible.

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/intrumentation/vertx/OpenTelemetryVertxTracingFactory.java [hunk 3]
```diff
@@ -3,21 +3,36 @@
...
 
 public class OpenTelemetryVertxTracingFactory implements VertxTracerFactory {
+    HttpInstrumenterVertxTracer httpInstrumenterVertxTracer;
+
+    public OpenTelemetryVertxTracingFactory(HttpInstrumenterVertxTracer httpInstrumenterVertxTracer) {
+        this.httpInstrumenterVertxTracer = httpInstrumenterVertxTracer;
+    }
+
     @Override
     public VertxTracer<?, ?> tracer(final TracingOptions options) {
```
[the remark this answers is not in the document]
Comment (brunobat) [reply extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/intrumentation/vertx/OpenTelemetryVertxTracingFactory.java:15]: done

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/intrumentation/vertx/wrapper/DevModeOpenTelemetryWrapper.java (hunk 1 above)
Comment (brunobat) [reply extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/intrumentation/vertx/wrapper/DevModeOpenTelemetryWrapper.java]: obsolete

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/intrumentation/vertx/wrapper/OpenTelemetryWrapper.java (hunk 2 above)
Comment (brunobat) [reply extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/intrumentation/vertx/wrapper/OpenTelemetryWrapper.java]: obsolete

**Comment by brunobat** [comment]
@stuartwdouglas , in the end, @radcortez proposal about creating delegates on the the Tracer Factory makes more sense because it will not require future changes in the instrumenters themselves.
I avoided CDI altogether and I'm using a simplified factory for production code.

**Review by radcortez — APPROVED** [review]

**Review by stuartwdouglas — APPROVED** [review]

**Review by ozangunalp — APPROVED** [review]

**Comment by brunobat** [comment]
@gsmet any prediction on when this can be merged?

**Comment by radcortez** [comment]
I'll merge it.
