### PR TITLE
Opens modules for Netty, JEP 471, Unsafe

### LINKED ISSUE #39907: Some Netty features are not enabled by default
### Description

Currently there are (after the introduction of Java modules), few Netty features, which are not enabled because the "right" JVM args are not present by default on quarkus applications:
1. allocating direct buffer(s) without `Cleaner`s: this is used on off-heap pooled arena(s) backed NIO `ByteBuffer`s.  It can be enabled adding `-Dio.netty.tryReflectionSetAccessible=true --add-opens=java.base/java.nio=ALL-UNNAMED` to the JVM args. 
2. allocating "big enough" (>  1024 by default) `byte[]` without zeroing them, using the "hidden" feature explained at https://shipilev.net/jvm/anatomy-quarks/7-initialization-costs/#_experiment. It can be enabled via ` -Dio.netty.tryReflectionSetAccessible=true --add-opens=java.base/jdk.internal.misc=ALL-UNNAMED`

I'm **not** proposing to add both, but I think is important to be aware that these features are not available in the current default configuration.

The first problem (related the cleaner option) is pretty important, because:
- without configurations as it is now: it implies that the practical (direct) memory limits are the ones specified by Java by default, which means == the heap size (it means that a container should have **2*max Java heap size** available TOTAL memory: max java heap capacity + direct memory limits). Additionally, the JVM is responsible to expose via its metrics (yeeeee!) these direct allocations, and will take care of issuing `OutOfDirectMemory` (which is not "yay", the opposite: see https://github.com/openjdk/jdk/blob/jdk-21%2B35/src/java.base/share/classes/java/nio/Bits.java#L145-L178 how ugly can go!)
- with the proposed configuration: the direct memory limits are still (if nothing is configured, see https://github.com/netty/netty/blob/b0e43847a8c78325ea7dd8bb02934ed6c690cb9c/common/src/main/java/io/netty/util/internal/PlatformDependent.java#L151-L158) the same as the max Java heap **BUT** the JDK NIO direct `ByteBuffer`s allocations are tracked separately by OpenJDK, while the Netty direct allocations would use `Unsafe::allocateMemory`, instead, and its limit are enforced by Netty, instead. This means that the TOTAL memory required (in theory) to a container is: **3*max java heap**(!!!! ie heap + direct NIO memory limit + Netty direct memory limit). Additionally, there won't be any JVM metrics (maybe just native memory tracking AFAIK), which can report the total number of allocated direct memory (including the one from Netty, via Unsafe). Thanks to @alesj we can still use the Netty memory metrics, anyway, for this purpose.

So, why this second option could be appealing?
1. the allocated NIO `ByteBuffer`s won't contain any `Cleaner` saving some memory
2. the default heuristic for the platform, while going OOM, is not great (see https://github.com/openjdk/jdk/blob/jdk-21%2B35/src/java.base/share/classes/java/nio/Bits.java#L145-L178) and can cause an application to become unresponsive 

### Implementation ideas

Configured the proposed option by default

### LINKED ISSUE #51667: [Mandrel 25.0.x future-defaults=all, Graal master] All quarkus native integration tests fail since 2025-12-19
### Describe the bug

The last clean build (when all quarkus native integration tests passed) was from December 18, 2025 here:
https://github.com/graalvm/mandrel/actions/runs/20321891451

This is using revision `e98bc519e1abd959bd1ffc8cf84b94100eadda0d` from quarkus.

Since December 19, 2025 or quarkus revision `614cd6f798646765ab0e1791528c820df4798cf7` all quarkus native integration tests fail:
https://github.com/graalvm/mandrel/actions/runs/20355898577

It doesn't seem GraalVM master revision related as I ran the same local GraalVM master build when verifying #51538. Now with a newer quarkus version it fails.

**Steps to reproduce:**

1. Grab a graal-master build from the passing CI run [here](https://github.com/graalvm/mandrel/actions/runs/20321891451/artifacts/4906257520)
2. Build quarkus main, revision `614cd6f798646765ab0e1791528c820df4798cf7` or newer.
3. Run any native integration test (e.g. `smallrye-config`)
4. Observe that the native binary doesn't start.

### Expected behavior

Quarkus native integration tests pass.

### Actual behavior

Quarkus native integration tests fail.

### PR DESCRIPTION
**Pull request by Karm**
## Tested with
REST Hello World
* Java version: 21.0.9+10-LTS, vendor version: Mandrel-23.1.9.0-Final
* Java version: 25.0.1+8, vendor version: GraalVM CE 25.1.0-dev+8.1 (master some days ago)
* Java version: 25.0.1+8-LTS, vendor version: Mandrel-25.0.1.0-Final

## Perf
Almost useless, but at least a distant ballpark locally on Linux amd64, I don't see any difference with the `NativeImageConfigBuildItem build25Specific(` method commented out/not commented out. Yes, the correct build is used, because when I butchered the method, I got the `Unable to start HTTP...`.  

```
$  oha -z 30s -c 10 http://localhost:8080/hello
With patch:
  Success rate: 100.00%
  Total:    30000.2524 ms
  Slowest:  19.5058 ms
  Fastest:  0.0265 ms
  Average:  0.0952 ms
  Requests/sec: 103732.7273
Without patch:
  Success rate: 100.00%
  Total:    30000.7224 ms
  Slowest:  23.1098 ms
  Fastest:  0.0290 ms
  Average:  0.1097 ms
  Requests/sec: 90054.5982
```

I built the Hello World with and without `-Dquarkus.native.additional-build-args=--future-defaults=all,-ea`. 

I also removed a reflection registration for **pre** JDK 21 versions as no JDK 17 native-image is supported with the Quarkus main.

While this PR fixes the issue introduced by this change:

https://github.com/quarkusio/quarkus/blob/4f38bfb1c382d332536cd09a68d3d2efb1581ef1/extensions/netty/deployment/src/main/java/io/quarkus/netty/deployment/NettyOnJava24ProcessorExtension.java#L21-L29   done in f5382b9e678, specifically its open modules part, I still don't understand why we are letting Netty go down that code path in the first place.
Does this have any performance gains **in the context of native-image** ? I might be missing a point.... perhaps @franz1981  could set me right.

- Fixes: #51667
- Fixes: #39907
- Related to: #51773

### CODE REVIEW

File: extensions/netty/deployment/src/main/java/io/quarkus/netty/deployment/NettyOnJava24ProcessorExtension.java [hunk 1]
```diff
@@ -1,25 +0,0 @@
...
- * As Java 24 locks down access to sun.misc.Unsafe, Netty needs to adapt to this
- * to maintain its efficiency.
- * As this work progresses in upstream Netty to handle this better automatically,
- * we can already apply the following recommendations by the Netty team.
- * See also <a href="https://github.com/quarkusio/quarkus/issues/39907">#39907</a>
- * and <a href="https://netty.io/wiki/java-24-and-sun.misc.unsafe.html">Java 24 and sun.misc.unsafe</a>
- * </p>
- * Unfortunately, "--sun-misc-unsafe-memory-access=allow" should also be set,
- * but this can't be applied automatically as the Manifest format doesn't allow
- * setting such an option.
```
Comment (gsmet) [inline extensions/netty/deployment/src/main/java/io/quarkus/netty/deployment/NettyOnJava24ProcessorExtension.java:16]: @Sanne so are we good without a runner script given what's written here?

Comment (Karm) [reply extensions/netty/deployment/src/main/java/io/quarkus/netty/deployment/NettyOnJava24ProcessorExtension.java:16]: FWIW, the statement holds for HotSpot mode; I merely moved the JavaDoc over here: https://github.com/quarkusio/quarkus/pull/51807/files#diff-305a2796c8e31d213fe9b9b4d2162ee30f45471241fa06e8741acf15c324a4b6R91

**Comment by franz1981** [comment]
Reflective access allow Netty (assuming open modules to not prevent it to work) to optimize few relevant hot paths (see https://github.com/quarkusio/quarkus/issues/39907)

So @Karm if some recent changes removed that option, you should reconsider/rollback it or you will get a perf hit (which is what I suppose you measured too, matching what I have measured in the issue mentioned)

File: extensions/netty/deployment/src/main/java/io/quarkus/netty/deployment/NettyOnJava24ProcessorExtension.java (hunk 1 above)
Comment (Sanne) [reply extensions/netty/deployment/src/main/java/io/quarkus/netty/deployment/NettyOnJava24ProcessorExtension.java:16]: Yes we're good, having `--sun-misc-unsafe-memory-access=allow` is the default in the JVM, one needs to set it explicitly to avoid a warning but we were able to trick the JVM in not emitting such warning.

It will be fully resolved in future Netty versions.

File: extensions/netty/deployment/src/main/java/io/quarkus/netty/deployment/NettyProcessor.java [hunk 2]
```diff
@@ -79,6 +81,42 @@ public SystemPropertyBuildItem disableFinalizers() {
...
+     * <a href="https://openjdk.org/jeps/471">JEP 471</a> locks down access to sun.misc.Unsafe, Netty needs to adapt
+     * to this to maintain its efficiency. As this work progresses in upstream Netty to handle this better automatically, we can
+     * already apply the following recommendations by the Netty team. See also
+     * <a href="https://github.com/quarkusio/quarkus/issues/39907">#39907</a> and
+     * <a href="https://netty.io/wiki/java-24-and-sun.misc.unsafe.html">Java 24 and sun.misc.unsafe</a>.
+     * </p>
+     * Unfortunately, "--sun-misc-unsafe-memory-access=allow" should also be set for Java runtime, but it can't be applied
+     * automatically as the JAR Manifest format doesn't allow setting such an option.
+     */
+    @BuildStep(onlyIf = JavaVersionGreaterOrEqual25.class)
```
Comment (Sanne) [inline extensions/netty/deployment/src/main/java/io/quarkus/netty/deployment/NettyProcessor.java:94]: I'd generally prefer if we could avoid conditionals. Wouldn't these same rules be harmless when applied to an older version of the JVM?
Incidentally, I believe you'd need these rules on Java 23 and 24 as well.

File: extensions/netty/deployment/src/main/java/io/quarkus/netty/deployment/NettyProcessor.java [hunk 3]
```diff
@@ -79,6 +81,42 @@ public SystemPropertyBuildItem disableFinalizers() {
...
+                        new String[] { Class.class.getName(), int.class.getName() }));
+
+        reflectiveFields.produce(
+                new ReflectiveFieldBuildItem("Reflectively accessed through Netty's PlatformDependent0.",
+                        "java.nio.Bits", "UNSAFE_SET_THRESHOLD"));
+
+        // Enables Netty's PlatformDependent0 and PlatformDependent to access java.nio, e.g. java.nio.Bits
+        // It's potentially problematic regarding build-time and run-time inited JDK parts.
+        moduleOpenBuildItem.produce(
+                new ModuleOpenBuildItem("java.base", "io.netty.common", "java.nio", "jdk.internal.misc"));
```
Comment (Sanne) [inline extensions/netty/deployment/src/main/java/io/quarkus/netty/deployment/NettyProcessor.java:112]: wouldn't it have been simpler to leave these within their own method, like I had them in NettyOnJava24ProcessorExtension ?

File: extensions/netty/deployment/src/main/java/io/quarkus/netty/deployment/NettyProcessor.java [hunk 4]
```diff
@@ -79,6 +81,42 @@ public SystemPropertyBuildItem disableFinalizers() {
...
+
+        final NativeImageConfigBuildItem.Builder builder = NativeImageConfigBuildItem.builder()
+                .addNativeImageSystemProperty("io.netty.tryReflectionSetAccessible", "true")
```
Comment (Sanne) [inline extensions/netty/deployment/src/main/java/io/quarkus/netty/deployment/NettyProcessor.java:115]: I'm a bit confused, this is what I had previously but I thought you wanted me to remove it?
Again, I'd extract them in independent methods - without the conditional so to consistently and always set such properties.

File: extensions/netty/deployment/src/main/java/io/quarkus/netty/deployment/NettyOnJava24ProcessorExtension.java (hunk 1 above)
Comment (Sanne) [reply extensions/netty/deployment/src/main/java/io/quarkus/netty/deployment/NettyOnJava24ProcessorExtension.java:16]: P.S. the JVM plans to change such detault in the future, so by then we'll definitely need to have EITHER:

- a more recent Netty
- a runner script which flips the property to allow

File: extensions/netty/deployment/src/main/java/io/quarkus/netty/deployment/NettyProcessor.java (hunk 2 above)
Comment (Karm) [reply extensions/netty/deployment/src/main/java/io/quarkus/netty/deployment/NettyProcessor.java:94]: Hello @Sanne 

>  I believe you'd need them on Java 23 and 24 as well.

Java 23 and 24 are dead\*, nobody should be using those anywhere, so the Quarkus code related to native image is concerned only with JDK 21 and JDK 25 compatibility. Our only contemporary builder images are JDK 21 and JDK 25 based.

> these same rules be harmless

I don't think they are harmless as they create convolution and confusion in the already packed JSON configuration Quarkus generates and  the native-image compiler consumes. Having to figure out which change is superfluous, which change has side effects and what is harmless is laborious. I was browsing the Netty and JDK code and couldn't even find a method Quarkus mentioned only to realize it was pre-JDK21... So one simple conditional on the Quarkus extension side saves pain later when a JDK 21 issue pops up.
We are already using conditionals in AWT extension. We have been adding **and removing** as needed, e.g. all `if JDK 17` conditionals are gone, all but JDK 25/JDK 21 related are purged etc. 

\* more "dead" than JDK 8 or 11, as both JDK 8 and JDK 11 keep receiving updates...


I am writing this with my native-image hat on and with my AWT extension experience on mind. Others might feel differently.

File: extensions/netty/deployment/src/main/java/io/quarkus/netty/deployment/NettyProcessor.java (hunk 3 above)
Comment (Karm) [reply extensions/netty/deployment/src/main/java/io/quarkus/netty/deployment/NettyProcessor.java:112]: @Sanne I copied the style of the `build` method that's just below, created a similar one and added the `onlyIf` condition. I have no opinion on the organization of these methods, I am merely concerned with the resulting JSON.

Would you like these to be all separate build items?

File: extensions/netty/deployment/src/main/java/io/quarkus/netty/deployment/NettyProcessor.java (hunk 2 above)
Comment (gsmet) [reply extensions/netty/deployment/src/main/java/io/quarkus/netty/deployment/NettyProcessor.java:94]: I can confirm we don't care about 23 and 24 from a native image perspective so if it's native image only, we can condition it.

File: extensions/netty/deployment/src/main/java/io/quarkus/netty/deployment/NettyProcessor.java (hunk 4 above)
Comment (Karm) [reply extensions/netty/deployment/src/main/java/io/quarkus/netty/deployment/NettyProcessor.java:115]: >  but I thought you wanted me to remove it?

@Sanne 
You are referring to this comment:  https://github.com/quarkusio/quarkus/issues/51667#issuecomment-3691912276

The real culprit was the opening of the modules, not setting the property. Without opening the modules, Netty gracefully bailed out of the Unsafe on its own.

So I brought your original code back, opened the modules, set the `tryReflectionSetAccessible` to `true` and added the necessary config to walk [PlatformDependent0](https://github.com/netty/netty/blob/41ff1eb45a4acc9976150330e105211ecde36399/common/src/main/java/io/netty/util/internal/PlatformDependent0.java#L487) without crash.

So this PR enables Quarkus to initialize Netty with modules open, to go deeper into PlatformDependent0 init.
Looking at it, I don't think we are taking full advantage of it yet, but I'd like to leave that for another PR. Netty gracefully bails out of things it cannot access/find.

**Comment by Karm** [comment]
> Reflective access allow Netty (assuming open modules to not prevent it to work) to optimize few relevant hot paths (see #39907)
> 
> So @Karm if some recent changes removed that option, you should reconsider/rollback it or you will get a perf hit (which is what I suppose you measured too, matching what I have measured in the issue mentioned)

@franz1981 We are not fully there I think, but the door is open now. I'll check the trace if anything is missing. We might hit a wall though in places where GraalVM substitutes some java.nio classes  in a way Netty doesn't expect.  One would have to substitute more of Netty then :-D

File: extensions/netty/deployment/src/main/java/io/quarkus/netty/deployment/NettyProcessor.java (hunk 2 above)
Comment (Sanne) [reply extensions/netty/deployment/src/main/java/io/quarkus/netty/deployment/NettyProcessor.java:94]: My question wasn't about Java 23 and 24, but more about the *need* for the conditional altogether. Fine let's keep it :)

Comment (Sanne) [reply extensions/netty/deployment/src/main/java/io/quarkus/netty/deployment/NettyProcessor.java:94]: FWIW just a reminder that we'll likely want to deprecate the conditionals eventually.

File: extensions/netty/deployment/src/main/java/io/quarkus/netty/deployment/NettyProcessor.java (hunk 3 above)
Comment (Sanne) [reply extensions/netty/deployment/src/main/java/io/quarkus/netty/deployment/NettyProcessor.java:112]: I would generally separate the production of build items as much as possible yes, that keeps the build-item-producing methods from creating a complex network. And avoid the conditionals please, opening the modules should be the same on all versions.

File: extensions/netty/deployment/src/main/java/io/quarkus/netty/deployment/NettyProcessor.java (hunk 2 above)
Comment (gsmet) [reply extensions/netty/deployment/src/main/java/io/quarkus/netty/deployment/NettyProcessor.java:94]: > FWIW just a reminder that we'll likely want to deprecate the conditionals eventually.

The Mandrel team has been exceptionnaly good at that, a lot better than the rest of us :)

File: extensions/netty/deployment/src/main/java/io/quarkus/netty/deployment/NettyProcessor.java (hunk 3 above)
Comment (Karm) [reply extensions/netty/deployment/src/main/java/io/quarkus/netty/deployment/NettyProcessor.java:112]: > I would generally separate the production of build items as much as possible yes

O.K., will refactor the processor class.

File: extensions/netty/deployment/src/main/java/io/quarkus/netty/deployment/NettyProcessor.java (hunk 2 above)
Comment (dmlloyd) [reply extensions/netty/deployment/src/main/java/io/quarkus/netty/deployment/NettyProcessor.java:94]: Is the conditional even needed here? Would it cause a failure to produce these items on Java 17?

Comment (Karm) [reply extensions/netty/deployment/src/main/java/io/quarkus/netty/deployment/NettyProcessor.java:94]: @dmlloyd There is no native-image builder based on Java 17 in operation these days. It seems there are two fronts: One is trying to remove complexity from the Java code of Quarkus extension and the other is trying to remove complexity from debugging native-image build and runtime. I am advocating the latter. Furthermore, none of this is user facing.

**Review by gsmet — APPROVED** [review]
I understand we all have opinions and different coding practices but I would be in favor of merging this if nothing is really blocking, as it's blocking other PRs to move to Java 25. We can still iterate later if needed.

@Sanne I let you push the Merge button if you're reasonably happy about it.

**Comment by Karm** [comment]
@Sanne I ain't going anywhere, I have a test branch for opening modules on 21 and trying to trace how far the Unsafe init went before it bailed out in 25. If this is merged, I open a follow up...  I don't have a ready tested update to this PR right now at the moment though.

**Comment by gsmet** [comment]
After discussion with @sanne and @karm, I will merge this and we will iterate in subsequent pull requests. This work should allow us to switch the default Mandrel builder to 25 in my PR.
