### PR TITLE
Preserve the type of multi in the SecurityHandler

### LINKED ISSUE #21044: Reactive routes incorrect json serialization
### Describe the bug

Reactive routes resources returning invalid json when using `@RolesAllowed` annotation. Without the annotation its working fine.

Its working fine using Quarkus 2.3 version

### Expected behavior

API should return below JSON response

```javascript
[
	{
		"message": "Hello!"
	},
	{
		"message": "Hola!"
	},
	{
		"message": "Bonjour!"
	},
	{
		"message": "Ciao!"
	}
]
```

### Actual behavior

Instead its returning

```javascript
{"message":"Hello!"}{"message":"Hola!"}{"message":"Bonjour!"}{"message":"Ciao!"}
```

### How to Reproduce?

Reproducer: https://github.com/MM87037/reactive-routes

Steps:

1. Run `mvn clean verify` to see the failure

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

OpenJDK Runtime Environment Temurin-17+35 (build 17+35)
OpenJDK 64-Bit Server VM Temurin-17+35 (build 17+35, mixed mode, sharing)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.4.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by cescoffier**
Avoid using `transformToMulti` as we want to preserve the type of multi produced by the user method. This is required for Reactive Routes to handle custom Multi serialization.

Fix https://github.com/quarkusio/quarkus/issues/21044.

### CODE REVIEW

**Comment by geoand** [comment]
Oh, very nice! I didn't know about this capability

File: extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityHandler.java [hunk 1]
```diff
@@ -41,7 +41,9 @@ public Object handle(InvocationContext ic) throws Exception {
                     }).subscribeAsCompletionStage();
         } else if (Multi.class.isAssignableFrom(returnType)) {
             return constrainer.nonBlockingCheck(ic.getMethod(), ic.getParameters())
-                    .onItem().transformToMulti(new MultiContinuation(ic));
+                    // Do not use transformToMulti as we want to preserve the type of multi produced by the user method.
+                    // This is required for Reactive Routes to handle custom Multi serialization.
+                    .toMulti().plug(x -> new MultiContinuation(ic).apply(x));
```
Comment (michalszynkiewicz) [inline extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityHandler.java:46]: what's the actual difference?

**Review by mkouba — APPROVED** [review]
`Uni.toMulti().plug()` looks a bit like some dark magic but if it does what I think it does then +1 :D

File: extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityHandler.java (hunk 1 above)
Comment (mkouba) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityHandler.java:46]: IIUIC you don't wrap the `Multi` produced by the user method but instead call `new MultiContinuation(ic).apply(x)` when the `Multi` instance is created.

**Comment by michalszynkiewicz** [comment]
would be great to have a test that it actually fixes the linked issue :)

**Review by michalszynkiewicz — APPROVED** [review]

**Comment by cescoffier** [comment]
plug is not the most common API. It's used to create your own operator. Here, it's just convenient as we will return the multi we create directly.

**Comment by MM87037** [comment]
Is it possible to backport this fix to 2.4?

**Comment by geoand** [comment]
It has already been marked for backporting (see the labels)

**Comment by michalszynkiewicz** [comment]
@MM87037 could you create a separete issue and create a reproducer?

**Comment by MM87037** [comment]
Sure. Thanks
