### PR TITLE
RESTEasy client - use our provider factory when accessed statically

### LINKED ISSUE #27277: RESTEASY002120: ClassNotFoundException: Unable to load builtin provider in Quarkus Native 2.11.2.Final
### Describe the bug

After upgrading Quarkus from 2.10.3.Final to 2.11.2.Final one of our ETL modules logs this warnings:

```log
 __  ____  __  _____   ___  __ ____  ______ 
 __  ____  __  _____   ___  __ ____  ______ 
  --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
  -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
 --\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
 2022-08-14 11:09:47,878 WARN  [io.qua.run.con.ConfigRecorder] (main) Build time property cannot be changed at runtime:
  - quarkus.quartz.cluster-checkin-interval is set to '2000' but it is build time fixed to '15000'. Did you change the property quarkus.quartz.cluster-checkin-interval after building the application?
 2022-08-14 11:09:47,913 INFO  [liq.database] (main) Set default schema name to public
 2022-08-14 11:09:48,004 INFO  [liq.changelog] (main) Reading from public.databasechangelog
 2022-08-14 11:09:48,024 INFO  [liq.lockservice] (main) Successfully acquired change log lock
 2022-08-14 11:09:48,056 INFO  [liq.lockservice] (main) Successfully released change log lock
 2022-08-14 11:09:48,151 INFO  [io.quarkus] (main) etl-horoscope 2.5.0-SNAPSHOT native (powered by Quarkus 2.11.2.Final) started in 0.310s. Listening on: http://0.0.0.0:8080
 2022-08-14 11:09:48,151 INFO  [io.quarkus] (main) Profile localk8s activated. 
 2022-08-14 11:09:48,151 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, config-yaml, hibernate-orm, hibernate-orm-panache-kotlin, jdbc-postgresql, kotlin, liquibase, micrometer, narayana-jta, quartz, rest-client, rest-client-jsonb, scheduler, smallrye-context-propagation, smallrye-health, vertex]

<cut>

 2022-08-14 11:16:00,951 WARN  [org.jbo.res.res.i18n] (LoadHoroscope_Worker-1) RESTEASY002120: ClassNotFoundException: Unable to load builtin provider org.jboss.resteasy.plugins.providers.IIOImageProvider from resource:/META-INF/services/javax.ws.rs.ext.Providers: java.lang.ClassNotFoundException: org.jboss.resteasy.plugins.providers.IIOImageProvider
  at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:52)
  at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:133)
  at org.jboss.resteasy.plugins.providers.RegisterBuiltin.registerProviders(RegisterBuiltin.java:95)
  at org.jboss.resteasy.plugins.providers.RegisterBuiltin.register(RegisterBuiltin.java:74)
  at org.jboss.resteasy.core.providerfactory.ResteasyProviderFactoryImpl.registerBuiltin(ResteasyProviderFactoryImpl.java:188)
  at org.jboss.resteasy.spi.ResteasyProviderFactory.getInstance(ResteasyProviderFactory.java:127)
  at org.jboss.resteasy.spi.ResteasyDeployment.onServer(ResteasyDeployment.java:19)
  at org.jboss.resteasy.microprofile.client.DefaultResponseExceptionMapper.handles(DefaultResponseExceptionMapper.java:28)
  at org.jboss.resteasy.microprofile.client.ExceptionMapping.filter(ExceptionMapping.java:71)
  at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.filterResponse(ClientInvocation.java:799)
  at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:495)
  at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:152)
  at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:115)
  at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
  at jdk.proxy4.$Proxy109.getWeeklyHoroscope(Unknown Source)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:146)
  at jdk.proxy4.$Proxy110.getWeeklyHoroscope(Unknown Source)
  at hidden.WeeklyHoroscopeLoader.load(WeeklyHoroscopeLoader.kt:40)
  at hidden.WeeklyHoroscopeLoader_Subclass.load$$superforward1(Unknown Source)
  at hidden.WeeklyHoroscopeLoader_Subclass$$function$$1.apply(Unknown Source)
  at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:53)
  at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:133)
  at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:104)
  at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
  at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:58)
  at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
  at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
  at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
  at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:40)
  at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
  at hidden.WeeklyHoroscopeLoader_Subclass.load(Unknown Source)
  at hidden.WeeklyHoroscopeLoader_ClientProxy.load(Unknown Source)
  at hidden.WeeklyHoroscopeLoader_ScheduledInvoker_load_6b738a5c78d7e250ef51b965844a7d66fb79bcb6.invokeBean(Unknown Source)
  at io.quarkus.scheduler.common.runtime.DefaultInvoker.invoke(DefaultInvoker.java:19)
  at io.quarkus.scheduler.common.runtime.StatusEmitterInvoker.invoke(StatusEmitterInvoker.java:35)
  at io.quarkus.scheduler.common.runtime.SkipConcurrentExecutionInvoker.invoke(SkipConcurrentExecutionInvoker.java:37)
  at io.quarkus.quartz.runtime.QuartzScheduler$InvokerJob.execute(QuartzScheduler.java:582)
  at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
  at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
  at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:705)
  at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)
 
 2022-08-14 11:16:00,951 WARN  [org.jbo.res.res.i18n] (LoadHoroscope_Worker-1) RESTEASY002120: ClassNotFoundException: Unable to load builtin provider org.jboss.resteasy.plugins.providers.sse.SseEventProvider from resource:/META-INF/services/javax.ws.rs.ext.Providers: java.lang.ClassNotFoundException: org.jboss.resteasy.plugins.providers.sse.SseEventProvider
  at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:52)
  at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:133)
  at org.jboss.resteasy.plugins.providers.RegisterBuiltin.registerProviders(RegisterBuiltin.java:95)
  at org.jboss.resteasy.plugins.providers.RegisterBuiltin.register(RegisterBuiltin.java:74)
  at org.jboss.resteasy.core.providerfactory.ResteasyProviderFactoryImpl.registerBuiltin(ResteasyProviderFactoryImpl.java:188)
  at org.jboss.resteasy.spi.ResteasyProviderFactory.getInstance(ResteasyProviderFactory.java:127)
  at org.jboss.resteasy.spi.ResteasyDeployment.onServer(ResteasyDeployment.java:19)
  at org.jboss.resteasy.microprofile.client.DefaultResponseExceptionMapper.handles(DefaultResponseExceptionMapper.java:28)
  at org.jboss.resteasy.microprofile.client.ExceptionMapping.filter(ExceptionMapping.java:71)
  at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.filterResponse(ClientInvocation.java:799)
  at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:495)
  at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:152)
  at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:115)
  at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
  at jdk.proxy4.$Proxy109.getWeeklyHoroscope(Unknown Source)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:146)
  at jdk.proxy4.$Proxy110.getWeeklyHoroscope(Unknown Source)
  at hidden.WeeklyHoroscopeLoader.load(WeeklyHoroscopeLoader.kt:40)
  at hidden.WeeklyHoroscopeLoader_Subclass.load$$superforward1(Unknown Source)
  at hidden.WeeklyHoroscopeLoader_Subclass$$function$$1.apply(Unknown Source)
  at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:53)
  at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:133)
  at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:104)
  at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
  at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:58)
  at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
  at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
  at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
  at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:40)
  at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
  at hidden.WeeklyHoroscopeLoader_Subclass.load(Unknown Source)
  at hidden.WeeklyHoroscopeLoader_ClientProxy.load(Unknown Source)
  at hidden.WeeklyHoroscopeLoader_ScheduledInvoker_load_6b738a5c78d7e250ef51b965844a7d66fb79bcb6.invokeBean(Unknown Source)
  at io.quarkus.scheduler.common.runtime.DefaultInvoker.invoke(DefaultInvoker.java:19)
  at io.quarkus.scheduler.common.runtime.StatusEmitterInvoker.invoke(StatusEmitterInvoker.java:35)
  at io.quarkus.scheduler.common.runtime.SkipConcurrentExecutionInvoker.invoke(SkipConcurrentExecutionInvoker.java:37)
  at io.quarkus.quartz.runtime.QuartzScheduler$InvokerJob.execute(QuartzScheduler.java:582)
  at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
  at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
  at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:705)
  at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)
 
 2022-08-14 11:16:00,951 WARN  [org.jbo.res.res.i18n] (LoadHoroscope_Worker-1) RESTEASY002120: ClassNotFoundException: Unable to load builtin provider org.jboss.resteasy.plugins.providers.DefaultTextPlain from resource:/META-INF/services/javax.ws.rs.ext.Providers: java.lang.ClassNotFoundException: org.jboss.resteasy.plugins.providers.DefaultTextPlain
  at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:52)
  at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:133)
  at org.jboss.resteasy.plugins.providers.RegisterBuiltin.registerProviders(RegisterBuiltin.java:95)
  at org.jboss.resteasy.plugins.providers.RegisterBuiltin.register(RegisterBuiltin.java:74)
  at org.jboss.resteasy.core.providerfactory.ResteasyProviderFactoryImpl.registerBuiltin(ResteasyProviderFactoryImpl.java:188)
  at org.jboss.resteasy.spi.ResteasyProviderFactory.getInstance(ResteasyProviderFactory.java:127)
  at org.jboss.resteasy.spi.ResteasyDeployment.onServer(ResteasyDeployment.java:19)
  at org.jboss.resteasy.microprofile.client.DefaultResponseExceptionMapper.handles(DefaultResponseExceptionMapper.java:28)
  at org.jboss.resteasy.microprofile.client.ExceptionMapping.filter(ExceptionMapping.java:71)
  at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.filterResponse(ClientInvocation.java:799)
  at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:495)
  at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:152)
  at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:115)
  at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
  at jdk.proxy4.$Proxy109.getWeeklyHoroscope(Unknown Source)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:146)
  at jdk.proxy4.$Proxy110.getWeeklyHoroscope(Unknown Source)
  at hidden.WeeklyHoroscopeLoader.load(WeeklyHoroscopeLoader.kt:40)
  at hidden.WeeklyHoroscopeLoader_Subclass.load$$superforward1(Unknown Source)
  at hidden.WeeklyHoroscopeLoader_Subclass$$function$$1.apply(Unknown Source)
  at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:53)
  at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:133)
  at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:104)
  at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
  at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:58)
  at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
  at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
  at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
  at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:40)
  at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
  at hidden.WeeklyHoroscopeLoader_Subclass.load(Unknown Source)
  at hidden.WeeklyHoroscopeLoader_ClientProxy.load(Unknown Source)
  at hidden.WeeklyHoroscopeLoader_ScheduledInvoker_load_6b738a5c78d7e250ef51b965844a7d66fb79bcb6.invokeBean(Unknown Source)
  at io.quarkus.scheduler.common.runtime.DefaultInvoker.invoke(DefaultInvoker.java:19)
  at io.quarkus.scheduler.common.runtime.StatusEmitterInvoker.invoke(StatusEmitterInvoker.java:35)
  at io.quarkus.scheduler.common.runtime.SkipConcurrentExecutionInvoker.invoke(SkipConcurrentExecutionInvoker.java:37)
  at io.quarkus.quartz.runtime.QuartzScheduler$InvokerJob.execute(QuartzScheduler.java:582)
  at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
  at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
  at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:705)
  at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)
 
 2022-08-14 11:16:00,952 WARN  [org.jbo.res.res.i18n] (LoadHoroscope_Worker-1) RESTEASY002120: ClassNotFoundException: Unable to load builtin provider org.jboss.resteasy.plugins.providers.FormUrlEncodedProvider from resource:/META-INF/services/javax.ws.rs.ext.Providers: java.lang.ClassNotFoundException: org.jboss.resteasy.plugins.providers.FormUrlEncodedProvider
  at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:52)
  at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:133)
  at org.jboss.resteasy.plugins.providers.RegisterBuiltin.registerProviders(RegisterBuiltin.java:95)
  at org.jboss.resteasy.plugins.providers.RegisterBuiltin.register(RegisterBuiltin.java:74)
  at org.jboss.resteasy.core.providerfactory.ResteasyProviderFactoryImpl.registerBuiltin(ResteasyProviderFactoryImpl.java:188)
  at org.jboss.resteasy.spi.ResteasyProviderFactory.getInstance(ResteasyProviderFactory.java:127)
  at org.jboss.resteasy.spi.ResteasyDeployment.onServer(ResteasyDeployment.java:19)
  at org.jboss.resteasy.microprofile.client.DefaultResponseExceptionMapper.handles(DefaultResponseExceptionMapper.java:28)
  at org.jboss.resteasy.microprofile.client.ExceptionMapping.filter(ExceptionMapping.java:71)
  at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.filterResponse(ClientInvocation.java:799)
  at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:495)
  at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:152)
  at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:115)
  at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
  at jdk.proxy4.$Proxy109.getWeeklyHoroscope(Unknown Source)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:146)
  at jdk.proxy4.$Proxy110.getWeeklyHoroscope(Unknown Source)
  at hidden.WeeklyHoroscopeLoader.load(WeeklyHoroscopeLoader.kt:40)
  at hidden.WeeklyHoroscopeLoader_Subclass.load$$superforward1(Unknown Source)
  at hidden.WeeklyHoroscopeLoader_Subclass$$function$$1.apply(Unknown Source)
  at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:53)
  at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:133)
  at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:104)
  at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
  at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:58)
  at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
  at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
  at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
  at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:40)
  at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
  at hidden.WeeklyHoroscopeLoader_Subclass.load(Unknown Source)
  at hidden.WeeklyHoroscopeLoader_ClientProxy.load(Unknown Source)
  at hidden.WeeklyHoroscopeLoader_ScheduledInvoker_load_6b738a5c78d7e250ef51b965844a7d66fb79bcb6.invokeBean(Unknown Source)
  at io.quarkus.scheduler.common.runtime.DefaultInvoker.invoke(DefaultInvoker.java:19)
  at io.quarkus.scheduler.common.runtime.StatusEmitterInvoker.invoke(StatusEmitterInvoker.java:35)
  at io.quarkus.scheduler.common.runtime.SkipConcurrentExecutionInvoker.invoke(SkipConcurrentExecutionInvoker.java:37)
  at io.quarkus.quartz.runtime.QuartzScheduler$InvokerJob.execute(QuartzScheduler.java:582)
  at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
  at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
  at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:705)
  at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)
 
 2022-08-14 11:16:00,952 WARN  [org.jbo.res.res.i18n] (LoadHoroscope_Worker-1) RESTEASY002120: ClassNotFoundException: Unable to load builtin provider org.jboss.resteasy.plugins.providers.DefaultNumberWriter from resource:/META-INF/services/javax.ws.rs.ext.Providers: java.lang.ClassNotFoundException: org.jboss.resteasy.plugins.providers.DefaultNumberWriter
  at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:52)
  at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:133)
  at org.jboss.resteasy.plugins.providers.RegisterBuiltin.registerProviders(RegisterBuiltin.java:95)
  at org.jboss.resteasy.plugins.providers.RegisterBuiltin.register(RegisterBuiltin.java:74)
  at org.jboss.resteasy.core.providerfactory.ResteasyProviderFactoryImpl.registerBuiltin(ResteasyProviderFactoryImpl.java:188)
  at org.jboss.resteasy.spi.ResteasyProviderFactory.getInstance(ResteasyProviderFactory.java:127)
  at org.jboss.resteasy.spi.ResteasyDeployment.onServer(ResteasyDeployment.java:19)
  at org.jboss.resteasy.microprofile.client.DefaultResponseExceptionMapper.handles(DefaultResponseExceptionMapper.java:28)
  at org.jboss.resteasy.microprofile.client.ExceptionMapping.filter(ExceptionMapping.java:71)
  at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.filterResponse(ClientInvocation.java:799)
  at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:495)
  at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:152)
  at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:115)
  at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
  at jdk.proxy4.$Proxy109.getWeeklyHoroscope(Unknown Source)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:146)
  at jdk.proxy4.$Proxy110.getWeeklyHoroscope(Unknown Source)
  at hidden.WeeklyHoroscopeLoader.load(WeeklyHoroscopeLoader.kt:40)
  at hidden.WeeklyHoroscopeLoader_Subclass.load$$superforward1(Unknown Source)
  at hidden.WeeklyHoroscopeLoader_Subclass$$function$$1.apply(Unknown Source)
  at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:53)
  at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:133)
  at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:104)
  at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
  at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:58)
  at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
  at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
  at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
  at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:40)
  at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
  at hidden.WeeklyHoroscopeLoader_Subclass.load(Unknown Source)
  at hidden.WeeklyHoroscopeLoader_ClientProxy.load(Unknown Source)
  at hidden.WeeklyHoroscopeLoader_ScheduledInvoker_load_6b738a5c78d7e250ef51b965844a7d66fb79bcb6.invokeBean(Unknown Source)
  at io.quarkus.scheduler.common.runtime.DefaultInvoker.invoke(DefaultInvoker.java:19)
  at io.quarkus.scheduler.common.runtime.StatusEmitterInvoker.invoke(StatusEmitterInvoker.java:35)
  at io.quarkus.scheduler.common.runtime.SkipConcurrentExecutionInvoker.invoke(SkipConcurrentExecutionInvoker.java:37)
  at io.quarkus.quartz.runtime.QuartzScheduler$InvokerJob.execute(QuartzScheduler.java:582)
  at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
  at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
  at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:705)
  at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)
 
 2022-08-14 11:16:00,952 WARN  [org.jbo.res.res.i18n] (LoadHoroscope_Worker-1) RESTEASY002120: ClassNotFoundException: Unable to load builtin provider org.jboss.resteasy.plugins.providers.SourceProvider from resource:/META-INF/services/javax.ws.rs.ext.Providers: java.lang.ClassNotFoundException: org.jboss.resteasy.plugins.providers.SourceProvider
  at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:52)
  at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:133)
  at org.jboss.resteasy.plugins.providers.RegisterBuiltin.registerProviders(RegisterBuiltin.java:95)
  at org.jboss.resteasy.plugins.providers.RegisterBuiltin.register(RegisterBuiltin.java:74)
  at org.jboss.resteasy.core.providerfactory.ResteasyProviderFactoryImpl.registerBuiltin(ResteasyProviderFactoryImpl.java:188)
  at org.jboss.resteasy.spi.ResteasyProviderFactory.getInstance(ResteasyProviderFactory.java:127)
  at org.jboss.resteasy.spi.ResteasyDeployment.onServer(ResteasyDeployment.java:19)
  at org.jboss.resteasy.microprofile.client.DefaultResponseExceptionMapper.handles(DefaultResponseExceptionMapper.java:28)
  at org.jboss.resteasy.microprofile.client.ExceptionMapping.filter(ExceptionMapping.java:71)
  at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.filterResponse(ClientInvocation.java:799)
  at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:495)
  at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:152)
  at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:115)
  at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
  at jdk.proxy4.$Proxy109.getWeeklyHoroscope(Unknown Source)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:146)
  at jdk.proxy4.$Proxy110.getWeeklyHoroscope(Unknown Source)
  at hidden.WeeklyHoroscopeLoader.load(WeeklyHoroscopeLoader.kt:40)
  at hidden.WeeklyHoroscopeLoader_Subclass.load$$superforward1(Unknown Source)
  at hidden.WeeklyHoroscopeLoader_Subclass$$function$$1.apply(Unknown Source)
  at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:53)
  at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:133)
  at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:104)
  at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
  at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:58)
  at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
  at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
  at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
  at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:40)
  at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
  at hidden.WeeklyHoroscopeLoader_Subclass.load(Unknown Source)
  at hidden.WeeklyHoroscopeLoader_ClientProxy.load(Unknown Source)
  at hidden.WeeklyHoroscopeLoader_ScheduledInvoker_load_6b738a5c78d7e250ef51b965844a7d66fb79bcb6.invokeBean(Unknown Source)
  at io.quarkus.scheduler.common.runtime.DefaultInvoker.invoke(DefaultInvoker.java:19)
  at io.quarkus.scheduler.common.runtime.StatusEmitterInvoker.invoke(StatusEmitterInvoker.java:35)
  at io.quarkus.scheduler.common.runtime.SkipConcurrentExecutionInvoker.invoke(SkipConcurrentExecutionInvoker.java:37)
  at io.quarkus.quartz.runtime.QuartzScheduler$InvokerJob.execute(QuartzScheduler.java:582)
  at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
  at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
  at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:705)
  at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)
 
 2022-08-14 11:16:00,953 WARN  [org.jbo.res.res.i18n] (LoadHoroscope_Worker-1) RESTEASY002120: ClassNotFoundException: Unable to load builtin provider org.jboss.resteasy.plugins.providers.DocumentProvider from resource:/META-INF/services/javax.ws.rs.ext.Providers: java.lang.ClassNotFoundException: org.jboss.resteasy.plugins.providers.DocumentProvider
  at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:52)
  at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:133)
  at org.jboss.resteasy.plugins.providers.RegisterBuiltin.registerProviders(RegisterBuiltin.java:95)
  at org.jboss.resteasy.plugins.providers.RegisterBuiltin.register(RegisterBuiltin.java:74)
  at org.jboss.resteasy.core.providerfactory.ResteasyProviderFactoryImpl.registerBuiltin(ResteasyProviderFactoryImpl.java:188)
  at org.jboss.resteasy.spi.ResteasyProviderFactory.getInstance(ResteasyProviderFactory.java:127)
  at org.jboss.resteasy.spi.ResteasyDeployment.onServer(ResteasyDeployment.java:19)
  at org.jboss.resteasy.microprofile.client.DefaultResponseExceptionMapper.handles(DefaultResponseExceptionMapper.java:28)
  at org.jboss.resteasy.microprofile.client.ExceptionMapping.filter(ExceptionMapping.java:71)
  at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.filterResponse(ClientInvocation.java:799)
  at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:495)
  at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:152)
  at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:115)
  at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
  at jdk.proxy4.$Proxy109.getWeeklyHoroscope(Unknown Source)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:146)
  at jdk.proxy4.$Proxy110.getWeeklyHoroscope(Unknown Source)
  at hidden.WeeklyHoroscopeLoader.load(WeeklyHoroscopeLoader.kt:40)
  at hidden.WeeklyHoroscopeLoader_Subclass.load$$superforward1(Unknown Source)
  at hidden.WeeklyHoroscopeLoader_Subclass$$function$$1.apply(Unknown Source)
  at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:53)
  at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:133)
  at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:104)
  at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
  at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:58)
  at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
  at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
  at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
  at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:40)
  at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
  at hidden.WeeklyHoroscopeLoader_Subclass.load(Unknown Source)
  at hidden.WeeklyHoroscopeLoader_ClientProxy.load(Unknown Source)
  at hidden.WeeklyHoroscopeLoader_ScheduledInvoker_load_6b738a5c78d7e250ef51b965844a7d66fb79bcb6.invokeBean(Unknown Source)
  at io.quarkus.scheduler.common.runtime.DefaultInvoker.invoke(DefaultInvoker.java:19)
  at io.quarkus.scheduler.common.runtime.StatusEmitterInvoker.invoke(StatusEmitterInvoker.java:35)
  at io.quarkus.scheduler.common.runtime.SkipConcurrentExecutionInvoker.invoke(SkipConcurrentExecutionInvoker.java:37)
  at io.quarkus.quartz.runtime.QuartzScheduler$InvokerJob.execute(QuartzScheduler.java:582)
  at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
  at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
  at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:705)
  at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)
 
 2022-08-14 11:16:00,953 WARN  [org.jbo.res.res.i18n] (LoadHoroscope_Worker-1) RESTEASY002120: ClassNotFoundException: Unable to load builtin provider org.jboss.resteasy.plugins.providers.DefaultBooleanWriter from resource:/META-INF/services/javax.ws.rs.ext.Providers: java.lang.ClassNotFoundException: org.jboss.resteasy.plugins.providers.DefaultBooleanWriter
  at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:52)
  at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:133)
  at org.jboss.resteasy.plugins.providers.RegisterBuiltin.registerProviders(RegisterBuiltin.java:95)
  at org.jboss.resteasy.plugins.providers.RegisterBuiltin.register(RegisterBuiltin.java:74)
  at org.jboss.resteasy.core.providerfactory.ResteasyProviderFactoryImpl.registerBuiltin(ResteasyProviderFactoryImpl.java:188)
  at org.jboss.resteasy.spi.ResteasyProviderFactory.getInstance(ResteasyProviderFactory.java:127)
  at org.jboss.resteasy.spi.ResteasyDeployment.onServer(ResteasyDeployment.java:19)
  at org.jboss.resteasy.microprofile.client.DefaultResponseExceptionMapper.handles(DefaultResponseExceptionMapper.java:28)
  at org.jboss.resteasy.microprofile.client.ExceptionMapping.filter(ExceptionMapping.java:71)
  at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.filterResponse(ClientInvocation.java:799)
  at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:495)
  at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:152)
  at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:115)
  at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
  at jdk.proxy4.$Proxy109.getWeeklyHoroscope(Unknown Source)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:146)
  at jdk.proxy4.$Proxy110.getWeeklyHoroscope(Unknown Source)
  at hidden.WeeklyHoroscopeLoader.load(WeeklyHoroscopeLoader.kt:40)
  at hidden.WeeklyHoroscopeLoader_Subclass.load$$superforward1(Unknown Source)
  at hidden.WeeklyHoroscopeLoader_Subclass$$function$$1.apply(Unknown Source)
  at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:53)
  at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:133)
  at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:104)
  at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
  at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:58)
  at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
  at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
  at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
  at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:40)
  at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
  at hidden.WeeklyHoroscopeLoader_Subclass.load(Unknown Source)
  at hidden.WeeklyHoroscopeLoader_ClientProxy.load(Unknown Source)
  at hidden.WeeklyHoroscopeLoader_ScheduledInvoker_load_6b738a5c78d7e250ef51b965844a7d66fb79bcb6.invokeBean(Unknown Source)
  at io.quarkus.scheduler.common.runtime.DefaultInvoker.invoke(DefaultInvoker.java:19)
  at io.quarkus.scheduler.common.runtime.StatusEmitterInvoker.invoke(StatusEmitterInvoker.java:35)
  at io.quarkus.scheduler.common.runtime.SkipConcurrentExecutionInvoker.invoke(SkipConcurrentExecutionInvoker.java:37)
  at io.quarkus.quartz.runtime.QuartzScheduler$InvokerJob.execute(QuartzScheduler.java:582)
  at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
  at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
  at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:705)
  at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)
 
 2022-08-14 11:16:00,955 WARN  [org.jbo.res.res.i18n] (LoadHoroscope_Worker-1) RESTEASY002120: ClassNotFoundException: Unable to load builtin provider org.jboss.resteasy.plugins.providers.JaxrsFormProvider from resource:/META-INF/services/javax.ws.rs.ext.Providers: java.lang.ClassNotFoundException: org.jboss.resteasy.plugins.providers.JaxrsFormProvider
  at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:52)
  at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:133)
  at org.jboss.resteasy.plugins.providers.RegisterBuiltin.registerProviders(RegisterBuiltin.java:95)
  at org.jboss.resteasy.plugins.providers.RegisterBuiltin.register(RegisterBuiltin.java:74)
  at org.jboss.resteasy.core.providerfactory.ResteasyProviderFactoryImpl.registerBuiltin(ResteasyProviderFactoryImpl.java:188)
  at org.jboss.resteasy.spi.ResteasyProviderFactory.getInstance(ResteasyProviderFactory.java:127)
  at org.jboss.resteasy.spi.ResteasyDeployment.onServer(ResteasyDeployment.java:19)
  at org.jboss.resteasy.microprofile.client.DefaultResponseExceptionMapper.handles(DefaultResponseExceptionMapper.java:28)
  at org.jboss.resteasy.microprofile.client.ExceptionMapping.filter(ExceptionMapping.java:71)
  at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.filterResponse(ClientInvocation.java:799)
  at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:495)
  at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:152)
  at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:115)
  at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
  at jdk.proxy4.$Proxy109.getWeeklyHoroscope(Unknown Source)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:146)
  at jdk.proxy4.$Proxy110.getWeeklyHoroscope(Unknown Source)
  at hidden.WeeklyHoroscopeLoader.load(WeeklyHoroscopeLoader.kt:40)
  at hidden.WeeklyHoroscopeLoader_Subclass.load$$superforward1(Unknown Source)
  at hidden.WeeklyHoroscopeLoader_Subclass$$function$$1.apply(Unknown Source)
  at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:53)
  at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:133)
  at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:104)
  at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
  at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:58)
  at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
  at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
  at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
  at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:40)
  at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
  at hidden.WeeklyHoroscopeLoader_Subclass.load(Unknown Source)
  at hidden.WeeklyHoroscopeLoader_ClientProxy.load(Unknown Source)
  at hidden.WeeklyHoroscopeLoader_ScheduledInvoker_load_6b738a5c78d7e250ef51b965844a7d66fb79bcb6.invokeBean(Unknown Source)
  at io.quarkus.scheduler.common.runtime.DefaultInvoker.invoke(DefaultInvoker.java:19)
  at io.quarkus.scheduler.common.runtime.StatusEmitterInvoker.invoke(StatusEmitterInvoker.java:35)
  at io.quarkus.scheduler.common.runtime.SkipConcurrentExecutionInvoker.invoke(SkipConcurrentExecutionInvoker.java:37)
  at io.quarkus.quartz.runtime.QuartzScheduler$InvokerJob.execute(QuartzScheduler.java:582)
  at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
  at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
  at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:705)
  at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)
 
```

Implementation deps:

```kotlin

dependencies {
    implementation("io.quarkus:quarkus-rest-client-jsonb")

    implementation("io.quarkus:quarkus-quartz")

    implementation("io.quarkus:quarkus-hibernate-orm-panache-kotlin")

    implementation("io.quarkus:quarkus-liquibase")

    implementation("io.quarkus:quarkus-jdbc-postgresql")

}
```

### Expected behavior

No warning should be logged.

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

17.0.4

### GraalVM version (if different from Java)

GraalVM 22.2.0.0-Final Java 17 Mandrel Distribution

### Quarkus version or git rev

2.11.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.5.1

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by michalvavrik**
fixes: #27277

[DefaultResponseExceptionMapper](https://github.com/resteasy/resteasy-microprofile/blob/main/rest-client-base/src/main/java/org/jboss/resteasy/microprofile/client/DefaultResponseExceptionMapper.java#L51) detect whether deployment is on server, so [ResteasyProviderFActory#getInstance](https://github.com/resteasy/Resteasy/blob/main/resteasy-core-spi/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java#L108) get called and different instance than our is created. This leads to loading builtin providers that, however, are removed in native mode. This PR makes sure our instance is used. The issue is not present when resteasy server is present as there [we provide ResteasyDeployment with provider classes (see line 629 and 623)](https://github.com/quarkusio/quarkus/blob/main/extensions/resteasy-classic/resteasy-server-common/deployment/src/main/java/io/quarkus/resteasy/server/common/deployment/ResteasyServerCommonProcessor.java#L629), these classes are later registered when creating a provider factory. I didn't add a test as it would require resteasy classic IT module without server that I didn't find and this fix is one liner.

### CODE REVIEW

**Comment by michalvavrik** [comment]
cc @geoand

**Comment by michalvavrik** [comment]
`JVM Tests - JDK 17 MacOS M1` seems like CI failures -> unrelated

File: extensions/resteasy-classic/rest-client/runtime/src/main/java/io/quarkus/restclient/runtime/RestClientRecorder.java [hunk 1]
```diff
@@ -43,6 +43,7 @@ public InjectorFactory getInjectorFactory() {
         registerProviders(clientProviderFactory, useBuiltIn, providersToRegister, contributedProviders);
         RestClientBuilderImpl.setProviderFactory(clientProviderFactory);
         ResteasyClientBuilderImpl.setProviderFactory(clientProviderFactory);
+        ResteasyProviderFactory.setInstance(clientProviderFactory);
```
Comment (gsmet) [inline extensions/resteasy-classic/rest-client/runtime/src/main/java/io/quarkus/restclient/runtime/RestClientRecorder.java:46]: Won't it also override the server defined one?

Comment (michalvavrik) [reply extensions/resteasy-classic/rest-client/runtime/src/main/java/io/quarkus/restclient/runtime/RestClientRecorder.java]: Didn't realize that, now it's set only when RESTEasy classic is absent. Thank you

**Comment by geoand** [comment]
Should'nt we have a test for this?

**Comment by michalvavrik** [comment]
@geoand it only makes sense to test when you run tests in native mode and RESTEasy Classic is not in the classpath. As far as you as okay with adding a new module to integration modules, I don't know where to put it. Any suggestions please? I love tests...

**Comment by geoand** [comment]
There is a RESTEasy Reactive Kotlin integration test module that should fit the bill

**Comment by michalvavrik** [comment]
But currently there are only reactive deps (it's reactive module), however this issue does only affect classic one. Hmm?

**Comment by geoand** [comment]
Then I misunderstood your comment above - you said that you were looking for a module that does not have the classic dependencies.

If you are looking for something that instead does not have the Reactive dependencies, the main integration test should be fine

**Comment by michalvavrik** [comment]
Let me phrase it differently as it's not like I didn't try to find the module. If you have app with both `io.quarkus:quarkus-resteasy` and `io.quarkus:quarkus-rest-client`, the issue won't appear (I tried to explain reasons for that in the PR desc, but I can elaborate more; you can also see that in the issue desc). You need app where there is no `io.quarkus:quarkus-resteasy` but you still can add there `io.quarkus:quarkus-rest-client`.

**Comment by geoand** [comment]
Okay

**Review by gsmet — APPROVED** [review]
