### PR TITLE
Use custom ObjectMapper for Keycloak admin client if necessary

### LINKED ISSUE #30516: Customize application ObjectMapper can impact Keycloak admin client
### Describe the bug

For a front application that required a snake case naming strategy I've customize the application ObjectMapper by adding this ObjectMapperCustomizer.
```java
@Singleton
public class CustomizeObjectMapper implements ObjectMapperCustomizer {
    public void customize(ObjectMapper mapper) {
        mapper.setVisibility(PropertyAccessor.FIELD, JsonAutoDetect.Visibility.ANY);
        mapper.setPropertyNamingStrategy(PropertyNamingStrategies.SNAKE_CASE);
    }
}
```

the most important line is 

```java
mapper.setPropertyNamingStrategy(PropertyNamingStrategies.SNAKE_CASE);
```

The application also allows you to list the users managed in keycloak by using the **quarkus-keycloak-admin-client-reactive** for this.

But io.quarkus.keycloak.admin.client.reactive.runtime.ResteasyReactiveClientProvider#getObjectMapper have the comment :

`// the whole idea here is to reuse the ObjectMapper instance`

So keycloak admin client resuse a customized ObjectMapper which is not compatible with keycloak naming strategy.

### Expected behavior

Keycloak users must be returned with all of their properties valued: Id, Username, FirstName, LastName, ....

### Actual behavior

Keycloak users are all returned, but some properties are not set. These, for example FistName or LastName remain empty. 

These are the properties whose name is impacted by the overloaded snake case strategy in ObjectMapperCustomizer.

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

Ubuntu 22.10

### Output of `java -version`

openjdk version "19.0.1" 2022-10-18

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.15.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #30516

### CODE REVIEW

File: extensions/keycloak-admin-client-reactive/runtime/src/main/java/io/quarkus/keycloak/admin/client/reactive/runtime/ResteasyReactiveClientProvider.java [hunk 1]
```diff
@@ -31,30 +34,54 @@ private ClientBuilderImpl registerJacksonProviders(ClientBuilderImpl clientBuild
...
+                .select(ObjectMapperCustomizer.class);
+        if (!customizers.isUnsatisfied()) {
+            // ObjectMapperCustomizer can make arbitrary changes, so in order to be safe we won't allow reuse
+            return false;
+        }
+        InstanceHandle<JacksonBuildTimeConfig> jacksonConfig = arcContainer.instance(JacksonBuildTimeConfig.class);
+        if (jacksonConfig.isAvailable()) {
+            return jacksonConfig.get().propertyNamingStrategy.isEmpty();
+        }
+        return true;
```
Comment (gsmet) [inline extensions/keycloak-admin-client-reactive/runtime/src/main/java/io/quarkus/keycloak/admin/client/reactive/runtime/ResteasyReactiveClientProvider.java:82]: Don't you think it's going to be brittle? My fear is that we might break it when adding new Jackson customization options.
I'm not sure if it's really worth taking the risk, just to avoid creating a second `ObjectMapper` object.

Comment (geoand) [reply extensions/keycloak-admin-client-reactive/runtime/src/main/java/io/quarkus/keycloak/admin/client/reactive/runtime/ResteasyReactiveClientProvider.java:82]: I want to avoid creating a second `ObjectMapper` if at all possible.

The other option here is to look and see if there is any `quarkus.jackson...` configuration option set

Comment (geoand) [reply extensions/keycloak-admin-client-reactive/runtime/src/main/java/io/quarkus/keycloak/admin/client/reactive/runtime/ResteasyReactiveClientProvider.java]: PR updated to follow the approach mentioned above

**Comment by sberyozkin** [comment]
Hi @geoand It may be worth registering a custom ObjectMapper to check that this test, https://github.com/quarkusio/quarkus/blob/main/integration-tests/keycloak-authorization/src/test/java/io/quarkus/it/keycloak/AdminClientTestCase.java , is still passing

**Comment by geoand** [comment]
PR should be good to go now that the test was added (and another related bug fixed)

File: integration-tests/keycloak-authorization/src/main/java/io/quarkus/it/keycloak/AdminClientResource.java [hunk 2]
```diff
@@ -29,22 +29,22 @@ public class AdminClientResource {
...
+    public String getRealm() {
+        return keycloak.realm("quarkus").toRepresentation().getRealm();
     }
 
     @GET
-    @Produces(MediaType.APPLICATION_JSON)
+    @Produces(MediaType.TEXT_PLAIN)
     @Path("newrealm")
-    public RealmRepresentation createRealm() {
+    public String createRealm() {
```
Comment (sberyozkin) [inline integration-tests/keycloak-authorization/src/main/java/io/quarkus/it/keycloak/AdminClientResource.java:41]: Why is `ReamRepresentation` is replaced with `String`  here ?

Comment (geoand) [reply integration-tests/keycloak-authorization/src/main/java/io/quarkus/it/keycloak/AdminClientResource.java:41]: Because the `ObjectMapperCustomizer` I added customizes the server response, which means that you can no longer properly serialize it and expect the test code to be able to deserialize.

Comment (sberyozkin) [reply integration-tests/keycloak-authorization/src/main/java/io/quarkus/it/keycloak/AdminClientResource.java:41]: @geoand Oh yes, I see, KeycloakAdminClient itself returns a correct instance

**Review by sberyozkin — APPROVED** [review]
Thanks Georgios, LGTM.

**Comment by sberyozkin** [comment]
>Looks like we need to update more of the client tests to make CI happy
Sorry Georgios, looks like it is a pretty sensitive change :-)

**Comment by geoand** [comment]
It's a chance to do the right thing 🙂

**Comment by geoand** [comment]
It should be good now

**Comment by sberyozkin** [comment]
Getting there :-)

**Comment by sberyozkin** [comment]
We can start with the duplicate one if it proves too sensitive to optimise

**Comment by geoand** [comment]
This seems like the gift that keeps on giving...

**Comment by geoand** [comment]
I believe it should be fine now.

This turned out to be a lot more than I bargained for :)

**Comment by geoand** [comment]
I removed the backport label because this has the potential to cause issues: Essentially we used to mix the client's and server's Jackson related MessageBodyReader / Writer classes, which now we don't (this is the proper behavior).

**Comment by mjurc** [comment]
@geoand Imho this should be in https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.0#resteasy-reactive - as the decoupling can break the user apps (as it did for our tests)

**Comment by geoand** [comment]
I don't see why we would, because `quarkus-admin-client-reactive` already includes `quarkus-rest-client-reactive-jackson`
