### PR TITLE
RESTEasy Reactive: implement cancel for Multi on both client and server

### LINKED ISSUE #13988: Resteasy mutiny : multi subscription not cancelled if the request is cancelled from browser.
**Describe the bug**
When using resteasy with mutiny, I am sending an infinite stream as output and have opened the endpoint in the browser 
`http://localhost:8080/block/test`
After some time I have cancelled the request from browser but the server is still generating data. I am very new to Quarkus and testing out stuff, please correct if I am doing anything wrong. Please check the screenshot for the dependencies used.

```
@Path("/")
public class ReactiveGreetingResource 
{

    @Inject
    ReactiveGreetingService service;

    private static final Logger LOG = Logger.getLogger(ReactiveGreetingResource.class);

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    @Path("block/{name}")
    public Multi<Long> greeting(@PathParam String name) {
        return Multi.createFrom().ticks().every(
  			  
  			  Duration.ofSeconds(2)).invoke(x -> {
  				  
  				  LOG.info(Thread.currentThread().getName() + "-" + new Date().getSeconds());});
    }

}
```

**Expected behavior**
Multi should stop generating data if the request is cancelled. The subscription should be cancelled on request cancel.

**Actual behavior**
Multi is still generating data even though the request is cancelled.

**Screenshots**
Screenshot from 2020-12-20 00-27-32

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: 11
 - GraalVM version (if different from Java): 20.3.0.r11-grl
 - Quarkus version or git rev: 1.10.3.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
```
Apache Maven 3.6.0
Maven home: /usr/share/maven
Java version: 11.0.9, vendor: GraalVM Community, runtime: .sdkman/candidates/java/20.3.0.r11-grl
Default locale: en_IN, platform encoding: UTF-8
OS name: "linux", version: "5.3.0-46-generic", arch: "amd64", family: "unix"

```

### PR DESCRIPTION
**Pull request by FroMage**
Fixes #13988

### CODE REVIEW

File: independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/impl/MultiInvoker.java [hunk 1]
```diff
@@ -34,34 +36,86 @@ public MultiInvoker(WebTargetImpl target) {
         return (Multi<R>) super.get(responseType);
     }
 
+    /**
+     * We need this class to work around a bug in Mutiny where we can register our cancel listener
+     * after the subscription is cancelled and we never get notified
+     */
+    static class MultiRequest<R> {
```
Comment (geoand) [inline independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/impl/MultiInvoker.java:43]: So can we drop this when the said mutiny bug is fixed?

**Review by geoand — APPROVED** [review]

File: independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/impl/MultiInvoker.java (hunk 1 above)
Comment (FroMage) [reply independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/impl/MultiInvoker.java:43]: Yes, I'll add a note as to which bug it is: https://github.com/smallrye/smallrye-mutiny/issues/417

Comment (geoand) [reply independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/impl/MultiInvoker.java:43]: Cool, thanks

Comment (FroMage) [reply independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/impl/MultiInvoker.java:44]: Added note.

**Comment by gsmet** [comment]
This PR does not compile:
```
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
/home/runner/work/quarkus/quarkus/extensions/resteasy-reactive/quarkus-resteasy-reactive-servlet/runtime/src/main/java/io/quarkus/resteasy/reactive/server/servlet/runtime/ServletRequestContext.java:[50,8] io.quarkus.resteasy.reactive.server.servlet.runtime.ServletRequestContext is not abstract and does not override abstract method addCloseHandler(java.lang.Runnable) in org.jboss.resteasy.reactive.server.spi.ServerHttpResponse
```

**Comment by geoand** [comment]
Damn servlet...

@FroMage now with all the splitting that has been done, fixes need more surgery 😎

**Comment by FroMage** [comment]
DAMNIT, I knew there was a servlet impl, but I couldn't find it.

**Comment by FroMage** [comment]
And I don't get that class, it appears to still use Vert.x underneath.

**Comment by geoand** [comment]
> And I don't get that class, it appears to still use Vert.x underneath.

Well yeah, because it uses Quarkus HTTP (essentially Undertow 3) which is based on Vert.x
The idea isn't to have it totally decoupled from Vert.x (I think), but to have a proof of concept Servlet implementation.

**Comment by FroMage** [comment]
OK, should compile now :)

**Comment by gsmet** [comment]
@geoand @FroMage could you confirm the TCK test failure is not related?

```
JAXRSClient0176.closeTest:327->SSEJAXRSClient0177.querySSEEndpointAndAssert:69->SSEJAXRSClient0177.querySSEEndpoint:44->SSEJAXRSClient0177.querySSEEndpoint:64->JAXRSCommonClient.assertNotNull:789->JAXRSCommonClient.assertTrue:697->JAXRSCommonClient.fault:802 The message was not received
```

**Comment by geoand** [comment]
It does look related TBH, but @FroMage is the SSE expert

**Comment by gsmet** [comment]
OK, I won't include this one in CR1 then. We need a bit more time.

**Comment by FroMage** [comment]
Those tests do run on my machine, so I've restarted the tests.

**Comment by gsmet** [comment]
Note that even if it passes the second time, it looks like it's going to be flaky so we need to act on it.

**Comment by FroMage** [comment]
Yes, I'm trying to reproduce it.

**Comment by FroMage** [comment]
I think I fixed the TCK tests. Let's hope so.
