### PR TITLE
Ensure that Kubernetes Watchers work properly

### LINKED ISSUE #3077: Kubernetes client extension: JsonMappingException in native mode
I created a minimal project with the new Fabric8 Kubernetes Client extension. When I watch Pods, I get the following error:

```
Could not deserialize watch event: ...
com.fasterxml.jackson.databind.JsonMappingException: No resource type found for:v1#Pod
 at [Source: (String)"{"type":"ADDED","object":{"kind":"Pod","apiVersion":"v1","metadata":{"name":"operator-example-7fb6446744-969t5","generateName":"operator-example-7fb6446744-","namespace":"default","selfLink":"/api/v1/namespaces/default/pods/operator-example-7fb6446744-969t5","uid":"2d6e35d4-9d6a-11e9-ab7b-0242e3a6ea5b","resourceVersion":"4772","creationTimestamp":"2019-07-03T08:11:36Z","labels":{"app":"operator-example","pod-template-hash":"7fb6446744"},"ownerReferences":[{"apiVersion":"apps/v1","kind":"ReplicaS"[truncated 2069 chars]; line: 1, column: 2567] (through reference chain: io.fabric8.kubernetes.api.model.WatchEvent["object"])
        at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:1718)
        at io.fabric8.kubernetes.internal.KubernetesDeserializer.deserialize(KubernetesDeserializer.java:78)
        at io.fabric8.kubernetes.internal.KubernetesDeserializer.deserialize(KubernetesDeserializer.java:32)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3004)
        at io.fabric8.kubernetes.client.dsl.internal.WatchHTTPManager.readWatchEvent(WatchHTTPManager.java:293)
        at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$1.onMessage(WatchConnectionManager.java:224)
        at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:323)
        at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274)
        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:473)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
```

This is reproducable with the following minimal Java code:

```java
package com.instana.operator.example;

import io.fabric8.kubernetes.api.model.Pod;
import io.fabric8.kubernetes.client.DefaultKubernetesClient;
import io.fabric8.kubernetes.client.KubernetesClient;
import io.fabric8.kubernetes.client.KubernetesClientException;
import io.fabric8.kubernetes.client.Watcher;
import io.quarkus.runtime.StartupEvent;

import javax.enterprise.context.ApplicationScoped;
import javax.enterprise.event.Observes;

@ApplicationScoped
public class PodWatcher {

  void onStartup(@Observes StartupEvent _ev) {
    new Thread(this::watchPods).start();
  }

  private void watchPods() {
    KubernetesClient client = new DefaultKubernetesClient().inNamespace("default");
    client.pods().watch(new Watcher<Pod>() {
      @Override
      public void eventReceived(Action action, Pod pod) {
        System.out.println("Received " + action + " event for Pod " + pod.getMetadata().getName());
      }

      @Override
      public void onClose(KubernetesClientException e) {
        e.printStackTrace();
        System.exit(-1);
      }
    });
  }
}
```
The code works when I run it on the JVM instead of native mode.

### PR DESCRIPTION
**Pull request by geoand**
Fixes #3077

### CODE REVIEW

File: extensions/kubernetes-client/deployment/src/main/java/io/quarkus/kubernetes/client/deployment/KubernetesClientProcessor.java [hunk 1]
```diff
@@ -20,14 +25,30 @@
...
+                .forEach(c -> {
+                    final MethodInfo eventReceived = c.firstMethod("eventReceived");
+                    if (eventReceived != null) {
+                        if (eventReceived.parameters().size() == 2) {
+                            watchedClasses.add(eventReceived.parameters().get(1).name().toString());
+                        }
+                    }
+                });
+        if (!watchedClasses.isEmpty()) {
+            reflectiveClasses.produce(new ReflectiveClassBuildItem(true, true, watchedClasses.toArray(new String[0])));
```
Comment (gsmet) [inline extensions/kubernetes-client/deployment/src/main/java/io/quarkus/kubernetes/client/deployment/KubernetesClientProcessor.java]: Wouldn't it be better to make the array the size of `watchedClasses`?

File: extensions/kubernetes-client/runtime/src/main/java/io/quarkus/kubernetes/client/runtime/graal/KubernetesDeserializerSubstitutions.java [hunk 2]
```diff
@@ -0,0 +1,17 @@
+package io.quarkus.kubernetes.client.runtime.graal;
+
+import com.oracle.svm.core.annotate.Substitute;
+import com.oracle.svm.core.annotate.TargetClass;
+
+@TargetClass(className = "io.fabric8.kubernetes.internal.KubernetesDeserializer")
+public final class KubernetesDeserializerSubstitutions {
+
+    @Substitute
+    private static Class loadClassIfExists(String className) {
```
Comment (gsmet) [inline extensions/kubernetes-client/runtime/src/main/java/io/quarkus/kubernetes/client/runtime/graal/KubernetesDeserializerSubstitutions.java]: Please add a proper comment explaining the why of this substitution. I suppose it's related to the class loader, somehow?

Furthermore, it doesn't look related to the first part of the commit? Should it be a separate commit explaining what it's supposed to fix?

File: extensions/kubernetes-client/deployment/src/main/java/io/quarkus/kubernetes/client/deployment/KubernetesClientProcessor.java [hunk 3]
```diff
@@ -20,14 +25,30 @@
...
+    public void process(ApplicationIndexBuildItem applicationIndex, CombinedIndexBuildItem combinedIndexBuildItem,
             BuildProducer<ExtensionSslNativeSupportBuildItem> sslNativeSupport) {
         featureProducer.produce(new FeatureBuildItem(FeatureBuildItem.KUBERNETES_CLIENT));
 
+        Set<String> watchedClasses = new HashSet<>();
+        // make sure the watchers fully (and not weakly) register Kubernetes classes for reflection
+        applicationIndex.getIndex().getAllKnownImplementors(DotName.createSimple("io.fabric8.kubernetes.client.Watcher"))
+                .forEach(c -> {
+                    final MethodInfo eventReceived = c.firstMethod("eventReceived");
+                    if (eventReceived != null) {
```
Comment (gsmet) [inline extensions/kubernetes-client/deployment/src/main/java/io/quarkus/kubernetes/client/deployment/KubernetesClientProcessor.java]: I think this is a bit too fragile and it would be better to rely on the type parameter of the `Watcher`. I'm not sure if we have a way to properly resolve it with Jandex though.

I need something similar for HV so it won't be a lost cause.

**Review by gsmet — COMMENTED** [review]
I added a couple of comments.

File: extensions/kubernetes-client/deployment/src/main/java/io/quarkus/kubernetes/client/deployment/KubernetesClientProcessor.java (hunk 1 above)
Comment (geoand) [reply extensions/kubernetes-client/deployment/src/main/java/io/quarkus/kubernetes/client/deployment/KubernetesClientProcessor.java]: That's what I did initially, but it turns out that it's not needed - IntelliJ auto-suggests change

File: extensions/kubernetes-client/runtime/src/main/java/io/quarkus/kubernetes/client/runtime/graal/KubernetesDeserializerSubstitutions.java (hunk 2 above)
Comment (geoand) [reply extensions/kubernetes-client/runtime/src/main/java/io/quarkus/kubernetes/client/runtime/graal/KubernetesDeserializerSubstitutions.java]: Sure thing, I will add a comment. But I think that it should be one commit, since this change is also needed to get the `Watcher` working.

File: extensions/kubernetes-client/deployment/src/main/java/io/quarkus/kubernetes/client/deployment/KubernetesClientProcessor.java (hunk 3 above)
Comment (geoand) [reply extensions/kubernetes-client/deployment/src/main/java/io/quarkus/kubernetes/client/deployment/KubernetesClientProcessor.java]: Good point. Let me check and see if there is a way to do that

Comment (gsmet) [reply extensions/kubernetes-client/deployment/src/main/java/io/quarkus/kubernetes/client/deployment/KubernetesClientProcessor.java]: Note that you would have to support something like:
```
WatcherImpl implements MyWatcher<Foo>
```
with
```
MyWatcher<S> extends Watcher<S>
```
We use classmate to do that in HV itself but having a pure Jandex solution would be handy.

We should share it somewhere and polish it over the time.

Comment (geoand) [reply extensions/kubernetes-client/deployment/src/main/java/io/quarkus/kubernetes/client/deployment/KubernetesClientProcessor.java]: At this point I would say I am comfortable enough with Jandex to make any changes to it. I was basically thinking of checking to see if it supports what is needed in this case and if so using it.
Does that make sense?

File: extensions/kubernetes-client/runtime/src/main/java/io/quarkus/kubernetes/client/runtime/graal/KubernetesDeserializerSubstitutions.java (hunk 2 above)
Comment (geoand) [reply extensions/kubernetes-client/runtime/src/main/java/io/quarkus/kubernetes/client/runtime/graal/KubernetesDeserializerSubstitutions.java]: Furthermore this part of the code seems to only be reached on watch operations, not crud operations

File: extensions/kubernetes-client/deployment/src/main/java/io/quarkus/kubernetes/client/deployment/KubernetesClientProcessor.java (hunk 3 above)
Comment (gsmet) [reply extensions/kubernetes-client/deployment/src/main/java/io/quarkus/kubernetes/client/deployment/KubernetesClientProcessor.java]: You are or you are **not**?

I wasn't thinking about making changes to Jandex for now. I was wondering if we could write some code to use the information we have in the index to get the proper type parameter information expanded.

We could use it here, I think I would need it too for my latest changes to HV (maybe not the same exactly as I have 2 type parameters but something very similar).

I'm not sure how much work it would be though.

Comment (geoand) [reply extensions/kubernetes-client/deployment/src/main/java/io/quarkus/kubernetes/client/deployment/KubernetesClientProcessor.java]: Sorry, I meant I am **not** :P.

I see what you are saying and it makes perfect sense. I'll see what I can come up with :)

**Comment by geoand** [comment]
@gsmet PR updated. It now contains an implementation what we talked about - resolving generic types of an interface (`Watcher` used in this case)  that are used by concrete classes that implement said interface.

File: extensions/kubernetes-client/deployment/src/main/java/io/quarkus/kubernetes/client/deployment/KubernetesClientProcessor.java (hunk 3 above)
Comment (geoand) [reply extensions/kubernetes-client/deployment/src/main/java/io/quarkus/kubernetes/client/deployment/KubernetesClientProcessor.java]: Addressed

File: extensions/kubernetes-client/runtime/src/main/java/io/quarkus/kubernetes/client/runtime/graal/KubernetesDeserializerSubstitutions.java (hunk 2 above)
Comment (geoand) [reply extensions/kubernetes-client/runtime/src/main/java/io/quarkus/kubernetes/client/runtime/graal/KubernetesDeserializerSubstitutions.java]: Added comment

File: core/deployment/src/main/java/io/quarkus/deployment/util/GenericTypeUtil.java [hunk 4]
```diff
@@ -0,0 +1,160 @@
...
+    public GenericTypeUtil() {
+    }
+
+    /**
+     * Returns the captured generic types of an interface given a class that at some point in the class
+     * hierarchy implements the interface.
+     *
+     * The list contains the types in the same order as they are generic parameters defined on the interface
+     *
+     * A result is only returned iff all the generics where captured. If any of them where not defined by the class
```
Comment (gsmet) [inline core/deployment/src/main/java/io/quarkus/deployment/util/GenericTypeUtil.java]:
```suggestion
     * A result is only returned if all the generics were captured. If any of them where not defined by the class
```

File: core/deployment/src/main/java/io/quarkus/deployment/util/GenericTypeUtil.java [hunk 5]
```diff
@@ -0,0 +1,160 @@
...
+     */
+    public static List<Type> getCapturedGenericTypesOfInterface(DotName clazz, DotName iface, IndexView index) {
+        final ClassInfo classInfo = index.getClassByName(clazz);
+        if (classInfo == null) {
+            throw new IllegalArgumentException("Class " + clazz + " was not found in the index");
+        }
+
+        final ClassInfo ifaceClassInfo = index.getClassByName(iface);
+        if (ifaceClassInfo == null) {
+            throw new IllegalArgumentException("Interface " + iface + " was not found in the index");
```
Comment (gsmet) [inline core/deployment/src/main/java/io/quarkus/deployment/util/GenericTypeUtil.java]: I have a few other minor issues with the code but my main interrogation is: can we do it without requiring all the interfaces/superclasses to be in the index.

Because there's a good chance they will not be. Typically, `javax.validation.ConstraintValidator` for instance is not in the index. And I'm not sure I want to make it so.

AFAICS, without this preliminary check, you could live without the main interface being in the index or am I mistaken?

File: core/deployment/src/main/java/io/quarkus/deployment/util/GenericTypeUtil.java [hunk 6]
```diff
@@ -0,0 +1,160 @@
...
+
+import org.jboss.jandex.ClassInfo;
+import org.jboss.jandex.ClassType;
+import org.jboss.jandex.DotName;
+import org.jboss.jandex.IndexView;
+import org.jboss.jandex.ParameterizedType;
+import org.jboss.jandex.Type;
+import org.jboss.jandex.TypeVariable;
+
+public final class GenericTypeUtil {
```
Comment (gsmet) [inline core/deployment/src/main/java/io/quarkus/deployment/util/GenericTypeUtil.java]: I think I would have made it a `JandexUtil`.

File: core/deployment/src/main/java/io/quarkus/deployment/util/GenericTypeUtil.java [hunk 7]
```diff
@@ -0,0 +1,160 @@
...
+
+        return result;
+    }
+
+    private static boolean isDirectlyHandledType(Type matchingCapturedType) {
+        return (matchingCapturedType instanceof ClassType) ||
+                (matchingCapturedType instanceof ParameterizedType);
+    }
+
+    private static FindResult find(DotName iface, ClassInfo classInfo, IndexView index, List<Level> visitedTypes) {
```
Comment (gsmet) [inline core/deployment/src/main/java/io/quarkus/deployment/util/GenericTypeUtil.java]: The name of this method is too generic.

File: core/deployment/src/main/java/io/quarkus/deployment/util/GenericTypeUtil.java [hunk 8]
```diff
@@ -0,0 +1,160 @@
...
+        final List<Level> newVisitedTypes = new LinkedList<>(visitedTypes);
+        if (type instanceof ParameterizedType) {
+            final ClassInfo classInfo = index.getClassByName(type.name());
+            final Level level = new Level(type.name(), classInfo.typeParameters(), type.asParameterizedType().arguments());
+            newVisitedTypes.add(0, level);
+        }
+        return newVisitedTypes;
+    }
+
+    private static class FindResult {
```
Comment (gsmet) [inline core/deployment/src/main/java/io/quarkus/deployment/util/GenericTypeUtil.java]: Same here, too generic.

File: core/deployment/src/main/java/io/quarkus/deployment/util/GenericTypeUtil.java [hunk 9]
```diff
@@ -0,0 +1,160 @@
...
+        private final List<Type> argumentsOfMatch;
+        private final List<Level> levels;
+
+        public FindResult(List<Type> argumentsOfMatch, List<Level> levels) {
+            this.argumentsOfMatch = argumentsOfMatch;
+            this.levels = levels;
+        }
+    }
+
+    private static class Level {
```
Comment (gsmet) [inline core/deployment/src/main/java/io/quarkus/deployment/util/GenericTypeUtil.java]: Too generic too.

File: core/deployment/src/main/java/io/quarkus/deployment/util/GenericTypeUtil.java [hunk 10]
```diff
@@ -0,0 +1,160 @@
...
+                }
+                return null;
+            }
+            // we only check the other interfaces if we didn't find anything
+            // this ensures that we also use the "closest" path to the target interface
+            otherInterfaces.add(interfaceType);
+        }
+
+        for (Type otherInterface : otherInterfaces) {
+            final FindResult findResult = find(iface, index.getClassByName(otherInterface.name()), index,
```
Comment (gsmet) [inline core/deployment/src/main/java/io/quarkus/deployment/util/GenericTypeUtil.java]: Are you sure this one is in the index? There is a similar issue a few lines below.

File: core/deployment/src/main/java/io/quarkus/deployment/util/GenericTypeUtil.java [hunk 11]
```diff
@@ -0,0 +1,160 @@
...
+    /**
+     * Returns the captured generic types of an interface given a class that at some point in the class
+     * hierarchy implements the interface.
+     *
+     * The list contains the types in the same order as they are generic parameters defined on the interface
+     *
+     * A result is only returned iff all the generics where captured. If any of them where not defined by the class
+     * an exception is thrown
+     */
+    public static List<Type> getCapturedGenericTypesOfInterface(DotName clazz, DotName iface, IndexView index) {
```
Comment (gsmet) [inline core/deployment/src/main/java/io/quarkus/deployment/util/GenericTypeUtil.java]:
```suggestion
    public static List<Type> resolveTypeParameters(DotName clazz, DotName iface, IndexView index) {
```
?

File: core/deployment/src/main/java/io/quarkus/deployment/util/GenericTypeUtil.java (hunk 4 above)
Comment (gsmet) [inline core/deployment/src/main/java/io/quarkus/deployment/util/GenericTypeUtil.java]: I'm far from being convinced this is the best behavior. I would have allowed to resolve only the one I'm interested in because there's a good chance I will be interesting in only one of them.

**Review by gsmet — COMMENTED** [review]
Interesting work. I added some comments/questions inline.

File: core/deployment/src/main/java/io/quarkus/deployment/util/GenericTypeUtil.java (hunk 4 above)
Comment (geoand) [reply core/deployment/src/main/java/io/quarkus/deployment/util/GenericTypeUtil.java]: Actually the `iff` part was intentional - If and only if :). But I will update it to clarify

File: core/deployment/src/main/java/io/quarkus/deployment/util/GenericTypeUtil.java (hunk 5 above)
Comment (geoand) [reply core/deployment/src/main/java/io/quarkus/deployment/util/GenericTypeUtil.java]: Yes and do I would say.

Strictly speaking, yes the interface itself doesn't need to be in the index. But for the method to actually work, all the other interfaces in the path from the class to the interface do need to be in the index.

Why would `javax.validation.ConstraintValidator` not be in the index? In my case I look for Kubernetes resources which are not in the application index but they are in the combined index.

WDYT is the proper course of action here?

File: core/deployment/src/main/java/io/quarkus/deployment/util/GenericTypeUtil.java (hunk 4 above)
Comment (geoand) [reply core/deployment/src/main/java/io/quarkus/deployment/util/GenericTypeUtil.java]: TBH I have been pondering this as well. On one hand I absolutely understand the use case of being able to only resolve the parameters I care about, on the other hand it could lead to very surpring behavior where some of the arguments are resolved and others are not.

I'm on the fence with this one so I'll let you decide :)

File: core/deployment/src/main/java/io/quarkus/deployment/util/GenericTypeUtil.java (hunk 11 above)
Comment (geoand) [reply core/deployment/src/main/java/io/quarkus/deployment/util/GenericTypeUtil.java]: Makes sense

File: core/deployment/src/main/java/io/quarkus/deployment/util/GenericTypeUtil.java (hunk 6 above)
Comment (geoand) [reply core/deployment/src/main/java/io/quarkus/deployment/util/GenericTypeUtil.java]: No strong opinion on this, so let's go with `JandexUtil`

File: core/deployment/src/main/java/io/quarkus/deployment/util/GenericTypeUtil.java (hunk 5 above)
Comment (gsmet) [reply core/deployment/src/main/java/io/quarkus/deployment/util/GenericTypeUtil.java]: Well, I'm wondering if we could support both classes and interfaces and remove this test entirely.

Even if we can't, I would remove this test.

All the classes are not in the index. I'm pretty sure the `javax.validation` ones won't be in the index except if I make them part of it.

File: core/deployment/src/main/java/io/quarkus/deployment/util/GenericTypeUtil.java (hunk 10 above)
Comment (geoand) [reply core/deployment/src/main/java/io/quarkus/deployment/util/GenericTypeUtil.java]: Yeah... As mentioned above the entire hierarchy needs to be in the index, there is no way around that as far as I can tell.

So perhaps I should add a check here and throw an exception if it's not

File: core/deployment/src/main/java/io/quarkus/deployment/util/GenericTypeUtil.java (hunk 5 above)
Comment (geoand) [reply core/deployment/src/main/java/io/quarkus/deployment/util/GenericTypeUtil.java]: Supporting both classes and interfaces should be possible with a little more work. 
But I don't see a way of getting around things being in the index

**Comment by geoand** [comment]
@gsmet PR updated to address all your suggestions except the index restriction.

File: core/deployment/src/main/java/io/quarkus/deployment/util/GenericTypeUtil.java (hunk 10 above)
Comment (geoand) [reply core/deployment/src/main/java/io/quarkus/deployment/util/GenericTypeUtil.java]: Added index check here as well

**Review by gsmet — APPROVED** [review]
OK, let's get this one.

**Comment by geoand** [comment]
Cool, thanks!
