### PR TITLE
Ensure quarkusBuild Gradle task works properly with fast-jar

### LINKED ISSUE #11157: Gradle fast-jar is not recreated when using clean
**Describe the bug**
When I was using fast-jar I noticed, that fast jar is not recreated if you call `gradle clean quarkusBuild` two times in a row. Task :quarkusBuild is reported as up to date the second time. 

**Expected behavior**
Fast jar is recreated if it is not present in `build/quarkus-app` directory

**Actual behavior**
There is no Fast jar in `build/` directory (there is no `build/quarkus-app` directory) after second call.

**To Reproduce**
1. git clone git@github.com:asodja/quarkus-clean-fast-jar-reproducer.git
2. run `gradle clean quarkusBuild  --info`: fast jar is created
3. run `gradle clean quarkusBuild  --info` again: there is no fast jar in `build/`, quarkusBuild is reported up-to-date
4. remove `.gradle` folder in the project and run 2-3. again to reproduce the behaviour 

**Configuration**
```properties
quarkus.package.type=fast-jar
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin Kernel Version 19.5.0, MacBookPro16,1 Darwin
 - Output of `java -version`: openjdk version "1.8.0_242"
 - Quarkus version: tested with 1.6.1 and 1.7.0.CR1 
 - Build tool: Gradle 6.5.1

### PR DESCRIPTION
**Pull request by geoand**
When building a fast-jar, the typical runner jar is not created
so we need to make Gradle aware of this new output

Fixes: #11157

### CODE REVIEW

File: devtools/gradle/src/main/java/io/quarkus/gradle/tasks/QuarkusBuild.java [hunk 1]
```diff
@@ -78,13 +78,18 @@ public FileCollection getClasspath() {
...
 
     @OutputFile
-    public File getOutputDir() {
+    public File runnerJar() {
         return new File(getProject().getBuildDir(), extension().finalName() + "-runner.jar");
     }
 
+    @OutputFile
+    public File fastJar() {
+        return new File(getProject().getBuildDir(), "quarkus-app");
```
Comment (gsmet) [inline devtools/gradle/src/main/java/io/quarkus/gradle/tasks/QuarkusBuild.java:87]: It's not a problem if only one of the two is created when running the goal?

Comment (geoand) [reply devtools/gradle/src/main/java/io/quarkus/gradle/tasks/QuarkusBuild.java:87]: I had the same question myself, so I ran multiple tests and didn't see any problem.

Of course this will need to vetted by our Gradle experts :)

Comment (glefloch) [reply devtools/gradle/src/main/java/io/quarkus/gradle/tasks/QuarkusBuild.java:87]: Actually I had the same thought too, there are tests checking, if this is ok, we could also declare the native build result.

**Review by glefloch — APPROVED** [review]

File: devtools/gradle/src/main/java/io/quarkus/gradle/tasks/QuarkusBuild.java (hunk 1 above)
Comment (geoand) [reply devtools/gradle/src/main/java/io/quarkus/gradle/tasks/QuarkusBuild.java:87]: @glefloch yeah, that's a good idea for a follow up

File: devtools/gradle/src/main/java/io/quarkus/gradle/tasks/QuarkusBuild.java [hunk 2]
```diff
@@ -78,13 +78,18 @@ public FileCollection getClasspath() {
...
 
     @OutputFile
-    public File getOutputDir() {
+    public File getRunnerJar() {
         return new File(getProject().getBuildDir(), extension().finalName() + "-runner.jar");
     }
 
+    @OutputFile
+    public File getFastJar() {
+        return new File(getProject().getBuildDir(), "quarkus-app");
```
Comment (gastaldi) [inline devtools/gradle/src/main/java/io/quarkus/gradle/tasks/QuarkusBuild.java:87]: Sorry my ignorance, but isn't a `·jar' extension missing here?

Comment (geoand) [reply devtools/gradle/src/main/java/io/quarkus/gradle/tasks/QuarkusBuild.java:87]: This is just the directory where all the fast-jar output goes

File: devtools/gradle/src/main/java/io/quarkus/gradle/tasks/QuarkusBuild.java (hunk 1 above)
Comment (glefloch) [reply devtools/gradle/src/main/java/io/quarkus/gradle/tasks/QuarkusBuild.java:87]: Oh this should be `@OutputDirectory` then.
 And reading the documentation, it should works as expected: 
```
This will cause the task to be considered out-of-date when the directory path or task output to that directory has been modified since the task was last run.
```
Missing directory should not be a problem.

File: devtools/gradle/src/main/java/io/quarkus/gradle/tasks/QuarkusBuild.java (hunk 2 above)
Comment (glefloch) [reply devtools/gradle/src/main/java/io/quarkus/gradle/tasks/QuarkusBuild.java:87]: This should be `@OutputDirectory` then. 
BTW, reading the documentation, a missing directory should not be a problem.

File: devtools/gradle/src/main/java/io/quarkus/gradle/tasks/QuarkusBuild.java (hunk 1 above)
Comment (geoand) [reply devtools/gradle/src/main/java/io/quarkus/gradle/tasks/QuarkusBuild.java:87]: Oh nice, I didn't know of that annotation

**Review by gastaldi — APPROVED** [review]

**Review by glefloch — APPROVED** [review]

**Review by gsmet — APPROVED** [review]
