### PR TITLE
fix grpc method conversion in BlockingServerInterceptor

### LINKED ISSUE #48358: @Blocking not working on grpc service methods if method contains reserved keyword or underscore
### Describe the bug

Proto files with rpc definitions like `rpc A_B(Request) returns (Reply)` or `rpc Assert(Request) returns (Reply)` will compile into stubs with methods `aB` and `assert_` respectively. This is due to an effort of grpc-java to honor the Java Bean Spec.

When annotating these methods with `io.smallrye.common.annotation.Blocking`, like:

```java
@Blocking
public void aB(Request request, StreamObserver<Reply> responseObserver)
```

... the BlockingServerInterceptor will not work for these converted method names, ultimately leading to failure at runtime if blocking behaviour is detected.

### Expected behavior

It should work just as it does for "normal" rpc methods.

### Actual behavior

Fails at runtime if i/o, etc is used.

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by nconcetti**
- Fixes: https://github.com/quarkusio/quarkus/issues/48358.

### CODE REVIEW

File: extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/blocking/BlockingServerInterceptor.java [hunk 1]
```diff
@@ -1,10 +1,6 @@
 package io.quarkus.grpc.runtime.supports.blocking;
 
-import java.util.HashSet;
-import java.util.List;
-import java.util.Map;
-import java.util.Queue;
-import java.util.Set;
+import java.util.*;
```
Comment (cescoffier) [inline extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/blocking/BlockingServerInterceptor.java]: No star import

File: extensions/grpc/runtime/src/test/java/io/quarkus/grpc/runtime/supports/BlockingServerInterceptorTest.java [hunk 2]
```diff
@@ -4,7 +4,7 @@
 import static org.mockito.Mockito.mock;
 import static org.mockito.Mockito.when;
 
-import java.util.Collections;
+import java.util.*;
```
Comment (cescoffier) [inline extensions/grpc/runtime/src/test/java/io/quarkus/grpc/runtime/supports/BlockingServerInterceptorTest.java]: No star import

**Review by cescoffier — CHANGES_REQUESTED** [review]
LGTM, thanks.

Can you replace the star imports and makes sure your code is formatted (or the CI will complain).

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
Can you squash your commits?

**Comment by nconcetti** [comment]
commits are squashed :)

File: extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/blocking/BlockingServerInterceptor.java [hunk 3]
```diff
@@ -28,6 +28,8 @@
 import io.quarkus.grpc.runtime.Interceptors;
 import io.vertx.core.Vertx;
 
+import static javax.lang.model.SourceVersion.isKeyword;
```
Comment (geoand) [inline extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/blocking/BlockingServerInterceptor.java]: I am pretty sure we don't want this in code that runs at runtime and not build time.

**Review by geoand — CHANGES_REQUESTED** [review]

File: extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/blocking/BlockingServerInterceptor.java (hunk 3 above)
Comment (nconcetti) [reply extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/blocking/BlockingServerInterceptor.java]: im afraid there is no other way at the moment without knowing the real method name. If you mean SourceVersion specifically, i agree. That could be part of this class.

Anyway, i don't know how much use the reserved-keywords support for this interceptor is, since the extension generates mutiny stubs that are uncompilable (try with something like 'Void'). Looks like this problem could be solved in a more standardized way. What do you think?

Comment (geoand) [reply extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/blocking/BlockingServerInterceptor.java]: I think that for now we could just have a copy of the reserved keywords and be done with it

**Review by geoand — APPROVED** [review]

**Comment by nconcetti** [comment]
again, fixed code formatting for ci
