### PR TITLE
Fix server requests metrics tags for 404s when initialPath ends with /

### LINKED ISSUE #50226: Micrometer HTTP server requests metrics tags multiple URLs for 404s
### Describe the bug

The Micrometer HTTP server requests metric is supposed to capture all 404s under a generic `NOT_FOUND` URI tag to avoid cardinality explosion. However, if the not found URL ends with a trailing slash, the URL is separately tagged (with the slash removed).

This also similarly impacts the suppression of other 4xxs. If the URL responding with a 4xx ends with a trailing slash the request is not suppressed in the metrics.

### Expected behavior

All 404s are captured with the generic `NOT_FOUND` URI. Other 4xxs are always suppressed (if so configured).

### Actual behavior

Some URLs sneak through.

### How to Reproduce?

Reproducer: [quarkus-reproducer.zip](https://github.com/user-attachments/files/22487497/quarkus-reproducer.zip)

**Steps to reproduce**

1. Run the application.
2. Navigate to http://localhost:8080/foo/.
3. Navigate to http://localhost:8080/q/metrics.

**Expected result**

The request is included in the count of `NOT_FOUND` tagged URIs.

**Actual result**

A separate count is given for `uri="/foo"`:

```
http_server_requests_seconds_count{method="GET",outcome="CLIENT_ERROR",status="404",uri="/foo",} 1.0
```

### Output of `uname -a` or `ver`

Darwin Rods-MacBook-Pro.local 24.6.0 Darwin Kernel Version 24.6.0: Mon Aug 11 21:11:04 PDT 2025; root:xnu-11417.140.69.701.11~1/RELEASE_ARM64_T6031 arm64

### Output of `java -version`

openjdk version "21.0.7" 2025-04-15 OpenJDK Runtime Environment Homebrew (build 21.0.7) OpenJDK 64-Bit Server VM Homebrew (build 21.0.7, mixed mode, sharing)

### Quarkus version or git rev

3.25.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.14.1

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by brunobat**
Fixes #50226

### CODE REVIEW

**Comment by brunobat** [comment]
We should consider this for backport

File: extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/binder/HttpCommonTags.java [hunk 1]
```diff
@@ -100,6 +100,8 @@ public static Tag uri(String pathInfo, String initialPath, int code, boolean sup
 
     private static boolean isTemplatedPath(String pathInfo, String initialPath) {
         // only include the path info if it has been matched to a template (initialPath != pathInfo) to avoid a metrics explosion with lots of entries
-        return initialPath != null && !Objects.equals(initialPath, pathInfo);
+        // /not-there/ must have the same behaviour as /not-there
+        return initialPath != null && !(Objects.equals(initialPath, pathInfo) ||
+                Objects.equals(initialPath, pathInfo + "/"));
```
Comment (geoand) [inline extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/binder/HttpCommonTags.java:105]: I assume this can be done a little faster, no?

Comment (brunobat) [reply extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/binder/HttpCommonTags.java:105]: I thought about it and I actually think this might be the fastest. If I introduce an `if` to evaluate if there is a `/` at the end, it will be executed all the time, but in this case, because we have an `||`, if the left side is true, it will just return there. The special case is after the `||`

Comment (geoand) [reply extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/binder/HttpCommonTags.java:105]: 👍🏽

**Review by geoand — APPROVED** [review]
