### PR TITLE
Qute: `@EngineConfiguration` validation - consider superclasses

### LINKED ISSUE #34163: Qute section helper type check is not complete
### Describe the bug

I'm writing the following Qute section helpers:

```java
@EngineConfiguration
public class QuteCode128Code extends QuteBarCode {

    public QuteCode128Code() {
        super("code128", Barcode::code128Img);
    }
}

public abstract class QuteBarCode implements SectionHelperFactory<QuteBarCode.CustomSectionHelper> {

    @FunctionalInterface
    public static interface BarCodeEncoder {
        String encode(String value, int width, int height);
    }

    private String name;
    private BarCodeEncoder encoder;

    public QuteBarCode(String name, BarCodeEncoder encoder) {
        this.name = name;
        this.encoder = encoder;
    }

    @Override
    public List<String> getDefaultAliases() {
        return List.of(name);
    }

    @Override
    public ParametersInfo getParameters() {
        return ParametersInfo.builder()
                .addParameter(Parameter.builder("value"))
                .addParameter(Parameter.builder("size").optional())
                .addParameter(Parameter.builder("width").optional())
                .addParameter(Parameter.builder("height").optional())
                .build();
    }

    @Override
    public Scope initializeBlock(Scope outerScope, BlockInfo block) {
        Util.declareBlock(block, "value", "size", "width", "height");
        return SectionHelperFactory.super.initializeBlock(outerScope, block);
    }

    @Override
    public CustomSectionHelper initialize(SectionInitContext context) {
        Util.requireParameter(context, "value");
        // FIXME: support compile-time type-checking when Qute supports it
        Map<String, Expression> params = Util.collectExpressions(context, "value", "size", "width", "height");
        if (context.hasParameter("size")) {
            if (params.containsKey("width") || params.containsKey("height")) {
                throw new TemplateException("Cannot set both size and (width or height): choose one the others");
            }
        }
        return new CustomSectionHelper(params, encoder);
    }

    static class CustomSectionHelper implements SectionHelper {

        private Map<String, Expression> params;
        private BarCodeEncoder encoder;

        public CustomSectionHelper(Map<String, Expression> params, BarCodeEncoder encoder) {
            this.params = params;
            this.encoder = encoder;
        }

        @Override
        public CompletionStage<ResultNode> resolve(SectionResolutionContext context) {
            return Futures.evaluateParams(params, context.resolutionContext())
                    .thenApply(values -> {
                        String value = Util.typecheckValue(values, "value", String.class);
                        Integer size = Util.typecheckValue(values, "size", Integer.class, 200);
                        Integer width = Util.typecheckValue(values, "width", Integer.class, size);
                        Integer height = Util.typecheckValue(values, "height", Integer.class, size);

                        return new SingleResultNode(encoder.encode(value, width, height));
                    });
        }
    }
}
```

And I get exceptions at runtime:

```
	Suppressed: io.quarkus.qute.TemplateException: A class annotated with @EngineConfiguration must implement one of the [io.quarkus.qute.SectionHelperFactory, io.quarkus.qute.ValueResolver, io.quarkus.qute.NamespaceResolver]: io.quarkiverse.renarde.barcode.runtime.QuteCode39Code
		at io.quarkus.qute.deployment.QuteProcessor.collectEngineConfigurations(QuteProcessor.java:2121)
```

This is because the code in `QuteProcessor` only checks direct super interfaces, and mine comes from the superclass:

```java
    private static boolean isImplementorOf(ClassInfo target, DotName interfaceName) {
        for (DotName name : target.asClass().interfaceNames()) {
            if (name.equals(interfaceName)) {
                return true;
            }
        }
        return false;
    }
```

I think we should have some better subtyping rules here, no?

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mkouba**
- fixes #34163

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]

File: extensions/qute/deployment/src/main/java/io/quarkus/qute/deployment/QuteProcessor.java [hunk 1]
```diff
@@ -2196,10 +2198,19 @@ private boolean isNotTemplateLocatorImpl(AnnotationTarget locateTarget) {
...
+            for (DotName name : current.interfaceNames()) {
+                if (name.equals(interfaceName)) {
+                    return true;
+                }
+            }
+            DotName superName = current.superName();
+            if (superName != null && !superName.equals(DotName.OBJECT_NAME)) {
+                current = index.getClassByName(superName);
+            } else {
+                current = null;
```
Comment (FroMage) [inline extensions/qute/deployment/src/main/java/io/quarkus/qute/deployment/QuteProcessor.java:2213]: Well, this fixes my problem, but you're still forgetting the super-interfaces or super-interfaces. Don't we already have existing sub-typing utilities for Jandex in Quarkus? We must have, no?

**Review by FroMage — DISMISSED** [review]

File: extensions/qute/deployment/src/main/java/io/quarkus/qute/deployment/QuteProcessor.java (hunk 1 above)
Comment (mkouba) [reply extensions/qute/deployment/src/main/java/io/quarkus/qute/deployment/QuteProcessor.java:2213]: You're right. I did not think of this use case :shrug:.

> Don't we already have existing sub-typing utilities for Jandex in Quarkus? We must have, no?

I did not find anything in the io.quarkus.deployment.util.JandexUtil`...

Comment (mkouba) [reply extensions/qute/deployment/src/main/java/io/quarkus/qute/deployment/QuteProcessor.java]: Should be fixed now. The logic got extracted into the `io.quarkus.qute.deployment.Types#isImplementorOf()` method so that we could move it up if needed...

**Review by FroMage — COMMENTED** [review]
Absolutely :)
