### PR TITLE
When loading tests, check explicitly for nested classes which might have a QuarkusTest parent

### LINKED ISSUE #48781: QuarkusTests with nested classes fail when executing them with other QuarkusTests in IDEA IDE
### Describe the bug

Whenever I execute multiple Quarkustests and one of them contains nested classes in IntelliJ, the one with nested classes fails with the following message:
```
java.lang.RuntimeException: Internal error. The test class class org.acme.GreetingResourceTest should have been loaded with a QuarkusClassLoader, but instead it was loaded with jdk.internal.loader.ClassLoaders$AppClassLoader@76ed5528. This is caused by the FacadeClassLoader not correctly identifying this class as a QuarkusTest.
```

If the QuarkusTest with nested classes runs alone, all tests pass.
The same issue occurs when adding a tag to the QuarkusTest and execute it using the tag in IntelliJ.
We also experience the same issue when running the tests in Jenkins CI.

 

### Expected behavior

All QuarkusTests pass including those with nested classes when running all together.

### Actual behavior

QuarkusTests with nested classes fail when executing with other QuarkusTests in IntelliJ and Jenkins CI

### How to Reproduce?

Reproducer: [nested-quarkustest-issue-reproducer.zip](https://github.com/user-attachments/files/21060095/nested-quarkustest-issue-reproducer.zip)

Steps to reproduce:
1. Just run the run configuration "All QuarkusTests" or run all tests in IntelliJ

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

3.24.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.9.9

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by holly-cummins**
Resolves https://github.com/quarkusio/quarkus/issues/48781

When running nested tests on the CLI, or in an IDE by right-clicking on the parent class, the TCCL (`FacadeClassLoader` in our case) is only used to load the parent classes. However, when IDEA launches at the package level, it passes through a list of classes to load which includes the nested classes. These aren't correctly identified as quarkus tests, and fail. 

I've confirmed that my fix also works with more deeply nested classes:

image

### CODE REVIEW

**Review by gsmet — APPROVED** [review]
Discussed with Holly and she's fine with me merging.

File: test-framework/junit5/src/main/java/io/quarkus/test/junit/classloading/FacadeClassLoader.java [hunk 1]
```diff
@@ -344,6 +347,29 @@ public Class<?> loadClass(String name) throws ClassNotFoundException {
...
+    private boolean isQuarkusTest(Class<?> inspectionClass) throws ClassNotFoundException {
+        boolean isQuarkusAtTopLevel = AnnotationSupport.isAnnotated(inspectionClass,
+                quarkusTestAnnotation) // AnnotationSupport picks up cases where a class is annotated with an annotation which itself includes the annotation we care about
+                || registersQuarkusTestExtensionWithExtendsWith(inspectionClass)
+                || registersQuarkusTestExtensionOnField(inspectionClass);
+
+        if (isQuarkusAtTopLevel) {
+            return true;
+        } else {
+            // Normally we wouldn't loaded nested classes but when launched in an IDE at package level, they're sometimes included; make sure we identify them correctly
```
Comment (gsmet) [inline test-framework/junit5/src/main/java/io/quarkus/test/junit/classloading/FacadeClassLoader.java]: Feel free to ignore:
```suggestion
            // Normally we wouldn't load nested classes but when launched in an IDE at package level, they're sometimes included; make sure we identify them correctly
```
