### PR TITLE
Properly match paths ending with /*

### LINKED ISSUE #5318: Unexpected behavior of path matching for configuration-based security policies
If I have a permission for a path like
`quarkus.http.auth.permission.mypermission.paths=/a/*`
Then requests to `/a/anything` should be matched to it, but they are not.

If I change it to 
`quarkus.http.auth.permission.mypermission.paths=/a*`
Only then requests to `/a/anything` will start getting authorization checks.

This is contradictory to what is described in the documentation https://quarkus.io/guides/security#matching-on-paths-methods

### PR DESCRIPTION
**Pull request by jmartisk**
Fixes #5318

### CODE REVIEW

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/PathMatchingHttpSecurityPolicy.java [hunk 1]
```diff
@@ -93,7 +93,10 @@ void init(HttpBuildTimeConfig config, Map<String, Supplier<HttpSecurityPolicy>>
                     List<HttpMatcher> perms = new ArrayList<>();
                     tempMap.put(path, perms);
                     perms.add(m);
-                    if (path.endsWith("*")) {
+                    if (path.endsWith("/*")) {
```
Comment (sberyozkin) [inline extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/PathMatchingHttpSecurityPolicy.java]: The original check should be retained as well IMHO, so that the last URL segment paths can be wildcard matched, those not ending with "/"

Comment (jmartisk) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/PathMatchingHttpSecurityPolicy.java]: It is retained, it was just moved in to the `else if` branch (line 99)

**Review by sberyozkin — APPROVED** [review]

**Comment by geoand** [comment]
Is this supposed to be backported into `1.0.x`?

**Comment by sberyozkin** [comment]
@geoand Yes, let me merge it, thanks

**Comment by geoand** [comment]
Excellent, thanks!
