### PR TITLE
TransactionalUniAsserter never fails with Hibernate Reactive 

### LINKED ISSUE #36582: Unit test always succeeds in combination with hibernate-reactive & panache
### Describe the bug

I experience an unwanted behaviour in unit testing with assertions.
I've set up a fresh app via https://code.quarkus.io/
and followed the guide on https://quarkus.io/guides/hibernate-reactive-panache.
My written unit test should/must fail but succeeds nevertheless.

The following dependencies are installed for the app:
```
// Quarkus
implementation(enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}"))
implementation("io.quarkus:quarkus-arc")
testImplementation("io.quarkus:quarkus-junit5")
// Flyway
implementation("io.quarkus:quarkus-flyway")
implementation("io.quarkus:quarkus-jdbc-postgresql")
// Hibernate Reactive
implementation("io.quarkus:quarkus-hibernate-reactive-panache")
implementation("io.quarkus:quarkus-reactive-pg-client")
testImplementation("io.quarkus:quarkus-test-hibernate-reactive-panache")
```

### Expected behavior

final Animal animal = new Animal();
animal.name = "danger noodle";
asserter.execute(() -> animal.persist());
asserter.assertEquals(() -> Animal.count(), 2L); // Should already fail here!
asserter.execute(() -> Animal.deleteAll());
asserter.fail(); // Must definitely fail here!

### Actual behavior

Unit test always succeeds, even if I intentionally write a broken test.

### How to Reproduce?

Reproducer: https://github.com/sebveit/reproducer-quarkus-hibreactpanache-unittesting

Steps to reproduce the behaviour:
1. Check out the reproducer
2. Import the app into your IDE
3. Run unit test (make sure you have docker running on your sys)

### Output of `uname -a` or `ver`

Darwin Tfcbtujbo-Air.local 21.6.0 Darwin Kernel Version 21.6.0: Fri Sep 15 16:17:23 PDT 2023; root:xnu-8020.240.18.703.5~1/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "21" 2023-09-19

### Quarkus version or git rev

3.5.0.RC1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.1.1

### Additional information

------------------------------------------------------------
Gradle 8.1.1
------------------------------------------------------------

Build time:   2023-04-21 12:31:26 UTC
Revision:     1cf537a851c635c364a4214885f8b9798051175b

Kotlin:       1.8.10
Groovy:       3.0.15
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          21 (Homebrew 21)
OS:           Mac OS X 12.7 x86_64

### PR DESCRIPTION
**Pull request by DavideD**
Fix #36582

### CODE REVIEW

File: test-framework/vertx/src/main/java/io/quarkus/test/vertx/UniAsserter.java [hunk 1]
```diff
@@ -144,4 +144,9 @@ public interface UniAsserter {
      * Clear the test data.
      */
     void clearData();
+
+    /**
+     * @return a {@link Uni} representing the operations pipeline up to this point
+     */
+    Uni<?> asUni();
```
Comment (mkouba) [inline test-framework/vertx/src/main/java/io/quarkus/test/vertx/UniAsserter.java:151]: I'm not 100% sure it's a good idea to expose the current execution directly as it opens the door for "creative usage" of the API. That was the reason why the `DefaultUniAsserter` was used internally. Maybe we could introduce `AbstractUniAsserter` or something like that. But maybe I just overthink this...

**Comment by mkouba** [comment]
Ugh, so an injected `TransactionalUniAsserter` parameter actually never worked because we never subscribed to it :facepalm:. Nice catch! Thanks.

**Review by mkouba — APPROVED** [review]

**Comment by mkouba** [comment]
@DavideD pls sort the imports ;-)

File: test-framework/vertx/src/main/java/io/quarkus/test/vertx/UniAsserter.java (hunk 1 above)
Comment (DavideD) [reply test-framework/vertx/src/main/java/io/quarkus/test/vertx/UniAsserter.java:151]: I got the reasoning behind the original approach. I've decided to use the asUni because it was the fastest way to check if the fix would work. Then I lost some time figuring out how to test it and forgot about it.

I'll see if I can introduce the abstract class.

Comment (DavideD) [reply test-framework/vertx/src/main/java/io/quarkus/test/vertx/UniAsserter.java]: What about this: 3c00df9c644b0114e773315d6bf6dfa2b2e54ac5

Comment (mkouba) [reply test-framework/vertx/src/main/java/io/quarkus/test/vertx/UniAsserter.java]: Better, except that I don't understand why the name `UnwrappableAsserter`? ;-)

Comment (mkouba) [reply test-framework/vertx/src/main/java/io/quarkus/test/vertx/UniAsserter.java]: > Never question a name without suggesting a better one ;)

Ah, sorry about that ;-)

> But the idea is that the uni is wrapped by the class and this interface provide a way to unwrap it.

And do we really need an interface for this? I mean it could be a package-private abstract class or something like that...

Comment (mkouba) [reply test-framework/vertx/src/main/java/io/quarkus/test/vertx/UniAsserter.java]: For sure, but I don't think we need this flexibility at the moment... it should be a small implementation detail, not a part of the public API at all.

Comment (DavideD) [reply test-framework/vertx/src/main/java/io/quarkus/test/vertx/UniAsserter.java]: I've changed the scope to `package-private`. 
And the name to `UnwrappableUniAsserter`.

I don't plan to do any extra work on this issue (if it passes all the checks on CI).
I don't see any drawback of having an interface in this situation. But feel free to change it any way you prefer.

Comment (mkouba) [reply test-framework/vertx/src/main/java/io/quarkus/test/vertx/UniAsserter.java]: No problem. It's perfect. Thanks.

**Review by mkouba — APPROVED** [review]

**Comment by DavideD** [comment]
Uff, there are some issues with the build. I will have another look on Thursday

File: integration-tests/hibernate-reactive-panache/src/test/java/io/quarkus/it/panache/reactive/TransactionalUniAsserterTest.java [hunk 2]
```diff
@@ -18,16 +20,21 @@ public class TransactionalUniAsserterTest {
...
             assertNotNull(transaction);
             assertFalse(transaction.isMarkedForRollback());
             assertNotEquals(transaction, asserter.getData("tx"));
         });
     }
 
+    @Test
+    @RunOnVertxContext
+    public void testFailure(final TransactionalUniAsserter asserter) {
+        assertThrows(AssertionFailedError.class, asserter::fail);
```
Comment (mkouba) [inline integration-tests/hibernate-reactive-panache/src/test/java/io/quarkus/it/panache/reactive/TransactionalUniAsserterTest.java:38]: In fact, `asserter::fail` does not result in an exception. You would need to subscribe to the underlying `Uni`.

Unfortunately, JUnit5 does support the Junit4-style `@Test(expected = NullPointerException.class)`. So we can't easily assert the failure...?

Comment (DavideD) [reply integration-tests/hibernate-reactive-panache/src/test/java/io/quarkus/it/panache/reactive/TransactionalUniAsserterTest.java:38]: Ah, right. Thanks

**Comment by DavideD** [comment]
I've removed the test for now. I need to focus on another issue. But, we need to add a way to test when something fails

**Review by mkouba — APPROVED** [review]

**Comment by mkouba** [comment]
> I've removed the test for now. I need to focus on another issue. But, we need to add a way to test when something fails

It's a pity that we don't have a test that the injected `TransactionalUniAsserter` was actually used. I'll try to send a follow-up PR.
