### PR TITLE
fix(native): native image build fails when directory contains spaces

### LINKED ISSUE #2830: Native compilation again does't like spaces in project directory in 0.15.0 and 0.16.0 ver
**Describe the bug**
Native compilation doesn't like space in project directory. It is a old bug anf fixed in 0.13.0 release reference ticket no: #1673 . i am facing the samer issue with 0.15.0 and 0.16.0 releases.

**Expected behavior**
Native compilation should allow spaces in the project directory path.

**Actual behavior**
Throwing the below error
12:57:08 Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: /home/jenkins/workspace/Online%20Service%20Name%20CRP/NameService/target/NameService-0.0.1-SNAPSHOT-runner.jar (No such file or directory)
12:57:08 	at io.quarkus.undertow.runtime.graal.URLResourceSubstitution$ResourceInfo.<clinit>(URLResourceSubstitution.java:103)
12:57:08 	... 40 more
12:57:08 Caused by: java.io.FileNotFoundException: /home/jenkins/workspace/Online%20Service%20Name%20CRP/NameService/target/NameService-0.0.1-SNAPSHOT-runner.jar (No such file or directory)

**To Reproduce**
1. Create project directory name with space and execute a native compile

### PR DESCRIPTION
**Pull request by machi1990**
Fixes #2830

### CODE REVIEW

File: extensions/undertow/runtime/src/main/java/io/quarkus/undertow/runtime/graal/URLResourceSubstitution.java [hunk 1]
```diff
@@ -73,7 +75,7 @@ private void openConnection() {
             URLClassLoader ucl = (URLClassLoader) cl;
             for (URL res : ucl.getURLs()) {
                 if (res.getProtocol().equals("file") && res.getPath().endsWith(".jar")) {
-                    try (JarFile file = new JarFile(res.getPath())) {
+                    try (JarFile file = new JarFile(URLDecoder.decode(res.getPath(), StandardCharsets.UTF_8.name()))) {
```
Comment (dmlloyd) [inline extensions/undertow/runtime/src/main/java/io/quarkus/undertow/runtime/graal/URLResourceSubstitution.java]: I wonder if it would maybe be better to use `res.toUri().getPath()` instead?

Comment (machi1990) [reply extensions/undertow/runtime/src/main/java/io/quarkus/undertow/runtime/graal/URLResourceSubstitution.java]: Readability wise yes :-) I'll change it.

**Comment by machi1990** [comment]
[TCKs pipeline](https://github.com/quarkusio/quarkus/pull/2882/checks?check_run_id=151002927) failure seems unrelated.

**Comment by geoand** [comment]
I restarted the failed TCK job

**Comment by machi1990** [comment]
> I restarted the failed TCK job

Thanks. All green now.

**Review by FroMage — APPROVED** [review]
LGTM, thanks!
