### PR TITLE
Make sure OIDC issuer-based tenant resolver can recover when OIDC server becomes available after Quarkus app started

### LINKED ISSUE #42497: OIDC named tenants fail to recover when unavailable at startup
### Describe the bug

When using quarkus-oidc with named tenants and resolve-tenants-with-issuer, if an OIDC server is not available when the application starts, requests with credentials issued by that OIDC server will never succeed.

This behavior prevents an application from self-healing and requires a manual restart to return to normal operation.

Variations attempted:
- single named tenant
- multiple named tenants
- discovery-enabled=false
- connection-delay=PT2M
- connection-retry-count=999

### Expected behavior

Quarkus eventually reattempts to contact the OIDC server, and subsequent requests succeed with 200 Ok.

### Actual behavior

Quarkus never reattempts to contact the OIDC server, and all requests fail with 401 Unauthorized forever.

### How to Reproduce?

[https://github.com/segfault24/quarkus-oidc-bug/tree/main](https://github.com/segfault24/quarkus-oidc-bug/tree/main)

1. Start the application, and wait for it to become ready. It will produce warnings about the OIDC server not being available.
    ```shell script
    ./mvnw quarkus:dev
    ```
    ```
    2024-08-08 21:57:04,578 WARN  [io.qua.oid.run.OidcRecorder] (vert.x-eventloop-thread-1) Tenant 'keycloak-1': 'OIDC Server is not available'. OIDC server is not available yet, an attempt to connect will be made during the first request. Access to resources protected by this tenant may fail if OIDC server will not become available
    ...
    2024-08-08 21:57:04,647 INFO  [io.quarkus] (Quarkus Main Thread) quarkus-oidc-bug 1.0.0-SNAPSHOT on JVM (powered by Quarkus 3.13.1) started in 2.053s. Listening on: http://localhost:8080
    ```

2. In a second terminal, start the Keycloak container, and wait for it to become ready.
    ```shell script
    docker-compose up
    ```
    ```
    ...
    2024-08-08 21:57:37,093 INFO  [org.keycloak.services] (main) KC-SERVICES0032: Import finished successfully
    2024-08-08 21:57:37,228 INFO  [org.keycloak.services] (main) KC-SERVICES0009: Added user 'admin' to realm 'master'
    2024-08-08 21:57:37,295 INFO  [io.quarkus] (main) Keycloak 25.0.2 on JVM (powered by Quarkus 3.8.5) started in 7.546s. Listening on: http://0.0.0.0:8080. Management interface listening on http://0.0.0.0:9000.
    ```

3. In a third terminal, acquire an access token and make a request to the application. It will always respond with 401 Unauthorized.
    ```shell script
    ACCESS_TOKEN=$( \
        curl http://localhost:8081/realms/quarkus/protocol/openid-connect/token \
        -d "client_id=test-client" -d "username=alice" -d "password=alice" -d "grant_type=password" \
        | jq -r '.access_token')
    curl -v http://localhost:8080/hello -H "Authorization: bearer ${ACCESS_TOKEN}"
    ```

### Output of `uname -a` or `ver`

MINGW64_NT-10.0-22631 DESKTOP-REDACTED 3.4.10-87d57229.x86_64 2024-02-14 20:17 UTC x86_64 Msys

### Output of `java -version`

openjdk version "21.0.1" 2023-10-17 LTS OpenJDK Runtime Environment Corretto-21.0.1.12.1 (build 21.0.1+12-LTS) OpenJDK 64-Bit Server VM Corretto-21.0.1.12.1 (build 21.0.1+12-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.13.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.7 (8b094c9513efc1b9ce2d952b3b9c8eaedaf8cbf0) Maven home: C:\Users\austin\.m2\wrapper\dists\apache-maven-3.9.7-bin\33482774\apache-maven-3.9.7 Java version: 21.0.1, vendor: Amazon.com Inc., runtime: C:\Program Files\Amazon Corretto\jdk21.0.1_12 Default locale: en_US, platform encoding: UTF-8 OS name: "windows 11", version: "10.0", arch: "amd64", family: "windows"

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by michalvavrik**
- Closes: https://github.com/quarkusio/quarkus/issues/42497

Issuer-based tenant resolver has chicken-egg problem when static tenants are not available on startup. Before this PR, static tenants were only lazily initialized when tenant was resolved. And they leaked to the dynamic tenants. This caused me a problem in the Issuer-based tenant resolver because the original static tenants would be simply replaced (provided the issuer-based resolver could initialize it, which it could not) with dynamic tenants. The dynamic tenants are not supported for issuer-based tenant resolution. 

So, what this PR does:

- issuer-based tenant resolver tries to initialize static tenants that were not ready on application startup exactly once; because of that:
  - static tenant resolvers are moved to dedicated class (another level of abstraction solves it all :-)) because I had to switch String to Uni<String> and thought it's unnecessary to change TenantResolver interface, users don't seem to need it and issuer-based resolver is a special case
- fixes static tenants leaking into dynamic tenants; required by the issuer-based tenant resolver, because:
  - right now, if static tenant is not ready, the TenantConfigContext that represents it is left as it was and if late initialization of the static tenant context succeeds, the new one is added to the dynamic tenants; but the issuer-based resolver kept the original contexts that were never initialized; keeping polling dynamic tenants for changes is IMO bad solution, so I made sure that static tenants can be lazily initialized (switched)

### CODE REVIEW

**Comment by sberyozkin** [comment]
Hi Michal, @michalvavrik, thanks for this effort. 

I wonder if we should align it with what @snazy has tried to do around exactly the same problem, preventing leaking static tenants into  dynamic tenants ?
I had a feeling that #43110 was very close to becoming completed, with access to the dynamic map totally encapsulated in the tenant config bean.

I feel we need to fix that problem, one way or another first, too much is going on otherwise, and I'm having hard time following what is going on, sorry :-).

@snazy, do you plan to finish #43110 ? Would you like us to complete it ? I can have a look and then Michal can rebase

**Comment by michalvavrik** [comment]
> I had a feeling that https://github.com/quarkusio/quarkus/pull/43110 was very close to becoming completed

that is different solution; now that I have more insights on how it works, I can comment there if that one goes first 

> with access to the dynamic map totally encapsulated in the tenant config bean.

that is unrelated issue easy to solve, this PR only fixes what it needs to fix (static tenants)

> I feel we need to fix that problem, one way or another first, too much is going on otherwise, 

I prefer solution in this PR because #43110 keeps static tenants in concurrent map that I'll have to keep checking in the issuer-based resolver and when static tenant gets ready, I'll have to add it to that resolver either concurrent map or keep looking for it on every request for every tenant that wasn't ready on app startup.

> and I'm having hard time following what is going on, sorry :-).

If it is about this PR, please have a look again. I believe changes in this PR are easy to follow. If it is about syncing to PRs, sure, understandable.

> @snazy, do you plan to finish https://github.com/quarkusio/quarkus/pull/43110 ? Would you like us to complete it ? I can have a look and then Michal can rebase

If #43110 get merged first, this PR will require rework and I'll put the work in. It is not matter of rebasing.

**Comment by sberyozkin** [comment]
Hi Michal, like I said, I appreciate the effort, it is just too much going on here given the issue we are dealing with is the issuer-based tenant context recovery. 

And whichever way it goes, IMHO, it should be a dedicated PR dealing with the static and or dynamic maps only, nothing else, given the high sensitivity of this code. 

I have to admit, if we go with this PR first, the one will be totally out of sync. I think I'll need to pick up @snazy's PR if he os not planning to finalize it

**Comment by michalvavrik** [comment]
I don't agree with your comment, but as I already provided my arguments, let's have it your way. I'll wait.

**Comment by michalvavrik** [comment]
> I think I'll need to pick up @snazy's PR if he os not planning to finalize it. The PR @snazy did has my comment that the static map should not be concurrent.

Maybe it wasn't clear what I am saying, I'll try little comment. I am saying that https://github.com/quarkusio/quarkus/pull/43110 cannot be _close to the completion_ and has static tenants immutable. It requires different approach. I also do not wish to continue in https://github.com/quarkusio/quarkus/pull/43110 because it deals with unrelated things. This PR only handles changes required for my issue.

Considering I already commented on https://github.com/quarkusio/quarkus/pull/43110 that I am fine with waiting for @snazy implementation, I think we are not in disagreement.

**Comment by michalvavrik** [comment]
I'll convert this to draft until I am sure this PR is not going to be used (don't run CI twice), but please consider this PR on hold till #43110 is clarified or PR merged.

**Comment by sberyozkin** [comment]
Hey Michal, @michalvavrik, let me take it slowly and try to have some clarity on what is going on. Sure, I meant, I'd take on that PR, I can't just expect you doing just everything on your own :-). 
My preference would be to have this PR split in 2 PRs anyway, one - whatever is needed to accommodate the issuer-based resolver fix, the 2nd one - the actual fix.
But let me poke around in the background and see what is happening

**Comment by michalvavrik** [comment]
I am not in hurry, I'll just make it draft to make it clear. I don't see an issue.

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/StaticTenantResolver.java [hunk 1]
```diff
@@ -0,0 +1,267 @@
...
+                    if (tenantContext.ready()) {
+                        return resolveTenant(context, index + 1);
+                    }
+
+                    return tenantContext.initialize()
+                            .onItemOrFailure()
+                            .transformToUni(new BiFunction<TenantConfigContext, Throwable, Uni<? extends String>>() {
+                                @Override
+                                public Uni<String> apply(TenantConfigContext newContext, Throwable throwable) {
+                                    if (throwable != null) {
```
Comment (sberyozkin) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/StaticTenantResolver.java:176]: @michalvavrik If the context fails to initialize again here then it can continue for every request.

The same can probably happen in other cases.

Should have have a tenant config context status enum, instead of boolean, `NOT_INITIALIZED`, `INITIALIZED` and `FAILED_TO_INITIALIZE`, if it is `FAILED_TO_INITIALIZE` then we never try to re-initalize it, i.e, we only try to move from a possible  `NOT_INITIALIZED` to `INITIALIZED` only once, when trying to recover a failed context at the runtime for the first time... 

What do you think ?

**Review by sberyozkin — COMMENTED** [review]
@michalvavrik My panic after seeing a `sealed` keyword yesterday disappeared, after carefully looking at your PR, I think it is perfect. I think I can look at picking up @snazy's work related to encapsulating access to the dynamic map independently, as you also pointed out.

One minor comment remains

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/StaticTenantResolver.java (hunk 1 above)
Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/StaticTenantResolver.java:176]: Trying to recover a failed static context at runtime already makes it 2 attempts for the static context, we can't continue indefinitely, it can make a system nearly irresponsive if we have more than one unreachable static context

**Comment by michalvavrik** [comment]
>  My panic after seeing a sealed keyword yesterday disappeared, 

I must admit whenever I have opportunity I try to lower users way to implement / invoke / reach things we don't expect them to. It's not just here, in Quarkus Security and security portion of the Vert.x HTTP there has been basically everything public. The reason for this is that I think it is clearer for users. Ideally they would have API, but let's not discuss that here.

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/StaticTenantResolver.java (hunk 1 above)
Comment (michalvavrik) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/StaticTenantResolver.java:176]: >  If the context fails to initialize again here then it can continue for every request. The same can probably happen in other cases.

My thinking was that if the tenant is not supposed to get ready, why is it not disabled? And if it can get ready, we don't know when (after 5 minutes, 10 minutes). I agree , this is can be an issue.

> Should we have a tenant config context status enum, instead of boolean, NOT_INITIALIZED, INITIALIZED and FAILED_TO_INITIALIZE, if it is FAILED_TO_INITIALIZE then we never try to re-initalize it, i.e, we only try to move from a possible NOT_INITIALIZED to INITIALIZED only once, when trying to recover a failed context at the runtime for the first time...

That is alright if you believe that cannot recover later. Can this be that pod with Quarkus app spins (is scaled) exactly when IdM is not available? You could say that they should keep IdM available I guess.

What about I change `ready` flag to `enum` that you proposed but user can choose if they want to keep trying even if it failed to initialize? It will require additional property, something like `quarkus.oidc.resolve-tenants-with-issuer.retry-tenant-initialization`? Or we could provide a bean that users can define (strategy that has one method `tryToInitialize`? And default strategy would be don't try after failed initialization.

If you don't mind, I don't think that enum is required outside of the issuer-based tenant resolver. And for flag I don't need synchronization, because initialization only succeeds when is ready. I'd like to avoid enum in favor of some counter inside of the issuer-based resolver. But this is a small thing, I can do the enum if you can see other usages?

Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/StaticTenantResolver.java:176]: >My thinking was that if the tenant is not supposed to get ready, why is it not disabled? 

As far as I know, in most cases, these are test situations, or some transient initial connectivity issues.

>What about I change ready flag to enum that you proposed but user can choose if they want to keep trying even if it failed to initialize?

IMHO it is too flexible, the requests have started coming in, the system supporting the security access is either available now or not, and we don't do it for dynamic tenants. May be we can do it later for all types of tenants, keep retrying optionally...

>If you don't mind, I don't think that enum is required outside of the issuer-based tenant resolver.

Would the same be the case with any other static tenant resolver, which just returns a tenant id ? The code then will try to initialize, if it fails, the error is returned, and then it will start over from the next request...

Comment (michalvavrik) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/StaticTenantResolver.java:176]: I don't have strong opinion, but this could be difference between good feature and minor fix. Please let's try another round:

> As far as I know, in most cases, these are test situations, or some transient initial connectivity issues.

ok, so sure, the tests can be fixed with this PR without retrying

> IMHO it is too flexible, the requests have started coming in, the system supporting the security access is either available now or not, and we don't do it for dynamic tenants. May be we can do it later for all types of tenants, keep retrying optionally...

no flag, no problem. What about:

```
/**
* By default Quarkus Issuer-based tenant resolver retries just once to initialize static tenant that wasn't available on the application startup. If your OIDC server is frequently available, you can implement this interface as a CDI bean.
*/
public interface StaticTenantInitializationStrategy {
     boolean initializeTenant(String tenantId);
}
```
?

> Would the same be the case with any other static tenant resolver, which just returns a tenant id ? The code then will try to initialize, if it fails, the error is returned, and then it will start over from the next request...

I think that is different scenario. What happens now (correct me if I am wrong):

- tenant resolver selects tenants independently whether they are enabled or not; e.g. based on path or end of the path (default tenant)
- Quarkus gets selected tenant that is supposed to be initialized
- Quarkus always tries to reinitialize it, not just once or twice, always

But what issuer-based tenant resolver does is more dangerous:

- let's try to initialize this tenant in case it is the tenant with my issuer (AKA: I might not need this tenant)

So this `May be we can do it later for all types of tenants, keep retrying optionally...` doesn't fit, maybe you could elaborate how you mean it.

Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/StaticTenantResolver.java:176]: Re `StaticTenantInitializationStrategy` and the last question, re `all types of tenants`, why would we do possibly unlimited retries for those whose configuration is declared in `application.properties` but not those where the configuration is created dynamically, see what I mean ?
Also, we have never had anyone asking for this feature. Recovery, yes, but otherwise users would be getting empty screens in prod (401), tests will be failing anyway, unless they have been rewritten to loop, etc.

>Quarkus always tries to reinitialize tenant that is not ready, not just once or twice, always

Right, to be honest, I've never thought, that it would also be trying to do it, it just became obvious now :-). 

>let's try to initialize this tenant in case it is the tenant with my issuer (AKA: I might not need this tenant)

Indeed, with the issuer based resolution, a single loop can end up initializing all not-ready tenants, but all these tenants are meant to be initialized anyway, and in a busy system, it may well be concurrent

Comment (michalvavrik) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/StaticTenantResolver.java:176]: > Re StaticTenantInitializationStrategy and the last question, re all types of tenants, why would we do possibly unlimited retries for those whose configuration is declared in application.properties but not those where the configuration is created dynamically, see what I mean ?

Sorry, I don't get a point yet. The strategy is only useful for the issuer-based tenant resolver. Because we do unlimited retries for those whose configuration is declared in application.properties when some tenant resolver selects a tenant that is not ready.

> Also, we have never had anyone asking for this feature. 

Fair point.

> and in a busy system, it may well be concurrent

AFAICT not a problem


> Indeed, with the issuer based resolution, a single loop can end up initializing all not-ready tenants, but all these tenants are meant to be initialized anyway

I agree, but it seems to contradict what you try to initialize just once after failed startup initialization. Just so that it is clear, conclusion is that we should retry just once after initialization on startup failed, correct?

I can do that, just want to confirm before I start.

Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/StaticTenantResolver.java:176]: >The strategy is only useful for the issuer-based tenant resolver

But it would require us introducing a strategy specific interface, IMHO it does not really matter if this initialization attempt was attempted from the issuer based resolver ( FYI, I only referred to the concurrency to alleviate a concern that a single request may end up doing all the re-initialization) or when checking a tenant id returned from other static resolvers, or indeed, if the attempt to create a dynamic tenant fails. Dynamic tenants are not even recorded right now when the provided `OidcTenantConfig` fails to resolve, but may be they should be as non-ready as well. which is why I'm proposing to support optional unlimited init retries for all types of tenants (eventually).

IMHO if we start supporting more than 2 initialization retries for static tenants or more than 1 for dynamic ones, we should have a single option for all, and we can wait for this one to be requested.  


> We should retry just once after initialization on startup failed

IMHO we can indeed restrict it to 2 attempts for now for static tenants but as always we can enhance things further :-).

File: extensions/oidc/deployment/src/test/resources/application-dev-mode.properties [hunk 2]
```diff
@@ -9,7 +9,7 @@ quarkus.oidc.application-type=web-app
 quarkus.oidc.logout.path=/protected/logout
 quarkus.oidc.authentication.pkce-required=true
 quarkus.log.category."org.htmlunit".level=ERROR
-quarkus.log.category."io.quarkus.oidc.runtime.TenantConfigContext".level=DEBUG
+quarkus.log.category."io.quarkus.oidc.runtime.TenantConfigContextImpl".level=DEBUG
```
Comment (sberyozkin) [inline extensions/oidc/deployment/src/test/resources/application-dev-mode.properties:12]: This is totally unrelated, but I wonder, if it would be nice to  point to the interface and have all interface implementations logging ?

**Comment by sberyozkin** [comment]
@michalvavrik I'm not seeing any updates related to restricting a number of times a tenant can be tried to be initialized, did you commit them ?

File: extensions/oidc/deployment/src/test/resources/application-dev-mode.properties (hunk 2 above)
Comment (michalvavrik) [reply extensions/oidc/deployment/src/test/resources/application-dev-mode.properties:12]: np, I'll do that. To be frank, I don't know what is customary

**Comment by michalvavrik** [comment]
> @michalvavrik I'm not seeing any updates related to restricting a number of times a tenant can be tried to be initialized, did you commit them ?

I fixed it, please have a look at the issuer-based tenant resolver. I really believe it is better to avoid that enum you proposed because I don't want to synchronize things until necessary. If I have switch between INITIALIZED and FAILED_INITIALIZATION, it cannot be done without locks. but now, I am simply setting tenant context when it is ready.

**Comment by michalvavrik** [comment]
> @michalvavrik I'm not seeing any updates related to restricting a number of times a tenant can be tried to be initialized, did you commit them ?

you can recognize it also by looking at the test, I had to adjust it because previous test required multiple attempts to recover the tenant

File: extensions/oidc/deployment/src/test/resources/application-dev-mode.properties (hunk 2 above)
Comment (michalvavrik) [reply extensions/oidc/deployment/src/test/resources/application-dev-mode.properties:12]: let's wait if you require additional changes, if not, I suggest we can simply do it together with encapsulation of dynamic tenants, it will be related work that can be done quickly, especially as @snazy did most of the work already

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/StaticTenantResolver.java [hunk 3]
```diff
@@ -0,0 +1,287 @@
...
+            var tenantContext = tenantConfigContexts[index];
+            if (detectedTenantWithoutMetadata) {
+                // this is static tenant that didn't have OIDC metadata available at startup
+
+                if (tenantContext.getOidcMetadata() == null) {
+                    if (tenantContext.ready()) {
+                        return resolveTenant(context, index + 1);
+                    }
+
+                    if (!tryToInitialize(tenantContext)) {
```
Comment (michalvavrik) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/StaticTenantResolver.java:175]: @sberyozkin these are the drons you are looking for

Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/StaticTenantResolver.java:175]: Thanks @michalvavrik, I see it now.

I believe this map though should be at the `StaticTenantResolver` level, for `DynamicTenantConfigResolver#initializeStaticTenantContextIfNotReady` to be able to use it as well.
Otherwise, non-ready static tenants resolved from other static tenant resolvers will keep stressing the system

Comment (michalvavrik) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/StaticTenantResolver.java:175]: The thing is, that static tenants could keep pressing system because they were simply selected by some tenant resolver. In which case they are desired.

Comment (michalvavrik) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/StaticTenantResolver.java:175]: sorry if I am being to careful

Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/StaticTenantResolver.java:175]: Hi Michal, @michalvavrik,  one thing we definitely agree upon is that fixing it for the issuer based resolver is necessary, and indeed, let's not try to put the unrelated change into this PR by extending this restriction to all other static tenants.
I'll open another issue to handle it in another PR.

>until now, it was possible for all the static tenants to recover anytime (after 20 initialization failures, even 1000).

Yeah, but it was never intended to be more than a single init retry, I only realized it was the case while discussing the issuer based resolver with yourself here. Right now it is even more than 1000 :-), it is an indefinite number of retries across possibly a highly concurrent system. The OIDC provider might not be available at the startup, but if after another retry at the startup, it is still not available, then I think just keeping returning 401 is cheaper than failing to connect forever and returning 401.

But indeed, let's finalize this PR, thanks

**Review by sberyozkin — APPROVED** [review]
Proposing to avoid a backport due to somewhat sensitive changes

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/StaticTenantResolver.java (hunk 3 above)
Comment (michalvavrik) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/StaticTenantResolver.java:175]: > The OIDC provider might not be available at the startup, but if after another retry at the runtime, it is still not available, then I think just keeping returning 401 is cheaper than failing to connect forever and returning 401.

I agree with that and I am happy to participate on changes whether in this or about finish encapsulation of dynamic tenants or whatever is needed. I was just worried to do it here. Thanks for insights on intended behavior.
