### PR TITLE
Graceful shutdown for named messaging worker pools

### LINKED ISSUE #47237: SmallRye worker pools are not closed on shutdown
### Describe the bug

I'm debugging graceful shutdown issues in my application and I stumpled upon this piece of code in QuarkusWorkerPoolRegistry:

```java
public void terminate(
            @Observes(notifyObserver = Reception.IF_EXISTS) @Priority(100) @BeforeDestroyed(ApplicationScoped.class) Object event) {
        if (!workerExecutors.isEmpty()) {
            for (WorkerExecutor executor : workerExecutors.values()) {
                executor.close();
            }
        }
    }
```

The issue is that `executor.close()` returns a Uni, which is not subscribed to, thus not triggered. The user is warned in the documentation of this method as well:

```java
/**
   * Close the executor.
   * <p>
   * Unlike the <em>bare</em> Vert.x variant, this method returns a {@link io.smallrye.mutiny.Uni Uni}.
   * Don't forget to <em>subscribe</em> on it to trigger the operation.
   * @return the {@link io.smallrye.mutiny.Uni uni} firing the result of the operation when completed, or a failure if the operation failed.
   */
  @CheckReturnValue
  public io.smallrye.mutiny.Uni<Void> close() { 
    return io.smallrye.mutiny.vertx.AsyncResultUni.toUni(handler -> {
        delegate.close(handler);
    });
  }
```

### Expected behavior

The returned Uni is triggered and the worker pool is issued a shut down request.

### Actual behavior

The custom smallrye worker pool is not issued a shutdown request,

### How to Reproduce?

1.  Define a smallrye worker pool in application.properties (see: https://smallrye.io/smallrye-reactive-messaging/4.27.0/concepts/blocking/).
2. Use the worker pool for something.
3. Send SIGTERM to Quarkus. Debug it to see that the close operation is not triggered. I think it should trigger io.vertx.core.impl.WorkerPool#close.

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

openjdk version "17.0.2"

### Quarkus version or git rev

3.8.6, still present in main

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

apache-maven-3.9.7

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ozangunalp**
Named worker pools created for Messaging are now shut down gracefully with a timeout.

The WorkerPoolRegistry termination event is now called before (lower priority value 0) messaging connector termination (priority value 50), to allow for processed messages during the grace period to be acked.

In dev and test mode, the graceful shutdown is disabled by default by setting the grace period to 0.

Further work is needed to rationalize the config mapping for messaging. WorkerPoolConfig introduced in this PR can be transformed into a config mapping.

- Resolves: #47237

### CODE REVIEW

File: extensions/smallrye-reactive-messaging/runtime/src/main/java/io/quarkus/smallrye/reactivemessaging/runtime/QuarkusWorkerPoolRegistry.java [hunk 1]
```diff
@@ -58,19 +62,76 @@ private static Set<String> initVirtualThreadWorkers() {
...
+                            .executor();
+                    WorkerPoolConfig poolConfig = workerConfig.get(entry.getKey());
+                    long timeout = poolConfig != null ? poolConfig.shutdownTimeout().toNanos()
+                            : TimeUnit.MILLISECONDS.toNanos(DEFAULT_SHUTDOWN_TIMEOUT_MS);
+                    long interval = poolConfig != null ? poolConfig.shutdownCheckInterval().toNanos()
+                            : TimeUnit.MILLISECONDS.toNanos(DEFAULT_SHUTDOWN_CHECK_INTERVAL_MS);
+                    log.debugf("Await termination loop: %d, worker: %s, remaining: %d ns",
+                            Integer.valueOf(loop), entry.getKey(), Long.valueOf(timeout - elapsed));
+                    try {
+                        if (!innerExecutor.awaitTermination(Math.min(timeout - elapsed, interval), TimeUnit.NANOSECONDS)) {
```
Comment (cescoffier) [inline extensions/smallrye-reactive-messaging/runtime/src/main/java/io/quarkus/smallrye/reactivemessaging/runtime/QuarkusWorkerPoolRegistry.java:107]: I'm wondering if we should do that in parallel instead of sequentially.

File: extensions/smallrye-reactive-messaging/runtime/src/main/java/io/quarkus/smallrye/reactivemessaging/runtime/QuarkusWorkerPoolRegistry.java [hunk 2]
```diff
@@ -58,19 +62,76 @@ private static Set<String> initVirtualThreadWorkers() {
...
+                                innerExecutor.shutdownNow();
+                                workerExecutor.closeAndAwait();
+                            } else {
+                                terminated = false; // Still waiting
+                            }
+                        }
+                    } catch (InterruptedException e) {
+                        Thread.currentThread().interrupt();
+                        log.warnf(e, "Interrupted while waiting for worker pool %s to terminate", entry.getKey());
+                        terminated = false;
```
Comment (cescoffier) [inline extensions/smallrye-reactive-messaging/runtime/src/main/java/io/quarkus/smallrye/reactivemessaging/runtime/QuarkusWorkerPoolRegistry.java]: Should we "shutdownNow" here (in a safe manner)? As the interruption my interrupt the shutting down process.

**Review by cescoffier — APPROVED** [review]
I just wrote 2 comments, nothing major.

File: extensions/smallrye-reactive-messaging/runtime/src/main/java/io/quarkus/smallrye/reactivemessaging/runtime/QuarkusWorkerPoolRegistry.java (hunk 1 above)
Comment (ozangunalp) [reply extensions/smallrye-reactive-messaging/runtime/src/main/java/io/quarkus/smallrye/reactivemessaging/runtime/QuarkusWorkerPoolRegistry.java:107]: We do already call shutdown to all worker executors beforehand.

This is just for waiting on the termination. I think best-case and worst-case waiting times will be the same with sequentially and parallel waiting.

File: extensions/smallrye-reactive-messaging/runtime/src/main/java/io/quarkus/smallrye/reactivemessaging/runtime/QuarkusWorkerPoolRegistry.java (hunk 2 above)
Comment (ozangunalp) [reply extensions/smallrye-reactive-messaging/runtime/src/main/java/io/quarkus/smallrye/reactivemessaging/runtime/QuarkusWorkerPoolRegistry.java]: Good point, if interrupted we need to force shutdown all workers and quit the loop

**Review by cescoffier — APPROVED** [review]
