### PR TITLE
gRPC - fail the build if an unsupported client stub is injected

### LINKED ISSUE #17062: gRPC cannot inject async and ListenableFuture-style client stubs but does not fail during build
The docs is clear that quarkus gRPC can only inject _blocking_ stubs and _reactive_ stubs based on Mutiny. However, if a user attempts to inject an _async_ stub the app fails with `java.lang.NoSuchMethodError` at runtime because the generated synthetic bean implements `Contextual.create(CreationalContext<T>)` incorrectly.

I think that we should either support all types of stubs or detect a wrong injection and fail the build.

### PR DESCRIPTION
**Pull request by mkouba**
- resolves #17062
- also rename GrpcServiceBuildItem to GrpcClientBuildItem
- Mutiny generated stub now implements the MutinyStub marker interface

### CODE REVIEW

File: extensions/grpc/deployment/src/main/java/io/quarkus/grpc/deployment/GrpcClientBuildItem.java [hunk 1]
```diff
@@ -0,0 +1,81 @@
...
+                return false;
+            }
+            StubInfo other = (StubInfo) obj;
+            return Objects.equals(className, other.className);
+        }
+
+    }
+
+    public enum StubType {
+
```
Comment (michalszynkiewicz) [inline extensions/grpc/deployment/src/main/java/io/quarkus/grpc/deployment/GrpcClientBuildItem.java:66]: maybe this would be a tiny bit better
```java
        BLOCKING("newBlockingStub"),
        MUTINY("newMutinyStub");

        private final factoryMethodName;
        StubType(String factoryMethod) {
                factoryMethodName = factoryMethod;
        }

        public String getFactoryMethodName() {
                return factoryMethodName;
        }
    }
```

File: extensions/grpc/deployment/src/main/java/io/quarkus/grpc/deployment/GrpcClientProcessor.java [hunk 2]
```diff
@@ -104,62 +111,93 @@ void discoverInjectedGrpcServices(BeanDiscoveryFinishedBuildItem beanDiscovery,
...
-            if (injectionType.kind() == Type.Kind.PARAMETERIZED_TYPE) {
-                // Instance<X>
-                type = injectionType.asParameterizedType().arguments().get(0).asClassType();
-            } else {
-                // X directly
-                type = injectionType.asClassType();
+
+            // Programmatic lookup - take the param type
+            if (DotNames.INSTANCE.equals(injectionType.name()) || DotNames.INJECTABLE_INSTANCE.equals(injectionType.name())) {
+                injectionType = injectionType.asParameterizedType().arguments().get(0);
```
Comment (michalszynkiewicz) [inline extensions/grpc/deployment/src/main/java/io/quarkus/grpc/deployment/GrpcClientProcessor.java:126]: this will throw some nasty exception if someone tried to use Instance without a type, right?

Comment (michalszynkiewicz) [reply extensions/grpc/deployment/src/main/java/io/quarkus/grpc/deployment/GrpcClientProcessor.java:126]: it would be nice to have info where the wrong injection type was met

**Review by michalszynkiewicz — APPROVED** [review]

**Comment by michalszynkiewicz** [comment]
LGTM, added two minor notes

File: extensions/grpc/deployment/src/main/java/io/quarkus/grpc/deployment/GrpcClientProcessor.java (hunk 2 above)
Comment (mkouba) [reply extensions/grpc/deployment/src/main/java/io/quarkus/grpc/deployment/GrpcClientProcessor.java:126]: In fact, _"If an injection point of raw type Instance is defined, the container automatically detects the problem and treats it as a definition error."_ (5.6.1. The Instance interface) so ArC should detect this problem just before gRPC extension. I'm not sure it does. I'll check and send a separate PR if needed...

Comment (mkouba) [reply extensions/grpc/deployment/src/main/java/io/quarkus/grpc/deployment/GrpcClientProcessor.java:126]: See https://github.com/quarkusio/quarkus/pull/17109

**Review by cescoffier — APPROVED** [review]
