### PR TITLE
Make mockito parent first

### LINKED ISSUE #7854: ClassCastException running Mockito with Quarkus 1.3.0.Final
Using Mockito into @QuarkusTest, like this:
```
    @Test
    public void testHelloEndpoint() {

        HttpServletRequest request = mock(HttpServletRequest.class);
```
I got a ClassCastException:

```
﻿[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.177 s <<< FAILURE! - in net.lucamasini.testcase.ExampleResourceTest
[ERROR] testHelloEndpoint  Time elapsed: 0.677 s  <<< ERROR!
org.mockito.exceptions.base.MockitoException: 

ClassCastException occurred while creating the mockito mock :
  class to mock : 'javax.servlet.http.HttpServletRequest', loaded by classloader : 'jdk.internal.loader.ClassLoaders$AppClassLoader@6ff3c5b5'
  created class : 'org.mockito.codegen.HttpServletRequest$MockitoMock$188783148', loaded by classloader : 'net.bytebuddy.dynamic.loading.MultipleParentClassLoader@510689af'
  proxy instance class : 'org.mockito.codegen.HttpServletRequest$MockitoMock$188783148', loaded by classloader : 'net.bytebuddy.dynamic.loading.MultipleParentClassLoader@510689af'
  instance creation by : ObjenesisInstantiator

You might experience classloading issues, please ask the mockito mailing-list.

	at net.lucamasini.testcase.ExampleResourceTest.testHelloEndpoint(ExampleResourceTest.java:18)
Caused by: java.lang.ClassCastException: class org.mockito.codegen.HttpServletRequest$MockitoMock$188783148 cannot be cast to class org.mockito.internal.creation.bytebuddy.MockAccess (org.mockito.codegen.HttpServletRequest$MockitoMock$188783148 is in unnamed module of loader net.bytebuddy.dynamic.loading.MultipleParentClassLoader @510689af; org.mockito.internal.creation.bytebuddy.MockAccess is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @65f095f8)
	at net.lucamasini.testcase.ExampleResourceTest.testHelloEndpoint(ExampleResourceTest.java:18)

2020-03-13 16:53:28,727 INFO  [io.quarkus] (main) Quarkus stopped in 0.024s
```
this worked with 1.2.1.Final.

### PR DESCRIPTION
**Pull request by stuartwdouglas**
This is a stop gap measure, we need
a more extensible solution to this.

Fixes #7854

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]

**Comment by gastaldi** [comment]
It would be nice to add a test too reproducing the error in #7854

**Comment by geoand** [comment]
Tested and it works. Like @gastaldi says it would be great to have a test for mocking both `HttpServletRequest` and some application class to ensure it works in both cases (I did try it and both worked)

**Comment by gsmet** [comment]
> (I did try it and both worked)

Looks like you already did half of the work :).

**Comment by geoand** [comment]
Yeah, I can push a test to the PR if @stuartwdouglas doesn't plan to

**Comment by gastaldi** [comment]
@geoand go ahead and push a test to this PR, I think @stuartwdouglas is sleeping atm :)

**Comment by geoand** [comment]
@gastaldi done

File: integration-tests/main/src/test/java/io/quarkus/it/main/MockitoTest.java [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+import org.junit.jupiter.api.Test;
+
+import io.quarkus.test.junit.QuarkusTest;
+
+@QuarkusTest
+public class MockitoTest {
+
+    @Test
+    public void testMockHttpServletRequest() {
+        HttpServletRequest request = mock(HttpServletRequest.class);
```
Comment (gastaldi) [inline integration-tests/main/src/test/java/io/quarkus/it/main/MockitoTest.java]: How about using AssertJ like this? 

```
assertThatCode(() -> mock(HttpServletRequest.class)).doesNotThrowAnyException(); 
```

Comment (geoand) [reply integration-tests/main/src/test/java/io/quarkus/it/main/MockitoTest.java]: Thought about it, but adding AssertJ just for this didn't seem to warrant it. 
But I guess I should do it since AssertJ would provide a much better error message if mockito does start failing...

Comment (geoand) [reply integration-tests/main/src/test/java/io/quarkus/it/main/MockitoTest.java]: Done

**Review by gastaldi — APPROVED** [review]
