### PR TITLE
Suppress split package warning in Fabric8 Openshift Client

### LINKED ISSUE #19092: Split package usage for `io.fabric8:openshift-model`, `io.fabric8:openshift-model-operator`
### Describe the bug

Quarkus reports split package `io.fabric8.openshift.api.model` usage in `io.fabric8:openshift-model`, `io.fabric8:openshift-model-operator` artifacts.

```
2021-07-29 13:47:28,761 WARN  [io.qua.arc.dep.SplitPackageProcessor] (build-8) Detected a split package usage 
which is considered a bad practice and should be avoided. Following packages were detected in multiple archives: 
- "io.fabric8.openshift.api.model" found in [io.fabric8:openshift-model, io.fabric8:openshift-model-operator]
```

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

Build project with `quarkus-openshift-client` extension and check the console logs.

### Output of `uname -a` or `ver`

macOS BigSur

### Output of `java -version`

Java 11

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

Quarkus 2.1.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #19092

The first commit comes from https://github.com/quarkusio/quarkus/pull/19089, so this should be merged after that PR goes in

### CODE REVIEW

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/SplitPackageProcessor.java [hunk 1]
```diff
@@ -107,4 +138,30 @@ void splitPackageDetection(ApplicationArchivesBuildItem archivesBuildItem,
...
         }
     }
+
+    private List<Predicate<String>> initPredicates(Collection<String> exclusions) {
+        final String packMatch = ".*";
+        List<Predicate<String>> predicates = new ArrayList<>();
+        for (String exclusionExpression : exclusions) {
+            if (exclusionExpression.endsWith(packMatch)) {
+                // Package ends with ".*"
+                final String pack = exclusionExpression.substring(0, exclusionExpression.length() - packMatch.length());
```
Comment (gsmet) [inline extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/SplitPackageProcessor.java:148]: Wondering if we should make things a bit more complex. E.g. either the package should be `my.package` or it should start with `my.package.` (with a final dot). I don't think we want to catch `my.package2` and if I'm not mistaken, we catch it with what you did.

**Review by gsmet — DISMISSED** [review]

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/SplitPackageProcessor.java (hunk 1 above)
Comment (geoand) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/SplitPackageProcessor.java:148]: This comment should into the original PR :)

Comment (manovotn) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/SplitPackageProcessor.java:148]: Current way actually allows for both cases. If you really wanted to, you could filter with `my.package..*` (note the double dot) to get the behavior.
But yes, with just `my.package.*`, `my.package2` will be considered a match.
Honestly, I think we are going into enough complexity already for a configuration which has the purpose of suppressing a warning which you should have fixed and not suppressed in the first place :-)

**Review by manovotn — APPROVED** [review]

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/SplitPackageProcessor.java (hunk 1 above)
Comment (gsmet) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/SplitPackageProcessor.java:148]: Well, I disagree. The current behavior is incorrect, it needs a fix. And I don't think it will be that hard. If you're not willing to do it, I can do it.

**Review by gsmet — DISMISSED** [review]
Please don't merge this given the first commit needs rework.
