### PR TITLE
ApplyHttpGetActionPortDecorator now also sets scheme

### LINKED ISSUE #32135: Quarkus-openshift fails to properly deploy applications which use management interface
### Describe the bug

I have an application, which uses separate management interface[1] and deployed on Openshift via quarkus-openshift extension[2]. Both main and management interfaces are not accessible after deployment.

[1] https://github.com/quarkusio/quarkus/pull/30506
[2] https://quarkus.io/guides/deploying-to-openshift

### Expected behavior

Quarkus openshift extension should deploy an application is completely working state.

### Actual behavior

see below

### How to Reproduce?

1. Clone: `git clone git@github.com:fedinskiy/reproducer.git -b openshift-extension-management`
2. Create new openshift project `oc new-project fvd-test-management`
3. Deploy the app according to manual: `mvn clean install -Dquarkus.kubernetes.deploy=true -Dquarkus.openshift.route.expose=true -Dquarkus.kubernetes-client.trust-certs=true`
Log contains something like 
`[INFO] [io.quarkus.kubernetes.deployment.KubernetesDeployer] The deployed application can be accessed at: http://openshift-quickstart-fvd-test-management.apps.ocp4-12.rest.of.url`
4. Check the app
```
[fedinskiy@localhost reproducer]$ curl -v http://openshift-quickstart-fvd-test-management.apps.ocp4-12
<omitted for brevity>
> User-Agent: curl/7.85.0
< HTTP/1.0 503 Service Unavailable
```

For comparison: 

1. `oc new-project fvd-test-old`
2. `echo "" > src/main/resources/application.properties`
3. `mvn clean install -Dquarkus.kubernetes.deploy=true -Dquarkus.openshift.route.expose=true -Dquarkus.kubernetes-client.trust-certs=true`
4. The application can be accessed: ` curl http://openshift-quickstart-fvd-test-old.apps.ocp4-12<omitted>` 

### Output of `uname -a` or `ver`

6.0.18-300.fc37.x86_64

### Output of `java -version`

17.0.5, vendor: GraalVM Community

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

3.0.0.Beta1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)

### Additional information

```
$ oc version
Client Version: 4.11.0-202208020706.p0.g7075089.assembly.stream-7075089
Kustomize Version: v4.5.4
Kubernetes Version: v1.25.4+18eadca

```

### PR DESCRIPTION
**Pull request by iocanel**
Resolves: #32135

### CODE REVIEW

**Review by geoand — APPROVED** [review]

File: extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/ApplyHttpGetActionPortDecorator.java [hunk 1]
```diff
@@ -90,6 +96,12 @@ public void visit(HTTPGetActionFluent<?> action) {
         } else {
             action.withNewPort(port);
         }
+
+        if (scheme == null) {
+            action.withScheme((String) null);
+        } else {
+            action.withScheme(scheme);
+        }
```
Comment (Sgitario) [inline extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/ApplyHttpGetActionPortDecorator.java:104]: why not simply using `action.withSchema(schema)`?

Comment (geoand) [reply extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/ApplyHttpGetActionPortDecorator.java:104]: I assume because the compiler can't determine which method to call because of the missing type

Comment (gsmet) [reply extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/ApplyHttpGetActionPortDecorator.java:104]: I agree it's probably not needed by let's not block the PR for that, merging.
