### PR TITLE
WebSockets next: improve default strategies for unhandled failures

### LINKED ISSUE #42569: when/if onTextMessage throws exception connection is "quietly" closed without explanation
### Describe the bug

i had some code like this:

```java
        @OnTextMessage
        Uni<Map<String, Object>> onMessage(JsonNode msg, WebSocketClientConnection connection) {
            boolean succes = msg.get("success").asBoolean();

            logger.info("onTextMessage: " + msg + " succes: " + succes);

            if (!succes) {
                logger.error("Error from Home Assistant: " + msg.get("message").asText());
                return null;
            }
```

which i looked at for a long time to grok why I couldn't figure out why the output was just empty.

I enabled traffic logging and I got:

```posh
2024-08-15 10:06:03,400 DEBUG [io.qua.web.nex.traffic] (vert.x-eventloop-thread-0) [client] connection opened: /api/websocket, Connection[clientId=io.quarkiverse.homeassistant.runtime.HomeAssistantWS$ClientEndpoint, id=7c72217f-0b13-440f-9f7e-5e392a5cf14f], Handshake headers[]

2024-08-15 10:06:03,400 DEBUG [io.qua.web.nex.traffic] (vert.x-eventloop-thread-0) [client] received text message, Connection[clientId=io.quarkiverse.homeassistant.runtime.HomeAssistantWS$ClientEndpoint, id=7c72217f-0b13-440f-9f7e-5e392a5cf14f], Payload: 
{"type":"auth_required","ha_version":"2023.3.1"}
2024-08-15 10:06:03,401 INFO  [io.quarkus] (Quarkus Main Thread) web 1.0.0-SNAPSHOT on JVM (powered by Quarkus 3.12.2) started in 0.313s. Listening on: http://localhost:8080
2024-08-15 10:06:03,401 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2024-08-15 10:06:03,401 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, homeassistant, jfr, opentelemetry, qute, qute-web, rest, rest-client, rest-client-jackson, rest-qute, smallrye-context-propagation, vertx, websockets-next]
2024-08-15 10:06:03,401 INFO  [io.qua.dep.dev.RuntimeUpdatesProcessor] (Aesh InputStream Reader) Live reload total time: 0.342s 
2024-08-15 10:06:03,403 DEBUG [io.qua.web.nex.traffic] (vert.x-eventloop-thread-0) [client] connection closed, Connection[clientId=io.quarkiverse.homeassistant.runtime.HomeAssistantWS$ClientEndpoint, id=7c72217f-0b13-440f-9f7e-5e392a5cf14f]
```

wondering why client connection was closed I enabled full quarkus.debug logging and in between everyting was this debug log:

```
2024-08-15 10:09:13,360 DEBUG [io.qua.web.nex.run.Endpoints] (vert.x-eventloop-thread-4) Connection closed due to unhandled failure java.lang.NullPointerException: Cannot invoke "com.fasterxml.jackson.databind.JsonNode.asBoolean()" because the return value of "com.fasterxml.jackson.databind.JsonNode.get(String)" is null: WebSocket client connection [id=58fc1f2a-3e0e-4d83-abd0-8da44413ab4a, clientId=io.quarkiverse.homeassistant.runtime.HomeAssistantWS$ClientEndpoint]
```

so error was because I accidentally threw an exception by accident.

### Expected behavior

1) error printed about exception happening when calling onMessage - why should that be hidden?

2) have client traffic logging include cause/reason on errors

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mkouba**
- introduce UnhandledFailureStrategy.LOG_AND_CLOSE
- WebSocketsClientRuntimeConfig#unhandledFailureStrategy - change the default value from "close" to "log"
- WebSocketsServerRuntimeConfig#unhandledFailureStrategy - change the default value from "close" to "log-and-close"
- resolves #42569

### CODE REVIEW

**Review by geoand — APPROVED** [review]

File: extensions/websockets-next/runtime/src/main/java/io/quarkus/websockets/next/WebSocketsClientRuntimeConfig.java [hunk 1]
```diff
@@ -43,9 +43,12 @@ public interface WebSocketsClientRuntimeConfig {
...
      * The strategy used when an error occurs but no error handler can handle the failure.
      * <p>
-     * By default, the connection is closed when an unhandled failure occurs.
+     * By default, the error message is logged when an unhandled failure occurs.
+     * <p>
+     * Note that clients should not close the WebSocket connection arbitrarily. See also RFC-6455
+     * <a href="https://datatracker.ietf.org/doc/html/rfc6455#section-7.3">section 7.3</a>.
      */
-    @WithDefault("close")
+    @WithDefault("log")
```
Comment (cescoffier) [inline extensions/websockets-next/runtime/src/main/java/io/quarkus/websockets/next/WebSocketsClientRuntimeConfig.java:51]: This should be mentioned in the migration guide

**Review by cescoffier — APPROVED** [review]

File: extensions/websockets-next/runtime/src/main/java/io/quarkus/websockets/next/WebSocketsClientRuntimeConfig.java (hunk 1 above)
Comment (mkouba) [reply extensions/websockets-next/runtime/src/main/java/io/quarkus/websockets/next/WebSocketsClientRuntimeConfig.java:51]: Yes, I usually add a note in the migration guide after the PR is merged ;-).
