### PR TITLE
QuarkusComponentTest: add basic support for nested test classes

### LINKED ISSUE #46449: @QuarkusComponentTest fails on nested test classes
### Given
Quarkus version: 3.17.8
Extensions: quarkus-junit5-component

### When
Having a any CDI bean (dummy MyService used in this case) and test class like

```
@QuarkusComponentTest
class NestedComponentTest {

    @Inject
    private MyService testUnit;

    @Test
    void topLevel() {
    }

    @Nested
    class NonStaticInnerClass {

        @Test
        void nested() {
        }
    }
}

```

### Then
`java.lang.IllegalStateException: No component classes to test`

### Expected behavior

The extension should handle nested test classes, as these are often used to structure more complex test scenarios, for which especially @QuarkusComponentTest is a good candidate to reduce mocking efforts.

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mkouba**
- resolves #46449

### CODE REVIEW

**Comment by mkouba** [comment]
Test failures are very likely not related.

File: test-framework/junit5-component/src/main/java/io/quarkus/test/component/QuarkusComponentTestExtension.java [hunk 1]
```diff
@@ -404,64 +417,93 @@ private void stopContainer(ExtensionContext context, Lifecycle testInstanceLifec
...
         }
+        if (configuration.configBuilderCustomizer != null) {
+            configuration.configBuilderCustomizer.accept(configBuilder);
+        }
+        SmallRyeConfig config = configBuilder.build();
+        smallRyeConfigProviderResolver.registerConfig(config, tccl);
+        store(context).put(KEY_CONFIG, config);
+        ConfigBeanCreator.setClassLoader(tccl);
+
+        // Inject fields declated on test classes
```
Comment (manovotn) [inline test-framework/junit5-component/src/main/java/io/quarkus/test/component/QuarkusComponentTestExtension.java:498]:
```suggestion
        // Inject fields declared on test classes
```

File: test-framework/junit5-component/src/test/java/io/quarkus/test/component/nested/NestedTest.java [hunk 2]
```diff
@@ -0,0 +1,54 @@
...
+
+@QuarkusComponentTest
+@TestConfigProperty(key = "foo", value = "BAR")
+public class NestedTest {
+
+    @Inject
+    MyComponent myComponent;
+
+    @InjectMock
+    Charlie charlie;
```
Comment (manovotn) [inline test-framework/junit5-component/src/test/java/io/quarkus/test/component/nested/NestedTest.java:25]: I'd add similar injected fields into the nested class and test them as well.
(which works fine, I just want to create test coverage for it :))

**Review by manovotn — COMMENTED** [review]
Just one note WRT tests, otherwise looks good

File: test-framework/junit5-component/src/test/java/io/quarkus/test/component/nested/NestedTest.java (hunk 2 above)
Comment (mkouba) [reply test-framework/junit5-component/src/test/java/io/quarkus/test/component/nested/NestedTest.java:25]: Good idea. The reason why I didn't add them before was that I thought that having the tested components/mocks injected in the top-level class is the only reasonable use case for nested test classes I can see ;-).

Comment (mkouba) [reply test-framework/junit5-component/src/test/java/io/quarkus/test/component/nested/NestedTest.java:25]: Done.

**Review by manovotn — APPROVED** [review]
