### PR TITLE
Don't provide empty paths when using a root prefix

### LINKED ISSUE #38663: ContainerRequestContext.getUriInfo().getMatchedURIs() IndexOutOfBoundsException
### Describe the bug

See https://github.com/keycloak/keycloak/issues/26799 - Keycloak users are effectively setting the quarkus.http.root-path to a value that does not end in a slash (as documented), then when accessing that path see an IndexOutOfBoundsException

### Expected behavior

The filter logic should succeed.

### Actual behavior

ContainerRequestContext.getUriInfo().getMatchedURIs() results in an IndexOutOfBoundsException

### How to Reproduce?

- Set quarkus.http.root-path=/foo
- Install a filter that accesses getMatchedURIs():
```
    @Override
    public void filter(ContainerRequestContext requestContext, ContainerResponseContext responseContext)
            throws IOException {
        System.out.println(requestContext.getUriInfo().getMatchedURIs());
        return
    }
```
- Access /foo in the browser

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

at least versions 3.2 - 3.7

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

The logic in ResteasyReactiveRequestContext.getPathWithoutPrefix is allowed to resturn an empty string when stripping the prefix, but logic like ResteasyReactiveRequestContext.saveUriMatchState assumes that the path is at least a single character - presumably /.

### PR DESCRIPTION
**Pull request by shawkins**
There appear to be two instances where removing the prefix could result in an empty path. This pr also converts the whole ResourceLocatorTest to use the app root prefix - if that's not welcomed / needed, this can be refined further.

- Closes: #38663

### CODE REVIEW

**Review by geoand — APPROVED** [review]
🤞🏼

File: extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/test/java/io/quarkus/resteasy/reactive/server/test/resource/basic/ResourceLocatorTest.java [hunk 1]
```diff
@@ -61,6 +61,7 @@ public static void close() {
 
     @RegisterExtension
     static QuarkusUnitTest testExtension = new QuarkusUnitTest()
+            .overrideConfigKey("quarkus.http.root-path", "/app")
```
Comment (FroMage) [inline extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/test/java/io/quarkus/resteasy/reactive/server/test/resource/basic/ResourceLocatorTest.java:64]: A bit late to the party, but I worry that this will now have one less test where the path is empty. Perhaps we should have duplicated this test instead? One with path, one without?

Comment (geoand) [reply extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/test/java/io/quarkus/resteasy/reactive/server/test/resource/basic/ResourceLocatorTest.java:64]: We actually already have a version of the test in the independent project, so we should be fine

**Comment by michbeck100** [comment]
will this fix be back ported to the 3.2.x LTS version?

**Comment by michbeck100** [comment]
To make it easier I've created a PR for this: https://github.com/quarkusio/quarkus/pull/38981
