### PR TITLE
Fix issue 8254 - PanacheQuery.count() throws "unexpected token: SELECT"

### LINKED ISSUE #8254: PanacheQuery.count() throws "unexpected token: SELECT" if the query string starts with "SELECT"
HQL queries that starts with the string `SELECT` as in this
example `Order.find("select distinct o from Order o left join fetch o.lineItems");`
from https://quarkus.io/guides/hibernate-orm-panache#simplified-queries
throws the following error when the `count()` method is invoked:
```
2020-03-29 16:16:51,600 ERROR [org.hib.hql.int.ast.ErrorTracker] (executor-thread-1) line 1:17: unexpected token: SELECT
2020-03-29 16:16:51,602 ERROR [org.hib.hql.int.ast.ErrorTracker] (executor-thread-1) line 1:17: unexpected token: SELECT: line 1:17: unexpected token: SELECT
        at org.hibernate.hql.internal.antlr.HqlBaseParser.primaryExpression(HqlBaseParser.java:1009)
        at org.hibernate.hql.internal.antlr.HqlBaseParser.atom(HqlBaseParser.java:3549)
        at org.hibernate.hql.internal.antlr.HqlBaseParser.unaryExpression(HqlBaseParser.java:3401)
        at org.hibernate.hql.internal.antlr.HqlBaseParser.multiplyExpression(HqlBaseParser.java:3273)
        at org.hibernate.hql.internal.antlr.HqlBaseParser.additiveExpression(HqlBaseParser.java:2930)
        at org.hibernate.hql.internal.antlr.HqlBaseParser.concatenation(HqlBaseParser.java:615)
        at org.hibernate.hql.internal.antlr.HqlBaseParser.relationalExpression(HqlBaseParser.java:2697)
        at org.hibernate.hql.internal.antlr.HqlBaseParser.equalityExpression(HqlBaseParser.java:2558)
        at org.hibernate.hql.internal.antlr.HqlBaseParser.negatedExpression(HqlBaseParser.java:2522)
        at org.hibernate.hql.internal.antlr.HqlBaseParser.logicalAndExpression(HqlBaseParser.java:2438)
        at org.hibernate.hql.internal.antlr.HqlBaseParser.logicalOrExpression(HqlBaseParser.java:2403)
        at org.hibernate.hql.internal.antlr.HqlBaseParser.expression(HqlBaseParser.java:2116)
        at org.hibernate.hql.internal.antlr.HqlBaseParser.aliasedExpression(HqlBaseParser.java:2357)
        at org.hibernate.hql.internal.antlr.HqlBaseParser.selectedPropertiesList(HqlBaseParser.java:1390)
        at org.hibernate.hql.internal.antlr.HqlBaseParser.selectClause(HqlBaseParser.java:1300)
        at org.hibernate.hql.internal.antlr.HqlBaseParser.selectFrom(HqlBaseParser.java:1040)
        at org.hibernate.hql.internal.antlr.HqlBaseParser.queryRule(HqlBaseParser.java:748)
        at org.hibernate.hql.internal.antlr.HqlBaseParser.selectStatement(HqlBaseParser.java:319)
        at org.hibernate.hql.internal.antlr.HqlBaseParser.statement(HqlBaseParser.java:198)
        at org.hibernate.hql.internal.ast.QueryTranslatorImpl.parse(QueryTranslatorImpl.java:290)
        at org.hibernate.hql.internal.ast.QueryTranslatorImpl.doCompile(QueryTranslatorImpl.java:189)
        at org.hibernate.hql.internal.ast.QueryTranslatorImpl.compile(QueryTranslatorImpl.java:144)
        at org.hibernate.engine.query.spi.HQLQueryPlan.<init>(HQLQueryPlan.java:113)
        at org.hibernate.engine.query.spi.HQLQueryPlan.<init>(HQLQueryPlan.java:73)
        at org.hibernate.engine.query.spi.QueryPlanCache.getHQLQueryPlan(QueryPlanCache.java:155)
        at org.hibernate.internal.AbstractSharedSessionContract.getQueryPlan(AbstractSharedSessionContract.java:604)
        at org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:716)
        at org.hibernate.internal.AbstractSessionImpl.createQuery(AbstractSessionImpl.java:23)
        at io.quarkus.hibernate.orm.runtime.entitymanager.TransactionScopedEntityManager.createQuery(TransactionScopedEntityManager.java:317)
        at io.quarkus.hibernate.orm.runtime.entitymanager.ForwardingEntityManager.createQuery(ForwardingEntityManager.java:142)
        at io.quarkus.hibernate.orm.panache.runtime.PanacheQueryImpl.count(PanacheQueryImpl.java:119)
        at org.acme.hibernate.orm.panache.FruitResource.count(FruitResource.java:38)
        at org.acme.hibernate.orm.panache.FruitResource_ClientProxy.count(FruitResource_ClientProxy.zig:114)
```

I've created a reproducer by changing two files in hibernate-orm-panache-quickstart

Added a resource that attempts to invoke `count()`
https://github.com/sirf/quarkus-quickstarts/blob/master/hibernate-orm-panache-quickstart/src/main/java/org/acme/hibernate/orm/panache/FruitResource.java#L31

Added a (failing) test case
https://github.com/sirf/quarkus-quickstarts/blob/master/hibernate-orm-panache-quickstart/src/test/java/org/acme/hibernate/orm/panache/FruitsEndpointTest.java#L14

### PR DESCRIPTION
**Pull request by sirf**
Fixes https://github.com/quarkusio/quarkus/issues/8254

Queries like these
`select distinct o from Order o left join fetch o.lineItems`
are translated into
`SELECT COUNT(*) select distinct o from Order o left join fetch o.lineItems`
when `PanacheQuery.count()` is invoked which clearly is not valid syntax.

This change will result in a query that looks like this:
`SELECT COUNT(distinct o) from Order o left join fetch o.lineItems`

Works with SELECT and SELECT DISTINCT.

### CODE REVIEW

**Review by FroMage — CHANGES_REQUESTED** [review]
LGTM but could you add a test for both cases please?

**Comment by FroMage** [comment]
And also squash all commits into one.

**Comment by FroMage** [comment]
Mmm, I'm not sure what to think of this. All tests are normally done in the `quarkus-integration-test-hibernate-orm-panache` module with real queries and not unit tests like this.
On the other hand this is probably faster, but spreads the tests.

**Comment by sirf** [comment]
That's cool.
I'll write an integration test and delete the current test.

**Review by FroMage — APPROVED** [review]
Sorry this is horrible, you should refactor `Cat` to be `Dog`, we can't accept cats in our code.

Just kidding, this is great, thanks a lot!

**Comment by FroMage** [comment]
Let me know when the CI passes and I'll merge it.

File: extensions/panache/hibernate-orm-panache/runtime/src/main/java/io/quarkus/hibernate/orm/panache/runtime/PanacheQueryImpl.java [hunk 1]
```diff
@@ -153,6 +158,9 @@ public long count() {
     }
 
     protected String countQuery() {
+        Matcher selectMatcher = SELECT_PATTERN.matcher(query);
+        if (selectMatcher.matches())
+            return "SELECT COUNT(" + selectMatcher.group(1) + ") " + selectMatcher.group(2);
```
Comment (gastaldi) [inline extensions/panache/hibernate-orm-panache/runtime/src/main/java/io/quarkus/hibernate/orm/panache/runtime/PanacheQueryImpl.java]:
```suggestion
        if (selectMatcher.matches()) {
            return "SELECT COUNT(" + selectMatcher.group(1) + ") " + selectMatcher.group(2);
        }
```
