### PR TITLE
Fix regression with locationPackages paths on Windows

### LINKED ISSUE #26831: Windows paths not escaped in DevUI
### Describe the bug

On Windows when the DevUI renders the template [main.html](https://github.com/quarkusio/quarkus/blob/91ba39965d13652e853446e227b256a1b8cea477/extensions/vertx-http/deployment/src/main/resources/dev-templates/main.html) the path are not properly escaped leading to the page not being able to be used as JavaScript is broken.

The code [here](https://github.com/quarkusio/quarkus/blob/91ba39965d13652e853446e227b256a1b8cea477/extensions/vertx-http/deployment/src/main/resources/dev-templates/main.html#L146-L150) takes the paths as is and put them into the HTML, leading to the following error `provider:594 Uncaught SyntaxError: Invalid Unicode escape sequence (at provider:594:70)`.

### Expected behavior

The paths should be properly escaped using `\\` for path separators on Windows.

### Actual behavior

It lead to the JavaScript error:
`provider:594 Uncaught SyntaxError: Invalid Unicode escape sequence (at provider:594:70)`

### How to Reproduce?

Create/move a project into a path where the directory would start with an invalid Unicode character i.e. `c:\userproject`.

I have created and uploaded a sample project to Github as a sample:
https://github.com/bwolkerstorfer/sample-quarkus-path-issue

Steps:
1. run the project on Windows using `gradle quarkusDev`
2. navigate to i.e. http://localhost:8080/q/dev/io.quarkus.quarkus-oidc/provider
3. check the JS console

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.10.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

------------------------------------------------------------ Gradle 7.5 ------------------------------------------------------------  Build time:   2022-07-14 12:48:15 UTC Revision:     c7db7b958189ad2b0c1472b6fe663e6d654a5103  Kotlin:       1.6.21 Groovy:       3.0.10 Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021 JVM:          17.0.3 (Eclipse Adoptium 17.0.3+7) OS:           Windows 11 10.0 amd64

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by dt-bwolkerstorfer**
Fixes a regression that was introduced through [commit f7b28fa0](https://github.com/quarkusio/quarkus/commit/f7b28fa018886921ab1f2229ea73732a4cdd79df#diff-5d886c297bbf81799a7e65ae5aec5de0966e6a5dbe06641a569a7c5afa0cf5b1L893) where the replacement of backslashes for to forward slashes in Windows paths.

fixes #26831

### CODE REVIEW

File: extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/devmode/console/DevConsoleProcessor.java [hunk 1]
```diff
@@ -940,7 +940,7 @@ public Object apply(EvalContext ctx) {
                 for (Path sourcePaths : sourcesDir) {
                     List<String> packages = sourcePackagesForRoot(sourcePaths);
                     if (!packages.isEmpty()) {
-                        sourcePackagesByDir.put(sourcePaths.toAbsolutePath().toString(), packages);
+                        sourcePackagesByDir.put(sourcePaths.toAbsolutePath().toString().replace("\\", "/"), packages);
```
Comment (gsmet) [inline extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/devmode/console/DevConsoleProcessor.java:943]: So somehow when we consume the keys from the Map, we have `/` in the paths even on Windows? Do you have handy the place where this is consumed?

Comment (bwolkerstorfer) [reply extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/devmode/console/DevConsoleProcessor.java:943]: The map is consumed in the `main.html` ([here](https://github.com/quarkusio/quarkus/blob/main/extensions/vertx-http/deployment/src/main/resources/dev-templates/main.html#L147-L152)) and subsequently used by the JS function `openInIde` later in that HTML.

Depending on the IDE type used the call either tries set a `window.location` (for `client` type IDEs) or it invokes the server (for `server` type IDEs) using AJAX where the call ends up in [OpenIdeHandler.java](https://github.com/quarkusio/quarkus/blob/main/extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/devmode/console/OpenIdeHandler.java).

The path is actually not relevant for the `server` type IDEs since only the fully-qualified class name is sent to the server which the resolves a proper path for the OS anyway.

As for the `client` type IDEs, it seems that only _vscode_ is currently supported and there the path pattern `vscode://file/{0}:{1}` is used and it uses internal also forward slash to specify paths on windows (i.e. `vscode-file://vscode-app/c:/Users/ExampleUser/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/workbench.html`).

The open IDE flow can be tested when running the DEVUI locally on the ArC Beans page (http://localhost:8080/q/dev/io.quarkus.quarkus-arc/beans) by clicking the link underneath a user-defined bean.

**Review by gsmet — APPROVED** [review]
