### PR TITLE
Fix Smallrye OpenApi CORS when http path is not attached to main router

### LINKED ISSUE #26296: CORS response headers not present with quarkus.http.non-application-root-path
### Describe the bug

When using `quarkus.http.root-path` and `quarkus.http.non-application-root-path` to customize the location of REST endpoints (not `/`), but keeping the non-application endpoints (`/openapi`, etc.) available at `/q`, the CORS filter is not executed for the non-application endpoint calls.

Example config:
```
quarkus.http.cors=true
quarkus.http.root-path=/api
quarkus.http.non-application-root-path=/q
```

Making an HTTP request to `/api/hello` will return CORS response headers;  a request to `/q/openapi` will not.

If the non-application root path is changed to not have a leading `/`, then the CORS headers are available, but the `q` path is now available at `/api/q`.

### Expected behavior

CORS headers should be available (when CORS enabled and Origin header present in requests) for non-application endpoints if the root path has been customized.

### Actual behavior

No CORS headers are present.

### How to Reproduce?

[code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/8958794/code-with-quarkus.zip)

1. Run in dev mode (./mvnw clean compile quarkus:dev)
2. `curl --head -H "Origin: https://www.google.com" localhost:8080/api/hello`
3. Note the response has the `access-control-allow-origin` and `access-control-allow-credentials` headers
4. `curl --head -H "Origin: https://www.google.com" localhost:8080/q/openapi`
5. Note the response does not have and CORS related headers returned
6. Change `quarkus.http.non-application-root-path` to `q`
7. Repeat step 2, note same results as step 3
8. `curl --head -H "Origin: https://www.google.com" localhost:8080/api/q/openapi`
9. Note the CORS headers are present in the response

### Output of `uname -a` or `ver`

Linux laverne 5.13.0-44-generic #49~20.04.1-Ubuntu SMP Wed May 18 18:44:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.15" 2022-04-19 OpenJDK Runtime Environment (build 11.0.15+10-Ubuntu-0ubuntu0.20.04.1) OpenJDK 64-Bit Server VM (build 11.0.15+10-Ubuntu-0ubuntu0.20.04.1, mixed mode, sharing)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.9.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537) Maven home: /home/nde/.m2/wrapper/dists/apache-maven-3.8.4-bin/52ccbt68d252mdldqsfsn03jlf/apache-maven-3.8.4 Java version: 11.0.15, vendor: Private Build, runtime: /usr/lib/jvm/java-11-openjdk-amd64 Default locale: en_US, platform encoding: UTF-8 OS name: "linux", version: "5.13.0-44-generic", arch: "amd64", family: "unix"

### Additional information

This problem exists since at least 2.7.5.Final.

### PR DESCRIPTION
**Pull request by michalvavrik**
fixes: #26296

When non-application root path is not underneath the HTTP root path, filters (such as authorization, authentication, cors) are not applied. That lead to situation when user had to expose his OpenApi endpoints on application root in order to have (non-default) CORS headers. However current implementation expected CORS filter to be applied when CORS are enabled (please see comment https://github.com/quarkusio/quarkus/blob/main/extensions/smallrye-openapi/runtime/src/main/java/io/quarkus/smallrye/openapi/runtime/OpenApiHandler.java#L78). I don't want to attach SmallRye OpenApi routes to http route router by default is that would defy documented behavior https://quarkus.io/guides/all-config#quarkus-vertx-http_quarkus.http.non-application-root-path.

This PR adds CORS filter to (and only to) SmallRye OpenApi routes when CORS are enabled and path is not attached to main router. `autoSecurityFilter` is registered as bean in a separate build step in order to avoid cycle.

### CODE REVIEW

**Comment by michalvavrik** [comment]
cc @sberyozkin

**Comment by michalvavrik** [comment]
Failing test is not related (it's Jandex issue, QE also experienced Jandex issues in our tests): _Build step io.quarkus.deployment.steps.ApplicationIndexBuildStep#build threw an exception: java.lang.NoSuchMethodError: 'void org.jboss.jandex.Indexer.index(java.io.InputStream)'_

**Review by phillip-kruger — APPROVED** [review]
LGTM

**Comment by geoand** [comment]
Let's also get the blessing of @sberyozkin on this :)

**Review by ebullient — APPROVED** [review]

**Comment by sberyozkin** [comment]
Oops, apologies, looking now

**Comment by michalvavrik** [comment]
np @sberyozkin :-) you are busy

File: extensions/smallrye-openapi/deployment/src/test/java/io/quarkus/smallrye/openapi/test/vertx/OpenApiDefaultPathTestCase.java [hunk 1]
```diff
@@ -34,4 +34,20 @@ public void testOpenApiPathAccessResource() {
                 .body("info.title", Matchers.equalTo("quarkus-smallrye-openapi-deployment API"))
                 .body("paths", Matchers.hasKey("/resource"));
     }
+
+    @Test
+    public void testDisabledCors() {
```
Comment (sberyozkin) [inline extensions/smallrye-openapi/deployment/src/test/java/io/quarkus/smallrye/openapi/test/vertx/OpenApiDefaultPathTestCase.java:39]:
```suggestion
    public void testDefaultOpenApiCorsProperties() {
```

File: extensions/smallrye-openapi/deployment/src/test/java/io/quarkus/smallrye/openapi/test/vertx/OpenApiHttpRootDefaultPathTestCase.java [hunk 2]
```diff
@@ -36,4 +37,17 @@ public void testOpenApiPathAccessResource() {
                 .body("info.title", Matchers.equalTo("quarkus-smallrye-openapi-deployment API"))
                 .body("paths", Matchers.hasKey("/foo/resource"));
     }
+
+    @Test
+    public void testEnabledCors() {
```
Comment (sberyozkin) [inline extensions/smallrye-openapi/deployment/src/test/java/io/quarkus/smallrye/openapi/test/vertx/OpenApiHttpRootDefaultPathTestCase.java:42]:
```suggestion
    public void testCorsFilterProperties() {
```

File: extensions/smallrye-openapi/deployment/src/test/java/io/quarkus/smallrye/openapi/test/vertx/OpenApiHttpRootPathCorsTestCase.java [hunk 3]
```diff
@@ -0,0 +1,34 @@
...
+    @RegisterExtension
+    static QuarkusUnitTest runner = new QuarkusUnitTest()
+            .withApplicationRoot((jar) -> jar
+                    .addClasses(OpenApiRoute.class)
+                    .addAsResource(new StringAsset("quarkus.http.cors=true\n" +
+                            "quarkus.http.non-application-root-path=/api/q\n" +
+                            "quarkus.http.root-path=/api"), "application.properties"));
+
+    @Test
+    public void testEnabledCors() {
```
Comment (sberyozkin) [inline extensions/smallrye-openapi/deployment/src/test/java/io/quarkus/smallrye/openapi/test/vertx/OpenApiHttpRootPathCorsTestCase.java:22]:
```suggestion
    public void testCorsFilterProperties() {
```

**Comment by sberyozkin** [comment]
@michalvavrik We all are :-), I just don't get why I get some notifications and why not, it is happening all the time.

In any case, sorry for the delay and thanks for continuing picking up tricky security issues :-)
I've only proposed to change the test names as I got confused initially and could not figure where those properties in a  `disabledCors` test were coming from :-). Please rename if you agree, but not critical, thanks

**Review by sberyozkin — APPROVED** [review]

**Comment by michalvavrik** [comment]
Renamed tests looked better, thank you, done.
