### PR TITLE
Fix the messaging codestarts

### LINKED ISSUE #23018: No messages emitted on start of smallrye-reactive-messaging-kafka codestart in dev mode
### Describe the bug

No messages emitted on start with `smallrye-reactive-messaging-kafka` codestart in dev mode.

I had to adjust JAX-RS endpoint to inject `MyReactiveMessagingApplication` and invoke the method with emitter as part of endpoint call. When I accessed the endpoint I finally saw the log messages with the upper-case text.

Application code: https://github.com/quarkusio/quarkus/blob/main/devtools/project-core-extension-codestarts/src/main/resources/codestarts/quarkus/extension-codestarts/reactive-messaging-codestart/java/src/main/java/org/acme/MyReactiveMessagingApplication.java#L19

In the log I noticed new lines just before the upper-case prints:
```
2022-01-19 16:55:03,870 INFO  [io.sma.rea.mes.kafka] (vert.x-eventloop-thread-0) SRMSG18256: Initialize record store for topic-partition 'word-0' at position -1.
2022-01-19 16:55:03,886 INFO  [io.sma.rea.mes.kafka] (vert.x-eventloop-thread-1) SRMSG18256: Initialize record store for topic-partition 'uppercase-word-0' at position -1.
```

Seems that kafka dev service is not fully or properly initialized to handle messages sent from `onStart` method

This behaviour is quite confusing and it took me some time to figure out that the code flow in `MyReactiveMessagingApplication` is correct and the problem is with message sending.

CC @cescoffier 

### Expected behavior

```
>> HELLO
>> WITH
>> SMALLRYE
>> REACTIVE
>> MESSAGE
```
gets printed on boot in dev mode

### Actual behavior

Upper-case text is not printed

### How to Reproduce?

 - Select quarkus-resteasy-reactive and quarkus-smallrye-reactive-messaging-kafka on https://code.quarkus.io/
 - Download the app and run `mvn quarkus:dev`

### Output of `uname -a` or `ver`

macOS Monterey

### Output of `java -version`

Java 17

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.6.2.Final and Quarkus main

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by cescoffier**
They could not work as they were implemented.
This PR simplifies the app and config and remove the MQTT code start.

Fix https://github.com/quarkusio/quarkus/issues/23018

### CODE REVIEW

**Review by maxandersen — APPROVED** [review]
tested both and I at least see the messages in the console.

I would have expected at least some mention in the readme on what class to go look in like resteasy gives link to the right URL.

But that can be done/improved seperately.

File: integration-tests/devtools/src/test/resources/__snapshots__/ReactiveMessagingCodestartIT/testKafkaContent/src_test_java_ilove_quark_us_MyReactiveMessagingApplicationTest.java [hunk 1]
```diff
@@ -3,57 +3,25 @@
...
-
 import static org.junit.jupiter.api.Assertions.assertEquals;
-import static org.junit.jupiter.api.Assertions.assertTrue;
 
 @QuarkusTest
-@QuarkusTestResource(MyReactiveMessagingApplicationTest.InMemoryChannelTestResource.class)
 class MyReactiveMessagingApplicationTest {
 
     @Inject
     @Any
```
Comment (rsvoboda) [inline integration-tests/devtools/src/test/resources/__snapshots__/ReactiveMessagingCodestartIT/testKafkaContent/src_test_java_ilove_quark_us_MyReactiveMessagingApplicationTest.java:19]: @cescoffier any reason for `@Any` annotation here?
