### PR TITLE
Fix augmentors called multiple times for each identity provider

### LINKED ISSUE #42600: `SecurityIdentityAugmentor` are called multiple times with multiple identityProviders
### Describe the bug

With quarkus security, when multiple `IdentityProvider` are present and they return a `nullitem`  the SecurityIdentityAugmentors will be called once per IdentityProvider  that where called.

### Expected behavior

If an identity provider returns a null item, it should not re trigger an augmentation. The augmentor should be called only once.

### Actual behavior

_No response_

### How to Reproduce?

[https://github.com/Malandril/quarkus-bug-augment](https://github.com/Malandril/quarkus-bug-augment)

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

 #42599 with fix

### PR DESCRIPTION
**Pull request by Malandril**
Fixes #42600.

When multiple `IdentityProvider` are present and they return a `nullitem`  the SecurityIdentityAugmentors will be called once per IdentityProvider  that where called.

It is caused by the Uni transforming the SecurityIdentity for each called `IdentityProvider`.

### CODE REVIEW

**Comment by sberyozkin** [comment]
I doubt it is a valid PR, please see the comments in the issue

File: extensions/security/runtime/src/main/java/io/quarkus/security/runtime/QuarkusIdentityProviderManagerImpl.java [hunk 1]
```diff
@@ -127,6 +127,9 @@ public Uni<SecurityIdentity> apply(SecurityIdentity securityIdentity) {
                         return handleProvider(pos + 1, providers, request);
                     }
                 });
+        if (pos > 0) {
```
Comment (michalvavrik) [inline extensions/security/runtime/src/main/java/io/quarkus/security/runtime/QuarkusIdentityProviderManagerImpl.java:130]: this would be easier to understand if you extracted recursion to dedicated method and dropped `if`

**Comment by michalvavrik** [comment]
> I doubt it is a valid PR, please see the comments in the issue

I think it's fine, but `if` is not really helping because it takes little thinking to figure why is it there. I am off for the first half of the next week, so I won't review.

File: extensions/security/runtime/src/main/java/io/quarkus/security/runtime/QuarkusIdentityProviderManagerImpl.java (hunk 1 above)
Comment (michalvavrik) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/QuarkusIdentityProviderManagerImpl.java:130]: meaning: lines 114-129

**Comment by sberyozkin** [comment]
Yeah, I removed my comment

**Review by sberyozkin — APPROVED** [review]
Sorry for a delay, LGTM, @michalvavrik, please review as well

**Review by michalvavrik — APPROVED** [review]
Yep, that's what I had in mind. Thank you @Malandril for good catch and fix, changes LGTM

**Comment by michalvavrik** [comment]
I think we need more CI runs, not sure why they got cancelled, but worth retriggering.

**Comment by sberyozkin** [comment]
@Malandril Can you please rebase your PR against the upstream main branch ?

**Review by michalvavrik — APPROVED** [review]
