### PR TITLE
Init Quartz with the correct CL

### LINKED ISSUE #11017: Quartz - scheduling jobs programmatically fails when running from IDE
**Describe the bug**
Execution of "SCHEDULING PERIODIC TASKS WITH QUARTZ" Guide fails when MyJob is fired after job creation is done correctly.  

**Expected behavior**
Trigger calls MyJob method "performTask()" and persist a new Task.

**Actual behavior**
When it comes to fire MyJob execution, it throws IllegalStateException:  Job class must implement the Job interface.

**To Reproduce**
Code to reproduce (as  [Quarz Guide](https://quarkus.io/guides/quartz) )
```
import io.quarkus.arc.Arc;
import io.quarkus.hibernate.orm.panache.PanacheEntity;
import io.quarkus.runtime.Quarkus;
import io.quarkus.runtime.StartupEvent;
import io.quarkus.runtime.annotations.QuarkusMain;
import org.quartz.*;

import javax.enterprise.context.ApplicationScoped;
import javax.enterprise.event.Observes;
import javax.inject.Inject;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.transaction.Transactional;
import java.time.Instant;

@QuarkusMain
public class Main {

    public static void main(String[] args) {
        Quarkus.run(args);
    }


    @Entity
    @Table(name = "TASKS")
    static class Task extends PanacheEntity {
        public Instant createdAt;

        public Task() {
            createdAt = Instant.now();
        }

        public Task(Instant time) {
            this.createdAt = time;
        }
    }

    @ApplicationScoped
     static class TaskBean {

        @Inject
        private Scheduler quartz;

        void onStart(@Observes StartupEvent event) throws SchedulerException {
            JobDetail job = JobBuilder.newJob(MyJob.class)
                    .withIdentity("myJob", "myGroup")
                    .build();
            Trigger trigger = TriggerBuilder.newTrigger()
                    .withIdentity("myTrigger", "myGroup")
                    .startNow()
                    .withSchedule(
                            SimpleScheduleBuilder.simpleSchedule()
                                    .withIntervalInSeconds(10)
                                    .repeatForever())
                    .build();
            quartz.scheduleJob(job, trigger);
        }

        @Transactional
        void performTask() {
            Task task = new Task();
            task.persist();
        }

        // A new instance of MyJob is created by Quartz for every job execution
        static class MyJob implements Job {

            public void execute(JobExecutionContext context) throws JobExecutionException {
                Arc.container().instance(TaskBean.class).get(). performTask();
            }

        }
    }
}

````

SQL database generation: [link](https://github.com/quarkusio/quarkus-quickstarts/blob/master/quartz-quickstart/src/main/resources/db/migration/V2.0.0__QuarkusQuartzTasks.sql)

**Configuration**
```
quarkus.quartz.store-type=jdbc-cmt
quarkus.quartz.clustered=true
quarkus.quartz.force-start=true

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=password
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost/db

quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.sql-load-script=no-file

quarkus.flyway.connect-retries=10
quarkus.flyway.table=flyway_quarkus_history
quarkus.flyway.migrate-at-start=true
quarkus.flyway.baseline-on-migrate=true
quarkus.flyway.baseline-version=1.0
quarkus.flyway.baseline-description=Quartz
```

**Screenshots**
Screenshot

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
Microsoft Windows [Versione 10.0.18363.959]

 - Output of `java -version`: 
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)

 - Quarkus version or git rev: 
Quarkus 1.6.1.FINAL

 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\Program Files\apache-maven\bin\..
Java version: 1.8.0_201, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk1.8.0_201\jre
Default locale: it_IT, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Additional context**
Runned with:
```
docker run --name some-postgres -e POSTGRES_PASSWORD=password -e POSTGRES_USER=postgres -e POSTGRES_DB=db -d  -p 5432:5432 postgres:alpine
```

### PR DESCRIPTION
**Pull request by stuartwdouglas**
Make sure Quartz captures the Runtime ClassLoader
on startup and uses it to load job classes.

Fixes #11017

### CODE REVIEW

File: extensions/quartz/deployment/src/main/java/io/quarkus/quartz/deployment/QuartzProcessor.java [hunk 1]
```diff
@@ -135,6 +135,8 @@ private String guessDriver(Optional<JdbcDataSourceBuildItem> jdbcDataSource) {
         reflectiveClasses.add(new ReflectiveClassBuildItem(true, false, SimpleInstanceIdGenerator.class.getName()));
         reflectiveClasses.add(new ReflectiveClassBuildItem(false, false, CascadingClassLoadHelper.class.getName()));
```
Comment (mkouba) [inline extensions/quartz/deployment/src/main/java/io/quarkus/quartz/deployment/QuartzProcessor.java:136]: This line is now useless, or?

**Review by mkouba — COMMENTED** [review]
Added one minor comment. Othewise looks good. Thanks Stuart!

**Comment by mkouba** [comment]
Nice PR number by the way ;-)

**Review by machi1990 — COMMENTED** [review]
Thanks @stuartwdouglas

**Comment by mkouba** [comment]
For the record - I've just tested @bobanbg's reproducer with this PR and running the `@QuarkusMain` from Eclipse IDE works fine...

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Merging this one to include it in the CR1.
