### PR TITLE
Provide a way to observe security events

### LINKED ISSUE #26549: SPI for performed authorization checks
### Description

It would be nice if Quarkus had some kind of callback mechanism which would allow registering a listener which would be notified when an authorization check either failed or succeeded. An application could use this to implement a custom security logging mechanism.

Currently, this is not so simple, because depending on whether the authorization rules are declared using annotations (`@RolesAllowed` et al.) or config properties (`quarkus.http.auth.*`) and depending on whether the outcome of the check was "allow" or "deny", different hooks need to be used, which could possibly also conflict with other uses of those hooks.

### Implementation ideas

One idea would be to fire CDI events with the details.

### PR DESCRIPTION
**Pull request by michalvavrik**
closes: #26549

### CODE REVIEW

File: extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/AuthorizationEvent.java [hunk 1]
```diff
@@ -0,0 +1,63 @@
...
+    }
+
+    public Exception getAuthZFailureException() {
+        return (Exception) eventProperties.get(AUTHORIZATION_FAILURE_EX_KEY);
+    }
+
+    /**
+     * @return name of a class that performed check
+     */
+    public String getCheckerClassName() {
```
Comment (sberyozkin) [inline extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/AuthorizationEvent.java:39]: I'm not sure it can help a lot, may be lets drop it for now and add if someone asks ? IMHO it is worth starting with the minimalistic API

Comment (michalvavrik) [reply extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/AuthorizationEvent.java:39]: But if there is a failure and `RoutingContext` is not available in every single case (thought I did my best to have it available, together with CDI injection it should cover most of it), wouldn't you like to find out what authorization check failed?

That said, the name is bad, I know it. @sberyozkin would you be fine with putting it as event properties map item? also please suggest name, something like `FAILED_CHECK_CLASS_NAME`, not sure. It's valuable information.

Comment (michalvavrik) [reply extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/AuthorizationEvent.java:39]: I mean putting it to map instead of `getCheckerClassName`.

File: extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/AuthenticationEvent.java [hunk 2]
```diff
@@ -0,0 +1,36 @@
+package io.quarkus.security.spi.runtime;
+
+import java.util.HashMap;
+import java.util.Map;
+
+import io.quarkus.security.identity.SecurityIdentity;
+
+public class AuthenticationEvent implements SecurityEvent {
```
Comment (sberyozkin) [inline extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/AuthenticationEvent.java:8]: This event (as well as the authorization one), can it be used to indicate the authentication or authorization has succeeded ? IMHO it is should be supported too

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpAuthenticator.java [hunk 3]
```diff
@@ -93,25 +101,35 @@ public Uni<SecurityIdentity> attemptAuthentication(RoutingContext routingContext
...
+                            return createSecurityIdentity(routingContext);
                         }
-                        return createSecurityIdentity(routingContext);
-                    }
-
-                });
 
+                    });
+        }
+        if (fireAuthenticationEvent) {
```
Comment (sberyozkin) [inline extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpAuthenticator.java:123]: Probably makes sense to fire for positive results too

File: docs/src/main/asciidoc/security-customization.adoc [hunk 4]
```diff
@@ -620,6 +620,51 @@ are using an executor that is capable of propagating the identity (e.g. no `Comp
...
+
+    void observeAsync(@ObservesAsync SecurityEvent event) {         <4>
+        Map<String, Object> eventProperties = event.getEventProperties();
+    }
+}
+----
+<1> This observer will be notified with all the security events.
+<2> The `AuthenticationEvent` event is fired whenever authentication failed.
+<3> The `AuthorizationEvent` event is used for failed security checks and HTTP permission checks.
+<4> Both synchronous and asynchronous CDI observer can be used to observe security events.
```
Comment (sberyozkin) [inline docs/src/main/asciidoc/security-customization.adoc:666]: Is using async observers more performant ? If yes then we should recommend using the async

File: extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/AuthorizationEvent.java (hunk 1 above)
Comment (sberyozkin) [reply extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/AuthorizationEvent.java:39]: @michalvavrik Sure, perhaps indeed, just put that class name as a map property for now if you'd like

**Comment by sberyozkin** [comment]
@michalvavrik Very nice, nearly ready to be merged

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpAuthenticator.java (hunk 3 above)
Comment (michalvavrik) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpAuthenticator.java:123]: agreed, I answer this little above, didn't do it to limit downsides for those not interested in auth success. let's discuss in the other thread

File: docs/src/main/asciidoc/security-customization.adoc (hunk 4 above)
Comment (michalvavrik) [reply docs/src/main/asciidoc/security-customization.adoc:666]: > I would recommend to fire both, a sync and async event.

This is performance sensitive feature, likely to run almost on every request if for example we are talking authentication success event. No worry, code I added analyze observers and only fire events based on what what events are observed (you can combine it, you can have both synchronous and asynchronous for same event).

> And yes, there are differences. For example, if a sync observer throws an exception the processing of the event is aborted. If an async observer throws an exception then the processing of the event is NOT aborted.

Thanks.

Comment (mkouba) [reply docs/src/main/asciidoc/security-customization.adoc:666]: > > I would recommend to fire both, a sync and async event.
> 
> This is performance sensitive feature, likely to run almost on every request if for example we are talking authentication success event. No worry, code I added analyze observers and only fire events based on what what events are observed (you can combine it, you can have both synchronous and asynchronous for same event).

Well, ArC does optimize injected `Event`s so that `Event#fire()` is basically no-op if no matching observer exists. But +1 if you can optimize even further...

Comment (michalvavrik) [reply docs/src/main/asciidoc/security-customization.adoc:666]: Noted, and thanks again; I don't want to pre-optimize, this code  https://github.com/quarkusio/quarkus/blob/6d6ad1e10bfa32aa0f6502064b738302e90c8cd4/extensions/security/runtime/src/main/java/io/quarkus/security/runtime/event/CDISecurityEventProducer.java#L63 probably provides small advantage against `io.quarkus.arc.impl.EventImpl`, but the code is short, so I'll keep it.

File: extensions/security/runtime/src/main/java/io/quarkus/security/runtime/event/CDISecurityEventProducer.java [hunk 5]
```diff
@@ -0,0 +1,88 @@
...
+            this.allSyncEventsObserved = this.syncObservedEventClasses.contains(SecurityEvent.class.getName());
+            this.otherSyncEventsObserved = !allSyncEventsObserved || this.syncObservedEventClasses.size() > 1;
+        }
+    }
+
+    @Override
+    public <T extends SecurityEvent> void fire(T securityEvent) {
+        Objects.requireNonNull(securityEvent);
+        if (allSyncEventsObserved) {
+            cdiEvent.select(SecurityEvent.class).fire(securityEvent);
```
[the remark this answers is not in the document]
Comment (mkouba) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/event/CDISecurityEventProducer.java:64]: I believe that it would be more efficient to store a dedicated `Event` for each `SecurityEvent` implementation class.

[the remark this answers is not in the document]
Comment (manovotn) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/event/CDISecurityEventProducer.java:64]: You are correct in the folding idea though - you should just fire event of type `SecurityEvent` and the assignability will take care of the rest.

From [spec](https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0#observer_resolution):

> An event is delivered to an observer method if:
> * ...
> * An event type is assignable to the observed event type, taking type parameters into consideration.

File: extensions/security/deployment/src/main/java/io/quarkus/security/deployment/SecurityProcessor.java [hunk 6]
```diff
@@ -840,10 +846,71 @@ AdditionalBeanBuildItem authorizationController(LaunchModeBuildItem launchMode)
...
+                .stream()
+                .map(ClassInfo::name)
+                .forEach(knownSecurityEventClasses::add);
+
+        // keep only classes that have CDI observers
+        Set<String> syncObservedSecurityEventClasses = new HashSet<>();
+        Set<String> asyncObservedSecurityEventClasses = new HashSet<>();
+        for (DotName knownSecurityEventClass : knownSecurityEventClasses) {
+            for (ObserverInfo observer : synthesisFinished.getObservers()) {
+                boolean isObserved = observer.getObservedType().name().equals(knownSecurityEventClass);
```
Comment (manovotn) [inline extensions/security/deployment/src/main/java/io/quarkus/security/deployment/SecurityProcessor.java:891]: Just an FYI side note - you are matching based on type and events/observers can have qualifiers too. Technically, you can get a false positive here if users defined an observer with given type and some custom qualifier but it seems to be a very unlikely case here.

File: docs/src/main/asciidoc/security-customization.adoc (hunk 4 above)
Comment (manovotn) [reply docs/src/main/asciidoc/security-customization.adoc:666]: > I would recommend to fire both, a sync and async event. And yes, there are differences. For example, if a sync observer throws an exception the processing of the event is aborted. If an async observer throws an exception then the processing of the event is NOT aborted.
> 
> CC @Ladicek @manovotn

Yes, having both is IMO good idea. The optimization here makes sure it's not fired when not needed and various apps are free to choose whether they want to handle it in a sync or async fasion, so :+1:

Comment (manovotn) [reply docs/src/main/asciidoc/security-customization.adoc:666]: > > Well, ArC does optimize injected Events so that Event#fire()
> 
> I should probably mention I'm not injecting the event as there can be many types of the events.

You should be able to operate just on `Event<SecurityEvent>`. Any observers using subtype of `SecurityEvent` will still get notified.

File: extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/SecurityEventProducer.java [hunk 7]
```diff
@@ -0,0 +1,28 @@
...
+public interface SecurityEventProducer {
+
+    /**
+     * Way to notify event observers. Two type of security event observers, if present, will be notified:
+     * - Observer of {@code T} type
+     * - Observer of {@code SecurityEvent} type
+     *
+     * @param securityEvent security event
+     */
+    <T extends SecurityEvent> void fire(T securityEvent);
```
[the remark this answers is not in the document]
Comment (michalvavrik) [reply extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/SecurityEventProducer.java:17]: There are many points for this API:

1. If you need to disable observing of only security events during runtime, how do you  do it without having one place that takes care of security events?
2. If you prefer publish events with Kafka or anything else, you don't need to first use CDI events and consume them, you can define `SecurityEventProducer` that can filter / transform / publish. I don't expect users do this though.
3. Did you see code I deleted from OIDC extension? Just imagine that his sort of code would need to be repeated anywhere security events are fired, just this PR fires events from: Security, Vert.x HTTP, RESTEasy Reactive, RESTEasy Classic, OIDC

[the remark this answers is not in the document]
Comment (michalvavrik) [reply extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/SecurityEventProducer.java:17]: but TBH main reason was @sberyozkin comment here https://github.com/quarkusio/quarkus/issues/26549#issuecomment-1828400971, I didn't want to write code just to rewrite it when we _introduce SPI_. This API provides one way to fire security events. `fireAuthenticationEvent` wouldn't be part of the `independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl/EventImpl.java:53` so would it work the way that extensions just fire event and Arc code only handles it when it is used? Difference is that it means extra work, often on `Uni` I need to call extra `invoke` etc. and create event.

[the remark this answers is not in the document]
Comment (mkouba) [reply extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/SecurityEventProducer.java:17]: > This API provides one way to fire security events. `fireAuthenticationEvent` wouldn't be part of the `independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl/EventImpl.java:53` so would it work the way that extensions just fire event and Arc code only handles it when it is used?

What I had in mind is something like:
```java
interface SecurityEventProducer {
   void fireAuthenticationEvent(AuthenticationEvent event);
   void fireAuthorizationEvent(AuthorizationEvent event);
}
```
And then the impl bean could inject `Event<AuthenticationEvent>` and `Event<AuthorizationEvent>` and rely on internal optimizations. Ofc, this would not be possible if the set of security events is "unbounded".

File: docs/src/main/asciidoc/security-customization.adoc [hunk 8]
```diff
@@ -620,6 +620,51 @@ are using an executor that is capable of propagating the identity (e.g. no `Comp
 to make sure that Quarkus can propagate it. For more information see the
 xref:context-propagation.adoc[Context Propagation Guide].
 
+[[observe-security-events]]
+== Observe security events
+
+Quarkus fires security events, such as authentication or authorization failure, with the `io.quarkus.security.spi.runtime.SecurityEventProducer` CDI bean.
```
[the remark this answers is not in the document]
Comment (Ladicek) [reply docs/src/main/asciidoc/security-customization.adoc:626]: So if I create a bean of type `SecurityEventProducer`, mark it as `@Alternative` and enabled for application (`@Priority(1)`), it will be called? I didn't inspect the code too deeply, but I didn't get that impression.

I commend your desire to design an extensible API, but the nice thing about CDI events is that they already provide all the extensibility you need. If someone wants to use this API to write security events to some form of an audit log, for example, they don't need the `SecurityEventProducer` SPI -- they just need to observe those events.

[the remark this answers is not in the document]
Comment (michalvavrik) [reply docs/src/main/asciidoc/security-customization.adoc:626]: it is default bean, all you need to do is to create bean. FYI I have tests for everything :-)

> I commend your desire to design an extensible API, but the nice thing about CDI events is that they already provide all the extensibility you need. If someone wants to use this API to write security events to some form of an audit log, for example, they don't need the SecurityEventProducer SPI -- they just need to observe those events.

I'm getting that impression from all that you write. @mkouba just spent many minutes now answering my questions on Zulip. Let me comment on this PR (not just in thread).

**Comment by michalvavrik** [comment]
@Ladicek @mkouba @manovotn You are right, I'll rewrite this PR so that only CDI events are used and there will be no API. I had following reasons to define API:

- one place to disable security events at runtime
- options for users to provide their own implementation of the SecurityEventProducer
- I tried to optimize as you saw too well :-)

@mkouba suggested on Zulip way to do all that I want to do and as you explained, handling of CDI events is already optimized and user can just observe events and then fire events with Kafka or whatever he wants.

I'll put this to draft, rework the PR and ask all of you for review when I'm done.

BTW @sberyozkin I'm sure you have opinions as well, but let me rework this first so that you can see what I have in mind this time. Thanks

File: extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/AuthenticationEvent.java (hunk 2 above)
Comment (sberyozkin) [reply extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/AuthenticationEvent.java:8]: @michalvavrik As far as I know some deployments would like to have a journal of all type of security events, for example, to check afterwards how many times user A has logged in. On the OIDC side Security event of type OIDC LOGIN can help, but this is OIDC specific,

Your proposal sounds best, I'd only propose avoiding introducing hierarchy, IMHO, lets have `AuthenticationSuccessEvent`, `AuthenticationFailureEvent` and the same for the authorization, which will implement SecurityEvent  SPI and these 4 events will cover all the security event variations. Many users will indeed likely listen to authentication and authorization failures only.

By the way, in the next phase it can make sense provide some default implementation which will for ex log everything to Splunk or something like that

**Comment by sberyozkin** [comment]
@michalvavrik Thanks, as far as CDI is concerned, the CDI experts who commented here know best :-), as long as it is easy for users to observe these 4 events we have discussed (plus the current OIDC SecurityEvent), all is great from my point of view

**Comment by sberyozkin** [comment]
@michalvavrik Sorry, I sent it back then too quickly :-), but in any case, it was more about informing everyone what was going for those who are interested to comment or watch, thanks

**Comment by michalvavrik** [comment]
> @michalvavrik Sorry, I sent it back then too quickly :-), but in any case, it was more about informing everyone what was going for those who are interested to comment or watch, thanks

sure thing, np

**Comment by michalvavrik** [comment]
TL;DR; gRPC extension won't support security events and I'm nervous that this PR fires events asynchronously

Danger of firing events asynchronously is that request context is activated asynchronously when request processing have already continued. Some extensions like gRPC need to activate request context themselves. Specifically in gRPC this behavior lead to hanging when HTTP authentication / authorizer fired events asynchronously in `GrpcAuthUsingSeparatePortTest` when security event observer method is defined. Arc independent project allows tracing of the request scope activation / deactivation and it happens every single time when gRPC server is not started on a separate server.

I think it should be safe to fire events asynchronously as long as extensions like RESTEasy Reactive activate new request context, but when `isActive()` is used as for `@ActivateRequestContext` in `ActivateRequestContextInterceptor` and in gRPC and others, it can happen that request scope is asynchronously deactivated when someone tries to use it.

For one, we had users trying to activate request context in SecurityIdentity augmentor (last one I remember is #37457) and just imagine what kind of situation can this lead if the request context is going to be asynchronously deactivated while user is trying to use it.

The context activation can't be disabled on Event notifier. We could fire async in cases when security check is performed when CDI request context is already active, but IMO it would be confusing that some checks can be consumed async and some not. I also think it is absolutely unnecessary to have the context active for security events, but at least for synchronous events we know the context is terminated before other code runs.

**Comment by mkouba** [comment]
> TL;DR; gRPC extension won't support security events and I'm nervous that this PR fires events asynchronously
> 
> Danger of firing events asynchronously is that request context is activated asynchronously when request processing have already continued. Some extensions like gRPC need to activate request context themselves. Specifically in gRPC this behavior lead to hanging when HTTP authentication / authorizer fired events asynchronously in `GrpcAuthUsingSeparatePortTest` when security event observer method is defined. Arc independent project allows tracing of the request scope activation / deactivation and it happens every single time when gRPC server is not started on a separate server.
> 
> I think it should be safe to fire events asynchronously as long as extensions like RESTEasy Reactive activate new request context, but when `isActive()` is used as for `@ActivateRequestContext` in `ActivateRequestContextInterceptor` and in gRPC and others, it can happen that request scope is asynchronously deactivated when someone tries to use it.
> 
> For one, we had users trying to activate request context in SecurityIdentity augmentor (last one I remember is #37457) and just imagine what kind of situation can this lead if the request context is going to be asynchronously deactivated while user is trying to use it.
> 
> The context activation can't be disabled on Event notifier. We could fire async in cases when security check is performed when CDI request context is already active, but IMO it would be confusing that some checks can be consumed async and some not. I also think it is absolutely unnecessary to have the context active for security events, but at least for synchronous events we know the context is terminated before other code runs.

@michalvavrik  I'm not sure if I understand the problem but keep in mind that for CDI async events a new request context is always activated, i.e. an async observer is notified within a separate request context. This is expected and should not pose any danger.

**Comment by michalvavrik** [comment]
@mkouba 

> async observer is notified within a separate request context. 

Yes, expect the very same request context is reused by other code because they just do 

https://github.com/quarkusio/quarkus/blob/4ad3038ed9aa64b76d3db76739a10a02979da37f/independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl/ActivateRequestContextInterceptor.java#L39

https://github.com/quarkusio/quarkus/blob/4ad3038ed9aa64b76d3db76739a10a02979da37f/extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/context/GrpcRequestContextGrpcInterceptor.java#L41

there there is always possibility that the context is terminated asynchronously when other code is using it

> This is expected and should not pose any danger.

I can create reproducer (in short: you just need to drop validation I added to gRPC extension and run `GrpcAuthUsingSeparatePortTest` with at least one observer method of a `SecurityEvent`, you will see that response is never comming, gRPC server endpoints are never invoked) and open Quarkus issue, but this PR is big enough, I'd like to discuss this separately.

@mkouba @manovotn @Ladicek please review this PR and let's talk about gRPC separately. I'm really concerned about this CDI request being activated during authN/ authZ but I bet I can't do anything about it.

**Comment by mkouba** [comment]
> I can create reproducer (in short: you just need to drop validation I added to gRPC extension and run `GrpcAuthUsingSeparatePortTest` with at least one observer method of a `SecurityEvent`, you will see that response is never comming, gRPC server endpoints are never invoked) and open Quarkus issue, but this PR is big enough, I'd like to discuss this separately.

Pls do, I still can't fully undestand.

> I'm really concerned about this CDI request being activated during authN/ authZ but I bet I can't do anything about it.

If you're worried then just do not fire the events asynchronously...

**Comment by michalvavrik** [comment]
> If you're worried then just do not fire the events asynchronously...

Yeah, only reason why I didn't do it was that I hoped you will just tweak Arc implementation when you see this problem. Like add option to not activate the request context for certain event types. If users want to activate it, they can always do it themselves.

**Comment by mkouba** [comment]
> > If you're worried then just do not fire the events asynchronously...
> 
> Yeah, only reason why I didn't do it was that I hoped you will just tweak Arc implementation when you see this problem. Like add option to not activate the request context for certain event types. If users want to activate it, they can always do it themselves.

Well, this is mandated by the spec. It has to be active during notification of an asynchronous observer method. But I still don't fully grasp what the problem is so :shrug:.

**Comment by michalvavrik** [comment]
> Well, this is mandated by the spec. It has to be active during notification of an asynchronous observer method. But I still don't fully grasp what the problem is so 🤷.

copy that, thank you

@mkouba kindy spent time on Zulip and Martin dispel my doubts as the request context activated by observer asynchronously should not be reachable from `Arc.container().requestContext().isActive()` from code that is meanwhile being processed in route handlers (my interpretation, please don't take inaccuracy on him). So I'll let the PR as is. IMHO it is ready for review.

**Comment by michalvavrik** [comment]
CI is heavily failing over flaky tests (for example Maven tooling) which is fun as from fully green CI I only transferred this to draft and back (no changes). I'll rebase on current main.

File: docs/src/main/asciidoc/security-customization.adoc [hunk 9]
```diff
@@ -620,6 +620,62 @@ are using an executor that is capable of propagating the identity (e.g. no `Comp
...
+    void observe(@Observes AuthenticationFailureEvent event) {
+        RoutingContext routingContext = (RoutingContext) event      <2>
+                .getEventProperties()
+                .get(RoutingContext.class.getName());
+    }
+
+    void observe(@Observes AuthorizationFailureEvent event) {       <3>
+        Throwable failure = event.getAuthorizationFailure();
+    }
+}
```
Comment (sberyozkin) [inline docs/src/main/asciidoc/security-customization.adoc:669]: I'd add here 2 more methods consuming Authentication and Authorization success events.

Also probably makes sense to suggest some method completion as QE can later recommend it in any case :-), such as `LOG. debugf("User %s has authenticated successfully", event.getIdentity().getPrincipal().getName())`, etc ?

File: docs/src/main/asciidoc/security-customization.adoc [hunk 10]
```diff
@@ -620,6 +620,62 @@ are using an executor that is capable of propagating the identity (e.g. no `Comp
...
+import jakarta.enterprise.event.ObservesAsync;
+
+public class SecurityEventObserver {
+
+    void observe(@ObservesAsync SecurityEvent event) {              <1>
+        SecurityIdentity identity = event.getSecurityIdentity();
+    }
+
+    void observe(@Observes AuthenticationFailureEvent event) {
+        RoutingContext routingContext = (RoutingContext) event      <2>
```
Comment (sberyozkin) [inline docs/src/main/asciidoc/security-customization.adoc:661]: I'd propose just to log something here as suggested in another comment, and instead have a list of event properties which will also be available for all event types

Comment (michalvavrik) [reply docs/src/main/asciidoc/security-customization.adoc:661]: Makes sense.

File: docs/src/main/asciidoc/security-customization.adoc [hunk 11]
```diff
@@ -620,6 +620,62 @@ are using an executor that is capable of propagating the identity (e.g. no `Comp
 to make sure that Quarkus can propagate it. For more information see the
 xref:context-propagation.adoc[Context Propagation Guide].
 
+[[observe-security-events]]
+== Observe security events
+
+Quarkus beans fire various security events that can be consumed by xref:cdi.adoc#events-and-observers[CDI observers].
```
[the remark this answers is not in the document]
Comment (michalvavrik) [reply docs/src/main/asciidoc/security-customization.adoc:626]: > I was not sure about Quarkus beans fire since they consume events if I understand it correctly

Security beans fire events and CDI observers consume them, IMO it is not incorrect, but as said, I like your version.

File: docs/src/main/asciidoc/security-customization.adoc (hunk 9 above)
Comment (michalvavrik) [reply docs/src/main/asciidoc/security-customization.adoc:669]: Sure thing.

File: docs/src/main/asciidoc/security-customization.adoc [hunk 12]
```diff
@@ -620,6 +620,62 @@ are using an executor that is capable of propagating the identity (e.g. no `Comp
...
+import io.quarkus.security.spi.runtime.AuthenticationFailureEvent;
+import io.quarkus.security.spi.runtime.AuthorizationFailureEvent;
+import io.quarkus.security.spi.runtime.SecurityEvent;
+import io.vertx.ext.web.RoutingContext;
+import jakarta.enterprise.event.Observes;
+import jakarta.enterprise.event.ObservesAsync;
+
+public class SecurityEventObserver {
+
+    void observe(@ObservesAsync SecurityEvent event) {              <1>
```
Comment (sberyozkin) [inline docs/src/main/asciidoc/security-customization.adoc:656]: Should `SecurityEvent` have a category or type enum property, example, `AUTHENTICATION_FAILED` etc ? Otherwise one needs to do up to 5 `instanceof` checks to distinguish which event that is.  (Note OIDC SecurityEvent already has getType() returning its own enum, so it will be getEventType())

I wonder if it is really important to have the `SecurityEvent` interface ? Is it more effective to use it to capture all events ? I'm not sure users will treat all events generically, they will most likely need to know what type of event it is, in which case, they will observer `AuthenticationFailed` etc.

What do you think ?

File: docs/src/main/asciidoc/security-customization.adoc [hunk 13]
```diff
@@ -620,6 +620,62 @@ are using an executor that is capable of propagating the identity (e.g. no `Comp
...
+    }
+}
+----
+<1> This observer consumes all the security events asynchronously, which means that HTTP request processing will continue regardless on the event processing.
+The `SecurityEvent` observer method is notified with every authentication and authorization success, depending on the application, that can be a lot of events.
+For that reason, asynchronous processing can have positive effect on performance.
+<2> Applications based on the Vert.x HTTP extension should be able to access the `RoutingContext` from event properties.
+<3> The `AuthorizationFailureEvent` event is fired when request does not comply a standard security annotation constrain or is denied access by an HTTP Security policy.
+
+IMPORTANT: The gRPC extension does not support security events.
```
Comment (sberyozkin) [inline docs/src/main/asciidoc/security-customization.adoc:677]: I thought it was only async events that could not be supported for gRPC or all of them ? Is it something that will never be supported or it is only the current limitation ?

Comment (michalvavrik) [reply docs/src/main/asciidoc/security-customization.adoc:677]: Yes and so far I can only reproduce it when gRPC is not running on a separate server, but as based on feedback I dropped check whether event is observed in sync / async / both events as unnecessary optimization and it would require to add everywhere additional if conditions before async is fired (because we always fire it). I'm honestly not sure what is happening in gRPC, but reproducer can be simple when this PR is in, that is why I'm waiting with opening of dedicated Quarkus issue. I hope it is related to how gRPC keeps Vert.x context state.

I'll try to address gRPC when there is a feedback from people like Clement on the issue I open after this one.

File: extensions/grpc/runtime/src/main/java/io/quarkus/grpc/auth/GrpcSecurityRecorder.java [hunk 14]
```diff
@@ -43,4 +47,17 @@ public void initGrpcSecurityInterceptor(Map<String, List<String>> serviceClassTo
...
 
+    public void validateSecurityEventsDisabled(String observedSecurityEvent) {
+        boolean securityEventsEnabled = ConfigProvider
+                .getConfig()
+                .getOptionalValue("quarkus.security.events.enabled", boolean.class)
+                .orElse(Boolean.TRUE);
+        if (securityEventsEnabled) {
+            throw new ConfigurationException("""
+                    Found observer method for event type '%s', but the gRPC extension does not support security
+                    events. Either disable security events with the 'quarkus.security.events.enabled'
```
Comment (sberyozkin) [inline extensions/grpc/runtime/src/main/java/io/quarkus/grpc/auth/GrpcSecurityRecorder.java:58]: What if both GRPC and vertx-http are used ?

Comment (michalvavrik) [reply extensions/grpc/runtime/src/main/java/io/quarkus/grpc/auth/GrpcSecurityRecorder.java:58]: Considering this is only time where I can reproduce it (not gRPC running on a separate server) and considering gRPC is just a route handler answer is: if gRPC extension is present, security events are not supported.

I'd not make fuss about it, it is temporary and it is done for a very good reason, something super strange and hard to debug is happening there if you fire asynchronous events that activate CDI request context and no, it is not in how I fire events because all this PR does is `event.fireAsync`, you can't make mistake in that.

File: extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/SecurityEvent.java [hunk 15]
```diff
@@ -0,0 +1,33 @@
...
+import java.util.Map;
+
+import io.quarkus.security.identity.SecurityIdentity;
+
+/**
+ * Common interface for all CDI security events, which allows to consume all the events.
+ */
+public interface SecurityEvent {
+
+    SecurityEvent NOOP = new SecurityEvent() {
```
Comment (sberyozkin) [inline extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/SecurityEvent.java:12]: What is the idea behind this `NOOP` ?

Comment (michalvavrik) [reply extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/SecurityEvent.java:12]: In order to check with `BeanManager` whether event type is observed, I need actual instance of that event. And ever bean that fire security events need this instances, so I thought it would be nice not to create them over and over again.

Comment (michalvavrik) [reply extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/SecurityEvent.java:12]: Same goes for empty instances on security event implementations.

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/DefaultTenantConfigResolver.java [hunk 16]
```diff
@@ -59,21 +63,21 @@ public class DefaultTenantConfigResolver {
...
 
-    private volatile boolean securityEventObserved;
-
-    private ConcurrentHashMap<String, BackChannelLogoutTokenCache> backChannelLogoutTokens = new ConcurrentHashMap<>();
-
-    public DefaultTenantConfigResolver(BlockingSecurityExecutor blockingExecutor) {
+    public DefaultTenantConfigResolver(BlockingSecurityExecutor blockingExecutor, Event<SecurityEvent> securityEvent,
+            BeanManager beanManager, SecurityConfig securityConfig) {
         this.blockingRequestContext = new BlockingTaskRunner<OidcTenantConfig>(blockingExecutor);
+        this.securityEventObserved = SecurityEventHelper.eventObserved(new SecurityEvent(null, (SecurityIdentity) null),
```
Comment (sberyozkin) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/DefaultTenantConfigResolver.java:78]: Should it be `SecurityEventHelper.eventObserved(SecurityEvent.class)` ?

Comment (michalvavrik) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/DefaultTenantConfigResolver.java:78]: This goes down to the `jakarta.enterprise.inject.spi.BeanManager#resolveObserverMethods`, I'm just spec folk had some reason for this, but I don't know why looking at `io.quarkus.arc.impl.BeanManagerImpl#resolveObserverMethods`  it just do `event.getClass`. Anyway, I can't change this.

File: extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/SecurityEventHelper.java [hunk 17]
```diff
@@ -0,0 +1,29 @@
+package io.quarkus.security.spi.runtime;
+
+import jakarta.enterprise.inject.spi.BeanManager;
+
+public record SecurityEventHelper(boolean fireEventOnSuccess, boolean fireEventOnFailure) {
+
+    public static SecurityEventHelper of(SecurityEvent successEvent, SecurityEvent failureEvent, BeanManager beanManager,
+            boolean enabled) {
+        if (enabled) {
+            boolean fireAllSecurityEvents = !beanManager.resolveObserverMethods(SecurityEvent.NOOP).isEmpty();
```
Comment (sberyozkin) [inline extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/SecurityEventHelper.java:10]: I'd suggest moving SecurityEvent.NOOP here instead of keeping it in the interface itself, though I'm wondering if we can avoid dealing with instances

Comment (michalvavrik) [reply extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/SecurityEventHelper.java:10]: > I'd suggest moving SecurityEvent.NOOP here instead of keeping it in the interface itself

Yes, will move it here, agreed. And will do same for other security events.

>  though I'm wondering if we can avoid dealing with instances

no, see answers above

File: extensions/security/runtime/src/main/java/io/quarkus/security/runtime/SecurityConfig.java [hunk 18]
```diff
@@ -0,0 +1,30 @@
...
+     */
+    SecurityEventsConfig events();
+
+    interface SecurityEventsConfig {
+
+        /**
+         * Whether security events should be fired.
+         */
+        @WithDefault("true")
+        boolean enabled();
```
Comment (sberyozkin) [inline extensions/security/runtime/src/main/java/io/quarkus/security/runtime/SecurityConfig.java:26]: Do we really need this property ? Users express that it is required indirectly by registering observers.

Comment (michalvavrik) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/SecurityConfig.java:26]: > Do we really need this property ? 

There is very small cost to having this property, but there is nice advantage - you can only enable debugging, which can be costly, without any code changes, you can do it at runtime for example on just some containers etc.

> Users express that it is required indirectly by registering observers.

They express they want to consume events in certain situations, what if they don't need it always?

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpAuthorizer.java [hunk 19]
```diff
@@ -18,17 +24,28 @@ public class HttpAuthorizer extends AbstractHttpAuthorizer {
...
+            @ConfigProperty(name = "quarkus.security.events.enabled") boolean securityEventsEnabled) {
+        super(httpAuthenticator, identityProviderManager, controller, toList(installedPolicies), beanManager, blockingExecutor,
+                authZFailureEvent, authZSuccessEvent, securityEventsEnabled);
     }
 
     private static List<HttpSecurityPolicy> toList(Instance<HttpSecurityPolicy> installedPolicies) {
         List<HttpSecurityPolicy> globalPolicies = new ArrayList<>();
         for (HttpSecurityPolicy i : installedPolicies) {
-            if (i.name() == null) {
+            if (i.name() == null && isNotPathMatchingPolicyWithoutPerms(i)) {
```
Comment (sberyozkin) [inline extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpAuthorizer.java:37]: It is a very minor update but since you are planning to work on HttpSecurityPolicy related PR later as well, then I propose to deal with this update there. I'm not sure why a policy without name can still be applied, but IMHO, in any case, it is another conversation

Comment (michalvavrik) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpAuthorizer.java:37]: > It is a very minor update but since you are planning to work on HttpSecurityPolicy related PR later as well, then I propose to deal with this update there.

It is just something I mentioned thanks to security events. I think this is just logical change as you don't want to check paths only to find out there are none.

It is not related to what I'll do in future, but I can create separate PR if you like and drop this change.

>  I'm not sure why a policy without name can still be applied, but IMHO, in any case, it is another conversation

this is about `io.quarkus.vertx.http.runtime.security.AbstractPathMatchingHttpSecurityPolicy` being run when there are no HTTP permissions. Why does that bean exist? Because whether bean is going to be created is decided during build time, but HTTP permissions are runtime defined.

File: extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/SecurityEventHelper.java [hunk 20]
```diff
@@ -0,0 +1,29 @@
...
+            }
+        } else {
+            return new SecurityEventHelper(false, false);
+        }
+    }
+
+    /**
+     * @return true if given event type is observed and security events are enabled
+     */
+    public static boolean eventObserved(SecurityEvent event, BeanManager beanManager, boolean enabled) {
```
Comment (sberyozkin) [inline extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/SecurityEventHelper.java:26]: I wonder if it should return some enum, say, `ObserveType`, with values like `NONE, ALL, SYNC, ASYNC`, so that rather than doing 2 calls `event.fire(); event.fireAsync();`, we can do for example, only `event.fire();` if no `ASYNC` observers are available ? Does it sound reasonable ?

File: docs/src/main/asciidoc/security-customization.adoc (hunk 13 above)
Comment (sberyozkin) [reply docs/src/main/asciidoc/security-customization.adoc:677]: @michalvavrik Sounds good, may be then worth saying `The gRPC extension currently does not support security events.`, giving some possibility it might in the future :-)

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpAuthorizer.java (hunk 19 above)
Comment (sberyozkin) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpAuthorizer.java:37]: @michalvavrik Sure, looks like it is worth backporting, so if it stays in this PR then it won't be backported, so it is up to you

File: extensions/grpc/runtime/src/main/java/io/quarkus/grpc/auth/GrpcSecurityRecorder.java (hunk 14 above)
Comment (michalvavrik) [reply extensions/grpc/runtime/src/main/java/io/quarkus/grpc/auth/GrpcSecurityRecorder.java:58]: > But if I want to observe OIDC events and also need to use GRPC, failing the builds looks unnecessary to me.

but in case gRPC is just a route handler and Vert.x HTTP security handlers like HTTP Authenticator and HTTP Authorizer are run, you don't know what handler is applied next. How do you know it is going to be REST stack and not a gRPC? I'm also not sure why should applications combine gRPC and REST stacks, wouldn't microservice do one thing?

> What do you mean when you say a big refactoring would be needed, I thought, in case of GRPC, for the events to work there would have to be some GRPC specific code to gave then fired

Problem is not a gRPC specific code firing events, problem is that when HTTP Authenticator and HTTP Authorizer fires events asynchronously it mess with how `io.quarkus.grpc.runtime.supports.context.GrpcRequestContextGrpcInterceptor` works with a context.

> , but this code is not even there so where is a problem if only a warning is issued ?

Code is there and logic that determines inside Vert.x HTTP routes what router will be next is complex.

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/DefaultTenantConfigResolver.java (hunk 16 above)
Comment (michalvavrik) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/DefaultTenantConfigResolver.java:78]: I agree @sberyozkin but I won't touch Arc project in this PR because I don't know why things are done there as they are done. CDI experts could say it should be added to spec first. It is not important enough, but if CDI experts agree, we can do it.

Comment (michalvavrik) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/DefaultTenantConfigResolver.java:78]: So IMHO not possible.

File: extensions/security/runtime/src/main/java/io/quarkus/security/runtime/SecurityConfig.java (hunk 18 above)
Comment (michalvavrik) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/SecurityConfig.java:26]: > @michalvavrik Right, I agree, users sometimes may want to disable some security features for example, such as authorization, or, when testing, they use @TestSecurity or Wiremocks

This is not only about disabling security features, there is expense of firing events because for example we need to catch exceptions and create event instances etc. You only want to do this optionally when you need it. Like if you experience some bug in a service, so you sent environment variable that enables security events.

> but I'm not sure how this property helps, theoretically at least, they can have Observes but for some reasons don't want anything reported, even if the security capability is present - if it is not they won't be reported - which is why I'm not sure it is necessary to introduce it immediately to address what looks like a rather rare case (Security capability is present but users don't want events fired).

How is this different to optionally enabling debug or trace logging? It is more effective to allow users to disable security events instead of for example define observers that log everything with debug / trace because you avoid some processing.

> May be it should be dropped for now - but it can easily be re-introduced if someone ever asks about such an option ?

Well, I'll do it if you insist. I think we are cutting down cool feature which users can't implement themselves. If they introduce application-specific custom config property that inside observer method skip processing of events when they don't need it, it is after we have already caught exception and collected data like `Securityidentity` and set the event.

If you think users can show their interest at build time (by defining observers), I'm not sure why there are runtime properties disabling features like `quarkus.hibernate-orm.active` and others.

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpAuthorizer.java (hunk 19 above)
Comment (michalvavrik) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpAuthorizer.java:37]: I'll move it.

**Comment by michalvavrik** [comment]
Thanks for review @sberyozkin, it seems I have very different views than you do, but IMO none of these matters is important. I'll make adjustments you reply to my comments. I think one last round of your replies to my comments should do, as we can drop all the things you want to drop and wait for feedback from users.

File: extensions/grpc/runtime/src/main/java/io/quarkus/grpc/auth/GrpcSecurityRecorder.java (hunk 14 above)
Comment (sberyozkin) [reply extensions/grpc/runtime/src/main/java/io/quarkus/grpc/auth/GrpcSecurityRecorder.java:58]: @michalvavrik OK, lets leave the GRPC issue for now

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/DefaultTenantConfigResolver.java (hunk 16 above)
Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/DefaultTenantConfigResolver.java:78]: @michalvavrik But if observing events with GRPC won't work then it can be in Vertx HTTP ? In any case, indeed, not a big problem, it is an internal code, so can be optimized eventually, thanks

File: docs/src/main/asciidoc/security-customization.adoc (hunk 12 above)
Comment (sberyozkin) [reply docs/src/main/asciidoc/security-customization.adoc:656]: @michalvavrik 

>  Having categories and enum means anyone who want create new event needs to add his category or use very general category that makes it useless.

It is Quarkus which decides which types of events it can send so it will only be Quarkus which would add them

> How exactly are you going to map OIDC event type OIDC_FRONTCHANNEL_LOGOUT_COMPLETED to this new enum?

As I said, given that OIDC has its own event type, a property on this new `SecurityEvent` would have to be named differently. May be in case of OIDC specific events a new property would be set to `OIDC` and then OIDC specific type would be used to narrow down further.

But, in any case, it can be added later if necessary.

But, IMHO, we should not recommend users writing the code like the one you suggest above. It still does not give any hint what this event is about. I totally agree some users may want to do fine-grained checks, check class names, individual properties, but in general, IMHO, we should advise a different pattern, where users catch specific events, then log them and then use `SecurityEvent` interface to post to Kafka or log properties - this will support both scenarios - where users are expressing interest in specific events but also using a common interface for further processing. IMHO it would be better than only giving an example where all events can be captured by a single observer.

Please consider updating the example if it sounds reasonable

File: extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/SecurityEventHelper.java (hunk 20 above)
Comment (sberyozkin) [reply extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/SecurityEventHelper.java:26]: @michalvavrik Sounds goods, can you consider something like `SecurityEventHelper.fire(Event<? extends SecurityEvent> event)` and have both `fire()` and `fireAsync()` there ? I don't mean to be pedantic, it is just looks like that having two calls in every place where firing is required might be optimized a bit

File: extensions/security/runtime/src/main/java/io/quarkus/security/runtime/SecurityConfig.java (hunk 18 above)
Comment (sberyozkin) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/SecurityConfig.java:26]: @michalvavrik 

>I think we are cutting down cool feature

I can guarantee you I'm not on a mission to cut down the coolness from this PR :-) I'm just looking what can be dropped which may not necessarily needed if needed at all, I know I'm not always following it myself :-).

My understanding properties like `quarkus.hibernate-orm.active=false` or `quarkus.oidc.tenant-enabled=false` etc are about making sure the application can start where no given DB is available or no OIDC provider is listening, etc. 

I'm just finding it hard to imagine why users would want to avoid observer methods firing at runtime. Is it because the downstream channel these event observers are coded to report to, ex kafka, that is expecting them is not available in this case, something like that ? May be then it is indeed necessary

File: extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/SecurityEventHelper.java (hunk 20 above)
Comment (michalvavrik) [reply extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/SecurityEventHelper.java:26]: Sure, will do.

File: docs/src/main/asciidoc/security-customization.adoc (hunk 12 above)
Comment (michalvavrik) [reply docs/src/main/asciidoc/security-customization.adoc:656]: I'm fine with dropping example of `void observe(@ObservesAsync SecurityEvent event) {`.


I don't think you can deny that:

- many application won't want to log something specific to the event (like _Authentication successful ...._) because extensive logging may slows down app, that's way they may not want to deal with anything specific to the event type
- if oidc `SecurityEvent` put `io.quarkus.oidc.SecurityEvent.Type` also to `eventProperties` map, than I don't loose any information by using interface as I do have
  - `SecurityIdentity`
  - `eventProperties`
  - `event class` which tells my type of event
-  if you use observer specific for every event like OIDC SecurityEvent, you will still need some identifier when you are storing it, I'm not sure why class signature is any worse than something you can type

My conclusion is:

1. I'll drop `SecurityEvent` observer example in favor of all other event type observers
2. I'll keep the interface.

If you disagree with 2. please comment.

Comment (sberyozkin) [reply docs/src/main/asciidoc/security-customization.adoc:656]: @michalvavrik Right, your points about keeping the interface are convincing, I'm just suggesting to revise the example for possibly a more typical case where specific even types are observed but also, the fact that all of them implement the interface can be used for some common event processing for all of those types like logging of the properties, posting to Kafka etc

File: extensions/security/runtime/src/main/java/io/quarkus/security/runtime/SecurityConfig.java (hunk 18 above)
Comment (sberyozkin) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/SecurityConfig.java:26]: @michalvavrik To be honest I don't find these 3 cases worthy of having a dedicated configuration property since IMHO users have good reasons for observing events in the code beyond typing it all in the prod code just to keep an option to debug. But IMHO I'd rather recommend users disable events in cases where their consumers are not available rather than injecting configuration properties - this is a case which I'm thinking about which might justify this property IMHO

Comment (michalvavrik) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/SecurityConfig.java:26]: > To be honest I don't find these 3 cases worthy of having a dedicated configuration property since IMHO users have good reasons for observing events in the code beyond typing it all in the prod code just to keep an option to debug.

Alright, I hear you and disagree. However I can accept dropping this property if you insist, please let me know.

Comment (michalvavrik) [reply extensions/security/runtime/src/main/java/io/quarkus/security/runtime/SecurityConfig.java:26]: We have conclusion, thanks.

**Comment by sberyozkin** [comment]
@michalvavrik I think we have agreed in all the pending/open comments, including keeping an interface and configuration property (even if we look at when to use it a bit differently), and IMHO this PR is nearly ready to be merged, thanks for your effort

File: docs/src/main/asciidoc/security-customization.adoc (hunk 10 above)
Comment (michalvavrik) [reply docs/src/main/asciidoc/security-customization.adoc]: Sorry, I actually ended up doing something similar again. Feel free to fight back, but I realized:

- we should show that authenticationfailureevent as always accessible Routingcontext (when it is HTTP based app, which is logical enough), it is important as it gives you access to path, credentials, cookies, headers etc.
- I think it doesn't make any sense to log exception without context and routingcontext is useful.

I swear I wrote this example from scratch only to end up on something like this. Have a look.

File: docs/src/main/asciidoc/security-customization.adoc [hunk 21]
```diff
@@ -620,6 +620,78 @@ are using an executor that is capable of propagating the identity (e.g. no `Comp
...
+        }
+        return null;
+    }
+
+}
+----
+<1> This observer consumes all the `AuthenticationSuccessEvent` events asynchronously, which means that HTTP request processing will continue regardless on the event processing.
+Depending on the application, that can be a lot of the `AuthenticationSuccessEvent` events.
+For that reason, asynchronous processing can have positive effect on performance.
+<2> PermitAll security check does not require authentication, therefore it can happen that SecurityIdentity will be null.
```
Comment (sberyozkin) [inline docs/src/main/asciidoc/security-customization.adoc:691]:
```suggestion
<2> Common code for all supported security event types is possible because they all support `io.quarkus.security.spi.runtime.SecurityEvent` interface.
```

I got confused with a reference to `PermitAll`, it looks normal to protect against NPE without this clarification, so I propose instead to highlight the important point of being able to write a common code for all the event types

File: docs/src/main/asciidoc/security-customization.adoc [hunk 22]
```diff
@@ -620,6 +620,78 @@ are using an executor that is capable of propagating the identity (e.g. no `Comp
...
+        if (principalName != null) {
+            LOG.debugf("User '%s' has been authorized successfully", event.getSecurityIdentity().getPrincipal().getName());
+        }
+    }
+
+    void observeAuthorizationFailure(@Observes AuthorizationFailureEvent event) {
+        LOG.debugf(event.getAuthorizationFailure(), "User '%s' authorization failed", event.getSecurityIdentity().getPrincipal().getName());
+    }
+
+    private static String getPrincipalName(SecurityEvent event) {
```
Comment (sberyozkin) [inline docs/src/main/asciidoc/security-customization.adoc:679]:
```suggestion
    private static String getPrincipalName(SecurityEvent event) { <2>
```

File: docs/src/main/asciidoc/security-customization.adoc [hunk 23]
```diff
@@ -620,6 +620,78 @@ are using an executor that is capable of propagating the identity (e.g. no `Comp
...
+        if (event.getSecurityIdentity() != null) {                                              <2>
```
Comment (sberyozkin) [inline docs/src/main/asciidoc/security-customization.adoc:680]:
```suggestion
        if (event.getSecurityIdentity() != null) {
```

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/DefaultTenantConfigResolver.java [hunk 24]
```diff
@@ -189,12 +195,9 @@ boolean isSecurityEventObserved() {
...
     }
 
-    void setSecurityEventObserved(boolean securityEventObserved) {
-        this.securityEventObserved = securityEventObserved;
-    }
-
-    Event<SecurityEvent> getSecurityEvent() {
-        return securityEvent;
+    void fireSecurityEvent(SecurityEvent event) {
+        securityEvent.fire(event);
```
Comment (sberyozkin) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/DefaultTenantConfigResolver.java:199]: @michalvavrik I'm not sure about `SecurityEventHelper` refactoring like `fireSuccessEvents`, `fireFailureEvents`, they can't take care of this code. Can we just make `SecureEventHelper.fire(securityEvent, event)` only used everywhere ? I thought we agreed to have a simple method added to it and now it looks totally different. Can you think of how  `SecureEventHelper` can support this code too ?

File: docs/src/main/asciidoc/security-customization.adoc (hunk 10 above)
Comment (sberyozkin) [reply docs/src/main/asciidoc/security-customization.adoc]: @michalvavrik The new example is fine, RoutingContext won't work for GRPC I guess if you'll make it work later, but it can clarified in due time as well

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/DefaultTenantConfigResolver.java (hunk 24 above)
Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/DefaultTenantConfigResolver.java:199]: IMHO it is worth it, not a big deal, but with new event types to be added in time, it is worth having a simple option to encapsulate `fire`, `fireAsync` for all events. This is the very last thing I'd like to ask for, I've been already prepared to approve, it is very close IMHO

Comment (michalvavrik) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/DefaultTenantConfigResolver.java:199]: > I thought we agreed to have a simple method added to it and now it looks totally different.

That was necessary, previously it was a record - **data carrier** - with only methods creating the record, now that you wanted to add utility method, it had to look differently in order to not disuse records.

> Can we just make SecureEventHelper.fire(securityEvent, event) only used everywhere ?

I thought how I refactored `SecurityEventHelper` allowed me to limit repeating of same pattern with booleans and `Event`. I'm not sure method like this

```
public static <T extends SecurityEvent> void fire(Event<T> securityEvent, T event) {
     securityEvent.fire(event);
    securityEvent.fireAsync(event);
}
```
is super useful, I think what I did limited repetition better. I can add this method to `SecurityEventHelper` @sberyozkin , but I don't see a reason to reduce helper as it looks now.

Comment (michalvavrik) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/DefaultTenantConfigResolver.java]: Done.

**Review by sberyozkin — APPROVED** [review]
Thanks @michalvavrik

File: extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/AuthenticationFailureEvent.java [hunk 25]
```diff
@@ -0,0 +1,39 @@
...
+
+import io.quarkus.security.identity.SecurityIdentity;
+
+/**
+ * Security event fired when authentication failed.
+ */
+public class AuthenticationFailureEvent implements SecurityEvent {
+
+    public static final String AUTHENTICATION_FAILURE_KEY = AuthenticationFailureEvent.class.getName() + ".FAILURE";
+    private final Map<String, Object> eventProperties;
```
Comment (mkouba) [inline extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/AuthenticationFailureEvent.java:14]: I wonder if it would make sense to create an `AbstractSecurityEvent` with `eventProperties` and `securityIdentity` fields?

File: extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/SecurityEventHelper.java [hunk 26]
```diff
@@ -0,0 +1,93 @@
...
+    public static final AuthenticationSuccessEvent AUTHENTICATION_SUCCESS = new AuthenticationSuccessEvent(null, null);
+    private final boolean fireEventOnSuccess;
+    private final boolean fireEventOnFailure;
+    private final Event<S> successEvent;
+    private final Event<F> failureEvent;
+
+    public SecurityEventHelper(Event<S> successEvent, Event<F> failureEvent, S successInstance, F failureInstance,
+            BeanManager beanManager, boolean enabled) {
+        if (enabled) {
+            boolean fireAllSecurityEvents = !beanManager.resolveObserverMethods(new SecurityEvent() {
```
Comment (mkouba) [inline extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/SecurityEventHelper.java:24]: Did you do any measurements? I'm still wondering if this optimization makes sense. I mean if no observers are present the `EventImpl#fire()` should be basically a no-op so :shrug: .

Comment (michalvavrik) [reply extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/SecurityEventHelper.java:24]: > Did you do any measurements? I'm still wondering if this optimization makes sense. I mean if no observers are present the EventImpl#fire() should be basically a no-op so

No, 

- one, because such addition won't have effect as you correctly assume, but if we all write code that do things that are not necessary and keep adding features executed on every single request while users are waiting and not using these features, it will have effect.
- two, I'm not worried about `EventImpl#fire()`; why should I create maps, functions, add try-catch during every single HTTP request when most applications might not use it? Having this behind boolean limits cost of this PR. 

Let me you few examples:

1.  this handler https://github.com/quarkusio/quarkus/blob/008451f0c1ae3e80c2e6d093fd3cbe44feb85f28/extensions/resteasy-reactive/quarkus-resteasy-reactive/runtime/src/main/java/io/quarkus/resteasy/reactive/server/runtime/security/EagerSecurityHandler.java is created for every RR runtime resource method and I will be running runnable for success and throwable for failure even though I know I don't need it, then create map, unwrap `RoutingContext`, get check name and create event instance
2. I'll catch exception https://github.com/quarkusio/quarkus/blob/008451f0c1ae3e80c2e6d093fd3cbe44feb85f28/extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityConstrainer.java#L63 which IIUC will only cost when actually catching it or create these mappers without needing it https://github.com/quarkusio/quarkus/blob/008451f0c1ae3e80c2e6d093fd3cbe44feb85f28/extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityConstrainer.java#L82

I just don't think it's good idea to create things during requests I know ahead noone is using once in constructor of singleton / application scoped bean.

I'd agree with you if code was like `event.fire(new Event());`. Anyway, if it turns out your view is generally shared, I can yield.

File: extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/AuthenticationFailureEvent.java (hunk 25 above)
Comment (michalvavrik) [reply extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/AuthenticationFailureEvent.java:14]: I had it, I changed it as I thought user will use `SecurityEvent` which as interface looks better in my eyes then `AbstractSecurityEvent`. But considering how much trouble I had to convince Sergey to keep this interface (as he expects users will prefer implementations), I can change it to abstract class. It will help to drop some code repetition.

Comment (mkouba) [reply extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/AuthenticationFailureEvent.java:14]: Nono, the `SecurityEvent` interface is perfect. I would personally keep it. I was more thinking about reusing the logic in the impl classes...

Comment (michalvavrik) [reply extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/AuthenticationFailureEvent.java:14]: Yeah, this way I like it, will do it.

File: extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/SecurityEventHelper.java (hunk 26 above)
Comment (mkouba) [reply extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/SecurityEventHelper.java:24]: Ok, I do understand your points and I share your opinion that we should avoid unnecessary logic if possible. So let's keep it this way for now...

File: extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/AuthenticationFailureEvent.java (hunk 25 above)
Comment (sberyozkin) [reply extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/AuthenticationFailureEvent.java:14]: @michalvavrik @mkouba Thanks, indeed, interface should stay

Comment (michalvavrik) [reply extensions/security/runtime-spi/src/main/java/io/quarkus/security/spi/runtime/AuthenticationFailureEvent.java]: It was for better, done.

**Review by manovotn — APPROVED** [review]
My comments are just minor nitpicks, otherwise the CDI bits and the event-firing optimization look good to me.

File: extensions/grpc/deployment/src/main/java/io/quarkus/grpc/deployment/GrpcServerProcessor.java [hunk 27]
```diff
@@ -792,4 +796,37 @@ void initGrpcSecurityInterceptor(List<BindableServiceBuildItem> bindables, Capab
...
+                .getIndex()
+                .getAllKnownImplementors(SecurityEvent.class)
+                .stream()
+                .map(ClassInfo::name)
+                .forEach(knownSecurityEventClasses::add);
+
+        // find at least one CDI observer and validate security events are disabled
+        knownClasses: for (DotName knownSecurityEventClass : knownSecurityEventClasses) {
+            for (ObserverInfo observer : synthesisFinished.getObservers()) {
+                boolean isObserved = observer.getObservedType().name().equals(knownSecurityEventClass);
```
[the remark this answers is not in the document]
Comment (michalvavrik) [reply extensions/grpc/deployment/src/main/java/io/quarkus/grpc/deployment/GrpcServerProcessor.java]: sure, done

File: docs/src/main/asciidoc/security-customization.adoc [hunk 28]
```diff
@@ -620,6 +620,78 @@ are using an executor that is capable of propagating the identity (e.g. no `Comp
 to make sure that Quarkus can propagate it. For more information see the
 xref:context-propagation.adoc[Context Propagation Guide].
 
+[[observe-security-events]]
+== Observe security events
+
+Quarkus beans can use xref:cdi.adoc#events-and-observers[CDI observers] to consume authentication and authorization security events.
```
[the remark this answers is not in the document]
Comment (michalvavrik) [reply docs/src/main/asciidoc/security-customization.adoc:626]: done, thank you

**Comment by michalvavrik** [comment]
Checked CI failures:

> integration-tests/hibernate-orm-tenancy/connection-resolver

contains no security and it didn't fail before latest changes

> IncludePatternTestCase.checkTestsAreRun

same as above plus works on JDK 17 and I can't see what is wrong from logs, it looks flaky

**Comment by sberyozkin** [comment]
I belive we can merge, thanks everyone
