### PR TITLE
Fix Spring Data JPA Query Methods for big hierarchy

### LINKED ISSUE #10581: Quarkus Spring JPA Repository query methods is not working, at least like in Spring Boot
**Describe the bug**
I have these Java classes:
A MappedSuperclass AbstractEntity that is a superclass for all JPA entities:

```java
@MappedSuperclass
public abstract class AbstractEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;
...
}
```
And these JPA entity classes:

The Order class:

```java
@Entity
@Table(name = "orders")
public class Order extends AbstractEntity {
...
    @OneToOne
    @JsonIgnore
    private Cart cart;
...
}
```

The Cart class:

```java
@Entity
@Table(name = "carts")
public class Cart extends AbstractEntity {

    @ManyToOne
    private Customer customer;
...
}
```

And finally the Customer class:

```java
@Entity
@Table(name = "customers")
public class Customer extends AbstractEntity {

...
}
```

I have a **JpaRepository** to find orders using the **Customer Id**:

```java
@Repository
public interface OrderRepository extends JpaRepository<Order, Long> {
    List<Order> findByCartCustomerId(Long customerId);
}
```

**Expected behavior**
This Query Method needs to be working as it is actually working in Spring Boot framework with Spring Data JPA.

**Actual behavior**
Runtime exception is thrown:

```bash
2020-07-08 18:34:00,858 ERROR [io.qua.dep.dev.DevModeMain] (main) Failed to start Quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.spring.data.deployment.SpringDataJPAProcessor#build threw an exception: io.quarkus.spring.data.deployment.UnableToParseMethodException: Entity com.targa.labs.quarkus.myboutique.domain.Order does not contain a field named: CartCustomerId. Offending method is findByCartCustomerId
```

**To Reproduce**
1. Create new Quarkus app with: Hibernate ORM and Quarkus Extension for Spring Data JPA API dependencies. For DB I used Postgresql
2. Add these classes
3. run `mvn quarkus:dev`

**Configuration**
```properties
quarkus.datasource.db-kind=postgresql
quarkus.hibernate-orm.dialect=org.hibernate.dialect.PostgreSQL10Dialect
quarkus.hibernate-orm.log.sql=true
quarkus.datasource.username=developer
quarkus.datasource.password=p4SSW0rd
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/demo
quarkus.hibernate-orm.database.generation=drop-and-create
```

**Screenshots**
None

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin MacBook-Pro-de-Nebrass.local 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64
 - Output of `java -version`:  OpenJDK 64-Bit Server VM GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02, mixed mode, sharing)
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.5.2.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 3.6.3

**Additional context**
(Add any other context about the problem here.)

### PR DESCRIPTION
**Pull request by nebrass**
Fix Spring Data JPA Query Methods for big hierarchy. 
Fixes #10581

### CODE REVIEW

**Comment by geoand** [comment]
Thanks a lot for the PR!

I didn't look at the implementation, but the tests are failing, so there is definitely something wrong :)

In addition to having the existing tests passing, we would need a test case for this feature

**Comment by geoand** [comment]
The current tests are passing, :+1: 

Now what we need to merge the PR is a test case showing that this PR fixes

**Comment by nebrass** [comment]
@geoand I added more modifications and the required tests :grinning:

**Comment by geoand** [comment]
Thanks.

I'll check tomorrow

File: extensions/spring-data-jpa/deployment/src/main/java/io/quarkus/spring/data/deployment/MethodNameParser.java [hunk 1]
```diff
@@ -253,6 +255,74 @@ public Result parse(MethodInfo methodInfo) {
 
             String upperPrefix = (ignoreCase || allIgnoreCase) ? "UPPER(" : "";
             String upperSuffix = (ignoreCase || allIgnoreCase) ? ")" : "";
+
+            // If the fieldName is not a field in the class and in camelcase format,
+            // then split it as hierarchy of fields
+            if (entityClass.field(fieldName) == null) {
```
Comment (geoand) [inline extensions/spring-data-jpa/deployment/src/main/java/io/quarkus/spring/data/deployment/MethodNameParser.java:261]: I think the entire contents of this `if` could be moved to a dedicated method.

File: extensions/spring-data-jpa/deployment/src/main/java/io/quarkus/spring/data/deployment/MethodNameParser.java [hunk 2]
```diff
@@ -253,6 +255,74 @@ public Result parse(MethodInfo methodInfo) {
...
+                if (indexView.getClassByName(fieldInfo.type().name()) != null) {
+                    childFields.addAll(
+                            indexView.getClassByName(fieldInfo.type().name()).fields()
+                                    .stream()
+                                    .map(FieldInfo::name)
+                                    .collect(Collectors.toList()));
+                }
+
+                // Collecting the inherited fields from the superclass of the actual class
+                if (entityClass.superClassType().name() != null &&
```
Comment (geoand) [inline extensions/spring-data-jpa/deployment/src/main/java/io/quarkus/spring/data/deployment/MethodNameParser.java:280]: As it seems that `indexView.getClassByName((entityClass.superClassType().name())` and `indexView.getClassByName((fieldInfo.type().name())` are used a few times, best move them to a variable with a proper name

File: extensions/spring-data-jpa/deployment/src/main/java/io/quarkus/spring/data/deployment/MethodNameParser.java [hunk 3]
```diff
@@ -253,6 +255,74 @@ public Result parse(MethodInfo methodInfo) {
...
+                for (String fieldInf : childFields) {
+                    if (StringUtils.containsIgnoreCase(fieldName, fieldInf)) {
+                        String newValue = finalName.toString()
+                                .replaceAll("(?i)" + fieldInf, lowerFirstLetter(fieldInf) + ".");
+                        finalName.delete(0, finalName.length());
+                        finalName.append(newValue);
+                    }
+                }
+
+                if (finalName.toString().charAt(finalName.length() - 1) == '.') {
```
Comment (geoand) [inline extensions/spring-data-jpa/deployment/src/main/java/io/quarkus/spring/data/deployment/MethodNameParser.java:319]: Can we have a comment explaining this please?

File: extensions/spring-data-jpa/deployment/src/main/java/io/quarkus/spring/data/deployment/MethodNameParser.java [hunk 4]
```diff
@@ -253,6 +255,74 @@ public Result parse(MethodInfo methodInfo) {
...
+                    childFields.addAll(
+                            indexView.getClassByName(indexView.getClassByName(fieldInfo.type().name())
+                                    .superClassType()
+                                    .name())
+                                    .fields()
+                                    .stream()
+                                    .map(FieldInfo::name).collect(Collectors.toList()));
+                }
+
+                for (String fieldInf : childFields) {
```
Comment (geoand) [inline extensions/spring-data-jpa/deployment/src/main/java/io/quarkus/spring/data/deployment/MethodNameParser.java:310]: A comment on what this section does would be nice

**Review by geoand — COMMENTED** [review]
Great work, thanks!

I added a few minor comments that once taken care of, we can merge.

**Comment by nebrass** [comment]
Thanks @geoand !
I made the requests modifications as requested 🤩  I hope it's ok now 😁

File: extensions/spring-data-jpa/deployment/src/main/java/io/quarkus/spring/data/deployment/MethodNameParser.java [hunk 5]
```diff
@@ -366,6 +375,74 @@ public Result parse(MethodInfo methodInfo) {
...
+        for (String fieldInf : childFields) {
+            if (StringUtils.containsIgnoreCase(fieldName, fieldInf)) {
+                String newValue = finalName.toString()
+                        .replaceAll("(?i)" + fieldInf, lowerFirstLetter(fieldInf) + ".");
+                finalName.delete(0, finalName.length());
+                finalName.append(newValue);
+            }
+        }
+
+        // In some cases; the built hierarchy is ending by a joining point. so we need to remove it
```
Comment (geoand) [inline extensions/spring-data-jpa/deployment/src/main/java/io/quarkus/spring/data/deployment/MethodNameParser.java:437]:
```suggestion
        // In some cases, the built hierarchy is ending by a joining point. so we need to remove it
```

File: extensions/spring-data-jpa/deployment/src/main/java/io/quarkus/spring/data/deployment/MethodNameParser.java [hunk 6]
```diff
@@ -488,7 +565,13 @@ private boolean entityContainsField(String fieldName) {
     }
 
     private FieldInfo getField(String fieldName) {
+        // Before validating the fieldInfo,
+        // we need to split the camelcase format and grap the first item
```
Comment (geoand) [inline extensions/spring-data-jpa/deployment/src/main/java/io/quarkus/spring/data/deployment/MethodNameParser.java:569]:
```suggestion
        // we need to split the camelcase format and grab the first item
```

File: extensions/spring-data-jpa/deployment/src/main/java/io/quarkus/spring/data/deployment/MethodNameParser.java [hunk 7]
```diff
@@ -516,10 +599,13 @@ private FieldInfo getField(String fieldName) {
...
-        if (mappedSuperClassInfos.size() > 0) {
-            return mappedSuperClassInfos;
-        }
-        return Collections.emptyList();
+        return mappedSuperClassInfoElements;
+    }
+
+    private static List<String> splitCamelCaseString(String s) {
+        List<String> result = new ArrayList<>();
+        Collections.addAll(result, s.split("(?<!(^|[A-Z]))(?=[A-Z])|(?<!^)(?=[A-Z][a-z])"));
```
Comment (geoand) [inline extensions/spring-data-jpa/deployment/src/main/java/io/quarkus/spring/data/deployment/MethodNameParser.java:607]: Perhaps add comment about how this works? Regex can be daunting when coming back to them after not having seen them for a while :)

**Review by geoand — COMMENTED** [review]
Added a final round of minor comments / suggestions

File: extensions/spring-data-jpa/deployment/src/main/java/io/quarkus/spring/data/deployment/MethodNameParser.java (hunk 7 above)
Comment (famod) [reply extensions/spring-data-jpa/deployment/src/main/java/io/quarkus/spring/data/deployment/MethodNameParser.java:607]: Do we have a "policy" regarding pre-compiling `Pattern`? Or is ok here if it is re-compiled every time since it probably won't be thousands of invocations and it is "just" deployment code?

https://www.baeldung.com/java-regex-pre-compile

Comment (geoand) [reply extensions/spring-data-jpa/deployment/src/main/java/io/quarkus/spring/data/deployment/MethodNameParser.java:607]: We don't really have one, but in this case it's very unlikely we will run into a bottleneck due to the very small number of methods this case handles.

Comment (nebrass) [reply extensions/spring-data-jpa/deployment/src/main/java/io/quarkus/spring/data/deployment/MethodNameParser.java:607]: @geoand I thought the name of the method was explicit 😅  I will add a comment anyway..
@famod yes it's a code executed only once..

Comment (geoand) [reply extensions/spring-data-jpa/deployment/src/main/java/io/quarkus/spring/data/deployment/MethodNameParser.java:607]: It is, I just want an explanation of the regex itself if possible 😎

Comment (nebrass) [reply extensions/spring-data-jpa/deployment/src/main/java/io/quarkus/spring/data/deployment/MethodNameParser.java:607]: @geoand I found a better choice.. in the apache commons there is the same method `StringUtils.splitByCharacterTypeCamelCase()` 😁

Comment (geoand) [reply extensions/spring-data-jpa/deployment/src/main/java/io/quarkus/spring/data/deployment/MethodNameParser.java]: Even better!

**Review by geoand — APPROVED** [review]
Thanks a lot!

**Comment by nebrass** [comment]
> Thanks a lot!

Thank you @geoand for your help and availability ! 🥳  I'm celebrating my first PR in Quarkus ! 🤩

**Comment by geoand** [comment]
:balloon: :tada:

**Comment by gsmet** [comment]
Merged, thanks!
