### PR TITLE
Fail smallrye-jwt build if @Claim types are injected without ClaimValue in ApplicationScoped beans

### LINKED ISSUE #1710: smallrye-jwt returns stale claim data from previous JWT
It seems that the quarkus smallrye-jwt integration holds on to values from previous JWT invocations and returns stale claim values instead of the ones from the current JWT.

E.g. accessing `currentUsername` always returns the value from the first JWT that was used to call the `/data/user` endpoint.
```java
import org.eclipse.microprofile.jwt.Claim;
import org.eclipse.microprofile.jwt.Claims;

import javax.annotation.security.RolesAllowed;
import javax.inject.Inject;
import javax.json.Json;
import javax.json.JsonString;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import java.util.Optional;

@Path("/data")
public class DataResource {

    private static final JsonString ANOYNMOUS = Json.createValue("anonymous");
   
    @Inject
    @Claim(standard = Claims.preferred_username)
    Optional<JsonString> currentUsername;

    @GET
    @Path("/user")
    @Produces(MediaType.TEXT_PLAIN)
    @RolesAllowed({"user"})
    public String userData() {
        return "data for user " + currentUsername.orElse(ANOYNMOUS);
    }
}
```
See discussion on twitter: https://twitter.com/thomasdarimont/status/1110569492520808450
The following example helps to reproduce the issue: https://github.com/thomasdarimont/quarkus-keycloak-demo

### PR DESCRIPTION
**Pull request by sberyozkin**
Fixes #1710

Injecting non-proxiable MP-JWT `@Claim` types into `@ApplicationScoped` or `@Singleton` beans is, per CDI rules, leads to a single injection and stale values reported across multiple requests.

Makes sense to fail the build proactively to avoid users being surprised.
This PR also removes the wrong legacy test code which was asserting that the stale claim values were returned for the test to pass - it can not be correct.

### CODE REVIEW

**Comment by sberyozkin** [comment]
I don't think we should mark it as a breaking change as it really will help to fix the user bugs - we don't recommend/suggest anywhere to inject `@Claim` values directly in non-`@RequestScoped` beans.

I'd consider backporting it at least to 3.4.x or even to all currently supported branches - what does everyone think ?

File: extensions/smallrye-jwt/deployment/src/main/java/io/quarkus/smallrye/jwt/deployment/SmallRyeJwtProcessor.java [hunk 1]
```diff
@@ -161,14 +165,35 @@ void registerOptionalClaimProducer(BeanRegistrationPhaseBuildItem beanRegistrati
...
+                                        + ", make the bean @RequestScoped or wrap this type with org.eclipse.microprofile.jwt.ClaimValue"
+                                        + " or jakarta.inject.Provider or jakarta.enterprise.inject.Instance",
+                                actualType.name());
+                        throw new IllegalStateException(error);
+                    }
+                }
+
+                if (providerType) {
+                    // Classes from jakarta.json are handled specially
+                    if (actualType.name().equals(DotNames.OPTIONAL) && !actualType.name().toString()
```
Comment (michalvavrik) [inline extensions/smallrye-jwt/deployment/src/main/java/io/quarkus/smallrye/jwt/deployment/SmallRyeJwtProcessor.java:190]: This is not a new code, but you are moving it, so it should also be part of the review. If `actualType.name().equals(DotNames.OPTIONAL)` which is `java.util.Optional`, then `toString()` for `DotName` is `java.util.Optional`.  So `&& !actualType.name().toString().startsWith("jakarta.json")` is implicitly true for `Optional`.

File: extensions/smallrye-jwt/deployment/src/main/java/io/quarkus/smallrye/jwt/deployment/SmallRyeJwtProcessor.java [hunk 2]
```diff
@@ -161,14 +165,35 @@ void registerOptionalClaimProducer(BeanRegistrationPhaseBuildItem beanRegistrati
...
+
                 Type actualType = injectionPoint.getRequiredType();
-                if (actualType.name().equals(DotNames.OPTIONAL) && !actualType.name().toString()
-                        .startsWith("jakarta.json")) {
-                    additionalTypes.add(actualType);
+
+                Optional<BeanInfo> bean = injectionPoint.getTargetBean();
+                if (bean.isPresent()) {
+                    DotName scope = bean.get().getScope().getDotName();
+                    if ((DotNames.SINGLETON.equals(scope) || DotNames.APPLICATION_SCOPED.equals(scope))
```
Comment (michalvavrik) [inline extensions/smallrye-jwt/deployment/src/main/java/io/quarkus/smallrye/jwt/deployment/SmallRyeJwtProcessor.java:177]: What happens if scope is `Dependent` and the bean is injected into `Singleton` bean?

Comment (michalvavrik) [reply extensions/smallrye-jwt/deployment/src/main/java/io/quarkus/smallrye/jwt/deployment/SmallRyeJwtProcessor.java:177]: I mean, if the claim is dependent injected into dependent bean injected into singleton, it will still have stale value, will it not?

File: extensions/smallrye-jwt/deployment/src/main/java/io/quarkus/smallrye/jwt/deployment/SmallRyeJwtProcessor.java (hunk 1 above)
Comment (sberyozkin) [reply extensions/smallrye-jwt/deployment/src/main/java/io/quarkus/smallrye/jwt/deployment/SmallRyeJwtProcessor.java:190]: @michalvavrik I honestly don't know what this code does - Martin @mkouba, do you recall its purpose ?

Comment (sberyozkin) [reply extensions/smallrye-jwt/deployment/src/main/java/io/quarkus/smallrye/jwt/deployment/SmallRyeJwtProcessor.java:190]: Oh I see, @michalvavrik, we can just remove this extra boolean check, thanks for spotting, and yes, recall now what this code does after all :-), there is some special handling for the Optional type

File: extensions/smallrye-jwt/deployment/src/main/java/io/quarkus/smallrye/jwt/deployment/SmallRyeJwtProcessor.java (hunk 2 above)
Comment (sberyozkin) [reply extensions/smallrye-jwt/deployment/src/main/java/io/quarkus/smallrye/jwt/deployment/SmallRyeJwtProcessor.java:177]: @michalvavrik I see, so I believe I need to tune and fail the build if the raw @Claim is injected in any but `@RequestScoped` bean, correct ?

Comment (michalvavrik) [reply extensions/smallrye-jwt/deployment/src/main/java/io/quarkus/smallrye/jwt/deployment/SmallRyeJwtProcessor.java:177]: I think it would be the simplest way yes. You can also keep iterate over bean injection tree until you determine non-dependent one. Personally I'd require `@RequestScope`.

File: extensions/smallrye-jwt/deployment/src/main/java/io/quarkus/smallrye/jwt/deployment/SmallRyeJwtProcessor.java (hunk 1 above)
Comment (sberyozkin) [reply extensions/smallrye-jwt/deployment/src/main/java/io/quarkus/smallrye/jwt/deployment/SmallRyeJwtProcessor.java]: @michalvavrik @mkouba I've removed the redundant `jakarta.json` check - it might've been needed in some form in the early days, but all passes now without it. Dropping the Optional check causes failures so I'm keeping it - in any case this is a clean up not related to the PR itself

File: extensions/smallrye-jwt/deployment/src/main/java/io/quarkus/smallrye/jwt/deployment/SmallRyeJwtProcessor.java (hunk 2 above)
Comment (sberyozkin) [reply extensions/smallrye-jwt/deployment/src/main/java/io/quarkus/smallrye/jwt/deployment/SmallRyeJwtProcessor.java]: Indeed, just requiring `RequestScoped` simplifies, thanks

**Review by michalvavrik — APPROVED** [review]
LGTM

File: extensions/smallrye-jwt/deployment/src/main/java/io/quarkus/smallrye/jwt/deployment/SmallRyeJwtProcessor.java [hunk 3]
```diff
@@ -161,14 +168,31 @@ void registerOptionalClaimProducer(BeanRegistrationPhaseBuildItem beanRegistrati
...
+
                 Type actualType = injectionPoint.getRequiredType();
-                if (actualType.name().equals(DotNames.OPTIONAL) && !actualType.name().toString()
-                        .startsWith("jakarta.json")) {
+
+                Optional<BeanInfo> bean = injectionPoint.getTargetBean();
+                if (bean.isPresent()) {
+                    DotName scope = bean.get().getScope().getDotName();
+                    if (!REQUEST_SCOPED_NAME.equals(scope)
+                            && (!providerType && !instanceType && !CLAIM_VALUE_NAME.equals(actualType.name()))) {
```
Comment (mkouba) [inline extensions/smallrye-jwt/deployment/src/main/java/io/quarkus/smallrye/jwt/deployment/SmallRyeJwtProcessor.java:181]: In theory, a user could also inject `io.quarkus.arc.InjectableInstance` for programmatic lookup.

**Review by mkouba — APPROVED** [review]
Looks good.
