### PR TITLE
Redis Client: fix NPE when constructing XPendingSummary

### LINKED ISSUE #45682: decodeAsXPendingSummary NPE on r.get(1) or r.get(2)
The xpending command can return null for lowest, hightest and consumer

https://github.com/quarkusio/quarkus/blob/main/extensions/redis-client/runtime/src/main/java/io/quarkus/redis/runtime/datasource/ReactiveStreamCommandsImpl.java#L367-L381

### PR DESCRIPTION
**Pull request by Ladicek**
Certain fields that were deemed to be mandatory can in fact be `null`, as demonstrated in newly added tests.

Also, this commit fixes translating `XTrimArgs` to the actual argument array in case `MAXLEN` is set to `0`. That is, in fact, a valid value, as demonstrated by the newly added tests and also by inspecting Redis source code [1].

[1] https://github.com/redis/redis/blob/7.2.4/src/t_stream.c#L941

Fixes #45682

### CODE REVIEW

File: extensions/redis-client/runtime/src/main/java/io/quarkus/redis/runtime/datasource/ReactiveStreamCommandsImpl.java [hunk 1]
```diff
@@ -370,12 +370,14 @@ protected XPendingSummary decodeAsXPendingSummary(Response r) {
...
-        var highest = r.get(2).toString();
+        var lowest = r.get(1) != null ? r.get(1).toString() : null;
+        var highest = r.get(2) != null ? r.get(2).toString() : null;
 
         Map<String, Long> consumers = new HashMap<>();
-        for (Response nested : r.get(3)) {
-            consumers.put(nested.get(0).toString(), nested.get(1).toLong());
+        if (r.get(3) != null) {
+            for (Response nested : r.get(3)) {
+                consumers.put(nested.get(0).toString(), nested.get(1).toLong());
```
Comment (gsmet) [inline extensions/redis-client/runtime/src/main/java/io/quarkus/redis/runtime/datasource/ReactiveStreamCommandsImpl.java:379]: In there we are sure the values are not null? If so, LGTM!

**Review by gsmet — APPROVED** [review]
I added a small question but in general LGTM.

I will let @cescoffier approve and merge though.

File: extensions/redis-client/runtime/src/main/java/io/quarkus/redis/runtime/datasource/ReactiveStreamCommandsImpl.java (hunk 1 above)
Comment (Ladicek) [reply extensions/redis-client/runtime/src/main/java/io/quarkus/redis/runtime/datasource/ReactiveStreamCommandsImpl.java:379]: I'm pretty sure that both the keys and the values are never `null`, but not completely, to be honest.

Comment (cescoffier) [reply extensions/redis-client/runtime/src/main/java/io/quarkus/redis/runtime/datasource/ReactiveStreamCommandsImpl.java:379]: me neither - it's not really said on the command documentation. I think it's good to go.

**Review by cescoffier — APPROVED** [review]
