### PR TITLE
Gradle dev mode test support and basic test

### LINKED ISSUE #9090: Quarkus 1.4.2: QuarkusDev not finding @Named injections of another module (build works
**Describe the bug**
When injecting beans with `@Named` from a submodule, `quarkusDev` fails to inject the beans while `quarkusBuild` builds successfully and runs the build as well. The same code also works with Quarkus 1.4.1 with quarkusDev. 

Exception: 

```
16:09:45: Executing tasks 'clean quarkusDev'...

> Task :quarkus:clean UP-TO-DATE
> Task :quarkus:processResources
> Task :common:compileJava
> Task :quarkus:compileJava
> Task :quarkus:classes

> Task :quarkus:quarkusDev
Listening for transport dt_socket at address: 5005
2020-05-05 16:09:49,450 INFO  [org.jbo.threads] (main) JBoss Threads version 3.1.1.Final
2020-05-05 16:09:49,861 ERROR [io.qua.dep.dev.DevModeMain] (main) Failed to start Quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: Found 2 deployment problems: 
[1] Unsatisfied dependency for type org.acme.common.health.HealthStatus and qualifiers [@Named(value = "Status2")]
	- java member: org.acme.app.Service2#healthStatus
	- declared on CLASS bean [types=[org.acme.app.Service2, java.lang.Object], qualifiers=[@Default, @Any], target=org.acme.app.Service2]
[2] Unsatisfied dependency for type org.acme.common.health.HealthStatus and qualifiers [@Named(value = "Status1")]
	- java member: org.acme.app.Service1#healthStatus
	- declared on CLASS bean [types=[org.acme.app.Service1, java.lang.Object], qualifiers=[@Default, @Any], target=org.acme.app.Service1]
	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:981)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:240)
	at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:135)
	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:358)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:931)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
	Suppressed: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.acme.common.health.HealthStatus and qualifiers [@Named(value = "Status2")]
	- java member: org.acme.app.Service2#healthStatus
	- declared on CLASS bean [types=[org.acme.app.Service2, java.lang.Object], qualifiers=[@Default, @Any], target=org.acme.app.Service2]
		at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:486)
		at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:362)
		at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:232)
		... 14 more
	Suppressed: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.acme.common.health.HealthStatus and qualifiers [@Named(value = "Status1")]
	- java member: org.acme.app.Service1#healthStatus
	- declared on CLASS bean [types=[org.acme.app.Service1, java.lang.Object], qualifiers=[@Default, @Any], target=org.acme.app.Service1]
		at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:486)
		at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:362)
		at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:232)
		... 14 more

	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:247)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:130)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:52)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:62)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:268)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:40)
	at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:129)
	at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:82)
	at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:119)
	at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:56)
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: Found 2 deployment problems: 
[1] Unsatisfied dependency for type org.acme.common.health.HealthStatus and qualifiers [@Named(value = "Status2")]
	- java member: org.acme.app.Service2#healthStatus
	- declared on CLASS bean [types=[org.acme.app.Service2, java.lang.Object], qualifiers=[@Default, @Any], target=org.acme.app.Service2]
[2] Unsatisfied dependency for type org.acme.common.health.HealthStatus and qualifiers [@Named(value = "Status1")]
	- java member: org.acme.app.Service1#healthStatus
	- declared on CLASS bean [types=[org.acme.app.Service1, java.lang.Object], qualifiers=[@Default, @Any], target=org.acme.app.Service1]
	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:981)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:240)
	at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:135)
	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:358)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:931)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
	Suppressed: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.acme.common.health.HealthStatus and qualifiers [@Named(value = "Status2")]
	- java member: org.acme.app.Service2#healthStatus
	- declared on CLASS bean [types=[org.acme.app.Service2, java.lang.Object], qualifiers=[@Default, @Any], target=org.acme.app.Service2]
		at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:486)
		at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:362)
		at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:232)
		... 14 more
	Suppressed: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.acme.common.health.HealthStatus and qualifiers [@Named(value = "Status1")]
	- java member: org.acme.app.Service1#healthStatus
	- declared on CLASS bean [types=[org.acme.app.Service1, java.lang.Object], qualifiers=[@Default, @Any], target=org.acme.app.Service1]
		at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:486)
		at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:362)
		at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:232)
		... 14 more

	at io.quarkus.builder.Execution.run(Execution.java:115)
	at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:156)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:245)
	... 9 more
Caused by: javax.enterprise.inject.spi.DeploymentException: Found 2 deployment problems: 
[1] Unsatisfied dependency for type org.acme.common.health.HealthStatus and qualifiers [@Named(value = "Status2")]
	- java member: org.acme.app.Service2#healthStatus
	- declared on CLASS bean [types=[org.acme.app.Service2, java.lang.Object], qualifiers=[@Default, @Any], target=org.acme.app.Service2]
[2] Unsatisfied dependency for type org.acme.common.health.HealthStatus and qualifiers [@Named(value = "Status1")]
	- java member: org.acme.app.Service1#healthStatus
	- declared on CLASS bean [types=[org.acme.app.Service1, java.lang.Object], qualifiers=[@Default, @Any], target=org.acme.app.Service1]
	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:981)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:240)
	at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:135)
	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:358)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:931)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
	Suppressed: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.acme.common.health.HealthStatus and qualifiers [@Named(value = "Status2")]
	- java member: org.acme.app.Service2#healthStatus
	- declared on CLASS bean [types=[org.acme.app.Service2, java.lang.Object], qualifiers=[@Default, @Any], target=org.acme.app.Service2]
		at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:486)
		at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:362)
		at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:232)
		... 14 more
	Suppressed: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.acme.common.health.HealthStatus and qualifiers [@Named(value = "Status1")]
	- java member: org.acme.app.Service1#healthStatus
	- declared on CLASS bean [types=[org.acme.app.Service1, java.lang.Object], qualifiers=[@Default, @Any], target=org.acme.app.Service1]
		at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:486)
		at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:362)
		at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:232)
		... 14 more

2020-05-05 16:09:49,861 INFO  [io.qua.dep.dev.DevModeMain] (main) Attempting to start hot replacement endpoint to recover from previous Quarkus startup failure

> Task :quarkus:quarkusDev FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:command_line_warnings
5 actionable tasks: 4 executed, 1 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':quarkus:quarkusDev'.
> Build cancelled while executing task ':quarkus:quarkusDev'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
16:09:52: Tasks execution finished 'clean quarkusDev'.
```

**To Reproduce**
1. Download and unzip reproducer 
[named-injection.zip](https://github.com/quarkusio/quarkus/files/4581236/named-injection.zip)
2. Run `./gradlew quarkusDev` to see the error shown above.
3. Run `./gradlew build` => works
4. Downgrade to Quarkus 1.4.1.Final => works with quarkus dev as well.

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Environment (please complete the following information):**
 - Windows 10
- Java 11
- Quarkus 1.4.2.Final

### LINKED ISSUE #9137: quarkusDev fails to work consistently across gradle subprojects
**Describe the bug**
I'm running into a lot of issues when implementing with a multi-module gradle project.

I thought it was related to #9090 

https://github.com/danelowe/quarkusmm
(https://github.com/danelowe/quarkusmm/tree/0ae48c62c84b4f1f292e4589116152350035acaa)

**Expected behavior**

- When running `quarkusDev`, the `/hello` route would return `"hello"`
- When there is no code in the root project, it would still build.

**Actual behavior**

- When running `quarkusDev`, the `/hello` route returns 404 error
- When running `quarkusBuild`, and then running the jar, the `/hello` route returns `"hello"`
- The project needs the empty `Application` class, otherwise it fails to build.

**To Reproduce**
https://github.com/danelowe/quarkusmm

clone master branch and run `./gradlew quarkusDev`

**Additional context**
As per workaround mentioned in #9090, this example _works_ when running  `./gradlew web:quarkusDev`, however, if you look at the `ports` branch you'll see an example of the project structure I'm hoping to achieve.

https://github.com/danelowe/quarkusmm/tree/17861ed082328a42fad72ebffb7484bd8c37f97d

I'm unable to get the `ports` branch to run or build. I'm not sure if this is because I have implemented it incorrectly, or if there is a bug or missing documentation, or this use case is not supported.

`Caused by: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type com.example.quarkusmm.port.CustomerService and qualifiers [@Default]`

Also, I cannot run this branch via the Main class

`io.quarkus.bootstrap.BootstrapException: Failed to determine the Maven artifact associated with the application`

### PR DESCRIPTION
**Pull request by aloubyansky**
* Basic Gradle quarkusDev test
* Include resources directories into the build classpath in dev mode
* Include all the artifact's paths into the index if at least one of the artifact's dirs contains a marker file

Fixes #9090
Fixes #9137

### CODE REVIEW

File: core/deployment/src/main/java/io/quarkus/deployment/index/ApplicationArchiveBuildStep.java [hunk 1]
```diff
@@ -171,47 +169,41 @@ ApplicationArchivesBuildItem build(
...
             throws IOException {
-        List<Path> ret = new ArrayList<>();
-        for (String file : applicationArchiveFiles) {
-            Enumeration<URL> e = classLoader.getResources(file);
-            while (e.hasMoreElements()) {
-                final URL url = e.nextElement();
-                final Path path = urlToPath(url, file);
-                if (!root.isExcludedFromIndexing(path)) {
-                    ret.add(path);
+        for (AppDependency dep : curateOutcomeBuildItem.getEffectiveModel().getFullDeploymentDeps()) {
```
Comment (aloubyansky) [inline core/deployment/src/main/java/io/quarkus/deployment/index/ApplicationArchiveBuildStep.java:175]: This may need adjustment. Previously it used to look for the markers in the deployment classloader, which includes more resources than the list of the deployment deps the resolver returns.

**Comment by aloubyansky** [comment]
Ok, so kotlin compiler does not support Java 14
```
java.lang.RuntimeException: Compilation failed. Unknown JVM target version: 14
Supported versions: 1.6, 1.8, 9, 10, 11, 12, 13
	at io.quarkus.kotlin.deployment.KotlinCompilationProvider.compile(KotlinCompilationProvider.java:82)
```

File: core/deployment/src/main/java/io/quarkus/deployment/index/ApplicationArchiveBuildStep.java (hunk 1 above)
Comment (stuartwdouglas) [reply core/deployment/src/main/java/io/quarkus/deployment/index/ApplicationArchiveBuildStep.java:178]: Yea, this needs to be user deps, not deployment deps.

**Review by stuartwdouglas — CHANGES_REQUESTED** [review]

File: core/deployment/src/main/java/io/quarkus/deployment/index/ApplicationArchiveBuildStep.java (hunk 1 above)
Comment (aloubyansky) [reply core/deployment/src/main/java/io/quarkus/deployment/index/ApplicationArchiveBuildStep.java]: Done.

**Review by stuartwdouglas — APPROVED** [review]

**Comment by andreas-eberle** [comment]
Won't this be part in 1.4.3?
