### PR TITLE
Qute Type-safe Templates - fix template path validation

### LINKED ISSUE #12355: NullPointerException when rendering Qute templates as XML
**Describe the bug**

```
Caused by: java.lang.NullPointerException
	at io.quarkus.qute.runtime.TemplateProducer$InjectableTemplateInstanceImpl.templateInstance(TemplateProducer.java:168)
	at io.quarkus.qute.runtime.TemplateProducer$InjectableTemplateInstanceImpl.render(TemplateProducer.java:149)
	at micro.apps.greeting.GreetingResource.hello(GreetingResource.java:30)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:167)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:638)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:504)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:454)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:456)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:417)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:391)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:68)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:488)
	... 20 more
```

**Expected behavior**
Render the template

**Actual behavior**
NullPointerException is thrown

**To Reproduce**

[greeting-quarkus.zip](https://github.com/quarkusio/quarkus/files/5286885/greeting-quarkus.zip)

1. Run `mvn quarkus:dev` in the attached project above
2. `curl http://localhost:8080/greeting` and you should see the error

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Fedora 32 
 - Output of `java -version`: 11
 - GraalVM version (if different from Java): Not used 
 - Quarkus version or git rev: 1.8.1.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/linuxbrew/.linuxbrew/Cellar/maven/3.6.3/libexec
Java version: 11.0.8, vendor: N/A, runtime: /home/ggastald/.sdkman/candidates/java/11.0.8-open
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.8.7-200.fc32.x86_64", arch: "amd64", family: "unix"
```

### PR DESCRIPTION
**Pull request by mkouba**
- also add more meaningful error message if a template matches the path
but the file suffix is not configured via quarkus.qute.suffixes
- resolves #12355

### CODE REVIEW

File: extensions/qute/deployment/src/main/java/io/quarkus/qute/deployment/QuteProcessor.java [hunk 1]
```diff
@@ -246,6 +247,20 @@ AdditionalBeanBuildItem additionalBeans() {
         checkedTemplateAnnotations.addAll(index.getIndex().getAnnotations(Names.CHECKED_TEMPLATE_OLD));
         checkedTemplateAnnotations.addAll(index.getIndex().getAnnotations(Names.CHECKED_TEMPLATE));
 
+        // Build a set of file paths for validation
+        Set<String> filePaths = new HashSet<String>();
```
Comment (gastaldi) [inline extensions/qute/deployment/src/main/java/io/quarkus/qute/deployment/QuteProcessor.java:251]: Does order matter here?

**Review by gastaldi — APPROVED** [review]
LGTM

File: extensions/qute/deployment/src/main/java/io/quarkus/qute/deployment/QuteProcessor.java (hunk 1 above)
Comment (mkouba) [reply extensions/qute/deployment/src/main/java/io/quarkus/qute/deployment/QuteProcessor.java:251]: It should not...

**Comment by gsmet** [comment]
CI failed with:
```
2021-03-02T19:22:51.8960176Z [ERROR] io.quarkus.resteasy.reactive.qute.deployment.MissingTemplateTest  Time elapsed: 0.807 s  <<< FAILURE!
2021-03-02T19:22:51.8962316Z java.lang.AssertionError: COM01003: Internal error: Assertion failure: Expected boolean value to be false
2021-03-02T19:22:51.8963621Z 	at org.wildfly.common.Assert.assertTrue(Assert.java:520)
2021-03-02T19:22:51.8966057Z 	at io.quarkus.resteasy.reactive.qute.deployment.MissingTemplateTest.lambda$static$1(MissingTemplateTest.java:20)
2021-03-02T19:22:51.8968705Z 	at io.quarkus.test.QuarkusUnitTest.beforeAll(QuarkusUnitTest.java:490)
2021-03-02T19:22:51.8971857Z 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$8(ClassBasedTestDescriptor.java:368)
2021-03-02T19:22:51.8975676Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2021-03-02T19:22:51.9032805Z 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:368)
2021-03-02T19:22:51.9037146Z 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:192)
2021-03-02T19:22:51.9040649Z 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:78)
2021-03-02T19:22:51.9044035Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:136)
2021-03-02T19:22:51.9047504Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
```

**Comment by gsmet** [comment]
Btw, we shouldn't use `org.wildfly.common.Assert`.

**Comment by mkouba** [comment]
> Btw, we shouldn't use `org.wildfly.common.Assert`.

Sure thing. I'm not the original author of the test though ;-).

The test should be fixed now.
