### PR TITLE
OpenTelemetry: NPE in HttpInstrumenterVertxTracer.RouteGetter when request got cancelled

### LINKED ISSUE #26764: OpenTelemetry: NPE in HttpInstrumenterVertxTracer.RouteGetter when request got cancelled
### Describe the bug

Relates to [#26356](https://github.com/quarkusio/quarkus/pull/26356/files#diff-8dd25e6bcffd41aa6d82e224799fbf61b9708d6d8a3ead2c7ed32ad261d62cccR152):
Using a vert.x HTTP server along with `quarkus-opentelemetry`, we are seeing such exceptions in the logs:
```
java.lang.NullPointerException: Cannot invoke "io.vertx.core.spi.observability.HttpResponse.statusCode()" because "response" is null
	at io.quarkus.opentelemetry.runtime.tracing.vertx.HttpInstrumenterVertxTracer$RouteGetter.get(HttpInstrumenterVertxTracer.java:153)
	at io.quarkus.opentelemetry.runtime.tracing.vertx.HttpInstrumenterVertxTracer$RouteGetter.get(HttpInstrumenterVertxTracer.java:136)
	at io.opentelemetry.instrumentation.api.instrumenter.http.HttpRouteHolder.updateHttpRoute(HttpRouteHolder.java:125)
	at io.quarkus.opentelemetry.runtime.tracing.vertx.HttpInstrumenterVertxTracer.sendResponse(HttpInstrumenterVertxTracer.java:94)
	at io.quarkus.opentelemetry.runtime.tracing.vertx.HttpInstrumenterVertxTracer.sendResponse(HttpInstrumenterVertxTracer.java:41)
	at io.quarkus.opentelemetry.runtime.tracing.vertx.OpenTelemetryVertxTracer.sendResponse(OpenTelemetryVertxTracer.java:47)
	at io.quarkus.opentelemetry.runtime.tracing.vertx.OpenTelemetryVertxTracer.sendResponse(OpenTelemetryVertxTracer.java:16)
	at io.vertx.core.http.impl.Http1xServerRequest.reportRequestReset(Http1xServerRequest.java:645)
	at io.vertx.core.http.impl.Http1xServerRequest.handleException(Http1xServerRequest.java:623)
	at io.vertx.core.http.impl.Http1xServerConnection.lambda$handleClosed$6(Http1xServerConnection.java:455)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:71)
	at io.vertx.core.impl.DuplicatedContext.execute(DuplicatedContext.java:163)
	at io.vertx.core.impl.AbstractContext.execute(AbstractContext.java:58)
	at io.vertx.core.http.impl.Http1xServerConnection.handleClosed(Http1xServerConnection.java:454)
	at io.vertx.core.net.impl.VertxHandler.channelInactive(VertxHandler.java:143)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
[...]
```

They occur when a client cancels a request before the server has sent a response.

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.10.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by tmihalac**
Fixes https://github.com/quarkusio/quarkus/issues/26764

Signed-off-by: Theodor Mihalache <tmihalac@redhat.com>

### CODE REVIEW

**Review by radcortez — CHANGES_REQUESTED** [review]
There are other places we call `response.get*`, so maybe we need to address those.

**Comment by gsmet** [comment]
@radcortez but will you call the methods of `ServerAttributesExtractor` if you don't have a response? Because AFAICS, the others are in the extractor.

**Comment by gsmet** [comment]
@tmihalac can you adjust and also be null safe for the methods in `ServerAttributesExtractor` that are manipulating `response`? From what I can see, you can return null if the response is null.

**Comment by tmihalac** [comment]
> @tmihalac can you adjust and also be null safe for the methods in `ServerAttributesExtractor` that are manipulating `response`? From what I can see, you can return null if the response is null.

So all I need to do is to be null safe with the response in ServerAttributesExtractor ?

**Review by gsmet — COMMENTED** [review]
Apart from my small comment, I think it makes sense.

But I will let @radcortez have the final say.

File: extensions/opentelemetry/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/vertx/HttpInstrumenterVertxTracer.java [hunk 1]
```diff
@@ -246,7 +248,7 @@ public Long responseContentLengthUncompressed(final HttpRequest request, final H
 
         @Override
         public List<String> responseHeader(final HttpRequest request, final HttpResponse response, final String name) {
-            return response.headers().getAll(name);
+            return response != null ? response.headers().getAll(name) : new ArrayList<>();
```
[the remark this answers is not in the document]
Comment (gsmet) [reply extensions/opentelemetry/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/vertx/HttpInstrumenterVertxTracer.java:251]: Important point: doing this because I don't expect anyone to write to this list so it can be an immutable empty list.

**Comment by gsmet** [comment]
For the formatting issues, I recommend you have a look at: https://github.com/quarkusio/quarkus/blob/main/CONTRIBUTING.md#ide-config-and-code-style .
And also run the formatter before pushing if you have doubts. But frankly, you should always build before pushing to check things at least compile.

Also, time for you to learn how to squash your commits yourself :).

What I personally do is:
```
git rebase -i <hash of the commit before my first change>
```
This will open an editor.
I keep `p` for the first commit and put `f` for the commit I want to squash. Then close the editor and Git should squash the commits. You can then force push to your branch.

Note: be careful when doing that as you rewrite the history.

File: extensions/opentelemetry/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/vertx/HttpInstrumenterVertxTracer.java [hunk 2]
```diff
@@ -231,12 +232,12 @@ public Long requestContentLengthUncompressed(final HttpRequest request, final Ht
 
         @Override
         public Integer statusCode(final HttpRequest request, final HttpResponse response) {
-            return response.statusCode();
+            return response != null ? response.statusCode() : 499;
```
Comment (radcortez) [inline extensions/opentelemetry/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/vertx/HttpInstrumenterVertxTracer.java:235]: Please, return `null` here if the `response` is null. The extractor can handle such return value.

File: extensions/opentelemetry/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/vertx/HttpInstrumenterVertxTracer.java [hunk 3]
```diff
@@ -231,12 +232,12 @@ public Long requestContentLengthUncompressed(final HttpRequest request, final Ht
...
         }
 
         @Override
         public Long responseContentLength(final HttpRequest request, final HttpResponse response) {
-            return getContentLength(response.headers());
+            return response != null ? getContentLength(response.headers()) : 0;
```
Comment (radcortez) [inline extensions/opentelemetry/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/vertx/HttpInstrumenterVertxTracer.java:240]: Please, return `null` here if the `response` is null. The extractor can handle such return value.

**Review by radcortez — CHANGES_REQUESTED** [review]

File: extensions/opentelemetry/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/vertx/HttpInstrumenterVertxTracer.java (hunk 2 above)
Comment (gsmet) [reply extensions/opentelemetry/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/vertx/HttpInstrumenterVertxTracer.java:235]: Ah yes, I thought it made sense but apparently `499` is specific to Nginx and is not standard.

**Review by radcortez — APPROVED** [review]

**Comment by radcortez** [comment]
Thank you!
