### PR TITLE
Make JSON exporter's route blocking

### LINKED ISSUE #23661: Micrometer JSON registry uses a non-blocking route
### Describe the bug

... so if there are gauges which require a blocking operation to get the value, then the call to `/metrics` fails

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

Use `quarkus.micrometer.export.json.enabled=true` and register a gauge that requires a blocking operation to retrieve the value, and then request a JSON export from `/metrics`

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

see discussion https://github.com/quarkusio/quarkus/discussions/23605

### PR DESCRIPTION
**Pull request by jmartisk**
Fixes #23661

### CODE REVIEW

File: extensions/micrometer/deployment/src/main/java/io/quarkus/micrometer/deployment/export/JsonRegistryProcessor.java [hunk 1]
```diff
@@ -45,6 +45,7 @@ public void initializeJsonRegistry(MicrometerConfig config,
         routes.produce(nonApplicationRootPathBuildItem.routeBuilder()
                 .routeFunction(config.export.json.path, recorder.route())
                 .handler(recorder.getHandler())
+                .blockingRoute()
```
Comment (ebullient) [inline extensions/micrometer/deployment/src/main/java/io/quarkus/micrometer/deployment/export/JsonRegistryProcessor.java:48]: I thought I did this?! :sigh:

**Review by ebullient — APPROVED** [review]
