### PR TITLE
Optionally run DNS lookup for OIDC server requests on worker thread

### LINKED ISSUE #35993: Event-loop thread blocked when connecting to an unavailable OIDC server
### Describe the bug

A Vertx Thread blocked exception occurs when a Quarkus system starts and tries to connect to a OIDC server which is not available:

```
2023-09-18 11:26:02,847 WARN  [io.ver.cor.imp.BlockedThreadChecker] (vertx-blocked-thread-checker) Thread Thread[vert.x-eventloop-thread-1,5,main] has been blocked for 5844 ms, time limit is 2000 ms: io.vertx.core.VertxException
: Thread blocked
        at java.base@17.0.8/java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
        at java.base@17.0.8/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:934)
        at java.base@17.0.8/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1543)
        at java.base@17.0.8/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:852)
        at java.base@17.0.8/java.net.InetAddress.getAllByName0(InetAddress.java:1533)
        at java.base@17.0.8/java.net.InetAddress.getAllByName(InetAddress.java:1385)
        at java.base@17.0.8/java.net.InetAddress.getAllByName(InetAddress.java:1306)
        at java.base@17.0.8/java.net.InetAddress.getByName(InetAddress.java:1256)
        at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
        at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
        at java.base@17.0.8/java.security.AccessController.executePrivileged(AccessController.java:807)
        at java.base@17.0.8/java.security.AccessController.doPrivileged(AccessController.java:569)
        at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
        at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
        at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
        at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
        at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
        at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
        at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
        at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
        at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:162)
        at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:139)
        at io.vertx.core.net.impl.ChannelProvider.handleConnect(ChannelProvider.java:152)
        at io.vertx.core.net.impl.ChannelProvider.connect(ChannelProvider.java:103)
        at io.vertx.core.net.impl.ChannelProvider.connect(ChannelProvider.java:89)
        at io.vertx.core.net.impl.NetClientImpl.connectInternal2(NetClientImpl.java:304)
        at io.vertx.core.net.impl.NetClientImpl.lambda$connectInternal$2(NetClientImpl.java:270)
        at io.vertx.core.net.impl.NetClientImpl$$Lambda$342/0x00007f95211d6640.handle(Unknown Source)
        at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
        at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
        at io.vertx.core.impl.future.Mapping.onSuccess(Mapping.java:40)
        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
        at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
        at io.vertx.core.impl.future.Mapping.onSuccess(Mapping.java:40)
        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
        at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
        at io.vertx.core.impl.future.Mapping.onSuccess(Mapping.java:40)
        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
        at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
        at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
        at io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:49)
        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
        at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
        at io.vertx.core.impl.future.Composition$1.onSuccess(Composition.java:62)
        at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
        at io.vertx.core.impl.future.FutureBase$$Lambda$343/0x00007f95211d6868.run(Unknown Source)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base@17.0.8/java.lang.Thread.run(Thread.java:833)

2023-09-18 11:26:04,635 WARN  [io.qua.oid.com.run.OidcCommonUtils] (vert.x-eventloop-thread-1) OIDC Server is not available:: java.net.UnknownHostException: xyz: Name or service not known
        at java.base/java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
        at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:934)
        at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1543)
        at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:852)
        at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1533)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1385)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1306)
        at java.base/java.net.InetAddress.getByName(InetAddress.java:1256)
        at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
        at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
        at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
        at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
        at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
        at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
        at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
        at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
        at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
        at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
        at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:162)
        at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:139)
        at io.vertx.core.net.impl.ChannelProvider.handleConnect(ChannelProvider.java:152)
        at io.vertx.core.net.impl.ChannelProvider.connect(ChannelProvider.java:103)
        at io.vertx.core.net.impl.ChannelProvider.connect(ChannelProvider.java:89)
        at io.vertx.core.net.impl.NetClientImpl.connectInternal2(NetClientImpl.java:304)
        at io.vertx.core.net.impl.NetClientImpl.lambda$connectInternal$2(NetClientImpl.java:270)
        at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
        at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
        at io.vertx.core.impl.future.Mapping.onSuccess(Mapping.java:40)
        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
        at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
        at io.vertx.core.impl.future.Mapping.onSuccess(Mapping.java:40)
        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
        at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
        at io.vertx.core.impl.future.Mapping.onSuccess(Mapping.java:40)
        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
        at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
        at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
        at io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:49)
        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
        at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
        at io.vertx.core.impl.future.Composition$1.onSuccess(Composition.java:62)
        at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:833)

2023-09-18 11:26:04,640 WARN  [io.qua.oid.run.OidcRecorder] (vert.x-eventloop-thread-1) OIDC server is not available at the 'http://xyz' URL. Please make sure it is correct. Note it has to end with a realm value if you work with
2023-09-18 11:26:04,640 WARN  [io.qua.oid.run.OidcRecorder] (vert.x-eventloop-thread-1) Tenant 'Default': 'OIDC Server is not available'. OIDC server is not avai
p://0.0.0.0:8080

```

### Expected behavior

Connecting to an unavailable server does not result in a blocked Thread.

### Actual behavior

2-3 VertxException for blocked event-loop threads are occuring in the logs at application startup.

### How to Reproduce?

Reproducer: https://github.com/siewp/keycloak-issue-reproducer
You can just follow the Readme of the project to reproduce.

1. Configure an oidc auth server which is not available in the application.properties
2. Build the project as a docker container
3. Run the docker container

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by michalvavrik**
I can't really reproduce the issue and I don't think this option can be tested on localhost. Implementation can be improved by inspecting DNS lookup cache TTL and only running blocking lookup when we calculate that hostname is not in cache, but I want to keep it simple as I'm not convinced it's worth to have there something more complex.

- Fixes: #35993

### CODE REVIEW

File: extensions/oidc-common/runtime/src/main/java/io/quarkus/oidc/common/runtime/OidcCommonUtils.java [hunk 1]
```diff
@@ -536,4 +542,37 @@ public static List<OidcRequestFilter> getMatchingOidcRequestFilters(Map<OidcEndp
...
+        if (blockingDnsLookup) {
+            return sendRequest(new Vertx(vertx), request, true);
+        } else {
+            return request.send();
+        }
+    }
+
+    public static Uni<HttpResponse<Buffer>> sendRequest(Vertx vertx, HttpRequest<Buffer> request, boolean blockingDnsLookup) {
+        if (blockingDnsLookup) {
+            return vertx.executeBlocking(new Callable<Void>() {
```
Comment (sberyozkin) [inline extensions/oidc-common/runtime/src/main/java/io/quarkus/oidc/common/runtime/OidcCommonUtils.java:557]: @michalvavrik Hey Michal, what I'm not sure if whether we should use Vertx's own worker pool or if we have something in Quarkus ? @cescoffier Can you please advise ?

**Review by sberyozkin — APPROVED** [review]
LGTM, waiting for the confirmation from @cescoffier re the worker pool

File: extensions/oidc-common/runtime/src/main/java/io/quarkus/oidc/common/runtime/OidcCommonUtils.java (hunk 1 above)
Comment (michalvavrik) [reply extensions/oidc-common/runtime/src/main/java/io/quarkus/oidc/common/runtime/OidcCommonUtils.java:557]: I read it in Vert.x community discussion here https://groups.google.com/g/vertx/c/FgI5sf-DAK0, it is fairly old topic, but I didn't find anything newer. If @cescoffier have better idea I'm happy to dig into it.

Comment (sberyozkin) [reply extensions/oidc-common/runtime/src/main/java/io/quarkus/oidc/common/runtime/OidcCommonUtils.java:557]: @michalvavrik I was thinking of something like running it on the Quarkus Infrastructure pool, something like that, I'm just not sure what is the best recommendation in such cases;

Comment (sberyozkin) [reply extensions/oidc-common/runtime/src/main/java/io/quarkus/oidc/common/runtime/OidcCommonUtils.java:557]: @michalvavrik Oh indeed, I see the Mail client uses the same technique, so it must be good, I'll wait for a bit for Clement to comment and will merge later, thanks

Comment (sberyozkin) [reply extensions/oidc-common/runtime/src/main/java/io/quarkus/oidc/common/runtime/OidcCommonUtils.java:557]: @michalvavrik Sure, I'd just like to have a bit more clarity re using the `Infrastructure.getDefaultWorkerPool()`

Comment (cescoffier) [reply extensions/oidc-common/runtime/src/main/java/io/quarkus/oidc/common/runtime/OidcCommonUtils.java:557]: When using URLs, DNS lookups are blocking. If your DNS server is slow (and the lookup result is not cached), you can block the event loop. So, it's better to offload the lookup when this can happen. 

Vert.x provides an async DNS resolver, but I do not recommend it. DNS is complex, and users are likely using the JVM default behavior.

**Review by cescoffier — APPROVED** [review]

File: extensions/oidc-common/runtime/src/main/java/io/quarkus/oidc/common/runtime/OidcCommonUtils.java (hunk 1 above)
Comment (sberyozkin) [reply extensions/oidc-common/runtime/src/main/java/io/quarkus/oidc/common/runtime/OidcCommonUtils.java:557]: @cescoffier Thanks, can you clarify please if using the `Infrastructure.getDefaultWorkerPool()` to run the blocking call can be more efficient or is it meant for different purposes ? Also we have this executor in the security, 
https://github.com/quarkusio/quarkus/blob/main/extensions/security/runtime/src/main/java/io/quarkus/security/runtime/IdentityProviderManagerCreator.java#L37

I wonder if we should use a single pool, such as the one provided by the security `IdentityProviderManagerCreator` for various blocking tasks in the security flows

Comment (michalvavrik) [reply extensions/oidc-common/runtime/src/main/java/io/quarkus/oidc/common/runtime/OidcCommonUtils.java:557]: >  Also we have this executor in the security,

Just to be clear, we almost never use this executor in security. It is just default implementation for case someone is not relying on the Vert.x HTTP extension. And not using it solved some weird issues, I don't remember details but you can check the PR in which I added this executor and you will see. I think most of our users including all that are using OIDC are using Vert.x `executeBlocking` from here https://github.com/quarkusio/quarkus/blob/main/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/VertxBlockingSecurityExecutor.java

Comment (michalvavrik) [reply extensions/oidc-common/runtime/src/main/java/io/quarkus/oidc/common/runtime/OidcCommonUtils.java:557]: The strange issue was related to HTTP/2 and solved by `executeBlocking` https://github.com/quarkusio/quarkus/issues/34912

Comment (michalvavrik) [reply extensions/oidc-common/runtime/src/main/java/io/quarkus/oidc/common/runtime/OidcCommonUtils.java:557]: BTW I didn't use that executor because this code is in OIDC commons and it does not require security (or it's SPI).

Comment (sberyozkin) [reply extensions/oidc-common/runtime/src/main/java/io/quarkus/oidc/common/runtime/OidcCommonUtils.java:557]: @michalvavrik Sounds good, thanks

**Comment by sberyozkin** [comment]
Thanks

**Comment by sberyozkin** [comment]
@gsmet, please consider it for the backport as it offers an option to avoid quarkus-oidc blocking the even loop thread, reported by Windows/Linux users
