### PR TITLE
Use proper CL when running Google Cloud Functions

### LINKED ISSUE #53812: Using @ConfigProperty with Google Cloud Function throws Exception when executing QuarkusTest
### Describe the bug

When using Google Cloud HTTP Function in combination with a `ConfigProperty`, an Exception is thrown when executing a QuarkusTest calling that Google Cloud HTTP Function. 
This used to work fine in Quarkus Platform version 3.31.4. 
This is not working anymore in Quarkus Platform version 3.32.2 and upwards, including the latest version 3.34.6.

The [sample code](https://github.com/tinohertlein/quarkus-issue) demonstrates this issue by extending the [Quarkus quickstart example](https://github.com/quarkusio/quarkus-quickstarts/tree/main/google-cloud-functions-quickstart) with

- a ConfigProperty
- a test that calls the Google Cloud HTTP Function

### Expected behavior

`QuarkusTest` runs without throwing an Exception.

### Actual behavior

`QuarkusTest` throws the following Exception:

```
Suppressed: java.lang.RuntimeException: Error injecting java.lang.String org.acme.quickstart.service.GreetingService.greeterName 
Caused by: java.lang.IllegalArgumentException: SRCFG00015: No configuration is available for this class loader
```

### How to Reproduce?

Clone the [sample project](https://github.com/tinohertlein/quarkus-issue) and execute the test in [src/test/java/HttpFunctionGreeterTest.java](src/test/java/HttpFunctionGreeterTest.java)

### Output of `uname -a` or `ver`

Darwin MacBook-Pro 25.1.0 Darwin Kernel Version 25.1.0: Mon Oct 20 19:32:41 PDT 2025; root:xnu-12377.41.6~2/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk 25.0.2 2026-01-20 LTS

### Quarkus version or git rev

Quarkus Platform version 3.32.2 and upwards

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.11

### Additional information

This used to work fine in Quarkus Platform version 3.31.4. 
This is not working anymore in Quarkus Platform version 3.32.2 and upwards, including the latest version 3.34.6.

### PR DESCRIPTION
**Pull request by geoand**
- Fixes: #53812

### CODE REVIEW

File: extensions/google-cloud-functions/runtime/src/main/java/io/quarkus/gcp/functions/QuarkusCloudEventsFunction.java [hunk 1]
```diff
@@ -12,10 +12,11 @@
 
 public final class QuarkusCloudEventsFunction implements CloudEventsFunction {
 
-    protected static final String deploymentStatus;
-    protected static boolean started = false;
+    private static final String deploymentStatus;
+    private static boolean started = false;
 
     private static volatile CloudEventsFunction delegate;
+    private static volatile ClassLoader delegateClassLoader;
```
Comment (gsmet) [inline extensions/google-cloud-functions/runtime/src/main/java/io/quarkus/gcp/functions/QuarkusCloudEventsFunction.java:19]: Do we need to reset it on shutdown? Can't it be an issue with dev mode?

File: extensions/google-cloud-functions/runtime/src/main/java/io/quarkus/gcp/functions/QuarkusHttpFunction.java [hunk 2]
```diff
@@ -13,10 +13,11 @@
 
 public final class QuarkusHttpFunction implements HttpFunction {
 
-    protected static final String deploymentStatus;
-    protected static boolean started = false;
+    private static final String deploymentStatus;
+    private static boolean started = false;
 
     private static volatile HttpFunction delegate;
+    private static volatile ClassLoader delegateClassLoader;
```
Comment (gsmet) [inline extensions/google-cloud-functions/runtime/src/main/java/io/quarkus/gcp/functions/QuarkusHttpFunction.java:20]: Same here.

File: extensions/google-cloud-functions/runtime/src/main/java/io/quarkus/gcp/functions/QuarkusBackgroundFunction.java [hunk 3]
```diff
@@ -14,14 +14,16 @@
...
 
-    protected static final String deploymentStatus;
-    protected static boolean started = false;
+    private static final String deploymentStatus;
+    private static boolean started = false;
 
     private static volatile BackgroundFunction delegate;
     private static volatile Class<?> parameterType;
     private static volatile RawBackgroundFunction rawDelegate;
+    private static volatile ClassLoader delegateClassLoader;
```
Comment (gsmet) [inline extensions/google-cloud-functions/runtime/src/main/java/io/quarkus/gcp/functions/QuarkusBackgroundFunction.java:26]: Same question here.

File: extensions/google-cloud-functions/runtime/src/main/java/io/quarkus/gcp/functions/QuarkusCloudEventsFunction.java (hunk 1 above)
Comment (geoand) [reply extensions/google-cloud-functions/runtime/src/main/java/io/quarkus/gcp/functions/QuarkusCloudEventsFunction.java:19]: It gets reset to the new ClassLoader in the recorder, so no it should not be necessary.

That said, it doesn't hurt to have some proper clearance here, so let me add that in a separate commit.

Comment (gsmet) [reply extensions/google-cloud-functions/runtime/src/main/java/io/quarkus/gcp/functions/QuarkusCloudEventsFunction.java:19]: But won't the new recorder live in a different class loader and with a different static variable?

Comment (geoand) [reply extensions/google-cloud-functions/runtime/src/main/java/io/quarkus/gcp/functions/QuarkusCloudEventsFunction.java:19]: Done

Comment (geoand) [reply extensions/google-cloud-functions/runtime/src/main/java/io/quarkus/gcp/functions/QuarkusCloudEventsFunction.java:19]: > But won't the new recorder live in a different class loader and with a different static variable?

Unless something has changed dramatically in our CL infrastructure, recorders do not change between restarts

**Review by gsmet — APPROVED** [review]

**Review by loicmathieu — APPROVED** [review]
If I understand it correctly, the function will always use the TCCL of the thread that loads Quarkus instead of the TCCL of the thread that makes the request.

I'm not sure I understand all the implications but if it solves the issue and didn't all tests pass OK for it.
Did you test it in a real function invocation?
As tests uses the invoker which may not be exactly what runs in the cloud.

**Comment by geoand** [comment]
> Did you test it in a real function invocation?

I did not. How would I test this?

**Comment by loicmathieu** [comment]
@geoand you can follow the guide ;)  https://quarkus.io/guides/gcp-functions#build-and-deploy-to-google-cloud

If you didn't have any Google Cloud Account, I can find some time this week to test it for you before merging.

**Comment by geoand** [comment]
Got it. I don't have a key AFAIK, so if you could try it, that would be great

**Review by radcortez — APPROVED** [review]

**Comment by geoand** [comment]
I'll go ahead and merge this, as it's very unlikely to be worse that the current state. @loicmathieu if you find during your testing that it doesn't work as expected, please do let me know :)
