### PR TITLE
Disallow the use of @Inject in JAX-RS Application classes

### LINKED ISSUE #22277: @Inject inside JAX-RS Application subclass not working with 2.x (ok with 1.6)
### Describe the bug

After upgrading Quarkus from 1.6.1.Final to 2.5.Final the following `@Inject` fails inside `javax.ws.rs.core.Application` subclass:

```java
@ApplicationScoped
public class MyBean {

    public String foo() {
        retun "bar";
    }
}
```

```java
@ApplicationPath("/")
public class MyApplication extends Application {

    @Inject
    MyBean myBean;

    @Override
    public Set<Class<?>> getClasses() {
        myBean.foo(); // Causes NPE on Quarkus 2.5.1.Final, worked well with 1.6.1.Final
    
    }
}
```

### Expected behavior

`myBean` instance above should not be null

### Actual behavior

`myBean` instance is null

### How to Reproduce?

See bug description.

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

jdk-11.0.12.7-hotspot

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.5.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
This did not work anyway, so it probably makes sense to
disallow it completely

Closes: #22277

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]

File: extensions/resteasy-classic/resteasy-server-common/deployment/src/main/java/io/quarkus/resteasy/server/common/deployment/ResteasyServerCommonProcessor.java [hunk 1]
```diff
@@ -998,7 +998,12 @@ private static JaxrsProvidersToRegisterBuildItem getFilteredJaxrsProvidersToRegi
                 throw new RuntimeException("More than one Application class: " + applications);
             }
             selectedAppClass = applicationClassInfo;
-            // FIXME: yell if there's more than one
```
Comment (gastaldi) [inline extensions/resteasy-classic/resteasy-server-common/deployment/src/main/java/io/quarkus/resteasy/server/common/deployment/ResteasyServerCommonProcessor.java:1001]: Not sure if this was intended to be removed?

Comment (geoand) [reply extensions/resteasy-classic/resteasy-server-common/deployment/src/main/java/io/quarkus/resteasy/server/common/deployment/ResteasyServerCommonProcessor.java:1001]: It was intentional as this has already been addressed in the code above
