### PR TITLE
Qute - fix templates and tags scanning from extension runtime artifacts

### LINKED ISSUE #21864: Qute: extension tags not registered
### Describe the bug

I just tried the latest Quarkus/Qute to see if it would pick up my Vixen extension tags, declared in `extensions/vixen/runtime/src/main/resources/templates/tags` (in the runtime module) and they're not visible to the user application, I'm getting errors.

Perhaps I'm doing it wrong and they need to be in the deployment module?

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mkouba**
- resolves #21864

### CODE REVIEW

File: extensions/qute/deployment/src/main/java/io/quarkus/qute/deployment/QuteProcessor.java [hunk 1]
```diff
@@ -2191,6 +2198,15 @@ private boolean isApplicationArchive(ResolvedDependency dependency, Set<Applicat
...
     }
 
+    static String readTemplateContent(Path path) {
+        try {
+            byte[] content = Files.readAllBytes(path);
+            return new String(content, StandardCharsets.UTF_8);
+        } catch (IOException e) {
+            throw new IllegalStateException("Unable to read the template content from path: " + path);
+        }
+    }
```
Comment (gastaldi) [inline extensions/qute/deployment/src/main/java/io/quarkus/qute/deployment/QuteProcessor.java:2208]: You can use `Files.readString` instead

File: extensions/qute/deployment/src/main/java/io/quarkus/qute/deployment/QuteProcessor.java [hunk 2]
```diff
@@ -2114,7 +2121,7 @@ private static void produceTemplateBuildItems(BuildProducer<TemplatePathBuildIte
         // NOTE: we cannot just drop the template because a template param can be added 
         watchedPaths.produce(new HotDeploymentWatchedFileBuildItem(fullPath, true));
         nativeImageResources.produce(new NativeImageResourceBuildItem(fullPath));
-        templatePaths.produce(new TemplatePathBuildItem(filePath, originalPath));
+        templatePaths.produce(new TemplatePathBuildItem(filePath, originalPath, readTemplateContent(originalPath)));
```
Comment (gastaldi) [inline extensions/qute/deployment/src/main/java/io/quarkus/qute/deployment/QuteProcessor.java:2124]:
```suggestion
        templatePaths.produce(new TemplatePathBuildItem(filePath, originalPath, Files.readString(originalPath)));
```

**Review by gastaldi — APPROVED** [review]
LGTM

File: extensions/qute/deployment/src/main/java/io/quarkus/qute/deployment/QuteProcessor.java [hunk 3]
```diff
@@ -2191,6 +2197,14 @@ private boolean isApplicationArchive(ResolvedDependency dependency, Set<Applicat
         return false;
     }
 
+    static String readTemplateContent(Path path) {
+        try {
+            return Files.readString(path);
+        } catch (IOException e) {
+            throw new IllegalStateException("Unable to read the template content from path: " + path);
```
Comment (gastaldi) [inline extensions/qute/deployment/src/main/java/io/quarkus/qute/deployment/QuteProcessor.java:2204]: Better propagate the IOException as the cause here? Also maybe `UncheckedIOException` may be more intuitive

File: extensions/qute/deployment/src/main/java/io/quarkus/qute/deployment/QuteProcessor.java [hunk 4]
```diff
@@ -1234,15 +1230,27 @@ void collectTemplates(ApplicationArchivesBuildItem applicationArchives,
...
+                } else {
+                    try (FileSystem artifactFs = ZipUtils.newFileSystem(path)) {
+                        Path basePath = artifactFs.getPath(BASE_PATH);
+                        if (Files.exists(basePath)) {
+                            LOGGER.debugf("Found extension templates in: %s", path);
+                            scan(basePath, basePath, BASE_PATH + "/", watchedPaths, templatePaths, nativeImageResources,
+                                    config.templatePathExclude);
+                        }
+                    } catch (IOException e) {
+                        LOGGER.warnf("Unable to create the file system from the path: %s", path);
```
Comment (gastaldi) [inline extensions/qute/deployment/src/main/java/io/quarkus/qute/deployment/QuteProcessor.java:1252]: Maybe add the IOException to the logs too?
