### PR TITLE
Don't attempt to load classes from the java package

### LINKED ISSUE #8260: Prohibited package name: java.util.concurrent
**Describe the bug**
I tried to upgrade quarkus version (platform + plugin) to 1.3.0.Final and 1.3.1.Final, but maven build failed due to error in instantiation of test:

```
...fileDownload  Time elapsed: 0.021 s  <<< ERROR!
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
Caused by: java.lang.reflect.InvocationTargetException
Caused by: java.lang.SecurityException: Prohibited package name: java.util.concurrent
```
I guess, it is somehow project related, because I couldn't reproduce the issue in basic demo application. The test was executed fine with quarkus 1.2.0.Final

I tried to search in all project depedencies if I spot a class within the that java package but no luck.

Is there a way, how to get more info from quarkus, what was wrong? I tried to enable TRACE log level in application.properties (in test/resources) but again, just those 

**Expected behavior**
The tests annotated by @QuarkusTest annotation should be executed fine or it should get back more explanatory error message, which class was in prohibited package.

**Actual behavior**
Test fails due to following issue : Caused by: java.lang.SecurityException: Prohibited package name: java.util.concurrent

**To Reproduce**
Not able to reproduce it.

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
Linux name-VirtualBox 4.15.0-91-generic #92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: 
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b06)
OpenJDK 64-Bit Server VM GraalVM CE 20.0.0 (build 25.242-b06-jvmci-20.0-b02, mixed mode)

 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.3.1.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/<>/Tools/maven
Java version: 1.8.0_242, vendor: Oracle Corporation, runtime: /home/<>/Tools/graalvm/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-91-generic", arch: "amd64", family: "unix"
**Additional context**
(Add any other context about the problem here.)

### PR DESCRIPTION
**Pull request by stuartwdouglas**
If a dependency has packaged java. classes for some reason
this could cause problems.

Fixes #8260

### CODE REVIEW

File: independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/classloading/QuarkusClassLoader.java [hunk 1]
```diff
@@ -276,6 +277,9 @@ public InputStream getResourceAsStream(String nm) {
 
     @Override
     protected Class<?> loadClass(String name, boolean resolve) throws ClassNotFoundException {
+        if(name.startsWith(JAVA)) {
```
Comment (gsmet) [inline independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/classloading/QuarkusClassLoader.java]: I would bet there is a formatting issue with a missing space after the if.

**Review by geoand — APPROVED** [review]
