### PR TITLE
Catch exceptions when running checkMissingCommand

### LINKED ISSUE #41513: Quarkus CLI - Some expected errors lead to a stacktrace and they shouldn't
In the case of `quarkus config enc`, if I forget the parameter, I end up with a stacktrace which is not really expected: we should have a standard Picocli error output and not a full stacktrace as this is a standard use case of the CLI and not an underlying error.

```
$ quarkus config enc
2024-06-27 14:23:25,703 ERROR [io.qua.run.Application] (main) Failed to start application (with profile [prod]): picocli.CommandLine$MissingParameterException: Missing required parameter: 'SECRET'
	at picocli.CommandLine$Interpreter.assertNoMissingParameters(CommandLine.java:14930)
	at picocli.CommandLine$Interpreter.validateConstraints(CommandLine.java:13659)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13620)
	at picocli.CommandLine$Interpreter.processSubcommand(CommandLine.java:13915)
	at picocli.CommandLine$Interpreter.processArguments(CommandLine.java:13811)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13597)
	at picocli.CommandLine$Interpreter.processSubcommand(CommandLine.java:13915)
	at picocli.CommandLine$Interpreter.processArguments(CommandLine.java:13811)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13597)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13565)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13460)
	at picocli.CommandLine.parseArgs(CommandLine.java:1552)
	at io.quarkus.cli.QuarkusCli.checkMissingCommand(QuarkusCli.java:165)
	at io.quarkus.cli.QuarkusCli.run(QuarkusCli.java:109)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:132)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.cli.Main.main(Main.java:9)
```

### PR DESCRIPTION
**Pull request by gsmet**
We want to check for the missing commands only, any other error will have to be handled by Picocli later (and thus will properly handle the formatting of the feedback and avoid a stacktrace).

Fixes #41513

### CODE REVIEW

**Comment by gsmet** [comment]
@radcortez this is the fix for the issue I reported about getting stacktrace when calling `quarkus config enc` with no parameters.

File: devtools/cli/src/main/java/io/quarkus/cli/QuarkusCli.java [hunk 1]
```diff
@@ -185,6 +185,11 @@ public Optional<String> checkMissingCommand(CommandLine root, String[] args) {
             return Optional.empty();
         } catch (UnmatchedArgumentException e) {
             return Optional.of(args[0]);
+        } catch (Exception e) {
+            // For any other exceptions (e.g. MissingParameterException), we should just ignore.
```
Comment (gastaldi) [inline devtools/cli/src/main/java/io/quarkus/cli/QuarkusCli.java:189]: Should we somehow log.debug this for debugging purposes?

Comment (gsmet) [reply devtools/cli/src/main/java/io/quarkus/cli/QuarkusCli.java:189]: I don't think so.

We really want to only catch the `UnmatchedArgumentException` at this stage.
Any other problem will be caught when Picocli is doing the same call a bit later (and then you have a proper error, not an obscure stracktrace).

**Review by gastaldi — APPROVED** [review]

**Review by radcortez — APPROVED** [review]
