### PR TITLE
Micrometer cors

### LINKED ISSUE #16329: Incorrect micrometer metrics for http method OPTIONS
## Describe the bug
The method="OPTIONS" request creates a separate counter for each path parameter instead of combining them.

### Expected behavior
Metrics should look like follow:

`
http_server_requests_seconds_max{,method="POST",outcome="SUCCESS",status="204",uri="/api/alerts/{alertId}",} 0.0
http_server_requests_seconds_max{method="OPTIONS",outcome="SUCCESS",status="200",uri="/api/alerts/{alertId}",} 0.0
`

### Actual behavior
For get/post-request it's ok, but not for options (cors preflight)
`
http_server_requests_seconds_max{method="POST",outcome="SUCCESS",status="204",uri="/api/alerts/{alertId}",} 0.0
http_server_requests_seconds_max{method="OPTIONS",outcome="SUCCESS",status="200",uri="/api/alerts/8676",} 0.0
http_server_requests_seconds_max{method="OPTIONS",outcome="SUCCESS",status="200",uri="/api/alerts/8586",} 0.0
http_server_requests_seconds_max{method="OPTIONS",outcome="SUCCESS",status="200",uri="/api/alerts/8631",} 0.0
`

## To Reproduce

Send an OPTIONS request to any http endpoint with path variables

### Quarkus version
1.12.2.Final

### PR DESCRIPTION
**Pull request by ebullient**
Resolves #16329

### CODE REVIEW

**Review by kenfinnigan — APPROVED** [review]

**Review by kenfinnigan — APPROVED** [review]

File: extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/binder/vertx/HttpRequestMetric.java [hunk 1]
```diff
@@ -81,4 +85,11 @@ public String toString() {
         return "HttpRequestMetric [initialPath=" + initialPath + ", currentRoutePath=" + currentRoutePath
                 + ", templatePath=" + templatePath + ", request=" + request + "]";
     }
+
+    private boolean isCORSPreflightRequest() {
```
Comment (sberyozkin) [inline extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/binder/vertx/HttpRequestMetric.java:89]: @ebullient Hi Erin - if Quarkus HTTP CORS is enabled then the CORS filter will not let the request flow further:

 https://github.com/quarkusio/quarkus/blob/main/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/cors/CORSFilter.java#L125

Is this `HttpRequestMetric` code running before CORSFilter ?

thanks

Comment (ebullient) [reply extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/binder/vertx/HttpRequestMetric.java:89]: it is caught @ vertx layer.

go ahead and run the test. ;)

Comment (sberyozkin) [reply extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/binder/vertx/HttpRequestMetric.java:89]: @ebullient this is very cool
