### PR TITLE
Fix mp.jwt.verify.publickey check in SmallryeJwtDevModeProcessor

### LINKED ISSUE #46928: Failed to read the public key content from 'mp.jwt.verify.publickey.location' in native with latest Quarkus main
### Describe the bug

Failed to read the public key content from 'mp.jwt.verify.publickey.location' in native with latest Quarkus main. Test works fine in JVM mode.

Works fine with Quarkus 3.21.0 in native, so it must be recent change in main.

```
2025-03-21 11:22:17,755 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-3) HTTP Request to /hello failed, error id: 6968d40d-6ed6-49e5-b63d-06dfc462a73b-1: jakarta.enterprise.inject.spi.DeploymentException: SRJWT02002: Failed to read the public key content from 'mp.jwt.verify.publickey.location'
	at io.smallrye.jwt.config.JWTAuthContextInfoProvider.getOptionalContextInfo(JWTAuthContextInfoProvider.java:734)
	at io.smallrye.jwt.config.JWTAuthContextInfoProvider.getContextInfo(JWTAuthContextInfoProvider.java:920)
	at io.smallrye.jwt.config.JWTAuthContextInfoProvider_ProducerMethod_getContextInfo_IdERZ3rgTvGnz5ERAK80guTDswo_Bean.doCreate(Unknown Source)
	at io.smallrye.jwt.config.JWTAuthContextInfoProvider_ProducerMethod_getContextInfo_IdERZ3rgTvGnz5ERAK80guTDswo_Bean.create(Unknown Source)
	at io.smallrye.jwt.config.JWTAuthContextInfoProvider_ProducerMethod_getContextInfo_IdERZ3rgTvGnz5ERAK80guTDswo_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:119)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:38)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)
	at io.quarkus.arc.generator.Default_jakarta_enterprise_context_ApplicationScoped_ContextInstances.c85(Unknown Source)
	at io.quarkus.arc.generator.Default_jakarta_enterprise_context_ApplicationScoped_ContextInstances.computeIfAbsent(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:35)
...
Caused by: java.net.MalformedURLException: no protocol: /foo/bar
	at java.base@21.0.5/java.net.URL.<init>(URL.java:772)
	at java.base@21.0.5/java.net.URL.<init>(URL.java:654)
	at java.base@21.0.5/java.net.URL.<init>(URL.java:590)
	at io.smallrye.jwt.util.ResourceUtils$UrlStreamResolver.resolve(ResourceUtils.java:122)
	at io.smallrye.jwt.util.ResourceUtils.getResourceStream(ResourceUtils.java:82)
	at io.smallrye.jwt.util.ResourceUtils.readResource(ResourceUtils.java:45)
	at io.smallrye.jwt.util.ResourceUtils.readResource(ResourceUtils.java:40)
	at io.smallrye.jwt.config.JWTAuthContextInfoProvider.getOptionalContextInfo(JWTAuthContextInfoProvider.java:729)
	... 125 more
```

`mp.jwt.verify.publickey.location=/foo/bar` is defined in https://github.com/quarkus-qe/beefy-scenarios/blob/main/003-quarkus-many-extensions/src/main/resources/application.properties to get over the check for definition presence, but jwt is not really used

### Expected behavior

Both JVM and Native work, tests pass.

### Actual behavior

JVM works, tests pass. Native doesn't work, fails on firs request.

### How to Reproduce?

Setup Mandrel or GraalVM

 * Use https://github.com/quarkus-qe/beefy-scenarios
 * Run `mvn clean verify -Dnative -f 003-quarkus-many-extensions`

`mvn clean verify -Dnative -f 003-quarkus-many-extensions -Dquarkus.platform.version=3.21.0` works fine

### Output of `uname -a` or `ver`

macOS

### Output of `java -version`

_No response_

### Mandrel or GraalVM version (if different from Java)

MANDREL 23.1.5.0 JDK 21.0.5+11-LTS

### Quarkus version or git rev

999-SNAPSHOT

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by rsvoboda**
Fix mp.jwt.verify.publickey check in SmallryeJwtDevModeProcessor

Fixes https://github.com/quarkusio/quarkus/issues/46928 / native mode case

### CODE REVIEW

**Comment by rsvoboda** [comment]
oki, I will fix this. it's obviously also for tests

File: extensions/smallrye-jwt/deployment/src/main/java/io/quarkus/smallrye/jwt/deployment/SmallryeJwtDevModeProcessor.java [hunk 1]
```diff
@@ -55,7 +56,7 @@ public class SmallryeJwtDevModeProcessor {
      *
      * @throws NoSuchAlgorithmException if RSA-256 key generation fails.
      */
-    @BuildStep(onlyIfNot = { IsNormal.class })
+    @BuildStep(onlyIfNot = { IsNormal.class, NativeOrNativeSourcesBuild.class })
```
Comment (gsmet) [inline extensions/smallrye-jwt/deployment/src/main/java/io/quarkus/smallrye/jwt/deployment/SmallryeJwtDevModeProcessor.java:59]: I would expect the native build to run in normal mode? So I'm a bit surprised it makes a difference?

Comment (rsvoboda) [reply extensions/smallrye-jwt/deployment/src/main/java/io/quarkus/smallrye/jwt/deployment/SmallryeJwtDevModeProcessor.java:59]: my bet is NativeSourcesBuild part, but I can look more into it

Comment (rsvoboda) [reply extensions/smallrye-jwt/deployment/src/main/java/io/quarkus/smallrye/jwt/deployment/SmallryeJwtDevModeProcessor.java:59]: Having just `@BuildStep(onlyIfNot = { IsNormal.class, NativeSourcesBuild.class })` doesn't fix the issue

So my change is the minimal one.

**Review by gsmet — DISMISSED** [review]
I'm not exactly excited about this change and I would like us to get to the bottom of it.

What I understand is that you are pointing to a non-existing public key and hoping things will work.

Also I'm not exactly sure why you have JWT around `but jwt is not really used`.

Could you clarify exactly what you're doing in this test, why you need to define a JWT key that points to nowhere - and why you expect this to be fine.

Maybe your patch is right but at this point I can't be sure.

**Comment by rsvoboda** [comment]
BeefyTS is legacy and we keep it alive to see if old approaches work. The 003-quarkus-many-extensions module combines a lot of extensions and the intention is to ensure it can be built in JVM and Native mode. JWT properties in https://github.com/quarkus-qe/beefy-scenarios/blob/main/003-quarkus-many-extensions/src/main/resources/application.properties#L4-L5 were needed when the app was composed, now the JWT extension doesn't need these properties to be defined when no JWT logic is triggered. I can remove them and things will work again.

I identified the PR that caused failure of the module in native. It's https://github.com/quarkusio/quarkus/pull/44272/ as mentioned in https://github.com/quarkusio/quarkus/issues/46928#issuecomment-2743105383

Very strange thing is that JVM mode doesn't fail, but native mode fails trying to read the `/foo/bar` from `mp.jwt.verify.publickey.location` property.

https://github.com/quarkusio/quarkus/pull/44272/ states that `Generate RSA-256 keys on dev mode` and that got me slightly sidetracked, it's apparently for dev mode and tests. So the title of PR should be renamed and also maybe also`SmallryeJwtDevModeProcessor.java` should be renamed to indicate also test, e.g. `SmallryeJwtDevTestModeProcessor.java`.

So in the end I think I will just adjust 003-quarkus-many-extensions and drop the mp.jwt dummy config.

**Comment by rsvoboda** [comment]
oh, I think I hit something :) I will update the PR

**Comment by rsvoboda** [comment]
@gsmet PR updated to check `userConfigs` for `mp.jwt.verify.publickey`, it also fixes my old/weird case

**Comment by rsvoboda** [comment]
I have updated https://github.com/quarkusio/quarkus/pull/44272 title to mention also test

Let me know about the `SmallryeJwtDevModeProcessor` file naming. Should I also rename it to `SmallryeJwtDevTestModeProcessor` or I'm just being too choosey :) ?

**Review by sberyozkin — APPROVED** [review]
Thanks @rsvoboda 🙏

**Review by sberyozkin — APPROVED** [review]
Thanks @rsvoboda 🙏

**Comment by sberyozkin** [comment]
As far as I recall, this fix from @rsvoboda fixes the typo in the @mcruzdev's PR, @mcruzdev can you please check?

**Comment by sberyozkin** [comment]
I'll hold off the merge for now, I'm on the road and missed there was the discussion, I think the fix is good, but would appreciate @mcruzdev having a look.

**Comment by mcruzdev** [comment]
I am taking a look now

**Review by mcruzdev — APPROVED** [review]

**Comment by sberyozkin** [comment]
Thanks @mcruzdev
