### PR TITLE
Reactive Connection Pools: always use TLOCAL, HealthCheck refactoring

### LINKED ISSUE #13868: SQL pool for Hibernate Reactive needs to be scoped by Vert.x Context
**Describe the bug**
We did misunderstand how to manage the lifecycle of the Vertx SQL pool: it should not be shared across all of Quarkus, but it needs to be scoped to a specific Vert.x context.
This implies we should not initialize the pool at creation of the Hibernate Reactive SessionFactory, but rather initialize a lazy supplier of `Pool`, and track them for disposal.

This mistake manifests as parallel access into unsynchornized state of the Session, resulting in tricky errors.

Relates to :
 - https://github.com/eclipse-vertx/vertx-sql-client/issues/849
 - https://github.com/hibernate/hibernate-reactive/issues/475

N.B. in upcoming Vert.x 4 the pool implementation is more flexible, we might be able to simplify things a bit after the upgrade, but the design expectation is similar.

### LINKED ISSUE #13943: Deprecate `thread-local` option for Reactive SQL Pool, enforce using it
**Description**

The property `thread-local` needs to be enforced, as not using it will most likely result in race conditions on the callbacks to Database operations.
 - https://quarkus.io/guides/datasource#quarkus-reactive-datasource_quarkus.datasource.reactive.thread-local

Will follow up on mailing list with more context.

**Implementation ideas**

1. Deprecate the configuration flag, low warnings if it's being used
2. Ignore its setting
3. Always use the ThreadLocal optimised pool wrapper (at least as long as we're on Vert.x v.3)

Might revise the actual pool implementation choice after migrating to Vert.x v4, but not necessarily as the optimised pool is expected to be a good fit for v4 as well. (v4 strictly doesn't require it, but it's not a bad choice).

### LINKED ISSUE #13978: Reactive Pool HealthCheck should run on the event loop
**Description**
A possible improvement to follow up on #13977 would be to ensure that the "health check" operations, which need to run a SQL statement on the reactive Pool, were dispatched on the Vertx Context to be run.

This would be useful as otherwise a `Pool` instance gets associated on the worker thread, while we would typically expect these pools to only be used by operations running on the Vert.x event loop.

It's not a problem if the user ends up triggering initialization of such pools on other threads if they prefer so, but we should avoid this in our components; beyond memory costs, this would also possibly tie up connections.

### PR DESCRIPTION
**Pull request by Sanne**
Fixes #13943
Fixes #13978
Fixes #13868

This was meant to only change the deafult configuration for a Reactive Pool, but the new configuration makes an existing possible timeout error more likely, so we also need to improve the errorhandling about this.

Also turns out the PG and MySQL health beans were almost the same, and shared the same errorhandling limitations: so unified the code. The DB2 pool health is entirely different, so added a note about this but didn't need the same refactoring.

Turns out that for this process to run reliably it needs to be run on the vert.x context; so incorporating #13978 as well.

### CODE REVIEW

File: extensions/reactive-datasource/runtime/src/main/java/io/quarkus/reactive/datasource/runtime/ReactiveDatasourceHealthCheck.java [hunk 1]
```diff
@@ -64,7 +64,7 @@ public HealthCheckResponse call() {
                                 });
                     });
                 } else {
-                    log.debug("Vert.x context not found for health check");
+                    log.warn("Vert.x context unavailable to perform healthcheck of reactive datasource `" + dataSourceName + "`. This is unlikely to work correctly.");
```
Comment (DavideD) [inline extensions/reactive-datasource/runtime/src/main/java/io/quarkus/reactive/datasource/runtime/ReactiveDatasourceHealthCheck.java:67]:
```
This is unlikely to work correctly.
```

Are you sure about this? I think it should be possible to run this without a context. Not sure why we had that issue only for MySQL and only on CI.

Comment (Sanne) [reply extensions/reactive-datasource/runtime/src/main/java/io/quarkus/reactive/datasource/runtime/ReactiveDatasourceHealthCheck.java:67]: You'll have the previous behaviour, which seems to timeout frequently. I'll keep the warning for now, as running w/o a Vert.x context seems tricky for other reasons as well.

**Review by gsmet — APPROVED** [review]

**Comment by Sanne** [comment]
Seems this also fixed #13868 , amending description.
