### PR TITLE
Properly show configuration errors in the output

### LINKED ISSUE #6466: Display proper error message when setting invalid configuration at runtime
I want to start a project deployed on kubernets (not compiled in native) 
i get this message 
`Exception in thread "main" java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:307)
	at io.quarkus.runtime.Application.start(Application.java:87)
	at io.quarkus.runtime.Application.run(Application.java:210)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:41)
Caused by: io.quarkus.runtime.configuration.ConfigurationException: One or more configuration errors has prevented the application from starting
	at io.quarkus.runtime.generated.Config.readConfig(Config.zig:28134)
	at io.quarkus.runtime.generated.Config.createRunTimeConfig(Config.zig:1864)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:133)
	... 3 more`

is it possible to have a better error description ?

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #6466

With this change, the output of  `./myapp -Dquarkus.profile= -Dquarkus.http.port=foo` is:

```
Exception in thread "main" java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:194)
        at io.quarkus.runtime.Application.start(Application.java:87)
        at io.quarkus.runtime.Application.run(Application.java:210)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:41)
Caused by: io.quarkus.runtime.configuration.ConfigurationException: One or more configuration errors has prevented the application from starting. The errors are:
Configuration key "quarkus.profile" is required, but its value is empty/missing: Property quarkus.profile not found
An invalid value was given for configuration key "quarkus.http.port": For input string: "foo"
```

### CODE REVIEW

File: core/runtime/src/main/java/io/quarkus/runtime/configuration/ConfigDiagnostic.java [hunk 1]
```diff
@@ -14,28 +16,31 @@
     private static final Logger log = Logger.getLogger("io.quarkus.config");
 
     @RecomputeFieldValue(kind = RecomputeFieldValue.Kind.Reset)
-    private static volatile boolean error = false;
+    private static List<String> errorsMessages = new CopyOnWriteArrayList<>();
```
Comment (dmlloyd) [inline core/runtime/src/main/java/io/quarkus/runtime/configuration/ConfigDiagnostic.java]: This should be final.

**Review by dmlloyd — CHANGES_REQUESTED** [review]
One minor fix.  Otherwise looks good!

File: core/runtime/src/main/java/io/quarkus/runtime/configuration/ConfigDiagnostic.java (hunk 1 above)
Comment (dmlloyd) [inline core/runtime/src/main/java/io/quarkus/runtime/configuration/ConfigDiagnostic.java]:
```suggestion
    private static final List<String> errorsMessages = new CopyOnWriteArrayList<>();
```

Comment (dmlloyd) [reply core/runtime/src/main/java/io/quarkus/runtime/configuration/ConfigDiagnostic.java]: Trying out "suggested change" :)

Comment (geoand) [reply core/runtime/src/main/java/io/quarkus/runtime/configuration/ConfigDiagnostic.java]: It worked :)

**Review by dmlloyd — APPROVED** [review]

**Comment by gsmet** [comment]
@geoand is it normal that the logger doesn't look like our standard logger?

**Comment by geoand** [comment]
Yeah, I followed @dmlloyd's suggestion in the issue to create a good error message and remove the (useless) stacktrace

**Comment by gsmet** [comment]
I was talking about our logging prefix? It looks like it's gone here.

**Comment by geoand** [comment]
I am guessing that logging isn't entirely set up at that point.
But the application fails to starts, so perhaps it's not that important?

**Comment by dmlloyd** [comment]
Yeah this isn't logging, it's putting the raw exception text into the final exception.  Logging is completely separate.
