### PR TITLE
Fail CLI create for invalid artifact/group id

### LINKED ISSUE #25991: CLI allows to create project with comma in the name
### Describe the bug

CLI allows to create project with comma in the name. Comma is not allowed character for `artifactId` in maven projects

```
quarkus create app app,with,comma
cd app,with,comma
quarkus build

...

[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] 'artifactId' with value 'app,with,comma' does not match a valid id pattern. @ line 6, column 15
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project org.acme:app,with,comma:1.0.0-SNAPSHOT (/Users/rsvoboda/tmp/app,with,comma/pom.xml) has 1 error
[ERROR]     'artifactId' with value 'app,with,comma' does not match a valid id pattern. @ line 6, column 15
```

### Expected behavior

CLI complains about problematic character

### Actual behavior

CLI allows to create project with comma in the name. Comma is not allowed character for `artifactId` in maven projects

### How to Reproduce?

```
quarkus create app app,with,comma
cd app,with,comma
quarkus build
```

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

Java 11

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.9.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ebullient**
Resolves #25991

### CODE REVIEW

File: devtools/cli/src/main/java/io/quarkus/cli/create/TargetGAVGroup.java [hunk 1]
```diff
@@ -52,6 +58,13 @@ void projectGav() {
                     }
                 }
             }
+            if (artifactId != CreateProjectHelper.DEFAULT_ARTIFACT_ID && !OK_ID.matcher(artifactId).matches()) {
+                throw new TypeConversionException(String.format(BAD_IDENTIFIER, "artifact", artifactId));
```
Comment (gsmet) [inline devtools/cli/src/main/java/io/quarkus/cli/create/TargetGAVGroup.java:62]: Should this be `artifactId` and `groupId`?

**Review by gsmet — COMMENTED** [review]
Nice, thanks. I added a small micro comment.

File: devtools/cli/src/main/java/io/quarkus/cli/create/TargetGAVGroup.java (hunk 1 above)
Comment (ebullient) [reply devtools/cli/src/main/java/io/quarkus/cli/create/TargetGAVGroup.java:62]: y.. probably should.

**Review by gsmet — APPROVED** [review]
