### PR TITLE
Replace OkHttp tracing grpc backend with Vert.x

### LINKED ISSUE #32238: OOM in Quarkus 3.0.0.Beta1 caused by okio via OpenTelemetry
### Describe the bug

okio starts a thread via the class `okio.AsyncTimeout.Watchdog` once "it has to deal with a timeout". The thread's configured as a daemon thread and seems to have some shutdown logic, and also aborts when its interrupted.

The behavior isn't an issue in production usecases, but it's an issue when running tests.

`okio.AsyncTimeout.Watchdog` is loaded by a Quarkus class loader for every test, so it implicitly keeps a reference to its class loader and transitively to all the resources that one holds - just because the thread's still running.

Setting the following parameters disables timeouts and in turn does not start that watchdog thread and the OOM doesn't happen. It's maybe a legit workaround for tests, until the issue's fixed.
```
quarkus.otel.exporter.otlp.timeout=0
quarkus.otel.exporter.otlp.traces.timeout=0
```

This behavior seems to be introduced after Quarkus 3.0.0.Alpha5, but I'm not sure why, because okio seems to behave this way "forever".

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
Closes: #32238

TODO:

* ~~Remove OkHttp dependency~~
* ~~Fix native~~
* ~~Perform hardening~~ ?

### CODE REVIEW

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/exporter/otlp/OtlpRecorder.java [hunk 1]
```diff
@@ -80,36 +82,50 @@ public void installBatchSpanProcessorForOtlp(
...
-        if (!exporterRuntimeConfig.traces().protocol().orElse("").equals(HTTP_PROTOBUF)) {
-            throw new IllegalStateException("Only the GRPC Exporter is currently supported. " +
-                    "Please check `otel.exporter.otlp.traces.protocol` property");
         }
-        return exporterBuilder.build();
+
+        return new VertxGrpcExporter(
+                "otlp",
+                "span",
+                GlobalOpenTelemetry::getMeterProvider,
```
Comment (radcortez) [inline extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/exporter/otlp/OtlpRecorder.java:123]: We should avoid using `GlobalOpenTelemetry`. Since we are not using OTel Metrics yet, we can just pass in a noop `MeterProvider`

**Comment by brunobat** [comment]
I'll review by the end of the week.

**Comment by geoand** [comment]
Thanks. 

I still need to make Vert.x related improvements to this, I'll let you know when I think it's ready to go.

**Comment by geoand** [comment]
I think it's in a shape to be reviewed now

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/exporter/otlp/VertxGrpcExporter.java [hunk 2]
```diff
@@ -0,0 +1,364 @@
...
+
+        var result = new CompletableResultCode();
+        var onSuccessHandler = new ClientRequestOnSuccessHandler(headers, compressionEnabled, exporterMetrics, marshaler,
+                loggedUnimplemented, logger, type, numItems, result);
+        client.request(server)
+                .onSuccess(onSuccessHandler)
+                .onFailure(new Handler<>() {
+                    @Override
+                    public void handle(Throwable t) {
+                        // TODO: is there a better way todo retry?
```
Comment (cescoffier) [inline extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/exporter/otlp/VertxGrpcExporter.java:106]: retries can be tricky, especially with exponential backoff.

The idea is to capture the action as a Supplier<Future> and then use something like:

```java
var retry = new RetryContainer(3, Duration.ofSecond(1), Duration.ofSecond(10));
retry.retry(supplier);)
```

retry would invoke the supplier check for the outcome and then use a vertx timer to schedule the next attempt.

**Review by cescoffier — COMMENTED** [review]
LGTM - at least the client.

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/exporter/otlp/VertxGrpcExporter.java (hunk 2 above)
Comment (geoand) [reply extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/exporter/otlp/VertxGrpcExporter.java:106]: I did not know this class.

I'll look into using it tomorrow

Comment (geoand) [reply extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/exporter/otlp/VertxGrpcExporter.java:106]: Ah, I thought it existed in Vert.x.

Do we have that somewhere else?

Comment (geoand) [reply extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/exporter/otlp/VertxGrpcExporter.java:106]: Is there perhaps a Mutiny version of the Vert.x gRPC Client that I could use and make things nicer?

**Review by radcortez — APPROVED** [review]

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/exporter/otlp/VertxGrpcExporter.java (hunk 2 above)
Comment (cescoffier) [reply extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/exporter/otlp/VertxGrpcExporter.java:106]: I'm actually not sure... the old one I think so, but maybe not the new one. @jponge do you know? I don't remember adding it.

Comment (jponge) [reply extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/exporter/otlp/VertxGrpcExporter.java:106]: We don't have that

Comment (geoand) [reply extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/exporter/otlp/VertxGrpcExporter.java:106]: No problem. In that case, I'll leave the PR as is for now and we can certainly improve in the future

**Comment by gastaldi** [comment]
Can we remove the `com.squareup.okhttp3:*` dependencies from the BOM also?

**Comment by geoand** [comment]
No, it's used elsewhere as well (I remember an issue with Infinispan)

**Review by cescoffier — APPROVED** [review]

**Review by brunobat — CHANGES_REQUESTED** [review]
Still checking the details on the PR, but one thing we must have is integration tests with the OTel Collector.
The OTel side has them for their stock exporter and we should too.

**Comment by geoand** [comment]
Where are those tests?

**Comment by brunobat** [comment]
We have a test here: https://github.com/open-telemetry/opentelemetry-java/blob/main/integration-tests/otlp/src/main/java/io/opentelemetry/integrationtest/OtlpExporterIntegrationTest.java

Also, we need to consider if we shouldn't be using a much simpler abstractions, available here: 
https://github.com/open-telemetry/opentelemetry-java/tree/main/exporters/sender

This is using a new SPI that allows to plug your own client.

**Comment by geoand** [comment]
> We have a test here: https://github.com/open-telemetry/opentelemetry-java/blob/main/integration-tests/otlp/src/main/java/io/opentelemetry/integrationtest/OtlpExporterIntegrationTest.java

Thanks

> Also, we need to consider if we shouldn't be using a much simpler abstractions, available here:
https://github.com/open-telemetry/opentelemetry-java/tree/main/exporters/sender

Those are only for HTTP, they do not work for gRPC.
I am already aware of this SPI and plan to use it for #21535

**Comment by brunobat** [comment]
Thanks!

**Comment by brunobat** [comment]
I wonder if the SPI cannot be used anyway... We just need to switch based on the protocol config...
https://quarkus.io/guides/opentelemetry#quarkus-opentelemetry_quarkus.otel.exporter.otlp.traces.protocol

**Comment by geoand** [comment]
> I wonder if the SPI cannot be used anyway

I don't see how as the gRPC exporters don't use HttpSender at all

**Comment by geoand** [comment]
Seems my IntelliJ setup is completely busted, so I won't be adding the test today. If you want to take a swing at it, feel free to push a new commit into this PR

**Comment by brunobat** [comment]
looking at the test right now

**Comment by geoand** [comment]
I was actually able to fix my IntelliJ setup so I am looking into it

**Comment by geoand** [comment]
As part of the test work, I'll also probably add TSL config support - looking into both now

**Comment by brunobat** [comment]
Ok @geoand. Will work on the baggage problem instead.

**Comment by geoand** [comment]
Sounds good!

**Comment by geoand** [comment]
PR updated with an integration test uses the same testing philosophy as the original opentelemetry-java but has two key differences:

* Uses Vert.x instead of Armeria
* It's an actual integration test in the sense that exercises a Quarkus application that uses the exporter

Furthermore, the final commit also adds support for TLS configuration of the exporter.

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/exporter/otlp/OtlpRecorder.java [hunk 3]
```diff
@@ -95,22 +117,66 @@ private OtlpGrpcSpanExporter createOtlpGrpcSpanExporter(OtlpExporterRuntimeConfi
...
+                    private void configureTLS(HttpClientOptions options) {
+                        // TODO: this can reuse existing stuff when https://github.com/quarkusio/quarkus/pull/33228 is in
+                        options.setKeyCertOptions(toPemKeyCertOptions(tracesConfig));
+                        options.setPemTrustOptions(toPemTrustOptions(tracesConfig));
+
+                        if (!options.getPemTrustOptions().getCertPaths().isEmpty()
+                                || !options.getPemKeyCertOptions().getCertPaths().isEmpty()
+                                || !options.getPemKeyCertOptions().getKeyPaths().isEmpty()) {
+                            options.setSsl(true);
+                            options.setUseAlpn(true);
```
Comment (geoand) [inline extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/exporter/otlp/OtlpRecorder.java:148]: @cescoffier I found that is is necessary, can you confirm?

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/config/runtime/exporter/OtlpExporterTracesConfig.java [hunk 4]
```diff
@@ -31,21 +31,6 @@ public interface OtlpExporterTracesConfig {
     @WithDefault(DEFAULT_GRPC_BASE_URI)
     Optional<String> legacyEndpoint();
 
-    //    /**
-    //     * Sets the certificate chain to use for verifying servers when TLS is enabled. The {@code byte[]}
-    //     * should contain an X.509 certificate collection in PEM format. If not set, TLS connections will
-    //     * use the system default trusted certificates.
-    //     */
-    //    @ConfigItem()
-    //    public Optional<byte[]> certificate;
```
Comment (brunobat) [inline extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/config/runtime/exporter/OtlpExporterTracesConfig.java:40]: I know this is a pain but the certificate in pem format and the property names are normalised:
https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md

Example:
    config.put("otel.exporter.otlp.certificate", certificatePath);
    config.put("otel.exporter.otlp.client.key", clientKeyPath);

We might configure this in a more Quarkusy way but we need to document.

**Review by brunobat — COMMENTED** [review]
Excellent. Getting rid of Armeria was perfect.

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/config/runtime/exporter/OtlpExporterTracesConfig.java (hunk 4 above)
Comment (geoand) [reply extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/config/runtime/exporter/OtlpExporterTracesConfig.java:40]: I'd say let's do such improvements in a follow up

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/exporter/otlp/OtlpRecorder.java (hunk 3 above)
Comment (geoand) [reply extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/exporter/otlp/OtlpRecorder.java:148]: I mean that based on the error message I was seeing, it seemed like Alpn is necessary when using HTTP2. Did I understand correctly?

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/config/runtime/exporter/OtlpExporterTracesConfig.java (hunk 4 above)
Comment (geoand) [reply extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/config/runtime/exporter/OtlpExporterTracesConfig.java:40]: For the time being, I followed what the rest of the Quarkus extensions do.

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/config/runtime/exporter/OtlpExporterTracesConfig.java [hunk 5]
```diff
@@ -73,6 +58,37 @@ public interface OtlpExporterTracesConfig {
...
+         */
+        Optional<List<String>> certs();
+    }
+
+    interface TrustCert {
+        /**
+         * Comma-separated list of the trust certificate files (Pem format).
+         */
+        Optional<List<String>> certs();
+    }
```
Comment (gastaldi) [inline extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/config/runtime/exporter/OtlpExporterTracesConfig.java:90]: Curious if this works (and if makes sense?)

```suggestion
    interface KeyCert extends TrustCert {
        /**
         * Comma-separated list of the path to the key files (Pem format).
         */
        Optional<List<String>> keys();
    }

    interface TrustCert {
        /**
         * Comma-separated list of the trust certificate files (Pem format).
         */
        Optional<List<String>> certs();
    }
```

Comment (geoand) [reply extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/config/runtime/exporter/OtlpExporterTracesConfig.java:90]: It probably does but I wouldn't risk it because the documentation generation probably will break

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/config/runtime/exporter/OtlpExporterTracesConfig.java (hunk 4 above)
Comment (brunobat) [reply extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/config/runtime/exporter/OtlpExporterTracesConfig.java:40]: Sounds good to me. Consistency in Quarkus is more important.

Comment (geoand) [reply extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/config/runtime/exporter/OtlpExporterTracesConfig.java:40]: That's been our approach so far (but no doubt we have made mistakes...)

**Comment by geoand** [comment]
@brunobat all good to merge?

**Review by brunobat — APPROVED** [review]
Thanks @geoand !

**Comment by geoand** [comment]
🙏🏼
