### PR TITLE
Fix for #6442 quarkusDev not working in multi module projects

### LINKED ISSUE #6442: quarkusDev doesn't work in multi module gradle project
**Describe the bug**
If using a multi module gradle project quarkusDev will fail complaining that beans are defined multiple times. This is due to both common/buld/classes and common/buld/lib/common.jar being on the classpath inside of dev-mode-context.dat

Project Structure
```
project-root
... common
... app
```
App depends on common via 
```
compile project(":commons")
```

The error that happens is

```        Suppressed: javax.enterprise.inject.AmbiguousResolutionException: Ambiguous dependencies for type commons.CommonsConfig and qualifiers [@Default]
        - java member: commons.cache.impl.CacheServiceImpl#config
        - declared on CLASS bean [types=[commons.cache.CacheService, commons.cache.impl.CacheServiceImpl, java.lang.Object], qualifiers=[@Default, @Any], target=commons.cache.impl.CacheServiceImpl]
        - available beans:
                - CLASS bean [types=[commons.CommonsConfig, java.lang.Object], qualifiers=[@Default, @Any], target=commons.CommonsConfig]
                - CLASS bean [types=[commons.CommonsConfig, java.lang.Object], qualifiers=[@Default, @Any], target=commons.CommonsConfig]
```

Inside META-INF/dev-mode-context.dat
```
commons/build/classes/java/main
commons/build/libs/commons-v383-1-gf5b4d8a.dirty.jar
```

**Expected behavior**
QuarkusDev should start without issues

**Actual behavior**
QuarkusDev fails due to AmbiguousResolutionException

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin Kernel Version 19.0.0
 - Output of `java -version`:  OpenJDK 64-Bit GraalVM CE 19.2.1 (build 25.232-b07-jvmci-19.2-b03, mixed mode)
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.1.0.FINAL

### PR DESCRIPTION
**Pull request by tobad357**
Fixes #6442 
The fix is to register if a dependency is a Project Component and ignore it if it is as it will be added to the classpath later on

### CODE REVIEW

File: devtools/gradle/src/main/java/io/quarkus/gradle/tasks/QuarkusDev.java [hunk 1]
```diff
@@ -242,7 +242,11 @@ public void startDev() {
                         e);
             }
             for (AppDependency appDep : appModel.getAllDependencies()) {
-                addToClassPaths(classPathManifest, context, appDep.getArtifact().getPath().toFile());
+                if (!appDep.getArtifact().isSubModule()) {
+                    addToClassPaths(classPathManifest, context, appDep.getArtifact().getPath().toFile());
+                } else {
+                    getLogger().info("Ignoring {} as it is a project dependency", appDep);
```
Comment (gsmet) [inline devtools/gradle/src/main/java/io/quarkus/gradle/tasks/QuarkusDev.java]: Should this one be debug instead of info?

Comment (tobad357) [reply devtools/gradle/src/main/java/io/quarkus/gradle/tasks/QuarkusDev.java]: It could be.. but the logging of the added dependencies in addToClasspaths is info so I thought it made sense to be on same level

Comment (gastaldi) [reply devtools/gradle/src/main/java/io/quarkus/gradle/tasks/QuarkusDev.java]: +1 to be debug

**Comment by gastaldi** [comment]
This looks good, but I'll let @aloubyansky chime in this since there are changes to AppArtifact (which should probably also reflect in the Maven plugin)

**Comment by gastaldi** [comment]
Can you squash these commits into a single one? Thanks!

File: devtools/gradle/src/main/java/io/quarkus/gradle/AppModelGradleResolver.java [hunk 2]
```diff
@@ -192,6 +194,10 @@ private ModuleIdentifier getModuleId(ResolvedArtifact a) {
     private AppDependency toAppDependency(ResolvedArtifact a) {
         final String[] split = a.getModuleVersion().toString().split(":");
         final AppArtifact appArtifact = new AppArtifact(split[0], split[1], split[2]);
+        final ComponentIdentifier id = a.getId().getComponentIdentifier();
+        if (id instanceof ProjectComponentIdentifier) {
+            appArtifact.setSubModule(true);
+        }
```
Comment (gastaldi) [inline devtools/gradle/src/main/java/io/quarkus/gradle/AppModelGradleResolver.java]: You can also replace this snippet with `appArtifact.setSubModule(id instanceof ProjectComponentIdentifier)` :wink:

Comment (gastaldi) [reply devtools/gradle/src/main/java/io/quarkus/gradle/AppModelGradleResolver.java]: Or simply `appArtifact.setSubModule(a.getId().getComponentIdentifier() instanceof ProjectComponentIdentifier);`

File: devtools/gradle/src/main/java/io/quarkus/gradle/AppModelGradleResolver.java [hunk 3]
```diff
@@ -23,6 +23,8 @@
 import org.gradle.api.artifacts.ModuleVersionIdentifier;
 import org.gradle.api.artifacts.ResolvedArtifact;
 import org.gradle.api.artifacts.ResolvedConfiguration;
+import org.gradle.api.artifacts.component.ComponentIdentifier;
```
Comment (gastaldi) [inline devtools/gradle/src/main/java/io/quarkus/gradle/AppModelGradleResolver.java]: I think this import is unused now?

Comment (tobad357) [reply devtools/gradle/src/main/java/io/quarkus/gradle/AppModelGradleResolver.java]: Sorted

**Comment by aloubyansky** [comment]
> This looks good, but I'll let @aloubyansky chime in this since there are changes to AppArtifact (which should probably also reflect in the Maven plugin)

Right, I'm not sure about that. We are already iterating though the classpath in QuarkusDev (line 278), could we do the filtering in that loop instead? Thanks.

**Comment by tobad357** [comment]
> > This looks good, but I'll let @aloubyansky chime in this since there are changes to AppArtifact (which should probably also reflect in the Maven plugin)
> 
> Right, I'm not sure about that. We are already iterating though the classpath in QuarkusDev (line 278), could we do the filtering in that loop instead? Thanks.

Don't we want to avoid adding the Jar artifact to the classpath as I would guess it would prevent reloading of the classes in the submodule.

**Comment by aloubyansky** [comment]
Sure, that's what the fix is about, right? I'm not questioning that. My comment was about isSubModule() in AppArtifact. I don't see how we can easily implement that in Maven case and whether we need it in that case. So, I was wondering whether we could do filter deps that should not be added to the classpath in the for loop I mentioned above.

**Comment by tobad357** [comment]
> Sure, that's what the fix is about, right? I'm not questioning that. My comment was about isSubModule() in AppArtifact. I don't see how we can easily implement that in Maven case and whether we need it in that case. So, I was wondering whether we could do filter deps that should not be added to the classpath in the for loop I mentioned above.

The problem is the Jar artifact is being added at line 244-250 and there is currently no way to check if a AppDependency is a project dependency.
My initial plan was to get the Jar artifact name and path from the Configuration and filter as you mentioned but couldn't find a way (this may be due to me not knowing all the Gradle APIs)

**Comment by aloubyansky** [comment]
I think instead of adding the deps to the classpath here https://github.com/quarkusio/quarkus/blob/master/devtools/gradle/src/main/java/io/quarkus/gradle/tasks/QuarkusDev.java#L245 You could create a map of the deps with AppArtifactKey as keys of all the deps.

Then here https://github.com/quarkusio/quarkus/blob/master/devtools/gradle/src/main/java/io/quarkus/gradle/tasks/QuarkusDev.java#L282 you can remove module deps from that map.
And then add to the classpath whatever remained in that map.
WDYT?

**Comment by tobad357** [comment]
@aloubyansky yes that makes sense. I did roughly what you said but instead added all project deps to a Set and then filter while adding to classpath. I think that makes the code a bit clearer vs manipulating a Map of deps in several places.

If you are happy with the change I'll squash the commits

File: independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/model/AppArtifact.java [hunk 4]
```diff
@@ -11,6 +11,8 @@
 
     protected Path path;
 
+    protected boolean subModule;
```
Comment (aloubyansky) [inline independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/model/AppArtifact.java]: Please remove this leftover.

**Review by aloubyansky — CHANGES_REQUESTED** [review]
Yes, looks good, thanks a lot! Please squash the commits.

**Comment by tobad357** [comment]
@aloubyansky thanks for your time, I've removed the property and squashed

**Review by aloubyansky — APPROVED** [review]
You're welcome @tobad357! Great work :)
