### PR TITLE
Prevent infinite loop if pom parent has empty relative path

### LINKED ISSUE #2719: Infinite iteration in LocalProject.loadRootModel
**Describe the bug**
When <relativePath> of <parent> is set to empty value, loadRootModel iterates indefinitely

**Expected behavior**
iteration should quit

**Actual behavior**
iteration continues forever

**To Reproduce**
1. set pom.xml to contain a parent similar to:
```xml
  <parent>
    <groupId>com.example.quarkus</groupId>
    <artifactId>parent</artifactId>
    <version>1.0</version>
    <relativePath></relativePath>
  </parent>
```

**Environment (please complete the following information):**
  - Quarkus version or git rev: 0.16.0

**Additional context**
 io.quarkus.bootstrap.resolver.maven.workspace.LocalProject
line 86:
            if(parent.getRelativePath() != null) {
should be 
            if(parent.getRelativePath() != null && !parent.getRelativePath().isEmpty) {

### PR DESCRIPTION
**Pull request by rquinio**
Fixes #2719 

I've noticed the files formatting was not matching the Quarkus eclipse-format.xml, but I've tried keeping the diff noise to a minimum.

### CODE REVIEW

**Comment by gsmet** [comment]
@aloubyansky Maybe we should apply the formatting to the bootstrap project too, if not already done?

File: independent-projects/bootstrap/core/src/test/java/io/quarkus/bootstrap/workspace/test/LocalWorkspaceDiscoveryTest.java [hunk 1]
```diff
@@ -167,35 +182,57 @@ public void loadWorkspaceForModuleWithNotDirectParentPath() throws Exception {
...
+                projects.containsKey(new AppArtifactKey(MvnProjectBuilder.DEFAULT_GROUP_ID, "root-module-not-direct-child")));
         assertTrue(projects.containsKey(new AppArtifactKey(MvnProjectBuilder.DEFAULT_GROUP_ID, "root")));
         assertTrue(projects.containsKey(new AppArtifactKey(MvnProjectBuilder.DEFAULT_GROUP_ID, "non-module-child")));
         assertTrue(projects.containsKey(new AppArtifactKey(MvnProjectBuilder.DEFAULT_GROUP_ID, "another-child")));
+        assertTrue(projects.containsKey(new AppArtifactKey(MvnProjectBuilder.DEFAULT_GROUP_ID, "empty-parent-relative-path-module")));
         assertLocalDeps(project, "another-child");
     }
+    
+    /**
+     * Empty realtivePath is a hack sometimes used to always resolve parent from repository and skip default "../" lookup
```
Comment (gsmet) [inline independent-projects/bootstrap/core/src/test/java/io/quarkus/bootstrap/workspace/test/LocalWorkspaceDiscoveryTest.java]:
```suggestion
     * Empty relativePath is a hack sometimes used to always resolve parent from repository and skip default "../" lookup
```

**Review by aloubyansky — APPROVED** [review]
Thanks a lot for the contribution @rquinio
