### PR TITLE
 Dev mode: fixed discovery of local dependencies inherited from parents

### LINKED ISSUE #10484: Devmode, Maven: Broken classpath when a local module depends via its parent on another local module
**Describe the bug**
Imagine the following Maven module structure:
- `level0`
- `level1` depends on `level0`
- `level2` depends on `level1`
  - `level2.submodule` (depends on `level1` via parent `level2`)
- `runner` depends on `level2` **and** `level0`

Each `level*` module contains a simple `@ApplicationScoped` service that calls the service from the "next-lower" level (e.g. `level1` -> `level0`).
`runner` contains a REST resource with two methods, one calling the `level2` service and one directly calling the `level0` service.

Both methods are working as expected with runner-jar, but in devmode the call to `level2` fails in ArC with a `NoClassDefFoundError` for the `level0` service which is very confusing because the direct call to `level0` _does work_!
This is with the current `master` that includes #10421. With 1.6.0.Final (or any earlier version) which does not yet contain that change, you'll see a `ClassCastException` instead.

**Expected behavior**
No error, should work in devmode the way it works with runner-jar.

**Actual behavior**
- `master`: `java.lang.NoClassDefFoundError: org/acme/level0/Level0Service`
- 1.6.0.Final or earlier:
    ```
    java.lang.ClassCastException: class org.acme.level0.Level0Service_ClientProxy cannot be cast to class org.acme.level0.Level0Service (org.acme.level0.Level0Service_ClientProxy is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @439b15f2; org.acme.level0.Level0Service is in unnamed module of loader 'app')
    ```

**To Reproduce**
1. See Reproducer-PR: #10485

**Configuration**
n/a

**Screenshots**
n/a

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:
    ```
    MINGW64_NT-10.0-18363 BIGBLUE 3.0.7-338.x86_64 2019-11-21 23:07 UTC x86_64 Msys
    ```
 - Output of `java -version`: 
    ```
    openjdk version "11.0.7" 2020-04-14
    OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
    OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)
    ```
 - GraalVM version (if different from Java): n/a
 - Quarkus version or git rev: `master` (NCDFE) or 1.6.0.Final or earlier (CCE)
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): `Apache Maven 3.6.3`

**Additional context**
I ran into this issue with Apache CXF: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/ClassCastException.20in.20dev.20mode.20but.20not.20with.20runner-jar
But in the end this has nothing to do with CXF specifically.

I'm 99% sure that I already know the **root cause** of this bug:

In `DevMojo`, `level1` is _not_ added to the `DevModeContext` and ends up in the `classPathManifest` which in turn does (of course) not contain any other local projects/modules (which _are_ part of the `DevModeContext`).
Because of this, `level1` cannot see `level0` in its classloader (or sees it in a diferent classloader before #10421).

`level1` is _not_ added to the `DevModeContext` because `LocalProject.collectSelfWithLocalDeps(LocalProject, Set<AppArtifactKey>, List<LocalProject>)` is working with `getRawModel().getDependencies()`, **but that will only include the _direct_ dependencies of a module, _not_ the ones it inherits from its parent(s)!** (it is just a "raw" model after all!)

So it seems that `LocalProject` will have to check the parent models as well, but that would mean custom merging and leaves the question whether this should really be done "by hand" or whether this should be offloaded to some OOTB Maven interpolation instead.
There is also a direct usage of `getRawModel().getDependencies()` in `DevMojo.filterExtensionDependencies()`.

There are also some more methods in `LocalProject` that are _not_ considering any parent(s), see usages of `rawModel.getBuild()` .

PS: From a design perspective, IMHO, `rawModel` should not be exposed like this by `LocalProject`.
I'd also strongly suggest to introduce a model cache to avoid costly re-parsing of already parsed parents.

### PR DESCRIPTION
**Pull request by aloubyansky**
Fixes #10484

### CODE REVIEW

File: independent-projects/bootstrap/maven-resolver/src/test/java/io/quarkus/bootstrap/workspace/test/LocalWorkspaceDiscoveryTest.java [hunk 1]
```diff
@@ -128,8 +127,6 @@ public void loadIndependentProjectInTheWorkspaceTree() throws Exception {
         final Map<AppArtifactKey, LocalProject> projects = project.getWorkspace().getProjects();
         assertEquals(6, projects.size());
         assertTrue(projects.containsKey(new AppArtifactKey(MvnProjectBuilder.DEFAULT_GROUP_ID, "independent")));
-
-        assertLocalDeps(project, "root-module-not-direct-child", "root-no-parent-module", "root-module-with-parent");
```
Comment (geoand) [inline independent-projects/bootstrap/maven-resolver/src/test/java/io/quarkus/bootstrap/workspace/test/LocalWorkspaceDiscoveryTest.java:132]: Can you please explain the rationale around the removal of these assertions?

Comment (aloubyansky) [reply independent-projects/bootstrap/maven-resolver/src/test/java/io/quarkus/bootstrap/workspace/test/LocalWorkspaceDiscoveryTest.java:132]: I removed LocalProject.getSelfWithLocalDeps() method because it did not return a complete set of dependencies and was only used in DevMojo.

Comment (geoand) [reply independent-projects/bootstrap/maven-resolver/src/test/java/io/quarkus/bootstrap/workspace/test/LocalWorkspaceDiscoveryTest.java:132]: Gotcha, thanks

File: integration-tests/maven/src/test/java/io/quarkus/maven/it/DevMojoIT.java [hunk 2]
```diff
@@ -814,4 +814,10 @@ public void testResourcesFromClasspath() throws MavenInvocationException, IOExce
         // test that we don't get multiple instances of a resource when loading from the ClassLoader
         assertThat(DevModeTestUtils.getHttpResponse("/cp/resourcesCount")).isEqualTo("1");
     }
+
+    @Test
+    public void testThatDependencyInParentIsEvaluated() throws IOException, MavenInvocationException {
+        testDir = initProject("projects/multimodule-parent-dep");
+        runAndCheck();
```
Comment (geoand) [inline integration-tests/maven/src/test/java/io/quarkus/maven/it/DevMojoIT.java:821]: Should we also be asserting the response of `/hello-0`?

Comment (aloubyansky) [reply integration-tests/maven/src/test/java/io/quarkus/maven/it/DevMojoIT.java:821]: We could. I don't see anything special about it though. @famod wdyt?

Comment (famod) [reply integration-tests/maven/src/test/java/io/quarkus/maven/it/DevMojoIT.java:821]: It _was_ special before this fix. After this fix both paths should behave the same.

I don't think `/hello-0` would ever break _individually_ in the future (`/hello` would then break as well, I suppose).

Long story short: I 'd leave it this way.

Comment (geoand) [reply integration-tests/maven/src/test/java/io/quarkus/maven/it/DevMojoIT.java:821]: OK, thanks

**Review by geoand — APPROVED** [review]

**Comment by famod** [comment]
What about `dep.getRawModel().getDependencies()` here?https://github.com/aloubyansky/quarkus/blob/10484/devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java#L916

**Comment by geoand** [comment]
Please rebase this onto master to up a CI fix

**Comment by aloubyansky** [comment]
> What about `dep.getRawModel().getDependencies()` here?https://github.com/aloubyansky/quarkus/blob/10484/devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java#L916

I re-implemented it and added a test for a project that includes an extension.

**Comment by stuartwdouglas** [comment]
@aloubyansky needs a rebase

**Comment by famod** [comment]
Would be great if this could be backported.

**Comment by aloubyansky** [comment]
It's not a regression though. I'll let @gsmet decide.

**Comment by geoand** [comment]
It might be a little to risky to include in 1.6?

**Comment by famod** [comment]
Well, not entirely sure whether this is really comparable but #10576 _is_ marked for backporting (potentially).

But I won't die if it is not backported. 😉

**Comment by aloubyansky** [comment]
Don't @famod we count on you
