### PR TITLE
Qute: fix template global class generation in the dev mode #2

### LINKED ISSUE #46005: Qute TemplateGlobal throws error on live reload
### Describe the bug

I upgraded my app to the latest Quarkus version and i got the following error (it used to work)

java.lang.IllegalArgumentException: Namespace [global] may not be handled by multiple resolvers of the same priority [-999]: io.quarkiverse.renarde.util.Globals_Globals@56d489bd and gr.admin.qute.MyGlobal_Globals@45bbbc71

In my project i defined a class with @TemplateGlobal which has a dependency to Renarde which has it's own @TemplateGlobal class.

It might be related to https://github.com/quarkusio/quarkus/pull/45771

When you start the app with `mvn quarkus:dev` it works as expected, but if you change something and trigger the live reload it will throw the error. 

Also, i tried a prod build and the error did not occur.

[Reproducer](https://github.com/gbourant/global-template-bug)

### PR DESCRIPTION
**Pull request by mkouba**
- follows-up on #45771
- fixes #46005

### CODE REVIEW

**Comment by mkouba** [comment]
@gbourant it would be great if you could test this fix as well.

**Comment by gbourant** [comment]
Thank you @mkouba, i tested it and now it's working.

File: extensions/qute/deployment/src/main/java/io/quarkus/qute/deployment/QuteDevModeProcessor.java [hunk 1]
```diff
@@ -53,7 +53,7 @@ public boolean test(String t) {
                             return false;
                         }
                     });
-            try (ClassCreator classCreator = ClassCreator.builder().className("io.quarkus.qute.test.QuteDummyGlobals")
+            try (ClassCreator classCreator = ClassCreator.builder().className("org.acme.qute.test.QuteDummyGlobals")
```
Comment (gastaldi) [inline extensions/qute/deployment/src/main/java/io/quarkus/qute/deployment/QuteDevModeProcessor.java:56]: Why changing this package name?

**Review by gastaldi — APPROVED** [review]

File: extensions/qute/deployment/src/main/java/io/quarkus/qute/deployment/QuteDevModeProcessor.java (hunk 1 above)
Comment (gsmet) [reply extensions/qute/deployment/src/main/java/io/quarkus/qute/deployment/QuteDevModeProcessor.java:56]: Yeah this is a bit odd.

Comment (mkouba) [reply extensions/qute/deployment/src/main/java/io/quarkus/qute/deployment/QuteDevModeProcessor.java:56]: > Why changing this package name?

Because we need to simulate an ordering issue where the generated globals are sorted by the FQCN of the declaring class.
