### PR TITLE
Fixed platform stream selection when platform key is null

### LINKED ISSUE #22402: quarkus create -S 2.5 fails if registry.quarkus.redhat.com is first
### Describe the bug

I have quarkus.redhat.com and quarkus.io listed:
```
quarkus registry list
Configured Quarkus extension registries:
playground.io (disabled)
registry.quarkus.redhat.com
registry.quarkus.io
(Read from /Users/max/.quarkus/config.yaml)
```

but running create using -S 2.5 (latest recommend community) fails:

```
quarkus create -S 2.5
Creating an app (default project type, see --help).
[ERROR] ❗  Unable to create project: Failed to locate stream 2.5 in platform(s): com.redhat.quarkus.platform, io.quarkus.platform
```

If I run `quarkus registry remove registry.quarkus.redhat.com` then `quarkus create -S 2.5` starts working 

### Expected behavior

should generate for stream 2.5 as found in the registry.quarkus.io registry.

Or at least state which platforms was searched so user can understand why it was rejected/not found.

### Actual behavior

just says it cannot find 2.5 even though it is there.

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by aloubyansky**
Fixes #22402

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]
LGTM 👍🏻

File: independent-projects/tools/devtools-testing/src/test/java/io/quarkus/devtools/project/create/UpstreamStreamCoordsWithNullPlatformKeyTest.java [hunk 1]
```diff
@@ -0,0 +1,76 @@
...
+import org.junit.jupiter.api.Test;
+
+public class UpstreamStreamCoordsWithNullPlatformKeyTest extends MultiplePlatformBomsTestBase {
+
+    private static final String DOWNSTREAM_PLATFORM_KEY = "io.downstream.platform";
+    private static final String UPSTREAM_PLATFORM_KEY = "io.upstream.platform";
+
+    @BeforeAll
+    public static void setup() throws Exception {
+        TestRegistryClientBuilder.newInstance()
```
Comment (gastaldi) [inline independent-projects/tools/devtools-testing/src/test/java/io/quarkus/devtools/project/create/UpstreamStreamCoordsWithNullPlatformKeyTest.java:18]: Hah, didn't know about this class, awesome!
