### PR TITLE
Fix cache compatibility with rest-client

### LINKED ISSUE #8221: @CacheResult for RestClient methods
**Description**
Make `io.quarkus.cache.CacheResult` work on RestClient's methods.
Right now, if you annotate a Rest Client method with `@CacheResult`, it will just ignore it silently and not cache anything.

**Implementation ideas**
[Discussed here](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/.40CacheResult.20.2B.20RestClient).
[Working Example Reproducer here.](https://github.com/rinaldodev/quarkus-issue-cacheresult-restclient)

Seeing RestClient's implementations as CDI beans, I would expect the `@CacheResult` annotation to work OOTB with it's methods.

### PR DESCRIPTION
**Pull request by gwenneg**
Fixes #8221.

This PR:
- Should not change anything in terms of extension behavior (except for the bug it fixes of course): none of the runtime tests were changed.
- Removes the interceptor bindings previously added using `AnnotationsTransformer` because that's what prevented the extension from being compatible with MP REST Client. The former API annotations (`@CacheResult`, `@CacheInvalidate` and `@CacheInvalidateAll`) are now the new interceptor bindings.
- Contains a full refactor of all build time validations.

Quarkus (Arc) currently supports repeated caching interceptor bindings (like `@CacheInvalidateAll`) but this PR **does not** allow repeated interceptor bindings on a method from a MP REST Client bean. The interceptors implementation from MP REST Client simply ignores repeated interceptor bindings. That's why there's a dedicated check at build time to forbid that combination.

### CODE REVIEW

File: extensions/cache/runtime/src/main/java/io/quarkus/cache/runtime/CacheInterceptor.java [hunk 1]
```diff
@@ -18,28 +22,66 @@
...
+            List<Short> positions = new ArrayList<>();
+            for (short i = 0; i < parameters.length; i++) {
+                if (parameters[i].isAnnotationPresent(CacheKey.class)) {
+                    positions.add(i);
+                }
+            }
+            short[] positionsArray = new short[positions.size()];
+            for (int i = 0; i < positions.size(); i++) {
+                positionsArray[i] = positions.get(i);
+            }
```
Comment (gwenneg) [inline extensions/cache/runtime/src/main/java/io/quarkus/cache/runtime/CacheInterceptor.java:76]: I know this is not pretty, but there's a reason behind that: avoid lambdas in runtime code.

**Comment by gwenneg** [comment]
cc @geoand for the `SpringCacheAnnotationsTransformer` changes

File: extensions/spring-cache/deployment/src/main/java/io/quarkus/spring/cache/SpringCacheAnnotationsTransformer.java [hunk 2]
```diff
@@ -15,21 +15,21 @@
...
 
     private static final DotName CACHE_RESULT_INTERCEPTOR_BINDING = DotName
-            .createSimple(CacheResultInterceptorBinding.class.getName());
+            .createSimple(CacheResult.class.getName());
     private static final DotName CACHE_INVALIDATE_INTERCEPTOR_BINDING = DotName
-            .createSimple(CacheInvalidateInterceptorBinding.class.getName());
+            .createSimple(CacheInvalidate.class.getName());
     private static final DotName CACHE_INVALIDATE_ALL_INTERCEPTOR_BINDING = DotName
-            .createSimple(CacheInvalidateAllInterceptorBinding.class.getName());
+            .createSimple(CacheInvalidateAll.class.getName());
```
Comment (gwenneg) [inline extensions/spring-cache/deployment/src/main/java/io/quarkus/spring/cache/SpringCacheAnnotationsTransformer.java:32]: cc @geoand

File: extensions/cache/deployment/src/test/java/io/quarkus/cache/test/deployment/DeploymentExceptionsTest.java [hunk 3]
```diff
@@ -0,0 +1,123 @@
...
+                assertEquals(10, t.getSuppressed().length);
+                assertPrivateMethodTargetException(t, "shouldThrowPrivateMethodTargetException", 1);
+                assertPrivateMethodTargetException(t, "shouldAlsoThrowPrivateMethodTargetException", 2);
+                assertVoidReturnTypeTargetException(t, "showThrowVoidReturnTypeTargetException");
+                assertClassTargetException(t, TestResource.class, 1);
+                assertClassTargetException(t, TestBean.class, 2);
+                assertUnknownCacheNameException(t, UNKNOWN_CACHE_1);
+                assertUnknownCacheNameException(t, UNKNOWN_CACHE_2);
+                assertUnknownCacheNameException(t, UNKNOWN_CACHE_3);
+            });
```
Comment (gwenneg) [inline extensions/cache/deployment/src/test/java/io/quarkus/cache/test/deployment/DeploymentExceptionsTest.java:53]: Here's a preview of what would be logged if the exceptions were not "caught" by the test:
```
Caused by: javax.enterprise.inject.spi.DeploymentException: Found 10 deployment problems:
[1] @CacheResult is not allowed on a method returning void [class=io.quarkus.cache.test.deployment.DeploymentExceptionsTest$TestResource, method=showThrowVoidReturnTypeTargetException]
[2] Caching annotations are not allowed on a class [class=io.quarkus.cache.test.deployment.DeploymentExceptionsTest$TestResource, annotation=io.quarkus.cache.CacheInvalidate]
[3] Caching annotations are not allowed on a private method [class=io.quarkus.cache.test.deployment.DeploymentExceptionsTest$TestResource, method=shouldThrowPrivateMethodTargetException, annotation=io.quarkus.cache.CacheInvalidateAll]
[4] Caching annotations are not allowed on a private method [class=io.quarkus.cache.test.deployment.DeploymentExceptionsTest$TestResource, method=shouldAlsoThrowPrivateMethodTargetException, annotation=io.quarkus.cache.CacheInvalidate]
[5] Caching annotations are not allowed on a private method [class=io.quarkus.cache.test.deployment.DeploymentExceptionsTest$TestResource, method=shouldAlsoThrowPrivateMethodTargetException, annotation=io.quarkus.cache.CacheInvalidate]
[6] Caching annotations are not allowed on a class [class=io.quarkus.cache.test.deployment.DeploymentExceptionsTest$TestBean, annotation=io.quarkus.cache.CacheInvalidateAll]
[7] Caching annotations are not allowed on a class [class=io.quarkus.cache.test.deployment.DeploymentExceptionsTest$TestBean, annotation=io.quarkus.cache.CacheInvalidateAll]
[8] A field or method parameter is annotated with a @CacheName annotation referencing an unknown cache name [class=io.quarkus.cache.test.deployment.DeploymentExceptionsTest$TestBean, cacheName=unknown-cache-1]
[9] A field or method parameter is annotated with a @CacheName annotation referencing an unknown cache name [class=io.quarkus.cache.test.deployment.DeploymentExceptionsTest$TestBean, cacheName=unknown-cache-2]
[10] A field or method parameter is annotated with a @CacheName annotation referencing an unknown cache name [class=io.quarkus.cache.test.deployment.DeploymentExceptionsTest$TestBean, cacheName=unknown-cache-3]
```

File: extensions/spring-cache/deployment/src/main/java/io/quarkus/spring/cache/SpringCacheAnnotationsTransformer.java (hunk 2 above)
Comment (geoand) [reply extensions/spring-cache/deployment/src/main/java/io/quarkus/spring/cache/SpringCacheAnnotationsTransformer.java:32]: 👍🏼

**Comment by geoand** [comment]
Thanks a lot for this work @gwenneg! 

I'd like @mkouba to take a look

**Comment by gwenneg** [comment]
Conflicts solved.

File: extensions/cache/runtime/src/main/java/io/quarkus/cache/runtime/CacheInterceptionContext.java [hunk 4]
```diff
@@ -0,0 +1,23 @@
+package io.quarkus.cache.runtime;
+
+import java.lang.annotation.Annotation;
+import java.util.ArrayList;
+import java.util.List;
+
+public class CacheInterceptionContext<T extends Annotation> {
```
Comment (mkouba) [inline extensions/cache/runtime/src/main/java/io/quarkus/cache/runtime/CacheInterceptionContext.java:7]: It would be nice if this class was immutable... WDYT?

**Comment by mkouba** [comment]
I added one minor comment, otherwise looks good to me.

**Review by gsmet — APPROVED** [review]
OK, looks like both @geoand and @mkouba are ok with it so let's merge.

The CI failure is a concurrency issue Gwenneg solved in another PR.

**Comment by gwenneg** [comment]
I was actually planning on applying @mkouba's suggestion about immutability and ask for another review tonight 😃 I'll do it in a separate PR.

**Comment by gsmet** [comment]
Ah I saw you pushed another commit, I thought you fixed it. Sorry :/

**Comment by gwenneg** [comment]
It's no big deal, we're only talking about a code improvement, master isn't broken :)

Thanks @geoand and @mkouba for the reviews!

File: extensions/cache/runtime/src/main/java/io/quarkus/cache/runtime/CacheInterceptionContext.java (hunk 4 above)
Comment (gwenneg) [reply extensions/cache/runtime/src/main/java/io/quarkus/cache/runtime/CacheInterceptionContext.java:7]: I agree, thanks for the suggestion. It took care of it in #14111.
