### PR TITLE
Making sure deployment modules excluded in POM files aren't pulled in by the Gradle plugin

### LINKED ISSUE #38533: 'Unable to find a JDBC driver' for Hibernate Reactive after updating to 3.7.1
### Describe the bug

When using `io.quarkus:quarkus-hibernate-reactive-panache` with version `3.7.1`, the build fails with an error message regarding a missing JDBC driver even though JDBC is not used in the application. In version `3.6.9`, the application successfully builds. I am not entirely sure, but it seems like the issue is only reproducible with Gradle.

The application only uses reactive dependencies:
```
dependencies {
    implementation enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")
    implementation 'io.quarkus:quarkus-resteasy-reactive-jackson'
    implementation 'io.quarkus:quarkus-hibernate-reactive-panache'
    implementation 'io.quarkus:quarkus-reactive-pg-client'
    implementation 'io.quarkus:quarkus-arc'
    implementation 'io.quarkus:quarkus-resteasy-reactive'
    testImplementation 'io.quarkus:quarkus-junit5'
    testImplementation 'io.rest-assured:rest-assured'
}
```

Furthermore, the configuration is as suggested [in the docs](https://quarkus.io/guides/hibernate-reactive):
```
quarkus.datasource.db-kind = postgresql
quarkus.datasource.username = quarkus_test
quarkus.datasource.password = quarkus_test
quarkus.datasource.reactive.url = vertx-reactive:postgresql://localhost:5432/quarkus_test
```

### Expected behavior

The application starts and accesses the database using Hibernate Reactive.

### Actual behavior

The following exception is produced when starting the dev mode:

```
     2024-02-01 16:37:42,442 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.agroal.deployment.AgroalProcessor#build threw an exception: io.quarkus.runtime.configuration.ConfigurationException: Unable to find a JDBC driver corresponding to the database kind 'postgresql' for the default datasource (available: ''). Check if it's a typo, otherwise provide a suitable JDBC driver extension, define the driver manually, or disable the JDBC datasource by adding 'quarkus.datasource.jdbc=false' to your configuration if you don't need it.
        at io.quarkus.agroal.deployment.AgroalProcessor.resolveDriver(AgroalProcessor.java:371)
        at io.quarkus.agroal.deployment.AgroalProcessor.getAggregatedConfigBuildItems(AgroalProcessor.java:345)
        at io.quarkus.agroal.deployment.AgroalProcessor.build(AgroalProcessor.java:102)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at java.base/java.lang.Thread.run(Thread.java:1583)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)

        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:334)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:251)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:60)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:112)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:433)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:55)
        at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:138)
        at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:93)
        at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:131)
        at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.agroal.deployment.AgroalProcessor#build threw an exception: io.quarkus.runtime.configuration.ConfigurationException: Unable to find a JDBC driver corresponding to the database kind 'postgresql' for the default datasource (available: ''). Check if it's a typo, otherwise provide a suitable JDBC driver extension, define the driver manually, or disable the JDBC datasource by adding 'quarkus.datasource.jdbc=false' to your configuration if you don't need it.
        at io.quarkus.agroal.deployment.AgroalProcessor.resolveDriver(AgroalProcessor.java:371)
        at io.quarkus.agroal.deployment.AgroalProcessor.getAggregatedConfigBuildItems(AgroalProcessor.java:345)
        at io.quarkus.agroal.deployment.AgroalProcessor.build(AgroalProcessor.java:102)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at java.base/java.lang.Thread.run(Thread.java:1583)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)

        at io.quarkus.builder.Execution.run(Execution.java:123)
        at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
        at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:160)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:330)
        ... 9 more
Caused by: io.quarkus.runtime.configuration.ConfigurationException: Unable to find a JDBC driver corresponding to the database kind 'postgresql' for the default datasource (available: ''). Check if it's a typo, otherwise provide a suitable JDBC driver extension, define the driver manually, or disable the JDBC datasource by adding 'quarkus.datasource.jdbc=false' to your configuration if you don't need it.
        at io.quarkus.agroal.deployment.AgroalProcessor.resolveDriver(AgroalProcessor.java:371)
        at io.quarkus.agroal.deployment.AgroalProcessor.getAggregatedConfigBuildItems(AgroalProcessor.java:345)
        at io.quarkus.agroal.deployment.AgroalProcessor.build(AgroalProcessor.java:102)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at java.base/java.lang.Thread.run(Thread.java:1583)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

When setting the `quarkus.datasource.jdbc=false` property as suggested, the following error is produced:

```
     2024-02-01 16:46:07,846 ERROR [io.qua.run.boo.StartupActionImpl] (Quarkus Main Thread) Error running Quarkus: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:113)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.ExceptionInInitializerError
        at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
        at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
        at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
        at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300)
        at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(MethodHandleAccessorFactory.java:103)
        at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:200)
        at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:549)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:70)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        ... 3 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: io.quarkus.agroal.runtime.DataSourcesJdbcBuildTimeConfig
        at io.quarkus.runtime.configuration.AbstractConfigBuilder.withMapping(AbstractConfigBuilder.java:66)
        at io.quarkus.runtime.generated.StaticInitConfigCustomizer.configBuilder(Unknown Source)
        at io.smallrye.config.SmallRyeConfigBuilder.lambda$build$0(SmallRyeConfigBuilder.java:722)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at io.smallrye.config.SmallRyeConfigBuilder.build(SmallRyeConfigBuilder.java:722)
        at io.quarkus.runtime.generated.Config.<clinit>(Unknown Source)
        ... 17 more
Caused by: java.lang.ClassNotFoundException: io.quarkus.agroal.runtime.DataSourcesJdbcBuildTimeConfig
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:518)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:468)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:518)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:468)
        at io.quarkus.runtime.configuration.AbstractConfigBuilder.withMapping(AbstractConfigBuilder.java:64)
        ... 29 more
```

### How to Reproduce?

Please find the attached reproducer for the issue:

[jdb-driver-exception-reproducer.zip](https://github.com/quarkusio/quarkus/files/14127641/jdb-driver-exception-reproducer.zip)

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`
```
openjdk 21.0.2 2024-01-16 LTS
OpenJDK Runtime Environment Temurin-21.0.2+13 (build 21.0.2+13-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.2+13 (build 21.0.2+13-LTS, mixed mode, sharing)
```

### Quarkus version or git rev

3.7.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
```
------------------------------------------------------------
Gradle 8.5 ------------------------------------------------------------ 

Build time:   2023-11-29 14:08:57 UTC
Revision:     28aca86a7180baa17117e0e5ba01d8ea9feca598 

Kotlin:       1.9.20
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          21.0.2 (Eclipse Adoptium 21.0.2+13-LTS)
OS:           Windows 11 10.0 amd64
```
### Additional information

_No response_

### PR DESCRIPTION
**Pull request by vemilyus**
This makes sure that exclusions in POM files of deployment modules are respected.

Once case where this is critical is when using quarkus-hibernate-reactive. Its deployment module takes care of pulling in quarkus-hibernate-orm-deployment where it excludes Agroal and Narayana.

If that exclusion isn't taken into account by the Gradle plugin, it pulls in quarkus-hibernate-orm-deployment on its own, where those other modules aren't excluded, which leads to a failure at runtime because Agroal tries to initialize and looks for a JDBC driver which isn't typically available in reactive DB scenarios.

- Fixes #38533

### CODE REVIEW

File: devtools/gradle/gradle-model/src/main/java/io/quarkus/gradle/tooling/pom/PomUtils.java [hunk 1]
```diff
@@ -0,0 +1,69 @@
...
+import org.gradle.api.internal.artifacts.DefaultModuleIdentifier;
+import org.gradle.api.internal.artifacts.result.DefaultResolvedArtifactResult;
+import org.gradle.internal.component.external.model.DefaultModuleComponentIdentifier;
+import org.gradle.maven.MavenModule;
+import org.gradle.maven.MavenPomArtifact;
+
+import io.quarkus.maven.dependency.ArtifactCoords;
+
+public final class PomUtils {
+    public static Set<String> readDeploymentDependencies(Project project, ArtifactCoords artifactCoords) {
```
Comment (gsmet) [inline devtools/gradle/gradle-model/src/main/java/io/quarkus/gradle/tooling/pom/PomUtils.java:25]: I will let @aloubyansky  chime in but I'm pretty sure we don't want to read the POM.

What I don't exactly understand is how you end up including these deployment dependencies given they shouldn't be part of the dependencies at all. But I'm not exactly sure how you get to them.

**Review by gsmet — COMMENTED** [review]
Thanks for this effort. I'm not entirely sure about the approach though.

File: devtools/gradle/gradle-model/src/main/java/io/quarkus/gradle/tooling/pom/PomUtils.java (hunk 1 above)
Comment (vemilyus) [reply devtools/gradle/gradle-model/src/main/java/io/quarkus/gradle/tooling/pom/PomUtils.java:25]: At the moment we go recursively through all dependencies to find the extensions for which we also need to add deployment modules.

Another option would be to turn the enforcement up to 11 and only consider first level extension dependencies. But there we would lose out on extensions pulled in by normal libraries (which is a use-case I have seen, because I do it).

For the Gradle Extension plugin we'd also then need to go much harder on enforcement for the deployment module dependencies, meaning we'd have to make the validation task mandatory for building the final artifact. This would also include a change to the documentation making adding the deployment modules of other extensions mandatory, otherwise they would be missing from the deployment classpath.

Comment (gsmet) [reply devtools/gradle/gradle-model/src/main/java/io/quarkus/gradle/tooling/pom/PomUtils.java:25]: What I don't understand is that I would expect that you would have an easy way in Gradle to resolve transitive dependencies of an app, and I would expect these transitive dependencies to respect the exclusions that are in the POM files.
I don't understand why we are trying to resolve things ourselves and thus ignoring the exclusions.

Note that I'm not familiar at all with the Gradle API so I could be completely mistaken.

Comment (aloubyansky) [reply devtools/gradle/gradle-model/src/main/java/io/quarkus/gradle/tooling/pom/PomUtils.java:25]: I'll copy here our exchange on the original commit @vemilyus 
```
aloubyansky 

One point to keep in mind is that, when we resolve deployment dependencies, we need to resolve only the top level one deployment artifact. So in that issue we are fixing, it'll be quarkus-hibernate-reactive-deployment. It will already resolve its dependencies with the exclusions applied.
Then we "simply" replace the quarkus-hibernate-reactive with quarkus-hibernate-reactive-deployment and its dependencies (where quarkus-hibernate-reactive is also present) to create the Quarkus build classpath.

However, when we resolve quarkus-hibernate-reactive-deployment we should apply exclusions from the dependencies that appear higher in the hierarchy, e.g. if quarkus-hibernate-reactive was a dependency of acme-lib and my-app had a dependency on acme-lib with quarkus-hibernate-reactive pulled in as its transitive dependency. So, if my-app configured dependency exclusions on acme-lib dependency, those exclusions that should also apply when we resolve dependencies of quarkus-hibernate-reactive-deployment.

vemilyus  Author Owner

Let me address your concerns one at a time:

We can never guarantee that deployment modules pull in all the deployment modules of an extension's runtime dependencies. We also don't enforce the validateExtension task in the extension plugin, which can also be disabled.
By only resolving the first level artifacts we lose out on extensions pulled in by normal libraries.
Extensions that are dependencies of normal libs (acme-lib) wouldn't be recognized as extensions, thus their deployment module wouldn't be added to the deployment classpath thereby nullifying its functionality.
```

Comment (aloubyansky) [reply devtools/gradle/gradle-model/src/main/java/io/quarkus/gradle/tooling/pom/PomUtils.java:25]: > We can never guarantee that deployment modules pull in all the deployment modules of an extension's runtime dependencies.

Why not? The extension dependency model implies consistency between runtime and deployment dependencies. Meaning if ext-a-runtime depends on ext-b-runtime then ext-a-deployment will depend on ext-b-deployment. If that rule is not followed there is not guarantee that extension will work, iow it's not supported.

Comment (aloubyansky) [reply devtools/gradle/gradle-model/src/main/java/io/quarkus/gradle/tooling/pom/PomUtils.java:25]: > By only resolving the first level artifacts we lose out on extensions pulled in by normal libraries.

If by first level you mean direct dependencies and in that case you are correct. Which is why we walk dependency trees until we meet the top level runtime extension artifact - that one will be the "first level" from that point.

Comment (vemilyus) [reply devtools/gradle/gradle-model/src/main/java/io/quarkus/gradle/tooling/pom/PomUtils.java:25]: So, if I understand you correctly we only walk regular libraries recursively and when we hit an extension we don't walk its dependencies?

Then I'd like to bring to mind my comment from two days ago where I mentioned that we should go hard on validation of extensions then, to make sure that only extensions which fit the model you mentioned can get published.

Comment (vemilyus) [reply devtools/gradle/gradle-model/src/main/java/io/quarkus/gradle/tooling/pom/PomUtils.java:25]: @aloubyansky In addition I'd propose that I then also add the feature to the Gradle extension plugin to automatically add the deployment modules of runtime extension dependencies to the deployment module unless the user specifies them himself, so we can make somewhat sure the deployment dependencies aren't forgotten :grin:

Comment (aloubyansky) [reply devtools/gradle/gradle-model/src/main/java/io/quarkus/gradle/tooling/pom/PomUtils.java:25]: We need to visit all the dependencies and identify all the extension artifacts either way since we need to make sure we activate all the conditional dependencies that need to be activated.

But when it comes to "injecting" deployment dependencies, we essentially replace the top level runtime extension dependency node (whether it appears to be a direct or a transitive dependency of an app) with its corresponding deployment dependency node that we would resolve in the plugin.

+1 to improving the extension dependency validation check.

I wouldn't add dependencies automatically. I would prefer failing the build with an error suggesting what should be fixed in the project.

Thanks a lot for looking into this @vemilyus

Comment (vemilyus) [reply devtools/gradle/gradle-model/src/main/java/io/quarkus/gradle/tooling/pom/PomUtils.java:25]: > I wouldn't add dependencies automatically. I would prefer failing the build with an error suggesting what should be fixed in the project.

Would you be okay with putting this behind a configuration value (disabled by default)? 

I'd like to have this feature and by putting it behind a flag it wouldn't change the default behavior and be explicit to the user. Ofc I can put it in a separate PR if you prefer.

Comment (aloubyansky) [reply devtools/gradle/gradle-model/src/main/java/io/quarkus/gradle/tooling/pom/PomUtils.java:25]: If you really like to do that, I'd separate it from the rest of the work related to fixing the issue.

**Comment by vemilyus** [comment]
@aloubyansky @gsmet Please re-review. I removed the pom.xml check, enforced the validateExtension task (to make sure the deployment modules are added to the dependencies), and clarified the documentation on the topic of deployment modules and when to add them.

File: devtools/gradle/gradle-model/src/main/java/io/quarkus/gradle/dependency/ConditionalDependenciesEnabler.java [hunk 2]
```diff
@@ -102,12 +102,6 @@ private void collectConditionalDependencies(Set<ResolvedArtifact> runtimeArtifac
                         queueConditionalDependency(extension, conditionalDep);
                     }
                 }
-
-                // If the extension doesn't have any conditions we just enable it by default
-                if (extension.getDependencyConditions().isEmpty()) {
-                    extension.setConditional(true);
-                    enableConditionalDependency(extension.getExtensionId());
-                }
```
Comment (aloubyansky) [inline devtools/gradle/gradle-model/src/main/java/io/quarkus/gradle/dependency/ConditionalDependenciesEnabler.java:110]: After all, this seems to be the only change related to dependency processing?

**Comment by aloubyansky** [comment]
@vemilyus could you please squash your commits? Thanks.

File: devtools/gradle/gradle-model/src/main/java/io/quarkus/gradle/dependency/ConditionalDependenciesEnabler.java (hunk 2 above)
Comment (vemilyus) [reply devtools/gradle/gradle-model/src/main/java/io/quarkus/gradle/dependency/ConditionalDependenciesEnabler.java:110]: Yes, a simple fix for a misunderstanding on my part.

**Comment by vemilyus** [comment]
@aloubyansky @gsmet Squashed! Thanks for the feedback and conversations. It was very enlightening!

**Comment by gsmet** [comment]
There is quite a lot of formatting noise and I would prefer to avoid it as it makes the patch a lot bigger than it actually needs to be.
Let me have a look.

**Comment by vemilyus** [comment]
> There is quite a lot of formatting noise and I would prefer to avoid it as it makes the patch a lot bigger than it actually needs to be. Let me have a look.

Removed some of it.

**Comment by gsmet** [comment]
I removed some more. We should be all good now but I will let @aloubyansky approve if all is well for him. Thanks!

**Review by aloubyansky — APPROVED** [review]
Thanks @vemilyus
