### PR TITLE
quarkus:native-image should not fail if the runner jar does not exist

### LINKED ISSUE #2908: quarkus:native-image should not fail if the runner jar does not exist
Currently, the NativeImageMojo gives up in case the runner jar (the outcome of the BuildMojo) can't be found on the disk. It would be nice to be able to simply execute `mvn quarkus:native-image` for a project.
Another enhancement I would like to add here is the ability to provide the Maven coordinates of the application I want to generate the native image for, instead of always configuring the NativeImageMojo for the current project like today.

### PR DESCRIPTION
**Pull request by aloubyansky**
Fixes #2908

### CODE REVIEW

File: devtools/maven/src/main/java/io/quarkus/maven/NativeImageMojo.java [hunk 1]
```diff
@@ -125,111 +141,249 @@
...
+            DefaultArtifact appMvnArtifact = null;
+            if (appArtifact == null) {
+                appMvnArtifact = new DefaultArtifact(project.getArtifact().getGroupId(),
+                        project.getArtifact().getArtifactId(),
+                        project.getArtifact().getClassifier(),
+                        project.getArtifact().getArtifactHandler().getExtension(),
+                        project.getArtifact().getVersion());
+                appCoords = new AppArtifact(appMvnArtifact.getGroupId(), appMvnArtifact.getArtifactId(),
+                        appMvnArtifact.getClassifier(), appMvnArtifact.getExtension(),
+                        appMvnArtifact.getVersion());
```
Comment (gsmet) [inline devtools/maven/src/main/java/io/quarkus/maven/NativeImageMojo.java]: So I see why we support the capability to point to another jar but I don't see why we need to support this case? Could you explain it to me?

Thanks!

Comment (aloubyansky) [reply devtools/maven/src/main/java/io/quarkus/maven/NativeImageMojo.java]: Sorry, I am not sure I understand your question. If the app artifact was not configured explicitly by the user, we assume the current project is the application (as it is today).
The requirement to build the native image for another project is coming from the requirement to integrate external tests into the platform.

Comment (gsmet) [reply devtools/maven/src/main/java/io/quarkus/maven/NativeImageMojo.java]: We discussed it on Zulip. @aloubyansky answered my questions.

**Review by gsmet — APPROVED** [review]
