### PR TITLE
Fix gRPC blocking context

### LINKED ISSUE #23603: gRPC service throw errors when using @Blocking and OpenTelemetry gRPC instrumentation
### Describe the bug

Calling a gRPC method with `@Blocking` annotation produces errors when enabling [io.opentelemetry.instrumentation:opentelemetry-grpc-1.6:1.10.0-alpha](https://mvnrepository.com/artifact/io.opentelemetry.instrumentation/opentelemetry-grpc-1.6/1.10.0-alpha) and io.quarkus:quarkus-opentelemetry-exporter-otlp.

It does not affect gRPC methods without `@Blocking` annotation.

### Expected behavior

no error.

### Actual behavior

The gRPC server will produce the below error:

```
2022-02-11 16:53:58,993 SEVERE [io.ope.ins.grp.v1_.int.ContextStorageBridge] (executor-thread-0) Detaching context which was not attached.: java.lang.Throwable
	at io.opentelemetry.instrumentation.grpc.v1_6.internal.ContextStorageBridge.detach(ContextStorageBridge.java:67)
	at io.grpc.override.ContextStorageOverride.detach(ContextStorageOverride.java:26)
	at io.grpc.Context.detach(Context.java:450)
	at io.quarkus.grpc.runtime.supports.blocking.BlockingExecutionHandler.handle(BlockingExecutionHandler.java:45)
	at io.quarkus.grpc.runtime.supports.blocking.BlockingExecutionHandler.handle(BlockingExecutionHandler.java:12)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

### How to Reproduce?

1. Use example `grpc-plain-text-quickstart` from `https://github.com/quarkusio/quarkus-quickstarts.git`
2. Add dependencies

```xml
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-opentelemetry-exporter-otlp</artifactId>
        </dependency>
        <dependency>
            <groupId>io.opentelemetry.instrumentation</groupId>
            <artifactId>opentelemetry-grpc-1.6</artifactId>
            <version>1.10.0-alpha</version>
        </dependency>
```

3. Add `@Blocking` annotation to `io.quarkus.grpc.examples.hello.HelloWorldService.sayHello`
4. Run test `io.quarkus.grpc.examples.hello.HelloWorldServiceTest`

### Output of `uname -a` or `ver`

21.2.0

### Output of `java -version`

openjdk version "17.0.2" 2022-01-18 OpenJDK Runtime Environment (build 17.0.2+8-86) OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.6.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.3.3

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by XSAM**
Resolves #23603

### CODE REVIEW

File: extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/blocking/BlockingExecutionHandler.java [hunk 1]
```diff
@@ -37,8 +37,7 @@ public void handle(Promise<Object> event) {
          * The lock object is assumed to be the request's listener
          */
         synchronized (lock) {
-            final Context previous = Context.current();
-            grpcContext.attach();
+            Context previous = grpcContext.attach();
```
Comment (XSAM) [inline extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/blocking/BlockingExecutionHandler.java:40]: This could fix `Detaching context which was not attached.` error, but it brings a warning `Context in storage not the expected context, Scope.close was not called correctly` from https://github.com/quarkusio/quarkus/blob/6d24576fafb2b0fec3efb16f98a7abcff6f84fe8/extensions/opentelemetry/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/QuarkusContextStorage.java#L40

I am not sure about the root cause, might need some help.

**Review by michalszynkiewicz — APPROVED** [review]

**Comment by michalszynkiewicz** [comment]
thanks @XSAM !

File: extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/blocking/BlockingExecutionHandler.java (hunk 1 above)
Comment (michalszynkiewicz) [reply extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/blocking/BlockingExecutionHandler.java:40]: oops, I might've merged prematurely. Are you sure it's this change that brings the warning you linked?

Comment (XSAM) [reply extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/blocking/BlockingExecutionHandler.java:40]: Yeah, I am pretty sure this PR brings this warning.

Comment (XSAM) [reply extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/blocking/BlockingExecutionHandler.java:40]: I am not sure what to do next. Should we revert this merged PR or fix this warning in the subsequent PR?

**Comment by michalszynkiewicz** [comment]
removed the backport label to make sure what's going on with the error @XSAM mentioned first

File: extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/blocking/BlockingExecutionHandler.java (hunk 1 above)
Comment (michalszynkiewicz) [reply extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/blocking/BlockingExecutionHandler.java:40]: I think this change is good.

Do you have a small project that reproduces the warning?

Comment (XSAM) [reply extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/blocking/BlockingExecutionHandler.java:40]: You can follow the steps from #23603 with changes in this PR.

Comment (michalszynkiewicz) [reply extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/blocking/BlockingExecutionHandler.java:40]: I'm quite busy, it would help me a lot if you could put up a ready reproducer, with a test for which the warning is printed.
If you don't have time for it, it's absolutely okay :)

Comment (XSAM) [reply extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/blocking/BlockingExecutionHandler.java:40]: OK, I could prepare a temp public repo for it.

Comment (XSAM) [reply extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/blocking/BlockingExecutionHandler.java:40]: You can use this repo https://github.com/XSAM/quarkus-issue-23603-reproducer to reproduce this warning. It uses a local Quarkus build `999-SNAPSHOT`.

Comment (michalszynkiewicz) [reply extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/blocking/BlockingExecutionHandler.java:40]: The warning is not printed without this change only because the error that you are fixing happens right before it and this iteration of closing the context is not invoked. I think it's safe to say this change didn't break anything

Comment (XSAM) [reply extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/blocking/BlockingExecutionHandler.java:40]: Thanks, @michalszynkiewicz. Is there a plan to fix this warning?

Comment (michalszynkiewicz) [reply extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/blocking/BlockingExecutionHandler.java:40]: Contributions are welcome ;)
Can you create an issue for it?

Comment (XSAM) [reply extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/blocking/BlockingExecutionHandler.java:40]: > Contributions are welcome ;)

I would love to contribute the fix, but I am new in Quarkus; this may go beyond my ability.

> Can you create an issue for it?

Sure, see #23805
