### PR TITLE
Validate the default JAXBContext at build time only if it is really u…

### LINKED ISSUE #31646: Allow third party extensions to avoid validating the default JAXB context
### Describe the bug

The change 46f348c85934b914f8d986f4f4535134e4ffba03 by @Sgitario has brought hard times to Quarkus CXF and Camel Quarkus. Basically all our CXF related tests fail, because duplicate JAXB classes seem to a normal situation in CXF. 

Here an example of the stack trace see when running [quarkus-cxf-integration-test-client](https://github.com/quarkiverse/quarkus-cxf/tree/main/integration-tests/ws-security-client): 

```
Caused by: java.lang.IllegalStateException: Failed to configure JAXB context
        at io.quarkus.jaxb.deployment.JaxbProcessor.validateContext(JaxbProcessor.java:395)
        at io.quarkus.jaxb.deployment.JaxbProcessor.setupJaxbContextConfig(JaxbProcessor.java:318)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:1589)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: org.glassfish.jaxb.runtime.v2.runtime.IllegalAnnotationsException: 1 counts of IllegalAnnotationExceptions
Two classes have the same XML type name "{http://www.w3.org/2005/08/addressing}EndpointReferenceType". Use @XmlType.name and @XmlType.namespace to assign different names to them.
        this problem is related to the following location:
                at org.apache.cxf.ws.addressing.EndpointReferenceType
                at public org.apache.cxf.ws.addressing.EndpointReferenceType org.apache.cxf.ws.addressing.ObjectFactory.createEndpointReferenceType()
                at org.apache.cxf.ws.addressing.ObjectFactory
                at protected java.util.List org.apache.cxf.ws.addressing.ReferenceParametersType.any
                at org.apache.cxf.ws.addressing.ReferenceParametersType
        this problem is related to the following location:
                at jakarta.xml.ws.wsaddressing.W3CEndpointReference

        at org.glassfish.jaxb.runtime.v2.runtime.IllegalAnnotationsException$Builder.check(IllegalAnnotationsException.java:83)
        at org.glassfish.jaxb.runtime.v2.runtime.JAXBContextImpl.getTypeInfoSet(JAXBContextImpl.java:421)
        at org.glassfish.jaxb.runtime.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:255)
        at org.glassfish.jaxb.runtime.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1115)
        at org.glassfish.jaxb.runtime.v2.ContextFactory.createContext(ContextFactory.java:144)
        at org.glassfish.jaxb.runtime.v2.JAXBContextFactory.createContext(JAXBContextFactory.java:44)
        at jakarta.xml.bind.ContextFinder.find(ContextFinder.java:368)
        at jakarta.xml.bind.JAXBContext.newInstance(JAXBContext.java:605)
        at jakarta.xml.bind.JAXBContext.newInstance(JAXBContext.java:546)
        at io.quarkus.jaxb.deployment.JaxbProcessor.validateContext(JaxbProcessor.java:393)
        ... 10 more
```

In this particular case, both conflicting classes come through transitive dependencies of CXF:

* `jakarta.xml.ws.wsaddressing.W3CEndpointReference` comes via

```
io.quarkiverse.cxf:quarkus-cxf-integration-test-client:2.0.0-SNAPSHOT:jar:
        -> io.quarkiverse.cxf:quarkus-cxf:2.0.0-SNAPSHOT:jar:
        -> org.apache.cxf:cxf-rt-frontend-jaxws:4.0.0:jar:
        -> org.apache.cxf:cxf-rt-bindings-soap:4.0.0:jar:
        -> jakarta.jws:jakarta.jws-api:3.0.0:jar
```

* `org.apache.cxf.ws.addressing.EndpointReferenceType` comes via

```
io.quarkiverse.cxf:quarkus-cxf-integration-test-client:2.0.0-SNAPSHOT:jar:
        -> io.quarkiverse.cxf:quarkus-cxf:2.0.0-SNAPSHOT:jar:
        -> org.apache.cxf:cxf-rt-frontend-jaxws:4.0.0:jar:
        -> org.apache.cxf:cxf-core:4.0.0:jar
```

I doubt we can exclude the artifacts and I doubt we can exclude the classes via `quarkus.jaxb.exclude-classes`.

Advising all users of `camel-quarkus-cxf` and `quarkus-cxf` to always have `quarkus.jaxb.validate-jaxb-context=false` in their `application.properties` does not seem to be a good UX.

I think the best way forward would be to find a programmatic way of disabling the JAXB context validation. 

I see three options:

### B. Split quarkus-jaxb into quarkus-jaxb-core and quarkus-jaxb

quarkus-jaxb would contain the config, the properties, the validation and the default context bean

quarkus-jaxb-core would keep all the rest. 

quarkus-cxf would depend only on quarkus-jaxb-core. If quarkus-cxf users need to inject the default JAXB context, they are on their own to add quarkus-jaxb dependency and resolve the conflicts.

## Assessment:

I see C as rather problematic. I think it would be hard to find the right semantics (esp. how it would combine with `quarkus.jaxb.validate-jaxb-context=false/true`), keep it transparent enough for end users and even document comprehensibly.

If A is technically possible, we should go with A. What do others think?

This blocks 
* https://github.com/apache/camel-quarkus/issues/4603
* https://github.com/quarkiverse/quarkus-cxf/issues/730

### PR DESCRIPTION
**Pull request by ppalaga**
…sed in the application; do not validate if user provides his own JAXBContext bean or if there is no JAXBContext injection point

Fix #31646

### CODE REVIEW

File: extensions/jaxb/deployment/src/main/java/io/quarkus/jaxb/deployment/JaxbProcessor.java [hunk 1]
```diff
@@ -297,29 +297,55 @@ void registerClasses(
...
+    void validateDefaultJaxbContext(
+            JaxbConfig config,
+            FilteredJaxbClassesToBeBoundBuildItem filteredClassesToBeBound,
+            SynthesisFinishedBuildItem beanContainerState,
+            BuildProducer<ValidationPhaseBuildItem.ValidationErrorBuildItem> errors) {
+
+        final BeanResolver beanResolver = beanContainerState.getBeanResolver();
+        final Set<BeanInfo> beans = beanResolver
+                .resolveBeans(Type.create(DotName.createSimple(JAXBContext.class), org.jboss.jandex.Type.Kind.CLASS));
+        if (config.validateJaxbContext && !beans.isEmpty()) {
```
Comment (Sgitario) [inline extensions/jaxb/deployment/src/main/java/io/quarkus/jaxb/deployment/JaxbProcessor.java:334]: I don't know what is the performance penalty of calling `beanResolver.resolveBeans`, but we should only discover the beans if `validateJaxbContext` is true.

File: extensions/jaxb/deployment/src/main/java/io/quarkus/jaxb/deployment/JaxbProcessor.java [hunk 2]
```diff
@@ -297,29 +297,55 @@ void registerClasses(
...
+    @BuildStep
+    void validateDefaultJaxbContext(
+            JaxbConfig config,
+            FilteredJaxbClassesToBeBoundBuildItem filteredClassesToBeBound,
+            SynthesisFinishedBuildItem beanContainerState,
+            BuildProducer<ValidationPhaseBuildItem.ValidationErrorBuildItem> errors) {
+
+        final BeanResolver beanResolver = beanContainerState.getBeanResolver();
+        final Set<BeanInfo> beans = beanResolver
+                .resolveBeans(Type.create(DotName.createSimple(JAXBContext.class), org.jboss.jandex.Type.Kind.CLASS));
```
Comment (Sgitario) [inline extensions/jaxb/deployment/src/main/java/io/quarkus/jaxb/deployment/JaxbProcessor.java:333]: Missing the Marshaller and Unmarshaller types too.

File: extensions/jaxb/deployment/src/main/java/io/quarkus/jaxb/deployment/JaxbProcessor.java [hunk 3]
```diff
@@ -297,29 +297,55 @@ void registerClasses(
...
+            final BeanInfo bean = beanResolver.resolveAmbiguity(beans);
+            if (bean.isDefaultBean()) {
+                /*
+                 * Validate the default JAXB context at build time and fail early.
+                 * Do this only if the user application actually requires the default JAXBContext bean
+                 */
+                try {
+                    JAXBContext.newInstance(filteredClassesToBeBound.getClasses().toArray(new Class[0]));
+                } catch (JAXBException e) {
+                    throw new IllegalStateException("Failed to configure JAXB context", e);
```
Comment (Sgitario) [inline extensions/jaxb/deployment/src/main/java/io/quarkus/jaxb/deployment/JaxbProcessor.java:344]: Produce a ValidationErrorBuildItem build item instead of throwing this exception.

**Review by Sgitario — CHANGES_REQUESTED** [review]
Apart from the comments, these changes cause a build cycle exception in the RESTEasy Reactive Jaxb tests.

File: extensions/jaxb/deployment/src/main/java/io/quarkus/jaxb/deployment/JaxbProcessor.java (hunk 1 above)
Comment (ppalaga) [reply extensions/jaxb/deployment/src/main/java/io/quarkus/jaxb/deployment/JaxbProcessor.java:334]: +1, let me reorder the conditions

File: extensions/jaxb/deployment/src/main/java/io/quarkus/jaxb/deployment/JaxbProcessor.java (hunk 2 above)
Comment (ppalaga) [reply extensions/jaxb/deployment/src/main/java/io/quarkus/jaxb/deployment/JaxbProcessor.java:333]: Marshaller and Unmarshaller require the JAXBContext bean to exist, so checking their existence is not necessary IMO.  Let me add a test to prove that.

File: extensions/jaxb/deployment/src/main/java/io/quarkus/jaxb/deployment/JaxbProcessor.java (hunk 3 above)
Comment (ppalaga) [reply extensions/jaxb/deployment/src/main/java/io/quarkus/jaxb/deployment/JaxbProcessor.java:344]: Good idea, let me do that. 
I just copied the old code without too much thinking about it. I had to add the ValidationErrorBuildItem consumer to the method signature to force the build time container to invoke the method.

**Comment by ppalaga** [comment]
5e39264: 

* Addressed the feedback by @Sgitario (thanks!)
* Solved the BuildStep methods cycle by not producing a ValidationErrorBuildItem and rather throwing a DeploymentException direcly plus consuming a JaxbContextConfigRecorder to force the container to call validateDefaultJaxbContext().

@Sgitario please feel free to re-review

File: extensions/jaxb/deployment/src/main/java/io/quarkus/jaxb/deployment/JaxbProcessor.java (hunk 2 above)
Comment (ppalaga) [reply extensions/jaxb/deployment/src/main/java/io/quarkus/jaxb/deployment/JaxbProcessor.java]: There is now ConflictingModelClassesMarshalerOnlyTest to cover the situation where there conflicting classes, no JAXBContext injection point, but there is a Marshaller injection point. The application fails on boot as expected.

File: extensions/jaxb/deployment/src/main/java/io/quarkus/jaxb/deployment/JaxbProcessor.java (hunk 3 above)
Comment (ppalaga) [reply extensions/jaxb/deployment/src/main/java/io/quarkus/jaxb/deployment/JaxbProcessor.java]: I had to remove the ValidationErrorBuildItem producer from the method signature because of the dependency cycle in resteasy-reactive-jaxb. Now the DeploymentException is thrown directly from validateDefaultJaxbContext() much like it was before this change.

Comment (Sgitario) [reply extensions/jaxb/deployment/src/main/java/io/quarkus/jaxb/deployment/JaxbProcessor.java]: ok ok!

**Review by Sgitario — APPROVED** [review]
lgtm! thanks @ppalaga !

btw, I still think https://github.com/quarkusio/quarkus/pull/31651 is something we could incorporate. Let me know if you want to add this change as part of your pull request or I should add it after yours is merged.

**Comment by ppalaga** [comment]
> I still think https://github.com/quarkusio/quarkus/pull/31651 is something we could incorporate.

On one hand, it looks like a nice general improvement. 
OTOH, I wonder how transparent can we make it for the users to understand that in spite they have a dependency bringing org.acme.Foo class, that class might still not be available in the default JAXBContext because some extension "Bar" that the user also happens to have in his classpath chose to exclude org.acme.Foo? However well we document that behavior in extension "Bar", it can still be very surprising to the users. 

Having a catch-all default JAXBContext is definitely intuitive and user friendly, but it is very hard to say who should be responsible for solving the namespace conflicts. I do not feel like it should (always) be extension devs, because they might not know what the users want. Maybe sometimes the choice is clear, e.g. when one half of the conflicting classes is deprecated or outdated. Maybe in such situations `ExcludeJaxbClassesToBeBoundBuildItem` would be useful.
