### PR TITLE
Don't ignore Spring Rest controllers interfaces if contains errors

### LINKED ISSUE #43704: Spring controller silently ignored if mapping is defined in interface and if there's an error in it
### Describe the bug

This is probably related to the Spring extension. The symptom is that Quarkus build succeeds when it should've failed when an interface defining a controller contains errors.

This issue makes it pretty tricky to migrate Spring applications as the generated artifact just silently doesn't include endpoints defined in such controller interfaces.

### Expected behavior

Build should fail, printing the error causing building a controller interface to fail.

### Actual behavior

Quarkus builds successfully without printing anything about errors when building the interface. The resulting artifact doesn't contain the endpoints defined in the controller interface either.

### How to Reproduce?

As an exemple, say we have an interface:

```
@RestController
@RequestMapping("/greeting")
public interface GreetingInterface {
    @GetMapping("/ping")
    String ping();

    @PostMapping("/hello")
    String hello(@RequestParam(required = false) @QueryParam("dung") String params);
}
```

and a controller class implementing the above interface

```
@Component
public class GreetingController implements GreetingInterface {

    @Override
    public String ping() {
        return "pinged";
    }

    @Override
    public String hello(String params) {
        return params.toString();
    }
}
```

building this code *is supposed to* fail with error `Cannot have more than one of @PathParam, @QueryParam, @HeaderParam, @FormParam, @CookieParam, @BeanParam, @Context on method java.lang.String hello(java.lang.String params)`

but in reality it can build successfully, and the resulting artifact doesn't include both APIs

```
$ ./mvnw quarkus:dev
...

$ curl -X GET http://localhost:8080/greeting/ping

404 - Resource Not Found
------------------------

Additional endpoints
	- /q/arc
		- CDI Overview
	- /q/arc/beans
		- Active CDI Beans
	- /q/arc/observers
		- Active CDI Observers
	- /q/arc/removed-beans
		- Removed CDI Beans
	- /q/dev-ui
		- Dev UI
```

### Output of `uname -a` or `ver`

Linux 5.10.225

### Output of `java -version`

openjdk version "17.0.9" 2023-10-17 OpenJDK Runtime Environment GraalVM CE 17.0.9+9.1 (build 17.0.9+9-jvmci-23.0-b22) OpenJDK 64-Bit Server VM GraalVM CE 17.0.9+9.1 (build 17.0.9+9-jvmci-23.0-b22, mixed mode, sharing)

### Quarkus version or git rev

3.15.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.8 (36645f6c9b5079805ea5009217e36f2cffd34256)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by aureamunoz**
Fixes: #43704

### CODE REVIEW

**Comment by aureamunoz** [comment]
cc @geoand @cescoffier

File: independent-projects/resteasy-reactive/common/processor/src/main/java/org/jboss/resteasy/reactive/common/processor/EndpointIndexer.java [hunk 1]
```diff
@@ -324,16 +324,22 @@ public Optional<ResourceClass> createEndpoints(ClassInfo classInfo, boolean cons
...
+                    log.debug("Ignoring interface " + classInfo.name(), e);
+                    return Optional.empty();
+                }
             }
             throw new RuntimeException(e);
         }
     }
 
+    private boolean isSpringRestController(ClassInfo classInfo) {
+        return classInfo.declaredAnnotation("org.springframework.web.bind.annotation.RestController") != null;
```
Comment (cescoffier) [inline independent-projects/resteasy-reactive/common/processor/src/main/java/org/jboss/resteasy/reactive/common/processor/EndpointIndexer.java:340]: It might be better to use a DotName instead of a String.

File: independent-projects/resteasy-reactive/common/processor/src/main/java/org/jboss/resteasy/reactive/common/processor/EndpointIndexer.java [hunk 2]
```diff
@@ -1039,7 +1045,7 @@ private static String methodDescriptor(MethodInfo info) {
         return info.name() + ":" + info.descriptor();
     }
 
-    private static boolean moreThanOne(AnnotationInstance... annotations) {
+    public static boolean moreThanOne(AnnotationInstance... annotations) {
```
Comment (cescoffier) [inline independent-projects/resteasy-reactive/common/processor/src/main/java/org/jboss/resteasy/reactive/common/processor/EndpointIndexer.java:1048]: I didn't see where this method was used.

**Review by cescoffier — CHANGES_REQUESTED** [review]

**Comment by cescoffier** [comment]
@aureamunoz seems you forgot to run the formatter. A ‘quickly’ build should fix it.

**Comment by geoand** [comment]
The error message also gives the exact to command to run :)

**Comment by aureamunoz** [comment]
Yes, I know, but it's trickier than that. Even after formatting, Git doesn't detect changes locally, and the same error is raised. I'm trying to solve it

File: independent-projects/resteasy-reactive/common/processor/src/main/java/org/jboss/resteasy/reactive/common/processor/EndpointIndexer.java [hunk 3]
```diff
@@ -324,16 +324,23 @@ public Optional<ResourceClass> createEndpoints(ClassInfo classInfo, boolean cons
...
             }
             throw new RuntimeException(e);
         }
     }
 
+    private boolean isSpringRestController(ClassInfo classInfo) {
+        return classInfo
+                .declaredAnnotation(DotName.createSimple("org.springframework.web.bind.annotation.RestController")) != null;
+    }
+
```
Comment (geoand) [inline independent-projects/resteasy-reactive/common/processor/src/main/java/org/jboss/resteasy/reactive/common/processor/EndpointIndexer.java:343]: I don't really want to add any Spring relate stuff to the core modules of RESTEasy Reactive, so I suggest introducing some sort of SPI for this

Comment (cescoffier) [reply independent-projects/resteasy-reactive/common/processor/src/main/java/org/jboss/resteasy/reactive/common/processor/EndpointIndexer.java:343]: Ah yes, makes sense. 
We would need to add a build item to pass "predicates".

**Comment by cescoffier** [comment]
@aureamunoz:
In resteasy reactive common, you need to add a new BuildItem class accepting a `Predicate<ClassInfo>`. In the resteasy reactive processor, you add a parameter: `List<YourBuildItem>` and iterate over that list to ensure the odd annotated class is not "accepted."

In the spring web extension processor, you produce an instance of this build item with the predicate:

```java
classInfo -> classInfo
                .declaredAnnotation(DotName.createSimple("org.springframework.web.bind.annotation.RestController")) != null;
```

@geoand : Should we add a deployment-spi module instead of adding the build item to the resteasy reactive common deployment module? It will be more "future-proof).

**Review by cescoffier — CHANGES_REQUESTED** [review]
See comment.

**Comment by geoand** [comment]
We can't have BuildItems themselves in the independent project. The builder of EndpointIndexer can accept a predicate like you mention and the extension can use build items to pass that information to the builder.

**Comment by cescoffier** [comment]
Ah ok, so it's slightly more complicated, we need another hop:

- Build Items in the extension
- Pass the list of predicated to the "common" component

**Comment by geoand** [comment]
Yeah exactlyu

**Comment by aureamunoz** [comment]
Perhaps there’s something I’m not fully understanding, but I don’t see the need to go through a BuildItem.

As you can see in the last commit, I’ve created an interface in RESTEasy so that any annotation (not just those from Spring) can be detected and handled similarly. I’ve moved the specific validation logic to its respective implementations. Then, using ServiceLoader as a discovery mechanism, the validation is delegated to the EndpointIndexer, as is done so far.

Please refer to my latest commit for more details and feedback.

File: bom/application/pom.xml [hunk 4]
```diff
@@ -3780,6 +3780,11 @@
                 <artifactId>quarkus-resteasy-common-spi</artifactId>
                 <version>${project.version}</version>
             </dependency>
+            <dependency>
+                <groupId>io.quarkus</groupId>
+                <artifactId>quarksu-resteasy-common-deployment-spi</artifactId>
```
Comment (cescoffier) [inline bom/application/pom.xml:3785]:
```suggestion
                <artifactId>quarkus-resteasy-common-deployment-spi</artifactId>
```

File: extensions/resteasy-common/deployment-spi/pom.xml [hunk 5]
```diff
@@ -0,0 +1,27 @@
...
+         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
+    <modelVersion>4.0.0</modelVersion>
+
+    <parent>
+        <groupId>io.quarkus</groupId>
+        <artifactId>quarkus-resteasy-common-spi-parent</artifactId>
+        <version>999-SNAPSHOT</version>
+    </parent>
+
+    <artifactId>quarksu-resteasy-common-deployment-spi</artifactId>
```
Comment (cescoffier) [inline extensions/resteasy-common/deployment-spi/pom.xml:13]:
```suggestion
    <artifactId>quarkus-resteasy-common-deployment-spi</artifactId>
```

File: extensions/resteasy-common/deployment-spi/src/main/java/io/quarkus/resteasy/common/deployment/EndpointValidationPredicatesBuildItem.java [hunk 6]
```diff
@@ -0,0 +1,20 @@
+package io.quarkus.resteasy.common.deployment;
+
+import java.util.function.Predicate;
+
+import org.jboss.jandex.ClassInfo;
+
+import io.quarkus.builder.item.MultiBuildItem;
+
+public final class EndpointValidationPredicatesBuildItem extends MultiBuildItem {
```
Comment (cescoffier) [inline extensions/resteasy-common/deployment-spi/src/main/java/io/quarkus/resteasy/common/deployment/EndpointValidationPredicatesBuildItem.java:9]: Can you add some Javadoc to indicate what it is?

Build items added to spi modules are considered public API.

File: extensions/resteasy-common/pom.xml [hunk 7]
```diff
@@ -0,0 +1,20 @@
...
+    <parent>
+        <artifactId>quarkus-extensions-parent</artifactId>
+        <groupId>io.quarkus</groupId>
+        <version>999-SNAPSHOT</version>
+        <relativePath>../pom.xml</relativePath>
+    </parent>
+    <modelVersion>4.0.0</modelVersion>
+
+    <artifactId>quarkus-resteasy-common-spi-parent</artifactId>
+    <name>Quarkus - JMS SPI - Parent</name>
```
Comment (cescoffier) [inline extensions/resteasy-common/pom.xml:14]:
```suggestion
    <name>Quarkus - RESTEasy Common SPI - Parent</name>
```

Comment (cescoffier) [reply extensions/resteasy-common/pom.xml:14]: I would also add a description indicating that this module is intended to be shared between resteasy classic and quarkus rest (aka Resateasy reactive)

File: extensions/resteasy-reactive/rest-client-jaxrs/deployment/pom.xml [hunk 8]
```diff
@@ -33,6 +33,10 @@
             <groupId>io.quarkus</groupId>
             <artifactId>quarkus-rest-spi-deployment</artifactId>
         </dependency>
+        <dependency>
+            <groupId>io.quarkus</groupId>
+            <artifactId>quarksu-resteasy-common-deployment-spi</artifactId>
```
Comment (cescoffier) [inline extensions/resteasy-reactive/rest-client-jaxrs/deployment/pom.xml:38]:
```suggestion
            <artifactId>quarkus-resteasy-common-deployment-spi</artifactId>
```

File: extensions/resteasy-reactive/rest/deployment/pom.xml [hunk 9]
```diff
@@ -46,6 +46,10 @@
             <groupId>io.quarkus</groupId>
             <artifactId>quarkus-security-spi</artifactId>
         </dependency>
+        <dependency>
+            <groupId>io.quarkus</groupId>
+            <artifactId>quarksu-resteasy-common-deployment-spi</artifactId>
```
Comment (cescoffier) [inline extensions/resteasy-reactive/rest/deployment/pom.xml:51]:
```suggestion
            <artifactId>quarkus-resteasy-common-deployment-spi</artifactId>
```

File: extensions/spring-web/core/deployment/pom.xml [hunk 10]
```diff
@@ -44,6 +44,10 @@
             <groupId>io.quarkus</groupId>
             <artifactId>quarkus-resteasy-common-spi</artifactId>
         </dependency>
+        <dependency>
+            <groupId>io.quarkus</groupId>
+            <artifactId>quarksu-resteasy-common-deployment-spi</artifactId>
```
Comment (cescoffier) [inline extensions/spring-web/core/deployment/pom.xml:49]:
```suggestion
            <artifactId>quarkus-resteasy-common-deployment-spi</artifactId>
```

**Review by cescoffier — CHANGES_REQUESTED** [review]
There is a typo in the module name :-)

File: extensions/resteasy-common/pom.xml [hunk 11]
```diff
@@ -0,0 +1,21 @@
...
+        <artifactId>quarkus-extensions-parent</artifactId>
+        <groupId>io.quarkus</groupId>
+        <version>999-SNAPSHOT</version>
+        <relativePath>../pom.xml</relativePath>
+    </parent>
+    <modelVersion>4.0.0</modelVersion>
+
+    <artifactId>quarkus-resteasy-common-spi-parent</artifactId>
+    <name>Quarkus - RESTEasy Common SPI - Parent</name>
+    <description>This module provides reusable abstraction for use with both RESTEasy Classic and Quarkus REST (formerly RESTEasy Reactive)</description>
```
Comment (geoand) [inline extensions/resteasy-common/pom.xml:15]: To be honest, I would like to avoid such modules. It's better if there is no coupling whatsoever and we just duplicate whatever we need.

Comment (aureamunoz) [reply extensions/resteasy-common/pom.xml:15]: Hi, I've been looking at this but the issue with duplicating is that the Spring Web extension includes a common core module for both classic and reactive modes, which is responsible for creating the predicate. If we duplicate, it will lead to an error because Quarkus REST and RESTEasy Classic cannot be mixed. For this reason, I don’t see how this approach could work effectively.

Comment (aureamunoz) [reply extensions/resteasy-common/pom.xml:15]: It can publish, the problem is when consuming. For instance, the tests include both dependencies in the classpath, which is not supported.

Comment (geoand) [reply extensions/resteasy-common/pom.xml:15]: I'll have to actually run that because I fail to see the problem

Comment (geoand) [reply extensions/resteasy-common/pom.xml:15]: Thanks I'll check

Comment (geoand) [reply extensions/resteasy-common/pom.xml:15]: This is likely caused by https://github.com/aureamunoz/quarkus/blob/88c7b352ebf9dccbd5e573fa9e33478c005681ae/extensions/spring-web/core/deployment/pom.xml#L49. 

`quarkus-spring-web-deployment` should only depend on SPI modules from RESTEasy Classic and Reactive

Comment (aureamunoz) [reply extensions/resteasy-common/pom.xml]: Ok, you're right. I managed to put the class in the right place, yes. Thanks. Once you review and validate it I will squash the commits

**Review by geoand — APPROVED** [review]
LGTM!

File: extensions/resteasy-common/pom.xml (hunk 11 above)
Comment (geoand) [reply extensions/resteasy-common/pom.xml]: Please go ahead and squash the commits

**Review by cescoffier — APPROVED** [review]
Awesome! Thanks @aureamunoz
