### PR TITLE
Properly determine classpath locations in Flyway

### LINKED ISSUE #10041: Flyway migrations of defined locations are not applied anymore
**Describe the bug**
I want to use different database migrations with flyway for testing.
I defined two different locations for the flyway migrations in the `application.properties`:
```yml
%test.quarkus.flyway.locations=classpath:/db/migration/,classpath:/db/testing/
```
**Expected behavior**
I expect that all migrations in the folders `migration` and `testing` are applied

**Actual behavior**
Only the migrations in the `migration` folder are applied, anything in `testing` is ignored.

**To Reproduce**
1. Use `quarkus-flyway` version newer than 1.4.2
2. Define non-default location for flway migrations (`quarkus.flyway.locations`)
3. Start application, only migrations in default path are applied

**Configuration**
```properties
quarkus.datasource.driver=org.postgresql.Driver
quarkus.datasource.username = ${POSTGRES_USER:postgres}
quarkus.datasource.password = ${POSTGRES_PASSWORD:postgres}
quarkus.datasource.url = ${POSTGRES_URL:jdbc:postgresql://localhost:5432/postgres}
quarkus.flyway.migrate-at-start=true
quarkus.swagger-ui.always-include=true

%test.quarkus.http.test-port=0
%test.quarkus.datasource.driver=org.testcontainers.jdbc.ContainerDatabaseDriver
%test.quarkus.hibernate-orm.dialect=org.hibernate.dialect.PostgreSQL9Dialect
%test.quarkus.datasource.url=jdbc:tc:postgresql:latest:///postgres
%test.quarkus.flyway.migrate-at-start=true
%test.quarkus.flyway.clean-at-start=true
%test.quarkus.flyway.locations=classpath:/db/migration/,classpath:/db/testing/

```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
Darwin Henriks-MBP-3.fritz.box 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64
 - Output of `java -version`: 
openjdk version "13.0.1" 2019-10-15
OpenJDK Runtime Environment (build 13.0.1+9)
OpenJDK 64-Bit Server VM (build 13.0.1+9, mixed mode, sharing)
 - GraalVM version (if different from Java): -
 - Quarkus version or git rev: 1.5.2
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
Maven home: /usr/local/Cellar/maven/3.6.3_1/libexec
Java version: 13.0.2, vendor: N/A, runtime: /usr/local/Cellar/openjdk/13.0.2+8_2/libexec/openjdk.jdk/Contents/Home
Default locale: en_DE, platform encoding: US-ASCII
OS name: "mac os x", version: "10.15.5", arch: "x86_64", family: "mac"

**Additional context**
This is working in version `1.4.2.Final` of `quarkus-flyway` but not with the newer ones.

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #10041

### CODE REVIEW

File: extensions/flyway/deployment/src/main/java/io/quarkus/flyway/FlywayProcessor.java [hunk 1]
```diff
@@ -192,13 +192,16 @@ ServiceStartBuildItem createBeansAndStartActions(FlywayRecorder recorder,
 
     private List<String> discoverApplicationMigrations(Collection<String> locations) throws IOException, URISyntaxException {
         try {
-            List<String> applicationMigrationResources = new ArrayList<>();
+            LinkedHashSet<String> applicationMigrationResources = new LinkedHashSet<>();
```
Comment (geoand) [inline extensions/flyway/deployment/src/main/java/io/quarkus/flyway/FlywayProcessor.java:195]: Done because you can end up with multiple copies of the same file

File: extensions/flyway/deployment/src/main/java/io/quarkus/flyway/FlywayProcessor.java [hunk 2]
```diff
@@ -223,7 +226,7 @@ ServiceStartBuildItem createBeansAndStartActions(FlywayRecorder recorder,
                     }
                 }
             }
-            return applicationMigrationResources;
+            return new ArrayList<>(applicationMigrationResources);
```
Comment (gastaldi) [inline extensions/flyway/deployment/src/main/java/io/quarkus/flyway/FlywayProcessor.java:229]: Change the return type of this method to `Collection<String>` and you don't need to wrap the `LinkedHashSet` into another collection

Comment (geoand) [reply extensions/flyway/deployment/src/main/java/io/quarkus/flyway/FlywayProcessor.java:229]: Sure, but then I need to change all the rest as well. I don't think it's worth it TBH

Comment (gastaldi) [reply extensions/flyway/deployment/src/main/java/io/quarkus/flyway/FlywayProcessor.java:229]: Well, if you look what calls it you'll see it's already expecting `Collection<String>` so it's not a huge change

Comment (geoand) [reply extensions/flyway/deployment/src/main/java/io/quarkus/flyway/FlywayProcessor.java:229]: I'll give it another look, but I thought it was List everywhere.

Comment (geoand) [reply extensions/flyway/deployment/src/main/java/io/quarkus/flyway/FlywayProcessor.java]: Fixed

**Review by gastaldi — APPROVED** [review]
Divine! :ok_hand:

**Comment by geoand** [comment]
> Divine! ok_hand

Thanks for suggesting the improvement!
