### PR TITLE
Use proper metrics path in Kubernetes annotation

### LINKED ISSUE #15118: /metrics uri in generated kubernetes.yml is wrong
**Describe the bug**
Quarkus (currently) prefixes all technical (non-application uri's) by /q. In kubernetes.yml this works perfect for liveness and readyness url's, but /metrics is added as is

prometheus.io/path: /metrics

**Expected behavior**
The created path should be
prometheus.io/path: /q/metrics
(or instead of /q the configured non-application-root-path).

**Actual behavior**
(Describe the actual behavior clearly and concisely.)

**To Reproduce**

Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific).

Or attach an archive containing the reproducer to the issue.

1. add metrics and kubernetes extensions to the project
2. let kubernetes.yml get generated
3. 

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: 
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 

**Additional context**
(Add any other context about the problem here.)

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #15118

### CODE REVIEW

File: integration-tests/kubernetes/quarkus-standard-way/src/test/java/io/quarkus/it/kubernetes/KubernetesWithMetricsTest.java [hunk 1]
```diff
@@ -73,7 +73,7 @@ public void assertGeneratedResources() throws IOException {
                 assertThat(deploymentSpec.getTemplate()).satisfies(t -> {
                     assertThat(t.getMetadata()).satisfies(meta -> {
                         assertThat(meta.getAnnotations()).contains(entry("prometheus.io/scrape", "true"),
-                                entry("prometheus.io/path", "/met"), entry("prometheus.io/port", "9090"),
+                                entry("prometheus.io/path", "/q/metrics"), entry("prometheus.io/port", "9090"),
```
Comment (geoand) [inline integration-tests/kubernetes/quarkus-standard-way/src/test/java/io/quarkus/it/kubernetes/KubernetesWithMetricsTest.java:76]: It changed from `met` to the default of `metrics` here because I removed `quarkus.smallrye-metrics.path` for this test as I also wanted to have a test that used the default path

**Review by kenfinnigan — APPROVED** [review]

**Comment by gsmet** [comment]
This failure looks very weird:
```
Error:  Failures: 
Error:    SseTestCase.testSseFromMulti:46->testSse:71 expected: java.util.Arrays$ArrayList@71ef0890<[hello, stef]> but was: java.util.ArrayList@27a9d59<[hello, stef]>
```
The content looks identical and the `equals` from `List` are supposed to compare the elements so I wonder what's wrong.

**Comment by geoand** [comment]
> This failure looks very weird:
> 
> ```
> Error:  Failures: 
> Error:    SseTestCase.testSseFromMulti:46->testSse:71 expected: java.util.Arrays$ArrayList@71ef0890<[hello, stef]> but was: java.util.ArrayList@27a9d59<[hello, stef]>
> ```
> 
> The content looks identical and the `equals` from `List` are supposed to compare the elements so I wonder what's wrong.

I'll take a quick look at it tomorrow

**Comment by geoand** [comment]
> This failure looks very weird:
> 
> ```
> Error:  Failures: 
> Error:    SseTestCase.testSseFromMulti:46->testSse:71 expected: java.util.Arrays$ArrayList@71ef0890<[hello, stef]> but was: java.util.ArrayList@27a9d59<[hello, stef]>
> ```
> 
> The content looks identical and the `equals` from `List` are supposed to compare the elements so I wonder what's wrong.

I opened https://github.com/quarkusio/quarkus/pull/15119 which should fix the issue, but even if it doesn't, it at least will provide better error messages
