### PR TITLE
ClosedFileSystemException or NullPointerException thrown when SharedArchivePathTree is opened and closed concurrently

### LINKED ISSUE #48220: `ClosedFileSystemException` or `NullPointerException` thrown when `SharedArchivePathTree` is opened and closed concurrently
This was originally reported as https://github.com/quarkiverse/quarkus-cxf/issues/1803

When a `SharedArchivePathTree` is opened and closed concurrently then in some cases some the following exceptions is thrown:

```
Caused by: java.lang.NullPointerException: Cannot invoke "io.quarkus.paths.SharedArchivePathTree$SharedOpenArchivePathTree.writeLock()" because "this.delegate" is null
        at io.quarkus.paths.SharedArchivePathTree$CallerOpenPathTree.close(SharedArchivePathTree.java:217)
        at io.quarkus.paths.SharedArchivePathTreeTest.lambda$stress$2(SharedArchivePathTreeTest.java:48)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

```
Caused by: java.nio.file.ClosedFileSystemException
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.ensureOpen(ZipFileSystem.java:1635)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.newByteChannel(ZipFileSystem.java:971)
        at jdk.zipfs/jdk.nio.zipfs.ZipPath.newByteChannel(ZipPath.java:870)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newByteChannel(ZipFileSystemProvider.java:247)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:380)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:432)
        at java.base/java.nio.file.Files.readAllBytes(Files.java:3281)
        at io.quarkus.paths.SharedArchivePathTreeTest.lambda$stress$2(SharedArchivePathTreeTest.java:47)
```

A PR with a reproducer follows.

### PR DESCRIPTION
**Pull request by ppalaga**
- Fixes: #48220

### CODE REVIEW

**Comment by ppalaga** [comment]
cc @holly-cummins @aloubyansky

**Review by aloubyansky — APPROVED** [review]
Thanks a lot @ppalaga

**Comment by ppalaga** [comment]
@geoand did you do anything else than rebase? I wanted to have a closer look at the failed tests today.

**Comment by geoand** [comment]
Only rebase onto `main`

**Comment by aloubyansky** [comment]
I'm gonna re-run it again.

File: independent-projects/bootstrap/app-model/src/main/java/io/quarkus/paths/SharedArchivePathTree.java [hunk 1]
```diff
@@ -60,11 +60,11 @@ public OpenPathTree open() {
             }
         }
         try {
-            this.lastOpen = new SharedOpenArchivePathTree(openFs());
+            lastOpen = this.lastOpen = new SharedOpenArchivePathTree(openFs());
```
Comment (ppalaga) [inline independent-projects/bootstrap/app-model/src/main/java/io/quarkus/paths/SharedArchivePathTree.java:63]: I am still not 100% sure what the intention behind the split into `SharedArchivePathTree`, `SharedOpenArchivePathTree` and `CallerOpenPathTree` is. A sentence of JavaDoc on each of those classes would help. 

My hypothesis is that the author wanted to allow multiple instances of `SharedOpenArchivePathTree` per `SharedArchivePathTree` where:

* The one stored in `lastOpen` is the preferred and longer living one
* All others are closed immediately when they are disposed via `close()`.
* Calling `openFs()` multiple times on a single file (per `new SharedOpenArchivePathTree(openFs())`) does not make the underlying `ZipFilesystemProvider` throw a `FileSystemAlreadyExistsException`, because perhaps the `SharedArchivePathTree.CACHE` somehow prevents it? Or what else is expected to happen in such situation?

When I saw `SharedArchivePathTree.lastOpen` writes and reads being protected by `OpenArchivePathTree.lock` in `SharedOpenArchivePathTree`, I thought it was a mistake not to protect also writing to `lastOpen` in `SharedArchivePathTree.open()`: 

```java
        try {
            lastOpen = this.lastOpen = new SharedOpenArchivePathTree(openFs());
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
```

But then, I figured out that the reads/writes from `SharedOpenArchivePathTree` are protected by per `SharedOpenArchivePathTree` lock anyway, so multiple instances of `SharedOpenArchivePathTree` can still race on accessing it. So perhaps it was not really intended not to protect `SharedArchivePathTree.lastOpen` by those locks at all but rather, those concurrent reads/writes to `SharedArchivePathTree.lastOpen` are by design and not considered harmful. Could please anybody confirm that? Git blame shows @aloubyansky as an author but hard to say if he wrote it originally.

Comment (aloubyansky) [reply independent-projects/bootstrap/app-model/src/main/java/io/quarkus/paths/SharedArchivePathTree.java:63]: `SharedArchivePathTree` has a bit of a Javadoc explaining the idea behind it.
`SharedOpenArchivePathTree` is the `OpenArchivePathTree` impl of it.
`CallerOpenPathTree` is basically shielding the `SharedOpenArchivePathTree` from the same caller calling `close()` multiple times on it and so from decrementing the user counter.

You're right about `lastOpen` not being well protected though. I'll have another look into it.

Comment (ppalaga) [reply independent-projects/bootstrap/app-model/src/main/java/io/quarkus/paths/SharedArchivePathTree.java:63]: > `SharedArchivePathTree` has a bit of a Javadoc explaining the idea behind it.

I was very thankful to see it :)

> `SharedOpenArchivePathTree` is the `OpenArchivePathTree` impl of it.
> `CallerOpenPathTree` is basically shielding the `SharedOpenArchivePathTree` from the same caller calling `close()` multiple times on it and so from decrementing the user counter.

Do we really need both Open* and Caller* flavors (and all abstraction layers above)? 
Does OpenPathTree have to inherit from PathTree? 
All those inheritance, inner-class and delegation links make it really hard to understand what is going on.

Comment (aloubyansky) [reply independent-projects/bootstrap/app-model/src/main/java/io/quarkus/paths/SharedArchivePathTree.java:63]: > Does OpenPathTree have to inherit from PathTree?

Yeah, OpenPathTree is something that needs to be closed but it otherwise a PathTree.

The whole complication is around caching and concurrent access to the same open archive.

Unfortunately, the test rarely fails for me w/o the fix.

**Comment by gsmet** [comment]
@aloubyansky do we merge this one or do you want to have another look before we merge?

**Comment by aloubyansky** [comment]
I'd merge it and also have another look. I have a few things to look into, so I wouldn't delay it since it appears to fix an issue. I didn't expect the CI failures though. They might be unrelated but I don't think we had a clean CI for this PR.

**Comment by aloubyansky** [comment]
I also struggled to make the included test fail w/o the fix. But it's kinda expected for it to be tricky to fail consistently.
