### PR TITLE
Properly implement redirection in REST Client for 307 responses

### LINKED ISSUE #34644: Rest client running GET requests instead of POST after redirect
### Describe the bug

I am using a Rest client to run POST requests on an endpoint that redirects to another POST endpoint.

[Quarkus v3 introduced a way to register a custom redirect handler|https://quarkus.io/guides/rest-client-reactive#redirection] that works fine.
The problem is that the request done after the redirect is GET and not the origin request type (POST in my case). So all my calls end with HTTP 405 "Method not allowed".

### Expected behavior

The expected behavior is to run a POST request after the redirect.

- POST /token
- HTTP 307 - /token/2
- **POST** /token/2
- HTTP 200

This is what the access logs should look when using cURL to run the request

```
curl --location 'http://localhost:8080/token' \
    --header 'Content-Type: application/json' \
    --data '{"value": "test"}' \
    -v
```

```
2023-07-10 11:33:42,831 INFO  [io.qua.htt.access-log] (vert.x-eventloop-thread-1) 127.0.0.1 - - 10/Jul/2023:11:33:42 +0200 "POST /token HTTP/1.1" 307 -
2023-07-10 11:33:42,847 INFO  [io.qua.htt.access-log] (vert.x-eventloop-thread-1) 127.0.0.1 - - 10/Jul/2023:11:33:42 +0200 "POST /token/2 HTTP/1.1" 200 70
```

### Actual behavior

The actual behavior i buggy, it runs a GET request instead of POST.

- POST /token
- HTTP 307 - /token/2
- **GET** /token/2
- HTTP 405

This is what the access logs should look when using cURL to run the request

```
curl --location 'http://localhost:8080/token' \
    --header 'Content-Type: application/json' \
    --data '{"value": "test"}' \
    -v
```

```
2023-07-10 11:32:27,476 INFO  [io.qua.htt.access-log] (vert.x-eventloop-thread-1) 127.0.0.1 - - 10/Jul/2023:11:32:27 +0200 "POST /token HTTP/1.1" 307 -
2023-07-10 11:32:27,487 INFO  [io.qua.htt.access-log] (vert.x-eventloop-thread-0) 127.0.0.1 - - 10/Jul/2023:11:32:27 +0200 "GET /token/2 HTTP/1.1" 405 -
[...]
org.jboss.resteasy.reactive.ClientWebApplicationException: Received: 'Method Not Allowed, status code 405' when invoking: Rest Client method: 'com.github.jdussouillez.client.TokenServiceApiClient#getToken'
[...]
```

### How to Reproduce?

Repo : https://github.com/jdussouillez/quarkus-rest-client-post-redirect-post

- Run the server
- Run the client, when it starts it makes a request on the server and fails

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

3.2.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
According to https://www.rfc-editor.org/rfc/rfc9110#status.307 an HTTP response with 307 status code should not change the request method

Fixes: #34644

### CODE REVIEW

File: extensions/resteasy-reactive/rest-client-reactive/deployment/src/test/java/io/quarkus/rest/client/reactive/redirect/RedirectTest.java [hunk 1]
```diff
@@ -31,50 +31,66 @@ public class RedirectTest {
...
                 .followRedirects(true)
-                .build(RedirectingResourceClient.class);
-        assertThat(client.post().getStatus()).isEqualTo(307);
+                .build(RedirectingResourceClient302.class);
+        assertThat(client302.post().getStatus()).isEqualTo(302);
+
+        RedirectingResourceClient307 client307 = RestClientBuilder.newBuilder()
+                .baseUri(uri)
+                // this property should be ignored in POST
+                .followRedirects(true)
```
Comment (geoand) [inline extensions/resteasy-reactive/rest-client-reactive/deployment/src/test/java/io/quarkus/rest/client/reactive/redirect/RedirectTest.java:65]: To be honest, I am not completely sure about this when the response is 307...

Comment (gsmet) [reply extensions/resteasy-reactive/rest-client-reactive/deployment/src/test/java/io/quarkus/rest/client/reactive/redirect/RedirectTest.java:65]: You mean that we should enforce it when it's 307?

Comment (geoand) [reply extensions/resteasy-reactive/rest-client-reactive/deployment/src/test/java/io/quarkus/rest/client/reactive/redirect/RedirectTest.java:65]: Thats what I am wondering... I don't know that the proper answer is...

**Review by gsmet — APPROVED** [review]
Let's merge this, it's a step in the good direction and we can adjust later if needed.
