### PR TITLE
Fire OIDC security event when OIDC server not available

### LINKED ISSUE #35920: Unable to add additional handling when OIDC provider is not available
### Describe the bug

I am trying to add additional handling for my app when upon startup it isn't able to connect to my OIDC provider. 
However, when trying to pass a @Observes StartupEvent, the OIDC discovery has already been performed - whether it failed or not. 
Is there a way to have this that when it isn't able to connect to my OIDC provider, I can invoke a customized handling? For example, 
sending message up to a messaging stream, customize logging or system.exit or something else...

image

### Expected behavior

Upon getting the 'Discovery has failed' or the exception: io.quarkus.oidc.common.runtime.OidcEndpointAccessException, I should be able to have a way to catch and invoke a customized handling either sending message up to a messaging stream, customize logging or system.exit or something else...

### Actual behavior

Unable to catch the exception and attempt through @Observes StartupEvent is already after the OIDC discovery stage.

### How to Reproduce?

Reproduce:

1. Configure quarkus app that uses OIDC provider - with jwt or none. 
2. Pass in an unreachable OIDC provider url. 
3. Start app, logs will show similar to the attached image above.

### Output of `uname -a` or `ver`

22.04.1-Ubuntu

### Output of `java -version`

Oracle GraalVM 17.0.8+9.1

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

Quarkus 3.2.4.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by michalvavrik**
closes: #35920

### CODE REVIEW

**Comment by sberyozkin** [comment]
@michalvavrik Thanks, great follow up. I'm no sure right now how many times it will be sent, for example, if the URL is not even set or mistyped then the server will not start - I believe this event should not be sent in these cases, please check. 

Also, if a connection error happens for statically configured OIDCs, then a retry will be made at the request time.  I wonder if sending this event at the first failed attempt time, will confuse the consumers, as opposed to sending it after the retry time failure ? They may fire some red alarm ex in RH Insights, but then 1 min later OIDC will be up...

May be we should support an OIDC_AVAILABLE event ?

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/SecurityEvent.java [hunk 1]
```diff
@@ -70,6 +74,11 @@ public SecurityEvent(Type eventType, Map<String, Object> eventProperties) {
         this.eventType = eventType;
     }
 
+    public SecurityEvent(Type eventType) {
```
Comment (sberyozkin) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/SecurityEvent.java:77]: Not sure it is necessary, since it is worth including an address of unavailable server

Comment (michalvavrik) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/SecurityEvent.java:77]: I'll drop it.

**Comment by michalvavrik** [comment]
> @michalvavrik Thanks, great follow up. I'm no sure right now how many times it will be sent,

- it is fired every time Quarkus tries to connect to the OIDC server and OIDC endpoint is not available
- you can see it in the logs as OIDC recorder logs information in the very same situation (equal): _OIDC server is not available at the '...' URL._

> for example, if the URL is not even set 

I've tried following steps:

1. `quarkus create app org.acme:security-openid-connect-multi-tenancy-quickstart     --extension='oidc,resteasy-reactive-jackson'     --no-code`
2. `cd security-openid-connect-multi-tenancy-quickstart/`
3. `mvn clean package`
4. `java -jar target/quarkus-app/quarkus-run.jar `

with result `'quarkus.oidc.auth-server-url' property must be configured` which is fired here 

https://github.com/quarkusio/quarkus/blob/e1c4c96ee8a07149102c830999cbea1edadcf4d2/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcRecorder.java#L211

therefore I don't think that could be a case.

> or mistyped

Validation happens here  https://github.com/quarkusio/quarkus/blob/e1c4c96ee8a07149102c830999cbea1edadcf4d2/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcRecorder.java#L213

while the long flow of unis that at certain point when no other uni failed starts here (which is later):

https://github.com/quarkusio/quarkus/blob/e1c4c96ee8a07149102c830999cbea1edadcf4d2/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcRecorder.java#L313

> then the server will not start - I believe this event should not be sent in these cases, please check.

It is not. If you need me to write tests, I didn't test when this "should not happen" because I suppose list could be long (potentially endless), however I'll add any test you require.

> Also, if a connection error happens for statically configured OIDCs, then a retry will be made at the request time. I wonder if sending this event at the first failed attempt time, will confuse the consumers, as opposed to sending it after the retry time failure ? They may fire some red alarm ex in RH Insights, but then 1 min later OIDC will be up...

We are talking about **Uni**, which should mean there is item or failure once. Therefore idea that retry will lead to multiple exceptions -> multiple events is not correct. I checked here https://smallrye.io/smallrye-mutiny/2.5.3/tutorials/retrying/ and I think this sentence should give us certainty: _If despite multiple attempts, it still fails, the failure is propagated downstream._

For that reason, I believe that retry like this one 

https://github.com/quarkusio/quarkus/blob/e1c4c96ee8a07149102c830999cbea1edadcf4d2/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcRecorder.java#L423

that later leads to reporting event

https://github.com/quarkusio/quarkus/blob/e1c4c96ee8a07149102c830999cbea1edadcf4d2/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcRecorder.java#L430

is fired when OIDC server is not available.

> They may fire some red alarm ex in RH Insights, but then 1 min later OIDC will be up...

1 min in OpenShift where Deployment may scale in a seconds and downscale again based on load and POD health is eternity. Why would you like to disclose information from users? I believe your worries needs to be documented, rather than not fire event.

It sounds to me like you believe there is nothing reasonable users can do with this security event when 1 min later OIDC might be available. But based on that event, they can re-check health of OIDC server from whole different place than this Quarkus app.

> May be we should support an OIDC_AVAILABLE event ?

That is sort of thing users can check easily with call to OIDC server from Quarkus app when they know there is a problem. I can add it if you want, but it wasn't part of #35920 so I didn't add it here. Your call.

Thanks @sberyozkin , I'll wait for feedback before I do any changes, as right now it can be anywhere between _drop constructor and add SERVER URL_ and _rewrite whole PR because your arguments are not sound enough_.

**Comment by michalvavrik** [comment]
I've decided to address the comment I agree with after all.

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/SecurityEvent.java (hunk 1 above)
Comment (michalvavrik) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/SecurityEvent.java]: Done.

**Comment by sberyozkin** [comment]
Hi @michalvavrik Sorry for a delay.

As far as a retry is concerned: I don't refer to that Uni retry, if the connection fails at the start up, then it is pending a retry when the first client request arrives, so at that point a new attempt to get that Uni based connection (with its own retries) is done.

Does it clarify it ?

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcRecorder.java [hunk 2]
```diff
@@ -514,6 +520,18 @@ private static OidcConfigurationMetadata createLocalMetadata(OidcTenantConfig oi
                 oidcConfig.token.issuer.orElse(null));
     }
 
+    private static void fireOidcServerNotAvailableEvent(String authServerUrl) {
+        if (Arc.container().instance(SecurityConfig.class).get().events().enabled()) {
+            if (authServerUrl == null) {
```
Comment (sberyozkin) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcRecorder.java:525]: I'd consider removing this guard since we don't expect it happening, if it will, then we'll handle a bug somewhere up the chain :-)

**Comment by michalvavrik** [comment]
> Hi @michalvavrik Sorry for a delay.

No hurry, I sense this PR will take a while.

> As far as a retry is concerned: I don't refer to that Uni retry, if the connection fails at the start up, then it is pending a retry when the first client request arrives, so at that point a new attempt to get that Uni based connection (with its own retries) is done.

I'm well aware, I tried to answer this here https://github.com/quarkusio/quarkus/pull/37760#issuecomment-1857641383. The idea that it is alright that we do not fire event because it might later be alright means users is loosing opportunity to react ASAP. When it fails on first request, it is worse situation than when it fails on startup. What matters are user requests.

> Does it clarify it ?

Yes.

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcRecorder.java (hunk 2 above)
Comment (michalvavrik) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcRecorder.java:525]: Ok.

**Comment by sberyozkin** [comment]
@michalvavrik The PR is perfect, I'm just thinking about that retry thing, the existing oidc-wiremock test on main demonstrates it, it fails to connect at the start up, but then Wiremock server is started and the connection is established when the test makes a request. I believe there should be an option to observe that OIDC server is available (meaning the previous alarm can be dropped)

**Comment by michalvavrik** [comment]
> @michalvavrik The PR is perfect, I'm just thinking about that retry thing, the existing oidc-wiremock test on main demonstrates it, it fails to connect at the start up, but then Wiremock server is started and the connection is established when the test makes a request. I believe there should be an option to observe that OIDC server is available (meaning the previous alarm can be dropped)

Sure, I'll add the `OIDC_AVAILABLE` event. I'm not sure about name, I'll use ` OIDC_SERVER_AVAILABLE` but you can always request changes later. Thanks

**Comment by michalvavrik** [comment]
Done, I became worried that we will keep sending events for every tenant even though there were no issues every time there is an attempt to connect to the OIDC endpoint, therefore the event reporting that OIDC server is available is only reported once for the tenant that had previous connection failure.

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/SecurityEvent.java [hunk 3]
```diff
@@ -11,8 +11,17 @@
...
     public static final String SESSION_TOKENS_PROPERTY = "session-tokens";
+    public static final String AUTH_SERVER_URL = "auth-server-url";
 
     public enum Type {
+        /**
+         * OIDC endpoint access event which is reported if an attempt to connect to the OIDC server failed.
+         */
+        OIDC_SERVER_NOT_AVAILABLE,
+        /**
+         * OIDC endpoint access event which is reported if connection with the OIDC server has been recovered.
```
Comment (sberyozkin) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/SecurityEvent.java:22]:
```suggestion
         * OIDC connection event which is reported when a connection with the OIDC server has been established.
```

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/SecurityEvent.java [hunk 4]
```diff
@@ -11,8 +11,17 @@
  */
 public class SecurityEvent extends AbstractSecurityEvent {
     public static final String SESSION_TOKENS_PROPERTY = "session-tokens";
+    public static final String AUTH_SERVER_URL = "auth-server-url";
 
     public enum Type {
+        /**
+         * OIDC endpoint access event which is reported if an attempt to connect to the OIDC server failed.
```
Comment (sberyozkin) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/SecurityEvent.java:18]:
```suggestion
         * OIDC connection event which is reported when an attempt to connect to the OIDC server has failed.
```

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcRecorder.java [hunk 5]
```diff
@@ -60,6 +66,7 @@ public class OidcRecorder {
     private static final Logger LOG = Logger.getLogger(OidcRecorder.class);
 
     private static final Map<String, TenantConfigContext> dynamicTenantsConfig = new ConcurrentHashMap<>();
+    private static final Set<String> tenantsForWhichWeReportServerAvailable = ConcurrentHashMap.newKeySet();
```
Comment (sberyozkin) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcRecorder.java:69]:
```suggestion
    private static final Set<String> tenantsExpectingServerAvailableEvents = ConcurrentHashMap.newKeySet();
```

It is just an internal var but not sure about `we` in its name :-)

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcRecorder.java [hunk 6]
```diff
@@ -427,7 +435,15 @@ protected static Uni<JsonWebKeySet> getJsonWebSetUni(OidcProviderClient client,
                     .transform(new Function<Throwable, Throwable>() {
                         @Override
                         public Throwable apply(Throwable t) {
-                            return toOidcException(t, oidcConfig.authServerUrl.get());
+                            return toOidcException(t, oidcConfig.authServerUrl.get(),
+                                    oidcConfig.tenantId.orElse(DEFAULT_TENANT_ID));
+                        }
+                    })
+                    .invoke(new Runnable() {
```
Comment (sberyozkin) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcRecorder.java:442]: Is it possible to make it conditional ? Creating a runnable instance if no one is listening will have some cost

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcRecorder.java [hunk 7]
```diff
@@ -514,6 +532,29 @@ private static OidcConfigurationMetadata createLocalMetadata(OidcTenantConfig oi
                 oidcConfig.token.issuer.orElse(null));
     }
 
+    private static void fireOidcServerNotAvailableEvent(String authServerUrl, String tenantId) {
+        if (fireOidcServerEvent(authServerUrl, OIDC_SERVER_NOT_AVAILABLE)) {
+            tenantsForWhichWeReportServerAvailable.add(tenantId);
```
Comment (sberyozkin) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcRecorder.java:537]: I see. I wonder if the time come to introduce OIDC SecurityEvent subtypes ? May be later though

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcRecorder.java (hunk 5 above)
Comment (michalvavrik) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcRecorder.java:69]: Well, someone has to do it... no seriously, I tried like 5 versions and your name is still better, thanks.

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/SecurityEvent.java (hunk 3 above)
Comment (michalvavrik) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/SecurityEvent.java:22]: I used `OIDC endpoint access` because that was name of the exception thrown by OIDC, personally couldn't care less, will use your version.

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcRecorder.java (hunk 7 above)
Comment (michalvavrik) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcRecorder.java:537]: I'm honestly not sure where to draw a line. It all depends on how / how-much will users use this. I don't want to add too much of a code to Quarkus OIDC. Considering this event is not fired for every application, but only those in (temporary?) problems, I think cost of this PR is going to be very small. So I'd wait.

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcRecorder.java (hunk 6 above)
Comment (michalvavrik) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcRecorder.java]: done

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcRecorder.java [hunk 8]
```diff
@@ -514,6 +542,32 @@ private static OidcConfigurationMetadata createLocalMetadata(OidcTenantConfig oi
...
+    }
+
+    private static void fireOidcServerAvailableEvent(String authServerUrl, String tenantId) {
+        if (fireOidcServerEvent(authServerUrl, OIDC_SERVER_AVAILABLE)) {
+            tenantsExpectingServerAvailableEvents.remove(tenantId);
+        }
+    }
+
+    private static boolean shouldFireOidcServerAvailableEvent(String tenantId) {
+        return tenantsExpectingServerAvailableEvents.contains(tenantId);
```
Comment (sberyozkin) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcRecorder.java:558]: @michalvavrik This is the last one I think, that should probably remove the tenant from the map, I guess, otherwise, when a dynamic TenantConfigResolver is used, it might keep growing even if only when connection failures occur

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcRecorder.java (hunk 7 above)
Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcRecorder.java]: @michalvavrik OK, lets not do it for now, thanks

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcRecorder.java (hunk 8 above)
Comment (michalvavrik) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcRecorder.java:558]: @sberyozkin I'll need little more to understand Sergey. Can you give me hint what you mean, please? Please note that tenant is removed when OIDC available event is reported. I don't want to remove it before that happens, because then I wouldn't have certainty that event were reported.

**Review by sberyozkin — APPROVED** [review]
