### PR TITLE
Fix FaultTolerance perf issue related to the creation of FaultToleranceOperation

### LINKED ISSUE #6761: QuarkusFaultToleranceOperationProvider should cache the FaultToleranceOperation
**Description**
`QuarkusFaultToleranceOperationProvider` re-creates a new `FaultToleranceOperation` object for each request. 

CPU profiling shows that creating such object can uses a significant amount of CPU, see here for details: https://groups.google.com/d/msg/quarkus-dev/2jFpwMt4QaI/edUfNagDCgAJ

Smallrye-fault-tolerance provides a CDI extension that caches the `FaultToleranceOperation` but Quarkus didn't use it (CDI portable extensions are not supported in Quarkus ) so we need to create something dedicated to Quarkus.

**Implementation ideas**
Fault tolerance extension can be found here: https://github.com/smallrye/smallrye-fault-tolerance/blob/master/implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/DefaultFaultToleranceOperationProvider.java#L43-L56

A prototype implementation that needs to be reworked can be found here:  https://github.com/quarkusio/quarkus/compare/master...loicmathieu:fix/ft-perf-issue

### PR DESCRIPTION
**Pull request by loicmathieu**
Fixes #6761

Still a draft PR as I want some feedback on the implementation before polishing it (if needed).

As discuss on the mailing list and on the issue, there is some performance issue as currently the `FaultToleranceOperation` is re-created on each request.

The first commit address this issue by using a cache that is filled at `RUNTIME_INIT` by the recorder. It works except for FT annotations on interfaces (like the one on RestClient interfaces). So there is a fallback that create it on the fly. If we only keep this change we need to store inside the cache the `FaultToleranceOperation` created on the fly to fix the issue correctly.

I made a second change when I discover that the recorder load all bean classes to analyse them for FT annotations. I restrict the list of bean classes to analyse using Jandex indexes and it improve a lot the performance of scanning the classpath for FT annotations. On the main integration test, the time to `validate` the annotations drop from 200ms to 7ms => improvement of 20x at runtime !

If we keep the second commit, we will also create `FaultToleranceOperation` for RestClient interfaces correctly at `RUNTIME_INIT` by the recorder as Jandex indexe interfaces.

@Ladicek @mkouba @michalszynkiewicz WDYT ?

### CODE REVIEW

File: extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java [hunk 1]
```diff
@@ -1,22 +1,39 @@
...
+
 import io.smallrye.faulttolerance.FaultToleranceOperationProvider;
 import io.smallrye.faulttolerance.config.FaultToleranceOperation;
 
 @Dependent
 @Alternative
 @Priority(1)
 public class QuarkusFaultToleranceOperationProvider implements FaultToleranceOperationProvider {
+    private static final Logger LOG = Logger.getLogger(QuarkusFaultToleranceOperationProvider.class);
+    static final Map<String, FaultToleranceOperation> OPERATIONS = new ConcurrentHashMap<>();
```
Comment (mkouba) [inline extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java]: You can make the `QuarkusFaultToleranceOperationProvider` a `@Singleton` and then there is no need to use static field here. Instead, you can use `Arc.container().instance(QuarkusFaultToleranceOperationProvider.class).init(Map<String,FaultToleranceOperation> ops)` in the recorder.

File: extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java [hunk 2]
```diff
@@ -1,22 +1,39 @@
...
 
     @Override
     public FaultToleranceOperation get(Class<?> beanClass, Method method) {
+        String key = getCacheKey(beanClass, method);
+        FaultToleranceOperation operation = OPERATIONS.get(key);
+        return operation != null ? operation : createAtRuntime(beanClass, method, key);
```
Comment (mkouba) [inline extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java]: We could use `Map.computeIfAbsent()` if a `FaultToleranceOperation` is not found in the cache...

File: extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/SmallryeFaultToleranceRecorder.java [hunk 3]
```diff
@@ -66,11 +70,12 @@ public void validate(List<String> beanNames) {
     private Set<Method> getMethodsForValidation(Class<?> beanClass) {
         Set<Method> allMethods = new HashSet<>();
         Class<?> currentClass = beanClass;
-        while (!currentClass.equals(Object.class)) {
+        System.out.println(currentClass);
```
Comment (mkouba) [inline extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/SmallryeFaultToleranceRecorder.java]: No `System.out.print` please ;-)

**Review by mkouba — CHANGES_REQUESTED** [review]

File: extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/SmallryeFaultToleranceRecorder.java (hunk 3 above)
Comment (loicmathieu) [reply extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/SmallryeFaultToleranceRecorder.java]: Still a draft :).
I will remove it

File: extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java (hunk 2 above)
Comment (loicmathieu) [reply extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java]: This was on my first implémentation, but as with the current one the operation should always be in the cache I don't know if it worth it.
It is here to catch potential bugs, and as it will be inside the hot code path I prefere to use `get` instead of `computeIfAbsent`. We could revisit it later if needed.

Comment (gsmet) [reply extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java]: My HV benchmarks taught me the hard way that using `get()` is faster if having the operation in the cache is the most common use case.

Comment (mkouba) [reply extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java]: +1

File: extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java (hunk 1 above)
Comment (loicmathieu) [reply extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java]: OK, will do.
And if I don't implements `computeIfAbsent` I should be able to use an HashMap directly instead of a concurrent one as the map will never be modified outside the enhancer.

File: extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java (hunk 2 above)
Comment (geoand) [reply extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java]: I remember having similar discussions on the PRs :). I say no `computeIfAbsent` anywhere on the hot path :)

File: extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java (hunk 1 above)
Comment (mkouba) [reply extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java]: Yep, an optimized immutable map would be a perfect fit but unfotunately there is no such impl in JDK.

File: extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java (hunk 2 above)
Comment (mkouba) [reply extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java]: Well, it depends on how many times it's invoked ;-). From my experience microbenchmarks are often tricky and the bottlenecks identified in the infra code might not be bottlenecks at all in a real app and vice versa.

Comment (loicmathieu) [reply extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java]: Well, with native image, stuff are a little different as there is no optimisation based on branch prediction (unless for paid customers using the new PGO mechanism of GraalVM). So computeIfAbsent could be more slow on native image than on JVM mode ...
Having said that, if I didn't saw any benchmark written with JMH that prove this I will deny it ;)

Anyway, I switch to regular HashMap and uses `get` as the operation should always be present (in fact I can move to a runtime exception if not in the cache if we prefere ... like a NPE :) )

File: extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/SmallryeFaultToleranceRecorder.java (hunk 3 above)
Comment (loicmathieu) [reply extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/SmallryeFaultToleranceRecorder.java]: Removed

**Review by gsmet — CHANGES_REQUESTED** [review]
I added a couple of very minor comments.

**Comment by mkouba** [comment]
It seems that a test from MP FT TCK failed:
```
[ERROR]   FallbackMethodGenericAbstractTest>Arquillian.arquillianBeforeClass:96 
```

**Comment by loicmathieu** [comment]
@gsmet I updated the PR with your proposed changes.

@mkouba I'll check the TCK

**Comment by loicmathieu** [comment]
@mkouba the issue from the TCK seems unrelated to my changes

```
java.lang.AssertionError: Unexpected exceptionjava.util.concurrent.ExecutionException: java.util.ServiceConfigurationError: io.smallrye.config.SmallRyeConfigFactory: io.quarkus.runtime.configuration.QuarkusConfigFactory not a subtype
```

**Comment by loicmathieu** [comment]
@mkouba just testing the TCK from master and it fails with the same error

**Comment by mkouba** [comment]
> @mkouba just testing the TCK from master and it fails with the same error

Hm, interesting. The last job does not seem to fail with this issue. Let me try this locally...

**Comment by mkouba** [comment]
So I've just tried to run the TCKs on master and the result is BUILD SUCCESS.

**Comment by loicmathieu** [comment]
@mkouba I will double-check ...

**Comment by loicmathieu** [comment]
@mkouba master is still failing for me but it only have 4 failures where my branch have 5.

So I chase down the new failing test to `FallbackMethodGenericAbstractTest`, I will investiguate.

**Comment by mkouba** [comment]
> master is still failing for me...

Hm, that's suspicious... 

> So I chase down the new failing test to FallbackMethodGenericAbstractTest

@loicmathieu yep, that's the one that fails on CI too.

**Comment by loicmathieu** [comment]
@mkouba thanks to the TCK I chased down a bug when the annotation is not on the bean class but on one of it's parent; the previous implementation didn't work.

I switch back to using the `validationPhase.getContext().beans()` to scan all beans but filter the list of bean to create FT operations for by using Jandex to check if an FT annotation is present on a class (or one of it's methods) or on one of it's parents (or on one of the parent's method). And now all FT operations for all tests (main integration test and TCK) are correctly found at build time !

As the startup performance issue was due to loading all bean classes via reflection, filtering the bean at the validation stage like this still give me the same performance improvements (on my personal projects 250ms startup improvements over 2.5s, same kind of startup improvements can be found for the main integration test).

@gsmet I check all the other usage of the ValidationBuildItem and none are suffering from the same issue (none load all beans via refleciton). When checking other usages, I spotted a small unecessary if condition on `VertxWebProcessor` that I remove (the same check was done as a stream predicate and in a if statement when iterating the stream), it is on a separate commit.

I will merge the first three commits when we agree on the implementation.

File: extensions/smallrye-fault-tolerance/deployment/src/main/java/io/quarkus/smallrye/faulttolerance/deployment/SmallRyeFaultToleranceProcessor.java [hunk 4]
```diff
@@ -187,13 +192,42 @@ public void transform(TransformationContext ctx) {
...
-        List<String> beanNames = new ArrayList<>();
-        for (BeanInfo bean : validationPhase.getContext().beans().classBeans()) {
-            beanNames.add(bean.getBeanClass().toString());
+    void validateFaultToleranceAnnotations(SmallryeFaultToleranceRecorder recorder,
+            ValidationPhaseBuildItem validationPhase) {
+        AnnotationStore annotationStore = validationPhase.getContext().get(BuildExtension.Key.ANNOTATION_STORE);
+        Set<String> beanNames = new HashSet<>();
+        IndexView index = combinedIndexBuildItem.getIndex();
+
+        for (BeanInfo info : validationPhase.getContext().beans()) {
```
Comment (mkouba) [inline extensions/smallrye-fault-tolerance/deployment/src/main/java/io/quarkus/smallrye/faulttolerance/deployment/SmallRyeFaultToleranceProcessor.java]: We're only interested in class beans which have at least one around invoke interceptor... so something like this could slightly improve the perf: `validationPhase.getContext().beans().stream().filter(BeanInfo::hasAroundInvokeInterceptors).iterator()`

File: extensions/smallrye-fault-tolerance/deployment/src/main/java/io/quarkus/smallrye/faulttolerance/deployment/SmallRyeFaultToleranceProcessor.java [hunk 5]
```diff
@@ -187,13 +192,42 @@ public void transform(TransformationContext ctx) {
...
-    void validateFaultToleranceAnnotations(
-            ValidationPhaseBuildItem validationPhase, SmallryeFaultToleranceRecorder recorder) {
-        List<String> beanNames = new ArrayList<>();
-        for (BeanInfo bean : validationPhase.getContext().beans().classBeans()) {
-            beanNames.add(bean.getBeanClass().toString());
+    void validateFaultToleranceAnnotations(SmallryeFaultToleranceRecorder recorder,
+            ValidationPhaseBuildItem validationPhase) {
+        AnnotationStore annotationStore = validationPhase.getContext().get(BuildExtension.Key.ANNOTATION_STORE);
+        Set<String> beanNames = new HashSet<>();
+        IndexView index = combinedIndexBuildItem.getIndex();
```
Comment (mkouba) [inline extensions/smallrye-fault-tolerance/deployment/src/main/java/io/quarkus/smallrye/faulttolerance/deployment/SmallRyeFaultToleranceProcessor.java]: Unused variable?

File: extensions/smallrye-fault-tolerance/deployment/src/main/java/io/quarkus/smallrye/faulttolerance/deployment/SmallRyeFaultToleranceProcessor.java [hunk 6]
```diff
@@ -187,13 +192,42 @@ public void transform(TransformationContext ctx) {
...
+        // then check on the methods
+        for (MethodInfo method : info.methods()) {
+            if (annotationStore.hasAnyAnnotation(method, FT_ANNOTATIONS)) {
+                return true;
+            }
+        }
+
+        // then check on the parent
+        DotName parentClassName = info.superName();
+        ClassInfo parentClassInfo = combinedIndexBuildItem.getIndex().getClassByName(parentClassName);
```
Comment (mkouba) [inline extensions/smallrye-fault-tolerance/deployment/src/main/java/io/quarkus/smallrye/faulttolerance/deployment/SmallRyeFaultToleranceProcessor.java]: I think that using `BeanArchiveIndexBuildItem` would be more appropriate in this case. Also the injected fields of `SmallRyeFaultToleranceProcessor` should be probably turned into injected params of the `SmallRyeFaultToleranceProcessor.build()` build step (they're not shared so it does not make much sense to use fields). I know that it's not a subject of this PR but it would deserve a small refactoring ;-).

File: extensions/smallrye-fault-tolerance/deployment/src/main/java/io/quarkus/smallrye/faulttolerance/deployment/SmallRyeFaultToleranceProcessor.java [hunk 7]
```diff
@@ -187,13 +192,42 @@ public void transform(TransformationContext ctx) {
...
+        if (parentClassName.equals(DOTNAME_OBJECT) || parentClassInfo == null) {
```
Comment (mkouba) [inline extensions/smallrye-fault-tolerance/deployment/src/main/java/io/quarkus/smallrye/faulttolerance/deployment/SmallRyeFaultToleranceProcessor.java]: You can reuse `io.quarkus.arc.processor.DotNames.OBJECT`.

**Review by mkouba — CHANGES_REQUESTED** [review]
Looks good but with this approach the rest client interfaces will not be processed, or?

**Comment by loicmathieu** [comment]
> Looks good but with this approach the rest client interfaces will not be processed, or?

No, so I must lazily creates it at runtime (using a CHM and a computeIfAbsent as in my first implementation). 
In fact, the previous implementation also didn't validate it at build time (so my current code improve the startup of the application) as it was also based on `validationPhase.context().beans()`.

**Comment by loicmathieu** [comment]
@mkouba I double-checked and in fact using `validationPhase.getContext().beans()` and not `validationPhase.getContext().beans().classBeans()` allow to access interfaces (they are indexed by Jandex). I tested on my project and it works for my rest client.

No need to cache the missing fault tolerance operations at runtime as they should all be in the cache. I will keep the WARNING as I expect users to open issue if they see WARNING in the log so if something is missing we can add it later to the cache.

File: extensions/smallrye-fault-tolerance/deployment/src/main/java/io/quarkus/smallrye/faulttolerance/deployment/SmallRyeFaultToleranceProcessor.java (hunk 4 above)
Comment (loicmathieu) [reply extensions/smallrye-fault-tolerance/deployment/src/main/java/io/quarkus/smallrye/faulttolerance/deployment/SmallRyeFaultToleranceProcessor.java]: No possible or we will miss the annotations on interfaces (like the one for rest client)

File: extensions/smallrye-fault-tolerance/deployment/src/main/java/io/quarkus/smallrye/faulttolerance/deployment/SmallRyeFaultToleranceProcessor.java (hunk 5 above)
Comment (loicmathieu) [reply extensions/smallrye-fault-tolerance/deployment/src/main/java/io/quarkus/smallrye/faulttolerance/deployment/SmallRyeFaultToleranceProcessor.java]: Yes, removed, sorry.

File: extensions/smallrye-fault-tolerance/deployment/src/main/java/io/quarkus/smallrye/faulttolerance/deployment/SmallRyeFaultToleranceProcessor.java (hunk 6 above)
Comment (loicmathieu) [reply extensions/smallrye-fault-tolerance/deployment/src/main/java/io/quarkus/smallrye/faulttolerance/deployment/SmallRyeFaultToleranceProcessor.java]: Switch to `BeanArchiveIndexBuildItem`.
Refactor to inject everything via parameters.

File: extensions/smallrye-fault-tolerance/deployment/src/main/java/io/quarkus/smallrye/faulttolerance/deployment/SmallRyeFaultToleranceProcessor.java (hunk 7 above)
Comment (loicmathieu) [reply extensions/smallrye-fault-tolerance/deployment/src/main/java/io/quarkus/smallrye/faulttolerance/deployment/SmallRyeFaultToleranceProcessor.java]: Done

**Comment by mkouba** [comment]
Hm, `validationPhase.getContext().beans()` also includes synthetic beans and AFAIK we do register synthetic beans for rest client interfaces iff they are annotated with `@RegisterRestClient`. In other words, yes this should cover most of the rest client interfaces but not those accessed directly through a builder.

**Review by gsmet — CHANGES_REQUESTED** [review]
Please squash these commits into one once you're done (and this review can be dismissed as soon as it's done).

**Comment by loicmathieu** [comment]
@mkouba 

> In other words, yes this should cover most of the rest client interfaces but not those accessed directly through a builder.

Will FT annotations works in this case ? If yes, so I must update the implementation to put in cache the missing FTOperations at runtime ...

**Comment by mkouba** [comment]
> Will FT annotations works in this case 

I think they should. It is not supported by the CDI spec - interceptor bindings on interfaces - but our Rest Client impl (previously SmallRye and now RESTEasy) resolves/invokes the CDI interceptors manually.

**Comment by loicmathieu** [comment]
@mkouba OK, I will switch back to using `computeIfAbsent` to allow runtime creation of FTOperations to be stored inside the cache.

**Comment by loicmathieu** [comment]
@mkouba I update my PR to store FT operations at runtime if not already done inside the build step.
Is it OK for you now ?

**Review by mkouba — CHANGES_REQUESTED** [review]
I added few minor comments. Otherwise looks good.

**Comment by mkouba** [comment]
@loicmathieu And thanks for your patience. Sometimes it takes time to find the correct solution ;-).

File: extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java [hunk 8]
```diff
@@ -1,22 +1,50 @@
...
 import io.smallrye.faulttolerance.FaultToleranceOperationProvider;
 import io.smallrye.faulttolerance.config.FaultToleranceOperation;
 
-@Dependent
+@Singleton
 @Alternative
 @Priority(1)
 public class QuarkusFaultToleranceOperationProvider implements FaultToleranceOperationProvider {
+    private static final Logger LOG = Logger.getLogger(QuarkusFaultToleranceOperationProvider.class);
+    private Map<String, FaultToleranceOperation> operationCache;
```
[the remark this answers is not in the document]
Comment (loicmathieu) [reply extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java]: Ah sorry, it was in my first implementation, I forgot to switch it.

File: extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java [hunk 9]
```diff
@@ -1,22 +1,50 @@
...
+        return operationCache.computeIfAbsent(key, new Function<String, FaultToleranceOperation>() {
+            @Override
+            public FaultToleranceOperation apply(String key) {
+                return createAtRuntime(beanClass, method, key);
+            }
+        });
+    }
+
+    private FaultToleranceOperation createAtRuntime(Class<?> beanClass, Method method, String key) {
+        LOG.warnf("FaultToleranceOperation not found in the cache for %s creating it at runtime", key);
```
[the remark this answers is not in the document]
Comment (loicmathieu) [reply extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java]: Yes, now that we define that it can occurs and it's not a bug, INFO seems better.

**Comment by loicmathieu** [comment]
@mkouba it should be OK now, I also squash the commit but I keep separate the small no-op vertx change.

File: extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java (hunk 9 above)
[the remark this answers is not in the document]
Comment (gsmet) [reply extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java]: Do we really need an INFO if it's the normal behavior? Or it's not a normal behavior?

If it's normal behavior, it should just be debug.

File: extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java [hunk 10]
```diff
@@ -1,22 +1,50 @@
...
+     * Called by SmallryeFaultToleranceRecorder to init the operation cache.
+     */
+    void init(Map<String, FaultToleranceOperation> operationCache) {
+        this.operationCache = operationCache;
+    }
 
     @Override
     public FaultToleranceOperation get(Class<?> beanClass, Method method) {
+        String key = getCacheKey(beanClass, method);
+        return operationCache.computeIfAbsent(key, new Function<String, FaultToleranceOperation>() {
```
[the remark this answers is not in the document]
Comment (gsmet) [reply extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java]: I don't see why we don't make the function a constant? Is there something forbidding it?

File: extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java (hunk 9 above)
[the remark this answers is not in the document]
Comment (loicmathieu) [reply extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java]: It will be logged only once, and should arrives in very rare conditions (using the builder aproach for RestClient is one that we thin of, this aproach is not documented on the Quarkus site).
But I'm OK with DEBUG ...

File: extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java (hunk 10 above)
[the remark this answers is not in the document]
Comment (mkouba) [reply extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java]: Because we use the method arguments inside the function -> `createAtRuntime(beanClass, method, key)`.

**Review by mkouba — APPROVED** [review]

File: extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java (hunk 10 above)
[the remark this answers is not in the document]
Comment (loicmathieu) [reply extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java]: It's possible if I used a CompositeKey with beanClass and method instead of a String. So everything needed to create the operation will be on the key and the Function could be a constant.

[the remark this answers is not in the document]
Comment (gsmet) [reply extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java]: Yeah, I was thinking about that.

TBH, the best solution here is to do what I suggested first: we do a first `get()` call and only call `computeIfAbsent` if we have nothing. As previously mentioned, I did some extensive benchmarks on HV and it's significantly faster if this is called often (and I suppose it will be called for every call to a function that is marked with FT annotations or am I missing something?). And this will avoid creating the function if this is in the cache.

File: extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java (hunk 9 above)
[the remark this answers is not in the document]
Comment (gsmet) [reply extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java]: If it's something that can happen and doesn't need any action by the user then debug is enough IMHO.

File: extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java (hunk 10 above)
[the remark this answers is not in the document]
Comment (mkouba) [reply extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java]: That would not help much - you'll have to create a new key object for each `get()` anyway...

[the remark this answers is not in the document]
Comment (loicmathieu) [reply extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java]: Previsouly I created a new String for each object so it should be the same ...

[the remark this answers is not in the document]
Comment (loicmathieu) [reply extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java]: And the key object just hold two references for existing object so should be small regarding a new string ...

[the remark this answers is not in the document]
Comment (loicmathieu) [reply extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java]: @gsmet @mkouba updated with a composite CacheKey to avoid re-creating the Function on each call and implemented @gsmet optimization on the CHM.

If it's OK I'll squash the last commit and we'll be ready to go :)

File: extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java [hunk 11]
```diff
@@ -19,33 +20,73 @@
...
+    static class CacheKey {
+        private Class<?> beanClass;
+        private Method method;
+
+        public CacheKey(Class<?> beanClass, Method method) {
+            this.beanClass = beanClass;
+            this.method = method;
+        }
+
+        public Class<?> getBeanClass() {
```
Comment (mkouba) [inline extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java]: What are the getters/setters for?

Comment (loicmathieu) [reply extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java]: Useless, removed, sorry.

**Comment by mkouba** [comment]
Looks good. Could you squash the commits? Thanks!

File: extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java [hunk 12]
```diff
@@ -1,22 +1,76 @@
...
+            if (o == null || getClass() != o.getClass())
+                return false;
+            CacheKey cacheKey = (CacheKey) o;
+            return Objects.equals(beanClass, cacheKey.beanClass) &&
+                    Objects.equals(method, cacheKey.method);
+        }
+
+        @Override
+        public int hashCode() {
+            return Objects.hash(beanClass, method);
```
Comment (gsmet) [inline extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java]: It's minor but I would compute the hashCode in the constructor if it can become a hot path. That's what we do in HV.

That allows to cache the hashCode once and for all for all the items that are in the map.

File: extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java [hunk 13]
```diff
@@ -1,22 +1,76 @@
...
+            this.beanClass = beanClass;
+            this.method = method;
+        }
+
+        @Override
+        public boolean equals(Object o) {
+            if (this == o)
+                return true;
+            if (o == null || getClass() != o.getClass())
+                return false;
```
Comment (gsmet) [inline extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java]: If you end up taking into account my comment below, please use curly braces for the two statements above.

**Comment by gsmet** [comment]
I added two more small comments. They are minor but since you are working on optimizing things, it might be worth it.

File: extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java (hunk 12 above)
Comment (mkouba) [reply extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java]: +1 and also make the fields final please.

File: extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java (hunk 10 above)
[the remark this answers is not in the document]
Comment (gsmet) [reply extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java]: @mkouba you won't avoid creating the key but you can avoid creating the function.

File: extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java (hunk 12 above)
Comment (gsmet) [reply extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java]: Actually, I'm torn on that, not having the fields final make the JDK do some weird optimizations :). I removed them from the key objects in HV after Sanne gave me the idea to test it and benchmark it.

Comment (mkouba) [reply extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java]: So I'm not following. Was it better or worse ;-). In any case, the key should be immutable and it's not.

File: extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java (hunk 13 above)
Comment (loicmathieu) [reply extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java]: Done, I should update my IDEA templates as I prefere having the curly braces ...

File: extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java (hunk 12 above)
Comment (loicmathieu) [reply extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java]: @gmset good catch on the cache of the hashCode, I'm not used to do it but totaly worth it :)

Regarding final fields, I add final to all three fields, I can remove it.

@gmset it's very interesting, I was not aware of performance penalty on final field writes inside a constructor so I make some research and yes, there is a small performance penalty because the VM emmit a memory barrier when one of the field written inside a constructor is final. The cost of the barrier is minimal (5ns on ARM, almost nefligeable on x86). As always some good explaination/experiments on this can be found on Alexey Shipilev blog: https://shipilev.net/blog/2014/all-fields-are-final/

I you want, I can remove the three final modifier ...

**Comment by loicmathieu** [comment]
@gsmet @mkouba I take into account all yours request except for the final fields: I keep them. Please tell me if I need to remove them. Else, ready to be merged :)

File: extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java (hunk 12 above)
Comment (gsmet) [reply extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java]: In my HV benchmarks (and I have no idea why), removing the final from the fields did help. In HV, the only classes that don't have final fields are the classes used as keys. It's a very hot path though.

Comment (loicmathieu) [reply extensions/smallrye-fault-tolerance/runtime/src/main/java/io/quarkus/smallrye/faulttolerance/runtime/QuarkusFaultToleranceOperationProvider.java]: OK, to please @gsmet ;) I remove the final modifier.
Ready to be merged

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
@loicmathieu it would be interesting to check what your flame graph looks like now. I know I had some bad surprises with the `equals` from the reflection API being slow in the past. But I merged and let's iterate from there!

**Comment by loicmathieu** [comment]
@gsmet on the mailing list I send flamegraph with a fix like this one (with a CacheKey) and it shows that FT was no longer an issue. I'll test again with this fix to be 100% sure (probably next week) and send update to the mailing list.
