### PR TITLE
Fix tracing protocol configuration to only allow grpc

### LINKED ISSUE #36084: Exception when specifying QUARKUS_OTEL_EXPORTER_OTLP_TRACES_PROTOCOL=grpc
### Describe the bug

When using the environment variable `QUARKUS_OTEL_EXPORTER_OTLP_TRACES_PROTOCOL=grpc` Quarkus will throw exception 
```
Caused by: java.lang.IllegalStateException: Only the GRPC Exporter is currently supported. Please check `otel.exporter.otlp.traces.protocol` property
	at io.quarkus.opentelemetry.runtime.exporter.otlp.OtlpRecorder.createOtlpGrpcSpanExporter(OtlpRecorder.java:110)
	at io.quarkus.opentelemetry.runtime.exporter.otlp.OtlpRecorder.installBatchSpanProcessorForOtlp(OtlpRecorder.java:61)
```

I think this issue has been resolved in https://github.com/quarkusio/quarkus/pull/35156 for 3.3.0, but for the older version, this is still causing issues. Can we implement a fix for the older versions? 

Looks like the logic at https://github.com/quarkusio/quarkus/blob/cca68dd37170d3d389fcf7117455ee798f6d055e/extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/exporter/otlp/OtlpRecorder.java#L109 is a little bit wrong. Shouldn't the error be thrown when the protocol not equals to `grpc` instead? 

Thanks! Please feel free to correct me if I am getting any thing wrong here.  

### Expected behavior

No exception should be thrown

### Actual behavior

Exception thrown 

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

3.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by siewp**
Fixes #36084

### CODE REVIEW

**Comment by gsmet** [comment]
@brunobat this makes sense to me given the exception we throw but I would prefer if you had a look.

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/exporter/otlp/OtlpRecorder.java [hunk 1]
```diff
@@ -106,7 +106,7 @@ public void accept(CompressionType compression) {
                     }
                 });
 
-        if (!exporterRuntimeConfig.traces().protocol().orElse("").equals(HTTP_PROTOBUF)) {
+        if (!exporterRuntimeConfig.traces().protocol().orElse("").equals(GRPC)) {
```
Comment (brunobat) [inline extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/exporter/otlp/OtlpRecorder.java:109]: The message is legacy, we currently allow either GRPC or HTTP_PROTOBUF. The exception should mention that.
We need to make sure we have a test for each protocol value.

**Review by brunobat — CHANGES_REQUESTED** [review]

**Comment by brunobat** [comment]
@siewp are you going to continue with the PR?

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/exporter/otlp/OtlpRecorder.java (hunk 1 above)
Comment (siewp) [reply extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/exporter/otlp/OtlpRecorder.java:109]: Isn't HTTP_PROTOBUF only available from Quarkus 3.3? I only saw `OtlpGrpcSpanExporter`, but no HttpExporter in 3.2

Comment (brunobat) [reply extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/exporter/otlp/OtlpRecorder.java:109]: HTTP_PROTOBUF and the HttpExporter are only available after 3.3

Comment (siewp) [reply extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/exporter/otlp/OtlpRecorder.java:109]: But the PR is for 3.2. Should the message of the exception then contain something like `Only the GRPC Exporter is currently supported. HTTP_PROTOBUF is available after Quarkus 3.3.`?

Comment (brunobat) [reply extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/exporter/otlp/OtlpRecorder.java:109]: I didn't realise it was against the branch. Please re-do the PR against `main` and we will mark it for backporting until 3.2... This will affect many branches because main is already preparing for 3.5.
I propose this more generic message: `Only the "grpc" and "http/protobuf" values are supported in the otel.exporter.otlp.traces.protocol property. "http/protobuf" is only available after Quarkus 3.3`.

Comment (siewp) [reply extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/exporter/otlp/OtlpRecorder.java:109]: The problem described in the issue doesn't exist anymore in `main`. It only exists in Quarkus 3.2 and lower versions. In 3.3 there was already [a rewrite of this](https://github.com/quarkusio/quarkus/blob/3.3/extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/exporter/otlp/OtlpRecorder.java#L88).

**Review by brunobat — APPROVED** [review]
Thanks @siewp!
@gsmet this should be good to go to the 3.2 branch.

**Comment by brunobat** [comment]
@siewp can you please squash the into a single commit?

**Comment by siewp** [comment]
@brunobat Done!

**Comment by siewp** [comment]
@gsmet Is there anything else that needs to be done to merge this PR?

**Comment by aloubyansky** [comment]
@brunobat is the equivalent change present in main? Is it still good to merge in 3.2? Thanks!

**Comment by brunobat** [comment]
The code in main has diverged after v3.3, however this PR still makes sense to v3.2 @aloubyansky. CC @gsmet 
I'm a bit surprised this is not merged yet.

**Comment by gsmet** [comment]
Pushing things to 3.2 only is not very usual, that's why this somehow felt through the cracks.

@aloubyansky @rsvoboda this one would probably require you having a look.

**Comment by gsmet** [comment]
I added the  `3.2.10.Final` milestone so that we keep it on the radar for consideration for 3.2.

**Comment by rsvoboda** [comment]
We had triage with Alexey, that's why he added the comment here. There wasn't any PR to main from @siewp

**Comment by brunobat** [comment]
yes, main had diverged significantly at that point, not needing this pr. This is because we now have totally different exporters.
