### PR TITLE
Use the DeploymentClassLoader to transform classes

### LINKED ISSUE #6091: mvn quarkus:dev freezes in a project with bidirectional JPA relationships
**Describe the bug**
Having the following entities in a Quarkus app makes `mvn compile quarkus:dev` freeze: 

```java
@Entity
@Table(name = "owners")
public class Owner {

    @OneToMany(cascade = CascadeType.ALL, mappedBy = "owner")
    private Set<Pet> pets;

    public Set<Pet> getPets() {
        return pets;
    }

    public void setPets(Set<Pet> pets) {
        this.pets = pets;
    }
}
```

And 
```java
@Entity
@Table(name = "pets")
public class Pet {

    @ManyToOne
    @JoinColumn(name = "owner_id")
    private Owner owner;

    public Owner getOwner() {
        return owner;
    }

    public void setOwner(Owner owner) {
        this.owner = owner;
    }
}

```

**Expected behavior**
Application should run 

**Actual behavior**
Application is frozen. This is the output of jstack: 
```java
"main" #1 prio=5 os_prio=0 tid=0x00007f65d400d800 nid=0x24228 waiting on condition [0x00007f65db60a000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000726b33bc0> (a java.util.concurrent.CompletableFuture$Signaller)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1707)
	at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
	at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1742)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)
	at io.quarkus.runner.RuntimeClassLoader.findClass(RuntimeClassLoader.java:214)
	at io.quarkus.runner.RuntimeClassLoader.loadClass(RuntimeClassLoader.java:179)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.objectweb.asm.ClassWriter.getCommonSuperClass(ClassWriter.java:935)
	at org.objectweb.asm.SymbolTable.addMergedType(SymbolTable.java:1200)
	at org.objectweb.asm.Frame.merge(Frame.java:1299)
	at org.objectweb.asm.Frame.merge(Frame.java:1197)
	at org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1607)
	at org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1543)
	at org.objectweb.asm.ClassReader.readCode(ClassReader.java:2431)
	at org.objectweb.asm.ClassReader.readThis is causeMethod(ClassReader.java:1283)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:688)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:400)
	at io.quarkus.hibernate.orm.deployment.HibernateEntityEnhancer$HibernateEnhancingClassVisitor.visitEnd(HibernateEntityEnhancer.java:67)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:692)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:400)
	at io.quarkus.runner.RuntimeClassLoader.handleTransform(RuntimeClassLoader.java:430)
	at io.quarkus.runner.RuntimeClassLoader.findClass(RuntimeClassLoader.java:225)
	at io.quarkus.runner.RuntimeClassLoader.loadClass(RuntimeClassLoader.java:179)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at io.quarkus.hibernate.orm.runtime.service.FlatClassLoaderService.classForName(FlatClassLoaderService.java:36)
	at org.hibernate.boot.model.source.internal.annotations.AnnotationMetadataSourceProcessorImpl.<init>(AnnotationMetadataSourceProcessorImpl.java:109)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess$1.<init>(MetadataBuildingProcess.java:155)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:149)
	at io.quarkus.hibernate.orm.runtime.boot.FastBootMetadataBuilder.build(FastBootMetadataBuilder.java:342)
	at io.quarkus.hibernate.orm.runtime.PersistenceUnitsHolder.createMetadata(PersistenceUnitsHolder.java:111)
	at io.quarkus.hibernate.orm.runtime.PersistenceUnitsHolder.constructMetadataAdvance(PersistenceUnitsHolder.java:84)
	at io.quarkus.hibernate.orm.runtime.PersistenceUnitsHolder.initializeJpa(PersistenceUnitsHolder.java:47)
	at io.quarkus.hibernate.orm.runtime.HibernateOrmRecorder$4.created(HibernateOrmRecorder.java:75)
	at io.quarkus.arc.runtime.ArcRecorder.initBeanContainer(ArcRecorder.java:101)
	at io.quarkus.deployment.steps.ArcProcessor$generateResources25.deploy_0(ArcProcessor$generateResources25.zig:406)
	at io.quarkus.deployment.steps.ArcProcessor$generateResources25.deploy(ArcProcessor$generateResources25.zig:36)
	at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:378)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:152)
	at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:178)
	- locked <0x00000005d3e2ea78> (a io.quarkus.dev.DevModeMain)
	at io.quarkus.dev.DevModeMain.start(DevModeMain.java:96)
	at io.quarkus.dev.DevModeMain.main(DevModeMain.java:67)
```

**To Reproduce**
1. Unzip the project in [jpa-example.zip](https://github.com/quarkusio/quarkus/files/3948053/jpa-example.zip)
2. run `mvn compile quarkus:dev`
3. Output should freeze after the following output is displayed: 
```
[INFO] Launching JVM with command line: /home/ggastald/.sdkman/candidates/java/8.0.232-open/jre/bin/java -XX:TieredStopAtLevel=1 -Xverify:none -Xdebug -Xrunjdwp:transport=dt_socket,address=5005,server=y,suspend=n -Djava.util.logging.manager=org.jboss.logmanager.LogManager -jar /tmp/jpa-example/target/jpa-example-dev.jar
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `Linux ggastald-laptop 5.3.14-300.fc31.x86_64 #1 SMP Mon Dec 2 15:41:35 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
 - Output of `java -version`: 
```
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)

```
 - GraalVM version (if different from Java):  Not used
 - Quarkus version or git rev: 1.1.0.CR1

**Additional context**
Look at the jstack output to find where the problem is. HINT: recursion in RuntimeClassloader

### PR DESCRIPTION
**Pull request by stuartwdouglas**
Fixes #6091

Using the RuntimeRunner itself can result in deadlocks
as it may try and load a class that is already in the
process of being loaded.

### CODE REVIEW

File: core/deployment/src/main/java/io/quarkus/runner/RuntimeClassLoader.java [hunk 1]
```diff
@@ -207,11 +206,15 @@ public InputStream getResourceAsStream(String nm) {
...
+            LoadingClass res = new LoadingClass(new CompletableFuture<>(), Thread.currentThread());
+            LoadingClass loadingClass = loadingClasses.putIfAbsent(name, res);
             if (loadingClass != null) {
+                if (loadingClass.initiator == Thread.currentThread()) {
+                    throw new LinkageError(
+                            "Load caused recursion in RuntimeClassLoader, this is a Quarkus bug loading class: " + name);
+                }
                 try {
-                    return loadingClass.get();
+                    return loadingClass.value.get();
```
Comment (gastaldi) [inline core/deployment/src/main/java/io/quarkus/runner/RuntimeClassLoader.java]: Maybe it would be nice to use the `get` method that accepts a timeout here to definitely avoid hanging?

**Comment by gastaldi** [comment]
I can confirm that this PR fixes #6091

**Review by gastaldi — APPROVED** [review]

File: core/deployment/src/main/java/io/quarkus/runner/RuntimeClassLoader.java [hunk 2]
```diff
@@ -422,7 +426,12 @@ private String getPackageNameFromClassName(String className) {
         }
 
         ClassReader cr = new ClassReader(bytes);
-        ClassWriter writer = new QuarkusClassWriter(cr, ClassWriter.COMPUTE_FRAMES | ClassWriter.COMPUTE_MAXS);
+        ClassWriter writer = new ClassWriter(cr, ClassWriter.COMPUTE_FRAMES | ClassWriter.COMPUTE_MAXS) {
```
Comment (gastaldi) [inline core/deployment/src/main/java/io/quarkus/runner/RuntimeClassLoader.java]: In order to avoid creating anonymous classes, it would be nice to introduce a new constructor to `QuarkusClassWriter` that takes a ClassLoader (defaulting to `Thread.currentThread().getContextClassLoader()`)

Comment (stuartwdouglas) [reply core/deployment/src/main/java/io/quarkus/runner/RuntimeClassLoader.java]: It's not necessarily the same thing, as the TCCL at creation might not match the TCCL at usage. I am not sure if all the current usages would be safe.

Comment (gastaldi) [reply core/deployment/src/main/java/io/quarkus/runner/RuntimeClassLoader.java]: `return this.cl==null? Thread.currentThread().getContextClassLoader(): cl`?
