### PR TITLE
Fix OIDC Dev UI paths when application root path is configured

### LINKED ISSUE #48772: OpenId Connect Dev Console fails when setting quarkus.http.root-path
### Describe the bug

We want to set `quarkus.http.root-path` since we're putting our application behind a reverse proxy.
We also want to use the OpenId Connect Dev Console.

Unfortunately it seems the latter breaks when we set the former.
The resulting error is:

```
2025-07-04 10:23:11,857 ERROR [io.ver.ext.web.RoutingContext] (vert.x-eventloop-thread-4) Unhandled exception in router: io.quarkus.security.AuthenticationFailedException
        at io.quarkus.oidc.runtime.DefaultTokenStateManager.decryptToken(DefaultTokenStateManager.java:247)
        at io.quarkus.oidc.runtime.DefaultTokenStateManager.getTokens(DefaultTokenStateManager.java:119)
        at io.quarkus.oidc.runtime.DefaultTokenStateManager_ClientProxy.getTokens(Unknown Source)
        at io.quarkus.oidc.runtime.dev.ui.OidcDevSessionCookieReaderHandler.handle(OidcDevSessionCookieReaderHandler.java:26)
        at io.quarkus.oidc.runtime.dev.ui.OidcDevSessionCookieReaderHandler.handle(OidcDevSessionCookieReaderHandler.java:14)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1283)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
        at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:205)
        at io.quarkus.vertx.http.runtime.filters.accesslog.AccessLogHandler.handle(AccessLogHandler.java:147)
        at io.quarkus.vertx.http.runtime.filters.accesslog.AccessLogHandler.handle(AccessLogHandler.java:94)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1283)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
        at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:205)
        at io.vertx.ext.web.impl.RouterImpl.handleContext(RouterImpl.java:251)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1283)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:151)
        at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup.handleHotReplacementRequest(VertxHttpHotReplacementSetup.java:146)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$HotReplacementRoutingContextHandler.handle(VertxHttpRecorder.java:1714)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$HotReplacementRoutingContextHandler.handle(VertxHttpRecorder.java:1704)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1283)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:151)
        at io.vertx.ext.web.impl.RoutingContextImpl.route(RoutingContextImpl.java:100)
        at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:69)
        at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:37)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$7.handle(VertxHttpRecorder.java:537)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$7.handle(VertxHttpRecorder.java:534)
        at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$2.handle(HttpServerCommonHandlers.java:87)
        at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$2.handle(HttpServerCommonHandlers.java:70)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$1.handle(VertxHttpRecorder.java:187)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$1.handle(VertxHttpRecorder.java:161)
        at io.vertx.core.impl.ContextImpl.emit(ContextImpl.java:342)
        at io.vertx.core.impl.DuplicatedContext.emit(DuplicatedContext.java:163)
        at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:174)
        at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:159)
        at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:153)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:289)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1357)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:868)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:796)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:732)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:998)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.NullPointerException: Cannot invoke "io.quarkus.oidc.runtime.TenantConfigContext.getSessionCookieEncryptionKey()" because "configContext" is null
        at io.quarkus.oidc.runtime.DefaultTokenStateManager.decryptToken(DefaultTokenStateManager.java:245)
        ... 61 more
```

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by michalvavrik**
- closes: https://github.com/quarkusio/quarkus/issues/48772

### CODE REVIEW

File: extensions/oidc/deployment/src/main/resources/dev-ui/qwc-oidc-provider.js [hunk 1]
```diff
@@ -499,7 +504,12 @@ export class QwcOidcProvider extends QwcHotReloadElement {
     }
 
     static _toServiceUrl(servicePath) {
-        return "http://localhost:" + propertiesState.httpPort + servicePath;
+        let rootUrl = 'http://localhost:' + propertiesState.httpPort + (propertiesState.rootPath ?? '');
```
Comment (sberyozkin) [inline extensions/oidc/deployment/src/main/resources/dev-ui/qwc-oidc-provider.js]: @michalvavrik Hi Michal, if I understand it correctly, the root path is not problem for a Keycloak or lightweight OIDC based DevUI, as far as users are concerned who enter the service path manually, they know what the endpoint address is, whether the root path is configured and is part of address is not important.
I.e it can be `/hello` or `/some-root/hello` - this is what users type.
But this change will now require them to type `/hello` where the endpoint address is actually `/some-root/hello`...

My understanding the problem is related to how the lightweight OIDC DevUI handlers deal with the situation when the root path is configured

Comment (michalvavrik) [reply extensions/oidc/deployment/src/main/resources/dev-ui/qwc-oidc-provider.js]: I did reproduce and fix the problem (by this PR). If you say that this portion - service path not having a root path is fine, I'll drop it. I don't mind, it doesn't really seems logical to me, but I think we should go with whatever you believe is correct behavior. I'll push it in few minutes.

Comment (michalvavrik) [reply extensions/oidc/deployment/src/main/resources/dev-ui/qwc-oidc-provider.js]: > But this change will now require them to type /hello where the endpoint address is actually /some-root/hello...

In other words, the endpoint is `/hello`, because it cannot be `/something-else/hello` or `whatever/hello` it must be `/some-root/`, not sure why they would like to repeat it over and over again. Anyway, as agreed I am going to drop this part.

Comment (michalvavrik) [reply extensions/oidc/deployment/src/main/resources/dev-ui/qwc-oidc-provider.js]: Done. IMO the default service path shouldn't be `/` but it should be a root path instead, but that doesn't belong to this PR as this PR is a bug fix. (aka we should prefill that input with `/` or `/some-root/` for users so that they only add `/hello` but see both the root and the hello in one input as it will be a one string)

Comment (sberyozkin) [reply extensions/oidc/deployment/src/main/resources/dev-ui/qwc-oidc-provider.js]: Hi Michal, sorry I signed off yesterday, 

>aka we should prefill that input with / or /some-root/ for users so that they only add /hello but see both the root and the hello in one input as it will be a one string

It is not how things work when users interact with the endpoint at the browser level. The configured root path may or may not contribute to `/path/hello`, the root path can be `/` or `/path`, it does not matter. Users work with the available endpoint URL space and they do not expect something be prefilled in the request URL

Comment (sberyozkin) [reply extensions/oidc/deployment/src/main/resources/dev-ui/qwc-oidc-provider.js]: @michalvavrik For example, in OIDC DevUI, if SwaggerUI is available, it will return complete paths, so if one has to add `/hello` manually, but test `/path/hello` in SwaggerUI, than it would be confusing

**Review by sberyozkin — APPROVED** [review]
Thanks Michal

File: extensions/oidc/deployment/src/main/resources/dev-ui/qwc-oidc-provider.js (hunk 1 above)
Comment (michalvavrik) [reply extensions/oidc/deployment/src/main/resources/dev-ui/qwc-oidc-provider.js]: > @michalvavrik For example, in OIDC DevUI, if SwaggerUI is available, it will return complete paths, so if one has to add `/hello` manually, but test `/path/hello` in SwaggerUI, than it would be confusing

good point, let's keep current state then.
