### PR TITLE
Store EntityManager per unit in TransactionSynchronizationRegistry

### LINKED ISSUE #12804: Cannot use multiple persistence units in same transaction
**Describe the bug**
Given two Java packages configured in two separate persistence units, it is not possible to query entities in both of them within the same transaction. The query for the second persistence unit will always fail, while the first one works (i.e. no matter which PU is queried first, the other will fail). Querying the PUs outside of a transaction succeeds, though.

**Expected behavior**
It should be possible to query two different persistence units within the same transaction. 

**Actual behavior**
The second query always fails with `java.lang.IllegalArgumentException: Could not locate ordinal parameter [1], expecting one of []`

**To Reproduce**
[panache-multipe-persistence-units.zip](https://github.com/quarkusio/quarkus/files/5403827/panache-multipe-persistence-units.zip)
1. unzip above archive (code is based on hibernate-orm-panache-quickstart)
2. invoke `mvn test`
3. see test class fail in `org.acme.hibernate.orm.panache.MultiPersistenceUnitTest.testBothQueriesInTx()`, while tests doing the same outside of a transaction succeed

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin C02Z74E4LVDQ 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64
 - Output of `java -version`: OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.4+11, mixed mode)
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.8.3-Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3

### PR DESCRIPTION
**Pull request by jfrantzius**
Fix #12804

### CODE REVIEW

File: extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/entitymanager/TransactionScopedEntityManager.java [hunk 1]
```diff
@@ -34,7 +34,7 @@
     private final TransactionSynchronizationRegistry tsr;
     private final EntityManagerFactory emf;
     private final String unitName;
-    private static final Object transactionKey = new Object();
+    private final Object unitEntityManagerInTxKey = new Object();
```
Comment (gsmet) [inline extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/entitymanager/TransactionScopedEntityManager.java:37]: I have a slightly different fix where I build a String key from the class simple name + ":" + the unit name in the constructor and use that.

It also fixes the issue and I think that's more in line with what we used to do.

If it makes sense to you, could you adjust your patch?

Comment (jfrantzius) [reply extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/entitymanager/TransactionScopedEntityManager.java:37]: yes, give me a sec ...

**Review by gsmet — APPROVED** [review]
I squashed your 2 commits and pushed my cleanup on top of it (it's mostly about renaming the variables for more clarity: the code was a bit like dark magic if you're not used to the terms we use).

Let's wait for CI and merge. I will backport this to 1.9.1.Final (should be released in about a week).

Thanks for tracking this issue!
