### PR TITLE
Ensure that Transformations always happen in a safe CL

### LINKED ISSUE #5878: Test instantiation exception with multicatch
**Describe the bug**

I have code that uses a multi-catch , which works nicely with `mvn compile quarkus:dev`, but fails when stating Quarkus as part of a test with `@Quarkustest`

The server shows

```
org.junit.jupiter.api.extension.TestInstantiationException: TestInstanceFactory [io.quarkus.test.junit.QuarkusTestExtension] failed to instantiate test class [com.redhat.cloud.custompolicies.engine.PolicyEvalTest]
Caused by: java.lang.ExceptionInInitializerError
Caused by: java.lang.RuntimeException: Failed to start quarkus
Caused by: java.lang.RuntimeException: Failed to initialize Arc
Caused by: java.lang.VerifyError: 
Bad type on operand stack
Exception Details:
  Location:
    com/redhat/cloud/custompolicies/engine/RestApi.verifyPolicy(Lcom/redhat/cloud/custompolicies/engine/model/Policy;)Ljavax/ws/rs/core/Response; @22: invokevirtual
  Reason:
    Type 'java/lang/Object' (current frame, stack[2]) is not assignable to 'java/lang/RuntimeException'
  Current Frame:
    bci: @22
    flags: { }
    locals: { 'com/redhat/cloud/custompolicies/engine/RestApi', 'com/redhat/cloud/custompolicies/engine/model/Policy', top, 'java/lang/Object' }
    stack: { uninitialized 17, uninitialized 17, 'java/lang/Object' }
  Bytecode:
    0x0000000: bb00 0a59 2bb7 0014 57b8 000c 4da7 0021
    0x0000010: 4ebb 0016 592d b600 17b7 0018 3a04 1101
    0x0000020: 9c2d b600 17b8 0019 1904 b600 0e4d 2c12
    0x0000030: 1b12 1cb6 001d 572c b600 0fb0          
  Exception Handler Table:
    bci [0, 13] => handler: 16
    bci [0, 13] => handler: 16
  Stackmap Table:
    same_locals_1_stack_item_frame(@16,Object[#56])
    append_frame(@46,Object[#118])
```

Source is like (full code is at https://github.com/pilhuhn/custom-policies-engine/blob/test-sys-profile/src/main/java/com/redhat/cloud/custompolicies/engine/RestApi.java#L93 )

```
  public Response verifyPolicy(Policy policy) {

    Response.ResponseBuilder builder;
    try {
      new PolicyParser(policy);
      builder = Response.noContent();
//    } catch (Exception ie) {
    } catch (IllegalArgumentException|IllegalStateException ie) {
      Msg msg = new Msg(ie.getMessage());
```

When I replace the line with multi-catch with the simple catch in the commented line above,
all works normally.

This is with 1.0.0.Final and .CR2

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
Darwin snert 18.7.0 Darwin Kernel Version 18.7.0: Sat Oct 12 00:02:19 PDT 2019; root:xnu-4903.278.12~1/RELEASE_X86_64 x86_64

 - Output of `java -version`: 

java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

 - GraalVM version (if different from Java): 

not used.

### PR DESCRIPTION
**Pull request by geoand**
Fixes #5878

Note: This is a temporary solution in any case since
ClassLoaders will be dealt with in a more holistic
manner soon.

All credits go to @stuartwdouglas for this

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]

File: test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java [hunk 1]
```diff
@@ -190,7 +190,8 @@ public URL getResource(String name) {
 
                                         @Override
                                         protected ClassLoader getClassLoader() {
-                                            return temp;
```
Comment (stuartwdouglas) [inline test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java]: Do we still need this class? Can it just use QuarkusClassWriter?

Comment (geoand) [reply test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java]: Yeah we do unfortunately need to override the method here because the TCCL at the time this executed has been changed to `temp`.
On the other hand if you are asking if we absolutely need `QuarkusClassWriter` since we aren't actually using it's method, the answer is no, we don't, we could just use a regular `ClassWriter`. But I think keeping it around will make finding the transformation usages easier since all you have to do is see where `QuarkusClassWriter` is being used. 
WDYT?

**Review by stuartwdouglas — APPROVED** [review]

**Comment by stuartwdouglas** [comment]
There was an intermittent failure that appears to be caused by https://github.com/oracle/graal/issues/1927
