### PR TITLE
fix Jaeger metrics initialization

### LINKED ISSUE #8578: OpenTracing quickstart native build failing
The OpenTracing quickstart native build is failing with current Quarkus master + quickstart development branch:

https://github.com/quarkusio/quarkus-quickstarts/runs/586602480?check_suite_focus=true
```
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: io.quarkus.jaeger.runtime.QuarkusJaegerMetricsFactory.<init>(). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
Trace: 
	at parsing io.quarkus.jaeger.runtime.QuarkusJaegerTracer.tracer(QuarkusJaegerTracer.java:45)
Call path from entry point to io.quarkus.jaeger.runtime.QuarkusJaegerTracer.tracer(): 
	at io.quarkus.jaeger.runtime.QuarkusJaegerTracer.tracer(QuarkusJaegerTracer.java:42)
	at io.quarkus.jaeger.runtime.QuarkusJaegerTracer.toString(QuarkusJaegerTracer.java:31)
	at java.lang.String.valueOf(String.java:2994)
	at java.nio.charset.IllegalCharsetNameException.<init>(IllegalCharsetNameException.java:55)
	at java.nio.charset.Charset.checkName(Charset.java:315)
	at com.oracle.svm.core.jdk.Target_java_nio_charset_Charset.lookup(CharsetSubstitutions.java:78)
	at java.nio.charset.Charset.isSupported(Charset.java:505)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_ARRAY:Ljava_nio_charset_Charset_2_0002eisSupported_00028Ljava_lang_String_2_00029Z(generated:0)
```

### PR DESCRIPTION
**Pull request by Ladicek**
Creation of the correct `MetricsFactory` was moved from runtime
to build time, which also means that it's created during native
image compilation. Therefore, the MicroProfile Metrics API and
SmallRye Metrics are not required to be present at runtime.
Which, in the end, means that native image compilation no longer
fails when the `quarkus-smallrye-opentracing` extension is present
but `quarkus-smallrye-metrics` is not.

Resolves #8578.

### CODE REVIEW

**Comment by Ladicek** [comment]
Draft because waiting for CI to finish in my fork.

File: extensions/jaeger/deployment/src/main/java/io/quarkus/jaeger/deployment/JaegerProcessor.java [hunk 1]
```diff
@@ -29,8 +32,11 @@ void setupTracer(JaegerDeploymentRecorder jdr, JaegerBuildTimeConfig buildTimeCo
 
         if (buildTimeConfig.enabled) {
             boolean metricsEnabled = capabilities.isCapabilityPresent(Capabilities.METRICS);
+            MetricsFactory metricsFactory = metricsEnabled
+                    ? new QuarkusJaegerMetricsFactory()
+                    : new NoopMetricsFactory();
 
-            jdr.registerTracer(jaeger, appConfig, metricsEnabled);
+            jdr.registerTracer(jaeger, appConfig, metricsFactory);
```
Comment (gsmet) [inline extensions/jaeger/deployment/src/main/java/io/quarkus/jaeger/deployment/JaegerProcessor.java:39]: I would keep passing the boolean and initialize the class in the recorder. I think it would work the same and be a bit less confusing.

The recorder method wouldn't be called so the class wouldn't be accessible either.

(Just guessing, you would need to try)

**Review by gsmet — DISMISSED** [review]

File: extensions/jaeger/deployment/src/main/java/io/quarkus/jaeger/deployment/JaegerProcessor.java (hunk 1 above)
Comment (Ladicek) [reply extensions/jaeger/deployment/src/main/java/io/quarkus/jaeger/deployment/JaegerProcessor.java:39]: But that's exactly how it used to be before, and it was failing :-)

What might work is to have 2 recorder methods, 1 for disabled metrics and 1 for enabled metrics. I guess.

Comment (geoand) [reply extensions/jaeger/deployment/src/main/java/io/quarkus/jaeger/deployment/JaegerProcessor.java:39]: I am personally fine with the approach of the PR, IMHO this is what the bytecode recording is all about - being able to easily "pass" objects from build time to runtime.

Comment (gsmet) [reply extensions/jaeger/deployment/src/main/java/io/quarkus/jaeger/deployment/JaegerProcessor.java:39]: No, it used to be done in `QuarkusJaegerTracer` based on a dynamic value and in a method called at runtime.

I won't fight for it but I prefer when it's clear a runtime object is a runtime object.

Comment (Ladicek) [reply extensions/jaeger/deployment/src/main/java/io/quarkus/jaeger/deployment/JaegerProcessor.java:39]: Ah, I think I see what you mean now. I'll try.

Comment (Ladicek) [reply extensions/jaeger/deployment/src/main/java/io/quarkus/jaeger/deployment/JaegerProcessor.java:39]: Or perhaps not. I have changed `JaegerProcessor` to be

```java
boolean metricsEnabled = capabilities.isCapabilityPresent(Capabilities.METRICS);

jdr.registerTracer(jaeger, appConfig, metricsEnabled);
```

just like before, and then change the `JaegerDeploymentRecorder` to have this:

```java
MetricsFactory metricsFactory = metricsEnabled
        ? new QuarkusJaegerMetricsFactory()
        : new NoopMetricsFactory();

initTracerConfig(jaeger);
quarkusTracer.setMetricsFactory(metricsFactory);
quarkusTracer.reset();
```

But no, this leads to the same failure as before.

I'll try the approach with 2 recorder methods.

Comment (gsmet) [reply extensions/jaeger/deployment/src/main/java/io/quarkus/jaeger/deployment/JaegerProcessor.java:39]: OK, well, let's leave it at that then. It's not worth your time.

Comment (Ladicek) [reply extensions/jaeger/deployment/src/main/java/io/quarkus/jaeger/deployment/JaegerProcessor.java:39]: The approach with 2 recorder method works:

```java
boolean metricsEnabled = capabilities.isCapabilityPresent(Capabilities.METRICS);

if (metricsEnabled) {
    jdr.registerTracerWithMetrics(jaeger, appConfig);
} else {
    jdr.registerTracer(jaeger, appConfig);
}
```

and

```java
synchronized public void registerTracer(JaegerConfig jaeger, ApplicationConfig appConfig) {
    registerTracer(jaeger, appConfig, new NoopMetricsFactory());
}

synchronized public void registerTracerWithMetrics(JaegerConfig jaeger, ApplicationConfig appConfig) {
    registerTracer(jaeger, appConfig, new QuarkusJaegerMetricsFactory());
}

private void registerTracer(JaegerConfig jaeger, ApplicationConfig appConfig, MetricsFactory metricsFactory) {
    ...
}
```

And I think it's certainly worth my time, as I get to learn a lot!

**Review by geoand — APPROVED** [review]
LGTM!

File: extensions/jaeger/deployment/src/main/java/io/quarkus/jaeger/deployment/JaegerProcessor.java (hunk 1 above)
Comment (Ladicek) [reply extensions/jaeger/deployment/src/main/java/io/quarkus/jaeger/deployment/JaegerProcessor.java]: I have modified the PR to use the approach with 2 recorder methods and currently waiting for CI to finish in my fork.

**Comment by Ladicek** [comment]
Un-WIP-ing, as CI passed in my fork (except one unrelated failure).

**Comment by geoand** [comment]
Test failure:

```
2020-04-15T14:41:08.3775762Z [ERROR] Failures: 
2020-04-15T14:41:08.3777171Z [ERROR]   AmazonLambdaSimpleTestCase.testGetText:22->testGetText:38 expected: <500> but was: <200>
2020-04-15T14:41:08.3777476Z [ERROR]   AmazonLambdaSimpleTestCase.testPostText:56->testPostText:67 expected: <500> but was: <200>
```

is irrelevant

**Comment by Ladicek** [comment]
Thanks!

**Comment by geoand** [comment]
Thanks for fixing this!
