### PR TITLE
MeterTagsSupport: prevent null metric tag values

### LINKED ISSUE #47891: NPE when ValueExpressionResolver returns null
### Describe the bug

`ValueExpressionResolver.resolve()` has been explicitly annotated with `@Nullable` in Micrometer 1.11.8:

https://github.com/micrometer-metrics/micrometer/issues/4094

But in Quarkus, this doesn't work as it would throw a NPE here:

https://github.com/quarkusio/quarkus/blob/176741713b172d7bf08343e8837d1cb129961c2b/extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/MeterTagsSupport.java#L50-L52

I was wondering if we could instead skip creating a `Tag` when the resolver returns null.

### Expected behavior

NPE is thrown when the resolver gets invoked.

### Actual behavior

Application should behave normally, metric tag should not be included if the resolver returns null.

### How to Reproduce?

```java
@ApplicationScoped
public class MyValueExpressionResolver implements ValueExpressionResolver {
  @Override
  public String resolve(@Nonnull String expression, @Nullable Object parameter) {
    return null;
  }
}
```

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by adutra**
This situation can happen when `ValueExpressionResolver.resolve()` returns null. The fix is to return an empty string instead.

Fixes #47891

### CODE REVIEW

File: extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/MeterTagsSupport.java [hunk 1]
```diff
@@ -66,19 +66,19 @@ private static Tags getCommonTags(ArcInvocationContext context) {
...
             }
-            return valueExpressionResolver.resolve(annotation.expression(), parameterValue);
+            value = valueExpressionResolver.resolve(annotation.expression(), parameterValue);
         } else if (parameterValue != null) {
-            return parameterValue.toString();
-        } else {
-            return "";
+            value = parameterValue.toString();
         }
+        return value == null ? "" : value;
```
Comment (adutra) [inline extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/MeterTagsSupport.java:81]: See https://github.com/micrometer-metrics/micrometer/blob/46a674e1501fda095e774c40069434240f397956/micrometer-core/src/main/java/io/micrometer/core/aop/MeterTagSupport.java#L47

**Review by brunobat — APPROVED** [review]
