### PR TITLE
Reset junit test's extension failed state for each test class

### LINKED ISSUE #37809: [Quarkus main] integration test 'main' fails in native mode: QuarkusTestCallbacksITCase.testCallbackContextIsNotFailed
### Describe the bug

We see this failure with various Mandrel versions. 23.1, 22.3 and Graal master:

```
Error:  Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.015 s <<< FAILURE! -- in io.quarkus.it.main.QuarkusTestCallbacksITCase
Error:  io.quarkus.it.main.QuarkusTestCallbacksITCase.testCallbackContextIsNotFailed -- Time elapsed: 0.003 s <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <false> but was: <true>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertFalse.failNotFalse(AssertFalse.java:63)
	at org.junit.jupiter.api.AssertFalse.assertFalse(AssertFalse.java:36)
	at org.junit.jupiter.api.AssertFalse.assertFalse(AssertFalse.java:31)
	at org.junit.jupiter.api.Assertions.assertFalse(Assertions.java:231)
	at io.quarkus.it.main.QuarkusTestCallbacksITCase.testCallbackContextIsNotFailed(QuarkusTestCallbacksITCase.java:61)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

22.3 failure: https://github.com/graalvm/mandrel/actions/runs/7247202176/job/19741555739?pr=638#step:12:651
23.1 failure: https://github.com/graalvm/mandrel/actions/runs/7228893522/job/19699470818#step:12:706
Graal master failure: https://github.com/graalvm/mandrel/actions/runs/7242468774/job/19728465877#step:12:688

### PR DESCRIPTION
**Pull request by zakkak**
Fix Quarkus TestExtensions to avoid mistakenly transferring the failed
state of one test class to the other.

Closes https://github.com/quarkusio/quarkus/issues/37809

Tests with Mandrel 24.0-dev https://github.com/graalvm/mandrel/actions/runs/7476057769

### CODE REVIEW

File: test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusIntegrationTestExtension.java [hunk 1]
```diff
@@ -146,8 +146,14 @@ private QuarkusTestExtensionState ensureStarted(ExtensionContext extensionContex
...
         boolean wrongProfile = !Objects.equals(selectedProfile, quarkusTestProfile);
+        // we reset the failed state if we changed test class
+        boolean resetFailedState = !Objects.equals(extensionContext.getRequiredTestClass(), currentJUnitTestClass);
+        if (resetFailedState && state != null) {
+            state.setTestFailed(null);
+            currentJUnitTestClass = extensionContext.getRequiredTestClass();
+        }
         // we reload the test resources if we changed test class and if we had or will have per-test test resources
-        boolean reloadTestResources = !Objects.equals(extensionContext.getRequiredTestClass(), currentJUnitTestClass)
+        boolean reloadTestResources = resetFailedState
```
Comment (geoand) [inline test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusIntegrationTestExtension.java:156]: This is kind of deceiving in appearances TBH because whether or not `reloadTestResources` is set to true, is not theorically equivalent to setting `resetFailedState` to `true`. 

So I would just keep this line the want it was.

Comment (geoand) [reply test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusIntegrationTestExtension.java:156]: If you want to avoid code duplication what I would do is introduce 👍🏼 

```java
boolean isNewTestClass = !Objects.equals(extensionContext.getRequiredTestClass(), currentJUnitTestClass);
        if (resetFailedState && state != null) {
```

and use that to set `resetFailedState` and `reloadTestResources`

File: test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java [hunk 2]
```diff
@@ -586,10 +586,15 @@ private QuarkusTestExtensionState ensureStarted(ExtensionContext extensionContex
         QuarkusTestExtensionState state = getState(extensionContext);
         Class<? extends QuarkusTestProfile> selectedProfile = getQuarkusTestProfile(extensionContext);
         boolean wrongProfile = !Objects.equals(selectedProfile, quarkusTestProfile);
+        // we reset the failed state if we changed test class and the new test class is not a nested class
+        boolean resetFailedState = !Objects.equals(extensionContext.getRequiredTestClass(), currentJUnitTestClass)
+                && !isNested(currentJUnitTestClass, extensionContext.getRequiredTestClass());
+        if (resetFailedState && state != null) {
+            state.setTestFailed(null);
+            currentJUnitTestClass = extensionContext.getRequiredTestClass();
+        }
```
Comment (geoand) [inline test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java:595]: Same comments here as above

File: test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusIntegrationTestExtension.java (hunk 1 above)
Comment (zakkak) [reply test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusIntegrationTestExtension.java]: Good point. Done.

File: test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java (hunk 2 above)
Comment (zakkak) [reply test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java]: Done

**Review by geoand — APPROVED** [review]
Thanks!

**Comment by zakkak** [comment]
I can reproduce the above issues with `main` locally, but I don't see them appearing in the Quarkus CI in https://github.com/quarkusio/quarkus/actions/runs/7466758136 so I am not sure if the failures are related or not :/

**Comment by zakkak** [comment]
> The fact that we don't get any passing JVM build is troubling

And it's also persistent so it's clearly related to the patch.

**Comment by gsmet** [comment]
It looks a bit related to what I was struggling with here: https://github.com/quarkusio/quarkus/pull/36356

**Comment by zakkak** [comment]
Interestingly, the tests fail even if I don't actually touch the state (https://github.com/zakkak/quarkus/commit/497776427eeddbb9016efe04cbdf80ae32442fa1)!

**Comment by geoand** [comment]
I will take a quick look

**Comment by geoand** [comment]
Hopefully https://github.com/quarkusio/quarkus/pull/38238 should fix it

**Comment by zakkak** [comment]
> Hopefully #38238 should fix it

Thanks @geoand, I am giving it a go in https://github.com/zakkak/quarkus/actions/runs/7556725913

**Comment by zakkak** [comment]
@geoand it works!

**Comment by geoand** [comment]
🥂

**Comment by geoand** [comment]
😱

**Comment by geoand** [comment]
Try rebasing onto `main` please

**Review by geoand — APPROVED** [review]
