### PR TITLE
Replace use of shell syntax for dates with extended JSON syntax

### LINKED ISSUE #11524: NullPointerException reading mongodb bson date (native image)
Hi,

only native image of my application cause  a NullPointerException parsing mongodb document with date field.

The error occours both with quarkus 1.6.0.final and 1.7.0.final. 

Here the full staktrace:
```
2020-08-21 15:12:12,711 ERROR [org.jbo.res.res.i18n] (executor-thread-1) RESTEASY002020: Unhandled asynchronous exception, sending back 500: org.jboss.resteasy.spi.ApplicationException: java.lang.NullPointerException
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:180)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:638)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:504)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:454)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:456)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:417)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:391)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:68)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:488)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:259)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:160)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:163)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:245)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:132)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:37)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:94)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
Caused by: java.lang.NullPointerException
	at java.text.SimpleDateFormat.matchZoneString(SimpleDateFormat.java:1695)
	at java.text.SimpleDateFormat.subParseZoneString(SimpleDateFormat.java:1763)
	at java.text.SimpleDateFormat.subParse(SimpleDateFormat.java:2169)
	at java.text.SimpleDateFormat.parse(SimpleDateFormat.java:1541)
	at org.bson.json.JsonReader.visitISODateTimeConstructor(JsonReader.java:836)
	at org.bson.json.JsonReader.readBsonType(JsonReader.java:225)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:85)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:42)
	at org.bson.codecs.BsonDocumentCodec.readValue(BsonDocumentCodec.java:104)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:87)
	at org.bson.BsonDocument.parse(BsonDocument.java:63)
	at io.quarkus.mongodb.panache.runtime.MongoOperations.executeUpdate(MongoOperations.java:619)
	at io.quarkus.mongodb.panache.runtime.MongoOperations.update(MongoOperations.java:614)
	at it.cineca.model.elaborato.HeartBeat.update(HeartBeat.java)
	at it.cineca.manager.HeartBeatManager.aggiornaBattito(HeartBeatManager.java:64)
	at it.cineca.manager.HeartBeatManager_ClientProxy.aggiornaBattito(HeartBeatManager_ClientProxy.zig:216)
	at it.cineca.web.BeatController.aggiornaBattito(BeatController.java:38)
	at java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:167)
	... 29 more
```
I'm compiling native image using maven's quarkus standard configuration with these Resource Configuration File:

```
{
  "bundles": [  {"name":"sun.util.resources.TimeZoneNames"}   ],
  "resources": [     {       "pattern": "org/joda/time/tz/data/.*/.*$"     },
                            {       "pattern": "org/joda/time/tz/data/.*$"     }   ]
}
```
Thank you
Nicola

### PR DESCRIPTION
**Pull request by jyemin**
Replace use of shell syntax for dates with extended JSON syntax

Fixes #11524

### CODE REVIEW

**Comment by gsmet** [comment]
I'm more in favor of fixing the issue like this: https://github.com/quarkusio/quarkus/pull/12479 .

Could you test this PR and see if it solves your issue?

**Comment by galderz** [comment]
@gsmet Why do you favour my fix? My fix is very hacky, and as pointed out by @jyemin, it could lead to not reading dates properly.

**Comment by galderz** [comment]
I can't really review this code since I'm not a MongoDB expert. @loicmathieu or other MongoDB experts are more suited here.

**Comment by gsmet** [comment]
@loicmathieu I let you check this one?

**Comment by loicmathieu** [comment]
Hi, I'm aware of this one but didn't know if it's a good thing or not.
Both should works and it's a workaround for a native image issue on the MongoDB driver side that has already been worked around but a substitution ...
So I'm still not decided wether it's worth it or not.

**Comment by gastaldi** [comment]
@loicmathieu so, yay or nay? :)

**Comment by loicmathieu** [comment]
@evanchooly when generating queries from PanacheQL to MongoDB bson query we format date using `ISODate`.
This PR propose to change this to `$date`.
I'm not sure it's better, WDYT ?

**Comment by evanchooly** [comment]
I don't know that I have an opinion.  It doesn't really seem to change the encoding of the actual value just how it's represented in the document.  There might be a reason on the server side for such a change (maybe the parsing is more robust/reliable/performant?).  But Jeff knows what he's doing so I have 0 problem deferring to his choice in the matter.

**Comment by loicmathieu** [comment]
OK, I'll review the PR then.

File: extensions/panache/mongodb-panache-common/runtime/src/main/java/io/quarkus/mongodb/panache/binder/CommonQueryBinder.java [hunk 1]
```diff
@@ -38,23 +38,9 @@ static String escape(Object value) {
...
-            return "ISODate('" + dateFormat.format(dateValue) + "')";
-        }
-        if (value instanceof LocalDate) {
-            LocalDate dateValue = (LocalDate) value;
-            return "ISODate('" + DateTimeFormatter.ISO_LOCAL_DATE.format(dateValue) + "')";
-        }
-        if (value instanceof LocalDateTime) {
-            LocalDateTime dateValue = (LocalDateTime) value;
-            return "ISODate('" + ISO_DATE_FORMATTER.format(dateValue.atZone(ZoneOffset.UTC)) + "')";
-        }
```
Comment (loicmathieu) [inline extensions/panache/mongodb-panache-common/runtime/src/main/java/io/quarkus/mongodb/panache/binder/CommonQueryBinder.java:54]: I'd rather keep the existing if chain than mutate the parameter to an Instant.
It feel strange to me as this methods accept a lot of different type and you mutate to an instant some of them

**Review by loicmathieu — CHANGES_REQUESTED** [review]

File: extensions/panache/mongodb-panache-common/runtime/src/main/java/io/quarkus/mongodb/panache/binder/CommonQueryBinder.java (hunk 1 above)
Comment (jyemin) [reply extensions/panache/mongodb-panache-common/runtime/src/main/java/io/quarkus/mongodb/panache/binder/CommonQueryBinder.java:54]: Yeah, I wasn't so pleased with it either.  But I also was trying to avoid repeating line 43 four times.

Please feel free to modify as you see fit.

Comment (loicmathieu) [reply extensions/panache/mongodb-panache-common/runtime/src/main/java/io/quarkus/mongodb/panache/binder/CommonQueryBinder.java:54]: @jyemin can you update your PR to keep the old if chain so I can merge it ?

Comment (jyemin) [reply extensions/panache/mongodb-panache-common/runtime/src/main/java/io/quarkus/mongodb/panache/binder/CommonQueryBinder.java]: Done

**Review by loicmathieu — APPROVED** [review]
LGTM, thanks for your patience !

**Comment by galderz** [comment]
Thx @jyemin for stepping up to help with the MongoDB issue, and @loicmathieu for the review :)

**Comment by jyemin** [comment]
It was my pleasure.  In the future please don't hesitate to @ mention me if any issues come up related to MongoDB support in Quarkus.

**Comment by loicmathieu** [comment]
> It was my pleasure.  In the future please don't hesitate to @ mention me if any issues come up related to MongoDB support in Quarkus.

Thanks. Will do.
