### PR TITLE
Properly read the value of testcontainers.reuse.enable

### LINKED ISSUE #30059: testcontainers.reuse.enable always set to false
### Describe the bug

When any Quarkus DevService is used, the property `testcontainers.reuse.enable` is always set to `false` in the `~/.testcontainers.properties` file, after starting in dev mode.

### Expected behavior

The property should not be changed by Quarkus.

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

At the following statement `oldReusePropertyValue` is always `false`.

https://github.com/quarkusio/quarkus/blob/6776f0deeb8537c5207ddb5ad08e7b3c5db83722/core/deployment/src/main/java/io/quarkus/deployment/IsDockerWorking.java#L90-L92

This has the effect, that its always set to `false` with:

https://github.com/quarkusio/quarkus/blob/6776f0deeb8537c5207ddb5ad08e7b3c5db83722/core/deployment/src/main/java/io/quarkus/deployment/IsDockerWorking.java#L103-L104

I think the issue should be solved when using the method `TestcontainersConfiguration#getEnvVarOrUserProperty` instead of `TestcontainersConfiguration#getUserProperty`. 

This because the method `TestcontainersConfiguration#getUserProperty` strangely ignores `TestcontainersConfiguration#userProperties`. Probably the name of the method `getUserProperty` is simply wrong.

### PR DESCRIPTION
**Pull request by geoand**
As mentioned by @LaunchPairs in the analysis of #30059, the use of `TestcontainersConfiguration#getUserProperty` results in using only environment variables as the source for reading the `testcontainers.reuse.enable`.
We should instead also read the value of `~/.testcontainers.properties` in order to ensure we write back the proper value when restoring

Fixes: #30059

### CODE REVIEW

File: core/deployment/src/main/java/io/quarkus/deployment/IsDockerWorking.java [hunk 1]
```diff
@@ -88,7 +88,7 @@ public Result get() {
                         .loadClass("org.testcontainers.utility.TestcontainersConfiguration");
                 Object configurationInstance = configurationClass.getMethod("getInstance").invoke(null);
                 String oldReusePropertyValue = (String) configurationClass
-                        .getMethod("getUserProperty", String.class, String.class)
+                        .getMethod("getEnvVarOrUserProperty", String.class, String.class)
```
Comment (geoand) [inline core/deployment/src/main/java/io/quarkus/deployment/IsDockerWorking.java:91]: There is also a case to be made in using `getEnvVarOrProperty` here, but let's be cautious and only broaden the scope a little instead of all the way

**Review by gastaldi — APPROVED** [review]

**Review by gsmet — APPROVED** [review]
