### PR TITLE
Make dev console work with BodyHandler

### LINKED ISSUE #14405: Dev UI - "Request has already been read" error when clearing cache if smallrye-graphql extension present
If the smallrye-graphql extension is present in my project, I have the following exception when clearing a cache using http://localhost:8080/q/dev/io.quarkus.quarkus-cache/caches:

```
 java.lang.IllegalStateException: Request has already been read
	at io.vertx.core.http.impl.HttpServerRequestImpl.checkEnded(HttpServerRequestImpl.java:593)
	at io.vertx.core.http.impl.HttpServerRequestImpl.setExpectMultipart(HttpServerRequestImpl.java:431)
	at io.quarkus.vertx.http.runtime.AbstractRequestWrapper.setExpectMultipart(AbstractRequestWrapper.java:193)
	at io.vertx.ext.web.impl.HttpServerRequestWrapper.setExpectMultipart(HttpServerRequestWrapper.java:286)
	at io.quarkus.devconsole.runtime.spi.DevConsolePostHandler.handle(DevConsolePostHandler.java:15)
	at io.quarkus.devconsole.runtime.spi.DevConsolePostHandler.handle(DevConsolePostHandler.java:11)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1038)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:137)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:132)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.doEnd(BodyHandlerImpl.java:296)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.end(BodyHandlerImpl.java:276)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl.lambda$handle$0(BodyHandlerImpl.java:87)
	at io.vertx.core.http.impl.HttpServerRequestImpl.onEnd(HttpServerRequestImpl.java:523)
	at io.vertx.core.http.impl.HttpServerRequestImpl.lambda$pendingQueue$1(HttpServerRequestImpl.java:117)
	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:237)
	at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:127)
```

I attached a reproducer. Just untar the project and run `mvn clean quarkus:dev` then go to http://localhost:8080/q/dev/io.quarkus.quarkus-cache/caches and clear the cache.

When smallrye-graphql is commented from the pom.xml, things are working as expected.
[quarkus-bot-java.tar.gz](https://github.com/quarkusio/quarkus/files/5838323/quarkus-bot-java.tar.gz)

### PR DESCRIPTION
**Pull request by stuartwdouglas**
Fixes #14405

### CODE REVIEW

**Review by geoand — APPROVED** [review]

File: extensions/vertx-http/dev-console-runtime-spi/src/main/java/io/quarkus/devconsole/runtime/spi/DevConsolePostHandler.java [hunk 1]
```diff
@@ -1,28 +1,49 @@
...
     @Override
     public void handle(RoutingContext event) {
-        event.request().setExpectMultipart(true);
-        event.request().endHandler(new Handler<Void>() {
-            @Override
-            public void handle(Void ignore) {
-                dispatch(event);
+        if (event.getBody() != null) {
+            //really simple form data decoder
+            //but we can't really re-use the netty one
```
Comment (mkouba) [inline extensions/vertx-http/dev-console-runtime-spi/src/main/java/io/quarkus/devconsole/runtime/spi/DevConsolePostHandler.java:21]: @stuartwdouglas Just out of curiosity, why can't we reuse the `HttpPostRequestDecoder`?

**Review by mkouba — APPROVED** [review]

File: extensions/vertx-http/dev-console-runtime-spi/src/main/java/io/quarkus/devconsole/runtime/spi/DevConsolePostHandler.java (hunk 1 above)
Comment (stuartwdouglas) [reply extensions/vertx-http/dev-console-runtime-spi/src/main/java/io/quarkus/devconsole/runtime/spi/DevConsolePostHandler.java:21]: It is very much based around netty objects that we no longer have access to (i.e. it is expecting to handle a stream of io.netty.handler.codec.http.HttpContent). We could use it if we created a heap of fake Netty objects to mimic this but it did not seem worth it.

Comment (mkouba) [reply extensions/vertx-http/dev-console-runtime-spi/src/main/java/io/quarkus/devconsole/runtime/spi/DevConsolePostHandler.java:21]: I see. I'm fine with this approach for the dev console. We can always improve the decoder later, once needed... ;-)
