### PR TITLE
Show proper error when a `@QuarkusTest` is run from a non-Quarkus project dir

### LINKED ISSUE #18132: Wrong error message: If QuarkusTest has wrong working directory, it should not blame it on "NoSuchElementException: SRCFG00011: Could not expand value platform.quarkus.native.builder-image in property quarkus.native.builder-image"
To reproduce with quarkus 1.13.3.Final (I haven't tried 2.0 yet):

1. git clone https://github.com/kiegroup/optaplanner-quickstarts
2. Open that project in IntelliJ
3. In the module quarkus-school-timetabling, open the class TimeTableConstraintProviderTest and run it by clicking on the run icon in the gutter of the java file editor at the class declaration line.

Notice that the working directory of the run configuration that IntelliJ gives you by default will be set to "optaplanner-quickstarts" and not "quarkus-school-timetabling". When it's set incorrectly like that, the unit test fails with this error:

```
java.lang.RuntimeException: java.lang.RuntimeException: java.util.NoSuchElementException: SRCFG00011: Could not expand value platform.quarkus.native.builder-image in property quarkus.native.builder-image

    at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:674)
...
Caused by: java.lang.RuntimeException: java.util.NoSuchElementException: SRCFG00011: Could not expand value platform.quarkus.native.builder-image in property quarkus.native.builder-image
...
 Caused by: java.util.NoSuchElementException: SRCFG00011: Could not expand value platform.quarkus.native.builder-image in property quarkus.native.builder-image
```

To a user, that error message should instead say "your working directory is wrong", so we can fix it and move on.

Here's how to fix it in the run configuration of intellij (which sets the working dir to quarkus-school-timetabling):

Selection_723

### PR DESCRIPTION
**Pull request by geoand**
This change fixes the (not uncommon) case where the IDE picks the wrong
working directory to launch the tests.
Without this PR, Quarkus throws a totally un-actionable message
regarding SmallRye Config's inability to expand the platform
properties

Fixes: #18132

### CODE REVIEW

File: test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java [hunk 1]
```diff
@@ -314,6 +314,11 @@ private ExtensionState doJavaStart(ExtensionContext context, Class<? extends Qua
                         .bootstrap();
             }
 
+            if (curatedApplication.getAppModel().getUserDependencies().isEmpty()) {
+                throw new RuntimeException(
+                        "The tests where run against a directory that does not contain a Quarkus project. Please ensure that the test is configured to use the proper working directory.");
```
Comment (aloubyansky) [inline test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java:319]:
```suggestion
                        "The tests were run against a directory that does not contain a Quarkus project. Please ensure that the test is configured to use the proper working directory.");
```

**Review by aloubyansky — APPROVED** [review]

**Review by gsmet — APPROVED** [review]
Nice usability improvement, thanks!

**Comment by geoand** [comment]
YW!

I was hit by this myself a couple times and didn't know what to make of it... Then I saw the issue and realised that it's a general problem that needs improvement.
