### PR TITLE
OIDC make token iat claim optional via config property

### LINKED ISSUE #39215: No way to configure iat claim as optional in quarkus-oidc
### Description

quarkus-oidc currently enforces iat as mandatory claim and there is no way to make it as optional:

https://github.com/quarkusio/quarkus/blob/main/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcProvider.java#L212

We use quarkus-oidc to support multi tenancy for our tokens, but as they do not have the iat claim present, the parsing fails with the following error:
`rejected due to invalid claims or other invalid content. Additional details: [[3] No Issued At (iat) claim present.]`

### Implementation ideas

I would recommend making the iat claim optional via configuration properties (just like the exp claim for example):

https://github.com/quarkusio/quarkus/blob/main/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcProvider.java#L201-L203

### PR DESCRIPTION
**Pull request by wesleysalimansdvb**
- Closes: https://github.com/quarkusio/quarkus/issues/39215

### CODE REVIEW

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcTenantConfig.java [hunk 1]
```diff
@@ -1542,6 +1542,15 @@ public static Token fromAudience(String... audience) {
...
         public Optional<Duration> age = Optional.empty();
 
+        /**
+         * Require that the token includes a `iat` (issued at) claim
+         *
+         * Set this property to `false` if your JWT token doesn't contain an `iat` claim,
+         * or you don't want to enable verification of it.
+         */
+        @ConfigItem(defaultValue = "true")
+        public boolean ageRequired = true;
```
Comment (sberyozkin) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcTenantConfig.java:1552]:
```suggestion
        public boolean issuedAtRequired = true;
```

**Review by sberyozkin — COMMENTED** [review]
@wesleysalimansdvb Thanks for the PR, I'd like to propose to have it named everywhere as `issuedAtRequired` and also document that this property will be ignored for the ID token verification - in `OidcIdentityProvider` there must be a `false` value passed when ID token is being verified.

Also, please update `OidcRecorder` to  throw a configuration exception if this property is true and the `quarkus.oidc.token-age` is also true.

Thanks

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcTenantConfig.java [hunk 2]
```diff
@@ -1542,6 +1542,15 @@ public static Token fromAudience(String... audience) {
         @ConfigItem
         public Optional<Duration> age = Optional.empty();
 
+        /**
+         * Require that the token includes a `iat` (issued at) claim
+         *
+         * Set this property to `false` if your JWT token doesn't contain an `iat` claim,
```
Comment (sberyozkin) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcTenantConfig.java:1548]:
```suggestion
         * Set this property to `false` if your JWT token does not contain an `iat` (issued at) claim.
```

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcTenantConfig.java [hunk 3]
```diff
@@ -1542,6 +1542,15 @@ public static Token fromAudience(String... audience) {
...
+         * or you don't want to enable verification of it. This property will be ignored for the ID token verification.
```
Comment (sberyozkin) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcTenantConfig.java:1549]:
```suggestion
         * Note that ID token is always required to have an `iat` claim and therefore this property has no impact on the ID token verification process.
```

I'm suggesting a minor rewording, as well as dropping a point where a user may choose to ignore the fact that the iat is present

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java [hunk 4]
```diff
@@ -509,7 +509,8 @@ private Uni<TokenVerificationResult> resolveJwksAndVerifyTokenUni(TenantConfigCo
             TokenCredential tokenCred,
             boolean enforceAudienceVerification, boolean subjectRequired, String nonce) {
         return resolvedContext.provider
-                .getKeyResolverAndVerifyJwtToken(tokenCred, enforceAudienceVerification, subjectRequired, nonce)
+                .getKeyResolverAndVerifyJwtToken(tokenCred, enforceAudienceVerification, subjectRequired, nonce,
+                        false)
```
Comment (sberyozkin) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java:513]:
```suggestion
                        (tokenCred instanceof IdTokenCredential))
```

otherwise it will block the access token too

**Comment by wesleysalimansdvb** [comment]
@sberyozkin thanks for the good feedback, I learned a lot by contributing to the quarkus codebase!

**Review by sberyozkin — APPROVED** [review]
Thanks @wesleysalimansdvb, I'll suggest a few more tiny updates, and we'll merge, please squash the commits if you don't mind

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcProvider.java [hunk 5]
```diff
@@ -191,7 +191,8 @@ private TokenVerificationResult verifyJwtTokenInternal(String token,
             boolean subjectRequired,
             String nonce,
             AlgorithmConstraints algConstraints,
-            VerificationKeyResolver verificationKeyResolver, boolean enforceExpReq) throws InvalidJwtException {
+            VerificationKeyResolver verificationKeyResolver, boolean enforceExpReq, boolean enforceAgeReq)
```
Comment (sberyozkin) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcProvider.java:194]:
```suggestion
            VerificationKeyResolver verificationKeyResolver, boolean enforceExpReq, boolean issuedAtRequired)
```

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcProvider.java [hunk 6]
```diff
@@ -209,7 +210,9 @@ private TokenVerificationResult verifyJwtTokenInternal(String token,
             builder.registerValidator(new CustomClaimsValidator(Map.of(OidcConstants.NONCE, nonce)));
         }
 
-        builder.setRequireIssuedAt();
+        if (enforceAgeReq) {
```
Comment (sberyozkin) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcProvider.java:213]:
```suggestion
        if (issuedAtRequired) {
```

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcRecorder.java [hunk 7]
```diff
@@ -318,6 +318,12 @@ private Uni<TenantConfigContext> createTenantContext(Vertx vertx, OidcTenantConf
             }
         }
 
+        if (!oidcConfig.token.isIssuedAtRequired() && oidcConfig.token.getAge().isPresent()) {
+            throw new ConfigurationException(
+                    "The 'token.issued-at-required' can only be set to false if 'token.age' is not set." +
+                            " Either set 'token.issued-at-required' to true or do not set 'token.age'.");
```
Comment (sberyozkin) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcRecorder.java:324]: Can you please check there in `OidcRecorder` how a problematic property is referenced in this exception's consructor, I think you can use `Set.of("quarkus.oidc.token.issued-at-required")`, it can help in devmode

**Review by sberyozkin — APPROVED** [review]
@wesleysalimansdvb Very last (I promise :-)) 3 suggestions are proposed, thanks

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcProvider.java (hunk 5 above)
Comment (wesleysalimansdvb) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcProvider.java]: Looked over that one, thanks!

**Comment by wesleysalimansdvb** [comment]
Squashed the commits in to 1 commit, I hope everything is alright like this. If not, I'll see :p

Thanks!

**Review by sberyozkin — APPROVED** [review]

**Comment by sberyozkin** [comment]
Proposing a backport to 3.8 following a request from @madocx at #39887, as the changes do not seem to be sensitive
