### PR TITLE
Graceful shutdown fixes

### LINKED ISSUE #15908: Quartz extension - graceful shutdown for @Scheduled does not work
Allow users to set the `quarkus.shutdown.timeout` (or a separate property) to configure graceful shutdown for `@Scheduled`.
A typical use case is that the application interacts with a message queue in a scheduled method. When upgrading/releasing a new version of the app the user wants the service to ignore incoming messages (i.e., not run any new scheduled jobs) but finish the currently running job(s).

### PR DESCRIPTION
**Pull request by mkouba**
- fix ExecutorRecorder to interpret the shutdown timeout property
correctly + test
- fix the graceful shutdown logic in QuartzScheduler
- resolves #15908

### CODE REVIEW

File: extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java [hunk 1]
```diff
@@ -281,10 +281,11 @@ void start(@Observes @Priority(Interceptor.Priority.PLATFORM_BEFORE) StartupEven
      *
      * @param event ignored
      */
-    void destroy(@BeforeDestroyed(ApplicationScoped.class) Object event) { //
+    void destroy(@Observes @BeforeDestroyed(ApplicationScoped.class) Object event) {
```
Comment (machi1990) [inline extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java:284]: Thanks for catching this!

**Review by machi1990 — APPROVED** [review]
Reviewed the Quartz part, LGTM.

**Review by gsmet — APPROVED** [review]

**Review by stuartwdouglas — APPROVED** [review]
