### PR TITLE
Arc - pre-destroy and post construct shouldn't be considered as candidates for around invoke interception

### LINKED ISSUE #19713: Arc - container invocation of predestroy/post-construct methods should not be treated as bussinees method invocations
### Describe the bug

Given a bean that has `@PreDestroy`/`@PostConstruct` methods and that has an interceptor with `@AroundInvoke` bound by binding on a class-level, Arc currently treats invocation of `@PreDestroy`/`@PostConstruct` as business method invocations.
This means that when container (Arc) invokes those methods, it will also intercept that invocation with any `@AroundInvoke` interceptor bound to them. This seems to be against CDI specification; this is what [spec says](https://jakarta.ee/specifications/cdi/2.0/cdi-spec-2.0.html#biz_method):

> Invocation of lifecycle callbacks by the container are not business method invocations, but are intercepted by interceptors for lifecycle callbacks.

A test for this behavior can be seen on my branch - https://github.com/quarkusio/quarkus/compare/main...manovotn:interceptionComplexTest?expand=1

### PR DESCRIPTION
**Pull request by manovotn**
Fixes #19713 

Makes sure that methods annotated with `@PreDestroy` and `@PostConstruct` which are declared on bean classes are not taken into consideration for around invoke interception.

### CODE REVIEW

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanInfo.java [hunk 1]
```diff
@@ -518,8 +518,11 @@ protected String getType() {
             for (Entry<MethodKey, Set<AnnotationInstance>> entry : candidates.entrySet()) {
                 List<InterceptorInfo> interceptors = beanDeployment.getInterceptorResolver()
                         .resolve(InterceptionType.AROUND_INVOKE, entry.getValue());
-                if (!interceptors.isEmpty()) {
-                    interceptedMethods.put(entry.getKey().method, new InterceptionInfo(interceptors, entry.getValue()));
+                MethodInfo method = entry.getKey().method;
+                // @PreDestroy and @PostConstruct methods declared on the bean are NOT candidates for around invoke interception
+                if (!interceptors.isEmpty() && !method.hasAnnotation(DotNames.PRE_DESTROY)
```
Comment (mkouba) [inline independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanInfo.java:523]: Woudln't it make more sense to ignore such methods in the `io.quarkus.arc.processor.Methods.SubclassSkipPredicate.test(MethodInfo)` instead?

Comment (manovotn) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanInfo.java:523]: Yea, that's another way. I can rework it if you want to.
Either way, I think we might run into a corner case problem where some users might attempt to call these methods manually (which interceptors spec doesn't forbid I think?) and at that point they still won't be intercepted, But it is IMO still better than what we do now.

Comment (manovotn) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanInfo.java]: Changed accordingly to your suggestion.

**Review by mkouba — APPROVED** [review]

**Review by Ladicek — APPROVED** [review]

**Comment by Ladicek** [comment]
Error seems to be ` Caused by: java.util.NoSuchElementException: SRCFG00027: Could not find a mapping for io.quarkus.arc.test.config.ConfigPropertiesTest$ServerConfigProperties`, which I don't really understand :-)

**Comment by manovotn** [comment]
> which I don't really understand :-)

Neither do I, it seems completely unrelated though.

**Comment by famod** [comment]
@mkouba @manovotn @Ladicek just to make sure: with this change, `@Transactional` doesn't work anymore for `@PostConstruct`.
That can be considered a breaking change, no?

**Comment by manovotn** [comment]
This fixes a behavior which was against specification and shouldn't have worked so I'd say no.

**Comment by Ladicek** [comment]
A bugfix may still be a breaking change in my opinion :-) Though using `@Transactional` on `@PostConstruct` methods sounds pretty strange to me.

**Comment by famod** [comment]
Ok, so let's agree that "breaking" might be to strong, but I suggest to mention this in the migration guide.

I guess nothing will "break" if you read something from the DB in `@PostConstruct` (e.g. for a cache or whatever) but there are still implications like inefficient connection handling and different data visibility rules.
Persisting something in `@PostConstruct` is nothing I've ever done, bute that will probably "break".

> Though using `@Transactional` on `@PostConstruct` methods sounds pretty strange to me.

It's not so much on the method itself, but on class level - which is pretty common I would say!

**Comment by Ladicek** [comment]
Nice example! I see how someone might have fallen into that trap without even knowing.

**Comment by manovotn** [comment]
> Ok, so let's agree that "breaking" might be to strong, but I suggest to mention this in the migration guide.

+1, won't hunt to let it be known.

**Comment by famod** [comment]
If this gets backported to 2.2, then it should probably be added to the 2.2 migration guide as well.

**Comment by mkouba** [comment]
For the record, the JTA spec is clear that _"The Transactional interceptor interposes on business method invocations only and not on lifecycle events. Lifecycle methods are invoked in an unspecified transaction context."_ (3.7 Transactional Annotation, JTA 1.2).

**Comment by mkouba** [comment]
On the other hand, I can imagine a use case where a transaction is needed when a bean is created. 

In theory, a similar workaround should work in Quarkus:
```java
class MyBean {
   @PostConstruct
   void init() {
     doInit(); // Interception works for self-invocation
   }
   
   @Transactional
   void doInit() {
     // ...e.g. save something in DB
   }
}
```

**Comment by manovotn** [comment]
I was stuck on other issue and on a mtg. I will update the migration guide tomorrow morning.
BTW I don't think we need to backport this.

**Comment by manovotn** [comment]
Added to the migration guide, see https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.3#cdi-predestroy-and-postcontruct-methods-on-bean-classes

**Comment by mkouba** [comment]
Looks good but we should probably verify that the workaround really works? ;-)

**Comment by manovotn** [comment]
@mkouba of course it works, I verified that :-)

**Comment by famod** [comment]
Great, thanks all!

**Comment by famod** [comment]
FWIW, I just had a weird failure in 2.2.3 that should be fixed with this PR:

`@InjectSpy` for a bean that has a classlevel `@Transactional(MANDATORY)` failed on a `@PostConstruct` method because there is no transaction:
```
org.junit.jupiter.api.extension.TestInstantiationException: Failed to create test instance
	at io.quarkus.test.junit.QuarkusTestExtension.initTestState(QuarkusTestExtension.java:894)
[...]
Caused by: javax.transaction.TransactionalException: ARJUNA016110: Transaction is required for invocation
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorMandatory.doIntercept(TransactionalInterceptorMandatory.java:36)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:57)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorMandatory.intercept(TransactionalInterceptorMandatory.java:30)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorMandatory_Bean.intercept(TransactionalInterceptorMandatory_Bean.zig:340)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at somecompany.healthcore.persistence.transaction.AsyncEventSender_Subclass.lookupBlocker(AsyncEventSender_Subclass.zig:206)
	at somecompany.healthcore.persistence.transaction.AsyncEventSender_Bean.create(AsyncEventSender_Bean.zig:402)
	at somecompany.healthcore.persistence.transaction.AsyncEventSender_Bean.create(AsyncEventSender_Bean.zig:418)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:96)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
	at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:17)
	at somecompany.healthcore.persistence.transaction.AsyncEventSender_ClientProxy.arc$delegate(AsyncEventSender_ClientProxy.zig:84)
	at somecompany.healthcore.persistence.transaction.AsyncEventSender_ClientProxy.arc_contextualInstance(AsyncEventSender_ClientProxy.zig:99)
	at io.quarkus.arc.runtime.ClientProxyUnwrapper.apply(ClientProxyUnwrapper.java:11)
	at io.quarkus.test.junit.mockito.internal.CreateMockitoSpiesCallback.createSpyAndSetTestField(CreateMockitoSpiesCallback.java:31)
	at io.quarkus.test.junit.mockito.internal.CreateMockitoSpiesCallback.afterConstruct(CreateMockitoSpiesCallback.java:21)
	... 70 more
Caused by: javax.transaction.TransactionRequiredException
	... 92 more
```
I was able to work around this by annotating the post-construction method with `@Transactional(NEVER)`.

/cc @geoand

**Comment by manovotn** [comment]
@famod Do you have a reproducer showing this? Or at least, how does the scenario differ from the test in this PR?

**Comment by famod** [comment]
@manovotn this PR is fine, AFAICS! I just wanted to point out that before this change you could run into actual problems, so this adjustment wasn't just "cosmetic".

**Comment by manovotn** [comment]
Ah, I misread your previous comment and thought you found another case where it fails :)
