### PR TITLE
Make sure REST methods can be called without an active CDI context

### LINKED ISSUE #22662: Gauges annotation are not showing up his value, on a resteasy endpoint
### Describe the bug

If a gauge is declared in a Resteasy endpoint through an annotation, the gauge value is not pushed to `/metrics`

Example: 
```
@Path("/using-microprofile-pingpong")
public class UsingMicroProfilePingPongResource {

    private static final String PING_PONG = "ping pong";
    private static final long DEFAULT_GAUGE_VALUE = 100L;

    // counters works as expected
    @GET
    @Counted(name = "simple_counter_mp", absolute = true)
    @Produces(MediaType.TEXT_PLAIN)
    @Path("/counter")
    public String simpleScenario() {
        return PING_PONG;
    }

    //TODO gauges are not promoting their values to /metrics
    @GET
    @Gauge(name = "simple_gauge_mp", unit = MetricUnits.NONE)
    @Produces(MediaType.TEXT_PLAIN)
    @Path("/gauge")
    public long highestPrimeNumberSoFar() {
        return DEFAULT_GAUGE_VALUE;
    }
}
```

But If I move on the gauge to a separate public method, then works as expected: 

```
@Path("/using-microprofile-pingpong")
public class UsingMicroProfilePingPongResource {

    private static final String PING_PONG = "ping pong";
    private static final long DEFAULT_GAUGE_VALUE = 100L;

    @GET
    @Counted(name = "simple_counter_mp", absolute = true)
    @Produces(MediaType.TEXT_PLAIN)
    @Path("/counter")
    public String simpleScenario() {
        return PING_PONG;
    }

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    @Path("/gauge")
    public long highestPrimeNumberSoFar() {
        return getDefaultGauge();
    }

    @Gauge(name = "simple_gauge_mp", unit = MetricUnits.NONE)
    public long getDefaultGauge() {
        return DEFAULT_GAUGE_VALUE;
    }
}
```

Additional when the gauge is not promoted I am getting the following warning message:
```
2022-01-05 16:48:04,996 WARN  [io.mic.cor.ins.int.DefaultGauge] (vert.x-worker-thread-0) Failed to apply the value function for the gauge 'io.quarkus.ts.micrometer.prometheus.UsingMicroProfilePingPongResource.simple_gauge_mp'. Note that subsequent logs will be logged at debug level.: javax.enterprise.context.ContextNotActiveException
	at io.quarkus.arc.impl.ClientProxies.getDelegate(ClientProxies.java:46)
	at io.quarkus.vertx.http.runtime.CurrentVertxRequest_ClientProxy.arc$delegate(Unknown Source)
```

From a developer experience point of view, would be great to have the same behavior in all metrics data structures. So, if counter annotations is available in an endpoint declaration then gauges should be also valid. 

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

openjdk 11.0.11 2021-04-20 OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9) OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jmartisk**
Fixes #22662 - the problem is that if there's a gauge on a REST method and its `GaugeAdapterImpl` calls that REST method during scraping, it is called without an attached CDI and routing context, and `CurrentVertxRequest.getCurrent()` throws an exception in this case, rather than returns null.

### CODE REVIEW

File: extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/binder/mpmetrics/MetricDescriptor.java [hunk 1]
```diff
@@ -10,7 +10,7 @@
 
 import io.micrometer.core.instrument.Tags;
 
-class MetricDescriptor {
+public class MetricDescriptor {
```
Comment (jmartisk) [inline extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/binder/mpmetrics/MetricDescriptor.java:13]: Not completely sure about this, but without this change I am seeing this in the log on startup:
```
2022-01-06 09:26:55,793 WARN  [io.qua.arc.pro.Methods] (build-4) A method register() declared on io.quarkus.micrometer.runtime.binder.mpmetrics.AnnotatedGaugeAdapter$GaugeAdapterImpl has a non-public parameter of type io.quarkus.micrometer.runtime.binder.mpmetrics.MetricDescriptor which prevents it from being intercepted. Please change the parameter type visibility in order to make it intercepted.
```

File: extensions/resteasy-classic/resteasy/runtime/src/main/java/io/quarkus/resteasy/runtime/QuarkusRestPathTemplateInterceptor.java [hunk 2]
```diff
@@ -24,7 +26,13 @@
     @AroundInvoke
     Object restMethodInvoke(InvocationContext context) throws Exception {
         QuarkusRestPathTemplate annotation = getAnnotation(context);
-        if ((annotation != null) && (request.getCurrent() != null)) {
+        RoutingContext routingContext = null;
+        try {
+            routingContext = request.getCurrent();
+        } catch (ContextNotActiveException ex) {
```
Comment (ebullient) [inline extensions/resteasy-classic/resteasy/runtime/src/main/java/io/quarkus/resteasy/runtime/QuarkusRestPathTemplateInterceptor.java:32]: This is a nit you can ignore if you want, but some IDEs suggest you should name this variable "ignored" for clarity (yes, IDE linter, yes I am ignoring this on purpose, stop chiding me about it)...

File: integration-tests/micrometer-mp-metrics/src/main/java/io/quarkus/it/micrometer/mpmetrics/PrimeResource.java [hunk 3]
```diff
@@ -70,6 +70,8 @@ String checkPrime(long number) {
     }
 
     @Gauge(name = "highestPrimeNumberSoFar", unit = MetricUnits.NONE, description = "Highest prime number so far.")
+    @GET
+    @Path("/blabla") // make this a REST method just to verify that a gauge will still work on it
```
Comment (ebullient) [inline integration-tests/micrometer-mp-metrics/src/main/java/io/quarkus/it/micrometer/mpmetrics/PrimeResource.java:74]: Do we have to add something to the test that will use it?

**Review by ebullient — APPROVED** [review]
A few nits, but not required. ;)
Thank you (and Happy New Year)!

File: extensions/resteasy-classic/resteasy/runtime/src/main/java/io/quarkus/resteasy/runtime/QuarkusRestPathTemplateInterceptor.java (hunk 2 above)
Comment (jmartisk) [reply extensions/resteasy-classic/resteasy/runtime/src/main/java/io/quarkus/resteasy/runtime/QuarkusRestPathTemplateInterceptor.java:32]: Ha, afaik my IDE only suggests that when the block is completely empty, adding a comment prevents that!

File: integration-tests/micrometer-mp-metrics/src/main/java/io/quarkus/it/micrometer/mpmetrics/PrimeResource.java (hunk 3 above)
Comment (jmartisk) [reply integration-tests/micrometer-mp-metrics/src/main/java/io/quarkus/it/micrometer/mpmetrics/PrimeResource.java:74]: No, the test already checks the value of that metric for some unrelated purposes, which is enough

**Comment by jmartisk** [comment]
@ebullient thanks for the review and happy new year to you too :)
