### PR TITLE
Fix setting service account in Kubernetes/Openshift extensions

### LINKED ISSUE #32933: Quarkus-3.0.1 - Ignores Kubernetes Service account property
### Describe the bug

Just upgraded to quarkus **3.0.1.Final**. Kubernetes manifest generation ignores this property and it works in **2.16.5..Final**

`quarkus.kubernetes.service-account=quarkus-tester-sa`

### Expected behavior

Manifest generation should work like 2.16.5

### Actual behavior

Service account being ignored

### How to Reproduce?

Declare the above mentioned property in `application.properties` and do `./mvnw clean package` and notice that service account property is missing in the `kubernetes.yaml`

### Output of `uname -a` or `ver`

mac m1

### Output of `java -version`

Java 17

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

3.0.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

./mvnw 3.8.2

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Sgitario**
Fix https://github.com/quarkusio/quarkus/issues/32933

### CODE REVIEW

File: extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/KubernetesCommonHelper.java [hunk 1]
```diff
@@ -304,16 +304,16 @@ private static Collection<DecoratorBuildItem> createRbacDecorators(String name,
         }
 
         // Add service account from extensions: use the one provided by the user always
-        String defaultServiceAccount = null;
+        Optional<String> defaultServiceAccount = config.getServiceAccount();
         String defaultServiceAccountNamespace = null;
         for (KubernetesServiceAccountBuildItem sa : serviceAccountsFromExtensions) {
             String saName = defaultIfEmpty(sa.getName(), name);
```
Comment (iocanel) [inline extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/KubernetesCommonHelper.java:310]: I know this line is not changed by this pull request, but why would a `KubernetesServiceAccountBuildItem` contain an empty name? This feels really weird.

Comment (iocanel) [reply extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/KubernetesCommonHelper.java:310]: I mean that it could possibly use Optional instead.

Comment (iocanel) [inline extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/KubernetesCommonHelper.java:310]: The rest of the pull request is shifting away from the use of `defaultIfEmpty` to using `Optional` which is something that makes the code easier to read. 
Maybe we need to do the same here?

File: extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/KubernetesCommonHelper.java [hunk 2]
```diff
@@ -304,16 +304,16 @@ private static Collection<DecoratorBuildItem> createRbacDecorators(String name,
         }
 
         // Add service account from extensions: use the one provided by the user always
-        String defaultServiceAccount = null;
+        Optional<String> defaultServiceAccount = config.getServiceAccount();
```
Comment (iocanel) [inline extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/KubernetesCommonHelper.java:307]: This is not the default service account, this is the configured service account.

File: extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/KubernetesCommonHelper.java (hunk 1 above)
Comment (Sgitario) [reply extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/KubernetesCommonHelper.java:310]: Changed to `Optional.ofNullable(sa.getName()).orElse(name);` and removed `defaultIfEmpty` method.

Comment (Sgitario) [reply extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/KubernetesCommonHelper.java:310]: We could use the optional, anyhow I prefer not doing this change in this pull request.

File: extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/KubernetesCommonHelper.java [hunk 3]
```diff
@@ -437,24 +437,24 @@ private static Collection<DecoratorBuildItem> createRbacDecorators(String name,
...
+                            defaultServiceAccountNamespace,
                             Collections.emptyMap())));
         }
 
         // set service account in deployment resource
-        if (defaultServiceAccount != null) {
-            result.add(new DecoratorBuildItem(target, new ApplyServiceAccountNameDecorator(name, defaultServiceAccount)));
+        if (defaultServiceAccount.isPresent() || requiresServiceAccount) {
+            result.add(new DecoratorBuildItem(target,
+                    new ApplyServiceAccountNameDecorator(name, defaultServiceAccount.orElse(name))));
```
[the remark this answers is not in the document]
Comment (Sgitario) [reply extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/KubernetesCommonHelper.java:457]: > The default service account is always the application name.

Not quite, the default service account is set by the user with `quarkus.kubernetes.service-account`. 

I've renamed this field to `effectiveServiceAccount`.

**Comment by Sgitario** [comment]
PR updated by removing the `defaultIfEmpty` method and renaming the `defaultServiceAccount` field. 
cc @iocanel

**Review by iocanel — APPROVED** [review]
LGTM
