### PR TITLE
Remove the session cookie if ID token verification failed

### LINKED ISSUE #31717: Quarkus OIDC Session Cookie not deleted in case of 401 unauthorized
### Describe the bug

In case the verification of the oidc session cookie fails (for instance because the id token is malformed, expired, ...), then the server response with an http 401. however, the server is not deleting the session cookie. hence all subsequent requests also fail with 401 without the change for the user to recover. Only deleting the session cookie or waiting for it to expire is possible.

### Expected behavior

If the server response with http 401, then the server also deletes the q_session cookie.

### Actual behavior

If the server response with http 401, then the (invalid) q_session cookie is not deleted automatically.

### How to Reproduce?

1) Login into your web application
2) manipulate the session cookie
3) perform another activity in the web application

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.16.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sberyozkin**
Fixes #31717

If the ID token verification fails then the session cookie has to be cleared - currently 401 is immediately returned and the user gets stuck. 

Note this exception is caused by `AuthenticationCompletionException` meaning no redirect to OIDC provider will be happening, user just gets `401`. In some cases when no session cookie exists for example, we'd throw `AuthenticationFailedException` leading to `302` and redirect to the provider. In this case though if for example the signature verification has failed then it means something gone badly wrong somewhere and just redirecting to the provider ro reauthenticate would be a problem, it may make some serious underlying security issue unnoticed.
So I think we should continue returning 401 in such cases but indeed get rid of the session cookie - for example, the application, if it wants, can catch the exception and offer a user an option to access a secured Quarkus page again which will cause the expected redirect back to the OIDC provider etc

### CODE REVIEW

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java [hunk 1]
```diff
@@ -321,8 +321,9 @@ public Uni<? extends SecurityIdentity> apply(Throwable t) {
 
                                             if (!expired) {
                                                 LOG.errorf("ID token verification failure: %s", t.getCause());
-                                                return Uni.createFrom()
-                                                        .failure(new AuthenticationCompletionException(t.getCause()));
+                                                return removeSessionCookie(context, configContext.oidcConfig)
+                                                        .replaceWith(Uni.createFrom()
+                                                                .failure(new AuthenticationCompletionException(t.getCause())));
```
Comment (gastaldi) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java:326]: Check if `t instanceof AuthenticationCompletionException`?

**Review by gastaldi — APPROVED** [review]

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java (hunk 1 above)
Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java:326]: @gastaldi Sure, I think `OidcIdentityProvider` would not throw it, but just in case, make sense, let me do it now
