### PR TITLE
QuarkusComponentTest: remove duplicate unsatisfied injection points

### LINKED ISSUE #51378: QuarkusComponentTest fails with ambiguous dependencies if bean is injected with parameterized qualifier multiple times
`QuarkusComponentTest` fails with ambiguous dependencies if bean is injected with parameterized qualifier multiple times

### Describe the bug

We have a project which connects to RabbitMQ using the SmallRye Reactive Messaging extension. One class injects two emitters on different channels.

When trying to test the class using `@QuarkusComponentTest`, the test fails to start due to ambiguous dependencies. Arc seems to produce both synthetic beans but cannot distinguish between them anymore (which is possible when running Quarkus itself).

I created a minimal reproducer using a custom qualifier.

### Expected behavior

The test class starts and runs the actual tests.

### Actual behavior

The test discovery fails with an error:

```
Caused by: jakarta.enterprise.inject.spi.DeploymentException: Found 2 deployment problems: 
[1] Ambiguous dependencies for type `com.example.TestBeanClass` and qualifiers [`@TestQualifier("foo")`]
	- injection target: `com.example.TestAppScopeClass#testBeanClass`
	- declared on CLASS bean [types=[`com.example.TestAppScopeClass`, `java.lang.Object`], qualifiers=[`@Any`, `@Default`], target=`com.example.TestAppScopeClass`]
	- available beans:
		- SYNTHETIC bean [types=[`com.example.TestBeanClass`, `java.lang.Object`], qualifiers=[`@Any`, `@TestQualifier("foo")`], target=n/a]
		- SYNTHETIC bean [types=[`com.example.TestBeanClass`, `java.lang.Object`], qualifiers=[`@Any`, `@TestQualifier("bar")`], target=n/a]
[2] Ambiguous dependencies for type `com.example.TestBeanClass` and qualifiers [`@TestQualifier("bar")`]
	- injection target: `com.example.TestAppScopeClass#testBeanClass2`
	- declared on CLASS bean [types=[`com.example.TestAppScopeClass`, `java.lang.Object`], qualifiers=[`@Any`, `@Default`], target=`com.example.TestAppScopeClass`]
	- available beans:
		- SYNTHETIC bean [types=[`com.example.TestBeanClass`, `java.lang.Object`], qualifiers=[`@Any`, `@TestQualifier("foo")`], target=n/a]
		- SYNTHETIC bean [types=[`com.example.TestBeanClass`, `java.lang.Object`], qualifiers=[`@Any`, `@TestQualifier("bar")`], target=n/a]
```

### How to Reproduce?

[reproducer.zip](https://github.com/user-attachments/files/23908023/reproducer.zip)

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

3.30.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.11 (3e54c93a704957b63ee3494413a2b544fd3d825b)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mkouba**
- these duplicates can appear if a qualifier with non-binding member is used
- fixes #51378

### CODE REVIEW

**Comment by Ladicek** [comment]
I was thinking about it once or twice and now I'm thinking again: should we perhaps normalize the `interceptorNonbindingMembers` and `qualifierNonbindingMembers` maps? They currently only hold non-binding members of annotations registered through extensions, but all places that use that info also check the annotation declarations to cover annotations that were discovered "normally". Maybe both maps should contain the non-binding info for _all_ annotations regardless of their provenance? Usages would be simplified considerably. In fact, I think we would be able to avoid making the `getQualifierNonbindingMembers()` method `public` if we had that, because we already have `getQualifierNonbindingMembers(DotName)`.

**Comment by mkouba** [comment]
> I was thinking about it once or twice and now I'm thinking again: should we perhaps normalize the `interceptorNonbindingMembers` and `qualifierNonbindingMembers` maps? They currently only hold non-binding members of annotations registered through extensions, but all places that use that info also check the annotation declarations to cover annotations that were discovered "normally". Maybe both maps should contain the non-binding info for _all_ annotations regardless of their provenance? Usages would be simplified considerably. In fact, I think we would be able to avoid making the `getQualifierNonbindingMembers()` method `public` if we had that, because we already have `getQualifierNonbindingMembers(DotName)`.

I think that it's a good idea to refactor this part of the code. However, it's also out of scope of this PR, which I'd like to backport as well (hence the minimal changes in `arc-core`).

**Comment by Ladicek** [comment]
Understood. I'd like to avoid making the `BeanDeployment.getQualifierNonbindingMembers()` method `public` forever, though. Could you make it `@Deprecated` or in some other clear way indicate that it should not be depended upon?

**Comment by mkouba** [comment]
> Understood. I'd like to avoid making the `BeanDeployment.getQualifierNonbindingMembers()` method `public` forever, though. Could you make it `@Deprecated` or in some other clear way indicate that it should not be depended upon?

Actually, I think that I don't need it to be `public` because `getQualifiers()` should return all qualifiers (including the ones added via `QualifierRegistrar`).

BTW the javadoc of `BeanDeployment#getQualifierNonbindingMembers(DotName)` is incorrect. First, it talks about interceptor bindings (copy and paste from the `getInterceptorNonbindingMembers()`?) and it also mentions `@NonBinding` which should be `@Nonbinding`...

**Comment by Ladicek** [comment]
> > Understood. I'd like to avoid making the `BeanDeployment.getQualifierNonbindingMembers()` method `public` forever, though. Could you make it `@Deprecated` or in some other clear way indicate that it should not be depended upon?
> 
> Actually, I think that I don't need it to be `public` because `getQualifiers()` should return all qualifiers (including the ones added via `QualifierRegistrar`).

+1

> BTW the javadoc of `BeanDeployment#getQualifierNonbindingMembers(DotName)` is incorrect. First, it talks about interceptor bindings (copy and paste from the `getInterceptorNonbindingMembers()`?) and it also mentions `@NonBinding` which should be `@Nonbinding`...

Yeah, the mention of interceptor bindings is clearly a copy 'n' paste error from the other method, and `@NonBinding` is a typo. I'll handle those when I do the refactoring, if you don't mind.

**Review by manovotn — APPROVED** [review]
LGTM

**Comment by manovotn** [comment]
> I was thinking about it once or twice and now I'm thinking again: should we perhaps normalize the `interceptorNonbindingMembers` and `qualifierNonbindingMembers` maps? They currently only hold non-binding members of annotations registered through extensions, but all places that use that info also check the annotation declarations to cover annotations that were discovered "normally". Maybe both maps should contain the non-binding info for _all_ annotations regardless of their provenance? Usages would be simplified considerably. 

That would be nice and definitely more understandable!

File: test-framework/junit5-component/src/main/java/io/quarkus/test/component/ComponentContainer.java [hunk 1]
```diff
@@ -891,6 +905,95 @@ private static Set<Annotation> findBindings(Method method, Set<String> bindings)
                 .collect(Collectors.toSet());
     }
 
+    private static Map<DotName, Set<String>> findQualifierToNonbindingMembers(BeanDeployment beanDeployment) {
+        Map<DotName, Set<String>> ret = new HashMap<>();
+        beanDeployment.getQualifiers().stream()
```
Comment (Ladicek) [inline test-framework/junit5-component/src/main/java/io/quarkus/test/component/ComponentContainer.java]: Nitpicking: you don't need to stream here, a classic for-each would do just fine :-)

File: test-framework/junit5-component/src/main/java/io/quarkus/test/component/ComponentContainer.java [hunk 2]
```diff
@@ -891,6 +905,95 @@ private static Set<Annotation> findBindings(Method method, Set<String> bindings)
...
+                    }
+                    nonbinding.addAll(beanDeployment.getQualifierNonbindingMembers(q.name()));
+                    if (!nonbinding.isEmpty()) {
+                        ret.put(q.name(), nonbinding);
+                    }
+                });
+        return ret;
+    }
+
+    private static List<TypeAndQualifiers> findDuplicitInjectionPoints(BeanDeployment beanDeployment,
```
Comment (Ladicek) [inline test-framework/junit5-component/src/main/java/io/quarkus/test/component/ComponentContainer.java]: Nitpicking: "duplicit" is not an English word, "duplicate" is what you mean here I think.

**Review by Ladicek — APPROVED** [review]
LGTM, just two nitpicking comments, feel free to ignore :-)
