### PR TITLE
Force java_generic_services to false for protos gathered from dependencies

### LINKED ISSUE #25275: Quarkus gRPC generator tries to write the same file twice
### Describe the bug

Trying to generate service/message definition from https://github.com/envoyproxy/java-control-plane/tree/main/api produces "Tried to write the same file twice" errors.

### Expected behavior

Should compile

### Actual behavior

Error 

```
[INFO] --- quarkus-maven-plugin:2.8.2.Final:generate-code (default) @ grpc ---
udpa/type/v1/typed_struct.proto:14:1: warning: Import validate/validate.proto is unused.
udpa/service/orca/v1/orca.proto:18:1: warning: Import validate/validate.proto is unused.
xds/type/v3/typed_struct.proto:10:1: warning: Import validate/validate.proto is unused.
xds/service/orca/v3/orca.proto:14:1: warning: Import validate/validate.proto is unused.
io/envoyproxy/envoy/service/accesslog/v3/AccessLogService.java: Tried to write the same file twice.
io/envoyproxy/envoy/service/accesslog/v2/AccessLogService.java: Tried to write the same file twice.
io/envoyproxy/envoy/service/auth/v3/Authorization.java: Tried to write the same file twice.
io/envoyproxy/envoy/service/auth/v2/Authorization.java: Tried to write the same file twice.
io/envoyproxy/envoy/service/auth/v2alpha/Authorization.java: Tried to write the same file twice.
io/envoyproxy/envoy/service/discovery/v3/AggregatedDiscoveryService.java: Tried to write the same file twice.
io/envoyproxy/envoy/service/discovery/v2/RuntimeDiscoveryService.java: Tried to write the same file twice.
io/envoyproxy/envoy/service/discovery/v2/SecretDiscoveryService.java: Tried to write the same file twice.
io/envoyproxy/envoy/service/discovery/v2/AggregatedDiscoveryService.java: Tried to write the same file twice.
io/envoyproxy/envoy/service/discovery/v2/HealthDiscoveryService.java: Tried to write the same file twice.
....
```

### How to Reproduce?

copy/pasting the proto folder from the given repo or using dependency :

```
quarkus.generate-code.grpc.scan-for-proto=io.envoyproxy.controlplane:api
```

```
<dependency>
      <groupId>io.envoyproxy.controlplane</groupId>
      <artifactId>api</artifactId>
      <version>0.1.31</version>
</dependency>
```

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.8.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

Removing `--q-grpc_out=/grpc/target/generated-sources/grpc` from the generated command line works.

### PR DESCRIPTION
**Pull request by scrocquesel**
Fixes: https://github.com/quarkusio/quarkus/issues/25275

### CODE REVIEW

File: extensions/grpc/codegen/src/main/java/io/quarkus/grpc/deployment/GrpcCodeGen.java [hunk 1]
```diff
@@ -146,6 +146,24 @@ public boolean trigger(CodeGenContext context) throws CodeGenException {
...
+        try (var reader = Files.newBufferedReader(protoPath);
+                var writer = Files.newBufferedWriter(outProtoPath)) {
+
+            String line = reader.readLine();
+            while (line != null) {
+                // filter java_generic_services to avoid "Tried to write the same file twice"
+                // when set to true. Generic services are deprecated and replaced by classes generated by
+                // this plugin
+                if (!line.contains("java_generic_services")) {
+                    writer.write(line);
```
Comment (cescoffier) [inline extensions/grpc/codegen/src/main/java/io/quarkus/grpc/deployment/GrpcCodeGen.java:159]: What about adding a warning here, indicating to the user that we had to change the proto file? If we could reference a place indicating that `java_generic_services` is deprecated, that would be really awesome.

File: extensions/grpc/codegen/src/main/java/io/quarkus/grpc/deployment/GrpcCodeGen.java [hunk 2]
```diff
@@ -146,6 +146,24 @@ public boolean trigger(CodeGenContext context) throws CodeGenException {
         return false;
     }
 
+    private static void copySanitizedProtoFile(Path protoPath, Path outProtoPath) throws IOException {
+        try (var reader = Files.newBufferedReader(protoPath);
+                var writer = Files.newBufferedWriter(outProtoPath)) {
+
+            String line = reader.readLine();
+            while (line != null) {
```
Comment (cescoffier) [inline extensions/grpc/codegen/src/main/java/io/quarkus/grpc/deployment/GrpcCodeGen.java:154]: I believe it would be simpler to use a Stream<String> and just filter out the` java_generic_services` one.

File: integration-tests/grpc-external-proto/src/main/resources/dir/my-proto.proto [hunk 3]
```diff
@@ -2,6 +2,8 @@ syntax = "proto3";
 
 option java_package = "com.test";
 
+option java_generic_services = true;
```
Comment (cescoffier) [inline integration-tests/grpc-external-proto/src/main/resources/dir/my-proto.proto:5]: Could you create a duplicated proto file?

**Review by cescoffier — CHANGES_REQUESTED** [review]

File: extensions/grpc/codegen/src/main/java/io/quarkus/grpc/deployment/GrpcCodeGen.java (hunk 1 above)
Comment (scrocquesel) [reply extensions/grpc/codegen/src/main/java/io/quarkus/grpc/deployment/GrpcCodeGen.java:159]: You mean logger warn ?

File: extensions/grpc/codegen/src/main/java/io/quarkus/grpc/deployment/GrpcCodeGen.java (hunk 2 above)
Comment (scrocquesel) [reply extensions/grpc/codegen/src/main/java/io/quarkus/grpc/deployment/GrpcCodeGen.java:157]: If you mean `reader.lines().stream().filter().foreach(line -> writer.write(line))`; Then `IOException `must be catched in the `foreach`. Caller is already catching IOException, I think it's easier to let it bubble up.

File: integration-tests/grpc-external-proto/src/main/resources/dir/my-proto.proto (hunk 3 above)
Comment (scrocquesel) [reply integration-tests/grpc-external-proto/src/main/resources/dir/my-proto.proto]: done

File: extensions/grpc/codegen/src/main/java/io/quarkus/grpc/deployment/GrpcCodeGen.java (hunk 1 above)
Comment (scrocquesel) [reply extensions/grpc/codegen/src/main/java/io/quarkus/grpc/deployment/GrpcCodeGen.java:162]: I add a logger info. To me, warning means the user should do something to fix it. But I believe that this issue will only happen for dependency the user do not own and have no control over it.
Doc now states that this option should not be used and is ignored for dependencies.

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
Can you make our "review for review"?

**Comment by scrocquesel** [comment]
> Can you make our "review for review"?

@cescoffier what do you mean?

**Comment by cescoffier** [comment]
The Or is still in draft.
