### PR TITLE
Apply HTTP port to probes

### LINKED ISSUE #8090: Generated kubernetes manifests contain wrong port in health probes
**Describe the bug**
When `quarkus.http.port=9090` and the `quarkus-smallrye-health` extensions is present, it is expected that the health and liveness probes will use that port (instead of the the default.)

**Expected behavior**
Port `9090` is used in health and liveness probes.

**Actual behavior**
The liveness probe (readiness is the same) looks like this:

```
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: "/health/live"
            port: 8080
            scheme: "HTTP"
```
**Environment (please complete the following information):**
 - Quarkus version or git rev: `1.3.0.Final`

### PR DESCRIPTION
**Pull request by iocanel**
Fixes: #8090

### CODE REVIEW

File: extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/ApplyHttpGetActionPortDecorator.java [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+import io.dekorate.deps.kubernetes.api.model.HTTPGetActionFluent;
+import io.dekorate.kubernetes.decorator.AddLivenessProbeDecorator;
+import io.dekorate.kubernetes.decorator.AddReadinessProbeDecorator;
+import io.dekorate.kubernetes.decorator.AddSidecarDecorator;
+import io.dekorate.kubernetes.decorator.ApplicationContainerDecorator;
+import io.dekorate.kubernetes.decorator.ContainerDecorator;
+import io.dekorate.kubernetes.decorator.Decorator;
+import io.dekorate.kubernetes.decorator.ResourceProvidingDecorator;
+
+public class ApplyHttpGetActionPortDecorator extends ApplicationContainerDecorator<HTTPGetActionFluent<?>> {
```
Comment (geoand) [inline extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/ApplyHttpGetActionPortDecorator.java]: I assume that this will be included in some future release dekorate so we can drop it from here  when that happens?

**Review by geoand — APPROVED** [review]
