### PR TITLE
Get hold of the assistant in another way

### LINKED ISSUE #49818: Quarkus dev mode not working for Hibernate ORM extension because of missing bean dependency
### Describe the bug

Generating a fresh Quarkus app using the latest version (3.26.1) that includes the Hibernate ORM extension and trying to start dev-mode leads to the following error:

```
jakarta.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type java.util.Optional<io.quarkus.assistant.runtime.dev.Assistant> and qualifiers [@Default]
    - injection target: io.quarkus.hibernate.orm.dev.ui.HibernateOrmDevJsonRpcService#assistant
    - declared on CLASS bean [types=[io.quarkus.hibernate.orm.dev.ui.HibernateOrmDevJsonRpcService, java.lang.Object], qualifiers=[@Any, @Default], target=io.quarkus.hibernate.orm.dev.ui.HibernateOrmDevJsonRpcService]
    The following beans match by type, but none has matching qualifiers:
    - PRODUCER METHOD bean [types=[java.lang.Object, java.util.Optional<T>], qualifiers=[@Any, @ConfigProperty], target=java.util.Optional<T> produceOptionalConfigProperty(jakarta.enterprise.inject.spi.InjectionPoint ip), declaringBean=io.smallrye.config.inject.ConfigProducer]


    at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:547)
    at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:689)
    at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:326)
    ... 12 more
```

Other extensions use the same `@Inject Optional<Assistant>` logic, but from some quick initial testing they seem to not be affected by this error.

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

Generate a Quarkus app from code.quarkus.io with the Hibernate ORM extension and launch `quarkus dev`.

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by phillip-kruger**
Fix #49818

This is due to Dev UI not being available. I think a better solution would be to advise all extensions to do this, but to drop the optional. This will need a new Chappie version, so for now this is the fix. Once I have make a change in Chappie I can get back to this and remove the optional.

I added a second commit that removed the Dev UI dependency completely. The only reason is there is due to the JsonRPCMessage. I changed Dev UI to allow passing in a Map for of this, then there is no need to depend on Dev UI.

We might also want to consider moving Dev UI Runtime to a Runtime Dev. (That will be the other option for this)

### CODE REVIEW

File: extensions/devui/runtime/src/main/java/io/quarkus/devui/runtime/comms/JsonRpcRouter.java [hunk 1]
```diff
@@ -202,15 +202,17 @@ private void routeToRuntimeMethod(JsonRpcRequest jsonRpcRequest, JsonRpcResponse
...
         uni.subscribe()
                 .with(item -> {
-                    if (item != null && JsonRpcMessage.class.isAssignableFrom(item.getClass())) {
-                        JsonRpcMessage<?> jsonRpcMessage = (JsonRpcMessage<?>) item;
-                        Object response = jsonRpcMessage.getResponse();
-                        if (jsonRpcMessage.isAlreadySerialized()) {
+                    if (item != null && Map.class.isAssignableFrom(item.getClass())) {
+                        Map map = (Map) item;
+                        if (map.size() == 3 && map.containsKey("alreadySerialized") && map.containsKey("messageType")
+                                && map.containsKey("response") && map.get("alreadySerialized").equals("true")) {
```
Comment (mbellade) [inline extensions/devui/runtime/src/main/java/io/quarkus/devui/runtime/comms/JsonRpcRouter.java:208]: I had added the `alreadySerialized` flag to `JsonRpcMessage` to allow for custom serialization, if we want `Map` to represent a custom response format it might be enough to check for `response` and `messageType` perhaps.

Also we can consider removing the flag from `JsonRpcMessage` altogether, as it won't be used anywhere else after this, to keep it clean.

File: extensions/hibernate-orm/runtime-dev/src/main/java/io/quarkus/hibernate/orm/dev/ui/HibernateOrmDevJsonRpcService.java [hunk 2]
```diff
@@ -151,53 +148,58 @@ public CompletionStage<JsonRpcMessage<String>> executeHQL(
         }
 
         if (Boolean.TRUE.equals(assistant)) {
-            Assistant a = this.assistant.orElse(null);
-            if (a == null || !a.isAvailable()) {
-                return errorDataSet(
-                        "The assistant is not available, please check the Quarkus assistant extension is correctly configured.");
-            }
+            if (this.assistant.isResolvable()) {
```
Comment (mbellade) [inline extensions/hibernate-orm/runtime-dev/src/main/java/io/quarkus/hibernate/orm/dev/ui/HibernateOrmDevJsonRpcService.java]: I'd return early to make it clearer we're failing in this case:

```suggestion
            if (!this.assistant.isResolvable()) {
                return errorDataSet(
                        "The Quarkus Assistant is not available, please install the Chappie extension.");
            }
```

**Review by mbellade — APPROVED** [review]
Thanks @phillip-kruger for working on this! I left a couple minor comments, I already tested the main change to `Instance` for the assistant injection and can confirm it solves the problem so +1

File: extensions/hibernate-orm/runtime-dev/src/main/java/io/quarkus/hibernate/orm/dev/ui/HibernateOrmDevJsonRpcService.java [hunk 3]
```diff
@@ -45,7 +42,7 @@ public class HibernateOrmDevJsonRpcService {
     private final String allowedHost;
 
     @Inject
-    Optional<Assistant> assistant;
+    Instance<Optional<Assistant>> assistant;
```
Comment (gsmet) [inline extensions/hibernate-orm/runtime-dev/src/main/java/io/quarkus/hibernate/orm/dev/ui/HibernateOrmDevJsonRpcService.java:45]: I think this pattern is very odd.

Your assistant CDI bean should be a `Assistant` IMHO, not an `Optional<Assistant>`. And then you just use `Instance` when injecting it.

This would be a lot more consistent with what we area doing elsewhere and what CDI offers.

Comment (phillip-kruger) [reply extensions/hibernate-orm/runtime-dev/src/main/java/io/quarkus/hibernate/orm/dev/ui/HibernateOrmDevJsonRpcService.java:45]: Like I mentioned in the chat - It's optional because it might be there (resolvable) but unconfigured.

Comment (phillip-kruger) [reply extensions/hibernate-orm/runtime-dev/src/main/java/io/quarkus/hibernate/orm/dev/ui/HibernateOrmDevJsonRpcService.java:45]: The other option is to have an AssistantHolder bean that has a `isAvailable` method on. This is problaby the cleanest way. The availability can change in runtime (if a user configure it)

Comment (phillip-kruger) [reply extensions/hibernate-orm/runtime-dev/src/main/java/io/quarkus/hibernate/orm/dev/ui/HibernateOrmDevJsonRpcService.java:45]: But that is a bigger change. So for now I would suggest we merge this and once that change is made in Quarkus and Chappie we can deprecate this way and change the documentation and know use of this. w.d.y.t ?

File: extensions/devui/runtime/src/main/java/io/quarkus/devui/runtime/comms/JsonRpcRouter.java (hunk 1 above)
Comment (phillip-kruger) [reply extensions/devui/runtime/src/main/java/io/quarkus/devui/runtime/comms/JsonRpcRouter.java:208]: Maybe we should keep the alreadySerialized in the map (but remove it from the Object). Keeping it on the map makes it less likely that someone wanted to return an actual map with these value
w.d.y.t ?

Comment (mbellade) [reply extensions/devui/runtime/src/main/java/io/quarkus/devui/runtime/comms/JsonRpcRouter.java:208]: Sure, I mean having exactly `response` and `messageType` would already be a good-enough discriminator IMO, but if you want to make it even more explicit that's fine. At that point I would say let's put `alreadySerialized` as a boolean value instead of `String.valueOf(true)`.

File: extensions/hibernate-orm/runtime-dev/src/main/java/io/quarkus/hibernate/orm/dev/ui/HibernateOrmDevJsonRpcService.java (hunk 3 above)
Comment (gsmet) [reply extensions/hibernate-orm/runtime-dev/src/main/java/io/quarkus/hibernate/orm/dev/ui/HibernateOrmDevJsonRpcService.java:45]: Fair enough :).

File: extensions/devui/runtime/src/main/java/io/quarkus/devui/runtime/comms/JsonRpcRouter.java (hunk 1 above)
Comment (phillip-kruger) [reply extensions/devui/runtime/src/main/java/io/quarkus/devui/runtime/comms/JsonRpcRouter.java:208]: I had to keep the Boolean a String, as Map<String,Object> did not work.

Comment (mbellade) [reply extensions/devui/runtime/src/main/java/io/quarkus/devui/runtime/comms/JsonRpcRouter.java:208]: Oh my bad, that's fine 👍

**Review by mbellade — APPROVED** [review]

**Review by gsmet — APPROVED** [review]
I see @mbellade is happy, let's merge and backport.
