### PR TITLE
Ability to handle both exit code and exception when running CLI applications

### LINKED ISSUE #12397: Exception Handling/Mapping When Running Quarkus Command Mode Applications
**Description**
Currently, command mode applications are unable to handle exceptions when executing the application but only provide a `Consumer<Integer>` to perform custom logic based on the exit code.

Applications should be able to catch any exception thrown during startup/execution in order to customize behavior or just shown better messages.

**Implementation ideas**
If we could change the [Quarkus.run](https://github.com/quarkusio/quarkus/blob/f98e0393664788f56169d055d585335f845ab8dd/core/runtime/src/main/java/io/quarkus/runtime/Quarkus.java#L52) method to accept a `BiConsumer` instead of a `Consumer`, applications could handle both exit code (as used today) as well as the exception that occurred.

I'm not sure about this line on [Quarkus.run](https://github.com/quarkusio/quarkus/blob/f98e0393664788f56169d055d585335f845ab8dd/core/runtime/src/main/java/io/quarkus/runtime/Quarkus.java#L67) which seems to indicate that exception mappers are expected to allow the proposed behavior. However, that catch block does not seem to be executed considering that the application exits at [ApplicationLifecycleManager.run](https://github.com/quarkusio/quarkus/blob/b95f4e494b26e9ae632fa8d927999dfff26b2d7b/core/runtime/src/main/java/io/quarkus/runtime/ApplicationLifecycleManager.java#L152).

### PR DESCRIPTION
**Pull request by pedroigor**
Fixes #12397
A few points:

* Basically, if an exit handler is provided we don't do any logging but leave to the custom exit handler to deal with both exit code and exception
* I've removed logging from `Application` so that any logging can be done depending on whether or not an exit handler is provided.

I'm not sure if that is the best approach but it helps to allow CLI applications to better handle messages to their users without necessarily show Quarkus messages and stack traces.

### CODE REVIEW

File: core/runtime/src/main/java/io/quarkus/runtime/ApplicationLifecycleManager.java [hunk 1]
```diff
@@ -136,10 +138,15 @@ public static void run(Application application, Class<? extends QuarkusApplicati
...
             }
         } catch (Exception e) {
-            if (appStarted) {
-                //we only log if the error occurred after the application was started
-                //as the generated application class already has logging
-                Logger.getLogger(Application.class).error("Error running Quarkus application", e);
+            if (exitCodeHandler == null) {
+                if (appStarted) {
+                    //we only log if the error occurred after the application was started
+                    //as the generated application class already has logging
```
Comment (stuartwdouglas) [inline core/runtime/src/main/java/io/quarkus/runtime/ApplicationLifecycleManager.java:144]: I don't think this is true any more.

File: core/runtime/src/main/java/io/quarkus/runtime/ApplicationLifecycleManager.java [hunk 2]
```diff
@@ -136,10 +138,15 @@ public static void run(Application application, Class<? extends QuarkusApplicati
...
+                    Logger.getLogger(Application.class).error("Error running Quarkus application", e);
+                } else {
+                    Logger.getLogger(Application.class).errorv(e, "Failed to start application (with profile {0})",
```
Comment (stuartwdouglas) [inline core/runtime/src/main/java/io/quarkus/runtime/ApplicationLifecycleManager.java:147]: I don't think the if statement is necessary here any more.

**Review by stuartwdouglas — CHANGES_REQUESTED** [review]
Just some minor comments otherwise looks good.

File: core/runtime/src/main/java/io/quarkus/runtime/ApplicationLifecycleManager.java (hunk 2 above)
Comment (pedroigor) [reply core/runtime/src/main/java/io/quarkus/runtime/ApplicationLifecycleManager.java:147]: I remember having `appStarted` == `true` indicating that the application was started but failed for some reason afterward. But I could not make it happen again. I thought the if the statement was intentional to differentiate errors in the different stages.

Going to remove.

**Review by stuartwdouglas — APPROVED** [review]
