### PR TITLE
Fail if more than one OIDC JWT credential key property is configured

### LINKED ISSUE #42920: Strange token generation/authentication behavior (oidc client)
### Describe the bug

Regarding https://github.com/quarkusio/quarkus/issues/40905

If the assertion property is set to true and secret is also provided, quarkus oidc client will try to use basic authentication header instead of the assertion form parameter. It generates opaque token instead of jwt bearer.

**!!! If the secret is removed then the jwt bearer auth is ok.**

Maybe when assertion is used then the secret just needs to be ignored if provided?

quarkus.oidc-client.salesforce.auth-server-url=
quarkus.oidc-client.salesforce.client-id=
quarkus.oidc-client.salesforce.credentials.jwt.key=
quarkus.oidc-client.salesforce.credentials.jwt.audience=
quarkus.oidc-client.salesforce.credentials.jwt.subject=
quarkus.oidc-client.salesforce.credentials.jwt.issuer=
quarkus.oidc-client.salesforce.credentials.jwt.lifespan=3600
quarkus.oidc-client.salesforce.grant.type=jwt
quarkus.oidc-client.salesforce.credentials.jwt.assertion=true
**#quarkus.oidc-client.salesforce.credentials.jwt.secret=**
quarkus.oidc-client.salesforce.token-path=/services/oauth2/token
quarkus.oidc-client.salesforce.discovery-enabled=false

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

3.13.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sberyozkin**
Fixes #42920.

This PR throws a `ConfigurationException` if more than one OIDC Credential JWT key property is configured as the consequences can be very confusing as shown in #42920.

OIDC Credential JWT group is used to configure various properties related to preparing a JWT authentication token which in turn is used to acquire an access token. The type of the key material can affect the way the JWT token is signed and can in turn impact how the OIDC provider handles it, which is why it is important to make sure only a single key property is used.

Other groups must also be reviewed, but I'll start with the JWT group.

Keeping in draft until I add a test

### CODE REVIEW

**Comment by sberyozkin** [comment]
Added a simple test to assert a failure is thrown if more than one JWT signing key or secret property is configured, was not 100% sure if a neater Java expression could be used though :-)

File: extensions/oidc-common/runtime/src/main/java/io/quarkus/oidc/common/runtime/OidcCommonUtils.java [hunk 1]
```diff
@@ -284,8 +284,23 @@ public static boolean isClientSecretBasicAuthRequired(Credentials creds) {
...
+            keyMaterialConfigCount++;
+        }
+        if (creds.jwt.keyFile.isPresent()) {
+            keyMaterialConfigCount++;
+        }
+        if (creds.jwt.keyStoreFile.isPresent()) {
+            keyMaterialConfigCount++;
+        }
+        if (keyMaterialConfigCount > 1) {
+            throw new ConfigurationException("Only a single OIDC JWT credential key property can be configured");
```
Comment (gastaldi) [inline extensions/oidc-common/runtime/src/main/java/io/quarkus/oidc/common/runtime/OidcCommonUtils.java:301]: This error is cryptic to me. Maybe specify the extra key properties already configured that are not mutually exclusive?

**Review by gastaldi — APPROVED** [review]

File: extensions/oidc-common/runtime/src/main/java/io/quarkus/oidc/common/runtime/OidcCommonUtils.java (hunk 1 above)
Comment (sberyozkin) [reply extensions/oidc-common/runtime/src/main/java/io/quarkus/oidc/common/runtime/OidcCommonUtils.java]: Hi @gastaldi Hopefully it looks better now, thanks :-)

Comment (sberyozkin) [reply extensions/oidc-common/runtime/src/main/java/io/quarkus/oidc/common/runtime/OidcCommonUtils.java]: @gastaldi Actually, sorry, I'll need to tweak it further, to correctly report `quarkus.oidc-client` vs `quarkus.oidc`, sorry

Comment (gastaldi) [reply extensions/oidc-common/runtime/src/main/java/io/quarkus/oidc/common/runtime/OidcCommonUtils.java]: No problem, I'll keep it approved as I trust you ;)

**Comment by sberyozkin** [comment]
Hi @gastaldi So now I've properly fixed it, I had to pass a boolean flag from `quarkus-oidc` and `quarkus-oidc-client` down to `OidcCommonUtils` to correctly determine the prefix. I also removed one redundant check there (from within the Apple POST JWT check function) since both at the `quarkus-oidc` and `quarkus-oidc-client` levels the Apple POST-JWT check is only done if the check I removed from the Apple POST JWT check already succeeded.
Sorry about it, I did not expect this PR be so tough for me :-)
