### PR TITLE
fix how defaultMode in Kubernetes volumes is parsed

### LINKED ISSUE #7722: defaultMode of a ConfigMap volume is 600 (decimal!) by default
**Describe the bug**

When I specify a ConfigMap volume using the Quarkus Kubernetes extension configuration properties, the volume has by default a `defaultMode` of `600`:

```yaml
      volumes:
      - configMap:
          defaultMode: 600
          name: "app-config"
          optional: false
        name: "app-config"
```

This is a decimal number, because it doesn't begin with `0`.

The Fabric8 Kubernetes client even warns about that: `Invalid value: 600: must be a number between 0 and 0777 (octal), both inclusive`.

The documentation says that default value here is `384` (which is `0600`). The corresponding `*Config` classes have `@ConfigItem(defaultValue = "0600")`, but apparently, when that string is converted to `int`, it's parsed as decimal, not octal.

**Expected behavior**
Default value of `defaultMode` is either `384` or `0600`.

**Actual behavior**
Default value of `defaultMode` is `600`.

**To Reproduce**
1. Add the `quarkus-kubernetes` extension.
2. Specify a ConfigMap in `application.properties`.
3. Run `mvn clean package -DskipTests`.
4. See `target/kubernetes/*.yml`.

**Configuration**
```properties
quarkus.kubernetes.deployment-target=openshift
quarkus.openshift.config-map-volumes.app-config.config-map-name=app-config
quarkus.openshift.mounts.app-config.path=/deployments/config
```

### PR DESCRIPTION
**Pull request by Ladicek**
Previously, the `defaultMode` config property of some Kubernetes
volumes (ConfigMap, secret) was always treated as a decimal number,
even though octal number is a common format (and we actually used
an octal number when specifying the default value!).

This commit changes the type of the config property to `String`,
which is later parsed to an `int` when calling the Dekorate API.
At that time, if the string begins with `0`, it's parsed as octal,
otherwise as decimal.

Fixes #7722.

### CODE REVIEW

File: extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/SecretVolumeConfig.java [hunk 1]
```diff
@@ -1,21 +1,25 @@
 package io.quarkus.kubernetes.deployment;
 
+import io.quarkus.runtime.annotations.ConfigGroup;
 import io.quarkus.runtime.annotations.ConfigItem;
 
+@ConfigGroup
```
Comment (Ladicek) [inline extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/SecretVolumeConfig.java]: I don't know why, but this annotation is present in similar classes (`ConfigMapVolumeConfig`, `PvcVolumeConfig`), but it wasn't here. I added it, but I don't know what I'm doing :-)

File: extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/SecretVolumeConfig.java [hunk 2]
```diff
@@ -1,21 +1,25 @@
...
 public class SecretVolumeConfig {
 
     /**
      * The name of the secret to mount.
      */
+    @ConfigItem
```
Comment (Ladicek) [inline extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/SecretVolumeConfig.java]: Same here.

File: extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/SecretVolumeConfig.java (hunk 1 above)
Comment (geoand) [reply extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/SecretVolumeConfig.java]: It's correct, nice catch!

**Review by geoand — APPROVED** [review]
Excellent, thanks!

File: docs/src/main/asciidoc/kubernetes.adoc [hunk 3]
```diff
@@ -464,15 +464,15 @@ Below you will find tables describing all available types.
...
 |====
 
 .SecretVolume
 |====
 | Property     | Type    | Description | Default Value
 | secret-name  | String  |             |
-| default-mode | int     |             | 384           
+| default-mode | int     |             | 0600
 | optional     | boolean |             | false
 |====
```
Comment (gsmet) [inline docs/src/main/asciidoc/kubernetes.adoc]: Could someone really have a look to the generated documentation and see if we can use it?

If we have proper Quarkus config now, it will really be a big win.

Comment (geoand) [reply docs/src/main/asciidoc/kubernetes.adoc]: @iocanel didn't you say you were going to look into it?

Comment (gsmet) [reply docs/src/main/asciidoc/kubernetes.adoc]: Maybe I will have a look and see how it goes.

Comment (gsmet) [reply docs/src/main/asciidoc/kubernetes.adoc]: BTW, one things that bugs me is that we have things like `timeout-seconds` in the doc.

I don't know how they have been translated in Quarkus config but they should be `Duration` and named `timeout` without `-seconds`.

That's really something we want done before Final so either @iocanel can have a look or I will, just tell me.

Comment (iocanel) [reply docs/src/main/asciidoc/kubernetes.adoc]: I will

**Review by iocanel — APPROVED** [review]
LGTM

File: docs/src/main/asciidoc/kubernetes.adoc (hunk 3 above)
Comment (gsmet) [reply docs/src/main/asciidoc/kubernetes.adoc]: @iocanel feel free to ping me if you need some help or guidance on this one.
