### PR TITLE
ArC - fix regression with repeatable interceptor bindings

### LINKED ISSUE #21174: Multiple cache invalidation not working with a native build
### Describe the bug

Hello, 
I have a REST endpoint to invalidate all my caches like so:

```
    @DELETE
    @CacheInvalidateAll(cacheName = Caches.MY_CACHE_A)
    @CacheInvalidateAll(cacheName = Caches.MY_CACHE_B)
    @CacheInvalidateAll(cacheName = Caches.MY_CACHE_C)
    public void invalidateCaches() {
        logger.info("Invalidating declared caches");
    }
```

When running in dev mode, everything is fine. The DEBUG logs shows that all caches are properly invalidated :

```
2021-11-03 15:06:12,757 DEBUG [io.qua.cac.run.CacheInvalidateAllInterceptor] (executor-thread-0) Invalidating all entries from cache ["cacheA"]
2021-11-03 15:06:12,759 DEBUG [io.qua.cac.run.CacheInvalidateAllInterceptor] (executor-thread-0) Invalidating all entries from cache ["cacheB"]
2021-11-03 15:06:12,759 DEBUG [io.qua.cac.run.CacheInvalidateAllInterceptor] (executor-thread-0) Invalidating all entries from cache ["cacheC"]
```

When running in native mode, a bug investigation revealed that only one cache is invalidated. This was reproduced on locahost. Calls to other resources use data from the cache instead of calling the backends.
`2021-11-03 15:06:12,759 DEBUG [io.qua.cac.run.CacheInvalidateAllInterceptor] (executor-thread-0) Invalidating all entries from cache ["cacheB"]`

(i have changed the cache names above but even after changing the order of the 3 annotations, it was always the same cache that was invalidated)

A temporary workaround is to have my multi-annotated method to delegate the invalidation to as many sub methods as necessary, each one with its own invalidation. Obviously that is the opposite of the interest to have multiple annotations. 

(And as a side note, i know this is somewhere on the roadmap: being able to programmatically invalidate all caches from my enum instead of adding/forgetting to add an annotation would even be better)

Thanks for your help !
Pascal.

### Expected behavior

All caches mentionned in each annotation are flushed.

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

Linux Sunnyvale 5.4.0-89-generic #100-Ubuntu SMP Fri Sep 24 14:50:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.12" 2021-07-20

### GraalVM version (if different from Java)

OpenJDK Runtime Environment GraalVM CE 21.2.0 (build 11.0.12+6-jvmci-21.2-b08)

### Quarkus version or git rev

2.1.4.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 6.8.3

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mkouba**
- register all interceptor bindings for reflection so that
javax.enterprise.util.AnnotationLiteral.equals(Object) works in a native
image
- do not use java.util.Set#of(Object...) directly because it throws an
IAE if there are duplicate elements
- resolves #21174

### CODE REVIEW

File: independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl/Sets.java [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+    public static <E> Set<E> of(E... elements) {
+        switch (elements.length) {
+            case 0:
+                return Set.of();
+            case 1:
+                return Set.of(elements[0]);
+            case 2:
+                return elements[0].equals(elements[1]) ? Set.of(elements[0]) : Set.of(elements[0], elements[1]);
+            default:
+                return Set.copyOf(Arrays.asList(elements));
```
Comment (mkouba) [inline independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl/Sets.java:29]: This is suboptimal (a list and a `HashSet` is created) but it should not be a problem because we don't use this method in a hot path.

**Comment by gsmet** [comment]
Should we backport this to 2.4?

**Comment by gwenneg** [comment]
> Should we backport this to 2.4?

This fixes a 2.4 regression so I'd say yes.

**Comment by gsmet** [comment]
I will release a 2.4.2.Final probably on Wednesday (might be Friday though depending on how CR1 goes) so it would be nice if someone could review this one by Tuesday evening Paris time.

Thanks.

**Comment by mkouba** [comment]
The "Native Tests - Windows - hibernate-validator" failure is not related: `LINK : fatal error LNK1171: unable to load mspdbcore.dll (error code: 1455)`.

File: integration-tests/main/src/main/java/io/quarkus/it/arc/interceptor/TestSimleBeanEndpoint.java [hunk 2]
```diff
@@ -0,0 +1,19 @@
+package io.quarkus.it.arc.interceptor;
+
+import javax.inject.Inject;
+import javax.ws.rs.GET;
+import javax.ws.rs.Path;
+
+@Path("/simple-bean")
+public class TestSimleBeanEndpoint {
```
Comment (Ladicek) [inline integration-tests/main/src/main/java/io/quarkus/it/arc/interceptor/TestSimleBeanEndpoint.java:8]: `Simle` -> `Simple` :-)

**Review by Ladicek — APPROVED** [review]

**Comment by mkouba** [comment]
@gwenneg did you get a chance to test this PR with your reproducer? I think I did test it and worked but it's better to doublecheck ;-).

**Comment by gwenneg** [comment]
> @gwenneg did you get a chance to test this PR with your reproducer? I think I did test it and worked but it's better to doublecheck ;-).

Not yet but I'll do it by the end of the day. Thanks for the fix!

**Comment by gwenneg** [comment]
@mkouba Fix tested and confirmed with the reproducer.

I thought I would have to fix the other issue from #21174 but the cache invalidation works with all caches when multiple `@CacheInvalidateAll` annotations are added to the same method. Did you fix that in this PR or was it fixed elsewhere?

**Comment by mkouba** [comment]
> I thought I would have to fix the other issue from #21174 but the cache invalidation works with all caches when multiple `@CacheInvalidateAll` annotations are added to the same method. Did you fix that in this PR or was it fixed elsewhere?

TBH I don't know what the other issue was about?

**Comment by gwenneg** [comment]
When a method was annotated with `n` @CacheInvalidateAll annotations, the cache interceptor would be executed `n` times in JVM mode and only `once` in native mode. I suspected the issue didn't come from the extension itself but rather from ArC. But since it's all working now, it's ok to close #21174.

**Comment by mkouba** [comment]
> When a method was annotated with `n` @CacheInvalidateAll annotations, the cache interceptor would be executed `n` times in JVM mode and only `once` in native mode.

Ah, ok. So this PR should fix this problem as well - previously the set of interceptor bindings contained only one `@CacheInvalidateAll` in native mode (because all annotations were considered equal).
