### PR TITLE
Define global timeout attributes for REST Clients

### LINKED ISSUE #22862: Rest Client exausts Threads.
### Describe the bug

This is a major issue for us.
I have dozens of services in prod that from time to time they freeze due to thread exhaustion. The vertex event loop stalls. 
his can be traced back to unconfigured timeouts on rest clients that hog connections. 
We need to go to all rest clients and specify connection and read timeouts on configurations, like:
```
com.td.wfm.common.client.SomeRestClientClass/mp-rest/connectTimeout=500
com.td.wfm.common.client.SomeRestClientClass/mp-rest/readTimeout=1000
```
If you use programatic rest creation you must:
```
        return RestClientBuilder.newBuilder()
                                .baseUri(URI.create(uri))
                                .connectTimeout(connectionTimeout, TimeUnit.MILLISECONDS)
                                .readTimeout(readTimeout, TimeUnit.MILLISECONDS)
                                //...
```

There are many issues related with this. See:
https://github.com/quarkusio/quarkus/issues/15056
https://github.com/quarkusio/quarkus/issues/15383
https://github.com/quarkusio/quarkus/issues/15191

This happens on 1.13.7.Final but I believe 2.* suffers from the same problem.

### Expected behavior

If the REST Client connection is half closed in the other side, it will timeout after a default amount of time. 

### Actual behavior

If the REST Client connection is half closed in the other side it will never timeout.

### How to Reproduce?

You need a rest client calling an endpoint in a loop, in different threads. The other side must hold the connection and not reply. 

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

11

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

1.13.7.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by TomasHofman**
Added global timeout attributes for rest clients:

quarkus.rest-client.connect-timeout
quarkus.rest-client.read-timeout

The default values are 15000 and 30000 ms respectively.

This resolves https://github.com/quarkusio/quarkus/issues/22862

### CODE REVIEW

**Comment by geoand** [comment]
Wouldn't it be best to use `Duration` as the type?

**Comment by radcortez** [comment]
> Wouldn't it be best to use `Duration` as the type?

Yes, but unfortunately we have defined the timeouts to be `Long` if you use the configuration per client:
https://quarkus.io/guides/all-config#quarkus-rest-client-config_quarkus.rest-client.-config-key-.connect-timeout
https://quarkus.io/guides/all-config#quarkus-rest-client-config_quarkus.rest-client.-config-key-.read-timeout

So they need to be consistent. Changing this to a `Duration` won't work either, because when no units are set, it assumes seconds and here we use milliseconds. We could provide a specific converter for `Duration` that would assume that these values are milliseconds, but it will be a different behavior from other places we use `Duration`. 

Another option is to just add new properties that take the duration and convert the old value to seconds internally.

File: extensions/resteasy-classic/rest-client-config/runtime/src/main/java/io/quarkus/restclient/config/RestClientsConfig.java [hunk 1]
```diff
@@ -95,6 +95,20 @@
 
     public RestClientLoggingConfig logging;
 
+    /**
+     * Global default connect timeout for automatically generated REST Clients. The attribute specifies a timeout
+     * in milliseconds that a client should wait to connect to the remote endpoint.
+     */
+    @ConfigItem(defaultValue = "15000", defaultValueDocumentation = "15000 ms")
+    public Optional<Long> connectTimeout = Optional.empty();
```
Comment (radcortez) [inline extensions/resteasy-classic/rest-client-config/runtime/src/main/java/io/quarkus/restclient/config/RestClientsConfig.java:103]: Do we want an `Optional` here if we have a default value? The Optional will always have a value unless the user sets the key as empty.

File: extensions/resteasy-classic/rest-client-config/runtime/src/main/java/io/quarkus/restclient/config/RestClientsConfig.java [hunk 2]
```diff
@@ -95,6 +95,20 @@
...
+
+    /**
+     * Global default read timeout for automatically generated REST Clients. The attribute specifies a timeout
+     * in milliseconds that a client should wait for a response from the remote endpoint.
+     */
+    @ConfigItem(defaultValue = "30000", defaultValueDocumentation = "30000 ms")
+    public Optional<Long> readTimeout = Optional.empty();
```
Comment (radcortez) [inline extensions/resteasy-classic/rest-client-config/runtime/src/main/java/io/quarkus/restclient/config/RestClientsConfig.java:110]: Do we want an `Optional` here if we have a default value? The Optional will always have a value unless the user sets the key as empty.

File: extensions/resteasy-classic/rest-client/runtime/src/main/java/io/quarkus/restclient/runtime/RestClientBase.java [hunk 3]
```diff
@@ -322,10 +322,13 @@ private RestClientConfig clientConfigByClassName() {
         return this.configRoot.getClientConfig(this.proxyType);
     }
 
-    private static <T> Optional<T> oneOf(Optional<T> o1, Optional<T> o2) {
-        if (o1.isPresent()) {
-            return o1;
+    @SafeVarargs
+    private static <T> Optional<T> oneOf(Optional<T>... optionals) {
```
Comment (radcortez) [inline extensions/resteasy-classic/rest-client/runtime/src/main/java/io/quarkus/restclient/runtime/RestClientBase.java:326]: If we assume that the global values don't need to be `Optional`, then we just use `orElse` if the specific client property is not available.

**Review by radcortez — CHANGES_REQUESTED** [review]

File: extensions/resteasy-classic/rest-client-config/runtime/src/main/java/io/quarkus/restclient/config/RestClientsConfig.java [hunk 4]
```diff
@@ -43,7 +43,7 @@
      * This property is applicable to reactive REST clients only.
      */
     @ConfigItem(defaultValue = "false")
-    public Optional<Boolean> disableSmartProduces;
+    public Optional<Boolean> disableSmartProduces = Optional.empty();
```
Comment (michalszynkiewicz) [inline extensions/resteasy-classic/rest-client-config/runtime/src/main/java/io/quarkus/restclient/config/RestClientsConfig.java:46]: is there any point in initializing these fields?

**Comment by michalszynkiewicz** [comment]
from the rest client's internals perspective, it looks good to me (and uses the defeaults we have in rest client reactive as the defaults)

File: extensions/resteasy-classic/rest-client-config/runtime/src/main/java/io/quarkus/restclient/config/RestClientsConfig.java (hunk 4 above)
Comment (TomasHofman) [reply extensions/resteasy-classic/rest-client-config/runtime/src/main/java/io/quarkus/restclient/config/RestClientsConfig.java:46]: I added it so that the fields are not null in certain tests, but probably it will be better to handle that in the test class rather than here in the config root. Will fix.

**Comment by TomasHofman** [comment]
> > Wouldn't it be best to use `Duration` as the type?
> 
> Yes, but unfortunately we have defined the timeouts to be `Long` if you use the configuration per client: https://quarkus.io/guides/all-config#quarkus-rest-client-config_quarkus.rest-client.-config-key-.connect-timeout https://quarkus.io/guides/all-config#quarkus-rest-client-config_quarkus.rest-client.-config-key-.read-timeout
> 
> So they need to be consistent. Changing this to a `Duration` won't work either, because when no units are set, it assumes seconds and here we use milliseconds. We could provide a specific converter for `Duration` that would assume that these values are milliseconds, but it will be a different behavior from other places we use `Duration`.
> 
> Another option is to just add new properties that take the duration and convert the old value to seconds internally.

I noticed the `Duration` discrepancy too, but I don't know if it's a good idea to change that now, considering backward compatibility and consistency issues.

For the original non-global `read-timeout` & `connect-timeout` properties, the MP spec says they should be given in milliseconds. As @radcortez says, if we change these to `Duration`, the default unit changes from milliseconds to seconds, which will be inconsistent with spec and also change the meaning of existing configurations without people noticing.

File: extensions/resteasy-classic/rest-client-config/runtime/src/main/java/io/quarkus/restclient/config/RestClientsConfig.java (hunk 2 above)
Comment (TomasHofman) [reply extensions/resteasy-classic/rest-client-config/runtime/src/main/java/io/quarkus/restclient/config/RestClientsConfig.java]: OK, I made it `Long`.

**Review by radcortez — APPROVED** [review]
