### PR TITLE
Make Picocli version providers unremovable classes

### LINKED ISSUE #38077: picocli should be able to mark its annotation dependent classes as unremovable
### Description

For example:

```java
@Command(name = "hassq", mixinStandardHelpOptions = true, 
          subcommands = { StateCommand.class, AreaCommand.class, EntityCommand.class, EventCommand.class, ConfigCommand.class},
          versionProvider = VersionProvider.class)
```

and then VersionProvider looks like this:

```java
@Unremovable @Singleton
public class VersionProvider implements IVersionProvider {

    @ConfigProperty(name = "quarkus.application.version")
    String version;

    @Override
    public String[] getVersion() throws Exception {
        return new String[] { version };
    }
}
```

This is picked up by quarkus picocli extension as we provided a picocli IFactory.

It shouldn't be necessary to specify @Unremovable in this case should it ?  Right now it is required though.

There are multiple other class references via annotation in picocli apis:

```
rg "Class<\? extends .*>.*default"
src/main/java/picocli/CommandLine.java
3960:        Class<? extends ITypeConverter<?>>[] converter() default {};
4016:        Class<? extends Iterable<String>> completionCandidates() default NoCompletionCandidates.class;
4126:        Class<? extends IParameterConsumer> parameterConsumer() default NullParameterConsumer.class;
4131:        Class<? extends IParameterPreprocessor> preprocessor() default NoOpParameterPreprocessor.class;
4262:        Class<? extends ITypeConverter<?>>[] converter() default {};
4313:        Class<? extends Iterable<String>> completionCandidates() default NoCompletionCandidates.class;
4360:        Class<? extends IParameterConsumer> parameterConsumer() default NullParameterConsumer.class;
4377:        Class<? extends IParameterPreprocessor> preprocessor() default NoOpParameterPreprocessor.class;
4642:        Class<? extends IVersionProvider> versionProvider() default NoVersionProvider.class;
4757:        Class<? extends IDefaultValueProvider> defaultValueProvider() default NoDefaultProvider.class;
4876:        Class<? extends IModelTransformer> modelTransformer() default NoOpModelTransformer.class;
4881:        Class<? extends IParameterPreprocessor> preprocessor() default NoOpParameterPreprocessor.class;
```

and I expect all of these will today require @Unremovable even though we should be able to detect that picocli will eventually need them.

Suggestion is thus that Arc gets instructed to leave these around if beans are of any of those types.

Anyone see an issue making this happen? 

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by geoand**
- Closes: https://github.com/quarkusio/quarkus/issues/38077

### CODE REVIEW

File: extensions/picocli/deployment/src/main/java/io/quarkus/picocli/deployment/PicocliProcessor.java [hunk 1]
```diff
@@ -99,6 +104,20 @@ void picocliRunner(ApplicationIndexBuildItem applicationIndex,
...
         }
+
+        // make the arguments of @Command unremovable beans if necessary
+        Collection<AnnotationInstance> commandInstances = index.getAnnotations(CommandLine.Command.class);
+        for (AnnotationInstance commandInstance : commandInstances) {
+            AnnotationValue versionProvider = commandInstance.value("versionProvider");
+            if (versionProvider != null) {
+                ClassInfo versionProviderInfo = index.getClassByName(versionProvider.asClass().name());
+                if (versionProviderInfo != null) {
+                    if (BuiltinScope.isDeclaredOn(versionProviderInfo)) { // TODO: should we make these beans even when they are not annotated as such?
```
[the remark this answers is not in the document]
Comment (geoand) [reply extensions/picocli/deployment/src/main/java/io/quarkus/picocli/deployment/PicocliProcessor.java:115]: Good catch, that's almost certainly the case!

[the remark this answers is not in the document]
Comment (mkouba) [reply extensions/picocli/deployment/src/main/java/io/quarkus/picocli/deployment/PicocliProcessor.java:115]: > My understanding is that unremovable won't make them beans. It will just avoid beans to be dropped by the optimizations.

That's correct.

[the remark this answers is not in the document]
Comment (geoand) [reply extensions/picocli/deployment/src/main/java/io/quarkus/picocli/deployment/PicocliProcessor.java]: 👍🏼

**Comment by maxandersen** [comment]
related to #38077

File: extensions/picocli/deployment/src/main/java/io/quarkus/picocli/deployment/PicocliProcessor.java [hunk 2]
```diff
@@ -99,6 +104,19 @@ void picocliRunner(ApplicationIndexBuildItem applicationIndex,
...
         }
+
+        // make the arguments of @Command unremovable beans if necessary
+        Collection<AnnotationInstance> commandInstances = index.getAnnotations(CommandLine.Command.class);
+        for (AnnotationInstance commandInstance : commandInstances) {
+            AnnotationValue versionProvider = commandInstance.value("versionProvider");
+            if (versionProvider != null) {
+                ClassInfo versionProviderInfo = index.getClassByName(versionProvider.asClass().name());
+                if (versionProviderInfo != null) {
+                    // TODO: should we make these beans even when they are not annotated as such?
```
Comment (maxandersen) [inline extensions/picocli/deployment/src/main/java/io/quarkus/picocli/deployment/PicocliProcessor.java:115]: I don't think so. 

Do we have examples of keeping other things around we don't have any explicit reference to in annotations/config ?

Comment (geoand) [reply extensions/picocli/deployment/src/main/java/io/quarkus/picocli/deployment/PicocliProcessor.java:115]: I can't remember off hand, but I am pretty we do.

File: extensions/picocli/deployment/src/main/java/io/quarkus/picocli/deployment/PicocliProcessor.java [hunk 3]
```diff
@@ -99,6 +104,19 @@ void picocliRunner(ApplicationIndexBuildItem applicationIndex,
             additionalBean.produce(AdditionalBeanBuildItem.unremovableOf(DefaultPicocliCommandLineFactory.class));
             quarkusApplicationClass.produce(new QuarkusApplicationClassBuildItem(PicocliRunner.class));
         }
+
+        // make the arguments of @Command unremovable beans if necessary
+        Collection<AnnotationInstance> commandInstances = index.getAnnotations(CommandLine.Command.class);
+        for (AnnotationInstance commandInstance : commandInstances) {
+            AnnotationValue versionProvider = commandInstance.value("versionProvider");
```
Comment (maxandersen) [inline extensions/picocli/deployment/src/main/java/io/quarkus/picocli/deployment/PicocliProcessor.java:111]: so should we lookup all of the names referenced in #38077 and fix it for all of them?

```
converter
completionCandidates parameterConsumer
preprocessor
converter
completionCandidates
parameterConsumer
preprocessor
versionProvider
defaultValueProvider
modelTransformer
preprocessor
```

?

Comment (geoand) [reply extensions/picocli/deployment/src/main/java/io/quarkus/picocli/deployment/PicocliProcessor.java:111]: I would prefer we do it on a case by case basis as doing it too broadly could cause problems (mostly because we none of us knows what those are used for)

Comment (maxandersen) [reply extensions/picocli/deployment/src/main/java/io/quarkus/picocli/deployment/PicocliProcessor.java:111]: well, I do :) 

These are all config options on picocli commands where picocli uses IFactory to instantiate them.

We provide IFactory to have these created - and just like VersionProvider here if user don't put @Unremovable on them cannot configure them via CDI beans and MUST add @Unremovable to have it to work.

afaics since we wont register them as unremovable *unless* they are referenced by users picocli and if they don't make that class a @Singleton or some scope then it will just instantiate as a regular instance - so no difference in performance/impact unless user actually does make a bean ?

File: extensions/picocli/deployment/src/main/java/io/quarkus/picocli/deployment/PicocliProcessor.java (hunk 2 above)
Comment (maxandersen) [reply extensions/picocli/deployment/src/main/java/io/quarkus/picocli/deployment/PicocliProcessor.java:115]: the only reason I could see that be relevant is if you use picocli programmatic API and circumvent the annotation setup ...but I don't see that as being the job of Quarkus to make all such possible subclasses unremovable by default for that edge case.

File: extensions/picocli/deployment/src/main/java/io/quarkus/picocli/deployment/PicocliProcessor.java (hunk 3 above)
Comment (geoand) [reply extensions/picocli/deployment/src/main/java/io/quarkus/picocli/deployment/PicocliProcessor.java:111]: I know we do provide a factory :). I guess reading it's docs it's safe to say that it is always used for the classes you mention.

Comment (geoand) [reply extensions/picocli/deployment/src/main/java/io/quarkus/picocli/deployment/PicocliProcessor.java]: PR updated

File: extensions/picocli/deployment/src/main/java/io/quarkus/picocli/deployment/PicocliProcessor.java [hunk 4]
```diff
@@ -99,6 +101,17 @@ void picocliRunner(ApplicationIndexBuildItem applicationIndex,
             additionalBean.produce(AdditionalBeanBuildItem.unremovableOf(DefaultPicocliCommandLineFactory.class));
             quarkusApplicationClass.produce(new QuarkusApplicationClassBuildItem(PicocliRunner.class));
         }
+
+        // Make all classes that can be instantiated by IFactory unremovable
+        unremovableBean.produce(UnremovableBeanBuildItem.beanTypes(CommandLine.ITypeConverter.class,
```
Comment (maxandersen) [inline extensions/picocli/deployment/src/main/java/io/quarkus/picocli/deployment/PicocliProcessor.java:106]: Ok - so this is doing it for all instances even if not referenced by picocli config.

Just curious why you do it this way when we only have to do it for those pointed to by users annotation?

Ease of coding in quarkus or that you don't believe it will matter enough in extra memory used ?

Comment (geoand) [reply extensions/picocli/deployment/src/main/java/io/quarkus/picocli/deployment/PicocliProcessor.java:106]: > Ok - so this is doing it for all instances even if not referenced by picocli config.

All it does it make beans of this type unremovable - nothing more

Comment (geoand) [reply extensions/picocli/deployment/src/main/java/io/quarkus/picocli/deployment/PicocliProcessor.java:106]: > Just curious why you do it this way when we only have to do it for those pointed to by users annotation?

This way is much much cleaner and also makes chances of copy-paste errors in the code far lower.

**Review by gsmet — APPROVED** [review]
