### PR TITLE
Fix broken sidecar handling

### LINKED ISSUE #10308: Quarkus kubernetes sidecars configs do not work
**Describe the bug**
Hi,

I am trying to generate sidecar configs using quarkus application.properties. I have below in my application.properties.

quarkus.kubernetes.sidecars.abc.image=def/abc
quarkus.kubernetes.sidecars.abc.ports[0].containerPort=3000
quarkus.kubernetes.sidecars.abc.arguments[0]=--config=/etc/abc/abc.conf
quarkus.kubernetes.sidecars.abc.mount[0].path=/etc/abc

It is supposed to configure abc sidecontainer in kubernetes.yml. But it is not. Main app container is correctly there along with other manifests (e.g. Service, ServiceAccount etc.) in the kubernetes.yml
Is there any issue with my properties? or it is not supported in Quarkus.

Reference:
https://quarkus.io/guides/deploying-to-kubernetes

**Expected behavior**
Sidecar container should be created in kubernetes.yml

**Actual behavior**
No sidecar container is created in kubernetes.yml

**To Reproduce**
1. Copy below configs in application.properties of a quarkus kubernetes project

quarkus.kubernetes.sidecars.abc.image=def/abc
quarkus.kubernetes.sidecars.abc.ports[0].containerPort=3000
quarkus.kubernetes.sidecars.abc.arguments[0]=--config=/etc/abc/abc.conf
quarkus.kubernetes.sidecars.abc.mount[0].path=/etc/abc

2.Build the project 

**Configuration**
```properties

quarkus.kubernetes.sidecars.abc.image=def/abc
quarkus.kubernetes.sidecars.abc.ports[0].containerPort=3000
quarkus.kubernetes.sidecars.abc.arguments[0]=--config=/etc/abc/abc.conf
quarkus.kubernetes.sidecars.abc.mount[0].path=/etc/abc

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: 
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 

**Additional context**
(Add any other context about the problem here.)

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #10308

### CODE REVIEW

**Comment by geoand** [comment]
@iocanel These fixes belong in dekorate IMHO, but I would prefer we keep them here for now so we can get the original issue fixed for 1.6.
When we have a new dekorate release that includes these changes, we can revert the decorator and adapter related changes made here.

File: extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/AddSidecarDecorator.java [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+import io.dekorate.deps.kubernetes.api.model.PodSpecBuilder;
+import io.dekorate.kubernetes.config.Container;
+import io.dekorate.kubernetes.decorator.Decorator;
+import io.dekorate.kubernetes.decorator.NamedResourceDecorator;
+import io.dekorate.kubernetes.decorator.ResourceProvidingDecorator;
+
+/**
+ * Copied from dekorate in order to fix some issues
+ */
+class AddSidecarDecorator extends NamedResourceDecorator<PodSpecBuilder> {
```
Comment (iocanel) [inline extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/AddSidecarDecorator.java:13]: The class seems identical to the upstream version. Can you please point out the difference?

File: extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/AddContainerPortDecorator.java [hunk 2]
```diff
@@ -0,0 +1,36 @@
...
+import io.dekorate.kubernetes.decorator.AddSidecarDecorator;
+import io.dekorate.kubernetes.decorator.ContainerDecorator;
+import io.dekorate.kubernetes.decorator.Decorator;
+import io.dekorate.kubernetes.decorator.ResourceProvidingDecorator;
+
+/**
+ * Adapted from Dekorate's {@link io.dekorate.kubernetes.decorator.AddPortDecorator} in order to
+ * address the limitation that the port was not being added (due to missing metadata)
+ */
+class AddContainerPortDecorator extends Decorator<ContainerBuilder> {
```
Comment (iocanel) [inline extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/AddContainerPortDecorator.java:15]: It's not obvious to me what's wrong with the upstream version.

Also, keep in mind that this implementation will result in the port being applied to all containers of all deployments (including init containers, sidecars or any other kind of container generated, or found under /src/main/kubernetes).

File: extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/ContainerAdapter.java [hunk 3]
```diff
@@ -0,0 +1,52 @@
...
+import io.dekorate.kubernetes.decorator.AddMountDecorator;
+import io.dekorate.kubernetes.decorator.AddReadinessProbeDecorator;
+import io.dekorate.kubernetes.decorator.ApplyImagePullPolicyDecorator;
+import io.dekorate.utils.Images;
+import io.dekorate.utils.Strings;
+
+/**
+ * Copied from dekorate in order to fix some issues
+ */
+public class ContainerAdapter {
```
Comment (iocanel) [inline extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/ContainerAdapter.java:19]: Ok, I now see why you needed to copy the sidecar decorator...

File: extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/ContainerAdapter.java [hunk 4]
```diff
@@ -0,0 +1,52 @@
...
+    public static Container adapt(io.dekorate.kubernetes.config.Container container) {
+        String name = container.getName();
+        if (Strings.isNullOrEmpty(name)) {
+            name = Images.getName(container.getImage());
+        }
+
+        ContainerBuilder builder = new ContainerBuilder()
+                .withName(name)
+                .withImage(container.getImage())
+                // this was changed to add working dir
```
Comment (iocanel) [inline extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/ContainerAdapter.java:30]: We will have to apply that upstream as well

File: extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/AddContainerPortDecorator.java [hunk 5]
```diff
@@ -0,0 +1,36 @@
...
+
+    private final Port port;
+
+    AddContainerPortDecorator(Port port) {
+        this.port = port;
+    }
+
+    @Override
+    public void visit(ContainerBuilder containerBuilder) {
+        containerBuilder.addNewPort()
```
Comment (iocanel) [inline extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/AddContainerPortDecorator.java:25]: What happens if the container you add has a port named after the port you are trying to add?

**Review by iocanel — COMMENTED** [review]
Looks good. It's not clear to me through what was the issue with the original `AddPort` decorator?

File: extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/AddSidecarDecorator.java (hunk 1 above)
Comment (geoand) [reply extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/AddSidecarDecorator.java:13]: It uses our custom `ContainerAdapter`, that's the only change

File: extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/AddContainerPortDecorator.java (hunk 2 above)
Comment (geoand) [reply extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/AddContainerPortDecorator.java:15]: The upstream version doesn't apply the port because the object contains no metadata.

I am pretty certain that this decorator doesn't apply to all containers and if I am not mistaken, my test verifies that

File: extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/ContainerAdapter.java (hunk 4 above)
Comment (geoand) [reply extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/ContainerAdapter.java:30]: Yes of course. I just wanted to get these changes in Quarkus so we can include the fixes in 1.6 which is right around the corner.

**Review by iocanel — APPROVED** [review]
LGTM

File: extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/AddContainerPortDecorator.java (hunk 5 above)
Comment (geoand) [reply extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/AddContainerPortDecorator.java:25]: That probably won't go down well, but I think it's rather unlikely to happen, no?
