### PR TITLE
Make application version and name available as (fixed) runtime properties

### LINKED ISSUE #6255: quarkus.application.version config property is unavailable
**Describe the bug**
The following config property injection doesn't work: 
```java
@Path("/hello")
public class GreetingResource {

    @ConfigProperty(name = "quarkus.application.version", defaultValue = "not-set")
    String version;

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        return "hello " + version;
    }
}
```
**Expected behavior**

When running `http localhost:8080/hello`, to return `hello 1.0.0-SNAPSHOT`

**Actual behavior**
When running `http localhost:8080/hello`, it returns `hello not-set`

**To Reproduce**
1. Create a sample project and add the endpoint above

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #6255

Relates to: #6267

### CODE REVIEW

**Comment by geoand** [comment]
I am making this a draft because it only solves part of the problem. With this change `quarkus.application.name` and `quarkus.application.version` are available when running the prod mode of the application. It doesn't work for dev-mode or tests.
@dmlloyd I can dig further, but maybe you have some insight why this is?

**Comment by gsmet** [comment]
We need to add a test for that one.

**Comment by geoand** [comment]
Yes for sure. However at the moment it only works for prod mode so the only test we can have is one of the heavyweight tests that invoke Maven.

**Comment by geoand** [comment]
Never mind, I think I have a fix for dev mode as well.

**Comment by geoand** [comment]
Actually this needs more thought since with my fix you can't override the value in dev-mode.

**Comment by geoand** [comment]
@gsmet had the idea to use the build system properties introduced in https://github.com/quarkusio/quarkus/pull/3137.

This is well worth exploring so I'll do that in a few hours and see what happens

File: core/runtime/src/main/java/io/quarkus/runtime/ApplicationConfig.java [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+
+    /**
+     * The version of the application.
+     * If not set, defaults to the version of the project
+     */
+    @ConfigItem(defaultValue = "${project.version:unset}")
+    public String version;
+
+    public static boolean isNameUnset(String name) {
+        return name.contains("unset");
```
Comment (gsmet) [inline core/runtime/src/main/java/io/quarkus/runtime/ApplicationConfig.java]: shouldn't it be `equals()` instead of contains? What if you have `unset` in your project name or even if the artifact is called `unset` (which might be a nice project name)?

I would make it `__UNSET__` or something similar.

**Review by gsmet — CHANGES_REQUESTED** [review]
I added a small suggestion. It's nice to have tests for that one.

I think what we need now is a Gradle equivalent.

File: core/runtime/src/main/java/io/quarkus/runtime/ApplicationConfig.java (hunk 1 above)
Comment (geoand) [reply core/runtime/src/main/java/io/quarkus/runtime/ApplicationConfig.java]: Yes you are right. This got left over from previous stuff I was checking. Let me fix it

Comment (geoand) [reply core/runtime/src/main/java/io/quarkus/runtime/ApplicationConfig.java]: Done

**Comment by geoand** [comment]
prod mode of Gradle will work, so if we get this in I am hoping @gastaldi will take care of the necessary changes for dev mode :)

**Comment by geoand** [comment]
I'm taking this out of draft since I also fixed some CI issues the PR had

File: core/runtime/src/main/java/io/quarkus/runtime/ApplicationConfig.java [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+
+@ConfigRoot(phase = ConfigPhase.BUILD_AND_RUN_TIME_FIXED)
+public class ApplicationConfig {
+
+    /**
+     * The name of the application.
+     * If not set, defaults to the name of the project.
+     */
+    @ConfigItem(defaultValue = "${project.name:__UNSET__}")
+    public String name;
```
Comment (dmlloyd) [inline core/runtime/src/main/java/io/quarkus/runtime/ApplicationConfig.java]: If we allow it to be unset, it should just be optional.

Comment (geoand) [reply core/runtime/src/main/java/io/quarkus/runtime/ApplicationConfig.java]: Can a property have a default value and also be `Optional`?

Comment (geoand) [reply core/runtime/src/main/java/io/quarkus/runtime/ApplicationConfig.java]: The reason I went this was is because of https://github.com/quarkusio/quarkus/blob/master/core/deployment/src/main/java/io/quarkus/deployment/configuration/RunTimeConfigurationGenerator.java#L738. 
With the current code of `ApplicationConfig` in master the line above is what (I believe) causes the value to not be used at runtime.

Comment (dmlloyd) [reply core/runtime/src/main/java/io/quarkus/runtime/ApplicationConfig.java]: > Can a property have a default value and also be `Optional`?

Yes, it can.  But the default value should be meaningful.  It looks like you might be trying to hack around something the wrong way here.

> The reason I went with this is, is because of https://github.com/quarkusio/quarkus/blob/master/core/deployment/src/main/java/io/quarkus/deployment/configuration/RunTimeConfigurationGenerator.java#L738.
> With the current code of `ApplicationConfig` in master the line above is what (I believe) causes the value to not be used at runtime.

This logic essentially means "if this property has no default value, and no other sub-trees of this value have default values, don't generate pointless default value methods which would always return null for every name".  This logic only controls what values end up as defaults at run time based on what's in the parse tree.  If a property has no default value, then no default value needs to be returned for it.

This logic does *not* generate run-time-readable config values for values which were specified in build time config, which I suspect is what you're trying to do here.  Trying to use this logic for that purpose will yield incorrect results.

Comment (geoand) [reply core/runtime/src/main/java/io/quarkus/runtime/ApplicationConfig.java]: Well I wasn't trying to use something in any particular way. I was lead to that piece of code by debugging and comparing what made this type of configuration different from others that did behave the way we expected. 
But let me go back and take another look.

File: core/runtime/src/main/java/io/quarkus/runtime/ApplicationConfig.java [hunk 3]
```diff
@@ -0,0 +1,31 @@
...
+
+    /**
+     * The version of the application.
+     * If not set, defaults to the version of the project
+     */
+    @ConfigItem(defaultValue = "${project.version:__UNSET__}")
+    public String version;
+
+    public static boolean isNameUnset(String name) {
+        return name.equals("__UNSET__");
```
Comment (gastaldi) [inline core/runtime/src/main/java/io/quarkus/runtime/ApplicationConfig.java]:
```suggestion
        return (name == null) || ("__UNSET__".equals(name));
```

Comment (gastaldi) [reply core/runtime/src/main/java/io/quarkus/runtime/ApplicationConfig.java]: For the cases where the Config object is uninitialized properly

Comment (geoand) [reply core/runtime/src/main/java/io/quarkus/runtime/ApplicationConfig.java]: I'm going to change this stuff based on @dmlloyd's comments, but thanks for the suggestion

File: core/runtime/src/main/java/io/quarkus/runtime/ApplicationConfig.java (hunk 2 above)
Comment (geoand) [reply core/runtime/src/main/java/io/quarkus/runtime/ApplicationConfig.java]: > This logic does _not_ generate run-time-readable config values for values which were specified in build time config, which I suspect is what you're trying to do here. 

And yes, that is exactly the end result I am looking for :)

Comment (geoand) [reply core/runtime/src/main/java/io/quarkus/runtime/ApplicationConfig.java]: Thanks for the invaluable input! I think this iteration is better. WDYT?

**Comment by geoand** [comment]
@dmlloyd what do you think about the latest iteration?

**Review by dmlloyd — APPROVED** [review]
Seems like a legitimate incremental improvement.

**Comment by geoand** [comment]
Thanks!

**Comment by geoand** [comment]
@gsmet OK to merge?

File: devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java [hunk 4]
```diff
@@ -490,7 +490,13 @@ void prepare() throws Exception {
             for (Map.Entry<Object, Object> e : System.getProperties().entrySet()) {
                 devModeContext.getSystemProperties().put(e.getKey().toString(), (String) e.getValue());
             }
+
             devModeContext.getBuildSystemProperties().putAll((Map) project.getProperties());
+
+            // this is a minor hack to allows up to populate ApplicationConfig with default
```
Comment (gsmet) [inline devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java]:
```suggestion
            // this is a minor hack to allow ApplicationConfig to be populated with defaults
```

File: integration-tests/maven/src/test/java/io/quarkus/maven/it/NativeImageIT.java [hunk 5]
```diff
@@ -16,13 +16,13 @@
...
+import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;
 
 import io.quarkus.maven.it.verifier.MavenProcessInvocationResult;
 import io.quarkus.maven.it.verifier.RunningInvoker;
 
-/**
- *
- */
+// ensure that this test only runs when GraalVM is configured
+@EnabledIfEnvironmentVariable(named = "GRAALVM_HOME", matches = ".*")
```
Comment (gsmet) [inline integration-tests/maven/src/test/java/io/quarkus/maven/it/NativeImageIT.java]: So we don't run it on CI with Docker? I don't think GRAALVM_HOME is set in this case?

**Review by gsmet — CHANGES_REQUESTED** [review]
I added a suggestion and a question.

File: integration-tests/maven/src/test/java/io/quarkus/maven/it/NativeImageIT.java (hunk 5 above)
Comment (geoand) [reply integration-tests/maven/src/test/java/io/quarkus/maven/it/NativeImageIT.java]: We do, I checked the docker image that we use and it does set it

**Comment by gsmet** [comment]
BTW, you got back to a previous version? I don't see the thing we talked about.

File: integration-tests/maven/src/test/java/io/quarkus/maven/it/NativeImageIT.java (hunk 5 above)
Comment (gsmet) [reply integration-tests/maven/src/test/java/io/quarkus/maven/it/NativeImageIT.java]: The Docker image sets it. But is it set when the test is executed?

Comment (geoand) [reply integration-tests/maven/src/test/java/io/quarkus/maven/it/NativeImageIT.java]: It's part of the Docker image, so it's present when the container is run

**Comment by geoand** [comment]
> BTW, you got back to a previous version? I don't see the thing we talked about.

I changed it based on the feedback from @dmlloyd. It essentially does the use the build parameters, but for setting the application name and version directly.

File: devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java (hunk 4 above)
Comment (geoand) [reply devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java]: Fixed, thanks

File: integration-tests/maven/src/test/java/io/quarkus/maven/it/NativeImageIT.java (hunk 5 above)
Comment (gsmet) [reply integration-tests/maven/src/test/java/io/quarkus/maven/it/NativeImageIT.java]: I might be missing something but my understanding is the test is not executed inside the Docker image and thus the `GRAALVM_HOME` is not set. Am I missing something?

Comment (geoand) [reply integration-tests/maven/src/test/java/io/quarkus/maven/it/NativeImageIT.java]: Aha, I see what you are saying! Indeed you are absolutely right! I'll try and think of some other way to do this.
However I don't knoq how this test ever passed in the first place... The reason I disabled it is because the PR was failing on it, because of course native-image doesn't exist

Comment (geoand) [reply integration-tests/maven/src/test/java/io/quarkus/maven/it/NativeImageIT.java]: I pushed a change. WDYT?

File: integration-tests/maven/src/test/java/io/quarkus/maven/it/NativeImageIT.java [hunk 6]
```diff
@@ -37,8 +34,13 @@ public void testJavaLibraryPathAtRuntime() throws Exception {
         final RunningInvoker running = new RunningInvoker(testDir, false);
 
         // trigger mvn package -Pnative -Dquarkus.ssl.native=true
-        final String[] mvnArgs = new String[] { "package", "-DskipTests", "-Pnative", "-Dquarkus.ssl.native=true" };
-        final MavenProcessInvocationResult result = running.execute(Arrays.asList(mvnArgs), Collections.emptyMap());
+        List<String> mavenArgs = Arrays.asList("package", "-DskipTests", "-Pnative", "-Dquarkus.ssl.native=true");
+        if (System.getenv("GRAALVM_HOME") == null || System.getenv("GRAALVM_HOME").isEmpty()) {
+            // If the GRAALVM_HOME env var isn't set, try to use docker to build the image.
+            // This is needed because CI doesn't have a GraalVM installation
+            mavenArgs.add("-Dquarkus.native.container-runtime=docker");
```
Comment (gsmet) [inline integration-tests/maven/src/test/java/io/quarkus/maven/it/NativeImageIT.java]: Can't say I'm excited about this because that means we will require Docker to be installed for a standard JDK run? Or am I mistaken?

Comment (geoand) [reply integration-tests/maven/src/test/java/io/quarkus/maven/it/NativeImageIT.java]: Well unless I have completely missread this test, it can't succeed without GraalVM being installed, right?
So the change just allows us to fallback to docker if it's not.

Comment (geoand) [reply integration-tests/maven/src/test/java/io/quarkus/maven/it/NativeImageIT.java]: So essentially now it's safer than it was before, right?

**Comment by geoand** [comment]
It seems like there is an issue with the Windows test.... Seems like Docker on Windows isn't playing nicely in CI...
Should we perhaps ignore this test for Windows?

**Comment by geoand** [comment]
> Should we perhaps ignore this test for Windows?

This is what I ended up doing

File: devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java [hunk 7]
```diff
@@ -490,7 +490,13 @@ void prepare() throws Exception {
             for (Map.Entry<Object, Object> e : System.getProperties().entrySet()) {
                 devModeContext.getSystemProperties().put(e.getKey().toString(), (String) e.getValue());
             }
+
             devModeContext.getBuildSystemProperties().putAll((Map) project.getProperties());
+
+            //  this is a minor hack to allow ApplicationConfig to be populated with defaults
+            devModeContext.getBuildSystemProperties().putIfAbsent("quarkus.application.name", project.getArtifactId());
```
Comment (gastaldi) [inline devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java]: Should it resolve to `project.name` first and fallback to `artifactId`?

Comment (geoand) [reply devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java]: Does the former exist for Gradle as well?

Also note that we already do the same thing for the regular build, it was just missing from dev mode

Comment (gastaldi) [reply devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java]: > Does the former exist for Gradle as well?

I have no idea, but now that you mention the `QuarkusDev` task in the Gradle plugin needs to be updated too, no?

> Also note that we already do the same thing for the regular build, it was just missing from dev mode

:+1:

Comment (geoand) [reply devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java]: It does yes, I was hoping you would take that up once this is merged 😉

**Comment by geoand** [comment]
@gsmet unless you have any suggestions for getting around the NativeImageIT problem some other way, should we merge this?

**Comment by geoand** [comment]
PR updated with a suggestion from @gsmet regarding better handling of the problematic `NativeImageIT`

File: integration-tests/maven/src/test/java/io/quarkus/maven/it/NativeImageIT.java (hunk 6 above)
Comment (geoand) [reply integration-tests/maven/src/test/java/io/quarkus/maven/it/NativeImageIT.java]: Fixed a different way

File: integration-tests/maven/src/test/java/io/quarkus/maven/it/NativeImageIT.java (hunk 5 above)
Comment (geoand) [reply integration-tests/maven/src/test/java/io/quarkus/maven/it/NativeImageIT.java]: Fixed a different way

**Review by gsmet — APPROVED** [review]
As mentioned on Zulip, I'm not entirely convinced by the annotation approach (especially the fact that it was needed) but since it's there, let's make progress on this one.
