### PR TITLE
Arc - Revisit BeanContainer API

### LINKED ISSUE #35744: Revisit API for BeanContainer
Currently, the `BeanContainer` methods for bean resolution are pretty confusing for users.
The way it works is that a bean resolution is attempted and if there is no bean found, a default fallback is executed. However, this fallback is pretty simplistic and tries to instantiate an object via no-arg constructor which may or may not exist.

The current javadoc also seems to be fumbled now that I read it again (which is something I might have butchered back then) - the deprecated version should be the one that doesn't throw ambig. dep. exception which isn't quite clear now.

We could do some (or more) of the following:
* Deprecate all bean resolving methods in this API and eventually delete them
  * The `beanInstance` and the `beanInstanceFactory` methods
* Introduce a method providing access to Arc container
  * Basically just returning `Arc.container()`; user can do the rest from there
* Retain `beanInstance` but change it's behavior so that it either returns the bean or `null` leaving user to handle the fallback in whichever way they want to
  * We could still deprecate/drop the `beanInstanceFactory` method in this case

Personally, I'd deprecate current methods and introduced two new ones:
* One a convenient access method to `ArcContainer`
* The other similar to `beanInstance` but well defined in that it performs a lookup, resolves ambiguity but in case no bean is found allows user to handle `null` whichever way they choose to

While at it, we should also look into internal usage of `BeanContainerBuildItem` - this is still useful to detect a 'container-ready' state in `STATIC_INIT` but has no real value in `RUNTIME_INIT` as the container is always active at that point in time.
For instance `AmazonLambdaProcessor` depends on this item for no real reason.

### PR DESCRIPTION
**Pull request by manovotn**
Fixes #35744

A draft of changes for `BeanContainer` API - some of these are breaking in behavior although they were already dubious in how they worked because we had conflicting javadoc and implementation.

The `BeanContainer#beanInstanceFactory` method stays in terms of what it does and it now has a javadoc documenting this behavior (i.e. no longer says it can return `null`). There is also a new variant allowing users to specify a custom fallback `Factory` implementation that can be used to perform arbitrary fallack in case the bean isn't present.

The `BeanContainer#beanInstance` method which is used in our own extensions remains in place but also changes in that it can no longer return `null` - instead it is a proper CDI lookup dealing with ambiguous and unsatisfied dependencies. Extensions looking to implement fallbacks in case the beans are missing can leverage the `beanInstanceFactory` method, or just access `ArcContainer` and query for a bean via dynamic resolution.

Last but not least, formerly deprecated methods (deprecated since version 2.14) are now deleted.

### CODE REVIEW

File: independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl/ArcContainerImpl.java [hunk 1]
```diff
@@ -291,12 +291,12 @@ public <X> InstanceHandle<X> instance(Type type, Annotation... qualifiers) {
 
     @Override
     public <T> Supplier<InstanceHandle<T>> beanInstanceSupplier(Class<T> type, Annotation... qualifiers) {
-        return createInstanceSupplier(false, type, qualifiers);
+        return createInstanceSupplier(true, type, qualifiers);
```
Comment (manovotn) [inline independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl/ArcContainerImpl.java:294]: This was an unfortunate bug from the start introduced by [this commit](https://github.com/quarkusio/quarkus/commit/c5b87cf365729d0ecfc60da5e415174978ae87a4#diff-06bb4f2eae4445212128b4f566fc42949f578c01b721589280cf9991a59ffb13).
`beanInstanceSupplier` is the variant that *should* resolve ambiguities while  `instanceSupplier` *should not*.

**Comment by manovotn** [comment]
> /cc @Sanne (hibernate-orm), @brunobat (opentelemetry), @ebullient (metrics), @gsmet (hibernate-orm), @jmartisk (metrics), @radcortez (opentelemetry), @yrodiere (hibernate-orm)

Sorry for the label explosion, the PR changes those extensions only in terms of replacing now-deprecated Arc API call(s).
That is, unless the CI proves me otherwise :)

**Comment by gsmet** [comment]
> as most extensions (including our own in core repo) should "just work" with this approach as well

Famous last words :]

**Comment by manovotn** [comment]
> > as most extensions (including our own in core repo) should "just work" with this approach as well
> 
> Famous last words :]

Indeed :-D
I mean I did expect *some* failures; will take a look tomorrow.

**Comment by manovotn** [comment]
Alright, it turns out the default behavior - fallback to instantiation via no-args ctor - is way more common than I anticipated.
Especially weird since the javadoc of related methods indicated different behavior and the ability to return `null` which basically never happened :)
I have verified that at least Undertow, Websockets and RR are all making use of this fallback.

With that in mind, we might instead consider changing the javadoc, keeping the default instantiation (I assume more extensions out in the wild might use that) and introducing a new method, that will use a custom `Factory` in case we cannot find the bean.
Something like this:

```
    /**
     * Returns an instance factory for given bean type and qualifiers.
     * <p/>
     * This method follows standard CDI resolution rules in that if there are two or more matching beans,
     * an ambiguous dependency exception is thrown.
     * If no matching bean is found, delegates all calls to the supplied factory fallback
     *
     * @param fallbackSupplier supplier to delegate to if there is no bean
     * @param type bean type
     * @param qualifiers bean qualifiers
     * @return a bean instance factory, never {@code null}
     */
    <T> Factory<T> beanInstanceFactoryWithFallback(Supplier<Factory<T>> fallbackSupplier, Class<T> type,
            Annotation... qualifiers);
```

**Comment by manovotn** [comment]
I've updated the PR as per mu suggestion above, let's see what CI thinks about it now :)

**Comment by manovotn** [comment]
Also, in RR there is a `BeanFactory` implementation using this API which throws somewhat suspicious exception.
See https://github.com/quarkusio/quarkus/blob/main/extensions/resteasy-reactive/quarkus-resteasy-reactive-common/runtime/src/main/java/io/quarkus/resteasy/reactive/common/runtime/ArcBeanFactory.java#L40-L43

I am not sure what was the original intention of this but right now the `if` clause catches an exception thrown by `DefaultInstanceFactory` trying to instantiate a non-CDI object, telling users that their class should be a CDI bean. However, if the fallback `DefaultInstanceFactory` kicks in and succeeds in creating the object (i.e. no-args ctor exists and is accessible), that's perfectly fine even though it isn't an actual CDI bean? Maybe I am just missing something... 
CC @geoand

**Review by mkouba — APPROVED** [review]

**Comment by geoand** [comment]
> I am not sure what was the original intention of this but right now the if clause catches an exception thrown by DefaultInstanceFactory trying to instantiate a non-CDI object, telling users that their class should be a CDI bean

This was introduced in https://github.com/quarkusio/quarkus/pull/19829 with the intent of making the error message better.

**Review by Ladicek — APPROVED** [review]
