### PR TITLE
Use SyntheticBeanBuildItem to construct HibernateValidatorFactory

### LINKED ISSUE #47945: Nullpointer Exception at at io.quarkus.hibernate.validator.runtime.interceptor.AbstractMethodValidationInterceptor.validateMethodInvocation(AbstractMethodValidationInterceptor.java:62
### Describe the bug

We are getting Intermittent Null Pointer Exception in the classes where the @NotNull annotation is used .
We are using 3.15.4 version  below is the stacktrace of the issue.
java.lang.NullPointerException
	at io.quarkus.hibernate.validator.runtime.interceptor.AbstractMethodValidationInterceptor.validateMethodInvocation(AbstractMethodValidationInterceptor.java:62)
	at io.quarkus.hibernate.validator.runtime.interceptor.MethodValidationInterceptor.validateMethodInvocation(MethodValidationInterceptor.java:17)
	at io.quarkus.hibernate.validator.runtime.interceptor.MethodValidationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
	at com.XXXXXXXXXXXXX.cassandra.CassandraConsistencyResolver_Subclass.getConsistencyLevel(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:119)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:38)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)
	at io.quarkus.arc.generator.Default_jakarta_enterprise_context_ApplicationScoped_ContextInstances.c18(Unknown Source)
	at io.quarkus.arc.generator.Default_jakarta_enterprise_context_ApplicationScoped_ContextInstances.computeIfAbsent(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:35)
	at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:21)
	at com.gemalto.telecom.foundations.sekms.business.configuration.ConfigurationHolder_ClientProxy.arc$delegate(Unknown Source)
	at com.gemalto.telecom.foundations.sekms.business.configuration.ConfigurationHolder_ClientProxy.checkConfiguration(Unknown Source)
	at com.gemalto.telecom.foundations.sekms.business.configuration.BackgroundConfigurationManager.runCheckConfiguration(BackgroundConfigurationManager.java:83)
	at com.gemalto.telecom.foundations.sekms.business.configuration.BackgroundConfigurationManager.lambda$runCheckConfiguration$1(BackgroundConfigurationManager.java:94)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)

### Expected behavior

It should get initialized properly at the runtime.

### Actual behavior

NullPointerException

### How to Reproduce?

Re-Starting Application number of times with the heavy load of thread starting up at runtime initializing the ApplicationScoped bean using the @NotNull annotation inside method.

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
- Fixes: #47945

### CODE REVIEW

**Comment by geoand** [comment]
It seems like this change has caused more types to be reachable and tripping GraalVM, so it needs more work.

**Review by gsmet — COMMENTED** [review]
Yeah, so the problem is that with the new code, the `ValidatorFactory` is initialized at runtime and not at static init.

And things work atm because the VF is initialized at static init.

**Comment by geoand** [comment]
That definitely makes sense, but the way the Synthetic Bean is created, it should be static-init and not runtime init.

**Comment by geoand** [comment]
@mkouba what is the expectation here for synthetic beans that are `staticInit=true`? When should the function itself run?

**Comment by mkouba** [comment]
> @mkouba what is the expectation here for synthetic beans that are `staticInit=true`? When should the function itself run?

The recorder is called during `ExecutionTime#STATIC_INIT`, i.e. from a generated static initializer...

**Comment by geoand** [comment]
The recorder yes, but how about the function itself?

**Comment by mkouba** [comment]
> The recorder yes, but how about the function itself?

When the relevant bean is created. When exactly? That depends on the scope and the "clients" (e.g. other CDI beans that invoke methods of the bean).

**Comment by geoand** [comment]
I see, that makes sense. Is there anyway to guarantee a very eager (i.e. static init) initialization of the bean without writing some kind of dummy code?

**Comment by gsmet** [comment]
Like an equivalent of `startup()` but for static init.

**Comment by mkouba** [comment]
> Like an equivalent of `startup()` but for static init.

Yes, there's `BeanConfiguratorBase#startup(int)`, `SyntheticBeanBuildItem.ExtendedBeanConfigurator` extends the `BeanConfiguratorBase`.

**Comment by gsmet** [comment]
Yes but my understanding of `startup()` is that it will be run at runtime init?

At least my attempt to use it didn't change at thing.

**Comment by gsmet** [comment]
@geoand FYI, I pushed an additional commit with some further cleanup that should be squashed once we figure out how to do things properly.

I dropped the additional GraalVM stuff as it's not the way to go.

**Comment by geoand** [comment]
Okay, fixed it

**Comment by geoand** [comment]
I pushed a commit that should also be squashed if we agree it's the way to go.

File: extensions/hibernate-validator/runtime/src/main/java/io/quarkus/hibernate/validator/runtime/HibernateValidatorRecorder.java [hunk 1]
```diff
@@ -284,4 +285,10 @@ public ResteasyConfigSupport get() {
             }
         };
     }
+
+    // this is done in order to ensure that HibernateValidatorFactory is fully initialized at static init
+    // so completely in heap and ready to go when a native image is built
+    public void hibernateValidatorFactoryInit(BeanContainer beanContainer) {
+        HibernateValidatorFactory hibernateValidatorFactory = beanContainer.beanInstance(HibernateValidatorFactory.class);
```
Comment (mkouba) [inline extensions/hibernate-validator/runtime/src/main/java/io/quarkus/hibernate/validator/runtime/HibernateValidatorRecorder.java:292]: Note that this only works because `HibernateValidatorFactory` is `@Singleton` and not a normal scoped bean with a client proxy.

Comment (geoand) [reply extensions/hibernate-validator/runtime/src/main/java/io/quarkus/hibernate/validator/runtime/HibernateValidatorRecorder.java:292]: Yup, I'm aware.  If it were ApplicationScoped I would have called toString

**Review by gsmet — APPROVED** [review]
If you end up with a green CI, I think it's good to merge.
