### PR TITLE
Ignore GraalVM features in HibernateValidatorProcessor

### LINKED ISSUE #47033: Native compilation failure using some extensions and bean validation
### Describe the bug

Hi,

I try to build a native executable of a project with those 3 extensions:
- quarkus-cxf
- quarkus-mongodb-client
- quarkus-hibernate-validator

But the build fails.
It seems that the failure appears only when `@Valid` is set on a property of type List (I didn't try other collection classes), such as:
```
    @NotNull
    @Size(min = 0)
    @Valid // commenting this made the build succeed
    private List<TestData2> fields;
```

Removing one of the 3 extensions or commenting `@valid` result to a build success.

Note that a `@Valid` on an Object (not a collection) does not fails the build.

I build the native executable using Docker:
```
mvn clean package -Dnative -Dmaven.test.skip=true -Dquarkus.native.container-build=true
```

Thanks.

### Expected behavior

The native build passes using the 3 extensions and `@Valid` on List properties.

### Actual behavior

The native build fails using the 3 extensions and `@Valid` on List properties with the following stacktrace:

```
Produced artifacts:
 /project/build-artifacts.json (build_info)
 /project/svm_err_b_20250327T124443.290_pid60.md (build_info)
========================================================================================================================
Failed generating 'code-with-quarkus-1.0.0-SNAPSHOT-runner' after 2m 18s.

The build process encountered an unexpected error:

com.oracle.svm.core.util.VMError$HostedError: com.oracle.svm.core.util.UserError$UserException: Image heap writing found a class not seen during static analysis. Did a static field or an object referenced from a static field change during native image generation? For example, a lazily initialized cache could have been initialized during image generation, in which case you need to force eager initialization of the cache before static analysis or reset the cache using a field value recomputation.
    class: org.eclipse.angus.activation.nativeimage.AngusActivationFeature
  reachable through:
    object: [Ljava.lang.Class;@15756b0c  of class: java.lang.Class[]
    object: com.oracle.svm.core.code.ImageCodeInfo@33f24d15  of class: com.oracle.svm.core.code.ImageCodeInfo
    root: com.oracle.svm.core.code.ImageCodeInfo.prepareCodeInfo()

        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:82)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:720)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:550)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:539)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:721)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:143)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:98)
Caused by: com.oracle.svm.core.util.UserError$UserException: Image heap writing found a class not seen during static analysis. Did a static field or an object referenced from a static field change during native image generation? For example, a lazily initialized cache could have been initialized during image generation, in which case you need to force eager initialization of the cache before static analysis or reset the cache using a field value recomputation.
    class: org.eclipse.angus.activation.nativeimage.AngusActivationFeature
  reachable through:
    object: [Ljava.lang.Class;@15756b0c  of class: java.lang.Class[]
    object: com.oracle.svm.core.code.ImageCodeInfo@33f24d15  of class: com.oracle.svm.core.code.ImageCodeInfo
    root: com.oracle.svm.core.code.ImageCodeInfo.prepareCodeInfo()

        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:73)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.NativeImageHeap.reportIllegalType(NativeImageHeap.java:592)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.NativeImageHeap.addObjectToImageHeap(NativeImageHeap.java:556)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.NativeImageHeap.addConstant(NativeImageHeap.java:327)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.NativeImageHeap.processAddObjectWorklist(NativeImageHeap.java:705)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.NativeImageHeap.addTrailingObjects(NativeImageHeap.java:202)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.buildNativeImageHeap(NativeImageGenerator.java:760)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:697)
        ... 5 more

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:28 min
[INFO] Finished at: 2025-03-27T13:44:43+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:3.19.4:build (default) on project code-with-quarkus: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: io.quarkus.deployment.pkg.steps.NativeImageBuildStep$ImageGenerationFailureException: Image generation failed. Exit code: 1
[ERROR]         at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.imageGenerationFailed(NativeImageBuildStep.java:496)
[ERROR]         at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:287)
[ERROR]         at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:255)
[ERROR]         at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:1583)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:499)
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

Ubuntu 24.04.2 LTS

### Output of `java -version`

openjdk version "21.0.6" 2025-01-21

### Mandrel or GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

3.19.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.7

### Additional information

Reproducer:
[code-with-quarkus-cxf-mongo.zip](https://github.com/user-attachments/files/19486804/code-with-quarkus-cxf-mongo.zip)

or generate a fresh project with the 3 extensions + a class with a `@Valid` on a List property.

### PR DESCRIPTION
**Pull request by gsmet**
Fixes #47033

### CODE REVIEW

File: extensions/hibernate-validator/deployment/src/main/java/io/quarkus/hibernate/validator/deployment/HibernateValidatorProcessor.java [hunk 1]
```diff
@@ -701,33 +703,72 @@ private static void contributeBuiltinConstraints(Set<String> builtinConstraints,
...
         }
-        for (ClassInfo implementor : indexView.getAllKnownImplementors(className)) {
+        for (ClassInfo implementor : indexView.getAllKnownImplementors(classInfo.name())) {
             if (Modifier.isAbstract(implementor.flags())) {
                 // we can avoid adding the abstract classes here: either they are parent classes
                 // and they will be dealt with by Hibernate Validator or they are child classes
                 // without any proper implementation and we can ignore them.
                 continue;
             }
+            if (isInGraalVMFeature(indexView, implementor)) {
```
Comment (marko-bekhta) [inline extensions/hibernate-validator/deployment/src/main/java/io/quarkus/hibernate/validator/deployment/HibernateValidatorProcessor.java:736]: I was thinking whether we could say something like:
```
if (hasAnyConstraints(indexView, implementor)) {
```
If there are no constraints, there's nothing to cascade into, right? But I don't remember if we need to keep the classes without constraints.. will try to take a look later

Comment (gsmet) [reply extensions/hibernate-validator/deployment/src/main/java/io/quarkus/hibernate/validator/deployment/HibernateValidatorProcessor.java:736]: I think:
- if the class is a leaf class
- it doesn't have any constraints
we can skip it.

So I think we could go with your approach... but... I would still try to exclude the `Feature` classes as you never know if someone adds a `@NotNull` by mistake.

Comment (marko-bekhta) [reply extensions/hibernate-validator/deployment/src/main/java/io/quarkus/hibernate/validator/deployment/HibernateValidatorProcessor.java:736]: yeah +1 just to be safe

Comment (marko-bekhta) [reply extensions/hibernate-validator/deployment/src/main/java/io/quarkus/hibernate/validator/deployment/HibernateValidatorProcessor.java:736]: yes 👍🏻 🙂

Comment (marko-bekhta) [reply extensions/hibernate-validator/deployment/src/main/java/io/quarkus/hibernate/validator/deployment/HibernateValidatorProcessor.java:736]: ok checked aand that won't fly 🙈:
```java
Validator validator = validator( Set.of( A.class ) );

assertThat( validator.validate( new A() ) ).containsOnlyViolations(
		violationOf( NotNull.class ).withProperty( "name" )
);

// fails as we get the `UninitializedBeanMetaData` and hence no constraints ... 
assertThat( validator.validate( new B() ) ).containsOnlyViolations(
		violationOf( NotNull.class ).withProperty( "name" )
);
```
If we skip the class, even if it's a leaf with no constraints (or if it's anywhere in the hierarchy for that matter), we will end up having the `UninitializedBeanMetaData` for it once someone wants to validate an instance of it and it simply has 0 constraints (the ones from the super classes are there).

Comment (gsmet) [reply extensions/hibernate-validator/deployment/src/main/java/io/quarkus/hibernate/validator/deployment/HibernateValidatorProcessor.java:736]: I think we should have started with: WTH is this class in the index? I wouldn't expect it to be.

**Comment by gsmet** [comment]
@marko-bekhta I just pushed an updated version on top of @Ladicek 's work in https://github.com/quarkusio/quarkus/pull/47213 .

I will rebase and get it out of draft once the Jandex update PR is merged.

**Comment by gsmet** [comment]
@marko-bekhta I'm interested in your review!

**Review by marko-bekhta — APPROVED** [review]
looks nice! 🎉
