### PR TITLE
Also register superclasses as bean types in ResteasyReactiveProcessor

### LINKED ISSUE #47003: Instance<T> does not find implementations having a @Context annotated field
### Describe the bug

When iterating over a `Instance<T>`, no implementations of `T` having a `@Context` annotated field are returned.

```
    @Inject
    Instance<GreetingGenerator> generators;
```
```
for (GreetingGenerator generator : generators) {
            if (generator.handlesLanguage("de")) {
                return generator.generateGreeting();
            }
        }
```

And: 

```
@ApplicationScoped
public class GermanGreetingGenerator extends GreetingGenerator {

    @Context
    HttpHeaders headers;
```

The GermanGreetingGenerator  is never found by the for loop.

Directly injecting and using the GermanGreetingGenerator works as expected,

### Expected behavior

Either a log message about this circumstance. or find the GermanGreetingGenerator.

### Actual behavior

GermanGreetingGenerator is not returned with Instance<T>

### How to Reproduce?

Download reproducer: 

[instance-unremovable.zip](https://github.com/user-attachments/files/19468014/instance-unremovable.zip)

mvn quarkus:dev
Open localhost:8080/hello.
Should display "Servus", but instead displays "Hello".
In GermanGreetingGenerator.java, remove     @Context HttpHeaders headers;
Open localhost:8080/hello.
Correctly displays now "Servus"

### Output of `uname -a` or `ver`

MINGW64_NT-10.0-26100 NANBCHL9NG3 3.3.6-341.x86_64 2022-09-05 20:28 UTC x86_64 Msys

### Output of `java -version`

openjdk 21.0.5 2024-10-15 LTS OpenJDK Runtime Environment Temurin-21.0.5+11 (build 21.0.5+11-LTS) OpenJDK 64-Bit Server VM Temurin-21.0.5+11 (build 21.0.5+11-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.19.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.8 (4c87b05d9aedce574290d1acc98575ed5eb6cd39) Maven home: C:\eclipse\tools\java\maven Java version: 21.0.5, vendor: Eclipse Adoptium, runtime: C:\eclipse\tools\java\21 Default locale: de_DE, platform encoding: UTF-8 OS name: "windows 11", version: "10.0", arch: "amd64", family: "windows"

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by gsmet**
Fixes https://github.com/quarkusio/quarkus/issues/47003

@geoand @Postremus interested in your feedback.

### CODE REVIEW

File: independent-projects/resteasy-reactive/common/processor/src/main/java/org/jboss/resteasy/reactive/common/processor/EndpointIndexer.java [hunk 1]
```diff
@@ -297,7 +297,7 @@ public Optional<ResourceClass> createEndpoints(ClassInfo classInfo, boolean cons
                 }
                 clazz.setPath(sanitizePath(path));
             }
-            if (factoryCreator != null && !classInfo.isInterface()) {
+            if (factoryCreator != null && !classInfo.isInterface() && !classInfo.isAbstract()) {
```
Comment (gsmet) [inline independent-projects/resteasy-reactive/common/processor/src/main/java/org/jboss/resteasy/reactive/common/processor/EndpointIndexer.java:300]: This change is specifically there to fix `SubResourceAmbiguousInjectTest`. The `isInterface()` test was added recently to fix the issue and I think the `isAbstract()` makes also sense but happy to be proven wrong.

**Review by geoand — APPROVED** [review]
Seems reasonable to me!

**Comment by gsmet** [comment]
@Postremus I made you a co-author as the test is just an extended version of the one you wrote.

File: extensions/resteasy-reactive/rest/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/ResteasyReactiveProcessor.java [hunk 2]
```diff
@@ -1049,21 +1049,21 @@ private boolean isRecord(IndexView index, DotName name) {
...
-        Set<DotName> interfaceNames = new HashSet<>();
+        Set<DotName> allBeanTypes = new HashSet<>();
+        allBeanTypes.add(clazz.name());
+
         ClassInfo currentClazz = clazz;
-        while (!ResteasyReactiveDotNames.OBJECT.equals(currentClazz.name())) {
-            currentClazz.interfaceNames().forEach(iface -> interfaceNames.add(iface));
-            // inspect super class
+        while (!ResteasyReactiveDotNames.OBJECT.equals(currentClazz.name()) && currentClazz != null) {
+            if (currentClazz.isAbstract()) {
```
Comment (Postremus) [inline extensions/resteasy-reactive/rest/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/ResteasyReactiveProcessor.java:1057]: Maybe all classes, even non abstract need to be added to the typed annotation?

Eg:
```
@Named("base")
public class Base {

}

@ApplicationScoped
public class Ext1 extends Base {
        @Context
        HttpHeaders headers;
}

@ApplicationScoped
public class Ext2 extends Base {
        @Context
        HttpHeaders headers;
}
```

Now doing an:
```
@Inject
Instance<Base>
```

what happens? I believe Instancehandle should point to Ext1 and Ext2, but won't since the Typed annotation does not contain the Base class.

Comment (gsmet) [reply extensions/resteasy-reactive/rest/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/ResteasyReactiveProcessor.java:1057]: That's what I did first and I had ~ 4 tests failing with ambiguous resolution so I wonder if it might break some applications.
For instance `SimpleQuarkusRestTestCase` was failing and there were a few others.

Now I could be convinced to do it if it has a lot of value but we would have to check with @geoand .

Comment (geoand) [reply extensions/resteasy-reactive/rest/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/ResteasyReactiveProcessor.java:1057]: I personally would not do it for now

Comment (Postremus) [reply extensions/resteasy-reactive/rest/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/ResteasyReactiveProcessor.java:1057]: ok, fine by me, at least this decission is now documented somewhere.

**Review by Postremus — APPROVED** [review]
