### PR TITLE
Use SmallRyeConfigBuilder Customizer to generate Quarkus configuration

### LINKED ISSUE #25999: Allow to create runtime only ConfigSource
### Description

Currently, if we define a ConfigSource via a ConfigSourceFactory, this ConfigSource is initialized once at build time (and the `getPropertyNames()` method is called) and once at runtime.

We should be able to define runtime only ConfigSource / ConfigSourceFactory for exemple for ConfigSource that load a file at runtime which can be not found at build time. As ConfigSourceFactory allow to access the `ConfigSourceContext` which can be different at build and runtime it's important to have this functionality.

See this Zulip discussion for context: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/ConfigSourceFactory.20initialized.20at.20build.20time

### Implementation ideas

_No response_

### LINKED ISSUE #32674: Extension config for both build and run time with same prefix
### Describe the bug

Extension [writing guide][1] recommends using `@ConfigMapping` instead of `@ConfigRoot` with prefix and name but in case of split config with same prefix for build time and run time SR Config validation effectively forbids it.

[1]: https://quarkus.io/guides/writing-extensions#configuration

Similar approach with `@ConfigRoot(prefix = "my", name = "", phase = ...)` seems to work fine.

See also: [zulip thread](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Extension.20build.20and.20run.20time.20config.20under.20the.20same.20prefix/near/350364010).

### Expected behavior

Ability to map configuration properties to both run time and build time config with validation failure only if the property is absent in both.

### Actual behavior

```
ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: io.smallrye.config.ConfigValidationException: Configuration validation failed:
        my.greeting does not map to any root
```

### How to Reproduce?

Reproducer:

1. `quarkus create extension org.acme:my-ext && cd my-ext`
2. Add following classes to `runtime` module

```java
@ConfigMapping(prefix = "my")
@ConfigRoot(phase = ConfigPhase.RUN_TIME)
public interface MyExtRunTimeConfig {
  /** */
  String greeting();
}

@ConfigMapping(prefix = "my")
@ConfigRoot(phase = ConfigPhase.BUILD_TIME)
public interface MyExtBuildTimeConfig {
  /** */
  @WithDefault("true")
  boolean enabled();
}
```

3. Add `<module>intergration-tests</module>` to root `pom.xml`
4. Add `my.greeting = Hi` to `integration-tests/src/main/resources/application.properties`
5. Run `quarkus dev`

### Output of `uname -a` or `ver`

Linux unterwelt 6.2.10-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 07 Apr 2023 02:10:43 +0000 x86_64 GNU/Linux

### Output of `java -version`

openjdk 17.0.6 2023-01-17 OpenJDK Runtime Environment Temurin-17.0.6+10 (build 17.0.6+10) OpenJDK 64-Bit Server VM Temurin-17.0.6+10 (build 17.0.6+10, mixed mode, sharing)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.16.6.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.7 (b89d5959fcde851dcb1c8946a785a163f14e1e29)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by radcortez**
These are significant changes, with the following goals:

- Simplify the generation of Config, by adding a `Customizer` and removing all individual components registration in the generator
- Register components directly and avoid ServiceLoader
- Merge Quarkus defaults source into SmallRye Config built-in defaults

Used `config-quickstart` to measure improvements with Java 17 Temurin and Graal 22.3 - Java 17:

<google-sheets-html-origin style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);">

  | JVM RSS | Native RSS | JVM Start | Native Start
-- | -- | -- | -- | --
3.4.0 | 153403 | 25714 | 0.624 | 0.025
#35322 | 146538 | 22543 | 0.597 | 0.017
Diff to 3.4.0 | -4.68% | -14.06% | -4.57% | -46.09%

</google-sheets-html-origin>

Overall, this PR, should show startup time and RSS improvements for every Quarkus application (at scale), since the improvements affect the core, which always executes regardless of which extensions are available. 

- Fixes #25999
- Fixes #32674

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]

**Review by franz1981 — APPROVED** [review]
Quickly taken a look, great Roberto!

**Comment by gastaldi** [comment]
@radcortez it seems you're using a Mac, which does not provide a case sensitive volume by default. See the discussion in Zulip

**Comment by radcortez** [comment]
> @radcortez it seems you're using a Mac, which does not provide a case sensitive volume by default. See the discussion in Zulip and [#36180 (comment)](https://github.com/quarkusio/quarkus/pull/36180#issuecomment-1737726060)

When I did a rebase, I noticed that file, but I thought it was just code-style formatting applied by the build.

File: core/runtime/src/main/java/io/quarkus/runtime/ConfigConfig.java [hunk 1]
```diff
@@ -23,7 +22,6 @@ public interface ConfigConfig {
     /**
      * Profile that will be active when Quarkus launches.
      */
-    @WithDefault("prod")
```
Comment (gsmet) [inline core/runtime/src/main/java/io/quarkus/runtime/ConfigConfig.java:26]: I can see how we wouldn't want a default for an Optional but do you confirm this doesn't change our behavior?

Comment (radcortez) [reply core/runtime/src/main/java/io/quarkus/runtime/ConfigConfig.java:26]: Yes, it is fine because the profile was always being overridden by the launch mode:
https://github.com/quarkusio/quarkus/pull/35322/files#diff-11168005e2c503c75c2ff0f927c06e4ca8fb9676b91d58e37ea98b05d68cc27dR29

So, there's no point in setting it here. Also, it would show up as the default in the docs, and because the profile changes depending on the launch mode, it doesn't make sense either to show a default profile in there.

Comment (gsmet) [reply core/runtime/src/main/java/io/quarkus/runtime/ConfigConfig.java:26]: Thanks for confirming! Let's get this in then.

**Review by gsmet — APPROVED** [review]
