### PR TITLE
Leave the TCCL how we found it after test discovery

### LINKED ISSUE #47081: Accessing ConfigProvider from a custom JUnit condition results in ServiceConfigurationError
### Describe the bug

Originally reported on Zulip for Quarkus `999-SNAPSHOT`:

https://quarkusio.zulipchat.com/#narrow/channel/187038-dev/topic/WG.20.2330.20Test.20Classloading.20chatter/near/509166917

If you have a custom JUnit extension, use lifecycle callbacks and try to access `ConfigProvider`, you get an exception like:

```
java.util.ServiceConfigurationError: io.smallrye.config.SmallRyeConfigFactory: io.quarkus.runtime.configuration.QuarkusConfigFactory not a subtype
    at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:593)
    at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1244)
    at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
    at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
    at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
    at io.smallrye.config.SmallRyeConfigProviderResolver.getFactoryFor(SmallRyeConfigProviderResolver.java:102)
    at io.smallrye.config.SmallRyeConfigProviderResolver.getConfig(SmallRyeConfigProviderResolver.java:78)
    at io.smallrye.config.SmallRyeConfigProviderResolver.getConfig(SmallRyeConfigProviderResolver.java:66)
    at org.eclipse.microprofile.config.ConfigProvider.getConfig(ConfigProvider.java:85)
```

If you set the TCCL so that the classes is loadable (see attached reproducer), things work ok.

Here's a reproducer app (see details below).

[junit-condition-test.zip](https://github.com/user-attachments/files/19535662/junit-condition-test.zip)

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

See attached reproducer app.

Replicate the failure with `mvn clean test`. To activate a TCCL switch that fixes the test do `mvn clean test  -DswitchTCCL=true`.

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

999-SNAPSHOT

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by holly-cummins**
Resolves https://github.com/quarkusio/quarkus/issues/47081

The problem happened because at the end of test discovery, we leave the TCCL as the FacadeClassLoader. That classloader isn't really much use, outside the context of discovery, and it's actively unhelpful when other code is trying to evaluate JUnit conditions. The ideal TCCL for doing that is the system classloader. 

We do have the option to listen to an event when discovery finishes, so I've hooked that event to reset the TCCL. For symmetry, I've also switched from intercepting the whole invocation to just hooking the discovery start. 

My fix does not fix the continuous testing case; in that case, something in the runner is setting the TCCL to be the deployment classloader, which is still wrong for the condition execution code. I've committed a reproducer and raised https://github.com/quarkusio/quarkus/issues/47364.

### CODE REVIEW

**Comment by gsmet** [comment]
I see a couple of errors in the logs, some of which didn't actually make the build fail but still look a bit concerning (and that's why I'm listing them here):

(note that I don't know if they appear on a normal run but they looked suspicious)

1. Attempted to close a launcher session which had already been closed.

```
2025-04-23T20:28:46.5839315Z [ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
2025-04-23T20:28:46.5840256Z [ERROR] java.lang.IllegalStateException: Internal error: Attempted to close a launcher session which had already been closed.
2025-04-23T20:28:46.5841406Z [ERROR] org.apache.maven.surefire.api.util.SurefireReflectionException: java.lang.IllegalStateException: Internal error: Attempted to close a launcher session which had already been closed.
2025-04-23T20:28:46.5842599Z [ERROR] 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.closeLauncher(JUnitPlatformProvider.java:201)
2025-04-23T20:28:46.5843915Z [ERROR] 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)
2025-04-23T20:28:46.5844960Z [ERROR] 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:122)
2025-04-23T20:28:46.5845837Z [ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
2025-04-23T20:28:46.5846619Z [ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
2025-04-23T20:28:46.5847303Z [ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
2025-04-23T20:28:46.5848010Z [ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
2025-04-23T20:28:46.5848819Z [ERROR] Caused by: java.lang.IllegalStateException: Internal error: Attempted to close a launcher session which had already been closed.
2025-04-23T20:28:46.5849805Z [ERROR] 	at io.quarkus.test.config.ConfigLauncherSession.launcherSessionClosed(ConfigLauncherSession.java:48)
2025-04-23T20:28:46.5850709Z [ERROR] 	at org.junit.platform.launcher.core.DefaultLauncherSession.close(DefaultLauncherSession.java:76)
2025-04-23T20:28:46.5851715Z [ERROR] 	at org.apache.maven.surefire.junitplatform.LazyLauncher.close(LazyLauncher.java:80)
2025-04-23T20:28:46.5852649Z [ERROR] 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.closeLauncher(JUnitPlatformProvider.java:199)
2025-04-23T20:28:46.5853547Z [ERROR] 	... 6 more
2025-04-23T20:28:46.5853794Z [ERROR] 
```

2. Failed to load default class orderer class 'io.quarkus.test.config.QuarkusClassOrderer' - this one appears several times

```
2025-04-23T20:29:02.3721644Z 2025-04-23 20:29:02,290 INFO  [io.quarkus] (Quarkus Main Thread) quarkus-test-test-profile 1.0-SNAPSHOT on JVM (powered by Quarkus 999-SNAPSHOT) started in 2.212s. Listening on: http://localhost:8080
2025-04-23T20:29:02.3723103Z 2025-04-23 20:29:02,292 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2025-04-23T20:29:02.3724101Z 2025-04-23 20:29:02,293 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, resteasy, smallrye-context-propagation, vertx]
2025-04-23T20:29:02.8692418Z HOLLY TCCL watch 2 QuarkusClassLoader:Augmentation Class Loader: TEST for quarkus-test-test-profile-1.0-SNAPSHOT@678bae67
2025-04-23T20:29:02.8693633Z HOLLY TCCL watch 2a QuarkusClassLoader:Augmentation Class Loader: TEST for quarkus-test-test-profile-1.0-SNAPSHOT@678bae67
2025-04-23T20:29:02.8695666Z 2025-04-23 20:29:02,855 WARNING [org.jun.jup.eng.con.InstantiatingConfigurationParameterConverter] (Test runner thread) Failed to load default class orderer class 'io.quarkus.test.config.QuarkusClassOrderer' set via the 'junit.jupiter.testclass.order.default' configuration parameter. Falling back to default behavior.: java.lang.ClassNotFoundException: io.quarkus.test.config.QuarkusClassOrderer
2025-04-23T20:29:02.8698224Z 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
2025-04-23T20:29:02.8698947Z 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
2025-04-23T20:29:02.8699722Z 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
2025-04-23T20:29:02.8700228Z 	at java.base/java.lang.Class.forName0(Native Method)
2025-04-23T20:29:02.8700672Z 	at java.base/java.lang.Class.forName(Class.java:467)
2025-04-23T20:29:02.8701326Z 	at org.junit.platform.commons.util.ReflectionUtils.lambda$tryToLoadClass$10(ReflectionUtils.java:874)
2025-04-23T20:29:02.8702085Z 	at org.junit.platform.commons.function.Try.lambda$call$0(Try.java:57)
2025-04-23T20:29:02.8702640Z 	at org.junit.platform.commons.function.Try.of(Try.java:93)
2025-04-23T20:29:02.8703352Z 	at org.junit.platform.commons.function.Try.call(Try.java:57)
2025-04-23T20:29:02.8704032Z 	at org.junit.platform.commons.util.ReflectionUtils.tryToLoadClass(ReflectionUtils.java:861)
2025-04-23T20:29:02.8704702Z 	at org.junit.platform.commons.util.ReflectionUtils.tryToLoadClass(ReflectionUtils.java:798)
2025-04-23T20:29:02.8705510Z 	at org.junit.platform.commons.support.ReflectionSupport.tryToLoadClass(ReflectionSupport.java:95)
2025-04-23T20:29:02.8709163Z 	at org.junit.jupiter.engine.config.InstantiatingConfigurationParameterConverter.newInstanceSupplier(InstantiatingConfigurationParameterConverter.java:52)
2025-04-23T20:29:02.8710632Z 	at org.junit.jupiter.engine.config.InstantiatingConfigurationParameterConverter.lambda$supply$1(InstantiatingConfigurationParameterConverter.java:46)
2025-04-23T20:29:02.8711563Z 	at java.base/java.util.Optional.map(Optional.java:260)
2025-04-23T20:29:02.8712444Z 	at org.junit.jupiter.engine.config.InstantiatingConfigurationParameterConverter.supply(InstantiatingConfigurationParameterConverter.java:46)
2025-04-23T20:29:02.8714100Z 	at org.junit.jupiter.engine.config.InstantiatingConfigurationParameterConverter.get(InstantiatingConfigurationParameterConverter.java:38)
2025-04-23T20:29:02.8715249Z 	at org.junit.jupiter.engine.config.DefaultJupiterConfiguration.getDefaultTestClassOrderer(DefaultJupiterConfiguration.java:162)
2025-04-23T20:29:02.8716459Z 	at org.junit.jupiter.engine.config.CachingJupiterConfiguration.lambda$getDefaultTestClassOrderer$9(CachingJupiterConfiguration.java:126)
2025-04-23T20:29:02.8717489Z 	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1740)
2025-04-23T20:29:02.8718467Z 	at org.junit.jupiter.engine.config.CachingJupiterConfiguration.getDefaultTestClassOrderer(CachingJupiterConfiguration.java:125)
2025-04-23T20:29:02.8719387Z 	at org.junit.jupiter.engine.discovery.ClassOrderingVisitor.visit(ClassOrderingVisitor.java:40)
2025-04-23T20:29:02.8720031Z 	at org.junit.platform.engine.TestDescriptor.accept(TestDescriptor.java:309)
2025-04-23T20:29:02.8720606Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
2025-04-23T20:29:02.8721646Z 	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.run(EngineDiscoveryRequestResolution.java:85)
2025-04-23T20:29:02.8722361Z 	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolver.resolve(EngineDiscoveryRequestResolver.java:116)
2025-04-23T20:29:02.8723712Z 	at org.junit.jupiter.engine.discovery.DiscoverySelectorResolver.resolveSelectors(DiscoverySelectorResolver.java:48)
2025-04-23T20:29:02.8724437Z 	at org.junit.jupiter.engine.JupiterTestEngine.discover(JupiterTestEngine.java:69)
2025-04-23T20:29:02.8725411Z 	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:152)
2025-04-23T20:29:02.8726603Z 	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverSafely(EngineDiscoveryOrchestrator.java:132)
2025-04-23T20:29:02.8727736Z 	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:105)
2025-04-23T20:29:02.8729004Z 	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:78)
2025-04-23T20:29:02.8729728Z 	at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:99)
2025-04-23T20:29:02.8730585Z 	at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:77)
2025-04-23T20:29:02.8731381Z 	at org.junit.platform.launcher.core.DelegatingLauncher.discover(DelegatingLauncher.java:42)
2025-04-23T20:29:02.8732285Z 	at org.junit.platform.launcher.core.InterceptingLauncher.lambda$discover$0(InterceptingLauncher.java:33)
2025-04-23T20:29:02.8733668Z 	at org.junit.platform.launcher.core.ClasspathAlignmentCheckingLauncherInterceptor.intercept(ClasspathAlignmentCheckingLauncherInterceptor.java:25)
2025-04-23T20:29:02.8734798Z 	at org.junit.platform.launcher.core.InterceptingLauncher.discover(InterceptingLauncher.java:33)
2025-04-23T20:29:02.8735604Z 	at org.junit.platform.launcher.core.DelegatingLauncher.discover(DelegatingLauncher.java:42)
2025-04-23T20:29:02.8736474Z 	at org.junit.platform.launcher.core.SessionPerRequestLauncher.discover(SessionPerRequestLauncher.java:56)
2025-04-23T20:29:02.8737320Z 	at io.quarkus.deployment.dev.testing.JunitTestRunner.prepare(JunitTestRunner.java:217)
2025-04-23T20:29:02.8738068Z 	at io.quarkus.deployment.dev.testing.ModuleTestRunner.prepare(ModuleTestRunner.java:83)
2025-04-23T20:29:02.8738793Z 	at io.quarkus.deployment.dev.testing.TestSupport.runInternal(TestSupport.java:430)
2025-04-23T20:29:02.8739618Z 	at io.quarkus.deployment.dev.testing.TestSupport$3.run(TestSupport.java:389)
2025-04-23T20:29:02.8740130Z 	at java.base/java.lang.Thread.run(Thread.java:840)
2025-04-23T20:29:02.8740400Z 
2025-04-23T20:29:02.8740652Z HOLLY TCCL watch 3 jdk.internal.loader.ClassLoaders$AppClassLoader@1dbd16a6
2025-04-23T20:29:02.8741430Z HOLLY TCCL watch 4 QuarkusClassLoader:Deployment Class Loader: TEST for quarkus-test-test-profile-1.0-SNAPSHOT@64358056
2025-04-23T20:29:02.8742033Z Starting test run, 1 tests to run.
2025-04-23T20:29:02.9692752Z Running 1/1. Running: #JUnit Jupiter
2025-04-23T20:29:02.9693474Z Running 1/1. Running: org.acme.ExampleTest#ExampleTest
2025-04-23T20:29:03.4699274Z Running 1/1. Running: org.acme.ExampleTest#testSomething()
```

3.  java.lang.ClassCastException: class io.smallrye.config.SmallRyeConfigProviderResolver cannot be cast to class io.quarkus.test.config.TestConfigProviderResolver (io.smallrye.config.SmallRyeConfigProviderResolver and io.quarkus.test.config.TestConfigProviderResolver are in unnamed module of loader 'app'

```
2025-04-23T20:28:46.3124707Z [INFO] Running org.acme.tck.HelloResourceTest
2025-04-23T20:28:46.4085666Z java.lang.ClassCastException: class io.smallrye.config.SmallRyeConfigProviderResolver cannot be cast to class io.quarkus.test.config.TestConfigProviderResolver (io.smallrye.config.SmallRyeConfigProviderResolver and io.quarkus.test.config.TestConfigProviderResolver are in unnamed module of loader 'app')
2025-04-23T20:28:46.4088038Z [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.035 s <<< FAILURE! -- in org.acme.tck.HelloResourceTest
2025-04-23T20:28:46.4088990Z [ERROR] org.acme.tck.HelloResourceTest.testHelloEndpoint -- Time elapsed: 0.014 s <<< ERROR!
2025-04-23T20:28:46.4090315Z java.lang.RuntimeException: java.util.ServiceConfigurationError: io.quarkus.runtime.test.TestHttpEndpointProvider: io.quarkus.resteasy.server.common.runtime.RESTEasyTestHttpProvider not a subtype
2025-04-23T20:28:46.4091685Z 	at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:693)
2025-04-23T20:28:46.4092661Z 	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:791)
2025-04-23T20:28:46.4093611Z 	at java.base/java.util.Optional.orElseGet(Optional.java:364)
2025-04-23T20:28:46.4094152Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
2025-04-23T20:28:46.4094644Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
2025-04-23T20:28:46.4095706Z Caused by: java.util.ServiceConfigurationError: io.quarkus.runtime.test.TestHttpEndpointProvider: io.quarkus.resteasy.server.common.runtime.RESTEasyTestHttpProvider not a subtype
2025-04-23T20:28:46.4096698Z 	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:593)
2025-04-23T20:28:46.4097435Z 	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1244)
2025-04-23T20:28:46.4098281Z 	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
2025-04-23T20:28:46.4098993Z 	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
2025-04-23T20:28:46.4099556Z 	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
2025-04-23T20:28:46.4100030Z 	at io.quarkus.runtime.test.TestHttpEndpointProvider.load(TestHttpEndpointProvider.java:17)
2025-04-23T20:28:46.4100626Z 	at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:191)
2025-04-23T20:28:46.4101079Z 	at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:660)
2025-04-23T20:28:46.4101522Z 	at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:712)
2025-04-23T20:28:46.4101842Z 	... 1 more
2025-04-23T20:28:46.4101938Z 
2025-04-23T20:28:46.4102203Z [ERROR] java.lang.IllegalStateException: Internal error: Attempted to close a launcher session which had already been closed.
2025-04-23T20:28:46.4102772Z 	at io.quarkus.test.config.ConfigLauncherSession.launcherSessionClosed(ConfigLauncherSession.java:45)
2025-04-23T20:28:46.4103489Z 	at org.junit.platform.launcher.core.DefaultLauncherSession.close(DefaultLauncherSession.java:76)
2025-04-23T20:28:46.4103958Z 	at org.apache.maven.surefire.junitplatform.LazyLauncher.close(LazyLauncher.java:80)
2025-04-23T20:28:46.4104470Z 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.closeLauncher(JUnitPlatformProvider.java:199)
2025-04-23T20:28:46.4105059Z 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)
2025-04-23T20:28:46.4105742Z 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:122)
2025-04-23T20:28:46.4106265Z 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
2025-04-23T20:28:46.4106712Z 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
2025-04-23T20:28:46.4107105Z 	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
```

**Comment by holly-cummins** [comment]
> I see a couple of errors in the logs, some of which didn't actually make the build fail but still look a bit concerning (and that's why I'm listing them here):

Sorry, I should have marked this as draft once the build was underway. It's definitely not ready to merge. :( I keep having to toggle between draft and not-draft to evaluate changes and I'm sometimes forgetting. 

I can do a really nice fix for the original Camel problem, but because Gradle does its classloading outisde the JUnit discovery phase, the fix doesn't work for gradle. I can get gradle working, but gradle continuous testing was harder. I've managed to get that working with a TCCL hack, but I wouldn't want to merge it ... and the CI has shown that with all that, maven isn't working. So definitely a work in progress. 

That's a good spot about the stack traces, though. *Hopefully* when I get a proper clean fix the logs will also be clean, but I'll make sure to look through the CI ones.

**Comment by gsmet** [comment]
Oh don't worry, it was obvious it wasn't ready to merge. But I was curious and then I saw more errors than what the report was saying so I thought it was a good idea mentioning them.

**Comment by holly-cummins** [comment]
I now *am* ready to declare victory on this particular issue. I've checked the logs and confirmed the `2025-04-24T18:57:06.3745132Z 2025-04-24 18:57:06,306 WARNING [org.jun.jup.eng.con.InstantiatingConfigurationParameterConverter] (Test runner thread) Failed to load default class orderer class 'io.quarkus.test.config.QuarkusClassOrderer' set via the 'junit.jupiter.testclass.order.default' configuration parameter. Falling back to default behavior.: java.lang.ClassNotFoundException: io.quarkus.test.config.QuarkusClassOrderer` message is gone. In an ideal world, we'd have a failing test for that, not just a stack trace, but I don't want to block this fix for that. 

At one point I got excited because an intermediate version of this fix also fixed https://github.com/quarkusio/quarkus/issues/47657. That's now no longer the case, so we definitely still have TCCL issues, especially in continuous testing. But this is a step forward, so I think it's worth knocking this one off and then moving forward to the other issues with this in the codebase. 

I'm also wondering if it's worth trying to ask gradle for some hooks we could use, so we can be more targeted in when we set the TCCL for classloading, but that would be a longer-term thing.

File: test-framework/junit5/src/main/java/io/quarkus/test/junit/launcher/CustomLauncherInterceptor.java [hunk 1]
```diff
@@ -1,21 +1,29 @@
...
+    private static FacadeClassLoader facadeLoader = null;
+    // Also use a static variable to store a 'first' starting state that we can reset to
+    private static ClassLoader origCl = null;
 
     public CustomLauncherInterceptor() {
     }
 
+    private static boolean isProductionModeTests() {
+        // We're too early for config to be available, so just check the system props
+        return System.getProperty("prod.mode.tests") != null;
```
Comment (aloubyansky) [inline test-framework/junit5/src/main/java/io/quarkus/test/junit/launcher/CustomLauncherInterceptor.java:20]: What sets this property?

**Review by aloubyansky — APPROVED** [review]
Thanks @holly-cummins. Approving it.

I think having another test classloading design review session following what we've discovered following this path would be useful. My impression is the changes we add to fix/workaround issues make the codebase challenging to maintain and evolve in the future. Not that it was simple before that, of course.

**Comment by holly-cummins** [comment]
> Thanks @holly-cummins. Approving it.
> 
> I think having another test classloading design review session following what we've discovered following this path would be useful. My impression is the changes we add to fix/workaround issues make the codebase challenging to maintain and evolve in the future. Not that it was simple before that, of course.

Good idea. I'd like to have a "Life of a TCCL" session where we trace through all the places it gets set and the requirement that setting it is fulfilling and produce a visualisation. Config is a big driver of the current TCCL dance (having a 'findable' config means we need a predictable classloader we can put it on, and then making sure the classes are compatible when it's retrieved). So there may be something we can simplify there. 

The "gradle doesn't load classes in the JUnit discovery phase" is also driving a lot of complexity (and is maddening). If we could somehow fix that we could drop setting the TCCL in the session interceptor and everything would become cleaner.

File: test-framework/junit5/src/main/java/io/quarkus/test/junit/launcher/CustomLauncherInterceptor.java (hunk 1 above)
Comment (holly-cummins) [reply test-framework/junit5/src/main/java/io/quarkus/test/junit/launcher/CustomLauncherInterceptor.java:20]: Do you know, I have no idea. Good spot. This is the same code as before, just refactored for clarity. I think I must have found it by inspection of the system properties in native tests, because I can't find it in the source code. There must be a cleaner way, so I'll raise an issue.
