### PR TITLE
Fix the path to MetricsRequestHandler when quarkus.http.root-path is set

### LINKED ISSUE #14516: Metrics throw a 500 Internal Server Error when Application has configured a quarkus.http.root-path
**Describe the bug**
When the App has a quarkus.http.root-path configured I get a 500 and the Error:
`The expected context root of metrics is /q/metrics, but a request with a different path was routed to MetricsRequestHandler`
when trying to browse Metrics.

**Expected behavior**
Metrics should also work with a root path.

**Actual behavior**
Browsing to http://localhost:8095/admin/q/metrics throws a 500. The root path is named admin and before version 1.11.0 it has worked with a root path

**To Reproduce**

1. Create a project with quarkus.http.root-path=/admin
2. Add quarkus-smallrye-metrics
3. Try to browse metrics.

**Configuration**
```properties
# Add your application.properties here, if applicable.
quarkus.http.port=8095
quarkus.http.root-path=/admin
```

**Screenshots**
image

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin bwand-mac.local 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec 2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64
 - Output of `java -version`: openjdk version "11.0.2" 2019-01-15
 - GraalVM version (if different from Java): No Native Build
 - Quarkus version or git rev: powered by Quarkus 1.11.0.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Maven 3.6.3

### PR DESCRIPTION
**Pull request by jmartisk**
Fixes #14516

### CODE REVIEW

File: extensions/smallrye-metrics/deployment/src/main/java/io/quarkus/smallrye/metrics/deployment/SmallRyeMetricsProcessor.java [hunk 1]
```diff
@@ -165,13 +167,13 @@ void createRoute(BuildProducer<RouteBuildItem> routes,
         }
         routes.produce(new RouteBuildItem.Builder()
                 .routeFunction(route)
```
Comment (kenfinnigan) [inline extensions/smallrye-metrics/deployment/src/main/java/io/quarkus/smallrye/metrics/deployment/SmallRyeMetricsProcessor.java:169]: Would it be better for `NonApplicationRootPathBuildItem.adjustPath()` to do this adjustment rather than sprinkling it into each extension that needs it? As I think all extensions would need this.

I vaguely recall having it do that at one point but can't remember why I took it out now. Maybe because at the time I was thinking /q would always be at the root and not be impacted by the HTTP root.

One thing we need to think about is how this being done at static init is impacted by the root path being changed on the command line at start. That might have been the reasons why I was originally thinking not hanging it off the app path

Comment (jmartisk) [reply extensions/smallrye-metrics/deployment/src/main/java/io/quarkus/smallrye/metrics/deployment/SmallRyeMetricsProcessor.java:169]: > Would it be better for NonApplicationRootPathBuildItem.adjustPath() to do this adjustment rather than sprinkling it into each extension that needs it? 

Perhaps yes, but then we would need to refactor these two build items and probably merge them into one, because I think you can't inject a build item into another build item to read its value... We would need a single build item that knows both of these configured roots.

To make it more complicated, in some places you need to pass a path adjusted only for the `nonApplicationRootPath` (like the constructor of `NotFoundPageDisplayableEndpointBuildItem` for example), while other places require a path adjusted for both root paths (like here in this PR), and some places require the path to be not adjusted at all (like `RouteBuildItem.route(path)`).
Maybe it would make more sense to improve the javadocs to make it more clear how adjusted a path needs to be?

> One thing we need to think about is how this being done at static init is impacted by the root path being changed on the command line at start.

It's not impacted at all, overriding the root paths at start has no effect, because they're build-time-only properties (you get a warning if you try to override them at startup).

Comment (kenfinnigan) [reply extensions/smallrye-metrics/deployment/src/main/java/io/quarkus/smallrye/metrics/deployment/SmallRyeMetricsProcessor.java:169]: Shouldn't be an issue to modify https://github.com/quarkusio/quarkus/blob/master/extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/VertxHttpProcessor.java#L83 to take the `HttpBuildPathItem` as a parameter and pass it to the creation of the non application one.

Could we have two methods for adjusting the path on `NonApplicationRootPathBuildItem`? One that takes into account the HTTP Root and one that doesn't?

For some reason I thought it was run time, must have been confused with port.

Comment (jmartisk) [reply extensions/smallrye-metrics/deployment/src/main/java/io/quarkus/smallrye/metrics/deployment/SmallRyeMetricsProcessor.java:169]: It feels a little bit like duplicating functionality of one BuildItem in another, but ok I applied that, please check

File: extensions/smallrye-metrics/deployment/src/main/java/io/quarkus/smallrye/metrics/deployment/SmallRyeMetricsProcessor.java [hunk 2]
```diff
@@ -154,6 +155,7 @@ MetricsCapabilityBuildItem metricsCapabilityBuildItem() {
     void createRoute(BuildProducer<RouteBuildItem> routes,
             SmallRyeMetricsRecorder recorder,
             NonApplicationRootPathBuildItem frameworkRoot,
+            HttpRootPathBuildItem httpRoot,
```
Comment (kenfinnigan) [inline extensions/smallrye-metrics/deployment/src/main/java/io/quarkus/smallrye/metrics/deployment/SmallRyeMetricsProcessor.java:158]: Is this parameter still needed?

**Comment by gsmet** [comment]
@jmartisk I let you drive this puppy home before tomorrow evening? Looks like something we really want in 1.11.1.Final.

**Comment by jmartisk** [comment]
I've resolved some last minor things and think it is ready

**Review by kenfinnigan — APPROVED** [review]

**Comment by gsmet** [comment]
Perfect, thanks a lot to both of you!
