### PR TITLE
Fix user methods requiring a session in Panache REST Data with Reactive

### LINKED ISSUE #34432: User methods requiring a session in Hibernate Reactive does not work for interfaces of Panache REST Data extension
### Describe the bug

Two problems:

First, run `curl -H 'Content-Type: application/json' localhost:8080/bot --data-binary '{"id": "bot-a", "config": {}}' `, then these two commands fail:

1. `curl localhost:8080/bot` throws exception,  `rs.getString()` failed on JsonObject.

```
Caused by: java.lang.ClassCastException: Invalid String value type class io.vertx.core.json.JsonObject
                        at io.vertx.sqlclient.Tuple.getString(Tuple.java:410)
                        at org.hibernate.reactive.adaptor.impl.ResultSetAdaptor.getString(ResultSetAdaptor.java:80)
                        at org.hibernate.type.descriptor.jdbc.JsonJdbcType$2.doExtract(JsonJdbcType.java:140)
                        at org.hibernate.type.descriptor.jdbc.BasicExtractor.extract(BasicExtractor.java:44)
                        at org.hibernate.reactive.sql.exec.spi.ReactiveValuesResultSet.lambda$readCurrentRowValues$2(ReactiveValuesResultSet.java:145)
                        ... 35 more
```

2. `curl localhost:8080/bot/all2` throws exception too:
```
java.lang.IllegalStateException: No current Mutiny.Session found
        - no reactive session was found in the context and the context was not marked to open a new session lazily
        - you might need to annotate the business method with @WithSession
        at io.quarkus.hibernate.reactive.panache.common.runtime.SessionOperations.getSession(SessionOperations.java:155)
        at io.quarkus.hibernate.reactive.panache.common.runtime.AbstractJpaOperations.getSession(AbstractJpaOperations.java:351)
        at io.quarkus.hibernate.reactive.panache.common.runtime.AbstractJpaOperations.findAll(AbstractJpaOperations.java:179)
```

BotResource.java:

```java
public interface BotResource extends PanacheEntityResource<BotEntity, String> {

    @GET
    @Path("/all2")
    @Produces("application/json")
    default Uni<List<BotEntity>> all2() {
        return BotEntity.findAll().list();
    }
}
```

BotEntity.java:

```java
import io.quarkus.hibernate.reactive.panache.PanacheEntityBase;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

@Entity
@Table(name = "bot")
public class BotEntity extends PanacheEntityBase {

    @Id
    @Column(length = 24, nullable = false)
    public String id;

    @Enumerated(EnumType.STRING)
    @Column(length = 8, nullable = false, columnDefinition = "VARCHAR(8) DEFAULT 'DRAFT'")
    public Status status = Status.DRAFT;

    @Column(name = "created_at", insertable = false, updatable = false,
            nullable = false, columnDefinition = "DATETIME DEFAULT current_timestamp")
    public Instant createdAt;

    @Column(name = "updated_at", insertable = false, updatable = false,
            nullable = false, columnDefinition = "DATETIME DEFAULT current_timestamp ON UPDATE current_timestamp")
    public Instant updatedAt;

    @JdbcTypeCode(SqlTypes.JSON)
    @Column(nullable = false)
    public BotConfig config;

    public static enum Status {
        DRAFT, REVIEW, REJECTED, APPROVED, DELETED
    }
}
```

BotConfig.java
```java
public class BotConfig {

    public String name;
}
```

### Expected behavior

Doesn't throw exception.

### Actual behavior

Throws exception.

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

Darwin xxx 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64 x86_64

### Output of `java -version`

OpenJDK 64-Bit Server VM Temurin-17+35 (build 17+35, mixed mode, sharing)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

3.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.8 (4c87b05d9aedce574290d1acc98575ed5eb6cd39)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Sgitario**
These changes add the `@WithSessionOnDemand` annotation at class level when using Panache REST Data with Hibernate Reactive. 

This annotation makes user methods that return an Uni class to work.

About tests, I've covered the following scenarios:
- user GET method that returns an Uni
- user POST method that returns an Uni (and requires a transaction)
- injecting the generated resource will also work

Fix https://github.com/quarkusio/quarkus/issues/34432

### CODE REVIEW

**Review by geoand — APPROVED** [review]
LGTM

File: extensions/panache/hibernate-reactive-rest-data-panache/deployment/src/test/java/io/quarkus/hibernate/reactive/rest/data/panache/deployment/entity/CollectionsResource.java [hunk 1]
```diff
@@ -1,8 +1,32 @@
...
+import jakarta.ws.rs.Path;
+import jakarta.ws.rs.PathParam;
+
+import io.quarkus.hibernate.reactive.panache.common.WithSessionOnDemand;
 import io.quarkus.hibernate.reactive.rest.data.panache.PanacheEntityResource;
 import io.quarkus.rest.data.panache.ResourceProperties;
+import io.smallrye.mutiny.Uni;
 
 @ResourceProperties(hal = true, paged = false, halCollectionName = "item-collections")
+@WithSessionOnDemand
```
Comment (mkouba) [inline extensions/panache/hibernate-reactive-rest-data-panache/deployment/src/test/java/io/quarkus/hibernate/reactive/rest/data/panache/deployment/entity/CollectionsResource.java:16]: This annotation should not be necessary here, or?

File: extensions/panache/rest-data-panache/deployment/src/main/java/io/quarkus/rest/data/panache/deployment/JaxRsResourceImplementor.java [hunk 2]
```diff
@@ -107,6 +108,9 @@ private void implementClassAnnotations(ClassCreator classCreator, ResourceMetada
                 classCreator.addAnnotation(classAnnotation);
             }
         }
+        if (capabilities.isPresent(Capability.HIBERNATE_REACTIVE)) {
```
Comment (mkouba) [inline extensions/panache/rest-data-panache/deployment/src/main/java/io/quarkus/rest/data/panache/deployment/JaxRsResourceImplementor.java:111]: I don't know how Panache REST Data works internally, but why is this actually needed? Is this class reused by the reactive version as well?

Comment (Sgitario) [reply extensions/panache/rest-data-panache/deployment/src/main/java/io/quarkus/rest/data/panache/deployment/JaxRsResourceImplementor.java:111]: Exactly, this implementor is used also for HIBERNATE classic, so we need to check the capabilities.

File: extensions/panache/hibernate-reactive-rest-data-panache/deployment/src/test/java/io/quarkus/hibernate/reactive/rest/data/panache/deployment/entity/CollectionsResource.java (hunk 1 above)
Comment (Sgitario) [reply extensions/panache/hibernate-reactive-rest-data-panache/deployment/src/test/java/io/quarkus/hibernate/reactive/rest/data/panache/deployment/entity/CollectionsResource.java:16]: This was actually a leftover, thanks for spotting!

Comment (Sgitario) [reply extensions/panache/hibernate-reactive-rest-data-panache/deployment/src/test/java/io/quarkus/hibernate/reactive/rest/data/panache/deployment/entity/CollectionsResource.java]: PR updated

File: extensions/resteasy-reactive/jaxrs-client-reactive/deployment/src/main/java/io/quarkus/jaxrs/client/reactive/deployment/ParamData.java [hunk 3]
```diff
@@ -0,0 +1,27 @@
...
+
+import org.jboss.jandex.AnnotationInstance;
+import org.jboss.jandex.ClassInfo;
+
+/**
+ * ClientxxxParam annotations can be defined on a JAX-RS interface or a sub-client (sub-resource).
+ * If we're filling parameters for a sub-client, we need to know the defining class of the ClientxxxParam
+ * to properly resolve default methods of the "root" client
+ */
+public class ParamData {
```
Comment (mkouba) [inline extensions/resteasy-reactive/jaxrs-client-reactive/deployment/src/main/java/io/quarkus/jaxrs/client/reactive/deployment/ParamData.java:11]: Where's this class used?

Comment (Sgitario) [reply extensions/resteasy-reactive/jaxrs-client-reactive/deployment/src/main/java/io/quarkus/jaxrs/client/reactive/deployment/ParamData.java]: Sorry again, this was part of another work I was doing and added here by mistake. Removed.

Comment (mkouba) [reply extensions/resteasy-reactive/jaxrs-client-reactive/deployment/src/main/java/io/quarkus/jaxrs/client/reactive/deployment/ParamData.java]: No problem :-)

**Review by mkouba — APPROVED** [review]

**Comment by gsmet** [comment]
Do we want this backported to 3.2? If so please add the backport label.

**Comment by Sgitario** [comment]
> Do we want this backported to 3.2? If so please add the backport label.

I would not backport this since there is an existing workaround.

**Comment by Dieken** [comment]
Isn’t 3.2 a LTS version?  I would like it’s backported, the explicit call to `Panache.withSession` is very ugly, does’t match the non-reactive version.

**Comment by Dieken** [comment]
@Sgitario   could you consider again to backport this fix to 3.2?   If 3.2 will be a LTS version,  the workaround is very ugly, I would like to have consistent developer experience with non-reactive version.

**Comment by Sgitario** [comment]
> @Sgitario could you consider again to backport this fix to 3.2? If 3.2 will be a LTS version, the workaround is very ugly, I would like to have consistent developer experience with non-reactive version.

These changes introduce a very major change from a technical view perspective, so I would like to iterate over the solution a bit more, to make sure everything works as before.

**Comment by Sgitario** [comment]
@Dieken since this solution seems to work fine in some test iterations (for a few days). I've just added the `backport` label to incorporate these changes into 3.2.
