### PR TITLE
Fix deadlock in command mode

### LINKED ISSUE #9163: Command mode doesn't exit after unchecked exception
**Describe the bug**
Command mode projects will not exit if an unchecked exception occurs (might not only be that, but that's how I reproduced it.). It will show the stacktrace then sit doing nothing.

**Expected behavior**
I would expect the application to exit after the stacktrace and any following code has executed.

**Actual behavior**
It shows the stacktrace but does nothing afterwards.

**To Reproduce**
1. Create an empty quarkus command mode project with the following code:
JavaMain:
```
@QuarkusMain
public class JavaMain
{
  public static void main(String... args) {
    Quarkus.run(Testing.class, args);
  }
}
```
Testing.java:
```
public class Testing implements QuarkusApplication
{
  @Override
  public int run(final String... args) {
    boolean willFail = args[0].equals("foo");

    return 0;
  }
}
```
2. Run either in Intellij or command line. Behavior was observed to be the same in Intellij and dockerized native image.

**Configuration**
No additional configuration is needed.

**Screenshots**
Screen Shot 2020-05-07 at 11 17 48 AM

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
**Darwin MacBook-Pro.local 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64**
 - Output of `java -version`: 
**openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.3+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.3+7, mixed mode)**
 - GraalVM version (if different from Java): 
**Used the default Quarkus native build plugins**
 - Quarkus version or git rev: 
**1.4.1.Final**
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
**Tested with mvnw and mvn, both 3.6.3**

**Additional context**
(Add any other context about the problem here.)

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #9163

### CODE REVIEW

**Comment by geoand** [comment]
@stuartwdouglas this is what I came up with (and it fixes the problem), but I am not 100% sure it's the right solution.

File: core/runtime/src/main/java/io/quarkus/runtime/ApplicationLifecycleManager.java [hunk 1]
```diff
@@ -142,12 +142,8 @@ public static final void run(Application application, Class<? extends QuarkusApp
             } finally {
                 stateLock.unlock();
             }
-            application.stop(new Runnable() {
```
Comment (stuartwdouglas) [inline core/runtime/src/main/java/io/quarkus/runtime/ApplicationLifecycleManager.java:145]: I think this will break some tests, although I can't remember the details. Maybe the default handler that calls System.exit() needs to do it from a new thread.

Comment (geoand) [reply core/runtime/src/main/java/io/quarkus/runtime/ApplicationLifecycleManager.java:145]: Yeah I thought so as well, but when I ran the CI on my fork, all tests passed.

So should I leave it as is (assuming we'll get green CI here as well) or change to use another thread?

Comment (stuartwdouglas) [reply core/runtime/src/main/java/io/quarkus/runtime/ApplicationLifecycleManager.java:145]: I know I had a good reason for doing it this way, but I can't actually remember what it was. Maybe subsequent changes mean it is not needed now, so if CI passes then lets merge, and if we see intermittent failures we can change it.

Comment (geoand) [reply core/runtime/src/main/java/io/quarkus/runtime/ApplicationLifecycleManager.java:145]: Cool, makes sense

**Comment by geoand** [comment]
@stuartwdouglas CI is all green.

**Review by stuartwdouglas — APPROVED** [review]
