### PR TITLE
Kafka Streams fire event after created and before scheduling the start

### LINKED ISSUE #36341: The API method KafkaStreams#cleanUp() is not applicable when use @Produces to build the topology
### Describe the bug

To delete the Kafka streams application’s local state directory on any machines where the Kafka streams application instance was run. You must do this before restarting an application instance on the same machine. 

You can use this method:The API method KafkaStreams#cleanUp() in your application code.

The is issue is that the clean up process is not applicable when we use @Produces to build the topology as below:

`@Produces
    public Topology buildTopology() {
        StreamsBuilder builder = new StreamsBuilder();
 return builder.build();
    }`

The Kafka streams is created by quarkus internally and there is no any control to clean up the streams before start up.

Kafka reference: [https://kafka.apache.org/24/documentation/streams/developer-guide/app-reset-tool.html](url)

### Expected behavior

Have a separate function that can clean up the streams before start.

### Actual behavior

there is no way to clean up the kafka streams 

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

openjdk version "17.0.2" 

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

3.4.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ozangunalp**
Schedules the KafkaStreams#start at StartupEvent instead of PostConstruct.
Removes Startup annotation from producer methods.

Fixes #36341 and #36774

Corrects Kafka streams default Kafka broker to localhost:9092 instead of 9012.

Switching StartupEvent I haven't noticed any change in registered classes for native compilation

### CODE REVIEW

**Comment by ozangunalp** [comment]
@cescoffier I imagine the default kafka broker to port 9012 was a mistake ?

**Comment by cescoffier** [comment]
Oh yeah, nice typo!

**Review by cescoffier — APPROVED** [review]

File: extensions/kafka-streams/runtime/src/main/java/io/quarkus/kafka/streams/runtime/KafkaStreamsProducer.java [hunk 1]
```diff
@@ -101,33 +106,53 @@ public KafkaStreamsProducer(KafkaStreamsSupport kafkaStreamsSupport, KafkaStream
...
+        this.kafkaStreams = initializeKafkaStreams(streamsConfig, topology.get(),
+                kafkaClientSupplier, stateListener, globalStateRestoreListener, uncaughtExceptionHandlerListener);
         this.kafkaStreamsTopologyManager = new KafkaStreamsTopologyManager(kafkaAdminClient);
     }
 
-    @PostConstruct
-    public void postConstruct() {
+    public void onStartup(@Observes StartupEvent event) {
         if (kafkaStreams != null) {
             Arc.container().beanManager().getEvent().select(KafkaStreams.class).fire(kafkaStreams);
```
Comment (mkouba) [inline extensions/kafka-streams/runtime/src/main/java/io/quarkus/kafka/streams/runtime/KafkaStreamsProducer.java:121]: You can replace `Arc.container().beanManager().getEvent().select(KafkaStreams.class)` with a method parameter of type `Event<KafkaStreams>`.

**Review by mkouba — COMMENTED** [review]
I've added one minor comment, otherwise looks good.

File: extensions/kafka-streams/runtime/src/main/java/io/quarkus/kafka/streams/runtime/KafkaStreamsProducer.java (hunk 1 above)
Comment (ozangunalp) [reply extensions/kafka-streams/runtime/src/main/java/io/quarkus/kafka/streams/runtime/KafkaStreamsProducer.java:121]: Do you mean injecting `Event<KafkaStreams>` and fire in the method?

Comment (mkouba) [reply extensions/kafka-streams/runtime/src/main/java/io/quarkus/kafka/streams/runtime/KafkaStreamsProducer.java:121]: I mean: 
```java
 public void onStartup(@Observes StartupEvent event, Event<KafaStreams> streamsEvent) {
     if (kafkaStreams != null) {
        steams.fire(kafkaStreams);
     }    
    // ...
 }
```

because parameters of observer methods are injection points...

Comment (ozangunalp) [reply extensions/kafka-streams/runtime/src/main/java/io/quarkus/kafka/streams/runtime/KafkaStreamsProducer.java]: Yes, that's exactly what I had in mind, Thanks!
