### PR TITLE
Process classes from the application artifact instead of the module output directory

### LINKED ISSUE #31375: RuntimeException using VirtualThreads with Jacoco
### Describe the bug

Building a quarkus 2.16.3 app using Virtual threads on JDK 19 I came up with the following error on runtime : 
```
Method xxx of class 'XXX' uses @RunOnVirtualThread but the target JDK version doesn't support virtual threads. Please configure your build tool to target Java 19 or above.
```

I know my project is built correctly using the JDK19 because I checked the .class major version and it was correctly set to `63`.

### Expected behavior

No error.

### Actual behavior

[It seems like Quarkus pickups the first class file it found in the build directory to determine the project majorVersion.](https://github.com/quarkusio/quarkus/blob/bdbd55cc01607f70dde041c8d45667f554f48b6b/core/deployment/src/main/java/io/quarkus/deployment/steps/CompiledJavaVersionBuildStep.java#L30)

I have run the `compiledJavaVersion` function on my built files and it always picked up AgentJar.class file (From Jacoco) with a majorVersion set to 49. 
Here is another Jacoco class getting picked up by your algo after setting `classDumpDir` with : 
```
classDumpDir = layout.buildDirectory.dir('jacoco/classpathdumps').get().asFile
```

```
KryoException.a0b9661061bc7653.class
majorFound : 49
```

### How to Reproduce?

- Clone this [project](https://github.com/HiddenSplioGuy/jacoco-virtual-threads-reproducer) 
- Execute the project test in a gitlab runner environment (I use https://www.npmjs.com/package/gitlab-ci-local#installation)
- `gradle build --info` to see the error in the gitlab runner env.
- It works flawlessly locally

### Output of `uname -a` or `ver`

`Linux 91d7275ab5b8 5.15.79.1-microsoft-standard-WSL2 #1 SMP Wed Nov 23 01:01:46 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

### Output of `java -version`

```
openjdk version "19.0.2" 2023-01-17
OpenJDK Runtime Environment Temurin-19.0.2+7 (build 19.0.2+7)
OpenJDK 64-Bit Server VM Temurin-19.0.2+7 (build 19.0.2+7, mixed mode, sharing)
```

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.16.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

8.0.1

### Additional information

Is quarkus-jacoco using the latest Jacoco version with jdk19 class support ? 
https://github.com/jacoco/jacoco/releases

### LINKED ISSUE #42884: `CompiledJavaVersionBuildStep` may load a wrong class number with gradle
### Describe the bug

`CompiledJavaVersionBuildStep` will try to produce  a `CompiledJavaVersionBuildItem` by walking the build directory and finding the first java class it can get a java version from.
This is problematic as gradle often uses the `build/tmp/.cache` directory to unzip temporary files, that may contain classes and the version of these classes may be loaded instead of the ones from the project.

This can prevent some builds from using virtual threads with `@RunOnVirtualThread` for example.

### Expected behavior

The java version should be retrieved from a class compiled by the gradle project.

### Actual behavior

The java version is retrieved from the first found class, even from some temporary build directory

### How to Reproduce?

Reproducer her [https://github.com/Malandril/quarkus-bug-virtual-jacoco.git](https://github.com/Malandril/quarkus-bug-virtual-jacoco.git)

clone it then run 
`./gradlew test jacocoTestReport`

It should fail, because the `CompiledJavaVersionBuildStep` will load the version from a class in `build/tmp/.cache/expanded/zip_zipchecksum/org/jacoco/agent/package-info.class/package-info.class` which is of java 5 instead of java 21

### Output of `java -version`

openjdk version "21.0.2" 2024-01-16

### Quarkus version or git rev

3.14.1
### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.8

### Additional information

Maybe we could simply exclude hidden folders from the `SimpleFileVisitor` in the `CompiledJavaVersionBuildStep` ?
This would not ensure that a project class will be loaded, but would solve the issue with jacoco at lease

### PR DESCRIPTION
**Pull request by aloubyansky**
The output directory may contain all sorts of content, including classes that don't belong to the application itself.

- Fixes: #42884
- Fixes: #31375

### CODE REVIEW

File: core/deployment/src/main/java/io/quarkus/deployment/steps/CompiledJavaVersionBuildStep.java [hunk 1]
```diff
@@ -26,40 +22,28 @@ public class CompiledJavaVersionBuildStep {
...
+            if (file.getFileName().toString().endsWith(".class") && !Files.isDirectory(file)) {
+                log.debugf("Checking file '%s'", file.toAbsolutePath().toString());
+                try (DataInputStream data = new DataInputStream(Files.newInputStream(file))) {
+                    if (0xCAFEBABE == data.readInt()) {
+                        data.readUnsignedShort(); // minor version -> we don't care about it
+                        int v = data.readUnsignedShort();
+                        majorVersion.set(v);
+                        log.debugf("Determined compile java version to be %d", v);
+                        visit.stopWalking();
+                        log.info("GOT JAVA VERSION " + v);
```
Comment (aloubyansky) [inline core/deployment/src/main/java/io/quarkus/deployment/steps/CompiledJavaVersionBuildStep.java:39]: oh, i need to remove this

**Review by geoand — APPROVED** [review]
Thanks!

**Comment by aloubyansky** [comment]
@gsmet you may want to look at this error in the Build report
