### PR TITLE
Integrate Fernflower decompiler into Quarkus build of fast-jar

### LINKED ISSUE #612: Print disassembly of generated bytecode
Writing an extension that generates bytecode with ASM or gizmo pretty often you get things wrong and have verify errors or just buggy generated code. It would be really nice if there were an option to make shamrock generate disassembled bytecode of what we just generated.

### PR DESCRIPTION
**Pull request by geoand**
This makes it easy for Quarkus developers and extension authors
to see the bytecode that Quarkus produces  (both generated and transformed)

Fixes: #612

### CODE REVIEW

**Comment by geoand** [comment]
cc @FroMage @stuartwdouglas

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/JarResultBuildStep.java [hunk 1]
```diff
@@ -667,6 +700,56 @@ public void accept(Path path) {
         return new JarBuildItem(initJar, null, libDir, packageConfig.type, null);
     }
 
+    private void downloadFernflowerJar(PackageConfig packageConfig, Path fernflowerJar) {
+        String downloadURL = String.format("https://jitpack.io/com/github/fesh0r/fernflower/%s/fernflower-%s.jar",
```
Comment (gsmet) [inline core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/JarResultBuildStep.java:704]: Is there a reason we download it rather than making it a build dependency?

Comment (geoand) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/JarResultBuildStep.java:704]: My reasoning is that this is super unlikely to be used by regular users, so there should be no reason to make it an explicit dependency.

Comment (gsmet) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/JarResultBuildStep.java:704]: I see it's not on Maven Central but maybe we could ask nicely?

Comment (geoand) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/JarResultBuildStep.java:704]: Was going to mention that as well.

For the time being it's only available on Jitpack because some fellow forked the Jetbrains repo and configured Jitpack.

I'll open an issue on the Jetbrains tracker

Comment (gsmet) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/JarResultBuildStep.java:704]: It's a bit more complicated than that. We had quite a lot of corporate users complaining it's hard to download things outside of Maven Central. So downloading from Maven Central is usually the way to go. Not sure downloading it always would be a big issue given how many artifacts people get to download to do a build. But I have no idea how big it is.

Comment (geoand) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/JarResultBuildStep.java:704]: I opened IDEA-262376.

But let's be clear about the scope of this PR: This is extremely unlikely to be used by anyone not developing Quarkus extensions or Core (more likely only the latter...)

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/JarResultBuildStep.java [hunk 2]
```diff
@@ -667,6 +700,56 @@ public void accept(Path path) {
...
+                packageConfig.fernflower.hash, packageConfig.fernflower.hash);
+        try (BufferedInputStream in = new BufferedInputStream(new URL(downloadURL).openStream());
+                FileOutputStream fileOutputStream = new FileOutputStream(fernflowerJar.toFile())) {
+            byte[] dataBuffer = new byte[1024];
+            int bytesRead;
+            while ((bytesRead = in.read(dataBuffer, 0, 1024)) != -1) {
+                fileOutputStream.write(dataBuffer, 0, bytesRead);
+            }
+        } catch (IOException e) {
+            log.debug("Unable to download Fernflower from " + downloadURL, e);
```
Comment (gsmet) [inline core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/JarResultBuildStep.java:714]: Given you explicitly enable it, I think this should be logged as an error.

Comment (geoand) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/JarResultBuildStep.java:714]: You are probably right. I was on the fence, but I'll go with your suggestion

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/JarResultBuildStep.java [hunk 3]
```diff
@@ -481,6 +486,23 @@ private JarBuildItem buildThinJar(CurateOutcomeBuildItem curateOutcomeBuildItem,
...
+        Path fernflowerJar = null;
+        Path decompiledOutputDir = null;
+        boolean wasDecompiledSuccessfully = true;
+        if (packageConfig.fernflower.enabled) {
+            Path jarDirectory = Paths.get(packageConfig.fernflower.jarDirectory);
+            if (!Files.exists(jarDirectory)) {
+                Files.createDirectory(jarDirectory);
+            }
+            fernflowerJar = jarDirectory.resolve(FERNFLOWER_JAR);
+            if (!Files.exists(fernflowerJar)) {
```
Comment (gsmet) [inline core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/JarResultBuildStep.java:498]: You will need to deal with updates somehow. So I think you probably need to include the git hash or a signature in the filename.

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/JarResultBuildStep.java (hunk 2 above)
Comment (geoand) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/JarResultBuildStep.java]: Fixed

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/JarResultBuildStep.java (hunk 3 above)
Comment (geoand) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/JarResultBuildStep.java:498]: Yeah, I guess that makes sense

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/JarResultBuildStep.java (hunk 1 above)
Comment (gsmet) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/JarResultBuildStep.java:704]: Also with Maven, you get signature checking, automatic updates with Dependabot and so on.

It's not on Maven atm so we can't really do anything about it but maybe we could ask?

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/JarResultBuildStep.java (hunk 3 above)
Comment (geoand) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/JarResultBuildStep.java:498]: Fixed

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/JarResultBuildStep.java (hunk 1 above)
Comment (geoand) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/JarResultBuildStep.java:703]: Yup, I did just that in https://youtrack.jetbrains.com/issue/IDEA-262376

Comment (geoand) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/JarResultBuildStep.java:703]: > But I have no idea how big it is.

For the hash I have used, the jar is around 600kB

**Comment by geoand** [comment]
The gradle failure is the same seen in other PRs, it has nothing to do with this PR

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/JarResultBuildStep.java (hunk 1 above)
Comment (FroMage) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/JarResultBuildStep.java:706]: I was going to suggest making this default to true if the current user is `stephane`, but that jar thing looks like an attack vector :-/

**Review by FroMage — COMMENTED** [review]
That's awesome. Didn't I write some exception catcher that dumped a disassembled class using ASM, _somewhere_?

Is this decompiler better than the ASM one?

Does it deal with the non-iodiomatic-Java bytecode we can produce?

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/JarResultBuildStep.java (hunk 1 above)
Comment (geoand) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/JarResultBuildStep.java:706]: Hahahhah

**Comment by geoand** [comment]
> That's awesome. Didn't I write some exception catcher that dumped a disassembled class using ASM, _somewhere_?
> 


Good question! I don't really know where that is...

> Is this decompiler better than the ASM one?
> 
> Does it deal with the non-iodiomatic-Java bytecode we can produce?

Its the decompiler IntelliJ uses and in all my experience with it and Quarkus, I have never opened a class file produced by Quarkus in it and not see a meaningful result.

**Comment by geoand** [comment]
Can I get a review of this please?

Thanks :)

**Comment by FroMage** [comment]
`IllegalClassExceptionMapper` in `quarkus-resteasy-reactive-deployment`. It dumps the offending method's bytecode, but it doesn't disassemble it because well, the bytecode is invalid…

So OK, not really the same thing as your PR. But we should really do something with it more generally because that's damn useful for devs.

**Review by FroMage — APPROVED** [review]

**Comment by geoand** [comment]
> generally because tha

Ah, right! We should definitely expand on it!

**Comment by FroMage** [comment]
So, if I am developing an extension and I fuck up my bytecode, with invalid ASM or even gizmo (invokevirtual instead of invokeinterface happened to me yesterday, though I don't expect that particular issue to crash a decompiler). What is the behaviour of this plugin? Does it crash or fall back to printing bytecodes or what?

**Comment by geoand** [comment]
It never crashes. In the worst case a `.java` file will be generated with a comment from the decompiler that it couldn't figure out the proper java code
