### PR TITLE
Properly set PoolOptions for REST Client

### LINKED ISSUE #42778: Rest Client (formerly reactive) keep using DEFAULT_MAX_POOL_SIZE
### Describe the bug

Quarkus 3.13.3
Java 21
Problem:

```
jakarta.ws.rs.ProcessingException: The timeout of 30000 ms has been exceeded when getting a connection to 10.148.10.23:8122
```

In Source code of Quarkus we have found this:
```
org.jboss.resteasy.reactive.client.impl;
public class ClientImpl implements Client {

    private static final Logger log = Logger.getLogger(ClientImpl.class);

    private static final int DEFAULT_CONNECT_TIMEOUT = 15000;
    private static final int DEFAULT_CONNECTION_POOL_SIZE = 20;
......

Object connectionPoolSize = configuration.getProperty(CONNECTION_POOL_SIZE);
        if (connectionPoolSize == null) {
            connectionPoolSize = DEFAULT_CONNECTION_POOL_SIZE;
        } else {
            log.debugf("Setting connectionPoolSize to %d", connectionPoolSize);
        }
        options.setMaxPoolSize((int) connectionPoolSize);
        options.setHttp2MaxPoolSize((int) connectionPoolSize);
....
```

But this is obviously ignored, see last image (dump of our service in visualvm).

Also, if you read documentation, you may find https://quarkus.io/guides/all-config#quarkus-rest-client-config_quarkus-rest-client-connection-pool-size.
And this is in source code used like that:
```
package io.quarkus.rest.client.reactive.runtime;

public class RestClientCDIDelegateBuilder<T> {
...

private void configureCustomProperties(QuarkusRestClientBuilder builder) {
       .....

        Optional<Integer> poolSize = oneOf(clientConfigByClassName().connectionPoolSize,
                clientConfigByConfigKey().connectionPoolSize, configRoot.connectionPoolSize);
        if (poolSize.isPresent()) {
            builder.property(QuarkusRestClientProperties.CONNECTION_POOL_SIZE, poolSize.get());
        }
.....
```

Then, we have set it up to `uarkus.rest-client.oms-client.connection-pool-size=1500` but this is ignored too.

Also, we tried to do https://quarkus.io/guides/rest-client#use-custom-http-options, but still no effect at all.

Look at our netstat:
изображение

Look at our dump:

изображение

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

Linux rmis01service 5.15.87-1.el7.3.x86_64 #1 SMP Mon Jan 16 21:44:20 MSK 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "21" 2023-09-19 LTS OpenJDK Runtime Environment Corretto-21.0.0.35.1 (build 21+35-LTS) OpenJDK 64-Bit Server VM Corretto-21.0.0.35.1 (build 21+35-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.13.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.9

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
- Fixes: #42778

### CODE REVIEW

**Review by cescoffier — APPROVED** [review]

File: independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/impl/ClientImpl.java [hunk 1]
```diff
@@ -192,7 +192,7 @@ public Vertx get() {
             options.setShared(true);
         }
 
-        var httpClientBuilder = this.vertx.httpClientBuilder().with(options);
+        var httpClientBuilder = this.vertx.httpClientBuilder().with(options).with(options.getPoolOptions());
```
Comment (gsmet) [inline independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/impl/ClientImpl.java:195]: Is it expected that the nested options are not applied by Vert.x? I would expect all the nested options to be applied when you do `with(options)`?

Especially since the nested structure is completely hidden from you.

Comment (gsmet) [reply independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/impl/ClientImpl.java:195]: In other words, while I'm all for a quick fix, I wonder if it's not a bug in Vert.x itself?

Comment (geoand) [reply independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/impl/ClientImpl.java:195]: It's a totally legitimate quetions which I also asked @cescoffier in chat before applying this. 

For now let's get it in and we can figure later out if we need to update Vert.x itself

**Comment by gsmet** [comment]
Yeah I totally agree we should merge and backport it.
