### PR TITLE
Automatically Load Liquibase Resource Files for Native Image Build

### LINKED ISSUE #40574: When Using Liquibase with "quarkus.liquibase.clean-at-start=true" a RuntimeException Is Thrown in Quarkus 3.10.0
### Describe the bug

At App startup an exception is thrown and the program exits, when using Liquibase with `quarkus.liquibase.clean-at-start=true` set.
This happens at least with Postgresql and H2.
The issue didn't occur before Quarkus 3.10.0
The problem happens for a local as well as an in-container build.

For Postgres, the following error is logged:

```
INFO  [liq.command] (main) Logging exception.
ERROR: Exception Details
ERROR: Exception Primary Class:  PSQLException
ERROR: Exception Primary Reason:  ERROR: relation "public.databasechangeloglock" does not exist
  Position: 8
ERROR: Exception Primary Source:  PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2)
INFO  [liq.command] (main) Command execution complete
2024-05-11 18:11:33,653 ERROR [io.qua.run.Application] (main) Failed to start application (with profile [prod]):
```

and the following exception is thrown:

```
java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
Caused by: java.lang.IllegalStateException: Error starting Liquibase
	at io.quarkus.liquibase.runtime.LiquibaseRecorder.doStartActions(LiquibaseRecorder.java:90)
	at io.quarkus.deployment.steps.LiquibaseProcessor$startLiquibase1744275855.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.LiquibaseProcessor$startLiquibase1744275855.deploy(Unknown Source)
	... 7 more
Caused by: liquibase.exception.DatabaseException: liquibase.exception.CommandExecutionException: liquibase.exception.LockException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Error executing SQL UPDATE public.databasechangeloglock SET LOCKED = FALSE, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1: ERROR: relation "public.databasechangeloglock" does not exist
  Position: 8
	at liquibase.Liquibase.dropAll(Liquibase.java:1028)
	at liquibase.Liquibase.dropAll(Liquibase.java:1009)
	at liquibase.Liquibase.dropAll(Liquibase.java:994)
	at io.quarkus.liquibase.runtime.LiquibaseRecorder.doStartActions(LiquibaseRecorder.java:71)
	... 9 more
Caused by: liquibase.exception.CommandExecutionException: liquibase.exception.LockException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Error executing SQL UPDATE public.databasechangeloglock SET LOCKED = FALSE, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1: ERROR: relation "public.databasechangeloglock" does not exist
  Position: 8
	at liquibase.command.CommandScope.execute(CommandScope.java:257)
	at liquibase.Liquibase.dropAll(Liquibase.java:1026)
	... 12 more
Caused by: liquibase.exception.LockException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Error executing SQL UPDATE public.databasechangeloglock SET LOCKED = FALSE, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1: ERROR: relation "public.databasechangeloglock" does not exist
  Position: 8
	at liquibase.lockservice.StandardLockService.releaseLock(StandardLockService.java:407)
	at liquibase.command.core.DropAllCommandStep.run(DropAllCommandStep.java:120)
	at liquibase.command.CommandScope.execute(CommandScope.java:219)
	... 13 more
Caused by: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Error executing SQL UPDATE public.databasechangeloglock SET LOCKED = FALSE, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1: ERROR: relation "public.databasechangeloglock" does not exist
  Position: 8
	at liquibase.executor.jvm.ChangelogJdbcMdcListener.query(ChangelogJdbcMdcListener.java:62)
	at liquibase.lockservice.StandardLockService.releaseLock(StandardLockService.java:372)
	... 15 more
Caused by: liquibase.exception.DatabaseException: Error executing SQL UPDATE public.databasechangeloglock SET LOCKED = FALSE, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1: ERROR: relation "public.databasechangeloglock" does not exist
  Position: 8
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:101)
	at liquibase.executor.jvm.JdbcExecutor.update(JdbcExecutor.java:337)
	at liquibase.executor.jvm.JdbcExecutor.update(JdbcExecutor.java:305)
	at liquibase.lockservice.StandardLockService.lambda$releaseLock$6(StandardLockService.java:372)
	at liquibase.executor.jvm.ChangelogJdbcMdcListener.lambda$query$1(ChangelogJdbcMdcListener.java:55)
	at liquibase.Scope.child(Scope.java:199)
	at liquibase.Scope.child(Scope.java:175)
	at liquibase.executor.jvm.ChangelogJdbcMdcListener.query(ChangelogJdbcMdcListener.java:55)
	... 16 more
Caused by: org.postgresql.util.PSQLException: ERROR: relation "public.databasechangeloglock" does not exist
  Position: 8
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2725)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2412)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:502)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:419)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:341)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:326)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:302)
	at org.postgresql.jdbc.PgStatement.executeUpdate(PgStatement.java:275)
	at io.agroal.pool.wrapper.StatementWrapper.executeUpdate(StatementWrapper.java:120)
	at liquibase.executor.jvm.JdbcExecutor$1UpdateStatementCallback.doInStatement(JdbcExecutor.java:328)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:80)
	... 23 more
```

For H2 the log contains:

```
INFO  [liq.command] (main) Logging exception.
ERROR: Exception Details
ERROR: Exception Primary Class:  JdbcSQLSyntaxErrorException
ERROR: Exception Primary Reason:  Tabelle "DATABASECHANGELOGLOCK" nicht gefunden (diese Datenbank ist leer)
Table "DATABASECHANGELOGLOCK" not found (this database is empty); SQL statement:
UPDATE PUBLIC.DATABASECHANGELOGLOCK SET LOCKED = FALSE, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1 [42104-224]
ERROR: Exception Primary Source:  H2 2.2.224 (2023-09-17)
2024-05-11 17:43:26,697 INFO  [liq.command] (main) Command execution complete
2024-05-11 17:43:26,727 ERROR [io.qua.run.Application] (main) Failed to start application (with profile [prod]):
```

and the exception is:

```
java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
Caused by: java.lang.IllegalStateException: Error starting Liquibase
	at io.quarkus.liquibase.runtime.LiquibaseRecorder.doStartActions(LiquibaseRecorder.java:90)
	at io.quarkus.deployment.steps.LiquibaseProcessor$startLiquibase1744275855.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.LiquibaseProcessor$startLiquibase1744275855.deploy(Unknown Source)
	... 7 more
Caused by: liquibase.exception.DatabaseException: liquibase.exception.CommandExecutionException: liquibase.exception.LockException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Error executing SQL UPDATE PUBLIC.DATABASECHANGELOGLOCK SET LOCKED = FALSE, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1: Tabelle "DATABASECHANGELOGLOCK" nicht gefunden (diese Datenbank ist leer)
Table "DATABASECHANGELOGLOCK" not found (this database is empty); SQL statement:
UPDATE PUBLIC.DATABASECHANGELOGLOCK SET LOCKED = FALSE, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1 [42104-224]
	at liquibase.Liquibase.dropAll(Liquibase.java:1028)
	at liquibase.Liquibase.dropAll(Liquibase.java:1009)
	at liquibase.Liquibase.dropAll(Liquibase.java:994)
	at io.quarkus.liquibase.runtime.LiquibaseRecorder.doStartActions(LiquibaseRecorder.java:71)
	... 9 more
Caused by: liquibase.exception.CommandExecutionException: liquibase.exception.LockException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Error executing SQL UPDATE PUBLIC.DATABASECHANGELOGLOCK SET LOCKED = FALSE, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1: Tabelle "DATABASECHANGELOGLOCK" nicht gefunden (diese Datenbank ist leer)
Table "DATABASECHANGELOGLOCK" not found (this database is empty); SQL statement:
UPDATE PUBLIC.DATABASECHANGELOGLOCK SET LOCKED = FALSE, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1 [42104-224]
	at liquibase.command.CommandScope.execute(CommandScope.java:257)
	at liquibase.Liquibase.dropAll(Liquibase.java:1026)
	... 12 more
Caused by: liquibase.exception.LockException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Error executing SQL UPDATE PUBLIC.DATABASECHANGELOGLOCK SET LOCKED = FALSE, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1: Tabelle "DATABASECHANGELOGLOCK" nicht gefunden (diese Datenbank ist leer)
Table "DATABASECHANGELOGLOCK" not found (this database is empty); SQL statement:
UPDATE PUBLIC.DATABASECHANGELOGLOCK SET LOCKED = FALSE, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1 [42104-224]
	at liquibase.lockservice.StandardLockService.releaseLock(StandardLockService.java:407)
	at liquibase.command.core.DropAllCommandStep.run(DropAllCommandStep.java:120)
	at liquibase.command.CommandScope.execute(CommandScope.java:219)
	... 13 more
Caused by: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Error executing SQL UPDATE PUBLIC.DATABASECHANGELOGLOCK SET LOCKED = FALSE, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1: Tabelle "DATABASECHANGELOGLOCK" nicht gefunden (diese Datenbank ist leer)
Table "DATABASECHANGELOGLOCK" not found (this database is empty); SQL statement:
UPDATE PUBLIC.DATABASECHANGELOGLOCK SET LOCKED = FALSE, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1 [42104-224]
	at liquibase.executor.jvm.ChangelogJdbcMdcListener.query(ChangelogJdbcMdcListener.java:62)
	at liquibase.lockservice.StandardLockService.releaseLock(StandardLockService.java:372)
	... 15 more
Caused by: liquibase.exception.DatabaseException: Error executing SQL UPDATE PUBLIC.DATABASECHANGELOGLOCK SET LOCKED = FALSE, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1: Tabelle "DATABASECHANGELOGLOCK" nicht gefunden (diese Datenbank ist leer)
Table "DATABASECHANGELOGLOCK" not found (this database is empty); SQL statement:
UPDATE PUBLIC.DATABASECHANGELOGLOCK SET LOCKED = FALSE, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1 [42104-224]
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:101)
	at liquibase.executor.jvm.JdbcExecutor.update(JdbcExecutor.java:337)
	at liquibase.executor.jvm.JdbcExecutor.update(JdbcExecutor.java:305)
	at liquibase.lockservice.StandardLockService.lambda$releaseLock$6(StandardLockService.java:372)
	at liquibase.executor.jvm.ChangelogJdbcMdcListener.lambda$query$1(ChangelogJdbcMdcListener.java:55)
	at liquibase.Scope.child(Scope.java:199)
	at liquibase.Scope.child(Scope.java:175)
	at liquibase.executor.jvm.ChangelogJdbcMdcListener.query(ChangelogJdbcMdcListener.java:55)
	... 16 more
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabelle "DATABASECHANGELOGLOCK" nicht gefunden (diese Datenbank ist leer)
Table "DATABASECHANGELOGLOCK" not found (this database is empty); SQL statement:
UPDATE PUBLIC.DATABASECHANGELOGLOCK SET LOCKED = FALSE, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1 [42104-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:514)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.command.Parser.getTableOrViewNotFoundDbException(Parser.java:8051)
	at org.h2.command.Parser.getTableOrViewNotFoundDbException(Parser.java:8045)
	at org.h2.command.Parser.getTableOrViewNotFoundDbException(Parser.java:8029)
	at org.h2.command.Parser.readTableOrView(Parser.java:8024)
	at org.h2.command.Parser.readTableOrView(Parser.java:7990)
	at org.h2.command.Parser.readSimpleTableFilter(Parser.java:1094)
	at org.h2.command.Parser.parseUpdate(Parser.java:1018)
	at org.h2.command.Parser.parsePrepared(Parser.java:765)
	at org.h2.command.Parser.parse(Parser.java:592)
	at org.h2.command.Parser.parse(Parser.java:564)
	at org.h2.command.Parser.prepareCommand(Parser.java:483)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:639)
	at org.h2.server.TcpServerThread.process(TcpServerThread.java:289)
	at org.h2.server.TcpServerThread.run(TcpServerThread.java:191)
	at java.base/java.lang.Thread.run(Thread.java:1570)

	at org.h2.engine.SessionRemote.readException(SessionRemote.java:650)
	at org.h2.engine.SessionRemote.done(SessionRemote.java:619)
	at org.h2.command.CommandRemote.prepare(CommandRemote.java:78)
	at org.h2.command.CommandRemote.<init>(CommandRemote.java:50)
	at org.h2.engine.SessionRemote.prepareCommand(SessionRemote.java:487)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1166)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:190)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:147)
	at io.agroal.pool.wrapper.StatementWrapper.executeUpdate(StatementWrapper.java:120)
	at liquibase.executor.jvm.JdbcExecutor$1UpdateStatementCallback.doInStatement(JdbcExecutor.java:328)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:80)
	... 23 more
```

### Expected behavior

The DB is migrated and the app successfully started.

### Actual behavior

An Exception is thrown, the DB isn't migrated and the application exits.

### How to Reproduce?

To reproduce the error with Postgresql:

1. Use the `liquibase-quickstart` from the `quarkus-quickstarts` repo.
2. Change `<artifactId>quarkus-jdbc-h2</artifactId>` to `<artifactId>quarkus-jdbc-postgresql</artifactId>` in `pom.xml`.
3. Change the data source to `%prod.quarkus.datasource.db-kind=postgresql` and the url to `%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/test` in `application.properties`.
4. Run a DB-instance e.g.: ` docker run -d --rm --name=test-db -p 0.0.0.0:5432:5432 -e POSTGRES_USER=sa -e POSTGRES_PASSWORD=sa -e POSTGRES_DB=test postgres:16.2`
5. Compile the app: `mvn clean package -Dnative -DskipTests`.
6. Run: `./target/liquibase-quickstart-1.0.0-SNAPSHOT-runner`.

You can use similar steps to reproduce the error with H2.

### Output of `uname -a` or `ver`

Darwin 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:11:05 PDT 2024; root:xnu-10063.101.17~1/RELEASE_X86_64 x86_64

### Output of `java -version`

java 21.0.3 2024-04-16 LTS Java(TM) SE Runtime Environment Oracle GraalVM 21.0.3+7.1 (build 21.0.3+7-LTS-jvmci-23.1-b37) Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 21.0.3+7.1 (build 21.0.3+7-LTS-jvmci-23.1-b37, mixed mode, sharing)

### Mandrel or GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

3.10.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)

### Additional information

_No response_

### LINKED ISSUE #40575: When Using Liquibase in Native Mode a ServiceConfigurationError is Logged
### Describe the bug

When Using Liquibase in Native Mode a ServiceConfigurationError is Logged.
This happens at least with Postgresql and H2.
The issue occurs at least since Quarkus 3.8.2
The error occurs for a local as well as an in-container build.
There seem to be no negative consequences of this error, besides polluting the application log.

### Expected behavior

No Error is logged.

### Actual behavior

At Quarkus start the following error is logged:

```
INFO  [liq.servicelocator] (main) Cannot load service: java.util.ServiceConfigurationError: liquibase.command.CommandStep: Provider liquibase.command.core.StartH2CommandStep not found
	at java.base@21.0.3/java.util.ServiceLoader.fail(ServiceLoader.java:593)
	at java.base@21.0.3/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1219)
	at java.base@21.0.3/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1228)
	at java.base@21.0.3/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
	at java.base@21.0.3/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
	at java.base@21.0.3/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
	at liquibase.servicelocator.StandardServiceLocator.findInstances(StandardServiceLocator.java:22)
	at liquibase.command.CommandFactory.findAllInstances(CommandFactory.java:244)
	at liquibase.command.CommandFactory.computePipelineForCommandDefinition(CommandFactory.java:71)
	at liquibase.command.CommandFactory.getCommandDefinition(CommandFactory.java:50)
	at liquibase.command.CommandScope.<init>(CommandScope.java:64)
	at liquibase.Liquibase.lambda$validate$25(Liquibase.java:1365)
	at liquibase.Scope.lambda$child$0(Scope.java:190)
	at liquibase.Scope.child(Scope.java:199)
	at liquibase.Scopefor child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:168)
	at liquibase.Liquibase.runInScope(Liquibase.java:1436)
	at liquibase.Liquibase.validate(Liquibase.java:1364)
	at io.quarkus.liquibase.runtime.LiquibaseRecorder.doStartActions(LiquibaseRecorder.java:79)
	at io.quarkus.deployment.steps.LiquibaseProcessor$startLiquibase1744275855.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.LiquibaseProcessor$startLiquibase1744275855.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
```

The error is exactly the same for Postgresql and H2.
It probably occurs for other databases as well.

### How to Reproduce?

1. Use the `liquibase-quickstart` from `quarkus-quickstarters`.
2. Run a H2 instance with **remote database creation** enabled.
3. Compile and run the app in native mode.

### Output of `uname -a` or `ver`

Darwin 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:11:05 PDT 2024; root:xnu-10063.101.17~1/RELEASE_X86_64 x86_64

### Output of `java -version`

java 21.0.3 2024-04-16 LTS Java(TM) SE Runtime Environment Oracle GraalVM 21.0.3+7.1 (build 21.0.3+7-LTS-jvmci-23.1-b37) Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 21.0.3+7.1 (build 21.0.3+7-LTS-jvmci-23.1-b37, mixed mode, sharing)

### Mandrel or GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

3.10.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)

### Additional information

_No response_

### LINKED ISSUE #42143: Native Image run issue with XML Changelog quarkus-liquibase
I'm facing an issue with quarkus-liquibase, particularly with the XML Changelog.
I noticed an issue on GitHub, which can be found at [https://github.com/quarkusio/quarkus/issues/27437](http://url/), opened in 2022.

**Configuration:**

```
quarkus.liquibase.enabled=true
quarkus.liquibase.migrate-at-start=true
quarkus.liquibase.change-log=db/postgres/changelog-master.yml
```
files : [https://github.com/RafiIsaharov/esb-infra/tree/main/src/main/resources/db/postgres](http://url/)

Snapshot of changelog-master.yml:

```
databaseChangeLog:
  - include:
      file: db/postgres/changelog.001.sql
  - include:
      file: db/postgres/changelog.002.xml
  - include:
      file: db/postgres/changelog.003.sql
  - include:
      file: db/postgres/changelog.004.sql

```

Snapshot of  changelog.002.xml:
```
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog https://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.3.xsd">

    <!--changeSet id="1" author="rafi.isaharov">
        <sql>
            ALTER TABLE routes ADD COLUMN timestamp TIMESTAMP;
        </sql>
    </changeSet-->

    <!--changeSet id="2" author="rafi.isaharov">
        <sql>
            ALTER TABLE routes ALTER COLUMN timestamp SET DEFAULT NOW();
        </sql>
    </changeSet-->

    <changeSet id="3" author="rafi.isaharov">
        <sql splitStatements="false">
            <![CDATA[
            -- Create a function to update timestamp on every update
            CREATE OR REPLACE FUNCTION update_timestamp()
            RETURNS TRIGGER AS $$
            BEGIN
                NEW.timestamp = NOW();
            RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            ]]>
        </sql>
    </changeSet>

    <changeSet id="4" author="rafi.isaharov">
        <sql splitStatements="false">
            <![CDATA[
            -- Create a trigger to execute update_timestamp function on every update
            CREATE TRIGGER update_routes_timestamp
                BEFORE UPDATE ON routes
                FOR EACH ROW
                EXECUTE FUNCTION update_timestamp();
            ]]>
        </sql>
    </changeSet>
```

Error Trace: 
[exception_liquibase_using_changelog_as_xml.txt](https://github.com/user-attachments/files/16378315/exception_liquibase_using_changelog_as_xml.txt)

**Observations:**

- This issue occurs only in the native image, not when running the runnable jar.

- The application fails to start with this error.

- Quarkus version: 3.12.3

- Java version: 17.0.11+7-LTS, vendor version: Oracle GraalVM 17.0.11+7.1

- Apache Maven  3.9.6

**Current Workaround:** 
To overcome the issue with the XML changelog file, I am converting it into an equivalent SQL file format.

**Reproduce the issue:**
I've uploaded the code to my GitHub repository, which includes the docker-compose.yaml file for the Postgres database. 
You can download and replicate it from the main branch [https://github.com/RafiIsaharov/esb-infra.git](http://url/).

### PR DESCRIPTION
**Pull request by gcw-it**
Fixes #40574 
Fixes #40575 
Fixes #42143

It seems, that after upgrading the `liquibase-core` version, the additional resource files that were added, weren't incorporated in the build.

To avoid this problem for future updates, this patch loads the following `iquibase-core` resources automatically:
- all `.property` files in the root folder
- all `.xsd` XML Schema Definitions from the `www.liquibase.org/xml/ns/dbchangelog` folder
- all service definitions in `META-INF/services`

The i18n resources were already automatically loaded before.

If in a future liquibase version a service is added, that needs initialisation at runtime, this information needs to be manually added to the code.
Manual intervention is also necessary, should any other resource types or locations be added to liquibase.

### CODE REVIEW

**Comment by gsmet** [comment]
Thanks! It's definitely a good idea as we have been struggling with it a lot. I'll have a look soon.

File: extensions/liquibase/deployment/src/main/java/io/quarkus/liquibase/deployment/LiquibaseProcessor.java [hunk 1]
```diff
@@ -278,6 +227,106 @@ private void consumeService(Class<?> serviceClass, BiConsumer<Class<?>, Collecti
...
+
+            try (var ignored = FileSystems.newFileSystem(jarUrl, Collections.EMPTY_MAP)) {
+                var rootPath = Paths.get(jarUrl);
+                loadLiquibaseServiceProviderConfig(rootPath, services, reflective, runtimeInitialized);
+                loadLiquibaseRootProperties(rootPath, resource);
+                loadLiquibaseXsdResources(rootPath, resource);
+            }
+        } catch (URISyntaxException | IOException ex) {
+            throw new IllegalStateException(ex);
+        }
```
Comment (gsmet) [inline extensions/liquibase/deployment/src/main/java/io/quarkus/liquibase/deployment/LiquibaseProcessor.java:252]: I'm not entirely sure about the implementation here.

I think, maybe using `CurateOutcomeBuildItem` to get the `ApplicationModel` would be better. Then you could get a `ResolvedDependency` from `getDependencies` that match Liquibase and use `getContentTree(PathFilter)`.

File: extensions/liquibase/deployment/src/main/java/io/quarkus/liquibase/deployment/LiquibaseProcessor.java [hunk 2]
```diff
@@ -278,6 +227,106 @@ private void consumeService(Class<?> serviceClass, BiConsumer<Class<?>, Collecti
...
+            BuildProducer<ReflectiveClassBuildItem> reflective,
+            BuildProducer<RuntimeInitializedClassBuildItem> runtimeInitialized) throws IOException {
+
+        List<Class<?>> runtimeInitializationServices = List.of(
+                liquibase.configuration.ConfigurationValueProvider.class);
+        Files.list(path.resolve("META-INF/services"))
+                .map(Path::getFileName)
+                .map(Path::toString)
+                .map(this::classFromString)
+                .filter(not(runtimeInitializationServices::contains))
```
Comment (gsmet) [inline extensions/liquibase/deployment/src/main/java/io/quarkus/liquibase/deployment/LiquibaseProcessor.java:267]: I think I would avoid transforming this to a class then a String again. You can make `runtimeInitializationServices` a set of strings and use `liquibase.configuration.ConfigurationValueProvider.class`.

File: extensions/liquibase/deployment/src/main/java/io/quarkus/liquibase/deployment/LiquibaseProcessor.java [hunk 3]
```diff
@@ -278,6 +227,106 @@ private void consumeService(Class<?> serviceClass, BiConsumer<Class<?>, Collecti
...
+        }
+    }
+
+    private void loadLiquibaseServiceProviderConfig(
+            Path path,
+            BuildProducer<ServiceProviderBuildItem> services,
+            BuildProducer<ReflectiveClassBuildItem> reflective,
+            BuildProducer<RuntimeInitializedClassBuildItem> runtimeInitialized) throws IOException {
+
+        List<Class<?>> runtimeInitializationServices = List.of(
```
Comment (gsmet) [inline extensions/liquibase/deployment/src/main/java/io/quarkus/liquibase/deployment/LiquibaseProcessor.java:261]: For now it doesn't make a lot of difference as you only have one item but let's make it a `HashSet` in case it grows in the future.

**Review by gsmet — COMMENTED** [review]
I added a few suggestions. Can you give it a try. I think it would improve the code but I haven't tried so please push back if you don't see it working.

Thanks!

File: extensions/liquibase/deployment/src/main/java/io/quarkus/liquibase/deployment/LiquibaseProcessor.java (hunk 1 above)
Comment (gcw-it) [reply extensions/liquibase/deployment/src/main/java/io/quarkus/liquibase/deployment/LiquibaseProcessor.java]: Thanks for the pointer. Done.

File: extensions/liquibase/deployment/src/main/java/io/quarkus/liquibase/deployment/LiquibaseProcessor.java (hunk 2 above)
Comment (gcw-it) [reply extensions/liquibase/deployment/src/main/java/io/quarkus/liquibase/deployment/LiquibaseProcessor.java]: Done.
I realised the same happened for the static initialisation. I changed it there, too.

File: extensions/liquibase/deployment/src/main/java/io/quarkus/liquibase/deployment/LiquibaseProcessor.java (hunk 3 above)
Comment (gcw-it) [reply extensions/liquibase/deployment/src/main/java/io/quarkus/liquibase/deployment/LiquibaseProcessor.java]: Done.

**Comment by gsmet** [comment]
@gcw-it I sent you an email on the email you use to commit (hopefully you read it!), let's try to figure out things there so that your setup works.

File: extensions/liquibase/deployment/src/main/java/io/quarkus/liquibase/deployment/LiquibaseProcessor.java [hunk 4]
```diff
@@ -278,6 +230,97 @@ private void consumeService(Class<?> serviceClass, BiConsumer<Class<?>, Collecti
...
+        loadLiquibaseRootProperties(tree, resource);
+        loadLiquibaseXsdResources(tree, resource);
+        loadLiquibaseServiceProviderConfig(tree, services, reflective, runtimeInitialized);
+    }
+
+    private boolean isLiquibaseDependency(ResolvedDependency dependency) {
+        return dependency.getResolvedPaths().stream()
+                .map(Path::getFileName)
+                .map(Path::toString)
+                .anyMatch(s -> s.contains(LIQUIBASE_ARTIFACT_NAME));
```
Comment (aloubyansky) [inline extensions/liquibase/deployment/src/main/java/io/quarkus/liquibase/deployment/LiquibaseProcessor.java:256]: Wouldn't `dependency.getArtifactId().equals(LIQUIBASE_ARTIFACT_NAME)` work here?

File: extensions/liquibase/deployment/src/main/java/io/quarkus/liquibase/deployment/LiquibaseProcessor.java [hunk 5]
```diff
@@ -278,6 +230,97 @@ private void consumeService(Class<?> serviceClass, BiConsumer<Class<?>, Collecti
...
+    }
+
+    private List<String> getResourceNames(PathTree pathTree, String basePath, String fileExtension, boolean stripPath) {
+        return pathTree.apply(basePath, visit -> {
```
Comment (aloubyansky) [inline extensions/liquibase/deployment/src/main/java/io/quarkus/liquibase/deployment/LiquibaseProcessor.java:260]: It looks like `pathTree.walk(visitor)` would be more appropriate here

Comment (aloubyansky) [reply extensions/liquibase/deployment/src/main/java/io/quarkus/liquibase/deployment/LiquibaseProcessor.java:260]: Ah, sorry, you want the direct children here.

File: extensions/liquibase/deployment/src/main/java/io/quarkus/liquibase/deployment/LiquibaseProcessor.java (hunk 4 above)
Comment (gcw-it) [reply extensions/liquibase/deployment/src/main/java/io/quarkus/liquibase/deployment/LiquibaseProcessor.java:256]: You're right, somehow I managed to overlook that possibility.
I will change this accordingly.

Comment (gsmet) [reply extensions/liquibase/deployment/src/main/java/io/quarkus/liquibase/deployment/LiquibaseProcessor.java:256]: Please do that and also test the groupId. Typically you could have someone having a `my-groupid:liquibase-core` in their app and you don't want to catch that.

Also I recommend using the `CONSTANT.equals(variable)` pattern instead of `variable.equals(CONSTANT)`. In this case, the variables won't be null so it won't change anything but it's a good practice to avoid NPEs. Once you have this habit, you're a lot safer.

File: extensions/liquibase/deployment/src/main/java/io/quarkus/liquibase/deployment/LiquibaseProcessor.java [hunk 6]
```diff
@@ -178,82 +186,26 @@ void nativeImageConfiguration(
...
-                    services.produce(
-                            new ServiceProviderBuildItem(serviceClass.getName(), implementations.toArray(new String[0])));
-                    reflective.produce(ReflectiveClassBuildItem.builder(implementations.toArray(new String[0]))
-                            .constructors().methods().build());
-                }));
-
         // Register Precondition services, and the implementation class for reflection while also registering fields for reflection
-        consumeService(liquibase.precondition.Precondition.class, (serviceClass, implementations) -> {
-            services.produce(new ServiceProviderBuildItem(serviceClass.getName(), implementations.toArray(new String[0])));
+        consumeService("liquibase.precondition.Precondition", (serviceClass, implementations) -> {
```
Comment (gsmet) [inline extensions/liquibase/deployment/src/main/java/io/quarkus/liquibase/deployment/LiquibaseProcessor.java:190]: I suggested to use `liquibase.precondition.Precondition.class.getName()` (and same for the others, for instance in `RUNTIME_INITIALIZATION_SERVICES`). Keep in mind that we don't manage the Liquibase development so better get a compilation warning if they change something in this area.

It's a bit more nuanced than that because we sometimes use the strings because either the classes are not accessible or because we want to avoid loading them if we can, but in this very case, I think it's better to use `.class.getName()`.

**Review by gsmet — COMMENTED** [review]
I think we're nearly there. I added a few additional comments/advices.

File: extensions/liquibase/deployment/src/main/java/io/quarkus/liquibase/deployment/LiquibaseProcessor.java (hunk 6 above)
Comment (gcw-it) [reply extensions/liquibase/deployment/src/main/java/io/quarkus/liquibase/deployment/LiquibaseProcessor.java:190]: I understand your reasoning here, but doesn't this contradict, what you wrote above?

> I think I would avoid transforming this to a class then a String again. You can make `runtimeInitializationServices` a set of strings and use `liquibase.configuration.ConfigurationValueProvider.class`.

I'm fine with restoring this to the class-based version, but I'd like to avoid any misunderstanding.

Comment (gcw-it) [reply extensions/liquibase/deployment/src/main/java/io/quarkus/liquibase/deployment/LiquibaseProcessor.java]: OK, i see. I will change the code accordingly.

**Comment by gcw-it** [comment]
I enabled `quarkus.liquibase.clean-at-start` for the liquibase extension integration test.
With `clean-at-start=true` the IT fails before integrating this patch and succeeds afterwards.

**Comment by gcw-it** [comment]
I realised, that my code for the runtime initialisation of the services is incorrect. It only registers the service type, and not the corresponding implementations. Correcting this leads unfortunately to another problem.

The reason why I registered the `ConfigurationValueProvider` service at runtime was a GraalVM build time compilation error for the `EnvironmentValueProvider` service implementation:
`Error: Unsupported field liquibase.configuration.core.EnvironmentValueProvider.environment is reachable` (see the detailed error message below).
This happens with GraalVM 21.0.4 as well as 22.0.2.

When I register the unproblematic service implementations correctly, and `ConfigurationValueProvider` at runtime, `ConfigurationValueProvider` will be optimised away during compilation, which in consequence leads to an exception at runtime:
`Cannot load service: java.util.ServiceConfigurationError: liquibase.configuration.ConfigurationValueProvider: Provider liquibase.configuration.core.EnvironmentValueProvider not found`.

Registering `ConfigurationValueProvider` additionally for reflection, that it won't get removed during compilation leads again to the 'Unsupported field' error. 

I think, the best course of action right now is, to not register the `ConfigurationValueProvider` services at all, since Quarkus has its own method for configuring Liquibase. Additionally the service wasn't registered in the previous version of the code, to no apparent adverse effect.

```
Error encountered while parsing com.oracle.svm.core.code.FactoryMethodHolder.EnvironmentValueProvider_constructor_f0afbab60625ae84e3a446aaf418c470e965b9de(generated:0)
Parsing context:
   at static root method.(Unknown Source)

Detailed message:

com.oracle.svm.core.util.UserError$UserException: Unsupported field liquibase.configuration.core.EnvironmentValueProvider.environment is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Error encountered while parsing com.oracle.svm.core.code.FactoryMethodHolder.EnvironmentValueProvider_constructor_f0afbab60625ae84e3a446aaf418c470e965b9de(generated:0)
Parsing context:
   at static root method.(Unknown Source)

Detailed message:

	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:97)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:248)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:833)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:571)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:537)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:526)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:701)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:140)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:95)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Unsupported field liquibase.configuration.core.EnvironmentValueProvider.environment is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Error encountered while parsing com.oracle.svm.core.code.FactoryMethodHolder.EnvironmentValueProvider_constructor_f0afbab60625ae84e3a446aaf418c470e965b9de(generated:0)
Parsing context:
   at static root method.(Unknown Source)

Detailed message:

	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:126)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:828)
	... 6 more
Caused by: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported field liquibase.configuration.core.EnvironmentValueProvider.environment is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.lookup(AnnotationSubstitutionProcessor.java:185)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:135)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:359)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.infrastructure.AnalysisConstantPool.lookupField(AnalysisConstantPool.java:42)
	at jdk.graal.compiler/jdk.graal.compiler.java.BytecodeParser.lookupField(BytecodeParser.java:4395)
	at jdk.graal.compiler/jdk.graal.compiler.java.BytecodeParser.genPutField(BytecodeParser.java:4924)
	at jdk.graal.compiler/jdk.graal.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5465)
	at jdk.graal.compiler/jdk.graal.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3473)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.iterateBytecodesForBlock(SharedGraphBuilderPhase.java:790)
	at jdk.graal.compiler/jdk.graal.compiler.java.BytecodeParser.handleBytecodeBlock(BytecodeParser.java:3433)
	at jdk.graal.compiler/jdk.graal.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3275)
	at jdk.graal.compiler/jdk.graal.compiler.java.BytecodeParser.build(BytecodeParser.java:1136)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.build(SharedGraphBuilderPhase.java:202)
	at jdk.graal.compiler/jdk.graal.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:1028)
	at jdk.graal.compiler/jdk.graal.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:102)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase.run(SharedGraphBuilderPhase.java:154)
	at jdk.graal.compiler/jdk.graal.compiler.phases.Phase.run(Phase.java:49)
	at jdk.graal.compiler/jdk.graal.compiler.phases.BasePhase.apply(BasePhase.java:435)
	at jdk.graal.compiler/jdk.graal.compiler.phases.Phase.apply(Phase.java:42)
	at jdk.graal.compiler/jdk.graal.compiler.phases.Phase.apply(Phase.java:38)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.AnalysisParsedGraph.parseBytecode(AnalysisParsedGraph.java:144)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisMethod.parseGraph(AnalysisMethod.java:888)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisMethod.ensureGraphParsedHelper(AnalysisMethod.java:853)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisMethod.ensureGraphParsed(AnalysisMethod.java:836)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.phases.InlineBeforeAnalysisGraphDecoder.lookupEncodedGraph(InlineBeforeAnalysisGraphDecoder.java:198)
	at jdk.graal.compiler/jdk.graal.compiler.replacements.PEGraphDecoder.doInline(PEGraphDecoder.java:1215)
	at jdk.graal.compiler/jdk.graal.compiler.replacements.PEGraphDecoder.tryInline(PEGraphDecoder.java:1198)
	at jdk.graal.compiler/jdk.graal.compiler.replacements.PEGraphDecoder.trySimplifyInvoke(PEGraphDecoder.java:1053)
	at jdk.graal.compiler/jdk.graal.compiler.replacements.PEGraphDecoder.handleInvokeWithCallTarget(PEGraphDecoder.java:1005)
	at jdk.graal.compiler/jdk.graal.compiler.replacements.PEGraphDecoder.handleInvoke(PEGraphDecoder.java:991)
	at jdk.graal.compiler/jdk.graal.compiler.nodes.GraphDecoder.processNextNode(GraphDecoder.java:930)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.phases.InlineBeforeAnalysisGraphDecoder.processNextNode(InlineBeforeAnalysisGraphDecoder.java:377)
	at jdk.graal.compiler/jdk.graal.compiler.nodes.GraphDecoder.decode(GraphDecoder.java:658)
	at jdk.graal.compiler/jdk.graal.compiler.replacements.PEGraphDecoder.decode(PEGraphDecoder.java:895)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.phases.InlineBeforeAnalysis.decodeGraph(InlineBeforeAnalysis.java:73)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:198)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:608)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.createFlowsGraph(MethodTypeFlow.java:167)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureFlowsGraphCreated(MethodTypeFlow.java:152)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.getOrCreateMethodFlowsGraphInfo(MethodTypeFlow.java:110)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.typestate.DefaultAnalysisPolicy.staticRootMethodGraph(DefaultAnalysisPolicy.java:209)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.PointsToAnalysis.lambda$addRootMethod$0(PointsToAnalysis.java:337)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.AbstractAnalysisEngine$1.run(AbstractAnalysisEngine.java:333)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:169)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:154)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.compute(ForkJoinTask.java:1726)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.compute(ForkJoinTask.java:1717)
	at java.base/java.util.concurrent.ForkJoinTask$InterruptibleTask.exec(ForkJoinTask.java:1641)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1489)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2071)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2033)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
```

**Comment by gsmet** [comment]
I agree we should ideally be in line with what was done before.

**Comment by gcw-it** [comment]
If everything is in order, I will squash the commits.
I kept them separate for now, to make it possible to monitor the changes.

**Comment by gcw-it** [comment]
After digging a bit deeper into the codebase, I found the culprit for the strange GraalVM build time exception.

The runtime package of the liquibase extension uses a GraalVM substitution (`liquibase.runtime.graal.SubstituteEnvironmentValueProvider`), that fixes an issue on Windows ([#22449](https://github.com/quarkusio/quarkus/issues/33030)).

This substitution deletes a field, that is later referenced by the default constructor, hence the `DeletedElementException`.

Substituting the constructor leads only to a temporary relief. The build is now successful, but at runtime a `NullPointerException` is thrown. It appears that the substitution of the constructor also removes/prevents the initialisation of some fields of the parent class `AbstractMapConfigurationValueProvider`. In this case the `ReentrantLock knownValuesLock` is null, which causes the `NullPointerException`. Explicitly calling `super()` from the substituted constructor makes no difference.

We could limit the application of the substitution to the Windows platform, but on my Windows machine (Windows 10 22H2 19045 4651, GraalVM 21.02+13.1), the error `DeletedElementException` occurs as well. 
On the other hand, after removing the `SubstituteEnvironmentValueProvider` the build succeeds. 

Maybe the upgrade to liquibase 4.27.0 helped, or newer GraalVM versions remediated problem #22449, but it seems, the patch isn't necessary anymore. I'm not entirely sure if the patch was necessary at all in the latest Quarkus versions, because the targeted class wasn't even included in the native image.

Ideally we could remove the `SubstituteEnvironmentValueProvider `, because GraalVM substitutions are inherently brittle.

Would the CI-Pipeline pick up, if we introduce a regression by removing the patch?

File: extensions/liquibase/deployment/src/main/java/io/quarkus/liquibase/deployment/LiquibaseProcessor.java [hunk 7]
```diff
@@ -105,10 +113,11 @@ IndexDependencyBuildItem indexLiquibase() {
     @BuildStep(onlyIf = NativeOrNativeSourcesBuild.class)
     @Record(STATIC_INIT)
     void nativeImageConfiguration(
-            LiquibaseRecorder recorder,
+            LiquibaseRecorder ignored,
```
Comment (gsmet) [inline extensions/liquibase/deployment/src/main/java/io/quarkus/liquibase/deployment/LiquibaseProcessor.java:116]: I think you can drop this parameter and the `@Record` annotation if we don't need them.

**Review by gsmet — COMMENTED** [review]
I think it's worth trying to drop the substitution and see how it goes.

One thing we need to do is to check if the quickstarts work: https://github.com/quarkusio/quarkus-quickstarts . You need to get the `develop` branch so that the quickstart points to 999-SNAPSHOT and run the specific liquibase quickstart with `-Dnative`. It has been failing for a while and I wonder if your patch would fix it: https://github.com/quarkusio/quarkus-quickstarts/actions/runs/10087017755/job/27890486199 .

If not, it's probably worth investigating. It won't block this PR though as I really want it in soon.

As for testing your patch on Windows, you could add the liquibase IT there: https://github.com/quarkusio/quarkus/blob/main/.github/native-tests.json#L135-L140 and it would then be run on Windows too (we don't run all the native tests on Windows).

**Comment by gcw-it** [comment]
> One thing we need to do is to check if the quickstarts work

Sorry, that I wasn't really clear. I already built the `liquibase-quickstart` successfully on windows, without the substitution. I just wasn't sure, if there could be other problematic areas.

I will remove the `recorder`, and add the liquibase IT.

Would you prefer the commits being squashed, or separate for now?

**Comment by gsmet** [comment]
I think you can add two more semantic commits for these two changes as they are not entirely related to your changes.

**Comment by gsmet** [comment]
This thread might also be of interest to you: https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Native.20Image.20Issue.20with.20quarkus-liquibase

**Comment by gcw-it** [comment]
I wonder, if in a next step it would be a good idea, to extract the functionality, to automatically find the resource paths in a dependency, to a utility class.

At least the liquibase-mongodb extension seems to suffer from a similar problem as the liquibase extension and could benefit from it. Maybe there are other extensions as well?

**Comment by gsmet** [comment]
Yeah so I can see how the Liquibase MongoDB extension would suffer from the same issue and probably needs the same fix.

I wouldn't generalize things too much though and use this approach when it's not risky at all (typically, versioned XSD resources makes perfect sense, blinding adding all services might not be what we want to do).

Let's get this in first though.

**Comment by gcw-it** [comment]
I agree with you, that we should concentrate on this fix first.

My proposal wasn't intended to be included in this PR, but further down the road

I also don't want to automate registering resources for a native built, that should remain the prerogative of the extension.
What a utility class could offer, is that given dependency coordinates and a base path, it returns a list of available resource paths at the given location, to be included in the native image at the extensions discretion.

This would simply extract some common functionality to avoid code duplication.

**Comment by gsmet** [comment]
Yes, it makes perfect sense.

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
And merged, thanks a lot for this fix.
