### PR TITLE
Remove Jackson from quarkus-analytics-common module

### LINKED ISSUE #52242: Build failure after upgrading to Quarkus 3.31.0 or 3.31.1
### Describe the bug

After upgrading Quarkus from 3.31.0.CR1 to 3.31.0 (Final), the Maven build fails during OpenAPI code generation with a VerifyError related to Jackson classes.

This issue did not occur with 3.31.0.CR1.

The same project builds successfully with:

Quarkus 3.31.0.CR1
Same JDK
Same OpenAPI Generator plugin version
The failure appears only after moving to Quarkus 3.31.0 / 3.31.1

### Expected behavior

Build should succeed and OpenAPI sources should be generated, as with Quarkus 3.31.0.CR1.

### Actual behavior

Build fails with VerifyError during plugin execution before code generation completes.

The failure happens during execution of the OpenAPI Generator Maven plugin: org.openapitools:openapi-generator-maven-plugin:7.18.0:generate

java.lang.VerifyError: Bad type on operand stack

Location:
  io/swagger/v3/parser/ObjectMapperFactory.create(...)
Reason:
  Type 'com/fasterxml/jackson/datatype/jsr310/JavaTimeModule'
  is not assignable to 'com/fasterxml/jackson/databind/Module'

Execution v1 of goal org.openapitools:openapi-generator-maven-plugin:7.18.0:generate failed:
An API incompatibility was encountered...
realm = plugin>org.openapitools:openapi-generator-maven-plugin:7.18.0
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy

Notably, the plugin classpath contains mixed Jackson versions:

- jackson-databind: 2.18.2
- jackson-annotations: 2.18.2
- jackson-core: 2.18.2
- BUT jackson-datatype-jsr310: 2.19.2

This mismatch results in bytecode verification failing when JavaTimeModule is treated as a Module.

After upgrading to Quarkus 3.31.0, a recent commit in the Quarkus Maven tooling now exports 
Jackson datatype packages (JSR-310, JDK8) into the Maven plugin extension classloader 
(see commit 9df90518be133aae54bb8975a0c86449a7611932). :contentReference[oaicite:1]{index=1}

This causes Jackson classes to be mixed between the Quarkus tooling classloader and 
the OpenAPI Generator Maven plugin’s classloader, resulting in:

java.lang.VerifyError: Bad type on operand stack
… JavaTimeModule is not assignable to com.fasterxml.jackson.databind.Module
during openapi-generator-maven-plugin execution.

This appears to be caused by the tooling exporting Jackson modules into the plugin classloader, 
leading to incompatible Jackson versions being resolved at build time.

### How to Reproduce?

`quarkus-openapi-verifyerror-reproducer.zip` unzip and run:

```
mvn clean generate-sources
```
Then change the Quarkus version in pom.xml to 3.31.0.CR1 to verify the build succeeds there.

### Output of `uname -a` or `ver`

fedora 43

### Output of `java -version`

openjdk version "25.0.2" 2026-01-20 LTS

### Quarkus version or git rev

3.31.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.12

### Additional information

[build-stacktrace.log](https://github.com/user-attachments/files/24919403/build-stacktrace.log)

[quarkus-openapi-verifyerror-reproducer.zip](https://github.com/user-attachments/files/24919564/quarkus-openapi-verifyerror-reproducer.zip)

### PR DESCRIPTION
**Pull request by geoand**
Originally mentioned in https://github.com/quarkusio/quarkus/pull/52016#issue-3817877535

Fixes #52242

### CODE REVIEW

**Comment by geoand** [comment]
@brunobat @gsmet how would we test this?

**Comment by gsmet** [comment]
That would be a question for Bruno. But I think adding a breakpoint in the REST Client to check the JSON output is similar is probably fine.

We especially need to have the dates in the exact same format.

**Comment by geoand** [comment]
Right, those are the kinds of subtleties I'm worried about,  especially since I don't know what the test coverage is

**Comment by brunobat** [comment]
This concerns me because we need to make sure the output is understood by Segment. We cannot merge before this can be tested in the dev account. 
How urgent is this?

**Comment by geoand** [comment]
Not urgent AFAIK, but @gsmet would know better. 

What we could do is setup a proxy or something and make sure the data is the same

**Comment by brunobat** [comment]
Probably no need. We output what we upload to a `build-metrics.json` file.
We can collect a few and compare them.

**Comment by geoand** [comment]
👌

**Comment by geoand** [comment]
The two files seem structurally identical to me:

[build-metrics-new.json](https://github.com/user-attachments/files/24663177/build-metrics-new.json)
[build-metrics-orig.json](https://github.com/user-attachments/files/24663179/build-metrics-orig.json)

FWIW, Gemini agrees

**Comment by brunobat** [comment]
Sorry, it's not that file, it's inside target. It's the `build-analytics-event.json` and you will only see it in the Quarkus apps.

**Comment by geoand** [comment]
I belive that's what I copied, no?

**Comment by geoand** [comment]
But I'll try again later in any case

**Comment by brunobat** [comment]
No, I originally misled you. That's the file with the build metrics... timings for each build item

**Comment by gsmet** [comment]
I think it would be nice to add a test with the expected output and what we serialize so that we are sure we don't break it and we know about the format.

Not sure how practical it will be though.

**Comment by brunobat** [comment]
We would need to re-hydrate the DTO and perform the comparisons that way, otherwise it's hard because of the field ordering in the JSON file.

**Comment by geoand** [comment]
> Sorry, it's not that file, it's inside target. It's the `build-analytics-event.json` and you will only see it in the Quarkus apps.

~~What do I have to do to get that file to be generated? I don't see it in my `target` directory~~ Nevermind, I figured it out

**Comment by geoand** [comment]
[build-analytics-event-new.json](https://github.com/user-attachments/files/24671467/build-analytics-event-new.json)
[build-analytics-event-orig.json](https://github.com/user-attachments/files/24671468/build-analytics-event-orig.json)

Again they look the same

File: independent-projects/tools/analytics-common/src/main/java/io/quarkus/analytics/rest/RestClient.java [hunk 1]
```diff
@@ -122,23 +119,26 @@ Optional<AnalyticsRemoteConfig> getConfig(final URI uri) {
...
+        if (payload instanceof Identity identity) {
+            toSend = JsonSerializer.toJson(identity);
+        } else if (payload instanceof Track track) {
+            toSend = JsonSerializer.toJson(track);
+        } else {
+            throw new IllegalArgumentException("Unsupported payload type: " + payload.getClass().getName());
+        }
 
-            return httpClient.sendAsync(request, HttpResponse.BodyHandlers.ofString());
-        } catch (IOException e) {
```
Comment (brunobat) [inline independent-projects/tools/analytics-common/src/main/java/io/quarkus/analytics/rest/RestClient.java:138]: We should catch this exception. We want to continue processing even if we don't want to log.

**Review by brunobat — COMMENTED** [review]
It should be ok. I created tests and pushed a commit. 
The json is the one created by Jackson.

File: independent-projects/tools/analytics-common/src/main/java/io/quarkus/analytics/util/JsonSerializer.java [hunk 2]
```diff
@@ -0,0 +1,351 @@
...
+                builder.put(entry.getKey(), intVal);
+            } else if (value instanceof Long longVal) {
+                builder.put(entry.getKey(), longVal);
+            } else if (value instanceof Map) {
+                builder.put(entry.getKey(), toJsonObject((Map<String, Object>) value));
+            } else if (value instanceof List) {
+                builder.put(entry.getKey(), toJsonArrayFromObjects((List<Object>) value));
+            } else if (value != null) {
+                builder.put(entry.getKey(), value.toString());
+            }
```
Comment (aloubyansky) [inline independent-projects/tools/analytics-common/src/main/java/io/quarkus/analytics/util/JsonSerializer.java:247]: Just in case, it doesn't look like the fine-grained type casting is actually necessary. It's an impl detail but most of the methods call `putInternal` that simply casts the argument back to Object.
I have similar code here https://github.com/quarkusio/quarkus/blob/main/independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/app/ApplicationModelSerializer.java#L255-L261

Comment (geoand) [reply independent-projects/tools/analytics-common/src/main/java/io/quarkus/analytics/util/JsonSerializer.java:247]: Ah, nice!

Comment (aloubyansky) [reply independent-projects/tools/analytics-common/src/main/java/io/quarkus/analytics/util/JsonSerializer.java:247]: There seems to be some common code between our use-cases. I had some extra constraints not add extra dependencies in the `app-model`, so I exported the original object model to a `Map` with [Mappable](https://github.com/quarkusio/quarkus/blob/main/independent-projects/bootstrap/app-model/src/main/java/io/quarkus/bootstrap/model/Mappable.java) but I pass a collection factory that creates JSON objects directly.

Comment (geoand) [reply independent-projects/tools/analytics-common/src/main/java/io/quarkus/analytics/util/JsonSerializer.java:247]: 👌

**Review by gsmet — COMMENTED** [review]
I think you should be able to drop these two lines now:

https://github.com/quarkusio/quarkus/blob/2641a1d5f507ed951c38071ff38a9db5342a58c2/devtools/maven/src/main/resources/META-INF/maven/extension.xml#L5-L6

and get the CI still green.

**Comment by geoand** [comment]
Good point!

I updated the PR. How about we get it in now and then work on what we need from the JSON module to cover common cases in another PR?

**Review by gsmet — APPROVED** [review]
Yeah, totally agree.

**Comment by geoand** [comment]
`2026-01-17T12:49:09.1725310Z ##[endgroup]
2026-01-17T12:49:09.8474093Z ##[error]Failed to get latest Mandrel release for Java 21 from DISCO API: TypeError: Cannot read properties of undefined (reading 'links')` is unrelated
