### PR TITLE
Make error message about needing a DataSource for a PersistenceUnit actionable

### LINKED ISSUE #49159: Hibernate initalization issue with Multiple Datasources and Compose Dev Services
### Describe the bug

I am trying to create a simple example with Hibernate ORM Panache, Multiple Datasources and Compose Dev Services.
I can spin up the containers and see exactly the default datasource in the console with the example provided here: https://github.com/myfear/ejq_substack_articles/tree/main/xa-transaction-tutorial

As soon as I uncomment the following two lines in the application.properties:

# --- Hibernate ORM configuration ---
#=com.example.customer
#quarkus.hibernate-orm.accounts.packages=com.example.account

- The Compose Dev Services do not start the containers anymore. (podman ps lists zero containers)
- And I get below exception:

```posh
2025-07-30 08:41:58,352 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor#configurationDescriptorBuilding threw an exception: io.quarkus.runtime.configuration.ConfigurationException: Datasource must be defined for persistence unit 'accounts'. Refer to https://quarkus.io/guides/datasource for guidance.
	at io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor.collectDialectConfig(HibernateOrmProcessor.java:997)
	at io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor.producePersistenceUnitDescriptorFromConfig(HibernateOrmProcessor.java:949)
	at io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor.handleHibernateORMWithNoPersistenceXml(HibernateOrmProcessor.java:889)
	at io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor.configurationDescriptorBuilding(HibernateOrmProcessor.java:352)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:255)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2651)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2630)
	at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1622)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1589)
	at java.base/java.lang.Thread.run(Thread.java:1583)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:372)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:289)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:61)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:89)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:432)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:55)
	at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:143)
	at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:98)
	at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:107)
	at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:70)
```

### Expected behavior

Both containers start and Hibernate initializes accordingly.

### Actual behavior

No Dev Service container is started and I get the mentioned exception.

### How to Reproduce?

https://github.com/myfear/ejq_substack_articles/tree/main/xa-transaction-tutorial

1) Checkout and start Quarkus => Containers start as expected. => Stop Quarkus
2) Uncomment Lines 17+18 here https://github.com/myfear/ejq_substack_articles/blob/main/xa-transaction-tutorial/src/main/resources/application.properties
3) Start Quarkus => Exception

### Output of `uname -a` or `ver`

Darwin Kernel Version 24.5.0: Tue Apr 22 19:53:27 PDT 2025; root:xnu-11417.121.6~2/RELEASE_ARM64_T6041 arm64

### Output of `java -version`

openjdk 21.0.7 2025-04-15 LTS OpenJDK Runtime Environment Temurin-21.0.7+6 (build 21.0.7+6-LTS) OpenJDK 64-Bit Server VM Temurin-21.0.7+6 (build 21.0.7+6-LTS, mixed mode, sharing)

### Quarkus version or git rev

 <quarkus.platform.version>3.24.5</quarkus.platform.version>

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.9 (8e8579a9e76f7d015ee5ec7bfcdc97d260186937)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
This is done by giving the exact configuration property that the user needs to set.

- Closes: #49159

### CODE REVIEW

File: extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmProcessor.java [hunk 1]
```diff
@@ -989,10 +989,16 @@ private static void collectDialectConfig(String persistenceUnitName,
         Optional<String> dbKind = jdbcDataSource.map(JdbcDataSourceBuildItem::getDbKind);
         Optional<String> explicitDbMinVersion = jdbcDataSource.flatMap(JdbcDataSourceBuildItem::getDbVersion);
         if (multiTenancyStrategy != MultiTenancyStrategy.DATABASE && jdbcDataSource.isEmpty()) {
+            String dsConfigProperty;
+            if (PersistenceUnitUtil.DEFAULT_PERSISTENCE_UNIT_NAME.equals(persistenceUnitName)) {
```
Comment (geoand) [inline extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmProcessor.java]: I am not sure if this can happen here, but I thought I would play it safe regardless

Comment (mbellade) [reply extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmProcessor.java]: It can, so definitely +1

**Review by mbellade — APPROVED** [review]
Thank you @geoand

File: extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmProcessor.java [hunk 2]
```diff
@@ -989,10 +989,16 @@ private static void collectDialectConfig(String persistenceUnitName,
...
+                dsConfigProperty = "quarkus.hibernate-orm.datasource";
+            } else {
+                dsConfigProperty = String.format(Locale.ROOT, "quarkus.hibernate-orm.\"%s\".datasource", persistenceUnitName);
+            }
```
Comment (yrodiere) [inline extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmProcessor.java]: You might want to use `HibernateOrmRuntimeConfig.puPropertyKey` to do this?

Like here:

https://github.com/quarkusio/quarkus/blob/8149d79e4c84f97d9997071ed2fd27c99fe5d3aa/extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmProcessor.java#L713-L717

**Review by yrodiere — APPROVED** [review]
LGTM, thanks! You might want to use `HibernateOrmRuntimeConfig.puPropertyKey`, but that's a detail.

File: extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmProcessor.java (hunk 2 above)
Comment (geoand) [reply extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmProcessor.java]: Ah nice. I'll use that

**Review by yrodiere — APPROVED** [review]
