### PR TITLE
Load Kotlin parent first

### LINKED ISSUE #11549: Quarkus, Jackson and Kotlin 1.4
**Describe the bug**
* Upgraded to Kotlin 1.4
* Use Jackson and Jackson-module-kotlin
* Running with @QuarkusTest fails
* Same test without @QuarkusTest is ok

Se repository: [https://github.com/kny78/quarkus-kotlin14-jackson-fail](https://github.com/kny78/quarkus-kotlin14-jackson-fail)
See failure output: [https://github.com/kny78/quarkus-kotlin14-jackson-fail/tree/master/failure-logs](https://github.com/kny78/quarkus-kotlin14-jackson-fail/tree/master/failure-logs)

**Expected behavior**
Both tests should run ok:
* im.kny.DeSerializeQuarkusTest (Fails)
* im.kny.DeSerializeNonQuarkusTest (Ok)

**Actual behavior**
The test im.kny.DeSerializeQuarkusTest fail.s

**To Reproduce**
1. git clone git@github.com:kny78/quarkus-kotlin14-jackson-fail.git
2. mvnw install
3. 

```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:

        Linux kjetil 5.7.15-200.fc32.x86_64 #1 SMP Tue Aug 11 16:36:14 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

 - Output of `java -version`: 

        openjdk version "11.0.8" 2020-07-14
        OpenJDK Runtime Environment 18.9 (build 11.0.8+10)
        OpenJDK 64-Bit Server VM 18.9 (build 11.0.8+10, mixed mode, sharing)

 - GraalVM version (if different from Java): N/A
 - Quarkus version or git rev: 1.7.0
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 

        Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
        Maven home: /home/kny/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3
        Java version: 11.0.8, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-11-openjdk-11.0.8.10-2.fc32.x86_64
        Default locale: en_GB, platform encoding: UTF-8
        OS name: "linux", version: "5.7.15-200.fc32.x86_64", arch: "amd64", family: "unix"


**Additional context**
(Add any other context about the problem here.)

### PR DESCRIPTION
**Pull request by stuartwdouglas**
Also change to 1.4, which I am not sure if want just yet or if it should be a different PR (although this is all inter-related, as you can't do 1.4 upgrade without these changes).

Also note that the existing Kotlin tests exhibit the failure from #11549 when the update to 1.4 is performed, so I did not add a specific test for this (as we already have tests).

Fixes #11549

### CODE REVIEW

File: extensions/kotlin/deployment/src/main/java/io/quarkus/kotlin/deployment/KotlinCompilationProvider.java [hunk 1]
```diff
@@ -102,7 +105,7 @@ public boolean hasErrors() {
             return !errors.isEmpty();
         }
 
-        @Override
+        //kotlin 1.3 version
```
Comment (evanchooly) [inline extensions/kotlin/deployment/src/main/java/io/quarkus/kotlin/deployment/KotlinCompilationProvider.java:108]: smart.  i'd removed that in my PR...

File: extensions/kotlin/runtime/pom.xml [hunk 2]
```diff
@@ -19,6 +19,20 @@
                 <groupId>io.quarkus</groupId>
                 <artifactId>quarkus-bootstrap-maven-plugin</artifactId>
                 <configuration>
+                    <parentFirstArtifacts>
```
Comment (evanchooly) [inline extensions/kotlin/runtime/pom.xml:22]: I had started to realize late yesterday the answer probably lay in loading parent first.  I was going to hit you up for input today actually.  But i had no idea this mechanism existed.    Pretty brilliant.

File: extensions/kotlin/runtime/pom.xml [hunk 3]
```diff
@@ -19,6 +19,20 @@
...
+                        <parentFirstArtifact>org.jetbrains.kotlin:kotlin-stdlib-jdk8</parentFirstArtifact>
+                        <parentFirstArtifact>org.jetbrains.kotlin:kotlin-stdlib-jdk7</parentFirstArtifact>
```
Comment (evanchooly) [inline extensions/kotlin/runtime/pom.xml:24]: I don't know that we need the `-jdk8` and `-jdk7` deps any more.  The kotlin docs suggest that 1.4 doesn't need those and we can just dep on `stdlib`.

File: extensions/panache/hibernate-orm-panache-kotlin/runtime/pom.xml [hunk 4]
```diff
@@ -21,6 +21,10 @@
             <groupId>io.quarkus</groupId>
             <artifactId>quarkus-hibernate-orm</artifactId>
         </dependency>
+        <dependency>
```
Comment (evanchooly) [inline extensions/panache/hibernate-orm-panache-kotlin/runtime/pom.xml:24]: do the `mongodb-panache-kotlin` poms need updating or do they already dep on `quarkus-kotlin`?

**Review by evanchooly — CHANGES_REQUESTED** [review]
questions aside, this looks great.  the load parent first was the missing piece in my own work so this cleans that all up.  It *does* look like the mongodb modules need an update, too, as they are failing with the same "can't find kotlin.Any" error.

**Comment by evanchooly** [comment]
I tried pushing changes to the PR but they ended up on my fork instead.  https://github.com/evanchooly/quarkus/tree/11549

The diff is pretty light.  i'll take another swing at getting them in right place (if I have rights) after lunch.

**Comment by stuartwdouglas** [comment]
There is some weirdness here, as I can't reproduce these failures locally (even though I could originally). 

I then thought my changes had fixed them, but it turns out somehow those tests just started working on their own for me locally, which I still don't understand.

**Comment by evanchooly** [comment]
did you see my PR on your PR?  just a handful of changes on what's here and all seems to be well.

**Comment by stuartwdouglas** [comment]
I have updated it

**Comment by evanchooly** [comment]
@geoand i'm already on the review.  :)  I think we're just waiting for CI (which looks like it might be hung with that job already taking 2.5h) and we're good to go.  i tested the PR with the reproducer project the OP submitted and it passed.

**Comment by geoand** [comment]
> @geoand i'm already on the review. :) I think we're just waiting for CI (which looks like it might be hung with that job already taking 2.5h) and we're good to go. i tested the PR with the reproducer project the OP submitted and it passed.

:+1: 

I only re-requested the review because you had requested changes and Stuart seems to have addressed them

**Comment by evanchooly** [comment]
Got it.   He merged a PR i filed against his.  Provided the tests pass in all thumbs up.

**Review by evanchooly — APPROVED** [review]
