### PR TITLE
Fix step authentication with Keycloak when protocol mapper has 'acr' user attribute configured as single valued string

### LINKED ISSUE #50364: OIDC Steup authentication is missing information about insufficient authentication level in 'www-authenticate' when provider responses with single ACR
### Describe the bug

I was reviewing my colleague @jcarranzan test coverage failures today for OIDC step up authentication and mentioned that Keycloak can respond with a single ACR stored that is deserialized into a `String`, instead of `JsonArray`. In such a case, response status is correctly 401, but the `www-authenticate` header is missing information about the insufficient level.

We do have extensive test coverage https://github.com/quarkusio/quarkus/blob/main/integration-tests/oidc-tenancy/src/test/java/io/quarkus/it/keycloak/BearerTokenStepUpAuthenticationTest.java, but the OIDC provider that I used returned array even for a single values.

I'll fix it later today.

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by michalvavrik**
- closes https://github.com/quarkusio/quarkus/issues/50364
- in https://datatracker.ietf.org/doc/rfc9470/ `6.2.  OAuth 2.0 Token Introspection` section defines the `acr` claim as a single string value, so this needs to be supported

### CODE REVIEW

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/StepUpAuthenticationPolicy.java [hunk 1]
```diff
@@ -147,4 +151,13 @@ static void markAsEnabled() {
     static boolean isEnabled() {
         return enabled;
     }
+
+    private static String[] splitAcrValues(String acrValues) {
+        String[] acrValuesArr = acrValues.split(",");
+        if (acrValuesArr.length > 1) {
+            // it doesn't make sense, but it is theoretically possible that user will specify one value multiple times
```
Comment (sberyozkin) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/StepUpAuthenticationPolicy.java]:
```suggestion
```
This is a sound code removing duplicates so I believe we don't have to explain it 🙂, may be we could instead warn but I'd not be concerned

**Review by sberyozkin — APPROVED** [review]
Thanks Michal

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/StepUpAuthenticationPolicy.java (hunk 1 above)
Comment (michalvavrik) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/StepUpAuthenticationPolicy.java]: yep
