### PR TITLE
Make CORS Allowed-Headers check case insensitive

### LINKED ISSUE #3681: CORS Allowed-Headers shouldn't be case sensitive
**Describe the bug**
CORS config `quarkus.http.cors.headers` shouldn't be case sensitive, since [HTTP headers are case-insensitive](https://tools.ietf.org/html/rfc2616#section-4.2).

**Expected behavior**
Setting  `quarkus.http.cors.headers=Content-Type` on `application.properties` should cause [pre-flight `OPTIONS` http requests](https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request) with `Access-Control-Request-Headers: content-type` to return a response with header `Access-Control-Allow-Headers: content-type`.

**Actual behavior**
Lower case allow-headers `content-type` is not returned when client asks for camel-case `Content-Type`.

**To Reproduce**
1. [Configure the Quarkus CORS filter](https://quarkus.io/guides/undertow-reference#cors-filter) with `quarkus.http.cors.headers=Content-Typet`
2. Make a pre-flight `OPTIONS` request with the header `Access-Control-Request-Headers: content-type`
3. Notice the missing `Access-Control-Allow-Headers: content-type` in the response headers.

**Configuration**
```properties
#CORS
quarkus.http.cors=true
quarkus.http.cors.headers=Content-Type
```
**Environment (please complete the following information):**
 - Quarkus version or git rev: 0.21.1

**Additional context**
HTTP headers are case-insensitive, from [RFC 2616 -   Hypertext Transfer Protocol -- HTTP/1.1, section 4.2 - Message Headers](https://tools.ietf.org/html/rfc2616#section-4.2),.

### PR DESCRIPTION
**Pull request by gwenneg**
Fixes #3681

### CODE REVIEW

File: extensions/vertx-web/runtime/src/main/java/io/quarkus/vertx/web/runtime/cors/CORSFilter.java [hunk 1]
```diff
@@ -24,9 +24,10 @@ private void processRequestedHeaders(HttpServerResponse response, String request
         if (corsConfig.headers.isEmpty()) {
             response.headers().set(HttpHeaders.ACCESS_CONTROL_ALLOW_HEADERS, requestedHeaders);
         } else {
+            String lcRequestedHeaders = requestedHeaders.toLowerCase();
             final String validRequestHeaders = corsConfig.headers
                     .stream()
-                    .filter(requestedHeaders::contains)
+                    .filter(configHeader -> lcRequestedHeaders.contains(configHeader.toLowerCase()))
                     .collect(Collectors.joining(","));
```
Comment (gwenneg) [inline extensions/vertx-web/runtime/src/main/java/io/quarkus/vertx/web/runtime/cors/CORSFilter.java]: @gsmet Is it OK to keep this lambda here?

Comment (machi1990) [reply extensions/vertx-web/runtime/src/main/java/io/quarkus/vertx/web/runtime/cors/CORSFilter.java]: Should we lower case requested headers too?

Comment (gwenneg) [reply extensions/vertx-web/runtime/src/main/java/io/quarkus/vertx/web/runtime/cors/CORSFilter.java]: We should and it's already done at line 27 :)

Comment (machi1990) [reply extensions/vertx-web/runtime/src/main/java/io/quarkus/vertx/web/runtime/cors/CORSFilter.java]: Oops, my bad. Please Ignore my comment, I missed that part. Thanks :-)

Comment (gsmet) [reply extensions/vertx-web/runtime/src/main/java/io/quarkus/vertx/web/runtime/cors/CORSFilter.java]: I think I would have lowercased the config headers at the init of the filter once and for all.

As it's runtime code and the lambda is not that useful, I would have removed it.

And, if I'm not mistaken, the current code is fragile and unsafe. I think we should split the requested headers before doing any comparison. Otherwise, you could have a partial match.

And I would probably have done the same for the methods.

**Review by gsmet — CHANGES_REQUESTED** [review]
Added some comments. Not directly related to your change but while we're at it...

File: extensions/vertx-web/runtime/src/main/java/io/quarkus/vertx/web/runtime/cors/CORSFilter.java (hunk 1 above)
Comment (gwenneg) [reply extensions/vertx-web/runtime/src/main/java/io/quarkus/vertx/web/runtime/cors/CORSFilter.java]: I did lowercase the headers in the filter constructor at first and then saw that `CORSConfig` was part of `HttpConfiguration` which is annotated with `@ConfigRoot(phase = ConfigPhase.RUN_TIME)`. Knowing that, is it really OK to lowercase once at the filter init?

Comment (gsmet) [reply extensions/vertx-web/runtime/src/main/java/io/quarkus/vertx/web/runtime/cors/CORSFilter.java]: Hmmm, you’re right.

Comment (gsmet) [reply extensions/vertx-web/runtime/src/main/java/io/quarkus/vertx/web/runtime/cors/CORSFilter.java]: Yup, that's exactly why I'm not happy with the current code.

Comment (gwenneg) [reply extensions/vertx-web/runtime/src/main/java/io/quarkus/vertx/web/runtime/cors/CORSFilter.java]: And it's about to be changed, I'll update the PR as soon as I find some time :)

**Comment by gwenneg** [comment]
The lambdas and unsafe lists comparisons are gone.

**Comment by geoand** [comment]
@gsmet I think we longer need the `backport` label, correct?

File: extensions/vertx-web/runtime/src/main/java/io/quarkus/vertx/web/runtime/cors/CORSFilter.java [hunk 2]
```diff
@@ -12,6 +15,8 @@
 
 public class CORSFilter implements Handler<RoutingContext> {
 
+    private static final String COMMA_SEPARATED_SPLIT_REGEX = "\\s*,\\s*";
```
Comment (gsmet) [inline extensions/vertx-web/runtime/src/main/java/io/quarkus/vertx/web/runtime/cors/CORSFilter.java]: You need to compile the regexp, otherwise it will be compiled each time you use it.

File: extensions/vertx-web/runtime/src/main/java/io/quarkus/vertx/web/runtime/cors/CORSFilter.java [hunk 3]
```diff
@@ -20,34 +25,43 @@ public CORSFilter(CORSConfig corsConfig) {
...
 
-            final String validRequestedMethods = corsConfig.methods
-                    .stream()
-                    .filter(method -> requestedMethods.contains(method.name()))
-                    .map(HttpMethod::name)
-                    .collect(Collectors.joining(","));
+            List<String> validRequestedMethods = new ArrayList<>();
+            for (HttpMethod configMethod : corsConfig.methods) {
+                if (requestedMethods.contains(configMethod.name())) {
+                    validRequestedMethods.add(configMethod.name());
```
Comment (gsmet) [inline extensions/vertx-web/runtime/src/main/java/io/quarkus/vertx/web/runtime/cors/CORSFilter.java]: Shouldn't we be case insensitive too?

**Review by gsmet — CHANGES_REQUESTED** [review]
Added 2 comments inline.

File: extensions/vertx-web/runtime/src/main/java/io/quarkus/vertx/web/runtime/cors/CORSFilter.java (hunk 3 above)
Comment (gwenneg) [reply extensions/vertx-web/runtime/src/main/java/io/quarkus/vertx/web/runtime/cors/CORSFilter.java]: Not according to the RFC 2616: https://tools.ietf.org/html/rfc2616#section-5.1.1

> The method is case-sensitive.

Comment (gsmet) [reply extensions/vertx-web/runtime/src/main/java/io/quarkus/vertx/web/runtime/cors/CORSFilter.java]: OK, I would have been more lenient but I can live with it :).

Comment (gwenneg) [reply extensions/vertx-web/runtime/src/main/java/io/quarkus/vertx/web/runtime/cors/CORSFilter.java]: I'm fine with being lenient :) I'll change this while adding the regexp compilation.

**Comment by gwenneg** [comment]
There's an author issue with my last commit, I'll fix that in a couple hours.

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
OK, please post a message when fixed!

**Comment by gwenneg** [comment]
Author issue solved!
