### PR TITLE
Make sure @ClientExceptionMapper works properly in native mode

### LINKED ISSUE #23766: Unable to use @ClientExceptionMapper in native build
### Describe the bug

While building I get this exception;

Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: org.acme.RestService.toException(javax.ws.rs.core.Response).

I tried making the method public, and registering the interface for reflection but it did not work.

cc @geoand 

### Expected behavior

Graalvm build should work

### Actual behavior

Graalvm build fails with an exception

### How to Reproduce?

I dont have a reproducer now, but I can provide one in needed.

### Output of `uname -a` or `ver`

Darwin Kernel Version 20.6.0

### Output of `java -version`

openjdk version "17.0.2" 2022-01-18

### GraalVM version (if different from Java)

GraalVM 21.3.1 Java 17 CE

### Quarkus version or git rev

2.7.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #23766

### CODE REVIEW

File: integration-tests/rest-client-reactive/src/main/java/io/quarkus/it/rest/client/main/HelloClient.java [hunk 1]
```diff
@@ -1,16 +1,29 @@
...
 @Path("")
 public interface HelloClient {
     @POST
     @Produces(MediaType.TEXT_PLAIN)
     @Consumes(MediaType.TEXT_PLAIN)
     String greeting(String name, @QueryParam("count") int count);
+
+    // this isn't used, but it makes sure that the generated provider can be properly instantiated in native mode
+    @ClientExceptionMapper
+    static RuntimeException toException(Response response) {
```
Comment (michalszynkiewicz) [inline integration-tests/rest-client-reactive/src/main/java/io/quarkus/it/rest/client/main/HelloClient.java:23]: can we use it instead? 
In the future we may have other native bugs in this and having half of the test already written maybe it's worth going all the way?

**Review by michalszynkiewicz — APPROVED** [review]

File: integration-tests/rest-client-reactive/src/main/java/io/quarkus/it/rest/client/main/HelloClient.java (hunk 1 above)
Comment (geoand) [reply integration-tests/rest-client-reactive/src/main/java/io/quarkus/it/rest/client/main/HelloClient.java:23]: Yeah, I'll certainly add the rest of the test in the future :)
