### PR TITLE
Jacoco Fixes

### LINKED ISSUE #16358: quarkus-jacoco produces tons of logged excepiions in 1.13 like `Cannot transform java.lang.Object`
## Describe the bug
After some experiments how to change our code to get "proper code-coverage" of tests running via Quarkus, we've realized that 1.13.0 introduced the quarkus-jacoco extension, which solved our problem that the code-coverage with jacoco+Quarkus didn't work. However it introduced a new issue that Quarkus now complains that it can no longer instrument classes with messages like `Cannot transform java.lang.Object as its containing application archive could not be found.`. This happens both locally and in CI (GH infra). It seems to be a problem since 1.13.0.

### Expected behavior
Quarkus + jacoco instrumentation + code-coverage not polluting the logs with those exceptions

### Actual behavior
Tons of exceptions logged. Few examples:
```
java.lang.instrument.IllegalClassFormatException: Error while instrumenting io/quarkus/test/common/TestResourceManager.
2021-04-08 10:52:58,272 WARN  [io.qua.dep.ste.ClassTransformingBuildStep] (build-76) Cannot transform java.lang.Deprecated as its containing application archive could not be found.
2021-04-08 10:52:58,280 WARN  [io.qua.dep.ste.ClassTransformingBuildStep] (build-76) Cannot transform java.lang.Object as its containing application archive could not be found.
```

Example CI runs:
* [PR that introduced the quarkus-jacoco extension](https://github.com/projectnessie/nessie/runs/2200318356)  - choose "Build with Maven", around log line number 4060
* [later commit](https://github.com/projectnessie/nessie/runs/2234618541) - choose "Build with Maven", around log line number 4150

## To Reproduce

```
git clone https://github.com/projectnessie/nessie.git
./mvnw clean install -DskipTests
./mvnw clean install -Pcode-coverage -pl servers/quarkus-server/
```

### Configuration
application.properties in [`servers/quarkus-server/src/main/resources/application.properties`](https://github.com/projectnessie/nessie/blob/main/servers/quarkus-server/src/main/resources/application.properties)

### Output of `uname -a` or `ver`
github OSS CI

### Output of `java -version`
```
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment GraalVM CE 21.0.0.2 (build 11.0.10+8-jvmci-21.0-b06)
OpenJDK 64-Bit Server VM GraalVM CE 21.0.0.2 (build 11.0.10+8-jvmci-21.0-b06, mixed mode, sharing)
```

### Quarkus version or git rev
1.13.0 + 1.13.1

### PR DESCRIPTION
**Pull request by stuartwdouglas**
- Note in docs that you can't use both plugin and extension
- Make sure only actual dependencies are taken into account
- If an error occurs print out an error report

Fixes #16358

### CODE REVIEW

File: test-framework/jacoco/deployment/src/main/java/io/quarkus/jacoco/deployment/JacocoProcessor.java [hunk 1]
```diff
@@ -99,16 +105,23 @@ void transformerBuildItem(BuildProducer<BytecodeTransformerBuildItem> transforme
             Set<String> sources = new HashSet<>();
             MultiSourceFileLocator sourceFileLocator = new MultiSourceFileLocator(4);
             if (BuildToolHelper.isMavenProject(targetdir.toPath())) {
+                Set<AppArtifactKey> runtimeDeps = new HashSet<>();
+                for (AppDependency i : curateOutcomeBuildItem.getEffectiveModel().getUserDependencies()) {
+                    runtimeDeps.add(i.getArtifact().getKey());
+                }
                 LocalProject project = LocalProject.loadWorkspace(targetdir.toPath());
+                runtimeDeps.add(project.getKey());
```
Comment (stuartwdouglas) [inline test-framework/jacoco/deployment/src/main/java/io/quarkus/jacoco/deployment/JacocoProcessor.java:113]: @aloubyansky do you know if the gradle code below would also need a similar change? I don't have any multi module gradle projects locally to test on.

Comment (aloubyansky) [reply test-framework/jacoco/deployment/src/main/java/io/quarkus/jacoco/deployment/JacocoProcessor.java:113]: Haven't tried it but looking at the change, it makes sense. BTW, the AppModel already includes `getLocalProjectArtifacts()` method, it could simplify your loops here.

**Comment by snazy** [comment]
I've tried this commit (cherry-picked onto the Quarkus 1.13 branch, 3b461a23a56da52d690d91e474019117e8f0eb4e) but the warnings + stacktraces are still logged.

**Comment by snazy** [comment]
Sorry, was too fast without reading the explicitly mentioned docs change. After disabling the jacoco-plugin in that module, the warnings and stacktraces are no longer logged.

The reason why projectnessie has this jacoco setup is to collect the code-coverage for the source in the Maven module that uses Quarkus _and_ the code-coverage for other classes. I can't really test the whole CI spiel locally, so cannot confirm whether all that works. Would be great to get this PR backported into the 1.13 branch.

File: docs/src/main/asciidoc/tests-with-coverage.adoc [hunk 2]
```diff
@@ -175,6 +175,9 @@ Now we need to add Jacoco to our project. To do this we need to add the followin
 This Quarkus extension takes care of everything that would usually be done via the Jacoco maven plugin, so no additional
 config is required.
 
+WARNING: Do not use both the extension and the plugin, if you configure both you will get lots of errors about classes
+already being instrumented.
```
Comment (famod) [inline docs/src/main/asciidoc/tests-with-coverage.adoc:179]: Doesn't that contradict paragraph "7. Coverage for tests not using @QuarkusTest"?

Comment (gsmet) [reply docs/src/main/asciidoc/tests-with-coverage.adoc:179]: @stuartwdouglas could you have a look at this comment?

**Review by gsmet — APPROVED** [review]

**Comment by bcluap** [comment]
In 1.13.2 and prior I can use the Jacoco extension in a multi-module project and it includes the coverage of all the modules in the project. Now as of 1.13.3 this is no longer the case and it only includes the direct module in which the @QuarkusTest is found.

Is there a way to get the plugin to analyse the coverage of all the modules?

**Comment by stuartwdouglas** [comment]
Can you file an issue? That should work.

**Comment by bcluap** [comment]
Created a reproducer: https://github.com/quarkusio/quarkus/issues/17086
