### PR TITLE
Optimise path decoding in RoutingUtils

### LINKED ISSUE #47384: Performance regression while resolving path
### Describe the bug

https://github.com/quarkusio/quarkus/commit/7899c9d44b4ce8dd338940c9996b75bdc8475ebd has introduced a change in io/quarkus/vertx/http/runtime/RoutingUtils.getNormalizedAndDecodedPath which makes it perform additional parsing and URI allocations - even for simple hello world cases

see

Image

in violet - which cost as much as HTTP request parsing

and from nearest distance: 

Image

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ia3andy**
- Closes: #47384

### CODE REVIEW

**Comment by ia3andy** [comment]
@franz1981 I'll try to submit a follow up PR fixing it even when there is % in the path..

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/RoutingUtils.java [hunk 1]
```diff
@@ -28,6 +28,9 @@ public static String getNormalizedAndDecodedPath(RoutingContext ctx) {
         if (normalizedPath.contains("?")) {
             return null;
         }
+        if (normalizedPath.indexOf('%') == -1) {
```
Comment (franz1981) [inline extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/RoutingUtils.java:31]: I know that is unrelated to this issue but since we are here...
Uses String::indexOf('?')  since it is slightly better optimized and doesn't involve String matching , but single char

**Comment by franz1981** [comment]
In theory URLDecoder can do the same here (slow path) - but what looks like a waste to me is that Vertx already spent cycles doing something here which can be replaced by a single method that does it at once.
And in theory the better home for this util method IMO is in vertex itself.
I am surprised they don't need any of this, to avoid security issues @cescoffier

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/RoutingUtils.java (hunk 1 above)
Comment (ia3andy) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/RoutingUtils.java:31]: WIll do the same for '?'

**Comment by ia3andy** [comment]
@franz1981 all the vertx tooling for this is not exposed as public API

**Comment by franz1981** [comment]
Julien is on PTO, let's wait him to come back

**Comment by ia3andy** [comment]
I think it's a bit more complicated than checking for '%' as we also need the remove dots '../' and replace '\' with '/'. Let's hold a bit

**Comment by ia3andy** [comment]
This is what's in the internal API that we would need:
`io.vertx.core.internal.net.RFC3986`

**Comment by gsmet** [comment]
Same here, I would expect Vert.x to do this for us, I'm surprised we have to handle this manually.

**Comment by ia3andy** [comment]
I don't think we can avoid the dots removal :-/ @franz1981 when this PR is green could you run the perf check again? It will probably be less effective than before the breaking commit but still better than using URI all the time..

**Comment by franz1981** [comment]
In any case I am on PTO, right now, so cannot perform tests. My suggestion is to use the JMH module we have in quarkus and write a bench..and I can help review it 🙏

**Comment by ia3andy** [comment]
@vietj https://github.com/vert-x3/vertx-web/blob/master/vertx-web/src/main/java/io/vertx/ext/web/handler/impl/StaticHandlerImpl.java#L174

I seems doing the remove dots there is not needed here as it's already done as explained in my previous comment.

**Comment by ia3andy** [comment]
@franz1981 this should be safe to merge, can you approve?

**Review by franz1981 — APPROVED** [review]
Lgtm

**Review by gsmet — COMMENTED** [review]
I'm not saying we shouldn't merge this as a quick fix but I'm still wondering why we have to handle things ourselves.

My understanding is that the issue is only with `GeneratedStaticResourceBuildItem` so I'm wondering if we should somehow alter the registered endpoint for these and escape it when we register it, rather than doing things at runtime when the request arrives.

My understanding is that we should be able to deal with this once and for all when we register the resource and then have a standard handling as if the files were on disk.

I suppose I might be missing something so happy to have an explanation :).

**Comment by gsmet** [comment]
FWIW, I have been looking at both https://github.com/quarkusio/quarkus/commit/7899c9d44b4ce8dd338940c9996b75bdc8475ebd and the original issue and I'm not clear on what the original patch was exactly supposed to fix.

Sorry for asking dumb questions but I would appreciate if we could take a step back and clarify things for posterity.

**Comment by ia3andy** [comment]
@gsmet the test in the original fix should explain the purpose.

**Comment by ia3andy** [comment]
Here was the original issue: https://github.com/quarkusio/quarkus/issues/45775

**Comment by ia3andy** [comment]
Also the issue is not for GeneratedStaticResourceBuildItem but for all static resources.

**Comment by ia3andy** [comment]
Here is where we need this: https://github.com/quarkusio/quarkus/blob/main/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/StaticResourcesRecorder.java#L98-L107


Also we are using this method from other extensions which rely on path to get resources (Qute Web for example)

**Comment by franz1981** [comment]
I got the feeling that similarly to how we scan the endpoints to decide how to configure the right handlers for the types required (see https://github.com/quarkusio/quarkus/blob/006177281dbc82b3cb67547b153b78f5172f9631/independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/startup/RuntimeResourceDeployment.java#L144)
we should be able there to check if the endpoint path matches the one which should contains static resources and save any check to happen since they won't deliver anything, but I don't remember by heart

**Review by gsmet — APPROVED** [review]

**Comment by tsegismont** [comment]
> @vietj @tsegismont https://github.com/vert-x3/vertx-web/blob/master/vertx-web/src/main/java/io/vertx/ext/web/handler/impl/StaticHandlerImpl.java#L174
> 
> It seems doing the remove dots there is not needed here as it's already done as explained in my previous comment.

Thanks @ia3andy for the heads-up

**Comment by tsegismont** [comment]
> > @vietj @tsegismont https://github.com/vert-x3/vertx-web/blob/master/vertx-web/src/main/java/io/vertx/ext/web/handler/impl/StaticHandlerImpl.java#L174
> > It seems doing the remove dots there is not needed here as it's already done as explained in my previous comment.
> 
> Thanks @ia3andy for the heads-up

@ia3andy in fact, it is required because `rc.normalizedPath()` will not remove dot segments in case of an encoded backslah (see https://github.com/vert-x3/vertx-web/blob/0e4a13c5dcfe1edd0512f279b272554c47ef4c4b/vertx-web/src/test/java/io/vertx/ext/web/tests/handler/StaticHandlerTest.java#L955)

**Comment by ia3andy** [comment]
Having to remove dots twice feels quite wrong. Maybe we should consider adding an exception to the RFC decode step to also handle `\`, since they’re eventually converted to `/` anyway?

**Comment by ia3andy** [comment]
Or maybe we should remove support for windows path, because URI paths `\` are not meant to be used as path delimiter (as they are not unreserved).

**Comment by tsegismont** [comment]
I believe it happens in two steps because a route handler (other than a static file server) can be interested in having a normalized path without fully decoding uri.
