### PR TITLE
Properly captures and restores the vert.x context in the reactive REST Client

### LINKED ISSUE #23940: Opentelemetry traces for reactive services contain erroneus values
### Describe the bug

When running application with enabled jaeger tracing, traces contain not just endpoints but also mysterious "HTTP GET" string, but only if the application uses reactive endpoints and Quarkus 2.7.2.Final.

### Expected behavior

Tracing should work the same way for reactive and not-reactive libraries.

### Actual behavior

Traces for a non-reactive application(or for version 2.7.1.Final) contain "ping/pong", "hello", "hello", traces for a reactive application contain "hello", "HTTP GET", "ping/pong"

### How to Reproduce?

Reproducer:
git@github.com:quarkus-qe/quarkus-test-suite.git
Command to reproduce:
`mvn clean verify -pl io.quarkus.ts.qe:monitoring-opentelemetry-reactive -Dquarkus.platform.version=2.7.2.Final`

Commands, which do not lead to this failure:
`mvn clean verify -pl io.quarkus.ts.qe:monitoring-opentelemetry-reactive -Dquarkus.platform.version=2.7.1.Final`
`mvn clean verify -pl io.quarkus.ts.qe:monitoring-opentelemetry -Dquarkus.platform.version=2.7.2.Final` (module monitoring-opentelemetry contains the same test and code logic, but uses non-reactive REST)

### Output of `uname -a` or `ver`

OS name: "linux", version: "5.16.7-200.fc35.x86_64"

### Output of `java -version`

11.0.12, vendor: GraalVM Community

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.7.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by cescoffier**
This PR handle duplicated context propagation property for the reactive REST Client.

When creating a Client request context, we capture the Vert.x context. If none, or if it's a root context, we create a duplicated context. This duplicated context is stored in the client request context, which allows filters, such as open telemetry to retrieve it. 

Also, it executes the HTTP request/response on the captured context.

It also implement a _trampoline_ to avoid enqueuing actions when we are on the right context.

### CODE REVIEW

File: independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/handlers/ClientSendRequestHandler.java [hunk 1]
```diff
@@ -70,7 +73,30 @@ public void handle(RestClientRequestContext requestContext) {
             return;
         }
         requestContext.suspend();
-        Uni<HttpClientRequest> future = createRequest(requestContext);
+        Uni<HttpClientRequest> future = createRequest(requestContext)
+                .runSubscriptionOn(new Executor() {
+                    @Override
+                    public void execute(Runnable command) {
+                        Context current = Vertx.currentContext();
+                        ClientRequestContextImpl clientRequestContext = requestContext.getClientRequestContext();
```
Comment (michalszynkiewicz) [inline independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/handlers/ClientSendRequestHandler.java:81]: can `getClinetRequestContext` ever return null here?

File: independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/spi/ResteasyReactiveClientRequestContext.java [hunk 2]
```diff
@@ -1,12 +1,27 @@
...
+    String VERTX_CONTEXT_PROPERTY = "__context";
+
     void suspend();
 
     void resume();
 
     void resume(Throwable t);
+
+    /**
+     * @return the captured or created duplicated context. See {@link #VERTX_CONTEXNT_PROPERTY} for details.
```
Comment (michalszynkiewicz) [inline independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/spi/ResteasyReactiveClientRequestContext.java:24]:
```suggestion
     * @return the captured or created duplicated context. See {@link #VERTX_CONTEXT_PROPERTY} for details.
```

**Comment by michalszynkiewicz** [comment]
It would be great to check if that's enough e.g. for filters to be executed with the proper context.

**Comment by radcortez** [comment]
> It would be great to check if that's enough e.g. for filters to be executed with the proper context.

I'll try it out

**Comment by cescoffier** [comment]
Filter won't be executed on the context. At least I didn't do anything in that sense. 

Aren't filters blocking by spec?

CC @geoand

**Comment by geoand** [comment]
> Aren't filters blocking by spec?

There isn't much in them that forces them to be blocking - in almost all cases they won't be actually.

**Comment by cescoffier** [comment]
Then, it should be possible to run them on the context.

File: independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/handlers/ClientSendRequestHandler.java (hunk 1 above)
Comment (radcortez) [reply independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/handlers/ClientSendRequestHandler.java:81]: I believe not. The `getOrCreateClientRequestContext` is called before the client request execution.

**Comment by radcortez** [comment]
Updated the PR to show that it fixes the OTel issue.

**Review by radcortez — APPROVED** [review]

File: independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/handlers/ClientSendRequestHandler.java (hunk 1 above)
Comment (cescoffier) [reply independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/handlers/ClientSendRequestHandler.java:83]: there is a test where it got `null` :-D

File: extensions/opentelemetry/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/restclient/OpenTelemetryClientFilter.java [hunk 3]
```diff
@@ -72,20 +72,25 @@ public OpenTelemetryClientFilter(final OpenTelemetry openTelemetry) {
...
             request.setProperty(REST_CLIENT_OTEL_SPAN_CLIENT_CONTEXT, spanContext);
             request.setProperty(REST_CLIENT_OTEL_SPAN_CLIENT_PARENT_CONTEXT, parentContext);
             request.setProperty(REST_CLIENT_OTEL_SPAN_CLIENT_SCOPE, scope);
         }
     }
 
+    private static io.vertx.core.Context getVertxContext(final ClientRequestContext request) {
+        io.vertx.core.Context vertxContext = (io.vertx.core.Context) request.getProperty(VERTX_CONTEXT_PROPERTY);
+        if (vertxContext == null) {
+            return QuarkusContextStorage.getVertxContext();
```
Comment (michalszynkiewicz) [inline extensions/opentelemetry/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/restclient/OpenTelemetryClientFilter.java:88]: I see `QuarkusContextStorage.getVertxContext()` can return null. 
I don't fully understand when, is it only if a user spawns their own thread and calls the client from it?
Do we still have tracing in this case?

Comment (radcortez) [reply extensions/opentelemetry/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/restclient/OpenTelemetryClientFilter.java:88]: We only use the Vert.x Context when we have a Vert.x duplicated Context available. If not, we fall back to the ThreadLocal Context Storage (for instance when you are tracing a CDI Bean outside Vert.x)

Comment (michalszynkiewicz) [reply extensions/opentelemetry/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/restclient/OpenTelemetryClientFilter.java:88]: cool

**Review by michalszynkiewicz — APPROVED** [review]
