### PR TITLE
Call the health check method on the worker pool

### LINKED ISSUE #4531: Health check called on the event loop
**Describe the bug**

With the following class:

```
@Readiness
@ApplicationScoped
public class DatabaseConnectionHealthCheck implements HealthCheck {

    @Inject
    FightService fightService;

    @Override
    public HealthCheckResponse call() {
        HealthCheckResponseBuilder responseBuilder = HealthCheckResponse.named("Database connection health check");

        System.out.println("Thread: " + Thread.currentThread().getName());
        try {
            List<Fight> fights = fightService.findAllFights();
            responseBuilder.withData("Number of rows in the database", fights.size()).up();
        } catch (IllegalStateException e) {
            e.printStackTrace();
            responseBuilder.down();
        }

        return responseBuilder.build();
    }
}
```

The call fails because it tries to access the database from an IO Thread.

**Expected behavior**
It should use a worker thread.

**Actual behavior**
It uses the event loop thread

### PR DESCRIPTION
**Pull request by cescoffier**
Fix #4531

### CODE REVIEW

**Review by kenfinnigan — DISMISSED** [review]

File: extensions/smallrye-health/runtime/src/main/java/io/quarkus/smallrye/health/runtime/SmallRyeHealthHandler.java [hunk 1]
```diff
@@ -17,7 +20,10 @@
 
     @Override
     public void handle(RoutingContext event) {
-
+        InjectableContext context = Arc.container().getActiveContext(RequestScoped.class);
```
Comment (kenfinnigan) [inline extensions/smallrye-health/runtime/src/main/java/io/quarkus/smallrye/health/runtime/SmallRyeHealthHandler.java]: @mkouba is this ok?

Comment (stuartwdouglas) [reply extensions/smallrye-health/runtime/src/main/java/io/quarkus/smallrye/health/runtime/SmallRyeHealthHandler.java]: Nope, it needs to be cleaned up afterwards. Also at the moment there is no way it can be active when this method is called.

**Review by gsmet — DISMISSED** [review]
Just blocking this thing so that nobody merges it by mistake as it has been approved.

Please dismiss once everything is ready.

**Review by stuartwdouglas — APPROVED** [review]

File: extensions/smallrye-health/runtime/src/main/java/io/quarkus/smallrye/health/runtime/SmallRyeHealthHandler.java (hunk 1 above)
Comment (mkouba) [reply extensions/smallrye-health/runtime/src/main/java/io/quarkus/smallrye/health/runtime/SmallRyeHealthHandler.java]: Also it's easier to use `io.quarkus.arc.ArcContainer.requestContext()` instead...

Comment (mkouba) [reply extensions/smallrye-health/runtime/src/main/java/io/quarkus/smallrye/health/runtime/SmallRyeHealthHandler.java]: Oh, and the method returns null if there is no request context active..

Comment (cescoffier) [reply extensions/smallrye-health/runtime/src/main/java/io/quarkus/smallrye/health/runtime/SmallRyeHealthHandler.java]: Fixed.

**Comment by cescoffier** [comment]
@gsmet changes have been made.
