### PR TITLE
ArC: decorators fixes

### LINKED ISSUE #50947: ArC: decorators - default method not correctly forwarded
### Describe the bug

A default method is not decorated by decorator but implemented by a bean - it should be forwarded to the bean but the default method is used instead.

Test: https://github.com/mkouba/quarkus/blob/arc-decorator-comparable/independent-projects/arc/tests/src/test/java/io/quarkus/arc/test/decorators/DecoratorDefaultMethodTest.java#L33

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### LINKED ISSUE #50950: ArC: an application decorator can easily break a framework bean
### Describe the bug

In https://github.com/quarkusio/quarkus/pull/43245, we changed the behavior in a way that an applied decorator turns the ArC-generated classes for framework beans into application classes. This makes package-private access impossible, including field injection (i.e. injecting a package-private field). As a result, an app decorator can easily break fwk beans in tests/dev mode. This can be very confusing for users. First of all, the error message does not help much - it's the usual class loading problem message (something along the lines of: "com.example.Foo_Bean cannot access com.example.Foo#fieldA"). Also it only happens in tests/dev mode.

Unfortunately, I don't think there's a good solution. If we turn the fwk bean class into application class then we'll break package-private access to package-private members/classes. In theory, we could turn all classes from the whole package into application classes, or would that be overkill?

We could also try to produce an actionable message but given the fact that it's the extension that would need a "fix". Not to mention that it's perfectly legal to use pacage-private members 🤷 .

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Ladicek**
Fixes #50947
Fixes #50948
Fixes #50950

### CODE REVIEW

**Comment by Ladicek** [comment]
~~This PR doesn't include a fix for #50950, because:~~

~~1. I'm still working on it~~
~~2. I imagine it will provoke some discussion, while the 2 fixes present in this PR should be relatively non-controversial.~~

This PR now includes a fix for #50950.

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Decorators.java [hunk 1]
```diff
@@ -118,6 +117,10 @@ static DecoratorInfo createDecorator(ClassInfo decoratorClass, BeanDeployment be
         }
 
         if (Modifier.isAbstract(decoratorClass.flags())) {
+            // TODO this check is not precise: we check that decorators do not declare _any_ abstract methods,
```
Comment (mkouba) [inline independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Decorators.java:120]: Do we have a follow-up issue for this TODO?

Comment (Ladicek) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Decorators.java:120]: We don't; good point. Filed #51196.

**Review by mkouba — APPROVED** [review]
Looks good.

**Review by manovotn — APPROVED** [review]
LGTM

Particularly the solution in the second commit is really nice 👍

**Comment by Ladicek** [comment]
Rebased in order to rerun, and added a fix for #50950.

**Review by manovotn — APPROVED** [review]
Initially I thought the third commit will be problematic for a non-normal scoped non-app bean decorated with an app bean decorator but that seems to somehow just work, so I think we're good :)

**Comment by Ladicek** [comment]
> Initially I thought the third commit will be problematic for a non-normal scoped non-app bean decorated with an app bean decorator but that seems to somehow just work, so I think we're good :)

I'll add a test for this case soon.

**Comment by Ladicek** [comment]
Added the test to the top commit.

**Comment by Ladicek** [comment]
@mkouba Could you please take a look at the last commit? Thanks!

**Review by mkouba — APPROVED** [review]
