### PR TITLE
Ability to generate gRPC descriptor set

### LINKED ISSUE #36897: Unable to generate gRPC descriptor set
### Describe the bug

I would like to be able to generate the [Protobuf descriptor set](https://protobuf.com/docs/descriptors#compilation-process) alongside the source code. Generally this is done as an additional flag to the `protoc` compiler process.

This can be done in Maven by configuring the [`protobuf-maven-plugin`](https://www.xolstice.org/protobuf-maven-plugin/usage.html) (see the Output Of Binary File Descriptor Sets at the bottom of that link).

I'm having a hard time being able to do that in Quarkus. I've followed the steps in https://quarkus.io/version/main/guides/grpc-generation-reference#skipping-code-generation but it seems to clash with Quarkus' code generation. 

When I disable Quarkus' code generation by doing either `-Dgrpc.codegen.skip=true` or setting `quarkus.grpc.codegen.skip=true` in `application.properties`, the application no longer compiles. It seems the Mutiny classes generated by Quarkus are no longer generated and therefore my application no longer compiles.

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

1. Clone https://github.com/quarkusio/quarkus-super-heroes
2. `cd` into `quarkus-super-heroes/rest-fights`
3. Open `pom.xml`
4. Replace it's contents with this:

```xml
<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>io.quarkus.sample.super-heroes</groupId>
  <artifactId>rest-fights</artifactId>
  <version>1.0</version>
  <name>Quarkus Sample :: Super-Heroes :: Fights Microservice</name>
  <properties>
    <assertj.version>3.24.2</assertj.version>
    <compiler-plugin.version>3.11.0</compiler-plugin.version>
    <grpc.version>1.57.2</grpc.version>
    <grpcmock.version>0.10.1</grpcmock.version>
    <mapstruct.version>1.5.5.Final</mapstruct.version>
    <maven.compiler.parameters>true</maven.compiler.parameters>
    <maven.compiler.release>17</maven.compiler.release>
    <microcks.version>0.1.3</microcks.version>
    <os-maven-plugin.version>1.7.1</os-maven-plugin.version>
    <pact.version>1.1.0</pact.version>
    <pact.writer.overwrite>true</pact.writer.overwrite>
    <protobuf-maven-plugin.version>0.6.1</protobuf-maven-plugin.version>
    <protoc.version>3.22.0</protoc.version>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
    <quarkus.platform.group-id>io.quarkus.platform</quarkus.platform.group-id>
    <quarkus.platform.version>3.5.0</quarkus.platform.version>
    <surefire-plugin.version>3.2.1</surefire-plugin.version>
    <wiremock.version>3.3.1</wiremock.version>
  </properties>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>${quarkus.platform.group-id}</groupId>
        <artifactId>${quarkus.platform.artifact-id}</artifactId>
        <version>${quarkus.platform.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-hibernate-validator</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-openapi</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-reactive-messaging-kafka</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-reactive-jackson</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-arc</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-rest-client-reactive-jackson</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-fault-tolerance</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-health</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-micrometer-registry-prometheus</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-jacoco</artifactId>
    </dependency>
    <dependency>
      <groupId>org.mapstruct</groupId>
      <artifactId>mapstruct</artifactId>
      <version>${mapstruct.version}</version>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-container-image-docker</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-openshift</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-kubernetes</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-minikube</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-apicurio-registry-avro</artifactId>
    </dependency>
    <dependency>
      <groupId>io.strimzi</groupId>
      <artifactId>kafka-oauth-client</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-mongodb-panache</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-liquibase-mongodb</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-stork</artifactId>
    </dependency>
    <dependency>
      <groupId>io.smallrye.stork</groupId>
      <artifactId>stork-service-discovery-static-list</artifactId>
    </dependency>
    <dependency>
      <groupId>io.smallrye.stork</groupId>
      <artifactId>stork-service-discovery-kubernetes</artifactId>
    </dependency>
    <dependency>
      <groupId>io.smallrye.stork</groupId>
      <artifactId>stork-service-discovery-eureka</artifactId>
    </dependency>
    <dependency>
      <groupId>io.smallrye.stork</groupId>
      <artifactId>stork-service-discovery-consul</artifactId>
    </dependency>
    <dependency>
      <groupId>io.smallrye.stork</groupId>
      <artifactId>stork-service-discovery-knative</artifactId>
    </dependency>
    <dependency>
      <groupId>io.smallrye.stork</groupId>
      <artifactId>stork-load-balancer-random</artifactId>
    </dependency>
    <dependency>
      <groupId>io.smallrye.stork</groupId>
      <artifactId>stork-load-balancer-least-requests</artifactId>
    </dependency>
    <dependency>
      <groupId>io.smallrye.stork</groupId>
      <artifactId>stork-load-balancer-least-response-time</artifactId>
    </dependency>
    <dependency>
      <groupId>io.smallrye.stork</groupId>
      <artifactId>stork-load-balancer-power-of-two-choices</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-kubernetes-client</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-opentelemetry</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-info</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-grpc</artifactId>
    </dependency>
    <dependency>
      <groupId>io.github.microcks.quarkus</groupId>
      <artifactId>quarkus-microcks</artifactId>
      <version>${microcks.version}</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-junit5</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-panache-mock</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.rest-assured</groupId>
      <artifactId>rest-assured</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.assertj</groupId>
      <artifactId>assertj-core</artifactId>
      <version>${assertj.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.wiremock</groupId>
      <artifactId>wiremock</artifactId>
      <version>${wiremock.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.grpcmock</groupId>
      <artifactId>grpcmock-junit5</artifactId>
      <version>${grpcmock.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.smallrye.reactive</groupId>
      <artifactId>smallrye-reactive-messaging-in-memory</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-test-kafka-companion</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.quarkiverse.pact</groupId>
      <artifactId>quarkus-pact-consumer</artifactId>
      <version>${pact.version}</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>io.quarkiverse.pact</groupId>
      <artifactId>quarkus-pact-provider</artifactId>
      <version>${pact.version}</version>
      <scope>provided</scope> <!-- See https://github.com/quarkiverse/quarkus-pact/issues/28 -->
    </dependency>
  </dependencies>
  <build>
    <extensions>
      <extension>
        <groupId>kr.motd.maven</groupId>
        <artifactId>os-maven-plugin</artifactId>
        <version>${os-maven-plugin.version}</version>
      </extension>
    </extensions>
    <plugins>
      <plugin>
        <groupId>${quarkus.platform.group-id}</groupId>
        <artifactId>quarkus-maven-plugin</artifactId>
        <version>${quarkus.platform.version}</version>
        <extensions>true</extensions>
        <executions>
          <execution>
            <goals>
              <goal>build</goal>
              <goal>generate-code</goal>
              <goal>generate-code-tests</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>${compiler-plugin.version}</version>
        <configuration>
          <parameters>${maven.compiler.parameters}</parameters>
          <annotationProcessorPaths>
            <path>
              <groupId>org.mapstruct</groupId>
              <artifactId>mapstruct-processor</artifactId>
              <version>${mapstruct.version}</version>
            </path>
            <path>
              <groupId>io.quarkus</groupId>
              <artifactId>quarkus-panache-common</artifactId>
              <version>${quarkus.platform.version}</version>
            </path>
          </annotationProcessorPaths>
        </configuration>
      </plugin>
      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>${surefire-plugin.version}</version>
        <configuration>
          <systemPropertyVariables>
            <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
            <maven.home>${maven.home}</maven.home>
            <pact_do_not_track>true</pact_do_not_track>
            <pact.writer.overwrite>true</pact.writer.overwrite>
          </systemPropertyVariables>
        </configuration>
      </plugin>
      <plugin>
        <artifactId>maven-failsafe-plugin</artifactId>
        <version>${surefire-plugin.version}</version>
        <executions>
          <execution>
            <goals>
              <goal>integration-test</goal>
              <goal>verify</goal>
            </goals>
            <configuration>
              <systemPropertyVariables>
                <native.image.path>${project.build.directory}/${project.build.finalName}-runner</native.image.path>
                <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
                <maven.home>${maven.home}</maven.home>
              </systemPropertyVariables>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.xolstice.maven.plugins</groupId>
        <artifactId>protobuf-maven-plugin</artifactId>
        <version>${protobuf-maven-plugin.version}</version>
        <configuration>
          <writeDescriptorSet>true</writeDescriptorSet>
          <descriptorSetFileName>locationservice-v1.dsc</descriptorSetFileName>
          <descriptorSetOutputDirectory>src/test/resources/wiremock/grpc</descriptorSetOutputDirectory>
          <protocArtifact>com.google.protobuf:protoc:${protoc.version}:exe:${os.detected.classifier}</protocArtifact>
          <pluginId>grpc-java</pluginId>
          <pluginArtifact>io.grpc:protoc-gen-grpc-java:${grpc.version}:exe:${os.detected.classifier}</pluginArtifact>
          <protocPlugins>
            <protocPlugin>
              <id>quarkus-grpc-protoc-plugin</id>
              <groupId>io.quarkus</groupId>
              <artifactId>quarkus-grpc-protoc-plugin</artifactId>
              <version>${quarkus.platform.version}</version>
              <mainClass>io.quarkus.grpc.protoc.plugin.MutinyGrpcGenerator</mainClass>
            </protocPlugin>
          </protocPlugins>
        </configuration>
        <executions>
          <execution>
            <id>compile</id>
            <goals>
              <goal>compile</goal>
            </goals>
          </execution>
          <execution>
            <id>test-compile</id>
            <goals>
              <goal>test-compile</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
  <profiles>
    <profile>
      <id>native</id>
      <activation>
        <property>
          <name>native</name>
        </property>
      </activation>
      <properties>
        <quarkus.package.type>native</quarkus.package.type>
      </properties>
    </profile>
  </profiles>
</project>
```

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by edeandrea**
Ability to generate gRPC descriptor sets.

@cescoffier please take a look. In the code gen I needed a way to get access to the project root directory so that the user could specify an output directory relative to that. I modified the Maven & Gradle plugins to provide that info into the generation. I also added a bunch of tests to both plugins.

Fixes #36897

### CODE REVIEW

**Comment by edeandrea** [comment]
The majority of the 50 changed files are new integration tests that I added.

File: extensions/grpc/codegen/src/main/java/io/quarkus/grpc/deployment/GrpcCodeGen.java [hunk 1]
```diff
@@ -1,6 +1,6 @@
 package io.quarkus.grpc.deployment;
 
-import static java.lang.Boolean.TRUE;
+import static java.lang.Boolean.*;
```
Comment (cescoffier) [inline extensions/grpc/codegen/src/main/java/io/quarkus/grpc/deployment/GrpcCodeGen.java:3]: We try to avoid * imports

**Review by cescoffier — APPROVED** [review]
There is a * import to fix. The rest looks good. I've asked Aleš and Alexei to have a look for the gRPPC protoc part and maven/gradle part.

File: extensions/grpc/codegen/src/main/java/io/quarkus/grpc/deployment/GrpcCodeGen.java [hunk 2]
```diff
@@ -262,6 +270,25 @@ private boolean isGeneratingFromAppDependenciesEnabled(Config config) {
                 .filter(value -> !"none".equals(value)).isPresent();
     }
 
+    private boolean shouldGenerateDescriptorSet(Config config) {
+        return config.getOptionalValue(GENERATE_DESCRIPTOR_SET, Boolean.class).orElse(FALSE);
+    }
+
+    private Path getDescriptorSetOutputFile(CodeGenContext context) throws IOException {
+        var dscOutputDir = context.config().getOptionalValue(DESCRIPTOR_SET_OUTPUT_DIR, String.class)
+                .map(context.projectDir()::resolve)
```
Comment (alesj) [inline extensions/grpc/codegen/src/main/java/io/quarkus/grpc/deployment/GrpcCodeGen.java:279]: Is this the only need for projectDir?
I guess it simplifies the desc out-dir usage?
Or it could be still done with full relative path?

**Review by alesj — APPROVED** [review]

File: extensions/grpc/codegen/src/main/java/io/quarkus/grpc/deployment/GrpcCodeGen.java (hunk 1 above)
Comment (edeandrea) [reply extensions/grpc/codegen/src/main/java/io/quarkus/grpc/deployment/GrpcCodeGen.java]: Just committed a fix

File: extensions/grpc/codegen/src/main/java/io/quarkus/grpc/deployment/GrpcCodeGen.java (hunk 2 above)
Comment (edeandrea) [reply extensions/grpc/codegen/src/main/java/io/quarkus/grpc/deployment/GrpcCodeGen.java:280]: > Or it could be still done with full relative path?

I'm not sure what you mean by this?

We need a reference to the project directory because the user could specify a relative path to it for the descriptor set output. Something like `src/test/resources` could be a good place to have it generated (so that tests could see it). Tools like Wiremock require configuring a path relative to the project root for where to pick it up (see https://wiremock.org/docs/grpc).

I didn't want to make an assumption that `$context.outDir/..` was _ALWAYS_ the project root dir, because that might not always be true. I thought it was safer to have the build tool pass it in.

Comment (alesj) [reply extensions/grpc/codegen/src/main/java/io/quarkus/grpc/deployment/GrpcCodeGen.java:280]: So ... is projectDir the root of the overall project (even in multi-module apps) or just a directory of your current module (sub-app if you call it)?
e.g. if I have a project with multiple microservices apps

Comment (edeandrea) [reply extensions/grpc/codegen/src/main/java/io/quarkus/grpc/deployment/GrpcCodeGen.java:280]: Its the directory of your current module. The current application being built.

Comment (alesj) [reply extensions/grpc/codegen/src/main/java/io/quarkus/grpc/deployment/GrpcCodeGen.java:280]: Just wondering "out-loud", since I'm surprised we didn't need this dir so far.

Comment (alesj) [reply extensions/grpc/codegen/src/main/java/io/quarkus/grpc/deployment/GrpcCodeGen.java:280]: Where does then `$context.outDir/..` point to, if not to the module's root?

Comment (alesj) [reply extensions/grpc/codegen/src/main/java/io/quarkus/grpc/deployment/GrpcCodeGen.java:280]: But yeah, I see your point.
It's good to have project-dir there, specially being 100% sure knowing where it points to.
And hence you can then have things like you described - placing things easily into `src/test/recources`, etc

Comment (edeandrea) [reply extensions/grpc/codegen/src/main/java/io/quarkus/grpc/deployment/GrpcCodeGen.java:280]: I thought this as well and tried to play around with just using `outDir()` (essentially the project's build dir), but then I kept thinking that it wouldn't be an unreasonable requirement to have some process generate these files and then commit to source control somewhere. Or do you think that requirement is unreasonable? Honestly I could argue it either way. I just thought this was more flexible in the end.

Supposedly there is `CodeGenContext.applicationModel().getApplicationModule()` which has `getModuleDir()`, which would provide this info, but during my testing I found that `CodeGenContext.applicationModel().getApplicationModule()` was always returning `null`.

This code is pretty unfamiliar to me and I couldn't figure out how/where it was getting constructed, so I opted for what I ended up doing.

Comment (edeandrea) [reply extensions/grpc/codegen/src/main/java/io/quarkus/grpc/deployment/GrpcCodeGen.java:280]: > Where does then `$context.outDir/..` point to, if not to the module's root?

From the docs: `context.outDir/..`would typically be resolved as `<project.build.directory>/generated-sources/<codegen-provider-id>`

Comment (alesj) [reply extensions/grpc/codegen/src/main/java/io/quarkus/grpc/deployment/GrpcCodeGen.java:280]: > but then I kept thinking that it wouldn't be an unreasonable requirement to have some process generate these files and then commit to source control somewhere. Or do you think that requirement is unreasonable? Honestly I could argue it either way. I just thought this was more flexible in the end.

Well, generating things directly into source dirs ... never really the best idea, but ... if it's needed it needed. :-)

> This code is pretty unfamiliar to me and I couldn't figure out how/where it was getting constructed, so I opted for what I ended up doing.

This is imho a question for @aloubyansky ...

Comment (edeandrea) [reply extensions/grpc/codegen/src/main/java/io/quarkus/grpc/deployment/GrpcCodeGen.java:280]: > Well, generating things directly into source dirs ... never really the best idea

Generally I would agree, but a descriptor set's intent is to be able to be used by code/tooling. Its a self-describing artifact of the entire contract.

Again, though, I could argue it either way, and generally when I'm in that situation I tend to make things as flexible as possible. But if people think it would be better to keep generated things in the build directory then I can re-work this a bit. It will certainly simplify the implementation.

Comment (edeandrea) [reply extensions/grpc/codegen/src/main/java/io/quarkus/grpc/deployment/GrpcCodeGen.java:280]: @cescoffier any thoughts?

Comment (cescoffier) [reply extensions/grpc/codegen/src/main/java/io/quarkus/grpc/deployment/GrpcCodeGen.java:280]: About the location of the generated descriptor, we must be sure the generation is idempotent, even when using different os/ machines...

Comment (edeandrea) [reply extensions/grpc/codegen/src/main/java/io/quarkus/grpc/deployment/GrpcCodeGen.java:280]: I guess by allowing it to be outside the build directory (`context.workDir`), then running a mvn/gradle `clean` will NOT remove it. Once its generated, its generated.

The more I think about it the more I think we should keep it confined to the `workDir` and not allow the generation outside of that. It is, after all, a generated resource and should be treated as such.

If you both (@cescoffier / @alesj ) are ok with that, I'll re-work this PR for that. It'll make it much simpler actually.

Comment (aloubyansky) [reply extensions/grpc/codegen/src/main/java/io/quarkus/grpc/deployment/GrpcCodeGen.java:280]: > Supposedly there is `CodeGenContext.applicationModel().getApplicationModule()` which has `getModuleDir()`, which would provide this info, but during my testing I found that `CodeGenContext.applicationModel().getApplicationModule()` was always returning `null`.
> 
> This code is pretty unfamiliar to me and I couldn't figure out how/where it was getting constructed, so I opted for what I ended up doing.

The module layout part of that API is, by default, initialized only in dev and test modes, since this is when we need to load classes and resources from the workspace instead of from the JARs.
However, it can be enabled for the package building mode too by enabling a project property. Perhaps it should always be available. There were other use-cases where this was necessary. The reason not to do that was to not waste time discovering the workspace.

**Review by aloubyansky — APPROVED** [review]

File: extensions/grpc/codegen/src/main/java/io/quarkus/grpc/deployment/GrpcCodeGen.java (hunk 2 above)
Comment (edeandrea) [reply extensions/grpc/codegen/src/main/java/io/quarkus/grpc/deployment/GrpcCodeGen.java:280]: Thank you for the info!

Comment (alesj) [reply extensions/grpc/codegen/src/main/java/io/quarkus/grpc/deployment/GrpcCodeGen.java:280]: > It is, after all, a generated resource and should be treated as such.

Exactly.
All other generated stuff goes there; 
e.g. proto sources, etc ... and tools (mostly) don't have problems with it.
Imho, this Wiremock should be flexible enough to handle this as well.

Comment (edeandrea) [reply extensions/grpc/codegen/src/main/java/io/quarkus/grpc/deployment/GrpcCodeGen.java]: I've made the change. I still have all the same integration tests, but now there is less code in the actual codebase that has changed. Just the `GrpcCodeGen` class.

**Comment by edeandrea** [comment]
@gsmet I'm not sure whats up with that Gradle integration test. I see it failing on other PRs as well, so I'm not sure I did anything here that would cause that failure.

**Comment by johannesctrl** [comment]
Hi, I appreciate the new feature of generating the descriptor file a lot because I would like to use this for WireMock. However, I am not able to generate it. While ...

- using Maven
- using Quarkus version 3.6.0.CR1
- adding `quarkus.generate-code.grpc.descriptor-set.generate=true` to my application.properties
- defining the goals "build", "generate-code" and "generate-code-tests"

I am getting the warning that the key cannot be found:
"[WARNING] [io.quarkus.config] Unrecognized configuration key "quarkus.generate-code.grpc.descriptor-set.generate" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo"

**Comment by edeandrea** [comment]
Hi @johannesctrl have you tried it with 3.6.0 (the released version)?

Using it with Wiremock is exactly why I did this PR in the first place :)

**Comment by edeandrea** [comment]
@johannesctrl I just added that to the [`grpc-locations` project within the Quarkus superheroes](https://github.com/quarkusio/quarkus-super-heroes/tree/main/grpc-locations) and I see that it was generated:

image

You can customize the name & location of the file by using the `quarkus.generate-code.grpc.descriptor-set.output-dir` and `quarkus.generate-code.grpc.descriptor-set.name` properties:

```yaml
quarkus:
  generate-code:
    grpc:
      descriptor-set:
        generate: true
        output-dir: .
        name: locationservice-v1.dsc
```

image

**Comment by johannesctrl** [comment]
Thank you so much for checking! :) Yes, I already tried the 3.6.0 version and also using the name and location properties. Maybe it's something else in my settings ... I'm gonna check all my settings again, I guess 😄
