### PR TITLE
Optimize OIDC code flow to do one less redirect when the original path has to be restored

### LINKED ISSUE #12756: OIDC with REST-endpoint using "code" query-parameter fails
**Describe the bug**
My service uses OIDC (type=web-app) and has a REST-API /hello?**code**=abc.
The **Query-Parameter code** conflicts with the OIDC authorization code flow.

```
DEBUG [io.qua.oid.run.CodeAuthenticationMechanism] (vert.x-eventloop-thread-13) The state cookie is missing after a redirect from IDP
```

**Expected behavior**
I can use any query-parameter name in my REST API without conflicting with OIDC extension.

**Actual behavior**
The REST API returns wrong response status code.

**To Reproduce**
Follow the steps in the README.md of
https://github.com/haraldatbmw/oidc-code-query-parameter

**Environment (please complete the following information):**
 - Quarkus version or git rev: 1.8.3.Final

### PR DESCRIPTION
**Pull request by sberyozkin**
OIDC `CodeAuthenticationMechanism` can restore the original request path, for example:
1. User does `GET /web-app/service`
2. Redirect path is configured as `/web-app`
3. The user, after authenticating, is redirected back to Quarkus to `/web-app`
4. Now, before proceeding with the code to token exchange, the user is redirected to `/web-app/service` thus restoring the original request URI; to implement it, a custom `pathChecked` query is added, so it is not ideal
5. Finally, after the code has been exchanged, another redirect follows, dropping `code` and `state` and other non-custom query parameters

So, step 4 is redundant, it adds to the cost of processing and also returns `code` and `state` back to the browser because the code flow has not completed yet.

As such this PR drops step 4 and the original path, if needed, will be restored as part of the last step

I had to fix a few tests because they were written around the flow involving step4.

### CODE REVIEW

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java [hunk 1]
```diff
@@ -278,13 +277,18 @@ private boolean shouldAutoRedirect(TenantConfigContext configContext, RoutingCon
                 // Local redirect restoring the original request path, the state cookie is no longer needed
                 removeCookie(context, configContext, getStateCookieName(configContext));
             }
+        } else if (configContext.oidcConfig.authentication.isChallengeWithoutStateCookie()) {
+            LOG.debug("The state cookie is missing after a redirect from IDP, re-authentication is required");
+            return Uni.createFrom().optional(Optional.empty());
         } else {
             // State cookie must be available to minimize the risk of CSRF
-            LOG.debug("The state cookie is missing after a redirect from IDP");
+            LOG.debug("The state cookie is missing after a redirect from IDP, authentication has failed");
```
Comment (pedroigor) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java:285]: Isn't just a matter of checking whether or not the state cookie was set and if not just redirect to the IdP ?

**Review by pedroigor — CHANGES_REQUESTED** [review]

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java (hunk 1 above)
Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java:285]: @pedroigor The current behaviour in Quarkus is what is happening in this branch in this PR, if the state cookie is absent when Quarkus OIDC thinks it is processing a code response from the IDP redirect then it must be 401. Without it we were getting a lot of reports of the browser going into the redirection loop :-) due to the cookie being lost after the redirect, the user is redirected back and the IDP redirects the user back again, etc, so it is a safety check which should remain a default option IMHO.
May be you meant a session cookie ? It is still the case that if it is not available then the user is redirected to IDP.

Comment (pedroigor) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java:285]: As you said, if the state cookie is absent it may think it is processing a code. But if the state cookie is not set, that means the code flow even started so we could just force the flow to start.

Maybe I should try this out and see if I'm missing something.

Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java:285]: Hi Pedro @pedroigor `if the state cookie is absent it may think it is processing a code. But if the state cookie is not set...` it is the same situation :-).
So, putting this PR aside for the moment, when we have a `code` parameter set we assume it is part of the code flow response and therefore we expect that the `state` cookie is present. If it is not present, then until this PR, it is 401 (risk of the redirect loops otheriwise if we return the user back to IDP again - typically it is happening when say you access `index.html` on the 1st request and then `/web-app/service` on the redirect from IDP, etc, and if no cookie path/domain property is set).
The only cookie which we have always used to decide whether to redirect to IDP or not, based on its presence/absence is the session cookie. We only use the state cookie to coordinate the code flow.

And with this PR, we have a situation where a code is coming on the 1st unauthenticated request, or, as it appears in the user case, after the session has expired, so yes, with the new option, we will give the users an option to redirect the users to IDP if the state cookie is absent to resolve the ambiguity with the custom `code` parameter vs a `code` returned by IDP.

Does it clarify it :-) ?

**Comment by sberyozkin** [comment]
@pedroigor Hey, I've spent a lot of time trying to make it work and came to the conclusion is that is impossible to avoid some hacks :-) and as such I'm going to close this PR, but the good news is, while refactoring the code to make it work I've managed to get rid of one local redirect where the original path is restored :-). so I'll update thos PR and its name a bit later

**Comment by sberyozkin** [comment]
@pedroigor Hey Pedro
I've completely re-focused the PR on optimizing the redirects, please see the description, it drops one redundant redirect which can only a good thing for the performance and the security of the flow too :-)

**Review by pedroigor — APPROVED** [review]
