### PR TITLE
Don't rely on the '--rm' flag for stopping containers in integration tests

### LINKED ISSUE #21101: Docker container is not stopped (on Windows) after integration test
### Describe the bug

Basic generated and downloaded quarkus project with jax-rs and quarkus-container-image-docker with some small alterations to the native tests to run on the build docker image works fine but fails to stop the docker image.

### Expected behavior

mvn clean verify 
Builds / tests 
Starts docker image 
Runs QuarkusIntegrationTest successful
Stops docker image

Steps are repeatable

### Actual behavior

mvn clean verify 
Builds / tests 
Starts docker image 
Runs QuarkusIntegrationTest successful
Docker image remains running

Steps are not repeatable because the docker image is still running.

### How to Reproduce?

1. Download standard build project with jax-rs and  quarkus-container-image-docker
2.  Add the following to the regular maven build:
```
      <plugin>
        <artifactId>maven-failsafe-plugin</artifactId>
        <version>${surefire-plugin.version}</version>
        <executions>
          <execution>
            <goals>
              <goal>integration-test</goal>
              <goal>verify</goal>
            </goals>
            <configuration>
              <systemPropertyVariables>
                <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
                <maven.home>${maven.home}</maven.home>
              </systemPropertyVariables>
            </configuration>
          </execution>
        </executions>
      </plugin>
```
3. In class NativeGreetingResourceIT change @NativeImageTest to @QuarkusIntegrationTest
4. Add the following to application.properties
```
quarkus.container-image.build=true
quarkus.container-image.group=org.acme
quarkus.container-image.name=code-with-quarkus
``` 
5. run mvn clean verify
6. Observe that docker image is still running

### Output of `uname -a` or `ver`

Windows 10 + Docker desktop 3.6.0

### Output of `java -version`

openjdk version "11.0.9.1" 2020-11-04 OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9.1+1) OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9.1+1, mixed mode)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.4.0 (but same under 2.3.1, 2.3.0 and earlier

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\Portable-dev\apache-maven-3.6.3\bin\..
Java version: 11.0.9.1, vendor: AdoptOpenJDK, runtime: C:\Portable-dev\jdk-11.0.9.1+1
Default locale: nl_NL, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
It seems that this flag is not very reliable on some cases in Windows,
so we just give the container a name and use that name to manually
stop the container.

Fixes: #21101

### CODE REVIEW

File: test-framework/common/src/main/java/io/quarkus/test/common/DefaultDockerContainerLauncher.java [hunk 1]
```diff
@@ -78,12 +84,14 @@ public void start() throws IOException {
         }
 
         List<String> args = new ArrayList<>();
-        args.add("docker"); // TODO: determine this dynamically?
+        args.add(DOCKER_BINARY); // TODO: determine this dynamically?
         args.add("run");
         if (!argLine.isEmpty()) {
             args.addAll(argLine);
         }
-        args.add("--rm");
```
Comment (stuartwdouglas) [inline test-framework/common/src/main/java/io/quarkus/test/common/DefaultDockerContainerLauncher.java:86]: Shouldn't we still keep `--rm` ? If there is an issue in the JVM process the cleanup command may not be run.

Comment (geoand) [reply test-framework/common/src/main/java/io/quarkus/test/common/DefaultDockerContainerLauncher.java:86]: Yeah, it won't hurt. I'll add it

Comment (geoand) [reply test-framework/common/src/main/java/io/quarkus/test/common/DefaultDockerContainerLauncher.java:86]: Added it back

File: test-framework/common/src/main/java/io/quarkus/test/common/DefaultDockerContainerLauncher.java [hunk 2]
```diff
@@ -59,7 +65,7 @@ public void start() throws IOException {
             System.out.println("Pulling container image '" + containerImage + "'");
             try {
                 int pullResult = new ProcessBuilder().redirectError(DISCARD).redirectOutput(DISCARD)
-                        .command(List.of("docker", "pull", containerImage).toArray(new String[0])).start().waitFor();
+                        .command(List.of(DOCKER_BINARY, "pull", containerImage).toArray(new String[0])).start().waitFor();
```
Comment (gastaldi) [inline test-framework/common/src/main/java/io/quarkus/test/common/DefaultDockerContainerLauncher.java:68]: Maybe this would look better? 

```suggestion
                        .command(DOCKER_BINARY, "pull", containerImage).start().waitFor();
```

File: test-framework/common/src/main/java/io/quarkus/test/common/DefaultDockerContainerLauncher.java [hunk 3]
```diff
@@ -163,7 +173,13 @@ private String convertPropertyToEnVar(String property) {
 
     @Override
     public void close() {
-        quarkusProcess.destroy();
+        try {
+            Process dockerStopProcess = new ProcessBuilder(List.of(DOCKER_BINARY, "stop", containerName)).redirectError(DISCARD)
```
Comment (gastaldi) [inline test-framework/common/src/main/java/io/quarkus/test/common/DefaultDockerContainerLauncher.java:177]: Same as above?

File: test-framework/common/src/main/java/io/quarkus/test/common/DefaultDockerContainerLauncher.java (hunk 2 above)
Comment (geoand) [reply test-framework/common/src/main/java/io/quarkus/test/common/DefaultDockerContainerLauncher.java]: Sure, done

**Review by gastaldi — APPROVED** [review]
