### PR TITLE
Qute - fix assignability check when validating expressions

### LINKED ISSUE #31077: Qute: regression in template extension method with byte array
### Describe the bug

During the bump from 2.16.0 to 2.16.1, the following template extension method stopped working:

```java
@TemplateExtension
public class JavaExtensions {

    public static String mimeType(byte[] bytes) {
        if (bytes == null || bytes.length == 0) {
            return null;
        }
        return FileUtils.getMimeType("", bytes);
    }

}
```

It now generates this at build time:

```
Caused by: java.lang.NullPointerException: Cannot invoke "org.jboss.jandex.ClassInfo.isInterface()" because "classInfo" is null
	at io.quarkus.qute.deployment.Types$AssignableInfo.from(Types.java:146)
	at io.quarkus.qute.deployment.Types.isAssignableFrom(Types.java:194)
	at io.quarkus.qute.deployment.Types.isAssignableFrom(Types.java:140)
	at io.quarkus.qute.deployment.QuteProcessor.findTemplateExtensionMethod(QuteProcessor.java:2377)
	at io.quarkus.qute.deployment.QuteProcessor.validateNestedExpressions(QuteProcessor.java:1246)
	at io.quarkus.qute.deployment.QuteProcessor.validateExpressions(QuteProcessor.java:860)
```

Due to looking up the class for `[B` in `Types.java`, where `className1` is `[B` and `className2` is `java.lang.String`

```java
    static boolean isAssignableFrom(DotName className1, DotName className2, IndexView index,
            Map<DotName, AssignableInfo> assignableCache) {
        // java.lang.Object is assignable from any type
        if (className1.equals(DotNames.OBJECT)) {
            return true;
        }
        // type1 is the same as type2
        if (className1.equals(className2)) {
            return true;
        }
        ClassInfo class1 = index.getClassByName(className1);
        AssignableInfo assignableInfo = assignableCache.get(className1);
        if (assignableInfo == null) {
            // No cached info
            assignableInfo = AssignableInfo.from(class1, index);
            assignableCache.put(className1, assignableInfo);
            return assignableInfo.isAssignableFrom(className2);
        } else {
            if (assignableInfo.isAssignableFrom(className2)) {
                return true;
            }
            // Cached info does not match - try to update the assignable info (a computing index is used)
            assignableInfo = AssignableInfo.from(class1, index);
            if (assignableInfo.isAssignableFrom(className2)) {
                // Update the cache
                assignableCache.put(className1, assignableInfo);
                return true;
            }
        }
        return false;
    }
```

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mkouba**
- fixes #31077

Follows-up on https://github.com/quarkusio/quarkus/pull/30593.

### CODE REVIEW

File: extensions/qute/deployment/src/main/java/io/quarkus/qute/deployment/Types.java [hunk 1]
```diff
@@ -133,10 +133,13 @@ static boolean containsTypeVariable(Type type) {
     }
 
     static boolean isAssignableFrom(Type type1, Type type2, IndexView index, Map<DotName, AssignableInfo> assignableCache) {
-        // TODO consider type params in assignability rules
-        if (type1.kind() == Kind.ARRAY && type2.kind() == Kind.ARRAY) {
-            return isAssignableFrom(type1.asArrayType().component(), type2.asArrayType().component(), index, assignableCache);
+        if (type1.kind() == Kind.ARRAY) {
```
Comment (FroMage) [inline extensions/qute/deployment/src/main/java/io/quarkus/qute/deployment/Types.java:136]: What if `type2` is an array and `type1` isn't?

**Review by FroMage — APPROVED** [review]

File: extensions/qute/deployment/src/main/java/io/quarkus/qute/deployment/Types.java (hunk 1 above)
Comment (mkouba) [reply extensions/qute/deployment/src/main/java/io/quarkus/qute/deployment/Types.java:136]: Then the method returns `false` ... see https://github.com/quarkusio/quarkus/pull/31112/files#diff-9fdf5c1c1f88f93d3b6b0d4e5f0ebb70b73d7309644b5a036ca9d012123f06e0R49.

**Review by gastaldi — APPROVED** [review]

File: extensions/qute/deployment/src/main/java/io/quarkus/qute/deployment/Types.java (hunk 1 above)
Comment (FroMage) [reply extensions/qute/deployment/src/main/java/io/quarkus/qute/deployment/Types.java:136]: OK :)
