### PR TITLE
Testing: add checks to QuarkusMock

### LINKED ISSUE #53051: QuarkusMock.installMock fails with ClassCastException in a Kotlin Gradle project
### Describe the bug

Quarkus version: `3.32.3`, `3.34.CR1`

When trying to replace an `ApplicationScoped` bean using `QuarkusMock.installMockForType(obj, Interface::class.java)` to supply a fake interface implementation in a `QuarkusTest`, the call fails with a `ClassCastException` because the captured bean type is not the parent interface, but its concrete production implementation, so a sibling test impl cannot be cast to it.

Documentation reference that led me to discover this error:
https://quarkus.io/guides/getting-started-testing#quarkus_mock

Based on the documentation I don't see any mistakes in the failing code.

--------

Reproduction is trivial: generate a quarkus project in the web generator with the following extensions: `quarkus-rest`, `kotlin`, build system: Gradle with Kotlin DSL, Java version: `17`

Add the following two files:

```kotlin
// src/main/kotlin/org/acme/service.kt
package org.acme

import jakarta.enterprise.context.ApplicationScoped

interface Interface

@ApplicationScoped
class ProdInterfaceImpl : Interface

@ApplicationScoped
class Service(
    private val iface: Interface
)
```

```kotlin
// src/test/kotlin/org/acme/ServiceTest.kt
package org.acme

import io.quarkus.test.junit.QuarkusMock
import io.quarkus.test.junit.QuarkusTest
import jakarta.inject.Inject
import org.junit.jupiter.api.Test

@QuarkusTest
class ServiceTest {

    @Inject
    lateinit var service: Service

    @Test
    fun testInterfaceReplacement() {
        QuarkusMock.installMockForType(TestInterfaceImpl(), Interface::class.java)
    }

    class TestInterfaceImpl : Interface
}
```

Running `testInterfaceReplacement` fails with the following:

```
org.acme.ProdInterfaceImpl@7c5d36c3 is not a normal scoped CDI bean, make sure the bean is a normal scope like @ApplicationScoped or @RequestScoped
java.lang.RuntimeException: org.acme.ProdInterfaceImpl@7c5d36c3 is not a normal scoped CDI bean, make sure the bean is a normal scope like @ApplicationScoped or @RequestScoped
	at io.quarkus.test.junit.MockSupport.installMock(MockSupport.java:63)
	at io.quarkus.test.junit.QuarkusMock.installMockForType(QuarkusMock.java:63)
	at org.acme.ServiceTest.testInterfaceReplacement(ServiceTest.kt:19)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:110)
	at java.base/java.lang.reflect.Method.invoke(Method.java:565)
	at io.quarkus.test.junit.MockSupport.installMock(MockSupport.java:54)
	... 2 more
Caused by: java.lang.ClassCastException: class org.acme.ServiceTest$TestInterfaceImpl cannot be cast to class org.acme.ProdInterfaceImpl (org.acme.ServiceTest$TestInterfaceImpl and org.acme.ProdInterfaceImpl are in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @44fdce3c)
	at org.acme.ProdInterfaceImpl_ClientProxy.arc$setMock(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	... 4 more```



### Expected behavior

I can supply a fake interface implementation to Quarkus in tests.

### Actual behavior

`QuarkusMock.installMockForType` fails with an exception

### PR DESCRIPTION
**Pull request by Ladicek**
The `QuarkusMock.installMock*()` methods used to implicitly require that the given mock is assignable to the bean class of the selected bean. However, only one of the methods attempted to check that, and the attempt was subtly buggy so that it could actually never fail.

This commit adds a proper check to all methods. Further, this commit adds a check that the given instance may in fact be mocked (that is: it is a client proxy, `Event`, or `MockedThroughWrapper`). Nearly the same check exists in `MockSupport`, so we wouldn't have to check it in `QuarkusMock`, but if we didn't, we could get a wrong bean class or we could allow something we know is going to fail. Let's just live with this duplication.

- Fixes: #53051

### CODE REVIEW

**Review by geoand — COMMENTED** [review]
Nice, thanks!

LGTM, but I'll defer approval to the expert :)

File: test-framework/junit/src/main/java/io/quarkus/test/junit/QuarkusMock.java [hunk 1]
```diff
@@ -2,90 +2,135 @@
...
+        Class<?> instanceClass;
+        if (instance instanceof MockedThroughWrapper) {
+            instanceClass = instance.getClass();
+            if (instanceClass.getName().endsWith("_ClientProxy")) {
+                // the condition is hideous, but we don't depend on ArC in this module
+                instanceClass = instanceClass.getSuperclass();
+            }
+            // only generated by RestClient Reactive, which always implements exactly 1 interface
+            instanceClass = instanceClass.getInterfaces()[0];
+        } else if (instance instanceof Event<?>) {
```
Comment (mkouba) [inline test-framework/junit/src/main/java/io/quarkus/test/junit/QuarkusMock.java:121]: Why is this needed?

Comment (Ladicek) [reply test-framework/junit/src/main/java/io/quarkus/test/junit/QuarkusMock.java:121]: Because events are also mockable.

Comment (mkouba) [reply test-framework/junit/src/main/java/io/quarkus/test/junit/QuarkusMock.java:121]: Ah, sure you can't use `io.quarkus.arc.impl.Mockable` here.

**Review by mkouba — APPROVED** [review]
I'm not an expert here but it looks good!
