### PR TITLE
Ensure that returning an InputStream from RESTEasy Reactive works in native

### LINKED ISSUE #26780: NoSuchMethodException in Resteasy-reactive when running in native mode (RestResponse<InputStream>)
### Describe the bug

I'm facing a similar issue to the one described in #25973 fixed by #26021.

In my case the method signature and annotations look like:
```java
  @GET
  @Path("/{fileName:.+}")
  public RestResponse<InputStream> getStaticFile(@PathParam("fileName") String fileName) throws IOException {
```

Maybe accounting for RestResponse/InputStream in [`ResteasyReactiveProcessor`](https://github.com/quarkusio/quarkus/blob/main/extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/ResteasyReactiveProcessor.java) might fix it :shrug:.

I can workaround this issue by annotation the affected class with `@RegisterForReflection`

### Expected behavior

No exception should be thrown, method should pipe an input stream to the response.

### Actual behavior

Fails with:
```
2022-07-18 11:59:15,376 ERROR [org.jbo.res.rea.com.cor.AbstractResteasyReactiveContext] (executor-thread-0) Request failed: java.lang.RuntimeException: java.lang.NoSuchMethodException: com.example.fullstack.GatewayResource.getFrontendStaticFile(java.lang.String)

```

### How to Reproduce?

https://github.com/marcnuri-demo/202207-quarkus-26780

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

OpenJDK Runtime Environment Temurin-17.0.1+12 (build 17.0.1+12)

### GraalVM version (if different from Java)

- quay.io/quarkus/ubi-quarkus-mandrel:21.3-java17
- quay.io/quarkus/ubi-quarkus-mandrel:22.1-java17

### Quarkus version or git rev

<=2.10.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #26780

### CODE REVIEW

File: independent-projects/resteasy-reactive/common/runtime/src/main/java/org/jboss/resteasy/reactive/common/providers/serialisers/InputStreamMessageBodyHandler.java [hunk 1]
```diff
@@ -26,9 +26,17 @@ public boolean isWriteable(Class<?> type, Type genericType, Annotation[] annotat
...
+        return InputStream.class.isAssignableFrom(type);
+    }
+
     @Override
     public void writeTo(InputStream inputStream, Class<?> type, Type genericType, Annotation[] annotations, MediaType mediaType,
             MultivaluedMap<String, Object> httpHeaders, OutputStream entityStream) throws IOException, WebApplicationException {
+        doIsWriteable(inputStream, entityStream);
+    }
+
+    protected void doIsWriteable(InputStream inputStream, OutputStream entityStream) throws IOException {
```
Comment (gastaldi) [inline independent-projects/resteasy-reactive/common/runtime/src/main/java/org/jboss/resteasy/reactive/common/providers/serialisers/InputStreamMessageBodyHandler.java:39]: This method name doesn't sound right. How about `writeTo(InputStream,OutputStream)`?

File: independent-projects/resteasy-reactive/common/runtime/src/main/java/org/jboss/resteasy/reactive/common/providers/serialisers/InputStreamMessageBodyHandler.java [hunk 2]
```diff
@@ -26,9 +26,17 @@ public boolean isWriteable(Class<?> type, Type genericType, Annotation[] annotat
         return InputStream.class.isAssignableFrom(type);
     }
 
+    protected boolean doIsWriteable(Class<?> type) {
+        return InputStream.class.isAssignableFrom(type);
```
Comment (gastaldi) [inline independent-projects/resteasy-reactive/common/runtime/src/main/java/org/jboss/resteasy/reactive/common/providers/serialisers/InputStreamMessageBodyHandler.java:30]: I think we can name it `isInputStream(Class<?>)` since that seems to be the intention of this method :)

**Review by gastaldi — COMMENTED** [review]
Looks good, added a few comments about the method names

File: independent-projects/resteasy-reactive/common/runtime/src/main/java/org/jboss/resteasy/reactive/common/providers/serialisers/InputStreamMessageBodyHandler.java (hunk 2 above)
Comment (gastaldi) [reply independent-projects/resteasy-reactive/common/runtime/src/main/java/org/jboss/resteasy/reactive/common/providers/serialisers/InputStreamMessageBodyHandler.java:30]: Actually I think this method is not needed and you can call the one-liner directly

**Comment by geoand** [comment]
@gastaldi thanks for spotting the issues! Fixed now

File: independent-projects/resteasy-reactive/common/runtime/src/main/java/org/jboss/resteasy/reactive/common/providers/serialisers/InputStreamMessageBodyHandler.java [hunk 3]
```diff
@@ -23,12 +23,20 @@ public InputStream readFrom(Class<InputStream> type, Type genericType, Annotatio
...
         return InputStream.class.isAssignableFrom(type);
     }
 
     @Override
     public void writeTo(InputStream inputStream, Class<?> type, Type genericType, Annotation[] annotations, MediaType mediaType,
             MultivaluedMap<String, Object> httpHeaders, OutputStream entityStream) throws IOException, WebApplicationException {
+        doWriteTo(inputStream, entityStream);
+    }
+
+    protected void doWriteTo(InputStream inputStream, OutputStream entityStream) throws IOException {
```
Comment (gastaldi) [inline independent-projects/resteasy-reactive/common/runtime/src/main/java/org/jboss/resteasy/reactive/common/providers/serialisers/InputStreamMessageBodyHandler.java:39]: Do we really need the `do` prefix here?

File: independent-projects/resteasy-reactive/common/runtime/src/main/java/org/jboss/resteasy/reactive/common/providers/serialisers/InputStreamMessageBodyHandler.java [hunk 4]
```diff
@@ -23,12 +23,20 @@ public InputStream readFrom(Class<InputStream> type, Type genericType, Annotatio
 
     @Override
     public boolean isWriteable(Class<?> type, Type genericType, Annotation[] annotations, MediaType mediaType) {
+        return doWriteTo(type);
+    }
+
+    protected boolean doWriteTo(Class<?> type) {
```
Comment (gastaldi) [inline independent-projects/resteasy-reactive/common/runtime/src/main/java/org/jboss/resteasy/reactive/common/providers/serialisers/InputStreamMessageBodyHandler.java:29]: Sorry for not being clear in the first time, but because of the triviality of this method, I think it is not needed and you can do `InputStream.isAssignableFrom(class)` in the subclasses. 

Sorry for nitpicking :)

File: independent-projects/resteasy-reactive/common/runtime/src/main/java/org/jboss/resteasy/reactive/common/providers/serialisers/InputStreamMessageBodyHandler.java (hunk 3 above)
Comment (geoand) [reply independent-projects/resteasy-reactive/common/runtime/src/main/java/org/jboss/resteasy/reactive/common/providers/serialisers/InputStreamMessageBodyHandler.java:39]: That's how I usually disambiguate :)

File: independent-projects/resteasy-reactive/common/runtime/src/main/java/org/jboss/resteasy/reactive/common/providers/serialisers/InputStreamMessageBodyHandler.java (hunk 4 above)
Comment (geoand) [reply independent-projects/resteasy-reactive/common/runtime/src/main/java/org/jboss/resteasy/reactive/common/providers/serialisers/InputStreamMessageBodyHandler.java]: Should be a little better now :)

File: independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/providers/serialisers/ServerInputStreamMessageBodyHandler.java [hunk 5]
```diff
@@ -33,4 +34,15 @@ public long getSize(InputStream inputStream, Class<?> type, Type genericType, An
         return -1;
     }
 
+    @Override
+    public boolean isWriteable(Class<?> type, Type genericType, ResteasyReactiveResourceInfo target,
+            MediaType mediaType) {
+        return super.isWriteable(type, null, null, null);
```
Comment (gastaldi) [inline independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/providers/serialisers/ServerInputStreamMessageBodyHandler.java:40]: I'd just do `InputStream.isAssignableFrom(type)` here but that's okay 😉

**Review by gastaldi — APPROVED** [review]

File: independent-projects/resteasy-reactive/common/runtime/src/main/java/org/jboss/resteasy/reactive/common/providers/serialisers/InputStreamMessageBodyHandler.java [hunk 6]
```diff
@@ -29,6 +29,10 @@ public boolean isWriteable(Class<?> type, Type genericType, Annotation[] annotat
     @Override
     public void writeTo(InputStream inputStream, Class<?> type, Type genericType, Annotation[] annotations, MediaType mediaType,
             MultivaluedMap<String, Object> httpHeaders, OutputStream entityStream) throws IOException, WebApplicationException {
+        writeTo(inputStream, entityStream);
+    }
+
+    protected void writeTo(InputStream inputStream, OutputStream entityStream) throws IOException {
         try {
             byte[] buffer = new byte[8192];
             int c;
```
[the remark this answers is not in the document]
Comment (geoand) [reply independent-projects/resteasy-reactive/common/runtime/src/main/java/org/jboss/resteasy/reactive/common/providers/serialisers/InputStreamMessageBodyHandler.java:38]: Good point. We probably have a few places where this can be applied.

I'll have a look over the next few days
