### PR TITLE
Wait until the OIDC endpoint is actually available

### LINKED ISSUE #18089: OIDC: Wait for actual realm
## Description

`quarkus.oidc.connection-delay` can be used to wait (a longer time) for IDP availability (Keycloak in my case).
This delay does unfortunately _not_ wait for the actual realm endpoint to become available.
If Keycloak (KC) starts at about the same time as Quarkus and imports the respective real via the entrypoint script, then Quarkus will finish waiting too early, will end up with missing tenant config and will throw an exception saying `Tenant configuration has not been resolved` for each request that is issued.

## Implementation ideas

https://github.com/quarkusio/quarkus/blob/901c30cc171c98954a8305cc0dcab1aa52433d3b/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcRecorder.java#L315
Instead of returning `null` on 404, either wait for 200 by default or introduce a property to fine-tune the expected behavior.

### PR DESCRIPTION
**Pull request by sberyozkin**
Fixes #18089.

This PR makes sure that the `connection-delay` is used until the OIDC endpoint is actually available:
- condition for the failure has changed - it is either `ConnectException` or a newly introduced `OidcTokenAccessException` with `404` - the actual realm resource must be available
- until now the `connection-delay` was only applicable for the auto-discovery case - but not when discovery was disabled - so I added the same failure handling when an initial JWK set is retrieved and the discovery is not enabled
- The changes apply to both `quarkus-oidc` and `quarkus-oidc-client` - so the other changes are about making some code reusable (to do with the auto-discovery, and connection-delay checks)

CC @famod

### CODE REVIEW

File: extensions/oidc-common/runtime/src/main/java/io/quarkus/oidc/common/runtime/OidcCommonUtils.java [hunk 1]
```diff
@@ -23,16 +28,22 @@
...
+import io.smallrye.mutiny.Uni;
 import io.vertx.core.http.HttpClientOptions;
 import io.vertx.core.json.JsonObject;
 import io.vertx.core.net.ProxyOptions;
 import io.vertx.mutiny.core.MultiMap;
 import io.vertx.mutiny.core.buffer.Buffer;
+import io.vertx.mutiny.ext.web.client.WebClient;
 
 public class OidcCommonUtils {
+    public static final Duration CONNECTION_BACKOFF_DURATION = Duration.ofSeconds(2);
```
Comment (pedroigor) [inline extensions/oidc-common/runtime/src/main/java/io/quarkus/oidc/common/runtime/OidcCommonUtils.java:40]: Wondering if people are not going to ask for making this configurable. But I guess you want to wait for it.

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcRecorder.java [hunk 2]
```diff
@@ -246,6 +243,18 @@ public OidcProvider apply(JsonWebKeyCache jwks) {
                 });
     }
 
+    protected static Uni<JsonWebKeyCache> getJsonWebCacheUni(OidcProviderClient client, OidcTenantConfig oidcConfig) {
```
Comment (pedroigor) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcRecorder.java:246]: Perhaps `getJsonWebKeySetUni`?

**Review by pedroigor — APPROVED** [review]

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcRecorder.java (hunk 2 above)
Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcRecorder.java]: @pedroigor hey Pedro, yes, I renamed it this way and also an internal  `JsonWebKeyCache` to `JsonWebKeySet`; when I named it `JsonWebKeyCache` I meant to convey it was a local JWK set cache but it is a JWK set after all :-), internally it used Jose4j `JsonWebKeySet` as well

File: extensions/oidc-common/runtime/src/main/java/io/quarkus/oidc/common/runtime/OidcCommonUtils.java (hunk 1 above)
Comment (sberyozkin) [reply extensions/oidc-common/runtime/src/main/java/io/quarkus/oidc/common/runtime/OidcCommonUtils.java:44]: @pedroigor yeah; it was like this from the very early days of `quarkus-oidc`, and no one asked for the delay between retries be configurable, I can surely make it configurable if someone finds it can be useful :-).
