### PR TITLE
Fix GraalVM version parsing for JDK 26-based builds

### LINKED ISSUE #48403: [NativeImageBuildStep] Unable to parse GraalVM for JDK 26
We see new native-image integration tests failing because Quarkus isn't able to parse the following JDK 26-based GraalVM version:

```
$ native-image --version
native-image 26 2026-03-17
GraalVM Runtime Environment GraalVM CE 26-dev+1.1 (build 26+1-jvmci-b01)
Substrate VM GraalVM CE 26-dev+1.1 (build 26+1, serial gc)
```

This results in the `picocli-native` integration test to fail with an error along the lines of this:

```
[INFO] --- quarkus:999-SNAPSHOT:track-config-changes (track-config-changes) @ quarkus-integration-test-picocli-native ---
[INFO] 
[INFO] --- compiler:3.14.0:compile (default-compile) @ quarkus-integration-test-picocli-native ---
[INFO] Recompiling the module because of changed source code.
[INFO] Compiling 21 source files with javac [debug deprecation parameters release 17] to target/classes
[INFO] 
[INFO] --- resources:3.3.1:testResources (default-testResources) @ quarkus-integration-test-picocli-native ---
[INFO] skip non existing resourceDirectory /home/sgehwolf/Documents/openjdk/quarkus/quarkus-source/integration-tests/picocli-native/src/test/resources
[INFO] 
[INFO] --- compiler:3.14.0:testCompile (default-testCompile) @ quarkus-integration-test-picocli-native ---
[INFO] Recompiling the module because of changed dependency.
[INFO] Compiling 4 source files with javac [debug deprecation parameters release 17] to target/test-classes
[INFO] 
[INFO] --- surefire:3.5.3:test (default-test) @ quarkus-integration-test-picocli-native ---
[INFO] Skipped
[INFO] 
[INFO] --- quarkus:999-SNAPSHOT:build (default) @ quarkus-integration-test-picocli-native ---
[INFO] [quarkus-build-caching-extension] Quarkus previous configuration not found
[INFO] [quarkus-build-caching-extension] Quarkus build goal marked as not cacheable
[INFO] [quarkus-build-caching-extension] Quarkus previous configuration not found
[INFO] [quarkus-build-caching-extension] Quarkus build goal marked as not cacheable
[INFO] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Building native image source jar: /home/sgehwolf/Documents/openjdk/quarkus/quarkus-source/integration-tests/picocli-native/target/quarkus-integration-test-picocli-native-999-SNAPSHOT-native-image-source-jar/quarkus-integration-test-picocli-native-999-SNAPSHOT-runner.jar
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Building native image from /home/sgehwolf/Documents/openjdk/quarkus/quarkus-source/integration-tests/picocli-native/target/quarkus-integration-test-picocli-native-999-SNAPSHOT-native-image-source-jar/quarkus-integration-test-picocli-native-999-SNAPSHOT-runner.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.801 s
[INFO] Finished at: 2025-06-16T12:09:32+02:00
[INFO] ------------------------------------------------------------------------
[INFO] Njord session closed
[INFO] 14 goals, 14 executed
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:build (default) on project quarkus-integration-test-picocli-native: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: java.lang.RuntimeException: Failed to get GraalVM version
[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildRunner.getGraalVMVersion(NativeImageBuildRunner.java:41)
[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:246)
[ERROR] 	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:735)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:255)
[ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2651)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2630)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1622)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1589)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:1474)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] Caused by: java.lang.NumberFormatException: For input string: "null"
[ERROR] 	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
[ERROR] 	at java.base/java.lang.Integer.parseInt(Integer.java:565)
[ERROR] 	at java.base/java.lang.Integer.parseInt(Integer.java:662)
[ERROR] 	at java.base/java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:231)
[ERROR] 	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
[ERROR] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:570)
[ERROR] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)
[ERROR] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:635)
[ERROR] 	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:291)
[ERROR] 	at java.base/java.util.stream.IntPipeline.toArray(IntPipeline.java:564)
[ERROR] 	at io.quarkus.runtime.graal.GraalVM$Version.breakdownVersion(GraalVM.java:127)
[ERROR] 	at io.quarkus.runtime.graal.GraalVM$Version.<init>(GraalVM.java:116)
[ERROR] 	at io.quarkus.deployment.pkg.steps.GraalVM$Version.<init>(GraalVM.java:229)
[ERROR] 	at io.quarkus.deployment.pkg.steps.GraalVM$VersionParseHelper.parse(GraalVM.java:89)
[ERROR] 	at io.quarkus.deployment.pkg.steps.GraalVM$Version.of(GraalVM.java:279)
[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildRunner.getGraalVMVersion(NativeImageBuildRunner.java:38)
[ERROR] 	... 11 more
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

We also see similar failures in our Mandrel CI here:
https://github.com/graalvm/mandrel/actions/runs/15646482173/job/44085716121#step:12:455

### PR DESCRIPTION
**Pull request by jerboaa**
JDK 26+ based GraalVM builds won't have a version mapping any more. They use the JDK version scheme instead. This also fixes an issue with wrong JDK versions being detected with `io.quarkus.runtime.graal.GraalVM.Version.getCurrent()` API and adds tests for it.

**Testing**
- [x] Ran various native integration tests with various Mandrel/GraalVM builds (including JDK 26). All pass.
- [x] Unit tests in `GraalVMTest.java`

- Closes: #48403

### CODE REVIEW

File: core/deployment/src/test/java/io/quarkus/deployment/pkg/steps/GraalVMTest.java [hunk 1]
```diff
@@ -184,6 +211,38 @@ public void testGraalVMVersionsOlderThan() {
...
+        // Mandrel
+        System.setProperty(GRAALVM_VENDOR_VERSION_PROP, "Mandrel-24.2.1.0-Final");
+        v = io.quarkus.runtime.graal.GraalVM.Version.getCurrent();
+        Assertions.assertEquals("24.2", v.getMajorMinorAsString());
+        Assertions.assertEquals(24, v.javaVersion.feature());
+        System.setProperty(GRAALVM_VENDOR_VERSION_PROP, "Mandrel-23.1.7.0-1b2");
+        v = io.quarkus.runtime.graal.GraalVM.Version.getCurrent();
+        Assertions.assertEquals("23.1", v.getMajorMinorAsString());
+        Assertions.assertEquals(21, v.javaVersion.feature());
+        Assertions.assertEquals(7, v.javaVersion.update());
```
Comment (zakkak) [inline core/deployment/src/test/java/io/quarkus/deployment/pkg/steps/GraalVMTest.java]: I sugggest using `@ParameterizedTest` like in the tests `testJDKVersion` and `testJDKVersionCompare` to avoid code duplication.

File: core/runtime/src/main/java/io/quarkus/runtime/graal/GraalVM.java [hunk 2]
```diff
@@ -80,6 +80,12 @@ public static class Version implements Comparable<Version> {
                 "23", "24.1",
                 "24", "24.2",
                 "25", "25.0");
```
Comment (zakkak) [inline core/runtime/src/main/java/io/quarkus/runtime/graal/GraalVM.java]: I believe we need to drop this as well:

```suggestion
                "24", "24.2");
```

File: core/runtime/src/main/java/io/quarkus/runtime/graal/GraalVM.java [hunk 3]
```diff
@@ -97,14 +103,17 @@ public static class Version implements Comparable<Version> {
...
         protected final String fullVersion;
         public final Runtime.Version javaVersion;
         protected final Distribution distribution;
         private int[] versions;
         private String suffix;
 
         Version(String fullVersion, String version, Distribution distro) {
-            this(fullVersion, version, "21", distro);
+            // FIXME: The hard-coded JDK version is probably wrong for liberica NIK builds
+            // that use JDKs higher than JDK 21
```
Comment (zakkak) [inline core/runtime/src/main/java/io/quarkus/runtime/graal/GraalVM.java]: Liberica uses the same versioning scheme with Mandrel so we can use `mandrelJDKvers` for it as well (potentially renaming `mandrel*` to `community*` or similar):

```
❯ ~/.sdkman/candidates/java/23.0.8.r17-nik/bin/native-image --version
native-image 17.0.15 2025-04-15
GraalVM Runtime Environment Liberica-NIK-23.0.8-1 (build 17.0.15+10-LTS)
Substrate VM Liberica-NIK-23.0.8-1 (build 17.0.15+10-LTS, serial gc)

❯ ~/.sdkman/candidates/java/23.0.5.r17-mandrel/bin/native-image --version 
native-image 17.0.12 2024-07-16
OpenJDK Runtime Environment Mandrel-23.0.5.0-Final (build 17.0.12+7)
OpenJDK 64-Bit Server VM Mandrel-23.0.5.0-Final (build 17.0.12+7, mixed mode)

❯ ~/.sdkman/candidates/java/23.1.7.r21-nik/bin/native-image --version 
native-image 21.0.7 2025-04-15
GraalVM Runtime Environment Liberica-NIK-23.1.7-1 (build 21.0.7+9-LTS)
Substrate VM Liberica-NIK-23.1.7-1 (build 21.0.7+9-LTS, serial gc)

❯ ~/.sdkman/candidates/java/23.1.6.r21-mandrel/bin/native-image --version 
native-image 21.0.6 2025-01-21
OpenJDK Runtime Environment Mandrel-23.1.6.0-Final (build 21.0.6+7-LTS)
OpenJDK 64-Bit Server VM Mandrel-23.1.6.0-Final (build 21.0.6+7-LTS, mixed mode)

❯ ~/.sdkman/candidates/java/24.2.1.r24-mandrel/bin/native-image --version 
native-image 24.0.1 2025-04-15
OpenJDK Runtime Environment Mandrel-24.2.1.0-Final (build 24.0.1+9)
OpenJDK 64-Bit Server VM Mandrel-24.2.1.0-Final (build 24.0.1+9, mixed mode)

❯ ~/.sdkman/candidates/java/24.2.1.r24-nik/bin/native-image --version
native-image 24.0.1 2025-04-15
GraalVM Runtime Environment Liberica-NIK-24.2.1-1 (build 24.0.1+11)
Substrate VM Liberica-NIK-24.2.1-1 (build 24.0.1+11, serial gc)
```

File: core/runtime/src/main/java/io/quarkus/runtime/graal/GraalVM.java [hunk 4]
```diff
@@ -80,6 +80,12 @@ public static class Version implements Comparable<Version> {
                 "23", "24.1",
                 "24", "24.2",
                 "25", "25.0");
+        private static final Map<String, String> MANDREL_JDK_REV_MAP = Map.of(
+                "23.1", "21",
+                "24.0", "22",
+                "24.1", "23",
+                "24.2", "24",
+                "25.0", "25");
```
Comment (zakkak) [inline core/runtime/src/main/java/io/quarkus/runtime/graal/GraalVM.java]: Since this is the inverse of `GRAAL_MAPPING` I suggest we either:

1. Construct one based on the other
2. Keep only one of them and retrieve the key by looking up the value for the other use case.

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/GraalVM.java [hunk 5]
```diff
@@ -67,7 +66,7 @@ static Version parse(List<String> lines) {
 
                 String vendorVersion = secondMatcher.group(VENDOR_VERSION_GROUP);
 
-                String graalVersion = graalVersion(javaVersion, v.feature());
+                String graalVersion = graalVersion(javaVersion, v.feature(), v.interim(), v.update());
```
Comment (zakkak) [inline core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/GraalVM.java]: I think it will be cleaner if we just pass `v` as an option.

```suggestion
                String graalVersion = graalVersion(javaVersion, v);
```

File: core/runtime/src/main/java/io/quarkus/runtime/graal/GraalVM.java [hunk 6]
```diff
@@ -127,6 +136,27 @@ private void breakdownVersion(String version) {
...
+                    String mandrelMajorMinor = String.format("%s.%s", parts[0], parts[1]);
+                    // If we don't find a reverse mapping we use a JDK version >= 25, thus
+                    // the feature version is the first part of the quadruple.
+                    String feature = MANDREL_JDK_REV_MAP.getOrDefault(mandrelMajorMinor, parts[0]);
+                    // Heuristic: The update version of Mandrel and the JDK match.
+                    // Interim is usually 0 for the JDK version.
+                    return String.format("%s.%s.%s", feature, "0", parts[2]);
+                }
+            } catch (Throwable e) {
+                // fall-through do default
```
Comment (zakkak) [inline core/runtime/src/main/java/io/quarkus/runtime/graal/GraalVM.java:173]: I wonder if it would be worth printing a warning in this case.

**Review by zakkak — CHANGES_REQUESTED** [review]
Thank you @jerboaa 

Looks good to me but I think we should handle Liberica NIK the same way we handle Mandrel.

I added a few suggestions/minor comments for your consideration as well.

File: core/runtime/src/main/java/io/quarkus/runtime/graal/GraalVM.java (hunk 3 above)
Comment (jerboaa) [reply core/runtime/src/main/java/io/quarkus/runtime/graal/GraalVM.java]: OK.

File: core/runtime/src/main/java/io/quarkus/runtime/graal/GraalVM.java (hunk 2 above)
Comment (jerboaa) [reply core/runtime/src/main/java/io/quarkus/runtime/graal/GraalVM.java]: Sure.

File: core/deployment/src/test/java/io/quarkus/deployment/pkg/steps/GraalVMTest.java (hunk 1 above)
Comment (jerboaa) [reply core/deployment/src/test/java/io/quarkus/deployment/pkg/steps/GraalVMTest.java]: OK.

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/GraalVM.java (hunk 5 above)
Comment (jerboaa) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/GraalVM.java]: Makes sense.

File: core/runtime/src/main/java/io/quarkus/runtime/graal/GraalVM.java (hunk 6 above)
Comment (jerboaa) [reply core/runtime/src/main/java/io/quarkus/runtime/graal/GraalVM.java:173]: I can add that. No strong feelings about this either way.

File: core/runtime/src/main/java/io/quarkus/runtime/graal/GraalVM.java (hunk 4 above)
Comment (jerboaa) [reply core/runtime/src/main/java/io/quarkus/runtime/graal/GraalVM.java]: Went with option 1)

**Comment by jerboaa** [comment]
@zakkak How does the latest version look to you? Thanks!

**Review by zakkak — APPROVED** [review]
LGTM, thanks @jerboaa !
