### PR TITLE
Declare input for quarkusGenerateCode gradle task

### LINKED ISSUE #16661: QuarkusGenerateCode gradle task is not incremental
## Describe the bug

When running `quarkusBuild` or `quarkusDev`, it triggers `quarkusGenerateCode` task. This tasks is always ran, even when no change happen.

### Expected behavior
The task should be `UP-TO-DATE`, if no changes happen to 

 
### Actual behavior
The task always is always ran

## To Reproduce

1. Create a simple project 
2. run `./gradlew quarkusBuild` multiple times, it never will be `UP-TO-DATE`.

### PR DESCRIPTION
**Pull request by glefloch**
This declares the following directories as task input:

- `src/main/avro`
- `src/main/proto`
- `src/test/avro`
- `src/test/proto`

This allows to the task to be detected as `UP-TO-DATE` by gradle.

close #16661

### CODE REVIEW

File: devtools/gradle/src/main/java/io/quarkus/gradle/tasks/QuarkusGenerateCode.java [hunk 1]
```diff
@@ -53,6 +57,20 @@ public FileCollection getClasspath() {
...
+    @OutputFiles
+    @org.gradle.api.tasks.Optional
+    public Set<File> getGeneratedSourceDirectory() {
+        Set<File> sourcesDirectories = new HashSet<>();
+        Path src = getProject().getProjectDir().toPath().resolve("src");
+        Path mainSrc = src.resolve(SourceSet.MAIN_SOURCE_SET_NAME);
+        Path testSrc = src.resolve(SourceSet.TEST_SOURCE_SET_NAME);
+        for (String codeGenerationSource : CODE_GENERATION_SOURCES) {
+            sourcesDirectories.add(mainSrc.resolve(codeGenerationSource).toFile());
+            sourcesDirectories.add(testSrc.resolve(codeGenerationSource).toFile());
```
Comment (aloubyansky) [inline devtools/gradle/src/main/java/io/quarkus/gradle/tasks/QuarkusGenerateCode.java:69]: Would it makes sense to check whether these paths exist before adding them?

Comment (aloubyansky) [reply devtools/gradle/src/main/java/io/quarkus/gradle/tasks/QuarkusGenerateCode.java:69]: Or would it be too early at this point?

Comment (glefloch) [reply devtools/gradle/src/main/java/io/quarkus/gradle/tasks/QuarkusGenerateCode.java:69]: No I think that's doable. I will need to do some refactoring, the generated code is not the default source set location (we have a subfolder per type of file: proto, avdl, ...) and thus, each generated java file needs to be registered to the compileJava task which is not the case when the task is `UP-TO-DATE`..

**Comment by glefloch** [comment]
@aloubyansky I updated the code to declare both input and output. I also check if the path exists before adding it to the `Set`

**Comment by gsmet** [comment]
@glefloch failures look related?

**Comment by glefloch** [comment]
Yes I need to update the assertions for two of the three failures and look at the third one.

**Comment by glefloch** [comment]
@aloubyansky could you have a look at this one? this should help fixing #13882 as generated source directory will be available from `main` sourceSet

**Review by aloubyansky — APPROVED** [review]
Sorry, I thought I approved it before. Thanks @glefloch
