### PR TITLE
Propagate the javax.annotation.security annotations in REST Data

### LINKED ISSUE #28995: PanacheEntityResource not propagating javax.annotation.security
### security is not respected

we have custom endpoints and generated one with PanacheEntityResource.

all have security annotations. the security has no effect on PanacheEntityResource:

Pasted Graphic 1

@DenyAll but is still reachable:

Pasted Graphic 4

### Expected behavior

work like intended as on the custom resources

### Actual behavior

security is not respected

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Sgitario**
With these changes, the REST Data with Panache extension will propagate the Security annotations within the package `javax.annotation.security` that are defined on your resource interfaces:

```java
import javax.annotation.security.DenyAll;
import javax.annotation.security.RolesAllowed;

@DenyAll
@ResourceProperties
public interface PeopleResource extends PanacheEntityResource<Person, Long> {
    @RolesAllowed("superuser")
    boolean delete(Long id);
}
```

Additionally, if you are only interested in specifying the roles that are allowed to use the resources, the `@ResourceProperties` and `@MethodProperties` annotations have the field `rolesAllowed` to list the security roles permitted to access the resource or operation.

Fix https://github.com/quarkusio/quarkus/issues/28995

### CODE REVIEW

**Comment by Sgitario** [comment]
cc @geoand @punkratz312

**Review by geoand — APPROVED** [review]

**Comment by sberyozkin** [comment]
@Sgitario Hi Jose, can you please add a small section to the main `security.adoc` to link back to the rest-panache doc, for example, just next to https://quarkus.io/guides/security#secure-serialization

File: extensions/panache/rest-data-panache/deployment/src/main/java/io/quarkus/rest/data/panache/deployment/properties/ResourcePropertiesProvider.java [hunk 1]
```diff
@@ -19,6 +23,8 @@ public class ResourcePropertiesProvider {
     private static final DotName METHOD_PROPERTIES_ANNOTATION = DotName.createSimple(
             io.quarkus.rest.data.panache.MethodProperties.class.getName());
 
+    private static final List<String> ANNOTATIONS_TO_COPY = List.of("javax.annotation.security");
```
Comment (gsmet) [inline extensions/panache/rest-data-panache/deployment/src/main/java/io/quarkus/rest/data/panache/deployment/properties/ResourcePropertiesProvider.java:26]: Could you make it `RolesAllowed.class.getPackageName()`. I'd like to make sure it's rewritten by the Jakarta scripts.

**Review by gsmet — CHANGES_REQUESTED** [review]

**Comment by Sgitario** [comment]
> @Sgitario Hi Jose, can you please add a small section to the main `security.adoc` to link back to the rest-panache doc, for example, just next to https://quarkus.io/guides/security#secure-serialization

Added

**Review by gsmet — APPROVED** [review]

**Comment by sberyozkin** [comment]
Thanks @Sgitario, we have various security features supported across different extensions, so it makes sense to have a map of all of them in one place :-)

**Comment by punkratz312** [comment]
thanks for fast response

**Review by geoand — APPROVED** [review]
