### PR TITLE
ArC - distinguish "bean archive" and "additional" index

### LINKED ISSUE #11863: Generic Type arguments of producer method needs to be in a bean archive
**Describe the bug**
I have a setup like this:
A producer that produces something with a generic type argument

```
@ApplicationScoped
public class BusinessObjectContainerProducer {

    @Produces
    @Dependent
    public <T extends BusinessObject> BusinessObjectContainer<T> produceProducer(InjectionPoint injectionPoint) {
        //Details ommitted
        // ParameterizedType targetType = (ParameterizedType) injectionPoint.getType();
        // Type[] targetTypeArgs = targetType.getActualTypeArguments();
        // ...
        return new BusinessObjectContainer<T>() {

            @Override
            public void set(T bo) {
                //
            }
        };
    }
}
```
I have some concrete type "SpecificBusinessObject extends BusinessObject" where I inject the BusinessObjectContainer with the concrete type argument:

```
@Inject
BusinessObjectContainer<SpecificBusinessObject> container;
```
Just for completeness; the container looks like this:

```
public interface BusinessObjectContainer<T extends BusinessObject> {
    void set(T bo);
}
```

All classes are part of the main quarkus application except SpecificBusinessObject and BusinessObject. They are defined in an external jar that does not contain a beans.xml (it does not contain any CDI beans).

**Expected behavior**
It should work; no error on quarkusBuild. As the external jar does not contain any CDI beans, there should not be the need to add a beans.xml.

**Actual behavior**

```
Caused by: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.acme.BusinessObjectContainer<org.acme.SpecificBusinessObject> and qualifiers [@Default]
- java member: org.acme.ExampleResource#container
- declared on CLASS bean [types=[org.acme.ExampleResource, java.lang.Object], qualifiers=[@Default, @Any], target=org.acme.ExampleResource]
```

As soon as I add a beans.xml to the external jar, all works.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Linux dev-vm.local 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
 - Quarkus version or git rev: 1.7.1.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Gradle 6.5.1

**Additional context**
https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/CDI.20producer.20with.20generic.20type.20argument

### PR DESCRIPTION
**Pull request by mkouba**
- the first one is used to discover beans, etc.
- the latter one is also used to discover types during type-safe
discovery
- fixes #11863

### CODE REVIEW

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanProcessor.java [hunk 1]
```diff
@@ -291,7 +292,29 @@ public Builder setName(String name) {
...
+        }
+
+        /**
+         * Set the (optional) additional index used to discover types during type-safe resolution. These types may not be part
+         * of the bean archive index.
+         * 
+         * @param additionalIndex
+         * @return self
+         */
+        public Builder setAdditionalIndex(IndexView additionalIndex) {
```
Comment (mkouba) [inline independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanProcessor.java:316]: I decided to use a more general name (`additionalIndex`) because it may be useful for other use cases as well...

**Comment by mkouba** [comment]
@ 38leinaD this PR should fix your problem. It would be great if you could try to test the branch...

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanProcessor.java (hunk 1 above)
Comment (geoand) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanProcessor.java:316]: Perhaps `applicationIndex` would be a better name?

Comment (mkouba) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanProcessor.java:316]: Hmm, that's a better name, yes...

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Types.java [hunk 2]
```diff
@@ -164,13 +165,16 @@ static Type getProviderType(ClassInfo classInfo) {
     static Set<Type> getProducerMethodTypeClosure(MethodInfo producerMethod, BeanDeployment beanDeployment) {
         Set<Type> types;
         Type returnType = producerMethod.returnType();
+        if (returnType.kind() == Kind.TYPE_VARIABLE) {
+            throw new DefinitionException("A type variable is not a legal bean type: " + producerMethod);
```
Comment (geoand) [inline independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Types.java:169]: Perhaps this can be improved? I'm bringing it up because I don't even remember what a type variable is :P

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Types.java [hunk 3]
```diff
@@ -192,12 +196,15 @@ static Type getProviderType(ClassInfo classInfo) {
     static Set<Type> getProducerFieldTypeClosure(FieldInfo producerField, BeanDeployment beanDeployment) {
         Set<Type> types;
         Type fieldType = producerField.type();
+        if (fieldType.kind() == Kind.TYPE_VARIABLE) {
+            throw new DefinitionException("A type variable is not a legal bean type: " + producerField);
```
Comment (geoand) [inline independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Types.java:200]: Same here

**Review by geoand — COMMENTED** [review]
I think this is fine improvement!

I just added some tiny suggestions

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Types.java (hunk 2 above)
Comment (mkouba) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Types.java:169]: > I don't even remember what a type variable is...

I will pretend that you've never written this ;-).

Type variables are type parameters, e.g.:
```
class ProducingBean<T> {

   // This is illegal...
   @Produces
   T produce() {
    // ...
   }
}
```

Comment (geoand) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Types.java:169]: Hahaha

I meant that just mentioning type parameter as a Jandex term is unlikely to help a user understand what's going on. Perhaps just mention generics - that way everyone will know what the problem is

Comment (mkouba) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Types.java:169]: Hm, the message contains the declaring class, method signature and return type... and it's a definition error as defined [by the spec](https://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#producer_method). I'd keep it simple for now. It's not a common use case...

Comment (geoand) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Types.java:169]: OK :)

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanResolver.java [hunk 4]
```diff
@@ -45,14 +43,20 @@ public BeanResolver(BeanDeployment beanDeployment) {
...
                 assignables.add(subclass.name());
             }
-            Collection<ClassInfo> implementors = beanDeployment.getIndex().getAllKnownImplementors(name);
-            for (ClassInfo implementor : implementors) {
+            for (ClassInfo implementor : beanDeployment.getBeanArchiveIndex().getAllKnownImplementors(name)) {
                 assignables.add(implementor.name());
             }
+            if (beanDeployment.hasApplicationIndex()) {
+                for (ClassInfo subclass : beanDeployment.getApplicationIndex().getAllKnownSubclasses(name)) {
+                    assignables.add(subclass.name());
```
Comment (manovotn) [inline independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanResolver.java:54]: @mkouba `ClassInfo` doesn't override `equals`/`hashCode`(as noted in https://github.com/wildfly/jandex/issues/83), can you be sure you won't get duplicates from both indexes?

**Review by manovotn — COMMENTED** [review]
Added few remarks.

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanDeployment.java [hunk 5]
```diff
@@ -357,7 +361,19 @@ ValidationContext validate(List<BeanDeploymentValidator> validators,
     }
 
     public IndexView getIndex() {
-        return index;
+        return getBeanArchiveIndex();
```
[the remark this answers is not in the document]
Comment (mkouba) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanDeployment.java:364]: Well, it's a public method on a public class that can be used by an integrator... On the other hand, Quarkus and the `ArcTestContainer` are probably the only integrators so far. So I'm going to remove this method...

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanResolver.java (hunk 4 above)
Comment (mkouba) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanResolver.java:54]: That's OK. `assignables` is a set of dot names.

Comment (manovotn) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanResolver.java:54]: Oops my bad, I thought its set of `ClassInfo`.

**Review by manovotn — APPROVED** [review]
