### PR TITLE
Validate parameter passed to ConfiguratorBase.param()

### LINKED ISSUE #27664: Proper exception message when passing null value to SyntheticBeanBuildItem Configuration parameter
### Description

When you pass a null value as parameter to the SyntheticBeanBuildItem generation, you get a NullPointerException but you don't have any clue (at first) where the problem occured.

```
Caused by: java.lang.NullPointerException
        at io.quarkus.gizmo.BytecodeCreatorImpl.allocateLocalVariables(BytecodeCreatorImpl.java:1195)
        at io.quarkus.gizmo.MethodCreatorImpl.write(MethodCreatorImpl.java:122)
        at io.quarkus.gizmo.ClassCreator.writeTo(ClassCreator.java:202)
        at io.quarkus.gizmo.ClassCreator.close(ClassCreator.java:225)
        at io.quarkus.arc.processor.BeanGenerator.generateSyntheticBean(BeanGenerator.java:222)

```
You can trigger the above Exception by code like this

```
        return SyntheticBeanBuildItem.configure(Foo.class)
                .scope(Singleton.class)
                .creator(FooCreator.class)
                .param("test", (String)null)
                .done();
```

Of course, in our extension the parameter test was based on some logic and it was not clear that the NPE was caused by passing `null` as value as it happens later and stacktrace is not related anymore to the problematic statement.

### Implementation ideas

Add a proper check and exception to all `.param` overloaded methods to indicate null is not an allowed value.

### PR DESCRIPTION
**Pull request by rdebusscher**
to not to be null. Fixes #27664.

### CODE REVIEW

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/ConfiguratorBase.java [hunk 1]
```diff
@@ -31,6 +32,7 @@ public THIS param(String name, boolean value) {
     }
 
     public THIS param(String name, boolean[] value) {
+        Objects.requireNonNull(value, "Parameter value can't be null");
```
Comment (mkouba) [inline independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/ConfiguratorBase.java:35]: I'd presonally use something like `params.put(name, Objects.requireNonNull(value));` becaue the message does not seem to be very helpful...

Comment (rdebusscher) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/ConfiguratorBase.java]: Updated the PR.

**Review by mkouba — APPROVED** [review]
Looks good!
