### PR TITLE
Account for more complex throws exception types on proxies.

### LINKED ISSUE #4178: ClientProxyGenerator - handle thrown exception types correctly
Currently, we only expect a `ClassType`: https://github.com/quarkusio/quarkus/blob/0.22.0/independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/ClientProxyGenerator.java#L100

### PR DESCRIPTION
**Pull request by manovotn**
Fixes #4178

### CODE REVIEW

**Review by kenfinnigan — APPROVED** [review]

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/ClientProxyGenerator.java [hunk 1]
```diff
@@ -98,7 +98,14 @@ public ClientProxyGenerator(Predicate<DotName> applicationClassPredicate) {
 
             // Exceptions
             for (Type exception : method.exceptions()) {
-                forward.addException(exception.asClassType().toString());
+                Type.Kind kind = exception.kind();
+                if (Type.Kind.CLASS.equals(kind)) {
```
Comment (mkouba) [inline independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/ClientProxyGenerator.java]: Hm, so I'm wondering:
1. Do we actually need to check the specific type or just always use `toString()`?
2. Should we add some tests? ;-)

Comment (manovotn) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/ClientProxyGenerator.java]: 1. that's a good point, we can just use `toString()`
2. I thought this change a bit too trivial to write a test for it, feel free to add one ;)

**Comment by manovotn** [comment]
Apparently, Stuart came across the same thing here and just pushed that as part of another fix - https://github.com/quarkusio/quarkus/commit/22a354c7a3ca569c601aa5bc7218655e9cc53c20

I'll rebase it and keep just the plain `toString()` as that seems to be universal for all cases...
