### PR TITLE
Deprecate OidcSession#expiresIn and add new methods

### LINKED ISSUE #27122: io.quarkus.oidc.OidcSession uses Instant to present duration
### Describe the bug

In, io.quarkus.oidc.OidcSession (https://github.com/quarkusio/quarkus/blob/main/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcSession.java),
it uses Instant to present duration.

```
    /**
     * Return an {@linkplain:Instant} indicating how long will it take for the current session to expire.
     *
     * @return
     */
    Instant expiresIn();
```

Based on [Javadoc](https://docs.oracle.com/javase/8/docs/api/java/time/Instant.html), it is an instantaneous point on the time-line. But the comment says "how long", it should be Duration.

When using it in app, it seems that the value is filled with Duration too.
e.g. One value I got is `"expiresIn": "1970-01-01T00:23:05Z"`. I guess it means the session has 23 hours and 5 minutes to expire.

Personally, I prefer to use Instant but it should assigned the correct time value (a duration value is a little hard to predict the ending time without base time) and the comment should be updated.

### Expected behavior

Using Instant but it should assigned the correct time value (a duration value is a little hard to predict the ending time without base time) and the comment should be updated.

### Actual behavior

It uses Instant with the wrong value and comment is misleading.

### How to Reproduce?

Just any endpoint with injection of OidcSession.

### Output of `uname -a` or `ver`

Darwin Kernel Version 21.4.0

### Output of `java -version`

openjdk version "18" 2022-03-2

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.8.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.4.1

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sberyozkin**
Fixes #27122.

This PR:
- Fixes OidcSession#expiresIn to return a correct `Instant` representation of the token expiration time
- Adds a new method which will help users check how long, starting from now, the session will remain valid for.

Testing for a precise duration value is not easy, it is 3 secs (id token lifespan), but I'd like to avoid some random test failures, I think allowing for a ">1 && < 5" margin is reasonable, even for practical purposes. 

@geoand Have a look please when you are back :-).

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]

**Comment by sberyozkin** [comment]
Thanks @gastaldi :-)

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcSession.java [hunk 1]
```diff
@@ -16,12 +17,21 @@ public interface OidcSession {
...
+     * which is a number of seconds from the epoch of 1970-01-01T0:0:0Z.
      *
-     * @return
+     * @return Instant
      */
     Instant expiresIn();
 
+    /**
+     * Return a {@linkplain Duration} indicating how long will it take for the current session to expire
+     * starting from the current time
```
Comment (geoand) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcSession.java:29]: Maybe instead of 'current time' we should say invocation time?

Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcSession.java:29]: @geoand Yeah, sure, I was contemplating if we should imply that this check is done at the request (invocation) time, I can update

**Review by geoand — APPROVED** [review]

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcSession.java (hunk 1 above)
Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcSession.java]: @geoand I've changed it to `starting from this method's invocation time` as I thought it might be open to a few interpretations otherwise what invocation time is referred to here... Are you OK with it ?

Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcSession.java]: Looks like so as you've just approved :-)

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcSession.java [hunk 2]
```diff
@@ -16,12 +17,21 @@ public interface OidcSession {
...
      */
     Instant expiresIn();
 
+    /**
+     * Return a {@linkplain Duration} indicating how long will it take for the current session to expire
+     * starting from this method's invocation time.
+     *
+     * @return Duration
+     */
+    Duration getExpiresInDuration();
```
Comment (gsmet) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcSession.java:33]: This is really less than ideal. I would have expected something like `getExpirationTime` returning an Instant and `expiresIn` returning a duration.
Given this previous method is of not much use right now, I think we should break things now, rather than living with some badly named methods forever.

**Review by gsmet — CHANGES_REQUESTED** [review]

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcSession.java (hunk 2 above)
Comment (gastaldi) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcSession.java:33]: If breaking the API is an option here, then I agree with @gsmet, but I'd name it `expirationTime()` instead 😉

Comment (gsmet) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcSession.java:33]: Well, we somehow break the API as we won't return the same thing that it used to be. If people are using the existing API, things will get messy as the meaning has changed.
So I would prefer if we broke things cleanly.

Agreed on `expirationTime()` being better since apparently getters were not used for the rest.

Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcSession.java:33]: @gsmet Fix to the original API is not a breaking change but a bug fix, I won't be removing it but I'm fine with deprecating it as I've already had some pushback for just breaking things in a supported extension.

So we'll have 
```
@Deprecated
@use expirationTime();
Instant expiresIn();

// new method
Instant expirationTime();

// new method - anything better than expiresInPeriod ? It is not ideal but IMHO it works, the docs make it clear what it is for
Duration expiresInPeriod();

```

Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcSession.java:33]: To be honest I think `expiresInDuration` is also good enough, I'd not make a big deal out of it

Comment (gastaldi) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcSession.java:33]: Actually `on` is for dates, so it would be used in the expirationTime  https://continuingstudies.uvic.ca/elc/studyzone/490/grammar/prepositions-time-in-at-on

Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcSession.java:33]: may be `Duration validFor()`

Comment (gsmet) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcSession.java:33]: @sberyozkin it is a breaking change as the meaning is different. If people were using the value before to do something useful, it will be broken as you will return something with a totally different meaning.
That's why I would prefer if we break the API. That way, you know that the meaning has changed.

Comment (gsmet) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcSession.java:33]: Well. I don't. I think `expiresAt` for instance and `expiresIn` for duration would be better candidates. But you seem to have a strong opinion about it so I will let you decide and live with it :).

Comment (gsmet) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcSession.java:33]: And `validFor` is indeed `less worse` then the previous proposals :).

Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcSession.java:33]: @gsmet I agree with you, and I do appreciate you keeping an eye, but I'm just trying to workaround about the fact I might need to keep the current `expiresIn`, but I'm not sure now this interface made it to the product, I'll check, if not I'll be happy to get rid of the current `expiresIn`

Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcSession.java:33]: @gsmet Sadly it was committed to 2.7.0.CR1, did it for Stephane but this expiry thing was not even requested, just added it in a rush in addition to `logout()`, so I guess the proposed strategy where we try to return something meaningful from this currently badly implemented, explain it in the docs but deprecate at the same time, and then have as you propose `Instance expirationTime` (saw you agreeing on it above) and I guess then `Duration validFor()` may work.

But I'll ping a few more colleagues to discuss, thanks

Comment (gsmet) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcSession.java:33]: `expiresAt` is probably a bit better than `expirationTime`.

Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcSession.java:33]: @gsmet Sure, I've just checked, for the token gen API, it is [expiresAt for Instant](https://github.com/smallrye/smallrye-jwt/blob/main/implementation/jwt-build/src/main/java/io/smallrye/jwt/build/JwtClaimsBuilder.java#L105) and [expiresIn for Duration](https://github.com/smallrye/smallrye-jwt/blob/main/implementation/jwt-build/src/main/java/io/smallrye/jwt/build/JwtClaimsBuilder.java#L125) :-). I'm about to push the update, but if you'd like then we can avoid adding `Duration validFor()` just yet - but do it in `2.13.0.CR1` where we can delete (though not 100% sure about it just yet) the deprecated method and add `Duration expiresIn()`

Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcSession.java]: @gsmet Have a look please, like I said, we can postpone adding `Duration validFor` unless it would imply we'd have to wait for a long time before it can be added

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcSession.java [hunk 3]
```diff
@@ -18,10 +19,29 @@ public interface OidcSession {
...
+     * @deprecated Use {@link #expiresAt()}.
+     *
+     * @return Instant
      */
+    @Deprecated
     Instant expiresIn();
 
+    /**
+     * Return an {@linkplain Instant} representing the current session's expiration time
+     * which is a number of seconds from the epoch of 1970-01-01T0:0:0Z.
```
Comment (gsmet) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcSession.java:31]: Is this javadoc correct? It looks like the javadoc of `expiresIn`? I thought we decided to display the actual expiration time here?
`which is a number of seconds from the epoch of 1970-01-01T0:0:0Z` looks weird.

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcSession.java [hunk 4]
```diff
@@ -18,10 +19,29 @@ public interface OidcSession {
     /**
      * Return an {@linkplain:Instant} indicating how long will it take for the current session to expire.
      *
-     * @return
+     * @deprecated Use {@link #expiresAt()}.
+     *
+     * @return Instant
      */
+    @Deprecated
```
Comment (gsmet) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcSession.java:26]:
```suggestion
    @Deprecated(forRemoval = true, since = "2.12.0")
```

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcSession.java [hunk 5]
```diff
@@ -18,10 +19,29 @@ public interface OidcSession {
     /**
      * Return an {@linkplain:Instant} indicating how long will it take for the current session to expire.
      *
-     * @return
+     * @deprecated Use {@link #expiresAt()}.
```
Comment (gsmet) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcSession.java:22]:
```suggestion
     * @deprecated This method shouldn't be used as it provides an instant corresponding to 1970-01-01T0:0:0Z plus the duration of the validity of the token, which is impractical. Please use either {@link #expiresAt()} or {@link #validFor()} depending on your requirements. This method will be removed in a later version of Quarkus.
```

**Review by gsmet — CHANGES_REQUESTED** [review]
OK for the impl but I added some suggestions regarding the doc.

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcSession.java (hunk 3 above)
Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcSession.java:31]: @gsmet It is correct, this is what the `exp` claim value is which is what this `Instant` captures

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcSession.java (hunk 5 above)
Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcSession.java]: @gsmet Nice idea, thanks

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcSession.java (hunk 3 above)
Comment (gsmet) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcSession.java:34]: I don't understand really. Isn't this method supposed to return the real expiration time and not something weird? The doc seems to indicate it will be 1970 + 30 minutes (typically) instead of the real expiration time?

I thought it was the original issue we were trying to solve so I might miss something entirely.

Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcSession.java:34]: @gsmet It is just the way the expiration time is handled for JWT tokens, the epoch is a base. if we take from some other base then we won't be able to correctly compare it against the current time (which is also calculated from the epoch).
From the `exp` claim definition in the OIDC spec:
```
Expiration time on or after which the ID Token MUST NOT be accepted for processing. ... Its value is a JSON number representing the number of seconds from 1970-01-01T0:0:0Z".
The same for `issuedAt` time, etc.

> The doc seems to indicate it will be 1970 + 30 minutes
It will be more than 30 mins, it will be more than the current time. If it is less than the current time then the session (token) has expired.

Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcSession.java:34]: @gsmet, if you'd like you can do `mvn quarkus:dev` in `security-openid-connect-quickstart` and go to the OIDC devUI card, login to KC as `alice:alice` and check the `exp` value in the displayed access or ID token...

**Review by gsmet — APPROVED** [review]

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcSession.java (hunk 3 above)
Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcSession.java]: Removed the ref to the epoch time to avoid the confusion as agreed with Guillaume
