### PR TITLE
Catch exception happening in the gRPC interceptors

### LINKED ISSUE #28053: gRPC ServerInterceptor throwing exceptions are not catched
### Describe the bug

Hi all, I'm trying to use an interceptor coming from an external package, which throws an exception when executing `interceptCall`. When this happens, quarkus will print the exception as uncaught but won't reply back.

Looking at the docs of [`ServerInterceptor`](https://grpc.github.io/grpc-java/javadoc/io/grpc/ServerInterceptor.html#interceptCall-io.grpc.ServerCall-io.grpc.Metadata-io.grpc.ServerCallHandler-), throwing an exception there looks like a valid implementation:

> If the implementation throws an exception, call will be closed with an error.

### Expected behavior

Response back with error grpc status code `INTERNAL` and some status message indicating the failure (or maybe just "Internal server error")

### Actual behavior

No response back

### How to Reproduce?

1. Create an interceptor throwing an exception
2. Try to send a request using grpcurl, e.g. `grpcurl -vv -plaintext -d '{"name":"Francesco"}' localhost:9000 hello.HelloGrpc/SayHello`

See the reproducer attached

[reproducer.zip](https://github.com/quarkusio/quarkus/files/9598156/reproducer.zip)

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

openjdk version "17.0.4.1" 2022-08-12

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.12.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by cescoffier**
Fix https://github.com/quarkusio/quarkus/issues/28053.

### CODE REVIEW

File: extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/context/GrpcDuplicatedContextGrpcInterceptor.java [hunk 1]
```diff
@@ -2,20 +2,20 @@
...
 import javax.enterprise.context.ApplicationScoped;
 import javax.enterprise.inject.spi.Prioritized;
 
 import org.jboss.logging.Logger;
 
-import io.grpc.Metadata;
-import io.grpc.ServerCall;
-import io.grpc.ServerCallHandler;
-import io.grpc.ServerInterceptor;
+import io.grpc.*;
```
Comment (gsmet) [inline extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/context/GrpcDuplicatedContextGrpcInterceptor.java:14]: Nope :).

**Review by gsmet — CHANGES_REQUESTED** [review]

**Comment by cescoffier** [comment]
@gsmet updated.
