### PR TITLE
ArC - fix resolution if the required type is wildcard

### LINKED ISSUE #3311: ArC removes indirect referenced beans
Quarkus in version 19.1 removes indirect referenced beans.

Lets have following scenario. You define an interface for your strategies and an services that depending on any argument, returns the appropriate strategy. These strategies are defined as beans. As these beans are not referenced directly with injections, but only through the interface, the are removed by ArC. The only way to fix it, is by setting `quarkus.arc.remove-unused-beans=false`

```java
public interface Exporter<T extends Exportable> {
    boolean accept(Class<T> clazz);
    String export(T object);
}

@ApplicationScoped
public class ApplicationExporter implements Exporter<Application> {
   boolean accept(Class<Application> clazz) { return clazz instanceof Application; }
   String export(Application application) {
     ...
   }
}

@ApplicationScoped
public class ExporterService {
  @Inject
  Instance<Exporter<? extends Exportable>> exporters; 
  public <T>Exporter<T> getExporter(Class<T> exporterClazz) {
    // BUG: exporters are empty!
    return StreamSupport.stream(exporters.spliterator(), false)
            .filter(exporter -> exporter.accept(exporterClazz))
            .findFirst().orElseThrow(...);
  }
}
```

If there is an `@Inject javax.enterprise.inject.Instance<T>` Quarkus (ArC) should keep all classes implementing `T`.

### PR DESCRIPTION
**Pull request by mkouba**
- resolves #3311

### CODE REVIEW

**Comment by mkouba** [comment]
@dkellenb this PR should fix the bug I've mentioned in https://github.com/quarkusio/quarkus/issues/3311. It would be great if you could verify whether it fixes your problem too.

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanResolver.java [hunk 1]
```diff
@@ -125,6 +125,8 @@ boolean matchesNoBoxing(Type requiredType, Type beanType) {
                 }
                 return true;
             }
+        } else if (WILDCARD_TYPE.equals(requiredType.kind()) || TYPE_VARIABLE.equals(requiredType.kind())) {
```
Comment (manovotn) [inline independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanResolver.java]: The tests don't cover the type variable case, or am I missing something?

**Review by manovotn — APPROVED** [review]
