### PR TITLE
Ensure that custom Jackson modules work in dev-mode

### LINKED ISSUE #44231: Hot-reload brokes Vertx JsonObject serialization (dev mode)
### Describe the bug

Scenario: 
- custom dto with a custom jackson `StdSerializer` registered via `ObjectMapperCustomizer`
- serialization of a `io.vertx.core.json.JsonObject` where a property is an instance of custom dto
- serialization of a `io.vertx.core.json.JsonArray` where one or more elements are instances of custom dto

During first run all works correcty, but after the application is hot-reloaded due to some project modifications, serialization stop to works with this error

(partial stacktrace)

```
io.vertx.core.json.EncodeException: Failed to encode as JSON: No serializer found for class org.acme.StringAndInt and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: java.util.ArrayList[0])
	at io.quarkus.vertx.runtime.jackson.QuarkusJacksonJsonCodec.toString(QuarkusJacksonJsonCodec.java:147)
	at io.vertx.core.json.JsonArray.encode(JsonArray.java:557)
	at io.quarkus.resteasy.reactive.jackson.runtime.serialisers.vertx.VertxJsonArrayMessageBodyWriter.writeResponse(VertxJsonArrayMessageBodyWriter.java:26)
	at io.quarkus.resteasy.reactive.jackson.runtime.serialisers.vertx.VertxJsonArrayMessageBodyWriter.writeResponse(VertxJsonArrayMessageBodyWriter.java:15)
	at org.jboss.resteasy.reactive.server.core.ServerSerialisers.invokeWriter(ServerSerialisers.java:218)
	at org.jboss.resteasy.reactive.server.core.ServerSerialisers.invokeWriter(ServerSerialisers.java:186)
	at org.jboss.resteasy.reactive.server.core.serialization.FixedEntityWriterArray.write(FixedEntityWriterArray.java:31)
	at org.jboss.resteasy.reactive.server.handlers.ResponseWriterHandler.handle(ResponseWriterHandler.java:34)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:147)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at org.jboss.resteasy.reactive.server.handlers.RestInitialHandler.beginProcessing(RestInitialHandler.java:48)
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:23)
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:10)
```

### Expected behavior

Serialization should works correctly after an hot-reload

### Actual behavior

Serialization stops to work after an hot-reload

### How to Reproduce?

https://github.com/luca-bassoricci/vertxjson-serialization-hotreload-issue

No tests are present due to nature of problem.
To reproduce 
1. start application with quarkus:dev
2. do a `GET http://localhost:8080/test/array`, all should works fine
3. reload using 's' console command
4. do a `GET http://localhost:8080/test/array`: error

### Output of `uname -a` or `ver`

windows

### Output of `java -version`

jdk17

### Quarkus version or git rev

3.16.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
- Fixes: #44231

### CODE REVIEW

**Comment by geoand** [comment]
This is important enough to be backported, however I would very much like to have this properly run through all QE, Mandrel and performance test suites because it could theoretically cause regressions in native image

File: extensions/vertx/deployment/src/main/java/io/quarkus/vertx/core/deployment/VertxCoreProcessor.java [hunk 1]
```diff
@@ -286,6 +286,12 @@ ContextHandlerBuildItem createVertxContextHandlers(VertxCoreRecorder recorder, V
         return new ContextHandlerBuildItem(recorder.executionContextHandler(buildConfig.customizeArcContext()));
     }
 
+    @BuildStep
+    @Record(ExecutionTime.RUNTIME_INIT)
+    public void cleanUp(VertxCoreRecorder recorder, ShutdownContextBuildItem shutdown) {
+        recorder.resetMapper(shutdown);
+    }
+
```
Comment (geoand) [inline extensions/vertx/deployment/src/main/java/io/quarkus/vertx/core/deployment/VertxCoreProcessor.java:294]: This is causing issues in native mode and since it's only meant to fix a dev-mode case, we should limit it's applicability to that mode

File: extensions/vertx/deployment/src/main/java/io/quarkus/vertx/core/deployment/VertxCoreProcessor.java [hunk 2]
```diff
@@ -286,6 +287,12 @@ ContextHandlerBuildItem createVertxContextHandlers(VertxCoreRecorder recorder, V
         return new ContextHandlerBuildItem(recorder.executionContextHandler(buildConfig.customizeArcContext()));
     }
 
+    @BuildStep(onlyIfNot = NativeOrNativeSourcesBuild.class)
```
Comment (gsmet) [inline extensions/vertx/deployment/src/main/java/io/quarkus/vertx/core/deployment/VertxCoreProcessor.java:290]: Does it make sense to do that outside of dev mode?

File: extensions/vertx/runtime/src/main/java/io/quarkus/vertx/runtime/jackson/QuarkusJacksonJsonCodec.java [hunk 3]
```diff
@@ -30,11 +30,31 @@
...
+            synchronized (QuarkusJacksonJsonCodec.class) {
+                if (mapper == null) {
+                    populateMapper();
+                }
+            }
+        }
+        return mapper;
+    }
+
+    private static void populateMapper() {
```
Comment (gsmet) [inline extensions/vertx/runtime/src/main/java/io/quarkus/vertx/runtime/jackson/QuarkusJacksonJsonCodec.java:57]: Will the `QuarkusJacksonJsonCodec` always be loaded by Vert.x? Because if so, I wonder if we should populate a new mapper directly instead of resetting it.
That being said I'm not entirely sure we could safely drop some of the guards but wanted to push the idea in case you didn't think about it.

File: extensions/vertx/deployment/src/main/java/io/quarkus/vertx/core/deployment/VertxCoreProcessor.java (hunk 2 above)
Comment (geoand) [reply extensions/vertx/deployment/src/main/java/io/quarkus/vertx/core/deployment/VertxCoreProcessor.java:290]: It's really only for dev-mode, so yeah, we could limit it to that

File: extensions/vertx/runtime/src/main/java/io/quarkus/vertx/runtime/jackson/QuarkusJacksonJsonCodec.java (hunk 3 above)
Comment (geoand) [reply extensions/vertx/runtime/src/main/java/io/quarkus/vertx/runtime/jackson/QuarkusJacksonJsonCodec.java:57]: The name of the method is probably confusing here - what it does is actually create a new `ObjectMapper` used by Vert.x. Do you want me to change the method as to make it easier for us to understand next time we stumble upon the code?

File: extensions/vertx/deployment/src/main/java/io/quarkus/vertx/core/deployment/VertxCoreProcessor.java (hunk 2 above)
Comment (gsmet) [reply extensions/vertx/deployment/src/main/java/io/quarkus/vertx/core/deployment/VertxCoreProcessor.java:290]: Yeah I would rather limit it to where it's useful. Either dev mode or dev/test mode, whatever is better.

File: extensions/vertx/runtime/src/main/java/io/quarkus/vertx/runtime/jackson/QuarkusJacksonJsonCodec.java (hunk 3 above)
Comment (gsmet) [reply extensions/vertx/runtime/src/main/java/io/quarkus/vertx/runtime/jackson/QuarkusJacksonJsonCodec.java:57]: No I understand what the method does.

What I was wondering is if the `reset()` could `populate()` the default mapper instead of populating it. Maybe in a synchronized method so that we could drop the volatile.

That would make sense only if the codec is always initialized though. Otherwise we might pay the initialization cost for nothing.

It might be a bad idea though, I will let you decide what's best.

Comment (geoand) [reply extensions/vertx/runtime/src/main/java/io/quarkus/vertx/runtime/jackson/QuarkusJacksonJsonCodec.java:57]: > could populate() the default mapper instead of populating it. Maybe in a synchronized method so that we could drop the volatile.

I want to avoid that because populating means extracting from Arc, which I am not 100% sure would give the proper bean at this point.
Whereas the way it's done now, the loading of the mapper happens in the same "timing" as if there no reload.

Comment (gsmet) [reply extensions/vertx/runtime/src/main/java/io/quarkus/vertx/runtime/jackson/QuarkusJacksonJsonCodec.java:57]: OK, sure, it makes perfect sense. We can revisit if we see it creates some performance issues but in this case, we will have to be very careful as to how operations are ordered.

**Review by gsmet — APPROVED** [review]
I let you decide if you want to merge or wait for additional feedback from QE and perf (my understanding is that it will be tested by the lab once merged).

**Comment by geoand** [comment]
> (my understanding is that it will be tested by the lab once merged).

Rigth, that's why I will merge now and await be on the lookout for any suspicious upticks
