### PR TITLE
Fix Proxy usage by OIDC devservices

### LINKED ISSUE #49389: OIDC Dev UI won't work behind an HTTP Proxy
### Describe the bug

When trying to use OIDC extension Dev UI with keycloak disabled, and targeting for example EntraID, through an HTTP Proxy, it won't work (but token validation inside the application is OK) :
Dev UI won't be able to access OIDC metadata URL because it does not take quarkus.oidc.proxy.* properties into account (nor JVM http.Proxy, ... system properties), we get a timeout while accessing oidc metadata.

The cause seems to be that the Vert.x WebClient used by OIDC dev UI does not use proxy configuration if present (see OidcDevServicesUtils createWebClient method).

### Expected behavior

OIDC Dev UI should use proxy Configuration

### Actual behavior

OIDC Dev UI fails to access OIDC endpoints even if quarkus.oidc.proxy.* properties are set up.

### How to Reproduce?

Follow https://quarkus.io/guides/security-openid-connect-providers#microsoft to set up a quarkus application, and add  quarkus.oidc.proxy.* to make OIDC mechanism access endpoints through a proxy.
The OIDC extension will take proxy conf into account, but Dev UI won't.

### Output of `uname -a` or `ver`

4.18.0-553.64.1.el8_10.x86_64 #1 SMP Wed Jul 23 16:42:14 EDT 2025 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "18.0.2.1" 2022-08-18 OpenJDK Runtime Environment (build 18.0.2.1+1-1) OpenJDK 64-Bit Server VM (build 18.0.2.1+1-1, mixed mode, sharing)

### Quarkus version or git rev

3.20.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.9.11

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by flofourcade**
Add OIDC DevUI Proxy support

Fixes https://github.com/quarkusio/quarkus/issues/49389

### CODE REVIEW

**Comment by michalvavrik** [comment]
@flofourcade Sergey, who will review your PR, is currently not around, have a patience, it might take a week or two.

File: extensions/oidc/runtime-dev/src/main/java/io/quarkus/oidc/runtime/dev/ui/OidcDevServicesUtils.java [hunk 1]
```diff
@@ -30,6 +34,34 @@ public static WebClient createWebClient(Vertx vertx) {
         WebClientOptions options = new WebClientOptions();
         options.setTrustAll(true);
         options.setVerifyHost(false);
+        Config config = ConfigProvider.getConfig();
+        //We can use quarkus.oidc.proxy.* properties, or maybe can we use Java proxy System properties (http.proxyHost , ...)?
```
Comment (sberyozkin) [inline extensions/oidc/runtime-dev/src/main/java/io/quarkus/oidc/runtime/dev/ui/OidcDevServicesUtils.java]:
```suggestion
```

File: extensions/oidc/runtime-dev/src/main/java/io/quarkus/oidc/runtime/dev/ui/OidcDevServicesUtils.java [hunk 2]
```diff
@@ -30,6 +34,34 @@ public static WebClient createWebClient(Vertx vertx) {
...
+        //Don't know if there's a better way to get config valuees here ....
```
Comment (sberyozkin) [inline extensions/oidc/runtime-dev/src/main/java/io/quarkus/oidc/runtime/dev/ui/OidcDevServicesUtils.java]:
```suggestion
```

**Comment by sberyozkin** [comment]
@flofourcade Thanks for the PR, LGTM, I only suggested to drop the comments for now, support for Java proxy configuration would be a wider issue

**Comment by flofourcade** [comment]
Hello!
Applied your suggestions. 
Any chance for this to be ported to LTS (3.20.x) branch ?

**Comment by sberyozkin** [comment]
@flofourcade Thanks, please squash, I can do it tomorrow as well.

We can try to request a backport to 3.20

**Review by sberyozkin — APPROVED** [review]
