### PR TITLE
Register any additional necessary providers for server sent event @Produce(s)

### LINKED ISSUE #2176: Kafka Guide does not work
I followed the steps in the Kafka Guide in https://quarkus.io/guides/kafka-guide and when I open the page, all I get is 
```
Last price

The last price is N/A €.
```

You can see that the connection closes prematurely if you use HTTPie to connect to `/prices/stream` as in:
 
```http --stream -f localhost:8080/prices/stream -v```
 
By debugging and comparing to the quickstart in https://github.com/quarkusio/quarkus-quickstarts/tree/master/kafka-quickstart (which works btw), the only missing part (and what makes the guide work) is to add the following code to the `PriceResource`:

```java
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        return "hello";
    }
```

See: https://github.com/quarkusio/quarkus-quickstarts/blob/master/kafka-quickstart/src/main/java/org/acme/quarkus/sample/PriceResource.java#L21-L25

### PR DESCRIPTION
**Pull request by jaikiran**
The commit here introduces a way where any additional necessary `providers` are registered for any resource that `@Produces` `MediaType.SERVER_SENT_EVENTS`. This should allow for fixing the issue reported in https://github.com/quarkusio/quarkus/issues/2176 such that the `PriceResouce` in that example can now use:

```
@GET
    @Path("/stream")
    @Produces("text/event-stream;element-type=text/plain")
    public Publisher<Double> stream() {
        return prices;
    }
```
and will no longer require a (dummy) resource endpoint to register the basic `text/plain` type providers.

Fixes #2176

### CODE REVIEW

**Comment by gsmet** [comment]
This is more correct but I doubt people will get it right.

Another option would be to include the text plain media type as soon as we have a `MediaType.SERVER_SENT_EVENTS`. Maybe we could have a generic method contributing additional media types based on a media type.

Typically, we would call `contributeAdditionalMediaTypes()` at these places:
- https://github.com/quarkusio/quarkus/blob/master/extensions/resteasy-common/deployment/src/main/java/io/quarkus/resteasy/common/deployment/ResteasyCommonProcessor.java#L188
- https://github.com/quarkusio/quarkus/blob/master/extensions/resteasy-common/deployment/src/main/java/io/quarkus/resteasy/common/deployment/ResteasyCommonProcessor.java#L198
- https://github.com/quarkusio/quarkus/blob/master/extensions/resteasy-common/deployment/src/main/java/io/quarkus/resteasy/common/deployment/ResteasyCommonProcessor.java#L208

and it would return an augmented list of elements in some cases (for now, only the `MediaType.SERVER_SENT_EVENTS` case).

Does it make sense to you?

**Comment by jaikiran** [comment]
> This is more correct but I doubt people will get it right.

@gsmet, I understand what you mean.

> Another option would be to include the text plain media type as soon as we have a MediaType.SERVER_SENT_EVENTS. Maybe we could have a generic method contributing additional media types based on a media type.

Okay, so instead of expecting users to use an `element-type` `MediaType` parameter, we by default add the `text/plain` provider if and when we see the use of `MediaType.SERVER_SENT_EVENTS` in the application. That sounds fine to me.

> Typically, we would call contributeAdditionalMediaTypes() at these places: 

I have looked at the code that you pointed to (the 3 places) and do understand what you mean. However, those 3 places won't be the right place to do this logic, since those 3 places are processing the providers that have been found in the classpath, rather than the user's application resources which use those providers. That latter part happens later and I have updated this PR to use this common logic in that central place where it happens for `MessageWriter`, `MessageReader` and `ContextResolver`. 

The commit in this PR now adds the `text/plain` provider if it finds the usage of server sent events, plus also supports any additional `element-type` parameter if at all the user application has used such a construct.

Furthermore, I have included a test case to test the server sent events. Do note that this test case is ineffective in _reproducing_ the original reported issue because of the way we run our integration tests, where multiple other JaxRS endpoints are scanned and because of their usage of `text/plain`, the providers will anyway be registered and this issue won't be triggered. However, this test at least adds some amount of testing around server sent events.

**Review by asoldano — APPROVED** [review]
I think this proposal from Jaikiran is fine; see section 5 at https://docs.jboss.org/resteasy/docs/4.3.0.Final/userguide/html/Reactive.html#d4e2322

**Comment by geoand** [comment]
If @asoldano agrees, then it I think we should merge. @gsmet ?

**Comment by gsmet** [comment]
Please wait.

AFAICS there is also `@SseElementType` which seems to be used in this case - see example 1 here: https://docs.jboss.org/resteasy/docs/4.3.0.Final/userguide/html/Reactive.html#d4e2483

I think I would add `TEXT_PLAIN_TYPE` only if the element type is not defined one way or another.

What I'm unclear about is the precedence between the `;element-type` parameter and the `@SseElementType` annotation.

@asoldano could you shed some light on this?

**Comment by geoand** [comment]
@gsmet up to you :)

**Comment by asoldano** [comment]
@gsmet uh, thanks, I would need to run some tests, but you might have made me notice a "bug". So `@SeeElementType` is the RESTEasy annotation that controls the `;element-type` parameter, however it looks like a `@Produce("text/event-stream; element-type=foo/bar")` would result in a response with no parameter is the `@SseElementType` annotation is not there too. Anyway, for the Quarkus case, it's probably safe to check if the `element-type` parameter is defined in any way (directly or with the dedicated annotation), with the `@SseElementType` overriding the value from `@Produces`.

**Comment by gsmet** [comment]
@asoldano OK, cool, thanks!

@jaikiran could you implement the above? (and defaults to text/plain if we don't have any meaningful information). I think it would greatly improve things in Quarkus.

**Comment by jaikiran** [comment]
Thank you @asoldano for all these details and the review and thank you @gsmet for the patience with this review. I have now pushed a change to this PR which takes into account what we have discussed here. The comments in the code should summarize how we deal with it now (essentially the same as what we decided here).

**Comment by geoand** [comment]
There are some formatting issues.

You can do `mvn process-resources` to fix them and then update the PR

**Comment by geoand** [comment]
Clean install should do the trick. It has so often however that we commit before doing it 😅

File: extensions/resteasy-common/deployment/src/main/java/io/quarkus/resteasy/common/deployment/ResteasyCommonProcessor.java [hunk 1]
```diff
@@ -269,26 +274,95 @@ private static boolean collectDeclaredProvidersForMethodAndMediaTypeAnnotation(S
...
+        if (matches(MediaType.SERVER_SENT_EVENTS_TYPE, mediaType)) {
+            final Set<String> additionalProvidersToRegister = new HashSet<>();
+            // first check for @SseElementType
+            final AnnotationInstance sseElementTypeAnnInst = targetMethod.annotation(SSE_ELEMENT_TYPE);
+            String elementType = null;
+            if (sseElementTypeAnnInst != null) {
+                elementType = sseElementTypeAnnInst.value().asString();
+            } else {
+                // fallback on the MediaType parameter
+                if (mediaType.getParameters() != null
```
Comment (gsmet) [inline extensions/resteasy-common/deployment/src/main/java/io/quarkus/resteasy/common/deployment/ResteasyCommonProcessor.java]: It's really very very minor but can it be a `else if` instead?

**Review by gsmet — CHANGES_REQUESTED** [review]
@jaikiran I added a very minor comment but the main thing is that it needs a rebase (I would have merged as is if not).

Could you take care of the rebase and fix my minor remark along the way?

Other than that, it's perfect, thanks a lot for this.

Thanks!

**Comment by jaikiran** [comment]
Hi @gsmet, I've updated this PR after rebasing with latest and also incorporated the (valid) change that you mentioned in the latest comment.

**Review by kenfinnigan — APPROVED** [review]

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Merged, very nice improvement, thanks!
