### PR TITLE
Ensure that Java 12+ interfaces of java.lang.String are as CDI types

### LINKED ISSUE #5062: Building a Quarkus application with Java 12+ can result in failure to start it in Java 8 runtime
Quarkus applications are generated to be runnable against a minimum Java 8 version. However, there appears to be an issue where if a Quarkus application is built using Java 8+ (especially Java 12 or higher) and then that application is started on Java 8, then it runs into an exception. One such exception is:

```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:27)
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl1.<clinit>(ApplicationImpl1.zig:325)
	... 1 more
Caused by: java.lang.NoClassDefFoundError: java/lang/constant/ConstantDesc
	at io.quarkus.arc.runtime.QuarkusConfigProducer_ProducerMethod_produceStringConfigProperty_75511873be6a3e578c4555b07b03c7231f99c7bc_Bean.<init>(QuarkusConfigProducer_ProducerMethod_produceStringConfigProperty_75511873be6a3e578c4555b07b03c7231f99c7bc_Bean.zig:257)
	at io.quarkus.arc.setup.Default_ComponentsProvider.getComponents(Default_ComponentsProvider.zig:81)
	at io.quarkus.arc.impl.ArcContainerImpl.<init>(ArcContainerImpl.java:102)
	at io.quarkus.arc.Arc.initialize(Arc.java:19)
	at io.quarkus.arc.runtime.ArcRecorder.getContainer(ArcRecorder.java:34)
	at io.quarkus.deployment.steps.ArcProcessor$generateResources15.deploy_0(ArcProcessor$generateResources15.zig:72)
	at io.quarkus.deployment.steps.ArcProcessor$generateResources15.deploy(ArcProcessor$generateResources15.zig:36)
	at io.quarkus.runner.ApplicationImpl1.<clinit>(ApplicationImpl1.zig:295)
	... 1 more
Caused by: java.lang.ClassNotFoundException: java.lang.constant.ConstantDesc
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 9 more
```
It looks like we are missing the use of `-release` option that should be configured in our Maven (and Gradle?) compiler plugins to prevent `javac` from using Java 8+ APIs in the generated class files.

### PR DESCRIPTION
**Pull request by geoand**
This is needed because when building with Java 12+ but targeting Java 8-11,
we need to ensure that the extra interfaces that java.lang.String implements
do not end up in the generated bytecode.

Fixes: #5062

### CODE REVIEW

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Types.java [hunk 1]
```diff
@@ -45,6 +46,13 @@
 
     private static final Type OBJECT_TYPE = Type.create(DotNames.OBJECT, Kind.CLASS);
 
+    // we ban these interfaces because they are new to Java 12 and are used by java.lang.String which
+    // means that they cannot be included in bytecode if we want to have application built with Java 12+ but targeting Java 8 - 11
+    // actually run on those older versions
+    // TODO:  add a extensible banning mechanism based on predicates if we find that this set needs to grow...
+    private static final Set<String> BANNED_INTERFACE_TYPES = new HashSet<>(
```
Comment (mkouba) [inline independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Types.java]: Why not to use `DotName`s?

Comment (geoand) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Types.java]: Makes sense, I'll do that

Comment (geoand) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Types.java]: Done

**Review by gsmet — APPROVED** [review]
