### PR TITLE
QuarkusTestProfile - make it possible to disable app lifecycle observers

### LINKED ISSUE #15083: ApplicationScoped bean observing start/stop still observing even when mocked
**Describe the bug**
I have an application scoped bean observing start:

```
@ApplicationScoped
public class SomeBean {
  protected void onStart(@Observes StartupEvent ev) {
    System.out.println("I'm here");
  }
}
```
I can of course see this hit the start method when the application starts.

In my QuarkusTests, I don't actually need/want the start to be hit.

If I use `@InjectMock SomeBean`, or create a `@Mock` replacement that overrides the start, I still see the original `onStart` being called.

**Expected behavior**
If you use `@InjectMock` or an alternative bean with `@Mock`, the original observes should not be called.

**To Reproduce**
See attached [observes.zip](https://github.com/quarkusio/quarkus/files/5982250/observes.zip)

**Environment (please complete the following information):**
Quarkus version 1.11.3.Final
Maven info:
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Java version: 11.0.9.1, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-11-openjdk-11.0.9.11-9.fc32.x86_64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.10.7-100.fc32.x86_64", arch: "amd64", family: "unix"

### PR DESCRIPTION
**Pull request by mkouba**
- resolves #15083

### CODE REVIEW

File: test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java [hunk 1]
```diff
@@ -1112,6 +1115,7 @@ public void execute(BuildContext context) {
                             .build();
 
                     List<String> testClassBeans = new ArrayList<>();
+                    testClassBeans.add(ClassloaderApplicationClassPredicate.class.getName());
```
Comment (geoand) [inline test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java:1118]: Can you explain the need for this? It's evident why it's necessary

Comment (mkouba) [reply test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java:1118]: We need the predicate to be able to distinguish the application classes from fwk/lib classes. This is an implementation bean that leverages the `QuarkusClassLoader`. We could use `AdditionalBeanBuildItem` as well but since all ``TestClassBeanBuildItem``s are transformed into ``AdditionalBeanBuildItem``s it's easier... I can add a comment though ;-)

Comment (geoand) [reply test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java:1118]: OK, it is kinda sketchy so it at least needs to be properly commented :)

Comment (mkouba) [reply test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java:1118]: +1 it's "sketchy" and the impl is "hacky" ;-)

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ArcTestConfig.java [hunk 2]
```diff
@@ -0,0 +1,15 @@
...
+import io.quarkus.runtime.annotations.ConfigItem;
+
+@ConfigGroup
+public class ArcTestConfig {
+
+    /**
+     * If set to true then disable {@code StartupEvent} observers declared on application bean classes during the tests.
+     */
+    @ConfigItem(defaultValue = "false")
+    public boolean disableApplicationStartupObservers;
```
Comment (geoand) [inline extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ArcTestConfig.java:13]: I am wondering if it makes sense to disable the `ShutdownEvent` as well

Comment (mkouba) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ArcTestConfig.java:13]: That's a good point. In general, the `ShutdownEvent` is less often used because one can simply use `@PreDestroy` on application/singleton beans but it probably makes sense to keep it consistent.

Comment (FroMage) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ArcTestConfig.java:13]: Yeah, agreed.

Comment (mkouba) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ArcTestConfig.java]: Done.

File: test-framework/junit5/src/main/java/io/quarkus/test/junit/ClassloaderApplicationClassPredicate.java [hunk 3]
```diff
@@ -0,0 +1,24 @@
...
+class ClassloaderApplicationClassPredicate implements TestApplicationClassPredicate {
+
+    @Override
+    public boolean test(String name) {
+        QuarkusClassLoader cl = (QuarkusClassLoader) Thread.currentThread()
+                .getContextClassLoader();
+        //if the class file is present in this (and not the parent) CL then it is an application class
+        List<ClassPathElement> res = cl
+                .getElementsWithResource(name.replace(".", "/") + ".class", true);
+        return !res.isEmpty();
```
Comment (mkouba) [inline test-framework/junit5/src/main/java/io/quarkus/test/junit/ClassloaderApplicationClassPredicate.java:21]: Unfortunately, it seems that this approach does not work at all. I've copied this code from `IsolatedDevModeMain` but we probably need something different for tests. @stuartwdouglas Any idea?

Comment (stuartwdouglas) [reply test-framework/junit5/src/main/java/io/quarkus/test/junit/ClassloaderApplicationClassPredicate.java:21]: That won't work in tests, and TBH I don't know if the concept really makes sense. In dev mode 'application class' has a very specific meaning that is a class that can be hot reloadable. In tests I think this is a bit less clear. 

My original idea around this that I did not really articulate clearly was to basically just have a @DisableForTests annotation that you could apply to  the problematic observer method.

Comment (mkouba) [reply test-framework/junit5/src/main/java/io/quarkus/test/junit/ClassloaderApplicationClassPredicate.java:21]: > In tests I think this is a bit less clear.

My understanding of an _application class_ is that it's a class from the application root (`src/main/java`), or root of any other module in a multi-module project, or test dir (`src/test/java`), i.e. the classes that form the app except for classes coming from dependencies (quarkus extensions or libs).

Is the definition of _hot deployable resources_ different?

> My original idea around this that I did not really articulate clearly was to basically just have a @DisableForTests annotation that you could apply to the problematic observer method.

The main disadvantage of this approach is that the problematic observer would be always disabled (in all tests), whereas the approach in this PR is based on test profiles.

Comment (mkouba) [reply test-framework/junit5/src/main/java/io/quarkus/test/junit/ClassloaderApplicationClassPredicate.java]: Ok, so I've replaced the class loader approach with a bean "preloded" during STATIC_INIT. It works just fine, the question is whether we're OK with the concept in general...

**Comment by mkouba** [comment]
@stuartwdouglas @FroMage @geoand Are we OK with the concept in general? If so I can hit the ready for review button. If not I will close this PR.

**Comment by geoand** [comment]
This is +1 from me

File: extensions/arc/runtime/src/main/java/io/quarkus/arc/runtime/ArcRecorder.java [hunk 4]
```diff
@@ -55,13 +66,29 @@ public BeanContainer initBeanContainer(ArcContainer container, List<BeanContaine
         return beanContainer;
     }
 
-    public void handleLifecycleEvents(ShutdownContext context, BeanContainer beanContainer) {
-        LifecycleEventRunner instance = beanContainer.instance(LifecycleEventRunner.class);
-        instance.fireStartupEvent();
+    public void handleLifecycleEvents(ShutdownContext context, LaunchMode launchMode,
+            boolean disableApplicationLifecycleObservers) {
+        ArcContainerImpl container = ArcContainerImpl.instance();
+        List<Class<?>> mockBeanClasses = new ArrayList<>();
```
Comment (geoand) [inline extensions/arc/runtime/src/main/java/io/quarkus/arc/runtime/ArcRecorder.java:72]: Super minor nitpick: Perhaps we can avoid the allocation here this list will rarely be populated?

**Review by geoand — APPROVED** [review]

File: extensions/arc/runtime/src/main/java/io/quarkus/arc/runtime/ArcRecorder.java (hunk 4 above)
Comment (mkouba) [reply extensions/arc/runtime/src/main/java/io/quarkus/arc/runtime/ArcRecorder.java]: Done.
