### PR TITLE
Collect providers required for RESTEasy's @PartType annotations

### LINKED ISSUE #13539: RESTEASY: Unable to find a MessageBodyReader for media type: text/plain; charset=us-ascii and class type java.util.Map
```java
    @POST
    @Path("/import")
    @Consumes({MediaType.MULTIPART_FORM_DATA})
    @Produces({MediaType.APPLICATION_JSON})
    @Transactional
    public Response myFileImport(@MultipartForm MyImportData importData) {
         [...]
    }
```
---

```java
public class MyImportData {

    @FormParam("myFile")
    @PartType(MediaType.APPLICATION_OCTET_STREAM)
    public InputStream inputStream;

    @FormParam("myMapping")
    @PartType(MediaType.APPLICATION_JSON)
    public Map<Integer, String> myMapping;
}
```

Exception:
```
Marcus Biel: java.lang.RuntimeException: RESTEASY007545: Unable to find a MessageBodyReader for media type: text/plain; charset=us-ascii and class type java.util.Map
at org.jboss.resteasy.plugins.providers.multipart.MultipartInputImpl$PartImpl.getBody(MultipartInputImpl.java:226)
at org.jboss.resteasy.plugins.providers.multipart.MultipartFormAnnotationReader.setFields(MultipartFormAnnotationReader.java:189)
at org.jboss.resteasy.plugins.providers.multipart.MultipartFormAnnotationReader.readFrom(MultipartFormAnnotationReader.java:79)
at org.jboss.resteasy.core.interception.jaxrs.AbstractReaderInterceptorContext.readFrom(AbstractReaderInterceptorContext.java:101)
at org.jboss.resteasy.core.interception.jaxrs.ServerReaderInterceptorContext.readFrom(ServerReaderInterceptorContext.java:63)
at org.jboss.resteasy.core.interception.jaxrs.AbstractReaderInterceptorContext.proceed(AbstractReaderInterceptorContext.java:80)
```
---
media type: text/plain is confusing, since I set APPLICATION_JSON as the type - but it gave me the hint for a quick hack:
Putting media type: text/plain and a String Java type, then converting the raw Json String with a Jackson Objectmapper in my Java code myself. I guess I need to provide a custom MessageBodyReader, but I couldn't get this to work quickly, so I went with my hack instead.

### LINKED ISSUE #13731: Take into account PartType in RESTEasy's provider detection
When working with multipart, `org.jboss.resteasy.annotations.providers.multipart.PartType` can reference other media types and might require additional providers to be registered.

At the moment, we totally ignore it.

This is more important with JSON being the default as a lot of users didn't properly registered the Consumes/Produces and thus all the providers were registered. Now that we only register JSON by default, there might be some missing providers.

### PR DESCRIPTION
**Pull request by gsmet**
Fixes #13539
Fixes #13731

### CODE REVIEW

File: extensions/resteasy-common/deployment/src/main/java/io/quarkus/resteasy/common/deployment/ResteasyCommonProcessor.java [hunk 1]
```diff
@@ -483,6 +484,14 @@ private static boolean collectDeclaredProviders(List<RestClientBuildItem> restCl
                     }
                 }
             }
+
+            // handle @PartType: we don't know if it's used for writing or reading so we register both
+            for (AnnotationInstance partTypeAnnotation : index.getAnnotations(ResteasyDotNames.RESTEASY_PART_TYPE)) {
+                providersToRegister
+                        .addAll(categorizedReaders.getPossible(MediaType.valueOf(partTypeAnnotation.value().asString())));
```
Comment (gastaldi) [inline extensions/resteasy-common/deployment/src/main/java/io/quarkus/resteasy/common/deployment/ResteasyCommonProcessor.java:491]: I think an `IllegalArgumentException` may be thrown if the `MediaType` cannot be resolved? Also, it would be nice to call `MediaType.valueOf` just one time

Comment (gsmet) [reply extensions/resteasy-common/deployment/src/main/java/io/quarkus/resteasy/common/deployment/ResteasyCommonProcessor.java]: Right, fixed!

**Review by gastaldi — APPROVED** [review]

**Comment by gsmet** [comment]
I added a test, should be good to go now.

**Review by geoand — APPROVED** [review]
Nice!
