### PR TITLE
Optimize ArcDevConsoleProcessor.buildDependencyGraph()

### LINKED ISSUE #27281: ArcDevConsoleProcessor.collectBeanInfo() is taking a long time
### Describe the bug

Quarkus 2.11 takes 13s to do a restart in dev mode, forced by pressing s in the terminal.

A large chunk of this time is spent on ArcDevConsoleProcessor.collectBeanInfo.

The app has 730 non removed beans, and 130 entities.

I can't export a flamegraph file on my current environment, however I can send you a .nps (sampling snapshot created by visualvm) privatly.

Thread, build-41 taking 71% of overall profiling time.
image

Timeline:
image

Screenshot from another run sampled with visualvm:
image

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19044.1826]

### Output of `java -version`

openjdk 18.0.2 2022-07-19 OpenJDK Runtime Environment Temurin-18.0.2+9 (build 18.0.2+9) OpenJDK 64-Bit Server VM Temurin-18.0.2+9 (build 18.0.2+9, mixed mode, sharing)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.11.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537) Maven home: C:\eclipse\tools\java\maven Java version: 18.0.2, vendor: Eclipse Adoptium, runtime: C:\eclipse\tools\java\18 Default locale: de_DE, platform encoding: UTF-8 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mkouba**
- resolves #27281

### CODE REVIEW

**Comment by Postremus** [comment]
@mkouba Thank you, this is a massive improvement for my app.

Force restart:
2.11.2.Final: 16s
5017e8ba405131e17c220a9a882fa4da57c3855f: 11s

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/devconsole/ArcDevConsoleProcessor.java [hunk 1]
```diff
@@ -183,38 +200,52 @@ void addNodesDependencies(BeanInfo root, Set<DevBeanInfo> nodes, Set<Link> links
...
-                            addNodesDependents(root, nodes, links, dependent, beans, declaringToProducers, resolver,
-                                    devBeanInfos);
-                        }
+    void addNodesDependents(BeanInfo root, Set<DevBeanInfo> nodes, Set<Link> links, BeanInfo bean,
+            List<InjectionPointInfo> injectionPoints, Map<BeanInfo, List<BeanInfo>> declaringToProducers, BeanResolver resolver,
+            DevBeanInfos devBeanInfos, Map<BeanInfo, List<InjectionPointInfo>> directDependents) {
+        List<InjectionPointInfo> direct = directDependents.get(bean);
+        if (direct == null) {
+            direct = new ArrayList<>();
+            for (InjectionPointInfo injectionPoint : injectionPoints) {
```
Comment (Ladicek) [inline extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/devconsole/ArcDevConsoleProcessor.java:209]: Naive question, but this loop has to run once for each bean, while it seems it should be possible to create a map of direct dependencies (either `Map<BeanInfo, List<InhjectionPointInfo>>` or even `Map<BeanInfo, List<BeanInfo>>`) once, when building the dependency graph (that is, when the `allInjectionPoints` list is being populated). That should be quite a bit faster when the number of injections is much higher than the number of beans I'd guess?

Comment (mkouba) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/devconsole/ArcDevConsoleProcessor.java:209]: So in this particular case we would need an "inverse" map because we're looking for _dependents_ not dependencies. And since we cache the result I believe it's essentially the same perf as if was built beforehand, or am I missing something?

Comment (manovotn) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/devconsole/ArcDevConsoleProcessor.java:209]: I think @Ladicek is basically suggesting to move this logic to L#144 where you iterate over all beans and their IPs so that you could build the same information from just a single iteration.

Comment (Ladicek) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/devconsole/ArcDevConsoleProcessor.java:209]: @manovotn is right on the money. Single iteration should be enough and should provide some additional speedup (I _think_ :-) )

Comment (manovotn) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/devconsole/ArcDevConsoleProcessor.java:209]: Looking more in the code, it seems like that would work well in resolving direct dependencies while saving some iterations (and potentially a lot of them in cases with lots of IPs for each bean), so +1
You'd still need to so the transient dependency resolution and producers later on once you have complete information on direct dependencies, but unless I am missing something, that seems doable.

Comment (manovotn) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/devconsole/ArcDevConsoleProcessor.java:209]: @mkouba something like this should do the trick - https://github.com/manovotn/quarkus/commit/3c4067977e5178ece195b779d7c96e79e61cb18e
Feel free to use that commit however you wish (warning: didn't run more than a quickstart sanity check with it)

Comment (Ladicek) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/devconsole/ArcDevConsoleProcessor.java:209]: Big props, I considered refactoring the code myself, but was too lazy :laughing:

Comment (mkouba) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/devconsole/ArcDevConsoleProcessor.java:209]: Hm, I get your point. But this would not help for programmatic lookup injection points that would require an additional iteration over all beans to find all eligible candidates. In other words, it would probably help a little when the number of injections is much higher than the number of beans but could make it worse when it's the other way around.

Comment (Ladicek) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/devconsole/ArcDevConsoleProcessor.java:209]: I'm not sure I follow -- the way I understand it, @manovotn's change leads to strictly less work than before when building the dependents map, and all the other work remains unchanged?

**Review by manovotn — APPROVED** [review]

File: extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/devconsole/ArcDevConsoleProcessor.java (hunk 1 above)
Comment (Ladicek) [reply extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/devconsole/ArcDevConsoleProcessor.java:209]: After some additional discussion over Zulip, I'm retracting this comment. Thanks for your patience though :-)

**Review by Ladicek — APPROVED** [review]
