### PR TITLE
Containerized native image build on remote docker daemons (issue #1610)

### LINKED ISSUE #1610: dockerBuild for native image doesn't work with remote Docker daemons
The build fails, to try to create a native binary with `dockerBuild` true and accessing a remote Docker daemon which does not allow bind mounts via `docker run -v` as it is done in https://github.com/quarkusio/quarkus/blob/fea6ba9709cbfa431706788123b49ef21999fec8/core/creator/src/main/java/io/quarkus/creator/phase/nativeimage/NativeImagePhase.java#L286

This use is important when e.g. building against minikube/minishift's internal Docker daemon (`eval $(minikube docker-env)`) so that an image does not need to be pushed to a registry but could be directly used within minikube.

For this setup, in Syndesis we avoided bind mounts but used a combination of running the actual build during a Docker build and then copying out the generated binary from the created image by running a container with `cat`:

The actual build is like in 

```bash
cd $operator_dir
docker build -t syndesis-operator-builder . -f Dockerfile-builder
docker run syndesis-operator-builder cat /syndesis-operator > syndesis-operator
chmod a+x syndesis-operator
```

with that Dockerfile

```Dockerfile
FROM golang:1.11.0
RUN go get -u github.com/golang/dep/cmd/dep
WORKDIR /go/src/github.com/syndesisio/syndesis/install/operator
COPY Gopkg.toml .
COPY Gopkg.lock .
RUN dep ensure -vendor-only -v
COPY . .
RUN CGO_ENABLED=0 go build -o /syndesis-operator ./cmd/syndesis-operator
```

This might not be useful in this context as it depends on the size of the source to copy over into the image when doing the build.

As an alternative, we used ssh to copy over the sources into the Minishift VM and then used a bind mount within the VM, but the current solution is (a) more generally applicable and (b) also more robust.

### PR DESCRIPTION
**Pull request by jonathan-meier**
Container builds for native images on a *remote* docker host are currently not possible (#1610). The issue is that the native build step mounts a volume to the build container containing the sources for the native image build and to which the final native image is written back to the host. However, volume mounts are not available for remote docker daemons. Still, using remote docker daemons is a pretty common scenario.

I outlined a solution to this problem in a comment on the above mentioned issue https://github.com/quarkusio/quarkus/issues/1610#issuecomment-674521423, which is to copy the build sources into the container as well as copy the final native image out of the container back to the host, instead of using the volume mount.

This PR introduces separate runners for native image builds. The `NativeImageBuildStep` class now acts as a driver for the different native image build runners (local and containerized). Moreover, thanks to this new driver/runner structure, a new runner for containerized native image builds on remote docker daemon is provided as well, implementing the above mentioned strategy fixing #1610. It can be enabled with the new property `quarkus.native.remote-container-build=true`. Please note that due to a permission problem, the new runner does not work with the officially provided native build docker images yet (see PR https://github.com/quarkusio/quarkus-images/pull/128).

In the future, more runners could easily be added, e.g. a runner using the docker-java library (https://github.com/docker-java/docker-java) for communicating with docker, instead of explicitly invoking the docker CLI.

Resolves: #1610

### CODE REVIEW

**Comment by gsmet** [comment]
@zakkak could you have a look at this?

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java [hunk 1]
```diff
@@ -279,7 +280,8 @@ public NativeImageBuildItem build(NativeConfig nativeConfig, NativeImageSourceJa
         }
     }
 
-    private static NativeImageBuildRunner getNativeImageBuildRunner(NativeConfig nativeConfig, Path outputDir) {
+    private static NativeImageBuildRunner getNativeImageBuildRunner(NativeConfig nativeConfig, Path outputDir,
+            String nativeImageName) {
         boolean isContainerBuild = nativeConfig.containerRuntime.isPresent() || nativeConfig.containerBuild;
```
Comment (zakkak) [inline core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java:285]: I think `nativeConfig.remoteContainerBuild` should be added as well.

**Review by zakkak — APPROVED** [review]
LGTM (please see my comment though) Thanks @jonathan-meier !

@gsmet please note that this PR conflicts with https://github.com/quarkusio/quarkus/pull/13963 so once one of them gets merged the other one will need to be rebased.

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java (hunk 1 above)
Comment (jonathan-meier) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java]: Good point! My intention was that the `nativeConfig.remoteContainerBuild` is actually only respected when `nativeConfig.remoteContainer` is `true` and it would simply be ignored when `nativeConfig.remoteContainer` is `false`. However, thinking about it, this might be confusing behavior. I added it to the condition above as you suggest, such that it is enough to set `nativeConfig.remoteContainerBuild` to `true` to trigger a remote container build.

The question then is, what runner should be chosen when both `nativeConfig.remoteContainer` and `nativeConfig.remoteContainerBuild` are set to `true`? The current code would choose the remote container build in that case, which I think is fine.

**Comment by jonathan-meier** [comment]
Thanks for the review @zakkak! About the conflicting PR #13963: I see there's quite a bit of overlap. Which merge order do you think will lead to less rebasing work?

**Comment by zakkak** [comment]
> Thanks for the review @zakkak! About the conflicting PR #13963: I see there's quite a bit of overlap. Which merge order do you think will lead to less rebasing work?

I think I prefer #14635 (this PR) to be merged first and then #13963 (since I've already reviewed your code the rebase should probably be easier for me), but since we would like to get the functionality of #13963 backported to 1.11 it might not be wise to follow that order. That said I would prefer @gsmet to decide what should get merged first and whether https://github.com/quarkusio/quarkus/issues/13754 should be fixed in a different PR than #13963 for 1.11.

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java (hunk 1 above)
Comment (zakkak) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java]: > The current code would choose the remote container build in that case, which I think is fine.

Yes, that's what I'd expect as a user.

**Comment by jonathan-meier** [comment]
rebased on current master to resolve conflict introduced by the changes of https://github.com/quarkusio/quarkus/pull/14655

**Comment by jonathan-meier** [comment]
@zakkak may I ask what the status is on this PR? Have you come to a decision yet whether to backport PR #13963?

I don't know exactly the release schedule, just trying to make sure we don't accidentally miss landing this PR in 1.12.

**Comment by zakkak** [comment]
@gsmet I suggest we merge this (and backport to 1.12 as requested by @jonathan-meier if possible), I will then rebase https://github.com/quarkusio/quarkus/pull/13963 and get it ready for 1.13.

If we end up needing the functionality of https://github.com/quarkusio/quarkus/pull/13963 in 1.11 it looks like it will need to be through a finer-grained PR anyway (as you point out in https://github.com/quarkusio/quarkus/pull/13963#issuecomment-772693962).

**Comment by jonathan-meier** [comment]
rebased on current master to resolve conflict introduced by the changes of https://github.com/quarkusio/quarkus/pull/15041

@gsmet what's your opinion on zakkak's suggestion above?

**Comment by gsmet** [comment]
I rebased this one, let's make progress to get this in 1.13!

**Review by geoand — APPROVED** [review]

**Comment by geoand** [comment]
Thanks!

**Comment by jonathan-meier** [comment]
Thanks everyone for the reviewing and rebasing work. Super happy that this got merged, it helps us getting quite a bit further in building a native image for our app in our CI infrastructure!

I think #1610 can be closed now.

**Comment by geoand** [comment]
Can we also get a small documentation update describing this feature?

**Comment by jonathan-meier** [comment]
@geoand I opened PR #15591 with a doc update draft.
