### PR TITLE
Reorder codec registry configuration so that custom codecs are registered first

### LINKED ISSUE #13236: wrong initialisation order of mongo codec providers
**Describe the bug**
It is impossible to override standard coders, `MongoClients.createMongoConfiguration()` uses `defaultCodecRegistry` before custom `CodecProvider`:
```java
        CodecRegistry registry = CodecRegistries.fromRegistries(defaultCodecRegistry,
                CodecRegistries.fromProviders(providers));
        settings.codecRegistry(registry);
```

**Expected behavior**
Custom providers should be used at the first place:
```java
        CodecRegistry registry = CodecRegistries.fromRegistries(CodecRegistries.fromProviders(providers), defaultCodecRegistry);
```
this is also recommended by mongodb-team [Codec and CodecRegistry](https://mongodb.github.io/mongo-java-driver/3.6/bson/codecs/):
```java
CodecRegistry defaultCodecRegistry = ... 
DocumentCodecProvider documentCodecProvider = ... 
Codec<Instant> instantCodec = ...   
codecRegistry = CodecRegistries.fromRegistries(CodecRegistries.fromCodecs(instantCodec),
                                               CodecRegistries.fromProviders(documentCodecProvider),
                                               defaultCodecRegistry);
```

**Actual behavior**
codecs registry is initialized with default codes at the first place and this will not allow to override them. reading of the `BigDecimal` value will not use a custom `Codec` and will fail with the message:
```
Caused by: org.bson.BsonInvalidOperationException: readDecimal can only be called when CurrentBSONType is DECIMAL128, not when CurrentBSONType is STRING.
	at org.bson.AbstractBsonReader.verifyBSONType(AbstractBsonReader.java:690)
	at org.bson.AbstractBsonReader.checkPreconditions(AbstractBsonReader.java:722)
	at org.bson.AbstractBsonReader.readDecimal128(AbstractBsonReader.java:380)
	at org.bson.codecs.BigDecimalCodec.decode(BigDecimalCodec.java:39)
	at org.bson.codecs.BigDecimalCodec.decode(BigDecimalCodec.java:30)
	at org.bson.codecs.DecoderContext.decodeWithChildContext(DecoderContext.java:96)
	at org.bson.codecs.pojo.PojoCodecImpl.decodePropertyModel(PojoCodecImpl.java:219)
	... 106 more
```

**To Reproduce**
Please check this repository [quarkus-mongo-bug](https://github.com/oxelad/quarkus-mongo-bug.git)

run tests: `mvn clean verify` ; integration tests will fail.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:  `Darwin Kernel Version 19.6.0`
 - Output of `java -version`:  `java version "11.0.9" 2020-10-20 LTS`
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): `Apache Maven 3.6.3`

### PR DESCRIPTION
**Pull request by evanchooly**
fixes #13236

### CODE REVIEW

File: extensions/mongodb-client/runtime/src/main/java/io/quarkus/mongodb/runtime/MongoClients.java [hunk 1]
```diff
@@ -299,6 +269,39 @@ private MongoClientSettings createMongoConfiguration(MongoClientConfig config) {
...
+        }
+        // register property codec provider
+        if (!mongoClientSupport.getPropertyCodecProviders().isEmpty()) {
+            pojoCodecProviderBuilder.register(getPropertyCodecProviders(mongoClientSupport.getPropertyCodecProviders())
+                    .toArray(new PropertyCodecProvider[0]));
+        }
+        CodecRegistry registry = !providers.isEmpty() ?
+                fromRegistries(fromProviders(providers), defaultCodecRegistry,
+                        fromProviders(pojoCodecProviderBuilder.build())) :
+                fromRegistries(defaultCodecRegistry, fromProviders(pojoCodecProviderBuilder.build()));
```
Comment (oxelad) [inline extensions/mongodb-client/runtime/src/main/java/io/quarkus/mongodb/runtime/MongoClients.java]: is it correct? providers provided by `pojoCodecProviderBuilder` will be registered  after `defaultCodecRegistry`- this will be the same situation as it was with custom providers :(

File: extensions/mongodb-client/runtime/src/main/java/io/quarkus/mongodb/runtime/MongoClients.java [hunk 2]
```diff
@@ -299,6 +269,39 @@ private MongoClientSettings createMongoConfiguration(MongoClientConfig config) {
...
+                .conventions(Conventions.DEFAULT_CONVENTIONS);
+        // register bson discriminators
+        ClassLoader classLoader = Thread.currentThread().getContextClassLoader();
+        for (String bsonDiscriminator : mongoClientSupport.getBsonDiscriminators()) {
+            try {
+                pojoCodecProviderBuilder
+                        .register(ClassModel.builder(Class.forName(bsonDiscriminator, true, classLoader))
+                                .enableDiscriminator(true).build());
+            } catch (ClassNotFoundException e) {
+                // Ignore
```
Comment (oxelad) [inline extensions/mongodb-client/runtime/src/main/java/io/quarkus/mongodb/runtime/MongoClients.java:293]: it doesn't relate to the issue of the codec ordering, but ... suppressing of exception is not good- developers will spend a lot of time to understand why some logic doesn't work when it should be, it will be not so easy to find that something was broken because of class-load-issue... better will be to log it...

sorry for this my 2 cents

Comment (loicmathieu) [reply extensions/mongodb-client/runtime/src/main/java/io/quarkus/mongodb/runtime/MongoClients.java:293]: @oxelad this error should never occurs as the class has been discover in a previous build step so it should be safe to ignore the error

**Review by loicmathieu — APPROVED** [review]
LGTM

File: extensions/mongodb-client/runtime/src/main/java/io/quarkus/mongodb/runtime/MongoClients.java (hunk 1 above)
Comment (evanchooly) [reply extensions/mongodb-client/runtime/src/main/java/io/quarkus/mongodb/runtime/MongoClients.java]: In theory, no.  Custom defined codecs, as I understand how this is all formulated, are in the `providers` list where POJO codecs are registered with `pojoCodecProviderBuilder`.  So the codecs for entities will be resolved last, yes, but in practice this will only be a problem if the `defaultCodecRegistry` somehow has a codec for your entity types which seems a bit of a stretch.  But should you wish to provide your own codec for a non-entity type, this should be sufficient.

**Comment by gsmet** [comment]
@evanchooly please NEVER add a specific commit for the formatter run. We end up a commit with a broken tree that we cannot easily compile without adding options. Please squash the commits before merging (or let me do it).

**Comment by evanchooly** [comment]
Hrm.  Yeah that should've been squashed.  I thought I clicked that option.  My apologies.

**Comment by gsmet** [comment]
Unfortunately, GH UI doesn't allow merge commits with squash so you have to do it manually :/

**Comment by evanchooly** [comment]
Pfft.  Noted.  I thought it did.  But yeah, that's a terrible breakage I hadn't even considered.  I'll make sure that never happens again.
