### PR TITLE
Fix typo in OpenShift liveness probe

### LINKED ISSUE #32135: Quarkus-openshift fails to properly deploy applications which use management interface
### Describe the bug

I have an application, which uses separate management interface[1] and deployed on Openshift via quarkus-openshift extension[2]. Both main and management interfaces are not accessible after deployment.

[1] https://github.com/quarkusio/quarkus/pull/30506
[2] https://quarkus.io/guides/deploying-to-openshift

### Expected behavior

Quarkus openshift extension should deploy an application is completely working state.

### Actual behavior

see below

### How to Reproduce?

1. Clone: `git clone git@github.com:fedinskiy/reproducer.git -b openshift-extension-management`
2. Create new openshift project `oc new-project fvd-test-management`
3. Deploy the app according to manual: `mvn clean install -Dquarkus.kubernetes.deploy=true -Dquarkus.openshift.route.expose=true -Dquarkus.kubernetes-client.trust-certs=true`
Log contains something like 
`[INFO] [io.quarkus.kubernetes.deployment.KubernetesDeployer] The deployed application can be accessed at: http://openshift-quickstart-fvd-test-management.apps.ocp4-12.rest.of.url`
4. Check the app
```
[fedinskiy@localhost reproducer]$ curl -v http://openshift-quickstart-fvd-test-management.apps.ocp4-12
<omitted for brevity>
> User-Agent: curl/7.85.0
< HTTP/1.0 503 Service Unavailable
```

For comparison: 

1. `oc new-project fvd-test-old`
2. `echo "" > src/main/resources/application.properties`
3. `mvn clean install -Dquarkus.kubernetes.deploy=true -Dquarkus.openshift.route.expose=true -Dquarkus.kubernetes-client.trust-certs=true`
4. The application can be accessed: ` curl http://openshift-quickstart-fvd-test-old.apps.ocp4-12<omitted>` 

### Output of `uname -a` or `ver`

6.0.18-300.fc37.x86_64

### Output of `java -version`

17.0.5, vendor: GraalVM Community

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

3.0.0.Beta1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)

### Additional information

```
$ oc version
Client Version: 4.11.0-202208020706.p0.g7075089.assembly.stream-7075089
Kustomize Version: v4.5.4
Kubernetes Version: v1.25.4+18eadca

```

### PR DESCRIPTION
**Pull request by Sgitario**
Fix https://github.com/quarkusio/quarkus/issues/32135

There were two issues:
- There was a typo in the OpenShift liveness probe
- Missing AddStartupProbeDecorator class in the after method in ApplyHttpGetActionPortDecorator (so it was not guaranteed that the startupProbe will use the right port).  Fixed by using the common decorator class AbstractAddProbeDecorator instead.

### CODE REVIEW

File: extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/OpenshiftProcessor.java [hunk 1]
```diff
@@ -310,15 +313,15 @@ public List<DecoratorBuildItem> createDecorators(ApplicationInfoBuildItem applic
         }
 
         // Probe port handling
-        result.add(KubernetesCommonHelper.createProbeHttpPortDecorator(name, OPENSHIFT, "livenssProbe", config.livenessProbe,
+        result.add(KubernetesCommonHelper.createProbeHttpPortDecorator(name, OPENSHIFT, LIVENESS_PROBE, config.livenessProbe,
```
Comment (gsmet) [inline extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/OpenshiftProcessor.java:316]: Good catch.

**Review by iocanel — APPROVED** [review]
lgtm
