### PR TITLE
RuntimeConfigDefault changes ignored on restart

### LINKED ISSUE #17069: Runtime defaults config supplied via `RunTimeConfigurationDefaultBuildItem` are not overridden on restart during dev mode
## Describe the bug

An extension author can provide default values via the `RunTimeConfigurationDefaultBuildItem`, this is the case for dev services. In dev mode, the same key can have different values on each restart e.g a new container was spun by testcontainers, taking a new random/different port. The behaviour I am seeing with dev services is that a new restart of the container having a different port does not update the config value and the first supplied value is always cached.  

### Expected behavior

Defaults values supplied via `RunTimeConfigurationDefaultBuildItem` should always be taken into account on each app restart in dev mode and not cache the first value. 

### Actual behavior

The first default value of a config item is cached and subsequent overrides of the values are not taken into account. 

This is the case for datasource devservices and mongo devservices.  This leads to connection failures. 

## To Reproduce

The issue can be reproduced with the current quickstarts e.g the [mongodb one](https://github.com/quarkusio/quarkus-quickstarts/tree/development/mongodb-quickstart)

 
1. Using the `https://github.com/quarkusio/quarkus-quickstarts/tree/development/mongodb-quickstart` quickstart 
2. Open the `vim src/main/resources/application.properties` configuration file and add the following entry only
```properties
quarkus.mongodb.devservices.image-name=mongo
```
while making sure that the connection-string property is commented out or removed.
3. start the quickstart in dev mode with `mvn quarkus:dev`
4. visits the `http://localhost:8080/q/dev/io.quarkus.quarkus-vertx-http/config` page and observe the auto-configured connection string. 
Also observe the output of the `docker ps` command to see the current mongo container mapped port. This should match the port in the config page. 
5. Open the `vim src/main/resources/application.properties` configuration file and change the image tag to `mongo:4.4.5` this will lead to a new container being spin up. 
```properties
quarkus.mongodb.devservices.image-name=mongo:4.4.5
```
while making sure that the connection-string property is commented out or removed.
6. Observe the logs of the command in (3) and you'll see logs like below
```log
(cluster-ClusterId{value='6095541bbe5033399414ba51', description='null'}-localhost:49194) Exception in monitor thread while connecting to server localhost:49194: com.mongodb.MongoSocketOpenException: Exception opening socket
	at com.mongodb.internal.connection.AsynchronousSocketChannelStream$OpenCompletionHandler.failed(AsynchronousSocketChannelStream.java:124)
	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:129)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishConnect(UnixAsynchronousSocketChannelImpl.java:283)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(UnixAsynchronousSocketChannelImpl.java:198)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(UnixAsynchronousSocketChannelImpl.java:213)
	at java.base/sun.nio.ch.EPollPort$EventHandlerTask.run(EPollPort.java:306)
	at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.checkConnect(Native Method)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishConnect(UnixAsynchronousSocketChannelImpl.java:252)
	... 7 more
```

Observing the output from `docker ps` again will show that a new container was started by devservices but the app is using the old container which can be observed in the config page.

### PR DESCRIPTION
**Pull request by stuartwdouglas**
Fixes #17069

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
Moving to draft for now, as it turns out some Dev Services are relying on this behaviour.

**Comment by stuartwdouglas** [comment]
This ended up being a bit of a substantial dev services cleanup, but I think the end result is cleaner. We also no longer restart them for tests which makes continuous testing a lot faster and more usable.

**Comment by stuartwdouglas** [comment]
This is proving more complex than I had hoped, so I have split the dev services cleanup into https://github.com/quarkusio/quarkus/pull/19075

**Comment by gsmet** [comment]
This needs a rebase.

**Review by radcortez — APPROVED** [review]

**Comment by stuartwdouglas** [comment]
@radcortez I have modified this a lot and it should work now, can you have another look?

**Review by radcortez — APPROVED** [review]

File: core/deployment/src/main/java/io/quarkus/deployment/steps/ConfigGenerationBuildStep.java [hunk 1]
```diff
@@ -95,13 +116,6 @@ void generateConfigClass(
             return;
         }
 
-        Map<String, String> defaults = new HashMap<>();
-        for (RunTimeConfigurationDefaultBuildItem item : runTimeDefaults) {
-            if (defaults.putIfAbsent(item.getKey(), item.getValue()) != null) {
-                throw new IllegalStateException("More than one default value for " + item.getKey() + " was produced");
```
Comment (knutwannheden) [inline core/deployment/src/main/java/io/quarkus/deployment/steps/ConfigGenerationBuildStep.java:101]: I have stumbled over this validation a few times in the past, since I tried to use this mechanism to set up default values for various config properties which then sometimes conflicted with properties set by other extensions. Specifically, I tried to set a default for the dev-services Docker image name this way.

It seems like this validation no longer exists now and that it may be a case of last build item wins. Meanwhile I found a different solution using a custom config source, but due to the indeterminism it may make sense to keep this validation in place somewhere. Thoughts?
