### PR TITLE
Move reflection and serialization configuration from Feature to json

### LINKED ISSUE #29693: MethodTooLargeException when too many ReflectiveClassBuildItem are producer
### Describe the bug

For the project camel-quarkus, I'm working on an extension allowing to marshall and unmarshall SWIFT messages by leveraging the library https://github.com/prowide/prowide-iso20022. 

The problem with this library is the fact that it contains more than 3 thousand classes that must be registered for reflection. With the current code, we end up with an error of type:
```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:2.15.0.CR1:build (quarkus-build) on project camel-quarkus-integration-test-swift: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.deployment.steps.NativeImageFeatureStep#generateFeature threw an exception: org.objectweb.asm.MethodTooLargeException: Method too large: io/quarkus/runner/Feature.registerForReflection (Lorg/graalvm/nativeimage/hosted/Feature$BeforeAnalysisAccess;)V
[ERROR] 	at org.objectweb.asm.MethodWriter.computeMethodInfoSize(MethodWriter.java:2088)
[ERROR] 	at org.objectweb.asm.ClassWriter.toByteArray(ClassWriter.java:511)
[ERROR] 	at io.quarkus.gizmo.ClassCreator.writeTo(ClassCreator.java:219)
[ERROR] 	at io.quarkus.gizmo.ClassCreator.close(ClassCreator.java:230)
[ERROR] 	at io.quarkus.deployment.steps.NativeImageFeatureStep.generateFeature(NativeImageFeatureStep.java:727)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
[ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:829)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

### Expected behavior

No failure even with several thousands of classes to register for reflection

### Actual behavior

We get a `MethodTooLargeException` when trying to get a native image.

### How to Reproduce?

1 . Checkout the branch `4220/camel-swift-extension` of https://github.com/apache/camel-quarkus
2. Go to `integration-tests/swift`
3. Execute the command `mvn clean install -Pnative`

The pending PR is https://github.com/apache/camel-quarkus/pull/4315

### Output of `uname -a` or `ver`

Darwin LT-C02CP37VMD6R 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "11.0.17" 2022-10-18 OpenJDK Runtime Environment GraalVM CE 22.3.0 (build 11.0.17+8-jvmci-22.3-b08) OpenJDK 64-Bit Server VM GraalVM CE 22.3.0 (build 11.0.17+8-jvmci-22.3-b08, mixed mode, sharing)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

main

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by zakkak**
This has the following benefits:

1. It's easier to debug/inspect reflection and serialization configuration by looking at a json file instead of having to decompile a generated `Feature` class and figure out what's going on
2. It implicitly avoids issues like https://github.com/quarkusio/quarkus/issues/29693

### Performance considerations

In a [related zulip chat discussion](https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Json.20library.20to.20use.20in.20core.3F) some concerns about performance where brought up so I am adding some comments on that as well.

This patch should only affect native image generation times (not runtime). This PR only affects how we inform `native-image` about the classes we would like to register for reflection and serialization. With this PR we hand a json file to `native-image` and ask it to parse it and do the necessary registrations for us. Before this PR we were explicitly invoking the GRAAL VM API to do the registrations our selves.

According to my measurements the transition from explicitly invoking the API versus passing a json file doesn't have a significant impact on the native image generation times.

#### Results using the API:
```
reflect-ser-config-API.txt:Finished generating 'quarkus-integration-test-main-999-SNAPSHOT-runner' in 4m 35s.
reflect-ser-config-API.txt:Finished generating 'quarkus-integration-test-main-999-SNAPSHOT-runner' in 4m 34s.
reflect-ser-config-API.txt:Finished generating 'quarkus-integration-test-main-999-SNAPSHOT-runner' in 4m 21s.
reflect-ser-config-API.txt:Finished generating 'quarkus-integration-test-main-999-SNAPSHOT-runner' in 4m 20s.
reflect-ser-config-API.txt:Finished generating 'quarkus-integration-test-main-999-SNAPSHOT-runner' in 4m 33s.

reflect-ser-config-API.txt:                        13.6s (4.9% of total time) in 57 GCs | Peak RSS: 7.40GB | CPU load: 6.08
reflect-ser-config-API.txt:                        15.5s (5.6% of total time) in 60 GCs | Peak RSS: 7.47GB | CPU load: 6.05
reflect-ser-config-API.txt:                        15.5s (5.9% of total time) in 64 GCs | Peak RSS: 7.52GB | CPU load: 6.25
reflect-ser-config-API.txt:                        13.4s (5.1% of total time) in 60 GCs | Peak RSS: 7.45GB | CPU load: 6.19
reflect-ser-config-API.txt:                        16.5s (6.0% of total time) in 65 GCs | Peak RSS: 7.46GB | CPU load: 6.11
```

#### Results using the json file
```
reflect-ser-config-json.txt:Finished generating 'quarkus-integration-test-main-999-SNAPSHOT-runner' in 4m 23s.
reflect-ser-config-json.txt:Finished generating 'quarkus-integration-test-main-999-SNAPSHOT-runner' in 4m 21s.
reflect-ser-config-json.txt:Finished generating 'quarkus-integration-test-main-999-SNAPSHOT-runner' in 4m 18s.
reflect-ser-config-json.txt:Finished generating 'quarkus-integration-test-main-999-SNAPSHOT-runner' in 4m 19s.
reflect-ser-config-json.txt:Finished generating 'quarkus-integration-test-main-999-SNAPSHOT-runner' in 4m 22s.

reflect-ser-config-json.txt:                        15.8s (6.0% of total time) in 64 GCs | Peak RSS: 7.54GB | CPU load: 6.28
reflect-ser-config-json.txt:                        14.4s (5.5% of total time) in 62 GCs | Peak RSS: 7.37GB | CPU load: 6.21
reflect-ser-config-json.txt:                        13.8s (5.3% of total time) in 61 GCs | Peak RSS: 7.42GB | CPU load: 6.25
reflect-ser-config-json.txt:                        15.0s (5.8% of total time) in 63 GCs | Peak RSS: 7.52GB | CPU load: 6.29
reflect-ser-config-json.txt:                        14.5s (5.5% of total time) in 62 GCs | Peak RSS: 7.50GB | CPU load: 6.23
```

Relates to https://github.com/quarkusio/quarkus/issues/25975
Fixes: https://github.com/quarkusio/quarkus/issues/29693

cc @essobedo

### CODE REVIEW

**Comment by essobedo** [comment]
Thx for sharing 🙏  One small question: How did you fix the issues related to optional services which cause several native tests to fail (kafka and graphql)?

Indeed the difference between before and this PR, is the fact that the classes were registered only if the class could be initialized (indeed calling `getDeclaredConstructors`, `getDeclaredMethods` and `getDeclaredFields` force the initialization of the class) but with the json file approach the classes are registered without beeing initialized which causes side effects.

To workaround the problem, I propose to be able to define conditions https://github.com/essobedo/quarkus/commit/d7bbed37f638cf1ac2985d71f54ecc44de429e41 WDYT?

**Comment by zakkak** [comment]
> Thx for sharing pray One small question: How did you fix the issues related to optional services which cause several native tests to fail (kafka and graphql)?

I probably didn't. I only tested with a few integration tests, so I probably never crossed these issues.

> Indeed the difference between before and this PR, is the fact that a class was registered only if it could be initialized 

Hmmm, that's a good point. I guess we should either way remove classes that can't be initialized.

> (indeed calling `getDeclaredConstructors`, `getDeclaredMethods` and `getDeclaredFields` force the initialization of the class) but with the JSON file approach the classes are registered without being initialized which causes side effects.

In Quarkus we ask anything reachable to be build-time initialized, so I am not sure that holds in Quarkus.

> To workaround the problem, I propose to be able to define conditions [essobedo@d7bbed3](https://github.com/essobedo/quarkus/commit/d7bbed37f638cf1ac2985d71f54ecc44de429e41) WDYT? As you can see, [the build is not yet over](https://github.com/essobedo/quarkus/actions/runs/3702594988/jobs/6273507310) but all the native tests pass

Nice, I like the addition of the conditions but it also makes me wonder... Don't we know what's reachable and what's not at the deployment phase of Quarkus? Why do we need to offset this to `native-image`? Is there any way to have the class reachable in one **native** run and not in another?

**Comment by essobedo** [comment]
> Nice, I like the addition of the conditions but it also makes me wonder... Don't we know what's reachable and what's not at the deployment phase of Quarkus? Why do we need to offset this to `native-image`? Is there any way to have the class reachable in one **native** run and not in another?

It is what I thought at first too, so before adding it to the JSON file, I tried to initialize the class first but in practice it makes even more tests to fail due to a native compilation issue so obviously, there is a difference in terms of available classes between the deployment phase and the native compilation. TBH I did not dig much to understand the difference especially because I believed that it is still interesting to have a way to add a condition on class registration, we then get even more control than before.

**Comment by essobedo** [comment]
Maybe I missed something so let's try again https://github.com/essobedo/quarkus/commit/b352685410b67adb6218172fc41e8adae983beac and see the results of the build

**Comment by zakkak** [comment]
Well, I am curious to see what makes the failing to register classes to be requested in the first place and see if we can fix it there.

**Comment by zakkak** [comment]
> Well, I am curious to see what makes the failing to register classes (e.g. `org.apache.kafka.common.security.oauthbearer.secured.OAuthBearerValidatorCallbackHandler`) to be requested in the first place and see if we can fix it there.

OK so it looks like such classes are added using generic getters like in https://github.com/quarkusio/quarkus/blob/e12ebe19253498a834d99968c72ced4075acfb2d/extensions/kafka-client/deployment/src/main/java/io/quarkus/kafka/client/deployment/KafkaProcessor.java#L433

The class exists in the Quarkus index (i.e. it's reachable), but Quarkus doesn't know it can't be loaded due to missing dependencies, so there indeed doesn't seem to exist a smart way to avoid getting it in the candidates list in the first place.

**Comment by essobedo** [comment]
> Well, I am curious to see what makes the failing to register classes (e.g. `org.apache.kafka.common.security.oauthbearer.secured.OAuthBearerValidatorCallbackHandler`) to be requested in the first place and see if we can fix it there.

Please note that in theory, AFAIU, the class `OAuthBearerValidatorCallbackHandler` is only meant to be used for the inter-broker communication so it should not be registered at all but adding a condition make it more flexible

**Comment by zakkak** [comment]
> Please note that in theory, AFAIU, the class `OAuthBearerValidatorCallbackHandler` is only meant to be used for the inter-broker communication so it should not be registered at all but adding a condition make it more flexible

It's not clear to me what the best approach would be here. The condition is indeed a generic that can allow us to overcome such issues, but on the other hand Quarkus should avoid registering blindly classes even if they can be build-time initialized as this is adding overhead to the application.

I think as far as this PR is concerned  I am going to cherry pick your commit with the conditional registration.

**Comment by mkouba** [comment]
The **Native Tests - Messaging1** job fails with `java.lang.NoClassDefFoundError: org/jose4j/keys/resolvers/VerificationKeyResolver` which is very likely related to the build-time initialization discussion, right?

**Comment by essobedo** [comment]
> The **Native Tests - Messaging1** job fails with `java.lang.NoClassDefFoundError: org/jose4j/keys/resolvers/VerificationKeyResolver` which is very likely related to the build-time initialization discussion, right?

Yeah we know, it is what I mention in this comment https://github.com/quarkusio/quarkus/pull/29886#issuecomment-1352918508

**Comment by essobedo** [comment]
Here is the kind of error you get if you initialize the class during the build deployment phase https://github.com/essobedo/quarkus/actions/runs/3704534875/jobs/6277704690#step:12:482

File: core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageReflectConfigStep.java [hunk 1]
```diff
@@ -169,17 +181,22 @@ static final class ReflectionInfo {
...
+            this(false, false, false, null, false);
+        }
+
+        private ReflectionInfo(boolean constructors, boolean methods, boolean fields, String typeReachable,
+                boolean serialization) {
             this.methods = methods;
             this.fields = fields;
+            this.typeReachable = typeReachable;
             this.constructors = constructors;
-            this.weak = weak;
```
Comment (essobedo) [inline core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageReflectConfigStep.java]: Good idea 👍

File: core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageReflectConfigStep.java [hunk 2]
```diff
@@ -0,0 +1,204 @@
...
+                json.put("methods", methodsArray);
+            }
+            if (info.fields) {
+                json.put("allDeclaredFields", true);
+            } else if (!info.fieldSet.isEmpty()) {
+                JsonArrayBuilder fieldsArray = Json.array();
+                for (String fieldName : info.fieldSet) {
+                    JsonObjectBuilder field = Json.object();
+                    field.put("name", fieldName);
+                    fieldsArray.add(field);
```
Comment (essobedo) [inline core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageReflectConfigStep.java:114]:
```suggestion
                    fieldsArray.add(Json.object().put("name", fieldName));
```

File: core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageSerializationConfigStep.java [hunk 3]
```diff
@@ -0,0 +1,63 @@
...
+                Collections.addAll(serializableClasses, classNames);
+            }
+        }
+
+        JsonObjectBuilder root = Json.object();
+        JsonArrayBuilder types = Json.array();
+        for (String serializableClass : serializableClasses) {
+            JsonObjectBuilder json = Json.object();
+            json.put("name", serializableClass);
+            types.add(json);
```
Comment (essobedo) [inline core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageSerializationConfigStep.java:40]:
```suggestion
            types.add(Json.object().put("name", serializableClass));
```

File: core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageSerializationConfigStep.java [hunk 4]
```diff
@@ -0,0 +1,63 @@
...
+        }
+        root.put("types", types);
+
+        JsonArrayBuilder lambdaCapturingTypes = Json.array();
+        if (!lambdaCapturingTypeBuildItems.isEmpty()) {
+            for (LambdaCapturingTypeBuildItem i : lambdaCapturingTypeBuildItems) {
+                JsonObjectBuilder lambdaCapturingType = Json.object();
+                lambdaCapturingType.put("name", i.getClassName());
+                lambdaCapturingTypes.add(lambdaCapturingType);
```
Comment (essobedo) [inline core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageSerializationConfigStep.java:49]:
```suggestion
                lambdaCapturingTypes.add(Json.object().put("name", i.getClassName()));
```

**Review by essobedo — APPROVED** [review]
👍 Awesome! Just some cosmetic remarks

**Comment by essobedo** [comment]
The build passed so I guess that the PR is ready for review

**Comment by zakkak** [comment]
cc @dmlloyd @n1hility @Sanne in case they can forsee issues with this change.

File: core/deployment/src/main/java/io/quarkus/deployment/builditem/nativeimage/ReflectiveClassBuildItem.java [hunk 5]
```diff
@@ -118,8 +100,9 @@ public boolean isConstructors() {
         return constructors;
     }
 
+    @Deprecated
```
Comment (mkouba) [inline core/deployment/src/main/java/io/quarkus/deployment/builditem/nativeimage/ReflectiveClassBuildItem.java:103]: We should add a note why it's deprecated and whether we're going to remove it in a future version of quarkus...

The same applies to `finalFieldsWritable()`.

File: core/deployment/src/main/java/io/quarkus/deployment/builditem/nativeimage/ReflectiveClassConditionBuildItem.java [hunk 6]
```diff
@@ -0,0 +1,29 @@
...
+
+import io.quarkus.builder.item.MultiBuildItem;
+
+/**
+ * Used to define a condition to register a class for reflection in native mode only when a specific type is reachable
+ */
+public final class ReflectiveClassConditionBuildItem extends MultiBuildItem {
+
+    private final String className;
+    private final String typeReachable;
```
Comment (mkouba) [inline core/deployment/src/main/java/io/quarkus/deployment/builditem/nativeimage/ReflectiveClassConditionBuildItem.java:11]: What exactly does this field represent? Is it a type that needs to be reachable in order to register the class for reflection? 

Maybe we could add an example to the javadoc?

File: core/deployment/src/main/java/io/quarkus/deployment/steps/ReflectiveHierarchyStep.java [hunk 7]
```diff
@@ -214,7 +214,6 @@ private void addClassTypeHierarchy(CombinedIndexBuildItem combinedIndexBuildItem
                         .builder(name.toString())
                         .methods(true)
                         .fields(true)
-                        .finalFieldsWritable(doFinalFieldsNeedToBeWritable(info, finalFieldsWritable))
```
Comment (mkouba) [inline core/deployment/src/main/java/io/quarkus/deployment/steps/ReflectiveHierarchyStep.java:217]: Shouldn't we remove the `doFinalFieldsNeedToBeWritable()` method as well?

File: core/deployment/src/main/java/io/quarkus/deployment/builditem/nativeimage/ReflectiveClassConditionBuildItem.java (hunk 6 above)
Comment (essobedo) [reply core/deployment/src/main/java/io/quarkus/deployment/builditem/nativeimage/ReflectiveClassConditionBuildItem.java:11]: > What exactly does this field represent? Is it a type that needs to be reachable in order to register the class for reflection?

In this case, it is exactly what you understood. In practice, it could be used as a condition for any kind of metadata entry but for this use case, it is good enough (more details [here](https://www.graalvm.org/22.2/reference-manual/native-image/metadata/#specifying-metadata-with-json)).

File: core/deployment/src/main/java/io/quarkus/deployment/builditem/nativeimage/ReflectiveClassBuildItem.java (hunk 5 above)
Comment (essobedo) [reply core/deployment/src/main/java/io/quarkus/deployment/builditem/nativeimage/ReflectiveClassBuildItem.java:106]: We could mention that `finalIsWritable` and `allowUnsafeAccess` are deprecated since GraalVM 21.2.0 and no more used. See the note, I quote: "Parameters {@code finalIsWritable} and {@code allowUnsafeAccess} no longer serve a purpose." Source https://github.com/oracle/graal/blob/vm-21.2.0/sdk/src/org.graalvm.nativeimage/src/org/graalvm/nativeimage/hosted/RuntimeReflection.java#L107-L116

Comment (essobedo) [reply core/deployment/src/main/java/io/quarkus/deployment/builditem/nativeimage/ReflectiveClassBuildItem.java:107]: Warning in 21.1, it is still used as you can see here https://github.com/oracle/graal/blob/vm-21.1.0/sdk/src/org.graalvm.nativeimage/src/org/graalvm/nativeimage/hosted/RuntimeReflection.java#L121-L123

File: core/deployment/src/main/java/io/quarkus/deployment/steps/ReflectiveHierarchyStep.java (hunk 7 above)
Comment (zakkak) [reply core/deployment/src/main/java/io/quarkus/deployment/steps/ReflectiveHierarchyStep.java:217]: Done

File: core/deployment/src/main/java/io/quarkus/deployment/builditem/nativeimage/ReflectiveClassConditionBuildItem.java (hunk 6 above)
Comment (zakkak) [reply core/deployment/src/main/java/io/quarkus/deployment/builditem/nativeimage/ReflectiveClassConditionBuildItem.java:11]: Done

File: core/deployment/src/main/java/io/quarkus/deployment/builditem/nativeimage/ReflectiveClassBuildItem.java (hunk 5 above)
Comment (zakkak) [reply core/deployment/src/main/java/io/quarkus/deployment/builditem/nativeimage/ReflectiveClassBuildItem.java:107]: Done

File: core/deployment/src/main/java/io/quarkus/deployment/builditem/nativeimage/ReflectiveClassConditionBuildItem.java (hunk 6 above)
Comment (zakkak) [reply core/deployment/src/main/java/io/quarkus/deployment/builditem/nativeimage/ReflectiveClassConditionBuildItem.java:11]: @mkouba correct. This is following the graalvm json schema (see https://www.graalvm.org/latest/reference-manual/native-image/metadata/#specifying-metadata-with-json), not sure it's worth documenting in Quarkus as well.

Comment (mkouba) [reply core/deployment/src/main/java/io/quarkus/deployment/builditem/nativeimage/ReflectiveClassConditionBuildItem.java:11]: I think that we should at least add the link...

File: core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageSerializationConfigStep.java [hunk 8]
```diff
@@ -0,0 +1,59 @@
...
+import io.quarkus.builder.Json.JsonObjectBuilder;
+import io.quarkus.deployment.annotations.BuildProducer;
+import io.quarkus.deployment.annotations.BuildStep;
+import io.quarkus.deployment.builditem.GeneratedResourceBuildItem;
+import io.quarkus.deployment.builditem.nativeimage.LambdaCapturingTypeBuildItem;
+import io.quarkus.deployment.builditem.nativeimage.ReflectiveClassBuildItem;
+
+public class NativeImageSerializationConfigStep {
+
+    @BuildStep
```
Comment (mkouba) [inline core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageSerializationConfigStep.java:22]: Shouldn't we use `@BuildStep(onlyIf = NativeOrNativeSourcesBuild.class)` instead?

File: core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageReflectConfigStep.java [hunk 9]
```diff
@@ -0,0 +1,202 @@
...
+import io.quarkus.deployment.builditem.nativeimage.ForceNonWeakReflectiveClassBuildItem;
+import io.quarkus.deployment.builditem.nativeimage.ReflectiveClassBuildItem;
+import io.quarkus.deployment.builditem.nativeimage.ReflectiveClassConditionBuildItem;
+import io.quarkus.deployment.builditem.nativeimage.ReflectiveFieldBuildItem;
+import io.quarkus.deployment.builditem.nativeimage.ReflectiveMethodBuildItem;
+import io.quarkus.deployment.builditem.nativeimage.ServiceProviderBuildItem;
+
+public class NativeImageReflectConfigStep {
+
+    @BuildStep
```
Comment (mkouba) [inline core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageReflectConfigStep.java:27]: `@BuildStep(onlyIf = NativeOrNativeSourcesBuild.class)`?

File: core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageSerializationConfigStep.java (hunk 8 above)
Comment (zakkak) [reply core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageSerializationConfigStep.java:22]: It makes sense, but I am not sure. The `generateFeature` (which generates the native image feature previously used for the same reason) in `NativeImageFeatureStep` doesn't use this `onlyIf`.

Comment (zakkak) [reply core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageSerializationConfigStep.java:22]: Actually non of the build steps named `io.quarkus.deployment.steps.NativeImage*` seems to come with this condition.

Comment (mkouba) [reply core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageSerializationConfigStep.java:22]: > It makes sense, but I am not sure. The `generateFeature` (which generates the native image feature previously used for the same reason) in `NativeImageFeatureStep` doesn't use this `onlyIf`.

Yes, because it produces `GeneratedNativeImageClassBuildItem` and `JPMSExportBuildItem` which are only consumed when a native image is built. 

Here you produce the `GeneratedResourceBuildItem` which is also consumed when the fast-jar is generated... You can try to run some app in the dev mode and check the [build steps report](https://github.com/quarkusio/quarkus/blob/main/TROUBLESHOOTING.md#analysing-build-steps-execution-time) if the build step is executed.

Comment (zakkak) [reply core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageSerializationConfigStep.java]: Thanks for the clarifications! This is now fixed.

File: core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageReflectConfigStep.java (hunk 9 above)
Comment (zakkak) [reply core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageReflectConfigStep.java]: Done

**Review by mkouba — APPROVED** [review]
Looks good but it's quite an important change so I think that we should get another pair of eyes...

**Comment by mkouba** [comment]
Also we might need to squash the commits...

**Comment by maxandersen** [comment]
@sanne and @n1hility comments on this - I understood you had reasons to ensure we still would want to use features for at least some extensions as not all can be expressed by a static json.

**Comment by dmlloyd** [comment]
> @sanne and @n1hility comments on this - I understood you had reasons to ensure we still would want to use features for at least some extensions as not all can be expressed by a static json.

It is correct that static JSON blobs in libraries is not an adequate solution for us. However dynamically generating the JSON config is, for the most part, functionally similar to generating features as far as I can tell.

**Comment by geoand** [comment]
These large json files don't actually end up in the native binary do they?

**Comment by Sanne** [comment]
> These large json files don't actually end up in the native binary do they?

No they won't - however if they are huge there will be lots of other bloat in there. So even if it's going to be less troublesome to have a big list, I suggest please keep working on making these small.

**Comment by Sanne** [comment]
> @Sanne and @n1hility comments on this - I understood you had reasons to ensure we still would want to use features for at least some extensions as not all can be expressed by a static json.

I have no concerns. There might be an occasional situation in which we still need a more advanced API, but we can still use those tactically. In the meantime, it certainly makes sense to have these large lists stored in a resource rather than in bytecode - I'm not a fan of the JSON format for this but since it's a stable API provided by GraalVM, might as well leverage the existing capability.

But let's also keep our options open, should we need more flexibility: I suppose we might end up using a combination of JSon resources and API calls for when more advanced features are needed.

**Comment by mkouba** [comment]
> > These large json files don't actually end up in the native binary do they?
> 
> No they won't - however if they are huge there will be lots of other bloat in there. So even if it's going to be less troublesome to have a big list, I suggest please keep working on making these small.

The thing is that the generated `Feature` class is also huge, esp. when you need to register a lot of classes for reflection.

**Comment by maxandersen** [comment]
> 



> The thing is that the generated `Feature` class is also huge, esp. when you need to register a lot of classes for reflection.

I think that is the point sanne is making - no matter if we use Features or json to register classes for reflection we should do what we can to keep them at a minimum.  Thus ask is that we don't just keep adding classes to load because we now can as no upper limit; and that when needing to use Features look into continue optimizing the generated code.

**Comment by essobedo** [comment]
I hope that I'm the only one, but TBH I'm a bit lost with all the opposite feedback regarding the status of this PR, does it mean that this approach is rejected in favor of pushing the limits of the Feature class generation by reducing its size? How to decide? Cast a vote?

**Comment by mkouba** [comment]
> does it mean that this approach is rejected in favor of pushing the limits of the Feature class generation by reducing its size?

I don't think so. I believe that the consensus is that we will need both: the generated json file (for simple registrations) and the generated `Feature` (for more dynamic/complex stuff).

**Comment by maxandersen** [comment]
The hesitance is simply that https://github.com/quarkusio/quarkus/issues/25975 was referenced and here the suggestion is that we should not use or reduce the use of API approach. I'm saying that it is fine we provide the option of generating json list but it dow not mean we should not use API approach when needed. On top - be aware that just because we now can register much longer list of classes it should not be used as a solution over doing proper vetting of what gets registered. If we don't we will over time loose RSS and performance gains.

Thus yes, +1 on the fix but just want to be sure we treat this issue as solving the problem fully.

**Comment by zakkak** [comment]
Now that we seem to have a consensus we will need to solve another issue before merging this PR.

Since we no longer wrap the registrations in try-catch blocks we get warnings like the following (which is good, see https://github.com/quarkusio/quarkus/issues/26162):

```
Warning: Could not resolve com.sun.xml.internal.bind.v2.ContextFactory for reflection configuration. Reason: java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory.
Warning: Could not resolve io.quarkus.smallrye.openapi.deployment.OpenApiConfigMapping for reflection configuration. Reason: java.lang.ClassNotFoundException: io.quarkus.smallrye.openapi.deployment.OpenApiConfigMapping.
```

As we don't want users to suddenly get warnings they are not responsible for we need to go through these warnings one by one and fix/work-around them as needed.

**Comment by essobedo** [comment]
Regarding `io.quarkus.smallrye.openapi.deployment.OpenApiConfigMapping`, I'm wondering in which case it makes sense to register for reflection a class that is in the deployment module? Maybe it should rather be in the runtime module?

**Comment by essobedo** [comment]
> As we don't want users to suddenly get warnings they are not responsible for we need to go through these warnings one by one and fix/work-around them as needed.

OK, let me try to propose a fix/workaround for each of them

**Comment by zakkak** [comment]
@essobedo I integrated your changes following the approach discussed in https://github.com/essobedo/quarkus/commit/8173e45d8dcd9377ffc2196d14bc257ef21a6d68#r93681106

I am waiting for @radcortez 's feedback in https://github.com/essobedo/quarkus/commit/4e306db6b7aa4c27c31962f43064ffbf3f36d830#commitcomment-93668682 to proceed with the integration of the `OpenApiConfigMapping` fix as well.

Early feedback is welcome :)

File: extensions/mailer/deployment/src/main/java/io/quarkus/mailer/deployment/MailerProcessor.java [hunk 10]
```diff
@@ -68,16 +69,22 @@ ExtensionSslNativeSupportBuildItem activateSslNativeSupport() {
...
+                        && x.getArtifactId().equalsIgnoreCase("vertx-mail-client"))) {
+            // We must register the auth provider used by the Vert.x mail clients
+            reflectiveClass.produce(new ReflectiveClassBuildItem(true, true,
+                    "io.vertx.ext.mail.impl.sasl.AuthDigestMD5",
+                    "io.vertx.ext.mail.impl.sasl.AuthCramSHA256",
+                    "io.vertx.ext.mail.impl.sasl.AuthCramSHA1",
+                    "io.vertx.ext.mail.impl.sasl.AuthCramMD5",
+                    "io.vertx.ext.mail.impl.sasl.AuthDigestMD5",
+                    "io.vertx.ext.mail.impl.sasl.AuthPlain",
+                    "io.vertx.ext.mail.impl.sasl.AuthLogin"));
```
Comment (essobedo) [inline extensions/mailer/deployment/src/main/java/io/quarkus/mailer/deployment/MailerProcessor.java:86]: The logic will be more complex than that since `AuthCram` seems to replace `AuthCramSHA256`, `AuthCramSHA1`, and `AuthCramMD5` and `AuthDigest` seems to replace `AuthDigestMD5` and `AuthDigestMD5 ` starting from 3.8.0. Even if the versions 3.8.0- are no more supported, the name of the classes have changed as you can see [here](https://github.com/vert-x3/vertx-mail-client/tree/5817da6d218ace197706383744cd73f32d9c8f12/src/main/java/io/vertx/ext/mail/impl/sasl)

File: extensions/schema-registry/apicurio/avro/deployment/src/main/java/io/quarkus/apicurio/registry/avro/ApicurioRegistryAvroProcessor.java [hunk 11]
```diff
@@ -14,27 +15,36 @@ FeatureBuildItem feature() {
...
+                    "io.apicurio.registry.serde.avro.strategy.TopicRecordIdStrategy"));
+        }
+
+        if (curateOutcomeBuildItem.getApplicationModel().getDependencies().stream().anyMatch(
+                x -> x.getGroupId().equalsIgnoreCase("io.apicurio")
+                        && x.getArtifactId().equalsIgnoreCase("apicurio-registry-serde-common"))) {
+            reflectiveClass.produce(new ReflectiveClassBuildItem(true, true, true,
+                    "io.apicurio.registry.serde.strategy.SimpleTopicIdStrategy",
+                    "io.apicurio.registry.serde.strategy.TopicIdStrategy",
+                    "io.apicurio.registry.serde.DefaultSchemaResolver",
```
Comment (essobedo) [inline extensions/schema-registry/apicurio/avro/deployment/src/main/java/io/quarkus/apicurio/registry/avro/ApicurioRegistryAvroProcessor.java:42]: Do you confirm that you don't test the version on purpose? You accept to get the warning in case the version is 2.2+, right?

File: extensions/kafka-client/deployment/src/main/java/io/quarkus/kafka/client/deployment/KafkaProcessor.java [hunk 12]
```diff
@@ -336,25 +330,30 @@ private void handleOpenTracing(BuildProducer<ReflectiveClassBuildItem> reflectiv
...
-                "org.keycloak.representations.AccessTokenResponse",
-                "org.keycloak.representations.IDToken",
-                "org.keycloak.representations.JsonWebToken",
-                "org.keycloak.jose.jwk.JSONWebKeySet",
-                "org.keycloak.jose.jwk.JWK",
-                "org.keycloak.json.StringOrArrayDeserializer",
-                "org.keycloak.json.StringListMapDeserializer"));
+        if (curateOutcomeBuildItem.getApplicationModel().getDependencies().stream().anyMatch(
+                x -> x.getGroupId().equalsIgnoreCase("org.keycloak")
+                        && x.getArtifactId().equalsIgnoreCase("keycloak-core"))) {
```
Comment (dmlloyd) [inline extensions/kafka-client/deployment/src/main/java/io/quarkus/kafka/client/deployment/KafkaProcessor.java:344]: I've noticed this pattern a few times in this PR. Isn't there a better/more efficient way to look for an artifact in the dependency set? Since it *is* a set, it should be feasible to do a `contains()` AFAICT, which should run in constant time even for large projects, and the case-insensitivity seems unnecessary as well.

**Review by dmlloyd — COMMENTED** [review]
Looks OK to me in principle, though it's notable that we're making the `Json` API in `io.quarkus.builder` be public. I just have one comment.

File: extensions/mailer/deployment/src/main/java/io/quarkus/mailer/deployment/MailerProcessor.java (hunk 10 above)
Comment (zakkak) [reply extensions/mailer/deployment/src/main/java/io/quarkus/mailer/deployment/MailerProcessor.java:86]: Interesting, so do you think it's worth adding a version check or shall we make these weak (and add the new class names as well)?

File: extensions/schema-registry/apicurio/avro/deployment/src/main/java/io/quarkus/apicurio/registry/avro/ApicurioRegistryAvroProcessor.java (hunk 11 above)
Comment (zakkak) [reply extensions/schema-registry/apicurio/avro/deployment/src/main/java/io/quarkus/apicurio/registry/avro/ApicurioRegistryAvroProcessor.java:42]: No, that slipped away as well. Thanks for the catch!

File: extensions/kafka-client/deployment/src/main/java/io/quarkus/kafka/client/deployment/KafkaProcessor.java (hunk 12 above)
Comment (zakkak) [reply extensions/kafka-client/deployment/src/main/java/io/quarkus/kafka/client/deployment/KafkaProcessor.java:344]: Thanks for the suggestion David I will try to improve it.

Comment (essobedo) [reply extensions/kafka-client/deployment/src/main/java/io/quarkus/kafka/client/deployment/KafkaProcessor.java:344]: I'm afraid it is not that simple since you only compare one part of the coordinates of a dependency (group id and artifact id) the rest (scope, version, type...) is ignored so the method `contains` will always return `false`. One thing that could be done is to propose a method that groups the dependencies by the pair (groupId, artifactid) but to be efficient, you will need a cache and you will need to invalidate it any time the list of dependencies is updated, it adds some complexity with all the consequences behind. I'm wondering if it is really needed within the context of this PR knowing that it is a global approach that we see all over the place in the Quarkus code base, maybe a dedicated task for it would be more efficient, WDYT?

File: extensions/mailer/deployment/src/main/java/io/quarkus/mailer/deployment/MailerProcessor.java (hunk 10 above)
Comment (essobedo) [reply extensions/mailer/deployment/src/main/java/io/quarkus/mailer/deployment/MailerProcessor.java:86]: Knowing that comparing versions is something that [has already been done ](https://github.com/quarkusio/quarkus/blob/main/extensions/schema-registry/confluent/avro/deployment/src/main/java/io/quarkus/confluent/registry/avro/ConfluentRegistryAvroProcessor.java#L51-L59), I tend to say it's worth adding but it is only my humble opinion

Comment (zakkak) [reply extensions/mailer/deployment/src/main/java/io/quarkus/mailer/deployment/MailerProcessor.java:86]: It looks like the version used is 4.3.6 and we don't have to worry about other versions as the dependency is pulled due to the following dependency tree:

```
[INFO] +- io.quarkus:quarkus-mailer:jar:999-SNAPSHOT:compile
[INFO] |  +- io.quarkus:quarkus-vertx:jar:999-SNAPSHOT:compile
[INFO] |  |  ...
[INFO] |  \- io.smallrye.reactive:smallrye-mutiny-vertx-mail-client:jar:2.29.0:compile
[INFO] |     \- io.vertx:vertx-mail-client:jar:4.3.6:compile
```

the `io.smallrye.reactive:smallrye-mutiny-vertx-mail-client` version is fixed in [the quarkus bom file](https://github.com/quarkusio/quarkus/blob/65c3f7df50da58a1840629ada95f990666e46278/bom/application/pom.xml#L57) and `io.smallrye.reactive:smallrye-mutiny-vertx-mail-client` defines the `io.vertx:vertx-mail-client` version in https://github.com/smallrye/smallrye-mutiny-vertx-bindings/blob/b70234921a911286872df03e1504efad7b2d2319/pom.xml#L49

Comment (zakkak) [reply extensions/mailer/deployment/src/main/java/io/quarkus/mailer/deployment/MailerProcessor.java:86]: @cescoffier WDYT? Do we still to register these classes for reflection? It looks like they have not been registered for quiet a while...

Shall we register:
```
            reflectiveClass.produce(new ReflectiveClassBuildItem(true, true,
                    "io.vertx.ext.mail.impl.sasl.AuthCram",
                    "io.vertx.ext.mail.impl.sasl.AuthDigest",
                    "io.vertx.ext.mail.impl.sasl.AuthLogin",
                    "io.vertx.ext.mail.impl.sasl.AuthPlain"));
```
for vertx-mail-client 4.3.6 onwards?

File: extensions/kafka-client/deployment/src/main/java/io/quarkus/kafka/client/deployment/KafkaProcessor.java (hunk 12 above)
Comment (dmlloyd) [reply extensions/kafka-client/deployment/src/main/java/io/quarkus/kafka/client/deployment/KafkaProcessor.java:344]: Makes sense; maybe we should think of developing a data structure which is backed by a map that is keyed by group & artifact IDs if this is a common pattern.

File: extensions/schema-registry/apicurio/avro/deployment/src/main/java/io/quarkus/apicurio/registry/avro/ApicurioRegistryAvroProcessor.java (hunk 11 above)
Comment (zakkak) [reply extensions/schema-registry/apicurio/avro/deployment/src/main/java/io/quarkus/apicurio/registry/avro/ApicurioRegistryAvroProcessor.java:42]: Revisiting this I see that quarkus [is using 2.3.1.Final](https://github.com/quarkusio/quarkus/blob/65c3f7df50da58a1840629ada95f990666e46278/bom/application/pom.xml#L200) but in integration-tests/kafka-avro the version [is pinned to 1.2.2.Final](https://github.com/quarkusio/quarkus/blob/65c3f7df50da58a1840629ada95f990666e46278/integration-tests/kafka-avro/pom.xml#L17)

My understanding is that we care for boh 1.x and 2.x support. Is it OK to assume we only need to support 2.3.1 from 2.x and "any version" from 1.x? cc @Ladicek @phillip-kruger

**Review by dmlloyd — APPROVED** [review]

**Comment by zakkak** [comment]
> Now that we seem to have a consensus we will need to solve another issue before merging this PR.
> 
> Since we no longer wrap the registrations in try-catch blocks we get warnings like the following (which is good, see https://github.com/quarkusio/quarkus/issues/26162):
> 
> ```
> Warning: Could not resolve com.sun.xml.internal.bind.v2.ContextFactory for reflection configuration. Reason: java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory.
> Warning: Could not resolve io.quarkus.smallrye.openapi.deployment.OpenApiConfigMapping for reflection configuration. Reason: java.lang.ClassNotFoundException: io.quarkus.smallrye.openapi.deployment.OpenApiConfigMapping.
> ```
> 
> As we don't want users to suddenly get warnings they are not responsible for we need to go through these warnings one by one and fix/work-around them as needed.

As this turned out to be more complex than I anticipated I am going to move the resolution of these issues in separate PRs. Most of them should be tackled independently of this PR anyway.

**Comment by essobedo** [comment]
Regarding the move of OpenApiConfigMapping to runtime, it is included in the PR [Allow to register ConfigSourceInterceptor at runtime or buildtime](https://github.com/quarkusio/quarkus/pull/30055)

**Comment by n1hility** [comment]
> > As we don't want users to suddenly get warnings they are not responsible for we need to go through these warnings one by one and fix/work-around them as needed.
> 
> As this turned out to be more complex than I anticipated I am going to move the resolution of these issues in separate PRs. Most of them should be tackled independently of this PR anyway.
> 
> I suggest we **DON'T merge** this before the corresponding PRs fixing the warnings get merged.

@zakkak What if instead of using their JSON format, which won't cover all of our use cases anyway (we need features), we used our own lightweight format loaded by a dynamic feature? Instead of thousands of byteode calls (status quo), it would be a much smaller loop

This would allow us to specially handle warnings (also knowing where they actually occur), and it would allow us to optimize the format and processing of it however we like, vs a gigantic single text file that gets out of control. 

wdyt? (also @dmlloyd @Sanne ?)

**Comment by zakkak** [comment]
> @zakkak What if instead of using their JSON format, which won't cover all of our use cases anyway (we need features for advanced cases if nothing else), we used our own lightweight format loaded by a dynamic feature? Instead of thousands of bytecode calls (status quo), it would be a much smaller load loop sequence.

@n1hility It feels like re-inventing the wheel to me. When using GraalVM's JSON format/schema, GraalVM actually does exactly what you describe. Creating our own schema, and a feature to parse it and register the classes, seems unjustified to me **at this point**. 
Can you please provide examples where GraalVM's existing JSON schema expressiveness might be limiting Quarkus?

> This would allow us to specially handle warnings (also knowing where they actually occur) and it would allow us to optimize the format and processing of it however we like, vs a gigantic single text file that gets out of control.

I don't see how that would be different when using a different format. My understanding is that you suggest moving checks in the native-image feature (instead of using GraalVM's one which is clueless about some special handling we might want), but I think we can perform most (if not all) the checks we need during `deployment` (i.e. before even adding classes to be registered in the JSON file). After all, this PR doesn't remove any handling (other than blindly ignoring ClassNotFoundExceptions while registering classes for reflection) done by the dynamic feature, so I don't see the need for something like this.

Regarding the gigantic single text file FWIW we can already split it in multiple JSON files using the GraalVM schema. GraalVM supports loading configurations from multiple such files:

```
-H:ReflectionConfigurationFiles=<string>*    One or several (comma-separated) paths to JSON files that specify which program elements should be made available via
                                             reflection. [Extra help available]
-H:SerializationConfigurationFiles=<string>* One or several (comma-separated) paths to JSON files that specify lists of serialization configurations. [Extra help
                                             available]
```

**Comment by dmlloyd** [comment]
I guess we would be talking about a lightweight binary format, not a text or JSON format. Using a customized binary format, we could do things like compress package and class names (think of jandex's `DotName` for example) and support structural patterns ("all nested classes of Foo" or "all subtypes of Bar") which are difficult to represent exactly with pattern strings. We could also match by class loader. The downside would be that debugging might be somewhat more difficult.

In any event, one thing worth noting is that this is essentially a protocol that we are using in order to communicate out-of-band information from the Quarkus augmentation process to the GraalVM native image process during a single build. Thus it does not need a strong schema or compatibility guarantees; it's not an API. But it does need to be fast and light.

It would be interesting to see how much time it takes during a build for GraalVM to parse and process the JSON.

I don't think there is really any getting away from having a fairly large number of types, fields, methods, proxy classes, etc. in the file though - other than actually making a positive effort to reduce this in upstream projects. Maybe we should print a shame warning when an extension registers too many things.

**Comment by zakkak** [comment]
> I guess we would be talking about a lightweight binary format, not a text or JSON format.

How many types do we expect to see listed in such files? My understanding is that the common case is in the hundreds while exceptional cases go up to the thousands. For instance in https://github.com/quarkusio/quarkus/issues/29693 @essobedo says that they are trying to register more than 3000 classes for reflection.

Given such numbers, I don't expect the text format becoming a bottleneck any time soon, so I fail to see the need for a lightweight binary format that will indeed make debugging much harder.

> Using a customized binary format, we could do things like compress package and class names (think of jandex's `DotName` for example) and support structural patterns ("all nested classes of Foo" or "all subtypes of Bar") which are difficult to represent exactly with pattern strings. 

This can be done either during "deployment" or during `native-image` building. Shifting to a _custom_ approach like this seems necessary only if we want to do it during `native-image` building and not during "deployment" for some reason.

> We could also match by class loader.

That indeed looks like something that could only be done during `native-image` building, but do we have any use-case for it?

> The downside would be that debugging might be somewhat more difficult.

Agreed, if we end up going that way we will certainly need to provide some tooling for debugging.

> In any event, one thing worth noting is that this is essentially a protocol that we are using in order to communicate out-of-band information from the Quarkus augmentation process to the GraalVM native image process during a single build. Thus it does not need a strong schema or compatibility guarantees; it's not an API. But it does need to be fast and light.
> 
> It would be interesting to see how much time it takes during a build for GraalVM to parse and process the JSON.

Such measurements should contain two parts of the compilation:

1. During _deployment_: The time spent to generate the JSON file vs the time spent to dynamically generate the corresponding bytecode (current state)
2. During `native-image` build: The time spent to parse and process the JSON file vs the time spent to run the dynamic feature generated in deployment.

Unfortunately it's not trivial to get this kind of measurements. The trivial way to compare would be end-to-end build times.

It is also worth keeping in mind that these parts:
1. are only executed at build time and do not impact run-time
2. are expected to comprise only a tiny part of the total time spent in native-image compilation

My non-scientific and pretty basic comparison using the integration test `main`, presented in the description of this PR, hints that the parsing and processing of the JSON file is no worse than the current approach.
FWIW the `main` integration test registers 511 types for reflection which results in a minified JSON file of ~60Kb.

I wonder if @essobedo can provide some numbers from the application that registers 3000+ classes.

> I don't think there is really any getting away from having a fairly large number of types, fields, methods, proxy classes, etc. in the file though - other than actually making a positive effort to reduce this in upstream projects. Maybe we should print a shame warning when an extension registers too many things.

:D

**To sum up**: I can see the value in implementing a custom _protocol_ in theory, but I am not sure there is a need for it at the moment.  This PR seems to me like an overall improvement to the _current approach_, and it fixes some existing issues (e.g. https://github.com/quarkusio/quarkus/issues/29693 and https://github.com/quarkusio/quarkus/issues/26162). 

At this point I would suggest we decide whether:
1. we are going to merge this PR and move the discussion about a _custom protocol_ to a new issue for future consideration.
2. not merge this PR and use the discussions in it about a _custom protocol_ as a description of how the related issues should be fixed instead.

**Comment by Sanne** [comment]
I do think it's very important that we retain full control of the "protocol". I think it's ok to leverage the existing json infrastructure (even though I hate json..) as a convenience, but this is acceptable only as an implementation detail: we need to be able to evolve / override such aspects as necessary even if there's no specific need today.

In terms of custom compact formats, my inner geek gets excited but admittedly let's remember that this is just a protocol during compilation - we're not going to ship such resources within the binary right? Therefore I'd not consider it a priority, with debuggability and opportunities for code reuse providing higher value at this time.


> At this point I would suggest we decide whether we plan to:
> 1. merge this PR and move the discussion about a custom protocol to a new issue for future consideration.

+1 , with the understanding that the use of the json format should never leak into higher level APIs so that this can be replaced at first need.

Incidentally, I don't think there's need to open an issue for an hypotethical future protocol: I'm confident we'll figure it out if ever such need materializes.

**Comment by essobedo** [comment]
> I wonder if @essobedo can provide some numbers from the application that registers 3000+ classes.

Here are some numbers.

For the tests, I used `GraalVM 22.3.0 Java 17 CE` on an MBP with `2.6 GHz Intel Core i7 6 cores` as CPU and `32 Go` of RAM.

First, to evaluate the overhead of the registration of 25 000+ classes, 170 000+ fields, and 380 000+ methods, I first launched a test with my extension that doesn't do any registration, then I executed the same test but with the registrations using this code for the JSON approach and [my original proposal](https://github.com/quarkusio/quarkus/pull/29694/commits/5161027cebd6251a74c0fdc3b93d9cd1ff033fad) for the "protocol" approach.

Here are the results:

|  Test Description        | Total Time | Total Memory  | Generated File Size |
|----------------------|-----------|----------------|---------------------|
| Without Registration  | 131 s         | 6.3 Go               |                                   |
|  Json                            | 472 s        | 10.2 Go             |  3.7 Mo                      |
|  Protocol                      | 445 s        |  10.5 Go            |  2.0 Mo                     |

As you can see, the difference between the 2 approaches is not really significant at least in terms of total time and total memory.

**Comment by zakkak** [comment]
> As you can see, the difference between the 2 approaches is not really significant at least in terms of total time and total memory.

Well, I would say that 27 seconds is kind of significant :) but this number is not necessarily reflecting the difference between the two approaches, it could be "noise" if the reported numbers are the result of a single run.
Does the difference remain the same when running multiple times?

**Comment by essobedo** [comment]
TBH my goal was only to give some global ideas, not to provide formal results but ok let me do formal tests and change the results consequently

**Comment by essobedo** [comment]
Under the same conditions as [previously described ](https://github.com/quarkusio/quarkus/pull/29886#issuecomment-1380141452), I launched the test 5 times to compare the 2 approaches and got the following results:

|  Test Description        | Min Total Time | Avg Total Time | Max Total Time | Min Total Memory  | Avg Total Memory | Max Total Memory 
|----------------------|-----------|----------------|---------------------|-----------|----------------|---------------------|
|  Json                            | 367 s        | **424 s**                |  567 s                        | 10.4 Go        | **10.6 Go**                |  11.1 Go                        |
|  Protocol                      | 408 s        |  **437 s**           |  479s                     | 9.4 Go        | **10.2 Go**                |  10.6 Go                        |

What I have noticed during the tests, is the fact that the results mostly depend on the analysis phase because it tends to consume 100 % of all my cores available.

Those results show once again that the difference between the 2 approaches is not significant (less than 4 %) in terms of total memory and total time.

File: extensions/schema-registry/apicurio/avro/deployment/src/main/java/io/quarkus/apicurio/registry/avro/ApicurioRegistryAvroProcessor.java (hunk 11 above)
Comment (zakkak) [reply extensions/schema-registry/apicurio/avro/deployment/src/main/java/io/quarkus/apicurio/registry/avro/ApicurioRegistryAvroProcessor.java]: Ping @Ladicek @phillip-kruger. Can you please have a look at this question? ^^

Comment (Ladicek) [reply extensions/schema-registry/apicurio/avro/deployment/src/main/java/io/quarkus/apicurio/registry/avro/ApicurioRegistryAvroProcessor.java]: Umm, it's been a while since I worked on this.

So `integration-tests/kafka-avro` verifies support for Apicurio Registry 1.x libraries; the tests for Apicurio Registry 2.x libraries is in `integration-tests/kafka-avro-apicurio2`.

We use Apicurio Registry 1.2.2 libraries in `integration-tests/kafka-avro`, because Apicurio Registry 1.3 libraries require some extra support which is a bit hacky (https://github.com/quarkiverse/quarkus-apicurio-registry-client). I believe we want[ed] to drop support for Apicurio Registry 1.x libraries at some point, together with `integration-tests/kafka-avro`. I'm not sure if that time has come.

For `integration-tests/kafka-avro-apicurio2`, I believe we want to use the same version of Apicurio Registry 2.x libraries that we compile against elsewhere.

Also CC @ozangunalp @carlesarnal

**Comment by essobedo** [comment]
Once merged, it could be nice to propose a (dedicated?) build item that matches [with the JSON model of GraalVM for the reflection](https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/configure/ReflectionConfigurationParser.java#L100-L178) in order to have a more fine-grained configuration which could help to reduce the size of the native image in some cases. This way, among other things, we would be able to register either public, declared and/or queried methods/fields/constructor instead of only declared ones.

**Comment by essobedo** [comment]
> I suggest we **DON'T merge** this before the corresponding PRs fixing the warnings get merged.
> 
> So far these are:
> 
> * [Remove reflective class registrations for Java 8 #30015](https://github.com/quarkusio/quarkus/pull/30015)
> * [Make registrations of removed (in version 3) kafka classes optional #30016](https://github.com/quarkusio/quarkus/pull/30016)
> * [Update reflection registrations of vertx mail classes #30017](https://github.com/quarkusio/quarkus/pull/30017)
> * [Move log4j-api to correct quarkus module and add condition for jackson-module-jaxb-annotations registrations #30018](https://github.com/quarkusio/quarkus/pull/30018)
> * [Register keycloak classes for reflection only when keycloak-core present #30019](https://github.com/quarkusio/quarkus/pull/30019)
> * [Register bouncycastle classes for reflection only when present #30020](https://github.com/quarkusio/quarkus/pull/30020)
> * [Register kafka serializers and schemaregistry classes only when present #30021](https://github.com/quarkusio/quarkus/pull/30021)
> * [Register properly OpenApiConfigMapping at runtime #30055](https://github.com/quarkusio/quarkus/pull/30055)
> * and there is one more in the baking for [Apicurio](https://github.com/quarkusio/quarkus/pull/29886#discussion_r1054712793).

FYI all the PRs have been merged

**Comment by zakkak** [comment]
> FYI all the PRs have been merged

All except for the [apicurio one](https://github.com/quarkusio/quarkus/pull/29886#discussion_r1054712793).

File: extensions/schema-registry/apicurio/avro/deployment/src/main/java/io/quarkus/apicurio/registry/avro/ApicurioRegistryAvroProcessor.java (hunk 11 above)
Comment (zakkak) [reply extensions/schema-registry/apicurio/avro/deployment/src/main/java/io/quarkus/apicurio/registry/avro/ApicurioRegistryAvroProcessor.java]: Ping @ozangunalp @carlesarnal

Do you have any additional feedback on this? If not I will proceed based on the above comment.

Comment (carlesarnal) [reply extensions/schema-registry/apicurio/avro/deployment/src/main/java/io/quarkus/apicurio/registry/avro/ApicurioRegistryAvroProcessor.java]: No additional feedback other than what Ladislav already said. Apicurio 1.x is no longer supported on our end and users are highly encouraged to move to 2.x. Maybe Quarkus 3 is the perfect moment to drop the 1.x support, but in the end, it's up to the Quarkus maintainers (basically @Ladicek and @ozangunalp in this case, I guess) to make that decision.

**Review by radcortez — APPROVED** [review]

**Review by n1hility — APPROVED** [review]
