### PR TITLE
Properly construct instance of LateBoundBatchSpanProcessor

### LINKED ISSUE #29987: OTel `LateBoundSampler` logs warning if using Liquibase and JDBC instrumentation
### Describe the bug

I was irritated by the following message very early during boot and started digging:
```
WARN  [io.qua.ope.run.tra.LateBoundSampler] (JPA Startup Thread) No Sampler delegate specified, no action taken.
```
Turns out that when you have [JDBC instrumentation](https://quarkus.io/guides/opentelemetry#jdbc) _and_ Liquibase migration at startup (using the same datasource and OTEL driver as the rest of the app), the sampler is apparently not set yet, hence the warning.

### Expected behavior

No warning from OTEL extension, even if using "startup time features" such as the liquibase extension.

### Actual behavior

Warning logged

### How to Reproduce?

[liquibase-quickstart-with-otel.zip](https://github.com/quarkusio/quarkus/files/10280148/liquibase-quickstart-with-otel.zip)

`mvn quarkus:dev`

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.15.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

`LateBoundBatchSpanProcessor` issues a similar warning (if otlp export is not disabled).

Of course it doesn't make much sense to trace liquibase JDBC operations, but simply using the regular app datasource is the default setup for simple cases.

### PR DESCRIPTION
**Pull request by geoand**
This is now done entirely in a CDI producer method which is then fully initialized when OpenTelemetry autoconfigures itself

Fixes: #29987 (which with newer Quarkus versions is even [more problematic](https://github.com/quarkusio/quarkus/issues/29987#issuecomment-1621594578))

Detailed explanation:

* The first commit fixes the case where the DataSource cannot properly be constructed because the `OpenTelemetry` has not yet been created by CDI. This could happen because there was not declaration of the need for that bean when constructing the DataSource bean, only programmatic lookup.
* The second commits actually fixes the issue with the missing delegate in a pretty straightforward way: We move the creation of `LateBoundBatchSpanProcessor` to a synthetic bean - prior to this commit the `LateBoundBatchSpanProcessor` bean was created from a CDI producer but was then "updated" by a recorder. These two operations are obviously not "atomic", meaning that the `OpenTelemetry` bean that consumed `LateBoundBatchSpanProcessor` would see the bean in the intermediate state - where it was created but not updated.
    * This commit also includes the removal of various intermediate build items whose only purpose was to pass data between the various steps. These are no longer necessary, since everything can be accomplished with the combination of CDI and the `BeanContainer` in recorder methds.
    * Furthermore, this commit makes sure that we no longer use `Arc.container()...` in recorder methods as these are extremely sensitive to timing issues - by utilizing synthetic beans and the `BeanContainer` in recorder methods we overcome this problem.
* The third commit builds on the second one to make the configuration of the `SpanProcessor`s of `OpenTelemetry` even more reasonable. We essentially only include  `LateBoundBatchSpanProcessor` in the `OpenTelemetry` bean if a delegate has been set. 

_Future work_: The creation of the `OpenTelemetry` can be done via a synthetic bean as this allows us complete control over the injection points and does not suffer from any bean creating timing issues (assuming of course the creation is done properly).
This would essentially take what is not done in `OpenTelemetryProducer` and move it into a recorder method that includes all the creation logic (including the logic that currently resides in the synthetic bean for `LateBoundBatchSpanProcessor`)

### CODE REVIEW

**Comment by geoand** [comment]
Correct, the bean initialization is not forced at build time anymore

**Review by radcortez — APPROVED** [review]

**Comment by brunobat** [comment]
This makes everything much simpler. Not sure about the increased startup time... Most likely not noticeable.
I need to check possible implications on the OpenTelemetryProducer, but I won't have time today.

**Comment by geoand** [comment]
No rush!

**Comment by gsmet** [comment]
If it gets merged, should it be backported?

**Comment by geoand** [comment]
I dunno, I'm on the fence...

**Comment by radcortez** [comment]
I think we can hold this until 3.3.

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/TracerRecorder.java [hunk 1]
```diff
@@ -27,24 +17,13 @@ public class TracerRecorder {
     public static final Set<String> dropStaticResourceTargets = new HashSet<>();
 
     /* STATIC INIT */
-    public RuntimeValue<Optional<IdGenerator>> createIdGenerator() {
-        BeanManager beanManager = Arc.container().beanManager();
-
-        Instance<IdGenerator> idGenerator = beanManager.createInstance()
```
Comment (brunobat) [inline extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/TracerRecorder.java:33]: This might break idGeneration. We don't have a proper test. Will come up with something, to make sure.

**Review by brunobat — CHANGES_REQUESTED** [review]
I need to create a new test before approving this PR.

**Comment by brunobat** [comment]
@radcortez @gsmet I'd like this back-ported to 3.2.* because these changes affect core parts of the extension and 3.2.* will run for a long time, potentially causing complex merges in the future.

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/TracerRecorder.java (hunk 1 above)
Comment (geoand) [reply extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/TracerRecorder.java:33]: Wouldn't we already have this problem in the current version?

**Comment by geoand** [comment]
If we want this backported, we probably should do it as soon as possible instead of waiting for late 3.2.z releases

**Review by brunobat — APPROVED** [review]
Let's be pragmatic then. 
I'll not be able to do this while at the RivieraDev conf. 
Any iD generator issue can be dealt in this new issue: https://github.com/quarkusio/quarkus/issues/34668

**Comment by geoand** [comment]
I'm going to have to redo this one unfortunately since there are plenty of conflicts... 

Furthermore, this will conflict with #34647

**Comment by geoand** [comment]
Here is my proposal for this one:

I redo it after https://github.com/quarkusio/quarkus/pull/34647 is in, in order to avoid additional conflicts.
For 3.2, I open a new PR specifically targetting the 3.2 branch. 

WDYT?

**Comment by radcortez** [comment]
Sure.

**Comment by geoand** [comment]
Should be working now

**Comment by geoand** [comment]
But there is another thing I want to improve if possible

**Comment by geoand** [comment]
Should be good to go now

**Comment by geoand** [comment]
In future, I would like to move the creation of the `OpenTelemetry` bean out of `OpenTelemetryProducer` and into a synthetic bean, but I'll leave that for some other time because it's a lot of mechanical work that is not absolutely necessary at the moment

**Comment by geoand** [comment]
Oh, I didn't know about those tests...

**Comment by geoand** [comment]
The JDBC telemetry stuff is pretty broken (it only worked by accident before) so I need to see what can be done...

**Comment by brunobat** [comment]
Those tests are a bit brittle but beware that they end up finding a lot of problems.

**Comment by geoand** [comment]
The tests themselves are great and they indeed show a real problem here.

**Comment by brunobat** [comment]
Ok @geoand. The interdependencies with vert.x in `InstrumentationRecorder.createTraces(..)`
Will an OTel Producer as a synthetic bean work with dev mode reload?

**Comment by geoand** [comment]
All tests pass so this is good from my end.

**Review by brunobat — APPROVED** [review]
Thanks @geoand !
