### PR TITLE
Dev UI Base path fix in case of non-application root set to dev*

### LINKED ISSUE #42022: Setting root path starting with `/dev` breaks the dev-ui
### Describe the bug

When setting a root path for the application with `quarkus.http.root-path` or for `quarkus.http.non-application-root-path` that is starting with `/dev` it breaks the `dev-ui`.

For example setting it to `/devil` breaks the ui.

It doesn't redirect to the expected urls, and redirects them to `/dev-ui`.

It seems to be caused when the ui tries to get the basePath such as here for example
https://github.com/quarkusio/quarkus/blob/6ece69038ce2a283dc6d1fdc39bab4560cd7b8a0/extensions/vertx-http/dev-ui-resources/src/main/resources/dev-ui/controller/router-controller.js#L139

Maybe it is some legacy behaviour from V1 dev ui path ?

### How to Reproduce?

Create a quarkus app with vertx http, then add a root path containing dev, and run the dev mode
```shell 
quarkus create app -x 'quarkus-rest' quarkus-dev-redirect -P 3.12.3
cd  quarkus-dev-redirect
quarkus dev -Dquarkus.http.non-application-root-path=/devil/q
```
When connecting to the dev ui on http://localhost:8080/devil/q/dev-ui it will redirect you to http://localhost:8080/dev-ui/extensions .

### Quarkus version or git rev

3.12.3

### PR DESCRIPTION
**Pull request by phillip-kruger**
Fix #42022

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Review by cescoffier — APPROVED** [review]

File: extensions/vertx-http/dev-ui-resources/src/main/resources/dev-ui/controller/jsonrpc.js [hunk 1]
```diff
@@ -126,7 +126,7 @@ export class JsonRpc {
                 JsonRpc.serverUri = "ws:";
             }
             var currentPath = window.location.pathname;
-            currentPath = currentPath.substring(0, currentPath.indexOf('/dev')) + "/dev-ui";
+            currentPath = currentPath.substring(0, currentPath.indexOf('/dev-ui')) + "/dev-ui";
```
Comment (gsmet) [inline extensions/vertx-http/dev-ui-resources/src/main/resources/dev-ui/controller/jsonrpc.js:129]: I think to be completely safe, it would have to be refined a bit:
- you would have to forbid `dev-ui` as a root path
- or be sure you would have `/dev-ui` after the first iteration and use `lastIndexOf` - but if you have additional path segments, you can't really be sure

Also, I think you should:
- check if the string ends with `/dev-ui` and do what you're doing
- if not, I would search for `/dev-ui/` instead.

Otherwise, you improved the situation for sure but you can still break it relatively easily if you're unlucky (root path of `dev-ui-whatever` for instance).

Comment (phillip-kruger) [reply extensions/vertx-http/dev-ui-resources/src/main/resources/dev-ui/controller/jsonrpc.js]: I applied you suggestions. I tested with setting the root to both `/dev-ui` and `/dev-ui-whatever`.

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Thanks!
