### PR TITLE
Fix generation of Scheduler startmode enum tooltip

### LINKED ISSUE #37818: Scheduler start-mode enum not shown properly in scheduler config reference
### Describe the bug

In this page; https://quarkus.io/guides/scheduler-reference. The text of [quarkus.scheduler.start-mode](https://quarkus.io/guides/scheduler-reference#quarkus-scheduler_quarkus.scheduler.start-mode) is not shown properly

### Expected behavior

tooltip should be shown when we hover over the type, only the first element of the enum seems to show ok.

### Actual behavior

tooltip text shown not be shown unless item is hovered on.

### How to Reproduce?

n/a

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by michalvavrik**
fixes: #37818

I tested generation of Scheduler runtime config reference with / without this and this PR fixes the issue.

### CODE REVIEW

**Comment by michalvavrik** [comment]
Hmm, but I'll replace `System.lineSeparator()` with `\n` constant as for our use case it will probably be same.

File: core/processor/src/main/java/io/quarkus/annotation/processor/generate_doc/ConfigDocItemFinder.java [hunk 1]
```diff
@@ -496,7 +497,7 @@ private List<String> extractEnumValues(TypeMirror realTypeMirror, boolean useHyp
                     // Show enum constant description as a Tooltip
                     String javaDoc = enumJavaDocParser.parseConfigDescription(rawJavaDoc);
                     acceptedValues.add(String.format(Constants.TOOLTIP, enumValue,
-                            javaDoc.replace("<p>", Constants.EMPTY).replace("</p>", Constants.EMPTY)));
+                            javaDoc.replace("<p>", EMPTY).replace("</p>", EMPTY).replace(NEW_LINE, EMPTY)));
```
Comment (gsmet) [inline core/processor/src/main/java/io/quarkus/annotation/processor/generate_doc/ConfigDocItemFinder.java:500]: I would replace a new line with a space, ideally, to have both elements separated. But maybe we always have a space?

Comment (michalvavrik) [reply core/processor/src/main/java/io/quarkus/annotation/processor/generate_doc/ConfigDocItemFinder.java]: No, there is no way we could add it inside text. I just checked generated ASCII, HTML and did not mention there was no space between sentences (I see it now). Thank you, fixed.

**Review by gsmet — APPROVED** [review]
