### PR TITLE
Apply improvements to error handler page

### LINKED ISSUE #43642: Improve Quarkus error page handler
> Sorry, I should have been a bit more assertive in my review as I think we really should switch to wrapping. While this PR is an improvement over the existing behavior, having to scroll is really annoying, either when trying to see the whole line or even when copy/pasting the error.
> 
> We have a good example of that when pasting stack trace in GitHub with backticks, it can quickly get annoying and sometimes, I even switch to quoting so that you have the nice wrapping behavior.
> 
> @mcruzdev any chance you could create a follow-up PR with some wrapping instead as you seem to agree with it in your reaction? Thanks!

Hi @gsmet obviously! Another point that I would to talk about is `TemplateHtmlBuilder`, we Java code with HTML code together what is the possibility to change it to use Qute? 

This question above is for the future (maybe), I will create another PR that adds wrapping behavior, thank you!

_Originally posted by @mcruzdev in https://github.com/quarkusio/quarkus/issues/43552#issuecomment-2382954157_

### PR DESCRIPTION
**Pull request by mcruzdev**
## Why

This pull request was created after this pull request [discussion](https://github.com/quarkusio/quarkus/pull/43552).

## What

I am adding:

-  copy to clipboard button, to copy the stacktrace

[final.webm](https://github.com/user-attachments/assets/611a55e0-3064-44e6-a3e5-4694c70a7d7c)

- change the view mode (wrap and scroll)

image

Closes #43642

### CODE REVIEW

**Review by phillip-kruger — APPROVED** [review]

**Comment by phillip-kruger** [comment]
Very cool ! Any reason this is still in Draft ?

File: core/runtime/src/main/java/io/quarkus/runtime/TemplateHtmlBuilder.java [hunk 1]
```diff
@@ -15,33 +15,112 @@
...
+            <script>
+                const translations = {
+                    'en': {
+                        'toggleStackTrace': 'Toggle Stack Trace Order',
+                        'defaultStackTrace': 'Default to Reverse Ordered Stack Trace'
+                    },
+                    'pt': {
+                        'toggleStackTrace': 'Alternar Ordem do Stack Trace',
+                        'defaultStackTrace': 'Padrão para Stack Trace em Ordem Reversa'
+                    }
```
Comment (gsmet) [inline core/runtime/src/main/java/io/quarkus/runtime/TemplateHtmlBuilder.java:28]: I'm not entirely sure I want to start this. I could see how problematic it would be if we had a ton of translations and had to update one particular message.

I think the actions are sufficiently easy to understand for us to  not translate them and have a non-localized UI.
It's very technical.

File: core/runtime/src/main/java/io/quarkus/runtime/TemplateHtmlBuilder.java [hunk 2]
```diff
@@ -15,33 +15,112 @@
...
+
+                async function copyStacktrace() {
+                    const stacktrace = document.getElementById("stacktrace");
+                    const content = stacktrace.getElementsByTagName("code")[0];
+                    await navigator.clipboard.writeText(content.textContent);
+                }
+
+                function initStacktraceStyles() {
+                    document.querySelector("#stacktrace code > pre").setAttribute("data-viewmode", "scroll");
+                    stacktrace.querySelector("#stacktrace code").classList.add("scroll-code")
```
Comment (gsmet) [inline core/runtime/src/main/java/io/quarkus/runtime/TemplateHtmlBuilder.java:82]: Can we make wrap the default?

File: core/runtime/src/main/java/io/quarkus/runtime/TemplateHtmlBuilder.java [hunk 3]
```diff
@@ -165,11 +244,11 @@ public class TemplateHtmlBuilder {
...
     private static final String OPEN_IDE_LINK = "<div class='rel-stacktrace-item' onclick=\"event.preventDefault(); fetch('/q/open-in-ide/%s/%s/%d');\">";
 
-    private static final String ERROR_STACK = "    <div id=\"original-stacktrace\" class=\"trace hidden\">\n" +
+    private static final String ORIGINAL_STACK_TRACE = "    <div id=\"original-stacktrace\" class=\"trace hidden\">\n" +
             "<h3>The stacktrace below is the original. " +
-            "<a href=\"\" onClick=\"toggleStackTraceOrder(); return false;\">See the stacktrace in reversed order</a> (root-cause first)</h4>"
+            "<a href=\"\" onClick=\"toggleStackTraceOrder(); return false;\">See the stacktrace in reversed order</a> (root-cause first)</h3>"
             +
-            "        <code class=\"stacktrace\"><pre>%1$s<pre></code>\n" +
+            "        <code class=\"stacktrace\"><pre>%1$s</pre></code>\n" +
```
Comment (gsmet) [inline core/runtime/src/main/java/io/quarkus/runtime/TemplateHtmlBuilder.java:251]: Good catch!

File: core/runtime/src/main/java/io/quarkus/runtime/TemplateHtmlBuilder.java [hunk 4]
```diff
@@ -15,33 +15,112 @@
...
-            "		stElement.setAttribute('data-current-setting', 'reversed-stacktrace');\n" +
-            "		return;\n" +
-            "	}\n" +
-            "</script>\n";
+    private static final String SCRIPT_STACKTRACE_MANIPULATION = """
+            <script>
+                const translations = {
+                    'en': {
+                        'toggleStackTrace': 'Toggle Stack Trace Order',
+                        'defaultStackTrace': 'Default to Reverse Ordered Stack Trace'
```
Comment (gsmet) [inline core/runtime/src/main/java/io/quarkus/runtime/TemplateHtmlBuilder.java:23]: Can you drop the caps except for the first word? Thanks!

**Review by gsmet — CHANGES_REQUESTED** [review]
Nice work!

I required some small changes (sorry but when dealing with UI/UX, there's always a lot of nitpicking).

Also, I think the test failure might be related. Maybe the test needs some adjustments due to the changes made, I don't know.

**Review by gsmet — APPROVED** [review]
AFAICS, the intent looks good from my POV now, thanks!

@phillip-kruger I let you do a final check as quite some code has changed since you first reviewed.

**Review by phillip-kruger — APPROVED** [review]
