### PR TITLE
Ensure that connection issues can be handled in Reactive REST Client

### LINKED ISSUE #24364: Reactive REST Client NullPointerException
### Describe the bug

There seems to be a case where the header map in the ClientResponseContext is null. 

```
java.lang.NullPointerException
at org.jboss.resteasy.reactive.common.jaxrs.AbstractResponseBuilder.setAllHeaders(AbstractResponseBuilder.java:132)
at org.jboss.resteasy.reactive.client.handlers.ClientResponseCompleteRestHandler.mapToResponse(ClientResponseCompleteRestHandler.java:39)
at io.quarkus.rest.client.reactive.runtime.MicroProfileRestClientResponseFilter.filter(MicroProfileRestClientResponseFilter.java:35)
at org.jboss.resteasy.reactive.client.handlers.ClientResponseFilterRestHandler.handle(ClientResponseFilterRestHandler.java:20)
at org.jboss.resteasy.reactive.client.handlers.ClientResponseFilterRestHandler.handle(ClientResponseFilterRestHandler.java:9)
at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:141)
at org.jboss.resteasy.reactive.client.impl.RestClientRequestContext$1.lambda$execute$0(RestClientRequestContext.java:272)
at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.lang.Thread.run(Thread.java:833)
at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:597)
at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:194)
```

### GraalVM version (if different from Java)

22.0

### Quarkus version or git rev

2.7.4.Final/2.7.5.Final

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #24364

### CODE REVIEW

**Review by michalszynkiewicz — APPROVED** [review]

File: independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/handlers/ClientSendRequestHandler.java [hunk 1]
```diff
@@ -247,6 +248,10 @@ public void handle(Throwable failure) {
         }, new Consumer<>() {
             @Override
             public void accept(Throwable event) {
+                // set some properties to prevent NPEs down the chain
+                requestContext.setResponseHeaders(new MultivaluedTreeMap<>());
```
Comment (gastaldi) [inline independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/handlers/ClientSendRequestHandler.java:252]: Is this always the first handler invoked? Curious if the response headers could be overwritten if they were set previously

Comment (geoand) [reply independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/handlers/ClientSendRequestHandler.java:252]: It doesn't really matter if it gets overridden. All that matters in this case is that it's not null
