### PR TITLE
Intercept and report exceptions when using the WithSpan annotation

### LINKED ISSUE #33372: Error handling with @WithSpan (OpenTelemetry)
### Describe the bug

If an exception occurs in a method that's annotated with `@WithSpan`, the error won't be recorded in the trace.

### Expected behavior

Trace will contain error span.

### Actual behavior

Currently the error span is missing from the trace. Or in the reproducer's case the entire trace is missing.

### How to Reproduce?

Slightly modified `TracedResources` class from the OpenTelemetry quickstart. https://quarkus.io/guides/opentelemetry
```java
package org.acme.opentelemetry;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

import io.opentelemetry.instrumentation.annotations.WithSpan;
import org.jboss.logging.Logger;

@Path("/hello")
public class TracedResources {
    private static final Logger LOG = Logger.getLogger(TracedResources.class);

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello(){
        LOG.info("hello");
        doSomething();
        return "hello";
    }

    @WithSpan
    public String doSomething() {
        throw new RuntimeException("foo");
    }
}
```
When the app is running, execute the command `curl http://localhost:8080/hello` and look at the trace result.

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

openjdk version "17.0.5"

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by brunobat**
Fix #33372

### CODE REVIEW

File: extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/exporter/otlp/LateBoundBatchSpanProcessor.java [hunk 1]
```diff
@@ -18,7 +18,7 @@
 public class LateBoundBatchSpanProcessor implements SpanProcessor {
```
Comment (geoand) [inline extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/exporter/otlp/LateBoundBatchSpanProcessor.java:18]: Is this change in this file intended to be part of the change? 

If so, it looks sort of unrelated to the reported and should probably be a separate commit

**Review by geoand — APPROVED** [review]

**Comment by geoand** [comment]
Should this be backported?

**Comment by brunobat** [comment]
> Should this be backported?

No need, It's a minor improvement.
