### PR TITLE
Decorate stacktraces in dev mode error page

### LINKED ISSUE #37002: provide source file context for exception message
### Description

saw https://github.com/laech/java-stacksrc today

turns:

```
org.opentest4j.AssertionFailedError: expected: <hello> but was: <hi>
	at org.junit...
	at com.example.MyTest.hello(MyTest.java:24)
	...
```

into

```
org.opentest4j.AssertionFailedError: expected: <hello> but was: <hi>
	at org.junit...
	at com.example.MyTest.hello(MyTest.java:24)

	   22    @Test
	   23    void compareStrings() {
	-> 24      assertEquals("hello", "hi");
	   25    }

	...
```

would be awesome to hook into quarkus dev and have that printed in logs and on error page with option to turn on/off.

### Implementation ideas

The functionality is dead simple: https://github.com/laech/java-stacksrc/tree/main/core/src/main/java/nz/lae/stacksrc

3 files that just decorate any java stacktrace.

could even consider to just copy it in to avoid extra dependency.

hook in to JBoss logging of errors and the error page.

### PR DESCRIPTION
**Pull request by geoand**
- Closes: #37002

### CODE REVIEW

**Comment by maxandersen** [comment]
@phillip-kruger you wanna take this in?

**Comment by geoand** [comment]
🎉

**Comment by maxandersen** [comment]
this really works awesome.

one thing I noticed was that with some compile errors I seem to get ansi characters in the output?

with this:

```java
package org.acme;

import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;

@Path("/hello")
public class GreetingResource {

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        inter var;
       // if (System.currentTimeMillis()!=0) throw new RuntimeException();
        return "Hello from Quarkus REST";
    }
}
```

I got:


```
java.lang.RuntimeException: [91mCompilation Failed:
/Users/manderse/code/latestapp2/src/main/java/org/acme/GreetingResource.java:14: error: cannot find symbol
        inter var;
        ^
  symbol:   class inter
  location: class org.acme.GreetingResource[0m
	at io.quarkus.deployment.dev.JavaCompila
```

but 

```java
package org.acme;

import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;

@Path("/hello")
public class GreetingResource {

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        if (System.currentTimeMillis()!=0) throw new RuntimeException();
        return "Hello from Quarkus REST";
    }
}
```

gave me clean/no ansi:

```
java.lang.RuntimeException
	at org.acme.GreetingResource.hello(GreetingResource.java:14)

	   12      @Produces(MediaType.TEXT_PLAIN)
	   13      public String hello() {
	-> 14          if (System.currentTimeMillis()!=0) throw new RuntimeException();
	   15          return "Hello from Quarkus REST";
	   16      }


	at org.acme.GreetingResource$quarkusrestinvoker$hello_e747664148511e1e5212d3e0f4b40d45c56ab8a1.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reac
```

also - should we have original stacktrace link provide the *true* original without the injected locations?

**Comment by maxandersen** [comment]
for future - would be great to have those lines with know locations clickable to open in IDE :)

**Review by maxandersen — COMMENTED** [review]
+1 on this; if the ansi code is known issue already we should merge this as its really helpful IMO. 

the other suggestions are improvements on what is already nice.

**Comment by phillip-kruger** [comment]
@maxandersen I can not recreate the encoding issue ... 
I added a config to disable this in Dev Mode, or enable this in other modes: `quarkus.http.decorate-stacktraces=false`

**Comment by phillip-kruger** [comment]
Making the lines clickable to open an IDE is a bigger piece of work. The error page is not a Dev UI page, so it's not that easy.  However, looking at the log in Dev UI, you can click on it: 
clickable

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/HttpConfiguration.java [hunk 1]
```diff
@@ -289,6 +289,14 @@ public class HttpConfiguration {
     @ConfigItem
     public Map<String, FilterConfig> filter;
 
+    /**
+     * This will decorate the stacktrace to show the line in the code that cause the exception
+     * By default, this is enabled in Dev Mode and disabled in all other modes. Making this true will enable it in all mode
+     * and making this false will disable this in all modes.
+     */
+    @ConfigItem
+    public Optional<Boolean> decorateStacktraces;
```
Comment (maxandersen) [inline extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/HttpConfiguration.java:298]: Not fully convinced its good to allow enable this in prod up front as it will leak source code which could have security issues.

And the sources aren't available in prod anyway is it ? how will it get the sources?

**Review by maxandersen — CHANGES_REQUESTED** [review]
as we don't have options for disabling the reversal of stacktraces and there are security issues for prod - I suggest to make this pr have this feature enabled always in devmode and only add a option to disable in dev and enable in prod  as a follow up if we get feedback/usecase on it.

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/HttpConfiguration.java (hunk 1 above)
Comment (phillip-kruger) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/HttpConfiguration.java]: Good point. I changed to Dev Mode only.

**Review by maxandersen — APPROVED** [review]
Lgtm
