### PR TITLE
Throwing ForbiddenException if OidcUtils.findRoles throws an exception

### LINKED ISSUE #5750: quarkus-oidc throws an OIDCException when a token does not contain the `role-claim-path``
**Describe the bug**
In `application.properties`, we specify a custom `role-claim-path`: `quarkus.oidc.roles.role-claim-path=resource_access/your-client-id/roles`. 

When testing a token using this path (but with the wrong role), everything works as expected.
When testing tokens that do not have this path, it throws an `OIDCException: No claim exists at the path resource_access/your-client-id/roles at the path segment your-client-id`.

By "testing", I mean calling a JAX-RS endpoint (with the appropriate bearer token) that requires a role contained in this claim path.

```
[io.quarkus.vertx.http.runtime.QuarkusErrorHandler] HTTP Request to /access-rights failed, error id: 38f42768-bd07-4e7e-bcde-3d4bd3dc8e2d-1: io.quarkus.oidc.OIDCException: No claim exists at the path resource_access/your-client-id/roles at the path segment /your-client-id
    at io.quarkus.oidc.runtime.OidcUtils.findClaimValue(OidcUtils.java:60)
    at io.quarkus.oidc.runtime.OidcUtils.findClaimValue(OidcUtils.java:66)
    at io.quarkus.oidc.runtime.OidcUtils.findClaimWithRoles(OidcUtils.java:44)
    at io.quarkus.oidc.runtime.OidcUtils.findRoles(OidcUtils.java:21)
    at io.quarkus.oidc.runtime.OidcIdentityProvider$1.handle(OidcIdentityProvider.java:73)
    at io.quarkus.oidc.runtime.OidcIdentityProvider$1.handle(OidcIdentityProvider.java:53)
    at io.vertx.ext.auth.oauth2.impl.OAuth2AuthProviderImpl.lambda$decodeToken$3(OAuth2AuthProviderImpl.java:271)
    at io.vertx.ext.auth.oauth2.impl.OAuth2AuthProviderImpl.authenticate(OAuth2AuthProviderImpl.java:238)
    at io.vertx.ext.auth.oauth2.impl.OAuth2AuthProviderImpl.decodeToken(OAuth2AuthProviderImpl.java:269)
    at io.quarkus.oidc.runtime.OidcIdentityProvider.authenticate(OidcIdentityProvider.java:53)
    at io.quarkus.oidc.runtime.OidcIdentityProvider.authenticate(OidcIdentityProvider.java:23)
    at io.quarkus.oidc.runtime.OidcIdentityProvider_ClientProxy.authenticate(OidcIdentityProvider_ClientProxy.zig:349)
    at io.quarkus.security.runtime.QuarkusIdentityProviderManagerImpl.handleProvider(QuarkusIdentityProviderManagerImpl.java:121)
    at io.quarkus.security.runtime.QuarkusIdentityProviderManagerImpl.authenticate(QuarkusIdentityProviderManagerImpl.java:89)
    at io.quarkus.security.runtime.IdentityProviderManagerCreator_ProducerMethod_ipm_91f102be1b2a781216db8a81e6ab4b9b1a84f03c_ClientProxy.authenticate(IdentityProviderManagerCreator_ProducerMethod_ipm_91f102be1b2a781216db8a81e6ab4b9b1a84f03c_ClientProxy.zig:105)
    at io.quarkus.oidc.runtime.AbstractOidcAuthenticationMechanism.authenticate(AbstractOidcAuthenticationMechanism.java:27)
    at io.quarkus.oidc.runtime.BearerAuthenticationMechanism.authenticate(BearerAuthenticationMechanism.java:26)
    at io.quarkus.oidc.runtime.BearerAuthenticationMechanism_ClientProxy.authenticate(BearerAuthenticationMechanism_ClientProxy.zig:201)
    at io.quarkus.vertx.http.runtime.security.HttpAuthenticator.attemptAuthentication(HttpAuthenticator.java:66)
    at io.quarkus.vertx.http.runtime.security.HttpAuthenticator_ClientProxy.attemptAuthentication(HttpAuthenticator_ClientProxy.zig:150)
    at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$1.handle(HttpSecurityRecorder.java:35)
    at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$1.handle(HttpSecurityRecorder.java:24)
    at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
    at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
    at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:130)
    at io.quarkus.vertx.http.deployment.devmode.VertxHotReplacementSetup$2.handle(VertxHotReplacementSetup.java:75)
    at io.quarkus.vertx.http.deployment.devmode.VertxHotReplacementSetup$2.handle(VertxHotReplacementSetup.java:64)
    at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:330)
    at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
    at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
    at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:830)
```

**Expected behavior**
The endpoint should:
* return a 403
* and/or give the possibility to a `@Provider` (`ExceptionMapper`) to catch and handle this exception.

**Configuration**
```properties
quarkus.oidc.roles.role-claim-path=resource_access/your-client-id/roles
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64`
 - Output of `java -version`: `OpenJDK 64-Bit Server VM AdoptOpenJDK (build 13+33, mixed mode, sharing)`
 - Quarkus version or git rev: `1.0.0.Final`

### LINKED ISSUE #5826: Make sure the causes of the security exceptions are included
**Description**
Right now `ForbiddedException` and other exception classes do not accept the cause parameters.

**Implementation ideas**
See https://github.com/quarkusio/quarkus-security/issues/3 and https://github.com/quarkusio/quarkus-security/pull/4

### PR DESCRIPTION
**Pull request by sberyozkin**
Fixes #5750
Fixes #5826

This PR simply completes the future with `ForbiddenException`, instead of propagating `OIDCException`. Note `OidcUtils.findRoles` does not itself throw `ForbiddenException` because it is not guaranteed to be called during the authentication, but it logs a warning now.
`OidcUtilsTest` has a test confirming `OidcUtils.findRoles` throws an exception with the invalid path

### CODE REVIEW

**Comment by sberyozkin** [comment]
@gsmet Hi, if it is approved and looks good to you too then please consider it for 1.0.1.Final.
I need to go offline now so may not have time to react to the review comments today, but it is not a blocker issue, thanks

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java [hunk 1]
```diff
@@ -73,8 +75,8 @@ public void handle(AsyncResult<AccessToken> event) {
                     for (String role : OidcUtils.findRoles(clientId, config.getRoles(), token.accessToken())) {
                         builder.addRole(role);
                     }
-                } catch (Exception e) {
-                    result.completeExceptionally(e);
+                } catch (OIDCException e) {
+                    result.completeExceptionally(new ForbiddenException());
```
Comment (gsmet) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java]: What bugs me a bit is that we don't handle the other exceptions if they happen?

This probably needs to be discussed so will be a bit late for 1.0.1.

Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java]: @gsmet Hi Guillaume, yes, sure. FYI, inside OidcUtils.findRoles there is only unchecked exception which can happen which is `OIDCException` when some paths can not be resolved (all that code does is it iterates over already prepared JSONObject). If something else escapes then I'd consider enhancing `OidcUtils` further. 
However I can also add a RuntimeException catch to catch everything else ? Let me know what you think please, but yes, it can wait

Comment (loicmathieu) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java]: I would add the `OIDCException` as the cause of the `ForbuddenException` to not loose the exception context

Comment (loicmathieu) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java]: I'm OK with all other exceptions being not handled, they will all result to a ServerError. 
We only want authentication exceptions being transformed to ForbiddenException.

**Review by loicmathieu — CHANGES_REQUESTED** [review]

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java (hunk 1 above)
Comment (gsmet) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java]: Can we keep the previous branch too?

I mean having something like:
```
                } catch (OIDCException e) {
                    result.completeExceptionally(new ForbiddenException());
                } catch (Exception e) {
                    result.completeExceptionally(e);
                }
```

That would have my preference.

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcUtils.java [hunk 2]
```diff
@@ -57,15 +61,16 @@ private static Object findClaimValue(String claimPath, JsonObject json, String[]
...
+                throw new OIDCException();
             }
         } else if (step + 1 < pathArray.length) {
             if (claimValue instanceof JsonObject) {
                 int nextStep = step + 1;
                 return findClaimValue(claimPath, (JsonObject) claimValue, pathArray, nextStep, mustExist);
             } else {
-                throw new OIDCException("Claim value at the path " + claimPath + " is not a json object");
+                LOG.warn("Claim value at the path " + claimPath + " is not a json object");
+                throw new OIDCException();
```
Comment (gsmet) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcUtils.java]: Could you explain why you chose to do that this way? I.e. going from an exception message to a warn?

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java (hunk 1 above)
Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java]: @gsmet sure

**Comment by sberyozkin** [comment]
@loicmathieu 
> I would add the OIDCException as the cause of the ForbuddenException to not loose the exception context
Not possible at the moment, since `ForbiddenException` only has a default constructor and it is in a separate `quarkus-security` repositoryright now.

> I'm OK with all other exceptions being not handled...
Restoring that block would only make sure the future is cleanly completed exceptionally.

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcUtils.java (hunk 2 above)
Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcUtils.java]: @gsmet Please see my response to Loic, at the moment it is not possible to wrap the OIDC exception. I'll make it the error message again once `ForbiddenException`/etc are updated, does it sound OK ?

Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcUtils.java]: I'll open an issue to track it so as I don't forget

**Comment by loicmathieu** [comment]
@sberyozkin I tought it was the JAX-RS ForbiddenException ...
As soon as you create an issue to update the code later I'm OK with it.

**Review by loicmathieu — APPROVED** [review]

**Comment by sberyozkin** [comment]
@loicmathieu @gsmet FYI, #5826 
I'll do a quick PR for the quarkus-security as well
Thanks

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java (hunk 1 above)
Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java]: @gsmet done

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcUtils.java (hunk 2 above)
Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcUtils.java]: I'm going to do a small PR to the quarkus-security and will follow up with the updates to this code but also to other Quarkus code where the causes are not included for those exceptions

**Comment by sberyozkin** [comment]
@gsmet PR to quarkus-security has been submitted so if you prefer we can wait till it is released so that I update this PR accordingly. Or I can follow up with the #5626 fix (have assigned that issue to me), either way works for me, thanks

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcUtils.java (hunk 2 above)
Comment (stuartwdouglas) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcUtils.java]: FYI https://github.com/quarkusio/quarkus/pull/5952

**Comment by sberyozkin** [comment]
@gsmet, @loicmathieu Hi, FYI, I've now updated this PR to have the cause exception included across the Quarkus code :-), after Stuart has released the latest `quarkus-security`

**Review by gsmet — APPROVED** [review]
