### PR TITLE
Agroal - Only generate health checks for JDBC datasources

### LINKED ISSUE #37779: No healthcheck for default Agroal datasource if `quarkus.datasource.db-kind` is not set
### Describe the bug

Quarkus allows not setting `quarkus.datasource.db-kind` for the default datasource if there's only one JDBC extension in the classpath; if so, the `db-kind` is inferred automatically.

But when you do that, there is no healthcheck on the default datasource.

This doesn't seem to happen in dev mode, probably because `db-kind` is set by the dev service. It does happen in production.

### Expected behavior

Always have a healthcheck on the default datasource, at least when it's started/used.

### Actual behavior

No healthcheck on the default datasource when `quarkus.datasource.db-kind` is not set.

### How to Reproduce?

Just try with the quickstart: https://github.com/quarkusio/quarkus-quickstarts/tree/main/hibernate-orm-quickstart

You'll need to add the Smallrye Health extension.

Then build and start in prod:

```
$  curl http://localhost:8080/q/health
{
    "status": "UP",
    "checks": [
        {
            "name": "Database connections health check",
            "status": "UP",
            "data": {
                "<default>": "UP"
            }
        }
    ]
}
```

Then remove `%prod.quarkus.datasource.db-kind=postgresql` from `application.properties`, compile and start again:

```
$  curl http://localhost:8080/q/health
{
    "status": "UP",
    "checks": [
        {
            "name": "Database connections health check",
            "status": "UP"
        }
    ]
}
```

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

The bug is in https://github.com/quarkusio/quarkus/blob/main/extensions/datasource/runtime/src/main/java/io/quarkus/datasource/runtime/DataSourcesHealthSupportRecorder.java#L20-L22
We assume that a datasource is configured only if its `db-kind` config is set. Which is wrong for the default datasource.

### LINKED ISSUE #38934: Agroal Data Source Health check failing for reactive data source
### Describe the bug

When application defines a mix of datasources (Reactive & JDBC), health check fails with below error.

Works fine with Quarkus Version < 3.7. I think issue is introduced by https://github.com/quarkusio/quarkus/pull/38108

Sample config:

quarkus.datasource.db-kind=postgresql
quarkus.datasource.metrics.enabled=true
quarkus.datasource.jdbc=false
quarkus.datasource.reactive=true
## additional datasource for flyway migration
quarkus.datasource.migds.db-kind=postgresql
quarkus.datasource.migds.reactive=false
quarkus.datasource.migds.jdbc=true
quarkus.flyway.migds.clean-at-start=false
quarkus.flyway.migds.create-schemas=false
quarkus.flyway.migds.migrate-at-start=true
quarkus.flyway.migds.repair-at-start=true

### Expected behavior

Health check should return health status of both the datasources.

### Actual behavior

Start app using quarkus:dev

Test URL http://[localhost:8080/q/health](http://localhost:8080/q/health)

```
{
    "status": "DOWN",
    "checks": [
        {
            "name": "io.quarkus.agroal.runtime.health.DataSourceHealthCheck_ClientProxy",
            "status": "DOWN",
            "data": {
                "exceptionClass": "java.lang.IllegalArgumentException",
                "exceptionMessage": "No datasource named '<default>' exists",
                "rootCause": "No datasource named '<default>' exists"
            }
        },
        {
            "name": "Reactive PostgreSQL connections health check",
            "status": "UP",
            "data": {
                "<default>": "UP"
            }
        }
    ]
}
```

Errors in Logs

```
SRHCK01000: Error processing Health Checks: java.lang.IllegalArgumentException: No datasource named '<default>' exists
        at io.quarkus.agroal.runtime.DataSources.doCreateDataSource(DataSources.java:165)
        at io.quarkus.agroal.runtime.DataSources$1.apply(DataSources.java:145)
        at io.quarkus.agroal.runtime.DataSources$1.apply(DataSources.java:142)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
        at io.quarkus.agroal.runtime.DataSources.getDataSource(DataSources.java:142)
        at io.quarkus.agroal.runtime.health.DataSourceHealthCheck.init(DataSourceHealthCheck.java:49)

```

### How to Reproduce?

Easy to reproduce. Getting started sample with below config produces the error.

```
quarkus.datasource.db-kind=postgresql
quarkus.datasource.metrics.enabled=true
quarkus.datasource.jdbc=false
quarkus.datasource.reactive=true
## additional datasource for flyway migration
quarkus.datasource.migds.db-kind=postgresql
quarkus.datasource.migds.reactive=false
quarkus.datasource.migds.jdbc=true
quarkus.flyway.migds.clean-at-start=false
quarkus.flyway.migds.create-schemas=false
quarkus.flyway.migds.migrate-at-start=true
quarkus.flyway.migds.repair-at-start=true
```

Sample app: https://github.com/mvmandapati/code-with-quarkus

### Output of `uname -a` or `ver`

Linux

### Output of `java -version`

openjdk 21.0.2 2024-01-16

### Quarkus version or git rev

3.7.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.9.1

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by gsmet**
- Fixes #38934
- Fixes #37779

### CODE REVIEW

**Review by geoand — APPROVED** [review]

File: extensions/agroal/runtime/src/main/java/io/quarkus/agroal/runtime/health/DataSourceHealthCheck.java [hunk 1]
```diff
@@ -40,10 +41,12 @@ protected void init() {
         }
         DataSourceSupport support = Arc.container().instance(DataSourceSupport.class)
                 .get();
+        AgroalDataSourceSupport agroalSupport = Arc.container().instance(AgroalDataSourceSupport.class)
+                .get();
         Set<String> names = support.getConfiguredNames();
```
Comment (yrodiere) [inline extensions/agroal/runtime/src/main/java/io/quarkus/agroal/runtime/health/DataSourceHealthCheck.java:46]: I wonder if you shouldn't just rely exclusively on `agroalSupport.entries` and get rid of `support.getConfiguredNames()` altogether. `support.getConfiguredNames()` is sometimes returning non-agroal datasource names (which you're working around here), and I've noticed before (#37779) that it may not even return the name of all configured Agroal datasources:

https://github.com/quarkusio/quarkus/blob/5bbae6fc32ca65188b91d0f86db987fde727332f/extensions/datasource/runtime/src/main/java/io/quarkus/datasource/runtime/DataSourceRecorder.java#L21-L29

File: extensions/agroal/runtime/src/main/java/io/quarkus/agroal/runtime/health/DataSourceHealthCheck.java [hunk 2]
```diff
@@ -40,10 +41,12 @@ protected void init() {
         }
         DataSourceSupport support = Arc.container().instance(DataSourceSupport.class)
                 .get();
+        AgroalDataSourceSupport agroalSupport = Arc.container().instance(AgroalDataSourceSupport.class)
+                .get();
```
[the remark this answers is not in the document]
Comment (yrodiere) [reply extensions/agroal/runtime/src/main/java/io/quarkus/agroal/runtime/health/DataSourceHealthCheck.java:45]: You're right, with the current code this will be fine.

**Review by yrodiere — APPROVED** [review]
Thanks, LGTM.

I'll just point out that you might be able to go a step further and fix #37779 while you're at it; see comments below.

I get that's not your immediate concern though, so feel free to merge.

**Comment by yrodiere** [comment]
> `org.opentest4j.AssertionFailedError: Expected analysis_results.fields.reflection to be within range [163 +- 3%] but was 168 ==> expected: <true> but was: <false>`

Looks like this failure already happens on main: https://github.com/quarkusio/quarkus/actions/runs/8001599270/job/21853643446

Why though >_< It passed last time I touched the Hibernate ORM extension: https://github.com/quarkusio/quarkus/pull/38731

Looking at the history... this seems to fail randomly? https://ge.quarkus.io/scans/tests?search.timeZoneId=Europe%2FParis&tests.container=io.quarkus.it.jpa.postgresql.ImageMetricsITCase&tests.test=verifyImageMetrics&tests.unstableOnly=false#

(@gsmet Develocity is great, btw!)

@zakkak any idea?

**Comment by yrodiere** [comment]
> Looking at the history... this seems to fail randomly

Scratch that, it's just the `-withxml` test failing, but we used the same package name and class names in both modules, hence the alternating success/failure.

First failure was on da7f89a01988090dea1f50b34dc46f0b534f3dfc, previous success on 5044d93f0e139342042ec251e2e2ac4eabd0a804 .
The problem should be somewhere in here: https://github.com/quarkusio/quarkus/compare/5044d93f0e139342042ec251e2e2ac4eabd0a804...da7f89a01988090dea1f50b34dc46f0b534f3dfc ?

File: extensions/agroal/runtime/src/main/java/io/quarkus/agroal/runtime/health/DataSourceHealthCheck.java (hunk 1 above)
Comment (gsmet) [reply extensions/agroal/runtime/src/main/java/io/quarkus/agroal/runtime/health/DataSourceHealthCheck.java]: Yeah, you're right. I dropped it in a second commit so that we don't introduce any more confusion but I will only backport the first one.

**Review by yrodiere — APPROVED** [review]
