### PR TITLE
TransformerFactory not "used" with GraalVM for JDK 21 (23.1)

### LINKED ISSUE #35676: GraalVM 24.0/23.1: JPAFunctionalityInGraalITCase.verifyJDKXMLParsersAreIncluded fails
### Describe the bug

With a latest Graal master (24.0, possibly also 23.1 build) the `JPAFunctionalityInGraalITCase.verifyJDKXMLParsersAreIncluded` integration test in native fails, no longer finding `TransformerFactory` in the report. I haven't looked into the details yet.

```
Error:  io.quarkus.it.jpa.postgresql.JPAFunctionalityInGraalITCase.verifyJDKXMLParsersAreIncluded -- Time elapsed: 0.179 s <<< FAILURE!
org.opentest4j.AssertionFailedError: Type 'javax.xml.transform.TransformerFactory' was not found in the report in target/quarkus-integration-test-jpa-postgresql-withxml-999-SNAPSHOT-native-image-source-jar/reports/used_classes_quarkus-integration-test-jpa-postgresql-withxml-999-SNAPSHOT-runner_20230901_021852.txt
```

See:
https://github.com/graalvm/mandrel/actions/runs/6044323984/job/16403307103#step:12:713

### PR DESCRIPTION
**Pull request by zakkak**
javax.xml.transform.TransformerFactory does not appear as used in
GraalVM for JDK 21's reports due to inlining.

Closes #35676

### CODE REVIEW

**Review by jerboaa — COMMENTED** [review]
Please add a comment as to why we are looking for the new class.

**Comment by zakkak** [comment]
> Please add a comment as to why we are looking for the new class.

Done

File: integration-tests/jpa-postgresql-withxml/src/test/java/io/quarkus/it/jpa/postgresql/JPAFunctionalityInGraalITCase.java [hunk 1]
```diff
@@ -21,9 +21,10 @@ public void verifyJDKXMLParsersAreIncluded() {
         report.assertContains(org.postgresql.jdbc.PgSQLXML.class);
         report.assertContains(UUIDJdbcType.class);
 
-        //And finally verify we included the JDK XML by triggering
-        //io.quarkus.jdbc.postgresql.runtime.graal.SQLXLMFeature
-        report.assertContains(javax.xml.transform.TransformerFactory.class);
+        // And finally verify we included "com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl" which is
+        // the fallback implementation class name used in javax.xml.transform.TransformerFactory.newInstance()
+        // whose invocation gets triggered when io.quarkus.jdbc.postgresql.runtime.graal.SQLXLMFeature is enabled
```
Comment (jerboaa) [inline integration-tests/jpa-postgresql-withxml/src/test/java/io/quarkus/it/jpa/postgresql/JPAFunctionalityInGraalITCase.java:26]: Suggestion:

```
... triggered when io.quarkus.jdbc.postgresql.runtime.graal.SQLXLMFeature is enabled.
We cannot use class javax.xml.transform.TransformerFactory directly since delegation to
the implementation might get inlined, thus resulting in 'javax.xml.transform.TransformerFactory'
not showing up as a used class in the reports (due to '-H:+InlineBeforeAnalysis').
```

Comment (zakkak) [reply integration-tests/jpa-postgresql-withxml/src/test/java/io/quarkus/it/jpa/postgresql/JPAFunctionalityInGraalITCase.java:26]: :+1: Amended.

Comment (jerboaa) [reply integration-tests/jpa-postgresql-withxml/src/test/java/io/quarkus/it/jpa/postgresql/JPAFunctionalityInGraalITCase.java:26]: Nit: Add a period (`.`) after `SQLXMLFeature is enabled`. I.e. `... SQLXMLFeature is enabled.`

**Review by jerboaa — APPROVED** [review]
Seems fine to me. Question: Is the actual working of the XML stuff of the driver actually asserted in the test?

**Comment by zakkak** [comment]
> Seems fine to me. Question: Is the actual working of the XML stuff of the driver actually asserted in the test?

To my understanding yes, in https://github.com/quarkusio/quarkus/blob/main/integration-tests/jpa-postgresql-withxml/src/test/java/io/quarkus/it/jpa/postgresql/JPAFunctionalityTest.java

**Comment by jerboaa** [comment]
> > Seems fine to me. Question: Is the actual working of the XML stuff of the driver actually asserted in the test?
> 
> To my understanding yes, in https://github.com/quarkusio/quarkus/blob/main/integration-tests/jpa-postgresql-withxml/src/test/java/io/quarkus/it/jpa/postgresql/JPAFunctionalityTest.java

Great, thanks!

File: integration-tests/jpa-postgresql/src/test/java/io/quarkus/it/jpa/postgresql/JPAFunctionalityInGraalITCase.java [hunk 2]
```diff
@@ -21,9 +21,14 @@ public void verifyJdkXmlParsersHavebeenEcludedFromNative() {
...
 
-        //And finally verify we managed to exclude the JDK XML because of having hinted the analysis
-        //(See io.quarkus.jdbc.postgresql.runtime.graal.SQLXLMFeature )
+        // And finally verify we exclude "com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl" which is
+        // the fallback implementation class name used in javax.xml.transform.TransformerFactory.newInstance()
+        // whose invocation gets triggered when io.quarkus.jdbc.postgresql.runtime.graal.SQLXLMFeature is enabled.
+        // We cannot only use class javax.xml.transform.TransformerFactory directly since delegation to
+        // the implementation might get inlined, thus resulting in 'javax.xml.transform.TransformerFactory'
+        // not showing up as a used class in the reports (due to '-H:+InlineBeforeAnalysis').
         report.assertContainsNot(javax.xml.transform.TransformerFactory.class);
```
Comment (yrodiere) [inline integration-tests/jpa-postgresql/src/test/java/io/quarkus/it/jpa/postgresql/JPAFunctionalityInGraalITCase.java:30]: If `javax.xml.transform.TransformerFactory` never appears in the report anyway, maybe we should remove this? Otherwise it's a bit confusing...

**Review by yrodiere — APPROVED** [review]
LGTM, though I'd remove the now unnecessary (and confusing) `.assertContainsNot(javax.xml.transform.TransformerFactory.class)`.
Thanks!

File: integration-tests/jpa-postgresql/src/test/java/io/quarkus/it/jpa/postgresql/JPAFunctionalityInGraalITCase.java (hunk 2 above)
Comment (zakkak) [reply integration-tests/jpa-postgresql/src/test/java/io/quarkus/it/jpa/postgresql/JPAFunctionalityInGraalITCase.java:30]: The reason I kept it is because the only reason it doesn't appear in the report when rynning `withxml` is because it gets optimized away. It should definitely keep not appearing in this test, so I think it remains a valid assertion.

**Comment by yrodiere** [comment]
Merged, thanks!
