### PR TITLE
Use a dynamic sources encoding during a hot reload compilation

### LINKED ISSUE #3486: Hot reload: the sources encoding used during recompilation should be dynamic
**Describe the bug**
Since #3467 got fixed, we're using a hardcoded `UTF-8` encoding during a hot reload compilation.

**Expected behavior**
Ideally, the encoding should come dynamically from the `project.build.sourceEncoding` Maven property or a Gradle equivalent.

### PR DESCRIPTION
**Pull request by gwenneg**
Fixes #3486

### CODE REVIEW

File: core/devmode/src/main/java/io/quarkus/dev/CompilationProvider.java [hunk 1]
```diff
@@ -24,19 +26,22 @@
...
-                File outputDirectory) {
+                File outputDirectory,
+                String sourceEncoding) {
 
             this.name = name;
             this.classpath = classpath;
             this.projectDirectory = projectDirectory;
             this.sourceDirectory = sourceDirectory;
             this.outputDirectory = outputDirectory;
+            this.sourceEncoding = sourceEncoding == null ? StandardCharsets.UTF_8 : Charset.forName(sourceEncoding);
```
Comment (gwenneg) [inline core/devmode/src/main/java/io/quarkus/dev/CompilationProvider.java]: `sourceEncoding ` can't be typed sooner to `Charset` because `DevModeContext` is serialized in the Maven and Gradle plugins.

**Comment by gwenneg** [comment]
@aloubyansky: Since the Maven and Gradle plugins are involved in this PR, could you please review it?

**Review by aloubyansky — APPROVED** [review]
Looks good to me. Thanks!
