### PR TITLE
Fix for deactivating managed context in GraphQL server

### LINKED ISSUE #27036: GraphQL spurious authentication failures
### Describe the bug

After upgrading from **2.9.2.Final**, requests to the GraphQL API for secured resources (queries / mutations) may spuriously fail with an "unauthorized" error-code.

I have created a [simple Quarkus GraphQL project](https://github.com/nvrs/quarkus-graphql-auth-issue) that uses the the https://quarkus.io/guides/microprofile-graphql as a base to exhibit / reproduce the issue. Specifically, the quarkus GraphQL example has been modified by adding an extra method to the API (`allFilmsSecured`) that's secured using the standard `@Authenticated` annotation, and leveraged the `quarkus-elytron-security-properties-file` extension to configure a set of valid user credentials.

### Expected behavior

When querying the secured endpoint with the correct credentials (HTTP Basic Auth) concurrenctly with / without other unsecured endpoints, one should not receive `unauthorized` error-code responses.

### Actual behavior

Given enough concurrent requests (tests are configured to 50 but failures occur with fewer too), some will fail with `unauthorized` error-code. What's also suprising is that the unexpected behaviour is not exactly the same for all versions > 2.9.2.Final. Specifically, for versions up to **2.10.3.Final** the bug seems to occur only when there are concurrent requests with different security credentials and / or a combination of resources with different security restrictions. However on **2.10.4.Final** and **2.11.1.Final** failures are observed even when loading the service with concurrent requests for the same resource with the exact same credentials.

### How to Reproduce?

Executing the Junit tests in [ConcurrentAuthTest](https://github.com/nvrs/quarkus-graphql-auth-issue/blob/main/src/test/java/org/acme/microprofile/graphql/ConcurrentAuthTest.java) reproduces the issue on two machines that I have tried it out (8 cores / 16 threads - Ryzen 58000x, and 4 cores / 8 threads intel i7 kaby lake). On the test class there are two tests, one that attempts concurrent requests on both secured and unsecured resources (that fails on all versions > **2.9.2.Final**), and another that only performs concurrent requests on the secured resource that fails only on **2.10.4.Final** and **2.11.1.Final**.

A [JMeter Test Plan](https://github.com/nvrs/quarkus-graphql-auth-issue/blob/main/graphql-auth-test.jmx) is also included that reproduces the issue very reliably (JSON Assertions fail when receiving `unauthorized` error codes).

### Output of `uname -a` or `ver`

Linux fedora-desktop 5.18.13-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Jul 22 14:03:36 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.2" 2022-01-18 OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8) OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode, sharing)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by phillip-kruger**
Fix #27036

Signed-off-by: Phillip Kruger <phillip.kruger@gmail.com>

### CODE REVIEW

**Review by stuartwdouglas — APPROVED** [review]

File: extensions/smallrye-graphql/runtime/src/main/java/io/quarkus/smallrye/graphql/runtime/SmallRyeGraphQLAbstractHandler.java [hunk 1]
```diff
@@ -67,6 +68,7 @@ public void handle(final RoutingContext ctx) {
         }
         try {
             handleWithIdentity(ctx);
+            currentManagedContext.deactivate();
```
Comment (gsmet) [inline extensions/smallrye-graphql/runtime/src/main/java/io/quarkus/smallrye/graphql/runtime/SmallRyeGraphQLAbstractHandler.java:71]: Why isn't this one in a finally?  Why deactivate in one case and terminate in the case of an exception?

Also what's the purpose of this.currentManagedContextTerminationHandler now?

Comment (phillip-kruger) [reply extensions/smallrye-graphql/runtime/src/main/java/io/quarkus/smallrye/graphql/runtime/SmallRyeGraphQLAbstractHandler.java:71]: `this.currentManagedContextTerminationHandler ` will terminate (so deactivate and destroy) once we are done, while the deactivate after the `handleWithIdentity` will only deactivate (so that it does not leak)

Comment (phillip-kruger) [reply extensions/smallrye-graphql/runtime/src/main/java/io/quarkus/smallrye/graphql/runtime/SmallRyeGraphQLAbstractHandler.java:71]: It does not need to be in a finally as the catch with terminate

Comment (gsmet) [reply extensions/smallrye-graphql/runtime/src/main/java/io/quarkus/smallrye/graphql/runtime/SmallRyeGraphQLAbstractHandler.java:71]: I can understand that but my concern was more that we are not consistent. Typically here: https://github.com/quarkusio/quarkus/pull/27040/files#diff-5b5cda47e6a5418c9345a577d468f058e05c412dc9b64fce6a6ef5aec496023bR75-R85 where we simply deactivate. Or maybe the exception from the latter is caught below?

Also what do you mean by leaking? What I don't understand is how we can leak something between this and the end of the response? Or is it that the thread is somehow reused between the end of this and the end of the response?

Comment (phillip-kruger) [reply extensions/smallrye-graphql/runtime/src/main/java/io/quarkus/smallrye/graphql/runtime/SmallRyeGraphQLAbstractHandler.java:71]: The thread could be reused, in a high traffic scenario.

Comment (gsmet) [reply extensions/smallrye-graphql/runtime/src/main/java/io/quarkus/smallrye/graphql/runtime/SmallRyeGraphQLAbstractHandler.java:71]: But you're sure that all the response handlers we added earlier are always executed on the right thread at the right time?
That's what gets me a bit worried.

Note that I have no idea how this all works so I'm asking naive questions.

Comment (phillip-kruger) [reply extensions/smallrye-graphql/runtime/src/main/java/io/quarkus/smallrye/graphql/runtime/SmallRyeGraphQLAbstractHandler.java:71]: Yes sure. Maybe @stuartwdouglas can explain better. By leaking I mean that a new request that use the same thread can get the context that still float around (because it's not been deactivated)
