### PR TITLE
Reactive routes - use end handler to terminate the CDI request context

### LINKED ISSUE #9141: `JsonWebToken` always null inside Uni/ Multi callback
**Describe the bug**
I'm building API w/ `quarkus-vertx-web` & `quarkus-smallrye-jwt`. When I try call get claims values from`JsonWebToken` inside `Uni`/ `Multi` callback they're always `null` like this: 

```
@Route(path = "/tickets/:id", methods = HttpMethod.GET)
  void getTicket(RoutingContext ctx) {
    UUID id = RouteUtil.getUUIDParams(ctx, "id");
    log.info(">>>>>>>> " + jwt.getName()); // <== this return correct value
    ticketSvc.getOneById(id)
        .subscribe()
        .with(ThrowingConsumer.unchecked(ticket -> {
              if (ticket == null) {
                ctx.fail(HttpStatus.SC_NOT_FOUND);
              } else if (!Objects.equals(ticket.getUserId(), jwt.getName())) {
                ctx.fail(HttpStatus.SC_FORBIDDEN);
              } else {
                log.info("<<<<<<<<< " + jwt.getName());  // <== this return null
                ctx.response()
                    .setStatusCode(HttpStatus.SC_OK)
                    .putHeader(HttpHeaders.CONTENT_TYPE, "application/json")
                    .end(mapper.writeValueAsString(ticket));
              }
            }),
            ctx::fail);
  }
```

**Expected behavior**
Should return correct claims value

**Configuration**
```properties
# Add your application.properties here, if applicable.
mp.jwt.verify.publickey.location=https://${AUTH0_DOMAIN}/.well-known/jwks.json
mp.jwt.verify.issuer=https://${AUTH0_DOMAIN}/
smallrye.jwt.path.groups=permissions
smallrye.jwt.groups-separator=','
smallrye.jwt.always-check-authorization=true

```

### PR DESCRIPTION
**Pull request by mkouba**
- i.e. fix context propagation
- resolves #9141

### CODE REVIEW

**Comment by mkouba** [comment]
@KienDangTran could pls verify that this PR fixes your problem with JWT?

File: extensions/vertx-web/deployment/src/test/java/io/quarkus/vertx/web/reactive/RequestContextPropagationTest.java [hunk 1]
```diff
@@ -0,0 +1,75 @@
...
+    static class MyRoutes {
+
+        @Inject
+        Ping ping;
+
+        @Route(path = "ping")
+        void ping(RoutingContext ctx) {
+            // Init the Ping bean
+            ping.init("foo_");
+            Uni.createFrom().item(ctx.request().getParam("val")).subscribe().with(
```
Comment (FroMage) [inline extensions/vertx-web/deployment/src/test/java/io/quarkus/vertx/web/reactive/RequestContextPropagationTest.java:47]: Did you actually run this test without your fix? Did it fail?
I'm asking because this looks like a synchronous call: there's nothing that would make it switch thread or delay execution.
If it does already pass without your fix (as I think it should), try switching your code to:

```java
Uni.createFrom().item(ctx.request().getParam("val")).onItem().delayIt().by(Duration.ofMillis(200)).subscribe().with(...)
```

**Review by FroMage — CHANGES_REQUESTED** [review]

File: extensions/vertx-web/deployment/src/test/java/io/quarkus/vertx/web/reactive/RequestContextPropagationTest.java (hunk 1 above)
Comment (mkouba) [reply extensions/vertx-web/deployment/src/test/java/io/quarkus/vertx/web/reactive/RequestContextPropagationTest.java:47]: Yes, I did and it failed. Most probably because my machine is fast and the `ping()` method completes before the `Uni` callback. `.delayIt().by(Duration.ofMillis(200))` sounds reasonable though. Thanks...

Comment (FroMage) [reply extensions/vertx-web/deployment/src/test/java/io/quarkus/vertx/web/reactive/RequestContextPropagationTest.java:47]: The speed of your machine should not be able to explain it failing. Either `Uni.createFrom().item(ctx.request().getParam("val")).subscribe().with()` is synchronous, or it's not. If it's synchronous your callback will be called before the method returns and before you get into your interceptor, which therefore should not fail the test because we haven't destroyed the context yet.

@cescoffier where am I wrong here?

Comment (mkouba) [reply extensions/vertx-web/deployment/src/test/java/io/quarkus/vertx/web/reactive/RequestContextPropagationTest.java:47]: Hm, why do you think it's synchronous? I'm definitely no expert here but I'd expect it to be async... @cescoffier will tell us ;-).

Comment (FroMage) [reply extensions/vertx-web/deployment/src/test/java/io/quarkus/vertx/web/reactive/RequestContextPropagationTest.java:47]: Well, `item()` is synchronous, no?

Comment (mkouba) [reply extensions/vertx-web/deployment/src/test/java/io/quarkus/vertx/web/reactive/RequestContextPropagationTest.java:47]: Yes, but `Uni.subscribe()` is not... but I may be completely wrong ;-).

Comment (cescoffier) [reply extensions/vertx-web/deployment/src/test/java/io/quarkus/vertx/web/reactive/RequestContextPropagationTest.java:47]: The `item` method will emit the item immediately after subscription in a synchronous fashion (using the thread used for the subscription).

 You can simulate some delay with `delayIt` as pointed by @FroMage.

Comment (cescoffier) [reply extensions/vertx-web/deployment/src/test/java/io/quarkus/vertx/web/reactive/RequestContextPropagationTest.java:47]: Just to clarify:

```
Uni.createFrom().item("hello").subscribe().with(t -> Systme.out.println(t));
System.out.println("Done");
```

prints:

```
hello
Done
```

```
Uni.createFrom().item("hello")
    .onItem().delayIt().by(Duration.ofSecond(1))
    .subscribe().with(t -> Systme.out.println(t));
System.out.println("Done");
```

prints:

```
Done
hello # printed roughly 1 second later
```

Comment (mkouba) [reply extensions/vertx-web/deployment/src/test/java/io/quarkus/vertx/web/reactive/RequestContextPropagationTest.java:47]: Ok, I should double check my test then... Anyway, from my "reactive noob" POV it feels weird that `onItem().delayIt().by(Duration.ofSecond(1))` causes async execution. I read the javadoc of `subscribe()` as a non-blocking subscription...

Comment (FroMage) [reply extensions/vertx-web/deployment/src/test/java/io/quarkus/vertx/web/reactive/RequestContextPropagationTest.java:47]: Well, subscribe depends on whether the left-hand-side is already completed or not. In the case of a single item it is, so synchronous. In the case of delay, it's not, so it will be completed later, so async.
Now the much bigger questions is how could this test possibly fail before you put the fix, since it's all synchronous? That's what's worrying me.

Comment (mkouba) [reply extensions/vertx-web/deployment/src/test/java/io/quarkus/vertx/web/reactive/RequestContextPropagationTest.java:47]: >  That's what's worrying me.

Maybe it's just a PEBKAC on my side ;-). I will tell you in few mins...

Comment (cescoffier) [reply extensions/vertx-web/deployment/src/test/java/io/quarkus/vertx/web/reactive/RequestContextPropagationTest.java:47]: `subscribe` is non-blocking. It does not block the caller thread. It receives the item once it is emitted. 

So the interesting aspect is _when_ your item is emitted. In your code, the item is emitted during the subscription (immediately). That's what `Uni.createFrom().item()` is doing. Then, every processing stage is synchronous in your code - which means each stage is called immediately (well, you don't do any processing so it's obviously synchronous). That explains why the subscriber is called directly (on the subscriber thread).

Comment (mkouba) [reply extensions/vertx-web/deployment/src/test/java/io/quarkus/vertx/web/reactive/RequestContextPropagationTest.java]: Good news everyone. It was PEBKAC... I wasn't able to reproduce the failure without `onItem().delayIt()`. Thanks for clarification guys!

Comment (FroMage) [reply extensions/vertx-web/deployment/src/test/java/io/quarkus/vertx/web/reactive/RequestContextPropagationTest.java]: OK, pfew, at least we are more confident in the test and fix now :)

**Review by FroMage — APPROVED** [review]

**Comment by mkouba** [comment]
For the record - this PR may cause slight performance drop in benchmarks...

File: extensions/vertx-web/runtime/src/main/java/io/quarkus/vertx/web/runtime/RouteHandler.java [hunk 2]
```diff
@@ -33,13 +34,23 @@ default void handle(RoutingContext context) {
...
                 requestContext.activate();
                 if (user != null) {
                     RouteHandlers.fireSecurityIdentity(user.getSecurityIdentity());
                 }
+                // Reactive routes can use async processing (e.g. mutiny Uni/Multi) and context propagation
+                // 1. Store the state (which is basically a shared Map instance)
+                // 2. Terminate the context correcly when the response is disposed or an exception is thrown 
+                InjectableContext.ContextState state = requestContext.getState();
+                context.addEndHandler(v -> {
+                    requestContext.activate(state);
```
Comment (stuartwdouglas) [inline extensions/vertx-web/runtime/src/main/java/io/quarkus/vertx/web/runtime/RouteHandler.java:47]: Wouldn't it be more performant to have a terminate(state) method in arc, so you don't have to touch the thread locals?

Comment (stuartwdouglas) [reply extensions/vertx-web/runtime/src/main/java/io/quarkus/vertx/web/runtime/RouteHandler.java:47]: Also we try and avoid lambdas in runtime code.

File: extensions/vertx-web/deployment/src/test/java/io/quarkus/vertx/web/reactive/RequestContextPropagationTest.java [hunk 3]
```diff
@@ -0,0 +1,78 @@
...
+
+    @RegisterExtension
+    static final QuarkusUnitTest config = new QuarkusUnitTest()
+            .setArchiveProducer(() -> ShrinkWrap.create(JavaArchive.class)
+                    .addClasses(MyRoutes.class, Ping.class));
+
+    @Test
+    public void test() {
+        get("/ping?val=bar").then().statusCode(200).body(is("foo_bar"));
+        assertTrue(Ping.DESTROYED.get());
```
Comment (stuartwdouglas) [inline extensions/vertx-web/deployment/src/test/java/io/quarkus/vertx/web/reactive/RequestContextPropagationTest.java:35]: This is racey.

As far as the client is concerned the request is complete when the last bit of data is received from the wire. This happens in the vert.x end() call, and at that point the bean has not been destroyed, as the destruction happens after the data is sent. Usually the test will pass because destroying the bean happens straight after the data is sent, and sending the data is relatively slow, but occasionally it will fail. This is a very common cause of intermittent CI failures. 

If you change the AtomicBoolean to a CompletableFuture and wait a few seconds for the value this will fix it.

**Review by stuartwdouglas — CHANGES_REQUESTED** [review]

File: extensions/vertx-web/runtime/src/main/java/io/quarkus/vertx/web/runtime/RouteHandler.java (hunk 2 above)
Comment (mkouba) [reply extensions/vertx-web/runtime/src/main/java/io/quarkus/vertx/web/runtime/RouteHandler.java:47]: > so you don't have to touch the thread locals?

Hm, yes that would help. We don't need to activate the context here.

File: extensions/vertx-web/deployment/src/test/java/io/quarkus/vertx/web/reactive/RequestContextPropagationTest.java (hunk 3 above)
Comment (mkouba) [reply extensions/vertx-web/deployment/src/test/java/io/quarkus/vertx/web/reactive/RequestContextPropagationTest.java:35]: I see. Thanks for spotting this!

**Review by stuartwdouglas — APPROVED** [review]

**Comment by mkouba** [comment]
The failure in "Quarkus - Integration Tests - Maven tooling" seems to be unrelated:
```
2020-05-26T08:30:43.3745436Z [ERROR]   PackageIT.testRunnerJarHasValidCRC:166 
2020-05-26T08:30:43.3746285Z Expecting:
2020-05-26T08:30:43.3746554Z  <1>
2020-05-26T08:30:43.3746758Z to be equal to:
2020-05-26T08:30:43.3746940Z  <0>
2020-05-26T08:30:43.3747135Z but was not.
```
