### PR TITLE
Fix MessageBundle key/file name resolver algorithm

### LINKED ISSUE #39960: MessageBundle naming issue
### Describe the bug

In this kind of situation:

```
public class EmailBundles {
    @MessageBundle
    interface started {
        @Message
        String started(String id, String filename);
        @Message
        String documentAccessUrl(String url);
...
    @MessageBundle
    interface startedValidator {
        @Message
        String started(String id, String filename);
        @Message
        String turnEmailWillBeSent();
...
```

The following error appears:

```
io.quarkus.qute.deployment.MessageBundleException: Message bundle method turnEmailWillBeSent() not found on: com.iarchiva.EmailBundles$started
```

If I rename "interface started {" to "interface rstarted {" the initial part of the name does not match and there is no issue.

### Expected behavior

I expect no name collision between "started" and "startedValidator".

### Actual behavior

Names collide being different.

### How to Reproduce?

Having two interfaces that start with the same string.

### Output of `uname -a` or `ver`

Microsoft Windows [Versión 10.0.22631.3296]

### Output of `java -version`

openjdk version "21" 2023-09-19 OpenJDK Runtime Environment GraalVM CE 21+35.1 (build 21+35-jvmci-23.1-b15) OpenJDK 64-Bit Server VM GraalVM CE 21+35.1 (build 21+35-jvmci-23.1-b15, mixed mode, sharing)

### Quarkus version or git rev

3.9.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.6

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by gastaldi**
- Fixes #39960

### CODE REVIEW

**Comment by gastaldi** [comment]
@ercalamar can you give it a try building Quarkus with this PR and let me know if that fixes your issue?

**Comment by ercalamar** [comment]
Hi Thanks. I will over the weekend.

File: extensions/qute/deployment/src/main/java/io/quarkus/qute/deployment/MessageBundleProcessor.java [hunk 1]
```diff
@@ -315,6 +315,30 @@ List<MessageBundleBuildItem> processBundles(BeanArchiveIndexBuildItem beanArchiv
         return bundles;
     }
 
+    private static boolean bundleNameMatchesFileName(String fileName, String name) {
```
Comment (mkouba) [inline extensions/qute/deployment/src/main/java/io/quarkus/qute/deployment/MessageBundleProcessor.java:318]: It would be nice to have a plain junit test for this static method ;-). I.e. make the method package-private and add `MessageBundleProcessorTest`, something like we do in `io.quarkus.qute.deployment.QuteProcessorTest`.

**Review by mkouba — COMMENTED** [review]
One little comment. Otherwise looks good!

**Review by mkouba — APPROVED** [review]
