### PR TITLE
Only include the jars in the lib/ directory and classpath entries

### LINKED ISSUE #2852: Invalid classpath entry in MANIFEST.MF
Using that reproducer: https://github.com/vietk/QuarkusReproducer , we end up with the following entry `lib/maven.dependency.pom.xml` in the `Class-Path` entry of the `MANIFEST.MF` file of the runner.

Which is invalid and leads to the following error when trying to build the native image:
```
Error: Invalid or corrupt jarfile /.../Reproducer/application/target/application-1.0-SNAPSHOT-runner.jar
```

@stuartwdouglas WDYT would be better: Should we filter out the XML files or include just the jar files in the entry? I know some people use specific extensions for their artifacts so I'm not sure only including jar files is a good idea.

/cc @vietk

### PR DESCRIPTION
**Pull request by gsmet**
This is a very naive fix for #2852 .

I wonder if we should filter the files earlier but that might be a bit too soon (and we might want to keep the non-jars entry in the model?).

@aloubyansky WDYT?

Fixes #2852 .

### CODE REVIEW

**Comment by aloubyansky** [comment]
Well, the model is build from the dependencies and is used to set up classpaths. Having POM deps on the classpath is probably not useful.
BTW, you could have filtered it out by also checking the type of the dependency which would be "pom". A dependency in the model may also point to a classes directory (in tests, for example).

**Comment by FroMage** [comment]
@aloubyansky can you review please?

File: core/creator/src/main/java/io/quarkus/creator/phase/runnerjar/RunnerJarPhase.java [hunk 1]
```diff
@@ -309,6 +309,10 @@ public FileVisitResult visitFile(Path file, BasicFileAttributes attrs)
 
                 }
             } else {
+                // Exclude files that are not jars (typically, we can have XML files here, see https://github.com/quarkusio/quarkus/issues/2852)
+                if (!resolvedDep.getFileName().toString().endsWith(".jar")) {
```
Comment (FroMage) [inline core/creator/src/main/java/io/quarkus/creator/phase/runnerjar/RunnerJarPhase.java]: Shouldn't we also accept directories?

**Review by FroMage — CHANGES_REQUESTED** [review]

File: core/creator/src/main/java/io/quarkus/creator/phase/runnerjar/RunnerJarPhase.java (hunk 1 above)
Comment (aloubyansky) [reply core/creator/src/main/java/io/quarkus/creator/phase/runnerjar/RunnerJarPhase.java]: When we build the runner jar the lib dir includes only the JARs. So, it's probably ok.

Comment (aloubyansky) [reply core/creator/src/main/java/io/quarkus/creator/phase/runnerjar/RunnerJarPhase.java]: This kind of check should move though out of the `if`. If `uberJar` is true then `resolvedDep` will be passed to `ZipUtils.newFileSystem(resolvedDep)`, which will fail if it's not an archive.

Comment (FroMage) [reply core/creator/src/main/java/io/quarkus/creator/phase/runnerjar/RunnerJarPhase.java]: Ah, then ball in @gsmet 's camp.

**Comment by FroMage** [comment]
Windows build failed due to a Kafka timeout, I restarted it.

File: core/creator/src/main/java/io/quarkus/creator/phase/runnerjar/RunnerJarPhase.java (hunk 1 above)
Comment (gsmet) [reply core/creator/src/main/java/io/quarkus/creator/phase/runnerjar/RunnerJarPhase.java]: Ah right, I had an hesitation, will fix.

Comment (gsmet) [reply core/creator/src/main/java/io/quarkus/creator/phase/runnerjar/RunnerJarPhase.java]: @aloubyansky done!

**Review by aloubyansky — APPROVED** [review]

**Comment by gsmet** [comment]
@FroMage I think we answered your concerns?

**Review by FroMage — APPROVED** [review]

**Comment by FroMage** [comment]
Yes, thanks.
