### PR TITLE
Fix #9036: support filters on queries

### LINKED ISSUE #9036: PanacheEntityBase: support for Hibernate @Filter
**Description**
In panache you can use hibernate @Filter(). But to activate filters, you must:
- call the entity manager and unwrap to hibernate session
- enableFilter by name
- setParameter with name and value

**Implementation ideas**
We could add to 2 methods to enable a filter with parameter/parameters:

```
public static void enableFilter(String filterName, String parameterName, Object value) {
        JpaOperations.getEntityManager().unwrap(Session.class)
                .enableFilter(filterName)
                .setParameter(parameterName, value);
    }

    public static void enableFilter(String filterName, Map<String, Object> params) {
        JpaOperations.getEntityManager().unwrap(Session.class)
                .enableFilter(filterName);
        for (Map.Entry<String, Object> entry : params.entrySet()) {
            JpaOperations.getEntityManager().unwrap(Session.class)
                    .getEnabledFilter(filterName)
                    .setParameter(entry.getKey(), entry.getValue());
        }
    }
```
And a new method to find() using the filters (implemented at build time):
 ```
public static PanacheQuery<MobilePhone> findByFilters(String orderBy) {
        if (orderBy != null) {
            return MobilePhone.find("select a from MobilePhone a", Sort.by(orderBy));
        }
        return MobilePhone.find("select a from MobilePhone a");
    }
```

My complete use case:
2 entities and 1 rest class, to activate different filters by query parameters:

```
import io.quarkus.hibernate.orm.panache.PanacheEntity;
import io.quarkus.hibernate.orm.panache.PanacheQuery;
import io.quarkus.hibernate.orm.panache.runtime.JpaOperations;
import io.quarkus.panache.common.Sort;
import org.hibernate.Session;
import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.ParamDef;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

@Entity
@Table(name = "persons")
@FilterDef(name = "lastName", parameters = @ParamDef(name = "lastName", type = "string"))
@Filter(name = "lastName", condition = "lastName LIKE :lastName")

@FilterDef(name = "tax_code", parameters = @ParamDef(name = "tax_code", type = "string"))
@Filter(name = "tax_code", condition = "tax_code = :tax_code")

@FilterDef(name = "phones_by_brand", parameters = @ParamDef(name = "brand", type = "string"))
@FilterDef(name = "phones_by_phone_model", parameters = @ParamDef(name = "phone_model", type = "string"))
@FilterDef(name = "phones_by_mobile_operator", parameters = @ParamDef(name = "mobile_operator", type = "string"))

public class Person extends PanacheEntity {

    public String firstName;
    public String lastName;
    public String tax_code;

    @OneToMany(mappedBy = "owner", fetch = FetchType.EAGER, cascade = CascadeType.ALL)
    @Filter(name = "phones_by_brand", condition = "brand = :brand")
    @Filter(name = "phones_by_phone_model", condition = "phone_model = :phone_model")
    @Filter(name = "phones_by_mobile_operator", condition = "mobile_operator = :mobile_operator")
    public List<MobilePhone> mobilePhones = new ArrayList<>();

    public static void enableFilter(String filterName, String parameterName, Object value) {
        JpaOperations.getEntityManager().unwrap(Session.class)
                .enableFilter(filterName)
                .setParameter(parameterName, value);
    }

    public static void enableFilter(String filterName, Map<String, Object> params) {
        JpaOperations.getEntityManager().unwrap(Session.class)
                .enableFilter(filterName);
        for (Map.Entry<String, Object> entry : params.entrySet()) {
            JpaOperations.getEntityManager().unwrap(Session.class)
                    .getEnabledFilter(filterName)
                    .setParameter(entry.getKey(), entry.getValue());
        }

    }

    public static PanacheQuery<Person> findByFilters(String orderBy) {
        if (orderBy != null) {
            return Person.find("select a from Person a", Sort.by(orderBy));
        }
        return Person.find("select a from Person a");
    }

    public Person add(MobilePhone mobilePhone) {
        this.mobilePhones.add(mobilePhone);
        return this;
    }
}
```

```
import com.fasterxml.jackson.annotation.JsonBackReference;
import io.quarkus.hibernate.orm.panache.PanacheEntity;
import io.quarkus.hibernate.orm.panache.PanacheQuery;
import io.quarkus.hibernate.orm.panache.runtime.JpaOperations;
import io.quarkus.panache.common.Sort;
import org.hibernate.Session;
import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.ParamDef;

import javax.persistence.*;
import java.time.LocalDate;
import java.util.Map;

@Entity
@Table(name = "mobilephones")

@FilterDef(name = "mobile_operator", parameters = @ParamDef(name = "mobile_operator", type = "string"))
@Filter(name = "mobile_operator", condition = "mobile_operator = :mobile_operator")

@FilterDef(name = "brand", parameters = @ParamDef(name = "brand", type = "string"))
@Filter(name = "brand", condition = "brand = :brand")

@FilterDef(name = "phone_model", parameters = @ParamDef(name = "phone_model", type = "string"))
@Filter(name = "phone_model", condition = "phone_model = :phone_model")

@FilterDef(name = "person_id", parameters = @ParamDef(name = "person_id", type = "integer"))
@Filter(name = "person_id", condition = "person_id = :person_id")

@FilterDef(name = "owner_by_tax_code", parameters = @ParamDef(name = "tax_code", type = "string"))
@Filter(name = "owner_by_tax_code", condition = "person_id in (select p.id from persons p where p.tax_code = :tax_code)")

public class MobilePhone extends PanacheEntity {

    public LocalDate purchase_date;
    public String mobile_operator;
    public String brand;
    @OrderBy
    public String phone_model;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "person_id")
    @JsonBackReference
    public Person owner;

    public static void enableFilter(String filterName, String parameterName, Object value) {
        JpaOperations.getEntityManager().unwrap(Session.class)
                .enableFilter(filterName)
                .setParameter(parameterName, value);
    }

    public static void enableFilter(String filterName, Map<String, Object> params) {
        JpaOperations.getEntityManager().unwrap(Session.class)
                .enableFilter(filterName);
        for (Map.Entry<String, Object> entry : params.entrySet()) {
            JpaOperations.getEntityManager().unwrap(Session.class)
                    .getEnabledFilter(filterName)
                    .setParameter(entry.getKey(), entry.getValue());
        }

    }

    public static PanacheQuery<MobilePhone> findByFilters(String orderBy) {
        if (orderBy != null) {
            return MobilePhone.find("select a from MobilePhone a", Sort.by(orderBy));
        }
        return MobilePhone.find("select a from MobilePhone a");
    }

    public MobilePhone owner(Person owner) {
        this.owner = owner;
        return this;
    }

    public MobilePhone purchase_date(LocalDate purchase_date) {
        this.purchase_date = purchase_date;
        return this;
    }

    public MobilePhone mobile_operator(String mobile_operator) {
        this.mobile_operator = mobile_operator;
        return this;
    }

    public MobilePhone brand(String brand) {
        this.brand = brand;
        return this;
    }

    public MobilePhone phone_model(String phone_model) {
        this.phone_model = phone_model;
        return this;
    }

    @Override
    public String toString() {
        return "MobilePhone{" +
                "purchase_date=" + purchase_date +
                ", mobile_operator='" + mobile_operator + '\'' +
                ", brand='" + brand + '\'' +
                ", phone_model='" + phone_model + '\'' +
                ", owner=" + owner +
                '}';
    }
}
```

```
import io.quarkus.hibernate.orm.panache.PanacheQuery;
import io.quarkus.panache.common.Page;
import ovh.flw.quarkusfilters.model.secondarytable.Person;

import javax.transaction.Transactional;
import javax.ws.rs.*;
import javax.ws.rs.core.Context;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.UriInfo;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;


@Path("/api/persons")
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
public class PersonsRs {

    @Context
    UriInfo ui;

    private List<Gift> paginate(PanacheQuery<Gift> search, Integer startRow, Integer pageSize) {
        long listSize = search.count();
        if (listSize == 0) {
            return new ArrayList<>();
        } else {
            int currentPage = 0;
            if (pageSize != 0) {
                currentPage = startRow / pageSize;
            } else {
                pageSize = Long.valueOf(listSize).intValue();
            }
            return search.page(Page.of(currentPage, pageSize)).list();
        }
    }
   
    @GET
    @Transactional
    public Response getList(
            @DefaultValue("0") @QueryParam("startRow") Integer startRow,
            @DefaultValue("10") @QueryParam("pageSize") Integer pageSize,
            @QueryParam("orderBy") String orderBy) {

            if ((ui.getQueryParameters().containsKey("lastName")
                && ui.getQueryParameters().getFirst("lastName") != null)) {
                       Person.enableFilter("lastName", "lastName", "%" + get("lastName") + "%");
             }
            PanacheQuery<Person> search = Person.findByFilters(orderBy);
            List<Person> list = paginate(search, startRow, pageSize);
            return Response.ok(list).build();
        } catch (Exception e) {
            e.printStackTrace();
            return Response.serverError().build();
        }
}
```

### PR DESCRIPTION
**Pull request by FroMage**

### CODE REVIEW

File: extensions/panache/hibernate-orm-panache-common/runtime/src/main/java/io/quarkus/hibernate/orm/panache/common/runtime/CommonPanacheQueryImpl.java [hunk 1]
```diff
@@ -93,6 +109,12 @@ private CommonPanacheQueryImpl(CommonPanacheQueryImpl<?> previousQuery, String n
         return new CommonPanacheQueryImpl<>(this, select.toString() + query, "select count(*) " + query);
     }
 
+    public void filter(String filterName, Map<String, Object> parameters) {
```
Comment (loicmathieu) [inline extensions/panache/hibernate-orm-panache-common/runtime/src/main/java/io/quarkus/hibernate/orm/panache/common/runtime/CommonPanacheQueryImpl.java:112]: Maybe use `withFilter` as we already have `withHint` and `withLock` ?

File: extensions/panache/hibernate-orm-panache-common/runtime/src/main/java/io/quarkus/hibernate/orm/panache/common/runtime/CommonPanacheQueryImpl.java [hunk 2]
```diff
@@ -93,6 +109,12 @@ private CommonPanacheQueryImpl(CommonPanacheQueryImpl<?> previousQuery, String n
...
+        if (filters == null)
+            filters = new HashMap<>();
```
Comment (loicmathieu) [inline extensions/panache/hibernate-orm-panache-common/runtime/src/main/java/io/quarkus/hibernate/orm/panache/common/runtime/CommonPanacheQueryImpl.java:114]: We didn't lazily instantiate the hint Map.
If you think it worth it, can you refactor the hint Map to be lazily instantiated for coherence sake ?

File: extensions/panache/hibernate-orm-panache-kotlin/runtime/src/main/kotlin/io/quarkus/hibernate/orm/panache/kotlin/PanacheQuery.kt [hunk 3]
```diff
@@ -148,6 +152,53 @@ interface PanacheQuery<Entity: Any> {
...
+     * with [FilterDef] on your entity or package, and enabled with [Filter] on your entity.
+     * <p>
+     * WARNING: setting filters can only be done on the underlying Hibernate [Session] and so this
+     * will modify the session's filters for the duration of obtaining the results (not while building
+     * the query). Enabled filters will be removed from the session afterwards, but no effort is made to
+     * preserve filters enabled on the session outside of this API.
+     * 
+     * @param filterName The name of the filter to enable
+     * @param parameters The set of parameters for the filter, if the filter requires parameters
+     * @return this query
```
Comment (loicmathieu) [inline extensions/panache/hibernate-orm-panache-kotlin/runtime/src/main/kotlin/io/quarkus/hibernate/orm/panache/kotlin/PanacheQuery.kt:167]: We usually describe the return type as `this query, modified`

File: integration-tests/hibernate-orm-panache-kotlin/src/main/kotlin/io/quarkus/it/panache/kotlin/TestEndpoint.kt [hunk 4]
```diff
@@ -1018,4 +1018,45 @@ class TestEndpoint {
         Assertions.assertNull(f.getAnnotation(XmlAttribute::class.java))
         Assertions.assertNotNull(f.getAnnotation(XmlTransient::class.java))
     }
+
+
+    @GET
+    @Path("9036")
+    @Transactional
+    fun testBug9036(): String {
```
Comment (loicmathieu) [inline integration-tests/hibernate-orm-panache-kotlin/src/main/kotlin/io/quarkus/it/panache/kotlin/TestEndpoint.kt:1026]: This is not a bug but a feature ;)
Maybe `testIssue9036` or `testFilter` ?

**Review by loicmathieu — CHANGES_REQUESTED** [review]
Some small feedback but overall looks good ;)

File: extensions/panache/hibernate-orm-panache-common/runtime/src/main/java/io/quarkus/hibernate/orm/panache/common/runtime/CommonPanacheQueryImpl.java (hunk 1 above)
Comment (FroMage) [reply extensions/panache/hibernate-orm-panache-common/runtime/src/main/java/io/quarkus/hibernate/orm/panache/common/runtime/CommonPanacheQueryImpl.java:112]: We could argue about this. `hint` doesn't represent an action: we don't want the result to be a hint, and `lock` has an immediacy that isn't true, because the results are locked later.
OTOH, `filter` is an action that doesn't sound wrong even if applied immediately.

So I could argue for `filter` instead of `withFilter` but the reasoning is not obvious, and `withFilter` would be more regular. OTOH, we have `page` and `range` and not `atPage` and `atRange`.

So, not sure at all either way, TBH.

File: extensions/panache/hibernate-orm-panache-common/runtime/src/main/java/io/quarkus/hibernate/orm/panache/common/runtime/CommonPanacheQueryImpl.java (hunk 2 above)
Comment (FroMage) [reply extensions/panache/hibernate-orm-panache-common/runtime/src/main/java/io/quarkus/hibernate/orm/panache/common/runtime/CommonPanacheQueryImpl.java:114]: It's something I like to do for <10% use-cases just in case. You can do it for the other stuff if you want or wait until a later refactor. No rush.

Comment (FroMage) [reply extensions/panache/hibernate-orm-panache-common/runtime/src/main/java/io/quarkus/hibernate/orm/panache/common/runtime/CommonPanacheQueryImpl.java:114]: Oh, sure, I can add it here.

File: extensions/panache/hibernate-orm-panache-kotlin/runtime/src/main/kotlin/io/quarkus/hibernate/orm/panache/kotlin/PanacheQuery.kt (hunk 3 above)
Comment (FroMage) [reply extensions/panache/hibernate-orm-panache-kotlin/runtime/src/main/kotlin/io/quarkus/hibernate/orm/panache/kotlin/PanacheQuery.kt:167]: Ah, OK.

File: integration-tests/hibernate-orm-panache-kotlin/src/main/kotlin/io/quarkus/it/panache/kotlin/TestEndpoint.kt (hunk 4 above)
Comment (FroMage) [reply integration-tests/hibernate-orm-panache-kotlin/src/main/kotlin/io/quarkus/it/panache/kotlin/TestEndpoint.kt:1026]: Who cares, really? The issue number is what matters.

File: extensions/panache/hibernate-orm-panache-common/runtime/src/main/java/io/quarkus/hibernate/orm/panache/common/runtime/CommonPanacheQueryImpl.java (hunk 1 above)
Comment (loicmathieu) [reply extensions/panache/hibernate-orm-panache-common/runtime/src/main/java/io/quarkus/hibernate/orm/panache/common/runtime/CommonPanacheQueryImpl.java:112]: OK, no need to argue, name it as you prefere ;)
Naming is hard ...

File: integration-tests/hibernate-orm-panache-kotlin/src/main/kotlin/io/quarkus/it/panache/kotlin/TestEndpoint.kt (hunk 4 above)
Comment (loicmathieu) [reply integration-tests/hibernate-orm-panache-kotlin/src/main/kotlin/io/quarkus/it/panache/kotlin/TestEndpoint.kt:1026]: Me ? But OK it's nitpicking ;)
I don't care about issue number for what is not a bug.
Let's keep it if you want.

File: extensions/panache/hibernate-orm-panache-common/runtime/src/main/java/io/quarkus/hibernate/orm/panache/common/runtime/CommonPanacheQueryImpl.java (hunk 1 above)
Comment (FroMage) [reply extensions/panache/hibernate-orm-panache-common/runtime/src/main/java/io/quarkus/hibernate/orm/panache/common/runtime/CommonPanacheQueryImpl.java:113]: I'll leave it like this, but I don't feel strongly either way.

File: extensions/panache/hibernate-orm-panache-kotlin/runtime/src/main/kotlin/io/quarkus/hibernate/orm/panache/kotlin/PanacheQuery.kt (hunk 3 above)
Comment (FroMage) [reply extensions/panache/hibernate-orm-panache-kotlin/runtime/src/main/kotlin/io/quarkus/hibernate/orm/panache/kotlin/PanacheQuery.kt]: Done.

File: extensions/panache/hibernate-orm-panache-common/runtime/src/main/java/io/quarkus/hibernate/orm/panache/common/runtime/CommonPanacheQueryImpl.java (hunk 2 above)
Comment (FroMage) [reply extensions/panache/hibernate-orm-panache-common/runtime/src/main/java/io/quarkus/hibernate/orm/panache/common/runtime/CommonPanacheQueryImpl.java:115]: Done.

**Review by loicmathieu — APPROVED** [review]
LGTM

**Comment by FroMage** [comment]
@geoand can you help me review this please? @Sanne won't have time.

**Comment by geoand** [comment]
Sure, let me check

File: extensions/panache/hibernate-orm-panache-common/runtime/src/main/java/io/quarkus/hibernate/orm/panache/common/runtime/CommonPanacheQueryImpl.java [hunk 5]
```diff
@@ -26,6 +29,17 @@
     private static final Pattern SELECT_PATTERN = Pattern.compile("^\\s*SELECT\\s+((?:DISTINCT\\s+)?[^\\s]+)\\s+([^\\s]+.*)$",
             Pattern.CASE_INSENSITIVE);
 
+    private interface NonThrowingCloseable extends AutoCloseable {
+        @Override
+        void close();
```
Comment (geoand) [inline extensions/panache/hibernate-orm-panache-common/runtime/src/main/java/io/quarkus/hibernate/orm/panache/common/runtime/CommonPanacheQueryImpl.java:34]: Can we make this a `default`? Would some typing later on :)

File: integration-tests/hibernate-orm-panache-kotlin/src/test/kotlin/io/quarkus/it/panache/KotlinPanacheFunctionalityTest.kt [hunk 6]
```diff
@@ -71,4 +71,8 @@ open class KotlinPanacheFunctionalityTest {
                 personAsString)
     }
 
+    @Test
+    fun testBug9036() {
+        RestAssured.`when`()["/test/9036"].then().body(Matchers.`is`("OK"))
```
Comment (geoand) [inline integration-tests/hibernate-orm-panache-kotlin/src/test/kotlin/io/quarkus/it/panache/KotlinPanacheFunctionalityTest.kt:76]: Damn Kotlin and your `where` keyword...

File: integration-tests/hibernate-orm-panache/src/main/java/io/quarkus/it/panache/TestEndpoint.java [hunk 7]
```diff
@@ -1299,4 +1299,45 @@ public String testBug8254() {
...
+    @Transactional
+    public String testBug9036() {
+        Person.deleteAll();
+
+        Person emptyPerson = new Person();
+        emptyPerson.persist();
+
+        Person deadPerson = new Person();
+        deadPerson.name = "Stef";
+        deadPerson.status = Status.DECEASED;
```
Comment (geoand) [inline integration-tests/hibernate-orm-panache/src/main/java/io/quarkus/it/panache/TestEndpoint.java:1314]: You need to be careful man... :laughing:

**Review by geoand — APPROVED** [review]
I added a small comment, but it doesn't really affect anything

**Comment by geoand** [comment]
You merged the other PR so now you need to fix the conflicts :)

File: extensions/panache/hibernate-orm-panache-common/runtime/src/main/java/io/quarkus/hibernate/orm/panache/common/runtime/CommonPanacheQueryImpl.java (hunk 5 above)
Comment (FroMage) [reply extensions/panache/hibernate-orm-panache-common/runtime/src/main/java/io/quarkus/hibernate/orm/panache/common/runtime/CommonPanacheQueryImpl.java:40]: It's only used here, I don't see the point. It's in the JDK that this interface belongs :(

File: integration-tests/hibernate-orm-panache/src/main/java/io/quarkus/it/panache/TestEndpoint.java (hunk 7 above)
Comment (FroMage) [reply integration-tests/hibernate-orm-panache/src/main/java/io/quarkus/it/panache/TestEndpoint.java:1334]: It's a risky job…

**Comment by FroMage** [comment]
Yeah, just rebased, thanks.

File: extensions/panache/hibernate-orm-panache-common/runtime/src/main/java/io/quarkus/hibernate/orm/panache/common/runtime/CommonPanacheQueryImpl.java (hunk 5 above)
Comment (geoand) [reply extensions/panache/hibernate-orm-panache-common/runtime/src/main/java/io/quarkus/hibernate/orm/panache/common/runtime/CommonPanacheQueryImpl.java:40]: True

**Comment by FroMage** [comment]
Pfff…

```
2020-05-13T17:30:36.0126617Z [ERROR] Plugin net.alchim31.maven:scala-maven-plugin:4.1.1 or one of its dependencies could not be resolved: Failed to read artifact descriptor for net.alchim31.maven:scala-maven-plugin:jar:4.1.1: Could not transfer artifact net.alchim31.maven:scala-maven-plugin:pom:4.1.1 from/to central (https://repo.maven.apache.org/maven2): Transfer failed for https://repo.maven.apache.org/maven2/net/alchim31/maven/scala-maven-plugin/4.1.1/scala-maven-plugin-4.1.1.pom: Unknown host repo.maven.apache.org: Temporary failure in name resolution -> [Help 1]
```

Restarting CI.
