### PR TITLE
Maven test utils: Regexp accounts for terminal colours

### LINKED ISSUE #31689: Maven IT fails on Windows, terminal control symbols confuse regexps
### Describe the bug

Maven integration test fails for me on Windows 10:
```
[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   TestMojoIT>LaunchMojoTestBase.testThatTheTestsAreReRunMultiModule:56 Tests were run, but the log is not parseable with the patterns we know. This is the log:...
```
The problem (not visible in the log output text) is that there are terminal control characters present.

That is despite test generated projects having `quarkus.test.basic-console=true`.
When I sanitized those symbols before parsing, it works for me.

### Expected behavior

```
mvnw clean verify -f integration-tests/pom.xml -pl maven -Ddocker -Dquarkus.container-image.build=true -Dquarkus.native.container-runtime=podman -Dquarkus.docker.executable-name=podman -Davoid-containers=false
```
Passes.

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

Windows 10, terminal: cmder

### Output of `java -version`

17.0.6

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

main

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Karm**
Fixes #31689

While testing #31490 on Windows, it turned out that Maven Integration tests don't work for me on my Windows 10 workstation.

It ends up rather abruptly with:
```
[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   TestMojoIT>LaunchMojoTestBase.testThatTheTestsAreReRunMultiModule:56 Tests were run, but the log is not parseable with the patterns we know. This is the log:
 17:39:14.
Starting test run, 1 tests to run.
Running 1/1. Running: #JUnit Jupiter
Running 1/1. Running: com.acme.ResourceTest#ResourceTest
2023-03-07 17:39:16,205 WARN  [io.qua.con.build] (Test runner thread) The 'quarkus.test.basic-console' config property is deprecated and should not be used anymore
2023-03-07 17:39:16,723 INFO  [io.quarkus] (Test runner thread) quarkus-quickstart-multimodule-main 1.0-SNAPSHOT on JVM (powered by Quarkus 999-SNAPSHOT) started in 0.564s. Listening on: http://localhost:8081
2023-03-07 17:39:16,723 INFO  [io.quarkus] (Test runner thread) Profile test activated.
2023-03-07 17:39:16,724 INFO  [io.quarkus] (Test runner thread) Installed features: [cdi, resteasy, smallrye-context-propagation, vertx]
Running 1/1. Running: com.acme.ResourceTest#testHelloEndpoint()
2023-03-07 17:39:17,003 INFO  [io.quarkus] (Test runner thread) quarkus-quickstart-multimodule-main(test application) stopped in 0.005s
2023-03-07 17:39:17,011 ERROR [io.qua.test] (Test runner thread) ==================== TEST REPORT #2 ==================== [Error Occurred After Shutdown]
2023-03-07 17:39:17,012 ERROR [io.qua.test] (Test runner thread) Test ResourceTest#testHelloEndpoint() failed
 [Error Occurred After Shutdown]: java.lang.AssertionError: 1 expectation failed.
Response body doesn't match expectation.
Expected: is "hello"
  Actual: 1d630f72-8684-4f1c-a766-4b438eda4b3a

        at io.restassured.internal.ValidatableResponseOptionsImpl.body(ValidatableResponseOptionsImpl.java:238)
        at com.acme.ResourceTest.testHelloEndpoint(ResourceTest.java:21)

2023-03-07 17:39:17,016 ERROR [io.qua.test] (Test runner thread) >>>>>>>>>>>>>>>>>>>> Summary: <<<<<<<<<<<<<<<<<<<<
com.acme.ResourceTest#testHelloEndpoint(ResourceTest.java:21) ResourceTest#testHelloEndpoint() 1 expectation failed.
Response body doesn't match expectation.
Expected: is "hello"
  Actual: 1d630f72-8684-4f1c-a766-4b438eda4b3a [Error Occurred After Shutdown]
2023-03-07 17:39:17,018 ERROR [io.qua.test] (Test runner thread) >>>>>>>>>>>>>>>>>>>> 1 TEST FAILED <<<<<<<<<<<<<<<<<<<< [Error Occurred After Shutdown]
1 test failed (1 passing, 0 skipped), 1 test was run in 881ms. Tests completed at 17:39:17 due to changes to HelloResource$Blah.class and 1 other files.
```
As you can see, the `1 test failed (1 passing, 0 skipped),` bit should easily match the regexp in [TestModeContinuousTestingMavenTestUtils.java](https://github.com/quarkusio/quarkus/blob/main/test-framework/maven/src/main/java/io/quarkus/maven/it/continuoustesting/TestModeContinuousTestingMavenTestUtils.java#L24), i.e.:
```java
private static final Pattern SOME_PASSING = Pattern
        .compile("(\\d\\d*) tests? failed \\((\\d\\d*) passing, (\\d\\d*) skipped\\)", Pattern.MULTILINE);
```
Being bitten by something similar in the past, I added additional logging that also dumps the buffer to a file, getting:

```
[ERROR] Failures:
[ERROR]   TestMojoIT>LaunchMojoTestBase.testThatTheTestsAreReRunMultiModule:56 Tests were run, but the log is not parseable with the patterns we know,
i.e. neither "All (\d+) tests are passing \((\d+) skipped\)" nor "(\d+) tests? failed \((\d+) passing, (\d+) skipped\)".
 Note that possible terminal control characters might not be seen here.
Check the text file dump too: C:\tmp\quarkus_main\integration-tests\maven\target\quarkus-maven-test-debug-log13996201237018610376.txt. This is the log:
<removed for brevity>
```

i.e.

```
[39m[91m1 test failed[39m ([32m1 passing[39m, [94m0 skipped[39m), [91m1 test was run in 889ms. Tests completed at 14:55:51 due to changes to HelloResource$Blah.class and 1 other files.[39m
```

So, despite having the [quarkus.console.basic](https://quarkus.io/guides/all-config#quarkus-core_quarkus.console.basic) set, the output is formatted on Windows.

This patch updates deprecated `quarkus.test.basic-console` to `quarkus.console.basic`, but that on its own doesn't help.
The patch also makes the regexp more resilient, accounting for terminal control symbols.

The maven suite then passes for me on Windows:

```
[INFO] Results:
[INFO]
[WARNING] Tests run: 166, Failures: 0, Errors: 0, Skipped: 6
[INFO]
[INFO]
[INFO] --- maven-failsafe-plugin:3.0.0-M9:verify (default) @ quarkus-integration-test-maven ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  47:00 min
[INFO] Finished at: 2023-03-08T14:27:20+01:00
[INFO] ------------------------------------------------------------------------
```

Why hasn't it failed on GHA CI before?  I am not sure. I am running tests on an old, physical desktop PC in a generally popular developer terminal [cmder](https://cmder.net/). It could be the case that when executed headless, it might behave differently.

### CODE REVIEW

**Comment by famod** [comment]
FWIW, this reminds me a bit of https://github.com/quarkusio/quarkus/pull/13717/files#diff-c8d6cbd031069f059263db7a1a9f9f4c2f75528e519791926521e3dd35d72604R103

**Comment by holly-cummins** [comment]
> I can't say I'm really capable of reviewing this :)

I was thinking the same, so I was counting on you, @geoand!

**Comment by geoand** [comment]
😆 

In that case I would say let's just what @Karm has done :)

**Review by geoand — APPROVED** [review]

File: test-framework/maven/src/main/java/io/quarkus/maven/it/continuoustesting/TestModeContinuousTestingMavenTestUtils.java [hunk 1]
```diff
@@ -18,10 +22,16 @@ public class TestModeContinuousTestingMavenTestUtils extends ContinuousTestingMa
...
     // All 2 tests are passing (0 skipped), 2 tests were run in 1413ms. Tests completed at 21:22:33.
-    private static final Pattern ALL_PASSING = Pattern.compile("All (\\d\\d*) tests are passing \\((\\d\\d*) skipped\\)",
+    // Windows log, despite `quarkus.console.basic=true', might contain terminal control symbols, colour decorations.
+    // e.g. the matcher is then fighting: [39m[91m1 test failed[39m ([32m1 passing[39m, [94m0 skipped[39m)
+    private static final Pattern ALL_PASSING = Pattern.compile(
+            "(?:\\e\\[[\\d;]+m)*All (\\d+) tests are passing \\((\\d+) skipped\\)",
             Pattern.MULTILINE);
     private static final Pattern SOME_PASSING = Pattern
-            .compile("(\\d\\d*) tests? failed \\((\\d\\d*) passing, (\\d\\d*) skipped\\)", Pattern.MULTILINE);
+            .compile(
```
Comment (iocanel) [inline test-framework/maven/src/main/java/io/quarkus/maven/it/continuoustesting/TestModeContinuousTestingMavenTestUtils.java:31]: I would rather stripping of the ansi characters so that it can work with the original regexp which is something I can follow.

**Review by iocanel — COMMENTED** [review]
If possible, I'd rather keep the regex simpler. Can't we just strip the ansi characters before using the regex?

**Review by maxandersen — APPROVED** [review]
just cleanup and a bit broader regexp to catch colors. Does not hurt afaics.

Weird if cmder.app behaves differently though. Wuold have expected no colors rather then enforced colors?

**Comment by Karm** [comment]
@maxandersen 

> just cleanup and a bit broader regexp to catch colors. Does not hurt afaics.
> 
> Weird if cmder.app behaves differently though. Wuold have expected no colors rather then enforced colors?

There are no colours in both `PowerShell` and `CMD`, so that's why you don't see this problem in CI.

`Cmder`, being a good developer friendly terminal is explicitly enabled though: See: [QuarkusConsole.java](https://github.com/quarkusio/quarkus/blob/main/core/devmode-spi/src/main/java/io/quarkus/dev/console/QuarkusConsole.java#L30).

As to the question why there are colours at all when `quarkus.console.basic=true` is all over the place. I am not sure. Could be some Windows specific arguments passing thing? But then again, other arguments, such as test profile, should be failing too? 

At this moment, I find making the regexp more resilient a good enough option.

**Comment by geoand** [comment]
The Gradle tests are very unstable lately

**Comment by Karm** [comment]
I think it could be merged.

**Comment by iocanel** [comment]
> With all due respect, I don't want to do that. Something like `.replaceAll(regexp string, "")` would have to be called on every single chunk of log, many times for those tests there. It instantiates the whole regexp engine again, compiles the regexp, reads the whole chunk, again and again. Instead of one regexp, pre-compiled in advance, we would have two places with regexps, wasting cycles :-(

Touche! :smi

**Comment by Karm** [comment]
@gsmet Is there anything holding this PR back from being merged now?
