### PR TITLE
Container runtime detection cached in sys prop, container-docker extension 

### LINKED ISSUE #31893: Docker or Podman required for tests since 3.0.0.Alpha6
### Describe the bug

Since 3.0.0.Alpha6 it's not possible to run tests that do not require testcontainers without having docker or podman installed. Instead you get:

```
SomeTest > initializationError FAILED
	    java.lang.NoClassDefFoundError at BasicLoggingEnabler.java:109
	        Caused by: java.lang.ExceptionInInitializerError at ContainerRuntimeUtil.java:86
 ```

### Expected behavior

You should only need podman/docker if testcontainer needs to be startet

### Actual behavior

You need podman/docker even if you only have unit tests without any interaction with services

### How to Reproduce?

1. Have a computer without docker or podman installed (or simply not in Path)
2. Init a simple quarkus app with 3.0.0.Alpha6 without and extensions
3. Try to run the tests

### Output of `uname -a` or `ver`

5.19.0-35-generic

### Output of `java -version`

openjdk version "17.0.6" 2023-01-17 LTS
OpenJDK Runtime Environment Corretto-17.0.6.10.1 (build 17.0.6+10-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.6.10.1 (build 17.0.6+10-LTS, mixed mode, sharing)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

3.0.0.Alpha6

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

------------------------------------------------------------
Gradle 8.0.2
------------------------------------------------------------

Build time:   2023-03-03 16:41:37 UTC
Revision:     7d6581558e226a580d91d399f7dfb9e3095c2b1d

Kotlin:       1.8.10
Groovy:       3.0.13
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.18 (Ubuntu 11.0.18+10-post-Ubuntu-0ubuntu122.04)
OS:           Linux 5.19.0-35-generic amd64

### Additional information

Noticed it on the build server first, then tried uninstalling docker + podman locally and that let me reproduce it.

### PR DESCRIPTION
**Pull request by Karm**
~~Do not merge yet, ongoing testing on Windows Docker and Podman...~~

Followup on #31490

* As per our discussion on #31490, the container runtime detected is cached in a sys prop, not in a file now.
* Removed superfluous calls to `podman` when `docker` is hinted by `quarkus.native.container-runtime` and vice versa.
* Fixed a scenario when there is neither `podman` nor `docker` and it's O.K. as it's not needed.
* Switched `extensions/container-image/container-image-docker` to use Core's container runtime autodetection too, with the current property `quarkus.docker.executable-name` being an optional way to override the detection system.

The experience with  `extensions/container-image/container-image-docker` is much improved on Podman only systems, because one doesn't have to explicitly specify `quarkus.docker.executable-name=podman` to make it work.

### CODE REVIEW

**Comment by Karm** [comment]
@geoand / @gsmet  Could you help me with the CI pls? 🤔😔

**Comment by geoand** [comment]
I would rebase the PR onto main and force push. The problem was likely a GH Actions issue

**Comment by gsmet** [comment]
@Karm I'm working on some additional cleanup on top of your patch. I would appreciate if you could review the changes once I push them.
(I'll add comments to explain the rationale of the changes)

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/AppCDSBuildStep.java [hunk 1]
```diff
@@ -39,7 +39,6 @@ public class AppCDSBuildStep {
     public static final String CLASSES_LIST_FILE_NAME = "classes.lst";
     private static final String CONTAINER_IMAGE_BASE_BUILD_DIR = "/tmp/quarkus";
     private static final String CONTAINER_IMAGE_APPCDS_DIR = CONTAINER_IMAGE_BASE_BUILD_DIR + "/appcds";
-    public static final ContainerRuntimeUtil.ContainerRuntime CONTAINER_RUNTIME = detectContainerRuntime(false);
```
Comment (gsmet) [inline core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/AppCDSBuildStep.java:42]: Let's avoid doing the autodetection in static fields.

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/AppCDSBuildStep.java [hunk 2]
```diff
@@ -204,12 +203,10 @@ private Path createClassesList(JarBuildItem jarResult,
     // generate the classes file on the host
     private List<String> dockerRunCommands(OutputTargetBuildItem outputTarget, String containerImage,
             String containerWorkingDir) {
-        if (CONTAINER_RUNTIME == ContainerRuntimeUtil.ContainerRuntime.UNAVAILABLE) {
-            throw new IllegalStateException("No container runtime was found. "
-                    + "Make sure you have either Docker or Podman installed in your environment.");
-        }
+        ContainerRuntime containerRuntime = detectContainerRuntime(true);
```
Comment (gsmet) [inline core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/AppCDSBuildStep.java:206]: The exception will be thrown automatically if required is true.

File: core/deployment/src/test/java/io/quarkus/deployment/pkg/steps/NativeImageBuildContainerRunnerTest.java [hunk 3]
```diff
@@ -1,6 +1,5 @@
 package io.quarkus.deployment.pkg.steps;
 
-import static io.quarkus.deployment.pkg.steps.AppCDSBuildStep.CONTAINER_RUNTIME;
```
Comment (gsmet) [inline core/deployment/src/test/java/io/quarkus/deployment/pkg/steps/NativeImageBuildContainerRunnerTest.java:3]: Let's not involved something that has nothing to do with this test.

File: core/runtime/src/main/java/io/quarkus/runtime/util/ContainerRuntimeUtil.java [hunk 4]
```diff
@@ -77,46 +77,48 @@ public static ContainerRuntime detectContainerRuntime(boolean required) {
...
         if (runtime == null) {
             return null;
-        } else if (ContainerRuntime.DOCKER.name().equalsIgnoreCase(runtime)) {
-            return ContainerRuntime.DOCKER;
-        } else if (ContainerRuntime.PODMAN.name().equalsIgnoreCase(runtime)) {
-            return ContainerRuntime.PODMAN;
-        } else if (ContainerRuntime.UNAVAILABLE.name().equalsIgnoreCase(runtime)) {
-            return ContainerRuntime.UNAVAILABLE;
-        } else {
+        }
```
Comment (gsmet) [inline core/runtime/src/main/java/io/quarkus/runtime/util/ContainerRuntimeUtil.java]: Moved that logic to the enum and simplified things a bit. Would appreciate a second pair of eyes to make sure I didn't break something.

File: extensions/container-image/container-image-docker/deployment/src/main/java/io/quarkus/container/image/docker/deployment/DockerProcessor.java [hunk 5]
```diff
@@ -336,14 +337,15 @@ private void pushImage(String image, DockerConfig dockerConfig) {
...
+            throw dockerException(executableName, pushArgs);
         }
         log.info("Successfully pushed docker image " + image);
     }
 
-    private RuntimeException dockerException(String[] dockerArgs) {
+    private RuntimeException dockerException(String executableName, String[] dockerArgs) {
         return new RuntimeException(
-                "Execution of 'docker " + String.join(" ", dockerArgs) + "' failed. See docker output for more details");
+                "Execution of '" + executableName + " " + String.join(" ", dockerArgs)
```
Comment (gsmet) [inline extensions/container-image/container-image-docker/deployment/src/main/java/io/quarkus/container/image/docker/deployment/DockerProcessor.java:347]: Given we are not always using `docker`, let's make the message accurate.

**Review by gsmet — COMMENTED** [review]
@Karm I added some comments to explain the logic of my changes.

Let me know if you're happy with them.

**Comment by Karm** [comment]
Thx @gsmet, I am walking through the scenarios atm...

**Comment by Karm** [comment]
@gsmet I think it's fine, both Linux and Windows, podman, docker, nothing, plain tests, dev mode, native build in container, docker extension...

CI failure here: Not sure. Do you find it related?

BTW, I am running JDK 17 and apparently the formatter picked up these:

```
diff --git a/integration-tests/java-17/src/main/java/io/quarkus/it/hibernate/panache/person/PersonResource.java b/integration-tests/java-17/src/main/java/io/quarkus/it/hibernate/panache/person/PersonResource.java
index 0bf2c3756b..7935235a7c 100644
--- a/integration-tests/java-17/src/main/java/io/quarkus/it/hibernate/panache/person/PersonResource.java
+++ b/integration-tests/java-17/src/main/java/io/quarkus/it/hibernate/panache/person/PersonResource.java
@@ -25,7 +25,6 @@ public Response addPerson(Person person) {
         return Response.created(URI.create("/persons/entity/" + id)).build();
     }
 
-
     @GET
     @Path("hql-project")
     @Transactional
diff --git a/integration-tests/java-17/src/test/java/io/quarkus/it/hibernate/panache/person/PersonResourceTest.java b/integration-tests/java-17/src/test/java/io/quarkus/it/hibernate/panache/person/PersonResourceTest.java
index bbc5a7df07..601241f450 100644
--- a/integration-tests/java-17/src/test/java/io/quarkus/it/hibernate/panache/person/PersonResourceTest.java
+++ b/integration-tests/java-17/src/test/java/io/quarkus/it/hibernate/panache/person/PersonResourceTest.java
@@ -4,11 +4,11 @@
 import static io.restassured.RestAssured.when;
 import static org.hamcrest.CoreMatchers.is;
 
-import io.quarkus.test.TestTransaction;
 import org.junit.jupiter.api.Test;
 
 import io.quarkus.it.mongodb.panache.person.Person;
 import io.quarkus.it.mongodb.panache.person.Status;
+import io.quarkus.test.TestTransaction;
 import io.quarkus.test.common.QuarkusTestResource;
 import io.quarkus.test.h2.H2DatabaseTestResource;
 import io.quarkus.test.junit.QuarkusTest;
```

**Review by gsmet — APPROVED** [review]
Let's merge!
