### PR TITLE
Mark the uber-jar as a multi-release jar if META-INF/versions/ exists in the generated jar

### LINKED ISSUE #19991: Uber-JARs don't support multi-release libraries
### Describe the bug

`quarkus-arc` depends, through `quarkus-core` and `smallrye-config`, on `smallrye-common-classloader`. This is a multi-release JAR file. For Java 8 it uses `sun.misc.Unsafe` to generate implementations of interfaces annotated with `@ConfigMapping`, for Java 9 and up it uses method handles. This library has a manifest entry `Multi-Release: true`, which is needed to make the multi-release mechanism work.

When an uber-JAR is created, the resulting manifest does not have the `Multi-Release: true` entry. As a result, on Java 11, an error is thrown because the method from `sun.misc.Unsafe` that is used in the Java 8 implementation has been removed.

For other forms this all works because the JAR files are kept intact, and the manifest entry is therefore not dropped.

### Expected behavior

When an uber-JAR is created and an interface annotated with `ConfigMapping` is used, this should just work.

If any manifest includes the `Multi-Release: true` entry, this should be included in the resulting manifest.

### Actual behavior

When an uber-JAR is created and an interface annotated with `ConfigMapping` is used, an error is thrown as soon as the interface is used.

The resulting manifest never includes the `Multi-Release: true` entry.

### How to Reproduce?

1. Create a new project.
2. Add a config interface and annotate it with `@ConfigMapping`.
3. Create a bean where this config interface is injected. Annotate it with `@Singleton` and `@Startup` so the problem will be encountered as soon as the application starts.
4. Set the packaging to uber-jar.
5. Start the application and observe the error.cmd

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19042.1165]

### Output of `java -version`

openjdk version "11.0.12" 2021-07-20 OpenJDK Runtime Environment Temurin-11.0.12+7 (build 11.0.12+7) OpenJDK 64-Bit Server VM Temurin-11.0.12+7 (build 11.0.12+7, mixed mode)

### GraalVM version (if different from Java)

N/A

### Quarkus version or git rev

2.2.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.2 (ea98e05a04480131370aa0c110b8c54cf726c06f)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jaikiran**
Fixes https://github.com/quarkusio/quarkus/issues/19991

The commit here introduces a change to mark a uber-jar as `Multi-Release: true` if the generated uber jar has a `META-INF/versions/` directory. The commit also contains a test which reproduces the issue and verifies this change.

### CODE REVIEW

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/JarResultBuildStep.java [hunk 1]
```diff
@@ -401,6 +401,23 @@ private void buildUberJar0(CurateOutcomeBuildItem curateOutcomeBuildItem,
...
+            // should be OK.
+            if (Files.isDirectory(runnerZipFs.getPath("META-INF", "versions"))) {
+                log.debug("uber jar will be marked as multi-release jar");
+                final Path manifestPath = runnerZipFs.getPath("META-INF", "MANIFEST.MF");
+                final Manifest manifest = new Manifest();
+                // read the existing one
+                try (final InputStream is = Files.newInputStream(manifestPath)) {
+                    manifest.read(is);
+                }
+                manifest.getMainAttributes().put(Attributes.Name.MULTI_RELEASE, "true");
```
Comment (gastaldi) [inline core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/JarResultBuildStep.java:416]: Better test if `manifestPath` exists first?

File: integration-tests/maven/src/test/java/io/quarkus/maven/it/PackageIT.java [hunk 2]
```diff
@@ -124,7 +125,13 @@ private void verifyUberJar() throws IOException {
         List<File> jars = getFilesEndingWith(targetDir, ".jar");
         assertThat(jars).hasSize(1);
         assertThat(getNumberOfFilesEndingWith(targetDir, ".original")).isEqualTo(1);
-
+        try (JarFile jarFile = new JarFile(jars.get(0))) {
```
Comment (gastaldi) [inline integration-tests/maven/src/test/java/io/quarkus/maven/it/PackageIT.java:128]: I think you need to use the other `JarFile` constructor to have support multi-release JARs read properly. Better yet, use the `io.smallrye.common.io.jar.JarFiles` class 😉

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/JarResultBuildStep.java (hunk 1 above)
Comment (stuartwdouglas) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/JarResultBuildStep.java:416]: We know it exists because it is generated, however there is a comment at the generation saying it needs to be the first entry in the jar. 

Is there any problems with just marking all of them as multi release jars in the generateManifest code?

Comment (jaikiran) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/JarResultBuildStep.java:416]: > Is there any problems with just marking all of them as multi release jars in the generateManifest code?

That's an interesting point. I will experiment a bit to see if it has potential to cause issues.

File: integration-tests/maven/src/test/java/io/quarkus/maven/it/PackageIT.java (hunk 2 above)
Comment (jaikiran) [reply integration-tests/maven/src/test/java/io/quarkus/maven/it/PackageIT.java:128]: Hello @gastaldi, in this specific testcase I was just interested in seeing if the `Multi-Release: true` attribtue made it into the jar file and for that test, using any variant of `JarFile` constructor and then calling the `isMultiRelease()` works fine.

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/JarResultBuildStep.java (hunk 1 above)
Comment (rob-spoor) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/JarResultBuildStep.java:416]: That may have a negative impact on performance. There is a reason that Oracle has made multi-release JAR authors include the flag in manifests instead of just checking for the presence of `META-INF/versions`. The manifest is probably already available, whereas checking for folders inside JAR files may require scanning the entire contents.

For this PR that check should be sufficient, because otherwise you'd have to go through the manifest files of all bundled dependencies, as well as that of the application itself. The chances of using `META-INF/versions` without wanting a multi-release JAR is very, very small.

**Comment by rob-spoor** [comment]
Is there any update on this PR? I would really like to see it part of the October release.

**Comment by jaikiran** [comment]
> Is there any update on this PR? I would really like to see it part of the October release.

Sorry @rob-spoor, I got involved in a few other things at work and haven't been able to get back to this. I hope to work on this tonight or this weekend and see if anything needs to be changed in this current PR.

File: core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/JarResultBuildStep.java (hunk 1 above)
Comment (jaikiran) [reply core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/JarResultBuildStep.java:416]: @stuartwdouglas, I had a look at the JDK code (especially the `JarFile`). Marking all (uber) jars as `Multi-Release`, as far as I can see won't have a functional impact. However, it does have a performance penalty. The code in `java.util.jar.JarFile` upon finding that a jar is multi-release will go into a code path which has additional `synchronized` blocks. When it sees that there are no versioned entries, it then fallbacks to the code that represents a non mutil-release jar. This additional synchronization penalty will be applicable every time there's a `JarEntry` being fetched (which can be high).

So I think the current approach in the PR to mark it as multi-release only when we find the `META-INF/versions`, IMO, would be a better approach. Does that sound fine?

**Review by stuartwdouglas — APPROVED** [review]

**Comment by jaikiran** [comment]
Thank you Stuart and George for the reviews.
