### PR TITLE
Fix HTTP2 NPE issue

### LINKED ISSUE #25658: NPE in 2.9.1 Http2 response processing
### Describe the bug

After upgrading from 2.8.3 to 2.9.1 we started seeing these errors in our logs.

### Expected behavior

No errors

### Actual behavior

```posh
java.lang.NullPointerException: Cannot invoke "io.vertx.core.Handler.handle(Object)" because "handler" is null
at io.vertx.core.http.impl.Http2ServerResponse.write(Http2ServerResponse.java:474)
at io.vertx.core.http.impl.Http2ServerResponse.end(Http2ServerResponse.java:433)
at io.vertx.core.http.impl.Http2ServerResponse.end(Http2ServerResponse.java:413)
at io.quarkus.vertx.http.runtime.filters.AbstractResponseWrapper.end(AbstractResponseWrapper.java:481)
at org.jboss.resteasy.reactive.server.vertx.VertxResteasyReactiveRequestContext.end(VertxResteasyReactiveRequestContext.java:331)
at org.jboss.resteasy.reactive.server.handlers.ResponseWriterHandler.handle(ResponseWriterHandler.java:38)
at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:114)
at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:141)
at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:550)
at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:833)
```

### How to Reproduce?

It is intermittent and cannot reproduce outside of our production environment

### Output of `uname -a` or `ver`

AWS Fargate

### Output of `java -version`

OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.9.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #25658

### CODE REVIEW

File: independent-projects/resteasy-reactive/server/vertx/src/main/java/org/jboss/resteasy/reactive/server/vertx/VertxResteasyReactiveRequestContext.java [hunk 1]
```diff
@@ -328,7 +329,13 @@ public ServerHttpResponse setStatusCode(int code) {
     @Override
     public ServerHttpResponse end() {
         if (!response.ended()) {
-            response.end((Handler<AsyncResult<Void>>) null);
+            if (response instanceof Http1xServerResponse) {
+                // Http1xServerResponse correctly handles a null handler
+                response.end((Handler<AsyncResult<Void>>) null);
+            } else {
+                // we don't if other instances handle a null handler so just use the future form
```
Comment (gsmet) [inline independent-projects/resteasy-reactive/server/vertx/src/main/java/org/jboss/resteasy/reactive/server/vertx/VertxResteasyReactiveRequestContext.java:336]:
```suggestion
                // we don't know if other instances handle a null handler so just use the future form
```

**Review by cescoffier — APPROVED** [review]
Note for myself: this won't be needed once I integrate Vert.x 4.3.1
