### PR TITLE
Fix JAXB unmarshalling error when compiling to native

### LINKED ISSUE #36479: JAXB unmarshalling fails in native mode
### Describe the bug

When a class annotated with JAXB annotations is unmarshalled, the unmarshalling fails with

```bash
...
Caused by: java.lang.RuntimeException: org.glassfish.jaxb.runtime.v2.runtime.IllegalAnnotationsException: 1 counts of IllegalAnnotationExceptions
Property expression appears in @XmlType.propOrder, but no such property exists. Maybe you meant executorService?
	this problem is related to the following location:
		at org.apache.camel.model.ThrottleDefinition

	at io.quarkus.jaxb.runtime.JaxbContextProducer.createJAXBContext(JaxbContextProducer.java:82)
	at io.quarkus.jaxb.runtime.JaxbContextProducer.jaxbContext(JaxbContextProducer.java:31)
	at io.quarkus.jaxb.runtime.JaxbContextProducer_ProducerMethod_jaxbContext_6a6d20272304edd64c7bdfa35e3ed5d5971a3949_Bean.doCreate(Unknown Source)
	at io.quarkus.jaxb.runtime.JaxbContextProducer_ProducerMethod_jaxbContext_6a6d20272304edd64c7bdfa35e3ed5d5971a3949_Bean.create(Unknown Source)
	at io.quarkus.jaxb.runtime.JaxbContextProducer_ProducerMethod_jaxbContext_6a6d20272304edd64c7bdfa35e3ed5d5971a3949_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:113)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:37)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:34)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:34)
	at io.quarkus.jaxb.runtime.JaxbContextProducer_ProducerMethod_jaxbContext_6a6d20272304edd64c7bdfa35e3ed5d5971a3949_Bean.get(Unknown Source)
	at io.quarkus.jaxb.runtime.JaxbContextProducer_ProducerMethod_jaxbContext_6a6d20272304edd64c7bdfa35e3ed5d5971a3949_Bean.get(Unknown Source)
	at io.quarkus.arc.impl.Instances$3.get(Instances.java:132)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.LazyInstanceHandle.instanceInternal(LazyInstanceHandle.java:32)
	at io.quarkus.arc.impl.AbstractInstanceHandle.get(AbstractInstanceHandle.java:46)
	at de.turing85.converter.FooConverter.getContext(FooConverter.java:51)
	at de.turing85.converter.FooConverter.unmarshalFromString(FooConverter.java:39)
	at de.turing85.converter.FooConverter.unmarshal(FooConverter.java:34)
	at java.base@21/java.lang.reflect.Method.invoke(Method.java:580)
	at org.apache.camel.support.ObjectHelper.invokeMethod(ObjectHelper.java:355)
	... 28 more
...
```

### Expected behavior

The object gets unmarshalled

### Actual behavior

The above exception is thrown.

### How to Reproduce?

Reproducer:
- Clone https://github.com/turing85/quarkus-camel-jaxb
  ```bash
  git clone https://github.com/turing85/quarkus-camel-jaxb.git
  cd quarkus-camel-jaxb
  ```
- Build the application, run the tests
  ```bash
  ./mvnw clean verify
  ```
- Observe that the tests succeed
- Build the application natively, run the tests
  ```bash
  ./mvnw --define native clean verify
  ```
- Observe that the tests fail with above exception

### Output of `uname -a` or `ver`

Linux ecco 5.15.0-52-generic #58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.8" 2023-07-18 
OpenJDK Runtime Environment Temurin-17.0.8+7 (build 17.0.8+7) 
OpenJDK 64-Bit Server VM Temurin-17.0.8+7 (build 17.0.8+7, mixed mode, sharing)

### GraalVM version (if different from Java)

mandrel-23.0.1.2-java17

### Quarkus version or git rev

3.2.6.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.3 (21122926829f1ead511c958d89bd2f672198ae9f) 
Maven home: /home/marco/.m2/wrapper/dists/apache-maven-3.9.3-bin/326f10f4/apache-maven-3.9.3 
Java version: 17.0.8, vendor: Eclipse Adoptium, runtime: /opt/java/mandrel/23.0.1.2-java17 
Default locale: en_US, platform encoding: UTF-8 
OS name: "linux", version: "5.15.0-52-generic", arch: "amd64", family: "unix"

### Additional information

- Notice that neither `Foo.java` nor `Bar.java` define `propOrder`. Defining them does not change the behaviour.
- Notice that registering the classes `Foo` and `Bar` for reflectoin and serialization does not change the behaviour.

### PR DESCRIPTION
**Pull request by rysurd**
Fix #36479

The root cause was that not all classes annotated with Jaxb annotations were marked for reflection when using native compilation, in case there we have fields that are declared in parent classes. The fix made was to replace the ReflectiveClassBuildItem from JaxbProcessor with ReflectiveHierarchyBuildItem in order to mark inherited fields for native compilation.

There is a warning throw stating that some classes are not indexed via Jandex. If anyone know how to fix this don't hesitate to tell me ! I have added the jandex maven plugins as documented in the Quarkus doc but it changes nothing. For instance : 
```logs
[WARNING] [io.quarkus.deployment.steps.ReflectiveHierarchyStep] Unable to properly register the hierarchy of the following classes for reflection as they are not in the Jandex index:
        - com.sun.istack.FinalArrayList (source: JaxbProcessor > jakarta.xml.bind.annotation.XmlAccessorType)
        - com.sun.org.apache.xerces.internal.impl.dv.xs.SchemaDVFactoryImpl (source: JaxbProcessor > com.sun.org.apache.xerces.internal.impl.dv.xs.SchemaDVFactoryImpl)
        - com.sun.org.apache.xpath.internal.functions.FuncNot (source: JaxbProcessor > com.sun.org.apache.xpath.internal.functions.FuncNot)
        - com.sun.xml.internal.stream.XMLInputFactoryImpl (source: JaxbProcessor > com.sun.xml.internal.stream.XMLInputFactoryImpl)
        - com.sun.xml.internal.stream.XMLOutputFactoryImpl (source: JaxbProcessor > com.sun.xml.internal.stream.XMLOutputFactoryImpl)
        - jakarta.activation.MimeType (source: JaxbProcessor > jakarta.xml.bind.annotation.XmlAccessorType)
        - javax.xml.namespace.QName (source: JaxbProcessor > jakarta.xml.bind.annotation.XmlAccessorType)
        - org.glassfish.jaxb.core.v2.model.annotation.AnnotationReader (source: JaxbProcessor > jakarta.xml.bind.annotation.XmlAccessorType)
        - org.glassfish.jaxb.core.v2.model.annotation.Locatable (source: JaxbProcessor > jakarta.xml.bind.annotation.XmlAccessorType)
        - org.glassfish.jaxb.core.v2.model.core.Adapter (source: JaxbProcessor > jakarta.xml.bind.annotation.XmlAccessorType)
        - org.glassfish.jaxb.core.v2.model.core.BuiltinLeafInfo (source: JaxbProcessor > jakarta.xml.bind.annotation.XmlAccessorType)
        - org.glassfish.jaxb.core.v2.model.core.ClassInfo (source: JaxbProcessor > jakarta.xml.bind.annotation.XmlAccessorType)
        - org.glassfish.jaxb.core.v2.model.core.Element (source: JaxbProcessor > jakarta.xml.bind.annotation.XmlAccessorType)
        - org.glassfish.jaxb.core.v2.model.core.ElementInfo (source: JaxbProcessor > jakarta.xml.bind.annotation.XmlAccessorType)
        - org.glassfish.jaxb.core.v2.model.core.ElementPropertyInfo (source: JaxbProcessor > jakarta.xml.bind.annotation.XmlAccessorType)
        - org.glassfish.jaxb.core.v2.model.core.EnumLeafInfo (source: JaxbProcessor > jakarta.xml.bind.annotation.XmlAccessorType)
        - org.glassfish.jaxb.core.v2.model.core.ErrorHandler (source: JaxbProcessor > jakarta.xml.bind.annotation.XmlAccessorType)
        - org.glassfish.jaxb.core.v2.model.core.ID (source: JaxbProcessor > jakarta.xml.bind.annotation.XmlAccessorType)
        - org.glassfish.jaxb.core.v2.model.core.NonElement (source: JaxbProcessor > jakarta.xml.bind.annotation.XmlAccessorType)
        - org.glassfish.jaxb.core.v2.model.core.PropertyInfo (source: JaxbProcessor > jakarta.xml.bind.annotation.XmlAccessorType)
        - org.glassfish.jaxb.core.v2.model.core.PropertyKind (source: JaxbProcessor > jakarta.xml.bind.annotation.XmlAccessorType)
        - org.glassfish.jaxb.core.v2.model.core.TypeInfo (source: JaxbProcessor > jakarta.xml.bind.annotation.XmlAccessorType)
        - org.glassfish.jaxb.core.v2.model.core.TypeInfoSet (source: JaxbProcessor > jakarta.xml.bind.annotation.XmlAccessorType)
        - org.glassfish.jaxb.core.v2.model.core.WildcardMode (source: JaxbProcessor > jakarta.xml.bind.annotation.XmlAccessorType)
        - org.glassfish.jaxb.core.v2.model.nav.Navigator (source: JaxbProcessor > jakarta.xml.bind.annotation.XmlAccessorType)
        - org.glassfish.jaxb.core.v2.runtime.IllegalAnnotationException (source: JaxbProcessor > jakarta.xml.bind.annotation.XmlAccessorType)
        - org.glassfish.jaxb.core.v2.runtime.Location (source: JaxbProcessor > jakarta.xml.bind.annotation.XmlAccessorType)
        - org.glassfish.jaxb.core.v2.runtime.RuntimeUtil$ToStringAdapter (source: JaxbProcessor > org.glassfish.jaxb.core.v2.runtime.RuntimeUtil$ToStringAdapter)
        - org.xml.sax.Locator (source: JaxbProcessor > jakarta.xml.bind.annotation.XmlAccessorType)
Consider adding them to the index either by creating a Jandex index for your dependency via the Maven plugin, an empty META-INF/beans.xml or quarkus.index-dependency properties.
```

### CODE REVIEW

**Comment by rysurd** [comment]
@gsmet @zakkak Hello ! I have opened the PR for the jaxb unmarshalling error. I included an integration test which reproduce the same issue and check if it works or not.

File: extensions/jaxb/deployment/src/main/java/io/quarkus/jaxb/deployment/JaxbProcessor.java [hunk 1]
```diff
@@ -220,15 +225,24 @@ void processAnnotationsAndIndexFiles(
...
-            reflectiveClass.produce(
-                    ReflectiveClassBuildItem.builder(xmlJavaTypeAdapterInstance.value().asClass().name().toString())
-                            .methods().fields().build());
+            String className = xmlJavaTypeAdapterInstance.value().asClass().name().toString();
+            Type jandexType = Type.create(DotName.createSimple(className), Type.Kind.CLASS);
+            reflectiveClass.produce(new ReflectiveHierarchyBuildItem.Builder()
+                    .type(jandexType)
+                    .index(index)
+                    .source(getClass().getSimpleName() + " > " + jandexType.name().toString())
+                    .build());
```
Comment (gsmet) [inline extensions/jaxb/deployment/src/main/java/io/quarkus/jaxb/deployment/JaxbProcessor.java:245]: My guess is that this change should be reverted and that's probably what causes the warnings.

File: extensions/jaxb/deployment/src/main/java/io/quarkus/jaxb/deployment/JaxbProcessor.java [hunk 2]
```diff
@@ -274,7 +288,7 @@ void ignoreWarnings(BuildProducer<ReflectiveHierarchyIgnoreWarningBuildItem> ign
     void registerClasses(
             BuildProducer<NativeImageSystemPropertyBuildItem> nativeImageProps,
             BuildProducer<ServiceProviderBuildItem> providerItem,
-            BuildProducer<ReflectiveClassBuildItem> reflectiveClass,
+            BuildProducer<ReflectiveHierarchyBuildItem> reflectiveClass,
```
Comment (gsmet) [inline extensions/jaxb/deployment/src/main/java/io/quarkus/jaxb/deployment/JaxbProcessor.java:291]: My guess is that this change should be reverted and that's probably what causes the warnings.

File: extensions/jaxb/deployment/src/main/java/io/quarkus/jaxb/deployment/JaxbProcessor.java [hunk 3]
```diff
@@ -412,9 +430,14 @@ public static Stream<Path> safeWalk(Path p) {
         }
     }
 
-    private void addReflectiveClass(BuildProducer<ReflectiveClassBuildItem> reflectiveClass, boolean methods, boolean fields,
-            String... className) {
-        reflectiveClass.produce(new ReflectiveClassBuildItem(methods, fields, className));
+    private void addReflectiveClass(BuildProducer<ReflectiveHierarchyBuildItem> reflectiveClass, boolean methods,
```
Comment (gsmet) [inline extensions/jaxb/deployment/src/main/java/io/quarkus/jaxb/deployment/JaxbProcessor.java:433]: The call sites of this method would have to checked. I'm really not sure it makes sense to replace it in all cases (and might not even be necessary depending on when it's called).

File: extensions/jaxb/runtime/pom.xml [hunk 4]
```diff
@@ -70,6 +70,19 @@
...
+                <artifactId>jandex-maven-plugin</artifactId>
+                <executions>
+                    <execution>
+                        <id>make-index</id>
+                        <goals>
+                            <goal>jandex</goal>
+                        </goals>
+                    </execution>
+                </executions>
+            </plugin>
```
Comment (gsmet) [inline extensions/jaxb/runtime/pom.xml:85]: Why is this needed? The entity classes should be in the app, not in the extension, shouldn't they?

**Review by gsmet — CHANGES_REQUESTED** [review]
Thanks for having a look at this. I think we need to be more careful about when we use the hierachy feature: it should only be used on domain classes that will be serialized with JAXB, not on everything that was declared for reflection.
That's why you end up with all these warnings.

You can have a closer look if you want or I can have a look if you prefer, let me know.

In any case, it's nice to have a test case as we will be able to test that everything is fine if we make adjustments.

**Comment by rysurd** [comment]
> Thanks for having a look at this. I think we need to be more careful about when we use the hierachy feature: it should only be used on domain classes that will be serialized with JAXB, not on everything that was declared for reflection. That's why you end up with all these warnings.
> 
> You can have a closer look if you want or I can have a look if you prefer, let me know.
> 
> In any case, it's nice to have a test case as we will be able to test that everything is fine if we make adjustments.

Thanks for your review! I did some changes according to your inputs but I still got the warning, even if now there are only jaxb classes involved. If you don't mind I would not say no to a little help to troubleshoot this ... :D Thanks a lot again!

**Comment by gsmet** [comment]
I will have a look later this week. Thanks for pursuing this.

**Comment by rysurd** [comment]
@gsmet I think I resolved the issue with the Jandex warning ... Build seems ok now (No specific warnings or errors) so maybe if you have some time could you check on this please ? 😄 The integration test seems to do its job too as it failed when using the main branch codebase and succeed when I use the fix.

**Review by gsmet — APPROVED** [review]
@rysurd sorry for the delay, your latest changes look good.

I made some very small changes to make it more consistent with code we already had in the tree but these were really micro changes.

Let's see what CI has to say and merge!

**Comment by gsmet** [comment]
Merged, thanks for your contribution!

**Comment by rysurd** [comment]
> Merged, thanks for your contribution!

Thanks !

**Comment by rysurd** [comment]
Ah, sorry I should have catched that the extent of these changes would reach also into other libs ...

**Comment by ppalaga** [comment]
Here is my proposal: https://github.com/quarkusio/quarkus/pull/38221

**Comment by ppalaga** [comment]
@rysurd @turing85 could you perhaps check that https://github.com/quarkusio/quarkus/pull/38221 fixes your original issue?

**Comment by turing85** [comment]
@ppalaga Seems to work :+1:
