### PR TITLE
Move OpenTelemetry integration to use Instrumenter

### LINKED ISSUE #19745: OpenTelemetry missing useful span name & tags for OAuth2/OIDC HTTP operations
### Describe the bug

The quarkus VertxTracingAdapter sets useful span names and attributes for outgoing HTTP requests, but does this only if the request is an instance of `io.vertx.core.http.HttpServerRequest`.

When using OIDC requests to an external oauth2 server are manifested as instances of `io.vertx.core.http.impl.HttpRequestHead`, which is not an instance of HttpServerRequest. 

This means the spans recorded from OIDC communications tend to pretty barbones (e.g. they have a name "post" and no additional http info attribution). 

### Expected behavior

The same span name mapping and tags based on e.g. HTTP headers that apply to HttpServerRequest instances should apply to `io.vertx.core.spi.observability.HttpRequest` instances.

### Actual behavior

Spans recorded from OIDC communications have a name derived from the http method only, and no additional http info attribution)

### How to Reproduce?

Enabling opentelemetry on any OAuth2-secured resource endpoint, and capturing the spans produced for OAuth2 server directed HTTP requests in e.g. jaeger/zipkin should reproduce the problem. Alternatively a simple unit test based on an instance of `io.vertx.core.spi.observability.HttpRequest`.

### Output of `uname -a` or `ver`

MINGW64_NT-10.0-18363 LAP1453 3.0.7-338.x86_64 2019-04-30 21:52 UTC x86_64 Msys

### Output of `java -version`

openjdk version "11.0.12" 2021-07-20

### GraalVM version (if different from Java)

OpenJDK Runtime Environment GraalVM CE 21.1.0 (build 11.0.11+8-jvmci-21.1-b05)

### Quarkus version or git rev

2.1.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by radcortez**
- [x] Replace old manual code with the OTel Instrumenter API: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/contributing/using-instrumenter-api.md
- [x] Use JAX-RS Filters to cover invocation calls from `WebTarget` (and MP REST Client) 
- [x] Remove old integration code
- [x] Verify that all tests are ok with the new integration
- [x] Micrometer Vert.x Metrics

### CODE REVIEW

File: extensions/opentelemetry/opentelemetry/deployment/src/main/java/io/quarkus/opentelemetry/deployment/OpenTelemetryProcessor.java [hunk 1]
```diff
@@ -29,6 +30,7 @@
 import io.quarkus.opentelemetry.runtime.OpenTelemetryRecorder;
 import io.quarkus.opentelemetry.runtime.QuarkusContextStorage;
 import io.quarkus.opentelemetry.runtime.tracing.cdi.WithSpanInterceptor;
+import io.quarkus.opentelemetry.runtime.tracing.restclient.OpenTelemetryClientFilter;
```
Comment (ebullient) [inline extensions/opentelemetry/opentelemetry/deployment/src/main/java/io/quarkus/opentelemetry/deployment/OpenTelemetryProcessor.java:33]: watch this import -- depending on what it imports, you may run into trouble with a project w/o this enabled.

Supporting optional deps is why most of the telemetry/metrics support works with strings, not with imported class.getName()

Comment (radcortez) [reply extensions/opentelemetry/opentelemetry/deployment/src/main/java/io/quarkus/opentelemetry/deployment/OpenTelemetryProcessor.java:33]: This is only used here:

https://github.com/radcortez/quarkus/blob/2b148a3d35cdc9aa52c84d57440a097a36ffd422/extensions/opentelemetry/opentelemetry/deployment/src/main/java/io/quarkus/opentelemetry/deployment/OpenTelemetryProcessor.java#L113-L118

To add it as an additional class to index if the REST Client is Available, by testing this:

https://github.com/radcortez/quarkus/blob/2b148a3d35cdc9aa52c84d57440a097a36ffd422/extensions/opentelemetry/opentelemetry/deployment/src/main/java/io/quarkus/opentelemetry/deployment/OpenTelemetryProcessor.java#L48-L58

The `OpenTelemetryClientFilter` is then added via CDI and `@Provider`:

https://github.com/radcortez/quarkus/blob/2b148a3d35cdc9aa52c84d57440a097a36ffd422/extensions/opentelemetry/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/restclient/OpenTelemetryClientFilter.java#L35-L36

I think it is fairly safe, but let me add some tests for it.

File: extensions/opentelemetry/opentelemetry/runtime/pom.xml [hunk 2]
```diff
@@ -27,6 +27,10 @@
             <groupId>io.quarkus</groupId>
             <artifactId>quarkus-vertx</artifactId>
         </dependency>
+        <dependency>
```
Comment (kenfinnigan) [inline extensions/opentelemetry/opentelemetry/runtime/pom.xml:30]: This will add a HTTP server to all applications using OpenTelemetry, correct?

Is that desired for Reactive Messaging applications?

File: extensions/opentelemetry/opentelemetry/deployment/src/main/java/io/quarkus/opentelemetry/deployment/OpenTelemetryBuildItem.java [hunk 3]
```diff
@@ -0,0 +1,17 @@
+package io.quarkus.opentelemetry.deployment;
+
+import io.opentelemetry.api.OpenTelemetry;
+import io.quarkus.builder.item.SimpleBuildItem;
+import io.quarkus.runtime.RuntimeValue;
+
+public final class OpenTelemetryBuildItem extends SimpleBuildItem {
```
Comment (kenfinnigan) [inline extensions/opentelemetry/opentelemetry/deployment/src/main/java/io/quarkus/opentelemetry/deployment/OpenTelemetryBuildItem.java:7]: This is used on a producer side, but not being consumed.

Is it needed?

File: integration-tests/opentelemetry/src/test/java/io/quarkus/it/opentelemetry/OpenTelemetryTestCase.java [hunk 4]
```diff
@@ -189,7 +189,7 @@ void testEmptyClientPath() {
                 Assertions.assertEquals("/", spanData.get("attr_http.target"));
                 Assertions.assertEquals(pathParamUrl.getAuthority(), spanData.get("attr_http.host"));
                 Assertions.assertEquals("http", spanData.get("attr_http.scheme"));
-                Assertions.assertNull(spanData.get("attr_http.route"));
```
Comment (kenfinnigan) [inline integration-tests/opentelemetry/src/test/java/io/quarkus/it/opentelemetry/OpenTelemetryTestCase.java:192]: I'm not sure the `route` should be `/` given it represents a path template.

If there is no path, it should probably be null/empty

File: integration-tests/opentelemetry/src/test/java/io/quarkus/it/opentelemetry/OpenTelemetryTestCase.java [hunk 5]
```diff
@@ -303,7 +303,7 @@ void testSlashClientPath() {
...
+                Assertions.assertEquals("/", spanData.get("attr_http.target"));
```
Comment (kenfinnigan) [inline integration-tests/opentelemetry/src/test/java/io/quarkus/it/opentelemetry/OpenTelemetryTestCase.java:306]: This changed from testing `route` to `target`, which is already tested on line 303

**Review by kenfinnigan — COMMENTED** [review]
Was a little difficult to fully grasp given the breadth of changes.

Have you verified the attributes and trace/span shape are identical to existing code and post this change for all situations? I'm unsure of the REST Client situation, as that has large changes. Does the correct trace get created for classic and Reactive with sync and async return types?

Do the traces for Reactive Messaging look good still?

File: extensions/opentelemetry/opentelemetry/runtime/pom.xml (hunk 2 above)
Comment (radcortez) [reply extensions/opentelemetry/opentelemetry/runtime/pom.xml:30]: This was to obtain the Vert.x Routing Context, but I may be able to rewrite this without a direct dependency.

File: extensions/opentelemetry/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/restclient/OpenTelemetryClientFilter.java [hunk 6]
```diff
@@ -0,0 +1,213 @@
...
+                .newClientInstrumenter(new ClientRequestContextTextMapSetter());
+    }
+
+    @Override
+    public void filter(final ClientRequestContext request) {
+        Context parentContext = Context.current();
+        if (instrumenter.shouldStart(parentContext, request)) {
+            Context spanContext = instrumenter.start(parentContext, request);
+            Scope scope = spanContext.makeCurrent();
+            request.setProperty("otel.span.client.context", spanContext);
```
[the remark this answers is not in the document]
Comment (radcortez) [reply extensions/opentelemetry/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/restclient/OpenTelemetryClientFilter.java:66]: These are just local keys to use the JAX-RS Context to pass the `Scope` and the `Context` between the filter request and filter response. We can certainly extract them to static strings. They are not intended to be used outside the Client Filter.

File: extensions/opentelemetry/opentelemetry/deployment/src/main/java/io/quarkus/opentelemetry/deployment/OpenTelemetryBuildItem.java (hunk 3 above)
Comment (radcortez) [reply extensions/opentelemetry/opentelemetry/deployment/src/main/java/io/quarkus/opentelemetry/deployment/OpenTelemetryBuildItem.java:7]: Ah, I guess I added it to use it as a parameter to the Vert.x Tracer, but then I ended up using `GlobalOpenTelemetry.get()`. I'll remove it.

File: integration-tests/opentelemetry/src/test/java/io/quarkus/it/opentelemetry/OpenTelemetryTestCase.java (hunk 4 above)
Comment (radcortez) [reply integration-tests/opentelemetry/src/test/java/io/quarkus/it/opentelemetry/OpenTelemetryTestCase.java:192]: Yes, the spec is not very clear about this. Let me try to clarify this with the OTel group. In the meanwhile, I'll revert this.

File: integration-tests/opentelemetry/src/test/java/io/quarkus/it/opentelemetry/OpenTelemetryTestCase.java (hunk 5 above)
Comment (radcortez) [reply integration-tests/opentelemetry/src/test/java/io/quarkus/it/opentelemetry/OpenTelemetryTestCase.java:306]: Correct. Wrong copy paste.

**Comment by radcortez** [comment]
> Was a little difficult to fully grasp given the breadth of changes.

Yes, sorry but thanks for reviewing :)

> Have you verified the attributes and trace/span shape are identical to existing code and post this change for all situations? I'm unsure of the REST Client situation, as that has large changes. Does the correct trace get created for classic and Reactive with sync and async return types?
> 
> Do the traces for Reactive Messaging look good still?

Yes, I've added a few more tests in `RestClientOpenTelemetryTest`. Also, the tests in the reactive rest-client pass without any change in `io.quarkus.it.rest.client.BasicTest`. We can probably add a few more.

The filter now also supports the JAX-RS Web Client (it was only MP REST Client before).

**Comment by radcortez** [comment]
I've removed the Vert.x Http dependency to obtain the route and used the Vert.x Metrics instead. This is still not correct, because we cannot conflict with the Micrometer Metrics, but it was the only other way to retrieve the route. 

In the meanwhile, I'll discuss with @ebullient on how we can share some things between Vert.x Metrics and Tracing.

**Comment by radcortez** [comment]
> I've removed the Vert.x Http dependency to obtain the route and used the Vert.x Metrics instead. This is still not correct, because we cannot conflict with the Micrometer Metrics, but it was the only other way to retrieve the route.
> 
> In the meanwhile, I'll discuss with @ebullient on how we can share some things between Vert.x Metrics and Tracing.

For now, I guess the most pragmatic way is to check if the Micrometer extension is available and only register the OTel metrics portion if is not. I've also modified the Micrometer extension to provide a way to retrieve the selected Vert.x route, so it would work in any case.

File: extensions/opentelemetry/opentelemetry/deployment/src/main/java/io/quarkus/opentelemetry/deployment/OpenTelemetryProcessor.java [hunk 7]
```diff
@@ -43,6 +45,18 @@ public boolean getAsBoolean() {
         }
     }
 
+    static class RestClientAvailable implements BooleanSupplier {
+        @Override
+        public boolean getAsBoolean() {
+            try {
+                Class.forName("javax.ws.rs.client.ClientRequestFilter", false, Thread.currentThread().getContextClassLoader());
+                return true;
```
Comment (ebullient) [inline extensions/opentelemetry/opentelemetry/deployment/src/main/java/io/quarkus/opentelemetry/deployment/OpenTelemetryProcessor.java:53]: See what I do in some of the MicrometerProcessors. You can do this once (static final) so you aren't rechecking every time the boolean supplier is used.

File: extensions/opentelemetry/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/vertx/OpenTelemetryHttpServerMetrics.java [hunk 8]
```diff
@@ -0,0 +1,43 @@
+package io.quarkus.opentelemetry.runtime.tracing.vertx;
+
+import java.util.Optional;
+
+import io.vertx.core.Context;
+import io.vertx.core.http.impl.HttpServerRequestInternal;
+import io.vertx.core.spi.metrics.HttpServerMetrics;
+import io.vertx.core.spi.observability.HttpRequest;
+
```
Comment (ebullient) [inline extensions/opentelemetry/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/vertx/OpenTelemetryHttpServerMetrics.java:9]: Can you add a comment here re: mutual exclusivity with micrometer extension?

File: extensions/opentelemetry/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/vertx/OpenTelemetryVertxMetricsFactory.java [hunk 9]
```diff
@@ -0,0 +1,21 @@
+package io.quarkus.opentelemetry.runtime.tracing.vertx;
+
+import io.vertx.core.VertxOptions;
+import io.vertx.core.http.HttpServerOptions;
+import io.vertx.core.net.SocketAddress;
+import io.vertx.core.spi.VertxMetricsFactory;
+import io.vertx.core.spi.metrics.HttpServerMetrics;
+import io.vertx.core.spi.metrics.VertxMetrics;
+
+public class OpenTelemetryVertxMetricsFactory implements VertxMetricsFactory {
```
Comment (ebullient) [inline extensions/opentelemetry/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/vertx/OpenTelemetryVertxMetricsFactory.java:10]: Same here. Just to make sure relationship (or presence/absence) of this support w.r.t. micrometer extension is clear

Comment (ebullient) [reply extensions/opentelemetry/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/vertx/OpenTelemetryVertxMetricsFactory.java:10]: I might also consider making OpenTelemetryHttpServerMetrics an inner class so that it is a single unit that fills the gap when micrometer isn't around.

File: integration-tests/opentelemetry-vertx/src/main/resources/reflection-config.json [hunk 10]
```diff
@@ -0,0 +1,74 @@
+[
```
Comment (ebullient) [inline integration-tests/opentelemetry-vertx/src/main/resources/reflection-config.json:1]: Is this needed because of how we're testing?

File: integration-tests/opentelemetry-vertx/src/main/resources/application.properties [hunk 11]
```diff
@@ -0,0 +1 @@
+quarkus.native.additional-build-args =-H:ReflectionConfigurationFiles=reflection-config.json
```
Comment (ebullient) [inline integration-tests/opentelemetry-vertx/src/main/resources/application.properties:1]: Is this only needed because we're testing/checking span values?

File: extensions/opentelemetry/opentelemetry/deployment/src/main/java/io/quarkus/opentelemetry/deployment/OpenTelemetryProcessor.java (hunk 7 above)
Comment (radcortez) [reply extensions/opentelemetry/opentelemetry/deployment/src/main/java/io/quarkus/opentelemetry/deployment/OpenTelemetryProcessor.java:53]: Sure.

File: extensions/opentelemetry/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/vertx/OpenTelemetryHttpServerMetrics.java (hunk 8 above)
Comment (radcortez) [reply extensions/opentelemetry/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/vertx/OpenTelemetryHttpServerMetrics.java:9]: Sure.

File: extensions/opentelemetry/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/vertx/OpenTelemetryVertxMetricsFactory.java (hunk 9 above)
Comment (radcortez) [reply extensions/opentelemetry/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/vertx/OpenTelemetryVertxMetricsFactory.java:10]: Sure.

File: integration-tests/opentelemetry-vertx/src/main/resources/reflection-config.json (hunk 10 above)
Comment (radcortez) [reply integration-tests/opentelemetry-vertx/src/main/resources/reflection-config.json:1]: Yes. This is in the integration test modules, so not a big deal.

File: integration-tests/opentelemetry-vertx/src/main/resources/application.properties (hunk 11 above)
Comment (radcortez) [reply integration-tests/opentelemetry-vertx/src/main/resources/application.properties:1]: Yes. This is in the integration test modules, so not a big deal.

**Review by ebullient — APPROVED** [review]

File: integration-tests/opentelemetry-vertx/src/main/resources/application.properties (hunk 11 above)
Comment (ebullient) [reply integration-tests/opentelemetry-vertx/src/main/resources/application.properties:1]: Well. I just wanted to make sure that a user would not have to do this in their app. ;)

Comment (radcortez) [reply integration-tests/opentelemetry-vertx/src/main/resources/application.properties:1]: It should have worked it `@RegisterForReflection`, but for some reason it didn't work. I'll have to look into that.
