### PR TITLE
ArC - fix AnnotationStore

### LINKED ISSUE #10593: ArC AnnotationStore - AnnotationTarget is incorrectly used as a key in a Map
`ClassInfo`  and `FieldInfo` do not override `equals()`/`hashCode()`. Moreover, new `FieldInfo` objects are created for each `ClassInfo.fields()` invocation.

### PR DESCRIPTION
**Pull request by mkouba**
- AnnotationTarget was incorrectly used as a key in a Map
- resolves #10593

### CODE REVIEW

**Comment by manovotn** [comment]
FTR, this is the relevant Jandex issue - https://github.com/wildfly/jandex/issues/83

**Review by manovotn — APPROVED** [review]
Good catch!

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/AnnotationStore.java [hunk 1]
```diff
@@ -144,4 +148,65 @@ public Transformation transform() {
...
+                case CLASS:
+                    return target.asClass().name().hashCode();
+                default:
+                    throw unsupportedAnnoationTarget(target);
+            }
+        }
+
+    }
+
+    private static IllegalArgumentException unsupportedAnnoationTarget(AnnotationTarget target) {
```
Comment (gastaldi) [inline independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/AnnotationStore.java:208]:
```suggestion
    private static IllegalArgumentException unsupportedAnnotationTarget(AnnotationTarget target) {
```
