### PR TITLE
Properly perform reflection registration for @Gauge instances

### LINKED ISSUE #32427: Smallrye-metrics integration test fails when passing `-H:-ParseOnce` GraalVM option
### Describe the bug

$title

### Expected behavior

Test should pass.

### Actual behavior

Test fails (at runtime) with the following error:

```
2023-04-05 13:27:19,321 ERROR [io.qua.run.Application] (main) Failed to start application (with profile [prod]): java.lang.NoSuchMethodException: io.quarkus.it.metrics.DummyGaugeNoReflectionAnnotation.<init>()
	at java.base@17.0.6/java.lang.Class.getConstructor0(DynamicHub.java:3585)
	at java.base@17.0.6/java.lang.Class.getDeclaredConstructor(DynamicHub.java:2754)
	at io.quarkus.arc.impl.Reflections.findConstructor(Reflections.java:120)
	at io.quarkus.it.metrics.DummyGaugeNoReflectionAnnotation_Bean.doCreate(Unknown Source)
	at io.quarkus.it.metrics.DummyGaugeNoReflectionAnnotation_Bean.create(Unknown Source)
	at io.quarkus.it.metrics.DummyGaugeNoReflectionAnnotation_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:113)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:37)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:34)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:34)
	at io.quarkus.it.metrics.DummyGaugeNoReflectionAnnotation_Observer_init_d9b3512abf4722e7f3d533b41bf11910f3524d6a.notify(Unknown Source)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:344)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:326)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:82)
	at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:151)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:102)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
```

### How to Reproduce?

```
./mvnw -Dnative -pl integration-tests/smallrye-metrics \
  -Dnative.surefire.skip -Dformat.skip -Dno-descriptor-tests \
  clean verify \
  -Dquarkus.native.additional-build-args=-H:-ParseOnce
```

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #32427

### CODE REVIEW

File: extensions/smallrye-metrics/deployment/src/main/java/io/quarkus/smallrye/metrics/deployment/SmallRyeMetricsProcessor.java [hunk 1]
```diff
@@ -286,10 +285,12 @@ public void transform(TransformationContext context) {
...
     @BuildStep
     void reflectiveMethodsWithGauges(BeanArchiveIndexBuildItem beanArchiveIndex,
-            BuildProducer<ReflectiveMethodBuildItem> reflectiveMethods) {
+            BuildProducer<ReflectiveClassBuildItem> reflectiveClass) {
         for (AnnotationInstance annotation : beanArchiveIndex.getIndex().getAnnotations(GAUGE)) {
             if (annotation.target().kind().equals(AnnotationTarget.Kind.METHOD)) {
-                reflectiveMethods.produce(new ReflectiveMethodBuildItem(annotation.target().asMethod()));
+                reflectiveClass.produce(
+                        ReflectiveClassBuildItem.builder(annotation.target().asMethod().declaringClass().name().toString())
+                                .methods(true).constructors(true).build());
```
Comment (gsmet) [inline extensions/smallrye-metrics/deployment/src/main/java/io/quarkus/smallrye/metrics/deployment/SmallRyeMetricsProcessor.java:293]: It won't be problematic to register the classes several times? I think we usually build a `Set` when doing that.

Comment (geoand) [reply extensions/smallrye-metrics/deployment/src/main/java/io/quarkus/smallrye/metrics/deployment/SmallRyeMetricsProcessor.java:293]: It will not be problematic because of how we [aggregate](https://github.com/quarkusio/quarkus/blob/e145e31077afbc4cb3fbc4defb8636e344ab5854/core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageReflectConfigStep.java#L146) the info.

But I'll indulge and add a `Set`

**Review by ebullient — APPROVED** [review]
