### PR TITLE
Make sure that Flyway resources are only processed once

### LINKED ISSUE #10215: Flyway Callback Scripts Failing When Running mvn test
**Describe the bug**
I have a "beforeMigrate" flyway callback script. when I run **mvn test** I get the flyway error:

I'm also using test containers

```
2020-06-24 11:33:53,683 INFO  [org.fly.cor.int.lic.VersionPrinter] (main) Flyway Community Edition 6.4.2 by Redgate
2020-06-24 11:33:54,085 INFO  [org.fly.cor.int.dat.DatabaseFactory] (main) Database: jdbc:mysql://localhost:32773/test_db (MySQL 5.7)
2020-06-24 11:33:54,164 ERROR [io.qua.application] (main) Failed to start application: org.flywaydb.core.api.FlywayException: Found more than 1 SQL callback script called beforeMigrate!
Offenders:
-> /.../target/classes/db/migration/beforeMigrate.sql
-> /..../target/classes/db/migration/beforeMigrate.sql
        at org.flywaydb.core.internal.callback.SqlScriptCallbackFactory.<init>(SqlScriptCallbackFactory.java:79)
        at org.flywaydb.core.Flyway.prepareCallbacks(Flyway.java:655)
        at org.flywaydb.core.Flyway.execute(Flyway.java:517)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:159)
        at io.quarkus.flyway.runtime.FlywayRecorder.doStartActions(FlywayRecorder.java:53)
        at io.quarkus.deployment.steps.FlywayProcessor$createBeansAndStartActions-1520831253.deploy_0(FlywayProcessor$createBeansAndStartActions-1520831253.zig:76)
        at io.quarkus.deployment.steps.FlywayProcessor$createBeansAndStartActions-1520831253.deploy(FlywayProcessor$createBeansAndStartActions-1520831253.zig:36)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:420)
        at io.quarkus.runtime.Application.start(Application.java:90)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.runner.bootstrap.StartupActionImpl.run(StartupActionImpl.java:222)
        at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:156)
        at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:297)
        at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:330)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$7(ClassBasedTestDescriptor.java:359)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:35

```

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #10215

### CODE REVIEW

File: extensions/flyway/deployment/src/main/java/io/quarkus/flyway/FlywayProcessor.java [hunk 1]
```diff
@@ -196,9 +195,9 @@ ServiceStartBuildItem createBeansAndStartActions(FlywayRecorder recorder,
         return migrationLocations;
     }
 
-    private List<String> discoverApplicationMigrations(Collection<String> locations) throws IOException, URISyntaxException {
+    private Set<String> discoverApplicationMigrations(Collection<String> locations) throws IOException, URISyntaxException {
         try {
-            List<String> applicationMigrationResources = new ArrayList<>();
+            Set<String> applicationMigrationResources = new HashSet<>();
```
Comment (sirAlexander) [inline extensions/flyway/deployment/src/main/java/io/quarkus/flyway/FlywayProcessor.java:200]: nice one @geoand

Comment (geoand) [reply extensions/flyway/deployment/src/main/java/io/quarkus/flyway/FlywayProcessor.java:200]: Yeah, because we do resource discovery at build time we need this to avoid duplicated being passed to Flyway

Comment (sirAlexander) [reply extensions/flyway/deployment/src/main/java/io/quarkus/flyway/FlywayProcessor.java:200]: Will this fix make it into 1.5.3?

Comment (geoand) [reply extensions/flyway/deployment/src/main/java/io/quarkus/flyway/FlywayProcessor.java:200]: There won't be a 1.5.3 most likely. It should hopefully be in the upcoming 1.6.0.CR1

Comment (sirAlexander) [reply extensions/flyway/deployment/src/main/java/io/quarkus/flyway/FlywayProcessor.java:200]: any ETA on 1.6.0.CR1.

Comment (geoand) [reply extensions/flyway/deployment/src/main/java/io/quarkus/flyway/FlywayProcessor.java:200]: Should be in a few days

**Review by gsmet — APPROVED** [review]
