### PR TITLE
Fix regressions in Kubernetes health handling

### LINKED ISSUE #14438: Kubernetes: liveness and readiness probes ignore the `quarkus.http.root-path` setting
Seems that we have a [regression issue](https://github.com/quarkusio/quarkus/issues/6833): 
Works on 1.7
Fails on 1.11.0.Final

[Jira Ref](https://issues.redhat.com/browse/QUARKUS-705)

### PR DESCRIPTION
**Pull request by geoand**
This was introduced when we moved framework specific endpoint under /q.
It seems like `KubernetesWithRootAndHealthTest` was erroneously updated then

Fixes: #14438

### CODE REVIEW

File: extensions/smallrye-health/deployment/src/main/java/io/quarkus/smallrye/health/deployment/SmallRyeHealthProcessor.java [hunk 1]
```diff
@@ -299,17 +300,29 @@ private void warnIfJaxRsPathUsed(IndexView index, DotName healthAnnotation) {
...
                 new KubernetesHealthReadinessPathBuildItem(
-                        frameworkRootPath.adjustPath(healthConfig.rootPath + healthConfig.readinessPath)));
+                        kubernetesPath(httpConfig, frameworkRootPath, healthConfig.rootPath, healthConfig.readinessPath)));
+    }
+
+    private String kubernetesPath(HttpBuildTimeConfig httpConfig, NonApplicationRootPathBuildItem frameworkRootPath,
+            String healthRootPath, String specificPath) {
+        String result = frameworkRootPath.adjustPath(healthRootPath + specificPath);
+        if (!httpConfig.rootPath.equals("/")) {
+            String prefix = httpConfig.rootPath.endsWith("/")
```
Comment (kenfinnigan) [inline extensions/smallrye-health/deployment/src/main/java/io/quarkus/smallrye/health/deployment/SmallRyeHealthProcessor.java:320]: Can `httpConfig.adjustPath()` be used instead of the manual path manipulation?

Comment (geoand) [reply extensions/smallrye-health/deployment/src/main/java/io/quarkus/smallrye/health/deployment/SmallRyeHealthProcessor.java:320]: Good idea. I'll add that method as it currently doesn't exist

Comment (geoand) [reply extensions/smallrye-health/deployment/src/main/java/io/quarkus/smallrye/health/deployment/SmallRyeHealthProcessor.java]: PR updated as per your suggestion

Comment (kenfinnigan) [reply extensions/smallrye-health/deployment/src/main/java/io/quarkus/smallrye/health/deployment/SmallRyeHealthProcessor.java]: It doesn't? Thought it did as I'd done the same for non app endpoint.

**Review by kenfinnigan — APPROVED** [review]

File: extensions/smallrye-health/deployment/src/main/java/io/quarkus/smallrye/health/deployment/SmallRyeHealthProcessor.java (hunk 1 above)
Comment (geoand) [reply extensions/smallrye-health/deployment/src/main/java/io/quarkus/smallrye/health/deployment/SmallRyeHealthProcessor.java]: Maybe it was in some other http related config
