### PR TITLE
Hibernate Reactive services initiator fix

### LINKED ISSUE #10187: Hibernate Reactive bug with generated IDs
When using generated IDs such as:

```java
    @Id
    @GeneratedValue
    public Long id;

```

in HR I get:

```
java.lang.UnsupportedOperationException: The application must supply JDBC connections
	at org.hibernate.engine.jdbc.connections.internal.UserSuppliedConnectionProviderImpl.getConnection(UserSuppliedConnectionProviderImpl.java:44)
	at org.hibernate.internal.NonContextualJdbcConnectionAccess.obtainConnection(NonContextualJdbcConnectionAccess.java:38)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:104)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:134)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.connection(StatementPreparerImpl.java:50)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$1.doPrepare(StatementPreparerImpl.java:90)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:176)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareStatement(StatementPreparerImpl.java:75)
	at org.hibernate.id.enhanced.SequenceStructure$1.getNextValue(SequenceStructure.java:93)
	at org.hibernate.id.enhanced.NoopOptimizer.generate(NoopOptimizer.java:40)
	at org.hibernate.id.enhanced.SequenceStyleGenerator.generate(SequenceStyleGenerator.java:523)
	at org.hibernate.reactive.event.impl.AbstractReactiveSaveEventListener.generateId(AbstractReactiveSaveEventListener.java:172)
	at org.hibernate.reactive.event.impl.AbstractReactiveSaveEventListener.reactiveSaveWithGeneratedId(AbstractReactiveSaveEventListener.java:154)
	at org.hibernate.reactive.event.impl.DefaultReactivePersistEventListener.entityIsTransient(DefaultReactivePersistEventListener.java:178)
	at org.hibernate.reactive.event.impl.DefaultReactivePersistEventListener.reactiveOnPersist(DefaultReactivePersistEventListener.java:126)
	at org.hibernate.reactive.event.impl.DefaultReactivePersistEventListener.reactiveOnPersist(DefaultReactivePersistEventListener.java:56)

```

This is because `ReactiveIdentifierGeneratorFactoryInitiator` is supposed to take over the metamodel's `IdentifierGenerator` creation, but it gets registered too late after ORM is booted and has built its metamodel with the JDBC `IdentifierGenerator`.

ATM for ORM we register `QuarkusMutableIdentifierGeneratorFactoryInitiator` in `RecordableBootstrap` while for HR we register `ReactiveIdentifierGeneratorFactoryInitiator.INSTANCE` in `PreconfiguredReactiveServiceRegistryBuilder`.

### PR DESCRIPTION
**Pull request by Sanne**
Fixes #10187

### CODE REVIEW

**Comment by Sanne** [comment]
@ebullient : eb365c1 is meant for you. Is that what you had in mind?

File: extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/boot/LightPersistenceXmlDescriptor.java [hunk 1]
```diff
@@ -36,9 +36,6 @@ public LightPersistenceXmlDescriptor(final PersistenceUnitDescriptor toClone) {
     }
 
     private static void verifyIgnoredFields(final PersistenceUnitDescriptor toClone) {
-        if (toClone.getNonJtaDataSource() != null) {
-            throw new UnsupportedOperationException("Value found for #getNonJtaDataSource : not supported yet");
-        }
```
Comment (Sanne) [inline extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/boot/LightPersistenceXmlDescriptor.java:41]: the same check is repeated below

**Comment by Sanne** [comment]
Assigned to @gsmet as it's rather urgent, but maybe @FroMage or @emmanuelbernard have time?

**Review by gastaldi — APPROVED** [review]
LGTM

**Review by gsmet — APPROVED** [review]

**Comment by ebullient** [comment]
> @ebullient : [eb365c1](https://github.com/quarkusio/quarkus/commit/eb365c1460746a1dc422a3ce627e0409251439c1) is meant for you. Is that what you had in mind?

Yes! Thanks =)

File: extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/boot/RecordableBootstrapFactory.java [hunk 2]
```diff
@@ -0,0 +1,63 @@
...
+        // N.B. support for custom IntegratorProvider injected via Properties (as
+        // instance) removed
+
+        final QuarkusIntegratorServiceImpl integratorService = new QuarkusIntegratorServiceImpl(providedClassLoaderService);
+        final QuarkusStrategySelectorBuilder strategySelectorBuilder = new QuarkusStrategySelectorBuilder();
+        final StrategySelector strategySelector = strategySelectorBuilder.buildSelector(providedClassLoaderService);
+        return new BootstrapServiceRegistryImpl(true, providedClassLoaderService, strategySelector, integratorService);
+    }
+
+    private static InitialInitiatorListProvider initReactiveListProviderMaybe() {
```
Comment (FroMage) [inline extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/boot/RecordableBootstrapFactory.java:49]: In ORM Panache I have used a list of `BuildItem` to register optional stuff like these. Otherwise a service loader would work too. I guess both would be better than reflection, no?

**Review by FroMage — APPROVED** [review]

File: extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/boot/RecordableBootstrapFactory.java (hunk 2 above)
Comment (Sanne) [reply extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/boot/RecordableBootstrapFactory.java:49]: I considered that, but this code is invoked from within a Bytecode Recorder.

This implies that if I were to pass the full list of Initiators to the recorder from the layer in which I have BuildItems, I'd need to load and proxy many more classes - which then get loaded by reflection anyway.

If I were to "just" pass the InitialInitiatorListProvider it would also need to be recorded, proxied and loaded again.. with the added complexity of having a BuildItem needed for this, and need some way to enforce it to be one class at most?

Happy to revisit, but I don't feel like it would be much better.

Comment (Sanne) [reply extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/boot/RecordableBootstrapFactory.java:49]: P.B. I considered the ServiceLoader at first, but I really want "only one" - if there's a list of such providers it's a problem, it's not meant as an SPI. Single-named constant seems more fitting.

Comment (FroMage) [reply extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/boot/RecordableBootstrapFactory.java:49]: Fair enough :)
