### PR TITLE
Check OIDC discovery 'introspection_endpont' property

### LINKED ISSUE #15440: OIDC Client stopped working and fails with 500 Internal Server
**Describe the bug**
Having this configuration:

```
# Security
quarkus.oidc.auth-server-url=http://localhost:8180/auth/realms/test-realm
quarkus.oidc.client-id=test-application-client
quarkus.oidc.credentials.secret=test-application-client-secret
quarkus.http.auth.permission.authenticated.paths=/*
quarkus.http.auth.permission.authenticated.policy=authenticated
org.eclipse.microprofile.rest.client.propagateHeaders=Authorization

# OIDC Client Configuration
quarkus.oidc-client.auth-server-url=http://localhost:8180/auth/realms/test-realm
quarkus.oidc-client.client-id=test-application-client
quarkus.oidc-client.credentials.secret=test-application-client-secret
```

And this REALM configuration for Keycloak:

```
"clients": [
    {
      "clientId": "test-application-client",
      "enabled": true,
      "protocol": "openid-connect",
      "standardFlowEnabled": true,
      "implicitFlowEnabled": false,
      "directAccessGrantsEnabled": true,
      "serviceAccountsEnabled": true,
      "clientAuthenticatorType": "client-secret",
      "secret": "test-application-client-secret",
      "redirectUris": [
        "*"
      ]
    }
```

When running our application, it fails with the next exception:

```
2021-03-03 15:34:06,728 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-14) HTTP Request to /rest-pong failed, error id: b24d56d4-cfff-46e3-95e2-b9739e981896-5: io.vertx.core.VertxException: Invalid url: null
	at io.vertx.ext.web.client.impl.WebClientBase.requestAbs(WebClientBase.java:256)
	at io.vertx.ext.web.client.impl.WebClientBase.requestAbs(WebClientBase.java:246)
	at io.vertx.ext.web.client.impl.WebClientBase.postAbs(WebClientBase.java:176)
	at io.vertx.mutiny.ext.web.client.WebClient.postAbs(WebClient.java:334)
	at io.quarkus.oidc.runtime.OidcProviderClient.getHttpResponse(OidcProviderClient.java:95)
	at io.quarkus.oidc.runtime.OidcProviderClient.introspectToken(OidcProviderClient.java:63)
	at io.quarkus.oidc.runtime.OidcProvider.introspectToken(OidcProvider.java:115)
	at io.quarkus.oidc.runtime.OidcIdentityProvider.introspectTokenUni(OidcIdentityProvider.java:275)
	at io.quarkus.oidc.runtime.OidcIdentityProvider.verifyTokenUni(OidcIdentityProvider.java:251)
	at io.quarkus.oidc.runtime.OidcIdentityProvider.createSecurityIdentityWithOidcServer(OidcIdentityProvider.java:122)
	at io.quarkus.oidc.runtime.OidcIdentityProvider.access$200(OidcIdentityProvider.java:34)
	at io.quarkus.oidc.runtime.OidcIdentityProvider$3.apply(OidcIdentityProvider.java:115)
	at io.quarkus.oidc.runtime.OidcIdentityProvider$3.apply(OidcIdentityProvider.java:109)
```

Our project was working fine before these changes were merged: https://github.com/quarkusio/quarkus/pull/14953. So, this is a regression issue.

**To Reproduce**
1- git clone https://github.com/quarkus-qe/beefy-scenarios
2- cd beefy-scenarios/013-quarkus-oidc-restclient
4- mvn clean install (it needs to have built quarkus master locally)

**Environment (please complete the following information):**
 - Quarkus version or git rev: 999-SNAPSHOT

### PR DESCRIPTION
**Pull request by sberyozkin**
Fixes #15440.

This PR checks not only the legacy `token_introspection_endpoint` but also `introspection_endpoint` discovery property.
How did the tests pass without it ? 1) `integration-tests/oidc_wiremock` uses `token_introspection_endpoint` while `integration-tests/oidc_tenancy` which has a few tests involving the introspection use the test `OidcResource` and a non-discovery option to set the introspection path directly on `OidcTenantConfig`.

This PR also makes sure the extra token verification failures are correctly returned as `AuthenticationFailedException` - after I fixed the `introspection_endpoint` check the `integration-tests/oidc` test which sends a refresh token as a bearer token and expects 401 started failing with 500. The reason it was passing before the fix is because: Keycloak RT is JWT but its verification fails due to `UnresolvedKeyException` as it has no matching JWK - and since the live KC `introspection_endpoint` was missed - it was immediately returning 401. With the fix the RT is successfully introspected but now the code which has always been used before is hit which throws `OIDCException` if the JWT `typ` is `Refresh` - however during the refactoring  wrapping this exception as `AuthenticationFailedException` was lost which is now restored.

I've also added one more test sending an opaque bearer token which is expected to fail with 401. And restored one test which was accidentally disabled during the refactoring

Hope  it clarifies it all.  

CC @Sgitario

### CODE REVIEW

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcConfigurationMetadata.java [hunk 1]
```diff
@@ -3,6 +3,15 @@
 import io.vertx.core.json.JsonObject;
 
 public class OidcConfigurationMetadata {
+    private static final String ISSUER = "issuer";
+    private static final String TOKEN_ENDPOINT = "token_endpoint";
+    private static final String INTROSPECTION_ENDPOINT = "introspection_endpoint";
+    private static final String TOKEN_INTROSPECTION_ENDPOINT = "token_introspection_endpoint";
```
Comment (pedroigor) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcConfigurationMetadata.java:9]: We should just ignore this one.

Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcConfigurationMetadata.java:9]: Hi @pedroigor 
I'd be happy to do it, but `vertx-auth` supports it - which is why `integration-tests/oidc-wiremock` passes (it uses `token-introspection-endpoint`). Would you mind if we delay removing this property, may be till Quarkus 2 ? At the moment I'd like to minimize any side-effects with the migration...
That said, if this property was only used with very old Keycloak versions which Quarkus users have a low chance of using then indeed we can avoid this extra check
What do you think ?

Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcConfigurationMetadata.java:9]: @pedroigor I guess we can indeed continue focusing on the standard path - if someone reports any problem in 1.13.0.CR1 then I'll put it back, let me update

**Review by pedroigor — APPROVED** [review]
