### PR TITLE
spring-di: support scopes on bean methods #2778

### LINKED ISSUE #2778: Support scopes on @Bean methods in spring-di
From spring Javadoc (https://github.com/spring-projects/spring-framework/blob/master/spring-context/src/main/java/org/springframework/context/annotation/Bean.java#L82):

> `@Scope`  [on method annotated with  `@Bean` ] changes the bean's scope from singleton to the specified scope" 

But the current implementation of SpringDiProcessor doesn't conform to this:

1. `@Dependent` scope is added to all beans produced by `@Bean` methods in `@Configuration` classes, so following #2178 in Quarkus 0.14.0+ it generates an error:

```
@Configuration
public class MyConfig {

	@Bean
	@Singleton // Causes "multiple scope type annotations" error
	public SomeBean myBean() {
		return new SomeBean();
	}

	private static class SomeBean {
	}
}
```

Actual behavior:
```
Caused by: javax.enterprise.inject.spi.DefinitionException: Producer method org.acme.quickstart.MyConfig$SomeBean myBean() declares multiple scope type annotations: javax.inject.Singleton, javax.enterprise.context.Dependent
	at io.quarkus.arc.processor.Beans.multipleScopesFound(Beans.java:281)
	at io.quarkus.arc.processor.Beans.createProducerMethod(Beans.java:175)
	at io.quarkus.arc.processor.BeanDeployment.findBeans(BeanDeployment.java:696)
	at io.quarkus.arc.processor.BeanDeployment.<init>(BeanDeployment.java:142)
	at io.quarkus.arc.processor.BeanProcessor.process(BeanProcessor.java:153)
	at io.quarkus.arc.deployment.ArcAnnotationProcessor.build(ArcAnnotationProcessor.java:282)
```
Expected behavior: the default scope should be singleton (not dependent), and it should also be allowed to make it explicit with `@javax.inject.Singleton` without causing "multiple scope type annotations" error.

2. Using `@org.springframework.context.annotation.Scope` causes a NPE: 

```
@Bean
@Scope("singleton") // NPE
public SomeBean myBean() {
	return new SomeBean();
}
```

Actual behavior:
```
Caused by: java.lang.NullPointerException
	at io.quarkus.spring.di.deployment.SpringDIProcessor.getScope(SpringDIProcessor.java:190)
	at io.quarkus.spring.di.deployment.SpringDIProcessor.getAnnotationsToAdd(SpringDIProcessor.java:297)
	at io.quarkus.spring.di.deployment.SpringDIProcessor.lambda$beanTransformer$1(SpringDIProcessor.java:126)
	at io.quarkus.arc.processor.AnnotationStore.transform(AnnotationStore.java:116)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1688)
	at io.quarkus.arc.processor.AnnotationStore.getAnnotations(AnnotationStore.java:70)
	at io.quarkus.arc.processor.AnnotationStore.hasAnnotation(AnnotationStore.java:94)
	at io.quarkus.arc.processor.BeanDeployment.findBeans(BeanDeployment.java:599)
	at io.quarkus.arc.processor.BeanDeployment.<init>(BeanDeployment.java:142)
	at io.quarkus.arc.processor.BeanProcessor.process(BeanProcessor.java:153)
	at io.quarkus.arc.deployment.ArcAnnotationProcessor.build(ArcAnnotationProcessor.java:282)
```
Expected behavior: scope should be singleton.

3.  Other Spring scopes (`org.springframework.web.context.annotation.RequestScope`) do not seem taken into account ?

```
@Bean
@RequestScope
public SomeBean myBean() {
	return new SomeBean();
}
```

Actual behavior:
```
Caused by: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.acme.quickstart.MyBean and qualifiers [@Default]
	- java member: org.acme.quickstart.GreetingService#<init>()
	- declared on CLASS bean [types=[org.acme.quickstart.GreetingService, java.lang.Object], qualifiers=[@Default, @Any], target=org.acme.quickstart.GreetingService]
	at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:378)
	at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:366)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:286)
```
Expected behavior: the bean should be seen, with scope javax.enterprise.context.RequestScoped

**To Reproduce**
1. Add configuration class into a module with empty META-INF/beans.xml
2. Use spring-di quarkus extension
3. Run a @QuarkusTest or Maven build

**Environment:**
 - Output of `uname -a` or `ver`: Microsoft Windows [version 10.0.17134.765]
 - Output of `java -version`: jdk1.8.0_181 Java HotSpot(TM) 64-Bit Server VM
 - GraalVM version (if different from Java): N/A
 - Quarkus version or git rev: 0.16.1

**Additional context**
I was looking at contributing a quick fix to SpringDiProcessor, but it appears more complex I initially thought:
- https://github.com/quarkusio/quarkus/blob/0.16.1/extensions/spring-di/deployment/src/main/java/io/quarkus/spring/di/deployment/SpringDIProcessor.java#L187 : Jandex ClassInfo#annotations() returns all annotations (not only class-level) so this line seems wrong, but changing the behavior to instead loop on ClassInfo#classAnnotations() breaks some existing unit tests.
- in Jandex annotations are not stored in parent class AnnotationTarget (that's sad !), so the existing scope/stereotype determination logic will need be duplicated/refactored to support ClassInfo or MethodInfo.

### PR DESCRIPTION
**Pull request by rquinio**
Fixes #2778 

- Fix NPE when org.springframework.context.annotation.Scope is used on a bean method
- Change default bean implicit scope from dependent to singleton
- Do not process non-spring annotations (i.e. an explicit singleton) in spring-di, to avoid adding duplicate scopes with Arc processor

### CODE REVIEW

File: extensions/spring-di/deployment/src/main/java/io/quarkus/spring/di/deployment/SpringDIProcessor.java [hunk 1]
```diff
@@ -162,18 +162,24 @@ AnnotationsTransformerBuildItem beanTransformer(
...
+     * Translate spring built-in scope identifiers to CDI scopes.
      *
-     * @param clazz The class declaring the @Scope
+     * @param target The annotated element declaring the @Scope
      * @return A CDI built in (or session) scope that mostly matches
      *         the spring one. Websocket scope is currently mapped to @Dependant
      *         and spring custom scopes are not currently handled.
      */
-    private DotName getScope(final ClassInfo clazz) {
-        if (!clazz.annotations().containsKey(SPRING_SCOPE_ANNOTATION)) {
```
Comment (rquinio) [inline extensions/spring-di/deployment/src/main/java/io/quarkus/spring/di/deployment/SpringDIProcessor.java]: Note: I've changed ClassInfo#annotations() (all levels annotations in the class) to ClassInfo#classAnnotation() (only class-level annotations of the class). The former was causing NPE when trying to access a method-level annotation value via clazz.classAnnotation().value()

File: extensions/spring-di/deployment/src/main/java/io/quarkus/spring/di/deployment/SpringDIProcessor.java [hunk 2]
```diff
@@ -372,10 +378,17 @@ private void visitAnnotation(final DotName clazz, final IndexView index, final M
...
-                annotationsToAdd.add(create(
-                        CDI_DEPENDENT_ANNOTATION,
-                        target,
-                        Collections.emptyList()));
+                DotName declaredScope = getScope(methodInfo);
+                // Non-spring specific annotations are processed by Arc
+                if (declaredScope == null && !methodInfo.hasAnnotation(CDI_SINGLETON_ANNOTATION)) {
+                    declaredScope = CDI_SINGLETON_ANNOTATION; // implicit default scope in spring
+                }
+                if (declaredScope != null) {
```
Comment (geoand) [inline extensions/spring-di/deployment/src/main/java/io/quarkus/spring/di/deployment/SpringDIProcessor.java]: I don't think we ned this check anymore

File: extensions/spring-di/deployment/src/main/java/io/quarkus/spring/di/deployment/SpringDIProcessor.java [hunk 3]
```diff
@@ -372,10 +378,17 @@ private void visitAnnotation(final DotName clazz, final IndexView index, final M
                         CDI_PRODUCES_ANNOTATION,
                         target,
                         Collections.emptyList()));
-                annotationsToAdd.add(create(
-                        CDI_DEPENDENT_ANNOTATION,
-                        target,
-                        Collections.emptyList()));
+                DotName declaredScope = getScope(methodInfo);
+                // Non-spring specific annotations are processed by Arc
+                if (declaredScope == null && !methodInfo.hasAnnotation(CDI_SINGLETON_ANNOTATION)) {
```
Comment (geoand) [inline extensions/spring-di/deployment/src/main/java/io/quarkus/spring/di/deployment/SpringDIProcessor.java]: Can you clarify the second check a bit?

**Review by geoand — COMMENTED** [review]
Looks good to me, thanks!

Just a couple of comments, which are probably just questions and might not even require changes

File: extensions/spring-di/deployment/src/main/java/io/quarkus/spring/di/deployment/SpringDIProcessor.java (hunk 2 above)
Comment (rquinio) [reply extensions/spring-di/deployment/src/main/java/io/quarkus/spring/di/deployment/SpringDIProcessor.java]: We need it for the case of explicit `@Singleton` scope. Otherwise the integration tests I've added trigger duplicate scopes error.
I find out that spring-di should not add `@Singleton` because Arc also does it (not sure where). This seems to make sense since @Singleton is not a spring thing ?

File: extensions/spring-di/deployment/src/main/java/io/quarkus/spring/di/deployment/SpringDIProcessor.java (hunk 3 above)
Comment (rquinio) [reply extensions/spring-di/deployment/src/main/java/io/quarkus/spring/di/deployment/SpringDIProcessor.java]: It's linked to the previous review comment about the null check.

**Comment by geoand** [comment]
Great stuff, thanks @rquinio!

**Review by geoand — APPROVED** [review]
