### PR TITLE
Read client configuration directly from Config rather than via @ConfigRoot

### LINKED ISSUE #21332: Property expression `quarkus.http.test-port` with rest-client not working with 2.4.1
### Describe the bug

I'm having problems after upgrading from 2.3.1.Final to 2.4.1 Final. I'm using property expressions to test my RestClient. The test application.yaml has following properties

```quarkus:
  http:
    test-port: 0 # use random port
  rest-client:
    example-rest-client:
      url: 'http://localhost:${quarkus.http.test-port}'
```
so if the tests starts with random port like 61234 then the URL should be http://localhost:61234 . This works when using RestAssured. But this does not work for injected RestClient. But it did work before with 2.3.1.Final. So something must have changed in the mean time.

When debugging and checking the property with ConfigProvider.getConfig().getConfigValue("quarkus.rest-client.example-rest-client.url") it also shows correct URL. I have a strong feeling that this is connected with creation of io.quarkus.restclient.config.RestClientsConfig as it already has the incorrect URL.

It was discussed on [Zulip](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Property.20expressions.20with.20rest-client.20not.20working.20with.202.2E4.2E1)

@radcortez wrote

> Roberto Cortez: ok this is caused by https://github.com/quarkusio/quarkus/pull/17220 and because REST Client configuration is now read from a ConfigRoot
> Roberto Cortez: the issue is that ConfigRoots are eagerly initialized with the configuration when the app starts (before determining the test port)
> Roberto Cortez: when the test port is mutated it is already too late, because the value is already set in the config root
>Roberto Cortez: not exactly sure what can we do here. I need to discuss this and think about it first

### Expected behavior

Property expressions evaluation works for rest-client properties with 2.4.1.Final

### Actual behavior

Property expressions are not evaluated for rest-client

### How to Reproduce?

Here is a small reproducer https://github.com/damian-burda/rest-client-prop-expression

Just build it with maven and the test will fail. Switch the version to 2.3.1.Final and it will work again.

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.4.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### LINKED ISSUE #21336: Hashicorp Vault integration stopped working in 2.4.0
### Describe the bug

Our application has a Rest-Client defined with `@RegisterRestClient(configKey = "aclient")`, and config 
```
aclient/mp-rest/url=https://somethi.ng
```
Most of the config lives is Hashicorp Vault when not running locally.
When upgrading to 2.4.0/.1 startup fails with
```
Caused by: java.lang.IllegalArgumentException: Unable to determine the proper baseUrl/baseUri. Consider registering using @RegisterRestClient(baseUri="someuri"), @RegisterRestClient(configKey="orkey"), or by adding 'quarkus.rest-con
fig."aclient".url' or 'quarkus.rest-config."aclient".uri' to your Quarkus configuration
```

Changing the config key to `quarkus.rest-config."aclient".url`, `quarkus.rest-config.aclient.url`, `quarkus.rest-client.aclient.url` has no effect.

Looking at RestClientBase between [2.3.1](https://github.com/quarkusio/quarkus/blob/2.3.1.Final/extensions/resteasy-classic/rest-client/runtime/src/main/java/io/quarkus/restclient/runtime/RestClientBase.javaa) and [2.4.1](https://github.com/quarkusio/quarkus/blob/2.4.1.Final/extensions/resteasy-classic/rest-client/runtime/src/main/java/io/quarkus/restclient/runtime/RestClientBase.java) we see that handling of config is changed from ` ConfigProvider.getConfig().getOptionalValue(property, class)` to [RestClientsConfig](https://github.com/quarkusio/quarkus/blob/2.4.1.Final/extensions/resteasy-classic/rest-client/config/src/main/java/io/quarkus/restclient/config/RestClientsConfig.java).

My hypothesis is that the code that set `RestClientsConfig.configs` (code generated by [RunTimeConfigurationGenerator](https://github.com/quarkusio/quarkus/blob/2.4.1.Final/core/deployment/src/main/java/io/quarkus/deployment/configuration/RunTimeConfigurationGenerator.java)?) uses `ConfigSource.getPropertyNames()`, and [VaultConfigSource](https://github.com/quarkusio/quarkus/blob/main/extensions/vault/runtime/src/main/java/io/quarkus/vault/runtime/config/VaultConfigSource.java#L51) return empty set for both `getProperties` and `getPropertyNames()`.
When setting breakpoint (java field breakpoint in Intellij) we see that the config from Vault loaded.

The same behaviour is seen with [quarkus-micrometer-registry-influx](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/.E2.9C.94.20quarkus-micrometer-registry-influx.20.2B.20Hashicorp.20Vault).

### Expected behavior

All config from Vault is used as if defined in application.properties.

### Actual behavior

Config values stored in Vault is not used, application crash with message that they are mssing.

### How to Reproduce?

* Combine guides for [rest-client](https://quarkus.io/guides/rest-client) and [vault](https://quarkus.io/guides/vault): [quarkus-vault-rest-client reproducer](https://github.com/computerlove/quarkus-vault-rest-client).
* Follow the steps for initializing the local Vault container. 
  * `docker run --rm --cap-add=IPC_LOCK -e VAULT_ADDR=http://localhost:8200 -p 8200:8200 --name=dev-vault vault:1.6.0` (Terminal A)
  * `docker exec -it dev-vault sh` (in new terminal B)
  * `export VAULT_TOKEN=$Root Token FROM terminal A ` (in terminal B)
  * `vault kv put secret/myapps/vault-quickstart/config a-private-key=123456`  (in terminal B)
  * ```
     cat <<EOF | vault policy write vault-quickstart-policy -
     path "secret/data/myapps/vault-quickstart/*" {
        capabilities = ["read"]
    }
    EOF

  * ```
     vault auth enable userpass
     vault write auth/userpass/users/bob password=sinclair policies=vault-quickstart-policy
  * Login to http://localhost:8200 with $Root Token FROM terminal A and add secrets in myapps/vault-quickstart/ (use do it in terminal B)

Downgrading to Quarkus 2.3.1 will make the application work as expected.

### Output of `uname -a` or `ver`

N/A

### Output of `java -version`

11, 17

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.4.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn 3.8.3

### Additional information

vault

### LINKED ISSUE #21341: MP REST Client configuration at runtime does not work since quarkus 2.4.0-final
### Describe the bug

In versions before quarkus 2.4.0-final the configuration of MP REST clients was possible during the runtime of the application. It was very helpful e.g to switch an client to a backup system if the productive system was not available. since quarkus 2.4.0-final the mutation of the Microprofile Rest Client properties during the runtime does not have effect.

Example:

Resource:
```
@RequestScoped
@Path("/hello")
public class GreetingResource {

    public static final String GREETING_MESSAGE = "Hello From GreetingResource";
    public static final String CONFIG_NAME_SALUTATION = "greetings.salutation";

    @ConfigProperty(name = CONFIG_NAME_SALUTATION, defaultValue = "Hoi!!")
    String salutation;

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        return salutation + " " + GREETING_MESSAGE;
    }
}
```

Client:
```
@RequestScoped
@RegisterRestClient(configKey = "greetings.client")
public interface GreetingsClient {

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello();
}
```

⚠️Test is failing since quarkus 2.4.0-final:
```
@QuarkusTest
public class GreetingResourceTest {

    @Inject
    @RestClient
    GreetingsClient greetingsClient;

    @Test
    @SetSystemProperty(key = "greetings.client/mp-rest/url", value = "https://www.google.de")
    public void testWithRestClientWithWrongUrl_ViaMP() {
        String message = greetingsClient.hello();
        assertThat(message, not(containsString(GreetingResource.GREETING_MESSAGE))); //⚠️failing since quarkus 2.4.0-final
    }
}
```

### Expected behavior

After the mutation of MP REST client configuration the newly created instance must use the changed configuration

### Actual behavior

MP REST Client configuration at runtime does not work since quarkus 2.4.0-final 

### How to Reproduce?

https://github.com/franden/issue-rest-client-configuration 
run `GreetingResourceTest.testWithRestClientWithWrongUrl_ViaMP` test

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19042.1288]

### Output of `java -version`

openjdk version "11.0.10" 2021-01-19 OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9) OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.4.1-final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d) Maven home: C:\Users\ivfrk\.m2\wrapper\dists\apache-maven-3.8.1-bin\2l5mhf2pq2clrde7f7qp1rdt5m\apache-maven-3.8.1 Java version: 11.0.10, vendor: AdoptOpenJDK, runtime: c:\Work\Tools\JDK\11\OpenJDK11U-jdk_x64_windows_hotspot_11.0.10_9\jdk-11.0.10+9 Default locale: de_DE, platform encoding: Cp1252 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

### Additional information

_No response_

### LINKED ISSUE #21345: REST Client Configuration via Uppercase/Underscore Environment Variables Stopped Working in 2.4.0
### Describe the bug

I have the following REST client:

```
package com.ionos.cloud.auth.user;
...
@RegisterRestClient(configKey = "user-api-rest-client")
public interface UserApiRestClient { ... }
```

I used to configure it via the following environment variable (as we can only use uppercase characters and underscores in our environment):
```
USER_API_REST_CLIENT_MP_REST_URL
```
This worked perfectly fine up to Quarkus 2.3.1.

In Quarkus 2.4.0 + 2.4.1, I get the following error message (I've added line breaks for better readability):
```
Caused by: java.lang.IllegalArgumentException: Unable to determine the proper baseUrl/baseUri.

Consider registering using @RegisterRestClient(baseUri="someuri"), 
                           @RegisterRestClient(configKey="orkey"), 
or by adding 'quarkus.rest-config."user-api-rest-client".url' 
          or 'quarkus.rest-config."user-api-rest-client".uri' 
to your Quarkus configuration
```

First of all, there's an error in that message, it should be "quarkus.rest-client", not "quarkus.rest-config" (see https://quarkus.io/guides/rest-client#create-the-configuration).

But that's not the issue here.

As per the documentation, all these configuration keys work fine (in a test environment):
```
user-api-rest-client/mp-rest/url
quarkus.rest-client.user-api-rest-client.url
quarkus.rest-client.user-api-rest-client.uri
quarkus.rest-client."user-api-rest-client".url
quarkus.rest-client."user-api-rest-client".uri
quarkus.rest-client."com.ionos.cloud.auth.user.UserApiRestClient".url
quarkus.rest-client."com.ionos.cloud.auth.user.UserApiRestClient".uri
```

However, as I said before, in our production environment, I can use only uppercase and underscore.

But all these keys do *not* work:
```
USER_API_REST_CLIENT_MP_REST_URL
QUARKUS_REST_CLIENT_USER_API_REST_CLIENT_URL
QUARKUS_REST_CLIENT_USER_API_REST_CLIENT_URI
QUARKUS_REST_CLIENT__USER_API_REST_CLIENT__URL
QUARKUS_REST_CLIENT__USER_API_REST_CLIENT__URI
QUARKUS_REST_CLIENT__COM_IONOS_CLOUD_AUTH_USER_USERAPIRESTCLIENT__URL
QUARKUS_REST_CLIENT__COM_IONOS_CLOUD_AUTH_USER_USERAPIRESTCLIENT__URI
```

### Expected behavior

Uppercase/underscore environment variables - such as the following ones - should be usable for REST client configuration:
```
<CONFIG_KEY>_MP_REST_URL
QUARKUS_REST_CLIENT_<CONFIG_KEY>_URL
QUARKUS_REST_CLIENT_<CONFIG_KEY>_URI
QUARKUS_REST_CLIENT__<CONFIG_KEY>__URL
QUARKUS_REST_CLIENT__<CONFIG_KEY>__URI
QUARKUS_REST_CLIENT__<FULLY_QUALIFIED_CLASS_NAME>__URL
QUARKUS_REST_CLIENT__<FULLY_QUALIFIED_CLASS_NAME>__URI
```

### Actual behavior

*None* of the following uppercase/underscore environment variables are usable for REST client configuration:
```
<CONFIG_KEY>_MP_REST_URL
QUARKUS_REST_CLIENT_<CONFIG_KEY>_URL
QUARKUS_REST_CLIENT_<CONFIG_KEY>_URI
QUARKUS_REST_CLIENT__<CONFIG_KEY>__URL
QUARKUS_REST_CLIENT__<CONFIG_KEY>__URI
QUARKUS_REST_CLIENT__<FULLY_QUALIFIED_CLASS_NAME>__URL
QUARKUS_REST_CLIENT__<FULLY_QUALIFIED_CLASS_NAME>__URI
```

### How to Reproduce?

1. Create a REST client with a config key.
2. Try to configure it via environment variables with only uppercase characters and underscores.

### Output of `uname -a` or `ver`

Linux debian 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux

### Output of `java -version`

openjdk version "16.0.1" 2021-04-20

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.4.0, 2.4.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3

### Additional information

_No response_

### LINKED ISSUE #21348: REST Client Config - Limitations of ConfigRoot `RestClientsConfig`
### Describe the bug

We are seeing several issues with the REST Client Config move to the `RestClientsConfig` ConfigRoot added in https://github.com/quarkusio/quarkus/pull/17220.

Related issues:
- https://github.com/quarkusio/quarkus/issues/21341
- https://github.com/quarkusio/quarkus/issues/21336
- https://github.com/quarkusio/quarkus/issues/21332
- https://github.com/quarkusio/quarkus/issues/21345

One of the main issues seems to be the expectation that the REST Client Config (or at least the URL) can be dynamically changed during runtime by just changing the configuration.

Another issue is the way that `RestClientConfig` is mapped. The use of `public Map<String, RestClientConfig> configs;` implies that named configuration (in this case the resource) is added by iterating the `Config#getPropertyNames`. This is usually ok because for most cases we are not aware of the named configuration and this is the only way to retrieve them. In the particular case of REST Clients, the named configuration is known at build time, but we ignore it and fill in the Map with `getPropertyNames` ignoring that some Config Sources like Vault do not provide their property names.

### PR DESCRIPTION
**Pull request by TomasHofman**
This should make it possible to read REST client configuration from vaults, which currently doesn't work due to the fact that vault config sources do not list their contents when `ConfigSource#getPropertyNames()` is called. This causes the properties from vaults to not being included in `@ConfigRoot` instances.

Related to https://github.com/quarkusio/quarkus/issues/21348

- Fixes https://github.com/quarkusio/quarkus/issues/21348
- Fixes https://github.com/quarkusio/quarkus/issues/21341
- Fixes https://github.com/quarkusio/quarkus/issues/21336
- Fixes https://github.com/quarkusio/quarkus/issues/21332
- Fixes https://github.com/quarkusio/quarkus/issues/21345

### CODE REVIEW

**Comment by TomasHofman** [comment]
Hello @radcortez @michalszynkiewicz , this is my proposal on how to modify the rest client configuration.

File: extensions/resteasy-classic/rest-client/deployment/src/test/java/io/quarkus/restclient/configuration/RestClientOverrideRuntimeConfigTest.java [hunk 1]
```diff
@@ -41,9 +41,6 @@ void overrideConfig() {
         assertTrue(specifiedDefaultValues.isPresent());
         assertTrue(specifiedDefaultValues.get().getPropertyNames()
                 .contains("io.quarkus.restclient.configuration.EchoClient/mp-rest/url"));
-        // This config key comes from the interceptor and it is recorded with an empty value. This allow the user to still override using the original key
-        assertEquals("", specifiedDefaultValues.get()
-                .getValue("quarkus.rest-client.\"io.quarkus.restclient.configuration.EchoClient\".url"));
```
Comment (TomasHofman) [inline extensions/resteasy-classic/rest-client/deployment/src/test/java/io/quarkus/restclient/configuration/RestClientOverrideRuntimeConfigTest.java:46]: @radcortez FYI - since the "url" property is no longer processed as part of any ConfigRoot, it's not going to be present in the "specifiedDefaultValues" source, so I need to remove this bit. Let me know if you want me to modify this test differently.

Comment (radcortez) [reply extensions/resteasy-classic/rest-client/deployment/src/test/java/io/quarkus/restclient/configuration/RestClientOverrideRuntimeConfigTest.java:46]: It's ok. This was because of https://github.com/quarkusio/quarkus/pull/20590 but with this PR is not required anymore.

**Comment by radcortez** [comment]
I guess the CI is not happy :(

**Comment by TomasHofman** [comment]
Note that this change should 

> I guess the CI is not happy :(

Yes, I will be looking into that :).

**Comment by TomasHofman** [comment]
CI looks OK now.

**Review by radcortez — APPROVED** [review]

**Comment by radcortez** [comment]
I guess the only downside is that the config documentation is not going to be auto-generated anymore. Maybe we can keep the `@ConfigGroup` and `@ConfigItem`s for documentation purposes?

**Comment by TomasHofman** [comment]
I didn't thought of that. I will put the annotations back in (hopefully that's enough for the docs generation to keep working).

**Comment by radcortez** [comment]
Since everything is Optional, it should be ok.

**Comment by geoand** [comment]
@radcortez I'll leave it to you to merge this

**Comment by gwenneg** [comment]
@gsmet Can this be backported to the next 2.5 release? All our projects are stuck with 2.3.1.Final because of the rest-client issues fixed by this PR.

**Comment by TomasHofman** [comment]
If this is backported, following PR should be backported too: https://github.com/quarkusio/quarkus/pull/21709
