### PR TITLE
ArC: fix build-time and runtime resolution of beans with recursive generic types

### LINKED ISSUE #17147: ArC fails to construct bean with self-referencing generic constraint
ArC appears to be unable to generate beans if they have a generic parameter and a constraint referencing the generic parameter, as is common for e.g. `T extends Comparable<T>`. The issue can be reproduced as follows:

```java
public class CdiProducers {
    @Produces
    public <T extends Comparable<T>> List<T> getSpecificList() {
        return new ArrayList<>();
    }
}
```

which results in the following error at build time:
```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:1.13.3.Final:build (default) on project my-project: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.arc.deployment.ArcProcessor#generateResources threw an exception: java.lang.IllegalStateException: Unable to construct the type handle for PRODUCER METHOD bean [types=[java.util.List<T extends java.util.List>, java.util.Collection<T extends java.util.List>, java.lang.Object, java.lang.Iterable<T extends java.util.List>], qualifiers=[@Default, @Any], target=java.util.List<T extends java.util.List> getSpecificList(), declaringBean=me.demo.CdiProducers]: Unsupported bean type: UNRESOLVED_TYPE_VARIABLE, T
[ERROR]         at io.quarkus.arc.processor.BeanGenerator.initConstructor(BeanGenerator.java:671)
[ERROR]         at io.quarkus.arc.processor.BeanGenerator.createConstructor(BeanGenerator.java:566)
[ERROR]         at io.quarkus.arc.processor.BeanGenerator.generateProducerMethodBean(BeanGenerator.java:398)
[ERROR]         at io.quarkus.arc.processor.BeanGenerator.generate(BeanGenerator.java:115)
[ERROR]         at io.quarkus.arc.processor.BeanProcessor.generateResources(BeanProcessor.java:181)
[ERROR]         at io.quarkus.arc.deployment.ArcProcessor.generateResources(ArcProcessor.java:458)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:920)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:829)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

with a prettyfied error message:
```
Build step io.quarkus.arc.deployment.ArcProcessor#generateResources threw an exception:
java.lang.IllegalStateException: Unable to construct the type handle for PRODUCER METHOD bean [
    types=[
        java.util.List<T extends java.util.List>,
        java.util.Collection<T extends java.util.List>,
        java.lang.Object,
        java.lang.Iterable<T extends java.util.List>
    ],
    qualifiers=[@Default, @Any],
    target=java.util.List<T extends java.util.List> getSpecificList(),
    declaringBean=me.demo.CdiProducers
]: Unsupported bean type: UNRESOLVED_TYPE_VARIABLE, T
```

A few more examples:
- does _not_ work: `<T extends List<T>>`
- _does_ work: `<T extends Serializable>`
- _does_ work: `<T>`

I have attached a sample project to reproduce the problem: [arc-selfreferencing-generic-constraint.zip](https://github.com/quarkusio/quarkus/files/6460654/arc-selfreferencing-generic-constraint.zip)

### PR DESCRIPTION
**Pull request by Ladicek**
Fixes #17147

Includes 3 commits:

### ArC: fix assignability check during build-time resolution

The `AssignabilityCheck.isAssignableFrom()` method used to search a Jandex index for subtypes of first type to determine if it is assignable from the second type. This doesn't work well with on-demand indexing; for example, if we ask the index for all subtypes of `Comparable`, we don't get anything, because JDK types are not in the index.

This commit reverses the `isAssignableFrom()` logic: instead of searching the index for subtypes of the first type, it searches the index for supertypes of the second. That works well with on-demand indexing and doesn't change meaning.

This change alone is enough to fix build-time resolution that involves recursive generic type. For example, a `@Dependent` producer method for type `List<T>`, where `T extends Comparable<T>`, now correctly matches when resolving an injection point of type `List<String>`.

### ArC: fix runtime representation of recursive bean types

This was already attempted once, but the previous fix only worked well for simple recursive generic types. This commit fixes the runtime representation even for mutually recursive generic types.

The fix uses the following observation: in a type, multiple occurences of a type variable (as denoted by the type variable identifier) always refers to the same type. Therefore, it is not necessary to maintain a stack of type variables as they being processed. Instead, a simple string-keyed map is enough to:

1. canonicalize all occurences of a type variable;
2. canonicalize all occurences of a type variable reference;
3. at the end, patch all type variable references to point to the type variables.

The canonicalization was not performed before, but is necessarsy now (to correctly handle equality of multiple occurences of type variables), plus it also slightly improves runtime footprint of the set of bean types.

### ArC: fix bean type assignability for recursive generic types

This is adapted from [WELD-2738](https://github.com/weld/core/pull/2826).

### CODE REVIEW

**Comment by Ladicek** [comment]
Draft because this only fixes build-time resolution and not runtime programmatic lookup. So it's only a partial fix (for now).

**Review by mkouba — COMMENTED** [review]
Nice idea! But I think that we need to fix the runtime assignability rules as well, i.e. we should really be consistent here ;-).

**Comment by manovotn** [comment]
@Ladicek want me to take a look into the runtime part of this?

**Comment by Ladicek** [comment]
I actually wanted to take a look at it one of these days. But if you could take a stab at this in Weld, I guess that would be helpful as well, because a lot of the code in ArC is copied (and possibly adapted) from there.

**Comment by manovotn** [comment]
> I actually wanted to take a look at it one of these days. But if you could take a stab at this in Weld, I guess that would be helpful as well, because a lot of the code in ArC is copied (and possibly adapted) from there.

So this is a problem in Weld as well? I might have forgotten that over the break :)
I'll take a look, thanks!

**Comment by manovotn** [comment]
Just to keep a note on it here - I've been doing some deep dives into Weld assignability system and came with a hack that would make the scenario presented here pass.
The WIP draft can be seen at https://github.com/weld/core/pull/2826

**Comment by Ladicek** [comment]
This is now updated with the fix from Weld (as well as an additional fix to runtime representation of bean types in presence of recursive generic types). I'll let CI run in my fork before undrafting.

**Comment by Ladicek** [comment]
Rebased, marked as ready, and updated the PR summary/description.

**Review by manovotn — APPROVED** [review]

**Comment by mkouba** [comment]
I don't think that we'd like to backport this, or?

**Comment by Ladicek** [comment]
This is such a corner case I don't think anyone is waiting for fixes in previous releases, so I agree.

File: independent-projects/arc/tests/src/test/java/io/quarkus/arc/test/producer/generic/RecursiveGenericInvalidTest.java [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+
+public class RecursiveGenericInvalidTest {
+    @RegisterExtension
+    public ArcTestContainer container = ArcTestContainer.builder()
+            .beanClasses(Producer.class, Target.class)
+            .shouldFail()
+            .build();
+
+    @Test
+    public void test() {
```
Comment (mkouba) [inline independent-projects/arc/tests/src/test/java/io/quarkus/arc/test/producer/generic/RecursiveGenericInvalidTest.java:24]: It's a good practice to assert the `container.getFailure()` in the test method :-)

**Review by mkouba — APPROVED** [review]
Looks good otherwise.

File: independent-projects/arc/tests/src/test/java/io/quarkus/arc/test/producer/generic/RecursiveGenericInvalidTest.java (hunk 1 above)
Comment (Ladicek) [reply independent-projects/arc/tests/src/test/java/io/quarkus/arc/test/producer/generic/RecursiveGenericInvalidTest.java:24]: Ah, I don't remember seeing that anywhere, but in hindsight, that's obvious! I'll add a fix.

Comment (Ladicek) [reply independent-projects/arc/tests/src/test/java/io/quarkus/arc/test/producer/generic/RecursiveGenericInvalidTest.java:27]: Done.

**Comment by Ladicek** [comment]
This thing keeps failing in CI here, but passes just fine in my fork: https://github.com/Ladicek/quarkus/actions/runs/3937566221 :shrug:

**Comment by gsmet** [comment]
FWIW, this is not a test that usually fails, it's the first time I see it failing.

**Comment by xstefank** [comment]
@Ladicek no, this shouldn't be failing.

**Comment by Ladicek** [comment]
Gotcha, thanks! I'll continue looking.

**Comment by gsmet** [comment]
Apparently it's all green now, cool!
