### PR TITLE
When disabling name and version for label selected in k8s, don't remove from labels

### LINKED ISSUE #30100: Setting `add-version-to-label-selectors: false` removes the app.kubernetes.io/version label
### Describe the bug

It seems that setting `add-version-to-label-selectors: false` completely removes the version label.

### Expected behavior

The version should not be used in the selector but still be in the labels.

### Actual behavior

Version is not in the selector but it has been removed from the labels as well.

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

17

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2..15.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
The version label should remain, only the labels in the selectors should be removed

Fixes: #30100

### CODE REVIEW

**Review by Sgitario — APPROVED** [review]

File: extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/KubernetesCommonHelper.java [hunk 1]
```diff
@@ -208,13 +207,11 @@ private static Collection<DecoratorBuildItem> createLabelDecorators(Optional<Pro
         });
 
         if (!config.isAddVersionToLabelSelectors()) {
-            result.add(new DecoratorBuildItem(target, new RemoveLabelDecorator(name, Labels.VERSION)));
             result.add(new DecoratorBuildItem(target, new RemoveFromSelectorDecorator(name, Labels.VERSION)));
             result.add(new DecoratorBuildItem(target, new RemoveFromMatchingLabelsDecorator(name, Labels.VERSION)));
         }
 
         if (!config.isAddNameToLabelSelectors()) {
-            result.add(new DecoratorBuildItem(target, new RemoveLabelDecorator(name, Labels.NAME)));
```
Comment (gsmet) [inline extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/KubernetesCommonHelper.java:217]: @geoand (working on the 2.13 backports with @rsvoboda) we saw that you are doing the same fix for the name but we don't see it mentioned anywhere. You positive it needs fixing too? If so could you adjust the title of the PR so that the change is properly documented in the changelog?

Thanks!

Comment (geoand) [reply extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/KubernetesCommonHelper.java:217]: I am yeah, it's the same exact logic

Comment (geoand) [reply extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/KubernetesCommonHelper.java:217]: PR title updated accordingly

Comment (gsmet) [reply extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/KubernetesCommonHelper.java:217]: We tried to backport it to 2.13 but this method doesn't exist at all (and I don't see something similar in this class). So either we should backport the previous fix that introduced this method or we can skip it.

I will let you and @Sgitario decide what to do with it. Please ping me loudly on Zulip if an action on my side is needed.

Comment (Sgitario) [reply extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/KubernetesCommonHelper.java:217]: I don't think that disabling the selectors is a super important feature that we should backport to 2.13, on the other hand, the changes are not very complex. 
I would say to not backport the feature and hence these changes.

**Comment by rsvoboda** [comment]
@gsmet drop 2.13 backport label too?
