### PR TITLE
Properly handle http.root-path in webjars-locator

### LINKED ISSUE #22558: webjars-locator does not work with quarkus.http.root-path set
### Describe the bug

The `quarkus-webjars-locator` extension only works properly if `quarkus.http.root-path` is equal to `/`.

### Expected behavior

Webjar content should be accessible as described in the [HTTP reference][1], regardless of the value of `quarkus.http.root-path`.

With a webjar dependency like this one:

```xml
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-webjars-locator</artifactId>
    </dependency>
    <dependency>
      <groupId>org.webjars</groupId>
      <artifactId>jquery-ui</artifactId>
      <version>1.13.0</version>
    </dependency>
```

And an `application.properties` of:

```properties
quarkus.http.root-path=/app
```

Both of these paths should return `HTTP 200 OK`:
1. `GET /app/webjars/jquery-ui/1.13.0/jquery-ui.min.js`
2. `GET /app/webjars/jquery-ui/jquery-ui.min.js`

[1]: https://quarkus.io/guides/http-reference#webjar-locator-support

### Actual behavior

Trying to access the path without a version (`GET /app/webjars/jquery-ui/jquery-ui.min.js`)  results in a `HTTP 404 Not found`.

### How to Reproduce?

Reproducer: https://github.com/eliasnorrby/quarkus-webjars-locator-bug-reproduction

Follow the steps in the README to reproduce.

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

openjdk version "11.0.13" 2021-10-19 OpenJDK Runtime Environment (build 11.0.13+8) OpenJDK 64-Bit Server VM (build 11.0.13+8, mixed mode)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.6.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by eliasnorrby**
closes: #22558

## Cause

It seems to me that `RouteBuildItem.builder().route()` will set up a route relative to the configured HTTP root path.

The current implementation includes the root path prefix in `webjarRootPath` used in the `.route()` call.

```java
routes.produce(
        RouteBuildItem.builder().route(webjarRootPath + "*")
                .handler(recorder.getHandler(webjarRootPath, webjarNameToVersionMap)).build());
```

When `quarkus.http.root-path=/`, then `webjarRootPath=/webjars/`. The handler will be set up for calls to `/webjars/*`, and calls to e.g. `/webjars/jquery-ui/jquery-ui.min.js` will be mapped to `/webjars/jquery-ui/1.13.0/jquery-ui.min.js`.

When `quarkus.http.root-path=/app`, then `webjarRootPath=/app/webjars/`. The handler will be set up for calls to `/app/app/webjars/*` (note the extra `/app`), not `/app/webjars/*`. Calls to `/app/webjars/jquery-ui/jquery-ui.min.js` will not be properly mapped to `/app/webjars/jquery-ui/1.13.0/jquery-ui.min.js`. I found this out by injecting some log statements in `WebjarLocatorRecorder.getHandler`.

## Solution

Do not include the root path prefix when setting up the route handler.

```java
routes.produce(
        RouteBuildItem.builder().route("/webjars/*")
                .handler(recorder.getHandler(webjarRootPath, webjarNameToVersionMap)).build());
```

I found this hard to verify with tests since RESTEasy will abstract away `quarkus.http.root-path`. I verified that, after this change, the handler is set up properly in both cases (`quarkus.http.root-path=/` and `quarkus.http.root-path=/app`) by building `webjars-locator` locally (`./mvnw install -f extensions/webjars-locator`) and using it in [the issue reproduction repo][1]: 

```xml
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-webjars-locator</artifactId>
      <version>999-SNAPSHOT</version>
    </dependency>
```

```bash
❯ ./mvnw quarkus:dev
❯ ./curl_webjar.sh
curl with version
200
curl without version
200

❯ ./mvnw quarkus:dev -Dquarkus.http.root-path=/app
❯ ./curl_webjar.sh /app
curl with version
200
curl without version
200
```

[1]: https://github.com/eliasnorrby/quarkus-webjars-locator-bug-reproduction

### CODE REVIEW

**Comment by geoand** [comment]
Thanks for this!

Maybe you can add a test similar to https://github.com/quarkusio/quarkus/blob/main/extensions/webjars-locator/deployment/src/test/java/io/quarkus/webjar/locator/test/WebJarLocatorDevModeTest.java#L13 ?

**Comment by eliasnorrby** [comment]
@geoand I added a test based on the [WebJarLocatorTest](https://github.com/eliasnorrby/quarkus/blob/bugfix/webjars-locator-with-root-path/extensions/webjars-locator/deployment/src/test/java/io/quarkus/webjar/locator/test/WebJarLocatorTest.java), with [a single addition](https://github.com/eliasnorrby/quarkus/blob/8005d5d8a16c5342a7df344ceb35bef095bdd43a/extensions/webjars-locator/deployment/src/test/java/io/quarkus/webjar/locator/test/WebJarLocatorRootPathTest.java#L23):

```diff
    static QuarkusUnitTest runner = new QuarkusUnitTest()
            .withApplicationRoot((jar) -> jar
                    .addAsResource(new StringAsset("<html>Hello!<html>"), META_INF_RESOURCES + "/index.html")
                    .addAsResource(new StringAsset("Test"), META_INF_RESOURCES + "/some/path/test.txt"))
+           .overrideConfigKey("quarkus.http.root-path", "/app")
            .setForcedDependencies(Arrays.asList(new AppArtifact("org.webjars", "jquery-ui", JQUERY_UI_VERSION),
                    new AppArtifact("org.webjars", "momentjs", MOMENTJS_VERSION)));

```

It fails on `main` but passes on my branch. If there's a more DRY way to do this, let me know!

**Comment by geoand** [comment]
Looks good!

**Review by geoand — APPROVED** [review]

**Comment by gastaldi** [comment]
That's pretty detailed description of the problem and the solution, thanks!

File: extensions/webjars-locator/deployment/src/test/java/io/quarkus/webjar/locator/test/WebJarLocatorRootPathTest.java [hunk 1]
```diff
@@ -0,0 +1,66 @@
...
+
+public class WebJarLocatorRootPathTest extends WebJarLocatorTestSupport {
+    private static final String META_INF_RESOURCES = "META-INF/resources/";
+
+    @RegisterExtension
+    static QuarkusUnitTest runner = new QuarkusUnitTest()
+            .withApplicationRoot((jar) -> jar
+                    .addAsResource(new StringAsset("<html>Hello!<html>"), META_INF_RESOURCES + "/index.html")
+                    .addAsResource(new StringAsset("Test"), META_INF_RESOURCES + "/some/path/test.txt"))
+            .overrideConfigKey("quarkus.http.root-path", "/app")
```
Comment (aloubyansky) [inline extensions/webjars-locator/deployment/src/test/java/io/quarkus/webjar/locator/test/WebJarLocatorRootPathTest.java:23]: If you configure the root as `/app` is it still expected `RestAssured.get("/")` will get the `index.html` content?

Comment (eliasnorrby) [reply extensions/webjars-locator/deployment/src/test/java/io/quarkus/webjar/locator/test/WebJarLocatorRootPathTest.java:23]: My understanding is that, unless we override `RestAssured.basePath` (as [in this case](https://github.com/eliasnorrby/quarkus/blob/8b864470d458c006bf726890b069b01fd5177670/extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/test/java/io/quarkus/resteasy/reactive/server/test/path/RestApplicationPathTestCase.java#L42), for example), `RestAssured.get` will take the configured root path into consideration. So a `RestAssured.get("/")` translates to a `GET /app/`, which is expected to return the `index.html`.

If this was not the case, I would expect all the get requests in the test to result in `404`s as none of them specify the `/app` root path prefix.

Comment (aloubyansky) [reply extensions/webjars-locator/deployment/src/test/java/io/quarkus/webjar/locator/test/WebJarLocatorRootPathTest.java:23]: Thanks, looks like I messed something up in my branch, it fails on this test now.
