### PR TITLE
Qute: ultimate fix for the problem with registering NativeImageResourceBuildItem correctly on Windows

### LINKED ISSUE #40055: Unable to compile qute codestart to native on windows
### Describe the bug

When I try compile resteasy-qute and rest-qute (resteasy-reactive-qute) codestart to native on windows the compilation fail with this error:
```
[1/8] Initializing...                                                                                   (11,5s @ 0,14GB)                                                                                                                                                        Java version: 21.0.2+13-LTS, vendor version: Oracle GraalVM 21.0.2+13.1                                                                                                                                                                                                        Graal compiler: optimization level: 2, target machine: x86-64-v3, PGO: ML-inferred                                                                                                                                                                                             C compiler: cl.exe (microsoft, x64, 19.38.33130)                                                                                                                                                                                                                               Garbage collector: Serial GC (max heap size: 80% of RAM)                                                                                                                                                                                                                       4 user-specific feature(s):                                                                                                                                                                                                                                                    - com.oracle.svm.thirdparty.gson.GsonFeature                                                                                                                                                                                                                                   - io.quarkus.runner.Feature: Auto-generated class by Quarkus from the existing extensions                                                                                                                                                                                      - io.quarkus.runtime.graal.DisableLoggingFeature: Disables INFO logging during the analysis phase                                                                                                                                                                              - org.eclipse.angus.activation.nativeimage.AngusActivationFeature                                                                                                                                                                                                             ------------------------------------------------------------------------------------------------------------------------                                                                                                                                                        3 experimental option(s) unlocked:                                                                                                                                                                                                                                             - '-H:+AllowFoldMethods' (origin(s): command line)                                                                                                                                                                                                                             - '-H:BuildOutputJSONFile' (origin(s): command line)                                                                                                                                                                                                                           - '-H:-UseServiceLoaderFeature' (origin(s): command line)                                                                                                                                                                                                                     ------------------------------------------------------------------------------------------------------------------------                                                                                                                                                       Build resources:                                                                                                                                                                                                                                                                - 12,09GB of memory (75,6% of 16,00GB system memory, determined at start)                                                                                                                                                                                                      - 2 thread(s) (100,0% of 2 available processor(s), determined at start)                                                                                                                                                                                                       [2/8] Performing analysis...  [*]                                                                       (76,8s @ 1,08GB)                                                                                                                                                          11 652 reachable types   (86,9% of   13 416 total)                                                                                                                                                                                                                             16 854 reachable fields  (58,6% of   28 750 total)                                                                                                                                                                                                                             63 411 reachable methods (58,6% of  108 179 total)                                                                                                                                                                                                                              3 693 types,   155 fields, and 3 238 methods registered for reflection                                                                                                                                                                                                             4 native libraries: crypt32, ncrypt, psapi, winhttp                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ------------------------------------------------------------------------------------------------------------------------                                                                                                                                                                              11,3s (12,6% of total time) in 111 GCs | Peak RSS: 1,88GB | CPU load: 1,94                                                                                                                                                                              ------------------------------------------------------------------------------------------------------------------------                                                                                                                                                       Produced artifacts:                                                                                                                                                                                                                                                             C:\Users\jedla\Downloads\code-with-quarkus\target\code-with-quarkus-1.0.0-SNAPSHOT-native-image-source-jar\svm_err_b_20240412T200838.238_pid2728.md (build_info)                                                                                                              ========================================================================================================================                                                                                                                                                       Failed generating 'code-with-quarkus-1.0.0-SNAPSHOT-runner' after 1m 28s.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     The build process encountered an unexpected error:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            com.oracle.svm.core.util.VMError$HostedError: InternalFeature defined by com.oracle.svm.hosted.ResourcesFeature unexpectedly failed with a(n) java.util.regex.PatternSyntaxException                                                                                                   at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:86)                                                                                                                                                                        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.handleFeatureError(FeatureHandler.java:287)                                                                                                                                                            at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:92)                                                                                                                                                                 at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$11(NativeImageGenerator.java:786)                                                                                                                                     at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.AbstractAnalysisEngine.runAnalysis(AbstractAnalysisEngine.java:181)                                                                                                                                              at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:783)                                                                                                                                               at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:592)                                                                                                                                                             at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:550)                                                                                                                                                               at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:539)                                                                                                                                            at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:721)                                                                                                                                                 at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:143)                                                                                                                                                 at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:98)                                                                                                                                           Caused by: java.util.regex.PatternSyntaxException: Unknown character property name {a} near index 11                                                                                                                                                                           templates\page.qute.html                                                                                                                                                                                                                                                                  ^                                                                                                                                                                                                                                                                           at java.base/java.util.regex.Pattern.error(Pattern.java:2204)                                                                                                                                                                                                                  at java.base/java.util.regex.Pattern.family(Pattern.java:3089)                                                                                                                                                                                                                 at java.base/java.util.regex.Pattern.sequence(Pattern.java:2332)                                                                                                                                                                                                               at java.base/java.util.regex.Pattern.expr(Pattern.java:2245)                                                                                                                                                                                                                   at java.base/java.util.regex.Pattern.compile(Pattern.java:1945)                                                                                                                                                                                                                at java.base/java.util.regex.Pattern.<init>(Pattern.java:1576)                                                                                                                                                                                                                 at java.base/java.util.regex.Pattern.compile(Pattern.java:1101)                                                                                                                                                                                                                at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ResourcesFeature.makeResourcePattern(ResourcesFeature.java:364)                                                                                                                                                       at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)                                                                                                                                                                                         at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)                                                                                                                                                                                         at java.base/java.util.concurrent.ConcurrentHashMap$KeySpliterator.forEachRemaining(ConcurrentHashMap.java:3573)                                                                                                                                                               at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)                                                                                                                                                                                             at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)                                                                                                                                                                                      at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)                                                                                                                                                                                             at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)                                                                                                                                                                                  at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)                                                                                                                                                                                            at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)                                                                                                                                                                                            at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)                                                                                                                                                                                             at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ResourcesFeature.compilePatterns(ResourcesFeature.java:357)                                                                                                                                                           at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ResourcesFeature.duringAnalysis(ResourcesFeature.java:335)                                                                                                                                                            at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$10(NativeImageGenerator.java:786)                                                                                                                                     at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:90)                                                                                                                                                                 ... 9 more
```

### Expected behavior

Finish build without any error.

### Actual behavior

```
Caused by: java.util.regex.PatternSyntaxException: Unknown character property name {a} near index 11
templates\page.qute.html
```

### How to Reproduce?

1. Download [https://code.quarkus.io/d?e=resteasy-qute&cn=code.quarkus.io](https://code.quarkus.io/d?e=resteasy-qute&cn=code.quarkus.io)
2. Compile to native by `mvn.cmd install -Dnative`
3. During the stage 2 error appear

### Output of `uname -a` or `ver`

Windows

### Output of `java -version`

_No response_

### Mandrel or GraalVM version (if different from Java)

GraalVM 23.1 JDK 21.0.2+13-LTS-jvmci-23.1-b30

### Quarkus version or git rev

3.8.3+, 3.9.0.CR2+

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache maven 3.8.8

### Additional information

Latest version where this is working are 3.8.2 and 3.9.0.CR1 (just tested if all 3.9 is affected)
Tried it on Windows 10 but this happening also on github runners. Tested it on Linux and build fine.

### PR DESCRIPTION
**Pull request by mkouba**
This pull request should contain the ultimate fix for the problem with registering `NativeImageResourceBuildItem` correctly on Windows.

It also fixes #40055.

There's a zulip topic about the contract of `NativeImageResourceBuildItem`: https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/NativeImageResourceBuildItem.20-.20format.20of.20resource.20params.3F. However, this problem will be probably addressed in a separate PR.

We've also added the `quarkus-qute-integration-test` module into the native Windows CI category. Hopefully, this will improve our ability to detect this kind of problems.

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]

**Comment by gastaldi** [comment]
Looks like this needs to be backported too?

**Comment by mkouba** [comment]
> Looks like this needs to be backported too?

Yes, if possible...

File: extensions/qute/deployment/src/main/java/io/quarkus/qute/deployment/QuteProcessor.java [hunk 1]
```diff
@@ -3397,85 +3355,52 @@ public static String getName(InjectionPointInfo injectionPoint) {
...
                 originalPath);
         boolean restartNeeded = true;
         if (config.devMode.noRestartTemplates.isPresent()) {
-            restartNeeded = !config.devMode.noRestartTemplates.get().matcher(osAgnosticResourcePath).matches();
+            restartNeeded = !config.devMode.noRestartTemplates.get().matcher(resourcePath).matches();
         }
-        watchedPaths.produce(new HotDeploymentWatchedFileBuildItem(osAgnosticResourcePath, restartNeeded));
-        nativeImageResources.produce(new NativeImageResourceBuildItem(osSpecificResourcePath));
+        watchedPaths.produce(new HotDeploymentWatchedFileBuildItem(resourcePath, restartNeeded));
+        nativeImageResources.produce(new NativeImageResourceBuildItem(resourcePath));
```
Comment (gsmet) [inline extensions/qute/deployment/src/main/java/io/quarkus/qute/deployment/QuteProcessor.java:3380]: It's good enough, probably but we still have the issue that this is gonna be interpreted like a regexp, right? So `.` will mean any char for instance?

**Review by gsmet — APPROVED** [review]
I think we can merge but I wouldn't qualify it as `ultimate` as I think the issue with `NativeImageResourceBuildItem` being brittle is not fixed :)

**Comment by mkouba** [comment]
> I think we can merge but I wouldn't qualify it as `ultimate` as I think the issue with `NativeImageResourceBuildItem` being brittle is not fixed :)

Yes, it's "ultimate" from Qute POV, not from the core POV ;-)

File: extensions/qute/deployment/src/main/java/io/quarkus/qute/deployment/QuteProcessor.java (hunk 1 above)
Comment (mkouba) [reply extensions/qute/deployment/src/main/java/io/quarkus/qute/deployment/QuteProcessor.java:3380]: Yes, but that's another issue that should be addressed in a separate pull request.

**Comment by mzellho** [comment]
@mkouba@ @gastaldi @gsmet : Unfortunately, I have some problems with these additions. I am running on Linux and have some `@CheckedTemplates` in places like `src/main/resources/templates/foo/bar.xml`. When we arrive at `io.quarkus.qute.deployment.QuteProcessor#scanTemplateRootSubtree`, the default `templatePathExclude` now matches `templatePath`, which is `../../classes/templates/foo/bar.xml` at this point. The only Qute-specific configuration I have is `quarkus.qute.suffixes=html,txt,xml`.

I added `quarkus.qute.template-path-exclude="^$"` to work around this issue, but if you didn't already resolve this with https://github.com/quarkusio/quarkus/pull/40067, then maybe you want to look at this one again? Sadly, I don't really have time to contribute here for the next 2 months, sorry!

**Comment by mkouba** [comment]
> @mkouba@ @gastaldi @gsmet : Unfortunately, I have some problems with these additions. I am running on Linux and have some `@CheckedTemplates` in places like `src/main/resources/templates/foo/bar.xml`. When we arrive at `io.quarkus.qute.deployment.QuteProcessor#scanTemplateRootSubtree`, the default `quarkus.qute.template-path-exclude` (`"^\\..*|.*\\/\\..*$"`) now matches `templatePath`, which is `../../classes/templates/foo/bar.xml` at this point. The only Qute-specific configuration I have is `quarkus.qute.suffixes=html,txt,xml`.
> 
> Does #40067 resolve this already? Sadly, I don't really have time to contribute here for the next 2 months, sorry!

In which mode does it happen? Dev/prod? We do have a [test](https://github.com/quarkusio/quarkus/blob/main/extensions/qute/deployment/src/test/java/io/quarkus/qute/deployment/exclude/TemplatePathExcludeTest.java) for the default value of `quarkus.qute.template-path-exclude`. I've tried to add a specific test for a template located in `templates/bar/_foo.txt` but it seems to work.

CC @aloubyansky

**Comment by mzellho** [comment]
@mkouba : super interestingly, it does NOT occur in `dev`, but only during my `test`s.

By the way: the `@CheckedTemplate`s are annotated like this:
```
@CheckedTemplate(basePath = "foo",
                 defaultName = CheckedTemplate.HYPHENATED_ELEMENT_NAME)
public class ManagerTemplates {
    public static native TemplateInstance bar(/*arguments omitted*/)
}
```

But I have also tried to set basePath to "/foo", "templates/foo", "/templates/foo", but all of them produce a `No template matching the path foo/bar could be found for: org.acme.FooTemplates.bar`

**Comment by mkouba** [comment]
> super interestingly, it does NOT occur in `dev`, but only during my `test`s.

@mzellho Do you run the tests from the command line or IDE?

> By the way: the @CheckedTemplates are annotated like this:

`CheckedTemplate.HYPHENATED_ELEMENT_NAME` has no effect here - it's only used if the method name contains upper-case letters.

**Comment by mzellho** [comment]
@mkouba: Well, in reality my template / static method is not called `bar`, but contains camelCase, e.g. "confirmationReport" :-)

Both, I had it failing on our Build Server when running a `mvn package`, but also when running it in IntelliJ via right click on `test`/`java` and so on.

**Comment by mkouba** [comment]
> Well, in reality my template / static method is not called `bar`, but contains camelCase, e.g. "confirmationReport" :-)

Sure ;-)

> Both, I had it failing on our Build Server when running a mvn package, but also when running it in IntelliJ via right click on test/java and so on.

Ok, your build server is also Linux? Does it fail if you run the tests locally with `mvn clean test`?

**Comment by mzellho** [comment]
Yes, both are on Linux and it also fails locally with a `mvn clean test`

**Comment by mkouba** [comment]
> Yes, both are on Linux and it also fails locally with a `mvn clean test`

Uf, I wasn't able to reproduce the problem locally with the [qute-quickstart](https://github.com/quarkusio/quarkus-quickstarts/tree/main/qute-quickstart) which also contains `@CheckedTemplate` and the template is located in `templates/ItemResource/items.html`.

**Comment by mzellho** [comment]
`3.9.5`, `3.9.4` worked nicely. I'll try to reproduce my setup with that repo see if I can reproduce the issue.

**Comment by mzellho** [comment]
So, reproduced, but I don't think it would affect too many people, and likely it also doesn't need to be fixed urgently.

The scenario is that there is a `@CheckedTemplate` at `src/main/resources/templates/foo/barBaz.xml` and another file at `src/test/resources/templates/foo/barBaz-test.xml`, that holds the expected value for the assertion inside the test. Until the file within the test resources exists, everything is working nicely, but as soon as the test resource is there, it seems that only files from `src/test/resources/templates` are being looked at and that cannot the actual template cannot be found anymore.

I will also share the reproducer in a moment.

**Comment by mkouba** [comment]
> I will also share the reproducer in a bit / after lunch.

Pls create a new issue and attach the reproducer there. Thanks a lot!

**Comment by mzellho** [comment]
alright, thank you --> https://github.com/quarkusio/quarkus/issues/40366
