### PR TITLE
Use Maven plugin's groupId and version as the base for the target platform groupId and version

### LINKED ISSUE #19250: quarkus-maven-plugin:2.1.0.Final creates project with different platform version
### Describe the bug

quarkus-maven-plugin:2.1.0.Final creates project with `<quarkus.platform.version>2.1.1.Final</quarkus.platform.version>`, which is not expected.
The issue exists even if `-Dquarkus.platform.version=2.1.0.Final` is specified.

Affects only 2.1.0.Final but may transit into 2.1.1.Final when a new release will be out.

### Expected behavior

`quarkus.platform.version` of the generated project is the same as `quarkus-maven-plugin` version

### Actual behavior

The `quarkus.platform.version` is resolved to 2.1.1.Final (the latest Quarkus version at the time)

### How to Reproduce?

```
mvn io.quarkus:quarkus-maven-plugin:2.1.0.Final:create -DprojectGroupId=my-groupId -DprojectArtifactId=app-generated-skeleton -DprojectVersion=1.0.0-SNAPSHOT -DpackageName=org.my.group -DplatformVersion=2.1.0.Final
```
and see in the `/pom.xml` file, the `<quarkus.platform.version>`

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.1.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by aloubyansky**
Fixes #19250, #19558, #19612

In case the `quarkus-maven-plugin` is used to create a project and the registry client is disabled or a configured registry isn't available, fallback to the default platform release, unless the desired platform groupId, artifactId and version were provided by the user. The default platform groupId and version are matching those of the `quarkus-maven-plugin` and the default platform artifactId is `quarkus-bom`.

For example if a registry isn't available

`mvn io.quarkus.platform:quarkus-maven-plugin:999-SNAPSHOT:create` will create a project using `io.quarkus.platform:quarkus-bom:999-SNAPSHOT`.

`mvn io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:create` will create a project using `io.quarkus:quarkus-bom:999-SNAPSHOT`.

A warning would look something like this:
````
[INFO] --- quarkus-maven-plugin:999-SNAPSHOT:create (default-cli) @ standalone-pom ---
[INFO] Refreshing the local extension catalog cache of registry.quarkus.io
Downloading from aliyunmaven: https://maven.aliyun.com/repository/public/io/quarkus/registry/quarkus-registry-descriptor/1.0-SNAPSHOT/maven-metadata.xml
Downloading from aliyunmaven: https://maven.aliyun.com/repository/public/io/quarkus/registry/quarkus-registry-descriptor/1.0-SNAPSHOT/quarkus-registry-descriptor-1.0-SNAPSHOT.json
[WARNING] The extension catalog will be narrowed to the io.quarkus:quarkus-bom:999-SNAPSHOT platform release. To enable the complete Quarkiverse extension catalog along with the latest recommended platform releases, please, make sure the following registries are accissible from your environment: registry.quarkus.io
Set the project groupId [org.acme]:
````

### CODE REVIEW

**Comment by aloubyansky** [comment]
fyi @kshpak

**Review by gsmet — CHANGES_REQUESTED** [review]
Hmmm. I'm not sure we really want this, at least not in the current state of our doc or do we?

`mvn io.quarkus:quarkus-maven-plugin:VERSION:create` is what we use in the docs so nobody will use the new platform.

Isn't the right fix to somehow honor the version provided as a parameter?

**Comment by aloubyansky** [comment]
@maxandersen wdyt?

**Comment by gsmet** [comment]
@aloubyansky why not... but do you agree that means everyone using our doc will not use the new platform or am I missing something? And that even if we update the doc, there are thousands of blog posts around.

**Comment by aloubyansky** [comment]
That will use the version advertised in the docs.

**Comment by gsmet** [comment]
But the `io.quarkus:quarkus-bom` not the `io.quarkus.platform:quarkus-bom`. That's what I'm trying to say :)

**Comment by aloubyansky** [comment]
Right.

**Comment by aloubyansky** [comment]
I guess I should add the corresponding doc changes to this PR.

**Comment by aloubyansky** [comment]
I see our guides still refer to the universe BOM, btw, so - yes, I'll update the docs.

**Comment by aloubyansky** [comment]
I updated the docs in the second commit.

**Comment by maxandersen** [comment]
the update of the docs i understand but why make the connection from what plugin you used to the project you create ? why is that not done using what is in the platform?

**Comment by aloubyansky** [comment]
Basically because it may be confusing, given that you specify the version of the plugin on the command line. While the generated project may include a completely different version of the plugin in the generated POM.

**Comment by aloubyansky** [comment]
The change is based on the fact that the plugin is a part of the platform release. So, specifying the full coordinates of the plugin, you are essentially targeting the corresponding platform release.

**Comment by aloubyansky** [comment]
Although, the problem with this change and the docs being in the core repo is that the docs will be released before the platform, afaiu.

**Comment by maxandersen** [comment]
suggestion - add a flag `-DignoreRegistryRecommendation` to let the maven plugin use its own GAV instead of what regstiry is configured in the config the user has.

**Comment by gsmet** [comment]
Well, just to clarify, I kinda agree with @aloubyansky that calling the Maven plugin with a `2.0` version and ending with a `2.1` project is very weird from a user perspective (even if it has some logic in our registry based world). My concerns were about the documentation.

Also, these changes make sense in the context of the user using the Maven plugin and... we will move to the CLI soon enough anyway, won't we? And this one will default to the registry recommendation.

And just to be extra clear: these changes do not affect code.quarkus.io right? We will still be able to run code.quarkus.io with 2.1 and creating 2.2 projects by default?

**Comment by aloubyansky** [comment]
That's correct @gsmet My point was the plugin is a part of the platform release and is configured per project, while the CLI is a global tool in that sense, re-used for all the user projects.
So when I create a project using a Maven plugin, I am effective saying "Platform release, create me a new project" and I would expect the resulting platform version to match the release the plugin belongs to. That would still involve the registry though to hook in the non-platform extensions compatible with the target platform.

But anyway, because of the docs, I will back off on this one. The issue is that with this change `io.quarkus.platform:quarkus-maven-plugin` and `io.quarkus:quarkus-maven-plugin` will always be creating community-based projects. So RHBQ customers will either have to use the CLI or `com.redhat.quarkus.platform:quarkus-maven-plugin` to create RHBQ-based projects. That could lead to more confusion, although to me personally this change would make sense.

**Comment by maxandersen** [comment]
I understand the inclination to want the version maven forces you to put in be reused but it just breaks the uniformity of letting the registry you point to be the ones that define the defaults.

Thus for that one special case where you want the exact same version then I suggest to add a flag to have the plugin ignore the recommended platform artifact/versions and instead use the plugins own exact coordinates.

**Comment by aloubyansky** [comment]
The current approach makes the coordinated of the plugin that a use would be typing attentively (unfortunately you can't do it otherwise) irrelevant, which is not a good experience. You have to think about which version of the plugin to type anyway. And then, at some point knowing, that there are different plugin `groupId` out there, a user may ask a question whether the groupId specified is significant. Treating everything the user typed as insignificant is leading to bad user experience.

**Comment by aloubyansky** [comment]
The comparison to the CLI isn't a fair one. The CLI is installed as a tool in the environment and is re-used for all the projects in that environment.

With this change the registry isn't completely ignored. It is still used to pull in the compatible non-platform extensions for the project to be created.

**Comment by maxandersen** [comment]
I bet users dont type these things in manually - they copy/paste the mvn plugin line from an article/book/markdown etc. to create a quarkus project. Let them add `-Dingoreregistrydefaults` if they insist.

That the mavne plugin will use registry for additional extensions is great but making the maven plugin not capable of using the registry defaults undermines the value of the registry IMO.

We want users to upgrade and use latest; we want them to use what their configured registry recommends.

**Comment by aloubyansky** [comment]
> That the mavne plugin will use registry for additional extensions is great but making the maven plugin not capable of using the registry defaults undermines the value of the registry IMO.

I'd say it somewhat undermines the usage of the Maven plugin, not the registry. The Maven plugin is also not the primary dev tool that we should be promoting any more. So all the docs should be advertising the CLI examples to copy-paste instead of the Maven plugin anyway.
If you are worried about the legacy examples with the plugin version pre-2.x they are not looking past 2.0.0 release (excluding it). So this change won't affect the legacy examples.

**Comment by aloubyansky** [comment]
I updated the PR to fallback to the default platform coords computed from the plugin's coords if the registry isn't enabled or not available logging a detailed warning about the narrowed to the platform catalog and why it is narrowed down.

File: devtools/maven/src/main/java/io/quarkus/maven/CreateProjectMojo.java [hunk 1]
```diff
@@ -325,79 +326,107 @@ public void execute() throws MojoExecutionException {
...
+            groupId = getPlatformGroupId(mojo, groupId);
+            artifactId = getPlatformArtifactId(artifactId);
+            version = getPlatformVersion(mojo, version);
+            final StringBuilder buf = new StringBuilder();
+            buf.append("The extension catalog will be narrowed to the ").append(groupId).append(":").append(artifactId)
+                    .append(":").append(version).append(" platform release.");
+            buf.append(
+                    " To enable the complete Quarkiverse extension catalog along with the latest recommended platform releases, please, make sure ");
+            if (QuarkusProjectHelper.isRegistryClientEnabled()) {
+                buf.append("the following registries are accissible from your environment: ");
```
Comment (maxandersen) [inline devtools/maven/src/main/java/io/quarkus/maven/CreateProjectMojo.java:343]:
```suggestion
                buf.append("one of the following registries are accissible from your environment: ");
```

I assume it just needs one to be present ?

**Review by maxandersen — APPROVED** [review]
Gist of this I approve - falling back to maven plugins ID's if no other info (i.e. registry) available to calculate the right one.

File: devtools/maven/src/main/java/io/quarkus/maven/CreateProjectMojo.java (hunk 1 above)
Comment (aloubyansky) [reply devtools/maven/src/main/java/io/quarkus/maven/CreateProjectMojo.java:343]: Actually at this point it will fail if at least one isn't available. It would have to be disabled or removed from the config.

Comment (gsmet) [inline devtools/maven/src/main/java/io/quarkus/maven/CreateProjectMojo.java:343]:
```suggestion
                buf.append("the following registries are accessible from your environment: ");
```

File: devtools/maven/src/main/java/io/quarkus/maven/CreateProjectMojo.java [hunk 2]
```diff
@@ -325,79 +326,107 @@ public void execute() throws MojoExecutionException {
...
+                            new ArtifactCoords(getPlatformGroupId(mojo, groupId), getPlatformArtifactId(artifactId), "pom",
+                                    getPlatformVersion(mojo, version))));
         } catch (RegistryResolutionException e) {
             throw new MojoExecutionException("Failed to resolve the extensions catalog", e);
         }
+
+        if (catalog == null) {
+            final StringBuilder buf = new StringBuilder();
+            buf.append(
+                    "The Quarkus registry client failed to resolve the extension catalog. Please make sure the following registries are accissible from your environment: ");
```
Comment (gsmet) [inline devtools/maven/src/main/java/io/quarkus/maven/CreateProjectMojo.java:377]:
```suggestion
                    "The Quarkus registry client failed to resolve the extension catalog. Please make sure the following registries are accessible from your environment: ");
```

**Review by gsmet — CHANGES_REQUESTED** [review]
I spotted two small typos.

Also, I'm still thinking we should update all our guides to use the Platform plugin? For instance here: https://github.com/quarkusio/quarkus/blob/main/docs/src/main/asciidoc/getting-started.adoc#4-bootstrapping-the-project .

**Review by gsmet — APPROVED** [review]
