### PR TITLE
Use `-Prelocations` in `update-extension-dependencies.sh` & filter out `quarkus-amazon-common`

### LINKED ISSUE #22836: Incorrect changes after running update-extension-dependencies.sh
If you:

-  have cloned and built this repository before #21736 was merged
- run `update-extension-dependencies.sh` because, for example, you're adding an extension

Then the output contains references to the modules that were moved out of the repository.

This was found while working on #22810

### PR DESCRIPTION
**Pull request by famod**
Fixes #22836, but filtering of `quarkus-amazon-common` is only a mitigation for `quarkus-amazon-common` still ending up in `quarkus-bom-quarkus-platform-descriptor-*.json` because the generation does not respect the build tree/workspace.

Will create another issue after this is merged.

### CODE REVIEW

File: update-extension-dependencies.sh [hunk 1]
```diff
@@ -49,7 +54,9 @@ echo ''
 # get all "artifact-id" values from the generated json file
 # pipefail is switched off briefly so that a better error can be logged when nothing is found
 set +o pipefail
-ARTIFACT_IDS=$(cd "${PRG_PATH}" && grep '^    "artifact"' devtools/bom-descriptor-json/target/quarkus-bom-quarkus-platform-descriptor-*.json | grep -Eo 'quarkus-[a-z0-9-]+' | sort)
+# note: quarkus-amazon-common was removed from this repo without a relocation
+ARTIFACT_IDS=$(cd "${PRG_PATH}" && grep '^    "artifact"' devtools/bom-descriptor-json/target/quarkus-bom-quarkus-platform-descriptor-*.json \
+    | grep -Eo 'quarkus-[a-z0-9-]+' | grep -v quarkus-amazon-common | sort)
```
Comment (gsmet) [inline update-extension-dependencies.sh:59]: Maybe a stupid idea but should we just exclude all the relocated artifacts here? That might be easier?

Comment (famod) [reply update-extension-dependencies.sh:59]: `-Prelocations` further up already does that trick! It prevents those relocated modules from ending up in the descriptor.
But since we don't have a relocation for `quarkus-amazon-common` and the generation of the descriptor doesn't respect the workspace, we have to exclude that single artifact like this.

Ideally, generation would take the workspace into account and then we'd be good, without any specific filtering.

Comment (famod) [reply update-extension-dependencies.sh:59]: And to answer:
> That might be easier?

No, IMO. The list would be much longer and as long we have a relocation (also for future modules to be moved out), we're good here.

File: update-extension-dependencies.sh [hunk 2]
```diff
@@ -16,14 +16,19 @@ then
...
   then
     echo ''
-    echo 'Building entire project...'
+    echo 'Building entire project with relocations...'
     echo ''
-    mvn -q -e -Dquickly -T0.8C -f "${PRG_PATH}" $*
+    mvn -q -e -Dquickly -Dno-test-modules -Prelocations -T0.8C -f "${PRG_PATH}" $*
+  else
+    echo ''
+    echo 'Aborted!'
```
Comment (famod) [inline update-extension-dependencies.sh:29]: Btw, the idea behind kinda forcing the build is that I don't expect anyone to have built with `-Prelocations` before calling this script.

File: update-extension-dependencies.sh (hunk 1 above)
Comment (gsmet) [reply update-extension-dependencies.sh:59]: well, the list would be longer but you wouldn't have to enforce the build :).

Anyway, I'm good with this.

**Review by gsmet — APPROVED** [review]

**Comment by famod** [comment]
This is mergable once the inititial jdk11 build was ok.

File: update-extension-dependencies.sh (hunk 1 above)
Comment (famod) [reply update-extension-dependencies.sh:59]: > you wouldn't have to enforce the build

That's true! Still, I prefer less stuff in the script (which is only a band aid after all).

**Comment by famod** [comment]
PS: I deliberately merged before the JDK jobs finished as those won't be affected by this change aynway.
