### PR TITLE
Reflection-free deserializers - Better handle basic types

### LINKED ISSUE #47478: VerifyError when using Float in Model deserialized by Jackson
### Describe the bug

If I want to deserialize a model that contains a float, a `VerifyError` occurs during deserialization because the deserializer which is generated during the build uses a `Double` instead of a `Float`. 

The error only occurs if reflection free serializers are enabled.

```
2025-04-22 12:14:59,534 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /v1/products failed, error id: 94f8448d-b4e0-4258-9bac-f7dd12ef09c4-1: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    io/i15s/quarkus/Product$quarkusjacksondeserializer.deserialize(Lcom/fasterxml/jackson/core/JsonParser;Lcom/fasterxml/jackson/databind/DeserializationContext;)Ljava/lang/Object; @243: invokevirtual
  Reason:
    Type 'java/lang/Double' (current frame, stack[1]) is not assignable to 'java/lang/Float'
  Current Frame:
    bci: @243
    flags: { }
    locals: { 'io/i15s/quarkus/Product$quarkusjacksondeserializer', 'com/fasterxml/jackson/core/JsonParser', 'com/fasterxml/jackson/databind/DeserializationContext', 'com/fasterxml/jackson/databind/JsonNode', 'java/util/Iterator', 'java/util/Map$Entry', 'java/lang/Object', integer, 'com/fasterxml/jackson/databind/JsonNode', 'io/i15s/quarkus/Product', top, double, double_2nd }
    stack: { 'io/i15s/quarkus/Product', 'java/lang/Double' }
  Bytecode:
    0000000: 2bb6 0017 2bb6 001d c000 1f4e bb00 0859
    0000010: b700 213a 092d b600 253a 0419 04b9 002b
    0000020: 0100 9a00 09a7 0108 0000 bf19 04b9 002f
    0000030: 0100 c000 313a 0519 05b9 0034 0100 c000
    0000040: 1f3a 0819 08b6 0037 9a00 e219 05b9 003a
    0000050: 0100 3a06 1906 b600 4036 0715 07ab 0000
    0000060: 0000 00ca 0000 0004 c42b cf84 0000 0051
    0000070: 0033 7a8b 0000 002b 0035 f4d4 0000 0064
    0000080: 065f b149 0000 003e 1242 1906 b600 469a
    0000090: 0006 a700 06a7 003f a700 8f12 4819 06b6
    00000a0: 0046 9a00 06a7 0006 a700 3da7 007c 124a
    00000b0: 1906 b600 469a 0006 a700 06a7 003e a700
    00000c0: 6912 4c19 06b6 0046 9a00 06a7 0006 a700
    00000d0: 42a7 0056 1908 b600 503a 0a19 0919 0ab6
    00000e0: 0054 a700 4519 08b6 0058 390b 1909 180b
    00000f0: b800 5eb6 0062 a700 312c 1908 1264 b600
    0000100: 6a3a 0d19 0919 0dc0 0064 b600 6ea7 001a
    0000110: 2c19 0812 64b6 006a 3a0e 1909 190e c000
    0000120: 64b6 0071 a700 03a7 0003 a7fe f119 09b0
    0000130:                                        
  Stackmap Table:
    full_frame(@27,{Object[#2],Object[#19],Object[#102],Object[#31],Object[#39],Top,Top,Top,Top,Object[#8]},{})
    full_frame(@40,{},{Object[#115]})
    full_frame(@43,{Object[#2],Object[#19],Object[#102],Object[#31],Object[#39],Top,Top,Top,Top,Object[#8]},{})
    full_frame(@136,{Object[#2],Object[#19],Object[#102],Object[#31],Object[#39],Object[#49],Object[#60],Integer,Object[#31],Object[#8]},{})
    same_frame(@149)
    same_frame(@152)
    same_frame(@155)
    same_frame(@168)
    same_frame(@171)
    same_frame(@174)
    same_frame(@187)
    same_frame(@190)
    same_frame(@193)
    same_frame(@206)
    same_frame(@209)
    same_frame(@212)
    same_frame(@229)
    same_frame(@249)
    same_frame(@272)
    same_frame(@295)
    full_frame(@298,{Object[#2],Object[#19],Object[#102],Object[#31],Object[#39],Object[#49],Top,Top,Object[#31],Object[#8]},{})
    full_frame(@301,{Object[#2],Object[#19],Object[#102],Object[#31],Object[#39],Top,Top,Top,Top,Object[#8]},{})

	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3549)
	at java.base/java.lang.Class.getConstructor0(Class.java:3754)
	at java.base/java.lang.Class.getConstructor(Class.java:2442)
	at io.quarkus.resteasy.reactive.jackson.runtime.serialisers.GeneratedSerializersRegister$MappingModuleHolder.createMappingModule(GeneratedSerializersRegister.java:55)
	at io.quarkus.resteasy.reactive.jackson.runtime.serialisers.GeneratedSerializersRegister$MappingModuleHolder.<clinit>(GeneratedSerializersRegister.java:32)
	at io.quarkus.resteasy.reactive.jackson.runtime.serialisers.GeneratedSerializersRegister.customize(GeneratedSerializersRegister.java:28)
	at io.quarkus.jackson.runtime.ObjectMapperProducer.objectMapper(ObjectMapperProducer.java:26)
	at io.quarkus.jackson.runtime.ObjectMapperProducer_ProducerMethod_objectMapper_KgqnG0Hv0d6QYgKd-v-HRXlW39Y_Bean.doCreate(Unknown Source)
	at io.quarkus.jackson.runtime.ObjectMapperProducer_ProducerMethod_objectMapper_KgqnG0Hv0d6QYgKd-v-HRXlW39Y_Bean.create(Unknown Source)
	at io.quarkus.jackson.runtime.ObjectMapperProducer_ProducerMethod_objectMapper_KgqnG0Hv0d6QYgKd-v-HRXlW39Y_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:119)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:38)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:32)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.ComputingCacheContextInstances.computeIfAbsent(ComputingCacheContextInstances.java:19)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:35)
	at io.quarkus.jackson.runtime.ObjectMapperProducer_ProducerMethod_objectMapper_KgqnG0Hv0d6QYgKd-v-HRXlW39Y_Bean.get(Unknown Source)
	at io.quarkus.jackson.runtime.ObjectMapperProducer_ProducerMethod_objectMapper_KgqnG0Hv0d6QYgKd-v-HRXlW39Y_Bean.get(Unknown Source)
	at io.quarkus.arc.impl.InstanceImpl.getBeanInstance(InstanceImpl.java:325)
	at io.quarkus.arc.impl.InstanceImpl.getInternal(InstanceImpl.java:309)
	at io.quarkus.arc.impl.InstanceImpl.get(InstanceImpl.java:190)
	at io.quarkus.resteasy.reactive.jackson.runtime.serialisers.AbstractServerJacksonMessageBodyReader$1.get(AbstractServerJacksonMessageBodyReader.java:35)
	at io.quarkus.resteasy.reactive.jackson.runtime.serialisers.AbstractServerJacksonMessageBodyReader$1.get(AbstractServerJacksonMessageBodyReader.java:32)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:32)
	at io.quarkus.resteasy.reactive.jackson.runtime.serialisers.AbstractServerJacksonMessageBodyReader.getEffectiveReader(AbstractServerJacksonMessageBodyReader.java:48)
	at io.quarkus.resteasy.reactive.jackson.runtime.serialisers.ServerJacksonMessageBodyReader.doReadFrom(ServerJacksonMessageBodyReader.java:91)
	at io.quarkus.resteasy.reactive.jackson.runtime.serialisers.ServerJacksonMessageBodyReader.readFrom(ServerJacksonMessageBodyReader.java:44)
	at io.quarkus.resteasy.reactive.jackson.runtime.serialisers.ServerJacksonMessageBodyReader.readFrom(ServerJacksonMessageBodyReader.java:83)
	at io.quarkus.resteasy.reactive.jackson.runtime.serialisers.ServerJacksonMessageBodyReader_ClientProxy.readFrom(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.RequestDeserializeHandler.readFrom(RequestDeserializeHandler.java:126)
	at org.jboss.resteasy.reactive.server.handlers.RequestDeserializeHandler.handle(RequestDeserializeHandler.java:84)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:135)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$15.runWith(VertxCoreRecorder.java:638)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)
	at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

### How to Reproduce?

I've created a small reproducer project.  https://github.com/andlinger/quarkus-reproducer/tree/quarkus-47478
In principle, however, a normal Java POJO with a Float member is sufficient and the reflection free serializers must be activated.

```properties file=application.properties
quarkus.rest.jackson.optimization.enable-reflection-free-serializers=true
```

```java
public class Product {

    @NotBlank(message = "Name must not be blank")
    private String name;
    private Float price;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Float getPrice() {
        return price;
    }

    public void setPrice(Float price) {
        this.price = price;
    }
}
```

### Quarkus version or git rev

3.21.3

### PR DESCRIPTION
**Pull request by gsmet**
Fixes #47478

### CODE REVIEW

File: extensions/resteasy-reactive/rest-jackson/deployment/src/main/java/io/quarkus/resteasy/reactive/jackson/deployment/processor/JacksonSerializationUtils.java [hunk 1]
```diff
@@ -0,0 +1,65 @@
...
+    static boolean isBoxedPrimitive(Type type) {
+        return isBoxedPrimitive(type.name().toString());
+    }
+
+    static boolean isBoxedPrimitive(String typeName) {
+        return "java.lang.Character".equals(typeName) || "java.lang.Short".equals(typeName)
+                || "java.lang.Integer".equals(typeName) || "java.lang.Long".equals(typeName)
+                || "java.lang.Float".equals(typeName) || "java.lang.Double".equals(typeName)
+                || "java.lang.Boolean".equals(typeName);
+    }
```
Comment (gsmet) [inline extensions/resteasy-reactive/rest-jackson/deployment/src/main/java/io/quarkus/resteasy/reactive/jackson/deployment/processor/JacksonSerializationUtils.java:32]: @Ladicek I was wondering if we should have a util in Jandex for this. I couldn't find one but maybe there is one?

File: extensions/resteasy-reactive/rest-jackson/deployment/src/main/java/io/quarkus/resteasy/reactive/jackson/deployment/processor/JacksonSerializationUtils.java [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+            case "boolean" -> bytecodeCreator.load(DEFAULT_BOOLEAN);
+            case "char" -> bytecodeCreator.load(DEFAULT_CHAR);
+            case "double" -> bytecodeCreator.load(DEFAULT_DOUBLE);
+            case "float" -> bytecodeCreator.load(DEFAULT_FLOAT);
+            case "int" -> bytecodeCreator.load(DEFAULT_INT);
+            case "long" -> bytecodeCreator.load(DEFAULT_LONG);
+            case "short" -> bytecodeCreator.load(DEFAULT_SHORT);
+            default -> throw new IllegalStateException("Type " + type + " should be handled by the switch");
+        };
+    }
```
Comment (gsmet) [inline extensions/resteasy-reactive/rest-jackson/deployment/src/main/java/io/quarkus/resteasy/reactive/jackson/deployment/processor/JacksonSerializationUtils.java:64]: @Ladicek do you see a better way to handle that? I need to assign a value to the `ResultHandle`, including for primitive types and I ended up with this but I was wondering if there was a better way to handle that.

**Review by mariofusco — APPROVED** [review]
Great job, thank you!

**Review by geoand — APPROVED** [review]

File: extensions/resteasy-reactive/rest-jackson/deployment/src/main/java/io/quarkus/resteasy/reactive/jackson/deployment/processor/JacksonSerializationUtils.java (hunk 1 above)
Comment (geoand) [reply extensions/resteasy-reactive/rest-jackson/deployment/src/main/java/io/quarkus/resteasy/reactive/jackson/deployment/processor/JacksonSerializationUtils.java:32]: 👍🏽 

That could probably be used in a lot of places.

File: extensions/resteasy-reactive/rest-jackson/deployment/src/main/java/io/quarkus/resteasy/reactive/jackson/deployment/processor/JacksonSerializationUtils.java (hunk 2 above)
Comment (Ladicek) [reply extensions/resteasy-reactive/rest-jackson/deployment/src/main/java/io/quarkus/resteasy/reactive/jackson/deployment/processor/JacksonSerializationUtils.java:64]: I don't think we have a method to load a default value based on given type. What you have is close to the best. (I'd personally avoid the static fields and just pass `(byte) 0`, `false`, `'\0'`, `0.0`, `0.0F`, `0`, `0L`, `(short) 0`, but there's almost zero difference.)

(I actually think we don't have that in Gizmo 2 either. I'll make sure we add it, because it makes sense.)

Comment (gsmet) [reply extensions/resteasy-reactive/rest-jackson/deployment/src/main/java/io/quarkus/resteasy/reactive/jackson/deployment/processor/JacksonSerializationUtils.java:64]: @Ladicek yes, Gizmo 2 is exactly where I expected this to go. I thought it was useful input from real world usage.
