### PR TITLE
Fixes devmode for multi module projects using 'revision' property as versions

### LINKED ISSUE #8832: Dev mode fails when using "Maven CI Friendly Versions" and Quarkus version override via -D
**Describe the bug**
(Warning: This is a rather strange edge-case.)

When using [Maven CI Friendly Versions](https://maven.apache.org/maven-ci-friendly.html) (e.g. `<version>${revision}</version>`), dev mode seems run into an inconsistent state when the Quarkus version is overridden via `-D...` (e.g. root pom defines 1.3.2.Final and you want to test 1.4.0.Final or 1.4.1.Final) and a submodule `dist` is "selected" via `mvn -f dist ...` (or via `cd dist`).

In this case, if the module contains a simple REST controller (e.g. `HelloResource`) with an injection of another simple bean (which resides in the same package, e.g. `AnotherHelloBean`), dev mode will fail with `AmbiguousResolutionException` because it finds the latter twice:
```
Caused by: javax.enterprise.inject.spi.DeploymentException: Found 2 deployment problems:
[1] Ambiguous dependencies for type com.github.famod.modmono_quarkus.dist.AnotherHelloBean and qualifiers [@Default]
        - java member: com.github.famod.modmono_quarkus.dist.HelloResource#bean2
        - declared on CLASS bean [types=[com.github.famod.modmono_quarkus.dist.HelloResource, java.lang.Object], qualifiers=[@Default, @Any], target=com.github.famod.modmono_quarkus.dist.HelloResource]
        - available beans:
                - CLASS bean [types=[com.github.famod.modmono_quarkus.dist.AnotherHelloBean, java.lang.Object], qualifiers=[@Default, @Any], target=com.github.famod.modmono_quarkus.dist.AnotherHelloBean]
                - CLASS bean [types=[com.github.famod.modmono_quarkus.dist.AnotherHelloBean, java.lang.Object], qualifiers=[@Default, @Any], target=com.github.famod.modmono_quarkus.dist.AnotherHelloBean]
```
This does _not_ happen when 1.4.1.Final is set in root pom.

**Expected behavior**
There should be no difference between setting the version in root pom.xml or via `-D...`.

**Actual behavior**
`-D...` causes a bean class in the same module being found twice preventing dev mode from starting properly.

**To Reproduce**
1. Clone https://github.com/famod/modmono-quarkus.git
2. Switch to branch `quarkus-8832-ci-friendly-quarkus-update`
3. Verify that dev mode works with the initial version 1.3.2.Final:
    ```
    mvn clean install -DskipTests && mvn quarkus:dev -f dist
    ```
4. Rebuild project and restart dev mode with version 1.4.1.Final (should fail):
    ```
    mvn clean install -DskipTests -Dquarkus.version=1.4.1.Final && mvn quarkus:dev -f dist -Dquarkus.version=1.4.1.Final
    ```
5. (optional) Set `1.4.1.Final` in pom.xml, rebuild and start dev mode (should be ok)

**Configuration**
n/a

**Screenshots**
n/a

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:
    ```MINGW64_NT-10.0-18363 W4DEUMSY9003463 3.0.7-338.x86_64 2019-11-21 23:07 UTC x86_64 Msys```
 - Output of `java -version`:
    ```
    openjdk version "11.0.6" 2020-01-14
    OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
    OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)
    ```
 - GraalVM version (if different from Java): n/a
 - Quarkus version or git rev: `1.4.1.Final`
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): `Apache Maven 3.6.3`

**Additional context**
This problem totally led my astray while trying to test #8794. Before creating this issue I had a detailed chat on Zulip with @aloubyansky.
My guess is that Quarkus does not consider system properties when handling the Maven poms to support "Maven CI Friendly Versions".

Btw, the respective bean is even found _three_ times when using `mvn -f ./dist ...` (notice the leading dot). I guess this has something to do with a bug in 1.3.2 (and 1.3.1) where this pattern causes the bean to be found _two_ times (even _without_ "Maven CI Friendly Versions"). That bug is _not_ present in 1.4.0+ anymore.

### LINKED ISSUE #8899: Maven regression in 1.4.1.Final vs 1.3.2.Final - ${revision} and custom repository defined in settings.xml
**Describe the bug**
In Quarkus 1.4.1.Final, test dependencies resolved during Quarkus test execution are always retrieved from "central", ignoring custom repository, if ${revision} placeholder is used for version as defined [in Maven documentation](https://maven.apache.org/maven-ci-friendly.html) and a custom repository is defined in `settings.xml` as defined [in Maven documentation](http://maven.apache.org/settings.html#repositories)

Note that this bug does not occur if the custom repository is defined in `pom.xml`. However, ignoring repositories defined in `settings.xml` is an issue and should be resolved. Additionally, it is not possible to configure credentials in pom.xml, so any private repository that requires authentication will not function even with this workaround.

**Expected behavior**
All dependencies, including those resolved by Quarkus test runner, should be resolved using repositories defined in standard Maven configuration.

**Actual behavior**
Dependencies resolved during Quarkus test execution ignore `settings.xml` and instead all pull from the default repository of "central".

**To Reproduce**
Full reproduction details and test case are located at [https://github.com/jeffhubLR/quarkus-1.4.1-maven-regression](https://github.com/jeffhubLR/quarkus-1.4.1-maven-regression)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin xxxxx 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
 - Output of `java -version`: openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)
 - GraalVM version (if different from Java): Not needed for replication
 - Quarkus version or git rev: Quarkus 1.4.1.Final and Quarkus 1.3.2.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Regression occurs regardless of using mvnw or direct mvn.

`./mvnw --version`:
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /Users/jeff.hubbach/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3
Java version: 11.0.6, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.4", arch: "x86_64", family: "mac"

`mvn --version`:
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/Cellar/maven/3.6.3_1/libexec
Java version: 11.0.6, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.4", arch: "x86_64", family: "mac"

**Additional context**
Sections copied from [demonstration repository](https://github.com/jeffhubLR/quarkus-1.4.1-maven-regression) README.md:

## Background

1. Maven `${revision}`

   Since 3.5.0-beta-1, maven has supported using a ${revision} placeholder for the version in pom files.

   https://maven.apache.org/maven-ci-friendly.html

   This is often used in CI systems to be able to inject version at build time via `mvn -Drevision=1.2.3 package`

2. Companies frequently require all dependencies to be pulled through an internal Maven repository that also proxies upstream. One easy way to accomplish this is by providing a `settings.xml` file that specifies that repository. For the purpose of this demonstration, we just override the name but leave the repository as Maven Central.

## Expectation

All dependencies should be retrieved from "get-all-from-here" repository. If at any point we see dependencies pulled from "central", that proves our Maven configuration is not being honored.

## Actual Result

On Quarkus 1.4.1.Final with a custom repository defined and <version> replaced with ${revision}, dependencies downloaded during Quarkus test execution are pulled from "central" rather than the expected configured repository.

### PR DESCRIPTION
**Pull request by aloubyansky**
Fixes #8832 
Fixes #8899

### CODE REVIEW

**Comment by jeffhubLR** [comment]
This does _not_ resolve #8899

File: devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java [hunk 1]
```diff
@@ -642,13 +643,47 @@ void prepare() throws Exception {
...
+            int i = mavenCmdLine.indexOf("-D");
+            if (i < 0) {
+                return;
+            }
+            final StringBuilder buf = new StringBuilder();
+            buf.append("-D");
+            i += 2;
+            while (i < mavenCmdLine.length()) {
+                final char ch = mavenCmdLine.charAt(i++);
+                if (!Character.isWhitespace(ch)) {
```
Comment (gsmet) [inline devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java:670]: I find this very fragile. IIRC, it's not the first time we discuss about this. What happens if there is a properly escaped space in the property? That happens a lot with paths on Windows.

Can't we get some Maven classes to parse the command line somehow? I thought we did that somewhere else last time we discussed this.

**Review by gsmet — CHANGES_REQUESTED** [review]
I added some concern I have about this patch.

@maxandersen could you review this one today? We had a few users asking for it?

File: devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java (hunk 1 above)
Comment (aloubyansky) [reply devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java:670]: You're right about escaping. It's not Maven-specific parsing though.

Comment (gsmet) [reply devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java:670]: I agree the escaping is not Maven specific but I suppose we should be in line with what Maven does? AFAICS we are in a Maven specific module.

Comment (aloubyansky) [reply devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java:670]: I don't think Maven does that anywhere. I can't think of reason why it would need to.

Comment (gsmet) [reply devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java:670]: I would have expected Maven to have code to parse parameters of the command line? But maybe I'm missing something obvious :).

**Comment by maxandersen** [comment]
> @maxandersen could you review this one today? We had a few users asking for it?

just saw it - I can look later tonight.

File: devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java (hunk 1 above)
Comment (maxandersen) [reply devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java:670]: Is there a reason why we need to propogate individual parameters here and not just pass on the full system properties map ?

Comment (aloubyansky) [reply devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java:670]: That would probably mean persisting them to a file and then reading it and setting the properties in the dev mode process. I thought it'd be easier to parse a "little" string to pass what's in it on.

File: integration-tests/maven/src/test/resources/projects/multimodule-revision-prop/html/src/main/resources/META-INF/resources/a.html [hunk 2]
```diff
@@ -0,0 +1 @@
+sadfasdfasdfas
```
Comment (maxandersen) [inline integration-tests/maven/src/test/resources/projects/multimodule-revision-prop/html/src/main/resources/META-INF/resources/a.html:1]: added by mistake or ?

File: independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/resolver/maven/workspace/ModelUtils.java [hunk 3]
```diff
@@ -184,6 +210,39 @@ public static String getVersion(Model model) {
         throw new IllegalStateException("Failed to determine version for project model");
     }
 
+    public static String getVersion(Model model) {
+        final String rawVersion = getRawVersion(model);
+        return isUnresolvedVersion(rawVersion) ? resolveVersion(rawVersion, model) : rawVersion;
+    }
+
+    public static boolean isUnresolvedVersion(String version) {
+        return version.charAt(0) == '$';//UNRESOLVED_VERSION_PATTERN.matcher(version).find();
```
Comment (maxandersen) [inline independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/resolver/maven/workspace/ModelUtils.java:219]: couldn't the property expression be in any part of the version string ?

Comment (famod) [reply independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/resolver/maven/workspace/ModelUtils.java:219]: Since I was the one who added `UNRESOLVED_VERSION_PATTERN` I am also a litte surprised by this change.

The [Maven documentation](https://maven.apache.org/maven-ci-friendly.html) doesn't exactly answer this question but I don't see why you should _not_ be allowed to start the raw version with a literal.

It seems the only thing that is explicitly _forbidden_ as per above mentioned doc is the usage of any _other property than `revision`, `sha1` or `changelist`.

Comment (aloubyansky) [reply independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/resolver/maven/workspace/ModelUtils.java:219]: I'll change it back.

File: integration-tests/maven/src/test/resources/projects/multimodule-revision-prop/html/src/main/resources/META-INF/resources/a.html (hunk 2 above)
Comment (aloubyansky) [reply integration-tests/maven/src/test/resources/projects/multimodule-revision-prop/html/src/main/resources/META-INF/resources/a.html:1]: This is just a copy of the multimodule project that already existed in the TS.

File: devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java [hunk 4]
```diff
@@ -642,13 +643,47 @@ void prepare() throws Exception {
...
+
             args.add("-jar");
             args.add(tempFile.getAbsolutePath());
             if (argsString != null) {
                 args.addAll(Arrays.asList(CommandLineUtils.translateCommandline(argsString)));
             }
         }
 
+        private void propagateUserProperties() {
+            final String mavenCmdLine = BootstrapMavenOptions.getMavenCmdLine();
```
Comment (maxandersen) [inline devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java:657]: might be minor issue but this will only consider things explicitly set on the command line; it will not honor `.mvn/maven.config`

Comment (aloubyansky) [reply devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java:657]: I'd classify it as a separate issue which should be fixed in the bootstrap Maven context/resolver.

File: independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/resolver/maven/workspace/ModelUtils.java [hunk 5]
```diff
@@ -184,6 +210,39 @@ public static String getVersion(Model model) {
...
+        final String rawVersion = getRawVersion(model);
+        return isUnresolvedVersion(rawVersion) ? resolveVersion(rawVersion, model) : rawVersion;
+    }
+
+    public static boolean isUnresolvedVersion(String version) {
+        return getUnresolvedVersionPattern().matcher(version).find();
+    }
+
+    public static String resolveVersion(String rawVersion, Model rawModel) {
+        final Map<String, String> props = new HashMap<>();
```
Comment (maxandersen) [inline independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/resolver/maven/workspace/ModelUtils.java:223]: this would not handle case where there are nested properties would it ?

**Review by maxandersen — APPROVED** [review]
The PR fixes the reported issue on $revision usage and about passing basic properties.

A few edge cases are not covered but I would say we should merge this in but open separate issues for them:

1) properties set in `.mvn/maven.config` are not propagated. not 100% they should but they are treated the exact same as user provided `-D` thus for completeness they should
2) parsing of the maven cmd line is done without handling quoting etc. for this specific case there are no spaces etc. thus something could  be done in follow up fix
3) the resolution does not take into account nested property resolution - again, for this specific case that are being fixed its not critical but something to consider for a update to it.

File: independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/resolver/maven/workspace/ModelUtils.java (hunk 5 above)
Comment (aloubyansky) [reply independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/resolver/maven/workspace/ModelUtils.java:223]: Nesting is not allowed in Maven project versions.

**Review by gsmet — APPROVED** [review]
We had a discussion yesterday evening with Max and Alexey and Max approved it.

File: devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java (hunk 4 above)
Comment (Thul95) [reply devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java:662]: @maxandersen @aloubyansky we work with values in the `.mvn/maven.config` file. This still results in 

`
Caused by: io.quarkus.bootstrap.resolver.maven.workspace.UnresolvedVersionException: Failed to resolve version '${revision}${sha1}' for com.example:lambda
at io.quarkus.bootstrap.resolver.maven.workspace.UnresolvedVersionException.forGa(UnresolvedVersionException.java:13)
at io.quarkus.bootstrap.resolver.maven.workspace.LocalProject.getVersion(LocalProject.java:195)
at io.quarkus.bootstrap.resolver.maven.workspace.LocalProject.getAppArtifact(LocalProject.java:286)
at io.quarkus.bootstrap.resolver.maven.workspace.LocalProject.getAppArtifact(LocalProject.java:281)
at io.quarkus.bootstrap.BootstrapAppModelFactory.resolveAppModel(BootstrapAppModelFactory.java:275)
... 46 more
`

A workaround is putting the properties in the `pom.xml`. For us that would mean adapting all project to streamline them again.

Comment (aloubyansky) [reply devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java:662]: @Thul95 please create a new issue for that. Thanks!
