### PR TITLE
Apply custom JAX-RS exception mappers for non-authentication exceptions raised during proactive auth or auth required by HTTP permissions

### LINKED ISSUE #39155: Custom Exception in SecurityIdentityAugmentor
### Describe the bug

I'm currently making an implementation of `SecurityIdentityAugmentor` that extracts data from the headers and use it to validate that the user currently logged has access to the ressource.
If something goes wrong in analyzing the header value such as a wrong value, I want to throw a custom exception `ResourceNotFoundException` and send a 404 not found since the ressource being asked is not valid.

It kinda looks like this 
``` java
@ApplicationScoped
public class AccountRoleAugmentor implements SecurityIdentityAugmentor {

    @Override
    public Uni<SecurityIdentity> augment(@NonNull final SecurityIdentity securityIdentity,
                                         @NonNull final AuthenticationRequestContext context) {
        // Get your user from DB, add roles etc.

        if (whatever) {
            throw new ResourceNotFoundException();
        }

        // ...
    }
}
```
``` java
public class ResourceNotFoundException extends RuntimeException {
    // All default exception constructors
}
```
``` java
@Provider
public class ResourceNotFoundExceptionMapper implements ExceptionMapper<ResourceNotFoundException> {

    @Override
    public Response toResponse(final ResourceNotFoundException exception) {
        // ResourceNotFoundExceptionMapper.logger.error("Resource not found from ExceptionMapper", exception);
        return Response.status(Response.Status.NOT_FOUND).build();
    }
}
```

It looks like the exception is always causing a 500 internal server error instead of going through the `ExceptionMapper`.

For information, when I'm trying to throw the same exception from a controller, it's working just fine and I get my 404 without any issues.

### Expected behavior

I would except my custom exception to behave in the same way as exceptions such as `io.quarkus.security.ForbiddenException` but with my custom exception.

### Actual behavior

An error 500 is always sent to the client despite the `ExceptionMapper`.

### How to Reproduce?

1. Create a `SecurityIdentityAugmentor`
2. Create a custom exception with the proper `ExceptionMapper`
3. Throw a custom exception
4. See an error 500 instead of going through the `ExceptionMapper`

### Output of `uname -a` or `ver`

Windows

### Output of `java -version`

OpenJDK 21

### Quarkus version or git rev

3.8.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.9.5

### Additional information

_No response_

### LINKED ISSUE #44945: ServerExceptionMapper not called
### Describe the bug

ServerExceptionMappers are supposed to be always consulted if they perfectly match the exception.
But if proactive authentication is turned on, they are not.

### Expected behavior

Customt ExceptionMapper should be called if authentication fails

### Actual behavior

they are not.

### How to Reproduce?

run this [test](https://github.com/mschirmacher/QuarkusAuthorizationPolicySuspendBug/blob/noExceptionMapperCalled/src/test/kotlin/org/acme/GreetingResourceTest.kt)
If the custom exception mapper is called, the test should be green.
Note the config on line 29 of the test - if set to false the test is green!

Architectural overview:
The test sets up a wiremock response, that returns invalid json.
There is a [custom identity provider](https://github.com/mschirmacher/QuarkusAuthorizationPolicySuspendBug/blob/noExceptionMapperCalled/src/main/kotlin/org/acme/security/auth/CustomIdentityProvider.kt), that will call an external service (the one mocked by wiremock) for authentication.
As the response cannot be deserialized, an exception is thrown which SHOULD be handled by the matching [ServerExeptionMapper](https://github.com/mschirmacher/QuarkusAuthorizationPolicySuspendBug/blob/noExceptionMapperCalled/src/main/kotlin/org/acme/exception/ServerExceptionMapper.kt) - but its not.

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

(my unprofessional debugging attemts reveald, that [this]{io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder} class is the bad guy as it doesnt seem to be prepared to call custom exception mappers)

### PR DESCRIPTION
**Pull request by michalvavrik**
- closes: https://github.com/quarkusio/quarkus/issues/39155
- closes: https://github.com/quarkusio/quarkus/issues/44945

It's important to only begin RESTEasy/REST processing only when the exception is handled by some exception mapper for cases that previously wasn't handled, because it would change response behavior and lead to more processing.

### CODE REVIEW

File: extensions/resteasy-classic/resteasy/deployment/src/main/java/io/quarkus/resteasy/deployment/ResteasyStandaloneBuildStep.java [hunk 1]
```diff
@@ -158,6 +160,29 @@ public void boot(ShutdownContextBuildItem shutdown,
         recorder.start(shutdown, requireVirtual.isPresent());
     }
 
+    private static boolean foundOtherCustomExMapper(IndexView index) {
```
Comment (sberyozkin) [inline extensions/resteasy-classic/resteasy/deployment/src/main/java/io/quarkus/resteasy/deployment/ResteasyStandaloneBuildStep.java:163]:
```suggestion
    private static boolean foundOtherCustomExceptionMapper(IndexView index) {
```

Cosmetic one, might be easier to read later...

File: extensions/resteasy-classic/resteasy/deployment/src/main/java/io/quarkus/resteasy/deployment/ResteasyStandaloneBuildStep.java [hunk 2]
```diff
@@ -158,6 +160,29 @@ public void boot(ShutdownContextBuildItem shutdown,
...
+        // check if user specified custom exception mapper that is not an exception mapper for one of auth exceptions
+        // builtin exception mappers are not supposed to be indexed, therefore this should only detect application one's
+        for (var implementor : index.getAllKnownImplementors(EXCEPTION_MAPPER)) {
+            for (Type interfaceType : implementor.interfaceTypes()) {
+                if (EXCEPTION_MAPPER.equals(interfaceType.name())) {
+                    final String mapperExSignature = interfaceType.asParameterizedType().arguments().get(0).name().toString();
+                    if (AuthenticationCompletionException.class.getName().equals(mapperExSignature)) {
```
Comment (sberyozkin) [inline extensions/resteasy-classic/resteasy/deployment/src/main/java/io/quarkus/resteasy/deployment/ResteasyStandaloneBuildStep.java:170]: If you'd like you might try keeping these names in the static set, or do some switch, but this is not really verbose so it is up to you

Comment (michalvavrik) [reply extensions/resteasy-classic/resteasy/deployment/src/main/java/io/quarkus/resteasy/deployment/ResteasyStandaloneBuildStep.java:170]: I actually think we can drop this one, I have only discovered runtime way to detect exact exception mapper for an exception later. Going this extra mile could make sense in Quarkus REST (where I didn't do it because I wasn't sure what I do was reliable), but no in the RESTEasy Classic. I'll drop it.

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpSecurityRecorder.java [hunk 3]
```diff
@@ -227,6 +235,20 @@ public static Throwable extractRootCause(Throwable throwable) {
...
+            if (!(throwable instanceof AuthenticationException)) {
+                event.put(OTHER_AUTH_FAILURE, Boolean.TRUE);
+            }
+        }
+
+        public static void removeMarkAsOtherAuthFailure(RoutingContext event) {
+            event.remove(OTHER_AUTH_FAILURE);
+        }
+
+        public static boolean isOtherAuthFailure(RoutingContext event) {
```
Comment (sberyozkin) [inline extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpSecurityRecorder.java:249]: I'd not mind to have `Auth` expanded to `Authentication` just to make these names a bit more descriptive, but it is not a big deal

**Review by sberyozkin — APPROVED** [review]
LGTM, thanks Michal, but Georgios' review is required as well

File: extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpSecurityRecorder.java (hunk 3 above)
Comment (michalvavrik) [reply extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpSecurityRecorder.java]: sure, done

**Review by geoand — APPROVED** [review]
I love this, thanks a lot!
