### PR TITLE
fix from pattern in CommonPanacheQueryImpl class

### LINKED ISSUE #10617: Method countQuery does not create select if where are line break characters (\n)
I have base functional for create where string, it create string with line break characters (\n). 

code:
 

>  PanacheQuery<MyEntity> myEntityPanacheQuery = MyEntity.find(whereStr, whereParameters);
   

> myEntityPanacheQuery.page(Page.of(pageNumber, pageSize)).list(); // it is good work

  
>  myEntityPanacheQuery.count(); // it is return exception

method count() is return exception: 
`io.quarkus.panache.common.exception.PanacheQueryException: Count query not supported for select query: FROM com.MyEntity WHERE field like :field 
 and (1 = :value1 OR (field2 = :field2))
        at io.quarkus.hibernate.orm.panache.common.runtime.CommonPanacheQueryImpl.countQuery(CommonPanacheQueryImpl.java:252)
        at io.quarkus.hibernate.orm.panache.common.runtime.CommonPanacheQueryImpl.count(CommonPanacheQueryImpl.java:214)
        at io.quarkus.hibernate.orm.panache.runtime.PanacheQueryImpl.count(PanacheQueryImpl.java:144)
        at com.bivgroup.soglacie.rra.service.journal.jra.WorkAgentJournalService.lambda$loadJournalResult$1(WorkAgentJournalService.java:39)
        at io.smallrye.mutiny.operators.UniMapOnResult$1.onItem(UniMapOnResult.java:31)
`
If remove  line break characters from where string, when countQuery will be to work well.
I think FROM_PATTERN in CommonPanacheQueryImpl class it should be replaced `Pattern.compile("^\\s*FROM\\s+.*", Pattern.CASE_INSENSITIVE);` on `Pattern.compile("^\s*FROM\s+(.|\n)*", Pattern.CASE_INSENSITIVE)`; or similar that patter processed line break characters (\n).

Quarkus version 1.5.2

### PR DESCRIPTION
**Pull request by xumk**
replace CommonPanacheQueryImpl.FROM_PATTERN in CommonPanacheQueryImpl.class because pattern not matches string if it is contains line break characters.
Add test for check CommonPanacheQueryImpl.FROM_PATTERN

Fixes #10617

### CODE REVIEW

File: extensions/panache/hibernate-orm-panache-common/runtime/src/main/java/io/quarkus/hibernate/orm/panache/common/runtime/CommonPanacheQueryImpl.java [hunk 1]
```diff
@@ -32,7 +32,7 @@
             Pattern.CASE_INSENSITIVE);
 
     // match FROM
-    static final Pattern FROM_PATTERN = Pattern.compile("^\\s*FROM\\s+.*",
+    static final Pattern FROM_PATTERN = Pattern.compile("^\\s*FROM\\s+(.|\\n|\\r)*",
```
Comment (gsmet) [inline extensions/panache/hibernate-orm-panache-common/runtime/src/main/java/io/quarkus/hibernate/orm/panache/common/runtime/CommonPanacheQueryImpl.java:35]: I think it would be better to use the `DOTALL` flag.

**Review by gsmet — DISMISSED** [review]

**Comment by gsmet** [comment]
Just a reminder that we will need to squash things before merging.

Thanks!

**Comment by xumk** [comment]
@gsmet i find similar error in SELECT_PATTERN. Used DOTALL flag for it

**Comment by gsmet** [comment]
Thanks. I squashed the commits. @loicmathieu @FroMage I let you have a look?

**Review by FroMage — APPROVED** [review]
LGTM, I didn't know newlines where allowed in JPQL. Thanks!
