### PR TITLE
fixed lost OIDC refresh token when performing a refresh

### LINKED ISSUE #10924: OIDC refresh token lost if not resent by provider
**Describe the bug**
When using Google OpenID Connect as Quarkus OIDC provider, the application receives both an access and refresh token, when `access_type=offline` is sent to Google.

It work that Quarkus uses this refresh token under the hood to refresh the expired access token, however, Google sends the refresh token only for the very first time (and never again), when a token is requested.

`CodeAuthenticationMechanism` then causes the refresh token to be lost in the `q_session` cookie, since it overrides the value with the result from the refresh, and there the refresh token is non-existent.

**Expected behavior**
To save and reuse the refresh token, since it might not be resent -- this is the case for Google, not sure how other OIDC providers do this.

**Potential fix**

I've fixed this issue in my project by manually building `quarkus-oidc` with the [following patch](https://github.com/sdaschner/quarkus/commit/9d7aac49d1176252ef4efefa9a7a4698c878c73d)

Happy to provide a PR, however, I'm not quite sure whether this is just a dirty hack or solves it in all solutions; in general, it would be good if the OIDC extension wouldn't loose refresh tokens that are only issues once, like for Google.

### PR DESCRIPTION
**Pull request by sdaschner**
Fixes #10924

### CODE REVIEW

**Review by sberyozkin — APPROVED** [review]
This PR provides a very simple update to avoid a potential NPE which we can't verify with Keycloak. It can be tested later once we support `WireMock` (confirming that all works if IDP does not recycle RTs). 
We have a good `CodeFlowTest` RT test provided by @pedroigor so having this test passing will confirm this PR does not affect the preferred case where RTs are recycled

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java [hunk 1]
```diff
@@ -303,7 +303,7 @@ public void accept(SecurityIdentity identity) {
                                             LOG.debug("ID Token is required to contain 'exp' and 'iat' claims");
                                             uniEmitter.fail(new AuthenticationCompletionException());
                                         }
-                                        processSuccessfulAuthentication(context, configContext, result, identity);
+                                        processSuccessfulAuthentication(context, configContext, result, null, identity);
```
Comment (sberyozkin) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java:306]: Lets replace `null` with `result.opaqueRefreshToken()`

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java [hunk 2]
```diff
@@ -471,7 +470,7 @@ public void handle(AsyncResult<Void> result) {
                                                 @Override
                                                 public void accept(SecurityIdentity identity) {
                                                     // after a successful refresh, rebuild the identity and update the cookie 
-                                                    processSuccessfulAuthentication(context, configContext, token,
+                                                    processSuccessfulAuthentication(context, configContext, token, refreshToken,
```
Comment (sberyozkin) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java:473]: Lets replace `refreshToken` with `result.opaqueRefreshToken() != null ? result.opaqueRefreshToken() : refreshToken` because this check only makes sense in context of the refresh token grant processing

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java [hunk 3]
```diff
@@ -348,15 +348,14 @@ private String signJwtWithClientSecret(OidcTenantConfig cfg) {
...
-
+            AccessToken result, String refreshToken, SecurityIdentity securityIdentity) {
         removeCookie(context, configContext, getSessionCookieName(configContext));
 
-        String cookieValue = new StringBuilder(result.opaqueIdToken())
-                .append(COOKIE_DELIM)
-                .append(result.opaqueAccessToken())
-                .append(COOKIE_DELIM)
-                .append(result.opaqueRefreshToken()).toString();
+        String refresh = result.opaqueRefreshToken() != null ? result.opaqueRefreshToken() : refreshToken;
```
Comment (sberyozkin) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java:354]: This line can be removed once the proposed changes have been implemented

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java (hunk 1 above)
Comment (sdaschner) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java:306]: LGTM

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java (hunk 2 above)
Comment (sdaschner) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java:473]: LGTM

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java (hunk 3 above)
Comment (sdaschner) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java:354]: You mean, rather `result.opaqueRefreshToken()` being replaced with `refreshToken` (if that's always set from either two at the method invocation already, as you proposed, right?

**Review by sberyozkin — CHANGES_REQUESTED** [review]
@sdaschner Hi, sorry, I did my initial review in a rush. Your PR is OK as it is, but I felt a bit uncomfortable later on about passing `null` at the point where RT is expected to be available. Please apply the minor proposed changes, thanks

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java (hunk 3 above)
Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java:354]: @sdaschner, this method is called from 2 places, when we complete the code grant exchange and refresh the token, in the former case RT is expected to be avail, in the latter - may not be, so I thought that in this function we should use `refreshToken` parameter

Comment (sdaschner) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java:354]: Yes, exactly +1

**Review by sdaschner — COMMENTED** [review]
Added the changes, LMK if that's what you intended

**Comment by sberyozkin** [comment]
@sdaschner Thanks for the quick update, yeah, it reads a bit better, and indeed your comment in context of the RT grant processing makes it easier to understand as well why RT may be null, so LGTM now :-) Hope the builds will like it too and then I'll merge unless Pedro has some comments. Thanks

**Comment by sberyozkin** [comment]
@sdaschner Can you please rebase, squash and force-push ? There was a  strange build failure not related to your PR

**Comment by sdaschner** [comment]
Sure, done

**Comment by sberyozkin** [comment]
@sdaschner Thanks, but did you squash ? I see 2 commits

**Comment by sdaschner** [comment]
No I didn't, now :)

**Comment by sberyozkin** [comment]
`JDK Java8 JVM Tests ` Kubernetes integration test failed, `Security Test 3` are good, Java11 & ` JDK Java 8 - 242 JVM Tests` are also good

**Comment by pedroigor** [comment]
LGTM, didn't know Google behaves like that.

**Comment by sberyozkin** [comment]
Hi @pedroigor yeah, it is a bit strange, may be because an `access_type=offline` is requested...

**Comment by sberyozkin** [comment]
@gsmet Hi, there appears to be some instability with the builds, but native security tests 3 etc are all good as far as the OIDC tests are concerned, I'll merge tomorrow morning unless you have some concerns, cheers

**Review by sberyozkin — APPROVED** [review]
