### PR TITLE
Pass all the configuration minus Quarkus defaults to Gradle code generator task

### LINKED ISSUE #49788: Quarkus issue with quarkus-confluent-registry-avro and smallrye-config-jasypt
### Describe the bug

We have the following setup:

Quarkus 3.25.4/3.26.0
Kotlin 2.2
Gradle with Kotlin Script
Ktlint

After upgrading to Quarkus 3.25.4 (same for 3.26.0) I am getting the following issue when running gradle checks like `ktlint`:

```
* What went wrong:
Execution failed for task ':quarkusGenerateCode'.
> There was a failure while executing work items
   > A failure occurred while executing io.quarkus.gradle.tasks.worker.CodeGenWorker
      > Failed to generate sources in the QuarkusGenerateCode task for org.acme:code-with-quarkus:1.0.0-SNAPSHOT due to java.lang.reflect.InvocationTargetException
```

After analysing the issue I came to the conclusion that it's being produced by the combination of the following dependencies:

```
    implementation("io.smallrye.config:smallrye-config-jasypt")
    implementation("io.quarkus:quarkus-confluent-registry-avro")
```

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

Feel free to use the following reproducer project: https://github.com/akoufa/quarkus-issues

Just run:
`./gradlew ktlintFormat`

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by radcortez**
- Fixes #49788
- Caused by https://github.com/quarkusio/quarkus/pull/49503

When running separate Gradle tasks (without the build), `application.properties` is not available in the classpath to load configuration. In the case of the code generator tasks, all the configuration values are passed down via system properties. With #49503, we replaced this only to pass Quarkus configuration, but this is insufficient, so this PR readds the ability to pass the entire Config, except the defaults already included by Quarkus.

### CODE REVIEW

File: devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/EffectiveConfig.java [hunk 1]
```diff
@@ -140,6 +141,8 @@ public Map<String, String> get() {
                         properties.put(propertyName, configValue.getValue());
                     }
                 }
+                configClass(PackageConfig.class).getProperties().keySet().forEach(properties::remove);
+                configClass(NativeConfig.class).getProperties().keySet().forEach(properties::remove);
```
Comment (aloubyansky) [inline devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/EffectiveConfig.java:145]: Why only these config properties are removed @radcortez ?

Comment (radcortez) [reply devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/EffectiveConfig.java:145]: Because Gradle passes the configuration to the worker as System Properties.

This doesn't work well with our deprecation configuration code, because it thinks that the user is setting these properties explicitly and then issues a warning message.

So, this removes the configuration that is set as default (from the mappings), and prevent it to be passed down as SystemProperties. As we start our own configuration with the same mappings on the Quarkus side, the defaults will be there.

Comment (aloubyansky) [reply devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/EffectiveConfig.java:145]: Aren't the other `*Config` classes in the same situation?

Comment (radcortez) [reply devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/EffectiveConfig.java:145]: No, because these are the only ones added in the Gradle Config:
https://github.com/quarkusio/quarkus/blob/beecd2cdd3230c1d8f13b48025260789a4a916bc/devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/EffectiveConfig.java#L87-L88

**Review by aloubyansky — APPROVED** [review]
Thanks @radcortez!
