### PR TITLE
Propagate context inside quarkus-cache async computations

### LINKED ISSUE #8166: ContextNotActiveException when using CacheResult annotation
**Describe the bug**

I get a ContextNotActiveException when I put a CacheResult annotation on a method and make the first call (not hitting the cache). If i remove it, everything works fine.

```
java.util.concurrent.CompletionException: javax.enterprise.context.ContextNotActiveException: interface javax.enterprise.context.RequestScoped
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: javax.enterprise.context.ContextNotActiveException: interface javax.enterprise.context.RequestScoped
	at io.quarkus.hibernate.orm.runtime.RequestScopedEntityManagerHolder_ClientProxy.arc$delegate(RequestScopedEntityManagerHolder_ClientProxy.zig:83)
	at io.quarkus.hibernate.orm.runtime.RequestScopedEntityManagerHolder_ClientProxy.getOrCreateEntityManager(RequestScopedEntityManagerHolder_ClientProxy.zig:191)
	at io.quarkus.hibernate.orm.runtime.entitymanager.TransactionScopedEntityManager.getEntityManager(TransactionScopedEntityManager.java:77)
	at io.quarkus.hibernate.orm.runtime.entitymanager.TransactionScopedEntityManager.createQuery(TransactionScopedEntityManager.java:316)
	at io.quarkus.hibernate.orm.runtime.entitymanager.ForwardingEntityManager.createQuery(ForwardingEntityManager.java:142)
	at io.quarkus.hibernate.orm.panache.runtime.JpaOperations.find(JpaOperations.java:266)
	at io.quarkus.hibernate.orm.panache.runtime.JpaOperations.find(JpaOperations.java:276)
	at io.quarkus.hibernate.orm.panache.runtime.JpaOperations.find(JpaOperations.java:272)
	at e.r.x.c.domain.repository.DomainClusterRepository.find(DomainClusterRepository.java)
	at e.r.x.c.domain.repository.DomainClusterRepository.findByIdCodeAndIdDomainCode(DomainClusterRepository.java:15)
	at e.r.x.c.domain.repository.DomainClusterRepository_ClientProxy.findByIdCodeAndIdDomainCode(DomainClusterRepository_ClientProxy.zig:1723)
	at e.r.x.c.domain.service.impl.DomainService.getDomainCluster(DomainService.java:27)
	at e.r.x.c.domain.service.impl.DomainService_ClientProxy.getDomainCluster(DomainService_ClientProxy.zig:166)
	at e.r.x.c.service.impl.CodeConversorServiceImpl.getConvertedValue(CodeConversorServiceImpl.java:56)
	at e.r.x.c.service.impl.CodeConversorServiceImpl_ClientProxy.getConvertedValue(CodeConversorServiceImpl_ClientProxy.zig:261)
	at e.r.x.c.typecode.service.impl.TypeCodeService.findTypeCodeByNotNormalizedCode(TypeCodeService.java:94)
	at e.r.x.c.typecode.service.impl.TypeCodeService_Subclass.findTypeCodeByNotNormalizedCode$$superaccessor1(TypeCodeService_Subclass.zig:277)
	at e.r.x.c.typecode.service.impl.TypeCodeService_Subclass$$function$$5.apply(TypeCodeService_Subclass$$function$$5.zig:59)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.cache.runtime.CacheResultInterceptor.lambda$intercept$0(CacheResultInterceptor.java:27)
	at io.quarkus.cache.runtime.caffeine.CaffeineCache$MappingSupplier.get(CaffeineCache.java:133)
	at io.quarkus.cache.runtime.caffeine.CaffeineCache.lambda$get$0(CaffeineCache.java:55)
	at com.github.benmanes.caffeine.cache.LocalAsyncCache.lambda$get$0(LocalAsyncCache.java:77)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)

```

**Expected behavior**
Get result without exception. Value put in the cache. Cache hitted on second call

**Actual behavior**
ContextNotActiveException rised on first call (not hitting the cache. Just trying to get the value persisted in database)

**To Reproduce**

1. Create quarkus project 1.3.0.Final with panache-jpa, postgres
2. Include cache dependency
3. Annotate a service layer method with CacheResult

**Configuration**
```properties
# configure your datasource
quarkus.datasource.db-kind = postgresql
quarkus.datasource.username = x
quarkus.datasource.password = x
quarkus.datasource.jdbc.url = jdbc:postgresql://localhost:5432/x
quarkus.http.port=8081
# drop and create the database at startup (use `update` to only update the schema)
quarkus.hibernate-orm.database.generation =  validate
#quarkus.hibernate-orm.database.generation =  drop-and-create
quarkus.flyway.migrate-at-start= true

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - linux 2018RMS0228 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u5 (2019-08-11) x86_64 GNU/Linux
 - OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_212-b03)
 - 1.3.0.Final
 - Apache Maven 3.6.3

**Additional context**
 
Nothing, I suppouse

Thanks a lot in advance

### PR DESCRIPTION
**Pull request by gwenneg**
Fixes #8166

### CODE REVIEW

**Comment by gwenneg** [comment]
@mkouba I had to change things a bit since our last discussion. Passing the `ManagedExecutor` instance from the `SmallRyeContextPropagationProcessor` build step to the `CacheProcessor` build step through a dedicated build item didn't work because calling `beanContainer.instance(ManagedExecutor.class)` is forbidden from a build step for an instance produced from `RUNTIME_INIT` generated bytecode.

I hope what I wrote is clear, I didn't copy the error message when it happened but it definitely didn't work for me :)

I reproduced the #8166 issue using `master` and confirmed it is fixed by this PR.

**Comment by gwenneg** [comment]
@gsmet Maybe this should be included in `1.3.1` but I don't know if that's too late or not.

File: extensions/cache/deployment/src/main/java/io/quarkus/cache/deployment/CacheProcessor.java [hunk 1]
```diff
@@ -74,9 +75,9 @@ ValidationErrorBuildItem validateBeanDeployment(ValidationPhaseBuildItem validat
     }
 
     @BuildStep
-    @Record(STATIC_INIT)
+    @Record(RUNTIME_INIT)
```
Comment (gwenneg) [inline extensions/cache/deployment/src/main/java/io/quarkus/cache/deployment/CacheProcessor.java]: We need to manually propagate the context using the Quarkus `ManagedExecutor` to fix #8166 and this executor is initialized in generated bytecode executed at `ExecutionTime.RUNTIME_INIT`. That's why the caches intialization was moved from `STATIC_INIT` to `RUNTIME_INIT` here.

File: extensions/cache/deployment/pom.xml [hunk 2]
```diff
@@ -21,7 +21,7 @@
         </dependency>
         <dependency>
             <groupId>io.quarkus</groupId>
-            <artifactId>quarkus-arc-deployment</artifactId>
+            <artifactId>quarkus-smallrye-context-propagation-deployment</artifactId>
```
Comment (gsmet) [inline extensions/cache/deployment/pom.xml]: Can we keep the Arc dependency if it's needed by this extension?

Relying on transitive dependencies is not a good idea if your extension uses directly ArC.

File: extensions/cache/runtime/pom.xml [hunk 3]
```diff
@@ -18,7 +18,7 @@
     <dependencies>
         <dependency>
             <groupId>io.quarkus</groupId>
-            <artifactId>quarkus-arc</artifactId>
+            <artifactId>quarkus-smallrye-context-propagation</artifactId>
```
Comment (gsmet) [inline extensions/cache/runtime/pom.xml]: Same here.

File: extensions/cache/runtime/src/main/java/io/quarkus/cache/runtime/caffeine/CaffeineCacheBuildRecorder.java [hunk 4]
```diff
@@ -19,14 +21,15 @@ public void buildCaches(BeanContainer beanContainer, Set<CaffeineCacheInfo> cach
         // The number of caches is known at build time so we can use fixed initialCapacity and loadFactor for the caches map.
         Map<String, CaffeineCache> caches = new HashMap<>(cacheInfos.size() + 1, 1.0F);
 
+        ManagedExecutor managedExecutor = Arc.container().instance(ManagedExecutor.class).get();
```
Comment (gsmet) [inline extensions/cache/runtime/src/main/java/io/quarkus/cache/runtime/caffeine/CaffeineCacheBuildRecorder.java]: Can't you use the `BeanContainer` since you pass it?

File: extensions/smallrye-context-propagation/deployment/src/main/java/io/quarkus/smallrye/context/deployment/ManagedExecutorBuildItem.java [hunk 5]
```diff
@@ -0,0 +1,12 @@
...
+
+import io.quarkus.builder.item.SimpleBuildItem;
+
+/**
+ * This build item can be injected in an extension {@link io.quarkus.deployment.annotations.BuildStep BuildStep} to make sure
+ * the Quarkus {@link org.eclipse.microprofile.context.ManagedExecutor ManagedExecutor} instance is available for injection
+ * during bytecode recording. The executor can only be used from generated bytecode executed at
+ * {@link io.quarkus.deployment.annotations.ExecutionTime#RUNTIME_INIT ExecutionTime.RUNTIME_INIT}.
+ */
+public final class ManagedExecutorBuildItem extends SimpleBuildItem {
```
Comment (gsmet) [inline extensions/smallrye-context-propagation/deployment/src/main/java/io/quarkus/smallrye/context/deployment/ManagedExecutorBuildItem.java]: Since it doesn't pass the `ManagedExecutor`, I would have named it `ManagedExecutorInitialized`.

File: extensions/cache/deployment/src/main/java/io/quarkus/cache/deployment/CacheProcessor.java [hunk 6]
```diff
@@ -74,9 +75,9 @@ ValidationErrorBuildItem validateBeanDeployment(ValidationPhaseBuildItem validat
...
     void recordCachesBuild(CombinedIndexBuildItem combinedIndex, BeanContainerBuildItem beanContainer, CacheConfig config,
```
Comment (gsmet) [inline extensions/cache/deployment/src/main/java/io/quarkus/cache/deployment/CacheProcessor.java]: If we initialize the caches at runtime, it opens the gate for making the cache configuration partly runtime? At least the size of the caches?

**Review by gsmet — CHANGES_REQUESTED** [review]
I added a couple of comments but I'll let @mkouba drive this puppy home.

File: extensions/cache/deployment/pom.xml (hunk 2 above)
Comment (gwenneg) [reply extensions/cache/deployment/pom.xml]: Fixed.

File: extensions/cache/runtime/src/main/java/io/quarkus/cache/runtime/caffeine/CaffeineCacheBuildRecorder.java (hunk 4 above)
Comment (gwenneg) [reply extensions/cache/runtime/src/main/java/io/quarkus/cache/runtime/caffeine/CaffeineCacheBuildRecorder.java]: Good catch. I tried a few build time solutions based on `BeanContainer` that didn't work, but I forgot to try it from the recorder.

File: extensions/smallrye-context-propagation/deployment/src/main/java/io/quarkus/smallrye/context/deployment/ManagedExecutorBuildItem.java (hunk 5 above)
Comment (gwenneg) [reply extensions/smallrye-context-propagation/deployment/src/main/java/io/quarkus/smallrye/context/deployment/ManagedExecutorBuildItem.java]: Done. That's a better name indeed.

File: extensions/cache/deployment/src/main/java/io/quarkus/cache/deployment/CacheProcessor.java (hunk 6 above)
Comment (gwenneg) [reply extensions/cache/deployment/src/main/java/io/quarkus/cache/deployment/CacheProcessor.java]: Yes, it does. I would probably make the entire [CaffeineConfig](https://github.com/quarkusio/quarkus/blob/master/extensions/cache/deployment/src/main/java/io/quarkus/cache/deployment/CacheConfig.java#L29) class runtime config. WDYT?

File: extensions/cache/runtime/pom.xml (hunk 3 above)
Comment (gwenneg) [reply extensions/cache/runtime/pom.xml]: Fixed.

File: extensions/cache/deployment/src/main/java/io/quarkus/cache/deployment/CacheProcessor.java (hunk 6 above)
Comment (gsmet) [reply extensions/cache/deployment/src/main/java/io/quarkus/cache/deployment/CacheProcessor.java]: exactly what I had in mind. But let's make it another PR once this one is in.

**Comment by gsmet** [comment]
Please don't set the milestone to 1.3.2. If backport is needed, use the backport label.

I did it.

**Comment by gsmet** [comment]
I have another concern about this. Until now I think the context-propagation dependency was always optional and context propagation was enabled if the user added the dependency explicitly. This PR makes it a transitive dependency of cache.

If I'm right (I haven't followed this closely so better check), I think this should be discussed in a place with more visibility and warrants a post on the ML

**Comment by gwenneg** [comment]
Thanks for the review @gsmet!

I didn't know about `smallrye-context-propagation` being usually optional. I think it could be made optional as well in this PR. I'll run some local tests and then update the PR is it works like that. Otherwise, I'll post a message on the ML.

**Comment by gsmet** [comment]
That being said, I wonder if we should change that and make it transitive.

More and more things have weird behaviors if it's not there. I'm not entirely sure of the consequences though.

**Comment by gwenneg** [comment]
Then maybe making the dependency optional here would be a good first step to be consistent with other extensions and more precisely with `mutiny`.

In parallel, we can start a discussion on the ML about this subject and if there's something to change, apply the change everywhere in Quarkus in a single dedicated PR.

**Comment by gwenneg** [comment]
I forced-push a new commit that makes the `smallrye-context-propagation` optional. CI will be happy with is (tested on fork) but I want to run additional manual tests, hence the `[WIP]` tag.

**Comment by gwenneg** [comment]
Manual tests results are not good:
```
java.lang.RuntimeException: java.lang.ExceptionInInitializerError
Caused by: java.lang.ExceptionInInitializerError
Caused by: java.lang.RuntimeException: Failed to start quarkus
Caused by: java.lang.NoClassDefFoundError: org/jboss/resteasy/context/ResteasyContextProvider
Caused by: java.lang.ClassNotFoundException: org.jboss.resteasy.context.ResteasyContextProvider
```
I added an exclusion for `resteasy-context-propagation` based on the quarkus-mutiny `pom.xml` but it's not fixing the issue.

I'll continue investigating this on my fork tonight.

**Comment by gwenneg** [comment]
I reverted the `optional` changes, it was clearly not done the good way.

**Comment by gwenneg** [comment]
I just pushed a new version of this PR that makes `quarkus-smallrye-context-propagation` properly optional for `quarkus-cache`. CI should be happy with it and it was also tested manually with a few quickstarts to make sure everything is running fine.

@gsmet I wanted to have a proper version with an optional `smallrye-context-propagation` before I started the ML discussion. Could you please tell me if you still think this subject needs to be discussed? I like this new version without the compile dependency on `smallrye-context-propagation` much better than the first one.

**Comment by gwenneg** [comment]
So what should I do about this PR? :)

File: core/deployment/src/main/java/io/quarkus/deployment/builditem/ManagedExecutorInitializedBuildItem.java [hunk 7]
```diff
@@ -0,0 +1,42 @@
...
+ *        if (managedExecutorInitialized) {
+ *            ManagedExecutor managedExecutor = beanContainer.instance(ManagedExecutor.class);
+ *            // Use it...
+ *        }
+ *    }
+ * }
+ * </pre>
+ * </p>
+ */
+public final class ManagedExecutorInitializedBuildItem extends SimpleBuildItem {
```
Comment (gsmet) [inline core/deployment/src/main/java/io/quarkus/deployment/builditem/ManagedExecutorInitializedBuildItem.java:41]: I wonder if this should be in a SPI module rather than in core. But we can move it later.

File: extensions/cache/runtime/pom.xml [hunk 8]
```diff
@@ -24,6 +24,10 @@
             <groupId>io.quarkus</groupId>
             <artifactId>quarkus-caffeine</artifactId>
         </dependency>
+        <dependency>
+            <groupId>org.eclipse.microprofile.context-propagation</groupId>
+            <artifactId>microprofile-context-propagation-api</artifactId>
+        </dependency>
```
Comment (gsmet) [inline extensions/cache/runtime/pom.xml:30]: @FroMage @stuartwdouglas what's your opinion on having a dependency on that one here? It's a bit related to what you are currently doing with the other PR.

Comment (gwenneg) [reply extensions/cache/runtime/pom.xml:30]: If that can help answer @gsmet's question, this dependency is only present here to allow the `ManagedExecutor` import and usage in `CaffeineCacheBuildRecorder`.

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Rebased and force-pushed. Let's merge it if CI is green.
