### PR TITLE
Refine how resource classes with same components are merged

### LINKED ISSUE #25462: Request routing partially broken in reactive RESTEasy
### Describe the bug

Consider the following two resource classes:

```
@Produces(MediaType.TEXT_PLAIN)
@Path("/routing-broken/{id1}")
public class RoutingBrokenA {
    @GET
    @Path("/some/other/path")
	public Response doSomething(@PathParam("id1") String id) {
	    return Response.ok(id).build();
	}
}


@Produces(MediaType.TEXT_PLAIN)
@Path("/routing-broken/{id2}")
public class RoutingBrokenB {
    @GET
    @Path("/some/path")
	public Response doSomething(@PathParam("id2") String id) {
	    return Response.ok(id).build();
	}
}
```

Note the different path parameter name on both classes. It seems that one class shadows the other class completely, i.e. requests matching `RoutingBrokenA.doSomething` are returned as 404. It works if the path parameter has the same name in both classes.

The same code works without problems in classic RESTEasy.

### Expected behavior

Both resource methods should be addressable by corresponding requests.

### Actual behavior

Only one of the two methods is accessible.

### How to Reproduce?

Run `quarkus.bugs.RoutingBrokenTest` from https://github.com/sithmein/bugs-in-quarkus.

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

17

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.8.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Postremus**
Fixes #25462 

Resources classes where merged by using all components as map key. This leads to situations where the only differing property of a component may be its name. The name is for a DEFAULT_REGEX however not enough to be considered a different path itself.

The merge is now based on a custom (String) key, build on properties which should enforce uniqueness when needed: type, literal, and pattern.

### CODE REVIEW

**Comment by geoand** [comment]
Thanks for looking into this @Postremus! 

While working on this, please make sure that the JAX-RS TCK is passing with this change

**Comment by Postremus** [comment]
@geoand
Where are the tcks located for resteasy-reactive? 
Is it this module? https://github.com/quarkusio/quarkus/tree/main/tcks/resteasy-reactive

**Comment by geoand** [comment]
Yes exactly, Just run `mvn install` on that module once you've built your change in Quarkus.

**Comment by Postremus** [comment]
@geoand 
TCKs are passing.

**Comment by Postremus** [comment]
Test failures do not look related. The kafka dev service container could not be started.
```
java.lang.RuntimeException: 
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.kafka.client.deployment.DevServicesKafkaProcessor#startKafkaDevService threw an exception: java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Container startup failed
```

**Review by geoand — APPROVED** [review]
LGTM, thanks!

@stuartwdouglas any objections?

**Review by geoand — CHANGES_REQUESTED** [review]
Actually, looking at https://github.com/quarkusio/quarkus/issues/25462#issuecomment-1126738354, it seems like this was an opt-in feature of RESTEasy Classic.

So we should probably do the same here.

**Comment by Postremus** [comment]
I don't see how `resteasy.wider.request.matching` is related to this issue.

This flag was first mentioned, as far as I found, in the migration guide for 3.0-beta-5 to 3.0-beta-6:
https://docs.jboss.org/resteasy/docs/3.0.6.Final/userguide/html/Migration_from_older_versions.html
```
[..] For example, resource classes are scanned for a best match, other are ignored in the match. [..] There is one config switch I added so that Resteasy will ignore the Spec defined class expression filtering step and instead match base on the full expressions of each JAX-RS method. resteasy.wider.request.matching. [..]
```

I found these integration tests in resteasy:
* https://github.com/resteasy/resteasy/blob/main/testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/basic/WiderMappingTest.java
* https://github.com/resteasy/resteasy/blob/main/testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/basic/WiderMappingNegativeTest.java

The test consisist of:
* one resource class with path "/hello"
* one resource class with path "{x:.*}"

In WiderMappingTest (`resteasy.wider.request.matching=true`), {x:.*} must match, while "/hello" must match in the negative test.

Also, as far as I can tell, the handling of the flag `resteasy.wider.request.matching` is done in ResourceMethodRegistry. In each method of this class, `widerMatching` is checked. if true, do operations on `rootNode` (all endpoints), otherwise operate on `root` (only resource classes).

This flag only changes the order of how resources with different paths are merged, but has no influence in how resources with the same paths are matched.

I therefore believe that this fix is still correct, and no config switch is needed. We merge resources with the same path (components) on class level. No change is done to the specific resource matching.

**Comment by Postremus** [comment]
I am btw. happy to introduce a config switch for this @geoand , I just don't want to do anything based on false assumptions on how the old stack worked.

**Review by stuartwdouglas — APPROVED** [review]
I think this looks ok.

**Comment by geoand** [comment]
@Postremus thanks for this.

Any chance you can do a small benchmark to see if this introduces any noticeable overhead?

**Comment by Postremus** [comment]
yep, will prepare a test project and do a simple benchmark (e.g. look at either profiler data or check how long dev mode restarts take comperativly)

**Comment by geoand** [comment]
Thanks!

We also want to make sure throughput for simple hello-world style rest calls is not affected

File: independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/startup/RuntimeDeploymentManager.java [hunk 1]
```diff
@@ -255,4 +260,54 @@ private String sanitizePathPrefix(String prefix) {
...
+                keyBuilder.append(";");
+                if (component.pattern != null) {
+                    // (?<id1>[a-zA-Z]+) -> [a-zA-Z]+
+                    String pattern = component.pattern.pattern();
+                    keyBuilder.append(component.pattern.pattern(), pattern.indexOf('>') + 1, pattern.length() - 1);
+                }
+                keyBuilder.append("|");
+            }
+
+            this.key = keyBuilder.toString();
```
Comment (gsmet) [inline independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/startup/RuntimeDeploymentManager.java:285]: My guess is that it would be better if you could compute the hashCode here and cache it in a final field.

**Review by gsmet — COMMENTED** [review]
@Postremus could you have another look at this one so that we finalize it?

I added a small suggestion.

**Comment by gsmet** [comment]
@Postremus friendly ping.

**Comment by geoand** [comment]
@Postremus are you still interested in driving this home?

**Comment by gsmet** [comment]
@geoand I rebased and applied some minor tweaks to reduce the cost of this new layer. I think you're more equipped than me to see if it introduces some significant overhead?

**Comment by geoand** [comment]
I'll have a look

**Comment by geoand** [comment]
Fixed the styling issue and applied one more small enhancement

**Review by geoand — APPROVED** [review]
