### PR TITLE
Swagger and static resource support AWS Lambda HTTP, Azure HTTP

### LINKED ISSUE #8226: swagger-ui endpoint not accessible in AWS Lambda
**Describe the bug**
Making a http call to /swagger-ui/ , the app fails to serve the swagger-ui files. Local Dev mode works fine. 

**Expected behavior**
Opening /swagger-ui/ should load swagger-ui/index.html page

**Actual behavior**
ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-2) HTTP Request to /swagger-ui/index.html failed, error id: bea62c51-a11f-4cb4-8aba-86217c872b1d-1: io.vertx.core.file.FileSystemException: java.nio.file.NoSuchFileException: META-INF/swagger-ui-files/index.html
	at io.vertx.core.file.impl.FileSystemImpl$7.perform(FileSystemImpl.java:625)
	at io.vertx.core.file.impl.FileSystemImpl$7.perform(FileSystemImpl.java:613)
	at io.vertx.core.file.impl.FileSystemImpl.propsBlocking(FileSystemImpl.java:162)
	at io.vertx.ext.web.handler.impl.StaticHandlerImpl.lambda$getFileProps$4(StaticHandlerImpl.java:295)
	at io.vertx.ext.web.handler.impl.StaticHandlerImpl.wrapInTCCLSwitch(StaticHandlerImpl.java:266)
	at io.vertx.ext.web.handler.impl.StaticHandlerImpl.getFileProps(StaticHandlerImpl.java:295)
	at io.vertx.ext.web.handler.impl.StaticHandlerImpl.lambda$sendStatic$1(StaticHandlerImpl.java:208)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:330)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.file.NoSuchFileException: META-INF/swagger-ui-files/index.html
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at io.vertx.core.file.impl.FileSystemImpl$7.perform(FileSystemImpl.java:619)

**To Reproduce**
1.  Create a sample Quarkus project with Quarkus 1.3.0.final 
2.  Maven Dependencies - quarkus-resteasy, resteasy-jackson, quarkus-smallrye-openapi and quarkus-amazon-lambda-http
3. SAM template - Lambda to API gateway proxy integration 
4. Set quarkus.swagger-ui.always-include=true in application.properities
5. Deploy the app to lambda 
6.) Try to accessing <host>/swagger-ui/ endpoint 

**Configuration**
```properties
# Add your application.properties here, if applicable.
quarkus.swagger-ui.always-include=true
```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`:  java8
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.3.0.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): maven 3.6.2+

**Additional context**
(Add any other context about the problem here.)

### PR DESCRIPTION
**Pull request by patriot1burke**
I was not handling static resource correctly in the virtual HTTP layer.  This fix will allow swagger support to work with AWS and Azure HTTP extensions as well as any static resource that emits FileRegion's internally.

I also redid the VirtualChannel stuff a bit to avoid context switching.  I was having trouble with FileRegions as the VirtualChannel was closing the file before the azure/aws layer could read from the region.  Since I was doing too much context switching anyways, I decided to just move message processing to the io loop.  This aws/azure message processing is all non-blocking so it should be fine.

@stuartwdouglas Not sure if I handled FileRegions correctly.  Can you take a look?  They are in a spin loop.  It looks like the NioChannel is handling them in the same way.

### CODE REVIEW

File: extensions/amazon-lambda-http/runtime/src/main/java/io/quarkus/amazon/lambda/http/LambdaHttpHandler.java [hunk 1]
```diff
@@ -46,19 +53,102 @@ public AwsProxyResponse handleRequest(AwsProxyRequest request, Context context)
...
+                if (msg instanceof FileRegion) {
+                    FileRegion file = (FileRegion) msg;
+                    if (file.count() > 0 && file.transferred() < file.count()) {
+                        if (baos == null)
+                            baos = createByteStream();
+                        if (byteChannel == null)
+                            byteChannel = Channels.newChannel(baos);
+                        // AbstractNioByteChannel also seems to do a spin, albeit with a count.
+                        while (file.transferred() < file.count()) {
+                            file.transferTo(byteChannel, file.transferred());
```
Comment (stuartwdouglas) [inline extensions/amazon-lambda-http/runtime/src/main/java/io/quarkus/amazon/lambda/http/LambdaHttpHandler.java:118]: I don't think this is correct. I think you need to create a buffer that is the size of file.count(), then just calling transferTo once should be enough. If you don't have enough space in the buffer then there is no way to read all the contents.

**Review by stuartwdouglas — CHANGES_REQUESTED** [review]

File: extensions/amazon-lambda-http/runtime/src/main/java/io/quarkus/amazon/lambda/http/LambdaHttpHandler.java (hunk 1 above)
Comment (patriot1burke) [reply extensions/amazon-lambda-http/runtime/src/main/java/io/quarkus/amazon/lambda/http/LambdaHttpHandler.java:118]: The channel is a ByteArrayOutputStream:
Channels.newChannel(baos);

I thought the problem would have been on the read of the file.  That's why I was worried.

Comment (stuartwdouglas) [reply extensions/amazon-lambda-http/runtime/src/main/java/io/quarkus/amazon/lambda/http/LambdaHttpHandler.java:118]: Ah yea, in that case I think it should just work without the loop. According to the docs:

`Fewer than the requested number of
     * bytes are transferred if this channel's file contains fewer than
     * <tt>count</tt> bytes starting at the given <tt>position</tt>, or if the
     * target channel is non-blocking and it has fewer than <tt>count</tt>
     * bytes free in its output buffer.
`

This should be a blocking channel, so as far as I can see it should always succeed in one call. The ones inside Netty itself are working with non-blocking channels.

**Comment by patriot1burke** [comment]
@oztimpower This has resolved the exception stack trace issues when running with test harness.

File: extensions/amazon-lambda-http/runtime/src/main/java/io/quarkus/amazon/lambda/http/LambdaHttpHandler.java [hunk 2]
```diff
@@ -46,19 +53,99 @@ public AwsProxyResponse handleRequest(AwsProxyRequest request, Context context)
...
+                    }
+                }
+                if (msg instanceof FileRegion) {
+                    FileRegion file = (FileRegion) msg;
+                    if (file.count() > 0 && file.transferred() < file.count()) {
+                        if (baos == null)
+                            baos = createByteStream();
+                        if (byteChannel == null)
+                            byteChannel = Channels.newChannel(baos);
+                        file.transferTo(byteChannel, file.transferred());
```
Comment (stuartwdouglas) [inline extensions/amazon-lambda-http/runtime/src/main/java/io/quarkus/amazon/lambda/http/LambdaHttpHandler.java:116]: This should be file.count().

File: extensions/azure-functions-http/runtime/src/main/java/io/quarkus/azure/functions/resteasy/runtime/BaseFunction.java [hunk 3]
```diff
@@ -92,51 +92,83 @@ protected HttpResponseMessage nettyDispatch(VirtualClientConnection connection,
...
-                        ReferenceCountUtil.release(msg);
                 }
+                if (msg instanceof FileRegion) {
+                    FileRegion file = (FileRegion) msg;
+                    if (file.count() > 0 && file.transferred() < file.count()) {
+                        if (baos == null)
+                            baos = createByteStream();
+                        if (byteChannel == null)
+                            byteChannel = Channels.newChannel(baos);
+                        file.transferTo(byteChannel, file.transferred());
```
Comment (stuartwdouglas) [inline extensions/azure-functions-http/runtime/src/main/java/io/quarkus/azure/functions/resteasy/runtime/BaseFunction.java:154]: should be .count().

**Review by stuartwdouglas — CHANGES_REQUESTED** [review]
LGTM except you have used .transferred() instead of .count()

File: extensions/amazon-lambda-http/runtime/src/main/java/io/quarkus/amazon/lambda/http/LambdaHttpHandler.java (hunk 2 above)
Comment (patriot1burke) [reply extensions/amazon-lambda-http/runtime/src/main/java/io/quarkus/amazon/lambda/http/LambdaHttpHandler.java:116]: ok, that concerns me because my test passes.

Comment (stuartwdouglas) [reply extensions/amazon-lambda-http/runtime/src/main/java/io/quarkus/amazon/lambda/http/LambdaHttpHandler.java]: Actually no, I am completly wrong here. This should be file.transferred(), which will always be 0.

Comment (stuartwdouglas) [reply extensions/amazon-lambda-http/runtime/src/main/java/io/quarkus/amazon/lambda/http/LambdaHttpHandler.java]: @patriot1burke sorry for the noise, I got confused between the parameters the underlying file channel takes and the FileRegion itself.

Comment (patriot1burke) [reply extensions/amazon-lambda-http/runtime/src/main/java/io/quarkus/amazon/lambda/http/LambdaHttpHandler.java]: Yeah, I remember why I had it like that. Its supposed to be position, not how many.

**Comment by patriot1burke** [comment]
@stuartwdouglas Approve?

**Review by stuartwdouglas — APPROVED** [review]

**Comment by gsmet** [comment]
@patriot1burke I'm considering backporting that one to 1.5.1. Does it make sense to you or is it too risky?
