### PR TITLE
Use CDI when accessing UserTransaction/TransactionManager in QuarkusTransaction

### LINKED ISSUE #28709: QuarkusTransaction does not fire @Initialized(TransactionScoped.class)
### Describe the bug

When starting a new transaction with `QuarkusTransaction.run`, listeners listening with `@Observes @Initialized(TransactionScoped.class) Object notUsed` are not notified.

### Expected behavior

Listeners should be notified.

### Actual behavior

Listeners are not notified.

### How to Reproduce?

1. Execute [transaction-event-reproducer.zip](https://github.com/quarkusio/quarkus/files/9827630/transaction-event-reproducer.zip)
2. Wait 10s
3. See log output...it is fired for `@Transactional`, but not for `QuarkusTransaction.run`

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19044.2006]

### Output of `java -version`

OpenJDK Runtime Environment Corretto-17.0.4.9.1 (build 17.0.4.1+9-LTS)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.13.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by yrodiere**
So that CDI scopes are handled correctly.

Fixes #28709

### CODE REVIEW

File: extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/QuarkusTransactionImpl.java [hunk 1]
```diff
@@ -218,6 +218,11 @@ private static void begin(RunOptionsBase options) {
         }
     }
 
+    static void begin(BeginOptions options) {
+        RequestScopedTransaction tx = Arc.container().instance(RequestScopedTransaction.class).get();
```
Comment (mkouba) [inline extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/QuarkusTransactionImpl.java:222]: Do you happen to know why the `RequestScopedTransaction` is used instead of `cachedUserTransaction` for the `begin()` method?

Comment (yrodiere) [reply extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/QuarkusTransactionImpl.java:222]: I guess it's just a failsafe in `QuarkusTransaction#begin`?

It's documented that way, at least:

https://github.com/quarkusio/quarkus/blob/eed0241eaf6dfdd1f148e14dd153edf7404ac2d1/extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/QuarkusTransaction.java#L37-L38

That's not really related to our problem, though. `RequestScopedTransaction` uses a CDI-provided `UserTransaction` under the hood, so it should work fine.

**Review by mkouba — APPROVED** [review]

**Comment by yrodiere** [comment]
Merged, thanks
