### PR TITLE
Change timing of @Initialized and @BeforeDestroyed events so that they can be observed from a bean within given context

### LINKED ISSUE #46108: @Observes @BeforeDestroyed(?Scoped.class) does not work in the same bean and the same scope
### Describe the bug

It seems when its observed by a application scoped bean, the `@Observes` works fine like here:

https://github.com/manovotn/quarkus/blob/ed08d10bcf5d6635a76574cf149c5e2a42d45ae9/extensions/undertow/deployment/src/test/java/io/quarkus/undertow/test/sessioncontext/ObservingBean.java

However, when its observed from a bean inside the same scope, it doesnt work:

```
@RequestScoped
public class Obsi {
    public void destroy(@Observes(notifyObserver = Reception.IF_EXISTS) @BeforeDestroyed(RequestScoped.class) Object event) {
        System.err.println("@BeforeDestroyed");
    }
}

```

Doesnt matter if Session or RequestScoped

### Expected behavior

should be called

### Actual behavior

is not called

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by manovotn**
Fixes #46108

The idea is to be able to observe `@Initialized` and `@BeforeDestroyed` from within a bean in a context that's being initialized/destroyed - see the test in this PR.

Since we can be handing over context states that may or may not have been initialized/destroyed yet, I placed that information into the `CurrentContextState` implementation.

### CODE REVIEW

File: independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl/CurrentManagedContext.java [hunk 1]
```diff
@@ -62,10 +62,17 @@ public ContextState activate(ContextState initialState) {
         if (initialState == null) {
             CurrentContextState state = initializeState();
             currentContext.set(state);
+            if (state.shouldFireInitializedEvent()) {
```
Comment (mkouba) [inline independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl/CurrentManagedContext.java:65]: Hm, I think that we should just move `fireIfNotNull(initializedNotifier)` out of `initializeState()` and place after `currentContext.set(state)`, and move `fireIfNotNull(beforeDestroyedNotifier);` before `currentState.invalidate()`, i.e. no need to add more state to the `CurrentContextState`...

Comment (manovotn) [reply independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl/CurrentManagedContext.java:65]: Hm, that's what I did initially (and it works for just ArC) but then I thought we are passing around context state and we cannot be sure if the state was initialized/destroyed or not or we just set its context?

File: independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl/CurrentManagedContext.java [hunk 2]
```diff
@@ -62,10 +62,17 @@ public ContextState activate(ContextState initialState) {
...
+                fireIfNotNull(initializedNotifier);
+            }
             return state;
         } else {
             if (initialState instanceof CurrentContextState) {
-                currentContext.set((CurrentContextState) initialState);
+                CurrentContextState currentContextState = (CurrentContextState) initialState;
+                currentContext.set(currentContextState);
+                if (currentContextState.isValid() && !currentContextState.shouldFireInitializedEvent()) {
```
[the remark this answers is not in the document]
Comment (manovotn) [reply independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl/CurrentManagedContext.java]: Oops, thanks, that was a leftover :)

File: independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl/CurrentManagedContext.java (hunk 1 above)
Comment (mkouba) [reply independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl/CurrentManagedContext.java:65]: That's a very good point.

File: independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl/CurrentManagedContext.java [hunk 3]
```diff
@@ -62,10 +62,17 @@ public ContextState activate(ContextState initialState) {
...
             CurrentContextState state = initializeState();
             currentContext.set(state);
+            if (state.shouldFireInitializedEvent()) {
+                fireIfNotNull(initializedNotifier);
+            }
             return state;
         } else {
             if (initialState instanceof CurrentContextState) {
-                currentContext.set((CurrentContextState) initialState);
+                CurrentContextState currentContextState = (CurrentContextState) initialState;
```
Comment (mkouba) [inline independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl/CurrentManagedContext.java:71]: You could use pattern matching here... 

```java
if (initialState instanceof CurrentContextState current) {
   if (current.isValid() && current.shouldFireInitializedEvent()) {
      fireIfNotNull(beforeDestroyedNotifier);
   }
   return initialState;
}
```

File: independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl/CurrentManagedContext.java [hunk 4]
```diff
@@ -271,6 +290,14 @@ public boolean isValid() {
             return isValid == VALID;
         }
 
+        boolean shouldFireInitializedEvent() {
+            return INITIALIZED_FIRED.compareAndSet(this, FALSE, TRUE);
+        }
+
+        public boolean shouldFireBeforeDestroyedEvent() {
```
Comment (mkouba) [inline independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl/CurrentManagedContext.java:297]: Why `public`? Or why is it different compared to `shouldFireInitializedEvent()`?

File: independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl/CurrentManagedContext.java (hunk 1 above)
Comment (mkouba) [reply independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl/CurrentManagedContext.java:65]: I think that we should also clarify that `ManagedContext#initializeState()` does not fire an `@Initialized` event. That it merely creates a new context state.

Comment (manovotn) [reply independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl/CurrentManagedContext.java:65]: Yes, and while at it, I will also add that `active()` fires it.

File: independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl/CurrentManagedContext.java (hunk 4 above)
Comment (manovotn) [reply independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl/CurrentManagedContext.java:297]: They used to be both `public` but I forgot to remove it from this one - will do.

**Comment by manovotn** [comment]
@mkouba @Ladicek all of the comments should be addressed now.

**Review by mkouba — APPROVED** [review]

**Review by Ladicek — APPROVED** [review]
