### PR TITLE
Fix Dev UI Theme switch

### LINKED ISSUE #42297: Can't change between light and dark mode in DevUI
### Describe the bug

I'm not sure how long this is not possible, but when I click the icon in the top right corner to change the theme in DevUI, the icons pop up, but they are not clickable. So I'm unable to change to a different theme.

### Expected behavior

DevUI can change the theme.

### Actual behavior

Not possible to change the theme in DevUI.

### How to Reproduce?

- Open DevUI.
- Click the icon in the top right corner.
2024-08-02-1722609908_316x62
- Try to change the theme, I can't click any of the icons that pop up.
2024-08-02-1722609885_324x110
- After you click away, they disappear but the monitor icon doesn't appear again unless DevUI restarts.

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by phillip-kruger**
Fix #42297

A vaadin-web-components upgrade broke the theme switch. However, the theme switch was always a bit of a hack, example, you can click on the icon then all the options appear, and if you do not select one, but click off screen, all options disappear.  

I change this to not use the menu item with the popup, but rather made the button just loop through all options [Desktop, Light, Dark] as you click. You can also use your mouse wheel to go up and down thought the themes. 

I also moved the theme logic to it's own component, out of header. This is more maintainable.

/cc @xstefank @melloware

### CODE REVIEW

**Review by xstefank — APPROVED** [review]
LGTM

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
Nice!

File: extensions/vertx-http/dev-ui-resources/src/main/resources/dev-ui/qwc/qwc-theme-switch.js [hunk 1]
```diff
@@ -0,0 +1,112 @@
...
+        }
+        
+        this._changeToSelectedThemeIndex();
+    }
+
+    render() {
+        let theme = this.themes[this._selectedThemeIndex];
+        
+        return html`<div class="themeButton">
+                        <vaadin-button theme="icon" aria-label="${theme.name}" title="${theme.name} theme" class="button" @wheel="${this._scrollTheme}" @click="${this._nextTheme}">
```
Comment (jmartisk) [inline extensions/vertx-http/dev-ui-resources/src/main/resources/dev-ui/qwc/qwc-theme-switch.js:64]: I'm not a fan of scrolling with mousewheel here, it is too easy to do it by accident and then not know what happened or how to revert it. What do others think?

Comment (phillip-kruger) [reply extensions/vertx-http/dev-ui-resources/src/main/resources/dev-ui/qwc/qwc-theme-switch.js:64]: You mouse pointer has to be on the icon, and the scroll basically go through the 3 options, so to revert you can scroll the other way, or continue to scroll.

Comment (jmartisk) [reply extensions/vertx-http/dev-ui-resources/src/main/resources/dev-ui/qwc/qwc-theme-switch.js:64]: Yes I know that, but that's because I read the PR description. If I was a random user, I could imagine scrolling by accident and not knowing what I did :)

Comment (phillip-kruger) [reply extensions/vertx-http/dev-ui-resources/src/main/resources/dev-ui/qwc/qwc-theme-switch.js:64]: (It's kind of the same as on Linux Desktop if you scroll over your Desktop switcher icon it flips between your Desktops. It really never happens on accident.

Comment (jmartisk) [reply extensions/vertx-http/dev-ui-resources/src/main/resources/dev-ui/qwc/qwc-theme-switch.js:64]: > (It's kind of the same as on Linux Desktop if you scroll over your Desktop switcher icon it flips between your Desktops. It really never happens on accident.)

Oh it has happened to me by accident many times, and it took me a while to figure it out and start being careful about it :)

Comment (phillip-kruger) [reply extensions/vertx-http/dev-ui-resources/src/main/resources/dev-ui/qwc/qwc-theme-switch.js:64]: OK lets remove it.

Comment (phillip-kruger) [reply extensions/vertx-http/dev-ui-resources/src/main/resources/dev-ui/qwc/qwc-theme-switch.js]: Removed.

**Review by jmartisk — APPROVED** [review]
Nice! Sorry for bothering with the mousewheel, I personally find this quite annoying :D

**Review by melloware — APPROVED** [review]
