### PR TITLE
Fix native error with OTLP exporter for OpenTelemetry

### LINKED ISSUE #18314: Native build error when using quarkus-opentelemetry-exporter-otlp
## Describe the bug
A native build of a Quarkus application fails if it includes the pom dependency:

```
<dependency>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-opentelemetry-exporter-otlp</artifactId>
</dependency>
```
with quarkus.version set to 2.0.0.Final

### Expected behavior
The build should succeed

### Actual behavior
The following native build error occurs:

```
...
[demo-0.0.3-SNAPSHOT-runner:25]     analysis: 269,454.77 ms,  3.31 GB
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Detailed message:
Trace:
        at parsing io.opentelemetry.exporter.otlp.trace.OtlpGrpcSpanExporterBuilder.build(OtlpGrpcSpanExporterBuilder.java:164)
Call path from entry point to io.opentelemetry.exporter.otlp.trace.OtlpGrpcSpanExporterBuilder.build():
        at io.opentelemetry.exporter.otlp.trace.OtlpGrpcSpanExporterBuilder.build(OtlpGrpcSpanExporterBuilder.java:127)
        at io.quarkus.opentelemetry.exporter.otlp.runtime.OtlpRecorder.installBatchSpanProcessorForOtlp(OtlpRecorder.java:28)
        at io.quarkus.deployment.steps.OtlpExporterProcessor$installBatchSpanProcessorForOtlp-727556406.deploy_0(OtlpExporterProcessor$installBatchSpanProcessorForOtlp-727556406.zig:85)
        at io.quarkus.deployment.steps.OtlpExporterProcessor$installBatchSpanProcessorForOtlp-727556406.deploy(OtlpExporterProcessor$installBatchSpanProcessorForOtlp-727556406.zig:40)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:643)
```

NB: replacing the otlp  exporter with the jaeger exporter makes the error go away.

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.18363.1500]

### Output of `java -version`

Java Version 11.0.11+8-jvmci-21.1-b05

### GraalVM version (if different from Java)

GraalVM 21.1.0 Java 11 CE

### Quarkus version or git rev

2.0.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1

### PR DESCRIPTION
**Pull request by kenfinnigan**
Fixes #18314

### CODE REVIEW

File: extensions/opentelemetry/opentelemetry-exporter-otlp/runtime/src/main/java/io/quarkus/opentelemetry/exporter/otlp/runtime/graal/OtlpExporterSubstitutions.java [hunk 1]
```diff
@@ -0,0 +1,98 @@
...
+                                        .build());
+                    } catch (IllegalArgumentException | SSLException e) {
+                        throw new IllegalStateException(
+                                "Could not set trusted certificates for gRPC TLS connection, are they valid "
+                                        + "X.509 in PEM format?",
+                                e);
+                    }
+                } else {
+                    throw new IllegalStateException(
+                            "TLS cerificate configuration only supported with Netty. "
```
Comment (gsmet) [inline extensions/opentelemetry/opentelemetry-exporter-otlp/runtime/src/main/java/io/quarkus/opentelemetry/exporter/otlp/runtime/graal/OtlpExporterSubstitutions.java:73]:
```suggestion
                            "TLS certificate configuration only supported with Netty. "
```

File: extensions/opentelemetry/opentelemetry-exporter-otlp/runtime/src/main/java/io/quarkus/opentelemetry/exporter/otlp/runtime/graal/OtlpExporterSubstitutions.java [hunk 2]
```diff
@@ -0,0 +1,98 @@
...
+
+import io.grpc.ManagedChannel;
+import io.grpc.ManagedChannelBuilder;
+import io.grpc.Metadata;
+import io.grpc.netty.GrpcSslContexts;
+import io.grpc.netty.NettyChannelBuilder;
+import io.grpc.stub.MetadataUtils;
+
+@TargetClass(className = "io.opentelemetry.exporter.otlp.trace.OtlpGrpcSpanExporterBuilder")
+final class Target_io_opentelemetry_exporter_otlp_trace_OtlpGrpcSpanExporterBuilder {
```
Comment (gsmet) [inline extensions/opentelemetry/opentelemetry-exporter-otlp/runtime/src/main/java/io/quarkus/opentelemetry/exporter/otlp/runtime/graal/OtlpExporterSubstitutions.java:20]: I think it would be nice to have a class level comment explaining why this substitution.

**Review by gsmet — CHANGES_REQUESTED** [review]
Nice! Added some small comments.

**Comment by kenfinnigan** [comment]
Thanks for the review @gsmet, made the requested changes

**Review by ebullient — APPROVED** [review]

**Review by gsmet — APPROVED** [review]
