### PR TITLE
Simplify and fix building the list of framework endpoints

### LINKED ISSUE #46040: OpenTelemetry extension traces health endpoints when a custom root-path is configured
### Describe the bug

Configuring a custom path for the health endpoint like:

```
quarkus.smallrye-health.root-path=/observe/health
```

And then invoking endpoints such as `/observe/health/live` & `/observe/health/ready` results in them being traced if the OpenTelemetry extension is present. It seems to ignore `/observe/health` but not sub-paths.

### Expected behavior

All endpoint paths under `quarkus.smallrye-health.root-path` are excluded from tracing.

### Actual behavior

See details above.

### How to Reproduce?

1. `git clone https://github.com/jamesnetherton/otel-non-app-path-trace.git`
2. `cd otel-non-app-path-trace`
3. `mvn clean test`

`OtelTest` will fail. It's expecting to find only one application endpoint being traced. But it finds 3 as the health endpoints are also traced.

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

3.18.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by gsmet**
We already have the full path at some point so there's really no need to rebuild it once again, especially since the code was incorrect as it was adding the /q/ prefix always if it wasn't there in the path.

It's perfectly valid to not have /q in the path, for instance if you set quarkus.smallrye-health.root-path to /something/else.

I added a new test based on the report in addition to the ones we added recently for related fixes.

Fixes #46040

### CODE REVIEW

**Comment by gsmet** [comment]
Note: we really need to clean up all this and come up with something more solid. Everything is extremely brittle.

File: extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/RouteBuildItem.java [hunk 1]
```diff
@@ -43,6 +44,7 @@ public static Builder builder() {
         this.routerType = routerType;
         this.notFoundPageDisplayableEndpoint = builder.getNotFoundEndpoint();
         this.configuredPathInfo = builder.getRouteConfigInfo();
+        this.absolutePath = builder.absolutePath;
```
Comment (gsmet) [inline extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/RouteBuildItem.java:47]: We already built a proper `absolutePath` so let's expose it rather than rebuilding it incorrectly at a later stage.

File: extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/VertxHttpProcessor.java [hunk 2]
```diff
@@ -137,27 +135,11 @@ FrameworkEndpointsBuildItem frameworkEndpoints(NonApplicationRootPathBuildItem n
         Set<String> frameworkEndpoints = new HashSet<>();
         for (RouteBuildItem route : routes) {
             if (FRAMEWORK_ROUTE.equals(route.getRouteType())) {
-                if (route.getConfiguredPathInfo() != null) {
-                    String endpointPath = route.getConfiguredPathInfo().getEndpointPath(nonApplicationRootPath,
-                            managementBuildTimeConfig, launchModeBuildItem);
-                    frameworkEndpoints.add(endpointPath);
+                if (route.getAbsolutePath() == null) {
```
Comment (gsmet) [inline extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/VertxHttpProcessor.java:138]: For one of the route, it's null, not exactly sure which it is, maybe the 404 one.

**Review by brunobat — APPROVED** [review]

**Review by cescoffier — APPROVED** [review]
