### PR TITLE
Get OIDC recover from the connection failure if the discovery is disabled

### LINKED ISSUE #21706: Startup fails if OIDC provider is not available
### Describe the bug

I'm using the quarkus-oidc extension (multi-tenants) to securize my rest endpoints.
I defined the default oidc server as follow:

```
%prod.quarkus.oidc.auth-server-url=https://www.myoidcserver.com
%prod.quarkus.oidc.token.issuer=my-issuer
%prod.quarkus.oidc.token.audience=my-audience
%prod.quarkus.oidc.credentials.jwt.token-key-id=my-jwt-token-id
%prod.quarkus.oidc.jwks-path=/jwt/jwk-set.json
%prod.quarkus.oidc.token.header=My-Authorization
%prod.quarkus.oidc.discovery-enabled=false
%prod.quarkus.oidc.token.allow-jwt-introspection=false
%prod.quarkus.oidc.token.allow-opaque-token-introspection=false
```

### Expected behavior

I should be able to run my docker container even if https://www.myoidcserver.com is not reachable.
Just like mentionned here: https://github.com/quarkusio/quarkus/issues/16725

### Actual behavior

I got the following exception:

```
io.quarkus.oidc.common.runtime.OidcEndpointAccessException
        at io.quarkus.oidc.runtime.OidcProviderClient.getJsonWebKeySet(OidcProviderClient.java:77)
        at io.quarkus.oidc.runtime.OidcProviderClient.lambda$getJsonWebKeySet$0(OidcProviderClient.java:56)
        at io.smallrye.context.impl.wrappers.SlowContextualFunction.apply(SlowContextualFunction.java:21)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransform$UniOnItemTransformProcessor.onItem(UniOnItemTransform.java:36)
        at io.smallrye.mutiny.vertx.AsyncResultUni.lambda$subscribe$1(AsyncResultUni.java:35)
        at io.vertx.mutiny.ext.web.client.HttpRequest$10.handle(HttpRequest.java:717)
        at io.vertx.mutiny.ext.web.client.HttpRequest$10.handle(HttpRequest.java:714)
        at io.vertx.ext.web.client.impl.HttpContext.handleDispatchResponse(HttpContext.java:370)
        at io.vertx.ext.web.client.impl.HttpContext.execute(HttpContext.java:357)
        at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:335)
        at io.vertx.ext.web.client.impl.HttpContext.fire(HttpContext.java:302)
        at io.vertx.ext.web.client.impl.HttpContext.dispatchResponse(HttpContext.java:264)
        at io.vertx.ext.web.client.impl.HttpContext.lambda$null$8(HttpContext.java:519)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
        at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

### How to Reproduce?

1. Install the extension quarkus-oidc
2. Define the oidc params (copy/paste my params listed above)
3. mvnv package
4. docker build
5. docker run

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.4.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sberyozkin**
Fixes #21706 

It already works and tested when OIDC fails to discover OIDC metadata at the start up but if the discovery is disabled then it fails to recover. 

So this PR does a very simple fix (wraps the connection exception into `OIDCException` which is checked when the recovery is activated), updated the existing test and added a new test confirming it is now properly recovered.
Also replaces 2 `OIDCException`s with `ConfigurationException` - the latter is used everywhere in the OIDC code when the config issue is detected - the use of `OIDCException` in such cases is the old code...

No OIDC logic itself has been affected....

### CODE REVIEW

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcRecorder.java [hunk 1]
```diff
@@ -151,16 +151,17 @@ private static Throwable logTenantConfigContextFailure(Throwable t, String tenan
         if (!oidcConfig.discoveryEnabled) {
             if (!isServiceApp(oidcConfig)) {
                 if (!oidcConfig.authorizationPath.isPresent() || !oidcConfig.tokenPath.isPresent()) {
-                    throw new OIDCException("'web-app' applications must have 'authorization-path' and 'token-path' properties "
-                            + "set when the discovery is disabled.");
+                    throw new ConfigurationException(
```
Comment (stuartwdouglas) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcRecorder.java:154]: If you pass in the 'configKeys' property to the constructor here you will get an editor on the error page in dev mode to allow you to fix it.

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcRecorder.java [hunk 2]
```diff
@@ -151,16 +151,17 @@ private static Throwable logTenantConfigContextFailure(Throwable t, String tenan
...
+                                    + "set when the discovery is disabled.");
                 }
             }
             // JWK and introspection endpoints have to be set for both 'web-app' and 'service' applications  
             if (!oidcConfig.jwksPath.isPresent() && !oidcConfig.introspectionPath.isPresent()) {
                 if (!oidcConfig.authentication.isIdTokenRequired() && oidcConfig.authentication.isUserInfoRequired()) {
                     LOG.debugf("tenant %s supports only UserInfo", oidcConfig.tenantId.get());
                 } else {
-                    throw new OIDCException(
+                    throw new ConfigurationException(
```
Comment (stuartwdouglas) [inline extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcRecorder.java:164]: Same here

**Review by stuartwdouglas — DISMISSED** [review]

File: extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcRecorder.java (hunk 1 above)
Comment (sberyozkin) [reply extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcRecorder.java:155]: @stuartwdouglas It is very cool, thanks, updated it. Note there are more `ConfigurationException`s in this code - but I was not sure yet about updating them, as some of them report an invalid combination, etc. I'll follow though a bit later and also add the OIDC config keys constants, I've added a few of them in #21693, [here](https://github.com/quarkusio/quarkus/pull/21693/files#diff-046bbd237257d7d7e787b03bffd235e4579119ca55f45953db69d1113c3bd8ccR16), so I'll move them may be to `OidcTenantConfig` and will reuse everywhere.

**Review by gastaldi — APPROVED** [review]
LGTM
