### PR TITLE
Arc - Fix assignability for generic hierarchies, add some tests

### LINKED ISSUE #2456: Unsatisfied dependency with quarkus-arc not happening with Weld
I am currently stuck in a project migration from Thorntail to Quarkus because the following type of injection (classes changed for example purpose) is not working with quarkus-arc:0.15.0 while there's no problem with Weld.

```
public abstract class Vehicle<T extends Engine> {
	@Inject
	private T engine;
}

public interface Engine {}

@Dependent
public class PetrolEngine implements Engine {}

@ApplicationScoped
public class Car extends Vehicle<PetrolEngine> {}
```

The following exception is thrown during a Quarkus build (with the Gradle plugin):

```
Caused by: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type T extends main.java.Engine and qualifiers [@Default]
        - java member: main.java.Vehicle#engine
        - declared on CLASS bean [types=[main.java.Vehicle<main.java.PetrolEngine>, main.java.Car, java.lang.Object], qualifiers=[@Default, @Any], target=main.java.Car]
        at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:378)
        at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:361)
        at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:268)
        ... 12 more
```

I reproduced this in the following repository: https://github.com/gwenneg/quarkus-unsatisfied-dependency.

Run the ` ./gradlew clean build --stacktrace` command to see the error happening.

Is this an expected behavior from quarkus-arc?

### PR DESCRIPTION
**Pull request by manovotn**
Resolves #2456

### CODE REVIEW

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanDeployment.java [hunk 1]
```diff
@@ -578,20 +578,24 @@ private void validateBeans(List<Throwable> errors) {
                     // Disposers are not inherited
                     disposerMethods.add(method);
                 } else if (annotationStore.hasAnnotation(method, DotNames.OBSERVES)) {
-                    // TODO observers are inherited
```
Comment (mkouba) [inline independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanDeployment.java]: This shouldn't be removed - it's about discovering inherited observers.

**Review by mkouba — APPROVED** [review]

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanDeployment.java (hunk 1 above)
Comment (manovotn) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanDeployment.java]: Not sure what you mean by that, but I can re-add that TODO
