### PR TITLE
Fix issue when .m2/repo contains spaces in path

### LINKED ISSUE #1402: quarkus:dev fails with .m2/repo in path with spaces on all platforms
Download https://github.com/quarkusio/quarkus-quickstarts/tree/master/getting-started
run via
mvn compile quarkus:dev
throws
java.lang.NoClassDefFoundError: org/jboss/logging/Logger

on Windows10 with both Java8 and Java11:
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T20:41:47+02:00)
Maven home: D:\Development\Maven\bin\..
Java version: 11.0.2, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-11.0.2
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

### PR DESCRIPTION
**Pull request by starksm64**
Fixes #1402, 
This also output more information about the dev process launch when in mvn -X debug mode.

### CODE REVIEW

**Review by dmlloyd — APPROVED** [review]

**Comment by dmlloyd** [comment]
pending CI

File: devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java [hunk 1]
```diff
@@ -115,6 +115,9 @@
     @Parameter(defaultValue = "${session}")
     private MavenSession session;
 
+    @Parameter(defaultValue = "TRUE")
```
Comment (cescoffier) [inline devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java]: the recommendation says "true", but not an issue.

**Review by cescoffier — APPROVED** [review]

**Comment by dmlloyd** [comment]
See https://github.com/quarkusio/quarkus/issues/1673#issuecomment-477205320
