### PR TITLE
[Gradle] make quarkusRun depend on quarkusBuild

### LINKED ISSUE #37379: Gradle `quarkusRun` does not keep the server up
### Describe the bug

E.g.

```
❯ JAVA_HOME=/Users/galder/opt/graalvm-community-openjdk-17.0.9+9.1/Contents/Home /Users/galder/1/quarkus-quarkus/integration-tests/gradle/./gradlew -Dmaven.repo.local=/Users/galder/.m2/repository -Dorg.gradle.console=plain --configuration-cache --stacktrace --no-watch-fs --info --daemon clean quarkusRun
...
> Task :quarkusRun
Caching disabled for task ':quarkusRun' because:
  Build cache is disabled
Task ':quarkusRun' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
file or directory '/Users/galder/1/quarkus-quarkus/integration-tests/gradle/target/classes/it-test-native-agent-project/build/classes/java/quarkus-generated-sources/grpc', not found
file or directory '/Users/galder/1/quarkus-quarkus/integration-tests/gradle/target/classes/it-test-native-agent-project/build/classes/java/quarkus-generated-sources/avdl', not found
file or directory '/Users/galder/1/quarkus-quarkus/integration-tests/gradle/target/classes/it-test-native-agent-project/build/classes/java/quarkus-generated-sources/avpr', not found
file or directory '/Users/galder/1/quarkus-quarkus/integration-tests/gradle/target/classes/it-test-native-agent-project/build/classes/java/quarkus-generated-sources/avsc', not found
file or directory '/Users/galder/1/quarkus-quarkus/integration-tests/gradle/target/classes/it-test-native-agent-project/src/native-test/java', not found
file or directory '/Users/galder/1/quarkus-quarkus/integration-tests/gradle/target/classes/it-test-native-agent-project/src/quarkus-generated-sources/java', not found
file or directory '/Users/galder/1/quarkus-quarkus/integration-tests/gradle/target/classes/it-test-native-agent-project/src/quarkus-test-generated-sources/java', not found
file or directory '/Users/galder/1/quarkus-quarkus/integration-tests/gradle/target/classes/it-test-native-agent-project/src/integrationTest/resources', not found
file or directory '/Users/galder/1/quarkus-quarkus/integration-tests/gradle/target/classes/it-test-native-agent-project/src/native-test/resources', not found
file or directory '/Users/galder/1/quarkus-quarkus/integration-tests/gradle/target/classes/it-test-native-agent-project/src/quarkus-generated-sources/resources', not found
file or directory '/Users/galder/1/quarkus-quarkus/integration-tests/gradle/target/classes/it-test-native-agent-project/src/quarkus-test-generated-sources/resources', not found
JBoss Threads version 3.5.1.Final
Quarkus augmentation completed in 188ms
Executing "/Users/galder/opt/graalvm-community-openjdk-17.0.9+9.1/Contents/Home/bin/java -Dorg.gradle.daemon.idletimeout=10000 -Djava.specification.version=17 -Dsun.jnu.encoding=UTF-8 -Dsun.arch.data.model=64 -Djava.vendor.url=https://www.graalvm.org/ -Dsun.boot.library.path=/Users/galder/opt/graalvm-community-openjdk-17.0.9+9.1/Contents/Home/lib -Dsun.java.command=org.gradle.launcher.daemon.bootstrap.GradleDaemon 8.4 -Djdk.debug=release -Djava.specification.vendor=Oracle Corporation -Djava.version.date=2023-10-17 -Djava.home=/Users/galder/opt/graalvm-community-openjdk-17.0.9+9.1/Contents/Home -Dfile.separator=/ -Djava.vm.compressedOopsMode=Zero based -Dline.separator=
 -Djava.vm.specification.vendor=Oracle Corporation -Djava.specification.name=Java Platform API Specification -Dsun.management.compiler=HotSpot 64-Bit Tiered Compilers -Djava.runtime.version=17.0.9+9-jvmci-23.0-b22 -Duser.name=galder -Dfile.encoding=UTF-8 -Djava.vendor.version=GraalVM CE 17.0.9+9.1 -Djava.io.tmpdir=/var/folders/ph/4_sztq2j1f799kcr2fpk9sww0000gn/T/ -Djava.version=17.0.9 -Djava.vm.specification.name=Java Virtual Machine Specification -Dnative.encoding=UTF-8 -Djava.library.path=/Users/galder/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:. -Djava.vendor=GraalVM Community -Dsun.io.unicode.encoding=UnicodeBig -Dlibrary.jansi.path=/Users/galder/.gradle/native/jansi/1.18/osx -Dmaven.repo.local=/Users/galder/.m2/repository -DsocksNonProxyHosts=local|*.local|169.254/16|*.169.254/16 -Djava.class.path=/Users/galder/.gradle/wrapper/dists/gradle-8.4-all/56r6xik2f6skrm47et0ibifug/gradle-8.4/lib/gradle-launcher-8.4.jar -Djava.vm.vendor=GraalVM Community -Duser.variant= -Duser.timezone=Europe/Zurich -Djava.vm.specification.version=17 -Dos.name=Mac OS X -Dorg.gradle.console=plain -Duser.country=001 -Dsun.java.launcher=SUN_STANDARD -Dhttp.nonProxyHosts=local|*.local|169.254/16|*.169.254/16 -Dsun.cpu.endian=little -Duser.home=/Users/galder -Duser.language=en -Dorg.gradle.appname=gradlew -Djdk.internal.vm.ci.enabled=true -Dapple.awt.application.name=GradleDaemon -Dftp.nonProxyHosts=local|*.local|169.254/16|*.169.254/16 -Dpath.separator=: -Dos.version=14.1.1 -Djava.runtime.name=OpenJDK Runtime Environment -Djava.vm.name=OpenJDK 64-Bit Server VM -Djava.vendor.url.bug=https://github.com/oracle/graal/issues -Duser.dir=/Users/galder/1/quarkus-quarkus/integration-tests/gradle/target/classes/it-test-native-agent-project -Dos.arch=aarch64 -Dquarkus.gradle-worker.max-heap=256m -Djava.vm.info=mixed mode, sharing -Djava.vm.version=17.0.9+9-jvmci-23.0-b22 -Djava.class.version=61.0 -jar /Users/galder/1/quarkus-quarkus/integration-tests/gradle/target/classes/it-test-native-agent-project/build/quarkus-app/quarkus-run.jar"

20 problems were found storing the configuration cache, 5 of which seem unique.
- Task `:quarkusGenerateCode` of type `io.quarkus.gradle.tasks.QuarkusGenerateCode`: execution of task ':quarkusGenerateCode' caused invocation of 'Task.convention' in other task at execution time which is unsupported.
  See https://docs.gradle.org/8.4/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution
- Task `:quarkusGenerateCode` of type `io.quarkus.gradle.tasks.QuarkusGenerateCode`: execution of task ':quarkusGenerateCode' caused invocation of 'Task.project' in other task at execution time which is unsupported.
  See https://docs.gradle.org/8.4/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution
- Task `:quarkusGenerateCode` of type `io.quarkus.gradle.tasks.QuarkusGenerateCode`: invocation of 'Task.project' at execution time is unsupported.
  See https://docs.gradle.org/8.4/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution
- Task `:quarkusRun` of type `io.quarkus.gradle.tasks.QuarkusRun`: cannot serialize object of type 'org.gradle.api.internal.tasks.DefaultSourceSet', a subtype of 'org.gradle.api.tasks.SourceSet', as these are not supported with the configuration cache.
  See https://docs.gradle.org/8.4/userguide/configuration_cache.html#config_cache:requirements:disallowed_types
- Task `:quarkusRun` of type `io.quarkus.gradle.tasks.QuarkusRun`: invocation of 'Task.project' at execution time is unsupported.
  See https://docs.gradle.org/8.4/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution

See the complete report at file:///Users/galder/1/quarkus-quarkus/integration-tests/gradle/target/classes/it-test-native-agent-project/build/reports/configuration-cache/282v3e9qzfh7z2iihmmexbtci/bho1uq5u2x5wjvp97q20zzix6/configuration-cache-report.html

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.4/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD SUCCESSFUL in 3s
6 actionable tasks: 5 executed, 1 up-to-date
Configuration cache entry discarded with 20 problems.
Stopped 1 worker daemon(s).
```

The server should be staying up ready to receive requests, just like it does in `mvn quarkus:run`.

There are no integration tests for this under `integration-tests/gradle` to verify this works as expected either.

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by aloubyansky**
Fix https://github.com/quarkusio/quarkus/issues/37379

### CODE REVIEW

File: devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/QuarkusPlugin.java [hunk 1]
```diff
@@ -227,7 +227,8 @@ public boolean isSatisfiedBy(Task t) {
 
         TaskProvider<QuarkusDev> quarkusDev = tasks.register(QUARKUS_DEV_TASK_NAME, QuarkusDev.class, devRuntimeDependencies,
                 quarkusExt);
-        TaskProvider<QuarkusRun> quarkusRun = tasks.register(QUARKUS_RUN_TASK_NAME, QuarkusRun.class);
+        TaskProvider<QuarkusRun> quarkusRun = tasks.register(QUARKUS_RUN_TASK_NAME, QuarkusRun.class,
+                build -> build.dependsOn(quarkusBuild));
```
Comment (gsmet) [inline devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/QuarkusPlugin.java:231]: Should `quarkusDev` depend on `quarkusBuild` too?

Comment (aloubyansky) [reply devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/QuarkusPlugin.java:231]: No, `quarkusBuild` produces a packaged app, which isn't necessary for `quarkusDev`.

**Review by gsmet — APPROVED** [review]
