### PR TITLE
Fix Encoding and implement Accept header requirement from spec

### LINKED ISSUE #18521: Utf-8 graphql issue with non ascii chars
## Describe the bug
Utf-8 chars like german umlauts are not usable.

### Expected behavior
Special chars should work like normal chars.

### Actual behavior
Special chars like german ä, ö, ü are replaced by things like Ã¼

## To Reproduce

Or attach an archive containing the reproducer to the issue.
[code-with-quarkus_graphql_utf8.zip](https://github.com/quarkusio/quarkus/files/6783786/code-with-quarkus_graphql_utf8.zip)

1. Send the example query via dev ui or intellij http request.
2. The response does contain destroyed umlauts.

```
Example Query:

query test{
  hello(string: "München")
}

Example response:

{
  "data": {
    "hello": "MÃ¼nchen"
  }
}

Example Intellij http request:

POST http://localhost:8080/graphql
Content-Type: application/json

{"query":"query test{\n  hello(string: \"München\")\n}\n","variables":null,"operationName":"test"}


### Output of `uname -a` or `ver`

### Output of `java -version`
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)
### Quarkus version or git rev
2.0.1.Final

Problem could be here:

io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler#readBody

return new String(bytes);

### PR DESCRIPTION
**Pull request by phillip-kruger**
Fix #18521
And also allow setting of the required encoding in the `Accept` header as per spec:

https://github.com/graphql/graphql-over-http/blob/main/spec/GraphQLOverHTTP.md#body

Signed-off-by:Phillip Kruger <phillip.kruger@gmail.com>

### CODE REVIEW

**Review by jmartisk — CHANGES_REQUESTED** [review]
I verified clients providing/requesting specific charsets in JVM mode, but it's not working in native mode - when I send a request with CP1250 encoding, I get

```
java.nio.charset.UnsupportedCharsetException: cp1250
	at java.nio.charset.Charset.forName(Charset.java:529)
	at io.vertx.core.buffer.impl.BufferImpl.toString(BufferImpl.java:100)
	at io.vertx.ext.web.impl.RoutingContextImpl.getBodyAsString(RoutingContextImpl.java:286)
	at io.vertx.ext.web.impl.RoutingContextDecorator.getBodyAsString(RoutingContextDecorator.java:166)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.readBody(SmallRyeGraphQLExecutionHandler.java:182)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.getJsonObjectFromBody(SmallRyeGraphQLExecutionHandler.java:163)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.handlePost(SmallRyeGraphQLExecutionHandler.java:88)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.doHandle(SmallRyeGraphQLExecutionHandler.java:69)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLAbstractHandler.handleWithIdentity(SmallRyeGraphQLAbstractHandler.java:66)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLAbstractHandler.handle(SmallRyeGraphQLAbstractHandler.java:48)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLAbstractHandler.handle(SmallRyeGraphQLAbstractHandler.java:23)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:160)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:96)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:158)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:481)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2442)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1476)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)

```

This can be fixed by producing a `NativeImageEnableAllCharsetsBuildItem`. Not sure how much of a performance impact it has (it seems to increase the native binary size by ~6 MB for me), so maybe this could be controlled by a build-time config property? And if that property is false, we would only support UTF8, and if the client wants to work with something else, then reject it?

Also I could imagine a test where a client requests something with a non-UTF8 charset (in the Accept header) and then verifies that the response is encoded that way..

**Comment by phillip-kruger** [comment]
I wonder if cp1250 is supported at all ?? (in java ?) Did you try any others ?

**Comment by jmartisk** [comment]
In JVM mode, CP1250 works.
Aaaa, I missed that there is a general `quarkus.native.add-all-charsets` property, that should resolve the problem I mentioned

**Review by jmartisk — APPROVED** [review]
Ok, no need for a new config property, setting `quarkus.native.add-all-charsets` resolves the problem. In that case the only thing missing for me is a small test, I'm +1'ing this

**Comment by phillip-kruger** [comment]
A test for another encoding ?

**Comment by jmartisk** [comment]
Yes, like something where a client calls a Query with `Accept: application/json;charset=CP1250`, the server responds with something simple but containing special characters, and the client then verifies that it has the right encoding?

**Comment by phillip-kruger** [comment]
Ok fair, let me add that

**Comment by phillip-kruger** [comment]
@jmartisk - added tests, once ci complete I think we can merge ?

File: extensions/smallrye-graphql/deployment/src/test/java/io/quarkus/smallrye/graphql/deployment/GraphQLTest.java [hunk 1]
```diff
@@ -193,6 +250,7 @@ public void testContext() {
     private static Map<String, String> configuration() {
         Map<String, String> m = new HashMap<>();
         m.put("quarkus.smallrye-graphql.events.enabled", "true");
+        m.put("quarkus.native.add-all-charsets", "true");
```
Comment (jmartisk) [inline extensions/smallrye-graphql/deployment/src/test/java/io/quarkus/smallrye/graphql/deployment/GraphQLTest.java:253]: If I'm not mistaken unit tests don't support native mode, this would be only needed inside `integration-tests`

**Review by jmartisk — CHANGES_REQUESTED** [review]

**Comment by phillip-kruger** [comment]
Thanks @jmartisk !

**Review by jmartisk — APPROVED** [review]
