### PR TITLE
Prevent non-public classes of method params from breaking interceptor handling

### LINKED ISSUE #18477: Upgrade to 1.13.0.Final and above causes Cannot transform java.util.concurrent.ThreadPoolExecutor as its containing application archive could not be found
## Describe the bug
After increasing version from 1.12.2.Final to 1.13.0.Final and higher the application will not startup correctly.
`WARN  [io.qua.dep.ste.ClassTransformingBuildStep] (build-54) Cannot transform java.util.concurrent.ThreadPoolExecutor as its containing application archive could not be found.`

We use Quartz (cluster mode) for scheduling tasks among pods and java.util.concurrent.ScheduledThreadPoolExecutor to execute tasks for every pod.

### Expected behavior
App starts correctly and schedules and executes first task.

### Actual behavior
Application starts up and throws warning 
`WARN  [io.qua.dep.ste.ClassTransformingBuildStep] (build-54) Cannot transform java.util.concurrent.ThreadPoolExecutor as its containing application archive could not be found.`
Flyway Migration continues successfully. Then the first task is to be scheduled and application crashes showing below stack trace.

## To Reproduce

1.  Download [reproducer.zip](https://github.com/quarkusio/quarkus/files/6776107/reproducer.zip)
2. run mvn clean quarkus:dev
3. will produce error as described
4. Modify POM.XML  <quarkus.platform.version>**1.12.2.Final**</quarkus.platform.version>
5. run mvn clean quarkus:dev
6. Task is executed and new task is scheduled

### Configuration
```properties
# Add your application.properties here, if applicable.

```

### Screenshots
(If applicable, add screenshots to help explain your problem.)

### Output of `uname -a` or `ver`
`Darwin XXXXX 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64`

### Output of `java -version`
`openjdk version "11.0.7" 2020-04-14 LTS
OpenJDK Runtime Environment Zulu11.39+15-CA (build 11.0.7+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.39+15-CA (build 11.0.7+10-LTS, mixed mode)`

### Quarkus version or git rev
Working: up to and incl. 1.12.2.Final
Not Working starting with 1.13.0.Final up to 2.0.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
`Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: /usr/local/Cellar/maven/3.8.1/libexec
Java version: 11.0.7, vendor: Azul Systems, Inc., runtime: /Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home
Default locale: de_DE, platform encoding: UTF-8
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"`

## Additional context
Stacktrace:
`ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile dev): java.lang.IllegalAccessError: failed to access class java.util.concurrent.ThreadPoolExecutor$Worker from class com.bmw.MyThreadExecutor_Subclass (java.util.concurrent.ThreadPoolExecutor$Worker is in module java.base of loader 'bootstrap'; com.bmw.MyThreadExecutor_Subclass is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @36361ddb)
        at com.bmw.MyThreadExecutor_Subclass.<init>(MyThreadExecutor_Subclass.zig:860)
        at com.bmw.MyThreadExecutor_Bean.create(MyThreadExecutor_Bean.zig:236)
        at com.bmw.MyThreadExecutor_Bean.create(MyThreadExecutor_Bean.zig:297)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:96)
        at io.quarkus.arc.impl.AbstractSharedContext.access$000(AbstractSharedContext.java:14)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
        at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
        at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:17)
        at com.bmw.MyThreadExecutor_ClientProxy.arc$delegate(MyThreadExecutor_ClientProxy.zig:67)
        at com.bmw.MyThreadExecutor_ClientProxy.scheduleDataFileTask(MyThreadExecutor_ClientProxy.zig:2056)
        at com.bmw.AppLifecycleBean.onStart(AppLifecycleBean.java:26)
        at com.bmw.AppLifecycleBean_Subclass.onStart$$superaccessor2(AppLifecycleBean_Subclass.zig:340)
        at com.bmw.AppLifecycleBean_Subclass$$function$$2.apply(AppLifecycleBean_Subclass$$function$$2.zig:33)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:63)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(InvocationInterceptor_Bean.zig:521)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
        at com.bmw.AppLifecycleBean_Subclass.onStart(AppLifecycleBean_Subclass.zig:297)
        at com.bmw.AppLifecycleBean_Observer_onStart_fd71b5e0b207b7d1ef838b94eaeff75e52b8f463.notify(AppLifecycleBean_Observer_onStart_fd71b5e0b207b7d1ef838b94eaeff75e52b8f463.zig:147)
        at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:283)
        at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:268)
        at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:70)
        at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:128)
        at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:97)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(LifecycleEventsBuildStep$startupEvent1144526294.zig:87)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(LifecycleEventsBuildStep$startupEvent1144526294.zig:40)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:1092)
        at io.quarkus.runtime.Application.start(Application.java:90)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:100)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.runner.bootstrap.StartupActionImpl$3.run(StartupActionImpl.java:134)
        at java.base/java.lang.Thread.run(Thread.java:834)
`

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #18477

### CODE REVIEW

**Review by mkouba — COMMENTED** [review]
Shall we have a test? ;-)

**Comment by geoand** [comment]
Sure yeah, I'll add one soon :)

**Comment by geoand** [comment]
> Shall we have a test? ;-)

Done

File: independent-projects/arc/tests/src/test/java/io/quarkus/arc/test/interceptors/methodargs/MethodArgsInterceptionTest.java [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+        Counter counter = container.instance(Counter.class).get();
+
+        counter.reset();
+        ExampleResource exampleResource = container.instance(ExampleResource.class).get();
+
+        assertEquals("first,second", exampleResource.create(List.of("first", "second")));
+        assertEquals(1, counter.get());
+
+        assertEquals("NotPublic{}", exampleResource.otherCreate(new ExampleResource.NotPublic()));
+        assertEquals(1, counter.get()); // the interceptor should have been called because the method argument is not public
```
Comment (mkouba) [inline independent-projects/arc/tests/src/test/java/io/quarkus/arc/test/interceptors/methodargs/MethodArgsInterceptionTest.java:31]: Hm, should or should not be called? ;-)

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Methods.java [hunk 2]
```diff
@@ -505,6 +509,20 @@ public boolean test(MethodInfo method) {
...
             }
+
+            List<Type> parameters = method.parameters();
+            if (!parameters.isEmpty() && (beanArchiveIndex != null)) {
+                for (Type type : parameters) {
+                    ClassInfo parameterClassInfo = beanArchiveIndex.getClassByName(type.name());
+                    if (parameterClassInfo == null) {
+                        continue; // hope for the best
+                    }
+                    if (!Modifier.isPublic(parameterClassInfo.flags())) {
```
Comment (mkouba) [inline independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Methods.java:520]: Hm, I'm not really sure this is the correct fix. If we go this way then we should probably at least log a warning. But I'm not quite sure that only public param classes are acceptable. What about package-private param classes? These should be probably OK because the generated subclass has the same package. 

@manovotn Do you remember what Weld does in similar cases?

File: independent-projects/arc/tests/src/test/java/io/quarkus/arc/test/interceptors/methodargs/MethodArgsInterceptionTest.java (hunk 1 above)
Comment (geoand) [reply independent-projects/arc/tests/src/test/java/io/quarkus/arc/test/interceptors/methodargs/MethodArgsInterceptionTest.java]: You are absolutely right, fixed

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Methods.java (hunk 2 above)
Comment (geoand) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Methods.java:520]: I thought about this as well. We could I guess check if the package of the class to which the method belongs is the same as the package of the parameter's class if that class is package-private.

But I'll hold off until we know what Weld does

Comment (manovotn) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Methods.java:520]: @mkouba @geoand sorry for the delay, below are my thoughts on this.

> These should be probably OK because the generated subclass has the same package.

Yea, this should be fine unless we have some edge cases where we have to create subclasses into dedicated (different) packages.

> Do you remember what Weld does in similar cases?

I don't remember so I wrote a similar test to what Georgios has here and Weld executes that with interception just fine.

Comment (geoand) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Methods.java:520]: Thanks for the info @manovotn

OK, so basically Weld allows parameters whose class is package private parameters and use the same package, correct?

I'll update the PR accordingly

Comment (mkouba) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Methods.java:520]: > I don't remember so I wrote a similar test to what Georgios has here and Weld executes that with interception just fine.

And for a private parameter type?

Ok, so I think that we should ignore and log a warning only for a `private` parameter type. WDYT?

Comment (manovotn) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Methods.java:520]: > And for a private parameter type?

That requires a somewhat awkward setup to be able to reference that type and pass it as an arg. into the intercepted method. But yes, Weld will allow you to do that as well and interception will work.

Comment (mkouba) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Methods.java:520]: Hmm, actually we could try to fallback to reflection as well... But let's create a separate issue for that.

Comment (geoand) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Methods.java:520]: I think what I pushed now covers the common cases - it certainly handles the original issue :)

**Review by manovotn — APPROVED** [review]
I think this looks good now.
Let's track the reflection fallback for private args in a separate issue.

**Comment by geoand** [comment]
> I think this looks good now.
> Let's track the reflection fallback for private args in a separate issue.

I opened https://github.com/quarkusio/quarkus/issues/18602

File: independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Methods.java [hunk 3]
```diff
@@ -505,10 +513,40 @@ public boolean test(MethodInfo method) {
...
+
             // Note that we intentionally do not skip final methods here - these are handled later
             return false;
         }
 
+        private String determinePackage(DotName dotName) {
+            if (dotName.isInner()) {
+                dotName = dotName.prefix();
+            }
+            return dotName.prefix() == null ? "" : dotName.prefix().toString();
```
Comment (mkouba) [inline independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Methods.java:547]: I think that this will not work for names created via `DotName.createSimple()`: _"Simple DotName variants never have a prefix"_.

Comment (geoand) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Methods.java:547]: What would the proper use be in that case?

Comment (mkouba) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Methods.java:547]: `io.quarkus.arc.processor.DotNames.packageName(DotName)` should work although the impl is pretty "simplistic" :-)

Comment (geoand) [reply independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Methods.java:547]: I was not aware of it, I'll put it on the TODO list :)
