### PR TITLE
Micrometer exemplars on HTTP

### LINKED ISSUE #43845: Exemplars are not recorded for metric `http_server_requests*`
### Describe the bug

I'm running Keycloak with Metrics and OpenTelemetry tracing enabled. 

When running HTTP 1.x requests, I find that the metrics are recorded for `http_server_requests_*`, but no exemplars are recorded. Other metrics have exemplars. 

NOTE: I retrieved metrics from my application using 

```
curl http://localhost:9000/metrics
```

as when running with Chrome, it never returned the OpenMetrics format with the Exemplars, but always the old text/plain Prometheus format (possibly due to content negotiation in the headers). 

### Expected behavior

I expect exemplars to be provided for http server metrics.

```
http_server_requests_seconds_count{method="GET",outcome="SUCCESS",status="204",uri="/realms/{realm}/protocol/{protocol}/login-status-iframe.html/init"} 2.0 # {span_id="cc258ebf850c7ec8",trace_id="39750627ed1138e074b6256816bfa845"} 1.0 1728839669.614
```

### Actual behavior

They are missing

```
http_server_requests_seconds_countmethodGEToutcomeREDIRECTIONstatus302uri/admin 3.0
http_server_requests_seconds_summethodGEToutcomeREDIRECTIONstatus302uri/admin 0.0324834
http_server_requests_seconds_countmethodGEToutcomeSUCCESSstatus204uri/realms/{realm}/protocol/{protocol}/login-status-iframe.html/init 7.0
```

### How to Reproduce?

* Start Keycloak 26.0.0 and enable Metrics and OpenTelementry
* Login to issue some HTTP requests
* Retrieve metrics from the metrics endpoint using CURL

### Output of `uname -a` or `ver`

Windows 11

### Output of `java -version`

JDK 17

### Quarkus version or git rev

3.15.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

I found that `OpentelemetryExemplarSamplerProvider` expects the current trace context to be present in the Vert.x context:

https://github.com/quarkusio/quarkus/blob/main/extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/export/OpentelemetryExemplarSamplerProvider.java#L25-L40

Unfortunately Vert.x doesn't set the context:

https://github.com/eclipse-vertx/vert.x/blob/1e2fdf820be9628af2576c0f32828802111855b1/vertx-core/src/main/java/io/vertx/core/http/impl/Http1xServerConnection.java#L265-L270

I assume this can be fixed by changing Vert.x to set the context. I'll open an issue there to suggest a change. I'll post a link to the issue here. 

Happy for other pointers and ideas from the Quarkus team. Thanks!

### PR DESCRIPTION
**Pull request by brunobat**
Fixes #43845

### CODE REVIEW

**Comment by brunobat** [comment]
CC @ahus1

**Comment by ahus1** [comment]
Thank you for this PR, @brunobat! These code changes are beyond my Vert.x/Quarkus skills, thank you for looking into this! I see what the test case is doing, and that part I can understand and it looks good to me.

File: extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/export/exemplars/OpenTelemetryExemplarContextUnwrapper.java [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+        }
+
+        io.opentelemetry.context.Context oldContext = QuarkusContextStorage.INSTANCE.current();
+        try (Scope scope = QuarkusContextStorage.INSTANCE.attach(newContext)) {
+            return methodReference.apply(parameter);
+        } finally {
+            if (oldContext != null) {
+                QuarkusContextStorage.INSTANCE.attach(oldContext);
+            }
+        }
```
Comment (tsegismont) [inline extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/export/exemplars/OpenTelemetryExemplarContextUnwrapper.java:33]: Is this really necessary? I thought that would be done automatically when closing the scope returned by `attach(newContext)`.

**Review by tsegismont — APPROVED** [review]
LGTM with one question about the unwrapper implementation.

File: extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/export/exemplars/OpenTelemetryExemplarContextUnwrapper.java (hunk 1 above)
Comment (brunobat) [reply extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/export/exemplars/OpenTelemetryExemplarContextUnwrapper.java:33]: I'm just making sure that the previous scope continues after we do this operation.

Comment (tsegismont) [reply extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/export/exemplars/OpenTelemetryExemplarContextUnwrapper.java:33]: I understand the intent, but I'm wondering if this isn't redundant with the action triggered by the closing of the scope.

Comment (brunobat) [reply extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/export/exemplars/OpenTelemetryExemplarContextUnwrapper.java:33]: @cescoffier What do you think?

Comment (tsegismont) [reply extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/export/exemplars/OpenTelemetryExemplarContextUnwrapper.java:33]: For the record, if this patch is applied:

```patch
Index: extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/export/exemplars/OpenTelemetryExemplarContextUnwrapper.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/export/exemplars/OpenTelemetryExemplarContextUnwrapper.java b/extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/export/exemplars/OpenTelemetryExemplarContextUnwrapper.java
--- a/extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/export/exemplars/OpenTelemetryExemplarContextUnwrapper.java	(revision a9bb1201605b10d969e2fd960cee88fe29dd24fe)
+++ b/extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/export/exemplars/OpenTelemetryExemplarContextUnwrapper.java	(date 1730121975953)
@@ -1,12 +1,12 @@
 package io.quarkus.micrometer.runtime.export.exemplars;
 
-import java.util.function.Function;
-
-import jakarta.enterprise.context.Dependent;
-
 import io.opentelemetry.context.Context;
 import io.opentelemetry.context.Scope;
 import io.quarkus.opentelemetry.runtime.QuarkusContextStorage;
+import jakarta.enterprise.context.Dependent;
+
+import java.util.Objects;
+import java.util.function.Function;
 
 @Dependent
 public class OpenTelemetryExemplarContextUnwrapper implements OpenTelemetryContextUnwrapper {
@@ -23,13 +23,13 @@
             return methodReference.apply(parameter);
         }
 
-        io.opentelemetry.context.Context oldContext = QuarkusContextStorage.INSTANCE.current();
-        try (Scope scope = QuarkusContextStorage.INSTANCE.attach(newContext)) {
-            return methodReference.apply(parameter);
-        } finally {
-            if (oldContext != null) {
-                QuarkusContextStorage.INSTANCE.attach(oldContext);
-            }
+        io.opentelemetry.context.Context expected = QuarkusContextStorage.INSTANCE.current();
+        R applied;
+        try (Scope ignored = QuarkusContextStorage.INSTANCE.attach(newContext)) {
+            assert QuarkusContextStorage.INSTANCE.current() != null;
+            applied = methodReference.apply(parameter);
         }
+        assert Objects.equals(expected, QuarkusContextStorage.INSTANCE.current());
+        return applied;
     }
 }
```

The test still passes (assertions are correct).

File: extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/export/exemplars/OpenTelemetryExemplarContextUnwrapper.java [hunk 2]
```diff
@@ -0,0 +1,35 @@
...
+
+import io.opentelemetry.context.Context;
+import io.opentelemetry.context.Scope;
+import io.quarkus.opentelemetry.runtime.QuarkusContextStorage;
+
+@Dependent
+public class OpenTelemetryExemplarContextUnwrapper implements OpenTelemetryContextUnwrapper {
+
+    @Override
+    public <P, R> R executeInContext(Function<P, R> methodReference, P parameter, io.vertx.core.Context requestContext) {
```
Comment (cescoffier) [inline extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/export/exemplars/OpenTelemetryExemplarContextUnwrapper.java:15]: is requestContext a duplicated context? If it's a root context that can be problematic.

File: extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/export/exemplars/OpenTelemetryExemplarContextUnwrapper.java [hunk 3]
```diff
@@ -0,0 +1,35 @@
...
+        if (requestContext == null) {
+            return methodReference.apply(parameter);
+        }
+
+        Context newContext = QuarkusContextStorage.getContext(requestContext);
+
+        if (newContext == null) {
```
Comment (cescoffier) [inline extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/export/exemplars/OpenTelemetryExemplarContextUnwrapper.java:22]: IS it really possible? Or should it be considered as a failure (or at least logged)

File: extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/export/exemplars/OpenTelemetryExemplarContextUnwrapper.java (hunk 1 above)
Comment (cescoffier) [reply extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/export/exemplars/OpenTelemetryExemplarContextUnwrapper.java:33]: It should not be necessary as the closing of the scope restores the previous context in the duplicated context.

File: extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/export/exemplars/OpenTelemetryExemplarContextUnwrapper.java (hunk 3 above)
Comment (cescoffier) [reply extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/export/exemplars/OpenTelemetryExemplarContextUnwrapper.java:22]: It will be checked in the `attach` method - but I'm wondering if we need to do it before.

**Review by cescoffier — CHANGES_REQUESTED** [review]

File: extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/export/exemplars/OpenTelemetryExemplarContextUnwrapper.java (hunk 2 above)
Comment (tsegismont) [reply extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/export/exemplars/OpenTelemetryExemplarContextUnwrapper.java:15]: It should be, it's the context bound to a particular HTTP Request

File: extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/export/exemplars/OpenTelemetryExemplarContextUnwrapper.java (hunk 3 above)
Comment (tsegismont) [reply extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/export/exemplars/OpenTelemetryExemplarContextUnwrapper.java:22]: It is totally possible when the metrics SPI method is invoked directly from the EL thread (e.g. when reporting bytes sent metrics)

File: extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/export/exemplars/OpenTelemetryExemplarContextUnwrapper.java (hunk 1 above)
Comment (brunobat) [reply extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/export/exemplars/OpenTelemetryExemplarContextUnwrapper.java:33]: It is a duplicated context:
Screenshot 2024-11-13 at 09 52 21

**Comment by brunobat** [comment]
@cescoffier should be fixed now.

**Review by cescoffier — APPROVED** [review]

**Comment by tsegismont** [comment]
Thank you @brunobat !

**Comment by ahus1** [comment]
@brunobat - thank's a lot, looking forward to try it out!

**Comment by brunobat** [comment]
@gsmet There are request to backport this PR to 3.15. Will prepare a PR.

**Comment by gsmet** [comment]
To clarify our plan after the backport meeting: the idea is to let it bake a bit more in current releases before backporting it for 3.15.4 (probably released around the end of March).

If you have a strong objection about this plan, please let us know :).
