### PR TITLE
Fix cache exception handling

### LINKED ISSUE #13399: Cache exception handling broken in Quarkus 1.10.0.Final
**Describe the bug**
When the cache value computation throws an exception a non-completed `CompletableFuture` value is written to the cache. The next time a client fetches the value for the same key from the cache the call will block forever in `CompletableFuture#get()` since the value was not removed from the cache in the exception handling.

For a simple reproducer see https://github.com/knutwannheden/caching-bug.

In Quarkus 1.10.0.CR1 this problem didn't exist and is thus probably caused by https://github.com/quarkusio/quarkus/commit/668ff4301ecd99c65bd720cc42d50c8104054709 which was integrated as part of the 1.10.0.Final release.

**Expected behavior**
An exception thrown by method annotated with `@CacheResult` should not have any impact on subsequent calls.

**Actual behavior**
An exception thrown by method annotated with `@CacheResult` causes subsequent calls to this method (for the same cache key) to block. Here is the corresponding stack trace for the blocking call:

```
"executor-thread-1@6796" daemon prio=5 tid=0x54 nid=NA waiting
java.lang.Thread.State: WAITING
at jdk.internal.misc.Unsafe.park(Unsafe.java:-1)
at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1796)
at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3128)
at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1823)
at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1998)
at io.quarkus.cache.runtime.CacheResultInterceptor.intercept(CacheResultInterceptor.java:48)
at io.quarkus.cache.runtime.CacheResultInterceptor_Bean.intercept(CacheResultInterceptor_Bean.zig:334)
at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
...
```

**To Reproduce**
Run unit test in https://github.com/knutwannheden/caching-bug.

1. git clone https://github.com/knutwannheden/caching-bug
2. cd caching-bug
3. ./mvnw verify

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Windows 10
 - Output of `java -version`: 11
 - Quarkus version or git rev: 1.10.0.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Maven 3.6.3

### PR DESCRIPTION
**Pull request by gwenneg**
Fixes #13399.

### CODE REVIEW

File: extensions/cache/runtime/src/main/java/io/quarkus/cache/runtime/caffeine/CaffeineCache.java [hunk 1]
```diff
@@ -68,9 +68,15 @@ public CaffeineCache(CaffeineCacheInfo cacheInfo) {
...
-            Object value = valueLoader.apply(key);
-            newCacheValue.complete(NullValueConverter.toCacheValue(value));
-            return unwrapCacheValue(newCacheValue);
+            try {
+                Object value = valueLoader.apply(key);
+                newCacheValue.complete(NullValueConverter.toCacheValue(value));
+                return unwrapCacheValue(newCacheValue);
+            } catch (Throwable t) {
+                cache.asMap().remove(key, newCacheValue);
+                newCacheValue.completeExceptionally(t);
```
Comment (gwenneg) [inline extensions/cache/runtime/src/main/java/io/quarkus/cache/runtime/caffeine/CaffeineCache.java:77]: @ben-manes I need your help with this line. When it is executed, Caffeine is logging a warning about an `Exception thrown during asynchronous load` (the old warning I already got rid of before). Why is this happening while the future was removed from the cache with the previous line?

Comment (ben-manes) [reply extensions/cache/runtime/src/main/java/io/quarkus/cache/runtime/caffeine/CaffeineCache.java:77]: I suppose because there is no way to remove a whenComplete callback. I didn’t think the put added the handler but would need to review the asMap code

Comment (ben-manes) [reply extensions/cache/runtime/src/main/java/io/quarkus/cache/runtime/caffeine/CaffeineCache.java:77]: Yes, this is due to the callback and that cannot be removed by the CompletableFuture api. There is no mechanism for the callback to be aware of the situation for how a removal occurred and to no-op. At best it can safeguard against multiple invocations. The [code](https://github.com/ben-manes/caffeine/blob/b95222ab4fbf4b01f34ea053522227cc4e3ee3e2/caffeine/src/main/java/com/github/benmanes/caffeine/cache/LocalAsyncCache.java#L187-L214) in question.

The logic in this callback is to try to update the entry's metadata (weight, expiration) on success, try to remove it on failure, and record the statistics. If the entry was replaced or removed prior to completion then the conditional writes fail, but the statistics are still valid so they are recorded. For example an in-progress load that is removed still counts towards the load time and having started due to a cache miss. Similarly, `LoadingCache.refresh(key)` might load but fail to replace the entry if it was explicit removed, such as after when the system of record was updated and the cache invalidated.

Trying to special case the logger to sometimes log and other times not based on guessing the likely user interaction is error prone. If the use-case is to warn because users forget to handle errors, an ignoring to log when an in-flight future was explicitly inserted doesn't somehow negate error handling. I would agree the cache isn't responsible for a user's error handling, but unfortunately real world code means we have to be mindful that most will forget and silently ignore production errors.

I suspect the cleanest solution is simply to disable the logger. That is a simple configuration or api call and matches how loggers are intended to be used. Otherwise, you will have to restore the workaround to suppress the error from the cache's perspective in order to silence this message.

Comment (gwenneg) [reply extensions/cache/runtime/src/main/java/io/quarkus/cache/runtime/caffeine/CaffeineCache.java]: Thanks for your very detailed answer @ben-manes!

I don't really like the idea of this extension changing the behavior of Caffeine application-wide, so I restored the workaround to suppress the warning.

Comment (ben-manes) [reply extensions/cache/runtime/src/main/java/io/quarkus/cache/runtime/caffeine/CaffeineCache.java]: That is true, except I thought (maybe incorrectly) that Quarkus shades Caffeine so it would only apply to your extension if you disable the logger at the shaded path? I might be completely wrong, in which case you're very much right.

**Comment by gwenneg** [comment]
@gsmet This PR fixes a regression in 1.10.0.Final, it must be included in the next release.

File: extensions/cache/runtime/src/main/java/io/quarkus/cache/runtime/caffeine/CaffeineCache.java (hunk 1 above)
Comment (gwenneg) [reply extensions/cache/runtime/src/main/java/io/quarkus/cache/runtime/caffeine/CaffeineCache.java]: You're probably right, I don't know everything about Quarkus and this specific feature is unknown to me. I'll see if I can find some information about it.

Comment (gsmet) [reply extensions/cache/runtime/src/main/java/io/quarkus/cache/runtime/caffeine/CaffeineCache.java]: We don't shade Caffeine.

Comment (gwenneg) [reply extensions/cache/runtime/src/main/java/io/quarkus/cache/runtime/caffeine/CaffeineCache.java]: Thanks @gsmet! Then the current fix is the good one.

File: extensions/cache/runtime/src/main/java/io/quarkus/cache/runtime/CacheResultInterceptor.java [hunk 2]
```diff
@@ -59,8 +60,15 @@ public Object apply(Object k) {
                 }
             }
 
-        } catch (CacheException e) {
-            if (e.getCause() instanceof Exception) {
+        } catch (ExecutionException e) {
+            if (e.getCause() instanceof CacheException) {
+                CacheException cacheException = (CacheException) e.getCause();
+                if (cacheException.getCause() instanceof Exception) {
```
Comment (gsmet) [inline extensions/cache/runtime/src/main/java/io/quarkus/cache/runtime/CacheResultInterceptor.java:66]: Not sure I understand this particular one?

It looks a bit like dark magic, we should at least add comments about what we're doing here.

**Review by gsmet — COMMENTED** [review]
Added a small question.

File: extensions/cache/runtime/src/main/java/io/quarkus/cache/runtime/CacheResultInterceptor.java (hunk 2 above)
Comment (gwenneg) [reply extensions/cache/runtime/src/main/java/io/quarkus/cache/runtime/CacheResultInterceptor.java:66]: It's not as dark as it seems :)

Exceptions happening during a cache computation are thrown from a `CompletableFuture` execution and are therefore encapsulated into an `ExecutionException` automatically. Since we use the functional interface `Function<Object, Object>` to pass the value loader to the cache, we also need to encapsulate any exception thrown during a cache computation into a `CacheException extends RuntimeException` because `Exception` cannot be thrown from a functional interface.

So if an `IOException` is thrown during a cache computation, it is encapsulated into a `CacheException` because of the functional interface used for the computation and again the `CacheException` is encapsulated into an `ExecutionException` because of the `CompletableFuture`.

This is the most likely scenario, but there are other possibilities as well (like the JVM throwing an Error) which are taken care of with a bunch of `else` blocks.

Comment (gwenneg) [reply extensions/cache/runtime/src/main/java/io/quarkus/cache/runtime/CacheResultInterceptor.java:66]: I will add comments btw.

Comment (gwenneg) [reply extensions/cache/runtime/src/main/java/io/quarkus/cache/runtime/CacheResultInterceptor.java:72]: @gsmet The exception handling code is now commented.

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Thanks!
