### PR TITLE
RESTEasy classic servlets - add RoutingContext to active request context

### LINKED ISSUE #30405: Quarkus Undertow doesn't work with blocking SecurityIdentityAugmentor
### Describe the bug

Found in versions: 2.15.0, 2.15.3

Extension used: [cdi, resteasy, resteasy-jsonb, security, servlet, smallrye-context-propagation, vertx]

In case that I have undertow together with some blocking security identity augmentor in the project, the authorized requests end with NullPointerException:

```
2023-01-12 11:58:26,226 ERROR [io.und.req.io] (executor-thread-0) Exception handling request a2892aab-b89a-40b8-943a-ddd34d3a9b68-1 to /bug/fruits: java.lang.NullPointerException: Cannot invoke "io.vertx.ext.web.RoutingContext.request()" because "routingContext" is null
	at io.quarkus.resteasy.runtime.ContextUtil.pushContext(ContextUtil.java:19)
	at io.quarkus.resteasy.runtime.ResteasyFilter$ResteasyResponseWrapper.service(ResteasyFilter.java:69)
	at io.quarkus.resteasy.runtime.ResteasyFilter$ResteasyResponseWrapper.sendError(ResteasyFilter.java:76)
	at io.undertow.servlet.handlers.DefaultServlet.doGet(DefaultServlet.java:172)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:503)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
```

There is no issue without undertow or with non blocking augmentor.

### Expected behavior

no exception shall be thrown

### Actual behavior

_No response_

### How to Reproduce?

I have created example [github project](https://github.com/myroch/quarkus-undertow-bug), just start it up in dev mode and try following request:
http://localhost:21380/bug/fruits
Basic Auth: admin/pass

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.15.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by michalvavrik**
fixes: #30405

Starting with Quarkus 2.13.0.Final request context may come activated instead of being activated by Undertow when `@ActivateRequestContext` is used. As `RestFilter` down the stream requires the routing event to be part of the current Vert.x context, NPE was thrown.

I failed to identify actual change (PR) that brings this behavior (no NPE in 2.12.3.Final), I'm out of ideas after inspecting all 2.13 changes in Security, Arc, Undertow, RESTEasy Classic and Vert.x HTTP, but I'm happy to look again if you have a good idea where to look.

### CODE REVIEW

**Review by cescoffier — APPROVED** [review]

**Comment by sberyozkin** [comment]
Hey @michalvavrik sorry I missed it, thanks. Clement approved so it is good to go, your update looks simple and makes sense, even though I'm not really familiar with Undertow and Vertx combination,  can you check please what happened with Sec tests ?

File: extensions/undertow/runtime/src/main/java/io/quarkus/undertow/runtime/UndertowDeploymentRecorder.java [hunk 1]
```diff
@@ -564,6 +564,11 @@ public T call(HttpServerExchange exchange, C context) throws Exception {
                         // Not sure what to do here
                         ManagedContext requestContext = beanContainer.requestContext();
                         if (requestContext.isActive()) {
+                            if (currentVertxRequest.getCurrent() == null && exchange != null
```
Comment (stuartwdouglas) [inline extensions/undertow/runtime/src/main/java/io/quarkus/undertow/runtime/UndertowDeploymentRecorder.java:567]: Can you add a comment about what is actually causing this condition? (i.e. what is activating the request scope without also setting the current request).

This seems fine, but I would like to understand why it is happening.

**Review by stuartwdouglas — CHANGES_REQUESTED** [review]

File: extensions/undertow/runtime/src/main/java/io/quarkus/undertow/runtime/UndertowDeploymentRecorder.java (hunk 1 above)
Comment (stuartwdouglas) [reply extensions/undertow/runtime/src/main/java/io/quarkus/undertow/runtime/UndertowDeploymentRecorder.java:567]: I don't really understand how @ActivateRequestContext in the augmentor could do this. It should be terminated after the invocation: https://github.com/stuartwdouglas/quarkus/blob/8398d79f770b7f5b7e1cb6c90397072cafee6264/independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl/ActivateRequestContextInterceptor.java#L131

Comment (michalvavrik) [reply extensions/undertow/runtime/src/main/java/io/quarkus/undertow/runtime/UndertowDeploymentRecorder.java:567]: Request context activated in the augmentor is terminated as you say, however when `io.quarkus.vertx.http.runtime.security.HttpAuthorizer#doPermissionCheck` is run, context snapshot is created from `SlowActiveContextState` (previously restored by `SlowCapturedContextState`) and at the moment when `ServletInitialHandler` handles request the state is active again. It's done by Smallrye Context Propagation and I can't tell whether this is expected.

I have limits in understanding of above-mentioned area, I can look deeper to context propagation on Thursday evening (or do required changes then), but if someone could give me a hint on expected behavior of context propagation I'd be grateful.

Comment (michalvavrik) [reply extensions/undertow/runtime/src/main/java/io/quarkus/undertow/runtime/UndertowDeploymentRecorder.java:567]: btw. you know it's down to the `@ActivateRequestContext` as if you comment it out, problem disappear.

Comment (michalvavrik) [reply extensions/undertow/runtime/src/main/java/io/quarkus/undertow/runtime/UndertowDeploymentRecorder.java:567]: Can't tell based on https://github.com/smallrye/smallrye-context-propagation whether this is expected behavior, but @FroMage @mkouba are maintainers of Smallrye Context Propagation extension. Could you kindly give me a hint whether what I describe in the comment above is expected, please?

Comment (manovotn) [reply extensions/undertow/runtime/src/main/java/io/quarkus/undertow/runtime/UndertowDeploymentRecorder.java:567]: > io.quarkus.vertx.http.runtime.security.HttpAuthorizer#doPermissionCheck is run, context snapshot is created from SlowActiveContextState 

SR CP just propagates (by default) all contexts when asked to - for CDI this means req. scope if it was active. So I guess the question is whether it's expected that someone activates the context at that point? Also note that the `ActivateRequestContextInterceptor` can still terminate the req. context on the original thread (in terms of its state - the beans it had) and so any thread that CP propagates it into would then seem to have req, context active but would in fact be a fresh instance of req. context.

Comment (michalvavrik) [reply extensions/undertow/runtime/src/main/java/io/quarkus/undertow/runtime/UndertowDeploymentRecorder.java:567]: > SR CP just propagates (by default) all contexts when asked to - for CDI this means req. scope if it was active. So I guess the question is whether it's expected that someone activates the context at that point?

reproducer is more or less c&p of docs example https://quarkus.io/guides/security-customization#security-identity-customization including request context activation, so IMO yes

> Also note that the `ActivateRequestContextInterceptor` can still terminate the req. context on the original thread (in terms of its state - the beans it had) and so any thread that CP propagates it into would then seem to have req, context active but would in fact be a fresh instance of req. context.

@manovotn that's exactly what happens, thank you for taking your time to answer

Comment (michalvavrik) [reply extensions/undertow/runtime/src/main/java/io/quarkus/undertow/runtime/UndertowDeploymentRecorder.java:567]: @stuartwdouglas I added comment as you suggested, should the comment be improved, just let me know.

**Review by stuartwdouglas — APPROVED** [review]
