### PR TITLE
Make REST Data Panache work properly with id fields not named 'id'

### LINKED ISSUE #25920: REST Data Panache with ResteasyReactive: field 'id' was not found error
### Describe the bug

When using REST Data Panache with ResteasyReactive for entity that has an id field not named "id" application crashes on start with exception: 

```
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.resteasy.reactive.links.deployment.LinksProcessor#initializeLinksProvider threw an exception: java.lang.RuntimeException: Class 'java.lang.Object' field 'id' was not found
	at io.quarkus.resteasy.reactive.links.deployment.LinksProcessor.getFieldInfo(LinksProcessor.java:146)
	at io.quarkus.resteasy.reactive.links.deployment.LinksProcessor.getFieldInfo(LinksProcessor.java:144)
	at io.quarkus.resteasy.reactive.links.deployment.LinksProcessor.getFieldInfo(LinksProcessor.java:144)
	at io.quarkus.resteasy.reactive.links.deployment.LinksProcessor.implementPathParameterValueGetters(LinksProcessor.java:103)
	at io.quarkus.resteasy.reactive.links.deployment.LinksProcessor.initializeLinksProvider(LinksProcessor.java:65
```

example entity:
```java
public class ExampleEntity extends PanacheEntityBase {
    @Id
    long companyId;
}
```
example resource:
```java
@ResourceProperties(path =  "/example")
public interface ExampleResource extends PanacheEntityResource<ExampleEntity, Long> {
}
```
Data Panache generate resource with path "/example/{id}" so `io.quarkus.resteasy.reactive.links.deployment.LinksProcessor#getFieldInfo` scans for field "id", ignoring the fact that entity can have id field with whatever name but with annotation `@Id`

### Expected behavior

REST Data Panache with ResteasyReactive should work with an entity with id field not named "id" but annotated with `@Id`

### Actual behavior

_No response_

### How to Reproduce?

use 
```
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-hibernate-orm-rest-data-panache</artifactId>
        </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-reactive</artifactId>
    </dependency>
```
example entity:
```java
public class ExampleEntity extends PanacheEntityBase {
    @Id
    long companyId;
}
```
example resource:
```java
@ResourceProperties(path =  "/example")
public interface ExampleResource extends PanacheEntityResource<ExampleEntity, Long> {
}
```

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.9.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #25920

### CODE REVIEW

File: extensions/resteasy-reactive/quarkus-resteasy-reactive-links/deployment/src/main/java/io/quarkus/resteasy/reactive/links/deployment/LinksProcessor.java [hunk 1]
```diff
@@ -117,19 +121,49 @@ private RuntimeValue<GetterAccessorsContainer> implementPathParameterValueGetter
...
+                        // this is a special case where we want to go through the fields of the class
+                        // and see if any is annotated with any sort of @Id annotation
+                        // N.B. as this module does not depend on any other module that could supply this @Id annotation
+                        // (like Panache), we need this general lookup
+                        FieldInfoSupplier byIdAnnotation = new FieldInfoSupplier(
+                                c -> {
+                                    for (FieldInfo field : c.fields()) {
+                                        List<AnnotationInstance> annotationInstances = field.annotations();
+                                        for (AnnotationInstance annotationInstance : annotationInstances) {
+                                            if (annotationInstance.name().toString().toLowerCase(Locale.ROOT)
```
Comment (Sgitario) [inline extensions/resteasy-reactive/quarkus-resteasy-reactive-links/deployment/src/main/java/io/quarkus/resteasy/reactive/links/deployment/LinksProcessor.java:143]: I think that this logic is too wide, maybe we should be more strict by using the dot name of `javax.persistence.Id`.

Comment (geoand) [reply extensions/resteasy-reactive/quarkus-resteasy-reactive-links/deployment/src/main/java/io/quarkus/resteasy/reactive/links/deployment/LinksProcessor.java:143]: I thought about it and I really don't know. If we did that, it would pretty much mean that this can only be used with Hibernate REST Data Panache.

Comment (geoand) [reply extensions/resteasy-reactive/quarkus-resteasy-reactive-links/deployment/src/main/java/io/quarkus/resteasy/reactive/links/deployment/LinksProcessor.java:143]: I guess we can start by being strict

Comment (geoand) [reply extensions/resteasy-reactive/quarkus-resteasy-reactive-links/deployment/src/main/java/io/quarkus/resteasy/reactive/links/deployment/LinksProcessor.java]: Done

File: extensions/resteasy-reactive/quarkus-resteasy-reactive-links/deployment/src/main/java/io/quarkus/resteasy/reactive/links/deployment/LinksProcessor.java [hunk 2]
```diff
@@ -117,19 +120,48 @@ private RuntimeValue<GetterAccessorsContainer> implementPathParameterValueGetter
...
+                        // this is a special case where we want to go through the fields of the class
+                        // and see if any is annotated with any sort of @Id annotation
+                        // N.B. as this module does not depend on any other module that could supply this @Id annotation
+                        // (like Panache), we need this general lookup
+                        FieldInfoSupplier byIdAnnotation = new FieldInfoSupplier(
+                                c -> {
+                                    for (FieldInfo field : c.fields()) {
+                                        List<AnnotationInstance> annotationInstances = field.annotations();
+                                        for (AnnotationInstance annotationInstance : annotationInstances) {
+                                            if (annotationInstance.name().toString().endsWith("persistence.Id")) {
```
Comment (geoand) [inline extensions/resteasy-reactive/quarkus-resteasy-reactive-links/deployment/src/main/java/io/quarkus/resteasy/reactive/links/deployment/LinksProcessor.java:142]: Done line this in order to avoid having to change when we move to jakarta

Comment (gastaldi) [reply extensions/resteasy-reactive/quarkus-resteasy-reactive-links/deployment/src/main/java/io/quarkus/resteasy/reactive/links/deployment/LinksProcessor.java:142]: Maybe comparing to `EntityClassHelper.JAVAX_PERSISTENCE_ID` could avoid surprises but I think this works

**Review by gastaldi — APPROVED** [review]

**Comment by geoand** [comment]
For the time being we don't want to add any extra dependencies, so let's keep it as is
